### ISSUE TITLE
Add autocompletion when connecting methods to signals via code

### ISSUE THREAD

**Issue by nubels** [godotengine/godot-proposals#10013]
### Describe the project you are working on

A 3D action RPG.

### Describe the problem or limitation you are having in your project

When connecting function to signals via code, you have to write repetitive boilerplate code and you need to look up the parameters of the specific signal in case you forgot them. It's a very repetitive task that could use some UX improvements.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement a feature that automatically creates a function and fills in the argument of the connect function. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When accepting the `connect` autocompletion suggestion, automatically fill in the callable argument and create a function that matches the Godot style guide. This function should have all the parameters of the signals as arguments.

https://github.com/godotengine/godot-proposals/assets/81755541/fc449a2f-ea72-4fdc-9e21-cd1ebae0b76c

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe this will be used often and I don't think there's a work around with a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?

Connecting methods to signals via code is very common. This saves a of of time because you don't need to write boilerplate code or look up signal arguments when connecting methods to signals.

**Comment by Calinou** [comment]
For future reference, this is a duplicate of https://github.com/godotengine/godot-proposals/issues/8714.
