### ISSUE TITLE
Add a function to copy the position and rotation of the camera editor

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot-proposals#10011]
### Describe the project you are working on

3D Game

### Describe the problem or limitation you are having in your project

You can't apply the editor's camera view to Camera3D; Unity had an option where the camera could exactly copy the position and rotation of the editor's camera in space, which Godot lacks

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It is necessary to add some kind of key combination so that the 3D nodes can accurately copy the position and rotation of the editor's camera; this very quickly helps to set up the position for the cameras, especially when there are many of them

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same as above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is often used, of course you can write a plugin, but it’s not for beginners

### Is there a reason why this should be core and not an add-on in the asset library?

This is a very simple function, and very useful in the development of 3D projects, it should become part of the engine

**Comment by KoBeWi** [comment]
You have that option at the bottom of Perspective menu.

**Comment by JekSun97** [comment]
> You have that option at the bottom of Perspective menu.

Thank you! I checked this before creating a topic, but didn't find anything, apparently I didn't search well.
