### ISSUE TITLE
Add Nested Type Collections

### ISSUE THREAD

**Issue by DDAN-17** [godotengine/godot-proposals#10016]
### Describe the project you are working on

A maze generator

### Describe the problem or limitation you are having in your project

To represent the maze, I need to use an Array of Arrays of Directionalized Connections, but according to an error, Nested typed collections are not supported.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add nested type collections

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would just work

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This should be a core feature

**Comment by dalexeev** [comment]
Please see the rules in the README (on the main page of this repository):

> You have two options to make a suggestion for the future of the engine. You can either open a proposal [**Issue**](https://github.com/godotengine/godot-proposals/issues/new/choose), or you can create an open [**Discussion**](https://github.com/godotengine/godot-proposals/discussions/new).
>
> Proposal *issues* are required to explain in technical detail how the suggested change should be implemented. It is also preferred that the submitter of a proposal is ready to implement it if it was approved. If you have a more general idea for a feature but are not well versed in Godot's architecture or do not possess the necessary knowledge to implement it in the engine, feel free to open a [*discussion*](https://github.com/godotengine/godot-proposals/discussions/new) instead of an [*issue*](https://github.com/godotengine/godot-proposals/issues/new/choose).

If you are not going to supplement the proposal with implementation details, I can convert it into a discussion.

**Comment by DDAN-17** [comment]
I have already converted it to a discussion.

**Comment by dalexeev** [comment]
* See #10022.
