### ISSUE TITLE
Support exporting multiple architecture specific Android APKs in a single export

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot-proposals#1002]
**Describe the project you are working on:**
Mobile game

**Describe the problem or limitation you are having in your project:**
Godot has support for 4 different architectures when exporting to Android (arm-v7, arm64-v8, x86, x86-64). If you want ship smaller APKs for each architecture, and do this without using App Bundles, then you need to export 4 different times and change the settings each time. This is manually manageable but quite fiddly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I propose an additional checkbox under the Architecture export options for "Export Individually" (or some other appropriate name). When selected the output will produce a single APK for each selected architecture. Not sure how this would work with the File Save dialog, but as a quick fix we could take the chosen name and just post-fix the arch type in the file name.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Hopefully description above is clear enough.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No. To my knowledge you can't script the export process, you need to manually go in and change options each time. You could build 4 separate export templates for each arch, and build a shell script invoking Godot with the `--export` option instead, but this has the drawback of now needing to keep 4 export configs in sync, (i.e. the only desired difference is the arch).

**Is there a reason why this should be core and not an add-on in the asset library?:**
Changes to export process seems core to me. It's not essential but would be a decent quality of life change in the Android workflow.

**Comment by Calinou** [comment]
This is probably better addressed by #332, as Android Application Bundles will handle this kind of work for you.

**Comment by andy-noisyduck** [comment]
@Calinou Potentially yes, though AAB imposes additional restrictions which may not always be suitable (such as a max size of 150mb, and losing the capability for expansion files).

I have no real data on how export is being used outside of our own projects to know if our use case is common or if AAB support would serve most people better.

**Comment by TheNeoGameFactory** [comment]
Must have for 2021!

https://www.androidpolice.com/2020/06/12/google-play-store-will-make-app-bundles-a-requirement-in-2021/?amp

**Comment by andy-noisyduck** [comment]
With that now confirmed this proposal probably doesn't make sense. Happy to be archived.

**Comment by Calinou** [comment]
Closing per @andy-noisyduck's comment.
