### ISSUE TITLE
Cross-platform HDR support

### ISSUE THREAD

**Issue by romulasry** [godotengine/godot-proposals#1004]
HDR support would be nice to have in the near future.

**Comment by fire** [comment]
I want this as a feature, but please fill out the form and I'll or someone else on the team will reopen.

**Comment by romulasry** [comment]
**Describe the project you are working on:**
HDR Support

**Describe the problem or limitation you are having in your project:**
No HDR Support

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Allow me to have HDR content in the engine

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
HDR supporrt / on each platform, etc

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Don't know.

**Is there a reason why this should be core and not an add-on in the asset library?:**
In the future most platforms should support it out of the box. I don't see why you wouldn't want it in the engine.

**Comment by romulasry** [comment]
@fire @Calinou Could you reopen it now?

**Comment by clayjohn** [comment]
@romulasry I'm sorry but you will have to seriously fill in the template for your proposal to be reopened. Putting words under each headline is not enough. 

If you can't take your proposal seriously enough to put in the effort, then why should anyone else take your proposal seriously enough to discuss it/ implement it?

If you are having trouble understanding what the questions expect from you, please ask and someone will be happy to clarify.

**Comment by fire** [comment]
I think this is a duplicate of https://github.com/godotengine/godot-proposals/issues/1004.

Translate High Gamut to HDR.

**Comment by Calinou** [comment]
@fire There are some differences between color profile management and HDR output support. These features require working on different parts of the engine to be implemented.

**Comment by fire** [comment]
From talking to some Blender people, they were saying there's two possible flows.

# Work In Progress

Render to some high gamut format (currently 4.0 master is undefined) -> engine tone-mapping OpencolorIO ACES-HDR -> ACES->SDR -> Game configured tone-mapping

Render to some high gamut format (currently 4.0 master is undefined) -> engine tone-mapping OpencolorIO ACES-HDR -> HDR10 (monitor hdr) -> Game configured tone-mapping

# Has pr for 3.2

Render to some high gamut format (currently 4.0 master is undefined) -> engine tone-mapping littlecms dci-d3 -> HDR10 (monitor hdr) -> Game configured tone-mapping (This option was mentioned as unsupported)

Render to some high gamut format (currently 4.0 master is undefined) -> engine tone-mapping littlecms dci-d3 -> SRGB (monitor sdr) -> Game configured tone-mapping (This option was mentioned as unsupported)

# Summary

A Blender person mentioned that EA's Frostbite has a technique for having the internal format to stay as ACES-HDR and not break when one converts from wide gamut to sdr. However, he mentioned ACES has problems. I suggested littlecm's workflow but he didn't know.

https://www.youtube.com/watch?v=7z_EIjNG0pQ

Please explain how this is different?

Reference:

https://chrisbrejon.com/

https://docs.google.com/presentation/d/1oN3jJxUmdSXnzISzYiJYz9EML-SROhf3Ef5KC0Eyig8/edit?usp=sharing

**Comment by MickL** [comment]
I am sorry for commenting on an old issue but I am very curious about HDR. The docs say: "Godot does not support high dynamic range output yet.". Is this still up to date or will it change with Godot 4.x? I didnt find any informations or open issues to that topic.

Personally I would be very much interested to publish my game(s) in HDR: Nearly each TV now supports HDR10+ or Dolby Vision. More and more other devices also use OLED or Mini-LED screens, e.g. iPhone (OLED) iPad Pro (Mini LED), Macbook Pro (Mini LED).

**Comment by mhilbrunner** [comment]
That is AFAIK still correct for Godot 4.

**Comment by Calinou** [comment]
> The docs say: "Godot does not support high dynamic range output yet.". Is this still up to date or will it change with Godot 4.x? I didnt find any informations or open issues to that topic.

HDR support isn't planned for 4.0, but for a future 4.x release instead. None of the rendering contributors have access to HDR monitors, and contributors who do have access to such monitors generally don't have the required platform API knowledge to implement HDR output support.

**Comment by MickL** [comment]
OLED HDR TV's are not much expensive anymore. I am already a Patron but might be willing in sponsoring a tv/display if a rendering contributor really does not have access to one. IMO the value of HDR is incredibly high and with the increasing amount of high contrast displays it could also reach a lot of people of all different platforms.
