### ISSUE TITLE
Simple function to convert a float into a Vector2 or Vector3

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#10053]
### Describe the project you are working on

FPS.

### Describe the problem or limitation you are having in your project

I have some scale sizes I want to apply to an object depending on the FOV chosen. I have them in a dictionary and I want to set the scale on the object depending on the FOV:
```swift
var fovs = {
	9 : 0.05,
	14 : 0.12,
	20 : 0.24
}
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Converting a float that's stored that way for easy to read convenience to a Vector3 requires writing something like:
```swift
var fovscale = fovs.get(int(fov))
scale = Vector3(fovscale,fovscale,fovscale)
```
It would be convenient if Vector3 or Vector2 had a function that took the float and created a Vector3 or Vector2 with the float as all three components.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would be something like:
```swift
var the_value : float= 1.25
var new_vector : Vector3 = Vector3.componetize(the_value)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Absolutely, but this would be convenient.

### Is there a reason why this should be core and not an add-on in the asset library?

It should be part of the Vector3 and Vector2 functions.

**Comment by AThousandShips** [comment]
> Absolutely, but this would be convenient.

I wouldn't call `Vector3.ONE * the_value` inconvenient, though a bit clumsy

Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/4822

**Comment by elvisish** [comment]
> > Absolutely, but this would be convenient.
> 
> I wouldn't call `Vector3.ONE * the_value` inconvenient, though a bit clumsy
> 
> Thank you for your proposal, consolidating in:
> 
> * [Support GLSL style initialization and functions for vectors #4822](https://github.com/godotengine/godot-proposals/issues/4822)

Ahh true, that's a simple enough way of doing it.
