### ISSUE TITLE
Improve multi-scale and-rotate editing of 2D nodes

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-proposals#10054]
### Describe the project you are working on

A game in production

### Describe the problem or limitation you are having in your project

You cannot select multiple objects and scale them at once and if you rotate multiple objects, they rotate around their individual origins, which is not always what you want.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the option to scale when selecting multiple objects and add a toggle to go between individual origins and the centre (average) of the selected objects.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Scale needs to be implemented.
An icon needs to be added that toggles the centre of the scale / rotation. I used the Blender Median Point one as an example here. 

![image](https://github.com/godotengine/godot-proposals/assets/4955051/a123f8dd-fee3-4766-880c-14b5cc580cd7)

Note: This could also be added for 3D context.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would be used often.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving 2D editing out of the box.

**Comment by Calinou** [comment]
Ideally, several options should be provided for defining the rotation/scale pivot. See Inkscape's options for align/distribute:

![image](https://github.com/godotengine/godot-proposals/assets/180032/ab4fd974-651b-4caf-a05a-6b65d1530c3f)

**Comment by JoNax97** [comment]
I think individual/center and first selected should be enough. The user just has to pick the object they want first, with any criteria they want.

**Comment by Arnklit** [comment]
I don't really like the idea of the first selected. I feel like Godot would need to get an "active selected" like Blender has for it to make sense so you could manupulate it, otherwise it will just feel bad.

**Comment by JoNax97** [comment]
Fair enough

**Comment by KoBeWi** [comment]
Rotating around custom origin was implemented in https://github.com/godotengine/godot/pull/58375
It's available in 4.3 beta.

**Comment by Arnklit** [comment]
Resolved through https://github.com/godotengine/godot/pull/98534
