### ISSUE TITLE
real support for GLSL shading language 

### ISSUE THREAD

**Issue by ballerburg9005** [godotengine/godot-proposals#1006]
Please switch to true GLSL shading language or at least allow it to run as an alternative to the inhouse shading language.

**The current state of affairs is identical to a web browser only supporting JPEG2000, but not JPEG, because JPEG2000 is just so much better and in principle you could convert images by hand between the two.**

Shaders are flowing around the internet like JPEG images. No one wants to write shaders themselves. Especially not complex shaders that often exceed 200 or even 500 lines of code. There are ample sources where to copy GLSL shaders from and vivid communities to share shaders, such as Shadertoy: all GLSL. I believe most people on Unity or UE also use GLSL.

As far as I understand it, GLSL is already implemented by other open source projects - so it is just a matter of copy pasting it - and it is actually the custom inhouse shading language that is more complicated and causing dev overhead.

It is especially frustrating for beginners to experience that no common shader file will run in Godot without a solid understanding of shaders in general and specifically of the Godot inhouse language and that most shaders will need an average of 15 minutes of work to migrate by hand, even if an expert on shaders.

The situation is to some people as ridiculous as that they are modifying and developing shaders on Shadertoy in GLSL, to experiment on what works well and what doesn't, only then to spent additional effort to migrate them into Godot once they found something that works well.

Godot is totally laying bricks in a very obvious path. It is excluding itself and its users from open  exchange and access by not following common standards.

I think I speak for the entire community that we are ready to trash all JPEG2000 support right here right now in favor of JPEG.

02:30 < ballerburg9005> john[m]5: quite a few things just don't work in 2D, but they do in 3D - like chaining screen shaders
02:33 < ballerburg9005> half of the screen shaders for emulators use multiple passes and multiple effects
02:33 < ballerburg9005> like 2xsai with 2 passes combined with CRT bulge and scanlines that is 4 shaders
02:34 < ballerburg9005> it would be a total mess to rewrite that into one single shader file, it is basically impossible
02:35 < ballerburg9005> on top of that, godot uses its own variant of shading language, so you can't just copy an ordinary GLSL shader from your favorite programs or websites like Shadertoy .. you have to spend about 15-30 minutes rewriting every single shader and sometimes it gets very very ugly
02:36 < ballerburg9005> this one shader, it had a couple of #define s for various mathematical functions very elegantly
02:37 < ballerburg9005> but since godot doesn't support GLSL and thus no #define s, I had to unroll most of them that couldn't be replaced by functions with copy&paste like 50 times it was a total mess
02:38 < ballerburg9005> I would say not using a standard shading language like GLSL was one of the biggest mistakes they ever made
02:40 < ballerburg9005> it is just like Photoshop not supporting JPEG, reasoning than WEBP is so much better
[.....]
02:44 < ballerburg9005> shaders are awesome, if you write them yourself for neat item effects or something it is fun
02:45 < ballerburg9005> .. but most of the time you want to copy stuff from somewhere else and then you have to waste time adapting it from GLSL into Godot format ...

**Comment by clayjohn** [comment]
This has already been added in 4.0 and will be further refined as time goes on.

Take a look at the most recent progress report for details. https://godotengine.org/article/vulkan-progress-report-7

**Comment by ballerburg9005** [comment]
Oh nice! Never mind then!

I searched all the issues and on Google but I couldn't find anything.
