### ISSUE TITLE
Add Undo / Redo support to Animation Library Editing

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-proposals#10062]
### Describe the project you are working on

A game in production

### Describe the problem or limitation you are having in your project

When editing animation libraries it is easy to make a mistake and loose work due to it not supporting undo redo.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement undo / redo in the Animation Library

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You should be able to undo deleting / creating / renaming / copying animations in the "Edit Animations Libraries" view.
![image](https://github.com/godotengine/godot-proposals/assets/4955051/0745042a-806f-4dfc-ad08-0b60e4deee3d)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Undo / Redo missing cannot be worked around with a script

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the editor workflow out of the box

**Comment by AThousandShips** [comment]
> Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Please fill this in in more detail, what options are we talking about and how would this work?

**Comment by Arnklit** [comment]
> Please fill this in in more detail, what options are we talking about and how would this work?

Sorry. Good point. I added a basic description, but maybe this would make more sense as a Discussion issue.

**Comment by AThousandShips** [comment]
Generally proposals should have some basic description or idea of how to do it as well as what to do, but this might be sufficient

**Comment by akien-mga** [comment]
There is UndoRedo code in AnimationLibraryEditor, so this might be a bug more than a missing feature.
CC @KoBeWi

**Comment by KoBeWi** [comment]
Yes, the code exists, and it's functional, but the undo/redo shortcuts don't work while the dialog is open. You need to close it 🙃
