### ISSUE TITLE
Simple overriding of default variable values in subclassed scripts

### ISSUE THREAD

**Issue by tektrip-biggles** [godotengine/godot-proposals#10060]
### Describe the project you are working on

A data-heavy strategy game

### Describe the problem or limitation you are having in your project

A common use case for subclassing a script is to be able to override a particular default value in the parent class. Currently, doing so is cumbersome, requiring workarounds which often have undesirable consequences or side-effects or require a lot of manual data entry which is prone to human error.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a decorator `@override` (or `@override_default`) for subclasses to redefine a variable in the parent class with a new default value.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
# A.gd
class_name A
var foo:int = 1

# B.gd
class_name B
extends A
@override var foo = 2
```

Note that any attempt to specify a different "type" for the overridden value should probably be flagged as an error.
Ideally, the new keyword should work in combination with the `@export` keyword such that if the variable `foo` above was declared with `@export` by class `A`, then any instances of class `B` should also show `foo` in the inspector, but with `B`'s default value present instead of `A`'s

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I suspect that this would be used extremely often if supported, certainly by me!

Current workarounds include:
1. Using a "getter" function & overriding that value in the subclass (note that this precludes being able to also set `@export`ed values via the inspector)
2. Manually setting the value in all instances of the subclass
3. Setting the value during initialisation or ready etc (has subtle quirks relating to initialisation order that can trip you up & also doesn't work well with exported variables & the inspector)
4. Duplicating a "template" resource instance manually before editing
5. Not using subclassing at all and instead relying on "duck typing" without a guarantee that the variable will even exist when used

### Is there a reason why this should be core and not an add-on in the asset library?

Not possible to implement as an add-on in the asset library.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/338
