### ISSUE TITLE
Tileset Editor set tile origin

### ISSUE THREAD

**Issue by jurgel** [godotengine/godot-proposals#1007]
**Describe the project you are working on:**
Tileset Editor

**Describe the problem or limitation you are having in your project:**
Can't set the tile origin (center point), it's doable using `texture_offset` at the inspector, but there's no feedback at the tileset editor.
Tile's origin is important, as it'll be used to calculate render order in YSort.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a button to set origin in the tileset editor (this will change `texture_offset` value)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![image](https://user-images.githubusercontent.com/2030889/83714838-19e41e00-a656-11ea-8b02-60e101a234b7.png)
(The crosshair is the tile origin)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
You can manually modify `texture_offset` at the inspector as a workaround.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a simple change to update the existing value (`texture_offset`) with GUI on the existing tileset editor.

**Comment by jurgel** [comment]
Use case:
Youtube tutorial from GDQuest [here](https://youtu.be/V9OoaOlXc_4?t=360)

He said the tileset is only going to be drawn on the top-left cell, even though the tile is 4x4 cells. Currently, it's doable by setting texture offset, as someone mentions it in the comment section, but it's inconvenient.

**Comment by jurgel** [comment]
If anyone found it useful, I can make a PR.
It's on my [branch](https://github.com/jurgel/godot/tree/3.2_tileset_editor_set_origin)

**Comment by MCrafterzz** [comment]
@jurgel Create a pr! When you have spent the time implementing it then there's no reason not to send a pr :P

**Comment by jurgel** [comment]
@MCrafterzz OK, it's up ([here's the PR](https://github.com/godotengine/godot/pull/39550))

**Comment by Calinou** [comment]
@groud Is this proposal still relevant with the new TileMap and TileSet editor?

**Comment by groud** [comment]
> @groud Is this proposal still relevant with the new TileMap and TileSet editor?

Hmm, don't think it is relevant anymore. There's now visual indication of the texture origin. Basically the new editor displays a red square indicating where the tile under the texture would be. This work only when the texture is bigger than the tile of course.

**Comment by Calinou** [comment]
Closing per @groud's comment.
