### ISSUE TITLE
Bookmark AssetLibs Items

### ISSUE THREAD

**Issue by RustoMCSpit** [godotengine/godot-proposals#10083]
### Describe the project you are working on

irrelevent

### Describe the problem or limitation you are having in your project

I can't bookmark AssetLibs

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

![image](https://github.com/godotengine/godot-proposals/assets/134429563/2531e8d9-5910-47a0-8521-28197525913b)

I would like for there to be a bookmark button for AssetLib items, I picked a random one but imagine there was a bookmark icon

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A bookmark icon

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

No

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/3521.

**Comment by RustoMCSpit** [comment]
would also be cool to make custom bookmarks
