### ISSUE TITLE
Mesh needs to be able to return the primitive type it models

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#10091]
### Describe the project you are working on

A project which uses ImmedateGeometry to build a mesh, and then uses the RenderingServer to draw the mesh in the viewport.

### Describe the problem or limitation you are having in your project

The Mesh class currently does not provide any way to determine the primitive type of the mesh it is representing.  Given that it is able to return the Arrays of it's data, it should be able to return the primitive type too.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a `get_primitive_type(surface_index:int)` method to the Mesh class.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When called, this method will return the primitive type of the data in the Mesh.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Requires changing a core class.

**Comment by AThousandShips** [comment]
For anything except `ArrayMesh`, what would be the direct need to access this? Moving this method from `ArrayMesh` to `Mesh` is probably compatibility breaking at least for extensions

**Comment by blackears** [comment]
I'm trying to access the data in a Mesh to convert it into other objects, including into my custom Mesh derived class.  It would also be useful in other situations where you're using the mesh to represent data rather than just passing it on to the renderer.  At the moment I'm forced to just presume that the mesh is triangle strips because there is no other way to tell what the data represents.  

For editor plugins and some games, being able to analyze and manipulate the geometry itself is important.  The primitive type must already be known since it is passed on to the rendering pipeline.  Methods like `surface_get_arrays` aren't much help without this since you don't know what sort of data is being represented.

There also does not seem to be any way to convert a general Mesh to an ArrayMesh, so that isn't going to be  a work around.

**Comment by AThousandShips** [comment]
> There also does not seem to be any way to convert a general Mesh to an ArrayMesh, so that isn't going to be a work around.

There is, using `SurfaceTool`, with `create_from` and `append_from`

**Comment by blackears** [comment]
That looks like it will work.
