### ISSUE TITLE
Enhancement Request: Support for Function Overloading in GDScript

### ISSUE THREAD

**Issue by DevSavvySerge** [godotengine/godot-proposals#10116]
### Describe the project you are working on

I'm working on a Vampire Survivor-like game where I aim to utilize Object-Oriented (OO) programming best practices. This involves creating a flexible and maintainable codebase that leverages polymorphism and other OO principles.

### Describe the problem or limitation you are having in your project

GDScript currently does not support function overloading. This limitation severely restricts polymorphism, making it difficult to design flexible and reusable code. Without function overloading, I have to use workarounds such as creating functions with different names or relying on optional parameters, which can lead to less readable and less maintainable code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose adding support for function overloading in GDScript. Function overloading would allow defining multiple functions with the same name but different parameter lists. This enhancement would enable more expressive and intuitive code, making it easier to implement polymorphism and other OO patterns.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's a basic outline of how the proposed enhancement could work:

    Allow defining multiple functions with the same name but different parameters:

```gdscript

func attack(target: Enemy):
    # Attack an enemy
    target.take_damage(10)

func attack(target: Boss, weapon: Weapon):
    # Attack a boss with a specific weapon
    target.take_damage(weapon.damage)
```

The appropriate function would be called based on the arguments provided:

```gdscript

var enemy = Enemy.new()
var boss = Boss.new()
var sword = Weapon.new()

attack(enemy) # Calls attack(Enemy)
attack(boss, sword) # Calls attack(Boss, Weapon)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Currently, the workaround involves creating functions with different names or using optional parameters and type checks within the function body. However, these methods are not ideal as they can lead to more complex and harder-to-maintain code. Function overloading would provide a cleaner and more efficient solution.

### Is there a reason why this should be core and not an add-on in the asset library?

Function overloading is a fundamental feature in many programming languages that support OO principles. Implementing it as a core feature would significantly improve GDScript's flexibility and expressiveness, benefiting a wide range of developers. It would also ensure consistent behavior and integration with the language's existing features, which is essential for maintaining a cohesive and robust development experience.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/1571

Please add any ideas that proposal doesn't already cover there
