### ISSUE TITLE
Refactor the pause system to allow pausing arbitrary parts of the scene tree

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1011]
**Describe the project you are working on:**

See the discussion in https://github.com/godotengine/godot/issues/15993, there are already many users desiring this feature and giving example use cases. In fact, most of the users in the thread seem to be confused and thought it was a bug at first, since how they expected pausing to work is how this proposal works.

**Describe the problem or limitation you are having in your project:**

The current pause enum looks [like this](https://docs.godotengine.org/en/latest/classes/class_node.html#enumerations):

> * **PAUSE_MODE_INHERIT = 0** — Inherits pause mode from the node’s parent. For the root node, it is equivalent to PAUSE_MODE_STOP. Default.
> * **PAUSE_MODE_STOP = 1** — Stops processing when the SceneTree is paused.
> * **PAUSE_MODE_PROCESS = 2** — Continue to process regardless of the SceneTree pause state.

The SceneTree pause state referenced above is [a boolean in SceneTree](https://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-property-paused).

Changing the pause mode for any node has no effect except for when the `paused` boolean is true. This means that the only purpose of changing the pause mode is to force specific nodes to be **un**paused, and the only purpose of `PAUSE_MODE_STOP` is to force pausing of a node under an unpaused one. This also means that there is no way to pause just some parts of the scene tree.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The proposal is to refactor the pause system to allow pausing arbitrary parts of the scene tree. I propose to simplify the system such that the only thing that determines the pause state is the pause mode enum (renamed to `PauseState` to reflect this). This means that SceneTree's `paused` boolean will be removed. Then, the enum would behave like this:

* **PAUSE_STATE_INHERIT = 0** — Inherits pause state from the node’s parent. For the root node, it is equivalent to PAUSE_STATE_PROCESS. Default.
* **PAUSE_STATE_STOP = 1** — Stop processing always.
* **PAUSE_STATE_PROCESS = 2** — Continue processing always.

This means that if you wanted to pause the whole scene tree, instead of `get_tree().paused = true`, you would instead use `get_tree().root.pause_state = PAUSE_STATE_STOP`. Unlike the current system, this proposed system can be used to pause or unpause any node in the scene tree. You can simply replace `get_tree().root` with a reference to the node you want to pause or unpause. Unlike the current system, the ability to pause any node is not dependent on the SceneTree's (or root node's) pause state.

I would appreciate it if anyone can share use cases that can't work with the above system. I can't think of any, the system seems to work really well in my head considering how simple it is.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

The behavior is explained above, and it would behave like that. I could implement it if desired. EDIT: https://github.com/godotengine/godot/pull/39606

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, not really. However, this new system is a lot more flexible if users did want to have a lot more manual control over how their game is paused.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is about refactoring a core feature, so it is already in core.

**Comment by nobuyukinyuu** [comment]
I think I might prefer a system that attaches pause groups to the existing pause mode so that there's a distinction between the pause mode and the pause *state*.  Correct me if I'm wrong, but it sounds like what you're proposing is to remove the distinction from the paused state and the pause mode of a node, and this would require the user to manage these states on their own for each node they'd want to modify.  Currently, there's nothing in place to determine what the *original* design-time state of each node's PauseMode is.

Not sure how feasible a group system would be, but the end-user implementation of such a feature would probably be simpler to manage even if under the hood it would be more complex.  Nodes could keep their normal pause mode state, and instead of having a global `paused` property for the scene tree, it could be a pause server or scene tree structure which would allow you to push a pause state to a group key and have that state propagate to the group (and override its default pause state) while it's active.

**Comment by aaronfranke** [comment]
@nobuyukinyuu You can just use Godot's group system, assign nodes to a group, iterate through that group, and set the pause mode for each node you wish to change. But also, keep in mind that in most cases you will only have to pause a small amount of nodes, since all children inherit their parent's pause mode.

**Comment by superoven** [comment]
A use case that has come up for me (and perhaps I'm doing it wrong) is trying to use a Tween while the SceneTree is paused. Even if you spawn a Tween inside of a Node that is set to `PAUSE_STATE_PROCESS`, with the Tween itself also set to process, the Tween will still interpolate in relation to the SceneTree, and never work when the SceneTree is paused.

This is incredibly annoying to me, as I would like to run Tweens on transitions between scenes while paused or add some flair to pause screens. As it stands, this doesn't seem doable. I haven't tried this change yet, and I hope it would make something like that possible.

**Comment by tavurth** [comment]
> @nobuyukinyuu You can just use Godot's group system, assign nodes to a group, iterate through that group, and set the pause mode for each node you wish to change. But also, keep in mind that in most cases you will only have to pause a small amount of nodes, since all children inherit their parent's pause mode.
> 
> EDIT: But also, I guess `PauseMode` should be renamed to `PauseState` as part of this proposal.

I think that both names are pretty confusing, and were difficult for me to grok when I first started using Godot.
Perhaps `PauseBehavior` would be more apt.

**Comment by markdibarry** [comment]
As an example, I have a game where the menu system should be paused when in the normal gameplay state, and the normal gameplay state should be paused when in the menu system. Same goes for cutscenes, time system, etc. Certain contexts require specific systems active and others paused (and visually reflect that). The current pause system doesn't accommodate this workflow, and would require keeping the tree paused at all times, while switching out the inactive node branches.

In the meantime, I made a Node extension that disables/enables one branch at a time as a workaround. This also allows me to avoid the heavy memory leak that the pause system introduces, and would quickly break the game if the scene tree required remaining paused at all times.

**Comment by reduz** [comment]
I suggest closing this issue, as the discussion in #1835 supersedes it. Pausing can't be selectively be done in parts of the tree, because part of pausing means stopping the physics engine (which is a continuous feedback loop that can't be disabled by sections), so the idea being discussed in the comments implement something similar that allows to disable part of the tree, while keeping pause global.
