### ISSUE TITLE
Add the ability to export PCK using code

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot-proposals#10122]
### Describe the project you are working on

Sandbox

### Describe the problem or limitation you are having in your project

My game has support for mods using pck files, but I want to write a separate program for creating game modifications so as not to go into Godot to create a mod, but this is impossible since export to pck is only possible in the Godot Engine editor.

Many popular games have third-party program tools for creating modifications, for example Skyrim, Minecraft, Gta San Andreas, etc., but in Godot it will not be possible to make such a tool if we use PCK files as modifications

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add function to export pck files

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the function ProjectSettings.save_resource_pack is needed, I don’t know what the arguments will be for this function, perhaps it would be necessary to specify the path to the folder that will be exported with all the attached files and folders, but this does not fit Godot programming logic

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As far as I know no

### Is there a reason why this should be core and not an add-on in the asset library?

You can't do this with a plugin

**Comment by AThousandShips** [comment]
Please add some more details on what would be involved in this that can't be done with existing code like [`PCKPacker`](https://docs.godotengine.org/en/latest/classes/class_pckpacker.html)

**Comment by JekSun97** [comment]
> Please add some more details on what would be involved in this that can't be done with existing code like [`PCKPacker`](https://docs.godotengine.org/en/latest/classes/class_pckpacker.html)

Wow... I came across this class for the first time, this is what I needed, thank you. It’s really strange that this function is in a separate class, unlike loading, which is a little confusing.

**Comment by AThousandShips** [comment]
It belongs in a dedicated class because of how the syntax works, there's nothing in the project settings to export it with, it'd be weird to have it there
