### ISSUE TITLE
Add hexagonal pathfinding to AStarGrid

### ISSUE THREAD

**Issue by kopeek** [godotengine/godot-proposals#10120]
### Describe the project you are working on

Now I'm trying to make hexagonal pathfinding for 2D strategy game

### Describe the problem or limitation you are having in your project

AStarGrid2D doesn't have option to set the cell shape to hexagon. Instead of making the game I need to watch tutorial that are outdated, or do it by myself, and spend hours trying do to that.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add hexagons as a option in pathfinding

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Maybe by changing tile shape etc. in the code

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Maybe put it in the editor?

### Is there a reason why this should be core and not an add-on in the asset library?

Because this feature can help beginners, making their games, instead of losing hope in their dream games and in the Godot Engine

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/9710
