### ISSUE TITLE
Add buttons to Animation dock for moving cursor to next/previous keyframe

### ISSUE THREAD

**Issue by mihe** [godotengine/godot-proposals#10142]
### Describe the project you are working on

A game in production.

### Describe the problem or limitation you are having in your project

When working in the Animation dock, there's currently no way to move the timeline cursor to a specific keyframe.

This isn't so much a problem when the keyframes happen to line up with whatever snapping you have configured in the Animation dock, but if the keyframe doesn't line up with the snapping it can be cumbersome to move the cursor to it. You're essentially forced to look up the exact time of that particular keyframe and manually input that time value into the "Animation position" box in the Animation dock.

It's also not possible to simply jump directly between keyframes in the Animation dock, without having to scrub manually, which can be handy as well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To solve the above mentioned issues it would be nice if there were buttons in the Animation dock that let you jump to the next/previous keyframe.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Blender offers this already in its animation player, which looks like this (red circles are mine):

![image](https://github.com/godotengine/godot-proposals/assets/4884246/75095521-2384-4525-8b80-a3daffc5ff26)

I feel like those exact buttons (and icons) would be perfect to add alongside the existing play/reverse buttons found in the Animation dock:

![image](https://github.com/godotengine/godot-proposals/assets/4884246/19d5adbd-4eba-432c-8743-d91798fc52ad)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This could potentially be done with a tool script, but this is about addressing a UX shortcoming, so should ideally be done in Godot itself.

### Is there a reason why this should be core and not an add-on in the asset library?

This could potentially be done with an add-on, but this is about addressing a UX shortcoming, so should ideally be done in Godot itself.

**Comment by passivestar** [comment]
Was about to propose this too. Also snapping to keyframes, as a toggle or as a modifier key (or both) would be convenient
