### ISSUE TITLE
Add "Group tracks by node" toggle to the "Copy Tracks..." dialog in Animation dock

### ISSUE THREAD

**Issue by mihe** [godotengine/godot-proposals#10143]
### Describe the project you are working on

A game in production.

### Describe the problem or limitation you are having in your project

When working in the Animation dock you have the choice between displaying the animation tracks either as just a plain list (in the order they were added in), or have them be grouped by the node to which the property belongs (also in the order they were added in).

However, when you go to the "Copy Tracks..." dialog, this option is missing, and the tracks will always be listed as a "plain list" rather than be grouped by their respective nodes, which when considering the fact that they're displayed in the order they were added in, can be cumbersome to navigate when dealing with many property tracks.

https://github.com/godotengine/godot-proposals/assets/4884246/452725d8-b848-4e91-9cc5-4b010e7b3ac6

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This problem would be resolved by simply adding this same toggle to the "Copy Tracks..." dialog.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As mentioned above, simply add this same "Group by tracks by node" toggle to the "Copy Tracks..." dialog.

It should ideally also be possible to check a specific node as well, which would then check all the tracks belonging to that node. Also, inversely, if all tracks of a specific node are checked, then the node itself should probably become checked as well.

It could look something like this when having toggled the node grouping:

![image](https://github.com/godotengine/godot-proposals/assets/4884246/c5a35ae5-b4ad-4896-918a-403e6cbd1eef)

(Note the new button in the top-right corner, although the placement of it is up for debate I guess.)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This could potentially be done with a tool script, but this is about addressing a UX shortcoming, so should ideally be done in Godot itself.

### Is there a reason why this should be core and not an add-on in the asset library?

This could potentially be done with an add-on, but this is about addressing a UX shortcoming, so should ideally be done in Godot itself.

**Comment by Arnklit** [comment]
I'd suggest resolving this, with this proposal I logged. Where you would be able to select tracks directly in the editor instead of generating the lists in popups for operations. https://github.com/godotengine/godot-proposals/issues/9830

**Comment by mihe** [comment]
That would be a much better approach, yes.

Consider this consolidated into #9830.
