### ISSUE TITLE
Improve readability and data exploring capabilities of monitors and profiler

### ISSUE THREAD

**Issue by samdze** [godotengine/godot-proposals#1014]
**Describe the project you are working on:**
Various 2D and 3D projects.

**Describe the problem or limitation you are having in your project:**
When I look at my monitors in the debugger dock I can only see the current value of each monitor and I can't understand at glance what the past values were.

In the profiler instead, if I select a frame I'll have to search and read the corresponding values to the left each time. I believe this could be improved.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Having auto-updating references on the Y axis to the left of each monitor graph would greatly improve their readablity.

Furthermore, a way to exactly read previous values if the graph is hovered or clicked with the mouse would be very useful. This is applicable to both monitors and profiler.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
For monitors, reference values on the left:
![monitors_value_references_mockup](https://user-images.githubusercontent.com/19392104/83876808-b2070380-a739-11ea-9909-1f7571f71007.png)

For monitors and profiler, precise info on click/hover can be provided, aligned with each value on the graph:
![with_hover_click_info](https://user-images.githubusercontent.com/19392104/83876829-bc290200-a739-11ea-9978-a88a95d038c1.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so, this is functionality that has to be provided by the engine.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Same as above.

**Comment by Calinou** [comment]
The frame number could also be associated to a timestamp (either relative to the project startup, or in `hh:mm:ss` format).

**Comment by akien-mga** [comment]
Fixed by godotengine/godot#39719 and godotengine/godot#39302.
