### ISSUE TITLE
I can't export my project

### ISSUE THREAD

**Issue by Sorens-1** [godotengine/godot-proposals#10158]
### Describe the project you are working on

I'm currently working on paradox portals on the phone

### Describe the problem or limitation you are having in your project

I can't reduce the export window. Because of this I can't export the game
![Screenshot_2024-07-09-11-02-48-075_org godotengine editor v4](https://github.com/godotengine/godot-proposals/assets/175100444/088435d0-2587-4615-8e63-616b1d417f16)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

You can add editing of the export window

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

**Comment by RedMser** [comment]
This should be a bug report ticket on the main repository. Proposals are for feature requests only.

**Comment by Mickeon** [comment]
In theory the proposal could be reworded to be "Allow resizing the Export Window", but it'd be very... succinct.

**Comment by Calinou** [comment]
For future reference, this is a bug: https://github.com/godotengine/godot/issues/73130

See also https://github.com/godotengine/godot/pull/93526.
