### ISSUE TITLE
Line index color of empty lines should be white

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1015]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**
Empty lines aren't unsafe lines but they aren't real safe lines, they're just empty. The line index color is sometimes green (safe) and sometimes gray (unsafe). I couldn't find what it depends on.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Empty lines/ lines with spaces/ lines with indentations should have the line index color white.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
1 extends Node
2 
3 var test
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.
**Is there a reason why this should be core and not an add-on in the asset library?:**
_I don't have experience with add-ons._

**Comment by dalexeev** [comment]
> Empty lines aren't unsafe lines

In fact, empty lines are the safest lines. :laughing: 
Three colors is too much. Gray color indicates possible type errors. If there are no such errors, then all lines should be green.

**Comment by KoBeWi** [comment]
tbh this sounds more like a bug.

**Comment by MaaaxiKing** [comment]
@KoBeWi Yes, I also think it's a bug but I made a proposal because I don't want this bug to be fixed and then the color is another (my favourite: white) anyway if this proposal will be accepted.

**Comment by dalexeev** [comment]
See also: godotengine/godot#20418.

**Comment by Calinou** [comment]
Having *three* different line number colors might start looking like Christmas :slightly_smiling_face: 

I think it'd be better to always mark blank/comment lines as safe.

**Comment by MewPurPur** [comment]
These are already marked safe in 4.0

**Comment by Calinou** [comment]
> These are already marked safe in 4.0

Indeed, this is implemented as of 4.0.rc1:

![image](https://user-images.githubusercontent.com/180032/219455600-2659f5f7-203e-4c90-
bd0b-24f421d04ebd.png)
