### ISSUE TITLE
Place Object at Editor's Camera Position

### ISSUE THREAD

**Issue by bjr29** [godotengine/godot-proposals#1016]
**Describe the project you are working on:**
3D Game

**Describe the problem or limitation you are having in your project:**
Sometimes a bit awkard to position and object quickly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Have a keybind to move and rotate the selected object to the editor's camera position.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Say like, pressing Shift-F will teleport the selected object(s) to the current position in a 3D scene or position a 2D object to the center of the editor's camera.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Nope

**Is there a reason why this should be core and not an add-on in the asset library?:**
I feel like quite a few people could find this useful.

**Comment by Jummit** [comment]
It already exists: Align Transform with View (Ctrl+Alt+M)

**Comment by bjr29** [comment]
Ah ok, thanks for telling me
