### ISSUE TITLE
Expose initial values in ProjectSettings

### ISSUE THREAD

**Issue by Craig-Stoneham** [godotengine/godot-proposals#10167]
### Describe the project you are working on

I would like to expose the initial values set in ProjectSettings.

### Describe the problem or limitation you are having in your project

I have built a UserOptions system (in C++) which interacts a little with ProjectSettings. My UserOptions system loads file(s) at start up. Each option in the UserOptions class has a project_setting boolean which, if true, will set the value in ProjectSettings when files(s) are loaded. This is done early in the core phase, which allows me to actually set the values which initialize certain systems. Each option also has function bindings (Callable getter and setter) for option (obviously these only work on singletons) 
My problem arises from the fact that my UserOpitions class has a revert function, which is fine for values which are not "project_settings" as my UserOptions class will store initial values internally when this is false. The revert function, when true, needs to grab the initial value from ProjectSettings and call the setting Callable with it.
I am also considering adding my UserOptions class as a proposal, but I have not exposed it to scripting and was not sure on the potential of it being misused as it might be a little advanced and being as it is only pure C++ and currently internal to my project I have not made an editor plugin for it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Exposing the initial value in ProjectSettings will give me access to the data and easily solve my problem. I have had to modify the ProjectSettings class to achieve this behaviour, and for the project I am working on, I have so far avoided editing the Godot source code directly, as my current project is added directly as a module.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There would only only need to be minor additions to the source code, which I would be happy to submit via a PR:

project_settings.h:

```cpp
class ProjectSettings {
public:
...
	Variant get_initial_value(const String &p_name) const;
...
};
```

project_settings.cpp:

```cpp
Variant ProjectSettings::get_initial_value(const String &p_name) const {
	ERR_FAIL_COND_V_MSG(!props.has(p_name), Variant(), "Request for nonexistent project setting: " + p_name + ".");

	return props[p_name].initial;
}

void ProjectSettings::_bind_methods() {
...
	ClassDB::bind_method(D_METHOD("get_initial_value", "name"), &ProjectSettings::get_initial_value);
...
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no script workaround for this issue.

### Is there a reason why this should be core and not an add-on in the asset library?

As exposing this data requires adding to the source code.

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`cpp
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by Craig-Stoneham** [comment]
> PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):
> 
> ```cpp code here ```
> 
> I edited your post accordingly, but remember to do this in the future 🙂

Noted. Thanks for that.

**Comment by Calinou** [comment]
Also, this proposal appears to be the consquence of a bug/oversight of the ProjectSettings class: https://github.com/godotengine/godot/issues/56598

**Comment by dalexeev** [comment]
```gdscript
for property in ProjectSettings.get_property_list():
    var setting: String = property.name
    if ProjectSettings.has_setting(setting) and ProjectSettings.property_can_revert(setting):
        prints(
            var_to_str(setting),
            var_to_str(ProjectSettings.get_setting(setting)),
            var_to_str(ProjectSettings.property_get_revert(setting)),
        )
```

**Comment by Craig-Stoneham** [comment]
> You can use `Object.property_get_revert()`:
> 
> ```gdscript
> for property in ProjectSettings.get_property_list():
>     var setting: String = property.name
>     if ProjectSettings.has_setting(setting) and ProjectSettings.property_can_revert(setting):
>         prints(
>             var_to_str(setting),
>             var_to_str(ProjectSettings.get_setting(setting)),
>             var_to_str(ProjectSettings.property_get_revert(setting)),
>         )
> ```

Thank you for that [dalexeev](https://github.com/dalexeev). I failed to see that function in Object / GDCLASS()

**Comment by Craig-Stoneham** [comment]
This function already exists in the codebase.
