### ISSUE TITLE
Add a method for Tween to wait for a signal

### ISSUE THREAD

**Issue by Meorge** [godotengine/godot-proposals#10169]
### Describe the project you are working on

Various projects, including one with a fair amount of scripted character movement

### Describe the problem or limitation you are having in your project

In my projects, there are times when I'd like to script a bunch of actions to happen in sequence. Tweens are great for accomplishing this, and back when I was working in Unity, I used tweens a lot to achieve complex sequences of behaviors.

I have been enjoying using Tweens similarly in Godot, but there have been times that I've wanted to make a tween wait on a signal to finish; however, as far as I am aware, there is not currently a way to do that.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A new method would be added to the `Tween` class, which would be passed a `Signal` object. The tween would wait at that step until it received the signal emission, then continue executing. I think `Tween.tween_signal` or `Tween.tween_await` could both work as names for this method.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is an example function I wrote using the `tween_await` method name:
```gdscript
extends AnimatedSprite2D
...

func play_attack_sequence():
    # Character should walk to the position,
    # play an attack animation, then when done,
    # walk back to their original position.
    var tw = create_tween()

    # Walk to target position.
    tw.tween_callback(func(): play("walk"))
    tw.tween_property(self, "position", Vector2(900, 360), 1.0)

    # Play attack animation, and wait for it to finish.
    tw.tween_callback(func(): play("attack"))
    tw.tween_await(animation_finished)

    # Walk to original position.
    tw.tween_callback(func(): play("walk"))
    tw.tween_property(self, "position", Vector2(200, 360), 1.0)
    tw.tween_callback(func(): play("default"))
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It looks like this can be accomplished by using a `tween_callback` like so:
```gdscript
extends AnimatedSprite2D
...

func play_attack_sequence():
    # Character should walk to the position,
    # play an attack animation, then when done,
    # walk back to their original position.
    var tw = create_tween()

    # Walk to target position.
    tw.tween_callback(func(): play("walk"))
    tw.tween_property(self, "position", Vector2(900, 360), 1.0)

    # Play attack animation, and wait for it to finish.
    tw.tween_callback(func(): play("attack"))
    tw.tween_callback(func():
        tw.pause()
        await animation_finished
        tw.play()
    )

    # Walk to original position.
    tw.tween_callback(func(): play("walk"))
    tw.tween_property(self, "position", Vector2(200, 360), 1.0)
    tw.tween_callback(func(): play("default"))
```
While not too bad, it still feels unnatural to use a reference to the tween within a function it's calling, and/or like overall this kind of use case should be covered by the Tween API. (Perhaps, if this approach is "safe" to do, this could be how it works under the hood?)

### Is there a reason why this should be core and not an add-on in the asset library?

It would be part of the Tween class which is core as far as I know/understand

**Comment by Meorge** [comment]
Welp, I nerd-sniped myself and attempted an implementation, now a PR: https://github.com/godotengine/godot/pull/94194

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/7337
