### ISSUE TITLE
Implement KHR_animation_pointer in GLTF for animating custom properties

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#10164]
### Describe the project you are working on

I am working on making Godot suitable for games with real-time dynamically-loaded user-generated 3D content. For safety reasons, this means glTF files, since it's more sanitized to accept these than to accept arbitrary Godot scenes. Plus, the goal is to allow content to be engine-agnostic, not locking creators of this content into just using Godot, and to make it easy to create content in any non-Godot app, including Blender.

### Describe the problem or limitation you are having in your project

Godot currently only supports the vanilla glTF animation system, which allows for animating position, rotation, scale, and blend shape weights. For other properties, such as the color of a light, the FOV of a camera, the albedo color of a material, the UV offset of a material, and more, you can't do it. However, there is a glTF extension that allows for animating many more properties: KHR_animation_pointer.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add support for importing and exporting glTF files with more advanced animations by implementing KHR_animation_pointer in Godot's GLTF module, allowing users to animate many more properties.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I've already done so here: https://github.com/godotengine/godot/pull/94165

https://github.com/godotengine/godot/assets/1646875/0d81e50d-4937-44c5-9ac2-c9a7498d69dc

Test project: [gltf_khr_animation_pointer.zip](https://github.com/user-attachments/files/16159373/gltf_khr_animation_pointer.zip)

These test files were created by the Khronos group, not me. The source is here: https://github.com/KhronosGroup/glTF-Sample-Assets/pull/106

### If this enhancement will not be used often, can it be worked around with a few lines of script?

For the general case, no. It would take many thousands of lines of script. For a more narrow case, it could be done with less, but the goal here is to implement a system that is extendable and allows animating many properties.

### Is there a reason why this should be core and not an add-on in the asset library?

This must be core to Godot Engine because it requires a lot of low-level hooks to do it right, and other extensions need to be able to build on these features.

**Comment by aaronfranke** [comment]
Implemented and merged here: https://github.com/godotengine/godot/pull/94165

**Comment by coderofsalvation** [comment]
are these animations also preserved when exporting to glb?

**Comment by aaronfranke** [comment]
@coderofsalvation Yes, `.glb` is also GLTF, but just `.glb` instead of `.gltf` file extension and binary instead of text.

What do you mean "animating alpha"? You can animate the `alpha_scissor_threshold` of a material.

**Comment by coderofsalvation** [comment]
awesome, yes i mean both gltf/glb.

with alpha I meant opacity.

btw. do you have these test gltf's downloadable somewhere?
Would be great to try them out in Godot as blender does not have support for it yet.

**Comment by aaronfranke** [comment]
@coderofsalvation Which glTF property corresponds to that?

**Comment by aaronfranke** [comment]
@coderofsalvation Yes, you can use Godot as a "game asset SDK", in fact it would be great for that. Godot already includes built-in support for [animation pointer](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_animation_pointer), [lights](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_lights_punctual), texture transform, [KTX](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_texture_basisu) & [WebP](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_texture_webp) textures, [single root](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/GODOT_single_root) files (trying to get this in [Three.js](https://github.com/mrdoob/three.js/pull/31112) and [UnityGLTF](https://github.com/KhronosGroup/UnityGLTF/pull/850) as well), and with [an unmerged PR](github.com/godotengine/godot/pull/88204) as you've seen, [audio emitters](https://github.com/KhronosGroup/glTF/pull/2137).

Additionally, you can greatly expand Godot's glTF extension support by grabbing the [omi-godot](https://github.com/omigroup/omi-godot) repository and adding the addon it to your project. This adds a bunch of things including [environment/skyboxes](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_environment_sky), [joints](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_physics_joint), [spawn points](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_spawn_point), [seats](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_seat), and most fun of all, [vehicles](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_vehicle_body). There's also [an unmerged PR](https://github.com/omigroup/omi-godot/pull/5) for [gravity fields](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_physics_gravity) like Super Mario Galaxy, but this requires an unmerged engine PR ([#82878](https://github.com/godotengine/godot/pull/82878)).

Godot's editor is lightweight and beginner-friendly, so it can be great as a tool to compose final game-ready assets following open standards, enriched with glTF extension data, ready to be imported into no-code game platforms. Much nicer than, say, VRChat which requires downloading the entirety of Unity to compose a proprietary asset just for VRChat.
