### ISSUE TITLE
Expose Import Defaults control for meshes, lightmap uv, or add way to select more than one mesh at import

### ISSUE THREAD

**Issue by catprisbrey** [godotengine/godot-proposals#10177]
### Describe the project you are working on

Working on a project with lots of meshes that do not yet have a UV2 unwrapped. They will need one for lightmapping. So I'll need to unwrap them all first before running the lightmap baking.  

### Describe the problem or limitation you are having in your project

It seems there aren't easy/quick ways to handle the unwrap setting for larger bulk number of meshes. All options currently seem to be one-at-a-time.

The simplest solution for me would be to be able to change the default action for lightmap unwrapping for meshes, but the there isn't an option for it (that i can find in) in the Import Defaults menu. For scenes, and obj, and other things sure, but i can't change the default mesh import settings anywhere that i can find.

![image](https://github.com/godotengine/godot-proposals/assets/43008564/534c5f62-0f81-4d10-9896-53fe8cb8f968)

The next option would be to simply select all the meshes in the import menu and change that drop down, unfortunately you cannot select more than one mesh at once to change a setting for all of them. You must click on at a time. If you have a lot of meshes, this is a lot of tedium, to click each mesh, one at time, then shift the dropdown for the lightmap from default to 'enabled'.

![image](https://github.com/godotengine/godot-proposals/assets/43008564/ee509e1c-ad1b-460a-a206-2b8763c87eab)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Either expose access to change the default mesh import settings in the Default Import menu, or add the ability to select more than one mesh at a time in the Import menu itself, to allow changing settings en masse.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For the default Imports Menu, simply dropdown section called "Mesh" like the other object/filetypes have, and the exposed default mesh import options to be able to set them there.

Or on the import menu itself, being able to hold ctrl to select multiple individual meshes, hold shift to select many in a row, or use Select All keyboard shortcuts to select all. Like a filesystem would use.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I imagine it would be used by all folks who need non-default mesh import settings. Or folks who need to bake lighting, but their meshes aren't setup in pre-production with a 2nd UV. 

### Is there a reason why this should be core and not an add-on in the asset library?

It seems more like an oversight to not allow the default to be changed in the default import menu. I'm actually expecting somebody to reply saying "it's over here actually" since most import setting defaults options appear exposed already.

**Comment by Calinou** [comment]
Individual objects in the Advanced Import Settings dialog are *not* imported resource types, which is why they don't appear in the Import Defaults dialog.

Note that mesh objects in this dialog should not be confused with the **Mesh** import type, which is reserved for .obj files. This currently doesn't support UV2 unwrapping or LOD generation (see https://github.com/godotengine/godot-proposals/issues/5600).

**Comment by catprisbrey** [comment]
Maybe i just need to be more clear. This setting arrowed below is exactly what i want to control the default import setting form. Currently you can pick Default, Enabled, Disabled. Currently the Default is disabled, i'd like to change it to Enabled, but find nowhere to define that default.

![image](https://github.com/user-attachments/assets/afc134ec-5caf-4ebf-8fab-3061e1a3d03a)

**Comment by catprisbrey** [comment]
When I set that to enabled, that mesh imports exactly how I need it to. It's just tedious to set enabled manually for every single mesh, since you can't select all meshes and change that, or change the default (that I can find) to be enabled

**Comment by Calinou** [comment]
I know this is what you're referring to, I was just saying that implementing this will likely be difficult, especially if we want to keep the UI clean. It may require adding a second dropdown that appears next to the current dropdown when you select the **Scene** import type in the Import Defaults dialog.

PS: In the future, please use the **Edit** button (located behind the **…** icon in the top-right corner of your comments) instead of multi-posting.

**Comment by catprisbrey** [comment]
Sure thing. 

But I don't want an option changed or morenui added to the import menu. I'd rather see in the Project Settings /Default Imports settings a menu/exported option to choose that default setting for incoming imports.

It seems odd to have three options currently "Default, Enabled, Disabled" when really there are wonky two options "Disabled, Enables" since disabled is the default with nowhere to chnge that import preference.

**Comment by Calinou** [comment]
> But the Default Settings may need a looking at since they don't seem to be doing anything?

Remember that Import Defaults only affect newly created files. Existing files will keep their existing defaults, as default values are stored in the respective `.import` files.
