### ISSUE TITLE
[Just a thought, not sure if possible and easy to implement] Broader generic type for GDScript static typing?

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [godotengine/godot-proposals#10188]
### Describe the project you are working on

Any projs

### Describe the problem or limitation you are having in your project

Currently, we have `Array[Type]` and soon will be `Dictionary[KeyT, ValueT]`, so this hit me of this proposal.
I believe there have been some of proposals like this - asking for generic types in GDScripts. However, someone would say, "hey bro don't you know that you can type a pure type in functions as parameters?" True, we can currently pass pure type names as parameters in function calls:
```GDScript
func is_type(value: Variant, type: Object):
    return is_instance_of(value, type)
    
# Somewhere you call it
var a := Node.new()
is_type(a, Node)
```
Yep, see, the definition of the second parameter is determined as `Object` type literally; however, you can actually enter a parameter which is purely the type name! Here `Node`, a pure type name, is passed in as the second parameter of the function, and your editor allows it so no errors will be thrown.

This is simple, but let's think something a bit more complex:
Assume we have a `Scope` class that helps us to scope single or multiple nodes we want:
```GDScript
class_name Scope

static func select_all(type: Object) -> Array[Object]:
      ....

# And when we try to call it in a script inheriting `Node`
var arr := Scope.select_all(Node)
```
The result would be great. However, let's review somewhere tricky:
```GDSCript
static func select_all(type: Object) -> Array[Object]:
```
Notice it? You input a parameter with a specific type (like `Node`), but the returned array is not a specified array, which still contains the super class of `Node`. Then what if we want the input a Type and output an array with this specific Type? The first thing we would think of is inheritance on this `Scope` class. Of course this may solve the problem, as since 4.2 you can override a function and let it return a more specified type. But what if you have a sea of bunch of classes to be done so? Should you make class inheritances one by one like a donkey working drastically on a farm?

Therefore, generic type, then, can solve this problem.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement a simple/pseudo generic typing for GDScript static typing, making this quicker and more convenient.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Since we have brackets `[]` used as a pseudo-generic symbols, we can use it for broader generic types as well:
```GDScript
static func select_all[T]() -> Array[T]: # Note: Only you defined the `T` in the brackets before the function name can the returned `T` become valid symbol.
    ....

# Then
var arr := select_all[Node]() # And the editor will regard the returned as Array[Node] automatically

# For lambdas
var generic_lambda := func[G]():
....

# You cannot use generic type in a lambda function called immediately with return values
var value_by_generic_lambda := (func[G]:
    ....
    return <your value>
) # Error: Call on generic-typed lambda is not supported
```

Not only for functions, in the further future we can also add generic class for more advanced static typing:
```GDScript
class_name MyGeneric[G]
extends Node

signal generic_signal(type: G)

var member_generic: G

func _init[G](...args):
....
```

For inheriting a generic class:
```GDScript
class_name MyChildGeneric[H, I] # You can pass in multiple generic type symbols here
extends MyGeneric[G]

var child_member_generic: G
var member_2: H
var member_3: I

func _init[G, H, I](...args):
super[G](...args)
...
```

When creating a new generic instance:
```GDScript
var a := MyGeneric.new[RefCounted](<your args here>)
var b := MySubGeneric.new[RefCounted, Resource, Shape2D](<your args here>)
```
Yep, the generic typing call of `new()` function is the same as other generic-typed functions

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as this is the functionality of core godot resource

### Is there a reason why this should be core and not an add-on in the asset library?

The first reason is the same as the answer in previous question.
The second reason is that there are people being thirsty for generic type in functions, and even in a whole class. So the implemention of broarder generic type may provide great conveniece for us to code more beautifully.

**Comment by Gnumaru** [comment]
https://github.com/godotengine/godot-proposals/issues/1207

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1207.
