### ISSUE TITLE
Editor to remember position and size

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot-proposals#10197]
### Describe the project you are working on

Any game, have this issue when streaming as I need to size and position the editor to the area of the screen being captured.

### Describe the problem or limitation you are having in your project

I've got a wide screen monitor and do not want to run the Godot editor full screen when streaming. It would be great if I could configure the Godot editor to not run full screen, but to give it a fixed size and position.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add similar position and size options as a normal Godot game, but now for the editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

n/a

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Might be scriptable, not sure

### Is there a reason why this should be core and not an add-on in the asset library?

Might be possible as an add-on, not sure

**Comment by AThousandShips** [comment]
Consolidating in:
* https://github.com/godotengine/godot-proposals/issues/8358
