### ISSUE TITLE
ReflectionProbe rework

### ISSUE THREAD

**Issue by bud11** [godotengine/godot-proposals#10209]
### Describe the project you are working on

A game.. with lighting

### Describe the problem or limitation you are having in your project

Reflection probes are incredibly limited, at least in terms of controlling how and when they render what they do. 

For example, I wanted to have a bunch of them throughout a level, just reflecting static level geometry, maybe sometimes updating if major changes happen to level geometry/scenario that'd make the reflections look noticably wrong. It seems like the only way to do that is to toggle between update modes, wait a frame, then toggle back, or just move the probe subtly. 

I also have no way of waiting for the probes to render. So when levels load, you just see all these probes rendering one by one and kind of popping in new detailed lighting across the level, because its not like I can factor that into level loading code besides just waiting some arbitary amount of extra time.

Id also really prefer if I could just bake the probes even if it took just as long to load as it did to render, because then I could at least guarantee what they look like and hand tune the reflective elements to some degree in editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose the following:

Remove the move threshold aspect of update_once. Its confusing and really useless in my opinion. If you want a reflection probe that just.. updates sometimes, then you should control that yourself in code. If you want something that updates constantly or is linked to a dynamic object in some way, then just use update_always. I see zero in-game reason for the weird middle ground that update_once currently offers there.
(This might be useful to preserve as editor only behavior though, where you actually might want to make these subtle changes)
Could potentially add some functionality to update_always to preserve move threshold stuff. Maybe update_always could have an update framerate and/or an update movement threshold on top of that. That makes a lot more sense to me.

Add a queue_redraw method that queues a full probe redraw for the end of the current process frame. This could expose identical behavior to what update_once already does internally.

Add an update_none mode that just never updates unless you use queue_redraw. Id personally use this so that I could do something like hide characters, draw, then show characters.

Potentially add an update_baked mode as well that lets you directly save and/or use a cubemap of your choice.

Add a get_progress method or similar that returns an enum value that indicates the current general rendering progress (inactive, preparing, done), so that you can wait on rendering probes or see if theyve started rendering or loading baked data. Id personally use this to determine if the scene is presentable and ready to be shown on screen yet.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Partially, but even then, not all that clearly or conviniently.

### Is there a reason why this should be core and not an add-on in the asset library?

Standard engine rendering feature

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/4782 and https://github.com/godotengine/godot-proposals/issues/2934.
