### ISSUE TITLE
Remote tree "clone" visible while debugging

### ISSUE THREAD

**Issue by Visnicio** [godotengine/godot-proposals#10202]
### Describe the project you are working on

I think it should be nice to implement some way to represent the current remote tree in a visible way in the editor, this could be helpful specially when testing UI

### Describe the problem or limitation you are having in your project

I use tweens to animate my UI Control Nodes, but I can't debug their boundaries in a "normal" way, I could add a border and track them... with my eyes tho, not a good way to test it I think

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would help me to better visualize where my control nodes and every other node are outside the camera viewport

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The engine already has track of the remote tree, it would be a matter of representing it current state in the editor

### If this enhancement will not be used often, can it be worked around with a few lines of script?

With major effort only

### Is there a reason why this should be core and not an add-on in the asset library?

This is a common feature on any major engine

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/7213 and https://github.com/godotengine/godot-proposals/issues/9142.
