### ISSUE TITLE
Ragdoll Physics Node

### ISSUE THREAD

**Issue by JaberOnFire1** [godotengine/godot-proposals#10205]
### Describe the project you are working on

What to make a simple player scene with ragdoll physics.. Using animations to move it and such.

### Describe the problem or limitation you are having in your project

Theres rigidbody, theres characterbody, but no ragdoll body or whatever. Tutorials on youtube are so over complicated because they are making a DIY ragdoll.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Maybe a ragdoll node, or something on the same line to help ease the difficulty to make ragdolls.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well click add node, 
add ragdoll, 
put the skeleton3d as a child and get a reference to it. 
Then get the animation node reference and when you play an animation the node will use hooks law to play the animation will taking ragdoll physics.
I'm not that smart so you will have to come up with some idea.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Currently in 4.3 no tutorial or guide makes a working ragdoll, and its a lot more than a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?

Because it should be a base assest in the game engine to be a ragdoll node, its like using a staticbody node instead of a characterbody and trying to add functions like is_on_floor...

**Comment by AThousandShips** [comment]
> Currently in 4.3 no tutorial or guide makes a working ragdoll, and its a lot more than a few lines of script.

Did you see [this](https://docs.godotengine.org/en/latest/tutorials/physics/ragdoll_system.html)?

**Comment by JaberOnFire1** [comment]
I've seen the docs and i have got a better grasp on it. I usually watch YouTube tutorials but they are a bit over the top sometimes.

**Comment by AThousandShips** [comment]
Then the proposal should reflect that desire, it focuses on ragdoll and very little on the ability to animate them, which should be the main focus if the existing ragdoll features aren't enough IMO

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/750 and https://github.com/godotengine/godot-proposals/issues/7097
