### ISSUE TITLE
Add in-built terminal

### ISSUE THREAD

**Issue by dipanshparmar** [godotengine/godot-proposals#10210]
### Describe the project you are working on

A 2d vampire survivor-like game

### Describe the problem or limitation you are having in your project

I prefer using a terminal whenever possible when navigating through the file system. But Godot doesn't have any in-built terminal. So when performing, cutting, copying, moving, navigating, and git operations, I have to open the external terminal and then navigate to the Godot project directory. It messes up the workflow sometimes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Please add the support of an in-built terminal that when opened always points to the current project directory. This will improve the workflow of people who prefer terminals.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The terminal tab can be added here
![image](https://github.com/user-attachments/assets/62fff4e8-7996-4f6a-9abb-ac1624bd8404)

_This is how it is in VS Code_
![image](https://github.com/user-attachments/assets/c76f257a-7d06-410b-a244-5b3b010d68e5)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure.

### Is there a reason why this should be core and not an add-on in the asset library?

I feel that an in-built terminal should be present to improve workflow out of the box as it is often required for plenty of tasks.

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot-proposals/issues/4473
