### ISSUE TITLE
Allow for easy add_group dropdowns for inspector properties for plugins

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot-proposals#1021]
**Describe the project you are working on:**
A design goal I'm aiming for in my project is to build all my level editing needs within Godot. I'm working on an Inspector plugin that "extends" the CanvasItem node globally. The idea is to add a few extra useful inspector properties to control from my plugin.

**Describe the problem or limitation you are having in your project:**
I can't seem to be able to easy add a "group" dropdown menu with a plugin.

I'm using `EditorInspectorPlugin`, `add_property_editor` and override `parse_category` to add properties to CanvasItem categories globally. However, I have a few properties I'd like to add, so I'd like to be able to put them under a dropdown group menu (much like the `Anchors` menu on `Controls`).

I suspected that _maybe_ `add_property_editor_for_multiple_properties` _could_ help with this but I have no idea what this does and the documentation isn't clear. I've tried using it in multiple ways and it hasn't helped. I'd love to be enlightened on the usage of this method.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This feature allows the plugin designer to easily add a "group" menu, such that properties can be put under subcategories like the `Anchors`, `Margin`, `rect`, etc, menus.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm not sure how this would be done with the API the Godot developers are aiming for, but I guess the simplest way to do this would be to add a `Control` node that looks like the group control used in the actual Inspector but has methods to add multiple `EditorProperty`s to it.

That or maybe a method to group `EditorProperty` nodes together, like 
```gdscript
extends EditorInspectorPlugin

func can_handle(object) -> bool:
    return object is CanvasItem

func parse_category(object: Object, category: String) -> void:
    if category != "CanvasItem": return

    var prop1 = EditorProperty.new()
    prop1.label = "A"

    var prop2 = EditorProperty.new()
    prop2.label = "B"

    add_group_property_editors("AB", [prop1, prop2])
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This could definitely be worked around but not with a few lines of script, I don't think. I'd love to know if there is. However, to my knowledge, you'd have to create your own dropdown that opens and collapses within the editor, and write code for how it would display multiple EditorProperties.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I feel like this is a natural and common thing users would want to do if they want to "extend" properties on certain node types for Inspector plugins.

**Comment by Zylann** [comment]
At first I thought it was about node groups but you actually mean categories for properties, which allow to put them under an expandable/folding widget, right?

**Comment by Lucrecious** [comment]
Yes, exactly

**Comment by stickgrinder** [comment]
I have the same issue. I'd want my plugin to group an inspector interface under its own category, but no luck with this.

Since the last activity here has been in 2020 I guess this has never been a priority.
@Lucrecious did you manage to work around this somehow?

I second this anyway. I should ideally be able to add a category to the inspector, with icon, title and collapsible behavior by simple declaration.

**Comment by stickgrinder** [comment]
Well, it seems I did it (or at least I did what I wanted, unsure if it's the same).

You can add a section to the inspector for any node you want with the `Node._get_property_list()` like this

```gdscript
func _get_property_list():
    var properties = []
    properties.append({
        name = "My Section",
        type = TYPE_NIL,
        usage = PROPERTY_USAGE_CATEGORY
    })
    return properties
 ```
 
 This actually adds a section right after the "Script Variables" of a node.
 You can then either add more properties appending them to the array (see [this section of the docs](https://docs.godotengine.org/en/3.5/tutorials/scripting/gdscript/gdscript_exports.html#properties)) or `_parse_category()` into your `EditorInspectorPlugin` to place stuff where you want.

**Comment by YuriSizov** [comment]
@stickgrinder In Godot 4 you also have annotations for grouping exported properties, so no `_get_property_list` override is necessary. In Godot 3 you could always do what you did, yes. Though I'd suggest using `PROPERTY_USAGE_GROUP` and not category, as semantically categories are meant to represent classes in the hierarchy, not groups of properties of the same class.

But if you do use categories, do note that you can add custom icons to them by defining a `class_name`'d script with the same name as your category. 🙃 

That said, this original proposal here is not about that, I don't think? It seems like the author wants to extend built-in classes universally using an inspector plugin. Which is not something that is supported or is going to work reliably. So adding a way to create groups like that is not really going to solve anything. They should instead do what you did, and extend the class with a script and define their custom properties, including groups, in there. No plugin necessary.

I think it's safe to close this proposal, as the original use case is not really supported and the suggested feature already exists in both 3.x and 4.x, but in a more idiomatic way.

**Comment by stickgrinder** [comment]
Hi @YuriSizov! Thanks for your advice on Godot 4. In the next few weeks I'll port the plugin to the new version, it's nice to have annotations to solve this.
For the icons, I'll try what you suggested, thanks! :)
