### ISSUE TITLE
Add to the NodePath documentation how to get to a parent's property

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot-proposals#10218]
### Describe the project you are working on

I'm working on an online RPG

### Describe the problem or limitation you are having in your project

I'd like to be able to use this pseudo code
`$MultiplayerSynchronizer.add_property(^"..:variable")`
but it does not seem to work that way

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

add to the documentation how to access the parent's property through a nodepath

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

already explained above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't make it work, perhaps it's simple but looking at the documentation it seems that this is missing there

### Is there a reason why this should be core and not an add-on in the asset library?

it's a pretty basic feature, I personally think this should be a core, if it isn't already a feature that I don't know how to use

**Comment by AThousandShips** [comment]
This sounds like a bug, and if it isn't there's no reason to open a feature proposal for it, but instead a bug report on the [docs repo](https://github.com/AThousandShips/godot-docs) to track the missing documentation, but first I'd say to open a bug report for this not working and see if it's possible or supported in the first place, and if so what's broken

**Comment by AThousandShips** [comment]
Reading the code:
https://github.com/godotengine/godot/blob/97b8ad1af0f2b4a216f6f1263bef4fbc69e56c7b/modules/multiplayer/multiplayer_synchronizer.cpp#L382-L389

Which calls:
https://github.com/godotengine/godot/blob/97b8ad1af0f2b4a216f6f1263bef4fbc69e56c7b/modules/multiplayer/multiplayer_synchronizer.cpp#L36-L43

It doesn't seem that it supports paths not under `root_node`

I think this should instead be a documentation issue for clarifying this, *or* a proposal that this should be allowed, but it *currently* isn't supported (and IMO doesn't makes sense to support)

So closing this as the feature isn't supported at all, please open either a documentation issue for clarifying that you *can't* synchronize properties not under `root_node`, or a proposal for allowing this
