### ISSUE TITLE
Add the built-in SCREEN_UV to the spatial shader's light() function

### ISSUE THREAD

**Issue by RoyBerardo** [godotengine/godot-proposals#10222]
### Describe the project you are working on

simple puzzle game with a stylized lighting look

### Describe the problem or limitation you are having in your project

I've created a light() shader that uses a screen-space texture to give shadows a stylized look. In order to accomplish this, I need to access the screen UV to place the texture. Because the light() function does not actually have SCREEN_UV, I  do the following:

```
void light() {
	vec2 SCRN_UV = (VIEW.xy + FRAGCOORD.xy) / VIEWPORT_SIZE;
       ...
}
```
(If I name the variable SCREEN_UV, it causes issues. Not sure if that's intended behavior or not)

I admit, I don't even know if this is the right solution to get the actual screen UV. It looks right in-game though.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add `SCREEN_UV` as a built-in for the light() function, exactly the same as it is in the fragment() function. This would simplify the process of getting the screen's UV, and also make it more intuitive.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You would be able to access SCREEN_UV in the light() function, and it would return a vec2 of the Screen UV coordinate of the pixel currently being processed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As mentioned above, you can use something like `vec2 SCRN_UV = (VIEW.xy + FRAGCOORD.xy) / VIEWPORT_SIZE;` to make your own SCREEN_UV variable in the light() function (I don't know if this is correct even), though IMO it feels intuitive that there would just be a SCREEN_UV bulit-in.

### Is there a reason why this should be core and not an add-on in the asset library?

SCREEN_UV is a very basic built-in for the fragment() function. Such a built-in for the light() function would also be very basic.

**Comment by Calinou** [comment]
cc @Chaosus
