### ISSUE TITLE
Make timeline snapping and keying snapping separate buttons in the animation editor

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-proposals#10225]
### Describe the project you are working on

A game in production

### Describe the problem or limitation you are having in your project

We generally always want key snapping enabled when setting and editing keys, but when scrubbing the animation to preview animations we don't want it enabled.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Separate the snapping feature into two buttons, one for the keying and one for scrubbing the timeline.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/user-attachments/assets/86329fc5-ee26-443f-8dae-238c70993ca8)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would be used often

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the animation tools out of the box

**Comment by Calinou** [comment]
Timeline snapping should probably be disabled by default, in fact. Most animations are designed to be played in a continuous manner after all.
