### ISSUE TITLE
Show MeshLibrary item ID in the GridMap editor item labels

### ISSUE THREAD

**Issue by KakkoWojtylla** [godotengine/godot-proposals#10233]
### Describe the project you are working on

3D Gridmap based projects in general, dealing with meshlib files

### Describe the problem or limitation you are having in your project

Working with big libmesh files, on a gridmap can become real cumbersome and annoying real fast, to set a cell item of a gridmap by code you use the method "void set_cell_item ( Vector3i position, int item, int orientation=0 )" you already have a preview of all you items, but not a easy way to check their ids , when dealing with smaller libmesh files its easy, but opening a 200 item libmesh file just to find a single mesh item id take too much time and effort, image a 3d tile project where you have to deal with multiple libmesh files

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

to add a simple ID to the name of an item on the gridmap's libmesh preview window

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

first i want to say that i dont know if my way of doing this is the right way, i am not fluent in cpp, i just used what i know about c#, so far using it eveyday, works like a charm
but long story short, change the line 893 on the file grid_map_editor_plugin.cpp from:
String name = mesh_library->get_item_name(id);
to
String name = mesh_library->get_item_name(id) + " (" + String::num(id) + ")";

the result on the preview window is from this:
![image](https://github.com/user-attachments/assets/9ac00831-6cea-4979-a898-9de4c4384092)
to this:
![image](https://github.com/user-attachments/assets/4b3e114a-9f61-46bb-9b19-ab97692493c7)

simple, yet very useful

### If this enhancement will not be used often, can it be worked around with a few lines of script?

to the honest, i've tried before going this route, it can be done with a editor , but being that a single line change, i dont see the reason why not
(i dont have a full understand of godot's code, so it might be a bad idea and i dont know, if is that the case, sorry)

### Is there a reason why this should be core and not an add-on in the asset library?

i've done this change to my own godot editor before, and it have been a simple yet very useful quality of life change, having to just hover over a item on the preview window to know the id o the mesh you want to use, saves a bunch of time, over having to open a meshlib file and search, all with a single line changed

**Comment by Hiiamwilliam** [comment]
Something very similar was proposed [here](https://github.com/godotengine/godot-proposals/issues/5866) and there is a pending pull request [here](https://github.com/godotengine/godot/pull/85127). It's slightly different than what you're asking, maybe try to leave a comment there.

**Comment by KakkoWojtylla** [comment]
> Something very similar was proposed [here](https://github.com/godotengine/godot-proposals/issues/5866) and there is a pending pull request [here](https://github.com/godotengine/godot/pull/85127). It's slightly different than what you're asking, maybe try to leave a comment there.

thank you very much

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/5866.
