### ISSUE TITLE
Allow users to specify signal method receiver name format

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-proposals#1023]
**Describe the project you are working on:**
A game's UI

**Describe the problem or limitation you are having in your project:**
I'm currently reorganizing the user interface of a game and whenever I rename an instanced scene, or I change the "Edit Children" property of the instanced scene, I lose all my signal connections that live outside of those instanced scenes.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Instead of generating a string of type `_on_${node.name}_${node.signal_in_question}`, let users specify what string they want to use when connecting signals by using other property values of the node.

For example, by editing the project properties, users can then specify the signal format of: `_on_${node.name}_${node.class}_${node.signal_in_question}`

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not entirely. Connecting signals through GDScript has the side effect of not showing up in the UI which is not what we want in our current project given the sheer amount of signals.

It's worth mentioning that this issue will come up when working on complex games -- refactoring nodes and code whilst keeping the UI the same will become a pain because users will have to retype or copy paste function names every single time they attempt to connect signals through the editor.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Godot's editor must be modified to add this feature.

**Comment by dalexeev** [comment]
See godotengine/godot#52997.
