### ISSUE TITLE
Add own default for every property on every node

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1024]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**
There should be an own default on every property on every node. The Engine's default of a Label is "". Maybe I want to set an own default as "This is my own default" and then I want to change the text again to "something" but then I could easily change it back to "This is my own default".
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If I changed a property of a node in a script and wanted to reset it https://github.com/godotengine/godot-proposals/issues/1022 , I'd maybe want to reset it to my own default instead of the Engine's default.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Script: `real_default()` `own_default()` `set_own_default()` `get_own_default()`
Editor:
![own default](https://user-images.githubusercontent.com/60623532/83977844-bf6fe980-a903-11ea-9775-a70ca021fdeb.png)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes but maybe more than a few lines. You could define a variable for your own default.
**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by Calinou** [comment]
This can be achieved using instanced scenes. It won't be truly global, but that might not be a good idea anyway.

**Comment by Calinou** [comment]
Closing due to lack of support. If you need this for specific elements in a project, you can always use instanced scenes as mentioned above.
