### ISSUE TITLE
Add a "Duplicate from Theme" button to Theme Overrides when a theme is used on the control node or a parent

### ISSUE THREAD

**Issue by KccbzZ** [godotengine/godot-proposals#10245]
### Describe the project you are working on

A RTS prototype. Currently implementing authentication, and making the menu.
The context though is just the speed of menu styling.

### Describe the problem or limitation you are having in your project

It can get repetitive to make a theme override for StyleBoxes, but change a little bit only.

### **EXAMPLE:**

So lets say I have a large "default_theme.tscn" theme, and I want to override a button's colors only from its styleboxes and all else is fine. I would have to:

1. Find the control node with the theme from a bunch of other nodes
2. Find the type of node this is in perhaps a long list of types
3. Potentially navigate to the styles tab
4. Copy the style box
5. Find the control node I'm working on again
6. Paste it and make it unique, and THEN edit
7. Repeat for Hover, Pressed, etc depending on the Control node type.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have a button next to each object in "Theme Overrides > Styles" which would duplicate the corresponding style from the theme that it uses, and make it unique.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's what I image it to look like. It's self-explanatory from the image:
![image](https://github.com/user-attachments/assets/b47ab06a-76c7-409f-be93-4d42b36dadc0)

Some pseudo code:

```gdscript
# IN THIS PSEUDO-CODE:
# 1. This is part of the theme override system.
# 2. get_theme() is the theme that this Control node is influenced by.
# 3. type refers to e.g. Button type, or LineEdit type.
# 4. style_box_name is like the Normal, Hover, Pressed, etc. styleboxes.

func _ready():
     if self.get_theme() != null and get_theme().is_type_used(type) and get_theme().get_type(type).is_stylebox_used(style_box_name):
          duplicate_button.show()

func _on_duplicate_button_pressed(style_box_name):
     var style_box_duplicate = get_theme().get_type().get_stylebox(style_name).duplicate(true) # Duplicate subresources?
     self.set_style(style_name, style_box_duplicate)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Perhaps an editor plugin could do this, but I believe this would be used quite a lot, to the extent that this is could be a core functionality.

### Is there a reason why this should be core and not an add-on in the asset library?

The majority of applications that use Godot have some form of UI, and that usually people do some styling on, and currently overriding Styleboxes but only changing a little bit, is tedious.

**Comment by KccbzZ** [comment]
Oh and probably the button would be in the context menu, not like the way I drew it above:
![image](https://github.com/user-attachments/assets/6f74e35d-0798-460d-bcc5-275ffd3090dc)

**Comment by RedMser** [comment]
Alternative implementation could be that you can look at the Styleboxes without even overriding (instead of `<empty>`), but it's read-only. Once you tick the checkmark, it duplicates the theme's Stylebox and allows you to edit it directly. Same could then be implemented for theme constants, colors etc.

**Comment by KccbzZ** [comment]
That also sounds like a nice way to do this. As long as this process is simplified, I'd say the feature is great.

**Comment by KoBeWi** [comment]
Related: #3876

**Comment by KccbzZ** [comment]
Duplicate of #8022

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/8022.
