### ISSUE TITLE
Make 2D/3D suffix after node name consistent

### ISSUE THREAD

**Issue by freerangerstudios** [godotengine/godot-proposals#1025]
**Describe the project you are working on:**
Not project specific, this applies to all projects.

**Describe the problem or limitation you are having in your project:**
I find it hard to remember which nodes have a 2D / 3D suffix and which don't. For example, the position nodes (Position2D and Position3D) both have the suffix while others (like Sprite and Sprite3D) don't.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I think all nodes that have multiple versions for the different dimensions should have a suffix which tells you what dimension the node is made for. 
Example: Sprite would become Sprite2D, while Sprite3D would stay as it is.

This would make it a lot easier to remember since you know that all nodes which have a 2D / 3D counterpart also has a suffix showing that. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I don't know exactly how this works, but I'm imagining that it would just be a class name change or something similar.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:*
Not possible.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, since this is affecting a core feature and I don't think an add-on is able to do that. I also believe that the node suffixes should be consistent, so different styles would just make it even more confusing than it already is.

**Comment by Calinou** [comment]
This was done in the `master` branch last year: https://github.com/godotengine/godot/issues/30736

There are a few exceptions, but Sprite indeed has been renamed to Sprite2D.

Therefore, I'll close this.

**Comment by freerangerstudios** [comment]
I apologize, I should have checked the devlogs to see if it already had been implemented. It's really great that it has though!
