### ISSUE TITLE
Get the mouse cursor's global position in scene

### ISSUE THREAD

**Issue by yoaveini9** [godotengine/godot-proposals#10254]
### Describe the project you are working on

A 2D top down game where the player can shoot projectiles

### Describe the problem or limitation you are having in your project

Having to calculate the mouse's global position by myself with the camera

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A function that return's the mouse's global position in a scene

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
func get_global_mouse_position() -> Vector2:
	var mouse_position_relative = get_viewport().get_mouse_position()
	var screen_center_global = get_viewport().get_camera_2d().get_screen_center_position()
	var half_screen_size: Vector2 = get_viewport().get_visible_rect().size / 2 / get_viewport().get_camera_2d().zoom
	
	var screen_start_global = screen_center_global - half_screen_size
	var mouse_position_global = screen_start_global + mouse_position_relative / get_viewport().get_camera_2d().zoom
	
	return mouse_position_global
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

yes as shown above

### Is there a reason why this should be core and not an add-on in the asset library?

yes I think this should be a core feature because it's engine related, plus many games will use the mouse's global position to instantiate various scenes.

**Comment by AThousandShips** [comment]
Does [`CanvasItem.get_global_mouse_position`](https://docs.godotengine.org/en/latest/classes/class_canvasitem.html#class-canvasitem-method-get-global-mouse-position) give you what you are looking for? Otherwise please add some details on what kind of position you want, as this doesn't really explain what you are looking for (the code explains how you achieve it, but not what it *is*)

**Comment by yoaveini9** [comment]
I want the global position of the mouse, I don't have a canvas layer in the scene, I just want to get the position of the mouse for my player or map or enemy scene

**Comment by AThousandShips** [comment]
You don't need a canvas layer, have you tried using it?

**Comment by yoaveini9** [comment]
I did now thanks
