### ISSUE TITLE
Obtain plugin information by name

### ISSUE THREAD

**Issue by 0x78f1935** [godotengine/godot-proposals#10268]
### Describe the project you are working on

I'm currently working on my first godot4 plugin

### Describe the problem or limitation you are having in your project

Within my dock bottom panel, I would like to display plugin information, such as the version and author. Currently, as far as I know, this isn't directly possible. There are ways to obtain specific information, but it requires some custom coding.

I do have a workaround, but I believe there should be built-in methods within the engine to provide this information easily.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I simply would like to obtain the version, author, description and plugin name by doing something like:
```gdscript
get_plugin("my_plugin").description
```

This keeps my code, clean and readable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My current workaround involves manually parsing the .cfg file to extract plugin information. Here's how it works:
```gdscript
@tool
extends Control
# Set plugin information
func _set_plugin_info() -> void:
    plugin_info = {}
    if FileAccess.file_exists("res://addons/plugin.cfg"):
        var file = FileAccess.open("res://addons/plugin.cfg", FileAccess.READ)
        var content = file.get_as_text()
        file.close()

        # Parse the content as an INI-like structure
        for line in content.split("\n"):
            var parts = line.split("=")
            if parts.size() == 2:
                plugin_info[parts[0].strip_edges()] = parts[1].strip_edges()

        # Access plugin version
        var version = plugin_info.get("version", "x.x")
        var author = plugin_info.get("author", "undefined")
        var description = plugin_info.get("description", "something")
        # Set description
        error_description.text = description
        # Set author
        discord_label.text = "Discord %s" % author
        # Set version tag
        version_label.text = "| Version %s" % version
```

# How the Proposal Will Work

1. **Engine Methods**: Implement methods within the Godot engine to read and parse `.cfg` files. These methods would be similar to the workaround but would be integrated directly into the engine, providing a more seamless and efficient way to access plugin information.
2. **API Design***: Provide a simple API to access plugin information. For example:
```gdscript
var plugin_info = Engine.get_plugin("My Plugin Name")
var version = plugin_info.version
var author = plugin_info.author
var description = plugin_info.description
var ... ... ...
```

# Benefits

- **Ease of Use**: Developers can access plugin information without writing custom parsing code.
- **Consistency**: Standardizes how plugin information is accessed and displayed.
- **Efficiency**: Reduces redundant code and potential errors in manually parsing .cfg files.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As you can see, you need quiet a lot of code to simply read out the `.cfg` file.

### Is there a reason why this should be core and not an add-on in the asset library?

`.cfg` files are an integral part of Godot. Given their significance, it makes sense to implement methods that can read and display information from these files directly. Relying on add-ons for such a fundamental task is unnecessary when it can be seamlessly integrated into the core engine.

**Comment by Calinou** [comment]
You should already be able to use the ConfigFile class to load `plugin.cfg` and read its keys from the `plugin` section.

**Comment by 0x78f1935** [comment]
> You should already be able to use the ConfigFile class to load `plugin.cfg` and read its keys from the `plugin` section.

While it's true that the `ConfigFile` class in Godot can be used to load `plugin.cfg` and read its keys, this approach still has several drawbacks that make the case for a built-in method within the engine:

- **Ease of Use**: The ConfigFile class requires developers to write additional boilerplate code to load and parse the configuration file. A built-in method would streamline this process, making it more accessible, especially for those new to Godot or programming in general.
- **Consistency**: Having a dedicated method for reading plugin information ensures consistency across different projects. It reduces the risk of errors and inconsistencies that can arise from manually parsing the file in various ways.
- **Efficiency**: A built-in method can be optimized for performance and reliability, ensuring that plugin information is read efficiently without the overhead of additional script processing.
- **Future Proofing**: As Godot evolves, having built-in methods ensures that any changes to the configuration format or requirements are handled centrally, without requiring updates to individual scripts across numerous projects.

In my opinion, while the `ConfigFile` class is a powerful tool, having a built-in method for reading any `plugin.cfg` would significantly enhance the usability, consistency, and reliability of accessing plugin information within the Godot engine.

**Comment by KoBeWi** [comment]
> Ease of Use: The ConfigFile class requires developers to write additional boilerplate code to load and parse the configuration file.

ConfigFile is already very easy to use though.
```GDScript
var cfg := ConfigFile.new()
cfg.open("res://addons/plugin/plugin.cfg")
plugin_name = cfg.get_value("plugin", "name")
```
3 lines of code. A few more if you want all info. With a dedicated method you will save 2 lines at most.

> Consistency: Having a dedicated method for reading plugin information ensures consistency across different projects. It reduces the risk of errors and inconsistencies that can arise from manually parsing the file in various ways.

ConfigFile does all the parsing for you. It's consistent.

> Efficiency: A built-in method can be optimized for performance and reliability, ensuring that plugin information is read efficiently without the overhead of additional script processing.

A core method would still likely use a ConfigFile internally (the information is not cached), so there is no real benefit performance-wise.

> Future Proofing: As Godot evolves, having built-in methods ensures that any changes to the configuration format or requirements are handled centrally, without requiring updates to individual scripts across numerous projects.

Again, since ConfigFile does all the parsing, it also handles all format changes. It won't handle field changes, but so does built-in method, which could lose some of its properties.

**Comment by 0x78f1935** [comment]
> 3 lines of code. A few more if you want all info.

Fair, that does work in this particular case. `ConfigFile` matches with how my proposal works and even includes default values. I guess it's more syntax sugar than anything. `get_plugin('External Animator').author` feels more Godot-like.
