### ISSUE TITLE
Make `move_and_collide` and `move_and_slide` not runnable in the editor if `@tool` is attached, or `RigidBody2D` runnable if it's attached with a `@tool`-ed script, in order to achieve coherent behaviors

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [godotengine/godot-proposals#10277]
### Describe the project you are working on

General projects with physics

### Describe the problem or limitation you are having in your project

*I'm not sure whether I should post this as bug or proposal, but it seems more like a proposal...*
Currently, a `@tool`-ed script allows an `PhysicsBody2D` to move in the editor, because we coded:
```GDScript
func _physics_process(delta):
    move_and_collide(velocity * delta) # or move_and_slide()
```
Reload the scene and you will see that your body can move around in the editor mode. However, let's look at how `RigidBody2D`, a kind of`PhysicsBody2D` which will move automatically without `_physics_process`, works in the editor. If we only tag an `@tool` at the top of its script without doing external and extra things, and reload the current scene, it doesn't move at all, because we didn't code its behavior in its script, while it's inner process didn't work either. This causes the incoherence between all `PhysicsBody2D` and `RigidBody2D`.

In my opinion, it's better to make their behaviors coherent in the editor, so that everything can run reasonably.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are two optimizations for this, one of which is ok:
1. Either to make `move_and_slide()` and `move_and_collide()` runtime only, which means that only the runtime can these calls work as usual.
2. Or, making `RigidBody2D` movable in the editor if `@tool` is tagged in its script.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For solution 1: Adding a simple line of source code before executing the main body of `move_and_slide/collide()`:
```Cpp
if (Engine::get_singleton()->is_editor_hint()) {
    // UtilityFunction::print("Cannot call this function in non-runtime mode!"); // Optional
    return;
}
```
For solution 2: Detect if the rigid body has a script which contains `@tool`; if yes, then make the body movable in the editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's impossible to be solved out of source code.

### Is there a reason why this should be core and not an add-on in the asset library?

Same as the previous answer.

**Comment by AThousandShips** [comment]
> It's impossible to be solved out of source code.

Not impossible, you just use `Engine.is_editor_hint`, which is the suggested behaviour if you need to make a node run in the editor

**Comment by AThousandShips** [comment]
If you're still interested in the feature and the workaround isn't sufficient for you you can still keep this open, my feedback isn't necessarily absolute or a rejection of the feature, it's up to you
