### ISSUE TITLE
Support conditional breakpoints

### ISSUE THREAD

**Issue by vPumpking** [godotengine/godot-proposals#10271]
### Describe the project you are working on

Any elaborated game where you need debugging

### Describe the problem or limitation you are having in your project

Godot offers two ways to make breakpoints, one with the red dot on the left, which breaks at the corresponding line:
![image](https://github.com/user-attachments/assets/e33ceb96-71cb-4c80-869f-db666dfccf27)

and another with the `breakpoint` keyword, a lot more flexible since it can be saved in the code and shared between computers:
![image](https://github.com/user-attachments/assets/0d13ebae-253f-4611-b70d-b3d7bf4093db)

The problem is that no matter which way is used, if you place a breakpoint in a function it will **always** trigger it, which means that if you need it to happen only in certain cases, for example when a specific code block is activated or a variable is true, it's not possible.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest a differenciation between red dot breakpoint and in code keyword: `breakpoint` keyword would rather work like any other keyword, and be triggered only when its line and indent is processed at runtime:
this should break only if `trigger_breakpoint` is true
![image](https://github.com/user-attachments/assets/f6e41afa-a489-412d-bfdb-e76b0d573fd6)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

breakpoint would work similar to the break or continue keywords, meaning it would stop the current block execution and bring back to editor rather than just stop when parser reaches the corresponding line.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so

### Is there a reason why this should be core and not an add-on in the asset library?

Parser behavior is core

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/909.
