### ISSUE TITLE
Make "inspect native shader code" available also when selecting shader resources

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#10278]
### Describe the project you are working on

Godot engine

### Describe the problem or limitation you are having in your project

"Inspect native shader code" is available when inspecting a material, but not when inspecting a shader

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make it avialable for shaders too

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add the option in the dropdown

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Native editor feature

**Comment by tetrapod00** [comment]
Made a PR: https://github.com/godotengine/godot/pull/97205.
