### ISSUE TITLE
Do not use redundant member names in enumerations.

### ISSUE THREAD

**Issue by twoco** [godotengine/godot-proposals#10272]
For example: Why `MouseButton.MOUSE_BUTTON_RIGHT` and not `MouseButton.RIGHT`? It's redundant and too much text. I mean you will never have something like `MouseButton.KEYBOARD_KEY_ARROW_RIGHT`.  The context is clear. No need to repeat it again. I see that this was a change from Godot 3 to 4. Why adding enum name to each enum member?

**Comment by dalexeev** [comment]
For native enums, you don't have to use the enum name as a prefix, `MouseButton.MOUSE_BUTTON_RIGHT` and `MOUSE_BUTTON_RIGHT` are the same thing. We can't change this in 4.x for compatibility reasons.

See:

* #1426
* #5624

Also please follow the guidelines described in the README:

>> **Note:** The following points describe requirements for a proposal issue. A [discussion](https://github.com/godotengine/godot-proposals/discussions/new), on the other hand, can be started in any form.
>
> 1. Only proposals that properly fill out the template will be considered. If the template is not filled out or is filled out improperly, it will be closed.

Thanks for the contribution nonetheless!
