### ISSUE TITLE
Allow the render loop to continue when the window is minimized

### ISSUE THREAD

**Issue by pochoco24** [godotengine/godot-proposals#10286]
### Describe the project you are working on

A Twitch Stream Overlay for OBS.

### Describe the problem or limitation you are having in your project

When minimizing the Godot window, the game capture in OBS freezes until I restore the window back.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If Godot stops drawing when minimized to save energy, it would be great to toggle that feature so OBS captures could work.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A boolean in Project Settings to toggle drawing when minimized.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature can be useful for VR games or games that require to draw while minimized.

I've tried to compile a custom godot build to fix this problem, but I can't find what disabled minimized window rendering. (I'm not familiar with C++ neither.)

### Is there a reason why this should be core and not an add-on in the asset library?

I'm unsure if plugins can change engine behavior like this.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/5790.

**Comment by dsnopek** [comment]
In order to solve an XR issue (see PR https://github.com/godotengine/godot/pull/94412), we added a feature (in Godot 4.3-rc1) that will allow you to make Godot keep rendering even if all Godot windows are minimized: [DisplayServer.register_additional_output()](https://docs.godotengine.org/en/latest/classes/class_displayserver.html#class-displayserver-method-register-additional-output)

If an additional output is registered with `DisplayServer`, then Godot will keep rendering.

**Comment by Calinou** [comment]
I suppose what @dsnopek mentioned could be implemented as a project setting, which would register an additional output with a reserved name.

**Comment by pochoco24** [comment]
I tried to capture Godot with OBS while minimized with this commit, but it still freezes in OBS when the window is minimized.

All I have in the scene is an animated moving cube, a camera, and a script:

`extends Node3D

var object = Object.new()

func _ready() -> void:
DisplayServer.register_additional_output(object)`

**Comment by Calinou** [comment]
cc @dsnopek

**Comment by Calinou** [comment]
> an OBS issue (maybe it can't capture the window's content when it's minimized?)

Are you using game capture or window capture in OBS?
