### ISSUE TITLE
Add a way to force `await` upon select functions.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot-proposals#10296]
### Describe the project you are working on

I would like to have my functions complete sequentially in the order that they are called because certain character actions have priority over others.

### Describe the problem or limitation you are having in your project

In this greatly simplified example `action_property1` requires an await call and will defeat playerB if called by playerA, `action_property2` does not require an await call but will defeat playerA if called by playerB:
```gdscript
var winner : set = set_winner
func set_winner(val):
	winner = val
	print(val+" is WINNER!!")

func _ready():
	
	execute_action_properties_of_character("PlayerA")
	execute_action_properties_of_character("PlayerB")

func execute_action_properties_of_character(character):
	if winner == null:
		action_property1(character)
		action_property2(character)

func action_property1(character):
	#maybe a node needs to be loaded and readied here, 
	#like a character is summoning a projectile and setting its animation,
	#or maybe a rayscan or collision check which requires a physics process frame 
	await get_tree().process_frame
	print("property1"+character)
	if character == "PlayerA":
		winner = character
func action_property2(character):
	print("property2"+character)
	if character == "PlayerB":
		winner = character

```

I want playerA to process his actions before playerB, but oh no the output is a complete mess:
```
property2PlayerA
property2PlayerB
PlayerB is WINNER!!
property1PlayerA
PlayerA is WINNER!!
property1PlayerB
```

playerB defeats playerA first and then playerA defeats playerB after he was already declared the winner.

The solution to get the desired order of actions is to spam the await keyword over literally every function call like so:

```gdscript
func _ready():
	#i would also want await calls here because i don't want "Player B" to execute his properties if he is defeated.
	await execute_action_properties_of_character("PlayerA")
	await execute_action_properties_of_character("PlayerB")

func execute_action_properties_of_character(character):
	if winner == null:
		await action_property1(character)
		await action_property2(character)

func action_property1(character): 
	await get_tree().process_frame
	print("property1"+character)
	if character == "PlayerA":
		winner = character
func action_property2(character):
	print("property2"+character)
	if character == "PlayerB":
		winner = character
```

And this gets way more annoying to keep track of the longer the chain of functions are between establishing the order of actors, and having the actions take place. Also certain action properties may trigger other action properties in my project which also adds to the await spam that I find needlessly cumbersome. 

(Note:  There's recursive calls and stuff that's hard to explain which makes implementing a call buffer equally, if not more tedious and prone to user error as adding await to everything. I'd essentially have to keep track of which calls should and shouldn't be added to this buffer to prevent it from locking up.)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a special function type which forces await calls.
The syntax for this could be: `awaitfunc function_name():` that forces calls to `function_name()` to be handled as `await function_name()` by the interpreter.  Also there should be a way to not await on these functions by adding a keyword like `noawait` or something before an awaitfunc call to make it not await.

My only concern is that it could get confusing if you await on a function unexpectedly while debugging, but it beats having to add the `await` keyword to 20-40 calls of functions in a hierarchy because a function at the at the end of said hierarchy needs to be awaited upon.

Something like this would also help in defining which functions need to be awaited upon and which functions do not. 
For my use case this would be enough but there's probably a better solution, all this would effectively do is invert the behavior of select functions in regards to whether it awaits or not.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

How it would look:

```gdscript
func _ready():
	execute_action_properties_of_character("PlayerA")
	execute_action_properties_of_character("PlayerB")
	noawait execute_action_properties_of_character("SpecialException")

awaitfunc execute_action_properties_of_character(character):
	if winner == null:
		action_property1(character)
		action_property2(character)

awaitfunc action_property1(character): 
	await get_tree().process_frame
	print("property1"+character)
	if character == "PlayerA":
		winner = character
awaitfunc action_property2(character):
	print("property2"+character)
	if character == "PlayerB":
		winner = character
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think it would be used often to manage problems related to execution order at a large scale.

### Is there a reason why this should be core and not an add-on in the asset library?

It is related to keywords.

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot-proposals/issues/3901
* https://github.com/godotengine/godot-proposals/issues/5893

**Comment by KnightNine** [comment]
@AThousandShips 
It's exactly #3901 but for a different reason that isn't resolvable by a buffer or queue.

**Comment by AThousandShips** [comment]
Then this is a duplicate, closing, please add any additional ideas or details there
