### ISSUE TITLE
Make `Color.hex` constant

### ISSUE THREAD

**Issue by mageowl** [godotengine/godot-proposals#10294]
### Describe the project you are working on

RPG roguelike with arrays of colors used to modify textures based on skin tone

### Describe the problem or limitation you are having in your project

A constant array provides a performance boost, but is harder to read than using the `Color.hex` method.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make `Color.hex(...)` a constant function so it can be used in constant arrays.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
const MY_COLOR = Color.hex(0xffffff)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, because constant functions cannot be defined with GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

Color is a basic type in GDScript.

**Comment by AThousandShips** [comment]
Do you mean compile time evaluated? Because it can't be `const` because it's `static` and `const` doesn't make any sense for `static` methods, this is more a limitation in the GDScript compiling generally and not specific to `Color.hex`

**Comment by KoBeWi** [comment]
You can use constructor instead of static method
```GDScript
const MY_COLOR = Color(0xffffff)
```

**Comment by mageowl** [comment]
Thanks, I didn't realize this worked. I don't think it's documented.

**Comment by KoBeWi** [comment]
Turns out it's not a constructor, but an implicit conversion operator.
This works too:
```GDScript
const MY_COLOR: Color = 0xffffffff
```
