### ISSUE TITLE
Allow importing 3D models without colliders

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1029]
**Describe the project you are working on:** Godot TPS demo

**Describe the problem or limitation you are having in your project:**

The TPS demo's Blender files contain colliders on some of the meshes. Godot imports them as StaticBody children with CollisionShape nodes. My goal is to get rid of them. I can't figure out how to remove them in Blender, and Godot does not have an import setting for this.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

My proposal is to add an import setting for 3D models to ignore all collider information, such that the imported scene does not contain any PhysicsBody or CollisionShape nodes. Godot already has tons of import options in the "Import" dock to configure meshes, skins, materials, and animations, and more, so I think it is very reasonable to add import options for physics.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

In the "Import" dock, a new checkbox will be added, something like "Import colliders". This checkbox will be enabled by default. If unchecked, Godot does not import colliders or generate physics nodes.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This is not a feature that exists in script, it is an import option.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Yes, because it is an import option and can't be worked around in a script.

**Comment by Calinou** [comment]
What are some possible use cases for this feature? In other words, why do you want to ignore colliders from an imported mesh?

**Comment by aaronfranke** [comment]
Here is an example with a more dire need for this feature. I have this door model (taken from the TPS demo) and it has the ability to open. Godot gives the door StaticBody colliders.

The result is... the door is unusable because you can't walk through it.

![Untitled](https://user-images.githubusercontent.com/1646875/84473728-9202a300-ac57-11ea-945d-1c64b2f83848.png)

**Comment by Calinou** [comment]
@aaronfranke Shouldn't be model be modified so it generates KinematicBodies for the door parts instead of StaticBodies?

**Comment by HeadClot** [comment]
What @aaronfranke is proposing would be useful for me. I have an fighting arena level that has collision outside the bounds that the players cannot get to. The collision is static currently. Being able to just import no collision for these distance meshes would be great as it would save me some performance. :)

**Comment by aaronfranke** [comment]
@vonflyhighace2 I don't see why I should have to edit the 3D model file to get rid of the colliders. I'm not a Blender expert.

**Comment by aaronfranke** [comment]
Closing as rejected. I believe the current stance is that the files you give Godot should be correct, and that if a model has undesired collisions, the model should be edited to remove them. Which, honestly, is fine. This proposal was fueled by my short-term annoyance with Godot doing something I didn't want and my stubbornness to not edit the model.

As far as I understand it, the import options are primarily designed to handle cases where the file is using different conventions and those need conversion, not to make lots of changes to the model.

**Comment by aaronfranke** [comment]
Implemented by https://github.com/godotengine/godot/pull/96745

Note: Implements what was originally requested, not the follow-up discussion's expanded feature set, which is rejected.
