### ISSUE TITLE
Provide "Do nothing for missing tracks" for deterministic option in AnimationTree

### ISSUE THREAD

**Issue by omercemcicekli** [godotengine/godot-proposals#10317]
### Describe the project you are working on

FPS game

### Describe the problem or limitation you are having in your project

Currently, I am trying to add a rotation to my root bone when firing the gun. Since the deterministic option automatically considers missing tracks as "0", fp arms act weirdly(well, not weirdly, they are returning to 0 position, since the animation missing the position track). Firing the gun only modifies root bone's rotation and does not modify the position since it's an additive animation. But deterministic option messes this up. 

I can't use non-deterministic because blending is producing unexpected results. I'll also need this feature when the gun out of ammo and slide stays at the back. I can't do this since it will return to the 0 position when I switch to the idle pose(well, I can certainly provide more animations but does not make sense to double the animation amount for this).

In Blender, right hand is connected to the gun root bone with "child of" modifier.

https://github.com/user-attachments/assets/c21c4fa2-f6ef-4ef4-8d67-85b576dd513a

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Provide "Do nothing for missing tracks" option just like the non-deterministic.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Not sure about this one... I would guess this needs a bit of overhauling the AnimationMixer

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it will take lots of work to get around this and I would think it would be used frequently.

### Is there a reason why this should be core and not an add-on in the asset library?

AnimationTree is a core part of the engine.

**Comment by Calinou** [comment]
cc @TokageItLab

**Comment by TokageItLab** [comment]
Reading at the use case, it sounds quite like a case where root_motion should be used.

Also, when blending a single track, it is theoretically impossible for Deterministic Blending and Non-Deterministic Blending to coexist. It might be possible to have a Deterministic option for each track, but not during 4.x, and you would have to split the animation in two.

However, for the proposed use case, as I said above, root_motion already exists, so this should not be a problem. See https://docs.godotengine.org/ja/4.x/classes/class_animationmixer.html#class-animationmixer-method-get-root-motion-position
