### ISSUE TITLE
get_child_by_class to be added to Node

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot-proposals#10328]
### Describe the project you are working on

A card game.

### Describe the problem or limitation you are having in your project

I use Nodes to set up a component based system. I want to add and retrieve components by class to avoid using strings, to keep my project as strictly-typed and refactor friendly as possible.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

get_child_by_class would retrieve the first node of specified class from the children, acting like GetComponent in component based systems. 

Additionally get_children_by_class would also be useful in other contexts.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
func increase_entity_damage(entity : Entity):
	var damage_component : Damage = entity.get_child_by_class(Damage)
	damage_component.set_base_amount(damage_component.get_base_amount() + 1)
```

Related proposals: #7498 #5512

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is currently possible to create this function manually like this:
```gdscript
func get_child_by_class(parent: Node, class_type: Variant):
	for child in parent.get_children():
		if is_instance_of(child, class_type):
			return child
	return null
```
but having it as part of Node in c++ would be superior.

### Is there a reason why this should be core and not an add-on in the asset library?

Changes Node.

**Comment by AThousandShips** [comment]
Thank you for your proposal, however this is completely covered by:
* https://github.com/godotengine/godot-proposals/issues/7498

Closing, please add your feedback to that proposal
