### ISSUE TITLE
Split editor_doc_cache.res into version

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot-proposals#10326]
### Describe the project you are working on

Any

### Describe the problem or limitation you are having in your project

My main project is developed on 4.2.2, but after opening the editor of version 4.3 for testing, the next opening of the editor 4.2.2 causes an error constantly due to the difference in the versions of editor_doc_cache.res in 4.2 and 4.3, more details about the problem can be found here - https://github.com/godotengine/godot/issues/93806

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It might be worth splitting editor_doc_cache.res into versions, such as editor_doc_cache.res and editor_doc_cache_v2.res, to fix this error.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

same as above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This is part of the engine.

**Comment by Calinou** [comment]
I don't think we need a proposal for this, as I consider this to be bug territory (and is already covered by the original issue).
