### ISSUE TITLE
Add target FPS value to visual profiler

### ISSUE THREAD

**Issue by DanielKinsman** [godotengine/godot-proposals#10369]
### Describe the project you are working on

XR projects that run on different headsets, e.g. meta quest, valve index

### Describe the problem or limitation you are having in your project

The visual profiler has a handy reference line at 60Hz / 16.66ms, but for many projects that isn't going to be the target. Console games might target 30Hz, XR projects typically target 72Hz or 90Hz.

For XR in particular stutters above the target can cause motion sickness so being able to easily identify when you are exceeding the target is nice.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an editor setting to allow the reference line to be set at a customizable level.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I've already implemented it here: https://github.com/DanielKinsman/godot/tree/profiler-target-fps
Would need translations added.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

The visual profiler is a core feature

**Comment by clayjohn** [comment]
Great idea! Feel free to open a pull request directly.
