### ISSUE TITLE
Add support for AI image upscaling at load-time

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-proposals#1037]
**Describe the project you are working on:**
A 3D Platform

**Describe the problem or limitation you are having in your project:**
Long time for texture importing

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Using a compressor integrated with the engine which takes almost no time to import, compressing it to reduce final game filesize, and still maintaining quality.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

As reduz mentioned in the last reunion, using[ betsy's GPU Compressor](https://github.com/darksylinc/betsy) inside the engine could be the best solution for now, and I was thinking 
about using a recent technology in conjunction with betsy: UPSCALING AI as shown in this [video (all necessary material to implement is on description)](https://www.youtube.com/watch?v=HvH0b9K_Iro) , so there are two approaches i can think of now:

![Screenshot from 2020-06-11 11-30-34](https://user-images.githubusercontent.com/58845030/84399587-693ac900-abd7-11ea-943e-7207383e9d48.png)
this one is my favorite:
* User Import image
* The Ai downscale it (the most it can without losing information) [must have project settings?]
* Then Bet's do its work and communicate with engine

![Screenshot from 2020-06-11 11-32-33](https://user-images.githubusercontent.com/58845030/84399876-bdde4400-abd7-11ea-9fc6-ad418132e751.png)
* User Import image
* Betsy do its work
* communicate with the engine
* AI Upscale only is called when necessary (showing in-game,export,etc..)

I expect I've been clear here! please let me know you guys opinion...
ps: sorry for any mockup error, I dont know how the engine works behind the scenes...
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This will be useful for everyone

**Is there a reason why this should be core and not an add-on in the asset library?:**
MUST/HAS to comunicate with core with less barriers as possible for performance/time reasons

**Comment by Calinou** [comment]
AI-based upscaling takes a lot of time and is difficult to integrate into the engine. (Most AI image upscaling suites are either proprietary or written as standalone Python scripts.)

I think this is better left to specialized tools.

**Comment by Calinou** [comment]
Closing due to lack of support. AI upscaling can (and should) generally be preformed offline using tools like https://github.com/JoeyBallentine/ESRGAN.
