### ISSUE TITLE
Add a way to make `RegEx` compilation quiet (i.e. not print an error to stdout).

### ISSUE THREAD

**Issue by Germenzi** [godotengine/godot-proposals#10381]
### Describe the project you are working on

Search field, wich allows user to search using regex. 

### Describe the problem or limitation you are having in your project

Currently there is no way to hide regex compilation error, so if regex code provided by user, one can't validate it without error printing in stdout.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a second parameter to `RegEx.compile` and `RegEx.create_from_string` named `show_error` with `true` default value.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Samples:
```gdscript
var regex := RegEx.create_from_string("abc)") # pritns "3: unmatched closing parenthesis" to debugger
var regex_quiet := RegEx.create_from_string("abc)", false) # no prints
```
Same in `RegEx.compile`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/95212.
