### ISSUE TITLE
When going into editor settings don't darken main editor

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#1038]
**Describe the project you are working on:**

N/A as it works for any project

**Describe the problem or limitation you are having in your project:**

When you enter editor settings main editor darkens colour making it hard  to adjust settings the way you want them 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

By removing this behaviour you will improve users ability to finetune it. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Regular editor
![1](https://user-images.githubusercontent.com/30668026/84415019-13cbdf80-ac0a-11ea-827b-021ce4a057a4.PNG)

Editor when settings are open
![2](https://user-images.githubusercontent.com/30668026/84415030-16c6d000-ac0a-11ea-9543-eedd5a2c6283.PNG)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

In every project.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Yes it's a core feature

**Comment by bruvzg** [comment]
There's "Dim Editor On Dialog Popup" option in "Editor Settings" → "Interface" → "Editor" to disable this behavior.

**Comment by Feniks-Gaming** [comment]
Thanks
