### ISSUE TITLE
Add INTERPOLATE_NONE option for Image class resize()

### ISSUE THREAD

**Issue by naturally-intelligent** [godotengine/godot-proposals#1039]
**Describe the project you are working on:**

Low-res pixel art game.

**Describe the problem or limitation you are having in your project:**

Need to capture higher-res screenshots of low-res pixel art screens, but when calling resize(), there is no interpolation option for "no interpolation" which is required to upscale pixel art properly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Having no interpolation allows pixel-perfect resizing (assuming exact integer scaling multiples are passed)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

INTERPOLATE_NONE in Image class:
https://docs.godotengine.org/en/stable/classes/class_image.html#enum-image-interpolation

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

For now, it can be used with an outside image utility like GIMP or ImageMagik

**Is there a reason why this should be core and not an add-on in the asset library?:**

Is too low-level to be an asset library.

**Comment by Calinou** [comment]
`INTERPOLATE_NEAREST` is what you're looking for. There's no such thing as "no interpolation" when resizing images in graphics editing; otherwise, you'd have blank space between pixels.

**Comment by groud** [comment]
Yes, you should use Image.INTERPOLATE_NEAREST, this is what you are looking for.

**Comment by naturally-intelligent** [comment]
Thanks @Calinou and @groud, that works! :)

Funny, I tried all the others but that one, based on the documentation (https://docs.godotengine.org/en/stable/classes/class_image.html#enum-image-interpolation): "If the image is resized, it will be pixelated." I guess that could be interpreted right or wrong (I interpreted it wrong)

**Comment by groud** [comment]
Ah yes, it might be a little bit unclear. You can open an issue in the [godot docs repo](https://github.com/godotengine/godot-docs/) about it if you want.
