### ISSUE TITLE
Add possibilty to get all children and children's children etc. of a node

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1040]
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
I can't change a property of all nodes in the scene with few code.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
You will get all children and children's children etc. of a node.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`var all_nodes = get_all()`
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Maybe a little bit more than "a few", but yes.
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, it is useful for every project.

**Comment by SIsilicon** [comment]
> @MaaaxiKing said:
> **If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Maybe a little bit more than "a few", but yes.

If this can be implemented in code, then it isn't very important to be implemented in core. You could use the following function to get what you want.
```
func get_all(node:Node):
    var all_children := []
    for child in node.get_children():
        all_children.append(child)
        for grand_child in get_all(child):
            all_children.append(grand_child)

    return all_children
```

**Comment by groud** [comment]
If you need to do a processing on a node and all its children, you could use the `propagate_call(...)` method. See https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-propagate-call

**Comment by MaaaxiKing** [comment]
I've never used notifications before so I don't know at all what this does.

**Comment by MaaaxiKing** [comment]
I want to set the pause mode of every node in the scene tree to stop but
```
func _ready():
	propagate_call("pause_all")
	get_tree().paused = true

func pause_all():
	pause_mode = PAUSE_MODE_STOP
```
doesn't work, what's wrong?

**Comment by groud** [comment]
`propagate_call` tries to call the function on the target node, not on the one calling the function.
You should probably use something like that :
```
propagate_call("set", "pause_mode", PAUSE_MODE_STOP)
```

**Comment by MaaaxiKing** [comment]
Firstly I think `pause_mode` isn't given as a String but what to write in `set()` then? I searched for "godot propagate_call" on the internet but as far as I've come, there's no tutorial.

**Comment by groud** [comment]
I don't understand what you mean.
What my proposed code does is the equivalent of calling `set("pause_mode", PAUSE_MODE_STOP)` on each child. The "pause_mode" is passed as a string as it is the name of the pause_mode property.

**Comment by MaaaxiKing** [comment]
Right, thanks a lot. I know this repository isn't used for asking questions but I thought it would be too cumbersome to ask a question at https://godotengine.org/qa/ask.

**Comment by groud** [comment]
Alright, I consider this issue as solved then. 

If anyone has a use case which could not be covered by the propagate_call method, please reopen a proposal explaining why the current implementation is not sufficient.

**Comment by MaaaxiKing** [comment]
However, how to call a function like `show()` then on each node?

**Comment by groud** [comment]
> However, how to call a function like show() then on each node?

`propagate_call("show")`

**Comment by MaaaxiKing** [comment]
I'm not really into this function yet xD

**Comment by MaaaxiKing** [comment]
Ohh, just now I understood, bruh. I thought I'd have to declare the function I want to call. I don't know if I am the only person who didn't quickly understand this function but if not, a better documentation would be greatly appreciated!
