### ISSUE TITLE
Project presets.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#10404]
### Describe the project you are working on

not important

### Describe the problem or limitation you are having in your project

Every time you create a new project you have to configure the project options. Set the fps, the options for pixelart etc...

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Enable the option to choose a preset and custom project configuration when creating a new project.

Example:
To create a retro game I choose my default project template "retro".
This configuration has the fps at 30, the resolution at 320x240 etc...

This way I don't have to configure everything every time I start a new project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

After pressing the button to generate new project Godot offers the selection of templates. Initially there are no custom templates, you can create one and then choose it to get the project configuration quickly.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think not.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know if this can be done with an add-on

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot-proposals/issues/8205

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1481.
