### ISSUE TITLE
Add `std::initializer_list` constructors for containers

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot-proposals#10407]
### Describe the project you are working on

-

### Describe the problem or limitation you are having in your project

-

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot only recently switched from C++03 to C++14. As such it is understandable that a lot of the codebase is still mostly written in the older C++ standard. 

I think it would make sense to add std::initializer_list constructors to atleast the Container types to allow for more idiomatic construction and make it easier to target Godot via C++. `Vector` and `LocalVector` already have them so its just a matter of adding it to other containers like `Dictionary` and `Array`.

Also for some odd reason there is a `varray` function which takes a variable number of typed parameters (which by the way really should be passed via forwarding reference and then forwarded to the `Variant` ctor) and also returns a `Vector<Variant>` instead of the `Array` you might expect based on the name.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
Array(const std::initializer_list<Variant>&)
Dictionary(const std::initializer_list<Pair<Variant,Variant>>&)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1357.
