### ISSUE TITLE
Make the Sprite Frames Editor automatically "guess" the amount of rows and columns in a Sprite Sheet when loading it instead of defaulting to 4x4

### ISSUE THREAD

**Issue by TheSofox** [godotengine/godot-proposals#10415]
### Describe the project you are working on

A cartoony 2D platformer. It has a lot of sprite sheets due to the wide variety of animations in the game.

### Describe the problem or limitation you are having in your project

When adding animations to `SpriteFrames`, I click `Add Frames from a sprite sheet` and when I open up my spritesheet, the game divides it into a 4x4 grid every single time. I then have to manually enter in how many rows and columns the sprite sheet has so that I can then properly select frames from the sheet. While it's understandable I would have to do this to some extent, some of the sprite sheets I have make it very obvious how many rows and columns they are meant to have, even from a casual glance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The desired feature is that when you load a sprite sheet for the first time, the engine should make a "good guess" at how many rows and columns the sheet has. If it works for the majority of cases, it'll save the user time and energy and make it a bit more convenient. In the cases where the guess is wrong, the user will have to adjust the values manually, which is what they would have to do anyway unless their sprite sheet happened to be a 4x4.

To make a guess, I will make some assumptions:
1. The sprites are evenly spaced around the sprite sheet
2. They are not tightly packed together
3. That there is a consistent background colour to the sheet.

Given the above assumptions, the algorithm would work as follows:
1. When image is loaded, the top left pixel is sampled. This is assumed to be the background colour.
4. The image is scanned from left to right to find any full columns of pixels that consist only of that background colour. These are assumed to be the boundaries between columns of the sprite sheet.
5. These bands are counted up to give an estimated `column` count
6. The same process is used to scan the image from top to bottom to calculate `row` count

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My code would be placed in `sprite_frames_editor_plugin.cpp`:

```
Size2i SpriteFramesEditor::_estimate_sprite_sheet_size(const Ref<Texture2D> texture) {
	Size2i default_size = Size2i(4, 4);
	Ref<Image> image = texture->get_image();
	Size2i size = texture->get_size();

	Color assumed_background_color = image->get_pixel(0, 0);

	bool contiguous_lines = true;
	int division_count = 1;
	for (int x = 0; x < size.x; x++) {
		bool background_vert_line = true;
		for (int y = 0; y < size.y; y++) {
			if (assumed_background_color != image->get_pixel(x, y)) {
				background_vert_line = false;
			}
		}
		if (contiguous_lines) {
			if (!background_vert_line) {
				contiguous_lines = false;
			}
		} else {
			if (background_vert_line) {
				contiguous_lines = true;
				division_count++;
			}
		}
	}
	if (contiguous_lines && division_count > 1) {
		division_count--;
	}
	default_size.x = division_count;

	contiguous_lines = true;
	division_count = 1;
	for (int y = 0; y < size.y; y++) {
		bool background_horiz_line = true;
		for (int x = 0; x < size.x; x++) {
			if (assumed_background_color != image->get_pixel(x, y)) {
				background_horiz_line = false;
			}
		}
		if (contiguous_lines) {
			if (!background_horiz_line) {
				contiguous_lines = false;
			}
		} else {
			if (background_horiz_line) {
				contiguous_lines = true;
				division_count++;
			}
		}
	}
	if (contiguous_lines && division_count > 1) {
		division_count--;
	}
	default_size.y = division_count;

	if (default_size.x == 1 && default_size.y == 1){
		default_size.x = 4;
		default_size.y = 4;
	}
	return default_size;
}
```
An adjustment later in the code would be needed to call this function and use its values instead of the arbitrary value of `4`

Modification to `void SpriteFramesEditor::_prepare_sprite_sheet(const String &p_file) {`
```
-                       split_sheet_h->set_value(4);
-                       split_sheet_v->set_value(4);
-                       split_sheet_size_x->set_value(size.x / 4);
-                       split_sheet_size_y->set_value(size.y / 4);
+                       const Size2i split_sheet = _estimate_sprite_sheet_size(texture);
+                       split_sheet_h->set_value(split_sheet.x);
+                       split_sheet_v->set_value(split_sheet.y);
+                       split_sheet_size_x->set_value(size.x / split_sheet.x);
+                       split_sheet_size_y->set_value(size.y / split_sheet.y);
```

I have already tested this code with my game project. It successfully divides up most of my sprite sheets and I am happier using it than the alternative.

Here is an example of a sprite sheet that the algorithm accurately guesses the amount of rows and columns: https://opengameart.org/content/lpc-curly-hair-elven-ears-white-cape-with-blue-trim-and-more

![image](https://github.com/user-attachments/assets/c9cdc85f-70b2-4f5a-8e8d-e3c66a7eb504)

Another sprite sheet here: https://opengameart.org/content/explosion-sheet

### If this enhancement will not be used often, can it be worked around with a few lines of script?

`SpriteFrames` and its editor is built into the engine. It can't be modified with GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a relatively small change and tightly integrated into the engine.

**Comment by AThousandShips** [comment]
Related:
* https://github.com/godotengine/godot-proposals/issues/7021
* https://github.com/godotengine/godot/pull/80448

**Comment by TheSofox** [comment]
Created Pull Request for this proposal: https://github.com/godotengine/godot/pull/95475 Since I'd coded it already, I felt best to make it available.
