### ISSUE TITLE
Make all bones automatically selected in the filter menu of animation nodes

### ISSUE THREAD

**Issue by hayde26904** [godotengine/godot-proposals#10424]
### Describe the project you are working on

A 3rd person 3D survival game.

### Describe the problem or limitation you are having in your project

When the "Enable Filtering" checkbox is clicked, it disables all the bones by default so when I want to only filter out a couple bones from the bone filter of an AnimationNode, I have to manually reselect a lot of bones.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Instead of having all the bones deselected by default, have them all selected by default but have the checkboxes disabled until you check the "Enable Filtering" checkbox.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![godotdiagram](https://github.com/user-attachments/assets/977896c4-52f0-4f38-847b-6926be681aaa)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This enhancement will be used often. Trust.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a small change that makes a lot more sense than the current implementation and would improve developer experience out of the box.

**Comment by Calinou** [comment]
cc @TokageItLab

**Comment by TokageItLab** [comment]
Most of problem has been already solved by 4.3 with https://github.com/godotengine/godot/pull/76654.
