### ISSUE TITLE
why the  .scn file must be saved before playing everytime?

### ISSUE THREAD

**Issue by imdjs** [godotengine/godot-proposals#1044]
why the  .scn file must be saved before playing in the editor everytime? even the scene objects are not be modified, only modify the script.
sometimes the .scn file  is very large that will take a long time to save(it's bad for the hard disk with frequently writting large file also). is there any setting to avoid saving the .scn file?
if the .scn file has been modified it should be saved,but if the .scn file is not been modified, it's not necessary to be saved. usually we only modify the .gd file but not the .scn file.

**Comment by Jummit** [comment]
In the Project Settings under `Run` > `Auto Save` you can disable `Save Before Running`.

**Comment by imdjs** [comment]
thanks this solve the problem.
