### ISSUE TITLE
Add a new solid color TextureResource 

### ISSUE THREAD

**Issue by Burloe** [godotengine/godot-proposals#10440]
### Describe the project you are working on

A top down pixel art detective RPG

### Describe the problem or limitation you are having in your project

I often use solid colored sprites and textures as placeholders or as backgrounds and such. Instead of creating several .png's and cluttering my project, I found I was able to generate them in Godot by creating a Gradient2D > Delete one of the gradient colors > color the remaining one whatever I want. 

This is simple enough but really cumbersome to work with as anytime you want to make a change, you have to press the node > texture > gradient > gradient color > color square just to change the color. When you duplicate a node you have to make the texture and gradient unique so they don't share gradient color. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This could be a lot easier by adding a new texture resource called "SolidTexture" or something that just has a single solid color. There's so much that can be done with a simple solid colored rect and the fact that you don't need to open up an image editor or something to create and clutter a project with placeholder files is invaluable. I actually use this to create particle textures as well.  

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It's simply a texture resource like all others but with a single color picker square. 
![Sprite-00025](https://github.com/user-attachments/assets/1f866659-f6b7-48c6-b8f7-bd3413a780c2)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Could do this with a tool script to automate the setup process by assigning a saved Gradient2D.tres file to a TextureRect. Also making an export variable that updates the gradient color. Would still be easier with a versatile and simple solid color solution.

You can also make a 1x1px white Gradient2D and use the modulate property to achieve the same result. I just think it'd be more intuitive for newcomers to see the option to create one where you create similar resources rather than figuring it out by jumping through hoops to and find workarounds. 

### Is there a reason why this should be core and not an add-on in the asset library?

This is such a no-brainer in my opinion. How often would it be easier to be able to generate a solid color in the engine rather than having to make one in a third party software? Need to make a 3x1 pixel slightlyh blue line for rain particles? Just create a new SolidTexture resource, specify it's size and pick a color. Want to make a panel frame and be able to modulate the background inside the frame for UI? Create a SolidTexture resource on a TextureRect with a 9PatchRect as a child for the frame. Now you can recolor the backing independently.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/9956

Please add any additional information there
