### ISSUE TITLE
Add a changed signal to Array and Dictionary Variants

### ISSUE THREAD

**Issue by BlackShift** [godotengine/godot-proposals#10478]
### Describe the project you are working on

I'm working on a RPG combat system, there are quite a lot of custom resources and classes used.

### Describe the problem or limitation you are having in your project

I can't monitor the state of an Array and if it was changed or modified via code.
```gdscript
var someArray:Array:
	set(value):
		print("Array changed!")
	
func _ready():
	#Setter gets called
	someArray = Array()
	#Setter doesn't get called
	someArray.append("test")

```
This is expected behavior, but can only be solved by wrapping Array's methods, which results in a lot of extra methods.

Resources by default have a changed signal, and you could in theory wrap all of the Array's methods to have an emit_changed(), but it would much more elegant by having a changed signal built into Array

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a `.changed` signal to array and dictionaries.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
var someArray:Array:
	set(value):
		someArray = value
		someArray.changed.connect(_on_array_changed)

func _on_array_changed():
	print("Array changed")
	pass #Update something, like queue_redraw()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It could be wrapped around using an custom object class, but the inspector interaction may get ugly.

### Is there a reason why this should be core and not an add-on in the asset library?

Variants are core.

**Comment by AThousandShips** [comment]
This wouldn't be possible with the current system, only `Object`s have signals, this would require a lot of rework to be possible, and it would be very performance heavy as well as the `changed` signal on resources is far less general and isn't fired on *every* change to it, a change in an `Array` or a `Dictionary` would be *far* more common and each emission of a signal takes some degree of performance, even if it doesn't have any connections, multiply that by *a lot* and that's almost guaranteed to slow down general performance of the engine (depending especially how signals for non-`Object`s would even work)

**Comment by Mickeon** [comment]
I think something like an underlying function called whenever an array index is accessed would be more suitable for these purposes. 
- See https://github.com/godotengine/godot-proposals/discussions/8070
