### ISSUE TITLE
Implement lightmap antialiasing for static shadows

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#10489]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

When baking lightmap for static lights, the lightmap resolution can sometimes be insufficient for especially thin objects. This is especially visible in https://github.com/godotengine/godot/pull/89919#pullrequestreview-2244353831.

![](https://github.com/user-attachments/assets/9cd57870-d4b5-498d-957a-ff074d067d34)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Simply take a few more shadow samples when baking.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When baking, instead of taking one sample, take multiple samples slightly offset on a plane perpendicular to light direction. This makes sure that a pixel in the lightmap averages out any sudden change in the area it covers and make the shadows a little more nice to look at.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Lightmap baking is core

**Comment by clayjohn** [comment]
I have a work in progress branch already: I should have a PR momentarily https://github.com/clayjohn/godot/tree/Lightmapper-AA-direct-light

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/95828.
