### ISSUE TITLE
Add depth aware upscaling for post-processing effects

### ISSUE THREAD

**Issue by Rytelier** [godotengine/godot-proposals#10497]
### Describe the project you are working on

3D game

### Describe the problem or limitation you are having in your project

Post-processing effects such as global illumination, ambient occlusion produce very nasty looking pixelization around edges when running at half resolution.
![image](https://github.com/user-attachments/assets/97044046-a729-48ff-81c8-edc13ac8d34c)
Issue can be solved by setting them to use full resolution, but it affects performance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add depth aware upscaling - method of upscaling screen buffers from lower resolution to full using depth buffer as guidance on how the pixel should cover the areas, resulting in smoothed edges.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When an effect is set to render at lower resolution, an additional filter pass is applied to the effect buffers that upscales them before being used in the render.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can't be added in a script.

### Is there a reason why this should be core and not an add-on in the asset library?

Improves quality of built-in effects.

**Comment by Calinou** [comment]
I thought bilateral upscale was already used for SSAO, or maybe that was only in the 3.x implementation of SAO (4.x uses ASSAO).

**Comment by clayjohn** [comment]
Here is the current upscaling code for GI:
https://github.com/godotengine/godot/blob/da5f39889f155658cef7f7ec3cc1abb94e17d815/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1578-L1602

it looks like we only take normals into account

**Comment by Rytelier** [comment]
It looks like SSAO has upsampling, but still has some flaws
![image](https://github.com/user-attachments/assets/c3b6beb7-d33a-4fac-a8a6-86184e5f0e55)
![image](https://github.com/user-attachments/assets/17e01237-3048-4b9a-a262-68177bed0c3f)
VoxelGI/SDFGI looks like the upscaling just doesn't work at all. Probably it needs a bug report in that case?

> Note that using TAA or FSR2 does a good job of hiding artifacts on half-resolution GI buffers in my experience.
The visuals should look good without the need of TAA.

**Comment by clayjohn** [comment]
> VoxelGI/SDFGI looks like the upscaling just doesn't work at all. Probably it needs a bug report in that case?

I think so, yes

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/95865, as this is considered a bug.
