### ISSUE TITLE
Add export variable unit hints to Inspector

### ISSUE THREAD

**Issue by ShawnHardern** [godotengine/godot-proposals#10498]
### Describe the project you are working on

A game prototype that makes heavy use of the inspector in the godot editor.

### Describe the problem or limitation you are having in your project

While prototyping a game, I often change various variables such as speeds, angles, pixel values, and other parameters directly in the Inspector to modify and fine-tune my game mechanics.

The Inspector allows me to quickly and easily adjustment these values during development, but a key limitation I encounter is the lack of clarity regarding the units of these variables.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose extending the existing PropertyHint system in Godot (both in GDScript and C#) to allow for an additional unit hint to be displayed next to exported variables in the Inspector. This unit hint would provide context about the expected units of measurement (e.g., m/s, px, deg) for specific variables, making it easier for developers to understand and adjust their values directly in the Inspector.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I propose extending the existing PropertyHint system in Godot (both in GDScript and C#) to allow for an additional unit hint to be displayed next to exported variables in the Inspector. This unit hint would provide context about the expected units of measurement (e.g., m/s, px, deg) for specific variables, making it easier for developers to understand and adjust their values directly in the Inspector.

Possible Gdscript Example
```
@export_unit("px") var height
```
Possible C# Example
```csharp
[Export(PropertyHint.Unit, "px")]
public int height{ get; set; }
```

Possible Screen Mockup #1
![Mockup1](https://github.com/user-attachments/assets/6bebf82d-1365-425a-b5fa-df6bd084fda0)
Possible Screen Mockup #2
![Mockup2](https://github.com/user-attachments/assets/c4fdf835-8d69-41fa-ab6d-98e3f02dbae0)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't believe there is currently a way to do this

### Is there a reason why this should be core and not an add-on in the asset library?

It relates to how the core editor currently works

**Comment by AThousandShips** [comment]
Why would you need a *separate* unit displayed beyond the existing unit suffix?

**Comment by Castro1709** [comment]
I think maybe you are not aware of it but you can do that with the suffix hint like this:
```
@export_range(0, 100, 1.0, "suffix:px") var pixel_range : float = 80.0
```

**Comment by AThousandShips** [comment]
Or with `@export_custom` (not sure if there's a direct equivalent in C#, not familiar with exports there)

**Comment by ShawnHardern** [comment]
Hey @Castro1709 and @AThousandShips, 👋🏻 

Thanks so much for bringing this to my attention 😄 . I was referring to the information available in  [GDScript exported properties docs](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_exports.html) and [C# exported properties docs](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_exports.html), but I didn’t come across this feature there. 

I will investigate this further and will update the documentation to include this information if appropriate.

**Comment by AThousandShips** [comment]
Closing as already implemented, thank you for your proposal nonetheless

**Comment by ShawnHardern** [comment]
> Closing as already implemented, thank you for your proposal nonetheless

Thanks for your time @AThousandShips, I have created [docs PR #9785](https://github.com/godotengine/godot-docs/pull/9785) to surface this functionality better
