### ISSUE TITLE
Option for KinematicBody to enable collision from its complete Node tree (grand children included)

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot-proposals#1049]
**Describe the project you are working on:**
Currently working on a 3d 3rd person project.

**Describe the problem or limitation you are having in your project:**
I need a collision shape structure that follow Player animations at least in a rough manner. I have set NodeAttachments to body parts to add their collision shapes. However, I can't make Player to inherit from KinematicBody class because it disables all except direct children  collision shapes.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I wish a kinematic body had the option to enable all grand children collision shapes. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If we have the structure:
-kinematic 0
- - collision 0
- - kinematic 1
- - - collision 1
- - kinematic 2
- - - collision 2

then there should be an option for kinematic 0 to enable all collision 0, 1, 2 shapes for collision detection. In current implementation collision 1 and 2 are disabled.
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know a way to enable this in few lines of code
**Is there a reason why this should be core and not an add-on in the asset library?:**
It enables making collision to follow animations at least in a rough manner.

**Comment by KoBeWi** [comment]
You can put all the colliders under your root node and use RemoteTransform2D to push the positions/rotations from animated parts.

**Comment by jcarlosrc** [comment]
Seems that for each collision-node couple: I would need to first get collision - bone transformation differences for translation and rotation and apply it every frame after copying bone transformation. This way I could get collision to follow bone animation. This for each bone. Seems there should be a built-in option.

Yes, seems a duplicate of #535. Closing.
