### ISSUE TITLE
Consecutive unary addition looks like it should be Pre-increment

### ISSUE THREAD

**Issue by BlakeKessler** [godotengine/godot-proposals#10501]
### Describe the project you are working on

N/A (doing a code review for a friend). 

### Describe the problem or limitation you are having in your project

Pre-increment and post-increment operators are (IIRC) intentionally not part of GDScript, but the unary addition operator is part of it. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To prevent confusion, this should cause either an error or a warning.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```cpp
if (codeArr[i] == '+' && codeArr[i + 1] == '+') {
   log_gdscript_error("There is no pre-increment in GDScript");
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be trivially avoided if you already know that there is no pre-increment, but is an extremely subtle logic error if you don't already know.

### Is there a reason why this should be core and not an add-on in the asset library?

It is a small modification to GDScript itself to help find an extremely subtle logic error.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/8829.
