### ISSUE TITLE
Implement a new node called "DialogueCore" that allows to conversate with NPCs or even trigger events.

### ISSUE THREAD

**Issue by PeeledChairStudios** [godotengine/godot-proposals#10511]
### Describe the project you are working on

A 3D extraction shooter with RPG elements.

### Describe the problem or limitation you are having in your project

Every time I want to make a dialogue with an NPC, I have to run an independent check. I can share this function if I create a script above the NPC behavior. However, this would make me have to manually repeat the responses for every NPC that replies to the same dialogue.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To solve this problem I created a node that works as a brain for a dialogue system using two new types of resources...

**The DialogueCore**

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The DialogueCore is a node added to the three of an NPC or a trigger object, it has an array of a resource called `Phase` (maximum 128 but this quantity might change) and each `Phase` has an array of a resource called `Response`. The purpose of this node is to receive a String from a player or another trigger object, then the node will run a check and will reply by returning the String of the correspondent dialogue in a function or sending it through a signal.

The array of `Phase` in the DialogueCore is called `phases`, aside from it, the DialogueNode contains an int called `current_phase` that determines in which `Phase` of the `phases` runs the check.

The array of `Response` in `Phase` is called `acceptable_dialogues`, aside from it, the `Phase` contains a String called `default_response` that contains the default response and an int called `default_phase_to`, in case the check fails the `default_response` will be returned or sent and the `default_phase_to` will be the new phase.

The `Response` resource contains two Strings called `dialogue` and `reply` where the `dialogue` it's the String to match with the received String on the DialogueCore and `reply` it's the String to send back with said node, also contains an int called `phase_to` that determines which `phase` the DialogueCore will be set after sending the reply.

The node works like this: 

The DialogueCore node receives a String:

**PlayerScript**:
```
var NPC : DialogueCore #Imagine this is an NPC found in the level of your game.

var player_name : String #Imagine this is one of the many dialogues you could say to the NPC.

func _ready() -> void:
    print(NPC.listen(player_name))
```
The node makes a check in the `phases[current_phase]`:

`DialogueCore`:
```
func listen(value : String) -> String:
	var _v : String #Using a value here makes it possible to recycle the function for acceptable and default replies.
	for i in phases[current_phase].acceptable_dialogues:
		if value == i.dialogue:
			_v = i.reply 
			set_current_phase(i.phase_to)
			response.emit(_v)
			return _v
	_v = phases[current_phase].default_response
	set_current_phase(phases[current_phase].default_phase_to)
	response.emit(_v)
	return _v
```
If there is a `dialogue` that matches the given value the node will return its `reply`, if not, then the `default_response` will be returned.

`current_phase` will change if the new value of the `Response` or the `Phase` itself is acceptable:

```
func set_current_phase(value : int) -> void:
	if value >= phases.size():
		push_warning(str(value) + " is invalid. Value is too high!")
		return
	elif value < 0:
		push_warning(str(value) + " is invalid. Value is too low!")
		return
	current_phase = value #The warnings prevent errors given by the Engine trying to find an inexistent phase in the array of phases.
```

Representation of the node working:
![NodeDiagram_Mesa de trabajo 1](https://github.com/user-attachments/assets/4d6df944-759b-4434-93b6-9eebbec8be93)

Here is the code of the node:
[DialogueNode.zip](https://github.com/user-attachments/files/16682963/DialogueNode.zip)

Notes: Response was intended to use a Dictionary for the dialogue and reply making both choosable Variants, but a bug occurred that reset all values to null for some reason.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The complexity of any dialogue system makes it impossible to replicate in fewer lines of code, mostly because of the impossibility of exporting custom classes and the inability to save data from custom classes without the use of extended Resources.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes indeed. Every new developer who wants to create a dialogue system would have to use it as an external tool making it incompatible with updates, tutorials, and documentation that Godot provides for their nodes.

More than that, this node can be more useful and complex with a visual editor or even custom class export, sadly the visual editor is beyond my programming skills and the custom class export is beyond the engine's capabilities; both problems can be solved by making this part of the engine itself.

**Comment by Meorge** [comment]
This sounds to me like something that would work better as a plugin, especially since the precise behavior of a "dialogue system" can vary wildly across different games. There are many available on GitHub, but to name a few:
- [Dialogue Manager](https://github.com/nathanhoad/godot_dialogue_manager)
- [Dialogic](https://github.com/dialogic-godot/dialogic)
- [GodotInk](https://github.com/paulloz/godot-ink)

Again, I think it depends on the level of complexity necessary for each individual game, but I'm not sure if it would make sense to build a system like the one you've described and refer to it as Godot's "official" dialogue system.

Perhaps this could be abstracted out to some kind of data structure that acts like a more modifiable `match` statement, where it runs down its list of "key" conditions until it locates a condition that is matched, and returns the associated value there? I'm struggling to come up with many use cases for such a data structure, or how it would be implemented and interfaced with in the editor, though.

**Comment by PeeledChairStudios** [comment]
I tried to make it as much general as I could, that’s why I chose Strings as the variant, it can be used to make 2D text or to call Audio files among other resources. 

And yes, I thought about the match statement, the problem it’s that you would have to repeat the same code fragment every time you have to make an NPC mixing own dialogues and new dialogues. You could copy-paste them, but the script would weight more.
