### ISSUE TITLE
Update references to a Timer node upon renaming that node

### ISSUE THREAD

**Issue by shashjar** [godotengine/godot-proposals#10510]
### Describe the project you are working on

A simple 2D game to learn how to use Godot

### Describe the problem or limitation you are having in your project

References to `Timer` nodes are not kept and updated based on renaming actions

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When I rename a `Timer` node (e.g. a node called `attack_cooldown`), it would be helpful to automatically rename or flag the references that were previously created for that `Timer`. For example, I might have `$attack_cooldown.start()` / `$attack_cooldown.stop()` calls or the `func _on_attack_cooldown_timeout()` callback. It would be nice to hold references to these in relation to the `Timer` node so that they can be updated or otherwise reported to the user when those are renamed.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Attach node references to the `Timer` (fairly straightforward for `$` but maybe less so for the function callbacks?). Update them accordingly on updates to the source node.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Could definitely be an editor plugin

### Is there a reason why this should be core and not an add-on in the asset library?

This is fairly reasonable/expected functionality that fits with patterns elsewhere in Godot / IDEs

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/899.
