### ISSUE TITLE
Provide a way to exclude folders from Quick Load

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [godotengine/godot-proposals#10535]
### Describe the project you are working on

I'm currently working on a 3D game with a complex code base, and am making use of gdUnit4, Func_Godot and Jolt as addons.

### Describe the problem or limitation you are having in your project

When using addons with a lot of files associated with them, they quickly clutter the Quick Load dialogue. While mostly an annoyance (the search box mitigates most of the issue), it makes it difficult to use the quick load dialogue if you can't remember what a scene or script was called.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Provide a way for developers to set which directories are included or excluded from the Quick Load list.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add an option in Project Settings to exclude specific directories from being enumerated in Quick Load. 
Add a checkbox to "Include Excluded Directories" in Quick Load so that the exclusions can be quickly ignored if needed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's not clear that it can be. As far as I'm aware you can't replace or override Editor Dialogues easily, and a plugin or script that could would likely be fairly complex.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a basic usability improvement, and not in the purview of an add-on as far as I'm aware.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/9378.
