### ISSUE TITLE
Add an `add_editor_plugin` method to `EditorPlugin` to add sub plugins by object

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot-proposals#10556]
### Describe the project you are working on

An editor plugin which adds two new custom 2d nodes which both need special options above the viewport.

### Describe the problem or limitation you are having in your project

The editor plugin api allows to add buttons to the edit bar above the 2d viewport. To only show them for the right node, we can use `_make_visible` and `_handles`. This whole API does not work well for an editor plugin that adds multiple node types (and also if you want to add custom nodes and a main screen). In those cases it is easier to split the different nodes and the main screen into their own `EditorPlugin`s. However there is no way to conveniently activate those.

There is `EditorInterface.set_plugin_enabled` but it can only activate plugins that are backed by a `plugin.cfg` and adding configs for such sub plugins would add confusing entries to the plugin settings.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`EditorPlugin` will gain two new methods:

`add_editor_plugin(plugin: EditorPlugin)`
`remove_editor_plugin(plugin: EditorPlugin)`

The loading and instantiation can be done by the main plugin, Godot will only take care of adding and removing the plugin to the tree and possibly setting up a main screen.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

User facing api would look similar to adding other plugin types:

```gdscript
const Node1EditorPlugin = preload("...")
var node1_editor_plugin = Node1EditorPlugin.new()
const Node2EditorPlugin = preload("...")
var node2_editor_plugin = Node2EditorPlugin.new()

func _enter_tree():
    add_editor_plugin(node1_editor_plugin)
    add_editor_plugin(node2_editor_plugin)

func _exit_tree():
    remove_editor_plugin(node1_editor_plugin)
    remove_editor_plugin(node2_editor_plugin)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Will not be used often, but there is no way to work around it (if you know one please tell me 🙏)

### Is there a reason why this should be core and not an add-on in the asset library?

Requires interaction with unexposed internals

**Comment by KoBeWi** [comment]
> adding configs for such sub plugins would add confusing entries to the plugin settings.

Nested plugins don't show on plugin list.

**Comment by HolonProduction** [comment]
> Nested plugins don't show on plugin list.

Good to know :+1: 
I think this approach should probably be documented then.

**Comment by HolonProduction** [comment]
Closing in favor of https://github.com/godotengine/godot-docs/pull/9873
