### ISSUE TITLE
Add a node_added_on_edited_scene signal to EditorPlugin

### ISSUE THREAD

**Issue by yguel** [godotengine/godot-proposals#10569]
### Describe the project you are working on

I would like to extend themes by making it possible to change default values for widget proposed in the editor and not only property related to appearance. The idea would be to speed up ui production by recording default values chosen by the user.

I have a concrete example for the standard widget textEdit, systematically, I need to set the scroll_fit_content_height property to true. The default value being false, that need to be done manually.
When the list of changes become important and/or the widget used a lot, I am researching a nice way to automate that task and allow the users to specify it easily.

### Describe the problem or limitation you are having in your project

I am trying to perform actions on nodes added by the user on edited scene and the node_added signal of the node returned by the get_tree() method of the EditorPlugin returns many nodes that are not part of the edited scene.
It is necessary to filter them out by implementing a test that verify if the node is part of the edited scene or not.
For the EditorPlugin it seems like a very common need to work only on the nodes that are being edited and it seems a nice feature to have for the user to be able to react only on nodes from the edited scene

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a signal node_added_on_edited_scene( node: Node) seems a nice way to propose an interface to plugin developers to concentrate on work on edited nodes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I propose that the signal is being proposed by the EditorPlugin such that in _enter_tree() developers can connect their custom logic to it.
Example:
```gdscript
func _enter_tree():
    scene_changed.connect(_on_scene_changed)
    node_added_on_edited_scene(_on_node_added_to_scene)

# Example of use case
func _on_node_added_to_scene(node:Node)->void:
    if node is TextEdit:
         node.scroll_fit_content_height = true
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

well depending on what "a few lines" means, here is an example with a moderate number of lines:
```gdscript
var current_scene_root = null

func is_node1_and_ancestor_of_node(node1: Node, node: Node) -> bool:
    for child in node1.get_children():
        if child.get_instance_id() == node.get_instance_id():
            return true
        else:
            if is_node1_and_ancestor_of_node(child, node):
                return true
    return false

func is_node_in_scene(node: Node) -> bool:
    if null != current_scene_root:
        return is_node1_and_ancestor_of_node(current_scene_root, node)
    else:
        return false

func _on_node_added(node: Node) -> void:
    # Test if current_scene_root is an ancestor of node
    if not is_node_in_scene(node):
        return
    else:
        _on_node_added_in_edited_scene(node)

func _on_scene_changed(scene: Node) -> void:
    if null != current_scene_root:
        current_scene_root = null
    var scene_tree = get_tree()
    if scene_tree:
        var scene_root = scene_tree.edited_scene_root
        current_scene_root = scene_root
        if scene_root:
            scene_tree.node_added.connect(_on_node_added)

func _enter_tree():
    #connect signal scene_changed to _detect_node_added
    scene_changed.connect(_on_scene_changed)

#custom logic
func _on_node_added_in_edited_scene(node: Node) -> void:
    pass
```

That is the basis of the feature, if one wants to avoid nodes when they are loading but only react on nodes manually added by the user through the editor it requires a bit more works, since the state of the scene when it was loaded from file is to be recorded, to only fire the custom logic on nodes that were not already in the scene.
The feature looks to me to respond to a common need, so I expect the enhancement to be used a lot, but only user votes will solve that debate.
What I find not at all obvious from the documentation is the difference between the edited scene and the whole scene (being the editor) and how to filter efficiently user actions that act on the editor controls with respect to the ones acting on the edited scene.

### Is there a reason why this should be core and not an add-on in the asset library?

Because it is a feature that I expect to be used by many add-ons in the asset library : by add-ons proposing editor plugins (EditorPlugin subclasses).

**Comment by AThousandShips** [comment]
You can just connect to the scene tree and listen for added nodes and check for [`is_part_of_edited_scene`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-is-part-of-edited-scene) no? No need for the workaround you propose afaik

**Comment by yguel** [comment]
Thanks, I did not notice this method.

**Comment by yguel** [comment]
In godot 4.2 I got the following unexpected error: «Invalid call. Nonexistent function 'is_part_of_edited_scene' in base 'Button'.»
Should I be aware of some precondition to be able to use is_part_of_edited_scene ?
