### ISSUE TITLE
Add Scene Tree contextual menu or Inspector button to reveal Scene asset in the FileSystem, from either scene instance or Scene edit view

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-proposals#10566]
### Describe the project you are working on

A platformer

### Describe the problem or limitation you are having in your project

I often want to reveal the Scene asset (resource) 7hat was used to instantiate a certain scene instance in my Scene Tree, so that I can rename it, duplicate it or create an Inherited scene from it. In this case, clicking on the Slate icon to **open** the Scene will not work.

Even when editing the Scene, there is no way to reveal the asset in the FileSystem.

- there is no such command in the contextual menu of both the Scene instance and actual Scene being edited
- right-click on the Slate icon does nothing
- the Inspector 3-dots > Show in Filesystem is grayed out because even when you edit the scene itself, it is considered like a *node* representing the scene, and not the scene asset itself

The only way I found is to hover the mouse over the scene instance (not the scene itself being edited, that won't work, nor the slate icon) and it will show the path to the scene asset. Then you must manually open that folder in FileSystem.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A contextual menu and a button to reveal the scene asset in the FileSystem from either a scene instance or the actual scene being opened.

For Scene instances, it could be added directly to the contextual menu.

For Scene being edited:

Unfortunately, when a scene is being edited, it "forgets" information about itself and only see the root node as some content node, not representative of the containing scene. So the contextual menu shows nothing related to scene instances, nor the Inspector 3-dots button (which is meant for Resources). This however makes sense, if the idea is to reserve such menu for nodes being actually instances of another scene (this is the case for Inherited scenes, which contain a root node itself an instance of another scene).

In this case, the best seems to add a button on the Scene top bar itself, since it deals with the opened scene itself, not its contained nodes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Contextual menu for Scene instance:

![image](https://github.com/user-attachments/assets/b47d3cc1-504d-4793-b465-7e1744db1bae)

This is the scene-instance-specific contextual menu section.

Just above or below Open in Editor, add a menu item "Reveal Scene in FileSystem".

Button Scene being edited:

![image](https://github.com/user-attachments/assets/6bc8257e-65a0-4bda-ba9e-e234a8f75aff)

We could add a button right after the "Instantiate Child Scene" (chain) button to Reveal Scene in FileSystem.

The cool thing is that it would work for all scenes, even the Main scenes which are never instantiated in other scenes. So designers can easily retrieve their level assets, duplicate them, etc.

I was also tempted to use the Inspector 3-dots button:

![image](https://github.com/user-attachments/assets/10ba400b-f83d-4ca2-8fba-c56364613d3d)

but from the looks of it, it expects a Resource, and because it needs to distinguish the root node *inside* a scene and the scene resource itself, it may not work.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The best is to hover the node, read the path and search it manually.

We could also write a script using `get_scene_file_path` [doc](https://docs.godotengine.org/en/4.2/classes/class_node.html#class-node-property-scene-file-path) but I'm not sure about the API to reveal a resource in FileSystem, nor to add a contextual menu item.

### Is there a reason why this should be core and not an add-on in the asset library?

It really completes Open scene in Editor. In fact, it's common in applications to have Reveal and Open commands side-by-side.

**Comment by KoBeWi** [comment]
There is Show in FileSystem option when you right-click instance node. For current scene, you can right-click the scene tab.

**Comment by hsandt** [comment]
Just discovered that, I forgot my project was still in 4.2.1! I just upgraded it to 4.3 today, it's exactly what I needed!

![image](https://github.com/user-attachments/assets/6aef72c8-fab9-4aff-abbc-182e973154ea)

There is still the ambiguity for inherited scene: "do you want to reveal the scene asset for the root node or the base scene asset you inherited from?" but it's not an issue: if you Show the root node in FileSystem it will reveal the inherited scene resource, often what you want. If you really want to show the base scene, just click on the Slate icon to reveal the base scene, then right-click on that root node and Show in FileSystem.

Non-inherited scenes just work the same, whether you're clicking on the instance, or the root node of the opened scene.

So I can access whatever I need! Closing this issue.
