### ISSUE TITLE
Movie maker should allow a relative path

### ISSUE THREAD

**Issue by ROMthesheep** [godotengine/godot-proposals#10570]
### Describe the project you are working on

A 2D horror game

### Describe the problem or limitation you are having in your project

We are multiple ppl working at the same time and need to each one create clips of gameplay for documentation.
But everytime one of us needs to create a clip we need to change the path in the godot project configuration

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

allow relative paths, like `res://Clips/` to be valid

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When placed a relative path to a folder in the project files movie maker works

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This could be a plugin but it seems too convenient not to be a full release feature 

### Is there a reason why this should be core and not an add-on in the asset library?

I feel this is a really annoying problem to deal with when working in a group.

**Comment by AThousandShips** [comment]
Try `Clips/`, it should already support relative paths

**Comment by Calinou** [comment]
Relative paths are already supported as per @AThousandShips's comment. You need to enter the file path manually in the project setting field instead of using the button that browses through files.

Closing in favor of https://github.com/godotengine/godot/issues/90236.
