### ISSUE TITLE
Add the ability to transport shader variables from `fragment()` to `light()`

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot-proposals#1057]
**Describe the project you are working on:**
Some shaders.
**Describe the problem or limitation you are having in your project:**
i need use render_mode cull_disabled and need FRONT_FACING in light()
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Since light () is called for every pixel and works after fragment (), theoretically, nothing prevents it from accessing all the calculation results in fragment (). This would help to save the code, since the color of the material and the light emitted by it are often physically related. In some cases, this is simply necessary, i cannot determine the side of the polygon in light (). I want send my variables from fragment() to light().

I would also like to have access to DEPTH_TEXTURE in vertex (), I also see no reason why this would not be possible.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It may be worth using several vec4 or array for transport variables. Perhaps it is worth making an analog varying for fragment()...
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I am use ugly dirty hack for this trouble. I send variables from fragment to light with TRANSMISSION vec3. 
**Is there a reason why this should be core and not an add-on in the asset library?:**
this is part of engine.

Sorry for my english.

**Comment by vitorbalbio** [comment]
This is a quite annoying indeed. I have been doing a lot of workarounds and multiple calculations to overcome it. Hope it been improved in future.

**Comment by Calinou** [comment]
@vitorbalbio Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by vitorbalbio** [comment]
Sorry. Edited with my workaround.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/2022.
