### ISSUE TITLE
C# Add a Generics version of SceneTree.GetNodesInGroup(...)

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot-proposals#1059]
**Describe the project you are working on:** Personal game, details aren't related to this issue.

**Describe the problem or limitation you are having in your project:** We already have Generics methods for `GetNode<T>(...)`, `Instance<T>(...)`, `GetParent<T>()` and so on, it feels odd not having one for `GetNodesInGroup<T>(...)`.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** The Generics method would return a Generics `Godot.Collections.Array<T>`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```csharp
Godot.Collections.Array<T> GetNodesInGroup<T>(String group)
```
Of course, said group could contain nodes of incompatible types. On such case, errors should be handled as they are in `GetNode<T>(...)`.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** Casting, as usual.

**Is there a reason why this should be core and not an add-on in the asset library?:** It's a change to C# API.

**Comment by akien-mga** [comment]
Fixed by godotengine/godot#39652.
