### ISSUE TITLE
Expose methods to get the current rendering driver/method in use

### ISSUE THREAD

**Issue by pochoco24** [godotengine/godot-proposals#10609]
### Describe the project you are working on

A streaming overlay app

### Describe the problem or limitation you are having in your project

The OS class has a RenderingDriver enum that is not used anywhere. I'm looking for a get_rendering_driver() method in the docs, but it's either undocumented or not in Godot.

URL to the documentation page: https://docs.godotengine.org/en/stable/classes/class_os.html#enum-os-renderingdriver

Original issue in documentation: https://github.com/godotengine/godot-docs/issues/9851

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a function to detect the current rendering driver so it returns the RenderingDriver enum. This is especially useful when using `fallback_to_vulkan` or `fallback_to_d3d12` in Project Settings, so the function checks if the rendering driver fell back.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Im not familiar with C++, but I think there's a variable that holds the current renderer string name. It should be a matter of exposing the variable to a Godot class or something.

It also has to be included in the documentation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Unlikely, since it is not an accessible value for Godot.

### Is there a reason why this should be core and not an add-on in the asset library?

Has to be core, it is an unused enum.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/85430 implements this by exposing the existing method, which returns a String and not an enum value. This allows for custom rendering methods/drivers to be exposable without needing to modify the enum, but it allows for typos and doesn't provide autocompletion. That said, it should fulfill the use case you're looking for.
