### ISSUE TITLE
Copy Godot's `.natvis` file in godot-cpp for datatype visualization in Visual Studio

### ISSUE THREAD

**Issue by Withaust** [godotengine/godot-proposals#10605]
### Describe the project you are working on

I am working on a project that heavily relies on using GDExtension

### Describe the problem or limitation you are having in your project

Currently, godot-cpp is copying some of the files by default already (all Variant-related classes, for example), and having to manually copy .natvis file from the godot's repo feels like an oversight.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having a .natvis file for specific version that each branch relies on makes it easier for people to start debugging their extensions

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just copy .natvis file into each major release of godot-cpp as well

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be done manually, but it would be better if everything was in one whole package. Main feature of GDExtension is that you dont have to rely on the source code of the engine to make your own extensions, and having to deal with a separate repo just for a single file feels like an oversight.

### Is there a reason why this should be core and not an add-on in the asset library?

This should be accessible to everyone who is working with GDExtensions by default

**Comment by dsnopek** [comment]
Having a natvis file in godot-cpp makes sense to me.

However, are you sure that the natvis file from Godot works with godot-cpp?

Looking at the section for `Array` for example:

```xml
	<Type Name="Array">
		<Expand>
			<Item Name="[size]">_p->array._cowdata._ptr ? (((const unsigned long long *)(_p->array._cowdata._ptr))[-1]) : 0</Item>
			<ArrayItems>
				<Size>_p->array._cowdata._ptr ? (((const unsigned long long *)(_p->array._cowdata._ptr))[-1]) : 0</Size>
				<ValuePointer>(Variant *) _p->array._cowdata._ptr</ValuePointer>
			</ArrayItems>
		</Expand>
	</Type>
```

In godot-cpp, `Array` doesn't have `_p.array._cowdata._ptr`, that only exists after you've crossed over to the Godot side.

Some of these should work in godot-cpp where we've copied the code from Godot, like `Vector`, `LocalVector`, `List`, `HashMap`, etc. But just as many seem like they wouldn't work.

If I'm right about that, then I don't think it's a matter of just copying it - someone will need to make a modified natvis file for godot-cpp.

**Comment by julesfern** [comment]
For future readers: I needed to solve this problem in GDB for my own heavily cpp-based project. The trick is that gdextension types implement a buffer field usually called `opaque` which contains the data for the underlying engine type. Since you're probably debugging with the symbols for both the engine and your gdextension loaded, GDB's python library can be used to reinterpret the opaque buffer as the underlying type, and get you to the useful data you'd want to print. 

Example below shows the utility functions I'm using plus an example that can be used to pretty-print `godot::String`. This is provided unencumbered, please do whatever you want with it:

```python
class GodotCPPUtils:
    # Take an object with an opaque field and open it as raw struct data
    def value_from_opaque(value: gdb.Value, private_type: str, opaque_field: str = "opaque") -> gdb.Value:
        t_val = gdb.lookup_type(private_type)
        return value[opaque_field].address.cast(t_val.pointer()).dereference()
    
    # If the given object is godot::SomeType, unwraps it to the engine-internal SomeType
    # using the given opaque_field. Will break if the type is a template that for whatever
    # reason wasn't instantiated on the engine side, like godot::Vector<YourCustomExtensionType>
    def unwrap_opaque(value: gdb.Value, opaque_field: str = "opaque") -> gdb.Value:
        if "godot::" in value.type.name:
            unwrapped_name = value.type.name.split("::")[-1]
            unwrapped_type = gdb.lookup_type(unwrapped_name)
            return GodotCPPUtils.value_from_opaque(value, unwrapped_type, opaque_field)
        else: # Passthrough if not from the godot-cpp namespace
            return value

# Example pretty-printer for godot::String
class GodotCPPStringPrinter:
    def __init__(self, value):
        self.value = value

    def to_string(self):
        unwrapped = GodotCPPUtils.unwrap_opaque(self.value)
        return "%s '%s'" % (self.value.type.name, unwrapped["_cowdata"]["_ptr"].string())
    
    def display_hint(self):
        return "string"
```

**Comment by van800** [comment]
Recently I fixed the godot::StringName type presentation https://github.com/godotengine/godot/pull/116955
