### ISSUE TITLE
In the text editor side panel, automatically highlight method currently in possession of caret

### ISSUE THREAD

**Issue by vaner-org** [godotengine/godot-proposals#10617]
### Describe the project you are working on

Stealth action game with sizeable and complex scripts.

### Describe the problem or limitation you are having in your project

While clicking the method in the sidebar to quickly jump around in a large script is very useful...

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

...it would be even more useful to have the method inside which the caret currently resides automatically be highlighted, the same way it is when it is clicked in the sidebar.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Pretty straightforward, if I click here in the code, the sidebar should do this:

![(_) world tscn - openseam - Godot Engine 31 Aug 24 6_57_42 PM](https://github.com/user-attachments/assets/d839f0f1-101d-4849-87c5-6ce9e50e235d)

And if I click here, it should do this:

![(_) world tscn - openseam - Godot Engine 31 Aug 24 6_59_19 PM](https://github.com/user-attachments/assets/a6e2aaf1-872a-4e18-9503-1d16a0834385)

But if I click outside the body of a function...

![(_) world tscn - openseam - Godot Engine 31 Aug 24 7_04_52 PM](https://github.com/user-attachments/assets/e0bb72cb-033c-4de7-9d3d-a48f2e28091b)

..or even better, this...

![(_) world tscn - openseam - Godot Engine 31 Aug 24 7_04_52 PM - Copy](https://github.com/user-attachments/assets/2d256fa4-5f7f-47b5-90f5-c6d4add3b986)

...but then indent to be back inside:

![(_) world tscn - openseam - Godot Engine 31 Aug 24 7_04_28 PM](https://github.com/user-attachments/assets/40163eb9-bda9-4e35-b6d4-96cfeccc2f68)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure, but I would assume not. I find myself searching for this functionality fairly often, since it intuitively mirrors what the scripts panel above does.

### Is there a reason why this should be core and not an add-on in the asset library?

Just a small quality of life improvement to better help someone get their bearings, when deep in a method that is large(r than it should be).

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/10336

See there for more details and please add any ideas you have there if they're not already mentioned
