### ISSUE TITLE
Make `SplitContainer` operate with more than 2 `Control` children.

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot-proposals#10610]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Complicated Scene Tree structure with a lot of `remove_child` and `add_child` calls to maintain a `SplitContainer` that can have more than two `Control` children.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It will help to simplify the `SceneTree`.

To achive the same result with `SplitContainer` your tree will look like:
```
Scene
├── SplitContainer
│   ├── First
│   ├── SplitContainer
│   ├── ├── Second
│   ├── ├── SplitContainer
│   ├── ├── ├── Third
│   ├── ├── ├── Forth
```

To achive the same result after implemention this feature:
```
Scene
├── SplitContainer
│   ├── First
│   ├── Second
│   ├── Third
│   ├── Forth
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have already created `SplitterContainer`, but it still needs revision and support for child controls size flags and to be compatible with `SplitContainer` theme_cache.

[splitter_container.h](https://github.com/WhalesState/godot-pixel-engine/blob/pixel-designer/scene/gui/splitter_container.h)
[splitter_container.cpp](https://github.com/WhalesState/godot-pixel-engine/blob/pixel-designer/scene/gui/splitter_container.cpp)

Example:

https://github.com/user-attachments/assets/f48c12b7-caa9-4651-8393-66427efe9aee

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can't, this will require a full rewrite of a new `Container` to support more children.

### Is there a reason why this should be core and not an add-on in the asset library?

This will not break compatibility, because the `SplitContainerDragger` will be created/removed on demand instead of being a constant.
The only change is that the `split_offset` will be an `Array` instead of a `Float` and will be called split_offsets. We can keep both and we deprecate the first to not break compatibility.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/9666

Which already has a PR
