### ISSUE TITLE
Add scene tree context menu option "Replace with scene"

### ISSUE THREAD

**Issue by and-rad** [godotengine/godot-proposals#10635]
### Describe the project you are working on

A 3D game with lots of grayboxing and blocking out using modular pieces that are intended to be replaced by production-ready assets later.

### Describe the problem or limitation you are having in your project

When you work with blockout assets during early development, you'll eventually want to replace all the prototype geometry with finished assets. Even during day-to-day level design with final assets you might want to replace an asset with different versions of the same type, i.e. variations of a modular wall mesh.

This workflow is currently very cumbersome to achieve in Godot because there is no easy way to replace an instanced scene with another scene from the file system. If you want to replace the existing scene or node **A** with a packed scene **B**, you're forced to add B as a child of A, then un-parent B from A and then remove A from the level.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Similar to how it is already possible to replace one built-in node with another via the context menu entry "Change type", I propose an entry "Replace with scene". When this is clicked, a file dialog opens where you can choose the scene that the currently selected scene should be replaced with. This should work with multiple selected scenes, each one being replaced with the new one.

Bonus points for a second menu entry that offers to replace the selected scene(s) with the one that is currently highlighted in the file explorer.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is the feature in action in Unreal Engine:

https://github.com/user-attachments/assets/8266e350-0fbe-419d-8d51-1166a78759f9

When scenes are replaced, preservation of property data is a secondary concern. It is vital that transform data is preserved, but apart from that, it's okay if data preservation can't be guaranteed. I think a reasonable goal is to preserve all data up to the lowest common parent class of the two instances involved. 

Example 1: An instanced scene's root node is a `MeshInstance3D`. The scene is about to be replaced with a packed scene whose root node is a `Node3D`. In that case, users should be able to expect that every property on the old scene that belongs to `Node3D` carries over to the new scene.

Example 2: An instanced scene with `MeshInstance3D` at its root is replaced with a scene that has a `GPUParticles3D` node at its root. In this case, every property up to those present in `GeometryInstance3D` is preserved.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is possible to write a tool script that provides the same functionality.

### Is there a reason why this should be core and not an add-on in the asset library?

The use case is common enough and the amount of time saved is big enough that I think it is justified to have this feature in core.

**Comment by KoBeWi** [comment]
It's the same as #4991, no? It has an implementation that you can test.

**Comment by and-rad** [comment]
Yup.
