### ISSUE TITLE
Add `printwarn()` to print warnings to Output panel (as opposed to Debugger)

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot-proposals#10648]
### Describe the project you are working on

[Rift Riff](https://store.steampowered.com/app/2800900/Rift_Riff/) and soon a sequel to [Hidden Folks](https://hiddenfolks.com).

### Describe the problem or limitation you are having in your project

When you hit the play button to run a game from the Godot editor, the default `Action on Play` is to open the Output panel (as defined in Editor settings). For this reason, most devs (like myself) learn to use `print()` and `printerr()` to keep track of **gameplay-related** messages, warnings, and errors. However, even though the editor supports it, there is no way for users to print warnings to the Output panel. So when there is a point in my code where a warning is best suited for that particular gameplay case, I can't print it as such, and I have to choose between a regular grey output message or an everything-is-exploding red error output message. It feels like an oversight considering users _can_ print errors.

Why not let me print a warning? The Output panel even has a button to filter out warnings. A feature like that seems to suggest users should be able to print them in the first place. 

**Important Note:** I am specifically _not_ talking about the Debugger panel. I am aware of `push_error()` and `push_warning()`. I would like to be able to push warnings to the Output panel for gameplay reasons, so that I can see **gameplay related prints, warnings, and errors all in once place and in order of execution in the Output panel**.

<img width="864" alt="Screenshot 2024-09-03 at 20 48 28" src="https://github.com/user-attachments/assets/0cb688d9-1fd2-4679-8cb5-09693e738da3">

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a method such as `printwarn()` or `printw()` to allow users to print (filterable, as per the button in the Output panel) warnings **to the Output panel**.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like `print()`, but as a warning message.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can do `print_rich("[color=yellow]<message>")` but it is more verbose and not filterable in the Output panel.

### Is there a reason why this should be core and not an add-on in the asset library?

AFAIK `print()` and `printerr()` are both in core.

**Comment by arkology** [comment]
https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-push-warning

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/10568
