### ISSUE TITLE
If an Array element has a property called 'name', show it in the Array inspector

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot-proposals#10649]
### Describe the project you are working on

A tower defense game called [Rift Riff](https://store.steampowered.com/app/2800900/Rift_Riff/) and soon a sequel to my indie hit game [Hidden Folks](https://hiddenfolks.com).

### Describe the problem or limitation you are having in your project

I use Arrays with custom resources extensively and am often lost as to what array index holds which specific instance of my custom resource.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be super useful to see the names of the resources in the Array inspector like so (in white, but highlighted in red in this example):

<img width="659" alt="Screenshot 2024-09-03 at 21 29 20" src="https://github.com/user-attachments/assets/aaffc0b8-db01-401f-ac92-6a73344b8144">

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If an object inside an Array has a `name` property (or something else, maybe even configurable), add that to the index label in the Array inspector.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I could in theory write a custom PropertyInspector to replace the default inspector for Arrays, but I would rather not as it's quite complicated!

### Is there a reason why this should be core and not an add-on in the asset library?

The default property inspector for arrays is part of core.

**Comment by KoBeWi** [comment]
Resources do have a name property already.
![image](https://github.com/user-attachments/assets/c21a6bbc-c446-4571-b0ce-496ffbda0d6e)

**Comment by AdriaandeJongh** [comment]
right - that can be used to put into the id field in the property inspector of array elements.

**Comment by AdriaandeJongh** [comment]
Ah - I misunderstood. When you enter a name, it appears in the field of the property. That closes this proposal. Thanks @KoBeWi

**Comment by lucastucious** [comment]
Hey, sorry to do necromancy here, but could this be implemented into Remote Inspector ?

Local:

<img width="632" height="316" alt="Image" src="https://github.com/user-attachments/assets/9f767adc-5a2f-4aeb-b022-6aacf897c410" />

Remote :

<img width="630" height="356" alt="Image" src="https://github.com/user-attachments/assets/aefb0387-fe80-46e8-a1d2-7a3da91c8062" />

or maybe this will be better into a godot issue ?

**Comment by KoBeWi** [comment]
This would require rework of how remote Resources are displayed. The properties (including name) are not loaded until you click the object.
