### ISSUE TITLE
Add support for [Ctrl]+[Shift]+[U] unicode input on at least Linux

### ISSUE THREAD

**Issue by MagicCraftMaster** [godotengine/godot-proposals#10654]
### Describe the project you are working on

A GUI for a utility program I've been working on.
This would be nice to see available in all projects and the editor though.

### Describe the problem or limitation you are having in your project

While Godot does have the (hold) [Alt] [+] (Unicode hex sequence) (release) [Alt] it's something I only found out about after looking for it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

On many Linux systems the shortcut [Ctrl]+[Shift]+[U] is used you can then enter a unicode hex sequence and upon releasing [Ctrl]+[Shift] or pressing [Space] if you'd already released [Ctrl]+[Shift] the character will be inserted (if the sequence was valid)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simply add support for the shortcut when running on Linux similar to the [Alt][+] system
Another useful thing would be to make a u̲ show when in entry mode (Underscored lowercase u)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There may be a way to implement this in projects but it'd likely be annoying, break easily, and generally just be more effort that it's worth

### Is there a reason why this should be core and not an add-on in the asset library?

It would be better if it was consistent and not depending upon if a happens have it

**Comment by timothyqiu** [comment]
> make a u̲ show when in entry mode (Underscored lowercase u)

I suggest showing `U+`, which is a conventional way of representing a Unicode code point.

![Peek 2024-09-05 22-38](https://github.com/user-attachments/assets/e386c84d-0aea-4c98-9410-e7260e6d69ab)

**Comment by akien-mga** [comment]
> I suggest showing `U+`, which is a conventional way of representing a Unicode code point.

Some tests for the record, on Fedora 40:
- Firefox shows `u̲` and then the numbers underscored.
- Chromium doesn't show anything (but the feature works). Pretty bad UX IMO.
- Dolphin and LibreOffice don't seem to support the feature.

Which browser uses `U+`?

**Comment by bruvzg** [comment]
> I suggest showing U+, which is a conventional way of representing a Unicode code point.

I have checked few apps on PopOS and all seems to use `u` (which is what I have used in https://github.com/godotengine/godot/pull/96592), might be UI toolkit dependent.

**Comment by Zireael07** [comment]
From my experience most "what character is that" sites do use U+ notation, as do text editors in their character pickers.

**Comment by timothyqiu** [comment]
> Which browser uses `U+`?

Sorry for not making it clear. The gif is showing the Unicode input behavior of the fcitx5 input method.

Without the input method running, my Chrome shows no prompt as you described.
