### ISSUE TITLE
Make CSGBox3D extend CollisionObject3D

### ISSUE THREAD

**Issue by aladvs** [godotengine/godot-proposals#10668]
### Describe the project you are working on

3D first person shooter game

### Describe the problem or limitation you are having in your project

When statically typing, you should almost ALWAYS expect your raycast's collider to be a CollisionObject3D. Both Areas and Bodies extend from it. 
This code:
`var collider : CollisionObject3D = Raycast.get_collider()`

Should, in my opinion, be expected to never throw an error.

Except for CSGBox3Ds.

When collision is on, this throws an assignment error, as CSGBox3D does not extend from CollisionObject3D.

This requires a  _far_ more broad assignment so errors do not get thrown:
`var collider : Node3D = Raycast.get_collider()`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make CSGBox3D extend CollisionObject3D

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`var collider : CollisionObject3D = Raycast.get_collider()` should never throw an error

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it is not extremely important other than for the sake of consistency.

### Is there a reason why this should be core and not an add-on in the asset library?

Not possible outside of core

**Comment by fire** [comment]
The current chain of inheritance for CSGBox3D is.

CSGBox3D < CSGPrimitive3D < CSGShape3D < GeometryInstance3D < VisualInstance3D < Node3D < Node < Object

If CSGBox extends CollisionObject3D, it won't be able know to do CSG shape like add, subtract of find overlap of meshes.

**Comment by aladvs** [comment]
> The current chain of inheritance for CSGBox3D is.
> 
> CSGBox3D < CSGPrimitive3D < CSGShape3D < GeometryInstance3D < VisualInstance3D < Node3D < Node < Object
> 
> If CSGBox extends CollisionObject3D, it won't be able know to do CSG shape functionality like add, subtract of find overlap of meshes.

Not sure what can be done then, just strange that CollisionObject3D as a collider can _never_ be assumed.
I can close the issue if ya'll want

**Comment by Calinou** [comment]
CSG nodes create their collision at *runtime* if **Use Collision** is enabled, so it doesn't make sense for them extend CollisionObject3D.
