### ISSUE TITLE
Improve exporting to IOS

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1067]
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
I want to export to IOS but I don't have macOS. Why is it so complicated to export to IOS?
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
You could export from Windows.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, I think it's not possible to do it with an add-on

**Comment by groud** [comment]
This is not possible, this is how things work with apple. See the answers there: https://www.reddit.com/r/godot/comments/c9k4kr/hello_do_i_need_an_apple_pc_to_export_to_ios/
