### ISSUE TITLE
Add a button to switch between 'Search' and 'Replace' in the code editor

### ISSUE THREAD

**Issue by elliotfontaine** [godotengine/godot-proposals#10675]
### Describe the project you are working on

Noob following noob tutorials for now.

### Describe the problem or limitation you are having in your project

In most IDEs I usually `Command+F` instead of `Command+Option+F` even when I want to do replacements, because I find the keybind cumbersome. Most IDE have a button on the left to open the Replace panel from the Search panel. But the Godot Editor doesn't.

**Godot Editor**
<img width="988" alt="Capture d’écran 2024-09-06 à 23 05 30" src="https://github.com/user-attachments/assets/6af2e5b0-4bf9-47b7-aa55-50d0297e22c8">

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a arrowhead button on the left of the text field(s) in the Search panel to toggle the Replace panel.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

**VSCode**
<img width="351" alt="Capture d’écran 2024-09-06 à 23 18 22" src="https://github.com/user-attachments/assets/c7bd4f3f-bdc2-4f55-a1a4-7af0f7d92c92">
<img width="358" alt="Capture d’écran 2024-09-06 à 23 00 05" src="https://github.com/user-attachments/assets/6b1911d7-dca3-433a-8814-49dc96a34505">

I **guess** (I know nothing about the inner workings of the editor): the button added on each panel would only have to use the signal sent by `Command+Option+F` and `Command+F`, since the latter already reverts back to the Search panel from the Replace Panel.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by moving your fingers a few more centimeters lol.
But it should be easy to implement. I guess I could do it myself, and I might in the future :))

### Is there a reason why this should be core and not an add-on in the asset library?

Ergonomics / IDE standards

**Comment by tetrapod00** [comment]
Yes! This is a huge improvement. Little mismatches with standard text editor behavior like this are one of the reasons why I use an outside text editor when possible.
