### ISSUE TITLE
Re-add option to export macOS builds as an uncompressed .app bundle

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot-proposals#10674]
### Describe the project you are working on

Any game

### Describe the problem or limitation you are having in your project

In Godot 3 you could export mac builds as .app, in godot 4 you can now only export as .zip. (see attached images)
I found exporting as .app was easier and more convenient for uploading updates to Steam and Itch through the command line.
![mac export g3](https://github.com/user-attachments/assets/3838fcea-232c-4348-856e-79ab1d028d2a)
![mac export g4](https://github.com/user-attachments/assets/7e710b65-dbb3-42e0-8fe3-4804a6518197)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Re-add .app export option, apparently it still exists but just is disabled in the gui.
Reference: https://x.com/_miniglitch/status/1831882783167488463

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

can manually unzip it, but would be nice to have an editor default to save time

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by bruvzg** [comment]
You can export as `.app` on macOS and Linux, but not on Windows (it was disabled since it can't create symlinks and can't set Unix permissions, so exported .app will be half broken).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/96659, as this is considered a bug.
