### ISSUE TITLE
Expose `EditorSettings::get_auto_display_scale()`

### ISSUE THREAD

**Issue by BrixsterPlanet** [godotengine/godot-proposals#10683]
### Describe the project you are working on

I am working on a non-gui application that uses dpi-aware scaling for controls. I want it to behave similarly to how the Godot editor automatically scales its UI to compensate for higher-density displays.

For projects with `display/window/stretch/mode` set to `disabled` (a viable use case for non-gui apps), the UI will appear smaller on displays with high DPI (i.e. Apple Retina or 4K monitors). This is resolved by having a script to scale the entire UI based on the ratio of the current DPI to a target factor, which the Godot editor does automatically. This behavior should be made available to runtime projects.

### Describe the problem or limitation you are having in your project

The function [`get_auto_display_scale()` in the `EditorSettings` class](https://github.com/godotengine/godot/blob/5675c76461e197d3929a1142cfb84ab1a76ac9dd/editor/editor_settings.cpp#L1575) returns a float determining the target scaling factor for the editor UI based on the screen's DPI.

Currently, I have to rewrite this entire implementation for my own projects, and it becomes cumbersome to maintain it should the implementation ever change in the future (i.e., to compensate for more device types),

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Exposing the method to calculate the target scale would allow runtime applications to scale their UIs in behavior consistent with the Godot editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Expose the method to a more appropriate class, i.e., `DisplayServer`, to be called at runtime in GDScript or C#.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The current workaround is to rewrite the function in the target runtime language. For example:
```C#
float screenScale = 1;
// Use Godot's dpi screen scale handling in EditorSettings::get_auto_display_scale() for ref (https://github.com/godotengine/godot/blob/5675c76461e197d3929a1142cfb84ab1a76ac9dd/editor/editor_settings.cpp#L1575)
if (OS.GetName() == "Linux" && DisplayServer.GetName() == "Wayland")
{
    float mainWindowScale = DisplayServer.ScreenGetScale();
    if (DisplayServer.GetScreenCount() == 1 || mainWindowScale % 1 != 0)
    {
        screenScale = mainWindowScale;
    }
    else
    {
        screenScale = DisplayServer.ScreenGetMaxScale();
    }
}
else if (OS.GetName() == "macOS" || OS.GetName() == "Android")
{
    screenScale = DisplayServer.ScreenGetMaxScale();
}
else
{
    int screen = DisplayServer.WindowGetCurrentScreen();
    if (DisplayServer.ScreenGetSize(screen) == Vector2.Zero)
    {
        screenScale = 1;
    }
    else
    {
        int smallestDimension = Mathf.Min(DisplayServer.ScreenGetSize(screen).X, DisplayServer.ScreenGetSize(screen).Y);
        if (DisplayServer.ScreenGetDpi(screen) >= 192 && smallestDimension >= 1400)
        {
            screenScale = 2;
        }
        else if (smallestDimension >= 1700)
        {
            screenScale = 1.5f;
        }
        else if (smallestDimension <= 800)
        {
            screenScale = 0.75f;
        }
    }
}

GD.Print($"Screen DPI: {DisplayServer.ScreenGetDpi()}, using target scale: {screenScale}");

// Scale your UI accordingly, using the screenScale factor.
// ...
```

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2661.

**Comment by BrixsterPlanet** [comment]
> Thanks for the proposal! Consolidating in #2661.
> 
> The editor's **Auto** heuristic is a temporary workaround that has stuck for too long due to #2661 not being implemented. It should really not be used in production applications, as it'll often be incorrect and won't respect the user's preferences in terms of display scale. For instance, I use 100% scaling on a 4K 42" display, but Godot will default to 150% scaling which is too large.

The point of the proposal is to create consistency between the editor's UI scaling behavior and UI scaling in projects. It's been an issue for too long, and I agree with the proposal to create a more consistent solution that both the editor and runtime projects can tap into. I argue that the problems in the editor UI scaling is actually a separate issue but if there were to be consistency then fixing it would fix it on both the editor and in projects.
