### ISSUE TITLE
Proper support for requesting permissions at runtime on Android (for optional permissions)

### ISSUE THREAD

**Issue by mathgeniuszach** [godotengine/godot-proposals#10686]
### Describe the project you are working on

A Time-Attack reaction game and app with custom level support ([On Command](https://www.mathgeniuszach.com/portfolio/on-command/)).

### Describe the problem or limitation you are having in your project

Custom level support in my app requires read access to a subfolder in the user's "Documents" directory where custom levels can be placed. However, this permission is entirely optional and doesn't need to be given in order to run the app. Currently, there is no way to indicate this to the user, so my app only has two choices: remove custom level support entirely so I don't need the permission, or add the permission at install time as a required permission.

I don't want to remove the functionality, but it is very niche so I doubt many people would actually use it. Additionally, adding it as a permission at install time is sure to turn away regular users who aren't too fond of a game app asking for permissions to read their filesystem without context.

(Previously, I attempted to use `/Android/​media/​com.mathgeniuszach.oncommand/​levels` - which doesn't require permissions on most devices - however, it does not work everywhere, and there's no way to know if you can make this directory because Godot crashes if you try without permissions.)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The ability to request permissions at runtime gives app developers and users more freedom over how they can use an app. For me, I would be able to only request the permissions only when the user _wants_ to handle custom levels, without turning away new installs or removing the feature.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There was already a [pull request](https://github.com/godotengine/godot/pull/32246) in September of 2019 that implemented this feature, but it was vetoed on the basis that permissions are something that only need to be granted at install time. I believe this is incorrect, as optional permissions are a perfectly legitimate reason to ask for permissions at runtime instead of install time.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

A common thing that occurs in well-written open-source apps is that they will request optional/necessary permissions one at a time with an information describing what the permission is for. Another thing an app might want to do (say, a weather app), is request location data _once_ and never actually need it again. Or maybe it doesn't need it period - provided the user selects a location manually. Godot does not support any of these use cases.

This can be worked around by just granting the permissions anyway at install time, but an requiring an optional permission at install time is going to turn away potential users for no good reason.

### Is there a reason why this should be core and not an add-on in the asset library?

There is a function that already exists in the Godot API for requesting permissions called `OS.request_permission()`. Personally I think it's really silly that's it's a stubbed-out function with support for only one permission available.

**Comment by m4gr3d** [comment]
`OS.request_permission` is not stubbed out and works for requesting runtime permissions. 
The description in the doc is incorrect and will be updated.
