### ISSUE TITLE
Fix ackward placement of documentation

### ISSUE THREAD

**Issue by marcinn** [godotengine/godot-proposals#10699]
### Describe the project you are working on

Hit F1 - a modal will open. Click on an item  - modal will close, then it's documentation will hide your script and open doc in the editor window. How can I write code when the editor is hidden? It is impossible.

### Describe the problem or limitation you are having in your project

I can't write the code when documentation is open.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

 Doc should be in a separate window.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Leave the doc in a separate window.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is a core UX bug of the Godot Editor.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/9912
