### ISSUE TITLE
Prevent loosing of the user input

### ISSUE THREAD

**Issue by marcinnformula** [godotengine/godot-proposals#10693]
### Describe the project you are working on

Godot can lose user data very easily. Just create a base class (a custom node) with some properties, use the node in your scene file, then change a property name in the base class. Godot Editor will not read all values and with next save will remove stored data.

### Describe the problem or limitation you are having in your project

Level editors are loosing important data without any warning, when interface of our custom nodes is changing. And we have no possibility to write conversion tools.

Example. We are using `stay_open` property in our custom node, and our editors have bunch of files with this property filled.
![godot-lost-props](https://github.com/user-attachments/assets/8e667ae1-ad47-4d14-8939-d78d993b41ae)

We're updating our plugin, where we decided to change the name of a property `stay_open` to `open/wait_time`. When our editors will update the plugin, they will lose data at the first save of the scene.

![godot-lost-props-2](https://github.com/user-attachments/assets/25992e5c-5773-4db9-96f9-fbbd79567a23)

The problem is more important when using gdscipt. Our level editors can write some scripts to extend the functionality. Changing the property name (@export var) is very easy, and there are no warnings. So they will lose their data more often.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Just do not delete unused data from tscn files. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. Do not delete data already stored in (t)scn files
2. Show in the inspector a list / dictionary of unhandled properties. Let user decide what to do - remove, move or copy.
3. Allow to access to unhandled properties from the code. Plugin authors will be able to implement a conversion tool.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is related to the core of the Godot Editor.

### Is there a reason why this should be core and not an add-on in the asset library?

It applies to every single project. Nobody wants to lose data.

**Comment by marcinnformula** [comment]
Please delete the issue. I must switch to the proper GH account.

**Comment by Calinou** [comment]
- Superdeded by https://github.com/godotengine/godot-proposals/issues/10694.
