### ISSUE TITLE
Use collision detection ray to reposition objects already in the scene similar to drag-and-drop functionality

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot-proposals#10692]
### Describe the project you are working on

Free and Open-source warehouse/manufacturing simulator: https://github.com/Open-Industry-Project/Open-Industry-Project

### Describe the problem or limitation you are having in your project

It would be nice to be able to use the drag-and-drop to instantiate functionality, but with objects already in the scene.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

https://github.com/user-attachments/assets/3064a913-d73e-45d3-ae7f-1094a8de7d9a

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See video above.

It is the same way the drag-and-drop functionality works, but with objects in the scene. The first pass of this proposal would probably be limited to 1 object at a time. It would be associated with some key that isn't used, or maybe not even enabled by default. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Probably not

### Is there a reason why this should be core and not an add-on in the asset library?

I personally think this is useful enough to core since similar functionality exists such as drag-and-drop and snap to floor.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/755.
