### ISSUE TITLE
Expose functions for manual iterator traversal

### ISSUE THREAD

**Issue by Ivorforce** [godotengine/godot-proposals#10701]
### Describe the project you are working on

Just helping people on Discord when this came up.

### Describe the problem or limitation you are having in your project

When you have an iterator, you are 'expected' to drain it in a for loop. Manual traversal is neither documented, nor desired.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Creating iterators and traversing them manually should be supported with user-oriented functions, and documented.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add needed functions that support this, or a similar, workflow:

```gdscript
var iterator := array.create_iterator()
if iterator.is_done():
    return
var next := iterator.get()
if !iterator.advance():
    return
next = iterator.get()
```

This is not aligned with how python does it (StopIteration exception etc.), but rather with how Godot does it behind the scenes right now (referencing `_iter_next(arg)` and `_iter_get(arg)`.

A cleaner use would eliminate separate get, advance and is_done, but I can't think of a good way that would work without major changes to iterators (and possibly gdscript).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

(with reference to https://github.com/godotengine/godot/blob/d0dc3896ad6fe039e4ad0607d901c81197cb3a3b/modules/gdscript/tests/scripts/runtime/features/object_iterators.gd#L1)

```gdscript
var iterator := MyIterator.new(3)
var store := [null]
if !iterator._iter_init(store):
    return
var next := iterator._iter_get(store[0])
if !iterator._iter_next(store):
    return
next = iterator._iter_get(store[0])
```

### Is there a reason why this should be core and not an add-on in the asset library?

Manual iterator traversal is a common pattern present in most programming languages.

**Comment by dalexeev** [comment]
* godotengine/godot#89649 was recently merged.

![](https://github.com/user-attachments/assets/641cec3e-d6e4-4b62-ab52-67a01b68a411)

Is that enough or did you mean something else?

**Comment by Ivorforce** [comment]
That's the baseline, as described above. I'm proposing a more streamlined, user-oriented API in-line with other languages. Basically a few small wrappers around theis API.

**Comment by dalexeev** [comment]
You can write a wrapper. `iterable` can be an array, a dictionary, an object implementing the Iterator API, etc.

```gdscript
class ManualIterator extends RefCounted:
    func _init(iterable: Variant) -> void:
        # ...

    func is_done() -> bool:
        # ...

    func advance() -> bool:
        # ...

    func get_value() -> Variant:
        # ...
```

**Comment by Ivorforce** [comment]
Oh yeah, I suppose that's true. While the underlying API is not what I'd expect from an iterator API, being able to make my own wrapper is good enough for me. I'll close the proposal with this. Thank you for your time!
