### ISSUE TITLE
Add support to increasing values in options by mouse drag

### ISSUE THREAD

**Issue by sturl4ny** [godotengine/godot-proposals#10716]
### Describe the project you are working on

Im learning godot and think of that this feature might be handy for developers.

### Describe the problem or limitation you are having in your project

No limitations just QOL

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It's easier to see the results more dynamic when you will be able to leftclick the any value on right hand side and drag to right to increase and left to decrease the value - this feature is available in adobe premiere.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It's a QOL feature.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The values can be always set by script but if you will see how does chaning the value, change the outcome in your project in a dynamic way, people can develop faster and compare the results almost instantly.

### Is there a reason why this should be core and not an add-on in the asset library?

It's great QOL feature that make my work easy in adobe premier and i was using it all the time, insted of changing the value by typing them each time if i wanted to see what will be the result when the values changes.

**Comment by Meorge** [comment]
Unless I'm misunderstanding what you're looking for, this is already a thing in Godot 4.3:

https://github.com/user-attachments/assets/38113329-6848-4803-9942-999028975fcb

**Comment by sturl4ny** [comment]
Hey!

oh wow, you are totally right. For some reason it did not worked for me at
one field not sure why, but maybe i was just lucky - now that i'm testing
it, it's there - working just great! thanks for letting me know!

wt., 10 wrz 2024 o 23:03 Malcolm Anderson ***@***.***>
napisał(a):

**Comment by Meorge** [comment]
No problem, glad it's working for you now! Always a nice surprise to want a feature and then find out it already exists :D

**Comment by sturl4ny** [comment]
Oh yes, that was extremely fast implementation :D Keep on doing great work!

wt., 10 wrz 2024 o 23:08 Malcolm Anderson ***@***.***>
napisał(a):

**Comment by dalexeev** [comment]
Closing as already implemented. Thanks for the contribution nonetheless!
