### ISSUE TITLE
Individual key/value based Dictionary types.

### ISSUE THREAD

**Issue by SweetRazory** [godotengine/godot-proposals#10736]
### Describe the project you are working on

2D Isometric Story/Roguelike game.

### Describe the problem or limitation you are having in your project

In the editor when I export a Dictionary variable, I want to be able to instantly set message strings, or textures, and always picking the correct type of a field annoys me. Having individual key/value based types would make my life so much easier. Also having conditional types, like when x key is set to true, make the dictionary type this and that would be absolutely fantastic.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature would help create more Typesafe configurations, and also make working with Dictionaries in the editor easier and more faster, by using autocompletion, key/value generation, and setting types automatically.

Basically Typescript like Typing, the closer the better.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In my mind, the feature would look similar to what Typescript has with Objects.
```
I use Record here, but wrapping the Object type in {} would also work, not like it matters here :D 

const stuff: Record<{
    "key1": String,
    "key2": Record<{
        "innerKey1": Array<any>
    }>
}>[]
```
Where you can specify each key to be x and y type, and also conditional types.

And in Godot I imagined it like this:
```
@export var stuff: Array[Dictionary[{
    "key1": String,
    "key2": Dictionary[{
        "innerKey1": Array
    }]
}]]
```

These types would be enforced when modifying the variable in the editor, so adding new key/value pairs or removing them would be disabled.
And when wrapped into an Array type, adding a new Dictionary, would add these key/value pairs automatically.
And of course the editor should be smart enough so it autocompletes when I try to get a nested value like stuff[0].key1.key2.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Autocompletion, and keys/values having the desired type when created, without setting their values beforehand, would need a bunch of Dictionary specific code, which can easily multiply the lines of code in a project.

### Is there a reason why this should be core and not an add-on in the asset library?

I feel like people who come from strongly typed programming languages need to swallow this hard pill, and speaking from my experience, I feel a bit uncomfortable that I cannot specify what Types/behaviour I want for my variables, and also the hassle of setting everything by hand, and not getting it automatically also annoys me a bit.

**Comment by AThousandShips** [comment]
How would this be different from [typed dictionaries](https://github.com/godotengine/godot-proposals/issues/56)?

**Comment by Cykyrios** [comment]
Maybe what you're looking for is actually structs? (see #7329) That's how I would interpret a dictionary with different types for every key/value pair.

**Comment by SweetRazory** [comment]
@Cykyrios Yeah, that's exactly the solution I'm looking/asking for, just in a different format :) As long as the Types can be reassigned at runtime, I don't care about the syntax.

(Actually, this Struct syntax look a lot more polished tbf)

**Comment by dalexeev** [comment]
* Thanks for the proposal, consolidating in #7329.

I think a separate type category "structure" makes more sense than combining different kinds of typed dictionaries (key-value vs fixed list). Also, arrays seem more efficient/compact than dictionaries for implementing structures, due to the lack of hashing.
