### ISSUE TITLE
When using a SubViewport to show 2D scenes the normal map information is lost.

### ISSUE THREAD

**Issue by tipspit** [godotengine/godot-proposals#10734]
### Describe the project you are working on

A 3D game with a lot of 2D elements projected on meshes throught SubViewport or rendered on materials.

### Describe the problem or limitation you are having in your project

When using a SubViewport to show 2D scenes the normal map information is lost.
SubViewport.get_texture() returns a ViewportTexture that does not contain the information regarding normal maps.
For example, if I wanted to project a scene containing some Sprite2D and related textures (CanvasTexture containing diffuse_texture and normal_texture) onto a PlaneMesh using a SubViewport, currently there is no way to make it interact properly with the light coming on the mesh in the 3D environment, because the data about the normal maps is lost.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Some solutions:
- Set the diffuse_texture and normal_texture properties to ViewportTexture, mimicking the behavior of CanvasTexture.
- Add the get_normal() method to SubViewport.
- Make the SubViewport Rendering > Debug Draw > Normal Buffer feature that already works with 3D scenes work for 2D scenes as well. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

To implement it I think it would be necessary to access a Normal Buffer for the 2D scene, something similar to the one existing for 3D scenes, but I don't know if it is possible.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I have not found a way to do it with a workaround. Thought about duplicating the scene and render it only with normal maps, or calculating the lights vectors impacting the viewport in real time to add a corresponding light in the 2D scene, but these solutions are inefficient and performance demanding.

### Is there a reason why this should be core and not an add-on in the asset library?

I think that not permitting a SubViewport to contain the informations regarding the light management of its scene is a big limitation.

**Comment by AThousandShips** [comment]
This sounds like a bug, please open a bug report [here](https://github.com/godotengine/godot/issues) instead, or rewrite the proposal to be a proposal to be more focused on what you want and need as this reads as a bug issue not a proposal

**Comment by tipspit** [comment]
> This sounds like a bug, please open a bug report [here](https://github.com/godotengine/godot/issues) instead, or rewrite the proposal to be a proposal to be more focused on what you want and need as this reads as a bug issue not a proposal

I opened a bug [here](https://github.com/godotengine/godot/issues/96976) as you suggested
