### ISSUE TITLE
Add (optional) visual marker to Debug builds to make them easy to identify

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-proposals#1073]
**Describe the project you are working on:**
The Godot Engine :]

**Describe the problem or limitation you are having in your project:**
As outlined in #1071 and #1072, it's not always clear to Godot users when they are using/shipping a Debug build, and what kind of consequences it has on their game (performance, size).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
As suggested initially in godotengine/godot#19667 and godotengine/godot#20219, we could make this more obvious e.g. by adding a (opt-out) watermark on Debug builds, so that they're clearly identified as such. The watermark could be disabled in the export preset (or possibly further customized if we don't feature-creep too much).

Alternatively, it has also been suggested to use a red border for the window of Debug builds (which similarly would be opt-out). Doing both is likely overkill, but we can discuss whether we want one, the other, or another option.

Another change done recently by @Calinou is that Debug builds will now have a " (DEBUG)" appended to their window title, unless overridden manually by a call to `set_window_title()`. This could be considered sufficient and thus this proposal could be closed, but I do think that the watermark idea could still be interesting to consider.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Running or exporting a Debug build would superimpose a small but noticeable watermark to the game UI, probably in a corner. There would be a boolean option in the export preset for this watermark (enabled by default), so that users can disable it if they don't want it or want to make them own more customized one.

It could look like this:
![Screenshot_20200616_153227](https://user-images.githubusercontent.com/4701338/84782220-0dfa4380-afe8-11ea-8db6-e0b0ce5bff17.png)
This uses a custom font (Fira Sans), Godot's default font is not as pretty, so if we use the default font it might not look so good. (It's way beyond time we rediscuss Godot's default font, but that's outside the scope of this issue.) I used colors with transparency for both the text and its shadow, so that one could still see what's behind - it could be made even less opaque, but then there's the risk that it doesn't stand out so much.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm not sure how often this would be used, hence this proposal to get some community feedback.

It's fairly easy to implement for your own game if it was not implemented, as showing a watermark on Debug builds is as easy as doing:
```
if OS.is_debug_build():
	$DebugWatermark.show()
else:
	$DebugWatermark.hide()
```
Yet this needs to be done in all scenes/via a singleton, so it may be a bit bothersome.

**Is there a reason why this should be core and not an add-on in the asset library?:**
That mostly depends on how useful the community would find this. It could definitely be an add-on in the asset library (and then with tons of customization options to cater to all use cases under the sun :)).

**Comment by bruvzg** [comment]
Instead of just "DEBUG build", it should additionally show some useful information, e.g. engine and project version + user customizable text (like link for reporting issues). I would also, make font smaller and less opaque.

**Comment by katoneko** [comment]
It could be a banner in one of the top corners of the window if we just want a small marker.
Like this (see the top-right corner)

![image](https://user-images.githubusercontent.com/48890128/84788140-38f48f80-b008-11ea-954f-07b66d17c62f.png)

**Comment by pycbouh** [comment]
I’m a proponent of leaving things like this to the developer’s discretion. Yet making it opt-in instead would be pointless to say the least. I understand where this is coming from, but on the other end of scale there is going to be an increase in “how do you remove that annoying debug label” posts and questions and issues. Then goes the question of “Do we stop at DEBUG, or do we add something more to it”, like it is already suggested. How should it look, to comply with everyone’s expectations? What if I want to integrate it better into my game’s UI, how customizable is it?

There isn’t going to be a solution for everyone, if it’s inside the window at least. It’s the kind of thing that is either too unnoticeable to help those who miss the difference, or too noticeable for those who are going to be bothered by it.

**Comment by groud** [comment]
One solution might be to make the label clickable/hoverable, which would pop-up a menu allowing to dismiss the label. Eventually the menu could be used to display more information too (like version, etc..)

**Comment by clayjohn** [comment]
Im a little unclear on the particular problem this is trying to solve. I can see two distinct but related problems:
1. Users are testing the engine in debug instead of release and noticing what they think are performance regressions.
2. Users are accidentally exporting debug builds and sending them on to users not realizing the performance impact of doing so.

**Comment by akien-mga** [comment]
> Users are testing the engine in debug instead of release and noticing what they think are performance regressions.

If by this you mean testing the editor build with `target=debug` instead of `target=release_debug`, this is not what this aims to address (but that's also a valid problem that likely needs to be addressed too in its own proposal). The watermark proposal is only for when you actual run the game, not for the editor itself, and would be visible with any editor build (either `target=debug` or `target=release_debug`) and any debug template (whether the default `target=release_debug` or a custom `target=debug` one).

Though that might be up for discussion, and maybe showing the watermark while running the game from the editor is not a good idea (it would then appear on e.g. video tutorials, etc., which might be a bother). Though it could be kept only for export debug builds (`OS.is_debug_build() and not Engine.is_editor_hint()`).

> Users are accidentally exporting debug builds and sending them on to users not realizing the performance impact of doing so.

That's one of the problems that this proposal aims to address yeah, together with #1071 and #1072. Though it's not just about accidentally exporting debug builds but also about not being aware of the difference between release and debug builds, and especially the performance impact of the latter. This proposal is arguably the least important/necessary of the three, and solving #1071 and #1072 should greatly reduce the need for such a visual mark.

> One solution might be to make the label clickable/hoverable, which would pop-up a menu allowing to dismiss the label. Eventually the menu could be used to display more information too (like version, etc..)

That could be problematic if your game actually has interactive components where the watermark gets printed.

**Comment by akien-mga** [comment]
From early reactions, I'm tending towards the "let's make this an addon" idea, which would allow to make it as customizable as wanted without arbitrarily imposing visual changes to user's games. The resolving of #1071 and #1072 plus the newly added "(DEBUG)" suffix in the window title should already be sufficient to improve the release/debug confusion.

**Comment by groud** [comment]
> That could be problematic if your game actually has interactive components where the watermark gets printed.

If it allows you to dismiss the label, that's less of a problem though. Also, if we want something more advanced, we could even imagine being able to move the label/button dragging it around (snapping it to corners I guess).

**Comment by Calinou** [comment]
@groud Maybe the debug label could fade away after displaying for ~10 seconds or so.

**Comment by akien-mga** [comment]
I made a simple scene that can be used as addon to add such a debug watermark to your projects:
https://github.com/akien-mga/godot-debug-watermark

![Screenshot_20200618_162031](https://user-images.githubusercontent.com/4701338/85032031-a37c0b80-b17f-11ea-8967-24e4eef88708.png)

![Screenshot_20200618_162055](https://user-images.githubusercontent.com/4701338/85032087-b42c8180-b17f-11ea-9847-1a0e4c71af24.png)

PRs welcome to add more features/customization options (e.g. making a nicer looking tooltip that the ugly default one).

**Comment by akien-mga** [comment]
I'll close this as I no longer think this should be implemented in the engine itself.

See https://github.com/akien-mga/godot-debug-watermark for an attempt at making a (public domain) asset that any interest user can reuse in their own projects.
