### ISSUE TITLE
Implement reStructuredText generation for online documentation of GDExtensions

### ISSUE THREAD

**Issue by Ivorforce** [godotengine/godot-proposals#10733]
### Describe the project you are working on

A gdextension.

### Describe the problem or limitation you are having in your project

GDExtensions cannot currently generate online documentation akin to the [godot docs](https://docs.godotengine.org/en/stable/index.html). An online reference is an important alternative to in-editor documentation, especially before installation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

GDExtensions should be able to generate online-compatible documentation, much like [make rst](https://github.com/godotengine/godot/blob/master/doc/Makefile) for the godot engine itself.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

godot-cpp has [recently](https://github.com/godotengine/godot-cpp/commit/a434850069212b2d2dbe70fd82c4e5774b739040) acquired the capability to generate ingame docs files (doc_classes xml files), thanks to dsnopek. It should be possible to adapt some more of the [godot engine documentation pipeline](https://github.com/godotengine/godot/blob/master/doc/tools/make_rst.py) to generate rst files, that can be adapted by e.g. Sphinx to be hosted on a site.

I will be playing with the tool soon, especially as it tool may already support foreign docs to some capacity. If so, it could be integrated and / or its use documented for gdextensions that want to host documentation online.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really, though you could manually set up sphinx, duplicating your documentation.

### Is there a reason why this should be core and not an add-on in the asset library?

Docs are an important part of complex libraries, useful to all gdextensions.

**Comment by dsnopek** [comment]
This draft PR may also be interesting to you - it aims to put inline Doxygen comments in godot-cpp itself, so your IDE can help give you documentation: https://github.com/godotengine/godot-cpp/pull/1311

**Comment by Ivorforce** [comment]
I came across the PR as I was researching for this. It would be an excellent addition, though it's orthogonal to what I propose here.

**Comment by dalexeev** [comment]
`make_rst.py` only reads XML files, so you can probably run it against GDExtension docs too.

**Comment by Ivorforce** [comment]
I tested `make_rst.py`. It complains a ton, and I had to add a `version.py`, file to my own project to make it happy, but it does spit out correct looking `.rst` files.

## The approach, outlined

I think the first step should be to make the script officially support gdextensions, without complaining. The best way to use it without cloning the repo may be the way poetry handles their installer:

```bash
curl -sSL https://raw.githubusercontent.com/godotengine/godot/master/doc/tools/make_rst.py | python3 -
```

Finally, we'll need to add documentation for how to gdextensions should use the tool.

I don't think any of this will be a big burden to the existing tooling, so I'll just go forward prepare PRs in the next 1-2 weeks.

**Comment by Ivorforce** [comment]
I was able to build the docs into a readthedocs repo, mirroring the one godot uses: https://numdot.readthedocs.io/en/latest/introduction/about.html

To achieve this:
- Create `docs/`
- Add godot-docs as a submodule
- Copy over and modify `conf.py`, `index.rst` and `.readthedocs.yaml`.

For anyone coming across here looking to create docs for their own gdextension, feel free to use my implementation as a template: https://github.com/Ivorforce/NumDot/tree/main/docs

I will consolidate this information into a wiki page to the [gdextension docs page](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_docs_system.html). It would be nice to have a 'simpler' way for adding docs without depending on the full godot docs repo, but for now this is an acceptable workflow.

**Comment by Ivorforce** [comment]
As https://github.com/godotengine/godot-docs/pull/9966 was merged, the scope of this proposal is fulfilled: Generating online documentation from the ingame documentation is now a treaded and loosely documented path. With this, I'll close this proposal. 

To view the docs entry on the matter, visit the article [GDExtension Docs System](https://docs.godotengine.org/en/latest/tutorials/scripting/gdextension/gdextension_docs_system.html) (the changes should be viewable soon).

The outlined workflow could certainly be better, but it could also be a lot worse. Any improvements to it should be separately proposed.
