### ISSUE TITLE
Add a console/REPL/expression evaluator for debugging GDScript

### ISSUE THREAD

**Issue by severin-lemaignan** [godotengine/godot-proposals#1074]
**Describe the project you are working on:**

Several game dev (!)

**Describe the problem or limitation you are having in your project:**

[issue imported from https://github.com/godotengine/godot/issues/7057]

Debugging gdscript is difficult without being able to quickly inspect and/or manipulate variables. Many platforms/language have a tool to open an interactive console at arbitrary points, and inspect & execute code (from `pdb.set_trace` in python to the javascript console found in Firefox/Chrome dev tools).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

When debugging a game, the debugger panel should feature an additional sub panel or tab with an interactive console where gdscript command could be entered and executed.
The scope should be matching the local scope where the code has been interrupted (via a breakpoint or an exception).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

See above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This would form a key part of the debugging toolset.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/26219 where this feature was implemented, but it wasn't merged. Note that GDScript will be rewritten from scratch in Godot 4.0.

**Comment by severin-lemaignan** [comment]
Ok! Closing then!

**Comment by Calinou** [comment]
You could leave this proposal open - I think the feature is still relevant.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4473, which was created following an implementation of the feature.
