### ISSUE TITLE
Add a quad mesh to the material preview in the inspector

### ISSUE THREAD

**Issue by tetrapod00** [godotengine/godot-proposals#10744]
### Describe the project you are working on

Writing shaders.

### Describe the problem or limitation you are having in your project

There is no good preview mesh to preview VFX, foliage, or billboarding shaders. We are missing a single quad with UVs in the range of 0-1.

The box mesh might be usable to preview such effects in some cases, if it were unwrapped so that each face had 0-1 UVs. As is, it's not really usable for this purpose.
![godot windows editor dev x86_64_kBL64QYwtc](https://github.com/user-attachments/assets/cb3fe987-ac36-47b3-a3cc-697dcba2f7bd)

Previewing a VFX shader, like this simple radial gradient with alpha, looks terrible on the sphere and box:
![godot windows editor dev x86_64_NfUAqOkMdR](https://github.com/user-attachments/assets/92e3ff6e-35ac-46df-8055-49b50bd3f3bd)
![godot windows editor dev x86_64_NtbDEwT6Qd](https://github.com/user-attachments/assets/d9814f4d-4d08-40fc-8f6d-8f21823937ad)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a quad mesh with 0-1 UVs:
![godot windows editor dev x86_64_yEdVdJqJCA](https://github.com/user-attachments/assets/26f816fd-e219-4359-abd6-134c6b91e6de)

Previewing a VFX shader, like the radial gradient, looks correct with a quad mesh:
![godot windows editor dev x86_64_XQyBJSr5ym](https://github.com/user-attachments/assets/ecf1a707-e142-4b5c-940f-2b4eb4534a1b)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Duplicate the existing code for a box or sphere, but with a quad mesh instead.

With a quad mesh, there are some extra usability considerations. Unlike the sphere or box mesh, with backface (default) culling, the quad is only visible from some angles. It's possible to rotate the quad such that you cannot see it. **I believe this is a valid usecase**, as you may be testing double-sided materials. I don't believe that limiting the rotation, or forcing a double sided quad is the correct solution. Instead, whenever you select the quad mesh, the rotation resets so you can see the quad.

If instead we would rather limit the rotation so the quad is always visible, most of the code is already in place to do so.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can preview your materials by creating a scene with a quad mesh instead.

### Is there a reason why this should be core and not an add-on in the asset library?

The quad is a common, standard shape for previewing shaders, and it fills a gap in the current featureset.

**Comment by FyiurAmron** [comment]
does anyone know if a matching switch/editor setting exists for FileSystem preview window? I weren't able to find any switch related to it, and it defaults to the sphere for me. @tetrapod00 ?

**Comment by Calinou** [comment]
> does anyone know if a matching switch/editor setting exists for FileSystem preview window? I weren't able to find any switch related to it, and it defaults to the sphere for me. [@tetrapod00](https://github.com/tetrapod00) ?

FileSystem previews use an entirely different way of rendering (they are statically generated and not rendered in real-time). There are no options available, so only a sphere can be used.

If options were implemented, it would require regenerating all thumbnails to have a visible change on existing materials.
