### ISSUE TITLE
ProjectSettings.load_resource_pack custom root argument

### ISSUE THREAD

**Issue by walksanatora** [godotengine/godot-proposals#10745]
### Describe the project you are working on

I am trying to make a project with simple (but non overwriting mod loading)
The ability to specify a root within the resource tree would make it easier to section mods off into their own areas

### Describe the problem or limitation you are having in your project

Currently whenever you load a packed scene you have to dump all it's content into the root `res://` folder. Which prevents me from having each mod have a eg:  mod.json file in it's root as then the first mod to load is the only one with it's json present

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would allow me to make eg: res://mods/modA modB modC and have each unpacked into their own folders

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Mabey a `root: String = "res://"` argument for the load_resource_pack function

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Leave the extra argument blank and it will default too root just like the old behaviour

### Is there a reason why this should be core and not an add-on in the asset library?

This should be in core because I don't see any way for add-ons to implement this feature.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/7769
