### ISSUE TITLE
Highlight scripts used by current scene

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot-proposals#10750]
### Describe the project you are working on

I was just tinkering with the engine and accidentally found a 9 year old feature which was later removed...

### Describe the problem or limitation you are having in your project

There is a fairly common confusion as to how script editor relates to opened scene. Usually in form of "add scripts to top tabs instead of it's own list" or something.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Highlight the scripts that are used by currently opened scene. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![highlighting](https://github.com/user-attachments/assets/dbd02cab-54e2-472c-82b6-63e81628388c)
This feature is actually still fully implemented and functional (added in [e9bbb97](https://github.com/godotengine/godot/commit/e9bbb97acccc08ae03fde41e4cc6d2dc6722021a)), it's just overridden by 1 line of code (in [081a236](https://github.com/godotengine/godot/commit/081a236c6739e7f6d45731ec0c002d2269f2367b)). Just need to tweak the color, originally it was really attention grabbing and also covered the selected/hover color.
PS. custom icons in the screenshot above are unrelated here, I just grabbed it from my current build where I accidentally summoned the feature.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It's already existing feature and also one that cannot be implemented by addon. Either reimplement it or remove unused code if the feature is not wanted.

**Comment by Calinou** [comment]
Does the feature work with C# scripts (when the external editor is disabled)?

**Comment by aXu-AP** [comment]
I'll do a pr to get the mono build, I'm not feeling like learning how to do it myself 👀

**Comment by aXu-AP** [comment]
Ah, shortsighted me forgot that artifacts don't include Mono build for Windows. Well, if any Linux user wants to test it, the build is there for grabs in linked pr.

**Comment by mgrider** [comment]
> There is a fairly common confusion as to how script editor relates to opened scene. Usually in form of "add scripts to top tabs instead of it's own list" or something.

I came to this repo to find someone griping about the issue you mention. (And to pile on.) I realize this issue is not exactly the one I'm complaining about, but I do want to chime in and say that I think re-enabling this might make the issue I'm looking to gripe about _worse_.

(My proposed solution is to fully deselect any nodes in the Scene tab – and Files in the FileSystem tab – if they don't pertain to the currently edited/shown script.)

**Comment by aXu-AP** [comment]
> My proposed solution is to fully deselect any nodes in the Scene tab – and Files in the FileSystem tab – if they don't pertain to the currently edited/shown script.

Could you elaborate what is the problem this solves?

**Comment by mgrider** [comment]
I did elaborate a bit in [a comment on 10163](https://github.com/godotengine/godot-proposals/issues/10163#issuecomment-2364726680), but in essence each editor panel has its own selection, and it's quite easy for the selections to get out of sync with one another.

That's one aspect of the issue, but I think the more important one is how easy it is to hide the Scripts Panel, which is literally the only thing that shows you which file you are editing in the code editor. I've been thinking about this for a few days now, and I think that's a proposal I'm sure about now. I think Godot should show the current filename (& optionally path) somewhere either above or below the code as its being edited.

Finally, I think there's also an issue of the "visual weight" of all the selections shown in the editor. Currently, the eye really doesn't know what is the most important thing. It's entirely possible Godot also doesn't know the most important thing. But it does have some concept of which panel is "active" (although I think the 2d/3d scene "steals" the active selection when you just hover over it, which feels like another issue).

**Comment by aXu-AP** [comment]
> I did elaborate a bit in [a comment on 10163](https://github.com/godotengine/godot-proposals/issues/10163#issuecomment-2364726680), but in essence each editor panel has its own selection, and it's quite easy for the selections to get out of sync with one another.

I kind of see the point, but I think there's value of each panel having their own state. Whenever I need something from the filesystem, it's easier to orient myself if it is in the state I left it. Of course, some things are linked strongly together, like selecting a node in 2D or 3D view selects it also in the Scene tab and vice versa. I think coding is a slighly different thing, however, which warrants a different approach. It would be hard to imagine that selecting different nodes would open their scripts automatically for example. I inspect variety of nodes during scripting for checking/adjusting various properties for example. And there's the script button besides node name so there is a link when you need it.

Changing scenes is a different thing because youre changing the whole context. That's why I have turned on editor setting `text_editor/behavior/files/open_dominant_script_on_scene_change`. This proposal also helps with understanding the state of the editor.

> Finally, I think there's also an issue of the "visual weight" of all the selections shown in the editor.

That's why you have the option to turn this proposed feature and also script temperature off. In fact, there's the distraction free mode which hides all the other panels. I'm not sure how else one could reduce visual weight in the editor, it's all useful information that should be available.
