### ISSUE TITLE
Make freelook not center the mouse cursor after exiting freelook mode (and remove the crosshair)

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot-proposals#1076]
**Describe the project you are working on:**
Just looking forward to using godot

**Describe the problem or limitation you are having in your project:**
Looking around the 3D view with rightclick moves the cursor to the viewport center and displays a crosshair. Both of these actions are somewhat unnecessary and force-centering the cursor is even a little annoying as one has to reposition the mouse after every freelook (which in most cases is done quite frequently).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There should be toggles to disable the display of the crosshair and for recentering on freelook, or alternatively the crosshair just be removed and recentering disabled by default.
The crosshair currently may be a tiny helper in certain circumstances for selecting objects, but only because the recentering (mis)behaviour is there too. If the cursor didn't recenter, releasing the mouse to select objects would be a more consistent/direct rotate-view-select flow.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Internally the recentering could still be happening to make freelook work correctly, but on release the mouse should be positioned to the point where the initial click happened, as the action from a users point of view is 'grabbing the camera', not entering shooter mode. Or if implemented as setting there could even be an option that just does not lock the cursor (as unity does for example).
Removing the crosshair is probably simpler.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's internal to the editor behaviour, so it can't be worked around.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's internal to the editor behaviour, so it can't be user-scripted.

**Comment by Calinou** [comment]
> There should be toggles to disable the display of the crosshair and for recentering on freelook, or alternatively the crosshair just be removed and recentering disabled by default.

See https://github.com/godotengine/godot/pull/34801 where I added a crosshair. I decided against adding an editor setting as it doesn't seem like a significant enough feature to toggle. If we find a way to avoid the cursor centering when stopping freelook, we should remove the crosshair entirely as it'll no longer serve a purpose.

**Comment by aaronfranke** [comment]
@Flavelius What was the reason for wanting the crosshair removed? I thought it was nice. Just because it was unnecessary?

**Comment by Flavelius** [comment]
@aaronfranke It's somewhat related to the issue described in this thread. It only served as an indicator/visual confirmation that the hidden recentering happened. 
Apart from that my personal reasoning is more related to the aesthetic; godot was the only editor to have an fps-crosshair (but you cannot shoot with it) and the sprite gave it a certain old-school aesthetic that may relate to some, but as godot is intended to be used for all type of games and people, making it a bit more neutral is probably a good decision. These are my opinions though, but i'm all behind the actual justification that it's unnecessary, now, even more that the correct/standard/expected mouse behaviour is restored.
