### ISSUE TITLE
Allow replacing RenderingServer

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot-proposals#10778]
### Describe the project you are working on

Custom renderer + raytracing support from gdext

### Describe the problem or limitation you are having in your project

I want to be able to completely replace what godot uses to store materials/meshes/instances etc. Or to be able to atleast *know* what it has. I also want to override the way things are rendered.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would allow developers to replace the entire rendering pipeline drop-in from project settings, allowing gdextension to overhaul everything used to render Godot.

This behavior can be considered as "adding more rendering methods" (up for discussion)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Implementation of a RenderingServerManager, which allows gdextension modules to register, during server init, the other rendering servers.

Implementation of RenderingServerExtension meant to be overridden and used with it.

During register, gdextension may say that it still requires the native singleton (In this case, it overrides some of the methods, but not all)

Renaming `RS::get_singleton` to `RS::get_native_singleton` to still allow native rendering server methods to be called (unless gdextension says it doesnt need the native one, in this case it may need its own main rendering device)

Implementing `RS::get_singleton` to return a potentially overidden RenderingServer

When RenderingServerExtension is being initialized, the main rendering device is passed to it.

In the case of rendering server getting new methods and the rendering server extension still not being up to date, it should throw an error.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Currently only drawing can be overriden during 3D rendering by setting the texture to 1x1 and then back to the normal res during compositing.

### Is there a reason why this should be core and not an add-on in the asset library?

Cannot be implemented in an addon.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/4287

Which covers this topic and has a lot of responses, add anything you feel might be missing from your proposal there
