### ISSUE TITLE
Allow horizontal scrolling in 2D Tab

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1077]
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
In the 2D Tab I want to scroll horizontally but I don't want to click and hold this scrollbar and I don't have a mouse with 3D mouse wheel.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
You should be able to scroll horizontally while holding shift. In the Script Tab this already works.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, it's useful for everyone who makes a 2D game.

**Comment by Calinou** [comment]
This makes sense, but keep in mind that scrolling the mouse wheel in the 2D editor will zoom, not pan. So, it'd be a bit strange to have the 2D editor scroll when you use <kbd>Shift</kbd> + mouse wheel.

Still, I think providing this feature is better than not providing it.

**Comment by MaaaxiKing** [comment]
Oh yes, forgot that because I enabled Scroll To Pan in Editor --> Editor Settings --> Editors --> 2d. In most programs this is more common, so maybe this should be enabled by default?!

**Comment by Calinou** [comment]
@MaaaxiKing There's been some discussion about it, but there doesn't appear to be a clear consensus: https://github.com/godotengine/godot/issues/7409

**Comment by MaaaxiKing** [comment]
If more people don't like it to be enabled by default, I think horizontal scrolling should be allowed holding <kbd>Shift</kbd> anyhow but only if Scroll To Pan is enabled.
