### ISSUE TITLE
ScrollContainer Expand behaviour

### ISSUE THREAD

**Issue by EntityinArray** [godotengine/godot-proposals#10776]
### Describe the project you are working on

A 3D space game with heavy use of cut-out animation

### Describe the problem or limitation you are having in your project

ScrollContainer always collapses entirely and turns into a thin horizontal line.
This is a useless default behaviour which makes it unintiutive for making scrollable containers. Expand option is greyed out

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow Expand behaviour for the ScrollContainer.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

ScrollContainer will always expand to fully fit its contents onto the screen. Scroll bars will *only* appear when there's nowhere to expand (no more window space/parent space for example)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can use `custom_minimum_size` parameter to force minimum size for ScrollContainer
But then your UI has hardcoded sizes and is not adaptive

### Is there a reason why this should be core and not an add-on in the asset library?

Default ScrollContainer behaviour is turning any content into 1px strip that you can't even scroll. This makes scrolling containers very counter-intuitive to make in Godot.

**Comment by kleonc** [comment]
This proposal makes no sense to me, I'd say there's some misunderstanding how Containers work / what expand flags do.

> ScrollContainer always collapses entirely and turns into a thin horizontal line.
This is a useless default behaviour which makes it unintiutive for making scrollable containers. Expand option is greyed out

If expand option is greyed out this means that the parent Container doesn't allow / take into account such flag, hence it's disabled (it won't take any effect anyway).

E.g.:
- PanelContainer always expands its children to its own size, hence it doesn't allow setting expand flags (they're not taken into account anyway).
![Godot_v4 3-stable_win64_DDIWDaIx7o](https://github.com/user-attachments/assets/cb06cfb6-90d1-4117-ad47-43dd502030c6)

- VBoxContainer always expands its children horizontally, hence it allows setting only vertical expand flag on its children.
![iSVB85CyTA](https://github.com/user-attachments/assets/9fbdb122-f8e4-489d-8df1-6f9598c5d69e)

- ScrollContainer allows expanding its children on both axes:
![La3K0g30Xc](https://github.com/user-attachments/assets/ed3554a2-b958-4c32-9606-1052689460b2)

**Comment by EntityinArray** [comment]
Hi, thank you, looks like i misunderstood how containers work
