### ISSUE TITLE
Add node inside AnimationTree to set fixed duration for an animation

### ISSUE THREAD

**Issue by Deltt** [godotengine/godot-proposals#10780]
### Describe the project you are working on

3D adventure game; proposal relevant to all 3D projects with animated characters (maybe other objects as well)

### Describe the problem or limitation you are having in your project

Animation blending of multiple walk animations for omnidirectional movement animations require all animations to be blended to be the same length.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A node for adjusting an animation-node to a fixed duration before blending would solve this limitation in an easy way, inside of the engine.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Provide an additional node inside the AnimationTree that will set an input animation to a fixed duration.
The interface for this can be simply copied from the TimeScale node, except instead of the value being a multiplier, its the desired fixed duration.

Alternatively, a parameter could added to the BlendNode to normalize all used animations within the blend to the same duration.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The current workaround for this limitation is to have the to-be-blended animation all at the same length in the first place.

Another way _might_ be to adjust the animations length via the TimeScale, although it is extreme tedious to calculate the needed multiplier to aim exactly for the lead animations duration. I don't know how Godot handles animations internally, so there might also be the risk of those animations desyncing over time if the multiplier is not perfectly calculated or if animation timelines are measures in actual time rather than frames, of this I am not sure.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes. Animation is an integral part of most 3D games, and this issue has been discussed multiple times now on the Godot Cafe discord and other forums.

This would be a straight core QoL feature.

**Comment by TokageItLab** [comment]
It has been implemented by https://github.com/godotengine/godot/pull/87171
