### ISSUE TITLE
Clarify in "Copy System Info" whether the Godot client is running the X11 or Wayland DisplayServer

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-proposals#10787]
### Describe the project you are working on

Godot itself

### Describe the problem or limitation you are having in your project

Bug reports from Linux users which relate to windowing issues are pretty difficult to diagnose initially, because we need to know whether the user is running the X11 or Wayland version of the editor. See e.g. https://github.com/godotengine/godot/issues/97211#issuecomment-2363479718

The current line looks like this on my system:
```
Godot v4.4.dev (0a4aedb36) - Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)
```

So it says "Wayland", but I'm actually using the X11 version of the editor, on a Wayland session of KDE Plasma (i.e. through XWayland).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would tweak the report to make things more explicit, e.g. from:

> Godot v4.4.dev (0a4aedb36) - Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

to (changes in **bold**):

> Godot v4.4.dev (0a4aedb36) - Fedora Linux 40 (KDE Plasma **on Wayland**) - **X11 client (multi-window)** - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

I suggest adding "(single-window)" and "(multi-window)" too as it's often important information for GUI/input related issues.

CC @Riteo @Calinou

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Could be, but it would defeat the purpose of having better bug reports from the get go, and I think the current "Wayland" / "X11" mention of the OS session type is misleading at best.

### Is there a reason why this should be core and not an add-on in the asset library?

n/a, editor improvement for issue triage purposes

**Comment by Calinou** [comment]
Should we also list monitor count? Many UI issues only occur on multi-monitor setups.
