### ISSUE TITLE
Script Editor Split View Mode

### ISSUE THREAD

**Issue by SirPigeonz** [godotengine/godot-proposals#10785]
### Describe the project you are working on

Long Game Scripts that can't fit full script view

### Describe the problem or limitation you are having in your project

User has to perform excessive amounts of scrolling when editing longer script and in need to edit 2 different places in a script.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Introduce Split View Mode for Script Editor similar to Split View in 3D Editor. Feature often present in other IDEs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example from VSCode:
![obraz](https://github.com/user-attachments/assets/ea4a6748-ed2a-4d39-8845-77372394b5cd)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A Problem with Editor

### Is there a reason why this should be core and not an add-on in the asset library?

It's basic functionality important for UX. Should be available in vanilla editor.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/414

**Comment by felixmariotto** [comment]
much needed feature !

**Comment by neondeex** [comment]
+1

**Comment by Calinou** [comment]
@neondeex Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

Also, this proposal was closed as a duplicate of https://github.com/godotengine/godot-proposals/issues/414, so please continue the discussion there.
