### ISSUE TITLE
Godot should add syntax for deconstructing and assigning values

### ISSUE THREAD

**Issue by SGDS666** [godotengine/godot-proposals#10794]
### Describe the project you are working on

I extensively used dictionaries in writing scripts
For example, as
Function Parameters
Function return value
Custom class properties

### Describe the problem or limitation you are having in your project

When I want to retrieve a certain value or pass in a certain value
I think it's very tedious
Because I have been using TypeScript to develop modern websites for a long time
Comparing user experiences makes me feel uncomfortable

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add deconstruction assignment syntax and omission when key value variable names are consistent
It will make my life better

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript

func createPeople(params:Dictionary):People
    ...


func on_button_click():
    var name = "a"
    var age = 11
    var country = {...}
    var family = {...}

    #now
    createPeople({"name":name,"age":age,"country":country,})
    
    #I want
    createPeople({name,age,country,})



func on_grow_up(p:People):

  #now
  var limit = p.age * p.country.quota
  var after_tax = limit * p.country.tax_rate
  var useable = after_tax / p.family.members_count

  ...And more
  var a = p.xx * p.xx.x
  var b = p.xx + p.x.y
  var c = p.xx.x + p.x.z
  ...






  #I want 
  var {age,country:{quota,tax_rate},family:{members_count}} = p

  var limit = age * quota
  var after_tax = limit * tax_rate
  var useable =  after_tax / members_count

  ...And more
  var a = xx * x 
  var b = xx + y
  var c = x + z

  


```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not very achievable, requires syntax support

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, because it provides convenience at the grammatical level

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/2135
