### ISSUE TITLE
Support a wider character set in the default project font

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1079]
**Describe the project you are working on:**
Clicker Game
**Describe the problem or limitation you are having in your project:**
I want to write € in a Label if you want to use € instead of $. Russian, Chinese, Japanese letters, and I'm sure many more, also don't work.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
You could write whatever text you want.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Eurosupportgodot](https://user-images.githubusercontent.com/60623532/84926924-60149500-b0cc-11ea-8612-13bfc4d1ca8c.png)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it's not possible with add-on.

**Comment by Calinou** [comment]
You can already do this by loading a custom DynamicFont. The feature is already supported; the default bitmap font just doesn't include the required characters. https://github.com/godotengine/godot/pull/39603 will fix this.
