### ISSUE TITLE
Godot's current necessary functions

### ISSUE THREAD

**Issue by walker1412** [godotengine/godot-proposals#10795]
### Describe the project you are working on

I'm working on a 2D cartoon style game

### Describe the problem or limitation you are having in your project

I think godot should have a better encryption method for packaged works.
Purpose of godot users: to work for hobby or to earn money
However, the current godot packaged program is very easy to be cracked, especially when the game developed by the user involves network communication, even if the user has encrypted the communication process, but when the godot program is decompiled, the cracker can see the algorithms used in the network communication, then it can be restored to the communication process through other software, and fake game data. No longer a simple cheat at the memory level, the implications for the game are immense. I don't think absolute security exists, but godot packaged programs should not be made so vulnerable.
The long term result: people who develop games for the hobby may choose to give up because their copyrights are constantly being violated. As for developers who make money for the purpose of making money, or corporations, they will give up even more. Imagine how horrible it would be if it was the code of a game that you had worked so hard to develop, and then the next day it could be decompiled into a project file.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Strictly encrypt all gdscript or cs project files.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You can add strong obfuscation, or make stronger encryption of the code file such as AES encryption of the whole part. At the very least, you need to make sure that crackers can't get to the complete project code.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can choose whether to encrypt or not when exporting

### Is there a reason why this should be core and not an add-on in the asset library?

Copyright should be protected

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/4220
