### ISSUE TITLE
Add a _late_physics_process function.

### ISSUE THREAD

**Issue by PXLRank** [godotengine/godot-proposals#10815]
### Describe the project you are working on

I am currently working on a physics-based movement fps.

### Describe the problem or limitation you are having in your project

The limitations of CharacterBody are really apparent when wanting it to interact with RigidBodies correctly and making RigidBody based character controllers will require you to make every feature from scratch. And since the RigidBody is updated by the physics engine instead of something like move_and_slide, it comes with the risk of trusting the physics engine which isn't 100% deterministic.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since _physics_process runs before the actual physics step (from my understanding), adding a _late_physics_process, which would run after all of the physics calculations will allow for a RigidBody to be simulated as the player, if it doesn't interact with anything we can just move_and_slide with no trouble, if it does, we then can use the collision data from the RigidBody and apply it to the CharacterBody and make it looks as if it was the one to interact with the object.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Let's say we have a box in the position of (0,0), moving on the X axis with a velocity of 10 and a physics FPS of 10 as well, meaning the box is moving 1 meter per tick, I imagine the print results would look like this:
`
func _physics_process(): print(position)
`
would return (0,0) on the first tick, (1,0) on the second tick, (2,0) on the third tick, ect.
`
func _late_physics_process():
print(position)
`
would return (1,0) on the first tick, (2,0) on the second tick, (3,0) on the third tick, ect.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

From my research, there isn't a work around or at least a very known one which can be passed around easily.

### Is there a reason why this should be core and not an add-on in the asset library?

This function would allow for easier and better interactions with the physics engine, since there are quite a few cases where the information before and after physics interactions is needed on the same frame.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6795.
