### ISSUE TITLE
Enhanced Utilities for in-game settings / Expose Project Settings Component as Control Node

### ISSUE THREAD

**Issue by betalars** [godotengine/godot-proposals#10816]
### Describe the project you are working on

Frame of Mind, a game that has nice visuals but is also supposed to work on a steam-deck and therefore needs configurable rendering settings.
It also has a lot of accessibility settings that need to be processed somehow and just being able to add them as project settings and not have to create a whole UI for it would be very nice.

### Describe the problem or limitation you are having in your project

There is no utility for creating game settings that I know of. The only thing possible right now is create a complicated UI that hard codes each and every setting and connects to the engine methods, that need to be set to change a setting while the game is running or create a separate launcher that creates a project settings overlay, but even then you need to hard code each setting.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are several things that need to change imho.
 - allow settings to have callables that get emitted when project settings so updates can apply immediately when it is possible at runtime -> this would probably need a bit of tinkering. maybe this will only be possible for autoloads.
 - add a `ProjectSettings.get_property_info(name)` method at least
 - expose more of the `@export` input fields available in editor as control nodes in game
     - maybe even have a generalized ResourceEdit component
 - add a component that automatically generates a settings menu based on a list of project setting paths provided

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. Developer adds a user settings control element
2. Developer specifies what settings should be configurable
3. Godot generates a settings view based on the configured settings
4. Game is being exported
5. User launches the Game and changes a setting
6. if a callable is included in the setting, it is being called to cause the setting to apply immediately
7. user configuration is saved to an project settings overlay

optionally:
it would be neat, if hardware-agnostic settings would be stored in a different loation than user-specific setting, for when players want to play the same game on different devices and keep gameplay settings same but video settings differently.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As described, this is highly complex to code around.

### Is there a reason why this should be core and not an add-on in the asset library?

The tooling for creating the settings window already exists in the editor, but it simply cannot be exposed in game yet. Of course it is possible to create a parody of the settings panel trough an AddOn, but I feel like this would overall be wasting time.

**Comment by RedMser** [comment]
For exposing the editors used by the inspector, see #8908 
For exposing the entire inspector, see #7010

You can already get property info by calling `ProjectSettings.get_property_list()` and finding the property with the given `name`. It should work for custom settings as well.

> complicated UI that hard codes each and every setting 

Nothing stops you from looping over the properties yourself and using their data type to spawn UI elements. The main issue is that changing a ProjectSetting rarely affects the running game, means you have to restart to apply it. But this is a more fundamental problem in the engine, and not one that would be solved by adding a new UI control.

I personally don't think *games* should use the editor's UI, for many reasons. E.g. how should the engine decide which editor to use for a given property? Do you want to toggle a boolean using a checkbox, a toggle switch, a dropdown, a [carousel](https://github.com/godotengine/godot/pull/93041), radio buttons, or multiple toggle buttons in one group? There's so many options and different demands for layout, it seems difficult to realize in a generic way. In an editor plugin, it makes sense to have a consistent and uniform look, but games aren't applications and need to maintain a consistent style.

Or do you mean something like Unity's "launcher" window, where you can configure some settings before entering the game?

**Comment by Calinou** [comment]
There are already several add-ons out there that assist with creating settings menus. For instance: https://github.com/Maaack/Godot-Options-Menus

While there are engines that provide default settings menus for projects to use, it's very hard to provide good usability out of the box while still allowing developers to add their own personal touch to it.

**Comment by betalars** [comment]
@Calinou wrote
> There are already several add-ons out there

I have looked at many existing AddOns and never been quite happy with them.

Although I must admit there are severe limitations to this idea, as you often do want to expose settings that change multiple things at once ...

**Comment by betalars** [comment]
@RedMser wrote:
> I personally don't think _games_ should use the editor's UI, for many reasons. E.g. how should the engine decide which editor to use for a given property? Do you want to toggle a boolean using a checkbox, a toggle switch, a dropdown, a [carousel](https://github.com/godotengine/godot/pull/93041), radio buttons, or multiple toggle buttons in one group?

First and foremos: I have provided an intended user story alongside my proposal. I thought it was clear how I would like to see it implemented in general.

![image](https://github.com/user-attachments/assets/a29368a7-4515-44d5-a5ca-5c38bbf3587a)

And I agree with you: I don't think these are the prettiest interfaces to ever exist. But I think they are good enough for a lot of use cases and I much prefer being able to use that if I want over having to always code UI property setters from scratch.

**Comment by tetrapod00** [comment]
I don't think it's possible for Godot to support a *good* implementation of ingame settings, because the needs of desktop, mobile, and various console-like interfaces are so different, and the interface to change settings ingame is different than the interface for the project settings. To use the example you posted - an ingame settings menu should not be setting resolution by independently changing the width and height of the window in an input field. Or consider the case of anitaliasing options - not every game can support each antialiasing setting that the engine does. You can't simply expose the project settings as-is.

In this case, providing a partial solution is worse than no solution at all.

**Comment by betalars** [comment]
Closing this as I have to agree the current proposal actually is an over-simplification and while implementing the menu trough hard coding myself right now I realized more shortcomings of this idea.

I am still convinced there is an idea about helping people out and I also think it should probably be core, but this is not it.
