### ISSUE TITLE
Remove the ToolButton node in favor of plain Buttons

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1081]
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
It's useless if the only difference between Button and ToolButton is that it is flat, you can change this in the inspector. _Why don't exist 1000 Nodes for every Node with one property changed?_
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There would be a node less and the Node choosing window would look a tiny little bit clearer.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Godot node selection with ToolButton deleted](https://user-images.githubusercontent.com/60623532/85058216-10080200-b1a2-11ea-9891-6a3a33be5bac.png)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, you can't edit delete Nodes from the Enginge xD
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, it's done very quickly.

**Comment by Calinou** [comment]
I planned to do this as part of my editor theme redesign, but it makes sense to do it in a separate PR. We'll need to handle existing projects so they're converted into plain Buttons with the Flat property enabled.
