### ISSUE TITLE
Add `get_node()` function to Resource

### ISSUE THREAD

**Issue by PixelTim** [godotengine/godot-proposals#10814]
### Describe the project you are working on

Any project that uses custom resources

### Describe the problem or limitation you are having in your project

Resources have no way to access any node

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding `get_node()` (and maybe `get_parent()`) function for Resources will make accessing nodes from resource possible

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
extends Resource
class_name MyCustomResource
func _init():
	print(get_parent()) #returns node that contains this resource (if such node is present in the tree)
	print(get_node("..")==get_parent()) #returns true
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

`(Engine.get_main_loop() as SceneTree).current_scene` makes possible to navigate through the scene tree, but there's no short way to get a node that contains the resource.

### Is there a reason why this should be core and not an add-on in the asset library?

It's core (because the Resource code needs to be changed)

**Comment by PixelTim** [comment]
> A resource is usually global, and shared between multiple Nodes. They can also be stored elsewhere, not necessarily on a Node. So this API does not make much sense.

But when the resource have a NodePath variable with, for example, a Timer assigned to it and you need to connect timeout signal from timer to a function, it would be possible only if `get_node()` function was present (`get_node(timer).timeout.connect(Callable(self, &"my_function"))`)

**Comment by AThousandShips** [comment]
> But when the resource have a NodePath variable with, for example, a Timer assigned to it and you need to connect timeout signal from timer to a function

That wouldn't be appropriate code, it's not how resources are intended to work (you can't export a `Node` from a `Resource` for this reason)

**Comment by PixelTim** [comment]
> That wouldn't be appropriate code, it's not how resources are intended to work (you can't export a `Node` from a `Resource` for this reason)

But why resources are not intended to work with nodes? What is the sense of removing ability to export a Node?

**Comment by AThousandShips** [comment]
How would you know where in the scene tree a resource is? It isn't a node, so it can't have a path, it can be used in multiple nodes, or none

**Comment by sockeye-d** [comment]
Also, since Resources are serialized to disk it would be hard to maintain that reference when they are deserialized

**Comment by PixelTim** [comment]
> How would you know where in the scene tree a resource is? It isn't a node, so it can't have a path, it can be used in multiple nodes, or none

If Resource is assigned to __only one__ node in the scene tree, it will return node that contains this resource
If Resource is not assigned to any node in the scene tree, then it's code won't be executed, so this won't happen.
I don't know what will happen if the same Resource is assigned to many nodes (Array[Node] or error maybe?), but I think that  Resources in their current state are too kinda "detached" from nodes, so they need the methods to manage the nodes (`get_node`, `get_parent`, `get_tree()`, etc...)

**Comment by AThousandShips** [comment]
> If Resource is assigned to only one node in the scene tree, it will return node that contains this resource

Why? That's confusing and error prone, also how would you track that?

**Comment by WhalesState** [comment]
There are many other ways and tricks to get a node from any script.

Since you already know you can access the MainLoop globally `Engine.get_main_loop()` so you can easily get it's root `Window` which is the parent of all the nodes inside the `SceneTree`.

`Engine.get_main_loop().root`

From there you can get nodes with unique names `get_node("%MyNode")` or you search for them `find_node("MyNode")`.

Another trick is to use static variables or to assign the owner to the resource if it will only be used once at a time, yet can be dropped and picked by another player or enemy.

```gdscript
class_name Player
extends Node2D

static var singleton: Player
var weapon: Weapon
var speed := 100

func _init():
  singleton = self
  weapon = Sword.new()
  weapon.current_owner = self
```

```gdscript
class_name Sword
extends Weapon

var current_owner: Node:
  set(value):
    current_owner = value
    if current_owner == Player.singleton:
      print("The Player has the sword")
      current_owner.speed -= 15


func _init():
  print(Player.singleton.speed) # Prints 100
  await Engine.get_main_loop().process_frame
  print(Player.singleton.speed) # Prints 85

```

**Comment by WhalesState** [comment]
If you still want to use get_node() or get_parent(), then instead of using `Resource` you can use `Node` since both are just bases and they needs to be extended, then make sure to add the resource that extends from `Node` as a child to the desired owner to be able to use the `Node` functions.

**Comment by PixelTim** [comment]
Closing as not planned. Optimal solution in my case will be using nodes instead of resources

**Comment by peterept** [comment]
it would be nice to use Resource because then you can edit the value in place in the inspector. 
Using Node as the alternative means you need to create a new node and assign it.
