### ISSUE TITLE
Expose PackedArrayRef outside Variant in Core, GDExtension (+godot-cpp)

### ISSUE THREAD

**Issue by Ivorforce** [godotengine/godot-proposals#10830]
### Describe the project you are working on

A godot-cpp GDExtension.

### Describe the problem or limitation you are having in your project

`Packed*arrays` are copy-on-write: When you de-reference one, you effectively (regarding mutability) get a copy. That means, you cannot take in a `Packed*array` through a GDExtension method and modify it... right?

But: `Variants` hold a reference to a `Packed*array`. When you have multiple copies of a Variant referencing the same copy of a `PackedArrayRef` (referencing a `Packed*array`, you can mutate it in-place. This is how GDExtension avoids copy-on-write behavior in GDScript. You can mimic this in a GDExtension by calling variant functions:

```c++
void GDExample::mutate_array(Variant array) {
    array.call("append", Vector2{ 2, 34 });  // Mutates in-place
}
```

`Packed*arrays` are exposed to GDExtensions, but Variants' [PackedArrayRef](https://github.com/godotengine/godot/blob/master/core/variant/variant.h#L213C9-L213C23) are not. That means if you want to mutate a Packed* array in-place, you have to go through the stringy API.

The following does not work:

```c++
void GDExample::mutate_array(PackedInt32Array& array) {
    array.append(Vector2 { 2, 34 });  // Mutates a copy
}
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice to have access to `PackedArrayRef` directly. This way, one could take in a `Packed*Array` through a GDExtension's method parameters and modify it in-place, without going through the string-y `call` API.

Additionally, C++ only functions could be used, such as `ref->ptrw()`, to get access to the underlying C pointer and run much faster computation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Going by how C++ templates are unrolled in godot-cpp, it would probably be used like:

```c++
void GDExample::mutate_array(PackedVector2ArrayRef ref) {
    ref->append(Vector2 { 2, 34 });  // Mutates in-place
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As mentioned, the GDScript-like API can be used:

```c++
void GDExample::mutate_array(Variant array) {
    array.call("append", Vector2{ 2, 34 });  // Mutates in-place
}
```

However, this is slow, dynamically typed, and it doesn't work for c-like APIs like `.ptrw()`.

### Is there a reason why this should be core and not an add-on in the asset library?

It's core.

**Comment by AThousandShips** [comment]
This would make the feature only usable for extensions not code that can be both (like modules that can be compiled either as a module or an extension) as there's no such feature available in the engine itself

**Comment by Ivorforce** [comment]
Yeah, I suppose it would have to be added to core too to ensure feature parity.

**Comment by dsnopek** [comment]
Hm. It would be nice if this could be accomplished without adding a new type.

In Godot itself, if you had a function that took `PackedByteArray &` would that still lead to a copy if you modified it? If not, we could try and come up with a way to have the same behavior when passing a `PackedByteArray &` over GDExtension?

It looks like we encode packed arrays as pointers already. So, I think the copying is happening in the GDExtension binding (ie godot-cpp)? If so, we'd just need a way to prevent the copy in certain cases.

**Comment by Ivorforce** [comment]
> In Godot itself, if you had a function that took `PackedByteArray &` would that still lead to a copy if you modified it? If not, we could try and come up with a way to have the same behavior when passing a `PackedByteArray &` over GDExtension?

It currently converts to `PackedByteArray`, which creates a COW copy, so any modifications will modify the copy, see above:

```c++
void GDExample::mutate_array(PackedInt32Array& array) {
    array.append(Vector2 { 2, 34 });  // Mutates a copy
}
```

> Hm. It would be nice if this could be accomplished without adding a new type.

Even if we made the above example work, it would not cover use-cases where the reference should be stored (as `&` references cannot be stored), much like a Variant can be stored and modified in-place elsewhere.

I decided to instead address the underlying cause, which is Variant storing an `std::shared_ptr` like type, whose behavior cannot be recreated without it being exposed.

**Comment by Ivorforce** [comment]
That's for GDExtension, so after a `Variant` has been unpacked and thus copied.

If you have a `Packed`, and pass its `&` reference into a function, you can modify it in-place.

**Comment by dsnopek** [comment]
Ok, so if that works from within Godot, then I think we could maybe find a way for that work from GDExtension too. Like I [wrote above](https://github.com/godotengine/godot-proposals/issues/10830#issuecomment-2426822420), we're already encoding the packed arrays as pointers when passing them to GDExtension, and I think the actual copying is triggered from the language binding (not Godot itself), so we'd need to find a way to have the binding not copy in some cases.

**Comment by Ivorforce** [comment]
I'm not sure if I'm understanding your suggestion.

Godot still has the same limitation as GDExtension that, when given a `Variant`, it cannot modify the underlying `Packed` in-place without going through the stringy interface. Conversion of `Variant` to `Packed` always causes a copy to be made.

I was under the impression that any `GDScript` calls to a `GDExtension` are passing the values as Variant, which are unpacked for the C++ call. If that is the case, the PR is needed as provided to avoid a COW copy.

**Comment by dsnopek** [comment]
> Godot still has the same limitation as GDExtension that, when given a `Variant`, it cannot modify the underlying `Packed` in-place without going through the stringy interface. Conversion of `Variant` to `Packed` always causes a copy to be made.

Perhaps a method could be added to `Variant` to extract a reference to a packed array, rather than making a copy?

> I was under the impression that any `GDScript` calls to a `GDExtension` are passing the values as Variant, which are unpacked for the C++ call.

No, if GDScript makes a ptrcall (or really a validate call converted to a ptrcall) then the value will be passed as pointer, rather than being converted to a `Variant`. It'll only be converted to a `Variant` if GDScript does a normal call.

**Comment by Ivorforce** [comment]
> No, if GDScript makes a ptrcall (or really a validate call converted to a ptrcall) then the value will be passed as pointer, rather than being converted to a Variant. It'll only be converted to a Variant if GDScript does a normal call.

Ok, that's good to know. 

> Perhaps a method could be added to Variant to extract a reference to a packed array, rather than making a copy?

In this case this is a real alternative. Implementing your suggestion sounds good to me since it would require only modification of the bindings, and lead to behavior more consistent with user's expectations.

I would still argue that this proposal and the PR are worthwhile, even with the above suggestion implemented, because it will add the ability to store a strongly typed reference to a shared `Packed`, eliminating the need for `Variant` in these cases. But it would be much less important since a few use-cases would already be covered with the `&` return.

**Comment by Ivorforce** [comment]
FYI, I have two PRs open for this proposal now:

- https://github.com/godotengine/godot/pull/98392
    - Allows Variant owners to convert it to a typed unowned pointer, allowing for in-place modification and non-copy use.
- https://github.com/godotengine/godot/pull/98373
    - Implements `PackedArrayRef` classes that allow typed use of a shared `Packed` as if holding a Variant.

Both support orthogonal use-cases and thus don't compete with each other in terms of which should be merged.

**Comment by Ivorforce** [comment]
With godotengine/godot#99201 merged, i no longer have a personal use-case for this feature. If another use-case emerges, please comment on this proposal, or open a new one linking to this one.
I'll note that godotengine/godot#98373 should be functional and can be salvaged in this case.
