### ISSUE TITLE
Let Container grow if region rect width and height of sprite child changed

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1083]
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
I must set the position of a Container myself when the region rect width of a child (type Sprite) is enlarged, that the Container stays in the Top Center of the screen.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would grow automatically. If Grow Direction set to Both, I'd have to do less.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes, but I hope anyway it'll be accepted.
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, useful for many people

**Comment by groud** [comment]
Note that containers are not meant to work with sprites. I'd advise you to use a TextureRect instead.

**Comment by MaaaxiKing** [comment]
But in my Container, there's also a Button. Should I then do it like this:

- Container
	- TextureRect
		- Sprite
	- Button

?

**Comment by groud** [comment]
I meant replacing the Sprite by a TextureRect, not adding a TextureRect in the hierachy.
They are similar in features but TextureRect extends Control, which make it work correctly with containers.

**Comment by MaaaxiKing** [comment]
Doesn't work, I don't know what I'm doing wrong.

**Comment by groud** [comment]
Set the minimum size instead, not the size.

**Comment by MaaaxiKing** [comment]
Thanks, this worked but why didn't it work with just `size`?

**Comment by groud** [comment]
Alright I'll close this as solved then.

The size property of a child of a Container is computed by the container itself, so it basically gets overridden. Most of the cases the minimum size of a Control is computed automatically but if you want to increase it, you can use this minimum size instead.
