### ISSUE TITLE
Make it possible for Light2D light to penetrate into obstacles until hitting a backface or distance limit.

### ISSUE THREAD

**Issue by Asmageddon** [godotengine/godot-proposals#1088]
As per this old issue: https://github.com/godotengine/godot/issues/10092

Two images from a personal non-Godot project to illustrate what I mean:

![](http://i.imgur.com/0xI8T2D.png)

![](http://i.imgur.com/rKiJ3EJ.png)

I believe that this feature would enable quite a lot of new graphical styles, by being able to see the occluding objects instead of not being able to.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
