### ISSUE TITLE
Add crash pop-up on exported projects when the engine detects an error.

### ISSUE THREAD

**Issue by Awfyboy** [godotengine/godot-proposals#10899]
### Describe the project you are working on

This proposal will be useful for any type of project.

### Describe the problem or limitation you are having in your project

When developing your game, there is a high change that you are going to miss some sort of bug or some kind of error when the game is exported. Some of these errors can cause the game to freeze which can leave players puzzled as to why the game gets soft-locked.

Correct me if I am wrong, but Godot does not seem to push a crash pop-up when there is a bug on exported games. The error log goes into the user’s AppData > Roaming, which isn’t very user friendly. When my exported game crashes, the game simply freezes.  When this happens, users will only see a freeze and will not know whether there is an error with the game or with their computer. It also just makes it harder to fix errors since the reports of those errors would be low. Additionally, when an exported game crashes, the window will get 'stuck' making it hard to close the game window without using Task Manager (which isn't something that most players would know about).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose that exported projects should, at the very least, throw an error onto the screen. It saves so much hassle for the developer and the user and makes it easy to navigate the error and fix it. The user can simply copy-paste this error and report to the developer and the developer can simply navigate to the error and fix it. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I really like GameMaker's error message, so here is an example of what GameMaker has done:

![image](https://github.com/user-attachments/assets/a37d2c53-6f65-4e7b-9aca-b90cb34a6ae9)

If we translate this to Godot, the error message could show you:

- the script of which the error(s) took place
- the scene that has the attached script
- the root node of which the scene is currently a child of
- the line at which the error(s) have occurred
- the scope at which the error occurred (global or under a function)
- the scene ID (useful multiple instances of the scene exists under the root node)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This enhancement will be extremely beneficial that I see no reason why it wouldn't be used by every developer. I couldn't really find a way to replicate an error message myself. The only other thing I can think of is the "Export on Debug" option when exporting the game, but I would still prefer a proper crash pop-up, especially considering most developers tick of that option and it is mainly used for debugging purposes by developers, not for final builds.

### Is there a reason why this should be core and not an add-on in the asset library?

This would save so much time for both the developer and the player. The player can easily report bugs by copy and pasting the code instead of having to navigate to AppData > Roaming to get the error, or having to figure out why the game froze in the first place.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/7917

Please add any details you are missing there, thank you
