### ISSUE TITLE
Publish Godot source generators as library (.NET/C#)

### ISSUE THREAD

**Issue by benjiwolff** [godotengine/godot-proposals#10913]
### Describe the project you are working on

I am working on an FPS prototype.

### Describe the problem or limitation you are having in your project

I am building some basic parametric editor tools to prototype my environment. Whenever an exported property on a tool is edited, I want the output to be recomputed. This results in very repetitive code for each property:
```
private int npeaks;
[Export] private int nPeaks
{
    get => npeaks;
    set
    {
        npeaks = value;
        React();
    }
}
```
where the React method reapplies the parameters i.e. recreates the CSGShape. This boilerplate code can be longer and more complex when the property is a resource.

I would like to be able to write a source generator MySourceGenerator that generates the code above from just one line.
```
[ExportReactive] private int npeaks;
```

However, due to the way source generators work in .NET (see dotnet/roslyn#57239 or the image below), the generated ExportAttribute would not be expanded by Godot.SourceGenerators, resulting in it not being accessible in the editor.
![image](https://github.com/user-attachments/assets/60c5dbad-bc9f-46b0-8856-3aaa3a4c164d)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As far as I know, Godot.SourceGenerators itself cannot be referenced in a project without running the generators as is.

I propose, that the Godot source generators are published as a library (e.g. Godot.SourceGenerators.Implementation) that can be use inside other generators. This would allow MySourceGenerator to apply the Godot source generators to a revised compilation that includes the generated ExportAttributes.
![image](https://github.com/user-attachments/assets/26dd2949-9648-4e7b-a579-df60a222a35b)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

To familiarize myself with the issue, I have already created a working draft implementation:
* godotengine/godot#97881
* [Example project using Godot.SourceGenerators.Implementation](https://github.com/benjiwolff/godot-source-generation-chain-example)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No workaround necessary. The new library can be ignored.

### Is there a reason why this should be core and not an add-on in the asset library?

Godot.SourceGenerators is part of core Godot repository.

**Comment by benjiwolff** [comment]
@pineapplemachine thanks, that was an accident. It's public now.

**Comment by raulsntos** [comment]
As mention in https://github.com/godotengine/godot/pull/97881#issuecomment-2414633232, we don't think this is the proper way to fix the issue mentioned in this proposal. Since, the issue mentioned here is similar to other existing proposals/issues, we're closing this proposal to consolidate:

- https://github.com/dotnet/roslyn/issues/57239
- https://github.com/godotengine/godot-proposals/issues/9140
- https://github.com/godotengine/godot/issues/66597
- https://github.com/godotengine/godot/issues/67624

Thanks for the contribution nonetheless.

**Comment by pineapplemachine** [comment]
Since this change was rejected (I suppose understandably), has anyone figured out any sane workflows around generating C# boilerplate code such as the reactivity example in the original issue?

**Comment by MihaMarkic** [comment]
@pineapplemachine 
Here is something you could try:
Declare property as:
```csharp
[Export, ExportReactive] public partial int Npeaks { get; set; }
```

Then implement property with your source generator and Godot source generator will create required boilerplate to be visible to editor.
Here is how [I'm doing it](https://codeberg.org/mihamarkic/godot-property-changed-source-generator).
The only problem I'm seeing with this approach is the invisibility of default value to godot's source generator (my [proposal to solve it](https://github.com/godotengine/godot-proposals/issues/14177)).
