### ISSUE TITLE
Add option to highlight current hovered line

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1091]
**Describe the project you are working on:**
3.2.1.stable.official
**Describe the problem or limitation you are having in your project:**
I wanted to click next to the line number to set a breakpoint and I wasn't sure in which line I had to place it because the lines look similar to each other.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I noticed for this it would be useful if you can enable that the current hovered line is highlighted. If you enabled Highlight Current Line in Editor --> Editor Settings --> General --> Text Editor --> Highlighting , it should maybe highlight the hovered line in a different color, or maybe just weaker.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Godot current hovered line highlighted](https://user-images.githubusercontent.com/60623532/85197956-e4416500-b2e4-11ea-9f29-718cbe42c598.png)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, it's not very complicated to implement.

**Comment by Calinou** [comment]
#533 and #873 should address the need described in this proposal. I'm not aware of any other text editor providing a feature that changes the line background when hovering a line (it's probably too distracting).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/533 and https://github.com/godotengine/godot-proposals/issues/873 
as this proposal hasn't received much support over time.
