### ISSUE TITLE
Add `fallback_main_loop_type` in addition to the existing `main_loop_type`

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot-proposals#10931]
### Describe the project you are working on

3D platformer, but the project type doesn't matter

### Describe the problem or limitation you are having in your project

The game can't run if the GDExtension containing my mainloop (which extends SceneTree) fails to load.
This is alright, but I'd like to have a special error screen scene displayed that explains that there is problems with the GDExtension not loading to the user instead of the game not starting.
For this, it would just use SceneTree as a fallback mainloop instead of my custom SceneTree extension.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allows my to display my special error scene

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

New project setting application/run/fallback_main_loop_type that tries to load that given MainLoop class string if application/run/main_loop_type isn't found

### If this enhancement will not be used often, can it be worked around with a few lines of script?

can't, mainloop is core

### Is there a reason why this should be core and not an add-on in the asset library?

mainloop is core

**Comment by Calinou** [comment]
Shouldn't the engine itself display an error dialog visible to the user when the main loop can't be loaded?

**Comment by FireCatMagic** [comment]
> Shouldn't the engine itself display an error dialog visible to the user when the main loop can't be loaded? `OS.alert()` or a custom AcceptDialog can be used for this.

It does display an error dialog, but what I mean is I have a custom error scene I'd like to display if the GDExtension with my MainLoop can't be loaded. My MainLoop extends SceneTree, so if it fell back to default SceneTree it'd work fine and display the scene as it should
