### ISSUE TITLE
IDE should catch when you attempt to use nonexistent key/property names

### ISSUE THREAD

**Issue by VRNocturne** [godotengine/godot-proposals#10939]
### Describe the project you are working on

Developing game in which I was using labels to display text and making said labels visible or not based on what's happening. I made a typo on the property name, which was discovered only via an unexpected runtime error during testing.

### Describe the problem or limitation you are having in your project

For the longest, I was not aware I had made a typo in a property name. I had:

SomeLabel.vislble = "some text"

And never noticed it until now when I ran the project and that code branch was reached. Then, I got a runtime error saying that "vislble" was an invalid property.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would have been nice if the editor would have highlighted that an said something like `"vislble" is not a defined property on type Label` or something to that effect. I could have changed it immediately instead of potentially a bug going unnoticed until much later (and potentially more buried in the code).

It does this for variables that aren't defined. This would be a natural extension of that.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When a non-existent property is being referenced, the editor will highlight it with an error stating that the property does not exist for that object type. 

The following line was in the code, for example:

`%Label.vislble = "Game Over!"`

The editor would catch that "vislble" doesn't exist for Label objects and throw an error message: `"vislble" is not a defined property on type Label`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I'm aware of unless a script can alter what errors the IDE will alert the developer to.

### Is there a reason why this should be core and not an add-on in the asset library?

Not that I'm aware of unless asset packs/mods can alter what errors the IDE will alert the developer to.

**Comment by sockeye-d** [comment]
Since any `Object`-derived classes can implement the `_set` and `_get` functions, Godot actually has no way of knowing what properties will exist at runtime, thus making this impossible to determine 100% of the time. You can set `debug/gdscript/warnings/unsafe_property_access` to `warn` or `error` in the project settings if you want to only be able to access variables defined by core classes or those declared with `var`

**Comment by VRNocturne** [comment]
Gotcha. I'll set it to warn then to let me know. Then I'll at least look at it to make sure is okay in case I want to do something like that in the future.

Thanks for the heads up. I'll close this then since it won't be reliable.
