### ISSUE TITLE
Enhance AnimatedSprite2D with Frame-Specific Offset Support for Complex 2D Sprite Animations!!!

### ISSUE THREAD

**Issue by mqllin** [godotengine/godot-proposals#10937]
### Describe the project you are working on

2D turn-based MMORPG online game

### Describe the problem or limitation you are having in your project

I am currently working on a project using Godot's AnimatedSprite2D to recreate classic retro games. The game assets I am using are pre-existing and include complex 2D animations that feature multi-layered sprites with varying sizes, directional frames (8 directions), and multiple actions. Each frame of these animations also has specific XY offset information to ensure proper alignment of the layered sprites.

Unfortunately, I have encountered a significant challenge while trying to implement these assets into AnimatedSprite2D. The current system doesn't seem to support frame-specific offsets, which makes it difficult to correctly align and composite the animation frames. This is especially problematic because the add_frame method does not allow for specifying custom alignment or offsets for each frame. As a result, all frames appear to be centered both horizontally and vertically by default, which distorts the animation and makes it impossible to use my assets properly.

Adding XY offset functionality to each individual frame in AnimatedSprite2D would resolve this issue and allow for greater flexibility when working with complex, pre-existing game assets. I believe this enhancement is essential for anyone looking to use AnimatedSprite2D with assets that aren't perfectly uniform in size and position.

I hope to see frame-specific XY offset support added soon so that I can continue my project without having to resort to workarounds or creating custom tools for what should be a fundamental feature of sprite animation.

Thank you for considering this proposal!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This enhancement proposes adding the ability to define and apply per-frame XY offsets in AnimatedSprite2D. Currently, when adding frames via AddFrame, all frames are centered by default, which makes it difficult to properly align and composite animations that use frames of varying sizes, positions, and offsets. By allowing each frame to have custom XY offsets, developers will be able to handle more complex 2D animations, such as those with multi-layered sprites, directional frames, and varying frame sizes, without the need for external workarounds or manual adjustments. This will significantly improve AnimatedSprite2D’s flexibility and usability when working with pre-existing, non-uniform sprite assets, helping developers avoid common alignment issues.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```cs
using Godot;
using System.Collections.Generic;

public partial class ComplexSpriteExample : Node2D
{
    private AnimatedSprite2D animatedSprite;

    // Example of how each frame has different offset information
    // These offsets would need to be applied to each frame manually, but AnimatedSprite2D doesn't support this
    private List<Vector2> frameOffsets = new List<Vector2>()
    {
        new Vector2(0, 0),     // No offset for first frame
        new Vector2(5, -10),   // Second frame requires offset
        new Vector2(-7, 3),    // Third frame requires offset
        new Vector2(4, 2),     // Fourth frame requires offset
        // Add more as needed
    };

    public override void _Ready()
    {
        // Create AnimatedSprite2D instance
        animatedSprite = new AnimatedSprite2D();
        AddChild(animatedSprite);

        // Load the sprite frames (assume you have a SpriteFrames resource with pre-existing animations)
        var spriteFrames = new SpriteFrames();
        animatedSprite.SpriteFrames = spriteFrames;

        // Manually add frames with offsets (for illustration purposes)
        for (int i = 0; i < frameOffsets.Count; i++)
        {
            // Load the texture for each frame (this would typically come from your actual animation assets)
            Texture2D texture = GD.Load<Texture2D>($"res://path_to_texture/frame_{i + 1}.png");

            // The current AnimatedSprite2D only allows adding frames without offset control
            spriteFrames.AddFrame("default", texture);

            // This is where I would want to set the specific offset for each frame,
            // but AnimatedSprite2D does not support per-frame offsets
            // So all frames are centered by default, causing misalignment issues
            GD.Print($"Frame {i + 1} added without the ability to apply offset: {frameOffsets[i]}");
        }

        // Play the default animation
        animatedSprite.Animation = "default";
        animatedSprite.Play();
    }
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, because you never know what the size of the largest tile is. Unless you manually count them one by one, which is stupid.

### Is there a reason why this should be core and not an add-on in the asset library?

Make the AnimatedSprite2D fully morphed

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2060.
