### ISSUE TITLE
Add autoplay property to `GPUParticles`

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-proposals#10936]
### Describe the project you are working on

Topdown Shooter (3D) with usage of particles for weapon effects and item effects, which are one-shot.

### Describe the problem or limitation you are having in your project

`GPUParticles` have a problem with the one-shot property. Ignoring `is_emitting` being [falsely toggled and its state being changed by the game itself](https://github.com/godotengine/godot/issues/97974)

This proposal is about if the property `autoplay` is enabled, automatically enable `is_emitting` on `_ready()`.
Other nodes have this `autoplay` property like `AnimationPlayer`, `AudioStreamPlayer`, `VideoStreamPlayer` and ofc `AnimatedSprite`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In `GPUParticles` node, under the `Time` category, add a new boolean `autoplay`. If true, it automatically toggles `is_emitting` to true on `_ready`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, by attaching a custom script attached to all `GPUParticles3D` which you want to automatically start, which basically does
```gdscript
extends GPUParticle3D

func _ready():
   emitting = true
```

but its a chore to do this for every particle.

### Is there a reason why this should be core and not an add-on in the asset library?

This is QoL for `GPUParticles`

**Comment by KoBeWi** [comment]
Thank you for your proposal, consolidating in https://github.com/godotengine/godot-proposals/issues/8590
