### ISSUE TITLE
Compiling engine stripping nodes and gdscript?

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#10952]
### Describe the project you are working on

A minecraft clone

### Describe the problem or limitation you are having in your project

I was wondering if it's possible to compile the godot engine so that it doesn't have the node/scene system or gdscript
I was planning on using the servers and C# and arch.ecs

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would make the engine lighter, smaller and would force devs working with me to use the ecs engine and C#

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

some sort of compile flags.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not often, and no

### Is there a reason why this should be core and not an add-on in the asset library?

It would be a compile option.

**Comment by Meorge** [comment]
Isn't the node/scene system kind of at the core of Godot itself? It sounds to me like you might be better off rolling your own solution using pure C#

**Comment by Shadowblitz16** [comment]
Maybe your right

**Comment by Zireael07** [comment]
@Shadowblitz16 I am aware of at least one ECS Godot fork. I think one was made by AndreaCatania

**Comment by Shadowblitz16** [comment]
> @Shadowblitz16 I am aware of at least one ECS Godot fork. I think one was made by AndreaCatania

Yep Godex but it's still unfinished and by the looks of it it doesn't strip the node system out and reply in with ecs, it just adds ecs
