### ISSUE TITLE
Add "Fit Content Width" option to TextEdit

### ISSUE THREAD

**Issue by ch0m5** [godotengine/godot-proposals#10957]
### Describe the project you are working on

A tool to build DialogueTrees within Godot for a CRPG.

### Describe the problem or limitation you are having in your project

`TextEdit` is currently unable to automatically resize to fit its contents _horizontally_. This function is present for its height through the `Fit Content Height (scroll_fit_content_height)` property, but such a property, or option in general, does not exist for its _width_ counterpart.

This forces custom code for what is seemingly a pretty plain functionality: resize the container to fit its contents.
![image](https://github.com/user-attachments/assets/e67fe64f-1861-4c6d-ab7c-a0e8fe62dfb9)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I see two possible methods to fix this, in order of elegance imo:

A. Add a `Fit Content Width` property, which resizes the TextEdit to fit the width of its longest line, therefore also eliminating the horizontal scroll bar.

B. Add a `Off` option to the `Autowrap Mode` property so that all text in a line is presented in a line in the UI also, increasing the width of the container as needed. This is how `RichTextLabel` does it (`Fit Content`: ON + `Autowrap Mode`: OFF).
![image](https://github.com/user-attachments/assets/5172310c-7baa-4332-9b20-61363d4b9c0c)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It's either an extra property on the TextEdit or expanding its `Autowrap Mode` property to allow for no wrapping at all. Not much to explain.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm currently using this method, which isn't perfect, but simulates pretty accurately how I want/expect the text to behave to "Fit Content Width".

	func _resize_text_edit_to_width() -> void:
		var font: Font = get_theme_default_font()
	
		var lines: PackedStringArray = []
		if text_edit.text.is_empty():
			lines = text_edit.placeholder_text.split("\n")
		else:
			for line_idx: int in text_edit.get_line_count():
				lines.push_back(text_edit.get_line(line_idx))
	
		var max_width: int = 0
		for line: String in lines:
			var str_size: int = font.get_string_size(line).x
			if str_size > max_width:
				max_width = str_size
	
		text_edit.custom_minimum_size.x = max_width + _font_size_margin

The result behavior is this:

https://github.com/user-attachments/assets/30d95d9a-3993-4d02-96f9-5a646a1175af

### Is there a reason why this should be core and not an add-on in the asset library?

`TextEdit` is a core Control Node and `Fit Content Height` one of its properties. Adding a `Fit Content Width` equivalent seems a pretty useful and intuitive tool to have.

**Comment by kitbdev** [comment]
- added in https://github.com/godotengine/godot/pull/83070

**Comment by Calinou** [comment]
This was implemented in https://github.com/godotengine/godot/pull/83070 (which was merged before this proposal was opened),  closing.
