### ISSUE TITLE
Support for non-textured TouchScreenButton, or add multi-touch support to BaseButton

### ISSUE THREAD

**Issue by BaconEggsRL** [godotengine/godot-proposals#10958]
### Describe the project you are working on

2D pong clone with mobile/web support

### Describe the problem or limitation you are having in your project

The advantage of the Button (or BaseButton) node is that it inherits from Control, so it can be easily placed within the UI.
However, the Button node does not support multi-touch (ie, can't press two buttons at the same time.) I believe this is because the button uses mouse emulation to detect touch in touchscreen devices (and since mouse emulation does not support multiple input at the same time, it does not register second one when first one is already pressed.)

If multi-touch is desired, one must use the TouchScreenButton node.
However this node does not inherit from control, and instead inherits from Node2D.
This makes extra work trying to fit it within the UI. Additionally the user must supply textures for normal and pressed modes, whereas the regular Button node contains textures by default.

For users simply trying to add multi-touch support to regular buttons, it would be convenient if this functionality was somehow included in the default Button node. Alternatively, making it easier to swap from a Button to a TouchScreenButton would be preferred (inherit from Control instead of Node2D, supply a default texture option.)

Thank you for coming to my Ted Talk

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add default textures to TouchScreenButton so that they can be prototyped more easily
Make TouchScreenButton inherit from control node so they can be anchored more easily

Or, allow Button node to have multi-touch support so that regular buttons will work better on mobile, and TouchScreenButton is not required.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure. In my current project I have just decided to layer a TouchScreenButton on top of my regular button. That way I do not need to supply a texture. I tried copying the button normal and pressed textures from the default button theme; however these are StyleBoxTexture and not Texture2D, so I could not get it to work.

The limitation of this is that the button state textures are incorrect. (Pressing 2 buttons simultaneously, only one will appear in the pressed state.) So I just change all the default button textures to normal texture.

If there was an easy way to convert the base button textures to work with the touch screen button that would mostly solve my issue as well.

https://github.com/godotengine/godot-proposals/issues/3562

### Is there a reason why this should be core and not an add-on in the asset library?

This is core functionality

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/3976.

> Add default textures to TouchScreenButton so that they can be prototyped more easily

You can use GradientTexture2D, which has a square area defined by its size (which can be easily adjusted in the resource's properties). The color can be adjusted by modifying the gradient's stops (remove all but one of them for a plain color).
