### ISSUE TITLE
Making godot finally have an offical console port - support for the Playdate console.

### ISSUE THREAD

**Issue by NovaDC** [godotengine/godot-proposals#10971]
### Describe the project you are working on

My compulsions that any tool I use must be compatible with every platform ever.

In all seriousness though, I can find myself in the future working on a minimal 2d (not using 3d or 3d related nodes) game and wish this was a feature.

### Describe the problem or limitation you are having in your project

The problem isn't specifically something I encounter as a issue, I would find a official console port would help ensure that more console-centric features and compatibilities are not over looked in the future. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Supporting something like the Playdate would mean that the answer to "what kind of new and horrible problem could a console port introduce?" can be a much more relaxed and confident "cross that bridge when we get there". Things like support for platform specific graphics backends or input backends will be required, meaning that Godot has to grow in a way that enables support - while still not requiring support - for more platform specific backends - like the Playdate's monochrome display and crank inputs.

Supporting the Playdate specifically also allows for a game developed for the Playdate to be ported directly to both the Playdate and other platforms without having to worry about porting tons of lua or C code, and for less demanding and compatible  games already built in Godot to support a new platform built specifically for that kind of experience.

However, if a new console with an open SDK, support for a relatively modern graphics API, and the ability to compile for it using C/C++ is available, then I can absolutely see a platform like that being used here instead of the Playdate.

Also - most importantly - while there are already people able to port a Godot game to a console - having a openly supported console would enforce some paradigms for other console ports in the future - effectively - set an example for supporting consoles while also setting an example for porting Godot to a much more limited platform.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will require certain features in Godot to be added/changed and tested for. While the console in question doesn't have to be specifically the Playdate, most things listed here remain largely unchanged - except possibly for support for monochrome graphics and support for the crank on the Playdate changed to other platform specific input methods:

- A graphics backend that specifically supports the Playdate:
  - The ability to declare that a graphics backend can only support 2D rendering (perhaps this can also be extended to allows for backends declare that they only have 3D rendering capabilities)
  - Support for monochrome / limited colour range displays
  - Support for monochrome images (if this isn't already supported)
  - Support for converting color images to monochrome using settings specified at export time.
  - Playdate SDK bindings for drawing functions to this graphics backend

- An export template built for the Playdate (this template dosen't need 3D support):
  - Bindings from the Playdate SDK to the Godot engine for input, system status, filesystem related functions, various hardware available features (random number generation, screen brightness, battery level)
  - The ability to embed Godot resources in a the compiled Playdate export template

- Changes for the Input API to account for the crank on the Playdate.

- Optionally, the ability to launch the Playdate emulator and test it directly form a PC editor. The way this happens can be handled similarly to how web testing works: once a runable export for the Pladate is configured for the project a "Launch Playdate Emulator" button will appear beside the run buttons in the editor. This feature can instead be a addon if necessary.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Again, support for a console at all (not even particularly the Playdate, though it seems to be the best candidate so far) isn't something that can just be worked around unless that console is somehow heavily based on a existing platform already supported by Godot (for example - the Ouya or Apple TV would not apply here).

Since there seems to a a almost 40 year historic trend of at the very least Nintendo (and at least a 20 year trend for Xbox and Playstation) of all keeping their development kits closed and protected.

### Is there a reason why this should be core and not an add-on in the asset library?

Support for a console requires multiple changes and features, so this does not specifically apply as of yet, though if certain features specifically for the Playdate aren't supported directly by Godot, but Playdate exporting largely is, then certain gdextentions can be made on the library to supplement the missing features (for example - the Playdate's sleep mode or screen brightness).

**Comment by fire** [comment]
I am not sure if the playdate has opengl support.

The survey here suggests it does not. https://www.peterstefek.me/playdate3d.html

**Comment by Calinou** [comment]
See the note at the top of [Custom platform ports](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_platform_ports.html) in the documentation:

> Godot is a modern engine with modern requirements. Even if you only intend to run simple 2D projects on the target platform, it still requires an amount of memory that makes it unviable to run on most retro consoles. For reference, in Godot 4, an empty project with nothing visible requires about 100 MB of RAM to run on Linux (50 MB in headless mode).
>
> If you want to run Godot on heavily memory-constrained platforms, older Godot versions have lower memory requirements. The porting process is similar, with the exception of [DisplayServer](https://docs.godotengine.org/en/stable/classes/class_displayserver.html#class-displayserver) not being split from the [OS](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os) singleton.

[The Playdate has **16 MB** of RAM](https://help.play.date/hardware/the-specs/) (not 16 GB), making it impossible to run any Godot version on it, even in headless mode. There's also no support for any hardware-accelerated graphics API that Godot uses.

Closing, as this is not technically feasible.

**Comment by NovaDC** [comment]
NGL no idea what I was thinking when I wrote this lol
