### ISSUE TITLE
Truly portable mode (portable.txt, --portable)

### ISSUE THREAD

**Issue by L-the-forgettable** [godotengine/godot-proposals#10996]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

I store my project files on a USB drive so I can easily switch between what device I'm working from. Unfortunately this means I need to re-add all of my projects when I switch devices, re-set my editor settings, and redownload all of my export templates. (And, in the case someone ever needs to borrow another person's computer, files get dropped in their appdata folder.)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Something like a 'portable.txt' file you can drop in the editor's running location, or a --portable flag that persists between the project list, a project and back. When implemented this will help keep everything located where the editor is so as to minimize the need to constantly resetup things when you make a change.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When one of the two listed above are present, the engine will store the project list, and other such files next to the editor's exe file, maybe in a dedicated folder? Anything to do with a specific project (I know games run by the editor/not exported use a special folder inside the main editor folder when referencing user://) can be kept inside the project folder.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

See below

### Is there a reason why this should be core and not an add-on in the asset library?

At the point this would take effect, add-ons (and scripts) aren't loaded yet.

**Comment by bruvzg** [comment]
Portable (or self-contained) mode is already supported. To enable it, create an empty `._sc_` or `_sc_` file in the executable directory.

**Comment by L-the-forgettable** [comment]
That.. I actually had no idea that already existed. Apologies
