### ISSUE TITLE
TileMapLayer: Allow users to provide a replacement tile for broken/missing tiles.

### ISSUE THREAD

**Issue by leecommamichael** [godotengine/godot-proposals#11007]
### Describe the project you are working on

In my last game jam, we had several teammates editing both levels and TileSets simultaneously. We used a shared TileSet resource across many TileMapLayers, which helped have just one definition of what tiles would do. But that also meant changes would apply everywhere.

### Describe the problem or limitation you are having in your project

Iterating on levels built with TileMapLayer can be difficult when the TileSet changes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It'd be nice to be able to "replace tile X with tile Y" generically. Not only to fix missing broken tiles, but to update them as the design process evolves.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Per the docs:
> Tiles are referenced by using three IDs: their source ID, their atlas coordinates ID, and their alternative tile ID.

This means we can provide a UI to "remap" tiles based on pattern matching these IDs.
![image](https://github.com/user-attachments/assets/c7ee196a-f710-43b0-836f-5ee4b37c2e48)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It could be a plugin.

### Is there a reason why this should be core and not an add-on in the asset library?

Every user who collaborates with others will run into the scenario I did.

**Comment by KoBeWi** [comment]
If you select Paint tool and disable Contiguous checkbox, you can replace all instances of a tile in the whole TileMapLayer. It's only for this specific layer though.

**Comment by leecommamichael** [comment]
> If you select Paint tool and disable Contiguous checkbox, you can replace all instances of a tile in the whole TileMapLayer. It's only for this specific layer though.

Thank you so much! I'm a bit surprised that's an option that's nested under the Bucket tool...
