### ISSUE TITLE
Show error message to user if shader compiling fails

### ISSUE THREAD

**Issue by Gromph** [godotengine/godot-proposals#11008]
### Describe the project you are working on

We have ported our older card and board games to run on on Godot 3.5. Now we are upgrading to Godot 4.3. So we have a lot of users on older hardware.

### Describe the problem or limitation you are having in your project

When running the godot 4.3 version on a Windows 10 desktop that has an AMD Athlon II 260 with ATI Radeon 3000 Graphics.  A blank window is momentarily shown, then the game exits with no message shown to user as to why.  There is shader compiler errors in the log file.

The godot 3.5 version ran fine.

The message in log file is:

```
USER ERROR: SceneShaderGLES3: Fragment shader compilation failed:
Fragment shader failed to compile with the following errors:
ERROR: 0:478: error(#185) Array size must be a constant integer expression
ERROR: 0:488: error(#185) Array size must be a constant integer expression
ERROR: error(#273) 2 compilation errors.  No code generated

   at: _display_error_with_code (drivers\gles3\shader_gles3.cpp:254)
USER ERROR: Method/function failed.
   at: ShaderGLES3::_compile_specialization (drivers\gles3\shader_gles3.cpp:396)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When the shader fails to compile the game should show the message box to the user that says:
  Your video card drivers seem not to support the required OpenGL 3.3 version....
  
We edited this message box to instruct the user to go to our website to download an older version of the game. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If shader failed to compile:
   show message box saying to try updating drivers

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, godot exits before any script would have a chance to run

### Is there a reason why this should be core and not an add-on in the asset library?

No, godot exits before any add-on would have a chance to run

**Comment by clayjohn** [comment]
I think this should be a bug report. The fact that the engine reaches a shader to compile means that OpenGL initialized successfully (or ANGLE, I think those devices would fall back to ANGLE). 

My gut feeling is that we are letting some invalid GLSL slip through that we shouldn't and that is causing the error. To figure it out though, we need the full error logs and a copy of the shader that reproduces this error.

**Comment by Gromph** [comment]
Ok reported shader compile error and crash: https://github.com/godotengine/godot/issues/98398

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/98398.
