### ISSUE TITLE
Button node registers press when disabled

### ISSUE THREAD

**Issue by TheSpartanK** [godotengine/godot-proposals#11015]
### Describe the project you are working on

A game with cooldown timed buttons

### Describe the problem or limitation you are having in your project

Button node -> set to disabled
Press the button and hold down the mouse - NOTE: No down signal is sent (as expected), but the button still registered it's been pressed (which it shouldn't)
Keep the disabled button pressed
Wait for timer to enable the button
Release button - button up signal IS sent (even though it wasn't pressed)

Button node -> set to disabled
Hold down the mouse outside the button - NOTE: No down signal is sent (as expected)
Keep the mouse pressed
Wait for timer to enable the button
Move mouse over button
Release button - button up signal is NOT sent (as expected)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the Button node  completely disabled when disabled

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Because it seems like a bug in the core

**Comment by AThousandShips** [comment]
> Because it seems like a bug in the core

This does indeed seem like a bug, please open a [bug report](https://github.com/godotengine/godot/issues) instead

**Comment by AThousandShips** [comment]
Closing in favour of the report (if it isn't a bug this will be reopened)
