### ISSUE TITLE
Add "Always on screen" property to Control nodes

### ISSUE THREAD

**Issue by IoneGod** [godotengine/godot-proposals#1102]
**Describe the project you are working on:**
Mobile Game

**Describe the problem or limitation you are having in your project:**
I am not fully able to get a label node to stay on screen and I am working on a tooltip mechanism  to help players better understand the game
![Tooltip](https://user-images.githubusercontent.com/59492619/85239305-03e2a580-b42b-11ea-9844-207a27af1b09.PNG)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding an always on screen property to enable control nodes ensure that they don't go out of screen even when parent object is moving out of the screen

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
When always on screen is enabled on control nodes it creates like a collision shape that hits the bounding boxes of the screen and smoothly displaces itself from its parents when the parent tends to move it out of screen

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so

**Is there a reason why this should be core and not an add-on in the asset library?:**
Control nodes are core

**Comment by jonbonazza** [comment]
You should be using Anchors for this.

**Comment by iapps207** [comment]
Anchors how?

**Comment by jonbonazza** [comment]
https://docs.godotengine.org/en/stable/tutorials/gui/size_and_anchors.html

**Comment by jonbonazza** [comment]
You should also put the UI on a separate canvas layer and not child it to 2d nodes.

**Comment by Calinou** [comment]
Closing, as this is already feasible using anchors per the above comments. See also https://github.com/godotengine/godot-proposals/issues/1802, but this particular proposal is not necessary to address the problem you're encountering here.
