### ISSUE TITLE
Add (exclude commented) feature to search in code

### ISSUE THREAD

**Issue by MiroloTech** [godotengine/godot-proposals#11037]
### Describe the project you are working on

A Party Racing Game with a large complex custom car implementation

### Describe the problem or limitation you are having in your project

For Example: Finding the one print statement, that is still clogging up my output console is hard to find, when a lot of other print statements are commented out. I have to to look through the entire list of 'print' statements and sort out the real ones from the commeneted-out ones.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an option in the Ctrl+F Search menu in Code to 'exclude commented resulst'
![GodotProposalExcludeCommentFeature](https://github.com/user-attachments/assets/73817d4f-412e-4413-95ac-d4679e59ccbe)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

for each letter, in the search function, keep track, if it is commented, and if it is, just directly skip to the next, without checking simil;arity to the search tag.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I guess, that's note easely work-around-able

### Is there a reason why this should be core and not an add-on in the asset library?

It would just be inconvinient and hard to find a feture like this as an addon, and clog up your addons folder with a lot of editor-exclusive, barely significant addons. It's just to small and fixable for that.

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot-proposals/issues/563

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/563.
