### ISSUE TITLE
Animation panel: extend selection rectangle from the initial corner when mouse scrolling during multi-key drag selection, instead of moving the rectangle origin

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-proposals#11046]
### Describe the project you are working on

A platformer with 2D skeletal animation

### Describe the problem or limitation you are having in your project

I have many skeleton bones to animate and many keys to copy from one time to another, but it's cumbersome to select all the bone keys for a given frame. One intuitive way to select all the keys at a given time is to mouse drag rectangle to multi-select a column of keys. However, there are many keys so they don't all fit in the view and I need to scroll vertically to see them all.

However, when my drag rectangle hits the bottom of the track view, the track view doesn't auto-scroll vertically. In addition, manually scrolling with mouse wheel will _also_ move the selection rectangle origin, preventing user from selecting all keys from the initial click to the release position (it will only select keys that appear inside the rectangle at the final scrolling position).

[Godot 4.3 suggestion - Animation panel - drag rectangle + manual wheel scroll does not preserve selection origin.webm](https://github.com/user-attachments/assets/4dac8963-eee3-4db3-a6c7-02227e4518b6)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Preserve the initial selection rectangle corner, so when user manually scrolls, they extend the selection farther and farther instead of losing the previous selected keys (in other words the rectangle initial corner should move oppositely to scrolling).

**Alternatives**

There are alternative ways to make this work, such as automatically scrolling when drag selection hits the track view edge (I have already suggested this on https://github.com/godotengine/godot-proposals/issues/11045) and, for the specific case of selecting all keys aligned vertically, a special key or button to select all keys at the same time (already proposed on https://github.com/godotengine/godot-proposals/issues/1908).

I also considered Shift+click but I'm not sure what the best implementation is when dealing with 3+ clicks, see discussion: https://github.com/godotengine/godot-proposals/discussions/11047

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example with a file browser:

[Godot 4.3 suggestion - Animation panel - extend selection rectangle from the initial corner when mouse scrolling during multi-key drag selection, instead of moving the rectangle origin.webm](https://github.com/user-attachments/assets/cc4eb7f3-1ac7-4f23-a5db-75d040c0c2bc)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it is native editor behavior

### Is there a reason why this should be core and not an add-on in the asset library?

It is native editor behavior

**Comment by KoBeWi** [comment]
This is already fixed in 4.4.

**Comment by hsandt** [comment]
Fix confirmed in v4.4.dev3.official [f4af8201b] (thinking about it, this should have probably been a bug report, anyway). Closing.
