### ISSUE TITLE
Add new function to Control nodes: force_properties_update

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-proposals#11040]
### Describe the project you are working on

Card game - generating over 1000 cards and saving them as packed scenes, using an excel file.

### Describe the problem or limitation you are having in your project

I want to detect if the name or effect of the card I have - after I set text - overflows its `Label` rect by comparing against  `Label.get_visible_lines_count` and `Label.size.x`. If it overflows, I want to downscale the font size so it fits. And do this in a forloop, so I check for each font size.
```gdscript
for picked_font_size: i in range (max_font_size, min_font_size, -1):
   #if (greater than max size)
```

The problem is that I must await an unknown amount of time for the Control to update its properties. idk why. In the MRP it is merely 1 `await get_tree().process_frame`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By adding a function `force_properties_update` (name is bad, lets discuss its fitting name), so it works exactly like `Raycast3D.force_raycast_update()`

So on adding text on the `Label` for example, or any `Control` auto-resizing its size/rect, you can update it instantly. This allows for linear logic, and no hacks like connecting to `resized` signals by splitting the logic.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I share the code in the MRP first:
```gdscript
func _ready() -> void:
	print("Original height: ", size.y)
	text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor sit amet ligula in malesuada. Phasellus vitae neque id mi tristique mattis. Praesent urna lorem, aliquet in porttitor eu, sollicitudin eu erat. Quisque porta placerat enim, eget consequat eros. Duis vel ipsum nulla. Curabitur sem velit, hendrerit eu mauris vitae, ullamcorper posuere augue. Nunc nec ultricies tellus."
	await get_tree().process_frame # works only for MRP, in my project its a variable amount of frames
	print("New height: ", size.y)
```

With this suggestion's implementation, it would be:
```gdscript
func _ready() -> void:
	print("Original height: ", size.y)
	text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor sit amet ligula in malesuada. Phasellus vitae neque id mi tristique mattis. Praesent urna lorem, aliquet in porttitor eu, sollicitudin eu erat. Quisque porta placerat enim, eget consequat eros. Duis vel ipsum nulla. Curabitur sem velit, hendrerit eu mauris vitae, ullamcorper posuere augue. Nunc nec ultricies tellus."
	force_properties_update()
	print("New height: ", size.y)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

By hooking signals for each updated property. For example, `resized` but [that signal is bugged](https://github.com/godotengine/godot/issues/92849) so the implementation is quite a hack.

In my project's use-case, I had to split the write-to-disk logic in 2 parts, and bloat the code by awaiting for each card's signal long after every other operation is done on the card, then on that signal save to disk (twice because of the above bug)

I dont care much about the aforementioned [double-resized-trigger bug](https://github.com/godotengine/godot/issues/92849), but I do care about the part I must split my code in half even when I do any arbitrary text appending. Or I would have to add a timer which I wish it was just 1 `process` tick like MRP
[mrp.zip](https://github.com/user-attachments/files/17546312/mrp.zip)

### Is there a reason why this should be core and not an add-on in the asset library?

This is an addition of a core node (`Control`)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/20623 (possible duplicate?).

**Comment by TheYellowArchitect** [comment]
From the above issue

>Try using set_anchors_and_offsets_preset(_preset).

This succesfully force-updates the Control properties, but it is a hack imo, because it requires re-setting your anchors. If the anchors are custom, its a problem. At least it is a good workaround - better than binding resized signals.

You can close this as duplicate :thumbs_up:
