### ISSUE TITLE
An AreaLight3D Node?

### ISSUE THREAD

**Issue by MangoDragonHub** [godotengine/godot-proposals#11059]
### Describe the project you are working on

Showcasing 3D Models within a real time game engine.

### Describe the problem or limitation you are having in your project

When I'm doing in-engine renders and look dev with Godot for either static models or character models, I have to use point lights for the scene. Sure, they can do the job, but I need a simple lighting solution that allows me to get the proper rim and studio lighting that I need. For example, most of Marmoset, Unreal, and Blender showcase renders usually use a 3-point lighting set up. 
![Screenshot_20241031_140529](https://github.com/user-attachments/assets/2bcc84e2-fea3-4bac-abb1-3c8bd053d89e)
Usual Blender Setup for 3-Point Lighting with Area Lights
![Screenshot_20240222_182106](https://github.com/user-attachments/assets/80176737-d091-4f72-862d-0d81fe7be7a3)
Example of Godot Lighting using default Point Lights

It would be nice to get that specific level of control thanks to the rectangular shape of the light source.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In your nodes drop down, the AreaLight3D Node is bundled with the other 3D Light Sources. You can change the intensity and attenuation of the light source. However, thanks to it being able to change the shape of the light source,  it's both precise and contained when lighting a certain object or area. 
This can be helpful if you're working on a corridor and have those wide ceiling lightings, using an AreaLight3D to cover that space would make it easier to light that are inside of using multiple point lights, plus it reduces them overlaying on top of each other.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Using Unity, Godot and Blender a a basis, a lot the back end work is already done thanks to all main light source inherit from Light3D. The main core additions that needs to be made is having preset shapes of lights that can be chosen (ie. Rectangle, Disk, Star, etc.) and the ability to change the Width and Height of the shape. Elements from the OmniLight like Range and Attenuation functionally will stay the same.  
![AreaLight3D Proposal](https://github.com/user-attachments/assets/ee0699ce-63eb-47ef-ae08-c676d0a82249)
 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature will be commonly used. Especially for those who are previewing assets they've made in a DCC tool like Maya or Blender and want to render them in-engine. Environment Artists who needs precision with their light sources. Arc-Vis and Engineers who need to craft a basic lighting set ups that are accurate. This shouldn't take long to make since a lot of the work has already has been completed only needing those specific additions. 

### Is there a reason why this should be core and not an add-on in the asset library?

It should be part of the core engine since it's not heavy weight and right at home with the other light sources.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1275.
