### ISSUE TITLE
Option for script-wide warning ignores

### ISSUE THREAD

**Issue by InTheProcess** [godotengine/godot-proposals#11053]
### Describe the project you are working on

I am working on a project with lots of abstract classes and variables that are not used in-script, but are used by another class.

### Describe the problem or limitation you are having in your project

Because I have so many variables and methods, it is very repetitive and makes code more unreadable to add a warning ignore for every instance I want to ignore it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to ignore specific warnings as well as all warnings in a script.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For specific warning ignores:

@warning_ignore(“warning_id”)
class_name Example
extends Node

For all warning ignores:

@warning_ignore_all()
class_name Example
extends Node

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by adding an warning ignore annotation for every instance where it is needed, but this is very inconvenient and makes code harder to read.

### Is there a reason why this should be core and not an add-on in the asset library?

This makes sense to be a core feature of gdscript because this feature will be used very often and it is so simple that it makes sense for gdscript to have this feature.

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot-proposals/issues/5906
