### ISSUE TITLE
Add copy button to toast notifications

### ISSUE THREAD

**Issue by jaydensipe** [godotengine/godot-proposals#11067]
### Describe the project you are working on

An editor plugin that will utilize toast notifications if https://github.com/godotengine/godot/pull/98680 is merged

### Describe the problem or limitation you are having in your project

If https://github.com/godotengine/godot/pull/98680 is merged, the toast notifications that are created in editor (with `push_toast` method) are not displayed in the console for a user to easily copy, as well as the toast notification label not being selectable.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a copy button to the toast notification

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/user-attachments/assets/f163fea2-2680-4ea2-891d-bc1561b189d4

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

Should be included with the toast notifications

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/8155
and https://github.com/godotengine/godot-proposals/issues/8156.
