### ISSUE TITLE
Reparent nodes to the root node when they're dragged onto the empty space in scene dock

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot-proposals#11066]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

It could be easier to move nodes to the root node.

Nothing happens when you try to drag a node onto the empty space:

https://github.com/user-attachments/assets/5e2f509f-632d-4bf9-b8a2-39ab9fc84e80

In most software when you drag something to the empty space in a list you can expect it to appear at the top level at the end of the list:

https://github.com/user-attachments/assets/d72d8262-d99d-4ded-ab6d-baa39d910a49

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Reparent nodes dragged onto the empty space to the root node. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

Too basic to either be an addon or an editor script

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/8825.
