### ISSUE TITLE
Update Android Dialog Theme

### ISSUE THREAD

**Issue by syntaxerror247** [godotengine/godot-proposals#11071]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Currently, native dialogs on Android in Godot looks too old and feels inconsistent with other apps.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This proposal suggests updating the Android dialogs in the Godot Engine to use either `Theme_Material_Dialog_Alert` or `Theme_DeviceDefault_Dialog_Alert`. Dialogs will look alot better, providing a better user experience and consistency with other apps.

- **Theme_DeviceDefault_Dialog_Alert**: To align them with the native appearance and it will vary depending on the device's default styling.
- **Theme_Material_Dialog_Alert**: To keep it consistent across different devices.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We will have to modify the code in Godot.kt to use either `Theme_Material_Dialog_Alert` or `Theme_DeviceDefault_Dialog_Alert`.

For example, update alert dialog builder
```kt
val builder = AlertDialog.Builder(activity)
```
to this, to apply `Theme_Material_Dialog_Alert`
```kt
val builder = AlertDialog.Builder(activity, android.R.style.Theme_Material_Dialog_Alert)
```
<details><summary>Theme_DeviceDefault_Dialog_Alert Demo Image, tested on a Xiaomi Phone</summary>
<p>

![DeviceDefault](https://github.com/user-attachments/assets/6e40785d-389e-4ec8-8b56-16fced2a2ae1)

</p>
</details> 

<details><summary>Theme_Material_Dialog_Alert Demo Image</summary>
<p>

![Material](https://github.com/user-attachments/assets/2f4e8500-1645-465b-851c-0f342b6766d4)

</p>
</details> 

With either theme, binary size impact will likely be small. If `Theme_DeviceDefault_Dialog_Alert` is chosen, there should be no increase in binary size as it uses system resources.
`Theme_Material_Dialog_Alert` offers a more consistent appearance across different devices. This can improve the visual appeal but may differ from the device’s native alert styling and slightly more in size.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature could technically be worked around by creating an Android plugin to use custom dialog or by building a custom export template. However, both approaches require a good understanding of Android development, which may be too much for users who aren't familiar with Android-specific tools and setup.

### Is there a reason why this should be core and not an add-on in the asset library?

As mentioned earlier, while this can be technically achieved through custom plugins or export templates, it would be better to update in the core of Godot. This would eliminate the need for additional setup or knowledge of Android development for users.

**Comment by Calinou** [comment]
I recall this being discussed a while ago, and using an up-to-date Material theme involved increasing the APK size by several hundred kilobytes due to needing Jetpack libraries or something.

**Comment by syntaxerror247** [comment]
It won’t need any additional dependencies, `Theme_DeviceDefault_Dialog_Alert` and `Theme_Material_Dialog_Alert` are part of the core Android framework. Since both themes are system-provided, they rely on built-in resources.

**Comment by m4gr3d** [comment]
> I recall this being discussed a while ago, and using an up-to-date Material theme involved increasing the APK size by several hundred kilobytes due to needing Jetpack libraries or something.

I remember @Alex2782 did those tests and found the increase in apk size; if we can use a different approach that doesn't increase the apk size, then it sounds good to me!

**Comment by syntaxerror247** [comment]
@m4gr3d I haven't seen the discussion that is being referenced here, but if by "tests" you mean "old and new apk comparision" then, yes there is no increase in size.

This is comparision of old and new apk after aplying `Theme DeviceDefault` to only alert dialog.

![DeviceDefault](https://github.com/user-attachments/assets/f4537d97-0ecf-44d0-9dfa-60b07a38b4f0)

**Comment by Alex2782** [comment]
I tested with `com.google.android.material:material`, I wasn't aware of any other solution at the time.

**Comment by syntaxerror247** [comment]
I would also like to know which theme should we use. I would like to go with `DeviceDefault` as this will provide truly native dialogs.

React with your prefered theme 😅
👍 -> DeviceDefault
🚀 -> Material

**Comment by Alex2782** [comment]
`android.R.style.Theme_Material_Dialog_Alert`

I'll try to compare different OS (Samsung / Sony etc.) and different Android versions later on Firebase Testlab.
