### ISSUE TITLE
Add a way favorite/bookmark addons in the Asset Library

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot-proposals#11080]
### Describe the project you are working on

-

### Describe the problem or limitation you are having in your project

It is easy to forget what addons/plugins you've used in previous projects that you found good. Trying to find them again in the Asset Library can be tedious since there are usually several different addons that try to solve the same problem.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to bookmark/favorite addons in the Asset Library to more easily find them again.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A button in the addon details window, some way to see which has been bookmarked in the addons list, and a way to see all your bookmarks (either its own window or as a filter).

![image](https://github.com/user-attachments/assets/33a2ce01-5b69-40f4-88ad-0ee662c51b5a)
![image](https://github.com/user-attachments/assets/8f122889-dd4e-44f5-a8bc-977bb185162a)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/3521.
