### ISSUE TITLE
Extend Blender-style transformation controls to 2D editor

### ISSUE THREAD

**Issue by throckmorpheus** [godotengine/godot-proposals#11090]
### Describe the project you are working on

Point and click adventure game (specifically with rigged 2D characters), but this applies to any 2D project.

### Describe the problem or limitation you are having in your project

I use the Blender-style controls in 3D, and find that I can work much faster with them. Trying to set up compilicated scenes in 2D (rigging and animating with Skeleton2Ds), I found that the lack of these controls made things more cumbersome.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add equivalent Blender-style controls to the 2D editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would work equivalently to the Blender-style controls in 3D, just without the Z axis.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would be used often, at least by people who prefer the Blender-style controls.

### Is there a reason why this should be core and not an add-on in the asset library?

It already exists in the 3D editor, this just makes sense for parity.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/7742.
