### ISSUE TITLE
shadows on tiles with transparency

### ISSUE THREAD

**Issue by cobreen** [godotengine/godot-proposals#111]
Procedural generated dungeon

Is weird shadow casting can be fixed?

Bad:
![example](https://user-images.githubusercontent.com/22748041/65818976-9c8f2080-e21f-11e9-9c25-b7f52c43170d.png)

Good:
![example](https://user-images.githubusercontent.com/22748041/65818990-cfd1af80-e21f-11e9-9070-596584f31cee.png)

toggle in light2d.

Maybe

There are a lot of games which are using a tilemap and light2D both

**Comment by groud** [comment]
> https://github.com/godotengine/godot-proposals

Please read the rules and fill in the template.

Also, this might god into the [godot](https://github.com/godotengine/godot) repository, as this is more likely a bug.
