### ISSUE TITLE
Add `clear` function to `Node`

### ISSUE THREAD

**Issue by derkork** [godotengine/godot-proposals#11104]
### Describe the project you are working on

Applicable to all games and applications.

### Describe the problem or limitation you are having in your project

During development there are a lot of cases when one needs to rebuild part of a node tree. For example list views of players, items, etc. need to be updated. This usually results in code like this:

```gdscript
@onready var result_list_node:Container = ...

func update_player_results(results:Array[Results]) -> void:
    for child in result_list_node.get_children():
          result_list_node.remove_child(child)
          child.queue_free()

    # make new list items and add them to the result node.
```

Especially when doing UI work this pattern is visible everywhere, but it equally applies to things like inventories (if people decide to implement inventories with nodes) or pretty much an situation where a list of child nodes needs to be kept up-to-date.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a `clear` function to `Node` which clears its children and optionally frees them, e.g.

```gdscript
func clear(free_cleared_nodes:bool = true, include_internal:bool = false)
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The defaults are picked so that the operation will do the safe choice when people just call `clear()` - it will remove and free all the child nodes of the node. If people just want to clear out the node but keep the children around they can do:

```gdscript
var children = result_list_node.get_children() # or maybe they even have a list from when the nodes were added
result_list.clear(false)
```

Either way we don't need to write a for loop every time we want to clean out a part of our node tree.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around with a few lines of script but this is a simple convenience function that will streamline a use case that happens pretty frequently.

### Is there a reason why this should be core and not an add-on in the asset library?

It technically can be an add-on in the asset library but this is such a low level thing, that it just makes more sense to have it in core. Also since add-ons cannot change core APIs the call would then look something like 

```gdscript
NodeUtils.clear(_result_list)
```
which is still nicer than the for-loop but not as nice as:

```gdscript
_result_list.clear()
```

**Comment by dalexeev** [comment]
See:

* #764
* https://github.com/godotengine/godot/pull/94163

**Comment by derkork** [comment]
Nice, I did a search but it didn't pop up. Makes sense to continue the discussion there. I'm closing this.
