### ISSUE TITLE
Add properties to make VisibilityNotifier2D more accurate

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1110]
**Describe the project you are working on:**
flip screen platform game

**Describe the problem or limitation you are having in your project:**
VisibilityNotifier2D (as currently designed) is very inaccurate, even when setting the cell size to a very small number. Testing across different machines gives various results with the same values meaning consistency cannot be achieved for determining when an object leaves the screen.

Putting a notifier polygon far outside the sprite, in the example below the notifier on the right does not trigger until the sprite is completely off the screen to the right with a cell size of 8 (from default of 128).

![image](https://user-images.githubusercontent.com/12863685/85402724-13114280-b554-11ea-8c50-1a813ebb2a75.png)

This is generally ok because the visibility notifier is often used to remove sprites no longer needed, such as enemies, however when the notifier is required for the player (e.g. flip/wrap around) accuracy is important.

Switching to an Area2D on the camera is much more long winded and removes the ability to set the notifier with the player node.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A high quality flag for the visibility, or an 'EnhanceVisibilityNotifier2D'.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I imagine most of the complexity is for 3D, but for 2D it should be much less intensive and simpler to create a 'high quality' non heuristic approach to visibility.

Add a flag (or a new EnhanceVisibilityNotifier2D node) that either changes the method for 2D screen/viewport leaving/entering or increases polling and removes a 'cell size' requirement.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no, the only alternative is area2d on a camera, and that is more complex and removes ability to set it on a specific kinematic body.

**Is there a reason why this should be core and not an add-on in the asset library?:**
2D platform games make up a large volume of games and such a 'random' and inaccurate event is not good.

**Comment by Calinou** [comment]
What about checking for the distance from the viewport's edges occasionally? If you want a high-quality result, you should generally use a method that's guaranteed to be as deterministic as possible. VisibilityNotifier2D (and its 3D countertpart) are intentionally approximate in the interest of performance.

**Comment by chucklepie** [comment]
I have already rewritten using Area2D, I just thought there must be a better way to implement a more accurate version of the visibility notifier and a means of doing it with guaranteed same results. Accepting a hit on performance as it's much better to have notifiers on objects rather than on a camera. 

At the minute, it's only of use to stuff you aren't bothered about, which is not always the case.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/49632#pullrequestreview-684950135, closing.
