### ISSUE TITLE
Renaming node permanently destroys child nodes setup on another scene

### ISSUE THREAD

**Issue by kristianpiacenti** [godotengine/godot-proposals#11101]
### Describe the project you are working on

4.3

Both scenes are .res

### Describe the problem or limitation you are having in your project

https://github.com/user-attachments/assets/31c96e55-a834-4988-9244-692fa5c0d65a

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I don't know what the engine does behind the scene, it probably detects that the node has been renamed and it re adds to the scene. 

Something destructive like this should be confirmed by a prompt. If it's hard don't allow users to add sub nodes to non local nodes. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Display a confirmation node before destructive operations or display an error message forbidding the user to do the destructive operation

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It's crucial that behaviors like this are not present in a stable version of the engine, it can cause the user enormous loss of data if not aware

**Comment by KoBeWi** [comment]
Thanks for the proposal! Consolidating in #6291 (it presents a solution to the same problem)

> Display a confirmation node before destructive operations or display an error message forbidding the user to do the destructive operation

Renaming a node is normally not a destructive operation. It's destructive only if the scene is inherited by another scene and there is no feasible way to detect that.
