### ISSUE TITLE
Add shortcut properties to Vector3

### ISSUE THREAD

**Issue by 0zuzu** [godotengine/godot-proposals#11112]
### Describe the project you are working on

3D First person character controller with parkour elements.

### Describe the problem or limitation you are having in your project

Having to do "Vector2(velocity.x, velocity.z)" to extract horizontal velocity seems unnecessarily cumbersome compared to alternatives from other game engines and 3D software.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose adding the following methods to Vector3: `Vector3.xy`, `Vector3.xz` and `Vector3.yz`, which return a Vector2 with the corresponding coordinates. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In my current project, I only need to work with X and Z coordinates together, so I can't think of applications for .xy and .yz. However, I am sure that there are, such as projects that are using a different coordinate convention for example.

Example of usage: `horizontal_velocity = velocity.xz` instead of `horizontal_velocity = Vector2(velocity.x, velocity.z)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around, but like I said it is unnecessarily cumbersome and other game engines already have these methods, which can be confusing and annoying for new developers moving to Godot.

### Is there a reason why this should be core and not an add-on in the asset library?

Everyone benefits from it, I believe this is too simple and "core" to keep it as an asset library. It is used often and a couple extra methods won't bloat the Vector3 class. An interesting fact is that LLMs already recommend these methods when generating code fot Godot even though they don't even exist, that's how standard they are.

If this proposal already exists here please let me know and I'll delete it right away.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/727.
