### ISSUE TITLE
Add `PROPERTY_USAGE_NO_STORAGE` to PropertyUsageFlags

### ISSUE THREAD

**Issue by Goy288** [godotengine/godot-proposals#11127]
### Describe the project you are working on

An addon that involves a bunch of dynamic property list manipulation.

### Describe the problem or limitation you are having in your project

Basically, my property list displays parameters for a bunch of things my node dynamically generates, stores them into a dictionary when modified with the `_get()` function, and retrieves them from it when needs to display the modified properties with the `_set()` function. The dictionary data is legitimately all I need to be stored, but the problem is that these extra dynamic generated properties are stored into the scene data when they don't have to be. I even manually deleted the extra bloat data from the scene file, loaded it, and it displayed just fine. There's no use to me storing these at all, but they're there regardless. I tried using `PROPERTY_USAGE_EDITOR`, but this seems to have no effect in stopping these properties from being stored.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add `PROPERTY_USAGE_NO_STORAGE` to PropertyUsageFlags to just outright prevent storage of certain properties if they don't need to be stored.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Something kind of like:
```gdscript
properties.append({
	"name": "category_name/" + dynamic_string_for_whatever_this_would_be_used_for,
	"type": TYPE_OBJECT,
	"usage": PROPERTY_USAGE_NO_STORAGE,
})
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If it can, I'd love to know how.

This whole thing by the way technically doesn't affect the main functionality of my addon at all, but the junk data's existence still nags at me when I look at it.

### Is there a reason why this should be core and not an add-on in the asset library?

I feel like making a GDExtension for something this small would be overkill, so probably not.

Side note: This is like, my third property list related submission in a row so far. Not sure if I should be considered innovative or just weird at this point for using them the way that I have been.

**Comment by AThousandShips** [comment]
This isn't needed, you just don't add the `PROPERTY_USAGE_NO_STORAGE` flag, using `PROPERTY_USAGE_NONE` for example or `PROPERTY_USAGE_EDITOR` for editor but not storage

**Comment by Mickeon** [comment]
As AThousandShip said, properties are not stored by default. `PROPERTY_USAGE_NONE` (no flags, `0`) to `usage` means the property has no particularly special usage.
Any combination of flags with `PROPERTY_USAGE_STORAGE` means the property is saved.
Any combination of flags with `PROPERTY_USAGE_EDITOR` means the property is exposed in the Inspector.

I can understand the ambiguity, though, as `PROPERTY_USAGE_DEFAULT` _claims_ to be the default, but it's not. It's the default for properties with the `@export` annotation. I remember this confusion being tracked somewhere else, but I am not sure at the moment.

This proposal should be closed as this feature already exists. If you believe there's a misunderstanding, please let us know.
