### ISSUE TITLE
Add a Default Canvas Cull Mask project setting

### ISSUE THREAD

**Issue by Summersay415** [godotengine/godot-proposals#11122]
### Describe the project you are working on

2D Shooter game with minimap which uses SubViewport and visibility_layers

### Describe the problem or limitation you are having in your project

Minimap works this way: all its elements are on visibility layer 2, and everything else by default is on layer 1. I have MinimapViewport which have canvas_cull_mask set to 2. And I need to hide all CanvasItems with layer 2 on the root Viewport. To do this, I can write some initialization code, like `get_tree().root.set_canvas_cull_mask_bit(2, false)`, from editor interface I can't do this.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add project setting `rendering/viewport/default_canvas_cull_mask` which sets `canvas_cull_mask` on root Viewport on startup, providing more friendly interface than editing in code.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just single project setting `rendering/viewport/default_canvas_cull_mask`, which sets `canvas_cull_mask` on root Viewport on startup, but only in Game, not the Editor (I want to see all CanvasItems in the editor regardless of this setting)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around, but we have so much settings which just set something on root Viewport on startup, so, why not?

### Is there a reason why this should be core and not an add-on in the asset library?

It's core

**Comment by clayjohn** [comment]
Could you describe the limitation you are having in your project and how this new feature would lift that limitation?

The most important part of a feature proposal is communicating how this feature is needed to unblock you. It's not enough to say that you simply want the feature and the limitation is lifted by having the feature.

**Comment by Summersay415** [comment]
Updated

**Comment by clayjohn** [comment]
Are the Minimap CanvasItems stored in the heirarchy under the Viewport? It sounds like you may benefit more from using a unique World rather than using cull masks. 

Here is a tutorial on how this is supposed to work in Godot (its from Godot 3 but the concepts are the same) https://kidscancode.org/godot_recipes/3.x/2d/splitscreen_demo/index.html

**Comment by Summersay415** [comment]
No, minimap markers are stored along with the objects they show. I have one extra MinimapViewport which shares world with main window (this is done from code, but should be option like `own_world_2d`, but this is another proposal). This way minimap markers are not linked to minimap Viewport, and they can have any position in hierarchy, which gives very good flexibility.

**Comment by Summersay415** [comment]
Okay, 2 line workaround is OK
