### ISSUE TITLE
Allow `@export_tool_button` to be applied to methods directly

### ISSUE THREAD

**Issue by sockeye-d** [godotengine/godot-proposals#11147]
### Describe the project you are working on

I made some transitions and I added buttons to run them in the editor

### Describe the problem or limitation you are having in your project

The annotation is annoying to use, since you have to create a bunch of variables that don't do anything except store a reference to a method

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow applying them to methods

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would look like this:
```gdscript
@export_tool_button("Action")
func action():
    print("hi")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but it's annoying to

### Is there a reason why this should be core and not an add-on in the asset library?

It can't be a plugin

**Comment by dalexeev** [comment]
* See https://github.com/godotengine/godot-proposals/issues/2149#issuecomment-2394937456.

**Comment by sockeye-d** [comment]
Okay, I'll close this issue 😔
