### ISSUE TITLE
Show blend shape IDs and sort by ID instead of alphabetically

### ISSUE THREAD

**Issue by Jesusemora** [godotengine/godot-proposals#11155]
### Describe the project you are working on

3D game

### Describe the problem or limitation you are having in your project

blend shapes are currently shown in the inspector in alphabetical order.
but there is no way to obtain the names of the blendshapes through code, and the methods ask for an ID:
```
get_blend_shape_count()
get_blend_shape_value(blend_shape_idx : int)
set_blend_shape_value(blend_shape_idx: int, value: float)
```
![Captura desde 2024-11-13 17-53-45](https://github.com/user-attachments/assets/5fd15787-9ec3-4504-84ef-cabe82779c85)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

either show the blend shapes in order of ID, that is, in the order they appear in blender, or show the ID of each blend shape next to the name (or somewhere)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

very quick mockup, could be much better or different
![new_blend_shape_inspector](https://github.com/user-attachments/assets/9a9c9a90-6297-4a8a-b338-6f122f242ae0)

edit:
could this be the problem? line `89` of `scene/3d/mesh_instance_3d.cpp`:
```
void MeshInstance3D::_get_property_list(List<PropertyInfo> *p_list) const {
	List<String> ls;
	for (const KeyValue<StringName, int> &E : blend_shape_properties) {
		ls.push_back(E.key);
	}

	ls.sort();
```

why are we sorting the blend_shape_properties?

and there's also line `387` that seems to just give it a name:
```
void MeshInstance3D::_mesh_changed() {
	ERR_FAIL_COND(mesh.is_null());
	surface_override_materials.resize(mesh->get_surface_count());

	uint32_t initialize_bs_from = blend_shape_tracks.size();
	blend_shape_tracks.resize(mesh->get_blend_shape_count());

	for (uint32_t i = 0; i < blend_shape_tracks.size(); i++) {
		blend_shape_properties["blend_shapes/" + String(mesh->get_blend_shape_name(i))] = i;
		if (i < initialize_bs_from) {
			set_blend_shape_value(i, blend_shape_tracks[i]);
		} else {
			set_blend_shape_value(i, 0);
		}
	}

	int surface_count = mesh->get_surface_count();
	for (int surface_index = 0; surface_index < surface_count; ++surface_index) {
		if (surface_override_materials[surface_index].is_valid()) {
			RS::get_singleton()->instance_set_surface_override_material(get_instance(), surface_index, surface_override_materials[surface_index]->get_rid());
		}
	}

	update_gizmos();
}
```
but the name is used by the `_get` method, so it's probably not a good idea to change it.

edit: this code appears to send the data for creating the slider, so could we append the number here? or does it expect a `StringName`?
```
	for (const String &E : ls) {
		p_list->push_back(PropertyInfo(Variant::FLOAT, E, PROPERTY_HINT_RANGE, "-1,1,0.00001"));
	}
```

Edit again: sorry, I have been looking at the code for hours and I think I understand more of how Godot works.
1 - it has to be sorted because it's a HashMap
2 - the property name is passed to the inspector which then uses `get` `set` on the object, is this correct? So it has to be Verbatim.

I will continue to look at possible solutions.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

it is part of meshinstance3D

**Comment by fire** [comment]
Would it be ok if we displayed the blend_shape_properties by index and removed the sorting?

**Comment by fire** [comment]
I drafted a pr. Testing now https://github.com/godotengine/godot/pull/99231

**Comment by fire** [comment]
@Jesusemora 

Can you test with your samples and write if it works for you in the https://github.com/godotengine/godot/pull/99231 pull request?
