### ISSUE TITLE
Use default value for an argument after `,`

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1117]
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
I have to give the default value of the first argument if I want to pass a value that is different from the second argument's default.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
You could step over the argument and only pass a value to the next one.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
func _ready():
	my_function("vvv", "mmm")
	my_function("passed to first argument")
	my_function(, "passed to second argument")

my_function(arg1 = "hshaf", arg2 = "ldvm"):
	print(arg1, arg2)
```
This would print
vvv
mmm
passed to first argument
ldvm
hshaf
passed to second argument
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so.
**Is there a reason why this should be core and not an add-on in the asset library?:**
I think an add-on can't change/add etc. something to the language.

**Comment by bojidar-bg** [comment]
The problem/limitation discussed is likely the same one as #902.

**Comment by Calinou** [comment]
This feature might look confusing at a first glance to people coming from other language. I don't know of any popular language which allows this.

**Comment by SIsilicon** [comment]
@Calinou I personally think this is a pretty neat idea, regardless of what other languages do.
Besides, isn't this syntax similar to what is done with a setter and getter?
```
var set_and_get setget set, get
var set_only setget set
var get_only setget , get
```

**Comment by Calinou** [comment]
@SIsilicon Yes, but that `setget` syntax is going away in 4.0 last time I checked.

**Comment by KoBeWi** [comment]
> I can't think of any popular language which allows this.

You can do this in Javascript, but with `undefined` keyword, not blank space.

**Comment by MaaaxiKing** [comment]
I've also had thaughts about the setget similarity.
But one big question I have is why does a language has similarities to other ones? Why can't it just be made better no matter if other languages support this or if it would be the first language?!

**Comment by Calinou** [comment]
> But one big question I have is why does a language has similarities to other ones? Why can't it just be made better no matter if other languages support this or if it would be the first language?!

Most people using Godot have experience with at least one other programming language. Breaking expectations means they have to "unlearn" things they've learned in other languages. We want to keep this to a minimum.

**Comment by MaaaxiKing** [comment]
I can understand that but if all language programmers would make just little differences to other languages, you could then just not program a new one.

**Comment by pycbouh** [comment]
> You can do this in Javascript, but with `undefined` keyword, not blank space.

An explicit keyword is definitely better than just an empty space (I know that `undefined` is not a keyword in JS, it's actually problematic there). It's hard to notice a comma, it can look like an error or typing mistake. So if we want a way to explicitly request "use a default value from the function declaration" then I propose `default` or some other descriptive keyword to be used here.

So the example would be:
```gdscript
my_function(default, "passed to second argument")
```

**Comment by MaaaxiKing** [comment]
@pycbouh, I agree but what if you have a variable named _default_?

**Comment by MaaaxiKing** [comment]
Or maybe just a comma would be better if it was highlighted in a strong color? That would be my favourite, I think.

**Comment by pycbouh** [comment]
@MaaaxiKing Keywords are reserved words, you can't name variables using reserved words. You may have a variable named `default`, or something else, now, and in that case you'd need to change your code for a future version of GDScript. And since any of this can only be implemented in 4.0, a breaking change is not a big problem.

**Comment by MaaaxiKing** [comment]
OK, would be fine then.

**Comment by KoBeWi** [comment]
The keyword could be something less likely used for a variable name, like `_default_`.

**Comment by MaaaxiKing** [comment]
> The keyword could be something less likely used for a variable name, like `_default_`.

Or maybe `_default`?

**Comment by bojidar-bg** [comment]
There is already a "keyword" for something similar: `_`, at least when used for discarding values in `match` statements.

**Comment by MaaaxiKing** [comment]
Oh, you're right.

**Comment by pycbouh** [comment]
> There is already a "keyword" for something similar: `_`, at least when used for discarding values in `match` statements.

@bojidar-bg Arguably not the best syntax either. I'd prefer something that reads obviously in both cases. Makes a bit more sense in `match` statements to mean "match any" though. If it was a `switch` statement, making it `default` would be more reasonable.

**Comment by MaaaxiKing** [comment]
I think `_` from `match` should be changed to `_default` and in this proposal it should be `_default` too then.

**Comment by vnen** [comment]
I don't see a way to implement this. When calling functions in C++ there's no way to do this, and the binders also don't allow that (maybe could be done with a good amount of hacks but I'd rather not to). So even though I understand the value of this, I don't think it's feasible to implement.

**Comment by Calinou** [comment]
Closing per @vnen's comment.
