### ISSUE TITLE
Support choosing margin between textures in SpriteFrames

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1118]
**Describe the project you are working on:**
Breakout
**Describe the problem or limitation you are having in your project:**
I have a TileMap and want to select a texture in a frame in an animation of an AnimatedSprite and can't get it correctly because the program's default margin is set to 0.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
You could specify hw big the margin between each texture is.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Godot AnimatedSprite TileMap with Margin](https://user-images.githubusercontent.com/60623532/85758519-b27b3480-b710-11ea-928e-d0c8e073334e.png)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, everyone who uses TileMaps in AnimatedSprites could use.

**Comment by MaaaxiKing** [comment]
Of course, this should also be added in the import tab.

**Comment by Calinou** [comment]
> Of course, this should also be added in the import tab.

Why? As far as I know, frame width and height aren't defined in the Import tab. Adding a margin property there would be inconsistent with the width and height properties.
