### ISSUE TITLE
Parameter "get_viewport()" is null while reparenting in an Area2D/3D

### ISSUE THREAD

**Issue by Rebell10n** [godotengine/godot-proposals#11197]
### Describe the project you are working on

A top-down Zelda-like adventure game, but this doesn't matter a lot as this problem could hits a variety of game with a moving character.

### Describe the problem or limitation you are having in your project

Was creating a "change zone" mechanics while hitting certain Area2D. Got lots of problems, but then I hit one that does an infinite loops with putting as an error message : `Parameter "get_viewport()" is null` while all I do is reparent my main character to the new zone and docs def says I didn't needed to give him a viewport arg, neither did I accidentally, so searched for a bit on the net and found... That it's because the characterbody, as being reparented, triggers again the "Body entered" signal, as such restarting the function and reparenting again. Infinitenly as such. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, to be honest not sure if that the right place to suggest that, but since it's not a bug report but a suggestion to change the error message... so yeah, `Parameter "get_viewport()" is null`  is not helpful error at all. In fact might be in the doc to avoid such error that reparenting something consider it entering any zone it was in and retrigger all signal for doing such.

I don't know if the Node should in fact retrigger the area entered and body entered each time they are reparented, but the way to notify the error... I mean, how I'm supposed to know that the viewport thing is tied to that ? In fact I still don't know why ? 

I thought it was because Camera was absent for a frame, but not even, as for the guy was having the prob on the net as I've said precedently, was having this prob with enemies changing chunks, so def not a Camera prob.

Well it might be a small and minor issue, I agree, but for a second thought I would have hours of trying to fix and hellish problem, without using the good solutions I guess.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know exactly in fact.
First I guess add docs on that interactions, unless that too specifics.
Then I guess put a warning or change the error to say that it because your reparent retrigger the body_entered.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I cannot without changing the damn CPP. 

Well, the error in itself can be fixed by checking if the node already has been reparented by X node.

### Is there a reason why this should be core and not an add-on in the asset library?

Evidence.

#### EDIT
Seems that the bug wasn't due to what I said, but since it's similar to the issue of that other guy : https://www.reddit.com/r/godot/comments/1cloe8h/parameter_get_viewport_is_null/
That might still be tied, but since I don't know what triggered it, and definitely an unclear bug, I guess I couldn't even make a bug report, since I can't repro. Well guess this issue will sleep dormant until someone else figure it out.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/42719. Please report cryptic error messages there instead 🙂
