### ISSUE TITLE
Add a Viewport signal emitted when ReflectionProbe rendering is done

### ISSUE THREAD

**Issue by bertodelrio256** [godotengine/godot-proposals#11198]
### Describe the project you are working on

Working on a large 3D game involving the use of PBR and reflection probes

### Describe the problem or limitation you are having in your project

the reflection probe system in Godot samples all of its radiance and hdri data from the environment at run time after the scene is ready. there is not much control over this. When loading a new level, I will wait for the ready function of the root to be called before showing the scene and starting the level. however, since the probes have not finished sampling, they are seen flickering and creating bad looking visuals while cutscenes are playing. I've seen the Godot developers suggesting to set an arbitrary timer after ready before starting cutscenes, but I think this in an unacceptable solution for several reasons.

1. the amount of time that a scene can take to sample all of its probes can vary greatly depending of lots of factors
2. I think a player who pays thousands of dollars for a high end pc, should get every once of performance they can get and waiting for levels to load is very important part of that

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would propose a new signal is added at the viewport level that would be called after all the probes have finished sampling.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the signal would be called immediately after the probes have been sampled. im not sure where in the renderer code this is done.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

impossible, nowhere in the api is the sampling status exposed

### Is there a reason why this should be core and not an add-on in the asset library?

impossible, nowhere in the api is the sampling status exposed

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/4782.

If we implement the spedup baking solution I mentioned in https://github.com/godotengine/godot-proposals/issues/4782#issuecomment-2459518408, there's much less reason to have a signal since the probes will have finished baking much sooner. Offline baking would make it even less of a necessity, since most of the probes in the level (if not all) can be baked in advance and load instantly.

**Comment by bertodelrio256** [comment]
ok, if I can calculate the exact number a frames to wait, that works.  Thanks! If you think having a signal is overkill, I can close this.

**Comment by bertodelrio256** [comment]
Also, Im using C# so im not sure the equivalent to the gdscript "await". I can always just count an int in process.

**Comment by bertodelrio256** [comment]
```csharp
DisplayServer.VSyncMode prev_vsync = DisplayServer.WindowGetVsyncMode();
		int prev_max_fps = Engine.MaxFps;
		DisplayServer.WindowSetVsyncMode(DisplayServer.VSyncMode.Disabled);
		Engine.MaxFps = 0;
		int proberender_frame_ct = GetNode<Node3D>("lights/probes").GetChildCount() * 18;
		for (int i = 0; i < proberender_frame_ct; i++)
		{
			await ToSignal(GetTree(), "process_frame");
		}
		DisplayServer.WindowSetVsyncMode(prev_vsync);
		Engine.MaxFps = prev_max_fps;
```
for documentation, this is the code i used in C#. works great thanks!

**Comment by bertodelrio256** [comment]
i think the provided code works fine. although, i do think this should be in the documentation. closing.

**Comment by Zireael07** [comment]
Probably worth documenting better, yeah
