### ISSUE TITLE
Use native window drag handles on macOS when Expand to Title is enabled, making window tiling functional

### ISSUE THREAD

**Issue by D4r3NPo** [godotengine/godot-proposals#11214]
### Describe the project you are working on

Any of my godot project. 

### Describe the problem or limitation you are having in your project

Since MacOS Sequoia, window can be drag on screen edge to effortlessly arrange them into side-by-side tiles. (Like on Windows OS)
But Godot editor is not detected by the screen edge. (While Godot player windows are)
It is still possible to use the green button on top of godot editor window to use layout but it is less ... effortless.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add custom edge detection or make godot editor more like a "normal" MacOS window to allow the default detection

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same behavior as other MacOS windows, drag the window one screen edges, or in combinaison with option key will tile Godot editor window

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I estimate it will be use by near every MacOS user each time they use the Godot Editor

### Is there a reason why this should be core and not an add-on in the asset library?

I assume it's a light and very useful feature for all MacOS user.

**Comment by bruvzg** [comment]
> Consolidating in https://github.com/godotengine/godot/issues/36373, as this is due to the same cause.

Not related, it's caused by our custom title bar implementation, not by window size.
