### ISSUE TITLE
Consolidation of boundary-touching functions in character_body_2d.cpp

### ISSUE THREAD

**Issue by fitzgibe** [godotengine/godot-proposals#11218]
### Describe the project you are working on

I am working on potential contributions to an open source project for a class I'm taking on the subject.

### Describe the problem or limitation you are having in your project

While the naming conventions of the boolean functions on lines 433 through 455 in [character_body_2d.cpp](https://github.com/godotengine/godot/blob/master/scene/2d/physics/character_body_2d.cpp) are intuitive and likely easy to call elsewhere in the project, the work here could be condensed into a single variadic function. This function will interpret variadic input to return the values on_floor, on_wall, and/or on_ceiling or their negations.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would allow for simpler reference to boundary-position for Character2DBody objects elsewhere in the code.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This function would be called as CharacterBody2D.is_touching(“only”, “floor”); or CharacterBody2D.is_touching(“FLOOR”); as implemented below.
![Image](https://github.com/user-attachments/assets/02518593-684b-4820-9cef-08cf5b514a36)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You would need to use this function (or one of the current implementations) to access the private attributes on_floor, on_ceiling, on_wall, as they are currently defined in character_body_2d.h.

### Is there a reason why this should be core and not an add-on in the asset library?

My intention is that this would be a potential replacement for the current boolean functions, but it’s not necessary that those functions are removed.

**Comment by Calinou** [comment]
> This function would be called as CharacterBody2D.is_touching(“only”, “floor”); or CharacterBody2D.is_touching(“FLOOR”); as implemented below.

The downside of this approach is that it checks against strings, which is both slower and error-prone. You also don't get autocompletion out of the box - it needs to be specifically implemented in the Godot script editor and won't apply to non-GDScript languages.

**Comment by RedMser** [comment]
Instead of a string API, you could use an enum that is bitwise OR'd together. Such as `body.is_touching(SIDE_FLOOR | SIDE_WALL)`.

But I also don't see this as something necessarily needed in the core API, since it would need more logic to deconstruct these enum values than just returning simple booleans.
