### ISSUE TITLE
Change default renderer to D3D11 for Compatibility Mode on Windows.

### ISSUE THREAD

**Issue by Bonney01** [godotengine/godot-proposals#11211]
### Describe the project you are working on

Godot 4.4 dev4, the default renderer for Compalibility Mode on Windows is as the following:
Use OpenGL 3.3, if not supported, then fallback to ANGLE(D3D11)

Since D3D11 is much faster than OpenGL on Windows, directly use ANGLE(D3D11) as the default renderer instead of fallback to it on Windows.

### Describe the problem or limitation you are having in your project

OpenGL performs bad on Windows.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

D3D11 is much faster than OpenGL on Windows, why not just use D3D11 by default?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Menu bar: Project
Project Settings...->Renderer->gl_compatibility
gl_compatibility change to compatibility
The default render of Compatibility Mode for different platforms:
macOS, Linux: OpenGL 3.3
Windows: D3D11(ANGLE)
Android: OpenGLES(ANGLE)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is a common feature.

### Is there a reason why this should be core and not an add-on in the asset library?

Renderer settings are core features.

**Comment by clayjohn** [comment]
Have you tested performance yet? I'd be very interested in seeing your performance comparison once you do.

**Comment by Bonney01** [comment]
Compatibility Mode, same project, same resolution
1. exported with Godot 4.3 stable, it uses OpenGL renderer by default, CPU usage: 27%, GPU usage: 58%
![Image](https://github.com/user-attachments/assets/d32425e9-e920-4d96-b521-8ce34c13acb2)
2. exported with Godot 4.4 dev4, it fallbacks to ANGLE(D3D11) renderer, CPU usage: 22%, GPU usage: 47%
![Image](https://github.com/user-attachments/assets/90987d52-9fa2-4bce-a573-a2b59e97e024)

**Comment by Bonney01** [comment]
Besides, let's take a look at other engines
Unity: Uses D3D11 renderer on Windows for old GPUs.
GameMakerStudio2: Uses D3D11 renderer on Windows.
Both of them make use of D3D11 and their exported games perform better than Godot(prior to 4.4dev4, Compatibility Mode) on Windows.

**Comment by bruvzg** [comment]
> Since D3D11 is much faster than OpenGL on Windows, directly use ANGLE(D3D11) as the default renderer instead of fallback to it on Windows.

It's exactly opposite, there's no D3D11 renderer (and no plans to ever have it), ANGLE is a translation layer, and it is usually slower (and for complex projects it can be significantly slower, at least on relatively modern NVIDIA GPUs) than native OpenGL. It's only there for GPUs with badly implemented OpenGL (mostly integrated Intel graphics), it might be faster on some old GPUs, but it's primarily intended to workaround various bugs in the GL implementation.

> Use OpenGL 3.3, if not supported, then fallback to ANGLE(D3D11)

There's also a list of old devices with OpenGL 3.3 support which are forced to use ANGLE.

https://github.com/godotengine/godot/blob/f952bfe9985ad8f507cc29b2c7601bbba18b8039/main/main.cpp#L2065

> Unity: Uses D3D11 renderer on Windows for old GPUs.
> GameMakerStudio2: Uses D3D11 renderer on Windows.

In both cases it seems to be D3D11 renderer, not ANGLE.

> Android: OpenGLES(ANGLE)

ANGLE is used only on Windows (can be used on macOS as well, but ANGLE over Metal is causing more issues than fixing, and all the Metal capable macs have OpenGL support).

**Comment by Bonney01** [comment]
I'm not familliar with ANGLE, as you said, ANGLE translated D3D11 is slower in most cases, and there is no plan for a real D3D11 renderer, so I should close this proposal.
