### ISSUE TITLE
Add "Pack Project as ZIP" function

### ISSUE THREAD

**Issue by Meorge** [godotengine/godot-proposals#11233]
### Describe the project you are working on

The Godot editor

### Describe the problem or limitation you are having in your project

When documenting bugs or working on new features, we often want to create a minimal reproduction project (MRP). The [bug report submission form](https://github.com/godotengine/godot/issues/new?template=bug_report.yml) asks for the following:
> A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).

The user must close Godot, delete the `.godot` folder from their project folder (as well as any other hidden/unnecessary files produced by the OS or environment), then zip the folder to produce the ZIP for uploading. While not a *huge* deal, it introduces a bit of friction to the process, which is already an ask for someone who's trying to get their own project finished.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Just as Godot features the "Help" > "Copy System Info" menu item in the editor, I am proposing a "Pack Project as ZIP" function which would combine all relevant project files into a ZIP file, explicitly excluding the `.godot` folder and other user-specific files.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This function could live as a menu option either under the "Project" menu (since it is related to the project as a whole) or the "Help" menu (since it would frequently be used alongside "Copy System Info", when filing a bug report). Clicking it would open a file dialog which would determine where to save the packed project ZIP to. Upon confirming the location, the ZIP would be constructed and placed at that location.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Godot features the [`ZIPPacker` class](https://docs.godotengine.org/en/stable/classes/class_zippacker.html), which constructs ZIP files. I imagine an editor script could be written to recursively move through the project and add relevant files to the target ZIP file. This is something I'm hoping to try myself, as a prototype for how this functionality could potentially be implemented in Godot itself.

By default, an editor script to accomplish this task would pack *itself* into the MRP, which wouldn't be ideal, but I imagine it could include code to explicitly exclude itself.

### Is there a reason why this should be core and not an add-on in the asset library?

By the time someone finds and installs this as an add-on to their MRP, they could likely have just manually removed the `.godot` folder and other unnecessary files from the project themselves. The usefulness of this feature would come with it being built in to Godot so that a user only needs to click a button or two to get what they need. Essentially, I see this feature as going hand-in-hand with "Copy System Info".

**Comment by tetrapod00** [comment]
We might want to either:
- Call it "Export as MRP..." or "Export as zipped MRP..." or similar.
- Put it in the `Project` menu along with `Export...`. Though the `Help` menu also makes a lot of sense.

Downsides might include a slight uptick in users skipping the whole process of *making* an MRP, instead just uploading their existing projects as-is. I suppose that's a good reason to not call it "MRP" in the menu, too.

**Comment by Meorge** [comment]
That's a great point you brought up about it encouraging people to upload whole projects as MRPs. It hadn't crossed my mind before, but now I could certainly see a lot of people doing that... 😅 

I didn't want to specifically name the function "MRP" because I could see other cases where people would want to share projects that weren't MRPs, but also didn't want to include the extra unnecessary files in them. Perhaps avoiding using the phrase "as MRP" in the function name would help with your concern, because users might not be as quick to think that pressing the button "makes it" an MRP?

**Comment by tetrapod00** [comment]
Yeah, I don't think the word "MRP" should appear in the UI after considering the potential downsides.

**Comment by Meorge** [comment]
I've created a GDScript editor script that *seems to* work, from the testing I've done. It has to be named `zip_project.gd` and placed in the root directory of the project. When run, it produces a zipped copy of the project in the same directory as the project's directory itself.
```gdscript
@tool
extends EditorScript

func _run():
    var files: Array[String] = [
        ProjectSettings.globalize_path("res://project.godot")
    ]
    
    var destination := "res://../%s.zip" % ProjectSettings.get_setting("application/config/name")
    
    # Start in the main directory
    var fs := EditorInterface.get_resource_filesystem().get_filesystem()
    parse_subdir(fs, files)
    var success := write_to_zip(files, destination)

    if success:
        print("Zipped successfully!")
    else:
        print("An error occurred...")

func parse_subdir(fs: EditorFileSystemDirectory, files: Array[String]):
    for subdir_idx in fs.get_subdir_count():
        parse_subdir(fs.get_subdir(subdir_idx), files)

    for file_idx in fs.get_file_count():
        var full_filepath := ProjectSettings.globalize_path(fs.get_file_path(file_idx))

        # Don't include this zipping script.
        if fs.get_file_path(file_idx).ends_with("/zip_project.gd"):
            continue

        files.append(full_filepath)
        
        # Handle files with .uid metadata.
        if FileAccess.file_exists(full_filepath + ".uid"):
            files.append(full_filepath + ".uid")
            
        # Handle files with .import metadata.
        if FileAccess.file_exists(full_filepath + ".import"):
            files.append(full_filepath + ".import")

func write_to_zip(files: Array[String], destination: String) -> bool:
    var w := ZIPPacker.new()
    var err := w.open(destination)
    if err != OK:
        print("Error occurred! %s" % err)
    
    var base_path_len = ProjectSettings.globalize_path("res://").length()

    for f in files:
        var relative_path := f.substr(base_path_len)
        w.start_file(relative_path)
        var as_bytes := FileAccess.get_file_as_bytes(f)
        if as_bytes.size() == 0:
            print("Error occurred trying to open file %s: %s" % [f, FileAccess.get_open_error()])
            return false
        w.write_file(as_bytes)
        w.close_file()
    
    w.close()
    return true
```
I could only think of `.import` and `.uid` files, as well as `project.godot`, that would be important to a project functioning, and which `EditorFileSystemDirectory` doesn't recognize on its own. There may be other file types that would have to be added manually, though?

In the coming days I may see if I can adapt this into C++, for a PR to the engine to go along with this proposal 🙂

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/227.
