### ISSUE TITLE
TileSet & TileMap Editor Improvements

### ISSUE THREAD

**Issue by abueide** [godotengine/godot-proposals#1125]
**Describe the project you are working on:**
A project that uses animated tilesets & tilemaps.
**Describe the problem or limitation you are having in your project:**
- The tile map editor's tile picker can get very cluttered and unorganized.
  - Solution (PR #0000): Allow users to filter tiles by the texture that they came from using a TabContainer. Often users will organize their tiles into spritesheets of related tiles, so it makes sense to allow the user to see only tiles from a specific sprite sheet.
- There is currently no way select and place objects that are bigger than 1 tile (e.g. a tree that is 4 tiles, or a house that is 10 tiles).
  - Solution (no pr yet): Instead of using an ItemList for the secondary palette (referred to as manual_palette in tile_map_editor_plugin.h), use the same grid that is used to create atlas regions & auto tile regions inside of the tileset editor. Currently selecting multiple tiles places a single random tile, but the default should be placing all of the tiles. A checkbox would be added to enable the randomization mode instead.

**Comment by KoBeWi** [comment]
The title is almost the same as #896
Closing as duplicate, comment in the mentioned proposal if there's anything missing in there.
