### ISSUE TITLE
Blurry Text changing window scale

### ISSUE THREAD

**Issue by pochoco24** [godotengine/godot-proposals#11268]
### Describe the project you are working on

A Visual Novel with Arial font

### Describe the problem or limitation you are having in your project

When the Project Setting Window>Stretch>Scale is changed, the text looks blurry.

I made a script that changes the scale setting based on the Screen DPI so the text is readable on high-resolution monitors. The font size is 16px. So if the DPI is 125% times the base scale, the font size would be 20px, which is an integer and should not be blurry.

I've tried changing the hinting and sub-pixel positioning properties but it doesn't eliminate the blur.

Right-click and open the images in a new tab to see the blur better.

![Image](https://github.com/user-attachments/assets/e2c2fd0c-dad5-4427-abbe-fbfc29abb84a)
![Image](https://github.com/user-attachments/assets/7f30b9b8-f6cb-4ab6-8a44-62bd52c7b1d6)
![Image](https://github.com/user-attachments/assets/29d6e09f-e789-4c1c-ba01-af64d9aef674)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Maybe adding a way to make the font size independent from Window>Stretch>Scale setting so it can be changed manually?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This may be used often for GUI and text-based games.

### Is there a reason why this should be core and not an add-on in the asset library?

This would fix the blurriness of text, so it should be core.

**Comment by AThousandShips** [comment]
This is for proposals, please report bugs [in the main repo](https://github.com/godotengine/godot/issues/)

Please search for existing issues first, I think this has already been reported

**Comment by Calinou** [comment]
This is already reported here: https://github.com/godotengine/godot/issues/86563
