### ISSUE TITLE
Expose scene directional light data through the compositor effect callback

### ISSUE THREAD

**Issue by BadMachine** [godotengine/godot-proposals#11264]
### Describe the project you are working on

Godot addon that adds realistic sky/post-processing effects.
 

### Scene directional light data

Currently, we can access render scene buffers using the following code:
```
	var render_scene_data : RenderSceneDataRD = p_render_data.get_render_scene_data()
	var scene_data_uniform_buffers: RID = render_scene_data.get_uniform_buffer();
```
However, this buffer lacks crucial light source data, such as directional light direction or color. This limitation forces developers to implement a workaround by manually passing the light data from the outside. Here's the an example of the process:

1) Create a directional light.
2) Set up a resource that creates a uniform buffer and updates it whenever the light attributes (e.g., direction, color) change.
3) Pass this resource into your CompositorEffect and initialize a uniform set for the buffer.
4) Use the buffer inside your compute shader.

This approach places the entire responsibility of managing light data on the developer, which is inefficient and error-prone. For a practical implementation example, you can refer to this excellent [Godrays implementation](https://github.com/BastiaanOlij/RERadialSunRays/blob/master/radial_sky_rays/radial_sky_rays.gd)

### Shadow  Atlases
Another critical issue is the inability to access shadowmaps (shadow atlases) within post-processing compute shaders. While the compositor hook provides access to render scene buffers and their layers:

```
	var render_scene_buffers : RenderSceneBuffersRD = p_render_data.get_render_scene_buffers()
	var color_image = render_scene_buffers.get_color_layer(view);
	var depth_image = render_scene_buffers.get_depth_layer(view);
	var motion_buffer = render_scene_buffers.get_velocity_texture();
```
Shadowmaps remain inaccessible, which severely limits advanced rendering effects. For example, it is impossible to exclude Mie scattering effects in atmospheric rendering without sampling the shadowmap:
![Image](https://github.com/user-attachments/assets/dc1042a4-669d-4f62-9d63-baf1a8128a0c)

Why These Features Are Critical
Both directional light data and shadow atlas access are fundamental for modern visual effects in rendering pipelines. Without these, developers are forced to create custom, resource-intensive solutions to work around these limitations. Exposing this data directly to compositor effects would:

- Simplify workflows.
- Enhance rendering performance.
- Enable higher fidelity visual effects like accurate atmospheric scattering, godrays, and shadow-based post-processing.

By addressing these issues, Godot’s rendering pipeline would become significantly more robust and developer-friendly.

I know that there is a separate PR for [shader templates](https://github.com/godotengine/godot/pull/94427) but as I understand its related to the gdshader only

There is also another PR with [shader includes](https://github.com/godotengine/godot/pull/94193) and I cant wait to finally get it, but it's not related to exposing light data.

### Exposing Directional Light Data to Compositor Effects
Add a mechanism to directly expose directional light attributes (e.g., direction, color, and intensity) to the compositor effects. This could involve integrating the light data into the existing uniform buffers or providing a dedicated API for accessing light sources within the RenderSceneDataRD object.

### Shadowmap (Shadow Atlas) Access for Post-Processing
Allow access to shadowmaps (also known as shadow atlases) within the compositor framework. This can be achieved by exposing the shadowmap textures through the RenderSceneDataRD interface, similar to how color, depth, and motion layers are currently handled.

### Directional Light Data

```
 var scene_light_uniform_buffers: RID = render_scene_data.get_light_buffer();
```

### Shadowmap (Shadow Atlas)

```
var shadow_atlass = render_scene_buffers.get_shadow_atlass();
```

### Directional Light Data
Yes, it can be worked around with quite many lines of code :) Which as I explained above is not efficent and practically comfortable way.

### Shadowmap (Shadow Atlas)
Unfortunatelly there is no option to work this around with script.

### Is there a reason why this should be core and not an add-on in the asset library?

I assume the reason is the Compositor itself. It has been developed as solution for post processing effects.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/8872.

**Comment by BadMachine** [comment]
@Calinou
I played with my local build a bit and extended scene buffers with desired data
![Image](https://github.com/user-attachments/assets/705e0c30-1ba2-4ed0-a145-6bae8a6c84f8)

Here is the exposed directional light buffer 
```
RID RenderSceneDataRD::get_directional_light_buffer() const {
	return RendererRD::LightStorage::get_singleton()->get_directional_light_buffer();
}
```
Looks like kinda easy to implement.

But since there is a separate light_storage class, im not sure if it could be a part of the render_scene_data

**Comment by BastiaanOlij** [comment]
@BadMachine it was always my intention to expose more of the buffers used during rendering to compositor effects. #94193 is a first step in that process so you can include the structures Godot uses internally. Exposing the RIDs of the buffers is a next step.

**Comment by BadMachine** [comment]
@BastiaanOlij
Thank you for your reply.
I kinda ready to close the proposal :) But before doing it, is there any ETA on the feature? I mean at least we know that "shader includes" is a feature planned for 4.4, but what about buffer RIDs?

**Comment by BastiaanOlij** [comment]
> [@BastiaanOlij](https://github.com/BastiaanOlij) Thank you for your reply. Im kinda ready to close the proposal :) But before doing it, is there any ETA on the feature? I mean at least we know that "shader includes" is a feature planned for 4.4, but what about buffer RIDs?

Hard to say at this point in time, my focus currently is on a few XR tasks so it's a question of when I find a bit of free time to take the next steps (and that will first be rebasing and touching up the custom templates work). Right now I'm waiting for the built-in includes PR to be merged, it's a royal PITA to maintain multiple PRs that are all dependent on another PR.

**Comment by BadMachine** [comment]
Related to https://github.com/godotengine/godot/pull/100710
