### ISSUE TITLE
Inverted Y Sort

### ISSUE THREAD

**Issue by RamirezAllan791** [godotengine/godot-proposals#11271]
### Describe the project you are working on

A game where the player can place items in the shelves

### Describe the problem or limitation you are having in your project

I'm using a [linear perspective](https://finearttutorials.com/wp-content/uploads/2022/11/Orthogonals-1-1-1024x768.png) to draw the room and the shelves, and I am using Y-sort to render the closest items in front of the ones that are farther away. It works perfectly below the horizon line, but creates the opposite effect above the horizon.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the ability to choose to rendered nodes with a lower Y position in front of nodes with a higher Y position (the option to use it also in the reverse way of how it is currently done).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add an extra property here (in the CanvasItem->Ordering tab) where Z-Index, Z-as-relative and Y-Sort are located. I imagine it like a boolean/checkbox which only be available when Y-Sort is enabled and this property will define which CanvasItems will be rendered in front: those with a lower Y position or those with a higher Y position.
![Image](https://github.com/user-attachments/assets/e23ac031-7ee1-438d-b742-43c6386f8acb)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I have not tried yet, but it can be worked around changing the z index of the different canvas items based on their **position.y** value

### Is there a reason why this should be core and not an add-on in the asset library?

The code for rendering CanvasItem nodes with a higher Y position in front of nodes with a lower Y position already exists. I think adding a statement to render in the opposite order would work better where the existing code is located, instead of creating a different module, which could cause issues.

**Comment by RamirezAllan791** [comment]
I know that the Y-Sort property is replacing Y-Sort nodes and is currently in an experimental version. I hope this idea can help refine the concept of the Y-Sort rendering feature. 
I would also like to contribute code to the Godot engine by implementing that functionality. How can I go about doing that? How can I get started?

**Comment by AThousandShips** [comment]
This is already tracked in:
* https://github.com/godotengine/godot-proposals/issues/7015

Please continue the discussion there, thank you for your proposal

**Comment by RamirezAllan791** [comment]
Thanks @AThousandShips !
