### ISSUE TITLE
Extra Visual Script Commands

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#1128]
**Describe the project you are working on:**
VS->GDScript (and the other way around, however the other way around doesn't need this) converter

**Describe the problem or limitation you are having in your project:**
[_Obtaining Nodes is unreliable_] and getting data off those nodes is a pain

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add 2 properties of a Visual script, [_1 would be the number of nodes in the script_], and the other would be a dictionary of nodes that contains the following data on any given node: 
1)A list of Inputs (if it has inputs, same goes for outputs) that has data on what is plugged into inputs of the node
2)A list of Outputs it has connected that also has data to what nodes & node ports it is connected to
3)Node Class (like VisualScriptBuiltinFunc, VisualScriptFunctionCall etc.)
4)Node Name (like "add_child()", "print()" etc.)

1 and 2 would have the lengths of the number of input/output ports they have, and have the value null if they aren't connected

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
1.When a node is created, add to list of Nodes
2.When a node is changed (aside from moving, so changes like node change, some connection change) update relevant data for the node

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
[_only partly, as there is no way to get the number of nodes in a Visual Script, it's impossible to be sure if all the nodes have been collected because in order to get them you have to put an iterator to get nodes and save just what returns true because for some reason node lists can be sorted like "0,1,5,6,18,19..." and if you tried to use while it'd end after trying to see if node 2 exists which it doesn't but there are nodes past it_], as far as the data collection goes it can be for the most part built from the current VS it's just a very complicated process

**Is there a reason why this should be core and not an add-on in the asset library?:**
[_An addon would be impossible to make for this without the same limitations of the project that i'm working on, which is the problem with getting the actual number of nodes in the current VS implementation._]

Edit: you can ignore anything i put in brackets and italic now, In 3.2.2 that is no longer an issue

**Comment by Jummit** [comment]
This would be partially solved by adding a way to get the visual script GraphEdit to EditorInterface.

**Comment by mrjustaguy** [comment]
Aaand i think i can undo my edit, as apperently the method i found in 3.2.2 isn't perfect, as it seems that the actual issue with nodes is when you delete a node, the node id gets a gap resulting in more or less the same issue i've had before that needs the total number of nodes to solve...

**Comment by mrjustaguy** [comment]
Update: ok seems like all the data can be obtained by just running **LoadedVisualScript**.get("data"), something that isn't written in the VS documentation at all making it seem as if it were unaccessable when in reality it's just hidden...
