### ISSUE TITLE
Add `OS::get_version_alias()`

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot-proposals#11292]
### Describe the project you are working on

Reporting https://github.com/godotengine/godot/issues/100055

### Describe the problem or limitation you are having in your project

Especially on Windows 11, the system info Godot offers when selecting _Help → Copy System Info_ is misleading, as `Windows 10.0.22631` in reality means Windows 11, not Windows 10.

It stems from the use of `OS::get_version()` as the sole OS identifier.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`OS::get_version_alias()` would return these values when called on different systems.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

| Alias | Pseudo-rule of `OS::get_version()` |
| :---: | :---: |
| Windows 11 | `>= 10.0.22000` |
| Windows 10 | `< 10.0.22000` |
| Windows 8 | `>= 6.2.9200` |
| Windows 7 | `< 6.2.9200 && >= 6.1.7601` |
| Windows Vista | `< 6.2.9200` |
| macOS Sequoia | `>= macOS 15.0.0` |
| macOS Sonoma | `< macOS 15.0.0 >= macOS 14.0.0` |

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as it's a new API and needs to work in the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

Needs to be in the editor.

_Edit: Updated macOS to show their names._

**Comment by bruvzg** [comment]
> Does macOS need special handling here?

Only if we translate it to names instead of numbers: 15.x.x → macOS Sequoia, 14.x.x → macOS Sonoma, and so on.

**Comment by adamscott** [comment]
> This method should also list the Windows update, as it's relevant to many issues. For instance, Windows 10 1903 or Windows 11 24H2. Insider builds will have "unknown" build numbers, so their build number should be listed directly instead.

We could have `OS::get_sub_version_alias()` that returns `1903`, `24H2`, or `15.1`.

**Comment by adamscott** [comment]
I mean, we should absolutely copy something like "`OS::get_version_alias()` (`OS::get_version()`)" when clicking on _Help -> Copy System Info_.

**Comment by adamscott** [comment]
We could inspire ourselves from [what Python does](https://docs.python.org/3/library/platform.html).

| `platform` method | Return value |
| :---: | :---: |
| `mac_ver()` | `('15.1.1', ('', '', ''), 'arm64')` |
| `win32_ver()` | `('11', '10.0.22631', 'SP0', 'Multiprocessor Free')` |
