### ISSUE TITLE
Data Duplication Philosophy Change

### ISSUE THREAD

**Issue by TylerSwan** [godotengine/godot-proposals#11306]
### Describe the project you are working on

The way Godot handles data duplication has cropped up in every project I've worked on with the engine. Data duplication is an extremely common feature of other engines that is less efficient for good reason, it makes life so much easier for the developer. 

I've managed several workarounds but these require extra work for the developer to trick the engine into making a duplicate and create a ton of overhead for maintainability when expanding features as the duplication workaround code needs to be updated as well.

The "Make unique" toggle on many resources either doesn't work in most contexts I've tried them which I'll detail below, but the default should be unique instances not references. If I need the efficiency let me turn off uniqueness.

**Card Game:**
It is a common practice to take a base instance of a card or enemy and create a duplicate of it so we can affect them individually. A very useful structure for this is to have resources for cards and enemies, then create a duplicate of them so we can modify them at runtime while preserving the base.

**Top Down Tactics** (Think Xcom)
This game is making use of the gridmap to quickly and easily generate levels on a grid which subsequently makes it easy to generate movement grids ontop of the level that synch up using the gridmap mesh positions. This game

### Describe the problem or limitation you are having in your project

**Card Game**
- When a Goblin takes damage they all take damage because they are all the same goblin.
    - This occurs even with "local to scene" turned on as my enemy resources all exist in a single array of enemies in a given encounter and are thus in the same scene, and then I have have visual elements instantiated into the scene that connect to the resource when the enemy is present.
- Player cards use the same function, they are resources that exist in a single script that manages the players deck and are thus considered to be in the same scene. When drawing cards we instantiate a visual template and connect it to the players cards.

**Top down Tactics**
- GridMap objects are all mandatory instances of a single mesh library object reference. Turning on "Local to scene" does nothing for the mesh library object nor for it's materials.
    - This makes occlusion culling grid map layers in a 3D game impossible, as occluding one grid object will occlude every single object that shares the library reference.
    - The GridMap also seems to chop off a lot of the data about an object in each cell, and provides extremely limited information about the objects in a given cell instead of simply referencing the entire scene and allowing a user to interact with each cell as a scene as they would normally. This prohibits simple and common behavior like cells that would deal damage to the player when walked over.
- Unit instantiation has the same issues as with **Card Game**.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rework everything in the engine that needs to be re-worked with regards to allowing the player to duplicate data on command. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It's not so much a new feature as a change in core function. Any Node.Duplicate() or Resource.Duplicate() function should just actually duplicate the object. GridMap objects should be unique instances of a scene. I'm sure other examples exist that I've not personally seen or encountered.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The only workaround I've found is instantiating a new version of the base resource that doesn't exist yet, then manually copying all variables from the duplicated resource to the new one. With every change that is made to any object that needs to be duplicated changes to the duplication code are thus required and this is the only workaround I've managed to find through forums and tutorials.

### Is there a reason why this should be core and not an add-on in the asset library?

You can barely look up any tutorial on "data driven game design" without the liberal use of data duplication. It's an incredibly powerful and flexible way to design games that is common practice with other engines. Godot clearly recognizes this with the addition of the "Local to scene" toggle but that just isn't good enough and creates the opportunity for that toggle to simply fail in edge cases because the engine isn't designed to accommodate it.

Look up "Godot resource duplication" or "Godot node duplication" and just about all you will find are people who are confused about why this isn't Godot's default functionality. It's literally every result on the first page aside from Godot's documentation as I write this. 

I'm only so plugged into the community but my personal experience is exclusively that nobody wants Godot's data duplication philosophy to be what it is. Figured I'd post this and see if people actually agree.

**Comment by KoBeWi** [comment]
Related: https://github.com/godotengine/godot-proposals/issues/9603

**Comment by AThousandShips** [comment]
I would personally not expect duplication to duplicate resources, they are shared by design

I'm not sure using resources in this way to track enemy data and just duplicating them makes sense to begin with, resources aren't necessarily designed to be used for instance specific data

**Comment by Calinou** [comment]
- Superseded by https://github.com/godotengine/godot-proposals/issues/11312.
