### ISSUE TITLE
Allow variable paths in preload

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1130]
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
I have to use `match` (`if` would be the same)
![Screenshot (89)](https://user-images.githubusercontent.com/60623532/85944183-2007aa80-b935-11ea-9648-98397aed7360.png)

![Screenshot (88)](https://user-images.githubusercontent.com/60623532/85944182-1f6f1400-b935-11ea-90d2-a5a3895a7f60.png)
for instancing the right level.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
You could preload a scene with a path in which char(s) are different.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
instead of just preloading with one single line: `var level = preload("res://Levels/Level"+str(SceneChanger.level_number)+".tscn").instance()`
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Exactly this can't but the use can **but** there would be many lines if you have very much Levels.
**Is there a reason why this should be core and not an add-on in the asset library?:**
I think, it can't be an add-on.

**Comment by pycbouh** [comment]
`preload` only works when it can be determined what is being loaded beforehand, before any execution context exists. Your example should use `load`, it allows paths generated at runtime.

**Comment by MaaaxiKing** [comment]
But how can I instance something with `load()`? And OK it would be better if I placed the `preload` over `_ready()` or rather before `_ready()`.

**Comment by pycbouh** [comment]
You instance with `load` the same way you do in your proposed example with `preload`. Both methods return you a resource, or a scene, or a script. You use them in the same way. The difference is explained [in the docs](https://docs.godotengine.org/en/stable/getting_started/step_by_step/resources.html?highlight=preload#loading-resources-from-code).

**Comment by MaaaxiKing** [comment]
But `instance()` is not suggested on `load`.

**Comment by pycbouh** [comment]
Because `load` cannot be statically analyzed to guess which type of resource you are loading. That's the difference between the too: `preload` relies on complete paths to determine at compile-time what kind of resource it is; while `load` can only know about it at runtime.

It doesn't matter what code completion tools do or don't suggest you. They are only assisting you as much as they can, but they cannot replace your own understanding of what is your code supposed to do.

**Comment by KoBeWi** [comment]
You can use casting (`as`) for load if you want type safety and autocompletion.

That said, load is the method to use for non-static paths and this won't change. The proposal came from wrong understunding of preload.
