### ISSUE TITLE
Add a Process Mode or inherited property to block input but allow physics/animation for cutscenes and transitions

### ISSUE THREAD

**Issue by michaelLochlann** [godotengine/godot-proposals#11307]
Note: This is for making the core/default functionality more powerful/easier.
I know there are other ways to do this - but I believe this would be the simplest and most elegant option if added as an enhancement.

### Describe the project you are working on

Anything where you would want to block input but still play animations. 
State transitions, cutscenes. 

Example:
State machine for game mode
Game Mode - Title
Game Mode - Gameplay 

Press Space on Game Mode Title to go to Game Mode Gameplay.
Just switching instantly looks bad, so have a 3seconds fade in and fade out. During this fade out, block input but still draw the animations.   

Alternatively: you are making any game with a cutscene where the characters move around but are no longer controlled by the player.

There is no PROCESS_MODE or inherited Allow Input to do this, so we have to code it ourselves and handle the recursion ourselves, and also keep track of process mode and input blocking separately.

### Describe the problem or limitation you are having in your project

PROCESS MODE's functionality is exactly what I'm looking for and is easy to understand - however there is no option in it to block input and still run graphics, so you have to code that outside of process mode and manage both process mode and input blocking separately.  And basically recreate the process mode recursion logic specifically to run a cutscene or scene transition.  

Also, changing process mode is one line whereas doing the above is several lines and you would need to add that to any classes you wanted to use it for rather than applying it as part of the default Node class.

If we are not wanting to touch Process mode due to the pausing, then maybe we could add another property that is inherited on nodes specifically for allowing input.  Built into the node class and automatically having recursion from parent.  in that case it could be INPUT_ENABLED (default) and INPUT_DISABLED 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a new process mode.
I would call it PROCESS_BLOCK_INPUT.
it would still run the process functions but not the input functions.
to resume you can just use the existing PROCESS_PAUSABLE or PROCESS_ALWAYS as they both run input.

Right now if you want to do that in the same way that you do process mode, you have to do it separately and write a recursive function etc.  It's also a bit confusing/PITA to have to manage the two separately (process mode vs input).  For something we will need to do a lot (you never want to take additional input when switching between game modes) it seems like a nice to have to build in.

If we are not wanting to touch Process mode due to the pausing, then maybe we could add another property that is inherited on nodes specifically for allowing input.  Built into the node class and automatically having recursion from parent.  in that case it could be INPUT_ENABLED (default) and INPUT_DISABLED 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

process, physics_process = run as normal

input, unhandled input, etc. = do not run (block as if it was process mode DISABLED)

have it be recursive to children just as other process nodes (this is the main benefit of using process mode vs just coding it yourself.)
yes, we can code our own recursive function (and I did) but it took me about a week of research as a new Godot developer to figure this out - it is not intuitive - and I think it would be useful to everybody to be built in so that it's one line of code in one place that is built into every node by default.

If we are not wanting to touch Process mode due to the pausing, then maybe we could add another property that is inherited on nodes specifically for allowing input.  Built into the node class and automatically having recursion from parent.  in that case it could be INPUT_ENABLED (default) and INPUT_DISABLED 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think it would be used often, particularly in games with a lot of cutscenes, animations, or presentation polish. 

It would probably just be a copy paste of an existing process mode file with a couple of adjustments to block the inputs.  So I don't think it is a ton of work compared to how useful it would be.

Yes, you can work around it with recursion to get children and set input handled, but that's what process mode is already supposed to do, is set how the node's children should handle game loop events.  So I think it makes sense to bake this in rather than having to code extra things specifically for when you need rendering and not input.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving how we manage which nodes are running which game loop functions and giving us a bit more flexibility, making process mode more powerful.

**Comment by Zireael07** [comment]
Simple workaround: put an invisible fullscreen control that blocks all input.

**Comment by AThousandShips** [comment]
How would this be different from just disabling input processing? Using [`set_process_input`](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-set-process-input) etc.?

**Comment by michaelLochlann** [comment]
@AThousandShips it's not recursive meaning you have to add a script to each node you want to do this for, which then means it's not baked in functionality for nodes.  That's also not as elegant as using process mode.

@Zireael07 yes, there maybe other ways to handle this, but that feels like a "hack" and I think this sort of thing is exactly what PROCESS MODE would be useful for and can be done in code rather than by adding additional nodes.  You can also code your own pause system but godot has provided one for us because it's something games need to do all the time.  I'd actually argue that cutscenes are done more often than pausing.

**Comment by Zireael07** [comment]
Having another process mode is not an improvement IMO. Process modes and input passing is already a source of a lot of confusion and there are efforts underway to streamline it, and this would only add complexity for little gain

**Comment by michaelLochlann** [comment]
Something like this might help with the streamlining and is how I set mine up -

A recursive property for Input - InputMode
Allow_Input {
INHERIT
,ALWAYS
,WHEN_NOT_PAUSED
,WHEN_PAUSED
,NEVER
}

Process Mode (as is) but maybe with clearer name
 {
INHERIT
,ALWAYS
,WHEN_NOT_PAUSED
,WHEN_PAUSED
,NEVER
}

A property to say whether the node is paused or not. Currently it's on get tree paused but it might help to be able to see it in the inspector
Pause_Mode {
PAUSED
,NOT_PAUSED
}

All 3 of these could go where Process Mode currently is on the inspector

Anyway I'll be handling it the way I want with an autoload going forward but, regardless of how it's done, I think Godot needs an easier built-in way to handle cutscenes and pausing during animations.

**Comment by Calinou** [comment]
> and also requires programming a recursive function to go through the scene tree which will throw a beginner for a loop

This is trivial with `Node.find_children()`, which works recursively by default:

```gdscript
for node in find_children("", "ClassName"):
    node.do_something()
```

**Comment by michaelLochlann** [comment]
whatever
