### ISSUE TITLE
FileAccess should support reading and writing half floats

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#11315]
### Describe the project you are working on

File loader for npy data type

### Describe the problem or limitation you are having in your project

I need to be able to read half float (ie, two byte floating point values) from a binary file.  At the moment, FileAccess supports reading floats and doubles, but not half floats.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Extra methods will allow for more complete binary file access.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add extra methods for dealing with the half float data type.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Requires changing FileAccess

**Comment by bruvzg** [comment]
It is already supported in 4.4:

https://github.com/godotengine/godot/blob/aa8d9b83f66488dbb2c9c918e9016ef80f821fb4/core/io/file_access.cpp#L930
https://github.com/godotengine/godot/blob/aa8d9b83f66488dbb2c9c918e9016ef80f821fb4/core/io/file_access.cpp#L949

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/97716.
