### ISSUE TITLE
Notify about new versions of Godot in Project Manager

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot-proposals#1132]
**Describe the project you are working on:**
This is unrelated to proposal

**Describe the problem or limitation you are having in your project:**
I don't have any problems with it, because I'm up to date with the newest Godot versions. 
Some people use Godot versions downloaded from site, which is easy but after time this version may become outdated.
Of course there is Steam and Linux package managers which provide auto updates, but still not everybody have it.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding popup/info would help users to use the latest available versions of software.
Some of issues which they had, could be fixed in later versions of Godot.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

There should be a button "Check for updates" off by default(like vnen said, Godot should not connect to internet without user knowledge).

![ver](https://user-images.githubusercontent.com/41945903/44196972-b9f94c00-a13d-11e8-91fe-cf82c3821d1c.png)

or

![vvv](https://user-images.githubusercontent.com/41945903/44226042-539d1980-a18f-11e8-832b-de31ec753f28.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't thing so.
It should be used rather often by all users.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't think that is possible to use addon in project manager.

**Comment by KoBeWi** [comment]
> off by default(like vnen said, Godot should not connect to internet without user knowledge).

Or there could be prompt upon first run asking if automatically check for updates.

**Comment by Calinou** [comment]
> Or there could be prompt upon first run asking if automatically check for updates.

Since this is a rarely used feature, I wouldn't bother asking the user about it. Just add a button that can be clicked to check for updates.

**Comment by KoBeWi** [comment]
Well, GIMP added auto-checking recently and it asks you on first run IIRC. The button has to be placed in some obviously visible spot, otherwise users will miss it.

**Comment by I7SOD** [comment]
@KoBeWi what about next to the exit button underneath all the projects I guess that's easy to see

**Comment by Calinou** [comment]
@I7SOD Putting a non-desctructive action button right next to a "destructive" action (quitting the project manager) is an UI antipattern. I wouldn't do it.

**Comment by I7SOD** [comment]
@Calinou yeah you are right

**Comment by Calinou** [comment]
I have a WIP branch here: https://github.com/Calinou/godot/tree/project-manager-check-for-updates

I don't know if the Godot website has a JSON endpoint that contains the latest version and release date though.

**Comment by anderlli0053** [comment]
Ok, so will this be implemented or not?? What is going on right now? , what is the status??

**Comment by Calinou** [comment]
> Ok, so will this be implemented or not?? What is going on right now? , what is the status??

It will likely be implemented, but I can't guarantee it.

**Comment by jordanlis** [comment]
If this functionnality will be developed, I would like make some hilights : 

- Yes, it is dangerous to update the engine regarding a project. But I think that there is no difference in saying directly to the user that an update is available or letting him search directly on the web. The only difference is that we just tell him that he can do it, but it won't be done automatically. He has to accept/refuse it. This functionnality will not change the fact that users know that it could break their project.
- However, I think that if it's implemented, we should tell the user what kind of update it is : will it break compatibilities with his version for sure, or is it more or less safe to accept the update ? We need to give him some insights on wether he should do this update or not.

**Comment by mhilbrunner** [comment]
Some points:
> I don't have any problems with it, because I'm up to date with the newest Godot versions.
Some people use Godot versions ... but after time this version may become outdated.

Proposals are IMO best for features you, yourself actually need or see a very widespread demand for.
I'm not sure "people running years old versions of Godot just because they don't know better" is actually a huge problem. This is a technical product for a technical audience, not consumer software.

Also, updating your game engine mid-project should be a very thoughtful, deliberate choice.

With that said, adding a "Is there a new update available?" check button would be good, I guess.

**Comment by jordanlis** [comment]
I agree with you. 
Just another thing I just noticed is the way [Hourglass](https://hourglass.flyingpimonster.net/) is allowing the customer to manage different versions of godot in the project manager regarding his different project. I think it's a nice to have feature which would complete the "auto-update" big feature. It is worth considering at some point if this first feature will be  developed.

**Comment by me2beats** [comment]
the dialog could be also available from Editor dropdown menu (Debug, `Editor`, Help)
