### ISSUE TITLE
Add more options for WearOS

### ISSUE THREAD

**Issue by kopeek** [godotengine/godot-proposals#11357]
### Describe the project you are working on

I was working on a 3D game on Smartwatch, It was working fine, but ther was one REALLY big problem

### Describe the problem or limitation you are having in your project

My smartwatch and many others, have this feature "swipe to dismiss", that when you swipe from left to right it closes the app, A lot of games I played on Smartwatch have this feature disabled. But I can't disable it on my Godot game

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It is essential for games, because this feature "swipe to dismiss" is limiting a lot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I just want a check box like for (Rotaty Input support) in the Project Settings, or a clear tutorial on Godot Tutorials website on how to disable "swipe to dismiss"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Maybe a plugin, but should be in the Project settings

### Is there a reason why this should be core and not an add-on in the asset library?

It is about supporting Android devices and making Godot more accesible for variety of devices

**Comment by Calinou** [comment]
Have you tried disabling **Auto Accept Quit** in the Project Settings?

**Comment by kopeek** [comment]
I don't think it will because (because ther is an animation before quitting) I can test but I have to reinstall Android etc

**Comment by kopeek** [comment]
> Have you tried disabling **Auto Accept Quit** in the Project Settings then exporting the project again? See [Handling quit requests](https://docs.godotengine.org/en/stable/tutorials/inputs/handling_quit_requests.html) in the documentation.

I tried and testes on Android Virtual Machine, doesn't work :(

**Comment by kopeek** [comment]
YES YES FINALLY WITH THE HELP OF CHATGPT AND A LITTLE BIT SEARCHING I FOUND IT.

@Calinou Please look at this :)

You need to use Gradle build for this.
1. edit themes.xml file it is in **android\build\res\values**
2. add `<item name="android:windowSwipeToDismiss">false</item>` to GodotAppSplashTheme

Before:
`
<?xml version="1.0" encoding="utf-8"?>
<resources>

	<style name="GodotAppMainTheme" parent="@android:style/Theme.Black.NoTitleBar"/>
		

	<style name="GodotAppSplashTheme" parent="Theme.SplashScreen">
		
		<item name="android:windowSplashScreenBackground">@mipmap/icon_background</item>

		
		<item name="windowSplashScreenAnimatedIcon">@mipmap/icon_foreground</item>

		
		<item name="postSplashScreenTheme">@style/GodotAppMainTheme</item>
	</style>
</resources>

`

after:
`
<?xml version="1.0" encoding="utf-8"?>
<resources>

	<style name="GodotAppMainTheme" parent="@android:style/Theme.Black.NoTitleBar"/>
		

	<style name="GodotAppSplashTheme" parent="Theme.SplashScreen">
		
		<item name="android:windowSwipeToDismiss">false</item>
		<item name="android:windowSplashScreenBackground">@mipmap/icon_background</item>

		
		<item name="windowSplashScreenAnimatedIcon">@mipmap/icon_foreground</item>

		
		<item name="postSplashScreenTheme">@style/GodotAppMainTheme</item>
	</style>
</resources>`

**Comment by Calinou** [comment]
cc @syntaxerror247

What's the behavior of this option on smartphones/tablets?

**Comment by syntaxerror247** [comment]
This should be in AppMainTheme:
```xml
<style name="GodotAppMainTheme" parent="@android:style/Theme.Black.NoTitleBar">
	<item name="android:windowSwipeToDismiss">false</item>
</style>
````

The `android:windowSwipeToDismiss` attribute will be ignored on regular smartphones, so it should be okay to include it in theme. But I will recommend to only add this when you are targetting wearOS.

**Comment by syntaxerror247** [comment]
This should be in AppMainTheme:
```xml
<style name="GodotAppMainTheme" parent="@android:style/Theme.Black.NoTitleBar">
	<item name="android:windowSwipeToDismiss">false</item>
</style>
```

The `android:windowSwipeToDismiss` attribute is ignored on regular smartphones, so including it in the theme will not cause any issues. However, it is recommended to add this attribute only when targeting Wear OS, where it is relevant.

**Comment by syntaxerror247** [comment]
I considered implementing this as a checkbox in Export Settings to toggle the behavior. However, this solution would only apply to the Gradle build and would be tricky to support for the normal export. Therefore, I believe the best approach is to handle it manually. 
I’ll open a PR to add documentation for this in the Export tutorial doc.

**Comment by kopeek** [comment]
Thanks

**Comment by kopeek** [comment]
> This should be in AppMainTheme:
> 
> <style name="GodotAppMainTheme" parent="@android:style/Theme.Black.NoTitleBar">
> 	<item name="android:windowSwipeToDismiss">false</item>
> </style>
> The `android:windowSwipeToDismiss` attribute is ignored on regular smartphones, so including it in the theme will not cause any issues. However, it is recommended to add this attribute only when targeting Wear OS, where it is relevant.

True It now working good, before that fix, it wasn't leaving the app but the Input was being catched by that and that was annoying
