### ISSUE TITLE
Add Preview for UI Styles

### ISSUE THREAD

**Issue by josephsmithberger** [godotengine/godot-proposals#11366]
### Describe the project you are working on

I'm creating a noise editor that heavily relies on the UI/Control nodes. It uses sliders, buttons, labels, text inputs, spin boxes, check buttons, and drop-down menus. <img width="300" alt="Image" src="https://github.com/user-attachments/assets/03bb6c70-4438-442c-bf91-0f1f6be79b6a" />

### Describe the problem or limitation you are having in your project

When editing styles that are not currently displayed it's not possible to immediately see the changes you are making. If I were to mess with the hover style I'd have to run my project and hover over the button for every change. A reasonable work around is doing everything in the normal state then copying over.; however if you were to come back later it's unnecessarily tedious. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an option to the right click menu that allows you to preview the changes. Clicking this will change the node to whatever state is specified to preview changes. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Right click the style to bring up "Preview" option. Clicking this will change the node to whatever state is specified to preview changes. The preview will be discarded everytime its saved or another style is previewed. <img width="301" alt="Image" src="https://github.com/user-attachments/assets/e34a2b5e-9224-48fd-ab39-8b2d64006c45" />

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You could try running the editor and imposing the state (ie hovering, hover pressed, etc).

### Is there a reason why this should be core and not an add-on in the asset library?

This is a simple quality of life adjustment that could speed up Ui workflows.

**Comment by KoBeWi** [comment]
That's what Theme editor is for.
