### ISSUE TITLE
Converting code to correct code in the Script Editor

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot-proposals#11372]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

Sometimes it happens that we copy GDScript from third-party sites and resources, where the correct tabulation in the code is not provided, even if visually everything looks correct, for example, if you copy the GDScript code from ChatGPT and paste it into Godot, many errors will appear, even if they do not appear, then with further editing of the code, the error will still be detected.

Code copied directly from ChatGPT:
```
func find_farthest_object(origin: Vector2, group_name: String) -> Node2D:
    var farthest_object = null
    var max_distance = -INF  # Начальное значение - минус бесконечность
    
    # Перебираем все узлы в группе
    for obj in get_tree().get_nodes_in_group(group_name):
        if obj is Node2D:  # Убедимся, что узел имеет позицию
            var distance = origin.distance_to(obj.global_position)
            if distance > max_distance:
                max_distance = distance
                farthest_object = obj
    
    return farthest_object
```
![Image](https://github.com/user-attachments/assets/5c470138-3b2a-4040-9f63-e412e27eb4d1)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It is worth adding a new item to the drop-down menu in the script editor to bring the code into the correct form, for example, in the same way as it happens when converting code into a comment, or when adding tabs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When running this function, you will most likely need to count the number of spaces after each `'\n'`, i.e. at the beginning of each line, and replace every 4 spaces with tabs.
![Image](https://github.com/user-attachments/assets/41337b8b-050f-4729-931a-5d4bc93a7b87)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

A convenient feature that improves the quality of inserting code into the code editor

**Comment by AThousandShips** [comment]
Doesn't `script_text_editor/convert_indent_to_tabs` or `script_text_editor/convert_indent_to_spaces` work for this?

**Comment by JekSun97** [comment]
> Doesn't `script_text_editor/convert_indent_to_tabs` or `script_text_editor/convert_indent_to_spaces` work for this?

Oh... This is what I needed! I didn't find this before, thanks!

**Comment by Calinou** [comment]
Regarding performing this automatically on paste, see https://github.com/godotengine/godot-proposals/issues/3525.
