### ISSUE TITLE
SpinBox rework

### ISSUE THREAD

**Issue by Sloyd** [godotengine/godot-proposals#11395]
Im working on an editor with heavy use of SpinBoxes.

The SpinBox is pretty broken. It has a lot of issues:
1. FocusMode does nothing.
2. It doesnt fire a `ValueChanged` signal when you go about your business (like when you click somewhere else while the Spinbox is focused)
    I think every editing elemets like SpinBox or LineEdit and so on should lose focus when you click anywhere outside of them.
4. It has [this](https://github.com/godotengine/godot/issues/99349) bug that it fires a `ValueChanged` signal when the focus is released from its `LineEdit`
5. It should lose focus after submit
6. If `update_on_text_change` is true, editing the text becomes impossible. You cannot delete all digits. you cannot write the minus character. You cannot write the dot character (I think it was reported [here](https://github.com/godotengine/godot/issues/100620)). If maxvalue was exceeded, and you try to select all and rewrite the value, the text doesnt change..

I'm not so fluent in C, but I made a working Spinbox in a C# godot project:

[spinner.zip](https://github.com/user-attachments/files/18209277/spinner.zip)
I made it quickly so its not perfect, but it is waay more pleasant to work with.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
