### ISSUE TITLE
Support multiple .NET5 SDK-style projects per Godot project

### ISSUE THREAD

**Issue by GeorgeS2019** [godotengine/godot-proposals#1141]
**Describe the project you are working on:**
As project complexity increases, it may be necessary to have a simpler and intuitive way to organize Csharp scripts into multiple projects.

**Describe the problem or limitation you are having in your project:**
Currently it is not trivial to create separate csharp project as either an additional Csharp library or for unit/integration testing, within a godot project.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
[Migrate the current legacy csproj to the new .NET5 Sdk style csproj format ](https://github.com/godotengine/godot-proposals/issues/315)which make tracking which csharp files are associated with which csproj project simpler. However, the aim of the proposal is to go ONE step further on **HOW to organize these SDK style projects within a single Godot Project.**

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Allow one single Visual Studio Solution .sln file to support multiple the SDK style csproj projects with each on a separate csharp directory under a e.g. root Script directory.

The .sln file needs to be at the root level so it is possible to use continuous testing and delivery using Azure DevOps (Online or Server)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, we need this to allow Godot to support more complex and scalable project

**Is there a reason why this should be core and not an add-on in the asset library?:**
This involves the .sln solution file at the Godot Project root 

REF: [The current proposal requests the migration to the .NET5 SDK style csproj](https://github.com/godotengine/godot-proposals/issues/315). However the current proposal suggests how to organize Multiple SDK style projects per Godot Project to allow Godot project Csharp/mono project to scale in complexity

**Comment by Clonkex** [comment]
I'm working on a game using [Bepu Physics](https://github.com/bepu/bepuphysics2) as my physics engine (because Godot's own physics system doesn't offer enough control). I'd love to have the Bepu Physics wrapper C# project exist separately to my main game, so I can have a testing/development Godot project and then just link the Bepu C# project back to the main game project.

Currently I have to copy-paste C# source files from the testing Godot project to the main game project every time I make changes, which is super tedious and error-prone. Is that something this proposal would help with? I'm not familiar enough with C# projects and solutions to know what's allowed and what's not.

**Comment by GeorgeS2019** [comment]
@Clonkex  Try Godot4 .NET6  with SDK style project

**Comment by GeorgeS2019** [comment]
@Calinou  I think this is solved?

**Comment by Clonkex** [comment]
Huh, I'm already using Godot 4 with what appears to be the same type of project as in your example (I have no idea what the other types of project would look like though). It does appear to work just referencing the csproj file directly within the main game project. VS doesn't offer to link directly to csproj files from the GUI so I assumed it wasn't something you could do. Sigh.

The only issue now is that my nodes need to have scripts from this external project set on them, but the external project isn't inside the game's folder so I can't see the scripts. Maybe I can symlink it and exclude from the game's C# project? Hmm.

**Comment by GeorgeS2019** [comment]
> my nodes need to have scripts from this external project

U can add reference to project.csproj outside the Game folder.

**Comment by Clonkex** [comment]
A reference? In what? In the main csproj file? I did that, but the files aren't showing up in the Godot editor for me to set them as scripts on nodes.
