### ISSUE TITLE
should add a fade duration to the Style property.

### ISSUE THREAD

**Issue by ModuleCode** [godotengine/godot-proposals#11442]
### Describe the project you are working on

Demo

### Describe the problem or limitation you are having in your project

Button transitions are difficult to make. For example, if the background color changes too much after clicking the button, if you just add a normal style to the tween change, it will have no effect when the button is focused, which is very difficult to do.I think we should add a fade duration to the Style property.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Button transitions are difficult to make. For example, if the background color changes too much after clicking the button, if you just add a normal style to the tween change, it will have no effect when the button is focused, which is very difficult to do.I think we should add a fade duration to the Style property.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My technique is not very good. I am not very good at

### If this enhancement will not be used often, can it be worked around with a few lines of script?

NO

### Is there a reason why this should be core and not an add-on in the asset library?

YES

**Comment by tetrapod00** [comment]
Exact duplicate (double post?) of https://github.com/godotengine/godot-proposals/issues/11441.
