### ISSUE TITLE
Add an option to decode Ogg Vorbis at load time to save space and have good performance

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot-proposals#1144]
**Describe the project you are working on:** 2.5d Platformer (Fist of the Forgotten)

**Describe the problem or limitation you are having in your project:** I'd like to use ogg vorbis files for all sounds to keep the file size down, but I don't want to impact runtime performance.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** Decoding ogg files at load would allow the file size to remain small and not decoding in realtime will allow the performance to be better when playing lots of sounds.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** This would probably make the most sense as an import checkbox.  Like [] Decode sample into memory on load.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** No.

**Is there a reason why this should be core and not an add-on in the asset library?:** Not sure if this can be done as an add-on.  Seems pretty engine-level.

**Comment by Calinou** [comment]
Note that for anyone looking to implement this, [the audio thread can't allocate its own memory](https://github.com/godotengine/godot/issues/7496).

**Comment by TheDuriel** [comment]
What do you estimate would be the savings in disk space comparing OGG and WAV for sub 3 second long sounds. Assuming reverb tails are already stripped.

**Comment by Calinou** [comment]
@jitspoe Have you measured the performance impact of using Ogg Vorbis sounds in your project? Is it significant enough to warrant doing this?

**Comment by jitspoe** [comment]
@TheDuriel It looks like the wav files are about 4-8x larger for short sounds like footsteps.  I actually have a bunch of larger ambient sounds like wind and rain and thunder that I'd like to layer together.

@Calinou I'm not sure what the perf hit for ogg vorbis is.  I haven't actually done a profile.  I was just basing this off of the documentation: https://docs.godotengine.org/en/stable/tutorials/audio/audio_streams.html  I'd be interested to test on mobile, but I haven't gotten a build for that, yet.  I'd like to have possibly 20+ sounds layered, which I have a feeling would start impacting performance on low-end hardware.  If it doesn't have a significant impact, the documentation should probably be updated. :)

**Comment by jitspoe** [comment]
I created a test project with 600 stream players that can switch between wav and ogg.  The audio thread has spikes at a regular interval at around 17-19ms for wav and 80-85 for ogg (where it's doing the mixing, I assume).  In short, ogg is about 4-5x slower than wav.  Not sure if that'll have much of an impact in a realistic scenario, since it's already in its own thread, unless cores are limited.  Once you hit a certain threshold, though, the sound gets choppy.

Here's the project:
[Test Ogg Performance.zip](https://github.com/godotengine/godot-proposals/files/6300802/Test.Ogg.Performance.zip)

Space bar switches between ogg and wav streams.

**Comment by Calinou** [comment]
Note that [lossy WAV](https://wiki.hydrogenaud.io/index.php?title=LossyWAV) is an alternative that can be explored if Ogg Vorbis or even MP3 decoding are too expensive in your project. It's compatible with any program that can read WAV files, without requiring dedicated support.

**Comment by jitspoe** [comment]
The Rocket Bot Royale post mortem mentions perf issues decoding a bunch of ogg files and implemented a "Decode once" option, which I think is a great (and tested) solution.  https://github.com/godotengine/godot/issues/62291

Also just realized I never answered TheDuriel's question.  I have a mix of ogg and wav files for footstep sounds.  Wav files average around 40KB.  Ogg vorbis files average around 8KB, so that's about a 5x difference on really short sounds.  Probably a lot more on longer sounds with quiet sections that can benefit from VBR and such.  Also depends on the compression rate.

**Comment by Kersoph** [comment]
I think that can be a great feature and I was searching for ways to get something like that for me as well and found this proposal. I have players with a bit weaker CPU where the audio could not keep up the pace at some locations (audio seems to be single core, so more cores does not really help) with around 80-120 AudioStreamPlayer 2D/3D tested on Godot 3.5. I'm currently reducing the number but as well reduce the decoding load.

I've hit the wall on my machine with ogg with around 520 AudioStreamPlayer3D at 4.4GHz CPU where it takes up 100% of one core without any special effects. But as realistically the CPU is busy with other things as well and may has a lower CPU frequency, only a part of this is possible I think.
On my machine wav Ima-ADPCM takes around 5x less CPU than ogg (quality 2).
Pause or stop the stream reduces the cpu load practically to 0.

With this proposal the advantages of small disk space and low decoding load for frequent sounds can be combined on the cost of RAM.

**Comment by Yukitty** [comment]
I also require the functionality of runtime loading of Ogg Vorbis audio streams, to facilitate external and user-generated content, including decoding Oggs from the PackedByteArray returned from a ZIPReader.

... So I have cludged it together as a messy little GDExtension, for now, and submitted it to the Asset Library.

https://github.com/Yukitty/godot-runtime-ogg-vorbis
https://godotengine.org/asset-library/asset/9877

Many formats of image textures and even MP3s can also be loaded from external files and data, and Godot 3 could load ogg files directly as well. This seems like a feature of the engine that was inadvertently optimized away at some point, which could be standardized instead.

**Comment by sergeevabc** [comment]
Dear @jitspoe, why did you choose Vorbis over the next development of the same team, Opus? And are you familiar with the relatively new lossless, fast [QOA](https://qoaformat.org/) format? Its author, @phoboslab, emphasizes the decoding speed, especially in games.

**Comment by Calinou** [comment]
@sergeevabc [Godot lacks support for Opus](https://github.com/godotengine/godot-proposals/issues/6440), hence this proposal focusing on Vorbis only.

**Comment by DeeJayLSP** [comment]
> Regarding QOA support, see #7599 where it was mentioned in passing.

My statement about it having a better quality than Vorbis at max bitrate was wrong. It's actually comparable to it on lower bitrates like 96kbps with a bit of noise.

Regardless, it's still much better than IMA-ADPCM and the quality loss is pretty acceptable.

**Comment by DeeJayLSP** [comment]
> Regarding QOA support,

And it's supported now :)

**Comment by Calinou** [comment]
Closing, as QOA support effectively supersedes this by providing lossy audio compression with very low CPU requirements. It's most suited to sound effects and ambience, but it can technically be used for music as well.
