### ISSUE TITLE
Enhance experience for unmodified constructor inheritance

### ISSUE THREAD

**Issue by Erawpalassalg** [godotengine/godot-proposals#1145]
**Describe the project you are working on:**

**On Godot 3.2.2**

Let's say we have a simple project structure with 3 scripts.

- `Base.gd` which declares a constructor with 1 parameter
- `Child.gd` which inherits from `Base.gd` and do nothing
- `Test.gd`, linked to `Test.tscn`, the script to rule them all, which attempts to instantiate `Child.gd` on `_ready()`

**Describe the problem or limitation you are having in your project:**

First thing first. If I wanted my example to work properly I'd have to do something like `_init(param).(param)` in my `Child.gd`. As a side-note, if I wanted to modify my child's constructor, the current state of the editor wouldn't be an issue (except for the compile-time/runtime weirdness, but that's not a big problem)

Now, let's say I didn't declare my `Child`'s constructor.
- If I try to call it with one param, as declared in my `Base` class, the editor throws a **compile-time** error saying `Too many arguments for "_init()" call. Expected at most 0.` 
- If I remove the param and try to run the scene, I'm now getting a **runtime** error saying `Invalid call to '_init'. Expected 1 arguments`. 

This is pretty confusing. But it gets worse.

Let's say, now, that instead of having 3 files, I have only one file declaring 2 inner classes (still called `Base` and `Child`). Still not declaring the `Child`'s constructor.

- If I pass a parameter, now I get a **runtime** error saying that I made an `Invalid call to function 'new' in base 'GDScript. Expected 0 argments.`
- If I do not pass a parameter, I get a **compile-time** error saying `Too few arguments for "_init()" call. Expected at least 1.`

None of these error messages are useful in this case. Worse, they muddy the waters about something which is already not that obvious (why do I have to redefine my constructor if I expect my child to be built the same way than its parent? plus this thing has a unique and weird syntax, which is understandable, but already confusing as a beginner).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

This could be enhanced by either:
- 👍 making the child inherit it's parent constructor by default. This would prevent people not interrested in modifying the child's constructor behavior to have to look into the weird syntax stuff (I think it's pretty frustrating when you want to experiment with Godot's OOP design and stumble on this), or
- 🤷‍♂️ make the error messages clearer and normalize their pop-time, stating at compile-time that the constructor declaration of the child node is missing instead of this number-of-arguments thing

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Unfortunately I have no clue about how to implement this in the Godot's codebase (for now)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I think it would be used often 😛 

**Is there a reason why this should be core and not an add-on in the asset library?:**

Well, yeah, taht's because it's pretty core stuff

**Comment by DanielZTing** [comment]
I second inheriting constructors by default. I have a base class called `ComparisonSort` with a constructor that takes an array. It feels really awful to have to copy and paste

```gdscript
func _init(array).(array):
    pass
```

into each of my seven and growing child classes, maybe because it adds very un-GDScript-like boilerplate, or it feels like dead code but really isn't.

**Comment by dalexeev** [comment]
This is resolved in 4.x, so we can close this?

**Comment by Calinou** [comment]
Closing per @dalexeev's comment.
