### ISSUE TITLE
improve some of a bool syntax in different classes

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#1146]
**Describe the project you are working on:**

Applicable to any project. Currently I am working on the 2d side runner

**Describe the problem or limitation you are having in your project:**

Since GDScript is being rewritten it may be worth looking at some of the godot classes and improve naming in them to follow more natural spoken language and make it more readable what code is meant to do. 

For example in Array class we have following method. 

`clear( )` this does what everyone would expect it clears the array 

we then have next method

`duplicate( )` which also does what user expect it to do which is duplicates a array. etc. 

Then out of a blue we have `empty ( )` following the above example would be simple to assume this method empties the array. However it doesn't this is a `bool` that returns true is array is empty. Just by looking at this `my_array.empty( )` user has no way of knowing that `empty( )` is a boolean.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

We could change `empty( )` to `is_empty( )` and have much more readable code `if my_array.is_empty( ): #do something`

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

We could use this opportunity of GDScript being rewritten to hunt down through the code and fix the method names to better represent what methods are supposed to do. 

We already have some good naming convention for example in camera we use method is_position_behind( ) to represent that it's boolean returning true if position is behind a camera. We don't use position_behind() that would be confusing. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

no

**Is there a reason why this should be core and not an add-on in the asset library?:**

it's improvement to core GDScript

**Comment by pycbouh** [comment]
This is already part of the list on the main repo https://github.com/godotengine/godot/issues/16863

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/16863, as we prefer tracking renames there.
