### ISSUE TITLE
Automatic Fallback to OpenGL if Vulkon is not available.

### ISSUE THREAD

**Issue by llama-nl** [godotengine/godot-proposals#11460]
### Describe the project you are working on

Godot Engine 

### Describe the problem or limitation you are having in your project

Vulkan support is limited on older or lower-end devices, causing the engine to fail to start. This restricts deployment to devices without Vulkan support.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Introduce an automatic fallback mechanism to OpenGL (GLES3/GLES2) if Vulkan is unavailable, ensuring compatibility with a broader range of hardware and platforms.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If mobile/forward+ renderer selected and vulkon is not available change the renderer to OpenGL (Compatibility Renderer)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

probably. 

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think.

**Comment by AThousandShips** [comment]
Thank you for your proposal!

Already implemented, and will be in 4.4, see:
* https://github.com/godotengine/godot/pull/97142
