### ISSUE TITLE
Play AnimationPlayer using GPU compute features

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#1149]
**Describe the project you are working on:**

Multiplayer game

**Describe the problem or limitation you are having in your project:**

The goal is a subway demo proposal with a room full of people.

Add a GPU compute animation player for when you have lots of simple units.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

This feature will allow us to reduce cpu usage and have a room of skeletal animated characters.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

Simulate this photo.

![image](https://user-images.githubusercontent.com/32321/86200298-20f53380-bb11-11ea-9d81-c5a938391791.png)

**Describe implementation detail for your proposal (in code), if possible:**

Make a GPU animation player, that is simple and supports only simple blending and only processed visible objects. With compute its a bit more difficult because you need to pre-process the skeleton in a way where you can do things in parallel but matrix multiplication is extremely cheap in compute so you can process multiple bones with a single thread

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

The complexity is not a few lines.

**Is there a reason why this should be core and not an add-on in the asset library?:**

The animation player needs to be coded in Vulkan and have editor integration.

**Comment by Calinou** [comment]
Doesn't hardware skinning solve this problem already?

**Comment by fire** [comment]
Yes, this is a proposal for a type of hardware skinning that does not use transform feedback but rather a compute shader that writes to a texture and then a vertex animation is ran. This technique is similar to pivot painting or even the tree shaking in the wind demo. The idea is to do nested pivots in texture format.

**Comment by fire** [comment]
Prior art for ease of Googling.

https://www.unrealengine.com/marketplace/en-US/product/vertex-anim-toolset

https://assetstore.unity.com/packages/tools/animation/gpu-animation-baker-basic-135791?aid=1011lGbg&pubref=am&utm_source=aff

**Comment by fire** [comment]
Fixed by https://github.com/godotengine/godot/pull/44430.

According to reduz, the CPU still needs to be optimized via jobs over multiple cores, but the GPU rendering is not the bottleneck.
