### ISSUE TITLE
Support PCK file loading with offsets

### ISSUE THREAD

**Issue by Arivval** [godotengine/godot-proposals#1150]
**Describe the project you are working on:**
We are working on a [Play Asset Delivery](https://developer.android.com/guide/app-bundle/asset-delivery) android plugin for Godot. This feature, already supported on Android SDK and Unity, enables developers to request additional asset files from the Play Store.

**Describe the problem or limitation you are having in your project:**
One type of asset delivery for Play Asset Delivery is [install-time pack](https://developer.android.com/guide/app-bundle/asset-delivery#delivery-modes). Install-time asset packs are stored inside an uncompressed apk file with a particular offset and accessed by specifying the offset and length of the file. In Unity, developers would usually load an install-time pack by calling [this method](https://docs.unity3d.com/ScriptReference/AssetBundle.LoadFromFile.html) while specifying the offset. However, for Godot, if the Developer would like to load a resource pack that is served as an install-time pack, there is no way for them to achieve that since ```load_resource_pack()``` method only takes the path of the resource pack.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add optional ```int offset``` and ```int length``` fields to ```load_resource_pack()``` that will allow developers load resource packs stored in an uncompressed apk file.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The ```try_open_pack()``` function in [godot/core/io/file_access_pack.cpp](https://github.com/godotengine/godot/blob/master/core/io/file_access_pack.cpp#L126) can be modified to implement this addition.
The new function declaration will be:
```
bool PackedSourcePCK::try_open_pack(const String &p_path, bool p_replace_files, int offset, int length);
```
Inside this function, when we call seek to update the file pointer, we can take account into the offset and length in order to accommodate this feature.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Currently one workaround is to use GDScript’s file API to extract the install-time packs to a new path. This is a suboptimal solution since it creates additional disk space usage and consumes extra time. These tradeoffs are especially critical for mobile devices with limited storage space and file I/O speed.

**Is there a reason why this should be core and not an add-on in the asset library?:**
N/A

**Comment by akien-mga** [comment]
Closed by https://github.com/godotengine/godot/pull/40400.
