### ISSUE TITLE
Improving the visual look of visual scripting . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1159]
**Describe the project you are working on:**
A Tomb Raider game, atm, 3D, animations made in Blender . .

**Describe the problem or limitation you are having in your project:**
This is sort of a proposal, atm visual script looks a bit basic, it's looking nice but, I wanted to ask, for a later update, if it could get a visual look, more like Blender's shader nodes, which is very streamlined and, geared towards artists, which visual script is also, to an extent, not sure, it says in docs . . As an artist, the ' look ' in Blender's shader nodes, are probably the ideal look, also for visual script . . This is the proposal, make Godot's visual script look more, like Blender, the shader node system, like this . . .

![2020-07-04 0931](https://user-images.githubusercontent.com/61069740/86507770-343b2400-bddb-11ea-85ea-e917102ff9cb.jpg)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It's just a visual update, we had a discussion on what we wanted, to make visual script nicer, and this was my idea, I know it's simple, but it's so much more readable, what they have, in Blender, it's also open source software . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

The image above shows it, the shape of the boxes, except, the lines should be bendy, the idea is, make visual script in Godot look more, like the artist - friendly system, they have in Blender, for shaders . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't know how to change this very quickly, as a solo dev, I don't want to change the engine, to do this . .

**Is there a reason why this should be core and not an add-on in the asset library?:**

Well, I think Godot visual script is amazing, I have already made some simple games in it, I tried Unity some months ago, and I could not make a game, so visual script is amazing, for artists, prototypes . . . But, it looks a bit ' not artist - friendly ', and I personally think Blender has an almost optimal look, also for visual scripting . . Maybe you could think about it, and try to take something from both systems, and make a good ' mixture ', of those two styles, for instance, the boxes are more clearly colored, ie one can easier see what the boxes ' do ', in Blender, than in Godot, it's just for help, assistance . . .

Thx, know this is probably silly, Blender has such a nice LOOK, except for the non-bendy lines, between nodes, maybe Godot could take some of that, and make it more user-friendly, visual script . . .

But, keep the bendy lines, or have an option, to have ' straight ' lines, as Blender shaders, or the current bendy ones, as well . . That's, my proposal, I leave it to the engine gods, to decide what's best, I know I'm not good enough, to do that <3

**Comment by jasperbrooks79** [comment]
Again, thank you for your time, we started talking about, how to make visual script better, I feel the interface or, user - experience is a bit lacking, the OPTIMAL look for me, is pretty close, to what they have, in Blender, atm . . Super-fast to ready, well organized and, artist - friendly, at the same time . . 

ps. Still like the bendy lines, a lot, keep those, pls . .

![2020-05-02 0526](https://user-images.githubusercontent.com/61069740/86507978-7f096b80-bddc-11ea-96d4-6953bd801e07.jpg)

And, thank you . . .

**Comment by jasperbrooks79** [comment]
Here's my idea, of an ideal work-space, for visual script, there's a bar, at the top, with the name, of the box, and at the bottom, there's another bar, which has settings like, ' ? ', a question mark, that takes one to official docs, for what the box does, and another button, to toggle the box, as alsmost transparent, so one can make a large script more readable . .

![2020-07-04 1001](https://user-images.githubusercontent.com/61069740/86508164-45d1fb00-bdde-11ea-9d1a-593460853d71.jpg)

I'm not sure what most common features are, but I would like an ' expand all options ' button, a ' make box transparent or, faded ', and a ' Question ' button, to take one to the docs . . And, a collapse all options, after one has set them, if possible . . .

Thanks . .

**Comment by jasperbrooks79** [comment]
Here's an idea, for how the ' lines ' between nodes could look, a really nice style . .

![2020-07-04 1030](https://user-images.githubusercontent.com/61069740/86508585-7a938180-bde1-11ea-80de-b3d1c22a5c40.jpg)

That would be, my ideal visual script environment . . .

**Comment by jasperbrooks79** [comment]
Here's sort of the idea, for a nice visual script look, or so . . .

![2020-07-04 1046](https://user-images.githubusercontent.com/61069740/86508870-c47d6700-bde3-11ea-90f0-7b249e7eb12e.jpg)

So, when you're connecting the boxes, it feels like you're making, one of these, a REAL program, code . .
![2020-07-04 1035](https://user-images.githubusercontent.com/61069740/86508877-d3fcb000-bde3-11ea-9ea1-2d07814ce4f7.jpeg)

**Comment by jasperbrooks79** [comment]
I had one last idea, as a total beginner, and I know this might be tedious, but if one made so the background in visual script could be green, blue or, yellow, like classic chips, or motherboards, and made so the lines were either silver or, gold . . It would be such a cool look, I'm only talking about color themes, and so that the boxes were black, like chips, and had white writing in them, so they looked like chips, it would really fit these ideas, along with the standard ' dark ' Blender theme and, ' light ' Blender theme . .

That way, you're almost feeling, like you're working with the CPU, when working with visual script . .

![2020-07-05 1517](https://user-images.githubusercontent.com/61069740/86533619-b0646300-bed2-11ea-9617-e9df5ab6c0c1.jpg)

This would mean, visual script would appeal to both artists more, but also coders, as one could pick a theme, that felt amazing, no matter ones background . . .

Also, that one could right click, or CTRL + left-click on any line, and then open an edit mode, where one could place points, and make the lines between script boxes run, exactly the way one wanted it, purely visual . . This could help manage the ' spaghetti ' that many people run into, and find frustrating . . And, it would give Godot's visual scripting a unique look, that's different from the other engines, as well, and that was inspired by Blender, which is almost optimal, to look at, the boxes have a top bar, that clearly marks the function, and the bottom one, as well . . . 

Last request, if there was a button, to change the color of the ' top ' bar, and ' low ' bar, see above example, so one could after having made a character controller, make all the boxes in that part, a certain color, for easier reading, or so . .

Thx, I know this is a noob suggestion, but the more READABLE scripts are, the easier they are to manage, even at higher levels, and will be more appealing for beginners, and artists, while looking, like one has made a CHIP <3

Again, thanks for even reading this, tbh I'm VERY impressed with how you manage the engine, what you add to it, how you spend the money, you do a better job than I could, so I feel confident, no matter what happens, you will make the engine better, than I even could, Thanks, mean it, you're amazing <3 . .

Point is, this is a suggestion, that you could LOOK at, see if it was useful, or you could make something even better, I suspect you can, this is my little suggestion, can't wait to see what you do, it's usually better, than my ideas, so thanks . . . .

**Comment by jasperbrooks79** [comment]
Last idea, in the two bars, for the boxes, in the suggestion, make one button that completely collapses a node box, into a small box, where all the lines flow into one input, so one can make a box, smallest possible size, with just the top and, lower bar . . And, a text field, where one could write a custom name, for the collapsed boxes, like if when collapsed, there can fit 6 letters, one can write a custom ' name ', like ' Input ', ' VctClc ', when the script is done, one can better focus on working on the rest, especially if needs to make some boxes, that run on ' TOP ', of other boxes . .

Hope you give visual script a nice over-haul, so it's more friendly to work with, that's all . . .

Sorry, for the many posts, have trouble keeping my thoughts, together, have OCD, some autism . . . Can't WAIT, to see what Godot 4.0 becomes like, already looks amazing, last these are SUGGESTIONS, I know you guys are more pro, at basically anything, hope you can use it, for brain-storming, about what visual script should become, I know it will be better than this, most of all, can't wait, can't wait . . .

**Comment by jasperbrooks79** [comment]
Also, I really suck at making icons, use MS Paint, but idea is to have also a button, to expand or, collapse the box, to see all settings, like ' use default args ', so it's more accessible . . . I'm not sure what things should be in the lower bar, those are just some ideas, no more . . This is like one big proposal, I hope you can use some of these ideas, to make visual scripting even nicer, to look at . . That's, the idea . . . Sry, for so many posts, I struggle with using, the internet . . :O :O

**Comment by DarkMessiah** [comment]
It's based on GraphEdit and GraphNode like Visual Script: https://radmatt.itch.io/dialogue-designer

**Comment by jasperbrooks79** [comment]
Okay, if Godot visual script got a look more like that, it'd be amazing, anyway these are just some ideas, I know the core team is very pro, thank you . .

**Comment by Norrox** [comment]
> It's based on GraphEdit and GraphNode like Visual Script: https://radmatt.itch.io/dialogue-designer

that looks amazing

**Comment by jasperbrooks79** [comment]
Yea, I really hope we get something like that, for visual script, so it looks even better . .

Also, not just a ' name ' bar on top, but a settings bar, with common features, like PRINT ( any output ), and a button, to expand all the Arguments, ie Use Default Args, and a ' ? ' there, to take one to docs, for any box . . So, on page for docs, if there is missing info, one can place a ' message ', or perhaps write it oneself, or add use-case examples, to the docs, or so . .

![2020-07-06 0308](https://user-images.githubusercontent.com/61069740/88124502-95ca0380-cbcd-11ea-823c-51f149ea0b94.jpg)

The lower bar would be collapse, by clicking a little button in the lower corner, or in top bar, so it doesn't get very messy, and my biggest wish is, we get a ' line ' editor, where one can make lines follow the grid, and bend, by adding ( purely ) visual nodes on, lines, so one can avoid spaghetti or, get nicer lines, better flow . .
![2020-07-04 1055](https://user-images.githubusercontent.com/61069740/88124593-c9a52900-cbcd-11ea-8019-101c5c678a2a.jpg)

But, the example above already looks amazing, I do think the ideal form, is like Blender, but with a lower bar, one can expand or, collapse, ie make disappear, with Print, Expand Default Args, and a ' ? ', so EACH node, over time, will get examples, in the official docs, by the users, if the core team can't make all that documentation, I'd like to spend a few hours thinking how to make a nice example, for a box, or maybe explain a difficult one . . So, cool . . .

Overall, the radmatt example is really nice, but it's not compact enough, ie the boxes are very big . . That's where Blender is better, with more compact boxes or, like current visual script . . With so much wasted space inside boxes, one won't be able to have enough boxes on screen, ie wasted space in the boxes, to some extent needed, becomes a problem, as it means a ton, of scrolling, and one can't ' see ' all the nodes, for a bigger script, that's, the problem . . I think if the boxes got the visual look, of radmatt, but kept the same size as 3.2 boxes, it would be almost ideal . .

**Comment by jasperbrooks79** [comment]
Since a lot users that use visual script like simplicity, adding a collapsable bar, at the bottom, so one doesn't have to drag a PRINT box across the canvas, which creates almost always a spaghetti line, it would make it nicer, it should just PRINT all the outputs, like a drop-down list should appear, when clicking PRT, then, a name or, an index number, ie first output = index 0, second output = 1, or so . .

I think the lower bar, which can be toggle on / off ( collapsed ), would make visual script a lot, a lot nicer to use, and more interesting, for artists . . The biggest problem with radmatt is, that there seems to be a lot of space, in the nodes, compared to 3.2 or, Blender, that means one can't have as many boxes, on screen, but if they zoom function works better, that will fix it, but it has to work, then, ie, be readable . . No matter what radmatt, is an improvement, a big one . . 

Also, having that lower bar, would give Godot it's own unique look and, style, separate from other engines, AFAIK <3

**Comment by jasperbrooks79** [comment]
I have to say, can't wait for Godot . .

Hope, we get a time-frame soon, for when visual script gets a new edition, can't wait, can't wait . .

**Comment by jasperbrooks79** [comment]
It would be nice, with a function, or button to add, to the official docs, for any node . . Often, when I'm done with some work, and I have an hour, of rest, or like that . . I have the time to wonder, what would be a really good explanation, or tutorial, for a box, so people could easily fill out the docs, if needed, between work, on their games . . . That would be especially easy, if each box had a ' ? ' mark, alternatively, all these things, like PRINT, ' ? ', and so, could be inside one button, that opens a menu, when clicked, instead . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!

**Comment by 3DLAB0** [comment]
`know that vs is discontinued, but for extension or future godot vs implementation`
I like the idea of separating flow and data that Bolt 2 was supposed to use.
<img width="1046" alt="Screen-Shot-2020-02-17-at-8 16 43-PM" src="https://user-images.githubusercontent.com/94119095/188647702-5b97c51f-16ae-4e3b-8886-c62ef301d9f2.png">

**Comment by Zireael07** [comment]
@3DLAB0 There's a separate repo for visual scripting now, worth posting the pic there!
