### ISSUE TITLE
Remove AnimationTreePlayer in 4.0

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#1160]
**Describe the project you are working on:**

3D game where I'm playing around with 3d character animations.

**Describe the problem or limitation you are having in your project:**

When I add an AnimationTree, two nodes appear in the search: AnimationTree and AnimationTreePlayer.
Both have a configuration warning when they are added to the scene. One is a deprecation warning, the other is related to setup, which makes it hard to figure out which is the "real" one. I started out trying to use the AnimationTreePlayer, but it's super unpolished and nearly useless. I suggest removing it in 4.0, since it's long overdue.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

It wont appear in the search any more.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Remove the class from the engine and from the documentation for 4.0.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This proposal doesn't have to do with a feature.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This proposal doesn't have to do with a feature.

**Comment by KoBeWi** [comment]
This was already done in https://github.com/godotengine/godot/pull/36085 actually...
