### ISSUE TITLE
Add support for images in code comments in the script editor

### ISSUE THREAD

**Issue by monk-e-boy** [godotengine/godot-proposals#1168]
A 3D kite design program

**Describe the problem or limitation you are having in your project:**

I forget how some bits of code work, e.g. winding of opengl triangles, an image would help.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Picture is worth 1,000 comments.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Screenshot, paste into code. Image is a comment.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Don't know

**Is there a reason why this should be core and not an add-on in the asset library?:**

Don't know

**Comment by jonbonazza** [comment]
Not a good odea in general. Adding binary to source files will

 a) make the file unusable in many text editors and ides
 b) make cod diffs in version control brutal.

Just link to an external image.

**Comment by bojidar-bg** [comment]
There are some relatively benign ways to incorporate an image into text. For example, it might be a base64 encoded .svg. After this, it could be just a matter of loading and displaying such images (and convincing TextEdit that you can take the space up for an image). Might be doable with a addon and some hacky code, in fact.

**Comment by monk-e-boy** [comment]
Could you just put an img tag in?
```
var x = 1
# <img src="res://image1.png">
var y = 2
```
And the editor would just show the image (maybe on hover?)

**Comment by Calinou** [comment]
@monk-e-boy Godot's editor isn't a WebView. HTML tags won't work :slightly_smiling_face:

**Comment by monk-e-boy** [comment]
> @monk-e-boy Godot's editor isn't a WebView. HTML tags won't work

What sort of argument is that? It's too tricky to implement?!

Games are visual. Code and comments should incorporate some visual elements.

Animating sprite? Picture of sprite next to code. Looking for code that generates a flower? Look for picture of flower.

**Comment by Calinou** [comment]
@monk-e-boy Displaying images directly in text editors is definitely not a common feature. I don't know of any editor that supports it *out of the box*.

**Comment by Xrayez** [comment]
I think the most feasible workaround to this is actually being able to follow links in the script editor: #1172.

**Comment by me2beats** [comment]
> Picture is worth 1,000 comments.
And what about video?:) No joke
Btw it's worth implementing it as a plugin rather core, but there's no such APIs yet

**Comment by Calinou** [comment]
Closing due to lack of support (see the above comments).
