### ISSUE TITLE
2D DirectionalLight Node for Godot

### ISSUE THREAD

**Issue by sian2005** [godotengine/godot-proposals#1173]
**Describe the project you are working on:**

I am working on a 2D, Terraria-like Game.

**Describe the problem or limitation you are having in your project:**

I want to have perpendicular shadows from the tiles downwards, like a sun, With a normal Light 2D, this is not possible due to the shadows coming from one point, Yeah, the light from the sun in real life is also coming from one point, but then I would have to make the poor Light 2D so large that just a blank scene with that Light 2D will run at less that 1 frames per second.

A DirectionalLight 2D will solve all of these problems.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

With the feature I can have beautiful, perfect and endless downwards-facing shadows everywhere on the tiles visible to the DirectionalLight 2D. I will no longer need a Light 2D to be a child of my player to get shadows that don't look great when they are moving as you move. If I use multiple light 2D's and turn them on if the player is near them and off as he goes away there will be a snappy line in the border of them, there will be no perfect downfacing shadows as I wanted, it wont be endless vertically as well, I wont be able to rotate it arount the world to create a sunset because you cant make a normal Light 2D endlessly large to accomplish this effect and it won't be completely endless horizontally aswell.

It is also mentioned in this post: (https://github.com/godotengine/godot/issues/29994)

A DirectionalLight 2D will solve all of these problems.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Something similar to the existing DirectionalLight, but for 2D.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't think it will able to be worked around requiring a few lines of code, and still getting the effect of what a DirectionalLight could be able to accomplish with minimal efforts.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This requires changes to the rendering pipeline which cannot be done via script or addons.

**Comment by Calinou** [comment]
[This was implemented in the `master` branch](https://godotengine.org/article/godots-2d-engine-gets-several-improvements-upcoming-40)
, closing.
