### ISSUE TITLE
Add Delphi 10.4 Language Support to GODOT

### ISSUE THREAD

**Issue by Shpendicus** [godotengine/godot-proposals#1174]
**Describe the project you are working on:**
Just getting started with it/playing around

**Describe the problem or limitation you are having in your project:**
It would expand I think a lot the Godot useability, since Delphi/Free Pascal is a very powerful and high performant language with ease of use.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I think a big win for Godots Growth, since it synergizes well with Godot since Delphi is an ease of use language with C++ like features, and having a C++ similar Language which is quiet beatufiul and powerful at the same time, is a big win I think. Also Delphi has improved alot of its capabilities to use C++ classes/libs (partially with some workarounds) in Delphi codebase which is huge given the fact that you can share code bidirectionaly, respected the limitatiions ofc!

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
- 
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
-
**Is there a reason why this should be core and not an add-on in the asset library?:**
Selfexplained I think ^^

**Comment by andy-noisyduck** [comment]
If the goal is usability, I would think it's a hard case to make that Delphi is going to be more usable than say GDScript? 

Performance is perhaps more compelling, but when using a game engine the performance of the scripting language is rarely the bottleneck. It's far more likely to be something the engine is slower at, or a technique that isn't supported very well. For the few cases where the script really is the bottleneck then using GD native would probably make more sense than adding support for another compiled language?

Is Delphi used enough for additional support to make sense? I don't know much about the Delphi community to be honest, but [TIBOE ranks it pretty low in popularity](https://www.tiobe.com/tiobe-index/), and it doesn't make the [top 50 in Github](https://githut.info/). Granted that's not the most scientific method, but I think it's somewhat indicative.

**Comment by Calinou** [comment]
I would recommend trying out Godot with [GDScript](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exports) before looking into integrating more languages. There's always C# support too, which is official.

**Comment by Shpendicus** [comment]
@Calinou Thx mate, yes I have read about the Bindings but do you need to be a language-/Compiler dev to write those bindings or is it doable with "normal" programming skills? I would do this effort with some otgher ppl then, since I would love to have an Object-Pascal binding to this beautiful engine. Would look into that!

**Comment by Calinou** [comment]
@Shpendicus Creating a GDNative binding requires C knowledge, as well as knowing some of Godot's internals. In addition, you should be prepared to maintain it for a while if you want people to rely on it.
