### ISSUE TITLE
environment var expansion for "custom_modules" compile param

### ISSUE THREAD

**Issue by GoDino** [godotengine/godot-proposals#1178]
**Describe the project you are working on:**
setup where multiple games are started from a selection "game"

**Describe the problem or limitation you are having in your project:**
in automating/pipelining, it is great for us to be able to keep modules separate from the core using the new "custom_modules=path" compile parameter. It would be even cooler if that would go through os.path.expandvars()

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
module paths could contain vars such as "${PROJECT}/.../CUSTOM_MODULES", making them platform/root path independent

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
it would be a small modification in modules.py ->convert_custom_modules_path(), just add os.path.expandvars() in there

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no

**Is there a reason why this should be core and not an add-on in the asset library?:**
because it is a compile-only improvement

**Comment by Calinou** [comment]
Can't you pass the `custom_modules` setting with a string enclosed in double quotes (no single quotes) so the shell expands it on its own?

**Comment by Xrayez** [comment]
How do you set the `custom_modules`? In my own project I set this via another Python script, not command line, and even when I compile it via the command line alone, it still works (on Windows Powershell):
```powershell
$env:MY_PROJECT_PATH = "C:/src/my_project/"
scons custom_modules="$env:MY_PROJECT_PATH/modules"
```

What OS do you run?
