### ISSUE TITLE
GDScript generate warnings on non-statements

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1179]
Add a 'non-statement' warning to gdscript language to find expressions posing as statements. What I mean by that is lines that are not statements, are not assignments, do not create anything and there are no side-effects to the line.

For example the following line consisting of only:
`b == 'hello'
`
In this example it could result in a very, very difficult bug in code to track down.

There is never a use case where this is what was required, and clearly the line should have been b='hello'

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

PS: I think standalone expressions should already print a warning (like writing a string on its own line). If not, it might be a bug.

**Comment by KoBeWi** [comment]
There's a warning for this already, it's called standalone expression.

**Comment by chucklepie** [comment]
I found this out, but the case was closed for formatting so I didn't reply.

I never realised warnings were hidden behind a tiny yellow triangle. I was
expecting to appear in the main bottom pane with errors.

**Comment by KoBeWi** [comment]
Warning visibility might get improved by #1005
