### ISSUE TITLE
Add a track filtering node to AnimationTree

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot-proposals#1187]
**Describe the project you are working on:**
A 3D game that is slightly similar to VR Chat but of a much smaller scale and not in VR

**Describe the problem or limitation you are having in your project:**
Sometimes I need to animate a specific part of the body without affecting the rest. Track filtering is a good method to do it, but having it limited to Add2, Add3, Blend2 and OneShot is quite inconvenient.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
An independent track filtering node that would replace the filter option in Blend2 and OneShot, and expand the functionality to the other nodes. The animation output of any node can be connected through this node to any node that takes an animation input, and would limit the animation's effect to the selected tracks.

Mainly I want to be able to use track filtering in Transition and Blend3 nodes, but I thought having an independent node for filtering would be a good idea so I proposed this instead of just proposing to add filtering to those nodes.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
For the nodes that already have filtering, I think it won't be that complicated and would work similar to how it does now. Blend3 would work similar to Blend2 or Add3. Transition is where it might be complicated.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it's a modification of the core animation system

**Comment by Calinou** [comment]
- Closing in favor of https://github.com/godotengine/godot-proposals/issues/6816, which is more detailed.
