### ISSUE TITLE
Making it easier to make collisionshapes in Godot . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1193]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
When I important into Godot, from Blender, it is somewhat complicated, to make the collisionshape, from the mesh . . I was wondering, IF one made the collisionshape in Blender, and gave that low-poly mesh a name, so Godot knows, when importing it, that it should make a StaticBody collision-shape, it would be much faster, to import things, from Blender . . Like, if one added a special character, or name to the mesh, for collision, in Blender, like there's . .

Rock_wall_basemesh
Rock_wall_collision

So, when one imports the glTF, Godot automatically makes a collisionshape, from the Rock_wall_collision 3D object, and then deletes the mesh, basically I am asking for a system, where I make all the 3D in Blender, then when I import it, the importing steps are more easy or, less work . . It would be a nice addition, and also more intuitive, it could be done if Godot checked, for any mesh in a glTF that has, the _collision, or _coll, as a last name, then one can work on all the meshes, in Blender, and import with a single click, it all just works, this is for StaticBody and, their collision shape . . Hope it makes sense, maybe one could add a option, in the import settings, ' Turn _coll meshes into CollisionShapes ', or so . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It's just a bit sort of, not good, that the 3D work isn't done completely, in Blender, where it's very easy, and there's a lot of tools, for shaping collisionshapes, like snap_to_pixel, and it's easier to see, what is happening, in Blender . . Ideally, one wants to do all the 3D work, also collision shapes, custom ones, in Blender, and have a simple, direct import function, into Godot . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Basically, after making a complex 3D mesh, like an antique desk, with maybe 2000 poly count, to add a collisionshape in Blender, that is maybe 40 polys, or so, give it the name table_coll, or table_collision, and then the importer automatically turns that mesh into a StaticBody mesh, that ' just ' works . . . Then, it deletes it, or makes sure it doesn't get rendered, or so . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't know, it's just a lot easier to set up the collision bodies in Blender, and it makes more sense, to have this work-flow, over the current one, which works nice, fine, but it would be nice if 3D work was done completely, in Blender, and then game making and, design is done, in Godot . . I know this is a small thing, but it would be nice . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**

It doesn't make sense to add this, in an add-on, as many people would never get to use it . . I don't know if this is very complex, but it would be a lot nicer, if it worked that way, everything set up the right way, from Blender, to Godot . .

It would be a nice addition, and make a lot more sense, to the users . .

**Comment by jasperbrooks79** [comment]
Also, one could make some names, so if one imports a staticbody, from Blender, those meshes should have a special name, like _statcol, for a kinematicbody import, _kincol, and for rigidbodies, _rigidcol . . That way, Godot knows which meshes are supposed to be what, and the correct things are done, during the import, no extra work, and 3D stays in Blender, 3D modelling, game world setup, prop placement and, code, works in Godot, so you make a logic ' split ', between the two programs, that makes sense . . .

Thx . .

**Comment by DarkKilauea** [comment]
I believe this already exists: https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_scenes.html#import-hints

Does this system not work for you?

**Comment by jasperbrooks79** [comment]
I didn't know this, thx . .

**Comment by jasperbrooks79** [comment]
It's already there, I made a mistake, thank you, well done . . <3

**Comment by Calinou** [comment]
Closing, as this feature is already implemented.
