### ISSUE TITLE
Add a player for Lottie animations

### ISSUE THREAD

**Issue by benitogf** [godotengine/godot-proposals#1196]
**Describe the project you are working on:**

an application that receive signals and display the corresponding animation

**Describe the problem or limitation you are having in your project:**

I would like to be able to import the animations using [lottie](https://github.com/LottieFiles/lottie-player)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Currently I couldn't find any integration for godot

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I have no specifics, maybe a way to integrate the web player into godot?

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Think that it could be used often, currently I havent found a workaroud

**Is there a reason why this should be core and not an add-on in the asset library?:**

I'm not sure, I see that there are platforms integrating as a "core" feature like [QT](https://www.qt.io/blog/2019/03/08/announcing-qtlottie)

**Comment by Calinou** [comment]
I'm fairly sure this can be done with a third-party add-on or module.

**Comment by fire** [comment]
I was looking into this but got stuck, how familiar are you with coding? I can describe an approach.

**Comment by fire** [comment]
https://github.com/Samsung/rlottie/issues/353#issuecomment-660762597 They are interested re-licensing from LGPL to MIT license.

**Comment by fire** [comment]
Samsung relicensed rlottie from GPL to MIT licensed and I got the bare minimum working here https://github.com/godot-extended-libraries/lottie. A bit fried, so you'll need to know how to use custom modules without help. There might be documentation on scons custom modules, but this lottie importer is a first draft.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP). An implementation can still be pursued as a third-party effort (see https://github.com/godot-extended-libraries/lottie).
