### ISSUE TITLE
Change version naming convention from 4.0 into beta 1.0

### ISSUE THREAD

**Issue by pajcek11** [godotengine/godot-proposals#1201]
**Describe the project you are working on:**
Any Godot Project ever that requires standard programming functionalities of the most basic programming languages.

**Describe the problem or limitation you are having in your project:**
In several projects, I had to employ solutions and workarounds which should not even have existed in a non-alpha version of the program. The most recent - GDScript not supporting storing functions into variables via standard form, except via obscure methods.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I suggest the naming of Godot 4.0 be changed to Godot beta 1.0 because it only now gets a set of functionalities that should be part of any serious beta-level gaming engine. Most of the "features" in Godot 4.0 are "essentials", and thus it has been until now a misinformation to the potential users that Godot is a finished product.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Name Godot 4.0 into Godot beta 1.0 so people are aware that only now Godot has achieved basic functionality and standard of a gaming engine which is not in alpha.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
A few lines is all it takes.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Anything else would be intentional confusion of the consumer that Godot has been "finished" before 4.0

**Comment by Calinou** [comment]
> In several projects, I had to employ solutions and workarounds which should not even have existed in a non-alpha version of the program. The most recent - GDScript not supporting storing functions into variables via standard form, except via obscure methods.

For the record, first-class functions will be supported in Godot 4.0.
