### ISSUE TITLE
Expose a way to get an autotile's collision shape from a TileSet

### ISSUE THREAD

**Issue by cgbeutler** [godotengine/godot-proposals#1202]
**Describe the project you are working on:**
I was trying to make a plugin tool for [`TileMap`](https://docs.godotengine.org/en/3.2/classes/class_tilemap.html) and [`TileSet`](https://docs.godotengine.org/en/3.2/classes/class_tileset.html).

**Describe the problem or limitation you are having in your project:**
There is no apparent way to get collision shapes for an auto-tile or atlas-tile. There are functions like `TileSet::autotile_get_navigation_polygon(int id, Vector2 coord)` to get other auto/atlas tile properties, but the ones for collisions are not there. The regular `tile_get_*` set of functions has collision getters, but there is no apparent way to find the specific shape you are looking for for your auto/atlas subtile.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If there really is no way to find the collision for your sub-tile, then adding a getter would make that possible. If there is a way to get it, but it's convoluted, adding a getter would help folks like me who are confused and frustrated.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
There are _currently_ these functions in TileSet:

```
tile_get_shape ( int id, int shape_id )  -> Shape2D 
tile_get_shape_count ( int id ) -> int 
tile_get_shape_offset ( int id, int shape_id ) -> Vector2 
tile_get_shape_one_way ( int id, int shape_id ) -> bool 
tile_get_shape_one_way_margin ( int id, int shape_id ) -> float
tile_get_shape_transform ( int id, int shape_id ) -> Transform2D
tile_get_shapes ( int id ) -> Array
```

I propose adding matching functions for `autotile`. Something like:

```
autotile_get_shape ( int id, Vector2 coord, int shape_id )  -> Shape2D
autotile_get_shape_count ( int id, Vector2 coord ) -> int
autotile_get_shape_offset ( int id, Vector2 coord, int shape_id ) -> Vector2
autotile_get_shape_one_way ( int id, Vector2 coord, int shape_id ) -> bool
autotile_get_shape_one_way_margin ( int id, Vector2 coord, int shape_id ) -> float
autotile_get_shape_transform ( int id, Vector2 coord, int shape_id ) -> Transform2D
autotile_get_shapes ( int id, Vector2 coord ) -> Array
```

A bonus feature would be renaming `autotile_*` to `subtile_*` since those functions are for both autotile and atlastile. That would be a v4 thing, though.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No workarounds needed. This is just exposing new api.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I would think this is core functionality. Not having it seems like an oversight more than anything.

**Comment by cgbeutler** [comment]
Ah, it would appear `tile_get_shapes(...)` returns an array of dictionaries that look like: `{autotile_coord:(1, 0), one_way:False, one_way_margin:1, shape:[ConvexPolygonShape2D:152039], shape_transform:((1, 0), (0, 1), (0, 0))}`
The getters would still be useful, though.
I may make a docs request to make it clear that the shapes returned are dictionaries.

**Comment by GuyCooke** [comment]
@cgbeutler posted a dictionary string that shows the `"shape"` entry in the dictionary returned by `get_tile_shapes(...)` is a `ConvexPolygonShape2D` which is a `Shape2D` but the documentation claims the type will be a `CollisionShape2D`.

**Comment by cgbeutler** [comment]
The documentation is correct. I pasted a raw print, hence the `ConvexPolygonShape2D`
I think I will close this issue, as the `tile_get_shapes` works fine. (Reopen/make if you want.)
