### ISSUE TITLE
[Android] Androidx Upgrade

### ISSUE THREAD

**Issue by cagdasc** [godotengine/godot-proposals#121]
Google has changed their support libraries to named Jetpack. So We want to add android module which use to support or google branded libraries, the problems encountered. So in Godot, we need to refactor android project with androidx. I try it and see some changes in "Permission", "Download" and "Notification" section, they are `ContextCompat` import.

**Comment by golddotasksquestions** [comment]
You might want to have a look at that: https://github.com/godotengine/godot-proposals#rules-for-submitting-a-proposal

**Comment by groud** [comment]
Yes, please read the rules and fill in the issue template.
