### ISSUE TITLE
Make saving scenes faster

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1210]
**Describe the project you are working on:**
A Tomb Raider game, trying out Godot 4 for, debugging, seeing how it works . .

**Describe the problem or limitation you are having in your project:**
It takes a long time to save the scene, in the 4.0, this really gets in the way of testing, and debugging, not sure why it takes much longer, anyway if that was made faster, that alone would help many more people debug it, and have fun, not entirely sure why it takes 30 seconds, to save a scene, in 3.2 it took less than a second, would help debugging, make it more fun . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Trying out 4.0 for fun, the graphics are a lot better, so much fun, want to try and, do a little debugging, or error-reporting, but the long save times, before running the game, makes it a bit, of a hassle, or so . . . Thx . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just something that could help more in the community do test and, debugging on 4.0, not sure, maybe there's something I don't understand, the much slower times, to save a scene, <3

Godot 4.0 is already amazing, just wow, . . Graphics are better, textures are rendering better, it's just better . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by Calinou** [comment]
Godot 4.0 is still in early phases of development. Most optimizations haven't been implemented or finetuned yet.

**Comment by Jummit** [comment]
If saving scenes is considerably slower than 3.x builds, it should be put on the bug tracker instead of here imo. There is not much to be discussed, and it's not really a feature proposal either.

**Comment by jasperbrooks79** [comment]
Okay, Godot 4.0 has amazing graphics, as I see it, but if saving a scene takes, like 30 seconds, before playing a level, it will be sort of not ' fun ' for beta - testers, or so, to use it, and report bugs . .

Sry, if in wrong place, not sure it's a bug, maybe 4.0 will get a new file-system, or so, and it will take a long time, before it's complete . .

Anyway, 4.0 is looking amazing as it is, just cool . .

Can't wait, for 4.0, so cool . . .

**Comment by Calinou** [comment]
Closing per this comment:

> If saving scenes is considerably slower than 3.x builds, it should be put on the bug tracker instead of here imo. There is not much to be discussed, and it's not really a feature proposal either.
