### ISSUE TITLE
Make the script editor completion use better sorting/searching

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1216]
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
When using the '.' to expand the current object in the IDE it would be nice to be able to have the items sorted either alphabetically or using some kind of semi-intelligent ordering, instead of the current order which seems to list every single global first then everything else afterewards alphabetically. In addition, using the list to find items by typing is limited.

When you know what you want, you do not need the dropdown, so being confronted by an arbitrary sort containing first 3 pages of globals is pretty much pointless to anyone who actually needs the dropdown, as seen in the picture below.

I would suggest the following:
1. The simplest approach is simply alphabetical, this is at least navigable.
2. VSCode employs a much better (for some languages) approach in that it first lists all the current object's methods then everything else, alphabetical. Imagine on a Timer pressing '.' and getting all the actual timer methods/properties first :)

In addition, typing only works for the first letter. What if you don't know if it is 'is_deferred' or 'deferred'? in Visual Studio you can type a word and it finds everything with that word

Current system showing page after page of globals
![image](https://user-images.githubusercontent.com/12863685/87862465-5b036980-c948-11ea-93b5-b7845ae05502.png)

This is how the VSCode plugin for GDScript works, it colour codes and sorts alphabetically.

![image](https://user-images.githubusercontent.com/12863685/87862500-c0575a80-c948-11ea-9cd7-3adc17dfdefb.png)

In javascript it adds to this and finds inferred methods, etc. and creates a priority then alphabetical sort.

**Comment by me2beats** [comment]
I actually dream of being able to access the autocompletion elements (properties and methods).
then I could create my own sorting methods, which would be quite flexible.

For example, I would like to try sorting items by frequency of use.
Or hide some results, etc.

**Comment by me2beats** [comment]
or maybe even an ability to use custom autocompletion popup instead of default one.

recently I tried to get autocompletion popup from gdsript editor plugin — and it seems there is no way to do this.

**Comment by chucklepie** [comment]
Yes, that's how Visual Studio does it, but I didn't want to go too far ;-)

I just think the default of having 3 pages of Global properties is silly in my humble opinion (as an average user who needs the dropdown to find things), and anything would be better even plain alphabetical.

**Comment by EricEzaM** [comment]
I made this... Unlikely it will get merged though. It will need to be remade after updates are done to the editor for 4.0.

https://github.com/godotengine/godot/pull/38449#issue-412781186

**Comment by chucklepie** [comment]
That looks great. Does it sort too, as in when you're looking at all do you
still get the 30 or 40 global constants that nobody uses 😉

**Comment by chucklepie** [comment]
Possibly. But if its 99, then there's no hope of this happening 😉

As it stands, in my opinion, the context menu is a completely pointless
thing because in most cases you get 3 pages of global constants, then
random methods of various classes like Object, etc.

**Comment by pycbouh** [comment]
> Duplicate of #99?

Thank you, indeed they are too close to keep both. Closing in favor of #99.
