### ISSUE TITLE
Add a way to build GDNative modules into the engine on all platforms

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot-proposals#1218]
Currently dynamic library loading is impossible in some platforms (like UWP) I think it would be nice if it was possible to build the GDNative modules into the engine on all platforms in a simplified way (currently iOS I think does it, but no idea how to get it to work for UWP and co).

This would also benefit the Switch port.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
