### ISSUE TITLE
Make decals support MIX as well as the current ADD blend mode

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1219]
**Describe the project you are working on:**
A Tomb Raider inspired game, atm . . . LOTS, of work . . .

**Describe the problem or limitation you are having in your project:**
The decals in 4.0 current build are AMAZING, but they seem to work in the ADD blend mode, not the MIX blend mode, which makes them pale or, almost transparent, compared to original image . . Maybe one could add a setting, so one could pick between adding, mix, or multiply or, subtract, like the normal SpatialMaterial allows . .

![2020-07-19 1527](https://user-images.githubusercontent.com/61069740/87876080-e414b200-c9d5-11ea-8013-9e217d9f9b23.jpg)

![2020-07-19 1539](https://user-images.githubusercontent.com/61069740/87876110-1d4d2200-c9d6-11ea-8f22-0cd19d29982c.jpg)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Atm, the textures look pale, because it doesn't work in mix blend mode, making the textures look ' not ' right, maybe the decals are not finished yet, without that, I don't think they will be popular, especially for stylized ( 3D ) games, anyway maybe I don't understand them, have tried tweaking the settings, can't make go out, of ADD mode, to MIX Blend mode, at least on screen . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Well, ADD mode only limits the use of decals, quite a lot, maybe it is needed, to be included . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I can't explain it any better . . Also, Godot 4.0 current build is MIND -blowing fun and, AWESOME-ness ! ! So, good . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**

I can't decide these things, am pretty new to game engines, began learning Godot 6 months ago, I think . . .

Thx, :DD

**Comment by jasperbrooks79** [comment]
Atm, decals only support textures, not PBRmaterials, so I can't move a material in, as there isn't a place, for it, in the decals . .

**Comment by Calinou** [comment]
I'm pretty sure decals use a Mix mode if you load the texture into the Albedo slot (instead of Emission).

> Atm, decals only support textures, not PBRmaterials,

You can load a roughness map into a Decal already. Loading a metallic map wouldn't make much sense (I can't see much use cases for it).

**Comment by jasperbrooks79** [comment]
Thank you, I am trying the daily build from your web-page, so much fun . .

I was hoping one could use a material, instead, because then I could set it to Mix color blend mode, instead . .

To be clear the current decals are AMAZING ! ! I will use them, to make roads, and nice effects, on walls, like decay or, so, but it looks like it's been set to ADD, instead of MIX blend mode, at least when I test it, as a noob . . .

The first image, is a meshinstance plane, with a MIX mode texture, the middle is a meshinstance with the same texture, but using ADD mode, it's more fade, less sharp . . The last one is the decal, to the right, it looks more like the ADD mode, not sure . .

![2020-07-19 1527](https://user-images.githubusercontent.com/61069740/87879776-0d8d0800-c9ed-11ea-92e5-cad2a18124f0.jpg)

Tried changing all the settings, anyway I wanted to propose if idea is, to only have ADD mode, to add a switch, for MIX mode, SUBTRACT and, multiply, like in materials, it might be super-complicated, not sure, sry . .

Again, thanks for Godot, I'm happily a Patreon, with a silly, modest amount, features like this, make me excited, will give amazing control over texture looks, and help make much more detailed worlds, as well . . Thx <3

**Comment by SIsilicon** [comment]
May we see the settings used for the decal?

**Comment by jasperbrooks79** [comment]
Here . .
![2020-07-20 0628](https://user-images.githubusercontent.com/61069740/87899710-4a3f1a80-ca52-11ea-95b0-3e04010f85e8.jpg)

Sry, pretty tired, hope it's okay . . .

**Comment by jasperbrooks79** [comment]
Blend mode ' Add ' is almost only used for fire, smoke and, water effects . . It has little use, for what's normally considered ' decals ', as in Counter-strike, other games . .

**Comment by clayjohn** [comment]
Decals are not able to use the blend mode ADD. They only ever MIX. 

However, I can confirm the issue. It looks like the texture is using the wrong color space or something. 

![Screenshot (185)](https://user-images.githubusercontent.com/16521339/87902653-1393e080-ca0f-11ea-8de8-9bf1e7333287.png)

**Comment by NHodgesVFX** [comment]
i can confirm this issue as well. Should this be made into a bug report?

**Comment by clayjohn** [comment]
@NHodgesVFX Yes please

**Comment by NHodgesVFX** [comment]
> @NHodgesVFX Yes please

done :) https://github.com/godotengine/godot/issues/42073
