### ISSUE TITLE
Directory: Alternative to list_dir_begin: get_files

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#1225]
**Describe the project you are working on:**
Working on some tests following my recent pull requests on `DirAccess` bug fixes.

**Describe the problem or limitation you are having in your project:**
Listing files in a directory requires a lot of boilerplate code.

Example A:
```py
dir.list_dir_begin()

var file = dir.get_next()
while not file.empty():
	print(file)
	file = dir.get_next()

dir.list_dir_end()
```

Example B:
```py
dir.list_dir_begin()

var file
while true:
	file = dir.get_next()
	if not file:
		break
	print(file)

dir.list_dir_end()
```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This proposal will allow an alternative option that is a lot simpler to write.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```py
for file in dir.list_files():
	print(file)
```

**Note 1**: If buffering all the files in a list is an issue, we should probably change `file_access_pack`
![image](https://user-images.githubusercontent.com/14253836/87901912-de42bf00-ca1d-11ea-906d-e42414cb84e1.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Technically yes, this can be worked around by writing one of the top examples. However, this is used quite often and will not break compatibility for 3.2.

**Note 2**: Depending on how people think of this, `list_dir_begin`, `get_next`, and `list_dir_end` could be deprecated or removed in 4.0.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is not really relevant since Directory is already part of core.

**Comment by Xrayez** [comment]
Yeah, I have some [code written to work with `EditorFileSystemDirectory`](https://github.com/Xrayez/godot-editor-plugin-tools/blob/master/editor_plugin_utils.gd#L44-L122) for editor plugins, including the mentioned `get_files` method. Similarly you could write `get_files_recursive()` just like there's `make_dir_recursive()` and whatnot. But the core functionality will remain simplistic anyways whatever we propose, so I'm for improving the process of traversing the files within a directory at least.

**Comment by nathanfranke** [comment]
We could also implement an iterator class for GDScript so there is no buffering issue

**Comment by nathanfranke** [comment]
"git gut" :P

**Comment by KoBeWi** [comment]
I looked at DirAccess code and the funny thing is that it already stores internally the list of files/directories and `get_next()` just pops elements from this list xd
