### ISSUE TITLE
Change the name of nodes so they're less cluttered

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1226]
**Describe the project you are working on:**
A Tomb Raider game . .

![2020-07-20 0718](https://user-images.githubusercontent.com/61069740/87902165-3b0f9b00-ca59-11ea-83bc-bc6352ee2698.jpg)

**Describe the problem or limitation you are having in your project:**

Many of the node names have changed in Godot 4.0, but it makes a large node tree, in the scene inspector hard to read, because it says 3D everywhere, and it makes no sense, ie it becomes rather more difficult to read, the scene dock . . However, on the ' Add Node ' list, it is a very big help, for beginners, so one can find the correct node . . My proposal is, change the name of the ' Spatial node ', to Node3D, which is a lot easier, and change name of ' SpatialMaterial ' ( Godot 3.2 ) from ' StandardMaterial3D ' ( Godot 4.0 ) to ' PBRMaterial3D ', and ' ShaderMaterial ', to ' ShaderMaterial3D ' . . Those are the biggest ones . . 

Only add the ' 3D ' to a node, on the Add Node list, so on that list, it says Camera ( 3D ), or Camera [ 3D ] or, Camera_3D, or Camera.3D . . The changes in the names in Godot 4.0 have been a large improvement, but it becomes more unreadable, in the Scene Dock, or Scene Inspector, where all the names has 3D after them . .

![2020-07-20 0725](https://user-images.githubusercontent.com/61069740/87902684-98f0b280-ca5a-11ea-8787-f25988291ee1.jpg)

![2020-07-20 0728](https://user-images.githubusercontent.com/61069740/87902695-9e4dfd00-ca5a-11ea-96d5-c4ad817bf740.jpg)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

First of all, the new name changes in Godot 4.0 are AMAZING, the ' Add Nodes ' list is so much more user-friendly, the added 3D to all 3D related nodes, means you have no doubt, which node to click, at all . . It's a major improvement, for all users . . 

However, it has created a problem, where the Scene inspector becomes more unreadable, or difficult to read, with 3D added to every node, so it all looks the same, confusing . . . My proposal is, add a ( 3D ) behind all 3D related nodes, like extra information, but don't add it behind the nodes, in the inspector . .

Also, maybe change the name of MeshInstance, to simply Mesh3D, or 3DMesh, or so, MeshInstance is a bit misleading, as ' Instances ' in game engines, typically are like ' prefabs ', and it's a bit confusing, I  think . . . Or, MeshPolygon, or MeshObject3D . . These are minor things, as the improvements in Godot 4.0 already makes it better than 3.2, a lot, but it has created a problem, when reading the Scene Dock, where all the +3D, makes it a confusing mess, where it's difficult to immediately read which node, is what, it's all just 3D, less readable in that dock . . So, please keep the + 3D in the Add Node panel, or write ( 3D ) behind all 3D nodes, just don't add it in the scene dock, because, it all becomes a blur, it takes more time, to read that <3 . . 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I added pictures above, but idea is, add the 3D so one can quickly, or better see which nodes are 3D when ADDING them, as a node, but don't write MeshInstance3D in scene dock, because suddenly when trying to read it, all the 3D at end, makes the nodes look the same, hope that makes sense . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I can't do this, as a new user, I don't know how . .

**Is there a reason why this should be core and not an add-on in the asset library?:**

Well, the Godot 4.0 name changes are a POSITIVE step, in the right direction, it's far more user-friendly, but it creates an UNKNOWN problem, ie it makes the scene dock more unreadable . . I suggest instead of writing MeshInstance3D, the add node panel says MeshInstance ( 3D ), so it's clear when adding nodes, but doesn't change the name, or add +3D, in the scene dock, that would be very nice . . .

It would help, also consider changing MeshInstance, to 3DMeshNode, or MeshObject, Mesh3D, or PolygonMesh . . MeshObject, as a new user, I don't want to create an instance, of a prefab, just a 3DMesh, or a 3DObject . . Just saying, Godot 4.0 is better, than 3.2 in terms of names, by far, but the many +3D in the scene dock, makes all the nodes look the same, and I have to read the name twice, to see which one it is, a consequence of the new name-changes, that are VERY good, all the same . .

Thank you . .

**Comment by jasperbrooks79** [comment]
I guess problem is, we needed to more clearly see, in Add Node list, what was 3D, but in the Scene dock, especially with a lot of nodes, that all say 3D, it becomes a bit more unreadable . . My suggestion is, make sure all 3D related nodes in the Add Node Menu has not name MeshInstance3D, but maybe MeshInstance (3D), but that it doesn't carry over, into scene dock, where the game is structured, it gets pretty unreadable, with 3D behind every node, so they look the same . .

![2020-07-20 0744](https://user-images.githubusercontent.com/61069740/87903694-e5d58880-ca5c-11ea-8b89-8c8c558e8ce8.jpg)

For a short list, it doesn't matter, but when there are 100 nodes, and it says 3D all over the place, it gets hard to read . . Maybe, there is a good solution . . . Overall, 4.0 changes are a MASSIVE improvement, for sure, Thx . . .

**Comment by jasperbrooks79** [comment]
I hope this explains, what it's like to read scene dock, with 3D added, all over place, thanks . .

![2020-07-20 0753](https://user-images.githubusercontent.com/61069740/87904210-19fd7900-ca5e-11ea-915c-d53e97db8e11.jpg)

Like, that part gets harder, even if the names in Add Node are MUCH better, maybe there's a fix, or so . . . <3

**Comment by Calinou** [comment]
Closing due to lack of support (see lack of activity here).
