### ISSUE TITLE
Make an Godot 4.0 Pre-lim build with the features we've already seen . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1231]
**Describe the project you are working on:**
A Tomb Raider, adventure title . .

**Describe the problem or limitation you are having in your project:**
Okay, I've been trying Godot 4.0 and, it is already amazing, looks like Unreal engine, basically . . . I was wondering if you could make it a goal, to finish some of the nice features you have already, so we can have a Godot 4.0 where those core features are working, so we can start having fun, it's just amazing . . . Decals, sdfgi, all those good things, would be so fun if we could get a Godot 4.0 Basic build, where those features work, and then we can get the full package, with all the engine dev planned features, anyway I'm so blimey excited, it would be so cool, omg Please consider . .

The proposal is, make a Godot 4.0 Stable, with SOME of the planned features working, so we can start using it, if possible . . Might be too much work, don't know how it is, to make an engine, looks very advance, HAVE to ASK, Godot 4.0 ! ! <3

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I think that's enough, a working Godot 4.0 with sdfgi, decals, some of the smaller features, so we can start having fun, had too much fun with Godot 4.0 temporary build <3

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I just need more Godot now, <3 ! ! . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Can't wait, Please hurry, give us anything ! ! <3

**Is there a reason why this should be core and not an add-on in the asset library?:**
Hurry . . . ! ! :O

![2020-07-20 1554](https://user-images.githubusercontent.com/61069740/87945685-6322ec80-caa1-11ea-8ae9-369d502e8ebc.jpg)

Godot, is the business ! ! :O :O

**Comment by Calinou** [comment]
There are long-term plans to offer official nightly builds, but in the meantime, you can always use my [nightly builds](https://hugo.pro/projects/godot-builds/).

**Comment by groud** [comment]
Please, don't open proposal for things that are already planned. 
Be patient, there is no need to open proposal asking contributors to hurry up.

**Comment by jasperbrooks79** [comment]
Thank you, I'm so excited, so excited . .

**Comment by SIsilicon** [comment]
> but there will probably be an alpha release in 2020.

Emphasis on **probably**.
