### ISSUE TITLE
Integrate the `custom_modules` SCons parameter with Visual Studio project generation

### ISSUE THREAD

**Issue by GoDino** [godotengine/godot-proposals#1232]
**Describe the project you are working on:**
setup where multiple games are started from a selection "game"

**Describe the problem or limitation you are having in your project:**
when building with the "vsproj" parameter, the "custom_modules" parameter is not integrated with the vs project, so the visual studio build does include the "custom_modules" path and will therefore differ from the command line build.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
if "custom_modules" is used with "vsproj=yes", the "custom_modules" parameter is also included with the scons commands emitted by visual studio.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
methods.py -> generate_vs_project could check for the existence of the "custom_modules" parameter and include it if found:
```python
        custom_modules_flag = ""
        if env["custom_modules"]:
            custom_modules_flag = 'custom_modules="%s"' % env["custom_modules"]
        env["MSVSBUILDCOM"] = build_commandline(
            "scons --directory=\"$(ProjectDir.TrimEnd('\\'))\" platform=windows progress=no target=$(Configuration) tools=!tools! %s -j%d" % (custom_modules_flag, num_jobs)
        )
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
anytime there is a custom modules location, it will have to be passed to compile successfully and VS would be expected to give the same result as the command line, so it would be used everytime. It can be worked around by adding the path by hand in VS, however it would be expected behaviour and be less confusing if the VS project contained the path as well.
Especially when overriding an existing module in this fashion, a potential error would not be easy to track as it would still use the unmodified code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
it is a compile enhancement, code is not affected

**Comment by Xrayez** [comment]
@GoDino does the snippet actually work? If yes, you could [create a pull request](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) yourself if you want, or I could add this myself and add you as a co-author. I do have Visual Studio installed to get this tested but I don't use it extensively for Godot development...

This was requested by @fire as well in https://github.com/godotengine/godot/pull/36922#issuecomment-626361172.
