### ISSUE TITLE
Voronoi noise texture

### ISSUE THREAD

**Issue by 3top1a** [godotengine/godot-proposals#1236]
I'm trying to make a crater generator, which requires a Voronoi noise texture.
The Voronoi noise texture should be like open simplex noise texture, able to be created in a noise texture.
The code could be similar to blender's Voronoi noise node, with multiple distance metrics (Euclidean, Manhattan, etc.)

This has an implementation in the Godot asset store using viewports and shaders, but it would be more efficient in code using noise textures.

**Comment by clayjohn** [comment]
Please see [Rule #1](https://github.com/godotengine/godot-proposals#rules-for-submitting-a-proposal) for submitting proposals:

> Only proposals that properly fill out the template will be considered. If the template is not filled out or is filled out improperly, it will be closed.

Please update your proposal to follow the template or else it will be closed. 

Also note, there is a [PR](https://github.com/godotengine/godot/pull/35144) awaiting review that adds voronoi noise among many others.

**Comment by 3top1a** [comment]
Thanks (for the pr)!
