### ISSUE TITLE
Show the serialized Visual Script as text

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1240]
**Describe the project you are working on:**
A Tomb Raider, climbing, traversal game . .

**Describe the problem or limitation you are having in your project:**
Gamesfromscratch had a video, where Lumberyard 1.25 has a window, where one can see the written code, that the visual scripts do, that would be a nice feature, in visual script, since it could help coders, and visual scripters talk, help visual scripters learn code, and help written coders debug visual scripts . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It's in the latest video from Gamesfromscratch, Lumberyard 1.25 has it, it would really help visual scripters move to code, as they don't scale well, ie becomes spaghetti and, create a more unified community . . Thx . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It's basically just a dock, where visual scripts real-time, are turned into written code, it also turns it directly into C#, maybe visual script could do that, or GDScript . . So, cool . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so, Lumberyard 1.25 has it, very nice . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Like above, it would unify the coding and, visual script community, a lot faster, and help teach code, ie be a new way, for new or, inexperienced users, to learn written code, over time . .

**Comment by Calinou** [comment]
If I recall correctly, VisualScript isn't compiled to GDScript, C# or C++. It uses its own virtual machine.

**Comment by jasperbrooks79** [comment]
Oh, I saw a video a long time ago, but I forgot it, it said that if one renamed a .vs visual script file, to something like, .scen, or .tscn, one could read it, as GDScript . . I've been looking for it ever since, saw it when I was just starting out, but I can't find it, some obscure visual script tutorial, 4 - 5 months ago . . .

I made a mistake, it is in Bolt 2, for unity, where the visual script can be seen, as written code . . .

https://www.youtube.com/watch?v=KRb_gYM2jr8

Notice lower dock, with C# converted, from the visual script, as one makes it . .
![2020-07-22 1059](https://user-images.githubusercontent.com/61069740/88156991-7a311e00-cc0a-11ea-8724-03c6dfe2d03b.png)

I saw in a video, one can change name, from .vs, to, something, like .scen, and then re-import it, then one can read it as a .gd, but I lost the video, some guy figured it out, but a long time ago, maybe the engine makers could include that . .

I have a deep wish to learn written code, and write my own, like the hard-core game developers, and it would really help me, get to that point, thx . . A suggestion, might be super-complex, don't know . . . I have never coded a single line, only beginner visual script . . :(

**Comment by jasperbrooks79** [comment]
The video where the visual script was converted, into GDScript might have been 3.0, or 3.1, at the time, I think 3.1 was latest official release . . . :(

**Comment by Xrayez** [comment]
I think the proposal's title could be changed to "Convert VisualScript to GDScript" then.

Note that on ideological level, Godot already does something similar for converting `VisualShader` to `Shader` resource, as seen in godotengine/godot#30152, which I think is a valuable feature for those who'd like to learn the shading language that way.

Similarly, makes perfect sense to be able to see how the same `VisualScript` would look like in `GDScript`. But I'm afraid that the real purpose of visual scripting in Godot is not something which was made for beginners... [The lead developer described visual scripting to be useful for giving ability for non-programmers to tweak the behavior of a game easily](https://twitter.com/reduzio/status/760120732911362048):

> Unlike Unreal, this is more meant as a complement to programmers, so game designers, level designers, etc. can work more easily.

**Comment by fire** [comment]
The godot VS language does not exist in a text format. It is the result of executing the nodes. There's texture format of the nodes as inputs and outputs converted to text, but I don't know if that is what you wanted.

**Comment by jasperbrooks79** [comment]
Thanks, I guess you know, what I really mean :) . .

**Comment by Xrayez** [comment]
@fire well why would one need to see the actual contents of visual script files as text? I think @jasperbrooks79 meant to say that it would be nice to actually convert `VisualScript` to `GDScript`, just read my post above. I understand that it's not trivial to implement but that's a valid feature proposal in my eyes. 🙂

**Comment by jasperbrooks79** [comment]
If you look at Bolt example, that has it, above, it would help visual scripters learn code faster and, also help coders debug visual scripts as well, ie it could be a nice stepping stone, to bridging the technical and, artistic community, and help make games faster . . The idea, is to have it like in the Bolt 2 example ( Unity add-on ), so you can see the ' code ', that gets made, or so . . If it's super-difficult, I'm sorry, not an expert . . .

**Comment by mrjustaguy** [comment]
VS to GDScript and the other way around is possible.. I've worked on a converter to get my VS into GDScript format.. However i found making it to work for all cases to take quite a lot of work when working in GDScript and so sorta scrapped the idea for now.. on an Engine level it might be easier but wouldn't know.

![VS](https://user-images.githubusercontent.com/50302479/88818010-82ff9200-d1be-11ea-97c3-9dfe7a9f53da.png)

This is the general idea of how it works.
Red arrows are Next line of GDScript code, Blue arrows are collecting the variables

The example above would generate
`func Function(FVar):
   if var1==true:
      Node(Fvar math var2)`
by doing these things: 
1.Getting the current function aka Function and getting it's Variables (FVar in this case)
2.Following Sequence to next node (If in this case)
3.Grabbing Inputs (var1 in this case)
4.Continuing Sequence to next node (Node in this case)
5.Grabbing Inputs on Node (gets Math)
6.Grabbing Inputs on Math (gets FVar as 1st input and var2 as 2nd input)
7.Compiling the whole argument path and getting FVar math var2
8.Putting the argument on the right place in Node (so 1st argument as it has only one input, if it had 2 or more and it was on the 2nd and 1st one wasn't connected it'd be `Node(null,Fvar math var2)`)

GDScript to VS would actually be easier in a way, as all I'd have to do is go line by line and spawn nodes of the appropriate stuff and connecting it, however i'd have to have more of an idea what is actually what in GDScript vs VS
