### ISSUE TITLE
Automatically convert all leading spaces into tabs

### ISSUE THREAD

**Issue by AbominableMonkey** [godotengine/godot-proposals#1241]
**Describe the project you are working on:**
multiple small projects, to get comfortable with Godot

**Describe the problem or limitation you are having in your project:**
as being new to Godot, I try to incorporate code from previous languages, so I don't have 
to write it all again.
But copy an paste litters the code with both 'tabs and spaces'
and sometimes even after deleting one or more lines, the editor still notices an invisable space.
I had to rewrite the code in notebook, for Godot to accept it without errors...
 
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
if the editor disallows spaces in front of lines, just convert them automaticly into tabs.
if ' for instance' you leave a space in your next line of coding, and it is converted; you either don't notice, or don't care.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
that's a bit elaborate...

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no, as that 'is' the problem.

**Is there a reason why this should be core and not an add-on in the asset library?:**
no. I suppose only coders new to Godot are having this issue.

**Comment by Calinou** [comment]
There's a pull request implementing this: https://github.com/godotengine/godot/pull/28561

**Comment by KoBeWi** [comment]
The easiest way to get rid of unwanted spaces is Shift + Tabbing until all indentation is gone and then Tabbing everything properly. Easier than rewriting the code at least.

**Comment by AbominableMonkey** [comment]
I did remove all indentation on all the lines I pasted in. There was no visible indentation left. I even got a parse error when I deleted the line with the error on it.(it just skipped to an other line)
Convert on paste would be a good idea, but not needed if Godot just converted any spaces left in indentation, when the focus is of that line. (but probably more intrusive?)

**Comment by KoBeWi** [comment]
> if Godot just converted any spaces left in indentation, when the focus is of that line.

Running checks like this for each line could potentially kill the performance of Script Editor.

**Comment by AbominableMonkey** [comment]
Thanks fire. You make me appear less illiterate. ;)

**Comment by akien-mga** [comment]
This is pretty much covered by the changes proposed in #3525, so I'll close this as duplicate.
