### ISSUE TITLE
Add a navigation scheme based on Alt + mouse buttons in the 3D editor viewport

### ISSUE THREAD

**Issue by soundsbeard** [godotengine/godot-proposals#1245]
**Describe the project you are working on:**  
any 3d project

**Describe the problem or limitation you are having in your project:**  
im a 3d artist and i experience lack of a convenient navigation in 3d viewport.  
mainly, i work in blender, but have been learning 3d with some other software, which is using so called 'industry standard' input and navigation.
some time ago blender devs managed to solve a problem with industry standard input.  
they analyzed the main market including not only 3d content software but also 3d game engines like unity and UE:  
https://developer.blender.org/T54963  
i realize, that game engine is not a place to create 3d content, but as a 3d artist i do a lot of greyboxing, and a scene, which requires 15 mins to greybox in blender, takes hours in godot.  
some of the blender specific features in godot are under development as you can see in this thread and i like them a lot:  
https://github.com/godotengine/godot-proposals/issues/1215  
but what i would like to see in godot is this:  
https://i.imgur.com/gk0Yewc.png  
it is a navigation using alt + mouse buttons combinations.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**    
so, implementation of this industry standard navigation actually differs from software to software.

lets take zooming (alt+RMB) for instance.  
while zooming, blender takes the position of a cursor and takes only the value of Y coordinate as if a screen was an XY coordinate plane.  
so you move cursor up and down to zoom in and out respectively, like in cinema4d, maya(inverted), 3ds max.   
https://i.imgur.com/CFArSiR.mp4  
unity and UE take both X and Y coordinates of a cursor (which is very annoying imo).  
unity: X+ and Y- to zoom in, X- and Y+ to zoom out:  
https://i.imgur.com/Wj6oDsv.mp4  
UE: same as unity, but can be inverted it settings:  
https://i.imgur.com/8cgpAlZ.png  

now panning (alt+MMB):  
well, all the applications besides UE have natural panning, while UE has inverted panning (can be inverted it settings).  

and orbiting (alt+LMB):  
all applications have natural orbiting (even UE).  

so this 'industry standard' navigation implemented in godot would save time and nerves tremendously.  

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**  
i hope that i've described everything above in the most clear way.  

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**  
according to the fact, that making a game is a long and complicated process, 3d game developers/artists will jump from one app to another, it is inevitable. so i assume that this enhancement will be used often.

**Is there a reason why this should be core and not an add-on in the asset library?:**  
because keeping the workflow homogeneous is very important thing.

**Comment by Calinou** [comment]
The issue with the <kbd>Alt</kbd> modifier is that most Linux window managers will intercept it by default. We don't want to require all users to change their window manager modifier key to <kbd>Meta</kbd> just so they can use Godot's 3D features.

**Comment by soundsbeard** [comment]
> For the record, a large portion of Godot's user base is on Linux.)
 im a linux user myself, and by no means im asking it be the default.
yes, i've changed my modifier key to Meta key, but for now all i want is to have just an option to use alt + mouse in godot.

**Comment by soundsbeard** [comment]
i appreciate your help, @Calinou. maya navigation scheme is exactly what i was looking for.  
but why would you add new information by editing your reply instead of posting a new one?
i've been waiting for new comments, and as far as i know 'editings' doesn't have notifications on emails, and the answer was here all this time ._.
not cool

thanks for help once again, and this thread can be closed i think.

**Comment by Calinou** [comment]
@soundsbeard Sorry for the inconvenience. I typically edit my comments to avoid multi-posting (which looks odd).
