### ISSUE TITLE
Clicking the line number gutter in the script editor should select that line of code

### ISSUE THREAD

**Issue by Cambysses** [godotengine/godot-proposals#1247]
**Describe the project you are working on:**
Very new to Godot, just starting on some simple tutorial projects.

**Describe the problem or limitation you are having in your project:**
No shortcut to select line of code in text editor.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In most code editors, you can click on the line number to select that line. Godot's built-in editor lacks this feature, unless I am doing something incorrect.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Left click line number in text editor --> Line becomes highlighted and selected

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a very basic feature common to most editors that I am aware of. 

Thanks 🤠

**Comment by Calinou** [comment]
This is already implemented when you click-and-drag the cursor over multiple lines. It's just that *clicking* on a line number won't select the whole line (like it does in VS Code, for instance).

**Comment by bojidar-bg** [comment]
Note that only the area on the left of the line number is used for setting breakpoints, so this proposal will not conflict with breakpoints.
