### ISSUE TITLE
Change the hash identifier of the daily / nightly build to date / time . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1252]
**Describe the project you are working on:**
I fudge-me love seeing, the new Godot 4.0 build, it's so awesome, I'm mind-blown . . .

But, I can't see if it has been updated, since last time I tried it, anyway, I was thinking if maybe the hash number, could be the date, or have parts of the date, 0724 ( July, 24 ), month, or so, somewhere . .

**Describe the problem or limitation you are having in your project:**
Godot 4.0, has me excited, in numerous ways . . . Being able to try the latest build, as someone who is new to the engine, but loves geeky things, is pretty cool . . . But, I can't see the date, to see if there's a new version, not sure, if it's intended, it's confusing . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I would like to know when there's a new update, so I can check back, and quickly see, if there's a reason to download the 4.0 nightly build, maybe just some small letters, on the page, in a corner, update 24-07-20 - 18:04, or so . . Like, if it was in the hash number, mixed with the letters, like adgfid2407, that'd be cool . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Downloading the 4.0 as is, is too good . . . But, the date is missing, don't want to miss anything . . :((

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's just, a suggestion, hope, it is okay, fine . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
I can't always answer this question but, I really try . . I don't think so . . :O :O . . . . ;)) . .

**Comment by Calinou** [comment]
There's already an issue about displaying the date of the latest nightly build available: https://github.com/Calinou/godot-builds-ci/issues/2

It can be done easily. However, each build has its own manifest since different builds may fail occasionally. I don't want to display 6+ build dates on the page as it looks messy, so I'd prefer a solution that looks less cluttered.

**Comment by jasperbrooks79** [comment]
Okay, thank you, I knew there was a reason . .

I will download it every other week, on friday evening, to celebrate weekend, that way . . <3 :DD . . .

**Comment by Calinou** [comment]
Closing, as this repository should be used for *official* Godot resources only. My nightly builds aren't official :slightly_smiling_face:
