### ISSUE TITLE
Make grouping exported variables easier

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot-proposals#1255]
**Describe the project you are working on:**
2d space game

**Describe the problem or limitation you are having in your project:**
My nodes (e.g. planets, stars) have a LOT of exported variables, often thematically grouped (eg. physical properties and cosmetic stuff, ship physics and AI stuff and cargo...)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
We already have a workaround to group the exported variables, https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_exports.html#adding-script-categories , but it is... NOT pleasant to use.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The syntax proposed in PR #40669 is the following: cosmetic (section, "sectionname"): followed by an indent and any variable declarations wanted.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be worked around, but it takes TOO many lines of script (circa 10 per each variable, times 10 variables, that's around 100 lines just for that - and in another project, I have nodes with 20 variables...)

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't think addons can do such deep injections into the inspector, AND the same NEEDS to apply to remote scene tree debugging, where the issue is exacerbated by also showing non-exposed variables.

**Comment by groud** [comment]
> Make grouping related variables easier.

Sorry, but this is not a description of the feature or how it would be implemented... Could you at least copy-paste the syntax proposed in the PR related to this proposal. This is the things that should be discussed, not "making something easier", which isn't really a proposal...

**Comment by Zireael07** [comment]
Whoops, it was fairly late and I didn't notice I put it in the wrong place :P - updated.

**Comment by golddotasksquestions** [comment]
Direct Link to the PR: https://github.com/godotengine/godot/pull/40669

**Comment by Calinou** [comment]
Now that we have GDScript annotations, I suppose we could have a `@category("Category Name")` annotation. Here's what would happen:

- Properties would be grouped automatically with categories of the same name.
- A **single** boolean property can have a `@category_toggle("Category Name")` annotation. This is used to toggle the display of *all* properties within a category except the toggle property itself.
  - If there is more than one, print a GDScript parse error.
  - If this is used on a property that's not a `bool`, print a GDScript parse error.
- If only a single property is added to a category, print a GDScript warning as this is considered bad practice. People will have to unfold the inspector only to see a single property. Spare people's mice :slightly_smiling_face:

**Comment by pycbouh** [comment]
For posterity, vnen's proposal regarding grouping annotations [was](https://github.com/godotengine/godot-proposals/issues/828#issuecomment-629270690):

```gdscript
@export_category("category")
@export_group("group", "prefix") # All variables with name starting with "prefix" are added to the group.
```

**Comment by fire-forge** [comment]
This is a great idea! It would really help in cases like this where there's lot of properties that have the same prefix. If all of the `tile_*` properties could be in a group, that would make it a lot cleaner.

![image](https://user-images.githubusercontent.com/67974470/164337051-719be63e-cd4f-4d7d-8b92-d17b433f861d.png)

> ```gdscript
> @export_category("category")
> @export_group("group", "prefix") # All variables with name starting with "prefix" are added to the group.
> ```

An `@export_subgroup("subgroup", "prefix")` annotation for exporting subgroups would be a nice addition as well, but definitely not as important as a group annotation is.
