### ISSUE TITLE
Add Support for Applying Scale

### ISSUE THREAD

**Issue by I7SOD** [godotengine/godot-proposals#1256]
**Describe the project you are working on:**
I am currently learning godot

**Describe the problem or limitation you are having in your project:**
There a lot of scaling issues that arise from using `floating ` or `non-uniform` scale values in the editor ranging from making calculations with them and so on which I think other users should have noticed.
![ScaleIssue2](https://user-images.githubusercontent.com/51547693/88443603-cf3e8100-ce10-11ea-8c5a-6b10667eee0e.PNG)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding an apply scale button at the end of scale after changing the scale to make the scaling be a `uniform ` 1 to 1 scaling like that available in blender .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Using blender as an example after changing the scale of objects in blender and using the `apply-scale` functionality in blender, the scale becomes uniform again which now makes it easier to make calculations based on the scale.

![ScaleIssue1](https://user-images.githubusercontent.com/51547693/88443991-c9e23600-ce12-11ea-8733-6c30694643aa.PNG)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think you can use scripts to fix this problem.

**Is there a reason why this should be core and not an add-on in the asset library?:**
The scale options are part of the core functionalities of Godot : Node2D, Spatial and Control nodes

**Comment by groud** [comment]
Applying a scale in blender does modify the mesh itself. There's no equivalent in Godot at all, you cannot modify the mesh's vertices to apply the scale. At most we could have another "internal" scale to hide the real value, but I really don't see the point...

If you need to "make calculation", remember you can simply type expression directly inside the inspector's fields. Like typing "0.73 * 2" would be automatically computed to 1.46.

**Comment by Calinou** [comment]
> There's no equivalent in Godot at all, you cannot modify the mesh's vertices to apply the scale.

This is available for OBJ meshes at import-time (check the Import dock).

**Comment by I7SOD** [comment]
Wow I didn't know that

**Comment by Calinou** [comment]
Closing, as this isn't something that can be implemented at the inspector level (and this feature is already present in the OBJ mesh and 3D scene importers for all 3D scene formats).
