### ISSUE TITLE
Improve the font rendering quality by using LCD subpixel optimizations

### ISSUE THREAD

**Issue by bluenote10** [godotengine/godot-proposals#1258]
**Describe the project you are working on:**

A guitar practicing application ([here](https://www.youtube.com/watch?v=odWXE5Dv9HQ) is an old version but in VR).

In general, interested in non-game use cases of Godot.

**Describe the problem or limitation you are having in your project:**

I cannot achieve the high quality font rendering I want (and I get with native applications -- which in my case is Linux).

I've setup a [small demo project](https://github.com/bluenote10/GodotDebugProjects/tree/master/FontRendering) to illustrate the problem. The example uses the "Ubuntu Medium" font, but the problem is not specific to this font -- all fonts I tried suffer from the problem.

In the demo code the "Use Filter" and "Use Mipmaps" settings on the font are enabled, as well as the "Rendering > Quality > Dynamic Fonts > Use Oversampling" setting. Depending on the hinting mode the result ranges from:

*Normal hinting:*

![image](https://user-images.githubusercontent.com/3620703/88452235-56b1e180-ce5d-11ea-9e05-75ac5b3607ab.png)

*Light hinting:*

![image](https://user-images.githubusercontent.com/3620703/88452245-71845600-ce5d-11ea-8668-69a07ae32ec2.png)

*No hinting:*

![image](https://user-images.githubusercontent.com/3620703/88452275-9d074080-ce5d-11ea-9965-cf7df0939a5d.png)

This looks much worse compared to what I get from native font rendering. For instance this is how the font looks in the native font viewer:

![image](https://user-images.githubusercontent.com/3620703/88452298-cde77580-ce5d-11ea-8b78-da3069c584c9.png)

Or this is with rendering the font in the browser (Firefox):

![image](https://user-images.githubusercontent.com/3620703/88452311-e9528080-ce5d-11ea-8204-729bfe615b2a.png)

It may help to zoom into the images to see the differences in font hinting.

Overall I'm seeing this low quality font rendering in all Godot-based applications I've tried, and also the fonts in the editor always looked slightly off to me. [Others seem to observe the same](https://www.reddit.com/r/godot/comments/cskigl/is_there_any_way_to_get_better/). There are also related open issues e.g. https://github.com/godotengine/godot/issues/30643 or https://github.com/godotengine/godot/issues/31495.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Come up with a solution for high quality font rendering. This needs planning by the experts ;).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I'm not expert on the topic, but my guess is that the missing piece is subpixel hinting / aliasing. But maybe there are other ideas?

I assume Godot uses Freetype, and Freetype in general seems to support [subpixel rendering](https://www.freetype.org/freetype2/docs/reference/ft2-lcd_rendering.html). [This post](https://www.reddit.com/r/godot/comments/cskigl/is_there_any_way_to_get_better/) suggest that it might be possible, but may be tricky due to color blending modes. 

Nonetheless, subpixel rendering is a standard in native applications, and for non-game use cases, users may expect font rendering to be on par with native font rendering. It would be great to give users the option trade rendering performance for higher quality font rendering.

**Is subpixel rendering not outdated and HiDPI displays will solve the problem in the long term?**

On the ambitious gaming side that is hopefully true. But on the other hand, 1080p is such a prevalent resolution, that it is unlikely that it disappears entirely any time soon. Especially for non-game applications I think it is likely that 1080p is still around for quite a while, and on 1080p subpixel rendering seems to make a big difference.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't see a work-around, because font rendering is something fundamental in the engine.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Probably the same applies: font rendering is something fundamental in the engine.

**Comment by bruvzg** [comment]
> I assume Godot uses Freetype, and Freetype in general seems to support subpixel rendering.

Godot uses Freetype, and Freetype do support subpixel render modes (FT_PIXEL_MODE_LCD / FT_PIXEL_MODE_LCD_V), but rendering it is not implemented in Godot, here's relevant `DynamicFont` code: https://github.com/godotengine/godot/blob/963d3a07bd0c71ec70d1ec0bf19ff068c4cfa377/scene/resources/dynamic_font.cpp#L504-L526

**Comment by Calinou** [comment]
@bruvzg I looked into exposing subpixel optimizations in Godot, but it seems there's a complex blending operation needed as the optimization varies depending on the background color.

**Comment by bluenote10** [comment]
> @bruvzg I looked into exposing LCD subpixel optimizations in Godot, but it seems there's a complex blending operation needed as the optimization varies depending on the background color.

I'm wondering how e.g. browsers solve this problem. Do they really have to query each underlying pixel :thinking: 

For many UI purposes, maybe it would be good enough to go for a heuristic: Instead of really blending with the true underlying background color, the user could configure a "default background color" per font. Since one dynamic font instance is often drawn onto the same background color (or only slightly varying background colors where the "default background color" would still be a good approximation), this may solve the problem in many cases without making it overly complex?

**Comment by jeancallisti** [comment]
+1 to this proposal.

Every time I open Godot, **I have this disturbing initial impression that the game Editor's UI text is slightly blurry.** And that's definitely because everything else in Windows (especially Visual Studio, which in dark mode and looks very similar to Godot) is rendered using Microsoft's **subpixel rendering method** (described above) called ClearType, which makes use of red and blue to draw even black and white letters. 

Godot does not have that -- everything is pure gray on dark blue or dark gray. Which is "good enough" but not the top solution.

**Comment by Calinou** [comment]
If anyone is interested into implementing this, these are the parts of the code you'll need to modify on `master`:

https://github.com/godotengine/godot/blob/f91e5bad8ce2ae30834e0f46be644dbc1d9daf10/modules/text_server_adv/text_server_adv.cpp#L1113

You'll need to make use of the `FT_LOAD_TARGET_LCD` and `FT_RENDER_MODE_LCD` constants. Also, remember that the font needs to be stored as RGBA (or BGRA), so the data size needs to be changed accordingly here:

https://github.com/godotengine/godot/blob/f91e5bad8ce2ae30834e0f46be644dbc1d9daf10/modules/text_server_adv/text_server_adv.cpp#L1018

Remember to apply the same changes in `text_server_fb.cpp` as well (which is used when HarfBuzz is disabled at compile-time to reduce binary size).

You will also need to add an enum property to FontData choose between various LCD subpixel optimization modes (Disabled, RGB, BGR, vertical RGB, vertical BGR): https://github.com/godotengine/godot/blob/f91e5bad8ce2ae30834e0f46be644dbc1d9daf10/scene/resources/font.cpp#L211

**Comment by bruvzg** [comment]
Not exactly the same as proposed solution, but might resolve original issue - https://github.com/godotengine/godot/pull/57877

> If anyone is interested into implementing this, these are the parts of the code you'll need to modify on master

In addition to the `TextServer` changes, implementing LCD sub-pixel rendering will most likely require changes to the `canvas` shader to correctly blend it, since `TextServer` do not process text color and has no information about background color to do it in place. Also, it will probably require some OS specific code to detect LCD sub-pixel arrangement.

**Comment by bruvzg** [comment]
For anyone who is interested in LCD sub-pixel rendering, but do not want to deal with the `TextServer` internals. Here's a test branch which implements everything except custom blending mode (so all LCD antialiased text is rendered on the black background).

<img width="540" alt="aa_lcd_test" src="https://user-images.githubusercontent.com/7645683/153407831-a3698461-5b27-4248-b964-d9332d894196.png">

https://github.com/bruvzg/godot/tree/make_fonts_unbearably_ugly

If I'm not mistaken, custom blend mode should look something like this (font texture essentially contains 3 separate alpha channels for each color), but I have no idea where to add it:
```c++
dst_r = text_r * modulate_r * modulate_a + dst_r * (1.0 - text_r);
dst_g = text_g * modulate_g * modulate_a + dst_g * (1.0 - text_g);
dst_b = text_b * modulate_b * modulate_a + dst_b * (1.0 - text_b);
dst_a = modulate_a + dst_a * (1.0 - modulate_a);
```

**Comment by Calinou** [comment]
> Isn't the red/blue hue shift enough?

For LCD antialiasing to look correct, you need to use a special blending formula that is not found in most real-time rendering engines.

**Comment by bluenote10** [comment]
Would it be possible to configure the background color? This could avoid the need for a truly alpha-based blending mode. 

Assuming a fixed opaque background color would probably work well in many text-focused use cases, because they often render on uni-color backgrounds anyway. Even if text is rendered on backgrounds with a subtle texture, using the "mean color" should still give reasonable results. It only becomes a problem when rendering on e.g. color gradient background or high contrast backgrounds (but rendering text directly over a high contrast background isn't very legible anyway, so not really a typical use case of subpixel hinting).

The only real benefit of an alpha-based blending mode in these use cases would be that the user doesn't have to "sync" the background color information between the actual background and the text property.

**Comment by bruvzg** [comment]
It's possible to apply blend with the screen reading shader (add canvas item shader material), and blend formulas I have mentioned in the previous comment seems to be working correctly:

```glsl
shader_type canvas_item;

uniform vec4 modulate;

void fragment() {
	if (COLOR.a == 1.0) {
		vec4 text = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0).rgba;
		
		COLOR.r = COLOR.r * modulate.r * modulate.a + text.r * (1.0 - COLOR.r);
		COLOR.g = COLOR.g * modulate.g * modulate.a + text.g * (1.0 - COLOR.g);
		COLOR.b = COLOR.b * modulate.b * modulate.a + text.b * (1.0 - COLOR.b);
		COLOR.a = modulate.a + text.a * (1.0 - modulate.a);
	} else {
		COLOR.a = 0.0;
	}
}
```

Note: It's just a test, and not intended for real use, since material is applied to the whole control, not just text it will break rendering of control icons / styleboxes. And screen reading shaders are slow.

![Screenshot 2022-02-11 at 13 30 31](https://user-images.githubusercontent.com/7645683/153584646-863b3a1a-f9f9-45bf-8bd4-3aafadf3897a.png)

> Would it be possible to configure the background color?

It is possible to do, but most users probably expect text to work on any examples. Hack like this can be used for the specific project, but probably are not acceptable for the engine.

**Comment by bluenote10** [comment]
> It is possible to do, but most users probably expect text to work on any examples. Hack like this can be used for the specific project, but probably are not acceptable for the engine.

Subpixel rendering could be seen as an advanced use case that could justify some extra effort on user side (I wouldn't mind). The approach also has performance benefits, because the rendering could be done more efficiently if the blending can assume a fixed color, instead of having to do real alpha blending. Note that some browsers do similar things when it comes to subpixel hinting. For instance, as far as I remember Firefox disables subpixel hinting when rendering on transparent `Canvas` elements, and only enables it when rendering on opaque mode for performance reasons.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/64422.
