### ISSUE TITLE
Introduce bi-monthly regular hotfix releases

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#126]
**Describe the project you are working on:**

Top down 2 d game with survival elements

**Describe the problem or limitation you are having in your project:**

Currently Godot sufferes from small bugs here and there due to fast pace of it's development. Many of those bugs are fixed over time however users need to wait for major releases to benefit from those fixes. There is option of building from source but this introduces whole bunch of problems of working with partially completed features of next big release. 

Providing more regular hot fix builds as often as every other month would allow comunity to benefit from all the work that bug fixers are doing without introducing serious changes to the editor itself.  We already had version 3.1.1 getting versions 3.1.2 and 3.1.3 before 3.2 is released would be nice benefit for a comunity and wouldn't take away anything from a hype of new version combining with latest features in a future.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

It would provide comunity with more and more stable version of the engine without introducing big changes to editor itself and would be very safe for ongoing projects. 

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

N/A

**Describe implementation detail for your proposal (in code), if possible:**

Simply release compiled bug fixes branch to public more often.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This enhancement would be used all the time by almost every member of comunity as fixing bugs would benefit any projects. 

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by willnationsdev** [comment]
I'm curious about what the difficulties/bottlenecks are in this process. I'm sure it is some part manpower (which people - with access to creating releases - will put together these builds. Are there enough of them?), some part data (knowing which commits are cherry-pickable), and some part backend logistics (how do we ensure that we can make builds for every platform, quickly and consistently?).

How this stuff is set up isn't really outlined to the general public in any sort of documentation, so it's status is a bit of a black box. Perhaps there are people in the community that could help further with anything that makes the above proposal more difficult?

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/32233.

I think it would be a good start to provide official nightly builds of the `master` and stable branches (currently `3.1`).

**Comment by fire** [comment]
I also agree and both I and @Calinou know a lot of the process.

@akien-mga mentioned using Github actions through Azure?

That seems like the most direct route.

**Comment by Toshiwoz** [comment]
> 
> 
> See also [godotengine/godot#32233](https://github.com/godotengine/godot/issues/32233).
> 
> I think it would be a good start to provide official nightly or weekly builds of the `master` and stable branches (currently `3.1`). These could be fully automated to decrease the maintenance burden.

If possible, IMHO, it would be better to have one with the stable 3.1 release plus the cherrypicks only.
If you pick the master branch, probably it won't be "stable", as the stable version... lol, if that makes sense to you.

**Comment by Calinou** [comment]
@Toshiwoz The idea is to have both, so that a stable "patched" release is also available in addition to builds for early adopters.

**Comment by fire** [comment]
@Calinou I feel gitlab-ci flows are more open and easier to self-host gitlab / runners. This matches Godot's open source nature.

Do you know anyone who's started on a Gitlab cicd?

What are the problems with having a Gitlab instance mirroring Godot Engine's Godot git and generating the builds?

**Comment by Calinou** [comment]
My Godot builds system is now configured to build and upload a new build of the `3.1` branch every week (in addition to daily `master` builds): https://archive.hugo.pro/builds/godot/3.1/

I'll update the [web page](https://hugo.pro/projects/godot-builds/) to link to stable builds soon.

**Comment by Feniks-Gaming** [comment]
@Calinou are those stable bug fixes only builds or just regular weekly build?

**Comment by Calinou** [comment]
@Feniks-Gaming Those are regular weekly builds based on the `3.1` branch, which contain only bug fixes and small feature additions. See the [`3.1` branch commit log](https://github.com/godotengine/godot/commits/3.1).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1458 (which is very similar, but more frequent).
