### ISSUE TITLE
Add signals for device volume changes and output routing changes

### ISSUE THREAD

**Issue by hakoptak** [godotengine/godot-proposals#1264]
**Describe the project you are working on:**
A microphone-driven mobile game.

**Describe the problem or limitation you are having in your project:**
You play my game with a group of players in the same room. The game uses audio cues to communicate between devices. To make this work, the game needs to know the device volume and must be notified when this changes. When the volume is too low the game needs to notify the player to crank up the volume. Since the game depends on speaker output, it also needs to know whether headphones are plugged in. To my knowledge, Godot does not support these features.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
-When the device volume changes, the game must be notified with the actual volume.
-When the output routing is changed, the game must be notified about the actual routing (speaker/headphones).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I know that Android and iOS have these system features, but I am not an expert on the other platforms.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This is a core feature.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a system feature.

**Comment by m4gr3d** [comment]
@hakoptak both on Android and iOS, this feature request can be done via a platform specific plugin and doesn't need to be implemented in core.

cc @naithar

**Comment by naithar** [comment]
Yeah, it does look like module/plugin or GDNative library is the best way to approach this feature.
While plugins for iOS are not yet merged, GDNative support should be enough for volume notifications to work.

**Comment by hakoptak** [comment]
Okay, thanks for the direction. I'll look into it.

**Comment by m4gr3d** [comment]
@hakoptak I'm closing the proposals since it won't be implemented in `core`, but feel free to add comments if you have questions.
