### ISSUE TITLE
Add a toggle for globally disabling "filter" so people don't have to re-import their assets constantly

### ISSUE THREAD

**Issue by pajcek11** [godotengine/godot-proposals#1265]
**Describe the project you are working on:**
Adding pixel-graphics to my game like a normal human bean.

**Describe the problem or limitation you are having in your project:**
Every time I import an asset, I have to re-import it because someone thought it was a good idea to make all assets blurry upon default import (the notorious "filter" toggle)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In the settings, add a checkbox to globally disable filtering of new assets so normal people can just uncheck it and have their assets imported without the filter, instead of having to reimport them all the time 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Inside of Editor > EditorSettings > Filesystem > Import, there is a LOT of space where you can add a checkbox that says "apply filter by default"

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Oh, man, I'm sure there is a very good reason for filtering being the default, as it is also a problem in Gamemaker, but cmon. People use these types of engines for pixel games. And it's not a loud minority. If there is overwhelming proof that the vast majority (and not 50:50) like blurry and ugly assets in their games, then I wanna see that statistic.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is as basic as it gets. I'm surprised that it doesn't exist yet.

**Comment by Calinou** [comment]
> I have to re-import it because someone thought it was a good idea to make all assets blurry upon default import (the notorious "filter" toggle)

There are a lot of non-pixel art games out there (both 2D and 3D). For these games, disabling Filter is usually not a good idea.
 
You can already define an import preset as being the default by clicking the **Preset** menu button and choosing **Set as Default for 'Texture'**:

![image](https://user-images.githubusercontent.com/180032/88520700-38321e80-cff4-11ea-9865-85fa1ed445db.png)

**Comment by pycbouh** [comment]
It would be nice, though, if you could edit the defaults in the project settings. Having that option in a dropdown of the Import dock is non-intuitive and hard to discover naturally.

**Comment by KoBeWi** [comment]
This is already resolved in 4.0.

**Comment by Calinou** [comment]
Closing per @KoBeWi's comment.
