### ISSUE TITLE
Exported vars should automatically detect changes

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1268]
**Describe the project you are working on:**
Spaceship game

**Describe the problem or limitation you are having in your project:**
nodes don't update when their resource's variables change including nested data

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make changing resources and thier nested data update on the nodes end withing using properties and a tool script

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I would guess something similar to unity in which if you change something it updates in the scene and inspector 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it would be used quite alot especially in ui.
it also can be worked around but you have to update everything manually

**Is there a reason why this should be core and not an add-on in the asset library?:**
its help reduce the amount of code to do something that should already be part of the editor and how it serializes scripts.

**Comment by YuriSizov** [comment]
I'm going to close this proposal, as there doesn't seem to be much traction on it and it lacks implementation detail. Feel free to open a discussion in this repository, if you want to throw ideas for how to improve the existing behavior, so maybe a new proposal can be formulated later.
