### ISSUE TITLE
Add an option to export a HTML5 project as a Progressive Web App

### ISSUE THREAD

**Issue by yhcharles** [godotengine/godot-proposals#1269]
**Describe the project you are working on:**
A simple game targeting for web export.

**Describe the problem or limitation you are having in your project:**
I want to export the project as a PWA app, which can be played offline and "installed" on device for mobile as well as desktop. But it's not supported now. I can add partially support by using html template, but this solution doesn't generalize well. I still need to manually add/change some file after exporting.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
With official support, web export should be able to automatically generate the `manifest.json` as well as `service_worker.js` files, which makes the web export an complete PWA app.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I tried to follow Google's tutorial: https://codelabs.developers.google.com/codelabs/your-first-pwapp/#0 to add PWA support. And here's the commit enabling PWA for my toy project: https://github.com/yhcharles/yhcharles.github.io/commit/22553cb2483b56b7d5c2fffc6d6d48bf79ebe144

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It is possible, but still some manual work, and not so convenient.

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by darrinm** [comment]
Fantastic proposal! It would be great if the open web (HTML5) would be a viable alternative to delivering via walled-garden App Stores. PWAs can be installed, added to home screen and run offline so that goes a long way toward parity.

**Comment by Calinou** [comment]
> It would be great if the open web (HTML5) would be a viable alternative to delivering via walled-garden App Stores.

Keep in mind these have completely different performance figures, though.

**Comment by darrinm** [comment]
> Keep in mind these have completely different performance figures, though. Running HTML5 exports on mobile will never be as smooth as native applications.

No doubt. Question is if it is "good enough" for a given application considering the tradeoffs. I'm curious though @Calinou, do you know of any benchmarks or other comparisons specifically regarding Godot Engine? Maybe there are aspects that can be improved.

**Comment by kreaninw** [comment]
A very good proposal indeed 💯

With this option, it's not necessary for the players to wait for their favorite title to get ported on their system. It's totally possible to pilot a game/app on as many platforms as possible, then porting to a native later (if there's any demand there).

**Comment by Calinou** [comment]
Note that [PWA support was just added to the HTML5 editor](https://github.com/godotengine/godot/pull/46796), but it remains to be added for exported projects.
