### ISSUE TITLE
Add a new / better way to add important add-ons, when downloading the engine . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1271]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
I've been thinking, one reason that many add-ons are not ' core ', is to avoid the engine getting too big . . I had an idea, to make downloading some often asked for features happen, on the official download page . . So, the page looks like, so . .

To be clear, I know those suggestions are bad, ie. it would NEVER be that list, it's stupid . . But, it's an idea, for sort of taking some of the features people ask for the most, and put them there, so when one downloads the engine, those things are there, in the Godot game folder, as sub-folders, any game made in it, can reference . . Also, when one builds the game, those things would get exported, in the final game export . . Again, it's a very bad graphics, I have made, sry . .

![2020-07-27 1253](https://user-images.githubusercontent.com/61069740/88653941-02ad3400-d0cd-11ea-8b15-fdc4171971c2.jpg)

![2020-07-28 1224](https://user-images.githubusercontent.com/61069740/88654251-65063480-d0cd-11ea-96e8-618c2b017cc2.jpg)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I often find that I want to download finished, approved expansions, but they are not there, ie. I have to look for plug-ins, or google it, maybe this could be a good way to add features, that are OFTEN asked for, such as Terrain Editor, so the engine retains it's small size, for those who want that, and so one doesn't have to google, or look in the Assetlib for these things, since technically a terrain editor is not an ' asset ', that's more like 3D characters, tile sets, stuff you put in the game . .

This is a suggestion, but I think this would be very nice, and also so the core developers could make these things, since many people ask for them, but the core Godot engine stays small . . It would require that the engine would be able to use the directory the Godot.exe for engine is located, and store stuff there . . If one clicks an add-on, one knows the engine devs have looked at it, and that it is finished, and can be used . . It could be a way of expanding the engine, without bloating it . .

Those features would have to be integrated well with the engine, ie. if one selects something, on the list, it just works, and the extra menus, so on, are included . . To avoid bloating the engine, for instance, there could be a new tab, in a dock, or so, where one can select terrain . . I'm mentioning terrain, that's the only thing I can think of, but it could be other things, that the devs, and community want in the engine, but so far hasn't been developed, to keep the engine small, and light . . .

It's a proposal, since to me it's not clear, to look for stuff like a terrain editor in Assetlib, assets are typically stuff like 3D models, textures, or so . . It would also mean, a part of the core contributors could go all-in, on developing a good terrain system, with layered textures, without it adding, to the core engine download, unless it's specifically needed . . There could also be stuff, like a low-poly, mid-poly, high-poly character creator, with options to change textures, or colors on clothes, with animations, included . . Having it on the official download page would help me know, it's not a buggy feature, that some user have made and, that might crash, but it's been tested, a lot, by the core team, and works well with the engine . . It would lower total size of Godot download to a minimum, while providing support for much asked for features, at the same time, ie. you download what you need, not more . .

The ideas above are BAD, ie. it will probably be completely different things the devs, and contributors think belong there, but it would be nice, to able to download things that, are often asked for, but isn't in the core engine, because it might belong outside the ' core ' definition, of the engine . . It could also be away for contributors, and devs to add the features they feel are needed, without increasing the size of the download needlessly, and users would know, those things there, it's tested, good code, wholly endorsed by the engine makers, and, it works . .

Thx . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The pictures above hopefully show it, again, the things on the list are really ridiculous, completely wrong . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I feel some of the features many users ask for, but aren't in the core engine, could be developed there, and many users would enjoy it, and find it makes sense, also . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Again, I think this is a better way of doing it, and it would be immediately obvious to new users, downloading the engine, what they have to do, to get these things, ie. not look for weeks on the internet, to find out a random guy called Zylann made a plug-in, that might work, or so . . I know Zylann is hard-core, but I have no idea what I'm downloading, at all, could be buggy, un-supported, make the engine crash, or worse . . .

Thank you . . . :O

**Comment by jasperbrooks79** [comment]
Also, when one clicks to download an extra thing, only really big, often requested things, it should work well, and be well integrated in how Godot core works, ie. a nice user-interface, good functionality, official docs . .

:O <3 . .

To me, that would make the engine a lot better, and more user-friendly, nice . .

**Comment by jasperbrooks79** [comment]
Since the engine is downloaded as a single-executable, it might work if there was some zip-files, or an extra folder, or an installation program, or so . . So, the extra stuff gets placed in the right areas . .

Also, the core devs would have to find out, what would belong on that list, ie. often asked, or very use-ful add-ons, ie. things that deserve to have been made, by or, tested by the core devs or, contributors, and considered bug-free or, production - ready . .

I would really like that, as a new user, I think it's a nice way of adding this, so, it's a suggestion . . Thx . . . .

**Comment by jasperbrooks79** [comment]
Alternatively, I think you should call the AssetLib, CommunityTemplates, or something, since it's not clear most of them, aren't made by the core team, and might have bugs, other problems . . Perhaps, a shorter name . . . Thx <3

**Comment by RaTcHeT302** [comment]
yes pls

**Comment by jasperbrooks79** [comment]
Also, if you want to, you can make the add-ons like small .exe files, so you just download some .exe files, that are compiled . . Then, in Godot, when you press ' terrain editor ', it runs that .exe, and it somehow works . . Simple, clean file system, if possible . . .

**Comment by jasperbrooks79** [comment]
Another cool thing, maybe a particles extra, or so . . Where there are a bunch, of the coolest user-made particle systems, fire, smoke, other stuff, that they made MIT . . So, there's a growing particle system pack, or so, since learning visual shaders is really tough, atm . . ie. I can't do it, I get lost, can't code it, even visual shader . . :(( Thx . .

**Comment by jasperbrooks79** [comment]
But, also simple things, like fire, or so . .

![2020-07-28 1707](https://user-images.githubusercontent.com/61069740/88684230-e8874c00-d0f4-11ea-8787-0522eb714d8a.gif)

Again, an advanced one, there could be stylized, or more real ones . .

![2020-07-28 1708](https://user-images.githubusercontent.com/61069740/88684350-0bb1fb80-d0f5-11ea-9ab5-9293585166f2.gif)

I want to make a nice particle effect one day, also these pre-made ones, running in real time could, make engine more popular, and they could be modifiable, ie. one could change color, to like, have nice ones . . .

It's an example, of things that would be nice to say, I would like to download these things, with relevant files, or so, and know they had been tested, and also given clearance, by the dev team, and there was quality devs, or contributors making them, approving them . . Also, it would be such a nice demo, of what Godot can do, to click download 40, or 60, or 80, 100 particle effects, that really rock, ie. impress . . 

So, ' official ' terrain editor, ' official ' Particle System Starter Pack, or so . . Thx . . .

**Comment by jasperbrooks79** [comment]
I would make it my goal, to make one so good, one day, it'd be in the pack, after all the work making it myself, want to show it off and, share it, I suppose, would be, nice . . :O

**Comment by DrMoriarty** [comment]
Hi All! Recently I implemented my own plugin management system for my own modules. It mostly designed for process binary precompiled modules for third-party SDKs for iOS and Android. There are 37 production ready packages: analytics, ads, social network integration and so on.

The system has dependencies, autoloading gd wrappers, export hooks, uniform module settings for app keys and so on. It can be used as GUI addon and as CLI utility (for example when you want build your project with CI and don't want to store all binary frameworks in github repo. They can be automatically downloaded before your project was build.)

Full info and package list: https://drmoriarty.github.io/nativelib/
GUI Addon: https://godotengine.org/asset-library/asset/824
CLI utility: https://github.com/DrMoriarty/nativelib-cli

What do you think of it?

**Comment by Calinou** [comment]
Closing, as only official add-ons would be able to be promoted in this manner. So far, there are no such add-ons that would be useful to a *significant* portion of the userbase, [with the exception of C# once it's moved to an add-on](https://github.com/godotengine/godot-proposals/issues/2333). (In this case, the editor will most likely offer a built-in tool to download C# support.)
