### ISSUE TITLE
Allow pinning specific properties in the inspector on a per-node basis

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1276]
**Describe the problem or limitation you are having in your project:**
The inspector can get very, very long, especially with nodes such as particle2D. When navigating to your often updated (e.g. 'emit', 'one shot', 'colour', or modifying two or more properties to see different effects on the node) properties the process is slow and cumbersome.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In the inspector tab create a top level section 'favourites' (does not imply persistence) that will remain on the top even when the inspector is scrolled (but it can still be expanded/contracted as normal) and for any property you can copy it to this section (right-click, a new icon, etc) to the 'favourites'. As my example this means you can be anywhere in the inspector but still click emit/one-shot or tweak velocity/curve, etc. An alternative to this would be with the new docking system in 4.0 to allow individual section headings (e.g. 'Transform', 'visibility') to be undocked.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
1. frozen pane - here I've duplicated emit and amount to the locked section. This remains and the rest of inspector scrolls.
![image](https://user-images.githubusercontent.com/12863685/88787914-824e0800-d18c-11ea-94a5-c5acc2b75c60.png)

2. Alternate undocked section (not inheritance section) - here I've taken out the 'Time' section of particle2d and it's floating
![image](https://user-images.githubusercontent.com/12863685/88788217-f092ca80-d18c-11ea-9872-a044ef66f50f.png)

**Is there a reason why this should be core and not an add-on in the asset library?:**
Will make the IDE better

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4274, which is more detailed.
