### ISSUE TITLE
Select Frames Modal has no zoom functionality

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot-proposals#1278]
**Describe the project you are working on:**
2D Action Adventure with use of AnimatedSprites

**Describe the problem or limitation you are having in your project:**
In the frame selection screen of the AnimatedSprite the sprites are very small if they *are* small (like 16x16 tiled sprite sheet)
This is some times very hard to find and click the correct frames.

![EeKGVWVX0AAOEF8](https://user-images.githubusercontent.com/4989757/88899019-da007800-d24d-11ea-9a70-77e754244a0b.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Please implement a zoom functionality like in other windows like the tileset editor or the region rect window.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
That is really up to the guy who wants to implement this, but it should fit with the other zoom UI :)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it is possible to open the image in an external program and counting rows to find the frame I need.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Cause AnimatedSprite will be used by smaller sprites for pixle art games often, I guess.

It would be very nice if someone finds the time to implement this!

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by letsgamedev** [comment]
I updated my proposal description, sorry for being too messy before.

**Comment by akien-mga** [comment]
Fixed by godotengine/godot#41223.
