### ISSUE TITLE
Add an OS method to retrieve a screen's refresh rate

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#1284]
Related to https://github.com/godotengine/godot/issues/21486, #236 and #1283.

**Describe the project you are working on:**

The Godot editor :slightly_smiling_face: 

**Describe the problem or limitation you are having in your project:**

It is currently impossible to retrieve a screen's refresh rate.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

A method to get the monitor's refresh rate can be helpful in several ways:

- The returned value can be used to adjust the physics FPS to match the monitor's refresh rate. This can be used to provide smooth, reactive physics without incurring additional CPU costs and stuttering to those on lower refresh rate displays.
- The returned value can be used to lock the FPS to the monitor's refresh rate without relying on V-Sync. This can be important when power savings are desired, but the latency added by V-Sync is unacceptable.
  - We can add this to the Project Settings with an additional boolean setting, such as "Force Fps Match Monitor Hz". Alternatively, it can be done by the user in a script in `_ready()`. Care should be taken about setups that have monitors with different refresh rates.
  - We can use the fastest monitor's refresh rate to adjust the low-processor mode sleep duration in the Godot editor.

With high-refresh rate displays becoming more and more popular (including on mobile devices), providing the best possible experience on such displays is getting more important.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This feature has to be implemented in an OS-specific manner. It should preferably return a floating-point value in Hz, although returning an integer value in Hz is also acceptable. If the engine fails to retrieve the monitor refresh rate for any reason, it should return `60` as a fallback since this is the most common refresh rate.

I tried to implement this for X11 based on the SDL2 code, but it's easier said than done :slightly_smiling_face: 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It *might* be possible to do this on Linux by calling `xrandr`, but it's not particularly user-friendly. On other platforms (especially mobile platforms), this may not be possible at all.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This might be feasible using a GDNative-based add-on. However, since high refresh rate displays will probably be the norm in a few years' time, it's probably better to support this as a core feature.

**Comment by aaronfranke** [comment]
Related to https://github.com/GodotVR/godot_openvr_fps/issues/6

**Comment by name-here** [comment]
> - The returned value can be used to lock the FPS to the monitor's refresh rate without relying on V-Sync. This can be important when power savings are desired, but the latency added by V-Sync is unacceptable.
>   - We can add this to the Project Settings with an additional boolean setting, such as "Force Fps Match Monitor Hz". Alternatively, it can be done by the user in a script in `_ready()`. Care should be taken about setups that have monitors with different refresh rates.
>   - We can use the fastest monitor's refresh rate to adjust the low-processor mode sleep duration in the Godot editor.

Does Vulkan support this?  The comments in [this issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/370) seem to suggest it doesn't yet provide a way to sync up with the monitor without using V-Sync.  (I'm not familiar with the Vulkan API, though, so maybe I'm misinterpreting things?)

Also, we'll need to account for variable refresh rate monitors somehow.

**Comment by Calinou** [comment]
> Does Vulkan support this? The comments in this issue seem to suggest it doesn't yet provide a way to sync up with the monitor without using V-Sync. (I'm not familiar with the Vulkan API, though, so maybe I'm misinterpreting things?)

Limiting FPS to `$monitor_refresh_rate + 1` often works well enough if you don't mind having some tearing but find the V-Sync latency unacceptable.

**Comment by Calinou** [comment]
cc @jordigcs

I personally don't mind returning `-1.0` as a fallback value, as long as the documentation mentions how to handle this value (typically by treating it as if it was `60.0` in your code).

**Comment by jordigcs** [comment]
> cc @jordigcs
> 
> I personally don't mind returning `-1.0` as a fallback value, as long as the documentation mentions how to handle this value (typically by treating it as if it was `60.0` in your code).

I think this would be a better way to handle failure as well. I'll get started on that.

**Comment by jordigcs** [comment]
Opened at #57938

**Comment by Calinou** [comment]
This feature was also implemented in `3.x` thanks to https://github.com/godotengine/godot/pull/58812 (will be in 3.5beta2).
