### ISSUE TITLE
Add a `[hint=description]text[/hint]` BBCode tag to RichTextLabel to display tooltips on hover

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#1285]
**Describe the project you are working on:**

The Godot editor :slightly_smiling_face: 

**Describe the problem or limitation you are having in your project:**

In https://github.com/godotengine/godot/pull/40872, I added tooltips to `virtual`, `const` and `vararg` method qualifiers in the online class reference. I'd like to do the same in the editor documentation. However, there's no way to specify a tooltip for a *specific* part of the text in a RichTextLabel.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Adding tooltips on specific text makes it possible to specify additional information that would otherwise take too much space to display.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I propose adding the following BBCode tag: `[hint=description]text[/hint]`

This would be equivalent to `<abbr title="description">text</abbr>` in HTML.

When hovering `text`, `description` appears as a standard UI tooltip.

One open question is: should we add default styling for hinted text? People may want to use their own overrides for it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, as setting the `hint_tooltip` property affects the tooltip of the whole RichTextLabel. It will display when any part of it is hovered.

**Is there a reason why this should be core and not an add-on in the asset library?:**

I'm not sure if RichTextEffect allows doing this kind of stuff.

**Comment by jonbonazza** [comment]
If this is implemented, id like to see it support translations as well.

**Comment by Calinou** [comment]
@jonbonazza This can be done by passing `description` to the `tr()` function.
