### ISSUE TITLE
CSG Editor perfomance.

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot-proposals#1289]
**Describe the problem or limitation you are having in your project:**
Example if exist 500 CSG nodes and if i start move 100 CSG of this, then editor recalc every frame and this impact of perfomance,(Very impact), but if i unparent CSG nodes and move 100 CSG(not parented of CSG_Combiner) - not affected perfomance.
Can you change code - if transform(move,rotate, ...) - then not recalc, if only stop transform - recalc. ?
from https://github.com/godotengine/godot/issues/40934

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by SuperDIMMaX** [comment]
> In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done 
> 
> I think a good way to solve this would be to add an editor-only timer to recalculate CSG changes only after things have settled for a certain amount of time (say, 0.5 seconds). This is called _debouncing_.

 I think a good way to solve this would be to add an editor-only "button check" - update or not - as IK animation.?
