### ISSUE TITLE
Disable TreeItem tooltips

### ISSUE THREAD

**Issue by Reno57** [godotengine/godot-proposals#1295]
**Describe the project you are working on:**

Making a Quest Journal user interface for a RPG game project

**Describe the problem or limitation you are having in your project:**

I use TreeItem control node to achieve this function, the display of the three Item is not satisfactory because tooltips always appear above the TreeItem.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

There is no possibility to disable tooltips in TreeItem. I asked the community, I was advised to turn on github. Please add the ability for the TreeItem to disable tooltips.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

the result is quite obvious, i think.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

no, as far as i know.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Relative to TreeItem Object.

**Comment by tom-jk** [comment]
Does `item.set_tooltip(0, " ")` work?

**Comment by Reno57** [comment]
not very clean, but yes it works, thanks you 🙂 !
Does i have to do something with the thread ?

________________________________
De : tom-jk <notifications@github.com>
Envoyé : mardi 4 août 2020 00:40
À : godotengine/godot-proposals <godot-proposals@noreply.github.com>
Cc : Reno57 <leinuo@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [godotengine/godot-proposals] Disable TreeItem tooltips (#1295)


Does item.set_tooltip(0, " ") work?

**Comment by tom-jk** [comment]
Well you could close it but, like you say, this isn't very clean. This way of disabling tooltips is very obscure and not documented. So perhaps this proposal should now be about having a more sensible, more discoverable way of disabling tooltips, or about improving the documentation? (I don't know if it's preferred to open a new issue.)

**Comment by Reno57** [comment]
Well, i will close this issue and open a new one that is more precise.

**Comment by Calinou** [comment]
Superseded by #1315.
