### ISSUE TITLE
Reopen Scene Button (in editor [for tool scripts]) 

### ISSUE THREAD

**Issue by LotsaBugs** [godotengine/godot-proposals#130]
**(EDIT)**
(**_Scene -> Revert Scene_** currently does **_almost_** exactly this, but there is no shortcut for it, and it's not listed in the shortcut menu. Also, you need to save the scene (**_Ctrl+S_**) before hitting **_Revert Scene_**)

_**Describe the project you are working on:**_
A tool script for dynamically creating cards for a card game.

_**Describe the problem or limitation you are having in your project:**_
When working with a tool script, changes made in the scene (such as swapping an image) aren't visible until you close and re-open the scene.

**_Describe how this feature / enhancement will help you overcome this problem or limitation:_**
Having a button to automatically save, close, and reopen the current scene in the editor would speed up development time for tool scripts, add-ons, etc.

**_Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:_**
![Close-Reopen Scene Icon](https://user-images.githubusercontent.com/52873190/66271019-5592d200-e894-11e9-8d6c-6475ab5a1833.png)

**_Describe implementation detail for your proposal (in code), if possible:_**
(Pseudo-code):

_on_reopen_scene_pressed():
*	save_scene()
*	close_editor_scene()
*	open_last_closed_editor_scene()

Shortcut to reload the editor scene could be : _Control+Shift+Alt+R_

There should also be a GDScript function for this so that it can be called whenever a change requiring a refresh is made.  [ _reload_editor_scene()_ ]

**_If this enhancement will not be used often, can it be worked around with a few lines of script?:_**
It would be used often by anyone working with tool scripts. 
Currently, there is no code workaround.

**_Is there a reason why this should be core and not an add-on in the asset library?:_**
This should be a built-in feature.

**Comment by Calinou** [comment]
Isn't this done by the existing **Scene > Revert Scene** menu option?

**Comment by LotsaBugs** [comment]
Hi, Calinou, 
I didn't even know that that button was there.
I just tried it, and it works perfectly!
However, I don't see a "Revert Scene" option in the shortcut menu anywhere.
I searched for it by name also looked at all the shortcuts under Editor and SceneTree and didn't see it.
I think it needs to be added.

Thank you!

**Comment by Calinou** [comment]
@LotsaBugs [It seems to have been merged after Godot 3.1's release](https://github.com/godotengine/godot/pull/26551), which means it will only be available in 3.2 onwards.

**Comment by LotsaBugs** [comment]
Great to hear that it'll be in 3.2.
Feel free to mark this as closed, unless it should be left open.
Thanks!

**Comment by Calinou** [comment]
I'll close this proposal as it has now been implemented in 3.2 betas (see my comment above).
