### ISSUE TITLE
Make lights set to 'Bake Mode All' stop lighting baked objects

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot-proposals#1306]
**Describe the project you are working on:**
Mobile game

**Describe the problem or limitation you are having in your project:**
With the current implementation if a light is set to Bake Mode ALL it lights two times baked objects (once the baked lightmap and once the light itself) which makes them too bright compared to dynamic objects who only get light once making it a pain and confusing to make it look consistent.

Also what's the point of baking a light on 'Bake Mode All' if is still going to dynamically illuminate (wasting resources) baked objects?

Note: Dynamic objects still need to be able to cast shadows on baked objects.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If lights set to 'Bake Mode All 'stop lighting baked objects, dynamic and baked objects will get the correct amount of light. Making the lightmap process much more consistent and easy to use.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
- A light gets set to 'Bake Mode All'
- All baked objects stop receiving dynamic light from that light and computing shadows from baked objects.
- Dynamic objects can cast shadows on to baked objects (doesn't matter if shadows get added and look a little more dark, thats preferable to the current behaviour).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Don't think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Its much more intuitive that wen you set a light to 'Bake Mode All' all is going to be baked and it will stop receiving dynamic lighting from that light. It will also make the lighting process much more simple for users and it will give consistent results and better performance.

**Comment by Calinou** [comment]
> Also what's the point of baking a light on 'Bake Mode All' if is still going to dynamically illuminate (wasting resources) baked objects?

You should disable the light after baking using the "All" bake mode. However, the light baker should still take it into account, so you should enable it again before re-baking the light.

**Comment by Janders1800** [comment]
Then dynamic objects don't get any light.

**Comment by Zireael07** [comment]
@Janders1800: For dynamic lighting, use a second light node?

**Comment by Janders1800** [comment]
Well, I think that actually makes it worse;
- Now you have more nodes to keep track of and a more complicated setup.
- Since there are more lights, worse performance.
- Baked objects also get that light so that makes three lights vs dynamic two, so still no consistency.

This is a "workaround solution" y put together to make a setup that "works nice" with dynamic objects.
The Gold rule here is:
-If the light is going to touch a dynamic object then set the amount of light at normal and the baked objects materials at half brightness.
- If the light is not going to touch a dynamic object but it is in a material that shares lights that they do (the material is at half brightness), then set the light at double brightness and hide light.
-If neither the light and other objects lights are going to touch a dynamic object lights and materials normal and hide lights.
Here a example: 
[LightMaps.zip](https://github.com/godotengine/godot-proposals/files/5023272/LightMaps.zip)

**Comment by TheDuriel** [comment]
```
extends <Type>Light
class_name Baked<Type>Light

func _init() -> void:
visible = false
```

or

```
extends <Type>Light
class_name Smart<Type>Light

func _init() -> void:
visible = light_bake_mode > 0```

Same amount of light nodes. No keeping track of anything.

**Comment by Janders1800** [comment]
The set up of the lights is not that simple, you have to take into account if they are going to light dynamic objects, or if they are going to light materials who are going to be light for lights who are going to light dynamic objects.

Also, light layers do not work on stable.

**Comment by lawnjelly** [comment]
Agreed, current behaviour was very hard to control last time I looked at it. Something for @JFonS to have a look at? There may have already been adjustments to this. His version will be replacing the old as soon as merged:

https://github.com/godotengine/godot/pull/40035

**Comment by JFonS** [comment]
I opened https://github.com/godotengine/godot/pull/41629 which should address the issue at hand. Feel free to test/review :)

**Comment by Janders1800** [comment]
Nice! Do you know if it will make it to 3.2.3?

**Comment by Calinou** [comment]
@Janders1800 The 3.2.3 release is imminent, so I think this is more likely to land in 3.2.4.

**Comment by JFonS** [comment]
https://github.com/godotengine/godot/pull/41629 was merged, so I'm closing the issue :)
