### ISSUE TITLE
Add documentation on how to export to consoles.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#131]
**Describe the project you are working on:**
Smaller projects for fun.

**Describe the problem or limitation you are having in your project:**
Would love to learn to do homebrew with consoles using godot.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Some persons want to easily export to consoles.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Add third party solutions, or at least documentation on how to export to diferent retro consoles like Wii or the Vita or 3DS.

**Describe implementation detail for your proposal (in code), if possible:**
I think a third party repository would be enough or just add some documentation on how to one person can easily compile console exports to his project.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Most of what I request is better documentation, maybe a third party repository with third party code to export to consoles.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not really in core, is more about improving the documentation.

**Comment by Calinou** [comment]
The issue is that nobody is legally allowed to provide public documentation or export templates. The [Console support in Godot](https://docs.godotengine.org/en/latest/tutorials/platform/consoles.html) documentation page already explains why.

**Comment by golddotasksquestions** [comment]
See here:
https://godotengine.org/qa/4018/does-godot-have-plans-support-exporting-consoles-ps4-xbox-etc
and here:
https://github.com/godotengine/godot-website/issues/57

**Comment by DriNeo** [comment]
Why not a documentation for programmers about platform addition ?

**Comment by EIREXE** [comment]
> The issue is that nobody is legally allowed to provide public documentation or export templates. The [Console support in Godot](https://docs.godotengine.org/en/latest/tutorials/platform/consoles.html) documentation page already explains why.

He said homebrew, we are legally allowed to provide documentation and even code, if we use a fully legal toolchain.

**Comment by basdp** [comment]
Just some words describing a generic approach to adding a new platform might be useful. Just the glue between the OpenGL (or in the future Vulkan) examples from the proprietary SDK's and Godot. At the very least a list of what parts of the engine is platform dependent (require porting), and which parts are cross-platform.

**Comment by Calinou** [comment]
Closng, as this repository is dedicated to engine feature proposals, not documentation requests. Moreover, this was already requested in https://github.com/godotengine/godot-docs/issues/2330.
