### ISSUE TITLE
Can we get a AppImage download for 3.2.2 and following releases?

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1310]
Sorry about not following the template most of it was unnessary anyways..
Can we get a AppImage download for 3.2.2 and following releases?
I recently switched to ubuntu and there doesn't seem to be a way to install godot in the application menu with a icon.

**Comment by Janders1800** [comment]
You mean a deb package?

**Comment by aaronfranke** [comment]
@Shadowblitz16 AppImage will not help you get Godot in the menu with an icon. For that, you need a `.desktop` file in `~/.local/share/applications`. You can just make one yourself if you want. If you want an easier option, you can just install Godot via Steam, and then tell Steam to make a menu shortcut for it.

@Janders1800 No, Godot is not currently an [AppImage](https://appimage.org/), it is just an executable.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by Shadowblitz16** [comment]
@Calinou you sound like a robot
> In the interest of making high-quality proposals, please read the rules and fill in the issue template. This proposal will be reopened once this is done slightly_smiling_face

the issue if perfectly fine please reopen it. 
if you have a problem with it then reorganize the issue template to not be based around games
 
Anyways Godot should at least provide a installer so that we can install it into the menu

**Comment by aaronfranke** [comment]
> if you have a problem with it then reorganize the issue template to not be based around games

No.

> Anyways Godot should at least provide a installer so that we can install it into the menu

There is little benefit for Godot to do this, and there are many other issues that are a higher priority than this one. You can install Godot through Steam if you want, or make your own `.desktop` file.

**Comment by Zireael07** [comment]
> if you have a problem with it then reorganize the issue template to not be based around games

Issue template is not based around games, and if you look around, there are quite some generic proposals filled out.
