### ISSUE TITLE
get_open_scenes() should return an Array of Nodes(Scenes) instead of an Array of Nodes.filename(Scenes.filename)

### ISSUE THREAD

**Issue by gianlluca** [godotengine/godot-proposals#1314]
**Describe the project you are working on:**
Plugin that makes changes in scenes components importing a custom file.

**Describe the problem or limitation you are having in your project:**
I can only get the path of the open scenes I cannot get the scenes itself. This makes very difficulty avoid inconsistencies because if I only edit scenes with the plugin getting by path and press "play project" the editor will "accidentaly" save open scenes and overwrite all changes that plugin did. Close all scenes every time before import is impracticable.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Change EditorInterface.get_open_scenes() to return scenes instead of scenes.filename will help plugins decide to make changes in scenes getting by editor if they are open. Doing this will avoid inconsistencies between scenes open and their files.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
My proposal is remove "->get_filename()" from this line:

https://github.com/godotengine/godot/blob/f8c066e97eec9c936d5e809328144d7af21acd0d/editor/editor_plugin.cpp#L216

BTW filename will easily geted by something like that:

Assuming EI is EditorInterface geted.

```
for f in EI.get_open_scenes():
    print(f.filename)
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I can't find a way to get scenes outside the core.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/10895, which is more detailed.
