### ISSUE TITLE
Make the window when running centered on the screen

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1317]
**Describe the project you are working on:**
A Tomb Raider game, atm . .

**Describe the problem or limitation you are having in your project:**
When I ' run ' the game, the window is always sitting in the bottom corner, and I have to move it, constantly . . It's sort of annoying, and feels like a bug, almost . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make it so, when running the game, regardless the resolution, it always run in the middle of screen, or is centered, instead of always in a corner . . It also makes more sense, one wants to see ones game, in the middle of the screen . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![2020-08-06 0401](https://user-images.githubusercontent.com/61069740/89482191-9780f300-d799-11ea-802e-0de79ba5b811.jpg)

It's just annoying constantly having to manually move the ' run ' window, to the middle of the screen, I can't find where to move it, would be nice if default it, was just centered, like splash screen <3

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I have no idea where to do this, have checked Project settings - Visuals, there are some settings, but not one for ' Run Window is Centered ' . . :(( . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
I'm not sure how to answer this, maybe . . But, I really would like this, it'd be nice, thanks . .

**Comment by werdnahull** [comment]
This is already available by going to the **Editor** menu, **Editor Settings**, **Run>Window Placement**

![image](https://user-images.githubusercontent.com/10228963/89496802-e6b22e00-d76f-11ea-835e-1277558e5f20.png)

**Comment by jasperbrooks79** [comment]
Whoops . . When I have it in centered, it's sort of in the lower corner . . . :(( . . .

**Comment by Calinou** [comment]
This is actually a bug: https://github.com/godotengine/godot/issues/13017

Try enabling **Display > Window > Allow Hidpi** in the Project Settings.
