### ISSUE TITLE
Add `hint_transparent` for uniforms

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot-proposals#1325]
**Describe the project you are working on:**
2D painting game.

**Describe the problem or limitation you are having in your project:**
I use a complex shader in order to make some painting effects. It uses several sampler uniform to blend the color. 
If some of uniforms don't used I should to set to it special transparent texture 1x1 in order to skip some type of processing. It's just because we don't have `hint_transparent` in shader language. If I use `hint_black` of `hint_white` it only changes RGB channels and Alpha is always 1.0.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If we would have `hint_transparent` in shader languages then unused uniforms will have Alpha = 0.0 and it will not affect on result color.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
uniform sampler2D add_tex : hint_black;
uniform sampler2D sub_tex : hint_black;
uniform sampler2D mul_tex : hint_white;
uniform sampler2D blend_tex : hint_transparent;

void fragment() {
    vec4 col = texture(TEXTURE, UV);
    vec4 add_col = texture(add_tex, UV);
    vec4 sub_col = texture(sub_tex, UV);
    vec4 mul_col = texture(mul_tex, UV);
    
    col = (col * mul_col) - sub_col + add_col;
    vec4 col2 = texture(blend_tex, UV);
    COLOR = mix(col, col2, col2.a);
}
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes, it requires in every place where the uniform does't used use instead of it special placeholder 1x1 texture.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's just a several lines of code! I saw how implemented `hint_black`:
```
                glGenTextures(1, &resources.black_tex);
                unsigned char blacktexdata[8 * 8 * 3];
                for (int i = 0; i < 8 * 8 * 3; i++) {
                        blacktexdata[i] = 0;
                }

                glActiveTexture(GL_TEXTURE0);
                glBindTexture(GL_TEXTURE_2D, resources.black_tex);
                glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, 8, 8, 0, GL_RGB, GL_UNSIGNED_BYTE, blacktexdata);
                glGenerateMipmap(GL_TEXTURE_2D);
                glBindTexture(GL_TEXTURE_2D, 0);
```

We already have 4 types of default textures. Let's add the last one and we will have the full range of options.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
I am having a similar issue in my code. mix returns white because the sampler2D is defaulted to a 1x1 white texture. There is no easy way to default a lot of textures and materials to a 1x1 transparent texture. 

I would also like to suggest the name `hint_transparent_albedo`  since we already have `hint_black_abledo` though I would prefer `hint_transparent` if this is to be implemented.
