### ISSUE TITLE
Particle2D should not reset itself when you change amount

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1327]
**Describe the project you are working on:**
2D platform

**Describe the problem or limitation you are having in your project:**
When you change the 'amount' value of particle2D it resets the particles, i.e. immediately stops them all then starts again. This means if you want to increase particles over time, such as in an animation player, e.g. number of flames particles increase, you cannot.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Allow or change particle system so that increasing amount will simply continue adding more particles as required instead of stopping the particle system and restarting. I guess the same can apply to reducing...

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I would presume anyone wanting to change amount will expect the particle system to not reset as it looks awful.

**Is there a reason why this should be core and not an add-on in the asset library?:**
it is probably as users expect.

**Comment by Calinou** [comment]
See also #815.

**Comment by chucklepie** [comment]
thanks, sorry, I did search first. Sometimes the words do not find things :)

Is there any chance this might appear in a pre 4.0 update?

**Comment by Calinou** [comment]
> Is there any chance this might appear in a pre 4.0 update?

This likely requires rewriting the particle system to be changed, so I doubt it.

**Comment by KoBeWi** [comment]
> Fixing this likely requires rewriting the particle system, so I doubt it.

https://github.com/godotengine/godot/issues/16352#issuecomment-363179758 suggests a solution that should probably be easy to do with the current system.

Further down in that issue there's a linked shader that implements this: https://github.com/godotengine/godot/issues/16352#issuecomment-452987479
It's most likely very outdated at this point, but some custom shader is a viable workaround for now.

**Comment by chucklepie** [comment]
Thanks, you can close this issue.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/16352, as this is actually a bug.
