### ISSUE TITLE
Implement some API for rollback netcode

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#1328]
**Describe the project you are working on:**
Plan on making some online 2D fighters.

**Describe the problem or limitation you are having in your project:**
Need a form of rollback netcode in my game.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Could be a default integration with the ggpo code.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
There's already a ggpo module, but It lacks documentation and seems not polished enough.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, this requires integration with the godot engine at some level, specifically the ggpo step of resimulation the engine in a single frame, is not a trivial problem for average users.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Rollback netcode has been described as free lag experience for online games.
As such It's very beneficial not just for 2D fighters but for more genres that requires netcode, because it gives a free lag experience compared to normal online methods.
It should be a core network issue, or at least godot developers should have some discussion to see if they can use some of the ideas of ggpo specifically to improve the godot networking to a level where is a lag free experience to the users.

**Comment by Calinou** [comment]
> There's already a ggpo module, but It lacks documentation and seems not polished enough.

Can you link to it? Maybe it can be improved.

**Comment by ca3games** [comment]
@Calinou  https://github.com/FlutterTal/godot_ggpo

The issue is the lack of proper documentation on it.

**Comment by Calinou** [comment]
> The issue is the lack of proper documentation on it.

This is not an issue on our end. It's up to module maintainers to document their work if they want other people to use it :slightly_smiling_face:

**Comment by jonbonazza** [comment]
This is best implemented as an addon as was suggested. The referenced addon looks like a good start. :) Btw, rollback netcode is geberally fairly game specific, so creating a truly generic implementation is extremely difficult if not impossible. You can get an implementation that will get you mostly the way there with a lot of tuning though. Just something to be aware of.

**Comment by FlutterTal** [comment]
Yay, someone is talking about my work in the godot repo! ^^
But seriously, I'm of course still maintaining the module, but I realized I can't really do that all alone. So I was thinking that anyone who wants to help me with that can dowload the module and test it on their side so they can tell me the issues. As for the documentation, I'm also working on it, but the thing is the original library used for this module isn't really well documented as well. So I'll just do my best with that. ^^

**Comment by SirPigeonz** [comment]
> As far as I know, rollback netcode is typically only relevant for fighting games. It's unlikely to be relevant in other game genres such as turn-based games, shooters or racing games.

Not really, it is useful for any fast-paced versus game that uses p2p.

**Comment by Faless** [comment]
Netcode rollback implementation is very game dependent, and we feel this is best left as an addon. If there is anything that can be exposed from the Godot core that would make such an addon better integrate with the engine we would be happy to discuss it.
Closing for now as there seem to be a GGPO plugin.

**Comment by dsnopek** [comment]
FYI, I'm working on a rollback & prediction addon, which will probably appear in the asset library in a month or two. I'll try to remember to come back here and post the link :-)
