### ISSUE TITLE
Make the editor change debug remote port automatically if unavailable

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot-proposals#1335]
**Describe the project you are working on:**
A multiplayer game

**Describe the problem or limitation you are having in your project:**
I need to launch 2 instances of the Godot editor, one for the server and one for the client, in order to work on the game. When I launch the game on both editor instances, the second instance can't use the debug remote port set in editor settings, since it's being used by the first instance. It says ` Error listening on port <remote debug port>`.
Each time I want to work on the game, I have to manually change the debug remote port in one of the editor instances so they don't interfere with each other.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make the editor automatically change the port if it finds the default unavailable.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Perhaps a fallback port that would also be set in editor settings, then after it throws `Error listening on port <remote debug port>`, it automatically changes to that port and attempts to connect.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a general enhancement to the editor that would better be done in core.

**Comment by Calinou** [comment]
> I need to launch 2 instances of the Godot editor, one for the server and one for the client, in order to work on the game.

This is now supported by the editor out of the box :slightly_smiling_face:  https://github.com/godotengine/godot/pull/36920

**Comment by Tooniis** [comment]
> This is now supported by the editor in `master` out of the box slightly_smiling_face [godotengine/godot#36920](https://github.com/godotengine/godot/pull/36920)

Actually my server and client are different, so this won't help me. Still a good addition nonetheless

**Comment by Faless** [comment]
For reference, there is a PR implementing this: godotengine/godot#37067

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/53241 (`master`) and https://github.com/godotengine/godot/pull/37067 (`3.x`), closing.

**Comment by Chinwe-D** [comment]
I am a beginner in godot and I encounter this error, please can someone assist?

"Invalid set index 'playing' (on base: 'null instance') with value of type 'bool'"

**Comment by Calinou** [comment]
@Chinwe-D Please don't ask support questions here, as this issue tracker is meant to be used for feature proposals only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by Chinwe-D** [comment]
Noted with thanks. I'm sorry about that
