### ISSUE TITLE
Make TileMap snap settings available before defining a tile

### ISSUE THREAD

**Issue by mount2010** [godotengine/godot-proposals#1337]
**Describe the project you are working on:**
I am working on a project using TileMaps.

**Describe the problem or limitation you are having in your project:**
Currently, to change the snap settings of a TileSet in the TilesetEditor, you must first define a tile (of the wrong size), in order to access the TilesetEditorContext inspector properties which contains the snap settings. This is counterinitutive, as you will be looking for the settings for changing the snap settings before you define a tile.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a "Snap Settings" button next to the Snap button in the Tileset Editor (similar to the Snap button in the Viewport) to access TilesetEditorContext properties, either in a popup menu, or in the Inspector. This will allow the user to change the snap settings at any time.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Similar to the Snap Settings button in the Viewport:

![image](https://user-images.githubusercontent.com/13136505/89711572-9f20e180-d9bd-11ea-862c-ca1af2a07f56.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
N/A

**Comment by BlueSky-fur** [comment]
is this still a thing to come? kinda aged a bit.

**Comment by Calinou** [comment]
> is this still a thing to come? kinda aged a bit.

The TileMap editor was rewritten from scratch since this proposal was opened. Please check in [4.0.beta1](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1) if the original problem is still present.

**Comment by BlueSky-fur** [comment]
> > is this still a thing to come? kinda aged a bit.
> 
> The TileMap editor was rewritten from scratch since this proposal was opened. Please check in [4.0.beta1](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1) if the original problem is still present.

Thank you for the hint!

**Comment by mount2010** [comment]
To be honest, I kind of wrote this issue on impulse after discussions in the Godot Discord.
However, 4.0 definitely has way better UX in Tilemaps than 3.0. I'm impressed at the work you guys did. 
I'll be closing this issue.
