### ISSUE TITLE
Port visual shader graph icons from Godot 2.1 to 3.x

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot-proposals#134]
**Describe the project you are working on:**
Various 2d and 3d projects

**Describe the problem or limitation you are having in your project:**
Not really a problem or limitaiton.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
This will be very nice to look at and make it look more professional.
Easier to connect one to another if there are something other that text and color.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![55761449-8e75f980-5a5f-11e9-8f3f-d14836e80fbf](https://user-images.githubusercontent.com/13393087/66440819-9f1a2300-ea34-11e9-8dfa-f5d64225e2b5.png)

**Describe implementation detail for your proposal (in code), if possible:**
Somehow transfer them from 2.1 to 3.** ?

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It will be used by everyone that's using visual shaders

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yeah, this should just be in the core, this should be the first thing a new user sees when they open visual shader, first impressions last the longest.

**Comment by clayjohn** [comment]
Please follow the template provided or else this proposal will be closed.

**Comment by clayjohn** [comment]
Closing now. If you update to follow the provided template, I will reopen. 

For reference, here are the rules for submitting proposals. https://github.com/godotengine/godot-proposals

**Comment by Norrox** [comment]
update!

**Comment by clayjohn** [comment]
Try out the changes to VisualShaders in 3.2 Alpha. With the new system I'm not sure your proposal even makes sense https://downloads.tuxfamily.org/godotengine/3.2/alpha2/

**Comment by Norrox** [comment]
Yes ofc it is, just because the new windows are more foldable does not mean that i ( we ) want less graphical representation of what kind of input / output / value it is.
Please open this so people has a chance to voice their opinions, thanks
