### ISSUE TITLE
Editor hint when zoom level is maxed out, and focus indicator on the object rotating gizmo

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot-proposals#1340]
**Describe the project you are working on:**
3D VR game

**Describe the problem or limitation you are having in your project:**
My editor got stuck in a mode where I could not zoom in enough to edit my CSG object.  This was pretty frustrating and I could not fix it even by duplicating the scene and trying to edit it again.  

I only found out how to fix it by searching through the old bugs and getting a clue that there was a Focus mode in the editor that I did not know about -- even after using Godot for 2 months.  

I had zoomed out and looked away from the object and accidentally pressed the 'F' key, so the editor was stuck focused on the Grid plane (which does not exist in the node tree).

The real GUI problem is that the object of the "spatial_editor/focus_selection" is an entirely invisible factor to the user.  They just have to remember what they selected last, which could be hours ago and accidental.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Detect when a novice user is repeatedly trying to zoom further in and has hit the end-stop, and provide them with a hint that they should set the focus to an object that they want to get close to.  
https://docs.godotengine.org/en/stable/getting_started/editor/default_key_mapping.html

It is reasonable to guess that when a user is trying to go beyond this limit it is because they don't know how to get what they want.

There is a zooming gizmo on the left of the editor that maxes out (on the lower level) at 0.0.  Unlike the axis gizmo it is non-interactive.

It would be useful if the Inspector or the selected object gizmo gave some indication that the object was in or out of focus wrt to zooming.

Also, the Freelook mode could be made more discoverable in the following way:
Editor->Editor Settings->Editors->3d  "Freelook" section could have a tool-tip highlight that tells the user how to enter and exit that mode.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

* When zooming hard against the 0 level, the zoom gizmo blinks red and you get a tool tip that says: "Limit reached for this focused object"

* There is a section in the Inspector pane that either says: "This object has 3D focus" or there is button that says "Make this object have 3D focus".  Its tooltip would tell you the keyboard shortcut.

* Put an asterisk somewhere on the object gizmo that is white if object has focus, or grey if it does not have focus (but you can click it to make it have focus)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's an editor UI issue

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's an editor issue for noobs.

**Comment by Calinou** [comment]
The center of the 3D view is technically not bound to any object, but to a position. Personally, I'd make it so the center is represented by some kind of cursor like in Blender.

**Comment by Calinou** [comment]
This is now implemented:

https://user-images.githubusercontent.com/180032/175795365-51f4dd8d-7266-48f5-a39f-7cbfc22381c7.mp4

As for the zoom origin, I believe this would be better tackled by https://github.com/godotengine/godot-proposals/issues/910.
