### ISSUE TITLE
Add a ' set ' and ' get ' autoload singleton variable box to visual script . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1347]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
I've been trying to find out, how to access a singleton in visual script, and I accidentally found the answer, online . . It's quite complicated, as can be seen here . .

![2020-08-11 0259](https://user-images.githubusercontent.com/61069740/89845433-bf4bce80-db7e-11ea-8fca-b3e72aaed6aa.png)

![2020-08-11 0300](https://user-images.githubusercontent.com/61069740/89845437-c2df5580-db7e-11ea-9b77-c806eb45ec9b.png)

Singletons are really nice, like global variables, that are stored between scenes, and they seem to be very important for the engine . . I would like to ask for a SIMPLER way to do this, than the above, as there's almost no chance of a beginner actually figuring this out, and it seems to be expected that one uses them, ie. they're presented as important features, for making game in the docs, right now . . I'd like to have a ' get ' and ' set ' autoload singleton box in Godot, atm I don't think it's possible, it doesn't make sense there's no way I'd have found the answer above, on my own, as a non-coder ( learning it, though <3

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make a ' set ' and ' get ' button, for accessing singletons, in the list of nodes, if that's not a good idea, make some sort of box, or way for it to be easier, and more logical . . right now, it's tough . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Since autoloads are considered a core feature, maybe make a ' get autoload ', or ' set autoload ', right now accessing a singleton is very difficult, for people learning visual script, for no reason, imo, sry . . . :((

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I can't change visual script, like that, as a beginner . . :((

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because, singletons are very powerful, and useful parts, of the engine, and the official docs mention them, in the cool features, of the engine . . . :)) <3

**Comment by TheDuriel** [comment]
![image](https://user-images.githubusercontent.com/44248915/89900797-7c244680-dbe4-11ea-8ea1-1fb58cf0f1cb.png)
This is the proper way for getting an Autoloads property at this current point in time. And ofc you never need to repeat those first two nodes.

**Comment by jasperbrooks79** [comment]
dear duriel, how did you get the amazing looking visual script <3 it's SO cool, WOOWOWOWOW <3 ! ! . . is it a theme <3 must have . . Thank you . .

**Comment by jasperbrooks79** [comment]
my wish is only, that top bar was bit rounded, like this, then visual script Godot look PERFECT . . .

![2020-07-06 0242](https://user-images.githubusercontent.com/61069740/89975800-fd242200-dc66-11ea-9f1c-4e4a436f2696.jpg)

if visual script got that look, from your image, in Godot 4.0, so good . . :DROOL <3 Thanks . .

**Comment by jasperbrooks79** [comment]
I sort of noobed it, I found a way to do it, that also works . .

Make a .vs code document, add some variables to it . .

Then, move the ' Preload ' of it into a visual script area . .

![2020-08-11 0545](https://user-images.githubusercontent.com/61069740/89976727-80df0e00-dc69-11ea-9a91-4044e342ac0c.gif)

Move the ' obj ' output out, and under remove(), there's a ' Get Default Variable Value ', or so . . Type in name, of singleton, and it works, also . .

**Comment by jasperbrooks79** [comment]
I made a suggestion, some time ago, that each box also had like, an expandable lower panel, with common settings, or stuff, like PRINT . .

![2020-08-12 0709](https://user-images.githubusercontent.com/61069740/89977235-eda6d800-dc6a-11ea-8bb9-5a44f3f8d49f.jpg)

I added a little ' wink ', or edge in the corner, idea for visual script is, click that, you get some common things, one often needs, for each box . .

![2020-07-06 0308](https://user-images.githubusercontent.com/61069740/89977283-0ca56a00-dc6b-11ea-8780-69d1a85a9a7e.jpg)

Your visual script looks SOO cool, is there a way to download it, so nice . . . <3 . .

**Comment by jasperbrooks79** [comment]
My biggest wish for Godot 4.0, or just 3.2 was there was some themes, so one could make visual script look like yours, by clicking a button <3 WOOWOWOWOW ! ! <3
