### ISSUE TITLE
Add Default Settings for 2D Snap Step

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot-proposals#1348]
**Describe the project you are working on:** a 2D Top Down Shooter

**Describe the problem or limitation you are having in your project:** 
I want to snap to 5 or 10 px Grid Step instead of 8 px but couldn't find the default settings for them so I have to change them every scene.

![image](https://user-images.githubusercontent.com/12462089/89849867-a578ae80-dbb3-11ea-913b-391df22f548a.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add default settings for the configurations in the picture above (especially Grid Step which is what I need)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Add them to `Editor Settings: Editors > 2d` along with the color settings.

![image](https://user-images.githubusercontent.com/12462089/89850052-16b86180-dbb4-11ea-9d1d-31d8342ad382.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** No.

**Is there a reason why this should be core and not an add-on in the asset library?:** This is an editor patch.

**Comment by KoBeWi** [comment]
What version are you using? In 3.2 when you create a new scene, it automatically keeps the snap settings from the last scene that was opened.

**Comment by DleanJeans** [comment]
For some reason, I remember having to change it half a dozen times. I'll keep it closed until it happens again.

**Comment by nihiluis** [comment]
this always gets reset. I have to do it again and again. can someone reopen. @KoBeWi approach doesn't work. snap mode also gets reset. I'm on v3.4.2.

**Comment by KoBeWi** [comment]
> this always gets reset. I have to do it again and again.

Yeah I had this problem in a new project. Basically if you already opened some scenes, they will have the old settings stored. So whatever settings will a new scene have depends on what scene you have opened when creating a new one. So this solution isn't very reliable unfortuantely.

**Comment by PrinceMerluza** [comment]
> There's probably a case for making this setting per-project instead of per-scene,

Yes, at least one. An entire genre called 2d top-down rpg. 

Or at least it should be possible to set a default for new scenes and can override it for specific scenes.

**Comment by kregi123** [comment]
> 2D editor snap settings are set on a per-scene basis, not a per-project or editor-wide basis

This is not about making it per-project setting but adding possibility to change the default value which is currently 8xp.

It's annoying that it needs to be changed in every scene. The feature that keeps the snap settings from the last opened scene works only on new scenes if I open already existing scene, in which I never used grid before, it defaults to 8px.

There is already editor-wide default setting 8px why not allow to change it?
