### ISSUE TITLE
Addition of a project path declaration to Godot's exported executable

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [godotengine/godot-proposals#135]
**Describe the project you are working on:**
I am currently working on a Steam like distribution platform, that is centered around plug'n'play idea of having engine, game, and mods to be three separate entities that organically gets build by the platform into a final resulting game.

**Describe the problem or limitation you are having in your project:**
There is currently a problem, that prevents me from adding Godot into a pool of available engines. It is due to a fact, that there is no way to launch exported Godot executable with an argument to a real project path like in the editor.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Inclusion of an argument that would allow specifying folder path with game data (.pck file/ mono installation) will help me to launch desired game with a simple system call.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Godot.exe -project/-launch %SomeFormOfAPath%/GameName

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This needs to be done externally, so developers on their end won't have to write initialization code to hook up their own asset library.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because Godot's nature is already based on plug'n'play principles that I am striving towards. Plus, I don't want developers to handicap themselves by using our API just to load their assets. I already implemented this in Unity and I already implemented this in UE4, and It works as expected.

**Comment by bruvzg** [comment]
> Inclusion of an argument that would allow specifying folder path with game data (.pck file/ mono installation)

There already are `--main-pack` argument to specify PCK and `--path` to specify folder path available in both editor and exported executables.

**Comment by IlyaStuurFedorov** [comment]
Yeah, that works, but I could not find that `--main-pack` argument [in here anywhere](https://docs.godotengine.org/en/3.1/getting_started/editor/command_line_tutorial.html)

**Comment by bruvzg** [comment]
You can get full list of supported command line arguments by using `--help` argument.
