### ISSUE TITLE
3D Transform to be constructed from its string representation 

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot-proposals#1351]
**Describe the project you are working on:**
VR cave mapping game

**Describe the problem or limitation you are having in your project:**
The recommended way to save games is to use the JSON format to write a file on disk 
 https://docs.godotengine.org/en/stable/tutorials/io/saving_games.html

I wanted to save the orientation and position of some of my elements, but there is no good way to do this without writing a stack of code to flatten out the numbers into a float array.

```GDscript
	var t = Transform()
	t = t.rotated(Vector3(0,1,0), 0.1)
	t.origin = Vector3(-10,20,30)
	print("Original transform=%s" % t)
	var s = [ t.basis.x.x, t.basis.x.y, t.basis.x.z, 
		  t.basis.y.x, t.basis.y.y, t.basis.y.z, 
		  t.basis.z.x, t.basis.z.y, t.basis.z.z,
		  t.origin.x,  t.origin.y,  t.origin.z ]
	print(s)
	var j = to_json(s)
	print(j)
	
	var p = parse_json(j)
	var n = Transform(Vector3(p[0], p[1], p[2]), Vector3(p[3], p[4], p[5]), 
			  Vector3(p[6], p[7], p[8]), Vector3(p[9], p[10], p[11]))
	print("Parsed transform=%s" % n)
```

In contrast to this, there is a highly developed binary serialization format for shifting packets across multiplayer games that just works for Transform objects, among other things. https://docs.godotengine.org/en/stable/tutorials/misc/binary_serialization_api.html

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The Transform object has a String representation, which you get when you print its value to the console or give it to the `to_json()` function that looks like: `"0.995004, 0, 0.099833, 0, 1, 0, -0.099833, 0, 0.995004 - -10, 20, 30"`  

We could make this conversion reversible.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
We would add a new constructor into the Transform class https://docs.godotengine.org/en/stable/classes/class_transform.html

```GDscript
Transform ( String f )
	var f = str(t)
	var lf = f.split(" - ", false)
	var b = lf[0].split_floats(",")
	var o = lf[1].split_floats(",")
	return Transform(Vector3(b[0], b[1], b[2]), Vector3(b[3], b[4], b[5]), 
					  Vector3(b[6], b[7], b[8]), Vector3(o[0], o[1], o[2]))
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
See above.  

An alternative is to include that code snippet on the  https://docs.godotengine.org/en/stable/tutorials/io/saving_games.html page to give the quick work around so it doesn't take up too much of people's time working it out for themselves.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a class function.  Actually, it's very similar to the python `__repr__()` function that gives an output that usually works with `eval()`.

**Comment by TheDuriel** [comment]
Do remember that you _can_ just store_var() instead of ever converting to plain text for savegames.

Back to serialization: https://docs.godotengine.org/en/3.2/classes/class_@gdscript.html#class-gdscript-method-var2str and its counterpart exist, and work, and should be used by most of the engine already.

**Comment by goatchurchprime** [comment]
I haven't looked at the `store_var()` system yet (and it's not mentioned as an option on the Save game tutorial).  

The json format is pretty useful and easier to debug at the early stages of development when you need all the help you can get.

I'm closing this and blaming my ignorance on the documentation instead. :)  
  https://github.com/godotengine/godot-docs/issues/3893
