### ISSUE TITLE
Use the 2D main screen plugin as default instead of 3D (affects empty scenes without root node)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-proposals#1352]
**Describe the project you are working on:**
Godot Engine :)

**Describe the problem or limitation you are having in your project:**
When you create a new Godot project, or create a new scene (empty initially), the default main screen plugin (i.e. the central part of the editor) is the 3D viewport, like this:

![Screenshot_20200811_193012](https://user-images.githubusercontent.com/4701338/89929120-15655400-dc09-11ea-8b9d-ff89254b0ff8.png)

![Screenshot_20200811_192939](https://user-images.githubusercontent.com/4701338/89929075-054d7480-dc09-11ea-8434-abb9ad2264b0.png)

https://github.com/godotengine/godot/pull/41036 and this proposal suggest to change that to the 2D viewport, which is the first top menu item:

![Screenshot_20200811_193058](https://user-images.githubusercontent.com/4701338/89929191-3037c880-dc09-11ea-9fb6-209c7eafae49.png)

![Screenshot_20200811_193108](https://user-images.githubusercontent.com/4701338/89929214-375ed680-dc09-11ea-820a-cd5f092ce362.png)

This proposal serves to gather feedback from the community on which one is preferred, to see if we should change it or keep things as is. (I'm neutral myself, just opening the proposal as it's the intended workflow to get community feedback.)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

PR https://github.com/godotengine/godot/pull/41036 changes the default to "2D".

Note that this will only impact **empty** projects. As soon as you add a Node to the scene tree, the default main screen plugin for that scene will be the one that best matches the root node (2D for CanvasItem-derived nodes, 3D for Spatial/Node3D-derived nodes).
Then, any subsequent empty scene will use the same main screen plugin as the previously opened scene.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

See https://github.com/godotengine/godot/pull/41036

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Not relevant, it's about changing a default for the engine.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Yes, it's about changing a default for the engine.

**Comment by Ophiolith** [comment]
I have no idea how feasible this would be, but I guess some kind of toggle in the project settings between 3D/2D/Script for new projects might be a nice little quality-of-life feature.  That said, I mainly work in 3D, so my preference is for the current default, but I'd have no strong feelings about one extra click per new project.

**Comment by vnen** [comment]
Honestly I think it would simpler and more relevant to store the last one that you had open. Like what happens on a new scene, but store that across sessions too.

**Comment by eon-s** [comment]
I agree with @Ophiolith , when creating a new project one should be able to put if the project will be mainly for 2D or 3D, store in on project settings and the editor always leaves you on that type of editor.

This may help on modernizing a bit the Project Manager too.

**Comment by pycbouh** [comment]
While I'm currently not interested in 3D capabilities of Godot myself, I can see why making 3D is a better option for, lets say, engine promotion. Probably makes it look more seriously aimed at 3D than many would believe it is otherwise.

**Comment by reduz** [comment]
I would leave as is. While the majority of Godot users seem to use it for 2D, we don't know if this will remain being the case after 4.0 is out. 

More like, I would leave it as is, but make it customizable in the editor.

**Comment by hoontee** [comment]
The engine would probably shift towards 3D use after 4.0, so I'd say leave it as is.

**Comment by KoBeWi** [comment]
IMO this change is fine. It simplifies current behavior and changes very little actually. The viewport is already remembered when you create new scenes (even if they have Node root). So when you create a 3D project, the only thing that changes is that you have to switch to 3D *once* (and in 2D project you will likely never see the 3D viewport, unless you open it accidentally). I just don't understand why there's so much discussion over a trivial thing like this 🙃

**Comment by ArdaE** [comment]
Why not a special "splash" mode with the Godot logo and some helpful information below it for beginners (such as links to documentation, tutorials, and the latest news)?

This should only be for newly created projects though (i.e. the very first scene in a new project). For scenes that are created later, Godot's current behaviour is perfectly fine and shouldn't change in my opinion.

**Comment by aaronfranke** [comment]
One of the main reasons for this change is to make this code more generic, to avoid preferring any specific main screen plugin. The PR changes the logic to make the default be whatever the first plugin in the list is, as [explained here](https://github.com/godotengine/godot/pull/41036/files#diff-b6d74ccf775245adb707953658e4defdR422):

```
	// Switch to the first main screen plugin that is enabled. Usually this is
	// 2D, but may be subsequent ones if 2D is disabled in the feature profile.
```

**Comment by ShivamMukherjee** [comment]
Why not have this as a toggle when you create a new project?

**Comment by aaronfranke** [comment]
@ShivamMukherjee There is no point. The main screen automatically switches once you create a node anyway.

**Comment by TheNeoGameFactory** [comment]
Why Not a Option in Project creation Like unity do in their unity Hub?

Godot Project window -> create new Project -> 2d or 3d -> Render pipeline (Low or high)

**Comment by pycbouh** [comment]
@TheNeoGameFactory Exactly the same question is answered in the comment right above yours. There is no point in this setting because it would only affect the first time you see the project before making any scene with any node.

**Comment by aaronfranke** [comment]
Would anyone else like to give feedback on this? I'm still in favor of this, for many reasons. It seems arbitrary for the default main screen to be the second one on the list, and most Godot users use Godot for 2D, and also 3D users still need to use 2D for UIs.

As a reminder, the tab automatically switches to 2D when creating a `Node2D` or `Control`, and automatically switches to 3D when creating a `Node3D`, so there are no extra clicks when creating a new scene either way.

**Comment by KoBeWi** [comment]
IMO there isn't anything else to say here. I'd just merge the PR.

**Comment by nathanfranke** [comment]
Surprised I didn't notice this until now, but https://github.com/godotengine/godot/pull/41036 didn't actually change the default. It was like that originally, but I kept it at 3D due to reduz's poll. I updated the follow-up PR to also fix this oversight.
