### ISSUE TITLE
Make a simple cut-scene editor where one can drag-drop animations, sounds, so on . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1356]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
I would like to have cut-scenes, but right now it takes a lot of custom, written code, or large visual scripts, to do that . . I know Unity has a lot of flaws, but they have a nice feature, where one can place animations, and sounds, in a ' timeline ', or ' Playback Sequencer ', and sort of just trigger them . . I think it would be nice if there was such a thing, to manage cinematics, cut-scenes, or more . .

![2020-08-13 0605](https://user-images.githubusercontent.com/61069740/90093124-14c4de80-dd2b-11ea-8134-5a69c460ff12.png)

So, one can make different animations, for a character, camera-movement, and so on . . Anyway, I thought timeline worked well in Unity, it was simple, drag in animations you needed, set time, total time, so on, when one press play, it all just works, no need to make a massive ( visual script ), and fit the times, all that stuff, also sound . . . Wanted to ask, if such a editor might be a good idea, for Godot, or close . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Have a special editor, where one can drag animation tracks, and sound tracks ( Track Manager, Track Editor, or so ), and then one can ' move ' a single ' TrackNode ', ' TrackEditorNode ' into Godot, and call ' meta ' - animations, from there . . It makes a lot of sense to make the process visual, anyway, an idea, not sure, if cool . . <3

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just take the animations you want to play, at the same time, and place them in layers, so when it's set up, it just plays in sequence, all those animations, complete with sound, animation, camera movement, and effects ( ie. trigger particles, changes in camera settings, post-processing, or more ) . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm not sure, I have been wanting to make a nice cut-scene, cinematic in Godot, and it's rather confusing, how to even start . . Having a simple, powerful visual editor, where it makes sense, point-click, drag-and-drop, would really help me, get started . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
I'm not sure, I think it is built into Unity, but I'm not sure, if it's not in Godot already there might be a good reason for it, all it'd have to do was ' play ' the animations, and sounds in sequence, so one could set up a single, linear cinematic, and then be able to store several ones, that one can call, from a meta-code, or visual script box, ' TrackManager ', ' TrackComposer ', or so . . It could make a new place, in the debugger, same way adding an AnimationPlayer, one gets a sort of, well place to add key-frames, same thing, but for cinematics, ie. one can drag animations, sound, camera animations, and effect triggers, and play them, in a simple sequence, with option of having more than one sequence, to make branching animations, or cinematics . .

Thanks . .

**Comment by jasperbrooks79** [comment]
All it would have to do, was to place animations, sounds, in a meta-track, or ' timeline ', and play them in sequence, ie. character_animation01, npc_animation01, character_sound01 camera_movement01, and coordinate them . . .

**Comment by TheDuriel** [comment]
> All it would have to do, was to place animations, sounds, in a meta-track, or ' timeline ', and play them in sequence, ie. character_animation01, npc_animation01, character_sound01 camera_movement01, and coordinate them . . .

This is what Animation players already let you do though...

**Comment by jasperbrooks79** [comment]
I guess it's because I work more in a visual way, it would be nice, with a drag and drop system, where it's all visualized, like bars, ordered . . Thanks . . It's just easier to coordinate everything, visually, WYSIWYG <3 . .

**Comment by RaTcHeT302** [comment]
> I guess it's because I work more in a visual way, it would be nice, with a drag and drop system, where it's all visualized, like bars, ordered . . Thanks . . It's just easier to coordinate everything, visually, WYSIWYG <3 . .

i mean, sounds good to me 

i feel like Sony Vegas set a really good benchmark as far as, a video editing style tool goes, it's stupid easy to use and edit stuff in, so if someone wants to turn Godot, to act more like Sony Vegas, please do rip it off
![](https://i.imgur.com/ciFVh0W.png)

**Comment by Calinou** [comment]
Closing due to lack of support (see general lack of activity here). Also, this is already provided by AnimationPlayer.
