### ISSUE TITLE
Add several themes for how visual script looks to Godot 4.0

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1359]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
I use visual script, main focus was to start making simple games, and not spend 6 - 12 months learning code, even though I knew it from before, from 20 years ago, never used it . . I absolutely love visual script, for making games, prototypes, but the current look of the nodes are a bit lacking . . I asked for a major overhaul, but have noticed one can load themes, however none are available, I have tried looking . . Please consider adding some different themes, to visual script in Godot 4.0, another user ( Duriel ) has this AMAZING version, I'd LOVE having that, as an in-built theme option, for visual script, it's just 200 % better, nicer . . .

![2020-08-12 0707](https://user-images.githubusercontent.com/61069740/90141226-259d4080-dd7b-11ea-82a9-f56bd3d0f292.png)

It seems one can already do it, change the look of visual script, I'm just so excited, wanted to ask you add this as soon as possible, just a new theme, for the next Godot 3.2 release, or 4.0, that would be the nicest addition, thank you . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I just want some in-built themes, for visual script, like there is for editor color, or so . . The sooner, the better, tired of waiting, for Godot . . <3

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It should just look like the above example, as a theme, nothing more, don't know how one can find those, they're so amazing, wonderful . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know how, at all . . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's just 200 % better, the example above, thank you . . <3

**Comment by jasperbrooks79** [comment]
Also, please consider getting the above theme, but also with slightly rounded corners, on the top <3 . .

![2020-08-13 1544](https://user-images.githubusercontent.com/61069740/90141856-f3401300-dd7b-11ea-99cc-aa7c85c12bba.jpg)

Having those two themes, would be the BEST, for Godot 4.0, please consider . . In-built themes, no download <3

**Comment by jasperbrooks79** [comment]
Last, consider adding a setting, to change color of font, from white, to black, depending on theme, ie. a sort of complex visual script theme menu . . :O :O

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
