### ISSUE TITLE
Add option to import resources using a command line argument

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot-proposals#1362]
**Describe the project you are working on:**
I'm working on PR which import and check project to test PR - https://github.com/godotengine/godot/pull/40994

**Describe the problem or limitation you are having in your project:**
I can't find(because probably doesn't exists) any flag, that would only import all files(scenes, resources, images etc...)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Now I use timeout to prevent godot from quiting during importing, which sadly doesn't always work in CI
```
timeout 25s godot -e
```
but this isn't also universal solution, because  a lot of projects have a lot of assets which is impossible to measure time which is needed to import all files.

So better idea is to add new flag e.g. `--import-only` which would import files and after that just close Godot.
It would be great if the editor wasn't even running.
```
godot --import-only
```

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The best if it would work without needing initializing all graphics editor components, but I know that this isn't now possible, because code which imports resources exists in `EditorFileSystem`

The easiest way to do this is to save to variable  if user used `--import-only` option and check it in `EditorFileSystem::_notification` inside `NOTIFICATION_EXIT_TREE` if is set, so it may wait until all files will be imported.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Like I wrote, it can be used timeout but it is really really really bad solution for any project greater than 1 image.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It would be very helpful for all people wanting to integrate their projects into CI

**Comment by Calinou** [comment]
`godot --editor --quit` should do the job *in theory*.

**Comment by qarmin** [comment]
In smaller project it usually works, but with https://github.com/godotengine/tps-demo  it close after 2/3 second, which is impossible import all files because normal importing take ~30 minutes.

**Comment by Xrayez** [comment]
I vote yes! My legit use case godotengine/godot#39396.

**Comment by asheraryam** [comment]
I support this. I've worked the headless godot a lot and I found that `godot --editor --quit` is very unreliable.

**Comment by knightofiam** [comment]
I would like to see this implemented to avoid spurious CI errors when exporting via Godot headless:

```
ERROR: get_dependencies: Cannot open file 'res://.import/blahblahblahblah.sample At: core/io/resource_format_binary.cpp:1048
```

It reports an error because it can't find the `.import` folder (not under source control), but then it auto-generates it after the so-called "error" before exporting.

**Comment by Yazir** [comment]
I second @knightofiam 's comment.

Projects using build pipelines, without ./.import in repo are facing this issue. Build works, but with an error for each asset.

**Comment by aaronfranke** [comment]
I ran into this issue today. I tried `./godot --headless --editor --quit` but then a later CI step has many errors like this:

```
ERROR: Failed loading resource: res://whatever. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
```

So, as mentioned above, `--editor --quit` doesn't seem to be working as expected.

**Comment by PoolloverNathan** [comment]
Bump, I also need this for my build workflow since the web editor does not preserve the `.import` folder.

**Comment by Calinou** [comment]
@PoolloverNathan Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by myaaaaaaaaa** [comment]
A much more robust (and absurd) workaround would be to run

```godot --export "Linux/X11" /path/to/nonexistent/file```

This initiates import and waits for it to finish, then attempts to export the game, fails, and quits.

You'll then be able to perform CI tasks that require `.import/`, such as running standalone GDScripts.

**Comment by mogoh** [comment]
What is the best workaround for this issue for now?
The best that I came up with is commit `.godot/imported/*` and `*.translation`.

`timeout 25s godot -e` does not work in CI because it requries XServer which is not available in CI.

**Comment by Calinou** [comment]
> timeout 25s godot -e does not work in CI because it requries XServer which is not available in CI.

`timeout 25s godot --headless -e` will work :slightly_smiling_face:

**Comment by juse4pro** [comment]
We had the same problem and opening the project via command line in editor mode with `--quit-after 2` was solving it.
`--quit-after 1` quits too early. Related to this: https://github.com/godotengine/godot/issues/77508 (which is closed but has to be re-opened)
