### ISSUE TITLE
Add support for iOS plugins (similar to Android)

### ISSUE THREAD

**Issue by cagdasc** [godotengine/godot-proposals#1364]
**Describe the project you are working on:**
I'm working on creating Godot plugin for iPhone platform likely Android v1 plugin system.

**Describe the problem or limitation you are having in your project:**
Mobile developers need to be 3rd-party libraries for improve their apps. Some of them are ads libraries, Facebook integration, game services etc. With this integration Android and iOS apps can be same. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
At Godot, we can only create plugin for Android after 3.2.x, now with this proposal we can create plugin for iPhone and our games will run same features.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I will add a samples and first release candidate at next week.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
There is not a workaround for adding third-party library for iOS. So people needs to be add module to engine and recompile Godot.
**Is there a reason why this should be core and not an add-on in the asset library?:**
Because with this project you can create a plugin framework and you need to call this framework from core with reflection.

**Comment by Calinou** [comment]
Is this addressed by https://github.com/godotengine/godot/pull/41230?

**Comment by cagdasc** [comment]
@Calinou this can not be completely addressed I think, but both of them are similar. My solution is completely same as creating Android plugin. Your pointed issue seems like to write and plug module to Godot engine without recompile engine. I have done big part of my work and I will open a PR and add code samples.

**Comment by naithar** [comment]
> Mobile developers need to be 3rd-party libraries for improve their apps. Some of them are ads libraries, Facebook integration, game services etc. With this integration Android and iOS apps can be same.

My implementation of plugins (godotengine/godot#41230 and proposal https://github.com/godotengine/godot-proposals/issues/1185) should already cover it as well as any additional use cases that previously required engine modules. 
Using `.a` static libraries for iOS also allows direct usage of Godot's own code and minimal binary size.

I've already tried using `.frameworks` or `.xcframework` for plugins, but it required Godot binary to be `.framework` itself. Otherwise resulting framework size would be too big to even consider using it in production and using it resulted in some runtime artifacts and regressions.

Still, it would be interesting to look at your implementation :)

**Comment by cagdasc** [comment]
@naithar I look at your implementation and pluggable module idea is good work and cover my solution :) In my solution, you need to add plugin framework file to exported project and not need to edit some files. I haven't tested Swift and library size matter yet. I will share example tonight.

**Comment by naithar** [comment]
> In my solution, you need to add plugin framework file to exported project and not need to edit some files.

In my PR `dummy.cpp` file and libraries export is handled by export code, so developers don't have to do anything else other than enabling the plugin in export settings once it's in project structure.

**Comment by cagdasc** [comment]
@naithar I open a [draft PR](https://github.com/godotengine/godot/pull/41269)

I explain the code snippet and give link to project and library source at below.

First you need to create a framework which include your objective-c codes with 3rd-party libs. After compile you need to import the library framework to exported Godot project. At this time, feature can not support emit signal, I will add this feature next time.

[Project Sources](https://drive.google.com/drive/folders/1sMluVyRDmJyjPhSoy1uNUFoErt7a3NqO?usp=sharing)

**iOS Plugin Native Code:**
```
#import "GodotiOSPlugin.h"

// Plugin name for register as a singleton to engine
@implementation GodotiOSPlugin
-(NSString *)getPluginName {
    return @"GodotiOSPlugin";
}

// Plugin methods which you want to use. I must to create my own method signature definitons, because in objective-c all objects type encoding coming with "@" encoding so I can not find which type. With this definition I can validate methods.
-(NSArray<NSString*>*)getMethodName {
    return @[@"void|paramString-NSString", @"void|paramBOOL-bool", @"void|paramDouble-double", @"void|paramInt-int", @"void|paramStringArray-[NSString]", @"void|paramIntArray-[int]", @"void|paramFloatArray-[float]", @"void|paramDictionary-NSDictionary", @"NSString|returnString", @"bool|returnBOOL", @"double|returnDouble", @"int|returnInt", @"void|paramByteArray-[byte]", @"[byte]|returnByteArray"];
}

- (void)paramString:(NSString *)param {
    NSLog(@"%@", param);
}

- (void)paramBOOL:(NSNumber *)param {
    if ([param boolValue]) {
        NSLog(@"YES!!");
    } else {
        NSLog(@"NO!!");
    }
}

- (void)paramDouble:(NSNumber *)param {
    NSLog(@"%f", [param doubleValue]);
}

- (void)paramInt:(NSNumber *)param {
    NSLog(@"%d", [param intValue]);
    
}

-(void)paramStringArray:(NSArray<NSString*>*) param {
    for (NSString *str in param) {
        NSLog(@"Param: %@", str);
    }
}

-(void)paramIntArray:(NSArray<NSNumber*>*) param{
    for (NSNumber *str in param) {
        NSLog(@"Param: %d", [str intValue]);
    }
}
-(void)paramFloatArray:(NSArray<NSNumber*>*) param{
    for (NSNumber *str in param) {
        NSLog(@"Param: %f", [str floatValue]);
    }
}
-(void)paramDictionary:(NSDictionary*) param {
    NSLog(@"Param: %@", [param objectForKey:@"cagdas"]);
}
-(NSString*) returnString {
    NSLog(@"String return: ");
    return @"String Return";
}
-(BOOL) returnBOOL {
    NSLog(@"BOOL return: ");
    return YES;
}
-(NSNumber*) returnDouble {
    NSLog(@"Double return: ");
    return [NSNumber numberWithDouble:3.1415];
}
-(NSNumber*) returnInt {
    NSLog(@"Int return: ");
    return [NSNumber numberWithInt:121314];
}

-(void)paramByteArray:(NSData*) param {
    char x[[param length]];
    [param getBytes:x length:[param length]];
    for (int i = 0; i < [param length]; i++) {
        NSLog(@"Param Byte Array: %d", x[i]);
    }
}

-(NSData*) returnByteArray {
    uint8_t *bytes = malloc(sizeof(*bytes) * 4);
    
    for (int i = 0; i < 4; i++) {
        bytes[i] = i;
    }
    
    return [NSData dataWithBytesNoCopy:bytes length:4 freeWhenDone:YES];
}

@end
```

**GDScript Code:**
```
extends Node2D


func _ready():
	print("GMP: GodotMobilePlugin Started.")
	if Engine.has_singleton("GodotiOSPlugin"):
		print("GMP: GodotiOSPlugin Exist.")
		var godot_ios_plugin = Engine.get_singleton("GodotiOSPlugin")

		godot_ios_plugin.paramString("String Parameter")
		godot_ios_plugin.paramBOOL(false)
		godot_ios_plugin.paramBOOL(true)
		godot_ios_plugin.paramDouble(3.14)
		godot_ios_plugin.paramInt(298)
		
		var arr = PoolStringArray()
		arr.push_back("String")
		arr.push_back("Array")
		arr.push_back("Pushed")
		godot_ios_plugin.paramStringArray(arr)
		
		var intarr = PoolIntArray()
		intarr.push_back(1001)
		intarr.push_back(1002)
		intarr.push_back(1003)
		godot_ios_plugin.paramIntArray(intarr)
		
		var floatarr = PoolRealArray()
		floatarr.push_back(12.12)
		floatarr.push_back(13.13)
		floatarr.push_back(14.14)
		godot_ios_plugin.paramFloatArray(floatarr)
		
		var points_dir = {"string_key": "Hi I am plugin dict element"}
		godot_ios_plugin.paramDictionary(points_dir)
		
		var ret_bool = godot_ios_plugin.returnBOOL()
		var ret_str = godot_ios_plugin.returnString()
		var ret_int = godot_ios_plugin.returnInt()
		
		print("GMP: Return BOOL type: ", ret_bool)
		print("GMP: Return STR type: ", ret_str)
		print("GMP: Return INT type: ", ret_int)
		
		var byte_arr = PoolByteArray()
		byte_arr.append(-12)
		byte_arr.append(13)
		byte_arr.append(256)
		godot_ios_plugin.paramByteArray(byte_arr)
		
		var ret_byte_arr = godot_ios_plugin.returnByteArray()
		for by in ret_byte_arr:
			print("GMP: Return BYTE Array type: ", by)

```

**Comment by naithar** [comment]
Well, I can't say I fancy the idea of using objc runtime to this extent. It could be hard support and prone to bugs, that no one would be able to trace and fix. But if that works for you, thats cool :)

While your implementation does copy Android's one, for iOS this might not work that good.
Also method registration is currently untyped, which could lead to even more problems.

I've also noticed that there is no glue code for Godot api. So I understand it wouldn't be possible to directly reference engine classes, like `AppDelegate`, which would be required for implementing something like push notifications support?

**Comment by cagdasc** [comment]
@naithar thank you for your comments :) 

Yes this method is error prone. I try to use all capabilities of obj-c runtime introspection and want to create common plugin approach which copying Android plugin system. I will try to cover possible errors with checking them at runtime (untyped issue). There is a problem for push notifications you said. I need to pass the reference of `AppDelegate` and I will look at what can I do with `AppDelegate`.

After added signal support, this needs to be performance tests but while doing test there is no other method like that.

My motivation is create common method for supported mobile platforms, this method make it possible. And next time maybe can be a mobile plugin store and users can choose up to dated official plugins. Than next time maybe we can create plugins with Kotlin (Multiplatform support) and develop one time to distribute to multiple platforms.

**Comment by naithar** [comment]
> Yes this method is error prone. I try to use all capabilities of obj-c runtime introspection and want to create common plugin approach which copying Android plugin system. 

I'm not sure having same interface for iOS plugins as Android is good enough reason for bringing fragile and error prone implementation.

> I will try to cover possible errors with checking them at runtime (untyped issue). 

This would be better to be handled at compile time. Protocols or something like that could be helpful. Custom types or a mechanism like `NSPredicates` could also be helpful I think.

> There is a problem for push notifications you said. I need to pass the reference of `AppDelegate` and I will look at what can I do with `AppDelegate`.

I'm afraid injecting any service into `AppDelegate` while parts of your implementation is so fragile isn't a good idea. 

> After added signal support, this needs to be performance tests but while doing test there is no other method like that.

Not sure I understand that part - `there is no other method like that`

> My motivation is create common method for supported mobile platforms, this method make it possible. And next time maybe can be a mobile plugin store and users can choose up to dated official plugins. Than next time maybe we can create plugins with Kotlin ([Multiplatform support](https://github.com/godotengine/godot-proposals/issues/1263)) and develop one time to distribute to multiple platforms.

iOS and Android most of the time have a completely different ways to handle things, that look the same from user perspective. 
So I'm not sure if that's a good idea to have same implementation as Android for same functionality.

**Comment by jkb0o** [comment]
Actually, I do not see any problem to implement any third-party integrations using gdnative c++ API. It is possible since godotengine/godot-cpp#353. I've already use Appsflyer, Facebook, Firebase, Onesignal, Zendesk. Is this really needed? 

Addons can use Method Swizzling to overwrite AppDelegate methods. When you write a plugin using ObjectiveCPP there is no single point in iOS you couldn't access. We just need better tutorials and examples with gdnative+ios and keep engine codebase as simple as possible.

**Comment by naithar** [comment]
As I've stated in PR, GDNative doesn't give direct access to `AppDelegate` or any other platform specific Godot's code for iOS.

And method swizzling is not really a good/safe/reliable option and should be treated with caution. Especially since Apple could make (and did it multiple times already) private/undocumented changes to the API, which would be hard to track down with swizzling.

Plugins in some form would address this issues.
There are already two implementations for plugins, so the question is not only `Is plugins needed` but also `How they should work`.

**Comment by m4gr3d** [comment]
@cagdasc Sorry for the delay, but I was incorrectly linked to this proposal as I only cover Android related development and iOS is outside of my area/knowledge.

That said, I fully agree with @naithar as that the plugin implementation should follow the approach best suited to the target platform. Trying to make them compatible is a moot point is the implementation is fragile/prone to bugs.
So I'd recommend to stop trying to emulate the Android plugin architecture and instead collaborate with @naithar on what the best implementation for iOS would be.

Even for projects that use Kotlin multiplatform, only the `business logic` is shared. Platform specific logic is implemented following the platform's recommended approach so even your idea for a common multiplatform plugin is not realistic as such implementation would be **very** limited in scope.

**Comment by cagdasc** [comment]
Okay. Thank you for your comments. I am stopping the development for this proposal.
