### ISSUE TITLE
Starting project should start out with a default audio asset

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot-proposals#1365]
**Describe the project you are working on:**
Any

**Describe the problem or limitation you are having in your project:**
No default audio.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
We start all projects with a default icon AND a default environment. We should start with default audio.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
res//:
    default_env.tres
    icon.png
    sound.ogg

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Starting project.

**Comment by clayjohn** [comment]
Could you go into more detail why?

**Comment by Zireael07** [comment]
Many projects do not need audio at all. Unless it's like a teeny-tiny file, my vote is no.

**Comment by TheDuriel** [comment]
The usefulness of a single Sine Beep is highly questionable. A more specified sound would be completely useless.

**Comment by bojidar-bg** [comment]
Very random thought: instead of a simple sine beep or similar sound effect, the default audio might be a recording of the "proper" pronunciation of "Godot", just like the default image is a the "proper" visual representation of "Godot".

**Comment by CenTdemeern1** [comment]
I would go with a double square wave beep. It sounds retro and is less stale to your ears. It's used often in chiptune music.

**Comment by LillyByte** [comment]
I approve of this and would like to subscribe to your newsletter.

Also, if the audio is of the correct pronounciation of Godot, which is a great idea-- it should also include all the incorrect ways it's pronounced as well, but also don't point out which one is correct... because we need the conflict to bide our time.

**Comment by RaTcHeT302** [comment]
i don't know, i mean, everyone is making fun of this, but i wouldn't mind if a sample music track was included, along WITH a sample sound effect

this may seem stupid, but i guess it wouldn't hurt to know what frequency an audio file needs to be at, plus i feel like it would give godot some personality, and a ton of people use the godot icon as an actual placeholder texture, so having some placeholder audio could actually have some usage for a fast prototype

i really wouldn't mind some extra, minor placeholder assets, i mean, people DO use them, as strange as that may seem, plus people can just double click on the audio or on the music, and it gives them an excuse to see what the user interface for those things looks like

**Comment by TheDuriel** [comment]
Btw, for setting up streamplayers you dont need an actual sample. You can make an empty one within the inspector just fine.

**Comment by CenTdemeern1** [comment]
Oooh, what if we added a menu to the Godot editor which allows you to choose from a library of placeholder assets?
Including textures, audio, models, all kinds of stuff!
I remember Scratch (yes I know I also can't believe I'm bringing that stupid thing up) having a library like this, with template sprites which include audio and animation frames.
With something like this, it could give a lot of projects a kickstart!
(I might open up a proposal issue thing myself)

**Comment by Calinou** [comment]
> Oooh, what if we added a menu to the Godot editor which allows you to choose from a library of placeholder assets?
Including textures, audio, models, all kinds of stuff!

[It already exists](https://godotengine.org/asset-library/) in the form of the AssetLib tab and Templates tab in the Project Manager. It's up to people to provide high-quality template packs still :slightly_smiling_face:

**Comment by Jummit** [comment]
Just to clear this up: The reason there is a image file in the default project is that it needs an application and project icon.

> AND a default environment. 

A default environment is also necessary for 3d scenes to work when there is no ´Environment´ node added yet.

Instead of making this about adding one file, a way to customize the files of a default project would be a more general solution with much more use cases.

**Comment by CenTdemeern1** [comment]
The assetlib doesn't contain audio or textures though. And the templates are just templates.

> Just to clear this up: The reason there is a image file in the default project is that it needs an application and project icon.

Yes, we know.

**Comment by nathanfranke** [comment]
> **Is there a reason why this should be core and not an add-on in the asset library?:**
Starting project.

I would not consider this a valid answer to the question. I think the best place to put assets like sounds would be in the asset library.

**Comment by Calinou** [comment]
There are now audio assets in the asset library, such as [Kenney Interface Sounds](https://godotengine.org/asset-library/asset/793) and [Kenney UI Audio](https://godotengine.org/asset-library/asset/795).

Since this proposal isn't getting much support per the above discussion and reactions on OP, I'll close it.
