### ISSUE TITLE
Add a volumetric cull mask to lights for volumetric fog (and implement an "additive fog" option for volumetric lighting)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#1374]
*Note: This feature was discussed with reduz. It's probably good to implement if someone finds a way to do it.*

**Describe the project you are working on:**

The Godot editor :slightly_smiling_face: 

**Describe the problem or limitation you are having in your project:**

With the [newly-added volumetric fog effect](https://github.com/godotengine/godot/pull/41213), it's not possible to prevent individual lights from contributing to the volumetric fog's color.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

A volumetric cull mask property could be added to prevent individual lights from contributing to the volumetric fog's color.

Alternatively, this can be done by adding a Volumetric Fog Energy property to Light3D. (It's probably better as it gives more control to the user, rather than an all-or-nothing solution.)

In addition, there should probably be a way to disable fog completely in areas not lit by anything (instead of having a black fog). This way, it can be used purely as a volumetric lighting solution, not adding any fog unless desired by the artist.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

There could be a Volumetric Cull Mask property mimicking Light's Cull Mask property. It would only affect volumetric fog. Direct and indirect lighting would be left unaffected by this mask.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, as this is core renderer functionality.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is core renderer functionality.

**Comment by SIsilicon** [comment]
Volumetrics has been added to 4.0? That's pretty neat! Now I don't have to worry about porting my volumetrics plugin. 😄

On a more related note, I was actually thinking of adding cull layers to my system as well.
So how will this work? Like have a cull mask in the volumetric fog settings? Then the mask will just cull away lights that aren't in the same layer.

**Comment by MadaraZ** [comment]
@SIsilicon yes, already added merge master 4.0 recently (Volumetrics Plugin can be forgotten)

**Comment by MadaraZ** [comment]
watch youtube https://www.youtube.com/watch?v=wYZ_GUitNnk only works Vulkan

**Comment by MadaraZ** [comment]
@SIsilicon I recently tested plagiarism lags hard GLES3 Volumetrics Plugin

**Comment by Calinou** [comment]
@MadaraZ Please use the Edit button (hidden behind the **…** dropdown in the top-right corner) instead of multi-posting.

**Comment by Calinou** [comment]
I started work on this here: https://github.com/Calinou/godot/tree/volumetric-fog-add-per-light-energy

The "additive fog" part works great (with OmniLights at least), but it needs per-light fog energy to be really useful. Unfortunately, I haven't got that part to work yet.
