### ISSUE TITLE
Add monitorable/monitoring properties to KinematicBody[2D] node

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot-proposals#1377]
**Describe the project you are working on:**
2d rpg

**Describe the problem or limitation you are having in your project:**
`KinematicBody[2D]` doesn't have monitoring and monitorable properties like `Area[2D]` does, so in order to disable/enable collisions, you need to manually adjust collision layer and collision mask bits, which is annoying and error prone.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Add monitoring and monitorable properties to `KinematicBody[2D]` to be consistent with `Area[2D]`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Add the properties to the class and expose via scripting api

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The work around is manually fiddling with collision layer and collision mask bits which is painful anf error prone.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's part of a core class.

**Comment by KoBeWi** [comment]
You can also set collision shapes to disabled.

**Comment by TheDuriel** [comment]
This would not be consistent, Kinematic Bodies do no perform any monitoring. And detection by different Objects can already be controlled via Masks (thread safe), or Shapes (not thread safe).

**Comment by jonbonazza** [comment]
That's fair @TheDuriel . Closing.
