### ISSUE TITLE
Improve post-process color correction by supporting 3D LUTs instead of a single Gradient

### ISSUE THREAD

**Issue by UnknownS1024** [godotengine/godot-proposals#1382]
**Describe the project you are working on:**
Godot Editor, I will decide to work on ARPG 3D (low poly)

**Describe the problem or limitation you are having in your project:**
Godot need to improve post process (LUTs) for Color Grading very helpful

Area Post Process Box example hit inside color change other different colors

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
description here
![image](https://user-images.githubusercontent.com/17591539/90359103-a5b7f480-e060-11ea-9a32-b6ad19851811.png)

https://docs.unrealengine.com/en-US/Engine/Rendering/PostProcessEffects/UsingLUTs/index.html

example screenshot to the left or to the right the color is different depends on customize for the designer
![image](https://user-images.githubusercontent.com/17591539/90359646-24616180-e062-11ea-9d40-dfe31db74155.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
.......

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
.......

**Is there a reason why this should be core and not an add-on in the asset library?:**
Post Process is very useful for realistic graphic games, if without it it would be very bad, this is for 3D AAA studio games (of course the core)

**Comment by Calinou** [comment]
See also #903.

**Comment by fire** [comment]
This pull request can be updated for 4.0 if you're interested. https://github.com/godotengine/godot/pull/26101

It's less hard than #903.

**Comment by Madaraz1024** [comment]
> This pull request can be updated for 4.0 if you're interested. godotengine/godot#26101

yeah i'm see

**Comment by fire** [comment]
I ran out of effort, but you can see my last pr. The vulkan render isn't showing the 3d lut.

https://github.com/godotengine/godot/pull/42761

**Comment by fire** [comment]
See updated pr.

**Comment by Madaraz1024** [comment]
checking now :)

**Comment by Jummit** [comment]
Isn't this added in godot#42761?

**Comment by clayjohn** [comment]
> Isn't this added in godotengine/godot#42761?

Yep. Closing as it has been added. :)
