### ISSUE TITLE
Narrowing conversion from float to int must be reported as a warning

### ISSUE THREAD

**Issue by Vivraan** [godotengine/godot-proposals#1383]
**Describe the project you are working on:**
Proposal is valid anywhere.

**Describe the problem or limitation you are having in your project:**
When I statically typed a var as an int, and accidentally forgot that it was supposed to be a float, it always silently floored (0.25 to 0, say), so a resulting float times int multiplication was always evaluating to zero.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Warn when assigning a float to an int about lossy conversion.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A static check to see if the resulting rhs is equal to its own floor.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Using dynamic typing skirts around this, but breaks consistency. Plugins would make it opaque, where it is required to be implicit.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is supposed to be a chage in the core.

**Comment by Calinou** [comment]
This seems more of a bug than a feature proposal to me.

**Comment by Vivraan** [comment]
I entertained the possibility that it was the intended behaviour - it also doesn't really have any mention in any doc, so I put it here and referred to this on the bug report.

**Comment by Vivraan** [comment]
How are code warnings usually generated?

**Comment by Vivraan** [comment]
Any updates?

**Comment by nene** [comment]
It seems this has already been implemented:

<img width="620" alt="Screenshot 2022-03-07 at 13 39 54" src="https://user-images.githubusercontent.com/118201/157025528-bfce3668-4f1b-49b3-8151-c15b16e25ce8.png">
