### ISSUE TITLE
Add an `autoplay` property to AnimatedSprite

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#1390]
**Describe the project you are working on:**
2D game with lots of animated stuff.

**Describe the problem or limitation you are having in your project:**
I sometimes decide to use an AnimatedSprite and I come into the same problem - there's no way to properly play an AnimatedSprite in game without using a script. AnimationPlayer has an autoplay functionality, but AnimatedSprite is missing it. This leaves basically 2 options:
- setting `playing` to true. This means that your animation will play in the editor, constantly changing the `frame` property. Every time you save the scene, a different value ends in the `tscn`, which is bad for your VCS
- playing it in a script. That requires every single AnimatedSprite having a script attached, which is meh

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There could be an `autoplay` property, which if true would make an animation play when AnimatedSprite is ready (in-game). This is consistent with AnimationPlayer and AudioStreamPlayers.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just add the `autoplay` property and set `playing` to true in `NOTIFICATION_READY` if `autoplay` is true.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be worked around with 3 lines of script, but that script could've not existed in the first place.

**Is there a reason why this should be core and not an add-on in the asset library?:**
AnimatedSprite is clearly missing this.

**Comment by Calinou** [comment]
Shouldn't the `autoplay` property be defined on a per-animation resource in the SpriteFrames resource instead? This would be more consistent with AnimationPlayer's behavior where this is stored on a per-Animation basis.

That said, it might not be technically feasible.

**Comment by KoBeWi** [comment]
The `autoplay` in AnimationPlayer is actually an AnimationPlayer property, which simply stores the animation name.

Although storing it in SpriteFrames resource in AnimatedSprite shouldn't be difficult to do. We could add another button here
![image](https://user-images.githubusercontent.com/2223172/93006221-d6088b00-f559-11ea-8f4c-d30dbfa8637d.png)
and display an icon next to the autoplayed animation.

**Comment by elvisish** [comment]
Agreed, how is it meant to autoplay currently, if Playing is enabled?

**Comment by Calinou** [comment]
> Edit: Oh, it looks like #54633 might fix this, although it appears to have stalled.

I think you meant to link https://github.com/godotengine/godot/pull/54633 :slightly_smiling_face:

**Comment by domdfcoding** [comment]
This was closed as completed but I can't find the option in 4.2.2. Was it added and removed/renamed or did it never actually get added?

**Comment by dalexeev** [comment]
@domdfcoding

![](https://github.com/user-attachments/assets/74d7528f-8e30-4fda-a647-30aba0fe401f)
