### ISSUE TITLE
`Node.get_child(-1)` should return last child

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#1392]
**Describe the project you are working on:**
A game using GDScript.

**Describe the problem or limitation you are having in your project:**
This is a convenience issue. To get the last child of a node you need to do `get_child(get_child_count()-1)`, which is needlessly long.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
`get_child(-1)` should return the last child of a node. Could be theoretically expanded to negative indices like in Array, but from my experience the last child is much more often useful than second to last etc.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
> `get_child(-1)` should return the last child of a node.

The implementation is trivial, just check if the index is -1 and replace with child count -1 if yes.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
With this
> `get_child(get_child_count()-1)`

but it could be shorter.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's about core method.

**Comment by nhold** [comment]
Would -2 get second from the back?

Maybe a get_child_back\reverse(int index) would make more sense (0 being last node, 1, second last etc).

**Comment by volzhs** [comment]
`get_children()[-1]` is not enough?

**Comment by TheDuriel** [comment]
@volzhs That would be unsafe and crashes with an empty array. get_child at least returns a null instance instead.

I agree that all index lookups in the engine should follow array logic and wrap via negatives.

**Comment by Xrayez** [comment]
I like the idea but we're potentially mixing how C++ vs GDScript work, which might be a bad idea.

How about adding a new `get_last_child()` method? Unless you want this proposal to be extended to "get second to last child" as you say.

For any other array-based operation we could use `get_children()` as suggested above.

> That would be unsafe and crashes with an empty array.

In theory you could also use `get_children().back()` to return `null`, but it would *just* print an error. @KoBeWi is this proposal one of the reasons why you raised godotengine/godot#41204? 🙃

But if you were to make it consistent, you'd now have to add `get_first_child()` over `get_child(0)`.

To make it even more complete, it would be great to have more navigational methods: `get_first()`, `get_next()`, `get_previous()`, `get_last()`, as typically seen in other node-based APIs.

**Comment by KoBeWi** [comment]
> How about adding a new get_last_child() method?

Adding a separate method for that is probably too much 🙃

> Unless you want this proposal to be extended to "get second to last child" as you say.

I already said that it's rarely useful. You usually need the first child, last child or iterate all of them.

> is this proposal one of the reasons why you raised godotengine/godot#41204?

Nah, it's unrelated. Also `get_children()` returns a copy of the children array, so you can use `pop_back()` to avoid error. (also using it is slower™ than `get_child()`)

**Comment by SekoiaTree** [comment]
Made a pr: https://github.com/godotengine/godot/pull/41505
