### ISSUE TITLE
Implement script editor description hint on hover a symbol/word

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot-proposals#1393]
**Describe the project you are working on:**
Description hint on hover for the text edit(https://github.com/ThakeeNathees/godot/tree/TextEdit-hover-hint)

**Describe the problem or limitation you are having in your project:**
it's one of the essential feature for a fully featured script editor and currently we lack of. Also the implementation of GDScript doc comments (https://github.com/godotengine/godot/pull/41095) it'll improve the user experience.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
when a symbol is hovered by the mouse, the text editor emits a signal to validate the symbol (like when it's being hovered with a ctrl), and when validating for that symbol it'll add some additional data (like description, type, class_name, return_type, arguments, etc.,) and display them at the text edit's draw call.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A working example (this will work with doc comments when it'll be merged)
![hint2](https://user-images.githubusercontent.com/41085900/90722006-9d1d2380-e2d7-11ea-9aca-a3555145a481.gif)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, It would be a great usability improvement and can't be worked around with the script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
there is no way to implement this with an add-on

*Bugsquad edit (keywords for easier searching): tooltip*

**Comment by echebbi** [comment]
I'm glad to see that someone is finally working on this, thanks very much for the work! 

Would it also be possible associate the "show hint" action to a keyboard shortcut (i.e. show the hint corresponding to the symbol at the cursor's location)? I mainly use the keyboard when coding and having to take the mouse each time I want to check the documentation would be inconvient.

**Comment by me2beats** [comment]
Providing API for (optional) having this for custom classes and methods could be useful as well

**Comment by Calinou** [comment]
@me2beats This will probably be done automatically by https://github.com/godotengine/godot/pull/41095.

**Comment by ThakeeNathees** [comment]
@me2beats yeah it's possible with godotengine/godot#41095 tested locally.
I've exams next month, I'll improve it and implement color themes when it's done :)

**Comment by elvisish** [comment]
Oh please say this will happen, coming from Unity I feel lost without hover hints.

**Comment by Calinou** [comment]
@elvisish Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by alterae** [comment]
Is work on this still ongoing?  The last commit in the linked fork was over a year and a half ago

**Comment by Calinou** [comment]
> Is work on this still ongoing? The last commit in the linked fork was over a year and a half ago

ThakeeNathees has been inactive on GitHub for a long time, so https://github.com/godotengine/godot/pull/41502 will likely have to be salved by another contributor.

**Comment by Dante3085** [comment]
I would really like to have this feature now. Is there any way to make a custom Godot Editor build with the functionality shown in the gif at the top?

**Comment by Calinou** [comment]
> I would really like to have this feature now. Is there any way to make a custom Godot Editor build with the functionality shown in the gif at the top?

No, as there is no up-to-date branch with an implementation of this feature. The script editor received a large refactor last year, so most of the work would have to be redone from scratch.

**Comment by jwmcgettigan** [comment]
I'm interested in taking a stab at this issue so I've done a quick review of (1) what we already have that is similar, (2) references to the solution in other applications, and (3) the possible features/requirements that may be considered.

## Review of Existing/Similar Implementations

### 1. Generic tooltip
![godot-mono_2023-03-12_13-52-04](https://user-images.githubusercontent.com/1691061/224563111-88860f0c-e289-47ae-ad37-ae8938d19025.gif)

### 2. Inspector elements tooltip on hover
![godot-mono_2023-03-12_13-30-19](https://user-images.githubusercontent.com/1691061/224561862-2b582f69-eb82-4427-ad2c-504ed36d31d6.gif)

### 3. Intellisense dropdown
![godot-mono_2023-03-12_14-16-29](https://user-images.githubusercontent.com/1691061/224564260-1251af57-449f-4cde-858f-320809afc0a6.gif)

### 4. The authoring comment of this issue.
* https://github.com/godotengine/godot-proposals/issues/1393#issue-682448616

### 5. Existing draft for this issue (for Godot 4)
* https://github.com/godotengine/godot/pull/63908
  * Appears to work only for some functions.  Has many issues to iron out.  Last update was 6 months ago.
  * Note: You need to replace all instances of `plus_file` with `path_join` to be able to build it.

![godot windows tools x86_64_2023-03-12_13-35-13](https://user-images.githubusercontent.com/1691061/224562101-821811a7-fdc4-4671-8110-18ace3d53228.gif)

## References

### 1. Visual Studio (C#)
![devenv_2023-03-12_14-18-39](https://user-images.githubusercontent.com/1691061/224564354-07bfe04c-44e7-4fee-89f1-5b7655f84059.gif)

### 2. WebStorm (JavaScript/TypeScript)
![webstorm64_2023-03-12_14-33-11](https://user-images.githubusercontent.com/1691061/224565042-b7c08e2c-eb5f-4286-8e86-28c9f1e036c6.gif)

### 3. Visual Studio Code (Python)
![Code_2023-03-12_14-37-46](https://user-images.githubusercontent.com/1691061/224565296-8c4cf28b-d849-454f-a471-6ce0849d84c2.gif)

### 4. Visual Studio Code (JavaScript/TypeScript)
![Code_2023-03-12_14-53-34](https://user-images.githubusercontent.com/1691061/224566308-a35c84f4-9c2b-43ce-ba4b-3886314ccbdb.gif)

## Review of Possible Features/Requirements

1. Provide a tooltip hint when hovering over a function/variable. (e.g. Reference 3)
    a. Determine tooltip padding, border, and border-radius.
    b. Dynamically adjust height and width.  Set max-width and max-height.
    c. Dynamically anchor the tooltip depending on how close to the edge of the editor you are.
    ![image](https://user-images.githubusercontent.com/1691061/224610341-1aabac49-5bc2-4c8f-9eec-2fa40167511b.png)
    d. Should there be a delay on hover before showing the tooltip? For example, the inspector tooltip has a delay.
    e. Include the icon for the type of item. (e.g. class, function, variable, etc.)
    Godot icons example             |  How it would be included
    :-------------------------:|:-------------------------:
    ![image](https://user-images.githubusercontent.com/1691061/224610594-d2a0fff7-25f5-48c3-8ed7-40aa886e971f.png) | ![image](https://user-images.githubusercontent.com/1691061/224608896-68f7afbf-31ed-466c-b77e-9ea146c2b8cb.png)
2. Keep tooltip open if the mouse is hovering over it. (e.g. Reference 1)
    a. Show scrollbar if there is vertical overflow.
    b. Allow the tooltip to be resizable.
    * Would also be useful to implement for the inspector elements tooltip.  (Is there an open issue for this?)
4. Have links to functions/types/parameters/websites in tooltip.  (e.g. Reference 1)
    * This will depend on document comment capabilities.
      * https://github.com/godotengine/godot/pull/41095
    a. Support links that jump to the classes, functions, and variables in the _code_.
    ![image](https://user-images.githubusercontent.com/1691061/224575567-84a98557-117e-4bc3-806d-5d34be0751a4.png)
    b. Support links that jump to the classes, functions, variables, or types in the _documentation_
    c. Support external links to websites.
    d. Nested tooltips.
    * Would also be useful to implement for the inspector elements tooltip.  (Is there an open issue for this?)
5. Show any errors or warnings (e.g. type hints) related to the function/variable. (e.g. Reference 2)
![image](https://user-images.githubusercontent.com/1691061/224582877-c7b994d4-f814-401a-88c4-a44843725996.png)

## Notes

Some improvements I'd like to make to this comment include:
* Add additional possible features that have been overlooked.
* Reword some of the features and/or provide better example and images for them.
* Create some example UI designs for what the tooltip may look like.
* Add links to any issues or PRs that are relevant.

**Question**: Should I create another issue or a discussion for the contents of this comment?  I'm not sure if the scope of this issue encompasses these possible features and if this is the right place for their discussion in case it leads to off topic comments.

**Comment by Calinou** [comment]
> d. Should there be a delay on hover before showing the tooltip? For example, the inspector tooltip has a delay.

Definitely – I'd use the same delay as GUI tooltips and EditorHelpBits in general.

**Comment by jwmcgettigan** [comment]
Here are some UI designs that I experimented with (using HTML/CSS).

![chrome_2023-03-14_00-44-32](https://user-images.githubusercontent.com/1691061/224895600-82bbf26a-b481-48a7-a8df-ed072ade67ea.gif)

You can find the file or preview it below.
- **Gist:** https://gist.github.com/jwmcgettigan/3a563a4df07f02c94d5fc866ca43b851
- **Preview:** https://gistpreview.github.io/?3a563a4df07f02c94d5fc866ca43b851

### Notes
* I only implemented an example tooltip for the `_ready()` function.  Nothing else will show the tooltip on hover.
* Styles, colors, and icons are by no means polished.  These are just to determine a design direction.
* I plan to change the links and code block styles to mimic the in-editor godot-docs.
* I've added a few more feature bullets to my previous comment.

**Comment by Spartan322** [comment]
Just to point out I have just rebased godotengine/godot#63908 to master.

**Comment by Arecher** [comment]
As a side-note, it's worth adding Editor Settings to determine what/how much is shown on the hovers. Personally, I'd never really want to hover and see function documentation. I'd mostly want to hover arguments to see their name and type (especially for custom functions), so a very minimal hover would be preferred.

If the tooltip could automatically adjust it's content based on settings, it could remain one general hover, while still allowing users control over what information they see!

**Comment by jwmcgettigan** [comment]
> Would also be nice if the tip showed on auto completions as a sub popup.

I presume you mean something like this?

![Code_2023-07-26_00-13-46](https://github.com/godotengine/godot-proposals/assets/1691061/6decb3cf-5ed4-4c70-9642-0c9348e3a5d8)

**Comment by TheColorRed** [comment]
> > Would also be nice if the tip showed on auto completions as a sub popup.
> 
> I presume you mean something like this?
> 
> ![Code_2023-07-26_00-13-46](https://user-images.githubusercontent.com/1691061/256114912-6decb3cf-5ed4-4c70-9642-0c9348e3a5d8.gif)

Yup, just like that!

**Comment by TheColorRed** [comment]
Not sure if it is supported or not (the docs don't show support), so maybe this would be a new proposal, using a `@param` tag to describe a function parameter would be nice to show in the popup (again similar to vscode).

```gdscript
## Do something with the two colors
## @param color1 Description of color 1
## @param color2 Description of color 2
func fancy_color(color1: Color, color2: Color):
  # Do something with the two colors
```

So, when creating a JavaScript/TypeScript function, the popup shows like this image, as seen, it auto formats the `@param` items with the name, and its description.

![image](https://github.com/godotengine/godot-proposals/assets/1571806/6202242c-6f5b-406c-b89f-3f1f6ea12fcd)

**Comment by Calinou** [comment]
> Not sure if it is supported or not ([the docs don't show support](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html#tags)), so maybe this would be a new proposal, using a @param tag to describe a function parameter would be nice to show in the popup (again similar to vscode).

The way Godot class reference docs are written favors documenting parameters inline in the description, using `[param name]` references to reference parameters in the description.

**Comment by devchenli** [comment]
It has been 3 years and this feature has not been officially launched yet.  It seems that Godot still has a long way to go. Thank you to those who have contributed to this feature.
