### ISSUE TITLE
Expose Structs to GDScript

### ISSUE THREAD

**Issue by brndel** [godotengine/godot-proposals#1394]
**Describe the project you are working on:**
A project using GDScript

**Describe the problem or limitation you are having in your project:**
Nodes like `ItemList` have tons of functions to set/get text, icon, modulate, metadata, tooltip... of the items. As GDScript is a object oriented programming language this doesn't feel very right.

Some other places, where i have found those kind of functions are `TreeItem`, `Tabs` and `RayCast` (probably there are some more)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Internally `ItemList`, `TreeItem` and `Tabs` are using a Struct for the items, so one way to get rid of all of those functions, would be to add Structs to GDScript (which also is a feature, requested by some users), alternatively the said Nodes could use Objects instead of Structs, because the can already be exposed to GDScript.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

ItemList
```
var item : ItemList.Item = ItemList.get_item(0)
item.text = "new text"
item.icon = load("res://icon.png")
```

TreeItem
for TreeItem.Cell i would also imagine Subtypes like TextCell, ButtonCell, IconCell, CheckCell...
```
var text_cell : TreeItem.TextCell = TreeItem.get_cell(0)
cell.text = "edited cell"

var button_cell : TreeItem.ButtonCell = TreeItem.get_cell(1)
button_cell.text = "press me"
button_cell.disabled = false
```
RayCast
```
$RayCast.force_raycast_update()
var hit_result : RayCast.HitResult = $RayCast.get_hit_result()
if(hit_result.hit):
  show_hit_effect(hit_result)
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no
**Is there a reason why this should be core and not an add-on in the asset library?:**
not possible

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2816, which is more detailed and has received more discussion.
