### ISSUE TITLE
Complained a lot about visual script looking bad - found a setting, now it's wonderful, sorry . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1397]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
Visual script didn't look so good, found a button <3 . .

<img width="993" alt="Skærmbillede (15)" src="https://user-images.githubusercontent.com/61069740/90892946-74238e00-e3be-11ea-9268-2f1a49ecf8e3.png">

![Skærmbillede (16)](https://user-images.githubusercontent.com/61069740/90892960-78e84200-e3be-11ea-9c5f-bb035a6c13c6.png)

![Skærmbillede (19)](https://user-images.githubusercontent.com/61069740/90892971-7c7bc900-e3be-11ea-9fe2-6126c8500477.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I asked for a lot of visual script changes, for Godot, my only request is, you make a button, so one can make top corners of the boxes a bit rounded, just a setting, under the editor . .

![2020-08-13 1544](https://user-images.githubusercontent.com/61069740/90893062-9ddcb500-e3be-11ea-8755-85ddba6e1df6.jpg)

I also think it would be really nice, with an expandable lower bar, like image, where there could be settings, such as for changing color of box, from a 16 color palette, or so . . Right now, visual script is 98 % perfect, so nice, anyway, can't really ask for more, but that's my hope, just, gotta give you praise, it's so amazing, well done . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Well, like the image, a setting in editor settings, to have ' Graph Node Headers Colored ', ' Graph Node with Rounded Top ' . . So, we can make it look, like Blender visual shaders, which is probably best, looks bit, like thinking bubbles . . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I can't change engine, on my own . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
As an extra setting, in editor, it would not bloat the engine, and give visual script users an extra option . . Right now, I'm so happy with how it looks, I'm not sure even ask for it, but wanted to try . .

<3 . .

**Comment by fire** [comment]
Proposal resolved by proposer.
