### ISSUE TITLE
Improve editor property capitalization

### ISSUE THREAD

**Issue by im4potato** [godotengine/godot-proposals#1399]
I'm not sure if this type of suggestion belongs here, but I couldn't find a more appropriate place.

**Describe the project you are working on:**
Cleaning up the Godot editor UI strings.

**Describe the problem or limitation you are having in your project:**
Many strings in the Godot editor are not properly capitalized, acronyms only capitalize the first letter, or abbreviations are used. I know these are small issues, but it would contribute to a more cohesive and "correct" UI.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I would like to see many of the strings throughout the editor cleaned up so that they use the proper syntax. Many of these issues can be found in `Editor Settings`, for instance, `Network > Ssl`. SSL is an acronym, all letters should be capitalized. Similarly, `2D` and `3D` should be used, not `2d` and `3d`. `Poly Editor` should be `Polygon Editor`, etc.
![Screenshot from 2020-08-21 15-13-28](https://user-images.githubusercontent.com/62815710/90940160-b64ece80-e3c2-11ea-82b7-09fd67ade9fc.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
These strings should simply be updated to their proper forms. I've already tried to look into doing this myself, but I can't seem to find these UI strings anywhere within the project, which makes me think that they are somehow generated from some other bit of code, so perhaps there is a technical reason why things are the way they are currently, but I still believe this should be cleaned up.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/58706.
