### ISSUE TITLE
Support f-string variable replacement similar to Python.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot-proposals#140]
Support f-string variable replacement similar to Python.

Example:

```
var x='abc'
output =  f'The alphabet starts with {x}'
print(output)
```

Saves the headache from having to add extra .format or % parameters.

**Comment by Calinou** [comment]
In the interest of having high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
