### ISSUE TITLE
Plug a graph drawing framework into GraphEdit, for automatic layout and routing

### ISSUE THREAD

**Issue by umarcor** [godotengine/godot-proposals#1401]
**Describe the project you are working on:**

The main mechanic of a tool I'm prototyping is an [schematic editor](https://en.wikipedia.org/wiki/Schematic_editor). There is a logical problem/puzzle that needs to be solved by combining pre-existing blocks/modules with given functionality and inputs/outputs. 

Hence, the use case has virtually no difference compared to any other usage of GraphEdit, including the Visual Editor in godot.

Several in-progress PRs apply to GraphEdit (godotengine/godot#37227, godotengine/godot#40043, godotengine/godot#40322), but none of them conflicts with this request from a feature point of view. However, code conflicts might exist.

**Describe the problem or limitation you are having in your project:**

In complex schematic diagrams, laying all the blocks in a left to write flow is inneficient. The vertical space can be better used by laying the blocks in several rows (a grid). Furthermore, clustering can significantly aid in providing an easy to understand layout/graph.

However, current connections are splines or bezier curves. As a result, feedback connections (the ones going from right to left) are drawn below the blocks/nodes/modules. On the other hand, clustering seems not to be supported.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Many libraries exist for automatic layout and routing of diagrams, since it is a complex task that has been throroughly studied. The proposal is to pick one that is compatible with godot, in terms of licensing. Then, provide some acceptable defaults/presets in GraphEdit class/node.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

In the following references, multiple layout algorithms are shown:

- https://ogdf.uos.de/wp-content/uploads/2019/04/ogdf.pdf
- http://rtsys.informatik.uni-kiel.de/%7Ebiblio/downloads/theses/msp-dt.pdf

From godot's user's point of view, there would be 1 or 2 options added to the 'GraphEdit' section of the 'Inspector', just below current 'Use Snap' or 'Zoom':

- Layout: algorithm used to position the nodes in the graph. Defaults to 'unset' or 'manual'.
- Router: algorithm used to draw the connections between nodes in the graph. Defaults to 'unset', 'splines' or 'bezier'.

Optionally, clustering would be supported. I believe a new node class would need to be written. From the usage perspective, users/developers/players would select a group of GraphNodes and would click an option to "Create cluster". There are two possible types of clusters:

- Transparent: a box is drawn in the diagram, but connections are not changed.
- Node/entity: ports are added to the cluster for each ingoing or outgoing connection; then existing connections are broken/split, for making them pass through the ports of the cluster.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

My main concern is routing of connections. I believe it is currently not possible to override how connections are drawn by GraphEdit. I assume that rewriting the class from scratch might be needed.

Regarding layout algorithms, there is #1253 where implementing 6 different algorithms is proposed. Should any of those be significantly different from the ones available in existing libraries, I wonder whether contributing them there might be a better long-term approach.

I think that clustering is NOT a priority. I mentioned it because it is thoroughly covered in some of the references, and it would come handy. Nevertheless, I believe that improving routing and layout are the relevant enhancements, in that order.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Having a "nice" schematic editor combined with godot's engine and assets is an unvaluable framework for gamification of all kinds of subjects. Schematic graphs/diagrams are used in many areas of engineering for communicating knowledge between programmers/designers and other developers. With GraphEdit, most of the functionality is already there. The only missing feature for working with large/complex graphs to be pleasing is a well-thought layout and routing solution.

Hence, it might be possible to duplicate GraphEdit, should making godot dependent on any external library be unacceptable. Otherwise, I believe that all the current users of GraphEdit would benefit from the enhancement being built-in.

Ref #506 #593 #1159 

# OGDF

OGDF is a long going open source project developed by several international research groups. It stands both for *Open Graph Drawing Framework* (the original name) and *Open Graph algorithms and Data structures Framework*.

> OGDF is a self-contained C++ library for graph algorithms, in particular for (but not restricted to) automatic graph drawing. It offers sophisticated algorithms and data structures to use within your own applications or scientific projects.

- [ogdf.uos.de](https://ogdf.uos.de/)
- [github.com/ogdf/ogdf](https://github.com/ogdf/ogdf)
- https://ogdf.github.io/doc/ogdf/index.html

# d3-hwschematic

Regarding minimization of crossings, "*see [On the Automatic Layout of Data Flow Diagrams](http://rtsys.informatik.uni-kiel.de/%7Ebiblio/downloads/theses/msp-dt.pdf) by Miro Spönemann, referenced in [ghdl/ghdl#111:363395770](https://github.com/ghdl/ghdl/issues/111#issuecomment-363395770) by @Nic30 (see [Nic30/d3-hwschematic](https://github.com/Nic30/d3-hwschematic)). See also [Nic30/d3-wave](https://github.com/Nic30/d3-wave) and [(RTL) Schematic view](https://github.com/eine/hwd-ide/wiki/%28RTL%29-Schematic-view)*" (from SymbiFlow/ideas/issues/41).

**Comment by TheDuriel** [comment]
I'm fully in support of adding a library with a compatible license, and thus giving graphedit a much needed refresh.

(And yeah, the list of people pinged is rather spot on)

**Comment by fire** [comment]
Please see if the implementation of suits your needs https://github.com/godotengine/godot-proposals/issues/1253

**Comment by fire** [comment]
Fixed by: https://github.com/godotengine/godot-proposals/issues/1253
