### ISSUE TITLE
Add presets to Modify Editor Features to ease the learning of Godot

### ISSUE THREAD

**Issue by mount2010** [godotengine/godot-proposals#1403]
**Describe the project you are working on:**
This proposal is general and is not limited to a certain project.

**Describe the problem or limitation you are having in your project:**
This proposal relates to learning Godot. As a beginner, especially if one intends to learn by doing (instead of following tutorials or guides step-by-step), one may be confused about the amount of features and nodes that Godot offers. To illustrate, imagine being a new user who has just downloaded Godot and started a project. Adding a new node may be daunting because you are immediately faced with the dozens of nodes that Godot offers for specific functionality. The intent of this proposal is not to remove features or to limit what one can do with Godot, but instead to offer "hints" to _beginners_ who want to learn Godot by using the software. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Currently, one can use the Editor -> Modify Editor Features interface to change what can be seen in the editor. This is useful, but it does not offer presets. I propose adding, for example, a "basic" or "beginner" preset that has more limited features in order to help new users learn how to use the engine. This preset will indicate to beginners that "hey, you may want to try out, and figure out, these features before moving on with the rest of the engine". This is a clear pathway for new users.

I do not claim to understand all the implications of separating "basic" or "beginner" features from "advanced" features, which is why I am making this proposal, to invite debate on this issue. I would like to note that I am myself a new user, and I have been confused about the amount of nodes I seem to have to learn and get familiar with, especially with the GUI-based editor being at the forefront of Godot, and no nodes seeming to work the same way in this GUI. As I am a new user, I cannot claim to know which nodes are _most likely_ used in a majority of projects. However, what I am thinking of, for example, is to place the User Interface nodes, as well as things that can encourage one to begin to design at the forefront, while nodes less important to newcomers such as the 3D nodes or nodes relevant to multiplayer may not be as important to show.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
While this is an abstract proposal, if beginner presets are added, one can show a pop-up on the first launch of the Project Editor:
![mockup](https://user-images.githubusercontent.com/13136505/90981608-9c64e580-e594-11ea-9449-64c7a15e0388.png)

Again, I do not claim to know the implications of such a pop-up. I am not a UX designer by any means. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A
**Is there a reason why this should be core and not an add-on in the asset library?:**
N/A

**Comment by TheDuriel** [comment]
How does one even quantify the features which would be shown/hidden?

I suspect no matter what features are visible/hidden, most users will very quickly run into something that forces them to show everything anyways.

**Comment by Calinou** [comment]
Closing due to lack of support. Determining what should be enabled in "basic" mode and what should be left out is an incredibly complex task in itself, and is likely not worth the trouble (and moving development resources away from more pressing 
topics).

**Comment by mount2010** [comment]
If I remember correctly, my original issue was that there were setting presets in Modify Editor Features that users could make, but no default presets to use (i.e. you'd have to make them yourself). I discussed this in the Godot Discord and wrote this issue out of impulse.
