### ISSUE TITLE
A way for Godot 4 to support god-rays . . 

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1406]
**Describe the project you are working on:**
Tomb Raider game, climbing, action . . .

**Describe the problem or limitation you are having in your project:**
Tbh, the demos I've seen of SDFGI, and volumetric fog blow my mind, it looks AAA ( +), I was hoping we might get support for ' god rays ', as well, since it creates a neat aesthetic, for many games, it adds atmosphere, ' style ' . . Not sure if it should be added as a setting, under light, or in environment, but with that, Godot will be really cool, for all . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I just love seeing god rays, dancing in the air, shafts, of pure light, so nice . . Hope it will be added, as the last thing I could ask for, in Godot 4.0, in a PBR based way, if possible, ie. it fits a physical / chemical work-flow, scientific, IF possible . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Add an appropriate setting, for enabling ' god rays ', a few parameters, to tweak it, hopefully physically based, if that is possible . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I have got no idea, how to do that, it looks nice, really cool . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, would be nice to just toggle it, and one gets some ' basic ', o-k quality god rays <3 Thanks . . . .

**Comment by Calinou** [comment]
The volumetric lighting implementation currently in the `master` branch already supports god rays, as long as your scene has a DirectionalLight.

**Comment by jasperbrooks79** [comment]
Ok, sorry, it's a bit hard to see, in the example . . Why I think having a ' demo ' scene, with some nature, or trees, might be a good way, I saw the video 3 times, and I THINK I can almost see it, but not sure . . :( :( . . .

A forest, jungle, or so scene might be better, tbh I can barely see it, :( :( . . .

That said, the new demo level is really good, really sparkles, I think, good choice, very relevant, to game makers <3 . .

**Comment by Calinou** [comment]
Nothing prevents you from increasing the Density property in volumetric fog to make god rays more noticeable. That said, it's usually better not to make effects overblown to not annoy players :slightly_smiling_face:

**Comment by jasperbrooks79** [comment]
thank you, I'm so excited for Godot 4.0, it has all the things I could ever want, as a new indie dev, for years . . . <3
