### ISSUE TITLE
slerp, lerp suggestions

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#141]
I am working on a spaceship game in which 4 players battle each other to the death.
right now I am having trouble trouble with Vector2.slerp throwing not normalized errors due to 3.1.1 slerp bug. however having this trouble made me comes up with this suggestion to make interpolation easier to understand and use.

I have a collection of suggestions regarding lerp and slerp..

1. Vector2's and Vector3's linear_interpolate should be made obsolete and should be renamed to lerp.
**do I need it:** no but it would be more clear for users
**will I use it often:** yes

2. slerp should be added to the core math library along with lerp
**do I need it:** yes it is very helpful.
**will I use it often** yes

3. all slerp and lerp functions should take a value from 0-n instead of 0-1 or just 1. 
see here https://github.com/godotengine/godot/issues/32692
**do I need it:** no.  but right now lerp and slerp are using two different excepted ranges and we should stick to one of them. and this suggestion covers more use cases.
**will I use it often:** yes

my proposal will allow a more constant syntax like so.. (notice that you are not restricted to a normalized value);
```
var v1 = Vector2().slerp(Vector2(4,0), 0.5);
var v2 = Vector2(). lerp(Vector2(4,0), 0.5);
var v3 = Vector3().slerp(Vector2(4,0), 0.5);
var v4 = Vector3(). lerp(Vector2(4,0), 0.5);
var f1 = slerp(0, 4, 0.5);
var f2 =  lerp(0, 4, 0.5);
```

I would think something like slerp would be done like so..
```
Vector2 slerp(Vector2 src, Vector2  dst, float speed)
{
    float_len = src.length; //save this and..
    return src.normalize().__internal_slerp(dst.normalize(), speed) * _len; //apply it at the end
}
```

this would be used alot I guarantee it. using a constant naming convention for interpolation and allowing both to take values other then normalized vectors will make it more user friendly and easier to use.

it would be in the core library because it basically already is.
this is just a suggestion to make them more convenient to use.

**Comment by clayjohn** [comment]
Please follow the provided template or this issue will have to be closed. More info on the rules can be found on this repo's main page. https://github.com/godotengine/godot-proposals

**Comment by aaronfranke** [comment]
1, 2: https://github.com/godotengine/godot/pull/20371 I implemented this last year, it will be in Godot 4.0.

3: Unlikely, it would hurt performance when it's easy to just add `.normalized()`.

**Comment by Shadowblitz16** [comment]
@clayjohn I edited my post

**Comment by clayjohn** [comment]
Thanks for trying. I know it's tough to apply a template after having already made a post. But I have to insist that you use the template that we provide. It is found here for convenience. https://github.com/godotengine/godot-proposals/blob/master/.github/ISSUE_TEMPLATE/feature---enhacement-proposal.md

**Comment by Shadowblitz16** [comment]
ok edited it again

**Comment by MCrafterzz** [comment]
Lerp and sleep using different ranges sounds confusing. Why not just make both 0-1?

**Comment by Shadowblitz16** [comment]
@MCrafterzz  because it would be easier for users to use a lerp and slerp function that accepts any range

**Comment by clayjohn** [comment]
Currently lerp and slerp accept ranges from 0-1. To convert from 0-n, just divide by n. I don't see a reason to slow down those basic functions to accomodate such a specific use-case. I've never seen another API that allows you to lerp between 0-n either.

**Comment by Shadowblitz16** [comment]
@clayjohn Vector2.linear_interpolate() takes values 0-n.
that's why I was suggesting it.

allowing all function to take 0-n would just fix the consistency without breaking existing projects.

changing Vector2.linear_interpolate() to only take 0-1 would require more work to people to adapt to then renaming it to lerp and allowing all interpolate functions to take 0-n.

**Comment by clayjohn** [comment]
Linear interpolate takes values from 0-1 http://docs.godotengine.org/en/latest/classes/class_vector2.html#class-vector2-method-linear-interpolate

**Comment by Shadowblitz16** [comment]
I have used it and it works with 0-n as the b vector

**Comment by clayjohn** [comment]
I seem to have misunderstood what you want. 

``slerp`` requires normalized coordinates because it is a spherical interpolation. I.e it is an interpolation over a sphere of radius ``1`` (in 2D this would be a circle instead of a sphere). 

Lets look over your three suggestions again:

1. Already implemented (https://github.com/godotengine/godot/pull/20371)
2. ``slerp`` is already built in http://docs.godotengine.org/en/latest/classes/class_vector2.html#class-vector2-method-slerp
3. Both ``lerp`` and ``slerp`` interpolate between ``a`` and ``b`` based on ``t`` when ``t`` is in range ``0-1``. ``lerp`` can take vectors of any shape, but ``slerp`` requires that the vector be normalized. This is necessary because spherical interpolations happen over the surface of a sphere. This isn't an implementation dependent thing, its just what a ``slerp`` is (see https://en.wikipedia.org/wiki/Slerp).

**Comment by Shadowblitz16** [comment]
@clayjohn 
1. thats good
2. slerp not Vector2.slerp() or vecor3().slerp()
3. why does it need to be a radius of 1? a sphere can be any size. just multiply it by the value you pass.

**Comment by clayjohn** [comment]
You just provided a reason not to add it in core. It's a one line addition for those who want it, but it would slow down the internal slerp function. So it shouldn't be forced on all users.

**Comment by Shadowblitz16** [comment]
it wouldn't slow it down that much. and again its better then the two alternatives..
1. leaving confusing lerp and slerp differences.
2. breaking peoples code to enforce 0-1.

and again if GDScript can be optimized to run faster the gain will outweigh the loss.
its literally one more line and if performance is a issue then we should have a optional bool which called quick for both lerp and slerp which clamps the values to 1.

it all this is too much then we might as well have the following signature..
```
var v1 = Vector2().slerp(0.5);
var v2 = Vector2(). lerp(0.5);
var v3 = Vector3().slerp(0.5);
var v4 = Vector3(). lerp(0.5);
var f1 = slerp(0.5);
var f2 =  lerp(0.5);
``` 
since there is literally no point in having a second parameter if we can't use ranges other then 1

**Comment by clayjohn** [comment]
I think you really misunderstand how lerp and slerp work. Please read my above messages.

**Comment by Shadowblitz16** [comment]
I know what lerp and slerp are I have used them before. the previous post was a bad example I was tired.

just because they were made to work with a range of 0-1 doesn't mean they can't work with a range of 0-n.

the whole point is to interpolate between two values at a percentage between 0-1. 
not interpolate between 0-1 at a percentage between 0-1. 
slerp is just a way of saying lerp spherically instead of linearly. 
it doesn't have anything to do with disallowing values to be pass as 0-1.

speed isn't a issue because its literally written in c++ and people are going to multiply and divide it anyways before they pass it in to lerp or slerp so why not just do it in the function?

**Comment by aaronfranke** [comment]
> speed isn't a issue because its literally written in c++

Unfortunately, C++ is not magic. Performance trade-offs are always relevant.

> people are going to multiply and divide it anyways

If this is a commonly needed feature, that would certainly be a reason for Godot to add it. You can either wait for users to comment they need this functionality often, or you can look through open-source Godot projects to find where this is done often. That would be evidence for whether or not it's a commonly needed feature.

**Comment by Calinou** [comment]
I'll close this due to lack of support (see the performance concerns above). The Vector2/Vector3 `linear_interpolate()` functions will probably be renamed to `lerp()` in 4.0.
