### ISSUE TITLE
How to change uint64 into byte array with big endian and change back

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot-proposals#1410]
I wan't to make a tcp package like this:
how to change uint64 into byte array with big endian
![企业微信截图_1598337172694](https://user-images.githubusercontent.com/29348971/91133059-f1f9d900-e6df-11ea-9cba-0daea61774c1.png)

**Comment by groud** [comment]
Sorry, this is not the place to ask questions about how to use the engine, but to ask for new features.
Use the [other community channels](https://godotengine.org/community) instead.
