### ISSUE TITLE
Expose the `poll()` function in StreamPeerTCP

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot-proposals#1415]
**Describe the project you are working on:**
I'm writing a tcp client model to connect to the server writted in golang.

**Describe the problem or limitation you are having in your project:**
When writing a low-level socket script,there are two functions to recv data:
1.StreamPeerTcp.get_data(1024) will block,there is a while loop in c++ code read() function.So,this will waste cpu and cause message delay if the data if short then 1024
2.StreamPeerTcp.get_partial_data(1024) can solve the message delay problem,but if there's no data,the function will return too.So if there is no data,the script will loop too,cpu is wasting.
We need a way to know if there has data to be read

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In c++ code,class StreamPeerTcp,there is a function called poll(),this can be used to notice if there has data to read

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Please export this function to gdscript

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This is a main function to use in all online games
libevent/libev/libuv all these library are based on this

**Is there a reason why this should be core and not an add-on in the asset library?:**
Normal tcp socket is write in this way,on windows is iocp,on linux is epoll

**Comment by groud** [comment]
We have an issue template, please fill it in, it's mandatory.
I'll reopen when this is done.

**Comment by chenjie199234** [comment]
@groud i updated the issue

**Comment by jonbonazza** [comment]
@chenjie199234 can you please elaborate a bit more on what you are ultimately trying to accomplish? I'm not sure I understand the core problem.

**Comment by chenjie199234** [comment]
@jonbonazza 
there has no functions to know if there has data to read in GDScript
so user have to loop to check if there has data to read,this will waste cpu
so need to export the readable and writable to the GDScript

**Comment by jonbonazza** [comment]
So the `poll` function is essentially just

```
if has_data:
    var data = read()
    return data
return null
```

It doesnt just tell you if there is data, it also reads the data off the buffer, after which you can't read it again. 

I do think poll should probsbly be exposed, but im not understanding how it solves this particular problem.

**Comment by chenjie199234** [comment]
@jonbonazza i didn't understand what you said.
i want a function like ```epoll``` or ```poll```in linux
so that i can avoid the useless loop to read data
does the ```poll``` function in ```StreamPeerTcp``` works like that?if so export it
