### ISSUE TITLE
Specify exact values for Curve Control Points in the Inspector

### ISSUE THREAD

**Issue by Inferno630** [godotengine/godot-proposals#1418]
**Describe the project you are working on:**
This is a general-purpose issue

**Describe the problem or limitation you are having in your project:**
Curves (whether Curve, Curve2D, or Curve3D) do not allow exact values to be specified for points or control points in the editor. This makes dealing with curves in any sort of precise manner nearly impossible. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Expose all curves' points and control points to the inspector (using the standard vector editor setup). This would allow these values to be changed with precision.

Without this functionality, Curves in general are substantially less useful than they should be.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![CurveEditMockup](https://user-images.githubusercontent.com/3170894/91365997-25179780-e7c8-11ea-8c3d-c82409cfe443.png)
Mockup for a Curve2D

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be worked around at runtime using the set_point_position(), set_point_in(), and set_point_out() methods, but cannot be worked around in the editor.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It modifies the inspector, and makes curves usable for more complex and precise tasks. The fact that it is not already built into the engine is very odd.

**Comment by Calinou** [comment]
You can hold <kbd>Ctrl</kbd> or <kbd>Ctrl + Shift</kbd> to snap coordinates in the curve editor.

**Comment by Inferno630** [comment]
> You can hold Ctrl or Ctrl + Shift to snap points to specific increments in the curve editor. It's not perfect, but it's a start.
> 
> Either way, this is a duplicate of #48 so I'll close it.

Ctrl and Ctrl + Shift only snap the point positions, they have no impact on manipulating the tangent lines. 

I saw #48, but it only specified for the Curve resource, not including Curve2D or Curve3D (which are all completely separate things in the documentation despite their similarities, as far as I can tell). But I suppose I'll just add a comment in #48. Apologies for the duplication.
