### ISSUE TITLE
Give projects a kickstart by including a placeholder asset library! (Placeholder textures, audio, and maybe models/meshes)

### ISSUE THREAD

**Issue by CenTdemeern1** [godotengine/godot-proposals#1419]
(I haven't used the assetlib much so please excuse any errors)

**Describe the project you are working on:**
N/A

**Describe the problem or limitation you are having in your project:**
It's hard to start out making a new project without assets.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Include a placeholder asset library!
Like, something like the existing assetlib, but you get placeholder textures, audio, and other assets there.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I imagine it'd be a tab within the assetlib section specifically for assets.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, because my idea is that this would literally just be integrated into the same system as the assetlib.

**Comment by Jummit** [comment]
There could also be new categories on the asset library for sounds, textures and models. Then placeholders could be uploaded in that category, and could be easily browsed in-editor.

**Comment by Calinou** [comment]
Note that creating the assets themselves is beyond the scope of the Godot project and should be handled by third parties.

**Comment by Calinou** [comment]
Closing, as this should be handled by third parties – in other words, anyone reading this :slightly_smiling_face: 

See https://godotengine.org/asset-library/asset?category=&godot_version=&sort=updated&filter=kenney for an example.
