### ISSUE TITLE
Access to full screen normal texture in shader

### ISSUE THREAD

**Issue by narcissawright** [godotengine/godot-proposals#1421]
**Describe the project you are working on:**
3D action/platformer with stylized character art.

**Describe the problem or limitation you are having in your project:**
I would like to achieve clean line art in 3D. This problem has been solved in other game engines as seen in Unreal and Unity, using full screen depth+normal texture. It is difficult to do this in Godot as things are now. I am hopeful that v4.0 and Vulkan will allow this possibility.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Having access to both the depth and screen normals in a shader allows you to create excellent lines. This method was used in [Manifold Garden](https://www.youtube.com/watch?v=jZ_yxZwAoCg) by William Chyr to create impressive visuals. This method can also be applied to stylized characters, with great results, as seen [here](https://youtu.be/DXv3YyL9H3c?t=375) in this work from Daniel Kreuter.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A breakdown of the method can be seen [here](https://halisavakis.com/my-take-on-shaders-edge-detection-image-effect/), created in Unity engine. A similar method can be done in Unreal engine.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This method is appearing in more places, as clean linework is a necessity for stylized characters. For Godot, the [Godot Shader Secrets](https://github.com/GDQuest/godot-shaders) project from GDQuest does include an interesting method for this (Pixel Perfect Outline). It's probably the best method available right now in Godot. I still would like to play around with full-screen normal + depth though.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Stylized rendering (NPR) is becoming more commonplace, and as it does, creators want more control over the render pipeline. Having the ability to do this directly would be great. I am hopeful that this is possible with Godot 4.0 and Vulkan.

**Comment by clayjohn** [comment]
This has already been added in master! :) 

You can access it in the ``.xyz`` channels of ``NORMAL_ROUGHNESS_TEXTURE``
