### ISSUE TITLE
Add a method to check if vibration is supported on Android

### ISSUE THREAD

**Issue by Zottelchen** [godotengine/godot-proposals#1427]
**Describe the project you are working on:** 

A simple Android game which uses vibration.

**Describe the problem or limitation you are having in your project:** 

Vibration is not available on all devices (e.g. Kindle Fire).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** 

Either there would be a function to check if the device can actually vibrate (something like OS.has_feature("vibrate")) or the Input.vibrate_handheld should return an error (currently void).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** 

Variant 1:

```gdscript
if OS.has_feature("vibrate"):
     Input.vibrate_handheld()
```

Variant 2:

```gdscript
 if ERR == Input.vibrate_handheld():
    print("Vibration failed")
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** 

Unless I missed something, this probably has to be changed in Godot_Java?

**Is there a reason why this should be core and not an add-on in the asset library?:** 

Same reason as above.

**Comment by Calinou** [comment]
>     if OS.has_feature("vibrate"):
>     Input.vibrate_handheld()

We only use feature-tags for features whose presence is determined at compile-time, not run-time. A method is more suited for this instead.

**Comment by m4gr3d** [comment]
@Zottelchen The typical pattern is to send the vibration request and if the device doesn't support it, nothing happens. Is there a reason / use-case that pattern doesn't work for your game?

**Comment by Robert-K** [comment]
@m4gr3d I'm providing input feedback to the player using vibration. It feels much better than using audio, as it's super low latency.
However, if the vibration is not supported or disabled system-wide, I'd like to fall back to audio.
As far as I can tell, there's no way to make that distinction at the moment.

**Comment by m4gr3d** [comment]
> @m4gr3d I'm providing input feedback to the player using vibration. It feels much better than using audio, as it's super low latency. However, if the vibration is not supported or disabled system-wide, I'd like to fall back to audio. As far as I can tell, there's no way to make that distinction at the moment.

@Robert-K Take a look at https://github.com/godotengine/godot/pull/97500.
It should provide the functionality you're looking for (targeted for Godot 4.4).
