### ISSUE TITLE
Add a physically based wind simulator . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1435]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
Right now, we're getting some amazing PBR, or ' science ' based features, like the new sky, so on . . And, sdfgi, volumetric fog, many improvements . . . I would suggest Godot gets a wind simulation system, where one can add ' objects ', or meshes to that layer, so it creates a wind system, based on physics, or approximations . . . All the objects needed to be affected by a global, procedural wind simulation, would be added, to the ' wind ' layer, or so . . Settings would include from light breeze, to more chaotic stuff, gusts, random factors, other stuff . . This would help games, that need this, to easily create some basic cases, more could be added later, to make it more realistic . . All the objects in the ' wind cull mask ', would be affected by a global wind simulation, with a number, of settings . . . This would help create planes of waving grass, from light breeze, to maybe storms, procedurally generated, based, in physics . . . Even if it was only applied to transparent grass objects, to begin with, it could create some amazing effects, for most users . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It might sound silly, but having an optimized, global, or perhaps restricted wind system, to a certain volume, if it was based in science, physics, could do amazing things, for many games . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Basically, in environment settings, have a new mode, called ' wind ', all the stuff in that cull mask, is affected by physics, optimized, to make things like fields, of wheat, random breezes . . .

![2020-08-31 0505](https://user-images.githubusercontent.com/61069740/91679090-9bf5bd00-eb47-11ea-9bd9-c738db306a4b.gif)

Having this feature, would help Godot better simulate real world effects, and should be user-friendly, and customizable . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Having it as in-built feature, would mean more games could benefit from it, it should be fairly small, or scalable, so it can be run, at least cost, to FPS . . <3

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's something that helps simulate worlds, or physics . . Game engines are moving towards this, more and more things a PBR, physics based, having an approximation, based in science, of wind, would be nice . .

**Comment by jasperbrooks79** [comment]
Also, both stylized and realistic games could use this, if it had the right settings or, modes . . <3

**Comment by Calinou** [comment]
Wind in grass and trees is generally simulated by using some kind of noise function in a shader. I don't think this needs to be a built-in feature as long as we have some way to introduce noise functions in shaders (which is already the case).

**Comment by jasperbrooks79** [comment]
Ok, I was not sure, nice to have procedural wind engine, that was optimized, at run -time . . . .

**Comment by RaTcHeT302** [comment]
it would be nice but i think ur best option is to just animate the grass to sway by hand

**Comment by Tooniis** [comment]
Other than grass, this would be useful for all other kinds of physics bodies. You could have a drag factor in rigid bodies, or perhaps multiple ones for each direction which would then be interpolated, and this factor would be used to calculate a force to apply to them to simulate wind.

**Comment by jasperbrooks79** [comment]
I know this might be a noob thing, to ask . . But, since we're getting like ' sky ' simulator, and PBR materials also ' imitate ' physics, and sdfgi mimics real light bounces, that one could maybe make a sort of, ' wind ' simulator, that just works, or so, where one can set various complexity settings . . .

But, I'm noob, not sure if it's best way, but once it was done, one could create all sorts of weather, very easily, and it'd be physically based, and would give very nice, out-of-box results, same way PBR materials, volumetric fog, so on, effectively imitates real world systems or, laws, of science, or so . .

Not sure, if it's really efficient, but since it could be turned off, it would not be performance demanding, and one could set ' detail ' of it, with various ' real ' world parameters, same as for fog, new ' sky ', other stuff . . . Having such a setting, or feature, that could create various kinds of ' pretty ', or advanced physics-based wind-simulations, or approximations, might really make games look ' next - gen ', on Godot, more than already do, and it'd fit in the ' box ', of adding science-correct simulation, in general, in 3D software, or games . . . <3

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2591, which has more detail about the feature to implement.
