### ISSUE TITLE
Increase the resolution of the default `icon.png`

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1436]
**Describe the project you are working on:** I've noticed the lack of resolution in a variety of projects.

**Describe the problem or limitation you are having in your project:**

Many people use `icon.png` as a placeholder, or even a part of their game. It's even [become a meme](https://www.youtube.com/watch?v=VJMb88-d-js).

However, `icon.png` has a fairly low resolution by default, it's only 64x64 pixels:

![icon](https://user-images.githubusercontent.com/1646875/91680009-eb23f980-eb17-11ea-85a8-514975d4ca5f.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

I propose increasing it to 128x128 pixels. Here's a 128x128 version compressed with `oxipng`:

![icon](https://user-images.githubusercontent.com/1646875/91680049-0b53b880-eb18-11ea-84f0-656e743e3a1c.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Godot will place [this](https://user-images.githubusercontent.com/1646875/91680049-0b53b880-eb18-11ea-84f0-656e743e3a1c.png) into the project instead of the existing `icon.png`.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This problem is very easy to work around, but this will be used very often (by anyone who creates a project, nearly 100% of users).

**Is there a reason why this should be core and not an add-on in the asset library?:**

`icon.png` is a core feature.

**Comment by groud** [comment]
If we consider icon.png only as a placeholder, I find that 64x64 is a good size. In 2D, it fits ok in high res game while still being usable for pixel art games, where the resolution might be smaller.

**Comment by Xrayez** [comment]
> In 2D, it fits ok in high res game while still being usable for pixel art games, where the resolution might be smaller.

There's even a related proposal for this: #457. 😃

**Comment by Calinou** [comment]
This can be fixed in https://github.com/godotengine/godot/pull/41430 by forcing a scale of 2.0 instead of 1.0.

**Comment by aaronfranke** [comment]
One thing to consider is that with `oxipng` we can get an PNG which is 40% smaller. Since we should use the same icon across all devices (since it's saved and it would be confusing for different computers to generate different projects), I think it would make sense to store the optimized PNG file inside of Godot instead of generating it each time.

**Comment by Xrayez** [comment]
Why not just copy `icon.svg` instead of generating `icon.png`? Should be more lightweight. In both cases, these are imported anyway.

**Comment by golddotasksquestions** [comment]
Instead of either a the 64x64 or 128x128 rasterized version, why not generate the project with the `icon.svg` instead of `icon.png`?
(sorry @Xrayez if that's what you have already been saying, I was not sure I understood what you were trying to say)

The `icon.svg` would generate the same 64x64 texture like the icon.png, and if the user wants a larger resolution on their icon, they can reimport it with svg/scale 2 to get a perfect 128x128 or anything bigger. Scaling down the icon resolution to work as placeholder for pixelart games with 32x32 or 16x16 tiles would be just as easy.

**Comment by Calinou** [comment]
@golddotasksquestions That could be done, but at the default scale, the icon will still look blurry in the Project Manager on hiDPI displays. This is why I would prefer to replace the icon with a 128×128 PNG instead.

**Comment by golddotasksquestions** [comment]
@Calinou Currently the artboard/canvas dimensions of the icon.svg is set to 64x64 by whoever made it. Since it's vector art, you can change that to whatever you want, save it again, and now the default resolution of the icon.svg will the that new value. Case in point:

[DefaultProjectIcon_128x128.zip](https://github.com/godotengine/godot-proposals/files/5219255/DefaultProjectIcon_128x128.zip)

Now the Project Manager icon on hiDPI should not appear blurry, because the texture Godot generates from the icon.svg is 128x128 by default.

However this still breaks compatibility with all other default values in Godot that currently work really well with the default icon. It also breaks a lot of tutorials. Given that there is only a much smaller percentage of users using the Godot Project Manager on hiDPI displays, I would consider another solution to fix the ability to perceive the low resolution of the icon Project Manager icon in hiDPI screens (which is, let's face it, only really an aesthetic issue for Macbook users). For exported projects which are in fact much more commonly viewed on high dpi harware such as mobile devices, Godot users will create their own icons in larger resolution anyway.

**Comment by aaronfranke** [comment]
To my surprise, the SVG file (5.0 KiB) is larger than the existing PNG file (3.2 KiB) and the compressed 128x128 PNG file (4.3 KiB). While there are still benefits to SVG files, a bigger file is a downside, Godot only imports a single size anyway, and PNG is a more universal format. This is worth a discussion but I'm not sure it would be worth it to go SVG.

**Comment by Calinou** [comment]
@aaronfranke It's not like a 0.7 KB file size difference is the end of the world. :stuck_out_tongue:

**Comment by aaronfranke** [comment]
@Calinou Yes, but a 116 byte difference is according to some users :stuck_out_tongue:

**Comment by Calinou** [comment]
Note that to implement this, we can't just force the `DefaultProjectIcon` icon scale to 2.0 or save the SVG as 128×128. Otherwise, all project icons will display twice as large. We'll also need to modify `project_manager.cpp` to solve this.

While making changes in `project_managere.cpp`, it would be good to avoid resizing the default project icon every time it has to be displayed in the project manager, as this is a relatively slow operation.

**Comment by lyuma** [comment]
Here, I did some manual editing and quantized the positions a bit and got the icon.svg down to 3650 bytes. (1769 if compressed in a .zip)

While the uncompressed size still exceeds the 3305 byte icon.png by 345 bytes, the compressed size of 1769 is way smaller (remember, PNG is already deflated, so cannot be compressed further). I think this is a win.
If necessary, I'm sure some additional quantization could be performed which won't be visible unless the icon size is above 512 pixels.

(Also, about the scale, I changed the document width and height to 64 and added a transform="scale(.5)" to match. Those two numbers can be tweaked to control the resolution.)

```xml
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" version="1.1">
<g transform="scale(.5)">
<g transform="translate(32,32)"><path fill="#355570" d="M-16-32c-8.86,0-16,7.13-16,15.99v95.98c0,8.86,7.13,15.99,16,15.99h96c8.86,0,16-7.13,16-15.99v-95.98C96-24.86,88.86-32,80-32H-16z"/><path
fill-opacity=".191" d="M-16-32c-8.86,0-16,7.13-16,15.99v95.98c0,8.86,7.13,15.99,16,15.99h96c8.86,0,16-7.13,16-15.99v-95.98C96-24.86,88.86-32,80-32H-16zM-16-28h96c6.64,0,12,5.35,12,11.99v95.98c0,6.64-5.35,11.99-12,11.99H-16c-6.64,0-12-5.35-12-11.99v-95.98C-28-22.65-22.64-28-16-28z"/>
<g><path fill="#FFFFFF" d="m32.03,78.97h-.02c-27.13-.09-43.96-9.43-43.96-24.37l-.02-3.37.02-8.09V24.33c-1.82-2.37-3.54-4.89-5.25-7.65-.58-.94-.59-2.13-.03-3.09,2.22-3.77,5.08-7.53
8.75-11.48.9-.97,2.35-1.23,3.54-.63,2.21,1.11,4.44,2.37,6.65,3.74C2.37,4.65
3.05,4.14,3.71,3.63L4.43,3.08C5.46,2.25,6.56,1.58,7.63.93,7.33-1.75,7.15-4.53
7.07-7.66,7.04-8.83,7.69-9.9,8.72-10.42c3.8-1.91,8.09-3.38,13.13-4.5,1.25-.27
2.56.27,3.22,1.39,1.31,2.2,2.6,4.64,3.84,7.27.93-.08,1.91-.12,2.99-.14
1.14.01,2.17.06,3.13.14,1.24-2.63,2.53-5.07,3.84-7.27.66-1.11,1.96-1.67
3.22-1.39,5.03,1.12,9.33,2.59,13.13,4.5,1.03.52,1.68,1.59,1.65,2.75-.08,3.13-.26,5.91-.56,8.60
1.07.64,2.17,1.32,3.25,2.18l.60.46c.68.52,1.38,1.05,2.07,1.62,2.19-1.37,4.42-2.62
6.65-3.74,1.19-.59,2.64-.33,3.54.63,3.67,3.95,6.53,7.71,8.75,11.48.56.95.54,2.15-.03,3.09-1.71,2.77-3.44,5.29-5.25,7.65v21.63c0,.07.0.14.0.21l.02,4.99c0,1-.01,2.04-.01,2.73l0,.67c0,14.93-16.82,24.27-43.91,24.37z"/></g></g><g transform="matrix(.1005,0,0,.1005,76.51,66.36)">
<path fill="#478CBF" d="M-531.75-110.54v245.75c.45,0,.90.03,1.35.07l150.66,14.52c7.89.75,14.1,7.1,14.63,15l4.64,66.5l131.42,9.36l9-61.37c1.17-7.96,7.99-13.86,16.05-13.86h158.9c8,0,14.8,5.9,16,13.8l9,61.3l131.4-9.3l4.6-66.5c.58-7.9,6.7-14.2,14.6-15.0l150.6-14.5c.44-.03.8-.07,1.3-.07v-19.5l.05-.02v-226.1h.56c19.9-25.4,38.4-52.3,56.1-80.9c-23.5-40-52.3-75.8-83.1-108.9c-28.5,14.3-56.3,30.6-82.5,48c-13.1-13-27.8-23.6-42.4-34.8c-14.2-11.4-30.3-19.8-45.5-29.6c4.5-33.7,6.7-67,7.6-101.7c-39.3-19.7-81.2-32.9-123.6-42.3c-16.9,28.4-32.4,59.2-45.8,89.4c-16-2.6-32-3.6-48.1-3.8
v-.01c-.11,0-.21.0-.31.0c-.1,0-.2-.01-.31-.01v.01c-16.1.19-32.1,1.1-48.1,3.8c-13.4-30.1-28.9-60.9-45.9-89.4c-42.4,9.4-84.3,22.5-123.6,42.3c.9,34.7,3.1,67.9,7.6,101.7c-15.2,9.7-31.3,18.1-45.5,29.6c-14.4,11.1-29.2,21.8-42.4,34.8c-26.2-17.3-53.9-33.6-82.5-48c-30.8,33.1-59.6,68.9-83.1,108.9c17.7,28.6,36.1,55.4,56.1,80.9H-531.7z"/>
<path fill="#478CBF" d="M147.6,180.7l-4.6,66.8c-.58,8-6.9,14.4-15,15.0l-160.4,11.4c-.40.0-.79.0-1.1.03c-7.9,0-14.8-5.8-16-13.8l-9.1-62.4h-130.9l-9.1,62.4c-1.2,8.3-8.7,14.4-17.2,13.8l-160.4-11.4c-8-.58-14.4-6.9-15-15.0l-4.6-66.8l-135.4-13.0c.05,14.5.24,30.5.24,33.6c0,143.1,181.5,211.8,407,212.6h.55c225.5-.79,406.9-69.5,406.9-212.6c0-3.2.19-19.1.25-33.6L147.6,180.7z"/><path fill="#FFFFFF" d="M-247.2-10.7c0,50.1-40.6,90.7-90.8,90.7c-50.1,0-90.7-40.6-90.7-90.7c0-50.1,40.6-90.7,90.7-90.7C-287.8-101.5-247.2-60.9-247.2-10.7"/><path fill="#414042"
d="M-269-5.3c0,33.2-26.9,60.2-60.2,60.2c-33.2,0-60.2-26.9-60.2-60.2c0-33.2,26.9-60.2,60.2-60.2C-296-65.6-269-38.6-269-5.3"/><path fill="#FFFFFF" d="M-124.4,88.2c-16.1,0-29.2-11.8-29.2-26.5v-83.5c0-14.6,13-26.5,29.2-26.5c16.1,0,29.2,11.9,29.2,26.5V61.7C-95.2,76.4-108.3,88.2-124.4,88.2"/><path fill="#FFFFFF" d="M-1.6-10.7c0,50.1,40.6,90.7,90.8,90.7c50.1,0,90.7-40.6,90.7-90.7c0-50.1-40.6-90.7-90.7-90.7C38.9-101.5-1.6-60.9-1.6-10.7"/><path fill="#414042" d="M20.1-5.3c0,33.2,26.9,60.2,60.2,60.2c33.3,0,60.2-26.9,60.2-60.2c0-33.2-26.9-60.2-60.2-60.2C47.1-65.6,20.1-38.6,20.1-5.3"/></g></g>
</svg>
```

Comparison pictures:
Quantized icon.svg, 3650 bytes:
![Quantized svg render](https://user-images.githubusercontent.com/39946030/124266642-15ee2e00-daec-11eb-9f3a-d7f177db94a6.png)
Original DefaultProjectIcon_128x128.svg, 13907 bytes:
![Original icon.svg](https://user-images.githubusercontent.com/39946030/124266568-00790400-daec-11eb-8ba8-5d4bd009648d.png)

I also have a 4107 byte SVG with less quantization applied which might be a compromise if the artifacts are visible to anyone.

**Comment by insomniacUNDERSCORElemon** [comment]
> we can't just force the `DefaultProjectIcon` icon scale to 2.0 or save the SVG as 128×128. Otherwise, all project icons will display twice as large

Yeah, this is something that--at least at first glance--has bothered me. I don't think it logically makes sense for bigger assets to have a bigger scale unless you're working at a fixed scale (like 1:1 pixels) and even then it only makes sense for technical/aesthetic reasons (for instance I wouldn't expect a modern dev w/an HD painted-style game to change assets for a bigger or smaller object). 

Particularly seems annoying for drop-in replacements (like different-resolution texture packs), although maybe there are custom fixes for that (at least in cases where all art is a clean multiple of the original).
