### ISSUE TITLE
GodotSharp / TextEdit Control should use StringBuilder and should contain Methods for Inserting, Appending and Clearing Text

### ISSUE THREAD

**Issue by EternalColor** [godotengine/godot-proposals#1437]
**Describe the project you are working on:**
I am currently working on a Hacking Simulator. I am emulating a terminal and using the TextEdit.Text Property to display text to the user.

**Describe the problem or limitation you are having in your project:**
My code for adding text to my emulated terminal (TextEdit) looks like this
` terminalTextEdit.Text += TerminalTextPrinter.Print(PrintType.AuthorizationEnterUsername, this.account, true);`
Since String is an immutable type, every time i am adding text a new string will be generated.
Especially when im printing multiple lines  at once this will quickly eat up a lot of unnecessary space in memory.
I encountered this when i tried to emulate the "cat" command for a text file.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Use StringBuilder for Controls that have a Text Property. Also add Methods for Inserting Appending and Clearing Text, so we can manipulate the StringBuilder from outside.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
public class TextEdit
{
    private StringBuilder text;

    public void InsertText(int position, string text)
    {
       this.text.Insert(position, text);
    }

    public void AppendText(string text)
    {
       this.text.Append(text);
    }

    public void ClearText()
    {
       this.text.ClearText();
    }
}
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
If there would be a property or public method for "getting" a StringBuilder object which contains the text of the control,
it would be already enough

e.g 

```
public class TextEdit
{
   public StringBuilder StringBuilder { get; }
}
```

**Is there a reason why this should be core and not an add-on in the asset library?:**
It would lower the string manipulation memory resources used.

**Comment by KoBeWi** [comment]
PoolStringArray is basically a StringBuilder.

**Comment by EternalColor** [comment]
Great, thanks for pointing me to PoolStringArray. Ill try using that and setting the Text Property to the Value of the Array (entries concatinated)

So this can be closed.
