### ISSUE TITLE
Add sort methods to PoolStringArray

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1439]
**Describe the project you are working on:**
gdscript plugins

**Describe the problem or limitation you are having in your project:**
There is `sort()` in `Array`, can't find it in `PoolStringArray`

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
`sort()` method in `PoolStringArray` could sort the array alphabetically

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```gdscript
PoolStringArray(["b","a"]).sort()
-> a b
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think this is possible, but I do not find it logical since there's `sort()` methods in Arrays

**Is there a reason why this should be core and not an add-on in the asset library?:**
should be a core feature

**Comment by Calinou** [comment]
This was added to the `master` branch in https://github.com/godotengine/godot/pull/32144 already.
