### ISSUE TITLE
Make it possible to use a plain color as splash screen instead of an image

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#1445]
**Describe the project you are working on:**

The Godot editor :slightly_smiling_face: 

**Describe the problem or limitation you are having in your project:**

Since many games would rather have their own animated splash screen, they may want to replace it with a pure color instead (not necessarily black). Likewise, most non-game applications use a plain color while loading (see how Electron apps handle this).

Right now, you can create a 1×1 black image and use it as a splash screen, but it's not very convenient for prototype and gamejam projects. (For command-line aficionados, the ImageMagick command `convert -size 1x1 xc:"#000000" g.png` can be used to create a 1×1 black image.)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

There should be a way to define a custom splash screen color without having to create an image.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Add a project setting that defines a splash screen background color. This color can be used in addition to a custom splash image (to define a color outside the splash) or as a replacement for the default splash image. The default color would be `Color(0, 0, 0, 0)` (fully transparent black), which makes Godot use the default splash instead. (A fully transparent splash color will make Godot not override the default splash image if none is defined.)

Note that splash screen hasn't been reimplemented yet in the `master` branch, so this requires splash screen functionality to be reimplemented first.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, as splash screen drawing is handled by the engine itself.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Add-ons can't modify how the splash screen is drawn since it's drawn by the engine itself.

**Comment by JamesC01** [comment]
Just to let you know, I didn't figure out the null thing, it's just something I found while googling. Also, setting to null fills the screen with white, for whatever reason.

**Comment by JamesC01** [comment]
I agree, this is definitely a nicer solution. I can see you've been wanting this since 2016! Hopefully it'll get implemented soon, I can't imagine it would take a lot of work.
