### ISSUE TITLE
Godot Bluetooth 

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot-proposals#145]
**Describe the project you are working on:**

I'm working on a bluetooth Poker on android which i want to recode and ameliorate in gdscript and using godot compatibility to port it on ios and android.
[My actual App](https://play.google.com/store/apps/details?id=ch.disd.BlueToothPoker8) 

**Describe the problem or limitation you are having in your project:**

There's no godot plugin for bluetooth.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The game is a multiplayer one with bluetooth as communication process. 

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

The plugin or the feature should be able to handle bluetooth communication process that mean to be able to send and receive data to multiple connected devices.

**Describe implementation detail for your proposal (in code), if possible:**

There is an open source library for android which handles bluetooth communication and could be useful for the implementation. 
[Ketai.org ](Ketai.org) 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, don't think so.
**Is there a reason why this should be core and not an add-on in the asset library?:**

I think it's place is in the asset library.

**Comment by Calinou** [comment]
> I think it's place is in the asset library.

In this case, you don't need to open a proposal here :slightly_smiling_face:

**Comment by DisDoh** [comment]
Where should i post this proposal as module?

**Comment by Calinou** [comment]
@DisDoh You can post this proposal on one of the other [community channels](https://godotengine.org/community) instead. Still, remember that in the open source world, people generally work on what they want to work on (unless you pay them).

**Comment by willnationsdev** [comment]
@DisDoh You can post this on the unofficial [Godot Ideas](https://github.com/godot-extended-libraries/godot-ideas) repository. Also, there *is* a [Godot 2.1 Bluetooth module](https://github.com/favarete/GodotBluetooth). Don't know how well it works though. Either way, it could get you started on implementing a GDNative-based solution, or you could just update it to work with Godot 3.1 or 3.2 and then keep it as a module when you build your iOS/Android export.

**Comment by girng** [comment]
Perfect use case to show the power of GDNative?

**Comment by lentsius-bark** [comment]
mmm, bluetooth!

**Comment by DisDoh** [comment]
[https://github.com/DisDoh/GodotBluetooth](url)

Here it is the start of the GodotBluetooth module now connecting between two android devices and ability to send a string.
I would complete it day after day...

**Comment by lentsius-bark** [comment]
You're awesome!

**Comment by DisDoh** [comment]
[https://github.com/DisDoh/GodotBluetooth](url)

So for now it's able to communicate with more than one android device and to communicate with String Array and Int array.
So the next step is to be able to implement BLE(Bluetooth Low Energy) to be compatible with IOS...
If anyone willing to participate here is the discord group: [https://discord.gg/GrmdnR](url)

**Comment by Calinou** [comment]
I'll close this, as this feature can be provided by a third-party module as demonstrated above.
