### ISSUE TITLE
Trim whitespace from Scene/Node names

### ISSUE THREAD

**Issue by rawbitt** [godotengine/godot-proposals#1451]
Scenes and Nodes that include a space character at the begining or end of their name are not clearly visible, and could cause frustration when refrencing by name in a script. Spaces are particularily elusive at the end of a name in the Scene Tree, as there is no visual indiciation. I recommend Scene/Node names be trimmed of whitespace (I don't see the need to allow them).

I ran into this today using `get_node()`: I didn't realize I had accidentally included a space at the end of the Node's name and wasn't able to identify it until someone on Discord suggested I double check what exactly `Copy Node Path` showed.

Cheers!

**Comment by pycbouh** [comment]
For the sake of making quality proposals, please fill out the template provided when creating an issue.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
