### ISSUE TITLE
Better control over exported assets (such as selecting folders for exporting resources)

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#1454]
(this is somewhat revival of https://github.com/godotengine/godot/issues/23784, but for different purpose)

**Describe the project you are working on:**
A very big game™

**Describe the problem or limitation you are having in your project:**
As mentioned above, my game is very big. Now, I wanted to make a demo. The easiest way would be export it with a "demo" feature tag that makes parts of the game inaccessible. The problem is that with this we end up with a huge game file with little content (the fact that players could potentially bypass the demo limiter is another concern). Of course there's an option to choose assets that will be exported, but this has problems:
1. The most obvious one is that the amount of assets is huge and you have to check each of them one-by-one. This gives immense room for error, where you forgot to check an asset and suddenly your exported game breaks
2. The assets you include might be not constant. Often there are improvements to the game that might land in the demo (like QoL features or additional sound effects etc.). You have to remember to include them

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The most basic feature that would help with above is an ability to choose assets that will be excluded from export. Such list is usually constant (i.e. when you pick something once, you won't need to include it later) and there's less room for error, because it's easier to tell if something is never going to be used than if something might be used (e.g. as dependency). If you miss something from exclusion, you just end up with bigger export, but it won't affect the running game.

Another useful thing would be an option to tick directories instead of only single files. This would help a lot in mass-selecting assets.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![image](https://user-images.githubusercontent.com/2223172/92119032-8ad2d780-edf7-11ea-81c9-4cca2d425dbe.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's usability feature for editor export.

**Comment by KoBeWi** [comment]
After doing https://github.com/godotengine/godot/pull/43538 and https://github.com/godotengine/godot/pull/43550 I realized another problem. Here's the resource list in my project:
![MJKxgw2PM5](https://user-images.githubusercontent.com/2223172/99160281-d6520d80-26e5-11eb-99df-f80d8fd3ead2.gif)
As you can see, that's some big amount of files. It would be useful if that panel had a filtering option like FileSystem Dock.

**Comment by Praytic** [comment]
I have also a need to import external assets for custom html page in Web export. I have no way to do it with editor capabilities.

**Comment by Calinou** [comment]
> I have also a need to import external assets for custom html page in Web export. I have no way to do it with editor capabilities.

This is an unrelated issue. If you want your custom HTML template to use custom files, you need to copy them manually (or use a	custom export script to do so for you after exporting).

**Comment by KoBeWi** [comment]
Nowadays I just use custom EditorExportPlugin that reads folder colors, which is like better than anything the export dialog could ever offer, so closing this.
