### ISSUE TITLE
Make hyperlinks appear underlined only on mouse hover in RichTextLabel (and the editor help)

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot-proposals#1474]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**
Permanent underlines makes text difficult to read in editor help pages. I have trouble reading.
![docgodot](https://user-images.githubusercontent.com/36481442/92428537-0f2aaf00-f198-11ea-81a5-75b540c092a9.gif)
![capmett](https://user-images.githubusercontent.com/36481442/92428550-15209000-f198-11ea-8ee6-282665104ea9.gif)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make hyperlinks appear underlined only on mouse hover in editor help pages.
 
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
for example docs.godotengine.org underlined links;
![cap](https://user-images.githubusercontent.com/36481442/92428881-05557b80-f199-11ea-8be2-df4c1fe0f97d.gif)
![underline](https://user-images.githubusercontent.com/36481442/92429021-6ed58a00-f199-11ea-9fe6-20df08bc39c6.gif)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes

**Comment by Calinou** [comment]
I think a mix of both options is the best option accessibility-wise:

- Use an underline with 50% opacity for non-hovered links.
- Use an underline with 100% opacity for hovered links.

This way, you get visual feedback when hovering a link *and* you can determine whether something is a link without relying on color alone.

**Comment by hazarek** [comment]
@Calinou 
<img width="1037" alt="cap 2" src="https://user-images.githubusercontent.com/36481442/92494317-3d42da00-f1fe-11ea-8bab-b486c5f93ed3.png">
<img width="691" alt="cap 4" src="https://user-images.githubusercontent.com/36481442/92494351-492e9c00-f1fe-11ea-853f-b0b7c5e0ceea.png">

**Comment by Calinou** [comment]
@hazarek That's an entirely different issue, which can be fixed by increasing the underline offset. Note that in 4.0, the underline offset is defined by the font file itself: https://github.com/godotengine/godot/pull/31086

**Comment by hazarek** [comment]
> @hazarek That's an entirely different issue, which can be fixed by increasing the underline offset (`underline_spacing` custom constant). Note that in 4.0, the font file's underline offset will be added to this constant: [godotengine/godot#31086](https://github.com/godotengine/godot/pull/31086)

[godotengine/godot#31086](https://github.com/godotengine/godot/pull/31086) these screenshots have same issue, should be a little lower. 
<img width="305" alt="cap 6" src="https://user-images.githubusercontent.com/36481442/92496062-55b3f400-f200-11ea-8249-d16a09c1f91e.png">

**Comment by hazarek** [comment]
The problem is that it's a permanent underscore, you're trying to rediscover gravity.
