### ISSUE TITLE
Find a way of ' making ' a commercial version of Godot . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1475]
**Describe the project you are working on:**
A Tomb Raider type game . .

**Describe the problem or limitation you are having in your project:**
I really love Godot, it is an amazing engine, in every way, so feature full, amazing, wonder-ful . . But, I feel that the current way, where it is free, and so, makes it difficult to use it, for commercial games . . Commercial games, the ones on Xbox, PC, are often a bit daft, or weird . . And, when one is given an amazing gift, made by amazing, generous people, like Godot devs, one feels it HAS to be used for games, that honor, and respect that amazing attitude, and generosity . . Sadly that means, at least for me, that I feel uncomfortable using it, for commercial games, or similar stuff, to what's on PC, Xbox, so on, because there is a ' for money ' attitude, that feels ' off ', when I use Godot . . I have been thinking, and I can't find a single good solution, but an idea is, there could be an option, to ' buy ' Godot, maybe where engine makers decide, this is a fair price, and one we can accept, for the engine, then one buys it, and one has a copy, a one-time payment, with rights to that version . . That way, one can say one has paid for it, and use it for more personal projects, or so . . The amount could be little, like 200 $, which is probably an insult to the work, behind the engine, but it doesn't really work . . I don't like the current ' pay per month ', or ' pay a percentage ' of what you make, from games, but it's also a problem, that this way, does not exist . . I feel uncomfortable taking such a free, delightful, superb gift, as this engine, and use it commercially, because it's an insult, to the purity, of the entire program, or so . .

Are there any plans to make a ' commercial ' version, some-how, of the engine, in such a way the money made, from those sales would go to Godot, it seems a bit off, when it's free, to even pay for it, but it's the best solution, I can find . . There would have to be some perks, to the commercial version, but it's really needed, because it limits Godot's ability to compete, a real shame, since it's such an amazing program, light, power-ful, just good . .

I would love to be able to ' buy ' Godot, and get a package, with a good manual, printed in a paper-back, and perhaps some high-quality assets, like really good particle systems, or other stuff, a manual, in a book, along with the software, perhaps on a USB-key, or a CD, would be really nice . . Also, if the ' bought ' form, guaranteed free access to next two versions, or a cheap upgrade, ie. upgrade to next version, at least than full cost, could be really nice . . I know the engine makers WANT it to be free, which is SO amazing, but also part of the problem . . It's a Great thing it is free, but it just makes it feel ' shitty ', to use it for commercial, or more personal projects . . How this might be combined with it also being free, is beyond me, but if the ' commercial ' version had some stuff, beyond the free version, or a manual, or a special tutorial series, in high quality, only in the paid for version, it starts to make sense, ie. a USB or CD version, of some REALLY in-depth tutorials, going over things much more carefully, than the current documentation, these are suggestions, and don't quite work . .

I would not mind paying 180 dollars, for a physical box, a manual, some extra stuff, since the engine is clearly worth it . . A one-time fee is also closer to the Godot mind-set, over monthly subscriptions . . Honestly, I'd pay 400 - 450 dollars for a version, right now, maybe Godot engine makers could decide on an amount, now that there are many donators, they might be able to make a ' decent ' offer, maybe 200 - 250 dollars, for sort of, personal, commercial version, or so, with a manual written by the core devs, with a lot of cool hints, other stuff, to make it worth it, sort of, since it is also free . . Combining the free current system, with a model for ' commercial use ' ' people ', would really help, to make one feel at ease using the engine, for more large-scoped, for-profit games, like, I made a purchase, now it's mine, I have the freedom to use it, as I see fit . . Also, the money from the sales would also go to Godot, indirectly . . Is there any way to make both ' camps ' happy, the free-for-all idealists, and also the, I make games commercially, with in-come in mind, so on . . Thx <3

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I'm not sure, maybe there's a way, for instance, buying a physical copy, in a nice package, with a good manual, so one maybe could start using it, for more commercial games, titles, without feelings bad, to-wards Godot . . :( :( . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm not sure, but I simply feel ' blocked ', when it's such an amazing gift, a FREE game engine, to use it for anything, of less than that, it's sort of rude, selfish, bad . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know how to remedy this, I just have a strong feeling, I'm diminishing the gift, of the software, when I use it for sake, of making money, or just ' closer-to-commercial ' game standards, so I hope there could be an answer, a physical box, with minimum requirements, and some nice graphics, would be ONE, but not ideal way, of doing this, but it seems broken, no matter how, not sure . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
I want to use Godot for all my game ideas, but making something even remotely like the current media feels wrong, the more ' commercial ' it gets, because one sort of ' forgets ' the amazing people, and ideas, ideology, behind the project . . I hope there's an answer, that keeps the spirit of Godot alive, but opens it up, for more commercial, personal use, I hope . . .

Thx <3

Maybe, like this, or a bundle where one gets Godot, Blender, Krita, and other strong open source programs, and the total money, goes to the ' makers ', behind it, like a ' hidden ' donation, at a price, that the devs feel is fair and, reasonable, respectful . . So, one could buy a ' low - cost ' very powerful combined open source software package, maybe for 450 dollars, where one basically donates to the programs, with the purchase, or so . .

![2020-09-08 1107](https://user-images.githubusercontent.com/61069740/92456819-b5d87500-f1c3-11ea-977d-741528968007.jpg)

**Comment by jasperbrooks79** [comment]
So, you can buy it, if you want, there's that option, you get a nice package, with high-quality material, and cool hints, written by the engine makers, and the money goes to the projects, so ' more commercial ' use, is more ' in ' reach . . It could also be cool, to have it on ones shelf, a ' real ' copy, maybe even a nice box, or with an e-book, with expanded hints, and so on, by the core team, where each specialist writes a chapter, to lessen work . . Hope, there is an answer, it would be amazing to use Godot for ' commercial ', personal stuff, as it's so amazing, it's long over-due, Please consider . .

**Comment by jasperbrooks79** [comment]
Today, a lot of media, given the amount of work behind it, sort of makes sense, that it costs money . . But, because Godot is a free gift, it feels so spoiled and, selfish to use it, for stuff like so . . I wish there was a way to ' buy ' current Godot ver., now it's yours, do with it what you want, you OWN the program, it's YOUR playground, as you please, or so . .

Help . . .

**Comment by jasperbrooks79** [comment]
An idea, there could be several Patreon levels :

Godot Entry
Godot Casual
Godot Pro
Godot Business

These are silly names, but then engine makers could maybe say, Godot Entry is suitable for new users, that want to TRY the engine, or see how it works, Godot Casual is when you like the software, and want to experiments, test it, more serious . . Godot Pro is when you have considered ' given a fair price ', and ' have bought the ' program, according to devs, Godot Business would be rather high, and give some perks, like guaranteed 1 - 2 hour talk, with engine pro, each month, or so . .

These are BAD suggestions, but maybe they could be made good, or so . . Ideally, one would want a way, to sort of pay enough, so one ' owns ' the program, according, to the devs . .

**Comment by pycbouh** [comment]
Jasper, just so you know, Patreon is not the only way to donate to Godot. You can use PayPal to make a one-time donation of any size too. See the bottom of https://godotengine.org/donate. This will be effectively you "buying" it at a price of your choosing.

![image](https://user-images.githubusercontent.com/11782833/92471588-db27ac00-f1e0-11ea-899d-ddcb3d789f0d.png)

**Comment by jasperbrooks79** [comment]
I know, but I don't know, when the engine devs feel happy, with purchase . .

Made some suggestions, for box art, or so . .

![2020-09-08 1343](https://user-images.githubusercontent.com/61069740/92472744-386c2f00-f1da-11ea-8ffe-10130debaa93.jpg)

Or, something silly, like a cereal box, fun, daft . .

![2020-09-08 1344](https://user-images.githubusercontent.com/61069740/92472781-45891e00-f1da-11ea-850d-224f45c57220.jpeg)

Or, a box covered in news-paper articles, with news from Godot land, or daft scandals, " Bug Spotted in the Godot Airport - Was Caught with Several Cases of Bad Code ", " Vulcan Erupts and Damages Several Game Folders " . .

![2020-09-08 1346](https://user-images.githubusercontent.com/61069740/92472952-6f424500-f1da-11ea-97f3-c99efc61cb5f.jpg)

I'd feel a lot better, if there was an official price, where the engine makers said, ' now you own it, for life ', what they consider a fair price or, want for it . . .

<3 . . . .

**Comment by pycbouh** [comment]
Think about it this way: devs may be unhappy to set an "official" price because that would make them feel obligated to provide a service equal to a "commercial" product instead of just making the tool for the love of it. I am sure they will enjoy any support you can fathom, but may not like to put a fixed price on it and commercialize this relationship.

**Comment by jasperbrooks79** [comment]
I agree, the issue is, to make it, in such a way, the engine makers like it, can ' live ' with it, maybe, it's possible, not sure . .

**Comment by vnen** [comment]
> I'd feel a lot better, if there was an official price, where the engine makers said, ' now you own it, for life ', what they consider a fair price or, want for it . . .

There is an official price: $0.00.  You already own it for life. You don't *need* to pay anything. If you want to help funding development you can donate. That applies to everyone.

Also if want physical goods, the amount of logistics needed for it would easily diminish the profits (even if the engine itself is free). It's really complicated to do that worldwide. Having something "commercial" would be super difficult because it would require an actual company, which requires administration, which also costs money. And then we would need to provide support and warranty to justify the price tag. It's just not feasible and not what Godot has in mind.

I did not read the whole thing TBH, but I think you are underestimating the effort (and cost) needed to do something like this.

Not to mention that Godot is getting traction *because* it's free. Adding a price tag would drive many people away because it sends the wrong message.

**Comment by sonic2kk** [comment]
I feel like this proposal completely goes against the FOSS principles of Godot. Having a cost associated with a piece of software does not automatically make it better, and likewise having no cost associated with software does not make it of poorer quality.

**Comment by Jummit** [comment]
To quote OP;

> These are BAD suggestions, but maybe they could be made good, or so . .
> Ideally, one would want a way, to sort of pay enough

There are multiple ways to do so already.

**Comment by aaronfranke** [comment]
If your goal is console exports, Godot as an organization can't do this for legal reasons, but other organizations are welcome to.

> a manual, in a book, along with the software, perhaps on a USB-key, or a CD

This sounds like a fun project actually, but not a very useful one. If anyone is up for making such a project, I will gladly help out with making an early 2000s style "Godot 3.2 CD Edition Install Wizard" just because it sounds like fun.

**Comment by jasperbrooks79** [comment]
My point is, I wish one could continue to download Godot for free, but there also was a ' commercial ' use-and-attitude, in a way that doesn't make it any less fun, or happy, for engine devs, that like FREE software, or programs . . .

I am sort of learning Unity, or Cryengine, bec. I don't feel ' good ' using Godot for commercial stuff, like it would be ' dis-regarding ' the amazing, wonder-ful gift it is, so pure, decent, for selfish ends, so it sort of destroys it's own ability to make commercial, or at least ' some money ' games, in it, even a little . .

Idea is, keep Godot engine FREE, if you WANT to, but also make an option, where engine team makes a ' fair, real ' price, so one can buy it, from the engine team, or close . . I can't use this engine, for any game that makes even a little money, so long as it is a free gift, given so generously, I can't bring myself to lessen it, by thinking about money, when using it, or so . . .

maybe, it can be fixed, with a semi-commercial model, along with free side, or so . . can't find a good answer, but I know I can't use the engine, for ANY money-make game or, title, it would be rude, dis-respectful . . .

:D :D <3 . . . .

**Comment by jasperbrooks79** [comment]
> If your goal is console exports, Godot as an organization can't do this for legal reasons, but other organizations are welcome to.
> 
> > a manual, in a book, along with the software, perhaps on a USB-key, or a CD
> 
> This sounds like a fun project actually, but not a very useful one. If anyone is up for making such a project, I will gladly help out with making an early 2000s style "Godot 3.2 CD Edition Install Wizard" just because it sounds like fun.

Yea, and the money would go to Godot, basically same place, just a ' fun ', old-school cardboard box, with a cheap USB, with a logo on, and maybe an e-book, written for that edition, a chapter by each core engine dev, or what experts among, 1000 contributors . . so, one can say, now I bought it, it's mine, it's a fair, simple deal, now I can make commercial stuff in it, if I want or, need . . Like, the other engines, maybe this not ' best ' way, of making godot more open, for ' commercial, enterprise ' use, or such . . :( :( <3 . . .

**Comment by jasperbrooks79** [comment]
Godot being free, is a bottle-neck for any-one wanting to make any, or some money using it, it's just rude, selfish . . .

Doesn't, work . . .

**Comment by clayjohn** [comment]
> Godot being free, is a bottle-neck for any-one wanting to make any, or some money using it, it's just rude, selfish ( to take something free, a gift, and get really rich from, bad manners ) . . . .

That is very kind that you feel that way. But really we are all happy for you to make money off your games. You don't have to feel bad about using a free tool to make paid games. Godot is meant to be used for commercial projects, hobby projects and everything in between.

**Comment by jasperbrooks79** [comment]
So, I have your permission to use it for commercial or, ' large ' games, if I want . . .

I wanted to ask, because what you've done, it's so amazing, so totally wonder-ful, I get afraid, to mis-use it, for personal goals /projects, or money . .

I wish there was a way I could pay for it, ' officially ', if I wanted to, or so . . Right now, I feel so bad, you have made all this stuff, for free, then I just take it, and get rich, so wrong, bad . . .

Maybe, there could be a commercial license, some enterprise - model, so one does feel like one has gotten a diamond, and is using it to dig holes, or, for oil, so on . . Like, getting something amazing, mind-blowing, and then turning it into trash, money . . .

**Comment by jasperbrooks79** [comment]
uhmm, what do the engine makers think is, a fair amount to pay, so they're happy . . . Like, on Patreon, I know they want it to be free, but for real, something this amazing, that does 90 % of the work for you, can't be free, I can be given freely, but it obviously has a money-wise value, I mean I can't really say, I could make a game, without the engine, at all . .

So, I'm relying on other people's work, and I'm getting a lot . . It would make me feel better, if perhaps there was a way, or a place to give, what engine makers ' expect ' or ' hope ', to earn, from it . . It's not fair, to take so much work, so much time, for free, and then just get rich, off it, or selfishly ' hoard ' the acclaim, or money . .

It would make me very happy, if there was an official, ' if you must ' price, one could give, on Patreon or, on PayPal, but I'm not sure, atm . . It's almost like stealing someone's car, and driving around in it, for fun, their work, money, time, sweat . . .

It's, un-comfortable, weird, I don't think there should be a ' commercial ' Godot, or so . . Just, some sort of model, where one can pay for it, if one wants, or so . . <3 <3

**Comment by aaronfranke** [comment]
@jasperbrooks79 Take a look at the tiers: https://www.patreon.com/godotengine

If you want to be told to choose a specific amount, how about one of the tiers for "Your Name in the Credits"?

**Comment by jasperbrooks79** [comment]
I know, I'm currently giving 108 dollars, each month, for a simple reason, my Samsung S10+ pay-a-year ran out, and, I have a pension, early retirement . . Before that, I paid 24 dollars . . . there are several reasons for this, mainly that I think it's a good idea there a FREE, basic engine, available to everyone, and also, that Godot can be used, for educational purposes, such as to teach code, in school, in a fun way, or so . . This is sort of what I support, and also dev of a cool, powerful engine, fun to use, as well . . .

And, my phone was actually 120 dollars, that were budgeted before, so it worked out . . That's basically what I support . .

But, I can't help feeling a bit like, stealing someone's nice car, and racing around in it, or so . . The engine took a lot of work, is a coding marvel, and fun, for users . . It's obvious, a lot went into it, they began dev in 2003, or so . . So, simply ' using ' such a massive, special thing, while getting rich myself, and not really ' paying ' for it, in a semi - fair way, feels like a no-go, or so . .

I think if there was a way, to have a paid subscription, or license, with some perks, maybe dev support, as in 1 - 2 hour monthly chats, with an engine dev, related to game dev, or engine support, maybe could be nice . . This would NOT remove the free download, but sort of create a ' tier ', or ' level ' of payment, or support, that sort of justified the amazing content and, software one is getting, partially . . .

Not sure, how to do it . . . <3

**Comment by jasperbrooks79** [comment]
Or, Godot Light ( no charge, can use the docs, forums, so on, or youtube, social media places . .
Godot Medium ( solo devs, that want a bit more support and, engine know-how, training . .
Godot Commercial (1 - 5 people, with goal of making semi- or, near-commercial game
Godot Enterprise . .

So, one could get support, perhaps designated dev time, to make a special feature, and training, and, perhaps some high-quality assets, effects, or high-level code, written by engine pros, or so . .

these are just ideas, for what one could get, I think it's a shame Godot is limited from being, by bigger commercial studios, I think this ' we shouldn't use a free gift, a real honor, and privelege, to shamelessly get rich, off others work, or so . .

It doesn't mean Godot has to become Donald Trump greedy, like . . But, maybe enough, so european kids, or game makers felt a bit more comfortable, making SOME, decent money, of it, fairly . . It isn't EITHER-OR, depending on the set-up, it could give MORE freedom, without giving TOO MUCH freedom, or so . . It's a balance, for the engine devs, to find, if they want to make Godot more ' commercially ' ready or, applicable . . <3 Thx <3 . . . . .

**Comment by jasperbrooks79** [comment]
or, Godot Free
Godot Light
Godot Hard
Godot Enterprise
one for free user, one for SERIOUS single, or 2 - 3 person teams, that want next level . .
Godot hard, for 1 - 4 team serious semi-commercial teams . .
Godot Enterprise, for 8 - 16 + size teams, that want support, for advanced features, training, more, or so . .

I'm not sure, this would work, if it took away, from the core development . .

If the price was low enough, almost a joke, but fair . . It would not make it any less open source, to me, not sure . . . .

**Comment by jasperbrooks79** [comment]
I think the engine devs could make the engine pro-dev work, right up to the point, of being greedy, selfish, but not crossing into the other side, ie. there has to be a bit of respect and, appreciate of others, or so . . But, within that being there, that basic, important sense, of other people having importance, value, one could make an honest living, using Godot, or so . . I think that's as far as the engine makers should go, to feel they can do it in good conscience, or so . . That way, they can rest well at night, knowing Godot won't be used for bad things, but moral, fair and, responsible use, or games . . .

**Comment by aaronfranke** [comment]
You are welcome to chat with me for hours if you'd like.

It seems that you are already giving very generous amounts of money back to Godot, I don't quite see the problem, you are doing much more than just "paying for it in a semi fair way" as you put it.

It's like you are racing someone's car, but you bring it back with a pile of cash inside. But also, because this is software, you racing the car doesn't take away anyone else's ability to race the car, and in this case the owners of the car want many people to race it.

**Comment by jasperbrooks79** [comment]
I'd just like to be able to pay a fair, engine dev decided amount, so I felt more free, or so . .

To use it, as I see fit, and not only ' completely open source centered ' games, but without it being ' bad ', just close to the point, where it becomes ' selfish ' use, but not so . . .

That would make me feel more free, to use the engine, responsibly, well, and make games that are more competitive, or can ' compare ' to sold stuff, atm . . It would really help, and the project could use the money, as they want, since I don't know what happens to it, ie. it could be another way, of ' indirectly ' supporting Godot, also . . That would be the result, probably, if done well, the Godot makers do everything well, maybe they could do this, also, so it keeps Godot, in the spirit, or like that <3 . . .

**Comment by jasperbrooks79** [comment]
I think, having -
Godot Basic ( free, anyone can download the engine, as they want )
Godot Pro ( for serious small teams, at game jams, or small studios even, wanting to make a ' more ' serious game, or so 
Godot Commercial ( more expensive, but if one buys for maybe 12 people, there is discount, or more ' dev ' hours, like for 6 people group purchase, 12 people, 18 people, 24, it gets cheaper, or less costly . .

the money, would be used as the Godot makers felt, was best, maybe to hire more people, or so, as they want, freely . .

**Comment by aaronfranke** [comment]
> That way, the engine devs could sleep well at night, knowing there's peace in Godot land

They already do.

I'm sorry @jasperbrooks79 but there is nothing actionable in this issue, so I'm closing this.

**Comment by pycbouh** [comment]
Despite your thoughts coming from a good place this suggestion is against all principles which the Godot is built on, Jasper. As mentioned by Aaron, your contributions are more than enough, they are significant and they allow Godot developers to do the work they like without much pressure or financial obligation. They can be free in their craft and do all of this out of love for the job.

I understand that you may not feel comfortable using the "free" work, but you are paying for it already if that matters. There are only so many words to explain that the purpose of Godot is to be free for everyone and it is owned by everyone who ever uses it. Users have no obligations, no requirements, no fees. Please understand this and be considerate of the wishes of our beloved *Juan Linietsky, Ariel Manzur, and Godot Engine contributors*.

**Comment by jasperbrooks79** [comment]
I agree, they're amazing . . .

The problem, even in normal theaters, the actors get paid, in almost all countries, or there'd be no theaters, no arts, no music . . .

I think the engine makers are amazing, no doubt . . And, I support the idea of a free game engine, a lot . . . But, in the real world, even in Europe, or communist China, workers get paid, for their work, bec. it's time-consuming, for them . . .

I would feel more comfortable using the engine, in a normal, socialist way, if one could buy a copy, to use, fair deal, or so . .

I think this limits Godot from legitimate use cases, ie. no harm, or so . . For instance, Danish tv-series, from like 2000's, we had a ' cop show ', was done really well, but even those actors, despite living in a ' free health-care ' country, got paid, it was a job, and they made ends meet, or so . .

I think Godot could ' endorse ' such things, without it becoming greedy, that's the line, or so . .

**Comment by jasperbrooks79** [comment]
But, doing it in a way, where the engine ' spirit ' stays the same, is what I can't seem, to figure . .

**Comment by jasperbrooks79** [comment]
oh, it was closed, I see, maybe, a good thing <3 . .

**Comment by aaronfranke** [comment]
> even in normal theaters, the actors get paid

> workers get paid, for their work

The main Godot developers do get paid, via Patreon. Your argument makes no sense.

**Comment by jasperbrooks79** [comment]
Thanks, for sort of, reading all this . . I have sort of, condensed my thoughts, and I will post it on next core dev stream, in a much shorter form, then they can maybe discuss it . . I sort of agree, with what you say, I think it makes little sense, but this has helped, I can make a short version, 20 lines, of this stuff, and, yea you're right, I agree, I also don't know if you're a core dev, I don't know all the names yet, sorry <3 . .

Thank you, Good points, I agree <3 . .

**Comment by aaronfranke** [comment]
> I also don't know if you're a core dev, I don't know all the names yet, sorry <3 . .

You can get a rough idea from this page: https://github.com/godotengine/godot/graphs/contributors I'm core enough to have the ability to close issues, but not merge PRs.

Generally speaking, higher on that list = more core/senior, but it's only a rough estimate. Not all commits are created equally, the value of each contribution is subjective, and different devs will focus on different repositories so some work just isn't listed there.
