### ISSUE TITLE
Torrent File for Export-Templates available on the website

### ISSUE THREAD

**Issue by Jean28518** [godotengine/godot-proposals#1479]
**Describe the project you are working on:**
Simple Linux-Project, doesn't matter..

**Describe the problem or limitation you are having in your project:**
Downloading the export templates takes 2 hours for me with a speed of 60 KB/s (Germany) I have a connection speed of 4,5MB/s...

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Through torrent files, many servers could serve the download too, so your download-server will be unloaded.  

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
An alternative .torrent download-file next to the "normal" download on the website. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Waiting... Stupid waiting...

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-website/issues/105.

In the meantime, use [this download mirror](https://archive.hugo.pro/godot-tuxfamily/) hosted by yours truly.

**Comment by Phixygamer** [comment]
I created torrent files that we can seed to improve download speed.
[https://phixy.eu/godot-export-template-torrent/](https://phixy.eu/godot-export-template-torrent/)

**Comment by Calinou** [comment]
The ongoing issue is being tracked in https://github.com/godotengine/godot/issues/108952.
