### ISSUE TITLE
World Environment option for reflections to be clear color with sky background

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot-proposals#148]
**Describe the project you are working on:**
3D free roam racing game

**Describe the problem or limitation you are having in your project:**
Currently, the best way to have a good looking sky is to use some shaders and a viewport texture (https://github.com/BastiaanOlij/godot-sky-asset and https://github.com/danilw/godot-utils-and-other are two examples). Unfortunately, reflections don't work for viewport sky, which is a preexisting issue already reported.
There exist workarounds,e.g. custom shaders for reflections (which makes it unnecessarily difficult to author content, as a Spatial Material would be sufficient). The other workaround is demonstrated in Bastiaan's asset (basically setting the viewport texture again every time it's changed) but it has quite an effect on the game's apparent performance even after throttling the updates to not occur every frame.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The current Color + Sky setting works the exact opposite way, it uses the sky for reflections and clear color for background, while for performance reasons I want to use the clear color for reflections (no longer necessitating the costly sky texture update/reset operation) while keeping the sky.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![Screenshot 2019-10-11 16:18:45](https://user-images.githubusercontent.com/4525388/66659151-348b0200-ec43-11e9-9b9b-f3f3a193e9b5.png)

**Describe implementation detail for your proposal (in code), if possible:**
IIRC all the world environment settings are enums, so it ought to be fairly easy to add a new option, but I have 0 idea where to start on the actual reflections code.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Nope, it's not possible to set a clear color for reflections in any way.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Requires code changes in engine.

**Comment by clayjohn** [comment]
3.2 will use clear color for reflections when background mode is color https://github.com/godotengine/godot/pull/27898

4.0 already uses the Viewport texture background for reflections too I believe. If not, it is already planned.

**Comment by Zireael07** [comment]
That's good to know, but I want the background to be sky (procedural or panorama), and color for reflections, in case I haven't made that clear enough.

**Comment by clayjohn** [comment]
Yep. Already added in 4.0.

**Comment by clayjohn** [comment]
As this is already implemented in master, I will close. :)

Just set ``background`` to "Sky" and set both ``ambient_light_source`` and ``reflected_light_source`` to "Color"

**Comment by Zireael07** [comment]
Thanks - just for clarification, you probably mean it happened post-Vulkan merge, right?

**Comment by clayjohn** [comment]
@Zireael07 I just realized I was wrong here. The settings that were added were actually just "Sky", "Background", and "Disabled" there is no option to use a color instead of the sky. It is implemented through the ability for sky shaders to selectively render to different buffers. So you can render a plain color to the radiance cubemap and then render the full sky as background to save speed. 

Additionally, radiance cubemap generation was sped up to be fast enough for real time. It no longer suffers from the slow generation that it did in 3.2. Finally, even if you use the highest quality, it only updates when the sky updates, so if you have a static sky, the radiance cubemap will only generate once. 

So, your exact proposal was not implemented like I thought it was, but you can definitely achieve what you asked for and due to the optimizations added, you shouldnt even need to use the workaround you asked for. :)

**Comment by Zireael07** [comment]
Revisiting this issue because I finally got around to trying Vulkan.

>  it only updates when the sky updates, so if you have a static sky, the radiance cubemap will only generate once.

Unfortunately I do have a dynamic sky, so the radiance cubemap generates every time the sun moves and no amount of tinkering allows me to prevent fps dipping to 45-ish when it happens (on a practically empty scene, two cubes and the sky).

Since I am rendering a plain color to the cubemap, what is the effing point of regenerating the cubemap?!

**Comment by Calinou** [comment]
> Unfortunately I do have a dynamic sky, so the radiance cubemap generates every time the sun moves and no amount of tinkering allows me to prevent fps dipping to 45-ish when it happens (on a practically empty scene, two cubes and the sky).

Did you set the background update mode to **Real-Time** instead of **Automatic**?
