### ISSUE TITLE
Add an out of the box, standardized options menu

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-proposals#1483]
**Describe the project you are working on:**
A 2D topdown action hobby game.

**Describe the problem or limitation you are having in your project:**
So I was implementing some options for the game and felt like I was just re-inventing the wheel with the options menu. Then I wanted to add some accesibility options, like input remapping, and thought everyday game could use those.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A standardized options menu with accesibilty options out of the box. That way each godot game, where the developers do not have the time, has at least a certain standard of accesibilty (input remapping, color filters, contrast, ...) and options. I think godot could benefit  from that.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I am not sure how to make such a feature, but I figure that standardizing an options menu is the hardest part. Then an OptionsScene could be added to every new project where one can adjust the visuals with the theme resource. And then developers could also add some game specific options.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be made in the editor, but depending on the amount of options, it can become somewhat complex.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It could be an add-on, but maybe more options can be accesed by putting it in the core? I don't know, I am not really a programmer.

**Comment by KoBeWi** [comment]
> but maybe more options can be accesed by putting it in the core?

That's impossible. Not everyone will want to use the standard menu, which means that these options need to be available for scripting. So this is definitely something for an add-on.

**Comment by EricEzaM** [comment]
Yeah there are already a number of templates on github made by the community which do this. Plus remember that not all godot applications are games, sometimes a settings menu does not make sense.

**Comment by boukew99** [comment]
Okay thanks. Do you have a link to such a template? And shall I close this request then?

**Comment by EricEzaM** [comment]
Here is an example.

https://github.com/nezvers/Godot-GameTemplate

I would say yes, as this would not be implemented into the engine as it is what add-ons and templates are made for.

**Comment by boukew99** [comment]
closed
