### ISSUE TITLE
Make it possible to not automatically open the virtual keyboard in SpinBox "on text entered"

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot-proposals#1492]
**Describe the project you are working on:**
I'm working on BlueTooth Poker 8 Free/Pro on Android

**Describe the problem or limitation you are having in your project:**
I must recompile the export templates because i don't want to open the virtual keyboard on spin boxes

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
a check box which let the developer to choose between virtual keyboard automatically opened or not automatically opened

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
a check box in Spin Boxes parameters and others which are emitting text_entered signal in Godot.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
must recompile the export templates for each new version of Godot.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's about virtual keyboard which is core implemented

**Comment by KoBeWi** [comment]
You can access the SpinBox's LineEdit with `get_child()` method and disable the keyboard. There's a property in LineEdit that allows it:
![image](https://user-images.githubusercontent.com/2223172/93004401-ea8f5800-f546-11ea-8442-39dbcf9fa631.png)
This is a workaround, but it's still better than recompilling templates.

**Comment by DisDoh** [comment]
Which version are you using? I'm using 3.2.2-stable and there is no such setting in LineEdit.

**Comment by KoBeWi** [comment]
I think it was added for 3.2.3, you can try [rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6), it's pretty stable already.

**Comment by DisDoh** [comment]
Thank you!

**Comment by m4gr3d** [comment]
@DisDoh Closing the proposal as it seems to be resolved by the option that @KoBeWi provided. Feel free to reopen if that's not the case.
