### ISSUE TITLE
Add more noise generators such as random, cellular, Anisotropic etc.

### ISSUE THREAD

**Issue by jak6jak** [godotengine/godot-proposals#1493]
**Describe the project you are working on:**
Learning about shaders and Godot

**Describe the problem or limitation you are having in your project:**
When creating procedural materials noise is often used. Common types of noise are random, cellular, FBM, and simplex noise.

Currently the visual shader editor only can generate simplex noise. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Currently if you want to use noise in visual shader editor you would have to build it yourself. This can be time consuming and difficult. Other visual shader editors have a large tool set of different noise generators such as Blender, and Substance. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I would assume it would be added to the list of types of noise to create within the NoiseTexture resource. 

I am interested in helping implement this myself. I am not familiar with how opensimplexnoise was added. Any guidance would be appreciated. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
this tutorial shows how to create the various nose through code: https://www.youtube.com/watch?v=ybbJz6C9YYA However, the tutorial does not use visual nodes. 

**Is there a reason why this should be core and not an add-on in the asset library?:**
Having a good selection of noises is common in visual shader programs such as Blender, Substance, and Unity. I think adding more noise types will put godot closer to being on par with other visual shading programs. I do not know how easy it is to create another generator with a plugin. If it is easy I would love to know how.

**Comment by Calinou** [comment]
This pull request addresses this: https://github.com/godotengine/godot/pull/35144

**Comment by jak6jak** [comment]
Does that pull request make this proposal obsolete?

**Comment by Calinou** [comment]
@jak6jak You can keep this proposal open until the pull request is merged :slightly_smiling_face:

**Comment by jak6jak** [comment]
whats holding it up? Anything I can do to help?

**Comment by Calinou** [comment]
@jak6jak We don't know if the feature added in the pull request is actually desired enough to be worth the added file size and maintenance costs.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/56718.
