### ISSUE TITLE
Visualize Position2D, Position3D and RayCast3D orientation with editor gizmos

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot-proposals#1497]
**Describe the project you are working on:**
I am using the Position2D node in my project as a socket so I can visually place and recognise them in the editor. The specific sockets where I noticed the issue were ones where directional weapons could be placed.

**Describe the problem or limitation you are having in your project:**
I cannot see the orientation of the node. Ideally, I'd like to have an error depicting the forward axis of the node, similar to how a DirectionalLight uses an arrow to visualise its direction.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Although the orientation can be seen when selecting the node and switching to local space, it becomes ambiguous when deselected. The gizmo for both the Position nodes could be rotated by 180 degrees in any direction without it being visually clear. Having an arrow depicting forward (or maybe different size/thickness axes?) would show the user the orientation immediately. The RayCast node only shows a line and not a direction; when not selected it is unclear what the start and end points are. RayCast2D does show an arrow, so for the sake of consistency alone it would make sense for the 3D version to do the same.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It could work exactly the same for Position3D and RayCast as a directional light in 3D, and the Position2D could work the same as a RayCast2D.
3D:
![image](https://user-images.githubusercontent.com/7684647/92997576-3b358f80-f50c-11ea-81dc-a2e06fee46c5.png)
2D:
![image](https://user-images.githubusercontent.com/7684647/92997597-61f3c600-f50c-11ea-8f10-603164b0a98e.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It would be used for every position and raycast node and wouldn't make a lot of sense as a tool; it's pretty much core functionality.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It doesn't add any actual functionality other than a life improvement when working with the engine; that wouldn't make a lot of sense as an add-on.

**Comment by Calinou** [comment]
This will probably have to be a toggleable property on a per-node basis, sincce you don't always care about a Position2D/Position3D's rotation.

**Comment by Calinou** [comment]
This has been addressed for RayCast with https://github.com/godotengine/godot/pull/46529 and will be addressed for Position2D/Position3D with https://github.com/godotengine/godot/pull/49128.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/46529 and https://github.com/godotengine/godot/pull/49128 are both merged now, closing.
