### ISSUE TITLE
Optimize start-up 3D environment

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1498]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
Many have complained the default lighting, bec. sky contribution is a bit ' blue ', from blue sky being a light source . . This makes it difficult, to make a ' pure white ' cube, and sort of, makes things look weird . . It's counter-intuitive for a beginner, to have to find a weird setting, called sky contribution, or know that's even the problem . . It's a lot better, in Godot 4 current builds <3, but I have a suggestion . . Right now, when one creates a 3D world, the ' assumption ' is, one wants to make a ' photo-real ' game, ie. with a sophisticated, near-accurate sun and, ' atmosphere ' simulation . . However, many games, going back a long time, and many current 3D games, are stylized, and do not need this, at all . .

There's also the idea, most graphics settings are turned off, by default, in Godot, to maximize performance, on any hardware, or for ' mobile ' titles, and this is a really good approach . . So, based on that, one can say, what is the ' optimal ' start environment, and that's simply a background, like in Blender, maybe a bit darker ( no auto-blue sky, or like that ), and a sky contribution set to ' 0 ', and the ambient light to ' pure white ', intensity 1 . .

That way, the ' fastest ' default editor settings, in terms of performance, on any device, would look like this, or so . . .

![Skærmbillede (243)](https://user-images.githubusercontent.com/61069740/93014772-24e30e80-f5b4-11ea-80d5-75468fc92c97.png)

![Skærmbillede (244)](https://user-images.githubusercontent.com/61069740/93014778-2ca2b300-f5b4-11ea-867f-237abb339a67.png)

And, since the most basic, classic games, are basically stylized, going back to Mario 2D ( simple, ambient light ), or games like Mario 3D games, these are sort of the most fun, silly games one can play, and it would make sense, if Godot sort of, looked like that, by default . . . Would make sense to new users, and no one would be confused, by an odd ' color ' to everything, they didn't ask for, and for stylized games, a MAJOR slice, of 3D games, even today ( Kingdom Hearts, Mario Galaxy, some Nintendo games ), this would be a GOOD default setting, as MANY games are made, designed to look like, that . .

So, because many games are SUPPOSED to look stylized, and it makes sense, if one imports an asset, that it ' looks ' basically like what it is, fundamentally . . .

Also, from performance perspective, since simple ambient light is the fastest, I think one could say, the ' best ' default environment is the above . . At least, that fits with the rest of the engine, where most graphics settings are turned ' off ', by default, such as MSAA, anisotropy, to make the engine run as fast, and have best performance, in editor, by default . . So, that is the idea, to make the default environment look, and run like above, I think that is logical, or almost . . :D :D <3 . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Just, make the most basic start-up editor look, as everything makes more sense then, and it will run faster, on basically any device, or so . . Alternatively, make a ' editor settings ' option, to set new default environment settings, like in Blender, where one can ' save ' a different start-up document, ex. no default cube, or so . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just make the default environment as FAST, and also logical, as possible, bec. MANY games are made to be stylized, and if one imports a model, even a photorealistic one, it still looks good in simple, white ambient light, but many stylized games look ' wrong ', when the PBR sky is set to on, ie. it would work better, for all cases <3 Thank you . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Just an idea, pretty simple, ps. Really love Godot, you've done an amazing job, it's the engine for me, for life <3

**Is there a reason why this should be core and not an add-on in the asset library?:**
To make, it faster and, far more intuitive, ESPECIALLY for beginners, and stylized game makers, as well . .

![2020-09-13 1136](https://user-images.githubusercontent.com/61069740/93014944-8061cc00-f5b5-11ea-8d1f-4677a854b134.jpg)

![2020-09-13 1137](https://user-images.githubusercontent.com/61069740/93014947-822b8f80-f5b5-11ea-8970-db1bcfb0f7f3.jpg)

![2020-09-13 1138](https://user-images.githubusercontent.com/61069740/93014961-98395000-f5b5-11ea-900d-b98e17e61a98.jpg)

Faster, more intuitive, and one doesn't have to look for tutorials, or join various forums, to make a simple, white color, or so, works for everyone, also PBR crowd, that know things need a lot more complex settings, to be more real-looking, after initial import, or so . .

Thanks <3 . . .

**Comment by jasperbrooks79** [comment]
If the default environment then looks ' empty ', one could make so, when adding the 3DNode, Spatial, that it is ' selected ', so there's a gizmo, one can see, instead of an ' empty ' space . .

![Skærmbillede (245)](https://user-images.githubusercontent.com/61069740/93015011-0b42c680-f5b6-11ea-83fd-8d48a7901bd9.png)

Stylized games, are by all definitions, pure classics, and making the default environment be ' set ' to those games, would not make the engine any less ' useful ', or cool . . And, it would make it easier, to use the engine, and MANY stylized games, are either classics, or have become classics . . .

![2020-09-13 1143](https://user-images.githubusercontent.com/61069740/93015041-4d6c0800-f5b6-11ea-9686-89e1c548ae37.jpg)

One could maybe argue, that those games are in fact ' more ' games, than more PBR 3D games, bec. it's OBVIOUS, it's just a game, not real, like a monopoly board, or chess, or so . . <3 :D . . .

**Comment by jasperbrooks79** [comment]
Result, better default performance, and everybody is more happy with engine, whether for small, or massive stylized games, as well as more photo-real minded games, either would look GOOD like that, by default, but now, NOTHING looks good, at it drains performance, to turn on needless feature, my thoughts, again thanks . . .

**Comment by jasperbrooks79** [comment]
Then, one would have to find a ' background grey ', that looked nice, in the themes, light, default, solarized, so it just ' works ', or so . . :D :D <3 . . . .

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/46315, closing.
