### ISSUE TITLE
Allow copy-pasting property values by hovering them in the inspector and pressing Ctrl + C / Ctrl + V

### ISSUE THREAD

**Issue by Olaf-007** [godotengine/godot-proposals#1504]
**Describe the project you are working on:**
Multiple projects. 

**Describe the problem or limitation you are having in your project:**
In my projects I ofthen have to align two nodes (or more) with the same propertys (e.g. aligning multiple nodes to the same position). So what I do: I go and copy the x-coordinate and paste it in the next object. Then I go back and copy the y-coordinate ... paste it ... z-coordinate ... paste it. UUfff!
Another example: I have two Buttons and create three custom_styles for normal, hover and pressed. I would like to quickly share these StyleBoxes with the other button, so what do I do: I save all three StyleBoxes in the file directory and drop them into the Button. UUfff, this takes a lot of time espacially when you want to try sth. out quickly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This is the solution I propose which is inspired by a feature in Blender:
When hovering a value inside the inspector, the user can press CTRL+C so without clicking the value is copied.
Then the user hoveres the property he wants to past in and presses CTRL+V (optionally the user has to press the property to not exidentally drop sth when not focussing on the mouse)
Here is how it works:
![Improvment](https://user-images.githubusercontent.com/56698992/93029519-b2a61480-f61b-11ea-8678-3504c07e174d.png)

And there could be even more: hovering a property and pressing Shift+C could copy the property name or path so the user can insert it directly into his code. (Imagine such long ones as subsurf_scatter_enabled) 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If you have more questions on this, please ask :) 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This enhancement will be used often because it increases the workflow dramatically.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a workflow speedup and huge comfortability feature. This should be part of the major engine.

**Comment by Calinou** [comment]
> And there could be even more: hovering a property and pressing Shift+C could copy the property name or path so the user can insert it directly into his code. (Imagine such long ones as subsurf_scatter_enabled)

I would use <kbd>Ctrl + Shift + C</kbd> for that instead.

**Comment by Jummit** [comment]
Maybe the same could be done with project and editor settings, they are a pain to copy too.

**Comment by me2beats** [comment]
I just wanted to create a similar proposal. My idea was that we could just select the property with mouse click, say `size`, then `Control+c`, then select the target property and then `Control+V`.
I also like the idea of ​​copying a property under the mouse.

This way you could easily copy values ​​for example from `size` to `min_size` or from `size_flags_horizontal` to `size_flags_vertical` or even properties from one node to another.
That would be super convenient.

Wondering if there are such plugins?
would be handy for reference

**Comment by me2beats** [comment]
Hm there are `Copy Params` and `Paste Params` in `EditorShortcuts`, `PropertyEditor` section. 
But it seems it works a bit strange. Need to delve into this
![copy_params](https://user-images.githubusercontent.com/16458555/109440652-d4be1280-7a54-11eb-8bd9-9e3053c65c27.png)

**Comment by Calinou** [comment]
Closing, as this was implemented by https://github.com/godotengine/godot/pull/39404.
