### ISSUE TITLE
translate_object_local() exist but move_and_slide_object_local() doesn't

### ISSUE THREAD

**Issue by BracerJack** [godotengine/godot-proposals#1517]
$KinematicBody.move_and_slide(-$KinematicBody.global_transform.basis.x) works on a crunch but move_and_slide_object_local() would complement/make consistent the overall language since translate_object_local already exist.

**Comment by groud** [comment]
Please fill in the issue template, it's mandatory. I' will reopen when this is done.

**Comment by BracerJack** [comment]
Too bureaucratic, point has been raised, if you want to shut it down because "process", so be it.

**Comment by groud** [comment]
Ok no problem.
