### ISSUE TITLE
Windows distribution on WinGet

### ISSUE THREAD

**Issue by SeleDreams** [godotengine/godot-proposals#1523]
Since Microsoft recently ended up adding an official open source package manager to Windows named WinGet, that is relying on community repositories, I felt like it could be a good idea to distribute Godot on it, the procedure to publish on WinGet seem pretty simple, it would make managing the godot install on windows more straightforward for those used to Unix-like workflows while using native microsoft softwares https://docs.microsoft.com/en-us/windows/package-manager/package/

**Comment by clayjohn** [comment]
Interesting idea, but please edit your post to use the template provided instead of deleting the template!

**Comment by SeleDreams** [comment]
> Interesting idea, but please edit your post to use the template provided instead of deleting the template!

the main reason is that the template seems to focus on a fix for a specific project while mine is more of a suggestion to make the installation and maintaining process more convenient for everyone, so i could follow the template but modify the stuff to refer to the general installation and update experience

**Comment by Calinou** [comment]
Anyone can add software to WinGet. However, [WinGet doesn't support installing from ZIP files yet](https://github.com/microsoft/winget-cli/issues/140), which means it's not currently possible to add Godot to WinGet.

**Comment by somedeveloper00** [comment]
any news yet? and why is this closed? couldn't someone build a version with installer for windows? I mean, I could do it if really no one's up to it ¯\_(ツ)_/¯

**Comment by somedeveloper00** [comment]
> Anyone can add software to WinGet; you don't need approval from core developers to do it. However, [WinGet doesn't support installing from ZIP files yet](https://github.com/microsoft/winget-cli/issues/140), which means it's not currently possible to add Godot to WinGet.

![image](https://user-images.githubusercontent.com/79690923/178246087-9ce26bd1-97c8-49f3-beb8-bbb828c2b6f3.png)
in the official docs https://github.com/microsoft/winget-pkgs#Contributing I think it reads that it's important to have the right to publish the package

**Comment by YuriSizov** [comment]
> in the official docs https://github.com/microsoft/winget-pkgs#Contributing I think it reads that it's important to have the right to publish the package

Godot is provided under the MIT license, so you are free to distribute it on your own. So this paragraph from WinGet docs is not preventing anyone from publishing Godot there.

> any news yet? and why is this closed?

It is closed, and there are no news, because we have no plans to publish on WinGet ourselves. Or, at least, didn't have such plans two years ago. But Godot is a community project, so everyone is free to try and support other ways of distributing it, and then we can "endorse" such distributions.

**Comment by Calinou** [comment]
I wouldn't recommend working on an unofficial installer in the goal of getting it published on WinGet for two reasons:

- Microsoft may not approve of unofficial builds branded as Godot.
- ZIP support is being worked on, so this will be possible with official builds eventually: https://github.com/microsoft/winget-cli/issues/140#issuecomment-1163490449

**Comment by PodyNoo** [comment]
@Calinou Since Winget now supports .zip installation [ #140](https://github.com/microsoft/winget-cli/issues/140), is Godot distribution via winget now possible for windows ?

**Comment by Calinou** [comment]
> @Calinou Since Winget now supports .zip installation [ #140](https://github.com/microsoft/winget-cli/issues/140), is Godot distribution via winget now possible for windows ?

Yes – feel free to open a pull request on https://github.com/microsoft/winget-pkgs for this :slightly_smiling_face:

**Comment by sitiom** [comment]
I do not recommend adding Godot to Winget yet. Godot is a GUI application and, thus, requires a start menu shortcut. However, Winget does not support it yet.
- https://github.com/microsoft/winget-cli/issues/2299

**Comment by somedeveloper00** [comment]
> I do not recommend adding Godot to Winget yet. Godot is a GUI application and, thus, requires a start menu shortcut. However, Winget does not support it yet.
> 
> * [Add start menu entries for portable applications microsoft/winget-cli#2299](https://github.com/microsoft/winget-cli/issues/2299)
> 
> The other issue is that the Mono version cannot be added to Winget. Symlinked executables from the command line suffer from missing DLLs/dependencies:
> 
> * [Zip binaries installer microsoft/winget-cli#2711](https://github.com/microsoft/winget-cli/issues/2711)
> 
> It seems like Winget is still behind on many things when it comes to portable applications. The only portable apps that you can add to Winget for now are **static CLI applications**, which is way limited.

Winget already has gui applications like Unity, Powertoys and even Jetbrains Rider and vscode as a few examples. I don't know the technical parts thoroughly, but vscode even gets a start menu when installed using winget. so that means it *is* possible, right? I think if you guys add an installer for it, then winget can get the installer and wait for it to finish? I believe that's what they did with Jetbrains Rider, but I'm not 100% sure about that

**Comment by sitiom** [comment]
> Winget already has gui applications like Unity, Powertoys and even Jetbrains Rider and vscode as a few examples.

Yes, but they all have installers, while Godot doesn't. You can track the installer proposal here:
- https://github.com/godotengine/godot-proposals/issues/1432

**Comment by RokeJulianLockhart** [comment]
https://github.com/microsoft/winget-pkgs/issues/124827#event-10891315609 resolves this.

**Comment by sitiom** [comment]
It is being run as a command and not put as a start menu shortcut, which is not ideal for a GUI app, isn't it?

**Comment by RokeJulianLockhart** [comment]
@sitiom, indeed. I've asked https://github.com/microsoft/winget-pkgs/discussions/184459#discussion-7342013 in the meantime, but we're still waiting for https://github.com/microsoft/winget-cli/issues/2299#issue-1291406635 or https://github.com/godotengine/godot-proposals/issues/1432 to be remediated for the experience to be pleasant.

I was solely referring to *this* issue's request, unfortunately.
