### ISSUE TITLE
Allow control of client port on StreamPeerTCP connections

### ISSUE THREAD

**Issue by dam-coder** [godotengine/godot-proposals#1527]
**Describe the project you are working on:**
Simple game with local and online multiplayer capabilities.

**Describe the problem or limitation you are having in your project:**
I need to have knowledge and control over the client ports used in the network connections so I can:
- connect players in peer-to-peer (no server-in-the-middle) mode using `NetworkedMultiplayerENet`;
- simultaneously, connect players to the central server (to perform matchmaking and keep high-scores) using `StreamPeerTCP`;
- perform NAT punch-through in both connections.

`NetworkedMultiplayerENet` already allows to control the client ports, but `StreamPeerTCP` does not.

Further notes: Since this is a fast-paced game, it is very sensitive to network delays which motivated me to use a peer-to-peer connection between the players.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This limitation can be overcome with two features:
- allow to state which client port the `StreamPeerTCP` will use;
- provide a way to know which client port is currently being used by the `StreamPeerTCP`.

Such will allow greater control and the ability to perform NAT punch-through over `StreamPeerTCP` connections.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I've implemented and tested (on Linux and Android) the proposed features.
- Pull request for `master` branch: https://github.com/godotengine/godot/pull/42151
- Pull request for `3.2` branch: ready for PR but rules clearly state to merge developments in master first.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
My understanding is that this will be used often and it cannot be worked around.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This seems to be a core feature and needs to interact with the underlying mechanisms of the net_socket... but I don't have sufficient knowledge about the add-ons to be sure about this. Maybe the core developers can shed some light on this one?

**Comment by jonbonazza** [comment]
I agree that you should be able to query which port the os assigned to the client, but there is no feasible way to pick a port for a client connection. This is provided by the os in a system call.

**Comment by Calinou** [comment]
> I agree that you should be able to query which port the os assigned to the client, but there is no feasible way to pick a port for a client connection. This is provided by the os in a system call.

If Xonotic's settings menu is anything to go by, choosing the client port is possible:

![image](https://user-images.githubusercontent.com/180032/96096571-45162e00-0ed0-11eb-8554-fa875aab9c4f.png)

Likewise, most torrent clients allow you to configure this port.

**Comment by dam-coder** [comment]
> I agree that you should be able to query which port the os assigned to the client, but there is no feasible way to pick a port for a client connection. This is provided by the os in a system call.

From what I read on the documentation, and based on my tests, it is possible to specify a port.
Note that I've already included a PR with the implementation which I tested on Linux and Android systems.

Below I describe what seems to be the common behavior on linux based and Windows operative systems:
- If you do not specify a port, the Operating System (OS) will provide one of the ephemeral ports if any is available, or an error otherwise. See [here](https://www.man7.org/linux/man-pages/man2/bind.2.html#ERRORS) under `EADDRINUSE` and [here](https://man7.org/linux/man-pages/man2/connect.2.html#ERRORS) under `EADDRNOTAVAIL`.
- In case you specify a port, the OS will try to provide that port, which may fail in case it is not available (which may happen for a number of reasons). Although not entirely explicit on the documentation, you can use the `bind` system call to specify the port you want to use. You can set the port number using the field `sin_port` inside the struct of the parameter `const struct sockaddr *addr`. Here you can find more info about the [bind system call](https://www.man7.org/linux/man-pages/man2/bind.2.html) and here about the struct [sockaddr](https://man7.org/linux/man-pages/man0/netinet_in.h.0p.html).

**Comment by jonbonazza** [comment]
Huh.. generally, bind is only used server-side to allow clients to connect to the address. I have never heard of bind being used client-side like this. I mean theoretically it should work, but i'm concerned there may be some unexpected implications to this. Perhaps @fales has some more insight here, but Id suggest we do some more research first.

**Comment by Calinou** [comment]
cc @Faless

**Comment by dam-coder** [comment]
> Huh.. generally, bind is only used server-side to allow clients to connect to the address. I have never heard of bind being used client-side like this. I mean theoretically it should work, but i'm concerned there may be some unexpected implications to this. Perhaps @Fales has some more insight here, but Id suggest we do some more research first.

It is commonly used to implement NAT traversal techniques like `NAT punch-through`.
Also, it is already implemented in part of GODOT networking tools, see method `create_client` in [NetworkedMultiplayerENet](https://docs.godotengine.org/en/stable/classes/class_networkedmultiplayerenet.html#class-networkedmultiplayerenet-method-create-client) for example. Its last argument allows you to establish the client port, similar to what I propose.

If this has some unexpected implications in GODOT, that I cannot comment on.

**Comment by dam-coder** [comment]
Closing because I submitted a new [Proposal](https://github.com/godotengine/godot-proposals/issues/1744) and [PR](https://github.com/godotengine/godot/pull/43174) that supersedes the current ones.
