### ISSUE TITLE
GLES2/WebGL check for GL_OES_standard_derivatives for the future transition to Godot 4

### ISSUE THREAD

**Issue by danilw** [godotengine/godot-proposals#1536]
**Describe the project you are working on:**
WebGL GLES2 export from Godot3 engine

**Describe the problem or limitation you are having in your project:**

as I understand Godot 3.2 do now support `GL_OES_standard_derivatives` n GLES2
[Differences between GLES2 and GLES3](https://docs.godotengine.org/en/latest/tutorials/misc/gles2_gles3_differences.html#shading-language)
dFdx dFdy fwidth not supported in Godot 3.2 in GLES2

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

**`GL_OES_standard_derivatives` supported on every modern GPU, when they fall-back to GLES2, like in WebGL mode**
https://developer.mozilla.org/en-US/docs/Web/API/OES_standard_derivatives

`GL_OES_standard_derivatives` is very useful

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Checkboxes in Godot GLES2 settings to "enable optional extensions"...

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
**Is there a reason why this should be core and not an add-on in the asset library?:**

render engine option

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/877.

We intend to keep some kind of GLES2 renderer in Godot 4.0, but it will likely be intentionally limited to ease maintenance. (It might be 2D-only, for instance.)

**Comment by danilw** [comment]
I see, thanks

look like WebGPU should be next Web-integration for Godot

closed I think
