### ISSUE TITLE
Add different icons to each data - type in the res folder / HDD dock

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1543]
**Describe the project you are working on:**
A Tomb Raider game, atm . .

**Describe the problem or limitation you are having in your project:**
Currently, many of the icons in the ' res ' folder, look the same, which can be a bit confusing . . .
<img width="226" alt="Skærmbillede (299)" src="https://user-images.githubusercontent.com/61069740/93725950-92de9580-fbb3-11ea-9db7-d34aef005da7.png">

I was wondering, if we could get some easier to read ' icons ', ie. either a visual easy ' to find ' icon, or just some letters, inside the ' document ' icons . . it would help read what was in the res:// folder, and speed up game making, also . .

Here are some simple, but easily recognizable icons, or a style . .

![2020-09-21 0240](https://user-images.githubusercontent.com/61069740/93726015-dcc77b80-fbb3-11ea-9367-52e0e82c99e5.jpg)

Ideally, we'd need some beautiful, nice icons, but the above is sort of a ' functional - working ' style, ie. it'd be enough . . One could also just write, with bigger letters, inside each icon, for example . .

<img width="654" alt="Skærmbillede (299)" src="https://user-images.githubusercontent.com/61069740/93726069-2617cb00-fbb4-11ea-9a4a-ca622d4b75a4.png">

Imo, having nice icons could make it more fun, to work with Godot, also . . However, actually making these icons, so they fit well with the editor, or so, is beyond me, the above are just suggestions . . Same way in visual script, the different boxes have a different colored header, maybe the icons could have a slightly different color, also . .

<img width="225" alt="Skærmbillede (299)" src="https://user-images.githubusercontent.com/61069740/93726128-72fba180-fbb4-11ea-998e-44411d0310c2.png">

Guess my point is, it would be nice if the icons actually we're both nice, and had colors, or at least a ' shape ', that was distinct, maybe someone can make a nice idea, not sure . . .

I like these, but they're not ' the right ' ones, or so, an idea . . .

![2020-09-21 0246](https://user-images.githubusercontent.com/61069740/93726153-a76f5d80-fbb4-11ea-8528-963dc920b296.png)

Or . .

![2020-09-21 0247](https://user-images.githubusercontent.com/61069740/93726166-b7873d00-fbb4-11ea-8cbb-51a43f85116a.png)

With each one being ' tweaked ', so they fit the engine, Thanks <3 . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Just make the editor a bit nicer, to work with . . Something fun, and that makes sense, for game making, is fun, but also neat, technical, efficient, something cool . . . <3

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just add a different icon pack, for the major data types, ie. imported mesh3D data, imported sound, visual scripts, png, jpeg, so on . . Right now the folder is difficult to read, bec. it's missing, compared to many other programs . . Would help keep track, and more easily find stuff, in the res:// folder dock <3 Thx . . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not sure, I don't know the engine well enough, tbh . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Everybody uses it all the time, so it makes sense, but someone needs to make some really nice ' Godot ' specific icons, maybe like the above, not sure, did a quick google search, for icon packs, none of them are ' just right ', or so . .

<3

**Comment by jasperbrooks79** [comment]
The above are a bit silly, maybe a bit more ' business ' or, ' hard-core software ' look, would be nicer, not sure . .

![2020-09-21 0252](https://user-images.githubusercontent.com/61069740/93726309-9a9f3980-fbb5-11ea-9c6e-ad216bf26d67.jpg)

Like, ' Microsoft Word ', or ' openOffice ' icons . . <3

**Comment by jasperbrooks79** [comment]
imo, the icons should be appealing and, have a clear visual signature and, ' look ' . . so, one can simply look at them, know what they do, and not have ' read ' anything, or so . . They should also be modest, simple and, ' look ' nice . . .

Ideas . . .

**Comment by Calinou** [comment]
Closing due to lack of support (see general lack of activity here).
