### ISSUE TITLE
Make PopupMenu usable without the use of scripts

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [godotengine/godot-proposals#1544]
**Describe the project you are working on:**

A landscape-visualization software: https://github.com/boku-ilen/landscapelab. It uses geo-data to dynamically create a world. Having the right geo-data every place on the world can be mimiced. There is also VR-features which in the near future will be extended.

**Describe the problem or limitation you are having in your project:**

To fill a PopupMenu an unrelational effort is required. It would be nice if there was support being able to do some of the Configurations inside the editor.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

My idea would be to give a PopupMenu an ``export(Dictionary)`` (can be seen inside editor) field that makes it possible to add new submenu items (where the key will be the displayed name and the value the submenu that is automatically tried to be accessed as a child-node of the PopupMenu). If the value will be left out being null, or the value can not be found as a child, the entry will not provide any further submenu.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Im not very fit for giving a C++ implementation and would let the professionals do their job. But a pseudo mockup would look like this: 

![grafik](https://user-images.githubusercontent.com/33001106/93761826-be429e00-fc0e-11ea-8a5b-14e1135055d2.png)

![grafik](https://user-images.githubusercontent.com/33001106/93761644-699f2300-fc0e-11ea-8d60-46fdd82bb973.png)

Maybe it would be smarter to be able to also add a type of the item (Submenu, Default, Radio-Check, Icon, ...). I dont really now if there is a possibility for this. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Kind off, but i feel like it could really enhance the usability of this node.

**Is there a reason why this should be core and not an add-on in the asset library?:**

I think that is kind off evident. I feel like one of the philosophies of godot is to be able to get a lot of work done without using scripts, this could further enhance this philosophy.

**Comment by groud** [comment]
Have you noticed the "Objects" menu appearing in the toolbar  when you select a PopupMenu node? It looks like what you are describing.

**Comment by MathiasBaumgartinger** [comment]
Well yeah, that was exactly what i was talking about, thank you for your response 👍
