### ISSUE TITLE
Replace Category and Name with a single property Name field in the Project Settings

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot-proposals#1545]
**Describe the project you are working on:**
A game

**Describe the problem or limitation you are having in your project:**
It is inconvenient to copy a two-part setting name, while the ProjectSettings singleton uses a single name.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
One single field from which you can copy the entire setting name.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![](https://user-images.githubusercontent.com/47700418/93780002-48e7c500-fc30-11ea-805e-42bc1536e9d2.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think not, you still have to copy it twice.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is just the functionality of the editor.

**Comment by Calinou** [comment]
I agree it would probably better to have a single property path rather than a category/property separation. This makes it easier to copy/paste the path around :slightly_smiling_face:

**Comment by EricEzaM** [comment]
From first glance this should be pretty easy to implement. Could be a good one for a new contributor...

I think you would start here to change the logic of the name generation after deleting one of the text boxes. 
https://github.com/godotengine/godot/blob/160ad23e5d07234e17032e8158ed48a2148fc668/editor/project_settings_editor.cpp#L151

https://github.com/godotengine/godot/blob/160ad23e5d07234e17032e8158ed48a2148fc668/editor/project_settings_editor.cpp#L197
