### ISSUE TITLE
Make inspector created nodepaths take the shortest route

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot-proposals#1546]
**Describe the project you are working on:**
Client-Server setup

**Describe the problem or limitation you are having in your project:**
In complex setups many dependencies have to be modelled using child nodes when doing it the godot way.
This leads to situations where configurations are done using nodepaths.
When using the ui to create those paths, moving nodes around etc. often times the auto-adjusted path does not take the shortest route, but instead goes through the parent property to access a target itself and then the desired child, like so
-Main
--Child
comes out as '../Main/Child' instead of 'Child' when set on Main

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Find the shortest route when adjusting the path internally. This will also minimize potential errors by excluding unecessary parts.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's part of the core system.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's part of the core system.

**Comment by KoBeWi** [comment]
This sounds more like a bug. If you have some reliable reproduction steps, you can fill a report on the main repository.

**Comment by Flavelius** [comment]
After trying to create a reproduction project it looks like this is related to drag-drop reparenting.
Here's a simple project that shows the result (ParentCopyMoved node -> testPath).
You can reproduce it by deleting the ParentCopyMoved node, duplicating the 'Parent' and dragging the duplicate below the original 'Parent'. The child reference of the moved Parent-duplicate will adjust to include the node-parent unnecessarily. Can you confirm this? Then i'll open an issue.
[NodePathRoute.zip](https://github.com/godotengine/godot-proposals/files/5260014/NodePathRoute.zip)

**Comment by KoBeWi** [comment]
Yeah this is a bug, but it was already reported: https://github.com/godotengine/godot/issues/35226
Also there's a PR open that fixes it.
