### ISSUE TITLE
Resource use report that displays use count and a list where the resource is being used

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [godotengine/godot-proposals#155]
**Describe the project you are working on:**

This proposal is not tied with a specific project

**Describe the problem or limitation you are having in your project:**

This proposal is not tied with a specific project

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

This proposal is not tied with a specific project

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

I have something even better. The same functionality but in a different tool (a mod content creator)
![file](https://user-images.githubusercontent.com/36826319/66725238-dce4c600-edfd-11e9-97c4-b243ea99d901.gif)

**Describe implementation detail for your proposal (in code), if possible:**

Each resource (files only for now) in the engine could be right clicked and then and in the right click context menu the last item is called "Use Info". When clicked it will show a Usage Report window that contains a list of locations where that object is being used (in scripts or nodes only for now). Double clicking on any entry will attempt to open that specific use case.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Could be an addon  although I think it could be faster and more efficient as a core addon.

**Comment by KoBeWi** [comment]
Did you actually try right-clicking a resource? There's an option called "View Owners" that already does what you describe.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@KoBeWi  What a strange naming . I would have never figured in 1000 years that "owners" means uses. It does fit the bill but it doesn't show total use count and doesn't show all use cases. Is mostly for tree uses and script uses.  

Turns out something like this exists just badly named feature.

**Comment by KoBeWi** [comment]
> It does fit the bill but it doesn't show total use count and doesn't show all use cases. Is mostly for tree uses and script uses.

You could create an improvement proposal for that.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@KoBeWi  I think is fine.  I think I could create an addon to improve on that functionality if is exposed to gdscript.
