### ISSUE TITLE
Print a warning message when importing a glTF file that references a specular/glossiness map

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#1553]
*See also https://github.com/godotengine/godot/issues/42235.*

**Describe the project you are working on:**

The Godot editor :slightly_smiling_face: 

**Describe the problem or limitation you are having in your project:**

Godot doesn't print a warning message when importing a specular/glossiness map from a glTF file. However, Godot does not support the specular/glossiness PBR workflow. It only supports the roughness/metallic workflow in the interest of simplicity and consistency.

An alternative would be to convert the specular/glossiness maps to roughness/metallic maps automatically when importing the textures. This sounds difficult to do in an accurate manner, though. Is there any literature on this?

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The glTF importer should print a warning message when importing a glTF file that either contains or references specular or glossiness maps.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

The warning message could be something along those lines:

> The glTF file "`<full path>`" contains a `<specular/glossiness>` map, but Godot only supports the roughness/metallic PBR workflow. Please convert the specular/glossiness maps to roughness/metallic maps and re-export the glTF file with the new textures referenced.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, as this is core import functionality. This is also about improving new users' experience with Godot.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is core import functionality.

**Comment by fire** [comment]
For reference: https://github.com/godotengine/godot/pull/38796

> Convert the specular/glossiness maps to roughness/metallic maps automatically
