### ISSUE TITLE
RichTextLabel: add ability to get text selection

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1558]
**Describe the project you are working on:**
gdscript editor plugins

**Describe the problem or limitation you are having in your project:**
RichTextLabel lacks `get_selection()` method.
It seems there is no way to get selection of text (selection start and end indices)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
`get_selection()` method

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It could return start and end indices, where the selection starts and ends in the text.

getting only text (using something like `get_selected_text()` method) could also be a convenient but less flexible solution, since there may be also a need for getting additional information about the selection (for example, get the line number where the selection begins or ends, etc.).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no it can't, since there's no api for working with selection at all (available in gdscript)

**Is there a reason why this should be core and not an add-on in the asset library?:**
not sure

**Comment by me2beats** [comment]
it might also be helpful to add a `selection_changed()` signal, not sure if it's worth creating a separate proposal

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/45899.

**Comment by Crystalwarrior** [comment]
> Fixed by [godotengine/godot#45899](https://github.com/godotengine/godot/pull/45899).

Any chance of this being backported to 3.5?
