### ISSUE TITLE
Make it possible to change the `.sln` and `.csproj` location in a project

### ISSUE THREAD

**Issue by n-tiz** [godotengine/godot-proposals#1575]
**Describe the project you are working on:**
Develloping a little game using C# to see limitations of the langage integration

**Describe the problem or limitation you are having in your project:**
I want to move all my scripts/sources in a directory, rather than be required to have the .sln and the .csproj in the root directory.
The name of the csproj is generated from "application/config/name" and the directory is "res://" (see in GodotSharpEditor.cs).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I think that it could be interesting to add a setting to override the sln/csproj location.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I dont know the engine code good enough to write code, but i think that the change will be done in GodotSharpEditor and it would replace:
`                string resourceDir = ProjectSettings.GlobalizePath("res://");`
By some code checking if the new csproj location setting is null, and if it's not, use its value rather than "res://".

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I dont think that it could be done by an add-on.

**Comment by Calinou** [comment]
> I think that it could be interesting to add a setting to override the sln/csproj location.

Can you explain some practical use cases for doing so?

**Comment by neikeq** [comment]
I think there's already another issue about this (can't search on phone), but in brief:
We won't allow moving `.sln` location. It will remain in the root directory next to `project.godot`.
I'll make it possible in 4.0 to change the csproj file location.

**Comment by GeorgeS2019** [comment]
@Calinou  

> Can you explain some practical use cases for doing so?

@neikeq 

> I think there's already another issue about this (can't search on phone), but in brief:

I attempted to discuss this issue here back in Aug 2020:
[Support multiple .NET5 SDK-style projects per Godot project](https://github.com/godotengine/godot-proposals/issues/1141#issuecomment-678607377)

**Comment by raulsntos** [comment]
There are now project settings to specify the .sln and .csproj directories as well as the assembly name. This was implemented by godotengine/godot#64089 (4.0) and godotengine/godot#64460 (3.6).
