### ISSUE TITLE
Allow hiding CanvasLayer nodes

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1578]
**Describe the project you are working on:**
Spaceship game

**Describe the problem or limitation you are having in your project:**
Can't seem to easily hide my parallax background node
![image](https://user-images.githubusercontent.com/2453707/94378922-e3894d80-00e1-11eb-97c0-bb59231d4942.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
allow us to hide the canvas layer node in the scene editor by toggling it or a parents visibility property

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
it would work like toggling visibility of any other node

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it would be used to turn off background for certain scenes

**Is there a reason why this should be core and not an add-on in the asset library?:**
its a pretty basic feature and to be honest I think its a massive oversight

**Comment by Calinou** [comment]
I suppose you can make the ParallaxBackground node a child of a Node2D as a workaround. It's like CanvasLayer and other nodes that inherit from CanvasItem instead of Node2D.

**Comment by Shadowblitz16** [comment]
@Calinou I actually did try that and its still visible

**Comment by KoBeWi** [comment]
Related:
https://github.com/godotengine/godot/issues/30059
https://github.com/godotengine/godot/issues/16532

**Comment by horatiohafnaugels** [comment]
> I suppose you can make the ParallaxBackground node a child of a Node2D (then hide that Node2D) as a workaround. It's like CanvasLayer and other nodes that inherit from CanvasItem instead of Node2D.

It doesn't work: for some reason the ParallaxBackground node is visible even when its parent is hidden.

**Comment by Shadowblitz16** [comment]
seems like I can't clip the parallax layer in a control either

**Comment by dalexeev** [comment]
Because `ParallaxBackground` inherits `CanvasLayer`, I think we need to add the `visible` property to the `CanvasLayer` class, not `ParallaxBackground`.

**Comment by Shadowblitz16** [comment]
> @Shadowblitz16 Could you edit the title and first post?

@dalexeev what do you want me to change about it?

**Comment by dalexeev** [comment]
"Allow hiding ParallaxBackground" → "Allow hiding CanvasLayer".

**Comment by Torguen** [comment]
When will we have this feature in Godot?

**Comment by KoBeWi** [comment]
When someone implements it ¯\\\_(ツ)_/¯
