### ISSUE TITLE
Add WebXR support

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot-proposals#1581]
**Describe the project you are working on:**

Various small VR experiences, that I'd like to distribute via the web.

**Describe the problem or limitation you are having in your project:**

Godot supports a number of VR and AR devices (with specific GDNative modules for each platform/device), but not WebXR!

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

WebXR is an open standard that works across devices, and has support for both VR and AR, making it a nice platform to target which gets you a lot of coverage at once (as opposed to having to use a different GDNative plugin for each platform/device.)

Also, in the same way that the HTML5 export is great for widely sharing small or hobbyist or game jam games, I think WebXR could help do the same thing for VR and AR games/apps.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

It will be a new 'webxr' module that adds a ARVRInterface when exporting to HTML5.

(I have a work-in-progress PR that I'll link here shortly.)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:**

There's only two ways to add new ARVRInterfaces, in core or via GDNative. However, this will only be used in the HTML5 export, and, unfortunately, the HTML5 export can't use GDNative. So, it has to be part of Godot core.

**Comment by akien-mga** [comment]
Closed by  godotengine/godot#44154 and godotengine/godot#42397.
