### ISSUE TITLE
Add an option to sort the editor's FileSystem dock by file type

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#1582]
**Describe the project you are working on:**
I'm currently working on a project, in which we're making a world with a lot of different animals, plants, etc. We recently decided to reorganize our Godot project, and instead of having one folder for scenes, one folder for sprites, and one folder for audiofiles (each with a folder for each entity in the world), we merged them together. That way everything that belongs to a single object in the world can be found in one folder. That feels a lot more organized and more efficient to work with.
But that is when I ran into a small inconvenience/problem.

**Describe the problem or limitation you are having in your project:**
As soon as I added .wav files, .pngs and .tscn files in a single folder, they organized themselves based on alphabetical order (as they should) in the filesystem. However, since all these files belong to a single entity, their names are very similar. After all, _bird.wav_ belongs to _bird.tscn_, with sprite _bird0.png_ and _bird1.png_.

![image](https://user-images.githubusercontent.com/10502115/94540346-a5f20500-0246-11eb-9b7f-84873a8b029f.png)

This makes the filesystem look quite unorganized and harder to read. I quickly went looking for a setting in the Editor settings to sort the filesystem by filetype, rather than by alphabetical order, but was surprised not to find such a feature.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Having a setting that can be changed to adjust the default sorting behaviour of Godot's Filesystem, would help a lot in this case. Sorting it in a way that has all the audiofiles next to each other makes it easier to implement them into a scene. And having all the scene files next to each other means you won't have to scour through a lot of other files to find them. All in all it would speed up the process of working in Godot (in this case, and similar cases).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
In my mind there are two options to implement a setting to allow the editor
a) A editor-wide setting in the editor settings that changes the behaviour of the default sorting of the Filesystem. Most likely in Editor Settings > Docks > Filesystem. 
![image](https://user-images.githubusercontent.com/10502115/94544541-a8a32900-024b-11eb-9f58-f107dd13959f.png)

A drop-down button with options such as 'Alphabetical' and 'By Filetype' would work.

b) A fancier way of implementing it would be to add a dropdown button at the top of the Filesystem, which can change the sorting method of the filesystem.

![image](https://user-images.githubusercontent.com/10502115/94543161-fae34a80-0249-11eb-890c-e59227bdca32.png)

That would allow more ease of access, which would likely make the feature used more often. Switching between sorting methods on the fly could be useful whenever you're looking for files of a specific type in a folder that is a bit too crowded, while allowing you to switch back to Alphabetical for folders that are less so.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Although adjustable sorting methods are practically a core feature in any filesystem, I was surprised to not find requests to add it to Godot, so I fear this isn't a priority for a lot of developers. And I would agree this is a lower priority request. Nothing is broken here, or NEEDS to be changed. But it would sure be useful to have, nonetheless. 

And I would love to presume how much work adding this feature is, but I have no clue, so I'll leave that up to people smarter than me.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This feature would be at the core of how an integral part of the engine works. I think it would most definitely be a core feature, and shouldn't be left as an add-on.

**Comment by Calinou** [comment]
I prefer the `b)` implementation, as it makes it much faster to switch between sorting by name and type.
