### ISSUE TITLE
In-viewport control of grid offset

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#159]
**Describe the project you are working on:**
2D game with non-tile-based world.

**Describe the problem or limitation you are having in your project:**
So XD My artist refuses to fit all the terrain art to a global grid. After putting the sprites in game, I have to make colliders for it. And it's horrible to work with.
![image](https://user-images.githubusercontent.com/2223172/66790194-147f6b00-eeef-11e9-8711-6a87dc4c8172.png)
Like, I need to make some surfaces flat, but I can't set a grid step that would work universally, so I have to change the offset for almost every vertex. And setting the offset is bothersome, because it's done in a dialog and you don't have any preview at all. It's mostly trial and error.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Would be cool if there was a shortcut to edit the offset without bringing the dialog, like dragging mouse with Ctrl + Shift pressed would move the grid along with the cursor, changing the offset, so it's easy to set, preview and all.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Sorry, too lazy to make a gif >_>

**Describe implementation detail for your proposal (in code), if possible:**
As I said, just a shortcut in Canvas Item editor that works with dragging. Maybe a separate tool, but that could be too much.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's impossible to access the grid via editor plugins.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, if the grid settings were exposed to scripting, I'd be fine with having it as an addon. Right now it's impossible.

**Comment by Xrayez** [comment]
Not really on topic but reminded me of godotengine/godot#19276 with snapping offset support. 😛

**Comment by Calinou** [comment]
I think having keyboard shortcuts to double/halve the grid size would be very useful too (in both 2D and 3D).

**Comment by KoBeWi** [comment]
Seems like there's low interest for this (I don't need this anymore either xd) so closing.
