### ISSUE TITLE
Allow ScrollContainer to be dragged from the inside with mouse inputs (right now it is touchscreen only)

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot-proposals#16]
I created an issue for it here: https://github.com/godotengine/godot/issues/31553

While using (emulate touch from mouse) is a work around, it does not work on HTML5 ( I think because touch inputs are converted to mouse inputs in HTML5?)

I propose that Dragging from the inside be either allowed or implemented to work with mouse input as well.
Also, an option to allow dragging from the inside that can be turned on/off in the inspector. Maybe called "scroll_drag"?

**Comment by reduz** [comment]
Please re-open this proposal using the new issue template.

**Comment by JustYourAverageJosh** [comment]
Ahh,  I didn't see this before: "Please refrain from opening proposals on this repository just yet,unless you are among the core contributors and discuss it beforehand." I'll wait until everything is set properly, sorry!
