### ISSUE TITLE
Being able to lightmap CSGShapes

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot-proposals#1600]
**Describe the project you are working on:**
Mobile 3D game

**Describe the problem or limitation you are having in your project:**
Can't lightmap CSGShapes.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Will be able to lightmap CSGShapes.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Wen you check "Use in baked light" in the 'GeometryInstance' section it gets lightmaped.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Don't think so, also performance.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Performance.

**Comment by Calinou** [comment]
This sounds more like a bug than a feature request to me.

**Comment by Janders1800** [comment]
I don't know, also can't lightmap meshinstances (cube, sphere, capsule, etc.)

**Comment by mrjustaguy** [comment]
Yeah I'd say it's more of a bug, as it isn't like it doesn't have the setting, instead the setting just doesn't do anything..

**Comment by Janders1800** [comment]
I've opened a bug report.
https://github.com/godotengine/godot/issues/42602

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/42602.
