### ISSUE TITLE
C++ Module integration in Godot for a connection with Arduino via Serial

### ISSUE THREAD

**Issue by threaderic** [godotengine/godot-proposals#1601]
**Describe the project you are working on:**
https://github.com/threaderic/GODOT_arduino

**Describe the problem or limitation you are having in your project:**
no possibility to connect Arduino to Godot

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
provide a module to copy under the module folder in Godot (tested version 3.1.2-stable and 3.2.3-stable)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
- Arduino side : 
create and send a message to Godot between <>
https://github.com/threaderic/GODOT_arduino/blob/41bbb42d520516e199e67bc260285f3a13183ce5/Arduino_code/Arduino_code.ino#L98
receiving message from Godot through the function  recvWithStartEndMarkers();
https://github.com/threaderic/GODOT_arduino/blob/41bbb42d520516e199e67bc260285f3a13183ce5/Arduino_code/Arduino_code.ino#L95
- Godot side :
declare Arduino connection
https://github.com/threaderic/GODOT_arduino/blob/41bbb42d520516e199e67bc260285f3a13183ce5/Godot_codes/example_2/Node.gd#L9
setup Serial connection to receive/send Arduino data
https://github.com/threaderic/GODOT_arduino/blob/41bbb42d520516e199e67bc260285f3a13183ce5/Godot_codes/example_2/Node.gd#L20
create a thread sending data to and from Arduino
https://github.com/threaderic/GODOT_arduino/blob/41bbb42d520516e199e67bc260285f3a13183ce5/Godot_codes/example_2/Node.gd#L21
received data from Arduino
https://github.com/threaderic/GODOT_arduino/blob/41bbb42d520516e199e67bc260285f3a13183ce5/Godot_codes/example_2/Node.gd#L41
send data to Arduino
https://github.com/threaderic/GODOT_arduino/blob/41bbb42d520516e199e67bc260285f3a13183ce5/Godot_codes/example_2/Node.gd#L55

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
the module can be used as is.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't know

**Comment by jonbonazza** [comment]
This sounds like it should be a gdnative plugin or 3rd party module. I dont think it belongs in core as it's pretty niche.

**Comment by Xrayez** [comment]
You're probably interested in asking this question to module and plugin makers community: #1476.

**Comment by Xrayez** [comment]
Oh sorry, I've misinterpreted the proposal. Do you suggest adding your module to `godot/modules` directly? The Godot development philosophy is to cater the most common use cases out of the box, and I think Arduino integration is not needed for *most* people who use Godot. Nonetheless, it doesn't mean that the module is not useful, on the contrary, you're encouraged to support this and describe possible problems that you stumble upon while making this.

I'm not sure whether you're aware of this, but Godot has an ability to compile external C++ modules with the `custom_modules` build option, so there's no need to copy the module contents directly under `godot/modules` for people to benefit from your module.

See [`Custom Modules`](https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html#custom-modules) documentation.

**Comment by threaderic** [comment]
Exact, one idea was to propose this functionnality integrated into the modules of Godot. I didn't know what is the policy of module's integration.
in fact, I just wanted to give the info of the possibility connecting arduino to Godot. Perhaps, I will also give this information to the arduino community. If my work could help others ! I take the opportunity to thanks all Godot developpers ! Godot is a really good software, well documentated ! 
I clicked to your link https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html#custom-modules. Interesting ! Is there a place where all custom modules (or links to custom modules) are listed /indicated ? As said, for the number of users, It would be sufficient.
Thanks for your comments !

**Comment by Calinou** [comment]
> Interesting ! Is there a place where all custom modules (or links to custom modules) are listed /indicated ? As said, for the number of users, It would be sufficient.

Yes: https://github.com/godotengine/awesome-godot

Anyway, I'll close your proposal as this feature is better maintained as a third-party module.

**Comment by Xrayez** [comment]
@threaderic you can assign [`godot-modules`](https://github.com/topics/godot-module) GitHub topic in your repository as well (modify "About" section). 🙂

**Comment by threaderic** [comment]
@Xrayez  Done ! thanks for this tip
