### ISSUE TITLE
Allow to create custom more complex nodes

### ISSUE THREAD

**Issue by crisestudio** [godotengine/godot-proposals#1606]
**Describe the project you are working on:**
2D fighter

**Describe the problem or limitation you are having in your project:**
It's very bothersome to not be able to create quickly new custom nodes to reuse scenes between projects/levels and upload them to the asset store so can be used by others or reused by myself.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Allow to create custom nodes easily, improve the export keyword functionality, so It can be used to create custom interfaces in a scene, which you can later save as a single node, but in reality is just a scene made from basic nodes.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Allow the root node to have some script with export variables, that allow to create a custom interface, similar to unity component system (which is just an interface of inner nodes), allowing for reusal of scenes between users/projects, and allow it to be uploaded to the asset store.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, requires some improvements to the export keyword.

**Is there a reason why this should be core and not an add-on in the asset library?:**
No, It's a core editor issue to export to the asset library.

**Comment by KoBeWi** [comment]
This is already possible. You can add a tool script to a scene, which can modify children nodes dynamically based on inpsector actions.

Although you can't make it into a single class without something like https://github.com/godotengine/godot/issues/21187 Or actually you can, but you need to create the whole scene from scrip. It's perfectly possible, but you can't tweak the scene visually in the editor. Something like https://github.com/godotengine/godot/issues/26552 could be useful too.

**Comment by Calinou** [comment]
Closing per KoBeWi's comment.
