### ISSUE TITLE
Add touch control to editor

### ISSUE THREAD

**Issue by cewbdex** [godotengine/godot-proposals#161]
**Describe the project you are working on:**

N/A

**Describe the problem or limitation you are having in your project:**

Can't use touch properly in Godot editor.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

I will be able to work without mouse better on the go, touchpad is not the most productive, touchscreen is just better. Implementing 3D view control and scrolling with finger would be nice.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**

N/A

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**

N/A

**Comment by Calinou** [comment]
Godot supports touchscreen input events, so this should be relatively easy to implement. We also need to add support for scrolling TextEdit and scrollable controls to make the script editor more usable.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2295 as it's more specific.
