### ISSUE TITLE
Rename "Windows Desktop" to "Windoes Desktop (EXE)" in export templates

### ISSUE THREAD

**Issue by droc101** [godotengine/godot-proposals#1610]
**Describe the project you are working on:**
Just any old game.

**Describe the problem or limitation you are having in your project:**
I always get confused between the Windows Desktop and Windows Universal export templates

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add "(EXE)" to the end of the "Windows Universal" export template. This will help me know what template to add.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Change the name of the Windows Desktop export template to Windows Desktop (EXE)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not that I know of.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it is an Export Template

**Comment by Calinou** [comment]
"Windows Universal" was renamed to "UWP" in 4.0. I believe this solves the issue at hand.

**Comment by droc101** [comment]
Yes, It does. Thank you for making me aware of this.
