### ISSUE TITLE
Big Sur compatible new macOS app icon proposal

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot-proposals#1616]
**Describe the project you are working on:**
Big Sur compatible new macOS app icon,

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Big Sur compatible new macOS app icon

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
<img width="512" alt="godot1" src="https://user-images.githubusercontent.com/36481442/100390451-75a9c580-3041-11eb-8313-2f23c1ee2903.png">
<img width="512" alt="godot2" src="https://user-images.githubusercontent.com/36481442/100390458-79d5e300-3041-11eb-9a3a-43074ee52ad5.png">

I uploaded this to https://macosicons.com/, if you search for "godot" you will see.

**Comment by Calinou** [comment]
Does Big Sur *require* new icons, or is this just a renewed design that better fits new Apple visual guidelines? If so, could you link to such guidelines?

**Comment by hazarek** [comment]
> Does Big Sur _require_ new icons (like Android adaptive icons), or is this just a renewed design that better fits new Apple visual guidelines? If so, could you link to such guidelines?
> 
> We'd prefer keeping the same icon on all platforms for consistency's sake. Therefore, if we change the icon on one platform, we would change it on all platforms.

It's just cosmetic compatibility for new Big Sur icons, I don't think it has to be the same across all platforms. all icons are box-shaped. for more info https://github.com/elrumo/macOS_Big_Sur_icons_replacements

**Comment by PabloNeirotti** [comment]
I know this isn't the official stance based on what @Calinou wrote, but I'd like to respectfully disagree.

The Godot icon sticks out like an eyesore in an otherwise neatly array of icons in the macOS dock or launchpad. It will become more evident as more apps get updated and Godot stays behind.

I think the icon should follow the OS guidelines as much as possible so it fits at home. I'd say the same about the UI but that's a lot more work.

Keeping consistency can be done from the projects side, or the users side. In the case of the icon, I think the user experience should be prioritized over the project identity enforcement. I do not think it's detrimental to Godot's identity to adapt its icon to the host OS, nor it would be confusing for users in any way if this was the case, for whoever actually develops on two different OSs at the same time.

I can whip out a Godot icon that looks like it was made by Apple itself in a few minutes if that's the issue.

Not sure if the decision is made by a Mac user, but I hope we are taken into account.

Thank you!

**Comment by hazarek** [comment]
@PabloNeirotti 
I uploaded this to https://macosicons.com/, if you search for "godot" you will see.
The icons here have the wrong corners.

**Comment by Calinou** [comment]
@PabloNeirotti Since so many applications seem to be adopting Big Sur-friendly icons these days, I think it makes sense to change Godot's icon now.

**Comment by PabloNeirotti** [comment]
Sweet!

Pablo Neirotti

**Comment by bruvzg** [comment]
Note: changing `.icns` in the `.app` bundle will change icon in the Finder, but not the dock icon while Godot is running, for this you'll need to change `main/app_icon.png` and rebuild the engine.

**Comment by hazarek** [comment]
> Personally, I prefer the second icon suggestion (the one with the light outline).

me too

**Comment by PabloNeirotti** [comment]
I like this one, not sure if it's the same you guys are talking about:

![Screen Shot 2020-11-26 at 6 03 13 PM](https://user-images.githubusercontent.com/905216/100391274-aa9e2400-3011-11eb-9930-610f09713a63.png)

The one with lines does not really follow the Big Sur style, primarily due to that outline on the box. Is it the outline on the logo that you like?

**Comment by Calinou** [comment]
> Screen Shot 2020-11-26 at 6 03 13 PM

The one with lines does not really follow the Big Sur style, primarily due to that outline on the box. Is it the outline on the logo that you like?

Yes, I think the outline helps it stand out a bit more.

**Comment by PabloNeirotti** [comment]
@Calinou Oh I agree with that. I can make some variations as well so I'm not just an armchair designer lol. Be back in a bit.

**Comment by hazarek** [comment]
I can update new ones for godot if you want.

**Comment by hazarek** [comment]
lines can be used.
<img width="127" alt="Ekran Resmi 2020-11-27 00 11 52" src="https://user-images.githubusercontent.com/36481442/100391657-2e253880-3045-11eb-90c4-5b03431db606.png">

**Comment by PabloNeirotti** [comment]
@hazarek I mean yes, although the function is to resemble a device in that case. In the case of containing an object (i.e a logo) the container serves as a backdrop and is typically flat or a gradient.

That's why stuff like Dictionary and Contacts have an emboss effect (they are books!), however those that contain objects (i.e: Pages, Numbers, Keynote, Mail, Music, Messages) have a flat-like backdrop instead.

**Comment by hazarek** [comment]
better contrast
![godotalt](https://user-images.githubusercontent.com/36481442/100391965-27e38c00-3046-11eb-942e-bdc85bb43cfb.png)

**Comment by PabloNeirotti** [comment]
Alright, I had a go at it.

I don't know whether the icon having an outline is important for the identity or not, although it does help bring together the idea of "the jaw being separated from the rest of the head".

<img width="512" alt="Godot Icon Test" src="https://user-images.githubusercontent.com/905216/100392258-b4755680-3014-11eb-9823-8565093cb0c9.png">

**Comment by Calinou** [comment]
> I don't know whether the icon having an outline is important for the identity or not, although it does help bring together the idea of "the jaw being separated from the rest of the head".

I think it's nice to have, but it's not essential per se.

**Comment by hazarek** [comment]
It should look good in a dark and bright background. Consider this too.

**Comment by PabloNeirotti** [comment]
@hazarek Indeed. The backdrop is similar to the one Mail has, except that I think it's slightly more "Godot blue". The gradient automatically makes it pop in either dark or white backgrounds.

<img width="768" alt="Screen Shot 2020-11-26 at 6 32 12 PM" src="https://user-images.githubusercontent.com/905216/100392563-bab80280-3015-11eb-82f1-f4c6b38d89b0.png">

**Comment by hazarek** [comment]
@PabloNeirotti your icon tool low contrast. mail icon with worst design along with safari.

**Comment by hazarek** [comment]
experimental 😆 
![godot_solid](https://user-images.githubusercontent.com/36481442/100393646-629bf300-304b-11eb-896a-7459ca476582.png)

**Comment by bruvzg** [comment]
Light blue logo is blending with blue background a bit too much, especially at smaller icon sizes, consider using light background too.

Few of my variants (along with badges for #541, and only using colors form official website design from [website_design.svg](https://github.com/godotengine/godot-design/blob/master/websites/website_design.svg)): [Godot.svg.zip](https://github.com/godotengine/godot-proposals/files/5607906/Godot.svg.zip)

![GodotIcons](https://user-images.githubusercontent.com/7645683/100451476-2bb3f480-30c0-11eb-98f1-5f8a40772b06.png)

Or maybe the same but without white outline on the logo (like https://github.com/godotengine/godot-proposals/issues/1616#issuecomment-734481093 but with gray background)?

**Comment by hazarek** [comment]
white background looks bad on macos darkmode, but dark background always looks good

**Comment by hazarek** [comment]
her eyes are not the same color everywhere.
<img width="947" alt="Ekran Resmi 2020-11-27 17 42 45" src="https://user-images.githubusercontent.com/36481442/100460291-fc10e680-30d7-11eb-8890-5ac087ba70b5.png">

#333F67 --> https://github.com/godotengine/godot-design/blob/master/websites/website_design.svg
#414042 --> https://commons.wikimedia.org/wiki/File:Godot_icon.svg

**Comment by hazarek** [comment]
<img width="503" alt="Ekran Resmi 2020-11-27 17 54 08" src="https://user-images.githubusercontent.com/36481442/100461254-9887b880-30d9-11eb-8800-776e39856106.png">

![aa](https://user-images.githubusercontent.com/36481442/100461298-a9382e80-30d9-11eb-9537-bf2b41888cbb.png)

**Comment by bryanrieger** [comment]
> The Godot icon sticks out like an eyesore in an otherwise neatly array of icons in the macOS dock or launchpad. It will become more evident as more apps get updated and Godot stays behind.
> 
> I think the icon should follow the OS guidelines as much as possible so it fits at home. I'd say the same about the UI but that's a lot more work.
> 
> Keeping consistency can be done from the projects side, or the users side. In the case of the icon, I think the user experience should be prioritized over the project identity enforcement. I do not think it's detrimental to Godot's identity to adapt its icon to the host OS, nor it would be confusing for users in any way if this was the case, for whoever actually develops on two different OSs at the same time.
> 
> I can whip out a Godot icon that looks like it was made by Apple itself in a few minutes if that's the issue.
> 
> Not sure if the decision is made by a Mac user, but I hope we are taken into account.

While waiting for a new Big Sur Godot icon, is it possible to change icon of the Godot app itself on macOS (to be more consistent with other apps) in the meantime? I've tried the usual ways; copy/paste in the Get Info window, replace the Godot.icns file in Godot.app/Contents/Resources/Godot.icns, but everytime I launch Godot the default app icon is still used.

Many macOS users will regularly change icons to suit their preferences, but currently this is not possible in the usual ways with Godot.

**Comment by Calinou** [comment]
> but everytime I launch Godot the default app icon is still used.

If macOS works like Linux on this aspect, the app icon displayed in the Dock is not the same as the app icon displayed in its title bar.

**Comment by bruvzg** [comment]
> If macOS works like Linux and Windows on this aspect, the app icon displayed in the Dock is not the same as the app icon displayed in its title bar. The app icon in the title bar is set by Godot itself and is hardcoded in the binary.

It is the case, Godot is setting Dock icon form the [embedded PNG](https://github.com/godotengine/godot/blob/master/main/app_icon.png) on start.

**Comment by Calinou** [comment]
@hazarek The one with the dark gray background looks pretty good, do you have an ICNS file for it (and ideally also a SVG file or another source format)?

**Comment by bryanrieger** [comment]
> > If macOS works like Linux and Windows on this aspect, the app icon displayed in the Dock is not the same as the app icon displayed in its title bar. The app icon in the title bar is set by Godot itself and is hardcoded in the binary.
> 
> It is the case, Godot is setting Dock icon form the [embedded PNG](https://github.com/godotengine/godot/blob/master/main/app_icon.png) on start.

Is there any possibility of not having Godot set the dock icon from the embedded PNG on start, to allow macOS users to change the icon themselves without having to compile Godot from source?

**Comment by Calinou** [comment]
> Is there any possibility of not having Godot set the dock icon from the embedded PNG on start, to allow macOS users to change the icon themselves without having to compile Godot from source?

The dock icon is in ICNS format, and the title bar icon only accepts PNG files.

**Comment by hazarek** [comment]
> @hazarek The icon with the dark gray background looks pretty good! Do you have an ICNS file for it (and ideally also a SVG file or another source format)?

i don't have source format for grey version
gray background ICNS - https://disk.yandex.com.tr/d/uLw9AdWLJ2sXDA
PDF files for blue background - https://disk.yandex.com.tr/d/3F0t7EbRNOXvtw?w=1

**Comment by bruvzg** [comment]
In case anyone needs it, here are some of my icon variants (source Inkscape `SVG` + `PNG`s + `ICNS`s + conversion scripts), including a few with the similar raised gray background: [Godot32.zip](https://github.com/godotengine/godot-proposals/files/6461143/Godot32.zip)

![Godot32](https://user-images.githubusercontent.com/7645683/117863438-730ff500-b29c-11eb-857b-a52c42b89dd4.png)

Personally I prefer dark blue background over the gray one.

**Comment by bruvzg** [comment]
> with the following patch Godot will always use ICNS from the bundle (or icon set be user via Get Info):

Proper changes to use bundle/use set icons instead of default (checks if running from a bundle and bundle icon exists).

4.x - https://github.com/godotengine/godot/pull/48685
3.x - https://github.com/godotengine/godot/pull/48686
