### ISSUE TITLE
Android ability to display game along the notch.

### ISSUE THREAD

**Issue by rmichaluszek** [godotengine/godot-proposals#1622]
**Describe the project you are working on:**

Im working on a mobile game

**Describe the problem or limitation you are having in your project:**

that would like to be shown in real full screen, but the sides along the notch are just black, I would like to show my game in these places too.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Some property in the project settings under the android, for example support notch true/false or something like that would be really useful, because there are a lot of phones now that have notches.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

It would just (probably) modify the manifest file, but i dont know how actually because i tried to do this manually and none of manifest properties worked for me to show the game along the notches.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

I encountered a lot of posts on different portals about this, and there are no answears or fixes for this problem yet.
eg: [link](https://godotengine.org/qa/56785/hide-security-zone-android-better-full-screen-display-effects)

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by facciocose** [comment]
I think the post linked has an updated answer that solves this issue.

Using custom build system you can override the default android theme and add `android:windowLayoutInDisplayCutoutMode`.

**Comment by kyoz** [comment]
Confirm, the guide in the post work for me. Tried on a few phones

**Comment by Calinou** [comment]
Is this implemented in 3.3 now when immersive mode is enabled? Judging by [this Q&A question](https://godotengine.org/qa/102235/immersive-mode-in-android-covers-notification-bar), the game now seems to display behind the notch by default.

**Comment by kyoz** [comment]
@Calinou I'v just tried Godot 3.3. Yes, it is implemented, i no longer need custom android build.

**Comment by GForceProductions** [comment]
What if I don't want to display behind the notch? Both Android and iOS.
I am using stretch mode viewport and ignore aspect ratio, and want to stretch it to the screen size without the notch and bars on its sides.
Because now it will stretch to the entire screen including notch, and part of the app falls behind the notch and is not visible, which is rather annoying

**Comment by Calinou** [comment]
@GForceProductions You can use `OS.get_window_safe_area()` which returns the area of the screen not hidden by the notch. Use the return value to move UI elements so they don't appear behind the notch.

Alternatively, add some margin on all sides to prevent UI elements from being placed behind the notch (or otherwise being too close to it).

**Comment by GForceProductions** [comment]
@Calinou Thank you for the reply and suggestion.
I am wondering if it is also possible to let the engine disregard that area completely?
Because reading the issue it sounds like that is how it used to be?

**Comment by Calinou** [comment]
> @Calinou Thank you for the reply and suggestion.
> I am wondering if it is also possible to let the engine disregard that area completely?
> Because reading the issue it sounds like that is how it used to be?

There doesn't appear to be a built-in way to do this anymore (on iOS at least). See also https://github.com/godotengine/godot/issues/49887.

**Comment by GForceProductions** [comment]
Ok thank you!
