### ISSUE TITLE
Add Alerts when In-AnimationTree loads fail

### ISSUE THREAD

**Issue by kingoftheconnors** [godotengine/godot-proposals#1624]
**Describe the project you are working on:**
A 2D platformer heavy on animations. The current system uses a state machine with 1D blend spaces to balance over 40 animations.

**Describe the problem or limitation you are having in your project:**
When trying to move my state machine into a blend-tree using the save and load features, I missed something up and the save created a corrupted .tres file. Thankfully I was careful and kept the old state machine in an archive file. BUT my main confusion was when trying to use this (unknowningly) flawed tres file:

When load is attempted, _**it fails silently**_:

![image](https://user-images.githubusercontent.com/23728939/95400029-9b371000-08d7-11eb-84f9-8bf552cb71f2.png)

![silentfail](https://user-images.githubusercontent.com/23728939/95400775-7fcd0480-08d9-11eb-9332-5df10f561c60.gif)

<br>

**Describe the feature/enhancement and how it helps to overcome the problem or limitation:**

The editors for these nodes don't throw an alert when isValid() returns false. The simple solution is to add an alert. The text would be similar to another alert used in the same process (but when copying in a playback node instead of loading it):

![image](https://user-images.githubusercontent.com/23728939/95400377-6f685a00-08d8-11eb-9a08-f3c1523412ae.png)

With this, users will know when their attempted import is of an illegal file type, or of a corrupted file.

<br>

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Nothing happens when a loaded file fails the isValid() check. To add an alert, we simply have to add an else clause with an alert:

![image](https://user-images.githubusercontent.com/23728939/95400521-c79f5c00-08d8-11eb-95e9-219da644172e.png)

This needs to be done in the code on both 1D and 2D blend spaces, the blend tree, and the state machine.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This is a minor fix to increase godot's intuitiveness by giving the user accurate feedback. Users won't know it's a problem until after they've wasted time on it, and there's very little that can be done afterwards.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Alerts like this are in the interest of users. They improve the UI, and this one is an extremely lightweight addition.

**Comment by EricEzaM** [comment]
Related to #1489

**Comment by Calinou** [comment]
@kingoftheconnors Feel free to open a pull request for this :slightly_smiling_face:
