### ISSUE TITLE
Add Get File Icon to Directory

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#1627]
**Describe the project you are working on:**
Various workflow tools

**Describe the problem or limitation you are having in your project:**
when using the Directory, unable to get the file icon that windows is using.
For example, let's say I've got a directory with shortcuts to blender, gimp and some other files..
I have the correct file path to all of the said files, and I want to add them to an Item List with icons..
I can get the Names just fine, but getting the icons to go along with the files? Not really, unless I manually find the Blender Icon and Gimp Icon and any other File Icons beforehand and feed it into the build

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
By just having a function that get's the icon the OS is displaying and using that outputs the Icon, it would be easy to list out what a directory has with icons to make searching for stuff easier and the UX better.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
When Directory has a file/folder of any kind, if function "get_file_icon()" is used on the directory/file:
1. Get file Path
2. Get file properties
3. Find from where the file is getting it's icon
4. Attempt to get and load the icon from where the file is getting it's icon
5. Return icon or null if icon cannot be found

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not really, the easiest way is to get the icons manually for all the needed files, but that isn't procedurally able to get all the icons from a folder if new things are added to it.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Directory is core, and the addition should be a part of it, as it can be used for tool managers, modding tools and other similar applications

**Comment by Calinou** [comment]
> when using the Directory, unable to get the file icon that windows is using.

The preview displayed by the file manager is an OS-specific thing. On some OSes like Linux, it might even vary depending on which file manager and icon theme you're using.

**Comment by mrjustaguy** [comment]
Closing due to lack of interest and acceptable workarounds have been found (avoid using icons)
