### ISSUE TITLE
New Keyword: "matchset"

### ISSUE THREAD

**Issue by LotsaBugs** [godotengine/godot-proposals#163]
**Describe the project you are working on:**
A card game (N/A)

**Describe the problem or limitation you are having in your project:**
Setting a variable using a match or if statement requires pasting the variable name multiple times.
(Ternary operations only allow 2 values, so it's not a solution.)

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Adding a _matchset_ type of functionality would reduce the amount of code required.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
(_matchset_ should be highlighted red (keyword))
(_value_ and _result_ should all be highlighted another color (inherent local variables)) 
![matchset keyword example](https://user-images.githubusercontent.com/52873190/67016884-e2127f80-f133-11e9-83c4-418fd45ebf80.png)

As you can see, I didn't have to keep writing "__msg = " or "__offset = " in the proposed change.

**Describe implementation detail for your proposal (in code), if possible:**
_matchset_ would take 3 arguments (_variable_to_match_, _variable_to_set_, _value_to_be_set_= _result)_
The built-in _matchset_ function should have an inherent variable, _result_, which is what you are defining on the right side of the colons in the match statement, and is automatically returned.
Also, _value_ should be an inherent variable that is set to the 2nd argument, so you can just use _value_ to refer to it instead of writing the variable name again.

The 3rd argument should be optional, and should default to the match _result_.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This would be used often by anyone who uses match statements to set a variable.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This wouldn't work as an add-on.

**Comment by arkology** [comment]
For the shown mock-ups, you can simply use dictionaries, which in this case will be much more convenient.

**Comment by bojidar-bg** [comment]
Wouldn't it be better to have `match` expressions which return a value?
That way, no new keywords or strange syntax would have to be added.
Example:
```gdscript
func test(x):
  var result = match x:
    "jump":
      Vector2(0, 16)
    "right":
      Vector2(6, 0)
    "left":
      Vector2(-6, 0)
    _:
      assert(false)
      Vector2() # Needed so that the whole match expression results in Vector2() and is not untyped
```

The example I wrote can already be done with dictionaries though:
```gdscript
func test(x):
  var result = {
    "jump": Vector2(0, 16),
    "right": Vector2(6, 0),
    "left": Vector2(-6, 0)
  }[x] # or .get(x, Vector2()) to have a default value
```

**Comment by LotsaBugs** [comment]
Yes, you guys are right.
A dictionary would be a fine solution for this. 
Thanks for your input, and sorry for the trouble.
