### ISSUE TITLE
Scene Scope Node

### ISSUE THREAD

**Issue by colorworlds** [godotengine/godot-proposals#1633]
**Describe the project you are working on:**
A small multi player RPG game  

**Describe the problem or limitation you are having in your project:**
I use a `GlobalManagement` node to manage the behavior of all things. For example, users need to notify this node when they log in or move. Almost all things need to access this node and take this node as its parent node.    
However, if I load this node automatically as a global Singleton, it seems that all the original child nodes on `GlobalManagement` node a will also become an autoload nodes,because they have an autoload singleton parent.   
This doesn't look right.   
So in the script for each node, I use the  `$'/root/GlobalManagement'` to get the GlobalManagement node.   
But it looks like repetitive code that can be omitted by having the editor generate code.   
The child node can omit path lookup such as $'../...' or $'/root/...' to obtain the parent node.
If the path is maintained manually, once the node structure changes, a lot of code needs to be changed.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Let the editor add the concept of a Scene Scope Node.   
1.In a scene, a scene scope node can be registered in all scripts directly belonging to the official node of the scene. 
  
For example:  
GlobalManagement.tscn  
```
node tree structure： 
--GlobalManagement  +GlobalManagement.gd  
----Player1  +Player.gd  
----Plyaer2  +Player.gd  
```  

GlobalManagement.gd
```
# scene scope node must be a official node
extends Node2D
# Register scene scope node GlobalManagement
register_scene_node GlobalManagement
# a func
func globel_timer():
    pass
```
Player.gd
```
# path lookup is omitted
# $'root/GlobalManagement'
# I can use the GlobalManagement node directly
GlobalManagement.globel_timer()
```

2.The scene scope nodes contained in the nodes instantiated by the custom scene are not visible to the outside scene.

For example:
Player.gd
```
# Register scene node player node
register_scene_node  Player
# define a func
func move():
    pass
```
GlobalManagement.gd
```
# The player node cannot be accessed in GlobalManagement.gd script
Player.move() # error
```

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I think it can be implemented using code generation techniques similar to connection signals.

  
1.In a scene, only the script on the official node can register a scene scope node, such as node, node2d, area2d, etc  

The nodes generated by scene instantiation can have their own scene scope nodes, but they cannot be seen from the outside.

2.All nodes in a scene, including those generated by scene instantiation, can access the registered scene scope nodes.  

Therefore, the editor needs to get the registered node, and then write its node path to the script of all child nodes in the scene to which it belongs.

3.All newly added scripts in the scene can also access the registered scene scope nodes.  

4.If the node path of the node registered as the scene scope changes, the scene acting on the node generated by all nodes in the scene can be automatically updated.  

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
**Sure.**
This is just a suggestion similar to grammar sugar

**Is there a reason why this should be core and not an add-on in the asset library?:**
Need editor, even gdscript  support

**Comment by KoBeWi** [comment]
Not sure if I understood correctly, but isn't it almost the same as `Node.owner`?

**Comment by colorworlds** [comment]
> Not sure if I understood correctly, but isn't it almost the same as `Node.owner`?

What I want to express is more like a global singleton whose scope is limited by the scene.  `Node.owner` seems to be related to scene storage,Maybe there's a mistake or something I don't know about?

**Comment by KoBeWi** [comment]
When you instance a scene, all children nodes have their `owner` set to the root of the instanced scene. So e.g. when you have Player scene, its children nodes' `owner` will point to the Player node.

**Comment by colorworlds** [comment]
> When you instance a scene, all children nodes have their `owner` set to the root of the instanced scene. So e.g. when you have Player scene, its children nodes' `owner` will point to the Player node.

Yes, it seems that the functions are very similar, but the `owner` can only access the root node. Sometimes I may want to access some other nodes in the same scene, such as Player node access GlobalManagement/UI node. This is very common. In general ,This proposal is only a simplification, not urgent.

**Comment by dalexeev** [comment]
> it seems that all the original child nodes on `GlobalManagement` node a will also become an autoload nodes,because they have an autoload singleton parent.
> This doesn't look right.

No, this is absolutely correct.

> So in the script for each node, I use the `$'/root/GlobalManagement'` to get the GlobalManagement node.
> But it looks like repetitive code that can be omitted by having the editor generate code.

You can simply use `GlobalManagement` if you haven't unchecked the Singleton checkbox in the Project Settings.

**Comment by colorworlds** [comment]
> > it seems that all the original child nodes on `GlobalManagement` node a will also become an autoload nodes,because they have an autoload singleton parent.
> > This doesn't look right.
> 
> No, it is absolutely correct that the autoload child nodes are not unloaded.
> 
> > So in the script for each node, I use the `$'/root/GlobalManagement'` to get the GlobalManagement node.
> > But it looks like repetitive code that can be omitted by having the editor generate code.
> 
> You can simply use `GlobalManagement` if you haven't unchecked the Singleton checkbox in the Project Settings.
> 
> ![](https://user-images.githubusercontent.com/47700418/95567814-1c072080-0a2c-11eb-9322-f09960d36b92.png)

I think if the game is big enough, it may be a problem to load the whole game into memory at once. Therefore, I didn't use `Autoload` to load the whole game when designing my game. However, I'm just a novice and don't have much experience about game development. So maybe I made a mistake.
Anyway, I feel this proposal can reduce the amount of code related to node search.

**Comment by dalexeev** [comment]
> I think if the game is big enough, it may be a problem to load the whole game into memory at once. Therefore, I didn't use `Autoload` to load the whole game when designing my game.

You can create GlobalManagement singleton using autoload. In this case, you will be able to use the `GlobalManagement` globally instead of typing `$'/root/GlobalManagement'` every time.

**Comment by colorworlds** [comment]
> You can create GlobalManagement singleton using autoload. In this case, you will be able to use the `GlobalManagement` globally instead of typing `$'/root/GlobalManagement'` every time.

I'm sorry for the late reply.  
Yes, you're right. I realize my error.  Thank you very much for your correction.
 However, in some situations, I feel that this function is still useful. For example, a game set containing multiple small games ,at this time, every small game may have its own `Management ` node, but not all  `Management`  nodes need to autoload at once.
