### ISSUE TITLE
Remove list of projects from `editor_settings-4.tres` for easier settings synchronization across devices

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-proposals#1637]
**Describe the project you are working on:**

Any.

**Describe the problem or limitation you are having in your project:**

I'd like to store Godot's editor configuration in a dotfiles repository, so I
can track changes and sync settings between machines.

Unlike all other fields in `editor_settings-*.tres`, which change when I edit
things in the "Editor Settings", the `projects` field changes automatically as
I add or remove projects. This causes unnecessary churn to the tracked file,
and persists settings that aren't relevant across machines (I might not have
all the same projects on my laptop, or at the same locations).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Store the projects list in $XDG_DATA_HOME rather than $XDG_CONFIG_HOME. It is data, not configuration.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

1. Remove `projects` from `EditorSettings`
2. Write/read `projects` from a file under the "User data" path (a simple .txt would suffice, but it could be .tres or something else)
3. (optional migration) If `projects` is present in `editor_settings-3.tres`, extract it to the data path.

I think 3 is not necessary if this is a 4.0-only feature, but could be convinced otherwise.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It is core to how Godot persists data.

**Comment by Calinou** [comment]
> Write/read projects from a file under the "User data" path (a simple .txt would suffice, but it could be .tres or something else)

The [ConfigFile](https://docs.godotengine.org/en/latest/classes/class_configfile.html) class is likely a more developer-friendly approach.

**Comment by Xrayez** [comment]
I do store common editor settings at GitHub as seen in https://github.com/Xrayez/godot-editor-settings, but not necessarily for *synchronization* purposes. I had to manually strip out all default settings from there, including projects. This still works for me because all other settings are populated upon running Godot again.

**Comment by rcorre** [comment]
@Xrayez I assume that means you have to be really deliberate about commiting changes, right? As soon as you load godot, are all the pre-populated changes written back to your file?

**Comment by Xrayez** [comment]
@rcorre yes, all the settings which are manually set won't be overwritten by loading Godot. Config comments will be lost, though.

> have to be really deliberate about commiting changes, right

Yes, this kind of approach is only useful for initial setups, and not sync. This could also work for "sync" purposes across machines if you don't need to change editor settings often. But it also means that your dotfiles repository will appear dirty, so this is likely not useful for your use case. I'm just describing the way I use it myself. 🙂

**Comment by rcorre** [comment]
I noticed `~/.config/godot/recent_dirs` is also written to the config dir. It isn't as big a deal, since you can ignore the whole file, but would it make sense to move that to `~/.local/share/godot` as well? It feels like state, not configuration.

**Comment by Calinou** [comment]
> I noticed `~/.config/godot/recent_dirs` is also written to the config dir. It isn't as big a deal, since you can ignore the whole file, but would it make sense to move that to `~/.local/share/godot` as well (or even `~/.cache/godot`)? It feels like state, not configuration.

I think it makes sense to move the recent dirs to `~/.local/share/godot/` too.

**Comment by rcorre** [comment]
Actually, `favorite_dirs` also writes to `~/.config`, and that is arguably _more_ config-like since it only changes due to an explicit action by the user. It feels weird to separate those two, so maybe we should leave them both in `~/.config`, and just `.gitignore` `recent_dirs` if you want to version-control dotfiles?

**Comment by Calinou** [comment]
> Actually, `favorite_dirs` also writes to `~/.config`, and that is arguably _more_ config-like since it only changes due to an explicit action by the user. It feels weird to separate those two, so maybe we should leave them both in `~/.config`, and just `.gitignore` `recent_dirs` if you want to version-control dotfiles?

That's fine by me too, I don't think there is a strong winner here.
