### ISSUE TITLE
Suggestions to improve visual script

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1638]
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
I wish visual script, would be even more competent, and geared towards visual minded coders, or artists, as well as being very powerful, for ordinary coders . . I wanted to suggest we get an option, to have rounded ' headers ', for graph nodes, so it looks similar, to Blender, which is a very friendly, and easy look, for making visual shaders, or so . .

![2020-10-09 0632](https://user-images.githubusercontent.com/61069740/95543584-37a50380-09f9-11eb-9294-d32972dccf5f.jpg)

However, I also think adding an option, to have a lower panel, that looks like this, would be really helpful, to visual coders, since they prefer to ' see ' what they're doing, and not so much use menus, ie. everything happens, in the script canvas, where possible . . So, here's an improved version, of an old suggestion, for visual script, boxes that look, like this . .

![2020-07-06 0242](https://user-images.githubusercontent.com/61069740/95543641-61f6c100-09f9-11eb-8365-5054d74f621b.jpg)

I also think we need a button, so we can toggle boxes to be visible, semi-visible, near-invisible, or so . . All this could be done, in an expandable lower panel, on each box, with some icons, for quickly accessing the nodes more ' expanded ' functions, or methods . . imo, visual script is already 95 %, what we need, but these things would help the visual ' thinkers ', since it would allow everything to be done, ' in ' the script canvas section, and rely less, on menus, and it would also be an AMAZING help for new coders, that after one has made a box, one can always click in a ' standard ' place, ie. the lower corner triangle button, to see what a particular box, can do quickly, all it's settings, so on . . Also, a link to a dedicated docs page, for EACH box, if they are different, of for a SUBTRACT, ADD, MULTIPLY box, to a ' common ' page, that explains all of, them . .

Having this feature, would make visual script much more user-friendly . . And, it would allow people that prefer the ' visual ' work-flow, to do that, more exclusively, or so . . ie., visual script would make more sense, visually, directly . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would just make visual script 100 % more, awesome, of close . . . It would also allow visual scripters to work more exclusively in the script canvas area, which is what we ' like ', or so . . I already suggested before, we get option to increase size, of comment font, and also ability to add, colored rectangles, so one can highlight certain areas, imo. this would make visual script much more competent, last some sort of system, where one can place ' nodes ' on the lines between boxes, so one can precisely make the lines, follow the grid, to make scripts more easy to read and, ordered . . .

![2020-07-04 1055](https://user-images.githubusercontent.com/61069740/95544021-5788f700-09fa-11eb-91cf-a4bdeb12ca4b.jpg)

Having these things, would certainly make visual script more appealing, and fun, and having a ' ? ' mark, on each box, would mean if one got stuck, at any time, there'd be a quick, user-friendly way, to get more info, without having to look through a ton of documentation, or random tutorials online, to find what one is looking for, the docs could have examples, as well as info, to do common things . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Like above, sorry, if I suggested this before, I'm VERY excited, about visual script, making it, better, as a user, also for new users, that want to use it, to learn the basics, of coding, before moving to GDScript / C#, ie. what are variables, functions, so on . . Can be easier to understand that, when one can ' see ', how it all connects, as a teaching tool, also . . <3

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I just hope you keep making improvement to visual script, so it becomes even better, and faster, for all users, and especially it becomes more ' intuitive ' for new users, that want to use it, or as a stepping stone tool, for learning coding basics, or so . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, bec. it wouldn't make sense, to have to download very small, very use-ful things, ie. basic improvements, that benefit all . . .

Thanks, can't wait to see, what happens next . . . <3

**Comment by jasperbrooks79** [comment]
Last, make it so when one disable the grid visually, one can still have ' snapping ' turned on, so one doesn't have to switch back - and - forth, when one wants to move a box, with snapping, then remove grid, for a better ' visual ' look, or so . . <3

**Comment by jasperbrooks79** [comment]
last, also if one select a bunch of nodes, there's a button, to make all of them visible, semi-visible or, near-transparent, or so . . maybe, like in Blender, the ' H ' key, or ' V ', or ' S ', for hide, visible, or see <3

And, a theme setting, to get rounded headers, instead of square, just, a new setting, in Project settings . . <3

This will address many of the complaints, I see in the Godot Discord, where people give up on visual script, bec. it isn't ' good ' enough, atm . . ie. add colored boxes, for highlighting chunks of code, add ' font size ' setting, to comment boxes, and add a feature, where one can simply write TEXT directly, on the canvas, with no box, and have different font sizes, also . . . Thx . . .

**Comment by jasperbrooks79** [comment]
it's difficult to explain, but as a visual scripter, I like being able to do every-thing, on the canvas, and not use menus, in the docks, change settings there, do everything, in the canvas, if possible . . .

these ideas will make it easier, to make everything, just using ' boxes ', no menus, no changing stuff, in menus, work 100 %, or close, with boxes, or visual script nodes, which is, the goal, for VISUAL coders . . . :O :O <3 . . . .

**Comment by jasperbrooks79** [comment]
ps. Right now many of the input ports, and out-put ports, don't follow the grid, it'd be very nice, epic . . if all the input nodes perfectly matched the grid, so one could have all the lines flow perfectly, either vertical, or horizontal, with a ' arrow between node ' editor, like above . . the boxes would get a bit bigger, for some of them, but then visual script would, look pro, real amazing . . . <3

**Comment by jasperbrooks79** [comment]
Imo, this is the closest one can get, to make visual script feel like, ' real ' coding, which is really cool <3

**Comment by groud** [comment]
@jasperbrooks79 please check if you already have opened a proposal about something before opening a new one: https://github.com/godotengine/godot-proposals/issues/1397

Please edit you proposal instead of opening a new one, especially when they include so many sub-proposal at the same time.

**Comment by jasperbrooks79** [comment]
I know, I just got some new ideas, or so . . Really like visual scripting, and I had a few new ideas, and couldn't find old post, lots, of posts, to look through . . . :-(( <3 . .

I had a few new ideas, and got so excited, went over everything, again, really excited . . .
