### ISSUE TITLE
Making the new sdf (signed distance field ) particle support a basic wind - simulation . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1639]
**Describe the project you are working on:**
Tomb Raider game, 3D, traversal, puzzles . . .

**Describe the problem or limitation you are having in your project:**
I've seen the videos, of the new collision with terrain particles, on Reduz twitter ( Mr. Linietsky <3

It'd be so cool, if those particles could react, to a wind system, to create some nice, out - of - box grass, vegation, sway or, motion . .

![2020-08-31 0522](https://user-images.githubusercontent.com/61069740/95546200-417e3500-0a00-11eb-8a37-d1d59e003844.gif)

As always, it'd have to be a compromise, between quality, and speed, performance . . Imagine having 100.000 blades of grass, or so . . that clings to the surface, of the world, and also has a simple, effective wind system or, simulation . . games would just ' pop ' right away, in Godot, making it more user - friendly, cool . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Some sort of support, for a wind simulation, a global thing, that makes things sway, and give good results, very, very fast, for prototyping, maybe final games <3

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm not sure, but if the new SDF particle also could have, a global wind system, it'd be cool . . . <3

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Again, it'd just be cool, if games could do that, very easy, a toggle, with some settings, some - where, maybe in particles or, World environment, or so . . Also seen the new SSAO, in Godot 4, it looks so amazing, everything is just better, Godot 4 will be a master - piece, imo . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Bec., it'd be nice, if people that haven't used the engine, can do some simple stuff, and it begins looking AA - AAA <3

Thx . . <3

**Comment by jasperbrooks79** [comment]
Also, if there were some simple settings, wind strength, direction, random, or so . . One could use an animationplayer, to animate a change, in weather, very fast . . . <3

**Comment by groud** [comment]
You have already opened about built-in wind already. Please merge this proposal with that one: https://github.com/godotengine/godot-proposals/issues/1435

**Comment by jasperbrooks79** [comment]
ok, sorry . . I can't merge here, bec. I don't manage this gitHub page, also I've never used gitHub, for really complex stuff, like code stuff, complete noob . . . <3 Didn't the users could also merge stuff, thought it was for people, that had open, the page, not me . . . :O :O . .

**Comment by clayjohn** [comment]
@jasperbrooks79 he just means that you should add this as a comment to your other proposal.

**Comment by jasperbrooks79** [comment]
okay, I get so excited, I post too much, these are my ideas, for things I'd like to see, to 'finish' the engine, already so excited for Godot 4 <3 Game dev is tough, Godot makes it possible, for people . .
