### ISSUE TITLE
Add pos2colrow and colrow2pos methods in TextEdit

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1644]
**Describe the project you are working on:**
gdscript plugins

**Describe the problem or limitation you are having in your project:**
I need to get `TextEdit` caret position. There is `cursor_get_column()` and `cursor_get_line()` but there is no easy way to convert them to pixels.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Methods that convert rowcol to xy and xy to rowcol would solve the problem

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`Vector2 pos2colrow(Vector2 pos xy coordinates in pixels)`
`Vector2 colrow2pos(Vector2 index in characters/lines)`

`pos2colrow` or maybe `pos2colline`

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No idea how it can be worked around with a few lines of script

**Is there a reason why this should be core and not an add-on in the asset library?:**
Should be core

**Comment by pycbouh** [comment]
In `master` this is partially implemented, as `TextEdit` now has `get_line_column_at_pos()` which takes a screen position and returns a vector containing the line/row and the column corresponding to that position. So I guess it just needs the opposite, `get_pos_at_line_column()`. (And `3.x` has neither, of course).

**Comment by NathanLovato** [comment]
Yes, this is exactly what we'd need.
