### ISSUE TITLE
Add a way to convert sprites to voxels

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot-proposals#1645]
**Describe the project you are working on:**
RPG

**Describe the problem or limitation you are having in your project:**
(As far as I know,) Converting a sprite/spritesheet into a 3D model requires using different programs such as Blender, MagicaVoxel, etc., then reimporting into Godot as .GLTF/.FBX or something.
I'm not sure if these programs support batch processing of a bunch of sprites at once, but if they don't, it would be tedious to convert each sprite manually.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Provide a functionality that allows a user to convert a sprite into a 3D voxel object, or batch process a spritesheet/directory of sprite files to create multiple objects.
Allowing the user to export the models as .GLTF files would be useful for animating them in another program if necessary.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
(Not really sure) But maybe it could work using CSG, subtracting from the mesh wherever there's a transparent pixel, then extruding the mesh to give it some depth.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It wouldn't be a *few* lines.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This actually could be an add-on.
Something like this could help users transition from working in 2D to 3D, since it wouldn't require the user to be familiar with 3D modeling programs or acquire 3D assets.

**Comment by Zireael07** [comment]
This looks like something for an add-on...

**Comment by lawnjelly** [comment]
See for example:
https://www.reddit.com/r/godot/comments/hy2n4a/i_made_a_project_that_turn_sprites_to_3d_voxel/
https://github.com/antopilo/VoxelFactory

**Comment by Calinou** [comment]
Voxelization is a difficult problem, so I think it's better left to an add-on as well.

> This actually could be an add-on.

If something can be an add-on, please open an issue on [godot-extended-libraries/godot-ideas](https://github.com/godot-extended-libraries/godot-ideas) instead of this repository :slightly_smiling_face:

**Comment by Error7Studios** [comment]
> See for example:
> https://github.com/antopilo/VoxelFactory

Awesome!

> If something isn't used very often and can be an add-on, please open an issue on godot-extended-libraries/godot-ideas instead of this repository 🙂

Sorry, didn't know about that repo. Will use it next time.
Closing, since VoxelFactory already exists.
Thanks!

**Comment by 98teg** [comment]
If anyone wants to use a gdscript addon to achieve this effect, I created SpriteMesh a while back: https://godotengine.org/asset-library/asset/1037
