### ISSUE TITLE
Update Issue Templates to facilitate opening Godot API Issues in the right places

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot-proposals#1663]
**Describe the project you are working on:**
N/A

**Describe the problem or limitation you are having in your project:**
Wanted to open an Issue for a Godot API change.

Godot docs aren't clear about where they should go (godotengine/godot-docs#4269), but even with that clarification, people who go to godotengine/godot and attempt to create an Issue won't see anything about the class reference. They see 'bug report' and 'security vulnerability' as the only available options and the documentation-related tickets linking to `godot-docs`, sending them to the wrong place. There, they see "enhancement request" to improve documentation, and that is likely what they would choose, since it's the only thing that seems applicable. However, that is the wrong place.

Had I not manually looked for `documentation`-tagged Issues in godotengine/godot, I wouldn't have had any official text anywhere indicating where I should create the Issue. That kind of confusion can inhibit or outright prevent new users from opening issues.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Update the issue templates in `godotengine/godot` and `godotengine/godot-docs` to specifically point people to the right places.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Change the file. N/A

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
N/A

**Comment by Calinou** [comment]
Now that we have a `class reference` label on godot-docs, I think it's fine to open class reference issues on either repository. There's no strong argument for using one or the other.

**Comment by willnationsdev** [comment]
If that's the case, and others feel similarly, then I suppose it's a non-issue and this can be closed. Not sure what all the different opinions are.

**Comment by Calinou** [comment]
This was addressed by https://github.com/godotengine/godot-docs/pull/4349, closing.
