### ISSUE TITLE
Legible output for typeof()

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-proposals#1665]
**Describe the project you are working on:**
n/a

**Describe the problem or limitation you are having in your project:**
n/a

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
`typeof` (or a variant: `typeof_str`) should return a Human readable string depicting the type of the arguement passed to it.
Ala Python's Type function:
https://docs.python.org/3.8/library/functions.html#type

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Previous discussion: https://github.com/godotengine/godot/issues/9336

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
n/a

**Is there a reason why this should be core and not an add-on in the asset library?:**
n/a

**Comment by pycbouh** [comment]
This still needs to be put into a proper proposal, preferably suggesting a particular way to address the issue, not just a complaint about an existence of one.

**Comment by CitrusWire** [comment]
This isn't a complaint. That issue was closed when the feature proposals were moved to this tracker. It says to open a new proposal if it's necessary; that's what I've done.

I'm not in any position to turn this into a "proper proposal", knowing nothing of Godot's internal architecture nor being even vaguely proficient at C++.

The sum total of the proposal can be summed up as:
> `typeof` (or a variant: `typeof_str`) should return a Human readable string depicting the type of the arguement passed to it.

There has already been an extensive discussion in that thread, I'd suggest continuing from that.

**Comment by pycbouh** [comment]
>  It says to open a new proposal if it's necessary

I'm not just being pedantic, because it also says 

> please open a new proposal on the GIP tracker **following the given issue template**

Otherwise this issue here will be closed as well until the template is filled out. The point of the movement is not to just copy and paste the issue but rather to provide a definitive solution that can be discussed and voted for. Or at least some research. There is a discussion on the matter, true. And a good proposal should collect it into a single digestible package. 

> I'm not in any position to turn this into a "proper proposal"

To put it blunt, that's a good reason not to open a proposal to keep the quality of issues here at a certain level.

**Comment by CitrusWire** [comment]
> > I'm not in any position to turn this into a "proper proposal"
> 
> To put it blunt, that's a good reason not to open a proposal to keep the quality of issues here at a certain level.

The consequence of this is that the only people who can make a whole swath of suggestions are ones who are proficient at C++. That doesn't seem very inclusive.

**Comment by pycbouh** [comment]
Please not the edit. You don't need to propose the exact implementation. You can stop at the user experience.

**Comment by CitrusWire** [comment]
Changed

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
