### ISSUE TITLE
Make the high-level multiplayer API multithreaded

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot-proposals#1675]
**Describe the project you are working on:**
Core Godot Multiplayer API

**Describe the problem or limitation you are having in your project:**
The current implementation of the Multiplayer API in Godot is already pretty great, however there are still some potential areas of improvement. One such area is concurrency (or more accurately, parallelism). The Godot multiplayer api is built on top of Godot's networking stack. Currently, the polling of the network happens during the idle frame on the main thread. This works for the most part, however during periods of higher computational load, this can cause various issues with networking, such as premature disconnections due to timeouts. Ideally, the network polling would happen on a separate thread so that it can continue to poll even when the main thread is busy preforming other expensive computations.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
As mentioned above, it would be best if network polling would happen in a separate thread. However it should be noted that it is still important that the processing of packets still happens on the main thread for a couple reasons:
1) it needs to do node lookups in the scene tree, which can end up causing hard to debug race conditions without careful use of synchronization primitives such as mutexes. 
2) most importantly, if rpcs were called on a separate thread, synchronizing them with other code in a class, such as that inside the `_process` or `_physics_process` methods would become extremely difficult to manage. Ordering is very important often times and asynchronous code is also more difficult to grasp for newcomers.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Luckily, the current Godot multiplayer API and netcode are already well abstracted to support such an improvement. In fact, the implementation I propose is isolated to a single class `MultiplayerAPI` and does not change the interface in any way.

It should be noted that I think we should actually make the _multiplayer api_ multithreaded rather than the low level network apis. In my opinion the networking apis are rarely used directly in practice and even then, being low level in nature suggests that they should be mostly bare bones. It also eases custom implementations of `NetworkMultiplayerPeer` since you don't need to worry about the nuances of threading or having to explain such nuances. If a developer needs to support multithreading of the low level network apis they are already low level enough to where they could implement the necessary threading themselves in their game code.

With all of that said, my suggestion is as follows:

1. Create a new struct `DeferredPacket` that contains three members, `sender`, `packet`, and `len` which correspond to the arguments for the `MultiplayerAPI::_process_packet` method.
2. Add three members to the `MultiplayerAPI` class, a `Mutex`, a `Thread`, and a queue. I'm not sure if we have an actual Queue class available, but if not `Array` or `Vector<DeferredPacket>` will work just as well for our use case. 
3. Create a new private method `_poll` (See prototype implementation below).
3. Instead of calling `network_peer->poll` in `MultiplayerAPI::poll`, start the thread with with `_poll` method in `_ready` and then in `poll`,
read from the queue under mutex and if a packet is available, call `_process_packet` with the contents.

As rough implementation of `_poll` might look like the following:

```cpp
void MultiplayerAPI::_poll() {
    while(true) { // There's an issue here which I will address later
        network_peer->poll();
        if (!network_peer.is_valid()) {
            return;
        }
        while (network_peer->get_available_packet_count()) {
            int sender = network_peer->get_packet_peer();
            DeferredPacket dp;
            dp.sender = sender;
            Error err = network_peer->get_packet(&dp.packet, dp.len);
            // TODO: handle error
            mu->lock();
            queue.push_back(dp)
            mu->unlock();
        }
    }
}
```

Now there is one flaw in the above function design. That is if the `MultiplayerAPI` instances is destroyed, we need to clean up that thread somehow. The `Thread` class has a method for waiting for it to finish that we can use in the destructor`, but we the example function doesn't have a way to tell the thread to end. As it is, it will just continue on indefinitely. This can be easily solved with an atomic boolean (or an atomic flag or w/e you wan to call it), but I'm not aware of an atomic boolean implementation in Godot, and I don't think using the stdlib options are worth it, so either we create our own, or we just use a second mutex and a regular boolean variable. Regardless, it's an easy problem to solve.

Lastly, there is one other thing to consider. While a multithreaded multiplayer implementation is ideal in most scenarios, there do exist situations in which you might not want a multithreaded implementation (for instance, inn platforms such as web where threading is not an option). So we may choose to make this optimization configurable. I'm not sure if this is worth it or not, but I leave it here as a consideration none-the-less.
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not really because how tightly coupled it is with the SceneTree.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's part of Godot core.

**Comment by jordo** [comment]
Some thoughts:

If we're going to move some work into another thread, it would be nice to do as much as possible there (serialization and de-serialization) would be nice work to push to into a network thread.  

We also don't want to busy-loop the thread.  The above code will busy-loop because nothing blocks.  For example, the Enet based peer used to block for up to 1ms, but was changed to non-blocking in this commit a few years ago:

https://github.com/godotengine/godot/commit/977c9477c1d5868eef8a38603e6f394e02f0e98b

**Comment by jonbonazza** [comment]
@jordo i agree it would be nice to handle serde in the thread as well. In fact, I'd prefer to handle everything up to the actual tree-related stuff off the main thread. @Faless mention on irc that all of `_process_packet` should remain on the main thread when I asked how heavy that function was and I wasn't sure he had a string reason for thus, o I wrote the proposal in this way hoping that he would chime in. This is the kind of feedback I am looking for, thanks.

As for the busy wait, I agree it's not ideal, but I don't know of any facilities that godot has in place already that could makr this more efficient without complocat7ing the code significantly. Aldo, ss you pointed to in your example, the enet peer already effectively uses this same pattern since the linked commit. Im open to ideas here however.

Lastly, I realize I was focused on the packet ingress and completely forgot to write a proposal for the egress side. Ill resolve that soon.

Thanks for the feedback!

**Comment by jordo** [comment]
Ya for egress, I'm not exactly sure what the API currently looks like when the underlying connection is stream based.  What happens when the outbound tcp buffer gets busy?  From my initial peek it looks like it just blocks, which we probably don't want to ever do on the main thread regardless of anything.  So there's even some benefits to threaded egress as well.  Still will require thread sync to wake the egress thread where there is work to do.

For the busy-wait, if ones going to implement a producer/consumer queue of some sort, you just would need some thread synchronization for wait and signalling.  Instead of having the consumer thread spin in a while loop, the consumer should wait on a signal.  Producer can push work into the queue, then signal the consumer to wake up and get to work.

It's probably too late now, but it also would be great to rename 'packet' to something like 'message' or something.  The multiplayer api seems to sit at a much higher level than the IP packet level, and the api was confusing to me at first.  When in netcode I usually infer packet = IP packet.

**Comment by jonbonazza** [comment]
Irt thread waiting, I suppose we could use a Semaphore here, but Im not sure what is determined as a good time to poll

I'd rather not complicate the code changes with such renamings since they are internal anyway. I agree they aren't ideal though.

**Comment by jonbonazza** [comment]
The only way I can think to solve this with ingress is to change the NetworkMultiplayerPeer interface to use a semaphor instead of a poll method.

Also, as long as we are multithreading a lock-free queue isn't really an option, though at the very least a RWMutex would be nice.

**Comment by jordo** [comment]
the timeout for enet connections is like 15s by default, and is even configurable.  I'm not sure what godot uses.  If the main thread pauses for that long, ur game is broken in may other ways.  

plus the enet poll, would be inside the proposed network thread. So even if the main thread pauses for a lot of work, the enet thread is still going to get pumped, (by the proposed network thread).

if the main thread pauses, all thats going to happen is the ingress queue is just to keep filling up and filling up. (enet is still polled by the network thread)

**Comment by jonbonazza** [comment]
@jordo there are legit reasons why a scene may not poll in time. Usually in scene startup. I agree they are few and far between and mostly can be solved by better design, but we can't always force this on users. Also, if the lolling happens on the main thread then making the multiplayer api threaded at all becomes useless. Serde and such isnt expensive enough to matter. Lastly, you have the other direction to worry about too. If for some reason a network implementation blocks in some way during polling, you hang up the main thread, which us not great.

Sorry, but I don't think polling on the main thread is negotiable.

Also, if you read the original post, i specifically mention that the network peer will _not_ but multithreaded and give some reasons why. The threading will happen in the MultiplayerAPI, which doesnt know anything about enet or the underlining implementation.

One if the goals here is to minimize the interface changes as much as possible. A overall goal of godot is to favor code maintainability, and user experience/ease of use over raw performance and efficiency

**Comment by jordo** [comment]
OK, perhaps i misunderstand the motivation here...  But when i say 'polling on the main thread', i simply mean processing the packets that are incoming from the network thread.  Basically, read the queue that the network thread is populating, and if any messages are there, process them.

It really boils down to WHEN you want to process the packet on the main thread, preemptively, asynchronously, or at a scheduled at some interval within the main thread's run loop (internal_process or something.

See below for some quick psuedo:

```c++
Queue message_queue;

// This loop is driving by network thread
void NetworkThread::_loop() {
	while(_running) {
		Message m = network_peer->pull_msg();  // say this blocks regardless of underlying connection is stream or packet based 
		message_queue.push_back(m);	
	}
}

// This func is called once per game loop from the main thread
void MultiplayerAPI::_poll() {
    while(!message_queue.empty()) { 
        Message m = message_queue[0];
	message_queue.erase(0);
	process_packet(m);
    }
}
```

**Comment by jonbonazza** [comment]
Let's continue this discussion on irc. I think it would be good to get other eyes on it too

**Comment by jonbonazza** [comment]
After much discussion on irc i decided to close this abd reevaluate things.
