### ISSUE TITLE
GitHub Actions: change the "Windows Builds" emoji icon to improve visual grepping

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot-proposals#1678]
**Describe the project you are working on:**
Godot Engine. 🙂

**Describe the problem or limitation you are having in your project:**
I'm using Godot's GitHub workflows and adapt them to suite my CI needs.
The current icon used to distinguish builds for Windows is 🏁. The problem is that I don't like it. 😛

In fact, there are quite a bunch of projects which choose their own icon for Windows builds specifically:
- https://github.com/Zylann/godot_voxel uses 🚪
- https://github.com/Orama-Interactive/Pixelorama uses 🗔
- https://github.com/goostengine/goost uses 🎨

Which objectively signifies that perhaps the current icon is not the best choice for representing Windows builds.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Build icons were introduced with godotengine/godot#41461. Personally, I suggest to use 🎨 because:
- it has all the original colors similar to previous Windows logos (from XP era, rather than 95);
- easily distinguishable from other icons, compare:
    - 🐧🍎🎨🤖🍏🌐 vs
    - 🐧🍎🏁🤖🍏🌐
- brings back good memories using MS Paint!

I also use a similar encoding to show which platforms various community C++ modules support in https://github.com/goostengine/godot-modules.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Replace all occurrences of 🏁 to 🎨 in build workflows before projects attempt to use different icons for Windows builds if they take Godot's workflows as the base.

See also a small poll at https://github.com/godotengine/godot-proposals/issues/1678#issuecomment-710994928 with some other candidates.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Sure, just use an icon you like in your projects, but I'd rather prefer to have a good enough default de-facto icon so that it's easy to identify Windows builds in other projects, and Godot Engine is the only entity with decent influence which is able to show a good example for people to follow. 🙂

This is especially important if Godot ever wants to provide general-purpose GitHub actions: #1413.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Have to modify `.github/workflows/*.yml` files.

**Comment by Calinou** [comment]
Note that emoji appearance differs depending on the OS. Here's how it looks like on my Fedora 32 system:

![image](https://user-images.githubusercontent.com/180032/96338415-3ecdb080-108e-11eb-9c6c-c4b2ae31ea7f.png)

**Comment by Xrayez** [comment]
On Google Chrome, Windows:

![google_chrome_windows](https://user-images.githubusercontent.com/17108460/96338502-2e6e0380-1097-11eb-8b90-3a343f84c32b.png)

**Comment by bruvzg** [comment]
macOS for the reference, Pixelorama icon is also missing (replaced by placeholder form [Last Resort Font](https://github.com/unicode-org/last-resort-font)).

<img width="440" alt="Screenshot 2020-10-17 at 16 38 25" src="https://user-images.githubusercontent.com/7645683/96338573-cff55500-1097-11eb-9b4d-e443e3f16fab.png">

**Comment by Xrayez** [comment]
# Poll

Given above references, react to this post with either emoji to choose your preference for the "Windows Build" icon!

Candidates taken from godotengine/godot#41461 discussion as well.

- [ ] 🚀 if you like 🏁 (current)
- [ ] 🎉 if you like 🎨
- [ ] 👀 if you like 🚪
- [ ] ❤️ if you like 🍷
- [ ] 😄 if you like 📎

**Comment by Xrayez** [comment]
I'm personally fine with any other icon as chosen by community, but I really think that 🏁 was not the best choice, in my opinion.

According to results in the poll, it seems like 🍷 is getting some traction:

![image](https://user-images.githubusercontent.com/17108460/100236872-e44e2c80-2f36-11eb-8310-a003a17b9bd6.png)

But this choice may be actually biased by people who use Linux as their main development platform. Personally, I'm for healthy lifestyle, and as a person who uses Windows as their main development platform currently, I wouldn't find this immediately recognizable either.

Also, Akien has changed his opinion from 🎨 to almost everything except 🎨, according to this poll, godotengine/godot#43835 and https://github.com/godotengine/godot/pull/41461#issuecomment-678750577. 😕

In fact, I've made godotengine/godot#43835 from the original 👍 from Akien in https://github.com/godotengine/godot/pull/41461#issuecomment-678750577, so I don't even know what to think now.

**Comment by akien-mga** [comment]
Well I gave the MSPaint icon a thumbs up as it's a fun and valid proposal, not worse than the flag one. That doesn't mean that I consider it better than any of the alternatives. To me all proposed alternatives are bad - I voted on the ones that might be somewhat recognizable. To that extent the clippy icon might actually be more recognizable than MSPaint as being "Windows" (that is, if people recognize MSPaint in the palette).

Since all options are somewhat bad, I don't see a strong motive for change. But that doesn't matter much and it's the kind of topic where I'm happy to follow the consensus once there is one (I wouldn't consider 3 options with 4 votes and 1 option with 5 being a consensus).

**Comment by akien-mga** [comment]
This one requires Unicode 13.0 (2020) and thus a recent font, but it's probably the least bad option:

🪟

**Comment by Xrayez** [comment]
You change opinions like it doesn't mean anything, and you change game rules during a game.

This is not serious.

**Comment by akien-mga** [comment]
Alright, I'll refrain from using emoji reactions from now on if some people interpret them as an injunction for change...

**Comment by Xrayez** [comment]
> Alright, I'll refrain from using emoji reactions from now on if some people interpret them as an injunction for change...

No, please do react, but only when you're really sure about it.

**Comment by Xrayez** [comment]
Also, this is not what I've been talking about in the proposal, most of the rationale I presented there was ignored.
