### ISSUE TITLE
Enable EditorPlugin to run a script/scene in debug mode like press the 'Scene Run button (F6)'

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot-proposals#1680]
**Describe the project you are working on:**
I'm working on a unit test plugin. It startes a test client in the background (hidden application)
The client comunicates over network connection with der server running by the plugin.
To run the test client i use the provided functionallity OS.excetute() with this arguments
[--no-window, -d, -s, res://addons/gdUnit/src/core/GdUnitClient.gd]

**Describe the problem or limitation you are having in your project:**
I want to execute a test suite with full debug functionallity where written by others e.g. breakpoints and stepping ...
The scripts are parsed and executing all test cases over a client application described on top.
My problem is the client is started with debug option but no realtime debugging is working.
To fix and test your writen code in a unit test it needs to can debug in realtime your code.
This is currently only possible to creata a extra "debug" scene and run manually by open the scene and press F6
But i want to execute the test client hidden in the background and started by a context menu inside the editor without an extra context switch.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a new function to the EditorPlugin class to enable a plugin to run a given script or scene with full debug support.
`run( <path>, debug:bool = false)`
Currently you can only achive this by creating an extra "debug" scene and start it by the editor button "Scene Run button (F6)"
But i want to run a specific script from a plugin context menu with full debug support.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`EditorPlugin.run( <path>, debug:bool = false)`
This will you full enable to debug such plugin code without creating an extra scene and context switch

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
* needs to create a extra scene
* needs to now where this scene is located and you have to open manually and press F6 to debug

**Is there a reason why this should be core and not an add-on in the asset library?:**
I guess this should be core functionallity to help debug plugin code

**Comment by pycbouh** [comment]
I'm not sure what do you mean here by full debug support, but you can run any scene from your plugin code since godotengine/godot#37619.

**Comment by MikeSchulze** [comment]
@pycbouh oh i not now about this functions,
Oh this is only Godot 4.0 supported right?

**Comment by MikeSchulze** [comment]
I closed as clarified because godotengine/godot#37619 provides already requested functionallity
Thanks
