### ISSUE TITLE
Pygame

### ISSUE THREAD

**Issue by yezz123** [godotengine/godot-proposals#1685]
As a simple suggestion why not `godotengine` support `python` and `pygame` with some new features a 3D or 2D engine that can make a lot of people who code with `python` try to use it and why not be inside developing big project.
As a user of `godotengine` i guess that can be a good idea!
![ee8029f362aebc3689ef66bdb803d86e](https://user-images.githubusercontent.com/52716203/96368076-a5fc6b00-1149-11eb-81e9-d7f647e35a6d.png)
Also `pygame` support 3d like this [3D Wave Interaction Simulator](https://www.pygame.org/project/604)
and Also a lot of project 🙏

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by Zireael07** [comment]
Godot already supports 2D and 3D. Showing pygame into it is like shoving a square peg into a round hole...

**Comment by SIsilicon** [comment]
Or a square box in a larger square hole.
