### ISSUE TITLE
Rotate/Move Viewport only while pressing a mouse button (Editor, Emulate 3 Button Mouse)

### ISSUE THREAD

**Issue by purestrain** [godotengine/godot-proposals#1691]
**Describe the project you are working on:**
Sample project for evaluation purposes (evaluating switch from unity3d)

**Describe the problem or limitation you are having in your project:**
I'm always accidentally rotating/moving the viewports when alt-tabbing to other programs or when trying to do a stepped-rotation (pressing control) using the transform tool. This is very annoying.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Click to move/rotate the viewport like everyone else does (blender, unity3d, unreal engine...) - GoDot is currently the only tool which is doing a rotation by using the mouse and some modifier keys without pressing a button. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If you press a modifier like alt it should not instantly rotate by moving the mouse .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, because it affects usability - and every other software is doing it right IMHO.

**Comment by Calinou** [comment]
This sounds like a bug (e.g. Godot thinks a mouse button is pressed down because you alt-tabbed while pressing a mouse button). Godot already shouldn't move the camera around if you don't press a mouse button.

**Comment by purestrain** [comment]
Godot, yes! :-) So actually i testet in in 2.x and there is no movement/rotation available. In 3.1.2 it's also zooming/moving only by holding down ctrl / shift keys. Maybe i need to test it on a different windows 10 system then.

**Comment by purestrain** [comment]
Yes, actually i'm using "Emulate 3 Button Mouse" - this is why it happens just to me. So 3 Button-Mouse works without a mouse press.

**Comment by Zireael07** [comment]
Sounds like a bug, not a feature proposal, still.

**Comment by purestrain** [comment]
I filed a bug report - but i actually don't know if its by design, we will see - thanks for pointing me in the right direction.
https://github.com/godotengine/godot/issues/42908

**Comment by aaronfranke** [comment]
Superseded by https://github.com/godotengine/godot/issues/42908, closing.
