### ISSUE TITLE
Export all the games to a single scene

### ISSUE THREAD

**Issue by colorworlds** [godotengine/godot-proposals#1692]
**Describe the project you are working on:**
Godot game loader, used to load my mini games

**Describe the problem or limitation you are having in your project:**
I hope to make a small game collection, or reuse some scenes from previous projects.
I was able to encapsulate the previous mini game project as a scene, but couldn't handle the `Autoload` nodes.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If the whole project can be exported as a scene, then I can load the game scene to get a game collection(It's like FC games), and even reuse some nodes.
I envision an additional benefit is that in the browser, users only need to download my loader once to get the engine, and then they only need to download my mini game scene without repeatedly downloading the entire engine.
So I can build a godot game platform.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The Autoload nodes are converted into normal nodes, and the path search(such as $'root/AutoloadNode' ) is added to each script file to obtain the AutoLoaded nodes.
There is a more detailed description in #1633  
And this proposal is simpler and invisible to users

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes,If you do not use AutoLoad nodes

**Is there a reason why this should be core and not an add-on in the asset library?:**
Need editor support

**Comment by pycbouh** [comment]
> Yes, If you do not use AutoLoad nodes

Exactly. For your specific purpose you can easily redesign the hierarchy of your games to move away from project-defined autoloads to just nodes added to each game's own root node. I bet you can even automate this conversion with a short shell script.

Or share the autoloaded scripts. Or make a single core autoloaded script that can house and give access to game-specific scripts which are registered and unregistered as the games are changing. This seems like a system design concern, not the engine concern.

**Comment by colorworlds** [comment]
> Exactly. For your specific purpose you can easily redesign the hierarchy of your games to move away from project-defined autoloads to just nodes added to each game's own root node on load. I bet you can even automate this conversion with a short shell script.
> 
> Or share the autoloaded scripts. Or make a single core autoloaded script that can house and give access to game-specific scripts which are registered and unregistered as the games are changing. This seems like a system design concern, not the engine concern.

Yes , This feature is only useful in specific situations and is not common

**Comment by Zireael07** [comment]
If this feature is only useful in highly specific situations, I wouldn't hold my breath for it happening (see Godot's philosophy is to keep the core lean and only put in features that are universally or almost universally useful)

**Comment by colorworlds** [comment]
> If this feature is only useful in highly specific situations, I wouldn't hold my breath for it happening (see Godot's philosophy is to keep the core lean and only put in features that are universally or almost universally useful)

Sorry, I didn't notice that
