### ISSUE TITLE
Ability to change order of elements in export (Array)

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot-proposals#17]
Copy of issue here: https://github.com/godotengine/godot/issues/31723

Export arrays in the inspector are great!
But it can be a pain when you add a lot of elements, then realize you need to insert another element at a certain index. Right now the only way to do that is to erase every element until you reach that index, insert the new element, then re-add every element.

There are a few ways to add this, for example:
-arrows next to the element index number to move it up or down the array
-Being able to drag the elements to sort them (however would not work with more than 1 page)
-Editable index number that will re-arrange elements according to the number you change it to
-"Insert at index #" option at top of the array

If there are any better ways then I'm all for it!

**Comment by reduz** [comment]
Please re-open this proposal using the new issue template.

**Comment by Calinou** [comment]
For future reference, this proposal was recreated in #23.
