### ISSUE TITLE
Drop support for 32-bit machines

### ISSUE THREAD

**Issue by strzelaminat** [godotengine/godot-proposals#1707]
**Describe the project you are working on:**
I create small strategy game

**Describe the problem or limitation you are having in your project:**
Since my project grows over time, I found some bugs in engine(all were reported before), but sadly still some are not fixed.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Dropping 32 bit architecture will allow Godot developers to focus only on 64 bit hardware which I think is in 99% of Godot users computers.

Dropping support probably will allow to delete or refactor some code and create smaller binaries(not too much probably).

This will allow to close issues like https://github.com/godotengine/godot/issues/31743 which are almost impossible to fix since almost no one have 32 bits computers.

It will also allow to drop some outdated things like 32 bit hashes(changing hashes to 64 bit probably will cause big overhead to 32 bit builds)

Even cheap Rasberry Pi 2+ have 64 bit processor.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
First step is to remove 32 bit compilation options from Scons.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Almost no one use now 32 bit editor and Godot 4.0 support for Vulkan(GLES 2 and 3 I don't think that will be available in it) will cause that probably 0 computers with 32 bit OS will be able to run it.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Skipping since doesn't make sense this question in this proposal

**Comment by Calinou** [comment]
We intend to keep 32-bit support for 4.0 as it's still important to have on Windows and Android.

We most likely won't build official 32-bit Linux binaries for 4.0, but it'll still be buildable from source.

**Comment by mrjustaguy** [comment]
I see no point in not supporting 32-bit... Still plenty of 32-bit systems out there, so if keeping it isn't a problem there is no point in dropping it...

**Comment by aaronfranke** [comment]
Reduz has already stated that Godot will focus on 64-bit systems as a priority for Godot 4.0. So, Godot will still be available for 32-bit systems, but all the code will be designed to run best on 64-bit systems, so Godot 4.0 might be slow on 32-bit systems.

**Comment by Calinou** [comment]
Closing per @aaronfranke's comment.
