### ISSUE TITLE
can we have properties for getting the relative vector from a vector2 or vector3

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1710]
**Describe the project you are working on:**
3d rougelike

**Describe the problem or limitation you are having in your project:**
I need a easy way to find the relative adjacent vectors from a current one.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
basically what I want to see is something like this..
```
 #already exist
var const = Vector3.UP

#what we need
var variable = Vector3.FORWARD
variable.rotated(Vector2.UP, 45)
var forward_movement = variable.forward * walk_speed
var side_movement = variable.right * walk_speed
```

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
above

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
this would be used alot for fps or 3d rougelike movement
I know there is something similar for 3d nodes but its not very understandable

**Is there a reason why this should be core and not an add-on in the asset library?:**
its easy to use and understand and is really useful

**Comment by groud** [comment]
Your proposal isn't really clear. "find the relative adjacent vectors from a current one." make not a lot of mathematical sense.
If you need to retrieve a vector perpendicular to two others, you can use the cross product. 

Otherwise, there's no way to produce two vectors out a single one, there's no way `variable.right` could return something if you don't provide it both a forward and up vector.

**Comment by KoBeWi** [comment]
You mean having something like this? https://github.com/godotengine/godot/issues/17200
Or a more generic feature for vectors?

**Comment by Xrayez** [comment]
Perhaps this: #566.

**Comment by Shadowblitz16** [comment]
@groud that's only if people know what cross product is.

Its easier to have shortcuts like this..
Vector3.FORWARD,
Vector3.BACK,
Vector3.UP,
Vector3.DOWN,
Vector3.LEFT,
Vector3.RIGHT
 
but that is local to the vector's rotation

for example moving left from the camera's view is as simple as..
`translation += get_node("Camera").rotation.forward * Vector3.LEFT`

**Comment by Shadowblitz16** [comment]
This proposal needs to be remade.
I didn't know at the time but I am talking about transform.<DIRECTION>
