### ISSUE TITLE
Allow offsetting built in mesh types

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1716]
**Describe the project you are working on:**
3D Roguelike

**Describe the problem or limitation you are having in your project:**
I need to offset cubes by half a unit for gridmaps

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I was wondering of a offset parameter could be added to meshes so that we can offset the vertices for gridmaps

this issue covered it but was closed due to a fix that didn't fix the issue  [#24602](https://github.com/godotengine/godot/issues/24602)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
something like size which is a vector3 under the mesh properties but for vertices offsets 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it would mostly be used for gridmaps and yes through a script but we shouldn't need to attach a script to every mesh just to offset it because gridmaps don't respect position

**Is there a reason why this should be core and not an add-on in the asset library
its useful to easily be able to create block based 3d maps

**Comment by Shadowblitz16** [comment]
nvm didn't see it was closed

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by Shadowblitz16** [comment]
@Calinou I updated the issue
