### ISSUE TITLE
Add an `extend()` method in Array

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1718]
**Describe the project you are working on:**
gdscript plugins

**Describe the problem or limitation you are having in your project:**
it seems
```gdscript
for i in b.size():
  a.append(b[i])
```
is faster than
```gdscript
a+=b
```
(especially if you are working with large arrays), but noisier (less laconic, this is most noticeable when you have to repeat it often in the code).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I think the built-in `extend()` method would be faster than `for .. append()` gdscript loop and certainly faster than `a+=b` and still look good.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```swift
var a = [1,2]
var b = [3,4]
a.extend(b)

-->
[1,2,3,4]
```
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
```
for i in b.size():
  a.append(b[i])
```
or `push_back()` (it seems marginally faster than `append()`)
also `a.resize()` can be used

**Is there a reason why this should be core and not an add-on in the asset library?:**
this is a new `Array` method

**Comment by Zylann** [comment]
It already works:

```gdscript
	var a = [1, 2]
	var b = [3, 4]
	var c = a + b
	print(c)
```

Prints:
```
[1, 2, 3, 4]
```

**Comment by me2beats** [comment]
I thought this is not efficient mainly because the new array is being created.
especially the difference in speed is felt on large arrays.

**Comment by me2beats** [comment]
and also I think this method would be convenient for beginners who switched from other languages ​​where there is `extend()` for example from `Python`

**Comment by Zylann** [comment]
I don't necessarily disagree with the addition of `extend()`, so let's say your proposal actually hides an issue with `+=` being unnecessarily slower when the operand is an array due to the loose translation, and that should be fixed.

**Comment by KoBeWi** [comment]
Related: https://github.com/godotengine/godot/issues/11073

**Comment by ZuBsPaCe** [comment]
I think, this would be a nice addition. I just ran into this a few minutes ago:

`func test():
	var arr := []

	append_one(arr)
	print(arr)
	# Prints "[1]"

	append_some(arr)
	print(arr)
	# Prints "[1]"

func add_one(arr : Array):
	arr.append(1)

func add_some(arr : Array):
	arr += [2, 3]
`

Took me a while to realize, that += creates a new, local array in the "add_some" function. But well, thinking about that, the behavior makes sense.

Having something like extend() or append_array() would be nice to have in such situations.
