### ISSUE TITLE
Add method to get vector from angle

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#1719]
**Describe the project you are working on:**
A 2D game

**Describe the problem or limitation you are having in your project:**
We have `Vector2.angle()` which is useful to get an angle in radians from a vector, my problem is that there's no opposite method. It's rather simple to write one, but let's say you want to do `velocity.angle().rotated(1)` and then get a directional vector again. You are forced to store the angle value into a variable. And then do maths. But what maths? `velocity = Vector2(sin(angle), cos(angle))`? `velocity = Vector2(cos(angle), -sin(angle))`? See? It's not obvious what combination of sin/cos will yield a vector that will be consistent with the built-in `angle()` method. I use this quite often, but not often enough to remember what to use xd

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
We could add a `angle_to_vector()` method, which would convert an angle to normalized Vector2() in a way that `angle_to_vector(vec.angle())` would be equal to `vec.normalized()`. This is just for convenience.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
Vector2 angle_to_vector(float p_angle) {
    return Vector2(cos(p_angle), sin(p_angle))
}
```
or something

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This is used quite often. But yes, can be worked around.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It just feels like the current set of math methods is missing this.

**Comment by groud** [comment]
Why not use `Vector2.RIGHT.rotated(angle)` ?

**Comment by Zireael07** [comment]
Drive-by comment: Please please, the same for Vector3, where it isn't as easy as in 2D...

**Comment by KoBeWi** [comment]
> Why not use Vector2.RIGHT.rotated(angle) ?

Because you have to come up with this solution first 🙃
Maybe just mentioning it in docs would be enough.

**Comment by Xrayez** [comment]
> Why not use `Vector2.RIGHT.rotated(angle)` ?

> This is just for convenience.

> It just feels like the current set of math methods is missing this.

I think this would certainly ***complement*** the engine.

**Comment by LightningAA** [comment]
> Drive-by comment: Please please, the same for Vector3, where it isn't as easy as in 2D...

How would such a function work? How would this be different from [Vector3.rotated()](https://docs.godotengine.org/en/stable/classes/class_vector3.html#class-vector3-method-rotated)

**Comment by aaronfranke** [comment]
Since https://github.com/godotengine/godot/pull/48237 was merged, should this be closed as resolved? I know there's the question about doing the same for Vector3, but I'm not sure what the use case is for that.

**Comment by aaronfranke** [comment]
> @LightningAA: How would such a function work?

It's a lot more complicated because there are different rotation orders to consider. Also, since there is no unary `Vector3.angle()` it's also not clear which direction should be treated as the unrotated direction, but probably forward. Here is a Vector3 from_angle method implemented in GDScript, in YX rotation order, treating zero angle as forward (-Z), and follows Godot's conventions of a right-handed coordinate system:

```gdscript
func vector3_from_angle_yx(y, x):
	var neg_cosx = -cos(x)
	return Vector3(neg_cosx * sin(y), sin(x), neg_cosx * cos(y))
```

**Comment by aaronfranke** [comment]
Closing as implemented in Vector2 and rejected for Vector3 (there is no one method for all use cases of angled Vector3s, depending on your use case you can use what I posted above).
