### ISSUE TITLE
Assign a dedicated maintainer to the demo projects repository

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#172]
**Describe the project you are working on:** https://github.com/godotengine/godot-demo-projects

**Describe the problem or limitation you are having in your project:**

The current problem is that right now there is an extremely low amount of reviewing and merging of pull requests by Godot developers in the demo projects repository. Godot is already in the beta stage for 3.2, meanwhile many of the demo projects are still optimized for 3.0, and show warnings and many diffs when opened in 3.1.

There are many pull requests which fix these issues and are likely ready to merge but haven't gotten any attention for years. For this repository, this isn't really acceptable, since it's very easy for pull requests to conflict with each other, making maintenance more difficult the more PRs are open.

To try and help with this, I took it upon myself a few months ago to review all open pull requests, the idea being that it would be easier for maintainers to review and merge them if they spent less time requesting changes. However, this doesn't work if there's nobody coming around to make the final decision and merge such pull requests.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

My proposal is to assign a dedicated maintainer, or set of maintainers, to the demo projects repository, who can regularly review and merge pull requests, or close abandoned ones (since, as I mentioned above, having many PRs is not really a good idea for this repository).

It's hardly a full time job, the current queue of pull requests built up over years could probably be reduced to only a few open PRs within the span of a week, assuming many of the abandoned PRs are closed. I volunteer for this, but it would be better if there was also a 2nd set of eyes looking over pull requests in addition to me - it's easy to miss or forget something.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

I don't think this is necessary.

**Describe implementation detail for your proposal (in code), if possible:** N/A

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** N/A

**Is there a reason why this should be core and not an add-on in the asset library?:** N/A

**Comment by clayjohn** [comment]
Great idea!

**Comment by Feniks-Gaming** [comment]
To expand on that Godot really need dedicated wiki maintainer after your proposal is done. I feel like next full time dev job should be first bringing wiki up to date with new versions of the engine before doing anything else. 

Documentation is essential for a good working projects it's ungrateful job that not many volunteers are willing to pick up so I feel this requires dedicated paid attention.

**Comment by aaronfranke** [comment]
This has been solved. The maintainer is now... me!

Actually, it's more than just me. There is a [demo projects team](https://github.com/orgs/godotengine/teams/demos) composed of myself, akien-mga, fire, and QbieShay. Additionally, bojidar-bg helps with coordinating releases, and NathanLovato from GDQuest has been helping out quite a bit. Also related, I can now moderate on the asset library.
