### ISSUE TITLE
Can't convert Vector2 to Vector3 due to y axis differences

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1720]
**Describe the project you are working on:**
3D rouglelike

**Describe the problem or limitation you are having in your project:**

something like this don't work due to y axis facing down in 2d and up in 3d
```
func v2_to_v3(vector:Vector2)->Vector3:
	return Vector3.FORWARD.rotated(Vector3.UP, vector.angle())
```

```
func check_move(dir:Vector2)->bool:
	if has_node("RayCast"):
		var raycast = get_node("RayCast")
		raycast.cast_to = v2_to_v3(dir).rotated(Vector3.UP, rotation.y)
		raycast.force_raycast_update()
		return not raycast.is_colliding()
	return true
```

I have a camera with no rotate except -90 degress on the x axis to make it face down and a ray cast with the same parent as the camera

Vector.UP
![image](https://user-images.githubusercontent.com/2453707/97095541-adbe8280-1615-11eb-8b74-9211a2b676f7.png)
Vector2.DOWN
![image](https://user-images.githubusercontent.com/2453707/97095561-d181c880-1615-11eb-80dd-9a3a9a119a2b.png)
Vector2.LEFT
![image](https://user-images.githubusercontent.com/2453707/97095547-bdd66200-1615-11eb-8f9f-413d2dc36ac1.png)
Vector2.RIGHT
![image](https://user-images.githubusercontent.com/2453707/97095551-c75fca00-1615-11eb-905f-efdb3f52bc34.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I suggest a option be added to invert the 3d y axis so that it matches the 2d counterpart
I also suggest making it the default option for future projects

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
What should be happening is this..
Vector2.LEFT
![image](https://user-images.githubusercontent.com/2453707/97095551-c75fca00-1615-11eb-905f-efdb3f52bc34.png)
Vector2.RIGHT
![image](https://user-images.githubusercontent.com/2453707/97095547-bdd66200-1615-11eb-8f9f-413d2dc36ac1.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
this would make things so much easier for people to convert between 3d and 2d vectors and while it might be doable with script its not very easy to understand and do.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It would simplify rotations and make them easier to understand

**Comment by Zylann** [comment]
Have you tried this?
```
# assuming vector contains a normalized direction
func v2_to_v3(vector:Vector2)->Vector3:
	return Vector3.FORWARD.rotated(Vector3.UP, Vector2(vector.x, -vector.y).angle())
```

**Comment by Shadowblitz16** [comment]
I was using the vector for movement so it wasn't necessarily normalized.

**Comment by Zylann** [comment]
Should work too with non-normalized vector though

**Comment by Shadowblitz16** [comment]
It would still be nice to be able to convert like so..

`return Vector3.FORWARD.rotated(Vector3.UP, vector.angle())` or
`return Vector3.FORWARD.rotated(Vector3.DOWN, vector.angle())`

like rotations should be the same regardless if you use 2d or 3d

**Comment by aaronfranke** [comment]
Changing the coordinate system in Godot won't happen, both for compatibility reasons, and because it isn't desired anyway (Godot's existing coordinate systems are already good). Having the option to change coordinate systems per project would be difficult to maintain for almost zero benefit, so this won't be done either.

The ability to convert vectors to different formats is something that should usually be done manually IMO, or it's easy to create your own helper methods as Zylann pointed out, but there are proposals like #727 that propose adding swizzle properties. So part of this proposal is invalid and part is a duplicate, closing.
