### ISSUE TITLE
Update documentation on method like add_child() to let know the user that the passing variable is modified

### ISSUE THREAD

**Issue by stebulba** [godotengine/godot-proposals#1722]
I avoid my proposal.

In documentation, I got trouble with to understanding the function add_child()
When you add_child from a instance, your node instance become your reference/pointer of your new child.
The documentation "Adds a child node." is confusing, because is not true.
It's not adding but doing more a " move_node_as_a_child ". Your instance node is moving as a child and your instance variable point now to your child.

Nothing in the documentation talk about that and can make confusion with other program language like unity where the reference of the child is return:
`SphereCollider sc = gameObject.AddComponent<SphereCollider>() as SphereCollider;`

I don't know how many function are working like this, but I think the documentation should talk about that.

That become my proposal. Update documentation for all method doing that if they have many.

**Comment by KoBeWi** [comment]
Related to https://github.com/godotengine/godot/issues/26542

**Comment by kintrix007** [comment]
```py
var child

func _ready():
    child = Sprite.new()
    add_child(child)
    # You can reference the variable "child" later
    child.position = Vector2(50, 0)

#Since "child" is public, you can even access it in different fUnctions.

func _process(delta):
    child.position += Vector2(10, 5) * delta
```

**Comment by stebulba** [comment]
Thanks, you realize me the child instance become the reference of the new added children. That make all the difference.
p_child->data.parent = this;
https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L1210

One question, why documentation don't talk about that.
https://docs.godotengine.org/fr/stable/classes/class_node.html#class-node-method-add-child


I can imagine for exemple a beginning error like that:
child = Sprite.new()
child.set_script( cow_enemy )
add_child(child)
child.set_script( chicken_enemy )
add_child(child)

when should be : add_child(child.duplicate())
I will change my title of the issues.

**Comment by kintrix007** [comment]
The reference doesn't change. The reference stays the same. Only, you pretty much just add the node the the scene tree. And with that making it a child of an object instead of an orphan.

**Comment by stebulba** [comment]
I understand what your mind. I missed something in my understanding. Thanks.
