### ISSUE TITLE
Add a button to reverse a Gradient resource in the editor

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot-proposals#1724]
**Describe the project you are working on:**
[Goost](https://goostengine.github.io/) - Godot Engine Extension.

See godotengine/godot#42855 and godotengine/godot-proposals#1677.

**Describe the problem or limitation you are having in your project:**
See https://github.com/godotengine/godot/pull/42855#issuecomment-716173277.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I suggest that the editor should have a way to reverse color offsets, just like in image editing software.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

![Screenshot 2020-10-25 195052](https://user-images.githubusercontent.com/17108460/97113449-1def0600-16f3-11eb-9eaf-c0e8743952c4.png)

Picture from https://graphicdesign.stackexchange.com/a/57225.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Trivial (but painful) for black and white gradients by switching leftmost and rightmost grabbers manually, *not* trivial for anything else.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Already part of core.

**Comment by Calinou** [comment]
There's already a [pull request](https://github.com/godotengine/godot/pull/29964) for this, but it needs to be redone to use a context menu option instead of the middle mouse button.

**Comment by Chaosus** [comment]
Fixed by https://github.com/godotengine/godot/pull/53321
