### ISSUE TITLE
Render the project offscreen and present it using DirectX or Vulkan to solve NVIDIA Optimus stuttering

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot-proposals#1725]
**Describe the project you are working on:**

A rhythm game in Godot.

**Describe the problem or limitation you are having in your project:**

OpenGL software has stuttering issues in some NVIDIA Optimus setups, this is universal and the only solution is to either not use OpenGL or to render the OpenGL buffer offscreen and present it using DirectX or Vulkan and forcing v-sync to be on.

Vulkan is preferred, as that leads to the least amount of problems in my experience using ANGLE.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

An option that allows the game to render offscreen and be presented by Dx11 or Vulkan.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I suppose the best way would be to do this in the Windows OS code, possibly overriding something in the GL context code.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

There is no solution.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is a fairly low level change that can't be done from an asset.

P.S:

It is obvious this change would only apply to 3.2 and the GLES2 renderer in 4.0.

**Comment by EIREXE** [comment]
It has been informed to me that the actual way to fix this issue is to have exclusive fullscreen, is it planned for 4.0?

**Comment by Calinou** [comment]
> It has been informed to me that the actual way to fix this issue is to have exclusive fullscreen, is it planned for 4.0?

Not that I know of. In general, exclusive fullscreen is becoming increasingly less relevant over time due to the lower convenience compared to borderless windows. See also https://github.com/godotengine/godot/pull/41746.

**Comment by EIREXE** [comment]
> > It has been informed to me that the actual way to fix this issue is to have exclusive fullscreen, is it planned for 4.0?
> 
> Not that I know of. In general, exclusive fullscreen is becoming increasingly less relevant over time due to the lower convenience compared to a borderless fullscreen window. See also [godotengine/godot#41746](https://github.com/godotengine/godot/pull/41746).

I will be doing a PR switching WGL with EGL if you think it's reasonable.

**Comment by Calinou** [comment]
Is this still relevant with https://github.com/godotengine/godot/pull/44845? If not, this proposal should be closed.

**Comment by EIREXE** [comment]
> 
> 
> @EIREXE Is this still relevant with [godotengine/godot#44845](https://github.com/godotengine/godot/pull/44845)?

Actually no, that does fix it, I also have another patch to fix fullscreen to behave like borderless windowed ready after that. I still have to port it to 4.0 though.

**Comment by Calinou** [comment]
@EIREXE Is this still an issue on the latest NVIDIA drivers?

**Comment by EIREXE** [comment]
> @EIREXE Is this still an issue on the latest NVIDIA drivers (526.86 as of writing)?

As I understand yes, but only on opengl

**Comment by EIREXE** [comment]
This doesn't apply anymore I believe since nvidia threaded optimization is now disabled.

**Comment by Calinou** [comment]
Note that DXGI presentation of Vulkan is tracked in a separate proposal: https://github.com/godotengine/godot-proposals/issues/5692
