### ISSUE TITLE
Make signals generate static typed parameters and returns

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1726]
**Describe the project you are working on:**
3D rougelike

**Describe the problem or limitation you are having in your project:**
Functions generated by signals are just really hard to know what they contain without pulling up the docs since they are treated as variants

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
When signals generate functions they should also generate static typed parameters and returns 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
something like this..
```
func _on_Player_input(event:InputEvent)->void:
    pass
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
yes it can be added but static typing should be encouraged as works well with auto complete 

**Is there a reason why this should be core and not an add-on in the asset library?:**
because it helps people know what members it has and also encourages good code

**Comment by KoBeWi** [comment]
Editor Settings -> Text Editor -> Completion -> Add Type Hints

**Comment by Shadowblitz16** [comment]
@KoBeWi  ty so much!
