### ISSUE TITLE
More input signals

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1727]
**Describe the project you are working on:**
3D Rougelike

**Describe the problem or limitation you are having in your project:**
I find working with the input event is a little too generic and was hard until I realized I had to check events with the 'is operator'  

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I suggest adding more concreate input events and moving existing ones to node

here are some I can think of..
- mouse_move
- mouse_down
- mouse_up
- key_down
- key_up
- touch_move
- touch_down
- touch_up
- action_down
- action_up

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I would guess it would look something like this..
```
func _on_mouse_move(event): # InputEventMouseMotion
  pass
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it would be used more often then the input signal if done right
while you can just use the input signal its not ideal for beginners

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think its a more beginner friendly system then what we have now.

**Comment by Jummit** [comment]
> while you can just use the input signal its not ideal for beginners

[There is extensive documentation on how to do that.](https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html)

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP).
