### ISSUE TITLE
Suggestion on how to make visual script more user-friendly, fast and, robust . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1735]
**Describe the project you are working on:**
A Tomb raider game, traversal, puzzle, so on . .

**Describe the problem or limitation you are having in your project:**
I use visual script for making games, atm, and I am often frustrated, that it's not possible to do ' everything ' the boxes do, in the boxes, or at least one can see important settings there . . I made a suggestion, that one could have an expandable panel or, dock on the bottom, but if that isn't enough, one could have a second one, under that . . In there, one would have all the common tools needed, for game dev, and it'd make sense to learn them first, so important stuff should be put there . . It could be settings, or a _processPRINT, _physicsprocessPRINT, _readyPRINT, and other important stuff . . This is my last suggestion, for making visual script better, the issue is often people that work in visual script, want the work done, almost entirely, in the visual script area, without having to use settings, menus, in the Inspector dock, etc . . Ideally, the whole thing would be click, drag-and-drop, enter values, and done completely, if possible ' in ' the boxes, no menus, total ' visual ' work or, so . . <3 That won't always be possible, for very advanced boxes, but having some common use-case ' icons ', under each box, one would know, if one can't make a box work, one should start there, as a good starting point, or so . .

<img width="882" alt="2020-10-27 0932" src="https://user-images.githubusercontent.com/61069740/97276304-4a139f80-1837-11eb-9598-7471c47b913e.png">

An advantage of having this, is that the MOST often used features, would be right there, so one could work almost entirely, with visual script, or so . . To save space, one would prob. use classic icons, or so, from other software, cogs, for settings, ' ? ' question mark, to go to documentation, etc etc . .

![2020-10-27 0925](https://user-images.githubusercontent.com/61069740/97276437-76c7b700-1837-11eb-8ed0-24a813ee7186.jpg)

I've made other suggestions before, but I think doing it this way, would 'complete' visual script, as a ' visual ' ONLY alternative, to written code, and new users would never have to worry, about where to look, when they add a new box, for what they need, etc . . . <3 :O :O . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would allow visual script coding to OPTIONALLY be done only in the script canvas, by clicking the boxes, expanding settings, etc etc . . It would help visual coders and, game makers get things done faster, and make visual script into what it is ' supposed ' to be, a full alternative, not replacement of course, for WRITTEN code, where everything is done, or 99 %, visually . . . <3 <3 . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See the above example, there's an error in the last picture, with the ' collapse toggle ', or so . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
As a new user, there's no way I can alter the engine, like this, and it makes sense, to have it . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, it'd sort of ' finish ' visual scripting, as an complete and, working alternative, to written code, and doing it this way, whenever one makes a new box, one won't realistically need more, for almost all cases, than what's in the boxes, no need to go to settings dock, inspector dock, so on . . Simply, a near - 100 % drag-and-drop, click and, ' work with ' boxes work-flow, or so . . .

Thanks <3 :O :O . .

**Comment by jasperbrooks79** [comment]
It would sort of mean, you could teach yourself visual script, by looking only at boxes, it'd be ' self - contained ', within the visual work-flow <3

**Comment by jasperbrooks79** [comment]
Last, this would be a nice thing, make so one can select some ' themes ', for how the boxes look, as one likes or, so . .
<img width="882" alt="2020-10-27 0950" src="https://user-images.githubusercontent.com/61069740/97278352-f5bdef00-1839-11eb-9509-ad72df618efa.png">

Thx . . .

**Comment by fire** [comment]
I don't understand your design.

> Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:
> See the above example, there's an error in the last picture, with the ' collapse toggle ', or so . . .

How would one implement this? Where would you get the collapsible toggle?

How is it different from modules? : https://gist.github.com/swarnimarun/06c223018b41e5dfd3012d0ff7e2c38e

**Comment by jasperbrooks79** [comment]
Sorry, I didn't check e-mail . . ok, so right now, if one wants to work mainly or, only with boxes, one can't do this . .

Modules, as far as I understand it, are like used for collapsing a bunch of math, or nodes into ' one ' node, a ' module ' . .

The stuff in the lower bar would be stuff like PRINT(_process), PRINT(_ready), or a ' ? ', that takes one, to documentation, for a visual script node box . .

for instance, most boxes, or some have an ' Expand Default Args ', or ' Use Default Values ', so one can make the boxes nicer, that setting is atm in the ' Inspector Dock ', not something one can change, in Visual script canvas, ONLY . . . However, the stuff that one could put in the lower panels, that one expands by clicking the triangle, in the lower corner, or maybe another place . .

You can CLICK an icon, or some other place, to EXPAND the lower panel, click same icon, it ' collapses ', or can't be seen . . .

<img width="586" alt="2020-10-28 1654" src="https://user-images.githubusercontent.com/61069740/97461718-4c145600-193e-11eb-9490-296480499cae.png">

![2020-10-28 1656](https://user-images.githubusercontent.com/61069740/97462023-9990c300-193e-11eb-94cd-2d3d4abc60fc.jpg)

So, you click an icon, or the little ' wedge ' thing, in the lower corner, to SEE the lower panel, like an ' expandable ' panel, it would be really cool, since one could put the most often used features or, functionality of, the boxes there, so when one makes a new box, one can CLICK it open, and see what the box is mainly used for, it will also make debugging faster, as there will be an ICON, that can PRINT any output port, to the console, maybe that needs to be PRINT()._ready, PRINT()._process and, PRINT()._physicsprocess . .

The whole point is, that problems or, issues one OFTEN runs into, also stuff like changing DEFAULT arguments, etc, could be done there, and when you get a new box, there will be icons for most common stuff . . For instance, I think having a ' ? ' symbol, that one can click, for each box, that takes one to a page, that explains EACH box, would be really cool, and those pages had an option, for people to write tutorials, or explanations, so if the devs haven't gone through all the boxes, the community can help fill it out, for them . . .

I find it very annoying, if I want to debug a BOX, that I have to find the main logic line, put a PRINT box in there, connect the wires, and it looks like a mess, often, having to move many boxes, or it looks really weird . . If there was an expandable panel, where I could click on a ' PRT ' icon, then I get a 3-point menu, PRINT_ready, PRINT_process, PRINT_physicsprocess, and, I can select which output port I want to PRINT, could be ONE example, of making visual script more user - friendly, to visual coders, and bring it closer to WRITTEN code, where one can always write PRINT(), and not have to move a ton of, lines of code, to make room, for it, or so . .

**Comment by jasperbrooks79** [comment]
another example, of something that could be there, was a button, to see ' Use default args ', sort of, so you just click a button, and you see every-thing, the box can do . . The thing is, putting the most common functions or, stuff related to visual script there, would mean that when you start learning visual script, and you get a new box, you don't know how to make work, you just click that button, and it teaches you most things, and helps in debugging, like described above, or so . .

either, it could be a ' wedge ' type icon, in the TOP header, click there, and you get a panel, at the bottom, of a box, or so . .

if one made TWO panels, like in first post, one panel could be for debugging tools, the next, for functionality, related to default args, so on . .

For instance, in the lower panel, I'd like a icon, to ' ? ', that takes me to the official docs, for the particular node, and a PRINT icon, that lets me print any output value, of the box . . maybe this is a bit dumb, I'm not sure, since when one wants to PRINT something, it's important where one places it, in the flow, of logic, like should one PRINT before, or after SET a var, or so, that wouldn't work . .

The idea was, that one could make a box, and work 100 % visually, or close, and avoid having to use the docks, like the Inspector Dock, so on . . However, I'm not sure, also you asked how to ' open ' or, collapse the lower panel, you just click an icon, on the box, or a little diamond, or corner, like the second picture, in the directly above post . . <3

Sry, if this is very dumb, I'm noob, I'd like to work as much, as possible, with the boxes, if that makes sense, and only need to use the other docks, for advanced features, or so . . Not sure, your criticial questions have made me wonder <3

**Comment by jasperbrooks79** [comment]
here's an example, of something I think could be, an ' icon ' on the box, instead of a setting, in the docks . .
![2020-10-28 1717](https://user-images.githubusercontent.com/61069740/97464706-87fcea80-1941-11eb-8305-5b9ef56ccb79.gif)

If it was done well, then one could work almost 100 %, in the boxes, no need to use menus, or such . .

**Comment by jasperbrooks79** [comment]
so, when you click the icon, on the box, it works like this . .
![2020-10-28 1723](https://user-images.githubusercontent.com/61069740/97465493-62bcac00-1942-11eb-82aa-972dee0fa6ee.gif)

then, in that panel there could be a ' ? ' icon, that takes you to the official docs, for the visual script node,

**Comment by kreaninw** [comment]
> here's an example, of something I think could be, an ' icon ' on the box, instead of a setting, in the docks . .
> ![2020-10-28 1717](https://user-images.githubusercontent.com/61069740/97464706-87fcea80-1941-11eb-8305-5b9ef56ccb79.gif)
> 
> If it was done well, then one could work almost 100 %, in the boxes, no need to use menus, or such . .
> 
> I think that option should be an ' icon ' on the box, bec. it makes sense, and also when you make a new box, you prob. want to start clicking all the buttons, to learn what they do, so it helps learn visual script, more fast, or so, Thanks . . .
> 
> That's, the idea . . To make it so, one can work ' only ' or, more so with the boxes, no need for the menus, etc . . <3

I vote for this idea. Currently, I have to toggle fullscreen all the time to have the inspector tab back just so I can change the number of arguments or set the node's mode (self, node path, instance, basic type). I think these are a very basic feature that you will use all the time when you're working with Visual Script.

I mostly work fullscreen with the Visual Script editor in order to get more nodes into my sight.

**Comment by jasperbrooks79** [comment]
Ok, I'm not sure if I thought it all through, maybe this is something that isn't ' possible ', when one actually attempts it, the idea is sort of, there are many features, in a box, that you need to access through menus, but maybe this is like redundant, not sure . . .

The goal would be, to make so one could work more exclusively visually, ie. not use menus, so on, and have to EASIER, faster tools located in the lower panel, for debugging, settings, ' expanding ' default arguments, just over-all, to have some near-standard symbols there, and to allow users to work more exclusively in, the visual format, with less need, to use the other docks, but I thought one could add a PRINT(_ready), PRINT (_process), to any box, but the problem becomes, WHEN is the PRINT supposed to be called, in all the logic . .

I guess it was a nice idea, maybe I'm not smart enough, for it to work, tbh it seemed a good idea, but maybe there are too many problems in it, not Completely sure Thx . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
