### ISSUE TITLE
GDScript: Prevent circular dependencies 

### ISSUE THREAD

**Issue by ShalokShalom** [godotengine/godot-proposals#1737]
**Describe the project you are working on:**

Independent from project, round-based strategy game.

**Describe the problem or limitation you are having in your project:**

Circular dependencies can still happen.

**Describe the feature/enhancement and how it helps to overcome the problem or limitation:**

The core idea is to prevent circular dependencies by requiring the file order and code order to be strictly in sync with the dependency order.

This can also be done optionally, in case it is seen as too intrusive as a default setting. 🙂

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

FSharp does this already. [See here why and how](https://fsharpforfunandprofit.com/posts/cyclic-dependencies)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No. 

**Is there a reason why this should be core and not an add-on in the asset library?:**

Since GDScript is in core and it's a clear improvement to it.
Much fun 🥳

**Comment by Xrayez** [comment]
See related closed issues: https://github.com/godotengine/godot-proposals/issues?q=is%3Aissue+is%3Aclosed+cyclic

This is currently treated as a bug: godotengine/godot#21461.

But in my opinion, I'd just reopen #460 to avoid duplicate reports. 😛

**Comment by ShalokShalom** [comment]
This is all not quite the same as preventing circular dependencies in the first place, thanks a lot for your intent. 😊

**Comment by Xrayez** [comment]
@ShalokShalom sorry, I suggest to elaborate on your proposal. 😮

**Comment by ShalokShalom** [comment]
Once circular references are possible, a circular dependency is possible too. This suggestion prevents it.

**Comment by vnen** [comment]
You should really add some examples here. In which way are circular dependencies allowed? The only way I see this happening is with `preload` and inheritance, and both have checks to avoid cycles.

Unless you mean every cyclic reference is also a cyclic dependency. But if we remove that it's pretty much impossible to use static typing.

Also not sure what "file order" means here since GDScript files are compiled individually.

**Comment by MonoGameDev** [comment]
> Unless you mean every cyclic reference is also a cyclic dependency. But if we remove that it's pretty much impossible to use static typing.

Just out of curiousity, what exactly makes it so difficult to implement static typing while allowing cyclic references? I'd imagine, that you could just check if a class has already been loaded and if so, use it for auto completion.
But I assume there is some deeper reason for why that doesn't work, right?

**Comment by Calinou** [comment]
Support for cyclic references is being added in https://github.com/godotengine/godot/pull/65752 (only for 4.0 – it won't be backported to 3.x).
