### ISSUE TITLE
Add multi-select for tracks for AnimationPlayer // Alternatively add way to change interpolation method for all tracks with one select

### ISSUE THREAD

**Issue by SaffronStreams** [godotengine/godot-proposals#174]
**Describe the project you are working on:**
For any 2D project, really. I've had this comfort problem during many game jams.

**Describe the problem or limitation you are having in your project:**
I've asked around and there seems to be no way to change the interpolation mode for multiple tracks in AnimationPlayer.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Take one character. After bone rigging I have an Animation with 38 tracks (pos + rot), if I want to switch the interpolation mode to cubic, which often yield more natural results for animating characters, I need to click 76 times (once on interpolation setting of that track, once for selecting a certain setting). I feel like it could be 2-4, with either a dropdown at the top that changes the setting for all tracks, or with a multiselect (click first, shift click last, click interpolation, select interpolation). So a potential save of 50+ clicks, depending on model complexity. For one animation, even in game jams I have 3-5.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![proposal](https://user-images.githubusercontent.com/50481103/67234050-ada90700-f444-11e9-8433-7239eaeca096.png)

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not to my knowledge, but I'm far from expert level.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This ease of use seems handy for anyone using Godot. I have no 3D experience, but their animation node might work the same?

**Comment by Calinou** [comment]
For the record, this seems to be different than https://github.com/godotengine/godot/pull/30778.

**Comment by ccLouis** [comment]
As of Godot 3.2, I've noticed this is possible provided that the tracks being selected are of the same property - ie. both tracks are position, or rotation_degrees etc.

If two tracks of different properties are selected, only the time property can be changed.

Since tracks are sorted by node and not property, unfortunately it's still extremely difficult to make large, quick adjustments to the easing. 

Characters or objects with 30+ nodes resulting in 60+ tracks are impractical to animate at the moment, the best solution currently to animate in 3.0 and import to 3.2.

**Comment by SaffronStreams** [comment]
I am currently working on a Drider Priestess animation. It has 96 tracks. Like always, I would want cubic interpolation for most of my tracks (12 animation principles; slow in, slow out) but just doing it for one track is **nearly 200 clicks**. Imagine being able to do it in 4 (select first, shift select last, open interpolation dropdown, select cubic).
![tracks1](https://user-images.githubusercontent.com/50481103/82911940-c47c8280-9f6c-11ea-9df4-5ef692b2361e.png)
![tracks2](https://user-images.githubusercontent.com/50481103/82911942-c5151900-9f6c-11ea-9685-ea5c65bb9675.png)
![tracks3](https://user-images.githubusercontent.com/50481103/82911945-c5151900-9f6c-11ea-8ad0-707f61aeb142.png)
![tracks4](https://user-images.githubusercontent.com/50481103/82911932-c3e3ec00-9f6c-11ea-8655-4bd5a245be11.png)

**Comment by Calinou** [comment]
> Like always, I would want cubic interpolation for most of my tracks (12 animation principles; slow in, slow out)

I wonder if we should default to cubic interpolation by default at some point.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5243, as it contains more implementation details.
