### ISSUE TITLE
Allow local port control on net_socket connections

### ISSUE THREAD

**Issue by dam-coder** [godotengine/godot-proposals#1744]
**Describe the project you are working on:**
Simple game with local and online multiplayer capabilities.

**Describe the problem or limitation you are having in your project:**
I need control over the local port used in the network connections so I can connect players in peer-to-peer (no server-in-the-middle) mode. To do so I need to use NAT traversal techniques that require me to be able to:
- specify which local port I want to use;
- know which local port is being used.

Although `NetworkedMultiplayerENet` already allows to specify the local port to be used, you might want to get a random port to avoid choosing an unavailable one. In such case there's no way to know which one got assigned to you.
Other networking related classes that do not support local port control are:
- `PacketPeerUDP`: cannot set/get local port;
- `StreamPeerTCP`: cannot set/get local port;
- `TCP_Server`: cannot get local port;
- `UDPServer`: cannot get local port.

One last note: Since this is a fast-paced game, it is very sensitive to network delays which motivated me to use a peer-to-peer connection between the players.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This limitation can be overcome with two features:
- allow to state which local port the connection will use;
- provide a way to know which local port is currently being used by the connection.

Such will allow greater control and the ability to perform NAT traversal.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I've implemented the proposed features and created a pull request for `master` branch: [godotengine/godot#43174](https://github.com/godotengine/godot/pull/43174)
This pull request implements all the missing local port controls stated above:
- `NetworkedMultiplayerENet`: set and get local port;
- `PacketPeerUDP`: set and get local port;
- `StreamPeerTCP`: set and get local port;
- `TCP_Server`: get local port;
- `UDPServer`: get local port.
In case you do not set a specific port, the operating system will provide one of the ephemeral ports, if any is available, or an error otherwise.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
My understanding is that this will be used often and it cannot be worked around.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This seems to be a core feature as it needs to interact with the underlying mechanisms of the net_socket.

**Comment by Faless** [comment]
Partially addressed via https://github.com/godotengine/godot/pull/47398
The ENet part is here: https://github.com/godotengine/godot/pull/48235

**Comment by Faless** [comment]
Both PRs mentioned above are merged. Closing as fixed.
