### ISSUE TITLE
Add `get_version_count()` method in UndoRedo

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1745]
**Describe the project you are working on:**
I'm creating a plugin, where I need to know current `UndoRedo` version count

**Describe the problem or limitation you are having in your project:**
It seems thee's no way to get version count.
The lack of this feature limits creating plugins which use `UndoRedo`.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding `UndoRedo` `get_version_count()` would solve the problem

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`int get_version_count()`
`get_version_count()` = `get_version()`+ Σ can_redo

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
not possible

**Is there a reason why this should be core and not an add-on in the asset library?:**
`EditorPlugin` feature

**Comment by KoBeWi** [comment]
> I'm creating a plugin, where I need to know current UndoRedo max version.

But what do you need it for? Knowing more details would be useful.

**Comment by me2beats** [comment]
The example I was trying to implement is Undo Slider like in Zbrush.
The idea is for the user to be able to do undo/redo using a slider.

But this is also true for creating an undo history list of any other kind (for example like in Blender).
(although in this case I would also need to get the text of the action when the version changes, I think it is worth creating a separate proposal for this)

That is without getting the number of all undo points, it is impossible to correctly create plugins to work with undo history.

**Comment by L4Vo5** [comment]
The method was added, so this should be closed

**Comment by KoBeWi** [comment]
Yes, it's called `get_history_count()`.
