### ISSUE TITLE
Add `get_action_name()` method in UndoRedo

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1746]
**Describe the project you are working on:**
I'm trying to create undo history plugin that shows undo history list and allows to go to some undo point (this feature is in many apps for example in Blender).

![get_action_name](https://user-images.githubusercontent.com/16458555/97589143-024f6c80-1a1f-11eb-986f-e8ca0c6a55e5.JPG)

**Describe the problem or limitation you are having in your project:**
The problem is I can't get names of all undo points (actions/versions).
There is only `get_current_action_name()` but this is not enough for the task.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
adding `UndoRedo` `get_action_name()` by version index would solve the problem

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`String` `get_action_name(version:int)`
Gets the name of action by version number.

also when implementing this method it would be logical and convenient to have [the count of all versions](https://github.com/godotengine/godot-proposals/issues/1745)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think this is possible

**Is there a reason why this should be core and not an add-on in the asset library?:**
`EditorPlugin` feature

**Comment by L4Vo5** [comment]
The method was added, so this should be closed
