### ISSUE TITLE
Add a way to temporarily disable error printing in the engine

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot-proposals#1763]
**Describe the project you are working on:**
[Goost](https://github.com/goostengine/goost) Godot Engine extension.

**Describe the problem or limitation you are having in your project:**
I happen to write unit test in GDScript using GUT, and this works well for most cases. I also want to test for failure paths from within GDScript itself for best coverage (like testing bad index to prevent crashes). The problem is that these kind of erroneous operations produce error prints in the debugger and console:

```gdscript
func test_choice_empty():
	# Should not crash.
	assert_null(Random.choice(""))
	assert_null(Random.choice([]))

```

![goost_err_catch_ok](https://user-images.githubusercontent.com/17108460/97927839-75821700-1d6e-11eb-9710-b8e5d78ab210.png)

The above problem can be seen in goostengine/goost#31.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I propose adding a method which allows to dynamically enable and disable error printing. Having ability to temporarily disable those errors allows to filter out the noise coming from "expected failures" seen in tests.

I've even written unit testing documentation describing this technique in [Testing failure paths](https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html#testing-failure-paths) section when writing unit tests in C++. The same thing should be possible to do from within Godot to work both in the console and the editor.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The approach would be similar to existing `ERR_PRINT_ON` and `ERR_PRINT_OFF` test macros in `tests/test_macros.h`. The method can be added to `OS` singleton, such as `OS::set_error_print_enabled()`. The missing part is that it should also apply to Godot's debugger in the editor.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Impossible to prevent error prints in the debugger *selectively*. It's possible to disable error printing via `application/run/disable_stderr` project setting, but that only prevents terminal output, and the idea here is that it should be possible to do this at run-time as well.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Can only be done on the engine level.

**Comment by Calinou** [comment]
Maybe this should be a property in the Engine singleton which can be set at run-time?

`Engine.print_errors = true/false`

**Comment by Xrayez** [comment]
Could this be backported to 3.x? I'm in dire need for this in 3.x, see for instance goostengine/goost#106.

I can do this myself if approved.

**Comment by Calinou** [comment]
> Could [godotengine/godot#48359](https://github.com/godotengine/godot/pull/48359) be backported to 3.x? I'm in dire need for this in 3.x, see for instance [goostengine/goost#106](https://github.com/goostengine/goost/pull/106).
> 
> I can do this myself if approved.

Sure, feel free to backport it to `3.x` :slightly_smiling_face:
