### ISSUE TITLE
Allow compiling godot scripts and scenes to C# library

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1764]
**Describe the project you are working on:**
A C# Game Editor

**Describe the problem or limitation you are having in your project:**
I want to make a set of tools using C#  and compile it to a library

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Allow us to build C# libraries with C# scripts and scenes

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I would guess we would be able to compile our project to a library through visual studio by referencing a godot nuget package

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know for other people but I would use it to make a my own dedicated game engine

**Is there a reason why this should be core and not an add-on in the asset library?:**
Its wouldn't be in core since it would be a nuget package

**Comment by Calinou** [comment]
Do you have any practical use cases for this? [Godot isn't designed to be used as a library](https://docs.godotengine.org/en/latest/about/faq.html#is-it-possible-to-use-godot-as-a-library).

**Comment by aaronfranke** [comment]
So you just want to put Godot scenes into a nuget package? This should already be possible, nothing is preventing you from doing this. Godot itself isn't designed to be a library, but you can have your own project be a library.

**Comment by Shadowblitz16** [comment]
@Calinou @aaronfranke  The idea is that I can make my Scenes, and C# scripts and package them in a library I can use in a C# project.

It would allow the user to use godot as more then a game engine, but also a tool.

**Comment by Calinou** [comment]
Closing, as converting a scene to a C# library is not technically possible.

Converting GDScript to C# *is* technically possible, but it's a ton of work to do correctly and is considered out of scope for the Godot editor. There's a [third-party GDScript to C# conversion tool ](https://github.com/HaSa1002/codetranslator) available, but it only handles basic syntax changes.
