### ISSUE TITLE
Can't change drag margins below 0

### ISSUE THREAD

**Issue by PinyaColada** [godotengine/godot-proposals#1768]
Now I am doing a platform game, with a game of this type the drag margins should be something like this:
![image](https://user-images.githubusercontent.com/72302480/98018240-9d21bf80-1e00-11eb-8e39-1c2287363be9.png)

But in godot the drag margins are from 0 to 1, there is no offset of the margin and this is the best I can obtain:
![image](https://user-images.githubusercontent.com/72302480/98018368-be82ab80-1e00-11eb-8d15-8ceccb4b9d5f.png)

I worked in another open source projects and seems like something easy to change, what I should look to change it? Or is there any way to do what I want already? Thank you for your time.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
