### ISSUE TITLE
Keep fullscreen state from previous session

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-proposals#1770]
**Describe the project you are working on:**
Arcade space shooter.

**Describe the problem or limitation you are having in your project:**
I like working in full screen in the editor, but have toggle it on every time I open it. Also, some games open in window or fullscreen mode, depending on what you used the last session / prefer (and also mine).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Remember fullscreen state between sessions.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
OS.window_fullscreen = previous_session_fullscreen

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
In editor, don't know how. In game, yes.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Small usability improvement.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/32056 which implements this feature, but needs to be redone for the `master` branch.

**Comment by boukew99** [comment]
Okay good to know, thanks!
