### ISSUE TITLE
Fix low_processor_usage_mode on Android

### ISSUE THREAD

**Issue by Altair1234** [godotengine/godot-proposals#1771]
I'm working on a todo app with extra features. I have this project in Android Studio and I'm trying to move it to Godot, given the longer dev time on AS compared to Godot.

Godot by default isn't meant for non-games and causes excessive battery drain while using simple apps, which is undesirable. 

Fixing the low-processor usage mode will enable full development of Godot apps on Godot. Current implementation causes flickering.

Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams: Not applicable imo

If this enhancement will not be used often, can it be worked around with a few lines of script?: Other options like capping frame rate and optimizing code won't be as effective. I think Android devs can use this often.

Is there a reason why this should be core and not an add-on in the asset library?: As the feature is available for desktop environments, I think it should also be available for mobile ones.

**Comment by Calinou** [comment]
This is a bug, not a feature proposal: https://github.com/godotengine/godot/issues/19304

**Comment by Altair1234** [comment]
Isn't the current decision to altogether disable it for mobile? I'm proposing that it's included as a fully supported feature instead.

**Comment by Calinou** [comment]
@Altair1234 Low-processor mode is technically attempted to be used, but it's broken

**Comment by Altair1234** [comment]
So no one is currently working/interested in working on it for the time being?

**Comment by Calinou** [comment]
@Altair1234 Nobody knows how to fix it :slightly_smiling_face:
