### ISSUE TITLE
Make a CompositeAnimationPlayer node for making cut-scenes and dialogue more easily . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1772]
**Describe the project you are working on:**
A Tomb Raider game, with magic system, a bit more . . . .

**Describe the problem or limitation you are having in your project:**
I really want to make cinematics, video sequences, so on, but right now I have to code it, and it's very difficult . . My interest in Godot is telling stories and, the artistic side, and I've seen Unity has something called Timeline, it's a drag-and-drop program, where one can drag video sequences ( similar, to AnimationPlayer stuff ), and trigger Audio events, and place camera animations . . It's a very simple ' sub-program ', but it really helps visually oriented teams put their animations, audio, and 2D text ( sub-titles ) in a composite animation, ie. one calls the player walk animation, for 2 seconds, while the camera, is panning over, the animation, and one can call 2D elements, like text-dialogue boxes, and also audio, from AudioStreamPlayer nodes, so one can quickly set up a linear animation, audio, and UI element sequence . . I know it's technically more correct, to CODE it, but as a visual script user, it would really help me ' churn ' out animations, cinematics, or prototype them . . It would work like this, or so . .

<img width="1920" alt="Skærmbillede (649)" src="https://user-images.githubusercontent.com/61069740/98111000-423fa500-1ea0-11eb-8287-483bfa9934d0.png">

It would look something, like so . .
<img width="1628" alt="Skærmbillede (648)" src="https://user-images.githubusercontent.com/61069740/98111468-f04b4f00-1ea0-11eb-9436-71cd885ec220.png">

So, one could drag and drop animationplayer node animations ( that could trigger animations, but also trigger particlesystems on, so on, or dialogue boxes as visible, or so ), and play them side-by-side, with AudioStreamPlayer stuff, or such . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I'm a visual story-teller, mostly, and my use-case for Godot is, the telling of stories, through dialogue, animations, sound, so on, this feature would really help me use the engine, as a beginner, and technically it'd just be a node, that can combine or, composite several animationplayer animations, and audiostreamplayer sounds, in a visual graph, a bit easier, for artists . . It would allow me to do about 80 - 90 % of animation problems or, situations I could ever want, and it'd really help me, and would help less code-oriented teams do, the same, very fast . . I know it's a noob solution, to coding it, but for me, that is very difficult, having such a node, would really help me, especially if the different events or, so were represented with different colored bars ( maybe one could select a custom color, for each event, or so, would, be nice . . ) Since Godot is getting such amazing graphics, just stunning, for ME, and maybe many others, this would be a nice way to create linear cut-scenes, in a user-friendly way, similar to Unity's current 'Timeline' program . . .

https://www.youtube.com/watch?v=G_uBFM3YUF4

Also, I think this would help many beginners, that are unfamiliar with code, to make their first project, with nice animation sequences, or so . . Maybe it could be called a SequencePlayer node, or an EventPlayer node, not sure . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See the above chart, a more drag-and-drop based method, as an alternative to hard-coding animations, audio events, that for me as a visual scripter, is very difficult, as a total beginner . . Thanks . . . <3

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm not sure, I'm not SO good at code yet, I feel I can do this, confidently, right now, Thanks . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, it'd be a simple node, and not that complex, a help to visual artists, or prototype animators, etc, that want to see what their amazing blender work looks like, combined with audio, and camera movement, almost, immediately . . .

Thanks, just, an idea . . . <3 <3

**Comment by jasperbrooks79** [comment]
Anyway, this is my own idea, it just makes sense to organize different animations, events or, audio this way, for making cinematics, intro-cut-scenes, other stuff . . <3

**Comment by jasperbrooks79** [comment]
Here's an example, from an Open Source video editor, one can drag animation clips, sound clips, so on, and combine them, as one, single animation, or 'event' . . .

![2020-11-04 1400](https://user-images.githubusercontent.com/61069740/98114921-440c6700-1ea6-11eb-9d83-07815f1f6e73.jpg)

So, it's like a CompositeEventPlayer node, or so <3

**Comment by jasperbrooks79** [comment]
Last, if one could move AnimationPlayer nodes either from the Scene Inspector Dock, OR, from the res:// folder, then for animations in a sub-scene, one could call animations, from the entire game archieve . .
<img width="1920" alt="Skærmbillede (650)" src="https://user-images.githubusercontent.com/61069740/98115943-e0833900-1ea7-11eb-82a4-e073dbb44c3c.png">

This way, if there is an animation, in a .glTF, I could import it as, ' Separate Scenes ', and access any animation, or audio event, very quickly <3 . . .

**Comment by Arrow-x** [comment]
The AnimationPlayer Have access to any properties of any Node in the current scene (just click on the key icon beside the the property, while selecting the AnimationPlayer Node). it will create a track for it, and you can edit it's value and key them to your liking.
sure it is not drag and dropping, and you can't organize or sort the tracks, but you can do all the above.

**Comment by Arrow-x** [comment]
Godot's AnimationPlayer Node have an animation track (click on the + icon besides Add Track), just select another AnimationPlayerNode in the current scene (that have refrence to the animations) and chose in the inspector what animation you want to play, (Just like [here ](https://docs.godotengine.org/en/stable/tutorials/animation/introduction_2d.html#advanced-call-method-tracks) but with animation Playback track) there is also an audio track, methode calling track ...etc

**Comment by Arrow-x** [comment]
Godot's AnimationPlayer Node have an Animation Playback Track (click on the + icon besides Add Track), just select another AnimationPlayerNode in the current scene (that have reference to the animations) right click in the timeline, and add a key, select it and chose in the inspector what animation you want to play, (Just like [here ](https://docs.godotengine.org/en/stable/tutorials/animation/introduction_2d.html#advanced-call-method-tracks) but with animation Playback track) there is also an audio track, methode calling track ...etc
to be fair this is undocumented AFIK, but 99% of what you want can be done without code, it just lacks the Drag and Dropping

**Comment by Arrow-x** [comment]
so this proposal should be closed

**Comment by jasperbrooks79** [comment]
ok, thank you, I was looking for the Unity stuff, didn't know, Godot is new program, to me <3

**Comment by NathanLovato** [comment]
I'll let the author close the proposal if they think the feature is there.

**Comment by NathanLovato** [comment]
@jasperbrooks79 is it okay to close this proposal?

**Comment by Arrow-x** [comment]
@NathanLovato you were asking about features that are undocumented a while back, well here is one!

**Comment by NathanLovato** [comment]
This feature is documented here: https://docs.godotengine.org/en/latest/tutorials/animation/animation_track_types.html

Maybe not in the best way, but at least it's not completely absent of the docs

**Comment by Arrow-x** [comment]
nice! but it is in latest, but not in stable, and I usually don't look up the latest branch (I should though it seems)

**Comment by NathanLovato** [comment]
That's currently how it is, due to the absence of an active maintainer on the docs, we don't have someone who'll take the hours to selectively backport changes to the 3.2 and then to the stable branch. Changes happening on master include docs for Godot 4.0, which aren't compatible with 3.2. Some updates in the 3.2 branch have to be manual and are time-consuming as a result.

**Comment by Arrow-x** [comment]
so is a new member in the community welcomed for this kind of work? (go over every merged PR, check if it applies to 3.2 and make changes to it if does not, Open a new PR)

**Comment by NathanLovato** [comment]
Absolutely! The workflow for that would be to cherry-pick changes first if possible: writing down commit ids that could apply to the 3.2 branch, create a new branch from 3.2, use the `git cherry-pick` command to apply the list of commits, and finally creating a pull request. That's how Akien ports features and bug fixes from Godot 4.0 / the godot master branch back to 3.2.

**Comment by Calinou** [comment]
Closing per the above comments, as this is already implemented.
