### ISSUE TITLE
Tilemap editing while navigating tilesets is a bad experience that should be improved

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1773]
**Describe the project you are working on:**
platform game

**Describe the problem or limitation you are having in your project:**
Editing tilemaps and finding tiles while using tilesets is so cumbersome and difficult

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

1. You cannot view the tileset while editing maps
2. When you have a lot of tiles, it's impossible to find anything when you can only view a dozen tiles in the vertical slice at once.

solution:
1. Allow the tileset to be edited/viewed while the tilemap is selected and being edited
2. Allow a tile from the tileset to be automatically selected when going back to tilemap mode
3. Provide a means of viewing the tiles like inside the tileset editor for easy selection. The current system is a small vertical slice and expanding it wide to view a full tileset loses almost all of your tilemap. In addition see point 1.

Have a look at the image below, I am in the tileset editor. I am here because I want to look at a tile that I've pointed to on my tilemap. However, when you are in the tileset you lose all abilities in the tilemap, as seen, it's just an image now. If I switch to my tilemap I lose my tileset so it's impossible to work with both at the same time. This is pretty much how most people will work, they are in the tilemap and doing so is very painful having to swap between the two.

tileset below, lose ability to see tilemap
![image](https://user-images.githubusercontent.com/12863685/98112429-1b7e7000-1e9a-11eb-8588-029cb4fabf7d.png)

tilemap, lose ability to look at the tileset
![image](https://user-images.githubusercontent.com/12863685/98112655-69937380-1e9a-11eb-912e-77faeca71846.png)

Secondly, if you look at the image above, in the tileset you get to see almost EVERY tile and it's easy to find a tile. However, you cannot use this to then select a tile for editing in the tilemap. Instead you have to remember the tile id then go back to the tilemap, remember the id and somehow use the scrollbar (yes, you can filter, but you need to remember everything and entering a single ID number usually does not work) as you can only see 10 or so tiles at once. This process is painful.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
1. Allow the tileset to be edited/viewed while the tilemap is selected and being edited
2. Allow a tile from the tileset to be automatically selected when going back to tilemap mode

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by groud** [comment]
I am about to rework the whole Tilemap editor. See this proposal #1769

**Comment by chucklepie** [comment]
I know it was a proposal to do work, I didnt' know anything was concrete. I'm just offering some suggestions/feedback based on my experience from using large tilesheet based tilemaps almost every day for the past 6 months :)

**Comment by chucklepie** [comment]
I see your first point is to address this, sorry I didn't realise.

But one thing I do hope is being done and I never saw it, was making it easier to create collision polygons, etc from tiles. At the minute you have to click on every tile, one at a tile, and create a collision shape.

**Comment by groud** [comment]
Ah I was about to answer ^^
Yeah no problem, proposals are meant for that.

**Comment by KoBeWi** [comment]
This is pretty much covered by #1769, so I'm closing as duplicate.
