### ISSUE TITLE
Add numerical RGBA raw sliders to modulate property inspector

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#178]
**Describe the projects you are working on:**

All my projects require to adjust the modulate property a ton. As soon as a WE node is added, this increases even more.

**Describe the problem or limitation you are having in your project:**

The current modulate value visualization in the inspector does not give me any information about it's actual value if it is above raw 1 and it's incredibly hard to judge which alpha value is given.
When working with modulate properties, there is no way around to open the color-picker and then switch to raw to see what are the set values. This becomes especially apparent while animating the modulate value and trying to set the right key. Much more so when a WorldEnvironment Node is present, because the representation of the value in the game is changed through the WE.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

- It would allow me to see on one glance what the modulate values are
- It would allow me to swiftly change the value by moving the slider or typing in a new value without having to go through menus. 
- It would allow me to instantly reset values, save a substantial part of dev time wastes on pointless clicking and trying to remember the last set values.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

![modulate_channels2](https://user-images.githubusercontent.com/47016402/67326683-2d070b00-f517-11e9-8776-1a31bfde0c99.png)

**Describe implementation detail for your proposal (in code), if possible:**
I would hope for these numerical slider adjustments right in the inspector to be present wherever the is a modulation preview. (under Canvas Item, in the AnimationPlayer key value panel, in shader_param ...)
I don't know C++.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Would be used often, because it would be the fastest way to intentionally change the modulate value, which currently is the only way to adjust color and alpha properties of a node in the editor.
Existing color-picker Workflow would be unchanged.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's an improvement of an existing UI/UX.

**Comment by Calinou** [comment]
This would make each color property occupy more space, so I'm not sure about this (unless the inspector is wide enough to allow displaying 4 fields side by side).

**Comment by golddotasksquestions** [comment]
Good points. Though I have considered all of them before making this proposal.

> This would make each color property occupy more space in the inspector

Yes I know. It's a tiny drawback but the alternative is a crippled UI with a UX that's terrible to work with when doing any actual work on a regular basis. 

> We could make all 4 fields display on a single line if the inspector is wide enough

This is the design I experimented with at first. If the RGBA values could only be displayed in the right column of the inspector, it would still be better than what we have now, the downside however would be that it would be a more clumsy to use, kind of circumventing the goal to make UX faster and more fluid. If we can use the whole inspector width, maybe there would be enough space. Having spelled out "Red Channel" also is al lot more informative about what is what to newcomers who do not have a degree in visual design. The slider makes a change happen in one fluid drag motion, no clicking through menus.

> but the fields should probably be hidden otherwise.

If the fields are hidden, this would make the whole thing pointless. Whenever modulate is visible, it should need one motion to change the value, just as it is with "position" or most if not any other node property.

> What about adding a tooltip that displays the exact values when hovering the property?

still horrible UIUX as a) this would require to hover over the color rectangle, waiting a few seconds as having them displayed right away is almost equally distracting when not doing it on purpose.
The wait time breaks flow just as much as clicking through popup windows, yielding no increase of speed, and to adjust the values, the user would then have to go into the pop up color picker menu anyway.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP).
