### ISSUE TITLE
Make `HTTPRequest.request()` return the response instead of emitting a signal

### ISSUE THREAD

**Issue by Tyrannosaurus1234** [godotengine/godot-proposals#1782]
**Describe the project you are working on:** A web crawler/interface for an internet forum.

**Describe the problem or limitation you are having in your project:** Because HTTPRequest.request() emits a signal containing the response to the request instead of the response itself, it's very cumbersome to make sequential requests. Instead of simply doing `var response = http.request(url)` and using it as necessary, you have to:

1. connect the HTTPRequest node to a receiver function that may vary based on the type of request
2. in the receiver function, either pass the response back to the function the request was initiated from, or make it a global
3. if you now want to use that HTTPRequest node for a different request that has to be interpreted a different way (i.e. it would have a different receiver function), you now have to disconnect it from the previous receiver function and connect it to the new one.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** It makes the process of multiple sequential requests entirely less cumbersome and confusing to manage, and brings it in line with how HTTP libraries in other languages (python `requests` for example) usually operate.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
var response = http.request(url)
print(response.body)
```
Depending on how HTTPRequest.request() was implemented behind the scenes, it could be non-blocking and thus require a `yield` or 4.0 `await` to apply sequentially, e.g.:
```
var response1 = yield(http.request(url), "completed")
print(response1.body)
var response2 = yield(http.request(url), "completed")
print(response2.body)
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** Anyone who uses the HTTPRequest node would be using this constantly, and if there's a simple workaround, I'm not aware of it.

**Is there a reason why this should be core and not an add-on in the asset library?:** It is a fundamental change to a built-in node.

**Comment by nathanfranke** [comment]
TIL HTTPRequest is a node... I think we should make it a singleton instead with this new behaviour- Perhaps for 4.0 we should rework HTTPRequest?

**Comment by jonbonazza** [comment]
You can't make HttpRequest.request() return a response without making it blocking, which is not a good tradeoff imo.

**Comment by nathanfranke** [comment]
> You can't make HttpRequest.request() return a response without making it blocking, which is not a good tradeoff imo.

It can return a GDScriptFunctionState which can be `await`-ed in Godot 4.0

```
var response = await HTTPRequest.request("https://example.com/")
```

**Comment by jonbonazza** [comment]
> > You can't make HttpRequest.request() return a response without making it blocking, which is not a good tradeoff imo.
> 
> It can return a GDScriptFunctionState which can be `await`-ed in Godot 4.0
> 
> ```
> var response = await HTTPRequest.request("https://example.com/")
> ```

Right, but that's not returning the respinse itself. That's returning a "future" (or "promise" or w/e you want to call it) that can be used to get the response--which i think we absoluteky should do for 4.0. But that's not the same thing.

**Comment by nathanfranke** [comment]
Understood, let's make those changes for 4.0 only since they're compatibility breaking regardless.

**Comment by Tyrannosaurus1234** [comment]
Just a small update with something I learned very recently: you can skip creating a receiver function to connect the "request_completed" signal to by simply assigning a variable to a yield to that signal, e.g.:
```http.request("http://example.com")
var response = yield(http, "request_completed")
# result, status code, response headers, and body are now in indices 0, 1, 2, and 3 of response```
I feel a bit dumb for not realizing you could do that before.

**Comment by jackgriffith03** [comment]
Sorry for necro, but I would like to second the request. When using 'yield' in a function as described above (i.e. assigning the HTTP response to a variable), the variable is scoped to the function and can't be returned as a value; you get a 'GDScriptFunctionState' instead. It would be convenient to get the response back without needing to worry about signals.

**Comment by nathanfranke** [comment]
> Sorry for necro, but I would like to second the request. When using 'yield' in a function as described above (i.e. assigning the HTTP response to a variable), the variable is scoped to the function and can't be returned as a value; you get a 'GDScriptFunctionState' instead. It would be convenient to get the response back without needing to worry about signals.

You need to yield for the gdscript function state too, since it is an asynchronous task.

```
var result = yield(my_func(), "completed")
```

> You can't make HttpRequest.request() return a response without making it blocking, which is not a good tradeoff imo.

> Right, but that's not returning the response itself. That's returning a "future" (or "promise" or w/e you want to call it) that can be used to get the response--which i think we absolutely should do for 4.0. But that's not the same thing.

So do you want it blocking or not?
...

**Comment by Faless** [comment]
As mentioned you can simply `yield(http, "request_completed")` (or `await http.request_completed` in `4.0`).
`request` simply returns an error if the request fail to start at all.

**Comment by rteijeiro** [comment]
I'm trying to use `await http.request_completed` but as stated in this issue, there is no way to get the response directly unless you connect it to a signal. Am I missing something?

**Comment by Juna-Idler** [comment]
> `await http.request_completed`

Apparently it can be done with "`var res = await http.request_completed`", but I can't find any description in the official documentation.

**Comment by Calinou** [comment]
> (I have never seen how "await" can be used to receive a "signal" argument.)

`await get_tree().process_frame` is a common pattern to wait for 1 frame before running more code, and `process_frame` is a signal from SceneTree :slightly_smiling_face: 

More information: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#awaiting-for-signals-or-coroutines

**Comment by Juna-Idler** [comment]
I know that, but I've never seen this usage.
`var params = await signal_with_params #(it is not coroutine)`
