### ISSUE TITLE
OS Theme resources

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1789]
**Describe the project you are working on:**
None right now

**Describe the problem or limitation you are having in your project:**
None with my project but more so with the editor.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Can we have a theme resource which takes the current windows, mac, or linux theme and translates it for godot?

Windows < 10: Win32 themes
Windows == 10: UWP themes
Mac: aqua?
Linux: Gtk

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I would guess it would be a type of theme resource where we just plug into godot or our root control and it makes it looks like a native app.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think the current theming support is good enough right now so it would have to be improved for this.
It also would not take just a few lines of script

**Is there a reason why this should be core and not an add-on in the asset library?:**
I realize this might require alot of code maybe it could be a official plugin?

**Comment by Calinou** [comment]
> Can we have a theme resource which takes the current windows, mac, or linux theme and translates it for godot?

It doesn't work like that.

To get a "native" look and feel, you need to reimplement the whole theme from scratch, which can take an inordinate amount of time. Since games don't need a native look and feel, we think this is better left as a third-party add-on.

**Comment by Shadowblitz16** [comment]
@Calinou the issue is it not possible right now to implement such a plugin.
Godot's themes and styles are too limited in what they can do.
I couldn't even make an accurate win95 theme.

I think not only would implementing such a feature be a good official addon.
but implementing it would help the godot devs improve the existing ui system.

I also think games could definitely use native OS look and feel for editors.
It would also allow people to easily develop tool applications in godot easily

**Comment by pycbouh** [comment]
> Godot's themes and styles are too limited in what they can do.

Then your proposals should be about particular Theme resource customization limitations. After those are resolved the actual implementation of such themes can be left for users.

**Comment by Shadowblitz16** [comment]
This is not just about game developers using os themes it's about the godot editor itself obeying os themes.
Especially on linux where people like a consistent look.

I shouldn't have to report every little problem with the ui system when their is a a truck ton of them and the devs could improve it themselves by implementing this feature.

I doubt they would be added anyways due to the fact my focus style suggestion as been closes 2 times now.

**Comment by pycbouh** [comment]
> I shouldn't have to report every little problem with the ui system when their is a a truck ton of them and the devs could improve it themselves by implementing this feature.

As it was explained, Godot doesn't rely on system vendor libraries for the UI. It would be detrimental for the engine to do so.

**Comment by Shadowblitz16** [comment]
how would it be detrimental?
It literally could be a optional plugin that wasn't shipped with the core

**Comment by pycbouh** [comment]
You don't need a proposal for a addon ot a custom module, so I weigh it assuming core improvement. Engine doesn't need this as proposed, but may actually benefit from Theme resource improvements.

**Comment by Shadowblitz16** [comment]
I am suggesting it because I think it would be a good official feature and would require a team to impliment.
however it would bloat the engine and I think godot should start publishing official packages to the godot package manager

**Comment by Shadowblitz16** [comment]
wxwidgets might be able to be used to create a rendering backend for this.

**Comment by Calinou** [comment]
> wxwidgets might be able to be used to create a rendering backend for this.

There are no plans to integrate "native" UI frameworks in Godot officially.

**Comment by Shadowblitz16** [comment]
I mean I guess but if that's the way your going to look at it I might as well learn allegro and make my own game engine

**Comment by Shadowblitz16** [comment]
This would require a very large amount of work.
Qt doesn't even get it right

I guess I opened this mainly to improve the theming system but idk.
