### ISSUE TITLE
Allow users to completely preview animation by scolling when dragging the timeline timestamp

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#179]
**Describe the project you are working on:**
Projects using the AnimationPlayer

**Describe the problem or limitation you are having in your project:**
I often click-drag on the timeline to quickly preview only sections of the animation or in the speed I need to check animation. This is very common behavior in pretty much any Software with animation capabilities and a timeline. Godot allows this, but only for the currently displayed time range. If I click and drag further outside the displayed range, I would expect the animation panel to start scrolling along until I move my cursor back into the displayed timeline or release my LMB.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It would help me preview animations that don't fit on my Animation Panel.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
This is what currently happens:
![drag_scroll_animpreview](https://user-images.githubusercontent.com/47016402/67449146-7a6ba100-f619-11e9-8231-966f8f29a1a3.gif)
I would expect it to start scrolling as soon as I drag the mouse outside the timeline.

**Describe implementation detail for your proposal (in code), if possible:**
I don't know how to code this.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's very common behavior for animators.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a small but relevant UX improvement.

**Comment by golddotasksquestions** [comment]
This works perfectly fine in 3.0.6 btw:
![timeline_scolling_3 0 6](https://user-images.githubusercontent.com/47016402/70684100-3bff7380-1ca5-11ea-8f8d-b53dd119ecf0.gif)

**Comment by asheraryam** [comment]
If this was working before and then broke, you could post an issue directly on https://github.com/godotengine/godot/ as a regression bug.

**Comment by golddotasksquestions** [comment]
@asheraryam 
https://github.com/godotengine/godot/issues/34362

**Comment by KoBeWi** [comment]
Closing this in favor of godotengine/godot#34362 as it's indeed a regression.
