### ISSUE TITLE
Improve theme editor

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1791]
**Describe the project you are working on:**
Zorin OS GTK Theme for Godot

**Describe the problem or limitation you are having in your project:**
Its very hard to go through all the controls and try to find out what does what

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I suggest adding all the controls to this panel (even sub controls)
![image](https://user-images.githubusercontent.com/2453707/98452717-ab285680-2106-11eb-89e3-51445a6f8596.png)

Then I suggest instead of this massive list
![image](https://user-images.githubusercontent.com/2453707/98452738-d448e700-2106-11eb-9c25-e9954dc69ee1.png)
It would show something like this for the control you have selected...
![image](https://user-images.githubusercontent.com/2453707/98453018-884b7180-2109-11eb-826c-20095e23fae1.png)

Each control would have these properties and icons would in a icon group for press hover, focus, normal, and disabled

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See above

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This might be able to be worked around but why?
This systems is better and makes theme editing mush easier

**Is there a reason why this should be core and not an add-on in the asset library?:**
It a improvement over the existing one

**Comment by lentsius-bark** [comment]
I have worked with themes in Godot a fair bit and I do remember it took me a long while at times to find the right one to tweak an import. Having the option of the bottom panel theme viewer that would, for instance, allow you to choose which components to add to the theme and also let you click the one you want to edit would indeed be amazing.
One idea that popped into my mind whilst reading this proposal would be that the bottom theme panel having two tabs, one for your current theme and another for the list of all available themeable components, using the second tab for activating them within your theme resource and the first tab for seeing what your theme looks like.

**Comment by EricEzaM** [comment]
Could be merged with #1438

**Comment by barbaros83** [comment]
this proposal sounds very good, i would like to add 1 more thing, and that is a global override for all the theme settings, that way, you could set your standard theme 1 time, and edit those corner cases where you would want something diffrent

**Comment by pycbouh** [comment]
> a global override for all the theme settings, that way, you could set your standard theme 1 time, and edit those corner cases where you would want something diffrent

That's already possible, is it not? You add your main theme to the topmost control, and it propagates through the whole branch of controls, and you can override individual controls with either sub-themes or by setting individual properties.

-----
I'll close this proposal, as the gist of it is already described in a more all-encompassing proposal here https://github.com/godotengine/godot-proposals/issues/1438#issuecomment-683762551.

That said, I'm currently working on major improvements to the Theme Editor and will probably open a new proposal to replace them all soon.
