### ISSUE TITLE
Add a horizontal scrollbar to the Scene tree dock

### ISSUE THREAD

**Issue by Syraleaf** [godotengine/godot-proposals#1793]
**Describe the project you are working on:**
I'm currently working on a city builder game.

**Describe the problem or limitation you are having in your project:**
The other designer made a UI mock up but I am unable to select all the nodes. As shown in the image below, I simply cannot see most of the children. 
![image](https://user-images.githubusercontent.com/13417427/98453266-9aec9780-2157-11eb-9c80-e3f636a74fcb.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding a horizontal slider at the bottom would allow me to move the view in the window to the right so I can select the desired nodes.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![image](https://user-images.githubusercontent.com/13417427/98453304-fb7bd480-2157-11eb-8bdc-a8932d4d3573.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The way to work around this issue is making a lot of different scenes. This would require us to save all the components of the UI before we actually know if we want to keep them. 

**Is there a reason why this should be core and not an add-on in the asset library?:**
I'm not sure. it could be an add-on? Just feels a bit weird if we'd have to download one for this type of issue.

**Comment by pycbouh** [comment]
> This would require us to save all the components of the UI before we actually know if we want to keep them.

Is that such a huge cost for prototyping, though? Is that the only reason why you don't refactor your scene into multiple parts? Such huge scenes are pretty uncommon for Godot development. Don't get me wrong, it makes sense to have a scrollbar there, it's just a pretty unusual circumstance. Also, you can resize the dock horizontally.

**Comment by Syraleaf** [comment]
> Is that such a huge cost for prototyping, though? Is that the only reason why you don't refactor your scene into multiple parts? Such huge scenes are pretty uncommon for Godot development. Don't get me wrong, it makes sense to have a scrollbar there, it's just a pretty unusual circumstance. Also, you can resize the dock horizontally as a temporary solution here.

Yeah, I would consider this a minor inconvenience from my part (I mostly handle the code on the project) but I'd say that the more you work with UI the more this would occur. All in all I really consider this a small request. ^^

**Comment by Arecher** [comment]
> Also, you can resize the dock horizontally as a temporary solution here.

This issue is especially annoying if you're working on a small screen, due to the viewport & inspector docks having a minimum size, disallowing you to make the Scene View Dock bigger. This happens to me all the time :(

![unabletorescale](https://user-images.githubusercontent.com/10502115/98453444-595cec00-2159-11eb-87ab-1ccab640df6b.gif)

**Comment by Zylann** [comment]
This would help my Editor Debugger plugin, which has to display the editor's scene tree, and that tree can be extremely deep.

**Comment by bonbonmiel** [comment]
An idea: it would be great to allow panning (e.g. with hold middle mouse click). This is the 2d equivalent of scrolling and I personnally prefer it than modifier+mousewheel.

**Comment by lentsius-bark** [comment]
@bonbonmiel similarly to Blender right? One thing I had been mesmerized by with blender was how the same controls applied to all editors. Perhaps this type of control could then be implemented for all windows even.

**Comment by Jummit** [comment]
> An idea: it would be great to allow panning (e.g. with hold middle mouse click). This is the 2d equivalent of scrolling and I personnally prefer it than modifier+mousewheel.

That would be amazing, but would have to be implemented in all UI elements that have scrolling.

**Comment by EricEzaM** [comment]
This seems more like a bug tbh... Either way, definitely needed.

**Comment by reduz** [comment]
The way this was implemented in #50146 is not ideal, so for the time being I will revert the behavior with #50146.

We most likely need to add a better way to do this, where where the button icons remain fixated at the right.
