### ISSUE TITLE
Switch from SCons to Meson to improve Godot's build performance

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot-proposals#1797]
**Describe the project you are working on:**

Godot engine development / FBX Importer

**Describe the problem or limitation you are having in your project:**

Rebuild times are quite slow, also we have no option to swap to shared linking

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

We were going to try using meson as it claims to be much faster than scons for intermediate rebuild times.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

We'd port to meson tool which is written in python.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No,

**Is there a reason why this should be core and not an add-on in the asset library?:**

Yes it won't work in a module.

So @Calinou and I were thinking of throwing a prototype build together for the editor only.

We'd port the existing behaviour to meson and see how much editor build times are improved by, then ask the core devs to look at the prototype.

We chose meson because its close to scons but with better performance overall, and it's not going to be outright refused like CMAKE would be since CMAKE is poorly explained and poorly documented.

Noteworthy a lot of projects use MESON it's very maintained and used for Mesa.

I believe that reduz previously mentioned that he likes scons because it can create reproducible builds, and meson supports this by default.

https://mesonbuild.com/Reproducible-builds.html

Meson also gives us the ability to run the build on multiple machines using ninja without hooking back into meson each time for each call, meaning the build environment won't change and cause a rebuild.

A prototype would include:
- editor build Linux
- standard options debug_symbols=yes/no 
- ninja support out of the box @fire  (https://mesonbuild.com/Quick-guide.html) :heart: 
- clearly defined dependencies for modules
- the ability to disable more modules and enable them as required without breaking the engine since we can make a clear dependency tree
- the ability to swap live between shared libs and static-libs for modules like #1796
- code generated headers could be rebuilt once and made so that it won't rebuild every time, allowing even further caching advantages in the compilation process
- we can half our link times by not including debug symbols when you only need to test some code fast!
- **we can make our rebuild times faster than CMAKE, SCONS and pretty much everything else https://mesonbuild.com/Simple-comparison.html**
- We would get much better .sln generation for MSVC.

I think it would be better to swap, but swapping IS not for the faint of heart, but a worthwhile endeavour and I believe it would also improve the build times for higher core count computers since we can take advantage of ninja files.

We should maybe make a prototype just to decide to see if we want to use it going forward.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/16014.

**Comment by fire** [comment]
See my simplified cmake from 2019. There’s also slurps’s cmake.

**Comment by RevoluPowered** [comment]
I think that the resistance has changed with time and that CMAKE would never be accepted even if core devs wanted to change since they don't like the syntax and the language and people find it difficult to use, I know a lot of effort went into the cmake port though. @hpvb doesn't like CMAKE and I think Reduz is the same. I also don't really like it, never found it to be so good, I prefer premake4 over cmake, but I think Meson is more practical as it has more users overall.

I asked for some clarification on this earlier in IRC so we know what we can do, and how much of a prototype its worth us putting together as I think you're right since the work was done before it would be better to not waste much time.

**Interestingly the code generator functionality seems quite easy to implement too which I think would be the first bit to get out of the way:**

https://mesonbuild.com/Generating-sources.html

**We'd also get self contained dependencies for modules for thirdparty too: 😄** 
https://mesonbuild.com/Dependencies.html#declaring-your-own

**Comment by marstaik** [comment]
@RevoluPowered @Calinou Have any of you started on this? I was planning on trying to knock this out this Thanksgiving break since I have the week off.

**Comment by Calinou** [comment]
@marstaik Check this branch: https://github.com/Calinou/godot/tree/buildsystem-use-meson

You have to compile it with SCons before building it with Meson. When building it with Meson, it will fail due to template issues I don't know how to solve.

**Comment by marstaik** [comment]
As a heads up to those here, I have already started working on the prototype. I will link to a branch when it is stable-ish enough.

**Comment by marstaik** [comment]
Sorry, it took quite a while but the initial work I did this week can be found here: 

BRANCH: https://github.com/marstaik/godot/blob/meson/
README: https://github.com/marstaik/godot/blob/meson/MESON.md

There is still a lot of work to be done, but for the most part the components needed to move us forward are done.
* The basic skeleton of the build process is also done.
* A new module database system that simplifies the build system (required for meson) has been implemented.
* All third-parties are forced to be their own static lbs instead of being directly embedded into the Godot libraries.
* All the *generation* code should have been completed, except for any specifics in the `platform/` folders other than windows.

At this point its solid enough that it should be feasible for people to start helping without stepping over each other.

**Comment by RevoluPowered** [comment]
I'll do a single module as a test like PNG

**Comment by alexfreyre** [comment]
well I have just tested both and the result on Intel i5-6500T CPU @ 2.50GHz, 4C/4T

**meson** `14 mins`
**scons** `17 mins`

while it's a little faster it doesn't show an output as a detailed list as scons does,
but the `actual/total` shows clearly the amount of files remaining to be compiled

**Comment by hilfazer** [comment]
Another reason to go for Meson is cppfront support.
https://nibblestew.blogspot.com/2022/10/using-cppfront-with-meson.html

**Comment by RevoluPowered** [comment]
I'm doing some clean up of my older proposals, if there isn't any major complaints I am probably going to close this proposal as it has a PR and implementation.

The rebased PR is here to backlink it
https://github.com/godotengine/godot/pull/51153

The other related PRs and original work is below
https://github.com/godotengine/godot/pull/52311
https://github.com/godotengine/godot/pull/45093

I'll give it 48 hours, if anyone wants us to keep this open let me know.
