### ISSUE TITLE
Allow one line save and load

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot-proposals#180]
**Describe the project you are working on:**
Small game for a game jam

**Describe the problem or limitation you are having in your project:**
I wanted a save system, but all the solutions I found made me write a lot of code. Then there is checking if we are loading an empty file and other complex things. 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
This feature will basically save small game jam projects(and simple games) from using complex save systems.
(see 'how proposal will work' below)

I am in no way saying that this is a perfect save system. Nor am I saying that this should be the preferred way of saving data. All I am saying is, coding a simple save system is not hard, but it does need a lot of code. Something like will not at all hurt anyone.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Unity guy here, and I remembered 'playerprefs' of Unity. Basically, to save some integer :
PlayerPrefs.SetInt("variableName",value)
To load it:
someVariable=PlayerPrefs.GetInt("varaibleName") 

Similarly there is GetStr, GetFloat. The engine should automatically check for empty load files and give some silent errors in case no save file is found.

I am not proposing it because 'Unity have it and this feature look very cool!', I am proposing it because it will help literally every Godot user in creating simple save files 

**Describe implementation detail for your proposal (in code), if possible:**
So basically, 7 new functions shall be added(name changes?):
getInt, setInt, getFloat, setFloat, getStr, setStr, deleteSave
As mentioned above, the engine should also itself handle file not found errors

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It will basically lessen code and save time in small games.
But literally every game at some point need saving data, and having a simplified save system like will save users from one  small game-making head ache :)

**Is there a reason why this should be core and not an add-on in the asset library?:**
Again, every game needs to save data. Having a simplified system never hurts. and literally every user will benefit from it. Many users are making small, minimalistic games on Godot, but every time they have to save some data, they are required to write a lot more code. Please don't think that this feature will promote 'bad practices' in coding, it will just simplify the work for many.

**Comment by Calinou** [comment]
> All I am saying is, coding a simple save system is not hard, but it does need a lot of code. Something like will not at all hurt anyone.

I think this is third-party territory, even if it's mostly targeted at gamejam games.

**Comment by nikhilCad** [comment]
I understand all your points @Calinou but is there any more concrete reason that this can not be added.
I mean, a few syntax sugar functions cannot possibly bulk up the engine.

**Comment by Calinou** [comment]
> I mean, a few syntax sugar functions cannot possibly bulk up the engine.

While a few syntax sugar functions won't impact binary size too much, think of all the other consequences:

- We need to document them, making documentation pages longer for little benefit. Good documentation is as concise as possible.
- We need to spend more time testing, debugging and supporting those functions.
- We end up having two ways to achieve the same thing, which introduces "choice paralysis".

**Comment by nikhilCad** [comment]
Thank you for answering!
