### ISSUE TITLE
Node names should not having trailing whitespace

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot-proposals#1800]
**Describe the project you are working on:**
Not my project but in a project of someone who follows my tutorials.

**Describe the problem or limitation you are having in your project:**
I got an email about the issue that a find_node("objects") returned null. But there was this node.
After I looked into the project myself, I figured out that the actual name of the node was "object " with trailing whitespace. And that I found that was pure luck cause you don't see this in the editor.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a warning somewhere if the user uses trailing whitespace in node names or don't allow it at all.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A small warning icon could be displayed like in other nodes.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This proposal is just for reducing the chances of getting into strange situations.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It should be in the core cause I can imagine that a lot of beginners will run into this problem.

**Comment by Calinou** [comment]
This was already implemented and will be available in 3.2.4: https://github.com/godotengine/godot/pull/42014
