### ISSUE TITLE
Make a node that allows for anaglyph ( red- cyan ) SBS 3D effect . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1805]
**Describe the project you are working on:**
A Tomb Raider game, now also have Oculus Quest 2 VR head-set, and got some red-cyan 3D glasses . .

**Describe the problem or limitation you are having in your project:**
Well, I've been wanting for a cheap, reliable, hardware-independent way, of making the 3D effect, like on 3D tv's, and it turns out there are anaglyph glasses, passive polarized glasses, and active shutter 3D glasses . . The last two require a special screen, but anaglyph glasses work, right away, on any standard monitor . . I thought the 3D effect would be really bad, but after watching a 3D anaglyph movie, on youtube, it is as good, or better, than the cinema, but many or, some of the videos, are not so good . . I was wondering if Godot could maybe get a setting, to turn on anaglyph 3D rendering, looks like this image . .

![2020-11-11 1743](https://user-images.githubusercontent.com/61069740/98839076-658cc600-2445-11eb-8ce4-fb5d9f16236a.jpg)

The cost of such glasses are 10 - 12 dollars, for two pairs, and they work on ALL monitors, and TV's, connected with a cable, also . . One can also download SBS 3D movies, and play them in VLC player, and there's the movie 3D effect . . If you have the time, or so, try and get some red-cyan 3D glasses, and watch this movie, it's really amazing, really cool . .

https://www.youtube.com/watch?v=e00N024D7Lg

3D is a bit, of a gimmick, or so . . But, that movie, and a few other on youtube look REALLY good, even better than the 3D movies, except for the slight tinge effect, towards yellow, greenish, from the colored glass . . Since this works really well, and is a super-cheap way for people to experience 3D, I was hoping you could make a special AnaglyphCamera3D, it require two cameras nearly side-by-side, and over-laying the two perspectives, seen it done, in a shader, but since this is very, very cheap, as in 10 - 12 dollars, for TWO glasses, it seems a fitting way, for people to have a bit of silly fun, with 3D in Godot, and doesn't require a special monitor, projector, or polarized screen . . . If you try and get some of these glasses, they look like this, watch the youtube video, I think you'll agree, the effect is stunning, for such a low cost . .

![2020-11-05 0359](https://user-images.githubusercontent.com/61069740/98839615-09767180-2446-11eb-8eed-2b124e60dd4a.jpg)

Since Godot is totally free software, and looking at youtube videos, one needs to really tweak the settings, to get the right look, not sure if the distance between the two side-by-side cameras is individual, so maybe there should be a setting, for this . . Anyway, it's a really cool way to get a nice 3D effect, and I think you'll have your minds blown, if you watch the above video . . It's dirt-cheap, fun, and doesn't require special hard-ware, IF Godot was to get some sort of 3D effect, on any monitor, this would be a good place to start, so I hope we could get an AnaglyphCamera3D, that's basically two cameras, side-by-side, with the images rendered, so they look, like this . .

![2020-11-11 1750](https://user-images.githubusercontent.com/61069740/98839895-6f62f900-2446-11eb-9807-f70e83c76a28.jpg)

It's so cheap, I see no reason it can't be a camera, or, a node, in Godot, and it takes 20 minutes to code it, but one needs to know how to do shader stuff, so I can't do it, it's simply too difficult, but the video I saw, I think to get the optimal effect, one needs to add some different settings, like maybe eye-distance, or so . . Was thinking Godot could get this, or so, for fun . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
3D is sort of, cool and, nice, or such . . Would really like to have a new node, maybe in Godot 4, or so, that renders a 3D viewpoint, in anaglyph setting, but a really well - implemented version, so it looks like the above video, which is pretty amazing <3

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm not sure how to do this, but it'd be a nice thing, in Godot, since it's so cheap, glasses cost 10 dollars, or less, it works on any monitor, down to the cheapest, also tv sets and, then people can have some fun with 3D, or so . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think it could be cool, if it was really well implemented, since 3D is pretty amazing, but so far isn't supported, with a quick feature, or so . . It actually looks amazing, if you could get some of these glasses, and see the Bunny Buck video, it's actually the full 3D effect, of modern cinemas, but basically available to all, regardless of monitor, hard-ware platform, etc, and it could be fun to play a 3D game, made in Godot, where the only hardware required, is some 8 - 10 dollar glasses, from internet . . <3

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, bec. 3D is cool, and sort of fits the 3D game engine, very well <3 . .

**Comment by Calinou** [comment]
As far as I know, this can already be implemented with a shader.

Also, red-cyan (or other two-color) anaglyph modes tend to be on the way out. They don't provide an actually good experience and are considered a novelty in 2020.

**Comment by jasperbrooks79** [comment]
I googled it, and found some images immediately, that look STUNNING . .

![Uploading 2020-11-11 1757.png…]()

![2020-11-11 1758](https://user-images.githubusercontent.com/61069740/98840825-940ba080-2447-11eb-9346-4fdc279ba691.jpeg)

![2020-11-11 1759](https://user-images.githubusercontent.com/61069740/98840833-95d56400-2447-11eb-85ff-48581ffc3597.png)

If you look at these images, the 3D is DEAD stunning, amazing, it's like you can leap into the picture, there are no artifacts, it's SIMPLY mind-blowing . .

Given the price, and no need for a monitor, if it was implemented as well as these images, it'd be crazy - fun . . <3

**Comment by jasperbrooks79** [comment]
I think maybe the problem is, they didn't know how to optimize the effect, the stuff you see in these images, or by googling anaglyph 3D images, is near 100 % the best 3D experience, I've ever seen, and it's so cheap to get started, also . . 8 - 10 dollars, and you have a 3D tv, or game dev environment, it's just amazing, really . . <3

**Comment by jasperbrooks79** [comment]
These, look mind-blowing, like you can dive into it, or you're hovering over the images, in real life . . .

![2020-11-11 1802](https://user-images.githubusercontent.com/61069740/98841312-388de280-2448-11eb-9378-fd4cebbcef86.jpg)

![2020-11-11 1803](https://user-images.githubusercontent.com/61069740/98841321-3cba0000-2448-11eb-94ea-7e3d21b574fc.jpg)

Maybe one could add a setting, under Camera3D, to render anaglyph 3D, so it's quite easy . .

I can honestly say, the pictures are some of the best, cutting - edge 3D effect I've ever seen, to date, with simple anaglyph glasses, you'll be amazed, at the effect, and cost, is 8 - 10 dollars, often for two pair <3

**Comment by jasperbrooks79** [comment]
I also thought the 3D effect had to be last-gen, or really bad . . But, trust me, the images above literally POP, and feel ' real ', the effect is simply AMAZING, maybe people with different eye distance will need to find other images, I googled anaglyph images, and right away, there were some REALLY good ones, REALLY nice . .

Please, consider . . <3

**Comment by SIsilicon** [comment]
I have skimmed through your proposal, and see that the main reason to add it to Godot is "because it's cool".
Have you taken into consideration the following that this isn't commonly used nowadays? This is a little too specific to be added to the engine. Plus, adding to what @Calinou stated, an implementation of this can be made with a shader an a couple viewports, so it doesn't even _need_ to be a part of the engine. Don't forget.
_If it can be made an add-on, it should probably _stay_ an add-on_.

**Comment by jasperbrooks79** [comment]
Yes, but the person I saw that made an add-on, it gave a really bad result, but it was 3D, to get a really good shader, and the correct camera set-up, might require some real pro shader coders, like in some images, the 3D is semi-good, but in others, it's like REALLY, REALLY good . . So, it seems one doesn't just need to convert an image, but actually know some techniques, or so, ie. it will require some research, so on . . Also, since it's not for static images, but for converting an actual 3D world into 3D, with dynamic backgrounds, distances, so on, making the effect run well, might be more complex, than making a viewport shader, with maybe interlacing . .

My biggest thing is, when I got the glasses, I was like this is dated, ancient technology, and it will look awful, the WORST 3D effect you can get, but after seeing some 3D movies, with glasses in the cinema, I can tell you, against my expectations, the 3D effect, when it's done correctly, not all images ' just ' work, is BETTER, than what I have seen, in ANY movie, to date . . The above images are the best I've found, the effect is SIMPLY amazing, and I think it has to do with, one has to render the images really well, ie. the tech behind making the images have actually improved, so it 100 % rivals, or is better, than in 3D movies, with more expensive glasses . . The ONLY down-side is, it sort of affect the colors, so the colors are a bit limited, but for the black-and-white images, the 3D effect is so good, you'll literally think, this is as good, as it gets . .

Since these are very cheap, and work on any monitor, I think it'd be cool to have a AnaglyphCamera3D ( basically two cameras, that render a side-by-side images, in an interlaced way ), like you think these glasses make the 3D effect, from movies from the 1980's, or 1970's, but when you put them on, the 3D effect is as good or, better than what is in the movies . . I'm not sure why, but these glasses rock, and you'll be mind-blown, when you find some well-rendered images, the thing is, I don't know the difference between the good images, or the bad images, so some real cool 3D people, and shader experts would have to figure out, how to get an amazing result . . Even if it was only SUPER-good for black-and-white images, those are the BEST I've seen, bec. the colors stay the same, to the eyes, one can make amazing things, entertainment-wise with such glasses, and they're so cheap, and easy for people then buying or, downloading the games, that it's simply not, an issue, like you can get them 8 dollars, on amazon . .

This image, is literally how good the best rendered image looks, or 90 % close, I had no idea, got them for fun, I think the tech behind rendering 3D images, also for anaglyph has vastly improved, since the 1980's, or so . .

![2020-11-12 1424](https://user-images.githubusercontent.com/61069740/98945470-d938dc80-24f2-11eb-9866-25d1ad86f770.jpg)

Try getting a pair, if you have the time, order the cheapest from amazon, and you'll see something like the above, so I think it could be cool, and a fun thing to add, to the engine, so people can experience the 3D effect, at like zero investment, and even make stuff or, games in it . .

The 3D effect, is NEARLY this good, except it only goes into the screen, not out, or so . . You think it's a joke, but the rendering technique, for making the images must have gotten a lot better, or so . .

![2020-11-12 6](https://user-images.githubusercontent.com/61069740/98945724-2f0d8480-24f3-11eb-83b4-8826ce8d48d3.jpg)

That's why I think this could be cool, for Godot, bec. it's so cheap, it's ridiculous, and one can make stuff like the two above images, or 90 - 95 % of that, that's how much the making, of the images, has improved, even for anaglyph . . Thanks . . .

**Comment by jasperbrooks79** [comment]
if you've tried the new Oculus Quest 2, or a VR head-set with the ' 3D ' effect, imo. this is as good or, better, when the images we rendered the most pro way, so asking the engine makers to consider adding support for this, the best tech for rendering the images, so it really pops, or looks amazing . . . .

**Comment by SIsilicon** [comment]
I'd like to see the shader code that was used to make the effect.
I'm thinking that a good implementation of this would require two viewports to render the scene from two slightly different perspectives. Then in a screenspace shader, overlay them on top of each other with red and greenish color modulation.
Could you give a link to the shader itself?

I'd also would like to know how making it built into the engine makes it any better than using a viewport shader setup.

**Comment by jasperbrooks79** [comment]
Here's the video, it's a bit strange, or so . . But, stuff works . .
https://www.youtube.com/watch?v=WfhdeLrq6_k

The reason I think the viewport shader set-up is not as good, is that SOME anaglyph images look really good, others look really, really bad . . I think there are different ways to make this effect, and that it makes a big difference, what camera set-up you use, maybe each user needs to have a custom distance, between the cameras ( eyes ) to make it look really nice, so one would need a slider, in the shader, where one can set the distance, between the two cameras, for individuals . . That's why I think the cool dev people here, that really understand 3D, would be needed to make a shader, that makes the best results, which is where the effect gets so good, it's use-ful <3 . . Thx . . .

**Comment by jasperbrooks79** [comment]
The reason I think it should be built-in, maybe just as a toggle, under the Camera3D, or in ' Visual ' project settings, or have an AnaglyphCamera3D, is bec. when it's done well, the results are stunning, but sometimes even if an image it ' technically ' anaglyph, with glasses on, it looks REALLY bad, ie. the 3D effect is completely weird, and it looks buggy, so on . . That's why I think it's not just enough to make an ' anaglyph ' viewport shader, people actually need to work with it, pro people, to make sure the effect is on a good enough level, ie. it will look good, for all users, in some of the images I've found on google, it looks completely like, well, a big mess . . And, I think that has to do with the fact, it's not just ' enough ' to make an anaglyph image, booom it works, one needs to know how the effect works, to really optimize it, so it looks amazing . . ie., it's not as simple, as making a view-port shader, to get the BEST result, some pro people are required, to make the stuff work, at the highest level <3

**Comment by jasperbrooks79** [comment]
The effect is only really good, when the images are rendered the ' best ' way, I also think, it might be necessary to render 3D object, onto flat planes, and then move the planes, in like billboard mode, to get the best effect, but, that could easily be done, later . . The point is, 3D is sort of, a nice thing, I love 3D movies, and this actually works, these dirt-cheap glasses, that don't require a special monitor, in terms of 3D effect, is JUST as good, as what is in the cinema, if you get some, you will be amazed at how well it works, or so . . You'd think the effect looks as good, as in the 1970's, or 1980's, where the red-cyan glasses first were released, but I tell you, this stuff can make as good, or better 3D effect, than any current movie, you can see, in the cinema . . Maybe, bec. the way they render the IMAGES, has been improved, so one can better use ALL 3D glasses, also, the red-blue ones <3

**Comment by SIsilicon** [comment]
Yeah, I watched that video before. I don't think he implemented it well either.
You're saying that _sometimes_ the effect doesn't look good. You mean based on scenario or implementation?

Either way, I think the user who did that was ether doing it poorly, or it just looked bad _to you_. I don't have anaglyph glasses myself so I can't tell.

**Comment by SIsilicon** [comment]
There is a better way to do it in vanilla Godot. You can use the following shader.

```
shader_type canvas_item;

uniform sampler2D left_camera;
uniform sampler2D right_camera;

void fragment() {
    vec4 left = texture(left_texture, UV) * vec4(1, 0, 0, 1);
    vec4 right = texture(right_texture, UV) * vec4(0, 1, 1, 1);

    COLOR.rgb = left.rgb + right.rgb;
}
```
Try doing the same setup that that guy did, but instead of using two texture rectangles, use one with the the shader above and with the two viewport textures in they're respective sampler uniforms.

**Comment by jasperbrooks79** [comment]
Well, I'm super - noob, in shaders, and I don't know how to any of that, never coded a shader before, a written one, ever . .

I think one reason it might look bad is, to get the best depth version, one needs to have the cameras be the same distance, as ones eyes, also works for VR head-set, set the distance between the eyes, or it doesn't look good . .

The reason it COULD be in Godot, is bec. it's such a simple shader one has to write, and it's instant - fun, same way there's an ARVRCamera3D, there could be an anaglyphcamera3D, and it could have the settings needed, to get a really good effect . . Some of the google images, and anaglyph videos look REALLY bad, but some of them, look REALLY good, and I think it might be because the images render with, different eye-distance in mind or, so . .

I can say one thing, the 3D effect AS good, as anything in the movies right now, but it does have an effect on the color, so things look more greenish-orange, or yellow . . 

Again, if you get a cheap pair from the internet, cost is like 10 dollars, or lower, you could see that it actually is a very cool technology, and the effect isn't ' behind ' current cinema or, tv stuff, in fact, it looks better than any 3D movie in cinema or, on tv I've ever seen, but then certain images, look REALLY bad, so I think it's a matter, of having the right settings, before rendering, and I wanted to ask some REALLY cool 3D coders to help doing this, and then make it a fun add-on, in Godot . . It could either be a new AnaglyphCamera3D node, or it could be a setting, under the normal Camera3D, to render like, also looking at the complexity of the shader code, I don't think it would add very much to size, of Godot :O :O . .

**Comment by jasperbrooks79** [comment]
Also, I don't know how to put the written shader code into Godot, do I need to have two cameras, one called left_camera, one called right_camera, I am asking for this feature, bec. I don't know how to code it myself, at all, and the 3D effect is VERY solid, even if the colors look a bit weird, black-white images, look amazing, no color distortion, so one could make a film noir grey-scale themed game, or so . .

Also, for some reason I think 3D vision, or so, fits really well with a fun, silly, amazing game engine, like it's really amazing . . <3

**Comment by jasperbrooks79** [comment]
Last, since I suspected one could do it better, I wanted ask here, since there are some super-cool coders, with a TON, of rendering, 3D knowledge, that might know, how to make this, an amazing shader, or add it to Godot . . I'd really like to play a bit, with 3D depth stuff, in Godot, and the price is staggeringly low, most cost 8 - 10 dollars, for either 1, or 2 glasses, on the internet . . And, it runs on ANY monitor, also, not special 3D hard-ware . .

**Comment by AlphinAlbukhari** [comment]
Since you use visual shader, I converted @SIsilicon's code to visual shader
![image](https://user-images.githubusercontent.com/54466934/99179695-9d03b700-2752-11eb-8c07-e5ea2d06b76d.png)

But that seems you need 2 cameras, so here's the single camera version
![image](https://user-images.githubusercontent.com/54466934/99179746-11d6f100-2753-11eb-8dba-9280e2a1d3c2.png)
You can change the offset by adjusting the values on VectorOp nodes
And note that to use ViewportTexture, you have to mark "Local to scene" first.

**Comment by jasperbrooks79** [comment]
ok, I will try it, seen your stuff on the Facebook, Alphin, you're a shader god, every-thing is, mint stuff <3 . .

Thx . . .

**Comment by jasperbrooks79** [comment]
Not sure, does the above shader add a 'red' tint to one side, and 'cyan' ( light blue-green color . . ), to the other side . .

I have to admit, this stuff feels so difficult, it's for an engine expert . . <3 :O . .

**Comment by jasperbrooks79** [comment]
That's why I wanted to ask here, bec. the effect can really suck, but when it's done right, by tech-experts, it's a solid 3D experience, no bull . . <3

**Comment by AlphinAlbukhari** [comment]
I've updated the shader, now you dont need 2 different textureuniforms anymore
![image](https://user-images.githubusercontent.com/54466934/99179972-d6d5bd00-2754-11eb-8295-dd226577b176.png)

**Comment by AlphinAlbukhari** [comment]
@jasperbrooks79 well actually to understand better with it, VisualShader should output preview from TextureUniforms, so you can see what's happening on every step

**Comment by jasperbrooks79** [comment]
Also, I think by using interlaced images, one would get a worse 3D effect, than by using some sort of, mix or, blend shader, of the the two cameras . . I'm also not sure, if one needs to rotate them, to a focus point, so if one looks 10 m from camera, to an object, they need to sort of, rotate, or for close, to eyes, lol . .

![2020-11-15 0912](https://user-images.githubusercontent.com/61069740/99180000-c3a9f980-2722-11eb-8d3b-0314a971f6e8.jpg)

This is stuff, that I would not know if was important, but 3D experts, would better know it <3

Sigh, I don't know how to set that up, can someone make a ' sample ' project, for me, I'm super noob, this stuff is super - complex, for me . . .

**Comment by jasperbrooks79** [comment]
I was sort of hoping, we could get a ' pro ' anaglyhcamera3D node, OR maybe a setting, under an Camera3D, to make a ' anaglyph ' 3d picture <3

**Comment by jasperbrooks79** [comment]
Here's how good it looks, 98 % this image, with SOME of the images or, youtube videos . .
![2020-11-15 0921](https://user-images.githubusercontent.com/61069740/99180133-ef79af00-2723-11eb-89ea-d658348e39db.jpg)

Sry, for the many posts, hope maybe someone could make an add-on, where one press play, the thing is done, with anaglyph mode, or something one can use, even when editing, the levels, or so . . <3

**Comment by AlphinAlbukhari** [comment]
First, let's start with TextureUniform
Actually, there's a Texture node where you can use it to use any texture, but you can't use ViewportTexture with it because it should be local to scene, I guess it's because nodes are resources and you can't change directly to local or not. So I use TextureUniform instead, the difference is TextureUniform export variable that can be changed from the inspector or param, and since it's 'exported' the texture you're going to use can be local. But at cost you can't see preview from it directly, I think this is normal but I hope they will implement it.

And to offset things, I use UV, UV is something that controls your texture or pixel coordinate or whatever I can't explain. Then I add the UV a bit to move the position to right, and the second one is substracted to move it to left, and I created 2 texture nodes with different UV, resulting the same image but has different coordination, and Multiply node to color things, for example, I multiplied with 1,0,0, meaning that we will only get red and no greenness and blueness, and finally to combine them together I use "add" node which add every pixel with second image's pixel

**Comment by jasperbrooks79** [comment]
Take my word for it, if you get some anaglyph glasses, the cheap ones, and look for google anaglyph images, you'll be be mind-blown, not sure why, maybe when they were used in 1980's, they didn't have virtual 3D worlds, to use to make the effect, they were limited to bad cameras, early tech . . <3

**Comment by jasperbrooks79** [comment]
> First, let's start with TextureUniform
> Actually, there's a Texture node where you can use it to use any texture, but you can't use ViewportTexture with it because it should be local to scene, I guess it's because nodes are resources and you can't change directly to local or not. So I use TextureUniform instead, the difference is TextureUniform export variable that can be changed from the inspector or param, and since it's 'exported' the texture you're going to use can be local. But at cost you can't see preview from it directly, I think this is normal but I hope they will implement it.
> 
> And to offset things, I use UV, UV is something that controls your texture or pixel coordinate or whatever I can't explain. Then I add the UV a bit to move the position to right, and the second one is substracted to move it to left, and I created 2 texture nodes with different UV, resulting the same image but has different coordination, and Multiply node to color things, for example, I multiplied with 1,0,0, meaning that we will only get red and no greenness and blueness, and finally to combine them together I use "add" node which add every pixel with second image's pixel

THANK YOU, I'm COMPLETE noob <3 Hope, we can get a high-tech, high-level Anaglyph stuff, in Godot <3

**Comment by AlphinAlbukhari** [comment]
> 
> 
> I was sort of hoping, we could get a ' pro ' anaglyhcamera3D node, OR maybe a setting, under an Camera3D, to make a ' anaglyph ' 3d picture <3 

No because I don't think everyone will need it

**Comment by jasperbrooks79** [comment]
Ok, did this, I get an error, on boxes . . :O . .
<img width="923" alt="Skærmbillede (712)" src="https://user-images.githubusercontent.com/61069740/99180386-1b962f80-2726-11eb-85e7-8c0a101d7186.png">

**Comment by jasperbrooks79** [comment]
When I try to copy the shader, it says ' Invalid source for shader ' in the Texture2D box . . <3

**Comment by jasperbrooks79** [comment]
Maybe it'd be easier, if there was an add-on, from Assetlib <3

**Comment by jasperbrooks79** [comment]
Or, quick youtube tutorial, or so . . :( <3 . .

**Comment by SIsilicon** [comment]
> Maybe it'd be easier, if there was an add-on, from Assetlib <3

That's what I was suggesting in the first place.

**Comment by jasperbrooks79** [comment]
Well, I'm not pro enough, to know how one would even do that </3 . .

I really hope some-one might do it, since the effect is simply awe-some, mind-blowing . . Sigh, I'm noob, so I ask for more qualified help, Thank you . . </3 . .

Thx . .

**Comment by jasperbrooks79** [comment]
Also, I wanted to ask here, bec. sometimes the effect is really bad, like it becomes a real mess, but when tech-experts get it right, it's mind-blowing, AMAZING . . <3

**Comment by jasperbrooks79** [comment]
Well, I'm so noob, tbh . . I can't make the stuff you do work, if someone wanted to make an add-on, or so . . Or, a shader one could download, sigh, I have no idea, what to do . . . </3 . .

**Comment by SIsilicon** [comment]
Well, since we know that this can be done as an add-on with little benefit being core, this proposal could _probably_ be closed.
But hey. You could ask around somewhere else like reddit, Godot Q&A, etc...

**Comment by jasperbrooks79** [comment]
Yea, I know, when I got the glasses, the effect was so good, and since it VERY cheap, almost NO money, like 10 dollars, that's all you, I wanted to ask here, also to ask some expert, in the 3D stuff, I'm not sure if I should ask for add-on, or shader download, or WHAT, very new to games, so far I struggle, to learn code, though, I try . . </3 . .

**Comment by SIsilicon** [comment]
You keep trying! Keep learning. You'll get the hang of it eventually. :

**Comment by jasperbrooks79** [comment]
Ok, it's really complex, this 3D depth render effect, for me . .

I wish, I understood code and, game dev and many other things, a lot better . . . Thx . .

**Comment by SIsilicon** [comment]
Good news! I just made an anaglyph camera addon.
![image](https://user-images.githubusercontent.com/34734122/99289288-c08a3880-280a-11eb-9601-c2282a1364e5.png)
[Anaglyph Camera.zip](https://github.com/godotengine/godot-proposals/files/5548800/Anaglyph.Camera.zip)

It gives a new node with two properties.
- `separation`: How far apart the "eyes" are. A larger value gives a stronger effect.
- `convergence`: The distance at which objects appear normal.

**Comment by jasperbrooks79** [comment]
THANK YOU SO MUCH, I WILL DOWNLOAD IT IMMEDIATELY, THIS IS SO COOL THANK YOU ! ! <3

AMAZING . . <3 <3 🤤 <3 

THANK YOU

IS ON ASSETLIB, OR I DOWNLOAD IN THE LINK ? <3 THX . .

**Comment by jasperbrooks79** [comment]
OMG, the 3D effect is REALLY good, it LOOKS like fluid, vibrant, glorious 3D, this is so amazing, thank you, Omg try and get some glasses, this is COOL . . :O :O . .

THANK YOU, made my day, SO AMAZING <3

**Comment by jasperbrooks79** [comment]
And, it's not even a bad 3D effect, it looks as good, as in the cinema, it's like, WOWOWOW <3 . .

I know it's not place to ask people to get cheap 3D glasses, anyway they cost 10 dollars, for 2 pairs, the 3D effect is REALLY good, one can see the ' orbs ' HOVERING, in SPACE, behind the pillars, this isn't a beta implementation, this REALLY rocks <3 . .

THANK YOU ! ! ! <3 <3 :D :D . .

**Comment by jasperbrooks79** [comment]
OMG, it LOOKS ALMOST, ALMOST LIKE THIS . .
![2020-11-15 0855](https://user-images.githubusercontent.com/61069740/99337206-21088c80-2882-11eb-95f9-d422867a5590.jpg)

There is a problem, the frame-rate is REALLY low, normally my laptop makes Godot run 144 FPS, atm it's like 10 FPS . . But, the 3D effect is REALLY, REALLY good, AMAZING already <3

![2020-11-17 0310](https://user-images.githubusercontent.com/61069740/99337358-67f68200-2882-11eb-82e7-85c1b543b426.jpg)

I can almost make a MOVIE, in Godot right now, so cool . . The add-on works REALLY well right now, except the frame-rate is for some reason, SUPER - low . . the 3D effect is NEARLY as good, as best I've ever seen <3

**Comment by jasperbrooks79** [comment]
First, this is an AMAZING thing, it has like a 90 - 100 % pro cinema look . .

But, the frame-rate is some-what low, like 5 - 10 FPS, on my laptop, that normally runs Godot, at 144 FPS, or higher, for a simple level . .

The 3D effect is SOLID, but the frame-rate is LOW, is there any way to make it faster . .

Seriously, you need to see this, it's AMAZING . . <3

**Comment by jasperbrooks79** [comment]
rouyell, you ABSOLUTELY nailed it, it looks AMAZING, I added a 3D model, of a dragon, and it's SPECTACULAR . .

the only problem is, the frame-rate is like, 5 - 10 fps, so it has a ' jagged ' look, the animations . .

but, the 3D effect, is 90 %, or 100 %, of what a 3D movie looks like, in the CINEMA . . <3 Thx . .

**Comment by jasperbrooks79** [comment]
Omg omg omg, now we can make 3D MOVIES, in Godot <3 AMAZING, GLORIOUS, WORLD-CLASS <3

**Comment by jasperbrooks79** [comment]
the add-on is AMAZING, REALLY nice, only thing is, it lowers frame-rate a TON, right now, not sure why . .

**Comment by jasperbrooks79** [comment]
I just checked on amazon, you can get 5 pair, for 5 pounds, or 8 dollars . .

If the frame-rate can be improved, maybe 30 fps, or even 60 fps, this will be super-cool, I also think the effect looks best, when it's black-and-white, then there isn't the weird color effect . .

![2020-11-17 0337](https://user-images.githubusercontent.com/61069740/99339302-35e71f00-2886-11eb-95e3-d53f1118b68e.jpg)

![2020-11-17 0338](https://user-images.githubusercontent.com/61069740/99339408-6dee6200-2886-11eb-871e-59f1f8ff4d2a.png)

I know it's a lot to ask, but could you consider maybe spending 5 pounds, on some glasses, and test it, make it REALLY nice . . I give to Patreon, I wouldn't mind giving 10 dollars more each month, or 20 <3 it looks REALLY good, right now, with 60 FPS frame-rate, it'd be the best <3

**Comment by jasperbrooks79** [comment]
Right now, add-on is 9.8 / 10 review . .

**Comment by jasperbrooks79** [comment]
for instance, here are 5 glasses, 5 pounds, that's like price, of a sandwich . . <3

https://www.amazon.co.uk/Basage-Anaglyph-Dimensional-VISION-Glasses-Blue/dp/B08722NR3M/ref=sr_1_3?dchild=1&keywords=anaglyph+glasses&qid=1605581156&sr=8-3

![2020-11-17 0347](https://user-images.githubusercontent.com/61069740/99340099-a2165280-2887-11eb-9ba9-72ec6acac060.jpg)

also, atm 3D movies are only 1080p, but Godot is running effect, in 4K, on my computer . . if it could get to 60 FPS, it'd be best 3D effect, in the world <3

**Comment by jasperbrooks79** [comment]
tried changing the demo-level, in add-on, to black - white objects, and it looks AMAZING, world-class <3

**Comment by SIsilicon** [comment]
Dude.
Chill.

**Comment by SIsilicon** [comment]
Also, the reason why the framerate's low might have something to do with the fact that the scene is being rendered _twice_. One for each camera. This yields a pretty "ground-truth" Anaglyph 3D effect. VR doesn't come cheap, and neither does 3D. The framerate can be improved by lowering the main viewport's resolution.

**Comment by jasperbrooks79** [comment]
Ok, sorry, you'd be amazed, at how well the plug-in works . . it's really like in the cinema, a really cool effect . .

Thx . .

**Comment by jasperbrooks79** [comment]
well, thank you, without any settings, it looks like a Disney Pixar 3D movie effect, or cinema mode <3

if you ever get the chance, it's really spectacular, already, with like just this one, maybe it can be made cheaper . . I guess it's the taking two 4K images, then ' blend ' them into a new image, during each frame, that slows the plug-in down . . <3

**Comment by aaronfranke** [comment]
@SIsilicon Can you publish this on the [Godot Asset Library](https://godotengine.org/asset-library/asset) so that it's easily available for users? Then we can close this proposal.

**Comment by jasperbrooks79** [comment]
@SIsilicon @SIsilicon wait, I wanted to ask, since ' blending ' two images is more performance heavy, if maybe the shader could be interlaced, and since we now have wide-screen, compared to old tv's, from way back when, maybe vertical, instead of horizontal interlacing, of the two camera images, might give much better performance . .

Also, the plug-in, as it is, is 80 - 90 % as good, just put some 3D objects in, or animate them, they fly over or, under your head, seriously, this is a cool plug - in . .

but, a problem with the glasses are, they sort of mute some colors, yellow, blue and, red are fairly normal, but green especially sort of, looks ' faded ' . . I wanted to ask, for a way to boost certain PARTS, of the color spectrum . . Right now, in environment settings, one can set the ' Color range ', but it doesn't, afaik allow to boost only some colors, but leave others . .

And, I can guarantee, trying out this effect will blow your mind, I've gotten some 3D movies, and it's almost like the movies, except the green colors, are not so good . . but, for black and white, it's like no problem . .

I was hoping it could be optimized, as I'm thinking of using the effect, for cut-scenes, in my games, bec. I can lower amount of objects, there . .

Cost for glasses = 10 dollars, for 2 pair, on amazon . . And, if you've seen a 3D movie in the cinema, the 3D effect is the SAME, but the colors, especially green, sort of, becomes ' feint ' or, mute . .

Thanks again, for an amazing plug-in, right now it's so slow, I can't really use it, was hoping interlacing the two images, might be better :O <3 . . Thanks . . .

**Comment by jasperbrooks79** [comment]
Atm, the 3D effect in the plug-in is a bit better, than this, is it explains it . .
![2021-01-12 0248](https://user-images.githubusercontent.com/61069740/104259003-d7eb4800-5480-11eb-839e-dd3c24bf2b68.jpg)

But, frame rate drops, to 12 - 15 FPS, in 1080p, even . .

If the speed was there, I'd make a game in it, start with a black - and - white story, since the glasses don't affect that, when looking, or so . .

**Comment by SIsilicon** [comment]
> @SIsilicon Can you publish this on the [Godot Asset Library](https://godotengine.org/asset-library/asset) so that it's easily available for users? Then we can close this proposal.
> 
> If you are committed to maintaining this, I would be willing to buy you some glasses, they're fairly cheap, and having this feature available would be nice for the users who want it.

I'm kinda busy with the current wild Jam, so I'll look back at this project when that's over. As for buying me glasses, that would be nice, but I live in Jamaica, and I don't want to bother with the hassle of shipping.

**Comment by SIsilicon** [comment]
Ok now. It's pending review in the asset library.
https://godotengine.org/asset-library/asset/edit/2941

**Comment by jasperbrooks79** [comment]
@SIsilicon Thanks, for this amazing plug-in . .

For me, it runs really slow, even in forced 1080p, it runs at maybe 10 - 15 FPS . . Hope it can be optimized, maybe with interlacing, instead of blending the two images . . Anyway, the 3D is rock - solid and, amazing . . it just needs to run faster, even with like 30.000 poly in a scene, it lags like crazy ( two 10.000 characters, and some buildings ) . . .

**Comment by SIsilicon** [comment]
Have you tried the new `half_res` property of the node? It reduces the vertical resolution of the two viewports by half. It trades image quality for performance. There really isn't any other way of doing this. Interlacing the videos didn't help.

**Comment by jasperbrooks79** [comment]
Thank you, for developing this, I download new version <3

**Comment by jasperbrooks79** [comment]
Okay, I've tried it, first of all the grey-scale function, so good . . It looks rock-solid 3D, no color distortion, the plug - in can be used for commercial 3D games, at this point . .

The half-resolution is difficult to say, bec. I haven't got other settings just right . .

As it stands, it's an amazing plug - in, simply put . .

Thank you, this is all I wanted, amazing work . . .
