### ISSUE TITLE
Make HTTPClient::request accept absolute URL and authority

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-proposals#1808]
**Describe the project you are working on:**
Trying to make HTTP requests via a proxy server.

**Describe the problem or limitation you are having in your project:**
Not possible to communicate with HTTP/HTTPS proxy server with `HTTPClient`.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Currently, the second parameter of `HTTPClient::request` only accepts absolute path. For example, only `/index.php` is allowed, and passing absolute URL (`http://somehost.com/index.php`) or authority (`somehost.com:80`) is an invalid parameter error.

```gdscript
Error request ( Method method, String url, PoolStringArray headers, String body="" )
```

However, using absolute URL and authority in the HTTP request line is [allowed](https://tools.ietf.org/html/rfc2616#section-5.1.2) by the HTTP protocol, and is required when talking to a proxy server:

* For a HTTP proxy, connect to the proxy server, and change absolute path to absolute URL in the request line.
* For a HTTPS proxy, connect to the proxy server, issue a `CONNECT target-authority` request first, and then we can talk to the proxy server as if it's the target server.

Also, technically the `CONNECT` method [requires](https://tools.ietf.org/html/rfc7231#section-4.3.6) its request uri to be authority, even in non-proxy use cases. So it makes no sense to use absolute path with `CONNECT`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Remove the requirement of `url` parameter beginning with `"/"`.

I made a custom build that removed the parameter check, and then I am able to setup HTTP/HTTPS proxy connections manually in GDScript.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, the parameter check is in C++. There's no way to skip the check.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Removing the parameter check is much easier than implementing a new HTTP client library.

**Comment by Calinou** [comment]
Shouldn't we implement support for the `HTTP_PROXY` and `HTTPS_PROXY` environment variable instead? Or is this for a different proxy use case?

**Comment by timothyqiu** [comment]
This is an essential first step toward resolving that issue.

1. Being able to setup proxy manually in GDScript. (here)
2. Implement easy proxy setup for `HTTPClient` in core.
3. Implement support for `HTTP_PROXY` / `HTTPS_PROXY` environment variables.

I was indeed trying to resolve the mentioned issue at first, and soon find out that `HTTPClient` will not be able to talk to HTTP/HTTPS proxy servers unless `request` accepts absolute URL and authority.
