### ISSUE TITLE
Allow the mouse to be both confined and hidden by changing the MouseMode enum to be bitwise

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1810]
**Describe the project you are working on:**

A game where a confined and hidden mouse is desired.

**Describe the problem or limitation you are having in your project:**

Currently, the mouse cursor can be one of four states via the [MouseMode enum](https://docs.godotengine.org/en/stable/classes/class_input.html#enumerations):

* Visible (free to move around anywhere)

* Hidden (free to move around anywhere)

* Captured (also makes it hidden)

* Confined (and visible)

There is currently no option to make it *both confined and hidden at the same time*.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The proposal is to change this enum to be bitwise, so that being hidden can simply be toggled on or off by choosing if the number is odd or not. This will allow us to get Confined with Hidden by simply using the bitwise OR `|` on the two values.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Branch: https://github.com/aaronfranke/godot/tree/mouse-mode-bitwise

PR: https://github.com/godotengine/godot/pull/43450 

Because Hidden/Captured are both hidden, and Visible/Confined are both visible, and Visible/Hidden are both free, and Captured/Confined are both restricted, the current logic is a bit overcomplicated since it usually has to check multiple cases rather than if specific bit(s) are enabled. This change will simplify the code in some areas. For example, `if (mouse_mode != MOUSE_MODE_VISIBLE && mouse_mode != MOUSE_MODE_CONFINED)` can be replaced with `if (mouse_mode & MOUSE_MODE_HIDDEN)`.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

You could try using confined with a transparent cursor, but [this isn't working right now](https://github.com/godotengine/godot/issues/21745). You can try to work around it by setting the mouse cursor texture to a 1 pixel image or something, but this is still visible so it's not ideal.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Handling the mouse cursor is a core feature. Hiding is already a core feature, and confining is already a core feature, so it would make sense to allow doing both of these things at the same time.

**Comment by Chaosus** [comment]
I think if this will implemented the https://github.com/godotengine/godot-proposals/issues/557 should be closed...
