### ISSUE TITLE
Allow creating projects in non-empty folders with a confirmation popup

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1811]
Follow-up to https://github.com/godotengine/godot/issues/15835, the linked PR replaces https://github.com/godotengine/godot/issues/39220.

**Describe the project you are working on:** New ones.

**Describe the problem or limitation you are having in your project:**

Creating projects in non-empty folders can be a dangerous operation, but is sometimes desired, especially by @SubSage. The specific use case here is that if you create an empty repository on GitHub, then clone to your computer, the cloned repo contains a `.git` folder, so you can't create a project there, and have to perform the workaround at the bottom of this proposal.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The enhancement is to allow creating projects in non-empty folders with a warning and a confirmation popup, rather than prevent users from doing this completely.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Branch: https://github.com/aaronfranke/godot/tree/project-in-non-empty

PR: https://github.com/godotengine/godot/pull/42526

The PR changes the message from an error to a warning, and adds a confirmation dialog that looks like the below (I moved the windows so that you can see everything at once, but normally they appear on top of each other).

![Screenshot from 2020-11-12 21-28-38](https://user-images.githubusercontent.com/1646875/99021230-369e4f00-252e-11eb-88a1-14c83cb96b93.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It can be worked around by creating the project elsewhere, then closing Godot, then copying the files to the desired location, then opening Godot and browsing to the new location.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is about the project manager, so it can't be an add-on in the asset library.

**Comment by Zireael07** [comment]
Just dropping by to say that Sage isn't the only one who would like this 😉
