### ISSUE TITLE
Rename Label to TextLabel

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1815]
**Describe the project you are working on:** This applies to pretty much any project with UI.

**Describe the problem or limitation you are having in your project:**

It's not necessarily a problem or limitation, but it is something that IMO could be improved. Currently if you want to put a piece of text on the screen, you would typically use a `Label` node. This name is accurate and fine, but it's not super discoverable if you are new to UI systems and don't know what it's called, or are coming from Unity. It's also a bit inconsistent with `RichTextLabel`.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The name `TextLabel` would:

* Be more consistent with `RichTextLabel` since it's still text but without the rich.

* Have improved search results when searching for "Text", which is:

  * More familiar for Unity users, in Unity it's called `TextMesh`, so this way both names contain "Text".

  * Helpful for people who haven't used Godot before or haven't used any UI system where it's called "Label".

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Renaming `Label` to `TextLabel` would solve this problem.

Branch: https://github.com/aaronfranke/godot/tree/text-label-rename

PR: https://github.com/godotengine/godot/pull/40124 (gets conflicts often, very important to rebase right before merging)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This enhancement will be used often. The workaround is to learn the name "Label".

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is about the name of a core node type, so it can't be an add-on.

**Comment by jonbonazza** [comment]
Label is the standard terminology in most other ui toolkits, so i'd be hesitent to change it. Also, RichTextLabel is not reslly inconsistent. It's called so not because it's a Rich TextLabel but because it's a RichText Label (note the locations of the space). RichText is in reference to rich text formatting here.

**Comment by me2beats** [comment]
I would not mind the opposite - replace `RichTextLabel` with `RichLabel`. 
"Text" is somewhat redundant there imo.

**Comment by me2beats** [comment]
As for the search results, there could simply be a feature like "search by description / by node tags", where the word "text" could be present.
This would make it easier for new users to search without having to rename established terms.

**Comment by golddotasksquestions** [comment]
I remember this also confused me a lot when I started out with Godot. I just wanted to write a word in Godot and was looking for a simple "Text" node. I would have never guessed I would have to look for "Label". For me a label is a sticker I stick on a box or bottle. You don't have to have text on a label, it could also be a symbol, a drawing or whathaveyou. In every other editor I ever used writing is accomplished with a "Text box" or "Text tool" or simply "Text". The symbol is in every case I can think of a "T".

**Comment by aaronfranke** [comment]
@golddotasksquestions Indeed, icons like this are very common:

![text-box-icon-17](https://user-images.githubusercontent.com/1646875/99191397-75a0f000-273a-11eb-897e-b0727bb9637f.png)

**Comment by akien-mga** [comment]
After discussion with some core devs we decided to reject the proposal, see https://github.com/godotengine/godot/pull/40124#issuecomment-751741421 for rationale.

> As for the search results, there could simply be a feature like "search by description / by node tags", where the word "text" could be present.
This would make it easier for new users to search without having to rename established terms.

That's definitely the way to go if we want to increase discoverability of API elements without having to compromise on their naming.
