### ISSUE TITLE
Flip 2D icon to match Godot's 2D handedness

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1818]
**Describe the project you are working on:** 2D projects.

**Describe the problem or limitation you are having in your project:**

![old](https://user-images.githubusercontent.com/1646875/76601616-aa8be180-64df-11ea-86d7-b30c0ed04e74.png)

In the 2D icon, the Y axis arrow points upwards. This is fine-ish, but Godot's 2D coordinate system has Y pointing down. The icon as it currently is can be a bit misleading if people don't know that Y is down in 2D, so users could be confused and think that Y is up like they teach in schools. I think it's important to convey to the user that Y is down in 2D.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The proposal is to flip the icon so that the Y axis arrow points down:

![new](https://user-images.githubusercontent.com/1646875/76601619-ac55a500-64df-11ea-8c0e-64420bf73ad2.png)

This may look a bit weird, but it makes more sense in context:

![3](https://user-images.githubusercontent.com/1646875/76601827-1e2dee80-64e0-11ea-97b4-ffd77061f154.png)

There are already other icons shaped in this way, such as all the curve icons and GraphEdit:

![Screenshot from 2020-11-12 01-03-53](https://user-images.githubusercontent.com/1646875/98902148-21201b00-2483-11eb-80b5-29da7aef2f87.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This SVG image: https://raw.githubusercontent.com/aaronfranke/godot/2d-flip/editor/icons/2D.svg

Branch: https://github.com/aaronfranke/godot/tree/2d-flip

PR: https://github.com/godotengine/godot/pull/37013 (also https://github.com/godotengine/godot-design/pull/51)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

The workaround is to ignore the problem and accept the current icon.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This can't be an add-on in the asset library.

**Comment by Jummit** [comment]
Wouldn't the 3d icon have to be flipped too?

**Comment by aaronfranke** [comment]
@Jummit No, why would it? The Y axis points up in 3D:

![Screenshot from 2020-11-12 02-16-49](https://user-images.githubusercontent.com/1646875/98907713-487be580-248d-11eb-8552-fdb2ce58b31b.png)

**Comment by Xrayez** [comment]
> There are already other icons shaped in this way, such as all the curve icons and GraphEdit:
> 
> ![Screenshot from 2020-11-12 01-03-53](https://user-images.githubusercontent.com/1646875/98902148-21201b00-2483-11eb-80b5-29da7aef2f87.png)

I think it makes more sense here especially with arrow pointing up to edited object. On the other hand:

> ![old](https://user-images.githubusercontent.com/1646875/76601616-aa8be180-64df-11ea-86d7-b30c0ed04e74.png)

Those icons are general-purpose enough in comparison. I think there's no absolute need for those icons to suggest the real conventions. In fact, I don't see a reason why Y should point down because it's totally possible to come up with your own conventions in Godot, even if the underlying architecture is different.

**Comment by andre-caldas** [comment]
> I don't see a reason why Y should point down because it's totally possible to come up with your own conventions in Godot, even if the underlying architecture is different.

Unless I am missing something, there are side-effects. Clockwise becomes counter-clockwise, for instance. `Vector2D.UP` will point down.

I would prefer to keep the icon and change Godot's orientation. But I am afraid of being lynched. :-(

When we write texts in English, we do so left to right and top to bottom. I think it made a lot of sense, back in the old days, that the origin was the top left corner of the screen. The icon that displays the usual orientation for the x-y axis is just a symptom that making Y point down might not be what most people expect.

On the other hand, if you had let mathematicians build the very first hand watch, clocks would spin to the *counter-clockwise* direction. =o)
