### ISSUE TITLE
Reformat Transform(2D) matrix display in the inspector

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#1820]
**Describe the project you are working on:** Godot

**Describe the problem or limitation you are having in your project:**

In master, the Transform editors in the inspector are a bit of a mess. Columns are displayed horizontally, rows displayed vertically, there is repeated information, and labels are non-unique. Also, Node2D is completely missing a section for its matrix, so it's impossible to edit a 2D node's transform matrix directly without using a script.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The proposal is to make the following changes:

* For Node3D, remove the duplicated translation information by displaying the `Basis` instead of the `Transform`.

* For Node3D, rename "Matrix" to "Raw Matrix" to better convey that this is how Godot works under-the-hood, and to slightly discourage users who don't know what it is from touching it.

* For Node2D, show the Transform2D similarly to Node3D, so that you can edit the transformation matrix from the inspector.

* For all matrix types, transpose them so that they correctly have columns displayed vertically and rows displayed horizontally.

* For all matrix types, change the labels to be unique for each field.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Branch: https://github.com/aaronfranke/godot/tree/transform-editor

PR: https://github.com/godotengine/godot/pull/32068

Everything in that PR should be good to go right now. Here are some before and after screenshots, the left side is before, the right side is after. There are exported values, Node2D, and Node3D. Each side has equivalent values to each other, the Y component of the X column vector (row 2 col 1) is set to 5 for most of the examples, and for Node2D the rotation is set to 5.

![Untitled](https://user-images.githubusercontent.com/1646875/111742689-fd207c00-885e-11eb-806b-86fd52875422.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Yes, there are ways to work around this. For 3D, you can just remember to transpose it in your head. For 2D the only way to edit the matrix directly is if you use a `tool` script, which is very un-ideal.

**Is there a reason why this should be core and not an add-on in the asset library?:**

The inspector is core, and these data structures are core, so how the structures are displayed in the editor should be core.

**Comment by jonbonazza** [comment]
In regards to rows vs columns, are godot transform matricies column major or row major? If they are column major then having columns displayed vertically makes sense.

**Comment by aaronfranke** [comment]
@jonbonazza Godot's transformation matrices are column-major, in that the left-most column represents the components of the X vector of the transformation matrix, and the 2nd-left-most column is the Y vector, etc. [Read more here](https://docs.godotengine.org/en/latest/tutorials/math/matrices_and_transforms.html).

**Comment by jonbonazza** [comment]
> @jonbonazza Godot's transformation matrices are column-major, in that the left-most column represents the components of the X vector of the transformation matrix, and the 2nd-left-most column is the Y vector, etc. [Read more here](https://docs.godotengine.org/en/latest/tutorials/math/matrices_and_transforms.html).
> 
> ![3d](https://camo.githubusercontent.com/ee0c07ea88b29fd2bc3919e4920764a3c9155f613576b227cd71f3d3837d16bc/68747470733a2f2f646f63732e676f646f74656e67696e652e6f72672f656e2f6c61746573742f5f696d616765732f33642d6964656e746974792e706e67)

In that case, i think having the transform field the way it is in the inspector makes sense, since this field is the transformation matrix from my understanding.
