### ISSUE TITLE
Improve AnimatedTexture resource

### ISSUE THREAD

**Issue by DiiaBlood** [godotengine/godot-proposals#1825]
**Describe the project you are working on:**
3D low poly FPS horror game with very low Texture (Albedo, Normal, Rough)

**Describe the problem or limitation you are having in your project:**
The limitations of the resource "Animatedtexture" is the problem, I see the Animatedtexture as an amazing resource and an extremely useful one, But it has very limited control (255 framesh, 2 methods, 4 properties, etc)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I dont have a solid idea of how to specifcly fix it or make it better but I could say make it have mych much more controls like animationplayer, E.G having a func called PlayFrom("Frame") to play the animated texture from the frame the user give, and so on

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Giving the animatedtexture more methods and properties to work with should be it and maybe some visual controls like the animationplayer 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Kinda yeah, What Im doing now in fact is replacing the animatedtexture with an animationplayer node and making it change the texture of the object every XX sec in the timeline and every XX I added a new frame which takes a lot of time to make each frame but it is a work around and somtimes when u want multiable objects to have the same Animatedtexture this work around will fail

**Is there a reason why this should be core and not an add-on in the asset library?:**
making the animatedtexture much more friendly and giving the user more control over should make the workflow much faster with way fewer limitation.

**Comment by Calinou** [comment]
AnimatedTexture and AnimatedSprite are deliberately meant to be used for simple use cases only. For advanced use cases, use Sprite + AnimationPLayer.

**Comment by KoBeWi** [comment]
> AnimatedTexture and AnimatedSprite are deliberately meant to be used for simple use cases only.

Not only that, AnimatedTexture has several limitations, which in return make it very efficient (e.g. you can't use atlases). This proposal is likely impossible to implement.

Also you say that AnimatedTexture is very limited, but you don't specify why is it a problem. Alternate solutions already exist for your use-case.

**Comment by itsjavi** [comment]
Would it be possible to be able to use a tile from a tileset on every AnimatedTexture frame, instead of having to make and use individual image files for each frame?

**Comment by PLyczkowski** [comment]
When I tried to use it in a shader (for vfx) the problem I encountered was that there is no way to control which frame is displayed, so there was no way for the shader instances to display a different frame

**Comment by Calinou** [comment]
Note that https://github.com/godotengine/godot/pull/49685 was recently implemented in the `master` branch, which makes it possible to easily implement animated textures when using low-level draw functions.

**Comment by Calinou** [comment]
Closing, as this proposal is too vague as it stands. See also https://github.com/godotengine/godot-proposals/issues/8329.
