### ISSUE TITLE
Add polyphony to allow playing multiple sounds at the same time in AudioStreamPlayer

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot-proposals#1827]
**Describe the project you are working on:**
A game.

**Describe the problem or limitation you are having in your project:**
Calling `$AudioStreamPlayer.play()` again truncates the audio being played if it hasn't finished yet. This is fine for music, but very inconvenient when you are implementing repetitive sound effects (e.g. gunshots, typewriter sounds, etc.). See also godotengine/godot#23541.

> The old Godot 2 sample players had the ability to play multiple sounds at once, using the same node.
Now, in Godot 3, one AudioStreamPlayerXX can only play one stream at a time.

![](https://user-images.githubusercontent.com/47700418/98998724-a5d46d00-2547-11eb-9e72-127944b928db.png)
_1\. The previous sound ends before the next one begins.
2.1\. The previous sound is cut off (current behavior).
2.2\. The next sound is mixed with the previous one(s) (the behavior I want to achieve)._

It is not trivial to work around this problem (you need to either create an `AudioStreamPlayer` every time (and then delete it), or keep the `AudioStreamPlayer`s pool).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I see two options:
1. Add a sound mixing mode that changes the behavior of the `AudioStreamPlayer.play()` method.
2. Add method `AudioServer.play_sound(stream: AudioStream, bus_idx: int = 0, volume_db: float = 0.0)`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, the workaround is either complicated or has less performance.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is often used in many games.

**Comment by Calinou** [comment]
This was supposed with a **Polyphony** property in Godot 2.x, but it hasn't been reimplemented in Godot 3.0 onwards (I don't know why).
