### ISSUE TITLE
Allow any nodes to become a parent node when dragged to the bottom of the tree

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#183]
**Describe the project you are working on:**
I work with Nodes in Godot

**Describe the problem or limitation you are having in your project:**
Working with nodes in the Scene Panel is fantastic. Drag and drop works beautifully for the most part. Thanks to the blue line and rectangle indicator, I can very deliberately drag nodes to precisely the location in the scene tree I intend to. There is hardly anything left to be desired except one thing that is bugging me like crazy: Dragging parent nodes (children of the root node) to the bottom position of the tree is not problem, but dragging children of those parent nodes to the bottom is impossibru.

I often add child nodes by accident to the wrong parent. Often this happens when I add a new node, but did not bother selecting the root node first. But there are plenty of other occasions where I want a specific child node (and often it's children) to be a parent node at bottom of my tree.
Because Godot does not allow me to directly drag a child node at the bottom of the tree, I first have to drag it above a parent node, then once it is a parent node I can drag it down to the bottom:

![lastnode_scenepanel](https://user-images.githubusercontent.com/47016402/67535176-c548ef80-f6d1-11e9-96d2-d5e7cc40b911.gif)

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
This would complete the otherwise great drag/drop functionality within the Scene panel. 

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
See description and gif above.

**Describe implementation detail for your proposal (in code), if possible:**
I can't count further than B++

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I believe others have this problem too.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a minor UX improvement of existing core features.

**Comment by golddotasksquestions** [comment]
Did some more testing, this starts looking more like a bug to me. It's not just child nodes, it's actually any node:
As soon as the last node in the scene tree is a node with children, **no node** can be dragged at the bottom anymore:
![lastnode_scenepanel02](https://user-images.githubusercontent.com/47016402/67586703-873fe000-f752-11e9-8003-0fdc51d437e5.gif)

Moving child nodes to the bottom position in the tree works, if the current bottom node does not have any children:
![lastnode_scenepanel03](https://user-images.githubusercontent.com/47016402/67586873-ec93d100-f752-11e9-94db-5d98005e907b.gif)

**Comment by akien-mga** [comment]
This is indeed a bug in the existing drag reordering feature. Note that you can already achieve what you want by dragging the node to its desired parent (in your GIF it would be Spatial), which adds it as the last child node.

Moved to godotengine/godot#36300.
