### ISSUE TITLE
Search in scenes' fields (the ones in the inspector) instead of just in the GD script files

### ISSUE THREAD

**Issue by julsams** [godotengine/godot-proposals#1837]
**Describe the project you are working on:**
A casual game

**Describe the problem or limitation you are having in your project:**
Unable to search in fields to find a node with specific texts or attributes' values.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would be great search results (ctrl+shift f) includes values stored in fields in the inspector.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
When you do a search in GDScript, it will also return .tscn files with attributes' values that match the search.

I suspect the implementation is easy. It is kind of like a grep on tscn files (I think) which is very similar to how the search works currently on gd files.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The programmer could assign all attributes in the code but I suspect that you can assign attributes to nodes in the inspector because this is useful to game designers.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It doesn't sound like an add-on but I am not sure exactly how plugins work.

**Comment by Calinou** [comment]
It would be possible to allow `.tscn` and `.tres` a filter, but this has two downsides:

- The output won't necessarily be human-readable.
- Binary `.scn` files can't be searched into.

**Comment by KoBeWi** [comment]
This can be enabled in Project Settings under Application -> Editor -> Search In File Extensions.

**Comment by julsams** [comment]
> This can be enabled in Project Settings under Application -> Editor -> Search In File Extensions.

Many thanks!
This answer was not readily available on Google and Godot Q&A.
Thank you took the time to help.

Added this answer here with credit:
[Question about this](https://godotengine.org/qa/5245/how-to-search-in-all-scripts)
