### ISSUE TITLE
Display a message when the search in AssetLib doesn't find anything

### ISSUE THREAD

**Issue by rezgi** [godotengine/godot-proposals#184]
**Describe the project you are working on:**
Learning Godot by making a small platformer

**Describe the problem or limitation you are having in your project:**
I wanted to use VCS for my project and searched 'VCS' in the AssetLib, and nothing was displayed, so I didn't know if there was a bug or if it found nothing.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It will be less confusing to have a message saying "nothing found" or something like this.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
<img width="1440" alt="Screen Shot 2019-10-25 at 21 47 53" src="https://user-images.githubusercontent.com/41618561/67603599-4dca9d00-f771-11e9-86df-3fd085a4b7ef.png">

**Describe implementation detail for your proposal (in code), if possible:**
Display a text in the search results saying that nothing was found

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
That would be a lot of code for something so small

**Is there a reason why this should be core and not an add-on in the asset library?:**
Everyone searches in the AssetLib and it would be better to avoid confusion for them when using the software

**Comment by Calinou** [comment]
> Umm.. I have a nice screenshot but don't know how to put it here ^^

You can drag-and-drop files in the editing box, they will be uploaded to GitHub automatically.

**Comment by KoBeWi** [comment]
> You can drag-and-drop files in the editing box, they will be uploaded to GitHub automatically.

You can also copy-paste image contents directly into text area and it will automatically get embedded.

**Comment by rezgi** [comment]
Haha it was way simpler than I thought. Thanks for the info, I updated to issue.
