### ISSUE TITLE
Provide also a cameCase naming for all GDScript functions and variable naming

### ISSUE THREAD

**Issue by dmitryuck** [godotengine/godot-proposals#1841]
**Describe the project you are working on:**
Not important

**Describe the problem or limitation you are having in your project:**
c_like_syntax is used by default in Godot for GDScript and this has historically happened.
but how about the idea to provide a camelCase syntax along with c_like
for some people it does matter me believe

**Describe the feature/enhancement and how it helps to overcome the problem or limitation:**
This is maybe a problem to pick up a Godot with GDScript for some who came from other languages
where camelCase syntax is used

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
var newVar: int = 0

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no

**Is there a reason why this should be core and not an add-on in the asset library?:**
GDScript is the core language

**Comment by Calinou** [comment]
[Style guides are meant to be followed](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html) :slightly_smiling_face: 

I don't think providing an alternative syntax is worth the cost.

If you absolutely need PascalCase/camelCase, consider using [C#](https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html) instead. That said, keep in mind you shouldn't choose a programming language for its syntax alone.

**Comment by pycbouh** [comment]
> for some who came from other languages where camelCase syntax is used

I don't really see how the style of naming can affect the learning curve of GDScript if you're otherwise familiar with programming. If anything, knowing other languages would make it easier to learn GDScript, whatever naming case it uses.

**Comment by dmitryuck** [comment]
It doesn't influence the learning curve, this is more about code perception
for me using C#, Dart, Js before c_like syntax looks weird
but GDScript very good, I believe giving an option to user write in the style they are used to would involve more developers using GDS,
regarding a mechanism to maintain code, maybe it could be kind of synonyms of functions like

func _physics_process:
pass

func _physicsProcess:
pass

**Comment by pycbouh** [comment]
Users are free to write their own code in whichever style suits them, but bringing such optional features to the core would only fuel chaos and arguments over which code style is better. Since you come from JS among others, you should know what I'm talking about. Stricter language is better, and the core API is a part of it.

**Comment by CedNaru** [comment]
Coming from CamelCase languages, I also prefer this style. 
But one consistent syntax is more important than pleasing everyone's eyes. 
It seems good on paper to give more "customization" to users but in the long run, I think it only adds more confusion and cost for virtually 0 gain. 
In the end, once you are used to several languages, you can easily manage any syntaxic change.

**Comment by Calinou** [comment]
Closing due to lack of support – see the above discussion.
