### ISSUE TITLE
Add pseudo-localization to better spot untranslated strings and unexpected layout changes caused by long strings

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#1844]
**Describe the project you are working on:**

The Godot editor :slightly_smiling_face: 

**Describe the problem or limitation you are having in your project:**

- When running your project, there's no way to immediately see which strings are translatable and which ones aren't. You have to fully translate the project to a language before you can detect non-translatable strings.
- Unexpected layout changes can also occur when translators use strings that are too long to fit in existing buttons/labels.
- Moreover, if you're translating to a language which only uses a Latin-1 character set, it might be difficult to notice that your font doesn't support the full character set required to support some languages out there. This may be a problem if you plan to localize to more languages in the future.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The 3 problems above can be detected early on by using *pseudo-localization* while developing the project. It performs two things:

- Replace characters with special characters while keeping the original strings readable.
- Add a constant prefix and suffix to each string to make them longer.

For instance, `Account Settings` could be turned into `[!!! Àççôûñţ Šéţţîñĝš !!!]`.

### Without pseudo-localization

![Without pseudo-localization](https://symfony.com/uploads/assets/blog/pseudolocalization-symfony-demo-disabled.png)

### With pseudo-localization

![With pseudo-localization](https://symfony.com/uploads/assets/blog/pseudolocalization-symfony-demo-enabled.png)

It looks pretty cursed at first, but this technique is actually known to improve the internationalization workflow :slightly_smiling_face: 

More information can be found in [this Symfony blog article](https://symfony.com/blog/new-in-symfony-5-2-pseudo-localization-translator).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

There could be a project setting and method in the TranslationServer to toggle this feature.

Note that this should work *in addition* to the existing localization. This way, if you use CSV translation keys, you still get to see the translated strings in your own language, except they'll be altered as mentioned above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't think a script can hook into the TranslationServer this way. Ideally, it should work with all `tr()` calls in addition to the automatic localization performed in Control nodes.

**Is there a reason why this should be core and not an add-on in the asset library?:**

See above.

**Comment by HaSa1002** [comment]
superseeds https://github.com/godotengine/godot-proposals/issues/284
If you need a prelimnary UI Debug Feature, you can use the method described in the proposal and use [this tool](https://github.com/HaSa1002/tool_make_longest_translation/blob/master/make_longest_translation.py).

**Comment by vnen** [comment]
This should have an option to test RTL (right-to-left) text and layout, since the position of elements will also change because of UI mirroring (see https://godotengine.org/article/complex-text-layouts-progress-report-2 for example)

**Comment by revanj** [comment]
Could similar functionalities be achieved by a subnode or a parent class that checks translation data and then automatically fill it if the translation data is empty? Will there be performance/usability issues if it's done this way?

**Comment by Calinou** [comment]
**Note:** This proposal is being worked on as part of a Google Summer of Code 2021 project. Stay tuned :slightly_smiling_face:

**Comment by angad-k** [comment]
Hey! 👋🏽  I'm Angad Kambli and I'll be working on this proposal over the next two months as a part of GSoC 2021. You can check the progress here in this [PR](https://github.com/godotengine/godot/pull/49361) I've already opened. 
You can read my in-depth proposal for the same [here](https://docs.google.com/document/d/1bz3hCe7ljByheO11YZaoNKi0eBhwP8ClH6kJ7PkxwNU/edit?usp=sharing).
I'll be implementing the following things related to pseudolocalization : 

- Flow for replacing characters with their accented variants.
- An option to check for rtl support by turning on fakebidi.
- Dynamic length expansion for strings.

The ui for the project settings for the same could look something like this : 
<p align="center">
<img src="https://i.imgur.com/vEzEip4.png" alt="Pseudolocalization settings" width="65%" />
</p>

Any suggestions are welcome 😃

**Comment by HaSa1002** [comment]
Can you consider adding something like I proposed in #284? It is more for final projects where the translations are already implemented and you need to verify your UI Layout. I don't know how well it fits into this feature work. I assume, it may be easy to implement it as well, because you are touching the code anyway. That being said, I just wanted to raise the issue again, but it is not so important as it can be achieved by creating a translation that contains all the longest strings.

For the UI proposal:
Idk, but it feels a lot like wasted space and since it is a tool rather than a project setting I wouldn't search it there. I would put it into the tools menu. Also, please replace the Checkbox with an switchbutton or how they are called. They are IMO the better control as a change happens when the button is pressed.

**Comment by Calinou** [comment]
I think it would be better to expose those options as generic project settings rather than adding a dedicated Pseudolocalization tab to the Project Settings tab.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/51395 (and backported to `3.x` by https://github.com/godotengine/godot/pull/51404), closing.

See https://github.com/godotengine/godot-demo-projects/pull/637 and https://github.com/godotengine/godot-docs/pull/5119 for demos and documentation.
