### ISSUE TITLE
I want to make a community of godot in china

### ISSUE THREAD

**Issue by RealSYWW** [godotengine/godot-proposals#1845]
Hello,the programmer team of Godot.I'm a middle school student in china,maybe my English is not well.I love Godot game engine,I want to make a community of godot in china.Because of transnational commection,chinese user can't go to the website comfortably,so I want to change it.I can set up forum and chinese website,you well became one of admins.I use open source forum system Discuz!:https://www.discuz.net/forum.php,it's a good open source forum system,and it also can set up website.If you're agree me,please call me back.Thanks.

**Comment by groud** [comment]
Hi @RealSYWW, welcome!

As this repository is for asking improvement proposal to Godot, I'll close this issue. But if you want to register your community, you may want to follow the instruction there: https://github.com/godotengine/community-map. We are going to create a map with all godot communities, so you might want to add yours there, with a link to your forum.

If you want you can also reach out to people from the community on other platforms, see: https://godotengine.org/community
You might find help there if you need so.
