### ISSUE TITLE
Add a rotation widget to the 3D viewport

### ISSUE THREAD

**Issue by JFonS** [godotengine/godot-proposals#185]
I'm working on a rotation widget for the 3D viewport. It's mostly done and working but I could use some feedback on any extra features or the visual design for it (size, colors, etc.) since right now I just copied the Blender widget.

**Describe the project you are working on:**
Any 3D project can benefit form the change.

**Describe the problem or limitation you are having in your project:**
It's sometimes hard to tell the current camera orientation and/or it's hard to orbit the camera when using a touchpad.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The rotation visualization helps the user tell the current camera rotation as well as changing to the predefined views by clicking on the different axes. 

The 3D viewport camera can be orbited by left clicking on the widget, so laptop users should finally be able to use the viewport in a more sane way.

I also added an auto-orthogonal feature. Setting the any of the axis views also sets the camera to orthogonal mode, but when the camera is rotated it turns back to perspective. I can't really think of any drawbacks of this, but I'm open to suggestions.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![Peek 2019-10-27 00-33](https://user-images.githubusercontent.com/4402304/67626970-ea656b80-f853-11e9-8fe8-0206d5a6ad1d.gif)

**Describe implementation detail for your proposal (in code), if possible:**
WIP pull request: https://github.com/godotengine/godot/pull/33098

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's just a UX improvement in the viewport that benefits all 3D projects.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's just a UX improvement in the viewport that benefits all 3D projects.

**Comment by fracteed** [comment]
This will be very useful for trackpad 3d usage. Auto-ortho switching is also nice. Please add an option to be able to turn the widget off, for those of us that generally dislike viewcubes :)

**Comment by asheraryam** [comment]
The PR looks great but it'd be nice if there could be a tooltip when hovering to indicate which axis is which. Especially in the case of x/z it's often frustrating to make sense of it. 

If a tooltip/infotest is not technically possible then perhaps literally writing x/y/z in small font on the widget itself.

**Comment by clayjohn** [comment]
@asheraryam the colors already match up with the colors of the XYZ axis in the Viewport itself. And those colors match up with the font color for the x, y, and z values in the inspector. Is that helpful enough? 

Are you currently getting confused about which axis is which? Im wondering if there is more we can do.

**Comment by asheraryam** [comment]
@clayjohn I've used the engine in a hobbyist (non-engine developer) capacity for a few hundred hours over the past 3 years and I still cannot visually differentiate between x and z (y is obvious because it's orthogonal to the sky horizon).

It's not a major issue worth spending a lot of time on, but if adding small text symbols to the widget is doable then it would be very welcome.

**Comment by Calinou** [comment]
Blender has visible axis names on the closest circles:

![image](https://user-images.githubusercontent.com/180032/67633297-84f29880-f8ae-11e9-94df-35a79219016e.png)

**Comment by asheraryam** [comment]
@Calinou That would be quite lovely and helpful. 👍

**Comment by MCrafterzz** [comment]
It would make it look better aswell so I agree

**Comment by JFonS** [comment]
I tried adding axis labels inside the small circles but it's tricky to get it right. I will keep working on it on my free time.

**Comment by Zireael07** [comment]
Someone pointed out on the PR that this widget covers the FPS info in editor, though - any ideas where to move the FPS, since the widget's probably there to stay?

**Comment by Calinou** [comment]
> BTW @Calinou, are there any drawbacks to adding a new editor font?

I'd prefer if we could use one of the existing fonts (default, bold, or monospace) for better visual consistency and lower binary sizes.

**Comment by JFonS** [comment]
I updated the PR, here's how it looks now: https://streamable.com/p4sw4
