### ISSUE TITLE
Add option to opt in to bone name sanitization in GLTF importer

### ISSUE THREAD

**Issue by geneishouko** [godotengine/godot-proposals#1855]
**Describe the project you are working on:**
It's a 3D character creator game with skeletal body customization and wearables

**Describe the problem or limitation you are having in your project:**
We rely on accessing the character skeleton programmatically to customize the body but the skeleton bones names have been changed from what was originally exported as GLTF from Blender. Our original bones use the "a01_S_BoneName_01" naming pattern but it is changed to a snake_case form on import by the GLTF importer to something like "a01_s_bone_name_1" thus making access to bones unpredictable.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
While the bone name sanitization process the GLTF importer does surely solves a corner case, it shouldn't be applied to every GLTF document. Skipping the renaming of bones lets users know their bone names remain unchanged and allows them to keep their preferred naming pattern. An import option should be added to the importer to opt in to this feature.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A boolean option named, for example, "verbatim names" is added to the importer. If enabled, the bone name sanitization is skipped on import/re-import.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The features discussed here occur during the import process and can't be worked around with a script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a change of behavior proposal for a core module.

Originally reported as godotengine/godot#43482

**Comment by Calinou** [comment]
Related to #1672.

**Comment by fire** [comment]
I wanted to investigate this.

```c++
String GLTFDocument::_sanitize_bone_name(const String &name) {
	String p_name = name.camelcase_to_underscore(true);

	RegEx pattern_nocolon(":");
	p_name = pattern_nocolon.sub(p_name, "_", true);

	RegEx pattern_noslash("/");
	p_name = pattern_noslash.sub(p_name, "_", true);

	RegEx pattern_nospace(" +");
	p_name = pattern_nospace.sub(p_name, "_", true);

	RegEx pattern_multiple("_+");
	p_name = pattern_multiple.sub(p_name, "_", true);

	RegEx pattern_padded("0+(\\d+)");
	p_name = pattern_padded.sub(p_name, "$1", true);

	return p_name;
}
```

Currently this is the sanitation of the bone names. I want the minimal required.

Because of https://github.com/godotengine/godot/pull/46939 we should also match node limits.
