### ISSUE TITLE
Custom C# class support for features such as Export and Signals

### ISSUE THREAD

**Issue by oakenmoon** [godotengine/godot-proposals#1857]
Quick edit: Forgot to apply labels, sorry about that- Probably falls under topic:core and topic:mono, if I were to guess.
A forewarning: I don't know whether it's reasonably possible to do this in the way I want it to be done, this thing is already (somewhat) possible via modifying the engine yourself, just not in an ideal way (See the "How does it help to overcome the problem/limitation section), and it's a bit of a niche request. Figured I'd put this forewarning here to avoid wasting anyone's time.

**Describe the project you are working on:**
I'm working on a video game using C# with Godot. I'll fully admit that the code for the game is a bit odd and hacked-together at times. I am using v3.2.2, so if this has already been added, sorry about that.

**Describe the problem or limitation you are having in your project:**
I've created a custom C# class, InvItem, to prevent potential item data desync issues and allow for easier addition of details to items. It's a fairly simple class so far, just has a variable for item ID, one for custom item data, one for the item's inventory texture, stuff like that. 
As far as I can tell, I cannot set a custom InvItem property as [Export], unlike built-in data types, and I can't pass it as an argument through a custom signal. I also can't use it in Object.Call, which is one of the most versatile functions, at least in my experience.
In case this is a bug, and if so apologies for posting in the wrong place, here's the errors it gives when I try to do those things in a forum post:
https://godotengine.org/qa/87710/how-do-i-get-godot-to-recognize-custom-classes-with-c%23

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Some kind of support for this would be excellent. While it seems certainly possible to do what I want to do by adding a data type to the editor using C++, this seems complex and not nearly as easy-to-modify, which is half the point of creating a C# class for this. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Absolutely no clue how this would work code-wise, being entirely honest. It _seems_ simple enough, but I don't know C++ nor how the engine is coded or designed. It's possible that it's just not feasible to transmit custom C# classes through stuff like properties or signals, if I was asked why I'd guess it's because of how Variants work.

As for functionality-wise, perhaps adding an option somewhere in the editor settings to declare your own data type, or to recognize either a .cs file as containing a class that acts like a datatype or the class that acts like a datatype itself could work? 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Maybe? Getting around the limitation with signals seems possible using the C# Events, though considering Object.Call also seemingly doesn't much like custom classes, there's not much replacement for custom properties using custom classes without seemingly complicated sets of C# Events.

**Is there a reason why this should be core and not an add-on in the asset library?:**
To be honest, not really, it seems like a bit of a niche request. Main reason it wouldn't be that I can imagine would be simply difficulty of coding such a thing into an addon. If there's an addon that already does this, then apologies, didn't realize it existed. 

I hope this was a sufficient amount of information. If needed, I can attempt to supply more.

**Comment by Calinou** [comment]
Did you see [this article](https://godotengine.org/article/csharp-ios-signals-events?

**Comment by oakenmoon** [comment]
I have not. Seems neat and like some excellent progress on the engine, but it seems like (at least, as far as I interpreted it) it'll still emit a signal even when done, which seems to me like it has the possibility of the same errors. Correct me if I'm wrong, though.
Is that change available in Godot 3.2.3? If so, I'll try it out, see if it works as I need.

**Comment by oakenmoon** [comment]
Update: Found a workaround! By making my InvItem class an extension of Godot.Object (or whatever doing "public class InvItem **: Godot.Object**" is called), it works perfectly!
