### ISSUE TITLE
Add custom archive file-format as module along with current .pck and .zip

### ISSUE THREAD

**Issue by sharkist** [godotengine/godot-proposals#186]
**Intro**

It would be great if godot gave the opportunity to create their own custom archive formats by adding own modules.
currently is builtin .pck and .zip only. But it would be great if everyone could create their own through modules.
additionally it would somehow protect against assets being stolen through script-kiddies.

**Describe the project you are working on:**

Various games, 2D RPGs etc.

**Describe the problem or limitation you are having in your project:**
**Describe how this feature / enhancement will help you overcome this problem or limitation:**

its actually hard to create custom archive fileformat. because you need to search the godot-code for functions that apply to it:
- add line with: packed_data->add_pack_source (custom_packed_data);  in   godot/main/main.cpp
- add functions: save_custom(...) and export_custom(...) in editor/editor_export.cpp for export
- add to _export_pck_zip_selected() your own function platform->export_custom(); in editor/project_export.cpp
and ofcourse:
- add file_access_custom.cpp / .h in core/io/ (but ofcourse you need it to create)

**Describe implementation detail for your proposal (in code), if possible:**

it wouldn't be better if you create it only with the module, something like that?:

```
static Ref<CustomArchive> your_archive;
void register_customarchive_types() {

	your_archive.instance();
	ArchiveLoader::add_archive_format_loader(your_archive);
} 
void unregister_customarchive_types() {
	ArchiveLoader::remove_archive_format_loader(your_archive);
	your_archive.unref();
}
```

**Comment by Calinou** [comment]
> additionally it would somehow protect against assets being stolen through script-kiddies.

Regardless of the archive format you use, textures can still be extracted with tools such as [RenderDoc](https://renderdoc.org/) :slightly_smiling_face:

**Comment by Jummit** [comment]
You missed the
> Describe the problem or limitation you are having in your project
section. If you can't put anything there, then I have a feeling you don't actually need this feature.

**Comment by Sslaxx** [comment]
Eh. Maybe something to make it easier for reverse-engineering projects like Daggerfall Unity on Godot, but that'd likely be done via GDNative anyway. .bsa, .wad etc.

But the topic is about not having inbuilt support for such formats anyway, but about allowing externally built modules to make support for them appear (in Godot) as if they were native. Allowing access (as in the code snippet) to register archive types to function as if they were .pck/.zip files might no go amiss. If nothing else, perhaps .7z support? In any case, the developer would still have to write the code to support the formats themselves in any case.

**Comment by Calinou** [comment]
Closing due to lack of support.

Note that PCK files can now be encrypted: https://docs.godotengine.org/en/latest/development/compiling/compiling_with_script_encryption_key.html
