### ISSUE TITLE
Use dark mode for the window title bar on Windows 10

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-proposals#1868]
**Describe the project you are working on:**
Any

**Describe the problem or limitation you are having in your project:**
When OS-wide dark mode is enabled on Windows, Godot still has a white title bar.
![image](https://user-images.githubusercontent.com/1311555/99886751-e1052900-2c36-11eb-9df9-3778374ed2f3.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Instead, it should follow the same color scheme and have a dark color.
(A similar issue was raised and fixed on MacOS: https://github.com/godotengine/godot/pull/27264)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm no expert in that OS-specific part, ~~but I suppose it should be relatively simple to do?~~
The color to pick could come from the editor theme, or from the OS if there is an API to obtain it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's OS-specific and there is nothing exposed to do this from a script AFAIK, it would be very inconvenient to do that with an addon anyways.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It relates to the core windowing system, used for games, editor and project manager.

**Comment by bruvzg** [comment]
Isn't it UWP only feature?

**Comment by Zylann** [comment]
I think in this day and age, we should be able to have this... but if we cant somehow, that would be very sad :/

**Comment by Calinou** [comment]
The only way we can implement this is to use client-side decorations; in other words, replace Godot's title bars with our own.

Other than that, you can change your OS settings to make title bars dark. Set the accent color to the darkest allowed color (`#333333`) and make the accent color affect the title bar.

**Comment by Xrayez** [comment]
If I understand correctly, I do have dark title bars in dark mode on Windows:

![image](https://user-images.githubusercontent.com/17108460/99902509-017cc400-2cc7-11eb-94d9-8b5a759aca62.png)

Yet as pointed by Calinou, unfocused windows are white:

![image](https://user-images.githubusercontent.com/17108460/99902526-1bb6a200-2cc7-11eb-91ce-f79502eba3e5.png)

**OS build**: 18363.1198.

**Comment by VedatGunel** [comment]
You can change the unfocused title bar color through registry.

- Type in **regedit** in Start Menu to access the Registry Editor.
- Go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM`.
- Create a new DWORD and name it **AccentColorInactive**.
- Set its value to the color you want. It should be in HEX format, and BGR order. For example, if you want a pure yellow color, the value would be 00ffff.

**Comment by Arnklit** [comment]
We couldn't just get rid of the title bar completely like browsers and other modern apps are doing? We're basically just taking up a line of space to show "Godot Engine", the name of the open file and the minimize, maximize and close buttons. They could be integrated into the same line as the top menus and people would get an extra line of editor space as well.

I understand this is a way bigger ask. but it would be a nice improvement.

**Comment by Zylann** [comment]
The problem with this approach is that you would loose OS-specific behavior for resizing and positionning windows, which you'd have to re-implement (that's what happened last time I tried this on another project).

**Comment by akien-mga** [comment]
This is missing important information: how do other Windows application behave with dark mode?

Changing theme or changing registry are workarounds and not so relevant to Godot development. What matters is that Godot behaves like all other applications. If it doesn't, and Godot is the odd one out, then we can look into fixing it. Otherwise there's no point trying to workaround design decisions from the Windows devs.

**Comment by Zylann** [comment]
@akien-mga well that settles it then I guess? Thing is, this part of theming is quite a mess on Windows. Some apps follow dark mode properly, others do it halfways, others don't. Core Windows apps do have dark title bar, while those using older APIs like Notepad++ don't, and Godot is among them.

**Comment by akien-mga** [comment]
Well if some apps can do it, we might be able to too. But indeed if it's only possible using UWP APIs, we might be out of luck.

https://github.com/godotengine/godot-proposals/issues/1868#issuecomment-731733894 suggests that dark mode works for the title, only that it's then white when unfocused. Is this the experience you have with other apps like Notepad++? How do native apps look like in both focus modes?

I'm not on Windows nor using dark mode, so it's a bit hard to see what's the current status and what's the desired status.

**Comment by Zylann** [comment]
> #1868 (comment) suggests that dark mode works for the title, only that it's then white when unfocused. Is this the experience you have with other apps like Notepad++? How do native apps look like in both focus modes?

After I turned on Dark mode, title bars of notepad++ and Godot were still white.
I had to check an option in Windows setting to have the accent color on title bars (it was off by default), then I had the same behavior as Xrayez's comment on Notepad++ and Godot.

Mozilla, Slack, Explorer and Console windows were keeping a dark color when unfocused, and in fact I actually screenshoted the Console to pick that color, and applied it to the registry thanks to VedatGunel's comment. At this point I got consistent decoration colors everywhere (except maybe on Discord which has custom decorations).

**Comment by Pablo96** [comment]
I've seen this is the only issue on window client side decorations and I wonder if I could take it as a task to implement it and have a programming buddy with me to start developing on this project. I would like to contribute this to the project

**Comment by xaviervitor** [comment]
I think the correct design would be like the Windows Explorer title bar.
Focused:
![image](https://user-images.githubusercontent.com/23154422/118297393-72ea4200-b4b4-11eb-9371-ce3765b1666e.png)
Unfocused:
![image](https://user-images.githubusercontent.com/23154422/118297432-84334e80-b4b4-11eb-8f27-3068862b2cf7.png)

**Comment by pattlebass** [comment]
[It might be possible in Windows 11](https://stackoverflow.com/a/70693198), but I haven't tested anything.

**Comment by ludogue** [comment]
In fact, this is possible from a long time, but not documented.
mintty do this ( https://github.com/mintty/mintty/blob/3.6.1/src/winmain.c )
so i have checked how they do it :
```
// set DWMWA_USE_IMMERSIVE_DARK_MODE; needed for titlebar
BOOL dark = 1;
if (S_OK != pDwmSetWindowAttribute(w, 20, &dark, sizeof dark)) {
    // this would be the call before Windows build 18362
    pDwmSetWindowAttribute(w, 19, &dark, sizeof dark );
}
```
I have tested it and it's work ( i have windows 10 build 19044 )
They also check os version with GetVersion :
```
DWORD win_version = GetVersion();
uint build = HIWORD(win_version);
win_version = ((win_version & 0xff) << 8) | ((win_version >> 8) & 0xff);
//printf("Windows %d.%d Build %d\n", win_version >> 8, win_version & 0xFF, build);
if (win_version >= 0x0A00 && build >= 17763) { // minimum version 1809
```
There is also check if dark mode is enabled on the system, but i am not sure if this is allway a good solution.
I think it may rather be linked to the theme used by the application.
A need more investigation for that part, so i will stop there for now ;-)

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/65026.

**Comment by brokedarius** [comment]
There is a windows app called mica everything that should be able to change all these legacy title bars to match with the dark theme, I haven't tried it on Windows 10 only 11.
