### ISSUE TITLE
Allow Navigation to work with adjacent/connected/overlapping navigation meshes.

### ISSUE THREAD

**Issue by asheraryam** [godotengine/godot-proposals#187]
**Describe the project you are working on:**

Simple large-world rpg demo with click-to-move navigation. I use Navigation for movement with Tweening (no physics movement).

**Describe the problem or limitation you are having in your project:**

I am trying to place several navigation meshes side by side so that I can Enabling/Disabling them separately. 

However I realised that it is almost impossible to get navmeshes to line up. Effectively, using multiple navmeshes is a broken feature as they remain isolated islands. 

The only way it *did* work is when I used identical squares and line up the vertices perfectly. Squares of different sizes don't work and that's still a very simplistic scenario.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

If individual navigation meshes can link up together properly, then I get the result I need. 

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

Example: A) Two big flat areas connected using a smaller rectangle (pathway).
B) An independent room (inside) connected to the map with a small rectangular pathway (door).

![propsal godot](https://user-images.githubusercontent.com/43449832/67668323-63f67a00-f978-11e9-8daf-22198c2b0681.png)

**Describe implementation detail for your proposal (in code), if possible:**

It might work similarly to the navmesh merge in this PR https://github.com/godotengine/godot/issues/30190# but it would need to happen either at real-time whenever a navmesh is enabled/disabled, or there would be Bake Navmesh Overlap button in the inspector that would calculate and store all permutations of Enable/Disable of the child navigation instances.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

The only way it *might* be worked around is if, instead of using several pre-calculated Navigation Mesh data, it is computed at real-time in the game by adding and removing Mesh Instances, which is not feasible for large terrain meshes (and **that is why there is the option to bake Navigation Mesh data in the editor in the first place**). 

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's practically a broken feature. Why allow a Navigation node be able to have multiple Navigation Mesh instances if they're basically isolated islands? Just force users to use one Navigation Mesh for each Navigation node and merge all the geometry inside it.

This should be core because currently multiple navmeshes cannot be used together for most cases, except for gridmaps, which is less used than Height Maps or other polygon meshes.

**Comment by asheraryam** [comment]
I'd like to know if this enhancement is welcomed, and if possible how you would like it to be implemented.

I don't have a lot of bandwidth with my work but if I get an OK and a direction I would love to work on this.

**Comment by Zireael07** [comment]
I am all for this, as I tried to use multiple navmeshes for navigation in my game, and had to abandon the idea of using navmeshes completely because I couldn't get the vertices to line up exactly.

**Comment by asheraryam** [comment]
@Zireael07 Thank you for the support.

I also considered using A* or even scrapping Navigation altogether and using physics obstacles, but I have performance issues with certain large cases and Navigation Meshes with Tweening is by far **THE BEST** thing I found.

**Comment by Zireael07** [comment]
I ended up using A*, but that has the limitation of my AI not knowing when they wander off the road network.

**Comment by Calinou** [comment]
Does the new NavigationServer handle this?

**Comment by asheraryam** [comment]
@Calinou I believe it does but I haven't tried the feature on the master branch yet, so maybe @AndreaCatania can confirm.

**Comment by AndreaCatania** [comment]
Yes, it's already done.

**Comment by Zireael07** [comment]
*poke* NavigationServer is 4.0 only, 3.x still suffers from the issue. Also there are reports of the same-ish issue for 2D navpoly...

**Comment by Calinou** [comment]
@Zireael07 This is a feature proposal, not a bug report. We have very few people willing to improve the current 3.2.x navigation system.
