### ISSUE TITLE
Have a compilation error when `onready var x = $X` points to a nonexistent Node

### ISSUE THREAD

**Issue by pierpo** [godotengine/godot-proposals#1871]
**Describe the project you are working on:**

I'm working on a little turn based tank game.

**Describe the problem or limitation you are having in your project:**

Sometimes we want to add a feature related to our player. This feature implies reworking the nodes of the player scene, which will break the paths in our scripts:

```diff
- onready var sprite = $Sprite
+ onready var sprite = $Body/Sprite
```

But we only know this at runtime once the scene with `sprite` is mounted, in the errors (which we sometimes miss).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

I'm not 100% sure, but it feels like the available nodes during `_ready` is deterministic: it's always the nodes in the editor.

Meaning that if a node is missing, we can know it right away. So, the editor might be able to display an error.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

```gdscript
onready var sprite = $Sprite # Compile time error: OOPS, no node found with this path!
```

Of course, this would only affect `onready` declared variables since it's perfectly acceptable to access nodes later during run time since new nodes might have been added dynamically.

I'm not an expert with Godot, so I might miss something that would make my proposal impossible...

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I can't think of any workaround.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This feels like a built-in GDScript behaviour that would make the refactoring experience a little better.

**Comment by Calinou** [comment]
> If I don't use onready, I can add this for each variable. But it's quite annoying since it's very verbose:

var sprite

func _ready():
  sprite = $Sprite
  if sprite == null:
    push_error("$Sprite does not exist")

It's still a run-time error if you do that, not a compile-time error. `get_node()` (which `$` is an alias of) will already print an error message if the node can't be found at run-time.

**Comment by pierpo** [comment]
> > If I don't use onready, I can add this for each variable. But it's quite annoying since it's very verbose:
> > ```gdscript
> > var sprite
> > 
> > func _ready():
> >     sprite = $Sprite
> >     if sprite == null:
> >         push_error("$Sprite does not exist")
> > ```
> 
> It's still a run-time error if you do that, not a compile-time error. `get_node()` (which `$` is an alias of) will already print an error message if the node can't be found at run-time.

Good point, it's still a run-time error! I was thinking that it's right when you launch the game (so, close to a compile-time error), but it's actually not true since the scene might be mounted later in the game.

**Comment by Haledire** [comment]
If you're having issues with node hierarchies changing in during development, perhaps instead of referencing the node directly - export a `NodePath` and use that to set the sprite on ready:

`export(NodePath) var sprite_path
var sprite

func _ready():
  sprite = get_node(sprite_path)`
![demo](https://user-images.githubusercontent.com/164616/99975234-fb8eed80-2d6f-11eb-8bbd-dcacde46c5c2.gif)


This way if you move the node referenced in the NodePath in the editor, the editor keeps referencing that same node even if you were to take the node and place it inside something else.  This only works for nodes within the scene environment of course (nodes within other scene instances could pose a problem here).

**Comment by pierpo** [comment]
> If you're having issues with node hierarchies changing in during development, perhaps instead of referencing the node directly - export a `NodePath` and use that to set the sprite on ready:
> 
> `export(NodePath) var sprite_path
> var sprite
> 
> func _ready():
> sprite = get_node(sprite_path)`
> ![demo](https://user-images.githubusercontent.com/164616/99975234-fb8eed80-2d6f-11eb-8bbd-dcacde46c5c2.gif)
> 
> This way if you move the node referenced in the NodePath in the editor, the editor keeps referencing that same node even if you were to take the node and place it inside something else. This only works for nodes within the scene environment of course (nodes within other scene instances could pose a problem here).

Thank you, I think this actually solves my use cases!

I didn't know this was a practice, I've never seen it in any tutorial.
We often see the usage with the `$` selector.

I'll try it out, thanks :blush: 

I think the proposal still makes sense though.

**Comment by vnen** [comment]
The problem really is that the script cannot know to which node it's attached to. In fact, the same script can be attached to multiple nodes with different hierarchies.

The only possible way to solve this would be to leverage some editor info (the same used by the auto-completion) to add extra errors and warnings. But this would only work if you had the scene open.

What I really want to do is add a tool for static checks. Something that scans the project and checks scripts in relation to their scenes. It was started as a GSoC project but I didn't yet have the opportunity to integrate and expand.

**Comment by pierpo** [comment]
Indeed! I did not have in mind that a script might be associated with multiple nodes. This makes my suggestion way harder to implement (the compiler should check each usage of the script to detect if the path is invalid for at least one Node).

A tool for static checks would be super helpful!
GDScript is fantastic in general, but my biggest problem with it right now is the lack of such checking tools. I find it's too easy to break something without noticing. I'm really glad that the static types are being improved with Godot 4, and I hope other stuff like this will come along :blush: 

I'll to you whether or not we close this issue. I guess it's still achievable, but it looks really tricky (but I have no idea of the underlying implications of such a feature).

**Comment by nathanfranke** [comment]
It would be impossible to be completely sure. For example, `set_script(load("res://script.gd"))`

**Comment by pierpo** [comment]
Yes indeed. I think the proposal can be closed. There's no safe way to know this at compile time.

Thank you for your answers!
