### ISSUE TITLE
Add Global File search shortcut like VSCode Go to File...

### ISSUE THREAD

**Issue by lwz7512** [godotengine/godot-proposals#1872]
**Describe the project you are working on:**

a large game project which have many script/scene files

**Describe the problem or limitation you are having in your project:**

whenever i want to open a script file to check it out, i must use mouse to click multiples times, this operation take time and not efficient also not developer friendly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

By adding a `Go to File...` shortcut like vscode using key `cmd + p`, then popup a dropdown file panel including a search input, game developer could easily navigate to the target file by inputing the part of file name, thus development experience would be greatly improved.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I have no idea how to implement this ,may be included to the core of godot editor is he best way

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

no

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is a very common way for file navigation in modern IDE like vscode/sublime/atom ...

**Comment by fire** [comment]
This feature is very similar to Blender's operator search and Emac's `M-x` execute command.

I want it.

**Comment by Calinou** [comment]
Use the Quick Open Script menu, which you can open by pressing <kbd>Ctrl + Alt + O</kbd>.

There's also Quick Open Scene (<kbd>Ctrl + Shift + O</kbd>) and Quick Open (any resource, <kbd>Alt + Shift + O</kbd>).

**Comment by EricEzaM** [comment]
@Calinou already answered the request of this proposal.

@fire what you are talking about seems to be more like #1444 to me.

**Comment by Calinou** [comment]
Closing, as this feature is already available.

**Comment by lwz7512** [comment]
wow, thank you! this is a hidden skill not visible in main menu...
