### ISSUE TITLE
Allow getting function caller

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1875]
**Describe the project you are working on:**
NetworkTest

**Describe the problem or limitation you are having in your project:**
I was trying to make a overload function so everything was in one place

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Allow getting the caller of a function 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
func is_master()->bool:
    if caller is Node:
	return caller.is_network_master()
    return false
```
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think this could be used to make static modules methods and no I don't think it can

**Is there a reason why this should be core and not an add-on in the asset library?:**
It would be a good way to redirect methods to other objects and its currently not possible to do afaik

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/233.

**Comment by jonbonazza** [comment]
It's unclear to me if this is in the context of networking or just in general for gdscript.

In the context of networking, you already have `multiplayer.get_rpc_sender_id()`

If you just mean getting the caller of a method in general, that's not gonna happen. Theres no way to implement this in basically any lamguage except gdscript, so it's not something we can add to the scripting api. Besides, it's a terrible programming paradigm and one people should actively avoid. For one, it breaks the fundamental principle of encapsulation. There are far better ways of doing this, like injected composition to name one.

**Comment by Shadowblitz16** [comment]
no it doesn't have to do with networking but just getting the function invoker object

**Comment by dalexeev** [comment]
I do not think it's a good idea. As far as I know, in release builds the `get_stack()` function does not work to increase performance. I don’t remember a language that supported this feature.

After all, a function that behaves differently depending on what called it is bad style. Pure functions depend only on arguments, ordinary functions on arguments and some external state. Functions that also depend on the call stack can make the code completely non-debuggable.

**Comment by Shadowblitz16** [comment]
@dalexeev C# has extension methods and it forces oop so it can be achieved with..

```
static bool IsMaster(this Node caller) 
{
    if (caller is Node):
	return caller.IsNetworkMaster()
    return false 
}

IsMaster()

```

lua can do so like this..

```
function is_master(caller) 
    if (caller is Node):
	return caller.IsNetworkMaster()
    return false 
end

object:is_master()
```

I don't know about c++ though

**Comment by vnen** [comment]
There isn't a call stack in GDScript (there's one only for debug purposes, but it's not used on release), so I don't think this is possible to implement. Not to mention that usually that sort of stack introspection is used frowned upon and rarely performant when possible, so you would be better of finding another way of doing what you want.

**Comment by Calinou** [comment]
Closing due to lack of support (see the above comments).
