### ISSUE TITLE
Allow new properties to have default backing field

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1881]
**Describe the project you are working on:**
NetworkTest

**Describe the problem or limitation you are having in your project:**
none related to the issue I just wanted to express my concerns for the new property system

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Allow default backing fields for properties

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
var property:
  set: value = property
  get: property = value
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It would be used when you don't need a extra backing field.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It improves the flexibility of the new properties

**Comment by vnen** [comment]
This is already the case. I've said that many types in my original proposal for properties.

**Comment by Shadowblitz16** [comment]
sorry and thankyou for the info
