### ISSUE TITLE
typeof should work on built in types

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1883]
**Describe the project you are working on:**
NetworkedTest

**Describe the problem or limitation you are having in your project:**
Not related to this specific project

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
typeof should work on build in types so we can compare to type names

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
var array1 = []
var array2 = []

#All could be valid
var test1 = typeof(array1) == typeof(array2) #currently is valid
var test1 = typeof(array1) == typeof(Array ) #currently not valid
var test1 = typeof(Array ) == typeof(array2) #currently not valid
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it allows checking to a type name and no

**Is there a reason why this should be core and not an add-on in the asset library?:**
It supports static typing

**Comment by vnen** [comment]
You can just do `var test1 = array is Array` if you want to use the type name.
