### ISSUE TITLE
Rename `Node.NOTIFICATION_PATH_CHANGED` to make it not misleading

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot-proposals#1885]
**Describe the project you are working on:**
C++ Module development, but this applies to anyone using the notification system

**Describe the problem or limitation you are having in your project:**
`Node::NOTIFICATION_PATH_CHANGED` is named such that you would expect it to be triggered whenever a node is parented, unparented, or otherwise moved in the scene tree. Those are all situations in which the node path changes. However, this notification is actually only triggered when the node name changes.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Rename `NOTIFICATION_PATH_CHANGED` to `NOTIFICATION_NAME_CHANGED`.

This makes the functionality of this notification no longer misleading.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
technically you work around this by doing nothing but that's not the point

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's part of the core engine.

I don't expect this proposal to go anywhere because this change breaks a ton of compatibility, but I feel better just by writing this.

**Comment by briansemrau** [comment]
> Does it _also_ change when moved around? Because changing the name technically also changes the path, so it would actually make sense in that scenario.

When the name changes the path does change. Unfortunately, that seems to be the only case the notification is delivered. From my testing, moving the node (remove_child and add_child to another parent) does not send out PATH_CHANGED.

**Comment by Zylann** [comment]
The notification is also received if you rename a parent, so the name makes sense.

**Comment by Xrayez** [comment]
It might as well be interpreted as a bug at it's current state, unless `NOTIFICATION_PATH_CHANGED` is also propagated in other cases other than "renaming".

That said, adding, removing, or moving nodes could also technically propagate `NOTIFICATION_PATH_CHANGED`.

**Comment by briansemrau** [comment]
@Zylann I agree that enter/exit tree are what should be used in this case, and that NOTIFICATION_PATH_CHANGED should not be expanded to handle the situations I described. I just think it's unclear.

At a minimum, [the documentation](https://docs.godotengine.org/en/latest/classes/class_node.html?highlight=node#constants) should probably be updated because as it stands:
```
...
NOTIFICATION_PATH_CHANGED = 23 --- Notification received when the node's NodePath changed.
```

**Comment by Zylann** [comment]
Yeah, it should probably say:
```
Received when the node's name, or one of it's parent's name is changed
```
Though a double-check in the code would help confirm that there is no other extra case.

**Comment by aaronfranke** [comment]
What about `NOTIFICATION_PATH_RENAMED`? I think this should convey that something in the node's path has been renamed, but not other changes like reparenting. If it doesn't convey this, it should at least convey confusion rather than a misconception, which would cause users to read the documentation.
