### ISSUE TITLE
Add the ability to detect editor changes in plugins

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1891]
**Describe the project you are working on:**
GodotNetworkedEditor plugin

**Describe the problem or limitation you are having in your project:**
I need to detect changes in the editor so I can send them over to other peers

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Something like a signal in EditorPlugin that detects when any property changes in the godot editor.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
connect("editor_property_changed", self, "property_changed")

func property_changed(object, member, value):
    pass

```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I am not sure what it could be used for other then networking but it doesn't seem to be possible to do right now.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it doesn't seem to be possible to do right now

**Comment by jonbonazza** [comment]
What does "in the editor" mean specifically?

A lot of your proposals propose a solution and treat the lack of your solution as the problem. That's not how these proposals are intended to work the goal here is define a concrete, specific problem, and proposone a solution. But the problem is the most important part of the proposalz not the proposed solution. 

This problem is not concrete enough to come uo with a good solution. 

Wgat is the actual, specific problem you are encountering?

**Comment by Shadowblitz16** [comment]
I mean in the godot editor
I need to receive notifications when things change in the editor

**Comment by pycbouh** [comment]
Yeah, but what kind of *things*? What are *things*? What kind of *change* to a *thing* you are interested in tracking?

**Comment by Shadowblitz16** [comment]
everything except editor settings

**Comment by jonbonazza** [comment]
Your specific use case requires tracking every change nade in ghe editir? I find that hard to believe for a network plugin.

**Comment by jonbonazza** [comment]
Are you trying to replicate changes to the entire editor ovrr to peers or just things added by your plugin?

**Comment by Shadowblitz16** [comment]
I am trying to replicate the entire editor over the network

**Comment by jonbonazza** [comment]
I see. Unfortunately, I don't think this is doable as a plugin. It would require far too many fundamental architectural changes beyond even this one.

Is your ultimate goal increased collaboration? Or are you just attempting this project for fun?

**Comment by Shadowblitz16** [comment]
Kinda both it was because I wanted to code with my older brother and teach him godot
I also wanted to release it as a plugin

**Comment by Adwait-Codez** [comment]
how can i detect changes to node properties in editor?

**Comment by Shadowblitz16** [comment]
I'm closing my bad proposals
