### ISSUE TITLE
Add a setting to control the value of `max_physics_steps` per idle frame

### ISSUE THREAD

**Issue by Demindiro** [godotengine/godot-proposals#1893]
### Describe the project you are working on
I'm working on a physics-based game.

### Describe the problem or limitation you are having in your project
I would like to increase the speed of the physics simulation without increasing/uncapping the idle framerate. Currently the amount of physics steps per idle frame is capped at 8 ([link to code][1]).

```cpp
static const int max_physics_steps = 8;
if (fixed_fps == -1 && advance.physics_steps > max_physics_steps) {
	step -= (advance.physics_steps - max_physics_steps) * frame_slice;
	advance.physics_steps = max_physics_steps;
}
```

It _can_ be worked around by specifying `--fixed-fps` but this setting doesn't carry over when launching a project and you cannot specify it directly in release binaries.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
A project (and runtime?) setting somewhere to increase this value would be preferable over recompiling the engine to change it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
- An integer setting `physics/common/max_physics_steps`
- Perhaps a runtime property `Engine.max_physics_steps`

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes (keep it at the default value).

### Is there a reason why this should be core and not an add-on in the asset library?
It cannot be changed with an add-on.

[1]: https://github.com/godotengine/godot/blob/7e009a167110e79caa102c5b88363fd32b75293c/main/main.cpp#L2378-L2382

**Comment by Calinou** [comment]
> and you cannot specify it directly in release binaries.

The **Main Run Args** project setting still applies after exporting the project, so you can use it for release binaries that way.

**Comment by mustangchavez** [comment]
This would be very useful. We have bumped up physics_fps for our game as a partial workaround to this issue with bumpy sphere movement on flat meshes: [https://github.com/godotengine/godot/issues/50463](https://github.com/godotengine/godot/issues/50463)

But, the problem then becomes that the game starts to "slow down" if the render FPS dips below 1/8 * physics_fps.

**Comment by Calinou** [comment]
> This would be very useful. We have bumped up physics_fps for our game as a partial workaround to this issue with bumpy sphere movement on flat meshes: [godotengine/godot#50463](https://github.com/godotengine/godot/issues/50463)
> 
> But, the problem then becomes that the game starts to "slow down" if the render FPS dips below 1/8 * physics_fps.

In Godot 3.4, you can adjust the number of solver iterations performed per physics frame. This is an alternative to increasing the physics FPS to improve collision detection stability: https://github.com/godotengine/godot/pull/50255

**Comment by pouleyKetchoupp** [comment]
> 
> 
> Should we just change this value from `8` to a larger number like `16`? A value of `16` allows using a physics FPS of 480 with a rendering FPS of 30, which is pretty high already compared to the rendered FPS. I'm not sure if a project setting should be added here, as this is a very specific use case. cc @pouleyKetchoupp
> 

I guess this cap is meant to avoid spiraling into low fps, since more physics steps affect the general frame time, so I wonder if 16 would be a bit much by default.
But what about adding just a simple script function like `Engine.set_max_physics_steps()`, so we don't add a new project option for a corner case? It wouldn't be too much to add or maintain.

**Comment by mustangchavez** [comment]
Yeah, 16 would work fine for us, or `Engine.set_max_physics_steps()` would be fine, too.

I don't believe adjusting solver iterations is viable as a fix for us because, reading the discussion, it sounds like it does not affect tunneling? Tunneling is also sometimes an issue for us (the game is a racing game where you control a small spherical character that moves very quickly).

For the moment we are just looking at editing `max_physics_steps ` with a custom build, which is so far looking to be shockingly easy to do, so that's awesome!

**Comment by Calinou** [comment]
> But what about adding just a simple script function like Engine.set_max_physics_steps(), so we don't add a new project option for a corner case? It wouldn't be too much to add or maintain.

If we do that, we might as well add a project setting (which we can mark as advanced in `master`).
