### ISSUE TITLE
Remember preferred script template editor-wide instead of per-project

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#1899]
### Describe the project you are working on
Games in Godot

### Describe the problem or limitation you are having in your project
Surprisingly often it happens that I work on a new Godot project. Every single time whenever I create a new script, I forget to change the script template to empty and I end up with the cluttered default. This happens frequent enough that I'm writing this proposal right now .-.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
So basically the default script template should be saved for the editor, not per-project. Do we even support project-specific templates? With this, I can just set the template once and forget, like, forever. No matter how many new project I will be opening.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not without modifying the source.

### Is there a reason why this should be core and not an add-on in the asset library?
It's usability thing.

**Comment by Calinou** [comment]
> Do we even support project-specific templates?

Yes: https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#project-defined-templates
