### ISSUE TITLE
Animation states for UI elements

### ISSUE THREAD

**Issue by MUTEDGALAXY** [godotengine/godot-proposals#1905]
### Describe the project you are working on
I'm working on my game that uses some tricks to animate UI stuff like button focus animations etc.
### Describe the problem or limitation you are having in your project
The problem is that i can't animate Tooltips.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It would be nice to animate UI elements like unity allows us to do.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
For example: in the theme editor we can add animation for any state we want like "appear", "dissappear", "clicked", "disabled" etc. and then we can animate our state in the timeline.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
I didn't find a way to animate Tooltips.
### Is there a reason why this should be core and not an add-on in the asset library?
I don't think that we can do it in the editor itself so there is no way that someone can upload it into the asset lib.

**Comment by MUTEDGALAXY** [comment]
forgot to add core label

**Comment by Calinou** [comment]
> I didn't find a way to animate Tooltips.

You can create your own tooltip system, which I would recommend for a game if you need highly polished tooltips with custom formatting and so on.

The built-in tooltip system is mainly intended to be used in non-game applications (like the editor itself) and for prototyping.

**Comment by MUTEDGALAXY** [comment]
Makes sense, Thank you!
