### ISSUE TITLE
Open file paths in the output panel

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#1915]
### Describe the project you are working on

GDScript project with parse errors and GDNative project with loading errors.

### Describe the problem or limitation you are having in your project

When there is an error, I have to manually navigate to the path of the script/scene file.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

File paths in the Output panel could show a line when hovered over and could be followed by clicking on them.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![link demo](https://user-images.githubusercontent.com/28286961/100752774-43a1b600-33e9-11eb-9ac9-2f0a592f15f6.jpg)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a QOL change.

**Comment by Calinou** [comment]
The Output panel's text is a RichTextLabel. Implementing this could go as follows:

- Parse URLs and surround them with an `[url]` tag. We can do this for `res://` (open using the editor), `user://`, `http://` and `https://` (open using `OS.shell_open()`).
- Connect the RichTextLabel's meta_clicked signal to a method that handles links based on their protocol.

**Comment by me2beats** [comment]
Similar to this one?
https://github.com/godotengine/godot-proposals/issues/1628

**Comment by Jummit** [comment]
Yes.
