### ISSUE TITLE
Use F2 to rename files in the FileSystem tab

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#1916]
### Describe the project you are working on

Any project with files and folders.

### Describe the problem or limitation you are having in your project

To rename a file I have to right click and select rename. This is pretty slow.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As the F2 key is now no longer used to switch editors, there is no reason not to use it to rename files in the FileSystem tab.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![screen](https://user-images.githubusercontent.com/28286961/100753591-49e46200-33ea-11eb-97c3-3fe465d84689.jpg)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a QOL feature.

**Comment by Calinou** [comment]
@ericezam Can this now be bound safely now that shortcuts should no longer conflict between various docks?

**Comment by EricEzaM** [comment]
Yes! You should be able to to the shortcut context to  the filesystem dock and they will no long overlap - if all is working correctly ;)

**Comment by EricEzaM** [comment]
@Calinou ah, actually maybe not 😢

I forgot that the `shortcut_context` implementation was only on Buttons... since the shortcuts for actions in the docks do not go through Buttons or MenuButtons, that functionality is not available.

I initialled wanted to have shortcut context implemented on `Control` rather than `BaseButton` but that was pushed back.

**Comment by EricEzaM** [comment]
Yep, just implemented it and it works.
