### ISSUE TITLE
Add integer interpolation for Animations

### ISSUE THREAD

**Issue by jlapointe** [godotengine/godot-proposals#1922]
- There are certain member variables I'd like to represent as `int`, e.g. Hitpoints.
- I'd like to be able to update these member variables via keyframes in an Animation track.
- Currently, [Animations can only update variables "that can be Interpolated"](https://docs.godotengine.org/en/stable/classes/class_animation.html#enum-animation-tracktype) 
-- (so that's `float`, and data structures made of `float`s, as I understand from [the docs on Interpolation](https://docs.godotengine.org/en/stable/tutorials/math/interpolation.html)).

**Comment by KoBeWi** [comment]
It already exists, just select "Discrete" as update mode
![image](https://user-images.githubusercontent.com/2223172/100866850-8c18ac80-3499-11eb-8d48-1e025038739c.png)

btw any primitive/built-in type can be interpolated, including vectors, colors and bools. You only can't interpolate Objects.
