### ISSUE TITLE
How to indicate to C # a file contained in PCK

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#1924]
### Describe the project you are working on
TMX file parser (Tiled)

### Describe the problem or limitation you are having in your project
I created a TMX file parser using the C # XmlReader api but now I discover that there is no way to access a file contained in the PCK (file created by Godot when exporting the project).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The limitation is that you cannot use C # libraries that need a string indicating access to any file contained in a PCK

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Provide a way for Godot to C # access a file contained in the PCK

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I think not

### Is there a reason why this should be core and not an add-on in the asset library?
I think it is not possible, it must be done from Godot internally.

**Comment by neikeq** [comment]
You can pass a stream to XmlReader rather than a file path. Right now Godot doesn't provide a stream class for its virtual file system, but that will change once #40775 is merged. You can grab the [FileStream](https://github.com/godotengine/godot/blob/eafb1a2dff95bd1c25231ecb46febdbd1544bc8d/modules/mono/glue/GodotSharp/GodotSharp/Core/IO/FileStream.cs) class from that PR if you want.

**Comment by Torguen** [comment]
> You can pass a stream to XmlReader rather than a file path. Right now Godot doesn't provide a stream class for its virtual file system, but that will change once #40775 is merged. You can grab the [FileStream](https://github.com/godotengine/godot/blob/eafb1a2dff95bd1c25231ecb46febdbd1544bc8d/modules/mono/glue/GodotSharp/GodotSharp/Core/IO/FileStream.cs) class from that PR if you want.

I am investigating but I don't know how to create the stream for xmlReader.
Some help?

**Comment by neikeq** [comment]
In my comment I linked the [FileStream](https://github.com/godotengine/godot/blob/eafb1a2dff95bd1c25231ecb46febdbd1544bc8d/modules/mono/glue/GodotSharp/GodotSharp/Core/IO/FileStream.cs) class from my PR which you can copy into your project. You may also need to include [this file](https://github.com/godotengine/godot/blob/eafb1a2dff95bd1c25231ecb46febdbd1544bc8d/modules/mono/glue/GodotSharp/GodotSharp/Core/Extensions/ErrorExtensions.cs).

**Comment by Calinou** [comment]
Closing per the above comments.
