### ISSUE TITLE
Allow to extend Translation class in the script or GDNative

### ISSUE THREAD

**Issue by o01eg** [godotengine/godot-proposals#1926]
### Describe the project you are working on

FreeOrion Godot client, alternative client with Godot UI https://github.com/freeorion/freeorion/pull/3235

### Describe the problem or limitation you are having in your project

We use own internationalization system and want to use already existing system in the Godot project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow `TranslationServer` to call `get_message` of `Translation` object via `Object::call` instead of virtual function call.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Call for the game's i18n code: https://github.com/o01eg/freeorion/blob/43ca1d3d17e8baa946cd03e872293ecd5560c7a8/godot/GodotI18n.cpp#L42

Initialization of internationalization: https://github.com/o01eg/freeorion/blob/43ca1d3d17e8baa946cd03e872293ecd5560c7a8/godot/gdfreeorion.cpp#L196-L201

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The only idea is to generate CSV from the game's translation files which will have to be re-imported each time main translation change.

### Is there a reason why this should be core and not an add-on in the asset library?

Asset library don't have access to translation internals.

**Comment by Calinou** [comment]
> The only idea is to generate CSV from the game's translation files which will have to be re-imported each time main translation change.

You could also convert the existing localization files to [gettext](https://docs.godotengine.org/en/latest/tutorials/i18n/localization_using_gettext.html). These files can then be loaded directly without having to import them.

**Comment by o01eg** [comment]
We don't use `gettext` either.

**Comment by o01eg** [comment]
Also we have plans to implement mods and I'm not sure if it possible to distribute additional translations for Godot.

**Comment by akien-mga** [comment]
Can't you create your own class that extends `Translation` so that you can redefine `get_message()`? It seems to be designed for this:
```
        virtual StringName get_message(const StringName &p_src_text, const StringName &p_context = "") const; //overridable for other implementations
```

**Comment by o01eg** [comment]
`TranslationPO` and `PHashTranslation` are overrided with `virtual` functions but GDNative uses same as GDScript method.

I opened PR for it: godotengine/godot#44670

**Comment by Xrayez** [comment]
> That's how `TranslationPO` and `PHashTranslation` are implemented, you could likely implement your own `TranslationFreeorion` or similar in GDNative that implements all the virtual methods you wish to customize.

Those methods don't seem to be exposed as `virtual` in GDScript, though. And apparently it's required to use `call()` on C++ side so those could call script methods if available anyways.

There's also explicit `get_script_instance()->call()` approach I've seen in Godot code, but apparently `Object::call()` handles script instance calls as well.
