### ISSUE TITLE
Add option to General->Text Editor->Completion to include searches from middle of keywords

### ISSUE THREAD

**Issue by RafalLauterbach** [godotengine/godot-proposals#1928]
### Describe the project you are working on
I'm working on strategy game.
My problem is 100% generic and text-editor related.

### Describe the problem or limitation you are having in your project
I do not remember all keywords/build-in classes and I love using completion to compensate for that.

When I searched for type "InputEventMouseButton" (that name I did not remember) I had big trouble finding it. Writing "Event" / "Mouse" / "MouseEvent" / 'e' and looking through all propositions couldn't get me where I wanted, I had to go to firefox to find this word. Didn't took me long, but sometimes I forget some name that is used way less often and than it's real issue.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
There could be checkbox (default off) in General->Text Editor->Completion tab to search for items "from middle" of target word. 

This could be named "Search for string in whole [target word]" (I don't know how to name [target word], that we search for) and has description "Search for string in whole [target word] instead of searching only in it's beginning (Warning! this option can be heavy on CPU)" 

List of those words would be listed just below suggestions that actually start with this string.

I believe this would be much, much "heavier" than how currently completion works, because searching for text in whole string is heavy compared to searching for it only from the beginning, but that's why it should be optional.

If Godot uses regex to check strings against strings in completion tool, than it should be trivial to implement by twisting formula just a little bit. That's what (in my opinion) justifies adding it even for very limited number of users.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
when I write "Eve", than it could propose me at first words that start with "Eve" (in my version only "event" starts with that letters), but than below that there would be list of words that "contain" this string in the middle of them. Like all InputEvent[....] types, and some other event related names.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I do not know how to edit behavior of completion tool. Otherwise I would propose ready solution.

If it uses regex than perhaps it looks for [searched string]+[any legth string]. After turning this option it would first list those items, but below it would list [string of at least 1 character]*+[searched string]+[any length string]

*(at least 1 char - to avoid duplicating items that are already on top)

### Is there a reason why this should be core and not an add-on in the asset library?
I think it's simple and small enough that it deserves to appear as another handy checkbox in settings.

**Comment by RafalLauterbach** [comment]
! What I found out is godot sometimes do just what I ask about here. It works like that at least on methods and names. I don't know what it works on too... I don't know why it doesn't work on typenames...

**Comment by KoBeWi** [comment]
This is a bug already fixed in 4.0: https://github.com/godotengine/godot/issues/33425

Maybe the fix could be cherrypicked?

**Comment by RafalLauterbach** [comment]
Oh, I didn't mentioned that I'm on version 3.2.1 . Maybe it's already fixed. I care less if that's bug, I was afraid it's totally missing.

I nailed it down a little bit after some testing : it seems like godot do NOT search in the middle IF you start with big letter. In my example
[looking for InputEventMouseButton]
Event(...) won't help me
Mouse(...) won't help me
entMou(...) will propose me what I need and many other stuff.

From my testing it's always the case and I couldn't find any counter-example so maybe it's just designed like that.



So... If you search for keyword that you partially know, do NOT start with big letter. If it's bug - that would be workaround. If it's by design, than it's just tip
