### ISSUE TITLE
Make a crisp shadow rendering effect similar to old classic games

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1930]
### Describe the project you are working on
A Tomb raider game, possibly a web-running motion comic with anaglyph 3D effect :OO . .

### Describe the problem or limitation you are having in your project
I've looked at the shadows in Godot, and they're a bit blurry, since I found it odd, I've been looking at REAL shadows, in real life, for instance at a lamp, and they too are blurry, not sharp . . But, there were some old games, that sort of made ' sharp ' shadows, and it looked amazing . . I really like the pixelated, or vector look, and I was wondering if it was possible to add a setting, so Godot could render shadows realistically, but also like old games, if that makes . .

Here is the effect, or so . . the shadows look blurry, at a distance, but one can see, shadows can also look ' sharp ', sometimes, not sure why, but here . . .

![2020-12-03 0319](https://user-images.githubusercontent.com/61069740/100955207-62ea3180-3516-11eb-8711-b9df12ef90d0.jpg)

I've also looked at real shadows, bec. I really confused me, and most of them, have a sort of blurry edge, when I go for walk, so I know they're better, more PBR, physics accurate, so Godot has an AMAZING shadow engine, as is . . But, there were some old games, that looked more like ' games, 3D ', because they had ' sharp ' shadows, I remember F.E.A.R. 1, a really amazing game, that had this . . I don't know if it's super-complex to code, or simulate, but it'd be amazing to have both options . . And, I think this is my last request, or proposal, as Godot 4 now has all the features, I ever dreamed of, or wanted, in games, etc etc . . So nice, it's just wonderful, what Godot 4 is going towards . . I'll try to keep this short, thanks . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It'd allow me to have really sharp shadows, like in Half-life 1, so many good games, I really liked, from back when, amazing memories, fun . .
![2020-12-03 0323](https://user-images.githubusercontent.com/61069740/100955500-f1f74980-3516-11eb-9d4a-6da074b086c5.png)

However, I don't know if this is super-complex, or how to do it, the default shadows in Godot aren't sharp, even with one DirectionalLight :( :( <3 . .

<img width="960" alt="Skærmbillede (737)" src="https://user-images.githubusercontent.com/61069740/100955734-5b775800-3517-11eb-9303-29f88f39258b.png">

If Godot got that, then I could create any game, I ever dreamed of, or wanted, so cool . . Don't know, if this is more hard-ware intensive, bec. I'm noob, thx . . <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, maybe a toggle somewhere, in project settings, or under the lights, not sure, so shadows look like Half-life image <3 <3 . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I'm not sure, I am not a pro, on 3D rendering, shaders, graphics, I'm mostly a Blender 3D modeller, basic coder, atm . .

### Is there a reason why this should be core and not an add-on in the asset library?
I'm not sure how to get this effect, so I have no idea, where it should be, many older games had it, and they were mind-blowing, to me, and it looked so good, like pixels, vectors, 3D <3 Thx . .

Again, Godot 4 has all my wishes already, but of course, I want more, you know . . If not in Godot 4, maybe Godot 4.2, or later . . Not sure if to ask more features, or simply hope you can finish Godot 4 instead, all my wishes for the engine are in 4.0, so I'm super grateful and, happy, as is . . Outstanding job, superb, can't complain . . Thx <3 . . Now, to keep it short . .

Thank you <3 :D :D . . .

**Comment by Calinou** [comment]
The issue with stencil shadows is that they become very demanding if you have lots of lights. Moreover, it also makes it impossible to follow a proper 3-point lighting system to the shadows always being fully sharp.

**Comment by jasperbrooks79** [comment]
ok, thanks, I didn't know it was actually complex, Godot's lighting system is better, atm . .

also think those old games sort of, cheated, well by having only one light, in the scene, ok it becomes LESS performant than the one there is now, so it's a dead - end, it doesn't scale well, well just really liked the ' look ' of those ' crisp ', pixel shadows, but I have no problem with Godot's current shadow system, ESPECIALLY if it runs faster <3 :O :O . . Thx . . .

**Comment by Calinou** [comment]
Closing due to lack of support. Stencil shadows may be implementable by third parties once the renderer is made more scriptable, but they won't be implemented in core Godot since they aren't relevant for most games anymore
.

**Comment by vect0000r** [comment]
i wonder how difficult it would be to implement frustum-traced shadows in godot? https://cwyman.org/papers/i3d15_ftizb.pdf
