### ISSUE TITLE
Add JavaScript support as official scriptable language out the box

### ISSUE THREAD

**Issue by dmitryuck** [godotengine/godot-proposals#1932]
### Describe the project you are working on
Any Project

### Describe the problem or limitation you are having in your project
To use JavaScript in Godot I need to download/recompile the engine

### Describe the feature/enhancement and how it helps to overcome the problem or limitation
It would be great if JavaScript support came out of the box, this will attract more people to the engine if they know they can
use JavaScript as a Script language (which is very popular)

### Is there a reason why this should be core and not an add-on in the asset library?
Sure. I believe it should be a core part like GDScript is

**Comment by Jummit** [comment]
If the problem is that you have to recompile the engine, maybe prebuilt binaries could be supplied.

**Comment by dmitryuck** [comment]
I can use prebuilds, but is there no difference to use prebuilds or have already working ready support?

Bytheway, there is an issue with downloading prebuild binaries

![Screenshot_2](https://user-images.githubusercontent.com/20966824/101019697-00288280-3576-11eb-8c3f-903aaed06114.png)

**Comment by pycbouh** [comment]
> It would be great if JavaScript support came out of the box, this will attract more people to the engine if they know they can
use JavaScript as a Script language

This can be said about almost any programming language in existence. Which is why instead of picking and choosing Godot provides a platform to use any language that the community is interested in using. The need to recompile the engine in some cases is a small price to pay for the convenience. 

That said, I agree with Jummit, the ECMAScript for Godot project should probably provide precompiled binaries. It's not that hard to set up.

**Comment by dmitryuck** [comment]
> This can be said about almost any programming language in existence.

GDScript, JavaScript, and Lua - truly scripting languages, so might be provided in the core

Other bindings like D, Go, is another story

**Comment by pycbouh** [comment]
Being a scripting language is not that important. Half gamedev world uses C#, some Godot users included. There is also no such thing as "just adding things to the core". Everything that is made core increases the overall maintenance cost. Having more core dependencies means more work to support it with every release. Third party modules can be updated independently.

**Comment by dmitryuck** [comment]
Users who will use the browser version of the engine also limited in available scripting languages

**Comment by Zireael07** [comment]
@dmitryuck: Uh, you know C# *is* in core and even has a contributor devoted almost wholely to it?

**Comment by dmitryuck** [comment]
> @dmitryuck: Uh, you know C# _is_ in core and even has a contributor devoted almost wholely to it?

I didn't know, really appreciate it

**Comment by Calinou** [comment]
As per [this page](https://docs.godotengine.org/en/latest/tutorials/scripting/gdnative/what_is_gdnative.html#supported-languages), there are no plans to support additional languages in core. This can still be done by third parties using C++ modules (which they can provide precompiled editor and export template builds for) and GDNative add-ons.
