### ISSUE TITLE
Support more interpolation options on Gradient

### ISSUE THREAD

**Issue by gongpha** [godotengine/godot-proposals#1933]
### Describe the project you are working on
Some kind of terrain procedural generator
### Describe the problem or limitation you are having in your project
I wrote a shader for use with the OpenSimplex. I used a gradient for visualizing a noise texture (e.g. Water/Sand/Grass/Mountain). And I want to try some little features like the voxel style of noise. This feature needs constant interpolation (aka. Nearest Neighbor) on each point.
### Describe the feature/enhancement and how it helps to overcome the problem or limitation
It helps those who use them for their shaders and other purposes with `GradientTexture`.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add a new enum as `calculation` for the calculation method. And implementing frequently used interpolation like Cubic, Nearest Neighbor
![ภาพ](https://user-images.githubusercontent.com/13400398/101021284-4dbae480-35a2-11eb-8282-d5c378d8b136.png)
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No. If used by official supports. But it possibly can implement in an alternative. Also possibly can do for Nearest Neighbor by using hacky way. Use two points with different colors and drag them closely as possible.
![ภาพ](https://user-images.githubusercontent.com/13400398/101020561-4941fc00-35a1-11eb-89c9-ba04bab30b48.png)
### Is there a reason why this should be core and not an add-on in the asset library?
Because it's the feature for `Gradient` resources

EDIT: `calculation` should be a single enum variable. Not array.

**Comment by Chaosus** [comment]
Fixed by https://github.com/godotengine/godot/pull/53321
