### ISSUE TITLE
Detect coroutines and change highlight color in editor

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot-proposals#194]
Function calls are highlighted in blue by default (as in 3.2 alpha).

When using coroutines (functions that may `yield` a GDScriptFunctionState), the caller must know it's a coroutine and change the caller appropriately, so

`x = foo()`

becomes

`x = yield(foo(),'completed')`

(or `x = await foo()` with [this pull request](https://github.com/godotengine/godot/pull/32034).)

It might be handy to highlight such coroutines with a different color in the editor, so that bugs are easier to find when you change a normal function to a coroutine or vice-versa and forget to change its calls.

I'd make the difference very noticeable, a bold orange for instance. This would've personally saved me a lot of time.

**Comment by Calinou** [comment]
@jabcross Please edit this proposal so it follows the [template](https://github.com/godotengine/godot-proposals/blob/master/.github/ISSUE_TEMPLATE/feature---enhancement-proposal.md).

**Comment by jabcross** [comment]
Not sure if this is still relevant with the Godot 4's new `await`. What do you think, @vnen ?

**Comment by vnen** [comment]
I don't think the highlighting system is smart enough to know if a particular function is a coroutine or not.

But yeah, in Godot 4 you'll actually get an error if you call a coroutine without `await`.

**Comment by Calinou** [comment]
Closing per @vnen's comment, as the 
error makes special highlighting redundant.
