### ISSUE TITLE
Allow depth-writing shaders to work with shadow maps

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-proposals#1942]
### Describe the project you are working on

A node rendering SDF models with raymarching: https://github.com/Zylann/godot_sdf_blender

### Describe the problem or limitation you are having in your project

The node cannot cast shadows, and cannot receive shadows.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In my use case, the node uses a simple geometry primitive (such as a quad, a box, or a sphere). The goal of that primitive is solely to render pixels in a certain location on screen. It might be displaced to be fullscreen (like post-processing effects do by assigning `POSITION`), or only part of the screen when a box is chosen.

But unlike post-processing effects, `DEPTH` is written into, as well as `NORMAL`, `ALBEDO` and other various pixel properties, and `discard` is used to cut out the edges of the model. This allows the result to fit nicely in a scene with regular meshes.
The AABB is also altered to match the real extents of the object.

![image](https://user-images.githubusercontent.com/1311555/101262514-4842d300-3737-11eb-89db-9382609b132d.png)

Because the shader writes to `DEPTH`, it provides the information for shadowmaps to also work on it. Currently that doesn't seem to happen.
I tried using a cube without displacing it and the resulting shadow was following the cube and not the real depths.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Take `DEPTH`-writing shaders into account?
I'm not expert in that area, but from what I understand of shadow maps, they render depth from the point of view of the light, and the result is used by the regular render pass to darken occluded pixels. So it sounds like it should be possible.
If it incurs at the expense of other "classic" shaders, maybe add a `render_mode` to treat the shader differently? Or have a `shadow()` function to allow customizing the shadow pass?

This should ideally not take effect on shaders that actually just do post-processing, because while those displace their quad to be fullscreen, it doesnt mean such quad should put everything in shadow by being right in front of the frustrum. Perhaps it would just work as long as they dont write to `DEPTH`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. Unless you re-implement a shadow mapping system on top of the `VisualServer` API using viewports, it's going to be terribly inefficient, hard to maintain and share as a plugin.

### Is there a reason why this should be core and not an add-on in the asset library?

It targets a part of the rendering engine.

--------
NB: this is an area I only started experimenting, so maybe Godot actually supports this and I got something wrong somewhere. If that's the case this proposal could be closed, but at the moment it's not certain yet ;)

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/1843#issuecomment-727656198.

**Comment by drcd1** [comment]
In 3.2.3-stable (at least), depth-writing shaders already write to shadow maps (and to any depth pre-pass, in general) if they use alpha-cutoff or `discard;`. If understand the code correctly, using any of these means they run the whole fragment shader when doing depth pre-pass (like when rendering shadow maps). They can cast shadows, they just can't receive them.

 I would suggest checking if depth is written to, in rasterizer_scene_gles3.cpp, in the same if statement where `uses_discard` is checked.

For now, a work around would be to just do something like "if(false) discard;" in the shader, to trigger `p_material->shader->spatial.uses_discard` to be true.

Note: there would still be some problems with the shadow maps, with bias or with dual paraboloid maps, but that would require further thought.

See also https://github.com/godotengine/godot-proposals/issues/974#issuecomment-778615284

**Comment by Zylann** [comment]
> depth-writing shaders already write to shadow maps (and to any depth pre-pass, in general) if they use alpha-cutoff or discard;

The shader shown in the screenshot uses `discard` already: https://github.com/Zylann/godot_sdf_blender/blob/master/addons/zylann.sdf_blender/raymarch.shader

**Comment by drcd1** [comment]
That's because SCREEN_UV doesn't work for the shadow passes, I think.
I changed your code (by creating a varying and setting to be the same as VERTEX.xy, and using that instead of SCREEN_UV in fragment) and shadows are cast, but they are not received (at least not in the correct position).
![imagem](https://user-images.githubusercontent.com/22733172/107859555-3023ba00-6e32-11eb-9d12-2f856e6dd553.png)

**Comment by viktor-ferenczi** [comment]
Ran into this issue with a depth writing shader. The resulting (carved out) object receives some shadow, but it corresponds to the original mesh (a cube), not to the 3D surface defined by the DEPTH written by the shader. It drops proper shadow according to its carved out shape. It cannot shadow itself.

It would be nice to have a way to fix the shadows in this case, even at a performance cost.

**Comment by viktor-ferenczi** [comment]
I think the fragment shader would need an extra `inout vec3 WORLD` variable. 

It would default to the world position of the fragment. Fragment shaders setting the DEPTH would also be required to update WORLD accordingly. The light shader would then use the WORLD position for the lighting calculation, which includes any shadow map lookup. It would allow for casting proper shadows. It would provide complete information for the lighting, since the normal is already there and correct.

**Comment by viktor-ferenczi** [comment]
[PR-65307](https://github.com/godotengine/godot/pull/65307)

Implemented the above change and it works perfectly, at least on Windows with Vulkan. Objects with a DEPTH setting fragment shader now receive shadow and even cast correct shadow on themselves. 

I'm aware that it may not be ideal to make VERTEX writable, but it perfectly solves the problem. We may want to introduce an out only variable instead, but it may result in slightly less performant shader code. 

The PR contains a FIXME comment on a performance optimization to my change. I don't know how to make that code block conditional, so it would be added only if the game defined fragment shader actually writes to the VERTEX variable. Could a Godot dev with experience in shader implementation help in this? (10 days ago I did not even know how to write shaders...)

The documentation update will also follow once we agree in a final solution.

**Comment by viktor-ferenczi** [comment]
Thinking a bit further along the lines of this change.

Setting the DEPTH is actually redundant, since all such fragment shaders mush contain the same logic to be consistent:
```
vec4 vertex;
...
VERTEX = vertex.xyz;
vec4 ndc = PROJECTION_MATRIX * vertex;
DEPTH = ndc.z / ndc.w;
```

We could save the last two lines and the headache of understanding non-linear depth by just calculating and setting the depth in Godot's shader code. This way the fragment shaders provided by games would only need to set VERTEX properly, which is simpler and equally good.

This change would allow removing the DEPTH variable completely.

**Comment by viktor-ferenczi** [comment]
[Spin-off proposal](https://github.com/godotengine/godot-proposals/issues/5436)
