### ISSUE TITLE
Make PhysicalBone inherit from RigidBody

### ISSUE THREAD

**Issue by Favkis** [godotengine/godot-proposals#1951]
### Describe the project you are working on
3d ragdoll physics based game

### Describe the problem or limitation you are having in your project
https://docs.godotengine.org/en/3.2/classes/class_physicalbone.html 
PhysicalBone has only 2 methods of manipulation, makes it extremily hard to manipulate, I'm trying to make physical based animations and using only apply force is extremily hard 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Having all methods possible from rigid body type objects would help a lot in making ragdolls more than just flat ragdoll

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Integrate more functions from physics engine 

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Only very hard animation imitation with apply_impulse which sounds like nightmare

### Is there a reason why this should be core and not an add-on in the asset library?
Probably addon, it isn't that important for most games I'd assume so addon would be great too

**Comment by Calinou** [comment]
> Probably addon, it isn't that important for most games I'd assume so addon would be great too

In this case, the godot-proposals repository isn't the right place for this :slightly_smiling_face: 

Feel free to open an issue on the third-party [godot-ideas](https://github.com/godot-extended-libraries/godot-ideas) repository, but remember that there are no obligations from developers.

**Comment by CrezyDud** [comment]
@AndreaCatania said this is not the way to do it, so this should be closed

**Comment by Calinou** [comment]
Closing, see here for rationale: https://github.com/godotengine/godot/pull/58658#issuecomment-1057238794
