### ISSUE TITLE
Influence of Energy parameter from BakedLightmap on illumination of dynamic objects

### ISSUE THREAD

**Issue by dedm0zaj** [godotengine/godot-proposals#1952]
### Describe the project you are working on
I'm making a game with baked light locations. The game has a change of day and night. Godot 3.2.3.

### Describe the problem or limitation you are having in your project
To change the illumination of the baked location, I use the Energy parameter from the BakedLightmap. But this parameter does not affect the baked volumetric light (light mass) and does not affect the illumination of dynamic objects.

![image](https://user-images.githubusercontent.com/75580200/101439223-ad204800-3946-11eb-8182-4580a7d7ed86.png)
![image](https://user-images.githubusercontent.com/75580200/101439250-bb6e6400-3946-11eb-8cff-fd3b00875222.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I suggest adding the effect of the Energy parameter to the volumetric light.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add influence to the volumetric light here (baked_lightmap.cpp):
```
void BakedLightmapData::set_energy(float p_energy) {
	energy = p_energy;
	VS::get_singleton()->lightmap_capture_set_energy(baked_light, energy);
}
```

P.S. In fact, I did not fully understand the code and did not understand in which variable the volumetric light is stored. If you can tell me where the volumetric light is stored in the code, I'll do it myself. I found the "Vector <Cell> bake_cells" variable (voxel_light_baker.h), but I don't understand how it works. And is it the correct variable.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No. These suggestions cannot be circumvented with a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?
This proposal should be included in the core as it is part of the rendering.

**Comment by Calinou** [comment]
@dedm0zaj Feel free to open a pull request for this :slightly_smiling_face: 

You'll have to open the pull request against the `3.2` branch since the `master` branch uses an entirely different lightmapper.

Also, you might want to check out https://github.com/godotengine/godot/pull/40035 which may be merged for 3.2.4.

**Comment by dedm0zaj** [comment]
@Calinou If it works out, I'll definitely post it.
Can you tell me about my question? Under what variable is the volumetric light stored in the code?

**Comment by Calinou** [comment]
> Can you tell me about my question? Under what variable is the volumetric light stored in the code?

I don't know, I've never worked on the lightmapper. @JFonS might be able to answer, but I'm not sure how much he's looked at the old lightmapper code.

**Comment by dedm0zaj** [comment]
@JFonS I still can't find where the volumetric light data is stored. Can you tell me?

**Comment by JFonS** [comment]
@dedm0zaj It is stored as an octree in `BakedLightmapData`, you can check `scene/3d/baked_lightmap.h` and `scene/3d/baked_lightmap.cpp` to find it. This data is then applied in the visual server via `RasterizerStorage::lightmap_capture_set_octree`.

**Comment by dedm0zaj** [comment]
Decision https://github.com/godotengine/godot/pull/44458

**Comment by akien-mga** [comment]
The proposal should be closed if/when the implementation is approved and merged.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/44458.
