### ISSUE TITLE
Rename InputEventX to InputX

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1960]
### Describe the project you are working on
Godot plugins (gdscript)

### Describe the problem or limitation you are having in your project
There are several classes with long names:
`InputEventMouseButton`,
`InputEventMagnifyGesture`
etc.
It's a bit hard to read and pronounce them

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The idea is making them shorter by removing `Event` word.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`InputMouseButton`
`InputMouseMotion`
`InputKey`
looks clearer and still sounds meaningful, isn't it?

### If this enhancement will not be used often, can it be worked around with a few lines of script?
—
API related

### Is there a reason why this should be core and not an add-on in the asset library?
—
API related

**Comment by groud** [comment]
I disagree with this. "Input" is the name of the singleton we use for managing input states. Without the "Event", it makes quite unclear those are events, and might cause confusion with the "Input" singleton.

I believe explicitness is better here.
