### ISSUE TITLE
Deprecate `Node.filename`, replace with something more accurate

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot-proposals#1961]
### Describe the project you are working on

Platformer

### Describe the problem or limitation you are having in your project

https://godotforums.org/discussion/24828/get-resource-path-of-root-scene

I frequently use F6 to run the scene I'm currently viewing, and I wanted my game to be aware of the path of the scene which was loaded, such that I could update one of my autoload singletons with the number of the level I'd loaded up.

It wasn't clear how to do this, hence the above forum post.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As you'll see in the forum post, the path of the scene is available with `Node.filename`. However, I *couldn't find* this in the docs, because I was searching for 'path' / 'resource path' / 'resource URL'.

To me as a Linux user, 'filename' specifically refers to just that - a file's name, not its full path, never mind a fully-qualified `res://` URL.

Additionally, this isn't in line with other GDScript naming. For example, the docs for `preload()` start with:

> `Resource preload(path: String)`
> 
> Returns a `Resource` from the filesystem located at `path`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

* Deprecate `Node.filename`.
* Replace it with something else. I'm not sure what would be best, because `path` by itself conflicts with the notion of a path in the scene tree. Perhaps `resource_path` or `file_path`?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope.

### Is there a reason why this should be core and not an add-on in the asset library?

Modifying `Node` is a pretty major thing anyway.

**Comment by Calinou** [comment]
If we are making this change for 4.0, we can just rename the property entirely since it's OK to break compatibility in that release.

**Comment by MaaaxiKing** [comment]
It would be cool if we had a `filepath` and a `filename` property!

**Comment by Mickeon** [comment]
There it is, shouldn't this proposal be closed?
![image](https://user-images.githubusercontent.com/66727710/185785067-8d5a5b60-681c-4dcb-a482-68ca061766df.png)

**Comment by snoopdouglas** [comment]
Nice! Yeah, that's much clearer.
