### ISSUE TITLE
GDScript normalized vector of length 0==vec(0), docs does not mark this

### ISSUE THREAD

**Issue by danilw** [godotengine/godot-proposals#197]
**Describe the project you are working on:**

GDScript `print(Vector2(0,0).normalized())`==(0, 0)

**Describe the problem or limitation you are having in your project:**

this should be marked somewhere(I think), some software return vector length==1 on normalize vec(0), some other(like nviida drivers) return inf...

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

not waste hours of debugin lots of code

**Comment by clayjohn** [comment]
I am having trouble understanding what this proposal is for. It is looking more like a bug report to me than anything else. However, you haven't stayed what the result is or what the expected result is.

**Comment by danilw** [comment]
sorry
build in godot docs say `normalized()
 Returns the vector scaled to unit length. Equivalent to v / v.length().`
length of vector is 0
exception when length is 0 does not documented

I ask to add to Godot docs, that Godot have build-in exception for that and return vector with length 0 as result

**Comment by Jummit** [comment]
If you can't fill out the issue template, it probably doesn't belong here. Put it on godotengine/godot instead.
