### ISSUE TITLE
Add project timer. 

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#1970]
### Describe the project you are working on

2d platformer

### Describe the problem or limitation you are having in your project

add a timer to each project so user can see how long they have spend working with current project currently it needs to be measured via external timers but it's something that can be easily done. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

timer would allow us better time tracking and break planing. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image856](https://user-images.githubusercontent.com/30668026/101905849-fe7f4000-3baf-11eb-9787-c4fb5d5d4d53.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

not sure I am sure it can be done via extension but I am not sure how.

### Is there a reason why this should be core and not an add-on in the asset library?

It can be add-on but I am not sure how to make it.

**Comment by pycbouh** [comment]
Well, it indeed can be an addon, and I've made one this summer: https://github.com/pycbouh/godot-time-tracker

**Comment by Feniks-Gaming** [comment]
is that available on asset library? I search there couldn't see any

**Comment by pycbouh** [comment]
Yes, https://godotengine.org/asset-library/asset/662

**Comment by Feniks-Gaming** [comment]
Maybe I am stupid but I have installed it like you said and nothing happened how do I start it?

**Comment by Feniks-Gaming** [comment]
Wired that I couldn't see it when I searched. Thanks I will try to figure out how it works and make it work so it starts when project starts and ends on quitting project so I don't have to manually start it otherwise it defeats a object of having one indie the editor rather than starting one when project starts like I did so far.

**Comment by ItsAleph** [comment]
@Feniks-Gaming I'm sorry for bumping such an old issue, but have you found a solution to automatically start timer, and if yes, can you please share it? I (and i'm sure many other people too) would really appreciate that!

**Comment by feidry** [comment]
![image](https://github.com/godotengine/godot-proposals/assets/5678432/d4263e08-080a-44d0-bd6b-c5f727cdccef)
I added this to TrackerDock.gd and it works perfectly. As soon as I click into the Godot window, it starts tracking time. The moment I click away, it stops.
