### ISSUE TITLE
Automatically switch Scene Tree view to Remote when playing the project/scene from the editor

### ISSUE THREAD

**Issue by GGAlanSmithee** [godotengine/godot-proposals#1971]
### Describe the project you are working on
an rpg

### Describe the problem or limitation you are having in your project
I build up my scenes dynamically, so the local scene tree does not give a lot of information when running the game

![image](https://user-images.githubusercontent.com/11805103/101912292-d8629b80-3bc1-11eb-8b16-bbfbbe636178.png)
![image](https://user-images.githubusercontent.com/11805103/101912241-c680f880-3bc1-11eb-9a04-854fc18e83ae.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
automatically (or provide a setting to) change to the "remote" scene tree view upon playing a project/scene (F5/F6)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See images in section above, not much more to explain

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It would be used often by me, and I have no idea how this could be worked around with script. It is ofcourse trivial to manually switch to remote after running the game, but this would be a great quality-of-life change for me atleast. This _is_ somewhat mitigated by the hot-reload behavior of the editor, but that does not always work, so I find myself having to re-play the game quite often

### Is there a reason why this should be core and not an add-on in the asset library?
it is part of the editor, I do not know to what degree a third party extension can affect this

**Comment by Calinou** [comment]
This was specifically disabled because it causes stuttering while the project is running. Since this is a bug, I'll close this.

**Comment by GGAlanSmithee** [comment]
@Calinou thanks for the info, I searched the docs and googled, but apparently not well enough!
