### ISSUE TITLE
Use domain name when hosting servers

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1974]
### Describe the project you are working on
NetworkTest

### Describe the problem or limitation you are having in your project
I want to use a unique domain name when hosting or joining servers

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I was wondering if we could be allowed to specify a domain name when hosting a server..

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
```
	var net = NetworkedMultiplayerENet.new()
	net.create_server_name(port, DEFAULT_SLOTS, "MyUniqueServerName")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not sure.

### Is there a reason why this should be core and not an add-on in the asset library?
Its easier to understand for users then and ip address.

**Comment by Calinou** [comment]
You don't have to specify the domain name when hosting a server. Your server doesn't need to know its domain name. Instead, you specify it when *connecting* to a server (like in every other networked application out there).

Closing, as this is already supported.

**Comment by Shadowblitz16** [comment]
what do you think game server list are then?

**Comment by Calinou** [comment]
> what do you think game server list are then?

Master servers (which power most server lists) typically don't store domain names. They just reference the IP addresses of registered servers. Some of them allow specifying domain names in the server description or even as the server's address field, but this is not common in my experience.
