### ISSUE TITLE
Add a clear button to the item list editor

### ISSUE THREAD

**Issue by Animus-Surge** [godotengine/godot-proposals#1975]
### Describe the project you are working on
I'm working on an RPG, and I had a traits list that I was just going to hard code in all the possible traits that affect certain features of the game into an OptionButton.

### Describe the problem or limitation you are having in your project
I ended up deciding that was a bad idea and not expandable by addons for my game, so I decided to clear out all the itemlists. However, I have to keep clicking the text box of an item, followed by the delete button at the top of the item list editor, and that gets really tedious if you have a whole lot of items for each item list.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think there should be a clear button in the item list editor so you can quickly remove every item for an OptionButton or similar. Maybe even a dialogue confirming that you would like to do that so it's idiot proof.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![concept](https://user-images.githubusercontent.com/22083792/101957986-7bbaad00-3bd0-11eb-93a5-8ae8d24615c9.png)

I just copy-pasted the delete icon to the clear button, but you can definitely change that.

I didn't mess with code, I just did a little bit of image editing to get that

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I'm not sure, I guess you could write a tool script or something, but I have zero experience with them. You could also just... delete the OptionButton or something, but I feel like adding this would be pretty useful so you don't have to keep deleting/re-adding the OptionButton if you keep changing things.

### Is there a reason why this should be core and not an add-on in the asset library?
It's one button, and I feel that it could be quite useful

**Comment by Calinou** [comment]
To distinguish the "clear" option from "delete", I'd rename them to "delete all" and "delete" respectively.

Also, we don't need to offer a confirmation if this operation is undoable (which it should be).

**Comment by Animus-Surge** [comment]
I like that naming schemem better, feel like it suits the engine a little. And yeah, should definitely be undoable, making the dialogue redundant
