### ISSUE TITLE
Allow visibility notifiers to be disabled

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1978]
### Describe the problem or limitation you are having in your project
Unlike all other nodes, visibility notifiers provides no means at all for disabling them.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
when an object is removed, e.g. you shoot it and it removes itself, the visibility notifier events still fire so you get an additional signal raised even though you have probably already queued it for deletion, or you may do more code inside visibility notifier that is no longer required.

The usual use-case for the signal is it has left the visible screen, not freed in code.

Because of this you have to provide workarounds by creating 'dead' flags, or whatever, to avoid the problem.

The only solution involves, as far as I can tell, disconnecting the signal. Inside the object it might not know the stringed method name, object and function name, and even if so, this is a really clunky way of stopping the notifier.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Provide a disable() method, nice and simple.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, everything is a hack and disconnecting the signal is not optimal or sometimes with dynamic objects, not always possible.

### Is there a reason why this should be core and not an add-on in the asset library?
Disabling a node from being active is pretty much basic core functionality.

**Comment by Calinou** [comment]
This should now be handled by https://github.com/godotengine/godot-proposals/issues/1835 being implemented in `master`, closing.

In `3.x`, you can use the "dead" flag approach as you mentioned. This proposal hasn't received much (if any) support judging by reactions on OP, so it may not be worth opening a pull request on `3.x` that implements a `disabled` property on VisibilityNotifier.
