### ISSUE TITLE
Support --no-window on linux

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-proposals#198]
**Describe the project you are working on:**

Any godot project.

**Describe the problem or limitation you are having in your project:**

I use an external editor and would like to be alerted of syntax errors from within my editor. There is an [open PR](https://github.com/dense-analysis/ale/pull/2642) to add a script checking functionality to ALE, which works by invoking `godot-server --check-only -s $script`.

The issue is that it requires the godot server as the godot editor will pop up a window even if you pass `--check-only -s`. This means you have to install another separate binary just for linting.

There is a `--no-window` flag, but it only supports Windows.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

If `--no-window` worked on linux, it would make it easier to check scripts from the CLI, which is useful for both editor integration and CI/CD.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

```
$ godot --no-window --check-only -s my_script.gd
... errors/warnings here, but no GUI is spawned
```

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Not as far as I'm aware.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It is supported in core for Windows. It seems weird to have it be built in for one platform but an add-on for a different platform.

**Comment by Calinou** [comment]
While I agree with the proposal, you could likely use an headless binary to achieve this.

**Comment by Xrayez** [comment]
Somewhat similar use case but from the opposite side: see [this snippet](https://github.com/Xrayez/godot-testbed/blob/09aa674553c33a587fd1724ae02cf25c86b71667/.travis.yml#L79-L82) I've written for CI testing of Godot Engine with GUT. In there you have to treat `--no-window` option separately as it's not available for the server build (not needed), but I think it would be just better if it's ignored for the server build, and of course be implemented for other platforms.

**Comment by Jummit** [comment]
Isn't this more of a bug? I would expect command line arguments working on all platforms.

**Comment by rcorre** [comment]
Since it is documented in --help that the flag only works for Windows, I wasn't sure if it qualified as a bug.

On November 3, 2019 3:25:22 PM EST, Jummit <notifications@github.com> wrote:
>Isn't this more of a bug? I would expect command line arguments working
>on all platforms.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/godotengine/godot-proposals/issues/198#issuecomment-549174911

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by akien-mga** [comment]
See also #991.

**Comment by rcorre** [comment]
Closing in favor of #991. I think the two motivations for this are:

1. Local script linting
2. Automated checks in CI

The former is now solved by the languageserver, and for the latter you can just install the server/headless build in CI.
