### ISSUE TITLE
Add a Flow Layout Container

### ISSUE THREAD

**Issue by Tyrannosaurus1234** [godotengine/godot-proposals#1980]
### Describe the project you are working on
Frontend for video game database

### Describe the problem or limitation you are having in your project
Listing tags in a space-efficient manner is tricky due to the variable length of tags combined with the lack of a conventional "flow" layout commonly used for such purposes, ex: 
![Flow Layout](https://files.catbox.moe/3mbln5.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
A container, similar to a `GridContainer`, where elements wrap to the row below only if they wouldn't fit on the current row, similar to word wrapping in a `RichTextLabel`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add a FlowContainer node -> set its `rect_size` property to the dimensions you wish to constrain your list of elements to -> optionally set V/H separation settings -> add elements as children to the FlowContainer node -> node positions its children automatically, with respect to their `rect_min_size` property.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes.

### Is there a reason why this should be core and not an add-on in the asset library?
It's one of the more common and useful UI layout types; while it may not be the most common thing to see in games specifically, it's very common in web & software (particularly mobile, where horizontal space is at a premium and you have to make the most of what you have).

**Comment by Calinou** [comment]
> ### If this enhancement will not be used often, can it be worked around with a few lines of script?
>
> Yes.

In this case, it's not suited for the proposal workflow, but rather as an add-on :slightly_smiling_face:

**Comment by Zylann** [comment]
I implemented a (modest) one for a part of my plugin: https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/tools/texture_editor/flow_container.gd

**Comment by bonbonmiel** [comment]
There is an addon for this already: https://godotengine.org/asset-library/asset/779

**Comment by me2beats** [comment]
I think it would be useful and convenient to have this container in core, since it is one of the basic types of containers.

It is commonly used and found in many UI frameworks.

And given the small amount of code, maintaining it would not have caused much difficulty.
