### ISSUE TITLE
add texturepacker's polygon packing algorithm support

### ISSUE THREAD

**Issue by denghe** [godotengine/godot-proposals#1981]
### Describe the project you are working on
2d sprite animation game

### Describe the problem or limitation you are having in your project
texture / pixel fill rate issue

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
support texturepacker "Polygon" algorithm,  map to Mesh2D array ?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![image](https://user-images.githubusercontent.com/3364637/102011374-93379880-3d7e-11eb-9f20-51cdf21c3c97.png)
![image](https://user-images.githubusercontent.com/3364637/102011386-a64a6880-3d7e-11eb-9c00-c7ed7c7bd798.png)
![image](https://user-images.githubusercontent.com/3364637/102011421-e4478c80-3d7e-11eb-85c4-9f91a89c49fe.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
N/A

### Is there a reason why this should be core and not an add-on in the asset library?
enhance 2d phone device performance

**Comment by Calinou** [comment]
Godot can already create polygons from sprites since 3.2. Select a Sprite node and click the **Sprite** menu at the top of the 2D viewport:

![image](https://user-images.githubusercontent.com/180032/102014906-bb140580-3d58-11eb-95bb-52ca36677ac9.png)
