### ISSUE TITLE
Make the loop option a property of the AnimationPlayer and not of the animations

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot-proposals#1982]
### Describe the project you are working on
A 2D Platformer.

### Describe the problem or limitation you are having in your project
As described in the https://github.com/godotengine/godot/issues/44357, the AnimationPlayer animation looping option in an instantiated editable child is not independent from it's parent or other instantiated children.

This happens because the Animation Looping property should be part of the AnimationPlayer itself and not of the animation file and enabled independently for each animation.

The loop option is kept inside the animation file.:

![loop-issue](https://user-images.githubusercontent.com/25422687/102039002-75325e00-3da7-11eb-8fc9-a4fb45638245.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
To be independent of other objects, **the loop option in the AnimationPlayer for each animation should work in the same way as the autoplay property which is not part of the animation file, but of the AnimationPlayer**. 

Removing the property loop from the animations and placing it as one of the AnimationPlayer itself should fix the fact that editable children could change the value of the loop in their parents.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
At the moment the property loop is inside the animation. So instead of the engine look for the loop property in the animation file, this should be done in the AnimationPlayer itself, in the same way that autoplay property works.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No. If you try to use an instantiate child and change the loop option it will change the loop option in the parent too what will change from the other children as well. 

### Is there a reason why this should be core and not an add-on in the asset library?
Because there is no workaround for this problem.

**Comment by AttackButton** [comment]
Every animation needs to have its own loop option, but how to unlink the loop of an instantiated child from its parent or other object that use the same animation file?

**Comment by mrjustaguy** [comment]
Haven't used the Animation stuff a lot myself yet, but I can totally see this as an improvement to have looping as the AP's property vs the animation itself, as it's easier to control & manipulate the AP at runtime vs the actual animation.

**Comment by Zireael07** [comment]
Counterargument - I can easily imagine having two animations, one of them looping and one not, in the same animplayer...

**Comment by mrjustaguy** [comment]
True... I'll have to look into the animations a bit when I have time, to see how difficult it is to loop/unloop an actual animation (both editor and runtime) compared to what it'd take to do so if AP was the one setting the looping in order to provide better feedback.

**Comment by Calinou** [comment]
> Counterargument - I can easily imagine having two animations, one of them looping and one not, in the same animplayer...

For instance, you could have a "run", "jump" and "die" animations. Only the first one should be looped, not the last two.

**Comment by AttackButton** [comment]
> Counterargument - I can easily imagine having two animations, one of them looping and one not, in the same animplayer...

True. That's a workaround. I was concerned about the fact that an editable child could change an option directly in the parent AnimationPlayer.


> For instance, you could have "run", "jump" and "die" animations for a player model. Only the first one should be looped, not the last two.

But I'm talking about the unit_offset property from the PathFollow2D that this single animation could be used for multiple objects like moving platforms, statues and doors as well. So for some editable children in the level design I could choose if it could loop or not.
