### ISSUE TITLE
Add support for "empty" translations

### ISSUE THREAD

**Issue by GoDino** [godotengine/godot-proposals#1985]
### Describe the project you are working on
international multigame project where rules and standards vary depending on the market/locale

### Describe the problem or limitation you are having in your project

default translation behaviour is
"Key found" - display current language translation
"Key not found" - display fallback language translation

so far so good, however when the current language translation does not have content, as can easily happen when a certain phrase must be omitted in a certain language or a certain rule does not apply there so it is left out. That is impossible with the current behaviour.
we have this behaviour:
"Key found, but string is empty" - try to find key in fallback language
"Key found in fallback language" - display fallback language translation

In our opinion there is an unreasonable assumption here in that just because a translation is empty, it is also nonexistent.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Differentiation should exist between an empty translation and a nonexistent translation:
"Key found, but string is empty" - display nothing
"Key not found for language" - try to find key in fallback language (current behaviour)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the differentiation would look like this:

"Key found, but string is empty" (no fallback, display nothing):
```
# csv
keys,en,de
KEY1,"Good Morning","Guten Morgen"
KEY2,"Good Evening",""

# en.po
msgid "KEY1"
msgstr "Good Morning"

msgid "KEY2"
msgstr "Good Evening"

# de.po
msgid "KEY1"
msgstr "Guten Morgen"

msgid "KEY2"
msgstr ""
```

"Key not found for language" (fallback, display english text)
```
# csv
keys,en,de
KEY1,"Good Morning","Guten Morgen"
KEY2,"Good Evening",

# en.po
msgid "KEY1"
msgstr "Good Morning"

msgid "KEY2"
msgstr "Good Evening"

# de.po
msgid "KEY1"
msgstr "Guten Morgen"

```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

it should be default behaviour

**Comment by pycbouh** [comment]
With PO I don't think it would be possible at all, because that's how PO was designed. By design you are not supposed to use keys with PO, but original (English) phrases instead. And thus the automatic fallback in case there is no translation.

You can work around it by using keys with some strict format that has zero chance to collide with genuine phrases within your application. And then make a wrapper in your code that will check if the returned value matches the key passed to the function, and if so, returns an empty string instead.

**Comment by GoDino** [comment]
Thank you. The reason we decided to use keys was that sometimes a larger text (multiple lines of) is translated, like a description of a game or feature. It seems to slow performance compared to using short unique keys.

I am not sure this is by design. Looking through the gettext specification I did not really find much about this special case except that C# differentiates between an empty and a nonexistent translation. Might just be opinion as to how this is handeled.

How would your workaround work for Keys appearing in Labels etc.?

For completeness, here is an example:

(contains a modified godot binary with the described new behaviour)

[translations.zip](https://github.com/godotengine/godot-proposals/files/5696485/translations.zip)

The "game" contains two languages, english and german. It has a title, "Test Game" and a description of a feature that does not exist for the german market and needs to be omitted there. There is no way of doing that currently. With the described modification it is easily done.

- load project "translation"
- to have it fall back to english (standard behaviour), one could simply remove "KEY2" from the german .po file. As far as I understand, missing entries are perfectly legal for gettext.

- when using .csv, fallback is achieved by removing the double quotes of the german translation, so it is "null" and not an empty string.

**Comment by pycbouh** [comment]
> I am not sure this is by design.

But it is. The whole idea behind PO format and `gettext` is to cover your whole project with methods that can seamlessly replace untranslated English strings with localized strings. You take `print("My message")` and wrap it like so `print(_("My message"))`, where `_()` is a method that is fetching localized messages for your current locale. It is expected that a string, any string, will always be returned by this method, and the execution of the program will not be interrupted and the output will be generated. As such, `msgid` is always the original message, and I can guarantee you that all proper implementations of this system will return you `msgid` as is if the translation for this message is empty.

> How would your workaround work for Keys appearing in Labels etc.?

By not relying on Godot's automatic translations. You would need to make a globally accessible function and handle translations for labels and such in your script. Same as you can do now with [`tr()`](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-tr), but with your own method that would handle your special case.

**Comment by GoDino** [comment]
Thanks for clarifying. I will check this out.

**Comment by GoDino** [comment]
I tried working around the issue in script, however what I am trying to have is control on a key/value level wheter to use fallback or not, so I cannot get this behaviour:

Translation resource contains the key but no value ("") -> do not fall back (see use case)
Translation resource does not contain the key -> fall back to fallback language

If I call TranslationServer.translate or tr(), I always get the automatic fallback in both cases.

Translation.get_message() already checks for the existence of a translation but returns an empty string if so. Therefore TranslationServer treats missing translations and empty strings the same and falls back.

If there was a "has_message" function, this could be checked.

I understand that this might not be gettext conform, but why would someone create a translation for a language and leave it empty other than having the intent that it is not to be translated in that language and neither "fall-backed"? I should have the freedom to do so without software judging that because it is empty, it must perforce be replaced with english. It should do that only if no translation was found at all. Or at least provide a way around it.

Also, I can just insert a single space " " and get exactly what I want (no fallback, the translation is just now a whitespace character). And I could then remove it in my wrapper function. Not a nice workaround though. So if whitespace is an acceptable translation, why not an empty string?

**Comment by pycbouh** [comment]
> So if whitespace is an acceptable translation, why not an empty string?

Because that's the difference between no value and some value. From the looks of it, you may want to make your own implementation of translation resources. `TranslationServer` is not that complicated to reimplement or at least wrap to use your specific logic. The only benefit of it is the magic of automatic translation for labels and stuff, but it's not crucial, IMO.

For example, there is no `TranslationServer` in for the Godot Editor and plugins, and when I was experimenting with it, I was able to replace it for my plugin with a simple dictionary of locales. Not sure if we need to change the engine here, because this seems to be completely implementable in the user-land.

Though I agree, PO/gettext philosophy does not necessarily map well on gamedev domain.

**Comment by GoDino** [comment]
you are right, it is more of a rarely used case though we often encounter it. Will implement it locally.
