### ISSUE TITLE
Add lower-level access to the AStar class

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot-proposals#1988]
### Describe the project you are working on
2D RTS game path finding

### Describe the problem or limitation you are having in your project

I have tried to write a path finding system where i can move around multiple units.
First i tried it with the navigation2d node, but it wasn't suited for what i wanted to do, so i tried with astar2D.
In astar, you can query for an id that gives you the closest available position to a specific position.
When moving multiple units around, it would be necessary to make all the units aware of each others position, or block the position that that unit occupies so that other units can get a path around that.
But in the astar class, you can disable individual points, and only get a specific point with an id, if you use a position to look for a point in the astar algorithm you get a close point, not necessarily the exact point, thus it becomes dificult to block the unit from other units.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

it would be very helpfull if we had more functions to work with in the astar algorithm, such as access to the underlying arrays, a way to get the exact point with position instead of id, and maybe enhancments that will allow for pathfinding of multiple units at once.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

im not experienced enough with coding or algorithms

### If this enhancement will not be used often, can it be worked around with a few lines of script?

i dont think this is doable with a few lines of script

### Is there a reason why this should be core and not an add-on in the asset library?

path finding is a core component of most games

extra:

![Screenshot from 2020-12-15 21-26-48](https://user-images.githubusercontent.com/59711483/102269199-98324e80-3f1c-11eb-87ea-1aca01a73e79.png)

as you can see, the function that returns a point doesnt give an exact location, thus i cant block the units precise postion so that other units can avoid it

**Comment by Calinou** [comment]
@barbaros83 Did you find a workaround for this? For future readers, it would be helpful to add some context on why you closed the proposal.
