### ISSUE TITLE
Rename "empty" function to "is_empty" on Array and Dictionary in GDScript

### ISSUE THREAD

**Issue by masmartyg** [godotengine/godot-proposals#1989]
### Describe the project you are working on
Generic projects

### Describe the problem or limitation you are having in your project
Spent some hours debugging my project trying to figure out why my array wasn't "emptying". I am not fluent in English and I used the "empty" function found in autocomplete instead of "clear" thinking it would empty the array. My fault, I should have read the documentation! 😇 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Renaming the "empty" function to "is_empty" would help to understand the purpose of the function on the fly and avoid misunderstandings

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
🤔 

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes, using the correct "clear" function 😄 

### Is there a reason why this should be core and not an add-on in the asset library?
🤔

**Comment by Jummit** [comment]
godotengine/godot#16863
