### ISSUE TITLE
Add a `placeholder` property to TextEdit (like LineEdit already has)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#1995]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

TextEdit can't have placeholder text. Placeholder text can be used to improve UX to hint what should be entered in a field:

![Text fields with placeholders](https://user-images.githubusercontent.com/180032/102356336-5e5d5880-3fad-11eb-8e62-e2cd776375dc.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow TextEdit to have placeholder text, just like LineEdit already supports.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a `placeholder` property that is displayed as translucent text if the TextEdit is empty. Translate it automatically as well.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Drawing a placeholder for TextEdit might be feasible using custom drawing or even a Label node as a child of the TextEdit, but it requires more than a few lines of script. Also, we'll need this in the editor in many places (https://github.com/godotengine/godot/issues/44413).

### Is there a reason why this should be core and not an add-on in the asset library?

This is core GUI system functionality.

**Comment by Paulb23** [comment]
Related PR #36830

**Comment by waotzi** [comment]
this would be very useful :+1:

**Comment by Calinou** [comment]
@waotzi Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by andrea-calligaris** [comment]
Just came across this right now.
Rather surprised not to find the parameter.
