### ISSUE TITLE
Allow change UI focus continuously by holding navigation key

### ISSUE THREAD

**Issue by univeous** [godotengine/godot-proposals#1997]
### Describe the project you are working on
A JRPG game
### Describe the problem or limitation you are having in your project
For now, If I want to change UI focus in game, I need to press and release the UI navigation key. I think it's very unnatural.

I have a backpack system in my game, and if I want to check items in my backpack, I need to press and release up and down a lot of times. 

I checked recent games and software in my steam library, They are [Tales of Maj'Eyal](https://store.steampowered.com/app/259680/Tales_of_MajEyal/), [DARK SOULS III](https://store.steampowered.com/app/374320/DARK_SOULS_III/), [Aseprite](https://store.steampowered.com/app/431730/Aseprite/), and the most recently, The [Godot](https://store.steampowered.com/app/404790/Godot_Engine/) Editor itself, They all can change UI focus continuously by holding the navigation key. But in games made by Godot, by default they can't. 

Maybe I'm wrong, but I did some research and I think they are hard-coded in the engine.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think we can add an option in project settings to allow change UI focus continuously by holding the navigation key.

By default, it's disabled, so game will work as before(I personally think it should be enabled by default though):

![image](https://user-images.githubusercontent.com/40604180/102461058-cf227480-4082-11eb-8ec1-e2d68effb466.png)

![ftqMlL9Dlw](https://user-images.githubusercontent.com/40604180/102461373-3e986400-4083-11eb-8027-b90e259e725f.gif)

If it's enabled then we can change UI focus continuously by holding the navigation key:

![image](https://user-images.githubusercontent.com/40604180/102461185-042ec700-4083-11eb-9cdc-4aef27c7ce7f.png)

![nAKWXeiieE](https://user-images.githubusercontent.com/40604180/102461387-422beb00-4083-11eb-8c1d-e30fdcecdfd5.gif)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I did something like this and I think it works well:

https://github.com/univeous/godot/blob/6bddcee049ac65eb5c169eb6337255a94bacda03/scene/main/viewport.cpp#L2381-L2421

I don't know if it will cause any side effects though.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't think so.
### Is there a reason why this should be core and not an add-on in the asset library?
It's very hard to create an add-on to implement this.

**Comment by Calinou** [comment]
If this is a common UI pattern, this doesn't need to be made optional by a project setting.

**Comment by univeous** [comment]
> If this is a common UI pattern, this doesn't need to be made optional by a project setting. Just make sure not to break analog gamepad focus (IIRC, it was broken before Godot 3.2).
> 
> Note that gamepads don't send echo events, which means this will still need to be done manually for people navigating menus with a gamepad (both with the D-pad and an analog stick).

I tried with my Xbox controller, and it works as usual. It shouldn't break gamepad focus, because what I did is basically just change the 'is_action_just_pressed' to 'is_action_pressed'. But my implement has a little problem, I will fix them soon.

So shall we make the UI work like this? I will make a pull request then.

**Comment by Calinou** [comment]
> So shall we make the UI work like this? I will make a pull request then.

Sure :slightly_smiling_face:

**Comment by univeous** [comment]
Here is the [pull request](https://github.com/godotengine/godot/pull/44456) about this.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/44456.
