### ISSUE TITLE
Improvement for Tileset Editor

### ISSUE THREAD

**Issue by rakun99** [godotengine/godot-proposals#2]
I have a nice idea for tilemaps. Usually, if you want to create a huge field of tiles, you press shift+ctrl, then press left button of mouse and pull the mouse. You press a right button to clear fields of tiles. But that's not convenient, when setting, for example, tunnels in these fields of tiles. And these fields are always squared.

So I propose an option, to make a huge field of tiles by one click. Just like working with brushes and pencils in image redactor. You twiddle the mouse, and half-transparent field of tiles follow it. These fields of tiles can be squared or circular. You can change the number of tiles in these fields. Tile in each cell, or tile across one cell. You click and set tiles in one place, then press Shift and click in another place, and line of tiles of same thickness stretches from one place to another etc. I think, it would greatly automatize process

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
