### ISSUE TITLE
Add Screencast Keys feature

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot-proposals#20]
Screencast Keys is a feature that would show all keystrokes (including modifiers) as text in the editor GUI. This assists developers and educators by helping those watching follow along with what hotkeys, shortcuts, etc. are being pressed to perform the actions happening on screen.

This would help grow Godot by making tutorials easier to produce, as well as helping with developers who are Pair Programming as part of a team, either in-person or remotely.

The text should be easy to read and stay out of the way as to not make the work harder to follow instead of easier.

A similar feature is available in Blender, and is very common (and quite useful) for tutorial videos.

Thanks

**Comment by Juankz** [comment]
I see this more as an addon than something that should go integrated in the engine.

**Comment by Janders1800** [comment]
I don't think its really necessary.
99% of Blender tutorials don't use Screencast Keys, and the ones that do, use a OS dependent stand alone program just for that.

**Comment by Calinou** [comment]
I'll close this due to lack of support, per the above comments.
