### ISSUE TITLE
Tweak the editor CheckButton appearance to clarify what's the "on" state

### ISSUE THREAD

**Issue by 01271** [godotengine/godot-proposals#2002]
### Describe the project you are working on
Making a top-down racing game.
### Describe the problem or limitation you are having in your project
The Godot UI is unclear at-a-glance when it comes to on/off switches.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
![image](https://user-images.githubusercontent.com/3951049/102706802-e5c6f800-4249-11eb-816c-462a36416d0d.png)
![image](https://user-images.githubusercontent.com/3951049/102706827-13ac3c80-424a-11eb-9fb2-abf168ad0bcc.png)

This is an on/off toggle. It is unclear if this is ON or OFF.
On certain programs toggles "fade out" when they are inactive. On others they go dark when inactive. It is therefore difficult to tell whether this is ON or OFF.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I would like the graphic changed to be clearer. The new graphic would need to be clear in all languages so it would be great to use colour instead of words.
The IOS toggle button is a great example.
![image](https://user-images.githubusercontent.com/3951049/102706856-5ec64f80-424a-11eb-8d43-7d2c62f80ef2.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It will be used often. We see it all the time.

### Is there a reason why this should be core and not an add-on in the asset library?
The core experience should be as clear as possible.

**Comment by Calinou** [comment]
I'd like to implement this, but there are two blockers right now:

- CheckButton doesn't have modulate theme items for its *icon* when the CheckButton is pressed. We need this to change the CheckButton's color depending on the editor theme's accent color (which is blue by default, but can be changed).
- CheckButton needs to be able to draw an "underlay" that we can modulate without modulating the white dot displayed on top.

Using an hardcoded blue color is an option too, but it won't look as pretty for those using a non-default editor theme.
