### ISSUE TITLE
Improve comment toggle behaviour 

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot-proposals#2005]
Not sure if this is new feature or fits more of the bugfix but here I go.

### Describe the project you are working on
bunch of solo projects, irrelevant

### Describe the problem or limitation you are having in your project
I have issue with behavior of comment toggle in script editor - it only uncomments code if very first sign of the line is comment sign, however I often comment lines manually putting # after indentation and in such case untoggle does not work. This gif from current 4.0 branch demonstrates it:

![gif_comment_toggle_old](https://user-images.githubusercontent.com/9964886/102724258-a44c5080-430e-11eb-9324-ed92972b62c0.gif)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose to alter behavior of comment toggle a bit:
- when there is no selection and comment token is first non white sign on line with cursor untoggle line by removig #
- when there is selection treat line with indented comment as regural commended line, so if all lines in selection are commented uncomment them, if at least one is not commented then comment them all - this means that line with indented # will get another # at beginning which ensures that if you toggle big block of code with comment in the middle it will not mess up comment.

Gifs below showcase new mechanics. 

![gif_comment_toggle_fixed](https://user-images.githubusercontent.com/9964886/102724561-b929e380-4310-11eb-811e-a75b4849a25b.gif)

There is some another multiline example

![comment_toggle_new_multiline](https://user-images.githubusercontent.com/9964886/102725527-a7980a00-4317-11eb-803b-3be2d6a6c30c.gif)

### Describe how
Some changes in code_editor logic. Proposed PR:  https://github.com/godotengine/godot/pull/44557

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Workaround is to simply remove comment manually but it kind of kills the point of the toggle. With proposed changes comment toggle should be a bit more "smart" and work as in most IDEs (for instance Jetbrains products).

### Is there a reason why this should be core and not an add-on in the asset library?
It's editor feature

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/110.

**Comment by Paulb23** [comment]
closing in favour of #110
