### ISSUE TITLE
GUI styles should draw focus behind text

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#2012]
### Describe the project you are working on
Win32 theme

### Describe the problem or limitation you are having in your project
Godot's themes just isn't flexible enough to recreate it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Render focus style under text and have separate text colors for each state instead.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![image](https://user-images.githubusercontent.com/2453707/102946671-2acf7200-4476-11eb-9524-447ed003fd7c.png)
the button on the far left can't be emulated in godot

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It would be used end of story and no

### Is there a reason why this should be core and not an add-on in the asset library?
Godot's theming system is severally limited and devs don't seem to think so.

**Comment by Shadowblitz16** [comment]
directly related https://github.com/godotengine/godot-proposals/issues/2011

**Comment by Calinou** [comment]
I don't see how you need the focus style to be drawn behind text to recreate the button on the left. The outline isn't placed over the text on the screenshot.

Likewise, web browsers also draw focus styles over any text if it overlaps.

**Comment by Shadowblitz16** [comment]
@Calinou the screen shot is from a win32 app not a godot one.

Godot seems to place the focus style over the text which is redundant due to the fact you can literally just set the text color. 

Note that its not possible to do this in godot due to the fact the focus style covers up the text and there is no alternative without redrawing the text again.

Its literally more flexible this way then what it is now

**Comment by Calinou** [comment]
Closing, as the current behavior is the most accessible one – a focus outline should *never* be obstructed by anything. There are very few cases in which you *need* the focus outline to be drawn behind text, so I don't think it's warranted to have this in core.

If you need more advanced behavior, it may be possible to [manually draw custom controls](https://docs.godotengine.org/en/stable/tutorials/2d/custom_drawing_in_2d.html) where you can choose the order in which individual styleboxes and texts are drawn.
