### ISSUE TITLE
Improve readability of Dictionaries in the inspector

### ISSUE THREAD

**Issue by haaldor** [godotengine/godot-proposals#2018]
### Describe the project you are working on:
Generic 2D platformer player controller.

### Describe the problem or limitation you are having in your project
Using dictionaries for creating categories in exported variables.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It's few small propositions of Quality of Life changes - it doesn't necessarily change functionality, but is more visual help.
As (as far as I know) we can't make categories in inspector, using dictionaries would help us work around this issue.
Moreover, I believe using dictionary for settings makes code much clearer.
Small changes that would help readability of dictionary in Inspector:

- Option to remove possibility to add new keys to dictionary and change type of existing values in inspector. Could be accomplished by simply not showing the following:
![image](https://user-images.githubusercontent.com/18580752/103081697-be20b880-45d8-11eb-831d-50e3eb4fccae.png)
![image](https://user-images.githubusercontent.com/18580752/103082752-2375a900-45db-11eb-97f3-3bba608d3f6d.png)

- Option to show String keys without quotes (by using option in project, creating dictionary with only String keys or by any other way). It helps readability.
- If dictionary contains dictionary, the "inside" dictionary could be shifted slightly to the right to show which options are "inside". On following example, keys in red rectangles should be shifted to the right:
![image](https://user-images.githubusercontent.com/18580752/103081990-69317200-45d9-11eb-9b8e-12efa5179daf.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Sadly I don't know GDscript engine from it's inside point of view, so I don't know what way of implementing this would be easiest/best.
In Script probably it would look something  like:
export const myDictionary = {
   "key": value,
   "insideDict": {
      "insideKey": value
   }
}

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not really, as those are Quality of Life improvements. Possibly could create categories instead, but in this case we can't use one dictionary for settings, which is the target here.

### Is there a reason why this should be core and not an add-on in the asset library?
Right now dictionaries are so unreadable in the inspector, that they aren't useful. Making them as readable as other variables would make it consistent.

**Comment by Calinou** [comment]
> Option to show String keys without quotes (by using option in project, creating dictionary with only String keys or by any other way). It helps readability.

Shouldn't we show quotes in string keys only if they can be confused with other types (such as `false` and `true`)?

**Comment by Shadowblitz16** [comment]
The whole inspector is very hard to ready when it comes to any sort of nested data.
I honestly don't see any readability improvements though.

**Comment by hilfazer** [comment]
I'd like that pencil button to be narrower - more horizontal space.

**Comment by Calinou** [comment]
@hilfazer I think it's better to keep the same margin to all buttons to make them easy enough to click. We'd have to introduce dedicated button styles that have a lower margin just for those edit buttons, and it'd make them difficult to click (especially on a touch screen).

**Comment by don-tnowe** [comment]
Nested collection view could be improved in another way. Look at Resources, they already have a [colored border that shifts hue based on nesting level!](https://github.com/godotengine/godot/pull/45907) Offset is a nice tiny bonus.

Though readability isn't my biggest gripe with Inspector collections. I rarely use them because the editing process is clumsy.
