### ISSUE TITLE
Inspector should have an option to fix/lock the transform values

### ISSUE THREAD

**Issue by chexmo** [godotengine/godot-proposals#202]
Short: 
I was working on a 2d platformer when i realized how easy is for a Godot user to move those nodes they don't want to be moved (same happens with sizing and rotation). 
Maybe, adding a lock button for certain properties in the inspector tab should be all we need.

Long:
In general, if the user isn't looking what node is selected in the tree of Scene tab every time he moves something, he could move the wrong node. (same happens when scaling or rotating) 
This seems not like a big problem, but AFAIK there are not specific nodes for certain porpouses, like grouping some nodes using x designer criteria. (The way I see users do something like that nowadays is creating a Node2D and adding those nodes wanted to be gouped as its child, and coding the wanted functions if needed)
So, here is my point: These nodes that are never though to be moved, are still abled to move/size/rotate it with common editor tools like the pointer. Moving some nodes may produce an unnexpected modification to the scene.

**Comment by willnationsdev** [comment]
I'm pretty sure there is already a button you can press to lock the transform of an individual node in the Scene dock or in the viewport toolbar. I recall there being an icon in the Scene dock that marks whether a node can't be moved or rotated, etc.

**Comment by Calinou** [comment]
@chexmo See @willnationsdev's reply above. As of Godot 3.2, locking and grouping is supported in both 2D and 3D. Does this fulfill your proposal? :slightly_smiling_face:

**Comment by chexmo** [comment]
I guess it's enogh for me. Thanks for replying.
