### ISSUE TITLE
GDNative: View custom docs from the editor.

### ISSUE THREAD

**Issue by LennyPhoenix** [godotengine/godot-proposals#2028]
### Describe the project you are working on
A Discord Game SDK wrapper for Godot, written in C using nativescript.

### Describe the problem or limitation you are having in your project
Although, nativescript 1.1 gives us the ability to set class, method, signal and property documentation via `nativescript_1_1_api->godot_nativescript_set_X_documentation`, there is no way to view these docs other than calling `CLASSNAME.get_X_documentation()` in GDScript.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow the built-in script editor to display these custom-defined docs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Here is a mockup using the [GDNative example from the docs](https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-c-example.html)

Docs definition from C:
```c
    godot_string string;

    api->godot_string_new(&string);
    api->godot_string_parse_utf8(&string, "<My class docs>");
    nativescript_1_1_api->godot_nativescript_set_class_documentation(p_handle, "Simple", string);
    api->godot_string_destroy(&string);

    api->godot_string_new(&string);
    api->godot_string_parse_utf8(&string, "<My method docs>");
    nativescript_1_1_api->godot_nativescript_set_method_documentation(p_handle, "Simple", "get_data", string);
    api->godot_string_destroy(&string);
```

Mockup of the docs in the editor: (Made in GIMP)
![mockup](https://user-images.githubusercontent.com/57148878/103155867-45b62500-479b-11eb-9b92-a62ba414a635.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not that I know of.

### Is there a reason why this should be core and not an add-on in the asset library?
There is no way the add-on can interact with this as far as I know, that is the point of this proposal.

**Comment by jonbonazza** [comment]
I think a better proposal would be a way of creating and displaying custom.documentation in general, regardless of the specific scripting language.

**Comment by LennyPhoenix** [comment]
@jonbonazza I agree, I thought GDNative needs it more specifically as you can't just look at the source code (and therefore function prototypes) of a compiled library, making it harder to tell what everything does without external documentation. Maybe for GDScript, docstrings could be displayed for the class's documentation, I'm not sure about VisualScript or Mono/C# though

**Comment by Calinou** [comment]
> I think a better proposal would be a way of creating and displaying custom.documentation in general, regardless of the specific scripting language.

This is already supported for GDScript: https://github.com/godotengine/godot/pull/41095

**Comment by jonbonazza** [comment]
Hmm seems like the gdscript implentation in that pr is specific to gdscript. Bummer. I was hoping there could be some language agnostic mechanism to support this feature. 

Oh well, if that's the case then yea, i guess this proposal makes sense being gdnative-specific.

**Comment by aaronfranke** [comment]
Thank you for this proposal! I'm closing this as a duplicate, in favor of proposal #8245.
