### ISSUE TITLE
Search and filter input map actions in project settings

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot-proposals#203]
**Describe the project you are working on:**
Godot Engine prosperity.

**Describe the problem or limitation you are having in your project:**
There's no way to easily search and organize input map actions via dialog. You have to type and guess what possible actions you might have in your project in order to search for them:

![input_map_search](https://user-images.githubusercontent.com/17108460/68142883-f5498b80-ff38-11e9-9a1d-a5b93d188523.png)

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Adding a search button or simply combining the process of searching and adding actions into the same interface so that the list is automatically updated:

![input_map_search_box](https://user-images.githubusercontent.com/17108460/68143218-afd98e00-ff39-11e9-941a-09f01acaaa6c.png)

**Describe implementation detail for your proposal (in code), if possible:**
Add ability to filter out actions by typing text in the input field intended for adding new actions, either for instant feedback or a way to search for similar actions. The filtering behavior is already present in the `General` tab, for instance.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The actions can be renamed in `project.godot` via external code editor but the way they are stored are not that user-friendly:
```ini
[input]

jump={
"deadzone": 0.5,
"events": [ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":false,"meta":false,"command":false,"pressed":false,"scancode":16777221,"unicode":0,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":false,"meta":false,"command":false,"pressed":false,"scancode":32,"unicode":0,"echo":false,"script":null)
 ]
}
```

**Is there a reason why this should be core and not an add-on in the asset library?:**
Already part of the editor, needs minor enhancement.

**Comment by Calinou** [comment]
Another related improvement would be to visually differentiate the built-in actions (e.g. different color and a tooltip that explains why they can't be removed).

**Comment by GammaGames** [comment]
I think making the "add" input behave like a filter would be really nice. It feels like the input map interface could use some work in general. There's a ton of wasted horizontal space and the tree doesn't really seem like it has a purpose. The only perk I can think of is that you can see when a bind is already set to another action, but there could be a message on the bind popup when an action is bound to another action instead.

I think some vertical menu to select, add, and filter actions with a panel to edit properties of the action might be easier to manage. I realize it should probably be a different proposal, but I already made a mockup:
![Screen record from 2020-02-19 20 32 19](https://user-images.githubusercontent.com/7832163/74898373-f3280300-5356-11ea-9274-5496e7884d5a.gif)
[jsfiddle](https://jsfiddle.net/v76ckqLp/)

**Comment by Calinou** [comment]
I think we should just port the search field available in the General tab to the Input Map tab. I'm not sure about making the filter field an hybrid "search and filter" field, as it may be confusing.
