### ISSUE TITLE
Support cdot and minus in text

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#2035]
### Describe the project you are working on
Tycoon Game
### Describe the problem or limitation you are having in your project
Showing a decrease of a value with a − (minus sign) in the text of a Label does not work.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Cdots and minus signs should be visible. 
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
One would see a minus or cdot instead of nothing.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
It is not worth an add-on and easy to implement.

**Comment by SIsilicon** [comment]
I can confirm that this doesn't seem to work. It's very strange considering that the editor interface can render those characters just fine, but not the user defined labels, line edits, etc...
![image](https://user-images.githubusercontent.com/34734122/103181101-2e466d00-486b-11eb-9296-0d5c3b2945f2.png)

**Comment by jonbonazza** [comment]
This could be considered a bug. I'll leave it up to @Calinou to determine, but definitely seems that way to me.

**Comment by KoBeWi** [comment]
This is a limitation of the default font. − is a unicode character, which the default game font doesn't support. You can fix this by adding a font with unicode support to your controls.

See #1079
