### ISSUE TITLE
Allow implementing and loading custom PCK file formats

### ISSUE THREAD

**Issue by Isolemma** [godotengine/godot-proposals#2036]
### Describe the project you are working on

A 2D game.

### Describe the problem or limitation you are having in your project

The PCK file contains plain texts and easily extractable resources.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Provide interfaces to process data before writing/after reading the PCK file, so that the file format is essentially customized.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I find that the PCK file format is only read in PackedSourcePCK::try_open_pack, but is written in two places: EditorExportPlatform::save_pack and PCKPacker::flush.

If the two writing routines are unified, then it's easy to add pre/post-processing interfaces.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

It's easy to implement and has no real performance impact.

**Comment by Calinou** [comment]
PCK encryption is supported since Godot 3.2.3, [Compiling with PCK encryption key](https://docs.godotengine.org/en/latest/development/compiling/compiling_with_script_encryption_key.html) and https://github.com/godotengine/godot/pull/38308.

As for allowing custom PCK formats, see https://github.com/godotengine/godot-proposals/issues/186 which was rejected.

**Comment by Calinou** [comment]
Closing due to lack of support. PCK encryption was also implemented in https://github.com/godotengine/godot/pull/38308, making the need for custom archive formats less useful. (I
f you really want to use a custom archive format, you can use a custom build of Godot to do so.)
