### ISSUE TITLE
Hide the 3D selection box when View Gizmos is disabled in the 3D editor viewport

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2044]
*Continuing discussion from https://github.com/godotengine/godot/issues/44779.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

The 3D selection box can get in the way when you want to preview 3D materials. This has always been an issue, but it became more noticeable with the [new 3D selection box appearance](https://github.com/godotengine/godot/pull/40106) that was merged in the `master` and `3.2` branches (for 3.2.4).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to *temporarily* hide the 3D selection box while still having something selected (so you can edit it).

Now that https://github.com/godotengine/godot/pull/44782 is merged, it's easy to hide the 3D selection box *permanently*, but this is rarely desired.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

One way to temporarily hide the 3D selection box would be to make it obey the **View Gizmos** setting which can be toggled in the 3D viewport's **Perspective** menu.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core editor functionality.

**Comment by fracteed** [comment]
@Calinou thanks for adding this proposal! As mentioned in the other thread, I think that hiding the whole transform gizmo (selection box and arrows/rings/scale cubes) should occur when the View Gizmos option is disabled.

Would also be great to be able to individually toggle this transform gizmo visibility via the View>gizmos selection list. If possible it should use the ctrl/tilda hotkey combo that Blender uses for the same function.
