### ISSUE TITLE
Add optional `translation_name` argument to `tr()`

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#2046]
### Disclaimer
I am not sure how impactful this request would be, since I'm not sure exactly whether our localization setup is common, nor how performance heavy translation is. If this addition would be more effort than it is worth, feel free to ignore the request.

### Describe the project you are working on
Project with localization

### Describe the problem or limitation you are having in your project
We decided to split up our `.translation files` in multiple, categorized sheets. That way it would be easier for us to organize translation keys, and handle possibly outsourcing translation/community translation. So we have a separate CSV sheet for 'resources', for 'ui_localization', for 'buildings', for 'tutorials' etc. That way we give each key some context as well, which might aid translation.

![image](https://user-images.githubusercontent.com/10502115/103284964-07a84380-49dd-11eb-9c05-91f03d328faf.png)

Due to that setup, it often happens that I already know which of the files needs to be checked to handle a certain translation. After all, any `tr()` of a string in `resource.gd` will never handle anything to do with buildings or tutorials, only with resources. So it would (to my expectation), be more optimized to be able to indicate this when using the tr() function, to avoid having to check through ALL files.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Being able to specify which file should be checked, would likely be more efficient. Especially as more files, and more keys get added over the course of development.

_As a small, (very!) niche, benefit, it could also help avoid with taking translations from the wrong file, if there are duplicate words/keys that need to be translated differently. 'logs' in resources will have a different translation to 'logs' in the settings menu. One refers to parts of a tree, while the other might refer to chat-logs. Specifying a specific file to take a translation from can avoid this issue._

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add an _optional_ argument to the `tr()` function. A string that can be added to indicate the filename of the translation, for example "resources" to **only** check translations in the file `resources.currentlocale.translation`.

![image](https://user-images.githubusercontent.com/10502115/103284670-1fcb9300-49dc-11eb-8f67-a7a94429d70b.png)
_The translation function with an optional argument. "resources" makes sure only a specific translation file is accessed to look for a translation_

I am not sure what the best syntax for the argument would be. `translation_name` or `translation_filename` would be descriptive, but they are also a bit long.

Lastly this request obviously overlooks the automatic translations done on `labels` throughout the project. Being able to indicate the same on those would be just as useful, but for the sake of this request I am keeping this at the `tr()` function only, since that seems less of a stretch.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
As said above, I'm not sure if this is a common setup for translation files. Neither am I sure whether adding such an argument would cause enough of an optimization, to make it worth the effort.

### Is there a reason why this should be core and not an add-on in the asset library?
Core: modification of a core function

**Comment by Omicron666** [comment]
this is simply solved by making your keys naming context dependent
like prefixing them, like "resources_logs", "R:logs", "r.logs"

translation server is probably optimized for constant time querying strings
by convention, you may want do that be default, especially if you feel you are likely to create colliding names for different context
this will also avoid cluttering your own code from additionnal logic

**Comment by Arecher** [comment]
> this is simply solved by making your keys naming context dependent
> like prefixing them, like "resources_logs", "R:logs", "r.logs"

I presume you are talking about this quote from my original post: 
>As a small, (very!) niche, benefit, it could also help avoid with taking translations from the wrong file, if there are duplicate words/keys that need to be translated differently.

Which is why I mentioned it was a fairly niche benefit. Most of the time, like you said, the keys should be different, and this issue shouldn't arise at all.

-------------------------------------

> translation server is probably optimized for constant time querying strings

I would presume it's optimized as well. However, I don't see how being extra specific in these cases could be less optimized.

**Comment by Calinou** [comment]
@Arecher Have you experienced translation lookups being a performance bottleneck in your project? If not, this seems like premature optimization to me.

**Comment by Calinou** [comment]
Closing, as support for translation contexts was implemented in 4.0. Performance is unlikely to be an issue when using OptimizedTranslation (PHashTranslation in `3.x`).

**Comment by inhalt120g** [comment]
I'm dealing with the same situation like the OP. Apparently I'm supposed to use "context", but how exactly? Help just says "add context".
https://docs.godotengine.org/en/latest/tutorials/i18n/internationalizing_games.html#translation-contexts

From that short paragraph it is not clear what are those "Actions" or "Distance" strings that defines this "context" thingy? I have tried typing in all kinds of stuff there for my project and no matter what I do the TranslationServer simply grabs the first (or the last, I forgot) translation key it finds and goes with it.

**Comment by AThousandShips** [comment]
For support questions and help please turn to the other [community channels](https://godotengine.org/community), this is for proposals, not a help desk. This proposal was closed years ago
