### ISSUE TITLE
Add numpad 0,2,4,6,8,9 to viewport camera options

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot-proposals#2051]
### Describe the project you are working on
Any 3D game

### Describe the problem or limitation you are having in your project
The ability to quickly view objects from all sides like in Blender

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Godot already has implemented the keys 1, 3, 5, 7 like they function in blender, but these only allow me to view the scene from the front, top and right and switching between orthographic/perspective. I'd like to have some more options for easier navigation just like they are in Blender.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
It should work exactly like in Blender, just like the 1, 3, 5 & 7 keys that already have been implemented. 2, 4, 6, 8 to spin around in the directions of the arrows on the keys, 9 to swap the view to the other side (which I _think_ is a 180 degree spin around the camera's local up axis), 0 to toggle camera view on and off (which should be the camera set to current). Even more ideal would be to also toggle it when the current camera is in a child scene.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Doesn't make a lot of sense to write a script for something that's already partially implemented.

### Is there a reason why this should be core and not an add-on in the asset library?
It improves an existing editor feature.

**Comment by Calinou** [comment]
This was already suggested in https://github.com/godotengine/godot-proposals/issues/1215, but I'll leave this proposal open since it's separate enough.

**Comment by robbertzzz** [comment]
> This was already suggested in https://github.com/godotengine/godot-proposals/issues/1215, but I'll leave this proposal open since it's separate enough.

I saw that, but didn't see these things being mentioned there

**Comment by Calinou** [comment]
Note that this proposal has been implemented in https://github.com/godotengine/godot-proposals/issues/1215, but no pull request has been opened yet.

**Comment by rcorre** [comment]
I could PR this feature separate from the rest of #1215 if that would be easier to review.

**Comment by Calinou** [comment]
> I could PR this feature separate from the rest of #1215 if that would be easier to review.

I think it's better to PR them separately if possible, so go ahead :slightly_smiling_face:
