### ISSUE TITLE
Allow drag-and-dropping or selecting multiple resources into an exported Array of resources

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#2056]
### Describe the project you are working on
Game project

### Describe the problem or limitation you are having in your project
I have been using exported arrays to be able to reference multiple (audio) resources in specific nodes. While adding the resources to the node, I need to select each individual resource and drag them to the array index. This requires a lot of dragging back and forth, and should also be possible in a single multi-selection drag, but Godot currently doesn't allow this.

![arrayissue3](https://user-images.githubusercontent.com/10502115/103422112-11c66f80-4ba0-11eb-991c-4be1e253e09f.gif)
_Each resource needs to be dragged individually. Godot does not accept multiple files, even if they are all of the correct type._

Therefore I suggest that **exported arrays will accept multiple resources in one go**, if multiple resources are selected, and automatically place them on empty indexes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Whenever a user has selected multiple resources, and drags them on top of an array that can accept this resource type, it should accept and add ALL selected resources. The resources should be added in order, with the top resource in the filesystem getting added first, and all other resources getting added in subsequent **empty** indexes below it.

![multi-addarray2](https://user-images.githubusercontent.com/10502115/103421581-6b796a80-4b9d-11eb-9948-19a5c72d52ee.gif)

That would really make working with exported arrays & resources a LOT more convenient and quick.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Now there are obviously some things to discuss regarding this request. (so please do so!)

1. Should indexes be overwritten, if they are already filled?
2. Do arrays automatically increase their size to make sure there are enough (empty) indexes to add all the selected resources?
3. Should dragging multiple resources onto index 3 mean that resources only get added from index 3 onward?
*For example, while dragging 3 files onto index 3 of an array of size 7 (fully empty), should the files be added on Index 0,1,2 or Index 3,4,5*
4. Should this also work on Dictionaries?
5. What happens if the selection includes one or more files that are not accepted by the array?

If some of these depend on the situation too much, bit might even be worth adding a dialog after dragging multiple files onto an array, which would allow the user perfect control over whether the array increases size, whether it overrides indexes, etc.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It can be worked around by selecting each individual resource and dragging it in. Not the worst thing in the world, but it could drastically be sped up.

### Is there a reason why this should be core and not an add-on in the asset library?
Core: Expands usability of exported Array UI.

Thank you everyone in the Godot Community, and a Happy New Year! 🎉

**Comment by EricEzaM** [comment]
Already done...

https://github.com/godotengine/godot/pull/37965

You should try the master branch before writing up proposals.

**Comment by Zireael07** [comment]
> You should try the master branch before writing up proposals. 

Master branch is still very unstable AND Vulkan-only AFAIU, so people without Vulkan capability can't try it yet.

**Comment by Arecher** [comment]
> Already done...
> 
> [godotengine/godot#37965](https://github.com/godotengine/godot/pull/37965)

Oh great, thank you! That's reassuring to see, and pretty much the implementation as I would have wanted it.

Having said that, I think checking the current stable build and checking for duplicate proposals (yours didn't show up because it was already closed), is more than enough to request a proposal. At the worst I wasted some of my own time, and the proposal gets closed.  Godot could use **more** people giving feedback and opening proposals, rather than less.

**Comment by Calinou** [comment]
Closing per @EricEzaM's comment.
