### ISSUE TITLE
Allow the Terminal Window to be opend and closed without closing the Editor.

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#206]
**Describe the project you are working on:**
This applies to every project I've ever worked on and ever will.

**Describe the problem or limitation you are having in your project:**
When I'm debugging, I'm switching between the Terminal window and the Editor window a lot and constantly close the Terminal window, which also also closes Godot Editor and therefore my project without any warning.
Other times I don't use the Terminal Window at all for longer stretches because the output panel within the Editor is sufficient. Then the Terminal window is an annoyance because it clogs up the Taskbar, especially when having multiple Godot projects open at the same time. Because the Terminal and the editor also uses the same icon it becomes a memory game which taskbar item is the Editor that I want to switch to, and which is is the Terminal, I often don't want to switch to and seems just to be there to annoy me and clutter my workspace.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Being able to decide if I want a Terminal Window would allow my workspace to be less cluttered, to be less irritated which tab to switch to because if I needed only one tab, there would be only one tab to go to. And less often close the Editor unintentionally when my muscle memory presses the X to close a window I don't want to have open.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Imagine a screenshot of the Editor without the Terminal Window in the background.

**Describe implementation detail for your proposal (in code), if possible:**
I cannot.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I would not know how.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I believe a setting like this can only be done through the core, but please correct me if I'm wrong.

**Comment by Calinou** [comment]
This is due to Windows limitations. Godot is built as a console application (when debugging is enabled), so it always shows a command prompt when starting it. However, you can make it hide instantly on startup by checking **Editor > Interface > Hide Console Window** in the Editor Settings. (You can also toggle the command prompt display using **Editor > Toggle System Console**.)

**Comment by golddotasksquestions** [comment]
Ah, I see, these settings are not in the 3.1 stable build. Found them in 3.2. Thanks!
