### ISSUE TITLE
Add way to detect system dark mode in GDScript

### ISSUE THREAD

**Issue by sosasees** [godotengine/godot-proposals#2062]
### Describe the project you are working on

A game whiches visual style is suited perfectly for both Light Mode and Dark Mode. All that's needed is a color swap,
and both modes look equally natural.

### Describe the problem or limitation you are having in your project

I must assume wether most players will use Light Mode or Dark Mode and then set that as the default for my game, instead of letting the game read the system setting to be sure. Additionally, I must make the game's Dark/Light setting separate from the system's.

This is acceptable for OSs without a system-wide dark mode toggle. But by today, most OSs Do have such a toggle.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

With a way to read the system setting for Dark/Light mode, I can use this value as a condition for wether to change to Light visuals or Dark visuals. This would mean that I can set the system setting as a Default, with the visuals still changing accordingly when the system setting changes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'd expect the light/dark mode detection to be codable approximately like this in GDScript:
```
if OS.is_dark_theme():
    theme_dark()  # custom local method
else:
    theme_light() # custom local method
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know of a way to do so,
even after I searched.

### Is there a reason why this should be core and not an add-on in the asset library?

Something like `OS.dark_mode` being an add-on would be totally unexpected. But this could be alleviated by stating it in the documentation page for OS, in a way where you'd find it by [Ctrl][F] searching the term "dark".

But I still think it should be Core because if "Trivial line of code features like this being Add-Ons only" pile up,
installing All these Add-Ons every time you install Godot will become really annoying really fast.

**Comment by Calinou** [comment]
Labeling as `topic:porting`, as the implementation is OS-specific.

I was thinking about opening a proposal for this a few days ago, since the editor will also benefit from it.

**Comment by Sosasees** [comment]
I was just thinking that
The documentation should definitely state that you (the developer) should take into account that for OSs that don't have a Dark Theme toggle, the value will be `null`.

**Comment by Calinou** [comment]
> The documentation should definitely state that you (the developer) should take into account that for OSs that don't have a Dark Theme toggle, the value will be null.

Instead of using a boolean, we should use an enum that can be `THEME_DARK`, `THEME_LIGHT` or `THEME_NO_PREFERENCE`. This is how it's done in the CSS `prefers-color-scheme` media query.

**Comment by Sosasees** [comment]
That sounds much better to me,
because then No developer who uses Godot will miss that they need to take into account users who don't have a system-wide Dark mode toggle.

This is my updated example code:
```
if OS.get_theme(THEME_DARK) or OS.get_theme(THEME_NO_PREFERENCE):
    theme_dark() # local custom method
elif OS.get_theme(THEME_LIGHT):
    theme_light() # local custom method
```

**Comment by Windvis** [comment]
I use the "auto" mode on macOS which uses a light theme during the day (I work in a bright environment 😅) and a dark theme at night. It would be nice if the Godot editor could match the system setting as well without manually having to switch between two themes. Would that require a separate proposal or can that be part of this one?

**Comment by Calinou** [comment]
> It would be nice if the Godot editor could match the system setting as well without manually having to switch between two themes. Would that require a separate proposal or can that be part of this one?

There's already a proposal tracking this: https://github.com/godotengine/godot-proposals/issues/5678

**Comment by Windvis** [comment]
Ah, sorry about that, should have searched better. Thanks!

**Comment by Joseph-DiGiovanni** [comment]
I know this is an old post but I just wanted to share for anyone who ends up here looking for a solution:

DisplayServer.is_dark_mode_supported()
DisplayServer.is_dark_mode()

**Comment by AThousandShips** [comment]
Closing as implemented in:
* https://github.com/godotengine/godot/pull/65026

This proposal was overlooked
