### ISSUE TITLE
Make a node so one can write text on a skewed 3D surface . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2064]
### Describe the project you are working on
A Tomb raider, exploration game, or so . .

### Describe the problem or limitation you are having in your project
Okay, this is tough . . I have some 2D UI elements, that look like ' 3D objects ', and I really need to be able to print text on them . . Here's an example . .
![2021-01-03 1503](https://user-images.githubusercontent.com/61069740/103480506-1f186f80-4dd5-11eb-8321-d8c9a2ec88a2.jpg)

I can make them, as a 3D object, and place it in front of the screen, or the camera . . But, that will mean that all the text has to be written into images, and be difficult to edit later, and having the text in var string, is a lot cooler . . I don't know if this is difficult to make, but I was hoping it was possible to have something like this, where one can place the four points, on a 2D element, and then the text gets ' projected ' on the surface, from strings, instead of having 2000 images, that have to be re-made, to fix any errors in the text, later, so on . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, just a new Node 2D, that one can 'write' text on, and where one can create perspective, by moving the four corners, so the text is ' written ' on that, or so . . maybe it's really a 3D node, but I want my UI to be pixel perfect, and hope it COULD be a 2D node, Thanks . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
So, one can place each corner, so one can get this effect . .
![2021-01-03 1503](https://user-images.githubusercontent.com/61069740/103480669-d9a87200-4dd5-11eb-89f9-1a1b865d1b8d.jpg)

That's all . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It can made in 3D, by making each image in Blender, with text on it, but later editing becomes a problem, fixing grammar errors, or 'bad' dialogue, etc . . Especially important, since my game is text heavy, lots of dialogue, etc . . . Thanks . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, not sure, I think it's missing, that's all . . But, maybe it should be an add-on, don't really know, sorry . . .

**Comment by volzhs** [comment]
are you looking for this?
https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d

**Comment by Zireael07** [comment]
To add to what @volzhs said, you can use Labels in those viewports, not just sprites/images. So there's no problem to have text in your gui in 3d, in fact I do it lots of times in my projects :)

**Comment by Calinou** [comment]
In 2D, this can also be achieved using a custom shader or the Skew properties in 4.0.

**Comment by Zireael07** [comment]
Do we have a label for proposals that are essentially 'improve docs to make certain things clearer'? That's like the fourth or fifth proposal for things that are already offered by Godot but are a bit obscure to newcomers...

**Comment by Calinou** [comment]
> Do we have a label for proposals that are essentially 'improve docs to make certain things clearer'?

Use the [godot-docs](https://github.com/godotengine/godot-docs) issue tracker for that :slightly_smiling_face: 

That said, I think the 3D use case is already well-covered by the GUI in 3D demo. As for the "skew shader" thing, it would be better served by an add-on.

**Comment by clayjohn** [comment]
I think a demo using decals to display text on 3D surfaces would be helpful. Its one thing to display text on a quad using a ViewportTexture and its another thing to add bits of text dynamically to regular objects like in the image in the original post.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/3219.
