### ISSUE TITLE
Allow mouse input in Editor Settings -> Shortcuts.

### ISSUE THREAD

**Issue by Syraleaf** [godotengine/godot-proposals#2065]
### Describe the project you are working on
A multiplayer city builder.

### Describe the problem or limitation you are having in your project
I often wish to quickly tab between two scripts. Godot has the shortcut called "History Next" and "History Previous" for this and they are very useful. I wish to use the side buttons on my mouse to trigger this instead of keys.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
By allowing mouse input I'd be able to go back and forth by pressing the extra buttons on my mouse. This feels like a more natural way for me to work.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I'd like the editor shortcuts to be closer to the "Input Map" under project settings. The Input Map allows for mouse input.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I have no clue if this would be used often. I suspect it depends heavily on how the person in question codes! I suspect hardcore coders will prefer the keyboard approach. 
I have no clue how the editor settings are set up and therefore don't know if it would take more than a few lines to solve this issue :(

### Is there a reason why this should be core and not an add-on in the asset library?
It would bring the editor settings more in line with the input map used in project settings. (Once again, I'm not sure if they're very different under the hood)

**Comment by EricEzaM** [comment]
Duplicate

https://github.com/godotengine/godot/issues/38326

FYI reduz is against this change currently due to fundamental differences bwteen how KB and Mouse input is handled.

**Comment by Syraleaf** [comment]
Thank you for the reply. RIP my dreams of quickly swapping between them :(

**Comment by Calinou** [comment]
> I often wish to quickly tab between two scripts. Godot has the shortcut called "History Next" and "History Previous" for this and they are very useful. I wish to use the side buttons on my mouse to trigger this instead of keys.

This is already covered by https://github.com/godotengine/godot-proposals/issues/954.
