### ISSUE TITLE
C#: add generic version of Node.FindNode()

### ISSUE THREAD

**Issue by felixscheffer** [godotengine/godot-proposals#2066]
Right now, there is only:

`Node FindNode(string mask, bool recursive = true, bool owned = true);`

Ideally, there would also be a generic version like there is for GetChild() and GetNode().
`T FindNode<T>(string mask, bool recursive = true, bool owned = true) where T : class;`

**Godot version:**
3.2

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
