### ISSUE TITLE
Reload project.godot when it changes outside of Godot (Especially with VCS)

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#2067]
### Describe the project you are working on
Multiple projects that use git.

### Describe the problem or limitation you are having in your project
1) Ask a friend to change project.godot (Such as adding to Input Map)
2) Tell them to push their changes
3) Pull their changes while the Godot Editor is open
4) Notice that Godot just reverted your friend's changes in project.godot

Example:

Before:
![image](https://user-images.githubusercontent.com/14253836/103529615-97ba1300-4e4b-11eb-9612-22066b3af974.png)

After:
![image](https://user-images.githubusercontent.com/14253836/103529604-91c43200-4e4b-11eb-9ee3-d9766c9df823.png)

https://youtu.be/TdfiONsTZOg

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Godot should listen for edits of project.godot and reload it as needed.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Make the editor watch for changes in project.godot

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, since this is an editor issue

### Is there a reason why this should be core and not an add-on in the asset library?
Project.godot is part of core

**Comment by Calinou** [comment]
This is actually a bug: https://github.com/godotengine/godot/issues/20250
