### ISSUE TITLE
Implement container conversion functions

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot-proposals#207]
**Describe the project you are working on:**
General engine feature development:
https://github.com/godotengine/godot/pull/26213

**Describe the problem or limitation you are having in your project:**
Using `List<T>` is the common thing in Godot as it uses only the memory required by the elements it contains but exposing to GDscript requires using `Vector<T>` or `PoolVector<T>`.
That implies a lot of repeated code around the engine codebase to convert between those types. 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Having methods/functions to implement that conversion will save some lines of code and prevent some potential copypaste bugs.

**Describe implementation detail for your proposal (in code), if possible:**
Maybe we could have a Vector::to_list(), List::to_vector(), PoolVector::to_vector() and PoolVector::to_list().

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is for internal use in the engine only.

**Comment by YuriSizov** [comment]
There doesn't seem to be any support or activity on this one for a few years now, so I'll close it. But feel free to drop the idea by in the #core channel of the contributors chat. Shouldn't be too hard to implement, and the time is ripe for container changes with all the work on HashMap/HashSet.
