### ISSUE TITLE
Enable "Add Type Hints" in the script editor completion by default

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-proposals#2073]
### Describe the problem or limitation you are having in your project
Autocomplete creates "low quality" code by default

### Describe the feature / enhancement and how it helps to overcome the problem
I was writing a ticket to suggest autocomplete includes types, but then discovered it already exists! (Completion>Add Type Hints). But for some reason it's not default.

I'd like to strongly suggest the default be to include types. It produces better and more readable code. If devs start seeing them they may also get into the good habit of using them themself.

**Comment by Calinou** [comment]
Type hints are not enabled by default because we don't consider GDScript to be a "statically typed by default" language.

Dynamic typing is still considered easier to learn for newcomers and is faster for prototyping.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on the first post).
