### ISSUE TITLE
Geometry Shader - for subd of dyn mesh

### ISSUE THREAD

**Issue by JeffGillin** [godotengine/godot-proposals#2075]
### Describe the project you are working on

Any game with lots of dynamic mesh generation. 

### Describe the problem or limitation you are having in your project.

Subdivision of dynamic mesh (subdivision would be too slow if cpu bound).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Geometry shaders to subd a mesh within shader instead of godot code

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Another shader function named "geometry()" that would allow you to add/remove mesh data.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Could probably be worked around with gpu compute, but then dealing with 2 passes to gpu (one to compute subd, and one to render). Geometry shader wouldn't require second call.

### Is there a reason why this should be core and not an add-on in the asset library?

Yeah, part of the shader language ...

**Comment by fire** [comment]
The game graphics industry consensus is that you create tessellation using compute shaders and not tessellation stages and definitely not geometry. I can go into more detail. Its related to the fact you can not create new geometry.

**Comment by SIsilicon** [comment]
@fire Please go into more detail. I'd like to know more.

**Comment by fire** [comment]
Have to do things but here is a article. http://www.joshbarczak.com/blog/?p=667

**Comment by clayjohn** [comment]
Most GPUs offload the geometry shader stage to the CPU which creates huge CPU and bandwidth bottlenecks on anything but the simplest demo projects. For that reason, we have decided in the past not to add support for them.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/784.

**Comment by Chaosus** [comment]
There was even the implementation by me https://github.com/godotengine/godot/pull/28237. If you really need them you can rebase this PR and recompile the engine. 

This proposal has no way to realize. @reduz said the points of why:

- Geometry shaders are being deprecated in modern API versions. They are inefficient and can be better replaced with Compute.
- Geometry shaders are not well supported in modern hardware. They remain there for compatibility but they are not very efficient.
- Godot uses OpenGL ES 3.0, which does not support them, so they won't work on mobile.
- There is not high demand for the feature.

**Comment by Calinou** [comment]
Closing, as geometry shaders will not be implemented in 4.0 or later given they are not present in Vulkan. See also https://github.com/godotengine/godot-proposals/issues/2075#issuecomment-754753446.
