### ISSUE TITLE
macOS Big Sur Icon 

### ISSUE THREAD

**Issue by ViktorEvil** [godotengine/godot-proposals#2077]
### Describe the project you are working on
any project.

### Describe the problem or limitation you are having in your project
no problem or limitations but an icon that matches the macOS Big Sur aesthetic would be nice.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
macOS Big Sur app icons are all now contained in a rounded rectangle.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
simply replace the standard Godot icon with something similar to this for macOS .
<img width="462" alt="Screenshot 2021-01-05 at 18 18 40" src="https://user-images.githubusercontent.com/4403212/103683759-858ec080-4f82-11eb-82f4-48f5cd3e6253.png">

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It is possible to change the icon in macOS but as soon as Godot runs the icon is replaced with the default one.

### Is there a reason why this should be core and not an add-on in the asset library?
Its a very simple fix

**Comment by KoBeWi** [comment]
Closing as duplicate.
