### ISSUE TITLE
Make nodes inherit custom multiplayer

### ISSUE THREAD

**Issue by udit** [godotengine/godot-proposals#2079]
### Describe the project you are working on
An online multiplayer where a single server executable will host several rooms using `custom_multiplayer` override
<br>

### Describe the problem or limitation you are having in your project
I think current process to setup multiplayer branches [as shown here in the example](https://github.com/LudiDorici/gd-custom-multiplayer/blob/master/script/custom_multiplayer.gd) can be simplified and optimized.
<br>

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
User will initialize the `custom_multiplayer` in the `_init()` callback of the desired node and set it as root node. Child nodes should set their `custom_multiplayer` from parent when it enters tree.
<br>

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Following code in the `_init()` of root multiplayer node should suffice to create a multiplayer branch:
```
custom_multiplayer = MultiplayerAPI.new()
custom_multiplayer.set_root_node(self)
```
Then, the engine can set the `custom_multiplayer` of child nodes or dynamically added nodes from the parent.
<br>

### If this enhancement will not be used often, can it be worked around with a few lines of script?
To get this to work in script, you will have to copy paste the following code to each and every node in the project which is not convenient:
```
func _enter_tree():
if custom_multiplayer == null:
    custom_multiplayer = get_parent().custom_multiplayer
```
<br>

### Is there a reason why this should be core and not an add-on in the asset library?
This can't be achieved through add-on

**Comment by Calinou** [comment]
cc @Faless

**Comment by Jummit** [comment]
Maybe `custom_multiplayer` should have something like [`pause_mode`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-property-pause-mode), which could be `inherit` or `none`. In most cases you would want `inherit`.

**Comment by Faless** [comment]
> To get this to work in script, you will have to copy paste the following code to each and every node in the project which is not convenient

In the [first demo](https://github.com/LudiDorici/gd-custom-multiplayer/blob/master/script/custom_multiplayer.gd) I posted about custom multiplayer I was connecting `node_added` in the "custom multiplayer root node" instead, so you don't have to write that code in all your child nodes.

I think the original issue with inheritance was either about performance (having to recursively check parent custom multiplayer) or reference counting (having the custom multiplayer being unexpectedly assigned to a child node, and not being deleted when you remove it from the only node you had explicitly assigned it to).

**Comment by udit** [comment]
> In the [first demo](https://github.com/LudiDorici/gd-custom-multiplayer/blob/master/script/custom_multiplayer.gd) I posted about custom multiplayer I was connecting `node_added` in the "custom multiplayer root node" instead, so you don't have to write that code in all your child nodes.

True, that is not needed as per demo. I mentioned it in reference to my solution.

>I think the original issue with inheritance was either about performance (having to recursively check parent custom multiplayer)

That shouldn't be an issue with my approach. Node will only check it's parent multiplayer while entering the tree, not recursively back up the tree. Since nodes are added in top-down order into the tree, all the children and sub-children will automatically inherit the multiplayer.

>or reference counting (having the custom multiplayer being unexpectedly assigned to a child node, and not being deleted when you remove it from the only node you had explicitly assigned it to).

I didn't quite get that. Do you mean child nodes will still have multiplayer assigned, when you set the root node's custom multiplayer back to null? But isn't that an issue with the approach in the above demo project too? If multiplayer is changed anytime after `_init()`, it will not propagate to children.
<br>
I do think custom multiplayer needs improvement. Consider the current approach in demo. With `m` server rooms and `n` nodes in each room, it will amount to `m*n` node path checks for assigning multiplayer whenever a new room is created.

**Comment by Faless** [comment]
This has been discussed during today's networking meeting, but we couldn't decide for a definitive answer.

Setting the custom_multiplayer on tree enter is not very problematic performance wise there is open questions on recursively setting it (or not) when changing.

We will likely re-evaluate this in the next networking meeting.

**Comment by Faless** [comment]
The `custom_multiplayer` property was in the end removed, it's now possible to configure entire branches of the SceneTree to use a separate `MultiplayerAPI` via `SceneTree.set_multiplayer(MultiplayerAPI, NodePath)`.

E.g.:

```gdscript
var mp1 = MultiplayerAPI.create_default_interface()
var mp2 = MultiplayerAPI.create_default_interface()
func _ready():
    get_tree().set_multiplayer(mp1, ^"/root/main/client")
    get_tree().set_multiplayer(mp2, ^"/root/main/server")
```

So that the `client` node and all its (grand-)children will use `mp1` and that the `server` node and all its (grand-)children will use `mp2`.

Closing as fixed via https://github.com/godotengine/godot/pull/57647
