### ISSUE TITLE
Allow setting of GDScript `class_name` property through the Create Script menu

### ISSUE THREAD

**Issue by homchom** [godotengine/godot-proposals#208]
**Describe the project you are working on:**

I am working on a program that allows the user to configure a thermometer-style progress bar to display.

**Describe the problem or limitation you are having in your project:**

I noticed that when creating GDScript files, the "Class Name" option in the menu is locked. The docs say this is because "the file itself represents the class". However, recently the `class_name` property was added, and I think this menu was overlooked. My "problem" is not as much a problem as it is a notice of inconsistency and overlook within the editor.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

 My proposal is to unlock this field and allow setting `class_name` from the menu, similarly to how `extends` can be set using the "Inherits" field. This would fix the inconsistency and overlook mentioned above.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

<img width="208" alt="h" src="https://user-images.githubusercontent.com/41265646/68253612-55523780-fff6-11e9-9aef-40a5d60a8723.png">

**Describe implementation detail for your proposal (in code), if possible:** N/A

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It can be worked around with one line; however, it should in theory be used just as often as the `class_name` keyword itself if implemented. It is also an easy fix to an inconsistency.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is not a "new feature" like those found in the asset library; it is just an expansion of an existing feature that makes logical sense.

**Comment by aaronfranke** [comment]
Related: #209
