### ISSUE TITLE
Make CSG nodes able to generate collision using CSG primitives rather than a triangle mesh

### ISSUE THREAD

**Issue by addmix** [godotengine/godot-proposals#2083]
### Describe the project you are working on
I am working on a semi-realistic FPS, that focuses on player controls and ergonomics.

### Describe the problem or limitation you are having in your project
I want to be able to use CSG objects (specifically tori [torus plural]) for collision. There is no built in option for a torus collision shape, or being able to apply a CSG difference operation on collision shapes, without using mesh collision

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
CSG objects having their proper round collision shapes, along with combination CSG primitives in the physics engine, without using tri mesh collision

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
CSG objects are notorious for being easy to raycast, along with raymarching. There are a few papers from the 90s documenting CSG collision. CSG basics outline how boolean operations are handled.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
no

### Is there a reason why this should be core and not an add-on in the asset library?
CSG is very common for prototyping, and is useful for approximate collision shapes of meshes. This should be a core functionality to the physics engine which can be hard to modify in this way, and keep efficiency without custom builds.

**Comment by Calinou** [comment]
This would require implementing CSG collision shapes in the engine, which has many use cases but also sounds pretty difficult.

**Comment by addmix** [comment]
With the way that CSG operations are handled, CSG collisions wouldn't be far off from the current collision shape workflow. Adding more collision shapes to the engine (torus, cylinder) would further expedite a possible inclusion of CSG based collision, as collisions can be tested using logical operators on the results of multiple individual collision bodies.

https://en.wikipedia.org/wiki/Constructive_solid_geometry
![image](https://user-images.githubusercontent.com/38119387/104094437-2a90ee00-524e-11eb-861d-2e4ed8236879.png)
"CSG objects can be represented by binary trees, where leaves represent primitives, and nodes represent operations."

The only probably issue I can imagine is current CSG may not translate to binary trees, possibly needing reworking.

**Comment by reduz** [comment]
This is not mathematically possible, sorry. The only technique that can more or less work this way is sphere-SDF collisions, which rules out all other physics shapes (box, convex poly, capsule, etc) and its also not amazingly precise. Physics engines work on the premise of convex shapes, and once you do a union/intersection/subtraction in CSG, it rarely remains convex.

**Comment by Calinou** [comment]
Closing per the above comment.
