### ISSUE TITLE
Add so the new .glTF exporter can export entire scenes, not just one mesh . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2086]
### Describe the project you are working on
A Tomb raider game, about defeating a god, of war, or so <3 . .

### Describe the problem or limitation you are having in your project
The new .glTF exporter, with materials, textures is really amazing, but I was hoping it could be have feature, so one can export an entire SCENE, since I often have terrain, static objects, houses, cars in a single scene, with nothing else . . Having the ability to export all that stuff, into Blender, would be really amazing, thanks . . :O <3 . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, the new exporter, if it could support exporting a single mesh, a selection of meshes or, an ENTIRE scene, it would be nicer, or so . . Thanks . . Export selected and, export entire scene mode, or so . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Not sure how new exporter works, but I'd really use that feature, a lot, adding exporting a complete scene, would be really, really cool or, so . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't code the engine, I can make a basic controller, and some levels, so I can't do this, atm . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it's such a cool feature, I plan on using it for most of my games, as it is, but being able to send an entire scene into Blender, work on it, and then send it back, would be amazing . . perhaps even a Blender plug-in, that allows live updates, ie. it updates the meshes, that have been changed, not the entire ' scene ', so one has ' live ' level editing, Godot < - - > Blender, or so, thanks . . <3

**Comment by akien-mga** [comment]
As far as I know the glTF export *is* a scene exporter (that's its name at least). Did you try it?

**Comment by jasperbrooks79** [comment]
No, I was waiting for the official Godot 3.2.4 release, in case there were any bugs or, so, wanted the ' official ' release, to worry less, over bugs, in code . . <3

Thx . .

**Comment by NHodgesVFX** [comment]
> No, I was waiting for the official Godot 3.2.4 release, in case there were any bugs or, so, wanted the ' official ' release, to worry less, over bugs, in code . . <3
> 
> Thx . .

Gltf exporter is in godot 4 not 3 i believe.

**Comment by jasperbrooks79** [comment]
no, it's also in the official dev note, of the Godot 3.2.4, but since my old projects might not work, in Godot 3.2.4, bec. of changes, well I don't make changes to engine, until it's an official release, bec. it can create all sorts of problems or, stress . .

I'll wait, until they all agree, it's stable, and the last bugs, have been worked out, but I want 3.2.4, since it has more lights, and many other cool stuff, mp3 support, which I will use, also . . but, bec. how games look in 3.2.3 - 3.2.4 are almost the same, it's a bit well, worrying to change version, as it might make bugs, and earlier projects crash, or won't work, or so . . :(( <3 . . .

**Comment by NHodgesVFX** [comment]
> no, it's also in the official dev note, of the Godot 3.2.4, but since my old projects might not work, in Godot 3.2.4, bec. of changes, well I don't make changes to engine, until it's an official release, bec. it can create all sorts of problems or, stress . .
> 
> I'll wait, until they all agree, it's stable, and the last bugs, have been worked out, but I want 3.2.4, since it has more lights, and many other cool stuff, mp3 support, which I will use, also . . but, bec. how games look in 3.2.3 - 3.2.4 are almost the same, it's a bit well, worrying to change version, as it might make bugs, and earlier projects crash, or won't work, or so . . :(( <3 . . .
> 
> might as well wait, until it's out of beta, since as a beginner, I will have some problems, finding out what weird bug reports, in the log actually mean, I can barely fix bugs, as it is, using the debugger :OO . .
> 
> it's just safer, to wait until an official release, and it happens so fast, now it's 3.2.4 beta 5, or 6, I'm just waiting until it's stable because, I'm noob . . .

Where do you see it mentioned that's in 3.2.4 the blog post mentions it but it doesn't say its in 3.2.4. https://godotengine.org/article/introducing-the-godot-gltf-2-0-scene-exporter this notes that its a feature for godot 4. Although i have a need for the exporter too so it would be cool if it was in 3 but i dont think so.

**Comment by jasperbrooks79** [comment]
wait, it's not there, I mis - read it, for some reason . .

was sure it said somewhere, in one of beta 4 or, beta 5 that, it would be there :(( . . .

**Comment by fire** [comment]
I do not have time to do this for 3.2 sorry.

**Comment by jasperbrooks79** [comment]
dang it, now I say what they ALL say . . can't wait, for Godot 4 . .

it'd be nice with a plug-in, in Blender, so one can auto - update the stuff, one works on, so if one has a .glTF with, ten houses, and one changes the textures, on one, or two, then one can click update, and just the stuff one changed, will be updated, so one doesn't send massive files, that needs updating, before working, or I will need to use, scenes, within scenes, or so . . :O 

Godot 4, why you no here </3 . .

**Comment by Calinou** [comment]
Closing, as this is already implemented in the `master` branch and `3.x`. (The glTF exporter has been backported to Godot 3.4.)
