### ISSUE TITLE
Change Versioning from major_version.minor to yyyy.mm or some date based one

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot-proposals#2095]
### Describe the problem or limitation you are having in your project
Godot's current version system is major.minor like 3.2.
Maybe a friendlier system would be a date based system like Godot 2021.03 or Godot 21.03.
Many major software systems use this type of versioning system (including other game engines :))
This could be done after Godot version 4 (which everyone is waiting for)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Dates are more human centric.
It is easier to remember.
If godot is moving to a shorter dev cycle after the 4.0 milestone this would be ideal. It is better to tell users that version 21.12 is self-evidently coming in December, than 4.0.1 is arriving in December.
 It is easier to bug report and say it was working in 21.09 but not in 21.08 rather than 3.2.5 b4 .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Maybe after version 4.0 is released this could be looked at?

**Comment by pycbouh** [comment]
This is all very speculative, especially the part about easier to report. Also, software that uses `year.version` notation rarely follows or can even keep up the monthly release cycle. Say, JetBrains' IDEs can release 2 to 4 versions a year, so they'd have, for example, `2021.2`, but it doesn't come out in February. So, any assumption like that would be wrong.

Speaking strictly of Godot, we don't keep such tight release cycle either and doubtfully would be able to do in future. Open source and month sprints don't work well together. Also, there is very little obligation that something will be finished in the year it was planned to be finished. Godot 4 would've been announced as `2020.x`, and would've missed that timeframe completely.

Finally, we prefer versions to have some meaning of actual compatibility between them. `4.x` is clearly not very compatible with `3.x`, but `2021.1` can be a minor update on top of `2020.12`. Therefore such versioning would only be helpful to understand in retrospect which year it was released, but any other assumptions would go out of the window.

**Comment by rick551a** [comment]
Interesting points, seems that this proposal isn't very suitable for Godot.  Just thought I'd put it out there, no harm done.

**Comment by Calinou** [comment]
Closing per @pycbouh's comment. We don't have plans to change the versioning scheme for now.
