### ISSUE TITLE
Add Collision on 3d particles 

### ISSUE THREAD

**Issue by regniraj** [godotengine/godot-proposals#21]
**Describe the project you are working on:**

**Describe how this feature / enhancement will help your project:**

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by clayjohn** [comment]
In order for your proposal to be considered, you need to fill out the template please.

**Comment by yaelatletl** [comment]
There's this already done as an addon: https://gitlab.com/polymorphcool/futari-addon. It would be cool if someone implemented it with the current collision system.

**Comment by groud** [comment]
There is an issue template, it is not here for nothing.
