### ISSUE TITLE
Rename 'SpinBox' to 'NumberInput'

### ISSUE THREAD

**Issue by TheFamousRat** [godotengine/godot-proposals#210]
**Describe the project you are working on:**
Basic tool project interface.

**Describe the problem or limitation you are having in your project:**
I think the name "SpinBox" is counter-intuitive and a handicap when it comes to looking for this import numerical input Control.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The current name, "SpinBox", is weird and makes allusion to the two arrows next to the input zone that allow to change the number with the mouse, but I think it is faulty since it doesn't represent the main function of this Control : allow the creation of a number input zone. 
 
A name like "NumberEdit" or "NumberInput" would be simpler, coherent with the rest of the input Control ("TextEdit", "LineEdit") and make the Control intuitive to find when looking through the docs.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
N/A

**Describe implementation detail for your proposal (in code), if possible:**
N/A

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think the "SpinBox" Control is very practical, but its weird name make it too hard to be found, and it may lead developer to lose time looking for a way to create their own numerical input Control because they didn't find it in Godot because of its name, when it fact it already existed.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Minor change in code (just a name change)

**Comment by bruvzg** [comment]
It's `SpinBox` in [WinAPI](https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-spin-controls), [Qt](https://doc.qt.io/qt-5/qspinbox.html), [TK/TCL](https://www.tcl.tk/man/tcl8.4/TkCmd/spinbox.htm), `SpinButton` in [GTK+](https://developer.gnome.org/gtk3/stable/GtkSpinButton.html), pretty much standard name that refers to the control with the arrow (or +/-) buttons.

For the generic number input you can use `LineEdit` and filter the input as necessary (for example: https://github.com/blurymind/godot-lineEditPlus/blob/master/LineEditPlusNode.gd).

**Comment by Calinou** [comment]
Related: https://github.com/godotengine/godot/issues/30736

**Comment by girng** [comment]
There are a lot of things in Godot that are counter-intuitive at first glance, but grow on the developer. It's been this way for nearly half a decade, why change it now (unless it's objectively the wrong spelling and no nuance, etc)?

**Comment by TheFamousRat** [comment]
I hear what you're saying about this. I don't agree, but I understand. My disagreement comes from this concern about newcomers looking for way too long a time for a NumberInput node, not finding it, maybe losing time creating theirs... 
A solution that might settle with both sides would be, hypothetically, to add keywords to Node of Godot. By default, it is an array containing only their own name, but in some cases (such as this one) where the isn't so intuitive, why not having it be ["SpinBox", "NumberInput"] ? It would in this case as well as other cases of renaming proposals be a convenient solution.

**Comment by Calinou** [comment]
> A solution that might settle with both sides would be, hypothetically, to add keywords to Node of Godot.

I proposed this for the editor help a while ago in https://github.com/godotengine/godot/issues/29286.

**Comment by Calinou** [comment]
I'll close this due to lack of support. Please open another proposal if you'd like to see search aliases/keywords for node names in the Create New Node dialog.
