### ISSUE TITLE
Make a visual script box that ' spawns ' objects, with 'GPU' physics or, so . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2112]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I need to make stuff, like a gun or, machine rifle, that ' spits ' out bullets, and I'd like to use a particle system, to do it . . The problem is, particles are limited to, only 'working' each time the ' timer ' runs out, so a particle time, of 4 second, means if I press the button, to spawn bullets, fast . . then, it'll ' pause ' until ' the next four seconds . . alternatively I can write code, that ' spawns ' them, but I was wondering, since the GPU is better, if one could make a node or, code that spawns ' a particle ' ( object ), and runs it on the GPU . . GPUSpawner node or, so on . . I'm not sure, if this would work, and I think it'd need some special built-in methods and, property, to make sure it ' only ' does, what the GPU can do ( compared, to CPU particles ) . . but, this would potentially be a way of spawning massive amounts of particles or, objects, or so . . I need it, so when I pump out bullets, when a button is pressed or, such . . that it spawns as many, and as fast, as I need . . and, has minimum lag, so it's faster, as well . .

Is this possible, and could this be a new way, of making games run faster, not sure <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, current particles don't work for stuff like ' bullets ', bec. they can only ' emit ', every time the timer hits the ' life ' time, for 4 seconds, it can ' being a ' spawn, at 4 seconds, 8 seconds, 12 seconds, so on . . but, I need it to spawn, at any, given time, and as FAST as possible, since many things only need GPU processing, CPU particles can do a few things, more, I think, not sure . . well, I was wondering if that might be good, in my case I guess simply coding a ' spawn ' using the normal code wouldn't matter, but supposed I need to spawn 100.000 particles or, objects, could the GPU do that . .

I just want the game to run as fast, as possible, in real - time . .

But, it might be technical also, need to be written, for GDScript, not only visual script, or so . . even if people only spawned, say 10.000 fog particles, doing it via GPU, would still be faster, and over-all be more optimized = faster FPS, I hope, thanks <3 . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, a way to instantiate, using the GPU, instead of CPU, or so . . not sure how to code it, be nice if it was just something, that could be done, using GDScript, or visual script . . for stuff that could be run on CPU, like the bullets, it'd may-be still be faster, and give a frame - rate boost, over - all <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't re-program the engine, total beginner . . :OO . .

### Is there a reason why this should be core and not an add-on in the asset library?
This is better left, to the engine devs, to figure out, was thinking it could work, like the ECTS system, in Unity, that allows 'spawning' of MANY objects, in parallel, or close <3

Thanks . .

**Comment by jasperbrooks79** [comment]
now, suppose you have to calculate collision, between 10.000 enemies . . maybe that could be sent to the GPU, and handled there, giving a much larger amount of enemies, on screen . . not sure, one would need a MathGPU visual script, or so on . .

maybe one could make a physics engine, that runs on the GPU . . other stuff . . <3

**Comment by jasperbrooks79** [comment]
like, move_and_slideGPU, which can only do the math, the GPU can . . and, maybe a property, so one can set aside, how many GPU threads on use, or say 25 %, so one can still have graphics performance . . not sure, is possible . .

**Comment by jasperbrooks79** [comment]
like, maybe make a RayCastGPU, so if one has an army, of 100.000 units, with collisions ( simplified ) running on the GPU, it could also calculate ' elevation ', so they can move over terrain . .

maybe, the GPU could handle simple collisions, or so . . >>
<img width="637" alt="2021-01-13 1059" src="https://user-images.githubusercontent.com/61069740/104436955-84ffb680-558e-11eb-9aef-ad1d821bb09a.png">

**Comment by jasperbrooks79** [comment]
like, the same way the GPU can run a bunch of shaders, at same time, maybe it could run some physics stuff, also . . .
![Skærmbillede (886)](https://user-images.githubusercontent.com/61069740/104438171-f9872500-558f-11eb-9e45-955cb0162866.png)

it'd only need some special methods, that are specific to that node, like sub - methods, so it's GPU - stuff <3

**Comment by jasperbrooks79** [comment]
like, maybe a RayCastGPU could work, by using a texture, as a height - map, and after it has calculated collision, it takes the ' height ' of unit, from the height map, since GPU process textures fast, not sure . . 

<img width="257" alt="2021-01-13 1125" src="https://user-images.githubusercontent.com/61069740/104439989-13c20280-5592-11eb-9061-b9d8840b3e57.png">

then, maybe the CPU could do the last calculations, for finding the exact height, or using, approximations, etc etc . . <3

**Comment by jasperbrooks79** [comment]
the last part, as SSD's are very fast, might be to be able to write large data amounts to SSD's, so it doesn't tax memory, not sure . . making full use, of the latest tech, to get un-rivalled performance, again, not sure . . <3

**Comment by jasperbrooks79** [comment]
last, calculating stuff like 3D sounds, so AudioStreamGPU, for calculating accurate sound acoustics or, using approximations, might enable like, 1000 people talking, simulated . . <3

**Comment by jasperbrooks79** [comment]
last thing is, GPU's are good at calculating light, so on . . those aspects, of the GPU's, might be able to be used, for other calculations, not just texture processing or, loading things super - fast, using special VRAM . . if that GPU memory, could be used for storing or, keeping physics information, it might be VERY fast, or so . . Thanks . . <3 <3

**Comment by jasperbrooks79** [comment]
last, since many computers use multi-threaded CPU's, maybe the work-load, could be sent there, for optimization . . ie., make full use, of the architecture, this is really wild, hard - core stuff . . :OO

**Comment by jasperbrooks79** [comment]
or, multi - core, maybe an engine god or, master could make really good use, of all this stuff, to create a brand new physics and, effects engine . . <3 :OOO . .

**Comment by jasperbrooks79** [comment]
maybe, the new voxel terrain editor, could be stored in a 3D texture, or so, and calculated, on GPU . . 

![2021-01-13 1226](https://user-images.githubusercontent.com/61069740/104446434-bda58d00-559a-11eb-9906-1187b9bab8b6.jpg)

not sure how well, GPU handles 3D textures or, volumetric textures, at all <3

**Comment by jasperbrooks79** [comment]
that way, the entire terrain would be a ' shader ', and the CPU could handle tri-mesh collision, alone . . :O

**Comment by jasperbrooks79** [comment]
stuff like water, might also be a ' voxel ' river, or wind, could be a ' shader ' :OO . .

may-be . . .
![2021-01-13 1232](https://user-images.githubusercontent.com/61069740/104447027-82f02480-559b-11eb-940c-8e2dff96cb67.gif)

GPU approximations . . <3 also, wind, hurricanes or, earth - quakes, that deform the pixels, in a GPU terrain shader, not sure . . :OO

**Comment by jasperbrooks79** [comment]
maybe in a terrain, instead of making a cube, if the terrain is say, 200 meter wide, and tops 20 meter high or, so . . then, the 3D texture could be compressed, to 200 x 20, to save space, or one could use alpha channel, to select parts, not to be calculated, so one ' thread ' could process faster and, be freed, to do other stuff, hard - core optimization, maybe using AI, or like, god - level code, or more <3 Thanks . .

**Comment by jasperbrooks79** [comment]
last, since the audio card also has a special processor, for what it does, maybe one could send certain calculations, like an 'audio' shader there, to make it pitch in, for frequency or, wave calculations, that's hard - core . . like, shaders run well, on GPU's, maybe the audio chip-set, could be ' recruited ', to do certain non - audio calculations, maybe in physics, such as wave height, on water - shader or, so . . Thanks . . . <3 <3

**Comment by jasperbrooks79** [comment]
like, maybe one of the threads in the audio card, could be used, for physics, instead of an ' effect ' . .

<img width="600" alt="2021-01-13 1148" src="https://user-images.githubusercontent.com/61069740/104448628-b8960d00-559d-11eb-9581-350c390fffff.png">

<3

**Comment by jasperbrooks79** [comment]
like, for calculating waves on, top of waves or, so . . >
![2021-01-13 1150](https://user-images.githubusercontent.com/61069740/104448814-f2ffaa00-559d-11eb-8ec4-028a4c36f5d9.png)

or, wind bouncing, in rooms or, so, for realistic wind effects <3

**Comment by jasperbrooks79** [comment]
here . .
![2021-01-13 1251](https://user-images.githubusercontent.com/61069740/104448935-1e829480-559e-11eb-9de9-3d8d87489cbc.jpg)

in theory, it should the same, as adding audio waves and, ' finding ' result <3 . . .

**Comment by jasperbrooks79** [comment]
or, rain drops that fall on water, and propagate like waves, etc . . .>>

![2021-01-13 1253](https://user-images.githubusercontent.com/61069740/104449162-78835a00-559e-11eb-93a5-b39c5976c750.jpg)

I don't know how good current audio chip-sets are, of what they can do . . a single rain-drop calculation could be ' replicated ' and, used again, once the calculations, are done <3 . . :OO . . .

**Comment by jasperbrooks79** [comment]
by sending calculations back, and forth between the CPU, GPU and, audio processor chip - set, one could make some cool physics or, simulations . . need to be written, in C# or, GDNative, to run the best . . :OO

**Comment by jasperbrooks79** [comment]
an earth - quake, a tsunami or, a massive storm is, also just a 'wave' that propagates . .

like a wave, in the sky . . <3 <3
![2021-01-13 1305](https://user-images.githubusercontent.com/61069740/104450217-06137980-55a0-11eb-929a-530ea0dc7753.jpg)

it's a stuff, for engine legends ( Juan <3 . . .

**Comment by jasperbrooks79** [comment]
rain, that billows in wind, is also a wave or, sine curve, getting mixed . . <3 <3 . . . Thanks . .

**Comment by jasperbrooks79** [comment]
and, maybe Sony could lend some expert help, with the coding, to create a brand new technology and, as a thank you, make Godot a supported engine, ie. allow export, and code the port, to Playstation <3 <3 . . :OO

**Comment by jasperbrooks79** [comment]
it might make Godot the most desired engine, to make next - gen games in, at least on Playstation, except one has to get 'approved' a game, by Sony, to publish it, but AAA studios might like it, that have a ' foot in ' the door, or so <3

also, they may give a nice donation, as thank you . .

**Comment by jasperbrooks79** [comment]
also, this could potentially put Playstation miles, ahead of Xbox, where it's lacking a bit, in terra-flops, think 10.2, vs. 12.3, on Xbox, getting the audio card involved, for making physics and, effects, might make it 50 % faster, than Xbox :OO <3 <3

**Comment by jasperbrooks79** [comment]
also, there could be a deal, where all companies wanting to use this ' audio shader ' tech . . would be asked to use Godot, for their game projects, as thank you . . <3 then, you're a house-hold name, in 1 - 2 years, globally <3 <3 . . . .

**Comment by jasperbrooks79** [comment]
for instance, the explosions inside the building, might be calculated as 3D sound, bouncing in the rooms, then send the physics calculations, to the GPU or, some part, of the CPU <3

![2021-01-06 1612](https://user-images.githubusercontent.com/61069740/104452335-285ac680-55a3-11eb-84f1-090ca0460dc5.gif)

or, maybe this could be handled, in part, by the audio multi-thread processor . . :OO

![2021-01-06 1613](https://user-images.githubusercontent.com/61069740/104452393-3c9ec380-55a3-11eb-8b05-c23a0cbe8b64.gif)

have to be heavily optimized, Sony could maybe be interested in this, and take Godot's open source code, and use it to build their in-house dev kit . . <3 <3 :OO . .

**Comment by jasperbrooks79** [comment]
last thing is, I heard what makes SSD fast, is that it can read a lot of things, in parellel, same way GPU makes calculations, in parallel, so it might be possible to recruit the SSD, as the last piece, of making ' shaders ' run fast, as virtual memory, or a place to store and, retrieve a ton of information, in parallel . . .

**Comment by Calinou** [comment]
Closing due to lack of support.

This can already be achieved with GPUParticles3D/2D nodes, including with manual emission from script.
