### ISSUE TITLE
Make the Lines in the TextureRegion Dock contrast the Texture's Color

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#2113]
### Describe the project you are working on
Game Project

### Describe the problem or limitation you are having in your project
Ran into a minor inconvenience while working on a white (`#ffffff`) sprite that I was using in a `NinePatchRect`. While adjusting the Region Rect through the `TextureRegion Dock`, the lines that indicate the cut-off point for the NinePatch completely blend with the sprite itself, making it hard to read and work with. The same goes for the outline.

![image](https://user-images.githubusercontent.com/10502115/104464815-a4f5a100-55b3-11eb-8f41-eef5411ad4e9.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Perhaps it would be better to contrast the lines against the Texture instead. I'm not sure this would look better _(especially on textures with a large amount of different colours)_, but at least it would be clear. Although seeing as this only really happens with extremely white colours, perhaps inverting the colour of the line (or replacing the colour) on those sprites with that colour might be enough.

I'm not really sure how to deal with the outline. It suffers from the same issues, but it needs to be both readable against the background, and against the sprite itself.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/10502115/104467042-28b08d00-55b6-11eb-94b0-234ad51ed3b2.png)

_contrasting lines of a different colour on the sprite itself_

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Cannot be worked around, and I'd argue this happens fairly frequently, as little UI pieces are often implemented in `#ffffff` , so they can easily be modulated through Godot itself.

I do get that adding this feature might be harder than it seems, and that the issue can still be worked with by looking at the variables or the lines on the background. However, I saw it fit to open a proposal for it either way. I am also sure this issue is also present in other (Texture editing) parts of the engine. If I find any, I'll post them in the comments below.

### Is there a reason why this should be core and not an add-on in the asset library?
Core: UX issue of a core feature.

**Comment by Calinou** [comment]
Making the dotted line have a translucent black background should solve this elegantly.
