### ISSUE TITLE
Add a setting, so you can change the color, of the ' origin ' lines . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2118]
### Describe the project you are working on
A Tomb raider game, with monsters . .

### Describe the problem or limitation you are having in your project
It's not a problem, so much . . But, I'd like to be able to set the individual colors, of the origin ( now, it's red, green, blue ) . . Just a place, to change that, so it looks consistent or, nice <3 <3

<img width="757" alt="Skærmbillede (894)" src="https://user-images.githubusercontent.com/61069740/104557932-5216fa80-5642-11eb-941e-34b520bca7f7.png">

It'd complete my experience of Godot, make it 100 % mine, or such . .

Also, the 3D gizmo, for rotating, scaling, etc . . Thanks . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Just, so the editor looks ' just ' right <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
That's the last request, from me, all I ask . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not sure, not able to code, so well <3

### Is there a reason why this should be core and not an add-on in the asset library?
Again, I have no idea . . :(( . . . . .

**Comment by jasperbrooks79** [comment]
if, may-be change each line, to have it's own color, be nice, Thanks . . . .

**Comment by Calinou** [comment]
I don't see an use case for changing origin line colors. It's widely established that X is red, Y is green and Z is blue.

**Comment by jasperbrooks79** [comment]
I agree, this is about making the engine look custom, so each user can have their own unique Godot experience . .

the text editor, for code, is highly customizable, you can change all kinds of things, it'd just have to be a setting in ' editor ' settings, under 3D ' Gizmo ', that already has many settings . .

so many other things are customizable, I'd really like this, HOPE it's not too complex <3 Thanks . . .

**Comment by mrjustaguy** [comment]
I mean eh, giving the option to change wouldn't hurt, but I don't see anybody using it, and totally don't think it's worth the effort of  adding that

**Comment by jasperbrooks79** [comment]
I would, use it, for my own version, of editor, based on my own ideas, and the project, I'm making, atm . . .

**Comment by Calinou** [comment]
Closing due to lack of support
.
