### ISSUE TITLE
Allow checking if an image resource is locked or not

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot-proposals#212]
**Describe the project you are working on:**
Graphics editor plugin

**Describe the problem or limitation you are having in your project:**
I can't check whenever an image resource is locked or not.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If this feature is added then I can check whenever an image resource is locked so I can write to the image.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes, but you would be sort of guessing when it's locked or not which can lead to some faulty code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This feature can only be in the core because it's impossible to check currently if an image resource is locked or not.

**Comment by KoBeWi** [comment]
The implementation would be literally 6 lines. But then we would effectively have a setter and getter, so `Image.locked` property could become a thing.

**Comment by akien-mga** [comment]
This is no longer relevant as `Image` no longer requires locking in 4.0.
