### ISSUE TITLE
Allow fine-tuning 3D scale of objects in all situations, regardless of zoom and scale

### ISSUE THREAD

**Issue by lentsius-bark** [godotengine/godot-proposals#2120]
### Describe the project you are working on
First-person story driven platformer

### Describe the problem or limitation you are having in your project
Using scaled assets for distant vistas, once an object has been scaled up fine tuning its size is near impossible
![godot_scale_tool](https://user-images.githubusercontent.com/38346332/104590623-e47fc400-566b-11eb-9b69-1d06d7289db3.gif)
The problem seems to be related to camera zoom at the moment.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The correct solution for this is beyond me, I've had a few ideas though:
1. The distance of the mouse click from the gizmo is relative 1.0, on screen position of the gizmo 0.0
2. Take the view's zoom into consideration, as at the moment the scale steps get bigger the further the camera is.

Now I'm not proposing a massive change here, I understand the underlying code might be complex, but I honestly hope there is a way of fixing this.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
1. gizmo on screen position.distance_to(mouse_on screen_position) = scale_start
2. scale step * zoom?

The best I could come up with!

### If this enhancement will not be used often, can it be worked around with a few lines of script?
The enhancement would improve overall usability of scaling in 3D. I've struggled with fine-tuning the scale of objects for a while now. If the scale tool is tweaked in a way that allows for fine, predictable scaling in a wider range of situations, users will notice the difference in a myriad of situations.

### Is there a reason why this should be core and not an add-on in the asset library?
This would also work as an addon. Sadly it would be an addon fixing a non-complete functionality of Godot's core scale gizmo/tool.

**Comment by lentsius-bark** [comment]
This proposal has received several thumbs up, and it still remains a usability issue I face daily when level designing in 3D.
I've come up with dirty workarounds, I.e. a scaled object is parented to a new parent and then I use the parent's scale to fine tune the size however as you may imagine this is not optimal.
Apologies if I shouldn't be bumping this but the shown interest and the fact it's a prevailing usability issue may be of interest to the devs :)

**Comment by lentsius-bark** [comment]
This has been fixed by my PR on both Master and 3.x branches, hence I'm closing this issue.

**Comment by Calinou** [comment]
For the record, this was fixed by https://github.com/godotengine/godot/pull/52685 and https://github.com/godotengine/godot/pull/52665.
