### ISSUE TITLE
Add `h_separation`& `v_separation` variables to ScrollContainer

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#2123]
### Describe the project you are working on
Attempting to use a ScrollContainer, to show it's limitations, in my opinion. As I said I would do in (#2119)

### Describe the problem or limitation you are having in your project
I want to be able to adjust the spacing between the Content of the ScrollContainer, and the Scrollbar it spawns. We all know there is basically a HBoxContainer in there somewhere, so I want to have those variables exposed, so I can properly space out my scrollbar.

![image](https://user-images.githubusercontent.com/10502115/104605301-9b853b00-567e-11eb-95a2-ac1ebe28cb36.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add `separation` variables to the ScrollContainer, which indicate the amount of spacing between the right side of the content, and the left side of the VScrollbar. Obviously the same goes for the HScrollbar.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just allow spacing such as this:
![image](https://user-images.githubusercontent.com/10502115/104605773-367e1500-567f-11eb-82df-fee9f971f6f6.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
The only way I know this can be worked around, is by giving the ScrollContainer a Theme, and giving the VScrollBar a material, which has an transparent border on the left. That will make it seem like it has spacing.

### Is there a reason why this should be core and not an add-on in the asset library?
Core: Addition to functionality of ScrollContainers

**Comment by pycbouh** [comment]
> The only way I know this can be worked around, is by giving the ScrollContainer a Theme, and giving the VScrollBar a material, which has an transparent border on the left. That will make it seem like it has spacing.

Does content margin of the stylebox not affect this?

**Comment by Arecher** [comment]
> Does content margin of the stylebox not affect this?

![image](https://user-images.githubusercontent.com/10502115/104607927-a1c8e680-5681-11eb-89ca-5b8d31bcccd5.png)

I thought the same originally. But it only seems to make it bigger.

**Comment by Arecher** [comment]
> Does content margin of the stylebox not affect this?

Nevermind, the Stylebox of the ScrollContainer does allow for this. You're right
![image](https://user-images.githubusercontent.com/10502115/104608374-169c2080-5682-11eb-85f1-007cff449437.png)
