### ISSUE TITLE
Make some visual script boxes that gets ' run ' as native or, turned into native by virtual machine . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2126]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I love performance and, strong FPS, or so . . I was wondering if one could make a virtual machine, for visual script, that turns it into native or, C# . . not sure if it's possible, wanted to ask, the Godot masters . . <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Maybe some boxes, like a Math box, called MathNative, that does things, in a native virtual machine, or runs the code, in a ' compiled ' way, not sure if it's like shaders, where native can only do certain things, if so, having the ability to make certain things, maybe by selecting in inspector, as a menu or, drop - down, that it runs in visual script, GDScript, native, or C#, so that only boxes that support this, can select it, or so . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, I want really good performance, and would love the ability to select certain parts of the visual script, to run in ' native ', or ' GDScript ', or so . . can it be done, thanks . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This is a job, for real experts and, hard - core coders . . 👍 
### Is there a reason why this should be core and not an add-on in the asset library?
Not, sure . . :(( Thanks . . .

**Comment by SIsilicon** [comment]
Wouldn't it be better if you just use C# or GDNative to begin with?

**Comment by mrjustaguy** [comment]
1st off This is the VS<->GDScript conversion.. Not going to happen anytime soon (if ever) as it's hard to convert from 1 to the other, and there aren't enough users that use VS (especially those that'd care about that)
2nd off VS and GDScript have roughly the same performance (Ignoring G4's Static GDScript), Idk why you'd want to convert from one to the other with performance in mind, however C is faster when compared to GDScript...
3rd and final, Visual Script and Top Performance don't mix, especially when you consider that most people using VS don't know a thing about optimization which is VERY important for very fast code. 
I mean hey, a Well made Algorithm brought to life in GDScript can run circles around a bad Algorithm brought to life in C++

**Comment by jasperbrooks79** [comment]
I don't think I'll ever make anything, WRITTEN in native, but like Unreal compiles blueprints to, C# and, Unity translates their visual scripts, LIVE, to C#, on the screen . . I was thinking, why not make it so Godot translates visual script into GDNative or, C# . .

or, since the visual scripts, at SOME point get written into C#, or Native, so the CPU can ACTUALLY run it, it seems, might as well have the option, to do those things . . Unity being able to ' LIVE ' turn Bolt Visual scripts, into C#, means it's possible, it just needs to be able, to also write it out, as GDNative . . :OO that way, so cool, one could convert a Visual script into GDScript, C# or, GDNative, which would be something Godot does, that not ever Unreal or, Cry-engine does, and would make Visual script THE best experience, also for really pro teams, or a team of, artists, a game jam or, AA studios, that want to code fast, no hassle . .

It's possible to convert visual scripts into C#, Unity does it, then just ' add ' the C# script, to the node, when it's done, instead of the visual script . . but, convert to GDNative, would be the coolest thing, ever done . .

or, there could be a Visual script --- > GDScript, then the GDScript could converted, to --->> C#, then C#, can be converted to GDNative, so people can do as much converting, to a low-level or, hard-ware level language, as they want to . .

So, visual scripts has a button, convert to GDScript . .

then, when one opens the GDScript, it has, in the written script editor, convert to C#, live . .

then, if one opens the made C# file, there's an option, convert C# to GDNative . .

it won't work ONLY from visual script, but it would make it faster, and allow each user, going from visual scripter, to C# or, GDNative coder, to sort of see, an instant changed script, into the NEXT level <3 that way, it'd be an educational tool, but would also allow visual scripters, to get amazing performance or, when needed, thanks . . <3

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
