### ISSUE TITLE
Gradually remove `#include <alloca.h>`

### ISSUE THREAD

**Issue by yeeing** [godotengine/godot-proposals#2127]
### Describe the project you are working on
play
### Describe the problem or limitation you are having in your project
alloca.h file is missing
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Replace all alloca functions into variable-length arrays
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`type *stack=(type*)alloca(sizeof(type)*n)` to `type stack[sizeof(type)*n)`
### If this enhancement will not be used often, can it be worked around with a few lines of script?
yes
### Is there a reason why this should be core and not an add-on in the asset library?
I am very happy to submit a PR if needed

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/42330.

**Comment by yeeing** [comment]
I found that alloca.h is used by other third-party modules except the core, and the removal work is too much. Is it better to implement an alloca() forwarding malloc()

**Comment by Calinou** [comment]
@vnen What's your opinion on this?

**Comment by vnen** [comment]
Any reason for doing this? AFAIK `alloca` is available everywhere. And yeah, VLA is not standard so I don't think it's a good replacement.

**Comment by Calinou** [comment]
Closing due to lack of support.
