### ISSUE TITLE
Godot Ai behavior tree editor

### ISSUE THREAD

**Issue by warriormaster12** [godotengine/godot-proposals#213]
- I'm working on a Doom style fps game where there multiple enemies that player has to fight against.

- Current limitation is that the engine doesn't have tools that allow designers to focus on creating behavior of the ai. Most things need to be done from scratch and figure out for yourself since there is no currently in my opinion good documentation available for creating ai characters in Godot using navmesh.

- Feature would allow designers to focus on creating believable behavior for the ai and there wouldn't be that big of a need to go under the hood.  

https://www.youtube.com/watch?v=27XFykjd8Ns

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
