### ISSUE TITLE
Add a keyboard shortcut to select the word under the caret in the script editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2134]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Selecting the word currently under the cursor takes more time than it should. You either have to:

- Reach for the mouse and double-click the word you'd like to select.
- Press <kbd>Ctrl + Left</kbd> to move the cursor at the beginning of the word then press <kbd>Ctrl + Shift + Right</kbd> to select the whole word.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Being able to select the word the cursor without reaching for your mouse can be a huge time saver.

In editors like Visual Studio Code, you can press <kbd>Ctrl + D</kbd> to select the word under the cursor. When pressing it multiple times, it will also select the same word if it's present elsewhere in the current file (but implementing this in Godot would require [support for multiple cursors](https://github.com/godotengine/godot-proposals/issues/245)).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- Implement <kbd>Ctrl + D</kbd> to select the word under the cursor as if you double-clicked it. I think using <kbd>Ctrl + D</kbd> makes the most sense as it's a common action and is the same shortcut as in Visual Studio Code.
  - When pressing <kbd>Ctrl + D</kbd> a second time, we could optionally do something such as unselecting the current selection. We can't implement multiple selections yet, so it would be nice to find something else to do that's still useful.
- Move the current Duplicate Line shortcut to <kbd>Ctrl + Shift + D</kbd> to avoid conflicts with the new shortcut.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as this is script editor functionality which can't be overridden easily (or at all).

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core usability feature.

**Comment by KoBeWi** [comment]
I don't get it. If the word is already under cursor, you can just double-click it. Why use a shortcut (which still requires to have the word under cursor)?

**Comment by pycbouh** [comment]
Maybe Calinou meant caret? And if so, I wish for a slightly different mechanic, the one present in IntelliJ IDEA and the rest of JB IDEs. Pressing, I think, Ctrl + W by default selects the token around the caret, with multiple presses extending the selection to a context encompassing the current selection. This is really handy when working with keyboard.

Adding a shortcut to select something under cursor, however, indeed seems redundant.

**Comment by KoBeWi** [comment]
> Maybe Calinou meant caret?

That would make more sense. Although IMO duplicating is more common that selecting word under caret, so it should use its own shortcut instead of replacing.

**Comment by Calinou** [comment]
> Pressing, I think, Ctrl + W by default selects the token around the caret, with multiple presses extending the selection to a context encompassing the current selection. This is really handy when working with keyboard.

I think this mechanic would make more sense in Godot since we don't have multi-cursor support yet.

**Comment by me2beats** [comment]
Selecting "words" under caret would be really useful.
As for shortcuts, I find (current) `Ctrl + D` quite handy for duplicating and use it often. Also this shortcut is well compatible with actions of other Editor contexts, for example `Ctrl + D` for duplicating nodes, etc.
So perhaps another default shortcut could be chosen.

After all, it might just be an empty shortcut. The user could assign it at any time.

**Comment by Calinou** [comment]
> As for shortcuts, I find (current) Ctrl + D quite handy for duplicating and use it often. Also this shortcut is well compatible with actions of other Editor contexts, for example Ctrl + D for duplicating nodes, etc.
So perhaps another default shortcut could be chosen for selecting words.

Remember that you can still use the same approach as Visual Studio Code or JetBrains IDEs to duplicate code. While not selecting anything, press <kbd>Ctrl + C</kbd> to copy the current line then press <kbd>Ctrl + V</kbd> to paste it.

**Comment by davidhorac3** [comment]
I'm afraid to ask... but is there any progress on this?
I've started to use Godot engine few days back and this feature is really missing.

Default shortcut is not important, as both D and W are already used -> so it does not need a default shortcut, but to be able to set and use it... that would be great. :)

**Comment by Calinou** [comment]
> I'm afraid to ask... but is there any progress on this?

As far as I know, nobody started working on this feature yet.
