### ISSUE TITLE
Add Dolby near quality sound processor or, effects . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2137]
### Describe the project you are working on
A Tomb raider game, about the ' Riders of the Apocalypse ' . .

### Describe the problem or limitation you are having in your project
I need state of the art sound re-production and, effects . . I was wondering if we could get Dolby certified solutions, they have a gitHub, with various stuff . . I need orchestras, massive sound effects and, almost, like in a cinema . .

https://github.com/DolbyLaboratories

![2021-01-17 0733](https://user-images.githubusercontent.com/61069740/104833067-60f5eb00-5896-11eb-9f57-a7a4aa944893.jpg)
^^ this, is what I need, or at least classic Dolby, the best you can find, or so . . .

Can this be included, as the official or, an add-on, if it's too much . . be really cool, if the Dolby logo, was in the audio editor . . I don't need full Dolby, but at least 95 % cinema ' blow your mind ' experience and, re-production, thanks <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Maybe add so, in project settings, one can select Dolby audio engine or, effects or, simply make it default, they have some stuff, that's already open source, need, the best, that's all <3 . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Make it an optional audio processor or, so, or make it default, based on what it already there . . Dolby Atmos support or, some-thing better, ya ya . . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't make it, I just need it, for some state of the art video - games . .

### Is there a reason why this should be core and not an add-on in the asset library?
Maybe, it should be optional, a plug-in or, a setting, in the Audio panel . .

Yes, please . . <3 <3

**Comment by jasperbrooks79** [comment]
No Dolby logo, or so . .
<img width="368" alt="Skærmbillede (918)" src="https://user-images.githubusercontent.com/61069740/104833195-250f5580-5897-11eb-84db-b06cb1c0864e.png">

I need something close, to what Hans Zimmer makes, Superman - theme, Star wars, etc . . . :OO <3 . . .

**Comment by jasperbrooks79** [comment]
If I can't get Dolby, I need the second - best audio engine, in the world . . basically, need 98 %, of what the full, latest Dolby system, can make, full support would give me, all I need, thanks . . . :OO <3 . . .

**Comment by Calinou** [comment]
Dolby is proprietary technology. We can't integrate it in Godot officially, but nothing prevents a third party from creating a module.
