### ISSUE TITLE
Implement grayscale lightmap baking to decrease memory usage and storage requirements

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2142]
*Originally suggested by @danilw in https://github.com/godotengine/godot/pull/44628#issuecomment-758283996. Pinging @JFonS as he implemented the CPU lightmapper.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Right now, the 2 lightmappers we have (CPU in `3.2` branch and GPU in the `master` branch) can only bake in color. You can disable HDR to decrease memory usage and storage requirements, but you lose the ability to have bright lights and it makes the scene look more bland overall.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The lightmappers  could allow baking grayscale lightmaps to decrease memory usage and storage requirements. This is useful for mobile or space-constrained games (HTML5).

For lights whose bake mode is set to **Indirect** (the default), the visual downgrade of baking in grayscale will probably be only slightly noticeable unless your scene has very colorful surfaces the light can reflect on.

Obviously, for lights whose bake mode is set to **All**, they won't be able to have any colors anymore. This may still be sufficient for some people (or those working on games with a low-color aesthetic). We could display a node configuration warning depending on the scene configuration to remind users of this :slightly_smiling_face: 

I doubt baking in grayscale will improve bake times noticeably, but you get other benefits such as the ones mentioned above anyway.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a **Grayscale** boolean property to BakedLightmap which affects the next bake.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as this is core rendering functionality.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core rendering functionality.

**Comment by JFonS** [comment]
Sounds like a good idea, adding it to my backlog.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/46054.
