### ISSUE TITLE
Make ability to import a ' Navigation mesh ' that one has made in 3D DCC . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2143]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I need to begin using navigation meshes, and I can already bake a navigation mesh, pretty easily, but the results are a bit well, chaotic . . I was wondering, if one could not simply make a ' self ' made navigation mesh, into Godot, made in Blender, so stairs, slopes, and all that stuff just, fits, immediately . . and if the new glTF scene exporter could export the baked navigation mesh into Blender, it's just 100 % easier, to manually make it, if one wants that amazing attention to detail . . 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add in Navigation meshes, one can plug in, a custom made one, as well as just bake it and, maybe using new scene exporter, to be able to send it into Blender, for that last touch, or so . . :OO  

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Like, in a Meshinstance, where one can use pre-set shapes or, plug in a custom made one, from Blender, so one can either ' bake ', for a fast result, or make a custom one, in Blender, especially nice if one could send a ' bake ' navmesh into Blender, then edit it there, so everything just ' fits ', optimally . . :OO <3 . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I have no idea, how to do that, sry . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, we want the BEST navigation meshes, for our games, always . . Having this option, might make them better, and any small errors in a baked nav mesh, can easily be fixed, manually . . . Thanks <3

**Comment by Calinou** [comment]
This is already supported by having an object with the `-navmesh` suffix in Blender: https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_scenes.html

**Comment by AbrahamBrookes** [comment]
For posterity, the link above has 404'd but you can find the info here: https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_3d_scenes/node_type_customization.html#create-navigation-navmesh
