### ISSUE TITLE
Make Godot capable of rendering high - production value images to the disc or, drive . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2145]
### Describe the project you are working on
A Tomb raider game, with demons or, such . .

### Describe the problem or limitation you are having in your project
I need to make some pre-rendered cut-scenes, and Godot can already make amazing graphics . . but, it would really help, if I could make some near - movie quality scene, that run at may-be 2 - 3 FPS, and then render each frame, as a .jpg or, .mpeg, to an external place, and then re-play them in Godot, as a recording, or ' pre-rendered ' . . this would mean, I could keep the same textures, lighting conditions, as the normal game, and the animations, could be ' key-framed ' in Blender . . The problem is, re-creating the same lighting conditions in Blender is tough, and often well, gets tough . .

Since animations can be made, from images alone, it'd just be a feature that allows a recording, that runs at say 0.5 - 2 FPS, bec. of the complexity, to store each frame, sequentially, as either images or, even a movie format, so the images can be put together, in a video software, and then be replayed in Godot, at 60 FPS, or so . . like in Blender, where you render an animation, and each frame takes maybe 30 seconds, then it puts it together, as a smooth animation . . I think, if Godot could render images alone, it's fairly easy to use another program, to ' put them ' together, ie. all it needs to do, is take a ' screen - shot ', of each frame . .

This would help get a near perfect semblance of, light, shadows, fog, to the real - time game, and be superb, I think . . <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, matching stuff in Blender, and Godot 100 % is very difficult, it'd be a feature that allowed one to render in - engine cut - scenes, without turning it into a movie production program, just be able to render each image, maybe of a scene where each tree has 100.000 poly, characters have 4K normal maps, textures, so on, and with effects like fog, so on, turned to high, SDFGI, the work, that would normally make game run at 2 - 3 FPS, anyway be nice to get the exact same look in cut-scenes, as the engine, at that time, thanks . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, like when Blender renders say, a 20 second animation, and it takes 10 minutes, to ' make ' all the images, then boom, you have a much nicer animation or, cinematic . . Having this ability, would help in matching lighting, textures, so on, in pre - rendered animations and, the actual game . . Prob. easier to just output each frame, as say a 2K png, like using Print screen button, or so . . also, for instance, for a cut - scene, where there are 20.000 soldiers, and animationplayers running, or so . . So, the game can make cinematics, like Blender, that 100 % match the look, of the rest, of the game, or so . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I have no idea, since adding a video compression format might be too much, simply being able to store each frame, as a .jpg or, .png in a folder, would solve it, the rest can be done, in free video editing programs or, so . . . <3

### Is there a reason why this should be core and not an add-on in the asset library?
Well, if it only outputs .png, then it'd be a fairly small add-on, and be a nice way, to make sure the lighting, fog, every-thing, 100 % matches the look, of the normal game - play, at run - time . . so, basically, one sets up a scene, with a ton of animations, then one presses PLAY, and the game begins to run, but it renders each frame, and stores them, to disc . . <3

**Comment by Calinou** [comment]
This is already possible using a script: https://github.com/Calinou/godot-video-rendering-demo

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP). Also, this functionality is best implemented using third-party add-ons which will also be more tailored to various specialized uses (such as [in-game photo modes](https://github.com/Calinou/godot-photo-mode-demo)).

Remember that for image or movie production, Eevee will still be significantly better-looking than Godot 4.0's renderer, even at maxed settings.
