### ISSUE TITLE
Add support for multiple atlases to the CPU lightmapper (already implemented in `3.x`)

### ISSUE THREAD

**Issue by NHodgesVFX** [godotengine/godot-proposals#2147]
### Describe the project you are working on
Playing with the new lightmapper

### Describe the problem or limitation you are having in your project
With large levels you cannot fit all objects on a single atlas this means you need to have 1 lightmap per object. in the tps demo this is over 1000 textures.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It would be great if when atlas is enabled it would put as many textures in an atlas a possible then roll over to a new atlass texture once it can not fit anymore in the current one. This way you can have maybe 20 4k textures instead 1000s of small textures.

I think 20 4k textures would be more efficient than 1000 smaller textures but if they have equal efficiency then this proposal isn't as important.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I described a bit how it should work above. I think this is always desirable so it should be always on. It could be made to be an option though

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
Lightmapper is in core, as this is an enhancement to the lightmapper it would also need to be in core

**Comment by Calinou** [comment]
cc @JFonS

**Comment by JFonS** [comment]
It should be doable, yes. I will take a look at it when I'm done with the more pressing issues :)

**Comment by KoxaKoxama** [comment]
> It would be great if when atlas is enabled it would put as many textures in an atlas a possible then roll over to a new atlass texture once it can not fit anymore in the current one. This way you can have maybe 20 4k textures instead 1000s of small textures.

This is exactly what I was hoping to see in new lightmaper in 3.3, unfortunately the way it currently works is kind of useless for actual projects with relatively large interior scenes. I understand that this approach is more complex but in the end this is the only correct way to do this.

**Comment by Calinou** [comment]
@KoxaKoxama To optimize frustum culling opportunities, you need to split the level into several meshes anyway. If your entire level is a single mesh, the level will always be rendered in full.

Splitting each room into its own mesh is usually a good way to proceed for interior levels. For large open world scenes, you can split with a grid-based approach.

**Comment by JFonS** [comment]
Allowing for multiple atlases would be nice, and I added it to my backlog, but it's not very high priority, so I won't be working on it in the near future. If anyone wants to give it a go, I'm happy to give pointers on what needs to be changed and where :)

In the meantime, remember that you can have multiple lightmaps in the same scene, so big scenes with multiple rooms can have one lightmap per room.  Splitting big meshes into smaller ones also helps as @Calinou mentioned, and you
 can also reduce the lightmap resolution to fit more objects in the atlas. Remember that you can use the "Lightmap Scale" property to give more resolution to specific objects that need it.

All in all, I think this is a good feature to have, just not high priority right now.

**Comment by KoxaKoxama** [comment]
Any progress on multiple atlases?

**Comment by Calinou** [comment]
> Any progress on multiple atlases?

As far as I know, nobody has started on working on multiple atlas support yet. JFonS is currently busy with other tasks, so it's not likely to happen for 3.5.

**Comment by JFonS** [comment]
Here is the PR for this proposal: https://github.com/godotengine/godot/pull/58102

I haven't tested it thoroughly, so any testing is welcome.

**Comment by Calinou** [comment]
This is now implemented by https://github.com/godotengine/godot/pull/58102 in `3.x` (will be in 3.5beta2). I'll leave this proposal open as this feature should also be ported to `master`.

**Comment by fire** [comment]
Forward ported to master by https://github.com/godotengine/godot/pull/61861.
