### ISSUE TITLE
BlendTree Node to interpolate between values

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#2148]
### Describe the project you are working on
Fighting game

### Describe the problem or limitation you are having in your project
I want to interpolate between rotations in the animations of a 2.5D fighting game.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
To allow AnimationTree 2D blend nodes to be used to interpolate the values of a variable, like having a certain rotation value set as the target of the animation 2D blend node, similar to how the tween node works.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
A node similar to the Tween node, but you can set diferent interpolation goals based on which current start value is closer to (Imagine a 3D sphere and your interpolation goal is the closest output goal you current value).

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It will be very useful as some kind of 2D blend lerp state machine.

### Is there a reason why this should be core and not an add-on in the asset library?
No, this is a core function.

**Comment by TokageItLab** [comment]
Closed by #https://github.com/godotengine/godot/pull/64924.
