### ISSUE TITLE
Make an option to increase saturation or, contrast on certain parts of color spectrum . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2151]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I want to make a game, that has option, to use 3D glasses, anaglyph glasses, there's already a plug-in, but the problem is, some parts of the spectrum, are sort of ' not ' good looking or, so . . like pale or, ' down - graded ' . . .

![2021-01-19 1718](https://user-images.githubusercontent.com/61069740/105061973-63189f00-5a7a-11eb-9363-2a3bb3c625ac.jpg)

The blue and, also green is ' muted ' . . If I increase the ' saturation ', it boosts all color, I was wondering if we could get a special way, so we can boost certain ranges, of the spectrum, like . . . >

![2021-01-19 1720](https://user-images.githubusercontent.com/61069740/105062766-4335ab00-5a7b-11eb-8d0f-02b84c6f2a32.jpg)

Most colors are at saturation 1, but some parts, of spectrum, are enhanced, so anaglyph 3D effect looks better, also it might be useful, in other games, where one needs complete control, over saturation range or, 'spectrum' . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Right now, we can use ' Post - proc ' effects, to make the ' light ' range blue, the mid-tones, more red and, the dark range, say orange or, green . . But, that only applies to the black - grey - white balance . . Could we get a new post - proc effect, that allows one to boost the spectrum, in certain places, want to see how good anaglyph 3D movies or, games can look, also might be fun, or useful in other games, not sure <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Like, a way to enhance the spectrum's saturation or, contrast, for SOME color ranges, like we can do color correction, but not on the black - white spectrum, but for certain, specific color ranges, or so . . Thanks <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I have got no idea, seems like it belongs, with the post - processing effects . . maybe call it new SpectrumTexture or, so <3 . . .
<img width="984" alt="Skærmbillede (925)" src="https://user-images.githubusercontent.com/61069740/105063418-01593480-5a7c-11eb-8813-1c7877ea8bcd.png">

then, one would have more control, over the games visual, want to see how good the anaglyph 3D looks, if it can to an extent, correct the loss of tones or, hues, bec. of the glasses, by boosting the ' faded ' parts, especially blue, orange, yellow and, green . . Thanks . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, not sure, it's for the engine makers to decide such things, those with tons of experience and, engine knowledge . . .

ps. having a ' SpectrumTexture ' as a default one, might be a nice addition, to Shader language, like one would assume, it should be there, or so <3

**Comment by Calinou** [comment]
In 4.0, you can use the new 3D LUT color correction feature to change how colors will look like.

As for chromatic aberration, this can likely be achieved using a third-party shader already.

**Comment by jasperbrooks79** [comment]
Thanks . .

might be a cool texture, to add to visual shaders, so one can choose entire spectrum, from red to blue, or maybe take a part, of the spectrum, like the green or, red, so one can have a setting, for a SpectrumTexture, how ' far ' it goes, on spectrum . . <3

**Comment by Calinou** [comment]
Closing, as this is already feasible with 3D LUTs in Godot 4.0 ([documentation is being added for it](https://github.com/godotengine/godot-docs/pull/6273)).
