### ISSUE TITLE
Emit a signal when a setting is changed in the Project Settings

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot-proposals#2155]
### Describe the project you are working on
Plugin

### Describe the problem or limitation you are having in your project
There's no way for a plugin to know if a project's settings have been changed. Currently the best way to use project settings is to re-fetch them at the point the setting is used. It's not feasible to do this for all types of settings, for example, a toggle for an operation that happens in the background. In my plugins I'm getting around this by polling settings on a timer, but that solution feels a bit ugly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
An extra signal called emitted through `EditorPlugin` (?) called `settings_changed`. Optionally we could include the key of the setting that was changed, but having the signal at all would be a great start.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
```
myPlugin.connect("settings_changed", self, "on_settings_changed")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?
You could work around this by implementing polling yourself. It's reasonably trivial, but this very much feels like functionality that should already be there. We already have methods for plugins to get and set the settings.

### Is there a reason why this should be core and not an add-on in the asset library?
Fixes a gap in existing core functionality.

**Comment by me2beats** [comment]
What about `ProjectSettings.settings_changed` signal (instead of `EditorPlugin` one)?
I also think some info on "what setting was changed" would be useful as well, so it could be `setting_changed` instead of `settings_changed`:
String `ProjectSetings.setting_changed()`
This would allow to do something like:
```gdscript
func on_setting_changed(setting:String):
    ...
```

**Comment by pycbouh** [comment]
Definitely should be a signal on the `ProjectSettings` singleton. It is exposed, no reason not to use it.

**Comment by pycbouh** [comment]
Apparently, https://github.com/godotengine/godot/pull/45956 added a `project_settings_changed` signal to `EditorPlugin` API. Should probably be manually backported to 3.x, because I don't think that this PR itself can be backported.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/53296.
