### ISSUE TITLE
Fix Visual script so it is as scalable as written coding, with a new feature . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2157]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
Currently, visual script doesn't scale well, since one has to draw really long arrows, to connect across a script, it's easier in written code, where one can define a VAR in the beginning, then 200 or, more lines later, SET or, modify it . . If we got a feature in visual script, so one could ' make ' lines, that are like this >>
<img width="821" alt="Skærmbillede (927)" src="https://user-images.githubusercontent.com/61069740/105141122-f690b500-5af8-11eb-944c-730685b0abc3.png">

Then, I think visual script would scale nearly as well, as written code . . the dashed lines in the picture isn't ' drawn ', when done, but to show how one can make connecting data across large scripts, much more easy . . :OO 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It would make it so, that one could much more easily send information across large visual scripts, and mean, it would scale almost as well, as written code, or so . . This becomes increasingly important, as scripts get larger . . To add to this, if one could ' divide ' the canvas, like with viewport, and one could drag and drop, between two areas, it'd be amazing . . >>
<img width="411" alt="Skærmbillede (912)" src="https://user-images.githubusercontent.com/61069740/105141562-a0704180-5af9-11eb-8b87-4da7bfbfff4a.png">
NOTE: the dashed lines aren't drawn, just to show, how it would work . . .

That way, it'd be super - easy to send data across large scripts, maybe when one drags out a port, and hold CTRL, or ALT, one could make these ' broken ' lines, that are still connected, in code or, so . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
A feature, where one can drag out a data port or, code port, and send it to different parts, of the script . . by double-click the point, one gets taken, to the other end . . last, if one port could have TWO such outputs, and appear in different places, it'd be amazing . . I think this would make visual script, in terms of scalability, as strong as written code, or close, Thanks . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Well, this needs to be written, so all users can use it, people that can't code the engine, or C# . . <3

### Is there a reason why this should be core and not an add-on in the asset library?
Well, we want the best, most amazing, cool Visual script experience, and this would be very useful, esp. for larger scripts, or so, <3 <3 . .

it'd be the same as dragging a super - long line, across the entire canvas, except it's not drawn, on screen, to easier connect or, send values, vars across large scripts, making it ALMOST like written code, that way, or so . . <3

all you'd need to do, to keep track of it was, write some comments around each port, and if one point became SEVERAL points, for output, when one CLICKS the original starting node, a little list appears, taking one to ' Point 1, Point 2, Point 3 ' or, node or some-thing . .
<img width="726" alt="Skærmbillede (928)" src="https://user-images.githubusercontent.com/61069740/105142858-5c7e3c00-5afb-11eb-9183-bb1f46ef0efe.png">

not sure if this only works for data lines or, code lines, also :OO . . like, the white ' logic ' ones, or so . . .

if we had this, Visual script would be much more flexible and, easy to ' manage ', or so . . . <3

**Comment by jasperbrooks79** [comment]
like, if one could create the ' end ' point, on the same canvas, but with different ' viewports ', like the 3D editor or, so . .
<img width="1617" alt="Skærmbillede (929)" src="https://user-images.githubusercontent.com/61069740/105143523-40c76580-5afc-11eb-8b48-898331f584aa.png">

I think, that would make visual script almost as good, as written code, that way, or so <3 <3

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
