### ISSUE TITLE
Standardize function overrides in GDScript

### ISSUE THREAD

**Issue by TheBeautifulOrc** [godotengine/godot-proposals#2162]
### Describe the project you are working on
Exploring Godot

### Describe the problem or limitation you are having in your project
I can't choose to override functions like `_ready`, `_physics_process`, etc. when extending classes in `GDScript`. 
I also have no say whether the code added to the child-functions is executed before or after the inherited code. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Re-implement the way function overriding works in `GDScript`. The main aim should be **flexibility and consistency**.

I do believe that **explicit is better than implicit**, however I can see an argument for implicit solutions being more convenient. Acknowledging this I propose one of the following two approaches:

1. All functions override the corresponding functions of their base-classes. In order to invoke the base-classes code you need to call it **explicitly** (this is how custom functions are handled at the moment). 
2. All functions invoke the corresponding functions of their base-classes **implicitly**, for the sake of convenience. Whether the invocation happens before or after the new code, should be clearly stated within the documentation. A new keyword `override` should be added that provides the functionality of `solution 1`, if needed. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Here is some pseudo-code describing the correct approach for both presented solutions:

Solution 1:
```
extends Base 

class_name Child


func _process(delta):
    # I can add code here
    super._process(delta) # could also be ._process(delta), Base.process(delta), etc.
    # I can also add code here 
```

Solution 2:
```
extends Base 

class_name Child


func _process(delta):
    # super._process(delta) could be executed here
    # I can add code here
    # super._process(delta) could also be executed here (at the moment it is executed after the new code)


# override-keyword makes it behave like solution 1 
# and gives the user more control
func _physics_process(delta) override:
    # I can add code here
    super._physics_process(delta)
    # I can also add code here 
```

NOTE: While I only used `_process` in this syntactic example, the goal is to make `GDScript` more consistent. This means whichever solution is chosen, it should be applied to both functions like `_process` as well as custom functions! 

### If this enhancement will not be used often, can it be worked around with a few lines of script?
At the moment the only way to emulate the desired behavior is to write custom functions that will be called from `_process`, etc. and being custom functions can be overridden properly. 

However this workaround is messy and inconvenient.  

### Is there a reason why this should be core and not an add-on in the asset library?
The way this is currently handled is inconsistent. An overhaul would benefit all users of `GDScript` (which are a overwhelming majority of Godot users).

**Comment by Calinou** [comment]
This behavior was already changed in the `master` branch.

**Comment by TheBeautifulOrc** [comment]
Just for future reference, is there any place where I can research what features have already been implemented on master (other than digging through commit messages)?

**Comment by Calinou** [comment]
> Just for future reference, is there any place where I can research what features have already been implemented on master (other than digging through commit messages)?

Not really. I recommend trying out the `master` branch before opening a proposal.
