### ISSUE TITLE
Expose the Completion properties and functions for text_edit

### ISSUE THREAD

**Issue by greencloversguy** [godotengine/godot-proposals#2168]
**Describe the project you are working on**

A plugin for making flagged conversations for a text game, coded in GDScript,

**Describe the problem or limitation you are having in your project**

If I want to include an auto-complete option for keywords which works similarly to the auto-complete in the script editor, I need to create myself from scratch, despite the source code for text_edit having functions and properties to handle completion.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation**

Expose the following properties in the editor, to allow developers to use them. 

	Set<String> completion_prefixes;

	bool completion_enabled;
	
	List<ScriptCodeCompletionOption> completion_sources;
	
	Vector<ScriptCodeCompletionOption> completion_options;
	
	bool completion_active;
	
	bool completion_forced;
	
	ScriptCodeCompletionOption completion_current;
	
	String completion_base;
	
	int completion_index;
	
	Rect2i completion_rect;

	int completion_line_ofs;

	String completion_hint;

	int completion_hint_offset;
	
	void set_completion(bool p_enabled, const Vector<String> &p_prefixes);
	
	void code_complete(const List<ScriptCodeCompletionOption> &p_strings, bool p_forced = false);
`
These can be found here: [https://github.com/godotengine/godot/blob/2abe996414b8b551e69e29461de3ff1bcaf5a28f/scene/gui/text_edit.cpp](https://github.com/godotengine/godot/blob/2abe996414b8b551e69e29461de3ff1bcaf5a28f/scene/gui/text_edit.cpp)
In addition, expose the ScriptCodeCompletionOption structure, so it can be used to create resources for the completion. 
By exposing these, they can be used by the developer to create their own unique completion settings and, with the completion_enabled property, allow it to be used in their own text editor. This may be used in plugins but also in games which ask users for text input. 

**Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams**

I don't know how to expose C++ properties and functions, however as a majority of other properties and functions are exposed, the same process can be used for them. 
In the editor, as there are a lot of properties, they could be sorted into a submenu, like the attachment. 
![completion_text_edit](https://user-images.githubusercontent.com/35625742/105614765-5326f500-5dc3-11eb-82f0-72cb40fc9280.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?**

No, as it requires adding in new nodes. 

**Is there a reason why this should be core and not an add-on in the asset library?**

It already exists in the source code, it seems like it would be wasteful to build it from scratch as an addon.

**Comment by KoBeWi** [comment]
There is a recent PR that might resolve this: https://github.com/godotengine/godot/pull/45393

**Comment by Paulb23** [comment]
Closing as fixed by godotengine/godot/pull/45393
