### ISSUE TITLE
Lacking compute support (HTML5)

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#2177]
### Describe the project you are working on
A water depth & velocity simulation shader in 2D (from above).

### Describe the problem or limitation you are having in your project
I've run into many issues while dealing with Godot's shader language, and I wanted to start this post as part of my documentation of such. When dealing with the current shader implementation I feel like my hands are tied many times, which leads me to believe that the current shader implementation keeps Godot far behind other engines.

#### No compute support (or inconsistent)
I've been using a lot of compute shaders using Viewports & only clearing the screen on the next render. This is extremely useful for people making CA (cellular automata), however at present support in Godot is lacking or buggy.

An example of this can be [found here](https://github.com/tavurth/godot-game-of-life).

FBO (viewport) is not currently fully cross compatible to the WEBASM version of Godot, which means we lose portability.

<details>
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
See above

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This enhancement will affect anyone who has more than a passing interest in shaders.

### Is there a reason why this should be core and not an add-on in the asset library?
Shader language improvements must be core.
</details>

**Comment by Calinou** [comment]
WebGL 2.0 is a subset of OpenGL ES 3.0, which itself doesn't support compute shaders. This feature is impossible to support until WebGPU comes around, and that won't happen before 4.0 (if not later).

**Comment by tavurth** [comment]
Yep that makes sense why it wasn't working in the HTML5 version!

However I have found a workaround, as can bee seen at the end of the docs for [this project](https://github.com/tavurth/godot-game-of-life).

**Comment by Calinou** [comment]
@tavurth Godot doesn't have compute shader support in 3.x. Reading your proposals, it seems you're using particle shaders as a hack for compute shader functionality, hence the issue title I applied.

**Comment by tavurth** [comment]
Almost, I'm using canvas shaders (2d texture rendering, rather than vertex rendering), and yes I would say it's lacking, however this issue should still be relevant when moving to the new 4.0 backend. (unless work is done on this)

**Comment by clayjohn** [comment]
Are you saying that Viewports are broken in HTML5? If so, this sounds like it needs to be a bug report rather than a proposal.

**Comment by tavurth** [comment]
At the current moment a sprite which is a child of a viewport cannot set it's texture to the parent viewport in HTML5.

<img width="321" alt="Screenshot 2021-01-25 at 19 09 14" src="https://user-images.githubusercontent.com/100964/105731784-d28e0300-5f40-11eb-9ebf-004d9ec7ef38.png">

I guess you might be right, this could be a bug, but may be a limitation of the current rendering engine.

**Comment by Faless** [comment]
> I guess you might be right, this could be a bug, but may be a limitation of the current rendering engine.

Can you provide some information on your **OS and browser**?
And possibly a screenshot showing what is the result on other platforms on HTML5?

**Comment by tavurth** [comment]
<img width="773" alt="Screenshot 2021-01-25 at 20 40 48" src="https://user-images.githubusercontent.com/100964/105743571-9d3be200-5f4d-11eb-9977-fdd84201bcc8.png">

<img width="337" alt="Screenshot 2021-01-25 at 20 41 01" src="https://user-images.githubusercontent.com/100964/105743707-a462f000-5f4d-11eb-97f4-dafcdfd5a982.png">

<img width="911" alt="Screenshot 2021-01-25 at 20 42 21" src="https://user-images.githubusercontent.com/100964/105744195-d3796180-5f4d-11eb-9a86-cf1f809272fb.png">

Here's an exported template of [this repo](https://github.com/tavurth/godot-game-of-life)

[GameOfLife.zip](https://github.com/godotengine/godot-proposals/files/5868440/GameOfLife.zip)

Unzip then run `python3 -m http.server` from the folder.

The code works just fine in Godot, but when exporting to HTML5 it breaks.

**Comment by Faless** [comment]
Did you try other browsers?
See:
- https://github.com/godotengine/godot/issues/40842 (that is GLES2, but still viewport related)

**Comment by tavurth** [comment]
I tried just now in Firefox and it also does not work.
It could well be related to that bug as the workaround uses `SCREEN_TEXTURE` rather than the viewport texture.

**Comment by Faless** [comment]
I'm seeing the following warning with that project running in Firefox:
```WebGL warning: drawElementsInstanced: Texture level 0 would be read by TEXTURE_2D unit 0, but written by framebuffer attachment COLOR_ATTACHMENT0, which would be illegal feedback.```

**Comment by clayjohn** [comment]
This is very clearly a limitation of WebGL. I'm surprised it even works on desktop. 

To do GPGPU using framebuffers you should always use 2 framebuffers and rotate between them.

**Comment by tavurth** [comment]
@clayjohn interesting, so basically double buffering.
You would suggest swapping out the renderer between two viewports before each frame?

**Comment by clayjohn** [comment]
Essentially yes. 

Rendering to the same Viewport that you are reading from is not well supported (and I'm pretty sure the OpenGL specification forbids it). 

Instead you should use what is often called a "ping pong" approach. 

The Sprite under Viewport A reads from Viewport B. While the Sprite under Viewport B reads from Viewport A. 

Depending on your program the Sprite in Viewport B may simply just copy the contents of Viewport A into Viewport B (e.g. for simulating the game of life). While for other effects (e.g. blur) you may apply your effect in both Viewports. 

This is the approach you will find used in all OpenGL programs prior to the introduction of general purpose compute.

**Comment by tavurth** [comment]
Unfortunately this approach does not seem to be well supported in Godot either:

<img width="242" alt="Screenshot 2021-01-25 at 22 18 43" src="https://user-images.githubusercontent.com/100964/105754570-4a692700-5f5b-11eb-9011-d0200769ca82.png">

<img width="582" alt="Screenshot 2021-01-25 at 22 18 56" src="https://user-images.githubusercontent.com/100964/105754593-5228cb80-5f5b-11eb-8c39-9d79e754eabe.png">

However the project happily runs under these conditions, and works in the HTML Export also (with some visual bugs)

**Comment by tavurth** [comment]
It seems like Godot was not happy with the `Viewport` being picked from the Sprite's `Texture` drop-down menu.
I loaded the Texture from code and no more warnings, however this seems like another bug.

A third bug I seem to have run into is that the `Clear color` of the main Godot screen does not support alpha blending. If you set a clear color with `vec4(1.0, 0.0, 0.0, 0.0)` it will still render as Red.

**Comment by tavurth** [comment]
I will submit these as bug reports in time after I've tested a bit more.
For now I will mark this as closed since I was going about it wrong.

The demo is updated here:
https://tavurth.itch.io/godot-gpu-game-of-life

Thanks for your help @clayjohn @Faless!
