### ISSUE TITLE
Improve support for external shader editors

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#2179]
### Describe the project you are working on
A water depth & velocity simulation shader in 2D (from above).

### Describe the problem or limitation you are having in your project
I've run into many issues while dealing with Godot's shader language, and I wanted to start this post as part of my documentation of such. When dealing with the current shader implementation I feel like my hands are tied many times, which leads me to believe that the current shader implementation keeps Godot far behind other engines.

#### Inconsistent support for external editors
I'm primarily an Emacs user. Whenever I edit a shader file outside of Godot and I run the project, it exits with an impossible to debug C++ error. However when editing with the internal editor I have a line number error, which I can click to see the error.

This is frustrating, as Godot will **never** get me to switch from my primary editor, and so the inconclusive and confusing errors are a major barrier to entry.

<details>
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
See above

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This enhancement will affect anyone who has more than a passing interest in shaders.

### Is there a reason why this should be core and not an add-on in the asset library?
Shader language improvements must be core.
</details>

**Comment by Calinou** [comment]
This sounds like a bug rather than a feature request, but as far as I know, external editor support was never officially implemented for shaders.

**Comment by tavurth** [comment]
Ok I will post in the main repo after some time. I will finish up your comments on these posts first 👍

**Comment by Calinou** [comment]
Closing in favor of #1466.
