### ISSUE TITLE
Ability to init an array of specified size, pre-filled with a specified init value

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot-proposals#2181]
### Describe the project you are working on
I'm working on a large astronomy simulation ([I, Voyager](https://github.com/ivoyager)) and an associated space 4X game.

### Describe the problem or limitation you are having in your project
I find myself working with very many arrays of fixed size that need to be initialized with the value 0.0, or sometimes 0. It's only a few lines of code to do this (or really just a call to a custom static function). But if others do this even a fraction as much as I do, then it perhaps should be a core capability.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I would like to be able to init an array of specified size, pre-filled with a specified init value - using a core function. This is purely a convenience proposal.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
To init an array of size 10, pre-filled with value 0.0, this is what I'd like to work:

`var array := Array(10, 0.0)`

Edit: Based on discussion below, this proposal applies also to PackedArrays. I'm also very supportive of the `Array.fill(0.0)` method in addition to the constructor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I suspect this will be used often. If I'm wrong about that, then yes, it can be worked around with a few lines of code. 

### Is there a reason why this should be core and not an add-on in the asset library?
I don't think it can be done outside of a core change.

**Comment by arkology** [comment]
> it can be worked around with a few lines of code.

At the cost of reduced performance. So yes, this will be used often.

**Comment by Xrayez** [comment]
See also #2023.

**Comment by DarknessCatt** [comment]
I am working on this one. I will also try to add the constructor to the Packed*Array.
