### ISSUE TITLE
Refactor HTML template options

### ISSUE THREAD

**Issue by Faless** [godotengine/godot-proposals#2182]
### Describe the problem or limitation you are having in your project

Currently, the HTML template in `misc/dist/html/full-size.html` comes with a lot of strings to be replaced during the export process.
The number of this strings keeps growing as we add more export options, making it hard for user to create and maintain custom html pages.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The idea, is to group the flags together into just 2 dictionaries (INIT_OPTIONS, RUN_OPTIONS), so the minimal HTML template will be just few lines of code.

Init options:
- wasmExtension: Override extension of the wasm file (should we deprecate this?)
- unloadAfterInit: if the engine binary should be unloaded from memory after start (default true, useful to keep when you expect to run -> close -> run).
- progressFunc: progress callback function

Run options:
- canvas: The canvas to use for rendering
- arguments: Array of (extra) CLI arguments to pass to the executable
- size: If the canvas should be resized by Godot after start
- locale: Locale override (read by browsers otherwise)
- name: File/pck name
- stdout: Callback function for prints
- stderr: Callback function for errors
- onExecute: Callback function for OS.execute
- onExit: Callback function when the runtime shuts down.
- libraries: Array of GDNative libraries
- persistence: Array of persistent paths (default: `/userfs`)

Then the minimum HTML template will be:
```html
<!DOCTYPE html>
<html>
<head>
<title>$GODOT_PROJECT_NAME</title>
</head>
</body>
        <canvas id='canvas'>
                HTML5 canvas appears to be unsupported in the current browser.<br />
                Please try updating or use a different browser.
        </canvas>
        <script type='text/javascript' src='$GODOT_URL'></script>
        <script>
Engine.setInitOptions($GODOT_INIT_OPTIONS)
var engine = new Engine($GODOT_RUN_OPTIONS);
engine.startGame(); // Godot will use the first canvas if you don't specify one
        </script>
</body>
```

Overriding values in your template will be possible via one of the following method:
```javascript
startGame(runOverride, initOverride) // Init, Preloads the PCK (and gdnative), run pck (+ args)
start(runOverride, initOverride) // Init (if not inited), run args
init(initOverride)
```

What do you think?

**Comment by pycbouh** [comment]
Well, this is definitely a more familiar approach to configuring for web developer, so I guess it makes sense in the context.

**Comment by Calinou** [comment]
Will there be an export preset setting to allow adding our own values into the options dictionary?

**Comment by Faless** [comment]
> Will there be an export preset setting to allow adding our own values into the options dictionary?

No, or not right now at least. I see little use for it, but it could be done later on, I just don't see much benefit from it.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/46200.
