### ISSUE TITLE
New button to reset transform matrix / basis

### ISSUE THREAD

**Issue by FECU** [godotengine/godot-proposals#2185]
**Describe the project you are working on**
3d openworld game.

**Describe the problem or limitation you are having in your project**
After a model is imported, we are stuck with its orientation / Basis.IDENTITY combination in Godot. If, for example, the Basis.IDENTITY faces along the x-axis we are able to reorient it to face along the y axis within Godot.

I would like to be able to rotate it and have a "reset Basis" button. This would reset the Basis back to (1, 0, 0, 0, 1, 0, 0, 0, 1) - _without transforming the object_. This would also be very useful with scale, if an object is improperly scaled on import, this will affect child nodes usually in an undesired way and there is no way of correcting it from within the editor. The same is especially true of unwanted sheering.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation**
This gives a method of determining which way is UP / FORWARD / etc in relation to the mesh from within the Godot. 

Currently, if the object is not facing the right way / if there is an undesired scale /  etc, the only option is to revert to an external programme like blender, apply the transforms and then reimport the object which is labour intensive. The current system has zero flexibility once an object is imported into Godot.

Say the user had imported a character model which is facing on the x axis when the matrix is IDENTITY. When the user employs the `look_at` method, they get an undesired result. It may be that this issue is only discovered after the materials, scripts and so forth have been added meaning that fixing it can only be done externally and requires importing the model again and repeating much work already completed. 

My suggestion would replace all this work with a few intuitive clicks of the mouse: 

1) reorientate the obj as desired
2) click to reset the basis / transform matrix. 

It would allow the user to change the orientation of the object relative to its IDENTITY at will and so give Godot greater flexibility and it sorely lacking in the current build in my opinion.

**Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams**
Very simple feature: a single button that performs only one task. The button would be located in the inspector beside the matrix. Its only function would be to reset the matrix to (1, 0, 0, 0, 1, 0, 0, 0, 1) _without transforming the object._

With the example above of the character model facing on the x axis, with the new functionality the user simply rotates the model to face the desired negative y vector. The user than clicks "reset basis" which resets the basis from (0, 0, 1, 0, 1, 0, -1, 0, 0) [or whatever it happens to be] to (1, 0, 0, 0, 1, 0, 0, 0, 1) without moving, rotating, sheering or scaling the object from the present (desired) orientation. That's to say, only the Basis floats change, the object does not change in any way. The button's only function is to change the Basis to (1, 0, 0, 0, 1, 0, 0, 0, 1) and nothing else. Future transforms update the matrix as usual from the new starting point with no other change.

The usage us simple. The user sets the transform to the desired transform and then clicks to reset the basis. UP, FORWARD, etc are now redefined to taste.

**If this enhancement will not be used often, can it be worked around with a few lines of script?**
I suspect this would be popular. 

**Is there a reason why this should be core and not an add-on in the asset library?**
It would clearly be a core feature as it's a single button resetting the transform matrix.

**Comment by aaronfranke** [comment]
There are only two possible ways to solve this:

* Change the positions inside of the 3D model file. This is the best option IMO, but can't be done in-engine.

* Have a new "starting point" matrix and store it somewhere. This is what you want. However, there doesn't need to be an import setting for this. You can simply instance your 3D model inside of a `.tscn`, then transform the model inside of that `.tscn`. The `.tscn` then has the "starting point" matrix as the model's transform, and an un-transformed root node. You then simply need to instance the `.tscn` in your project instead of the model directly. Having an import option for this kind of thing would be not necessary and also confusing because then there would be an additional location to check to find the transform.

Closing because this is extremely easy to solve and doesn't need an import option (and having one would be confusing).

**Comment by FECU** [comment]
@aaronfranke I wasn't suggesting a new import setting or to store any new values... Perhaps I wasn't clear enough. I was suggesting the equivalent of "apply transform" in blender.

It's fine, I'll make my own build with the change, it's only one new function and one extra button, will only take a few minutes to implement.

Thanks
