### ISSUE TITLE
Ideas and improvements of the new sky shader . . 

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2186]
### Describe the project you are working on
A Tomb raider game . . With characters and, levels . . .

### Describe the problem or limitation you are having in your project
The new sky shader, that is in Godot 4, is simply amazing . . There's another thing, I hope it will support stuff like dark rain-clouds, white clouds and, perhaps a layering effect, so one can have say, a sky where there's ' fire ' or, an ' internal ' color, or so . .
![2021-01-26 0557](https://user-images.githubusercontent.com/61069740/105802412-655b8b80-5f9b-11eb-844e-6185e38cd806.jpg)

That would allow me to make an effect, I need to make about God being angry / skies raining fire or, so, for a part of game, where there's ' biblical ' disasters . . 
![2021-01-26 0600](https://user-images.githubusercontent.com/61069740/105802575-c08d7e00-5f9b-11eb-96fa-a891372f537a.gif)

Part of the story is, how ' heaven ' responds, when a nation commits big crimes, like bad wars or, large cruelty <3 This would really help me, get the ' final ' look, I need . . so, it looks like dark or, murky clouds with fire or, smoldering flames inside . . <3 <3 . . .

so, it looks like there are different ' colors ' INSIDE the clouds . . <3 or, layers or, gradients . . .

Also, I want to make a game, where the character flies ABOVE the clouds, so I was hoping the sky shader could also be put ' under ' the screen <3

![2021-01-26 0603](https://user-images.githubusercontent.com/61069740/105802796-3396f480-5f9c-11eb-8f31-f2b1d4558325.jpg)

In procedural sky, one can change ' color ' of upper and, lower, like sky and, ground . . if sky shader could also be applied ' beneath ' the screen, it could work well, for air - plane games, or so . . And, eventually, maybe one could fly ' inside ' the clouds, as well, but that's probably super - advanced, to do in ' good ' resolution, so that's prob. not possible, or so . .

![2021-01-26 0605](https://user-images.githubusercontent.com/61069740/105802893-722caf00-5f9c-11eb-8c62-11d37a2df3de.gif)

That's prob. like Godot 4.4, or 5 :(( . . But, it'd look cool, hope it can be done, since air combat games are cool, also flight simulator games <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, what I wanted most, is to be able to put the sky shader below the horizon, for a flying above the clouds part, of the game, I hope this is fairly simple, but don't know . . And, I need to be able to make clouds, with fire or, flames inside, so it looks like a sky, full of hatred and, rage :OO :OO . . it's since part of my story is, adding some ' biblical ' disaster stuff or, so . .>>
![2021-01-26 0608](https://user-images.githubusercontent.com/61069740/105803276-62619a80-5f9d-11eb-802f-b893f46cfc0f.jpg)

Last, not sure it's even possible, but if one could animate the clouds, so it looks like a storm or, big hurricane, ie. clouds fold or, ' billow ' . . These are ideas, and may be TOO performance heavy, or they could be done in scenes, where one only looks at the clouds, or so . . Need it, for a cut - scene, about consequences, of defying the UN and, starting 'evil', sick wars . . :OO that's the core theme, for the game, the ' plot ' or, story . . :OO it's about a game, after living in Denmark, following the Iraq war or, so . . I want to talk about, why illegal wars and, invasions are just bad, in fiction or, ' media ' <3 that's all . . . . anyway, it's just a cool idea, for a game, or so . . <3 <3 . . . .

Also, will the clouds perhaps support things like internal lighting, as a  toggle, so one can simulate lighting or, so inside the clouds <3
![2021-01-26 0618](https://user-images.githubusercontent.com/61069740/105803798-78bc2600-5f9e-11eb-8c87-8abe24d21fd4.gif)

Hope some of it can be added, and run some-what well, the current sky shader looks amazing, so cool . . <3 but, I'd like to be able to put it on the ' ground ' and, not ' sky ', so one can fly above them . . :OO

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Like, if the sky shader could be expanded, to be able to have a ' gradient ' or, layers, so one can create all kinds of effects, it could also be used to create all sorts of 'novel' and, also cool effects, in other games, to get a 100 % custom look, not sure . . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I use visual script and, I can't reprogram the engine, esp. C# :(( <3

### Is there a reason why this should be core and not an add-on in the asset library?
Well, if it was added as a customization option, but not set to on, in the default, sky shader, but as stuff below, that's an option, it'd be nice . .

ps. having a stylized sky shader, might be nice, for more ' toon ' games, but maybe that's easier to make, for each project or, too ' difficult ' to make into ' one for all ' shader . . :(( . . .

I need these things, for a game I'm making, but maybe others could use them, to create very unique or, ' custom ' looks, all kinds of clouds, green clouds, gas clouds . . if one could animate the clouds, so they look like a storm - front, on the dark horizon, it'd be super - good . . :O

**Comment by jasperbrooks79** [comment]
sort of, like this, where there's fire or, flames on inside, of the clouds >>>
![2021-01-26 0635](https://user-images.githubusercontent.com/61069740/105804744-d8b3cc00-5fa0-11eb-96d6-aeca8c09475c.jpg)

if one could animate the noise texture, maybe set it in low resolution, one could create these effects, mayb 128x128 or, 256x256 is enough, hope for it . . also, lightning inside clouds is, very cool, maybe some of these, are possible . . .

**Comment by jasperbrooks79** [comment]
last thing, to 'round' it off, was a storm so powerful, it lifted rocks or, even boulders . . so, if one could make a storm simulation, that applied forces to objects inside the storm or, wind, then one could apply those forces to rocks, and make some 'really' nasty weather . .
![2021-01-26 0708](https://user-images.githubusercontent.com/61069740/105807074-89bc6580-5fa5-11eb-8da1-0888d52058b0.jpg)

like, the worst nightmare, is a tornado or, hurricane that could lift large boulders, and throw them, like ping - pong balls, or so . .
![2021-01-26 0711](https://user-images.githubusercontent.com/61069740/105807206-dacc5980-5fa5-11eb-9555-bedf3d723a5a.gif)

it'd require some sort of physics simulation, approximate, inside the storm, and then having rocks be affected by them . . those are prob. the the ' wildest ' weather systems, I can image, can it be done procedurally or, using approximations . . :OO <3 Thx . . . .

**Comment by Calinou** [comment]
There's already a cloud texture you can apply to ProceduralSky, but its use is mostly intended for stars at night due to how it's blended.

**Comment by SIsilicon** [comment]
As for the clouds and other weather effects, those sound a little too specific to be added to core. Those could be implemented with whatever the editor already has.

**Comment by jasperbrooks79** [comment]
well, this is hard - core stuff, wanted to ask, since I can't make it, and some of it is too specific, unless it could be procedurally generated + ran fast or, so . . but, I wanted to ask, since the Godot devs and, core team often knocks it out of the park, and it might be like, sure, we get that stuff done in 2 days . .

on a note, if the sky shader also, could be a ' good ' night shader, perhaps with clouds, stars, so on, procedurally generated . . Godot is already a super - star release, for Godot 4, but the more options users have, the better it will be . . so, since there's a procedural sun, why not also make a procedural moon, and stars, one can move between, using PBR, procedural stuff . . that way, my vampire and, werewolf game can have a really nice ' night ' vibe <3 I guess the last stuff is fog, but that's already there, and ALSO improved in Godot 4 . . anyway, it might be fun for a contributor, to add some stuff, or make this stuff a plug-in, as a challenge, as physical -science based, as possible <3

I know you're working hard, and Godot 4 is already a done deal <3 . . but, these might be in Godot 4.2, or later, or so or, as plug-ins <3 Thx . . .

**Comment by jasperbrooks79** [comment]
it's working, in Blender, atm . .>

![2021-01-26 1754](https://user-images.githubusercontent.com/61069740/105876787-979ed480-5fff-11eb-818d-5b8a3a04e85b.png)

if it was PBR based or, close, and cover most or, all ' smoke / gas ' types, so cool <3

**Comment by SIsilicon** [comment]
Continuing my previous comment, since this can all be done within the editor, it can indeed be made as a plugin.
The clouds can be made with a shader, the falling rocks and fire can be made with a particle system, and the storm can be a combination of a script, procedural geometry, shaders and a particle system. In fact, I made a storm this way for a game jam.
If you think you can't do this yourself, you have two choices.
1. Man up and do your research on how this can all be implemented.
2. Ask someone to make a plugin for you.

It's a nice feature proposal, but remember that anything you ask for in the proposal is something you are asking to be in the core engine. If it can be done with already existing features and is not widely needed by the community, then a plugin is a better route.

Here are some plugins in the asset library that could get you closer to your goal.

- Cloud shader by arlez80: https://godotengine.org/asset-library/asset/797 ![](https://bitbucket.org/arlez80/cloud-shader/downloads/capt1.PNG)
- Kenney Particle System published by Calinou: https://godotengine.org/asset-library/asset/783 ![](https://raw.githubusercontent.com/Calinou/kenney-particle-pack/master/preview.png)

And of course there's the Godot docs. Some notable pages:
- Your First Shader: https://docs.godotengine.org/en/3.2/tutorials/shading/your_first_shader/index.html
- Particle Systems (it's for the 2D node, but most of the mechanics can be translated to 3D): https://docs.godotengine.org/en/3.2/tutorials/2d/particle_systems_2d.html
- Procedural geometry: https://docs.godotengine.org/en/3.2/tutorials/content/procedural_geometry/index.html

**Comment by jasperbrooks79** [comment]
You're right, these things prob. have to be made manually, bec. not many games will need a tornado, or so . . I'm not sure, it's not something that's in EVERY game ( though, it's very cool <3 ) . .

So, it has to be made, with other engine resources, I guess :(( . . . Sucks, wanted a real, simulated tornado, using kick - ass physics, but one can prob. just make it, like you say, Thanks . . .

**Comment by Calinou** [comment]
Closing per @SIsilcon's comment above.

We now have documentation on sky shaders: https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/sky_shader.html

A 3D sky shaders demo with volumetric clouds is also being worked on: https://github.com/godotengine/godot-demo-projects/pull/809
