### ISSUE TITLE
Support for two 4K monitors / making a pro /studio / production version of Godot . . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2195]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I want to build a much nicer nerd - cave, for my computer moments, maybe get a new HP Omen laptop, 2060RTX, on sale <3 I want to use two monitors, and I was hoping Godot could get support, so one screen could view the entire ' game ' world, full-screen, so I have a 1 - to - 1 preview ( don't want to waste time, running game first, sucks . . ) . . I wanted to ask, if Godot 4 or, 3.2 maybe get support, to have 3D preview run full - screen on ONE monitor, and the editor running on the other side . .>
![2021-01-28 0535](https://user-images.githubusercontent.com/61069740/106091249-493b2400-612c-11eb-98c7-586053c6e6ae.jpg)

I saw HP Omen 'valkyrie' laptop and, felt a craving, to upgrade . . <3
<img width="739" alt="2021-01-28 0533" src="https://user-images.githubusercontent.com/61069740/106091285-5e17b780-612c-11eb-9162-66c04118d57f.png">

Ideally, I'd want to be able to just ' see ' the game, full-screen, in one screen and, the code next screen, so I can 'constantly' see what my final game will look like, while editing . . I really not like, to have to wait, or even click full - screen, to see what I'm making, it's so slow, 10 - years ago <3 Thx . . 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Support for two monitors, with one side being a full-screen preview of the 3D editor window, and with a little button, like ' Camera ' preview, to toggle ' gizmos, and grid ', for fast iteration <3 . . I prefer efficiency and, speed when game deving, and right now, the Godot editor is holding me back :'( :'( . . Thx . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Support for two monitors, with one of them being a full-screen 3D editor window, for that 1 - to - 1 blazing fast game dev experience, ya ya . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I use visual script, I can't write C# or, do any engine work :( :( . .

### Is there a reason why this should be core and not an add-on in the asset library?
Yea, it's obvious . . Godot should be able to run on a cheap laptop, with one screen, but also scale up, to a semi - pro home game dev studio, to cover all use cases and, scenarios . . I want to feel like I'm controlling a nuclear sub-marine, or more . . when I game - dev <3 . . Thx . . .

it's about WYSIWYG and, fast iterations . . right now, I can't code and, see the game full-screen, at the SAME time . . Why, not . . . Sigh . . . being able to see my game full-screen, in the right resolution, and aspect, would take it to the next level . . since I use custom resolutions, often 1280x720p, it'd be nice if the full - screen preview could support different resolutions, for that 1 - to - 1 experience, in dev <3 it'd also make Godot more attractive, for really big studios . .

ps. can we soon get so, the debugger can have several windows, so I can print one output in one column, and another next to it . . so, the debugger can print more than one thing, at same time . . I want my nerd - experience, to be near supreme or, more . .

it's a bit silly, but I want to feel, like my little nerd ' heaven ', is all I ever wanted and, more, thx . . <3

**Comment by jasperbrooks79** [comment]
I really want, this here . . .
![2021-01-28 0603](https://user-images.githubusercontent.com/61069740/106092463-a33ce900-612e-11eb-9325-fec969c15ea3.gif)

want to be, in the Matrix, a lot . .

**Comment by jasperbrooks79** [comment]
like, this . .
![2021-01-28 0535](https://user-images.githubusercontent.com/61069740/106094957-37a94a80-6133-11eb-82fe-2ad39540e10b.jpg)

the nice thing is, many users already have an android phone, or a cheap tablet, and one could really make a custom environment, with some of the screen being portable, over bluetooth . . it'd be the most kick - ass game - dev environment, if one also could connect audio devices, like a keyboard, so on, to make music . . if Godot got a plug - in, where one could make chip - tune music, and connect to audio devices, it'd be the most professional game dev studio, in one package and, also had video editing software, again, as plug - ins . . to begin with, these things could be small add - ons, but in the end, it could be two versions, Godot Light, Godot Hard, Godot Epic, Godot Ultimate, or so . . or, so . .

maybe there are some open source music and, video editing last, is picture editing, that could be included, of course the size of the program would increase, and not all users would want more, than the basic edition . . so, if one could download a ' bigger ' version of Godot, with the packages one needs, Godot Enterprise or, Godot Studio PRO <3 also, it'd give the Godot devs something to do, if some devs needed the work . .

So, one can download Godot, and it runs on a tablet, with a bluetooth keyboard, or one could download it, and it runs on the craziest, most supreme hard-ware . .

**Comment by jasperbrooks79** [comment]
so, Godot could scale up, to a bit more, than this level, in audio, video, picture editing and, also code . .>
![2021-01-28 0649](https://user-images.githubusercontent.com/61069740/106095932-f6199f00-6134-11eb-8415-e9d4d133d97d.jpg)

that'd give you the most pro experience, so bigger studios might feel, or solo or, small team devs, Godot is the ' best ' place, to do anything . . <3 Thx . .

**Comment by jasperbrooks79** [comment]
the video editor should be able to turn videos into C64 palette, Amiga 500 palette, and make any video effect ever used, in a good video game . .>
![2021-01-28 0706](https://user-images.githubusercontent.com/61069740/106097313-61647080-6137-11eb-8a6c-41fae4743ac9.jpg)

![2021-01-28 0707](https://user-images.githubusercontent.com/61069740/106097320-63c6ca80-6137-11eb-9ded-52d025b68e15.jpg)

the picture editor should be able to convert to C64 graphics, from a image, and the sound editor should be a C64 + Amiga 500 music maker, combined . . so, one drops a sample in, and it converts it to a keyboard sound scale, C, C#, D, D#, E, F, F# . . and, support using tech, like this . .

![2021-01-28 0708](https://user-images.githubusercontent.com/61069740/106097495-b4d6be80-6137-11eb-8224-2052cbed9786.png)

so, you can make amazing computer music, or so . .

that'd be an amazing, wonder-ful version, of Godot, for more ' pro ' stuff, production . .

**Comment by jasperbrooks79** [comment]
last, since the tracks would be stored as ' notes ' and, samples, and just recreated electronically, it would lower the size, of sound data, meaning smaller published game data, this could be nice for web browser games . . :OO . . .

**Comment by jasperbrooks79** [comment]
now, imagine if someone made an iconic, supreme game or, in Godot . . and, at a concert, they started up Godot, and it ran the beats and, synths, and there was some-thing, like this . .>
https://www.youtube.com/watch?v=I8pg2XoQTlA

( Snake eater, mgs theme, live, with an orchestra . .

it all starts, with a simple, decent theme or, sound . . <3

**Comment by jasperbrooks79** [comment]
last, if you could ' set ' up the speakers, in a virtual room, so you could control how the sound ' rolls ', then one could make a system for say, a home surround system, where the sub-woofer has to be placed 2 m behind the user, and two small speakers in front . . but, one could also make a ' custom ' version, for a large symphony or, hall, by simply placing the speakers differently, and then control the movement between them . . that would be really nice <3

**Comment by jasperbrooks79** [comment]
or, imagine playing the world champion ship, in a Godot fighting game, in a place like this, with proper chip - tune sound . . :OO . .
![2021-01-28 0831](https://user-images.githubusercontent.com/61069740/106104897-5a435f80-6143-11eb-8e04-665f2bab2393.jpg)

chip - tune glory, all day . . <3 . .

**Comment by jasperbrooks79** [comment]
combining a show, with a little good food, and games for social progress and, justice . . and, perhaps a charity, where the tickets go to charitable causes also, online tickets . . <3

honoring the games, that has had the most important social messages and, content . .

that'd be, amazing . . <3 <3 . . .

**Comment by jasperbrooks79** [comment]
maybe the award could be a red or, white rose, or a little Godot head - man trophy, made of gold or, polished silver or, so . .

made, of gold, with name winner written in gold or, silver . . name, of game and, year . . <3
![2021-01-28 0913](https://user-images.githubusercontent.com/61069740/106108827-1a7f7680-6149-11eb-9a49-1fad1a23b4c0.jpg)

may-be with some victory laurels on, head something cool or, ' decent ' . . .

**Comment by jasperbrooks79** [comment]
it could be done live, with the cameras far back, so it's not about ego, or so far away, one can see the importance of, the surroundings and, crowd, people . . all that close - up vanity and, egotism, the cameras can sadly end up being about that, not the, public . . <3

**Comment by bluenote10** [comment]
@jasperbrooks79 It is good to see that you started using the edit button, but why don't you just add all that to the top post instead of adding more and more posts? That were again 12 emails :confused:

**Comment by jasperbrooks79** [comment]
> @jasperbrooks79 It is good to see that you started using the edit button, but why don't you just add all that to the top post instead of adding more and more posts? That were again 12 emails 😕

sry, I get too excited, over games and, too much . . I also have OCD and, mild autism, sry . .

**Comment by pycbouh** [comment]
While this won't come to Godot 3.x, Godot 4.0 introduces a way to create multi-window setups. Currently we can only pop out the docks, but there were plans to allow the same for the script editor. So I see no reason as to why the 3D editor's viewports cannot be given the same treatment. But this won't be a part of 4.0, I don't think, but rather be built upon 4.0 features in the later versions.

This feature is already tracked as a proposal too: #28.
