### ISSUE TITLE
Allow animation blends/transitions to be interrupted in StateMachine

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot-proposals#2200]
### Describe the project you are working on
RPG-like multiplayer with many npcs

### Describe the problem or limitation you are having in your project
Most of it is already described in this issue:https://github.com/godotengine/godot/issues/43570
The gist is that transitions in progress can currently not be interrupted. This prevents setting up good/professional looking animations as it is quite common to interrupt animations for gameplay reasons and certain transitions are naturally required to be longer.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Just having that be available/implemented will already be the fix.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
It could be an exposed option for transitions in blendtrees, statemachines and an argument in the play method of the animationplayer.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It cannot be worked around. 

### Is there a reason why this should be core and not an add-on in the asset library?
It's part of the core engine

**Comment by TokageItLab** [comment]
It will probably be an improvement to the [AnimationNodeStateMachinePlayback](https://docs.godotengine.org/en/stable/classes/class_animationnodestatemachineplayback.html#class-animationnodestatemachineplayback).

**Comment by Calinou** [comment]
Isn't this a bug fixed by https://github.com/godotengine/godot/pull/37001?

**Comment by Flavelius** [comment]
> So the problem is that you can't force a transition with fast x-fade by using the current start() of AnimationNodeStateMachinePlayback, right?
I'm mainly using travel(), but i guess start is the same; and if, by fast x-fade, you mean immediately beginning a new transition (with its own duration) from a current transition state (any point in time in that one's duration), then yes.

**Comment by YuriSizov** [comment]
@TokageItLab Is this something that is being worked on?
