### ISSUE TITLE
Prevent editing a container child's position and size in the inspector

### ISSUE THREAD

**Issue by 36k-wild-monkey** [godotengine/godot-proposals#2202]
### Describe the project you are working on
UI design 

### Describe the problem or limitation you are having in your project
If I use anchor for percentage layout, once I modify the margin or anchor of the topmost control, it will cause all child controls to automatically set the margin, and then the layout will be messed up 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
1. It is recommended to add an optional option to freeze or lock properties such as rect, anchor, margin, otherwise following the changes of the parent control will cause problems such as disordered layout 
2. Add new attributes: min anchor, max anchor, min margin max margin, min rect max rect

**Comment by pycbouh** [comment]
> If I use anchor for percentage layout, once I modify the margin or anchor of the topmost control, it will cause all child controls to automatically set the margin, and then the layout will be messed up

I'm not sure I understand your problem. Changing parent properties is supposed to cause a cascading effect on its children, that's in the nature of the parent-child relationship.

**Comment by groud** [comment]
For reference, this was implemented by https://github.com/godotengine/godot/pull/30623.
