### ISSUE TITLE
Connect signal by string and omission of parameters when necessary make problems to debug

### ISSUE THREAD

**Issue by bodamat** [godotengine/godot-proposals#2204]
### Describe the project you are working on
I'm creating 3d ball platformer. Ball what rolls on different platforms and avoid problems. These problems can be different: moving platforms, falling platforms, and else. In this game, I use signals a lot, because it's an easier way to communicate with different objects and not refer

### Describe the problem or limitation you are having in your project
Connect signal by string make problems to debug when changing the signal name. Also when we call the signal, the parameters can be omitted, even when it is very necessary.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
When we connect the signal as a function we will be able to see the error before we run the program. If we attach a signal as text, we will not see the error immediately until we get to the point in the game. So when we connect many and many connections, it will be harder and harder to catch this mistake.
The same thing happens with the parameters. When we declare a signal, we cannot describe the parameters, which very necessary.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
**Declare signal:**
```GDScript 
signal signal_name(parameter: String, parameter2: int)
```

**emit signal:**
```GDScript 
(Object).signal_name.emit(value, value2)
```

**connect signal:**
``` GDScript
(Object).signal_name.connect((Object).function_name)
func function_name(parameter: String, parameter2: int):
    pass
```
or
``` GDScript
(Object).signal_name += function_name  # I think this is a lit bit harder to understand
```

(Object) -> we use this when a signal in a different object / script. If in the same script we can use self or leave it empty.
Function name also would be really great without string. It's easier to debug

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes, but only for emit. We can create a function and call emit inside, but it doesn't work with connecting. So these such problems are still

### Is there a reason why this should be core and not an add-on in the asset library?
Because this function is in the core.

**Comment by Calinou** [comment]
First-class signals and callables are already implemented in the [new GDS
cript](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged) (coming to Godot 4.0, closing.
