### ISSUE TITLE
Add a node / music editor that uses a simple, custom - made synth for Godot game music . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2209]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I recently got a Sega Megadrive sound emulator, for my music program . . I wanted to ask, if we could get a custom little music and, effects maker, that works like C 64 / classic arcade sound emulator . .

https://www.youtube.com/watch?v=U6aOpFhO6zU

![2021-01-28 0918](https://user-images.githubusercontent.com/61069740/106378453-3da66200-63a5-11eb-9ae6-8b2e778bdcd5.png)

It basically just stores notes, and uses a simple sound - frequency modulator or, ' synth ' to generate computer sounds . . I really love the OLD, classic Amiga and, C 64 sounds, and was hoping, Godot could get a ' music / sound / theme ' tab, next to 3D, 2D, Script, Assetlib, where one can make nice computer sounds . . It's very small in size, and an advantage is, the ' scores ' are kept in a very small format . . it could be nice for web - games, and it could be fun, for Godot devs to make their own custom version of, a classic game synth, made only, for Godot, with a library of sounds and, effects, to get started . . it could also support samples, in wav, perhaps . . while it'd add a bit to the size, of the engine, perhaps 50 KB, or 100 KB, one could make 10 hour long songs or, compositions, that then only take up 50 kb, for each one . . Remember the old Amiga ' intros ' . .>

https://www.youtube.com/watch?v=sTx0Xrr5rvc

While one can make them in an external program, they have to be saved, as .wav or, .ogg, which takes space . . And, it could be an amazing challenge, to make a video synth, that was only for Godot, and ran in the program . . if we could also have a chord prog. tracker, it'd be complete, and a little synth visualizer >>
<img width="1156" alt="2021-01-28 0748" src="https://user-images.githubusercontent.com/61069740/106378535-fc628200-63a5-11eb-8697-d4ca45724e11.png">

![2021-01-31 0924](https://user-images.githubusercontent.com/61069740/106378549-1734f680-63a6-11eb-962c-8ef0c2399bec.jpg)

if it supported small samples, it could be endlessly customizable . . and, one could make any classic arcade sound effect, very fast, in Godot, and the size of the games, would be drastically reduced, in terms of audio or, music . .

Here's a Sega Mega drive game, aren't those amazing and, cool sounds . . .

https://www.youtube.com/watch?v=kLzblT3JWVU

The synth just creates frequencies and, layers . . Suppose we had 8 tracks, or 16, and some classic sounds, bass, drum, snare, and, where one can tweak each sound, by setting some simple settings . . <3 those are some of the prettiest and, cool sounds I ever knew, especially good, for say browser games, to lower download size . . the synth is just some math, that makes the frequencies or, so . .

![2021-01-28 0928](https://user-images.githubusercontent.com/61069740/106378624-a7733b80-63a6-11eb-8bca-4cf6c38740da.png)

Make, a special synth, modulator for Godot, that makes good video game sounds, all way back to, C64, arcade, etc . . it'd also run well on android, tablets, so on <3 and, give that ' classic ' video - game sound, prob. not be bigger, than 20 kb, the code <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, I love video - game music, this would be a cool feature, to emulate classic systems and, arcade ya ya . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add a ' music / score / sound ' bar, next to 3D, 2D, Script, which is a simple music track editor, maybe with support for small samples, etc . . specifically made, to re-make or, pay tribute to all classic video games, from way back when <3 <3 . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't change the editor, this much . . :OO :OO . . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it would be very small, and allow users to make the BEST, classic video game music, if it was done well, specifically made for Godot, paying tribute to all classic synths, in the best way <3

you could call, it Godot Power synth, or Godot Rage synth, something that can blast a stereo or, something cool . . :OO . . or, Godot Tempo Synth <3 . . :OOO . .

also, it could be cool, to try and make the ' ideal ' video game music ' synth ' looking back, at all the years <3 . .

**Comment by jasperbrooks79** [comment]
Axel F theme . .
https://www.youtube.com/watch?v=SlyK_elUmIw

I saw some C 64 tracks, the size is like 2 KB, for something like <3 just add more tracks, improve the synth, over time . . and, one can make amazing music, using a PC keyboard and, mouse, alone . . <3

**Comment by jasperbrooks79** [comment]
also, if it supported surround sound, so it was easy to send the sound, back and forth, between speakers, then one could create stuff, like a rolling effect, bass that, shakes the floor, so on <3 Thx . . since cinemas use 10 speakers, and one sub-woofer, if one could go that high, then one could make a video - game theme, that could be played back in a cinema, for like speed - runs or, big competitions . . :OO . . imagine hearing one's video game theme, blasting in a cinema, while players compete or, gather to play a nice, good game, together <3 . .

Cool . .

**Comment by pycbouh** [comment]
We prefer not to overburden the editor with features which are better handled by specialized tools. For example, [LMMS](https://lmms.io/download) is a good option for audio production. There are even VSTs that specialize on game sounds.

If someone wants to support some kind of editor like this in Godot, this is a perfect use case for plugins.

**Comment by jasperbrooks79** [comment]
I just felt it was cool, if in 5 - 10 year, maybe . . Godot Synth had become like, a ' classic ', and people could be like, man, that was done in Godot, with those nice sounds <3 . . same way, we feel about Mario theme today <3

**Comment by RichardEllicott** [comment]
i also would some sort of basic synth to support some quick oldschool style development

it's fun to make old fashioned looking tilemaps, it feels natural for this i should be able to make bleeps and bobs.... but i fear how on earth would the Godot team be able to decide on which synth to use?

at the moment let's be honest, this proposal is a can of worms and too complicated.... is there any sort of standard library out there that encapsulates this so the Godot devs don't have to invent it?

for example, "fluidsynth", is this appropriate? it is a SF2 based synth... i'd have thought since we had these in our soundblaster days, they used a synthesis model similar (with more channels) to these old consoles (they had setting similar to FM). I think that "sound fonts" allowed FM like stuff, and also samples to.

**Comment by Calinou** [comment]
@RichardEllicott [FluidSynth is LGPL-licensed](https://github.com/FluidSynth/fluidsynth/blob/master/LICENSE), which is too restrictive to be in core Godot. That said, nobody prevents someone from developing a third-party C++ module or GDNative add-on for it.

**Comment by RichardEllicott** [comment]
> @RichardEllicott [FluidSynth is LGPL-licensed](https://github.com/FluidSynth/fluidsynth/blob/master/LICENSE), which is too restrictive to be included in core Godot. That said, nobody prevents someone from developing a third-party C++ module or GDNative add-on for it.
> 
> It looks like someone started creating a GDNative add-on for FluidSynth, although it was abandoned: https://github.com/nonameentername/godot-gdnative-fluidsynth

there's no point now of taking up the challenge now, a shame they opted to use the Stalman license!

i doubt it's the easiest native thing to do either, having to stream back to the audio buffer.

**Comment by fire** [comment]
Please try https://bitbucket.org/arlez80/godot-midi-player/src/master/ and https://bitbucket.org/arlez80/godot-mod-player/src/master/ since these exist there's not much need to add to the core of godot.

**Comment by jasperbrooks79** [comment]
the point is, the Godot devs do AMAZING things, all the time . . technically speaking, the old arcade synths are basically just ' oscillators ' or, frequency makers, when you put a computer generated frequency into some SPEAKERS, it says BEEEEP, or other stuff . . same as, any recording is just, some frequencies and, amplitudes . .

![2021-02-03 0418](https://user-images.githubusercontent.com/61069740/106693518-f3a4c280-65d6-11eb-96be-64021308db39.png)

that's how all classic synth sounds are generated, from the arcades . . one just need to send the ' wave ' into the sound card, and it makes the ' sound ', like a grammophone or, tape recording . . a microphone records waves, in the air, and ' stores ' them on a physical medium, when they're played again, the SPEAKERS 1 - to - 1 makes the same ' sound vibrations ' . .

![2021-02-03 0421](https://user-images.githubusercontent.com/61069740/106693696-48483d80-65d7-11eb-8c44-31685e2c3dc8.gif)

so, to get started making a ' synth ', all you have to do is make some ' sounds ', that are sine waves, and send them to the sound card . .

Then, make a ' synth ', where you can change settings like hertz, amplitude, so on . . 

![2021-02-03 0423](https://user-images.githubusercontent.com/61069740/106693868-a412c680-65d7-11eb-8124-695f642368c1.png)

Start, by making a ' sine ' wave, and make the sound card output that ' signal ', in the speakers . .

Here's a tutorial . . It has demos of how a sine wave and, another type of wave ( box wave ) sounds, it's really cool . .

https://www.youtube.com/watch?v=v4XG_NHLWcs ( 8 minutes )

You can hear, those sounds are CLASSIC arcade sounds . .

then, all you have to do, to create ' new ' sounds, is do ' math ' on the waves, maybe sin ^ 2, or take a slower sine wave ( Hz ) and, add a faster sine wave ( fast Hz ), and then you get something interesting . .

it's super - easy to make, the question is, to make the sound card ' play ' the signal . .

Then, when you have a bunch of sounds, you could make say 10 presets, for a ' bass ', a ' beep ', etc . . that could become the ' classic ' Godot sound library, and the code would be very low, basically make sound wave ( sine curve ) and, send it to sound card . . then, over time, the Godot team could experiment with it, and make some sounds, that were made for ' Godot ', and in 5 - 10 years time, when someone makes a NEW game, people might recognize it, just from the sound, and say, THAT was made in Godot, my favorite Godot games growing up, had THAT beeep, THAT'S Godot . .

Like, the Mario theme <3

Then, when you make the ' synth ' interface, just add some knobs that change frequency, Hz, and even add weird stuff like ' Add ', ' Subtract ', ' Multiply ' . . Boom, you have an infinite amount of sounds, in 5 - 10 minutes . . <3

**Comment by jasperbrooks79** [comment]
a voice recording, is ALSO just some waves, when should speakers ' move ' in or, ' out ', up down . .

![2021-02-03 0442](https://user-images.githubusercontent.com/61069740/106695138-492e9e80-65da-11eb-80c7-7fccd9061e67.png)

it's just really complex, when it's a voice or, music recording, with real instruments . . but, that's basically just a ' signal ', tells the speakers when to push ' out ' or, ' in ', which makes the play - back . . it'd be super - easy to make, if one started with sine waves, then tried all kinds of math on the waves, to see what that does . .

then, one often add some presets, imagine if one's favorite game, growing up, had been made in Godot, and one could open Godot, and start ' using' those sounds . . it could become almost time-less, like Mario theme so, many, many good arcade games . . <3

over time, you can make, so one can add a ' sample ', drop a sound in, and then put ' that ' in the track or, chord - line editor or, so . . <3

Godot has it's own visual script, it's own 3D editor, it's own code language, GDScript, it's own little version, of what the other engines do . . but, I wish one could make chip - tunes in Godot, using an in - house, super - custom user - friendly interface, for fun . . 

Thx . . . <3 <3

**Comment by jasperbrooks79** [comment]
I updated the comments a ton, this is the proposal, added stuff in first and, second comment, since you get e-mails every time :OO ( I don't get e - mails ?? ! ) .. 

last, if you wanted your characters to have ' chip ' sounds, like when the speak, they say beeep-beep-blip-booom-beep-beep, one could make that, as well, to 100 % computer generated characters, also in SOUND - design <3 So good, Thanks ya ya . .

**Comment by Calinou** [comment]
Closing, as audio production of this kind is better suited to third-party tools. For MIDI output, see https://github.com/godotengine/godot-proposals/issues/2321.

**Comment by fire** [comment]
This proposal is also a less focused version of https://github.com/godotengine/godot-proposals/issues/3394 which is still open.
