### ISSUE TITLE
Add the ability to set the duration of individual `AnimatedSprite` frames

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot-proposals#2214]
* See #5311.

### Describe the project you are working on
A game.

### Describe the problem or limitation you are having in your project
It is not possible to set individual display time for frames in `SpriteFrames`. At the same time, similar functionality is implemented in `AnimatedTexture`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add a field where you can set an individual additional display time for each frame (as in `AnimatedTexture`).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![](https://user-images.githubusercontent.com/47700418/189182699-58e8e289-de04-4ae4-b8f2-477f5846cf78.png)
![](https://user-images.githubusercontent.com/47700418/189183983-f32aa2e3-880f-47db-8abb-d487c1c6be84.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
`Sprite` + `AnimationPlayer` can be used, but this is not the solution we want. 

### Is there a reason why this should be core and not an add-on in the asset library?
This is the basic functionality of the editor.

**Comment by Calinou** [comment]
> Sprite + AnimationPlayer can be used, but this is not the solution we want.

Why not? Sprite + AnimationPlayer is designed to handle all advanced use cases.

**Comment by dalexeev** [comment]
> Why not?

Not very convenient to use.

> AnimatedSprite only intends to fulfill basic use cases to remain easy to use.

This is a fairly basic use case. This feature does not complicate the use of `AnimatedSprite`. In addition, the same feature is implemented in `AnimatedTexture`, although it is also intended only for basic cases. 

> Sprite + AnimationPlayer is designed to handle all advanced use cases.

This is not an advanced use case in my opinion. As far as I know, engines like Construct and GameMaker have this feature.

**Comment by Crystalwarrior** [comment]
Since AnimatedTexture already defines this I also see no reason why this isn't part of AnimatedSprite's interface. It is legit just one slider per-frame for the delay, all programs that allow you to export gifs allow you to define per-frame delay, and it is inherently more complicated and annoying to have to copy-paste frames to lengthen a certain image rather than just have fewer frames with variable delays. I feel like it's a major oversight where the "more complex" solution for such a simple and uncomplicated problem only further creates a worse user experience, as this is an extremely common use case.

**Comment by Mickeon** [comment]
If I get my hands on refactoring **AnimatedSprite** as I want to do, after my other related PRs (https://github.com/godotengine/godot/pull/64155, https://github.com/godotengine/godot/pull/65148), this shouldn't be too difficult to implement, and potentially optimised in such a way that no frame duration is accounted for if not defined on any frame, and perhaps hidden from the user's sight by default (requiring ticking a box in the Editor to visualise it).

**Comment by dalexeev** [comment]
> My personal favourite solution to the "problem" is duplicating the frames themselves. It's not as costly as one may be lead to believe

The problem is not cost, but inconvenience. Duplicating frames allows you to use only integer proportions. And if you need to make one frame out of 10 with a duration of 0.5 relative to the others, then you need to double the remaining 9 (and also change fps animation), instead of specifying the length of one short frame. The greater the difference between the shortest and longest frames, the more frames are duplicated. This is a completely inconvenient and ridiculous workflow. So many people use `AnimationPlayer` instead. If we change this, then `AnimatedSprite` will become much more useful, while remaining fairly simple.

**Comment by dalexeev** [comment]
@Mickeon I have edited the OP. Now we need to make similar changes to AnimatedSprite if you have the time and desire.

Note that `AnimatedSprite` has `speed_scale` property, which is a common factor for all animations (to speed up / slow down the animation of the sprite regardless of the current animation), and each animation can have its own `fps`.

**Comment by Mickeon** [comment]
Give it its time. It would be non-compatibility breaking, and I need to think of a proper and tidy implementation someday so that the class isn't cluttered.

**Comment by dalexeev** [comment]
@Mickeon I opened PR:

* godotengine/godot#65609

**Comment by boruok** [comment]
3.x port possible?

**Comment by AThousandShips** [comment]
It broke compatibility in 4.0 so unless it's very different in 3.x it'd do that too and we don't want to break compatibility in 3.x

**Comment by Mickeon** [comment]
It did not. The PR originally started as breaking compatibility but the current code handles old SpriteFrames just fine. The label assigned to it is wrong.
https://github.com/dalexeev/godot/blob/0d25d8e7fcb9db82e2017de3ca5281fcd28ddcf5/scene/resources/sprite_frames.cpp#L204-L210

**Comment by Mickeon** [comment]
Also see https://github.com/godotengine/godot/pull/65700 which has been abandoned to the sands of time (for some reason).
