### ISSUE TITLE
Remember `Match Case` and `Whole Words` for `Find and Replace` in the editor

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot-proposals#2216]
### Describe the project you are working on
A large solar system simulator (@ivoyager).
### Describe the problem or limitation you are having in your project
When using Find or Replace in the editor (both file and global), I guess maybe 95% of the time I need to select Match Case and Whole Words. It's a nuisance that this is not remembered between sessions.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
[Edited from my original proposal regarding default selection.]
Match Case and Whole Words selection should be remembered in both file and global searches. I believe this will speed usage of find and replace for many developers.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Fully described in title.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not applicable.
### Is there a reason why this should be core and not an add-on in the asset library?
If this is popular with other developers, it should be base editor functionality.

**Comment by pycbouh** [comment]
I think remembering the last selected state is a better approach.

**Comment by charliewhitfield** [comment]
@pycbouh ,

I'll clarify my proposal. I don't think it is in conflict with "remembered" state. It's just about what the editor presents to you when you first open the file or first open global search in a given session.

**Comment by pycbouh** [comment]
> I'll clarify my proposal. I don't think it is in conflict with "remembered" state. It's just about what the editor presents to you when you first open the file or first open global search in a given session.

Your idea is clear as it is, but I'd argue that this is an arbitrary proposal based on anecdotal experience. Some users need to check the flags now, and some will have to uncheck them later. It's a much better flow to keep it as is and instead preserve the state the user has picked for all future searches.

From my personal experience, I never use `whole words` in any code editor, because it's usually faster to look for a substring of something. But I do enable `match case` from time to time. So, you see, this is a personal preference, which is why I suggest we address it as such.

**Comment by charliewhitfield** [comment]
I could be assuming too much about other developer's work flow...

Perhaps a better proposal is for user selection to be remembered between editor sessions?

**Comment by pycbouh** [comment]
I think it's fine to keep this one open and gather more feedback on it. We can always edit the OP and the title later. 

And yes, for the record, you are free to close your own proposals. We may still reopen it if we consider that the idea is nonetheless valid and the discussion is important to keep.

**Comment by Calinou** [comment]
Most editors out there don't enable match case and whole words by default. Remembering the previous state is a better approach to this problem.

**Comment by charliewhitfield** [comment]
@pycbouh & @Calinou,

I liked your suggestion better than mine, so I changed the title and feature proposal.
