### ISSUE TITLE
AppleTV Support

### ISSUE THREAD

**Issue by petergilmour1987** [godotengine/godot-proposals#222]
Hello, AppleTV support would make Godot games available to be released on the new Apple Arcade which requires the games to un on MacOS, iOS as well as the TV. The implementation would (I assume) be fairly straight forward as the tvOS API is essentially the same as iOS with exception of the input. Please make this happen.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
