### ISSUE TITLE
Add support for feathers, bones and, stone ' jewelry ' / stuff . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2222]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I want to make some physics based items, on some characters . .
![2021-02-02 0638](https://user-images.githubusercontent.com/61069740/106557038-3c9a3f80-6521-11eb-8912-9fcdfaf3d70a.jpg)

However, to make simulation of feathers, bone - jewelry and, small stones, on strings, ornaments, I was wondering if when one makes a ' skeleton - rig ', if one could select the bone, in the editor, and click some light or, 'fast' physics simulations, for beads on a string, bracelet, etc . . something with collision - detection, etc . .

I would like, if it could support stuff like feathers, bangles, bone bracelets, etc . .

![2021-02-02 0640](https://user-images.githubusercontent.com/61069740/106557214-a3b7f400-6521-11eb-8999-d8ac0e15079d.jpg)

if one could go into a ' bone ' list, for an armature or, skeleton ' node ', and check a list, to enable such stuff, it'd be nice . . <3 also, up a ' chain ' of bones, like for a bead, on a string <3 Thx . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, right now setting up the physicsbodies, is a bit too complicated, for me . . If one could ' toggle ' some general physics behavior, such as ' feather ', ' bone ' or, ' bead - string ', or ' bead - chain ', and it then applies physics, based on the global position, that could be cool . . :OO Thx . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
when one selects a bone, one can right now scale, rotate it, in Godot . . it would be nice, if one could ' add ' some ' preset ' physics or, so . . <3 Thx . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I have no idea, if one adds a rigidbody to the skeleton, it doesn't move anyway, if it was a setting, or so . . 

<img width="1252" alt="Skærmbillede (974)" src="https://user-images.githubusercontent.com/61069740/106557565-61db7d80-6522-11eb-8e54-852f31ab6e0b.png">

So, there was a setting, ' apply collision ' ( add collisionshape ), apply physics, apply wind, apply world physics . . it could be a list, or drop-down, then set weight and, gravity or, so . . <3

### Is there a reason why this should be core and not an add-on in the asset library?
Well, I'm a complete noob, and need a nice interface, to work with <3 . . . maybe, it's possible . . with these settings, one could simulate almost all kinds of jewelry, from light ( feather ) to, medium - heavy ( bone ) to, heavy ( beads, gold, stone ) <3 <3 . . Thx . . .

also, if one made a sort of ' global ' wind - simulation system, feathers would move naturally, or so :OO <3 . . . Thx . .

**Comment by jasperbrooks79** [comment]
also, if one could make a string of bones, maybe 2 - 4, work like elastic, string or, chain, so one could get ' bounce ', or so, that could be used for ' simple ' hair simulations or, so . . maybe better, if one could just add ' physics ', ' collision ' and, ' wind ' to a rig skeleton, on the bones where one needs it, and some simply collision shapes, box, sphere, triangle or, cylinder <3 Thx . .

the last part is, maybe ' add ' jiggle to a bone chain, so it can move, from side to side, not just along it's own axis or, 'jitter - chain' :OO Thx . .

**Comment by Calinou** [comment]
This is already supported using ragdolls and PhysicalBone.
