### ISSUE TITLE
Add minimum and maximum range properties for OmniLight3D and SpotLight3D

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot-proposals#2223]
### Describe the project you are working on
Dungeon rpg

### Describe the problem or limitation you are having in your project
I can't get the light to look like i want(i'm not aiming to realism).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Range min and max: similar to fog's depth begin and end, range min is the range where the light is at the maximum brightness, while max range is where the light end, a range min of 0 would result in the current lights. 
This is necessary so we can have bigger areas with maximum brightness, otherwise objects are never under maximum brightness unless we deal with energy values that modify the colors.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Min and max range values similar to fog's depth begin and end.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't think so, also lights are essentials so they are used often.

### Is there a reason why this should be core and not an add-on in the asset library?
Lights are core.

**Comment by pycbouh** [comment]
Please make an individual proposal for each feature or improvement you suggest and use more descriptive titles for them.

**Comment by 2plus2makes5** [comment]
Sorry!
I'll change now :)

**Comment by Calinou** [comment]
This is already supported in the `master` branch with the Size property in OmniLight and SpotLight.

**Comment by 2plus2makes5** [comment]
No sharp cutoff, on the contrary, the smoother the better! :)
