### ISSUE TITLE
Make attenuation's resulting look closer to its curve

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot-proposals#2224]
### Describe the project you are working on
Dungeon rpg

### Describe the problem or limitation you are having in your project
I do not exclude that it could be a problem on my end(i didn't mess with GPU and screen color settings thought), but i can't get to have a "linear" light, a light that fades constantly, instead even with the attenuation at 1 the light is mostly rather bright and then near the end it fades to black. I could use higher attenuation values but that also alter the resulting max and min brightness radius, so i should adeguate the range value making things more complex while i just want a light to have a certain range.

Lights with linear attenuation looks more or less like this:
![image](https://user-images.githubusercontent.com/35235318/106586988-58b1d700-6549-11eb-8d8d-476b78639036.png)

You can clearly see the circle where the light ends.

To me the light in first image here looks more "linear" with a softer edge:
![image](https://user-images.githubusercontent.com/35235318/106587390-d8d83c80-6549-11eb-8ec8-9b609d9556ce.png)

But the light results darker.

(The images are taken from the documentation)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The attenuation should look closer to its curve, if it's set to linear(value=1) i expect the attenuation to look more "linear".

Also consider the use of Curve Texture to specify the attenuation in addition to the current method.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
It's all about the implementation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't think so, also lights are essentials so they are used often.

### Is there a reason why this should be core and not an add-on in the asset library?
Lights are core.

**Comment by Calinou** [comment]
In 3.2, light attenuation *is* truly linear if it's set to `1` and you use linear tonemapping (which is the default). You can also disable HDR if you want to be even more sure of this, although I don't think it has a significant effect.


However, please understand that displays are not perfectly linear. Depending on how your monitor is calibrated, the light's appearance can vary wildly.

[Attenuation has already been rewritten in the `master` branch to be more realistic.](https://github.com/godotengine/godot/pull/44941)

There's probably nothing else we can do, so I'll close this.
