### ISSUE TITLE
Add version of signing in export settings Android

### ISSUE THREAD

**Issue by Summersay415** [godotengine/godot-proposals#2226]
### Describe the project you are working on
Any Android

### Describe the problem or limitation you are having in your project
I can't use new APK signing types (v2, v3, etc)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Switch from **jarsigner** tool to **apksigner**.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add some export options for Android(version of signing) and switch from **jarsigner** to **apksigner**.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It's export function

### Is there a reason why this should be core and not an add-on in the asset library?
It's export function

**Comment by Summersay415** [comment]
Another my proposal: #2107

**Comment by pycbouh** [comment]
> I can't use new APK signing types (v2, v3, etc)

Can you elaborate on that?

**Comment by Summersay415** [comment]
https://developer.android.com/studio/command-line/apksigner#options-sign where is links on signature schemes

**Comment by Summersay415** [comment]
Apk Signer already implemented, I think add version of signing logic.

**Comment by m4gr3d** [comment]
@Summersay415 Following on @pycbouh's comment, can you elaborate why you can't use some APK signing types? In general new versions are supposed to be backward compatible with older versions, so they all should be usable.
