### ISSUE TITLE
increase Light2D range_height cap

### ISSUE THREAD

**Issue by Lodugh** [godotengine/godot-proposals#223]
I am making a 2D game with dynamic lighting and normal maps.
However to achieve the look I would want with the normal maps I need a higher light.
I see no reason why it would be capped at 100. I think it should probably go up to a thousand. At least thats what looked useful to me in some tools that I used.
I would be super thankful for this little change!

**Comment by Calinou** [comment]
This was increased in https://github.com/godotengine/godot/pull/27448, but it wasn't cherry-picked to the 3.1 branch yet.

**Comment by akien-mga** [comment]
Closing as fixed.
