### ISSUE TITLE
Make Area2D just for detecting collisions, add a new node for physics and audio overrides

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#2234]
### Describe the project you are working on
Snake but it's a competitive 2d top-down shooter
### Describe the problem or limitation you are having in your project
I'm using Area2d's for the collision detection in my game. The problem is Area2D's have a bunch of unnecessary properties  that go unused most of the time (for overriding physics and audio settings). 
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think that the Area2D node should be simplified so that **it's only purpose is to detect collisions**, since most of the time that's all that anyone needs. For the times when someone does need to override the physics or audio 2d settings, I think **there should be a separate node** for that (**that inherits from Area2D**), called something like "OverrideArea2D" (or maybe we should also separate the physics and audio overrides into separate nodes, like "PhysicsOverrideArea2D" and "AudioOverrideArea2D").
 I think this will be beneficial because it will **declutter the inspector/documentation/api** for Area2D, since **most of the time Area2D's are just being used to detect collisions**.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
<img height="400" src="https://user-images.githubusercontent.com/50304111/106795087-e7d8f080-6616-11eb-90bd-a1a98aee91f4.png" />
<img height="200" src="https://user-images.githubusercontent.com/50304111/106796108-2c18c080-6618-11eb-9cb4-4bcdb9a89e8a.png" />

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
Because Area2D is part of core

**Comment by Calinou** [comment]
I'm not sure if it's worth the effort to split a node into two *just* to provide a simpler version. As far as I know, we don't do this in Godot anywhere else.

**Comment by LightningAA** [comment]
@Calinou I feel like it's like how VisibilityNotifier and VisibilityEnabler are seperate nodes. You could just export a bool called something like "enabled_when_visible" on VisibilityNotifier and remove the VisibilityEnabler node, but that's not VisibilityNotifier's job (I think it's called the single responsibility principle, but correct me if I'm wrong).

I also just realized this is also relevant for Area3D, should I edit this is issue to make it about both? Or should that be a separate issue?

**Comment by KoBeWi** [comment]
This could be done, but unless it improves performance, it's not really useful change.

**Comment by LightningAA** [comment]
@KoBeWi I mean it would save a few kb of memory if you had a bunch of areas... I mean it's an optimization, but one that'll have barely any impact. I just thought it didn't really make sense that the majority of the space in the inspector is taken up by properties that most of the time people don't even want, especially since I thought it'd be pretty easy to just make a new node for the times when you do want to override the physics and audio settings. Like in my snake game I'm making I'm using an area for the snake's collision, and it just makes no sense to have physics override settings in there. If you don't think it makes sense to change the node, then I think at least putting the physics override settings in their own tab that's hidden by default like the audio override settings.

**Comment by pycbouh** [comment]
This seems like a UX problem that can be solved by a better grouping of properties.

**Comment by LightningAA** [comment]
> This seems like a UX problem that can be solved by a better grouping of properties.

That would be an improvement, yes. My reasoning with suggesting splitting Area2D into 2 nodes is because it feels to me like it's 2 nodes squished into one; one that provides basic collision detection and one that provides local physics (and audio) overrides. If you just need to override local physics settings, then the current setup works fine, but if you just need basic collision detection then all the properties and functionality relating to overriding local physics settings feel totally unnecessary.

**Comment by LightningAA** [comment]
I still believe that it would make more sense to have a node just for collision detection and a separate one for local physics and audio overrides, but if most people disagree, then I think better organizing the inspector would be a good compromise for now. It could look something like this:

<img width="300" src="https://user-images.githubusercontent.com/50304111/107864508-052d6c00-6e1a-11eb-9161-2c5429eb9677.png">

**Comment by Shadowblitz16** [comment]
I actually wanted to make this exact suggestion.
The only difference to mine is suggesting a area and physics body hybrid as well

I think this issue could be fixed by supplying a new physics parameters resource to the area2d instead of having all the properties being part of the area2d. this way you would be able to wrap it out if needed.

**Comment by LightningAA** [comment]
I was reading [this](https://godotengine.org/article/why-isnt-godot-ecs-based-game-engine), and in it reduz says "Nodes do exactly one thing, so it's very easy to understand what a scene does by just looking at it.". I think this sums up my biggest complaint with how areas are currently set up, right now areas are doing 3 things, collision detection, local physics overrides and local audio overrides, which makes it feel pretty clunky if you just want collision detection.

**Comment by LightningAA** [comment]
A problem with this solution (if Area2D was split into an AudioOverrideArea2D and PhysicsOverrideArea2D) is if you need an area with both audio and physics overrides then you would need to create 2 different areas with the same collision box, which could be kind of annoying. I think maybe a better way to implement what I wanted would be to give Area array of AreaOverride resources (which physics and audio override resources would inherit). In the future a post processing override resource could also be added.

**Comment by Shadowblitz16** [comment]
@AaronRecord was this proposal dropped?
I would still like to see the extra properties put into their own node that extends from Area2D and Area3D
