### ISSUE TITLE
Allow using static and "global" functions when defining constants

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2235]
### Describe the project you are working on
Editor plugins (gdscript)

### Describe the problem or limitation you are having in your project
In some cases, I would like constants, such as script paths, to be defined depending on user settings, for example, config files, `ProjectSettings`, etc, to be able to use them in `preload()` for example.
Now there is no way to do this.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allowing to use static and global functions when defining constants would solve the problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
const icon_path = ProjectSettings.get("application/config/icon")
```

```gdscript
const icon_path = get_icon_path()

static func get_icon_path():
	return ProjectSettings.get("application/config/icon")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not possible now

### Is there a reason why this should be core and not an add-on in the asset library?
GDScript language related

**Comment by Calinou** [comment]
`const` is only designed to be used with variables defined at compile-time. The ProjectSettings singleton isn't accessible at compile-time and there's no guarantee that it will always return the same value.

**Comment by me2beats** [comment]
Thanks
