### ISSUE TITLE
Rect2 properties in the inspector should have 2 rows

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#2237]
### Describe the project you are working on
2D game, I sometimes use rects (like rect region or something)

### Describe the problem or limitation you are having in your project
So after the most recent inspector makeover the inspector was optimized to have more space etc. But then there are Rect2 properties, that feel really cramped. I mean, the input fields have only space for few digits. It's ok when you edit them because they expand, but when you look over these properties, you can't immediately tell the exact value.

This illustrates the problem really well:
![image](https://user-images.githubusercontent.com/2223172/106809936-94918d00-666c-11eb-86aa-05c5b275a52d.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It would be better if rect property field had 2 rows. One for x/y and one for w/h. It might take more vertical space, but it would be more readable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![image](https://user-images.githubusercontent.com/2223172/106811025-09b19200-666e-11eb-8026-d555dcded12e.png)
The relevant code is in `editor_properties_array_dict.cpp`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not really, no.

### Is there a reason why this should be core and not an add-on in the asset library?
That would require a custom inspector as an add-on.

**Comment by KoBeWi** [comment]
So I just discovered that there's an editor setting `horizontal_vector_types_editing` that affects few types.
![rabsNeH36q](https://user-images.githubusercontent.com/2223172/106937361-f3630f00-671d-11eb-94fb-46ab9a2a2578.gif)
Still, 2x2 would be more optimal layout IMO.

**Comment by fire** [comment]
There's dissent in having Vector4 and Vector4i show in 2x2 layout.

https://github.com/godotengine/godot/pull/80893#issuecomment-1688751568
