### ISSUE TITLE
ClassDB: capture nature of constants as being part of a bitfield

### ISSUE THREAD

**Issue by migueldeicaza** [godotengine/godot-proposals#2242]
### Describe the project you are working on

C# and Swift bindings

### Describe the problem or limitation you are having in your project

Currently constants are surfaced as enumerations, but some high-level languages like C# and Swift offer special capabilities for values that should be treated as flags, both during debugging and at the language level.

For instance:
```
[Flags]
enum ValidColor {
   Red = 1 << 0,
   Blue = 1 << 1,
   Green = 1 << 2
}
var myValid = ValidColor.Red | ValidColor.Blue
```

The [`Flags` attribute in C#](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-5.0) turns the debugging capability that would print "Red, Blue" as opposed as printing the value "3".   In Swift this [surfaces a different API](https://developer.apple.com/documentation/swift/optionset) that allows users to use set-like operations in the language 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add method hints to ClassDB to signal that would allow developers to flag constants in a group as being flags - that is, that they can be combined, as opposed to being alternatives or states.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`ClassDB::bind_integer_constant` would take an additional parameter that would flag the enumeration as being part of flags.   If any of the flags listed has this flag set, the entire enumeration is considered a flags enumeration. A new macro `BIND_ENUM_CONSTANT_FLAG`, peer of `BIND_ENUM_CONSTANT` could simplify that process.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is purely a matter of surfacing better language and debugging capabilities.

### Is there a reason why this should be core and not an add-on in the asset library?

It has to be on the core method database.

**Comment by raulsntos** [comment]
Was this implemented by https://github.com/godotengine/godot/pull/62374?

**Comment by migueldeicaza** [comment]
This has been implemented.
