### ISSUE TITLE
add an easy way to mask

### ISSUE THREAD

**Issue by DrAlta** [godotengine/godot-proposals#2243]
This is basically just a repost of [Issue 27482](https://github.com/godotengine/godot/issues/27482) on the new proposal tracker. I search for a way to do a dynamic mask but I doesn't seem it's been dealt with

### Describe the project you are working on

I'm trying to do a ASCIIpOrtal style portal rendering for the minimap/map editor.

### Describe the problem or limitation you are having in your project
I need to dynamically generate a mask for the area behind the portal.
There is talk that Light2D can be used to do masking but I haven't found any examples of even documentation of how to do that with Light2D.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add to CanvasItem the following

void draw_clear_mask(  )
Clears the custom mask for drawing via components. Anything drawn afterwards will be rendered normally.

void draw_set_mask( PoolVector2Array points, bool invert=false, bool antialiased=false )
Sets a custom mask for drawing via components. Anything drawn afterwards will be mask to inside, if invert is false(outside if invert is true), the polygon defined by points.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I imagine it would be as simple as drawing the polygon to the stencil buffer.

Or

The _draw() is called Create a Current, and Mask buffers and render draws to the Current buffer.
Then when the mask is changed render the Current buffer multiplying the alpha by the a Mask buffer on top of the CanvasItem's Texture then clearing the Mask and Current buffers and drawing the polygon to the Mask buffer.
When the _draw() is done Current buffer on top of the CanvasItem's Texture like you do when the mask is changed. free the Currrent and Mask buffers or save them for reuse.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No. 
If bug [Issue 29105](https://github.com/godotengine/godot/issues/29105) where fixed it would be thou.

### Is there a reason why this should be core and not an add-on in the asset library?
It needs low level access to the renderer.

**Comment by Calinou** [comment]
This is already implemented by https://github.com/godotengine/godot/pull/43167 for 4.0, closing.
