### ISSUE TITLE
Add a property to change the texture sampling mode for Decals, OmniLight3D and SpotLight3D projectors

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2247]
### Describe the project you are working on

The Godot editor (Vulkan) :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

There's currently no way to change the texture sampling mode used for decals and light projectors. This means all decals and light projectors use linear filtering with no anisotropic filtering. There are two downsides to this:

- The lack of anisotropic filtering will make decals look blurry when viewed at oblique angles.
- For 3D games with a pixel art style, decals will look blurry instead of being pixelated.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add property to change the texture sampling mode for Decals, OmniLight3D and SpotLight3D projectors (nearest, linear, mipmaps, anisotropic, …).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Ideally, this should be adjustable on a per-node basis. The Sampling property would have the same values as the one used in StandardMaterial3D. However, since decals and projectors are part of an atlas, I understand this may not be possible. In this case, this option would have to be exposed as a project setting and would affect all decals/projectors used in the project.

*Note that light projectors have to be reimplemented first: https://github.com/godotengine/godot/issues/45733*

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as Godot 4.0's decal rendering is implemented by the engine and can't be overridden in a script.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core renderer functionality.

**Comment by mrwolfyer** [comment]
It's 2026, version 4.5.1 and there is still no way to change the sampling mode of a Decal...

**Comment by Calinou** [comment]
> It's 2026, version 4.5.1 and there is still no way to change the sampling mode of a Decal...

This is already available since 4.0:

<img width="1199" height="375" alt="Image" src="https://github.com/user-attachments/assets/659b0e63-f3ff-48fa-b2c5-ffb0a10b4541" />

Note that this changes the filter mode for **all** decals in the scene. For performance reasons, there is no way to change the filter mode for a specific decal only.

As a workaround, you can use linear filtering and increase the resolution of decals you want to be pixelated in an image editor *with nearest-neighbor filtering* (no interpolation). This will make the decals *look* pixelated, as if they were using nearest-neighbor filtering in the engine, even though they're not. You'll probably need to use a 4x scaling factor, possibly more if the decal is seen from up close.

**Comment by mrwolfyer** [comment]
OH, how did I miss this??????

Well thanks, and sorry for the comment!
