### ISSUE TITLE
Allow `Remove Class Items` in `Theme` to remove a custom type

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#2251]
### Describe the project you are working on
Game Project

### Describe the problem or limitation you are having in your project
I renamed some of my `Theme` types/variables for better consistency, so I want to remove a dozen or so of them at the same time. I'd expect to be able to use the `remove class items` for this, but custom created types do not show up there. And neither does typing them out allow removing all items.

This is stange, as `Add Class Items` does show these custom types as options.
![image](https://user-images.githubusercontent.com/10502115/107076480-c846f100-67eb-11eb-8409-fc8a9afb32b5.png)
*Remove Class Items does not show custom defined types, while Add Class Items does*

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
`Remove Class Items` in the `Theme` resource should allow removing all set variables of a custom class.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I won't be used often I think. Removing an entire custom class is quite a rare scenario. Can be worked around my manually removing each entry in a custom defined type. However, `Remove Class Items` was clearly created to avoid having to do exactly that.

### Is there a reason why this should be core and not an add-on in the asset library?
Core: Expanded functionality of a Core Resource/function.

PS: I realise after writing this that this might actually be a **BUG**. However, the GUI does not give any indication that this **should** be possible but isn't, so therefore I'm going to assume this is simply an incomplete feature/a omitted functionality (since it is fairly rare that you'd want to do this in the first place).

**Comment by barbaros83** [comment]
godot for the most part is very easy to use and very intuitive, but the theme editor seems very chaotic to me, maybe this should be redone for 4.0, an interactive way of theming would be very nice, where you could click on the example gui and edit its theme properties
