### ISSUE TITLE
Add a configuration file listing addon/plugin files and directories to ignore during installation (.godotignore)

### ISSUE THREAD

**Issue by rehhouari** [godotengine/godot-proposals#2255]
### Describe the project you are working on
A mobile game where you pet cats.

### Describe the problem or limitation you are having in your project
Importing addons also import other unneeded files and ones that can't even read by Godot making them useless, like the `README.md`, Screenshots, etc.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Make a file `.godotignore` at the base of the addon repository that have what files shouldn't be imported when installing a plugin.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
**.godotignore**: a plain text file with each line being a path toa  file; similar to `.gitignore`.
**asset_library_editor_plugin.cpp**: checks for it and deletes the files that are mentioned *or* automatically deselect them in the package installer.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No it can't.

### Is there a reason why this should be core and not an add-on in the asset library?
Would have to create an addon importer from scratch.

**Comment by pycbouh** [comment]
What goes into the addon during the in-editor installation is defined by what goes into the zip-file generated by GitHub. You can use `.gitattributes` to define what goes there, like so:
```
/images             export-ignore
/.gitattributes     export-ignore
/.gitignore         export-ignore
/LICENSE            export-ignore
/README.md          export-ignore
/project.godot      export-ignore
/icon.png           export-ignore
/icon.png.import    export-ignore
```

Users also can select which files to copy during the addon installation, so they can filter unneeded files on their end.

Keep in mind that even for an open source addon you want to have a license file inside of your addon package.

**Comment by Calinou** [comment]
See https://github.com/Calinou/godot-addon-template for an example of distributing an easily installable Godot add-on. It's a template repository, so you can create new repositories based on this template in the GitHub repository creation dialog.

**Comment by rehhouari** [comment]
awesome! thanks for clarification ^^
