### ISSUE TITLE
Optimize deleting a bunch of selected files

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#2257]
### Describe the project you are working on
A project with files
### Describe the problem or limitation you are having in your project
When you shift/ctrl select a bunch of files (~100+) in the FileSystem and delete them, it takes a really long time, many times longer than if I were to delete the files and their respective import files directly from file explorer. Interestingly enough, if you delete an entire folder with a bunch of files, it's almost instantaneous, but if you instead select all the files in that folder and delete them it's incredibly slow. This isn't a big issue, but it seems like something that can and should be fixed.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I'm not familiar with the relevant code or how it works, but this seems like something that could be optimized quite a bit (deleting ~1000 16x16 png files froze my computer for about 3-4 minutes).
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Like I said, I'm not familiar with the code, so I'm not sure exactly what can or should be done.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
It's part of the Godot editor

Here's a bunch of sprites from Kenney assets for testing:
[sprites.zip](https://github.com/godotengine/godot-proposals/files/5938362/colored_transparent_packed.zip)

**Comment by Calinou** [comment]
The first thing to try is to remove the editor progress notifications when removing files, in a similar fashion to https://github.com/godotengine/godot/pull/35938.

**Comment by LightningAA** [comment]
Closing as it's pretty close to https://github.com/godotengine/godot-proposals/issues/280
