### ISSUE TITLE
Package the GUI lib to be used separately in C++

### ISSUE THREAD

**Issue by patlecat** [godotengine/godot-proposals#2258]
### Describe the project you are working on
stuff
### Describe the problem or limitation you are having in your project
none
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
admin ui
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
it'll be a GUI lib using the same elements as the Godot app itself, so in effect making the GUI features a module would suffice already (maybe that's already the case?) and then documenting it a bit and voilà!
### If this enhancement will not be used often, can it be worked around with a few lines of script?
no idea but i doubt it
### Is there a reason why this should be core and not an add-on in the asset library?
no idea, does it matter?

**Comment by pycbouh** [comment]
Sorry, but you did not provide enough information about a particular problem that requires a solution. Please refer to the [rules for submitting a proposal](https://github.com/godotengine/godot-proposals#rules-for-submitting-a-proposal) before actually making one. We can only discuss and ultimately act upon well thought out and detailed high quality proposals.

That said, GUI controls are tightly coupled with the engine and cannot be easily separated from it. Godot is a game engine and not a UI toolkit, so the effort of making any part of it independent from the whole package is not worth it for our end goal. Besides, you can make UI apps with Godot as it is (take a look at [Pixelorama](https://github.com/Orama-Interactive/Pixelorama) for example). That is the only way to utilize Godot's GUI `Control` nodes in your project fully.

**Comment by patlecat** [comment]
> 
> 
> Sorry, but you did not provide enough information about a particular problem that requires a solution. Please refer to the [rules for submitting a proposal](https://github.com/godotengine/godot-proposals#rules-for-submitting-a-proposal) before actually making one. We can only discuss and ultimately act upon well thought out and detailed high quality proposals.
> 
> That said, GUI controls are tightly coupled with the engine and cannot be easily separated from it. Godot is a game engine and not a UI toolkit, so the effort of making any part of it independent from the whole package is not worth it for our end goal. Besides, you can make UI apps with Godot as it is (take a look at [Pixelorama](https://github.com/Orama-Interactive/Pixelorama) for example). That is the only way to utilize Godot's GUI `Control` nodes in your project fully.

I did provide an answer to every question as you demanded, can't complain about that. The details are make a GUI lib that's a module to Godot and then it can be used also as a genuine GUI lib that would be awesome. I think that's rather clear and specific enough for this proposal at this stage.
I think for an opensource project it would be fair to let others in the community to have a chance to share their thoughts on this as well, not just 1 guy, right?

**Comment by Calinou** [comment]
See [this FAQ item](https://docs.godotengine.org/en/stable/about/faq.html#is-it-possible-to-use-godot-as-a-library). There are no plans to allow using Godot as a library as it would divert significantly from its design goals.

**Comment by Xrayez** [comment]
Please enable GitHub discussions for this as proposed in #2069. This issue is a clear example of open-ended discussion.

@patlecat you can take a look at #190 if you're interested in this topic.

> I think for an opensource project it would be fair to let others in the community to have a chance to share their thoughts on this as well, not just 1 guy, right?

Yes!

You may consider using Godot Ideas repository https://github.com/godot-extended-libraries/godot-ideas. Unfortunately, no decision-making is done to allow open-ended discussions to take place in GIP *officially*: #1476.

That said, instead of closing the issue, it could be moved to GitHub Discussions without much hassle:

![image](https://user-images.githubusercontent.com/17108460/107442035-f9525900-6b3e-11eb-97b7-9882d131c342.png)

**Comment by pycbouh** [comment]
> This issue is a clear example of open-ended discussion.

Unfortunately, this particular issue doesn't provide any ground for a any discussion, because no description of an existing problem was provided by the user. In fact, the exact opposite was expressed by them:

> **Describe the problem or limitation you are having in your project**
none

As such, there is nothing to discuss as there is no problem and there are no arguments in favor of the propose idea. There is only unsubstantiated demand.

**Comment by Xrayez** [comment]
> Unfortunately, this particular issue doesn't provide any ground for a any discussion, because no description of an existing problem was provided by the user.

That's the point. Ideas don't necessarily have a ground (nor a problem). I've seen even smaller openings on various forums which created long-standing discussions.

Lets say you're a member of a forum and create a topic such as:

> ## Do you believe in God~~ot~~? 🙂

This question alone can spring up a valid discussion. I understand that we'd like to have technical discussions, certainly, but that's just to demonstrate the nature of discussions.

Whether the discussion would be fruitful or not is irrelevant, that's the point of discussions.

**Comment by pycbouh** [comment]
> I understand that we'd like to have technical discussions

No, we'd like to solve problems, not ponder on mere ideas without burden of relevance. This is the basic for creating any feature proposal: providing any sense of relevance. **patlecat** failed to do so and explicitly stated that there is no reason for this feature to be implemented other than "*me wants*". I'm not even mentioning the disrespectful manner of communication on their part.

For philosophical debate on whether or not an idea holds its ground please use community channels. This is what they are there for: idle talk and chatter. Here people should come with an idea that was already proven to be worthy (by the virtue of need, not want) and with a concept of implementation.
