### ISSUE TITLE
Allow for buttons on SpinBox to act independently of step value

### ISSUE THREAD

**Issue by esijg** [godotengine/godot-proposals#226]
**Describe the project you are working on:**

I am working on a project which uses spinboxes in one of its GUI components, I would like to allow users to write floats with relatively high precision in the spinboxes.

**Describe the problem or limitation you are having in your project:**

The arrow buttons on Spinbox become relatively useless when one wants to have the ability to write numbers with high precision. For example setting step to 0.000001. 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

I would want to propose having the possibility to set the arrow button step and the spinbox step precision independently of each other so that one can write numbers like 0.8237 but jump up a whole number for example with the buttons.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

As far as I know, no.

**Comment by Calinou** [comment]
I suppose there could be an additional `arrow_step` property for this. If it's set to 0 (the default), it would be equal to `step` for compatibility with existing projects.

**Comment by johannesgunnar** [comment]
I have already started playing around with this and have it mostly working. One thing I am unsure about though is what would we want to be the expected behaviour when dragging on the spinbox arrows with left mouse button. Do we want it to follow the arrow step or should it allow for more precision?

**Comment by johannesgunnar** [comment]
I have taken the liberty to implement this and opened a pull request https://github.com/godotengine/godot/pull/33743

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/54792.
