### ISSUE TITLE
Animation Frame Signal

### ISSUE THREAD

**Issue by NickersWeb** [godotengine/godot-proposals#2260]
Animation 2D only has a couple signals. I would like the ability to signal at a certain frame rather then at the end. 

Perhaps on ready. While getting the node, you could set an array of frames/animations you would want the signal to happening. When you play a certain animation, it would signal at those frames instead at the end/beginning.

Would be useful when you have animations but the action is midway through the animation rather then at the end.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
