### ISSUE TITLE
Light2D nodes should not extend the selection bounding box of any parent node

### ISSUE THREAD

**Issue by Sephirothphoenix** [godotengine/godot-proposals#2268]
### Describe the project you are working on

I am working on a 2D platformer. It consists of many 2D objects, with a basic lighting system involving Light2D nodes.

### Describe the problem or limitation you are having in your project

Adding a Light2D node as a child of any parent node (With a texture, shadows/light settings irrelevant except for texture scale) causes the "Selection Bounding Box" (In other words, the rectangle or "collision" of the node that allows the node to recognize when it's being hovered over or selected in the UI) to grow to be as large as the texture of the Light2D node.

This causes an issue where the light node's selection box will override any other nodes within the vicinity, preventing them from being selected within the editor. For example, if I have a Lamp node with a light next to my Player node, I will be unable to select the player node as the selection bounding box of the Lamp covers up the Player.

This problem reduces developer efficiency due to constantly having to work around this problem, and severely reduces precision with being able to edit position and other properties of nodes with the use of the editor, especially as more nodes with lights are added to the scene. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

My solution would be to prevent Light2D nodes from extending the selection bounding box of any parent nodes they're attached to. There is no situation where extending the selection bounding box of a node to the size of the light's texture is useful, thus it should be changed to increase efficiency and productivity.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not sure how Godot is coded, but I would imagine something along the lines of this:

func setNodeBoundingBox():
  for x in Children:
          if x.nodeType == Texture or Collision:
                     boundingBox = x.boundingBox (The largest bounding box of any of these children)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no situation where this wouldn't be used.  There is no reason to have the bounding box of nodes extend to the texture of their children's Light2D node, as this only leads to inaccuracy, due to the nature of selection bounding boxes and their purpose (To allow for intuitively selecting nodes based on what you see). Even if there is some reason do to so, the change is very minor and a workaround would not be difficult to create.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a foundational problem within Godot's code, and negatively affects everyone using the game engine, even if they are not explicitely aware of it. Fixing this problem would help improve quality of life and efficiency, as well as reduce frustration caused by misclicking and unintentionally selecting nodes.

**Comment by Calinou** [comment]
As a workaround, you may be able to hide the Light2D nodes in the editor and display them in a script's `_ready()` function.

**Comment by Calinou** [comment]
@Sephirothphoenix Does locking the Light2D node resolve this issue? I don't think we can (or should) try to override the visible AABB for the purpose of editor selection. It's important to be able to know when objects can be culled from rendering, and the 2D selection box size is a good estimate for this.

**Comment by Calinou** [comment]
Closing per the above comment (and due to general lack of support for the proposal – see lack of activity).
