### ISSUE TITLE
Animation Frame Signal

### ISSUE THREAD

**Issue by NickersWeb** [godotengine/godot-proposals#2269]
### Describe the project you are working on
2d roguelike game.

### Describe the problem or limitation you are having in your project
Some animation signals need to be triggered on certain frames of an animation. Instead of at the end or beginning.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Ability to set multiple signals per frame of animation. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
potentially set the animation name and list of frames you want the signal to happen on in the ready method of the parent node to the animation node. Similar to the other signals, when that frame and animation is hit, trigger the signal. The dev could then simply switch case animation and frame. Here they could call other methods aswell.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
If this is an edge case. One work around could be to split the animation on the frame that you want to do your signal on and then call your other methods there and then also play the rest of that split animation.

### Is there a reason why this should be core and not an add-on in the asset library?
If possible, an add-on is fine. If it's useful, I guess core would make more sense.

**Comment by pycbouh** [comment]
You can call methods at specific points in your animation already. Does that not work for you for some reason?

![image](https://user-images.githubusercontent.com/11782833/107570438-8d352b00-6bfa-11eb-8ab6-630bdfaee9e9.png)

**Comment by NickersWeb** [comment]
Woah. I tried checking the documents and also asking the discord chat. I was told this wasn't possible. I just tried it myself and this does the job completely. @pycbouh  Thank you so much <3

**Comment by Calinou** [comment]
PS: This is a duplicate of https://github.com/godotengine/godot-proposals/issues/2260.

Please don't open proposals if you haven't gotten an answer to your support question. Instead, use one of the [community channels](https://godotengine.org/community).
