### ISSUE TITLE
The ability to get class icon from GDScript

### ISSUE THREAD

**Issue by Shatur95** [godotengine/godot-proposals#2270]
### Describe the project you are working on

I working on third person shooter.

### Describe the problem or limitation you are having in your project

In my game, characters have abilities. I want to add icons to them. GDScript has the ability to add [an icon to class](https://docs.godotengine.org/ru/latest/getting_started/scripting/gdscript/gdscript_basics.html#classes):
![image](https://user-images.githubusercontent.com/22453358/107577764-7f33da00-6bfb-11eb-8366-2903f6fbef9e.png)
And I want to reuse such icons in game, but I need to specify the path to the icon a second time separately.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice to have the ability to get script icon. NariveScript already have [script_class_icon_path](https://docs.godotengine.org/ru/stable/classes/class_nativescript.html#class-nativescript-property-script-class-icon-path) property, but GDScript do not have any method to access used icon. I suppose this is becase the feature to specify an icon appeared relatively recently (in version 3.1).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can access [source_code](https://docs.godotengine.org/en/3.2/classes/class_script.html#class-script-property-source-code) of Script and parse icon myself. But this is a bit hacky.

### Is there a reason why this should be core and not an add-on in the asset library?

I think this is impossible without a corresponding API in the engine :)

**Comment by SIsilicon** [comment]
Another alternative would be to read the project settings.
``` gdscripy
Project settings.get("_global_script_class_icons") # a Dictionary of class names mapped to icon paths
```

**Comment by Shatur95** [comment]
> ProjectSettings.get("_global_script_class_icons") # a Dictionary of class names mapped to icon paths

Did non know about it, thanks! But there is no way to get the `class_name` from the script to access the icon from the dictionary :(
