### ISSUE TITLE
UX comment (MacOS (MacBook air) and General)

### ISSUE THREAD

**Issue by invisiblesun** [godotengine/godot-proposals#2277]
### Describe the project you are working on
I am doing game development using godot 3.2 

### Describe the problem or limitation you are having in your project
There are several cases of Editor behavior I find very frustrating and disruptive of workflow.
1) (possible-bug) When using debugger next-step button from the editor, the mouse cursor jumps to mid editor screen on each step. This is visually disruptive and inconvenient when trying to step through a few lines of code of gdscript. I believe this may be due to my game grabbing the mouse cursor.
2) Scene tabs have their own Find context, but do not retain the script being edited. In my case I am often working on several scenes where I am editing the scripts of the _children_ of the scene. Clicking on a scene resets the editing script to the root node. I lose most of my context by having to constantly reload the file I was just editing.
3) Screen real estate on a laptop is at a premium. Being able to collapse the side panels would be very helpful. I don't often need the inspector for instance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I will focus mainly on issue 2. I think retaining the script file being edited to the scene editors solves this issue cleanly in the same way that the search terms of find and find/replace are unique and retained for each scene editor.
For issue 3, I feel that being able to collapse the side panels in the same way as the lower tray panel can be minified would be very helpful.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I don't think 2 this is too difficult to code. 3 have the ellipsis tab provide options to collapse and expand the dock. I think double clicking the vertical ellipsis should minimize and maximize the dock.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Anyone editing more than one scene that has child node scripts will benefit. And easy means to manage screen real estate has obvious value.

### Is there a reason why this should be core and not an add-on in the asset library?
Yes as part of the editor basic workflow.

**Comment by Calinou** [comment]
Please open individual proposals for requested features instead of lumping them together in the same proposal. This makes it easier to track the implementation status of each feature 🙂

**Comment by invisiblesun** [comment]
Thanks. I already use distraction free mode. I made comments on the (closed) proposal. But I will stress that assuming people have a multi monitor environment when they have a laptop doesn't feel right.
