### ISSUE TITLE
Mesh Shader support (opengl, vulkan)

### ISSUE THREAD

**Issue by romulasry** [godotengine/godot-proposals#2281]
### Describe the project you are working on
I am not working on this I just thought I just post this here
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
https://www.geeks3d.com/20200519/introduction-to-mesh-shaders-opengl-and-vulkan/

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
