### ISSUE TITLE
Add Volume Calculations to Meshes

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#2293]
### Describe the project you are working on
Survival Game

### Describe the problem or limitation you are having in your project
The game needs to give resources based on the mass of an object, however to know the mass of the object volume needs to be known (as density is given by material and is constant)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
By having a built in way of Calculating Volume, one could get accurate masses of objects based on their density, which would allow for the following: 
1. Setting Proper Mass of a Rigid body for more accurate simulation, rather then eye-balling the mass
2. Mass could be used to determine the Resources obtained from harvesting a given object, to give a More realistic value for the size, again rather then eye-balling the mass
3. Run-time mass calculations with CSG - Would allow for Cutting up an object in half or any other arbitrary split into 2 (and more) pieces each that Could be assigned a Proper Mass that can be used for 1 and 2 which allows for fairly realistic Fully Destructive objects with pieces having proper rigid body mass for more accurate simulations and giving them an easy value to use for it's resource value via mass

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
https://en.wikipedia.org/wiki/Polyhedron#Generalisations_of_polyhedra
See 2.5 For the general formula that needs to be implemented

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes, the formula isn't very complicated to apply.

### Is there a reason why this should be core and not an add-on in the asset library?
Significantly improves Workflow when attempting to get Rigid bodies to interact with one another, as you can just set rigid body Density, and have the mass determined by the volume and density, and allows for Splitting meshes to turn into multiple rigid bodies and getting them to interact right out of the box, has several other applications it opens up, and as a Heavily math based problem it would have better performance as Core/GDNative, and could potentially be used for other features down the line

**Comment by Zireael07** [comment]
Asset library addons *can* be GDNative, and given the rather narrow uses (only useful for sims/survival games) I think it's best left to an addon.

**Comment by mrjustaguy** [comment]
Well, anywhere where you've got rigid bodies using density to calculate the proper mass is far simpler compared to assigning a mass (more trial and error when you've got massively different shapes you're dealing with that aren't intuitive to get the volume for to get the mass), and considering just how Small it is ([Volume.zip](https://github.com/godotengine/godot-proposals/files/5983250/Volume.zip)) it feels silly to have as an addon, when it can be implemented in core, as some other such very small things are in core despite not being that widely used... 

I mean, .dae (Collada) anyone? (hell it's even more code compared to the 20-ish lines this would need and doesn't look like anyone's using that, as gltf and obj and fbx are far more common and better)

**Comment by fire** [comment]
I argue that volume calculations should be part of the physics engine. @pouleyKetchoupp Thoughts?

**Comment by mrjustaguy** [comment]
Volume Calculations Could possibly be used with Soft Bodies, however that'd require some research and I'm unsure if the performance would be usable (do note that VCs are VERY fast even in GDScript, thousands of triangles takes a couple of ms, I am more worried about what How Soft Bodies would use them and how efficient that would be)

**Comment by mrjustaguy** [comment]
Closing, as GDScript is getting better, and now with GDExtensions, it's very easy to make a faster implementation (vs GDScript) if needed, so no more point in having this in Core unless there are places that use it in Core, which there are not at the moment.
