### ISSUE TITLE
Add a project setting to configure the audio resampling algorithm

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2298]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Godot's audio resampling algorithm is currently hardcoded and there is no way to change it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are a few reasons to change the audio resampling algorithm used in a game:

- Improve audio quality for sounds that have a low sample rate (< 44 kHz).
- Get a "punchier" feeling for low-sample rate sounds in retro games.
- Decrease CPU usage when many sounds are playing (only relevant on low-power machines like the Raspberry Pi and perhaps mobile).

Here's an example with Freedoom's shotgun sound played with *nearest* resampling, then *cubic* resampling, then *23th order sinc* resampling:

https://user-images.githubusercontent.com/180032/108107381-72960280-708f-11eb-9abb-1264dbe0071e.mp4

Of course, nothing prevents you from using nearest-neighbor resampling in your DAW then exporting the sample in 44 kHz or more, but doing so will increase file size. This can be a problem when targeting mobile/web platforms where distribution size needs to be kept as small as possible.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a project setting to configure the audio resampling algorithm used by Godot. I think having an option to use nearest-neighbor resampling in addition to the default high-quality mode would be a good start already.

https://github.com/godotengine/godot/pull/46086 is working on adding a new audio resampling mode which is of higher quality but also more demanding than the current cubic resampler. Therefore, we may need to keep the Cubic option available as well.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as this resampling is done in C++ in the audio engine.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by troy-lamerton** [comment]
Maybe the resampling algorithm needs improvement? It should be possible to have a one-size-fits-all resampling algorithm.

In Unity, audio assets are resampled quite well, and I don't choose any options for this.

Can you point out the hardcoded resampling code? Didn't see it in a quick search

**Comment by Calinou** [comment]
> EDIT: this is the hardcoded algorithm?
>
> https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/servers/audio/audio_rb_resampler.cpp

AudioRBResampler only seems to be used within VideoPlayer. The AudioStreamPlayer nodes have their own (cubic) resamplers.

**Comment by troy-lamerton** [comment]
So this proposal asks for an option to play an audio asset differently. Change an option to tweak the sound of the original asset.

@Calinou Am I understanding this correctly?

- Idk what options Godot already has for this.
- Unity has these options: https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/troy/2021/07/Unity_fk4XkVhZllIXrwRa.png

Resampling algorithms are complex. I would advise against touching this if there is an alternative to achieve what you would like.

**Comment by Calinou** [comment]
> Idk what options Godot already has for this.

Godot doesn't expose a way to configure the resampler; there is one one and it's hardcoded. However, I'm not sure if Unity and UE4 expose a way to change the resampling algorithm used.

**Comment by troy-lamerton** [comment]
> This proposal is effectively stating that there is no "one size fits all" resampler. It all depends on your needs, performance constraints and even personal preference 🙂

Can you elaborate on this? I don't understand this.

Why would you want to distort all your audio assets? They should sound the same in-game as when you listen to them in your music player.

**Comment by Calinou** [comment]
> Why would you want to distort all your audio assets? They should sound the same in-game as when you listen to them in your music player.

This is about improving *perceived* sound quality for retro games. In my experience, sounds with a sample rate below 44.1 kHz will often sound better when using a low-quality resampler compared to a high-quality one. There are exceptions here and there, but this is what I noticed on my hardware at least.
