### ISSUE TITLE
Add a method to detect whether a mobile project is running on a TV (Fire TV, tvOS, …)

### ISSUE THREAD

**Issue by michael-conrad** [godotengine/godot-proposals#2300]
### Describe the project you are working on

Numbers Maze: https://github.com/CherokeeLanguage/NumbersMaze.godot/

### Describe the problem or limitation you are having in your project

Currently the app cannot detect if it is running on a TV or not. This makes it difficult to have menus display correct instructions in regards to touch vs gamepad input instructions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding an option like OS.isTv() that indicates if the device is advertising itself as a TV would solve the issue. Should return true for Android TV, FireOS TV, and ios TV. Otherwise false.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Global OS, new method "isTv()" returns bool true/false.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I am aware of.

### Is there a reason why this should be core and not an add-on in the asset library?

Is an OS detection function.

**Comment by Calinou** [comment]
> Adding an option like OS.isTv() that indicates if the device is advertising itself as a TV would solve the issue. Should return true for Android TV, FireOS TV, and ios TV. Otherwise false.

This should probably be handled using [feature tags](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html) instead of adding a dedicated method to the OS singleton.

**Comment by michael-conrad** [comment]
Is there a way to add to the feature tags in the Java shim during app load for android?

**Comment by Calinou** [comment]
> Is there a way to add to the feature tags in the Java shim during app load for android?

You can define custom feature tags in the export preset when exporting the project, but you can't do that while the application is loading.

**Comment by michael-conrad** [comment]
Ah. Unfortunately setting the value during export is pointless as it needs to be checked at initial app load.

For libGDX I use the following class file to set a property on the main app during initialization in the android launcher.

```java
package com.cherokeelessons.vocab.animals.one;

import com.cherokeelessons.animals.TvDetector;

import android.annotation.TargetApi;
import android.app.UiModeManager;
import android.content.Context;
import android.content.res.Configuration;
import android.os.Build;
import android.os.Bundle;
import android.util.Log;


public class AndroidTvDetector implements TvDetector {
	
	private final Context context;

	public AndroidTvDetector(Context context) {
		this.context = context;
	}
	
	private static final String TAG = "DeviceTypeRuntimeCheck";

	@TargetApi(Build.VERSION_CODES.HONEYCOMB_MR2)
	@Override
	public boolean isTelevision() {
		/**
		 * Checks if the device is a TV.
		 */
			UiModeManager uiModeManager = (UiModeManager) context.getSystemService(Context.UI_MODE_SERVICE);
			if (uiModeManager.getCurrentModeType() == Configuration.UI_MODE_TYPE_TELEVISION) {
			    Log.d(TAG, "Running on a TV Device");
			    return true;
			}
			Log.d(TAG, "Running on a non-TV Device");
			return false;
	}
}
```

```java
package com.cherokeelessons.vocab.animals.one;

import com.badlogic.gdx.backends.android.AndroidApplication;
import com.badlogic.gdx.backends.android.AndroidApplicationConfiguration;
import com.cherokeelessons.animals.CherokeeAnimals;

import android.os.Bundle;

public class AndroidLauncher extends AndroidApplication {
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		AndroidApplicationConfiguration config = new AndroidApplicationConfiguration();
		CherokeeAnimals game = new CherokeeAnimals();
		game.setIsTelevisionDetector(new AndroidTvDetector(this.getApplicationContext()));
		initialize(game, config);
	}
}
```

**Comment by michael-conrad** [comment]
Work around for Android.

Create a custom Android build environment. (Required for TV anyways to set TV specific manifest entries, icons, etc).

First change the class Godot to read:

```java

package com.godot.game;

import android.app.UiModeManager;
import android.content.Context;
import android.content.res.Configuration;
import android.os.Bundle;
import android.util.Log;

import androidx.annotation.NonNull;

import com.cherokeelessons.maze.R;

import org.godotengine.godot.FullScreenGodotApp;
import org.godotengine.godot.Godot;

import java.util.Arrays;

/**
 * Template activity for Godot Android custom builds.
 * Feel free to extend and modify this class for your custom logic.
 */
public class GodotApp extends FullScreenGodotApp {

	protected static final String TAG = GodotApp.class.getSimpleName();

	@Override
	public void onCreate(Bundle savedInstanceState) {
		setTheme(R.style.GodotAppMainTheme);
		super.onCreate(savedInstanceState);
	}

	@NonNull
	@Override
	protected Godot initGodotInstance() {
		final Godot godot = new MyGodot();
		return godot;
	}

	public static class MyGodot extends Godot {
		@Override
		protected String[] getCommandLine() {
			String[] args = super.getCommandLine();
			args = Arrays.copyOf(args, args.length+1);
			args[args.length-1] = "--tv="+ isTv();
			return args;
		}

		protected boolean isTv() {
			if (uiMode() == Configuration.UI_MODE_TYPE_TELEVISION) {
				Log.i(TAG, "Running on a TV Device: true");
				return true;
			} else {
				Log.i(TAG, "Running on a TV Device: false");
				return false;
			}
		}

		protected int uiMode() {
			Context context = this.getContext();// getApplicationContext();
			UiModeManager uiModeManager = (UiModeManager) context.getSystemService(Context.UI_MODE_SERVICE);
			return uiModeManager.getCurrentModeType();
		}
	}
}

```

Second, in your game script files check the command line args for "--tv=true"

```gdscript
func _ready():
	print()
	print("=== PLATFORM: "+OS.get_model_name()+" ["+OS.get_name()+"]")
	var is_tv:bool
	for argument in OS.get_cmdline_args():
		if argument.begins_with("--tv="):
			if argument == "--tv=true":
				is_tv = true
			else:
				is_tv = false			
	print("--- TV: "+str(is_tv))	
	print()
```

**Comment by m4gr3d** [comment]
This functionality can be provided via a Godot Android plugin instead.
See [these instructions](https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html) for how to create a Godot Android plugin.

I'm closing the proposal since the suggestion addresses the primary need, but feel free to comment, or reopen if I overlooked something.

Thanks!

**Comment by m4gr3d** [comment]
I've only addressed the Android case, but the same option is applicable to iOS as well.
cc @naithar

**Comment by naithar** [comment]
tvOS support is added with this PR: https://github.com/godotengine/godot/pull/45829. There are a link to **unofficial** editor build and templates/plugins so building for tvOS should be possible with it.
Using `OS.get_name()` (will return `tvOS`) should allow to detect on which platform project is running.
