### ISSUE TITLE
Add a feature so one can use a ' background theme image ', on the editor . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2303]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I think it would be cool, if one could load an image, that sort of gets ' painted ', on the editor, maybe trees, sci - fi, etc . . that fits one's game . . I'm not sure if this would be complex, but it'd be a cool little feature, I'd like to have a ' nature ' inspired look, or so . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Just, a silly idea . . Add so one can load an image, and it get's ' projected ', on the editor, like a back-ground or, theme . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Like, so the editor looks like a certain theme, or such . . So, 3D preview doesn't change, just the background, of the docks, maybe <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I have no idea, it's just fun <3

### Is there a reason why this should be core and not an add-on in the asset library?
Not sure, really like it <3

**Comment by pycbouh** [comment]
In theory, it wouldn't be terribly complex, it would just require a panel with a styleboxtexture. But it won't be extremely practical either. And this can likely be done with an edtor plugin.

**Comment by Calinou** [comment]
Closing due to lack of support (see lack of reactions on OP and overall lack of comments here).
