### ISSUE TITLE
Copy selected nodes between scenes with `Ctrl+C` `Ctrl+V`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2305]
### Describe the project you are working on
plugins

### Describe the problem or limitation you are having in your project
There is already a way to copy-paste nodes from one scene to another: `Merge From Scene`.
But this is not so intuitive and handy as `Ctrl+C`/`Ctrl+V`.

The user does many copying things in Godot with `Ctrl+C/Ctrl+V` (copy code and other text, copy files paths etc).
So often he expects the same approach and shorcuts to copy-paste nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Ability to copy nodes between scenes with `Ctrl+C` `Ctrl+V` would solve the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
This could copy selected nodes like `Merge From Scene` does but without that popup dialog.
1. You just select nodes to copy
2. `Ctrl+C`
3. Open target scene
4. Select a node where to paste nodes
5. `Ctrl+V`

This should work for copying nodes to the current scene as well (in this case you just omit [3 — Open target scene])

`EditorShortcuts` could have this commands to be able to set different keyboard shortcuts, rather than `Ctrl+C`/`Ctrl+V`

### If this enhancement will not be used often, can it be worked around with a few lines of script?
You could use `Merge From Scene`, but this is not so handy.

### Is there a reason why this should be core and not an add-on in the asset library?
This would look like reinventing the wheel, because the copy/paste nodes functionality already exists, but not exposed.

**Comment by KoBeWi** [comment]
This is already implemented in 4.0 and will be added to 3.2.x soon.

**Comment by Xrayez** [comment]
See related PR: godotengine/godot#34892.
