### ISSUE TITLE
Minimizing parts of the Godot Engine UI

### ISSUE THREAD

**Issue by AntonioNoack** [godotengine/godot-proposals#2308]
### Describe the project you are working on
I am working on a racing game, but that's unrelated.

### Describe the problem or limitation you are having in your project
In the UI, all sections (Scene/Import, Code Editor, Output Console, File System) have a minimum width and height of about 200-250px. On a 1080p screen the console uses 25% of my screen real-estate (height, when coding, is most important), even if it's empty. And I cannot hide it by just making it smaller.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow sections to be smaller than 250px; maybe 20px, so they can be quickly collapsed

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Somewhere in Godot, there is this limitation coded. I just would change it to something lower.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, it's Godots UI. Maybe there is a setting somewhere, but I haven't found it yet.

### Is there a reason why this should be core and not an add-on in the asset library?
It's the base UI. This probably has to be changed in Godots core.

**Comment by pycbouh** [comment]
If you want to hide the Output panel, then you can just click on its title on the bottom panel.

**Comment by AntonioNoack** [comment]
Thank you 😁👍

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-proposals/issues/1441.
