### ISSUE TITLE
Buttons should be able to be resized to a minimum height of (0, 0) instead of (12, 20)

### ISSUE THREAD

**Issue by Nukiloco** [godotengine/godot-proposals#2309]
### Describe the project you are working on
This generally affects any projects that I'm working on.

### Describe the problem or limitation you are having in your project
The problem that I'm having in my project is that I realized that buttons in Godot can only be resized to (12, 20) without text unless if provided a custom font. Still even when providing a custom font, I'm only allowed to resize button to (12, 7) which is very close to being small as possible. I haven't found any possible way to change the minimal button height with themes also.

I assume this is a limitation with how the button can't resize to the maximum size of the because of the text. I assume without any text in the buttons would allow the button to resize to (0, 0) though this doesn't seem like the case.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The feature that I want to see is the ability to resize buttons to (0, 0). This will allow me and possibly other creators to make small buttons without any limits set by the engine. I would think it would be tedious for creators for the only solution to resize their buttons to the smallest by setting a custom font, which still doesn't seem to give a lot of control over how small the button can be.

For buttons that do have text in them should still have their minimal size be set by how huge the text is in the buttons. Though the Clip Text property should allow the button to be resized to (0, 0) still if there is text on it.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Resizing buttons (without text and with the **Clip Text** property enabled) should allow users allowed to resize down to (0, 0).
Resizing buttons with text and with the **Clip Text** property disabled should allow users to resize down to the minimum size of the text.
Resizing buttons with text and with the **Clip Text** property enabled should allow users to resize down to (0, 0).

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It might be possible to bypass this by automatically swapping all buttons with a script with a TextureButton instead but this will require the user to assign their own textures instead of just using the default theme for their buttons. It also might be possible to bypass it by setting the scale size or making a custom button scene with having no minimal size limit.

### Is there a reason why this should be core and not an add-on in the asset library?
Yes, because in my opinion and possibly others, it seems silly to use a custom add-on to bypass a minimal size limit with buttons when instead the limitation can be removed in the core.

**Comment by BastiaanOlij** [comment]
This needs a better use case described in order to be considered. 

The text of the button is what drives the minimum size of the button which is very important for the normal use case of buttons, especially for everyone who have created interfaces using containers that autosize. Their solutions may break if we remove the minimum size. 

There is an argument where we could say that if no text is given the minimum size becomes 0,0 but even that could trip up people who are building interfaces based on data and rely on the button height being correct for the chosen font. 

Note that if you don't have text on your button and just want a tiny are that users can click on, you can use a different button type like `TextureButton` that has no text.

**Comment by KoBeWi** [comment]
Most of the current minimum size comes from the stylebox. When you create custom one, you can shrink down to (0, `font_height`):
![uko4CAkQqT](https://user-images.githubusercontent.com/2223172/108346863-24444900-71e0-11eb-9718-f8fa59192356.gif)
We could make the minimum height 0 if the text is empty, but as said above, for empty buttons you can just use `TextureButton`.

**Comment by Flairieve** [comment]
Pasting some of the points that I made from the Godot chat.

> This needs a better use case described in order to be considered.

A use case for an example would be an mmo game with many buttons in a cramped menu/container/group of buttons. There can be a possibility where for example the button has a small font size or a single letter button. For example like a button that has the text E which in this case would stand for something like a power up called Energy. The developer possibly want the button to be this small to fit it in with a group of other buttons while keeping the same font size and button texture that his project/game uses.

> The text of the button is what drives the minimum size of the button which is very important for the normal use case of buttons, especially for everyone who have created interfaces using containers that autosize. Their solutions may break if we remove the minimum size.

> There is an argument where we could say that if no text is given the minimum size becomes 0,0 but even that could trip up people who are building interfaces based on data and rely on the button height being correct for the chosen font.

If this proposal can break their solutions, then I question if its possible for the editor/engine to set a minimal size on buttons created without having to set an internal limit so users can still set the minimal size to a size like 0, 0. I think the button size should still rely on the size of text. Though the user should be able to use a property like Clip Text to allow them to set the size of the button to 0, 0.

**Comment by Flairieve** [comment]
> Most of the current minimum size comes from the stylebox. When you create custom one, you can shrink down to (0, font_height)

I knew about creating a custom one would allow me to set the x to any size even to 0, though from comment I posted above, I think that Clip Text when enabled should allow a custom height to be set lower than the font height.

**Comment by BastiaanOlij** [comment]
I wouldn't be against the `clip text` option. I can see other use cases where you may want to clip larger sections of text where if you do want the full text to show a hoover over or popup will display the entire text.

**Comment by Flairieve** [comment]
A popup text for when Clip Text is enabled sounds like a good idea but I don't think that still covers the minimal height limit problem on buttons. Also I think Clip Text for buttons having a popup should be its own proposal.

**Comment by davthedev** [comment]
Clipping text was definitely used in other UI toolkits and plays nice by not enforcing a text-driven minimum size. This can be an optional setting.

Another caveat is that some fonts have too much vertical padding in them. Having the possibility to override or reduce minimum size by clipping or setting negative margins would allow to compensate such cases.

**Comment by Nukiloco** [comment]
Coming back to this proposal again. In the current system, buttons size are limited by the font height. While this is great for automatically expanding the button to the text. However, this causes a limitation when people want precise control over their UI, especially in situations when their user interface layouts are cramped and need all the possible space they can get.

Currently as pointed out by @BastiaanOlij, allowing people to scale their buttons further down will cause breaking changes and will affect existing projects as some or a lot of people might be dependent on the automatic font button scaling. An idea that I came up with to fix this problem is to have a variable called ``Scale by Font Size`` which is enabled by default. This variable when set to true will keep the current behavior on how button sizes are set by the font size. Setting this variable to false will give the user complete control over the button size without being limited by the font size.

**Comment by connerlane** [comment]
Commenting because this limitation is super annoying for very low res games. Please consider revisiting

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/35005, as this is actually a bug.
