### ISSUE TITLE
Add PoolBoolArray, PoolVector2/3i and `File.store_bool()`

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot-proposals#2310]
### Describe the project you are working on
Mostly grid based games

### Describe the problem or limitation you are having in your project
Not really much of a limitation but would be nice to have this features

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think this features could allow users to optimize their games more, and have a code that feels less "hacky" and better typecheck

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes this can be worked around
Tho there's a lot of wasted memory for storing the type of the variables, as normal array would have to redundantly store the type of its element 

### Is there a reason why this should be core and not an add-on in the asset library?
I think datatypes are usually built in, so probably won't be an unnecessary bloat to the engine

**Comment by pycbouh** [comment]
What exactly is your proposal?

**Comment by LoneDespair** [comment]
> What exactly is your proposal?

Addition of PoolBoolArray, PoolVector2/3i and file.store_bool

**Comment by pycbouh** [comment]
Note that in master version, where we have integer Vector2/3, PoolArrays are gone and PackedArrays are introduced.

As for the File API, `store/get_var` should probably have you covered.

**Comment by LoneDespair** [comment]
> Note that in master version, where we have integer Vector2/3, PoolArrays are gone and PackedArrays are introduced.
> 
> As for the File API, `store/get_var` should probably have you covered.

Thank you so much, for the reply

The main reason for me on needing the packedvector2integer, is i think it would be very inefficient to make sure that all the arrays are rounded to whole numbers

This is specially important when all of them will be used at the same time, eg rendering the data is from another client

For the store_bool, store_var feels very inefficient, as it adds an unnecessary 4 bytes, will quickly add up when storing tens of thousands of them

**Comment by SIsilicon** [comment]
I think a PackedByteArray would be a good alternative to PackedBoolArray. I'm not familiar with how the underlying code works, bit my best bet is that it stores the bytes as how they should be: a single byte of 8 bits. Most programming languages store booleans in a single byte anyway. If you want them even more packed, then you can pack them yourself to the individual bits. A little bit of boilerplate code can be made for that, meaning it can be worked around with a few lines of code.
The same can be said about store_bool(). You can use store_8() instead, and if you want it more packed, make some boilerplate code.

**Comment by LoneDespair** [comment]
> I think a PackedByteArray would be a good alternative to PackedBoolArray. I'm not familiar with how the underlying code works, but my best bet is that it stores the bytes as how they should be: a single byte of 8 bits.
> Most programming languages store booleans in _at least_ a single byte anyway. If you want them even more packed, then you can pack them yourself to the individual bits. A little bit of boilerplate code can be made for that, meaning it can be worked around with a "few" lines of code.
> **Edit**: in fact a special object called a BitSet can be, and has been implemented for this sort of thing. https://github.com/godot-extended-libraries/godot-next/blob/master/addons/godot-next/references/bitset.gd
> 
> The same can be said about store_bool(). You can use store_8() instead, and if you want it more packed, make some boilerplate code.

Ohhhh yupppp, bitwise, Thank you so much! this helped me find, what I'm looking for
