### ISSUE TITLE
Allow the user to see what's beyond the main viewport in 2d, very useful for GUI development

### ISSUE THREAD

**Issue by Thebas** [godotengine/godot-proposals#2313]
The follow image gives a perfect example, it is a scrollContainer, but I need to change the values to see what is hidden(unnecessarily).
![image](https://user-images.githubusercontent.com/5076514/108413233-094af680-722b-11eb-8cb7-5d61c74a24ae.png)

### Describe the project you are working on
Workout App with a lot of work in terms of GUI

### Describe the problem or limitation you are having in your project
Attached screenshot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
If we could see beyond the viewport it would allow faster navigation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Will be used all the time.

### Is there a reason why this should be core and not an add-on in the asset library?
Yes, I can't how could it be an add-on. GUI development assistant add-on?

Thank you in advance!

**Comment by Calinou** [comment]
This is not about seeing "beyond the main viewport", but rather having an editor-only way to display overflowing contents in a ScrollContainer.

I think this can be achieved with a `tool` script already :slightly_smiling_face:
See [Running code in the editor](https://docs.godotengine.org/en/stable/tutorials/misc/running_code_in_the_editor.html) in the documentatino.

**Comment by golddotasksquestions** [comment]
@Thebas 
You should be already able to do this in one click:
Go to the Inspector under Control > Rect uncheck "Clip Content"

**Comment by Calinou** [comment]
Closing, as this can already be done by unchecking **Clip Content** in ScrollContainer.
