### ISSUE TITLE
Upgrade Mono to 6.x for C# 8 support

### ISSUE THREAD

**Issue by giulianob** [godotengine/godot-proposals#232]
### Describe the project you are working on:

RPG game in Godot 3.1 with lots of entities.

### Describe the problem or limitation you are having in your project:

I would like better memory management when using C# for some operations which currently produce a lot of garbage and drops frame rate down from 60 fps.

### Describe how this feature / enhancement will help you overcome this problem or limitation:

The support for Span and stackalloc in latest Mono and C# 8 allows removing pressure from the GC.

### Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:

N/A 

### Describe implementation detail for your proposal (in code), if possible:

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?:

No this is critical for memory management in C# without resorting to `unsafe` or native.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

### Other reasons to upgrade

* Improve WASM runtime
* Improved NuGet support
* Support macOS 10.15

**Comment by exts** [comment]
(cc: @akien-mga )

**Comment by nhydock** [comment]
3.2 Beta 2 has been upgraded to this so I think the proposal can be closed
