### ISSUE TITLE
TileMap make cellv functions the same as cell functions

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-proposals#2324]
### Describe the project you are working on
Top-down exploration game

### Describe the problem or limitation you are having in your project
I have to use get_cell_autotile_coord and set_cell instead of get_cellv_autotile_coord (which doesn't exist) and set_cellv since set_cell doesn't seem to have an autotile_coord parameter.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add a get_cellv_autotile_coord which is like get_cell_autotile_coord but it takes a Vector2 argument. Add an autotile_coord parameter to set_cellv.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
🤷🏼 I dunno how the Godot source code works.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes.

### Is there a reason why this should be core and not an add-on in the asset library?
It would make the functions more consistent.

**Comment by Xrayez** [comment]
Note that `set/get_cellv` methods are planned to be removed in Godot 4.0 (see godotengine/godot#39976), and `set/get_cell` would accept `Vector2i` for position, so I think this would be only relevant for Godot 3.2.

**Comment by ShatReal** [comment]
Hm, well as long as it's consistent.

**Comment by aaronfranke** [comment]
This has been implemented with #48535. Closing.
