### ISSUE TITLE
Add color tags to the project manager

### ISSUE THREAD

**Issue by alexfreyre** [godotengine/godot-proposals#2329]
### Describe the project you are working on
Godot project manager

### Describe the problem or limitation you are having in your project
I usually have several projects in progress and each one in a different state. Some projects are unique or share similar solutions, are in similar states or are a specific group. But all together they are shown as a list where they can only be marked as favorites. 

The problem I have is that I need to mark my projects with different states/priorities:
- mark and identify a specific one (or let it as usual )
- group them (for whatever reason needed, for example )
.. which are finished
.. which are in a critical state
.. in which I still do not have the final solution
.. different engine versions or scripting language, see [#427](https://github.com/godotengine/godot-proposals/issues/427)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I propose to put a kind of label by color (the design is variable)
They can be grouped by color consecutively and each color responds to a status or priority.

This proposal leaves for discussion:
- Colors and quantity (for example: red, green, blue, yellow, orange, purple)
- If the user can alter the order of priority of the colors (green_up-red_down / red_up-green-down, etc)
- Design

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and / or diagrams

I have two solutions as a starting point:

![solution_1](https://user-images.githubusercontent.com/42384785/108638274-51b22080-7486-11eb-9902-1b6b808b9fa5.jpg)
![solution_2](https://user-images.githubusercontent.com/42384785/108638278-570f6b00-7486-11eb-85c4-02abdc5af74a.jpg)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
I think it is core.

**Comment by alexfreyre** [comment]
I have made this two solutions but I don't like them, but totally open if the community likes them more.

![solution_3](https://user-images.githubusercontent.com/42384785/108638560-c6398f00-7487-11eb-9215-eac3dd8cd6f4.jpg)
![solution_4](https://user-images.githubusercontent.com/42384785/108638561-c89be900-7487-11eb-834e-6b170f845fa5.jpg)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/427.

**Comment by alexfreyre** [comment]
some other solutions

![Solution_5](https://user-images.githubusercontent.com/42384785/108638855-3ac0fd80-7489-11eb-9328-a82e88ff12d6.jpg)
![Solution_5 1](https://user-images.githubusercontent.com/42384785/108638858-3e548480-7489-11eb-9c0d-32ea01a5bc01.jpg)

**Comment by dalexeev** [comment]
![](https://user-images.githubusercontent.com/47700418/108640864-25f66100-74ad-11eb-993c-95f3f617e874.png)

**Comment by me2beats** [comment]
@dalexeev cool idea, these are not *color* tags tho:)
Kinda "tabbed" categories.
I would like to have it but I think some kind of tag system (similar to github issues labels) would be more flexible solution.
It is worth a separate proposal imo.

**Comment by eon-s** [comment]
Not fully convinced of this (I prefer text tags, maybe colored text tags) but in any case, colors should not be limited for accesibility reasons (another options beside colors are icons/stamps, like using node icons).

**Comment by Calinou** [comment]
If we go through with https://github.com/godotengine/godot/pull/34528, the project color could be displayed at the left of the project item in the project list.

**Comment by dalexeev** [comment]
Another option is something like this:

![](https://user-images.githubusercontent.com/47700418/118397945-1414fc00-b65f-11eb-8d21-60aa164cef5e.png)

32x32 icons will look better than 16x16, and the current 64x64 is too big.

**Comment by eon-s** [comment]
The problem with that view is that is too compact, when you have many projects it will be wasting space on the right and too cluttered with packed information, complex to sort, etc.

Also for icons sometimes devs just put captures of a meaningful scene of their games (untill later when the game has a proper art for it).

Compact lists can be optional like with file explorer, mostly useful for cleanup and organization.

**Comment by dalexeev** [comment]
![](https://user-images.githubusercontent.com/47700418/118410142-a7b5ef00-b696-11eb-8dfa-f6b93c6eb15f.png)

**Comment by dalexeev** [comment]
[This comment](https://github.com/godotengine/godot-proposals/issues/2329#issuecomment-782939183) seems to have received the most support:

![](https://user-images.githubusercontent.com/47700418/141765234-f4ef755f-a7cd-482d-b17b-d85a52981966.png)

Personally, though, I prefer the file structure [option](https://github.com/godotengine/godot-proposals/issues/2329#issuecomment-841865961) (e.g. `~/godot/projects/subfolder/project-folder/`). Moreover, in 4.0, the editor's metadata is now stored in the project folder (`.godot/editor/`), i.e. you can move the project between subfolders without any problem.
