### ISSUE TITLE
Add GDScript as a .NET CLR language

### ISSUE THREAD

**Issue by montyclt** [godotengine/godot-proposals#2336]
### Describe the project you are working on
Not working on any serious project, I only used the engine to try it.

### Describe the problem or limitation you are having in your project
Inhertis a GDScript class from C# class, and vice versa.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Making GDScript as .NET CLR language will unify scripting in the same runtime.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I am aware that this is a bigger change, difficult to implemente and can break compatibility with current GDScript code. I propose create a new version of GDScript called GDScript.NET (or any other name) with other file extension to differentiate from the current GDScript (for example, `*.gdsn`).

This version of GDScript should have all keywords and features of the current GDScript (except not using types in method definitions, that I think this is not possible with .NET).

Unifying all scripting languages into .NET, will allow to use some `System` types that are duplicated into `Godot` namespace, for example `System.Numerics.Vector2` struct and `Godot.Vector2` struct.

I'm not sure, but I think the .NET version of GDScript will executed with same performance than C# scripts.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
C# can be use when a CLR language is needed. I'm not sure if there are any form to use GDScript classes from C# classes.

### Is there a reason why this should be core and not an add-on in the asset library?
I'm not sure if a version of GDScript that target .NET CLR can be added as addon language.

**Comment by Calinou** [comment]
> I propose create a new version of GDScript called GDScript.NET (or any other name) with other file extension to differentiate from the current GDScript (for example, *.gdsn).

The intent of GDScript is to have a small, simple language. Creating a derivative language is contrary to that goal.

**Comment by montyclt** [comment]
> Did you take a look at Godot's [cross-language scripting](https://docs.godotengine.org/en/latest/tutorials/scripting/cross_language_scripting.html) capabilities?

Hi @Calinou I missed the cross-language scripting capabilities, thank you for the link but there are not allow inheritance between languages. There are some external libraries that add new nodes, and for scripting a node, there are necessary to extends it.

> The intent of GDScript is to have a small, simple, dependency-free language. Creating a derivative language based on a runtime as large as Mono/.NET is contrary to that goal.

I understand that making current GDScript as .NET language is impossible due to the current codebase that need to be adapted and re-compiled, so I propose derivate language.

If this is contrary to GDScript principles and is not debatable, feel free to close the issue.

**Comment by Calinou** [comment]
> If this is contrary to GDScript principles and is not debatable, feel free to close the issue.

Indeed;
 there are no plans to create yet another programming language for Godot.
