### ISSUE TITLE
Release official 3.2.3 binaries for ARM-based Macs

### ISSUE THREAD

**Issue by MintStudios** [godotengine/godot-proposals#2340]
### Describe the project you are working on
A game?

### Describe the problem or limitation you are having in your project
I'd like to work with a CI on github, but 3.2.4 betas don't work for the 3.2.3 CI build. It's by aBARICHELLO.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I'm on an M1 mac, and I'd like a stable version. However, I want to keep things native.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I'm not sure, but there was a build file (I think) merged for ARM macs. Just use the 3.2.3 branch.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It could be under rosetta, but native is always better for something critical like a game engine.

### Is there a reason why this should be core and not an add-on in the asset library?
It can't be an add-on.

**Comment by Calinou** [comment]
You can ask @aBARICHELLO to provide an 3.2.4rc3 image which can feature macOS ARM support :slightly_smiling_face:

**Comment by pycbouh** [comment]
As there are code changes that make ARM macOS builds possible, this cannot be released under `3.2.3` version, as that version is already released and stable. `3.2.4` will come out soon enough and I'm sure it will be adopted by projects like [aBARICHELLO/godot-ci](https://github.com/aBARICHELLO/godot-ci).

Closing this in favor of aBARICHELLO/godot-ci#51.
