### ISSUE TITLE
Return Jarsigner for signing AABs

### ISSUE THREAD

**Issue by Summersay415** [godotengine/godot-proposals#2341]
### Describe the project you are working on
Any Android

### Describe the problem or limitation you are having in your project
AAB files cannot be signed by apksigner([https://developer.android.com/studio/build/building-cmdline#bundle_build_gradle](https://developer.android.com/studio/build/building-cmdline#bundle_build_gradle))

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Return Jarsigner for signing AABs(don't remove apksigner!)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add Editor setting with jarsigner path, and sign AABs with it

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
This is export function

**Comment by Calinou** [comment]
This change was done by @m4gr3d. It's unlikely to be negotiable :slightly_smiling_face:

**Comment by m4gr3d** [comment]
@Summersay415 As it's mentioned in the documentation you linked, gradle automatically signs the generated aab as long as the release keystore information is available.
