### ISSUE TITLE
PageCurl transition like iOS and android or unity

### ISSUE THREAD

**Issue by amitanubha** [godotengine/godot-proposals#2346]
### Describe the project you are working on
I am working on educational games and apps, which requires readers to read books as well. I am moving from as3 and evaluating moving to Godot(instead of Unity). I have this functionality built into my current apps using as3/iOS swift native page curl 

### Describe the problem or limitation you are having in your project
I am both new to engine and don't know have experience enough to write complex graphics and transforms or shaders in Godot Engine. I do have idea on problem and how to solve mathematically but specific to engine not expert yet. Also this feature as a built in effect or transition animation is missing

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
This feature helps overcome my specific requirement for implementing a nice books interface of pages, and I believe also make the engine more suitable for general purpose apps and not just games. Note here all other engines provides this functions/effect like AS3/Flash, iOS Pagecurl and Android PageCurl

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Here is website which describes the mockup in details:
https://dandarawy.com/html5-canvas-pageflip/
https://gl-transitions.com/editor/InvertedPageCurl
https://www.cs.vu.nl/~eliens/assets/apidoc/book/com/rubenswieringa/book/package-detail.html
https://github.com/harism/android-pagecurl
Essentially, we are trying to use 2d graphics to draw various turn pages using matrix rotation and translation and using clipping to hide and show turn
I am not clear what else is expected on this section please let me know

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No I don't think
![bookFlippingpreview](https://user-images.githubusercontent.com/3510609/109120005-6a168980-776b-11eb-86a2-7bd54ea3e9fa.gif)

### Is there a reason why this should be core and not an add-on in the asset library?
Seems to me part of core engine functionality to provide transition as high performance is needed and lots of core graphics calls needs to be made

**Comment by pycbouh** [comment]
Godot doesn't provide any built-in visual effects, this is done on the side of user projects, with shaders presumably. There is frankly no point in creating standard effects, as you would never be able to make them customizable enough to cover all the bases, yet simple enough to be a plug-n-play solution. There are often multiple ways to achieve the same things too, with a multitude of trade-offs.

For these reasons, and to avoid engine bloat, we provide tools, not specific solutions (unless it's something fundamental, like rendering pipeline or input handling).

> Seems to me part of core engine functionality to provide transition as high performance is needed and lots of core graphics calls needs to be made

There is nothing here that requires new core engine functionality. Performance doesn't come just from being bundled into the core. Godot is extendable and allows game developers to implement custom modules as well as use high performance languages via GDNative. But in this case, this is just a shader, which is run on GPU. Unless there is something missing from our shader language that is required for such visual effects, there is nothing here to add to the core.
