### ISSUE TITLE
Add project-wide signal/group managment

### ISSUE THREAD

**Issue by MinofCat** [godotengine/godot-proposals#2347]
### Describe the project you are working on:
I am working on a platform game

### Describe the problem or limitation you are having in your project
There are too many signal and group (which I created through UI and GDscipt) and I cannot manage them.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot should have a tool summarize all the signal/group in the project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
With the signal/group is created by UI, it will list in management tool
With the signal/group is created in GS Script, the tool will search all the GDScript and find the commands.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I saw a solution by using grep, but this method is unfriendly and I also don't familiar with Linux
https://www.reddit.com/r/godot/comments/8c03tz/is_there_a_signal_map_that_shows_you_all_your/

### Is there a reason why this should be core and not an add-on in the asset library?
It will be use a lot and helpful.

**Comment by pycbouh** [comment]
Maybe a mockup would help others see how exactly this will be used and useful?

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/24262 where this feature was implemented a while ago, but it wasn't merged./

**Comment by MinofCat** [comment]
For example in my game, It is similar to Megaman, and it has a character like Zero( In funny way). Whenever he appears, he might break something. He just appears in a few level and interact with many object. So I use a lot of signal for him.  But if I want to change his behavior (like every time he appears, he distract enemy, so I need to remove/change all the signals). 
If I have a tool like Project Manager Tool, I can know exactly how much I need to change, and that help me to prevent bug or zombie code.

Additionally, I think we should have some external tool to manage the project. It will show us the the map of all the scene, signal, group... how many of them, their status,...
I am sorry for the basic proposal

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3789, which is more detailed.
