### ISSUE TITLE
Enable using scrollwheel to easily zoom in and out in the visual shader/script editor

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#2352]
### Describe the project you are working on
Trying out the visual shader editor because I like the visual feedback
### Describe the problem or limitation you are having in your project
I'd like to be able to more easily zoom in and out
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think if you're holding Ctrl while using the Scrollwheel it should make you zoom in/out. <kbd>Ctrl</kbd> + <kbd>Scrollwheel</kbd> to zoom is a very common shortcut in many programs (Godot's script editor, Firefox, Tiled, GIMP, Inkscape, Photoshop, Illustrator, Visual Studio, FL Studio, LMMS, to name a few). Currently Ctrl + Scrollwheel does nothing.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Ctrl + scrollwheel up to zoom in, Ctrl + scrollwheel down to zoom out
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
The visual shader/script editor is part of core

**Comment by LightningAA** [comment]
I'm not super picky whether it's ctrl + scrollwheel or just scrollwheel. I think I prefer ctrl + scrollwheel because then it's still easy to use the scrollwheel to move around vertically and horizontally, but it's not a big deal. Ctrl + scrollwheel to zoom is more like the script editor, scrollwheel by itself is more like the 2d scene editor.

**Comment by germanbv** [comment]
Outcome: Connecting an outcome to this node will make it automatically play that outcome upon node play in-game. Let's say you connect the outcomes ADD > Trait > Black and REMOVE > trait > white. Upon playing this node, the system is going to add the player the trait black and remove the trait white from the player. You can connect as many outcomes as you want alongside with other kind of nodes. This way this node can play multiple outcomes while not breaking the data tree navigation.
