### ISSUE TITLE
Make it easier to connect inputs and outputs in the visual shader when zoomed out a little

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#2353]
### Describe the project you are working on
Trying out the visual shader
### Describe the problem or limitation you are having in your project
https://user-images.githubusercontent.com/50304111/109213618-0cd00780-776e-11eb-86ff-404083068692.mp4
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think you should be able to grab the output of a node even if you're zoomed out a little
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
^
 |
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
It's part of the visual shader editor

**Comment by Calinou** [comment]
This sounds like a bug rather than a feature proposal. Please open an issue on the [main Godot repository](https://github.com/godotengine/godot) about this.

**Comment by LightningAA** [comment]
Closed in favor of [https://github.com/godotengine/godot/issues/46425](https://github.com/godotengine/godot/issues/46425)
