### ISSUE TITLE
Add an ability to move items in ItemListEditor using mouse drag

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2356]
### Describe the project you are working on
plugins

### Describe the problem or limitation you are having in your project

I often use `ItemListEditor` for filling `PopupMenu` and `ItemList` nodes with some initial data and also for prototyping.
And I miss the ability to move items.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Moving items using mouse drag would be handy, 
this would be a nice addition to copying items https://github.com/godotengine/godot-proposals/issues/2355

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just mouse left drag selected/active item up or down to move it (change items order).

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't think so

### Is there a reason why this should be core and not an add-on in the asset library?
I'm not sure this could be done as a plugin properly (without some hacks).

**Comment by thiagola92** [comment]
There is any way to move items in the Item List Editor?  

While this propose mention mouse, which would be great, i also would be alright with buttons like "Move up" and "Move down" for start.

**Comment by Calinou** [comment]
Related to #368.

**Comment by Calinou** [comment]
This is now implemented in property arrays in the inspector, which ItemList now uses for editing items instead of a dedicated editor:

https://user-images.githubusercontent.com/180032/174281796-6c199a64-54ae-4857-8562-e3736a153ca4.mp4

This also makes undo/redo available.
