### ISSUE TITLE
Add HSlider to Tree

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2357]
### Describe the project you are working on
Plugins

### Describe the problem or limitation you are having in your project
I have a Tree node with dynamic content and I want to scroll it horizontally.

I have tried to put it in `ScrollContainer` but I have 2 problems:

1. I need to calculate "actual" width of the tree manually (ideally taking into account all parameters, including the theme ones) and also automatically update it as needed. It doesn't seem like a trivial task.

2. I have some problems with scrolling, for example there seems to be a conflict between horizontal and vertical sliders (when using a ScrolContainer).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Adding `HSlider` to `Tree` would solve the problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://user-images.githubusercontent.com/16458555/109239398-2c5f4280-77f7-11eb-9558-08667427ea1b.mp4

- This horizontal slider might be optional.
In such a case, a `horizontal_enabled` property could be added.
- Maybe some other properties that ScrollContainer has could be added (like `h_value`)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Could be work-rounded, but not with a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?
this could be used often when creating responsive UIs without the hassle and reinventing the wheel.
Imo this would be a logical addition to the existing vertical scroll slider.

**Comment by Calinou** [comment]
Related to #1793.

**Comment by TBleader** [comment]
I was wondering if you could share the workaround you did to add a horizontal scroll bar? A project I am working on has multiple trees in scroll containers and of course the horizontal scroll bar doesn't ever show up, despite being very needed! I do hope this gets fixed but in the mean time a workaround is alright. I couldn't get it to work by setting/changing the x in get_internal_min_size() similar to the mentioned issue above. I couldn't figure out how to get the tree to respond/update like in your demo clip.
