### ISSUE TITLE
Add support for VR 3D world-building / anaglyph 3D effect in viewport . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2363]
### Describe the project you are working on
A Tomb raider game . . 
<3
<img width="1783" alt="2021-02-25 1459" src="https://user-images.githubusercontent.com/61069740/109324002-6579d000-7854-11eb-9fb8-0922429044d2.png">

### Describe the problem or limitation you are having in your project
I hear during stream, maybe support for VR world - building, bec. it has advantages . . A very cool user, made an anaglyph 3D camera plug-in, and though it runs slower, the 3D effect is AMAZING, world - class, like cinema 3D movies, 90 %, or more . . Since anaglyph 3D glasses are a lot cheaper, than VR head-set . .

For black - and - white images, the colors are retained, it looks as the original, but for sadly, color images some green, is lost, also red . . But, Godot 4 will get feature, to ' boost ' certain part, of color spectrum . .

So, my suggestion is, make it so the editor can have special ' Anaglyph 3-d glasses ' view mode, like cinematic preview, and maybe add so, in the mode, the ' faded ' colors are boosted . . VR head-sets lower rendering time, bec. they have to render TWO images, so maybe 3d glasses, anaglyph work on any monitor, do not require special tv or, such . . Well, maybe it's a cheaper way, of experiencing spatial placement, than a VR head-set, and could COMPLEMENT vr world building, etc . . There's already a plug-in, the results are 80 - 90 %, this good, with no changing settings . .

The cost, of 2 3D glasses, is 12 dollars and, with this feature, maybe some would be interested, in making Godot games, that use 3D glasses, since the cost is low, to the user, it should be easier, than making people buy VR and, if the colors that are faded, could be boosted, or ' simulated ' with dithering, of colors that are not faded, it might look really nice, not sure . .

Also note, the plug-in might run faster, if it was written in Native or, optimized, etc . . Or, though I was told this didn't make a difference, vertically interlacing the images, but the plug - in composer told, me it was not faster ? </3 . .

I have the new Oculus Quest 2, and the 3D is basically as good, with the plug - in, 80 - 90 %, as good, but I didn't tweak the settings, for eye distance, etc . .

For black and white anaglyph images, ie. original image is black / white, the colors are 100 % retained, no need for tweaking . . You might THINK the old 3D glasses are bad, compared to modern stuff, but it's 100 % as good, as what you see, in a 3D movie . . So, if you have a chance, see a 3D movie, in cinema or, put on VR goggles, it's about same quality, of 3D effect . . It might be possible to fake for instance green, by dithering other colors, or other tricks . .

You just have to believe, anaglyph glasses, with more moden ways of rendering 3D images, is THIS good <3
<img width="834" alt="Skærmbillede (1111)" src="https://user-images.githubusercontent.com/61069740/109325713-8ba06f80-7856-11eb-9170-4a4746178be7.png">

The reason is, that the way 3D images are made now, are much better, than in 1980's movies, today they have true 3D cameras, better rendering, I think that's why it's gotten as good, as cinema, or my Oculus Quest 2, in terms of 3D effect, but the colors are, for green, a bit faded . . 😨 
![2021-02-26 1719](https://user-images.githubusercontent.com/61069740/109325906-c86c6680-7856-11eb-863a-066b06e9f39d.jpg)

However, since VR goggles requires rendering of a much larger image, over 2 x image, to get 1080p, in each goggle 'window', the performance decrease, either way, should be the same <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add a ' cinematic preview ' mode, that simulates side-by-side cameras, and ability to tweak personal settings, may-be eye distance, and you'll have 3D spatial ' world ' building, at fraction of cost, of VR head-sets . . . and, if the image is made black - and - white, there's not color problems, from glasses blocking certain light rays, so at least you can, for 5 dollars for a pair, of glasses, get same effect, when making a world, proto-type, as VR goggles, SAME effect . . :OO :OO <3 . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
like, cinematic preview, add a feature, that renders SBS 3D, to anaglyph <3 . . and, maybe boost or, fake-dither the colors, that are missing, using fancy shader tech . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't re-write the engine, you may think the old two - color glasses are bad, but it's not true . . . They give the SAME 3D effect as a cinema, or VR goggles, the down-side is some colors, are faded . . The advantage is, the cost, 10 dollars, for 2 pair, on Amazon . . :O

### Is there a reason why this should be core and not an add-on in the asset library?
Well, in stream was talk of adding VR support, for editing levels, or structures, or so . . This way is just as fast, since VR is more render - intensive and, the results are just as good, minus some color ' fading ' <3 <3

**Comment by jasperbrooks79** [comment]
or, not sure, fake interlace the part image, that is a faded color, maybe green could be, uhmm yellow stripes + red, or ' simulated ' <3

**Comment by SIsilicon** [comment]
Jasper. This is the _third_ time that you're asking for the same anaglyph camera.

**Comment by jasperbrooks79** [comment]
Yes, but this is, not THAT . .

In Godot stream, a core contributor said, he wanted to add VR goggles, for ' level ' building or, pre - viz, to ' better ' see depth or, spatial <3 like, ' live ' VR level 'editing' . .

So, I was thinking, since VR is much more rendering problematic, bec. you have to render the image twice, for each ' eye ', and head-sets costs a fortune, 3D glasses cost like 10 - 12 dollars, for TWO . .

To get that ' spatial ' in VR effect, it can be done with 3D cheap glasses, the down side is, parts of color spectrum are muted but, Godot will soon get, a new ' feature ', that one can enhance or, decrease parts of spectrum, for instance ' green ', or ' blue ' can, be increased, or so . .

I'm not asking for a anaglyph plug-in, I'm asking for the EDITOR, in 3D preview mode, to render anaglyph . . Bec., a core dev said he wanted to add ' VR ' level ' editing ', to Godot, since it offers advantages, in his words, to level ' making ' . .

Sry . . . It was mentioned, in latest Godot con stream, yesterday :(( . . . .

**Comment by SIsilicon** [comment]
I appreciate your idea, but the advantages of using VR over anaglyph is much greater than vice versa. Most notably, you have a much better idea of your environment with a VR headset, since you'd be able to look around with your head. With anaglyph, all you're doing is popping out the screen. It doesn't give any real benefits other than a little depth perception.

Also, you suggesting to add anaglyph in the editor is still you asking for anglyph in Godot, which you've asked for already.

**Comment by jasperbrooks79** [comment]
Get a, curved monitor . .

Try getting some glasses, or maybe some other devs <3

If someone tried the glasses, you'd be convinced, in 1 minute . . <3

**Comment by SIsilicon** [comment]
That's what I mean with VR. You'd practically _become_ the editor camera. With anaglyph, you're still stick with using the plain old mouse and keyboard to move around.
And I've seen a 3D cinema with technology better than anaglyph. It's really good, but not good enough to make feel immersed in the scene.

**Comment by jasperbrooks79** [comment]
Listen, I'm not very good at Godot, or code . . I make a simple suggestion, but, well not sure . .

Thx . .
