### ISSUE TITLE
Make the grapheditor more ' customizable ' similar to texteditor . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2364]
### Describe the project you are working on
A Tomb raider <3

### Describe the problem or limitation you are having in your project
I use Visual script, and find it really amazing, but want to make experience more stable, easy - to use and, ' strong ' . . I made a very long proposal, with a TON of ideas, but was told it was unrealistic, sad 'too' much . . So, I wanted to make a SMALLER proposal, that MAYBE is more realistic . .

Here are the key things, I would love, in visual script . .
<img width="1385" alt="Skærmbillede (1113)" src="https://user-images.githubusercontent.com/61069740/109373835-963c2280-78b1-11eb-8cff-05753a299896.png">

Same way TextEditor can be changed, in Editor Settings, where one can set Theme, Dark Godot, light Godot . . <3 Add a new menu, where one can change stuff, in the GraphEditor <3

I would REALLY like to be able to set opacity, on major VERTICAL lines, major HORIZONTAL lines, see image above . . also the smaller VERTICAL lines, and smaller HORIZONTAL lines, color and opacity . .

The next thing is, I'd really like the ability, to make the lines have a few, different ' pattern ' or, even ' dither ' looks, like this . .

![2021-01-13 0315](https://user-images.githubusercontent.com/61069740/109373985-6d685d00-78b2-11eb-9322-74dea49f2dfd.png)

I realize now, really big proposals get often sadly, 'not' used bec. they're TOO complex to implement, I wanted to ask for these things, as it'd really help me make Godot visual script a MUCH nicer experience and, I want to make Godot 4 visual script tutorial, and HOPE these things could be ready, so I could share my new, ' cool ' theme, and use it in, the tutorial, which takes you from non - coder, to visual script master and, also teaches a bit, of written code . .

My plan is, to make ' Hello World ', using _ready, in visual script as, the intro, and explain how, it works in written code, also <3 so, it's visual script /beginner written code tutorial, but I want a theme, editor look that ROCKS, so it's a nice experience, please help, me achieve this dream <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I hope we can get a special Theme /editor settings tab, for the ' GraphEdit ' or, visual script canvas, with some basic stuff revealed, I tried making a ' custom ' theme, but it had to re-start, after every single change, and it took, a long time, was super - complicated . . I know visual script is new, to Godot 3.0, but it's amazing, and the MORE stable an experience I can make, the nicer it will be, hope to share the theme, one day <3

Please, expose some basic settings, in the ' Editor settings ', so we can make a stable, well - running Visual script experience, I have MANY ideas, I'll make some-thing nice, don't worry . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
<img width="917" alt="Skærmbillede (1114)" src="https://user-images.githubusercontent.com/61069740/109374143-668e1a00-78b3-11eb-9b65-121ac0509b62.png">

Right now, Text Editor has many settings, pls. make Graph Editor settings, where one can change certain settings, like color, even pattern of lines, and opacity . . It will also make ' visual shader ' panel nicer, to use <3

I make TOO big proposals, so I limit it, to these, with these, I can make Ultimate Visual script theme and, have much more fun, using Godot <3 Thx . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I tried making a custom theme, but every time I re-started the engine, the fonts were very weird, and scaled down . . I had to open the custom theme again, for it to work, not sure, if bug, it was very tedious, and to see results, I had to re-start the engine, making it very tedious . . </3 . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, the Graph Editor is used for visual shaders, and visual scripts . . For me, it's super - important, I can't make games without Visual script, I want to make it more stable, well - running and, competent . . And, the theme, ' look ' is a BIG part, of making it a ' nice ' experience / work . . <3 Thx . .

ps. I made 18 part ' make 3D game using Visual script, in Godot ', about 10 - 12 hours, want to have an even better theme, for the viewers, so on . . for Godot 4 updated version, of this . . <3 I see amazing potential in Visual script, with these features, I can take it closer, to it's potential, making it rock - solid and, amazing . . <3 . .

All I'm asking for, is that these settings, can be ' found ' in, ' Editor Settings ' <3

**Comment by Calinou** [comment]
I don't see a practical use case to using dashed/dotted lines in GraphEdit, unless they're being used to represent an actually *different* kind of line. Are there any scenarios where a different color or opacity wouldn't suffice to convey that a connection line is different from another?

**Comment by fire** [comment]
This issue proposes to solve making the Visual Scripting experience more stable, easy to use, and  strong.

1. > I would REALLY like to be able to set opacity, on major VERTICAL lines, major HORIZONTAL lines, see image above . . also the smaller VERTICAL lines, and smaller HORIZONTAL lines, color and opacity . .
2. > The next thing is, I'd really like the ability, to make the lines have a few, different ' pattern ' or, even ' dither ' looks, like this . .

It is unclear how opacity and dashes achieves this.

**Comment by Zireael07** [comment]
@fire: I'd read not that (badly written sentence) but the issue title (make the editor more customizable). Opacity and dashes are certainly elements of customization, but like @Calinou I fail to see the ultimate goal in this.

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
