### ISSUE TITLE
Add a priority system for controlling node execution order

### ISSUE THREAD

**Issue by e344fde6bf** [godotengine/godot-proposals#2368]
### Describe the project you are working on

A 3D platformer. It uses kinematic bodies that can have complex interactions with each other.

### Describe the problem or limitation you are having in your project

The physics calculations for kinematic bodies are processed individually, and the order that they are processed in can affect the final outcome ([more discussion on this](https://github.com/godotengine/godot-proposals/issues/2332 )). In many situations, it is necessary to control the execution order to get the correct result.

For example, consider a platformer game were the player can ride on top of an enemy controlled by AI. The player can't be moved first since it depends on how the enemy moves.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A priority system should be introduced that allows fine grained control over the execution order of nodes without having to modify the scene tree.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The priority system would be used to control the execution order of nodes. Each node would be assigned a numeric value that determines their execution order. This value could be set by code or in the editor, or if no value is assigned it would use the default priority (probably scene tree order). The values would be chosen such that `p<0` high priority, `p=0` default priority, `p>0` reduced priority, this way things can easily be pushed to the front or back of the execution order.  Nodes have different callbacks (`_process()`, `_physics_process()`, etc) that may require different priorities so it should be possible to set there priorities separately.

It may be further useful to break up the priority into groups. This would would work by treating the priority number as group priority + member priority. For example, consider a game were enemies can stack on top of each other. At runtime, we want to reshuffle their priority relative to each other, but we don't want to mix up their order with other entities (platforms, projectiles, the player, etc). So by using a group priority, we could keep their execution order fixed relative to other entities and use the member priority to control their execution order relative to each other.

A priority system might have some other benefits:

* It helps make code execution more deterministic as it doesn't rely on whatever arbitrary order the scene tree is setup as.
* It could help performance by improving cache locality since we'll often be processing similar nodes together.
* The `Sync to Physics` feature is no longer necessary with the changes mentioned in https://github.com/godotengine/godot-proposals/issues/2332.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature will be used very often and the potential workarounds have various downsides:

* We could manual construct the scene so that nodes have the right execution order. This is unpractical for all but simple projects.
* We could dynamically rebuild the scene at runtime. This means we have to build the scene tree twice, adds unnecessary complexity to projects, and requires more work to maintain the correct execution order.
* Re-parenting nodes isn't an option since [it doesn't play nicely with physics](https://github.com/godotengine/godot-proposals/issues/2332#issuecomment-787000826).
* [Write messy code like this](https://github.com/godotengine/godot-proposals/issues/2332#issuecomment-787030173)

### Is there a reason why this should be core and not an add-on in the asset library?

This feature would be used by many different projects. As an add-on, it would not be able to achieve the same level of convenience or performance.

**Comment by pycbouh** [comment]
> It helps make code execution more deterministic as it doesn't rely on whatever arbitrary order the scene tree is setup as.

How is tree order not deterministic or "less" deterministic? Same tree order gives same execution order (unless there is a bug in the engine).

**Comment by Calinou** [comment]
Did you take a look at the `Node.process_priority` property?

**Comment by e344fde6bf** [comment]
> Did you take a look at the Node.process_priority property?

I'm sure I looked for this before I made this proposal.  I tried it, and it does what I want. I'm feeling pretty dumb now.

> How is tree order not deterministic or "less" deterministic?

I guess this a bad word choice here. What I mean is if your level is setup like this:

1. Enemy
2. Platform
3. Enemy
4. Platform

You'll get different result than if you do this:

1. Platform
2. Platform
3. Enemy
4. Enemy

They'll both produce the same results run to run, but when constructing multiple scenes it's much easier to get consistent behaviour between scenes using the second approach.

**Comment by pycbouh** [comment]
> I'm sure I looked for this before I made this proposal. I tried it, and it does what I want. I'm feeling pretty dumb now.

Hey, no worries, happens to the best of us. Though it's a good reason why we ask people to gather feedback from community before opening a proposal, as everyone may miss something. Hop on one of [our community platforms](https://godotengine.org/community) in case you want to discuss things with other Godot users 🙂
