### ISSUE TITLE
Save the exact Godot version number to `project.godot` and display it in the project manager

### ISSUE THREAD

**Issue by RobKohr** [godotengine/godot-proposals#237]
**Describe the project you are working on:**
I am working on a [Godot Asset Store](https://godotasset.store)

**Describe the problem or limitation you are having in your project:**
Looking at files in project directories isn't helpful in identifying what version of godot this project works with (or at least was developed with). 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
I am going to have it so users can easily submit godot projects, and it would be helpful to know what version of godot a project was built with

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
N/A

**Describe implementation detail for your proposal (in code), if possible:**
Whenever config or scene files are saved, it will add something like

```godot_version=3.1```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, this would have to be a fundamental change in how the engine saves data files

**Is there a reason why this should be core and not an add-on in the asset library?:**
This would be useful in the general evolution of godot for handling file versions and migrations to newer versions of godot. If something in one version was different in another, when upgrading, such differences can be highlighted.

**Comment by nobuyukinyuu** [comment]
It's a bit obtuse, but you can determine roughly incompatible project formats using `config_version` in project.godot.  Currently on version 4 for Godot 3.1, and version 3 for Godot 3.0.

**Comment by KoBeWi** [comment]
You'd have to do the same for scripts and it wouldn't work that well in this case. Maybe just add a mandatory field about Godot version that someone has to fill when uploading to the store?

**Comment by Calinou** [comment]
> Maybe just add a mandatory field about Godot version that someone has to fill when uploading to the store?

This is what we currently have, but it leaves to be desired as there's little granularity permitted in the supported version ranges. (This could be improved on the backend by supporting [semantic versioning](https://semver.org/) range strings.)

**Comment by aaronfranke** [comment]
See also https://github.com/godotengine/godot-proposals/issues/427 and https://github.com/godotengine/godot/pull/31171 (if implemented, would solve this proposal)
