### ISSUE TITLE
Expanding GraphEdit's Theme for Connections

### ISSUE THREAD

**Issue by mechPenSketch** [godotengine/godot-proposals#2371]
### Describe the project you are working on
A [FSM plugin](https://godotengine.org/asset-library/asset/706), which comes with a diagram.

### Describe the problem or limitation you are having in your project
Even with GraphEdit's Theme's `Bezier Len Pos/Neg` both set at 0, the node's connection still make that curve when to node is to the left of from node. For example, below shows the issue with nodes ToWait > Wait:
<img width="570" alt="fsm2" src="https://user-images.githubusercontent.com/15977859/109383549-10a48b00-7922-11eb-8865-09e51fc02b00.PNG">

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
On the Theme for GraphEdit, have an option on what kind of line is to be drawn for connections, whether it's straight or the usual curve.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Here's the best of what I could think of:
In place of `Bezier Len Pos/Neg`, we have a Resource (or Curve2D to be exact) `Connection Line`, which hold data for how the line should be drawn. The `Bezier Len Pos/Neg` property could be stored in the Resource.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can think of other solutions, but they'll take a few extensions of classes at best.
* I could use other control nodes aside from GraphNode, but I'll have to program them to scale accordingly when GraphEdit is zoomed or moved.
* In place of connections, I could use Line2D, but I'm not sure whether using Node2D node in Control is the right way. 

### Is there a reason why this should be core and not an add-on in the asset library?
The curved line used to draw a connect is programmed at a C++ level, not native gdscript.

**Comment by Jummit** [comment]
Would be fixed by godotengine/godot#40513

**Comment by mechPenSketch** [comment]
Closing this proposal as it's fixed by https://github.com/godotengine/godot/pull/51952
