### ISSUE TITLE
some "environment" settings enabled in camera preview only

### ISSUE THREAD

**Issue by ViktorEvil** [godotengine/godot-proposals#2372]
### Describe the project you are working on
3D mobile dungeon puzzle game

### Describe the problem or limitation you are having in your project
Enabling DOF blur "near" and "far" is showing in all scenes making it hard to navigate in a blurred view. I have to constantly enable and disable DOF as I am switching views and scenes

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Have the option to show some environment option in just the camera preview.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
A settings pane that can allow different settings enabled or disabled in normal scene views

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
Every developer will benefit from this option as it will make navigation in a blurred or foggy view easyier

**Comment by clayjohn** [comment]
In 4.0 some settings (like DoF) have moved from Environment. I'm not sure if that means they will only show in the "camera preview", but it would be worth checking as this may have already been solved!

**Comment by Calinou** [comment]
Indeed, this has already been solved in 4.0. In the meantime, you can define DoF properties in Environment in a non-tool script so that it doesn't affect the editor;

**Comment by ViktorEvil** [comment]
> Indeed, this has already been resolved in the `master` branch. In the meantime, you can set DoF properties in Environment in a non-`tool` script so that it doesn't affect the editor.

@clayjohn I can't get the Godot 4 nighties to run on my Apple Silicon Mac for some reason it just crashes instantly.

@Calinou thanks I didn't think of setting DoF via a script at runtime.
