### ISSUE TITLE
Add new SceneTree signal `paused_changed`

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot-proposals#2374]
### Describe the project you are working on
A large solar system simulator @ivoyager and an associated 4x game.

### Describe the problem or limitation you are having in your project
I need to know when SceneTree.paused changes for several reasons. Just for one example, our game speed Label changes during pause to display "____ (paused)". Currently, I'm polling SceneTree every frame. This works but is more expensive than it needs to be. I'm also under the impression that using `_notification` is expensive. (Someone please educate me if I'm wrong about that.)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Described in title. Having this will remove my need to poll SceneTree every frame.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Described in title.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
I think it will be used often. It can be worked around by polling SceneTree at some interval or using `_notification`.
### Is there a reason why this should be core and not an add-on in the asset library?
This is core SceneTree function.

**Comment by Calinou** [comment]
With the [pause mode refactoring coming to 4.0](https://github.com/godotengine/godot/pull/46191), is this still relevant?

**Comment by charliewhitfield** [comment]
@Calinou ,
I've always been under the impression that `_notification` would be expensive to override in GDScript. Due to this impression I've avoided it even in my rather huge project. But perhaps this is the special need that requires it...

I wasn't aware of the new 4.0 refactor. On first glance, I don't see how the new ProcessModes affect my proposal (I'd still need to poll or use `_notification`). But I might be missing something.

**Comment by KoBeWi** [comment]
> I've always been under the impression that _notification would be expensive to override in GDScript. Due to this impression I've avoided it even in my rather huge project. But that's my favorite of your alternatives. I'll edit/add that to OP.

It's as expensive as other overridable methods like `_process()` etc. But it's called much less often (the most frequent notifications need to be explicitly enabled). If you use it in one object, it won't have any noticeable performance effect. Also with reworked GDScript in Godot 4.0 it's going to be almost free.

**Comment by Xrayez** [comment]
I know that using a `match` statement is slower than `if/elif/else` chains in GDScript (don't know about GDScript 2.0), and `match` is similar to `switch` in C++ where those notifications are checked, and it's likely that GDScript does not perform optimizations around that for longer list of conditions as in C++ (which generates jump/lookup table in comparison), but this may be already handled by dictionary capabilities...

So, if performance is concern, don't use `match` in `_notification()`. But I'd prefer more readable code with `match`, as in most cases there's nothing to worry about performance-wise until you actually stumble upon serious performance bottleneck.

**Comment by charliewhitfield** [comment]
Closing for lack of interest, and `_notification()` does the job.
