### ISSUE TITLE
[Audio] - Beat detection

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot-proposals#2376]
### Describe the project you are working on
Beamer Laser that changes the pattern to a beat detection

### Describe the problem or limitation you are having in your project
I don't know how I can get a beat detection.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add to the audio a beat detection effect/Node.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I am thinking of a new node with some settings in the inspector like frequency range.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?
I think it belongs to the audio nodes of Godot.

**Comment by pycbouh** [comment]
> I don't know how I can get a beat detection.

Have you tried asking for help on one of our [community platforms](https://godotengine.org/community)? A proposal must justify how the feature would improve your development experience and game functionality. There must exist a limitation within the engine or the editor, that prevents you from achieving your goal. If you don't know how to achieve something at all, you need to do research.

There also needs to be justification as to why this should be core, and not a plugin or a custom module. A plugin or a module can work with Godot's "audio nodes", so this is not a valid exception.

You also need to provide how this feature should work, at least on the empyrical level. It is best if you provide technical details, but at least a description from user's perspective is needed to evaluate and discuss your proposal.

We aim to collect high quality proposals in this repository, not just nice-to-have ideas. Please consider [the documentation](https://github.com/godotengine/godot-proposals) about submitting proposals and what is required from them. I will close this issue until more information is provided.

**Comment by Gamemap** [comment]
Ok, I will remember this.
