### ISSUE TITLE
ConfigFile:  Erase key, Rename section/key

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot-proposals#238]
**Describe the project you are working on:**
Front-end tool

**Describe the problem or limitation you are having in your project:**
I use `ConfigFile` for user config in this project.  User-configurable lists use sections dedicated to them, specifically folder locations.  When removing an entity from this list, currently the entire section must be deleted and rebuilt.  Originally, I was going to delete a key and rename other keys (or shuffle data between keys and delete one at the end of the list), but noticed ConfigFile doesn't have this capability.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
This can solve problems only for specific workflows.  I haven't tested how complex the datatypes for `ConfigFile` values can be, so the solution I was originally going to implement in my project might be wrong-headed and both it and the workaround I eventually settled on may have been more work than necessary.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
**Describe implementation detail for your proposal (in code), if possible:**
```gdscript
var config = ConfigFile.new()
config.set_value("Default", "foo", 0)
config.rename_key("Default", "foo", "bar")  #New method.  Equivalent to the code below

config.set_value("Default", "bar", config.get_value("Default", "foo")
config.remove_key("Default", "foo")   #This method also doesn't exist yet
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Depending on the application, yes.  Users with full control over the input data can design around the limitations of ConfigFile however they please, but the only option they have within `ConfigFile` itself to remove expired or now-useless keys is to erase an entire section.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Implementing this as an add-on would be a lot less elegant and likely require use of file streams and `ProjectSettings.globalize_path()`, as well as reloading the config file or locking it while the operation is performed.

**Comment by Calinou** [comment]
`ConfigFile.erase_section_key()` was added recently, does it fit your use case?

**Comment by Calinou** [comment]
> I haven't tested how complex the datatypes for ConfigFile values can be, so the solution I was originally going to implement in my project might be wrong-headed and both it and the workaround I eventually settled on may have been more work than necessary.

IIRC, a ny data type can be saved, including binary data which will be serialized as Base64 :slightly_smiling_face:

**Comment by nobuyukinyuu** [comment]
Yes it does.

**Comment by Calinou** [comment]
@nobuyukinyuu Sorry, it seems I didn't interpret your reply correctly (I edited my message since then). Is this proposal still relevant? Renaming a key can be done in 3 lines of code, which doesn't seem to be excessive as it's not a common use case.

**Comment by nobuyukinyuu** [comment]
It solves my use case.  Perhaps the ability to rename a section it's still useful as compared to a loop;  for a single key it's trivial.  Shall I close the issue?

**Comment by Calinou** [comment]
@nobuyukinyuu I'll consider this resolved then :slightly_smiling_face: Thanks for opening a proposal either way.

**Comment by AilerNX** [comment]
> This response was originally to address the question if 32426 would address my use case scenario

I'm really sorry, I didn't see this proposal until yesterday. Renaming sections or keys is still relevant?

If it is I'll make an PR, but if it's not, I'm bumping in case someone wants the same thing and is discouraged from ask because of the archived label.
