### ISSUE TITLE
Add a command line flag to get list of export targets

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#2388]
### Describe the problem or limitation you are having in your project
From the command line the documentation states to use the --export flag with an invalid platform name to display a list of valid targets.

Apart from this doesn't actually do it (I raised a bug in documentation for this), and even if it does, it would be better for an actual flag to be present to list all the target platforms rather than invoking an error in the command line

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add an additional command line flag to display available platforms

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
godot --whatever

### If this enhancement will not be used often, can it be worked around with a few lines of script?
You currently have to open up the Godot IDE and select each platform, then write down the exact words, then type them in.

### Is there a reason why this should be core and not an add-on in the asset library?
Because it makes sense from a build perspective

**Comment by Calinou** [comment]
I don't see much point for displaying the export targets explicitly. As long as supplying an incorrect export preset name gives you a list of correct export preset names, I think it's fine.

**Comment by chucklepie** [comment]
As I said, it doesn't. Providing an invalid target simply starts up Godot.

**Comment by chucklepie** [comment]
Thanks, I redid my comment as I found the answer was because you cannot specify a target directory, it must be the current directory only. Is this what you're referring to as being changed?

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/47651 and is available in Godot 3.4 and later, closing. You can use `--export list` (with `list` being an invalid export preset name), and you'll get a list of export presets available in the given project.
