### ISSUE TITLE
XR input events for action bindings

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot-proposals#2389]
### Describe the project you are working on
XR support for Godot 4

*Work in progress* I'll be detailing this proposal out more in the coming days.  To much to write in one sitting :) But please any early feedback is welcome!

### Describe the problem or limitation you are having in your project
In Godot 3 we decided to combine VR controllers with Godots existing joystick handling as the only missing part was spatial tracking.

Time has moved on with VR controllers becoming far more complex in nature. 
OpenVR and OpenXR have gone down the route of an Action based approach very similar to Godots own input map system. 
It makes sense for us to follow that direction and make it easy to just use the input mapping system to support XR SDKs that do not have a build in action system.

XR controllers are far more varied then normal game controllers ranging from anything from your standard positional tracked controllers like the Vive wands to vision tracking of a players actual hands and that's not even covering the tip of the iceberg.

While controllers fixed inputs like buttons and trackpads/joysticks the industry is quickly identifying new types of inputs on these devices, inputs on vision based tracking possibly the most interesting where hand poses and/or gestures are directly converted to action inputs. 

At the same time we are also getting tracked inputs, originally a single tracked location per controller it is now often customary to track various locations on controllers. Currently these can't be defined in the current input map.

Lastly, and this one is a little out of place but I think it makes a lot of sense, and that is to map outputs.
Right now the only available outputs are rumbles on controllers but Godots current system really falls short of the needs of most XR devices but even for normal game controllers.
Rumble control nowadays have more variables then just strength but also when we look at XR we're seeing things like haptic vests hit the market. 

Lastly, and this is one area that I'm not happy about but it is what it is and we have no control over this. 
OpenXR is designed so the actual input mapping is performed in the runtime taking that control out of the hands of Godot. The input map becomes a blueprint that is sent to OpenXR and it will do the rest of the input and output handling with us just interacting with the actions themselves.
The justification here is two fold:
- many game developers simply don't bother and present VR games as is, this ensures XR always caters to people who are either left handed instead of right handed
- new input devices are hitting the market daily and moving the re-binding into the OpenXR runtime ensures support for devices the original game developers did not originally have access to.

However this also means that the proposed functionality will be far more powerful when this functionality is left to Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are a number of enhancements possible to Godots input map that help in solving the above mentioned issues.

At the bare minimum it involves adding XR specific input events that we can bind, these may change but the current ones I'm thinking off are:
- InputEventXRButton : informs of a state change of a button input 
- InputEventXRAxis : informs of a state change of axis based input (triggers, joysticks etc)
- InputEventXRPose : informs of a state change of a pose (location and orientation of a controller or any point tracked on the controller.
- InputEventXRAction : this is an internal event purely to deal with OpenXR doing the action mapping for us and informs of any OpenXR state change directly on the action. It will not be present in the mapping UI.

Adding support for "output events", have to further design this so this is a blind spot in this proposal but having a better way to deal with output haptics is something I want to make part of this work.

Adding a type and restrictions to actions. Right now all actions are design to be on/off things. A user pressed a button, an action is triggered. With adding analog inputs to actions this has already gotten a little more muddy but the actions are still only triggered as a button and it's purely querying the value. I ran into issues with non XR games here as well, its why I don't use the input map for my vehicle demo while I'd really like to and this enhancement would solve that too.
With the XR changes we'll need to build on this system and type actions:
- boolean (basically the default behavior we have now)
- value (analog input ranging from -1.0 to 1.0)  
- axis (joystick input with two axis handled as a unit)
- pose (location and rotation based info)
- haptic (an output action)

This should then also restrict which events can be bound to the action. You should be able to mix boolean and value with Button/Action/Motion events but pose and haptic are specific.

Another restriction we should look at adding is what devices an action is restricted to. This again is important in XR as you may restrict actions to just left hand controllers, or just right hand controllers, or just feet controllers, or treadmills, or gun props, etc.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Most of this is described in the section above but going into further detail I'll be adding more info here soon as I work out what the proposed events will have as options, how I propose we do the UI changes to the input map, and detail out more about actually implementing the XR events from a XR interface perspective.

One important discussion point that I will dive into already is that of determining the devices, input and outputs that will be selectable in the UI.

OpenXR is gone through some level of standardization but basically they assume you hard code these into your application and that requires source code updates when more options become available. 

The ideal scenario would be for the XR interface to have an interface where we can query the available options and this is the current line of thought I have. As OpenXR doesn't have any enumeration or discoverability API this still involves hard coding the options for that interface but other interfaces could decide to offer much more targeted data.
The flip side of this solution is shown with shortfalls in plugins like the Oculus Quest plugin. this plugin only runs on the Quest device, not on the desktop and therefor the editor has no way of interogating the interface. 
Either we introduce a way for this meta data to be presented so it doesn't require a running plugin or we need to introduce some other way to query this data.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This enhancement is critical to XR support

### Is there a reason why this should be core and not an add-on in the asset library?
This enhancement can only be done in the core.

**Comment by BastiaanOlij** [comment]
Closing this proposal. As there were too many differences between Godots input system and OpenXRs action system, we implemented a purpose build solution inside of the OpenXR module.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/2273 (for future reference).
