### ISSUE TITLE
Suggest function names in the signal connection dialog

### ISSUE THREAD

**Issue by evsey9** [godotengine/godot-proposals#239]
**Describe the project you are working on:**
I am currently working on a 2D physics puzzle-platformer. I want to make a system where each component has input signals that trigger specific functions, and output signals, and you can easily connect different component objects through the editor to quickly design puzzles.

**Describe the problem or limitation you are having in your project:**
I plan to have multiple different objects/components in a scene that would be connected using signals from levers/buttons/pressure plates/etc. to the components. Currently, there is only very simple and basically useless signal name suggestion - it consists of _on, the node name and signal name, which does not represent any functions that already might be in the code, requiring me to go check the code frequently so that I make sure to use the already existing functions and dont accidentally make a new one.
My proposal is a simple feature: show suggested function names in the editor when you are connecting a signal to another node (It could show all function names that start with _ (excluding _ready, _process and _physics_process) or by some other criteria .)

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
This feature would allow for faster and easier creation of different rooms/puzzles involving many different types of objects without having to look at the code constantly.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/7791364/69012547-e16e4280-0998-11ea-81b6-4bc66c19da43.png)

This is how the signal connect screen could be changed to look like, or maybe decrease the size of the "Extra Call Arguments" window on the right, since it takes up 50% of the space.

**Describe implementation detail for your proposal (in code), if possible:**
sadly not experienced with developing for Godot

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I am not sure you can work around that with a few lines of script

**Is there a reason why this should be core and not an add-on in the asset library?:**
This feature would also allow for people less experienced with code/not willing to look through huge amounts of code to easier work with signals, and prevent accidental creation of duplicate functions, resulting in faster code development.

**Comment by bojidar-bg** [comment]
Note that there should probably be a toggle for switching between script-defined methods and engine-defined methods (such as `play` or `queue_free`).
