### ISSUE TITLE
Add the Dracula theme as a preset theme option

### ISSUE THREAD

**Issue by likeich** [godotengine/godot-proposals#2392]
### Describe the project you are working on

The Godot editor and personal Godot games.

### Describe the problem or limitation you are having in your project

The default and current preset themes do not look very good and adding a new (good-looking) preset option for Godot 4.0 would make it feel fresh. (Preview below)

![Screenshot from 2021-03-01 17-17-39](https://user-images.githubusercontent.com/57882701/109831147-29a48900-7c0d-11eb-8f6a-d07b15607cd7.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding the Dracula Theme (MIT License) as a preset option for both the Godot Editor Theme and Text Editor Theme.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I've already implemented it in my own branch, I figured I would propose it here before issuing a pull request to see if the main contributors would be interested in it and to get feedback. My branch can be found here: https://github.com/godotengine/godot/compare/master...likeich:dracula_theme
The above screenshot is from this branch.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is already a Dracula Theme for Godot that can be downloaded and installed using the terminal/command line, but this takes time that most users would not spend looking for a theme. (https://draculatheme.com/godot)

### Is there a reason why this should be core and not an add-on in the asset library?

An add-on won't suffice because it requires changing multiple settings in the editor, to my knowledge this can't be done through the asset library and I don't think any other themes are there either. The editor already includes the Solarized Theme which is also MIT-Licensed, Dracula is another extremely popular theme that looks great with Godot.

**Comment by Calinou** [comment]
As far as I know, there are no plans to include additional syntax themes – it's impossible to please everyone with the default selection. Instead, we refer to the community to provide those themes. See [godot-syntax-themes](https://github.com/godotengine/godot-syntax-themes) which is an official repository offering many themes. It accepts pull requests, so feel free to send in your own themes as well.

**Comment by likeich** [comment]
Gotcha, I was not aware of that repo of themes. In terms of the faint borders, I actually prefer that, I think it makes for a much cleaner look once you already know where the different panels are. Thanks for the info.
