### ISSUE TITLE
Remove current export template version from "Installed Versions" list in Export Template Manager

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot-proposals#2394]
### Describe the project you are working on
N/A (not project related).

### Describe the problem or limitation you are having in your project
In the "Export Template Manager" popup, current version is listed twice if installed: at the top under Current Version label, and below under Installed Versions label:

![v1](https://user-images.githubusercontent.com/26509794/109853452-30a3b980-7c56-11eb-88ab-b17c5bffe5ff.png)

I propose to remove it from bottom list because:

1. unnecessary duplication (you can already see that it's installed due to "(Installed)" suffix in its name, and due to the button next to it saying "Uninstall"
2. possibly very specific and personal case, but one might want to uninstall all previous export templates by just clicking all "Uninstall" buttons, and accidentally uninstall current one since it's in the bottom list and didn't expect it to be there.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Just remove current export template from the "Installed Versions" list, like so:

![v2](https://user-images.githubusercontent.com/26509794/109853048-c25ef700-7c55-11eb-9773-3009e5c8b75d.png)

Additionally, rename "Installed Versions" to "Other Installed Versions" to make it less misleading.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I'm assuming it's fairly trivial to make the item not appear in the list below.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
N/A

### Is there a reason why this should be core and not an add-on in the asset library?
N/A

**Comment by pycbouh** [comment]
> Additionally, rename "Installed Versions" to "Other Installed Versions" to make it misleading.

Hopefully, to make it *less* misleading, though 🙃

**Comment by wingedadventurer** [comment]
Oops! Good catch, corrected it. :D
