### ISSUE TITLE
Add more color components to curve texture

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#2403]
### Describe the project you are working on
Various VFX

### Describe the problem or limitation you are having in your project
This is a very specific case for particles.
The correct way to pass a curve into a shader is to make a curve texture.
The curve texture is currently an R texture with a single component, which means that
for multiple curves you have to use multiple curve textures.
Because of the nature of particles, when you sample into a curve you generally sample
based on the lifetime, so you'd sample once and get N values from the texture.
Currently, instead, you have to bind N textures and sample N times in the shader.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
If a curve texture can carry multiple curves, there's less uniform binds wasted for achieving the same goal

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
CurveTexture gets an integer number representing the number of components that it supports.
The editor then shows multiple curves in the curve editor, which can be toggled for visibility.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This enhancement can definitely be worked around with a custom resource.

### Is there a reason why this should be core and not an add-on in the asset library?
See proposal #2404

**Comment by Xrayez** [comment]
> The curve texture is currently an R texture with a single component, which means that
> for multiple curves you have to use multiple curve textures.

See also #604.

**Comment by Calinou** [comment]
Alternatively, implementing https://github.com/godotengine/godot-proposals/issues/1933 would fulfill the need originally described here.

**Comment by QbieShay** [comment]
@Calinou no, controlling individual components in a gradient texture is not easy or user friendly at all. Even with components split, seeing them as color intensity is not a good visualization, and it's highly dependent on how good the monitor is. i don't think that would be a substitute for this at all.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/50054, closing.
