### ISSUE TITLE
Make particles use random ranges

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#2405]
### Describe the project you are working on
Various VFX

### Describe the problem or limitation you are having in your project
Most particle properties that support random only have a "base value" and a "random" percentage.
This approach is not optimal, in particular for scale: it is not possible to have particles range
from scale 0.9 to 1.3 for example, because the random of the scale is always done between the value
specified, and 1.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Change the way that random is used in particles material: instead of having a randomness value, have
2 sliders that specify min and max values.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
remove value + random range with min and max values

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It requires a custom particle shader

### Is there a reason why this should be core and not an add-on in the asset library?
This is an improvement for the default particles material.

**Comment by reduz** [comment]
The problem with ranges is that they are good when you want to use ranges, but when you don't you have to edit two values instead of one.

**Comment by QbieShay** [comment]
@reduz I think that this can be worked around it with an editor

**Comment by robbertzzz** [comment]
> The problem with ranges is that they are good when you want to use ranges, but when you don't you have to edit two values instead of one.

A workaround for that could be added, similar to how the other engines do it. Unreal has a drop down list from which you pick the type (simple, random between two values, and some more). The way it works now is really unclear, I've got no idea what the value you put in the random field really means.

**Comment by reduz** [comment]
Alright, then I suggest adding this to the proposal then.

**Comment by QbieShay** [comment]
I'll edit with a quick mockup :)

**Comment by robbertzzz** [comment]
Heres another thought: if you choose to keep the random, it would make more sense to randomize between the value and 0. It's not intuitive that 0.8 randomizes up and 1.2 randomizes down. Plus, what happens when the initial value is 1? Nothing? It's equally unintuitive that 1 and -1 randomizes differently, though negative values aren't used much or at all.

Figuring this out only today explains so much of the trouble I had in the past with this system...

**Comment by 2plus2makes5** [comment]
I prefer to specify explicit values like the proposal, but if you really want to keep value and random you could use this formula for the range of values: [value-random, value+random]

example:

value: 0.8
random: 0.5

would return values from 0.3 to 1.3.

**Comment by QbieShay** [comment]
@2plus2makes5 i like your idea as well, although i find the idea of random +- interval a little bit less user friendly: you don't immediately see on screen the possible values, like you'd do with min and max.

**Comment by 2plus2makes5** [comment]
@QbieShay 
I guess that another way it could be done is:
[value, value+random]
 
example:

value: 0.8
random: 0.5

would return values from 0.8 to 1.3

it could work with negative values too:

value: 0.8
random: -0.5

would return values from 0.3 to 0.8

**Comment by QbieShay** [comment]
After talking in the rendering channel on rocket chat, we established that the simplest way is to indeed follow @2plus2makes5 approach with value + random, which does the same thing, it's slightly less clear, but doesn't require fiddling with the get/set property methods.

**Comment by Calinou** [comment]
Which one should we settle for, though?

- Value ± random
  - This makes it easier to introduce more randomness without impacting the *average* value.
- Value + random
  - This makes it possible to always see the lowest bound, and the highest bound can be mentally calculated more easily since it's a simple addition.

**Comment by 2plus2makes5** [comment]
Personally i think that Value ± random is the most user-friendly option hence the best one in my opinion.

**Comment by QbieShay** [comment]
value +- random it is!

**Comment by KoBeWi** [comment]
As noted in the first comment (and the linked PR), this doubles the amount of values to edit. We could make it more friendly by adding a dedicated property editor for ranges. Here's a quick mockup:
![](https://user-images.githubusercontent.com/2223172/126777340-a6392086-af59-4365-879d-b7687a81aee5.png)

However there is no way to have one editor for 2 values without using some hacks, so maybe instead of having min and max value, we could use a Vector2, where x is min and y is max? Then we'd have a property hint that would make it edited with a range editor.

**Comment by QbieShay** [comment]
This is how it looks in the current PR:

https://user-images.githubusercontent.com/7917475/126789440-8ccc14ae-439f-4d8e-b8e6-620962866265.mp4

I don't think that it is unfriendly

**Comment by Calinou** [comment]
> I don't think that it is unfriendly

It does take more vertical space than it did previously, but to be fair, the Vector2 inspector would take a similar amount of space.

**Comment by QbieShay** [comment]
> It does take more vertical space than it did previously, but to be fair, the Vector2 inspector would take a similar amount of space (regardless of whether Horizontal Vector 2 Editing is enabled in the Editor Settings).

Previously we had two variables (value and randomness) and now we have again 2 values (min and max). Not sure what you mean when you say it takes more space than before.

**Comment by KoBeWi** [comment]
> We'll likely need a dedicated inspector to be implemented, but this can be done in a future PR.

That's basically what I said. Using a regular Vector2 wouldn't make much sense, as editing x/y isn't very intuitive in this context.

> I don't think that it is unfriendly

Well, you are right. Maybe it doesn't need any improvements 🤔

**Comment by AndreaCatania** [comment]
> 
> 
> As noted in the first comment (and the linked PR), this doubles the amount of values to edit. We could make it more friendly by adding a dedicated property editor for ranges. Here's a quick mockup:
> ![](https://user-images.githubusercontent.com/2223172/126777340-a6392086-af59-4365-879d-b7687a81aee5.png)
> 
> However there is no way to have one editor for 2 values without using some hacks, so maybe instead of having min and max value, we could use a Vector2, where x is min and y is max? Then we'd have a property hint that would make it edited with a range editor.

I like this editor, which is quite immediate to understand. However, use `Vector2` in this case is quite weird. In my mind `Vector2` indicate spatial positions. I think we should add `MinMax2` (maybe just by overriding `Vector2`, but adding some more methods to it). It should be much cleaner, code wise.

```c++
v.y == min
v.x == max

v.get_min() == min
v.get_max() == max
```

**Comment by robbertzzz** [comment]
I think that UI is pretty weird when there are no minimum/maximum values for the field. This clearly doesn't go below 0 and doesn't go above some number, but what are those numbers? And how would it work when the values are really close together, would I have to move one slider out of the way to be able to use the other?

**Comment by Calinou** [comment]
> And how would it work when the values are really close together, would I have to move one slider out of the way to be able to use the other?

It would likely move the Min value if you move the mouse cursor to the left, and move the Max value if you move the mouse cursor to the right.

**Comment by robbertzzz** [comment]
> It would likely move the Min value if you move the mouse cursor to the left, and move the Max value if you move the mouse cursor to the right.

What if I want to narrow the range even more? You could use the number fields in all those cases of course, but those already allow for dragging numbers up/down. There's not much added value to the double slider imo
