### ISSUE TITLE
Add an easy way to get the self colliding area in area monitor callback

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#2407]
### Describe the project you are working on
Top-secret C++ module 👀

### Describe the problem or limitation you are having in your project
I have an object that manages many small objects. Each of them has an Area2D assigned. I don't use nodes, I just use `Physics2DServer.create_area()` and store RIDs and manage them manually.

What I want to achieve is that when an external area (i.e. not managed by my object) collides with one of the small areas, I emit a signal telling which of my areas collided and with what. In my old solution, I had one giant area with lots of shapes. The problem I encountered was that when I collide with a shape, it registers only one collision with the big area. So when I collide with lots of overlapping small shapes, I only get one callback per physics frame.

So this is why I changed my "big area, lots of shapes" approach to "lots of areas, lots of shapes". **Now as for my actual problem I open this proposal for**, I have this manager object and call `area_set_area_monitor_callback()` for each of these areas, but the receiver of the callback is my main object. And this callback assumes that each area subscribes to a separate object. So when my callback is called, I don't know which of my small areas collided.

EDIT:
Here is a diagram that illustrates my case:
![Diagram](https://user-images.githubusercontent.com/2223172/110143638-b8650180-7dd7-11eb-97e1-698ddee0ac6b.png)
There is no way to know the "unknown" area if the call isn't tied to it. Area2D has single node->single area, so it doesn't have this problem. I have single node->multiple areas.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
There should be some way around this limitation of monitor callback, so that I can have callback on a single object, but I know exactly what pair of areas have collided.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I see at least 3 solutions:
1. Add `self_area` argument to `area_monitor_callback()`, so when it's called, you know both areas that have collided.
2. Add another callback. When area collides, it calls the regular `area_monitor_callback()` and the second callback e.g. `area_monitor_callback2()`, which has the `self_area` argument mentioned above.
3. Add a variable set for the time of the collision, so inside the callback you can e.g. do `Physics2DServer.get_current_self_area()` or something.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, it needs changes in physics server.

### Is there a reason why this should be core and not an add-on in the asset library?
It's as core as it can be.

**Comment by pouleyKetchoupp** [comment]
It seems like a good idea to allow this use case.

I would actually go for a more generic solution, by adding an optional user_data (Variant) argument when you register the callback, so in your case it could be an index to the corresponding area.

That could be done for both `area_set_area_monitor_callback` and `area_set_monitor_callback`.

**Comment by KoBeWi** [comment]
I actually found a workaround. I have a custom struct that keeps information for each of the small objects, so I just changed it into GDCLASS and made into callback receiver. It might be slightly less performant, but I don't see noticeable overhead.

So this proposal is mostly relevant if you don't have such helper structs, not sure if such cases exist. I guess this could be closed, at least for me.

**Comment by KoBeWi** [comment]
Resolved by https://github.com/godotengine/godot/pull/54471 (you can bind user data to Callable)
