### ISSUE TITLE
Change the default path in Project Manager when launching the Editor in self-contained mode

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot-proposals#2409]
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Make the path for new projects and for the scan button default to the Godot file when in portable mode (`_sc_`) to make projects easier to create/scan.
Or an editor setting to choose a path.
### Is there a reason why this should be core and not an add-on in the asset library?
,
,
,
I 'm sorry but the other questions are Project spezific and my feature request is for the Godot-Project-Manager so I can't answer these.

Should I remove these?

**Comment by Calinou** [comment]
> Make the path for new projects and for the scan button default to the Godot file when in portable mode (_sc_) to make projects easier to create/scan.

Which default values do you suggest? We intentionally don't use `$HOME/Documents/Godot` by default as this would require creating a Godot folder, even if the user never uses it (which can be seen as unnecessary cluttering).

> Or an editor setting to choose a path.

This is already available in the Editor Settings as Default Project Path. It's complimented by Autoscan Project Path which can be set to the same value.

**Comment by pycbouh** [comment]
Since this talks about self-contained mode, I assume "default to the Godot file" means the folder with the Godot executable.

**Comment by Gamemap** [comment]
Yes, I meant that the default path for new projects is in the folder with the Godot executable.
Are these the settings for the Project Manager?
![Settings](https://user-images.githubusercontent.com/71942164/110187484-d0a94080-7e18-11eb-9ca3-180c54d24428.PNG)

I understand your solution for the XY problem.

**Comment by Gamemap** [comment]
I think this feature request can be closed now that there are these settings in the editor and therefore it is no longer necessary, but the original idea was to change the default project path to the folder with the Godot executable when running in self-contained mode.

Sorry that I have expressed myself in a misleading way.
PS: Maybe you can add the link to the XY problem in a comment to the template for better understanding.

**Comment by Calinou** [comment]
> I think this feature request can be closed now that there are these settings in the editor and therefore it is no longer necessary, but the original idea was to change the default project path to the folder with the Godot executable when running in self-contained mode.

We can actually change that, but I don't remember what the current behavior is like.

**Comment by Gamemap** [comment]
Ok, I think it is like the picture above. (I haven't changed anything)

**Comment by Calinou** [comment]
On second thought, we shouldn't change the default project path in self-contained mode as this will break the Steam distribution. People shouldn't be putting their projects in `C:\Program Files`, and that will happen if we default the location to the executable path :slightly_smiling_face:

**Comment by Gamemap** [comment]
Thanks for the help.
