### ISSUE TITLE
Assign inline comment of an export variable to its inspector hover annotation

### ISSUE THREAD

**Issue by chepulis** [godotengine/godot-proposals#2413]
### Describe the project you are working on
A medium-sized indie game, irrelevant to the proposal. It has lots of scripts.

### Describe the problem or limitation you are having in your project
Export variables can be documented in scripts — invisible from the editor inspector.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
This is an inspector variable that displays a useful annotation on hover:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/11724303/110218104-706dd980-7ec0-11eb-8cdb-f1204ee2424f.png">

This is a custom export variable i've created in my script:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/11724303/110218116-7e235f00-7ec0-11eb-85e3-2d1679c7b718.png">
 It has a useful inline comment documenting its function.

That comment could be displayed here:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/11724303/110218129-95fae300-7ec0-11eb-9591-1f3518608770.png">

And that would make everybody's life a little easier. Especially when the work is done in teams.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Whoever is redeveloping GDScript can, i'm guessing, include these comments. @vnen?

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It's a minor usability improvement, the workaround is the status quo. But it is something that will deliver bits of utility very often.

### Is there a reason why this should be core and not an add-on in the asset library?
It's GDScript and editor. As core as it gets.

**Comment by pycbouh** [comment]
Documentation was already implemented based on #993 in https://github.com/godotengine/godot/pull/41095
