### ISSUE TITLE
Start/Test if program in administrator mode

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot-proposals#2415]
### Describe the project you are working on
Program updater
### Describe the problem or limitation you are having in your project
Save files to Windows ProgramFiles.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
OS.request_permissions() to restart the program in administrator mode on OS. I don't know how other programs write there. (maybe regedit on windows at installation?)
Also OS.has_permissions() to test if it is in admin mode.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
OS.request_permissions()
OS.has_permissions()
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
Most programs are installed in this directory to test whether they can write, should this function be in the core.

**Comment by Calinou** [comment]
This can be done by running a PowerShell script that elevates privileges such as [`sudo.ps1`](https://github.com/lukesampson/psutils/blob/master/sudo.ps1). You can bundle this script with your exported project.

**Comment by Gamemap** [comment]
How do I run this script? With `OS.shell_open()` ? Do I have to add arguments?

**Comment by Gamemap** [comment]
I found this: https://godotforums.org/discussion/19583/checking-for-admin-privileges 
I think I can close this now.
