### ISSUE TITLE
Rename `get_ok()` and `get_cancel()` to  `get_ok_button()` and `get_cancel_button()`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2418]
### Describe the project you are working on
plugins

### Describe the problem or limitation you are having in your project
there's `get_ok()` in `AcceptDialog` 
there's `get_cancel()` `ConfirmationDialog` 
there's `get_close_button()` in `AcceptDialog`.
That sounds inconsistent.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Renaming some of this methods would make API more consistent (in terms of naming).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
There are two options:
1. Rename `get_close_button()` to `get_close()`
2. Rename `get_ok()` and `get_cancel()` to  `get_ok_button()` and `get_cancel_button()`

I prefer (2), this makes the names of these methods clearer.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
—

### Is there a reason why this should be core and not an add-on in the asset library?
—

**Comment by pycbouh** [comment]
This was already tracked in https://github.com/godotengine/godot/issues/16863 and implemented for master in https://github.com/godotengine/godot/pull/44389.
