### ISSUE TITLE
Add `ok_button_text` and `cancel_button_text` properties to `ConfirmationDialog`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2419]
### Describe the project you are working on
plugins

### Describe the problem or limitation you are having in your project
If I want to change `ConfirmationDialog` `Ok` or `Cancel`  buttons text I have to do this only using code, 
this can lead to unnecessary increase in the project codebase.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Adding `ok_button_text` and `cancel_button_text` properties would solve the problem. One could set text using `Inspector`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`AcceptDialog.ok_button_text()`
`ConfirmationDialog.cancel_button_text()`

- Q: why only `text` property?
A: I think other properties of these buttons are not used often.
One can still use `get_ok()`/`get_cancel()`

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This could be worked-round using a script like
`get_ok().text = ..`

### Is there a reason why this should be core and not an add-on in the asset library?
Not sure if using such addon would be handy, if even possible.

**Comment by pycbouh** [comment]
> this can lead to unnecessary increase in the project codebase.

You can do this with just one line of code, it's not a dramatic increase. I think this is a problem too specific, and the solution is already available.

**Comment by Calinou** [comment]
`get_ok().text` is two more characters than `get_ok_text`. I don't think adding new properties to save typing two characters is worth it.

**Comment by me2beats** [comment]
It seems I was explaining it a bit confusingly

This is not only for saving characters.
This is rather for avoiding creating a script when you don't need it.

One could just set the ok/close button text in `Inspector`.

**Comment by fire-forge** [comment]
I agree with this proposal, not because of saving length in scripts, but because of the ability to customize button text in the inspector. It helps make the ConfirmationDialog node look the same in-editor as it does while running, which is useful when designing UI. Without this the buttons will say "OK" and "Cancel" in the editor and then change only when the project is running.

**Comment by YuriSizov** [comment]
This proposal is approved, PRs welcome!

**Comment by fire-forge** [comment]
Awesome! I started implementing this in a branch a few weeks ago, so I can finish it and open a PR soon.

**Comment by fire-forge** [comment]
I opened a PR that implements this: https://github.com/godotengine/godot/pull/62827
