### ISSUE TITLE
Add an option to remove project contents from `ProjectManager`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2421]
### Describe the project you are working on
Plugins

### Describe the problem or limitation you are having in your project
When I remove  a project in `ProjectManager` `Project List`, I almost always also want to remove its folder contents. To do this, I open the project directory, then remove it, then remove it from the Project List (using `Remove` or `Remove Missing` button).
This is inconvenient if you do this often. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Adding an option to remove project contents from `ProjectManager` would solve the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A checkbox could be added to `Remove Project Dialog` (which appears when you press `Remove`).

![remove from the list](https://user-images.githubusercontent.com/16458555/110242840-a3c06f00-7f79-11eb-9d07-b8d880f72aed.png)

It could be unchecked by default.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It could be worked around by removing the project from the OS (or any other) file explorer/file manager, but this is not so handy.

### Is there a reason why this should be core and not an add-on in the asset library?
There is no API for modifying PrjectManager

**Comment by Calinou** [comment]
When using this option, I think the project files should be moved to the trash instead of being removed permanently.
