### ISSUE TITLE
Add `EditorInterface.get_selected_paths()`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2424]
### Describe the project you are working on
plugin

### Describe the problem or limitation you are having in your project
I want to get all selected files in `FileSystem` dock.
There's `get_selected_path()` but it returns always only one item; and also it works more like `get_active_path()`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Adding `EditorInterface.get_selected_paths()` would solve the problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`Array EditorInterface.get_selected_paths()`
returns all selected paths in FileSystemDock

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not a few lines:
First you need to get FileSystem Tree control (which is already hacky)
Secondly get all selected items
Finally convert each item to path

### Is there a reason why this should be core and not an add-on in the asset library?
There could be a lot of FileSystem plugins which would use Filesystem selection.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/60931.
