### ISSUE TITLE
Add Rotate to Image

### ISSUE THREAD

**Issue by qdwang** [godotengine/godot-proposals#2428]
### Describe the project you are working on
A list display camera photos.
### Describe the problem or limitation you are having in your project
I cannot rotate photos in `ItemList`.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The feature: Adding `rotate` function in the `Image` object.

Currently the `Image` object has methods like `flip_x`, `flip_y`, but there is no `rotate` method. If the image is used in `ItemList`, there is also no method to rotate the icon in `ItemList`.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Best is to combine `rotate` and `flip`. And use it like this:
```
img.rotate_flip(rotate_flip_type)
```
rotate_flip_type:
```

Rotate180FlipNone | 2 | Specifies a 180-degree clockwise rotation without flipping.
Rotate180FlipX | 6 | Specifies a 180-degree clockwise rotation followed by a horizontal flip.
Rotate180FlipXY | 0 | Specifies a 180-degree clockwise rotation followed by a horizontal and vertical flip.
Rotate180FlipY | 4 | Specifies a 180-degree clockwise rotation followed by a vertical flip.
Rotate270FlipNone | 3 | Specifies a 270-degree clockwise rotation without flipping.
Rotate270FlipX | 7 | Specifies a 270-degree clockwise rotation followed by a horizontal flip.
Rotate270FlipXY | 1 | Specifies a 270-degree clockwise rotation followed by a horizontal and vertical flip.
Rotate270FlipY | 5 | Specifies a 270-degree clockwise rotation followed by a vertical flip.
Rotate90FlipNone | 1 | Specifies a 90-degree clockwise rotation without flipping.
Rotate90FlipX | 5 | Specifies a 90-degree clockwise rotation followed by a horizontal flip.
Rotate90FlipXY | 3 | Specifies a 90-degree clockwise rotation followed by a horizontal and vertical flip.
Rotate90FlipY | 7 | Specifies a 90-degree clockwise rotation followed by a vertical flip.
RotateNoneFlipNone | 0 | Specifies no clockwise rotation and no flipping.
RotateNoneFlipX | 4 | Specifies no clockwise rotation followed by a horizontal flip.
RotateNoneFlipXY | 2 | Specifies no clockwise rotation followed by a horizontal and vertical flip.
RotateNoneFlipY | 6 | Specifies no clockwise rotation followed by a vertical flip.


```
### If this enhancement will not be used often, can it be worked around with a few lines of script?
There is no work around to make a picture rotated in `ItemList`.
### Is there a reason why this should be core and not an add-on in the asset library?
It's just basic function in `Image` operation.

**Comment by Calinou** [comment]
> Best is to combine rotate and flip. And use it like this:

Have more simple methods is generally a better way to go about it rather than having few (but complex) methods.

**Comment by Xrayez** [comment]
I've added [`rotate()`, `rotate_90()`, and `rotate_180()` in Goost](https://goost.readthedocs.io/en/gd3/classes/class_goostimage.html#class-goostimage-method-rotate). The former also allows to rotate images with arbitrary angle. The implementation cannot be added in Godot since I'm using more or less hefty image processing library to achieve this, but perhaps the implementation from the thirdparty lib can be ported to work natively with Godot's `Image` class.

**Comment by mojoyup** [comment]
5/30/22: I would LOVE this right now. I've been struggling for a week trying to get an Image (not sprite, texture, etc. but IMAGE) to rotate and I found a code online that does it BUT it shifts half of the image up by a pixel. Any thoughts on this code:

`func rotate_img(image):
	var origin_image = Image.new()
	origin_image = image
	var tex = origin_image
	var trans = Transform2D()
	trans = trans.rotated(deg2rad(90))

	var p1 = trans.basis_xform(Vector2(0,0))
	var p2 = trans.basis_xform(Vector2(tex.get_width(),0))
	var p3 = trans.basis_xform(Vector2(tex.get_width(),tex.get_height()))
	var p4 = trans.basis_xform(Vector2(0,tex.get_height()))
	var ps = [p2,p3,p4]
	var minx = p1.x
	var miny = p1.y
	var maxx = p1.x
	var maxy = p1.y

	for p in ps:
		if p.x < minx:
			minx = p.x
		if p.x > maxx:
			maxx = p.x
		if p.y < miny:
			miny = p.y
		if p.y > maxy:
			maxy = p.y
	var imge = Image.new()
	imge.create(maxx - minx, maxy - miny , false, Image.FORMAT_RGBA8)`

![Capture](https://user-images.githubusercontent.com/29804613/171048553-1831fe21-11d7-4158-b3ed-b391f22a3279.PNG)


CURRENTLY: Godot 3.4.4 Stable (Steam Version)

**Comment by mojoyup** [comment]
Anyone have any ideas on this resulting data? Trying to figure out why either some of it is missing, or shifted. One of the two is happening. If I can figure this out, We can have rotations on images before 4.0.

**Comment by YuriSizov** [comment]
We've discussed it in the proposal review meeting, and the consensus is that it's quite useful to have rotation (at fixed angles, 90, 180, 270), but it shouldn't be mixed with flipping, which we already have.
