### ISSUE TITLE
add select all for keyframes in animation player and animation splitt feature

### ISSUE THREAD

**Issue by boyhax** [godotengine/godot-proposals#2432]
### Describe the project you are working on
**first person shooter**
### Describe the problem or limitation you are having in your project
**defecult to split the animation into defferent animations** 
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
**select all keyframes will allow me to move all keyframes back so i can change the start of animation and so it will be alternative solution that easy and work .**

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-proposals/issues/174 and https://github.com/godotengine/godot-proposals/issues/357.
