### ISSUE TITLE
Swap animations in `AnimatedSprite`

### ISSUE THREAD

**Issue by qarlosh** [godotengine/godot-proposals#244]
**Describe the project you are working on:**
Creating a 2D arcade game with Godot 3.2.beta1

**Describe the problem or limitation you are having in your project:**
My player sprite (an `AnimatedSprite`) has different animations for walking, jumping, etc... when he is firing a weapon and when he isn't. They are exact animations (frame count, fps, loop...), only the frames are different visually.
When firing a weapon, I try to set the `animation` property while playing (i.e. from "walk" to "walk_shooting") but the current frame is reset, breaking the continuity of the animation. I tried to store the `frame` property before changing the animation, and restoring after, but it doesn't work (I had a look to scene/2d/animated_sprite.cpp, I think there is some internal "timeout" resetting).

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
I think that a `swap(String anim)` method that changes the animation but keeps the frame and timing could be the solution.
I think that I could implement it myself, but I'm asking before trying it and creating a PR.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Sorry, no diagram

**Describe implementation detail for your proposal (in code), if possible:**
A new method in `AnimatedSprite`: `swap(String anim)`, changes the animation and keeps the timing. It checks that the current animation an the new one are "compatible" (frame count, fps...).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I managed to get a equivalent functionality by renaming the animations in the `SpriteFrames`object on the fly, but I think that this is not the proper way to do it.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Don't think that can be implemented as an add-on.

**Comment by golddotasksquestions** [comment]
More complex behavior like this is usually done with the AnimationPlayer.

**Comment by qarlosh** [comment]
Thank you, I will try to replicate the same behaviour using the AnimationPlayer, but if it gets too complex, I think that the swap() function would be a good idea.

**Comment by golddotasksquestions** [comment]
I don't think it is complex at all:
var left_off = AnimationPlayer.current_animation_position
AnimationPlayer.seek(left_off)

**Comment by qarlosh** [comment]
Thank you, I switched to using AnimationPlayer, I understand that AnimatedSprite has its own limitations and is very useful for simpler situations.

Closing the issue
