### ISSUE TITLE
Node's name should not contain space in editor

### ISSUE THREAD

**Issue by kienvn** [godotengine/godot-proposals#2440]
![image](https://user-images.githubusercontent.com/3658115/110554761-febab780-816d-11eb-865e-ddda8c5fcd04.png)
Node's name not contain whitespace at the beginning and at the end  in editor, it will help developer avoid mistakes

**Comment by SIsilicon** [comment]
I'm no moderator, but you might wanna fill in the sections provided in the issue template. Your proposal will be disregarded otherwise.

**Comment by Calinou** [comment]
This was already implemented in 3.2.4beta1 and later by https://github.com/godotengine/godot/pull/42014.
