### ISSUE TITLE
Group errors, warnings, prints in debugger output

### ISSUE THREAD

**Issue by menip** [godotengine/godot-proposals#2442]
### Describe the project you are working on
Any Godot project. 

### Describe the problem or limitation you are having in your project
Error, warning, and print output can quickly clutter up debugger output. We can have the same error get printed from different places, at different times. It can be hard to spot specific error in debugger output if you are getting spammed with another error.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Each message would be it's own group in debugger output. A group would get the same message appended to it, and the entire group should be collapsible. This way we can quickly see all outputs of message we are looking for, and collapse anything that is not currently important.

This would work very well for Godot errors/warning, and for some user prints. It would not work well for messages that tend to have unique content, for example, print mouse position every frame.

Ways to deal with this:
1. Only group Godot errors/warnings, don't group user prints.
2. Allow user to specify which prints should get grouped, for example `print("Test", group=True)`. I don't like this approach.
3. Have settings/debugger output option to group user prints or not.
4. Automatically group everything. Change so that when there is a single message in a group, it displays like it currently does, and cannot be collapsed.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Instead of ![image](https://user-images.githubusercontent.com/22862244/58187689-24f72680-7c6c-11e9-88a8-ec474798da97.png)
we can have
![tmp_delete_later](https://user-images.githubusercontent.com/22862244/110565883-0fcede80-8104-11eb-8dbc-b81345f8fe6b.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No. To not get a specific error/warning printed you can disable in settings, but this is not what the problem in question is here. 
### Is there a reason why this should be core and not an add-on in the asset library?
This can't be done via add-on from what I know.

**Comment by hsandt** [comment]
From the screenshot I think this is about the Debugger > Errors panel, not the Output panel.

So this seems to be in line with this comment:
https://github.com/godotengine/godot/pull/41321#issuecomment-751881015

that carrying over many of the Output panel improvements would be nice (there is also collapse and above all message filter in which I'm interested...).

I think I'll open a meta issue to carry over each feature (that makes sense) of Output panel to the Errors panel.
