### ISSUE TITLE
Add -fix core asset handling misbehaviours- to gsoc

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot-proposals#2444]
### Describe the project you are working on
Anything
### Describe the problem or limitation you are having in your project
Renaming/moving assets or nodes often breaks existing scenes using nesting (which is a very common way of working) by having nodes vanish or resources missing which seems to even break the scene loader. This is fundamental to working with godot; one should be able to trust the engine to not break things by itself. Unity for example handles this gracefully.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
By having this addressed reliably through someone dedicated to fixing it (GSoC), as it's probably not an easy task, trust in working with nested or inherited scenes (-a basic feature of godot) or assets in general can be restored and help everyone working with them.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This is wrong behaviour of the fundamental asset handling in the core, it cannot be worked around, and may even require extending the existing file format.
### Is there a reason why this should be core and not an add-on in the asset library?
It improves the situation for everyone working with godot.

**Comment by Calinou** [comment]
This isn't the place to discuss GSoC proposals. The [list of GSoC *ideas*](https://github.com/godotengine/godot-roadmap/blob/master/GSoC/GSoC-2021.md)
 has already been completed for 2021, and it can't be edited anymore now that Godot has been accepted for this year.

Please note that GSoC students are free to work on other tasks, but fixing core asset handling is not something you can do in 1.5 months of time as a new contributor unfamiliar with Godot, especially with refactoring going on in the `master` branch at the same time (with the 3D import workflow being rewritten).
