### ISSUE TITLE
Allow to set text size for bitmap fonts

### ISSUE THREAD

**Issue by davthedev** [godotengine/godot-proposals#2447]
### Describe the project you are working on

Multiple 2D games

### Describe the problem or limitation you are having in your project

I use a bitmap font for all my text needs in some of my 2D games.
The font is using an Angelcode format .fnt file, which is recognized out-of-the-box by Godot and automatically imported as a BitmapFont resource. I used this software to create my font: https://www.angelcode.com/products/bmfont/

At some points I would like to display a larger or smaller title using my bitmap font, other than using the strict 1:1 pixel ratio, and still have the ability to use containers to do the UI layout.

There are Height and Ascent settings. They seem to influence the minimum size box, but the text display is not affected.

Alternately, I can change the node scale to achieve the result I want. But this is impossible to do when using containers to lay controls automatically., as the control scale is forced to 1 in this case. Containers do not work well with children that have a scale not equal to (1, 1)

Reproduction project:
[bitmap_font_scaling.zip](https://github.com/godotengine/godot-proposals/files/6125121/bitmap_font_scaling.zip)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have a setting that changes font size for BitmapFont as well that is similar to how it is done with DynamicFont. Maybe it can be specifying an absolute pixel height or an aspect ratio (example : 1 = original size, 2 = double the pixel size).
If the Height parameter is supposed to do that, fix the bug that prevents the text from being resized.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

By changing the Height parameter, I can have my bitmap font resized.

or

A new "text scale" parameter allows to set a text scale as a multiplier of the 1:1 pixel representation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Workaround : use the node scale property. Cannot work if you use containers to arrange your UI.

### Is there a reason why this should be core and not an add-on in the asset library?

BitmapFont is a built-in resource

**Comment by Calinou** [comment]
This was implemented as part of the [Complex Text Layouts](https://godotengine.org/article/complex-text-layouts-progress-report-3) work for 4.0, closing.

**Comment by elvisish** [comment]
> This is already implemented as part of the [Complex Text Layouts](https://godotengine.org/article/complex-text-layouts-progress-report-3) work for 4.0, closing. You can set the font size on a per-node basis there, regardless of the font backend (bitmap, dynamic, and soon MSDF).

This setting does nothing on labels?
![Image](https://github.com/user-attachments/assets/f0a59014-56f0-4ced-b8ac-82df598e8b76)
![Image](https://github.com/user-attachments/assets/b31319eb-0482-4091-bff0-fdaa795fc327)

**Comment by Calinou** [comment]
> This setting does nothing on labels?

You need to enable it explicitly in the Import dock for bitmap fonts: https://github.com/godotengine/godot/pull/80605
