### ISSUE TITLE
Add radial / circular container to distribute control nodes around a circle

### ISSUE THREAD

**Issue by lale345** [godotengine/godot-proposals#2449]
When I make a project I can only place the control nodes in a line to the sides or up / down there is no other way, for example in circles they would make a more varied GUI

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

PS: Custom containers can be provided through add-ons. There's a [circular container add-on](https://godotengine.org/asset-library/asset/24) already available.

**Comment by lale345** [comment]
all graphics game engines implement different Gui methods officially without plugin
