### ISSUE TITLE
Make IK programmable in 2D

### ISSUE THREAD

**Issue by dryluggage** [godotengine/godot-proposals#2453]
### Describe the project you are working on
N/A
### Describe the problem or limitation you are having in your project
Right now you can only animate 2d skeletons in the editor and if you want do do procedual animation you need to make your own ik setup
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
You can use the Ik that the editor already uses.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Since you can already use ik for 2d in the editor i dont think (in my limited knowledge) it would be that hard to expose the functions in the skeleton2d/bone2d nodes like a make_bone_move_to_pos function in the setup skeleton node
### If this enhancement will not be used often, can it be worked around with a few lines of script?
I dont know maybe
### Is there a reason why this should be core and not an add-on in the asset library?
Because it already exists in the editor.

**Comment by Calinou** [comment]
I believe this feature is provided by https://github.com/godotengine/godot/pull/40347 which is slated to be merged for 4.0.

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/40347 A version of this is merged into 4.0.

**Comment by Calinou** [comment]
Closing, as this is now implemented in the `master` branch as per @fire's comment (also in 3D).
