### ISSUE TITLE
Implement a bounty system to develop assets for the asset store.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#2454]
### Describe the project you are working on
a 2D fighting game.

### Describe the problem or limitation you are having in your project
Sometimes I don't want to remake an entire gameplay mechanic or feature from scratch in every game and I just want to pay for an asset if I can save days or weeks of work.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Let's be honest, Godot current asset store is kind of crappy, and usually the assets are low quality or the asset has a very limited set of assets, We need to improve the asset store with some system where there's full time developers making paid or free extra functionality in the asset store.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Since paid assets are a controversial topic, and since most of godot devs are amateurs without a lot of money, I think some kind of bounty system, where a single person puts money into a bounty or several smaller devs pool their money into a group bounty, could be a good alternative to have paid developers who will develop quality assets for the comunity, and keep them free.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not really an engine issue, but more an organizational issue for the asset store.

### Is there a reason why this should be core and not an add-on in the asset library?
It's a proposal to improve the asset store quality.

**Comment by LightningAA** [comment]
In the asset library rewrite there'll be a way to rate assets which should help with quality

**Comment by ca3games** [comment]
> In the asset library rewrite there'll be a way to rate assets which should help with quality

Well, is not about rating, but hiring a developer to work on a feature you want.

**Comment by Zireael07** [comment]
Uh, I don't know of any assets stores that would have such a feature (plus it's a nightmare from a legal point of view, look at how the Godot team itself was restricted in who they could hire for what...)

**Comment by Calinou** [comment]
> Well, is not about rating, but hiring a developer to work on a feature you want.

You can already hire developers to work on the assets you'd like. There are platforms dedicated to this such as the [Professional Trade section of the Godot Forums](https://godotforums.org/categories/professional-trade) and the relevant channel on the Godot Discord server.

**Comment by ca3games** [comment]
> Uh, I don't know of any assets stores that would have such a feature (plus it's a nightmare from a legal point of view, look at how the Godot team itself was restricted in who they could hire for what...)

Well, not sure on the legality, could they be made under a MIT of GPL license?


> You can already hire developers to work on the assets you'd like. There are platforms dedicated to this such as the [Professional Trade section of the Godot Forums](https://godotforums.org/categories/professional-trade) and the relevant channel on the Godot Discord server.

didn't know that, thanks.
But from lurking there, my idea is closer to some kickstarter+proposal kind of system, rather than a work for my project team.

**Comment by Calinou** [comment]
> Well, not sure on the legality, could they be made under a MIT of GPL license?

You can ask the developers to license the work any way you want. It's up to you to define the terms.

**Comment by Calinou** [comment]
Closing due to lack of support (see lack of reactions on OP and general lack of activity here).
