### ISSUE TITLE
Add a default placeholder font as resource.

### ISSUE THREAD

**Issue by MatheusPese** [godotengine/godot-proposals#2456]
### Describe the project you are working on
Im working in a prototype, as usual, and i want to add text into the scene with a specific font size, and/or without anti-alias.

### Describe the problem or limitation you are having in your project
Every time i make a new project and i need to add some kind of text into it that has a bigger or smaller size than the default
font in the label nodes, i have to download and import a new font, or get it from another project, which is annoying and time consuming.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I needed godot to have a default font resource already in it, as a placeholder, like the good old "icon.png".
This way i would be able to change the font size easly, without needing to download or grab a new font every time i need a text with a different size.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add a new font inside the resource folder, as a placeholder, right next to icon.png.
Like that:
![image](https://user-images.githubusercontent.com/7685880/111016633-ce516400-838d-11eb-9f48-70057a379f7a.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, it can't

### Is there a reason why this should be core and not an add-on in the asset library?
Ease of use.

**Comment by SIsilicon** [comment]
Might wanna fill in those template sections buddy. It helps to understand the proposal, plus it's mandatory.

**Comment by MatheusPese** [comment]
> Might wanna fill in those template sections buddy. It helps to understand the proposal, plus it's mandatory.

Done

**Comment by pycbouh** [comment]
Font size is no longer a part of the font in master, it's its own theme property and can be adjusted without specifying a font resource.

Otherwise, for all intents and purposes, this is close enough to https://github.com/godotengine/godot-proposals/issues/306, so closing.
