### ISSUE TITLE
Add ability to snap to grid before creating a tile in TileSet editor

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-proposals#2459]
### Describe the project you are working on
game with tiles

### Describe the problem or limitation you are having in your project
When I want to make a new tile i can't snap the region to a grid because I don't have a grid yet and there's no way to turn on the grid without making a tile.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
it will let u snap tile regions to a grid when creating them

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
🤷🏼 

### If this enhancement will not be used often, can it be worked around with a few lines of script?
🤷🏼 

### Is there a reason why this should be core and not an add-on in the asset library?
TileSets are core to the engine.

**Comment by KoBeWi** [comment]
This is a bug actually. It's already resolved in the new tile editor coming in 4.0: https://github.com/godotengine/godot/pull/45278
