### ISSUE TITLE
Rename 'Move to Trash' to 'Move to Recycle bin' for Windows

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot-proposals#2460]
### Describe the project you are working on
Small testing of Godot

### Describe the problem or limitation you are having in your project
Currently on 3.2.4 rc 'Move to Trash' is the action when you 'delete' a file from the file browser. What is Trash on Windows?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
On windows 'Trash' is not recognised by many users. Recycle bin is standard. 
Users (beginners mainly) may think 'Is this a Godot specific folder' or 'where are my files?', not knowing the recycle bin is the pseudonym for 'Trash'. It's non-obvious.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Rename 'Trash' to 'Recycle Bin'

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
Core

**Comment by Xrayez** [comment]
I don't know, on Windows, "Delete" (always?) move files to recycle bin, so previous "Delete" name was fine on Windows.

![image](https://user-images.githubusercontent.com/17108460/111079335-3e80f680-8502-11eb-9a33-3ebfb3edbb5e.png)

**Comment by SIsilicon** [comment]
@Xrayez Delete doesn't _always_ move to trash. If you press `Shift+Del` then you have the option of deleting something permanently, and I'm pretty sure it's can setup their Windows to disable the recycling bin.

**Comment by Xrayez** [comment]
Yeah, but then we're talking about the default behavior, which is move to recycle bin, and the name in Godot should match the same terminology. I realize that it may not be correct, but Microsoft hasn't renamed the action to "Move To Recycle Bin", so it makes sense to be consistent in this regard, in my opinion.

**Comment by Xrayez** [comment]
@Calinou can you please explain why bringing back "Delete" is not an option to implement this proposal? I don't think we've even reached consensus here, this proposal was opened like 8 hours ago and there's little discussion on this topic, unless I've missed something...

**Comment by Calinou** [comment]
> can you please explain why bringing back "Delete" is not an option to implement this proposal?

I think "Delete" is not explicit enough. Some people would expect the file to be removed forever, whereas others would expect it to be moved to the system trash.

**Comment by Zireael07** [comment]
@golddotasksquestions: Some programs use 'Delete' without moving to trash bin, so it's better to be explicit.

**Comment by golddotasksquestions** [comment]
@Zireael07 

> Some programs use 'Delete' without moving to trash bin, so it's better to be explicit.
When it comes to files, then no, that's definitely not standard. Maybe some obscure program deletes files permanently under a "delete" command, but the Windows ecosystem standard (which all credible software developers follow) is to move deleted files to the Recycle/Trash bin.

**Comment by aaronfranke** [comment]
I prefer "Delete" above the other options. It's a simpler name that conveys the same thing. Whenever there is a trash, and there aren't two different buttons for deleting, "Delete" means moving to the trash, and not "Delete permanently".

Also, it's possible to disable the Recycle Bin on Windows, so wouldn't this change make the name inaccurate for those users?

![](https://www.tenforums.com/attachments/tutorials/52267d1485960454-set-recycle-bin-permanently-delete-files-immediately-windows-10-a-recycle_bin_permanently_delete-3.png)

**Comment by pycbouh** [comment]
Please note, that the discussion continues in a proposal https://github.com/godotengine/godot-proposals/issues/2463. This issue is closed.
