### ISSUE TITLE
Add a method to make RPC with an array of arguments

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot-proposals#2468]
### Describe the project you are working on
Online multiplayer game

### Describe the problem or limitation you are having in your project
Creating a custom rpc behaviour is quite hacky

So let's say, I want to make rpc_ids function

Since variadic functions are unlikely to be supported anytime soon
The only way to pass dynamic amount of args is through an array, however unpacking this array and checking arg data types is really tedious

```gdscript

remote func some_func(args : Array) -> void:
   pass
   # Unnecessary lines of codes, wasted on converting args into primitive variables
```
Another way is through callv, however this means we are going to have double the amount of functions that we have to
(Still better than manually unpacking the args)

```gdscript

remote func some_func(args : Array) -> void:
   callv("_unnecessary_func", args)


func _unnecessary_func(hey : String, sq : Rect2) -> void:
    pass
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
This feature is pretty much an rpc version of callv, but way less hacky

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
```gdscript

func test() -> void:
    rpcv_id(client_id, "target_function", [23, "dsds", "dadsadsadc"])


remote func target_function(num : int, idk : String, more_idk : String) -> void:
    pass
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes

### Is there a reason why this should be core and not an add-on in the asset library?

**Comment by Faless** [comment]
I'm not sure I full understand, but doesn't this work?
```gdscript
callv("rpc_id", [target_id, "target_function"] + args)
```

**Comment by LoneDespair** [comment]
> I'm not sure I fully understand, but doesn't this work?
> 
> ```gdscript
> callv("rpc_id", [target_id, "target_function"] + args)
> ```

That was very clever tysm!, works really well and will be using this on future projects
