### ISSUE TITLE
Display node's properties in the Inspector when in Code Editor

### ISSUE THREAD

**Issue by rezgi** [godotengine/godot-proposals#247]
**Describe the project you are working on:**
Creating a custom node with exported variables.

**Describe the problem or limitation you are having in your project:**
We always need to toggle between the 2D (or 3D) view to check on the exported variables or modify them when coding. When we are in code editor, we only have access to the script's inspector properties, it would be nice to have the 2D/3D view properties at the same time as the script's parameters.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It's more of a time-saving and UX feature, as we would avoid constantly toggling between the 2 displays and keep losing focus on the code when programming.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
We would have this : 
![01](https://user-images.githubusercontent.com/41618561/69348688-dc4e1380-0c76-11ea-916f-c385f77f3df2.jpg)

Instead of this : 
![02](https://user-images.githubusercontent.com/41618561/69348710-e708a880-0c76-11ea-922d-da5c3544259e.jpg)

**Describe implementation detail for your proposal (in code), if possible:**
Well don't know about C++, but I guess it's just about telling the engine to display the node's 2D/3D view by only adding the script's parameters on top or bottom when the user is in the code editor.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Nope, it's about the engine GUI. The only workaround is to toggle with shortcuts or mouse, which makes us lose focus of the code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's about UX improvement that would benefit all users and it's a heavy change, or maybe we could debate about how it makes the editor less focused ?

**Comment by Calinou** [comment]
Does this mean the editor should no longer switch from the Script view to the 2D/3D view when selecting a node in the Scene dock?

**Comment by KoBeWi** [comment]
> Does this mean the editor should no longer switch from the Script view to the 2D/3D view when selecting a node in the scene tree dock?

Related to https://github.com/godotengine/godot/issues/33704
Maybe the view switch should be changed to double click when in Script Editor.

**Comment by golddotasksquestions** [comment]
Why not just stack the script properties at the bottom of the node properties and always show both as soon as a node has a script?

![stackproperties](https://user-images.githubusercontent.com/47016402/69395513-8497c280-0cdf-11ea-82fd-9c15d6ac74f5.png)

**Comment by rezgi** [comment]
@Calinou No, it's exactly as @golddotasksquestions showed : keep showing the node's inspector properties when it has a script and add the script's properties to it.

**Comment by wyattbiker** [comment]
Just as a note for consideration, a script can be attached to many nodes. So how would that work?

**Comment by rezgi** [comment]
@wyattbiker Since the script's properties can be stacked with the node's properties, it shouldn't make any problem no ?

**Comment by wyattbiker** [comment]
Would be nice if the script button (blue circled) opened up but kept the node inspector open.

The indirect way is to select a node with an attached script and click on the Script tab  (red circled). That opens up a script window, but notice how now the node inspector stays intact. You can select any script and the node's inspector window stays intact including exported variables. Would be nice if this happened when the node's script attachment button did the same.
![image](https://user-images.githubusercontent.com/930478/70103437-21742d00-1609-11ea-8c0c-faf56e84ecd2.png)

**Comment by Calinou** [comment]
In both 3.5 and 4.0, selecting nodes in the script editor no longer switches the visible main screen. @wyattbiker's suggestion is still relevant though.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/84284.
