### ISSUE TITLE
Make godot editor theme accesible

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-proposals#2476]
### Describe the project you are working on
2D RPG, with small open world

### Describe the problem or limitation you are having in your project
Came to making a theme for the UI. The default theme of Godet was fine, only the colours where off (dark colours of Godet, against light colours of the world). But when you want to make a new theme the StyleBox starts from an "empty" state. So, i had to come up with all the Styles (Hover, Pressed, Normal, Focus, Disabled) myself. I tried mimicking (and improving?) the engine's theme, but I found it a bit difficult to see how some StyleBox's where done and it took some iterations to make it work for controller, mouse and keyboard.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Some way to access Godot engines editor theme, to make small tweaks. That way the already usable engine theme can be leveraged for in game UI.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Maybe when you make a new theme, the presets of godot's theme are already filled in the theme resource, or just make the theme available on the asset store
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No.
### Is there a reason why this should be core and not an add-on in the asset library?
Could be an add-on.

**Comment by Calinou** [comment]
Did you see the **Create From Editor Theme** button available in the dropdown in the theme editor?

**Comment by boukew99** [comment]
No, Thank you! That was what I was looking for.
