### ISSUE TITLE
Allow editor plugins to force reimport of resources

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot-proposals#2477]
### Describe the project you are working on
I maintain an [integration](paulloz/godot-ink) of a narrative scripting language into Godot.

### Describe the problem or limitation you are having in your project
I define some custom resource types and need to be able to ask Godot to reimport specific resources from the plugin's code. This is currently not possible.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Basically it'd be a way to achieve exactly the same thing as clicking the **Reimport** button of the import dock, but from code.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
From a quick scan through the code, I imagine such feature would be accessible from `EditorFileSystem`. Either using an existing method (e.g. `EditorFileSystem::reimport_files` is already `public` but not bound to `ClassDB`) or through a new one if more safety checks need to be performed.  
The method would probably take an array of paths as a parameter and either return nothing or an error code.
```gdscript
void reimport_files ( PoolStringArray files )
Error reimport_files ( PoolStringArray files )
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I imagine the alternative *hacky* way would be to nuke the resource file under `.import/` and ask Godot to scan the file system for changes. Which feels very wrong.

### Is there a reason why this should be core and not an add-on in the asset library?
I can't imagine how to achieve this from the outside.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/1615.

**Comment by pycbouh** [comment]
> See also #1615 (possible duplicate?).

A bit different contextes, but there can be a single solution, I suppose. In #1615 files are not detected, which can be considered a bug. Here files are not changed, but user has a reason to want to forcefully cause a re-import. Both can be solved by exposing a similar API.

**Comment by KoBeWi** [comment]
This is somewhat possible with `get_editor_interface().get_resource_filesystem().scan()`

**Comment by paulloz** [comment]
> This is somewhat possible with `get_editor_interface().get_resource_filesystem().scan()`

Not really. `EditorFileSystem.scan()` won't force a reimport if the file hasn't changed on disk.

**Comment by paulloz** [comment]
> You can always delete the file on `.import` and call `get_editor_interface().get_resource_filesystem().scan()` and it will force the reimport of that file.

That's fair. Feels (and is) very hacky, but I guess that's a good workaround for now.

**Comment by paulloz** [comment]
I missed godotengine/godot#61004 where `EditorFileSystem::reimport_files` was bound to `ClassDB`. I'm closing, since it is exactly what this proposal is about.
