### ISSUE TITLE
Rename the `2d` and `viewport` stretch modes to be more explicit

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot-proposals#2479]
### Describe the project you are working on
General 2D projects with pixel art.

### Describe the problem or limitation you are having in your project
Of “2D” and “Viewport”, I always forget which option does what. Does “Viewport” render at native res and scale to the Viewport? Or does it resize everything to Viewport size then render?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Rename the options to something more descriptive and intuitive, like “Preserve pixels” vs. “Change pixel count”, or “Nearest Neighbor” vs “Upsample”.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
It would change the name of the viewport scaling options. It’s pretty self-explanatory.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not really.

### Is there a reason why this should be core and not an add-on in the asset library?
Scaling modes are at a very base level in the engine.

**Comment by Calinou** [comment]
The scaling options were renamed to `canvas_items` and `viewport` in 4.0. `canvas_items` is a bit clearer than `2d`, but we could add descriptions in parentheses besides them.

**Comment by JapanYoshi** [comment]
Those names are still just as confusing as before. Canvas items? What are “canvas items”? And what do they have to do with scaling?

“Preserve pixels” vs. “Change pixel count” and “Nearest Neighbor” vs “Upsample” describe what the options actually mean. They would not necessitate extra descriptions in parentheses or a tooltip.

**Comment by Calinou** [comment]
> What are “canvas items”?

[CanvasItem](https://docs.godotengine.org/en/latest/classes/class_canvasitem.html) is the base 2D class in Godot.

**Comment by Zireael07** [comment]
Knowing what Canvas Items are in Godot doesn't help me visualize what the viewport options do, either... Which one preserves pixels and which does not?

**Comment by JapanYoshi** [comment]
> Knowing what Canvas Items are in Godot doesn't help me visualize what the viewport options do, either... Which one preserves pixels and which does not?

I’m in complete agreement. The end user doesn’t care about what process Godot undergoes in order to achieve that effect, or what that process has to do with “canvas items” or “viewports”.

There are way better names than `canvas_items` and `viewport`.

> I'm not convinced that everyone will understand this the same way, unfortunately. Scaling options are a difficult thing to understand; it's not as easy or seamless as it sounds like at first. It's expected that you will have to read documentation about it while working on your project.

The documentation is made lengthy and esoteric because you have to explain what those terms are from the ground up. With better names for those options, it can be much, much easier to understand.

That being said, let me suggest some alternate terms if you don’t like my suggestion:

* `no_scaling` vs `scale_then_render` vs `render_then_scale`
* `ignore` vs `stretch_pixels` vs `increase_pixels`
* `no_conversion` vs `editor_pixels` vs `screen_pixels`

**Comment by 2plus2makes5** [comment]
If i'm allowed to suggest some names i would say:

-no_scale or disabed: the image remains at its original size, meaning it could be smaller or bigger than the viewport

-scale: not for pixel art, it literally scales the image to fill the entire viewport

-upscale: it renders the image at viewport resolution to fill the entire viewport

also there could be:

-integer_scale or pixel_art_scale: for pixel art, it only scales to integer values, this also means that the image could not fit the entire viewport

**Comment by JapanYoshi** [comment]
If you’re going to name the new option `integer_scale` or `pixel_art_scale`, I think naming the more similar option `scale` is better. So that makes

* `no_scale` < None
* `scale_before` < 2D?
* `free_scale` < Viewport?
* `integer_scale` < new option

**Comment by dreamsComeTrue** [comment]
Hey, what about just adding more/any documentation when hovering over that property in Project Settings?
Currently (3.x) there is no docs at all, but adding elaborate description on which option does what - should solve the dispute, right? 😃

**Comment by Calinou** [comment]
> Hey, what about just adding more/any documentation when hovering over that property in Project Settings?
> Currently (3.x) there is no docs at all, but adding elaborate description on which option does what - should solve the dispute, right? :smiley:

This happens because of how the property is registered – the doctool never sees it, and therefore never generates a "property" for it in `doc/classes/ProjectSettings.xml`.

**Comment by golddotasksquestions** [comment]
The difference between those scaling terms took me months to understand. Knowing what a "Viewport" and "Canvas Item" was did not help much either. My first instinct was to assume 2D is suitable for pixelperfect pixelart. Which it is not.
The alternatives proposed here are not much more intuitive for me either. Especially anything involved "Before" and "After". Before what? After what? This is to me equally confusing as Viewport and 2D.

I would also really welcome a name change for the stretch settings to avoid this painful trail an error I had to undergo for future generations of Godot users, or at least shorten it. I don't think there is a perfect logical way to go about this.

These are my suggestions:

- ``no_stretch``
- ``project_resolution``
- ``device_resolution``
- ``pixelart_integer_steps``


"**no_stretch**" is what we currently have as "_disabled_". The tooltip could say: "Your project is not automatically scaled by the engine. A single project pixel is rendered as a single pixel of your display device. Example usecase: If you want to write your own custom scaling code."

"**project resolution**" is what we currently have as "_viewport_". The tooltip could say: "Scales your project to fit the current window size, using nearest neighbor method on the project resolution. Example usecase: PS1 3D style"

"**device resolution**" is what we currently have as "_2D_". The tooltip could say: "Scales your project to fit the current window size, using the display device resolution. Example usecase: 2D Cutout style, polygonal vector art style"

"**pixelart_integer_steps**" is what we currently don't have. It renders like "_viewport_", only in full integer steps. The tooltip could say: "Scales your project in integer steps to fit inside the current window size, using nearest neighbor method on the project resolution. Example usecase: 2D pixel perfect style, 8bit, 16bit era style"

**Comment by JapanYoshi** [comment]
I think similar options should have similar names.

- `disabled` → `ignore`
  - A pixel in the editor will be shown as a pixel in the window, which can be larger or smaller than the viewport in the editor. Recommended for 3D games.
- `2d` → `fill`
  - The project will scale to the window’s size before rendering. This allows polygons, shaders, and geometric shapes to appear crisp and smooth, at the risk of introducing “mixels” (pixel art at mixed resolutions). Recommended for 2D games with 3D or non-pixel art graphics.
- `viewport` → `pixel_fill`
  - The project will render the viewport at its original size and magnify it to the window’s size. It will fill the whole screen, but may result in “wobbly” looking pixels if the window size is not a multiple of the project size. Recommended for pixel art projects with sprite scaling and/or rotation, or retro 3D projects.
- new option → `pixel_integer`
  - The project will render the viewport at its original size and magnify it to the largest multiple that fits in the window. This ensures that all pixels in the editor are the same size on screen, but it could introduce large margins around the edges. Recommended for pixel art projects.

**Comment by jknightdoeswork** [comment]
"canvas_item" vs "viewport" is no better than 2D and Viewport - in fact it is somewhat worse as it needlessly throws away the built in knowledge that all the godot userbase already has.

The explanations on the Multiple Resolution pages are also somewhat lacking. They do not speak to the case where the design size is greater than the rendered size.

I am currently trying to determine how many calls to a fullscreen fragment shader will be executed using the different scaling modes, and am finding this a hard question to answer.

**Comment by Calinou** [comment]
> I am currently trying to determine how many calls to a fullscreen fragment shader will be executed using the different scaling modes, and am finding this a hard question to answer.

With the `disabled` and `2d` stretch modes, it's always 1:1 in relation to the window size.

**Comment by jknightdoeswork** [comment]
> With the viewport stretch mode, it matches the design size, which means it's significantly faster unless the window size is lower than the design size.

Yes, exactly. We are using the largest target device size (iPad Pro) as our Design Size. Most monitors are 1920x1080, which is far less resolution than the iPad Pro. The assumption is in the documentation in several places that the Design Size will be smaller than the typical Window Size, but that assumption cannot be universally made.

Your explanation clarifies thatthat using the 2D viewport scaling will be far more efficient than the Viewport scaling mode for us because we have a large design size. Thanks for that info.

I cannot offer a great name because I too have struggled to understand the meaning behind the scaling modes.

It almost seems like the modes are either "Before Rendering" or "After Rendering"?

ie: canvas_item = Before Rendering = scale the scene down to match the window size and then render

viewport = After Rendering = render the scene at the design size and then scale it down to the window size

**Comment by elvisish** [comment]
> I think similar options should have similar names.
> 
> * `disabled` → `ignore`
>   
>   * A pixel in the editor will be shown as a pixel in the window, which can be larger or smaller than the viewport in the editor. Recommended for 3D games.
> * `2d` → `fill`
>   
>   * The project will scale to the window’s size before rendering. This allows polygons, shaders, and geometric shapes to appear crisp and smooth, at the risk of introducing “mixels” (pixel art at mixed resolutions). Recommended for 2D games with 3D or non-pixel art graphics.
> * `viewport` → `pixel_fill`
>   
>   * The project will render the viewport at its original size and magnify it to the window’s size. It will fill the whole screen, but may result in “wobbly” looking pixels if the window size is not a multiple of the project size. Recommended for pixel art projects with sprite scaling and/or rotation, or retro 3D projects.
> * new option → `pixel_integer`
>   
>   * The project will render the viewport at its original size and magnify it to the largest multiple that fits in the window. This ensures that all pixels in the editor are the same size on screen, but it could introduce large margins around the edges. Recommended for pixel art projects.

I think we also need a Sonic Mania mode (working title) where the viewport is scaled to the closest integer, then antialiased/bilinear filtered up to fill the screen.
