### ISSUE TITLE
Improve type system and obsolete loading types by string path

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#2484]
### Describe the project you are working on
Non right now due to me running into bugs or missing features whenever I try to use godot

### Describe the problem or limitation you are having in your project
Currently types are loaded with string paths which seems to be a issue in https://github.com/godotengine/godot-proposals/issues/2307

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Make the engine register custom types by name. this allows things like built in scripts to have class_name or tool keywords.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
```
class_name MyCustomType

var instance = MyCustomType()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Most likely other languages load types by name and not by a filepath 

### Is there a reason why this should be core and not an add-on in the asset library?
It allows extending nodes into true custom types which can be linked in the header of a scene file

**Comment by Shadowblitz16** [comment]
I can't find the issue but can someone link this to willnationdev

**Comment by Calinou** [comment]
cc @willnationsdev

**Comment by aaronfranke** [comment]
You can already do what you want, you just need to add `.new`:

```gdscript
class_name MyCustomType

var instance = MyCustomType.new()
```

**Comment by Shadowblitz16** [comment]
@aaronfranke The main idea for this was so we didn't use string paths for inheritance and scenes.

everything could just be linked together with type names and we wouldn't need to worry about where files are.
one of the reasons I have a hard time using godot is due to the fact it has this weird artificial object oriented programming implementation.

I mean nodes coded in gdscript aren't really inherited as much as just a script attached to a node.
and this makes it really awkward to make custom types because they don't feel like it and it still feels like your limited to what the engine can do under the hood.

Not only that but people can edit your script when you might not even want it to be visible.

The final goal is to have true oop system where nodes don't attach scripts and everything is referenced by name.

I understand the devs of godot want to keep things easy but sometimes I feel they sacrifice the engines potential to do so and in this case its not easier.

**Comment by aaronfranke** [comment]
@Shadowblitz16 My reply to you does not contain any strings. I don't understand what you mean.

**Comment by Shadowblitz16** [comment]
@aaronfranke yes I know but I think scenes load types by file path don't they?

**Comment by me2beats** [comment]
Sometimes I really don't want to create custom types, for example when creating a plugin.
I just preload scripts by path.
This is a quite useful feature, so I don't think it shoud be obsolete

**Comment by Shadowblitz16** [comment]
I'm closing my bad proposals
