### ISSUE TITLE
Allow to move CanvasItems with arrows while in move mode

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#249]
This seems too trivial to go into this repo, but whatevs.

**Describe the project you are working on:**
2D game with node hierarchies.

**Describe the problem or limitation you are having in your project:**
Every time I have a compound node (i.e. a hierarchy of nodes) which isn't an instance, I need to click the top-most object and switch to Move mode to move it. This is ok, but sometimes I want extra precision and for that I need to use arrows and they only work in Select mode. This is not ok. I have to constantly switch between Select and Move to position my nodes in correct spots.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If I could use arrows in Move mode, I would just select the node I want to position and don't get distracted by unnecessary switching.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/2223172/69388183-5f4b8a00-0cc8-11ea-8e48-059b8cb9026c.png)
![image](https://user-images.githubusercontent.com/2223172/69388242-82763980-0cc8-11ea-9f82-a15031b26fe3.png)
![bCcLRrrPtK](https://user-images.githubusercontent.com/2223172/69388289-a76aac80-0cc8-11ea-8ede-d8f6a8651873.gif)

**Describe implementation detail for your proposal (in code), if possible:**
Just allow to use arrows with TOOL_MOVE active.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's an improvement to canvas editor plugin.

**Comment by MCrafterzz** [comment]
I've already implemented it: https://github.com/godotengine/godot/pull/33451 It's just waiting for 3.2 being released so that it can be merged
