### ISSUE TITLE
Make all feature tag names lowercase

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2492]
*See also https://github.com/godotengine/godot/pull/47255.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

[Feature tags](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html) are case-sensitive. Most feature tags like `mobile` have lowercase names, but platform feature tags are an exception: `Windows`, `OSX`, `HTML5`, …

This can lead to surprises when attempting to override project settings based on feature tags, especially from C++ code where you don't have access to a graphical Project Settings editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use the lowercase platform name for platform feature tags.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change the following feature tag names:

- `Windows` -> `windows`
- `OSX` -> `osx`
- `Linux` -> `linux` (also applies to FreeBSD, NetBSD, and BSD)
- `Android` -> `android`
- `iOS` -> `ios`
- `HTML5` -> `html5`
- `JavaScript` -> `javascript`
- `UWP` -> `uwp`
- `Server` -> `server`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as default feature tags are hardcoded.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by Jummit** [comment]
`Server` and `JavaScript` are missing.

**Comment by Calinou** [comment]
> Server and JavaScript are missing. JavaScript could be renamed to java_script or javascript.

I think `javascript` is better, and it's easier to handle internally.

**Comment by fire** [comment]
Didn't we rename `linux` to `linuxbsd`? It should be consistent.

**Comment by Calinou** [comment]
> Didn't we rename linux to linuxbsd? It should be consistent.

The platform name reported by `OS.get_name()` is Linux, unless you're on *BSD in which case it reports FreeBSD, NetBSD or just BSD.
