### ISSUE TITLE
Allow the ability to comment out a batch of comments regardless of the starting position.

### ISSUE THREAD

**Issue by liryu1973** [godotengine/godot-proposals#2495]
Problems
The ability to comment out lines at a time is very difficult to use.

(#) This is easy to use because it doesn't matter where you start writing,
but you can only comment out one line at a time.

("""  """) This will cause an error depending on where you write it.

Improvement strategy
How about making (""" """) work regardless of position, just like (#)?

**Comment by pycbouh** [comment]
Please follow the proposal template provided and answer fill out all of its sections. This proposal will be reopened, when you do.

**Comment by Calinou** [comment]
This is likely a duplicate of https://github.com/godotengine/godot-proposals/issues/1584.
