### ISSUE TITLE
Increase maximum TileSet's snap step (or remove limitation)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-proposals#2496]
### Describe the project you are working on
Turn-based strategy

### Describe the problem or limitation you are having in your project
I want to make tilesets with tiles bigger than 256x256 (for example 300x300) but have trouble using a step to conform with that size due to limitations.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Increase the step to 512x512(?) or remove that limit:
![image](https://user-images.githubusercontent.com/3036176/112121111-eddb5e80-8bcf-11eb-8d27-693b4f4fe378.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Removing CLAMP from `TileSetEditor::_set_snap_sep` should help but I'm not sure how this parameter may affect Separation and Offset, so I did not create a PR myself, I think @groud knows better how they should interact since he is responsible for TileMap enhancements.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
Its internal editor stuff

**Comment by Chaosus** [comment]
Seems like it's no longer relevant for the new TileMap created by @groud for 4.0.

**Comment by Calinou** [comment]
> Seems like it's no longer relevant for the new TileMap created by @groud for 4.0.

I think this is still relevant for `3.x`: https://github.com/godotengine/godot/pull/48820
