### ISSUE TITLE
Compiling and publishing development versions on the website.

### ISSUE THREAD

**Issue by frkntlr** [godotengine/godot-proposals#2508]
### Describe the project you are working on
Publishing versions with significant changes, such as beta alpha, on the official site. Similar to the structure in the blender, people can reach it. Or the possibility to reach with unity hub-like structure

### Describe the problem or limitation you are having in your project
It only takes a compilation time of over 1 hour to be able to test it (On my computer). This period will be longer on computers with lower equipment. There are people who don't trust and download from places like https://hugo.pro/projects/godot-builds/ because the compiled version is not on the official website. It prevents it from finding people easily.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Provides the ability to use the compiled godot. Many people will have the opportunity to see and experiment. It provides an opportunity to test new features.

### Is there a reason why this should be core and not an add-on in the asset library?

**Comment by pycbouh** [comment]
> Publishing versions with significant changes, such as beta alpha, on the official site. 

All alphas, betas and release candidates are published on the official website. There are blog posts and everything, and you can check the complete directory with all the releases [here](https://downloads.tuxfamily.org/godotengine/). As for https://hugo.pro/projects/godot-builds/, it's a website hosted and provided by one of our core developers, @Calinou. It's safe to download build from there.

**Comment by Calinou** [comment]
You can also download artifacts from GitHub Actions as long as you're logged in: https://github.com/godotengine/godot/actions

Note that these builds aren't compiled with full optimizations, so they will be slower than production builds.

**Comment by pycbouh** [comment]
Also I forgot to mention that 4.0 release, which requires third party builds, is not even in the alpha stage, which is why there are no binaries on the website.
