### ISSUE TITLE
[proposal] Please consider adding support for cmake, meson/ninja and/or GNU autoconfigure

### ISSUE THREAD

**Issue by rubyFeedback** [godotengine/godot-proposals#251]
Currently godot seems to insist on scons. Scons annoys me though.

I also know waf; mpv uses waf. I am annoyed by waf too, sorry.

We have GNU autoconfigure. This is very convenient from a user's
point of view e. g. "./configure --help". But developers hate it due
to awful syntax and macros.

That leaves two contenders: cmake, and meson/ninja.

I think both are fine and I would prefer if godot also allows us to
use any of these two.

I am not sure how likely it is that this can be added since this taps
away time from you guys and I suppose for you scons works
well. But I dislike it it. I'd much rather use cmake or meson/ninja.

So here is my proposal: would it be possible to add either
cmake or meson support, too? Only if it is not too much work.

I don't know how to allow for several compile targets for the
same project but for me it would be great. Then I don't have
to struggle with scons (and I am struggling with it right now;
I don't even see how far the progress is! with both cmake
and meson I see the progress... scons is really not great
IMO).

**Comment by clayjohn** [comment]
Please update your post using the template provided. Only proposals following the template will be considered. You can read the rules for proposals on the main page of this repo. https://github.com/godotengine/godot-proposals
