### ISSUE TITLE
[Godot 3.2.3 stable] Automatic text wrapping option missing

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot-proposals#2511]
### Describe the problem or limitation you are having in your project

There are lengthy lines in code that are difficult to manage.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Enable an automatic text wrapping option in editor settings. It would __visually__ break the line without inserting an actual line break.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is a general purpose addition.

**Comment by Calinou** [comment]
Enable **Word Wrap** in the Editor Settings:

![image](https://user-images.githubusercontent.com/180032/112663735-7587ce00-8e59-11eb-8d58-f6b8f3ed9074.png)

**Comment by jcarlosrc** [comment]
Really? So I missed. Thanks.
