### ISSUE TITLE
Add Houdini Support (OpenVDB support)

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#2516]
### Describe the project you are working on
3D JRPG.

### Describe the problem or limitation you are having in your project
Godot particle system is just too limited for industry standarts.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add some support for houdini, which means using openvdb.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Houdini is the best tool for particle simulations and volumetrics, would be really nice if you could make some volumetrics or water or particles effects with houdini, blender or any other volumetric tool, and just import a VDB file into godot as particle simulation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, It can't.

### Is there a reason why this should be core and not an add-on in the asset library?
It's a core issue (import).

**Comment by Calinou** [comment]
> Godot particle system is just too limited for industry standarts.

Can you pinpoint what is missing from the particle system in the `master` branch for your project?

**Comment by ca3games** [comment]
> Related to #1821.
> 
> > Godot particle system is just too limited for industry standarts.
> 
> Can you pinpoint what is missing from the particle system in the `master` branch (for the needs of your project)?

It's more that I'm not complaining about Godot current solution, rather that I feel I want support from houdini, which clearly is the top software to create volumetrics.

https://www.youtube.com/watch?v=QVlxGNLuD4U
Here's a simple showcase of Houdini being used in the industry.

**Comment by NHodgesVFX** [comment]
You can do this with baked flipbooks already. Vdbs are massive in size as are alembic files. Your going to quickly run into file size issues and bandwidth issues. You also won't get the same quality as the video you posted becuase a realtime render of volumetrics wont match an offline render that took days. 

For geometry, vertex animations textures would work well and for volumetrics animated 3d texture from houdini could work. NanoVDB could also work but would would still be large in size.

And of course by baking you lose all interactivity.

I think a better option is improving godots particles so that its on the level of ue4 or unity. 

Also take a look at embergen for some cool volumetric stuff in realtime.

**Comment by NHodgesVFX** [comment]
Perhaps I misunderstood are you just wanting to import a VDB to drive a Godot particle simulation if so you will actually be able to do this in Godot 4 by importing a vector field.

**Comment by ca3games** [comment]
> Perhaps I misunderstood are you just wanting to import a VDB to drive a Godot particle simulation if so you will actually be able to do this in Godot 4 by importing a vector field.

I mean, it would be nice to create a simulation inside houdini and just import it on godot.

**Comment by NHodgesVFX** [comment]
You can import houdini effects in godot by baking it to a flipbook or a VAT already, vat need a custom shader but works.

**Comment by ca3games** [comment]
> You can import houdini effects in godot by baking it to a flipbook or a VAT already, vat need a custom shader but works.

@fire  told me is possible to import an openVDB on blender and then export inside a GFTL, can someone confirm this is possible?

**Comment by NHodgesVFX** [comment]
thats not possible Openvdb store volumetric data not geometry. GLTF does not support volumetric data

**Comment by NHodgesVFX** [comment]
You could convert a vdb into geometry and save it to gltf but you would be limited to a single frame with GLTF.

**Comment by ca3games** [comment]
Thanks, seems possible, but right I think is cumbersome.

Will leave the proposal open if guys want to discuss how to import from houdini.

**Comment by fire** [comment]
@NHodgesVFX gltf2 already support multiple frames, but you can do better integrated into the blender exporter.

See https://github.com/godotengine/godot-proposals/issues/1821#issuecomment-804358429

**Comment by Calinou** [comment]
Closing due to lack of support (see general lack of activiy here). Also, this feature can be implemented by an add-on.
