### ISSUE TITLE
Node/Script Editing Workflow Convenience When Switching Between The Two.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot-proposals#2522]
Godot Engine v3.2.4.rc4.official - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GT 650M OpenGL Engine
OpenGL ES Batching: ON

### Describe the project you are working on
Working on some Godot ideas.

### Describe the problem or limitation you are having in your project
When you click on the script of a Node, the script editing opens and the Inspector changes. 

The problem is that if I click back on the same Node it does not present the node 2D/3D view nor does it show the Inspector of that node. You must first click on a different node and then click back on the same node. 

![2021-03-29 10-10-40 2021-03-29 10_14_05](https://user-images.githubusercontent.com/930478/112851076-9c701b00-9078-11eb-8361-c99c7f831818.gif)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
This would be a convenience and consistency feature so one does not have to remember to click on a different node or the 2D/3D tab at the top.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
When clicking back on the node, revert back to the 2D/3D view and show inspector of that node.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No it cannot

### Is there a reason why this should be core and not an add-on in the asset library?
It is part of the editor workflow

**Comment by KoBeWi** [comment]
This looks like a bug.

**Comment by wyattbiker** [comment]
Didn't occur to me, but now that you mention it, makes more sense it's a bug. @Calinou how is this handled? Can issue be moved or is it a reopen as bug.

**Comment by me2beats** [comment]
I think the SceneTree has `allow_reselect` off, or something.
There are 2D/3D  buttons on the top, I use them. Also there are shortcuts to switch between main 2D/3D/ScriptEditor screens.

But yea, I found that uinconvinient too at first.

**Comment by KoBeWi** [comment]
Right, this is fixed since RC5: https://github.com/godotengine/godot/issues/46935

**Comment by me2beats** [comment]
Downloaded 3.3.7; the problem still exists

**Comment by KoBeWi** [comment]
I can't reproduce
![tnwVfqX8Po](https://user-images.githubusercontent.com/2223172/112981063-f517e480-915a-11eb-8150-42d36b848c44.gif)

**Comment by wyattbiker** [comment]
I too see the problem too with the  Script button on the menu bar. For me rarely used but would be nice to fix for consistency.
