### ISSUE TITLE
Quality-of-Life Suggestions for Tilemaps

### ISSUE THREAD

**Issue by DreamsTandem** [godotengine/godot-proposals#2529]
### Describe the project you are working on
These ideas came as I was making a platformer.

### Describe the problem or limitation you are having in your project
While working on some tilesets, I noticed that it's not nearly as optimized as it can be. The engine could include many more features that can help users create tilesets more efficiently, using only one template to apply across entire projects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
First, I started hoping for options where one could copy-paste the collision, occlusion, and navigation masks from one tileset to another. There could also be an option to remove an entire collision mask in one click, in case someone suddenly decides certain tilesets should be passable instead of collideable. I know this system may take a while to add, but it's already a thing for bitmasks, which are much easier to make with the editor.

Next, I thought the editor could add a simple setting that allowed users to default bitmasks to settings such as 3x3 minimum instead of only 2x2, so users would not need to set them manually for each tileset.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
The option to copy a collision mask would locate the vertices on each collision shape and store them inside the engine. Once the user is ready to paste the collision map into another tileset, the engine would simply need to read where these vertices were located and place each collision shape into the new tileset. The option to clear an entire collision mask would simply remove every collision shape from the tileset's data. Combined, these features would resemble this mock-up I made in GIMP:
![image](https://user-images.githubusercontent.com/81639309/113026022-218e2980-9178-11eb-8c81-b61d3c894161.png)

The option to default bitmasks to 3x3 minimum instead of 2x2 may be placed in either Editor Settings or Project Settings, depending on whether it would be more appropriate to implement the change globally or in only one project.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Unless this script knows how to load tilesets into a text editor, locate each collision mask, and somehow copy-paste them all without breaking anything, that workaround would be too impractical to be worth considering. Changing the default bitmask size would also be cumbersome, as it requires knowledge of how Godot itself operates.

### Is there a reason why this should be core and not an add-on in the asset library?
These additions would greatly simplify the process of adding tilesets to projects in Godot, eliminating the need to manually reconfigure and redraw each collision shape by hand. Placing this enhancement in the base engine instead of an add-on would also help users who are afraid of installing malware or getting scammed. Overall, I believe this addition would greatly enhance the next major release of the Godot engine.

**Comment by LightningAA** [comment]
The tilemap system is already being reworked for 4.0, see https://github.com/godotengine/godot-proposals/issues/1769

**Comment by DreamsTandem** [comment]
I still feel like being able to default to 3x3 bitmasks would help improve the engine. To be fair, though, that thread's idea for tile collisions might actually be better than mine.

**Comment by Calinou** [comment]
@DreamsTandem Can you test the [4.0 test build](https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20211210/) and see if the new TileMap editor suits your needs?

**Comment by DreamsTandem** [comment]
I should have said this a long, **long** time ago, but whatever was done with 4.x has absolutely helped. Thank you.

**Comment by DreamsTandem** [comment]
I apologize for waiting this long to review that build, but it does not even seem able to accept textures into any part of the tile-map editor, even in places where it is labelled to accept them.

Regardless, the official release of 4.x has absolutely resolved this issue, along with every other issue that I had with version 3.x. Thank you.
