### ISSUE TITLE
Godot 3.2 Hotkey Revamp

### ISSUE THREAD

**Issue by thottee** [godotengine/godot-proposals#253]
Unfortunatelly in my case godot is really uncomfortable and annoying when you try to use it with only keyboard.
I really hate use mouse, and when i work, i try to do everything with keyboard, and with mouse of course, a little bit.
But when i use godot, the window focus thing is really terrible. I'm so sad when i must say bad things from a project what i really love, like godot.
An unified method of keyboard-using may need for the entire software, not this current window-focus thing, because when you want to use a hotkey, some hotkey has different function on different windows,
and it's not a comfortable way to use when you need to select a window before use keys, 'cause maybe you will do an unexpected thing, if you don't select the window before.
But not this is the biggest problem, but also a lot of tiny things. Some examples:
- when you use tab to select something, and sometimes tab select invisible things, or i think that is the window frame maybe
- you can't use keyboard's "dropmenu" key on files and directories in the browser, so you need to use the mouse right click beside keyboard to managing your files (it's not keyboard problems, but lack of icons at file browser's dropmenu is a little bit uncomfortable too, when you use it, but it's okay)
- when you use arrow keys in file browser window or in nodetree window, the operation of selection frame is annoying (sometimes you cant select a node with arrow keys + enter)
- godot hasn't a unified hotkey map. an example: you can't rename nodes or files with one hotkey (in turn you need to select the window first, 'cause godot why hasn't an unified hotkey to rename things, but yea i know it's adjustable)
- input fields auto focusing is a little bit annoying too, here is an example for logical issue: when you create a script resource in file browser, the first focused field should be the script name, not the create button, 'cause if you want to change script name before create, you need to use mouse, or 8-9 tab keys to rename it
- use of project browser with keyboard in 3.2 alpha is really terrible too, i hope it will be fix in 3.2 final release. an example: in 3.1, I use up-down arrow keys to select project (it was really great when the first autofocus was on the projects), and "enter" to open (it was good). Now, Try to select a project in project browser with up-down keys in 3.2 alpha.
- and there are a lot more little annoying and uncomfortable hotkey and keyboard-using problem, 'cause i feel that the whole software hasn't an unified keyboard maneuverability
i know it's a communal project, and want to say thanks to everybody who work on this project for us, but i think, it is worth pointing out the issues to help create a better software.
if I could, I would be happy to fix these issues, but i'm really bad in high level programming :S , so unfortunately i can't help in this :S

i hope this post wasn't humping. I really love this software, but i suffer regularly when i want to use it with only keyboard
maybe a full revamp would be good at this part of godot

thanks to everybody who read this long post!

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
