### ISSUE TITLE
Implement Vulkan validation layers on Android

### ISSUE THREAD

**Issue by szymonm-google** [godotengine/godot-proposals#2536]
### Describe the project you are working on
The purpose of the proposed change is to add support for Vulkan validation layers on Android. Validation layers will be automatically loaded and enabled in debug builds.

### Describe the problem or limitation you are having in your project
Currently, the validation layers on Android are not properly loaded and thus temporarily disabled.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The feature will fix the way how validation layers are loaded and enabled.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Loading validation layers in Android is different than on desktop. Validation layers' sources first need to be cloned from the official [Khronos repository](https://github.com/KhronosGroup/Vulkan-ValidationLayers) and then built locally. Compiled libraries need to be linked with the Android app.

Required changes:
*  On Android, automatically detect if validation layers were linked and if they were, enable validation layers automatically. The modifications will be done mostly in `drivers/vulkan/vulkan_context.[h/cpp]` and `platform/android/vulkan/vulkan_context_android.cpp`.
*  Create an internal manual instructing how to clone, compile and link validation layers with the Android app. Ideally, this process could happen automatically (which is a good candidate for another proposal).

### If this enhancement will not be used often, can it be worked around with a few lines of script?
N/A

### Is there a reason why this should be core and not an add-on in the asset library?
The feature is for engine developers working on Vulkan renderer for Android.

Play & Android Game Engine Support @ Google

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/2524.

**Comment by BastiaanOlij** [comment]
I'm all for getting more feedback from the engine when developing so it sounds like a good feature to have. I'd recommend looking into building this automatically as part of the scons/gradle setup so that it becomes part of the official builds.
