### ISSUE TITLE
Implement ItemList Pre-Draw Size Calculation

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot-proposals#254]
**Describe the project you are working on:**
Selection Popup UI for a Simplistic 2D Space Combat RTS

**Describe the problem or limitation you are having in your project:**
ItemList prevents accessing or determining item sizes and positions, and does not allow access to the list's height until after the draw call with autoheight. I seek to allow autoheight for the first 5 items in my list and then limit it beyond that so I can activate the item list scroll automatically, (by disabling autoheight and using min y size) however I can not know the height until after a draw and item list items don't allow me to retrieve nor easily guess the item's height, (the next alternative is rebuilding half the draw call for sizing) and I can't rely on waiting for draw because then it lags adding items to it or will overflow the list in a manner that gives it the same function as keeping autoheight enabled. The next alternative is requesting a draw after adding 5 objects but then I'm wasting an entire draw call just to rebuild the ItemList. (which it will do again regardless)

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If I could have some manner of either more simply estimating or knowing the item sizes or list size without wasting through the entire draw or performing otherwise ineffective or inefficient hacks it could make performing some more dynamic behavior on ItemLists which includes being able to easily and effectively handle size growth limiting for the list.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it would require either rebuilding the vital aspects of the draw to be slightly more efficient, or adding objects to the ItemList until satisfied and then making a draw request. (which will also waste draws to the screen)

**Is there a reason why this should be core and not an add-on in the asset library?:**
It can't capably be added to ItemList in an add-on, an add-on could be made that completely copies ItemList and just adds extra methods to either estimate item properties or request calculating the ItemList without drawing. (basically caching it for later) A calculation request would take longer to finish first time but it could be cached if the object doesn't change. Or you could just try to use the existing calculations, falling back on just recalculating it all should that be impossible which it already does when the shape changes anyway. At best there is a moderate reduced loss in efficiency compared to hacking with it, it the best scenario you construct the ItemList's new list ahead of the next draw, in the worst case you just double the algorithm's inefficiency regarding constructing the ItemList for every time you request it. (in my case I'd only need to request it once after adding some objects) In such a case, you lose nothing implementation or performance wise (least without specific use of the feature, and only marginally by itself) and increase flexibility of ItemList.

**Comment by girng** [comment]
> I seek to allow autoheight for the first 5 items in my list and then limit it beyond that so I can activate the item list scroll automatically,

Maybe you can set a counter, increment it one per item added. Then, when it reaches 5, activate the item list scroll. Not entirely sure if that would do what you want. Also, obtaining the first 5 items and their height is very specific for something to be changed in the core engine.

However, maybe exposing some methods to get the height you need could be done? I've seen some  of where stuff is made public and it fixed their issue

**Comment by Spartan322** [comment]
>Maybe you can set a counter, increment it once per item added. Then, when it reaches 5, activate the item list scroll. Not entirely sure if that would do what you want. Also, obtaining the first 5 items and their height is very specific for something to be changed in the core engine.

I don't believe that would work because it'll still manage the list's height automatically. And what I specifically desire is some manner of either performing behavior in accordance to the current height of the list in a manner that I can retrieve it or some type of limiter to the auto-height should that be too much to ask for.

In the least getting a height would be fine, but I'd find it just as serviceable to have a auto-height limit.

**Comment by Spartan322** [comment]
Perhaps we can move https://github.com/godotengine/godot/blob/master/scene/gui/item_list.cpp#L964-L1096 to a separate method entirely as it doesn't actually make any draw calls (I don't think, please correct me if I'm incorrect) and any call outside of NOTIFICATION_DRAW seems like ti should set everything properly and thus such a call could set `shape_changed` to false without issue. This would enable the draws to handle it automatically and if you need to know the height earlier then a draw call you could force it to construct all the necessary data early. Could call it something like `force_update_for_items`?
