### ISSUE TITLE
Provide GDScript access to `ED_SHORTCUT()` from editor_settings.cpp

### ISSUE THREAD

**Issue by SlugFiller** [godotengine/godot-proposals#2547]
### Describe the project you are working on

Vector graphics editor, render nodes, and SVG import plugin

### Describe the problem or limitation you are having in your project

Editor shortcuts. They're an important part of any designer/artist-facing tool, since no self respecting artist would move their pen off the canvas every time they need a different tool. However, currently, only C++ modules are able to add editor shortcuts that are available for edit via the editor settings. Plugins written in GDScript can only offer hard-coded shortcuts.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Provide GDScript binding for ED_SHORTCUT. It's a global function, but a proxy method could be added to EditorSettings, or directly to EditorPlugin. It is the default and preferred mode for adding shortcuts for editor buttons.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
Ref<Shortcut> EditorPlugin::add_shortcut(const String &p_path, const String &p_name, uint32_t p_keycode) {
	return ED_SHORTCUT(p_path, p_name, p_keycode);
}

void EditorPlugin::_bind_methods() {
	ClassDB::bind_method(D_METHOD("add_shortcut", "path", "name", "keycode"), &EditorPlugin::add_shortcut);
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't see how. The only way to add a shortcut to the list of shortcuts in EditorSettings is by using the setter for the "shortcuts" property. And, unfortunately, it only accepts InputEvents, which it turns into a shortcut object. The shortcut object is never returned, and lacks the "original" meta, which causes it to never appear in the options dialog. In other words, the closest thing to a workaround simply doesn't do the trick.

### Is there a reason why this should be core and not an add-on in the asset library?

It requires C++ code. The asset library is purely GDScript.

**Comment by pycbouh** [comment]
`ED_SHORTCUT` is a helper for the editor's internal logic, it's not suitable for users. What you want exposed is `add_shortcut`, `get_shortcut`, and `is_shortcut` methods from `EditorSettings` singleton. See also #70 for a more advanced system of editor actions that is planned to be implemented.

But even without those methods exposed you can already do the same with the setter, as you've mentioned. Setters don't normally return values, but you can use the getter immediately after setting the value to get the `Shortcut` object. Or, if you don't need the exact copy, you can create it yourself. There is no magic in "turning" `InputEvent` into `Shortcut`. You just assign `Shortcut`'s property `shortcut` the value of your `InputEvent`, and that's it.

**Comment by SlugFiller** [comment]
@pycbouh The issue is that the getter does its own magic filtering, so you might not get the value you set, or you might get the shortcut "unwrapped". There IS "magic" in turning an InputEvent into a shortcut, since ED_SHORTCUT adds the "original" metadata, and the aforementioned setter for EditorSettings.shortcuts does not. This metadata is then used to filter between "real" shortcuts (those added via ED_SHORTCUT), and ones added from GDScript, causing the latter not to appear in the settings window.

Now, if add_shortcut was exposed to GDScript, it WOULD be possible to re-implement ED_SHORTCUT using it, plus internal knowledge of how ED_SHORTCUT works. However, the need for said "internal knowledge", which is essentially paramount to voodoo (Without reading the code, how would you guess you have to call shortcut.set_meta?) is the reason why I think ED_SHORTCUT should be exposed directly, and not simply the low-level constructs it uses in order to actually work (which are essentially useless by themselves).

As an aside, there's also the fact that ED_SHORTCUT can work with a null InputEvent, while setting a meta to null via GDScript does not work (In C++, it uses Variant.Null, which somehow counts as having a value). This functionality allows creating editor shortcuts with a default binding of "None".

**Comment by pycbouh** [comment]
If the editor settings UI filters out shortcuts without the `original` meta, then this meta should be settable via `add_shortcut`, plain and simple. Same goes for the `null` behavior, because `ED_SHORTCUT` itself doesn't do anything special with that either. `ED_SHORTCUT` is an internal ex-macro that does transformations that we deemed to be appropritate for the editor internally. It is not fit to be exposed to the plugin API as is, precisely because it does "magic" around key combinations.

Plugin developers should not get exposed to the API that does hidden things beyond their control. And core developers should not be limited because an internal method suddenly got exposed. This is an incorrect approach.

**Comment by SlugFiller** [comment]
@pycbouh The issue is the lack of parity between the C++ and GDScript. In a perfect world, the entire Editor would be written in GDScript, and only the runtime core would be in C++. Then, plugins would be guaranteed access to all the same functionality, and even "games" could enjoy feature-parity with the editor (e.g. for things like Pixelorama). That's not going to happen, though.

Right now, the go-to process for a plugin developer trying to add features to the editor, is to read existing C++ code used by nodes in the editor, and try to imitate/port them in/to GDScript. But that's not an option when methods available to C++ are unavailable to GDScript.

I agree that using an ex-macro might not be the correct solution, but from that perspective, so long as it doesn't merely do something that GDScript would do implicitly (e.g. box/unbox values), it's not the correct solution for C++ components either, precisely because that would create said lack of parity.

Limiting what a core editor component can do to what a GDScript component can do seems entirely appropriate. If this causes them to lack some necessary functionality, then this simply means this functionality was critically missing for GDScript components in the first place, and the fix should apply for both. There's no reason why C++ editor components should be "privileged". Otherwise, for the sake of not limiting core developers, you've limited plugin developers instead.

**Comment by pycbouh** [comment]
This is turning into some philosophical debate, but no. Editor cannot be written in GDScript, not even in an ideal world, it doesn't make sense. And there cannot be a parity between internals of the engine and the editor and the plugin API. Yes, API should be extended, but not by exposing strictly internal methods. I would suggest we expose new, appropriately guarded methods, but we already have `add_shortcut`, `get_shortcut`, `is_shortcut` and even `get_shortcut_list`, so it would make sense to expose them. Maybe with some additional rub and polish applied.

> I agree that using an ex-macro might not be the correct solution, but from that perspective, so long as it doesn't merely do something that GDScript would do implicitly (e.g. box/unbox values), it's not the correct solution for C++ components either, precisely because that would create said lack of parity.

My point was that `ED_SHORTCUT` does transformations that are not necessarily desired by plugin developers. In fact, they can be unexpected and cause confusion. We've decided that internally some key bindings are translated for platforms such as macOS. But that's editor's logic, it's not universal logic, and therefore it should not be the default behavior exposed to the users. A good rule of thumb when creating APIs is to make sure it's not designed in a way that would make it hard job to override the default behavior. And as it stands, it's much easier to reimplement that transformation logic in the userland (after looking at sources and figuring out how the engine does it) than to disable the magic if it was default and you don't need it.

> Right now, the go-to process for a plugin developer trying to add features to the editor, is to read existing C++ code used by nodes in the editor, and try to imitate/port them in/to GDScript. But that's not an option when methods available to C++ are unavailable to GDScript.

I'm well aware of that, being an avid plugin API user myself. And I repeat that yes, more editor features need to be exposed via the API, and no, I am not against exposing this functionality here, regarding shortcuts. I am against exposing that particular ex-macro as is. User facing API needs to be designed to be safe and easy to use, and this method has been designed exclusively for the internal usage.

**Comment by SlugFiller** [comment]
@pycbouh
```
Editor cannot be written in GDScript, not even in an ideal world
```
In theory it could. The editor operates entirely on top of the same runtime engine as the game engine. It doesn't require any native capabilities not available to games, and if it did, it would make sense to make these available to games anyway. In practice, it could have been written in GDScript, but since it wasn't, it's too late now, as it would take too much time and effort to port it.

```
And there cannot be a parity between internals of the engine and the editor and the plugin API.
```
I don't see why not. Plugins are, fundamentally, core features that are simply not a sufficiently common use case to be added to the core (for risk of bloat). Sure, this same concept could be achieved by forking the engine, but it would be far too difficult and cumbersome to let end-users (i.e. game developers) pick and choose the features they need using a fork (assuming cross-compiling the engine for multiple platforms is not expected basic literacy for a game developer). It would defeat the purpose of a plugin system.

```
We've decided that internally some key bindings are translated for platforms such as macOS. But that's editor's logic, it's not universal logic, and therefore it should not be the default behavior exposed to the users.
```
The term "users" is a bit loaded, here. I don't think plugin developers should be coupled with end users. The reason this distinction is important here, is precisely because of what you call "editor's logic", and how it translates to the end user.

Suppose, for example, a plugin developer codes a new component in Windows, using the standard key combinations there. However, having attempted to use the bare functions, and not having considered diving through the (rather large) code of the core engine to find and copy the exact code used to built shortcuts, the end result lacks said "magic translations" for macOS. The plugin is then downloaded and used by an end-user running on macOS. Said end-user is suddenly surprised, as the same muscle-memory shortcuts that were working fine in every native component, are not working for the plugin component.

The only way for the plugin developer to avoid this is to re-implement `ED_SHORTCUT` using lower level methods. This re-implementation would have to be present in essentially any plugin adding editor functionality.

```
it's much easier to reimplement that transformation logic in the userland (after looking at sources and figuring out how the engine does it)
```
I used "looking at the source" as an anti-pattern. "Source-as-documentation" is one of Unreal Engine's main flaws. The only way to avoid it without exposing `ED_SHORTCUT` would be to add a GDScript port of `ED_SHORTCUT`'s code to the documentation of any `add_shortcut` that might be added.

```
to disable the magic if it was default and you don't need it.
```
One possibility is to add a bool parameter (true by default) indicating whether you want the magic or not. However, this use case is actually extremely rare. For the sake of end-users, plugin developers should simply follow the standards set by the main editor, and the API should encourage them to do so. For example, in my own plugin, I sampled the colors from native icons to produce new button graphics that don't look out-of-place within the existing editor's theme. It's a bit like following existing indentation style in an open-source project. There's no "universal logic" to indentation, but it's expected that your additions don't stick like a sore thumb.

**Comment by pycbouh** [comment]
> I used "looking at the source" as an anti-pattern. 

In open source it's the core strength. You don't need to be at the mercy of a blackboxed solution. You can look into the logic behind it and make your own adjustments. Which is why the default behavior must be the least presumptuous one.

At any rate, this is a moot discussion at this point. And yes, editor does need low level access at times, and it needs to be fast at specific taxing tasks.

**Comment by pycbouh** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/4112.
