### ISSUE TITLE
Add support for audio in BRSTM format

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot-proposals#2548]
### Describe the project you are working on
I am working on a project that contains looping music.

### Describe the problem or limitation you are having in your project
Fortunately, I have been having an okay time setting loop points on .ogg format music, but I am annoyed that I have to set the loop point manually; I would love for Godot to accept some of the looping music formats that I already use.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
BRSTM is a sound format developed by Nintendo for the GameCube, which is an ADPCM-compressed audio (lossless, by the way) file with looping metadata. [Here is the specification](https://wiibrew.org/wiki/BRSTM_file). According to Wikipedia, ADPCM is used in the aptX, DTS, and MQA audio coding standards, as well as in some WAV files.

Due to many Nintendo games using the format, BRSTM is popular with modders for games like [Mario Kart Wii](http://wiki.tockdom.com/wiki/Custom_Music) and [Super Smash Bros. Brawl](https://smashcustommusic.net).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
By default, BRSTM audio should loop (like when importing OGG audio), and the loop point set to the correct time. (BRSTM stores the start and end of the loop using samples instead of seconds, but that should be a division away.)

One problem that I anticipate is, because Godot doesn't currently let you specify where the END of the loop should be, so that will have to be added to import options.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
BRSTM can be converted into WAV (as well as other formats) using tools like [Looping Audio Converter](https://github.com/libertyernie/LoopingAudioConverter/releases). Noting down the loop points, cutting the length of the resultant WAV at the end of the loop, and setting the start of the loop in Godot on import should (in theory) result in a perfect loop.

### Is there a reason why this should be core and not an add-on in the asset library?
There could be an add-on that imports BRSTM files and converts it into WAV in order to cache/use it, but having it be in core would be more convenient for users who are already experienced in, or make music for, video game modding.

**Comment by Calinou** [comment]
Godot already supports WAV audio with IMA-ADPCM compression.

**Comment by JapanYoshi** [comment]
Weird; I read online that BRSTM is lossless like WAV. Maybe it uses a different variant of ADPCM. Maybe that article was wrong.

Anyway, it would be convenient if loop points are automatically read by Godot. If it needs to be a plugin...

**Comment by Calinou** [comment]
> Anyway, it would be convenient if loop points are automatically read by Godot. If it needs to be a plugin...

Does OGG Vorbis or MP3 have a sufficiently followed standard for defining loop points?

**Comment by Lauson1ex** [comment]
> Does OGG Vorbis or MP3 have a sufficiently followed standard for defining loop points?

@Calinou yes, with Vorbis comments metadata `LOOPSTART`, and `LOOPEND` or `LOOPLENGTH`. Much like the WAV `smpl` chunks, Vorbis loop points are stored as samples.

- RPG Maker reads the tags `LOOPSTART` and `LOOPLENGTH`;
- Game Maker reads the tags `LOOPSTART` and `LOOPEND`;
- SDL2 reads the tags `LOOPSTART`, `LOOP_START`, `LOOPEND`, `LOOP_END` and `LOOPLENGTH`.

**Comment by Lauson1ex** [comment]
> Does OGG Vorbis or MP3 have a sufficiently followed standard for defining loop points?

@Calinou yes, with Vorbis comments metadata `LOOPSTART`, and `LOOPEND` or `LOOPLENGTH`. Much like the WAV `smpl` chunks, Vorbis loop points are stored as samples. Here are a few implementations which follows the standard:

- RPG Maker reads the tags `LOOPSTART` and `LOOPLENGTH`;
- Game Maker reads the tags `LOOPSTART` and `LOOPEND`;
- SDL2 reads the tags `LOOPSTART`, `LOOP_START`, `LOOPEND`, `LOOP_END` and `LOOPLENGTH`.

**Comment by Calinou** [comment]
Closing due to lack of support. As for supporting Ogg Vorbis loop points, this is being tracked in https://github.com/godotengine/godot-proposals/issues/3307.
