### ISSUE TITLE
Don't use the abbrevation "Sep." in UI text

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-proposals#2551]
### Describe the project you are working on
Translating on Weblate.

### Describe the problem or limitation you are having in your project

The abbreviation "Sep." appears in two UI texts ("Named Sep." and "Sep."), and expands to two different full words, which confuses translators and probably users. (seen in [comment](https://hosted.weblate.org/translate/godot-engine/godot/zh_Hans/?checksum=788f57d5c21596b8&sort_by=-priority,position) section of Weblate.)

The "." at the end also confuses Weblate to think it's a punctuation, emitting a "Mismatched full stop" check failure for translations that does not end with a full stop. Many translations even added an unnecessary full stop at the end of the translated word for "Named Sep.".

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use the full word when possible.

| Current | Proposal |
|---|---|
| Named Sep. | Named Separator |
| Sep. | Separation |

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change the string.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Impossible.

### Is there a reason why this should be core and not an add-on in the asset library?

The text is hardcoded in C++ source code.

**Comment by pycbouh** [comment]
I don't think you need a proposal for this, just an issue on the main repo should probably do. Or you can just make a PR and explain everything there 🙂

**Comment by timothyqiu** [comment]
Thanks. I thought that anything other than bug reports should go here first 🤣 

I'll make a PR in the main repo.

**Comment by aaronfranke** [comment]
@pycbouh A proposal never hurts, though. Worst case, we get a space for discussion where there is nothing to discuss.

**Comment by timothyqiu** [comment]
Resolved by https://github.com/godotengine/godot/pull/47639
