### ISSUE TITLE
Search-list to make finding ANY engine function / method easy in visual script . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2555]
### Describe the project you are working on
A Tomb raider game, with cool graphics, code . . :O <3 . .

### Describe the problem or limitation you are having in your project
Often, I need to find a special function, or method, or property, in visual script, and it's not on the normal list, of nodes, prob. to not make the ' default ' list so long, it was impossible to manage, the default list has the most common nodes, functions . .

But, if I search for change_level, it doesn't show up, it's a ' special ' function, under the ' Scene Tree ' node only, and happens, when one pulls out the port . . My proposal is, add a feature so one can search ' all ' functions, methods, properties, in Visual script, and have it auto - set-up, the nodes . .

So, if I search in the ' longer ' list, for ' change scene ', it finds all methods, properties, with those words, and then you can see those . . for instance, these are not normally seen, but only when you make a ' Scene Tree ' node, and pull out the port . .
<img width="1150" alt="Skærmbillede (1350)" src="https://user-images.githubusercontent.com/61069740/113589487-b047ee00-9631-11eb-8be8-f7ee76525c22.png">

So, I propose we have a feature that, allows you to search for any method, or property, in the engine . . and, if you double-click, it auto set-ups the nodes, to that ' line ', of code <3

<img width="908" alt="Skærmbillede (1351)" src="https://user-images.githubusercontent.com/61069740/113589715-fd2bc480-9631-11eb-9dbc-5e38b420d4b7.png">

Last, in that search list, it would be a big help, if it was written also, as the ' code ', or so . . so, if I search for change scene, the list shows this search . . .

SceneTree.change_scene(str), in words . .

Then, double-click that, and it makes two boxes, a Scene Tree node, with a ' change_level(str) ' connected . . <3

This would help visual script users find any property, they can see in the docs and, would make it easier to follow ' written code ' tutorials, or so <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Right now, as a new user, one has to be a genius to find the really ' hidden ' stuff, it makes no sense . . . This feature would really help, and bridge the gap between the well-documented written code docs, and also visual script . . the idea is, it then ' creates ' the visual script boxes, properly connected, to get that ' code ', or such . . . <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
A ' new ' search bar, or list, where one can search for any method, property or, function, find it fast, and it sets up the boxes, or so . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't code the engine <3 . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it'd make Visual script 100 % easier to user, esp., for new users . . :OO . . Thx . . .

**Comment by jasperbrooks79** [comment]
Add, it'd also mean, if I saw some ' written ' code, I could search for that, like in youtube video, and I could find, maybe not always one, but maybe, three, four ' possible ' nodes, or node set-ups, and that would help, a ton . . . Thx . . <3

**Comment by jasperbrooks79** [comment]
Also, many new users have trouble finding an custom - made singleton, maybe add a last list, where the singletons are, and one can ' search ' there, and it set up these boxes, or so . . .

<img width="1048" alt="Skærmbillede (1358)" src="https://user-images.githubusercontent.com/61069740/113661206-f474d600-96a5-11eb-81ea-50f67c584489.png">

so, there's a search panel, for ' normal nodes ', ' any property / method ', and a last list, where all the user - made singletons are listed, to quickly add <3 . . this would help quite a bit, for new users . .

this . . .
<img width="1076" alt="Skærmbillede (1360)" src="https://user-images.githubusercontent.com/61069740/113661561-a2808000-96a6-11eb-9007-99e15ad5481f.png">

and, when one clicks it, it sets up the proper node structure <3 Not sure, if it can be done :(( . . .

**Comment by jasperbrooks79** [comment]
LAST, one can ' move ' things from project settings, into a visual script canvas, if there was a search list, for those, as last search bar :OO one would have the entire engine, at one's finger-tips, there could even be a last ' big ' search list, that simply had all these lists, or so :OO <3

**Comment by fire** [comment]
Fixed by https://github.com/godotengine/godot/pull/56252.

**Comment by pycbouh** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/3528 (which will be resolved by the aforementioned PR).
