### ISSUE TITLE
Improve user-friendliness of defining and set/get singletons, in visual script . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2558]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
Right now, it's a bit complicated, esp. for new users, to define true global variables, singletons . . I was thinking, why not make a new ' place ' in the visual script editor, where one could add singletons, more easy . .

<img width="586" alt="2021-04-06 0801" src="https://user-images.githubusercontent.com/61069740/113665861-84b71900-96ae-11eb-8e20-a2c7585af8e7.png">

When one ' adds ' the first one, there's a question, where to ' store ' them, ie. a code resource, so one types, maybe ' my_singletons.vs ', then one can add them, and set or, get them, faster . . since these are global to any script, one would have to ' generate ' the list, for all visual scripts, ie. they'd not be local, to one script, maybe it can be made better, or have a separate panel, or so . . one could even take the more ' complex ' set - up, for get or, set a singleton, and make it into ' one ' box, called Get Singleton ' name ' . . :OO . .

Or, one could simply generate a ' default ' singleton script, instead of the user typing a name, and store it in the root res:// folder, maybe call it default_singletons.vs, like default_env.tres <3 . .

The first click, would set up a ' autoload ', for the user, and also ' enable ' it, or so . . this would improve the user - friendliness, of the singleton process, I think . . <3

I think the node-path, and all that stuff, would be implied, when creating it, so could be just one box, SET and, GET, like for normal script - local variables <3 . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Make so one can make a singleton variable, in the visual script canvas, alone, so it's faster, and ' makes ' more sense, that's all, thx . . . <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See the images above, so one can make singletons, faster, and it makes more sense <3 . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I'm not sure, one can always manually create a new script, as a resource, and add it to auto-load, and then double-click it, to add a new singleton, but it's a bit 'weird', that such a useful feature, isn't easier, to access, or so . . 

### Is there a reason why this should be core and not an add-on in the asset library?
Well, would make things a bit easier, also for new users, and maybe this way, instead of using three boxes, to get, or set a singleton, one could just have a ' composite ' node or, box, like with set, get a normal variable <3 . . . Thx . . <3 It'd be a massive help, for new users, and one could even re-name singletons, to ' Global Variables ', maybe only in visual script canvas . . :OO or, write 'Global Variables (Singletons) + . . <3 . . .

It may be a bad idea, to ' call ' them Global variables, since new users won't know, what difference between a normal variable, and global variable is, from sort of, looking <3 . . .

ps. the singleton list might be some-what large, so if one could collapse it, and the same for normal variables :O . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
