### ISSUE TITLE
A recommendation.

### ISSUE THREAD

**Issue by Tazshelby2016** [godotengine/godot-proposals#256]
More of a recommendation than a feature/enhancement (Recommendations are not spoken about on either this repo or the main repo, so I will talk about it here.)
In the main repository, it seems that very little is done with pull requests that contradict each other or are straight-up copies of each other. I would recommend going through this clutter to help viewers, who see thousands of issues just sitting there.

**Comment by clayjohn** [comment]
Please read the rules on the main page of the repo
https://github.com/godotengine/godot-proposals

You must fill out the template for proposals properly or your proposal will be closed. 

To address your concerns, the core contributors are well aware of the problem and the solution. However, it will require hundreds of hours of volunteer time, to clean up the current issues and there is no one volunteering that much time to do it.
