### ISSUE TITLE
Blend Shapes should include a warning that they do nothing in GLES2

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot-proposals#2563]
### Describe the project you are working on
VR mapping gestures to avatars

### Describe the problem or limitation you are having in your project
I just used a lot of time trying to get blend shapes to do something in Godot.  I was loading in a GLB file and moving the values around, but nothing was happening.
![image](https://user-images.githubusercontent.com/677254/113855564-15b5ef00-9798-11eb-83e8-9088411250c2.png)

Eventually I found this docs note here:
    https://docs.godotengine.org/en/latest/tutorials/rendering/gles2_gles3_differences.html#blend-shapes

I have GLES2 selected most of the time because it's necessary for doing VR for the Oculus Quest2, since it's a mobile platform, so it didn't cross my mind that this could be the problem.  

When I checked with someone else doing similar VR coding, they also thought that blend shapes in Godot didn't work at all and wasn't a feature.  It's a relief to find that they are there, because I thought I was going crazy.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
As it has proven difficult to find out about this limitation, we need a contextual warning for people who get stuck.

For example, a _"This does nothing"_ note is included in the tooltips for the LOD values, as seen here:
![image](https://user-images.githubusercontent.com/677254/113857097-02a41e80-979a-11eb-8d22-b6e4e7b16cb5.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Can the Tooltips for the blend_shapes properties include a similar note when GLES2 is selected?

Also, is this just a temporary issue?  Is the Godot4.0 mode used for the Oculus Quest (and other mobile platforms) going to implement Blend shapes so it's no longer a modal limitation?  

### If this enhancement will not be used often, can it be worked around with a few lines of script?
N/A

### Is there a reason why this should be core and not an add-on in the asset library?
It's core UI

**Comment by Calinou** [comment]
> Can the Tooltips for the blend_shapes properties include a similar note when GLES2 is selected?

This only requires modifying the class reference – you don't need to open a proposal for that. You can ask for such documentation changes on the [godot-docs](https://github.com/godotengine/godot-docs).

**Comment by clayjohn** [comment]
Blend shapes were added to GLES2 so closing :)

https://github.com/godotengine/godot/pull/48480
