### ISSUE TITLE
Add the possibility to pass unique parameters per instance to a shader

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot-proposals#257]
**Describe the project you are working on:**
A Spatial shader whose attributes (ALBEDO, ROUGHNESS...) would be influenced by the position of the instance in the 3D world.

**Describe the problem or limitation you are having in your project:**
It is impossible to pass a parameter related to the instance of a mesh.
If two instances of a mesh share the same shader, all instances will have as parameter value the last one passed to the shader.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The possibility to pass (one or more) unique parameter for each instance would allow to use a single shader for several meshes while keeping the possibility to modify their aspect.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![godotVertexColor](https://user-images.githubusercontent.com/46683101/69718771-6f6fc900-110f-11ea-9e4b-9893070864fd.gif)

The two cubes above are instances of the same resource.
They share the same shader, mesh and script.
The color of the vertices of each cube is given by its position in the 3D world.
Unfortunately, currently the shader uses as a parameter the color of the last mesh drawn: both cubes have the same color.

![BlenderColor](https://user-images.githubusercontent.com/46683101/69721490-3e929280-1115-11ea-95eb-718aaa897d84.jpg)

The ability for the shader to retrieve one or more parameters unique to each instance would allow, as in Blender, to influence the rendering of instances of a mesh sharing the same attributes.

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by galmiza** [comment]
It seems the method **set_instance_custom_data** of class **MultiMesh** is what you need.  
See https://docs.godotengine.org/en/3.1/classes/class_multimesh.html

**Comment by TheMoye** [comment]
> 
> 
> It seems the method **set_instance_custom_data** of class **MultiMesh** is what you need.
> See https://docs.godotengine.org/en/3.1/classes/class_multimesh.html

Hello galmiza,

I saw it, but going through a MultiMesh requires to position the instances by a script (if I understood everything).
This is not always what we want : in my case instances are positioned during the level design in Blender.
It would be nice to have the same kind of possibility with simple Mesh.

**Comment by Calinou** [comment]
You can enable the **Local to Scene** property on the Mesh resource and its materials (or just the materials if they're set outside the Mesh):

![image](https://user-images.githubusercontent.com/180032/69724062-54a35180-111b-11ea-8513-9c48ec80bcbf.png)

This will duplicate the resource in every instance, making it possible to tweak parameters without affecting all other instances. Of course, this will be slower than sharing the material across all instances.

**Comment by TheMoye** [comment]
> Of course, this will be slower than sharing the material across all instances.

This is the important point of the thing :grin:

**Comment by clayjohn** [comment]
What you are asking for is impossible. If you don't want to share uniforms, you must use unique materials. All a material is, is a bundle of uniforms attached to a shader object. If you share a material then by nature you share uniforms. If you want each instance to have unique uniforms, then each instance needs its own material. 

You can share a shader across all the instances, by only making the material unique, that way, all your shaders will be the same and you get most of the speed benefit, and then you still have unique uniforms for each instance.

**Comment by TheMoye** [comment]
> What you are asking for is impossible. If you don't want to share uniforms, you must use unique materials.

Hello clayjohn,
I may be wrong, but it seems to me that Unity allows us to pass parameters per instance.
I wasn't thinking specifically about user-defined parameters but rather like what we find for Particles (a unique index, a velocity per particle...).

**Comment by clayjohn** [comment]
Ah, then it sounds like MultiMeshInstance is what you are looking for. Just like @galmiza suggested. :) 

Here is a tutorial on using per-instance attributes for each object to create complex shader effects.
http://docs.godotengine.org/en/latest/tutorials/3d/vertex_animation/animating_thousands_of_fish.html

**Comment by TheMoye** [comment]
> Ah, then it sounds like MultiMeshInstance is what you are looking for.

Yes I have already looked at this part of the doc, but as explained above, with MultiMeshInstance the position of the instances must be script-driven.
And it's not (easily) compatible with a level-design "by hand".

**Comment by Calinou** [comment]
@TheMoye I guess MultiMeshInstance usability is a topic for another proposal :slightly_smiling_face:

**Comment by galmiza** [comment]
> Yes I have already looked at this part of the doc, but as explained above, with MultiMeshInstance the position of the instances must be script-driven.
And it's not (easily) compatible with a level-design "by hand".

You can design your scene in Blender, import it as-this in Godot and "optimise it" automatically at runtime with some scripting. For instance, you can pack similar meshes into a MultiMesh.

**Comment by TheMoye** [comment]
> You can design your scene in Blender, import it as-this in Godot and "optimise it" automatically at runtime with some scripting. For instance, you can pack similar meshes into a MultiMesh.

That could be a good idea. :thumbsup:
I'm not sure that below a certain number of instances the performance gain between a MultiMeshInstance and a Mesh is perceptible.
And it takes a little more work to create a script to position the instances correctly.

**Comment by superoven** [comment]
For weary travelers looking to solve this problem:

I know this is a hack, but it's how I ended up handling passing unique variables to canvas_item shaders. Rather than use the shader uniforms, which are shared across all instances, I passed unique data on the red channel of the canvas_item's modulate and just retrieve my original number with code on the shader side like 
```
float MAX_VAL = 99999.0;
int my_num = int(clamp(floor(MODULATE.r * MAX_VAL), 0.0, MAX_VAL));
```
Yes, there are floating-point issues abound and this is makes it so you can't _actually_ modulate the color of your shader, but if this is acceptable to you, it works.

**Comment by Zireael07** [comment]
Nice workaround, I wish we had a Godot tips and tricks page collating all of those (there's at least five I use scattered across different PRs/issues)

**Comment by Calinou** [comment]
This is a commonly used trick in 3D with mesh vertex colors too. I'm not sure where it could be documented specifically, but this trick is still relevant in 3D in 4.x if using the Compatibility renderer (as per-instance uniforms in 3D are limited to Vulkan).

**Comment by CsloudX** [comment]
So love the `instance uniform`, can implement this feature in `canvas item` shader?
