### ISSUE TITLE
Improve 'triangulation' of imported meshes . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2580]
### Describe the project you are working on
A Tomb raider game <3

### Describe the problem or limitation you are having in your project
I've looked at the ' triangulation ' when importing, to the Godot engine . . It doesn't look at good, as Blender does it . . Is it possible to improve the algorhithm, so it looks nicer . .

![Skærmbillede (1429)](https://user-images.githubusercontent.com/61069740/114224704-b6abd200-9971-11eb-85d0-015702555811.png)
Godot, makes some ' bad ' triangles, could give artifacts, during animation, not sure . .

![Skærmbillede (1428)](https://user-images.githubusercontent.com/61069740/114224755-c75c4800-9971-11eb-8062-3985f3f8289b.png)
Same model, triangulated in Blender ( edit mode, faces, Triangulate ) . .

Notice how Blender makes more ' clean ' topology, could this be done, in Godot <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Improve the ' method ', in Godot, for this . . <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Not sure, right now it COULD be improved, or so . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't do this </3 . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it'd give nicer 3-d models, maybe improved animations, etc . . <3 Thx . . .

**Comment by Calinou** [comment]
If you want reliable triangulation, it's recommended to triangulate in the 3D DCC (like Blender) instead of letting the game engine do it for you. This advice isn't exclusive to Godot – it's also good practice for any kind of 3D I/O.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP and general lack of activity here).

Triangulating meshes before exporting them is documented here: https://github.com/godotengine/godot-docs/blob/46a907f4457c1e967c0a90c0541a877427c67c59/tutorials/assets_pipeline/importing_scenes.rst#L98-L116
