### ISSUE TITLE
Add support for rendering to a floating-point texture

### ISSUE THREAD

**Issue by galmiza** [godotengine/godot-proposals#259]
**Describe the project you are working on:**

I am working on a FPS and need to implement my own shadow rendering pipeline.

**Describe the problem or limitation you are having in your project:**

I need to render an accurate float representing depth to a texture.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**

Class **Viewport** can add a parameter **texture_type** to choose between **RGBA** and **FLOAT** texture types.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I currently need to pack the float into the RGBA texture and can only reach a float accuracy of 24-bits (as ALPHA channel can't be used as Godot triggers some incompatible pipeline processing if it is written).

**Is there a reason why this should be core and not an add-on in the asset library?:**

It must be core as it is low level.  
OpenGL offers a lot of different texture types (see https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml).  
I believe having just the two types RGBA and FLOAT is enough to cover most of the use cases.

**Comment by clayjohn** [comment]
This sort of thing may already be coming in 4.0 with low level access to the rendering device API. :)

**Comment by galmiza** [comment]
This is good news!
I was more thinking about an option available directly in the editor.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2935, which provides more information about potential use cases.
