### ISSUE TITLE
Support lossless WebP for texture import

### ISSUE THREAD

**Issue by mortarroad** [godotengine/godot-proposals#2593]
The purpose of this issue is to discuss the inclusion of Lossless WebP, and how to implement it best.
I am hoping to implement this myself.

### Summary
Lossless WebP has faster decompression and smaller file size than PNG. See https://developers.google.com/speed/webp/docs/webp_lossless_alpha_study
Only the default encoding speed seems to be lower. (But by choosing a fast preset, it looks like it is faster and still yields a smaller size.)
WebP is already supported in Godot, but the lossless mode is not made available.

### Implementation approach
Since the WebP library is already included, the implementation is mostly about how to enable the user to access it.

Completely replacing PNG with WebP is not possible, since WebP absurdly only supports image sizes up to 16383, therefore the largest power of two supported is 8192.
Larger textures may be a rare use case, but should still stay supported.

Therefore, the most sensible approach seems to be the following:

**Rename** the existing formats:
`DATA_FORMAT_LOSSLESS` becomes `DATA_FORMAT_PNG`,
`DATA_FORMAT_LOSSY` becomes `DATA_FORMAT_WEBP`.

Then, in the lossless importer mode, another checkbox (perhaps called "Use WebP") is added.
That means the `COMPRESS_LOSSLESS` can import both PNG or WebP.

**Comment by Calinou** [comment]
> Larger textures may be a rare use case, but should still stay supported.

We can use WebP for textures smaller than 8192×8192 and PNG for the rest. With such large sizes, you're expected to use VRAM compression anyway.

**Comment by mortarroad** [comment]
Even if we keep the user-interface the same, I'd rename the constants, since they are always that specific format.
Anything else is just needless abstraction.

**Comment by mortarroad** [comment]
A side note:
When generating mipmaps is checked in the importer, mipmaps are actually stored in the file for the lossless mode!
For VRAM compression this makes sense, because the compression and therefore generating mipmaps is expensive.
But for lossless textures, there is no expensive encoding step, and generating mipmaps on the GPU is faster than precomputing and uploading them.

**Comment by Calinou** [comment]
> But for lossless textures, there is no expensive encoding step, and generating mipmaps on the GPU is faster than precomputing and uploading them.

We can use pregenerated mipmaps to get higher quality mipmaps. However, this isn't implemented yet: https://github.com/godotengine/godot-proposals/issues/2450

**Comment by clayjohn** [comment]
Regarding storing mipmaps, we also want to implement proper texture streaming (loading higher level mips first) which won't work if we don't pre-generate the mipmaps.
