### ISSUE TITLE
Add a tile variation tool for already-placed tiles to the TileMap editor

### ISSUE THREAD

**Issue by mathias17** [godotengine/godot-proposals#2596]
In light of [@groud Gilles Roudière's awesome tiles editor progress](https://godotengine.org/article/tiles-editor-progress-3), now is the time for me to finally request this long-wanted Godot tilemap feature - something that would provide an efficient means of changing any tile's variations after they've been placed.
In his upcoming 4.0 update, Gilles has already implemented some improved variation choosing when tiles are placed, as seen [here](https://godotengine.org/article/tiles-editor-progress-report-2), but can changing the variations of specific tiles _after_ placement still be improved?

### Describe the project you are working on.
2D game which utilizes a lot of tilemap terrain sets - most tilemaps containing a lot of tile variations.

### Describe the problem or limitation you are having in your project.
Once tiled terrain is laid down, it's currently clunky and time-consuming going back through the tiled environments and changing desired tiles to use a different variation - in order to improve aesthetics, fix awkward repeats, etc.
I don't feel like I have enough control over tile variations, after placement.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation.
This feature would probably take the form of a new tool rather than settings that affect tile placement.
All this tool would do is randomly change a clicked tile to a different variation (a tile from the same terrain set which has the same bitmask) and nothing more. It wouldn't alter terrain or mess up auto-tiling in any way. If a clicked tile has no variations, then nothing would happen.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams.
Warcraft II's map editor demonstrates the idea fairly well:
(https://i.imgur.com/BMIBZK6.gif)
![GIF of Warcraft II's map editor while randomly changing tile variations.](https://i.imgur.com/BMIBZK6.gif)
In the above GIF you can see random variation changing in action.
Terrain was first painted using "plain mode" which doesn't use any randomization.
Once the snow, ice, and water tiles are in place, I then go back over it and alter tile variations (in an overtly ugly way but I'm just trying to give a visual demo).
In the Warcraft II map editor there is no dedicated randomizing tool like I would like. It's only a mode. As long as I have "snow" selected, and have switched to "Random" mode, if I then click on a snow tile, it will change that snow tile to random snow variation. **Instead, I want to simply click on _any_ tile and it change to a random variation without needing to select snow first.**

To accomplish this sort of thing in Godot 3.2, I must toggle Autotile and fish through my tiles for a specific tile variation and manually place it. The more tiles there are in the set the longer I spend fiddling around in the ui searching for tiles and trying to figure out which tiles I should be using. While having the option to do so is a good thing, it's the _only way_ to do it and becomes tedious pretty quick.
GIF of Godot 3.2 using the tile editor and making manual changes to tile variations:
(https://i.imgur.com/OJ4rieC.gif)
![GIF of Godot 3.2 using the tile editor and making manual changes to tile variations.](https://i.imgur.com/OJ4rieC.gif)
Detail-oriented level artists will likely want to make tweaks to random tile variations as they make progress laying out their tiled environments, but Godot 3.2 doesn't facilitate doing this as well as it could.

A new tool dedicated to manipulating variations would be my personal preference. This way it could be easily switched to with a keyboard shortcut and perform the function of randomizing variations in a very controlled way for the user.
Addition of a new tool into Godot's intentionally streamlined minimalistic ui is a big ask, but I don't see this need being met by adding a new option checkbox to the Paint Tile tool because when altering variations you don't want to accidentally paint new tiles at the same time.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, I don't believe so. It would mean adding a tool or some other editor ui change.

### Is there a reason why this should be core and not an add-on in the asset library?
I would expect this type of functionality to become part of any tilemap using level artist's environment art workflow (assuming they use tiles with variations) so I recommend it be considered for base Godot editor inclusion.
It's something that feels like it's missing from Godot 3.2 and the (amazing) upcoming 4.0 tiles editor update doesn't seem to fully satisfy the need.

**Comment by Calinou** [comment]
cc @groud

**Comment by groud** [comment]
This is already working more or less like that in the current implementation. Two tiles can have the same terrain patterns and are thus randomly picked from when painting the terrain. It's indeed not perfect as in some situations, you might have to click several times on a terrain (if you set some variations as rare), but otherwise it works:
![Peek 21-06-2021 11-09](https://user-images.githubusercontent.com/6093119/122737516-67432580-d281-11eb-89ed-4e047b1a1de7.gif)

I am not sure we need something more advanced like that, as it's already possible to have those random variations and you can still select the tiles in the normal painting mode if you need to do specific changes.

**Comment by mathias17** [comment]
Hello, @groud! Tiles Editor update looking great, way more features than I was expecting when I first heard you were going to start on it. Nice work.

_(I'm thinking this is one of those software feature requests where a developer trying to create something streamlined and clean and elegant may see it differently than the "power user" who spends countless hours using the tools in a real-world scenario, which is a very natural point-of-view issue.)_

You're right, this feature idea doesn't _really_ add missing functionality - it's trying to add convenience, reduce clicks, and save time. There are little bottlenecks here and there in most workflows, right? When using Godot 3's Tiles Editor, manipulating already placed variations is certainly one of them (for me).

But with your new Tiles Editor, it looks like we can now press a key to switch to the eyedropper, click the tiles we want to change variations for, then switch to paint tool and click in canvas to "re-paint" those tiles, clicking as many times as we want in order to alter already placed variations. This is a big improvement, and concerning control over variations this is already better than both the WarCraft II editor and Godot 3. Needing to click the same tile multiple times to cycle through variations is no problem.

But a tilemap user like me will still prefer a dedicated means of changing variations that doesn't first require selecting the right tile set and that can't accidentally mess up terrain by mis-clicking.

What do you think of this? -
_Updated Suggestion:_
(https://i.imgur.com/uuMmoVQ.png)
![Probability checkbox added.](https://i.imgur.com/uuMmoVQ.png)
A probability checkbox added to the options bar of tile painting tools which, if checked, will only affect probability values of clicked tiles. While this option is turned on, terrain sets cannot be altered - only variations.
This way, need for a new unique tool is negated, and with this option turned on tile terrain cannot be accidentally messed up when only wanting to manipulate placed variations.
Ability to set a keyboard shortcut for toggling this new checkbox would be beneficial.

**Comment by groud** [comment]
> A probability checkbox added to the options bar of tile painting tools which, if checked, will only affect probability values of clicked tiles. While this option is turned on, terrain sets cannot be altered - only variations.

Well, I'm not up for this solution. There's already the "paint random tile" next to it, it would be quite confusing IMHO.

To be honest, there are going to be so many ways to be efficient in the new TileMap editor that I hardly see why this specific feature would be needed. I'm not against the idea, but unless there's a significant amount of users feeling the need for it, I won't bother personally.

**Comment by mathias17** [comment]
> Well, I'm not up for this solution. There's already the "paint random tile" next to it, it would be quite confusing IMHO.
Right. Those two almost seem like they should be paired radio buttons or something. Figured you'd have a better ui idea.
Key difference with new checkbox being that affecting tiled terrain gets disabled and only variations are alterable, which means one could carelessly paint over multiple terrain set edges and only randomize variations - something I've always wanted in every tile editor I've ever used.

Okay, I think we've fully explored this topic.
If I address this subject again it'll be after 4.0 once I've had a chance to use your new stuff. Looking forward to it!
