### ISSUE TITLE
Make some new editor looks that reflect how cool, awesome Godot is . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2599]
### Describe the project you are working on
A Tomb raider game <3

### Describe the problem or limitation you are having in your project
Well, Godot is amazing, does well, just blimey amazing . . But, I feel in a small way, the editor looks too ' simple ', or basic . . And, the node icons, it sort of looks like a ' cheap ', or phone app, for people not used, to computers :O . . 

![2021-04-13 0855](https://user-images.githubusercontent.com/61069740/114509692-1b974e80-9c36-11eb-89c8-bef4749ff7ad.jpg)

Now, I'm a bit, of a 'hard - core' nerd, and I think it could be amazing, if we got a 'hard-core' editor look, one could load, like a theme, I guess best examples are more serious software . . imo, this would give a ' nicer ' feeling, when one wants to make an AA or, AAA game :OO . . and, give you a hint, this engine CAN deliver, results . . . I also think, since I'm a HUGE geek <3 that it'd be nice, if there was a techno-electro look, or so . . as well, also, as a ' more ' hard - core, awesome look <3 . . .

![2021-04-13 0859](https://user-images.githubusercontent.com/61069740/114510103-8ba5d480-9c36-11eb-9b9a-b7b09321243b.jpg)

When I look at the editor, it almost looks like, it is made, to do ' kids ' games, or for some young teens . . . . the icons are so friendly, it looks like the engine isn't that ' cool ', or so on . . I'm not sure WHAT such an alternate editor look would be, and the default one, people know, should be the ' default ' one . . but, I want to make some kick - ass games, that ' REALLY ' rock, and I feel in a way, the program isn't ' capable ' of doing that, like I can make, sorry, Mario or, Sonic in it, that's that . . 

I guess I'd like, that the engine had a ' hard - core ' look or, 'visual' . . and, that the icons were more bad-ass, just over-all, it looked ' rock - solid ', performant, more . .

![2021-04-13 0902](https://user-images.githubusercontent.com/61069740/114510483-0969e000-9c37-11eb-8a9e-4eaa952653ab.jpg)

I realize this might be ' close ', to having a ' commercial ' word ( bad, bad . . ! ) but, that's not what I'm asking for, just that it looks a bit more hard-core, adult, felt ' cool ' :O . . It's a fine line, not sure how to explain it . . But, I'd like the editor to be able to look, like I'd feel at ' home ', as a grown nerd, like it's ' Heaven ', for adult, mature geeks <3 . . of course, the default look should be standard, maybe it could be added as an option, or so . . :OO 

I don't want a ' commercial ' look, just a more competent, ' nerdy ', or cool look, or so . . Some-thing, where you don't feel it's ' commercial ', but that nice ' hard - core ' feeling, or so . . So, when you boot the engine, you feel it can do anything, or close <3 . . Like, it's hard-core geeky software, really nice, amazing . . <3 <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Not sure, right now I just feel, the engine user-interface is telling me, this is not really for hard-core, 'serious', well-running, optimized games, or so . . it's like, it's aimed at kids, young teens, and that's all it can do . . Was hoping, not we get a ' commercial ' look, which is something different, but maybe a ' Godot Hardcore ' alternate look, with ' nicer ' icons, or interface . . :OO 

![2021-04-13 0908](https://user-images.githubusercontent.com/61069740/114511166-d70cb280-9c37-11eb-982c-3fee7feb4d7e.png)

But, instead of thinking ' commercial engine ', just think, a ' hard - core ', geek paradise look, where it's like it can make the CPU, graphics cards, do back-flips and, ' push ' it . . <3 <3 Thanks . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, a look, that makes you feel, Godot can pull some weight, really do, bad - ass stuff or, so :O . . there's a line, where it starts looking commercial, it's not about that, yuck . . . but, having a more hard-core look, would make you feel, if you wanted to make a cool AA, or AAA title, that the engine wouldn't crash or, ' fall ' apart <3 . . Thanks . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not sure, I constantly feel I'm not using the right engine, I made sort of more complex 3D stuff, for a Tomb Raider game, PS2-PS3 quality, and it's like the engine is telling me, ' I can't do that ', it's made for simpler, less ' awesome ' stuff :O . .

![2021-04-11 1724](https://user-images.githubusercontent.com/61069740/114511527-50a4a080-9c38-11eb-824e-40e233474444.gif)

![2020-10-09 1457](https://user-images.githubusercontent.com/61069740/114511658-7df14e80-9c38-11eb-93e2-54747c9ffb52.gif)

Like, I'm making AA - AAA games, and while the engine prob. can do that, I'm sort of always thinking, this engine will crash, it can't do AAA, or even decent AA, look at the icons, it's for making phone games or, tablet games :( :( . . 

### Is there a reason why this should be core and not an add-on in the asset library?
Not sure, I'd like a hard-core, competent, nerd-paradise, amazing code, wonderful 3-d look, where editor tells me, ' we can handle this, add more code, stuff <3 ' . . Thanks . . . .

Add: Like Blender or, a bit more, something nice, something ' robust ' <3

**Comment by jasperbrooks79** [comment]
Like, here's a famous video, of some-one adding Quixel assets, to Godot . .

https://www.youtube.com/watch?v=xHd_-mtJpu4

Looking, at the interface one almost thinks, engine will have a ' seizure ', if one tries that . . may-be it could be inspired by Blender, or similar . . without looking ' commercial ', just cool, amazing . . . Thx . . <3

**Comment by pycbouh** [comment]
The feeling of professionalism is a matter of taste. Godot has pretty inoffensive UI that is fitting for many occasions, IMO. Be that as it may, this proposal is too vague and too wishful. I also feel like you've proposed several things that directly relate to it in the past.

So please stick to more concrete ideas about what you propose to change, don't make issues about making Godot more X in general.

**Comment by KoBeWi** [comment]
btw there are already plans to improve the editor look, see https://github.com/godotengine/godot/pull/45607

**Comment by jasperbrooks79** [comment]
I read the proposal, yes please <3

gonna give it a bunch of thumbs-up, that's all . . :OO <3
