### ISSUE TITLE
Implement seeking on VideoPlayers

### ISSUE THREAD

**Issue by linky00** [godotengine/godot-proposals#2602]
### Describe the project you are working on
An art installation under the guise of a television, in which a user can switch between the channels.

### Describe the problem or limitation you are having in your project
When a user switches to a channel, it should start playing a larger video stream from a specific timestamp depending on the time it currently is. However, Godot doesn't have time seeking implemented!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Implement a method on a VideoPlayer to actually set the video to a specific timestamp.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`set_stream_position(value)` should set the stream position (in seconds).

To keep it in line with AudioStreamPlayer, it would be neat if you could hand the play method a position to play from i.e. `play(float from_position=0.0)`.

Alternatively (though this may break compatibility), you could have it work the exact same way as AudioStreamPlayer, so give it `get_playback_position` and `seek` in place of the `stream_position` property (or change AudioStreamPlayer to work the same way as VideoPlayer, consistency would be nice!)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No way to work around it outside of letting the video play in the background, which is expensive and forces you to wait for it to get to the right point.

### Is there a reason why this should be core and not an add-on in the asset library?
This is pretty essential behaviour for a VideoPlayer, and there's already an empty method for it in the codebase.

**Comment by pycbouh** [comment]
Fixed by https://github.com/godotengine/godot/pull/47838?

**Comment by golddotasksquestions** [comment]
It would be really nice if this method could be the same for all playback Nodes. See https://github.com/godotengine/godot-proposals/issues/287

Since `$AnimationPlayer.seek(float second)` is probably the one best known, it would be nice to have the method name the same

**Comment by golddotasksquestions** [comment]
@pycbouh 
Sounds to me like it is not exactly a fix for this proposal as https://github.com/godotengine/godot/pull/47838 does not allow seeking as such:
https://github.com/godotengine/godot/pull/47838#issuecomment-819126956

**Comment by EIREXE** [comment]
> @pycbouh
> Sounds to me like it is not exactly a fix for this proposal as [godotengine/godot#47838](https://github.com/godotengine/godot/pull/47838) does not allow seeking as such:
> [godotengine/godot#47838 (comment)](https://github.com/godotengine/godot/pull/47838#issuecomment-819126956)

You know, thinking about it, it isn't that much different than from what audioplayer does, audioplayer also doesn't guarantee that the song will play right after play() or seek() is called, so we could just get rid of the property and make it be the default behaviour, but I added it as a property so as not to change how existing projects work.

**Comment by Calinou** [comment]
Closing, as this is actually a bug: https://github.com/godotengine/godot/issues/14430

**Comment by CsloudX** [comment]
I think it have some alternative solutions first then remove feature.
For me, covert to project to 4.x, do so much work, then found can't seek video any more.

**Comment by golddotasksquestions** [comment]
@CsloudX not sure what you are talking about, seeking for the VideoPlayer node was not implemented in Godot 3.X

**Comment by CsloudX** [comment]
@golddotasksquestions , Sorry about that. I mean, many features that I love in 4.0. And when 4.0 was dev, I'm try convert my project from 3 to 4. recently, I'm try simulate a video player in my project and found it can't seek position. and search this proposal, 

> **Edit (February 2022):** Someone is working on support for seeking WebM videos in `3.x`: [godotengine/godot#57690](https://github.com/godotengine/godot/pull/57690)

I *guess* 3.x was implement this feature but 4.x was not(MY FAULT, I'm not test). so I'm a bit angry. Sorry about that again.
ADDTION: I'm realy wish can seek position in video stream. format only ogv not a problem, because i can covert format use other software. and seek position was not anly alternative solution.
