### ISSUE TITLE
The size of the start-screen logo is too big

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2605]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I read some-one said, it's important to signal, also for tutorials, that we have a new version, I've been thinking, why not write the version, on may-be the start-up screen . . Like here . . . <3
<img width="1238" alt="Skærmbillede (1469)" src="https://user-images.githubusercontent.com/61069740/114715486-66e35700-9d33-11eb-9fd3-4f08ac1e1f20.png">

Also, it might be a nice idea, if the logo was updated, a little bit, or so . . Notice, I added a few lines, under the ' logo ', that's the best I could do, in MS Paint <3 . .

Last, I think the logos are too big, for the screen, and could be ' made ' smaller, a little bit . .

<img width="693" alt="Skærmbillede (1469) - Kopi" src="https://user-images.githubusercontent.com/61069740/114715758-b3c72d80-9d33-11eb-90f1-f03ca3ad14df.png">

I think the start-up screen is over-powering, is a bit scary, I read some-one wanted, a ' new ' editor look, also for tutorials, not sure . . I think, giving the start-up screen an over-all, and maybe making the icon ' slightly ' different, in a nice, taste-ful way, could help ' sell ' the engine and, impress, or such . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It's just an idea, on ways to signal there's a new engine, and also what number it is, ie. version, which is important, imo . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, I use Microsoft Paint, so I can't really do much . . These are just prelimenary ideas, I hope it could start a discussion, to what ' look ' the start-screen should have, since that sends a big signal, and is often seen, about what the engine is / does, etc . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, I don't think so <3 . . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it's just an idea, some-one said it was important to get ' new ' look, for tutorials, other stuff . . I never thought of that, but it's actually a really good idea . . So, I thought, maybe this could ' also ' help, in that regard <3 Thank you . . .

**Comment by aaronfranke** [comment]
I like the current size.

**Comment by jasperbrooks79** [comment]
As always, see these as ideas for pros to look at, then decide how to well, ' really ' do it . . There's probably a much better way, and it could give the engine a new look, if it said Godot 4, or some-thing, don't know what it should be, any-way I think it could look better, though it's really cool, as well, right now . . . Maybe someone can make a nicer version, of it . . Thx <3

**Comment by mrjustaguy** [comment]
Yeah, I really don't see a need to change something that's perfectly fine as is...

**Comment by Calinou** [comment]
Closing due to lack of support (see the above comments).
