### ISSUE TITLE
quisiera sugerir que los visual scripting y visual shader tengan mas libertad de alejar el zoom 

### ISSUE THREAD

**Issue by matiashak** [godotengine/godot-proposals#261]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**
quisiera sugerir que los visual scripting y visual shader tengan mas libertad de alejar el zoom  ya es funtamental que sea comodo ala hora de programar visualmente y no incomodar al usuario con el zoom estaria bueno para el engine ya que es futurista otra cosa que se deberia de implemetar es un cuadro de comentarios para cuando acercas el puntero del mouse se este mostrando el cuadro de comentarios para identificar los script
![godot](https://user-images.githubusercontent.com/58227174/69744402-62b79900-1140-11ea-8965-166f382b654e.png)

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by matiashak** [comment]
una mejora en programacion visual

**Comment by matiashak** [comment]
thanks

**Comment by Calinou** [comment]
Duplicate of #6.
