### ISSUE TITLE
Allow Novel EditorProperties Made via EditorInspectorPlugins to be Remembered upon Inspector Refresh

### ISSUE THREAD

**Issue by ACB-prgm** [godotengine/godot-proposals#2611]
### Describe the project you are working on
Making a plugin to add a "Keep Pivot Offset Centered" Property that will keep the `rect_pivot_offset` property in the center of a control's rect if toggled.

### Describe the problem or limitation you are having in your project
I cannot find a way to remember the value of the property when the inspector refreshes.  Because it is a new property, it is not included in the object's property list, and thus I cannot get it via `get_edited_object()[get_edited_property()]` and set it via the `update_property()` function.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I don't know how you would implement it, but I would like to have some way of storing the value similar to how normal properties or even export variables are stored.  This way when I add the `EditorProperty` to the inspector, I can somehow pass it the last value if it is different from the default.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I cannot program in C++, so I have no idea.  But maybe there could be a method in `EditorInspectorPlugin` that adds the property to the property list of the object.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I do not think it will be used often, but I can't figure out how to work around this.  Please correct me if I am wrong.

### Is there a reason why this should be core and not an add-on in the asset library?
I think this is beyond that, but I also can't program this myself.
****

**Comment by pycbouh** [comment]
>  I would like to have some way of storing the value similar to how normal properties or even export variables are stored.

"Normal" properties are properties of the object that you edit. You need to add your property to the object first, then create an editor for it. It doesn't work the other way. If you want to add new properties to a built-in class so that it's available by default to every instance of it, then, well, it's not possible currently. You'd have to extend that class and use your extended class instead of the base class wherever you need this.

**Comment by ACB-prgm** [comment]
> See #1167.
> EditorInspectorPlugins don't make properties, they provide controls to edit existing properties.>

Then what is the point of `parse_begin` and `parse_end`? 

> If you want to add new properties to a built-in class so that it's available by default to every instance of it, then, well, it's not possible currently. 

That is exactly what I want to do haha.  So that's unfortunate :(.  Though just extending my own custom class doesn't seem terrible.

**Comment by pycbouh** [comment]
> Then what is the point of `parse_begin` and `parse_end`?

You can use those to show a preview of your object if it's rendered in some form, or you can add buttons that do some actions on that object. Those methods allow you to just add extra controls in the scope of the class, that make sense at the top or at the bottom of the inspector dock.
