### ISSUE TITLE
Dashed or Dotted Line2D

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#2617]
### Describe the project you are working on
Multiple chart/financial systems

### Describe the problem or limitation you are having in your project
I'm unable to draw dashed or dotted lines using the Line2D.

I try to set the texture as a `8x4` tiled pixel, half of which is white. The texture mode is set to `tile`, and I would expect this to work, but it doesn't seem to.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow tiling textures on `LIne2D`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Set the texture as a `8x4` tiled pixel, half of which is white. 
The texture mode is set to `tile`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I believe this should be part of the `Line2D`
You can [create this using code](https://github.com/juddrgledhill/godot-dashed-line) but it's not very performant.

### Is there a reason why this should be core and not an add-on in the asset library?
This should be part of `Line2D`

**Comment by tavurth** [comment]
Edit, never mind I fixed it.

I had to re-import using the following flag:

<img width="474" alt="Screenshot 2021-04-16 at 22 34 36" src="https://user-images.githubusercontent.com/100964/115075561-ee7fc000-9f03-11eb-932a-6a852da49347.png">

Might be nice to have this in the documentation though.

**Comment by Calinou** [comment]
> Might be nice to have this in the documentation though.

This is already documented in the class reference: https://github.com/godotengine/godot/blob/49511d439124ab5a71defd22639737f45bd0ff70/doc/classes/Line2D.xml#L134
