### ISSUE TITLE
Make strings in arrays and dictionaries more obvious when printing

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#2623]
### Describe the project you are working on

I was working on  https://github.com/godotengine/godot/pull/41571 and encountered this thinking it was a different bug (invalid array with size 0 but says "1")

### Describe the problem or limitation you are having in your project

Empty arrays are indistinguishable from arrays with a single empty string

```py
# Current behavior
print([])              # []
print([""])            # []
print(["a", "b", "c"]) # [a, b, c]
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We should either put quote marks around these elements (that are strings) or specify when they are empty

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Strings in arrays and dictionaries should be wrapped in quotes to avoid ambiguity (See: https://github.com/godotengine/godot-proposals/issues/2623#issuecomment-1112774509):

```py
print([])              # []
print([""])            # [""]
print(["a", "b", "c"]) # ["a", "b", "c"]
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This will be used often

### Is there a reason why this should be core and not an add-on in the asset library?

Arrays are part of core

**Comment by Calinou** [comment]
Doesn't https://github.com/godotengine/godot/pull/34668 fix this?

**Comment by nathanfranke** [comment]
> Doesn't [godotengine/godot#34668](https://github.com/godotengine/godot/pull/34668) fix this?
> 
> Other than that, I agree that strings within arrays and dictionaries should always be printed with quotes. We'll have to escape double quotes within the strings though.

What part of that PR resolves this? From what I can see there is no changes to the array printing or string's to_string.

**Comment by nathanfranke** [comment]
This was discussed briefly in a PR Meeting. I thought it would be a good idea to implement a CSV-style encoding which checks if the string contains a comma. We could add another check for empty strings.

```py
var arr = ["hell, o", "world"]

# First
print(arr)  # [hell, o, world]
# Second
print(arr)  # ["hell, o", world]
```

**Comment by Calinou** [comment]
> This was discussed briefly in a PR Meeting. I thought it would be a good idea to implement a CSV-style encoding which checks if the string contains a comma. We could add another check for empty strings.

If quotes are to be added only when there's ambiguity, this should also be done for strings that look like integers or floats.
