### ISSUE TITLE
Remove `Engine.editor_hint` in favor of `Engine.is_editor_hint()`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2625]
### Describe the project you are working on
plugins

### Describe the problem or limitation you are having in your project
Having a property means you can get and set its value.
I see no case when setting `Engine.editor_hint` from a script would be useful.

The problem is that it can confuse users, making it possible to shoot himself in the foot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Depreciating `Engine.editor_hint` property and removing it from API would solve the problem.
One would use `is_editor_hint()` instead.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
1. Depreciate `Engine.editor_hint` property in favor of `is_editor_hint()` method;
2. Remove `editor_hint` property from API. The user should not access to it.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
- One could just use `is_editor_hint()` and not `editor_hint`.
- Documentation could make it clear that setting `editor_hint` is pointless.

But this would not completely solve the problem.

### Is there a reason why this should be core and not an add-on in the asset library?
This is core API.

**Comment by pycbouh** [comment]
It seems that read-only properties (i.e. properties exposed with only a getter) are frowned upon some of the core devs, but there doesn't seem to be a consensus. I can see a point in making them all accessible only via getters, not via properties. It would be more consistent and less confusing.
