### ISSUE TITLE
Expose shadow quality threshold distance

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#2629]
### Describe the project you are working on
3D scenes
Trying to help out community members with the look of their project

### Describe the problem or limitation you are having in your project
As I was trying to help NeZvers to [improve the looks of his car project](https://www.reddit.com/r/godot/comments/muw9w6/help_to_make_a_lowpoly_mobilefriendly_visual_setup/), I could not help but get annoyed by this apparent disruption in the shadow. This almost looks like a tearing issue in full screen:

https://user-images.githubusercontent.com/47016402/115499472-c7aceb00-a26f-11eb-96a9-b80fd1e9b21e.mp4

It reminded me having seen this many times before, not only in my projects, but also in other community members projects and demos (for instance in [Arnklit's WaterWays Demo](https://github.com/Arnklit/WaterwaysDemo)),

It seems to be a threshold distance after which Godot uses a lesser quality shadow quality. Right now there seems to be no way to adjust the distance where this threshold should occur or if it should occur at all. The only workaround I found is by adjusting the far and near plane of the camera. However this seems very counter intuitive: While reducing the far plane will bring the threshold distance closer to the camera (expected), increasing the far plane beyond the default value of 100 will not bring this threshold distance any further away from the camera (unexpected). Instead increasing the near plane (but only slightly, 4-6 worked well in this scene) will push this threshold distance out of camera frustum. (very counter intuitive)
Imho this should have nothing to do with near and far planes. Those are meant for clipping. It took me ages to figure out how to adjust this at all because I would have never considered looking at the near and far planes. And even when I did (increasing the far plane), nothing changed.

Because this behaviour is so weird and counter intuitive, and imho should not be adjusted with the near and far plane settings at all in the first place, I was not sure if this should not be reported as bug. But I guess this proposal would be an enhancement, so there you go ...

[Here is a zip with the project](https://github.com/golddotasksquestions/zipdump/raw/master/nezvers_LowPolyMobileTemplate.zip) (made by NeZvers, plus some visual improvements by me), if anyone wants to play around with the near and far planes to see the effect. (It's much easier to see fullscreen and without video compression)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Expose a separate setting for this feature and remove it's current counter intuitive and hard to adjust correlation with the camera near and far planes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
a property like "shadow_quality_threshold_distance" expecting a float value. I don't know the details of how this feature currently works, so it's hard for me to make a recommendation.

The next step would be to give it a reasonable default setting, one that won't make it appear right in the middle of a simple almost empty scene. Meaning if a beginner creates their first scene, they should not be confronted with something that looks like a bug or some rendering issue.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I tried to find anything in the docs and project settings, but could not find anything.

### Is there a reason why this should be core and not an add-on in the asset library?
It's about an already existing feature that makes Godot look bad because it looks like a visual bug on first glance, strikes through the middle of a scene and the only way to adjust it is through setting that are responsible for something else entirely.

**Comment by Bauxitedev** [comment]
This threshold is already exposed in DirectionalLight. It's called Split 1, 2, and 3. The higher the number, the further away from the camera the shadow quality transition happens.
![image](https://user-images.githubusercontent.com/31383123/115552246-65261000-a2ac-11eb-96f6-18d8f6272043.png)
You can also enable "Blend Splits" to smooth the transition between the different shadow resolutions.

**Comment by Zireael07** [comment]
@Bauxitedev: I am not sure if the project uses 4 Splits... and it's relative to some max_distance... also what about split 3 to split 4? I can't see this...

**Comment by golddotasksquestions** [comment]
@Bauxitedev Thank you! How I could have missed this, I don't know. I thought I spend at least an hour with each and every setting in the Inspector and Project settings. I supposed it must have been collapsed and escaped my attention that there is another range of properties I have not looked at yet.

Having played around with it for a while now, I still am puzzled about how counter intuitive it behaves, especially with the near and far plane of the camera.
Again, Godot's UI does nothing to help you understand what is going on. I will close this issue now regardless, as the initial intent of this proposal is already fulfilled. 
Thank you again for commenting!

**Comment by Calinou** [comment]
> You can also enable "Blend Splits" to smooth the transition between the different shadow resolutions.

Remember that Blend Splits has a cost and is not supported in GLES2. You'll want to disable it on low-end hardware.

**Comment by golddotasksquestions** [comment]
I really can't wait for 4.0 shadows to arrive soon enough. Which ever setting combination I try, Godot3.X shadows always look like dogpoop.

**Comment by Calinou** [comment]
If you really don't want splits to be visible, you can set the shadow mode to **Orthogonal** (which is also the fastest). This mode has the lowest overall quality, but you may be able to set the directional shadow size to 8192 in the Project Settings to compensate. (Doing so will likely neuter the performance improvements gained from switching to PSSM to orthogonal, though.)
