### ISSUE TITLE
Support for external and builtin script editor at the same time

### ISSUE THREAD

**Issue by irfan-hossain-bhuiyan** [godotengine/godot-proposals#2630]
### Describe the project you are working on
It is a script heavy project.
### Describe the problem or limitation you are having in your project
I can't use external script editor(vscode) and godot builtin script editor at the same time.
Godot built in text editor is highly intregrated with godot,There are some functionality that only support with the builtin editor,it is also less bug prone,but a lot of time external text editor is needed(like for git intregation).But I can't use both at the same time.I have to enable and disable the external text editor support in editor menu
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Right clicking any script in the project
There will be two option to open in external text editor or builtin editor.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
Probably not.
### Is there a reason why this should be core and not an add-on in the asset library?
It is a editor feature,I am not sure if an addon is possible.

**Comment by irfan-hossain-bhuiyan** [comment]
Will the intergation will work same as before for with external editor turned on like "smart autocompletion"

**Comment by KoBeWi** [comment]
Well, it's a bug. It was alreasy reported and doesn't affect the project in any way.
