### ISSUE TITLE
Docs: Describe GDScript in a bnf grammar

### ISSUE THREAD

**Issue by Joakker** [godotengine/godot-proposals#2639]
### Describe the project you are working on

A treesitter parser for GDScript 2.0.

### Describe the problem or limitation you are having in your project

The latest nightly release of the documentation describes GDScript 2.0 through examples and use cases. This is fine for new users and people who want to refresh their knowledge, but for people who want to write tools for working *with* GDScript (linters, formatters, parsers, the works), they'd have to pick apart and distill these examples into a bnf grammar they can build their program upon.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

[Backus-Naur Form](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) is a way of formally describing languages in terms of terminals and the rules that group them together. It has this form:

```
for_statement         →  'for' ID 'in' expr ':' suite
suite                 →  statement | '\n' statement+
expr                  →  ...
ID                    →  [a-zA-Z][a-zA-Z0-9]*
...
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A new page could be created, called `Formal Grammar` in the `Scripting/GDScript` section of the docs.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

It would help developers working on tools for GDScript, and help formalize and document new changes in the laguage.

**Comment by pycbouh** [comment]
I think we don't have any formal grammar description for GDScript even internally, but there was a community project that basically reversed engineered it. vnen even used it for his GDScript 2.0 rewrite, if I'm not mistaken.

**Comment by Calinou** [comment]
This is already documented here for GDScript 2.0: https://docs.godotengine.org/en/latest/development/file_formats/gdscript_grammar.html

**Comment by Joakker** [comment]
Oh, my bad. Thanks! 😃
