### ISSUE TITLE
Add a "Centered" toggle on Control Nodes (Mainly Texture Control Nodes)

### ISSUE THREAD

**Issue by Nefalox** [godotengine/godot-proposals#2642]
### Describe the project you are working on
a roguelite rpg, currently working with main menu/settings

### Describe the problem or limitation you are having in your project
centering control nodes offset or textures is a hassle and a work around of this is by using a node2d sprite which has a "centered" bool toggle but it can be a bit bad to work with especially when you want to control margins or anchors and stuff

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
add a "centered" bool toggle to control nodes just like the one in node2d sprite as it helps centering control nodes offset less of a pain in the back

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![image](https://user-images.githubusercontent.com/68357120/115959743-c5bc8380-a51e-11eb-9735-1192bebe6969.png)
just like this but for control (texture) nodes

### If this enhancement will not be used often, can it be worked around with a few lines of script?
i mean, maybe, but it would be much easier if it was just a simple button

### Is there a reason why this should be core and not an add-on in the asset library?
because for it's scope it doesn't have to be an entire add-on as it's just one button on the inspector

**Comment by pycbouh** [comment]
I'm not entirely sure what exactly you want to achieve and why it's a pain for you. Can you show an example of the outcome you want, not the option you think you need?

**Comment by Nefalox** [comment]
i

**Comment by Nefalox** [comment]
![image](https://user-images.githubusercontent.com/68357120/115963702-9cf1b980-a531-11eb-8add-2f928dee7a35.png)
i think this is now unecessary as i just found out that this exists 😓😓
