### ISSUE TITLE
GradientTexture: Add a option to generate HDR (raw) 32-Bit colors

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot-proposals#2655]
### Describe the project you are working on
Experimenting some shader effects

### Describe the problem or limitation you are having in your project
I have a explosion effect with a gradient that defines it's color, and I want that the explosion starts with a bright white, so it can show as glow in post processing. But GradientTexture don't generate the texture with floating-point colors, which results in a limitation from 0-255 for each color channel and don't give a HDR color as output.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The feature is a option to enable floating-point 32-Bit colors in the GradientTexture, enabling colors beyond the 0-255 range, this could be a option to save resources and just enable it when necessary.
It could be called something like `generate_raw` or `generate_hdr` to match the option for raw color option.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
The only change needed in the source code is change this line: 
https://github.com/godotengine/godot/blob/639b02f4541be289a10f2e7bc80fd1ea67e4cf32/scene/resources/texture.cpp#L1764
With a conditional that checks the boolean to switch between `Image::FORMAT_RF` and `Image::FORMAT_RGBA8` when updating the texture.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't think that this is possible because you can't override the GradientTexture's `_update` function because it is private.

### Is there a reason why this should be core and not an add-on in the asset library?
Because it enhances the overall editor user experience.

**Comment by Calinou** [comment]
As far as I know, HDR textures in Godot are 16bpc, not 32bpc.

**Comment by Calinou** [comment]
For the GradientTexture resource, this could be exposed as an `hdr` property.
