### ISSUE TITLE
Copy-pasting nodes between scenes (and projects)

### ISSUE THREAD

**Issue by lumenwrites** [godotengine/godot-proposals#2659]
### Describe the project you are working on

This applies to most of the projects I'm working on, especially the ones where I want to reuse assets from old projects.

### Describe the problem or limitation you are having in your project

Currently it's inconvenient to copy nodes between different scenes or projects. If I want to import a node from another project, I have to "Save Branch As Scene", use the file manager to copy-paste the node into a different project folder, import it into the scene I want it to be in, and then right click > "Make Local". If you have to do this often enough, that gets tiresome very quickly.

And since I tend to reuse the assets from my old projects, this comes up quite often. I think there must be an easier way.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Press Ctrl-C when the node is selected, it copies the node. Press Ctrl-V in another scene (or another project), and it pastes the node into the scene.

### Is there a reason why this should be core and not an add-on in the asset library?

It's an enhancement to the core UX and usability of Godot.

**Comment by pycbouh** [comment]
This was already implemented in 3.3:
https://godotengine.org/article/godot-3-3-has-arrived#node-copypaste

**Comment by KoBeWi** [comment]
Except copy-pasting between projects. The PR that implemented it was rejected: https://github.com/godotengine/godot/pull/31616 and it's unlikely Godot will have this feature in core. Save Branch as Scene is sufficient though.
