### ISSUE TITLE
Rework the inverse kinematics workflow to allow for improvements

### ISSUE THREAD

**Issue by PranavSK** [godotengine/godot-proposals#2660]

**Comment by Calinou** [comment]
Did you forget to fill in the template? If the template is not filled, this proposal will be closed.

By the way, IK is already being reworked for 4.0 in https://github.com/godotengine/godot/pull/39353 https://github.com/godotengine/godot/pull/40347. You may want to check those pull requests' descriptions and see if they address your needs.

**Comment by PranavSK** [comment]
Ahh sorry, this was accidental. You can close this. The idea I had was to implement each bone as a spatial node and add constraints as child nodes. This would allow for constraints to work with any Node3D/Node2D and the Bone3D node would only need to update its transform from the skeleton bone (similar to current BoneAttachment or apply its transform to the bone. 

But the approach which is currently pursued seems to be quite different and anyway, this can also be thought of after the groundwork for the above is done.
