### ISSUE TITLE
Add to support ping-pong loop in AnimationPlayer and playing backwards and ping-pong loop in NodeAnimation of AnimationTree

### ISSUE THREAD

**Issue by jtakakura** [godotengine/godot-proposals#2664]
### Describe the project you are working on
A 2D and 3D platformer project.

### Describe the problem or limitation you are having in your project.
I would like to have the feature to play the ping-pong loop in AnimationPlayer and NodeAnimation of AnimationTree.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Currently, we need to set loop-back keyframes of animation by hand.
This feature can be eliminated in such complicated animation settings.

![current](https://user-images.githubusercontent.com/640587/116489951-235f2000-a8d1-11eb-9ea1-5f168584ee8f.png)
In the above case, we need to set 10 keyframes from 0.55 sec to actualize the ping-pong loop animation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Mockup :
![pingpong](https://user-images.githubusercontent.com/640587/116488435-58697380-a8cd-11eb-903e-611b2cd08c99.png)

Add animation loop selectable button like loop wrap mode in the track setting.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
it could be done by hand but isn't as clean of a solution as it would be required for every ping-pong animations.

### Is there a reason why this should be core and not an add-on in the asset library?
This seems like a feature that should be standard and everyone would use.

**Comment by Seubmarine** [comment]
The Animation player does have a [play_backward](https://docs.godotengine.org/fr/stable/classes/class_animationplayer.html#class-animationplayer-method-play-backwards) function, but yeah it would be great to have it inside the editor has an option.

**Comment by TokageItLab** [comment]
The AnimationPlayer has a play_backward function, but certainly the NodeAnimation in the AnimationTree does not have a play_backward function. Also, like the [PR](https://github.com/godotengine/godot/pull/41728) I posted before, Godot 3.x does not allow Timescale to be negative. So, I favor this proposal expands on the PR.

**Comment by TokageItLab** [comment]
It has been re-implemented by https://github.com/godotengine/godot/pull/53819
