### ISSUE TITLE
Allow define Default Clear Color to zero

### ISSUE THREAD

**Issue by junkajii** [godotengine/godot-proposals#2667]
### Describe the project you are working on
Little 2D game, works in windowed mode

### Describe the problem or limitation you are having in your project
My final design have rounded corners for the window, I can not do this in Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Godot have a set for the main background in Project Settings > Rendering > Environment > Default Clear Color.
But setting alpha to 0 not work, the color remains.
Just allow to set Default Clear Color alpha to zero.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
My idea is use Borderless and Default Clear Color alpha zero, to get my final look. (like a app with rounded borders)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I think not, i tryed by code is the same alpha can't by removed
`VisualServer.set_default_clear_color(Color(255,0,0,0))` i get red background
### Is there a reason why this should be core and not an add-on in the asset library?
Yes

**Comment by bruvzg** [comment]
> My final design have rounded corners for the window, I can not do this in Godot.

If you want parts of the window to be transparent, set `display/window/per_pixel_transparency/allowed` and `display/window/per_pixel_transparency/enabled` properties in the project settings and add `get_tree().get_root().set_transparent_background(true)` call to the `func _ready():` to disable default color rendering.

**Comment by junkajii** [comment]
@bruvzg thank you!
