### ISSUE TITLE
Show the transform operation numbers in 2D

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#267]
**Describe the project you are working on:**
2D game.

**Describe the problem or limitation you are having in your project:**
The new ruler tool is very useful, but only when measuring distance. When it comes to moving objects, you still don't know how much you are moving them, which makes precise transformations difficult.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
In 3D editor, when you move/rotate/scale something, you get an information about how much it is moved/rotated/scaled. It would be extremely useful to have this in 2D too. I would know precisely how much I move things instead of relying on intuition.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![y41i88GVlD](https://user-images.githubusercontent.com/2223172/69872242-2ce7f100-12b5-11ea-9d65-99d8074baa63.gif)
(imagine this is 2D)

**Describe implementation detail for your proposal (in code), if possible:**
Probably porting code from 3D editor to 2D, with some changes like less dimensions etc.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This requires a plugin.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Having this only in asset library would be a joke.

**Comment by YuriSizov** [comment]
Approving on the account @KoBeWi is still interested in implementing it, and it seems to be a relatively small and easy change that can be handy.
