### ISSUE TITLE
Make `SceneTree.call_group()` call methods immediately instead of using deferred calls

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2671]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

People are sometimes confused by `call_group()` performing deferred calls by default: https://github.com/godotengine/godot/issues/36100

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use immediate (real-time) calls instead of deferred calls when using `SceneTree.call_group()` and `SceneTree.call_group_flags()` with the default flags.

**Advantages:**

- Less confusion for beginners and experienced users alike – things behave in a more "obvious" way.

**Disadvantages:**

- More risk of stutter/temporary freezing due to slow methods being called in lots of objects at once, with no possibility for the engine to delay things.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- Make `SceneTree.call_group()` call methods immediately instead of using deferred calls.
- Remove the `GROUP_CALL_REALTIME` flag in favor of a new `GROUP_CALL_DEFERRED` flag. This new `GROUP_CALL_DEFERRED` flag makes it possible to have the previous behavior when using `SceneTree.call_group_flags()`.

Since this breaks backwards compatibility, this should be considered for 4.0.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as this is core engine functionality.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core engine functionality.

**Comment by RandomShaper** [comment]
I fully support this.

When I started learning Godot I was a bit confused by that. Also, it would be consistent with the default behavior of signals.
