### ISSUE TITLE
Improve the look / visual presentation of the icons ( in editor ) . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2672]
### Describe the project you are working on
A Tomb raider type game . .

### Describe the problem or limitation you are having in your project
This is not a problem, with the project, but a very basic, sort of question . . The icons in Godot look a bit ' simple ', and I was wondering if perhaps they could look a bit more, well ' classic ', here I mean other open source software . . . Now, I have no idea what these even should be, so this is like early-early brain-storming, nothing clear, or even well, ' ready ', or so . . <3

<img width="738" alt="Skærmbillede (169)" src="https://user-images.githubusercontent.com/83387915/116633093-e3dc1680-a958-11eb-8b05-d4e8d3c78b28.png">

Now, these are quite nice, and I understand they have a retro - game art ' look ', and I'm quite fond of them, also . . At the same time, I makes me ' wonder ', is this an engine, for a ' serious ' project or, ' content ' . . Notice many open source software, doesn't mean they're right, have a more ' general ' icon set-up, appealing to both young, and old users, the entire use - base . .

Blender icons . .

<img width="779" alt="2021-04-30 0210" src="https://user-images.githubusercontent.com/83387915/116633325-7da3c380-a959-11eb-8868-1427cd471de0.png">

Also, note openOffice, has a more well, appeals to all ages icon line . .

<img width="697" alt="2021-04-30 0213" src="https://user-images.githubusercontent.com/83387915/116633411-b04dbc00-a959-11eb-8f9d-1bfc0aaab2bd.png">

Now, I don't like the open Office ones, for Godot . . but, my proposal is that you consider making a slightly more ' universal ' icon design, that appeals to young and, old . . Right now, it also gives the impression, not sure, the engine is really made, for young users, mainly :OO . . However, making a bunch of new icons, would be a ton, of work, so I know it's not just ' here - and - now ' stuff <3 Also, this is more like ' early ' ideas, nothing specific . . imo, one could even have several icon packs, that could be downloaded, as a plug-in, not sure . . .

It'd give the engine an ' appeals to all ' look or, vibe . . and, make people wanting to make more serious ' titles ', well, feel confident the engine was the right choice . . I think Blender has a nice starting - point but, it could be better . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, it'd just make it feel, that a small team, or serious, mid - level studio would ' think ', this engine is sort of, ' good ', or robust, or so . . . Right now, it has a look like it belongs in school, pre-college, pre-high school, or so . . That's not bad, but it can be a bit ' worrying ', if the engine can handle a bigger, more ' complex ', or so on title . . Just, a very simple proposal, no idea if this is necessary, or even easy, and what would make the engine look like, very young users, serious mid - level game studios, even old users, maybe over 50, with a ton of game - dev experience, would sort of think, this is ' nice ', makes sense :OO <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, here are icons, from another open source program ( called, mypaint, basically Krita, but easier to user, atm . . <3 ) . . . .

<img width="682" alt="Skærmbillede (182)" src="https://user-images.githubusercontent.com/83387915/116633981-2d2d6580-a95b-11eb-9c72-8632c6d23c59.png">

Well, I think it would be ' nice ', to have some icons, and ' editor ' look, that doesn't sort of, scare mature, ' serious ', sort of adult, grown-up people away, from the engine . . . I certainly think, is this engine made for kid's stuff ONLY, when I look at the icons, and wonder, will the rest of the engine be ' lagging ' or, even not optimized, or more . . .

It's a ton of work, though, but one could start with the most commonly seen icons, not sure . . . last, with newer monitors, one could have bigger icons, or more detailed, on a 4K monitor, or even, not sure, 8K . . So, might be a good idea, to make the icons scalable, ie. they look ' good ', even if scaled up, a bit . . it'd mean it have to be ' pro ' icons, lots of work, and also, designing it would be a massive challenge, and more . .

Right now, I look at the icons and think, is this like a program, for teens, or kids, mostly . . That's an important class, of users, but the main group of people that can make games, are actually coders, sometimes after university, or with some education, though they're not the only user group . . . Point is, I think the engine could look a bit more ' universal ', or ' standard ', or so . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't do this, sigh, I always get this wrong, I don't think so <3 <3

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it could be a plug-in, to begin with, so people could just try it, give feed-back, so on . . Not, sure <3

Biggest problem is, it's semi - concerning to see such an icon set - up, as a more serious dev, one 'WONDERS', can this engine handle advanced or, even ' complex ' titles, or just ' content ', like assets, that stuff . . . I think it could be a bit more ' inclusive ', and appeal to both new users, with zero experience, and old users, maybe even former industry workers, that are looking to pursue interest, or more . . .

Also, I don't think young kids are ' smart ' enough, to code an advanced controller, on their own, I'm not sure, at least young kids, teens, aren't the only group, some people actually have a lot of education, or more . . Well, it's an idea, not sure . . . .

**Comment by charlesmlamb** [comment]
Last, the stuff one can do in Godot, is some-times very high-level, and many of the terms, even in particles, isn't really only, for a young user - base . . stuff, like angular velocity, so on . .

And, as an adult user, I well, mildly freak out, and ' worry ' that, the engine can't handle a ' tough ' project . . Proposal is, make a 'timeless', more universal look, note that a Ph. D., in say math, or physics, could do almost professional work, in the engine, due to it's complexity, also C#, even native is supported, so the engine itself, isn't made for a teen or, younger audience, ONLY . .

That's why I think the engine could use a more ' pro ' look, without going into ' commercial ', etc <3

**Comment by charlesmlamb** [comment]
So, you know I believe it's VERY serious when making stuff for kids, that they don't get 'hurt' or, worried . .

It's a job for the best, of the ' very ' best, not noobs or, wanna-bees . . . <3

**Comment by charlesmlamb** [comment]
Last, there may-be should be a rule, that users below 15, 16, even 17 should not be allowed, to use the engine . .

And, when some kid shows up, younger than that, and want to use the engine, be ' famous ' or, well . . I smell trouble, or so . . 

Just saying, it's semi - irresponsible, ' un - noble ', even perverted <3 Not, sure . . .

Some thoughts, think most adults get this, media is not ' really ' for kids, at all . . .

Thanks <3 <3 . . . .

And, break . . . .

**Comment by charlesmlamb** [comment]
Last, it's semi - also a problem, for the ' tutorial ' community, bec. if you make stuff, so that a kid can start using the engine, ' trouble ' or, drama . . .

Well, the engine is run by amazing people, that in no way wants this, it could even lead to ' authorities ' shutting down the engine or, even jail <3

Not, ' wise ' . . .

And, ' illegal ', theoretically, ' spiritually ' . . . 

Break . . . .

**Comment by SIsilicon** [comment]
I honestly don't see any reason why the icons should be changed. When I first used Godot, I never had any confusion concerning those icons. Each one clearly showed what they were representing. Sorry if I sound rude, but this proposal is based solely on opinion with no sensible points to back it up.

**Comment by charlesmlamb** [comment]
Well, I might be wrong, happens often . . .

<3 . .

**Comment by Xrayez** [comment]
> one could even have several icon packs, that could be downloaded, as a plug-in, not sure . . .

Sounds like a good idea to me here, likely it's not currently possible to override editor icons in the editor... Icon data is generated dynamically from in-memory SVG documents, so not sure how easy or difficult it would be to implement. But perhaps you'd want to have an editor setting for a directory path containing a list of custom icons just like in https://github.com/godotengine/godot/tree/master/editor/icons to be able to override each one of them.

**Comment by pycbouh** [comment]
> Sounds like a good idea to me here, likely it's not currently possible to override editor icons in the editor...

That depends. For the UI all icons csn be overridden using themes. You can override the editor's theme in settings with a regular Theme resource, which contains new icon items.

But you likely can't override node and type icons as those are fetched via means other than Theme (even though all of them are in the theme as well).

**Comment by a3p169** [comment]
In my opinion, there's no need to change editor icons. Look and feel can be changed easily with theme. Theme can override all icons except for nodes icons. I do feel that nodes need more streamlined symbolic improvement. Having different colors doesn't always match the contrast level that an icon should have with certain bright or dark colors. This can be fixed by exposing node icons to theme resource and let users get creative with it. This will limit the developer's work from creating new set of icons for light and dark versions to only exposing the icons to theme and keep the defaults.

**Comment by a3p169** [comment]
I had been thinking about how community can help with such things. There are really good artists and programmers in Godot community that could help with this. IF theme resource can be exposed to all the GUI elements then we could just host simple competitions where winner's icons, theme gets to be included in Godot's default theme or gets included in the list of themes. Just sayin tha's all.

**Comment by charlesmlamb** [comment]
I'm super - excited for Godot 4, after seeing a few other proposals, I think most of what I'd ever hoped for is in Godot 4, almost 100 % . .

Didn't know Godot 4 was getting a new theme, I'm about as happy as I can be, atm . .

I simply think, Godot could get a more 'mature' look, bec. the engine is quite complex, anyway I'd like a more mature look, so I'm not so worried, program will 'crash' if I make a longer, more ' advanced ' game or, so on . . .

Thanks . . .

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on the first post).
