### ISSUE TITLE
Add built-in monetization and authentication plugins for mobile platforms

### ISSUE THREAD

**Issue by titangamingglt** [godotengine/godot-proposals#2676]
### Describe the project you are working on
I have been working on a project. It is a Boss based endless runner game developed for android. It has several enemies, powerups, online leaderboard systems and many more.
### Describe the problem or limitation you are having in your project
So in my project i use third party add ons for monetization and for online leaderboard which were developed by some awesome devs. issue with this is as Godot is constantly evolving , so after each updates the addons/plugins got obsolete unless the people who make those update it.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
As an android developer I think Monetization and a Authentication/storage system (like Firebase) are very essential component. If Godot has their own plugins or node for this it will be very beneficial for developers like us.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I think a built in node for monetization and online storage/authentication (i.e: Firebase) will do the trick.
### Is there a reason why this should be core and not an add-on in the asset library?
Being an add-on in assets library again brings the problem of the addons not being updated as Godot. So we have to wait for the plugin developer to update the add ons before we can update the engine itself.

**Comment by Calinou** [comment]
This cannot be done because "monetization" SDKs are often proprietary, and Godot cannot integrate proprietary software in its core.

**Comment by titangamingglt** [comment]
Is it possible for Godot having their own monetization system. Which will both benefit the developer and the Godot itself.

**Comment by Calinou** [comment]
> Is it possible for Godot having their own monetization system. Which will both benefit the developer and the Godot itself.

No, as Godot is managed by a nonprofit fundation (the Software Freedom Conservancy).

**Comment by SirLich** [comment]
The FAQ has some good information on this subject:  [Why doesn't godot integrate closed-source SDKs?](https://docs.godotengine.org/en/stable/about/faq.html?#will-insert-closed-sdk-such-as-fmod-gameworks-etc-be-supported-in-godot)

**Comment by Calinou** [comment]
Closing, as this will not be developed as an official effort per the [FAQ](https://docs.godotengine.org/en/latest/about/faq.html#will-insert-closed-sdk-such-as-fmod-gameworks-etc-be-supported-in-godot).
