### ISSUE TITLE
Allow positioning GraphNode ports or remove the need of children completely.

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#2679]
### Describe the project you are working on

A GraphEdit based behavior tree.

### Describe the problem or limitation you are having in your project

Often times when working with GraphNodes, the port-child relationship gets in the way. It's nearly impossible to position ports consistently if you don't just have a lot of Control nodes with the same height, like in this case:

![blender shader node](https://docs.blender.org/manual/en/latest/_images/render_shader-nodes_shader_glass_node.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Either `GraphNode.set_port` should have an optional `height` parameter, or make the positioning depend on a Theme constant that sets the separation between ports.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
set_slot(idx: int, enable_left: bool, type_left: int, color_left: Color, enable_right: bool,
    type_right: int, color_right: Color, custom_left: Texture = null,
    custom_right: Texture = null, height = -1)
# or a theme property:
# int port_separation [default: 20]  Separation between the ports
```

Personally, I'm more for the theme property because the `set_slot` signature is way too long already.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

A plugin would be more of a workaround instead of addressing the actual issue.

**Comment by pycbouh** [comment]
I'm not sure I understand the limitation you're facing. What you show on your screenshot from Blender is currently possible to achieve, and yes, you need to make sure those 4 bottom controls have the same height. Can you show more of what happens in Godot and what you want to happen in Godot but can't?

**Comment by Jummit** [comment]
> What you show on your screenshot from Blender is currently possible to achieve, and yes, you need to make sure those 4 bottom controls have the same height.

That's my point; the example is the optimal case where the child/port correlation make sense. In other cases it becomes a restriction:

![image](https://user-images.githubusercontent.com/28286961/116780343-68738580-aa7c-11eb-8917-34e9850e5533.png)

This is nearly impossible to replicate currently, you need to create dummy nodes to add the ports and manually position the `PanelContainer`.

**Comment by pycbouh** [comment]
@Jummit I see. A duplicate of #2212 then?

**Comment by Jummit** [comment]
> @Jummit I see. A duplicate of #2212 then?

Correct. I need to get better at searching before I open proposals. I'll add my solution and the images showing the problem to the linked issue.
