### ISSUE TITLE
make angle_to have an option to not choose the minimum angle

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#268]
**Describe the project you are working on:**
3D space sim.
**Describe the problem or limitation you are having in your project:**
`Vector3.angle_to` only returning the minimum angle makes it hard to get the player to always be standing up on a planets surface.
**Describe how this feature / enhancement will help you overcome this problem or limitation:**
I could rotate the player on the x and z axis by amounts I get from angle_to so his feet are on the ground.
**Describe implementation detail for your proposal (in code), if possible:**
Change the angle_to function of Vector3. This is probably hard. Old code:
```cpp
Math::atan2(cross(p_b).length(), dot(p_b));
```
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.
**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a good feature to have in Vector3.

**Comment by aaronfranke** [comment]
Have you considered using quaternions instead? It's best to not use angles with multiple rotations in 3D.

**Comment by Jummit** [comment]
Since I found another way to solve this problem, I think the answer to "can it be worked around with a few lines of script?" is true. Closing.
