### ISSUE TITLE
GUI, VirtualShader section UI

### ISSUE THREAD

**Issue by ALipAkrohk** [godotengine/godot-proposals#2684]
### Describe the project you are working on
A third person shooter project with MMORPG game mode.

### Describe the problem or limitation you are having in your project
Complexity in the VirtualShader section UI

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Using a separate section for material design, something like the shade design environment in Blender or Unreal Engine software

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
The Visual Shader section gets very crowded I do not know how to display it so I am just sending you a photo.
![image](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F13393087%2F88777663-c25ebc00-d187-11ea-8cd4-f6acb034f2fc.png&f=1&nofb=1)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
There is a need to modify the GUI in Godot, so the answer to this question is no.

### Is there a reason why this should be core and not an add-on in the asset library?
this is a request for godot's development team to refine godot's user interface to be more user friendly and easier to use, godot's an amazing tool for creating games of all sorts but something that I often find annoying is its user interface ESPECIALLY when it comes down to nodes.
everyone should know what i'm talking about . if you've ever tried to do something in godot through nodes (by nodes i mean visual scripting/visual shaders and animationtrees) i'm pretty sure you have come to notice that something about the interface is just wrong. it makes the engine look so unprofessional . 
not only the zooming in and out method is so inconvenient i often find myself struggling with connecting nodes to another. if you zoom out just a little bit you'll notice that you can't really connect nodes together anymore.. godot is such a capable engine with a bright future infront of it and for that reason i find this 
which to some of you might come as a minor issue , unfitting . personally i think godot can really benefit from a ui refinement. not having a good looking, fitting UI that's  convenient to use and easy to the eyes can really scare people away and that's not to be overlooked for a project like godot which's mostly driven by it's community . i don't know maybe hire a freelancer to redesign some of the icons to meet today's modern standards? or maybe just tweak the code a bit to make the whole node-based system smoother to use? like really connecting material nodes from just a tiny bit zoomed out view is almost a challenge on its own
.an example for this is the projcet 'material maker' which has been made using godot. it shares the same interface when it comes down to navigating through nodes and i think a lot of people can agree that while it's a flexible and capable tool and can be used to make some high quality materials, it does suffer from bad ui .thanks for reading through .

**Comment by pycbouh** [comment]
See also https://github.com/godotengine/godot/pull/45165.

**Comment by ALipAkrohk** [comment]
> See also [godotengine/godot#45165](https://github.com/godotengine/godot/pull/45165).
Please read the full text I wrote.
The entire NodeـTree section should be fully updated.
The link you sent is for the Shader Script section, the problem I'm talking about goes back to Visual Shader.

**Comment by pycbouh** [comment]
@ALipAkrohk I'm sorry, if I've misunderstood your proposal, but it's very hard to figure out from your text what exactly you are proposing. I can see some frustration and general suggestions like "it needs a more professional UI" and "hire a designer", but very little in terms of actual ideas on what to change and how.

One thing I took from your message was that you find current editor inconvenient, too crowded. Which is why I've linked to an old PR that suggested a dedicated shader editor with a preview for the material that is being edited. In my opinion, this is how the issue you've described can be solved. This is how they solve it in Blender too, by creating a workspace with a node editor and a 3d view for your object with the material that you edit. It doesn't matter that the PR talks mostly about the shaders written with code, the same approach can be applied to the visual shaders too.

Other than that, you've listed a lot of pains, but very little detail about them and about how they can be improved. I feel like many of them deserve their own fully thought-through proposals.

**Comment by paddy-exe** [comment]
From what I can understand @ALipAkrohk comments is / what my proposal would be: 
1. Refinement of the node connections when zoomed out (it's extremely hard/impossible to connect the nodes when you zoom out of 1x)
2. Visual Shader Groups just like in Unity/UE would help a lot with the clutter and organization

**Comment by pycbouh** [comment]
@paddy-exe 1) is a bug and was addressed in 3.3 (and OP is using 3.2.3), and 2) has its own proposal and PR in the making (it was a part of GSoC 2020, I think, but it wasn't finalized yet).

**Comment by paddy-exe** [comment]
@pycbouh 1) Still persists in my 3.3 version. Not sure how it was fixed but it doesn't work. And if 2) is fixed, great

**Comment by pycbouh** [comment]
@paddy-exe My bad, it was ported to 3.x, but not 3.3 specifically. Will be definitely fixed for 3.4, maybe will be a part of 3.3.x too.

https://github.com/godotengine/godot/pull/47173

**Comment by fire** [comment]
1. Zooming is resolved by https://github.com/godotengine/godot-proposals/issues/1253.
2. https://github.com/godotengine/godot-proposals/issues/7 has a dedicated proposal.

I am trying to organize proposals for visual script by picking the strongest proposals of the duplicates and closing fixed proposals. With the best intentions, feel free to proposal changes to Visual Script or generally to Godot Engine.
