### ISSUE TITLE
Please allow some sort of filter system for imports, in particular stopping CSV files importing automatically

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot-proposals#2687]
### Describe the project you are working on

A lot of projects of mine use CSV, it's very convenient for working with very large datasets

### Describe the problem or limitation you are having in your project

Any CSV files inside the Godot directory, Godot will constantly try to import over and over again as "translation files"

I could rename the CSV, but this throws all my file versioning out of wack, certain CSV files are from official sources so i want to make my project work with this resource for example:
https://github.com/astronexus/HYG-Database

I would like the user to obtain that folder, and not have to rename the files and raise git issue about the red warnings.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If we could set up our projects to ignore certain files or default to "Keep File (no import).

### Is there a reason why this should be core and not an add-on in the asset library?

it's a fundamental feature (couldn't be achieved with an addon), it could be best realised by using a system like .gitignore whereby you could set certain patterns to be ignored.... however just allowing changing the default setting for CSV would solve my issue (it seems you can set a default for textures)

maybe just adding an empty import profile for csv.... where you have "import as" you only have one option "CSV Translation" .... add a "Raw CSV" (make it do nothing)?

**Comment by Calinou** [comment]
This was already implemented in the `master` branch and backported to the `3.x` branch (available in 3.3): https://github.com/godotengine/godot/pull/47268

**Comment by RichardEllicott** [comment]
i need to add that it might be easier to edit 

> This was already implemented in the `master` branch and backported to the `3.x` branch (available in 3.3): [godotengine/godot#47268](https://github.com/godotengine/godot/pull/47268)

no it's not.... because i cannot choose it as a default

i have to go through each file, manually do this, and then reboot the editor for each file!

**Comment by Calinou** [comment]
> no it's not.... because i cannot choose it as a default

Did you see the [new import defaults editor](https://github.com/godotengine/godot/pull/46354) which was also backported to 3.3?

**Comment by RichardEllicott** [comment]
on the CSV screen, if you go there, there's only one option

you cannot stop it from assuming they're translation files

**Comment by RichardEllicott** [comment]
can you suggest how i word it so it doesn't get shut down... i though i documented my problem pretty clearly


so i just say "add changing the default CSV to no import"?
