### ISSUE TITLE
allow ignoring of CSV files in godot

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot-proposals#2688]
please allow ignoring of CSV files in the editor default imports

there is no option, only to leave it as "CSV Translation" ... this forces loading of CSV files as Language files causing errors and endless reload attempts by client

**Comment by pycbouh** [comment]
Hey there. That proposal template was important, and you were supposed to fill it out not to delete it. It contains questions the answers to which we need to be able to discuss the proposed feature or enhancement. Please consider it the next time you open a proposal.

That said, you've already found out that this is a duplicate to #2500, so I'll close it.

**Comment by RichardEllicott** [comment]
you don't give people enough time to defend and edit their proposal, i filled it all in the last one

**Comment by KoBeWi** [comment]
This is available in 3.3, as "Keep" import option.
