### ISSUE TITLE
Add advertisement (Unity ads, Admob ads, Facebook ads) support to Godot for mobile platforms (Android and iOS)

### ISSUE THREAD

**Issue by zolizolizoli** [godotengine/godot-proposals#2694]
### Describe the project you are working on

Currently I am working on 2D crossplatform mobile game (Android and iOS).

### Describe the problem or limitation you are having in your project

I would like to use mainly Facebook ads or Unity ads, but I can't. I can't find any assets in the asset store.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In my opinion this helps to improve the mobile app development. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know how to implement this issue. But I believe in you guys.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Unfortunatelly, no. 

### Is there a reason why this should be core and not an add-on in the asset library?

1. Because the add-on/asset library developer may not be able to keep up with the new Godot versions.
2. Lots of people will be so happy if you guys implement this wonderful feature.

**Comment by pycbouh** [comment]
Thanks for your suggestion, but this is something that you have to implement using a third-party plugin. Including such libraries with Godot is [not possible](https://docs.godotengine.org/en/stable/getting_started/step_by_step/godot_design_philosophy.html#open-source). However, Godot comes with a plugin system for both [Android](https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html) and [iOS](https://docs.godotengine.org/en/latest/tutorials/platform/ios/plugins_for_ios.html).
