### ISSUE TITLE
Better support for HTML5 games

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot-proposals#27]
Hi everyone, here is my proposal/request:
I'm a game developer and I'm developing HTML5 games, but the Godot HTML5 export template is not the best... We have no compatibility with Safari browser and there are thousands of problems, particles don't work properly, you can't use audio in loop and the performance of the exported game is really worst.
The result for me is simply moving to another game engine for HTML5 games, but there aren't engine so flexible and with fast development as Godot, so I'm wondering if could be better integrated the HTML5 export.
I have investigated a lot on HTML5 game engine and there is no one that is at least decent, the only way to create a game is using frameworks like Pixi.js or similar, but the development time increases a lot using that.

So my proposal is to enhance the engine export for HTML5 games.

P.S: if I want to have a look to create this template export what I have to do? There is some documentation about creating an export for Godot?

**Comment by groud** [comment]
Sorry but there is an issue template, and it is here to be filled in. Also, this repository is here to store precise and detailed proposal, not general ideas.
