### ISSUE TITLE
Implement AnimationNodeSub2/3 for additive animation

### ISSUE THREAD

**Issue by josefkaragoli** [godotengine/godot-proposals#2700]
### Describe the project you are working on

3D project with animations

### Describe the problem or limitation you are having in your project

The only method currently in Godot to mix animations is through `Blend` nodes (Blend2/3, BlendSpace1D/2D, Blendtree) and `Add` nodes (Add2/3). These two types of blending effectively do the same thing, as they use the same internal blend_input() function (see https://github.com/godotengine/godot/issues/37661). 

A vital part of character locomotion nowadays is to include additive animations - namely, animations that are overlayed upon other animations to create various realistic effects eg. leaning/changing character stance etc.

https://github.com/godotengine/godot/pull/42302 attempts to address this issue by exposing a 'add_directly' parameter, but 
it's very limited and is unclear in functionality. This is because additive animation requires a base pose from which the animation offsets can be calculated - the additive data should be extracted RELATIVE to a base pose, and the pull request does not actually specify or allow you to change what base pose is being used.

Here is an example of how UE4 allows you to change the base pose from which animation offsets are calculated.
![image](https://user-images.githubusercontent.com/76781125/117552029-19b88380-b05a-11eb-8269-764841217de3.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

My proposal is to remove the old functionality of Add2/3 since they effectively do the same thing as Blend2/3 albeit in a different format. I haven't seen anyone using Add over Blend since it's not really more useful, and its also harder to understand what it actually does (less straight forward than blending two anims). 
Instead, Add2/3 should solely be used for additive animations and a new graph input should be exposed called 'base' which will be used to extrapolate additive offsets.

Example use case from Stride engine:
![download](https://user-images.githubusercontent.com/76781125/117551675-4c617c80-b058-11eb-8940-729907c445cf.gif)
Leftmost animation = Walk animation
Rightmost animation = Idle animation
Two animations in the center  = Walk and Idle animations with Reload animation added ontop

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/76781125/117552502-c1cf4c00-b05c-11eb-8940-6c9780574f3a.png)

'in' is the input feed.
'add' is the additive animation that is overlayed on top of the input feed ('in')
'base' is the reference pose used to calculate the offset of 'add' to apply to 'in'

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Additive animation is used very often to create a variety of different movements with lesser amounts of animation clips. Also, AnimationNode behaviour can not be scripted outside of core.
### Is there a reason why this should be core and not an add-on in the asset library?
There is no way to change functionality of AnimationNodes outside of core.

### Additional references :
https://doc.stride3d.net/latest/jp/manual/animation/additive-animation.html - see "Difference Clips" section (basically Stride's way of saying additive animation)

https://docs.unrealengine.com/udk/Three/AdditiveAnimations.html

**Comment by josefkaragoli** [comment]
I would also like to add that the same thing be applied to AnimationNodeAdd3, since it would use the same framework.

**Comment by TokageItLab** [comment]
In glTF, all poses are relative to the default pose (e.g. T Pose). I've read that AdditiveAnimation creates a value relative to the Idle Pose instead of T Pose.

I agree that removing the old NodeAdd2/Add3 behavior. See also [#34134](https://github.com/godotengine/godot/pull/34134). However, adding the input Base to the current NodeAdd2 is may be bound to cause confusion.

Is `In: A, Add: B, Base: C` the desired result `A + (B - C)`? If so, how about simply implementing NodeSub2 to do the subtraction?

**Comment by josefkaragoli** [comment]
Should I update the proposal?

**Comment by TokageItLab** [comment]
We don't know yet how it will be implemented in fact. You can tell us what you want to do, so I think if the substance doesn't change significantly, you don't have to update it.

**Comment by Mikeysax** [comment]
Isn't this fixed?

https://github.com/godotengine/godot/pull/57675

**Comment by TokageItLab** [comment]
The addition is now done correctly, but the extraction node is not yet implemented. Changed title.

**Comment by TokageItLab** [comment]
Well, I would guess from the original title that this can be closed. The blending is now calculated based on rest correctly, so the Additive Blend should work fine.

**Comment by TokageItLab** [comment]
Closed by https://github.com/godotengine/godot/pull/57675

**Comment by Riordan-DC** [comment]
Can these animation fixes benefit 3.x also?

**Comment by Panda92524** [comment]
If I provide a new 3D character made by blender, could you add animation to the 3D character?
