### ISSUE TITLE
Use the `expand` stretch aspect by default

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2701]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Some developers have trouble supporting multiple resolutions and aspect ratios, despite the documentation on the subject being fairly thorough.

Here's an example of this happening in the wild: https://www.gamingonlinux.com/2021/05/free-game-thursday-check-out-office-point-rescue-deja-vu-a-new-retro-fps/comment_id=202920

Unfortunately, it's quite common for Godot games not to support multiple aspect ratios, despite Godot's support being quite good for it. With the right UI node anchor configuration, 48:9 surround setups can even be supported!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By changing the default value from `ignore` to `expand`, developers have one less setting to change to get multiple resolution *and* aspect ratio support working.

The developer will still have to choose a stretch mode since `expand` does nothing if the stretch mode is `disabled`. Nonetheless, I consider `expand` to be a "better" default that suits more use cases. (Screen distortion is almost never desired.)

We might also consider also changing the default stretch mode to `canvas_items` (called `2d` in `3.x`), but that might be a bit much as it requires UI anchors to be defined to work as expected. You would also pretty much always need to have a Camera2D in your scene for 2D games, even if the camera never moves. This would likely complicate tutorials a bit.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change the default setting of the stretch aspect project setting from `ignore` to `expand`.

**Why not `keep`?** `keep` adds black bars at the screen edges. While it is better than distorting the image, it is worse than providing proper support for multiple aspect ratios. Ultrawide monitors are not that rare among gamers nowadays, and some people also play games on 16:10 or 3:2 laptops occasionally. Don't assume everyone is using 16:9 :slightly_smiling_face: 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as this is about changing a default setting value and improving the out of the box developer experience.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by nobuyukinyuu** [comment]
I think `keep` is a more reasonable default – 2d games in particular are typically designed around one aspect ratio by default and it's not always a reasonable assumption that newbies design something in the area out of bounds for their particular aspect ratio, or worse, have part of their interface cut off.

**Comment by boukew99** [comment]
> We might also consider also changing the default stretch mode to `canvas_items` (called `2d` in `3.x`), but that might be a bit much as it requires UI anchors to be defined to work as expected. You would also pretty much always need to have a Camera2D in your scene for 2D games, even if the camera never moves. This would likely complicate tutorials a bit.

UI anchors are not a problem if you use keep, so newbies can switch to that for tutorials, right? And a having a Camera2D in a scene that never moves is not that bad in my opinion, because it centers around the origin (like most 2D scenes) and is useful for screen-shake and other camera effects. Disabled mode is more useful for editors in my experience (and not games).
