### ISSUE TITLE
Add a Presets tab for displaying color palettes in ColorPicker

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-proposals#2702]
### Describe the project you are working on
A small drawing app (called Painty).

### Describe the problem or limitation you are having in your project
I like colour palettes, because it lets you pre-define colours that work well together. I use them often for modulate and gray scale images and in shaders params.

Right now managing colour pallets in Godot is a bit akward. You define them in the ColorPicker itself (feels not very global and solid, although it is), the amount of columns can't be controlled, you can't re-arrange them, deleting is with right-mouse-button and they are a bit "hidden" in the bottom.

Next to that, I would like to use the ColorPickerButton (especially that of 4.0) in the drawing app itself, but with friendlier presets.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
For my drawing app the solution roughly amounted to defining the colour presets in the project setting and then putting the ColorPicker and presets in a TabContainer. 
By putting it in Project Settings it clear that it used for the whole project and a few more options, such as columns could be added.
By putting it in a TabContainer, one has to choose whether they want to pick any colour or a preset and each has their own space.   

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![afbeelding](https://user-images.githubusercontent.com/49942484/117566873-7303cf80-b0b9-11eb-98c8-9642bb34f8e4.png)![afbeelding](https://user-images.githubusercontent.com/49942484/117566940-d7269380-b0b9-11eb-9ea0-a8d35120a48f.png)
![afbeelding](https://user-images.githubusercontent.com/49942484/117566902-8fa00780-b0b9-11eb-834a-254da39c3c21.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It can be worked around with a custom implementation of colour presets.

### Is there a reason why this should be core and not an add-on in the asset library?
Easier to work with colour overall.

**Comment by Calinou** [comment]
Additionally (and this can be implemented independently of this proposal), I wonder if color presets should be stored in the project settings when adding new presets in the editor ColorPickers. This means the color presets would be stored to version control for easier teamwork. On the other hand, it can increase the risk of VCS conflicts if multiple artists are working on the same project at the same time. So I'm not sure if it's a good idea.

**Comment by boukew99** [comment]
@Calinou I agree, it makes more sense to leave it in EditorSettings. I just meant to use the palette only in the context of this project. One can always store color palettes as images in the FileSystem to communicate used color palettes.

**Comment by EricEzaM** [comment]
I already have a library for this.

Sure, it could be in core but it makes sense as a plugin. 

https://github.com/EricEzaM/godot-color-palette

**Comment by boukew99** [comment]
Yeah, I think my proposed solution does not entirely make sense any more. @EricEzaM plugin has the things I wanted (reordering and importing). Only defining columns is missing (which I use for different saturations of a hue)  ;) . However does it then make sense to include presets in the ColorPicker if you need a plugin to manage it well?

And for in-game, it would be nice to have a property on ColorPickerButton to only show the preset colors to limit user choice (so they can only pick colors, which fit with the rest.

**Comment by EricEzaM** [comment]
I think ColorPicker and ColourPickerButton could do with several of Quality of Life changes to make the better to use in the editor and in games.

**Comment by pycbouh** [comment]
> I also think the ability to hide the RGB/HSV/etc sliders would be useful for games where that sort of detail is not needed.

I think that we are making `ColorPicker` control less and less suitable for games by making it such a customizable beast. At this point, a simple `ColorPickerCircle` would be more beneficial, a control that just allows to pick or set a color on a radial gradient. Everything else, including color preview, sliders, palette management, can be done by users with relative ease, with just enough customization as they require.

> Picking from a list of colours is another cool one which could be added.

Editor color picker already remembers all the last used editor colors, by the way, and presents them in a little palette. So, while rudimentary, it already exists.

**Comment by boukew99** [comment]
Okay thought sometime about it. In godot 4 you have the picker shape property. 
![afbeelding](https://user-images.githubusercontent.com/49942484/120639321-806e6880-c471-11eb-905e-346216154280.png)
![afbeelding](https://user-images.githubusercontent.com/49942484/120639495-aeec4380-c471-11eb-826a-3392d5a84174.png)

An option "reference" could be added to the picker shape propery. You have to provide an image and then it will pick the color from where you clicked in the image. And to work with color pallets you just drop an image with a palette in it as shown below.
![afbeelding](https://user-images.githubusercontent.com/49942484/120640499-d8f23580-c472-11eb-8dd7-5528b6b1e642.png)
This is screenshot is from Material Maker where you use the reference tab for getting colors from reference images. I just placed a color pallete (of Godot's named Colors) in it and then you can easily work with color palettes. Then you can use presets to remember the colors you use often, if it is big picture for example.

Of course you can also  use "reference" with a picture or any other image.
With this solution the RGB and HSV sliders and presets can be left as is.

**Comment by hidemat** [comment]
I see EricEzaM has a nice plugin called color-palette-picker in the Godot asset library. I think a feature like this would fit nicely as a native feature in the Godot Editor. I would also add (I don't know how hard this would be to pull off) that it would be nice to also have "Global Colors", kind of like the one you have in adobe illustrator. Where, if you make a change to the color swatch in a palette, it will affect all nodes that have that color.

**Comment by Calinou** [comment]
> I would also add (I don't know how hard this would be to pull off) that it would be nice to also have "Global Colors", kind of like the one you have in adobe illustrator. Where, if you make a change to the color swatch in a palette, it will affect all nodes that have that color.

See https://github.com/godotengine/godot-proposals/issues/1734.

**Comment by boukew99** [comment]
Adressed in #62910

**Comment by Calinou** [comment]
Reopening, as the feature isn't implemented until that PR is merged :slightly_smiling_face:

**Comment by duianto** [comment]
The PR has been merged: [ColorPicker UX #62910](https://github.com/godotengine/godot/pull/62910)
