### ISSUE TITLE
Allow panning with the right mouse button in the new TileMap editor

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot-proposals#2706]
### Describe the project you are working on
Testing out the new Tilemap/Tileset editor in Godot 4.

### Describe the problem or limitation you are having in your project
I cannot "right-click" and hold to easily pan across my tileset in the new Tilemap/Tileset editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The user can pan by right clicking and dragging around the 2D / 3D canvas. The same should be replicated for the Tilemap/Tileset Editor when it's zoomed in greater than 100%.

Currently panning is not possible and it's bad user experience for the user to manually change the location of the tileset preview using the horizontal/vertical scrollbars.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
The user can right click, hold and move the mouse to pan.
![image](https://user-images.githubusercontent.com/8476589/117600089-a1071380-b18e-11eb-9e15-92844408ca59.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
This is an enhancement to the Tilemap/Tileset editor therefore it should be implemented as part of core.

**Comment by Calinou** [comment]
The TileMap editor should allow panning with both middle and right mouse button, since most laptop trackpads don't have a middle mouse button.

**Comment by KoBeWi** [comment]
This is already possible.

**Comment by serdevai** [comment]
how use right click for pan mode

**Comment by KoBeWi** [comment]
This issue is only for the TileMap bottom editor, 2D editor does not support right-click panning yet.

**Comment by Calinou** [comment]
Support for right-click panning in the 2D editor is being tracked in https://github.com/godotengine/godot-proposals/issues/3881.
