### ISSUE TITLE
Set the export variables first before the rest of the variables in the script.

### ISSUE THREAD

**Issue by Dragon20C** [godotengine/godot-proposals#2708]
Early today I have run into a issue, I wrote it into stackoverflow and a nice person gave me direction that godot export is initialized near the end, this causes values that include the export variables to either produce null or 0 depending on what kind of export it is, This is a link to the question I asked : https://stackoverflow.com/questions/67467252/a-export-value-set-in-the-editor-shows-its-a-zero-in-the-code/67468291?noredirect=1#comment119255058_67468291

```gdscript
extends Resource
class_name Monster

export(Texture) var front_sprite
export(Texture) var back_sprite
export(String) var name
export(int) var level

# Gets the types and gives the monster a type

export(TypeData.types) var type_1 = TypeData.types.none
export(TypeData.types) var type_2 = TypeData.types.none

# Base stats the limit the amount of points a monster can get

export(int) var Base_hp
export(int) var Base_attack
export(int) var Base_special_attack
export(int) var Base_defence
export(int) var Base_special_defence
export(int) var Base_speed

# The avaliable moves the monster can use to attack or other actions

export(Array,Resource) var move_slot = [null,null,null,null]

# The monsters stats based on the level

var hp  = ((float(Base_hp * level) / 100) + 5.0)#((Base_hp * level) / 100.0) + 5.0
var attack = ((float(Base_attack * level) / 100.0) + 5.0)
var special_attack = ((float(Base_special_attack * level) / 100.0) + 5.0)
var defence = ((float(Base_defence * level) / 100.0) + 5.0)
var special_defence = ((float(Base_special_defence * level) / 100.0) + 5.0)
var speed = ((float(Base_speed * level) / 100.0) + 5.0)

# So when the monster takes damage we can takeaway the hp

var current_hp
func hp():
	return((float(Base_hp * level) / 100.0) + 5.0)
func attack():
	return((float(Base_attack * level) / 100.0) + 5.0)
func special_attack():
	return((float(Base_special_attack * level) / 100.0) + 5.0)
func defence():
	return((float(Base_defence * level) / 100.0) + 5.0)
func special_defence():
	return((float(Base_special_defence * level) / 100.0) + 5.0)
func speed():
	return((float(Base_speed * level) / 100.0) + 5.0)
	
func set_current_health():
	current_hp = hp()
```

Here I have inserted the code that shows how important this feature is, I have some base stats that dont change, and then I make the actual values with a calculation for example HP, I take the base_hp and * it by the monster level, and do some division, but this doesnt work because the base_hp which is the export value is 0 at this stage so when i go about to use it, it only produces 5 because 0 * level is 0 and + 5 = 5, currently I have functions to call the correct values but as you might know this isnt a good way of doing it.

___

### Describe the project you are working on
A turn based system with multiple units 
### Describe the problem or limitation you are having in your project
I have created a resource called "monster" and inside the resource I have export variables that export information about the monster, like stats that include damage, health, attack etc, but I have noticed that export variables arent being used inside its own script, this causes a problem since I want to also do some calculations in the same script, I think the variables are nill because of how export is initialized, for what I know the script gets initialized first and then the export values are added, at a specific order. 
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Having the export values be accessible in the same resource can make code more readable and not have a repeatable lines of code
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I think the order of how the export variables are initialized, should be arranged so that when the script does a calculation with the export it actually uses the export and not 0.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
a workaround I have found would be to use a function, since the export is initialized, you can call a function return a value, but this has its limitations 
### Is there a reason why this should be core and not an add-on in the asset library?
This should be core because its a small feature that can improve godots export variables area.

**Comment by pycbouh** [comment]
You can just make your other properties that depend on export properties be `onready`. This order cannot be easily or reasonably changed, as these internal properties of yours are initialized as the script is loaded and initialized. But exported properties that have been saved as a part of the scene are only set after that, as the scene is restored from its resource. It cannot be done the other way, otherwise it wouldn't act predictably.

So `onready` in exactly what you want here.

**Comment by Dragon20C** [comment]
@pycbouh sorry for not replying straight away was busy, thats the problem when I try to add onready var to the variables that are using the export it, it says its a null, this is because of how export apply its value to the variable, or am I making a mistake somewhere because the only thing that connects to that resource is a preload line of code and I access the variable like so ,player.hp, which prints null

**Comment by Astrono2** [comment]
I think your problem might come from trying to access an `onready` variable before `_ready()` is called. I think you can manually call `player._ready()` before accessing `player.hp` but I don't know if it's a good idea. There are probably better ways of doing it than calling `_ready()` early, but basically you need to access your variables after `_ready()` has been called on player.

**Comment by pycbouh** [comment]
@Dragon20C I'm not sure what exactly you are doing there, but this totally works:
```gdscript
export var a = 0
onready var b = 2 + a

func _ready() -> void:
	print(b)
```

Which is exactly the case for your properties here:
```gdscript
var hp  = ((float(Base_hp * level) / 100) + 5.0)#((Base_hp * level) / 100.0) + 5.0
var attack = ((float(Base_attack * level) / 100.0) + 5.0)
var special_attack = ((float(Base_special_attack * level) / 100.0) + 5.0)
var defence = ((float(Base_defence * level) / 100.0) + 5.0)
var special_defence = ((float(Base_special_defence * level) / 100.0) + 5.0)
var speed = ((float(Base_speed * level) / 100.0) + 5.0)
```

**Comment by pycbouh** [comment]
@Dragon20C Preloaded resources are loaded the moment the file is parsed, so they would definitely be ready before `onready`. You may want to drop by one of our community channels where other people can help you debug your issues live. I feel like that may eliminate the need for this proposal.

**Comment by Dragon20C** [comment]
@pycbouh alright I will do that then!

**Comment by Dragon20C** [comment]
I apologize for reopening this issue I would like to get this issue done/sorted out, from what I understand onready vars should do the calculation correctly, it technically does work but it seems this is a unique issue where it only produces null when receiving the values from another script that has preloaded said resource.

**Comment by Dragon20C** [comment]
I will make a reproducible project for you guys to test things out.

**Comment by pycbouh** [comment]
Sorry, my bad, didn't realize the quite obvious fact that you were using a resource. Yeah, resources aren't nodes and don't have a ready signal. This indeed won't work for them, as it won't work for node at the `_init` stage. In that case, your second take to use functions was correct. You can even make readonly variables that would use getter functions, but let you use the property syntax:

```gdscript

var hp setget ,get_hp

func get_hp():
  return ((float(Base_hp * level) / 100) + 5.0)
```

This should work after the resource has been inited, but not before. So you can't read those values in resource's own `_init` function, as the values from the scene were not yet set.

**Comment by Dragon20C** [comment]
Even though there is a workarounds, I was wondering if a solution will come out of this.
for the possible solutions:
1: Change the order of how export applies its value (very unlikely to happen)
2:Add a "keyword" to a variable similer to onready that waits for the export variables to apply(possible solution)
3:Have resources utilize the ready signal (could be possible though there probably a reason why its doesnt have it)
