### ISSUE TITLE
Save the project selection folder

### ISSUE THREAD

**Issue by realmaster42** [godotengine/godot-proposals#271]
Hey!

This is a very small feature request, but it's a much needed quality of life upgrade to the project selection menu.

![image](https://user-images.githubusercontent.com/7365481/69903964-021e9b00-1390-11ea-906b-a01ad53c601a.png)

Right now, every time I open the "Create New Project" popup it takes it to the documents folder of my main user in the C: disk by default.

This is a bit annoying because I don't plan on using that disk at all for Godot development.

Would it be possible to have Godot save the documents folder from the last project creation so that when new projects are created we don't have to keep changing the folder?

Again, very small request, but would be a useful quality of life update.

Thanks!

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
