### ISSUE TITLE
Add option to drag GET/SET singleton from the project settings >> autoload page . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2711]
### Describe the project you are working on
A Tomb raider game, with a new RayCast edge - grab system . .

### Describe the problem or limitation you are having in your project
I wish it was easier to SET/GET singletons . . I'm not sure if this would be the ' best ' idea, but one can move many values, also properties from node dock, like Rotation, Scale . . Right now, one can't move the Singleton over to, Visual script canvas . . .

![2021-05-11 1423](https://user-images.githubusercontent.com/83387915/117814692-e85fd380-b264-11eb-9627-448f55dab580.gif)

I was thinking, if one could maybe ' move ' box over, to visual script, and make a SET or, GETTER, or so . . It'd at least help new users faster, to use singletons . . Not sure if it's the best idea, it'd be nice if it was a bit more user - friendly, in SOME way, to get, set custom made singletons, like player_hp between, say two levels . . Thx <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, maybe one could make a visual script box, a GET / SET, if one 'moved' the ' Singleton ' in autoload, into the canvas, then it has a ' str ' input, where one could write name, or so, of any singleton . . Currently, it's a bit difficult, to make singletons work, they're quite useful, for storing info between levels, without need, for save, to say json <3 . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
So, if one dragged a ' Autoload ' into visual script canvas, it created a box called Autoload Singleton, either a GET, or SET, or so . . Suppose I made a script, called PlayerSingleton, it could call box Autoload Singleton PlayerSingleton . . . Thx <3 . . . 

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Well, there is a way, to do it, it just takes a long time, and it makes it bit ' difficult ', to work on Singletons <3 . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it's just crazy difficult to use, esp. for new users, a simple feature, that's very easy, at least in written code . . :OO . . .

Or, maybe if one ' moved ' it in, it created a ' few ' boxes, to sort of, set it up . . imo, it SHOULD be as easy to get, set singletons, as any other variable, in any script . . .

Alternatively, one could add a new method, to a Preload script, that is also a singleton, ie. if I move in a .vs, and make preload, when I move out ' port ', there's a method called Get Singleton, Set Singleton <3

![2021-05-11 1438](https://user-images.githubusercontent.com/83387915/117816349-b7809e00-b266-11eb-8f30-b0a836a1aa6f.gif)

Well, maybe there's a better way, something fast . . <3 <3

**Comment by theraot** [comment]
Related: #2558

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
