### ISSUE TITLE
Expand Favorites by default

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot-proposals#272]
![Untitled](https://user-images.githubusercontent.com/15337628/69909940-ff3aad80-1456-11ea-847d-4d69b41428e9.png)

They're your Favorites, why wouldn't you want to see them by default?

It's a really small thing, you have to click it open every time you open your project which becomes annoying after you do it enough times. But a tiny problem only requires a tiny fix.

I considered filing this as a bug, because who wouldn't want to see it by default? If the benefit of the Favorites feature is _convenience_ then we can currently consider the convenience lessened.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by rainlizard** [comment]
**Describe the project you are working on:**
irrelevant
**Describe the problem or limitation you are having in your project:**
inconvenience
**Describe how this feature / enhancement will help you overcome this problem or limitation:**
convenience
**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![69909940-ff3aad80-1456-11ea-847d-4d69b41428e9](https://user-images.githubusercontent.com/15337628/69913547-172d2400-148d-11ea-8284-b63235c6710f.png)
**Describe implementation detail for your proposal (in code), if possible:**
change the boolean or whatever
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it is used often
**Is there a reason why this should be core and not an add-on in the asset library?:**
no one would disagree

I hope you realize how foolish it is to fill out this template for something so inconsequential, I intentionally did not. No new information has been obtained with the issue template.

With the introduction of the Godot Proposals repository, small enhancement requests are seemingly discouraged, because we make ourselves look silly filling out this template.
