### ISSUE TITLE
Improve select file dialog with search bar and sort button

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot-proposals#2721]
### Describe the project you are working on
None in particular

### Describe the problem or limitation you are having in your project
Trying to find things in the file dialog with tons of folders or files is slow. I think it would help greatly if you had the option to search through items inside of the file dialog with a search box to find what you're looking for, and for there to be a sort button so you could choose to show recently modified files first. I run into this issue when selecting scenes, and when finding the directory to put projects in.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It would add a search bar and sort button like the one inside of the filesystem dock, so that you can search through folders & files, and sort files by alphabetical order, extension, or by modified date

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
It would take the search bar and sort button from the filesystem dock and add it to the file dialog

https://user-images.githubusercontent.com/12120644/118267617-5b965f00-b48a-11eb-9899-771b6eb4e6bf.mp4

It would help speed up picking files from res:// through the file dialog as well. It makes sense since res:// already has search and sort

https://user-images.githubusercontent.com/12120644/118268961-15da9600-b48c-11eb-92c2-cec4687ef8dc.mp4

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It can't

### Is there a reason why this should be core and not an add-on in the asset library?
For new users getting an add on specifically to improve the file dialog seems inconvenient

**Comment by foxydevloper** [comment]
I'm also able to create a PR for this, I already made changes to editor_file_dialog to get this proposal working

**Comment by Calinou** [comment]
I would rename the "Search" placeholder to "Filter", because the filter box won't search files recursively like a search program would do (e.g. Windows Explorer).

**Comment by LightningAA** [comment]
> I would rename the "Search" placeholder to "Filter", because the filter box won't search files recursively like a search program would do (e.g. Windows Explorer).

Why not? Recursive searching sounds slower but more useful, could there maybe be an option for it?

**Comment by foxydevloper** [comment]
> > I would rename the "Search" placeholder to "Filter", because the filter box won't search files recursively like a search program would do (e.g. Windows Explorer).
> 
> Why not? Recursive searching sounds slower but more useful, could there maybe be an option for it?

Inside of the video I sent it doesn't search recursively, it only filters the current directory, which is why he said "Filter" makes more sense. It would be cool to make it search recursively but someone else would need to do that

**Comment by Calinou** [comment]
> > I would rename the "Search" placeholder to "Filter", because the filter box won't search files recursively like a search program would do (e.g. Windows Explorer).
> 
> Why not? Recursive searching sounds slower but more useful, could there maybe be an option for it?

Recursive searching adds a lot of complexity. A filter will be enough for the 90% use case :slightly_smiling_face:

**Comment by foxydevloper** [comment]
@Calinou Should I create and link a PR for this proposal?
