### ISSUE TITLE
Backport Decal node to 3.x

### ISSUE THREAD

**Issue by sairam4123** [godotengine/godot-proposals#2722]
### Describe the project you are working on
City Builder kind of Game.

### Describe the problem or limitation you are having in your project
I'm currently missing the Decal node which would help me project textures onto my buildings for selections and much more.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I'd like to have the decal node that's available in 4.0 master.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
You can see it live in Godot 4.0 master.

### If this enhancement will not be used often, can it be worked around with a few lines of script? 
No, it can't be.

### Is there a reason why this should be core and not an add-on in the asset library? 
There're some addons, but none of those addons work for me, only Decal node from 4.0 works for me currently.

**Comment by josefkaragoli** [comment]
> There're some addons, but none of those addons work for me, only Decal node from 4.0 works for me currently.
Why not? There are decal addons that work fine in 3.x

**Comment by sairam4123** [comment]
I found it difficult to use, and I felt like Godot 4.0's Decal system works great for me currently.

**Comment by Calinou** [comment]
It's not technically possible to backport the Decal node in `master` because it relies on the new Vulkan renderer in many ways.

**Comment by josefkaragoli** [comment]
> I found it difficult to use

You should consider making a proposal on the repository of the decal addon you used

**Comment by Calinou** [comment]
Closing, as this will not be tackled as a core effort for technical reasons (see my above comment).

As advised above, I suggest collaborating with decal add-on authors to make them more usable.
