### ISSUE TITLE
Add `--gameversion` option which can emit a game-provided version number rather than the engine version

### ISSUE THREAD

**Issue by alexbobp** [godotengine/godot-proposals#2726]
### Describe the project you are working on
I have been helping my friend a bit with a 2D platformer-shooter she is in early stages of prototyping with.

### Describe the problem or limitation you are having in your project
I gave her the idea to add a self-updating script to make it easier to do repeated multiplayer testing with a group of people.  The only way I can see right now to have a game's script provide a version number, would be using the -s option to run a specific version check script, which would still start up the game engine, spawn a GUI (and require X on linux), and require parsing through the verbose output or some other rpc.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The ability for a script or launcher to easily query the game version from the binary would be convenient for any game developer wanting to implement an external self-updating mechanism or other kind of game version management.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I don't know enough of the internals of early engine startup to be too specific, but the general idea that I would like to see is, a new command line option --gameversion that by default makes the game binary print nothing and exit, without starting the actual engine.  There should be some way for the game's code to provide a version number, probably in the same place as other metadata like the name and description, and then the --gameversion argument should print that and exit.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This feature has an extremely low risk of unintended use or side-effects.  No additional code should ever be needed to avoid it.

### Is there a reason why this should be core and not an add-on in the asset library?
It deals with a very early part of the launch of the game binary, so it would increase the complexity to implement as an add-on.  Also, I think it will be broadly useful and of very low complexity to add to core.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/35555.

You can implement custom command line arguments yourself by creating a custom project setting, then reading `OS.get_cmdline_args()`:

```gdscript
# In a script attached to a node in the main scene:
func _ready():
    if "--gameversion" in OS.get_cmdline_args():
        print(ProjectSettings.get_setting("application/config/version"))
		# Alternatively, if you're OK with hardcoding the reporting version:
		#print("1.0.0")

**Comment by Xrayez** [comment]
See also godotengine/godot#44594 which should help implementing game-specific command-line options via script among other things, not just engine-specific usage.

**Comment by alexbobp** [comment]
Thanks for the quick response.  Also, that's a good consideration to be aware of, but at least this feature is equally useful for update checking.

On the topic of being able to use the non-headless binary, I am less concerned about linking the X11 libraries, but rather avoiding requiring an active X server, or popping up a visible window.  I can imagine a linux user wanting to ssh home from work to make sure their favorite game is up to date when they arrive, or more likely, a game developer feeling that an extra window flashing on the screen when their launcher checks for updates is un-aesthetic.  So being able to do it without shipping an extra binary which might confuse users still seems nice.

Even the no-X-server requirement is probably a fringe use case, so now that I think of it, a command line option to simply suppress the main window from being shown would get us most of the way there.  Would that seem potentially feasible?

Also, would there be a difference in time cost between running an update checking script in the game code, and a core feature that can print out a metadata string without starting the engine or loading scripts?  Maybe it's small enough to be trivial.

**Comment by Calinou** [comment]
> or more likely, a game developer feeling that an extra window flashing on the screen when their launcher checks for updates is un-aesthetic

There's the `--no-window` command line argument which also works on Linux and macOS since 3.3 :slightly_smiling_face:

**Comment by alexbobp** [comment]
Okay, you've convinced me.  This feature proposal definitely isn't particularly necessary (even if still a nicer approach, imo).

**Comment by Calinou** [comment]
Closing due to lack of support (see general lack of activity here).

Note that in 4.0, game CLI arguments are now separated from editor CLI arguments, so you'd now have to use `path/to/game.exe --headless -- --game-version`.
