### ISSUE TITLE
Improve display of color previews in the script editor autocompletion

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot-proposals#2730]
### Describe the project you are working on
N/A

### Describe the problem or limitation you are having in your project
When typing in "Color" in the code editor followed by the period, a list of colours is shown in the dropdown, this list is excessively wide and only shrinks when more text is being typed.
![image](https://user-images.githubusercontent.com/8476589/118381708-3859e400-b631-11eb-8689-dac3895af2f7.png)

![image](https://user-images.githubusercontent.com/8476589/118381714-414ab580-b631-11eb-8e31-85bf561b7c11.png)
Even after typing the letter "i" it can be seen that it's worthwhile for UX aesthetics there be some padding between the color text and the actual colour preview.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The width of the intellisense that appears when "Color." is typed should be reduced in width so that it doesn't look out of proportion. Like below:

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
The maximum width of the intellisense that shows would be the same length as the longest color text + enough space to allow for the color square and additional padding for UI aesthetics.
![image](https://user-images.githubusercontent.com/8476589/118381861-c8e4f400-b632-11eb-8ca8-0532c36aeff8.png)
![image](https://user-images.githubusercontent.com/8476589/118381918-47419600-b633-11eb-80a3-9303a4e2f8d2.png)
After typing in a colour, a level of padding exists between the text and the colour box so that the two are not directly touching as it is now.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
It should be core because it's part of the editor and is a quality of life improvement.

**Comment by Calinou** [comment]
> When typing in "Color" in the code editor followed by the period, a list of colours is shown in the dropdown, this list is excessively wide and only shrinks when more text is being typed.

This is likely because one of the options is much longer and causes the dialog to be longer. Changing the autocomplete dialog width dynamically is something we should avoid since it'll look weird while the user is scrolling through suggestions. One way to solve this would be to display the color preview on the *left* (instead of the right).

**Comment by pycbouh** [comment]
> This is likely because one of the options is much longer and causes the dialog to be longer.

I couldn't find one. The list is indeed excessively wide by default but gets to the size of the longest item as you type more. And we could indeed add a bit of a padding between the text and the color preview, while keeping the preview to the right still.

**Comment by knadoor** [comment]
@Calinou  @pycbouh 
I've noticed the default behaviour in the Visual Studio editor is to set the width of autocompletion to the maximum width of the longest item in the list + about 2-3mm padding before the scroll bar. The width of the autocomplete then auto resizes as the user types and it finds a longer list item.

![image](https://user-images.githubusercontent.com/8476589/118415998-d52f8680-b6f0-11eb-9ec0-0dc63eb7abb8.png)

**Comment by Calinou** [comment]
Note that the *opposite* has been requested here: https://github.com/godotengine/godot/issues/16542

**Comment by me2beats** [comment]
Maybe another option is when colors are to the left of the suggestions

**Comment by pycbouh** [comment]
> Since there are definitely more than 50 named colors available, the maximum width is used instead. We could increase this number to something like 500, but this may decrease autocompletion performance significantly.

I get what you're saying, but how can an Electron app be more performant than a native one? 🙂 I.e. if it's okay for VS Code, surely we can manage?

**Comment by Calinou** [comment]
> I get what you're saying, but how can an Electron app be more performant than a native one? :slightly_smiling_face: I.e. if it's okay for VS Code, surely we can manage?

Done here: https://github.com/godotengine/godot/pull/49423

**Comment by TheSofox** [comment]
Seems fixed to me:

![image](https://github.com/godotengine/godot-proposals/assets/3089525/c91a29df-da6b-40df-a4ae-b0f3235717e0)
