### ISSUE TITLE
Create `Signal` type for better autocomplete and compiler errors

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#2731]
### Describe the project you are working on
Godot
### Describe the problem or limitation you are having in your project
Using strings for signals results in worse **compiler errors/autocomplete/refactoring tools**
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think there should be a `Signal` type for signals that (maybe) inherits `Callable` (kind of like C# `event`s).
`Object` would no longer need `connect()`, `disconnect()`, `emit_signal()`
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Here's some of my ideas for how it could look:

GDScript:
```gdscript
# player.gd
signal on_death(score: int)

func die():
	on_death.call(score)
	# or if callables ever support this
	on_death(score)
	# or maybe if using callables wouldn't make sense, something like
	on_death.emit(score)


# death_screen.gd
player.on_death.connect(show)

func show(score: int):
	# do stuff
```
C++:
```cpp
// base_button.h
public:
	Signal pressed; // something like this

// my_class.cpp
my_button->pressed.connect(callable_mp(this, &MyClass::do_stuff));
// or maybe like C#
my_button->pressed += callable_mp(this, &MyClass::do_stuff);
```
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
Signals are core
<hr>
See also: #2557

**Comment by dalexeev** [comment]
[This has already been done.](https://godotengine.org/article/core-refactoring-progress-report-1)

**Comment by KoBeWi** [comment]
Yep, closing.

**Comment by LightningAA** [comment]
I guess I got confused because most places in the c++ codebase still use strings for the signal name, is this just a gdscript thing?

**Comment by Calinou** [comment]
> I guess I got confused because most places in the c++ codebase still use strings for the signal name, is this just a gdscript thing?

Indeed, it's only used in GDScript for now. I'm not sure if there are plans to use the Signal type in C++.

**Comment by pycbouh** [comment]
Yes, engine uses strings for that. To make the process a bit more controlled you can use the `CoreStringNames` singleton.

```cpp
_curve->connect(CoreStringNames::get_singleton()->changed, callable_mp(this, &CurveTexture::_update));
emit_signal(CoreStringNames::get_singleton()->changed);
```
