### ISSUE TITLE
Allow tooltips to display over all other nodes

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-proposals#2732]
### Describe the project you are working on
This
![this](https://cdn.discordapp.com/attachments/713075589300486234/843732204722716692/unknown.png)

### Describe the problem or limitation you are having in your project
Sprite is on top of tooltip and is hard to see

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Putting tooltip on top will make it easier to see

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Imagine the example image but you can actually read the entire text

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yeah, I guess I could just instance the invisible buttons on top of everything else, I guess. But I would rather have the buttons be children of the enemy sprites instead. Unless that's not a good way to do it?

### Is there a reason why this should be core and not an add-on in the asset library?
Tooltips are core.

**Comment by KoBeWi** [comment]
This is a bug. Also it's fixed in 4.0.
