### ISSUE TITLE
Directory history tags system 

### ISSUE THREAD

**Issue by noearaujo** [godotengine/godot-proposals#2733]
I still don't have experience with c ++ and I don't know how Godot's UI is made, but I have experience with GDScript. So, I want to contribute in some way and so I can say that I am part of the developer community.
 
I am creating a Module Editor (File Maneger) for my game and I ended up creating a small system that can facilitate navigation between directories.

https://user-images.githubusercontent.com/37861515/118459250-f59c1880-b6d1-11eb-9a7a-beae529d70f6.mp4

Directory history:
Each directory (folders) is a button that contains information (path of the real directory, what type of file it can contain, etc.) ... and when opening it (doubleclick), it is placed in the history ["name of the folder "," directory path "]. (The history is a matrix []).

History tags:
When opening a directory (2x click in button), at the end of adding a new item in the history, it will analyze the history and create a new tag (top button) for each item. The tag will simply represent the history of the open directories (<>). It also has a variable that stores the current directory; if I open the previous directory using the Tags and in that same directory I will open a folder, the history is updated, the later Tags will be deleted (delete using a loop) and a new tag is created (representing the new directory).

I believe that the creation of these tags in the Godot directory browser, can make navigation even easier. I haven't seen any other software yet. I am very happy to have created this innovation in my projects and that is why I shared it with you.

God bless you all,
and may your god (or gods) bless you too.

Created by Google Translate (lol, my english is not so good)

**Comment by pycbouh** [comment]
Hey, please follow the template for the proposal. It's important to follow the provided sections and answer the questions presented.
