### ISSUE TITLE
Use underscore (`_`) as a "default" key for Dictionary

### ISSUE THREAD

**Issue by shraiwi** [godotengine/godot-proposals#2736]
### Describe the project you are working on

I am working on a VR application with low-latency streaming

### Describe the problem or limitation you are having in your project

I am mapping WebXR strings to enum values using a dictionary, like so:
```gdscript
# ClientMode is an enum
const WEBXR_FEATURE_MAPPING : Dictionary = {
	"local-floor": ClientMode.CLIENT_VR_3DOF,
	"bounded-floor": ClientMode.CLIENT_VR_6DOF,
};
```
But I'd like to avoid the overhead of using the `.get()` function every time to handle null coalescence.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I noticed that the `match...case` branch uses the `_` token as a wildcard. I believe that it would be intuitive for GDScript dictionaries to have this property as well. Instead of defining a default value during the `.get()` function call, I think it would be easier for programmers to define a default key-value pair upon declaration.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Accessing a dictionary this way is redundant and unintuitive:
```gdscript
const WEBXR_FEATURE_MAPPING : Dictionary = {
	"local-floor": ClientMode.CLIENT_VR_3DOF,
	"bounded-floor": ClientMode.CLIENT_VR_6DOF,
};

# for multiple calls, this gets unwieldy
WEBXR_FEATURE_MAPPING.get("local", ClientMode.CLIENT_FLAT); # returns ClientMode.CLIENT_FLAT
WEBXR_FEATURE_MAPPING.get("local-floor", ClientMode.CLIENT_FLAT); # returns ClientMode.CLIENT_VR_3DOF
```

But with the underscore wildcard, default values are be a breeze:
```gdscript
const WEBXR_FEATURE_MAPPING : Dictionary = {
	"local-floor": ClientMode.CLIENT_VR_3DOF,
	"bounded-floor": ClientMode.CLIENT_VR_6DOF,
	_: ClientMode.CLIENT_FLAT, # '_' denotes a default value
};

# this stays clear and concise
WEBXR_FEATURE_MAPPING["local"]; # returns ClientMode.CLIENT_FLAT
WEBXR_FEATURE_MAPPING["local-floor"]; # returns ClientMode.CLIENT_VR_3DOF

# of course, we can always override the default in the function call
WEBXR_FEATURE_MAPPING.get("local", ClientMode.CLIENT_LOCAL); # returns ClientMode.CLIENT_LOCAL
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

While it's possible to have default keys declared in the function call, it is easier to have them declared upon creation.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a change to a GDScript core object, so there's no way to implement this otherwise.

**Comment by pycbouh** [comment]
I don't think this is a common use-case for dictionaries and you can always make a method that would know to fallback on a special key or a predefined value.

```gdscript
func get_webxr_feature(key : String):
  if (WEBXR_FEATURE_MAPPING.has(key)):
    return WEBXR_FEATURE_MAPPING[key]

  return WEBXR_FEATURE_MAPPING["_"] # or just ClientMode.CLIENT_LOCAL
```

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/1321.

**Comment by KoBeWi** [comment]
> But I'd like to avoid the overhead of using the .get() function every time to handle null coalescence.

I don't think there is much more overhead than with the `[]` operator or with the proposed changes.

**Comment by zinnschlag** [comment]
Also, what happens if you do want to put a _ as regular key into a dictionary? I don't think having such kludges is a good idea. They are likely to trip people up sooner or later. Sounds like a violation of the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

If we really want to have this feature, it might be better to consider something like [Python's defaultdict](https://docs.python.org/3/library/collections.html#collections.defaultdict). But I am not convinced that it is worth it the additional type. As @pycbouh has pointed out, the issue can be worked around easily.

**Comment by shraiwi** [comment]
> Sounds like a violation of the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

My original reasoning was that since the `match..case` pattern uses the underscore as a wildcard, the dictionary should too, but your reasoning makes sense as well. The group that it benefits from a change like this is so small that it really isn't worth implementing it. Thanks for the feedback!
