### ISSUE TITLE
Make working with .glTF more user-friendly in terms of animations, rigging - work . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2741]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I've been thinking, this might be 'incredibly' dumb . . When one imports a .glTF, one can move it as a node, into the scene . . Atm, one can't access the animations, or bones in the node inspector . . I know this might be very wrong, was thinking if one could access the animations, even skeleton directly under the .glTF, and run, or sort-of play them . . . So, one could just ' move ' the animations into say, visual script, and it creates an animationplayer ' box ', to make working with .glTF faster, also for beginners . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, not sure why one has to save, to just ' play ' animations, for an imported .glTF . . Maybe, this is where I'm not sure, make so one can see the animations, for a .glTF in the inspector . . here . .
![2021-05-19 1615](https://user-images.githubusercontent.com/83387915/118828397-88e57180-b8bd-11eb-9888-7c487b1b131f.gif)

Atm, one can't access the animations, from the first .glTF node, it'd be nice if one could access them, right away, not sure . . .
<img width="406" alt="Skærmbillede (1794)" src="https://user-images.githubusercontent.com/83387915/118828527-a31f4f80-b8bd-11eb-8add-98fd77f3845d.png">

So, there was a menu, called animations, and one could sort of, drag - n - drop those into Visual script, and immeditately see the animations . . Not sure, if it's problem with audio nodes, so if one drag - n - drop audio stuff into scene, or node tree, one can just call them, from the first node, without being able to edit them <3 Ok, tested it, one can't drag n drop audio res. into the scene, and it just creates an Audiostream node :OO . . Been thinking about it, might make it easier for beginners to work with the engine, I'd use it, 100 % <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add so, when one ' moves ' a .glTF into a scene, the node that is created, can access animations, or so <3 . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Well, I can't code the engine . . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it'd just make it more user - friendly, to make 3D assets work, also sound . . :OO . . . Thx <3 . . . .

add. It'd just make it more ' intuitive ', to work with the engine, at least for beginners . . Thx . . . <3 <3

I guess you'd have to turn the .glTF node, into a may-be, super-node, one could access animations, or ' rig ' info from . . At least for animations, one often doesn't want to ' modify ' them, beyond what's made in Blender <3 . . .

**Comment by mrjustaguy** [comment]
Node3D Doesn't contain animations, and this is nearly identical to #2740 that you made like 2 hours ago.

To access animations and/or bones, turn on editable children on it, or just open the gltf as a new inherited scene and save it as a .tscn/.scn and do any changes you want to the scene directly.

**Comment by charlesmlamb** [comment]
Yes, well, some-times I don't want to change the animations, just play them, in an ' easier ' way, but it does take away control, or so . .

Well, not sure, I use visual script, to ' learn ' coding, if for instance the animations were on a list, and one could say, select one, and just ' move ' it into a script canvas, and it was set with, the correct name, it'd be faster to access animations, sort of, for beginners <3

The other proposal was to get, some import settings back, I guess, this is another way of making working with the engine more intuitive . . I'd just skip a ton of, repeat work-flow, and allow people to quickly see, their animations, esp. if selecting say, an animation, opened the ' Animation ' tap, so one could play it . .

It's an idea, also if moving an audio source into the 3D viewport, created an audiostream player, so on . . I realize it's noob, so it is, what it is . . . :(( <3 . . .

**Comment by charlesmlamb** [comment]
Ok, one could also make, so if one drag-and-drop a .glTF, it asks, if there's animation data, do you want to import as ' multiple scenes ', and set up the nodes, so it just work, ie. create an animationplayer node, and open the ' animation ' tab . . It avoids having to send signals, or singleton stuff between inherited scenes, and means anybody can start working with their animations, while maintaining the current system or, one could add a button, in the ' inspector ' that, generates the animationplayer node as a 'separate' scene and, one can ' faster ' see what has been made, in Blender, esp. for new users, MAY-BE more experienced users would also like it, not sure one can do the same, with the armature, haven't tried that . . .

Also, this might be nice for audio, esp. if one could go into a ' snap ' mode, when moving into 3-d viewport, that snapped a new audio node, to existing nodes, so if there was a car, and one ' dragged ' audio res files into the editor, it ' tried ' to snap to origin, of other objects, and set it up, in the ' inspector ' . . it'd just make it faster and, more noob - friendly, took me some months, to find the way, to do it, using a different importing work-flow, ie. multiple scenes . . :OO <3 . . .

**Comment by mrjustaguy** [comment]
Again - There ARE NO MULTIPLE SCENES in a gltf file, just a Tree of nodes, and when you just drag it into the scene the way you are doing, you are instancing the Tree, and as such you need to mark it as Editable to be able to manipulate the children in the editor, something that was ALWAYS the case.

What you want to do (as in were doing in 3.x but don't know how to do in 4.0, because of the new and Improved Import Workflow) is Right-click the gltf file, and open a New Inherited scene and modify stuff there, and save it as a scene to instance in your main scene.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP and comments).
