### ISSUE TITLE
Add a level of detail system for GPUParticles3D and CPUParticles3D

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2743]
*See also #2744 which is for light nodes and https://github.com/godotengine/godot-proposals/issues/2784 for reflection probes.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Particles currently don't feature a built-in LOD system.

When you use many particles nodes (e.g. for torches in a room), you don't want those to emit particles if the player is too far away to see the torches. This is especially true with small particles like sparks.

For the record, the Decal node (new in 4.0) features a built-in LOD system with configurable distance and fade distance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add emission range and fade distance properties to GPUParticles3D and CPUParticles3D.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If we find out a way to allow changing the number of particles emitted without resetting emission, this would likely be the ideal way to do LOD for particles as it will likely look the most seamless in action.

Alterntively, we can:

- Reduce the opacity of distant particles progressively. This can be more suited for particle systems that only emit a few large particles, but it's arguably less suited for particle systems that emit hundreds of particles or more.
- Disable emission for distant particles entirely (without affecting the public `emitting` property, so that it doesn't interfere with toggling it from a script). This is better than toggling the visibility (which causes visible pop-ins), but due to the "all or nothing" nature of toggling emission, it's still worse than the proposed alternatives.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Kind of. It's possible to toggle particle emission in a script. The [Godot LOD](https://github.com/godot-extended-libraries/godot-lod) add-on I wrote provides such a feature.

### Is there a reason why this should be core and not an add-on in the asset library?

Implementing this LOD system in C++ would lead to better performance when using large amounts of particle nodes (hundreds or more).

**Comment by QbieShay** [comment]
I like this idea!

It could be done by LOD'ing both the particle number and the material for the particles (switch from alpha to cutout?)

**Comment by Calinou** [comment]
> It could be done by LOD'ing both the particle number and the material for the particles (switch from alpha to cutout?)

The issue with switching materials is that you need to introduce a second material, which kind of negates the performance benefit. Also, isn't alpha-testing going to look pretty bad at a distance due to the aliasing?

**Comment by Zireael07** [comment]
Would it be possible to use scale for LOD? I have a rain particle that could benefit from being bigger in the back and smaller closer to the camera, so that it's almost uniform (but not quite) in size.

**Comment by clayjohn** [comment]
I'm concerned that this proposal is too limited. I echo Qbie's and Zireael's concerns, proper LODs will need to tweak more than just emission rate. Good particle LODs will need to change emission rate and process material (or even mesh and mesh material as well.

I think the only solution is to have something like HLODs for particles. Where one node fades out and another fades in based on distance with a specified hysteresis.

**Comment by Calinou** [comment]
With the [implementation of visibility ranges](https://github.com/godotengine/godot/pull/48847) and [distance fade](https://github.com/godotengine/godot/pull/54222) in `master`, it's possible to use this (H)LOD system for both GPUParticles3D and CPUParticles3D :tada: 

**Testing project:** [test_particle_lod.zip](https://github.com/godotengine/godot-proposals/files/8136949/test_particle_lod.zip)

Small tutorial:

- Add a GPUParticles3D node or CPUParticles3D node.
- Configure the ParticlesMaterial and the mesh resource to use in the particle.
- Duplicate the node and move it to be a child of the first particle node. Perform one or more changes that make the child particle node less demanding to render:
  - Use a less demanding mesh/material.
  - Use a lower amount of particles.
  - Use a different ParticlesMaterial.
- In the inspector's GeometryInstance3D section, configure **Visibility Range** so that the **End** distance of the parent node is equal to the **Begin** distance of the child node. (The distance should be set to whichever cutoff distance you desire; try `25.0` for instance.)
- If you want hysteresis or fading, set the fade mode accordingly in the **Visibility Range** section, then configure **End Margin** and **Begin Margin** on the parent and child nodes respectively.

https://user-images.githubusercontent.com/180032/155617738-fbe4dbc5-a6ca-45b5-8c6e-6982fa3c1810.mp4

I'll close this proposal as visibility ranges cover the original need in the proposal well enough. (In fact, it's more powerful than the solution proposed here, since it lets you adjust materials, meshes and process materials as well.

For Godot 3.x, you can use the [Level of Detail](https://github.com/godot-extended-libraries/godot-lod) add-on as always.

**Comment by Zireael07** [comment]
@Calinou: This is an excellent explanation worth documenting somewhere more accessible than Godot proposals... godot documentation itself...?

**Comment by Calinou** [comment]
> @Calinou: This is an excellent explanation worth documenting somewhere more accessible than Godot proposals... godot documentation itself...?

Documentation on visibility ranges and [particles](https://github.com/godotengine/godot-docs/pull/5535) hasn't been updated yet, so I'd wait until that part is done.
