### ISSUE TITLE
c++ 20, it's here, right?

### ISSUE THREAD

**Issue by unicomp21** [godotengine/godot-proposals#2747]
I would like to revisit the idea of co_await and c++ coroutines within godot.  The implication for simplifying procgen actor-like techniques, which are used at runtime, is too big to ignore, imho.

**Comment by Zireael07** [comment]
There is a proposal template - you're supposed to fill it out not replace it with two lines of your own text.

**Comment by pycbouh** [comment]
Indeed, please follow the rules for opening a proposal. Also note that C++ features are decided on individually, so you need to make a case for each feature you want to use, not just point at a recent standard.

This will be reopened if and when the proposal is properly formed.
