### ISSUE TITLE
texture/sprite Jiugongge stretch

### ISSUE THREAD

**Issue by wenbingzhang** [godotengine/godot-proposals#2752]
### If this enhancement will not be used often, can it be worked around with a few lines of script?
Can be implemented using script

**Comment by LikeLakers2** [comment]
Hi! You should fill out the rest of the questions in the issue template. Otherwise, we won't have the information necessary to understand what you're proposing.

**Comment by pycbouh** [comment]
Indeed, there are important parts missing from this to be a proposal. Namely the subject, the limitation that you want to solve and how you want to solve it. "Jiugongge stretch" doesn't yield many useful results, so you may want to use some international terminology to explain what exactly it is that you want.

This issue will be reopened when you update your proposal.
