### ISSUE TITLE
Color-Categorized Comment System

### ISSUE THREAD

**Issue by JordanHoffman** [godotengine/godot-proposals#2755]
### Describe the project you are working on
- A simple rpg/defend-the-tower style game

### Describe the problem or limitation you are having in your project
- I can't use color-categorized comments. I use comments for multiple purposes. Some of my comments explain the code. Other comments warn me of features I still have to do. Other comments tell me that there's something not working intended, and so on. I like to have different colored comments to let me know all of this as I skim through my code. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
- A color-categorized comment system. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Here's an example that I use in VSCode. It works great.
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

In this extension, they start off with the typical comment identifer (which for Godot would be # ). Then it checks for a special character(s) right afterwards (they have defaults and allow user-defined ones). If it sees that character, it knows to make this a special colored categorized comment.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No.

### Is there a reason why this should be core and not an add-on in the asset library?
Well, to be honest I'm not sure. Maybe you should lead with this question before someone fills out their entire proposal only to get to this question lol.

**Comment by pycbouh** [comment]
This is the kind of nice-to-have feature that is better solved by dedicated coding tools like the aforementioned VS Code. They are designed for this kind of fine tuning, and even then this is achieved with a plugin, not a core feature.

Though maybe it would be possible to add something like that in Godot 4, where the plugins would have more control over the syntax highlighter. In the meantime, there are TODO plugins that help you organize your special comments in a dedicated panel.

**Comment by JordanHoffman** [comment]
> This is the kind of nice-to-have feature that is better solved by dedicated coding tools like the aforementioned VS Code. They are designed for this kind of fine tuning, and even then this is achieved with a plugin, not a core feature.
> 
> Though maybe it would be possible to add something like that in Godot 4, where the plugins would have more control over the syntax highlighter. In the meantime, there are TODO plugins that help you organize your special comments in a dedicated panel.

I had searched for a comments extension in the asset library and found none. I never knew this existed! Thanks for bringing it to my attention. It's not quite the same, but it accomplishes at least what I want.
