### ISSUE TITLE
Import Photoshop (legacy) PSD documents

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#2758]
### Describe the project you are working on
A 3d game

### Describe the problem or limitation you are having in your project
PSD is a common format for textures. We could support it. Surveying to see if adding PSD support is worth the effort.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Implement PSD loading support.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add https://github.com/MolecularMatters/psd_sdk as an importer module.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
PSD import code is the nightmare of more than a few people.

### Is there a reason why this should be core and not an add-on in the asset library?
Could be GDNative.

**Comment by aaronfranke** [comment]
This kind of thing could be done in GDNative, and it seems like a niche enough use case that it should be GDNative.

**Comment by 2shady4u** [comment]
Hello! I'm the owner of the https://github.com/2shady4u/godot-kra-psd-importer repository and would like to chip in 😆 
Unfortunately I haven't had time to really work on this plugin lately.
I would like to convert this plugin to an actual importer plugin more akin to vnen's tiled importer (as currently it's more of a hybrid thing)

@fire Regarding the suggestion to add the psd_sdk as an importer module. There are several issues with the approach:
- The PSD_SDK is currently not compilable for Linux or MacOS (which is a big problem imo)
- The code of the PSD_SDK is a mess.. (I tried working with it) Also it uses a lot of old-school memalloc/free functionalities that should be replaced by more modern C++ smart pointers.

Also I would like to add that adding Krita (KRA) support would also be easily possible using the kra_sdk repository (https://github.com/2shady4u/kra_sdk)

I will probably have more time in the future to work on my plugin...
But I do think that **natively** supporting PSD importing sends the wrong message for a FOSS product.
We should not support/facilitate the usage of proprietary software, ESPECIALLY not Adobe products (🤮 )

**Comment by aaronfranke** [comment]
Another consideration is that it would generally go against Godot's philosophy to favor a proprietary format over FOSS ones, especially if this proprietary format is from a program that doesn't run on Linux (and therefore many Godot devs can't use). If PSD is added, it would make sense to first add XCF from GIMP, KRA from Krita, ORA (Open Raster format), and EXR.

**Comment by fire** [comment]
Closing due to negative interest in PSD support.

**Comment by anunknowperson** [comment]
Since support for the format with layers can be very useful in some situations, I created my own module for Godot 4.
https://youtu.be/HhiW25nzqLk
The video says why it might be useful

If someone needs it, I can share the source code.

Since this is implemented as a module, the export is supported on all platforms and for all platforms.

**Comment by fire** [comment]
Can you publish on github for review? I'm still interested.
