### ISSUE TITLE
problemas en android 5.0 al acercar 2 modelos 3D se desfigura el modelo

### ISSUE THREAD

**Issue by matiashak** [godotengine/godot-proposals#276]
**Describe the project you are working on:**problemas en android 5.0 al acercar 2 modelos 3D se desfigura el modelo esto tambien no funciona los materiales sin activar el unshaded en los materiales solo asi funcionaron con "sky" porque actualmente solo me funcionaba con "clear color" 
![Screenshot_2019-12-01-16-58-48](https://user-images.githubusercontent.com/58227174/69919558-6586f680-147e-11ea-809b-9d059edbbca6.png) al alejar los personajes no se deforman nada reproduce todas las animaciones correspondientes solo al acercarse unos a otros ocurre esto

**Describe the problem or limitation you are having in your project:**

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by clayjohn** [comment]
I think you meant to make a bug report on the normal Godot repo https://github.com/godotengine/godot . 

This repo is for feature proposals only. 

Also note, issues must be made in English as that is the language of development.
