### ISSUE TITLE
Add backwards auto code - completion to written code and ?? visual script . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2768]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
We were talking about visual script improvements, however this might apply to written code also . . . I was thinking, in visual script there's no search bars, for searching for ALL engine methods (functions??), and properties, and sort-of have the engine auto-finish it, the code, from the ' last ', ie. backwards - completion . . It was about visual script, but might also be cool, for written code . . Idea is, add search bars for 1. ANY engine method/function, 2. ANY property/parameter for the entire engine and, 3. for ANY user - made function, var, or singleton, or user-defined property, etc etc . . .

<img width="1006" alt="Skærmbillede (1829)" src="https://user-images.githubusercontent.com/83387915/119405183-2804d180-bce1-11eb-9952-2b9501fa820c.png">

Proposal, add either three new icons, that open a different version, of the normal 'right-click' search for nodes, or a search bar, where one can type, and it finds ' relevant ' hits, that sort of, let's say I need to GET, or SET engine FPS, frames-per-second, that's a property under the engine singleton performance . . .

So, in the back code - completion search fields, sort of, one types FPS, and it finds the best, or most used code - sequence to that SET, or GET, and auto-creates the boxes, we were talking about custom singletons, so it'd auto - create these boxes, for a user singleton . . ps. another guy I was talking to on Discord, made another proposal, this is not a well, extra - account :OO . . Thx . . .

![Skærmbillede (1361)](https://user-images.githubusercontent.com/83387915/119405583-c2fdab80-bce1-11eb-9974-847532453799.png)

The idea was, it would sort of, instead of starting from the beginning, like when one types, or so . . This is a bad example, since I don't know written code, atm . .

First, one builds it up, this is also where engine have FORWARD code - completion . .

engine

engine.singleton

engine.singleton.performance

engine.singleton.performance.FPS

This might not be right way, for accessing a singleton, in WRITTEN code . .

My idea is, could this be added, to both written code AND, visual script . . 

So, instead of typing all the above, maybe one has a special BUTTON, where one goes into backward code - completion, ie. instead of typing all that code, to access a singleton, one just writes . .

FPS

When say F5, for backward code - completion is on, and it gives THIS auto - completion result . .

FPS - and, if I click it, it types ALL this, at once . .

engine.singleton.performance.FPS

Idea was, instead of searching forward, one can also search backwards, at SOME level, I think level of engine methods, and engine properties make sense, since it's often the end-goal, of code, or so . . . And, this ONLY happens if one is in that mode, which can be toggle with a icon button, or maybe a short-key, like F5, something . . That button toggles between normal forward code-completion, and last word in ' code - word ', if one presses F5, it toggles it ON, then OFF, then ON . . It'd mean for instance, new users could find a method, or property in the docs, type it, and find the ' right ' way, to get the written code, even hard - core users could use it, if there was something they almost NEVER used, instead of looking it up, this is prob. the worst example ever, typed FPS, and it worked back - ward . .

We talked about it, bec. we wanted it for visual script, sort of, one has some panels, or icon one clicks, to get some search lists, that give access to ALL methods, or properties and, a last one, where the user - made stuff is, ie. singletons, new engine - level methods, coded by user, etc etc . . And, then it sort of ' creates ' the necessary boxes, with the ' correct ' information in the boxes, which is same, as back - ward code - completion, for visual script . . Then we sort of realized, this could work for written code as well, assuming the number of methods, and properties LIMITED . . Basically, the same could be done for written code, we talked about it for Visual script, like this . . .

<img width="1006" alt="Skærmbillede (1829)" src="https://user-images.githubusercontent.com/83387915/119406531-3a800a80-bce3-11eb-8a95-4a1ea35c0d7f.png">

So, we have NORMAL right-click search for nodes list, but also some icons, that open a new list, or some type-in-words search bars, that then open a list, with 1. ALL engine methods, 2. ALL engine properties and, 3. ALL user-made stuff, new functions, that are global, custom singletons, etc . . It would basically be the same, as 1. SEARCH for something, and 2. AUTO - code completion, for well, visual script . . . It might work for written code to, my idea is one has a button, or icon, where one can toggle it ON or, OFF, or so . . That way, the code editor knows what it is to search, the normal forward code auto completion, or the other way, since it might be more intensive, to have a much longer list, ie. there's prop. more words, one could toggle it on, if it was slow, or have some search bars, also in WRITTEN code, where one could search, and it might take even 1 second, before the answer was found . . so, it doesn't slow down the normal fast forward code - completion . . .

We wanted the same in visual script, so suppose I wanted to SET or, GET a user - singleton even, or some complex aspect, of the engine, one could type for instance FPS, and it auto-created these boxes, which is same, as code - completion, sort of, for visual script . . .

![Skærmbillede (1834)](https://user-images.githubusercontent.com/83387915/119407578-b595f080-bce4-11eb-8781-3340d8e01e86.png)

Idea was, since it's often COMPLEX to find, also fill the boxes correctly, for accessing many things, this ' might ' be cool but, then we got thinking, this MIGHT also work for written code . . So, wanted to suggest it, for EITHER system, maybe it's easier to make for GDScript first, the primary coding language, and if it's popular, add it to visual script, eventually . . . Well, it's an idea, sort of back-ward code auto completion, or so . . It'd be really nice for visual script, to be able to ' auto - make ' some complex boxes, the correct way, but this might be more cool, for written code, maybe start there, to get feed-back, and so on, not sure it's 'really' possible, for visual script . . . But, it'd be nice to have it there, as well . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Ok, that's the proposal, as you like, CONSIDER adding this to either written code, or visual script, or even both systems, in the order it is easier, or what is actually useful, ie. this might ONLY make sense in written code, and I'd have no idea, thanks <3 <3 . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add some search bars, where one can type in a ' reverse ' word, and it gives an increasingly shorter list, the more words one type in, like the normal search lists, so, in vs, if I search for . . .

m
ma
mat
math

It ONLY shows the 'Math' box <3 . .

Add a search bar, that has 1. all the methods, 2. all the properties and, 3. all the user - custom made stuff, singletons, custom new functions, or so . . . And, if this could be added to visual script, this is where we originally thought it MIGHT be useful, type this stuff, and it sort of auto sets the sequence of boxes, with the ' right ' connections, or so . . Since, in well, visual script making the boxes (nodes), finding proper information, figuring stuff out, can be 'quite' difficult, and we would really benefit from it, there . . However, it might be much more complex, to include all this ' what-if ' code for visual script, compared to written code, ie. filling the boxes might be complex, from a ' back-wards ' perspective . . That's why this proposal, as it is . . is both for written code, and visual script, or EITHER, as the engine experts see fit, or contributors, I have ZERO idea if this is practical, etc . . So, no matter what, it's a pure suggestion, no ' strings ' attached, or so . . 

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not sure, still a ' noob ', sadly . . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it might be a new feature, or rather ' cool ' . . We talked about it for visual script, but that might be so technical, due to the nature of the boxes, how to fill out fields, etc, that doesn't have a standard work-flow, AFAIK . . but, it might be possible for WRITTEN code, bec. there's prob. only ONE written code - path, of writing something, etc etc . .

ps. This might include enumerations, also, so if I type in FPS, which is a singleton.performance enum value, for Get Monitor, I guess it writes this, after search FPS . .

Singleton.performance.get_monitor(0) . .?

Where 0 is, enum for TIME_FPS . .

So, it's just an idea, it started in visual script, bec. it can be quite 'difficult' to sort of, access complex engine systems or, methods, etc . . Idea was, one could type in FPS, and one got a list, then one could ' move ' it in, and it auto-set ups these boxes . . .

![Skærmbillede (1834)](https://user-images.githubusercontent.com/83387915/119408859-b465c300-bce6-11eb-9bc9-932d04ffb709.png)

Which is the same, as reverse code - completion, just in visual script . . . However, it might not be so easy in visual script, bec. one has to fill the boxes, or so . .

Anyway, this might only really be POSSIBLE, in written code, so either way, it's a simple suggestion, I thought it was ' fairly' neat, but I'm also TOTAL noob . . Thx, for your further consideration, can't really say, if this is all kinds of stupid, maybe SOME of it could be used, at least making this, for WRITTEN code, or so . . Thx . . . <3 . . .

**Comment by charlesmlamb** [comment]
Ok, so, want to keep it short, this is the idea, for visual script, where setting stuff up like GET singleton, is quite tough, took me six months to figure this stuff out, the correct boxes . .

<img width="1016" alt="Skærmbillede (1836)" src="https://user-images.githubusercontent.com/83387915/119410931-e3c9ff00-bce9-11eb-89cb-b03b9c08b8a6.png">

However, then we got to thinking, this might actually make more sense for GDScript, as there's one line of code, for any specific engine method, so on . . but, in visual script there are many ways to set up the boxes, for instance I can type in some property, inside a box, or make a constant, with a ' string ' value, and connect it that way . . so, for visual script it might be impossible, unless it was re-written, to work almost, like well GDscript, so it might only be possible, for ' written ' code . . .

It's very rough, and as always, as a 'total' noob, I have ZERO idea, if this is just ' impossible ' or, worse . . . That's why, it's an early idea, for ' pros ' to consider, say people that can 'write' code, etc <3

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
