### ISSUE TITLE
Proposal for making Godot more 'attractice' / useful for commercial projects / titles . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2769]
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
Well, did some thinking, right now the open source, spec. 100 % free aspect of Godot, means sort of, ' commercial ' use seems 'foolish', bec. it goes against the ' intent ', of the engine, or so . . So, how does one ' change ' that, in a way that does not compromise Godot, legally, etc . .

One way, would be to create a paid version of Godot, but a problem arises, since the core engine is 100 %, and that will never change, what can that be . . Here's ONE idea, and I know it'll get a lot of ' flack ', for even suggesting this, bear with me, the engine will still be free, as one wants, 100 % . . .

Sort of, one could make, for instance, a physical box, that had some ' neat ' stuff, and a USB, or so, with Godot on, it can be quite silly, like . .

![2021-05-23 1717](https://user-images.githubusercontent.com/83387915/119415268-8c2f9180-bcf1-11eb-8906-f90004bb094d.jpg)

So, if you ' buy ' the commercial version of Godot, for a ' modest ', fair amount, you get something, that people that use a free download, doesn't, ie. you get value and, a ' little ' deal . . It could be a Godot cap, something that the ' paid ' for the engine users got, that was THEIRS . . That would effectively make it a deal, it could also contain a poster, with say the Godot logo, or so . . So, you get something, others don't have, from the purchase . . .

Now, this might seem ' strange ', the trick isn't not to have a ' paid ' version of Godot, the 'real' problem is to set a price, that encourages fair, decent commercial use, and avoids users thinking, this is for more ' nasty ' stuff, etc . . For example, if the engine ' took ' 2000 dollars, for a commercial version, it'd be a ' nasty ' move, that would encourage people, ' inspired ' by the engine, to do nasty stuff . . That's what should be avoided, ie. not ' good ' . . . But, let's say a commercial version, that included a cap and, some 'goodies', cost 120 - 140 dollars . . That's a very low, modest price, for what you're getting, like the engine is ' worth ' more, but by making a ' nice ', decent commercial offer, it would send the message, we don't mind ' commercial ' use, just remember, it's for ' nice ', cool, competent, decent ' work ' . . It'd sort of mean, if there was a ' solid ' commercial title, Godot would be more useful for that, ie. it'd encourage fair, ' decent ' commercial use, without sending the message, this 'might' be used for 'dirty', greedy stuff . . . Basically, it'd be a 'deal' if you got something, nobody else had, say a cap, or a t-shirt, or so . . . That'd mean the ' commercial ' purchasers, would feel more ' included ', while only encouraging ' good ', decent commercial projects, ie. things that fit Godot . . It's a mistake to think all ' commercial ' use is bad, but it can be if it gets TOO greedy . . . By making an offer, for say a physical box, with a cap, or some things, can be ' insignificant ', you'd sort of ' get ' something, for the purchase, that was unique, etc . . .

I know this will get all kinds of ' anger ', it's been free for VERY long, but this is how you make the engine more ' attractive ' for commercial use, without inviting use, that sort of, is ' bad ' . . . Also, there are many long-term fans that might like to support the engine, by getting a ' physical ' box, a ' deal ', that was a bit ' different ', from the free download, ie. felt like a ' purchase ', I got stuff, things . . It could be a cap and, a lan-yard, that'd be enough for people to say, ' nice ', I got something . . :OO . .

The real problem isn't ' commercial ' use, in itself . . The problem is, one sort of sets a ' tone ', with the price, and if it's unfair, then people will buy the engine, and use it for unfair, ' bad ' stuff, say if the engine makers took 2500 dollars, for a physical copy, or ' pay for ' version . . The ' answer ' is, make something where you get something, nobody else has, ' your ' Godot cap or, t-shirt, so you got ' more ', than others, like a ' deal ', purchase . . .

And, make the price so nice, though there's a ' commercial ' aspect, it is modest and, ' fair ' . . .

Well, it's something to consider, it'd mean for instance, if there was a classy, ' cool ', great ' commercial ' title, then people that didn't want to be 100 % non - commercial, could use the engine for that, at the same time, it'd send a message, the engine encourages nice, decent ' commercial ' use, but not TOO greedy, or too corrupt use . . . That's where the 'big' problem is, in the engine appealing to 'unfair', bad commercial use . . There's a balance, between the two, if one makes a nice, decent offer, a ' fair ' price, then it will send a message, this engine can be about money, so long as it's fair, and ' modest ' . . .

Hope this makes sense, I know this is prob. divisive, so, well, it's an idea . . . :OO . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, right now Godot sort of pushes ' commercial ' use away, bec. of the entire FOSS system, it sort of ' looks ' down on commercial, at least it's like the engine makers are ' above ' it, see it as ' not ' important, so on . . . It's sad in the sense, that SOME commercial projects, actually aren't immoral, as such . . ie., classy, well - made, modest, competent commercial games, are actually ' quite ' good and, could more easily be made in Godot this way . . plus, it's mean one could download it for free, the ' exact ' same engine, the ' commercial ', say 140 dollars would include other stuff, like a nice box, a cap and, some ' stuff ' . .  Something that'd make you excited, when opening the box, and make you feel, I ' got ' something, nice, 'happy', ie, happy customers, ' deal ' makes sense, etc . . . Anyway, this could mean Godot would be used for many more commercial projects, attract the ' right ' kind of projects, that everyone agrees, this was not ' bad ' or, ' greedy ', so on . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, it's more a meta - suggestion, for making commercial projects feel more ' welcome ', in the engine, while making sure, it could still be a free download and, not encourage 'corrupt', or 'greedy' commercial use, ie. where it becomes ' immoral ', worse, etc etc . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Well, this is different, or so . . . 

### Is there a reason why this should be core and not an add-on in the asset library?
It's just a suggestion, I know it'll get all kinds of ' hate ', it's a starting point, for a ' constructive ' discussion, about how to make the engine ' sell ' the message, that FAIR, modest, honest commercial work, is not against GODot . . Thx . . . <3 . . .

**Comment by pycbouh** [comment]
Jasper, you've already made a proposal like that. #1475.

**Comment by charlesmlamb** [comment]
Oh, I forget, sometimes . . It's tough to remember all one's thoughts, or so . . <3
