### ISSUE TITLE
Add a menu option to restart the editor quickly

### ISSUE THREAD

**Issue by luislodosm** [godotengine/godot-proposals#2773]
### Describe the project you are working on
2D narrative adventure.

### Describe the problem or limitation you are having in your project
I have to frequently restart the editor, as I work with custom resources that are not automatically updated in the inspector when I modify their script.  I also need to restart every time I create a new custom class or put a new icon.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Put a quick editor restart option in the project menu.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`Reload Project`, below last option.

<img width="474" alt="Captura de pantalla 2021-05-25 a las 23 30 13" src="https://user-images.githubusercontent.com/63356898/119576711-302c4200-bdb1-11eb-8bd1-dd21239ab0ee.png">

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't know.

### Is there a reason why this should be core and not an add-on in the asset library?
I think it could be useful in a lot of cases.

**Comment by Calinou** [comment]
If anyone is interested in implementing this, note that Godot already supports restarting on exit. Search the codebase for `set_restart_on_exit`.
