### ISSUE TITLE
Make Inspector related nodes available for use

### ISSUE THREAD

**Issue by speeder** [godotengine/godot-proposals#2781]
### Describe the project you are working on
I am working on an editor for https://github.com/OpenTTD/OpenTTD game assets.

### Describe the problem or limitation you are having in your project
Since it is a game editor, I was hoping to create a interface similar to Godot itself, since it is a good interface, but some parts of the interface can't be done that way without seemly diving into GDNative code or complicated hacks.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The feature in question would be just make the Inspector-related nodes availble to be used in non-plugin projects, with them behaving like a normal node, instead of forcing the instancing from the singleton.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, same as any other node, except now you have EditorInspector and other related nodes available, maybe with another name to avoid issues with plugin authors.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't think it can be worked around in a few lines... right now the workaround would be litearlly to recreate the inspector from scratch, maybe including C++ code in the same way Godot itself was made.

### Is there a reason why this should be core and not an add-on in the asset library?
Godot famously claim that "Godot is a Godot game", yet you can't re-create Godot interface itself with the currently available nodes.

**Comment by Xrayez** [comment]
You're probably looking for #2063 which covers this use case there:

> * The Inspector which can generate a competent GUI for editing data purely from a selected Object and its list of property metadata.

**Comment by pycbouh** [comment]
This is already covered by the aforementioned #2063 and, more directly, by #2276.

> Godot famously claim that "Godot is a Godot game", yet you can't re-create Godot interface itself with the currently available nodes.

You can recreate the entirety of it, but you do need to actually recreate everything. There is limited reusability, this is true.
