### ISSUE TITLE
skip_navigational argument of list_dir_begin() should be true by default

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#2787]
### Describe the project you are working on
GDScript stuff.

### Describe the problem or limitation you are having in your project
Every single time I use `list_dir_begin()`, I pass `true` to `skip_navigational`. This method is used to traverse directory files, `.` and `..` are not valid files. Listing them is useless unless you are implementing custom file explorer (aka never, because we have built-in FileDialog).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
`skip_navigational` should be true by default, so I can do `list_dir_begin()` instead of `list_dir_begin(true)` every time.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Technically passing `true` is a workaround, but this is the problem itself.

### Is there a reason why this should be core and not an add-on in the asset library?
It's core method.

**Comment by Calinou** [comment]
I agree this should be the default behavior too.

It's kind of like `ls -a` listing `.` and `..`, and `ls -A` not doing so, yet everyone still uses `ls -a`… :stuck_out_tongue:
