### ISSUE TITLE
Separate command line arguments from engine and game/editor

### ISSUE THREAD

**Issue by reduz** [godotengine/godot-proposals#2797]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

It is often a problem that the engine takes command line arguments, but sometimes the editor does too (For specific tasks or plugins), and sometimes also the game does need it too.

It has been proposed to generate a more complex command line parsing so everything could be supported transparently, but my view on this is that this is a very complex task that will most likely result in clashes or, in a more complex and language-like command line syntax to please everyone.

Still, the problem is real and it requires a solution.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I believe we should support the `--` command line argument, which is standard on Unixes to signify the end of command line options. Whatever comes next, it's up to the editor and plugins to parse, or to the game while running.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Right now we have the `OS.get_cmdnline_args()` function. I propose we add `OS.get_cmdline_user_args()` for anything that comes after `--`. This way, from the user side, you are free to parse anything you want, however you want.

*As a side note we should probable rename those functions, as they no longer match the naming conventions we use*.

### Is there a reason why this should be core and not an add-on in the asset library?

Can only be implemented as core.

#### Short Q&A:

**Q:** Does this not affect discoverability?
**A:** The feature needs to appear in the documentation, but custom command line arguments are game specific, so it has no relation to discoverability.

**Q:** What if I add an editor plugin, can I make it appear on the command line?
**A:** No, when running godot --help, the major part of the engine is not initialized, so plugins won't load anyway. 

**Q:** Is it really too difficult to parse all arguments together, engine and command line?
**A:** Yes, because otherwise error reporting becomes very difficult (unknown options, malformed arguments, or even guessing the amount of arguments following a `--option <args>` syntax. Separating between engine and editor/game options is the cleanest possible way to do and standard in Unixes for this task.

**Comment by Calinou** [comment]
In any case, parsing the original command line arguments should remain possible so that custom positional arguments can still be supported by script. This is required for file associations to work in non-game applications such as Pixelorama or Material Maker. So `OS.get_cmdline_args()`'s behavior should remain as it is now;

**Comment by reduz** [comment]
@Calinou I think it should remain possible, but this also means that given the engine ones are set in stone now, we can much better validate them by detecting the invalid or malformed ones.

**Comment by Shatur95** [comment]
@reduz, thanks for looking into it! First of all - sorry, I didn’t know that the PR that I am still working on was not discussed properly and was based on a proposal that did not guidelines.

I have a suggestion about the implementation. We could move the functionality into a class. In Rocket.Chat you said that parsing logic not big enough. But the suggested approach have some advantages:
1. This approach is more extensible. This will make adding new arguments easier and safer.
1. Other projects / games will be able to reuse this code to parse arguments from `OS.get_cmdline_user_args()`.
1. Would make the implementation of `--` easier.
1. Code will be cleaner. 
1. We already have the implementation #44594 that could be used for it. It test covered and documented. We can discuss the API I provided and I will make the necessary changes.

**Comment by reduz** [comment]
@Shatur95 as I mentioned on RC. I think the current command line parser is fine as is, 400 lines of code is nothing and its very easy to understand, does not warrant making a more complex system.

For the user side, I think very few projects will require this, so having a reusable command line parser in the core engine taking up binary space is not something that we should be looking forward to. For user projects, an add-on can be simply downloaded.

**Comment by pycbouh** [comment]
The problem with leaving end users with "everything after `--`" will end up with people reimplementing a parser for those options every time for every project that needs it or having to rely on a third-party plugin to do this job. While this problem can be solved in multiple ways so customization may be nice to some, this solution also increases the barrier for its usage.

**Comment by lupoDharkael** [comment]
I think the actual parser is kinda messy, it is split in multiple parts of the main.cpp (`Main::start` and `Main::setup2`) and requires some global variables to access intermediate information for other parts of the engine initialization or command parsing. I don't think that's simple or easy to maintain. When I implemented the code for my proposal it was kinda hard to decouple that logic and replace the code.
The actual parser code can't validate as the parsing is split in multiple stages and you can't know if something might be valid syntax for the second pass. I wish Godot had command validation because sometimes I use some engine commands and use the wrong one because I don't know all by heart, in some cases the engine just starts ignoring the wrong commands.

**Comment by hinlopen** [comment]
> I think the actual parser is kinda messy, it is split in multiple parts of the main.cpp (`Main::start` and `Main::setup2`) and requires some global variables to access intermediate information for other parts of the engine initialization or command parsing. I don't think that's simple or easy to maintain. When I implemented the code for my proposal it was kinda hard to decouple that logic and replace the code.

I have been working on refactoring main.cpp recently and it is definitely hard to decouple the argument parsing. It kind of requires most of the setup in main.cpp to be rewritten, but that just proves that it is necessary to do so. However, I do not think it is strictly necessary to replace the argument parsing with a generic command line parser. That is only necessary for the API, which can be implemented with a plugin following this proposal.

**Comment by SaracenOne** [comment]
So, on our project, one of the things we allow you to do is set a commandline for a scene file we use a multiplayer game map. However, the default Godot behaviour is that any path to a scene passed anywhere will be treated as the main scene, which in this instance we don't want, so we pretty much straight up disabled the 'main scene' functionality from our branch as a quick hack. Something like this seems like a better more universal solution though, having an explicit area where we are free to parse any abitrary commandline arguments would be good for situations like this.

**Comment by Calinou** [comment]
> However, the default Godot behaviour is that any path to a scene passed anywhere will be treated as the main scene, which in this instance we don't want, so we pretty much straight up disabled the 'main scene' functionality from our branch as a quick hack. Something like this seems like a better more universal solution though, having an explicit area where we are free to parse any abitrary commandline arguments would be good for situations like this.

I don't see a way to resolve this from the engine side, apart of adding a project setting that needs to be read before the custom scene to run is determined.

**Comment by Shatur** [comment]
I also want to add that a CLI parser is almost always needed for dedicated servers. Since we have a proposal for dedicated server export in #2756, I think it worth to have a parser that can be used for this as well.

**Comment by Calinou** [comment]
Note that if we don't want to require using `--` for user arguments, we can also encourage using a custom prefix for user-made command line arguments. `+` is a common choice for this purpose.

While it's not the prettiest solution, it's a fairly established one and doesn't require using a `--` separator (which some people may find cumbersome if they're only specifiying *game* arguments). This is pretty much the solution id Tech/Source went with. The only usability risk I see is people trying to use `-` for options that should be specified with `+`. If we print an error and abort when an unknown engine command line argument is passed, then this pitfall can be avoided.

Note that to keep supporting file associations, *positional* command line arguments (i.e. those without a prefix) should still be parsable by the game logic. (There can be several positional CLI arguments if you're opening several files at once with a program, separated by spaces.)

In the example below, the first two options are *engine* options, while the third option is a *game* option. The engine is not aware of the game option existing, but the game logic is allowed to parse it:

![image](https://user-images.githubusercontent.com/180032/180517092-2f1f72a3-b91c-49f5-8dbe-ff89465b98e7.png)

**Comment by reduz** [comment]
@Calinou the + prefix is useless because Godot will not know what to do with the value coming after it
