### ISSUE TITLE
Support multiple Shortcuts on Button

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#2801]
### Describe the project you are working on
Logic game
### Describe the problem or limitation you are having in your project
I cannot give my Button multiple Shortcuts via the Insepctor!
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
You would be able to add as many Shortcuts to a Button as you want.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just a +-Button or so, idk. If there are any such things yet where multiple resources are possible at once, then just use exactly that.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
I am not sure.
### Is there a reason why this should be core and not an add-on in the asset library?
Yes, it can be used for every project.

**Comment by LightningAA** [comment]
Would this be solved by https://github.com/godotengine/godot/pull/48009?

**Comment by MaaaxiKing** [comment]
Yes, it would be solved there.
