### ISSUE TITLE
Implement AMD FidelityFX Super Resolution (FSR) in the Vulkan renderer

### ISSUE THREAD

**Issue by mahdisml** [godotengine/godot-proposals#2809]
### Describe the project you are working on
3D Horror Game
### Describe the problem or limitation you are having in your project
low FPS problem
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
AMD FidelityFX Super Resolution (FSR) 
FidelityFX Super Resolution is a spatial upscaling technique, which generates a “super resolution” image from every input frame. In other words, it does not rely on history buffers or motion vectors. Neither does it require any per-game training. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
https://gpuopen.com/fsr-announce/
### If this enhancement will not be used often, can it be worked around with a few lines of script?
idk
### Is there a reason why this should be core and not an add-on in the asset library?
You could see FSR as an Rendering enhancement and I don't think changing the rendering as an add-on is such a good idea. Unreal Engine and Unity3D added DLSS in core ! :)

**Comment by Calinou** [comment]
Some comments:

- It's not the first time AMD is trying their hand at sharpening/upscaling. [FidelityFX CAS](https://gpuopen.com/fidelityfx-cas/) is one prior example of that, and it includes an optional fast upscaling filter ([proposal](https://github.com/godotengine/godot-proposals/issues/1519)).

- FSR will not be open sourced by AMD right away. It will be integrated into 10 AAA games or so in June, then it will be open sourced a few months later.

- FSR works with Vulkan, Direct3D 12 and Direct3D 11. No OpenGL support has been mentioned, which means it can't be backported to the `3.x` branch.

- FSR does not require motion vectors, but it *may* require the image to be antialiased using a temporal method beforehand (or perhaps MSAA) to look good. FXAA most notably is not a temporal antialiasing method. Whether this is true is unknown – it's just guesswork right now :slightly_smiling_face:

- FSR is probably not a machine learning-based method, which means it differs a bit from something like [Anime4K](https://github.com/bloc97/Anime4K) (which also works without motion vectors).

- In Godot, there are plans to expose motion vectors in the future (along with temporal antialiasing), but probably not for 4.0.

**Comment by Calinou** [comment]
FidelityFX has been released in some AAA games, although its source code isn't available yet.

[GPUOpen website](https://gpuopen.com/fidelityfx-superresolution/) says:

> The source code for FidelityFX Super Resolution 1.0 will be coming to GPUOpen in mid July!

**Comment by pycbouh** [comment]
> Unfortunately, Intel IGPs

Well, GamersNexus claims that it should work on the new dedicated Intel GPU, and it definitely works on the new AMD Ryzen 5700G, the one with the iGPU, so maybe it will work those too.

**Comment by mrjustaguy** [comment]
Runs on Kepler GPUs, Tested - Nvidia Quadro K2000 in Dota 2, Does indeed Upscale, and improves performance by ~5-15% for a roughly same Picture result on 1080p, However Seems to scale better with higher resolutions (Quality-Performance scaling that is, meaning Upscaling to higher Resolutions will yield better performance for roughly the same Visual Quality as non upscaled rendering)

**Comment by Zireael07** [comment]
AMD Fidelity FX was just open sourced: https://github.com/GPUOpen-Effects/FidelityFX-FSR

**Comment by Calinou** [comment]
> AMD Fidelity FX was just open sourced: [GPUOpen-Effects/FidelityFX-FSR](https://github.com/GPUOpen-Effects/FidelityFX-FSR)

Note that for this to be useful in Godot, we need to implement decoupling of the 3D rendering resolution from the viewport size. This way, 2D elements can keep their native resolution (and this will also pave the way for dynamic resolution scaling, which *can* work together with FSR).

**Comment by AlfonsoGrimaldo** [comment]
I don't know why but it works on my GTX 960.

**Comment by Calinou** [comment]
> I don't know why but it works on my GTX 960.
> ![Sin título](https://user-images.githubusercontent.com/48926464/125843838-f360b351-a232-4156-b33a-fdde5a8f95df.jpg)

It works on Maxwell GPUs too, but it will use a slower FP32 (full precision) code path instead of the faster FP16 (half precision) code path.

**Comment by AlfonsoGrimaldo** [comment]
> > I don't know why but it works on my GTX 960.
> 
> According to the [developer presentation](https://raw.githubusercontent.com/GPUOpen-Effects/FidelityFX-FSR/master/docs/FidelityFX-FSR-Overview-Integration.pdf), FSR works on Maxwell GPUs too. However, it will use a slower FP32 (full precision) code path instead of the faster FP16 (half precision) code path. Both look pretty much identical.

I'm happy to read that, something is better than nothing.

**Comment by mrjustaguy** [comment]
FSR Does run on Kepler GPUs too, but it's performance gains are not very large as it takes a bit of computation, but do note that FSR can have a negative performance effect if drawing pixels is just cheaper than upscaling (which isn't common, outside of very simple graphics levels)
