### ISSUE TITLE
Align Camera with editor view.

### ISSUE THREAD

**Issue by thecodeah** [godotengine/godot-proposals#2819]
### Describe the project you are working on
Irrelevant.

### Describe the problem or limitation you are having in your project
Not necessarily a limitation, it'd just be a useful editor shortcut/option.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Sometimes you want to quickly add a Camera to your 3D scene and make it look at a specific angle and position. At the moment you have no choice but to move/rotate it manually with the gizmo arrows and loops or to change the positional/rotational values in the properties section. It'd be useful if there was a way to make the Camera (Or any selected node for that matter) match the exact position and rotation of the Godot Editors 3D view.

This is already a feature in Unity, and it can be used with the CTRL+Shift+F shortcut.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Set the position of the selected node(s) to the position of the Editor Views camera.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes.

### Is there a reason why this should be core and not an add-on in the asset library?
It's lightweight, easy to implement, and might save a life some day.

**Comment by KoBeWi** [comment]
This already exists in the Perspective menu:
![image](https://user-images.githubusercontent.com/2223172/120652346-fbd71680-c47f-11eb-8e0c-4e8267a008cf.png)
