### ISSUE TITLE
Editor project data should be stored in project folder, not in \Godot Engine\editor_data\projects

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot-proposals#282]
**Describe the project you are working on:**
Not applicable.

**Describe the problem or limitation you are having in your project:**
Moving around project folder and renaming it resets everything about project's editor state, as a new `editor_data\projects` is generated based on path and name. This also makes it impossible to store that folder in VCS, which can be useful for personal projects.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It is a common practice among programming software to store state for each project inside the project folder, in a file, like `.editorconfig`, or under a subfolder, like `.idea`, `.vs`, `.git`, `.hg`, etc. This makes project folder a fully contained environment to start working on the project.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Not applicable.

**Describe implementation detail for your proposal (in code), if possible:**
There are two ways this can be implemented:

* As a default behavior
  1. When creating a new project, setup a `.godot` folder inside the project folder immediately
  2. When opening an existing project, look for `.godot` folder inside the project folder
  3. If none is present, check the old path `editor_data\projects` for a pre-existent folder in old form

* As a project setting
  1. When creating a new project, allow user to check whether to store editor data locally or in `editor_data\projects`, and create the corresponding folder (I suggest setting the checkbox to TRUE by default)
  2. When opening an existing project, check `project.godot` for setting and then look for the corresponding folder
  3. If the folder does not exist, create it
  4. If the setting does not exist, assume default behavior, save setting and create the corresponding folder
  5. When changing the setting from within the editor, move current folder's content into the new folder, save setting, then ask the user to restart the editor (I assume, this is required)

I understand, there might be a problem when opening the same project with different versions of Godot, as currently each Godot folder stores its own settings for each project. If this is important, some sanity checks must be implemented, when working with local editor folder. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it's not a part of user space.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a part of internal editor logic.

**Comment by Xrayez** [comment]
Note that you can run Godot in a [self-contained](https://docs.godotengine.org/en/2.1/development/compiling/packaging_godot.html#self-contained-mode) mode, but it only works per binary, not per project.

**Comment by pycbouh** [comment]
> Note that you can run Godot in a [self-contained](https://docs.godotengine.org/en/2.1/development/compiling/packaging_godot.html#self-contained-mode) mode, but it only works per binary, not per project (this is more useful if you do depend on custom C++ modules to be compiled with your project).

Huh, I guess I am actually running it in self-contained mode, and I've had no idea. I use Godot via Steam, and it seems this is why self-contained mode exists in the first place.

As I understand, in non-self-contained mode Godot uses `AppData` or `home` directory instead of `editor_data`, but this still separates editor settings from the project folder. I guess, my initial proposal is partially incorrect as I assume that `editor_data` is the only place that Godot uses to store editor settings for projects, when in fact there are a couple of such places. This is undesirable either way, in my opinion. Though this branching behavior should be considered, if my proposal is implemented.

**Comment by aaronfranke** [comment]
See also: https://github.com/godotengine/godot/issues/23368

Might be indeed worth making a single ignorable `.godot` folder and putting everything inside that.

**Comment by pycbouh** [comment]
So, it seems that moving an `editor_data\projects\<path>_<md5>` folder into a `<project_root>\.godot\editor` is a matter of just a couple of changes in `editor\editor_settings.cpp`.

I think I can do it, but I need to know the following:
* Do we make `.godot` folder in project root the default and only behavior going forward, or is it up to personal preference of developers?
* Do we need a fallback behavior for existing projects? What would be the strategy here?
* Is there any catch with creating a new hidden folder in project root? It does not show up in Godot Editor, but maybe it needs to have some special treatment somewhere else in code? Are there any concerns for the Mono build?

**Comment by tinmanjuggernaut** [comment]
I've had my editor viewport get messed up as the camera position went into the millions and could not be snapped back. It took a while to find the settings hidden away in obscurely named, project specific folders under AppData. All project specific settings should be self contained inside the project folder.

**Comment by nicolasdiehl** [comment]
I just added a singleton of an external logger script to my project settings, pushed to git, switched to my other workstation, checked the progress out, expected it to be running fine. But instead I had to add the singleton again. Please add this, preferably as default behaviour.

**Comment by Calinou** [comment]
@nicolasdiehl The list of singletons is stored in `project.godot` which is in the project folder. If it's not synchronized across machines, the issue must be coming from somewhere else.

**Comment by pycbouh** [comment]
So, should we do this now, since import and mono folder changes were merged?
