### ISSUE TITLE
Make Viewport extend Spatial instead of Node.

### ISSUE THREAD

**Issue by DrAlta** [godotengine/godot-proposals#2825]
Trying to implement object highlighting as described in https://www.youtube.com/watch?v=SMLbbi8oaO8

Describe the problem or limitation you are having in your project
camera's only render to the nearest viewport above the. If you put a viewport above them than it breaks the transform hierarchy so if yo want two camera at the same place you can't just have the two camera's children of the same node and the move that parent node. This also breaks using RemoteTransform(as reported @ https://randommomentania.com/2019/07/godot-color-mask-tutorial/
### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Could just make both cameras the child of one node and just move that parent node

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is an alternative to #2824 

Add a Viewport in a scene and it's children won't be sent back to the origin

### If this enhancement will not be used often, can it be worked around with a few lines of script?
yes
### Is there a reason why this should be core and not an add-on in the asset library?
Needs to change the class hierarchy

**Comment by pycbouh** [comment]
Viewports aren't related to 3D space, they cannot extend Spatial. On top of that, in 4.0 they are basically system windows.

**Comment by aaronfranke** [comment]
This proposal can't be implemented, so it isn't actionable, closing. Discussion on how to solve the problem mentioned here can be continued in the other proposal.

**Comment by aaronfranke** [comment]
This proposal can't be implemented, so it isn't actionable, closing. Discussion on how to solve the problem mentioned here can be continued in the other proposal.
