### ISSUE TITLE
Question: Does default RPC authorization on server protects against client_id spoof?

### ISSUE THREAD

**Issue by ka23ppa3** [godotengine/godot-proposals#2828]
### Describe the project you are working on
Multiplayer game with multi-room server and authorization

### Describe the problem or limitation you are having in your project
rpc client_id might be known for all players in room(not only server) in case if its not spoof-protected players with modified clients might be able to send rpc requests from any players and harm to gameplay.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
If its not protected can it be fixed by default, without implementing additional "session-secret" game-side, so all multiplayer games will be more protected against cheaters?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Client id will be still known for anyone but once player connected to room it will get his unique session-secret from the server and all rpc calls will include this session-secret which will automatically checked by engine before the call will invoked.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes, its simply can be implemented by creating session-secret in game logic, but better to have such protection(or even better if we talking about p2p games, which are not centralized) by default so games developed in Godot will be more protected against some sorts of cheating by default.

### Is there a reason why this should be core and not an add-on in the asset library?
Same as above

P.S: I did not checked engine code, please sorry me if my question is kindly stupid.
Thanks.

**Comment by Calinou** [comment]
cc @Faless 

PS: Please use the [Godot contributors chat](https://chat.godotengine.org) for such questions instead of the proposals workflow.

**Comment by ka23ppa3** [comment]
> cc @Faless
> 
> If you need network encryption, use [DTLS](https://godotengine.org/article/enet-dtls-encryption).
> 
> PS: Please use the [Godot contributors chat](https://chat.godotengine.org) for such questions instead of the proposals workflow.

Thanks, I will ask any next question in Godot contributors chat. I already seen that DTLS was implemented in Godot 4.x, but the problem is that Im talking about 3.x and we cannot be sure when 4.x will stable enough for production. Its a good policy to include security updates and small improvements in actively used branch and now we are on 3.x. Thanksfully this is type of feature which can be implemented game-side if needed.

**Comment by Calinou** [comment]
@ka23ppa3 DTLS support was backported in Godot 3.2.2 and later.

**Comment by Faless** [comment]
In general the peer ID is assigned by the network peer in use, and it's validated before performing RPCs.
So the peer ID itself cannot be spoofed, but depending on the network peer, the IP address could be spoofed instead (resulting in an invalid RPC being called).
This is mostly relevant for ENet, on network that are susceptible to IP spoofing.
If you are worried about that you can use DTLS.
