### ISSUE TITLE
Folded state in Node tree should not be stored in .tscn

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot-proposals#283]
**Describe the project you are working on:**
Not applicable.

**Describe the problem or limitation you are having in your project:**
Folding state of node branches in editor Scene tab is persistent, and is stored in `.tscn` file under
```
editor/display_folded = true
```
When using VCS, this causes unnecessary diffs when adjusting the scene tree for immediate needs. As this is an editor setting, it should not be affecting the state of the project, which can be shared between multiple parties.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Godot editor has its own place to store editor state within `editor_data\projects` folder. By the looks of it, it already stores folding state for object properties within `*-folding-*.cfg` files. Same should be implemented for scene tree.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Not applicable.

**Describe implementation detail for your proposal (in code), if possible:**
As this behavior seems reasonably close to the object properties, implementation should be similar.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it's not a part of user space.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a part of internal editor logic.

**Comment by Calinou** [comment]
Which Godot version are you using? This should no longer be the case since 3.1 thanks to https://github.com/godotengine/godot/commit/e647342140d8eb960b2a72d83b4b86e43aef4fc7.

**Comment by Xrayez** [comment]
Isn't it already implemented though? I do have outdated `editor/display_folded = true` in several of my old scene files which were never re-saved since 3.0 or so, but once you save them in 3.1/3.2 they disappear.

**Comment by pycbouh** [comment]
No, this actively happens in Godot 3.1 (Steam version), and I have never used older versions.

**Comment by Calinou** [comment]
@Xrayez This is about the node tree, not the inspector. Perhaps it's handled differently there.

**Comment by aaronfranke** [comment]
In the meantime, here's a [workaround](https://github.com/aaronfranke/Linux-tools/blob/master/all-distros/bash_aliases#L11) for Bash users (Mac and Linux):

    alias tscnnoeditor="find . -name '*.tscn' -exec sed -i '/^editor\//d' {} \;" # Remove "editor/display_folded"

**Comment by KoBeWi** [comment]
This was changed in 3.2.

**Comment by pycbouh** [comment]
@KoBeWi Can confirm, that this is improved in 3.2 (beta3). Scenes created in 3.2 save and restore correctly, while `.tscn` file is not polluted by unnecessary data. Scenes created in 3.1 when opened in 3.2 do not restore their folded state from `.tscn`, but are converted to the new format on the next save, removing the line from `tscn` file.

Closing this, thank you!
