### ISSUE TITLE
Add an option to TransformTrack to select between local and global transformations

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#2831]
### Describe the project you are working on

3D avater game

### Describe the problem or limitation you are having in your project

The current Godot does not have a retargeting system. There is a #2619 about this.

As mentioned in the above issue, a difference in rest rotation can break the animation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The general solution to this is to use retargeting, but if you change the rest rotation of a model, all systems that reference the rest rotation will also have to consider retargeting.

One way to solve the rest rotation difference is to describe the bone deformation in the animation as a global deformation. This is the method used by the MMD software.

This makes it possible to share animations between models that look similar but have different rest rotations without changing the rest rotation of the model. In other words, you can't share animations between T and A poses have different rest rotations, but you can share animations between T poses or between A poses have different rest rotations.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There is small demo video
https://www.youtube.com/watch?v=TVv_D0XSxrc

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is not possible to share animations between models with different rest rotations while maintaining the rest rotation of the model. It is possible to deal with this by converting animation resources every time the model is loaded, but this is not a good idea in terms of performance and maintainability.

### Is there a reason why this should be core and not an add-on in the asset library?

It is necessary to change the AnimationPlayer and AnimationTree.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/1191.

**Comment by TokageItLab** [comment]
@Calinou I understand what they want to do in #1191, but I think the behavior will be quite different when applied to Node3D and when applied to bones.

In #1191, what they want is similar behavior to root motion, but what I'm proposing in this issue is to deform bones without rest rotation. They can coexist, but it can be confusing.

I think it's a good idea to separate Skeleton from SkeletonTrack. Implementation of SkeletonTrack is also preferred by @fire.

**Comment by TokageItLab** [comment]
It will be superseded by #3379.
