### ISSUE TITLE
UI Debugging: Longest Translationtext

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot-proposals#284]
**Describe the project you are working on:**
Economy based Prototype with a LOT UI.
**Describe the problem or limitation you are having in your project:**
I'd like to simply check how all of my UI looks, when the longest Translations are applied. I have to manually run a script on the csv file to create a language based on the longest translations.
**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If it would be an built-in feature, then the workflow would be better, because one can not implement it as a script, since you can't access the the Translations as a whole.
**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
1. Debug -> Check UI Translation Testing
2. Run Game
3. Open your UIs and check them visually

**Describe implementation detail for your proposal (in code), if possible:**
I run [my script](https://github.com/HaSa1002/tool_make_longest_translation/blob/master/make_longest_translation.py) on the csv file and save the content into a language I don't use (i.e. aa). I am not sure if it would be better to run an alogorithmn on the TranslationServer instead.
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes. See the script. It's about a workflow improvement.
**Is there a reason why this should be core and not an add-on in the asset library?:**
One can not implement it as a script, since you can't access the the Translations as a whole.

**Comment by Jummit** [comment]
You forgot to fill out

**Is there a reason why this should be core and not an add-on in the asset library?**

**Comment by HaSa1002** [comment]
> 
> 
> You forgot to fill out
> 
> **Is there a reason why this should be core and not an add-on in the asset library?**

Oops. I defintily do Godot work to late in the night.

**Comment by HaSa1002** [comment]
superseeded by #1844
