### ISSUE TITLE
Add properties to control physics nodes' behavior when paused

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot-proposals#2843]
### Describe the project you are working on

Godot Engine

### Describe the problem or limitation you are having in your project

With https://github.com/godotengine/godot/pull/46191, objects process mode can be individually controlled, so nodes and their children can be all disabled at once. But it still doesn't affect physics behavior, because all physics nodes are just affected by whether the whole physics simulation is running or not.

This causes limitations in some scenarios:
- There's no easy way to switch physics on and off for a given physics body (all children included).
- Soft body simulation can't be disabled individually (it can only be hidden)

See https://github.com/godotengine/godot-proposals/issues/1835 for the original issue the object process mode PR was addressing.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This proposal is about adding options to physics-based nodes to select their behavior when paused, so when some nodes are disabled and they are not processing game logic, they can also be treated differently in physics, from not interacting at all to being static.

Project settings would also have default settings for different types of physics nodes, so it's easier to setup a unified behavior for a game.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

* `PhysicsBody2D`/`PhysicsBody3D` pause behavior options:

**DEFAULT**: use default project settings.
**NOTHING**: doesn't do anything special when paused. When the whole scene tree is paused, all rigid bodies will still stop being ticked and _physics_process won't be called.
**MAKE_STATIC**: change to static when paused, change back to dynamic when unpaused. This option doesn't affect static bodies, of course . While static, motion functions like `move_and_collide` or `move_and_slide` don't affect the body and it can't be pushed by other objects.
**DISABLE_PHYSICS**: disable the physics simulation when paused, re-enable when unpaused. It won't be detected by other objects while disabled.

* `Area2D`/`Area3D` pause behavior options:

**DEFAULT**: use default project settings.
**NOTHING**: doesn't do anything special when paused. When the whole scene tree is paused, all areas will still stop detecting objects and be detected.
**DISABLE_PHYSICS**: disable the physics simulation when paused, re-enable when unpaused. It won't detect or be detected by other objects while disabled. It will trigger exit events when disabled and enter events when re-enabled.

* `SoftBody3D` pause behavior options:

**DEFAULT**: use default project settings.
**NOTHING**: doesn't do anything special when paused. When the whole scene tree is paused, all soft bodies will still stop being physically simulated.
**DISABLE_PHYSICS**: disable the physics simulation when paused, re-enable when unpaused. It won't be detected by other objects while disabled.

* Project settings:

Default PhysicsBody pause behavior: **NOTHING**
Default Area pause behavior: **NOTHING**
Default SoftBody pause behavior: **NOTHING**

The default settings are all **NOTHING** because it's the most optimized behavior when pausing the whole physics simulation. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be done only with cumbersome workarounds, and the goal is to make it easy to use in any project.

### Is there a reason why this should be core and not an add-on in the asset library?

It's based on a core functionality and affects all physics nodes.

**Comment by reduz** [comment]
This looks awesome! Here is some feedback:

* I would have the property named "on_disable" and have modes: KeepActive, MakeStatic, Remove
* I would not use a global default, I think MakeStatic makes the most sense, Remove is probably less useful.
* There is a situation I am not sure how to account for. If you set the global pause mode, the physics will stop.. but don't really want to do anything to the physics. I think the logic should probably somehow check whether process mode is active but paused and then ignore the paused

**Comment by lawnjelly** [comment]
This is much needed, the ability to throttle down physics on some objects but not others - especially throttle down objects not close to the player area on a map.

I can see it is a difficult problem to solve because of the boundary, when an active object interacts with an inactive physics object. The thing to avoid is a 'glitch' where an object is respawned on a boundary and an active object is interpenetrating, and suddenly gets a big physics force applied. Maybe making the objects static on the boundary is a good solution, and then possibly completely deactivating them at a second boundary, where there is no possibility of interaction with moving physics objects. Maybe this can be done already though without pausing - but I wanted to give an example of real life use case.

**Comment by Calinou** [comment]
> This is much needed, the ability to throttle down physics on some objects but not others - especially throttle down objects not close to the player area on a map.

See also https://github.com/godotengine/godot-proposals/issues/439. Although I think this should be addressed separately from pausing.

**Comment by pouleyKetchoupp** [comment]
@reduz 
> I would have the property named "on_disable" and have modes: KeepActive, MakeStatic, Remove

Agreed, that seems more explanatory.

> I would not use a global default, I think MakeStatic makes the most sense, Remove is probably less useful.

Ok, it makes sense not to use a global default, but in this case I would put Remove as the default. Disabling all physics interactions by default seem like the more intuitive expectation and the most common use case.

> There is a situation I am not sure how to account for. If you set the global pause mode, the physics will stop.. but don't really want to do anything to the body. I think the logic should probably somehow check whether process mode is active but paused and then ignore the paused

Yeah, I was planning to do nothing as the default for this reason, but it does seem better to handle this case as an exception.

It would probably work well to just ignore the disable mode in physics when the whole tree is paused, since physics won't be processed in this case.

@lawnjelly 
Thanks for pointing out this use case, it makes a lot of sense! MakeStatic would be indeed useful for this scenario.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/49834.
