### ISSUE TITLE
Add a waitx_frames node to visual script . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2845]
### Describe the project you are working on
A Tomb raider game, working on making good animations atm <3

### Describe the problem or limitation you are having in your project
Right now, there's a wait node, that uses seconds . . And, there's a node, called waitframe, that only waits one frame . . The problem is, I'd like to tie my animations, to frame - delays, mostly for attack animations, but also for accurately linking animations, and it's often used, in martial arts titles, where each attack has certain frame - states, ie. block lasts 12 frames . . Right now, I think I can do that, by linking 12 waitframe nodes, but it's a bit weird . . And, it's quite ' frustrating ' to well, have to find out what floating point number 12 frames exactly equal, taking rounding up, down into consideration . . Maybe I haven't been smart enough, about it :(( . . .

<img width="700" alt="2021-06-09 1233" src="https://user-images.githubusercontent.com/83387915/121339611-f31e8e80-c91e-11eb-97bc-162b367b5f01.png">

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I'd suggest you make so, the ' wait ' either was about frames, since it's more accurate, for precise 'frame-to-frame' control or, added an input port, so one could input a constant, that was a float = 1 / 60, and that'd give 1 frame wait . . I realize having a wait 1 sec, ie. second unit is a use - case, but as a big 'nerd', I'd rather work in frames . . I suppose maybe problem is, for _process that time is variable, and in _physicsprocess it is not, atm I'm making stuff in _physicsprocess bec., it's easier . . and, give me frame-to-frame control, which is nice, ie. more 'math', logic, etc etc . . .

Sigh, not sure how to fix this, but having a waitxframes node, would be nice, even if it'd only work for _physicsprocess, since my animations are in frames, but also since I want martial art like code, to control my stun-lock anims, attack anims, so on, so it's more ' controlled ' or, math-oriented . .

Not sure this is easy, just really ' tired ' that, I can't work in my preferred unit, frames, instead of having to type floating point numbers, that will never ' perfectly ' fit the time or, frame - sequence . . . :((

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add a box, that allows one to ' wait ' 12 physics frames, or, at a constant FPS . . As a total noob, I'm some-what ' confused ' this isn't here already, wanted to ask, since I'd much rather work in a frame-accurate ' code ' world, thx . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I'm not sure, atm one can't input a flt in the wait box, so I'll have to constantly calculate, what say 17 frames is, at 60 FPS, instead of just making a constant, and divide by 60 . . .

![2021-06-09 1243](https://user-images.githubusercontent.com/83387915/121340862-5a890e00-c920-11eb-8861-51ab2ff92268.gif)

I'm starting to understand, that I have so little experience, with Visual script, in 'any' engine that, I don't really know what's best . . . I guess my question is, can something be done, so one can work accurately in frames, to get more ' control ' over, the code, Thx . . . :OO 

### Is there a reason why this should be core and not an add-on in the asset library?
I'd use it all the time, instead of the wait, in seconds . . .

**Comment by charlesmlamb** [comment]
what, oh yea <3 lol . . .

Well, was just thinking about it, want to have 'frame accurate' movement and, combat . . Ok, I'll try, this ' stuff ' is tough . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
