### ISSUE TITLE
Godot 4's path towords .NET6 ecosystem?

### ISSUE THREAD

**Issue by JimFFM** [godotengine/godot-proposals#2851]
### Describe the project you are working on
Currently I (aka [@GeorgeS2019](https://github.com/godotengine/godot-proposals/issues/2333#issuecomment-855061301) am using Godot as the main 3D development IDE for[ a Virtual Collaboration platform](https://youtu.be/spf_D7EMMs0?t=103) to address the challenges posed by the rapid diversification of COVID-19 mutant variants that, if uncheck, could compromise the progress made by vaccination.

![image](https://user-images.githubusercontent.com/59052120/121574595-b76eec00-ca26-11eb-8582-a368a35354d3.png)

### Describe the problem or limitation you are having in your project
The project requires Godot to be not just another game engine for game developers but be democratized and scalable as tool for non developers using the latest AI. In other words , godot is a tool for the expression of 3D opinions for non game developers. Since I am a .NET developer and azure cloud architect, it is important to understand how Godot team will define a path towards .NET6 ecosystem.
 
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The segment of Godot community who is passionate of Godot as .NET 3D engine, for the purpose of game or non game, need to define consensus on milestones how Godot 4 will eventually be part of the .NET6 ecosystem as defined with the diagram below.

![image](https://user-images.githubusercontent.com/59052120/121574094-37e11d00-ca26-11eb-95b0-81106cd93441.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I will add more later, based on the discussion this proposal trigger.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I will add more later, based on the discussion this proposal trigger.

### Is there a reason why this should be core and not an add-on in the asset library?
I will add more later, based on the discussion this proposal trigger.

**Comment by pycbouh** [comment]
> need to define consensus on milestones how Godot 4 will eventually be part of the .NET6 ecosystem as defined with the diagram below.

Fortunately, the plans are already outlined and can be discussed here: https://github.com/godotengine/godot-proposals/issues/2333
