### ISSUE TITLE
Add options to customize graph nodes further in Godot 4 . . 

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2852]
### Describe the project you are working on
A Tomb raider game, really ' complex ' . . . Climbing mechanic, etc . . .

### Describe the problem or limitation you are having in your project
Ok, atm Godot 4 ( latest build ) is looking better, in basically every SINGLE way, for Visual script ! ! . . So, amazing job, I give 9.8 / 10 :DD . . But, I have a small request, maybe for slightly better customization, that's all . . . I really, really like the new rounded boxes, and one can set the rounding to 0, so one can make nice graphs . . Wanted to ask for two more things, nothing big . . .

1. That can make the 'inside' of the boxes not be round, bec. it makes it a 'bit' hard, to read the text, when it's not on a horizontal line . . . This . . .

<img width="988" alt="Skærmbillede (1884)" src="https://user-images.githubusercontent.com/83387915/121676906-7f62ba00-cab5-11eb-982d-6e9b64e01ef3.png">

I sort of wish, that didn't become ' rounded ' bec., it sort of make it ' confusing ', to the read name of the box, but it's tough to complain, it's already super - super cool . . . The last thing I'd like, was to be able to set rounded value of top of box and, also the lower part, so one could really customize it . . . I know by now, I have almost no idea, what really ' works ' for a video - game engine, in the sense, I'm a complete noob . . . But, I think I made one proposal, that the ' theme ' editor became well, ' Advanced settings ', like in projects settings, for the ' Editor settings ' and, I was hoping this could be in advanced settings, as settings . . . It's really a small thing, but well, I work almost 100 % in visual script, and for that reason, I need a really good, ' efficient ', nice interface, with as little clutter, or well, ' confusion ', ie. difficult to read stuff, etc etc . . So, hope you will consider it, also for visual shaders . . :OO :OO . . .

2. Can you maybe add, so one can set box border, to more than 2 pixels, I was hoping 3 - 4 . .

I know you're working very hard, on Godot 4 . . But, I wanted to ask before Godot 4.1, bec. right now somebody updated all this code, and MIGHT be able to implement it, without re-reading all the relevant code again, that said if all we get is what's there, it's hard not, to be VERY excited, so, just, thank you, from a visual script + visual shader user, stunning job . . <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, I'm hoping Godot 4, not sure what's gonna happen, will get access, to customize it more . . I know few people use it, but since I use it, for a TON, of work . . It's really important the general ' experience ' is both fun, and nice . . Not sure if now is best time, was thinking since someone recently re-did the graph editor, it was well easier to ask now, than wait after Godot 4, in sense, that someone would have to re-read all the code, Thanks . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Like above, Visual script is already looking amazing, new colors, it's just COOL . . but, wanted to ask for these features, as someone who works in it for many hours, then the ' small ' details, and problems become important, in sense, well small frustrations can, build up and, so on, Thanks . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Can't re-write the engine, atm . . :OO . . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, this would impact visual script, but also work in visual shaders, and I think there's a new node based particle emitter system . . . These things don't really matter, for 30 - 60 minutes work, but for making a small AA game, tons of work in all these editors, well it adds up, to 'head-ache', thanks . . Again, it's already looking amazing, hope you will consider making the graph editor more 'customizable', these small things add, to a ' premium ' feel, imo . . :OO . . .

**Comment by Calinou** [comment]
> That can make the 'inside' of the boxes not be round, bec. it makes it a 'bit' hard, to read the text, when it's not on a horizontal line . . . This . . .

StyleBoxFlat doesn't support inner corner radii, so this is not technically feasible, unfortunately.

**Comment by charlesmlamb** [comment]
Well, ok . . not possible . . . so, here's the problem, we normally read text, in this way . . . . :OO . . .

<img width="346" alt="2021-06-11 1527" src="https://user-images.githubusercontent.com/83387915/121693734-b04cea00-cac9-11eb-81f1-ac8655ad9859.png">

For some reason, those small ' wedges ' make it really difficult, to read the lines, esp. the upper line, that's all . . .

I work many hours in visual script, also shaders, want to use new graph particles, etc . . .

So, sort of getting ' eye - strain ' constantly, is a bit annoying, for longer work times <3 . . .

**Comment by charlesmlamb** [comment]
Last, if I can give a 'small' compliment, it looks much better when zoomed out, etc . .

I see myself really using this feature a TON more, so really, really appreciated . . 10 / 10 <3 . . .

**Comment by charlesmlamb** [comment]
Sorry, the ' wedges ' make me do this, every time :OO . . .

![2021-06-11 1544](https://user-images.githubusercontent.com/83387915/121696026-ee4b0d80-cacb-11eb-9ba0-78d0b779865f.gif)

not important for like 30 minutes work, but making an entire game, it gets ' tough ' . . .

sounds like, it'd take a ton of work, wanted to ask . . I'm ready to make my game, no more questions, let's rock . . <3 . .

Thanks . . <3

**Comment by fire** [comment]
Similar to https://github.com/godotengine/godot-proposals/issues/2364?

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
