### ISSUE TITLE
Add a zoom slider to the SpriteFrames editor' Select Frames dialog (zooming already implemented)

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#2858]
### Describe the project you are working on
Pixels

### Describe the problem or limitation you are having in your project
Animated Sprite, Select Sprite: it's impossible to see the grid or even the sprites with small images

![image](https://user-images.githubusercontent.com/12863685/121781868-ad6ff900-cb9e-11eb-9d1d-92f453372467.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Can somebody add a scale/zoom option please and persist it between selections?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Somewhere in this dialog simply have  a scale slider

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It can't

### Is there a reason why this should be core and not an add-on in the asset library?
Yes, it's impossible to see things sometimes

**Comment by Calinou** [comment]
You should be able to zoom by using Ctrl + Mouse wheel. Zoom is also automatically adjusted on hiDPI displays since https://github.com/godotengine/godot/pull/46946 was merged.

**Comment by chucklepie** [comment]
I tried that, it doesn't do anything.

I'm on a Linux desktop on standard 1080p.

**Comment by Calinou** [comment]
The zoom code is here: https://github.com/godotengine/godot/blob/0024bb3f4eb9ec6808acd0760bb485d3a669bc3e/editor/plugins/sprite_frames_editor_plugin.cpp#L149-L162

However, it was never cherry-picked to the `3.3` branch (it is cherry-picked to `3.x`). This means the feature will be available in 3.4, but it's not currently available in 3.3.2.

**Comment by chucklepie** [comment]
Ok. I'll wait and just squint my eyes for now. Thanks for all these little improvements you're all making. 

Btw, a zoom slider would be nice though as it gives the feature an actual noticeable UI element on this quite sparse dialog.
