### ISSUE TITLE
Перемещение за другим объектом

### ISSUE THREAD

**Issue by godotiser5** [godotengine/godot-proposals#2860]
В моей игре, когда космический корабль приближается к планете, то планета должна крутиться и крутить за собой корабль. Единственный способ сделать это - сделать корабль дочерним объектом планеты. Но постоянно менять родителей для корабля мне не хочется.
Моё предложение: для классов _Node2d_ и _Spatial_ создать поле (свойство) **follow**. **Follow** будет принимать ссылку на объект, за которым нужно будет перемещаться.
Спасибо.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

Also, proposals must be written in English.

If you need a note to follow another node's position, enable its `toplevel` property then add a RemoteTransform node (RemoteTransform2D for 2D) that can be configured to follow another node.

**Comment by Xrayez** [comment]
> Also, proposals must be written in English.

By the way, the rules/guidelines in README does not explicitly forbid proposals written in other languages like Russian. I think the rules should mention this.

**Comment by Zireael07** [comment]
Spanish, too (I am not a native speaker, but considering Juan is Argentinian, well...)

**Comment by pycbouh** [comment]
Feel free to open a meta proposal or a PR to address that, guys. But keep in mind that the best way to have a productive conversation as a community is to use the same language. Auto-translated reports are fine. Proposals may be a bit too difficult to discuss if you can't argue well for it in English, but that's better than not arguing for them at all.

Also, if you feel like you represent a certain segment of our community that can have trouble expressing in our established lingua franca, it would also be really cool to offer those members your help translating their problems and ideas.
