### ISSUE TITLE
Use LunaSVG instead of NanoSVG for importing SVGs

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#2864]
### Describe the project you are working on
Games that wants to use SVG as game art.

### Describe the problem or limitation you are having in your project

Nanosvg isn't maintained. Nanosvg crashes and is not as robust.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To import SVGs use Lunasvg instead of nanosvg.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add Lunasvg as a Godot Engine module. 

We need to modify the SVG with an XML parser to make light theme or dark theme changes.

https://github.com/fire/godot/tree/lunasvg

Links:

* https://github.com/sammycage/lunasvg
* https://github.com/memononen/nanosvg
* https://github.com/godotengine/godot/pull/49601

### If this enhancement will not be used often, can it be worked around with a few lines of script?
SVG rendering is not easy.

### Is there a reason why this should be core and not an add-on in the asset library?
SVG is needed for editor icons too and that is before addons are initialized

**Comment by Calinou** [comment]
For future reference, LunaSVG was dropped in favor of ThorVG: https://github.com/godotengine/godot-proposals/issues/2912
