### ISSUE TITLE
Rename String's `to_int()` or `is_valid_integer()` so they match

### ISSUE THREAD

**Issue by cgbeutler** [godotengine/godot-proposals#2866]
### Describe the project you are working on
A thing that involves parsing of integers from a string

### Describe the problem or limitation you are having in your project
The naming of `to_int` and `is_valid_integer` don't really match each other, so when using both I often get confused/forget which is named full `integer` vs `int`. It would be nice if they were the same, like float is with `to_float` and `is_valid_float`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It'd be nice when moving to godot 4.0 to fix this little mismatch. Seems like 4.0 contains a lot of name-match fixes (like Spacial to Node3D.)
I don't care which gets renamed. It would just be nice if they match each other. I think I would prefer renaming `is_valid_integer` to `is_valid_int`, since using the full word `integer` feels more like a reference to the math concept than the computer science type.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Trivial. Just renames one function.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, this would break backwards compatibility. That means it would have to happen as a major version change.

### Is there a reason why this should be core and not an add-on in the asset library?
It is on the core String type.

**Comment by cgbeutler** [comment]
@akien-mga do these renames all goi in https://github.com/godotengine/godot/issues/16863 ? (Just curious)

**Comment by LightningAA** [comment]
@cgbeutler They don't have to, but this issue probably would have made more sense as a comment over there. See https://github.com/godotengine/godot/issues/16863#issuecomment-854800091

**Comment by cgbeutler** [comment]
Yeah, I didn't see that tracker thing till after this was finished. Wasn't sure if it is needed to help with updating G3 to G4 scripts one day.
