### ISSUE TITLE
Support display pixel (dp) as a unit for Controls (maybe also in other places)

### ISSUE THREAD

**Issue by ModProg** [godotengine/godot-proposals#2868]
### Describe the project you are working on
A Cross Platform Graphical Notetaking Application

### Describe the problem or limitation you are having in your project
Writing the UI I currently fall back to manually scale UI elements using the dpi value of `OS.get_screen_dpi(OS.get_current_screen())`. but this leads to a lot of complication due to resulting in me needing to set all the theme values (eg. margin) in code and not being able to use Themes for that.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Adding (for example to a theme) the option to use dp instead of normal pixels (`1 dp = 160 / screen density`) or another resolution independent unit.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
1. When applying the theme to Controls apply the StyleBox sizes not as pixels but as dp's.
2. (Better in my opinion) Change all Pixels to DP for controls (If enabled), this would also make it possible to use the DPs for other UI values like size.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It can be worked around by adding a function that for each value in a theme calculates the correct value (dp->pixel) and applies that new theme.

### Is there a reason why this should be core and not an add-on in the asset library?
This could be done as an addon but this would not be easily integreted (would only work if the addon reexports every Control as a DPControl).

**Comment by Calinou** [comment]
For games, Godot's [multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/rendering/multiple_resolutions.html) support should suffice as you want 2D elements to scale automatically to match the display resolution in games.

For non-game applications, the best way to solve this is to add a [2D scale factor property](https://github.com/godotengine/godot/pull/21446) which can be adjusted at run-time.

**Comment by Calinou** [comment]
This was addressed by https://github.com/godotengine/godot/pull/52137 in `3.x` and is being addressed by https://github.com/godotengine/godot/pull/52170 in `master`.

**Comment by Calinou** [comment]
Closing, as https://github.com/godotengine/godot/pull/52170 was recently merged :slightly_smiling_face:
