### ISSUE TITLE
Add a repository / forum section specifically for performance advice tailored to individual games

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot-proposals#2871]
### Describe the project you are working on
Godot engine support

### Describe the problem or limitation you are having in your project
Users often would benefit from tailored advice regarding performance, both in 2D and 3D. The main Godot issue tracker isn't well suited to this, as it is specifically for bugs.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Having an official specific place for this would allow devs / other users to help pool together advice in a central location, rather than having this info spread about in various internet sites. It would also make it more likely that questions would get seen by devs.

Having bespoke advice for a particular game can be invaluable, but it also serves as a great way for other users to learn techniques when they are making a similar game in future.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Could be a github repository where people post issues with details of their game, maybe with source code if open source, etc, giving details of what seems to be slowing it down. Could be a section on [Godot Forums](http://godotforums.org), or could be a dedicated website etc. Whatever works and is easy.

This advice could be available both at the design stage and during the production.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
N/A

### Is there a reason why this should be core and not an add-on in the asset library?
N/A

**Comment by Calinou** [comment]
The [Godot Q&A](https://godotengine.org/qa) platform is likely the best official platform for this, along with the [Godot Forums](https://godotforums.org). I don't think we should create yet another platform.

**Comment by lawnjelly** [comment]
Discussing this too on godotforums:
https://godotforums.org/discussion/26596/forum-section-specifically-for-performance-advice-tailored-to-individual-games

**Comment by eon-s** [comment]
Documentation can add a guide, not for advice but for identifying problems, games are all different but issues can be similar so it is better to know how to find the problems and what to ask for when searching for solutions.

There is already an entry for debugging and profiling but it may be possible to make it better for known/common performance problems.

**Comment by Xrayez** [comment]
We can use GitHub Discussions feature for this, similarly to #2069.

These discussions can be enabled either at Godot Proposals repository, or even the main repository, but as evident from previous discussions in GIP, at most we can hope for a centralized place for these kind of discussions at GIP. But personally, I'd enable GitHub Discussions feature even on the main repository, like I did with Goost: https://github.com/goostengine/goost/discussions.

**Comment by lawnjelly** [comment]
Thanks to the guys at godotforums, they've renamed the `exporting` section to `optimizing & exporting`, so we can potentially trial this as somewhere to direct people for performance advice. :+1: 

Github discussions may be another possibility (I'm not familiar) but for now I'm happy to direct people to godotforums and see how we get on.

**Comment by Calinou** [comment]
I added a `performance` label for issues and pull requests on the main Godot repository. This can be used to label issues about unexpected low performance, regressions, or performance optimization discussions. For pull requests, this can be used to label pull requests that improve performance or add low-end-friendly alternatives to high-end solutions.

**Comment by Calinou** [comment]
Closing, as this is now addressed by the [Optimizing and Exporting](https://godotforums.org/categories/exporting) section on the Godot Forums + the `performance` label on GitHub issues.
