### ISSUE TITLE
Allow shortcuts to have more than one input event assigned to them

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot-proposals#2875]
### Describe the project you are working on
The Godot engine

### Describe the problem or limitation you are having in your project
Editor Shortcuts can only have 1 binding. Sometimes you want multiple shortcut bindings: https://github.com/godotengine/godot/pull/47929, there are likely other issues submitted about this.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow for multiple bindings.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Allow for multiple bindings to be assigned to a shortcut. The PR linked below provides more information about possible implementation and serialisation.

Discussion point: Should the amount of bindings be limited (as in below PR) or should any number be allowed. If any number is allowed, this would have the benefit of being able to unify the editor shortcuts interface with that which allows changing of "built-in" actions, like `ui_accept`, etc. However, it would make the overall implementation more complex and more "heavy" since theoretically an infinite amount of shortcuts bindings could be made.

https://github.com/godotengine/godot/pull/48009

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Is core

### Is there a reason why this should be core and not an add-on in the asset library?
Is Core

**Comment by LightningAA** [comment]
What if there's a max of 8 or so shortcuts?

**Comment by KoBeWi** [comment]
IMO it should be either 2 or infinity. Any finite number means hard-coding the shortcuts (see the linked PR for example), so having too many shortcuts would make the code needlessly complex. If we used some generic code and a constant number, there's no reason to have it limited.

**Comment by Paulb23** [comment]
Both [QT](https://doc.qt.io/qt-5/qaction.html#setShortcuts) and [GTK](https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-set-accels-for-action) allow infinite shortcuts, so If we can I would say go for that.

**Comment by EricEzaM** [comment]
Ok, I think this is enough to go on. I will make a new pr with unlimited bindings and see how it goes.

**Comment by pycbouh** [comment]
> Both QT and GTK allow infinite shortcuts, so If we can I would say go for that.

Maybe we should support it for the shortcut system itself (i.e. for the use in the user projects), but in the editor only provide the UI to bind and view up to 2? I see little point in the infinite amount of binds for a professional application, and I don't think I've ever seen one to provide it. But it's fine for the system underneath to allow it.

So I would just change the system to support the unlimited number, but in the editor only allow primary and secondary binds.

**Comment by Paulb23** [comment]
>  I don't think I've ever seen one to provide it.
> So I would just change the system to support the unlimited number, but in the editor only allow primary and secondary binds.

Checking some apps I have installed turns out quite a few of them support any number of shortcuts for a single action (Qt Creator, Jetbrains IDEs, Sublime text, VScode, Blender and Aseprite).

With that said though, I agree, no strong thoughts one way or the other for the editor so long as the underlying system supports it. If it's easier, might be an idea to start with two and if we get feedback for more, we can always re-evaluate.

**Comment by pycbouh** [comment]
> (Qt Creator, Jetbrains IDEs, Sublime text, VScode, Blender and Aseprite).

Okay, you'd surprised me, because I use several of them, and I had to check. You are correct, of course, though I have to say that neither Aseprite nor VS Code make it obvious that you can add multiple shortcuts. JetBrains handles it a bit nicer in their tools.

But still, none of them assume you'd add more than a couple with their UI. So I think it's safe to stop there if it helps us make a more sensible interface for editor key mapping.

**Comment by EricEzaM** [comment]
Here is what I have so far. Honestly I think it will be hard to convince me that limiting to 2 will be better. Having the UI for actions ("Common") and shortcuts is really nice - cuts out a lot of unneeded code.

Common Actions
![image](https://user-images.githubusercontent.com/41730826/122692114-b041ac80-d276-11eb-85b0-0acf67c61385.png)

Shortcuts
![image](https://user-images.githubusercontent.com/41730826/122692178-f39c1b00-d276-11eb-99aa-fd96ee94a14e.png)

**Comment by EricEzaM** [comment]
You can also drag and drop the events to change which one is "Primary".
