### ISSUE TITLE
Compilation - Separate the Editor and the Export Templates, Into Their Own Rules

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-proposals#288]
**Possible Solution \ Idea**
okay i've come to the conclusion that this is how this should be handled

Editor_Debug (use the current "debug" rules) (debug symbols, runtme checks, allow the debugger to be attached)
Editor_Release (use the current "release_debug" rules)

ExportTemplate_Debug (uses the old rules from "release_debug")
ExportTemplate_Release (the godot editor, has no use for the "release" alone, so we move it here)

i think this makes so much more sense, and it's no longer a giant clusterfuck

or separate them as **Editor** and **ExportTemplate**, and apply the specific build rules to the "release" and "debug" targets
___
**Describe the project you are working on:**
teaching people how to compile the engine easily, right now it all feels a bit obtuse

**Describe the problem or limitation you are having in your project:**
people can't tell the difference between release_debug and release, functionally they do two completely different things, or are not ment to be used togheter at all

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
it stops people from making issues like this one
https://github.com/godotengine/godot/issues/28849

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
just rename some text

**Describe implementation detail for your proposal (in code), if possible:**
it's just a rename change

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no, or at least, i don't know, it's just some text change

**Is there a reason why this should be core and not an add-on in the asset library?:**
yes, it's related to the compilation stage

___
I find the naming convention to be extremelly confusing. I've seen a ton of cases, of other users who have also been confused because of this - we can assume that this happens all the time, most people just don't report this problem, as they don't even realize, that it's a problem

this is a very subtle issue, and it should be fixed

**Rename "Release_Debug" to "Release"**
- these are builds of godot, which are shared around
- official godot builds use this
- the _debug is really confusing, usually it's standard to use "debug" or "release", not both
- seriously you have no idea how much that extra "_debug" throws you off, just call it debug

**Rename "Release" to "ExportTemplate"**
- has nothing to do with the editor itself
- actually removes the tools
- is only used to export games, that's it
- has an immediate clarity now
- confuses new users, who have no idea what this is actually supposed to do
- users assume that release_debug is heavier, so they do a release, which is plain wrong
- users are confused, when godot throws up some random message
- users get confused, they assume this is inconsistent behaviour
- users assume that there's something wrong with godot

i think that this is a very obvious change and it woud improve the overall clarity and the usability as a whole

https://github.com/godotengine/godot/issues/28849
___
**edit 2:** after some more thought
Rename **Debug** to **DevelopmentBuild**
Rename **Release_Debug** to **OptimizedBuild**
Rename **Release** to **ExportTemplate**

___
**edit 3:** after some more thought
Rename **Debug** to **DevelopmentBuild**
Rename **Release_Debug** to **OptimizedBuild**

separate ExportTemplate into two
**ExportTemplate_Release
ExportTemplate_Debug**

**Comment by RaTcHeT302** [comment]
while we are at it, this error message should also mention that, this file is only ment to be used, as an export template
![](https://i.imgur.com/seHyZgC.png)

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by RaTcHeT302** [comment]
@Calinou ok

**Comment by RaTcHeT302** [comment]
i still find the naming convention to be too obtuse, let me think of something better

**Comment by RaTcHeT302** [comment]
Rename **Debug** to **DevelopmentBuild**
Rename **Release_Debug** to **OptimizedBuild**
Rename **Release** to **ExportTemplate**

**Comment by RaTcHeT302** [comment]
okay i've come to the conclusion that this is how this should be handled

Editor_Debug (debug symbols, runtme checks, allow the debugger to be attached)
Editor_Release (use the current "release_debug" rules)

ExportTemplate_Debug (uses the old rules from "release_debug")
ExportTemplate_Release (the godot editor, has no use for the "release" alone, so we move it here)

 i think this makes so much more sense, and it's no longer a giant clusterfuck

**Comment by Xrayez** [comment]
> in that case, if we use the tools=no flag, and, if we can set the target to be release \ debug anyway, then why does Release even exist, isn't it redundant at this point?

Yeah, I've also stumbled upon some confusion as in https://github.com/godotengine/godot/pull/32365#issuecomment-535474794:

> Makes sense, I've always found target vs tools confusing sometimes, especially when it's impossible to build release target with `tools=yes`. 🙂

**Comment by Xrayez** [comment]
> seeing as we have a tools=no flag, then my suggestion is to just add more flags, for whatever else is needed, but maybe this goes against how godot is setup at it's core, or maybe this makes no sense at all

It may be worth to add some command line argument which would be treated as a preset instead of renaming existing parameters something akin to:
```bash
scons platform=linux preset=editor_debug bits=64
scons platform=windows preset=export_template bits=64
```

Any specific args like `debug_symbols=yes` should override the default preset configuration in that case.

**Comment by RaTcHeT302** [comment]
i don't like how inconsistent they are, one has "_debug" in it, but the other one doesn't, i think the most elegant, and the easiest to read solution, would to have the targets split into their own thing

Editor_Debug
Editor_Release

ExportTemplate_Debug
ExportTemplate_Release 

and then, we give each preset, the specific rules which they need, and there's no more clashing

instead of writing "tools = no" \ "tools = yes " \ "target = debug_release" all the time, for every single configuration, the presets themselves should already have some preset settings

i think this is the most user friendly, and least confusing solution, you just gotta tell people what these do, and that's about it

i would also prefer if the name convention was consistent, so they both have "debug \ release", or we just type them as **Editor** and **ExportTemplate** (the configuration names), but i feel like, this is more messy, than just setting up the presets beforehand, it would simplify a lot of things in my mind

**Comment by Calinou** [comment]
Closing, as this will be addressed by the [switch to Meson planned in the long term](https://github.com/godotengine/godot-proposals/issues/1797
.
