### ISSUE TITLE
Allow scripts to handle unsupported Input devices

### ISSUE THREAD

**Issue by mr1337357** [godotengine/godot-proposals#2882]
### Describe the project you are working on
Flight simulator

### Describe the problem or limitation you are having in your project
Some of my joystick devices are unsupported or don't have all the buttons mapped in the SDL database. This prevents my game from reading certain inputs.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow the Input object to read inputs not mapped by the database or otherwise probe controller information

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
```
var num_axes = Input.get_raw_joy_axis_count() #states how many axes the input supports ignoring input mapping
for n in num_axes:
   print(Input.get_joy_raw_axis()) #retrieves axis values in order that the device reports instead of the order godot likes
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?
no

### Is there a reason why this should be core and not an add-on in the asset library?
It changes how the input handling object works.

**Comment by Calinou** [comment]
cc @madmiraal

**Comment by madmiraal** [comment]
> joystick devices are unsupported or don't have all the buttons mapped in the SDL database

Have you tried creating your own mapping? The [SDL2 Gamepad Tool](https://www.generalarcade.com/gamepadtool/) allows you to create mappings that you can import into Godot using [`add_joy_mapping()`](https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-add-joy-mapping). You can then create a PR to get them added to the [upstream database](https://github.com/gabomdq/SDL_GameControllerDB), which will be incorporated into future Godot releases.

**Comment by Calinou** [comment]
@mr1337357 Did you see madmiraal's comment above?

**Comment by Calinou** [comment]
Closing due to lack of response (and overall lack of community 
support).
