### ISSUE TITLE
Allow closing a ColorPicker by clicking its originating ColorPickerButton

### ISSUE THREAD

**Issue by pro-rookie-gamer** [godotengine/godot-proposals#2884]
### Describe the project you are working on

editor: UI/ UX

### Describe the problem or limitation you are having in your project

After opening a ColorPicker, there is no immediately obvious way to close it and clicking the originating ColorPickerButton immediately reopens after closing it. You have to click off the gui to close it. I believe this behavior is unintuitive as many other programs have designated buttons to close the pop-up, or feature this behavior.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Clicking on something like the modulate tab on a Sprite node, opens the gui and clicking it again accepts the changes and closes it. Or perhaps, a visible "close", "accept" or "ok" button allowing you to do the same. Being able to close the pop-up the way it's opened, is very common in other software and feels more intuitive.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Perhaps,
```
if albedo.color_picker.visible == true:
	if albedo.is_clicked():
		albedo.color_picker.visible = false
		albedo.accept_changes()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Since it's a UX design, I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

It seems too small a change to be an add-on.

**Comment by pro-rookie-gamer** [comment]
As you can imagine I've never done this before, ha mersee on mi.

**Comment by golddotasksquestions** [comment]
I've always struggled to find a place to click to confirm my choice after picking a color.

Clicking the modulate color rectangle again in the Inspector seems like a lot more intuitive than what we have now. However I don't think this is enough. Pressing the "Enter" key should also confirm the color choice, and there should be an explicit "confirm" or "ok" button as well, because neither pressing "Enter" nor clicking on the Color modulate rectangle again in the Inspector as a confirmation is visually explicit.

**Comment by Calinou** [comment]
> Pressing the "Enter" key should also confirm the color choice

How do you handle text fields? Should <kbd>Enter</kbd> be pressed twice to close the picker?

**Comment by golddotasksquestions** [comment]
@Calinou 

Yes, well .. kinda:

Currently when you click the modulate rect and the color picker popup appears, the focus is on the LineEdit. This makes no sense unless you plan on text-editing the hexidecimal color value (a very rare usecase imho).

I would argue the most common usecase is to click and drag the color map and color gradient. If you want to set a color to white or black, click and drag into a corner is 100 times faster than typing out the hexadecimal, even if the LineEdit is preselected like it currently is. Ctrl+V or Ctrl+C does not need the LineEdit focus.

So I would propose to have the focus on the "OK" button by default when the panel pops up. 
When click and dragging on the color map, the focus should also stay on "OK" (currently it stays on the LineEdit)
If you hit Ctrl+V or Ctrl+C while the focus is on the OK button, whatever text is in the clipboard should be pasted and copied from and into the LineEdit, the color picker should be actualized in case of a paste, but the focus should stay on "OK"

This way you only ever have to hit the enter key once to confirm, unless you want to manually write out or text edit the hex value.

**Comment by golddotasksquestions** [comment]
@AurangAsif What would you expect to happen, if someone clicks the color rect in the Inspector while the popup is visible? Currently a single click closes and immediately reopens the popup. 

"click it once to open", "click it a second time to close again" seems like a lot more intuitive behaviour to me.

**Comment by AurangAsif** [comment]
That makes sense. You click off so it should close, but you clicked the button which triggers it in the first place so it comes back, appearing flashy.

Thinking about what I just said, I guess that could close it as long as the button retains focus so pressing enter could reopen it again until the user clicks another control.

**Comment by duianto** [comment]
This proposal's title request:
>Allow closing a ColorPicker by clicking its originating ColorPickerButton

Seems to have been implemented in 4.0.

At least in v4.0.beta5.official [89a33d28f]
The ColorPickerButton toggles the ColorPicker opened/closed.

One workaround, in 3.x, is to right-click on the ColorPickerButton to close the ColorPicker.

**Comment by Calinou** [comment]
Closing per @duianto's comment.

For future reference, a `3.x` backport will require reimplementing the feature in the old ColorPicker code (as ColorPicker was rewritten from scratch in 4.0).

**Comment by golddotasksquestions** [comment]
@Calinou 

While this fix was a necessary UI improvement, this alone is not a solution to the underlying issue though.

For one, because by default the Colorpicker is obstructing the Inspector and often the ColorPickerButton:


https://user-images.githubusercontent.com/47016402/203612027-39c6d8fc-a6c8-4801-b740-8e8bd3d08660.mp4

even when the Inspector Panel is drastically enlarged:

https://user-images.githubusercontent.com/47016402/203612146-c290f73f-c822-4cbd-9cdb-041e579d3a83.mp4

**Comment by duianto** [comment]
@golddotasksquestions There's an open issue about the color picker covering the inspector:
Allow moving the color picker panel https://github.com/godotengine/godot-proposals/issues/5764
