### ISSUE TITLE
Improve Button->ShortCut->InputEventKey usability

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot-proposals#2890]
### Describe the project you are working on
2D space RTS/shooter hybrid

### Describe the problem or limitation you are having in your project
Adding an InputEventKey to a ShortCut to a Button in the editor does not provide an easy way to set the key that will be used as the shortcut.

The available fields where the character is set appear to be scancode or unicode but they are integer fields with no clear mapping to keyboard characters.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Selecting a key for the shortcut should be more similar to Input Map (at least it should be possible to pick a key by pressing on the keyboard or selecting from a list of human-readable stuff, not opaque integers)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Nope, can't be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?
Core.

Original issue: https://github.com/godotengine/godot/issues/18695

**Comment by EricEzaM** [comment]
https://github.com/godotengine/godot/pull/44181 added `InputEventConfigurationDialog` which should expose an easy API and reusable dialog for selecting input events, using the same interface as all other input event selection areas.

**Comment by EricEzaM** [comment]
Thoughts?

https://user-images.githubusercontent.com/41730826/123546078-8587b480-d79e-11eb-86f3-332d58fccf56.mp4
