### ISSUE TITLE
Move Android Clear Previous Install setting from Export to Editor Settings

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot-proposals#2892]
### Describe the project you are working on
Android based games

### Describe the problem or limitation you are having in your project
When running an Android project from the editor, you may want to uninstall the previous installation before installing the new one. The setting to enable this is found under Export settings. However this is confusing for users, because it's not an export setting. It doesn't affect the APK or AAB created. It's an editor setting. It only affects what happens when clicking the Android run button in the editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Move the setting from:
Project->Export->Android->One Click Deploy->Clear Previous Install
to:
Editor->Editor Settings->Export->Android->Clear Previous Install

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Currrent location:
![OneclickDeploy1](https://user-images.githubusercontent.com/9253928/122667096-00523d80-d1a9-11eb-8088-dc06d048758b.png)

Proposed location:
![Android Export Settings2](https://user-images.githubusercontent.com/9253928/122667320-21fff480-d1aa-11eb-8bd2-cf7935d8943c.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No.

### Is there a reason why this should be core and not an add-on in the asset library?
It's a change to the editor.

**Comment by akien-mga** [comment]
That makes sense in terms of semantics (editor setting affecting the editor export process), but at the same time I'm not sure that it's a setting which is typically turn on/off only once (like Editor Settings would be).

It used to default to ON so it would always clear before exporting, but that makes the export process fairly slow. In my experience, I tend to toggle it on and off for a given project when testing different things, e.g. I don't want it ON when doing quick iterations on the game itself, but I want it ON when testing the "first install" experience. It's especially relevant for projects which require specific permissions, where you want to test the first run experience when it comes to requesting and accepting or rejecting permissions.

If this is moved to the Editor Settings, it makes this process a lot more cumbersome.

I don't know how representative my personal use case is though (I don't work on serious projects, I mostly do testing of porting or export issues).

**Comment by madmiraal** [comment]
Another option would be to do away with the setting and have a second "run" icon which does the uninstall.

**Comment by pouleyKetchoupp** [comment]
> Another option would be to do away with the setting and have a second "run" icon which does the uninstall.

This sounds like a good option, since it's only used for one-click deploy.

Maybe a menu for alternative launch options like this to avoid adding too many launch icons in the bar?

![image](https://user-images.githubusercontent.com/1075032/122682206-f0d4f380-d1ac-11eb-8908-d560f65492cf.png)

![image](https://user-images.githubusercontent.com/1075032/122682145-9a67b500-d1ac-11eb-8af3-60517e911b0c.png)

**Comment by m4gr3d** [comment]
Either option seems good to me!

**Comment by akien-mga** [comment]
Yeah a drop-down menu with the extra option sounds good to me.

**Comment by YeldhamDev** [comment]
I took the initiative and merged the current available solution. If it's truly too bothersome to navigate to the settings, a PR can be made to put it into a dropdown instead.
