### ISSUE TITLE
Add a container for flex-wrap style component positioning

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#2893]
### Describe the project you are working on
A project where I want to have boxes wrapped like so:

<img width="500" alt="Screenshot 2021-06-20 at 14 40 51" src="https://user-images.githubusercontent.com/100964/122672695-a5830b00-d1d5-11eb-930d-6b9fd3ed7fe1.png">

### Describe the problem or limitation you are having in your project
Currently this requires a node tree similar to the following:

<img width="500" alt="Screenshot 2021-06-20 at 14 31 10" src="https://user-images.githubusercontent.com/100964/122672434-29d48e80-d1d4-11eb-8501-9c4d8e4b1408.png">

And then I have to manually sort the children to the next HBoxContainer (or create that container).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I would like to have a `WrapContainer` or perhaps better a `wrap` setting in the `HBoxContainer` and `VBoxContainer` which would wrap the items to the next vertical or horizontal row if the children would exceed the parents height or width.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
If the component is a `HBoxContainer` then with `wrap` enabled, when the child becomes wider than the parent width the children will be wrapped to the next line lower vertically (or higher depending on position settings of HBoxContainer)

For the VBoxContainer this would be the same but would wrap to the next horizontal line (or previous).

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I found some code here which might make this work:

https://godotforums.org/discussion/21875/flex-flow-wrap-container-layout-plugin

### Is there a reason why this should be core and not an add-on in the asset library?
`flex-wrap` is part of the CSS standard library, and so I believe this should be part of the Godot standard library.

**Comment by tavurth** [comment]
Note I have found [this plugin](https://godotengine.org/asset-library/asset/779) which should work, but I still think this would be a valuable addition to the Godot core.

**Comment by Zireael07** [comment]
Yep, I had an almost identical situation and had to make a tree of containers hardcoded to a certain width and height.

**Comment by KoBeWi** [comment]
Isn't GridContainer enough for this? Your buttons all have the same size.

**Comment by tavurth** [comment]
> @KoBeWi Isn't GridContainer enough for this? Your buttons all have the same size.

I'd actually like to be able to have different sized buttons as well, it's a common feature when you'd like to have mixed content types.

Imagine a RSS reader like Flipboard where you can have articles of different widths which span the page, but you'd also like them to be fairly dynamic.

In that case something like `flex-wrap` is extremely useful.

You can tell the individual components to take up as much space as possible in the x-axis (stretch), and keep a minimum width.
Any overflow will automatically spill over onto the next line.

This massively simplifies your dev workflow as you just need to add them in a linear loop:

```
for item in rss_items:
    self.add_child(item)
```

`GridContainer` is cool, and may work for my use case though!

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/56104.
