### ISSUE TITLE
Consider disabling the new 'highlight' current dock for Godot 4 . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2897]
### Describe the project you are working on
A Tomb raider game, with barbarians, and lore . . .

### Describe the problem or limitation you are having in your project
Trying Godot 4 nightly build, it has a highlight around each dock, as one clicks it, ie. for me a yellow ' square ' . . .

![Skærmbillede (1892)](https://user-images.githubusercontent.com/83387915/122708321-343a6b00-d25c-11eb-95a4-122afec7e489.png)

Now, it's quite glaring, on my screen, and makes it uncomfortable to work with the editor, so I'm hoping it can be disabled, for people with themes, that it's really ' tough ', to work with . . . Also, it's like the inspector, what's the purpose . . It's almost like the engine thinks I'm so dumb, I need help to understand where the mouse is, or where I'm currently working, or clicking, etc . . It doesn't help me make games, and it's confusing why, it's even there, also it creates clutter, and doesn't add anything to coding, graphics, etc . . Anyway, it might look nice with other themes, for me, it's really annoying . . . perhaps if one could set the 'opacity', or 'alpha' on it, so it was more subtle, ie. only a feint highlight . . :OO

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, Godot 4 is looking stunning, in many ways, to be honest, it has everything I ever wanted . . Thought maybe this was worth thinking about, since I have no idea what those highlights are for, or how they help me, or better ' navigate ' . . It's sort of cool, at first, then at least for my theme, it's just a ' migraine ', or severely confusing to look at, why it's there, and why the engine feels I need help, to know where I am working, at any time, as if I don't understand what the ' docks ', or panels are . . :OO For me, it's just weird, that said, only hoping we can have button to disable it, since Godot 4 is looking super - cool, atm, also for stuff I use, ie. Visual script . . <3 :OO . .

Well, everything's looking better, wanted to ask about these things, since I'm not sure what the purpose is, and atm it's a bit more annoying, than helpful, thx . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, the new highlight the tab you clicked in, or 'dock', is really weird, it doesn't make it easier to use the program, not sure, thx . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't recode the engine, or so . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it's a new feature . . I suppose, it's general engine, or so . . .

So, I really like where Godot 4 is going, stuff is just BETTER, all around, really cool . . For me it's really annoying, seems only thing it does, is reminds me where I clicked the mouse last, over what panel . . And, I don't need that, been using computers for over 20 years, know where I'm clicking, by now, it seems weird and, for my theme, makes it MORE annoying to work in the engine, though it's over-all looking better, basically all the new UI elements, this one, is ' weird ', or not sure, thanks <3 . . 

Godot 4 gets 9.8 / 10 . . This feature, new highlight, is reason it's not 9.9 / 10 or, even . . <3 Thx . . . Also, I've never seen it in any program, I've used, ever . . Maybe it's just my screen, and a bit of HDR, on my big-screen tv . . But, it's really ' glaring ', to look at, like being ' blinded ', or looking at a bright light, and it doesn't help me with the work, in the panels, docks . . Hope you'll look at it, maybe add a disable it or, set the alpha on it, from 0 - 100 . . Thx . . .

**Comment by Calinou** [comment]
This is already being addressed by https://github.com/godotengine/godot/pull/48567.

**Comment by Xrayez** [comment]
> The focus outline _does_ have an importance because it lets you see where keyboard shortcuts will go. Due to this, hiding it entirely is not an option.

Hardly ever I have to worry about where the keyboard shortcuts go, If anything, dock focusing problems are probably editor issues specifically. This may be important to someone working on editor plugins, though.

Also, is there a way to configure the outlines via editor settings? As long as those can be disabled, I'd feel much at home, so to speak.

**Comment by Calinou** [comment]
> Also, is there a way to configure the outlines via editor settings? As long as those can be disabled, I'd feel much at home, so to speak.

I wouldn't add an editor setting for something that *decreases* accessibility. Making focus outlines prominent enough is important to having a keyboard-friendly editor (something Godot isn't very good at currently).

**Comment by Xrayez** [comment]
> I wouldn't add an editor setting for something that _decreases_ accessibility.

Why not? To give an example, if I have a good eyesight, then I don't need to enable large fonts in the editor. Forcing upon large fonts on everybody would be catastrophic for those who don't actually need it. I think accessibility is subjective.

> To give an example, when Discord redesigned its UI a few months ago, making focus outlines more visible was a big part of that.

I've just tried tabbing within Discord, and those outlines are indeed quite similar to Godot. But until now, I wouldn't even know about this. 😮

I still happen to use mouse as often as keyboard, so perhaps that's the reason why I find outlines redundant on some level. So, I'd say this is already a reason why this could be an editor setting, because there are types of people who use either mouse or keyboard, or both, due to numerous reasons.

In any case, godotengine/godot#48567 looks like an improvement to me, but I'd still make the color subtle enough to be still visible.

**Comment by Zireael07** [comment]
I am inclined to agree with Xrayez: accessibility features that can hamper other users should be customizable. In this case, I find the highlight distracting, too, and a clearly labeled option to change the outline color would probably be enough.

**Comment by davthedev** [comment]
Such highlight is useful in case an identical keyboard action could have two different outcomes depending on the "window" it is sent to. A bit like text fields; the highlighted one is the one where your typing goes.

A middle-ground solution would be to show a more prominent focus indicator as soon as the user begins using the keyboard to navigate.

Exactly what is happening in this very GitHub write form. The green "Comment" button will slightly highlight if you click it with the mouse (small color change), but an outline shows around it if you focus it with the tab key.

**Comment by Calinou** [comment]
> A middle-ground solution would be to show a more prominent focus indicator as soon as the user begins using the keyboard to navigate.

This is something that needs to be implemented on the Control level, rather than editor-specific solution.

**Comment by charlesmlamb** [comment]
My point is, I've never seen it in any other program, and I'm not sure what it is . .

It's like the program assumes, I don't know how to use a simple program . . . 

I understand several having different short-cuts make sense, but I'd just highlight the tab, or header I was in . .

<img width="917" alt="Skærmbillede (1897)" src="https://user-images.githubusercontent.com/83387915/122850111-fba69a00-d30c-11eb-948a-b9d6799b6bc3.png">

It's just, never seen it in ANY other program, and I've never needed it, or heard anybody talk of needing, even people well, that are blind, deaf, never seen this, ever . .

I'd like to be able to set the alpha, so I can lower it so much, it's not distracting, and then start using it, since the engine makers have made it, and it's probably better . . Maybe it's my screen having HDR, but it's really ' glaring ' . . .

![2021-06-22 0353](https://user-images.githubusercontent.com/83387915/122850394-6d7ee380-d30d-11eb-8eee-ce432ade9156.jpg)

I don't mind the features, it's prob. there for a good reason, just the intensity, it's close to well, head-ache after 5 minutes, and it shifts randomly, instead of when I'm hovering somewhere, ie. after a click . . I've also never seen this done, in any accessibility program, normally one can toggle those features, if one needs them . . .

If the problem is, there are different short-cuts, highlighting the tab, is much more subtle, I'm not sure . . . My problem is, for my theme, it gets very 'intense', like a spot-light, and makes the calm editor experience, well 'tough' . . . So, since it's in Godot 4, and I'd like to use it, was hoping one could set the 'alpha', or 'brightness', maybe for the standard theme it's not that bad . . <3 

Gonna use it, just need to lower the brightness, also since it's not done in MANY other programs, going back many years, well maybe make it a setting, to just disable it . . I don't need it, I can use a program, but maybe it's a new trend in software, and it's quite useful . . I'll give it a go, right now problem is my theme becomes impossible to use, maybe others will run into same problem . . Plan is to lower alpha so much it's comfortable, and use it, thx <3

**Comment by charlesmlamb** [comment]
I think the answer is, to make it so no short-cuts conflict, or don't work, or it's very few . . But, that'd require re-writing all the short-cuts, and making sure there's no conflict . . .

One could also subtly highlight the entire panel, that'd make more sense . . .

<img width="509" alt="2021-06-22 0407" src="https://user-images.githubusercontent.com/83387915/122851511-5e993080-d30f-11eb-84b2-d0d50e3facb5.png">

<img width="509" alt="2021-06-22 0408" src="https://user-images.githubusercontent.com/83387915/122851528-62c54e00-d30f-11eb-87af-3db7526fb51a.png">

Or, highlight more than a single pixel border, so it's CLEAR, now you're working in THAT tab . . For some reason, the border just confuses me, never seen it in another program, but I like it, a new feature <3 Gonna use it, just hope one can lower brightness, or prob. alpha, so it's not ' glaring ', on my computer . . Have new tv, it has HDR, and also extra contrast . . :(( Thx . . .

**Comment by charlesmlamb** [comment]
One could also make the border around the dock a bit brighter, and increase color, of background or, some-thing . . .

<img width="752" alt="Skærmbillede (1900)" src="https://user-images.githubusercontent.com/83387915/122859325-22b89800-d31c-11eb-9aca-0235dce5697c.png">

To this <3 . . .

<img width="752" alt="Skærmbillede (19011)" src="https://user-images.githubusercontent.com/83387915/122859337-28ae7900-d31c-11eb-8615-84d73481a3ca.png">

That'd be a nicer, more ' clear ' way of showing, now you're working here . . not sure, thx . . .

**Comment by Zireael07** [comment]
> Such highlight is useful in case an identical keyboard action could have two different outcomes depending on the "window" it is sent to. A bit like text fields; the highlighted one is the one where your typing goes.

Yes, I know, that's why I suggested making the color customizable - this way you don't lose the advantages of the highlight while at the same time not distracting.

**Comment by DriNeo** [comment]
You can highlight the dock title to show the focus, instead of the outline. If it removes the need of an additional editor option why not ?

**Comment by Calinou** [comment]
This was addressed by https://github.com/godotengine/godot/pull/48567, closing
.
