### ISSUE TITLE
Add a `Tween.finish()` method

### ISSUE THREAD

**Issue by sheshire63** [godotengine/godot-proposals#2901]
### Describe the project you are working on
NPC Dialog
### Describe the problem or limitation you are having in your project
the visible_characters of the dialog box are animated via a yielded tween
and i want to end the tween animation immediately on an key-input

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
a function in tween that ends the tween sets the animated properties(calls the methods) with the final value and emits the signal tween _completed
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`tween.finish(object: Object, key: String = "")`
`tween.finish_all()`

### If this enhancement will not be used often, can it be worked around with a few lines of script?
`tween.stop_all()`
`tween.emit_signal("tween_all_completed")`

and you would have to set the end value after the yield

**Comment by Chaosus** [comment]
Note: Tweens are no longer a node in 4.0 and have been completely remade by -  https://github.com/godotengine/godot/pull/41794.

**Comment by KoBeWi** [comment]
The new Tweens have `custom_step()` method which can be used to finish them immediately.
