### ISSUE TITLE
Add HTTP client implementation using libcurl as a module, optionally replacing the default one

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#2903]
### Describe the project you are working on
3d multiplayer game

### Describe the problem or limitation you are having in your project
The current http api is terrible and is not able to be concurrent.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
To improve the http api, we can replace the current implementation with libcurl.

Libcurl supports HTTP/2 and any other versions as they're done.

This is already approved by a Networking team meeting.

Required features:

* Async file upload

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Implement libcurl similar to 
https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/C-libcurl.
 and https://github.com/OpenAPITools/openapi-generator/tree/master/samples/client/petstore/c

Use mbedtls: https://tls.mbed.org/kb/how-to/compile-curl-with-mbedtls
### If this enhancement will not be used often, can it be worked around with a few lines of script?
HTTP is not trivial.

### Is there a reason why this should be core and not an add-on in the asset library?
HTTP support is a core feature.

**Comment by Calinou** [comment]
I'm concerned about binary size as usual. I know it's possible to compile out certain features from curl (such as FTP support), but how small can it get with HTTP 1.1/HTTP 2.0 support? (Not including mbedTLS' size since we already have it compiled in Godot.)

**Comment by fire** [comment]
What platforms are we talking about? The web already has it in the web browser? The practical limit for mobile is 400mb compressed? for over the air download.

**Comment by fire** [comment]
https://stackoverflow.com/questions/27802559/how-to-build-a-small-libcurl-library says 300 kilobytes.

**Comment by Faless** [comment]
As discussed in the networking meeting, should be build as a module, optionally replacing the default implementation.
Depends on godotengine/godot#47308

**Comment by mhilbrunner** [comment]
See closing comment in https://github.com/godotengine/godot/pull/50964: jonbonazza spent a lot of time and work exploring this proposal and in the end, it took way more work and complexity than anticipated and the improvements were not as great as hoped compared to the complexity added.

Due to this, the networking team now feels this is extension/plugin territory for now if it happens.

**Comment by fire** [comment]
See https://github.com/Faless/gd-curl with HTTP/3 support.

**Comment by Ughuuu** [comment]
Is this going to also be on asset library at some point?
EDIT:
From link: `It requires an upstream PR to be able to seamlessly replace the default implementation.`
EDIT2:
Even without the PR, it should still be usable. Will check how to build it, though would be nice to be able to get it from asset library.
