### ISSUE TITLE
Add a `vertical` property to GridContainer

### ISSUE THREAD

**Issue by juanitogan** [godotengine/godot-proposals#2907]
### Describe the project you are working on
Multiplayer lobby for Sendit Soccer.

### Describe the problem or limitation you are having in your project
Grid fills horizontally first.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add a property that tells grid to change the fill order from horizontal-first (row-based) to vertical-first (column-based).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`grid.vertical = true`

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It will be used often, but... using VBoxContainers inside a HBoxContainer is the obvious workaround and requires only one extra loop to break between vertical fills.  If number of rows changes dynamically, however, it gets a bit more messy.

### Is there a reason why this should be core and not an add-on in the asset library?
It doesn't add significant bulk to the core object for a feature that will likely see a lot of use.

**Comment by Calinou** [comment]
As a workaround, you can rotate a GridContainer by 90 degrees and rotate all its children by -90 degrees (or 270 degrees and -270 degrees).

**Comment by juanitogan** [comment]
An amusing workaround idea, indeed... but only if you don't mind the first cell being in the upper right or lower left.  Unless you apply -1 scaling as well to the proper axis.  I toyed with that out of curiosity but found that duplicating an object (in the editor) not only resets the rotation and scaling on the duplicated object, it resets it on the original as well.  Weird.  That's probably another bug for another day.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/10234, which is more detailed.
