### ISSUE TITLE
Create New Project does not play nice with Git

### ISSUE THREAD

**Issue by txjohnson** [godotengine/godot-proposals#291]
If I init an empty repository. I can't create a project there. I have to create the project and then init the existing repository.  Sometime's I reach for git first and then find I have to start over.

Create New Project should just warn that a folder is not empty rather than prevent creation outright.

**Comment by Xrayez** [comment]
As a workaround, you can create an empty `project.godot` file manually and open it with Godot executable, see some [snippets for doing so](https://gist.github.com/Calinou/cd4c67e2a44377c9fb772500daa467f5) (Linux, Mac, Windows).

You can then make file associations to open a Godot project depending on your OS (though you'd have to configure project name and the default video renderer in project settings).

<details>
<summary>As a bonus for Windows users</summary>

You can also add [`Open With Godot` context menu](https://gist.github.com/Xrayez/fce615b43d525b73b0bcf2252dde0d78) option to open a folder containing Godot project.

![godot-windows-open-with-godot](https://user-images.githubusercontent.com/17108460/70434851-02a0eb00-1a8e-11ea-9cfe-575f9941139a.png)
</details>
