### ISSUE TITLE
Add a list of object methods to the signal connection dialog

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot-proposals#2913]
### Describe the project you are working on
Irrelevant

### Describe the problem or limitation you are having in your project
Recently I accidentally found out (thanks to the Godot Contributors Chat) that in the signal connection dialog it is possible to connect an existing method to a signal by typing its name. It is not even necessary that the node has an attached script (but for this you need to switch to advanced mode).

This possibility is not obvious, and it can sometimes be faster to select from a list of methods. This is the case when one proposal successfully solves two problems at once.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For example, add a dropdown list of methods here:

![](https://user-images.githubusercontent.com/47700418/123151095-c6648e00-d46b-11eb-9fe3-034df5080619.png)

Only the user should clearly understand that he can either select an existing method or enter a new name, and the corresponding method will be added to the script. Plus an autogenerated name like it is now.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A similar interface already exists in AnimationPlayer when adding a method call track:

![](https://user-images.githubusercontent.com/47700418/123150860-83a2b600-d46b-11eb-82aa-da4f2046d0b4.png)

Perhaps, the signal connection dialog should be slightly reworked, in the chat we discussed about this. Maybe someone will create a mockup that includes some other changes. In this case, do not forget to consider this suggestion.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No.

### Is there a reason why this should be core and not an add-on in the asset library?
This is the basic functionality of the editor.

**Comment by Calinou** [comment]
This is already implemented by https://github.com/godotengine/godot/pull/38218, but there is some disagreement as to the UX provided by that pull request.

**Comment by dalexeev** [comment]
Duplicate of #239.
