### ISSUE TITLE
Add text trimming vor overruning text in Label (with ellipsis, different modes)

### ISSUE THREAD

**Issue by Geometror** [godotengine/godot-proposals#2916]
### Describe the project you are working on

Godot itself + small test projects

### Describe the problem or limitation you are having in your project

Some labels which have limited space, for example in the EditorFileDialog (see picture), draw over other GUI elements when the text overruns. Setting the "clip" property just cuts the overrun text and the user has sometimes no idea that there are hidden parts of the text. This also applies to buttons.

![grafik](https://user-images.githubusercontent.com/50084500/123260493-ea6cb180-d4f5-11eb-80b8-993ff9368394.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This can be solved/improved by introducing ellipsis clipping per word or character to indicate that the label is unable to display its whole text.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Current options:
(no clipping)
![grafik](https://user-images.githubusercontent.com/50084500/123268974-d24d6000-d4fe-11eb-8dea-f91d2bfd15c5.png)
(standard clipping)
![grafik](https://user-images.githubusercontent.com/50084500/123268896-bfd32680-d4fe-11eb-96cf-304a78ed39f9.png)

New options:
(per word)
![grafik](https://user-images.githubusercontent.com/50084500/123268703-92867880-d4fe-11eb-9104-4ac051c6d671.png)
(per character)
![grafik](https://user-images.githubusercontent.com/50084500/123268642-839fc600-d4fe-11eb-8c40-ed4c297ca6af.png)

(Just a manually typed concept, I haven't implemented it yet.)
### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it needs to be quite fast and calculating at which position the text should be clipped (word/character) needs probably some additions to TextServer in order to do it properly (non-hacky).

### Is there a reason why this should be core and not an add-on in the asset library?
As it changes the behavior of a(some) core GUI control(s) this should be core. It could be useful in various parts of the editor as well as in projects (would help to improve UX) and provides functionality already present in most UI frameworks.

**Comment by MaaaxiKing** [comment]
I find the base concept of this idea very good. But if the dots belong to the text itself, that will be easy confusion, so something obvious and distinctive would be lovely!

**Comment by Geometror** [comment]
I understand your concern, but since the "just text" approach is the way nearly all other software does this it should not be very confusing. In addition, doing this kind of clipping just by changing the visible text to include an ellipsis without drawing additional textures or transparent gradients (e.g. fade-out) is the fastest approach.

However, why not experiment a little? 
Do you mean a fade-out effect or the dots in another color (maybe opaque) or even a distinct icon?
For example
1 ![grafik](https://user-images.githubusercontent.com/50084500/123299480-dd61b980-d519-11eb-9cd9-eee1d3cff13d.png)
2 ![grafik](https://user-images.githubusercontent.com/50084500/123299831-32053480-d51a-11eb-807e-ff3b13ee4183.png)
3 ![grafik](https://user-images.githubusercontent.com/50084500/123302550-1b141180-d51d-11eb-9abe-016a65b7716d.png)
4 ![grafik](https://user-images.githubusercontent.com/50084500/123299527-e94d7b80-d519-11eb-811e-1b8d0db60287.png)
5 ![grafik](https://user-images.githubusercontent.com/50084500/123299552-f0748980-d519-11eb-91a2-cefafd85ed87.png)
6 ![grafik](https://user-images.githubusercontent.com/50084500/123299580-f8ccc480-d519-11eb-8da9-3433b15c3867.png)

**Comment by MaaaxiKing** [comment]
I'm not sure either, but a fade-out (1) looks OK. Maybe this in combination with 3 dots under it but these without fading?

**Comment by Geometror** [comment]
Like that?
![grafik](https://user-images.githubusercontent.com/50084500/123318106-24a67500-d52f-11eb-8391-eae26b72eed0.png)

I am planning to implement this for 4.0, so I think I will try to get ellipsis clipping working in the traditional way first and then decide whether it is worth it to go further. (the fade-out makes the code significantly more complex I presume)

**Comment by MaaaxiKing** [comment]
Looks good to me

**Comment by Calinou** [comment]
I wouldn't use *both* a fade-out and an ellipsis. You lose on the benefits of the fade out (saving space) while losing on the benefits of the ellipsis (simpler implementation).

**Comment by balloonpopper** [comment]
The ellipsis is commonly recognised as an indicator that there's 'more that is not shown' and therefore I wouldn't use a different symbol as then it becomes non-intuitive.  I would consider situations where the text contained "..." to be an edge case that was outweighed by the benefits of indicating that text has been truncated via the ellipsis.

If fades are considered, the edge case to be thinking of is trailing spaces as you can't show these fading.

I do like the look of option 2 above where the ellipsis themselves are fading.

**Comment by Geometror** [comment]
Some early prototype implementation (only per character clipping). It behaves similar to the ellipsis clipping in Blender as @Calinou suggested (ellipsis shown with a length of above 6 characters). Fading/other considered effects, if at all, would probably be done in a later PR.
![Animation](https://user-images.githubusercontent.com/50084500/123510466-0601c480-d67c-11eb-9a82-90d78a256423.gif)

**Comment by Geometror** [comment]
Do you have any suggesions/ideas how ellipsis clipping should behave in a multi-line label? (or when auto wrap is enabled)

**Comment by MaaaxiKing** [comment]
As with a single-line one, in which way ever that will be made

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/50086.
