### ISSUE TITLE
Android notification when app was in background

### ISSUE THREAD

**Issue by BenjaminAndre** [godotengine/godot-proposals#292]
**Describe the project you are working on:**
I am working on an idle game where you gain one of the two kinds of credits by completing a Pomodoro, like in the Forest app.

**Describe the problem or limitation you are having in your project:**
To ensure the pomodoro was successful, I have to make sure that the app stays in focus. There is **MainLoop::NOTIFICATION_WM_FOCUS_IN** for this.
However, it **also triggers when the screen gets locked.** 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
While I can write a specific android module, it would be much more simple with a new notification. 

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

Hoping it isn't much more complicated

![Screenshot from 2019-12-09 14-35-42](https://user-images.githubusercontent.com/3999441/70439903-4ba66e80-1a91-11ea-9967-2d6146d404a4.png)

**Describe implementation detail for your proposal (in code), if possible:**

According to this  [stackoverflow thread](https://stackoverflow.com/questions/4414171/how-to-detect-when-an-android-app-goes-to-the-background-and-come-back-to-the-fo), there is a method done just for that in android :
`application.wasInBackground()`

It could be fired at the same time as WM_FOCUS_IN since you have to regain focus to discover that you were in the background

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes but no. It is a few lines of scripts in java, but setting up an android module just for that is quite heavy work.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it would complement the NOTIFICATION enum. Because the functionnality is so close to something already existing, separating it would be confusing.

**Comment by Calinou** [comment]
Would the `NOTIFICATION_APP_PAUSED` and `NOTIFICATION_APP_RESUMED` constants suffice? They were added in [this pull request](https://github.com/godotengine/godot/pull/32064), which is available in the 3.2 betas.

**Comment by BenjaminAndre** [comment]
I do not think it will. Android [lifecycle](https://developer.android.com/reference/android/app/Activity.html) specifies that onPause() is called when the device goes to sleep. Thus it doesn't discriminate between device going to sleep or app going background.

**Comment by BenjaminAndre** [comment]
I've tried like I proposed in this thread and also by implementing OS.wasInBackGround(). It may be me, but I've come to the conclusion that since the app pauses when in pause (the whole engine), it is unable to receive such event before going back up. If that's the case, I'll just stick to create an android module that can listen in the background. 
Then I close this proposal.
