### ISSUE TITLE
Option to activate the mode "without distractions" automatically

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#2923]
SORRY FOR THE TRANSLATION SPANISH -> ENGLISH

### Describe the project you are working on
indie project

### Describe the problem or limitation you are having in your project
the annoyance of having to manually toggle "distraction-free" mode on and off when using the code editor

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add an option so that the "no distractions" mode is activated automatically when the user is in the code editor.
It is automatically disabled when you exit the editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Simply distraction-free mode is activated automatically when the code editor is activated

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not sure

### Is there a reason why this should be core and not an add-on in the asset library?
I'm not sure this can be done with a plugin but I'm sure it would be best to make it native

**Comment by Calinou** [comment]
This is already supported. Enable **Separate Distraction Mode** in the editor settings, which lets you toggle distraction-free mode independently in the 2D/3D editors and script editor.

**Comment by Torguen** [comment]
Thanks!
