### ISSUE TITLE
Add `some()`, `every()` and `reduce_right()` methods to Array

### ISSUE THREAD

**Issue by Klaider** [godotengine/godot-proposals#2926]
### Describe the project you are working on

None yet, I'm still learning Godot.

### Describe the problem or limitation you are having in your project

None.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Simple Array methods based on JavaScript Array ([developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`reduce_right`:

```gdscript
var a = [[0, 1], [2, 3], [4, 5]].reduce_right(
    func(accumulator, current_value) : accumulator + current_value, [])

# a = [4, 5, 2, 3, 0, 1]
```

`some`:

```gdscript
[5, 10, 0].some(func(v): v > 5) # true
[5, 5 , 0].some(func(v): v > 5) # false
```

`every`:

```gdscript
[6, 10, 6].every(func(v): v > 5) # true
[6, 10, 0].every(func(v): v > 5) # false
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

How it looks with a workaround:

```gdscript
var ArrayHelpers = preload("res://gd-libs/array-helpers/lib.gd")

func reduce_right(array: Array, reduce_fn: Callable, initial_value = 0):
    return ArrayHelpers.reduce_right(array, reduce_fn, initial_value)

var r = reduce_right ( [[10], [5, 2], [1, 3]], func(a, v): a + v )
```

### Is there a reason why this should be core and not an add-on in the asset library?

It's simple enough to not be built-in. The PR https://github.com/godotengine/godot/pull/38645 added `filter`/`map`/`reduce`.

I can't do PR due to the repository weight.

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
`reduce()` exists in 4.0. You can achieve `reduce_right()` by reversing the array before using it.

Instead of `some()`, we could just add `find_custom()` method (`bsearch_custom()` doesn't work for unsorted arrays) and `every()` is the same as `some()` with opposite condition.

**Comment by Klaider** [comment]
@KoBeWi  I thought it's more readable though.

**Comment by Calinou** [comment]
I like the syntactic sugar aspect of `some()` and `every()`. `reduce_right()` avoids having to reverse the array before reducing it (which has a performance cost for large arrays), but I think concrete use cases for it are few and far between.

**Comment by nathanfranke** [comment]
I think `reduce_right` it too oddly specific to have its own method. I think `invert().reduce()` would be more readable, and if performance is important, just use a `for` loop.

**Comment by Calinou** [comment]
> Instead of `some()`, we could just add `find_custom()` method (`bsearch_custom()` doesn't work for unsorted arrays) and `every()` is the same as `some()` with opposite condition.

This was requested in https://github.com/godotengine/godot-proposals/issues/1120, but I think it should be addressed in a separate pull request.
