### ISSUE TITLE
Refactor platform export classes

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot-proposals#2929]
### Describe the project you are working on
Godot engine development

### Describe the problem or limitation you are having in your project
Currently, it's difficult to troubleshoot issues with exporting (especially to Android). The build model requires all the files to be in a single file `platform/*/export/export.cpp`. There is no separation between declarations and definitions. Attempts have been made to reduce the complexity by moving some code into an included header file. However, this just splits the file into multiple files. They are not header files, because they also contain declarations and definitions. Furthermore, the new files have no access to the functions and variables in the parent file `export.cpp`. Therefore, parts get moved back to `export.cpp`, which just adds to the complexity.

This structure has been there since https://github.com/godotengine/godot/commit/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac (GODOT IS OPEN SOURCE) so there is no history of why it was created this way. I assume it was to allow for a module style addition of platforms, and it seemed logical to put the platform build and export code together. Instead of using `SCsub`s, the root `SConstruct` is used to search for `platform/*/export/export.cpp` files. These are then used to both add the files to the tool build and create a generated file that is used to register each of the export options by calling their `register_*_exporter()` function. This all may have made sense when the export was simple and allowed new platforms to be added easily. However, when the export starts running its own build scripts and includes multiple ways of exporting (as is the case with Android) this results in the complexity we currently have, and the inflexibility to fix it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
- Use standard `SCsub`s to build the exporting code.
- Separate the declarations and definitions.
- Separate the platform exporting code from the platform build code.

This will both simplify and standardise the build of the export classes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
The platform export code is used by the editor, so create an `export` folder in the `/editor/` directory and place editor export code there. Separate the export code's declarations and definitions into `.h` and `.cpp` files respectively. Use `SCsub`s to build these components with the other editor code.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, it's core engine code.

### Is there a reason why this should be core and not an add-on in the asset library?
It's core engine code.

**Comment by akien-mga** [comment]
I'm fine with refactoring the code if it's necessary to make the structure clearer, but I disagree about moving it outside of `platform/<name>/`. Platform code is meant to be self-contained (as far as possible) in `platform`, and for export code it's definitely part of what is possible.

This allows us and third-party to distribute platform ports easily without having to modify the rest of the engine. For example https://github.com/godotengine/godot-haiku-platform can be added as a plug-n-compile platform in `platform` and it would in theory work to register a new platform and its export code. As you mention it, it's designed in a way similar to modules which allow auto-registration of platforms as soon as there's a valid platform folder in `platform`, without needing to fork the engine.

Other ports for consoles or niche platforms which we might not be able or want to merge into the main codebase also rely on this feature.

**Comment by madmiraal** [comment]
I understand why you would want to keep platform code together and that it can be convenient to provide a simple way to add new platforms. However, there is a big difference between running Godot on a platform and exporting a game to one of those platforms:
1. Each export requires a template (built from but not limited to the platform code), but each platform doesn't need an export. The Haiku example provided is a case in point.
2. Exporting is platform independent code associated with the editor, and only a subset of platforms are capable of running it.
3. There may be more than one way to export to a platform. Android's APK and AAB package formats, and Android's custom build vs updating an existing APK template are current examples.

Aside from exports being associated with a platform, they are not actually related. The code is completely unconnected to the platform code, but it is tightly bound to the editor code. Making the editor code reach out to the platform code just because there is also platform build code does not make sense to me.

The proposed changes also do not prevent new platforms (e.g. the Haiku example provided) from being created in a _"plug-n-compile"_ way. If the key objection to #50311 is that export code would no longer be _"plug-n-compile"_, this can always be changed by reverting to a generated `register_exporters.cpp` again. 

All that been said, the key motivation behind this proposal is that the current build forces all export code for a platform to be contained in a single file `export.cpp`. This code cannot be split into multiple files, because only the `export.cpp` files are added to the editor build. #50311 provides the basis for achieving this by enabling all `*.cpp` files in the `editor/export/` directory to be added to the editor code. It also moved the code to the `editor` directory where I think it belongs and it made `register_exporters.cpp` non-generated, because I don't believe new exporters would ever be created as _"plug-n-compile"_, but these two changes are not key to this proposal merely, what I thought would be, an additional benefit.

**Comment by m4gr3d** [comment]
It looks like there are two core goals behind this proposal:

- Clean/refactor/simplify the `export.cpp` files: this goal seems non-controversial (IMO) and the option you suggested (i.e: enabling all `*.cpp` files under the `export` directory) seems straightforward. As such, I would create a separate PR that just does that.
- Clear separation between platform support logic and platform exporting logic: I don't have a strong opinion here but the arguments presented seem rather subjective and don't provide a strong benefit (either at the user/developer/code maintenance level) for this refactor.

As such I would separate the first goal out from this proposal, and use this proposal instead to make the argument for the second case.

**Comment by madmiraal** [comment]
The biggest problem with keeping all the export code for a platform with the platform is that there currently is no way to create multiple export formats for a single platform e.g. Android's APK and AAB. This will become more and more problematic going forward when more and more options are not available across export formats. For example, APK expansions are only supported with APKs and Play Asset Delivery with AABs.

**Comment by m4gr3d** [comment]
> The biggest problem with keeping all the export code for a platform with the platform is that there currently is no way to create multiple export formats for a single platform e.g. Android's APK and AAB.

I'm not sure I follow here since we do just that for Android as you mentioned. Are you implying the process could be easier?

**Comment by m4gr3d** [comment]
Or are you suggesting, we should have a distinct `Android - APK` export format and a distinct `Android - AAB` export format instead of them being alternative options on the current `Android` export format?

**Comment by naithar** [comment]
As far as I understand registering multiple exporters for one platform should be possible by simply using `EditorExport::get_singleton()->add_export_platform` with different exporters. 

For example one could be for Android's APK and the other for AAB.
<img width="400" alt="Снимок экрана 2021-07-12 в 14 38 31" src="https://user-images.githubusercontent.com/3750083/125281654-28a00880-e31f-11eb-8940-2c85870beb4d.png">

The problem I see is probably that no `.cpp` files other than `export.cpp` are added to compilation. This would make supporting multiple exporters in single file (`export.cpp`) a really tough job.

I agree that some refactoring for export templates and it's compilation scripts might be required. This would make future modifications and support for current export templates easier. But moving files to other folder wouldn't really help.

**Comment by naithar** [comment]
This changes should allow to use multiple cpp files from `export` folder - https://github.com/naithar/godot/commit/78e07df03776a08a6359361af97920816403e6f6. 
Right now it's required for file to have platform prefix, so this changes shouldn't break any third-party export templates just in case. 

I've moved iOS export into separate file and made two android exporters for testing purposes.
<img width="547" alt="Снимок экрана 2021-07-12 в 15 45 04" src="https://user-images.githubusercontent.com/3750083/125289632-22625a00-e328-11eb-8177-b3bd6479f9bc.png">

**Comment by m4gr3d** [comment]
> This changes should allow to use multiple cpp files from `export` folder - [naithar/godot@78e07df](https://github.com/naithar/godot/commit/78e07df03776a08a6359361af97920816403e6f6).

That looks great!! And it sets up a great structure to easily simplify and cleanup the export logic.
For example for Android with that structure, we can have a base class for most of the common logic, and a derived class for each export format.

**Comment by m4gr3d** [comment]
@naithar Looking forward to the PR! 
Feel free to punt refactoring for the Android export logic and assign it to me if it looks too complex to get done in the PR.

**Comment by naithar** [comment]
I think we should probably wait for more feedback if that's more preferred way to address export's `cpp`/refactoring issue just in case :)

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/50771.
