### ISSUE TITLE
Improve Label's autowrap behavior and provide additional modes

### ISSUE THREAD

**Issue by Geometror** [godotengine/godot-proposals#2931]
### Describe the project you are working on
Godot itself + small test projects

### Describe the problem or limitation you are having in your project
Related to #2916. The autowrap feature of labels is limited to word wrapping, which is not always useful, especially when there is very limited space available.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
- Sometimes breaking by grapheme bounds is more desired (e.g. when displaying filenames). This is already used in the EditorFileDialog and some other places, where space is very limited:

![grafik](https://user-images.githubusercontent.com/50084500/123633108-11d6bd80-d819-11eb-9ba5-79c43d6093ab.png)
- "Smart" word autowrapping mode: Automatically break a word (hard) if it alone doesnt fit in one line.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Choosing the desired behavior could be done by changing the autowrap property to an enum property:

![grafik](https://user-images.githubusercontent.com/50084500/123636602-5b290c00-d81d-11eb-9c7f-3020a25fc351.png)

Grapheme wrapping:

![Animation3](https://user-images.githubusercontent.com/50084500/123635764-544dc980-d81c-11eb-9978-f9e221ad5efd.gif)

"Smart" word autowrapping mode:

![Animation2](https://user-images.githubusercontent.com/50084500/123637437-4f8a1500-d81e-11eb-9746-aa08494bd76c.gif)
(demonstration of behavior in JavaFX)
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, this requires some modifications of existing methods in the Label class/(+ eventually TextServer classes).
### Is there a reason why this should be core and not an add-on in the asset library?
As it changes the behavior of a core GUI control this should be core. It could be useful in various parts of the editor as well as in projects(especially non-game projects/editors/...).

**Comment by Error7Studios** [comment]
If you're also looking into `RichTextLabel`, please see the example project in https://github.com/godotengine/godot-proposals/issues/2698#issuecomment-835472204.
Specifically, the implementation of `get_wrapped_lines()`

**Comment by bruvzg** [comment]
In 4.0 this can be done by adding a new property and changing a single line https://github.com/godotengine/godot/blob/89f270f4c5b1edf655966d11bc7b1ea14ad39a13/scene/gui/label.cpp#L103 to switch.

- `TextServer::BREAK_MANDATORY` - for "off" (break only on `\n`).
- `TextServer::BREAK_MANDATORY | TextServer::BREAK_WORD_BOUND` - for word breaking (current default).
- `TextServer::BREAK_MANDATORY | TextServer::BREAK_GRAPHEME_BOUND` - for grapheme breaking.
- Rerun with `TextServer::BREAK_GRAPHEME_BOUND` if the result of `TextServer::BREAK_WORD_BOUND` do not fit to the width - for "smart" breaking.

Same for `RichTextLabel` and all other multiline controls. `Font::draw_multiline_string` already have flags as argument.

---

In 3.x each control and have its own line breaking logic.

**Comment by bruvzg** [comment]
>  please see the example project in #2698 (comment).

In 4.0 `RichTextLabel` already have some proposed functions:
- `scroll_to_line` - scroll to line counting line breaks, `scroll_to_paragraph` - scroll to line counting only `\n` breaks.
- `get_line_count`, `get_visible_line_count` and `get_paragraph_count`, `get_visible_paragraph_count` - to get line count (and count of currently visible on screen).

**Comment by Geometror** [comment]
@bruvzg I am currently implementing this together with #2916, but it seems like that there are some changes needed in shaped_text_get_line_breaks to implement "smart" autowrap efficiently/correctly, since rerunning shaped_text_get_line_breaks with TextServer::BREAK_GRAPHEME_BOUND is costly and would not result in the correct behavior (in smart mode, a word should only be broken if it alone doesn’t fit in one line, other words should not be affected):
I described this very vaguely above as I didn't know how this "smart" mode should exactly behave, so I will edit my top comment soon.
How "smart" word autowrap should behave:
![grafik](https://user-images.githubusercontent.com/50084500/123705856-c5ff3500-d867-11eb-9739-dd1102b2ee75.png)
![grafik](https://user-images.githubusercontent.com/50084500/123705867-c992bc00-d867-11eb-96f4-808cb20d6faa.png)
![grafik](https://user-images.githubusercontent.com/50084500/123705879-cbf51600-d867-11eb-9aea-249812c3aae5.png)
 
Also, do you think this "smart" mode should be default/replacing the normal word wrap? (I am asking because the LineBreakFlag enum in TextServer has some reserved values, so adding an additional flag is problematic) https://github.com/godotengine/godot/blob/89f270f4c5b1edf655966d11bc7b1ea14ad39a13/servers/text_server.h#L65-L71

**Comment by bruvzg** [comment]
> Also, do you think this "smart" mode should be default/replacing the normal word wrap? (I am asking because the LineBreakFlag enum in TextServer has some reserved values, so adding an additional flag is problematic)

There are no plans to use this reserved value, and currently no custom TextServer implementations exist. Using the reserved bit or adding a new one and extending the argument size to 16-bit won't break anything and should be fine.

Or smart mode might be enabled by setting both `BREAK_GRAPHEME_BOUND` and `BREAK_WORD_BOUND` bits at the same time.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/50086.
