### ISSUE TITLE
Disambiguate "Editor Settings" and "Project Settings -> Editor"

### ISSUE THREAD

**Issue by BenMcLean** [godotengine/godot-proposals#2939]
### Describe the project you are working on
[Porting Wolfenstein 3-D to VR](https://github.com/BenMcLean/WOLF3D-Godot)

### Describe the problem or limitation you are having in your project
I go looking for setting the command line parameters to run my program with and have trouble finding it. It turns out this isn't called "Command Line Parameters" and is instead called, "Main Run Args" and is under "Project Settings -> Editor" and not under "Editor Settings."

But this got me to thinking:

It is ***so confusing*** that Godot has a "Project Settings" with an "Editor" section within it and also at the same time has a "Editor Settings" which is completely separate with different separate stuff in it. These get mixed up constantly. People find the wrong thing when somebody's trying to help them because they're both called "Editor" and they're both in the settings.

I know why they're separated: it's because Project Settings are project-specific while Editor Settings are global. But why do they have to be separate ***and at the same time be named the same? That's confusing.*** IMHO, it should be renamed differently to be less confusing.

There's nothing wrong with the code here or with the scope of the actual settings: it's just that **naming more than one section the same in the GUI is a bad practice in interface design.**

It seems like we always have to fight against the stereotypical programmer attitude of, "if the code works then interface design doesn't matter because the GUI makes perfect sense to the person who wrote the code" -- that's a bad argument when designing software for humans.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I would suggest that "Editor Settings" be renamed to "Global Settings" in the Godot Editor GUI. This would be clearer because just as "Project Settings" expresses the scope of the settings being project-specific, the proposed "Global Settings" name would also express the scope of the settings it contains while the current "Editor Settings" name does not clearly describe the scope.

Alternatively, we could rename "Project Settings -> Editor" to something other than "Editor." But I'm not sure what.

Also, within the "Project Settings" it would be nice if searching for "command line parameters" would bring up the "Main Run Args" in settings so it could be found quicker. If "command line parameters" is what you're used to calling them, googilng it won't bring up "Main Run Args" -- or at least it didn't for me. Took a long time to find it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
This should just be affecting what things are called in the GUI, not code.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Absolutely not.

### Is there a reason why this should be core and not an add-on in the asset library?
Yes, it's part of the Godot Editor interface.

**Comment by dalexeev** [comment]
I think we need to _move_ these settings to the Editor Settings. And, if necessary, add the ability to override the editor settings per project (like git has global settings and local to the project). Also, the Editor Settings window should have two tabs for global and local settings, or otherwise resolve this situation.

<details>
<summary>Example</summary>

![](https://user-images.githubusercontent.com/47700418/123957944-1f28af00-d9b5-11eb-873d-593bb422e101.png)

</details>

**Comment by Calinou** [comment]
`main_run_args` only applies when running the project from the editor – it won't apply to an exported project. This is why it's in the **Editor** section of the Project Settings.

I'm not sure if we can find any better name for the **Editor** section (other than **Editor Only**, which sounds a bit uncanny to me).

**Comment by BenMcLean** [comment]
> I wouldn't rename Editor Settings to Global Settings, because a lot of third-party documentation refers to the Editor Settings.

The idea here would be that this would go into a major update like 4.0, which would be at a point where this would hardly be the biggest change third party documentation needs to make.

**Comment by Calinou** [comment]
> The idea here would be that this would go into a major update like 4.0, which would be at a point where this would be nowhere near the biggest change third party documentation needs to make.

We can't update third-party documentation ourselves – even more so when it's locked (such as Reddit posts/comments more than 6 months old).

**Comment by BenMcLean** [comment]
> We can't update third-party documentation ourselves – even more so when it's locked (such as Reddit posts and comments more than 6 months old).

What's your point? I don't see the relevance of this comment.

**Comment by mhilbrunner** [comment]
We discussed this in today's PR meeting.
https://github.com/godotengine/godot-proposals/issues/1480 may be a way to solve this globally.

We should also think about adding alias functionality to settings search to improve that for things like "Command Line Arguments".

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1480, which is a different solution to this problem. https://github.com/godotengine/godot/pull/53229 was rejected, so this proposal is also considered rejected.
