### ISSUE TITLE
Audio Mixer Faders - Change From Linear to Log/Exponential to Behave Like Mixers IRL

### ISSUE THREAD

**Issue by tekeldnb** [godotengine/godot-proposals#294]
**Describe the project you are working on:**
First of all thank you very much for your hard work!! =)

I am working on an arena FPS set in the future that is heavily audio-focused.

**Describe the problem or limitation you are having in your project:**
It is incredibly difficult to dial in the 'mixdown' of the game using the audio bus faders, they are set to linear making the sweet spots incredibly small and hard to dial in with a mouse. Additionally, the fader range is pretty small, even just adding another 50-100 vertical pixels would be a huge improvement. The ability to scale the fader range itself visually would be absolutely incredible.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Having the ability to switch the mixer faders from linear to logarithmic or exponential will solve this problem quite easily.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
set_bus_volume_db > either log or exp > actual mixer fader in the audio section of Godot.

**Describe implementation detail for your proposal (in code), if possible:**
N/A, I am using code manually to set the levels, which is arduous, but the only way I'm able to dial in the levels as accurately as I would in my DAW.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes, it would be incredibly easy to implement imo.

**Is there a reason why this should be core and not an add-on in the asset library?:**
The audio section of Godot is its weakest in my opinion, coming from working exclusively in audio. I would say bringing the audio section current should be among your absolute top priorities at this phase of the program. Thanks again for your work, Godot is an absolutely amazing accomplishment.

**Comment by Calinou** [comment]
I think this was already done in the 3.2 betas (try [3.2 beta3](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-3)).

**Comment by tekeldnb** [comment]
Oh wow, awesome! I didn't realize it was already in 3.2 I didn't see that mentioned anywhere, I'm sorry! 

Thank you for those functions, I was using my own, those will work better I'm sure. Thanks again!
