### ISSUE TITLE
TileMap.set_cell(): rename `autotile_coord` -> `tileset_coord`

### ISSUE THREAD

**Issue by pig005** [godotengine/godot-proposals#2940]
### Describe the project you are working on

a tilemap based game

### Describe the problem or limitation you are having in your project

`TileMap.set_cell()`'s `autotile_coord` parameter is really badly named; took 2+ hour to find out that it actually meant atlas' coordinates.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1. rename `autotile_coord` to `tileset_coord` / `tilemap_coord`
   - so it becomes **clear** that it is applied to **both** **atlas** and **autotile**
2. (optional) move parameter `autotile_coord(tileset_coord)` next to `tile:int`
   - to show that they are strongly connected
   - like how it's always `func(x, y, other_parameter)` but not `func(x, other_parameter, y)`
3. (optional) rename `tile: int` to `tileset: int` 
   - since a single tile could be seen as a 1x1 tileset;
   - also to implicitly encourage using atlas rather than making multiple 1x1 single tile object; I believe many do the latter simply because it's harder to find out how to do former (as I did); and using atlas & tileset seems to be the better approach. 
   

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
func TileMap.set_cell(
    x: int, y: int, tileset: int, tileset_coord: Vector2 = Vector2( 0, 0 )
    flip_x: bool = false, flip_y: bool = false, transpose: bool = false, 
) -> void
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

```gdscript
func set_cell(
    x, y, tileset, tileset_coord=Vector2(),
    flip_x=false, flip_y=false, transpose=false
)->void :
    .set_cell(x, y, tileset, flip_x, flip_y, transpose, tileset_coord)
```
however it creates unnecessary function call overhead

### Is there a reason why this should be core and not an add-on in the asset library?

- takes minimal effort (just renaming parameter name and position)
- documentation really doesn't help when the parameter name is `autotile_coord`

**Comment by Calinou** [comment]
cc @groud

**Comment by groud** [comment]
It has already been renamed `atlas_coords` on master, and `tileset_coords` seems too vague IMHO.
But I don't mind that much, if everyone think `tileset_coords` is better we could change it.

**Comment by pig005** [comment]
`atlas_coord` looks okay too;
then I could only suggest moving it's position next to `tile:int`; like how x and y stays near on parameter

**Comment by groud** [comment]
> then I could only suggest moving it's position next to tile:int; like how x and y stays near on parameter 

On master the system have changed (flip and transpose flag are no more handled in the TileMap). The argument are thus a little different and order is like that: `set_cell(Vector2i tile_map_coords, int source_id, Vector2i atlas_coords, int tile_alternative`

And for 3.x, the order cannot be changed for compatibility reasons.

**Comment by pig005** [comment]
seems neat!

one last question: could I ask what does `int tile_alternative` does?

**Comment by groud** [comment]
> one last question: could I ask what does int tile_alternative do?

See this progress report, I explained what alternatives are: https://godotengine.org/article/tiles-editor-progress-report-2

**Comment by pig005** [comment]
as the issue was already being handled flawlessly, I'm closing the issue.
