### ISSUE TITLE
How to hide security zone on Android? For better full screen display effects.

### ISSUE THREAD

**Issue by qq715152910** [godotengine/godot-proposals#295]
How to hide security zone on Android?
For better full screen display effects.

I also encountered the same problem, multiple attempts to modify the ''AndroidManifest.xml' but none worked ..
No matter how to adapt and adjust the zoom level,
Safe area always shows nothing..
[example](http://m.qpic.cn/psb?/V12yMqY32k7K5o/OxrhRFlO4euaVd5FUexCzzLHZnRzlfVoDQARWZpZogI!/b/dL8AAAAAAAAA&bo=8QBCAQAAAAARB4I!&rf=viewer_4)

**Comment by groud** [comment]
Sorry, this is not the place to ask questions about how to use the engine, but to propose new features.
Please use the [other community channels](https://godotengine.org/community) for this purpose.
