### ISSUE TITLE
Rename Polygon2D to Polygon and Polygon3D to Polyhedron

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#2950]
### Describe the project you are working on
Relations between regular polygons and regular polyhedrons
### Describe the problem or limitation you are having in your project
I got confused when I came back to Godot with its `Polygon2D`s and `Polygon3D`s from reading internet articles about polygons and polyhedrons. The current names are not that right.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The new names are more appropriate.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Class `Polygon2D` would be changed to `Polygon`, `Polygon3D` to `Polyhedron`.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
Yes, it's just a small change.

**Comment by Calinou** [comment]
I'm not sure if this helps clear confusion. It sounds like you want something like https://github.com/godotengine/godot-proposals/issues/2031 instead, where Polygon3D would allow moving points on its Y axis (or Z axis).

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP and general lack of comments here).
