### ISSUE TITLE
Allow to get list of value names from enum

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#2959]
### Describe the project you are working on
A pretty complex game I'm going to port to 4.0.

### Describe the problem or limitation you are having in your project
In 4.0 enums are no longer dictionaries. This was requested a lot and it's alright, but we lose ability to inspect them. In my project I use enums for e.g. list of elements (fire, water etc.). But I also have lots of data stored in text files (ConfigFiles, previusoly JSON) and there I reference the elements using strings, because Godot's enums aren't accessible outside the engine (and they probably couldn't be). When loading the data I do something like `element = ELEMENT_ENUM.keys().find(element)`, which converts my string to enum value.

This is impossible in 4.0. I'm planning to move to 4.0 eventually, so this is a rather cumbersome limitation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I suggest that we should be able to fetch the list of enum keys. I don't mean accessing it like dictionary. Enum keys are named, so it should be possible to get an array of strings containing the enum keys. It would be something like `MY_ENUM.get_keys()` or, if calling methods on enum is not possible, a global scope method: `get_enum_keys(MY_ENUM)`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
As said above, `enum.get_keys()` method or `get_enum_keys(enum)`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
You can theoretically use const Dictionaries as enums (basically what 3.x does, but explicitly), but it's rather unfortunate that enums exist and I can't use them due to such limitation.

### Is there a reason why this should be core and not an add-on in the asset library?
It improves core functionality.

**Comment by Error7Studios** [comment]
Also, if it's possible for the debugger to display the enum key next to the value, that would be great.
Just seeing the integer in the debugger doesn't really tell you anything, so you have to navigate to the enum declaration just to figure out what that value is supposed to represent.
Because of that, I've just been using  `const String dictionaries` everywhere instead of enums, like:

```gdscript
const STATE := {
	IDLE = "IDLE",
	JUMPING = "JUMPING",
	FALLING = "FALLING",
	ATACKING = "ATACKING",
}

var state: String = STATE.IDLE setget set_state
func set_state(__state: String) -> void:
	assert(STATE.values().has(__state))
	state = __state
```
	
But this is verbose.

**Comment by dalexeev** [comment]
My proposal:

```gdscript
enum MyEnum {
    A = 1,
    B = 1,
    C = 2,
    D = 5,
}

func _ready():
    
    # Minimal
    
    print(MyEnum.A) # 1
    print(MyEnum.B) # 1
    print(MyEnum.C) # 2
    print(MyEnum.D) # 5
    
    print(MyEnum.keys())   # ["A", "B", "C", "D"]
    print(MyEnum.values()) # [ 1,   1,   2,   5 ]
    
    # Useful
    
    print(MyEnum.size()) # 4
    print(MyEnum.min())  # 1 (strictly int, unlike Array.min())
    print(MyEnum.max())  # 5 (strictly int, unlike Array.max())
    
    for i in MyEnum:
        print(i)         # A B C D
        print(MyEnum[i]) # 1 1 2 5
    
    # Additional
    
    for i in MyEnum.size():
        print(i)               # 0 1 2 3
        print(MyEnum.key(i))   # A B C D
        print(MyEnum.value(i)) # 1 1 2 5
```

**Comment by MaaaxiKing** [comment]
Label this topic:gdscript!

**Comment by LightningAA** [comment]
> Also, if it's possible for the debugger to display the enum key next to the value, that would be great.
> Just seeing the integer in the debugger doesn't really tell you anything, so you have to navigate to the enum declaration just to figure out what that value is supposed to represent.
> Because of that, I've just been using `const String dictionaries` everywhere instead of enums, like:
 
See also https://github.com/godotengine/godot-proposals/issues/255
https://github.com/godotengine/godot-proposals/issues/2854

**Comment by JoanPotatoes2021** [comment]
@Error7Studios My workaround was the following, don't know if it's any better to be honest:

```
# Signals
const Signals:Array = ["Green","Yellow","Red"]
enum {Green,Yellow,Red}

var Signal_Example:String = Signals[Green]

func _ready():
	print(Signal_Example)
	print(Signals[Red])
```

**Comment by dalexeev** [comment]
> ```gdscript
> for each in MyEnum:
>                 #  Each should be Object in this, more reasoning below
> ```

I was based on `Dictionary` that iterates over keys, not values. But there is a [suggestion](https://github.com/godotengine/godot-proposals/issues/3457#issuecomment-950094806) to make the `for in` behavior more obvious.

> ```gdscript
> if MyEnum.A == MyOtherEnum.A: 
> 	print("same")
> ```

Enumerations are analogs of mathematical sets (let's forget about the fact that the same value can appear in the enum several times, we will assume that these keys are just synonyms), and enumeration values (integers) are analogs of elements of sets. Accordingly, the sets can intersect, and IMO it would be strange if `1` was not equal to `1`. Or elements need to be made explicit objects (as in PHP 8) and to get integer values you need to do this: `MyEnum.A.value` (which doesn't work well with the engine's built-in enumerations). So I am against the objectification of enumeration elements.

![](https://user-images.githubusercontent.com/47700418/144418599-6ab0ed8f-19ee-49db-8815-e57bfb3fc6e4.png)

```gdscript
# If
MyEnum.A == 1 # true
MyOtherEnum.A == 1 # true

# Then (since the equality relation is transitive)
MyEnum.A == MyOtherEnum.A # true
```

**Comment by dalexeev** [comment]
v4.0.dev.custom_build [b5c825af0]

```gdscript
@tool
extends EditorScript

enum MyEnum {
    A,
    B,
    C,
}

func _run() -> void:
    print(typeof(MyEnum) == TYPE_DICTIONARY)
    print(MyEnum.keys())
    print(MyEnum.values())
```

```
  Native class res://_dev/_run.gd.MyEnum used in script doesn't exist or isn't exposed.
  Native class res://_dev/_run.gd.MyEnum used in script doesn't exist or isn't exposed.
true
[A, B, C]
[0, 1, 2]
```

**Comment by KoBeWi** [comment]
Nice, closing.

**Comment by dalexeev** [comment]
Please reopen because this is a hack that spams the output log with error messages.

> Native class res://_dev/_run.gd.MyEnum used in script doesn't exist or isn't exposed.
> Native class res://_dev/_run.gd.MyEnum used in script doesn't exist or isn't exposed.

**Comment by KoBeWi** [comment]
This was actually already reported, I just didn't notice that the methods are already working: https://github.com/godotengine/godot/issues/54877
