### ISSUE TITLE
Add a feature so one can see what code does live in Visual script/GDScript ( meta-debugging ) . . 

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2962]
### Describe the project you are working on
A 2.5D game, with barbarians, to have a less big project, avoid too big projects . . .

### Describe the problem or limitation you are having in your project
I was thinking, after watching Bolt, that has these weird animations, when it is running, IF there was a good way, of even implementing that, it's a SUGGESTION, and it's MAYBE not useful, not sure . . . Was thinking, if one could make something, so one could see one's script running, while playing, so the boxes that are running are highlighted . . .

A case, suppose I have a 'condition' box, with an action node, then IF I press the button, the boxes that are ' run ', get highlighted . . .

It's for debugging purposes, since Visual script is also for teaching basic code, and having this extra layer, MIGHT make it easier, to ' see ' what's going on . . . During game-play, if I don't press the button, the script looks like this . . .

<img width="964" alt="Skærmbillede (1936)" src="https://user-images.githubusercontent.com/83387915/124869846-15f59e80-dfc2-11eb-9f31-8df7231f15b8.png">

And, when one presses the button, then the boxes it triggers, light up, become highlighted, like so . . .

<img width="947" alt="Skærmbillede (1937)" src="https://user-images.githubusercontent.com/83387915/124869891-29086e80-dfc2-11eb-8572-d4c869b0ce4f.png">

So, if one presses the button, a few times, the boxes it triggers, blink, or perhaps fade in, out, so one can see the entire script working, sort of visually . . This is of course simply not necessary, bec. one knows what the script does, after making it . . . It was more an idea, because Unity has this weird animations going on, that don't really help one debug, or understand the script, it's just everywhere, or so . . .

WHAT IS THIS ? ? :OO . . 

![2021-07-08 0759](https://user-images.githubusercontent.com/83387915/124870113-7ab0f900-dfc2-11eb-8d46-57e29e98be81.gif)

I was looking at it, and it doesn't really help a person debug, since it just runs the entire thing . . I know this is a weird feature, and personally not sure I need it, just got interested in the feature bec. Unity had it, and could it be improved . . . So, this is a far-out suggestion, I'm hoping you'll just THINK about, atm . . If that could be used in Godot, AT ALL, could it be done in such a way, that the parts of the script that are running, maybe just were highlighted, so one could debug one's script visually, and see if one pressed a button, what happens . . . Same thing, say enemy is in range, it chases after player, then as player is moving close, normally the ' inactive ' code, get highlighted, when say conditions are met . . . I don't think this is a super - cool feature, just more interested in improving what they have in Unity, bec. it doesn't really do anything, and takes CPU power . . .

So, proposal is, dumb as it is, for consideration by engine devs, it could be done this way, and effectively make a ' visual debugger ' for visual script, that might help people learning code, first in visual script, how the script works, and run-time, so they can see what is running, what is not . . I know it might not make a big difference, just saw it in Unity, and wondered why it was even there, and IF I had to make my own version, maybe that's how I'd do this . . . Got no idea if this is really useful, I'm thinking it'd be good for complete beginners, or as a simple debug feature, not sure . . Thanks . . . .

I'm thinking, WHY is that even there, in Unity . . Maybe there's a reason, I don't get . . . Wanted to suggest at least making it useful, and would like to hear, if anybody thinks this is really useful, and if Unity maybe not sure, just added stuff, for no reason . . . Anyway, this way one could visually ' debug ' visual scripts, in a fast way, esp. for beginners, but at same time, it seems pointless . . . Not sure why Unity has it, wanted to ask what you think, and if one had to add such a ' live ' debugger to visual script, not sure, how it could be done . . . I consider this very un-important, at least for myself, was just wondering why Unity had it, if I've missed something, etc . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, just make it so one can see visual script while running a project, then make so that the active parts of the chart, get highlighted, so as stuff happens, the script nodes flicker on-off, or get, highlighted . . I'm not sure why Unity does this, maybe someone here can give a reason, I just got thinking, IF that is in another engine, what's the purpose, and how would I like it to run . . . <3 Thx . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Like above, like a ' live ' debugger, for visual script . . Unity has it, but I'm not sure why, wanted to make a quick suggestion, for how it could be done, so it made sense, that's all . . . And, to get some pro feedback, since I got no idea why this was added, to Unity, seems like, wasting processing power . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Well, I can't do this, no idea . . .

### Is there a reason why this should be core and not an add-on in the asset library?
Again, I have no idea why this is in another engine, got me confused, wanted to suggest a way to add it, where it made more sense, though it'll prob. only help beginners, and semi - help experienced visual scripters . . . Right now, I'm just confused what purpose it has, etc . . . 

Add: I got no idea why this is in Unity, but if it is SOMEHOW useful, I'd implement it this way . . I give it 2 / 10, in terms usefulness, it's in another engine, wanted to suggest it, but not sure if it's important or, useful . . . :OO <3

Right now, my hope is the engine pros will just put it in back of head, for some maybe long-term visual script stuff . . . I honestly don't need it, just got curious, why Unity added this, if it's useful, since it's a big engine, guess they had reasons <3

**Comment by charlesmlamb** [comment]
Also, one could maybe do same, but for written code . . Atm, we have this sort of ' minimap ', for written code . . .

<img width="806" alt="2021-07-08 0822" src="https://user-images.githubusercontent.com/83387915/124872536-ad102580-dfc5-11eb-8c36-a06ecda4cdd8.png">

One could sort of highlight the relevant code, that was running, so one could see, if the right code segment, were activated . . . I'm thinking it's more useful, in written code, for really big code, so one knows it all works :OO 

I think maybe Unity just made a ' mistake ', was thinking how can one make this remotely useful, etc . . . .

**Comment by charlesmlamb** [comment]
Last, there are other problems, if one wants to debug something, that only happens on one frame, ie. a player_detected bool is set TRUE, then that would basically ' blink ', for a second, and not be seen . . .

I'm curious if this feature, can be made useful, and sort of help do meta - debugging, or even debugging between scripts . . 

So, I'm hoping for some feed-back, and perhaps even more ideas, to make this useful, I'm really thinking it might be a help, for written code, thx . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
