### ISSUE TITLE
Define versions for GDScript for better interoperability with third-party programs/integrations

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#2964]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

GDScript does not have formal versioning yet. While this is fine in Godot's context, it can be problematic when you're creating some kind of third-party integration (such as a syntax highlighting plugin for an external editor, or a code formatter).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Define formal GDScript versions. These will not be displayed internally in the editor, but should be listed in the documentation for posterity. (If we *really* need to, we can display the GDScript version somewhere in the editor's About dialog, but I don't think it's that important.)

Thanks to this versioning, third-party programs will be able to declare more easily which Godot versions they support (instead of specifying a range which may be unreliable, or difficult to discover for those third-party developers).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The ["GDScript 2.0"](https://github.com/godotengine/godot/pull/40598) moniker has been popular to define GDScript in Godot 4.0, so I suggest we use that one in Godot 4.0 and later.

For previous Godot versions, I suggest adopting the following version numbers retroactively:

| Godot version | Suggested GDScript version | Notable changes | 
|--------------:|----------------------------|:----------------|
| Godot 4.0     | GDScript 2.0 | Revamped setters/getters, etc. **Has breaking changes** |
| Godot 3.1-3.3 | GDScript 1.1 | Optional static typing. |
| Godot 3.0     | GDScript 1.0 | Property syntax, high-level multiplayer. **Has breaking changes** |
| Godot 2.0-2.1 | GDScript 0.3 | `var2bytes`, `bytes2var` + bytecode version upgrade |
| Godot 1.1     | GDScript 0.2 | `prints` + bytecode version upgrade |
| Godot 1.0     | GDScript 0.1 | `setget` |

The minor version number would be bumped for every new language feature or bytecode version bump. (Adding new built-in functions is not considered a new language feature.)

If breaking changes are made, the major version number should be incremented instead.

More information about GDScript's technical history can be found here: https://github.com/bruvzg/gdsdecomp/blob/master/BYTECODE_HISTORY.md

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is about declaring versions for GDScript, so it doesn't involve any code. It's a decision to take.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by vnen** [comment]
I see there are a number of positive reactions here, but I wonder how this would be used. In general, the GDScript version is the Godot version, since both are shipped together (and GDScript is inherently dependent on Godot core).

While GDScript does not need to change in every release, I wonder if it's worth keeping track of another version number just for GDScript. Or in other words: is a new version with no updates that much of a big deal?

**Comment by Sslaxx** [comment]
Could just use the Godot version number?

**Comment by mhilbrunner** [comment]
I agree just using the Godot release version number seems line the most simple solution. Having a separate version number would suggest it can change outside of Godot Engine releases and that it can be used separately from Godot, which both aren't the case, IMO.

**Comment by Calinou** [comment]
Closing, as there doesn't seem to be much support for doing this in the end.
