### ISSUE TITLE
Touch buttons nodes should be affected by vbox /hbox containers but they arent despite touch buttons being used for UI a lot

### ISSUE THREAD

**Issue by 2blackbar** [godotengine/godot-proposals#2965]
### Describe the project you are working on

android touch button game

### Describe the problem or limitation you are having in your project

its hard to center/allign the buttons perfectly

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

touch buttons should be able to be affected by hbox ,vbox and grid container , that would solve it

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

it should work like all the green nodes in box containers

### If this enhancement will not be used often, can it be worked around with a few lines of script?
no clue, maybe some nodes can act like its parent but workarounding incomplete implementation of UI buttons shouldnt be fixed by more code.

### Is there a reason why this should be core and not an add-on in the asset library?
Because eveyrone has smartphone in the pocket, and yet godot is not fully ready for touchscreens, theres just one touch button node and incomplete, cant be centered and you cant build perfectly alligned touch menus from it using vbox or hbox.

**Comment by Calinou** [comment]
@2blackbar The two last questions at the end aren't optional. Please fill them in by editing your first post (hidden behind the … icon in the top-right corner) :slightly_smiling_face:

**Comment by KoBeWi** [comment]
As a workaround, you can use Controls with the size of your button, put the button as their child and center it using script.

**Comment by 2blackbar** [comment]
@KoBeWi workarounding like that is exactly what i dont want to do  and this still wont give me results like when using hbox or vbox containers, i can even use fake buttons with hbox and then try to match acutal touch buttons by eye, but this is kinda ridiculous dont you think.

**Comment by likeich** [comment]
@2blackbar The kind of button you're looking for is the texture button instead. You can add a texture to it for your buttons and it will resize along with the rest of your interface. Use the signals from it to get the input from the button.

**Comment by AlecAcosta** [comment]
im strugling to make my game controls (TouchScreenButtons) adjust to various screen ratios, i think the Control buttons should work with multitouch so I don't have to use TouchScreenButtons

**Comment by smt923** [comment]
it's a bit lost on me that this isn't how it works, how are other devs implementing touch controls that scale nicely to different sized devices? it reads like a built in specifically for touch screen buttons, so I don't think manually having to use 'standard' buttons to achieve this makes sense, unless the touch button is meant to be for something else, which it _kinda_ sounds like it might be, but then I think what it's named now is pretty confusing because when you search for built in touch screen controls in Godot this is the first result almost everywhere, yet it seems like it's not intended to be used this way, despite having very nice built in stuff specifically for this purpose like passby press, multi touch, touchscreen-only settings, etc, when the _regular_ buttons have things named specific to mouse controls and mouse presses

**Comment by brennosouza** [comment]
Yeah it is a bit weird to work TouchScreenButton since they aren't Control nodes. Is there a specific reason why they are Node2D?

**Comment by Calinou** [comment]
> Is there a specific reason why they are Node2D?

Probably not, it's most likely a legacy decision that remains to this day.

However, if Button is modified to support multitouch, then TouchScreenButton won't be relevant anymore.

**Comment by roalyr** [comment]
Just found out that It is a case and Control buttons do not support multitouch. 

It was easy to fork Desktop UI into mobile UI, with all the buttons and so on, and having to switch to Node2D for gameplay buttons kinda breaks consistency.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3976, which is more likely to happen as a solution to this problem
.
