### ISSUE TITLE
Make directional shadow fading use a circular radius instead of linear distance

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#2969]
### Describe the project you are working on

Stealth game

### Describe the problem or limitation you are having in your project

Similar to https://github.com/godotengine/godot-proposals/issues/2963, there are instances where having a Radial Shadow fading would be useful, both aesthetically and mechanically (More visually pleasing as camera rotation doesn't affect the shadows you see, and from a mechanical standpoint, the player can't just switch up camera angles a little to shade/unshade different parts away which could disadvantage the player a little)

Do note while I am talking about there being mechanical use cases for this in some games, these are very rare and most games would use this because of the raw visual benefits.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding an option for Radial Shadows allows removes the camera angles as an element in the equation, when shadows don't have a high distance, and also looks significantly better in cases where shadow distances are smaller and the shadow fade more visible.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a Toggle (much like blending splits) that would turn the Fade from the linear fade to become circular fade. This could probably be default on as it provides a much more pleasing shadow experience (as they're stable, regardless of shadow angle) and the cost wouldn't be too significant, and would be similar to https://github.com/godotengine/godot/pull/50294

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Only by making shadows large enough for the camera angle change to not make a significant visible impact.

### Is there a reason why this should be core and not an add-on in the asset library?

Directional Shadows are Core and would require an addition directly to the Directional Lights.

Notes:
1) This is potentially significantly harder to implement than the Previous Proposal
2) This would probably require other splits to work in a similar fashion for best visual results, which is unclear how doable it is with the splits, and would probably result in lower effective resolution of the splits because non Orthogonal shadows are essentially a group of rectangle shadow maps, and each would have to be cut in a radial fashion, which would render more shadow map pixels to be left unused.

**Comment by Calinou** [comment]
Directional shadows are drawn using splits that are parallel to the camera (hence the "PSSM" name), so I'm not sure if this is feasible.

**Comment by mrjustaguy** [comment]
Yeah, I expect the intermediate splits would not be feasible.. The only Idea for doing the intermediate splits that I can think of is to pack them closer together so that they overlap just enough so that there's data for both sides of the split in the area and then an algorithm picking from which split it should take pixels, which would result in a lower effective resolution.

However, intermediate split transitions would Not look bad when Blending splits, as when blending splits, aside from the Fade, it's very hard to determine where the splits actually are, and wouldn't be easy to observe issues if they would remain linear and only the Fade being circular.

The way I see it, if this can be implemented it'd probably be only for Orthogonal Shadows and PSSM when Split Blending is on, as PSSM without Split Blending on Would indeed look bad with the mix of linear and circular transitions, and anyway it's done, it'd waste some data, which isn't too bad for the fade, but if it were somehow done for all splits it'd probably cost the resolution of the shadows to do.

**Comment by mrjustaguy** [comment]
Closing as this is no longer an issue when Directional Light Shadows can be moved up all to Camera Far and be made fairly well looking, even with ~10km View distances with the right settings in 4.0 and it's not worth investing time for 3.x for the few that would bump into this sort of an issue.

**Comment by Zireael07** [comment]
> when Directional Light Shadows can be moved up all to Camera Far and be made fairly well looking, even with ~10km View distances with the right settings in 4.0

Can you plz describe the settings used?

**Comment by mrjustaguy** [comment]
Sure. I'll update this comment with all the details (and resulting pics) of the solution in a couple of hours.

**Comment by Calinou** [comment]
It is actually possible to use a bounding sphere or bounding box for directional shadow splits. See slide 22 in in the slideshow linked here: https://web.archive.org/web/20121105134010/http://dice.se:80/publications/title-shadows-decals-d3d10-techniques-from-frostbite/

A bounding box will give you the best possible shadow density, but the slideshow does not mention how it was implemented (nor the bounding sphere for that matter).
