### ISSUE TITLE
Fade in / Fade out to solid color

### ISSUE THREAD

**Issue by 2blackbar** [godotengine/godot-proposals#2971]
### Describe the project you are working on

Working on a titlescreen and entering first level, also exiting the level to title

### Describe the problem or limitation you are having in your project

My problem is that i have to use workaround with animation player calls everywhere on every scene enterig /exiting and getting the node  relative to current node is a bit wonky, its recommended to get child nodes in the code anyway which would require making new animplayers just for fade.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Currently transition is immediate cause theres no built in fade in Godot so why not ?
Some people use animation player to workaround this very basic feature which is kinda weird.
It becomes problematic to create animation players or getting the node all over the scripts just to get fade playing.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

simple script command , fade_in or fade_out, time to set how long it will take to get to solid color, and thats it, eventually color values in rgb maybe.Similar time setting to yield so they can be used together when exiting a scene,

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it can be workarounded by colorrect and animation player calls all over the project which gets tiring especiallly to get that one animation player node from lowlevel nodes...

### Is there a reason why this should be core and not an add-on in the asset library?

Because  this behaviour is used in all games all over the world from the very beginning of videogames, so godot not having it hardcoded is a bit strange.

**Comment by Calinou** [comment]
You can use the ColorRect node placed in front of your GUI controls to achieve this. The ColorRect's color can be animated using AnimationPlayer or Tween.

**Comment by 2blackbar** [comment]
Thats exactly what im doing, you think its fun to have animplayer node referenced everywhere on all scenes and figuring out its path tree relative to current node? Its a nightmare.Fade hardcoded would really help with this.
Also im using splitscreen with multiple layers, something like global fade no matter when youre calling it is the best, wasting anim players for this is not the right way to do it.Maybe there are other code only methods , i havent found them yet.

**Comment by timothyqiu** [comment]
Take a look at [AutoLoad](https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html). You don't have to figure out relative paths, the name of singleton AutoLoads can be used directly.

**Comment by pycbouh** [comment]
There's nothing wrong with creating AnimationPlayers just for one effect in one specific node. That's not a workaround, that's the node system. You can even create and reuse a scene that would encompass different fading effects, expose properties and methods to control it and put it on top of your other scenes.

**Comment by 2blackbar** [comment]
I dont know, im not up for arguing, im just after one like of code for fade out effect, thats iut, no anim player no fake rects covering screen oin particular layers....

**Comment by KoBeWi** [comment]
There's no need to modify source for that, it's easy to achieve with scripts. Here:
[Fade.zip](https://github.com/godotengine/godot-proposals/files/6796064/Fade.zip)
Just put this scene into autoload and you can do Fade.out/in anywhere.

**Comment by Calinou** [comment]
Closing, as this can already be achieved using a ColorRect node (and perhaps an AutoLoad) as described above.
