### ISSUE TITLE
That very missing Z axis in 2D world......

### ISSUE THREAD

**Issue by 2blackbar** [godotengine/godot-proposals#2994]
### Describe the project you are working on

Im trying to recreate my own game from other engine

### Describe the problem or limitation you are having in your project

Godot doesnt have z axis to properly do up/down/left/right walk and jump.
It either has to be leftright and jump, or left/right/up/down without jump.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest using Vector3 in to readout z axis as well and not just x/y   , its not atari2600 days come on

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I think y axis can stay as depth, eveb tho its not really correct and it should be y axis but since y sort is already there, it should be more managable to add z axis.
Z axis would servefor eg to determine  jump height and overall height of the collission boxes.
y axis would represent depth of collission boxes.
That would require adding z height to collission code and making it possible to crate collisions over floor..

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I dont think that anyone succesfully recreated it with code where collission boxes could be put mid/air  to represent collision from head to waist  with depth.

### Is there a reason why this should be core and not an add-on in the asset library?

Because its not 80's where flat games ruled on atari 2600 but even NES games had z axis with a lot of its titles so why godot is behind ?
Godot has nice 3D but quite crippled 2d because of missing z axis

**Comment by pycbouh** [comment]
If you want to have 3D dimensions in your game, you should use 3D rendering pipeline, not 2D one. The point of the 2D pipeline is that there is no depth, there is only screenspace. You can of course mimic depth in various ways, but it would still be fake and more of an artistic choice. If you need real depth, use real 3D space and an orthographic camera.

**Comment by Calinou** [comment]
It's fully possible to build some kind of 3D awareness in 2D. See the [2.5D demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/2.5d) for an example of this.

**Comment by 2blackbar** [comment]
You guys ever tried to allign 3d collission boxes with player sprite...  or opened his scene acutally ? hes not even having sprite and 3d collission in one scene, its either looking at one or the other,yeah.,  no thanks ! 
I dont think so,its not viable option at all. 
3D world is not the way to go about this.Unless theres strictly 2.5D mode, where you just import sprites and animate them like in 2d world but use extra z axis as well, but there isnt tho and its mostly people who never really tried that workflow recommend 3d .
I know that i can always code it myself in 2d world (add z fake axis )but i cant as im not as good with coding, and if i would be then i would immediately add it to godot for everyone to use.
 Im looking for best tool for the job without having to code its basic behaviours myself , i like a lot of aspects in godot but some are very far behind.
x and y axis only just doesnt cut it for anything with depth z and jumps,I dont want to just do platformers and snes rpg clones, theres tons of 2d engines with just x and y axis and IMO godot should be ahead.
Id like to stay in 2d world, and just use 2d collision boxes with z axis added thats actually editable in editor so i can have both 3d collission boxes and 2d sprites.When You go 3D then you have one unless youre using just one non animated sprite but who wants that as his game character ?
Taking care of alligning sprite and bg images with actual 3d bricks isnt fun or easy.
I can go on and on, i know about the tests in 2.5d in godot, ive seen them, i know their limitations, thats why i came here to nag a bit.Cause its like having super luxury car but bike tires on it.
2D in godot is way way behind.

**Comment by pycbouh** [comment]
You seem to imply some isometric game where characters are supposed to move in 4 basic direction as well as jump with actual physical interactions with objects in the world. (Kind of like our 3D [Squash the Creeps demo](https://docs.godotengine.org/en/latest/getting_started/first_3d_game/index.html)). If you need some actual 3 dimensional physics, you kind of have to use 3D space. Imitating it would be tricky as you would need to rely on multiple physics layers and move your character between them with collision masks as it jumps. That's possible, though if you, by your own admission, lack the necessary skill then the actual 3D space is your best option.

2D engine in Godot is a 2D engine. It wasn't designed to imitate 3D, and it's not a matter of adding an axis.

**Comment by 2blackbar** [comment]
Its simply beatemup, where you can walk up,down,let,right and also jump, thats it.
Currently 3d and sprites3D are buggy in godot since over year, its white rect only when i use spatial mat, i haver to do it to use billboard so sprites in 3d world  dont really work even if id like to try very hard.
Theres one engine , openbor where z axis is available and its not an issue, but from what i see, its rarity and people dont really get how important it is in 2d games as well.
All beatemups have x,y and z.

**Comment by dalexeev** [comment]
> Its simply beatemup, where you can walk up,down,let,right and also jump, thats it.

Use `sprite.offset.y` to simulate the z-axis.

**Comment by aaronfranke** [comment]
@2blackbar If you want 3D objects, use 3D. That's what 3D is for. You can do billboards etc. This is what Unity does, its 2D system is actually flat 3D, so if you want Unity-style 2D, use Godot's 3D.

If you want 3D location while using 2D rendering for efficiency, use the approach in the 2.5D demo. I suggest actually downloading the demo before passing judgement. There is [a 2.5D viewport for easy editing](https://raw.githubusercontent.com/godotengine/godot-demo-projects/master/misc/2.5d/screenshots/editor.png).

**Comment by Shadowblitz16** [comment]
> ### Describe the project you are working on
> 
> Im trying to recreate my own game from other engine
> ### Describe the problem or limitation you are having in your project
> 
> Godot doesnt have z axis to properly do up/down/left/right walk and jump.
> It either has to be leftright and jump, or left/right/up/down without jump.
> ### Describe the feature / enhancement and how it helps to overcome the problem or limitation
> 
> I suggest using Vector3 in to readout z axis as well and not just x/y , its not atari2600 days come on
> ### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
> 
> I think y axis can stay as depth, eveb tho its not really correct and it should be y axis but since y sort is already there, it should be more managable to add z axis.
> Z axis would servefor eg to determine jump height and overall height of the collission boxes.
> y axis would represent depth of collission boxes.
> That would require adding z height to collission code and making it possible to crate collisions over floor..
> ### If this enhancement will not be used often, can it be worked around with a few lines of script?
> 
> I dont think that anyone succesfully recreated it with code where collission boxes could be put mid/air to represent collision from head to waist with depth.
> ### Is there a reason why this should be core and not an add-on in the asset library?
> 
> Because its not 80's where flat games ruled on atari 2600 but even NES games had z axis with a lot of its titles so why godot is behind ?
> Godot has nice 3D but quite crippled 2d because of missing z axis

Is this about godot using a different 3d axis orientation then what the 2d system uses?

If so he means having godot use a 3d axis system that is easily convertible back and forth between 2d
Right now godot requires us to perform axis rotation and flipping to convert between them, which I agree is dumb.

**Comment by pycbouh** [comment]
@Shadowblitz16 It is not about that.

**Comment by aaronfranke** [comment]
Closing because we will not add a Z axis to 2D and we have explained tricks to create depth effects in 2D. If you want a Z axis, that's what 3D is for.
