### ISSUE TITLE
Add a option to reset main scene for each export

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#2996]
### Describe the project you are working on

Multiplayer game

### Describe the problem or limitation you are having in your project

In my project, I have 4 export settings: Server(Linux); Client(Windows); Demo(HTML5); AcountMgr(Android)
Each export settings for a main scene, Every time, I must change the main scene in Project Settings then export.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If export settings have a main scene, I can set it and not need change it in Project Settings, so convenient.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Keep Project Settings.
Each export settings add a Main Scene, default empty. If set, use it; if notset, use Project Settings

### If this enhancement will not be used often, can it be worked around with a few lines of script?

/

### Is there a reason why this should be core and not an add-on in the asset library?

/

**Comment by timothyqiu** [comment]
You can override project settings with [feature tags](https://docs.godotengine.org/en/latest/tutorials/export/feature_tags.html#overriding-project-settings).

If you want to set a different main scene for the HTML5 build, for example, go to Project Settings, select "Main Scene" in Application/Run, and then click the "Override For..." button on top and click "HTML5" in the dropdown list. A "Main Scene.HTML5" entry will appear, and you can set the main scene for HTML5 there.

**Comment by CsloudX** [comment]
@timothyqiu Oh, So COOL! Thanks.
