### ISSUE TITLE
Visual script overhaul

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#3]
Here are some suggestions and proposals for VisualScript:

## Node io:
* [Reroute graph connections](https://github.com/swarnimarun/visual-scripting-node-library/pull/8)
* Change input type of switch
* Return of functions are always "any"
* Make functions not have output if no return exists
* A `Get Local Variable` node should find other `Set Local Variable` nodes with the same variable name and set it's type to that
* Constructors for non-basic classes
* Drag and drop consistency (Getters and Setters)
* Shift instead of Ctrl for setters (Shift is for inverting things)
* Pull out from an input port to create a variable of the correct type
* Update function arguments, name and output
## UI:
* The nearest port should be dragged, not a random one in range
* Nodes should be selected when added
* Better searching behavior (just show us all the things!)
* Search doesn't work with spaces
* Grid snapping options should be the same in any script
* Grid snapping should be 10 by default
* Functions should stay open when changing scripts
* Editing variable is always black (Theme is ignored)
* Ability to hide windows in the script editor (No minimum sizes)
* Allow visual script zooming with scroll wheel
* Make zooming better
* Enhance member variable editor (Click to edit variable, not name)
* Make long dropdowns searchable (this applies to other engine features as well)
* Shortcuts for compressing nodes into a function
* Double click function nodes to edit them
* When adding a node, it should automaticly drag out the first output/input
## Inheritance issues:
* Parent methods don't get displayed
* No methods / members get displayed
* Base type gets long when it's a custom script
## Other:
* Conditions should be configurable
* Make custom nodes resource based, or convert resource to custom node (this could be done in a plugin)
* Unify the visual script graph
* Text based saving for version control
* Unify `VisualScriptLocalVarSet`, `VisualScriptVariableSet` and `VisualScriptLocalPropertySet`

**Comment by fire** [comment]
To do for loops requires a generic shader node

I guess the Expression node is enough for "for" loops. The Visual Shaders currently do not support Functions and Flow control signatures.

https://github.com/godotengine/godot/issues/22243

**Comment by fire** [comment]
## Text based shaders

Also, in 4.0 there's a change that'll allow text visual script and materials

https://github.com/godotengine/godot-roadmap/issues/30

**Comment by fire** [comment]
## Grouping and regrouping random nodes and unifying custom nodes / expression nodes

The comment node is an excellent point to start.

https://github.com/godotengine/godot/issues/20490

* groups (interface with code)

Useful for merge and removing the merge of entire groups.

Groups have a title, a list of grouped nodes, input-output port, and position.

* groups -> comments;

 comment has a title, a list of grouped nodes, pos, and comment string.

* groups -> custom nodes; 

Custom nodes are like groups except has Gdscript.

* groups -> expression

Expression is like custom node except it is converted to shaders.

Requires to add a method to add input variables.

**Comment by fire** [comment]
## Technical details on scaling control nodes and graphs 

## Unified graph

**Comment by fire** [comment]
There's a hot spot zone for the port connection. We can tune the size of it.

> The nearest port should be dragged, not a random one in range

**Comment by Jummit** [comment]
> There's a hot spot zone for the port connection. We can tune the size of it.
> 
> > The nearest port should be dragged, not a random one in range

The issue with that it that it doesn't use the nearest point in range, but rather the first point in range it finds, which isn't always the closest one.

**Comment by Jummit** [comment]
> Expression is like custom node except it is converted to shaders.

What do you mean by `converted to shaders`?

**Comment by fire** [comment]
I will message you in discord and we can rewrite a summary. There's a summer of code proposal for this.

**Comment by fire** [comment]
Here's a rewrite:

## Groups

We have a super class called groups which are an interface with implementation.

This feature is useful for merge and removing entire groups of nodes.

Groups have:

* title
* a list of grouped nodes 
* input-output port
* position

## Comments 

Comments derives from the group class.

Each comment group can be moved as a group.

Each comment has:
* Inherited group properties
* comment string.

## Custom nodes

Custom nodes derive from the group class.

Each custom node has:

* Inherited group members
* Gdscript

## Expression nodes in Visual Shader 

An expression derives from the group class

Each expression node has:

* Inherited group members
* Shaders code (text)

To do for loops requires a generic shader node.

The Expression node is enough for "for" loops. The Visual Shaders currently do not support Functions and Flow control signatures.

#22243

Requires adding a method to add input variables.

**Comment by swarnimarun** [comment]
**I recommend to add a Flag for Breaking at the top of your proposal idea if it's breaking something.**
Here is the image if you any of you feel lazy.
![image](https://user-images.githubusercontent.com/19930870/57287572-71bbf880-70d5-11e9-9b83-fdf0b7f0c3ee.png)

**Comment by swarnimarun** [comment]
There is a huge list of things to be discussed probably worth breaking it into multiple proposals. 
For now, I think we might want to keep this one along with the UI aspects of the Visual Scripting Editor.
![breaks compatibility](https://user-images.githubusercontent.com/19930870/57287572-71bbf880-70d5-11e9-9b83-fdf0b7f0c3ee.png)

**Let me start with the basic things(UI and Design) and we can move ahead from there,**
(Note: Visual Scripting is Officially not production ready yet so breaking changes should be open for major releases worth discussing this with other Maintainers)
- Allow the Node Graph to be more self-sufficient and not have to move to the inspector for every new change.
- Make nodes that use color codes with more rigidity and have constant theme.
- More Dynamic Nodes, nodes that can change and are well contained for the purpose.

![image](https://user-images.githubusercontent.com/19930870/57286762-9b742000-70d3-11e9-8305-434d564a0483.png)

This is a quick MockUp to help understand the idea.

Here the color code is that brighter color is for the Specific Type and then the duller(whitish color) is for the Array of that type.
In this Grey is Any, Whitish Grey is Array(of all types).
Yellow is Int, Light Yellow is for Int Array(PoolIntArray).
Blue is for Object.

We have + and - buttons to add and remove elements.

For arrays it will just allow us to select a type and create a new variable.
While for setter fields they will pop open a menu to select a field we want to edit(as not all fields need to be changed)

This will make the setter node much more powerful and much less redundant(each setter editing one value was kinda wonky) and we obviously need a create Array node.

This design theme can be followed to other aspects of the Visual Script system as well.
Probably have even the Curve and Gradient Editors be a part of the Visual Script directly to make editing fields of even resources easier.

And yes this will have to change most of the currently present nodes and will require some substantial chnages to the GraphNodes UI to support for buttons, curves and such.

**Comment by swarnimarun** [comment]
Groups Nodes replace Functions
---
Grouping of Nodes in a chain should be allowed to simplify the process of creation of Node Units and increasing reusability of parts of the Visual Scripts.

![image](https://user-images.githubusercontent.com/19930870/57302002-da1bd180-70f7-11e9-83b9-164200a839be.png)
Quick Mockup.

> _Group Nodes should be stored as custom Nodes that are accessible from the same drop down for searching the Nodes and also allow for saving and loading groups as resources for use as custom nodes all across the project._

Probably even have a default folder where we can place all the Grouped Node(Custom Node) Resources that we want to be accessible across the project as custom nodes, automagically.
This would remove the need to newbie users to learn how to create Tool Scripts.

**Comment by swarnimarun** [comment]
@fire I believe the problem with the Scaling of the Theme is due to DPi. I mean we can use DPI scaling instead of normal scaling but we need dynamic DPi controls to do that I believe @toger5 had something on the topic.

![image](https://user-images.githubusercontent.com/19930870/57303717-890ddc80-70fb-11e9-958f-245c6796137b.png)

Here I changed the DPI of Editor itself to show how well DPI scaling works.

The process should be simple enough. Once we can get Dynamic DPi scaling working or if it already works then well I will make a PR ASAP.

Also, there are other Technical Details I have come across I think might be important. Should I share them here or just work on them on my own?

**Comment by swarnimarun** [comment]
Seems like Display Scaling is related but not necessarily dependent to DPi... Sheesh.

**Comment by fire** [comment]
What do I need to do to split this list into 10-20 issues? Alternatively we can create markdown documents. It is difficult to comment on the proposals @swarnimarun .

**Comment by turtletooth** [comment]
I'd like to add some nodes to the Visual Script system but I want feedback before I start implementing it.

I'd like to add some nodes that abstract away some of the complication of visual scripting to make it more accessible and bring the difficulty of visual scripting closer to that of GameMaker.

Some possibilities include a two way input node that returns a float based off of input. Also, a four way input that returns a Vector 2.

The idea is just to simplify some of the common actions and reduce the number of nodes required to do some of the basic tasks.

I'd like to see this included in Godot and not as an addon to make Visual Scripting as accessible as possible for folks.

I realize most of the talk here right now is in the UI of visual scripting, and I don't mind working on these on the side.

Thoughts?

**Comment by turtletooth** [comment]
I was thinking of making those without any input ports, but having the actions selected in the sidebar, like the action node right now.  

Are you looking at having any built in group nodes, again to abstract away some of the complexity for new users?

**Comment by fire** [comment]
One of the pending ideas is removing the sidebar, and using control - f (generic search) for everything. Can you make a new proposal and draw a design?

We can bundle the various combined nodes we have and will have as "visual script nodes". We already have a long list of bundled nodes.

**Comment by turtletooth** [comment]
Other nodes that come to mind might be:
restart current scene
quit
load scene

I realize that those can be done with just a couple nodes, but for some users having a single node would simplify things a lot.

**Comment by turtletooth** [comment]
I'm wondering if "combined nodes" still will confuse new users.  If there are some helper nodes to take care of some basic functionality that will make visual scripting easier to adopt for non-programmers or for example in schools (I teach middle school).

**Comment by fire** [comment]
Imagine that we can double click into the nodes and see how they work and the combinations show in the debugger too.

**Comment by turtletooth** [comment]
Got it.  I like it.

**Comment by Jummit** [comment]
Closing and maybe rewriting later to follow #10

**Comment by fire** [comment]
I highly recommend making a SEPARATE issue per task.

**Comment by Norrox** [comment]
i really would like to see Reroute graph connections, that will make clean up the VS much easier

**Comment by Jummit** [comment]
For the time being you can use this:
https://github.com/swarnimarun/visual-scripting-node-library/
