### ISSUE TITLE
Improvement for default 3D view.

### ISSUE THREAD

**Issue by Neo6666666** [godotengine/godot-proposals#30]
When you start editor, and open 3D view, first what you see it's a poorly looking emptiness and not good at all "horizon". Then you add spatial and your custom mesh, and what we see? A shabby picture - without any worthy lightning and post process shaders. 
SO:
My proposal is make a start scene like UE4, Blender or even Unity. With nice looking lightning, camera, post process shaders and some billet (ingot) like default cube in Blender.

**Comment by clayjohn** [comment]
Please update your post in accordance with the provided template. All posts not following the template will be closed.

**Comment by groud** [comment]
Sorry, there is an issue template, please fill in it with an accurate, precise and detailed description of the proposal. Vague proposals are not accepted on this repository, which was created to store high quality proposals, having a use case and a draft of what could be the implementation.
