### ISSUE TITLE
Make `add_child()` function return the name of the Node it creates

### ISSUE THREAD

**Issue by CopperyMarrow15** [godotengine/godot-proposals#3001]
### Describe the project you are working on

a 2D platformer with many Nodes being created with `addchild()`

### Describe the problem or limitation you are having in your project

I want to be able to mess around with a certain Node after I create it, and storing the Node's name in a variable would help with that.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Instead of returning `null`, `add_child` will return the name of the Node it creates when called.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

That makes it easy to do stuff like this.
```
new_node_name = add_child(Sprite.new(), true)
new_node_name.texture = res:\\example.png
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but it's weird and tedious.

### Is there a reason why this should be core and not an add-on in the asset library?

Science isn't about why. It's about why not!

**Comment by timothyqiu** [comment]
According to the code snippet, I think you mean "return the child node itself"?

```gdscript
var node = Sprite.new()
new_node = add_child(node, true)  # new_node should be node?
```

**Comment by CopperyMarrow15** [comment]
> According to the code snippet, I think you mean "return the child node itself"?
> 
> ```gdscript
> var node = Sprite.new()
> new_node = add_child(node, true)  # new_node should be node?
> ```

If I understand you correctly, no. `new_node` should be `"Sprite0"`, the legible, unique name given to it when it is created. Perhaps, I don't understand something about the `add_child()` function itself. I wouldn't doubt that as most of the tutorials and documentation on it are quite ambiguous.

**Comment by pycbouh** [comment]
Your example isn't valid code:
```
new_node_name.texture = res:\\example.png
```

Even if `add_child` was to return the name of the node, this code wouldn't work. You need to have a reference to the node in order to change its properties, just like @timothyqiu shown. All you could use the name for in this example is to get that reference using `get_node(new_node_name)`, but that's unnecessary since you already have the reference and can store it as shown by timothyqiu.

**Comment by Xrayez** [comment]
This was previously discussed at godotengine/godot#6521 and https://github.com/godotengine/godot/issues/26542#issuecomment-469076107. Godot implicitly follows single responsibility principle in this regard, the problem is that it's not documented.

**Comment by dalexeev** [comment]
```gdscript
add_child(node)
print(node.name)
```

**Comment by CopperyMarrow15** [comment]
The entirety of this issue was created due to a misunderstanding of Godot's `add_child()` function. To anyone viewing this in the future with a similar problem to myself, read the above comments. They do indeed perform as advertised.
