### ISSUE TITLE
Create separate enums for Joypad Buttons and Joypad Axes

### ISSUE THREAD

**Issue by cgbeutler** [godotengine/godot-proposals#3002]
### Describe the project you are working on

I am working in C# on some input caching for combo moves.

### Describe the problem or limitation you are having in your project

Currently, the JoystickList enum contains definitions for all buttons and axes in the same enum. This means the enum is kinda representing two different sets of items. This is evident by the fact that `AxisMax` exists with a value less than others in the enum.
This would be fine, but it introduces strange stuff when working with `System.Enum` functions in C#. For example,  `System.Enum.GetName(typeof(JoystickList), ev.Axis )` returns `Button0` instead of `Axis0`. This affects the `ToString` method for the enum as well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice to separate out the Axes enum into its own thing.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Pretty sure it just involves splitting the enum in two.
It may be worth splitting it in main Godot as well as the C# side, as future enum helpers will be easier to use then.
All the places I've seen axes and buttons used are separate anyway, so future typing would likely not be negatively affected.
I imagine two enums called `JoystickButtonList` and `JoystickAxisList`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Currently, to do a proper `ToString` and `System.Enum.IsDefined` and stuff, I found it easiest to just define my own separate enum that I cast to first. For IsDefined to work properly, my custom enums also leaves out `AxisMax` and `ButtonMax`, (though that may be a separate proposal?)

### Is there a reason why this should be core and not an add-on in the asset library?

Making it an add-on would then require checking and casting everything that came from core. I'm doing it now and it is a little cumbersome.

**Comment by madmiraal** [comment]
This has already been implemented on master as part of https://github.com/godotengine/godot/pull/38151 (https://github.com/godotengine/godot/pull/38151/commits/e7fee711b3d2417720ecfae86bc9351927f6daa0)

**Comment by Calinou** [comment]
Closing, as this is now implemented in `master` by https://github.com/godotengine/godot/pull/38151. Since this change breaks compatibility, it can't be backported to `3.x`.
