### ISSUE TITLE
Display the mouse coordinates in the 2D editor

### ISSUE THREAD

**Issue by damzen** [godotengine/godot-proposals#3007]
### Describe the project you are working on

2d project

### Describe the problem or limitation you are having in your project

No 2D coordinates listed in the editor dock,  in relation to realtime mouse position in 2D editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Label of the 2D coordinates of the current mouse position (updated realtime as mouse moves) to show current mouse coordinates in both 2D and 3D scenes. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Current mouse position is set to a label in the editor. This runs realtime (delta). Everytime mouse moves the coordinates update.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

editor plugin, but so far not implemented.

### Is there a reason why this should be core and not an add-on in the asset library?

Because it is used by every developer all the time when editing 2d and 3d scenes.

**Comment by Calinou** [comment]
For 2D, this is implemented by https://github.com/godotengine/godot/pull/47865.

For 3D, there is no easy way to map 2D mouse coordinates to 3D world coordinates, but you can enable **View Information** in the 3D editor's Perspective menu (in the top-left corner of the viewport). This will display the camera's coordinates in the bottom-right corner.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/54687 (see comments in https://github.com/godotengine/godot/pull/47865 as for why that original idea was rejected).

**Comment by crayonape** [comment]
Maybel it's late, but for anyone like me who needs to observe the coordinates of the nodes in a pixel game, I made a small addon for this.

![image](https://github.com/user-attachments/assets/3b2add28-a8ec-4ac4-8c00-4283f492224a)

https://github.com/crayonape/GodotMouseCoordinates
