### ISSUE TITLE
Accessing Port from GraphNode

### ISSUE THREAD

**Issue by mechPenSketch** [godotengine/godot-proposals#3009]
### Describe the project you are working on

[Finite State Machine](https://github.com/mechPenSketch/FiniteStateMachine), specifically in this context its main screen editor.

### Describe the problem or limitation you are having in your project

I can't drag the port of the GraphNode except by clicking directly on it. My intention is for the user to be able to port drag simply by clicking and dragging from either edge of the GraphNode.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add new methods in the GraphEdit that redifines what a hot zone is to click and drag a connection port.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

On the GraphEdit's cpp file, add two methods:

For input:
```
bool GraphEdit::is_in_input_hotzone(GraphNode gn, int i){
    Vector2 pos = gn->get_connection_input_position(j) + gn->get_position();
    return is_in_port_hotzone(pos / zoom, p_point / zoom);
}
```

and output
```
bool GraphEdit::is_in_output_hotzone(GraphNode gn, int i){
    Vector2 pos = gn->get_connection_output_position(j) + gn->get_position();
    return is_in_port_hotzone(pos / zoom, p_point / zoom);
}
```

Where `is_in_port_hotzone(...)` is renamed from `is_in_hot_zone(...)` to specify that the hot zone is related to the port by position.

`is_in_input_hotzone(...)` and `is_in_output_hotzone(...)` can then be exposed to be overridden if users want to redefine where the hotzone is, whether it would involve a port's position or not. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can think of a few:
1. Adjusting the port offset as well as setting the port texture as a large transparent block. However, I will need to get the texture height right or there will be an awkward situation where by mousing over the edge where the texture doesn't overlap with the area of the GraphNode, the hover effect could appear, but clicking won't work. I would also have to re-adjust the texture's height should more than one line be used.
2. Restarting the main screen FSM from scratch where instead of using GraphEdit and GraphNode, I use a combination of PanelContainer, LineEdit and Line2D. Please don't make me restart from scratch.
3. I could also call `draw_line(...)` from GraphEdit when I click and drag from the area I want. However, to match line's style with the connecting line produced from GraphEdit, I have to code it all over from scratch, as GraphEdit's `_draw_cos_line(...)` is not exposed to gdscript.

### Is there a reason why this should be core and not an add-on in the asset library?

Because I can't find any methods in GraphEdit or GraphNode that lets me drag a port without clicking on it.

**Comment by pycbouh** [comment]
I am not sure what you propose those methods should return. Slots/ports are not entities, and drag detection is just a bunch of hotzones calculated as click and drag events happen.

**Comment by mechPenSketch** [comment]
I was hoping that the slots are ImageButton I can access, but it looks like I have a long way :(

I'm now looking at [GraphNode](https://github.com/godotengine/godot/blob/master/scene/gui/graph_node.cpp). Here are my observations:
* There is a class Slot.
* There is a recurring var slot_info
Maybe expose Slot as a class and slot_info as GraphNode's property?

**Comment by pycbouh** [comment]
Yes, there are data abstractions, and yes, there are image textures, but the interaction doesn't happen with them directly. When you click or drag this data can be used to create rectangles for interactivity areas. But those are not buttons.

**Comment by mechPenSketch** [comment]
Does the indirect interaction means the ports' properties (like their positions/offsets) are used instead? If that's the case all along, then I don't really to access the ports to begin with.

I'm currently looking for a the method that draws a line from a port to the mouse's position (or vice versa). I can't find anything that resembles that in GraphNode's `_gui_input` or `_notification(NOTIFICATION_DRAW)`. However, [GraphEdit's](https://github.com/godotengine/godot/blob/master/scene/gui/graph_edit.cpp) `_notification(NOTIFICATION_DRAW)` have the method `draw_line`. Maybe that's what need to be exposed.

**Comment by pycbouh** [comment]
@mechPenSketch Yes, connection lines are drawn on a special `connection_layer` control inside of the `GraphEdit`. Yes, it does use a function to create a (Bezier) curve.

**Comment by mechPenSketch** [comment]
For `_top_layer_draw()` in GraphEdit to `_draw_cos_line(...)`, it needs to check for `connecting`. The only function that sets `connecting` to true is `_top_layer_input`. Maybe parts of  `_top_layer_input` should be split into separate functions that are to be exposed and called.

Or since `is_in_hot_zone(...)` decides whether `connect` would be set to true, it should be the one exposed so that I could override it. However, `is_in_hot_zone(...)` is using other variables and functions that I might need to expose as well...

Either way, I need to read and understand them first...
