### ISSUE TITLE
Editor setting for adding project settings to basic mode

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot-proposals#3015]
### Describe the project you are working on

A few projects that utilize project settings that are classified as advanced

### Describe the problem or limitation you are having in your project

I like disabling advanced mode because it hides away all the complicated settings (things like buffer size, sample count, platform overrides, etc), which is really nice for people who are easily overwhelmed.
However there are some settings that don't count as basic that I use, such as `editor/node_naming/*`, and `editor/run/main_run_args`. I wish that I could utilize the power of hiding away confusing and complicated settings, while still maintaining settings that count as "advanced" that I use often.
The ability to add custom project settings to basic mode would help merge these two cases together, and allow a more dynamic spectrum rather than a distinct binary between basic and advanced.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As people become more advanced they may want to gradually adapt to new settings they learned, so there should be an editor setting for adding certain project settings to appear when in basic mode.

Pros:
- Allows people who use the engine to gradually adapt to more project settings in basic mode, instead of forcing them to pick a binary between "basic" and "advanced"
- Would make it easier for Godot engine developers to pick reasonable defaults for basic/advanced modes that work for everyone, since if some don't like them, they still have the option to customize.

Cons:
- Adds a editor setting that people might not use (There's already a lot of those anyways. Just add advanced mode to editor settings as well 🙂)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add editor setting called "Basic Project Settings Overrides", that lets you specify a list of project settings (comma seperated probably), that will then show up in basic mode of project settings.
Would use `ProjectSettings::get_singleton()->set_as_basic(p_var, p_basic);` to set them when you save the editor setting.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Whenever you want to change a project setting that isn't in basic mode, you can:
- Activate advanced mode
- Find the setting and change it
- Disable advanced mode

When doing this for every new project (in the case of `editor/node_naming`), or often (`editor/run/main_run_args`), this easily becomes a hassle.

### Is there a reason why this should be core and not an add-on in the asset library?

Don't think it's possible as a add-on

**Comment by pycbouh** [comment]
You already know that this issue exists, but for the sake of completeness we are looking into adjusting which settings are considered basic in a tracker here: https://github.com/godotengine/godot/issues/50620.

It is better that we tweak which settings are often required for the majority or make the most sense to be handy, than to make this into a complicated system like proposed here, IMO.

**Comment by Calinou** [comment]
Closing due to lack of support (see lack of reactions on OP and general lack of activity here).
