### ISSUE TITLE
Add an editor setting to adjust the property value dragging sensitivity in the inspector

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#3017]
### Describe the project you are working on

General editor use.

### Describe the problem or limitation you are having in your project

Dragging an inspector value in the editor steps it up/down in tiny increments, there should be a setting that allows the user to customize the amount the value is increased/decreased.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For isntance, it makes it so the user doesn't have to drag the mouse the equivalent distance of 3km to adjust a transform position by 100 pixels.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/16231628/126311653-841a7c2a-dce1-45e6-85f0-d0a046bf9099.png)
![image](https://user-images.githubusercontent.com/16231628/126311738-7fcbc7ed-e905-4b78-b352-98117ecad7c4.png)
![image](https://user-images.githubusercontent.com/16231628/126311773-ec0b7928-5d2a-4212-8031-12547d7497d7.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it must be editor-side.

### Is there a reason why this should be core and not an add-on in the asset library?

Because it should be in the settings menu.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/29.

**Comment by elvisish** [comment]
This is really the same issue as [#2760](https://github.com/godotengine/godot-proposals/issues/2760) and I'm proposing an editor setting multipler, not a key modifier.

**Comment by Calinou** [comment]
> as I'm proposing an editor setting multiplier, not a key modifier. An editor setting would mean the user could custom set the global EditorSpinSlider drag speed without having to hold any keys at all.

We try to favor usability patterns that can work automatically, without requiring users to adjust settings that will work well for some properties and poorly for others. Nobody wants to spend hours tweaking editor settings depending on what they're doing :slightly_smiling_face:

**Comment by winston-yallow** [comment]
but these are not mutually exclusive? Even if the other proposal get's implemented, I would still want to be able to adjust the base speed as this proposal suggest.

**Comment by Calinou** [comment]
Note that holding down <kbd>Ctrl</kbd> generally makes dragging go faster with float values;

**Comment by winston-yallow** [comment]
That should not make it go faster, it still does the same `grabbing_spinner_dist_cache += diff_x;` in that case. The value is only rounded for the `set_value()` call, not for the internal cache. So the speed should stay the same

**Comment by elvisish** [comment]
`We try to favor usability patterns that can work automatically, without requiring users to adjust settings that will work well for some properties and poorly for others. Nobody wants to spend hours tweaking editor settings depending on what they're doing `
This would suggest to me that the base speed needs increasing as a default (since it is practically unusable in its current form), then no one would have to tweak a setting if they didn’t want to, but the option is there for the few users who might.

`Note that holding down Ctrl generally makes dragging go faster with float values, since it snaps the value to integers.`

Try it, it does not make it go faster (if anything it makes it go slower)

**Comment by elvisish** [comment]
Was this added?

**Comment by Calinou** [comment]
> Was this added?

No, as https://github.com/godotengine/godot/pull/50671 wasn't merged yet.
