### ISSUE TITLE
Add `global_position` and `global_rotation` properties to Node3D

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot-proposals#3033]
### Describe the project you are working on

3D game

### Describe the problem or limitation you are having in your project

It's annoying and unintuitive having to go through global_transform to change global position and global rotation

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be great if there was `global_position` and `global_rotation` for Node3D. These already exist for Node2D so it would fill in a missing gap of properties when moving from 2D to 3D.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would add a `global_position` and `global_rotation` property to Node3D that you can use to get or change the global position or global rotation of the node

### If this enhancement will not be used often, can it be worked around with a few lines of script?

getting global position: `global_transform.origin`
setting global position: `global_transform.origin = new_pos`
getting global rotation: `global_transform.basis.get_euler()`
setting global rotation:
`rotation = (get_parent().global_transform.basis.inverse() * Basis(new_rot)).get_euler()`
(probably simpler way to do it)

### Is there a reason why this should be core and not an add-on in the asset library?

They should be core properties to complement `Node2D.global_position` and `Node2D.global_rotation` but for 3D

**Comment by aaronfranke** [comment]
> setting global rotation:
`rotation = (get_parent().global_transform.basis.inverse() * Basis(new_rot)).get_euler()`
(probably simpler way to do it)

`global_transform.basis = Basis(new_rot)`

**Comment by jitspoe** [comment]
Not sure if it's worth creating a new issue for this, but I noticed we have local/global versions of basis, position, transform, rotation, and rotation_degrees, but not quaternion or scale.  Might be worth adding them for completion.  I had to set the global_basis from a quaternion to effectively set the global_quaternion.

**Comment by Calinou** [comment]
There was a PR adding global scale properties, but it was closed: https://github.com/godotengine/godot/pull/55200

Note that there is already a `global_scale()` method, so the property would have to be named differently to avoid conflicts.
