### ISSUE TITLE
Define enum for `get_import_order()` of Resource importers

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-proposals#3034]
### Describe the project you are working on

A resource importer.

### Describe the problem or limitation you are having in your project

Similar filenames with different extensions seem to get imported in alphabetical order. For example, a .atlas file might get imported first and if it depends on a .png file to be loaded, ResourceLoader will return a null object when loading the .png file during the first import round, possibly corrupting the .atlas import the first time around if the null object is not properly caught.

To fix this dependency import issue, there's currently a `get_import_order()` virtual function defined in `ResourceImporter` that returns an integer. Lower values have import precedence.

Useful values for `get_import_order()` remain undocumented and undefined in the Engine code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Define an enum with useful values for the import order, and expose them to GDScript.

For example, `ResourceImporterScene` has an import order value of `100`, and a comment that states the Scene resource gets loaded "after everything".

This value could, perhaps be defined as `RESOURCE_IMPORTER_ORDER_SCENE = 100`, and documented.

It seems that most importers use a value of `0`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```cpp
enum  {
RESOURCE_IMPORTER_ORDER_DEFAULT = 0,
RESOURCE_IMPORTER_ORDER_SCENE = 100
};
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often in custom `EditorImportPlugin` that require other resources to be loaded first.

### Is there a reason why this should be core and not an add-on in the asset library?

This change has to be made within the engine just so the enumerations are available on `EditorImportPlugin`.

**Comment by Calinou** [comment]
`get_priority()` returns a float, but enums can only contain integer values.
