### ISSUE TITLE
Add a shortcut key to toggle Camera3D preview mode

### ISSUE THREAD

**Issue by developomp** [godotengine/godot-proposals#3039]
### Describe the project you are working on

I am making a 3d platformer that is meant to be a replica of a Minecraft parkour map.

### Describe the problem or limitation you are having in your project

I have only one, small screen so I only have two options:
- toggle camera preview mode with a mouse every time
- use split view to reduce the already small working area

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Toggles preview mode for the selected camera when <kbd>Ctrl</kbd>+<kbd>P</kbd> is pressed.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Toggles preview mode for the selected camera when <kbd>Ctrl</kbd>+<kbd>P</kbd> is pressed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, this can be worked around with an editor plugin, but it is a necessary feature that can be used by a huge range of people.

### Is there a reason why this should be core and not an add-on in the asset library?

This feature could be used very often by a huge range of people. In fact, this is my day one with the Godot engine and I still felt the need for it.

**Comment by Calinou** [comment]
Note that if you want the shortcut to work while the Camera3D node isn't selected, this will require more than just assigning a shortcut to the button in question using `set_shortcut()`.

**Comment by developomp** [comment]
I should have been more clear about this. As I have said in the suggestion, this feature will work ONLY when a camera is selected. This resolves any ambiguity and other problems.

**Comment by Calinou** [comment]
> I should have been more clear about this. As I have said in the suggestion, this feature will work ONLY when a camera is selected. This resolves any ambiguity and other problems.

I think it'd remove a lot of the convenience aspect if you have to select the camera before pressing the shortcut to toggle the preview mode.

**Comment by developomp** [comment]
Oh my GOD, this is unbelievably fast!!
I thought I had to wait at least a month but here we are. Getting the fix in just 2 days!!
