### ISSUE TITLE
Let users inspect Editor `ShortCut` objects to  in `EditorPlugin`

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-proposals#3044]
### Describe the project you are working on

An editor plugin

### Describe the problem or limitation you are having in your project

While writing a plugin I attempted to inspect the Editor shortcuts through GDScript, but `EditorSettings::shortcuts` map is not exposed.

The goal was to make sure that a shortcut I wanted to add to `InputMap` wasn't already used by the Editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to see what shortcuts are already used in the Editor to avoid duplicating those. `InputMap` is available to users and it's up to them to scan `InputMap` action list and events to see whether the shortcut they want to install has also been used there by other editor plugins.

A new function similar to `EditorSettings::get_shortcut_list` is required to be able to inspect the Editor shortcuts but this new function that implements this functionality should duplicates the underlying Editor `ShortCut` objects in memory (or perhaps just their respective `InputEvent` objects) to avoid letting plugin writes overwrite the Editor's memory. Let's call such function `EditorSettings::get_shortcuts()` which returns an array of duplicated `ShortCut` objects.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
tool
extends EditorPlugin

func _enter_tree():
    var input_event_key : InputEventKey = InputEventKey.new()
    input_event_key.set_shift(false)
    input_event_key.set_control(false)
    input_event_key.set_alt(false)
    input_event_key.set_scancode(KEY_F12)
    input_event_key.set_pressed(true)

    var found_shortcut : bool = false
    for shortcut in get_editor_interface().get_editor_settings().get_shortcuts():
        if shortcut.is_shortcut(input_event_key):
            found_shortcut = true
            break

    if not found_shortcut:
        # Users check if InputMap also uses input_event_key in one of its actions
        # If the shortcut wasn't found yet, then users proceed to install the shortcut as desired
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

User-made shortcuts can be installed with `InputMap` for their own `EditorPlugin` needs, but the problem is that currently it's impossible to tell whether the installed shortcut has been duplicated or not. If the shortcut is a duplicate, entering the shortcut will fire several functions that could have weird side effects that could be hard to debug.

### Is there a reason why this should be core and not an add-on in the asset library?

This change needs to happen in the engine because the data users need to inspect is not currently available through GDScript.

**Comment by pycbouh** [comment]
See also https://github.com/godotengine/godot-proposals/issues/2547 (or at least my comments on it).

**Comment by YuriSizov** [comment]
Let's unify it with https://github.com/godotengine/godot-proposals/issues/4112. I don't think we need a dedicated function, since we're exposing methods for manipulating shortcuts anyway, editing them should be allowed. (Though, of course, it should be done using dedicated methods, preferably).
