### ISSUE TITLE
Simplify the use of Input.get_action_strength by taking an opposite action

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-proposals#3052]
### Describe the project you are working on

Testing out Platformer / FPS

### Describe the problem or limitation you are having in your project

It's common to subtract two action strength values. Writing the code feels repetitive and long thanks to its name:

```gdscript
var horizontal = Input.get_action_strength("right") - Input.get_action_strength("left")
```

It's quite easy to reach the default soft line length guideline of 80 characters :(

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an second parameter to `get_action_strength` as the opposite action name.

```gdscript
var horizontal = Input.get_action_strength("right", "left")
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Something like this:

```gdscript
func get_action_strength(action, opposite_action=""):
    var strength = _get_regular_action_strength(action)
    if opposite_action:
        strength -= _get_regular_action_strength(opposite_action)
    return strength
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes.

### Is there a reason why this should be core and not an add-on in the asset library?

Subtracting two `Input.get_action_strength`s is a quite common task.

**Comment by Calinou** [comment]
Have you seen the new features added in `master` and backported to `3.x`? See [Controllers, gamepads and joysticks](https://docs.godotengine.org/en/latest/tutorials/inputs/controllers_gamepads_joysticks.html) in the documentation.

**Comment by timothyqiu** [comment]
Ah, that's neat! I indeed remember seeing a issue/proposal like this somewhere. But I couldn't find any when writing this proposal.
