### ISSUE TITLE
Backport NavigationServer to Godot 3.x

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot-proposals#3054]
### Describe the project you are working on

In multiple small games i have worked on, my biggest obstacle was dealing with pathfinding, especialy when it comes to multiple units moving around, and disabling certain sections of the navigation area.

### Describe the problem or limitation you are having in your project

The problem is that its really dificult for a beginner such as myself to make navigation work as i want it to, for example, lets say i have a tilemap as a child of a navigation2d node, the navigation area works as intended, but if i put a seperate object, lets say i load in a building during gameplay, thats consist of a staticbody, its very dificult to cut out the space it occupies out of the navigation area.
Also, when i have multiple units, they bump into each other and get stuck, offcourse its possible to deal with this in code by a more experienced developer, its almost impossible to deal with for a beginner.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For the first problem an easy way to cut out or disable a certain area out of the navigation area.
And the second problem a way to deal with multiple units getting a nav path at the same time, or maybe attach a special node that temporarily disables the navigation area it sits on.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Im not sure what the best way is to deal with these issue's.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think navigation is used in a lot of games, i think a lot of beginners run into the same issuess as i am.

### Is there a reason why this should be core and not an add-on in the asset library?

Navigation is part of the core, this proposal is an enhancement of navigation.

**Comment by Calinou** [comment]
There's ongoing work to backport the NavigationServer to `3.x`: https://github.com/godotengine/godot/pull/48395

It's unlikely to be ready for 3.4, but maybe for 3.5.

**Comment by barbaros83** [comment]
@Calinou thnx, didnt know 3.x was getting that backported, i hope it fixes the problems im having, last time i tried to work with it on 4.0 it was still very buggy.

**Comment by Scony** [comment]
This was merged to `3.x` already so, @Calinou I think we can close.

**Comment by pycbouh** [comment]
Resolved by https://github.com/godotengine/godot/pull/48395.
