### ISSUE TITLE
Add a property hint to indicate a set of properties is an array

### ISSUE THREAD

**Issue by groud** [godotengine/godot-proposals#3059]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

Several Godot objects (especially the TileSet resource) use a pattern to expose an array of properties. Usually using a `my_property_count` property to expose the size of the array and a set of properties like `my_property/12` for the elements of the array. While this kind of works, the inspector provides no way to remove an item from the array, reorder them, or create one at a given position. This, in some situations, makes things very tedious to edit.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The idea would be to be able to specify when a property is the size of an array, and which prefix uses the array elements.
This would allow the inspector to detect which properties are part of an array and provide a better interface featuring:
- A way to add elements at a given position in the array,
- A way to remove elements at any position,
- A way to reorder elements,
- If possible, pagination for big arrays.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We add a `PROPERTY_HINT_ARRAY_SIZE`, that would be applied to an INT property, and would have as the secondary argument the template string for the array elements. For example, something like `"my_property_%d`. 

Using an example from the TileSet resource, this would make something like:
`ADD_PROPERTY(PropertyInfo(Variant::INT, "occlusion_layers_count", PROPERTY_HINT_ARRAY_SIZE, "occlusion_layer_%d", PROPERTY_USAGE_EDITOR), "set_occlusion_layers_count", "get_occlusion_layers_count");`
As data relative to a layer are named following the template `occlusion_layer_%d/<property_name>`, each element could be identified in the property list and thus handled correctly by the inspector as an element array.

When reordering element, like, for example, moving the element 1 to the position 0, the inspector would simply search for all properties prefixed by `my_property_1/*` and assign their values to `my_property_0/*` instead, and vice versa. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core.

**Comment by LightningAA** [comment]
Silly question, but how is this different than the current system for exporting arrays, e.g. https://github.com/godotengine/godot/blob/master/editor/editor_properties_array_dict.cpp?

**Comment by groud** [comment]
Closing as implemented by https://github.com/godotengine/godot/pull/52277.

> Silly question, but how is this different than the current system for exporting arrays,

An array/dictionnary is a single property, for each element of this array/dictionnary, it can only contain one exposed item (you cannot group a set of properties as part of the same element). The type of the element is also chosen by the user.

This feature instead group a set of properties (and thus all their hints and usage flags) together into arrays elements. This makes it so the editor displays the correct type for each property. See this example, which could not be achieved with an exported array:
![Peek 08-09-2021 09-55](https://user-images.githubusercontent.com/6093119/132469541-1ca22e1b-6c90-4bbe-a541-0f476930cf8f.gif)
