### ISSUE TITLE
Add a project setting to use a custom executable for debugging

### ISSUE THREAD

**Issue by versenyi98** [godotengine/godot-proposals#3061]
### Describe the project you are working on

I am currently working on a car simulator using gdnative with godot-cpp.

### Describe the problem or limitation you are having in your project

I use gdbserver for debugging the C++ code. For one of my nodes I defined the `_get_property_list`, `_get` and `_set` functions. I wanted to put breakpoints inside the functions, but the `_get_property_list` function was called only when the Node was opened in the Remote tab in the engine. The engine was being debugged, the project started from the engine was not, so I couldn't use the breakpoint.

Also, I cannot debug GDNative and GDScript at the same time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a boolean field to the ProjectSettings. When checked, a custom executable should be used. Add another field for the custom executable's path.

Setting the custom executable path to a script, which starts the gdbserver with the project as the target solves my problem.

The script looks something like this:
```
exec gdbserver localhost:port godot --path path/to/project $@
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The new fields can be added in the core/project_settings.cpp:
```
ProjectSettings::ProjectSettings() {
...
	GLOBAL_DEF("debug/settings/use_custom_executable", false);
	custom_prop_info["debug/settings/use_custom_executable"] = PropertyInfo(Variant::BOOL, "debug/settings/use_custom_executable");

	GLOBAL_DEF("debug/settings/custom_executable_path", "");
	custom_prop_info["debug/settings/custom_executable_path"] = PropertyInfo(Variant::STRING, "debug/settings/custom_executable_path", PROPERTY_HINT_GLOBAL_FILE, "*.sh");
...
}
```

In the editor/editor_run.cpp check the bool flag, and use the chosen executable:
```
Error EditorRun::run(const String &p_scene, const String &p_custom_args, const 
...
	String exec;
	bool custom_executable = ProjectSettings::get_singleton()->get("debug/settings/use_custom_executable");

	if (custom_executable) {
		exec = ProjectSettings::get_singleton()->get("debug/settings/custom_executable_path");
	} else {
		exec = OS::get_singleton()->get_executable_path();
	}
...
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't think of any other solution.

### Is there a reason why this should be core and not an add-on in the asset library?

It affects the editor, which is core

**Comment by Calinou** [comment]
This can already be done with the `%command%` placeholder that was added in 3.4beta2.

Set **Main Run Args** in the Project Settings to `exec gdbserver localhost:port %command%`. (`--path` will be set automatically.)

**Comment by versenyi98** [comment]
I forgot to mention that I am using 3.3 but if it is already available in the newer version I can switch to the newer one, until then I can use the solution I mentioned.
Thanks :smile:
