### ISSUE TITLE
Change the default font to one that is readable when zoomed out in a graph edit . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3068]
### Describe the project you are working on

A 2.5D game, with barbarians, etc . . .

### Describe the problem or limitation you are having in your project

There's been many complaints, that the default font is almost impossible, to read, in a graph edit, when zoomed to level - 1 or, level - 2 . . I didn't know, but using a different font, Libre Baskeville ( Google Font ), or SeguiBL ( Windows, not MIT ) solves it . . .

So, this might be a big decision, Godot has Visual script, but now also Visual shaders, and I saw a tweet, there might be a Particle graph, really nice . . .

So, my suggestion is, maybe find a new font, for Godot 4, that looks good, when zoomed at level - 1, in ANY graph edit, and perhaps better, level - 2 . . It's been an on-going complaints, among graph edit users, going back many months, and finding a new font, bas. solves it . . . It's a big decision, major UI stuff, so it's for the people that have worked a ton, on the engine, to decide what it could see examples, of fonts that sort-of work, or so . . .

<img width="800" alt="Skærmbillede (10)" src="https://user-images.githubusercontent.com/83387915/127740626-dfe1c04f-98a9-4d6b-aeca-450e0746e79d.png">

<img width="800" alt="Skærmbillede (11)" src="https://user-images.githubusercontent.com/83387915/127740628-d44a5206-5307-4515-bae6-25e6ed2574a2.png">

<img width="800" alt="Skærmbillede (12)" src="https://user-images.githubusercontent.com/83387915/127740630-fed53589-1ab5-48e8-97b6-d1fbb2d34fd7.png">

And, Segui BL, a Windows font, that's also much more readable . . . Godot 4 is getting major UI improvements, was thinking the engine makers could find one, that works better, when zoomed in graph edit, atm. it's ' gibberish ' . . . It's as simple, as find a new font, the engine makers also like . . . Thanks . . .

<img width="800" alt="Skærmbillede (13)" src="https://user-images.githubusercontent.com/83387915/127740667-fef718b6-afd6-4ef7-a744-908d7ed0a491.png">

<img width="800" alt="Skærmbillede (14)" src="https://user-images.githubusercontent.com/83387915/127740668-4f3d2039-084c-40e9-945b-752d173a986d.png">

<img width="800" alt="Skærmbillede (15)" src="https://user-images.githubusercontent.com/83387915/127740669-75a27103-ab1c-47d2-b480-c091cac332dc.png">

Was thinking, since Godot 4 is getting some editor changes, well it might be nice to find a new font, that the engine contributors, and coders like, that is more readable, at zoom level - 1, perhaps zoom level - 2, since more people will use graph edit, given Visual shaders, and I THINK, the new Particle graph, not sure . . . Thanks . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Find a font, that the engine makers like, only request is, it is readable, when zoomed to level - 1, or level - 2, in any graph edit, can look like the current one, ie. a sort-of ' BIT ' look <3, not sure . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above images, the right font is all, it takes, then one of longest running complaints, for graph edit users, instantly disappear, thanks . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Again, one can get a different font, but one doesn't think, that would work, given the ' default ' font doesn't work . . One thinks, that would happen for any font, and it's quite obscure, to even fix it, one assumes Godot has a font, that is sort-of optimal, by default . . 

I've got no idea, what might look good, and fit the engine, there are many font, ton, of free Google Fonts, MIT, so on . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it'd be a small update, that makes working in graph edits, more useful, thanks . . .

**Comment by charlesmlamb** [comment]
So, it'll be a major change, for the engine, it could improve the UX <3

Done, that's my last request, right now I'm waiting for Godot 4 alpha, gonna report small bugs I find, or stuff, like a feature that makes the editor crash, that's prob. what I'll do, from now on . .

So, 10 / 10, hope you can find a ' Godot ' way, for these proposals, that's where I don't know the engine, as a well noob . . .

**Comment by Calinou** [comment]
When you have only a few pixels to display a font, there's only so much you can do. Switching to a bolder font weight won't improve things much.

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
