### ISSUE TITLE
Add Vector2Int and Vector3Int to C#

### ISSUE THREAD

**Issue by AndreSacilotto** [godotengine/godot-proposals#3071]
### Describe the project you are working on

Testing the engine resources

### Describe the problem or limitation you are having in your project

Don't want to use 3 floats (12 bytes) when I can use 3 ints (6 bytes). Not only that int functions are faster.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Faster functions.
Less memory usage.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here the raw code for Vector2Int that I make from a rewriting of the c# vector2.

I can do the vector3Int, too.

public struct Vector2Int : IEquatable<Vector2Int>, IFormattable
{

    public int x;
    public int y;

    private static readonly Vector2Int _zero = new Vector2Int(0, 0);

    private static readonly Vector2Int _one = new Vector2Int(1, 1);

    private static readonly Vector2Int _negOne = new Vector2Int(-1, -1);

    private static readonly Vector2Int _up = new Vector2Int(0, -1);

    private static readonly Vector2Int _down = new Vector2Int(0, 1);

    private static readonly Vector2Int _right = new Vector2Int(1, 0);

    private static readonly Vector2Int _left = new Vector2Int(-1, 0);

    /// <summary>
    /// Access vector components using their index.
    /// </summary>
    /// <value>`[0]` is equivalent to `.x`, `[1]` is equivalent to `.y`.</value>
    public int this[int index]
    {
        get
        {
            if (index == 0)
                return x;
            else if (index == 1)
                return y;
            else
                throw new IndexOutOfRangeException();
        }
        set
        {
            if (index == 0)
                x = value;
            else if (index == 1)
                y = value;
            else
                throw new IndexOutOfRangeException();
        }
    }

    /// <summary>
    /// Zero vector, a vector with all components set to `0`.
    /// </summary>
    /// <value>Equivalent to `new Vector2(0, 0)`</value>
    public static Vector2Int Zero => _zero;

    /// <summary>
    /// Deprecated, please use a negative sign with <see cref="P:Godot.Vector2.One" /> instead.
    /// </summary>
    /// <value>Equivalent to `new Vector2(-1, -1)`</value>
    public static Vector2Int NegOne => _negOne;

    /// <summary>
    /// One vector, a vector with all components set to `1`.
    /// </summary>
    /// <value>Equivalent to `new Vector2(1, 1)`</value>
    public static Vector2Int One => _one;

    /// <summary>
    /// Up unit vector. Y is down in 2D, so this vector points -Y.
    /// </summary>
    /// <value>Equivalent to `new Vector2(0, -1)`</value>
    public static Vector2Int Up => _up;

    /// <summary>
    /// Down unit vector. Y is down in 2D, so this vector points +Y.
    /// </summary>
    /// <value>Equivalent to `new Vector2(0, 1)`</value>
    public static Vector2Int Down => _down;

    /// <summary>
    /// Right unit vector. Represents the direction of right.
    /// </summary>
    /// <value>Equivalent to `new Vector2(1, 0)`</value>
    public static Vector2Int Right => _right;

    /// <summary>
    /// Left unit vector. Represents the direction of left.
    /// </summary>
    /// <value>Equivalent to `new Vector2(-1, 0)`</value>
    public static Vector2Int Left => _left;

    /// <summary>
    /// Constructs a new <see cref="T:Godot.Vector2Int" /> with the given components.
    /// </summary>
    /// <param name="x">The vector's X component.</param>
    /// <param name="y">The vector's Y component.</param>
    public Vector2Int(int x, int y)
    {
        this.x = x;
        this.y = y;
    }

    /// <summary>
    /// Constructs a new <see cref="T:Godot.Vector2Int" /> from an existing <see cref="T:Godot.Vector2Int" />.
    /// </summary>
    /// <param name="v">The existing <see cref="T:Godot.Vector2Int" />.</param>
    public Vector2Int(Vector2Int v)
    {
        x = v.x;
        y = v.y;
    }

    /// <summary>
    /// Returns a new vector with all components in absolute values (i.e. positive).
    /// </summary>
    /// <returns>A vector with <see cref="M:Godot.Mathf.Abs(System.Int32)" /> called on each component.</returns>
    public Vector2Int Abs()
    {
        return new Vector2Int(Mathf.Abs(x), Mathf.Abs(y));
    }

    /// <summary>
    /// Returns this vector's angle with respect to the X axis, or (1, 0) vector, in radians.
    ///
    /// Equivalent to the result of <see cref="M:Godot.Mathf.Atan2(System.Single,System.Single)" /> when
    /// called with the vector's `y` and `x` as parameters: `Mathf.Atan2(v.y, v.x)`.
    /// </summary>
    /// <returns>The angle of this vector, in radians.</returns>
    public float Angle()
    {
        return Mathf.Atan2(y, x);
    }

    /// <summary>
    /// Returns the angle to the given vector, in radians.
    /// </summary>
    /// <param name="to">The other vector to compare this vector to.</param>
    /// <returns>The angle between the two vectors, in radians.</returns>
    public float AngleTo(Vector2Int to)
    {
        return Mathf.Atan2(Cross(to), Dot(to));
    }

    /// <summary>
    /// Returns the angle between the line connecting the two points and the X axis, in radians.
    /// </summary>
    /// <param name="to">The other vector to compare this vector to.</param>
    /// <returns>The angle between the two vectors, in radians.</returns>
    public float AngleToPoint(Vector2Int to)
    {
        return Mathf.Atan2(y - to.y, x - to.x);
    }

    /// <summary>
    /// Returns the aspect ratio of this vector, the ratio of `x` to `y`.
    /// </summary>
    /// <returns>The `x` component divided by the `y` component.</returns>
    public float Aspect()
    {
        return x / (float)y;
    }

    /// <summary>
    /// Returns the cross product of this vector and `b`.
    /// </summary>
    /// <param name="b">The other vector.</param>
    /// <returns>The cross product value.</returns>
    public float Cross(Vector2Int b)
    {
        return x * b.y - y * b.x;
    }

    /// <summary>
    /// Returns the squared distance between this vector and `to`.
    /// This method runs faster than <see cref="M:Godot.Vector2Int.DistanceTo(Godot.Vector2Int)" />, so prefer it if
    /// you need to compare vectors or need the squared distance for some formula.
    /// </summary>
    /// <param name="to">The other vector to use.</param>
    /// <returns>The squared distance between the two vectors.</returns>
    public int DistanceSquaredTo(Vector2Int to)
    {
        return (x - to.x) * (x - to.x) + (y - to.y) * (y - to.y);
    }

    /// <summary>
    /// Returns the distance between this vector and `to`.
    /// </summary>
    /// <param name="to">The other vector to use.</param>
    /// <returns>The distance between the two vectors.</returns>
    public float DistanceTo(Vector2Int to)
    {
        return Mathf.Sqrt((x - to.x) * (x - to.x) + (y - to.y) * (y - to.y));
    }

    /// <summary>
    /// Returns the dot product of this vector and `with`.
    /// </summary>
    /// <param name="with">The other vector to use.</param>
    /// <returns>The dot product of the two vectors.</returns>
    public int Dot(Vector2Int with)
    {
        return x * with.x + y * with.y;
    }

    /// <summary>
    /// Returns the length (magnitude) of this vector.
    /// </summary>
    /// <returns>The length of this vector.</returns>
    public float Length()
    {
        return Mathf.Sqrt(x * x + y * y);
    }

    /// <summary>
    /// Returns the squared length (squared magnitude) of this vector.
    /// This method runs faster than <see cref="M:Godot.Vector2Int.Length" />, so prefer it if
    /// you need to compare vectors or need the squared length for some formula.
    /// </summary>
    /// <returns>The squared length of this vector.</returns>
    public int LengthSquared()
    {
        return x * x + y * y;
    }

    /// <summary>
    /// Returns the axis of the vector's largest value. See <see cref="T:Godot.Vector2Int.Axis" />.
    /// If both components are equal, this method returns <see cref="F:Godot.Vector2Int.Axis.X" />.
    /// </summary>
    /// <returns>The index of the largest axis.</returns>
    public Vector2.Axis MaxAxis()
    {
        if (!(x < y))
            return Vector2.Axis.X;
        return Vector2.Axis.Y;
    }

    /// <summary>
    /// Returns the axis of the vector's smallest value. See <see cref="T:Godot.Vector2Int.Axis" />.
    /// If both components are equal, this method returns <see cref="F:Godot.Vector2Int.Axis.Y" />.
    /// </summary>
    /// <returns>The index of the smallest axis.</returns>
    public Vector2.Axis MinAxis()
    {
        if (!(x < y))
            return Vector2.Axis.Y;
        return Vector2.Axis.X;
    }

    /// <summary>
    /// Returns a perpendicular vector rotated 90 degrees counter-clockwise
    /// compared to the original, with the same length.
    /// </summary>
    /// <returns>The perpendicular vector.</returns>
    public Vector2Int Perpendicular()
    {
        return new Vector2Int(y, 0 - x);
    }

    /// <summary>
    /// Returns a vector composed of the <see cref="M:Godot.Mathf.PosMod(System.Single,System.Single)" /> of this vector's components and `mod`.
    /// </summary>
    /// <param name="mod">A value representing the divisor of the operation.</param>
    /// <returns>A vector with each component <see cref="M:Godot.Mathf.PosMod(System.Single,System.Single)" /> by `mod`.</returns>
    public Vector2Int PosMod(int mod)
    {
        return new Vector2Int()
        {
            x = Mathf.PosMod(x, mod),
            y = Mathf.PosMod(y, mod)
        };
    }

    /// <summary>
    /// Returns a vector composed of the <see cref="M:Godot.Mathf.PosMod(System.Single,System.Single)" /> of this vector's components and `modv`'s components.
    /// </summary>
    /// <param name="modv">A vector representing the divisors of the operation.</param>
    /// <returns>A vector with each component <see cref="M:Godot.Mathf.PosMod(System.Single,System.Single)" /> by `modv`'s components.</returns>
    public Vector2Int PosMod(Vector2Int modv)
    {
        return new Vector2Int
        {
            x = Mathf.PosMod(x, modv.x),
            y = Mathf.PosMod(y, modv.y)
        };
    }

    /// <summary>
    /// Returns a vector with each component set to one or negative one, depending
    /// on the signs of this vector's components, or zero if the component is zero,
    /// by calling <see cref="M:Godot.Mathf.Sign(System.Single)" /> on each component.
    /// </summary>
    /// <returns>A vector with all components as either `1`, `-1`, or `0`.</returns>
    public Vector2Int Sign()
    {
        return new Vector2Int()
        {
            x = Mathf.Sign(x),
            y = Mathf.Sign(y),
        };
    }

    /// <summary>
    /// Returns this vector slid along a plane defined by the given normal.
    /// </summary>
    /// <param name="normal">The normal vector defining the plane to slide on.</param>
    /// <returns>The slid vector.</returns>
    public Vector2Int Slide(Vector2Int normal)
    {
        return this - normal * Dot(normal);
    }

    /// <summary>
    /// Returns this vector with each component snapped to the nearest multiple of `step`.
    /// This can also be used to round to an arbitrary number of decimals.
    /// </summary>
    /// <param name="step">A vector value representing the step size to snap to.</param>
    /// <returns>The snapped vector.</returns>
    public Vector2Int Snapped(Vector2Int step)
    {
        throw new NotImplementedException();
        //return new Vector2Int(Stepify(x, step.x), Stepify(y, step.y));
    }

    /// <summary>
    /// Returns a perpendicular vector rotated 90 degrees counter-clockwise
    /// compared to the original, with the same length.
    /// Deprecated, will be replaced by <see cref="M:Godot.Vector2Int.Perpendicular" /> in 4.0.
    /// </summary>
    /// <returns>The perpendicular vector.</returns>
    public Vector2Int Tangent()
    {
        return new Vector2Int(y, 0 - x);
    }

    public static Vector2Int operator +(Vector2Int left, Vector2Int right)
    {
        left.x += right.x;
        left.y += right.y;
        return left;
    }

    public static Vector2Int operator -(Vector2Int left, Vector2Int right)
    {
        left.x -= right.x;
        left.y -= right.y;
        return left;
    }

    public static Vector2Int operator -(Vector2Int vec)
    {
        vec.x = 0 - vec.x;
        vec.y = 0 - vec.y;
        return vec;
    }

    public static Vector2Int operator *(Vector2Int vec, int scale)
    {
        vec.x *= scale;
        vec.y *= scale;
        return vec;
    }

    public static Vector2Int operator *(int scale, Vector2Int vec)
    {
        vec.x *= scale;
        vec.y *= scale;
        return vec;
    }

    public static Vector2Int operator *(Vector2Int left, Vector2Int right)
    {
        left.x *= right.x;
        left.y *= right.y;
        return left;
    }

    public static Vector2Int operator /(Vector2Int vec, int divisor)
    {
        vec.x /= divisor;
        vec.y /= divisor;
        return vec;
    }

    public static Vector2Int operator /(Vector2Int vec, Vector2Int divisorv)
    {
        vec.x /= divisorv.x;
        vec.y /= divisorv.y;
        return vec;
    }

    public static Vector2Int operator %(Vector2Int vec, int divisor)
    {
        vec.x %= divisor;
        vec.y %= divisor;
        return vec;
    }

    public static Vector2Int operator %(Vector2Int vec, Vector2Int divisorv)
    {
        vec.x %= divisorv.x;
        vec.y %= divisorv.y;
        return vec;
    }

    public static bool operator ==(Vector2Int left, Vector2Int right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Vector2Int left, Vector2Int right)
    {
        return !left.Equals(right);
    }

    public static bool operator <(Vector2Int left, Vector2Int right)
    {
        if (left.x == right.x)
        {
            return left.y < right.y;
        }
        return left.x < right.x;
    }

    public static bool operator >(Vector2Int left, Vector2Int right)
    {
        if (left.x == right.x)
        {
            return left.y > right.y;
        }
        return left.x > right.x;
    }

    public static bool operator <=(Vector2Int left, Vector2Int right)
    {
        if (left.x == right.x)
        {
            return left.y <= right.y;
        }
        return left.x <= right.x;
    }

    public static bool operator >=(Vector2Int left, Vector2Int right)
    {
        if (left.x == right.x)
        {
            return left.y >= right.y;
        }
        return left.x >= right.x;
    }

    public static implicit operator Vector2(Vector2Int v)
    {
        return new Vector2(v.x, v.y);
    }

    public static explicit operator Vector3(Vector2Int v)
    {
        return new Vector3(v.x, v.y, 0);
    }

    public static explicit operator Vector3Int(Vector2Int v)
    {
        return new Vector3Int(v.x, v.y, 0);
    }

    public override bool Equals(object obj)
    {
        if (obj is Vector2 vector)
            return Equals(vector);
        return false;
    }

    public bool Equals(Vector2Int other)
    {
        if (x == other.x)
            return y == other.y;
        return false;
    }
    public override int GetHashCode()
    {
        return y.GetHashCode() ^ x.GetHashCode();
    }

    public override string ToString()
    {
        return $"({x}, {y})";
    }

    public string ToString(string format)
    {
        return $"({x.ToString(format)}, {y.ToString(format)}";
    }

    public string ToString(string format, IFormatProvider formatProvider)
    {
        return string.Format(formatProvider, "({0}, {1})", x.ToString(format), y.ToString(format));
    }
}

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes you can create the types, but when you try to export will not have the nice editor.

### Is there a reason why this should be core and not an add-on in the asset library?

Shaders have it and I think gdscript 2.0 will have too.

**Comment by AndreSacilotto** [comment]
#2297

**Comment by Calinou** [comment]
> Don't want to use 3 floats (12 bytes) when I can use 3 ints (6 bytes).

Integers are 32-bit in Godot.

**Comment by aaronfranke** [comment]
They already exist in C#, in the current master branch:

https://github.com/godotengine/godot/blob/master/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector2i.cs

https://github.com/godotengine/godot/blob/master/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector3i.cs

We could backport them to Godot 3.x, but it's not feasible to backport the GDScript versions, so it would be an awkward situation where C# would have integer vectors in 3.x but GDScript would not. Still, it may be worth doing anyway.

**Comment by aaronfranke** [comment]
Closing per the above. They are already in C# in the current master branch of Godot.
