### ISSUE TITLE
Make the highlight for the current argument in the script editor more obvious

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#3074]
### Describe the project you are working on

A game with scripts :)

### Describe the problem or limitation you are having in your project

Sometimes with functions that take a lot of arguments it's not always easy to tell what argument you're on. (I just realized there is an underline, but it's only one pixel and it's pretty much impossible to see).

Godot:
![image](https://user-images.githubusercontent.com/50304111/127788079-6f774366-d6ec-4871-b8ac-a294df5d0255.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the argument the cursor is currently over bold/underlined.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

VS Code:
![image](https://user-images.githubusercontent.com/50304111/127788080-c5c25914-cfa3-46aa-9875-e671512d9aa4.png)

Visual Studio:
![image](https://user-images.githubusercontent.com/50304111/127788942-78f6a788-8345-494f-ae21-ac80db374d45.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

The script editor is core.

**Comment by Calinou** [comment]
Tooltips can't feature more than one font style at a given time, so the only workaround to make the underline thicker.

**Comment by KoBeWi** [comment]
> Tooltips can't feature more than one font style at a given time

Unless they are custom.
