### ISSUE TITLE
GDScript operators should support variant types

### ISSUE THREAD

**Issue by vetu11** [godotengine/godot-proposals#308]
**Describe the project you are working on:**
Android GUI based game.

**Describe the problem or limitation you are having in your project:**

In my game, I need to load some objects in sequence. The `GameManager` class that I'm using uses methods from other classes to determine the next actions. These methods return an object in case it needs to be added to the tree and some times they return a flag in the form of a `String`. To check a flag has been returned I use:

`if current_message_sequence.get_step() == current_message_sequence.DELAY_STEP`

which raises the error

`Invalid operands 'Object' and 'String' in operator '=='`

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

Doing it like this saves me the need of loading more objects from the SQLite database that the ones I need while keeping the code simple: a column in the database specifies how the object should be generated, or a flag if it shouldn't.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

In Python, if you use the operand `==` in variables of different types it just returns `False`, as it should do.

![imagen](https://user-images.githubusercontent.com/26150190/70861529-64020780-1f2f-11ea-93d1-e86333c33c49.png)

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Yes, workarounds can be made, of course, but if you're doing dynamic typing you will use this often.

**Is there a reason why this should be core and not an add-on in the asset library?:**

GDScript is supposed to be language with dynamic typing, this is a critical feature of language like this.

**Comment by KoBeWi** [comment]
Related: https://github.com/godotengine/godot/issues/26375

**Comment by vnen** [comment]
We discussed this many times over the years. It was decided that when you're comparing different types it's very likely that it's a bug in your code, so it's better that it reports an error. There are not many valid cases where you need to compare with different types.

When you do need to compare different types, you can check the type first:

```gdscript
var step = current_message_sequence.get_step()
if step is String and step == current_message_sequence.DELAY_STEP:
```

This improves type safety in general and it's also helpful for the new optimized typed interpreter for GDScript.
