### ISSUE TITLE
Implement Per-Split Biasing options for Directional Shadows

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#3086]
### Describe the project you are working on

Large Landscape

### Describe the problem or limitation you are having in your project

Because 1 Biasing setting effects all the splits, having a large difference between the effective resolution of different splits, those that have lower effective resolution need larger biases to combat Shadow Acne, however as they are splits further away (usually), they don't have much issue with the added Peter panning that increasing the Bias has on them, but splits close up will have very clearly visible Peter panning.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By giving a separate Biasing setting for every split, one could have very long distance shadows that don't suffer from notable Shadow acne far away, and yet don't suffer from a severe case of Peter Panning close up.
With such additional settings, Close up where you've got the highest effective shadow map resolution, you can lower the Bias while not introducing Shadow acne, and for more distant splits, gradually increase the Bias to account for their lower effective shadow map resolutions while not producing easily visible peter panning

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just add 3 more Biasing options that are for the 2&3&4 splits that are used instead of the current bias, and making the current Bias be for 1st split.

To keep Compatibility, Split Biases could be set to 0 and in that state be treated as "use 1st split"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Rendering is core.

**Comment by Calinou** [comment]
This is already handled in `master` by intelligently computing biases for each split.

In `3.x`, this is handled by the **Bias Split Scale** property in DirectionalLight.

**Comment by mrjustaguy** [comment]
BSS doesn't offer the fine grain control which can be needed when there's a large disparity between split distances.

However after testing in Master, this issue doesn't seem to exist as it generally tends to have similar Acne levels regardless of the split disparity, so just tweaking the Standard Bias settings seems to work just fine and consistently across splits..

As this issue is somewhat niche and most people that would be stumbling upon needing something like this would probably be going 4.0 when it comes out anyway, I'm closing this proposal.
