### ISSUE TITLE
Information (Vector2) about the selected tile in the atlas.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#3093]
### Describe the project you are working on

A project for smartphone.

### Describe the problem or limitation you are having in your project

When you select a tile in the atlas, Godot does not tell you what its Vector2 is in the atlas. This information can be obtained at runtime using "GetCellAutotileCoord" but in the editor this information is not available making access to this information somewhat complicated.
In this gif you can see what I mean.

![gif gif](https://user-images.githubusercontent.com/19652075/128322329-0cf27346-164a-43b5-b7e7-df54c3dcba99.gif)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Obtain what was said before, the vector2 belonging to the selected tile in the atlas. That is, Godot shows that information in some way.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
One way to do this could be that when you hover and hold the cursor over one of the atlas tiles, Godot will display the corresponding Vector2.
![Captura](https://user-images.githubusercontent.com/19652075/128326744-6ba773ce-ee2b-4dee-b5c2-1f828f5c90ea.PNG)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure about this.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure about this.

**Comment by KoBeWi** [comment]
This is already implemented in 4.0:
![image](https://user-images.githubusercontent.com/2223172/128334341-98a7c4cf-a969-45be-9ca4-f6645268b9d0.png)

**Comment by Torguen** [comment]
Not for 3.x ? 😔

**Comment by KoBeWi** [comment]
4.0 has a completely new tile editor; the old one won't get any more improvements, only bug fixes.
