### ISSUE TITLE
Add an option to prevent the auto-expansion in the Scene Tree dock when selecting nodes in the scene

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#3095]
### Describe the project you are working on

An indie project in which the levels require many scenes of enemies, items etc ... and the tree becomes a nuisance.

### Describe the problem or limitation you are having in your project

When a node belonging to a subtree is selected in the main tree, the subtree is automatically expanded.
I suggest adding an option so that this only happens if the user does it manually, this could help to keep the tree somehow better organized, it also helps to move faster through the tree.
Notice the gif, when I select a node that is inside a collapsed node, the collapsed node expands automatically.
I suggest an option to avoid this and have the node only expand if the user expands it manually.
https://imgur.com/OAwqGZp

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The addition of an option in the "Editor configuration" section that allows the option to avoid the auto-expansion of the nodes in the tree.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The editor will check the status of the option before auto-expanding.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

No idea

**Comment by KoBeWi** [comment]
Is this something that would be toggled often? Sometimes you want to auto-expand and sometimes you don't (although personally the auto-expand doesn't bother me much). I just wonder if an editor setting is enough or maybe the option should be easily available like e.g. editor grid, which can be toggled with a button/shortcut.

**Comment by Torguen** [comment]
Could it be added individually for each node as long as this node has children? It could appear in the contextual menu of the node when the right mouse button is clicked. 

I think that in order of usability the best would be: 
1 in the context menu 
2 in the editor-in-chief directly, same as the grid option. 3 as an option in the editor menu. Number 
3 would be too expensive if it needed to be changed often (unless a keyboard shortcut was assigned). 

Maybe at certain times it is necessary to know in which subtree a node is located, then this option should be disabled and then the best thing will be to be able to do it quickly.

**Comment by KoBeWi** [comment]
So as I thought, having this option easily available would be useful. Setting it for each node is overkill, so we should have some button somewhere, common for 2D and 3D editor. Maybe it could be next to the list select tool.

**Comment by Torguen** [comment]
I see no problem adding it in that position.

**Comment by alwaysusa** [comment]
I'd like to see this implemented in a similar fashion to Blender - icons alongside every node that control visibility (already exists), selectable, and expandable (would only affect nodes with children of course). It's a very intuitive way of handling the tree view and allows for unique settings per node.

**Comment by adadgio** [comment]
I'd love to see this option as well. At a (not far along) normal development, everything gets quickly expanded when you navigate, to the point you're practically unable to find something in the tree to drag it in your scene because everything is expanded...

**Comment by KoBeWi** [comment]
It's implemented.
