### ISSUE TITLE
Create a function type INVOKE () of unity in godot engine c #.

### ISSUE THREAD

**Issue by kone9** [godotengine/godot-proposals#31]
**Create a function type INVOKE () of unity in godot engine c #.**
Invoke () is a function that allows us to call another function from time to time, it is very useful and although in Godot c # we have the corroutines, it would be nice to have a simple method like this to make things a bit easier. I leave a 3 minute video with a practical example of the procedure in unity.
https://www.youtube.com/watch?time_continue=160&v=sLYcVjWG2O8

**Crear un funcion tipo INVOKE() de unity en godot engine c#.**
Invoke() es una función que nos permite llamar a otra función cada cierto tiempo,es muy util y aunque en Godot c# tenemos las corrutinas,estaria bueno tener un metodo simple como este para fácilitar un poco las cosas.Dejo un video de 3 minutos con un ejemplo practico del procedimiento en unity.
https://www.youtube.com/watch?time_continue=160&v=sLYcVjWG2O8

**Comment by groud** [comment]
Sorry, there is an issue template, please fill in it with an accurate, precise and detailed description of the proposal. Vague proposals are not accepted on this repository, which was created to store high quality proposals, having a use case and a draft of what could be the implementation.

**Comment by kone9** [comment]
> Sorry, there is an issue template, please fill in it with an accurate, precise and detailed description of the proposal. Vague proposals are not accepted on this repository, which was created to store high quality proposals, having a use case and a draft of what could be the implementation.

Es que no hace falta tanta explicación a parte no tengo el conocimiento sino lo hago yo...Ustedes estan maltratando a la gente que propone cosas.....Pero esta bien por cosas como estas estoy usando UNITY chau

**Comment by groud** [comment]
That's ok. 
You have to understand that both this repository and the godot one are tools for the developers. They are here to help contributors deciding what to implement, and how. We decided not to accept feature requests that are not able to answers in the issue template to improve the feature requests quality, and avoid good feature requests being overcrowded with low quality ones.

**Comment by reduz** [comment]
@kone9 Este repositorio tiene un template que se te pide que sigas para abrir una discusión. Si no querés seguirlo, el issue se cierra. Las reglas son iguales para todos, si no pensás seguirlas, entonces sé feliz usando Unity.

**Comment by kone9** [comment]
> That's ok.
> You have to understand that both this repository and the godot one are tools for the developers. They are here to help contributors deciding what to implement, and how. We decided not to accept feature requests that are not able to answers in the issue template to improve the feature requests quality, and avoid good feature requests being overcrowded with low quality ones.

ok,thanks

**Comment by kone9** [comment]
> @kone9 Este repositorio tiene un template que se te pide que sigas para abrir una discusión. Si no querés seguirlo, el issue se cierra. Las reglas son iguales para todos, si no pensás seguirlas, entonces sé feliz usando Unity.
Las personas que usamos Godot y unity no tenemos vuelta atrás,posiblemente nunca dejemos de usar los 2..Hice otro repositorio con el paso a paso..

**Comment by Calinou** [comment]
For future reference, this proposal was recreated in #44.
