### ISSUE TITLE
Give escape characters a different color in the script editor

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#3104]
### Describe the project you are working on

A game with scrips :)

### Describe the problem or limitation you are having in your project

Escape characters blend in with regular characters:
![image](https://user-images.githubusercontent.com/50304111/128611185-35d693bf-bb09-4a80-b054-c29dfef9d1ee.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It's not a big deal, but giving escape characters a different color like other editors do would be a nice feature. It might also be helpful for beginners to realize that there's something special about those characters.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Mockup (I thought the green would make sense but I'm not sure about it, I think it might blend in too much):
![image](https://user-images.githubusercontent.com/50304111/128611088-a3100614-f0a1-4ea7-aa17-fb3d515371de.png)

VS Code example:
![image](https://user-images.githubusercontent.com/50304111/128611180-69cac66d-4ae3-4153-b1da-dc60508e80bf.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

The script editor is core

**Comment by Calinou** [comment]
We should probably reuse an existing color defined in the syntax theme rather than create a new one (such as `symbol_color`). This way, third-party syntax themes don't need to be updated to add yet another color.
