### ISSUE TITLE
Consider adding a ' Simple ', ' Medium ' and, ' Advanced ' Settings to Project Settings / Editor Settings . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3106]
### Describe the project you are working on

A 2.5D game, with barbarians, lore . . . .

### Describe the problem or limitation you are having in your project

I've been sort-of thinking, having a ' Simple Settings ' and, ' Advanced Settings ' might not be best way, to order the Editor Settings, made a proposal about that, but I wanted to suggest, an improvement . . .

I was well thinking, for adding settings, to the Editor Settings, one could have this, may-be also in Project settings, to sort of have layers, so it's more intuitive . . . That way, in say Advanced Settings, one would have the entire theme to edit, but it'd sort of quite long, with custom settings, and even sub-settings for boxes, so on . . .

<img width="646" alt="Idea 003" src="https://user-images.githubusercontent.com/83387915/128619619-37781f86-b476-4e1e-94c8-1a3d15bdbfc2.png">

I'm not sure it's necessary, but if I had to break down Editor settings, for beginners, mid - level and, advanced users, I'd may-be do that, since there are so many layers, in theme settings, having just two, sort-of makes it go from nothing, to everything . .

It's just an idea, also it could be sort-of cool, to be able to have simple control, medium controls and, then full, every setting control, at least for Editor settings . . . . Thx . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, I made a proposal, I just got to thinking this might be better, that said, I'm not sure . . . It'd allow a 100 % control over, how one worked in the settings, for the editor, with-out overwhelming the user and, make it easier to make custom editor settings <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like in Godot 4 current build, there are simple and, advanced project settings, it might not be relevant, for project settings, but for adding this feature, to editor settings, since there are many layers, for customizing the theme, it'd might be easier, to have sort-of three levels, to work on . . . Thx . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Uhh, never really sure, here . . . . I think, no . . .

### Is there a reason why this should be core and not an add-on in the asset library?

It's just an idea, hoping to get some feed-back, it'd just make it easier to organize the editor settings, at least I think so, might be well dumb or, so on . . . .

**Comment by charlesmlamb** [comment]
The problem is, for the Editor settings, or making a theme, there are sort of, so many layers, it is quite too much . . .

<img width="1598" alt="Skærmbillede (26)" src="https://user-images.githubusercontent.com/83387915/128619883-da8ee1ec-f07a-4e5b-baf2-763f5f5c0e90.png">

One can set basic settings, then over-all settings for style box, then sub-settings for each box . . I think I'd make three layers, beginner, medium and, sort-of advanced, so one can do simple customization, all way to, advanced stuff . . . :OO . .

Not sure it's necessary, for project settings, after trying to make a theme, there are sort-of three layers, very simple, then working on boxes, then, working on the settings, inside the boxes, etc . . . <3 . .

**Comment by mrjustaguy** [comment]
Intermediate, not medium.

However I strongly disagree with adding it, as Advanced Settings for beginners aren't important, and only the ones shown in the Simplified settings would matter to them, but if they had a need for using some of the Advanced Settings, they're probably not beginners anymore and have some idea of what all those extra settings that are exposed actually do, and even if they don't, they're far more capable of figuring it out compared to someone totally new to Game Development.

**Comment by charlesmlamb** [comment]
Well, it was for editor settings, bec. there are some crazy stuff, one can set icons, fonts inside boxes, it gets a bit ' advanced ' and, I don't think it makes sense for project settings, though I don't know, don't really understand all the stuff there, except the beginner stuff, resolution, bit more . . .

Sort-of, I tried the theme editor once, a few times, and the level of customization, is just mind - blowing . . It's 5 x more complicated, than project settings, imo . . . Thx . . .

**Comment by mrjustaguy** [comment]
Well Editor settings can't really be simplified without loosing the control that it's trying to provide.

**Comment by pycbouh** [comment]
> but if I had to break down Editor settings, for beginners, mid - level and, advanced users

That's not how we break them up. We break them up by "most used/more niche". Nothing to do with the experience level of the user, but the merit of the setting itself.

**Comment by pycbouh** [comment]
> Sort-of, I tried the theme editor once, a few times, and the level of customization, is just mind - blowing . . It's 5 x more complicated, than project settings, imo . . . 

Yes, it's a complex tool, but in 3.4 we've simplified the user path significantly. For the most common use-case you just need to 

* select the picker tool, 
* click on the control you wan to customize in the preview, 
* find the property you want to customize on the right,
* click on the plus button to override it and set its value,
* save the theme.

StyleBoxes are still a few more steps, I know, and can be overwhelming. Still something we can work on.

**Comment by charlesmlamb** [comment]
I like the new Theme editor, but at least on my computer, after ' copying ' the default theme, then saving it as .tres, and loading it, Godot 3.4 just crashed and, it didn't work, ie. after sort-of re-loading Godot, with the new theme, the program crashed, during the load phase, I never even saw the program . . Had to physically delete the theme, in the C:\\Godot folder, to get it working again . . .

Also, in Godot 3.3, the theme editor had this weird effect . . One could say, ' Copy the current theme as, basis for custom theme ' and, after doing that, saving that and, re-starting Godot 3.3, it was a bit weird, but the program looked different, it was like the ' vertical space ' over text was different, and it looked like text, in scene editor, was sort-of a few pixels, BELOW the default Godot theme, so I stopped using it . . .

Anyway, I also got tired of the theme editor, bec. everything required a re-start, to see what I'd done, and then I'd have to re-open the theme.tres and, then scroll to the place, in a menu, in a sub-menu, of a sub-menu to find what I'd tried to change and, then after changing that 1 - 2 color values, re-start the program, to see what had been done, and then click through a ton of settings, to change those, say for a color value, for ONE box, change that from 0-255, maybe from 10, to 8, then re-start . . . It just seemed so buggy, it was not worth the effort . . . And, the preview window at the bottom, doesn't help at all, if one wants to customize graph edit, one has to click, find a particular thing, in some sub-sub-sub-menu, then to even see it, re-start, over and, over . . . And, it just looked weird, mostly bec. the vertical spacing of text, compared to icons, was different . .

So, I think the theme editor sucks, mostly because it's a re-start, to see how anything looked, at least for graph edit and, second bec. it sort-of messed with the default theme, if one wanted to change that, a few place or, so . . :OO :OO . . .

Also, when I use the eye-dropper, to try and well change, the look of graph edit nodes, it doesn't work and, one has to go into a list, find the stuff one wants, and, it's one of well least intuitive ways, of just making the appearance different, of a program, every-thing required a re-start, of the program, and the preview window, is just not complicated enough, to really show what's going on, for real customization . . .

It's also really weird, you have to right-click, in res folder, click add ' New resource . . . ' then, you have to GUESS, there's something called theme, there, then make that, then double-click that, to open the theme editor . . . It's like it's been hidden, so you have to have lucky, to even find it . . .

Anyway, the new eyedropper doesn't work, for graph edit objects . . And, the user interface for the theme editor is so convoluted, it feels like 2 hours, of pain, the make well simple modifications, nothing is explained or, documented . . .

Well, it got some updates, when I try to use it, it doesn't work, and it's insanely difficult, to get it to do anything, and the little preview window, at the bottom, doesn't help, at least I've never seen anything change there, after trying to change a node box, in graph edit, etc . . I'd rather just not use it, everything that should take 2 - 3 minutes, takes 30 - 60 minutes, that's too long, and who cares, at that point, about the UI . . .

Also, when I use the eyedropper, in 3.4, and click something, NOTHING happens . . . When I click ' Add preview ', it opens the res folder, with no explanation, of what I'm supposed to even open and, well I stopped caring, it's not worth it, nice as the updates are, I've got no clue how to change anything and, if I open a theme, then save it, Godot just crashed, after setting it as custom theme, before even opening, ie. it crashes when the DOS terminal is there . . .

Then I click the ' + ' icon, and get the list, I want to change Visual script, cool, I have to know, it's called ' graphedit ', then add that, nice settings are there . . . Then, when I click to change them, say for a test make the grid lines yellow or, red . . . Then, there's no visual update, I try and save the theme, and in 3.4, after reloading it, it crashes during program boot . . .

I give 2 / 10, for this feature, so far, it's been so frustrating, I'd rather not try, after spending 1 hour, trying to get the new one working, after finally figuring that, it was even there, in Godot 3.3 . . . Also, the little preview window, is one of dumbest things, bec. one can customize the ENTIRE program, and one can't see every single different box, or stylebox, in that little window . . . It's like the worst preview ever, bec. the program is so big, suppose I change an icon, in say graph edit, where is THAT, in the preview window . . 

So, just now, made a new theme, tried to change graphedit settings, after loading that, as custom theme, Godot just crashes, hard reset, and after booting it again, it's back to default theme . . . It's just, completely ' obscure ', how the feature works, atm . . .

**Comment by charlesmlamb** [comment]
Then, to change a feature, I don't know if it works, bec. it just crashed, when I try and use the custom theme, I have to click some weird ' + ', with no explanation I have to do that, then after doing that, it looks like I've added what I need, say graphedit, to make it less ' wonky ' or, off . . THEN, to change it I have to click ' + ', AGAIN, in the new list . . THEN, I FINALLY get what was like the Theme editor from Godot 3.3 and, there's no explanation, what order you have to click or, why to click any-where . . It says ' Add preview ', and instead of getting a list, of say ' GraphEdit ', one just gets the res folder, with ZERO explanation as to what a ' preview ' is called, is it called new_preview.prev, or so . . . So, it's all guess-work, and if I had to say anything, the user experience in Godot 3.4, is two steps backward and, more complicated . . Sadly, oh well . . . :OO . .

Also, I don't have a weird computer, don't 'need' it . . Got a new HP laptop, 5800H, nVidia 3070 RTX, top-of-line stuff, fairly fast . . . And, it crashes much more, than Godot 3.3, that just seemed unable, with the ' Save current theme as basis . . ', to even mess that up, bef. one got started . . . 

Can't really think of something I've used, that makes less sense, is more difficult to find when, you finally do, even the simplest thing takes hours, and it crashes, non - stop . . . So far, I haven't been able to make the grid lines less opaque, in graphedit, it has 30 / 30 times crashed, even for trying to LOAD the new theme, after saving it . . . And, there's ZERO explanation, documentation, for how I'm supposed to do it or, why it crashes . . . So, from my test, it's gotten 3 x worse, since Godot 3.3 but, maybe if there was documentation, so had some idea, WHY it crashes . . .

There's a bunch of buttons, settings . . They're all weird, nothing is where you expect and, when you finally after 30 minutes TRY to load a theme, every-thing crashes . . Imo, the feature is so far from done, might as well call it ' test ' code or, early-early-beta-don't_try-buggy-crash_prone :OO

**Comment by charlesmlamb** [comment]
Also, finally figured the eye dropper, I thought one could click, ANYWHERE in the program, to change something, then it took me to correct place, in the theme editor . . But, no one can click in the little preview window, and select stuff there . . Why, those are some of most basic settings, and most people could find them in 3.3 theme editor, fairly fast . . . So, if the eyedropper tool allows one to find something, in the preview window, for theme, and not the entire program, and there's so few things, in the preview window, why bother . . . I mean, you can change most of those settings, that one needs, basic editor color, font . . In the editor settings, and one gets an instant preview . .

So far, I've only had crashes, not ONCE has the 3.4 theme editor worked . . . It's like the 3.3 editor, but more complicated, and atm bit buggy . . As in, it crashes all the time, Godot refuses to boot or, just plain crashes . . ZERO documentation and, the new stuff added to ' theme editor ', makes it more complex, and it now takes LONGER, to do what one wanted, in 3.3 . . . So, I'm not gonna change the theme, it's one of most frustrating things, can't think of a single feature I've ever used, that was more obscure and, buggy, there was ONE program, sort-of ever, but I forgot it's name, something that non-stop crashed, didn't work and, well doesn't matter, forgot the name . . . :OO :OO . . .

**Comment by Calinou** [comment]
Closing due to lack of support. Having 2 levels of setting complexity is considered sufficient for now, and it's very uncommon for software to support more than 2.
