### ISSUE TITLE
Add a "Close Doc Tabs" context menu option in script editor tab list

### ISSUE THREAD

**Issue by regakakobigman** [godotengine/godot-proposals#311]
**Describe the project you are working on:**

A game where I open a lot of doc tabs while working.

**Describe the problem or limitation you are having in your project:**

The script editor has a list of open tabs, including doc/help tabs. Clicking a link will open it in a new tab by default, so it's easy to quickly amass a large amount of doc tabs. There is no way to quickly close these tabs without closing every tab, which is time consuming and tedious.

There are already context menu options to close one tab, close all tabs, or close all tabs except one. I propose there could be another option that only closes doc tabs, and leaves script tabs untouched.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

This feature would make it easy to instantly clean out all no-longer-needed doc tabs, without affecting any script tabs you might have open. It would solve a small but common frustration.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

A new context menu option titled 'Close Doc Tabs' could be added below the other options in the tab context menu:

![image](https://user-images.githubusercontent.com/42157525/70959712-efbc8680-204a-11ea-9696-fadd1e9e6bdd.png)

**Describe implementation detail for your proposal (in code), if possible:**

I don't know, but it could be simple enough for a junior job.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

There is no easy workaround that I know of, besides just right clicking on the doc tabs individually and closing them.

Note: you can select the bottom most tab and repeatedly press Ctrl-W, but the most recently opened tab will be re-focused each time, so this is still tedious and error-prone.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It's a small feature, and (AFAIK) wouldn't be easy to fix without forking the engine.

**Comment by Calinou** [comment]
I think we could implement this in a more general manner by adding a **Close Tabs Below** option, like we already have for scene tabs (where we have **Close Tabs to the Right**). Since documentation tabs always appear below script tabs, you could use this option on the last script in the list.

**Comment by bojidar-bg** [comment]
We actually already have that option -- it is just not in the context menu.
![image](https://user-images.githubusercontent.com/5276727/70990621-9d24ae00-20ce-11ea-9116-cba439689d29.png)

**Comment by regakakobigman** [comment]
@Calinou That sounds like a good solution, especially because 'Sort Tabs' is also an option.

@bojidar-bg That's even better. That could be added to the context menu, too.
