### ISSUE TITLE
Rename Particles to GPUParticles to avoid confusing with CPUParticles . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3110]
### Describe the project you are working on

A 2.5D game, with barbarians . .

### Describe the problem or limitation you are having in your project

This is a small problem, and not sure how to fix it . . It's a bit weird, that there are Particles and, then CPUParticles . . One THINKS it'd make sense, though it's not ideal, to rename Particles, to GPUParticles, but not sure . .

Well, it's a very small problem, but for new users, it's sort-of confusing, why there are Particles and, also CPUParticles . .

I don't know how, but was wondering if it could be rename, in a nice way, so it's a bit easier, to see which is which . . . Thx . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, I don't know HOW to fix this, just thinking it's been constantly confusing, why there are two particle systems, and well if one is GPUParticles, why does only one have CPUParticles, as a name . . 

Also, one could call it, a CPUParticleEmitter, or a GPUParticleEmitter, to make the name even more clear . . .

I'd just like maybe to consider, if the two nodes could be rename and, if possible, how . . .

Or, CPUParticleSystem or, GPUParticleSystem . .

It'd be a small improvement, but what's the best way, thx . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, maybe rename the two nodes, or so . . So, it's a bit more clear, what's going on, thx . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Sigh, I've got no idea, can't really code, beyond visual script . . . 

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it's just a little worry, not sure if it's important, it's a bit confusing, at least for some time, why there's two particles, and they seem to not be different, name-wise . . As a beginner, I assume all particles are CPU particles, bec. it's sort of math - heavy and, not texture - related or, rendering or, so . . .

**Comment by Calinou** [comment]
This is already done in the `master` branch, but it can't be done in `3.x` to avoid breaking compatibility with existing projects.
