### ISSUE TITLE
Update the Get Index and, Set Index Visual script nodes to have a write number for the Index input port . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3118]
### Describe the project you are working on

A 2.5D game, with barbarians and, guns . . . :OO . . .

### Describe the problem or limitation you are having in your project

Ok, this is perhaps a beginner thing, but one uses Get Index / Set Index to work, with arrays, that are quite useful, for Return functions, and, is really super - awesome . . .

However, one has to make a New Variable, and maybe write, 0, 2, or 4, to pick, the index, in say, an array variable . . Normally, I'm not in favor, of adding stuff, for the sake of adding it, was thinking, in the case of the Index number, since it will ONLY ever be an integer, and prob. in maybe 0 - 10 range, max., unless for a really big array, why not make so, one can just write it, to save some time, see here . . :OO . . . .

<img width="1104" alt="Skærmbillede (29)" src="https://user-images.githubusercontent.com/83387915/128984074-c6371373-bd3d-4e81-b20f-e190f7feaaa2.png">

I was having a thought, why not add, so one can write that number, since it will save time, and it being an integer, it'd also be easy, to write it, not sure . . . Thx . .

So, like these boxes, one could just write it, to save time, also it's only an integer, faster, to well, type it . . .

<img width="864" alt="Skærmbillede (30)" src="https://user-images.githubusercontent.com/83387915/128984564-88ccb8cc-d9e1-4eaa-ab4d-0c3e7686a7e1.png">

It's just a suggestion, that's all . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, like above, add a little field, so one can type it, idea is, work happens faster . . 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like above, I'm not sure about this, just had the idea and, it seemed, at least at first, like faster . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't rewrite the boxes . . 

### Is there a reason why this should be core and not an add-on in the asset library?

Well, tbh I've been looking at Visual script, and atm it's a 11 / 10 feature, all updates in Godot 4, it's getting to be near rock - solid . . .

![Skærmbillede (31)](https://user-images.githubusercontent.com/83387915/128985001-4766a0e4-b2fa-4b5e-8caf-e6d4d4c41c6c.png)

So, it's down to these last details, again not sure it's a good idea, wanted to suggest it, idea is, save time . . .

It's difficult to not be like, Godot 4 will be 12 / 10 version, dang, it's just getting so much stuff, wow . . . :OO . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
