### ISSUE TITLE
Rename some of the UI in the input map to be easier to read . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3121]
### Describe the project you are working on

A 2.5D game, with barbarians, to get practice, and not code 3D AI, as a beginner . . :OO . . <3

### Describe the problem or limitation you are having in your project

This is a very small problem, also not sure how to fix it . . In a Visual script, if I want to have some input event, there's a list, with names . . A few of them, aren't quite so obvious, for instance space is called ' select ', I think, and enter is called something else . . I was wondering, could one make the names a bit well more clear, so it's maybe easy, for new users to know, what buttons mean . . I have no idea, for the name changes, but maybe something, a bit more ' clear ', thx . . .

![Skærmbillede (34)](https://user-images.githubusercontent.com/83387915/129161091-20e99422-2cb7-42c9-add2-32b24426d9f4.png)

<img width="711" alt="Skærmbillede (34)" src="https://user-images.githubusercontent.com/83387915/129161195-77479aad-9480-4996-8d4b-613b456aa47f.png">

Last, heard Visual script was getting a little love, wow . . . I thought, maybe we'd get a few bug fixes, but you made everything better, so, it's much easier to use and, well amazing job, 10 / 10 . . :OO . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, for me it's down to these small things, for instance Set Index box now works, and, it's getting to, a joy to work with, so big thanks . . 

Idea is, to rename a few of these, so it's less confusing, what well names, do what, on the list, thanks . . . :OO . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, update the names a bit, so they make more sense or, one doens't have to check the input settings, well, not sure . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Again, sorry . . I can't code the engine . .

On a side note, well, Godot 4 is already a 10 / 10, for me, just, it's a massive, mind - blowing improvement, so thanks . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, not sure, I think it makes sense, not sure . . . :OO

**Comment by Calinou** [comment]
UI action names are intentionally abstracted, which is why `ui_select` is not called "Space". This is because it's mapped to other buttons on controllers, for instance.

I think we should display action names as-is and not capitalize them, as it would be confusing otherwise.

That said, the `.OSX` overrides should definitely *not* appear in the list.

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
