### ISSUE TITLE
Make ' new instances ' and spawned objects distinct boxes in visual script . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3122]
### Describe the project you are working on

A 2.5D game, with barbarians . . .

### Describe the problem or limitation you are having in your project

I have a problem, or it's quite confusing, for me to connect the boxes, after spawning a ' instanced_scene ', bec. one has to connect the node line, in a well complex way . . .

Here's an example, it isn't really clear, one has to connect the instantiated ' obj ' port, in this way, and one if left, to guess - work, or so . . . .

![Skærmbillede (35)](https://user-images.githubusercontent.com/83387915/129166371-c42a485f-a8f0-497e-9105-a2129b3b93db.png)

Here's my sort-of noob idea, for making it better . . . Somehow, make an ' icon ' or, a separate box, where one can SEE, the ' object ', one has not created, NOT in the script, but in the game or, so . . Bec., one is sort-of working, after this, with a ' component ', or a node, sort-of, bit more than logic . . .

<img width="711" alt="Skærmbillede (36)" src="https://user-images.githubusercontent.com/83387915/129167234-94b42bd0-ead3-4320-be75-fa12dbe9833b.png">

I think, having some sort-of clear icon, when one goes from working in logic, it doesn't matter there, to something that is in a way, not in the script, but ' node ' - tree, it would be nice, to have an icon, or some indicator, one was now working on something different, from ' code ', but an actual node, in the node tree . . . Unity, uses sort-of icons, in the boxes, for ' Bolt ', don't think they're necessary, for all nodes, but sometimes when, one makes a leap, from coding logic, to working on an actual object, it might be nice, to have an icon, so one knows the port, the ' new ' object, is well made in . . .

It's just an idea, I can't think of many other places it's needed, maybe signals, bec. one is now working on something outside the script, or sort-of ' meta ', it would be nice to have an indicator or, icon when one is working, in that level of abstraction, or so . . . One doens't have to ' break ' the box, in two, one could just have an icon, so it's a bit more clear, when one is working, beyond the script, or logic, that it ONLY, in the script . . It's an idea, not sure, thanks . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, like above, so it's a bit more clear, with an icon, WHERE the object is, or how to connect it . . . May be a few other places, where it's useful, anyway would make it a bit easier, one could also just use the icon, from the scene, as a ' indicator ' . . .

<img width="785" alt="Skærmbillede (37)" src="https://user-images.githubusercontent.com/83387915/129168030-b55f8ab0-8ed0-44eb-9ea8-fcb4afa22174.png">

So, what I'm asking for, is an indicator, or some preview icon, in front of the port, where the new node, one is spawning, is made . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like above, add a little preview icon, so one knows the port, object is spawned from, and one can visible ' see ' the object, that is spawned, so one knows exactly, where the code, and spawned objects are, looking at the script <3 . . .

So, the port, that spawns the object, has a ' preview ' icon, like for Get Texture, or like here . . :OO . . . 

<img width="1237" alt="Skærmbillede (38)" src="https://user-images.githubusercontent.com/83387915/129168600-45387584-ada7-4435-a536-4aac0e4aed4e.png">

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, I can do this, not sure . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, can't code this, and I'm not sure, it's just something, that'd make it easier for total noobs, to connect the boxes, or so . . .

Ok, that's it . . . Waiting for Godot 4, why is the Godot 4 milestone progress, not moving :(( :(( . . <3 . . .

**Comment by charlesmlamb** [comment]
Uhmm, I guess problem I have is, in ' Instantiate() ' box, the place where the ' spawned ' node is, is called ' return any ', then obj port . .

I gues I wish, maybe it was called ' Instance ' or, there was a preview icon, or so . . :OO . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
