### ISSUE TITLE
Add a property to Container which disables sorting of children

### ISSUE THREAD

**Issue by spectreseven1138** [godotengine/godot-proposals#3123]
### Describe the project you are working on

A 2D platformer with a UI that makes frequent use of Containers

### Describe the problem or limitation you are having in your project

In the project, I often use Containers such as BoxContainers and PanelContainers to help with positioning UI nodes. However, this significantly limits what I can do within scripts and animations when changing the properties of Container children.

For example, I have an interface used for selecting a savegame to load, which is essentially a VBoxContainer filled with PanelContainers (the saves). I indicate which save is selected by offsetting its position to the side slightly which works fine. However, when I change a property of the save (such as the text) that resizes the PanelContainer, it causes the VBoxContainer to resort its children, causing the side offset I mentioned to be reset undesirably.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By adding a property to the Container class (such as `sort_disabled` or `disable_child_manipulation`) which disabled resorting of the Container's children, users can use Containers to place nodes on initialisation or at specific points, and then disable resorting to that they can manipulate the size or scale of the child without them being overridden.

In the example I gave, disabling resort would allow me to change the text of a savegame without its position offset being reset automatically by the parent Container.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I've implemented this on the 3.x branch ([PR](https://github.com/godotengine/godot/pull/51547)). It adds the property `sort_disabled` which stops the NOTIFICATION_SORT_CHILDREN notification from being triggered when `queue_sort()` is called. I also added an argument to `queue_sort()` (`ignore_sort_disabled`) which forces the notification to be sent regardless of the value of `sort_disabled`.

Recordings of usage of the feature in the savegame example I talked about:

Without `sort_disabled`:

https://user-images.githubusercontent.com/44363049/129169692-1cf4eeca-d142-4e83-b574-a9289f1e8a4b.mp4

With `sort_disabled`:

https://user-images.githubusercontent.com/44363049/129169691-dad05b43-55af-41c7-8729-ee6f12edfb7a.mp4

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is a way to partially work around this by manually assigning the position or other properties of Container children after the resort occurs, but this causes a very noticeable visual flicker, so no.

### Is there a reason why this should be core and not an add-on in the asset library?

This feature allows disabling built-in features rather than adding new ones

**Comment by spectreseven1138** [comment]
I've been told that the name `sort_disabled` would likely be confusing for a lot of people because "sort" is mostly an internal engine term, which I definitely agree with. Suggestions for better naming (such as `control_mode` or `disable_child_manipulation`) would be appreciated.

**Comment by groud** [comment]
I think the idea might be acceptable, as I agree the use case for animating things might be interesting. Though I really don't want this feature to confuse users about how Containers vs Control node positioning works. As I said in the PR, it is already difficult to explain how both system work, so it might not be the best to add a way to make a Container "transform" into a normal Control node.

And also, in your example, I think thing will likely look broken as soon as you resize the window. As soon as the Container's positioning is disabled, it can create weird things which would need to be handled using a deeper hierachy instead (the children in the container would each have one children that could move around as you wish, relatively to its parent). This might be a cleaner solution to the animation problem.

Indeed the naming here is important, maybe we could go for an explicit `enable_children_positioning` that would be enabled by default ?

Also, I worry about all implications such toggle has. It is possible that some containers consider they always have hand on their children positioning. So I hope no container caches problematic things between two sort children notifications. We might easily end up with undesired behavior I believe.

**Comment by spectreseven1138** [comment]
> And also, in your example, I think thing will likely look broken as soon as you resize the window.

At least with my implementation, the everything looks fine when resizing the window (see video below).

https://user-images.githubusercontent.com/44363049/129184379-b688cd09-7848-4d2d-acc8-da0e732b7d10.mp4

> The children in the container would each have one children that could move around as you wish, relatively to its parent. This might be a cleaner solution to the animation problem.

That's actually what I'm already doing. The VBoxContainer contains PanelContainers which contain an HBoxContainer, and the buttons are moved by moving the HBoxContainer. The nodes I'm setting the `sort_disabled` property on are the PanelContainers.

**Comment by me2beats** [comment]
I agree something like this would be really helpful for creating UIs with UX friendly or just beautiful animations. I did some ugly work-rounds when trying to implement custom drag-drop behavior for  BoxContainer children (the default drag-drop approach was limited in that case).

**Comment by spectreseven1138** [comment]
I've changed the property name from `sort_disabled` to `child_manipulation_disabled` in the PR for now.

**Comment by timothyqiu** [comment]
I don't think this is a good idea.

The purpose of this feature is to disable child manipulation temporarily in order to animate the child nodes' positions. This is a straight forward solution to the problem, but it complicates the system and can be easily walked around by:

* ... replacing the container node with `Container` with `Node.replace_by()`, or
    * https://github.com/godotengine/godot/pull/51547#issuecomment-897521642
* ... adjusting the layout and animate the leading empty space instead of the X position of the button.
    * https://github.com/godotengine/godot/pull/51547#issuecomment-897514760

**Comment by akien-mga** [comment]
Closing as per above discussion and https://github.com/godotengine/godot/pull/51547.
