### ISSUE TITLE
Rename Control's Rect properties to exclude "rect_" part

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-proposals#3125]
### Describe the project you are working on

A game using Control node

### Describe the problem or limitation you are having in your project

Everytime I try to modify the control node with code, i end up forgetting the "rect_" part, it's extremely annoying.
It is weirdly inconsistent with other 2D nodes and makes me question why viewport node and the shape inside CollisionShape2D don't have the same treatment.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Just remove the "rect_" part, it's redundant.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/82024211/129210548-96b18301-8e37-4b0f-b075-7ba7cd211f48.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it cannot be done with a plugin.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about unifying the property naming convention with the rest of the engine.

**Comment by SilencedPerson** [comment]
It was also discussed if the Node3D's translation should be changed to position with an intent to mimic Node2D on which the users agreed that it should, I don't know if that change was greenlit by the devs of the engine, but if it was, then this one should be too, since it's basically same thing.

**Comment by Calinou** [comment]
> It was also discussed if the Node3D's translation should be changed to position with an intent to mimic Node2D on which the users agreed that it should, I don't know if that change was greenlit by the devs of the engine, but if it was, then this one should be too, since it's basically same thing.

Node3D's `translation` was renamed to `position` in https://github.com/godotengine/godot/pull/44198.

**Comment by Xrayez** [comment]
I think one of the reasons why those properties are prefixed with `rect_` is because they could be automagically grouped in the editor inspector. But as far as I know, it's not a requirement, and properties can be grouped together regardless of a prefix with `ADD_GROUP()` in the engine code.

**Comment by mrtripie** [comment]
I'd like this change too. I've been doing a lot UI of lately and I forget the rect part every time.

**Comment by SilencedPerson** [comment]
did anyone attempt to do something with this? i currently figuring out how to go about implementing it.

**Comment by Calinou** [comment]
> did anyone attempt to do something with this?

Not that I know of. Feel free to open a pull request against the `master` branch :slightly_smiling_face:
