### ISSUE TITLE
Make the arrows that connect node boxes, in Visual script more visually appealing . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3129]
### Describe the project you are working on

A 2.5D game, with barbarians . . .

### Describe the problem or limitation you are having in your project

Now, Godot 4 is getting some AMAZING updates, to Visual script, bugs fixed, UX, just 10 / 10 . . .

But, I have a small thing, again this is not important, something to consider . . . Right now, the lines, on the canvas, between nodes are sort-of bendy . .

![Skærmbillede (46)](https://user-images.githubusercontent.com/83387915/129286844-d56c23be-d312-4978-b356-771e65a2fb31.png)

And, it makes scripts bit unreadable, bec. it's sort-of chaotic . . Atm, the lines are 'bendy', not straight lines, I was thinking if one could update it a, so it looked like this, or perhaps better, there was a setting, to define how bendy they are . . Here's what I think, is better . . .

<img width="1920" alt="Skærmbillede (47)" src="https://user-images.githubusercontent.com/83387915/129287053-d06a8f3f-8b1a-4953-8641-6a68b9cfce8e.png">

Idea is, to make it look a bit more, well like a switch-board . . :OO This might not be for everyone, was thinking it might be a setting, so one could set, how the ' curve ' was made, not sure . . . 

![Switch001](https://user-images.githubusercontent.com/83387915/129287341-1194e38b-e76f-4299-956d-0e8731959385.jpg)

Or . . .

![Switch002](https://user-images.githubusercontent.com/83387915/129287350-4e881c58-e04c-4af7-89fe-0ffb1779ba06.jpg)

I realize this may not be for everybody, was hoping maybe it could be a setting, so the scripts well, looked bit more ' logical ', or so . . :OO Thx . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, atm. the program makes 'bendy' lines, that can look a bit like spaghetti, and aren't optimal, for readability . . .

Having lines, perhaps like in image - suggestion, could make it more easy, to read the scripts . . . And, having a setting to define, how bendy or, ' linear ' they are, could help, make scripts more readable while, allowing users, to well select their favorite ' look ', for the lines . . :OO . . .

![Switch03](https://user-images.githubusercontent.com/83387915/129287626-88ed5dd8-9039-44a6-a860-34289ca1da92.png)

![Switch004](https://user-images.githubusercontent.com/83387915/129287635-ba3154e1-80b6-494f-bb21-09646b4b246a.jpg)

So, idea is, make a setting, so one can set the ' bendy ' level, of the lines, so one can avoid spaghetti . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like above, not sure everybody will like it, maybe make it a customization setting, so one can customize how ' logical ', the scripts look, sort-of, for each user . . And, maybe with such a setting, make a new default Godot ' line ' look, that well, fits the engine or, so . . :OO <3 . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't do this, atm . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it'd make scripts, also visual shaders, more readable while, visually appealing . . <3 . . .

**Comment by charlesmlamb** [comment]
I'm sort-of asking, to be able to customize the 'experience', a slight bit more . . Ideally, maybe two settings, how many pixels the line goes to, before bending, and how ' sharp ' the bend is . . Then, let users pick their favorite . . It'd also be a nice difference, to have that ' extra ' coolness, for Godot 4, and give users a few more options, to make their own favorite Visual script well, experience, thx . . . .

**Comment by charlesmlamb** [comment]
This, might be ' ideal ', or so . . .

<img width="644" alt="Bendy 05" src="https://user-images.githubusercontent.com/83387915/129291559-44e48d13-0504-4268-8912-3869f03c1e28.png">

Anyway, just asking for some customization options, so I can make this . . .

**Comment by charlesmlamb** [comment]
Well, I'd like this, to make snake_case, in Visual script or, so . .

<img width="644" alt="Bendy 12" src="https://user-images.githubusercontent.com/83387915/129294209-d64dc226-fdac-441f-a92a-419f7bc0109c.png">

That might, be the ' definitive ' visual script look, at least in Godot . . :OO . . 

one could make a few others, with these customization options, might find them, after a week, or so . . . .

**Comment by boukew99** [comment]
Having it less curved and more straight means it is easier to see where the line is going and thus faster to read the connection, so that may be nice. 
If that is what your proposing. I recommend to keep the proposals shorter and to the point, because aint-nobody got time to read it all :).

**Comment by charlesmlamb** [comment]
Yes, I'm sorry, I get a bit weird, I have OCD . . Sometimes, when I think I figure something out, I get too excited . .

Yes, idea is to make it faster to read, also . . It should lead to less spaghetti, bec. I think the math, should lines will cross less or, when they do, it's easier to read, bec. lines are well more straight . . .

Any-way, hoping it might be customization, could look nice, for Visual shaders and, 'Particle graph' . . I think it's close to, ideal point between bendy and, spaghetty, and so linear, it bec. sort-of painful . . If one could set these things, and customize it, it'd be amazing and, perhaps be one more step, to making Visual script rock - solid and, 'efficient' . . :OO . .

**Comment by charlesmlamb** [comment]
So, you can easily see what line, from a port with several lines, going from same port, that is precisely what, ie. spaghetti goes away . . . <3

**Comment by charlesmlamb** [comment]
Sort of, if ONE node has several lines, from one node port, with this system, it'll be easier to see each line, so it removes spaghetti 100 %, I think . . .

<img width="644" alt="Bendy 19" src="https://user-images.githubusercontent.com/83387915/129413413-bc25fded-81fb-449f-ba3c-801fdd18de06.png">

And, if several lines cross, with the current lines, it can almost bec. impossible, bec. the lines are bending, but since each lines is a ' straight ' line, one can better read through, those places . . .

It also finds the ideal point, between ' straight ' lines and, ' bendy ', giving Godot a sort-of neutral experience, or as you want, imo. it could be little, to logic side, so it's like ' Godot ' X and, with option to customize it, with some default settings, ' default ', ' bendy ', ' narrow ' or, so . . Not sure, it's sort-of an idea, not sure how to implement it, maybe just make a new look, or allow customization, so one can make this <3 . . . Thx . . .

**Comment by charlesmlamb** [comment]
Last, if one wanted to make an ' X ' version, of it, it'd be a bit on logic side, from ' neutral ' and, the ' bends ' should not be circles, but sort-of curves or, so . . .

<img width="657" alt="Bendy 32" src="https://user-images.githubusercontent.com/83387915/129415501-67ee2c21-162c-42b3-95d8-83ca5426c6bb.png">

Then, one could maybe make the current one the default, make one called balanced ( X ) and, one even more narrow, called ( super - X ) and, even one with NO bends, ie. just straight lines, no curve at the bends, for logic - pain lovers <3 So, everyone has something, they like, <3 . . .

**Comment by charlesmlamb** [comment]
Here's another example, for ultra-logical thinkers . . .

<img width="694" alt="test 00777" src="https://user-images.githubusercontent.com/83387915/130205594-2bc3db43-c014-4444-9b18-e522853b97db.png">

It's different, from 'snake_case', maybe Simple-direct-code-system__

I think, with these options to customize visual script, I can make a ' neutral ' or, very close Visual script experience, it might seem weird, but these things ' add ' up and, we could slowly find some at least 'nicer' themes, that'd allow more people to use Visual script, graph edits . .

Having the ability to set these things, might be a step forward, and if there are other improvements, evt. make something, that's ' rock - solid ', or like engineering software . . .

![Skærmbillede (1979)](https://user-images.githubusercontent.com/83387915/130206081-503695d0-b24a-4975-904a-fdffcc3e108e.png)

I think, I can make a 'rock-solid' Visual script theme, and it might be possible, to add an official or, two themes, that just work, with Visual script . . . :OO . . .

**Comment by charlesmlamb** [comment]
I think, this is the settings . . One can make something super - logical, that way . . . .

<img width="719" alt="test 0005" src="https://user-images.githubusercontent.com/83387915/130208880-8fcd0d39-b714-4970-9a6c-6c407859c7e7.png">

One could make anything from 100 % bendy or, 'bezier' or, super - logical and, 'up-right' . . With these settings, one could make the ' best ' UX or, so . . .

And, one of examples above, is may-be x_case . . :OO . . . <3

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!

**Comment by afk-mario** [comment]
Wouldn't this apply to the Visual Shader editor ?

**Comment by YuriSizov** [comment]
@afk-mario Please open a new proposal if you think there are ideas here to be salvaged for visual shaders.
