### ISSUE TITLE
Add a Fixed Size property to AnimatedSprite3D and Sprite3D

### ISSUE THREAD

**Issue by colinmbo** [godotengine/godot-proposals#3130]
### Describe the project you are working on

I am building a 3D game that uses billboarded pixel-art sprites as characters. The entire game is low resolution / 3D pixel art, meaning if the players are not fixed size, there will be some pixel distortion as they move further away from the camera.

### Describe the problem or limitation you are having in your project

Currently, in order to have a Sprite3D be a fixed size you have to use a material override and modify a spatial material instead, in which there is a fixed-size option. This method, however, is not applicable to an AnimatedSprite3D, in which case animation won't work in the material override. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would help to add a "Fixed-Size" flag to the AnimatedSprite3D, just like there is with a spatial material. That way your animated pixel art sprites will keep their scale regardless of their distance from the camera.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I am assuming the code for Fixed-Size in the spatial material can be recycled to be used with the AnimatedSprite3D.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

After much research, I have found no way to implement sprite animation into spatial materials (aside from animatedTextures, which doesn't support SpriteFrames and would be extremely inefficient for longer animations.) This means the only way to use the fixed-size feature would be for it to be implemented into the AnimatedSprite3D node itself.

### Is there a reason why this should be core and not an add-on in the asset library?

It should be a relatively simple addition that would be incredibly useful for those making pseudo-3D pixel art games.

**Comment by NitroPlum** [comment]
I am also in need of this exact functionality. It's a hard stop on my current project.

**Comment by KarlTheCool** [comment]
This appears to be fixed now.

https://github.com/godotengine/godot/blob/0810ecaafdbee3ea747219e6ab3a8de5d2216a09/scene/3d/sprite_3d.cpp#L595

![image](https://user-images.githubusercontent.com/10494276/232255892-8921c5e1-fb64-45cc-b895-49d5ccc2f059.png)

**Comment by Calinou** [comment]
Closing, as this is implemented since 4.0 at least per the above comment.
