### ISSUE TITLE
Consider removing / updating CTRL + scroll wheel for vertical jump in Visual script or graph edit . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3132]
### Describe the project you are working on

A barbarian game, 2.5D . . .

### Describe the problem or limitation you are having in your project

Right now, there's been a massive improvement, to Visual script, the UX . . Atm . . . <3

Scroll - wheel => zoom . .

SHIFT + scroll - wheel => nothing . .

CTRL + scroll - wheel => vertical jump . .

Imo, having SHIFT or, CTRL do stuff, is really nice . .

I was thinking, what if SHIFT + left-click select, made a comment, over the selection . . .

![Animation (1)](https://user-images.githubusercontent.com/83387915/129387787-c29e0424-daa8-447b-a2dd-2bda11fc3fe6.gif)

Imo, it was really nice, to have those keys or, inputs . . Was thinking, maybe they could be used for something else, and atm. it doesn't make the CTRL + scroll - wheel is there, for vertical jump, see here . . .

![Animation (2)](https://user-images.githubusercontent.com/83387915/129388006-59d208ec-036d-4230-920a-ede59851f190.gif)

If I had to bring those back, I think I'd make them sort of ' scroll ' or, animate the jump, it could be fast . .

Anyway, maybe there's some amazing use, maybe CTRL + left - click could make a ' new function ' . . Or, not sure, SHIFT + left - click could make a _ready function, CTRL + left - click could make _process and, CTRL + SHIFT + left - click could make _physicsprocess, or maybe CTRL+ SHIFT could, make a print() node . . .

It was really nice, to get a few more features and, I think maybe there are good uses, for these short - cuts . . :OO . . .

Also, right now SHIFT + scroll - wheel does zoom, like the ordinary scroll - wheel . . It feels more stable, less jittery . . . Maybe someone has some ideas, for how one could add some often used features, to the buttons <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, like above . . I think it's really nice, to have those extra keys, not sure what most common stuff, one could use them for . .

Anyway, it's much better already, works really well, thx . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Maybe find some really good uses, for those keys . . . 

It was quite nice, to get some improvements, I think with a bit more thought, it'd be really nice . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not sure, it's not something I can code, sorry . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it was a good idea, why not just 'improve' it and, make it even nicer or, so . . :OO . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
