### ISSUE TITLE
Make a version of Godot Physics that is optimized / written in GD Native . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3138]
### Describe the project you are working on

A barbarian game, 2.5D, with lore . . .

### Describe the problem or limitation you are having in your project

I was thinking, why not have the normal Godot Physics engine, and a version, that's written in GD Native . . It'd be more difficult to maintain, and the normal Godot Physics would get updated faster, or more often . . But, have in physics engine, two options, Godot Physics and, Godot Native Physics . . . It might take much longer to write and, fully optimize, but when it's done, it should be the fastest physics engine, in the world . . .

Idea is, the normal Godot Physics engine is coded first, and implemented, as soon as possible . . . Then, the new features are more slowly added, to the Godot Native Physics engine, so maybe normal engine is 4.1, or so . . . And, the Godot Native Physics is only 4.0 but, still compatible, or works . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, physics are important, and help create amazing games, etc . .

And, normal users can't write a Native version, of the engine but, it might be possible, I think . . For engine pros, to make that . . . Question is, how does one maintain it and, are there anybody who can actually do this . . It might be so difficult but, when it's done, it might be 10 % faster, or 20 % and, sort-of be the fastest possible physics, or so . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, there's rumors there will be support for other physics engines, at some point . . . Why not have some amazing coders, if it's even possible, optimize the Godot Physics engine, so one can click, Godot Physics, Godot Native Physics and, physX, or so . . . It'd prob. be hard - core work, but could it theoretically run faster . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Ok, just an idea, could be really nice performance boost, for the physics engine, not sure . . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it could be a plug-in, one could download . . It's sort of the next step, might take so much time, it's impossible that said, it'd be really cool when it's done and, good question is, how much faster would it be . . And, is a physics engine something, that would run a little faster, or much faster, if made, in Native . . <3

**Comment by pycbouh** [comment]
Godot physics are natively implemented in the engine core. Moving it into a GDNative library would only achieve making is slower and less integrated into the engine.
