### ISSUE TITLE
Easy VisualScript CustomPropertyEditor Plugins (Inspector editor's)

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot-proposals#3139]
### Describe the project you are working on

General Visual Script improvements

### Describe the problem or limitation you are having in your project

Editing data input port's is not flexible 

For example: To edit a NodePath there is one option select the node and the path between Node.vs and Node will be implemented.
What if you do not jet have that path in scene? What if you want to call that path on a instance Node?

I do not think there is a perfect solution to this problem. So I propose to give the user multiple options with are easily modified upgraded and added to.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Redesign the (Custom)PropertyEditor to use vBox or Gridcontainer and provide all possible editors with are able to edit this data (PropertyInfo).
Provide a EditorCustomPropertyEditorPlugin class so more iteration between releases are possible.

This next part might have overlap and or synergy with EditorInspectorPlugin
Provide a EditorVisualScriptDataEditorPlugin class so more iteration between releases are possible.
can_handle(PropertyInfo)
or
int can_handle(type)
int can_handle(type_hint) # not always available
int can_handle(type_hint_string) # not always available
int can_handle(type_value) # not always available

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The new (Custom)PropertyEditor  will check core and plugins if they can_handle(?) and then provide the possible editors.
These may be sorted in different ways so in v1 no real consideration needs to be given.

The new VisualScriptDataEditor wil provide a Control that is able to edit the value in the most appropriate way. emit_changed()

The int returned by all the different can_handle functions needs to be limited. And provides future PropertyEditor a way to sort the editors.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no workaround.

### Is there a reason why this should be core and not an add-on in the asset library?

I think its one of the biggest incompleteness of VisuaScript and will be used often.

The demand that this VisualScriptDataEditor is needed may provide improved DataEditors for Inspector.
when Inspector DataEditor is considered in initial design it might be easily implemented later.

**Comment by pycbouh** [comment]
CustomPropertyEditor is an outdated class that needs to be removed in favor of using Inspector's EditorProperty. And then we could just reuse the inspector plugins for this without any need to introduce more abstractions.

**Comment by Gallilus** [comment]
Now the `EditorInspectorPlugin` decides what `EditorProperty` is used in the inspector. (if not default)
So is there a plan to allow multiple `EditorProperty`'s for one property?

For example: String FilePath needs at least 2 options LineEdit and FileSelector

**Comment by pycbouh** [comment]
EditorProperty is not bound to be a single control. It can be any number of controls put together. You can make it an hbox with a line edit and a button that brings a file dialog. In fact, we already have a property editor for files.

**Comment by Gallilus** [comment]
Let me try to rephrase the intent.
Now: There is a property witch needs to be edited and some part in the editor decides what EditorProperty is used to edit that property.
Proposal: There is a property witch needs to be edited and we ask the available EditorProperty if they can handle that. And use a list of EditorProperty to edit the property.

I think the current EditorPropertys are good. We may need to ad a few. 
Its the in between part the `EditorInspector` and `CustomPropertyEditor` that need more flexibility. And I think changing the direction of the question will help. 

And as the `CustomPropertyEditor` needs to find a alternative this is the right time and place to ask.

**Comment by pycbouh** [comment]
EditorProperty is just the control that edits a property that is given to it. It's the inspector plugin's job to answer if it can handle it or not. Basic EditorProperty classes are applied based on the type of data and some additional property info. For custom editors you add with an inspector plugin you can also use some other information, including the name of the property or what object it is in.

**Comment by Gallilus** [comment]
Then it might be intresting to make a change so it is easy to create a plugin that overwrite `CustomProperty Editor`?
It will leave room for experimetation and itteration.

**Comment by pycbouh** [comment]
Like I've already said, CustomPropertyEditor is an outdated class and must be replaced by EditorProperty classes. There is no point supporting to different versions that do the same. Visual editors are simply lagging behind and weren't updated when EditorProperty was introduced to replace CustomPropertyEditor in the Inspector some years ago.

**Comment by YuriSizov** [comment]
This can actually be closed now. I've removed `CustomPropertyEditor` from the engine recently and made visual editors use the new inspector widgets. So they technically should support plugins, but to make the most use of it the nodes need to be reworked. At least in the shaders half the fields are not defined as any sort of property and don't have a corresponding object, so defining plugins is harder.
