### ISSUE TITLE
Add supports to build Godot with google angle on Android and iOS platform for gles 2 renderer

### ISSUE THREAD

**Issue by kruglinski** [godotengine/godot-proposals#314]
**Describe the project you are working on:**
Just an idea

**Describe the problem or limitation you are having in your project:**
No problem, No limitation

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Maybe improve GLES 2 rendering performance in modern mobile hardware

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
No screenshots

**Describe implementation detail for your proposal (in code), if possible:**
No code

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because this is a core layer problem

**This is what I want to say:**
Google [Angle](https://github.com/google/angle) seems implemented gles 2 over vulkan on Android, and work in progress to implement gles over metal on iOS

if this is not too much cost work to have this support, the legacy gles 2 renderer will work on modern mobile hardware for many years in the future. it is good for the dedications for the stable gles 2 renderer and for all games that willing to use gles 2 for many years in the future.

so please think about it, many thanks!

![index](https://user-images.githubusercontent.com/2869425/71008570-c9b6e500-2123-11ea-9be6-5c091ef1fa4c.png)

**Comment by kruglinski** [comment]
It seems more relevant to have this support in Godot 3.2, to make 3.2 transparently have vulkan and metal rendering performance(and maybe some core options to adjust renderer performance)

but not so much relevant to have this in Godot 4.0, IMO all game made with 4.0 will adopt 4.0 engine features from the beginning

**Comment by clayjohn** [comment]
Angle exists as a layer over the GL drivers. We have no interaction or control over it on an application level.

**Comment by groud** [comment]
I am going to close this issue, partly per the comment above, but also because we want to keep the quality of the proposal here. Dropping any random technology, even if it sounds cool, wont be accepted without a real need.

**Comment by kruglinski** [comment]
> 
> 
> I am going to close this issue, partly per the comment above, but also because we want to keep the quality of the proposal high here. Dropping any random technology, even if it sounds cool, wont be accepted without a real need.

That's fine, as a experienced developer I can do it with or without help, just want to save some of my time.

I will do it myself when 3.2 stable released, thank you all
