### ISSUE TITLE
Switch to the new csproj system

### ISSUE THREAD

**Issue by SeleDreams** [godotengine/godot-proposals#315]
**Describe the project you are working on:**
I am working on an RPG in C# using Godot Mono 3.1.2.

**Describe the problem or limitation you are having in your project:**
I don't have a limitation in particular, however, this suggestion should make it easier to work with vs code etc to work on C# projects by making the syntax of the csproj more human-like.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
By switching to the new csproj syntax used by net standard and net core projects, it should be easier to edit information from the solution without being lost with the amount of useless details contained in the old autogenerated csproj files

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
instead of using this clunky kind of csproj
![image](https://user-images.githubusercontent.com/16335601/71049888-13172c80-2144-11ea-9978-a4d0d8c68023.png)

godot could generate csproj files like this
![image](https://user-images.githubusercontent.com/16335601/71049928-288c5680-2144-11ea-86ec-868cd47e2d40.png)

it would only require to use net45 in TargetFramework without the netstandard2.1. This format is compatible with mono and visual studio post 2017, so it should work without issues.

**Comment by neikeq** [comment]
I plan to switch both to project SDKs and to .NET Standard 2.1 sometime Q1 2020.
We will use our on SDK on top of `Microsoft.NET.Sdk`.
