### ISSUE TITLE
Unlink the options "snap grid" and "make grid visible"

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#3156]
### Describe the project you are working on

not important here

### Describe the problem or limitation you are having in your project

One thing is the option "Adjust Grid" and another thing is "make the grid visible".

Grid snap: allows user to move nodes by positions set by the grid

Make grid visible: makes the grid visible or invisible.

The problem: if you activate "Grid snap" the grid will be visible even if you don't want it visible and just want to snap its nodes to grid positions.

That would have to be corrected.
The "Grid Adjustment" must be unlinked from "Make Grid Visible".
I may want to adjust my nodes to the grid positions but I don't want the grid visible, that is not possible right now because the two things are linked.

Currently you cannot turn on the grid snap and turn off the grid display.
If you use the grid snap, you will necessarily see the grid.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Modifying this will allow the user to activate grid movement without the grid necessarily being visible.
The "grid snap" and "make grid visible" options will be independent.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

...

### If this enhancement will not be used often, can it be worked around with a few lines of script?

...

### Is there a reason why this should be core and not an add-on in the asset library?

...

**Comment by Calinou** [comment]
I think this was changed by @groud a while ago (maybe for 3.1). IIRC, it used to be possible to snap to the grid without the grid being visible in Godot 2.x. I preferred this behavior too, so I'd like to see it back ideally.

**Comment by groud** [comment]
My rationale to change that behavior was that toggling the grid with two separate buttons (especially when you use keyboard shortcuts) is a lot more annoying than a single one. There are usually two situations in a common workflow, either you want the grid (only snapping, only visible or both) or not. You don't want to bother with two settings to switch from one mode to the other. Thus this must be a single button, not two. 

I don't mind adding a way to choose your "grid's configuration", but I wont be in favor of getting back to two buttons, as I think it would worsen the UX.

**Comment by Torguen** [comment]
Can't add 3 functions in one button?
Perhaps the button could adopt 3 different colors or icons depending on the option selected.

1 - Visible grid with adjustment
2 - Visible grid without adjustment
3 - Invisible grid with adjustment

**Comment by timothyqiu** [comment]
Maybe we can think this another way: it's reasonable that we don't need to show a pixel grid when pixel snap is on. Then what about a 2 pixel snap, 3 pixel snap, etc... I think the same reason goes for grid snap.

Editors like GIMP, Krita, Photoshop, and even Blender separates grid snap from show grid.

**Comment by groud** [comment]
> Can't add 3 functions in one button?
Perhaps the button could adopt 3 different colors or icons depending on the option selected.
1 - Visible grid with adjustment
2 - Visible grid without adjustment
3 - Invisible grid with adjustment

Problem is that it also needs a disabled state, so that's 4 states for a single button, which makes things quite complex. We could go for a configuration menu, but that's kind of annoying.

Maybe another solution might be to have the two button separated, but make a shortcut that would switch both button off if the shorctu is pressed once, and then back to their previous state when the shortcut is pressed again. Not sure if we would keep shortcuts on the individual buttons then. That could be an acceptable compromise IMO.

**Comment by RedMser** [comment]
Is this fixed by https://github.com/godotengine/godot/pull/57848 ?

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/57848, closing.
