### ISSUE TITLE
Make the color of graph edit nodes customizable in Theme editor . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3160]
### Describe the project you are working on

A barbarian game, 2.5D . .

### Describe the problem or limitation you are having in your project

I'm sort-of trying to make Visual script a ' neutral ' experience, neither artistic or, too logical, the ' middle ' - point . . . <3 . .

To do that, I need to be able to customize the colors, of the node boxes, for instance, to make the logic boxes have a black header, with white text, and then the center be white, with black text . . Some things, are black-and-white, aka logic, etc . . .

However, I'm also thinking one could make graph edits more ' neutral ', by making them more boring, drab or, bland, in colors, more ' faded ' or, so on . . . Can't currently set the colors, for the types of graph nodes, I'm hoping they could maybe be made customizable, in the theme editor, that works actually really well, right now . . <3 . . .

Right now . . .

<img width="721" alt="Skærmbillede (2035)" src="https://user-images.githubusercontent.com/83387915/130062989-4aec21af-158c-48a9-b6a4-378278fbc16b.png">

I'd simply like to be able to set the colors of the node headers, for math type, logic type, and also color, of the center, and possibly if it uses light-font or, dark-font, bec. that could become a problem, so if center of a box is white ( logic ) and, text was white, it'd be unreadable . . .

I don't think this would make graph edit 100 % neutral but, might be a step, towards that . . . I'm hoping we can make Visual script amazing, and have the best ever version, also because I use it, and I simply want a stable, 'rock-solid' experience or, UX . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, sort-of make it more customizable, in the theme editor settings . . Right now, there are only a few settings, for comment boxes, my goal is to make it so, if one wants, one can make a rock-solid, easy version, quite drab, and boring, yet, more neutral, bec. it takes away the 'eye - candy ' and, so on . . .

Just trying to make a really nice experience, so any one can pick it up . . . If it looked more well boring, or ' sad ', or so . . . It'd still be an amazing coding - system, in that one has a full coding - system, and the power would not be altered . .

Really hope you'll make graph edits more customizable, at least in theme editor, so individual users can make what they're looking for, in my case, a ' neutral ' UX, also for sake of making tutorials and, content, etc . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, make it more customizable, so one can code confidently and, well more easily, ' happy ' . . 

Also, it'd help me make tutorials, and that could maybe get more people interested in Godot, in a nice, simple way . . :OO . . Thx . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, it's not something I can do, it'd just help, make the UX better and, more reliable . . :OO :OO <3 . .

And, each user could make their own version, in terms of UX, and ' feel ' or, so . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, I'd like to give this a serious attempt, at making something amazing, or plain ' neutral ', works for everybody, that simple . . .

And, if I could teach more, in a relaxed way, it might help the engine, or the other amazing Visual script contributors, sort-of make it rock-solid or, cool . . And, work in their favorite way, or so . . . <3

Thx, that's it . . . .

**Comment by charlesmlamb** [comment]
If this was possible, I'd spend some months, trying to figure the way, to make a ' neutral ', simplistic, competent version, that appeals to everyone, functional and, using ' visual ' coding or, logic . . :OO <3 <3 . . .

**Comment by fire** [comment]
Similar to https://github.com/godotengine/godot-proposals/issues/2364?

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
