### ISSUE TITLE
4.0 Generics should use <> instead of [] for better readability

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#3166]
### Describe the project you are working on

Non just messing with a build of godot 4.0 because its cool

### Describe the problem or limitation you are having in your project

static typing with generics is confusing right now because it uses array indexing and array declaration operators `[` and `]`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose '<' and '>' be used for generics to make code more readable
for example..
```
@export var list : Array[int]
@export var dict : Dictionary[int,int]
```
becomes...
```
@export var list : Array<int>
@export var dict : Dictionary<int,int>
```
This not only is more readable but also scales better.

Note I know dictionaries don't support static typing yet in 4.0.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

this is a core gd script 2.0 syntax feature so its important this issue is covered before 4.0 is released to keep future compatibility.

### Is there a reason why this should be core and not an add-on in the asset library?

its already part of the core.

**Comment by timothyqiu** [comment]
FYI: Python also uses square brackets for generic type hints: [PEP 484](https://www.python.org/dev/peps/pep-0484/#which-brackets-for-generic-type-parameters)

```python
x: List[int]
y: Dict[int, int]
```

**Comment by Shadowblitz16** [comment]
awful. 
ok closing then

**Comment by Joakker** [comment]
I feel like square brackets are easier to lex because
```gdscript
var l : List<List<String>>
#                       ^ Is this a bit-shift or two closing brackets? Who knows!
```

**Comment by KoBeWi** [comment]
You don't need to close proposal just because it doesn't match Python syntax.
That said, `<>` have this problem that they are ambiguous with `<` `>` `<<` `>>` operators.

**Comment by Shadowblitz16** [comment]
It is true that its also a bit shift operator if you have nested generics, but in the case of array indexers and decelerators you don't need to have them nested for it to be ambiguous.

I guess it was a matter of personal taste that's why I closed it.
At least its not D langs generics `!(T)`
