### ISSUE TITLE
Improve display of Arrays in the inspector

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#3167]
### Describe the project you are working on

non just looking at a 4.0 build

### Describe the problem or limitation you are having in your project

I just thought the inspector always looked kinda ugly this is not just a 4.0 issue.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

maybe something like this...
![image](https://user-images.githubusercontent.com/2453707/130179838-e593f6fc-5dce-4c96-b826-0e213b7146d6.png)
instead of this?
![image](https://user-images.githubusercontent.com/2453707/130179393-3529f7eb-231d-4be8-a7c4-c95b74d7dd0b.png)

dictionaries and collision masks/layers would use something similar, and the size field and plus button would collapse into the header.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

this can be worked around with a inspector plugin I guess but it would be nice to have it there by default

### Is there a reason why this should be core and not an add-on in the asset library?

It looks cleaner

**Comment by Calinou** [comment]
I think not displaying the array size in the preview harms usability overall. Moreover, moving the Size property at the bottom makes it hard to click it multiple times to adjust the number elements as the Size property will jump up and down every time if you do so.

**Comment by Shadowblitz16** [comment]
but usually when adding elements your working from the bottom of the collection.
if you want to modify it at the top you can just collapse the header.

**Comment by Shadowblitz16** [comment]
@Calinou what do you think of my previous images?

**Comment by Shadowblitz16** [comment]
I'm closing my bad proposals
