### ISSUE TITLE
Improve the VisualScriptCustom node, make it more user - friendly . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3169]
### Describe the project you are working on

A barbarian game, 2.5D . . . .

### Describe the problem or limitation you are having in your project

I met a beginner, who had problems understanding, he had to make a 'Singleton' node, set it to input, and move port out, to get some mouse controls . .

I was thinking, the current VisualScriptCustom node requires one, to be able to write code, and code well the ports, in and, out . . . Had same problem, when tried to make VR head-set work or, so . .

So, I was thinking maybe make a node, that makes it easier to type in short lines, of code, like this . . .

<img width="694" alt="Test 0044" src="https://user-images.githubusercontent.com/83387915/130201101-d49a1671-6668-455d-808a-1473ac7b5f3f.png">

One writes input, first line, there's a '.', at end . . . So, first ' box ' line, one writes Input, add news line, with + . . .

Then, one types next line, below that . . It's bit more visual and, might work well, not sure . . . So, next line might be, is_action_pressed . . Last box, ends with a ( ), not '.' <3 It's just an early idea, btw . . . <3

So, if I don't know how to make boxes, for say Input.is_action_pressed() - very simple example but, many beginners get stuck, if they have a written code example, or so . . The box is intentionally made a bit visual, one clicks the +, to add an extra line . .

Also, some functions have, methods or, properties, was thinking in inspector, one could click update, and one sees all methods, and properties, maybe with some default values and, the node could be updated, with the ports . . . This would make a step, many find difficult a bit easier, and help coders work more fast, with visual artists, sort-of if they have problem,  just send a line of code . .

However, was just wondering, if this could be a better way of making a user - friendly custom visual script node, well it's not custom, it's just something many new users ask about . . Don't know if there's maybe better way to make such a node box . . Also, it'd be a simple teaching tool, that might slowly help visual artist learn, basics of written code . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, it's a simple idea, also quite noob idea, for the how . . .

Anyway, it happens all time, someone gets stuck on making simple things working, and spend 1 - 2 days, or several weeks, trying to make stuff work . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, add a new node box, that helps one do advanced stuff, more easily and, in a way, that is more visual, ie. it's simple and, intuitive box, with good functionality, etc . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, can't code the engine . . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it'd help ' fill ' a small problem, where many users get stuck and, end up wasting days, weeks, trying to make simple stuff work, most coders can just make work, in 5 - 10 minutes . . . But, how could such a box look and, what should be in box, or in inspector ( methods, properties ) + how, to update it . . . I'm thinking, an ' update ' button in the box, or sort-of in inspector it auto-updates, so one can see everything there and, the default values, for each property, etc . . :O . . .

Thinking, an 'emergency' box, in one is stuck and, has seen the written code, or so . . . . Thx <3 . .

**Comment by charlesmlamb** [comment]
Sigh, the problem is if you want to add written code, one needs the VisualScriptCustom box, and it's quite complex . . .

I was thinking, making it bit easier to write code, from code 'snippets' and, sort-of fill a gap, between simple nodes and, custom node . . Thx . . . An idea, not sure how it'd be done, maybe like above . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
