### ISSUE TITLE
Check if its exporting for release or debug by the code on Android/iOS Plugin

### ISSUE THREAD

**Issue by gumaciel** [godotengine/godot-proposals#3174]
### Describe the project you are working on

Plugin for AdMob Android (and iOS as well):

 https://github.com/Poing-Studios/godot-admob-android
  https://github.com/Poing-Studios/godot-admob-ios

### Describe the problem or limitation you are having in your project

When exporting the Project the Programmer needs to remember to unmark a property that should only be activated when it is testing (debug) and deactivated when production (release) and this can cause some kind of bug

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In the Plugin development have some annotation or something like this.

Like this on C++:

https://docs.microsoft.com/en-us/cpp/preprocessor/hash-if-hash-elif-hash-else-and-hash-endif-directives-c-cpp?view=msvc-160#preprocessor-operators

will be like:

```
#if DEBUG
#if RELEASE
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
#if DEBUG
//do things for debug only
#if RELEASE
//do things for release only
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know for sure

### Is there a reason why this should be core and not an add-on in the asset library?

Theres no way to do that with asset lib (as i know)

**Comment by Calinou** [comment]
Have you looked at [Feature tags](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html)?

**Comment by gumaciel** [comment]
@Calinou thank you, I will test here and tell to you if works

**Comment by gumaciel** [comment]
It worked, thank you!
