### ISSUE TITLE
Autoload Project Page: Make node name and node path order consistent between adding a node and the node list

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot-proposals#3175]
### Describe the project you are working on

Just starting out with the engine, am working through a 2d tutorial.  Got to autoload and was tripped up by the fact that the order isn't consistent on this page.

### Describe the problem or limitation you are having in your project

The node name and path should be consistent here, but aren't.
[Example](https://i.imgur.com/Bpwp5Wr.jpg)
At the top, it's 
Path: __________________________ Name: _______
At the bottom, it's
Name: _________________________ Path:________

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest switching the locations in the new node entry, so you put in the name first, then the path.  That would make it consistent.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would look [like this](https://i.imgur.com/Qpp5J6n.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I know of.

### Is there a reason why this should be core and not an add-on in the asset library?

This enhances the core UI.

**Comment by pycbouh** [comment]
I don’t think this enhances the UI. When you add an autoload, you first need to select the file, then (re)name the autoload. The UI is laid out in the natural order of operations. But in the table, the name is more important than path, as name is what the autoloads are referred by.
