### ISSUE TITLE
Native support for DragonBones.

### ISSUE THREAD

**Issue by 111ukasz111** [godotengine/godot-proposals#318]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by groud** [comment]
Closing as the issue template was not filled in.
Also, this is unlikely to happen anyway, DragonBone is not a FOSS project and we don't want to support proprietary software as builtin (No problem as a plugin thouhg)
