### ISSUE TITLE
Native support for DragonBones.

### ISSUE THREAD

**Issue by 111ukasz111** [godotengine/godot-proposals#319]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**
Godot 2d bone animator is very limited.
**Describe how this feature / enhancement will help you overcome this problem or limitation:**
DragonBones have more features 
**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**
https://github.com/DragonBones/ 
gddragonbones plugin is not work.
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by groud** [comment]
Let's make things clear, we try to have here proposal that match a standard of quality, and need a real use case to be applied. If you are not working on a real project, facing real difficulties, your proposal will not be considered, sorry.

Also, as I stated in the previous issue you opened, we are not interested in supporting natively proprietary software, so this is unlikely to happen. 

> https://github.com/DragonBones/ 
gddragonbones plugin is not work.

Please open an issue on their repository then, we don't offer support for thirdparty software.
