### ISSUE TITLE
Capitalize abbreviation letters in signal names

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#3191]
### Describe the project you are working on

2D mobile game using signals

### Describe the problem or limitation you are having in your project

Abbreviations should always be capitalized.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

All abbreviations would be capitalized. The signals I found are `gui_focus_changed` and `gui_input`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`gui_focus_changed` would be `GUI_focus_changed` and `gui_input` `GUI_input`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, it's just a small change.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-proposals/issues/1399.
