### ISSUE TITLE
Make RichTextLabel show hand shaped cursor regardless of Meta Underlined

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-proposals#3193]
### Describe the project you are working on

Puzzle game

### Describe the problem or limitation you are having in your project

In the credits screen, I have a bunch of clickable links inside a RichTextLabel. Hovering the mouse cursor over the links changes the cursor into a hand shape.

I don't want to show underline for the links, so I unchecked the "Meta Underlined" property. But this also disables the hand shape change.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If this is a bug, then show the hand shape regardless of Meta Underlined.

If this is intended behavior, I suggest adding another property to control this behavior.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a "Meta Cursor Shape" property to control the cursor shape used when hovering a meta link.

If you want the old behavior, uncheck "Meta Underlined" and set this to `CURSOR_ARROW`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, the API of RichTextLabel is very limited at this domain.

### Is there a reason why this should be core and not an add-on in the asset library?

The same as above.

**Comment by lpares12** [comment]
I am interested in this feature and can implement it in Godot 4.

**Comment by YuriSizov** [comment]
I think we can just go ahead and decouple the cursor shape from this property. Underline is a stylistic choice. Hand is a usability feature. If you use meta, you want it to be clickable, so you want to telegraph it.

I could come up with a way to use a hidden meta with no indication in a game, but I think it's a bit far-fetched, and can be worked around with some custom tags.

**Comment by lpares12** [comment]
Yes, that's even better.

I have removed the lines:

    if (!underline_meta) {
        return get_default_cursor_shape();
    }

from `RichTextLabel::get_cursor_shape` and it is working as I would expect it to be. Unless there is another caveat that I'm not aware of, I think this should be enough.
