### ISSUE TITLE
Add a Mono Build keyboard shortcut

### ISSUE THREAD

**Issue by MallocStudio** [godotengine/godot-proposals#3197]
### Describe the project you are working on

Working on a 2D Top Down action game using the Mono version of Godot.

### Describe the problem or limitation you are having in your project

Sometimes I make changes to my code (and when I don't use intellisense or when for whatever reason it's not working), I come over to Godot, hit the Build button on top right to see if there are any compilation errors. The problem is that I am used to using my keyboard and want to compile rapidly as I make changes, and don't want to use the mouse to hit the Build button. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would be a minor enhancement but add a keyboard shortcut that Builds (Compiles the code) without running the game.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When I press "Ctrl + B" build the game (the functionality of the Build button on top right corner of Godot Mono) and display the compilation errors.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I compile my code to check for Compilation errors often. So for now I just click the Build button with my mouse.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the Mono Build functionality of Godot.

**Comment by Calinou** [comment]
cc @neikeq

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot-proposals/issues/3197.

**Comment by pycbouh** [comment]
Well, rather by https://github.com/godotengine/godot/pull/52633 and https://github.com/godotengine/godot/pull/52595
