### ISSUE TITLE
Warn if sending an rpc/rset that would be invalid

### ISSUE THREAD

**Issue by winadam** [godotengine/godot-proposals#320]
**Describe the project you are working on:**
I'm working on a project with networking.

**Describe the problem or limitation you are having in your project:**
Following rpc security errors back to the source is difficult because the error just shows up as invalid in the server with no sense of where the property or rpc was invalidly called.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
My ideal implementation would only be enabled in debug builds, and would create a warning when doing rset/rpc that would be invalid. Such as calling/setting a puppet method/property when the node is not the master.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
N/A

**Describe implementation detail for your proposal (in code), if possible:**
Enabled only in debug builds. Not sure, I want to know if my proposal has some critical flaws before I start working on it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
This proposal deals with the networking system and I believe the add-on would be replacing the entire networking system.

**Comment by winadam** [comment]
I'm not sure how others are using networking and if there is a scenario where its not known if the rpc/rset would be invalid to do.

**Comment by Faless** [comment]
Closing as this should be fixed for all cases where we can actually predict the failure. Note that there are some cases where it is not possible to know if the remote peer will accept the RPC.
Feel free to comment if you find a case where and error should be printed and it's not.
