### ISSUE TITLE
Make some static fields in C# constant

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#3202]
### Describe the project you are working on

chaotic 2D game

### Describe the problem or limitation you are having in your project

I want to use Vector2.Zero as a default argument but can't because it is only static and not constant and default arguments always must be compiletime constants.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

All concerned fields would be constant instead of just static.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`public static Vector2 Zero { get; }` should be `public const Vector2 Zero { get; }` in struct `Vector2` (`public static const Vector2 Zero { get; }` does not work, see [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0504)).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, it cannot be changed with an add-on.

**Comment by Calinou** [comment]
cc @aaronfranke

**Comment by raulsntos** [comment]
Structs and classes cannot be constants, a constant in C# is known at compile time and that's not possible here. You can't use `Vector2.Zero` as a default argument but you can use `default` which is the equivalent to calling `new Vector2()` which is the same as `Vector2.Zero` so:

```csharp
public void MyMethod(int a, int b, Vector2 v = default)
{
	// Do something
}
```

**Comment by MaaaxiKing** [comment]
Cool, thanks
