### ISSUE TITLE
Add server_relay option to WebRTCMultiplayer

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot-proposals#3208]
### Describe the project you are working on

I am working on a general purpose multiplayer workbench for testing and swapping between the different High level Multiplayer protocols (ENet, Websocket, and WebRTC) that can be used for benchmarking experiments.  

Its operation is tightly coupled with a tree of interface nodes for monitoring the many states involved in setting up the WebRTC system (ie signalling servers, for which I use MQTT).

The functionality requirements of the workbench is to handle the needs of a drop-in drop-out multiplayer VR world, rather than the usual process of match-making.

https://github.com/goatchurchprime/godot_multiplayer_networking_workbench/releases/tag/v0.1

As you can see in this diagram, the 2 clients are connected to the server, but not to each other.  You can't have this partial state with the ENet unless you set server_relay=false

![image](https://user-images.githubusercontent.com/677254/130946796-56c3da66-6463-47e5-bd71-a8d7bbab8978.png)

### Describe the problem or limitation you are having in your project

It would be great if all three low level protocols supported the same high level multiplayer functionality, and that they could be swapped in and out easily.  

The reason to use WebRTC is you don't have ENet on the HTML5 platform.  This is often a blocker when experimenting with making a release on the web if you have a networking game (as many games could easily be, and could be a lot more efficient streaming the rendered video stream on twitch).  You can use Websocket on HTML5, but it's slower and doesn't have the realtime unreliable channel.  

(In the long term (if the unusual inaccessible-server peer-to-peer feature is not needed), anywhere we used Websocket could seamlessly upgrade and integrate to WebRTC, while leaving the Websocket as the signalling channel so that all HTML5 games just had great networking by default.)

The `server_relay` option given in ENet.

https://docs.godotengine.org/en/3.3/classes/class_networkedmultiplayerenet.html#class-networkedmultiplayerenet-property-server-relay
> Enable or disable the server feature that notifies clients of other peers' connection/disconnection, and relays messages between them. When this option is false, clients won't be automatically notified of other peers and won't be able to send them packets through the server.

... is not enabled for WebRTCmultiplayer.

https://docs.godotengine.org/en/3.3/classes/class_webrtcmultiplayer.html#class-webrtcmultiplayer
> A simple interface to create a peer-to-peer mesh network composed of WebRTCPeerConnection that is compatible with the MultiplayerAPI.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I understand we are supposed to create a full mesh of connections between each pair of clients, and then finally one between the client and server, which then triggers the all the add_peer signals at once to make it seem compatible with the high level multiplayer code.  This pattern only works if you use it only for match-making.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The code behind the different protocols looks quite different.
I think the crucial _server_relay() for Websocket is here: 
https://github.com/godotengine/godot/blob/0cee8831b25377567bff8f46f7eaad8cb203dbf8/modules/websocket/websocket_multiplayer_peer.cpp#L209

And the functions for ENet are _relay() and _notify_peers():
https://github.com/godotengine/godot/blob/495319217244e576b150dcf1be2d75719c15cf2d/modules/enet/enet_multiplayer_peer.cpp#L590

But the design of the WebRTCmultiplayer doesn't have this.  It only has the facility to hold back peer_connected signals until the server peer is connected.
https://github.com/godotengine/godot/blob/495319217244e576b150dcf1be2d75719c15cf2d/modules/webrtc/webrtc_multiplayer_peer.cpp#L137

One of the ENet or Websocket ways of doing this could be copied across here.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If all my RPCs go through a single function I could implement server_relay for that function in the GD script, but then you are almost doing without the RPC system and implementing it by decoding and making the function calls yourself.  

Requiring all the client peers have WebRTC channels between them as well as to the server makes sense if the channels are carrying audio/video data, but is not justified for the binary RPC data where you have all the issues of the server resolving any conflict issues between the players.  

Multiplayer stuff is hard enough without adding in the possibility you can enter states where some channels can be missing or dropped and it is unclear what messages have got through between the players.  It is better to have only two possible states: connected to server (when all messages are getting through to all other connected players), or not connected to server (when you are totally on your own).   

### Is there a reason why this should be core and not an add-on in the asset library?

It's core to the WebRTC multiplayer module.

**Comment by goatchurchprime** [comment]
I attempted to implement this with code that is nowhere near good enough for a pull-request:
   https://github.com/goatchurchprime/godot/commit/b40a5c332735215c6419d0c3b5699b613c78111d

This would need implementation of the equivalent of `enet_packet_create()` to pack in some bytes at the front of the packets containing things like the `id` value for the `rpc_id(id)` function call and pass across the `peer_connected` signals.

The implementation of this same functionality is quite different in `WebSocketMultiplayerPeer::_process_multiplayer`, so it's not obvious which one the code should be modeled on.

For the time being I can implement this server_relay feature in pure GD script because I can route everything through a single rpc function present in a single node.

**Comment by Faless** [comment]
Using WebRTC you shouldn't need a `server_relay` option, or, in some form, `server_relay = true` is when `initialize` is called with `server_compatibility` mode.

But if you don't want a relay server, you should be able to that by just initializing the peer with `server_compatibliity=false` then only add the server peer in the clients. I.e:

```
# server.gd
rtc.initialize(1, false)
rtc.add_peer(client1, client1_id)
rtc.add_peer(client2, client2_id)


# client.gd
rtc.initialize(my_client_id)
rtc.add_peer(server_peer, 1)
# Don't add any other peer to clients, they will only be able to talk to the server.
```

**Comment by Faless** [comment]
Mmhhh.. it seems the `server_relay` option is also missing from `WebSocketMultiplayerPeer/WebSocketServer`, I guess it should be added there.
Given the above though, I guess we could indeed add a `MultiplayerPeer.server_relay` property, and then have all the other peers use that (including WebRTCMultiplayer, basically replacing the `server_compatibility` argument).

**Comment by Faless** [comment]
Nevermind, I just noticed that `server_compatibility = true` does not relay packets, but it should indeed. This should definitely be implemented.

**Comment by Faless** [comment]
I gave this some thoughts, and the more I this of it, the more it seems to me the functionality should be moved to the higher level `MultiplayerAPI`/`SceneMultiplayer` implementation.
There are good reason for letting the higher level API control the "peer signaling" (notification of new peers), e.g. to process handshake/authentication independently of the network layer (a much requested feature),
There still seem to be at least a case in "mesh" networks where a peer wants to claim to be the server while still preventing the higher layer to relay packets, signals peers.
So the implementation I propose in something on the line:

```gdscript
class MultiplayerPeer:
	# Overridden by peer implementation (depending on config). Used by higher level API to know the relay peer(s).
	virtual bool is_relay_peer(peer_id) # Returns true if peer_id is a relay peer.
```

```gdscript
class MultiplayerAPI:
	virtual void set_peer_signaling_enabled(enabled: bool)
	virtual bool is_peer_signaling_enabled()
```

Then in `SceneMultiplayer` (i.e. the default implementation of `MultiplayerAPI`) implement the following logic (pseudo-code).

```gdscript
func _add_peer(id):
	if relay_peer and multiplayer_peer.is_relay_peer(multiplayer_peer.get_unique_id()):
		# do peer signaling (i.e. send "new" peer to old ones, and old peers to new).

func _del_peer(id):
	if relay_peers and multiplayer_peer.is_relay_peer(multiplayer_peer.get_unique_id()):
		# do peer signaling (i.e. send "delete" peer to other peers.

func _process(packet):
	if packet[0] == COMMAND_SIGNALING:
		if not relay_peers:
			# Error, peer signaling not allowed
		if packet[1] == COMMAND_SIGNALING_ADD:
			# if I am a relay, error
			# else add peer if the source is a relay_peer, i.e. multiplayer_peer.is_relay_peer(multiplayer_peer.get_packet_peer()).
		elif packet[1] == COMMAND_SIGNALING_DEL:
			# Like above, for delete
		elif packet[1] == COMMAND_SIGNALING_RELAY:
			# if I am a relay, check and send relay
			# else process real packet if the source is a relay_peer.
```

Additionally, `SceneMultiplayer` internal access to `multiplayer_peer.put_packet` should be converted into a single (unexeposed) `SceneMultiplayer.put_multiplayer_packet` which takes the peer argument and convert it based on known "fake" vs "real" connected peers.
This design still allows custom MultiplayerPeer to implement their own relaying protocol and hide the peer signaling process if desired, but otherwise move the responsability of implementing a "default" relay/signaling protocol to the higher level MultiplayerAPI.

WDYT?
