### ISSUE TITLE
Enable Pixel Snap in the 2D scene editor by default

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-proposals#3209]
### Describe the project you are working on

I am working on a 2D game.

### Describe the problem or limitation you are having in your project

So far, I have never run into a case where I wouldn't want this to be turned on by default.
![image](https://user-images.githubusercontent.com/82024211/130985974-db1e7e7c-e569-49d8-a0df-3f764cb2dcb4.png)
Even in games where it doesn't really matter.

Often times i remember to turn it on too late and have to fix already existing scenes. Otherwise, I risk it being jarring or flickering.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Turn it on.

It's something you want to have turned on during the game creation but in the game, it can be overlooked. All I want is, to be able to place the sprites into the scene without having to think about if they are misaligned with other sprite by quarter of a pixel. I don't necessarily need them perfectly in the running game, for example on player character which changes position just too often for there to be a problem in this regard.

BEFORE and AFTER pictures.
![image](https://user-images.githubusercontent.com/82024211/130992105-bd12b521-0f10-4cbf-8b00-e1324b0036b7.png)
![image](https://user-images.githubusercontent.com/82024211/130992011-fa44554a-ba13-4011-b38a-96ddd386da76.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![iMxUP5rckw](https://user-images.githubusercontent.com/82024211/131008997-305bbf24-d3e9-4819-aec8-1911ced92ba8.gif)

Under ideal conditions, it won't even be noticeable change for the user unless they run into problems with it in the past.
The ideal conditions are when it's turned on.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often. It will be used by every 2D user even if they don't know it.

### Is there a reason why this should be core and not an add-on in the asset library?

It's user experience enhancement so small that making it with script or plugin is actually more complex than just turning it on in the source code.

**Comment by Calinou** [comment]
According to https://github.com/godotengine/godot/blob/43e96e0c652cd2ed41a1b9dfb7989ff272607a88/editor/plugins/canvas_item_editor_plugin.h#L567-L576, this should be the default already but it doesn't seem to be effective.
