### ISSUE TITLE
Make `OS.get_window_safe_area()` work on Android

### ISSUE THREAD

**Issue by NoFr1ends** [godotengine/godot-proposals#321]
**Describe the project you are working on:**
Mobile game

**Describe the problem or limitation you are having in your project:**
Currently it is not possible to handle display cut outs on Android devices. Instead the game will go into letter box and leave the area of the display cut out blank.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Adding the functionality of `OS.get_window_safe_area()` for android too.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
N/A

**Describe implementation detail for your proposal (in code), if possible:**
```
OS.get_window_safe_area()
```
This would return the safe inset for top, right, bottom, left.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This is an important API required for porting games to mobile devices properly, a possible work around would be to just add margins to the UI. I consider this work around as not optimal because this would add margins to devices without cut-outs or a notch too.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This proposal provides an important API for porting games to current mobile phones.

---

This also got an issue in the main repository:
https://github.com/godotengine/godot/issues/34466

---

**If this is okay to implement I can work on a PR.**

**Comment by NoFr1ends** [comment]
Resources:
https://developer.android.com/reference/android/view/DisplayCutout
https://developer.apple.com/documentation/uikit/uiview/2891102-safearealayoutguide

**Comment by NoFr1ends** [comment]
We found out that this is for iOS already implemented, only the android part is missing. I didn’t saw that in the docs.

`OS.get_window_safe_area()`

**Comment by akien-mga** [comment]
This was implemented by #43104 (`4.0`) and #43140 (`3.2`).
