### ISSUE TITLE
Custom text in progress bars

### ISSUE THREAD

**Issue by flyingpimonster** [godotengine/godot-proposals#322]
**Describe the project you are working on:**
Godot Version Manager, a tool to keep track of my projects and their needed Godot versions

**Describe the problem or limitation you are having in your project:**
I would like to have a progress bar that indicates the download progress of new Godot versions. Currently, a progress bar can only display a percentage, or no text. I want to show the progress as a ratio (like `1.2 / 26.6 MB`) instead.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
This will allow me to set the text of the progress bar separately from the value, so I can format it however I want.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![Screenshot from 2019-12-19 17-13-44](https://user-images.githubusercontent.com/24497353/71217448-7b205c80-2283-11ea-98af-880b3a1501b5.png)

**Describe implementation detail for your proposal (in code), if possible:**
This would be added as a String property, `custom_text`, to the ProgressBar class. If the property is set and `percent_visible` is `true`, it will be drawn in the middle of the progress bar in place of the percentage.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
As far as I can tell, no. I've tried using custom drawing on the ProgressBar node and it does not seem to work.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't think this is possible using a script without writing an entirely new ProgressBar implementation.

**Comment by flyingpimonster** [comment]
I can create a PR for this.

**Comment by girng** [comment]
You can add a label as a child, set layout to full/wide, and center text

**Comment by Jummit** [comment]
> As far as I can tell, no. I've tried using custom drawing on the ProgressBar node and it does not seem to work.

You should look into that. It is definitely possible.
Your problem could be that you don't call `update` to redraw the node.

**Comment by SuperDIMMaX** [comment]
This in first look good, but... this not realy good.
My opposition - remove text from this bar...
> You can add a label as a child, set layout to full/wide, and center text
I like Godot for clean. Hardcoded text - excess.
If not need text - Godot not need create text, load font, set margin.... less function - more framerate.
If need text - cteate label or draw text directly as you like... in mostly case need special text, suffix, prefix, seperation....
In one project i create progress bar - draggable button with pressing state and icons (progress bar work as seperator bitween top and bottom)

**Comment by flyingpimonster** [comment]
Thanks for all the advice. Since this turns out to be easily worked around I'm going to close the proposal.
