### ISSUE TITLE
Add scene recovery for "invalid/corrupt" scenes

### ISSUE THREAD

**Issue by zeroxoneafour** [godotengine/godot-proposals#3221]
### Describe the project you are working on

I was trying to make a title scene and import an image.

### Describe the problem or limitation you are having in your project

I tried importing images using the manual path settings of the Texture object, but couldn't. I then found another way, did that, and saved my project. When I tried to load it again, it failed to load the scene I worked on and couldn't recover it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to recover scenes that are invalid/corrupt, if they are recoverable (some parts of the scene can be loaded and some parts cannot)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

 When a scene is loaded and found to be invalid/corrupt, either just don't load the invalid parts or set them to default values, if default values are available. If the entire scene is corrupt, give a more descriptive error so the user can try to fix it manually. When saving a previously invalid scene, notify the user before overwriting the old, invalid scene.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This, as far as I know, can not be worked around with in-editor script. It would require a needlessly sophisticated script. It would be easier just to implement it in Godot, because Godot can already parse scenes and knows what is wrong with them.

### Is there a reason why this should be core and not an add-on in the asset library?

As far as I know, this cannot be an add-on because it deals with the low-level parsing of the scenes.

### Minimal reproduction project, containing an "invalid" scene

[InvalidSceneTest.zip](https://github.com/godotengine/godot-proposals/files/7073026/InvalidSceneTest.zip)

**Comment by Calinou** [comment]
I don't really see a way to recover scenes that are corrupt on disk. Your options are to use [version control](https://git-scm.com) to revert to a previous revision or edit the `.tscn` file manually to make it valid again.

**Comment by KoBeWi** [comment]
Sometimes the scene is "corrupted" if there is external resource pointing to invalid path. Normally you'd get a missing dependencies dialog, but in case of "corrupted" scene you only get message in the external console. Although this case is more a bug.

Other cases are when there is node referencing invalid resource id or if `load_steps` don't match resource count. Or if there is parsing error in the scene. This should be recoverable, given the structure of tscn (just ignore faulty resource/node). Although manual fixing is possible, because you can see these errors in the console.

**Comment by zeroxoneafour** [comment]
> Sometimes the scene is "corrupted" if there is external resource pointing to invalid path. Normally you'd get a missing dependencies dialog, but in case of "corrupted" scene you only get message in the external console. Although this case is more a bug.

This is what the problem I had was

**Comment by zeroxoneafour** [comment]
I made a GitHub project which can fix broken references in Godot scenes, but I'm 99% sure this doesn't work past very obvious cases.

[zeroxoneafour/godot-scenevalidator](https://github.com/zeroxoneafour/godot-scenevalidator)

**Comment by nathanfranke** [comment]
> Other cases are when there is node referencing invalid resource id or if load_steps don't match resource count

Just tested in 3.x and 4.x, and I can't get a parser error just by changing the load steps. Though I remember this being an issue at some point.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/6838, which is more detailed and up-to-date with the current situation.
