### ISSUE TITLE
Display bookmark, breakpoint and execution line markers when the gutter is hidden by underlining lines or line numbers

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#3222]
### Describe the project you are working on

Godot's editor settings

### Describe the problem or limitation you are having in your project

I wanted to save some horizontal space on my monitor without hiding information. The bookmark gutter uses the same space the breakpoint gutter does, but it can't adapt to being hidden: there is no longer any way to know when a line is bookmarked.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Without using extra space, show an alternative bookmark, like with breakpoints.

![with](https://user-images.githubusercontent.com/85438892/131257822-59fee0b0-4cb2-4752-bdb0-e1543d4dad50.png)

![without](https://user-images.githubusercontent.com/85438892/131257828-9a6618fb-cc9b-4241-8e89-0057192d5330.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A system similar to the breakpoint gutter would probably work. A line only under the number would be even less obstructive.

![implement](https://user-images.githubusercontent.com/85438892/131257840-890004df-91ff-47ce-bb3c-686775fc9e37.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Scripts can't work around it, as far as I know. It's an editor setting.

### Is there a reason why this should be core and not an add-on in the asset library?

A near-identical feature is already core.

**Comment by Calinou** [comment]
Good idea, but I prefer the line number variation (perhaps with a thicker line width) as it's less obstructive.

**Comment by MewPurPur** [comment]
I figured a big line would actually not work.

Because it can collide with the other lines if they are on the same line; it would be too confusing and inaccessible if the colors mix, it would be too crammed if they are next to each other, and information would be hidden if one covers another.

**Comment by dalexeev** [comment]
I think we can use fill for bookmarks and underline for breakpoints. In Kate, for example, bookmarks look like this:

![](https://user-images.githubusercontent.com/47700418/131288902-552d472f-446b-4ff8-9978-bfe56413647c.png)

Those it should look something like this (only we need to choose better colors):
![](https://user-images.githubusercontent.com/47700418/131289013-39f73d76-21ae-47a3-91fb-dfc38e87ca12.png)

**Comment by MewPurPur** [comment]
This issue is pretty irrelevant now, as we don't have the feature in Godot 4.

**Comment by MewPurPur** [comment]
This issue is pretty irrelevant now, as we don't have the feature in Godot 4.
