### ISSUE TITLE
Suggestion for improving colors of nodes to increase recognizability of graph edits . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3225]
### Describe the project you are working on

A 2.5D game, with barbarians, and some lore . . . .

### Describe the problem or limitation you are having in your project

First of all, I really like the more muted colors, of graph edits, it's more calm and, works well for me or, so . . .

But, a problem is, that now graph edits look very similar, before it was easy to see different parts and, find scripts made earlier, by looking for a certain ' color ', or graph nodes, on a small piece, of the graph edit canvas . . . But, bec. the colors are now almost the same, it bec. one big blur . . I was thinking, maybe one could keep the muted colors but, make the headers more distinct, atm. they're green, brown and, faded red . . . Was thinking one could use dark green, dark yellow, dark orange and, dark blue, so the scripts were a bit easier, to recognize, when re-reading or, some later de-bugging . . .

Also, I think perhaps the nodes are a bit too muted, in color and, I would suggest making them a bit more colored . .

Before . .
<img width="1920" alt="2021-08-30 0847" src="https://user-images.githubusercontent.com/83387915/131298790-5385846f-ecd7-475e-a3ca-b64d9c7f43d1.png">

After . . .
<img width="1920" alt="2021-08-30 0900" src="https://user-images.githubusercontent.com/83387915/131298820-3681690e-9b91-4688-b76b-f1a0dc2ccf1c.png">

So, right now the nodes well, fade into the background and, bec. a bit obscure . . . I like the faded look and, would propose a slight increase, for visual readability or, maybe a slider, where one could set custom contrast or, maybe saturation value . . .

Overall, visual script, and graph edits are getting much better, and there have been many small, but really nice bug - fix to nodes and, UX . . Was thinking, this might be a place, where something could be done, so it's friendly but, also competent or, so <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, like above, maybe change a few things . . Right now the nodes, sort-of all look identical, bec. of the muted colors . . . I'd maybe use more colors, like yellow, dark orange, really dark green and, really dark blue . . .

Or, add a setting to increase the saturation, to improve well readability . . <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like above, graph edits are already much better, was thinking this might be a good thing, considering UX . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't do this . . Otherwise I'd suggest making the node headers customizable, in theme editor or, like that . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, the faded look is really nice but, it makes the scripts or, graph edits look like a blur, every-where looks the same . . . It's nice but, it affects readability, of the script . . . A modest, and simple increase, in hue or, saturation, would make it easier, for long - term users, at least, or people needing visual script, for a shader or, perhaps particle graph or, short proto-type, visual scripting . . . . .

**Comment by charlesmlamb** [comment]
Note also, I think the best look for logic boxes, or code ' flow ' is black header and, white or, light grey inside node, for functions, etc . . . I'm hoping maybe we could get some customization options, to make a custom look, or something . . .

**Comment by charlesmlamb** [comment]
Last, if one made bas. a grey-scale or, almost grey-scale version, and had a slider, to set some values, maybe 4 settings, from almost grey-scale to, modest colors it'd, be quite nice or, so . . . .

I think such a grey-scale, where each box had a slightly different shade or, 'greyness' might, be a basically 'stable' experience but, it'd be difficult to read and, for hard - core coders or, so . . .

**Comment by charlesmlamb** [comment]
Now, I've been studying some ideas and, I've found that there's a 'spectrum', where one can got almost completely grey-scale, very thin lines between nodes, and very pale, that falls within communist ideology, that does not bec. objective evil, see here . . .

![Templar - Kopi](https://user-images.githubusercontent.com/83387915/131306340-ca6985b1-2ac3-4652-a9bf-dad345c400d2.jpg)

So, one should have an almost grey, dystopian theme, and on the other hand, there's a smaller window, for capitalism, where one could make SLIGHTLY over - saturated color boxes, sort of . . . .

<img width="1139" alt="Skærmbillede (2106)" src="https://user-images.githubusercontent.com/83387915/131306713-f5a4d7ec-4b88-40bc-a1d1-af3454e07d74.png">

Perhaps, bit less . . . That way, people from different backgrounds could have their favorite theme or, experience and, it'd be the well ideal range, of user - customizability, hard, difficult communism and, honest, decent, modest capitalism or, so . .

It'd make Godot more appealing, and keep it within 'reason' or, respectability or, so . . . Thx <3 . . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
