### ISSUE TITLE
Comment boxes in graph edit is very difficult to see for some themes . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3226]
### Describe the project you are working on

A 2.5D barbarian game, with lore . . .

### Describe the problem or limitation you are having in your project

Right now, for my theme, also light theme, comment boxes are very difficult to see . . .

![Skærmbillede (2107)](https://user-images.githubusercontent.com/83387915/131300142-c283890c-4470-4427-bc6b-390a373d0544.png)

I'd suggest making the background opaque, bec. then one could see them, over the grid, ie. grid not visible, if there's a comment box . . . Right now, it's almost impossible to see them, was thinking might be made some changes or, so . . .

Light theme . . .

![Skærmbillede (2108)](https://user-images.githubusercontent.com/83387915/131300335-fcfea0fb-0d04-4ad0-896e-16f1f17e2471.png)

Not sure what to do, but it's almost impossible to ' box ' an area and, see what the comment is referring to . . . . Thx . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, some way that the comments boxes are easier to see, maybe ability to set color of each comment background or, opacity, not sure . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, not sure, right now they're almost impossible to see, or so . . . See above . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Right now, the default settings isn't working, for some themes, also it's not ideal, for the default theme . . . Was hoping, it might be made better . . . For me, I'd just like them to be opaque, so one could see them, bec. the grid would disappear, where there are comments . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, the default settings aren't working, not sure . . . . <3

**Comment by charlesmlamb** [comment]
The comments, are here . . . >>

<img width="1920" alt="Skærmbillede (2109)" src="https://user-images.githubusercontent.com/83387915/131300763-658ea2b0-54bf-4d23-915f-c40bb200836e.png">

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
