### ISSUE TITLE
Add increased size font comment for better review and, re-reading of code in a graph edit . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3227]
### Describe the project you are working on

A 2.5D game, with barbarians . . .

### Describe the problem or limitation you are having in your project

Right now, graph edits are under-going a massive improvement, towards better UX <3 10 / 10 . . .

I was thinking, since one tends to zoom when, working with big scripts, adding ability to set size, of comment font, or have some presets, normal, large . . Would help in reviewing and, finding code later, esp. for big scripts . . So, like this . . . >>

<img width="1920" alt="2021-08-30 0930" src="https://user-images.githubusercontent.com/83387915/131302821-5cf1e774-4ad4-4504-a368-c66ee2a5a937.png">

Sorry, it is difficult to say how much better graph edits are getting, I think with few more customization options, one can make a really solid or, cool graph edit canvas . .

Comments are very useful, for reviewing code, or later bug - fixing . . . But, graph edits are different from written code, in that one often pans and, uses the zoom function, for larger scripts or, so . . Having an extra large comment size, or font, would help, in re-reading such scripts, much later and, navigating, so on . . . . Thx . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Like above, this is sorely missing, from graph edits, bec. one tends to zoom, unlike well written code, where one scrolls and, has a search function, so on . . . Was thinking, this might be one way, to help making comments or, annotations, for graph edits . . Atm., it's these small things we need, then I think graph edits are 100 % solid, or could be, with some extra customization options . . . It's getting there, still needs work and, lesser updates, thx . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like above, add the option to make comments, with larger fonts or, to write on canvas, for commenting, navigating, review or, bug - fixes, thx . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't do this, it's ONE suggestion, for making it easier to navigate graph edits, it's already getting really good, I think in Godot 4, or 4.1, it'll be rock - solid, just nice . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it's mostly for comments and, reviewing code, like written code, where it's easier, or so . . . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
