### ISSUE TITLE
Question: Would adding EARenderer instead of OpenGL 3.0 be a nice thing . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3228]
### Describe the project you are working on

A barbarian game, 2.5D . . 

### Describe the problem or limitation you are having in your project

One of reasons I haven't made any games in Godot 3.3, is bec. OpenGL is quite old, and I think it would crash, with modern 3D models, etc . . I saw this and, well was wondering, would it be in any way useful, to add support for this, or add to OpenGL features, using this demo . . .

https://www.youtube.com/watch?v=n0ktyKqq1UE

> https://github.com/man-in-black382/EARenderer/blob/master/EARenderer/Engine/Foundation/CRC32.cpp

I don't really understand it, but it has global illumination, and all kinds of stuff . . It looks quite nice . . Could one update OpenGL 3.0 in Godot, to have some of this or, will Vulkan completely replace OpenGL . . . I honestly though OpenGL was so old, like from 2005, or, like that and, DirectX was the new standard, and it was just completely dated or, such . . .

Well, why not have both but, maybe Vulkan is much better . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Sigh, watched an OpenGL vs. Vulkan demo, and it looked, well similar . . . I thought OpenGL was much worse than DirectX, or basically anything . . . Is OpenGL still viable, I mean, had similar frame-rate to Vulkan, some years ago, and I had no idea visual were about the same . . .

Was wondering if Godot could have an updated OpenGL, with optional support, for such things but, maybe Vulkan will just well, be better <3 . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, sorry . . Honestly thought OpenGL was obsolete, in 2005, or 2006 . . . Was thinking, that demo looks nice, and maybe one could make a faster version, not sure how good Vulkan is, atm . . . Thx . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, wanted to ask, if there could be improvements to OpenGL, that were toggled, so the basic OpenGL 3.0 would stay same but, it could do more, it might be dumb . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, had no idea they still worked on OpenGL, the EARenderer looks amazing, just wondering . . . Thx . . <3

**Comment by charlesmlamb** [comment]
It's bec. right now Vulkan, and sdfgi doesn't look so good, in Godot 4 nightly, there are weird shadow problems and, well would an OpenGL global illumination be faster, since OpenGL is older and, runs on older hardware, or not sure . . .

**Comment by charlesmlamb** [comment]
Well, it has stuff like surfels and, Cook-Torrance BDSF, looks like nice code, wouldn't it be cool or, so . . :OO 

Cone-traced SSR :OO . . . Sounds like, neat stuff <3

**Comment by charlesmlamb** [comment]
Last, there's also this Pathfinder renderer, it honestly looks better than Vulkan . .

>> https://www.youtube.com/watch?v=1oZw7PCOC2E

It looks like it's made, by one guy, and it's on gitHub, really crazy . . . :OO . . . .

**Comment by Calinou** [comment]
Godot has no plans to use external renderers such as EARenderer bgfx and will stick to raw OpenGL for a few reasons (when it's implemented in Godot 4.x). This is mainly because third-party libraries can suddenly fall out of maintenance – in fact, EARenderer doesn't seem to be actively maintained.
