### ISSUE TITLE
Allow any floating-point value for Lightmap Scale in MeshInstance instead of just 1×/2×/4×/8×

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot-proposals#3233]
### Describe the project you are working on

3D environments

### Describe the problem or limitation you are having in your project

Related with #3213 

The mesh scale on the lighmap is controlled by an enum. This is not optimal to control neither the quality or space of lightmap. In this case x8 is almost enought but not a granular control

x1
![image](https://user-images.githubusercontent.com/1168582/131378304-cc430e94-4888-480b-aeb0-8e2ad3e64546.png)

x8
![image](https://user-images.githubusercontent.com/1168582/131378552-283b8236-e888-4cc5-8ccb-7d2516d0a7c7.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow float numers instead of a fixed enum in the scale.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope

### Is there a reason why this should be core and not an add-on in the asset library?

Lightmap is core

**Comment by Calinou** [comment]
cc @JFonS

**Comment by Calinou** [comment]
There's probably a reason as to why only power-of-two scales are allowed. My guess is that the atlas is only designed to work with power-of-two sizes, as you'd end up with wasted space if you used a non-power-of-two size (since the reserved space in the atlas would "grow" to the next power of 2).

**Comment by jcostello** [comment]
> There's probably a reason as to why only power-of-two scales are allowed. My guess is that the atlas is only designed to work with power-of-two sizes, as you'd end up with wasted space if you used a non-power-of-two size (since the reserved space in the atlas would "grow" to the next power of 2).
> 
> cc @JFonS

`lightmap_size_hint` allow any Vector2. 
When importing a model, the `meshes/lightmap_texel_size` allows any float number. It directly impact on the `lightmap_size_hint` of all meshes imported

Probably we should unify the ways to improve the texel size. I understand that a power of 2 could be ideal to preserve space in the lightmap texture but is flexible enought. And you can waste space anyway with the `lightmap_size_hint`

**Comment by Calinou** [comment]
It turns out this is actually trivial to do: https://github.com/godotengine/godot/pull/75164

**Comment by WickedInsignia** [comment]
It's generally optimal in the workflow if this scales down, not up.
So 0.1, 0.5, 0.8 etc. rather than 2, 4, 8. Having the latter is important but less-used.
It's more common that most meshes in a scene will adhere to a set global texel density, and a handful of larger or further-away meshes will be reduced in lightmap size to save space. It rarely happens that artists scale upwards because that would need to be applied to most meshes in the scene and is the most time-consuming approach.

Granularity should be present in both directions but the current system prioritizes scaling-up in a way that should be dropped in future iterations.

**Comment by jcostello** [comment]
Thanks <3
