### ISSUE TITLE
Make the handle types of Bezier animation keyframes a property stored for every keyframe

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-proposals#3236]
### Describe the project you are working on

This is a proposal to improve the behavior of curve handles and curve manipulation in the animation Bezier curves editor.

In short, I think the handle type should be a property of the keyframes to give animators full control over the curves' interpolations.

This proposal would supersede one point of #3141 

### Describe the problem or limitation you are having in your project

In the current editor, you have a drop-down menu to change the mode of the handles.

![Screenshot from 2021-08-30 16-48-12](https://user-images.githubusercontent.com/12694995/131415521-d4f0e29d-5bbe-4b5d-814e-2831eb370905.png)

They can be free, balanced, or mirrored, allowing you to either get smooth and round curves or sharp turns in your curve, helping you design jump animations and so on.

When you select keys and change the option in the drop-down, nothing happens.

You have to change the mode first and then click on a keyframe's handle for it to update.

This causes three issues:

1. Depending on the position of the handle, it might jump to a different position when you click on it as the mode change updates its position, making the editor feel a little janky.
2. As a result, **you can't update the handle mode of many selected keyframes at once**. You have to click on each keyframe's handle individually.
3. Lastly, the selected mode always gets applied to the handles you click. Meaning if you have to edit a curve with many keys and they use different modes, **you have to constantly switch between the modes as you move through your timeline and edit your animation**.

In animation, it's very common to cleanup the animation in passes going from start to the end, so this makes the process of refining and polishing animations slow and tedious.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think the handle type should be a property of every keyframe. It should be persistent so that when you select the keyframe again, they use the handle mode you set them to.

If this becomes a property of the keyframes, we can remove the handle mode drop-down on the right side of the Bezier editor and have the property appear in the inspector.

The user would be able to change the handle mode property on all selected keyframes at once.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

With the suggested changes, the user would change the handle mode like so:

- Select one or more keyframe
- Change the handle mode property in the Inspector

Optionally, it could be nice to provide quick access to those options from the right-click context menu, as commands. This would limit the need for animators to leave the animation editor. Blender and other animation programs offer options like those.

![Screenshot from 2021-08-30 16-55-26](https://user-images.githubusercontent.com/12694995/131416166-277b498e-1d79-4313-9bc7-8b2c333c37a2.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's something you use often as an animator and part of a built-in editor.

### Is there a reason why this should be core and not an add-on in the asset library?

It's part of the animation editor.

**Comment by lyuma** [comment]
is there a way we can allow constant or discontinuous keys? Right now I can emulate those by setting very large values for "x" in a bezier track, but it would be nicer to set "constant" explicitly.

![blender_constant_bezier](https://user-images.githubusercontent.com/39946030/131439347-8ceb2c9a-f00f-4677-b221-85dbd4c054db.png)

As an example, it is possible to roughly get "Linear" and "Constant" keys in the bezier editor, but unintuitive (and causes the bezier handles to be hard or impossible to click on)

To get linear:
previous key Out Slope=0,0 and next key In Slope=0,0

To get step after previous key:
previous key Out Slope=0,0 and next key In Slope=-1000,0

To get step before next key:
previous key Out Slope=1000,0 and next key In Slope=0,0

To get step exactly in between two keys:
previous key Out Slope=1000,0 and next key In Slope=-1000,0

**Comment by NathanLovato** [comment]
Hi @lyuma, that'd surely be good to add, but also beyond the scope of this proposal. The way to code that's different from this, and would likely need to come after implementing this proposal. You can open a separate proposal if you'd like.

**Comment by NathanLovato** [comment]
It's in progress here, just a couple bugs left to solve: https://github.com/NathanLovato/godot/tree/GDQuest/animation-bezier-editor-ui-improvements

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/53298.
