### ISSUE TITLE
Add button to create `CollisionShape/Polygon` in Node Configuration Warning window

### ISSUE THREAD

**Issue by tischenkob** [godotengine/godot-proposals#3242]
### Describe the project you are working on

Generic platformer

### Describe the problem or limitation you are having in your project

When I add a node that requires a collision shape, there is a warning which, when pressed, says that I should consider adding a CollisionShape or CollisionPolygon without providing a quick way to do so.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add two buttons that allow to instantly add CollisionShape and CollisionPolygon child nodes

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Beside "OK" there would be buttons "Add CollisionShape" and "Add  CollisionPolygon"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by manually adding a child node in a few more steps

### Is there a reason why this should be core and not an add-on in the asset library?

I believe, there is no reason not to add this to core since it will increase productivity and provide a slightly more new-user-friendly and convenient piece of functionality

**Comment by Calinou** [comment]
The issue is that exposing runnable actions in the node configuration dialog is difficult to do. The API is just designed to return a PackedStringArray, and associating runnable actions to each string is going to be difficult to implement (if even possible).
