### ISSUE TITLE
Add an argument to `Navigation2D.get_simple_path()` to return a path without diagonals

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-proposals#3246]
### Describe the project you are working on

turn based 2D game

### Describe the problem or limitation you are having in your project

to implement simple grid based path-finding you have to do it on your own in A* when there is perfectly viable navigation system available.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

add new argument
`get_simple_path ( Vector2 start, Vector2 end, bool optimize=true, bool diagonals=true )`

This simple change allows to make with much ease simple roguelikes, turn based strategies, JPRG AIs and many other games.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

get_simple_path(start,goal,true,false)
now you can make a simple rogue-like in 5 minutes.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's probably very small change to the source.

### Is there a reason why this should be core and not an add-on in the asset library?

it's a change to GDScript

**Comment by kleonc** [comment]
@Calinou There's no `AStar.get_simple_path()`, it's about `Navigation2D.get_simple_path()`:
> get_simple_path ( Vector2 start, Vector2 end, bool optimize=true, bool diagonals=true )

---

@SilencedPerson `Navigation2D` isn't grid based so not really sure what you're suggesting in here. Seems like you're misconcepting something.

**Comment by SilencedPerson** [comment]
> @SilencedPerson `Navigation2D` isn't grid based so not really sure what you're suggesting in here. Seems like you're misconcepting something.

You are actually right, I was using it with tilemap.
