### ISSUE TITLE
Change Camera2D "current" property to "enabled" and make it true by default

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#3253]
### Describe the project you are working on

Mostly 2D games.

### Describe the problem or limitation you are having in your project

Whenever I add a Camera2D, I set it as current. Well, not always. I sometimes forget and then I turn it on after realizing what's wrong. When this happens I waste a couple of minutes.

This is potentially also a problem for beginners.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

2D cameras should be "current" by default. However this is not as straightforward thing as in 3D. In 3D, there is no rendering without camera. When you add camera, the first one in tree is automatically set as current. In 2D you don't need camera to render, **but** when you add one, 99% of the time you want it to be current. However due to the camera being optional in 2D, there should be some way to disable a camera node.

To make 2D cameras work similar to 3D ones while keeping them optionally active, the "current" property could be changed to "enabled". The first enabled 2D camera in tree would be the one affecting canvas. This way if someone just wants to add an camera, without affecting the default view, they could set `enabled` to false.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`current` property wouldn't be explicit property anymore. `set_current()`, `is_current()` etc. methods should be kept for convenience, but Camera2D would now have an `enabled` property that works as described above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Technically it's possible to make a custom class inheriting Camera2D, but the issue is mora a usability problem that's more relevant for newly created 2D projects (as adding cameras is usually done on early stages), including prototypes.

### Is there a reason why this should be core and not an add-on in the asset library?

Needs a rework of 2D camera.
___
Original issue: https://github.com/godotengine/godot/issues/31153

**Comment by MaaaxiKing** [comment]
`enabled` sounds like it were possible to have multiple cameras enabled. Furthermore, "enabled" is just a synonym for "true" in this case. Better would be `active`, but in my view, `current` is the best of all those and more which I can think of now.

**Comment by KoBeWi** [comment]
The problem with `current` is that only one camera may be current and also setting it will set `current` of all other cameras to false. Due to this, `current` can't be true by default, because it will interfere with multiple cameras.

> enabled sounds like it were possible to have multiple cameras enabled.

This is true. Only the first one would be active, the others would be on standby. Well, determining the camera order in an intuitive way would be the most difficult task here 🤔

**Comment by ZuBsPaCe** [comment]
Wouldn't it maybe at some point make sense to actually allow multiple active Camera2D siblings?

There's a proposal which wants to allow multiple active 3D cameras in a scene: https://github.com/godotengine/godot-proposals/issues/956. You could maybe think of similar scenarios in 2D.

What I always wondered is this: Why can't I have two active Camera2D's where one of them has a custom_viewport set? This would be quite useful for advanced shaders, if cameras could cull/filter some CanvasItems 

However: The last point will not be necessary anymore, after CanvasItem/Viewport visibility layers https://github.com/godotengine/godot/pull/52389 and viewports with root world_2d https://github.com/godotengine/godot/issues/31856 land.

**Comment by MaaaxiKing** [comment]
I have no idea how multiple cameras could be active simultaneously.
Another solution for the problem could eventually be the following: There is no such property—be it named ”current“, ”active“ or ”enabled“—, but the one camera which is the bottommost (because of the draw order) of all cameras in the scene tree could automatically, internally be chosen;
any thoughts on that?

**Comment by Zireael07** [comment]
@MaaaxiKing That solution doesn't allow implementing player switchable camera views, e.g. first person to third person or chase to cockpit.

**Comment by MaaaxiKing** [comment]
You could have multiple cameras in the player scene and then call `move_child` on the camera you want. But that's not a nice way to handle it, is it?

**Comment by Xrayez** [comment]
> Whenever I add a Camera2D, I set it as current. Well, not always. I sometimes forget and then I turn it on after realizing what's wrong. When this happens I waste a couple of minutes.

I agree that it's not intuitive for beginners, and even experienced developers forget about this. I don't know about 3D, but this is a real issue in 2D, and should be treated separately. Of course, we should strive for consistency, but not to the point of hurting the developer/user experience.

Those who know and care about multiple cameras will be able to manage it. Therefore, `current` must be enabled by default, we've already had a lot of changes in Godot 4.0 making features enabled by default, like raycast nodes.
