### ISSUE TITLE
Add some different themes for the GDScript code . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3254]
### Describe the project you are working on

A barbarian game, 2.5D . . .

### Describe the problem or limitation you are having in your project

First of all, amazing work, on the engine, wow . . .

Now, I'm sort-of ready, to begin writing code, start with GDScript . . And, it's super - nice, so on . . .

I have one big thing, it looks well, like it's for kids, sort-of simple or, so . . . That's not a problem, and it will then appeal, to that group of coders . . . Was hoping maybe a few themes, could make it look a bit more pro, or like ' average ' coding programs . . .

The problem is, I don't feel like trying GDScript, bec. it looks like kid's code or, programming . . . Like, I just think this will crash or, be sort-of slow, or not really ' pro ', like normal programs, that's all . . .

![code01](https://user-images.githubusercontent.com/83387915/132114301-ae2df190-7097-458e-b0ff-a8bff8cb85bf.jpg)

![code004](https://user-images.githubusercontent.com/83387915/132114310-f043241d-39b6-444c-bfd7-cf25c8d6c815.png)

![code003](https://user-images.githubusercontent.com/83387915/132114543-d77683da-39e5-4bcc-bd3a-c836b777c280.jpg)

Well, idea is, make some of the themes update coding look, right now, nice as it is, it sadly looks noob . . And, I get that, anyway just makes me not want to use GDScript, bec. it looks un-professional, crash - prone or, over-simplistic, for stuff I had been working on, as projects or, so . . .

So, suggestion is, IF possible, make some of themes update the look of GDScript, so it looks more like professional coding stuff, like C#, Visual basic, so on . . . .

This is a well bad image but, something a bit more ' sturdy ' or, normal . . . :OO . . . 

![code0045](https://user-images.githubusercontent.com/83387915/132114404-83636cbe-5ba6-4a66-a348-41bdc5c9afd6.jpeg)

Atm, don't feel like using it and, skipping to C#, to get more ' confident ' or, average UX <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Sorry, I know this is a big thing and, was hoping someone might have some ideas, I get the engine is also made, for a younger audience, it's a bit sad it can push more grown-up stuff away, or so . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, idea is, make some of the themes, completely re-vamp coding experience, or what is possible and, make it look like a more crisp or, 'solid' UX <3 . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Sure, one can customize GDScript, it's just a bit weird, that it's made to appeal, to kids, I think most devs are 18 +, at game jams and, kids is a small well number, of user - base and, perhaps not the ONLY age - group, the engine is made for . . . I know current theme has been used, for a long - time, but I think it could be more well adult or, ' confident ', and still appeal to kids . . . Thx . . . ! ! 

### Is there a reason why this should be core and not an add-on in the asset library?

Not sure, atm. sort-of get worried, GDScript is so simplistic, it can't be used for more advanced coding, AI, etc etc . . . . Thx . . . ! !

**Comment by charlesmlamb** [comment]
The point is, I guess, try and find a better coding UX, that has broader appeal while, keeping it friendly and, ' exciting ' . . .

I'm thinking age 24 - 32, or almost normal coding UX, or so . . <3

**Comment by charlesmlamb** [comment]
Perhaps, towards a more ' universal ' look or, 'theme' . . <3

**Comment by charlesmlamb** [comment]
Well, since Linux, MIT . . . emacs, looks nice . . :OO . . . .

![code0043](https://user-images.githubusercontent.com/83387915/132114977-90048c39-6000-4df1-9571-40a1626abaaf.jpg)

![code0024](https://user-images.githubusercontent.com/83387915/132114989-0d13603a-b175-485d-9a62-b1843e95eae7.gif)

Tbh, it makes the engine look dated and, geared towards kids only, or at least mostly . . .

Hope you, might be able to find something, well more adult or, sort-of respectable + recognized, as hard - core or, decent code programs . . . <3

**Comment by charlesmlamb** [comment]
Last, I think a good topic might be, what age - group should the engine appeal to, or so . . . Talking web - site, design, etc . . .

Imo, 16 - 24 is lowest, I'd say ideal is 22 - 36, or so . . . And, then everyone would feel more welcome and, the difficulty of the software, would match user - skills or, so on . . . Well, it's something to debate, hence it's a very simple, or early suggestion or, so . . . <3

**Comment by charlesmlamb** [comment]
Like, if it's even important, at what age are you ' ready ' to enter the media, full knowledge and, consent . . . I'd say 28 - 34 . . . At that age, you know what you're doing, and can handle the attention, say no, and understand the finances, or well bigger perspective . . .

Strict people might say, 28 - 38 is age, should be appealing to but, I think most responsible people know, the media or, 'entertainment' can be difficult, and worst case, well engine might be setting kids up for a ' fall ' or, problems, social, etc . . .

Again, maybe this is something to discuss, that's all . . . .

**Comment by sairam4123** [comment]
Well if you want to you use full blown programs use, C++ or C# instead of GDScript, GDScript has the name for it's simplistic and minimalistic style. We want to have a language that integrates with the editor.

> So, what is the responsible age, to ' sell ' the engine to, or present it . . Not sure, I'd say 26 - 38 <3

I wouldn't recommend selling the editor to specific age group.

**Comment by charlesmlamb** [comment]
Well, looking for some adults to chime in, and sort-of be reasonable . . .

I would not recommend a friend, from school, to begin making media, until after 24 and, having studied it at university, some experience and, then, is this for you or, well, can you handle it . . .

I think the corporate media tends to make things look easy, that are 'corrupt' or, well perhaps dangerous . . . And, open source or, MIT means free, also read the code, but it's also a maybe larger culture, that's pro - responsibility and, pro - decency . . <3

That's why I think, perhaps some get wrong idea, and don't really think about it, with so much media, kids, or young people being hyped and, made into ' products ' or, commercial ' figures ' of fame, or so . . .

I think maybe we need a counter - revolution, more sanity and, respect . . . And, I think many working for the engine, maybe have somewhat similar views, sure, plenty of fun but, also be careful, don't get into trouble, so on . . . !

Anyway, it's just a debate, hope someone will look at it and, think it through and, give a reflected, or perhaps noble perspective, not sure . . . Thx . . !

**Comment by sairam4123** [comment]
I'm pretty confused and can't understand you properly, what are you trying to say?

**Comment by charlesmlamb** [comment]
I'm saying a game - engine, allows you to make art or, vain stuff and, it's not safe to handle for kids . .

Thx . . . .

There's also publishing and, fame . . . Those things tend to cause problems, even for adults, as I see it . . . <3

**Comment by sairam4123** [comment]
Well.. there're tons of people who makes games. We can't stop kids from doing it. It's their wish to do it.

**Comment by charlesmlamb** [comment]
It's really a matter of how orthodox, modest or, respectable you are . . .

I think a solid soul would say, 26-28 to 38-44 is, proper age - group, to appeal to <3

That's all . . . .

**Comment by Cearaj** [comment]
Uhm, is this all about themes?

**Comment by charlesmlamb** [comment]
Sorry, it's about same thing, making more well adult . . And, why it's a good idea, not sure . . .

Just hoping people will think about it, for some time, and maybe decide . . . I'd say in Europe, it's prob. 24 - 38, if one goes to Russia, more strict, 30 - 44 . . . Before that, don't promote yourself and, don't do so, unless you have something to say, that matters . . .

I think Godot, should appeal to that age - group, well web - page, etc . . .

Here's a COMMERCIAL page, but I think it sends a more ' respectful ' message, sorry, it's a free program, but requires log-in, and is not MIT . . .

![Screenshot from 2021-09-05 07-59-50](https://user-images.githubusercontent.com/83387915/132117153-8ea9aba3-d111-44ac-a40a-4492423a0725.png)

It's of course just a game - engine, stuff like Mario, so on . . . But, one can also make almost AAA stuff, and can download free 3D models, almost be a 'theater' - company, or music - producer . . . 

![metahuman-creator-1](https://user-images.githubusercontent.com/83387915/132117187-aae8abe9-ee15-4946-9fa2-fc02da007587.png)

And, the commercial media just goes ahead and, sells anything . . But, is that wise, esp. for younger people, since it's a world of vanity, pretense or, manipulation, also money, power, glory and, wealth . . Sort-of hoping some people will at least think about it and, maybe be a bit critical or, maybe responsible, thx . . . .

**Comment by charlesmlamb** [comment]
Remember, how M. Jackson started, it was all fun, happy . .

![71WDeP8OUCL _SL1000_](https://user-images.githubusercontent.com/83387915/132117651-84154168-327e-4daa-86cc-36ab3fcca249.jpg)

That's sort-of the slope, Godot is sending well, kids, young adults on, with no warning in fact, almost makes it look ' normal ' or, happy . . . .

I think, that's a mistake, esp. now we know the media, seeing celebrity scandals and, we know there are some narcotics, alcoholism and, even suicide, it's rather sad . . 

That's what I think, could be improved, also be nice with a different engine, from the commercial ones, had other principles, and perhaps more concern, for the different people using it . . Thx . . !

**Comment by charlesmlamb** [comment]
After some reflection, and experience making content, from wise perspective . . .

I don't think, this is sad . . . That people making the ' commercial ' media know what they're doing or, perhaps, sadly, care . . .

Well, that's my experience, it's not that easy, to be an ' artist ', even part - time . . .

Or, so . . . <3

**Comment by DriNeo** [comment]
I suggest you to spend more time with GDScript programming, after some days your fellings could change.

**Comment by aaronfranke** [comment]
Unfortunately, abstract feelings are not actionable. Closing.
