### ISSUE TITLE
Rename `tscn` and `tres` to `scene` and `res` (prefix binary formats with `b`)

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#3255]
### Describe the project you are working on

Games that use scenes and resources.

### Describe the problem or limitation you are having in your project

When I was first learning Godot, I didn't get what `.tscn` or `.tres` stood for (**t**ext **sc**e**n**e and **t**ext **res**ource). I don't think they're the most intuitive file extensions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Because the people dealing with Godot files most often are going to be Godot developers, and Godot developers are most likely to be using text scenes and text resources during development, `tscn` and `tres` are seen quite a bit more often than `scn` and `res`. I think, for this reason, the file format that gets the prefix should be swapped. I propose:
```yaml
# Text formats:
tscn -> scene (or scn, but I prefer just using the full word)
tres -> res

# Binary formats:
scn -> b_scene (or bscene, or bscn)
res -> b_res (or bres)
```
I'm open for discussion about alternative rename ideas though.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Rename the file extensions in the code that creates and reads them. For users, this could be handled automatically by a Godot 3.0 to 4.0 project upgrader (https://github.com/godotengine/godot-proposals/issues/387).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core.

**Comment by pycbouh** [comment]
I'm not sure what this solves. Extension names are mostly inconsequential, using full generic words for them is not a good idea and underscored extensions aren't a common practice.

**Comment by LightningAA** [comment]
> I'm not sure what this solves. 

It makes it easier to understand what these files are for.

> underscored extensions aren't a common practice.

I guess, I just thought `b_scene` looked nicer than `bscene` or `bscn`. I wasn't aware of any problem with using them.

> Extension names are mostly inconsequential, using full generic words for them is not a good idea.

Possibly, we could do `gdscene` (like we did with `gdshader`), but I'm guessing people might complain that was too long? Anyways, we could just change the file extensions to `scn` and `res` for text and `bscn` and `bres` for binary, that'd still be an improvement imo, but I thought my proposed renames sounded nicer.

**Comment by pycbouh** [comment]
> It makes it easier to understand what these files are for.

I'm pretty sure we cover this in docs already, and if not, we should. Learning extensions doesn't take long, and then they don't matter as long as they are distinguishable.

I'm not against this per se. It's just very hard to prove that this is an improvement, and not just a change for change's sake. Plus, since you propose to change the meaning of the existing res extension, it may introduce confusion.

**Comment by LightningAA** [comment]
> > It makes it easier to understand what these files are for.
> 
> I'm pretty sure we cover this in docs already, and if not, we should. Learning extensions doesn't take long, and then they don't matter as long as they are distinguishable.

True, but for someone learning Godot for the first time every thing they don't have to look up is one less thing they have to remember and one less thing to feel confused about. When I first started learning Godot, I was watching YouTube tutorials, and I don't remember most of them stopping and explaining what `.tscn` or `.tres` stood for.

**Comment by Calinou** [comment]
I also think we should keep the current file extensions, as extensions that you use often should be kept short for usability reasons.

Also, extensions with underscores or dashes tend to look awkward, so I'd avoid them.

**Comment by LightningAA** [comment]
Closing due to lack of support, see above reactions.
