### ISSUE TITLE
Add drag and drop from inspector and to script

### ISSUE THREAD

**Issue by nosdregamon** [godotengine/godot-proposals#3256]
### Describe the project you are working on

I'm editing a 3d AnimationTree and once again I notice, that the properties aren't displayed as they are actually used in the script. Usually I just need to lower case a property, but with the long chains of animationTree-properties it get's a bit out of hand....

### Describe the problem or limitation you are having in your project

To use AnimationTree in the script I have to use $AnimationTree.set("parameters/idleWalkRun/blend_position", myValue), but "parameters/idleWalkRun/blend_position" is displayed as: 
Parameters 
-> Idle Walk Run 
-> Blend Position

So I either have to guess whether to use Upper/Lower-Case vs. underscore, or I have to select the property and hover over it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If I'm already hovering over the property, I would love to drag the inspector property fields into the script editor, where they are needed. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Kinda like I can drag and drop files from the FileSystem-Dock into the script and get the needed string.
Same could be useful for nearly every property.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think that's possible with a simple script/addon. But I'm not very experienced in this field.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think that's possible with a simple script/addon. But I'm not very experienced in this field.

**Comment by pycbouh** [comment]
This is already implemented by https://github.com/godotengine/godot/pull/51628 and https://github.com/godotengine/godot/pull/51629

**Comment by nosdregamon** [comment]
Thank you!
