### ISSUE TITLE
Expose `PhysicsDirectSpaceState.intersect_point()` to scripting

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot-proposals#3262]
### Describe the project you are working on

3D first person shooter

### Describe the problem or limitation you are having in your project

When using RayCast that starts and ends inside a shape, an intersection is not detected.
I need to know if the raycast starts inside an Area or not.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose `intersect_point` from `PhysicsDirectSpaceState` to GDscript.
This is already exposed in 2D

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

PhysicsDirectSpaceState.intersect_point(.....)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Will be used often, cant be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?

It already exists in engine, just needs to be exposed.

**Comment by Xrayez** [comment]
> When using RayCast that starts and ends inside a shape, an intersection is not detected.
> I need to know if the raycast starts inside an Area or not.

Perhaps could be fixed by godotengine/godot#41347.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/blob/43e96e0c652cd2ed41a1b9dfb7989ff272607a88/servers/physics_server_2d.cpp#L357-L359

This will require a bit of refactoring as no such method exists in 3D.

**Comment by 20kdc** [comment]
Bullet and GodotPhysics seem to have `intersect_point`, and the class structure involved here suggests that exposing it in the base class would do so in both.

"common code" style for `_intersect_ray`: https://github.com/godotengine/godot/blob/3.x/servers/physics_server.cpp#L252

Implementations of `intersect_point`:
https://github.com/godotengine/godot/blob/3.x/modules/bullet/space_bullet.cpp#L65
https://github.com/godotengine/godot/blob/3.x/servers/physics/space_sw.cpp#L53
