### ISSUE TITLE
Prioritize file matches in Quick Open Script / Quick Open Scene / Quick Open over folder matches

### ISSUE THREAD

**Issue by TX256** [godotengine/godot-proposals#327]
**Describe the project you are working on:**
Any project applies.

**Describe the problem or limitation you are having in your project:**
Quick Open Script, Quick Open Type and Quick Open push folder matches to the top, even if the there is a file named with the exact filename query (without extension) in the textfield.

For example let's say I have the following files/folders:
bots/alpha/alpha.tscn
bots/beta/beta.tscn
bots/bot.tscn

Now, if I type "bot" into e.g. Quick Open Scene, the topmost entry will be "bots/alpha/alpha.tscn".

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
This is a small usability improvement idea. To my mind/taste/preferences, it would make sense to modify the Quick Open algorithm in a way so that, if there is an exact match for a filename (without extension) - it is prioritized instead of a partial folder name match. At least, perhaps a preference could be added for this?

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/18146186/71318865-3b35c100-249f-11ea-95c7-08e43589d4f5.png)

**Describe implementation detail for your proposal (in code), if possible:**
I'm not familiar with Godot codebase.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not applicable.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Quick Open is a core feature already.

**Comment by KoBeWi** [comment]
Implemented in https://github.com/godotengine/godot/pull/33578, but still waits for merging.

**Comment by KoBeWi** [comment]
The PR was merged, so this can be closed:
![image](https://user-images.githubusercontent.com/2223172/80595018-55bb1080-8a24-11ea-9581-079cd2788a48.png)
