### ISSUE TITLE
Rename layers via PopupMenu/DialogBox

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot-proposals#3275]
### Describe the project you are working on

I'm currently working on a game using quite a lot different collision layers.

### Describe the problem or limitation you are having in your project

Currently, the only way to rename a layer in the editor is to open the project properties, then looking for the "layer names" category, then the good layer type and then the good layer index amongst all the layers.
The process is tedious, especially if you doesn't want to rename a lot of layer, but just decided to add one more named layer in your game.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'm proposing an enhancement to fluidize the renaming of layers, in addition to the current way : add the ability to rename a layer directly from the inspector.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Right click on a layer brings a Popmenu to rename this layer (maybe it could also be double-click instead).
Click this menu opens a ConfirmDialog with the current name, allowing to change it (layer index is shown in the title)
When confirming the rename, tooltips, name list in inspector and project properties are updated with the new layer name.

 Here is a demonstration : 

![rename_layers](https://user-images.githubusercontent.com/3649998/132918990-bbd4dfdf-46d8-4f27-933b-e1d02be4454f.gif)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As long as your game use layers (physics, 2D Render, 3D Render, Navigation, etc.) it will be used often to easily clarify the purpose of each layer. 

### Is there a reason why this should be core and not an add-on in the asset library?

I think it's a basic enhancement  which should be core. It's not a huge modification but it will facilitate quite a lot the management of layer names.

**Comment by jmb462** [comment]
If this proposal meets community interest, I could post a PR, I've already implemented this enhancement.

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:
