### ISSUE TITLE
Add a way for EditorImportPlugin to create custom AudioStreams

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#3278]
### Describe the project you are working on

FLAC importer plugin

### Describe the problem or limitation you are having in your project

No obvious way to create custom AudioStream from an EditorImporterPlugin script.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This will allow creation of plugins that add support for audio format that Godot have no built-in support of.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A class that extends AudioStream, maybe `AudioStreamPCM`, that allow you to set various properties such as bit depth, bitrate, metadata, etc. While this don't allow you to keep the benefits of compressed audio like FLAC, it will allow you to easily import other audio formats using a custom plugin so long as you know how to decode them.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know. If it is actually possible to create custom AudioStream for other file formats, someone please document this.

### Is there a reason why this should be core and not an add-on in the asset library?

If there is no proper way to create custom AudioStream then you can't make a plugin to fix this either because it would require changes to the engine.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/1190.

**Comment by atirut-w** [comment]
Huh, I think `AudioStreamSample` is what I am looking for. Closed, I guess?
