### ISSUE TITLE
Suggestion to fix the blue tint - make default sky white / light grey . . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3279]
### Describe the project you are working on

A 2.5D game, with barbarians, lore . . .

### Describe the problem or limitation you are having in your project

Default environment is still bit weird, ONE solution is this . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Now, in Godot 4.0 dev, also Godot 3.3 the blue tint is still there, and looks quite odd . . I've been looking at it, and one way of fixing it, is to make default sky look like this . . .

![Skærmbillede (2164)](https://user-images.githubusercontent.com/83387915/132945494-9c0881c3-5c8b-44bf-9029-e2927ef58e9e.png)

Or, darker ground . . .

![Skærmbillede (2165)](https://user-images.githubusercontent.com/83387915/132945500-ed2e4f53-b02f-4369-9140-b6a3feb6cd09.png)

Compare to before . . .

![Skærmbillede (2163)](https://user-images.githubusercontent.com/83387915/132945509-64780075-dcc1-4956-9d9a-900677220318.png)

Now, if Godot is going for a PBR look, it doesn't match, bec. one can go outside, and see almost clear white, so the default environment makes no sense, esp. for beginners, and it's annoying to change the default settings, so they look realistic, or esp. for stylized projects . . . 

My suggestion is, since many engines have a sort of empty, or ' black ' environment, where there are no lights, or an empty stage, this sort-of makes sense, sort-of everything is turned off, fastest environment for work, if you want to add a sky, look for the settings, or make it what you need . . . It'd be clear, this is not best sky, and most users would know, I need to look for sky settings, to make it blue, etc etc . . .

I also think it is appealing, simple, or so . . .

So, my proposal is, fix the default sky color, in Godot 3.3, perhaps 4.0, so that it is white, it gives advantage, with no light source, normal maps don't appear, with a sky contribution, I sort-of think they work, and one gets a simple, fast, and useful environment for both realistic work, and stylized projects . . .

Also, Godot 4.0 still has a weird blue tint, that one wonders, where does 'real' world look, like this, it's like it fails to be either a PBR default environment, and also stylized . . A SIMPLE, fast option, is to make default sky white, then devs will know, ohh this is sort-of start up environment, I need to set it, somewhere . . And, it'd be fast, look clean, and make sense, for an empty project, do whatever you want and, everybody well wins . . .

Godot 4 . . .

It looks pale, and a bit bluish, it could be fixed with a pure-white sky, and then when one makes a environment preview, it'd be more easy to set it there, and people might see, things get bit blue, when sky bec. blue, instead of white . . . 

![Skærmbillede (2168)](https://user-images.githubusercontent.com/83387915/132945978-0646bcca-b82c-49a9-a017-8fff20522abd.png)

I think having a black-white, or light-grey-black background, makes sense, for an empty project, and last I think the weird fog, in Godot 4, compared to Godot 3.3, it's a bit weird, since it's like fog is set to ' on ', when one hasn't wanted to, it makes well less sense, than just a clean, empty project, see above <3

So, tbh, Godot 4, 3.3, has gotten AMAZING upgrades and, bug fixes, I'm like, everything is a ton better, these things still are bit weird, and esp. new users will wonder, why does an empty project look like this . . It's also weird, that in 3D, if no camera, and one press play, it's like a blank screen, so one thinks, to fit that, maybe makes sense to also make default environment, like a blank 3D scene, no lights, no effects, nothing, it runs fast, and would be a nice starting project, and look quite stylish, esp. if environment preview allowed one to create a more full-featured sky, well easily <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, it's an idea, to make Godot more user - friendly, cool and, simplistic, ' reliable ' . . . :)) . . . !

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, it's just an idea, hoping someone could think about it and, find SOME solution, right now the engine looks unappealing, and it takes a long time, for new users esp., to find out what's wrong, it's a bit pointless, and a black-white, or light-grey to black def. environment would look good, serve all users, realistic, or stylized, and make engine bit easier, to use, or so . . . Thx ! ! . . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it's an idea, I think Unreal has a blank template, or start, where it's just a dark screen, no lights, one can't see 3D models, it's sort-of ultimate blank, it's quite neat, and makes sense, also, for beginners . . . . See above, thx . . . .

**Comment by pycbouh** [comment]
We already have a proposal for the environment changes, and it's one of the most liked proposals we have: https://github.com/godotengine/godot-proposals/issues/348
