### ISSUE TITLE
Rename AudioStreamRandomPitch to AudioStreamRandomizer and add more randomization options

### ISSUE THREAD

**Issue by ellenhp** [godotengine/godot-proposals#3281]
### Describe the project you are working on

Modernizing Godot audio.

### Describe the problem or limitation you are having in your project

AudioStreamRandomPitch does a good job of avoiding the "crunch" associated with playing back a bunch of identical sounds at the same time, but in order to make things sound good in a scenario like that you really need to be using *different* sounds, and it's also sometimes good to vary the volume on playback. I've needed to do both of these for a game I built a while back, and I think it's a very commonly implemented feature for polished games in Godot, so I'd like to bring it into core.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'd like to rename AudioStreamRandomPitch to AudioStreamRandomizer and change its `audio_stream` property to an `audio_streams` property to allow users to set up a pool of audio streams. Every time a playback is instanced from the randomizer stream, it will pick a random stream from this pool to use for playback.

I'd also like to add the ability to randomize volume, probably using the same pattern as the `random_pitch` property. Maybe call it `random_volume`?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The only part that really needs an explanation IMO is the volume. This is what I'd plan on doing to calculate the volume. It basically just mirrors the random pitch code.

```
float range_from = 1.0 / randomizer_stream->random_volume;
float range_to = randomizer_stream->random_volume;
volume_scale = range_from + Math::randf() * (range_to - range_from);
final_volume_db = Math::linear2db(volume_scale * Math::db2linear(volume_db));
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it can be worked around, but a *lot* of Godot games end up doing this, and we already mostly solve this problem with the AudioStreamRandomPitch, I just want to take it a step further for 4.0.

### Is there a reason why this should be core and not an add-on in the asset library?

AudioStreamRandomPitch is in core.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/52592.
