### ISSUE TITLE
Consider adding some simple font - packs to make UX improved / find some cool ones . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3282]
### Describe the project you are working on

A barbarian game, 3D . . . .

### Describe the problem or limitation you are having in your project

I've been looking into, using fonts to improve UX, idea is, maybe have some different font well themes, fonts don't take up that much space, ex . . .

Most are, 200 - 300 kb . .

Idea is, find some free, or MIT fonts, and make some different themes, using fonts . . . Atm, I use these, to make Godot more friendly, or simple . . .

<img width="959" alt="Skærmbillede (2189)" src="https://user-images.githubusercontent.com/83387915/132952398-869e32aa-a3da-4633-999b-a505b99f329c.png">

And . . . .

<img width="538" alt="Skærmbillede (2188)" src="https://user-images.githubusercontent.com/83387915/132952416-465a6ecb-af18-498e-ad89-30d6f236afc7.png">

Now, adding fonts is a silly idea, suggestion is, to look at different fonts, and see if any actually improve UX, in some way . . And, if there are some, add them so one, can pick certain well styles, sort-of like font - themes . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Ok, so it's not about adding some fonts, rather first look into, can one find fonts that actually improve the UX, and if that's possible, add them, maybe so each theme, has some fonts, or some, of them . . . If there's no improvement to UX, it makes no sense, I think it can make a big different and, be a small improvement, not sure . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, first look at different fonts, test a bunch, Google fonts, MIT . . .

If there are some that well significantly improve UX, why not add them, and either set them with a few themes, or add some different font themes or, so . . .

Again, if there isn't any good stuff, no reason to add it . .

Also, zip - compression makes them from 240, to 160 kb, so on . . 

Maybe that's the last straw, that will push Godot into excellent, or awe - inspiring, not sure . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, if there are some UX - improving fonts, makes no sense the average user has, to look for them . . Having some, that really improve general UX, might make sense, since well Godot 4, it's nit - picking, what to add . . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, not sure, maybe someone could look for it, and find some good ones, MIT . . !

Idea is to, do the work for the Godot - community and, have some excellent, or actually UX - improving fonts, to take it to, well 102 % or, so . . !

**Comment by charlesmlamb** [comment]
It might be possible to make an almost calm or, ' serene ' feeling, to the UX <3

Or, something semi - noble or, simple, honest . . .

It'd take some work, find MIT versions of MS fonts, there are some nice ideas or, so . . .

And, it might make Godot from cool to, kick - ass, would take some research, find good ones . . . .

**Comment by charlesmlamb** [comment]
Last, I use a nice courier font, for debugging, wish it was possible to increase size, or so . . .

<img width="764" alt="Skærmbillede (2192)" src="https://user-images.githubusercontent.com/83387915/132952834-e46f2eaa-08b4-4026-aee8-2e6980331e93.png">

Thinking, an emacs based style . . . !

**Comment by Calinou** [comment]
There are no plans to ship Godot with more fonts, as this would increase its binary size significantly. Font choices in editors are mostly about personal preference, so it's up to the user to find a custom font they like.

**Comment by Calinou** [comment]
Closing per the above comment.
