### ISSUE TITLE
Rename `Listener2D`/`Listener3D` nodes to `AudioListener2D`/`AudioListener3D`

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-proposals#3299]
### Describe the project you are working on

Game with positional audio.

### Describe the problem or limitation you are having in your project

When attempting to add/create nodes through the Editor, it is not intuitively clear that the `Listener2D`/`Listener3D` nodes are related to Audio.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename `Listener2D`/`Listener3D` nodes to `AudioListener2D`/`AudioListener3D`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The idea is that by just searching for "Audio" within the "Create New Node" dialog from the Editor (Ctrl-A), all the audio related nodes appear on the Node types tree.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by registering new types that extend `Listener2D`/`Listener3D`, but don't do anything else. In the end, this just clutters the UI.

### Is there a reason why this should be core and not an add-on in the asset library?

It's impossible to rename built-in nodes with GDScript alone.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/52751.
