### ISSUE TITLE
Add an angle difference function to the core math

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot-proposals#330]
**Describe the project you are working on:**
I am working on a puzzle game involving rotation which uses similar mechanics to rubiks cubes and combination locks. 

**Describe the problem or limitation you are having in your project:**
I have concentric circles which I need to tell if they are rotationally aligned. Since they have the same center I cant use Vector2.angle_to_point() unless I do Vector2.angle_to(Vector2(cos(angle), sin(angle))) but that seems excessive considering the angle_to_point function is probably using an angle difference function within it.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

I wrote a code which has the same effect with much less work which would be placed in the math core

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

Cant on my phone which is the only thing with internet right now please forgive my inability to use tab

**Describe implementation detail for your proposal (in code), if possible:**

```gdscript
# returns a value from -PI to PI
func angle_dif(from : float, to : float):
    var ans = fposmod(to - from, TAU)
    if ans > PI:
        ans -= TAU
   return ans
```
Here is the same thing in degrees if that is what they need: 

```gdscript
# returns a value from -180 to 180
func angle_dif_degree(from : float, to : float):
    var ans = fposmod(to - from, 360)
    if ans > 180:
        ans -= 360
   return ans
```

Here are corresponding angular interpolation functions 

```gdscript
func aint(from: float, to: float, weight: float)
    return from + angle_dif(from, to) * weight
```

```gdscript
func aint_degree(from: float, to: float, weight: float)
    return from + angle_dif_degree(from, to) * weight
```
*If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It will be used often and while it can be overcome by script the script they might come up with might not be as elegant as the solution I found. 

**Is there a reason why this should be core and not an add-on in the asset library?:**

because its usage would be pretty ubiquitous and it seems odd that angle_to_point is included but angle_dif is not.

**Comment by DleanJeans** [comment]
Isn't this what [Vector2.angle_to()](https://docs.godotengine.org/en/3.1/classes/class_vector2.html#class-vector2-method-angle-to) does?

```
print(Vector2.UP.angle_to(Vector2.DOWN)) # 3.141593
```

**Comment by lukostello** [comment]
> Isn't this what [Vector2.angle_to()](https://docs.godotengine.org/en/3.1/classes/class_vector2.html#class-vector2-method-angle-to) does?
> 
> ```
> print(Vector2.UP.angle_to(Vector2.DOWN)) # 3.141593
> ```

No that takes 2 Vector2s as inputs this takes one angle and another.

**Comment by Xrayez** [comment]
> Here are corresponding angular interpolation functions

`lerp_angle` is added in 3.2: godotengine/godot#30693, someone could take this as a base to implement angle difference method.
