### ISSUE TITLE
Add a command line argument to start the GDScript language server without starting the editor

### ISSUE THREAD

**Issue by AstroStucky** [godotengine/godot-proposals#3300]
### Describe the project you are working on

A 2D space game. It's irrelevant to this proposal.

### Describe the problem or limitation you are having in your project

I use Sublime Text 4 as an external text editor for GDScript. I've configured it to use Godot's GDScript language server using [Sublime's LSP package](https://github.com/sublimelsp/LSP). Since the language server only runs when the Godot editor is running, I must always keep the engine editor running in the background while writing GDScript; even when I don't need it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Ideally there would be a command-line flag added to the `godot` command that only launches Godot's language server. If the language server requires other processes in Godot to run, then those must be launched too.

**Example:**
```godot --language-server```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I could see two approaches for implementing the `--language-server` argument.

1. The language server editor plugin is launched with all the supporting infrastructure that an editor plugin requires to run. However, I worry that would be impossible or messy at best to run the editor plugin infrastructure separately from the rest of Godot.
2. Instead, I propose a more light-weight solution, which is to instance `GDScriptLangaugeProtocol` in a new server class of its own that's implemented to use as little Godot infrastructure as possible.

I wanted to list both in case my concern about pursuing **Option 1** are unfounded. I would like to discuss which approach is best in the comments.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Any work-around will depend on the LSP client being used. In my case, using Sublime Text's LSP package, I found two work-arounds, but neither of them are ideal. 

1. Configure your LSP client to launch Godot's editor itself, which means your text editor instance is always tied to your engine editor instance. 
**Why this is insufficient.** The engine editor must always be running while writing GDScript, even if you don't need it. On low-end machines in particular this is a problem. And if you have to restart your text editor, your engine will restart too.
2. Configure your LSP client to launch nothing, and always run the engine editor alongside your text editor. 
**Why this is insufficient.** Your engine editor must always be running while writing GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

I do not believe editor flags can be added as an add-on. 

Since this proposal tries to use as little of Godot as possible outside the GDScript language server, this could even be implemented as a stand-alone executable, but I think more external text editor users will benefit from it were it a flag argument implemented in the engine core instead.

**Comment by Calinou** [comment]
Would running a headless editor binary work? In Godot 4.0, it's no longer a separate binary and is toggled with the `--headless` command line argument instead.

**Comment by AstroStucky** [comment]
I did not know there were separate headless and server binaries. I wasn't sure what made more sense so I downloaded both linux_headless and linux_server to compare their performance against my own locally compiled desktop binary. All versions are 3.3.2 cause that's what I'm working in.
![Screenshot from 2021-09-17 14-17-21](https://user-images.githubusercontent.com/17039973/133848938-d5c2a0cd-f00a-4210-82df-9ee1568be676.png)
This performance is acceptable. I'm now having my LSP client run the headless version alongside Sublime Text. The language server works great this way! And I'm given the added benefit of having other server functionality available at my fingertips whether I have a Godot editor instance open or not.

Thanks @Calinou!

**Comment by tshrpl** [comment]
sorry for the irrelevant question ...
@AstroStucky how did you setup Sublime Text 4 lsp to work with Godot ? can you perhaps make a guide or at least point me to the right direction

**Comment by AstroStucky** [comment]
> sorry for the irrelevant question ... @AstroStucky how did you setup Sublime Text 4 lsp to work with Godot ? can you perhaps make a guide or at least point me to the right direction i was unable to find any relevant information

Not irrelevant at all. Happy to leave my configuration here for others that might need it. I am running on Ubuntu 20.04, so I can't know for sure if this will work on Windows. I pieced together my solution from [the LSP guide here](https://lsp.sublimetext.io/language_servers/), but they don't provide a guide for GDScript specifically.

Here's what my `LSP.sublime-settings` file looks like, which can be accessed from `Preferences > Package Settings > LSP > Settings`.

```JSON
{
    "clients": 
    {
        "gdscript-ls":
        {
            "enabled": true,
            "command": [
                "~/dev/godot/server/Godot_v3.3.2-stable_linux_headless.64",
                "-e",
                "--quiet"
            ],
            "selector": "source.gdscript",
            "tcp_port": 6008
        }
    }
}
```
You may want to add the `--no-window` flag if you're not using the headless or server binaries. I suspect your problem with your first attempt was that you needed the `-e` flag, which opens the editor instead of the launcher

**Comment by abitrolly** [comment]
Is the problem solved by `--no-window`?

**Comment by AstroStucky** [comment]
> Is the problem solved by `--no-window`?

Yes, but you'll have better performance running the headless or server binaries, which don't require the `--no-window` command.

**Comment by abitrolly** [comment]
So 4.0 already got `--headless` argument according to comments above. And 3.x has separate headless binaries. Does that solve the problem?

**Comment by AstroStucky** [comment]
I think it does.
