### ISSUE TITLE
Add a Skew property to StyleBoxFlat

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#3301]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Creating nice-looking "futuristic" UIs with StyleBoxFlat is quite limited.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

With a Skew property, it's possible to achieve skewed styleboxes without relying on textures. No custom shaders are required either, and you don't need to create multiple nodes (e.g. one for the Label, one for the Button).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The property should work like Node2D's Skew in the `master` branch. Positive values shift the StyleBoxFlat's upper portion towards the right, whereas negative values shift the StyleBoxFlat's upper portion towards the left.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around with a clever property setup, which is not obvious:

![image](https://user-images.githubusercontent.com/180032/133512022-bfeae390-2d5d-4480-b467-925b71e550c4.png)

This property setup also requires creating a different StyleBoxFlat resource per height desired. This can be inconvenient when you have multiple skewed StyleBoxes, each with their own height.

The question about how often it will be used remains though. I believe it will be used relatively often in futuristic-looking UIs. Many popular AAA games such as Overwatch and Doom Eternal feature skewed styleboxes, but this is not something that fits within all games' art style. Nonetheless, I think having the option makes sense.

### Is there a reason why this should be core and not an add-on in the asset library?

StyleBoxFlat is core functionality and can't be modified by a plugin.

**Comment by akien-mga** [comment]
Discussed in proposal review meeting, the feature doesn't seem *extremely* needed but the implementation is fairly simple and it can be useful for prototyping and to keep sharp vector StyleBoxFlat styles, so seems good.
