### ISSUE TITLE
Use `noexcept` modifier where it's possible to improve engine performance

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-proposals#3302]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

No, it just can improve the engine performance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`noexcept` is a C++ 11 feature (https://en.cppreference.com/w/cpp/language/noexcept) that can significantly increase the code performance due to enabling compile optimization by omitting the internal exception checking. Since Godot already does not have any exception handling by telling the compiler to not check it internally I think the result will be significantly better.

See also a discussion about it: https://stackoverflow.com/questions/10787766/when-should-i-really-use-noexcept

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

By adding `noexcept` definition to all function declarations/definitions, constructors and operators (excluding third-party code of course). Probably that should perform automatically using some tool.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It's a core thing by default

**Comment by Calinou** [comment]
As with any code change that relies on compiler specifics, make sure to benchmark the performance difference in real world scenarios to see if it's actually worth doing :slightly_smiling_face:

**Comment by Chaosus** [comment]
> As with any code change that relies on compiler specifics, make sure to benchmark the performance difference in real world scenarios to see if it's actually worth doing 🙂

Yeah, I'm just too lazy and don't know how to do it myself.

**Comment by KoBeWi** [comment]
According to the discussion you linked, the compiler can deduce if it should handle exceptions or not, and since we never use them, most likely Godot is already optimized on this regard.

Also adding `noexcept` to every single function is kind of meh. I wonder if there is a global compiler flag for that.

**Comment by Artromskiy** [comment]
> I wonder if there is a global compiler flag for that.

-fno-exceptions can be used.
