### ISSUE TITLE
Godot 4 current dev does not remember viewport settings on re-boot . . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3303]
### Describe the project you are working on

A barbarian game, 2.5D . . . .

### Describe the problem or limitation you are having in your project

Atm, after restarting Godot 4 dev, the editor layout / settings are forgotten, it's normally not big problem, but since it crashes at times, it's a tad annoying to re-set it every time, and reconfigure the windows, also doesn't remember the debugger, etc . . . It means, every time there's crash, have to spend like 20 seconds, just getting it back . . . It's not a major problem atm, more when people start testing it, it bec. a serious problem, for well UX . . .

Was hoping you would look into this, and see if something might be done, atm. re-starting the Godot 4 build, is a major pain, esp. with the many random crashes, that's all . . . I guess it's something to look into, before an alpha, atm. guess few users are trying dev version . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, for some reason the dev - version, well it forgets the layout, and one has to go into menus, and reset even debugger, to look like last time, here . . .

Boot . . . .

![Skærmbillede (2229)](https://user-images.githubusercontent.com/83387915/133591498-ce124c7d-bbd8-43d4-8624-f051f3af45e2.png)

Then, setting it again, takes 10 - 20 seconds, on 4K monitor, clicking the ' editor settings ', it's a bit tough, to see, and one tends to make errors, etc . . . .

![Skærmbillede (2230)](https://user-images.githubusercontent.com/83387915/133591618-4bb48227-52db-4153-8f74-6acd2185017e.png)

It's just an annoyance, since one re-starts all the time, and there are new crashes, when trying a new version, today the textures didn't work, in default material, well really happy about Godot 4 dev, looks to be an over-all almost leap forward, in UX, features, quality, more . . . 

So, 10 / 10 . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, for some reason engine doesn't remember the dock stuff, and one has to re-set it every time . . . Here's how small the little menu is, on my computer screen, 4K . . . .

![Skærmbillede (2231)](https://user-images.githubusercontent.com/83387915/133591970-1114868d-bb47-4976-9ab7-4f220a54c71b.png)

Going into those menus, it's some small stuff, and I tend to click wrong, or have to be super - careful . . . .

Well, amazing job, thanks . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, just wonder why this happens, at least when alpha is finally ready, this will finally work . . .

:DD :DD Thx . . .

### Is there a reason why this should be core and not an add-on in the asset library?

I think, it might be in core code, not really sure, pro - stuff, difficult to say, for a noob <3

**Comment by SIsilicon** [comment]
Wouldn't this more suit a bug report rather than a feature request? It sounds like it shouldn't happen.

**Comment by pycbouh** [comment]
Indeed, if there is a problem with one of the Godot versions, it should be filed as a bug report on the main repo, not as a proposal.

**Comment by charlesmlamb** [comment]
Oh yea . . I just uhh wait for Godot 4 alpha, I think you hopefully fix it by then, it's just bit annoying when Godot 4 dev crashes, happens sometimes, also to re-start a project, thanks . . .

**Comment by SIsilicon** [comment]
You should still check Godot issues if this has been reported and if not, file a bug report. You'd be helping the Devs and others that know how to code that way.

**Comment by charlesmlamb** [comment]
Well, it makes sense, it's sort-of rather obvious, think it will be fixed before the alpha, or soon after alpha . . !

Right now, it's a bit annoying, guess I'll wait 1 - 2 months, see what happens, sadly current dev is rather unstable, there are new bugs, that weren't there a few weeks ago, today textures didn't load, for albedo, some bug, crash . . . Well, I'll just wait, when get alpha, prob. some others might mention it, atm. not sure if alpha is 2 - 3 months away, well, thanks for all the amazing work, Godot 4 has stuff I really wanted, better UX, just over-all I'm 10 / 10, for what has been done so, now I'm just trying to relax, and like everybody else, well wait . . . .
