### ISSUE TITLE
Add some way to search for all functions, methods, or properties in visual script . . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3304]
### Describe the project you are working on

A barbarian title . . .

### Describe the problem or limitation you are having in your project

I've been thinking, in view of Visual script being much better, maybe one might add a search setting, sort-of like normal, and advanced settings, like in the improved project settings . . .

Right now, many methods, are not in default search, or so . . . Not sure if this is possible, but make a toggle, or so . . . So, one can search for all methods, properties, and not sure, set up all boxes, example . . .

Normally set_fps doesn't appear, maybe an advanced search, so one could easily find a property or, method . . . The search could just give you a string, that explains " Singleton(performance --> set_fps ", so one would have a small clue, how to do this, or place nodes, perhaps correctly set in order, I think with massive improvements to UX, more . . . It might be possible to add this feature, that's all . . . . 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, add a toggle, to have advanced search, so one might search all the methods in the entire engine, also properties, and get bit aid, or so . . . Well, auto - completion, or so . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When right-clicking in Visual script, one gets a list, and it tends to have a bunch of options, one would not think, would be in a basic list, perhaps add a advanced search, that finds more methods, well not sure . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I can't code the engine, at all . . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, not sure, and it might be a bad idea, maybe someone can find something else, have some ideas, that's all . . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
