### ISSUE TITLE
Add per channel customization when importing a texture

### ISSUE THREAD

**Issue by thenegativehunter2** [godotengine/godot-proposals#3306]
### Describe the project you are working on

a game that requires proper texture import to maximize performance.

### Describe the problem or limitation you are having in your project

i am not very experienced with texture import and possible optimizations, but i know it's very hard to decide to which import settings to use. and hard to debug to make sure if they are working correctly.
you could make a great game, and end up getting bad results due to bad import settings which don't look so obvious.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Texture import pipeline is too complicated. and seems to contain conflicting settings.
If we could just set(as a summary) :

- a swizzle along with a optional invert and a optional SRG conversion for every color channel in the source image.
- final used channel count (1, 2, 3, 4), and if we want to use a compression format which allows RGB channels to leak into each other or not.
- combine up to 4 images as source.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

it would require a complete rework of the texture import pipeline. that can be avoided by just making an additional texture importer. setting it it's name to "manual texture" or smth.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

not any that i know of.

### Is there a reason why this should be core and not an add-on in the asset library?

it's basic texture import.

**Comment by pycbouh** [comment]
To be honest, this doesn't read like simplification of the workflow. Current settings can always be overwhelming, but they are what people mostly use when importing textures. Per channel customizations make sense when you create a texture, not when you import it. Do you have an example of a relevant application that uses such flow?

This can be implemented as a plugin, by the way, if desired.

And if you have trouble making textures, there are powerful tools available. [Material Maker](https://www.materialmaker.org/) for example.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/2107.
