### ISSUE TITLE
Consider adding support for particle chains, deformable clouds . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3308]
### Describe the project you are working on

A barbarian game . . .

### Describe the problem or limitation you are having in your project

Well, saw this neat demo, where they used particle chains, to make in their case tentacles . . .

![Animation (17)](https://user-images.githubusercontent.com/83387915/133735906-b9c452c5-db03-4327-947b-d180d29be3f7.gif)

Now, I've been having this idea for a while, was thinking it might be nice to add something, like that, didn't know how to well formuate it, or so . . .

Also, one could make something like particle clouds, that were deformable, so they formed a matrix, and add say a texture2D, to each one, to get sort-of 'blubbery' clouds, with some physics simulation . . .

<img width="902" alt="2021-09-17 0840" src="https://user-images.githubusercontent.com/83387915/133736458-8694fd9f-e572-4e5c-b96e-1a40179c3547.png">

Or, one could make particle sheets, or, even columns . . . The results look pretty good, close to, Bloodborne stuff, might give some nice options, for devs . . . .

Anyway, had the idea some time ago, that it might be faster . . . .

<img width="480" alt="Skærmbillede (2235)" src="https://user-images.githubusercontent.com/83387915/133737029-96411ba2-5f3a-4173-9d72-a54e94494553.png">

![Animation (19)](https://user-images.githubusercontent.com/83387915/133737057-1a3163e1-b469-40da-8063-eeb14a7f2560.gif)

Anyway, been thinking, why not make sheets, or perhaps line, where the particles move down the line, as it animates, or sheets, where particles travel, on matrix - like sheets . . . I'm thinking, it could make stuff like electricity, etc . . And, plan was it'd run on GPUparticles, or if needed CPUparticles, make some nice effect . . . . Thx . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, like above, make some simple particle systems, with limited interaction, run it on GPU, and make some rather cool stuff, been thinking about it for months, well that's the idea, thx . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like examples above, to add that, make it customizable, add sheet, column, cylinder, line, and cloud support . . . Then, one could set properties of each one, and make them different . . .

Link, to full demo, 7 minutes . .

>> https://www.youtube.com/watch?v=tYibUTZIdig

Well, been thinking about it for a while, also make sheets, or grids, where particles travel on paths, to make some crazy particle stuff, that's it . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't code this, hoping for a simple gizmo system, where one can add particles, in some default configurations, sheet, line, cylinder, and cloud, then add say textures to each particle or, some mesh . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it looks like say Bloodborne, PS4 launch game, had some of this, had it on my mind, for a few months, it might be a neat way, of animating stuff, in a limited, 'physics' way . . . .

Also, to set it up, might be nice to have some say graph edit, to make it quite custom or, so . . . ! !

**Comment by Calinou** [comment]
This was already implemented in the `master` branch by https://github.com/godotengine/godot/pull/48242.
