### ISSUE TITLE
Add a built-in way to load theme resources as editor theme

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#3310]
### Describe the project you are working on

Nothing in particular.

### Describe the problem or limitation you are having in your project

(none)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I just thought it'd be a nice idea to be able to completely customize the look of Godot's editor and not just a few stuff provided in the settings. This could allow more in-depth customizations such as [custom fonts](https://cdn.discordapp.com/attachments/212250894228652034/851401847192682537/unknown.png), or even [revamping the look of the editor](https://cdn.discordapp.com/attachments/218361207990648832/851419023761735700/unknown.png).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This can already be done from an `EditorPlugin` script by getting the editor's interface(`get_editor_interface()`) and from the editor's interface, getting the base control of the editor(`get_base_control()` and setting the base control's theme. Althought this kind of works, it is very hacky, can cause visual glitches, and require doing it all over again when loading a new theme.

If this is to be implemented into Godot's editor, there have to be a few requirements, such as that when the theme is unset, the editor should reset to the built-in theme.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

(Can't find the old script I used to do this, but it can be implemented as explained above)

### Is there a reason why this should be core and not an add-on in the asset library?

As I said, while it can be done from an `EditorPlugin` script, it is hacky and can sometimes cause visual glitches.

**Comment by Calinou** [comment]
I don't understand the difference between this proposal and the custom theme editor setting that's already available.

**Comment by atirut-w** [comment]
The one that's already available only allow customizing basic stuff like
colors, etc. but not custom styles

**Comment by pycbouh** [comment]
No, you can have a fully custom theme if you want:

![image](https://user-images.githubusercontent.com/11782833/133762344-3446afd0-1e06-413a-a7f5-1593df8b841e.png)

So closing, as this feature already exists.

**Comment by atirut-w** [comment]
I don't remember this field using a theme resource... Huh...

**Comment by pycbouh** [comment]
Well, that's what it is for.

![image](https://user-images.githubusercontent.com/11782833/133762851-8d05586d-d8d3-4d76-9115-35438f06ea3f.png)


As for *3.3.3* it requires you to provide a full theme resource for the editor. You can create a copy of the current editor theme and edit it using the old theme editor.

Starting *3.4* you can have a partial theme resource, i.e. a resource that only overrides the necessary stuff on top of the base editor theme. And you can also create as granular copy as you want from the editor theme using the new theme editor.

**Comment by atirut-w** [comment]
That's cool. It's unfortunate that the field doesn't seem to be documented,
though.

**Comment by pycbouh** [comment]
I don’t think editor settings are documented in general at the moment?

**Comment by atirut-w** [comment]
Sad

**Comment by Calinou** [comment]
> I don’t think editor settings are documented in general at the moment?

See https://github.com/godotengine/godot-proposals/issues/1339 and its implementation https://github.com/godotengine/godot/pull/48548.

**Comment by atirut-w** [comment]
> As of **3.3.3** it requires you to provide a full theme resource for the editor. You can create a copy of the current editor theme and edit it using the old theme editor.

Something to note, 3.3.3 seem to crash if I try to use a partial theme resource.

**Comment by Calinou** [comment]
> Something to note, 3.3.3 seem to crash if I try to use a partial theme resource.

See https://github.com/godotengine/godot/issues/35462.
