### ISSUE TITLE
Suggestion for a plug - in / feature (?!) that helps writing video - games (specifically) . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3312]
### Describe the project you are working on

A barbarian 2.5D project . . .

### Describe the problem or limitation you are having in your project

First of all, this is clearly a plug - in suggestion, or perhaps a program that runs like MaterialMaker, not sure where else to ask, or so . . .

I been working on making my ideas, lore into stories, and that's somewhat complex, for video - games, for instance unlike a book, one can't really say what happens, in a linear way, word for word . . .

I sort-of think, for games one must write levels, instead, or 'zones' . . . And, to do that I need a 3D editor, where one can make prototypes, add text, like this . . .

<img width="765" alt="2021-09-17 1054" src="https://user-images.githubusercontent.com/83387915/133754666-30cac7a2-56a5-4e62-a2c0-d3d684a05c02.png">

With a bit, of 3D, rotate around z ( y ) + bit of rotation, or so . . .

It's bec. a sort-of problem, to find stuff that can do this, and it's bec. writing video - games is complex, one can't decide where the player is, at any time, or make some linear cut - scenes . . .

The second thing, I've been working on a simple, hard - core writing program, that allows one to write stories, in well like this . . . Again, this is obviously plug - in stuff, or sort-of a writing suite, spec. for making games, projects . . . .

<img width="1229" alt="Skærmbillede (2242)" src="https://user-images.githubusercontent.com/83387915/133755663-daa30130-a192-4607-ab6e-f3c956b38bb3.png">

After some thinking, or reflection . . I think this is the ' best ', but not only way to write for video - games, take the process from idea, to 'something' . . . Then, after making an overview, of basic story, one starts adding concept art, for certain story - moments or, events, and one slowly, carefully goes from idea, to something more ' early design / work ' . . .

The big problem is, atm. one doesn't have such a tool, so one might make a plug - in, if someone wants a rock - solid, simple writing method, or so . . . Not an expert, think most good stories are linear, from A to B, to Z . . . One might make branching stuff, if one wanted, it's sort-of individual . . .

The last thing is, have some sort of VERY simple text editor, where one could edit strings, atm. the user - interface means, one has to store text in variables, and it's quite annoying, to sort-of edit them . . . So, a simple string - editor, perhaps like a text editor, atm. in visual script, one can't see the text, or so . . . A simple, clean black-and-white editor, where each string is written, over text, dialogue, and one can use them, in code, or so . . Sort-of make an incredible writing suite, that allows one to go from idea, inspiration, to something concrete, and one can stop at any time, if one feels, it's not solid yet . . .

So, suggestion is, for a plug - in ! ! That one makes a program, spec. made for writing video - games, and make it more easy to write lore, stories, so on . . . . The problem is such a program doesn't exist, and ideally it'd work, so one could make a prototype, export as .glTF, and have that as ' floorplan ', for a project . . . This is obviously a plug -in or, perhaps a program, that might run in Godot, similar MaterialMaker, the ' best ', most solid writing ' system ', for video - games . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, after giving it some thought, current writing tools aren't made, for video - games, bec. one can't decide, at ONE time, like a book, where player is, what's going on, so well it's not possible to write a book, or ' normal ' script, one can at best give an overview of what happens, in a level, or area . . .

Also, for visual script editing esp. strings, is quite difficult, one could write the text in a comment, then move it to a string, then again, that doesn't work . . .

It'd sort-of be an almost ideal way, of going from some ideas, towards a story, one small, logical step at a time, and one can at any time decide, no story isn't ready, focus on that, characters need work, until the story is done, solid . . . Then, one can add a concept art example, see how that goes, and slowly build up a project, over time, making sure it's ' solid ' or, real, or so, depends on each person, or writer . . .

Thanks . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like above, can't code this, have been looking for it, classic writing tools well fall short, of video - game writing, so not sure if there are some contributors, that might want to make the ideal, ' best ' writing plug - in, for video - games, projects . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, don't know where to ask, this place is only place I know coders, spec. coders that might make a plug - in, that's be the ' best ' writing - suite, spec. for video - games, or so . . . It's more if somebody liked writing, or felt it was tough, to go from idea, to something one could sequentially, ordered work on, or so . . .

### Is there a reason why this should be core and not an add-on in the asset library?

I can never answer this question, but I'd say this is plug - in, or some program, that runs in Godot, a simple text editor, one can set normal, bold, italic, or so . . . Only example I know is ' WordPad ' . . Sort of, like a blank type-writer page or, so . . . .

Well, I find it difficult to slowly, surely go from idea, towards a linear, or perhaps competent story, right now there are no 100 % optimal, as I personally see it, writing tools, was thinking it could be a cool plug - in, for Godot, to help people go from idea, to finished project, in a linear, ordered way, thanks . . . . :) . . !

**Comment by charlesmlamb** [comment]
Here's the problem, for using visual script to edit text, or large amounts of lore, story . . . .

<img width="719" alt="Skærmbillede (2244)" src="https://user-images.githubusercontent.com/83387915/133760485-30ae61c9-864a-4e54-bfc5-6e6a55ca5aa3.png">

You can't see the text, in the actual nodes, and you have to edit, in that one line, for a 1000 word string, you have to move to that point, not sure it's easier in GDScript . . .

Also, finally learned how Godot written code work, thanks to visual script, and can prob. just make it in written, for visual script users the text editing, also reading is really difficult, hence suggestion to make a text editor, where one can write strings, well on a simple page, and then call them, in code or, so thanks . . .

Hope you would at least look at this, gonna move to written code, visual script was the training feature, I needed to understand, how to write, so thanks . . . . !

**Comment by charlesmlamb** [comment]
Problem is, in a book, you know reader will read in a A - B way . . . You can decide, what happens, also in a movie, you set up some scenes, it's linear . . . In a video - game, esp. more open levels, you don't know what's gonna happen, so the normal writing tools sort-of fail, for video - games . . .

You could write, what happens in room 1, room 2, room 3, like a script, but again don't know if player will go into room 1, 2, or 3 first . . . You're left with the option, as I find it, to make a basic 3D overview, of a level, with interactables, or so . . And, one can write a very rough overview, player enters at spawn location, has to find a key, open door, go, to the exit . . . The problem is there isn't a 100 % made, for video - games, writing tool, one that allows one to slowly, carefully go from idea, being able to always go back to working on story, characters, etc . . . That plug - in, or program might be made in Godot, as a nice, 'ideal' writing tool, since afaik it has not been made, but it's more a plug - in tool, esp. since writing video - games is complex, and well quite difficult, having a program that in simplest, most ' clean ' way helps one get from ' cool ' idea or, concept, to a finished game, with option to ' drop out ' at any time, and not make more, than what feels right, is a missing program, imo thanks . . . .

**Comment by charlesmlamb** [comment]
Here's my problem, I tend to have some amazing idea, and want to make content, stories . . . The program, image above with the arrows, allow me to see, may have a cool starting idea, and some cool final boss, but there's stuff missing, in the middle, all the stuff, between . . . It gives a clear overview, well of where story, plot is weak, and one can slowly work, at that level, simply as ideas, until the story is ready, or neat . . . Then, when one has a good story, might take two years, or more, to make that, one is confident in the story, one begins adding a few concept drawings, I have a tablet, with a pen, and add those . . . So, one sort-of slowly goes from idea, to finished project, have the tools needed, to at any point say, no story isn't good enough, then focus on that . . . It's well a minimum investment, and when one finally has a story, one would like to tell, one can build levels, etc . . . .

It's just a tool, optimized for making video - games, going from nice, or a cool idea, to a finished perhaps AAA project, depending on what one has, and one can add to the different levels, over years, getting story right, making sure there's a good, linear progression, to the last act, or segment . . . .

That tool is missing, classic tools fail, bec. of complex nature of games, etc . . . 

Then, as one gets new ideas, improvements, one can add more arrows, until one has a story, one likes . . . Then, one ' writes ' the project, by making over-view levels, with interactables, sounds, effects, that's what is possible, I suppose . . . And, one can add notes, or so . . .

Idea is one goes from overview arrow tool, to making levels, slowly, and adding concept art, or perhaps recordings of voice, to the 3D level editor, and at any one time, one can drop the project, or leave . . . Then, go back to having ideas, and building something solid, or respectable, etc . . . 

Atm, that tool is missing, it'd run well as something like, Materialmaker, and might be integrated a bit with Godot, so written text can bec. strings, and it's easy to move from basic writing, to making lore, story or, characters . . . It's just an idea, to make a super - cool, reliable writing tool, for video - games, esp. Godot, suppose when it's done might be ' best ' writing suite, in the world, and it might even be used, in say the industry, not really sure . . . Like LibreOffice writer, spec. for video - games, or complex story - telling, content, thanks . . . . .

**Comment by charlesmlamb** [comment]
So, after years of trying to write stories, from neat idea, to something like, AA . . I've found that, the most ' excellent ', one could say Godot way of writing stories, is linear, to about the story, message, tell one thing, then move to next point, or lore - element or, story . . . Many current AA - AAA projects use branching, or so stories, and that's fine, it's just my experience, alone, after well meditation, that the best, most ' upright ' stories are linear or, perhaps best told that way . . . That also means, one can make an ideal writing program, where one slowly, at minimum investment, goes from good, solid idea, over time, slowly, to something worth even publishing, and at any time, one can review it, or, improve it . . .

Guess many other people haven't thought about it, but people with very logical, simple thinking, ' clear ', will tend, to make linear stories, with a direct or, to-the-point plot, little or, no deviation . . . So, one can sort-of make a tool, for the best writers, the one's with good stories and, decent content, that helps them, in the simplest way, build their stories, lore, or characters, and when it makes sense or, has well soul, or so . . . Then one begins making the actual 3D stuff, starting from simple concept art, constantly being aware, until the story or, 'message' is cool, or well worthy, doesn't make sense, to make stuff, it's sort-of an ultimate writing tool, about minimal investment, and not moving to prototype or, early production, bef. one has a solid, 'real' reason, to make stuff, or so thanks . . . .

Again, this is my experience, after years of trying to make stuff, sort-of how to build it up, in minimal investment, so one can avoid 'vain' or, corrupt projects, and only take next step, when one is confident, in the essential ' worth ' or, character of the project, in a way, this is the 'ultimate' way to write video - games, content thanks . . . Give it some thought, don't 'believe' what you see, esp. in big media, you'll prob. find, this is the best way, for logical, 'clear', linear or, ordered thinkers, that's all . . . .

I'm thinking, it might be a nice plug - in, or program, running in Godot, esp. if it allowed one to move writing, to Godot, maybe as strings, not sure, sort of have the writing, in ONE place, and if needed, could sort-of send, to the engine, like a Blender .glTF export, thanks . . .

Bunch of mistakes, and 'bad' information going around, about the way to do it, not sure why, after some years, trying to do this, this is the best way, linear stories, clear plots, for logical thinkers, or ' minds ' . . . :)) . .

Well, Godot also relies on the content, to grow bigger, as it were, ' hit ' games, projects . . . And, this tool would be, something like a writing program, LibreOffice Writer, but made for video - games, and indirectly help the engine, sort-of second-hand or, so . . .

And, it'd be the rock - solid writing program, I THINK best one ever made, esp. nice if it was free or, ran on donations, thanks . . . !

**Comment by charlesmlamb** [comment]
Sorry, here's the point, making a game with many side - quests, that are optional, one runs into risk, of player not getting full story or, the entire 'point' or, meaning of the game . . . That's why linear stories, with few branches are the best way of maybe communicating, or ' reaching ' people, bec. the content maker knows exactly, what the player will hear, etc . . . .

And, for a simple, clear thinker, one wants to stay on one topic, get that done, and so move on, to next point, or what the ' theme ' or, content of the project is . . . That's the reason, linear games are best for telling stories, or content, one knows the player had seen, heard everything he's supposed to, at the end and, there's no bull - shit or, drama, just the core content, message, or point, hence the above is prob. best way of writing stuff, for competent, well - rounded writers, thanks . . .

**Comment by Calinou** [comment]
> First of all, this is clearly a plug - in suggestion, or perhaps a program that runs like MaterialMaker, not sure where else to ask, or so . . .

This repository isn't meant to be used for plugin ideas. The third-party [godot-ideas](https://github.com/godot-extended-libraries/godot-ideas) is more suited for this purpose.

**Comment by Calinou** [comment]
Closing due to lack of support (see lack of reactions on OP and general lack of activity here).
