### ISSUE TITLE
Allow to ignore await coroutines

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#3315]
### Describe the project you are working on

A game using GDScript that I'm going to eventually port to Godot 4.0.

### Describe the problem or limitation you are having in your project

While fixing the scripts, I noticed lots of instances of "function is a coroutine so you need to await it blah blah". I understand it was introduced, because the await no longer returns a function state, so you need to wait if you want a return value. But I don't care about return value. I just call the method and want to continue, I don't care if the method pauses midway or whatever. This was possible with yield, because it returned a function state that I just didn't use.

This can be worked around with `call_deferred()`, but it's not ideal, because there's a frame delay, which sometimes might be problematic.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If a function is a coroutine, but returns void, allow to skip `await` for that function. When this happens, the function call would be paused, but the parent function would continue. Just like the old yield, but without returning function state.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```GDScript
func my_func():
    print("Hello")
    await some_signal
    print("world")

func other_func():
    my_func()
    print("something something")
    some_signal.emit()
```
Result:
```
Hello
something something
world
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As I mentioned, you can technically use `call_deferred()`, but there are some cases when you want the part before `await` to be executed immediately and can't wait.

### Is there a reason why this should be core and not an add-on in the asset library?

GDScript is core.

**Comment by vnen** [comment]
This is actually a bug: godotengine/godot#48830

If you're not using the return value it should not ask for `await`.

**Comment by KoBeWi** [comment]
Oh...
