### ISSUE TITLE
Allow mouse button to be detected in the "Listen for input" tab of Input Map Editor.

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot-proposals#3318]
### Describe the project you are working on

A puzzle game using mouse button actions.

### Describe the problem or limitation you are having in your project

In godot 4.0, mouse buttons cannot be detected automaticaly in the "Listen for Input" tab when adding a new trigger for an action.

Mouse buttons need to be selected in the list in the "Manual Selection Tab"

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose the (re) enable the ability to detect mouse buttons automaticaly.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

To prevent mouse buttons to interfer with tab and buttons clicks, I propose to add a "dectection zone" for mouse button.
The buttons will be detected only is mouse is over this area.

Here is what it looks like in my current implementation : 

![image](https://user-images.githubusercontent.com/3649998/133924862-de830660-d91b-44d3-9a79-1d047644db2f.png)
![mb_detection](https://user-images.githubusercontent.com/3649998/133924871-a2a7d76c-0bfa-486f-9bd5-4b08bd7f8aaf.gif)

I could post a PR if this proposal meets interest.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be often use. Each time someone need to add a mouse button action (included mouse wheel)

### Is there a reason why this should be core and not an add-on in the asset library?

InputMap Editor is an base editor feature.

**Comment by EricEzaM** [comment]
When I implemented there _was_  a reason I disabled the auto-detection from the mouse, but I don't remember what the reason was now. I will take another look, because I agree it is a bit annoying that this is not supported.

**Comment by jmb462** [comment]
Without limiting detection to a specific area, mouse buttons are detected even when we click on UI elements like tabs and buttons.
I assumed that it what for that reason. Seems to look good with the area trick.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/52868.
