### ISSUE TITLE
Text Statement Nodes For Visual Script

### ISSUE THREAD

**Issue by SomeDumName** [godotengine/godot-proposals#3319]
### Describe the project you are working on

I have several ideas, but currently I am working on nothing. 

### Describe the problem or limitation you are having in your project

The Visual Script editor, though simple to think about and look at, is time consuming to use. This is because of how slow adding nodes is.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The Text Statement node, can be  added with `(insert_shortcut)` shortcut. If possible one can also combine an existing set of nodes into Text Statements with the same key. 
``` plural or singular depending on the implementation```
A Text Statement node can split into appropriate visual script nodes via a press of `(insert_key)`.
The inputs for this kind of node, limit the statement's accessible variables to the inputted variables.
This node outputs the effected variable of the statement if any.
Splitting the text statement should be preferred if possible.
This is useful for creating several nodes at once, and for calling class specific functions.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/91026837/133940452-b0750290-8e3b-42f7-92d4-e96a568e58d2.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I doubt it, If someone can prove the possibility go ahead.

### Is there a reason why this should be core and not an add-on in the asset library?

The Text Statement node is a useful TimeSaving tool. It improves the flow of the Visual Script editor, and should be available to all developers when they use the editor.

**Comment by Calinou** [comment]
Have you seen the VisualScriptExpression node?

**Comment by SomeDumName** [comment]
Didn't see it, It was buried in the menu, Can I call functions with it or Split it into other nodes? I'll close this anyway.
