### ISSUE TITLE
Control `mouse_filter` mode that behaves like `Ignore` when mouse input is not accepted

### ISSUE THREAD

**Issue by fire540** [godotengine/godot-proposals#3320]
### Describe the project you are working on

A 2D treehouse tycoon/building game

### Describe the problem or limitation you are having in your project

I am trying to make a Control node that covers the whole screen and that only accepts right-click input and ignores left-click input. "Stop" does not allow left-click input to propagate to nodes below the Control, and "Ignore" does not allow the Control to accept any input.

Why I need this is because I am making a camera that can be dragged with right click, and there are also rooms that can be selected with left click. 

I am looking for an in-between of these two `mouse_filter` types: one that acts like Stop if the input is accepted (using `Control.accept_event()`) and acts like Ignore if the input is not accepted, allowing the input to pass to nodes that are beneath it in the rendering order. 

The "Pass" `mouse_filter` mode will not work for this case, as it has two caveats (both of which are noted in the documentation): 
1. `_unhandled_input()` does not fire on other nodes, even if the input isn't handled using `Control.accept_event()`
2. Input propagates up after any Control nodes with `mouse_filter` set to Pass are encountered, which is the opposite of how Ignore propagates down.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A new `mouse_filter` type will be created. What the difference between this new type and the existing ones is that it allows for input to continue downwards if the input isn't accepted.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the Control node's `_gui_input` method, if the input event is accepted using `Control.accept_event()`, the input will be stopped similar to the Stop `mouse_filter`. If the input is not accepted, then it can be passed to other nodes similar to the Ignore `mouse_filter`. 

```gdscript
func _gui_input(event: InputEvent) -> void:
	if should_accept_input_event:
		accept_event() # Input is stopped and doesn't go to any other nodes
	else:
		pass # Input can go to other nodes as if this node's mouse_filter was set to Ignore
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but the method to do this is not ideal. Right now, if you want input to continue downward, you have to set the Control node's `visible` to `false` so that it won't be registered when the event is run again, run the same input event again using `Input.propagate_event()`, wait one frame for the input event to have run, then set the Control node's `visible` back to `true` so it can take input again.

Here is an example using left and right click:
```gdscript
func _gui_input(event: InputEvent) -> void:
	if event is InputEventMouseButton:
		match event.button_index:
			BUTTON_RIGHT:
				accept_event()
				# Do stuff
			BUTTON_LEFT:
				visible = false
				Input.parse_input_event(event)
				yield(get_tree(), "idle_frame")
				visible = true
```

### Is there a reason why this should be core and not an add-on in the asset library?

This would add a new `mouse_filter` type to Control, which can't be done by an add-on, and this has to do with the Control node and input event systems which are built-in.

**Comment by KoBeWi** [comment]
> Why I need this is because I am making a camera that can be dragged with right click, and there are also rooms that can be selected with left click.

Why would you need a fullscren Control for that? If your rooms don't handle the right-click, the `_unhandled_input()` in your root should be able to receive it. (or it's vice-versa)

**Comment by fire540** [comment]
I didn't know the root had `_unhandled_input()`. I should have thought that through better before making a proposal. That's my mistake. I'm going to close this issue now.
