### ISSUE TITLE
Consider adding support for OpenGL ES 3.0 volumetric lights ( see demo ) . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3321]
### Describe the project you are working on

A barbarian title . . .

### Describe the problem or limitation you are having in your project

My problem is, I want say God rays, but at same time SDFGI seems excessive, maybe only want it in say a corridor, or a few places, etc . . . I have no idea if this is dumb, saw a 2 minute video, of OpenGL ES 3.0 volumetric light, already getting volumetric fog, tbc. I DON'T understand what this does, it looks like sort-of turning GI on, for ONE light, I was thinking maybe one could make a performant way, of adding GI here, and there, or so . . . Don't want to use GI, unless it's super - necessary, bec. it can make stuff run slow, etc . . .

<img width="960" alt="Skærmbillede (2258)" src="https://user-images.githubusercontent.com/83387915/133956397-c5dc9e2b-fed1-40e6-9c32-6608b417b31a.png">

<img width="960" alt="Skærmbillede (2256)" src="https://user-images.githubusercontent.com/83387915/133956405-c847de6d-00f0-4dd7-b628-b1cb85a4afbf.png">

Just to be 100 % clear, I don't know what this is, it just looks like sort-of ' local ' sdfgi . . Was thinking that might be quite cool, since I don't need entire scene to be sdfgi, just a few places, where I'd like perhaps god rays, well, it looks nice, in the demo, here's link . . . .

>> https://www.youtube.com/watch?v=IONAMsLpahg

I guess what I'm asking for, is there any way we can get SDFGI, that is sort of local, or for one light source, so it runs really fast, for making a few windows, instead of something running, for entire scene, that's all . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, an option to add local GI, maybe for one light source, or, say a room / area . . Something faster, than normal sdfgi . . . :OO . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, saw this amazing demo, not sure what it is, it looks nice, like local GI, very cool . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I can't code this, on my own . . . .

I don't know, reason I wanted to ask, is because there's already volumetric fog, not sure, well seems logical to add volumetric light, though I don't know what it is, really would like some local, really fast GI, say for a window, or corridor ( Half-life 2, Resident Evil 5, on PS3 ) . . . .

### Is there a reason why this should be core and not an add-on in the asset library?

I have no idea, if one could add fast, performant GI, to a single light source or, area, that'd be amazing and, prob. run on slower hard-ware, demo looks like they have made GI, well, not sure how it's working . . . I don't need full sdfgi, except for AAA titles, be nice with a faster, more optimized system, for making god rays, in a very local space, with neat results, demo makes it look possible, don't understand the tech, behind it, atm . . . :OO . .

**Comment by charlesmlamb** [comment]
What I'm asking for is maybe not volumetric light, more like, some way to have GI, from one light source or, in a very limited area, and avoid using sdfgi that makes my frame - rate drop, rather a bit, atm . . . . Maybe there's a way to include that, using a limited sdfgi or, not sure . . . . :OO

**Comment by charlesmlamb** [comment]
I'm not an expert, I heard Godot 4 will at some time have OpenGL ES 3.0, this might be dumb, could one bake stuff like GI, I mean god rays, fog, or so . . Guess I'm asking for a more optimized, efficient, local GI system, that would work in OpenGL ES 3.0, if that's possible, something PBR - based or, so . . . So, guess asking for limited, local GI, in OpenGL ES 3.0, something that runs fast on any computer or, to bake PBR god rays, or so . . . The demo just makes it look, well easy . . . Is there a neat way, of doing this, well that'd be nice, esp. for beginners, or so . . . .

**Comment by Calinou** [comment]
There are no plans to add high-end features to the upcoming OpenGL renderer, as all hardware that is fast enough to render volumetric fog supports Vulkan.

> Well, an option to add local GI, maybe for one light source, or, say a room / area . . Something faster, than normal sdfgi . . . :OO . .

It's already available in Godot 3.x and `master` – it's called ReflectionProbe :slightly_smiling_face:

**Comment by charlesmlamb** [comment]
REFLECTION probe, only seen GI probe at GDQuest . . !

I read docs, asap . . . !

**Comment by Calinou** [comment]
Closing, as this feature is already provided by an add-on for Godot 3.x: https://github.com/SIsilicon/Godot-Volumetrics-Plugin

Godot 4.0 has built-in support for volumetric fog and fog volumes, but it can't be backported to `3.x` as it relies heavily on compute shaders.
