### ISSUE TITLE
Logging(`print`, `push_warning`, etc.) should also tell what script or what object it came from and when

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#3323]
### Describe the project you are working on

(None)

### Describe the problem or limitation you are having in your project

(None)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

One feature that I kind of miss after moving from Unity to Godot is that when logging things, Unity takes note of which script(and which object IIRC) the log came from and when. I can see this being pretty useful for debugging.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This would probably require changing a lot about how the output logging in Godot works. For example, `print`, `push_warning`, and `push_error`, instead of just putting things into the output, will create a sort of log object that contains message, time, etc. and send it to something that manages output.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

How do you even change how the print function globally works from a script?

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by Calinou** [comment]
Try using `print_debug()` or `print_stack()`, it should give you a stack trace.
