### ISSUE TITLE
Change GDScript's naming conventions from snake_case to PascalCase

### ISSUE THREAD

**Issue by NoorWachid** [godotengine/godot-proposals#3327]
### Describe the project you are working on

A game with a lot of mix scripts

### Describe the problem or limitation you are having in your project

It's NOT hard to keep tab from back and forth from C# convention to GDScripts convention, BUT it would be nice if we only have one convention like \*cough\* Unity \*cough\*

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Remap all functions

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
func _Process(deltaTime):
    transform.SetPosition(Input.GetGlobalMousePosition())
    
   finalDirection = Math.Atan(transform.position.y, transform.position.x)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's easy solved if I don't use GDScripts, but I believe if you came from Unity it would be nice to have GDScripts but with Unity convention because it will attract much more audience. Because GDScripts is easier and swifter to write.

### Is there a reason why this should be core and not an add-on in the asset library?

It's impossible to change core functions with add-on.

**Comment by Calinou** [comment]
I don't think changing GDScript's naming convention is a good idea. It'll break pretty much every tutorial and code sample you can find online. (Not even Godot 4.0's API renames and GDScript syntax changes will break as much code.)

**Comment by atirut-w** [comment]
Eh, it's a pain to rename all those functions and not break compatibility. You could alias the old names to new names and have Godot tell you the old names are deprecated, but why use PascalCase on a language that's more similar to Python?

**Comment by Xrayez** [comment]
Unfortunately, this is one of those things which you kind of have to accept even if you don't like it. I personally wish we could get rid of text-based programming at some really far future... 😃

I rarely if ever use C#, therefore `snake_case` looks quite natural to me, especially when I've been programming in C++ prior to picking up GDScript/Python.

**Comment by Calinou** [comment]
Closing due to lack of support (see the above comments and reactions on OP).
