### ISSUE TITLE
Allow exporting typed enums

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#3330]
### Describe the project you are working on

Space Ship game

### Describe the problem or limitation you are having in your project

Godot doesn't allow exporting enums statically

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow us to export typed enums.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
enum MyEnum {
  A,
  B
}

export var enumA :  MyEnum
export var enumB := MyEnum.A
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Idk its just nice to not have to export enums with..
```
export(MyEnum) var enum
```
or for 4.0
```
@export_enum var enum
```

### Is there a reason why this should be core and not an add-on in the asset library?

Its better on the eyes.

**Comment by Calinou** [comment]
cc @vnen

**Comment by KoBeWi** [comment]
Already possible in 4.0
except you can't do `export var enumB := MyEnum.A`, but I assume it's a bug
