### ISSUE TITLE
Expose WebRTC's ICE gathering state

### ISSUE THREAD

**Issue by thenegativehunter2** [godotengine/godot-proposals#3334]
### Describe the project you are working on

a project that is supposed to use webrtc

### Describe the problem or limitation you are having in your project

i have no way to know the webrtc ICE gathering state.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

webrtc's ICE gathering state must be exposed in WebRTCPeerConnection.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

i think it's called `IceGatheringState` in both native version (native build of webrtc) and javascript version.
i don't know the cross platform implications of bringing this value from the native version. there is probably an enum involved. i don't know if it will be the same for different platforms.

after exposing `IceGatheringState` to `WebRTCPeerConnection`, then `WebRTCPeerConnection` must expose this value to gdscript.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
i am no expert on this matter by any means but what i found out is :
not in a reliable OR a good way. but it's possible to 
1. wait a second or two and assume the ICE candidates have been fully gathered. 
2. send the gathered ICE candidates to the remote peer. hope the remote peer can connect. 
3. if the remote peer fails and ICE candidates count has changed so far, retry again with the new collection. 

### Is there a reason why this should be core and not an add-on in the asset library?

it's the only sane way to use webrtc.

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
This was implemented in master via https://github.com/godotengine/godot/pull/65659 .
