### ISSUE TITLE
UX improvements to graph edit in 3.3 / 3.4 . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3337]
### Describe the project you are working on

A barbarian game, 2.5D . . .

### Describe the problem or limitation you are having in your project

Well, one of things I like a ton, about Godot 4 is, the more muted colors, in graph edit, sort-of more calm, or ' serene ', reflected . . I know those UX improvements, that I find to be amazing, are for Godot 4, I wanted to ask, since Godot 3.4 might be the engine I use for the next several years, until Godot 4 is stable, if spec. we could get one thing, a more muted color scheme, something nice . . .

Reason is, it's quite saturated, I understand the UX changes for Godot 4, are well for the 4.x version <3, a leap forward, but tbh. looking at the mile-stone bar, it has moved 1 %, in like six months, from 78 %, to 81 % in that time . . . Normally don't mind waiting, but at that pace, looks like we'll have Godot 4 stable, in 2 - 3 years . . .

Here's problem, it's super - saturated, 'colorful' . . . .

![Skærmbillede (2265)](https://user-images.githubusercontent.com/83387915/134447622-b3188b3b-8971-4faf-a994-72319b6cf0fe.png)

I'm just hoping some of the UX improvements for graph edits, could bec. part, of Godot 3.3, or so, bec. the wait for Godot 4, looks like it'll take years, not sure . . . What I am hoping for, is a less saturated, and colorful look, it doesn't have to be same as Godot 4, I think you know what I mean, something a bit less ' saturated ' or, well not-sure 'intense' . . . It'd be a nice compromise, until we get Godot 4, since atm. it looks, sadly like it may be 2 years, based on mile-stone bar . . . That's sort of why I'm asking for this, otherwise it'd not be so important, also I really like OpenGL ES 3.0, and I might want to make my games in Godot 3.4, for quite some time, until Godot 4 gets OpenGL ES 3.0, though I like Vulkan, also, OpenGL has an ' old-school ', retro look, so super - happy with Godot 3.3, or 3.4 . . And, I just hope you'll sort-of port SOME, not all of the UX improvements to Godot 3.x, mostly bec. the wait for Godot 4, is sort-of agony <3 . . ! Thx . . :OO

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, sort of just hoping for a setting, maybe in 3 - 4 steps, to set saturation of the graph edit headers, to get a some-what more modest look, or 'calm' . . . Given how cool Godot 3.x is, I think it might benefit from these improvements, until Godot 4 is stable, and ready for actual projects, it'd be nice to work on stuff, in Godot 3.x series, with bit more comfort, UX - or so . . .

The things I'd like, not all are remotely possible . . .

1. Set saturation of graph edit headers, from 0 - 100 % . .
2. Ability to customize, or set color of graph node headers, similar to how one can set perhaps written code editor
3. The ability to set opacity of boxes, to sort-of hide certain boxes, so sort-of . . .

One can select some nodes, as a group, and set opacity, for a node, from 25 - 100 %, to sort-of fade certain boxes, or selections of boxes . . .

4. The option to select certain boxes, and hard-set the color, of the headers, this would help make graph edits more easy to read, long - term . . .

I think these are the features I need, from a UX perspective . . Given the wait for Godot 4 stable might be 1 - 2 years, I think makes sense, to add SOME of major improvements from Godot 4, to Godot 3.x, not all of them, but some . . Thx . . . !

And, those are all my wishes, understand prob. not even 50 %, are really possible, wanted to have all requests, to give an overview, of ' best ' case, that's all . . . !

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, there are several suggestions here, being able to over-ride a given box, and set a new color, would make it easier to read scripts, that's a new thing, and, also being able to set the opacity of a box, it'd help scripts be more readable . . :OO 

The no. 1 thing I need, is just a less saturated look, more ' greyish ', or not-so-colorful, I find it is distracting, and well, guess for me, I'd have a more stable, or modest experience, hope you'll look at this, and find a compromise, where Godot 4 gets the big, visual over-haul but, Godot 3.x gets some love, mostly over the entirely tragic wait <3, for Godot 4 :DD :DD Thx . . ! !

It's bec. of wait for Godot 4, looks like perhaps 2 years, until stable, or so . . . I think it makes sense, to add some of stuff, to Godot 3.x thx . . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I can't do this, it's not in the theme editor either, graph edit isn't fully customizable atm, at least when I try, I can work with comments, and that's about it, also haven't been able to make it work yet, don't know what texture a stylebox needs, end up having a bunch, of crashes, atm . . . Thx . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, Godot 4 is getting some amazing updates, the suggestion is, add SOME of those in a modest way, to Godot 3.x, so we have SOMETHING, until the wait is over, thx . . . !

**Comment by charlesmlamb** [comment]
Just, really looking forward to Godot 4, have watched some videos of OpenGL 4.3, for instance Doom (2016), so I think there's a nice engine, for making maybe AA stuff, until Godot 4 is ready, plan is to switch to Godot 4, when it's closer to a stable version, also want to see new sdfgi, until then super - excited about Godot 3.x, I think it's a good engine, and if it got some updates, to improve UX, it would help the wait and, allow Godot 4 to take maybe bit longer, no rush, etc . . .

I'm somewhat surprised Godot 3.x is so cool, plan is to use that, so many amazing titles made in OpenGL 4.3 + . . So, I think I might want to move bit more slowly, to Godot 4, since there's prob. back-ward compatibility stuff, anyway just thanks for this amazing software, hope you can do something for the 3.x stuff, since I have plans to use that, until ready to move to Godot 4, I'd imagine many other users, might feel the same <3 <3 10 / 10, superb . . . !

**Comment by charlesmlamb** [comment]
I found some examples, there are no good images, but being able to set it to stuff like this, so it looks more like well engineering software, it's sort-of more practical or, to the point . . . . These are just for well inspiration, I'd like a less visual, more ' logical ' look, so it's bit more friendly, or so . . . I think this would perhaps greatly improve UX for graph edit, at least, if there were some customization options, I think you'll see it's an improvement, when it's done, sort-of something for every-body, thx . . . !

Again, these were best images I could find :(( . . .

![2021-09-23 0900](https://user-images.githubusercontent.com/83387915/134466363-3dd30e51-387d-4f7d-9127-3ca6a06559c7.png)

![2021-09-23 0859](https://user-images.githubusercontent.com/83387915/134466372-a73384c5-17c0-469c-b266-185a638bc730.png)

![2021-09-23 0902](https://user-images.githubusercontent.com/83387915/134466399-bfcd4f1b-e180-402a-8106-f7e77be6b88f.jpg)

![2021-09-23 0901](https://user-images.githubusercontent.com/83387915/134466415-7adf2020-d281-4be1-ba26-878888ffd78d.jpg)

**Comment by charlesmlamb** [comment]
So, the new UX in Godot 4 dev, are sort-of better . . .

<img width="960" alt="Skærmbillede (2180)" src="https://user-images.githubusercontent.com/83387915/134761814-6e089354-9123-403e-b676-7910c2f4e65b.png">

I guess I'm hoping for two things, also for earlier 3.x bec., I'm gonna be using that for a while, perhaps next 1 - 2 years or, so . . . For me, the best case is, if one could set how black-white it is, to make it more mute, or sort-of calm, and also the color tone, these settings . . .

![Animation (26)](https://user-images.githubusercontent.com/83387915/134761919-d01d02d0-548a-405b-8058-ecbcebd3042e.gif)

I think I would prefer, an almost grey interface, with bit of difference, in the well headers . . . .

<img width="1920" alt="2021-09-25 0854" src="https://user-images.githubusercontent.com/83387915/134762042-d578b7d8-2714-4b4d-9e5d-ca57d3a32c22.png">

It's not for everybody, don't really need well fancy colors, to know what I'm coding <3

Goal is, to make it more modest, less ' bright ', esp. since I have monitor, with HDR, don't want to turn it off when, I start Godot every time . . .

It'd just to a slider, to lower contrast + grey-scale, I think many users would perhaps benefit from that, again, not sure this is best, if this is not changed, don't have much choice, to get decent UX, move to Godot 4, and wait until there's a stable release, well to make stuff <3 Thanks, I think it's a nicer interface, that fits my well engineering background, well bit better . . . <3

**Comment by fire** [comment]
Similar to https://github.com/godotengine/godot-proposals/issues/3225 issue.

**Comment by Calinou** [comment]
Closing due to lack of support (see lack of reactions on OP and general lack of activity).
