### ISSUE TITLE
Ability to open a scene that is stored in an export(PackedScene) field from the inspector

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot-proposals#3338]
### Describe the project you are working on

RPG with items.

### Describe the problem or limitation you are having in your project

I'm currently storing game item scenes in a database scene, that is generated via a custom plugin, so I can have an overview of all the items. They are saved via export(PackedScene) in nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be handy if there was a possibility to open the scene stored in export(PackedScene) field from the inspector. Currently you can only load in a new scene there, edit (which does not open), clear, make unique and save. There is also show in filesystem, from where you can open the scene, which is an ok workaround, but not ideal.

![image](https://user-images.githubusercontent.com/7307968/134503016-0cd0f3bd-1c93-43ee-8b15-fa2c53cc3aa5.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just an Open entry in the context menu would be fine.

Additional double clicking to open would also amazing, but currently activates editing like that:

![image](https://user-images.githubusercontent.com/7307968/134503389-9d1d0719-ced2-448e-ae60-c6afe5226e79.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Core.

### Is there a reason why this should be core and not an add-on in the asset library?

It's the inspector.

**Comment by pycbouh** [comment]
> It's the inspector.

Yes, and we have inspector plugin API. It's very much possible to create a small plugin that adds an open scene button for PackedScenes.

That said, I am not opposed to having it in the core.
