### ISSUE TITLE
Add ability to export levels in different, sequential files, to allow for faster download for bigger titles . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3339]
### Describe the project you are working on

A barbarian 2.5D title <3 . .

### Describe the problem or limitation you are having in your project

Uhh, I was thinking, with increasing file size, also since I prob. will publish my games in a sequential manner, if it was possible to make it so, that one could download, after export, level1-2.exe, then level3-4.exe, level5-6.exe, and have an option, after one game has played, level 1-2, that it auto-runs next file, sort-of just a feature, where one can set after closing down, that it opens another .exe, in same folder . . . I think say Playstation, has a new feature, sort-of one starts downloading, but can play level 1-2, after 10 minutes, rest of stuff downloads, while one is playing level 1 - 2 . . Having this feature would allow one to sort-of publish a bigger game, in a sequential fashion, that's what I'm looking for, also to minimize download size, or allow for background downloading of later content, in a big, maybe 10 - 20 gb project . . . This would give Godot support for much larger projects, it'd just be nice if it all just worked . . .

Another way would be to export level3-4 in a .pak, that the first level1-2.exe, could access, with pure data in it, so the engine can store levels, or scenes, in 2 - 3 .pak, that run in order . . It's just a nice feature, and allows for faster download, and this way it might be perhaps easy to implement, idea is to allow for faster download time, esp. for bigger projects, and also to publish games, maybe every 2 - 3 months, sort-of nice for indie publishers, that want to publish stuff early . . .

It's just an idea, to get that nice ' play faster ', from the newer consoles, where downloads can be 50 - 60 GB, also for slower internet connections, to allow people to play faster, then as one plays level 1-2, level 3-4 downloads in background, reason is it might actually be very simple to implement, quite easy with just 3 - 4 .exe, but not sure one can write as one closes a running, exported projected, that it should move to a new .exe, also it'd require a restart, though it would work really well, being able to store levels in several, sequential .pak, level1-2.exe, then level3-4.pak, then level5-6.pak, and it runs with no restart, of the engine executable, would effectively give a cheap, anybody could use high-end feature, from consoles, and help make Godot more attractive, for bigger projects, it's just a weird idea, since it's so easy to well make, wanted to ask, it'd also work well for indie projects, where one wants to publish in a more sequential manner, then every 2 months, on just uploads a new .pak, and the game gets bigger, it'd require Godot to read from more than, one .pak, anyway saw new consoles have this, and it's a QoL feature, might be easy to add it to Godot, this way . . . :OO . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, like above, so one can boost download times, esp. for bigger titles, and improve user experience, for people that play titles, made in Godot, esp. bigger titles . . . :) . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, an option to split the different scenes, that are each level, into several .pak, or at least a way to run an executable, in the same folder, as one Godot project closes, after exporting <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know, it'd be nice if it just worked, and be another small step, towards Godot being AAA - ready . . :OO 

### Is there a reason why this should be core and not an add-on in the asset library?

Again, it's always tough to answer this, don't know, it's a simple idea, mostly to increase download times, and allow for easier publishing, of serial games, ie. you just release a new .pak, and boom, there are well more levels . . . !

**Comment by charlesmlamb** [comment]
Some benefits, over the current console stuff . . . Atm. one can download 10 - 20 minutes of play, but has to wait until full 50 - 60 gb has downloaded, this feature would be better than consoles, I suppose . . .

One could simply do it, by having say level1.pak, level2.pak, level3.pak, and then write after ' change_current_scene ', an extra line  of code, so change_current_scene(level2.pak), it might be easy, to code this . . . Then, an 'advanced settings' when exporting, to store certain .tscn in different .pak, and perhaps auto-name them, 1.pak, 2.pak, 3.pak or, so . . .

It'd be a simple thing to add, and would make Godot ready for big projects, and I suppose be better than what they had, I think had this on PS4, or PS5, where it doesn't really work, it's esp. possible because engine is so small, and the first 1.pak, could be optimized to be small, say 200 mb, then next level could be 400 mb, then 1.2 gb, to give well, something like this . . . <3 . . .

**Comment by charlesmlamb** [comment]
The problem is you'd need a downloader, that allowed one to download the .pak in order, that could just be manually done on the web-page, or not sure, some download program, one could link to, that gets content, in a set ordered, level1.pak, then level2.pak <3

Well, it's just an idea, a small step towards making Godot, if needed, ready for AAA content, at least on PC, Linux, Mac, Android . . .

**Comment by pycbouh** [comment]
> if it was possible to make it so, that one could download, after export, level1-2.exe, then level3-4.exe, level5-6.exe

That's not how such a system works. It's not multiple executables and autoplay. It's content streaming. And Godot already supports content streaming, you can export your game into several PCK files and load them as needed. There is nothing out of the box that would do the splitting for you, so you have to configure it yourself, but the system itself is already present.
