### ISSUE TITLE
Move render settings to project settings

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot-proposals#335]
**Describe the project you are working on:**
Any
**Describe the problem or limitation you are having in your project:**
Render settings is hardcoded:
- use_rgba_3d_shadows
- depth_buffer_internalformat
..... and others

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
how i found Godot have problems with this settings and not all property define support/not support. see [issues - 34530](https://github.com/godotengine/godot/issues/34530) and many others.
If move this settings to project settings, then you can make avoid this, and on my side i can made graphical settings if user have a problem, or write test which told me what support.
[pull - 34473](https://github.com/godotengine/godot/pull/34473) - and avoid this (need just change settings in project settings)

In you side no cost move this to project settings.

in best case need write graphical test (app start and self testing)- not allways opengl get error and not allways this opengl feature/extention property used by GPU/drivers (remember i have a bugs in old games (2000-2010) in Nvidia Titan (funny... it be... a shadows)).

P.S. in my case i force use_rgba_3d_shadows, but i dont know where main problem - in shadow atlas or when glBlitFramebuffer (it cant blit color with depth or msaa or internal format mismatch), or ...

**Comment by clayjohn** [comment]
Im not sure this would be useful. These settings are set based on what gl_extensions are available. If your hardware doesn't meet the minimum spec then it won't work regardless of the setting. 

Right now Godot handles this automatically so users don't need to understand OpenGL, if we make it a project setting then users will have to understand OpenGL in order to appropriately set the settings.

**Comment by SuperDIMMaX** [comment]
how i say - force use_rgba_3d_shadows - help me.

> users don't need to understand OpenGL

Yes, end user dont care about this, this is our problems. (developers)
Or if you say "users" - who develop on Godot, then how about shader language, if need property shader, you need know opengl and how graphics works (what is 3dTexture, what is mean depth in texture, FBO, VBO, ... ).

> if we make it a project setting then users will have to understand OpenGL in order to appropriately set the settings.

You can make this settings as "secret" - in project settings, in top exist 
![image](https://user-images.githubusercontent.com/22836285/71427684-3d309780-26cc-11ea-838a-8106a830dfc6.png)

i can add this ability - changes severals strings, but then, need download new source, make changes, then compile... 
I know, this is not mutch cost in my side, and i not pretend to changes.
I just want help you, how i see you have a problems with this settings, it might be helpeful for you in future.

**Comment by SuperDIMMaX** [comment]
Example - [The internal format RGB32F should be color-renderable for texture, But mesa can not support it](https://bugs.freedesktop.org/show_bug.cgi?id=106601)
Easy way avoid this - make, just use - in my case for force use_rgba_3d_shadows...

```
config.use_rgba_2d_shadows = GLOBAL_DEF_RST("rendering/dev/use_rgba_2d_shadows",false);
config.use_rgba_3d_shadows = GLOBAL_DEF_RST("rendering/dev/use_rgba_3d_shadows",false);
```

![image](https://user-images.githubusercontent.com/22836285/71429224-a7e6d080-26d6-11ea-99af-b463806c25e5.png)

or you need predict all posible variants/fixes/etc... or expect when drivers/browsers/...  fix that.

how you see it not dificult and no cost.

**Comment by Calinou** [comment]
I don't see a real value in exposing those settings either. If the automatic detection logic is flawed, open pull requests to improve it :slightly_smiling_face:

**Comment by SuperDIMMaX** [comment]
I not sure, what you mean, but i mean - more about code style paradigm - if use "GLOBAL_DEF_RST" example and use not hardcoded style - #ifndef GLES_OVER_GL
And probality should make seperate use OpenGL ES and True OpenGL . Manufacturer not allways careful about ES on desktop PC - his short answer - Why you use ES on desktop? You should use OpenGL functions instead ES.

**Comment by SuperDIMMaX** [comment]
> If the automatic detection logic is flawed, open pull requests to improve it 🙂

I not fully investigate, where exacly problem... trying use gDEBugger, apitrace,.. only CodeXL works(not fully, and with bugs) - but, his not capture Mesa driver... can`t compare different... and i no see errors... manualy see RAM byte by byte... hard... modyfi sources... hard for me... i not know how all it works... shadow shaders... need more time to find where problem. How i say: this is "strange" problem, i not saw any similar in this GPU. And i not pro in graphics and c++
