### ISSUE TITLE
Better Splash Screens by default to improve Godot's perception.

### ISSUE THREAD

**Issue by gnat** [godotengine/godot-proposals#3356]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

N/A

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Saw this on Reddit earlier: https://old.reddit.com/r/godot/comments/pw8r75/made_a_custom_godot_splash_screen_for_my_game/

Unreal Engine and ID have used this "awesome splash screen" strategy to continually nurture an perception of creative badassery for decades.

I propose godot should adopt the idea of having a selection of nice splash screens simply built-in to brand projects with.

It's arguably the cheapest, most effective PR Godot can possibly have!

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by pycbouh** [comment]
Threads like that pop up all the time. Some just show a unique animation/design for their game, and some release the assets for everyone to use. Changing the image in Godot is trivial, animation is a bit more involved but also doable.

This is something that our community is clearly interested in doing and has better capacity to do it with more creativity than we ever could.

**Comment by Xrayez** [comment]
> Threads like that pop up all the time.

Could you please show other examples of this interest other than this proposal?

**Comment by pycbouh** [comment]
> Could you please show other examples of this interest other than this proposal?

I was referring to the linked Reddit thread with a custom splash screen animation. Threads like that are almost a monthly tradition.

**Comment by KoBeWi** [comment]
We could just add splash screen category to Asset Lib.

**Comment by Xrayez** [comment]
> > Could you please show other examples of this interest other than this proposal?
> 
> I was referring to the linked Reddit thread with a custom splash screen animation, not this proposal. Threads like that are almost a monthly tradition on Godot-related social media.

I asked to provide at least some concrete examples to back up your point, is it so difficult?..

Here's what I've found on Reddit:

* [Made a custom Godot splash screen for my game!](https://www.reddit.com/r/godot/comments/pw8r75/made_a_custom_godot_splash_screen_for_my_game/)
* [3rd custom splash screen logo. Someone suggested a toon shader. Use as you like.](https://www.reddit.com/r/godot/comments/pjc0ch/3rd_custom_splash_screen_logo_someone_suggested_a/)
* [Splash screen idea](https://www.reddit.com/r/godot/comments/mlw95b/splash_screen_idea_code_in_comments/)
* [Made a concept splash screen for Godot 4 when you launch it. Please note that it is a fanmade screen and not official.](https://www.reddit.com/r/godot/comments/m2xicc/made_a_concept_splash_screen_for_godot_4_when_you/)
* [My tribute to Godot for a splash screen for my game Humanless](https://www.reddit.com/r/godot/comments/lddaji/my_tribute_to_godot_for_a_splash_screen_for_my/)
* [Godot Splash screen - thanks to all Godot contributors!](https://www.reddit.com/r/godot/comments/iemy6r/godot_splash_screen_thanks_to_all_godot/)
* ["I too" jumped aboard the logo redesign wagon and created a splash screen for my coconut game](https://www.reddit.com/r/godot/comments/aqfiwk/i_too_jumped_aboard_the_logo_redesign_wagon_and/)
* [Made With Godot Boot Splash / Load Screen](https://www.reddit.com/r/godot/comments/jbcut2/made_with_godot_boot_splash_load_screen/)
* [I just love the AnimationPlayer node and here's pretty much why](https://www.reddit.com/r/godot/comments/oplps0/i_just_love_the_animationplayer_node_and_heres/)
* [Custom Godot splash we made- now publicly available for your game!](https://www.reddit.com/r/godot/comments/i60a28/custom_godot_splash_we_made_now_publicly/)
* [Why so few games mention that they are made with Godot? That's how my boot will look like.](https://www.reddit.com/r/godot/comments/b25353/why_so_few_games_mention_that_they_are_made_with/)

**Comment by pycbouh** [comment]
> I asked to provide at least some concrete examples to back up your point, is it so difficult?..

Sorry, it looked like you misunderstood my comment so I clarified it. But as you can see, logo variations are not hard to find.

**Comment by Xrayez** [comment]
> Sorry, it looked like you misunderstood my comment so I clarified it. But as you can see, logo variations are not hard to find.

I just want to see facts regardless of frequency. In my opinion, that's how Godot proposals should be proceeded: identify a concrete problem - come up with a solution. This would make the discussion/proposal valid and productive.

---

But more on topic: there are plethora ways to make a splash screen with Godot, like the one you can see in this Reddit post using `AnimationPlayer`:

* [I just love the AnimationPlayer node and here's pretty much why](https://www.reddit.com/r/godot/comments/oplps0/i_just_love_the_animationplayer_node_and_heres/)

The "canonical" splash screen is the one you see in Godot by default now displayed at startup. What kind of splash screens are we talking about here?

 This proposal looks somewhat part of or similar to #1419, in a way that more assets are proposed to be added to Godot to choose from, but as Calinou said:

> Note that creating the assets themselves is beyond the scope of the Godot project and should be handled by third parties.

So I'm not quite sure how well *this* particular proposal fits Godot's goals.

Quoting this proposal:

> I propose godot should adopt the idea of having a selection of nice splash screens simply built-in to brand projects with.

So in my opinion according to Godot's goals: a better splash screen by default (animated or not) - yes. Providing variations: third-party or officially supported assets.

**Comment by gnat** [comment]
Fundamentally, this is just a clear PR advantage that EPIC / Unreal Engine has been taking advantage of for quite some time- we're doing ourselves a disservice by not including a handful of nice splash screens.

This isn't just any asset, it's directly engine related.

**Comment by pycbouh** [comment]
> Fundamentally, this is just a clear PR advantage that Epic / Unreal Engine has been taking advantage of for quite some time- we're doing ourselves a disservice by not including a handful of nice splash screens.
> 
> This isn't just any asset, it's directly engine related, and has major benefits to the core project.

What exactly is Unreal Engine providing here? I'm not sure I've seen any custom UE logos which were not made by a professional AA or AAA studio specifically for the project (same with most other big studio engines, to be honest). Also, how exactly does that related to any PR advantage? Godot already has a splash screen, it uses the recognizable Godot mascot logo and the name of the engine. Cannot be any clearer than that.

Can you provide more grounded explanation why it is so important to have a collection of splash screens out of the box as opposed to having only just one and relying on the community for the customization options, like we do for pretty much everything? It's hardly obvious that the splash screen would have such a fundamental effect as you propose, so some demonstration/explanation is required, if that's what you believe it can achieve.

**Comment by Xrayez** [comment]
> Fundamentally, this is a clear PR advantage that Epic / Unreal Engine has been taking advantage of for quite some time- we're doing ourselves a disservice by not including a handful of nice splash screens.

Technically yes, because that's what https://godotengine.org/press provides as well: alternatives. Personally I'm not against providing splash screens to choose from, by the way. I'm just saying that this is something that may go against Godot's development scope, but hopefully not! Yet that may be just wishful thinking from my part.

**Comment by Calinou** [comment]
Closing due to lack of support (see lack of reactions on OP).
