### ISSUE TITLE
Visual Nodes for multiplayer scene replication

### ISSUE THREAD

**Issue by reduz** [godotengine/godot-proposals#3359]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

Recently, @Faless and the networking contributors did a great job [designing and merging](https://github.com/godotengine/godot/pull/51788) support for higher level scene replication. While the API is good for using from code, usability is not yet good enough the everyday Godot user, who expects to do this from a visual user interface, and to be as easy and comfortable to use as possible.

Scene replication happens when the server synchronizes game state to the clients, and reconciles new or disconnected players. While RPC can be used for this, using a higher level replication system helps because:
* General state changes can be batched and sent, consuming less bandwidth.
* The server is trusted and can perform synchronization as it best sees fit, but not trusted enough to a point (where it can cause security issues maliciously).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The idea is to implement two nodes that will aid in doing scene replication as easy as possible:
* **MultiplayerSync**
* **MultiplayerSpawn** (likely including also **MultiplayerSpawn2D** and **MultiplayerSpawn3D**)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

**MultiplayerSync**

This node allows choosing properties from the scene, the same way as AnimationPlayer does, and also editing parameters of how the replication happens, such as:
* **Protocol** (Reliable/Unreliable)
* **Interpolation** (Disabled,Linear,Hermite)
* **Synchronization** (Always, On Changes, On Reconnect)

Mock-up of how it works:
![image](https://user-images.githubusercontent.com/6265307/134982154-37b33e03-c7fc-4a4b-95f4-3692f205c378.png)

Being a node using a similar user interface to AnimationPlayer allows selecting any property on the scene for replication in an easy way, and also connecting a signal to it to perform validation of specific properties, all in the context of the scene.

**MultiplayerSpawn**

This node has a single property, which points to a scene file. It has a single method: `Node* MultiplayerSpawn::spawn(varargs)` which spawns and keep tracks of scenes. When a scene is spawned in the server, it is also spawned on the children nodes. This node can be inherited with a script and `spawn()` can take optional arguments, which are replicated also over the network. If a new player connects or reconnects, this node can ask for spawned scenes (and then those scenes containing a MultiplayerSync will sync properly).

Having the spawner being a node is an excellent tradeoff between usability and security because:

* Spawning is restricted to a single point in the scene tree, instead of anywhere.
* Spawning is restricted to only exist when the spawner node is present.  As a result, game states where the spawner node is not present will not allow spawning by defaylt.
* Spawning is restricted to only the types of scenes defined within the node. As a result, only the right scenes can be instantiated at this position.
* Spawning is restricted to a finite amount of instances by default (and the player must manually increase or decrease the limit.

Spawner node is a security-by-default approach to spawning with a high level of usability, as forces the developer to state the intentin of what will be spawned by default.

**Implementation**

These nodes allow for a very efficient implementation, as the following is possible:
* MultiplayerSync and MultiplayerSpawn register in the core Multiplayer API, they don't send information.
* The server only needs to send a single packet giving an numeric ID to the clients for the NodePath, then properties can be sent by index.
* All information can be batched in a single packet and compressed as much as possible. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This enhancement is core for networking.

### Is there a reason why this should be core and not an add-on in the asset library?

it needs to be integrated to the multiplayer API.

**Comment by Zylann** [comment]
Would this also have a way to compress the fields? A typical for example, with `Transform`, we don't actually need to sync all 12 floats all the time (48 bytes). It can also be synced as 16 bytes only, if we decide to send only position and rotation, with rotation using smallest three compression, and no scale, as typically characters don't need more than this.
Booleans and small states could be also be packed, but that might be harder to expose.

Another aspect is sync frequency. Would this stuff be sent every frame all the time? Could there be some form of priority based on distance to player or gameplay importance, such that less important stuff is synced less often/not at all?

Finally, having the list of synced properties declared this way allows for extra optimizations, such as the ability to omit field names and types since it can be assumed the receiver will have the same layout, further reducing bandwidth usage. But sending by index (just a byte?) may do a similar job if we are to send different properties in each packet.

**Comment by reduz** [comment]
@Zylann Consider this an MVP, I am sure that a lot of optimizations and improvements can be made over time. Regarding sending packets, then yes given this can batch and compress for a lot of nodes, a lot of optimization can be made.

**Comment by aaronfranke** [comment]
> (still sending position uncompressed, but rotation can stay 32-bit smallest three).

There are situations where you would want to send double-precision rotations, so I think it should still be an option (or just always send 64-bit rotation when using 64-bit real_t). For example, the Earth is 40 million meters in circumference, a single-precision rotation angle would have a precision of [over two meters](https://www.google.com/search?q=40074275%2F(2^24)) which is too big. Aside from this, using less precision could lead to more physics indeterminism in client-side calculations for anyone using doubles for the purpose of increasing physics precision.

**Comment by Zylann** [comment]
@aaronfranke oh of course, I was just mentionning this in the context of characters/npc, that kind of stuff. For sure there would be several options to choose from.

**Comment by Norrox** [comment]
Something like checkboxes to select what to sync and at what rate, would be awesome.
And in my opinion NetworkSync and NetworkSpawn as in your screenshot, sounds better. I mean maybe some people make netwok apps not games 🤔 😄

**Comment by Faless** [comment]
Following is the design and current implementation of the `MultiplayerReplicator`, resulting from last month's discussions in the networking meetings.

Design goals
---

- Easy prototyping of multiplayer logic.
- Extensible system allowing drop-in replacement of synchronization.
- Abstracting optimizations from developers.

Concept
---

- Allow users to define which scenes needs to be replicated.
- Create a common UI to define which scenes are relevant for networking.
- Specify which properties are relevant during spawn (e.g. textures/meshes/etc)
- Specify which properties needs to be constantly updated and their tick rate (e.g. position/velocity/etc)
- Minimize extra scene configurations (no special nodes, the same scene should work both for single player, split screen multiplayer, network multiplayer).


Mockup
---

Configuring and getting the replication **does not require to edit your scenes**. You simply selects which scenes need to be replicated, and which properties you want replicated from that scene (including script properties)


![sync-mock1](https://user-images.githubusercontent.com/1687918/135071702-870ceb49-1435-4d26-9da4-d0d1feac5cd3.png)

Extensibility
---

The current system, implements the default behaviour of replicating scenes from server to client **batching updates** of instances of each scene.

Upon connect, a client will receive the scenes that where spawned by the server (and marked for replication), and will start receiving updates.

Updates, as of now, do not have extra logic for e.g. relevancy, but the goal of the current system is also to allow drop-in replacement via plugin.

The replicator can in fact be instructed to call custom plugin functions when a sync is supposed to happen, letting the plugin create and decode the update/spawn transparently from the user.

**Comment by Faless** [comment]
Note, the current design:

- Do not use paths (well, only for spawning).
- Do not send object IDs.
- Send batched updates (one packet for "class"/"scene", containing all the instances of that scene)
- Have **9 bytes of overhead**.

**Comment by reduz** [comment]
@Faless there are quite several problems with your proposed UI

* If you have a large game, you can have hundreds of scenes, you will need to add to your UI the ability to search and manage them.
* You store paths, so if a scene is moved or changed you need to contemplate this. Using the new UIDs is a workaround, but they are not available at the time you load the project settings, so a hack is still required.
* Just clicking on a scene to see its properties is not so simple, scenes can take a long time to load so this menu will feel sluggish.
* The mock-up is wishful thinking, scenes have hundreds of properties in dozens or hundreds of nodes, its not just a few that appear that you can click and that's it. Normally they are folded so you are not aware of as many. You will need to manage a system for browsing the loaded scene.
* Scripts in tool mode will need to run for you to see some properties, and they will need to run in a way that is not intended (this UI instead of the editor).
* In the proposal I wrote above, I added more options for synchronization of properties which I believe are basic in multiplayer (not something you should leave to an add-on). With the proposed UI this is not contemplated.
* In general, this does not really conform to how Godot works. Godot avoids scene-wide settings on purpose, which is why there are nodes such as Environment, AnimationPlayer, AnimationTree, CanvasModulate,Lightmap, NavigationMesh, etc. The OP follows the same line on storing these type of settings in a node.

**Comment by Xrayez** [comment]
> This node allows choosing properties from the scene, the same way as AnimationPlayer does

For reference, I presented the same/similar ideas in https://github.com/godotengine/godot/issues/16793#issuecomment-457845781.

**Comment by Faless** [comment]
> I don't know whether it's possible, but according to my own needs, it's a necessity

Can you expand on this necessity with an example? I really don't see much gain in having reliable state updates, it makes sense to have the initial state sent reliably, but in which case would we want to send part of the state update unreliably and part of it reliably?

**Comment by reduz** [comment]
@Faless I would understand you need reliable updates in the following situation:
* Spawn
* Reconnect (a peer disconnected)
* Change

If a state is only going to change infrequently, it does not make sense to send it all the time via unreliable, it makes more sense to do so as reliable. I think unreliable is only for states that change often.

**Comment by reduz** [comment]
An example of this can be a variable that has the weapon equipped, or which traffic light is turned on, or some other game state that only matters on the server but that you want to make it visual in the client. While I understand you can do this via RPC, having a variable containing state synchronized is easier in case of re-connections.

**Comment by reduz** [comment]
Having this system using reliable state variables also can be very useful eventually if we implement (or make the hooks to implement) area based synchronization, which means that the server will only synchronize what is spatially close to the peer. In this case. When approaching the area of this node, the server will send those state variables to the client.

**Comment by goatchurchprime** [comment]
I've been doing multiplayer in VR, and there is no way this can work -- if you don't discriminate against high latency low band-width connections.  There are too many specific tricks and compromises that can be applied (eg only transmitting details of the player's fine-grain body postures [hand and finger tracking] when other players are close enough to see it).  An all-in-one pre-packaged node creates a barrier to development based on optimizing the bottlenecks. Shouldn't we start with a pure GDScript reference implementation that has all these features (without the nice UI)?

**Comment by reduz** [comment]
@goatchurchprime This is intended for the most common cases. If you want to go low level you can entirely use RPC yourself for what you need, then it is up to you how to synchronize this in different scenarios.

**Comment by goatchurchprime** [comment]
To put it another way, I feel we don't know enough about the most common use cases to design something that doesn't end up being counter-productive.  I think there's a high risk this becomes like the rset() function, which looked like it could be user friendly, but ended up being a bad idea in practice.  (See, for example, the [reason outlined](https://godotengine.org/article/multiplayer-changes-godot-4-0-report-1), such as that it sets one value at a time.)

It would be wiser to begin with at least one toy reference implementation of these features in its own project to analyze where the real problems are, because they are not where we think.  I began doing this, but got bogged down at showing off the different protocols: https://github.com/goatchurchprime/godot_multiplayer_networking_workbench

**Comment by Killfrra** [comment]
I like this proposal, but I would like to be able to also define and select my own sync cases and specify which groups of players to sync with, perhaps similar to how we define our own layers (and similarly be able to select multiple).
<details>
<summary>Usecase.</summary><br/>
I worked on a MOBA as part of a course project. An important part was not to allow anyone to see through the fog of war, even in theory to prevent "wallhacking", so it was a strict client-server and for each synchronized variable I <a href="https://github.com/Killfrra/League-of-LAN/blob/7947d0d788b099efe6e617e947ef3ff5387dde0e/entities/champions/player.gd#L62">set a category</a> (visible to everyone / visible only to the team and observers / visible only to the player and observers / visible only to the player) and synchronized the server data about the player with his opponents only those variables that they can see and only when he is in their scope. That is, as soon as the player got into the enemy's visibility zone, he opened up, synchronized all public variables and continued to update them until he went out of sight.
By the way, this was conceived for all game objects, only the players spawned on all machines at the start of the game, and everything else - as needed, when entering the field of view.
</details>
It would be cool if I had the ability to set up synchronization through a beautiful interface, and then just set variables and trigger events in the code without bothering too much. 

I will probably draw the interface tomorrow, but for now a quick sketch of the desired code part:
```gdscript
func on_peer_connected(id):
    multiplayer.set_category(tree.get_peer_id(), "spectators", true)
    
master func join_team(t):
    if t == "team1" or t == "team2":
        multiplayer.set_category(tree.get_peer_id(), "spectators", false)
        multiplayer.set_category(tree.get_peer_id(), t, true)

func on_visible_by_enemy():
    set_var_group_sync_active("syncWhenVisible", true)
    
func on_not_visible_by_enemy_anymore():
    set_var_group_sync_active("syncWhenVisible", false)    
    
func on_some_action():
    var_group_sync_oneshot("onAction")
```

**Comment by Faless** [comment]
This and #3459 were implemented via https://github.com/godotengine/godot/pull/55950 (and follow-up PRs).
