### ISSUE TITLE
Add a way to copy group names in the editor

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot-proposals#3360]
### Describe the project you are working on

Any game that uses groups

### Describe the problem or limitation you are having in your project

If I want to add a node to a group that another node is in, it would be convenient to just go to that other node and copy the group name instead of having to write it out again.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make so you can either highlight and edit the group name by clicking on it, or add a copy to clipboard button to quickly get the group name. 
![image](https://user-images.githubusercontent.com/7292421/135002567-1cdf045a-763a-4fd4-823c-73f262b3264d.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Double click the group name and it becomes an editable text field (intuitive, as this is how node names work). Or put a copy-to-clipboard button next to the delete icon.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can type the group name out manually, but it's kind of annoying when it's right there already written out.

### Is there a reason why this should be core and not an add-on in the asset library?

This improves base usability and is expected behaviour.

**Comment by Duroxxigar** [comment]
Went ahead and implemented this. I opted to go for the copy button.

https://user-images.githubusercontent.com/16636969/135012783-743873fa-29f8-4e6f-91cf-8543aa6d56c3.mp4
