### ISSUE TITLE
Constrain NodeExtensions method type parameters to extend Node instead of class

### ISSUE THREAD

**Issue by ganondev** [godotengine/godot-proposals#3362]
### Describe the project you are working on

Not a project, but was working on godotengine/godot#53106.
I noticed that the C# `Node` extension methods all generally look like this:

```c#
public T GetNode<T>(NodePath path) where T : class
{
    return (T)(object)GetNode(path);
}
```

Where the method seeks to return a reference to some node casted down to some type `T` that ideally extends `Node` at some level. `T` must be a `class` as opposed to a `struct`, but that doesn't mean very much.

### Describe the problem or limitation you are having in your project

The `where T : class` constraint is way broader than it needs to be. We know anything that comes out of this is going to be a descendent of `Node`, so why do these methods accept a type parameter outside of this inheritance tree? This opens up the method to pointless runtime cast errors.

Additionally, many of these methods have to cast up to `object` first for this to work properly, which can have a real runtime cost.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Tighten the constraints on the type parameter(s) for methods in the `NodeExtensions` class.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Where method signatures are written with a generic parameter e.g. `T` with a constraint 
```c#
public T GetParent<T>() where T : class

```
instead write
```c#
public T GetParent<T>() where T : Node
```

Any casts up to `object` can also be removed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Conceptually it will get 'used' every time someone calls one of these methods.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by raulsntos** [comment]
The methods were originally implemented the way you describe:

```csharp
public T GetNode<T>(NodePath path) where T : Godot.Node
```

But they were changed in godotengine/godot#22760 to:

```csharp
public T GetNode<T>(NodePath path) where T : class
```

The reason is explained in https://github.com/godotengine/godot/issues/22658#issuecomment-705103281

To summarize, with the `T : Godot.Node` restriction you can't use interfaces as the generic parameter.

**Comment by ganondev** [comment]
> To summarize, with the `T : Godot.Node` restriction you can't use interfaces as the generic parameter.

What about something like this as a secondary implementation?
```c#
public U GetNode<T, U>(NodePath path) where T : Node, U
{
    return (U) (T) GetNode(path);
}
```

That way it enforces the Node type but also allows for an interface return.
This way also doesn't have to cast back down after casting up.

You still have to specify a type on the `Node` inheritance tree, but you are going to need to know what that type is anyway if you expect it to be implementing some interface, even with the current constraint.

**Comment by raulsntos** [comment]
But then you need to call the method like this, which is more verbose:

```csharp
GetNode<MyNode, MyInterface>(path);
```

Also, if you know the class type you wouldn't use the interface, you can just use `GetNode<MyNode>` in this case, no need to specify the interface.

The problem is, there could be multiple classes that implement the interface (`MyNodeA` and `MyNodeB`) and you don't care which one it is as long as it implements `MyInterface`, but in with your suggested implementation you need to specify if it is `MyNodeA` or `MyNodeB`.

**Comment by ganondev** [comment]
> But then you need to call the method like this, which is more verbose:
> 
> ```cs
> GetNode<MyNode, MyInterface>(path);
> ```
> 
> Also, if you know the class type you wouldn't use the interface, you can just use `GetNode<MyNode>` in this case, no need to specify the interface.

I was aware of this, which is why I suggested it as a secondary implementation next to the simper one with only one type param `where T : Node`. This is because I don't see most people using interfaces.

> The problem is, there could be multiple classes that implement the interface (`MyNodeA` and `MyNodeB`) and you don't care which one it is as long as it implements `MyInterface`, but in with your suggested implementation you need to specify `T` is `MyNodeA` or `MyNodeB`.

I see. I thought there was a way around this because I was under the impression that partial classes could be extended in multiple assemblies. After doing more research, this assumption was wrong, so I don't see any way to get around that.
