### ISSUE TITLE
Add an OLED-friendly dark theme preset to the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#3368]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

These are the editor theme presets currently available:

![image](https://user-images.githubusercontent.com/180032/135321807-ca0ac75e-39f5-4792-a0ab-283ea4e8adf2.png)

There is no OLED-friendly editor theme preset available out of the box. An OLED-friendly theme is one that uses absolute black (`#000000`) whenever possible to save power and ensure the display's infinite contrast rate can be used. Unlike conventional monitors, OLED displays will turn off pixels that are fully black.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The theme could be called *Black (OLED)* or *Midnight (OLED)*. The *(OLED)* moniker helps OLED monitor users spot this option, as it's the most useful on OLED monitors.

Ultra-dark presets like this one are also relevant for non-OLED displays, but they don't save much power (if at all). However, they can make late night editor sessions more bearable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's an example with the script editor in the `master` branch. Editor settings used:

- **Base Color:** `#000000`
- **Accent Color:** `#80c4ff` (slightly brighter and less saturated version of the default accent color, for better visibility on a black background)
- All other settings at their default values.

![image](https://user-images.githubusercontent.com/180032/135321583-9cbcdbff-22c8-4eb8-83c3-c8860ba4f988.png)

We can consider doing adjustments to the default script editor syntax theme when the OLED preset is used to reduce the "halo" effect around text. Also, we'll most likely want to add some borders around docks when the OLED theme preset is used. Otherwise, the visual separation is lost entirely.

> ***"It looks worse than the Default dark and Gray presets!"***

The goal of an OLED preset isn't to look pretty. It's to be as functional as possible by allowing you to save a significant amount of power, therefore prolonging your laptop's battery life :slightly_smiling_face: 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It may be figured out by more advanced users, but more casual users usually aren't aware of tweaking the editor theme settings outside of the few presets offered.

### Is there a reason why this should be core and not an add-on in the asset library?

With laptops starting to adopt OLED displays, it makes sense to provide an OLED-friendly editor theme preset out of the box. PC monitors are also starting to see OLED options available (and TVs used as PC monitors are becoming increasingly popular too).

If the Godot editor is ported to mobile platforms in the future, this will become even more relevant. Most phones and tablets now use some variation of OLED displays such as AMOLED.

**Comment by Calinou** [comment]
I've made a [first attempt at an OLED-friendly theme](https://github.com/Calinou/godot/tree/editor-theme-add-oled-preset) with a dedicated setting to draw additional borders:

![image](https://user-images.githubusercontent.com/180032/151633899-83e33bf8-2540-4ee2-8264-76bd56ccb862.png)

**Comment by michaldev** [comment]
![main1248 8e6d0b77d29fd84703f62206d15767ff](https://user-images.githubusercontent.com/5132385/200607221-628de275-1424-47ed-adfc-77c35f48f41a.png)

Maybe it will be a good inspiration. Default jetbrains fleet editor theme. I really like the colors, typography and margins. Everything clean, modern and legible.
