### ISSUE TITLE
More crispy GUI 

### ISSUE THREAD

**Issue by BryanEnid** [godotengine/godot-proposals#337]
**Describe the project you are working on:**
Nothing.

**Describe the problem or limitation you are having in your project:**
I'm working on a Mac and the GODOT UI looks very bad.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It will look better.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
no.

**Describe implementation detail for your proposal (in code), if possible:**
No code... it's just an aesthetic proposal. I'm just asking for a more crispy UI. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm pretty sure everyone will love a more pixel perfect UI. It actually looks bad and blurry.

**Is there a reason why this should be core and not an add-on in the asset library?:**
100% this has to be in the core.

**Comment by clayjohn** [comment]
You need to provide more substance for your proposal to be considered. Keep in mind you need to answer all the questions, they are there for a reason. Answering "no" is unhelpful. 

Consider adding specific changes that could be made and examples of what a better UI would look like. Ideally you could provide a mock-up of what an ideal UI design would be. 

Im closing this issue until you provide more.

**Comment by Calinou** [comment]
For future reference, the default font hinting setting was changed to best match the OS in https://github.com/godotengine/godot/pull/31375. You can change this in the Editor Settings.
