### ISSUE TITLE
Print useful error messages in release builds

### ISSUE THREAD

**Issue by jordo** [godotengine/godot-proposals#3382]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

Useful information regarding error messages aren't printed in release builds.  This makes fixing problems in production environments difficult.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Currently, error message information is stripped in release builds, with this commit:   

https://github.com/godotengine/godot/commit/0d7409adfb053c723c0edf1b97d9b25522683f84

What this does, is substitute an empty string for the additional error information you would normally see printed in output.

For example, we have a config file error in a production game, and this is what we see:
![Screen Shot 2021-10-04 at 10 46 52 AM](https://user-images.githubusercontent.com/323868/135891241-82116236-8fe9-4907-9627-dcf7d3567b99.png)

In other builds, we would see what section and key the error comes from here:
![Screen Shot 2021-10-04 at 10 47 29 AM](https://user-images.githubusercontent.com/323868/135891331-8346070f-2b52-4c6e-a018-aaca7d417e44.png)

This is due to the fact that in release builds, the additional error information isn't printed out.  I can't understand why this is the case, as it makes debugging and fixing production games more difficult.

The only reasoning for this I can think of is a potential security issue, but that shouldn't be considered because any parameters passed to any error macro here already has the arguments in memory, which means they can be read by simply looking at memory.  (Not printing them out, isn't actually more secure, it just makes reading this information potentially more difficult)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Revert the commit https://github.com/godotengine/godot/commit/0d7409adfb053c723c0edf1b97d9b25522683f84

I think the majority of developers with production games would appreciate the additional logging information in any bug reports they receive.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It cannot be worked around, as it's in core error_macros.h

### Is there a reason why this should be core and not an add-on in the asset library?

It's core, as defined in error_macros.h

**Comment by pycbouh** [comment]
The commit you've linked only restored the intended behavior. It was removed previously by mistake. The PR this commit comes from has an answer to your "Why", by the way: https://github.com/godotengine/godot/pull/33595

**Comment by jordo** [comment]
From discussion in rocket chat today, the reasoning was for omission of string allocation/overhead and binary size considerations.

Our wasm build size with these errors enabled and disabled is below is:

27,326,350 bytes vs 27,242,926 bytes

So adding these errors details resulted in a 0.3% increase in binary size for our web builds.  

And the expansion / any other processing ONLY happens if the conditional passes.  

![Screen Shot 2021-10-04 at 11 32 43 AM](https://user-images.githubusercontent.com/323868/135897327-3630adf6-7d6f-4f2e-a3f2-9f425060e2d2.png)

**Comment by Calinou** [comment]
Given the relatively small increase in binary size, I think it's worth keeping messages in release builds.

**Comment by pycbouh** [comment]
Closed by https://github.com/godotengine/godot/pull/53405
