### ISSUE TITLE
More advanced options for splash or intro logos

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#3396]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

N/A

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

While not essential, a good looking splash screen can help make the game look more professionally-made. As of currently, Godot only have one option for the initial loading splash screen, and I am not even sure if it support videos.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Instead of a single image file for the splash screen, there should be an array of splash logo(idk how I should name this) resource(or classes?), in which you can set options such as type(static image, animated image with simple animations, video) along with the corresponding image or video file, duration, etc.

When the game starts up, Godot could either play those splash logos before or after loading(in which case you could specify a static image).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am not sure if you can implement the array part, but here's the rough idea:

1. An autoload (singleton?) script, after the game loads, pause everything and
2. go through the array, displaying custom splashes in order.
3. When done, switch back to the main scene specified in the project settings.

### Is there a reason why this should be core and not an add-on in the asset library?

This would be more convenient as a core feature.

**Comment by Calinou** [comment]
This is definitely third-party territory to me. Long splash screen sequences are generally considered more trouble than they're worth, especially in indie games where getting in an out of a game quickly is a selling point.

**Comment by Calinou** [comment]
Closing due to lack of support (see the lack of reactions on OP).
