### ISSUE TITLE
[Probably duplicate] Add Emacs as an external editor or allow generic command execution for external editor for Mono

### ISSUE THREAD

**Issue by treymerkley** [godotengine/godot-proposals#34]
**Describe the project you are working on:**
Right now, I'm trying to translate some of the templates to C#.

**Describe how this feature / enhancement will help your project:**
I use Emacs as my text editor, and it has my dev environment as I have it set up. That way I won't have to maintain a separate editor for my system. I imagine that this is true for many users and their chosen environments.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Really, just the option to have a generic string to execute, like in the GDScript external editor configuration.

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't know what the difference is, so I couldn't say.

**Comment by girng** [comment]
have you tried `Exec Path` and `Exec Flags`?
![image](https://user-images.githubusercontent.com/45474847/64364300-661b0880-cfc7-11e9-8a11-2894955cd7cb.png)

**Comment by treymerkley** [comment]
Hey, @girng buddy, it's been a while. Yeah, so I have it specified there, but there's a different section for editing Mono stuff, and it doesn't have those options in it.

**Comment by girng** [comment]
hey :)

i see. yeah, prob a good idea to get it added there as well. @neikeq can prob offer more insight on this matter

**Comment by neikeq** [comment]
The reason we have separate external editor options for C# is to provide a better experience for a set of editors/IDEs. If your editor is not one of them, you can use the settings at `Text Editor > External` as @girng mentioned. Right now, I can't think of any reason to provide an equivalent of those settings only for C#, unless you want to open GDScript and C# in different editors. If discoverability of the C# external editor settings is a problem, we could move them to `Text Editor > External`.

**Comment by treymerkley** [comment]
So you're saying that `Text Editor > External` setting will work for C#? And when you say discoverability, whether Godot is catching the text editor as expected?

**Comment by Calinou** [comment]
@treymerkley By "discoverability", @neikeq refers to the ability to find the setting easily so people don't miss it when navigating the Editor Settings.

**Comment by neikeq** [comment]
Yes, what @Calinou said. While global external text editor settings are at `Text Editor > External`, C#'s special settings are at `Mono > Editor`. This can make it hard to find them.

**Comment by treymerkley** [comment]
Oh! Okay. At most, I think adding tooltip to the external editor option might be helpful. Anything else would probably be unnecessary and detrimental to existing users. If you all think it would make more sense to move it, go for it, it's your project, but I didn't have too hard of a time *finding* the settings, at least. Since the issue is more or less resolved, if I understand correctly and the global editor settings will still be obeyed for C# files when Mono text editor isn't set, I'll go ahead and close this out.
