### ISSUE TITLE
Remove `@desc` tag in documentation comments

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot-proposals#3400]
### Describe the project you are working on

A game

### Describe the problem or limitation you are having in your project

[Documentation comments](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_documentation_comments.html#tags) added in 4.0-dev. The brief does not require a tag, but the description does, although the description is usually longer than the brief.

In this case, for the description, you need to add 4 spaces at the beginning of each line. This means less width space (quite a few people have narrow screens or try to stick to the 80-100 characters per line limit). Plus a slightly larger file size (not that important, but why increase the file size if it doesn't make sense?).

```gdscript
##
## A brief description of your script.
##
## @desc:
##     A more detailed description of the script.[br]
##     Lorem ipsum dolor sit amet, consectetur adipiscing elit,
##     sed do eiusmod tempor incididunt ut labore et dolore
##     magna aliqua.[br]
##     Ut enim ad minim veniam, quis nostrud exercitation ullamco
##     laboris nisi ut aliquip ex ea commodo consequat.[br]
##
## @tutorial:            http://the/tutorial1/url.com
## @tutorial(Tutorial2): http://the/tutorial2/url.com
##
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The first option is to swap the brief and description, i.e. require a tag for the first and not require a tag for the second:

<details>
<summary>Option 1.1</summary>

```gdscript
##
## @brief:
##     A brief description of your script.
##
## A more detailed description of the script.[br]
## Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
## do eiusmod tempor incididunt ut labore et dolore magna aliqua.[br]
## Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
## nisi ut aliquip ex ea commodo consequat.
##
## @tutorial:            http://the/tutorial1/url.com
## @tutorial(Tutorial2): http://the/tutorial2/url.com
##
```

</details>

We should also allow the brief to be on the same line as the tag:

<details>
<summary>Option 1.2</summary>

```gdscript
##
## @brief: A brief description of your script.
##
## A more detailed description of the script.[br]
## Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
## do eiusmod tempor incididunt ut labore et dolore magna aliqua.[br]
## Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
## nisi ut aliquip ex ea commodo consequat.
##
## @tutorial:            http://the/tutorial1/url.com
## @tutorial(Tutorial2): http://the/tutorial2/url.com
##
```

</details>

The first option has 2 drawbacks: some may not want to use descriptions at all, but they will have to use `@brief` every time; Also in doc comments, `@tags` are usually placed at the end. We can, by analogy with commit messages in git, split a comment into a brief and a description by an empty line between them:

<details>
<summary>Option 2</summary>

```gdscript
##
## A brief description of your script.
##
## A more detailed description of the script.[br]
## Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
## do eiusmod tempor incididunt ut labore et dolore magna aliqua.[br]
## Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
## nisi ut aliquip ex ea commodo consequat.[br]
##
## @tutorial:            http://the/tutorial1/url.com
## @tutorial(Tutorial2): http://the/tutorial2/url.com
##
```

</details>

Just a variation of Option 2:

<details>
<summary>Option 3</summary>

```gdscript
##
## A brief description of your script.
##
##
## A more detailed description of the script.
##
## Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
## do eiusmod tempor incididunt ut labore et dolore magna aliqua.
##
## Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
## nisi ut aliquip ex ea commodo consequat.
##
##
## @tutorial:            http://the/tutorial1/url.com
## @tutorial(Tutorial2): http://the/tutorial2/url.com
##
```

</details>

By the way, doc comments do not support `[p][/p]` BBCode, although `RichTextLabel` does.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be done with an add-on.

**Comment by LikeLakers2** [comment]
@dalexeev Actually, please ignore my suggestion for now. I realize I made a huge assumption about the current topic (I assumed it was about documentation as a whole, rather than just about the `@desc` tag).

I still want to recommend something similar to Rust's documentation style (I *really* think it would fit here), but I realize this isn't the best place to do so. So I've hidden my comments.

That all said, my support is now on **Option 3**, as it's the closest to what I'd want.

**Comment by dalexeev** [comment]
> Rust asks that you use `//!` for documentation that relates to the whole file, whereas you use `///` for documentation that relates to a single item within that file.

Thank you, now I understand. But this doesn't apply to this proposal, it's about removing unnecessary tag and indentation.

I don't see the need to somehow indicate the to the whole script. It's already well recognized by the fact that this comment is located at the beginning of the file.

> Then... I think how it's done now isn't that great?

See how it is done in [the core documentation](https://github.com/godotengine/godot/blob/a5a52233bc1327d8943c0a2a3866aa314371edec/doc/classes/Node.xml#L3-L22). The `[br]` BBCode has been added to make it possible to wrap lines in code without adding new lines in the documentation.

If you don't like `[br]` and double blank lines, then there is Option 4:

```gdscript
##
## A brief description of your script.
##
## A more detailed description of the script.
##
## Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
## do eiusmod tempor incididunt ut labore et dolore magna aliqua.
##
## Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
## nisi ut aliquip ex ea commodo consequat.
##
## @tutorial:            http://the/tutorial1/url.com
## @tutorial(Tutorial2): http://the/tutorial2/url.com
##
```

By the way, adding blank lines at the beginning and at the end is optional, I just copied that from the documentation. At the moment, this option also works:

```gdscript
## A brief description of your script.
##
## @desc:
##     A more detailed description of the script.[br]
##     Lorem ipsum dolor sit amet, consectetur adipiscing elit,
##     sed do eiusmod tempor incididunt ut labore et dolore
##     magna aliqua.[br]
##     Ut enim ad minim veniam, quis nostrud exercitation ullamco
##     laboris nisi ut aliquip ex ea commodo consequat.[br]
##
## @tutorial:            http://the/tutorial1/url.com
## @tutorial(Tutorial2): http://the/tutorial2/url.com
```

That is, there is no technical need to add exclamation marks to the script comment to distinguish it from others.

**Comment by vnen** [comment]
This looks sensible to me. The tag was added likely to be similar to the XML tags in the engine documentation, but option 2 or 3 could be used instead.
