### ISSUE TITLE
Template strings in GDScript 2.0

### ISSUE THREAD

**Issue by AhmedElTabarani** [godotengine/godot-proposals#3403]
### Describe the project you are working on

Nothing

### Describe the problem or limitation you are having in your project

This is just an idea for GDScript 2.0 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Can we have Template strings in GDScript 2.0, it will be a great feature in dealing with strings or dialogues text

in javascript have a backtick, and dart make it very flexible, and it is very helpful

in javascript

```js
var id = 123
var name  = "Ahmed"
var age = 21
```
without backticks 
```js
console.log("Hi I'm " + name + ", my age is " + age + ", id = " + id)
```
with backticks 
```js
console.log(`Hi I'm ${name}, my age is ${age}, id = ${id}`)
```

in dart, we can remove `{ }` I think this make it familiar with Godot style

Dart

```dart
print("Hi I'm $name, my age is $age, id = $id")
```

 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

These are my thoughts on how we can use them in Godot, and `it's up for discussion`

GDScript have a problem with combine different variables with string 

```gdscript
var id = 123
var name  = "Ahmed"
var age = 21

# error Invalid operands 'String' and 'int' in operator '+'.
print("Hi I'm " + name + ", my age is " + age + ", id = " + id)
```

we get an error, to handle it we must do this (convert int to string using str())

```gdscript
print("Hi I'm " + name + ", my age is " + str(age) + ", id = " + str(id))
```

This not a flexible way, if we're dealing with a lot of un-strings variable with huge and many dialogues text, It will be annoying and not flexible.

### My thoughts on how we can use them in Godot:

Using a symbol like `@` will be familiar with Godot 4.0 style

```gdscript
print("Hi I'm  @name, my age is @age, id = @id")
```
If we want to use expressions, we can do it like this `@( )`

```gdscript
for i in 10:
   print("No.  @(i + 1), @(i * i), @(i + i)")
   # normal way:
   print("No. " +  str(i + 1) + ", " + str(i * i) + ", " + str(i  + i))
```

in Dart can make a complex expression inside template strings like a ternary
```dart
print("There are ${x < 10 ? "a few" : "many"} people in this room");
```
we can use the same way and put it in godot using template strings

```gdscript
print("There are @('a few' if x < 10 ? else 'many') people in this room")
```

**I think it will be very interesting to discuss and take opinions and ideas about it**

**Comment by pycbouh** [comment]
Closing per the above comments.
