### ISSUE TITLE
Add timing options for AnimatedSprite (`current_time` and `frames_per_second`)

### ISSUE THREAD

**Issue by coderarnold** [godotengine/godot-proposals#3404]
### Describe the project you are working on

A 3d FPS with AnimatedSprite3D for the characters and loot.

### Describe the problem or limitation you are having in your project

When changing by code the animation for the AnimatedSprite3D (via the "animation" property, or the "play()" method), the current frame automatically goes to zero. In some cases this can be a problem. For example in a walk animation seen from different angles, if we change the view angle, it's considered a new animation as far as AnimatedSprite3D is concerned. While a character is walking, that's a problem, we don't want to set the frame back to zero each time the view angle changes.

The workaround for now is to set the current frame manually to the one before the animation change, but the animation timer goes back to zero no matter what. Therefore the overall character animation (eg walk, not the AnimatedSprite3D's current animation) is affected and goes out of sync with other elements (eg foot step sounds), and if we change the animation too often (eg the camera turns around the sprite, or the sprite turns on itself), and/or if the animation has few frames per second, it can even make the sprite appear on pause, but it just doesn't have enough time to move one frame forward before a new animation is set.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

What would be useful is the possibility to set by code the exact current time in the animation, not just the current frame, in absolute time units, eg in seconds, not percentage. That way we can control more complex animation transitions and scenarios the way we need.

Changing the animation speed in frames per second would also be useful. For example characters affected by different states (frozen or berserk) could have slower or faster animations.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the AnimatedSprite3D class, there would 2 new float properties we can get and set:
- "current_time" , in seconds, for the current animation
- "frames_per_second", for the current animation

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not a Godot expert, I'm still learning, but I think it could be done in the current state of the engine by using the Sprite3D class alone and implementing the animation logic ourselves. However the AnimatedSprite3D is here for exactly that role, so it would be make sense to extend its capabilities with timing options, and not let the users reinvent the wheel.

### Is there a reason why this should be core and not an add-on in the asset library?

AnimatedSprite3D is very limited right now in terms of animation control, despite its role as animation support for 2d sprites in 3d space. So it should be core.

**Comment by Calinou** [comment]
Note that if this feature is added in AnimatedSprite3D, it should also be made available in AnimatedSprite2D (AnimatedSprite in `3.x`).

**Comment by coderarnold** [comment]
> Still, consider using Sprite3D + AnimationPlayer for advanced scenarios. AnimationPlayer allows defining time as seconds rather than frames when seeking. AnimatedSprite is only meant to cater to basic scenarios such as constant animation, so that it can be kept simple for basic use cases.

Thanks, I'll do that in the meantime.

The AnimatedSprite3D class still has the advantage over the Sprite3D + AnimationPlayer solution, because it lets the user define custom rects for the frames, so that:
- frames can be reused in multiple animations
- frames don't have to be the same size
- frames can be from multiple textures resources

AFAIK the Sprite3D class allows defining a custom region rect, but then it's harder to animate, it's impossible to define multiple rects, and all frames must be from the same texture, unless I missed something.

**Comment by TokageItLab** [comment]
Closed by #71907 with adding `frame_progress`.
