### ISSUE TITLE
Make points in Line2D relative to the node instead of global

### ISSUE THREAD

**Issue by boyhax** [godotengine/godot-proposals#3407]
### Describe the project you are working on

2d platformer  with basic enemies walk in manual made path until player in chase or attack range. 

### Describe the problem or limitation you are having in your project

Every time level design change or i make copy of enemy i have to make the path points again

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Maybe every point is point2d node and added to the line2d node as child or every time the node moved the points will relocated relatively. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

With code in line2d node

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If points is point2d node it maybe could be few lines of code. 

### Is there a reason why this should be core and not an add-on in the asset library?

Points to be always relative to parent is what normaly anyone want and it by default will not make problems for how want it as global just dont move the node. And it is change to core node.

**Comment by kleonc** [comment]
Points of `Line2D` are local to that node, they're not global. So not sure what's the problem and what this proposal is about.

**Comment by boyhax** [comment]
ok sorry the points is relative to the node i needed to check more before .
