### ISSUE TITLE
Vector input action

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#3411]
### Describe the project you are working on

N/A (Applies to any project with directional movements)

### Describe the problem or limitation you are having in your project

As of currently, input actions in Godot can have strength to them, but they can only have one (positive) direction. This greatly limits on complex inputs such as vector inputs, which are commonly used since they are easy to manipulate.

For example, if you want to limit your character's horizontal movement speed, you have to put the four movement actions into a vector(at least a Vector2):
```gdscript
# Assume this is in a function
var movement := Vector2.new()
movement.x = Input.get_action_strength("right") - Input.get_action_strength("left")
movement.y = Input.get_action_strength("up") - Input.get_action_strength("down")
```
And then normalize the movement vector if it's length is more than 1:
```gdscript
if movement.length() > 1.0:
    movement = movement.normalized()
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This proposal proposes a new Vector input type, in which you can specified the positive and negative action for each axis, and with an option to limit the vector's length.

This will help reduce a lot of redundant code that deals with normalizing input directions, etc. that are shown above and make input stuff generally easier.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When adding a new input action, you will be able to choose what type of action it is, e.g. [default type with only one action key], Vector2, etc.

This may require a revamp of the input system, but seeing as the input system is pretty limited, I think it deserves a revamp anyway.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

(See the codes shown in the limitations section)

### Is there a reason why this should be core and not an add-on in the asset library?

As far as I can see, it is impossible for plugins to modify how the input system work.

**Comment by atirut-w** [comment]
> godot 3.4

Isn't that still in beta, though?

**Comment by KoBeWi** [comment]
It is, but you can get it here: https://godotengine.org/article/dev-snapshot-godot-3-4-beta-6
