### ISSUE TITLE
Add a way to load SVG files from buffer at an adjustable scale

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot-proposals#3422]
### Describe the project you are working on

2D topdown game.

### Describe the problem or limitation you are having in your project

Some elements need to be scaled correctly, the strategy of scaling the SVG up on import and shrinking when drawing has its limitations.

I'm importing a lot of SVG files at a larger scale (and shrinking later), this is increasing the size of the `pck` a lot, being able to load them at runtime would allow me to have a much smaller `pck`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The [`Image`](https://docs.godotengine.org/en/stable/classes/class_image.html) contains methods to load different formats from a buffer: [bmp](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-load-bmp-from-buffer), [jpg](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-load-jpg-from-buffer), [png](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-load-png-from-buffer), [tga](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-load-tga-from-buffer), [webp](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-load-webp-from-buffer).

But there are no methods to load buffer containing **SVG** data.

Implementing this method makes it possible to start working on a solution to update the texture when the desired size changes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The addition of this method `Image::load_svg_from_buffer(buffer: PoolByteArray, scale: float = 1.0)` to the [`Image`](https://docs.godotengine.org/en/stable/classes/class_image.html).

This method should be available in the editor and in exported projects.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, we can load **SVGs** from file at runtime with [Image::load](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-load), but there is no option to load it at different scales, the scale 1.0 is implicit and cannot be modified.

**Edit**: According to https://github.com/godotengine/godot-proposals/issues/3422#issuecomment-942560151, **SVG** is only available in editor builds, so even the [Image::load](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-load) won't work for exported projects.

### Is there a reason why this should be core and not an add-on in the asset library?

This method provides functionality to create amazing add-ons, but its implementation depends on things only available in the core, like access to the SVG parser and rasterizer library (nanosvg).

**Comment by sammycage** [comment]
> But as suggested here, a better SVG importer would need to be integrated.

You can use [LunaSVG](https://github.com/sammycage/lunasvg) for importing SVG files. It's fast, easy to use, regularly maintained, free from crash and supports a wide range of svg features.

> It's fast

Parse -> Layout -> Render

#### Parse

LunaSVG uses a very fast `XML` parsing technique which is faster than `fread` in many cases.

#### Layout

LunaSVG converts the `XML` node into an extremely simple representation which can be easily transformed or rendered multiple times.

#### Render

LunaSVG uses PlutoVG as the default renderer. It is very fast when rendering regular svg files. You can easily add another renderer if you don't like the way PlutoVG does things.

> Easy to use

Basic Usuage :

```cpp

#include <lunasvg.h>

using namespace lunasvg;

auto document = Document::loadFromFile("board.svg");
auto bitmap = document->renderToBitmap([<max width>, <max height>, <background color>]);
```

For more details : 
https://github.com/sammycage/lunasvg/blob/master/include/lunasvg.h

> Regularly maintained

LunaSVG is regularly maintained by an "SVG" experts.

> Free from clash

- Each pointer is checked before being accessed.
- Recursive `XML` referencing is properly handled.
- Smart memory management

**Comment by TechnoPorg** [comment]
This could tie in nicely to #6495, and probably others too, like #2924. Implementing a brand new SVG texture type would really improve Godot's SVG experience and make it much more powerful on that front.
I'm not sure whether a dedicated `SVGTexture` subclass of `Texture2D` would be the best solution for SVG handling, or whether it would be better to create an `SVGImage` to drop into an `ImageTexture`. Any thoughts?

**Comment by Calinou** [comment]
> I'm not sure whether a dedicated SVGTexture subclass of Texture2D would be the best solution for SVG handling, or whether it would be better to create an SVGImage to drop into an ImageTexture. Any thoughts?

I think it should be a dedicated SVGTexture with a `source` property. This would make it similar in spirit to GradientTexture, CurveTexture, etc.

**Comment by felaugmar** [comment]
@Calinou 
 
> I think it should be a dedicated SVGTexture with a `scale` property and a `source` property where you write the SVG code. The texture is updated when `scale` or `source` are modified. This would make it similar in spirit to GradientTexture, CurveTexture, etc.

I've tested an implementation like that [here](https://github.com/felaugmar/godot/tree/svg-texture).

It works but the usability is poor, the ".svg" must live as a file, not a property of `SVGTexture`.

**Comment by Calinou** [comment]
> It works, but the usability is poor, the ".svg" must exist as a file/resource, not as a property of SVGTexture.

I think it could have good usability if you added a way to change the texture's import mode to a SVGTexture, so that it imports a SVGTexture instead of an ImageTexture. You'd need to find a way to restrict this import mode to `.svg` only (and perhaps `.svgz` if its data can be decompressed on-the-fly).

**Comment by felaugmar** [comment]
> so that it imports a SVGTexture instead of an ImageTexture

I thought about this possibility, what made me disregard it for now was the current "import workflow", where `Resource`'s properties are defined when importing. 

This is fine in the case of **.svg content**, but an issue in the case of `scale` which would ideally be changed in the `EditorInspector`.

It's possible to write a custom workflow for `.svg`, but the work done is not so trivial. At least for me 😝
