### ISSUE TITLE
Make changes to `AndroidManifest.xml` using android plugin `.gdap` file 

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot-proposals#3423]
### Describe the project you are working on

Add extra changes to the `AndroidManifest.xml` from within the android plugin config file 

### Describe the problem or limitation you are having in your project

Some android plugin require a manual modification to the `AndroidManifest.xml` file .
For example `Admob` requires inserting the game id inside of the Manifest `<application>` 

```xml
<manifest>
    <application>
        <!-- TODO: Replace with your real AdMob app ID -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-################~##########"/>
    </application>
</manifest>
```

Not only google Admob but many sdks providers now requires an addition to `AndroidManifest.xml` file .

*The problem is* when using similar android plugins every time you upgrade to another Godot version the `AndroidManifest.xml` file gets rewritten by a new clean file , at that time you have to edit it and try to remember every plugin manifest implementation .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Seamless upgrading the project to a new **Godot**  version when every plugin will decide what it can add to the `AndroidManifest.xml` file

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This was available back then in the Godot android module old implementation  .

```python
if env['platform'] == 'android':
        # will copy this to the java folder
        env.android_add_to_manifest("AndroidManifestChunk.xml") <----
```

Now the new android plugins implementation looks like :
```md
[config]

name="MyPlugin"
binary_type="local"
binary="MyPlugin.aar"

[dependencies]

local=["local_dep1.aar", "local_dep2.aar"]
remote=["example.plugin.android:remote-dep1:0.0.1", "example.plugin.android:remote-dep2:0.0.1"]
custom_maven_repos=["http://repo.mycompany.com/maven2"]
```

we can add a new tag `[android_manifest]` and add below it what the plugin should add to the main android project `AndroidManifest` .

or more like 
```md
[android_manifest]

local=["AndroidManifestChunk.xml"]
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so 

### Is there a reason why this should be core and not an add-on in the asset library?

imo it is a feature that enhances the plugins creation experience

**Comment by hani09876** [comment]
Does it added?

**Comment by Calinou** [comment]
> Does it added?

No, not yet.

**Comment by hani09876** [comment]
> > Does it added?
> 
> No, not yet.

Why? This feature is so important. Then why aren't they implementing this

**Comment by Calinou** [comment]
> Why? This feature is so important. Then why aren't they implementing this

Contributions are made on a best-effort basis. No warranty is provided, and contributors do not have any obligation to implement features requested here.

**Comment by gumaciel** [comment]
Hello guys, I have a suggestion: Instead of creating an `AndroidManifestChunk.xml` we could give the user the possibility to edit the entry directly by the editor, this would prevent the user from looking for the .xml file and editing manually. What do you think?

iOS already does this and it would look something like this:

![image](https://user-images.githubusercontent.com/20030153/177072610-3800a779-bef0-4ace-a10a-c628d300e7df.png)

**Comment by m4gr3d** [comment]
The `gdap` Android plugin format has been deprecated in Godot 4.2 and the new format supports the ability to customize the `AndroidManifest.xml` file.

Please take a look at the documentation: https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html
