### ISSUE TITLE
Add Option in Settings to disable automatic script multilevel calls for GDScript

### ISSUE THREAD

**Issue by learis** [godotengine/godot-proposals#343]
As I understand it, at some point in the C# release, automatic script multilevel calls for functions such as _ready and _process were removed to keep things consistent with C# expectations [as shown here](https://github.com/godotengine/godot/pull/16205) . I am not asking them to be removed for GDScript as I know this would break so many people's projects. But what I am asking is for an option in settings to enable/disable this feature. That way people have the freedom to choose. I don't know how the engine is built for Godot and if this is even possible, but I just wanted to suggest it; below is my reasoning for this.

Auto-calls are useful and proper for certain situations. However for things like _process, it's understandable that complete overriding could be preferential to automatically calling all parent functions if a child is intended to have completely different behaviors than its parent(s). This is my reasoning for desiring this feature.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
