### ISSUE TITLE
Implement pressing the Stop button a second time to reset the animation to the start in the AnimationPlayer editor

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#3434]
### Describe the project you are working on

Implement this standard behavior in many players.
It is annoying having to exit the animation player buttons because there is no dedicated button to bring the time bar to the start.

### Describe the problem or limitation you are having in your project

The problem is the fact that there is no button to bring the time bar to the beginning of the animation directly, without playing it backwards.
Something that many players have is that when you press the stop button twice, the playback starts.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Simply when the user presses stop twice, the animation bar will automatically be placed at the beginning of the animation

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simplemente cuando el usuario pulse dos veces stop, la barra de animación se situará automaticamente al inicio de la animación

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's not possible

### Is there a reason why this should be core and not an add-on in the asset library?

It's not possible

**Comment by Calinou** [comment]
I think https://github.com/godotengine/godot-proposals/issues/167 is a better solution to this problem.

**Comment by Torguen** [comment]
Ok then it can be closed because the request has already been raised
