### ISSUE TITLE
Implement middle-clicking to paste with primary clipboard in X11

### ISSUE THREAD

**Issue by AndreaCalligaris** [godotengine/godot-proposals#3440]
### Describe the project you are working on

Any project while on a Linux OS using X Window.

### Describe the problem or limitation you are having in your project

While coding a GDScript in the Godot editor, if I middle-click to paste the primary selection, nothing happens.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be useful while coding to use the middle-click paste functionality of Linux system to improve coding.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Not applicable.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No possible workaround, except maybe with external clipboard software.

### Is there a reason why this should be core and not an add-on in the asset library?

Because as a Linux user it feels bad when the middle-click doesn't work, since it's a very useful feature that I normally use in any other program.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/53702.
