### ISSUE TITLE
Add Spritesheet support to RichTextLabel BBCode

### ISSUE THREAD

**Issue by progsource** [godotengine/godot-proposals#3441]
### Describe the project you are working on

I'm working on an adventure game. Nothing available public yet. Also like to do gamejams with Godot.

### Describe the problem or limitation you are having in your project

In RichTextLabel it is currently possible to add images. Now in my adventure game there will be many icons that I would like to show in RichTextLabel, but I don't want to create an asset per icon, because I have them already all in one image.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add support for spritesheets in BBCode. This way it would be possible to use one image with regions to select an icon to show in RichTextLabel

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
[img=<width>x<height> regionposx=<x> regionposy=<y> regionsize=<width>x<height>]{path}[/img]
```
Names of parameters just as example..

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not aware of a workaround other than to use many images.

### Is there a reason why this should be core and not an add-on in the asset library?

Parsing of RichTextLabel happens in a private method... It could be made as an own thing, but that would, I guess, require to copy the whole RichTextLabel into an addon/module.

**Comment by progsource** [comment]
> > I'm not aware of a workaround other than to use many images.
> 
> You can use any texture resource there. So you could use an atlas to drive all your images.

So would I have to create many textures then in that case?

**Comment by pycbouh** [comment]
I guess, though maybe there is a way to organize it better. Either way, your source texture would be just one asset in that case.

**Comment by progsource** [comment]
For me that sounds still like I have to do a lot of manual work to display the icons then. Even though making multiple textures might help it rendering-wise, it doesn't solve the issue of having many assets (in that case then textures).

**Comment by KoBeWi** [comment]
You can't add image normally. You can have a variable that stores a list of images you "added", use the effect callback to determine their position and draw them using `_draw()` method. This is a big hack, but should be possible to do (as a workaround, that is). I'll try to create an example.

**Comment by KoBeWi** [comment]
Uhhh I doubt this is useful xd
[ImageHack.tscn.txt](https://github.com/godotengine/godot-proposals/files/7360476/ImageHack.tscn.txt)
(this is a self-contained scene, with dependency on icon.png)

For this text
```
Spritesheet test
Image 1 goes here -> [sheet image=icon.png size=32,32 frame=0]      [/sheet] <- image2 goes here -> [sheet image=icon.png size=32,32 frame=1] [/sheet]




And there the third one [sheet image=icon.png size=32,32 frame=2] [/sheet]
```
It displays
![image](https://user-images.githubusercontent.com/2223172/137637554-efcd7d38-1745-417a-a767-5c44d775c83c.png)

Looks like `absolute_index` doesn't take newlines into account, but **this is possible to workaround too**. That solution is extremely inefficient though. A proper spritesheet support would be indeed better.

**Comment by progsource** [comment]
With the following code change based on 3.3.4-stable, I can add images with regions:

```diff
diff --git a/scene/gui/rich_text_label.cpp b/scene/gui/rich_text_label.cpp
// [...]
                        push_meta(url);
                        pos = brk_end + 1;
                        tag_stack.push_front("url");
-               } else if (tag == "img") {
+               } else if (tag.begins_with("img ") || tag == "img") {

                        int end = p_bbcode.find("[", brk_end);
                        if (end == -1)
                                end = p_bbcode.length();

+                       bool is_region_enabled = false;
+                       Rect2 region;
+                       String params_s = tag.substr(3, tag.length());
+                       Vector<String> params = params_s.split(" ", false);
+
+                       for (int i = 0; i < params.size(); ++i) {
+                               int pos = params[i].find("region_x=");
+                               if (pos != -1) {
+                                       region.position.x = params[i].substr(pos + String("region_x=").length(), params[i].length()).to_double();
+                                       is_region_enabled = true;
+                                       continue;
+                               }
+
+                               pos = params[i].find("region_y=");
+                               if (pos != -1) {
+                                       region.position.y = params[i].substr(pos + String("region_y=").length(), params[i].length()).to_double();
+                                       is_region_enabled = true;
+                                       continue;
+                               }
+
+                               pos = params[i].find("region_w=");
+                               if (pos != -1) {
+                                       region.size.x = params[i].substr(pos + String("region_w=").length(), params[i].length()).to_double();
+                                       is_region_enabled = true;
+                                       continue;
+                               }
+
+                               pos = params[i].find("region_h=");
+                               if (pos != -1) {
+                                       region.size.y = params[i].substr(pos + String("region_h=").length(), params[i].length()).to_double();
+                                       is_region_enabled = true;
+                               }
+                       }
+
                        String image = p_bbcode.substr(brk_end + 1, end - brk_end - 1);

                        Ref<Texture> texture = ResourceLoader::load(image, "Texture");
                        if (texture.is_valid())
+                               if (is_region_enabled) {
+                                       Ref<AtlasTexture> atlas_tex = memnew(AtlasTexture);
+                                       atlas_tex->set_atlas(texture);
+                                       atlas_tex->set_region(region);
+                                       texture = atlas_tex;
+                               }
                                add_image(texture);

                        pos = end;
-                       tag_stack.push_front(tag);
+                       tag_stack.push_front("img");
                } else if (tag.begins_with("img=")) {

                        int width = 0;
```

I just am not sure about creating a PR yet, because of namings, code style, code optimization, if it's wanted etc.
And it probably also should then be added to the block that is starting with ` } else if (tag.begins_with("img=")) {`, I guess.

```bbcode
[img region_w=16 region_h=16 region_x=16]res://icon.png[/img]la di da[img region_w=16 region_h=16]res://icon.png[/img]

la la ->[img region_w=16 region_h=16 region_y=16]res://icon.png[/img]<-
```

![richtextlabel](https://user-images.githubusercontent.com/1206026/137792550-3cda818a-2317-4c98-8484-385abe7b807e.png)


So for now I just leave this piece of code here for anybody who is interested 😉

**Comment by progsource** [comment]
Regarding bbcode API - what would be preferred?

* `[img region=0,0,32,32]res://icon.png[/img]`
* `[img region_size=32,32 frame=2]res://icon.png[/img]`
* `[img region_x=0 region_y=0 region_w=32 region_h=32]res://icon.png[/img]`

or something else?

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by progsource** [comment]
ping? ;)

**Comment by progsource** [comment]
So shall I just pick one of the possible APIs? ( I tend to the `[img region=0,0,32,32]res://icon.png[/img]` version)

**Comment by Calinou** [comment]
> So shall I just pick one of the possible APIs? ( I tend to the `[img region=0,0,32,32]res://icon.png[/img]` version)

This one sounds good to me. It needs to be concise after all, as I suppose referencing a spritesheet position is something you'll do often.
