### ISSUE TITLE
Import animations at the framerate (fps) used in the imported file (by default)

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot-proposals#3442]
### Describe the project you are working on

2.5D Platformer

### Describe the problem or limitation you are having in your project

When importing a mesh with animations, the framerate set on the import might not match the framerate of the animations, resulting in animations that are a little bit off due to interpolation (or have wasted keyframes for animations that have a low framerate).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Instead of having a set value for the import framerate, simply use the keyframe values that exist in the animation that was exported 1:1.  Maybe keep the set framerate behavior as an option for compatibility, but this just seems like a strange way to handle the process.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I actually had this implemented, but the gltf importer was completely rewritten in 3.3 or 3.4.  Easiest way to do it would be to figure out the fps of the animation and pass that in as the import fps, but ideally, it would use the exact keyframe values on the off chance somebody has some crazy animation software that allows for keyframes not snapped to a specific framerate.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You just have to remember with each file you import to set the framerate to match that which you had in blender or whatever software to use to animate.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core feature.  I don't think the importers can be modified with an addon.

**Comment by Calinou** [comment]
Isn't this a duplicate of https://github.com/godotengine/godot-proposals/issues/430?

**Comment by jitspoe** [comment]
*sighs* Yes, my memory is terrible.
