### ISSUE TITLE
Add a way to use a mathematically defined PointLight2D texture

### ISSUE THREAD

**Issue by nabfrew** [godotengine/godot-proposals#3444]
### Describe the project you are working on

A 2D drag and drop building game.

### Describe the problem or limitation you are having in your project

I find it a bit clunky tweaking the light shape, switching back and forth between editing and re-importing importing images. 

If the image textures cover a large area, they can be cumbersome as they get in the way of re-arranging other sprites as well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Being able to define a light with an image offers a lot of flexibility, but there are usually simple radial shapes you want for lights that can easily be mathematically defined and tweaked with a couple of parameters. This way the effect can be seen in real-time  in the editor as you adjust the parameters.

I would like to instead of adding a texture, select a predefined mathematical function and tweak it's parameters. I'm focused here on PointLight2D as I work in 2D, I don't know how lights work in 3D or weather this is applicable there as well.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Hopefully it can be accomplished with the same PointLight2D node, and selecting, say 'Gaussian' instead of Texture from the drop-down menu. 

Some useful presets might be: 

- An inverse square drop-off in intensity. This would need an inner saturation radius as a parameter, and some scaling factor to adjust the sharpness of the drop-off. 
-  A radial Gaussian drop-off in intensity, with a parameter to adjust the sharpness of the drop-off.
- No drop-off. Same intensity all the way to the edge of the screen.
- A plateau with a cut-off at fixed radius. A parameter could define how sharp the cut-off is.

For each of these, the following could apply:
- The peak intensity could be normalised to 1, and scaled by the light `energy` property. 
- A parameter limiting the light to within a certain angle might be useful as well (like a lampshade effect). An additional parameter could define if the angle cut-off is sharp or diffuse.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

These shapes can be created easily enough with image textures. But with a slower workflow, relying on other image editing software, and doesn't allow real-time feedback on the effect of changes.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure. I suppose a node type could be created that generates the textures from the parameters on the fly? The large textures would still get in the way in the editor, and I suspect it could be done more efficiently in core, but I'm no expert. In any case, I think a lot of people would enjoy having this out of the box.

**Comment by Calinou** [comment]
This is now implemented by [GradientTexture2D](https://github.com/godotengine/godot/pull/53234) (which supports linear and radial gradients), closing. GradientTexture2D will be available in 4.0 and 3.5.
