### ISSUE TITLE
Let "Ruler Tool" show position coordinates when clicking on the canvas

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot-proposals#3447]
### Describe the project you are working on

[Goost](https://goostengine.github.io/) - Godot Engine Extension.

### Describe the problem or limitation you are having in your project

When clicking on a single point in the canvas with "Ruler Mode", the following info is shown:

![image](https://user-images.githubusercontent.com/17108460/137952715-98e162d1-eb58-41d1-b03e-8f194b32cdce.png)

This information is not useful and frankly redundant, I need it to show position coordinates instead, for instance when I need to identify polygon coordinates in 2D (when no distance is measured).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow to show absolute position coordinates in the ruler tool.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/17108460/137953896-82a696a4-3207-472d-89bb-a817a4f78261.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's not practical to create an entire editor plugin for a convenience feature such as this.

### Is there a reason why this should be core and not an add-on in the asset library?

It's an editor feature.

**Comment by KoBeWi** [comment]
See also https://github.com/godotengine/godot/pull/47865

**Comment by Calinou** [comment]
> See also [godotengine/godot#47865](https://github.com/godotengine/godot/pull/47865)

If this proposal goes through, I think it would supersede https://github.com/godotengine/godot/pull/47865. It'll look less distracting when you don't use the Ruler tool.
