### ISSUE TITLE
Add the ability to rename files when installing an addon from the asset library

### ISSUE THREAD

**Issue by Nukiloco** [godotengine/godot-proposals#3449]
### Describe the project you are working on

A brick building sandbox game.

### Describe the problem or limitation you are having in your project

One of the current problems is that I'm using the ``addons`` folder for my default ``addons`` (not godot addons) that gets dynamically loaded into my game. Problem is when I want to install a godot addon, i typically try to install it in ``godot_addons``. There is one catch though. Currently i have no way to rename the folders or change where the files goes when installing an godot addon. This means that I have to install the addon, and move all the files which is tedious when installing a lot of addons.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A enhancement would be to make the ``Asset Installer`` to act in the same way as the ``FileSystem` where we can drag files around, move files, rename files, etc...

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My proposal would work where the ``Asset Installer`` would also act like how the current ``FileSystem`` dock works.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure exactly if the ``Asset Installer`` can be modified with a script to make it work.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think its possible currently to modify the ``Asset Installer`` with a script and not an addon in the asset library.

**Comment by Calinou** [comment]
> One of the current problems is that I'm using the addons folder for my default addons (not godot addons) that gets dynamically loaded into my game. Problem is when I want to install a godot addon, i typically try to install it in godot_addons. There is one catch though.

That seems like an unusual reason to rename Godot's `addons` folder. Can't you rename your project's expected add-ons folder instead (e.g. `packages`, `lib`, `modules`, …)?

**Comment by Calinou** [comment]
Closing due to lack of support (see general lack of activity here).
