### ISSUE TITLE
Add `Array.pick_random()` as a shorthand for `Array[randi() % Array.size()]`

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-proposals#3454]
### Describe the project you are working on

In most my games I sometimes have to pick a random element from an array (of cards, types of enemies, etc.).

### Describe the problem or limitation you are having in your project

To get a random element I have to do `array[ randi() % array.size() ]` while also checking that it is not empty, which impacts readability and can be error prone, especially if the array has a long name. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add `Array.pick_random()` (or any method name you think makes the most sense) as syntactic sugar for `Array[ randi() % Array.size() ]`

It makes the code easier to read, reduces errors and makes it more accesible to beginners since they have an easy way to get random elements without having to understand that randi() give any possible int value and how modulo is use to restrict those values. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A new pick_random() method will be added to arrays which does the Array[randi() % Array.size()] in C++. It could throw an error or return null for empty arrays. I'd like your input on which would be the best alternative. 

I can take care of implementing it since it's a simple enough change.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can, but it is something that will be used often.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a method addition to Array so it has to be core.

**Comment by Xrayez** [comment]
> I mentioned Array, does it makes sense to add pick_random() to all container types?

I've added support for `Dictionary` in goostengine/goost#140 at Goost, works alright and implementation-wise should be hopefully efficient enough using public API.

**Comment by gustavi** [comment]
Idea: a `pop_random()` method could be useful and implemented easily in the previous PR. It may be a dedicated proposal anyway.

**Comment by fire-forge** [comment]
I think this should be added to the `RandomNumberGenerator` class instead of `Array` so that it can be used to get consistent results with a seed. This is especially important for procedural generation.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/67444.
