### ISSUE TITLE
Enhance editor line length guide 

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#347]
**Describe the project you are working on:**

Breakout Clone

**Describe the problem or limitation you are having in your project:**

Currently Godot offers only one line guide that user can defined in settings by default set to 80 right now. This is great but sometimes it is beneficial to have more than one line guide many users will use something like soft limit and hard limit. Users will aim for majority of their code to don't extend over soft limit but will allow it at occasions. On the other hand the will never cross hard limit

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

It's fairly simple but will improve usability of the editor

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

Here is example how atom does it 
![1](https://user-images.githubusercontent.com/30668026/71695665-bace6480-2daa-11ea-9aa5-a31e2e35be6a.png)

**Describe implementation detail for your proposal (in code), if possible:**

I can imagine this as just replicating whatever code is used to create Line Length Guideline Column and giving it different value maybe allowing users to create more guildelines as they please?

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It would can be worked around by simply visually seeing code being roughly the desired length but it's nice to have

**Is there a reason why this should be core and not an add-on in the asset library?:**

It's part of a main editor and fairly easy to do.

**Comment by Calinou** [comment]
I can understand having a way to display two line length guidelines, but more than 2 sounds overkill to me.

**Comment by Feniks-Gaming** [comment]
2 is enough I agree.
