### ISSUE TITLE
Add support for defer callbacks

### ISSUE THREAD

**Issue by lfshr** [godotengine/godot-proposals#3474]
### Describe the project you are working on

MMO

### Describe the problem or limitation you are having in your project

Right now defers rely on strings to set the value of properties during idle time.

Is would be great if you could supply a callback to a `Defer` function, rather than having to rely on the strings required for `SetDeferred`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a Defer method that accepts an System.Action parameter. The callback action will be invoked during idle time.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```csharp
Defer(() => _collisionShape.Disabled = true);
Defer(() => _myNode.MyMethod(myParam));
```

Possible Implementation 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Can't think of a sensible way. Would need to make a node that proxied the requests.

### Is there a reason why this should be core and not an add-on in the asset library?

Too low level.

**Comment by blackholeearth** [comment]
none of the above worked.. in godot 4.4rc1 ide. 


this one works:

````c#
  Callable.From(MyMethod).CallDeferred();
````

**note:** google result broght me here.
