### ISSUE TITLE
Disable cut/copy/paste shortcuts when selecting keys in an animation track

### ISSUE THREAD

**Issue by MagdielM** [godotengine/godot-proposals#3475]
### Describe the project you are working on

A 3D prototype with animations authored in-engine.

### Describe the problem or limitation you are having in your project

Currently there is no support for copying and pasting individual keys in an animation track. This is understandable, but it also means that using the cut/copy/paste shortcuts performs these operations on the selected node rather than in the animation, which is very unintuitive. Several times I've cut the entire `AnimationPlayer` out of a scene while trying to cut and paste selected keys out of habit, and most recently I've lost an entire set of animations because I accidentally cut the node out of the tree and saved the scene, and my editor crashed shortly after (unrelated).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The shortcuts can be quite simply disabled when keys are selected in the animation editor. Perhaps a quick warning can also be displayed, telling the user that the shortcuts do nothing for animation keys. The point is that they should not cut the entire node when used while keys are selected.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The shortcuts do nothing when animation keys are selected, or warn the user that they have no effect.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The workaround would be to simply be more careful, but this is less a workaround and more just ignoring the issue.

### Is there a reason why this should be core and not an add-on in the asset library?

Addons can't modify the behavior of built-in editor windows, and even if they could, Godot's UX is important, and improving it probably shouldn't be delegated to external tools.

**Comment by CookieBadger** [comment]
This should no longer be an issue anymore, as all related shortcuts have been implemented in [#87250](https://github.com/godotengine/godot/pull/87250) and [#88350](https://github.com/godotengine/godot/pull/88350), and therefore the shortcuts actions cannot propagate up to the scene tree. Hence, this issue can be closed.

**Comment by Calinou** [comment]
Closing per the above comment.
