### ISSUE TITLE
Allow using `$/root` node paths without having to quote them in GDScript

### ISSUE THREAD

**Issue by Shawak** [godotengine/godot-proposals#3476]
### Describe the project you are working on

Generic project, not relevant to this proposal.

### Describe the problem or limitation you are having in your project

The dollar syntax to get a node is not consistent, because it breaks when using `/root`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow the usage of:
```gdscript
$/root/Level/Map
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change how [parse_get_node](https://github.com/godotengine/godot/blob/08d1ce718d5d1845c163f016b4083210136c1248/modules/gdscript/gdscript_parser.cpp#L2752) works, to make it work:
```cpp
GDScriptParser::ExpressionNode *GDScriptParser::parse_get_node(ExpressionNode *p_previous_operand, bool p_can_assign) {
	if (match(GDScriptTokenizer::Token::LITERAL)) {
		if (previous.literal.get_type() != Variant::STRING) {
			push_error(R"(Expect node path as string or identifier after "$".)");
			return nullptr;
		}
		GetNodeNode *get_node = alloc_node<GetNodeNode>();
		make_completion_context(COMPLETION_GET_NODE, get_node);
		get_node->string = parse_literal();
		return get_node;
	} else if (current.is_node_name()) {
		GetNodeNode *get_node = alloc_node<GetNodeNode>();
		int chain_position = 0;
		do {
			make_completion_context(COMPLETION_GET_NODE, get_node, chain_position++);
			if (!current.is_node_name()) {
				push_error(R"(Expect node path after "/".)");
				return nullptr;
			}
			advance();
			IdentifierNode *identifier = alloc_node<IdentifierNode>();
			identifier->name = previous.get_identifier();
			get_node->chain.push_back(identifier);
		} while (match(GDScriptTokenizer::Token::SLASH));
		return get_node;
	} else if (current.type == GDScriptTokenizer::Token::SLASH) {
		// TODO allow usage of /root
	} else {
		push_error(R"(Expect node path as string or identifier after "$".)");
		return nullptr;
	}
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Use `get_node()` instead.

### Is there a reason why this should be core and not an add-on in the asset library?

Because `$` is in the core.

**Comment by MarioLiebisch** [comment]
Maybe just me, but I'd argue that `$/Level/Map` would be more logical instead of `$/root/Level/Map`, given there are breaking changes anyway. Right now `/root` would be a unique identifier that's not really needed. Or am I missing something?

**Comment by rainlizard** [comment]
> 
> 
> Maybe just me, but I'd argue that `$/Level/Map` would be more logical instead of `$/root/Level/Map`, given there are breaking changes anyway. Right now `/root` would be a unique identifier that's not really needed. Or am I missing something?

``$/Level/Map`` is way too close to ``$Level/Map`` which is entirely different, it refers to the children of the node calling it, relatively. While /root/ is a direct path (not a relative path) that is always the same no matter which node is calling it.

**Comment by Shawak** [comment]
^this

Also `$"/root/Level/Map"` exists, and having a different behaviour in `$/` would be confusing.

**Comment by MarioLiebisch** [comment]
Yes, they'd obviously both have to change, but then again might be way more confusing for existing users. So yeah, let's scrap that idea. 😉

**Comment by vnen** [comment]
> Maybe just me, but I'd argue that `$/Level/Map` would be more logical instead of `$/root/Level/Map`, given there are breaking changes anyway. Right now `/root` would be a unique identifier that's not really needed. Or am I missing something?

`/root` is an actual node that can be referenced (it is the main window of the running project). It might technically have a different name, since nothing stops you from renaming it. While it could be that `$/` refers to the root node, usually we don't hide this details from user, so I'd rather keep the `root` there in this case.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/54358.
