### ISSUE TITLE
Blank space after end of code in text editor

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot-proposals#3482]
### Describe the project you are working on

Lots of mini-projects for jams, and a larger platformer. I use GDScript a lot and the built-in text editor.

### Describe the problem or limitation you are having in your project

I use the GDScript editor a lot since it's pretty convenient.

On small problem for me though is when I'm writing near the bottom of the text editor. I usually want my code to be near the middle to the top of the screen. However, when you fill the screen space in the text editor, and you're writing code near the bottom of the file, it's not possible for the scroll the code anymore because there's no text beneath it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think having an extra "page" of blank space to the editor that isn't newlines would solve the issue. It could be an option in the Editor Settings, say, "Blank Lines After End" or it could just be a set constant amount.

This would allow the text editor to scroll more despite there being no more text.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

VSCode does this:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/4584511/139509874-2dc93efb-4511-4c0c-afd3-3b907667e735.png">
You can see the line numbers end but there's still blank space beneath the code. This allows me to scroll the bottom of the code to the top since there's extra blank space.

In Godot, I can't scroll down anymore after the last line:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/4584511/139510183-b1be4346-aa4c-42cd-a118-0b208161752f.png">

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around by adding a bunch of new lines to the end of the file. However, this bloats the file line count and is a bit messy. Almost all my GDScript code on github has a bunch of extra new lines a the end if I forget to delete it after.

### Is there a reason why this should be core and not an add-on in the asset library?

Blank space after the end I think is pretty common in modern text editors and seems pretty easy to add. Seems like a very small but nice upgrade is all. A very low hanging fruit, if you will.

**Comment by Calinou** [comment]
This is already available as an option in the Editor Settings: **Text Editor > Cursor > Scroll Past End Of File**.
