### ISSUE TITLE
Expose `CapsuleShape2D::_get_points()` to GDScript

### ISSUE THREAD

**Issue by fire540** [godotengine/godot-proposals#3495]
### Describe the project you are working on

A 2D top-down shooter game

### Describe the problem or limitation you are having in your project

There is a capsule-shaped object in my game. I am trying to add light occlusion to it, but there is no way to use a `Shape2D` for light occlusion, only a polygon. In order to have accurate light shadows, I would need to generate a polygon that closely matches the `CapsuleShape2D` used in the object's `CollisionShape2D`. 

I would have just made a proposal for using `Shape2D`s as light occluders, but that would be a lot more work for the developers than just exposing one already existing function to GDScript.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If you zoom in on a `CapsuleShape2D` in the 2D editor, you'll notice that is made out of a polygon. I did a bit of digging, and found that the C++ script for `CapsuleShape2D` has a function for getting the points. This is used for drawing the collision polygon in the editor and when "Visible Collision Shapes" is enabled. However, this function is not accessible from GDScript. 

![image](https://user-images.githubusercontent.com/67974470/140256821-83f570f3-4aaf-411d-a814-6fda73a827f5.png)

This is the `capsule_shape_2d.cpp` script in the Godot engine code. `_get_points()` is the first function in the script.
https://github.com/godotengine/godot/blob/5b306859767d511a02618ae88a4da5fb15c9e202/scene/resources/capsule_shape_2d.cpp

```gdscript
Vector<Vector2> CapsuleShape2D::_get_points() const {
	Vector<Vector2> points;
	const real_t turn_step = Math_TAU / 24.0;
	for (int i = 0; i < 24; i++) {
		Vector2 ofs = Vector2(0, (i > 6 && i <= 18) ? -height * 0.5 + radius : height * 0.5 - radius);

		points.push_back(Vector2(Math::sin(i * turn_step), Math::cos(i * turn_step)) * radius + ofs);
		if (i == 6 || i == 18) {
			points.push_back(Vector2(Math::sin(i * turn_step), Math::cos(i * turn_step)) * radius - ofs);
		}
	}

	return points;
}
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The `CapsuleShape2D::_get_points()` method would be exposed to GDScript as `CapsuleShape2D.get_points()` or `get_polygon()`, and it would return a `PoolVector2Array` of points.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am currently in the process of converting the C++ code from the engine to GDScript, but since the function already exists in the engine I don't see why it shouldn't be accessible to GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

The function already exists in the engine, it is just a matter of adding bindings for GDScript to access it. Also, I think this is far too small of a feature to constitute an entire add-on. ,

**Comment by fire540** [comment]
I wrote a GDScript function for this. I wasn't able to convert the C++ code to GDScript because I don't completely understand how it works, but what I made does the same thing. And you're able to customize the number of points at each end, so this might even be better.

```gdscript
static func generate_capsule_polygon(end_points: int, radius: float, height: float) -> PoolVector2Array:
	var polygon: = PoolVector2Array()
	
	var i_divisior: = float(end_points - 1)
	for i in end_points:
		polygon.append(polar2cartesian(radius, (float(i) / i_divisior) * PI) + Vector2(0, height / 2))
	for i in end_points:
		polygon.append(-polar2cartesian(radius, (float(i) / i_divisior) * PI) + Vector2(0, -height / 2))
	
	return polygon
```

![image](https://user-images.githubusercontent.com/67974470/140260797-6acebbf8-ffd3-42ff-a0c3-1892436fff5e.png)


Not sure if I should close this or not, as it still might be useful to someone.

**Comment by Calinou** [comment]
cc @pouleyKetchoupp

**Comment by Xrayez** [comment]
I've been working on implementing CSG-like nodes in [Goost](https://goostengine.github.io/), and recently worked on `PolyCapsule2D` shape, see goostengine/goost#134, so you can refer to my own C++ implementation for generating capsule polygon there. Also, the code takes into account max arc error to determine point count for semicircles in such a way so that accuracy is not lost with different radius, and or max error could be configured to improve performance in expense of accuracy.

You can refer to https://github.com/goostengine/goost/blob/3772da12b19d433473ce3e5f782a3290e664a3ff/core/math/geometry/2d/goost_geometry_2d.cpp for both circle and capsule generation methods.

My vision is that those nodes could be used for various purposes: navigation, collision shapes, light occluders etc. But of course, being able to get polygon representation of `Shape2D` could certainly be useful, it's not really limited to `CapsuleShape2D`.
