### ISSUE TITLE
Use different icons for AnimationPlayer editor keyframes depending on the keyframe's easing type

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#3496]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

It's hard to see which keyframes are linear and which ones are non-linear in a given animation. You have to hover/click on each key to see their easing value.

Here, the first key has linear easing but the second key has in-out easing:

![image](https://user-images.githubusercontent.com/180032/140304647-b11580b0-5907-4f31-869d-c139704bc297.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To improve the distinction between different key easing values, use different icons for AnimationPlayer editor keyframes depending on the keyframe's easing type.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For instance, keys with non-linear easing could have a square appearance:

![image](https://user-images.githubusercontent.com/180032/140304756-c2e36d16-fccd-4ee3-9e9f-7338641d534b.png)

This would mimic the appearance of smooth line points in editors such as Inkscape and [Godot's Path2D editor](https://github.com/godotengine/godot/pull/31466).

Other options can also be considered, such as a slightly different color (which would also map nicely to any easing value, rather than being limited to a linear/non-linear dichotomy).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

No, as the animation editor icons can't be changed by an add-on.

**Comment by MaaaxiKing** [comment]
I think the square should then have the same size as the rhombus, so it's just rotated.
