### ISSUE TITLE
Download export templates on the background

### ISSUE THREAD

**Issue by Juankz** [godotengine/godot-proposals#35]
**Describe the project you are working on:**
3D traffic educational game, it matters for all projects tho
**Describe how this feature / enhancement will help your project:**
When downloading a export template from the editor can't close the dialog until it finishes the download (or else the download is lost), as the size is >400MB it takes some minutes, time where I can't work on the project.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
It can be a small download bar at the bottom Or/and a notification when the download has finished.

![Untitled Diagram](https://user-images.githubusercontent.com/18577412/64364670-00d01300-cfd9-11e9-8b58-3dbfc2756f23.jpg)

**Describe implementation detail for your proposal (in code), if possible:**
I'm not that familiar with godot source code
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Usually I go to godot website, download the export templates and install from file, it works but it is not a seamless experience.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a one time use for each godot version. Downloading an addon is a worthless extra step. This can be low priority but I think would be a small welcome addition. If someone is willing to guide me I could code it

**Comment by reduz** [comment]
well, technically you can open another Godot instance and do it :P

**Comment by Juankz** [comment]
>  well, technically you can open another Godot instance and do it :P

Never crossed my mind

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/48902, closing.
