### ISSUE TITLE
Add `String.invert()`/`reverse()`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#3503]
### Describe the project you are working on

Plugins

### Describe the problem or limitation you are having in your project

I need to invert a string but I can't to do this simply and efficient.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding `String.invert()`/`String.reverse()` would solve the problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The method would return new inverted string
`"hello".invert()` would give `"olleh"`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There are some workrounds, for example
```gdscript
static func invert_string(s:String)->String:
    var chars_pool = PoolStringArray()
    var length = s.length()
    chars_pool.resize(length)
    for i in length:
        chars_pool[i] = s[i]
    chars_pool.invert()
    return chars_pool.join("")
```
This doesn't look efficient tho

### Is there a reason why this should be core and not an add-on in the asset library?

Inverting strings is quite frequent task when working with text. For example in Python you can use `[::-1]` to do this.

**Comment by me2beats** [comment]
Updated the workaround example. It still requires using loop in gdscript.
First of all I tried `split()` but it doesn't work with empty delimiter.

**Comment by Calinou** [comment]
> First of all I tried split() but it doesn't work with empty delimiter.

See https://github.com/godotengine/godot/pull/21699 which was rejected.

**Comment by AThousandShips** [comment]
I also want to suggest this trivial workaround in 4.x:
```gdscript
func reverse(arg: String) -> String:
	var arr := arg.to_utf32_buffer().to_int32_array()
	arr.reverse()
	return arr.to_byte_array().get_string_from_utf32()
```
