### ISSUE TITLE
Implement one-click deploy for iOS

### ISSUE THREAD

**Issue by clofresh** [godotengine/godot-proposals#3506]
### Describe the project you are working on

An iOS game

### Describe the problem or limitation you are having in your project

The feedback loop from making a change to seeing it deployed on my iOS device is too slow. When you export to iOS, you just get an ipa file, and newer users won't know how to get it onto a device. Additionally, if your Apple developer certificate isn't set up correctly, the export will silently fail before even creating an ipa.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a one click deploy button for iOS the same way one shows up for Android when you plug an Android phone in. Add some extra contextual help for getting the build to run on the device.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There's been some prior work in an older issue: https://github.com/godotengine/godot/issues/2703

I'm assuming something involving ios-deploy and libimobiledevice.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You won't see anything different if you never plug in an iOS device.

### Is there a reason why this should be core and not an add-on in the asset library?

iOS export is already part of the core editor, but there's extra steps to deploy the ipa on the device and run it.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/26263 and https://github.com/godotengine/godot/pull/33086.

**Comment by YuriSizov** [comment]
This was implemented for 4.2, should be closed.
