### ISSUE TITLE
Add a Color property for detail map in BaseMaterial3D

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#3507]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Been Playing around with materials, and I noticed that Detail Albedo Doesn't have Color property, which the Normal Albedo does.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add Color Property for Detail Albedo, This would add more flexibility to Materials and shouldn't be hard to implement or degrade performance in any significant way.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same as the Albedo is affected by it's Color Property in Standard Material

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Materials are Core.

**Comment by Calinou** [comment]
I'd say modulating a detail map's color is a very uncommon need. It's not something you'll need to do on a majority of your materials in any game I can think of. You can use a custom shader if you need something like that.

**Comment by mrjustaguy** [comment]
Personally I can't think of many cases where this would be needed, and the only thing that comes to mind is for texture re-use if you've got 2 textures that need color changing which could be the case for Terrains for example a Muddy Texture with Grass Details, or Grass with Flower Details, where you might want to reuse the textures, but change the color a of both elements to get a slightly different feel, or in Strategy games if you've got Team Colors as one Texture, and some other texture that you also need to change colors for whatever reason at the same time.

Honestly, I made this proposal more because it seems logical that both layers can get the same options.

**Comment by mrjustaguy** [comment]
Closing due to lack of interest and an easy workaround was found by converting from Standard Material to Shader and minimal tweaking to the resulting shader.
