### ISSUE TITLE
Add tagging system to Project Manager

### ISSUE THREAD

**Issue by IntangibleMatter** [godotengine/godot-proposals#3513]
### Describe the project you are working on

Godot project manager

### Describe the problem or limitation you are having in your project

I'm learning the engine and have many different tutorial/demo projects that I don't want to delete that are clogging my project manager.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

What I propose is a tagging system, which can be used to better sort all the projects in the manager. It allows you to add tags to all your projects so you can quickly sort through and find the project that you forgot the name of, but you remember that it was made from a tutorial and had cats in it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![project manager tags](https://user-images.githubusercontent.com/47702559/140620607-bb3ae348-81db-4d76-b593-5161b9a0931b.png)

You add a section which displays a few of the tags to every project in the project manager, or you could display them in a little panel in the sidebar. This would allow for easier filtering and finding of projects in the Godot Project Manager

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, unless you write your own project manager.

### Is there a reason why this should be core and not an add-on in the asset library?

Because the project manager can't have add-ons, and most Godot users would likely use this feature if presented with it.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/2329.

**Comment by LordDestral** [comment]
Excellent. Add the ability to group projects under folders, and leave comments on projects, and I'm sold.

**Comment by Calinou** [comment]
> Excellent. Add the ability to group projects under folders, and leave comments on projects, and I'm sold.

You can already add a description to each project in the Project Settings. It's displayed as a tooltip when hovering a project in the project manager. (Since there isn't enough space to display the description anywhere else, we had to settle for a tooltip).

**Comment by IntangibleMatter** [comment]
Using Either Folders or tags would make things 1000x easier for everyone. I would take this on myself if I knew C++ and the full layout of the project, but I don't :/

I wonder how hard it would be to learn the specific stuff needed to add this feature....

**Comment by dalexeev** [comment]
See https://github.com/godotengine/godot-proposals/issues/2329#issuecomment-968751134.

**Comment by IntangibleMatter** [comment]
Closed by godotengine/godot#75047
