### ISSUE TITLE
Backport node grouping and locking shortcuts to `3.x`

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot-proposals#3516]
### Describe the project you are working on

3D open world game.

### Describe the problem or limitation you are having in your project

Clicking in the editor can be tedious at times, especially for making worlds in 3d with a lot of props. The "Make sure the object's children are not selectable" is a good feature, however, in an organized tree structure, it is a pain to activate/deactivate this bit, especially if you are using it a lot

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If a shortcut was added, you could simply click each node, and very effortlessly disable/enable this feature, reducing tedious nature.

It was awkward finding that this, along with several other 3d features have no option to bind them to shortcuts, despite the logic (for instance, lock node/movement also has no shortcut)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simply add a new shortcut for "Make sure the object's children are not selectable".

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Improves usability of 3d Editor. Most of the 3d features have shortcuts, so it would make sense for this feature among several others to have at least the option to bind a key to it.

**Comment by stryker313** [comment]
https://user-images.githubusercontent.com/83078010/140779451-fc270837-fc0b-40d2-9bc2-1cef73f95f6b.mp4

**Comment by Calinou** [comment]
[Shortcuts for locking and grouping nodes are already implemented in `master`](https://github.com/godotengine/godot/pull/50038), but it wasn't backported to `3.x` yet.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/54786.
