### ISSUE TITLE
Add a warning when assigning to a read-only variable

### ISSUE THREAD

**Issue by nabfrew** [godotengine/godot-proposals#3519]
### Describe the project you are working on

not relevant.

### Describe the problem or limitation you are having in your project

I got stuck trouble-shooting something for quite some time because I misunderstood how set/get properties worked. I had only given a property a getter function without a setter, not realising that would make it ignore all assignments to the property.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A hint that I was assigning a value would have made debugging easier.

Of course, it's by no means essential, but helps debugging, prevents mistakes, and improves user friendliness. Particularly if you're new to the language.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An editor warning when a script assigns a value to a read-only variable

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If you knew to write a few lines of scripts for the warning you wouldn't need the warning.

### Is there a reason why this should be core and not an add-on in the asset library?

if you knew to download the add-on you wouldn´t need the warning.

**Comment by Calinou** [comment]
There is no concept of "read-only variable" in Godot (other than `const` in GDScript, but it's not considered a variable in terms of semantics).

Built-in read-only properties are being removed in 4.0 in favor of getter methods, so this won't be needed anymore in 4.0 for built-in nodes.

**Comment by nabfrew** [comment]
Apologies, maybe I'm using the wrong terminology. Or is this a bug I've found then? When I run this script, it prints `0`, not `1`. 

```
extends Node2D

var foo : int:
	get:
		return foo

func _ready():
	foo = 1
	print(foo)
```

This is on v4.0.dev.20211027.official [157cba393]
I couldn't find any definitive documentation on how it was implemented in the end, it's a lot of discussion to read to work out what was settled on in the proposal: https://github.com/godotengine/godot-proposals/issues/844

**Comment by KoBeWi** [comment]
It's a bug. The variable should use default setter if user hasn't defined any.

**Comment by nabfrew** [comment]
@KoBeWi i see, is it a known bug or should I report it?

**Comment by KoBeWi** [comment]
I couldn't find any report, so yeah. I'll close it, open a new issue on the main repo.
