### ISSUE TITLE
Add support for importing and exporting `.blend` files

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#3529]
### Describe the project you are working on

3d multiplayer game.

### Describe the problem or limitation you are having in your project

Currently it takes 3-5 steps to go from Blender to Godot.

1. Open blender
2. Work
3. Save as gltf
4. Place the gltf file in the Godot Engine project directory
5. Press save button

The reverse of gltf exporting is true too.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature lets you drag or place `.blend` files in the project folder and it will import the files.

An editor setting sets the location of the blender binary. A empty setting means the feature is disabled.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. Add an editor setting to define the Blender path.
2. Set the editor setting so the file system browser works
3. Open the blend file via the command line without a py.
4. Save the blend as a gltf in the .godot/imported folder
5. Open in gltf importer

Symmetrical steps for saving as blend.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Was an addon until Reduz asked for me to port it. 

### Is there a reason why this should be core and not an add-on in the asset library?

Reduz thought blend i/o should be core instead of an addon.

**Comment by Calinou** [comment]
Is exporting `.blend` files from Godot really needed? Isn't the Blender glTF importer good enough for most use cases?

**Comment by fire** [comment]
The goal of Blender import and export is to reduce the number of steps in the workflow. `.blend` import and export can all be done manually and is error prone.

Here's the reverse.

1. Export as gltf from Godot Engine
2. Open blender
3. Open blender import dialog
4. Find the gltf in the Godot Engine project folder
5. Error prone settings managment on gltf import 
6. Press import

**Comment by mrjustaguy** [comment]
I think opening and saving `.blend` files in Godot actually makes a ton of sense if done right, as it is not totally uncommon for something to go wrong with Blender Exports, albeit much rarer these days, so having the option to open Blender's own files (sort of as a fallback) could help in such situations, instead of trying to figure out what went wrong and/or switching export file type in blender and hoping for the best.

**Comment by ngreve** [comment]
Being able to directly import a blend file and iteratively making Godot more compatible with Blender, would very likely be a massive advantage, compared to other game engines.

What I am looking for in particular, is a way to manipulate the geometry node inputs of a Blender model, from within Godot, to be able to use them for animations.

There is already an Unreal Engine Addon available, called [Altermesh](https://altermesh.com/), which provides such a feature. [Gamefromscratch also talked about it](https://youtu.be/IvAZXnK8xcU?t=351).

**Comment by GeorgeS2019** [comment]
@ngreve Please check this [repos](https://github.com/jarneson/godot-ply), perhaps it is relevant to what you have suggested.

**Comment by Zireael07** [comment]
This (awesome repo) is about modeling in editor, not about Blender import

**Comment by GeorgeS2019** [comment]
@Zireael07 Currently this discussion is more about .Blend import as GLTF. 
Godot4 alpha 1 article discussed about [Improved 3D Scene Importer](https://github.com/godotengine/godot/pull/52541)

>Godot 4 comes with a [dedicated import dialog](https://github.com/godotengine/godot/pull/47166) that allows you to preview and customize every part of the imported scene, its materials and physical properties. **Scripts can still be used for additional tweaks,**

It is here I see opportunity to improve the scope of .Blend import beyond current scope of GLTF and HOW project like ply may eventually evolve to contribute to that needed feature.

**Comment by Xartorx** [comment]
It would be awesome to be able to import materials directly from .blend file bypassing GLTF format, because currently GLTF doesn't support some things (e.g. subsurface scatter or clearcoat).

**Comment by Calinou** [comment]
> It would be awesome to be able to import materials directly from .blend file bypassing GLTF format, because currently GLTF doesn't support some things (e.g. subsurface scatter or clearcoat).

I don't think this will ever be feasible, as `.blend` is not an interchange format. We also have no plans to use Assimp (which *can* read `.blend` files directly, but as I said, it's ill-advised).

**Comment by fire** [comment]
As someone who is writing a .blend importer for Godot Engine via blender executable. I also second that we will not be using ASSIMP for blender import.
