### ISSUE TITLE
Disable multitouch

### ISSUE THREAD

**Issue by SmithJohnFirst** [godotengine/godot-proposals#353]
I develop various applications for mobile devices (Android/iOS).
In many situations, it is necessary to limit the operation of the screen on mobile devices with just one touch. 
For example, if we have several objects with which we can interact. Since multitouch always on, a situation may arise when multiple objects are selected. This breaks the logic of the application and creates many problems.

Godot does not allow you to disable multitouch.
We need a mechanism similar to `Input.multiTouchEnabled = false;` in Unity.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by vnen** [comment]
Note that if you use a mouse abstraction, only one touch will be detected. You can also make sure to only get the index `0` (first touch) and ignore the rest.
