### ISSUE TITLE
Allow turning GDScript warning categories into errors individually (instead of a global setting)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#3531]
*Related to https://github.com/godotengine/godot-proposals/issues/3284.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

It's not currently possible to turn a single GDScript warning category into an error. Instead, you can only enable warning-to-error conversion for *all* enabled warnings in the Project Settings.

See https://github.com/godotengine/godot/pull/54883 for context.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow turning GDScript warning categories into errors individually, instead of only having a global setting that enables all warning-to-error conversions. This allows for greater control, especially when only some warnings can be turned into errors without harming productivity too much.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change boolean warning properties to an enum with 3 values:

- **Ignore** (default for the currently disabled warnings)
- **Warning** (default for the currently enabled warnings)
- **Error**

Then remove the warnings-to-errors project setting, as it won't be needed anymore.

To improve the robustness of GDScript code written by users, we can consider making some warnings errors by default. However, this is likely better discussed in a separate proposal.

This configuration behavior is consistent with linters such as [ESLint](https://eslint.org/).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as the GDScript parser is implemented in C++ and its behavior can't be overridden with extensions.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by Xrayez** [comment]
I would definitely use this feature for treating #3463 an a error.

**Comment by hilfazer** [comment]
> To improve the robustness of GDScript code written by users, we can consider making some warnings errors by default. However, this is likely better discussed in a separate proposal.

Good idea. I'm against this particular suggestion but not against this proposal in general.

**Comment by filipworksdev** [comment]
You could do something like this  

![image](https://user-images.githubusercontent.com/36826319/146630733-c46ff89c-79ba-434d-ba08-c5f6626d05b5.png)

**Comment by Calinou** [comment]
> You could do something like this
> 
> ![image](https://user-images.githubusercontent.com/36826319/146630733-c46ff89c-79ba-434d-ba08-c5f6626d05b5.png)

This would make the inspector code more complicated for little benefit. It would also allow setting up conflicting options (warning disabled but "as errors" enabled). I think using enum properties is the way to go here.

**Comment by filipworksdev** [comment]
Yeah maybe is a bit much you are right. Enum properties I assume would show up for some of the Warnings in place of a checkbox?
