### ISSUE TITLE
Add an option to make a copy while importing external 3D scenes

### ISSUE THREAD

**Issue by sygi** [godotengine/godot-proposals#3536]
### Describe the project you are working on

A project where the 3D modelling is done in Blender, and the final scenes are imported to Godot.

### Describe the problem or limitation you are having in your project

While importing the 3D scene, Godot shows two options:
1. "Open anyway" without ability to modify
2. "New inherited" which creates an inherited scene.

![3d scene open prompt](https://i.ibb.co/cx496Wt/Screenshot-from-2021-11-11-16-06-11.png)

The scenes I import often require further editing (eg. lights from blender are imported as generic Spatial node). Neither of the available options offer convenient editing: the inherited scene has limitations: one cannot delete or rename the nodes (as they are preserved in the base file) or change the type. The reasonable alternative: creating an inherited scene and breaking the inheritance is hidden from a new user.

I believe storing a copy is a reasonable default (this is what the 3D modelling software does: it saves the imported scenes in its own format instead of trying to keep a file with differences), and should be shown to the user early on.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add another option "Copy to Godot" to the 3d scene import prompt which will work as creating an inherited scene and breaking the inheritance.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same dialog as above, but with 4 buttons instead of 3.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be used whenever one imports a 3D scene.

### Is there a reason why this should be core and not an add-on in the asset library?

This can well be implemented as an add-on, but the premise of the proposal is not as much workflow improvement (1 click instead of 2), but mostly to give users who may not be aware of inherited scene limitations access to working default import.

**Comment by Calinou** [comment]
The 3D import workflow in 4.0 has changed, and making an inherited scene is no longer recommended. There's a new **Advanced Import Settings** dialog where many more things can be configured compared to before.

The issue with copying a scene is that any further changes made in the 3D DCC won't be reflected, and you'll have to make all the changes again from scratch if you ever need to import the scene again. This is bad for productivity, and destructive workflows should be discouraged whenever possible.

**Comment by sygi** [comment]
Glad to hear things are changing/improving!

I tend to disagree with the absolute statement "destructive is bad"; there is a cost to re-using the previous scene in expressiveness of the difference vs the original format. Assuming that the problems I mentioned (inability to change the type or remove a node in inherited scenes) are genuinely there, there is literally no way of adjusting the scene other than going back to the original file and editing it elsewhere which is also a productivity hurdle and there's a tradeoff between it and the benefits of reusing the scene.

For example, Blender resolves it to use the destructive workflow (when you import .glft blender will save .blend) and I suspect other 3D software does the same.

> Which source format are you using? As far as I know, lights are supported by the glTF importer 
Thanks for letting me know they should work! I was using glb; let me double-check what works/doesn't with gltf and open an issue if they don't work as expected (is there a list of supported features somewhere?).

As my proposal is somewhat obsolete, let me close this issue and reopen/create a new one if I have suggestions for improvement to the new import workflow.
