### ISSUE TITLE
Add a Setting to Ignore Internal Soft Shadow Blur Multiplier to Project Settings

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#3538]
### Describe the project you are working on

3D Game Settings

### Describe the problem or limitation you are having in your project

Soft Shadows internally change the Blur quantity, which some users might not desire.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a project setting for this option would allow for consistent Shadow Blur Level across different Soft Shadow Qualities (if not disabled) at the cost of grainier appearance

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a Project Setting "Adjust Blur by Soft Shadow Quality"

On would adjust like it does now - Default
Off would not apply Blur multipliers that it currently adds with Soft Shadow Quality Settings

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The only way I can think of doing this, is to constantly propagate a call to lights from the root node, which is bad for performance, or to have each light have a script, which would be very user-error/bug prone

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be made as an addon efficiently.

**Comment by Calinou** [comment]
If you turn off soft shadows entirely, then all shadows become hard regardless of their blur multiplier or light size. I believe this is sufficient to cater to low-end platforms.

A global toggle for point light shadows is a good idea, but I think this could be handled by a LOD system once it's added. You could adjust the LOD bias to fade out shadows early on low-end platforms.

**Comment by mrjustaguy** [comment]
1) Blur multiplier isn't because of performance, Soft Shadow Quality is. The issue is Soft Shadows inherently mess with the Blur multiplier, which May be undesired, and there should be a way to counter it, project wide.

also now that I've forgotten about you being able to set quadrants to disabled so general lights (Omni and Spot) can be disabled project side, and I guess Directional lights can be done manually, as usually they aren't spawned in, and are almost always a part of level design, so they can easily get scripts to deal with turning shadows on/off

I'm adjusting the proposal above in regards to that.

**Comment by mrjustaguy** [comment]
Closed in favor of https://github.com/godotengine/godot-proposals/issues/5728 which solves this and adds another useful feature not present with this proposal
