### ISSUE TITLE
Add more consistency checks in inherited scenes

### ISSUE THREAD

**Issue by sygi** [godotengine/godot-proposals#3540]
### Describe the project you are working on

A project with two scenes: A, B where B inherits from A. B has one child node called "Camera2D", A has no child nodes:
![inherited node](https://i.ibb.co/PwNPdFL/Screenshot-from-2021-11-13-10-31-44.png)

### Describe the problem or limitation you are having in your project

After adding a child node with the name "Camera2D" to the A node:
![A node](https://i.ibb.co/zJbhnPY/Screenshot-from-2021-11-13-10-30-28.png)

Godot doesn't complain, rather puts node B in an inconsistent state where two nodes have the same name:
![B node](https://i.ibb.co/hVGTR4h/Screenshot-from-2021-11-13-10-30-57.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

An alert window preventing user from modifying base scene in a way that puts inherited scenes in inconsistent state or a way to rename the child nodes in the inherited scene even if the name matches two nodes.

Note that the feature is related, but not the same as, #518.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An alert "can't create a node with name 'X'/rename node to 'X', as there is an inherited scene node with this name".

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Proposal is not adding a feature but preventing the engine from getting into an inconsistent state.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, this is about core functionality.

**Comment by KoBeWi** [comment]
This is actually a bug: https://github.com/godotengine/godot/issues/26390
