### ISSUE TITLE
Saving a scene for the first time should automatically format the name to snake_case

### ISSUE THREAD

**Issue by spindlebink** [godotengine/godot-proposals#3553]
### Describe the project you are working on

Puzzle game for Game Off 2021.

### Describe the problem or limitation you are having in your project

When creating a new script on a node or saving a scene inherited from an imported model, Godot (as far as I can tell) pre-formats the name to match the `snake_case` style guide for filenames. (Edit: on further exploration, looks like it defaults to the name of the scene.) But when creating a new scene and then saving it, Godot uses the unformatted root node name as the filename by default.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Saving a new scene with root node `MainInterface`, for example, would default to `main_interface.tscn` instead of the current `MainInterface.tscn`. It's a minor adjustment, but it would aid in consistency and seamlessness of workflow.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Whatever functionality is currently in place for script names and resources could be applied to saving new scenes.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Since the default scene name is part of the core engine, it can't be.

### Is there a reason why this should be core and not an add-on in the asset library?

Default scene name is part of the core engine.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/1211 (which is for scripts).

**Comment by dalexeev** [comment]
Done: dalexeev/godot@b75608856d08f7a9deaa68de04b62033ef1e3139. But I suggest adding an editor setting to control this behavior. There is a similar setting for node names. See also godotengine/godot#52997. I think the naming should be configurable for both scenes and scripts.

**Comment by Jummit** [comment]
Would be fixed by godotengine/godot#52597

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/52597, closing.
