### ISSUE TITLE
Remove hoover signal( and any default signals) 

### ISSUE THREAD

**Issue by cloa513** [godotengine/godot-proposals#3566]
### Describe the project you are working on

A sudoku game with extensive use of buttons

### Describe the problem or limitation you are having in your project

My created button constantly switches to some default image whenever I mouse over it. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Eliminate any default mouse signals for buttons. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Excellent I will be in control of game not you 
func _pressed():

	var newTile=Button.new()
	newTile.set_script(nT)
	newTile.visible=false
	get_parent().add_child(newTile)
	newTile.rect_min_size=Vector2(75,75)
	spawnpoint=spawnlocn-Vector2(25,25)
	newTile._init3(spawnpoint,num,Color( 0.75, 0.75, 0.75, 3))
	newTile.set_global_position(spawnpoint)
	newTile.text=str(num)
	newTile.add_color_override("font_color",Color( 0.75, 0.75, 0.75, 3))
	var stylebox_flat := StyleBoxFlat.new()
	stylebox_flat.bg_color =Color(1, 1, 1, 1)
	newTile.add_stylebox_override("normal", stylebox_flat)

	newTile.visible=true

func _init3(_spawnpoint:Vector2,_num:int,_ntcolour:Color):
	sp=_spawnpoint
	num=_num
	c=_ntcolour
	connect("focus_entered",self,"disablefocus")
# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
func disablefocus():
	text=str(num)
	add_color_override("font_color",Color( 0.75, 0.75, 0.75, 3))
	var stylebox_flat := StyleBoxFlat.new()
	stylebox_flat.bg_color =c
	add_stylebox_override("normal", stylebox_flat)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I had to work out what the problem with multiple forum posters couldn't do. 

func _ready():
	var stylebox_flat := StyleBoxFlat.new()
	$Button.add_stylebox_override("normal", stylebox_flat)
	$Button.add_stylebox_override("hover", stylebox_flat)

### Is there a reason why this should be core and not an add-on in the asset library?

It should never have occurred.

**Comment by pycbouh** [comment]
> My created button constantly switches to some default image whenever I mouse over it.

Yes, buttons, like any other control, need to be styled for various states, be it normal, pressed, or hover. This has nothing to do with signals.

You can read more about GUI skinning in documentation [here](https://docs.godotengine.org/en/stable/tutorials/gui/gui_skinning.html), including how to do it with the [theme editor](https://docs.godotengine.org/en/stable/tutorials/gui/gui_using_theme_editor.html).

**Comment by cloa513** [comment]
It triggers hover when created.

**Comment by cloa513** [comment]
It has a stylebox when created.

**Comment by pycbouh** [comment]
Yes, all controls have styles by default, because otherwise people would not be able to use them as is and would need to extensively modify their UI theme even before starting to work on the project. There are always going to be some default styles and values.

**Comment by cloa513** [comment]
I didnt ask to activate that controln nor any other mouse controls. it just
suddenly changed from my preset Stylebox set  image black writing on white
writing on black  because the mouse was there.Hence that signal should be
deactivated by default as should all the others. It should the game
designer's choice to have any mouse input controls set the display of a
button. Hence please reopen my proposal. Many programmers on forums had no
idea why this behavior was happening.

**Comment by pycbouh** [comment]
If you want to disable mouse input on the button, you can disable the button or set its mouse filter property to `ignore`. Note that users normally want to be able to interact with buttons that look active. And for the disabled state you would also need to provide a separate stylebox, otherwise the default style will be used.

**Comment by cloa513** [comment]
That is for the game designer to decide how to allow the user to interact
with the buttons- it shouldnt be some internal GODOT engine workings. I am
t using buttons as both the game and  control system. I was told I couldn't
disable hoover with mouse- thats ridiculous. The default should be no
interaction. The game designer adds the controls that they want so they at
least expect something to happen (it wasnt some bug instead) I didnt know
that this hoover event was mandatory.

GODOT should be a game making tool not prescribing how games work. How
would you like if.someone changed how persoal computer worked.

**Comment by pycbouh** [comment]
No, the default should definitely NOT be "no interaction". That's something that should just work for most cases, and something that can be disabled if you don't need it, which is rarer.

That said, your problem has nothing to do with interactions, it seems. You just don't want the button to change its visuals on hover. For that the solution has been explained — add a custom stylebox for the hover state style, either via the theme or via a local override.

**Comment by dsnopek** [comment]
If you don't want the behavior of the `Button` control, maybe the answer is to not use `Button`s? You could make a completely custom button descending from `Control` or use a `TextureRect`? There's nothing that says all things that act button-like need to use `Button` :-)
