### ISSUE TITLE
change update() to _update() for consitency

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-proposals#3567]
### Describe the project you are working on

a game

### Describe the problem or limitation you are having in your project

i want to name function update but that requires me to overwrite the drawing update method

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I will now be able to define custom update() function

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the name is changed to _update() to be consistent with the rest of the method names across the engine.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

gdscript is core.

### Is there a reason why this should be core and not an add-on in the asset library?

it cannot be done with a add-on

**Comment by Zireael07** [comment]
Why close?

**Comment by KoBeWi** [comment]
Something similar was suggested here: https://github.com/godotengine/godot/issues/54161#issuecomment-962015533
Leading underscore is reserved for virtual methods, so it couldn't be renamed to `_update()` anyways.

**Comment by SilencedPerson** [comment]
> Why close?

sorry for late reply, it was for the reason KoBeWi mentioned.
