### ISSUE TITLE
Add Node2D (named) option to create node dialog

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot-proposals#3568]
### Describe the project you are working on

Every prototype I create.

### Describe the problem or limitation you are having in your project

When making prototypes I often want to create a Node2D which just helps organize the scene (e.g.: "Sprites" holding a lot of Sprite nodes). In that case I often find myself typing not the node type (Node2D) but the name that I want to give to the node ("Sprites") into the create dialog, because I think ahead of what I am doing. Then I have to delete the name type Node2D and rename the created node.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As soon as no Node matches the searched names the new Node options will be added to the top of the tree.
- Node2D (Named)
- Spatial (Named)
- Control (Named)

When selecting one of those the corresponding node will be added. In addition it will be named after the string entered in the search dialog.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Inside the CreateDialogue class exists a method that creates an instance of the selected type. In this method it would be checked if the selected item of the tree view should be named. (Would be solved via additional metadata for the item). In that case the `set_name` method of the instance will be used. By this salution the changes can be limited to one class.
(I would try to implement this myself if there are other users having the same problem)

Mockup:
![Screenshot 2021-11-18 111939](https://user-images.githubusercontent.com/67514656/142398581-b337ea3b-3274-4ae8-b23a-e8ad32abbe87.png)
(In the mockup the nodes are still ordered after inheritance but it would propably make sense to just add them all as child of Node from a usability standpoint)

This proposal is to some extends related to #1686 and would propably conflict with it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As far as I know the  create dialog can not be hijacked via an addon.

### Is there a reason why this should be core and not an add-on in the asset library?

It is usability and should therefore be build in.

**Comment by Zireael07** [comment]
Kinda related: #2717

**Comment by dalexeev** [comment]
> In that case I often find myself typing not the node type (Node2D) but the name that I want to give to the node ("Sprites") into the create dialog, because I think ahead of what I am doing. Then I have to delete the name type Node2D and rename the created node.

I think we can just add the Name field to the dialog.

![](https://user-images.githubusercontent.com/47700418/142419768-2d9912a2-a11d-4709-8910-308169377b78.png)

**Comment by RoniPerson** [comment]
> 
> 
> > In that case I often find myself typing not the node type (Node2D) but the name that I want to give to the node ("Sprites") into the create dialog, because I think ahead of what I am doing. Then I have to delete the name type Node2D and rename the created node.
> 
> I think we can just add the Name field to the dialog.

We could combine it with #1686 in this way. But I would suggest, that everything you type in the search will be added to the name as long as both are the same and the search does not match a node. In this way my use case would also be solved.
It would not be neccesarry to push `Node2D`, `Spatial` and `Controll` in the search because one could add them as favorites.

**Comment by dalexeev** [comment]
I find this confusing:

![](https://user-images.githubusercontent.com/47700418/142440013-62cd6115-e3c2-4efb-83fa-6c06ff53aff7.png)

As of #1686, there is no such problem because the type filter field is not used as a name field. Separated fields are good here.

**Comment by RoniPerson** [comment]
> As of #1686, there is no such problem because the type filter field is not used as a name field. Separated fields are good here.

Yes I agree that this may be confusing. It was just the best salution I could find for my use case.
#1686 would definitely help. But I think some sort of automated copying to the name field from the search field would help me a lot. (Idk if I am the only one experiencing this, but we could propably move the discussion about it to #1686).

**Comment by spindlebink** [comment]
What about a colon as a separator and after that is interpreted as the node name? Then the node picker remains as it is, but you could type something like `n2d:Sprites` and the type finder would select the match `Node2D` (a la current functionality) and pressing enter would create it and name it.

**Comment by RoniPerson** [comment]
> What about a colon as a separator and after that is interpreted as the node name? Then the node picker remains as it is, but you could type something like `n2d:Sprites` and the type finder would select the match `Node2D` (a la current functionality) and pressing enter would create it and name it.

While this would solve my case perfectly I think it wouldn't be really accesible. How should any user know about this without reding the docs?

**Comment by Zireael07** [comment]
@RoniPerson: A note below the input field would work.

**Comment by spindlebink** [comment]
> While this would solve my case perfectly I think it wouldn't be really accesible. How should any user know about this without reding the docs?

@Zireael07's solution works nicely. In addition, the original issue isn't so much a crucial usability thing as a convenience method (albeit a consistent annoyance for me as well), so making certain that every single user knows about it, while a good idea, wouldn't be the hugest priority.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP and general lack of activity here).
