### ISSUE TITLE
Add a way to get the physical scancode string: ex: OS.get_physical_scancode_string()

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot-proposals#3571]
### Describe the project you are working on

2.5D platformer (with key rebinding)

### Describe the problem or limitation you are having in your project

Using the new physical_scancode system, there's no way to display the correct key for non-qwerty keyboard layouts.  Docs suggest using OS.get_scancode_string(event.physical_scancode), but this displays the QWERTY equivalent of the key instead of the key of the current layout.  I can't seem to find a way to remap the physical scancode or a function to display the current string of the physical key.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would allow me to properly display the key name regardless of keyboard layout using the physical scancode.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Something like:
var key_string = OS.get_physical_scancode_string(input.physical_scancode)

or:
var scancode = OS.physical_scancode_to_scancode(input.physical_scancode)
var key_string = OS.get_scancode_string(scancode)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I couldn't find a way to -- if there is, it needs better documentation.

### Is there a reason why this should be core and not an add-on in the asset library?

Core, os-specific feature of the engine.  I don't think that info can be accessed from script.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/56015.
