### ISSUE TITLE
Enable mbedTLS Crypto object in official HTML5 builds

### ISSUE THREAD

**Issue by Faless** [godotengine/godot-proposals#3574]
### Describe the project you are working on

The Godot Web Editor, and a Godot HTML5 game that requires cryptographic functions.

### Describe the problem or limitation you are having in your project

The `Crypto` object is not available for HTML5 official builds since it requires the mbedTLS library which is disabled by default for the `javascript` platform.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The `mbedTLS` had originally only `StreamPeerSSL` and `PacketPeerDTLS` implementations, so it was not needed on the Web (since TLS/SSL is mostly handled by browsers), but it has expanded over time to include many useful cryptographic functions (hashing, signing, encryption) and it seems reasonable to now ship it along with Godot by default to allow using those engine features without having to recompile the export templates.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We should simply disable the forced default in:

https://github.com/godotengine/godot/blob/master/platform/javascript/detect.py#L55

and enable it in the release builds.

There is an increased binary size cost to this decision though.

These are the size differences (in KiB) once enabled:

```bash
# Release
13252   bin/godot.javascript.opt.wasm
4116    bin/godot.javascript.opt.wasm.gz

# Relase / mbedTLS
13612   bin/godot.javascript.opt.wasm # 360 KiB increase, ~3% increase
4340    bin/godot.javascript.opt.wasm.gz # 224 KiB increase, ~5% increase

# Release + LTO
12440   bin/godot.javascript.opt.lto.wasm
3976    bin/godot.javascript.opt.lto.wasm.gz

# Release + LTO / mbedTLS
12752   bin/godot.javascript.opt.lto.wasm # 312 KiB increase, ~3% increase (2.5%)
4184    bin/godot.javascript.opt.lto.wasm.gz # 208 KiB increase, ~5% increase
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's a build option.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a build option.

**Comment by akien-mga** [comment]
I would have expected the size difference to be less than 3%, but well, it's still a reasonable increase to have feature parity with all other platforms. I agree that this should be enabled by default now that it provides features which are not readily available through the browser.

Users who want to optimize for size could still build custom templates with this module disabled, alongside many others they probably don't need for a size constrained game (e.g. all 3D code for a simple 2D game, etc.).

**Comment by RPicster** [comment]
I just have the problem that I developed on desktop and now that the first real release on WebAssembly is due, I ran into exactly this problem (on 3.4).

It's extremely annoying to miss this feature for one platform so I would greatly welcome a feature parity here, ideally with a backport 😲

**Comment by Calinou** [comment]
> It's extremely annoying to miss this feature for one platform so I would greatly welcome a feature parity here, ideally with a backport astonished

This will have to wait for 3.5, as patch releases are now dedicated to bug fixes only to avoid regressions.

**Comment by RPicster** [comment]
Hey there,
are there any news about this? I didn't see it in the 3.5 notes so far so I wanted to ask again how's the plan for this :)
