### ISSUE TITLE
Reimplement maximum undo steps in UndoRedo

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#3575]
### Describe the project you are working on

A 3D painting application.

### Describe the problem or limitation you are having in your project

While adding undo/redo support to mesh painting, I realized it would be useful to be able to limit the undo actions to save on memory/disc space, as there are a lot of textures to be saved per brush stroke. This is currently not possible in Godot's native UndoRedo class.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Readd the `get_max_steps` / `set_max_steps` methods removed in godotengine/godot#15460. Steps that are older than `max_steps` would be freed from memory, and couldn't be reached by calling `undo()`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
var ur := UndoRedo()
ur.max_steps = 1

ur.create_action()
ur.add_do_property(self, "trade", Trade.new("apples", "eggs"))
ur.commit()

# Could undo the last action.

ur.create_action()
ur.add_do_property(self, "trade", Trade.new("bananas", "apples"))
ur.commit()

# The first action isn't available anymore and the trade is freed from memory.
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around with the native UndoRedo, but then you could also just reimplement it completely.

### Is there a reason why this should be core and not an add-on in the asset library?

It's common undo functionality, so it can be added in core.

**Comment by Calinou** [comment]
Should the undo/redo size limit the number of steps, or the maximum memory usage? The former is more predictable for the user, but it's also more limiting. Storing 200 move operations in the UndoRedo buffer requires much less memory than storing 200 different texture copies.

**Comment by Jummit** [comment]
That would be interesting, but I think starting with a sensible default that the user will most likely never reach is sufficient, and if that's not enough, it can easily be exposed in the settings.
