### ISSUE TITLE
A suggestion to add SOME features from Godot 4, to Godot 3 Graph edit . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3577]
### Describe the project you are working on

A barbarian 2.5D game, with lore and, quests . . . ! :-OO . . .

### Describe the problem or limitation you are having in your project

Right now, looking only at the Godot 4 bar, for mile-stone, it sadly looks like Godot 4 is maybe, mid 2022, late 2022, or perhaps early 2023 . . I don't KNOW that, it just looks like it . .

It's a bit sad, that the amazing UI improvements in Godot 4, that it might be well needed to wait that long :-(( . .

IF the engine won't be ready until, late 2022, or early 2023, in that regard, I sigh wanted to ask if it might be possible to get those UX improvements, to Godot 3 series, bec. it's such a long wait, and it'd help people finish projects in Godot 3.x . . Godot 3 has OpenGL ES 3.0, and can make amazing stuff, in the right hands, it's super - difficult, I really don't want to wait 1 - 1.5 years, to get such an experience, it helps a ton, experience is more calm, or ' quiet ' or, relaxed . .

Again, got no idea if Godot 4 will be ready in 2022, or even 2023 :-(( . . That's why, it'll be a long wait, to just get a big UX improvements, that's all, thanks . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, it might be a bad idea, maybe Godot 3 could benefit from these things, in the end, esp. Visual script is a bit weird, it takes experts to work on it, well imo . . . I THINK, there's so much 3D power, in Godot 3.x, it only makes sense to add it sooner, so people can work better, more easy . . In stuff right now, than wait for late 2022, or early, perhaps mid 2023, that's what it looks like, Godot 4 will be ready . . .

Also, I really like Vulkan, for me OpenGL has a nicer, more ' nerdy ' look, my plan is not to report, or maybe add bugs for Godot 4, until it has OpenGL ES 3.0, that's what I want to use . . So, I really want to use Godot 3.x, for the graphics, and I'll have to wait until Godot 4 gets OpenGL ES 3.0, before I can use the new UX stuff . . .

Last, since UX of graph edits can be improved, by imo making the ' theme ' more muted, bit LESS colorful, was hoping it might be added to theme editor, to customize graph edits more, I just want an ' as muted, calm ' look as possible, while still keeping it simple, or ' realistic ' . .

I think it'd give Godot 3 a boost, and people might work on stuff now, than wait for maybe mid 2022, or early, sigh, 2023 . .

That said, I know it's not easy . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, hoping the amazing work, on UX, and QoL made in Godot 4, given the MAYBE long wait, could be added, making graph edits much nicer, and calm, and help the community make stuff now, not wait for Godot 4, I have to give Godot 4 12 / 10 grade, but well looks like the wait will be, ' brutal ', nice, as it is . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I can not code the engine, at all . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, I'd like to get to work on my amazing projects right now, if Godot 4 is released, the ALPHA . . And, then looking at progress bar, it'll take maybe 1 - 1.5 years, before it's running well, no bugs, crashes, so one can start making stuff, waiting that much time, for these UX improvements, will be quite depressing, etc . . .

I'd like to be able, if possible, to customize the look of graph edits, to make them the ' best ' possible, 98 % stable, as close to 'clean' or, good code, as possible . . It's bec., the Godot 4 progress bar doesn't look, to move, sometimes it looks, sigh it's going back-wards, thanks . . . ! :-OO

**Comment by mrjustaguy** [comment]
Eh, Godot 3 also has bugs, so by that logic it shouldn't be out too.. there's practically no such thing as Bug-free software.

As for the rest, I don't see a point, as Godot 4 is really close to Alpha at this point https://twitter.com/Akien/status/1453627598727155714 (I know this is several weeks old at this point...) there's really just a very large chance that an official Alpha will drop within the next month or so, unless we come up with yet another major compatibility breaking QoL Improvement to do.. and there are even some semi-official "pre-Alpha" builds

Judging by past release history (, once an Alpha comes out, it'll be several months of alphas and betas till they're polished enough for release candidates to start appearing, at which point it's only a matter of time before we get a stable release out.

**Comment by charlesmlamb** [comment]
Well, the  problem is, I don't like the look of Vulkan, I made a post about it, it has too much post - proc, or ' blur ' . . 

I want to use OpenGL ES 3.0 for my games, I like the raster - render look better, so until Godot 4 gets OpenGL ES 3.0, I don't really want to use it, perhaps when it gets RTX, but, it only runs on high - end computers, want to make my stuff run in 720p, and, get that old - school and, pixelated raster - look . .

So, Godot 4 won't be useful for me, until it gets OpenGL ES 3.0, heard that was planned and, that might take a long time or, RTX, have a laptop RTX card <3

Alternative is to wait, I see no reason for Godot 3 not to get these things, that version will be used by many people, bec. it's really good, esp. for low - end computers . . My plan was also to skip Godot 4, until it gets OpenGL, so I won't be reporting bugs, the UI improvements are, so good one can work comfortably in graph edits, well, it'd be nice, also slowly learning GDScript, also Godot 4 will have bugs, some time after official release, and the progress bar, simply doesn't move, from what  can tell, it's been at 80 %, or so, for last year, or six months . . .

**Comment by Calinou** [comment]
Closing, as no backwards-incompatible features from Godot 4 will be backported to Godot 3 (unless they can be redesigned in a backwards-compatible manner).

Backporting efforts to Godot 3 are welcome, as long as they are fully backwards-compatible. It's a good idea to open a **specific, focused** proposal on what you intend to backport, but it's not strictly necessary.
