### ISSUE TITLE
Expose physics shape separation functionality

### ISSUE THREAD

**Issue by djrain** [godotengine/godot-proposals#3579]
### Describe the project you are working on

Action game with numerous fast moving objects, using custom collision system.

### Describe the problem or limitation you are having in your project

Our game requires precise collisions among numerous fast-moving objects. After messing with KinematicBody2D it became clear that this wouldn't do the job, largely due to areas missing overlaps with it. 

So instead I've made my own shapecasting functions in GDScript using only Area2D and the various methods in Physics2DDirectSpaceState. This allows for continuous collision detection, finer control, and avoiding having to wait for physics_process for things to update properly.

This is working great for the most part (though it definitely could have been easier with a more capable set of collision related functions). However it seems the last thing I really need is a way to separate two colliding shapes, and there isn't any function in physics API for this.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'm not super familiar with the inner workings, or physics engines in general, but the functionality to separate two shapes is present in the engine in some form, so I propose exposing it to scripting. There could perhaps be a function in Shape2D called separate_from() or something similar. It could take the two shapes and their transforms and return the new transforms after separation. Either that, or return the information I would need to separate the bodies myself, like the collision normal and penetration depth.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

that's it really.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

definitely no.

### Is there a reason why this should be core and not an add-on in the asset library?

It's already in core, and would go nicely with other already exposed collision functions.

**Comment by Calinou** [comment]
cc @pouleyKetchoupp

**Comment by Xrayez** [comment]
Collisions are resolved via separation/interpenetration contact constraints. I think this requires exposing *collision solvers* in Godot somehow. The collision solver in Godot is iterative (like in most physics engines), meaning that you'll also have to solve constraints one-by-one *n* number of iterations, because solving one constraint may violate the other.

To be honest, if you find yourself implementing your own collision stuff, perhaps you should consider implementing your own system for this, especially when physics is not necessarily realistic in your game. For instance, I've previously ported Box2D lite version in GDScript: https://github.com/Xrayez/box2d-lite-gdscript. Of course, I'm not suggesting to implement physics in GDScript, but that's definitely an option to consider.

**Comment by djrain** [comment]
> I think it's still practical to expose necessary functions in `Shape2D` in order to help you separate shapes yourself. This information includes an array of contact points (_contact manifold_) with _collision normal_ and _penetration depth_.

I think this would be perfectly sufficient for my needs. If there was a function that returns this stuff, or nothing if not colliding, that would be awesome.

**Comment by pouleyKetchoupp** [comment]
@djrain There's already `collide_and_get_contacts()` to get contact points given two shapes in 2D:
https://docs.godotengine.org/en/stable/classes/class_shape2d.html#class-shape2d-method-collide-and-get-contacts

And also `collide_with_motion_and_get_contacts()` which takes the shapes motion into account in case you need continuous collision.

They are not very well documented (that definitely needs to be improved), but here's what you can get from them:
- They return separation points for the provided pair of shapes
- The array will contain the contact positions, alternating between shape A and shape B, so two consecutive entries give you information for one contact
- You can calculate the separation depth and normal using these two points, using the (B-A) vector length and direction.
- The collision can generate multiple contacts depending on the shape types: a box can have 2-4 contacts with other shapes, but circle-circle will always generate just one contact.

I'm closing the proposal for now, but feel free to ask if you have questions or trouble when using these functions.

**Comment by djrain** [comment]
@pouleyKetchoupp So I've used the method you described to successfully separate shapes such as circles and rectangles, but I guess this doesn't necessarily work for concave polygons. Any thoughts on how to handle those?

**Comment by Xrayez** [comment]
@djrain concave polygons are made up of segments, and are constructed in counter-clockwise order. You can determine orientation of individual segments using cross product:

```gdscript
static func is_point_to_right(p, a, b):
	return (b - a).cross(p - a) > 0
```
If point is to the right of the segment, the contact point *may* be inside polygon.

That's assuming if `Shape2D` returns which segment collided exactly.

**Comment by djrain** [comment]
> That's assuming if `Shape2D` returns which segment collided exactly.

Don't think there's a reliable way to get that... seems to me that the contact points aren't much help for concave shapes.

As of right now, my only concave objects are roughly circular, so I might just aim for a "good enough" iterative separation based on the angle or collision normal. Might be a bit limiting, but on the plus side would avoid the hollowness issue.

**Comment by Xrayez** [comment]
If you use Goost, you may just decompose concave polygon into convex via [`GoostGeometry2D.decompose_polygon()`](https://goost.readthedocs.io/en/latest/classes/class_goostgeometry2d.html#class-goostgeometry2d-method-decompose-polygon), or [`PolyDecomp2D`](https://goost.readthedocs.io/en/latest/classes/class_polydecomp2d.html) if a polygon contains holes.

**Comment by pouleyKetchoupp** [comment]
> @pouleyKetchoupp So I've used the method you described to successfully separate shapes such as circles and rectangles, but I guess this doesn't necessarily work for concave polygons. Any thoughts on how to handle those?

What's the problem with concave shapes? It should work just as well as what the physics engine does internally (unless there's a bug). If you have a specific example to share, I would be interested to have a quick look next week.

**Comment by djrain** [comment]
@pouleyKetchoupp Here are two examples of a ConcavePolygonShape2D vs a RectangleShape2D, where none of the contact pairs could be used to resolve the collision
<img width="540" alt="Screen Shot 2021-12-05 at 11 48 31 AM" src="https://user-images.githubusercontent.com/33777501/144761375-ba1cf483-4094-4c0f-b0ac-f9641e7ed4f5.png">
<img width="471" alt="Screen Shot 2021-12-05 at 11 44 58 AM" src="https://user-images.githubusercontent.com/33777501/144761384-031cfd17-7f01-46a0-9aef-a4d59cdf6ddf.png">

**Comment by djrain** [comment]
@pouleyKetchoupp It seems like `collide_and_get_contacts()` might be failing in some cases. For example:

[(600, 200), (540, 200), (600, 300), (584, 252), (600, 200), (540, 200), (600, 300), (596.585388, 269.26828)]
<img width="511" alt="Screen Shot 2021-12-05 at 4 32 33 PM" src="https://user-images.githubusercontent.com/33777501/144770650-f062603b-075b-40a7-9a76-5247c26121f0.png">

Here I've drawn the consecutive contact pairs in the same color with lines connecting them. As you can see there is a repeated pair (600, 200), (540, 200) which is the yellow points. And my polygon does not have any vertex at the green point.

**Comment by pouleyKetchoupp** [comment]
@djrain Thanks for the example! It looks like this is a limitation of the physics engine when it comes to concave shapes, but in most cases it should work fine anyway.

If you consider the separation is done based on segments individually, these contact points make sense. They are the shortest path to separate. The green point is the closest point on the segment from the rectangle's corner.

They are not perfect as they don't take into account the global topology of the shape, but it should still be good enough. The rectangle shape should still be pushed to the left and up given these contact points.

I've made a project to test a similar example as your screenshot:
[concave-shape-contacts.zip](https://github.com/godotengine/godot-proposals/files/7664481/concave-shape-contacts.zip)

I'm getting these contact points with concave:
![image](https://user-images.githubusercontent.com/1075032/144945082-4749f188-650f-4922-bcd8-94f3a97102e9.png)

And also these contacts when using convex decomposition (I've just made 2 convex polygons by hand):
![image](https://user-images.githubusercontent.com/1075032/144945118-79cf3cae-63ce-48e5-ab0a-90f596d5bd6c.png)

If I change the rectangle bodies mode to Rigid to see how the separation works, it seems to be be fine:
![image](https://user-images.githubusercontent.com/1075032/144945249-e0569d44-df2f-48e5-9c1d-b8564c0ee17f.png)

There will be some cases that fail, like a shape stuck in between two segments with opposing normals. But generally if the overlap is not too much, these separation contacts will be ok.

**Comment by djrain** [comment]
@pouleyKetchoupp thanks, really appreciate you taking the time to look into this! 

That all makes sense, although I'm still not sure where that leaves me if I want to separate these shapes manually. It seems to me that the contact points alone won't get me very far, and the important logic is hidden in the collision solver. Am I right?

**Comment by pouleyKetchoupp** [comment]
@djrain Generally what you need is an iterative process to separate all the shapes:
-Each step you separate by only a fraction along the contact points normal (this fraction will give more or less elasticity to the collision)
-In one step, you can run all the shape separations several times before checking new contact points to help with cases of multiple bodies separating from each other without making it too expensive for performance (checking for contacts is the slowest part, especially for convex and concave polygons)

This is a simplified version of what the solver actually does. In practice it changes the velocity of all rigid bodies to take into account the separation, but also friction and bounce. Then at the end of the process it updates the positions based on updated velocities.

But for very simple physics, just moving the shapes by a given fraction on both sides along the contact normal for each contact should be good enough.

If what you need is something really fast and simple, I would suggest to stick with primitives and convex shapes as much as possible and avoid concave shapes though.

**Comment by djrain** [comment]
> But for very simple physics, just moving the shapes by a given fraction on both sides along the contact normal for each contact should be good enough.

Thanks again! Might give this a go. It would only be for a few shapes with few vertices. I guess I'd want to use `Shape2D.collide()` for the fastest possible collision check, if I don't need the contacts? 

And would it be sensible to avoid moving along two normals that are in roughly opposite directions?

**Comment by pouleyKetchoupp** [comment]
> I guess I'd want to use `Shape2D.collide()` for the fastest possible collision check, if I don't need the contacts?

I'm not sure I understand what you intend to do with `Shape2D.collide()`. Do you mean you want to check if the shapes collide, and then just separate them from each other without using contacts? It can be good enough, but it really depends on your use case. For info, using `Shape2D.collide()` might be a bit faster than the one with contacts but probably not much, because it still runs the most expensive part of the algorithm, which is to find out if the shapes are separated.

> And would it be sensible to avoid moving along two normals that are in roughly opposite directions?

Yeah that makes sense, not sure you need to do it specifically though. In practice if you move the shapes according to each pair of contact points, opposite contact normals are going to "naturally" cancel each other.

**Comment by djrain** [comment]
> For info, using `Shape2D.collide()` might be a bit faster than the one with contacts but probably not much, because it still runs the most expensive part of the algorithm, which is to find out if the shapes are separated.

Don't have a specific plan yet, so that's good to know, thanks!
