### ISSUE TITLE
Implement text-to-speech for Android

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#3584]
### Describe the project you are working on

I am working on 3d and 2d game development for Android. And i think godot is a great platform for Android games. 

### Describe the problem or limitation you are having in your project

There isn't any text to speech inbuilt system available in godot. But it is very much important for game to add a speech sothat the user can understand what's are the game about.So for my game and every android game developers there must be and text to speech system.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It could be implement as a plugin

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

On dialoguepopup():
$textToSpeech.text= "text to speech is needed for Android developer"
$textToSpeech.speech()

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I could be attached by godot developer as a plugin.but i think it is essential to have a process to add text to speech in godot.

### Is there a reason why this should be core and not an add-on in the asset library?

No. It could be a addon. But it should be developed by developer. There are three plugin available in gitbub. But these are not bug free.

**Comment by Zireael07** [comment]
if you say it's can be done with a plugin and there are preexisting plugins, this is not a place for this request - this is a repo for Godot core requests.

**Comment by hani09876** [comment]
> if you say it's can be done with a plugin and there are preexisting plugins, this is not a place for this request - this is a repo for Godot core requests.

The plugin are not in godot and also these aren't based on Android. Now would you tell me where should I ask .

**Comment by KoBeWi** [comment]
> But it is very much important for game to add a speech sothat the user can understand what's are the game about.

But that's what text is for... And if you have speech only, it's impossible to play the game with sound off.

**Comment by Calinou** [comment]
> Now would you tell me where should I ask .

For plugin ideas, use the third-party [godot-ideas](https://github.com/godot-extended-libraries/godot-ideas) repository.

**Comment by bruvzg** [comment]
https://github.com/lightsoutgames/godot-tts TTS plugin should support Android.

**Comment by GeorgeS2019** [comment]
@Calinou  You could consider putting this working [Godot TTS and STT project](https://github.com/kaiidams/Voice100Godot/issues/1#issue-1099967958) as part of monthly Godot community update.

This would encourage the author to enhance the project further to address the missing Godot demo in the area of TTS and STT.

**Comment by Calinou** [comment]
Note that this was implemented for all platforms in `master`, not just Android.
