### ISSUE TITLE
Facebook audience network adds

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#3585]
### Describe the project you are working on

I am working on both 2d and 3d game in godot

### Describe the problem or limitation you are having in your project

If i can implement Facebook adds on my android app it will be helpful for me to earn. and also it's the reason why i am creating an app. For me to earning by Godot it's important to implement Facebook audience network adds. 

So i think since there isn't any Facebook adds implementation system this is a limitation for every android developer

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There should be a options to add Facebook adds on app. As everyone creates apps for earnings money. So there should be a options to implement adds on game 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

By adding node called Facebook adds

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yeah it can

### Is there a reason why this should be core and not an add-on in the asset library?

Yeah. Facebook audience network is a great system for earning money.
Most of the android developer are using Facebook adds.

**Comment by KoBeWi** [comment]
Such plugin already exists: https://github.com/MrZak-dev/GodotFAN
It won't be in core.

**Comment by Xrayez** [comment]
> Such plugin already exists: [MrZak-dev/GodotFAN](https://github.com/MrZak-dev/GodotFAN) It won't be in core.

To explain my reaction to @KoBeWi's reply: it won't be in core not because of an arbitrary decision, but because it goes against [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) principles which Godot tries to follow, therefore these kind of plugins must be implemented by third-parties.

However, Godot does have some similar plugins maintained officially, such as https://github.com/godotengine/godot-google-play-billing, so this proposal has its ground.

I wonder if Godot's documentation states those principles somewhere, proposals like this tend to pop-up from time to time.

**Comment by KoBeWi** [comment]
Billing is a "core" Android functionality. It's standarized in the Play Store, which is the official app store for that system. If there was an official ad service for Android (AdMob or Facebook aren't such services), it would likely have an official plugin too.

**Comment by Calinou** [comment]
> I wonder if Godot's documentation states those principles somewhere, proposals like this tend to pop-up from time to time.

This is already mentioned in the FAQ: https://docs.godotengine.org/en/latest/about/faq.html#will-insert-closed-sdk-such-as-fmod-gameworks-etc-be-supported-in-godot

**Comment by Calinou** [comment]
Closing, as this will not be developed as an official effort per the [FAQ](https://docs.godotengine.org/en/latest/about/faq.html#will-insert-closed-sdk-such-as-fmod-gameworks-etc-be-supported-in-godot).
