### ISSUE TITLE
Suggestion to spawn particle systems with a basic, simple default spawn pattern . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3589]
### Describe the project you are working on

A 2.5D game, barbarians, lore . .

### Describe the problem or limitation you are having in your project

Uhh, using particles in Godot, took me some time, it's a somewhat difficult feature, that has process material, draw passes . .

There are two things . . I don't find it intuitive, or user-friendly to use particles, haven't had time to think about that, but maybe renaming stuff so it makes more sense . . It took me about 2 days of trial and error, and had to watch tutorials about it several times, to finally get particles to work . . So, I realize the particles are prob. named in a very good way, but was hoping someone might rename some things, so it's 1. easier for beginners, and 2. still very cool, for advanced users, so it's a balance, that tries to please everyone . . .

The second thing, and that is what the suggestion is about, when one makes particles, nothing is set to on . . That prob. makes sense, but esp. for beginners, but also having used them for a while, it's a bit weird, when one makes particles, that one can't see anything, WYSIWYG, the moment one adds the particles . . That's why I have a suggestion . . Since many particles used quad billboards, make it so particles spawn with simply quad materials, so one can see one has created particles, the second one adds a particle emitter, or system . . I think overall they are the most used, for adding sprites, particle sheets, also, in industry, so it makes sense to use quad planes, in draw passes, as default . . .

So, when one does that, one gets a bunch of quads, that fall down, sort of like cards falling, from a card trick, they overlap, and it still doesn't look, like what I'd call ' particles ' . . That doesn't really for a nerd like me, I understand the feature now, but it still make sense, as the default settings . . . I don't know what that could be, but since one oftens spawns particles near a ground surface, the planes will fall under ground, and bec. invisible, so one can't see them, in many common use-cases, say a torch in a cave, or some effect, near the ground . . I guess the ideal way, if one takes into account, that particle can be placed in different places, sometimes near ceiling, sometimes near ground, is just to spawn them randomly, in a sphere, radius 1 . . . And, instead of having a default gravity of (0,-9.8,0), which technically is another value, that is not simply zero, from the beginning, ie. one can't really say the DEFAULT ParticleMaterial, just has the value 0, in every value, why not make it so it makes more sense . . .

Here's one example, I think is better . . .

![Animation](https://user-images.githubusercontent.com/83387915/143144010-f493803f-a0ac-4559-a6d6-33ae7842b841.gif)

Idea is, when one adds a particle system, since one wants to customize the values, and there already has been some customization set, ie. gravity -9.8, on y - axis, why not make it bit more apparant, that it is particles . . .

However, since quads are only visible from one side, one could add some particles, and from the wrong side, one would not see them, for beginners that can be weird, so one idea is, spawn cubes, instead of quads, by default, looks like this . . .

![Animation (1)](https://user-images.githubusercontent.com/83387915/143144405-de75b4f4-515d-4258-8e44-c2c8a1567bcd.gif)

Or, spheres, problem is if spheres are 1 m radius, and the spawn radius, for particles is 1 m, it looks like this . . .

![Animation (2)](https://user-images.githubusercontent.com/83387915/143144521-a7cc5d3e-8f40-45bb-8b74-ed94b4f3e491.gif)

Anyway, uhh so that's is what this is about, making it so when one adds particles, a simple one is created, so one can see, from all angles, hey particles are spawning . . . Since spheres have many more polys, than cubes, to make it run on slower computer, I'd prob. use cubes, and set the default scale, of particles, to 0.1, or 0.2, this . . .

![Animation (3)](https://user-images.githubusercontent.com/83387915/143144742-81a7ef27-653b-4f82-8fc7-318783e06b04.gif)

Cubes, scale 0.2, no gravity . . Can be seen from any side, in order to make quads visible, one has to set more advanced in the material, for the draw passes, and that'd be quite difficult, for new users to find . . .

Alternatively, one could add a bit of gravity, to get this look, or something else, where they emit, from the center, radially . . .

Gravity set to 2 . .

![Animation (4)](https://user-images.githubusercontent.com/83387915/143144989-f96443ba-f857-4c15-aae1-463bec25b13b.gif)

This way, so if a new user adds particles, for trying to work with them, something happens, instead of having to watch tutorials, or spend 2 - 3 days experimenting, clicking various buttons, not really being able to make sense, of what is happening . . . Having these settings, one could immediately see, in ParticlesMaterials, that's where these things happens, and in draw passes, because there was a cube, one could see, hey so this is what I spawn . . .

It's simple, elegant, moderately cool . . One might be able to find better examples, maybe particles exploding from a center, or perhaps slowly fading with a curve, anyway . . The point is, make it more user-friendly, and perhaps fun, esp. for new users that just want to see some particles, or, like above, try and rename the particles so they make more sense . .

I don't know if this is a good idea, it was just some thoughts from a beginner, spent 2 - 3 days trying to get particles to work, ended up giving up, before getting it to work, some months later I watched a random tutorial, it was about particles, that's how I learned to make them work, or, even make a basic one . . There's no pain, no gain, and then there's wasting the community's time, and some things being added, so it makes no sense, or takes too long, to get anything working . . . Imo, particles are a bit like that, so I'm suggesting a review of the feature, sort-of like above, with a view on more user-friendliness, as much, as is possible, that's all . . . !

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, see above, it's about making it a bit easier, or more ' instant ' to get particles working, or at least making sure, it doesn't end up taking too long, to even spawn some simple particles, or something . . Right now, for beginners, it's a mess, like it was coded by people, that didn't want the end users to use the feature . . Maybe some improvements could be made, within reason . . . . Also, don't really like my suggestion, the boxes are nice, maybe someone has some better ideas, not sure . . . It's like, it's not quite right, but then again, it also should get better, that's all . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like above, see images, etc . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this is about default settings in the engine, since cubes are already coded, having a default setting using cubes, wouldn't really change anything, and since one has to click, to add say particleshaders anyway, it would not really change anything, one still has to click stuff, to change the settings, at least once, to get anything done, if it's all blank, no settings . . Same amount of work, however, it is a bit more fun, esp. for beginners, to add a particle system, and for experienced users, it's still a visual help, for getting started, and it makes sense, also other engines do this, but that doesn't exactly mean, it's a good idea, still, some improvements here, I think is perhaps necessary, so like always, this is a noob suggestion, hope someone could make it better, or, so, that's all . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it's never easy to answer this, I say core :-OO . .

Add : The default spawned particle material is quite ugly, esp. if combined with a quads, it's just like a things fall down, not sure, it could be more user-friendly, and by spawning say, in a cube, or sphere area, one could see the spawned particles, at all time . . Hope someone will give it some thought, maybe spawn cubes, inside a cube, instead of a sphere shape, tweak it . . . It's a suggestion, maybe it's not possible, but a little work here, might be quite helpful, not sure . . . 

Note, spawning cubes in 3D, would make them work well, with 2D, if they were square sprites . . Spawn in 3D, it's particles, as cubes, in 2D, it's sprites, also square, and the two sort-of uhh ' work together ', at least, well visually . . . !

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/2533.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2533 and https://github.com/godotengine/godot-proposals/issues/2998.
