### ISSUE TITLE
Install Python library 

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#3599]
### Describe the project you are working on

I am working on both 3d and 2d project

### Describe the problem or limitation you are having in your project

There isn't any options to install python library . And i think this feature must have to be included

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature will help the developer to add more amazing features on there app. And will remove the limitations of any app.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There should be an options on  cmd to install python library using command

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Yeah . There is a huge reason. It must be a core to ensure not to lose the ability of python library.

**Comment by Zireael07** [comment]
Godot core itself does not support Python. Python support is only provided by an external asset.

**Comment by hani09876** [comment]
> Godot core itself does not support Python. Python support is only provided by an external asset.

How can i get the assets. In godot 4 can we will be able to install c++ sdk or api

**Comment by Zireael07** [comment]
This is not the place for support questions.

**Comment by pycbouh** [comment]
Godot does not support Python out of the box, and there are no current plans for it either. Python can be added via a third-party module that adds Python-language API bindings for the Godot APIs, like https://github.com/touilleMan/godot-python.

C/C++ libraries can be added via the GDNative C/C++ bindings (https://github.com/godotengine/godot-cpp), or by building a module. In Godot 4 GDNative is replaced with GDExtension which is kind of in the middle between GDNative and modules.

Read more on modules here: 
https://docs.godotengine.org/en/stable/development/cpp/custom_modules_in_cpp.html
https://docs.godotengine.org/en/stable/development/cpp/binding_to_external_libraries.html

Read more on GDNative here:
https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/index.html
