### ISSUE TITLE
occlusion testing function for scripts

### ISSUE THREAD

**Issue by jasonswearingen** [godotengine/godot-proposals#360]
**Describe the project you are working on:**  open world game

**Describe the problem or limitation you are having in your project:**  concerned about godot's lack of occlusion culling options.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**  provide a script accessable occlusion testing function, so that even if the engine doesn't do occlusion culling, the game developer has some visual-based options

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Here is a github repo with demo+code for a Vulkan implementation (using compute shader): https://github.com/sydneyzh/gpu_occlusion_culling_vk

that repo also includes a link to https://interplayoflight.wordpress.com/2017/11/15/experiments-in-gpu-based-occlusion-culling/  which contains a lot of resources on occlusion culling.

**Describe implementation detail for your proposal (in code), if possible:**
a script accessable function to do an AABB test against the current/previous frame.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no,  there are some BSP/room based culling that can be done in script, but nothing visibility based.

**Is there a reason why this should be core and not an add-on in the asset library?:**
requires collaboration with the godot rendering system (very low level)

**Comment by clayjohn** [comment]
Occlusion culling is coming in 4.0. it absolutely needs to be implemented in the rendering backend, it cannot and will not be implemented in GDScript. 

You will be able to access the feature by turning it on through the editor or through GDScript. 

Occlusion culling required tight integration with the rendering system so it cannot be made available as something you can implement through GDScript. 

You also seem to be mixing up occlusion culling and frustum culling. Testing AABBs against the camera frustum is already implemented. Occlusion culling tests whether particular meshes (or parts of meshes) are fully covered by other meshes.

**Comment by jasonswearingen** [comment]
> You also seem to be mixing up occlusion culling and frustum culling

What I mean is testing an AABB against the rendered frame, not frustrum.  Basically to see if any of the pixels of the AABB would be drawn.   IIRC this is possible with DirectX and the various new fangled shaders (like the vulkan link I sent)

If this pixel test can be exposed to script, it would let game developers do their own scene culling optimizations, prior to, and in-addition to have it auto-magically enabled by the godot engine  (let the developer do early-rejections on their spatial partition).

Also, I think that OpenGL es3 supports occlusion testing, so this might be able to be backported to godot 3.2.     I'm not a graphics dev, but think this is a good link:    https://www.opengl.org/archives/resources/faq/technical/clipping.htm

**Comment by Calinou** [comment]
@jasonswearingen The GLES3 renderer is now considered to be in maintenance mode, so it won't get any new features.

**Comment by jasonswearingen** [comment]
>  The GLES3 renderer is now considered to be in maintenance mode, so it won't get any new features.

Understood and no problem.

> Occlusion culling required tight integration with the rendering system so it cannot be made available as something you can implement through GDScript.

Please reconsider.  Based on my (out of date) experience with DX12 and understanding of similar implementation with Vulcan, it seems straight forward to expose an AABB visibility test against the rendered frame.   If so,, it will allow early bound culling by the spatial partitioning system. (example, if an oct-tree node is visible)

**Comment by Zireael07** [comment]
>  AABB visibility test against the rendered frame

Unless I am misunderstanding, this is frustum culling, not occlusion culling. Occlusion culling refers to culling of the objects behind (occluded) by other objects.

**Comment by clayjohn** [comment]
> Please reconsider. Based on my (out of date) experience with DX12 and understanding of similar implementation with Vulcan, it seems straight forward to expose an AABB visibility test against the rendered frame. If so,, it will allow early bound culling by the spatial partitioning system. (example, if an oct-tree node is visible)

What is there to reconsider? The feature absolutely has to be implemented in Vulkan. GDScript is not an option. Accordingly, occlusion culling will be built into the rendering for Godot 4.0.

> If this pixel test can be exposed to script, it would let game developers do their own scene culling optimizations, prior to, and in-addition to have it auto-magically enabled by the godot engine (let the developer do early-rejections on their spatial partition).

If the pixel test could be exposed to script (it can't) it would be painfully slow. Already occlusion culling is a poor optimization technique as the cost of occlusion tests often outweighs the benefit of culling. If exposed to GDScript the cost would be prohibitively high. If you want to simple tests for single objects, Godot already exposes a [RayCast API](http://docs.godotengine.org/en/latest/classes/class_raycast.html).

> Also, I think that OpenGL es3 supports occlusion testing, so this might be able to be backported to godot 3.2. I'm not a graphics dev, but think this is a good link: https://www.opengl.org/archives/resources/faq/technical/clipping.htm

This is for depth-based fragment occlusion testing. Which Godot already does as it is implemented by OpenGL.

**Comment by jasonswearingen** [comment]
@Zireael07   The technique I'm advocating is doing box visibility tests in the GPU and reporting it back to the game.

To me, "Frustum Culling" means doing a BB intersection test against the camera frustum in the CPU.  So therefore I hope we all understand this is not what I am suggesting.

>  If the pixel test could be exposed to script (it can't) it would be painfully slow. 

@clayjohn it certainly would not be useful for all games/all the time, but especially for open world games it can provide hints to the game as to what sections of the game are visible.   Additionally, me calling it a "pixel test" is regrettable, as it's not something you would do per-pixel but "per game section".    I did a techdemo back with DX12+XNA and it worked pretty well.

However, I can agree that perhaps this request can be revisited once we have a Vulkan+occlusion culling version of godot to try out.    I should have something to test with then.

Thank you guys for the feedback, I'll close the request.

**Comment by mhilbrunner** [comment]
Thanks for taking the time to give feedback :) Lets see what happens with Godot 4.0!
