### ISSUE TITLE
Add TCP protocol for high-level multiplayer API

### ISSUE THREAD

**Issue by kinqsley** [godotengine/godot-proposals#3602]
### Describe the project you are working on

I am working on a 3D MMORPG game(non-browser) with an authoritative server architecture.

### Describe the problem or limitation you are having in your project

As far as I know, the current High-level multiplayer APIs (Enet) only supports UDP. 

Game developer should be provided with the option of choosing a protocol (multiplayer) suitable for their game project. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Should be able to use all the APIs from [High-level multiplayer](https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html) for TCP network connection.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Make [NetworkedMultiplayerPeer class](https://docs.godotengine.org/en/stable/classes/class_networkedmultiplayerpeer.html#networkedmultiplayerpeer) available for TCP_Server/StreamPeerTCP?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe this is not just a few lines of work.

### Is there a reason why this should be core and not an add-on in the asset library?

I believe It is a core feature.

**Comment by Calinou** [comment]
> Game developer should be provided with the option of choosing a protocol (multiplayer) suitable for their game project.

When you have reliable UDP at hand, there is no point in supporting TCP. Reliable UDP provides lower latency while having the exact same functionality as TCP available.

If you absolutely need to use TCP (e.g. to run a game on a network that blocks UDP ports), you can use a tunneling application (at the cost of latency).

**Comment by kinqsley** [comment]
It is viable to use WebSocket instead of raw TCP for non-web-based(browser) game?

**Comment by mhilbrunner** [comment]
>**Describe the problem or limitation you are having in your project**
>As far as I know, the current High-level multiplayer APIs (Enet) only supports UDP.
>Game developer should be provided with the option of choosing a protocol (multiplayer) suitable for their game project.

Why should they?
Please answer the above: which specific problem or limitation are you facing with the current reliable UDP transport in Godot for your project?

**Comment by Calinou** [comment]
> It is viable to use WebSocket instead of raw TCP for non-web-based(browser) game?

Yes, although it will result in higher latency compared to UDP (just like raw TCP would, in fact).

**Comment by kinqsley** [comment]
> Please answer the above: which specific problem or limitation are you facing with the current reliable UDP transport in Godot for your project? Also, how would these be solved by using TCP instead?

Thank you very much for the response. The issue is, when it comes to anti DDoS solutions most providers like cloudflare and OVH provide cheaper/free protection for TCP based software. 

Few months back worked with a team that used both UDP and TCP for a game, and the issue they had was their cloud provider was able to fend off TCP based attacks for free while when they were getting UDP reflection and amp attacks they were helpless against them. I remember they tried a wide range of cloud providers who offered DDoS protection, but in the end they had to rewrite their code to replace the UDP parts with TCP.

**Comment by Faless** [comment]
As mentioned by @Calinou , WebSocket (which uses TCP) has been supported in Godot for a long time.
WebSocket also requires an HTTP handshake which leaves even more room for access control / DoS protecion by using an HTTP proxy.
Maintaining a `TCPMultiplayerPeer` doesn't seem to give any value over `WebSocketMultiplayerPeer` (which uses StreamPeerTCP internally anyway).

Closing as not planned since the TCP use case is already covered by WebSocket, with a note that it is now also possible to implement custom multiplayer peers even in GDScript using [MultiplayerPeerExtension](https://docs.godotengine.org/en/latest/classes/class_multiplayerpeerextension.html) (`master`)  or [NetworkedMultiplayerCustom](https://docs.godotengine.org/en/stable/classes/class_networkedmultiplayercustom.html) (`3.x`).
