### ISSUE TITLE
Combine Camera2D "limit_top", "limit_bottom", "limit_left" and "limit_right" to a Rect2i "limit"

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#3604]
### Describe the project you are working on

A typical 2D Godot game

### Describe the problem or limitation you are having in your project

The Camera2D's limit variables (`limit_left`, `limit_top`, `limit_right`, `limit_bottom`) are all separate integers, which feels odd, considering they refer to the same thing. Even `editor_draw_limits` property, when enabled, draws a rectangle of them.
![image](https://user-images.githubusercontent.com/66727710/143626066-8533d5e7-6781-474c-aa0a-e9c73016b012.png)

Furthermore, passing these as arguments of _Vector2_ or _Rect2_ functions becomes a somewhat repetitive task, especially noticeable if the camera itself is referenced in a variable.
```gdscript
func something(camera: Camera2D):
	var limit_rect := Rect2(
			camera.limit_left, camera.limit_top, 
			camera.limit_right, camera.limit_bottom
	)
	
	limit_rect.grow(2)
	update_generic_boundaries(limit_rect)
	generic_enemy.act_area = limit_rect
```

Even though these values could be effectively expressed as a **top-left** and **bottom-right** _Vector2_.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Combining all limit properties into a single _Rect2i_ `limit` would make the variables less redundant while keeping its functionality relatively intact.

This would be a breaking change that takes advantage of Godot 4's new _Rect2i_ (_Rect2_ for integers)

### Notes, Drawbacks and other Proposals

- I am unsure about the new name of the property, whether it should be _limit_, _limits_ or something else entirely.
- This proposal was mentioned [in this comment](https://github.com/godotengine/godot/issues/16863#issuecomment-595585595) and in https://github.com/godotengine/godot/issues/16863
- An alternative to this proposal would be to have two _Vector2i_ properties expressing the **top-left** and **bottom-right** points, which may be preferable to the current solution, considering all of the following proposals it would require to make this one more user-friendly.
- - https://github.com/godotengine/godot-proposals/issues/1991 would further improve the usability of limit as a Rect2i.
- - https://github.com/godotengine/godot-proposals/issues/1991#issuecomment-750819499 suggests adding `begin` as a Rect2 property, which is also something worth proposing elsewhere, as it would **greatly** improve the viability of this proposal.
- - I am aware that there's a difference between the _Rect2i_ `size` and `end`. The exported values in the Inspector would actually be the `position` and the `size`, something often not desirable for Camera2D's use cases. For this reason, the ability to export _Rect2i_'s `end` is something that's worth proposing elsewhere.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
	# Example code
	var limit := camera.limit
	update_generic_boundaries(camera.limit)
	
	limit.end.x += 20
	limit.position.x -= 50
	limit.expand(point_of_interest)
```
![image](https://user-images.githubusercontent.com/66727710/143658890-9ad6eba5-73ad-44be-a149-ecc92d380a19.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It roughly can. Not really a few lines of script, and it is somewhat redundant.
```gdscript
extends Camera2D
tool

export var limit: Rect2 setget _set_limit

func _set_limit(new: Rect2):
	limit = new
	
	limit_left = limit.position.x
	limit_top = limit.position.y
	limit_right = limit.end.x
	limit_bottom = limit.end.y
```
![image](https://user-images.githubusercontent.com/66727710/143658836-a5c1de7d-47d6-40f9-afaf-01c7f502a6da.png)

### Is there a reason why this should be core and not an add-on in the asset library?

The Camera2D class is a core feature.

**Comment by golddotasksquestions** [comment]
I get what you are saying, but I'm not sure if this is a good idea tbh. 
`limit.x`, `limit.y`, `limit.w`, `limit.h` is just by far not as explicit self-explanatory and intuitive as `limit_left`, `limit_right`, `limit_bottom`, `limit_top`.

Dealing with camera movement and controls can be tough and challenging for beginners already. This is definitely a feature a beginner would use. I would be in favor of keeping it more explicit and self-explanatory and have it feel somewhat "odd", than making it more tough and less intuitive for beginners, but also less "odd".

**Comment by KoBeWi** [comment]
The problem is that Rect2 has width and height for right and bottom properties, so the camera limit would need to be camera bounds (i.e. top-left and size) to be intuitive as rect.

**Comment by Mickeon** [comment]
Closing, at least for now, as for this to be at the very least nicely doable there would need to be changes to the core class `Rect2`, or a more personalised way this Variant could be exported to the editor.

**Comment by Mickeon** [comment]
Closing, at least for now, as for this to be at the very least nicely doable there would need to be changes to the core class `Rect2`, or a more personalised way this very Variant could be exported to the editor.
