### ISSUE TITLE
Import JSON files as resources

### ISSUE THREAD

**Issue by sneakyspy** [godotengine/godot-proposals#3608]
### Describe the project you are working on

I am working on a quiz-like conversation game where you have to learn English as the game progresses, which requires a considerable amount of working with JSON files. 

### Describe the problem or limitation you are having in your project

Although the current method is usable, I am rather disappointed in the fact that I cant see JSON files in the editor, and I can't directly use them without copying and pasting them into a .trs file where I can't see errors and have to use a function to interpret the .trs file to turn it into a JSON file.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A direct method of seeing JSON files in the editor, and being able to use the path directly from the edditor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Creating a JSON file could be done in the editor, as well as editable in the text editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It could be worked around by making a Data.json.trs and putting the JSON data in there, as well as using this code to interpret it:

func load_json_file(path):
	var file = File.new()
	file.open(path, file.READ)
	var text = file.get_as_text()
	var result_json = JSON.parse(text)
	if result_json.error != OK:
		print("[load_json_file] Error loading JSON file '" + str(path) + "'.")
		print("\tError: ", result_json.error)
		print("\tError Line: ", result_json.error_line)
		print("\tError String: ", result_json.error_string)
		return null
	var obj = result_json.result
	return obj
(code by DriNeo).

### Is there a reason why this should be core and not an add-on in the asset library?

Would be easier for everyone and it might not be doable in the assets library, also it seems like something anyone should have imediately.

**Comment by Calinou** [comment]
JSON files are not considered resources and will probably never be, since Godot has no use for them. Instead, a solution such as https://github.com/godotengine/godot-proposals/issues/677 should be implemented.

**Comment by dalexeev** [comment]
You can create an [import plugin](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/import_plugins.html).

**Comment by Xrayez** [comment]
Such plugin already exists, see https://github.com/godot-extended-libraries/json, but it's written in C++.

Due to this, perhaps this could be integrated in [Goost](https://goostengine.github.io/), but it's likely best to ignore JSON files by default. In Goost specifically, JSON could likely be imported as a [`VariantResource`](https://goost.readthedocs.io/en/latest/classes/class_variantresource.html).

But it makes me wonder: do you really need to *import* JSON files as a custom `Resource`, or do you only need to edit JSON files from within the Godot's text editor?

**Comment by sneakyspy** [comment]
If a JSON file were a variant resource it could help with communication
between programs and could help with memory space. I am assuming that the
more code you write contributes to the memory used, so if you could have a
Godot integrated ParseJSON(path): then it would stop you from having to
re-write the code to parse the JSON every time you need to look at it.
Additionally, a public ParseJSON could help with making Godot more
accessible to more people, instead of having to search the public forums
for a code that works, most of the time it has some sort of problem with
the way you are doing it. While the Godot community is very helpful, They
don't always help with troubleshooting and bugs that were not specified in
the question. Although to answer your question, if we were to rule out
communication between programs, then we only need to be able to edit JSON
files, or .json.trs(my way of saying it is JSON related).

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/65295.
