### ISSUE TITLE
Improve default tonemapping settings in the 3D editor preview

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3611]
### Describe the project you are working on

A 2.5D game, right now . . .

### Describe the problem or limitation you are having in your project

Uhh, I've been comparing Vulkan, and OpenGL, and there are ton, of advantages to Vulkan, sdfgi, and fps . . .

But, I have a problem with it, for some reason I'd say, it has almost like bit post - proc. on, by default . . Maybe satuation, and it looks like the pixels are smoothed, maybe AA, don't know . . . For that reason, I like the simpler, less 'make-up' look of OpenGL . . I realize Vulkan is the standard, and, I don't understand those settings, I was wondering if there might be some settings, to tone it down, and make it look bit more like OpenGL, while, keeping the speed . . .

![image](https://user-images.githubusercontent.com/83387915/143894222-73b73393-1480-45e0-a3ab-2a8d8a14b39f.png)

It's difficult to find an image, but the pixels look sort-of blurry, not sharp . . It's new standard, so it's prob. the best, as default, but could one make some settings, to get that neat OpenGL, clear, and sharp pixels, also less post - proc., it sort-of looks like this . . .

![image](https://user-images.githubusercontent.com/83387915/143894521-396ea1fe-8e36-4dad-a66b-574e969ecfb7.png)

I think, it might make Vulkan slower, so hoping for some settings, to make it ideal graphics, as I see it, sort-of like OpenGL, bit more saturation, and more light, in high tones and, more defined or, ' accurate ' shadows . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, it'd help me get the graphics I want, maybe the few additions, to OpenGL, that'd make it the best, ideas above . . .

It'd help me get the graphics I want, and imo. make it better, that's subjective but, it's such a big minus, I don't feel like using Vulkan, it makes things ' over-done ', or not sure, fancy . . I just want an honest, cool rendering engine, no bull - shit, maybe there are some Vulkan settings one need to make adjustable, so it'd happen . . Thanks . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, not sure what it'd be, not a Vulkan expert, I just find it annoying, and don't really want to use it . . It's sort-of negative, bec. it's faster, but, at same time doesn't give visuals, I want . . Perhaps also more defined textures and, lighting, bit more ' sharp ', or clear, also effects, so it looks geeky and, runs well <3 Thanks . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't really do much, about how Vulkan renders or, makes the lights, in general . . Just hoping there will be some settings, since an engine is used by nerds, I think it should appeal to them, while also having that ' AAA ' look, sort - of pro . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, not sure, it's just a request, really think OpenGL looks nicer, it's more ' math ', less sort-of effects, polish . . . <3

I think Vulkan is nice, but it's a bit too much, ' creepy ' or, dis-honest, that's the point . . . .

**Comment by Calinou** [comment]
Filmic tonemapping is enabled by default in the 3D preview, but the whitepoint is set to 1, which creates blown out highlights. https://github.com/godotengine/godot/pull/49736 aims to adjust this to make tonemapping more useful.

**Comment by charlesmlamb** [comment]
Ok, the point is this, OpenGL has this really nice, pixelated look, like each pixel was sharp . .

![image](https://user-images.githubusercontent.com/83387915/143972548-32fc0766-a9b7-4441-89b4-6501894fabb8.png)

Vulkan, has some sort of weird effect, like this, or so . . .

![image](https://user-images.githubusercontent.com/83387915/143972622-3407864b-3ec6-44e7-9322-89be6220e1bf.png)

Like, there's post - proc., or almost a well photoshop filter on it, I know Vulkan is the new standard, just wish there were some settings, to make it look bit more ' math ', also, both things are prob. nice, just like those old - school, pixel looks, pixel art, the other stuff is prob. good for most people, but, some like the nostalgia, also classic OpenGL look, without losing the FPS improvements, and sdfgi, from Vulkan, <3

**Comment by charlesmlamb** [comment]
Sorry, uhh it's almost like Vulkan has the Unreal engine look, or Hollywood, sort-of post. proc., blur, not sure . . .

![image](https://user-images.githubusercontent.com/83387915/143974973-3cac4baa-d8b1-4a5f-a096-3cdc1b59e0ac.png)

![image](https://user-images.githubusercontent.com/83387915/143975027-5344ad47-4958-4c0b-8507-8544a059b270.png)

Like everything has been tonemapped, but also ' blurred ', like too much AA, it's unsharp, I want a video - game engine, that looks sharp, like ' good ' math, not some blurry hell . .

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/348, which already tracks the default tonemapping settings that could be changed.
