### ISSUE TITLE
Get Function Argument Type(s)

### ISSUE THREAD

**Issue by CrezyDud** [godotengine/godot-proposals#3614]
### Describe the project you are working on

Console where you can call functions from ingame

### Describe the problem or limitation you are having in your project

i need to get the argument types
preferably without creating an array and hardcoding that stuff in it

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

can't do that know (as far as i know)
would be happy for this, so i wouldn't have to hardcode that in some array

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
```
func clear(bg: Color)
 blabla

func entered_command(commands)
 blabla
 if command in self:
  for i in get_func_arg_types(command).size():
   if args[i] !is get_func_arg_type(command, i)
    return
 callv(command, args)
```
### If this enhancement will not be used often, can it be worked around with a few lines of script?

not as far as i know
other than some shiddy spereate array

### Is there a reason why this should be core and not an add-on in the asset library?

no other way of doing it as far as i know
without extra manual work every time i add/modify a function

**Comment by CrezyDud** [comment]
so, in total all i need is:
`get_func_arg_types(function: string)` 
`get_func_arg_type(function: string, argument: int)`  <- `argument: int` starts at `0`

**Comment by Xrayez** [comment]
Such ability already exists via `ClassDB` and/or `Script` API:
```gdscript
extends Node2D

func _ready():
	for method in get_script().get_script_method_list():
		if method.name == "clear":
			print(method.args)
			assert(method.args[0].type == TYPE_COLOR)

func clear(bg: Color):
	pass
```

However, this doesn't seem to provide proper information about method signatures ("bg" variable is empty), may be a bug. But this properly returns the type.

**Comment by CrezyDud** [comment]
for me it doesn't work
output is
```
[{class_name:, hint:0, hint_string:, name:arg0, type:0, usage:7}]
```
[godot 4.0 btw.]

**Comment by CrezyDud** [comment]
i used to use get_method_list()
which seems to be different from get_script_method_list()
lol

**Comment by Xrayez** [comment]
Yeah, `get_method_list()` would return method info for the built-in class only. I kind of agree that there's a potential discrepancy for built-in vs custom/scripted classes, see proposals like #2804.

**Comment by Xrayez** [comment]
In cases like this you can infer the required number of args `required_argcount = argcount - default_argcount`

But looks like `get_script_method_list()` does not populate `default_args` (always empty), again likely a bug.

**Comment by CrezyDud** [comment]
`typeof(args[i])`
always returns `4`

**Comment by Xrayez** [comment]
> `typeof(args[i])` always returns `4`

Expected, because `typeof()` is meant to be used on object instances, but `args` only provides type information. You should use `args[i].type` in this case and see if it matches with any `TYPE_*` constants.

*For the record, it wasn't me who marked your previous message as off-topic.*

**Comment by CrezyDud** [comment]
> _For the record, it wasn't me who marked your previous message as off-topic._

that was me, trying to keep this clean, yet my problems solved

**Comment by CrezyDud** [comment]
Invalid index 'type' (on base: 'String')

**Comment by KoBeWi** [comment]
As discussed above, this already exists, but is bugged.
I found some old issue: https://github.com/godotengine/godot/issues/33624
Closing.
