### ISSUE TITLE
First-Class Signals, like what was done to Methods.

### ISSUE THREAD

**Issue by diddykonga** [godotengine/godot-proposals#3618]
### Describe the project you are working on

N/A, just an average Game Engine enjoyer.

### Describe the problem or limitation you are having in your project

When coming from other languages/engines Signals can be kind of confusing considering they only exist as a system built into Objects of the Engine, and not as a First-Class Type of the Engine. They have a close similarity to Delegates or Events in other languages, but are used in a less explicit way. This also adds slight bloat to the Object class, which should always be kept from becoming too monolithic.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To me this provides a clearer understanding of exactly what it is your code is doing, and should hopefully even allow the Editor to provide better Code Suggestion/Completion and prevent typos of Signal names. As well as removing the methods for Signals from the Object class, which would make it less monolithic.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

First-Class Signals should provide this syntax:
`object.signal.connect(object.function)`

Compared to the current:
`object.connect("signal", object.function)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is a syntax change primarily, so of course.

### Is there a reason why this should be core and not an add-on in the asset library?

Signals are a part of Core.

**Comment by pycbouh** [comment]
That is already the case in master.
