### ISSUE TITLE
Undo stack should keep focus of active window

### ISSUE THREAD

**Issue by veryprofessionaldodo** [godotengine/godot-proposals#362]
**Describe the project you are working on:**
Some art style tests using shaders. 
**Describe the problem or limitation you are having in your project:**
If I'm working on the shader and then rotate or move an object, in the 3D Scene, whenever I hit Ctrl+Z to undo, it undoes the last action on the shader editing, and I can't undo the transformation unless I quit the shader editor. 
**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If I could undo what is currently being focused on, or even undo sequentially (as in, undo first the transformations, and then the shader changes), it would save me time of going back and forth closing tabs, and deliver a cleaner UX.
**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Like I said in the previous comment, open a shader editor, transform an object in the scene, and then undoing would undo the transfomation.
**Describe implementation detail for your proposal (in code), if possible:**
Haven't looked into it, but I assume that the undo event is being caught by the shader editor, and that there are two stacks for the different contexts. 
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not that I know of.
**Is there a reason why this should be core and not an add-on in the asset library?:**
It should be relatively simple, and it's an addition to the core UX of the engine.

Also, I love Godot, thanks for everything!

**Comment by KoBeWi** [comment]
This is actually a bug. The shader editor is stealing input focus, so you can't undo the scene. See https://github.com/godotengine/godot/issues/17591 for example.
