### ISSUE TITLE
Make animation preview not affect default values in inspector

### ISSUE THREAD

**Issue by POWERUPT** [godotengine/godot-proposals#3621]
### Describe the project you are working on

I am working on a Punch-Out style game that will be on Steam in the future that is driven pretty much entirely by the animation player. Every action as an animation associated with it, and so things are timed in sync with them, values from scripts and some functions that are called are put into the animations.
![image](https://user-images.githubusercontent.com/36461106/144327631-4ac95138-9741-42e3-842f-3a76100e1826.png)

### Describe the problem or limitation you are having in your project

The animation editor is really great, but the issue is that, when editing an animation, the editor shows the animation with the scene that you are working with. This makes sense in theory, but when a keyframe is selected when variable from a script is changed, or a kinematic body is moved, or a hitbox is enabled, it will stay that way even when you deselect the animation player, and will even be there for runtime.
I can't count the times that I clicked the animation player node for the player, and the first alphabetical animation is queued up, which is the one time the Boolean for countering is true, then I play the game and the player counters every attack. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

At the very least, the state for the node(s) that's being animated should be saved then restored when the animation editor is closed.
It would be great if there was a separate window that opened that previewed the animation in a contained fashion. The nodes are instanced in a new window, and their values can be manipulated, and when the window is closed, nothing is altered.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/36461106/144328893-6361f542-7312-4b69-b01e-f6eae526a683.png)
![image](https://user-images.githubusercontent.com/36461106/144329012-a48a86ea-1b57-41fa-8653-195223cfc503.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think this addition will be used a ton by anyone who uses the animation editor.
It may take more than a few lines of code though.

### Is there a reason why this should be core and not an add-on in the asset library?

Although it is not a bug, it definitely addresses a sizeable design flaw with the animation editor. This mends an annoyance that has cost me quite some time with my development.

**Comment by Calinou** [comment]
This is already implemented in Godot 3.4 with reset tracks: https://github.com/godotengine/godot/pull/43115

**Comment by POWERUPT** [comment]
@Calinou Ah, I didn't see that was in there already. Thanks for pointing it out!
