### ISSUE TITLE
Remember the scenes opened the last time Godot was closed

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#3622]
### Describe the project you are working on

It is a general suggestion, not a particular one.

### Describe the problem or limitation you are having in your project

When Godot is running, Godot will automatically open scenes that were opened at the time Godot was last closed.

Godot currently does not remember this and only automatically opens the main scene.
Then you must open every time Godot starts, all the scenes you need.
An option could also be added to enable this behavior.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When Godot closes, it will check which scenes are open and save the information.
That information will be restored when Godot is started again.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

...

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

IDK

**Comment by pycbouh** [comment]
You mean this?

![image](https://user-images.githubusercontent.com/11782833/144411427-78b4b8f9-6333-4a50-ac62-522b298dfb86.png)

**Comment by KoBeWi** [comment]
This option already exists. It's enabled by default in 4.0
Closing.

**Comment by Torguen** [comment]
Ohh ok, I looked for "scene" in the editor options but I missed it.
