### ISSUE TITLE
Upgrade code should keep classes if scons has `deprecated=no`

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#3623]
### Describe the project you are working on

3d multiplayer game

### Describe the problem or limitation you are having in your project

We build with scons deprecate on and Godot was unwilling to upgrade older scenes when deprecated is on.

This makes feature allows automatic upgrade to happen even when deprecated code is excluded.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Keep the lookup table for compatibility classes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot/pull/55546

The code isn't that much. Seems like text replacement.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Is a few lines of C++ code in the core.

### Is there a reason why this should be core and not an add-on in the asset library?

`add_compatibility_class` is in core.

**Comment by akien-mga** [comment]
The whole point of the `deprecated` flag is for code like this. So what you need is to just not build with that flag if you want to keep compatibility code.

**Comment by akien-mga** [comment]
I expanded the description of the option to clarify its use case in https://github.com/godotengine/godot-proposals/issues/3623.

**Comment by fire** [comment]
@akien-mga was the self link intended?

**Comment by akien-mga** [comment]
No, fixed it.
