### ISSUE TITLE
Angular velocity is difficult to calculate when throwing rigid bodies in VR games

### ISSUE THREAD

**Issue by balintbarna** [godotengine/godot-proposals#3626]
### Describe the project you are working on

I'm working on a VR game where it is possible to pick up and throw rigid bodies, such as swords.

### Describe the problem or limitation you are having in your project

When the body is picked up, the mode is set to "static body", and when it's released, the mode is reverted (usually to "rigid body").
Without setting the velocities manually, the body just falls down. Setting linear velocity is easy enough by numerically differentiating the positions in the last 2 frames. Doing the same for orientation/rotation is difficult. The calculations needed are significantly more complicated, representations and calculations have to be custom implemented, and the documentation is insufficient.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

# 1: Update the docs
The representation of angular velocity is unclear in the docs. According to my testing it is an axis-angle representation where the magnitude of the Vector3 object represents the size of the rotation in radians. This is not documented and I couldn't find it online anywhere.
# 2: Add axis-angle representation related functions
Conversion between Basis, Quat, and AxisAngle should be as easy as calling a function on any of those class instances, eg: my_quat.to_axis_angle().

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is my working code for calculating the angular velocity based on the current basis and the previous frame basis:
```gdscript
func calculate_angular_velocity(orientation_new: Basis, orientation_old: Basis, time_new: int, time_old: int):
    var time_elapsed = (time_new - time_old) / 1000000.0 # convert microseconds to seconds
    var orientation_new_relative_to_old = orientation_old.inverse() * orientation_new
    var axis_angle_new_relative_to_old = quat2axis_angle(Quat(orientation_new_relative_to_old))
    var angular_velocity_in_relative_frame = axis_angle_new_relative_to_old / time_elapsed
    return orientation_old * angular_velocity_in_relative_frame # axis transformed back to global frame, but retains magnitude


static func quat2axis_angle(q: Quat):
    var v = Vector3(q.x, q.y, q.z)
    var angle = 2 * atan2(v.length(), q.w)
    return v.normalized() * angle
```
Instead, this should be
```gdscript
func calculate_angular_velocity(orientation_new: Basis, orientation_old: Basis, time_new: int, time_old: int):
    var time_elapsed = (time_new - time_old) / 1000000.0 # convert microseconds to seconds
    var orientation_new_relative_to_old = orientation_old.inverse() * orientation_new
    var axis_angle_new_relative_to_old = orientation_new_relative_to_old.to_axis_angle()
    var angular_velocity_in_relative_frame = axis_angle_new_relative_to_old / time_elapsed
    return orientation_old * angular_velocity_in_relative_frame # axis transformed back to global frame, but retains magnitude
```
The documentation should also be updated to reflect the representation of the angular velocity, as well as provide this example code for calculating it from 2 orientations

Even better would be to abstract away these complex frame transformations and just provide a function for calculating "the relative rotation in global frame" or directly "the angular velocity" such as:
```gdscript
func calculate_angular_velocity(orientation_new: Basis, orientation_old: Basis, time_new: int, time_old: int):
    var time_elapsed = (time_new - time_old) / 1000000.0 # convert microseconds to seconds
    var incremental_rotation = orientation_new.get_relative_rotation_in_global_frame_from(orientation_old)
    return incremental_rotation / time_elapsed
```
or
```gdscript
func calculate_angular_velocity(orientation_new: Basis, orientation_old: Basis, time_new: int, time_old: int):
    var time_elapsed = (time_new - time_old) / 1000000.0 # convert microseconds to seconds
    return orientation_new.get_angular_velocity_from(orientation_old, time_elapsed)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around but it is ugly as well as undocumented, making it difficult to implement the first time around

### Is there a reason why this should be core and not an add-on in the asset library?

built-in types and docs are lacking

**Comment by Calinou** [comment]
cc @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment]
This is more of a core/math question, but I don't see why not exposing at least `Basis::get_axis_angle` to scripts, which would return a `Vector3`, set from the normalized axis (direction) and the angle (length).

**Comment by balintmaci** [comment]
I haven't made PRs for Godot before, but this could be a simple way to dip my toe. If I have some questions should I just write in the chat or is there someone to talk to directly?

**Comment by pouleyKetchoupp** [comment]
@balintmaci Yeah you can definitely discuss things in the chat if you haven't already, and link to this proposal. Would be worth having more feedback from other core contributors too to make sure there's consensus on adding a new math function.
