### ISSUE TITLE
Add support for multi-line Tree column titles

### ISSUE THREAD

**Issue by TBleader** [godotengine/godot-proposals#3632]
### Describe the project you are working on

Space 4x game, I use  `Tree` a lot for displaying information!

### Describe the problem or limitation you are having in your project

Column titles do not support the new line character / line breaks, this makes formatting more difficult.
![2021-12-03-18:32:32-screenshot](https://user-images.githubusercontent.com/5839706/144693846-5049490a-dfe2-4d84-9824-a56b98a54d67.png)
Top: An `HBoxContainer` with a bunch of labels that were set to center, and translating the column title localized string.
Bottom: The `Tree`'s column row set to translate the same localized string as above.
The localized strings all include a line break (as in I just hit enter when editing them in the CSV), however something like `\n` doesn't work either, nor inputting the unicode character for a new line.
Here are some examples copied straight from the CSV file:
```
LABEL_MINERAL,Mineral
LABEL_QTY,Quantity
LABEL_ACCESSIBILITY,Acc.
LABEL_PRODUCTION_YEAR,"Annual
Production"
LABEL_DEPLETION_YEAR,"Time To
Depletion"
LABEL_STOCKPILE,Stockpile
LABEL_PROJ_USAGE,"Projected
Usage"
```

I would expect them to more or less look the same, barring the issues with `Tree` column titles like text getting cut off. Now I believe the titles getting cut off are fixed in the `master` branch, and I know a lot of other nice fixes for trees have been done there so I am not able to benefit from any of this until it either gets backported to `3.x` (oh man pleeease lol) or 4.0 is stable enough to try and consider porting. However from what I could tell this issue remains in 4.0? I will admit I have not had the chance to compile and check with the current `master` build. If this is already fixed in `master` then great and I'll update this to instead be a request to backport some of the nice tree improvements to `3.x` :stuck_out_tongue: 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the support for new lines for `Tree` column titles just like it exists for `Label`, ie they should behave identically in the above screenshot (barring the other formatting like centering the text of course)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/5839706/144694231-62e5703a-7574-4f97-aea4-73dbf87a0327.png)

Top: An `HBoxContainer` with a bunch of labels that were set to center, and translating the column title localized string.
Bottom: The `Tree`'s column row set to translate the same localized string as above.

Same image as above, except I modified it so it is how it should look, with the `Tree` column titles properly using a new line.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I am aware of, but if there is a way to get it to work please let me know! I've tried `\n` `\r` `\u000a` and using the enter key in the CSV file to create the new line (which I imagine is doing one of the previous options)

### Is there a reason why this should be core and not an add-on in the asset library?

It's pertaining to the `Tree` type's functionality, a core engine feature.

**Comment by KoBeWi** [comment]
I'm fairly sure this is fixed in 4.0, as there were many changes related to text layouts. You can use a nightly build to check: https://hugo.pro/projects/godot-builds/
