### ISSUE TITLE
Modernize the V/H SplitContainer to allow for zero-border resizing

### ISSUE THREAD

**Issue by lentsius-bark** [godotengine/godot-proposals#3635]
### Describe the project you are working on

Productivity application (Mad Productivity)

EDIT: Forgot to mention that this applies and would be useful for game UI as well, it's an issue of modern interfaces altogether, be it apps or games.

### Describe the problem or limitation you are having in your project

V and H SplitContainers do not allow for zero border resizing, any attempt to do so will render the container useless and the user needs to implement their own custom solution.

As Godot picks up in popularity the userbase would greatly benefit from having the toolset which allows for the creation of modern interfaces out of the box, which it does! (making good looking apps in godot is such a pleasure, euphoric possiblities) Modern apps more often than not make use of zero or "minimal" (1-2px visual with a slightly larger area for capturing the mouse) border resizing. 

If youre looking for reference try opening just about ANY (I bet you'll find the one exception now) application on your system and there's a very high chance that any resizable panels have just a pixel wide line (or transparent).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow the H and V Split Containers to be set up in a way that allows for no or minimal borders.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://user-images.githubusercontent.com/38346332/144714552-d6666c21-b541-4c78-a35c-25fb6c8daffd.mp4

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's the bread and butter of application UI, one can create a custom solution however it's finicky to set up and should it be needed in multiple areas of their project it could grow bug ridden. Prone to errors due to moving nodes about and coding UI is rarely ever clean.

### Is there a reason why this should be core and not an add-on in the asset library?

Enables and simplifies the creation of modern and professional looking products that heavily rely on UI elements.

**Comment by pycbouh** [comment]
From the looks of it, you can set the separation to be 0 and use an empty/1px wide icon. But the trigger area is bound to the size of the gap which is bound to the size of the texture used for the grabber. And as such, you can't really interact with 1 pixel-wide trigger area. Another idea would be to have a margin container as a child, that expands over a part of the gap.

Those are workarounds, of course. But I'm not sure how to expose something like that. Do we add a constant that defines the size of the trigger area (regardless of the icon)? This may not be obvious for users who expect it to respect the icon. Do we replace grabber icon with a stylebox that would define the entire grabber area? That may make it more complicated to work with than needed.

So, not sure. Don't have an obvious solution yet.

**Comment by lentsius-bark** [comment]
@pycbouh 

> Do we add a constant that defines the size of the trigger area (regardless of the icon)?

I really like this idea. If there was a constant to define the area size and you could make the visible area just 1px thin it'd already allow for making modern split containers

> This may not be obvious for users who expect it to respect the icon.

I've been using the themes for a good while now and still need to do a little deep dive into trial and error for the split containers as well as designing custom scroll bars (those took me a while to decipher)

> Do we replace grabber icon with a stylebox that would define the entire grabber area?

This one may very well be the best solution form the ones you mentioned. It feels elegant and easy to understand.

**Comment by Calinou** [comment]
> Do we add a constant that defines the size of the trigger area (regardless of the icon)?

It can be a constant whose value is ignored if it's equal to 0, in which case the icon's width is used instead.

**Comment by Calinou** [comment]
> @Calinou meaning that if the value was 2 and no icon, then there is a 2 pixel gap that can be grabbed to resize?

Yes :slightly_smiling_face:

**Comment by lentsius-bark** [comment]
thinking a little more about this I think there could be a toggle "use texture space" that way its clear which one is being used instead of hidden conditions, what are your thoughts on this @pycbouh ?

**Comment by pycbouh** [comment]
That toggle would need to be a part of the theme, so a theme constant. But we don't really have boolean constants, it's all integers (even though some act as a boolean). So something like that would be cumbersome and not user-friendly to set up.

**Comment by lentsius-bark** [comment]
> That toggle would need to be a part of the theme, so a theme constant. But we don't really have boolean constants, it's all integers (even though some act as a boolean). So something like that would be cumbersome and not user-friendly to set up.

yeah that makes sense, aha! I don't mean to be throwing random ideas. feel free to stop me, to expand on what Calinou said, 
 noting new is added in terms of settings but if there's no texture then the "separation" amount creates a selectable area. IMO this is how one would imagine it to work. 
It wouldn't affect those using it now as everyone is using textures and would expand on its usability.
