### ISSUE TITLE
Return collided object for VehicleWheel

### ISSUE THREAD

**Issue by rydergaming** [godotengine/godot-proposals#3640]
### Describe the project you are working on

I am working on a 3D racing game using the built in VehicleBody and VehicleWheel classes.

### Describe the problem or limitation you are having in your project

I cannot get what the `VehicleWheel` is in contact with form the wheel itself.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

While I can check if a collision is happening with VehicleWheel's `is_in_contact()`, I can not get what the wheel is actually colliding with.

By adding a new method we could return what object the wheel is colliding with.

A common use case for this would be to check if the wheel is on tarmac, dirt, grass, etc. and we could update it's `wheel_friction_slip` accordingly.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I can see two solutions for this:

- Update the `is_in_contact()` to return either `null` or the object the collision is happening with.
- Create a new method that returns `null` or the object the collision is happening with.

I have limited C++ knowledge, but it seems to me returning `wheel.m_raycastInfo.m_groundObject` would solve this.

This is a piece of `real_t VehicleBody3D::_ray_cast(int p_idx, PhysicsDirectBodyState3D *s)` from `scene/3d/vehicle_body_3d.cpp`
```
	bool col = ss->intersect_ray(ray_params, rr);

	wheel.m_raycastInfo.m_groundObject = nullptr;

	if (col) {
		param = source.distance_to(rr.position) / source.distance_to(target);
		depth = raylen * param;
		wheel.m_raycastInfo.m_contactNormalWS = rr.normal;

		wheel.m_raycastInfo.m_isInContact = true;
		if (rr.collider) {
			wheel.m_raycastInfo.m_groundObject = Object::cast_to<PhysicsBody3D>(rr.collider);
		}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

A workaround could be achieved with adding a RayCast to each wheel manually, but it seems redundant if there's one already in the VehicleWheel class.

### Is there a reason why this should be core and not an add-on in the asset library?

As the VehicleWheel is already in core it makes sense to add this improvement to core as well.

**Comment by rydergaming** [comment]
I would be happy to implement this improvement to flex my C++ muscles if it gets accepted as something that's needed.

**Comment by Calinou** [comment]
cc @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment]
Yeah, that sounds like a good idea! A PR would be welcome.

I would go for adding a new method called `get_contact_body()` that returns a `Node`, so it will be more flexible for later if we want to support both `PhysicsBody3D` and `GridMap` later.

See the body entered signal on rigid bodies as a reference for documentation:
https://github.com/godotengine/godot/blob/46d384060ef20672e23b3c1ffe947ff7898ecf75/doc/classes/RigidDynamicBody3D.xml#L169-L175

**Comment by rydergaming** [comment]
Great! I will get on it and hopefully I'll have something in the following days!

**Comment by arjun988** [comment]
hi I am arjun  , I am having intermediate knowledge in C++ pls tell me what should I learn so that I can contribute . it would be very helpful if u can guide me.

**Comment by rydergaming** [comment]
I successfully implemented this feature and sent in a PR [here](https://github.com/godotengine/godot/pull/55723).

**Comment by pouleyKetchoupp** [comment]
> hi I am arjun , I am having intermediate knowledge in C++ pls tell me what should I learn so that I can contribute . it would be very helpful if u can guide me.

Hi Arjun! You can read [this article](https://docs.godotengine.org/en/stable/community/contributing/ways_to_contribute.html#contributing-code) about contributing to the code. I would suggest to start with checking issues from the main repo with the `junior job` label to get familiar with the engine.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/55723.
