### ISSUE TITLE
Suggestion to add support for the new Steamdeck, hand-held stuff . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3641]
### Describe the project you are working on

A 2.5D game, with barbarians . .

### Describe the problem or limitation you are having in your project

Uhh, not sure this is being worked on, I really like the new Steamdeck, and want to focus on making content for that, it's sort-of niche, but it's quite amazing, also, maybe Nintendo switch . . .

I was wondering, if Godot will get support for sort-of direct Steamdeck export, it's basically the platform I want to develop all my titles for, wanted, to ask, not sure if it's super - complex, from what I know it's a custom Linux version, so, it might be difficult, since it's made for 3D, I think video - games, anyway like new Steamdeck, wanted to ask for a good exporter, for my 3D projects, not sure it'll be used much for 2D, well looks made for 3D, well hoping for an exporter, maybe to a USB card or, a download format . .

On a side note, it's cool there's a page one can export to Nintendo switch, but it's sort-of annoying they take 30 %, I realize it's maybe a nice thing, but I think that price means the community will try to get less titles on Nintendo bec., it's an unappealing offer, below 5000 dollars they take 70 % . . So, at least for me, even though I also want to make stuff, for Nintendo switch, atm. I'm sort-of iffy about it, feels like ' burning ' money, not sure, that's all . . I realize it's a legit way of getting things on the Switch, but it's so much, 30 %, just don't feel like doing it, rather just well not do it, maybe it's bec. I hate greedy businesses, or sort-of corrupt ways, of ' running ' things, oh well . . Really wanted to port to switch, atm. it feels like, mehh . . So, I think there's a need for a better export work-flow to switch, in the community, where maybe there's a basic exporter, and then one wouldn't need a greedy company, or jerks, to ruin the fun and, make one not publish stuff on Switch, it's a shame bec. it's a nice little system but, atm. I just don't want to, feels like I'm getting screwed, nothing will change that, not a fool . .

Anyway, was thinking if one could get a plug-in, that did 80 %, maybe more, of export process, then one could do the last oneself, anyway right now just don't want to publish on Nintendo, feels like getting screwed, over money, I also think it's a shame for the community that someone has opened a page, takes money for it, and then it ends up hurting the community, leading to the problem, that one can't get official support, bec. someone is already doing it . . It just well, prevents people from publishing on Switch, bec. it's a ' bad ' deal, so until that is better, gonna forget Switch, and go for Steamdeck, 100 %, PC, Linux, so on . . . Thanks . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, not sure how difficult it is to export to Steamdeck, really like the system, looks good, runs fairly well . . Hoping there'll be really good support, bef. some jerk page makes it, and one has to pay 20 % of everything, to them, and end up not wanting to make stuff, for Steamdeck, etc . . .

I understand the page, gotm.io sort-of offers a deal, and, sure . . But, I'm not giving anyone 30 % of my work, in fact 70 % of first 5000 dollars, I know when I'm being screwed, it's not their work, and the page is getting in the way, of an official exporter, and well that hurts the community . . So, now we're stuck with a bad bargain and, it'll just mean, fewer people will publish on Nintendo, or it will be fools, that don't understand money, or say value of work, or effort, oh well . .

Sorry, for rant, I wanted to publish on Nintendo but, right now, it's just . . Why bother, feels like getting robbed, so on . . . I know this is a bit negative, but I think it's a problem, that people feel ' bad ' about publishing on Nintendo, has nothing to do with me, 30 %, no way I'm giving that to some people, that just tweak my game, and give it a logo - icon, if that's what I want . . The answer will be, I will prob. not try and publish on Nintendo, esp. since I can do it for free, on PC, Linux, Mac and, maybe Steamdeck, don't know . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, just hoping there'll be a good exporter, for the Steamdeck, heard it was some Linux stuff, or at least an exporter that does as much of the work, code, as possible, so one only needs an external partner, for very little stuff, to prevent the well problems with Switch, where it is currently, perhaps not that much, but is driving people AWAY, from publishing there . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's too complex, that's all . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, my major platform, will be the Steamdeck, it runs in 1280x800, and I want to run most content, in 1280x720, so it's sort-of a really good platform, assume it can be connected to a tv, and even have, external controllers, making it a really neat hand-held system, that has a ton, of well good stuff . . . So, before some gotm.io swoops in, and takes 40 %, I'm hoping we can get good support, it's a bit sad how Switch is now, sort-of a, ' wish I didn't export ' there, bec. of a page . . .

Thanks, as always, thanks for listening, I'm aware I sort-of push it but, this bugs me, wanted to publish on switch, now I don't want to, oh well . . :-(( . . .

**Comment by pycbouh** [comment]
Steam Deck is just a Linux PC in a handheld form factor. You don't need to explicitly supported, especially with Godot, that natively supports Linux. Many Godot games can already run on the Deck. Incidentally, we have a dev kit and several games have been tested and run great. There are still steps for some of them to be verified by Valve, but that's unrelated to Godot. They just need to follow usability guidelines, same as any other game that needs to be verified for Deck.

**Comment by charlesmlamb** [comment]
Ok, that's really nice, want to publish on Steamdeck, it's rather cool . . .
