### ISSUE TITLE
Errors in pixel - rendering on Vulkan / is this a bug . . 

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3642]
### Describe the project you are working on

A 2.5D game . .

### Describe the problem or limitation you are having in your project

Ok, to make a small rant short, I get these results, in rendering . .

![Animation (8)](https://user-images.githubusercontent.com/83387915/145085632-bdd971b0-2e62-4fcf-8a16-4ec08be19f81.gif)

Well, in OpenGL, that's where there's small rant, one can get really nice, or ' stable ' pixel rendering . . Sort-of, the pixels don't disappear, and one can well clearly see the intended graphics, here a texture, with some lines . .

I'm not sure if this can be fixed, by setting the import settings for textures to anisotropy on, and AA, etc . . I tried setting that for a scene, a .gltf from Blender, but I'm not sure the textures, in the materials, are imported with anisotropy, and mipmaps, if I set it in textures . . So, if that's the problem, suggestion is, add a setting to .glb import, so one generates mipmaps, and also has anisotropy set to on . . .

Now, here's the problem, Vulkan in tests is 50 % faster, than OpenGL, it's a massive boost, almost like getting a new graphics card, it's quite nice . . But, here's something I hope you might think about, all these tech features, better specs, all that stuff . . Doesn't really matter, if it looks uglier, in the final render, compared, to OpenGL . . . Right now, bec. of this, sort-of ' disappearing ' pixels, it looks random and, ' un - cool ' I'd rather use OpenGL, than Vulkan, even if it's faster . .

So, what I hope is, bef. you realize Godot 4, or in Godot 4.1, make it so Vulkan looks as nice as OpenGL, it's of course faster, but if the final image is uglier, or more ' chaos ', it ends up not making sense, also the default, made another post about this, it looks like Vulkan has some post-proc. on by default ( saturation, contrast, shadows and, extra sharp reflections ), and I like those things, to me the ideal work-flow is, one works in a place, with no post - proc, just a clean, ' honest ' image or, render . . And, then if one wants, one adds post - proc. later, in some way it feels like Vulkan is pushing one in direction of ' Hollywood ' or, post proc. - decisions, that should be made later, and gets in the way, of having simple, neat fun . .

So, I hope devs will look at this, make Vulkan as nice, as possible, sort-of the modest improvements one can make to OpenGL, to make it better, imo. OpenGL can get maybe 2 - 3 % better, anyway wanted to ask the devs to realize, it's not just about how fast it is, it's also a question, does the final image look good or, ' cool ' . . For most people, that's just honest pixels, clean vectors, no ' added ' non-sense, or effects . . Well, that's how I think, atm. I'm 2 % in favor of using Vulkan, bec. of these things, the extra speed, perhaps ' theoretical ' fidelity, means nothing if it looks ' weird ', or, so on . . 

Anyway, just hoping the devs will look at Vulkan, not just as some ' tech ' or, faster code . . But also, does it actually make graphics better, when one looks at the image, after the rendering, etc . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, just hope the devs will tweak Vulkan, so it doesn't just runs fast, or so . . But, also looks good, and bec. appealing, in the end all that code means nothing, if it makes a render that runs faster, but sort-of looks uglier, less ' clean ', that's all . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just hoping the engine devs won't just see Vulkan as some ' tech ', but also have maybe a discussion, of how to make the most of it, right now I'm against using it, the FPS stuff is neat but, the projects just look worse, in the final render, weird pixel 'errors', added post - proc., I don't like, it's weird one has to turn post-proc. off, to see the honest, 'normal' picture, at least that's not the work - flow I had imagined, so right now Vulkan is maybe faster, but it's not appealing, bec. OpenGL still looks better, less ' weird ', chaotic . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't do this, I just hope the devs will think about, now that Vulkan is there, to make the image good, I guess it's the last step, so we get a nice Godot 4, that appeals to all, also the nerds, geeks, that form the majority of the video - game community, and is prob. where Godot will grow from, etc . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it's bit sad, having heard of Vulkan for some time, and being rather hype, and then being disappointed, over something rather simple, that the ' final ' render, or what it makes, looks like a ' bad ' version, of OpenGL . . The point is, sorry . . . It's all for nothing, if the image isn't nice, or I guess the ' subjective ' look of the image, is worse than OpenGL . . Then it's almost a no - brainer, not to use it . . So, really big fan of Vulkan, sure, it has better specs, FPS, looks to be amazing, and even standard, for future . . I sort-of hope these small things can be fixed, before Godot 4, so we get the really nice Godot 4, we all have been wishing for, for so long, so it doesn't disappoint . . My guess is these things can be fixed, with a few settings, or tweaking the default stuff, maybe at code level, weird idea, set saturation to 0.95 %, contrast to 0.90 %, those numbers might be really bad, but to off - set the default ' post - proc. ' look, if I want that, just add it later, takes 2 seconds, having it set to on, by default, makes the engine too ' Hollywood ' or, big money by default, that's where I just want an honest, clean engine, thanks . . . .

**Comment by charlesmlamb** [comment]
Just to be clear, why I'm saying this . .

1. To get nicest possible Godot 4, on release day . .

2. Bec. I think it's just some settings, it might take 5 minutes to fix this, and, well, that's the why, thanks . . !

**Comment by Calinou** [comment]
This is due to broken mipmap generation on non-power-of-two VRAM-compressed textures, and is a known bug: https://github.com/godotengine/godot/issues/49981

**Comment by charlesmlamb** [comment]
Wow, thank you, just want Godot 4 edition, that looks as nice as well Godot 3, big thanks, it's gonna be a difficult wait . . .

**Comment by charlesmlamb** [comment]
Well, are you sure, bec. it happens on this texture, it is 2048x2048, so why does it happen . . .

![image](https://user-images.githubusercontent.com/83387915/145147176-a9ea7c0a-df03-4abc-9835-0b3c203230d9.png)

Anyway, I think it has to do with anisotropy, it looks like moire pattern stuff . .

![image](https://user-images.githubusercontent.com/83387915/145147256-9ac37c54-be6e-4459-8eee-c5c63eb7a529.png)

The problem is, I can't set mipmaps to on, in .glb importer, I think that's scene importer, and don't know where to set it, since textures are embedded in materials, anyway if it's power of two stuff, why does it also happen for a 2048x2048 texture . .
