### ISSUE TITLE
Contact hardening soft shadows / Percentage-Closer Soft Shadows

### ISSUE THREAD

**Issue by Leakbang** [godotengine/godot-proposals#3643]
### Describe the project you are working on

A 3D physics based, FPS

### Describe the problem or limitation you are having in your project

Poor implementation of shadows both in Vulkan

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add Contact hardening soft shadows. It means that shadows get blurrier, the further they are from a light source. Below is an example of it:
![image](https://user-images.githubusercontent.com/51197897/145110515-ada137e8-6f8b-4dcf-9cb1-4033b0b50a50.png)
[Source (Nvidia Docs)](https://docs.nvidia.com/gameworks/content/gameworkslibrary/graphicssamples/d3d_samples/d3dsoftshadowssample.htm)
Another neat implementation of it in Babylon.js:
![image](https://user-images.githubusercontent.com/51197897/145110801-d41512e6-7e96-4fbb-b07a-75406e3a883f.png)
[Source (Babylon.js Docs)](https://doc.babylonjs.com/divingDeeper/lights/shadows)

This would be an amazing addition to the Vulkan renderer in Godot 4. It makes the scenes especially interior ones look much more realistic, also it adds a special beauty to daylight nature scenes. With the tree trunk having sharper shadows and the leaves and branches being more blurred out. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Each light source will receive a boolean option to toggle Contact hardening soft shadows on or off. By default it would be disabled as it will cost some processing power.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. This feature is not simple enough to be implemented with only a few lines of code.

### Is there a reason why this should be core and not an add-on in the asset library?

This significantly improves the current state of shadows in Vulkan. As of `v4.0.dev.calinou [c1ed695f3]`, the lighting and shadows don't work as intended, but from screenshots that I have seen, the Vulkan shadows could really get some upgrades. There is a lot of dithering and soft shadows are extremely grainy. Additionally, adding such feature via an add-on might be impossible and or severely impact performance.

**Comment by Calinou** [comment]
PCSS are already implemented in the `master` branch. You can enable it by increasing the light's **Size** property above `0.0` (this is separate from the **Range** property).

It could technically be backported to `3.x`, but it's not really worth the effort since it's high-end-oriented.

**Comment by Leakbang** [comment]
Wow it's actually amazing that PCSS is already implemented. But I have to say, this feature is kind of buried. I had no idea that size is supposed to represent PCSS. Probably the naming could be improved a bit to indicate the presence of this feature.

> This is a known issue, see godotengine/godot#53534. This dithering is present by design.

Thank you for mentioning that issue. I did notice that issue before opening this thread. However, by running some tests of my own I was quite disappointed by the shadow quality.
This is a small scene with a couple of CSG cubes and an omnilight casting a shadow with the minimum Blur. It is the default shadow atlas size (4096). 
![image](https://user-images.githubusercontent.com/51197897/145121323-ceec7f78-0d15-450a-9142-fbe3106fb13a.png)
Increasing the shadow atlas size to 16k reduces the dithering but still it is very visible.

It looks much better when blurred, however still some massive dithering is visible. Specifically where the pole touches the ground (shown below).
![image](https://user-images.githubusercontent.com/51197897/145122100-2a772432-499c-48c3-b09d-20a4f8901ee8.png)

Perhaps an idea would be to render the hard shadows with a method like stencil shadows, so they look crispy, and for soft shadows the current implementation is kept. In the `shadow mode` property a new Stencil shadows option could be added for rendering hard shadows.

**Comment by Calinou** [comment]
> This is a small scene with a couple of CSG cubes and an omnilight casting a shadow with the minimum Blur. It is the default shadow atlas size (4096).

The aliasing is expected when the blur is set to a low value. The dithering helps hide the aliasing – without dithering, it'd look even worse :slightly_smiling_face:

**Comment by Leakbang** [comment]
> There are no plans to implement stencil shadows, as they are very expensive as soon as your geometry gets remotely complex. 

That's very good to know! Thanks for the detailed response :)
