### ISSUE TITLE
Allow two modifier keys for mouse navigation in the 3D editor viewport

### ISSUE THREAD

**Issue by larssteenhoff** [godotengine/godot-proposals#3646]
### Describe the project you are working on

Porting a game from Unity to Godot and needing to use the same viewport navigation because muscle memory and easy of use.

### Describe the problem or limitation you are having in your project

Unity let's me pan the viewport with ALT+CMD+LEFT MOUSE
Godot is limited to only allow one Modifier key in the option panel

![FC5IxhTXEAsqd5B](https://user-images.githubusercontent.com/9589240/145212612-fb89ff58-dd31-41f1-af13-ff1e444766ca.jpeg)

When I enable 3 button mouse it already pans when I press ALT and move the mouse ( without holding left mouse ) I would like it to Rotate with left mouse pressed, and pan when ALT+CMD+Left mouse is pressed. And do nothig with just ALT pressed when moving the mouse.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow two modifier keys to be selected and used in the project setting menu

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Allowing two modifier keys to be selected in the options

![two](https://user-images.githubusercontent.com/9589240/145213364-4cf4b935-61fc-475c-8bc2-0b79f8f9f593.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used by everyone who likes the Unity style navigation and want to use Godot without having to relearn navigation

### Is there a reason why this should be core and not an add-on in the asset library?

As this solves a viewport navigation limitation this will benefit a lot of users and is not limited to a single project use case.

**Comment by prominentdetail** [comment]
Currently Godot is very limited in the way you can change the 3d navigation controls. I'd prefer if there was a way to customize every 3d navigation action. At the moment I have to build godot from source using a modified source code to implement my controls scheme.

**Comment by Calinou** [comment]
> Currently Godot is very limited in the way you can change the 3d navigation controls. I'd prefer if there was a way to customize every 3d navigation action. At the moment I have to build godot from source using a modified source code to implement my controls scheme.

On the other hand, the issue with full customization is that it's a lot more time-consuming to set up if you just want a few keys to match other 3D software. This is why a preset approach is currently used.

Out of curiosity, which 3D program are you trying to replicate in Godot?

**Comment by prominentdetail** [comment]
> This is why a preset approach is currently used.

You could still have presets to choose(for popular schemes), and when you choose them it would just auto-fill the customizeable settings.

> which 3D program's navigation scheme are you trying to replicate in Godot?

Crocotile 3d (spacebar+lmb for rotate, spacebar+rmb for pan, and spacebar+mmb for zoom(or scrollwheel) ). At the moment I have been altering godot's source code and have to build each version release in order to get the control scheme working.
