### ISSUE TITLE
Allow disabling Shortcut's visual pressing of buttons

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot-proposals#365]
**Describe the project you are working on:** Simple Space-centric RTS 

**Describe the problem or limitation you are having in your project:** Shortcut Events always visually press buttons and there is no manner to disable such.

**Describe how this feature / enhancement will help you overcome this problem or limitation:** Its mostly just a concept to allow developers more visual control over their game without having to wire it up themselves, its more convenient to wire up buttons from the editor.

**Describe implementation detail for your proposal (in code), if possible:** Could add a boolean on the shortcut for detecting if it will visually activate it, however because of the nature of `on_action_event(InputEvent)` the BaseButton itself can't absolutely determine if what triggered it was a shortcut or a button press. In which case you could allow detection of the shortcut's visually active boolean in`_unhandled_input` but I'm not certain if that's fine with the style of Godot, I suppose there's nothing against a separate method in that case? I'm not sure how much trouble this would cause throughout the engine tho. That aside all that would have to be done in any case is handle calling `_toggle` and/or `_pressed` for the shortcut which seems trivial. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** Yes, its massively trivial as far as issues go, its just a matter of convenience in editor so I need not manage it, I'd just rather clean up my code and make it easier to see from the editor.

**Is there a reason why this should be core and not an add-on in the asset library?:** It would require re-implementing everything extending from BaseButton, reconstructing all the Buttons as new assets isn't practical for such a minor issue.

**Comment by Calinou** [comment]
Is there a reason to display this visual feedback by default? We should probably disable it when the button is triggered by a shortcut. If visual feedback is needed (which is probably the exception more than the rule), it should be added manually by the developer.

**Comment by Spartan322** [comment]
For my case I don't really have an opinion on shortcuts being incapable displaying activation status directly, if you prefer to just remove it, that's fine, I just would like a manner to have it not visually react to a shortcut.

**Comment by Spartan322** [comment]
This has to do with how
https://github.com/godotengine/godot/blob/b3bd08207032ca146319f4b25654bcddd31ee401/scene/gui/base_button.cpp#L261
and the call at https://github.com/godotengine/godot/blob/b3bd08207032ca146319f4b25654bcddd31ee401/scene/gui/base_button.cpp#L357
which doesn't make any distinction to `on_action_event` whether its called on a shortcut or by a press, I can submit a PR to address this, is there any specific manner this should be solved by?

**Comment by Calinou** [comment]
> which doesn't make any distinction to on_action_event whether its called on a shortcut or by a press, I can submit a PR to address this, is there any specific manner this should be solved by?

I think you can open a PR that disables visual feedback for shortcut-initiated presses entirely, and we can discuss from there.
