### ISSUE TITLE
Shader Graph improvements: noise textures, rotation matrixes and more to match current standard 3d tools.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot-proposals#3650]
### Describe the project you are working on

A 3D survival game.

### Describe the problem or limitation you are having in your project

Making materials is a bit limited because of the limited noise options (only one). Notably Voronoi texture creation is missing. Also because shader graph misses some quality of live improvements such as rotation matrixes nodes in the shader graph. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add more options to create noise textures (other than simplex noise). Also the creation of rotation matrixes as a single node and other common shading tools in the shader graph.  Also there could be a in-graph visualization of the material without having to make an instance in a new scene.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The new noise options should appear next to simplex noise. The nodes in the shader graph editor could appear as options to the transform nodes.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think these features are almost standard in most 3d creation tools. 

### Is there a reason why this should be core and not an add-on in the asset library?

I think these features are standard and useful for all projects in general.

**Comment by Calinou** [comment]
There's a pull request that implements more types of noise: https://github.com/godotengine/godot/pull/35144

However, it didn't reach much of a consensus and no proposal was specifically opened to support that PR.

**Comment by tetrapod00** [comment]
I believe this proposal can be closed, as these have been mostly implemented.
There are more noise types, including voronoi (called cellular). Rotation matrixes can be created from within visual shader. And the material/shader preview as just added in 4.4.

**Comment by Calinou** [comment]
Closing per @tetrapod00's comment.
