### ISSUE TITLE
Change the hotzone area size for ports in `GraphNode`

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot-proposals#3652]
### Describe the project you are working on

General VisualScript improvements

### Describe the problem or limitation you are having in your project

As first mentioned in https://github.com/godotengine/godot-proposals/issues/3009, dragging the port connector is finicky, especially when zoomed out.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Change the default `port_grab_distance_vertical` from 6 to 26

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot/blob/b46ab89675aef026650085c751a00cc47f8aa57e/scene/resources/default_theme/default_theme.cpp#L996-L997

theme->set_constant("port_grab_distance_vertical", "GraphEdit", 26 * scale);

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Default theme

### Is there a reason why this should be core and not an add-on in the asset library?

Default theme

Came across this while reviewing https://github.com/godotengine/godot/pull/52015
CC: @fire @mechPenSketch

The inputs are current measurements, the outputs are new measurement.
![image](https://user-images.githubusercontent.com/20573784/145629791-20370886-baab-4813-b89b-5b2a57169b9f.png)

**Comment by Gallilus** [comment]
https://github.com/godotengine/godot/blob/b46ab89675aef026650085c751a00cc47f8aa57e/scene/resources/default_theme/default_theme.cpp#L996-L997

Came across this while reviewing https://github.com/godotengine/godot/pull/52015

**Comment by fire** [comment]
I think the 6 lost the scale so this improves usability. We are trying to intuit how easy it is to grab a port.

**Comment by Gallilus** [comment]
What do you mean by 'intuit'?

**Comment by pycbouh** [comment]
If all you want is to 

> Change the default `port_grab_distance_vertical` from 6 to 26

then it's okay to just open a PR for that.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/56323.
