### ISSUE TITLE
Euler rotation representation should ideally be a real class, not piggybacking on Vector3

### ISSUE THREAD

**Issue by balintmaci** [godotengine/godot-proposals#3656]
### Describe the project you are working on

VR game with a lot of XDoF interactions. I have virtual joysticks to move with the VR hands, and rotating them in a joystick like fashion requires a specific sequence of rotations if I want to lock only certain axes.

### Describe the problem or limitation you are having in your project

I have to implement a lot of math myself and it's still ugly and confusing because of relying on Vector3.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`Euler` should be it's own class, instead of using `Vector3` to represent it. Euler angles do not form a vector, as opposed to axis-angle vectors, where it makes perfect sense to use Vector3.
Euler angles have different rotation orders, which could all be supported. Right now, the scripting interface only exposes Euler conversion functions in the default Godot Euler order, "yxz". There's also Euler orders where the first and last axes are the same, such as "zxz".
To avoid confusion and be more flexible, there should be a class named 'Euler' or something similar, which should avoid XYZ field names and instead focus on the order of rotation, and which should include its rotation sequence.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It should have the following fields (field names are open for debate):
# left-middle-right are rotations in radians around their respective local axis, as defined in the order property
var left: float
var middle: float
var right: float
var order: String

# defaults:
Euler(left = 0.0 middle = 0.0, right = 0.0, order = "yxz")

# convenience function:
set_order("zxz") # setting property allows switching between orders (bit inefficient because of having to compute the basis and then the new angles)

# other formats:
var basis = euler.to_rotation_matrix()
var euler = Euler(basis, order = "yxz")

The editor could also allow defining the rotation in any Euler order, but this doesn't seem that important.

Here's the code I wrote for generic conversion (only supports Tait-Bryan angles, not proper Euler angles, because the Vector3 rep. has XYZ  in it and I couldn't figure out how to make it not confusing)
```
# based on https://en.wikipedia.org/wiki/Euler_angles#Rotation_matrix
static func basis2euler(b: Basis, order = DEFAULT_EULER_ORDER) -> Vector3:
    var euler = Vector3()
    if order == "xzy":
        # rot =  cz*cy             -sy             cz*sy
        #        sx*sy+cx*cy*sz    cx*cz           cx*sz*sy-cy*sx
        #        cy*sx*sz          cz*sx           cx*cy+sx*sz*sy
        euler.x = atan2(b.y.z, b.y.y)
        euler.y = atan2(b.z.x, b.x.x)
        var sz = -b.y.x
        var cz = b.y.y / cos(euler.x)
        euler.z = atan2(sz, cz)
    elif order == "xyz":
        # rot =  cy*cz          -cy*sz           sy
        #        cz*sx*sy+cx*sz  cx*cz-sx*sy*sz -cy*sx
        #       -cx*cz*sy+sx*sz  cz*sx+cx*sy*sz  cx*cy
        euler.x = atan2(-b.z.y, b.z.z)
        euler.z = atan2(-b.y.x, b.x.x)
        var sy = b.z.x
        var cy = b.x.x / cos(euler.z)
        euler.y = atan2(sy, cy)
    elif order == "yxz":
        # rot =  cy*cz+sy*sx*sz    cz*sy*sx-cy*sz        cx*sy
        #        cx*sz             cx*cz                 -sx
        #        cy*sx*sz-cz*sy    cy*cz*sx+sy*sz        cy*cx
        euler.y = atan2(b.z.x, b.z.z)
        euler.z = atan2(b.x.y, b.y.y)
        var sx = -b.z.y
        var cx = b.y.y / cos(euler.z)
        euler.x = atan2(sx, cx)
    elif order == "yzx":
        # rot =  cy*cz             sy*sx-cy*cx*sz     cx*sy+cy*sz*sx
        #        sz                cz*cx              -cz*sx
        #        -cz*sy            cy*sx+cx*sy*sz     cy*cx-sy*sz*sx
        euler.x = atan2(-b.z.y, b.y.y)
        euler.y = atan2(-b.x.z, b.x.x)
        var sz = b.x.y
        var cz = b.y.y / cos(euler.x)
        euler.z = atan2(sz, cz)
    elif order == "zxy":
        # rot =  cz*cy-sz*sx*sy    -cx*sz                cz*sy+cy*sz*sx
        #        cy*sz+cz*sx*sy    cz*cx                 sz*sy-cz*cy*sx
        #        -cx*sy            sx                    cx*cy
        euler.y = atan2(-b.x.z, b.z.z)
        euler.z = atan2(-b.y.x, b.y.y)
        var sx = b.y.z
        var cx = b.y.y / cos(euler.z)
        euler.x = atan2(sx, cx)
    elif order == "zyx":
        # rot =  cz*cy             cz*sy*sx-cx*sz        sz*sx+cz*cx*cy
        #        cy*sz             cz*cx+sz*sy*sx        cx*sz*sy-cz*sx
        #        -sy               cy*sx                 cy*cx
        euler.x = atan2(b.y.z, b.z.z)
        euler.z = atan2(b.x.y, b.x.x)
        var sy = -b.x.z
        var cy = b.x.x / cos(euler.z)
        euler.y = atan2(sy, cy)
    else:
        push_error("Euler order must contain exactly one of X, Y, and Z axes in lowercase, e.g. 'xyz'. Proper Euler orders, such as 'zxz' are not supported.")
    return euler


static func euler2quat(angles: Vector3, order = DEFAULT_EULER_ORDER) -> Quat:
        return Quat(euler2basis(angles, order))


# xyz values in `angles` vector denote rotation around the respective local axis
static func euler2basis(angles: Vector3, order = DEFAULT_EULER_ORDER) -> Basis:
    if not (order.length() == 3 and "x" in order and "y" in order and "z" in order):
        push_error("Euler order must contain exactly one of X, Y, and Z axes in lowercase, e.g. 'xyz'. Proper Euler orders, such as 'zxz' are not supported.")
        return Basis()
    var rots = {
        "x": Basis(Vector3.RIGHT, angles.x),
        "y": Basis(Vector3.UP, angles.y),
        "z": Basis(Vector3.BACK, angles.z),
    }
    return rots[order[0]] * rots[order[1]] * rots[order[2]]
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's a mathy subject, which is easy to mess up. The calculations can be implemented in GDScript as well though. Proof to this is that there's bugs in my implementation as well.

### Is there a reason why this should be core and not an add-on in the asset library?

Relates to built-in math classes

**Comment by Calinou** [comment]
In the `master` branch, Node3D allows you to customize the Euler rotation order on a per-node basis.

**Comment by balintmaci** [comment]
@Calinou 
I can see the order parameter is exposed on get_euler and from_euler on the  `master`, that's already a big improvement. Any chance this will be backported to 3.x?

**Comment by Calinou** [comment]
> Any chance this will be backported to 3.x?

Feel free to open a pull request for this (as long as it's done in a backwards-compatible way) :slightly_smiling_face:

**Comment by Zireael07** [comment]
@balintmaci: You shouldn't close the proposal before the PR is opened...

**Comment by balintmaci** [comment]
@Zireael07 Sorry, should've left a closing comment. Closed because as per the discussion above there is a solution to make working with Euler angles easier on the master (although maybe not the ideal solution, but without introducing another a new core type), and it can be worked around on stable, so it's not that pressing.
