### ISSUE TITLE
Add option to sort Assets in AssetLib by GitHub Stars

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot-proposals#3658]
### Describe the project you are working on

Any project that uses assets from the asset lib

### Describe the problem or limitation you are having in your project

There's no easy way to check the popularity of an asset straight from the editor. It would save time when comparing similar assets or when checking what kind of asset is very popular.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since most assets from the official repository are also mirrored in GitHub, it could be possible to query the current number of stars as the asset entry is loaded, and sort by this number.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Will be an additional option in the Sort dropdown in the AssetLib workspace.

There is a View Files link in the asset library website that usually links to the GitHub repository, but it doesn't show up in the editor; I'm not sure if the official repository's API exposes this link.

Many assets also add the link to the repository in the description of the asset; the sorter could look for a GitHub link in the description as a fallback.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not easily.

### Is there a reason why this should be core and not an add-on in the asset library?

It could be an add-on, but it would be most useful if it was built-in (as it wouldn't have to be discovered in the first place)

**Comment by Calinou** [comment]
Not all assets use GitHub, so this would be unfair for assets that do not use GitHub (since people don't use GitLab stars nearly as often).


The [new asset library](https://github.com/Calinou/godot-asset-library-laravel) features GitHub/GitLab login and a review system, which is a better way to tackle this problem.
