### ISSUE TITLE
Expose BitMap's `convert_to_image` and `resize` methods to GDScript

### ISSUE THREAD

**Issue by OverloadedOrama** [godotengine/godot-proposals#3660]
### Describe the project you are working on

[Pixelorama](https://github.com/Orama-Interactive/Pixelorama), a pixel art editor.

### Describe the problem or limitation you are having in your project

Pixelorama uses a BitMap in order to store the state of the image's pixels; whether they are selected or not. It is the same size as the image, so when the image gets resized, so should the bitmap, hence the need for the `resize` method. We are also converting the bitmap to an image, in order to be processed by a shader to achieve the marching ants effect.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Right now we re-implemented the same methods in GDScript, which does the job but it also is very slow when we are dealing with large images. Having these methods exposed will improve performance, since the conversion to image and resizing code will run in native C++, and it will also let us clear out unneeded code. Plus, it will make the BitMap class a bit more powerful and useful.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Not much to say here, the entire proposal is for exposing methods to GDScript that already exist.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It definitely can, but like I mentioned above, it is slower when dealing with large images.

### Is there a reason why this should be core and not an add-on in the asset library?

It is already in core, just not exposed to GDScript.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/55841.
