### ISSUE TITLE
Add a `Node.get_children_of_type()` method to get child nodes inheriting from a specific type

### ISSUE THREAD

**Issue by diddykonga** [godotengine/godot-proposals#3661]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

I was thinking about how Interfaces are one of the lacking/missing OOP design patterns in Godot, but understood such a thing could be done via Composition over Inheritance with Child Nodes being the Interfaces that a Parent Node implements, and of course to use Interfaces one needs to know if something implements it, which led me to realize there is no helper function like `get_node()` for child nodes of specific types.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

```gdscript
var interfaces = get_children_of_type("Interface")
if interfaces.size() > 0:
    var interface = interfaces[0] as Interface
    interface.interface_func()
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This but in C++:
```gdscript
var interfaces = []
for i in get_children():
    if i is Interface:
        interfaces.append(i)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, its simply a helper function such as `get_node()`.

### Is there a reason why this should be core and not an add-on in the asset library?

Less static functions in globals, and could see high use, but that's what this proposal is for.

**Comment by Calinou** [comment]
> `get_nodes_of_type(Interface)`

How would the node path be specified?

**Comment by pycbouh** [comment]
> > `get_nodes_of_type(Interface)`
> 
> How would the node path be specified? `get_node()` requires a node path.

I think it's meant as `get_children_of_type()`.

**Comment by diddykonga** [comment]
> > > `get_nodes_of_type(Interface)`
> > 
> > 
> > How would the node path be specified? `get_node()` requires a node path.
> 
> I think it's meant as `get_children_of_type()`.

Yeah, `get_node()` searches children of the node in question, this would do the same.

Although now that I think about this I guess it would have to take a StringName wouldn't it, since as far as I'm aware there is no Type to represent ClassTypes in Godot.

**Comment by Xrayez** [comment]
> I was thinking about how Interfaces are one of the lacking/missing OOP design patterns in Godot

Since you mentioned this being the original problem, I think some of this could be solved with traits, see proposal: godotengine/godot#23101.

**Comment by diddykonga** [comment]
> > I was thinking about how Interfaces are one of the lacking/missing OOP design patterns in Godot
> 
> Since you mentioned this being the original problem, I think some of this could be solved with traits, see proposal: [godotengine/godot#23101](https://github.com/godotengine/godot/issues/23101), as an alternative solution to the problem.

This is interesting, but the thing is if we were to make a change to the language I believe the most beneficial one would instead to implement C++ 20's Concepts, which are simply Compile Time checks that a Type passed into a Method that expects a Concept matches the required syntax, which would work much better with a duck-typed dynamic language like GDScript, also they wouldn't even need to be able to change what a GDScript creates, they would simply be added in as "inner types" of an already existing GDScript, preferably above the Method that requires them.

```
concept BodyConcept:
    self is PhysicsBody # Requires self to at least be of PhysicsBody
    self.set_jump_speed(speed) # Requires self to implement a custom method, that takes one argument of any Type.
    self.jump_speed : float # Requires self to implement a custom property, of Type float.

func jump(body : BodyConcept)
    body.set_jump_speed(10)
    body.move_and_collide(body.jump_speed)
    ...
```

Kind of a poop example but you probably get the point.

**Comment by me2beats** [comment]
I find this especially useful when working with plugins to find a control in the editor.

**Comment by balintmaci** [comment]
I also like this feature a lot, but it would need to work with any superclass of the object too, same as the `is` keyword.
A good example is how in Angular you can use the `@ViewChild` or `@ViewChildren` for types.
```
@ViewChild(ChildDirective) child!: ChildDirective;
@ViewChildren(ChildDirective) viewChildren!: QueryList<ChildDirective>;
```
For example a physics body node needs a collision shape node as child, but how does the physics body find that child? Only way to do it right now is to loop through all children and check with `is`

Same in Godot:
```
var child = get_child_of_type(CollisionShape) # first child that extends CollisionShape
var children = get_children_of_type(CollisionShape) # all children that extend CollisionShape
```

**Comment by balintmaci** [comment]
I wrote a GDScript workaround with unit tests if anyone needs it in the mean time
```
extends Object
class_name NodeUtilities


# Note: passing a value for the type parameter causes a crash
static func get_child_of_type(node: Node, child_type):
    for i in range(node.get_child_count()):
        var child = node.get_child(i)
        if child is child_type:
            return child


# Note: passing a value for the type parameter causes a crash
static func get_children_of_type(node: Node, child_type):
    var list = []
    for i in range(node.get_child_count()):
        var child = node.get_child(i)
        if child is child_type:
            list.append(child)
    return list
```

tests:
```
extends "res://addons/gut/test.gd"


func test_get_child():
    var parent = KinematicBody.new()
    var first_shape = CollisionShape.new()
    parent.add_child(first_shape)
    parent.add_child(CollisionShape.new())
    parent.add_child(CollisionShape.new())
    parent.add_child(MeshInstance.new())
    assert_eq(NodeUtilities.get_child_of_type(parent, CollisionShape), first_shape)
    assert_eq(NodeUtilities.get_children_of_type(parent, MeshInstance).size(), 1)
    assert_eq(NodeUtilities.get_children_of_type(parent, CollisionShape).size(), 3)
    parent.free()
```

**Comment by felbecker** [comment]
Does `get_child_of_type` still work in 4.0? As it seems, `child_type` is no longer be accepted as a type when using `is`. It can not be a string either, because `get_class()` does ignore `class_name`. 

Is this sort of C++-style template method still possible in 4.0?

**Comment by kleonc** [comment]
> Does `get_child_of_type` still work in 4.0? As it seems, `child_type` is no longer be accepted as a type when using `is`. It can not be a string either, because `get_class()` does ignore `class_name`.
> 
> Is this sort of C++-style template method still possible in 4.0?

You can use [`is_instance_of`](https://docs.godotengine.org/en/4.0/classes/class_%40gdscript.html#class-gdscript-method-is-instance-of): `child is child_type` -> `is_instance_of(child, child_type)`.
See https://github.com/godotengine/godot/pull/73489.

**Comment by eterlan** [comment]
> > Does `get_child_of_type` still work in 4.0? As it seems, `child_type` is no longer be accepted as a type when using `is`. It can not be a string either, because `get_class()` does ignore `class_name`.
> > Is this sort of C++-style template method still possible in 4.0?
> 
> You can use [`is_instance_of`](https://docs.godotengine.org/en/4.0/classes/class_%40gdscript.html#class-gdscript-method-is-instance-of): `child is child_type` -> `is_instance_of(child, child_type)`. See [godotengine/godot#73489](https://github.com/godotengine/godot/pull/73489).

but it doesn't support inheritance check like "is" do, right?

**Comment by Wiechciu** [comment]
I am also trying to refactor my game into a composition-style. Nodes can have multiple "components", so I needed a way to check if a node is of specific type. The proposed built-in solution would be the best, but for now this works too:
```
# Parent_Node
func get_component(component_type) -> Node:
	for child in get_children():
		if is_instance_of(child, component_type):
			return child
	return null
```

**Comment by wjagodfrey** [comment]
Adding a version of @balintbarna's script with optional depth-first traversal. Will help you find nested nodes. Don't use on hot paths!

```gdscript
extends Object
class_name NodeUtils


static func get_child_of_type(node: Node, child_type, recursive := false):
	for i in range(node.get_child_count()):
		var child = node.get_child(i)
		if is_instance_of(child, child_type):
			return child
		if recursive:
			var child_node = get_child_of_type(child, child_type, recursive)
			if child_node:
				return child_node


static func get_children_of_type(node: Node, child_type, recursive := false):
	var list = []
	for i in range(node.get_child_count()):
		var child = node.get_child(i)
		if is_instance_of(child, child_type):
			list.append(child)
		if recursive:
			list += get_children_of_type(child, child_type, recursive)
	return list
```

Tests:
```gdscript
extends "res://addons/gut/test.gd"

const MESH1_NAME = "mesh1"
const MESH2_NAME = "mesh2"

var root


func before_each():
	root = CharacterBody3D.new()

	var skeleton = Skeleton3D.new()
	root.add_child(skeleton)
	var mesh1 = MeshInstance3D.new()
	mesh1.name = MESH1_NAME
	skeleton.add_child(mesh1)

	var node = Node3D.new()
	root.add_child(node)
	var mesh2 = MeshInstance3D.new()
	mesh2.name = MESH2_NAME
	node.add_child(mesh2)

	autofree(root)


func test_get_child():
	assert_null(NodeUtils.get_child_of_type(root, AnimationPlayer))
	assert_not_null(NodeUtils.get_child_of_type(root, Skeleton3D))
	assert_null(NodeUtils.get_child_of_type(root, MeshInstance3D))


func test_get_child_recursive():
	assert_null(NodeUtils.get_child_of_type(root, AnimationPlayer), true)
	assert_not_null(NodeUtils.get_child_of_type(root, Skeleton3D, true))
	var mesh = NodeUtils.get_child_of_type(root, MeshInstance3D, true)
	assert_not_null(mesh)
	assert_eq(mesh.name, MESH1_NAME)


func test_get_children():
	assert_eq(NodeUtils.get_children_of_type(root, AnimationPlayer).size(), 0)
	assert_eq(NodeUtils.get_children_of_type(root, Skeleton3D).size(), 1)
	assert_eq(NodeUtils.get_children_of_type(root, MeshInstance3D).size(), 0)


func test_get_children_recursive():
	assert_eq(NodeUtils.get_children_of_type(root, AnimationPlayer, true).size(), 0)
	assert_eq(NodeUtils.get_children_of_type(root, Skeleton3D, true).size(), 1)
	var meshes = NodeUtils.get_children_of_type(root, MeshInstance3D, true)
	assert_eq(meshes.size(), 2)
	assert_eq(meshes[0].name, MESH1_NAME)
	assert_eq(meshes[1].name, MESH2_NAME)
```

**Comment by saminton** [comment]
Can we reopen this issue ? The merge that "resolved" this issue solves only half of the problem. I need to retrieve a single child node of a type a lot more often that all child nodes of a type.

It's rather confusing as to why the current implementation allows a `type` parameter with `find_children` but not with `find_child`

```
find_child ( String pattern, bool recursive=true, bool owned=true ) const
find_children ( String pattern, String type="", bool recursive=true, bool owned=true ) const
```

When working with composition, which as far as I can tell is the preferred workflow for Godot, getting nodes via their type rather than their name seems like a more robust system

**Comment by Calinou** [comment]
> Can we reopen this issue ? The merge that "resolved" this issue solves only half of the problem. I need to retrieve a single child node of a type a lot more often that all child nodes of a type.

Please open a new proposal on the subject.

**Comment by actforjason** [comment]
> When working with composition, which as far as I can tell is the preferred workflow for Godot, getting nodes via their type rather than their name seems like a more robust system

The `type` here refers to "the base, built-in class name" (GetClass()) rather than the defined `class_name`(GetType()). Different script nodes belong to the same class node, so it may not be very meaningful for componentization.

find_children(pattern: String, type: String = "", recursive: bool = true, owned: bool = true) const
[docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-find-children](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-find-children)
