### ISSUE TITLE
Add option to always hide scene tabs close button

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#3669]
### Describe the project you are working on

Game in Godot

### Describe the problem or limitation you are having in your project

I find myself often clicking accidentally the close button on scene tabs. I never use this button normally, I close tabs with shortcut or middle click. The only times I click the X is when I missclick.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be useful to be able to hide the close button. Tabs node already has this option. It has an enum to Always Show, Show Active and Show Never. For scene tabs, only the former two are available. We could change the "Always Show Close Button" setting to use enum instead, so that all 3 options are available (and the Show Never can be used in scene tabs).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`interface/scene_tabs/always_show_close_button` -> change this thing to use enum from Tabs node instead.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I could maybe hack the editor to achieve this, but it's hacky.

### Is there a reason why this should be core and not an add-on in the asset library?

This option exists in e.g. VS Code. Also the functionality is already there, it just requires a change of one setting.

**Comment by Mickeon** [comment]
Nice minor proposal. I have to assume, some of the accidental clicks occur due of the script button being placed right next to the close button (when enabled, as well).
![image](https://user-images.githubusercontent.com/66727710/146102722-905e3041-045b-438d-a576-50ddd379aa48.png)
If that's true I see even more of a reason to implement this change. It's also already possible to close tabs by right-clicking and choosing the option, so it shouldn't make users feel lost. And surely, the proposal shouldn't be the default state of the setting.

**Comment by me2beats** [comment]
If I close a tab accidentally, in many other applications I just hit a shortcut that opens it back (open recently closed tab).
This would be a nice feature too imo.

**Comment by KoBeWi** [comment]
Except that feature already exists. But reopening scene may take a couple of seconds and the reopened tab always appears as last.

**Comment by me2beats** [comment]
> reopening scene may take a couple of seconds
agree
> and the reopened tab always appears as last.
It could be added in the position where it was closed
