### ISSUE TITLE
Backport Postion3D and Position2D editor drawing improvements to `3.x`

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#3670]
### Describe the project you are working on

A 3D game where the user needs to walk around a complex world.

### Describe the problem or limitation you are having in your project

Position3D nodes are a useful built in way to indicate points of interest in the world.  However, they provide no visual feedback in the editor as to their location in space, size or orientation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If there was a visual indicator for Position3D, it would be much easier to keep track of them and make sure they are turned the right way.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add code that runs in the editor (when Engine.EditorHint is true) that will draw a simple shape that gives some indication of the Transform of the Position3D in the scene.  The user would also be given a short list of shapes to choose from, such as Axis, Cube, Directional Arrow or Nothing.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You would need to create a new node to do this, but it would be better if Position3D and Position2D supported this without the need to extend them.

### Is there a reason why this should be core and not an add-on in the asset library?

This would require a change to a core asset type.

**Comment by Calinou** [comment]
This was already implemented in `master` by https://github.com/godotengine/godot/pull/49128, but it hasn't been backported to `3.x` yet.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/56044.
