### ISSUE TITLE
Add a `find_node_or_null` function that doesn't log an error if the node isn't found

### ISSUE THREAD

**Issue by derkork** [godotengine/godot-proposals#3671]
### Describe the project you are working on

It is not really specific to any project.

### Describe the problem or limitation you are having in your project

I have several components which may have an optional child node with a specific name, where the nesting path is not fixed. I use `find_node` to find these, but if they are not there, then this is not a problem. However `find_node` always prints out an error when the node is not found which pollutes the logs with noise and may hide real problems. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having a function `find_node_or_null` which works exactly like `find_node` but doesn't output an error when no node is found would help here.  I assume that `get_node_or_null` exists for the very same reason.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will work exactly like `find_node`, it just doesn't output an error message as a side effect. So you can replace `find_node` with `find_node_or_null` and it should be a drop-in-replacement.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really. Except if one manually implements find_node in GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

If `get_node_or_null` is core then `find_node_or_null` should also be core.

**Comment by boruok** [comment]
maybe get_node("somenode", default_value:Variant=null)?

**Comment by pycbouh** [comment]
> maybe get_node("somenode", default_value:Variant=null)?

get_node already has a counterpart that doesn't err and returns a null, get_node_or_null. They want a counterpart for find_node because they don't have a fixed position for a child, but they know its name.

-----

This is better solved by node groups, perhaps, since depending not just on a name, but on a name at an arbitrary position that can also not be there can prove very problematic for your project down the line.

**Comment by KoBeWi** [comment]
But `find_node()` doesn't log any error, it just returns null. You sure it's not something else?

> This is better solved by node groups

Groups are not really feasible if the code is used by multiple instances.

**Comment by pycbouh** [comment]
> Groups are not really feasible if the code is used by multiple instances.

True, but there is still a number of possible solutions that would be more stable than relying on a name of a node *somewhere* in the tree, that may not be there at all 🙃 Even going from the child node up the tree to tell the parent about itself is slightly better than that.

**Comment by Xrayez** [comment]
> However `find_node` always prints out an error when the node is not found which pollutes the logs with noise and may hide real problems.

If `find_node()` prints an error, that's a bug. Just like `Array.find()` or `String.find()`, they just return `-1`, equivalently `find_node()` returns `null`. If you don't handle the case when `find_node()` returns `null`, you'll likely get an error down the road within your script.

**Comment by Calinou** [comment]
In Godot 3.4 and later, the following may be enough to silence errors temporarily:

```gdscript
Engine.print_errors = false
find_node("something")
# Don't forget to enable error printing again!
Engine.print_errors = true
```

**Comment by derkork** [comment]
@Xrayez is correct, `find_node` actually does not print any errors if the node isn't found. I have been confused by output of other code which accidentally used `get_node` instead of `find_node`. So the original proposal is already in the engine, since `find_node` actually does what I need. 

There could still be a discussion whether `get_node` and `find_node` are two different ways of acquiring a node (one by path, the other by pattern) and that if this is the case `find_node` should probably behave the same way as `get_node` when it doesn't find a node. Under this premise, having a `find_node_or_null` would make sense. On the other hand, this is more of an academic discussion as I am with @Xrayez  on that `find_` implies that the node may not be there. Also changing the behaviour of `find_node` would break existing scripts, so I feel it is not worth it. 

So I would be inclined to close this.

**Comment by kleonc** [comment]
Before closing the docs for `find_node` should be clarified as [it's not written down what happens when no node is found](https://github.com/godotengine/godot/blob/e311389580226f0fc5adb6abe785d7af58e06892/doc/classes/Node.xml#L188-L193). A note similar to the one in [`get_node`'s description](https://github.com/godotengine/godot/blob/e311389580226f0fc5adb6abe785d7af58e06892/doc/classes/Node.xml#L263-L265):

>If the path does not exist, a null instance is returned and an error is logged. Attempts to access methods on the return value will result in an "Attempt to call <method> on a null instance." error.

should make things clear.
