### ISSUE TITLE
Will Godot use something like Unity component concept?

### ISSUE THREAD

**Issue by steelywing** [godotengine/godot-proposals#3672]
### Describe the project you are working on

3D physics game like Human Fall Flat

### Describe the problem or limitation you are having in your project

For now, `PhysicalBone` doesn't have movement or velocity function, if using component concept it can just add RigidBody as component, and then control the same node, and many type of node can be merge.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Component concept is more clearly, because some of the node will not has child (Ex: Music, Sound, Camera, ...), if they have child like Body / Shape will be weird.

And when component working with sibling component fell like better.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In `PhysicalBone`, can control the node like

```
var rigid = this.GetComponent<Rigid>();
if (rigid != null) {
  // do some rigid thing
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Now I need to use a joint to combine `PhysicalBone` and `RigidBody`, and then move the `RigidBody`, and very weird.

### Is there a reason why this should be core and not an add-on in the asset library?

It change the game engine struct.

**Comment by pycbouh** [comment]
Godot is build around a different paradigm. Problems are solved by composition and hierarchy in Godot, not by entities and components. In your example, bones normally don't move by themselves, they are driven by physics of the body, including constraints and joints, or are driven by animation, or both. Either way, the top-down approach of Godot is completely capable of solving moving bones in a sensible manner.

There are no plans to fundamentally change the engine at this point. We believe in the benefits of this system over other solutions, and prefer to solve shortcomings as they come. If you still want to use components with Godot, there is a third-party project that adds a ECS system to the engine (https://github.com/GodotECS/godex).

Please, in future use [community platforms](https://godotengine.org/community) to ask for questions. This is really not the place for that.

**Comment by Calinou** [comment]
> For now, PhysicalBone doesn't have movement or velocity function, if using component concept it can just add RigidBody as component, and then control the same node, and many type of node can be merge.

See also https://github.com/godotengine/godot-proposals/issues/1951.
