### ISSUE TITLE
UX for the Items of OptionButton could be improved

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#368]
**Describe the project you are working on:**
Irrelevant to the issue, but worth to mention it's a project done by a number of people.

**Describe the problem or limitation you are having in your project:**
This is the first time for me where I am using an option button, and the original scene containing the option button was not done by me. I had to modify the options of the option button. Took me solid 30 minutes to find where the options are added to the option button, because they were not present in the inspector so I assumed they were added via code.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
I think the UX of adding items to an OptionButton should be unified with the rest of Godot's, which is generally to have a property in the inspector panel on the right. In the case of the OptionButton, I would expect it to show an array that accept Items.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
What I would imagine is for the content of the popup that shows when you press on "items" to show instead in the inspector. This could be a minor change (not sure as I'm not super familiar with the editor code organization). What would be better is to treat the items of an option button as an array/list of dictionaries/resources.

Current look:
![optionbuttoncurrent](https://user-images.githubusercontent.com/7917475/72060835-0ade8700-32d5-11ea-81eb-b85a1ee36a66.png)
Items are defined by clicking on the Items button, close to the "anchors" button on the top part of the central view. Clicking that buttons opens this popup:
![optionbuttonitem](https://user-images.githubusercontent.com/7917475/72060891-26e22880-32d5-11ea-8a0c-9d3dacdef44b.png)

What I would expect is something similar to this:
![items](https://user-images.githubusercontent.com/7917475/72060925-32355400-32d5-11ea-82c7-396374f379f9.png)

It would be even better (from a consistency perspective) if it was a regular Array of Dictionaries or Array of Items.

**Describe implementation detail for your proposal (in code), if possible:**
Not sure, I'm not familiar with that part of the editor code.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I'm not sure this could be implemented with an add-on.

**Comment by lentsius-bark** [comment]
I like this idea.

**Comment by KoBeWi** [comment]
> I think the UX of adding items to an OptionButton should be unified with the rest of Godot's, which is generally to have a property in the inspector panel on the right.

There are lots of nodes that add buttons to the top toolbar. Sprite, Particles2D, Polygon... to name a few. The actual problem might be that the toolbar isn't really visible/obvious to use for beginners, see #14

**Comment by arkology** [comment]
+1. I hate this button (and non-resizable editor). It's not intuitive at all. Item list editor should be in inspector dock.

**Comment by hinlopen** [comment]
Adding it to the inspector seems too cluttered. We can also open the list upon selecting a node (ItemList/OptionButton/etc.):
![il_plugin](https://user-images.githubusercontent.com/25907608/85951813-f31fbb80-b965-11ea-99a9-53c4301bfb6b.png)
Other nodes with toolbar options usually have less essential functionality hidden there. Editing the items is very often a use case, so it can be justified to automatically open the list and take up a portion of the screen.

Let me know if this looks good, then I will open a PR.

**Comment by groud** [comment]
Thanks to https://github.com/godotengine/godot/pull/52277, it will be easy to move the ItemList items to the inspector. We should likely go that route.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/54342, closing.

**Comment by groud** [comment]
> This was implemented by godotengine/godot#54342, closing.

No, this PR was for ItemList items, not for OptionButton ones.

**Comment by groud** [comment]
Ah but it was implemented in https://github.com/godotengine/godot/pull/54533 in fact, so closing again!
Sorry for the spam.

**Comment by KoBeWi** [comment]
For some reason I don't see Items property in the OptionButton inspector, nor on the toolbar.

**Comment by KoBeWi** [comment]
Yep, `ADD_ARRAY_COUNT` wasn't implemented for OptionButton (MenuButton is a different node). Right now you can't edit the items at all.
