### ISSUE TITLE
An ability to set a temporary "pivot" for rotating selected nodes around it in editor.

### ISSUE THREAD

**Issue by SysError99** [godotengine/godot-proposals#3684]
### Describe the project you are working on

My game is 2D game, with some of animations made my `Skeleton2D` nodes.

### Describe the problem or limitation you are having in your project

When I work with animations and I want to make an animation that needs whole-object rotation (such as stumbling with rocks that the character will fall to front of itself), It's very difficult to make it smoothly. I need to constantly move nodes position and rotate until I find an optimal spot for the animation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a button alongside with many of movement/rotation buttons that activates "pivot rotation mode". After an activation, user will define a pivot rotation point by click-and-drag on desired spot, after pivot point appears, user can rotate an object by click-and-drag around the pivot point (click-and-drag on pivot point will simply move the pivot point to a new spot (in 3D, a small 3D axis will appear and user can drag it to change pivot position).

Now user can freely move whole objects without relying on creating a parent node that will be used to rotate whole nodes on specified point, and can be very useful on animation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1) User click on "pivot rotate" button to activate the rotation tool.
2) User click on empty space to create a pivot point.
3) User can now rotate nodes, referencing the pivot.
4) User can change pivot point position by dragging it to another point.
4) When finish, user can click on "finish" button or pressing ESC to go back on previous transform tool.

![image](https://user-images.githubusercontent.com/17522480/146568931-118da06a-f00a-4d2d-b270-6dd2b86fb2af.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't really think about true solutions beside of creating a new node that will be used for rotation, and it does not work so well on partial selection. It also does not work with armature tool.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a feature that many of image/model manipulation tool given out of the box, and can be very useful for many cases that require rotation of specific objects around the defined pivot, especially animation.

**Comment by KoBeWi** [comment]
Related: https://github.com/godotengine/godot/issues/19691
