### ISSUE TITLE
The ability to Limit(constraints) IK 

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#3712]
### Describe the project you are working on

I am working on creating Advanced Movement System Godot 3D template 

and I am using SkeletonModificationStack for IK system

### Describe the problem or limitation you are having in your project

SkeletonModification3DLookAt doesn't have an option to limit the rotation of the bone 

for example : Iam using it for head rotation so the head can follow(Look at) a target ,
but if the target is for example behind the player this will make the head rotate 180 degrees 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

the feature to add a limit to bone rotation (constraint it) so it doesn't rotate it awkwardly

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

add an option 

Bone limits (x,y,z)
and Enable/Disable option for this feature 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe it will be used a lot but
there is workaround though it isn't good :
like reducing the strength (but I want the head to look at the target not just tilt his head a little,

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think this small feature should be in a plugin while it could be directly in godot

**Comment by fire** [comment]
I’ve working on this, please contact me on discord fir details. Still draft stage.

**Comment by ywmaa** [comment]
@fire do you need someone to test it ?

**Comment by fire** [comment]
If you're able to help out test or able to provide sample case, that is welcome. It's also been difficult because of the different parts.

**Comment by ywmaa** [comment]
here I am working on advanced movement system template

https://github.com/ywmaa/Advanced-Movement-System-Godot

it is the main reason why I requested this feature

I think I can test the feature as it is part of my project

**Comment by fire** [comment]
I found an old IK Constraints proposal with some information https://github.com/godotengine/godot-proposals/issues/3712 supersedes this..

**Comment by Calinou** [comment]
> I found an old IK Constraints proposal with some information #3712.

You linked to the same proposal :slightly_smiling_face:

**Comment by ywmaa** [comment]
if someone is working on this , here is my contribution to it : 

https://github.com/godotengine/godot-proposals/issues/750#issuecomment-1009796131

and I am closing this issue because it is almost a duplicate of the issue above

and it has better explanation with better/more suggestions
