### ISSUE TITLE
Changing the term "master" to "main" or something like that

### ISSUE THREAD

**Issue by DennisHeine** [godotengine/godot-proposals#3713]
### Describe the project you are working on

It feels bad.

### Describe the problem or limitation you are having in your project

Ethics

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Change the term "master" in master/ppupet and the object authroity to "main", and puppet to "secondary" or "client" or something like that

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

...

### If this enhancement will not be used often, can it be worked around with a few lines of script?

sed

### Is there a reason why this should be core and not an add-on in the asset library?

it's an essential part of godot networking

**Comment by pycbouh** [comment]
There is no master mode anymore in Godot 4, and puppet was renamed to auth. https://github.com/godotengine/godot/pull/51481

There won’t be any changes in 3.x, as we can’t break compatibility.
