### ISSUE TITLE
Rotation for tiles on GridMap

### ISSUE THREAD

**Issue by LyimeS** [godotengine/godot-proposals#3716]
### Describe the project you are working on

just experimenting on how to import assets

### Describe the problem or limitation you are having in your project

When creating a MeshLibrary, I had to rotate the meshes I imported to -90º on X axis
![Captura de tela de 2021-12-25 09-16-40](https://user-images.githubusercontent.com/68334606/147384832-47bcb7f0-574c-434f-b404-018e54786b27.png)
But when I try to add the tiles to GridMap, it ignores the rotation
![Captura de tela de 2021-12-25 09-17-29](https://user-images.githubusercontent.com/68334606/147384843-c883bfcd-22ae-4fc5-978f-7be013b30684.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I was wondering if it is possible to configure the rotation of the tile on GridMap

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

adding a field for changing the rotation of tile in GridMap node inspector or MeshLib inspector

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think it can be worked around with lines of script, but the effects of it can only be seen when the game starts.

### Is there a reason why this should be core and not an add-on in the asset library?

maybe there is no reason for it to be a core feature.

**Comment by Calinou** [comment]
Transforms for individual MeshLibrary items is already supported since 3.4 thanks to https://github.com/godotengine/godot/pull/52298. Could you check that pull request's description and try to apply that in your own project?

**Comment by octetdev2** [comment]
Is this still an issue?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this lack of functionality in Godot 3.4.4 or later.
