### ISSUE TITLE
Add an alternative vector type notation - `(x, y)` for `Vector2(x, y)` and `(x, y, z)` for `Vector3(x, y, z)`

### ISSUE THREAD

**Issue by just-like-that** [godotengine/godot-proposals#3719]
### Describe the project you are working on

A 2D-game with lots of vector structures which I'm using with custom drawing functions.

### Describe the problem or limitation you are having in your project

In my project I'm using the vector datatype Vector2 a lot. As such it's cumbersome to always write Vector2() with parameters wherever it's used for assigning concrete values.

**That means declaring vector types with initial values for fields or arrays alike as well as in function calls, tend to spread the word Vector2 over the source code.**

I find it less intuitive and less readable than purely writing the values (x,y) as the values are framed by the word Vector2,
besides the additional effort of writing the word Vector2 or selecting the correct vector type from code completion.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

**It would be quite handy wherever vectors are used in GDScript to have a shorter notation with the same meaning and information given - just less "noisy".**

This can be useful for any kind of game or application using the vector types, as these are generic useful data structures.

**My proposal is to additionally allow the usage of (x,y) for construct Vector2(x,y) or (x,y,z) for construct Vector3(x,y,z).
That means the word Vector2 (or Vector3) is saved - the parentheses are necessary and as such mandatory and still used.**

**Instead of "constructor" Vector2(x, y) with x and y arguments just use alternative notation (x, y) by writing x- and y-values with parenthesis. I don't want to remove the existing notation, I recommend this as a shortcut for easier reading and faster writing of vector fields.**

The same also applies for type Vector3 including z-axis.

I see no overlaps or ambiguities with the existing syntax by doing so. All cases should be distinct and as such GDScript still valid. 
Both variations are still co-existing. No changes for the ones who want to stick to the explicite standard notation. 

### Benefits: 
Less to write without any loss of information while at the same time more readable.
The actual values are sticking out more at first glance - see scenarios below.
This is meant as an addition not as a replacement of the existing syntax.

### Summary:
**(x,y)   stands for Vector2(x,y).
(x,y,z) stands for Vector3(x,y,z).**

### Non-scope:

* Function call foo(x,y) is still calling function "foo" with scalar parameters x and y (as two separate parameters).
Whereas function call foo( (x,y) ) is calling function "foo" with parameter Vector2(x,y).
The parentheses for the arguments given make the difference.

* Other variations like () or (<single_scalar_value>) are not supported.
() is NOT applicable as abbreviation for Vector2(0, 0).
(0,0) is short enough and more explicit than Vector2() and is equal to Vector2.ZERO.
(<value>) is NOT applicable as abbreviation for Vector2(<value>, 0).

### Other vector types:

Everything said here also applies for vector types:
* Vector3(x-float, y-float, z-float)
* Vector2i(x-int, y-int)
* Vector3i(x-int, y-int, z-int)
Integer variants are being introduced with GDScript 4.0.

For integer variants of vector type use the notation **(<x-int>, <y-int>) for integer type**
and **(<x-float>, <y-float>) for float type**.
 
All combinations of float and int values for x- and y-axes (or z-axis) are using the float vector types.

Examples:
* (1.0, 2.0)      stands for Vector2(1.0, 2.0)
* (1, 2)            stands for Vector2i(1, 2)
* (1.0, 2.0, 3.0) stands for Vector3(1.0, 2.0, 3.0)
* (1, 2, 3)       stands for Vector3i(1, 2, 3)

### Remarks:
If the separate support for vector types float and int is too complex to implement 
I recommend to always use the standard float types as they already exist nowadays.

I think something similar exists for C++/C# with brackets {value_x, value_y, value_z}.

In all situations where usually the built-in type Vector2() (or Vector3()) is written explicitly the 
shorter and alternative notation with parentheses () is also applicable.

It's less to write with the same amount of information and it's more readable at the same time.
We have just getting used to the new alternative notation. 

### *) assignment of fields 
standard syntax:
var vec := Vector2(100, 100)

alternative syntax:
**var vec := (100, 100)**

### *) function call with parameters expecting type Vector2
standard syntax:
standard syntax:
foo( Vector2(100, 100) )

alternative syntax:
**foo( (100, 100) )**

### *) initialization of arrays
standard syntax:
var vec_arr := PoolVector2Array( [Vector2(100, 100), Vector2(200, 100), Vector2(150, 150), Vector2(100, 100)] )

alternative syntax:
**var vec_arr := PoolVector2Array( [(100, 100), (200, 100), (150, 150), (100, 100)] )**

**This also applies for generic arrays.**

### *) for-loops
standard syntax:
for idx in Vector2(0, 100): pass
for idx in range(0, 100): pass

alternative syntax:
**for idx in (0, 100): pass**

standard syntax:
for idx in Vector3(0, 100, 10): pass
for idx in range(0, 100, 10): pass

alternative syntax:
**for idx in (0, 100, 10): pass**

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think it will be used very often as we are talking about 2D- and 3D-space coordinates.
There exists a solution already by using the longer format Vector2(x,y) resp. Vector3(x,y,z).
It's just more noisy and less readable imo especially for default array initializations.

### Is there a reason why this should be core and not an add-on in the asset library?

As the vector types are built-in this can only be dealed with by the core.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/374 where this was proposed (and rejected). The problem with a `(x, y, z)` syntax is that it conflicts with the addition of tuples, which is planned in a future Godot 4.x release.

**Comment by just-like-that** [comment]
Hi @Calinou, thank you for your ultra-fast reply. I'm new to this great engine and community :)

Thank you for your clarification.

My idea initially stems from the fact to initialize arrays.

What I like to discuss is the addition of array initialization of Pool/Packed arrays hence of statically typed arrays:

The standard syntax with:
**var vec_arr := PoolVector2Array(  [ Vector2(100, 100), Vector2(200, 100), Vector2(150, 150), Vector2(100, 100) ] )**

is redundant, repetitive and less readable than the alternative syntax:
**var vec_arr := PoolVector2Array(  [ (100, 100), (200, 100), (150, 150), (100, 100) ] )**

At this point I know the type already - that's the reason why I declare it as PoolVector2Array or Packed in future.

It think it would be compatible with the future extension of tuples as the type is declared and fixed already by the context of array or dictionary.
The type of these members of an array is enforced by the array itself.

And it's more in line with other built-in types like byte, int, real or string arrays:
**var int_arr := PoolIntArray( [ 1, 2, 3 ] )**
**var int_arr := PoolStringArray( [ "1", "2", "3" ] )**

So what about considering this approach just in the event of array initialization of Vector2(i) and Vector3(i) arrays?

**Comment by Calinou** [comment]
> So what about considering this approach just in the event of array initialization of Vector2(i) and Vector3(i) arrays?

I'm afraid this is too much of a corner case to be considered. Programming languages should behave in a consistent manner – special casing should be avoided unless it saves a lot of time. Writing pooled arrays by hand is not something that's done very often in most projects, so I don't think it's worth the trouble.

**Comment by just-like-that** [comment]
Agreed. Closing.

That's what I just do now.
```
static func to_vector_array(values: Array) -> PoolVector2Array:
	var retval := PoolVector2Array()
	for idx in range(0, values.size(), 2):
		retval.push_back(Vector2(values[idx], values[idx + 1]))
	# for end
	return retval
```
