### ISSUE TITLE
Add function to get exported application version / product version

### ISSUE THREAD

**Issue by sriedi7** [godotengine/godot-proposals#372]
**Describe the project you are working on:**
Irrelevant

**Describe the problem or limitation you are having in your project:**
You can't get the version of the app or game that you export.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Make it easier to get version of my exported app.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Irrelevant

**Describe implementation detail for your proposal (in code), if possible:**
In the export preset there is a version field, example:
Android: Preset > Options > Version > Name
Windows: Preset > Options > Application > Product Version
etc
So these version should be available to get from Godot API.
My suggestion would be:
OS.get_product_version()
or
OS.get_application_version()

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Right now I use the project setting to make custom string field to write my game version and get it using ProjectSettings.get_setting(). But is not so effective because I have to edit it manually whenever I update my app version in export preset.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it is important.

**Comment by clayjohn** [comment]
Is that not what ``Engine.get_version_info().build`` returns?

**Comment by earlroxas13** [comment]
> Is that not what `Engine.get_version_info().build` returns?

tested just now on 3.2b5 it return 'official'

And I mean is not the engine version but version of the game you exported. The version that you type in Export Preset > Options

**Comment by Calinou** [comment]
You can define a custom project setting for this purpose. I'm not sure if it's technically feasible to return information from export presets at run-time, since `export_presets.cfg` isn't included in the exported PCK.

**Comment by earlroxas13** [comment]
Maybe store the value somewhere on export?
Or read from executable?

**Comment by Calinou** [comment]
Reading from the executable is something I'd consider overkill. It's also not possible on all platforms :wink:

Either way, my issue with this proposal is that not all platforms define the same metadata for each platform. If you want to access this metadata in a consistent manner cross platforms, you should define a project setting. To avoid repetition in export presets, we could do the following:

- Add an `application/config/version` project setting which defaults to something like `0.1.0`. It can be change by the user at any time.
- Rename version fields to "custom version" fields in export presets. If those fields are left empty (which is the default), the value in the project settings will be used by default.

**Comment by earlroxas13** [comment]
Yes, that's sounds good!

**Comment by SilvanaP** [comment]
From which version on is this available? It would be really nice to have access to the version code that is defined in the "export" panel in Android. I don't really want to have to set it in the ProjectSettings, additionally.

**Comment by Calinou** [comment]
> Forget what I wrote, this works like a charm on droid. Only thing to do is to add export_presets.cfg to the exported files in the export dialog:

`export_presets.cfg` contains sensitive information like Android keystore credentials. **Do not do this if you don't want to leak your release keystore!**

**Comment by KoBeWi** [comment]
> Only thing to do is to add export_presets.cfg to the exported files in the export dialog:

You don't need to include the whole export presets, you can create EditorExporPlugin that extracts version information to a file that will then be included with the build:
```GDScript
	func _export_begin(features: PoolStringArray, is_debug: bool, path: String, flags: int):
                var version = ""
                var export_config: ConfigFile = ConfigFile.new()
                var err = export_config.load("res://export_presets.cfg")
                if err == OK:
                    version = export_config.get_value("preset.1.options", 'version/code') + export_config.get_value("preset.1.options", 'version/name')

		var script = GDScript.new()
		script.source_code = str("extends Reference\nconst VERSION = ", version, "\n")
		ResourceSaver.save("res://version.gd", script)
```
Then anywhere in the project you can do `print(load("res://version.gd").VERSION)`

**Comment by KoBeWi** [comment]
Ok here's a plugin based on the above code:
https://github.com/KoBeWi/Godot-Auto-Export-Version
It will automatically fetch your project version from the profile whenever you export the project.

**Comment by blurrred** [comment]
Here's a little method that should give the Android app version with an Android plugin. It's pretty simple and straightforward if you're already using a custom Android plugin.

`
public int getVersion() throws PackageManager.NameNotFoundException {
		PackageManager manager = getActivity().getPackageManager();
		PackageInfo info = manager.getPackageInfo(getActivity().getPackageName(), PackageManager.GET_ACTIVITIES);
		return info.versionCode;
	}
`

**Comment by SteveSmith16384** [comment]
This issue does beg the question, what is/was the point of the File Version/Product version fields when exporting to (say) Windows?  Is it actually shown or used anywhere?

**Comment by YuriSizov** [comment]
It is available in the "Properties" dialog, if you right click on the executable. It is useful in some cases, but it's mostly useful to you as a developer, so you can attribute bugs and issues to a specific version.

**Comment by YuriSizov** [comment]
If you've specified them but they don't get written, that's probably because you don't have rcedit, or it just doesn't work (because it's not very reliable).

But I can confirm that it should work in principle:
![image](https://user-images.githubusercontent.com/11782833/210814574-5bd425ff-53f9-4260-9783-ad5326e6d4e6.png)
