### ISSUE TITLE
Allow setting a World2D to be used for rendering in CanvasItem

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot-proposals#3721]
### Describe the project you are working on

A game that heavily uses worlds to separate things like overlay, game itself, gui and etc, this allows for things like being able to independently zoom them, screenshot and etc

### Describe the problem or limitation you are having in your project

Injecting world 2d to viewports that are already in the scene tree does not update its children world, 

And there are cases where adding another viewport is not needed, only access to a separate world

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature would allow nodes with the same parent to be part of different world, which would open up a lot of possibilities and reduce clutter of viewport nodes

Imagine an Entity scene, you could add a sprite inside it that would automatically appear on a minimap, by just overwriting the world of the sprite, and when you delete that entity, the sprite is also deleted

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

sprite.set_world2d = World2D.new()

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well yes, but it becomes messy really fast, not to mention the overhead with all the viewports

### Is there a reason why this should be core and not an add-on in the asset library?

it seems suitable as a built in feature

**Comment by Calinou** [comment]
Wouldn't https://github.com/godotengine/godot/pull/52389 suffice?

**Comment by LoneDespair** [comment]
> Wouldn't [godotengine/godot#52389](https://github.com/godotengine/godot/pull/52389) suffice? There is also a `3.x` version of that pull request: [godotengine/godot#52391](https://github.com/godotengine/godot/pull/52391)

Thank you, very excited for that feature
