### ISSUE TITLE
Build from source using Docker

### ISSUE THREAD

**Issue by theoniko** [godotengine/godot-proposals#3724]
### Describe the project you are working on

Using docker in a project makes third party dependencies easily handled. It makes also possible to work on different machines/OS.

### Describe the problem or limitation you are having in your project

Sometimes it is not easy to build from source the project in Windows and it is time consuming to find the missing dependencies.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Creating a docker build from source support by adding a dockerfile with all the dependencies and a  tutorial wiki on how to use it. It can be incorporated to ci build and have an official docker image that can be pulled

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just a Dockerfile with all dependencies or an official docker image would be enough as a first step. Possible shell script like build and run docker would also be helpful.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

.

### Is there a reason why this should be core and not an add-on in the asset library?

I think that it would bring more contributors to the project since it would be easy to build. At least for me it was always a challenge to build from source a new project especially in windows os.

**Comment by pycbouh** [comment]
If you are referring to building the engine itself, then you can use the official build scripts and build containers, available here:
https://github.com/godotengine/godot-build-scripts
https://github.com/godotengine/build-containers

That said, I'm not sure which issues you are experience on Windows. I use Windows exclusively, and [the docs](https://docs.godotengine.org/en/stable/development/compiling/index.html) cover everything there is to configure.
