### ISSUE TITLE
Add a built-in sprite editor

### ISSUE THREAD

**Issue by SoyoTamo** [godotengine/godot-proposals#3728]
### Describe the project you are working on

It would serve at least for any project that handles pixelart

### Describe the problem or limitation you are having in your project

Comparing with GMS2 when making a pixelart game, the tool to create and edit sprites is missed by doing something crude to godot when working with pixelart.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose two new features:

-Edition: Once our sprite has been imported from wherever we find it, in the preview of the sprite or by clicking on its file, have an edition option that gives us the possibility of drawing or eliminating pixels (or draw on top of a jpg or whatever), (level of complexity of the characteristic later on).

-Creation: When we want to import a sprite in the sprites node (or wherever it may be appropriate to have that option), have the option to create one that will direct us to that editing feature.

And well as a tool I propose something simple similar to piskel, but how will it be needs more debate.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have no bigger idea

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's part of the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes. It is something that should be well integrated and I believe that it is something that if it were well done, the vast majority of people would use, in addition to being an appropriate characteristic.

**Comment by SoyoTamo** [comment]
I also propose to up the ante with the ability to handle layers in the edition to facilitate animations.

**Comment by Calinou** [comment]
A built-in sprite editor has been proposed numerous times already, but this is something that would be better implemented in an add-on. Also look into tools such as [Pixelorama](https://github.com/Orama-Interactive/Pixelorama) :slightly_smiling_face:

**Comment by SilencedPerson** [comment]
I think the main problem is that people expect full blown image editor inside Godot. I would be fine if it's intended use was for placeholders. Just make it implicit by name, not "sprite editor" but "2D placeholder editor". Sometimes, you just need a sprite that has two shitty frames for a lever, one for a wall, one for an enemy. Using the default Icon is not viable so you have to open external editor doing exactly that with added downtime of having to save the file to a correct place, it would be extremely welcome not having to go through that. Closest i got to having the process non-intrusive was with photoshop with image generator feature that automatically save named layers.

**Comment by WolfgangSenff** [comment]
I actually think this is the wrong approach. I think we should have a property in the editor settings that allows you to put in a specific external editor that is then opened when you double-tap a sprite or model (two settings: one for 2D, one for 3D?). This would be very similar to the approach to handling external code editors, and is a less-intensive solution for developers, as noted in the reasons above.

**Comment by Calinou** [comment]
> I actually think this is the wrong approach. I think we should have a property in the editor settings that allows you to put in a specific external editor that is then opened when you double-tap a sprite or model (two settings: one for 2D, one for 3D?). This would be very similar to the approach to handling external code editors, and is a less-intensive solution for developers, as noted in the reasons above.

There's already a proposal tracking this: https://github.com/godotengine/godot-proposals/issues/328
