### ISSUE TITLE
Add function to emulate features when playing the game from Editor

### ISSUE THREAD

**Issue by sriedi7** [godotengine/godot-proposals#373]
**Describe the project you are working on:**
Right now my game have 3 version that separated using feature:
1. Normal version
2. Demo version -> using feature tag 'demo'
3. Free version -> using feature tag 'free'

**Describe the problem or limitation you are having in your project:**
As an example, I have this project setting field "Stage Count" that is the number of stages that player can play.
In the normal version it is 20, in the demo version it is 8. For now if I want to test the demo version I have to export the game using preset that have feature tag demo.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If this feature implemented I dont have to export the game to test it.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Irrelevant

**Describe implementation detail for your proposal (in code), if possible:**
Add the Project Setting to store the feature you want to emulate.
My suggestion would be:
debug/settings/feature/emulated

Then if I use the OS.has_feature() it should return true if the feature tag is written in the setting above.
And also if you get ProjectSetting using ProjectSettings.get_setting() is should return the overrided value if any.

And also this should ONLY work on Editor and SHOULD NOT work on exported game.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
AFAIK,no.

**Is there a reason why this should be core and not an add-on in the asset library?:**
No, but it should be in the core to make testing more easy

**Comment by Calinou** [comment]
This can be worked around by having a method in a singleton whose `return` value depends on the feature tag or project setting:

```gdscript
func is_demo_mode():
    return OS.has_feature("demo) or ProjectSettings.get_setting("debug/emulate_feature_tag) == "demo"

It's not as convenient as a built-in feature, but it should suffice.

**Comment by KoBeWi** [comment]
Related: https://github.com/godotengine/godot/issues/22587

**Comment by lekoder** [comment]
Since godotengine/godot#22587 was closed in favor of this one, it's worth noting that features also provide resource overrides (ie. different logo for demo/free/full versions, etc), which is *not* handled by the workaround.

**Comment by earlroxas13** [comment]
> it's worth noting that features also provide resource overrides (ie. different logo for demo/free/full versions, etc), which is not handled by the workaround.

By logo did you mean the icon? I also encounter this. So, I have made 3 separate icons for each build. But the demo and Free icon is error and not assigned to the game.
![Logo](https://user-images.githubusercontent.com/8316851/72239045-40a3a880-3612-11ea-9ff1-380429304195.jpg)
And I check in the pck file (saved as zip) the icon for demo and free is not in the pck file.
Should we create another issue/feature proposal for this?

**Comment by lekoder** [comment]
[Here is the relevant documentation fragment.](https://docs.godotengine.org/en/3.1/getting_started/workflow/export/feature_tags.html#overriding-project-settings)

**Comment by Calinou** [comment]
I started working on this feature, although I don't know if I'll be able to complete it: https://github.com/Calinou/godot/tree/add-editor-custom-feature-tags-setting

**Comment by object71** [comment]
I would really like to see this implemented. I need it to distinguish a dedicated server from a client and the two for example have a different main scene override in the project settings. I want to safeguard my code with OS.has_feature.

**Comment by object71** [comment]
@Calinou I looked at your WIP commit in the branch you have linked here. It seems to be alright. Isn't this enough for this feature's implementation?

**Comment by Calinou** [comment]
> @Calinou I looked at your WIP commit in the branch you have linked here. It seems to be alright. Isn't this enough for this feature's implementation?

As the commit message says:

> TODO:
>
> - This compiles but it doesn't work yet (it does nothing).

**Comment by KoBeWi** [comment]
I've been thinking about this and ProjectSettings might not be the best place to put it. When working on a team project, it would be very easy to commit a feature tag that you just used to test something, which isn't desired. Also projects settings isn't the best place to store something that needs to be frequently changed.

On the other hand, we can't really have `set_feature_tag()` function, because the tags need to be known when the project is starting (for project setting or resource overrides that depend on features; these would be useful to test too).

So I think the best way would be to read an environment variable, e.g. `CUSTOM_TAGS`, which could be set using an editor plugin. This would have the best usability for advanced users, but the feature wouldn't be convenient for beginners.
