### ISSUE TITLE
Improve the default size of 3D shapes and meshes (Box, Capsule, and Cylinder)

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#3732]
### Describe the project you are working on

This applies to any 3D game, especially ones with human or humanoid characters.

### Describe the problem or limitation you are having in your project

The current default sizes for 3D shapes is a bit sub-optimal, and they almost always require tweaking.

![Screen Shot 2021-12-30 at 4 25 16 PM](https://user-images.githubusercontent.com/1646875/147796427-8074eb56-e714-454a-8c17-2584cd358e61.png)

* Box shapes currently have a default size of (2, 2, 2), which is a radius of 1. This means that if a node with a box is scaled by, for example, 7, then the box is 14 meters wide. It would make more sense to have a default size of (1, 1, 1) so that a scale of 7 means it's 7 meters wide.

* Capsule shapes are commonly used for characters, but the current default size is far too big and too wide to use for a human-sized character (1m radius, 3m height). It would make more sense to have the default be smaller.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose changing the default sizes to be more suitable. Boxes would have a default size of (1, 1, 1), and capsules/cylinders would have a default size of 0.25m radius and 1.75m height. It would look like this:

![Screen Shot 2021-12-30 at 3 30 39 PM](https://user-images.githubusercontent.com/1646875/147796451-1adf77a1-956e-4d45-a49b-baeed55822f7.png)

For reference, I looked at GDQuest's 3D mannequin model. This model is a great reference since its size is average human size. The example project for the model has a capsule with the exact dimensions proposed:

![Screen Shot 2021-12-30 at 3 16 47 PM](https://user-images.githubusercontent.com/1646875/147796471-b7875eff-9385-417c-a1ee-780d1b16cdb1.png)

Here's a comparison with both the old and new sizes right next to each other, so you can see how comically large the current defaults are if you tried to use them for a character controller (well, unless [this](https://lumiere-a.akamaihd.net/v1/images/p_turningred_21513_77ebf000.jpeg) is your character):

![Screen Shot 2021-12-30 at 3 40 19 PM](https://user-images.githubusercontent.com/1646875/147796535-60b75b85-d44a-4ac2-8046-d57c945e7e61.png)

The specific values of 0.25 and 1.75 are also nice because they are exact floats while being easy to remember/write.

The Y position would need to be set to 0.875 to put the bottom of the capsule at Y = 0.

If desired we could change these values to something else. 0.5 and 2.0 would be simpler and still better than 1.0 and 3.0, but I think 0.25 and 1.75 are much nicer values since they are very close to the size of an average human. Average human height is 1.74 meters, so 1.75 is extremely close to that amount.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Branch: https://github.com/aaronfranke/godot/tree/default-shape-size

PR: https://github.com/godotengine/godot/pull/56365

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it can be easily worked around without using any script. Also, even with improved defaults, the sizes will have to be adjusted in many cases because not all characters are the same, but hopefully with improved defaults the sizes will need to be adjusted less often and adjusted a smaller amount.

### Is there a reason why this should be core and not an add-on in the asset library?

These are defaults for shape already in the core engine, so it's already core.

**Comment by Calinou** [comment]
Should these changes also be applied to CSG nodes for consistency? I'd personally prefer CSG nodes to be as consistent as possible with their PrimitiveMesh counterparts (see https://github.com/godotengine/godot/pull/49729).

**Comment by aaronfranke** [comment]
@Calinou Yes, I think so. While CSG nodes are unlikely to be used for character controllers, they'd also probably have to be adjusted for every situation and there isn't one commonly-useful size (ex: human size), so the default size doesn't matter much. Therefore it would make sense to me to keep the CSG sizes in sync with the primitive changes proposed here.
