### ISSUE TITLE
GDScript `match` should work for type matching

### ISSUE THREAD

**Issue by balintbarna** [godotengine/godot-proposals#3733]
### Describe the project you are working on

VR Game

### Describe the problem or limitation you are having in your project

I'm using node children as components and I want to iterate through children and do something based on their type, eg
```gdscript
for child in get_children():
    if child is GrabComponent:
        child.grab()
    elif child is SomethingElse:
        child.call_something_else()
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Using match for type checking will make it less spaghetti

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same with match:
```gdscript
for child in get_children():
    match child:
        GrabComponent:
            child.grab()
        SomethingElse:
            child.call_something_else()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I haven't found a way to do type checking with match

### Is there a reason why this should be core and not an add-on in the asset library?

Improvement to GDScript basics has to be

**Comment by Calinou** [comment]
Are there types in GDScript that allow checking for both equality (`==`) and identity (`is`)? If so, this can create ambiguity and probably shouldn't be allowed.

**Comment by zacryol** [comment]
> Are there types in GDScript that allow checking for both equality (`==`) and identity (`is`)?

any Object does; `is` for class check, and `==` for exact reference

**Comment by balintmaci** [comment]
@Calinou Good point, I was very sure that Python does this already but now I cannot find any examples.

**Comment by Mickeon** [comment]
I find this would be a pretty neat Quality of Life feature, similar to matching `type_of()` with different Variant types. Perhaps it could be combined with the `is` keyword somewhere to make it less ambiguous? Although, that may reduce discoverability.

An alternative would be to have `get_class()` dynamically return the custom class name if overwritten, something that https://github.com/godotengine/godot/issues/21789 at first believed was going to be the case, as well.

**Comment by zacryol** [comment]
> similar to matching `type_of()` with different Variant types. 

this is different typeof() returns one specific value regarding the var type.
The proposal is for class checking, which applies to all inherited classes. There's no single value to compare to get that info.

**Comment by Mickeon** [comment]
> this is different, as typeof() returns one specific value regarding the var type.
I'm aware. I wasn't contesting its existence, rather comparing it to the proposal.

**Comment by dalexeev** [comment]
It already works. But at the moment this only works for const-preload scripts. Using other classes results in the "Expression in match pattern must be a constant" error.

```gdscript
const A = preload("res://a.gd")
const B = preload("res://b.gd")

func f(x):
    match x.get_script():
        A: print("A")
        B: print("B")

func _run():
    f(A.new())
    f(B.new())
```

**Comment by balintmaci** [comment]
I'm not sure why I couldn't find this last time, but Python definitely allows matching classes and it's even more powerful
![image](https://user-images.githubusercontent.com/13272850/148116519-11c569ec-2cb3-4ba7-b17c-1eafb35ffe1e.png)

full docs [here](https://www.python.org/dev/peps/pep-0636/#adding-a-ui-matching-objects)
the example reads *Rather than writing multiple isinstance() checks, you can use patterns to recognize different kinds of objects, and also apply patterns to its attributes*

Of course GDScript does not have to copy every feature of Python exactly, but instance checking in match would be a very welcome addition.

**Comment by balintmaci** [comment]
Maybe a clearer example for Python:
```
from dataclasses import dataclass

@dataclass
class Point:
    x: int
    y: int

def where_is(point):
    match point:
        case Point(x=0, y=0):
            print("Origin")
        case Point(x=0, y=y):
            print(f"Y={y}")
        case Point(x=x, y=0):
            print(f"X={x}")
        case Point():
            print("Somewhere else")
        case _:
            print("Not a point")
```

**Comment by dalexeev** [comment]
I suggest adding the following syntax for type checking (since `is` is not the same as `==`):

```gdscript
match value:
    is ClassA:
        print("Class A")
    is ClassB:
        print("Class B")
```

**Comment by balintmaci** [comment]
I would argue that the match keyword, as pattern matching, is already doing much more than a simple value equality check.
It can match to patterns that could take up many values and by matching it to different types of containers you're matching it to a type, eg. `[..]` according to the examples below. On top of that there's also binding to local vars.
```gdscript
match x:
    [var start, _, "test"]:
        print("First element is ", start, ", and the last is \"test\"")
    [42, ..]:
        print("Open ended array")
    {"name": "Dennis", "age": var age}:
        print("Dennis is ", age, " years old.")
    {"name", "age"}:
        print("Has a name and an age, but it's not Dennis :(")
    {"key": "godotisawesome", ..}:
        print("I only checked for one entry and ignored the rest")
    1, 2, 3:
        print("It's 1 - 3")
```

To achieve the same code with `if`s you'd need to check if your variable `is` dictionary or array or something else. From there it makes sense syntactically to just match to any type, just as Python also does. It would be very powerful, especially with binding.

**Comment by dalexeev** [comment]
And next time someone asks to add this:

```gdscript
match x:
    < 0:
        print("a")
    >= 0 and < 10:
        print("b")
    >= 10:
        print("c")
```

Some balance is needed between syntactic sugar and verbose but clear code. We must first make sure that this is a useful and commonly used feature before introducing more sugar.

**Comment by balintmaci** [comment]
@dalexeev I understand your concern but hopefully this feature proposal will be debated based on its own usefulness and merit and not based on what someone else may or may not ask in the future.

I personally use the scene tree with type checking children extensively and it'd be quite nice to have this feature, not because it would save me 20 seconds every time but because it would make my code more readable.

For example 
```gdscript
if child is ARVRCamera:
    hmd = child
elif child is ARVRController:
    match child.controller_id:
        1:
            left = child
        2:
            right = child
elif child is ARVRAnchor:
    anchors.append(child)
```
could potentially become 
```gdscript
match child:
    ARVRCamera:
        hmd = child
    ARVRController(controller_id=1):
        left = child
    ARVRController(controller_id=2):
        right= child
    ARVRAnchor:
        anchors.append(child)
```
and the more potential classes and options you have the more this sugar helps with readability

**Comment by nonunknown** [comment]
> Are there types in GDScript that allow checking for both equality (`==`) and identity (`is`)? If so, this can create ambiguity. I would prefer to avoid making `match` ambiguous here, so I'd err on the side of caution and not implicitly perform `is` comparison behind the user's back.

I think this confusion can simply be solved by doing this:

```gdscript
for child in get_children():
    match child:
        is GrabComponent:
            child.grab()
        is SomethingElse:
            child.call_something_else()
```

**Comment by timothyqiu** [comment]
This will be used often in input callbacks. It's de facto standard to write something like this, especially if you want static typing:

```gdscript
func _input(event):
    var mb := event as InputEventMouseButton
    if mb:
        pass  # handle mouse button events here

    var mm := event as InputEventMouseMove
    if mm:
        pass  # handle mouse move events here
```

The current `match` already supports variable binding, but very limited:

```gdscript
match x:
    1:
        print("It's one!")
    2:
        print("It's one times two!")
    var new_var:
        print("It's not 1 or 2, it's ", new_var)
```

Type matching could extend the existing variable binding syntax:

```gdscript
func _input(event):
    match event:
        var mb: InputEventMouseButton:
            pass
        var mm: InputEventMouseMotion:
            pass
```

**Comment by jonSP12** [comment]
its also not working for me, from converting pervious project in 3.5 to 4.0
It crashes right after pressing Play

![match](https://user-images.githubusercontent.com/77213594/206147680-8e051ff2-b29d-4514-a21a-348f1daf97f7.png)



```
@onready var pt1_spr = get_node_or_null("bodyCollision/01Lhand1");
@onready var pt1_up1 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneUp1");
@onready var pt1_up2 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneUp2");
@onready var pt1_up3 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneUp3");
@onready var pt1_md1 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneMiddle1");
@onready var pt1_md2 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneMiddle2");
@onready var pt1_md3 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneMiddle3");
@onready var pt1_dn1 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneDown1");
@onready var pt1_dn2 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneDown2");
@onready var pt1_dn3 = get_node_or_null("bodyCollision/01Lhand1/Skeleton2D/BoneDown3");
```

**Comment by balintbarna** [comment]
Closing as not using it anymore.
