### ISSUE TITLE
Bring back an option to not use atlases in LightmapGI

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#3734]
### Describe the project you are working on

Large Open World game

### Describe the problem or limitation you are having in your project

LightmapGI in 4.0 automatically atlases the textures into a single 16k image. While this is fine for environments that aren't very large, in complex environments this is easily taken up.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Bring back the option to make Lightmap textures per mesh, and add Texture LOD support (to save on Memory usage) so that distant Textures aren't as detailed, but close up meshes are as detailed as needed.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Return "Generate Atlas" to LightmapGI

To save on memory usage, Stream in Lightmap textures of a given quality as needed based on distance.
Note: This would require Texture Streaming to be implemented which isn't planned for 4.0 afaik.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Lightmaps are Core, and there's no way to change a core functionality easily without tweaking the engine.

**Comment by Calinou** [comment]
My understanding is that using an atlas is always better/faster/more organized than not using an atlas. Godot 3.x supports not using atlases in BakedLightmap because these are only supported when using GLES3, not GLES2.

**Comment by mrjustaguy** [comment]
True, Atlases are faster, more organized and generally better, until your lightmaps accumulate a total over 16k x 16k worth of pixels, which for really complex scenes can happen, and for such cases, having an option to not use atlases, or use multiple atlases (tho this would be really messy to stream into memory only the bits you need efficiently) is a must, as you want to have only one Baked Lightmap pass, as multiple mixed (Split in multiple scenes and baked separately) will produce artifacts quite often, or at the very least make it really difficult to make the Scenes.

**Comment by mrjustaguy** [comment]
Closing as the issue was solved by https://github.com/godotengine/godot/pull/61861
