### ISSUE TITLE
No function available to get the vertical scrollbar of a TextEdit

### ISSUE THREAD

**Issue by andrea-calligaris** [godotengine/godot-proposals#3737]
### Describe the project you are working on

GUI-oriented project.

### Describe the problem or limitation you are having in your project

There currently is no function to get the vertical scrollbar of a `TextEdit`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A `get_v_scrollbar()` function, like with ScrollContainer.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`var scrollbar = my_text_edit.get_v_scrollbar()`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It's provided in `ScrollContainer`, makes sense to have it in `TextEdit` and maybe in other Controls too, but open to debate.

**Comment by KoBeWi** [comment]
Vertical scroll is a property of TextEdit. Why do you need to access scroll bar? It's not needed for theming or hiding it.

**Comment by andrea-calligaris** [comment]
It was to work around https://github.com/godotengine/godot/issues/56384, otherwise yes it's probably not needed.
Thanks for that code workaround.
