### ISSUE TITLE
Add buttons to open project settings and export a project in the project manager

### ISSUE THREAD

**Issue by SoyoTamo** [godotengine/godot-proposals#3738]
### Describe the project you are working on

It isn't relevant, it is useful for 100% of the projects

### Describe the problem or limitation you are having in your project

1-The project launcher lacks configuration, it is just a step in the middle to get to the editor.
2-In godot 4 I have to do strange things to not work with vulkan because it does not allow me to open the editor (I have an old pc).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, I have several ideas to bring to the table:

1-Buttons in projects:

-A button to the right of each project that launches you to the project settings.
-A button next to the previous one that serves to export the project (this characteristic seems especially logical to me, and more considering the previous one, in case you want to configure something before exporting it).

2-Besides being useful by itself if you don't have real problems, for my problem in the second point it would be still a little more useful:

-Make editor settings and editor features settings accessible from the project launcher. This seems especially useful to me to have the editor just the way you want it to be without having to enter it in the first instance.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have no major idea, but it is certainly something quite feasible.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No :(

### Is there a reason why this should be core and not an add-on in the asset library?

It is part of the core / editor.

**Comment by SoyoTamo** [comment]
For example, I don't work with 3D for now, so supposing that I download a new version of godot, to create a project I have to go through 3D which takes up some memory, remove 3D and reopen the editor and thus lighten it a bit, which is a bit cumbersome.

**Comment by Calinou** [comment]
> to create a project I have to go through 3D which takes up some memory, remove 3D and reopen the editor and thus lighten it a bit (which means that even if you remove a feature while in the editor it will still use memory space unless you restart it. It is something that could be improved, but it is still something that makes it more logical to have the editor configuration from the beginning.), which is a bit cumbersome.

Disabling 3D will not actually free up memory or disk space.

**Comment by SoyoTamo** [comment]
I mean the space in RAM :), In case you didn't know, disabling features reduces ram usage in GODOT.

**Comment by Calinou** [comment]
As for the proposal itself:

> -A button to the right of each project that launches you to the project settings.

This is something that can be done in two clicks (or one, if you hold down the left mouse button) after opening a project in the editor. It does not warrant having its own button.

> -A button next to the previous one that serves to export the project (this characteristic seems especially logical to me, and more considering the previous one, in case you want to configure something before exporting it).

If you have to export a project frequently, look into using the [command line](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html) to automate the export process. This will save you move time compared to having to open the project manager or editor.

> -Make editor settings and editor features settings accessible from the project launcher. This seems especially useful to me to have the editor just the way you want it to be without having to enter it in the first instance.

This is already being tracked in https://github.com/godotengine/godot-proposals/issues/1602.

**Comment by SoyoTamo** [comment]
It is possible that it can already be done, but I do not think that having visual references bothers anyone, especially new ones, after all the project manager is not like it has too many elements for someone to see this bloated or out of place.

**Comment by Calinou** [comment]
> after all the project manager is not like it has too many elements for someone to see this bloated or out of place.

The project manager is the first UI new users see. It needs to be as simple as possible as to not overwhelm new users.
