### ISSUE TITLE
Add support for vector literals in GDScript

### ISSUE THREAD

**Issue by MyriaCore** [godotengine/godot-proposals#374]
**Describe the project you are working on:**
A 2D top down shooter/puzzle game that has a heavy emphasis on projection/reflection physics. This feature applies to all projects, though, as it relates to vector algebra, something we all have to slog through eventually as game developers.

**Describe the problem or limitation you are having in your project:**
Writing physics related code feels very unnatural, not because it's significantly difficult to work with vectors in godot, but because GDScript is already such a compact language that having to type out `Vector2(..., ...)` or `Vector3(..., ..., ...)` any time I want to create a vector contrasts very harshly with what I need to do to create a list or a dictionary. This compounds when (for example) working with lists of vectors, or a dictionary of vectors, making for a very cumbersome editing experience:
```
var vlist = [Vector2(..., ...), Vector2(..., ...), Vector2(..., ...), ...]
var vdictionary = { 
   "v1": Vector2(..., ...), 
   "v2": Vector2(..., ...), 
   "v3": Vector2(..., ...), 
   ...
}
```

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
GDScript borrows a lot of design elements from python, one of which is upheld across most of GDScript, but not when it comes to vectors (and some other physics-related types). In python, *most* commonly-used standard library datatypes can be expressed as literals:

| Literals in Python | Literals in GDScript |
| --- | --- |
| String literals: `"halo"` , `'12345'` |  Strings: `"Hello"`, `"Hi"`; Multiline strings:  `"""Hello"""` |
| Int literals: `0`,`1`,`2`,`-1`,`-2` | Base 10 integers: `45`; Base 16 (hex) integers: `0x8F51` |
| Float literals: `3.14` | Floating point numbers: `3.14`, `58.1e-10` |
| Boolean literals: `True` or `False` | Booleans: `true`, `false` |
| List literals: `[]`, `[5,6,7]` | Lists: `[1, 2, 3, 4]` |
| Dict literals: `{}`, `{'x':1}` | Dictionaries: `{ "a": 1, "b": 2, "c": 3 }` |
| Set literals: `{8,9,10}` |  |
| Long literals: `89675L` |  |
| Complex literals: `12j` |  |
| Unicode literals: `u"hello"` |  |
| Tuple literals: `()`, `(9,1)`,`(8,9,0)` |  |
|  | NodePath or StringName: `@"Node/Label"`  |
| | Shorthand for `get_node("NodePath")`: `$NodePath` |

As we can see, even complex datatypes, like dictionaries and sets, get their own literal representations. Godot has started taking this approach with some of their own standard-library concepts, like the `@"Node/Label"` and `$NodePath` literals.  

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
In code, I propose we implement vector literals using angle brackets, to best align with notation used in vector algebra:
- Vector2: `< v₀, v₁ >`
- Vector3: `< v₀, v₁, v₂ >`

Here's what real examples of code might look like with this syntax:
```
$Node2D.position = <400, 300>

var sprite = $Node2D/AnimatedSprite
if vel != <0, 0> and not sprite.playing: sprite.play("moving")

match vel:
   <0, 0>:
      print("player is standing still") 
   <0, var v_y>:
      print("player is moving %s at %d px/sec"  \
         % [("north" if v_y > 0 else "south"), abs(v_y)])
   <var v_x, 0>:
      print("player is moving %s at %d px/sec " \
         % [("west" if v_x > 0 else "east"), abs(v_x)])
   <var v_x, var v_y>:
      print("player is moving %s%s at %d px/sec"  \
         % [("north" if v_y > 0 else "south"), \
            ("east" if v_x > 0 else "west"), vel.length()])
```

**Describe implementation detail for your proposal (in code), if possible:**
In [`godotengine/godot/modules/gdscript`](https://github.com/godotengine/godot/tree/master/modules/gdscript):
1. Edit [`gdscript_tokenizer.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_tokenizer.h) and [`gdscript_tokenizer.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_tokenizer.cpp)
so balanced angle brackets can be properly recognized by the parser as relating to vector literals
2. Edit [`gdscript_parser.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.h) and [`gdscript_parser.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.cpp) to add parsing logic that makes terms of the form `< t₁, t₂>` and `< t₁, t₂, t₃>` legal. Also, add logic to ensure that at the the `<` token relating to less-than checks and the `<` token relating to vector-literals are distinguishably distinct. 
3. Edit [`gdscript.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript.h) and [`gdscript.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript.cpp) in the event that we need to add special evaluation rules to ensure less-than checks distinct from a vector-literal's opening bracket, as required in step 2.
4. Edit [`gdscript_compiler.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_compiler.h) and [`gdscript_compiler.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_compiler.cpp) in the event that target code relating to vectors should be different when working with literals vs. classes. I don't *think* this should be the case, as to my understanding, by the time the compiler is running, the distinction between literal datatypes and non-literal datatypes should've been abstracted away, but I could easily be wrong, which is why I include this step here.
5. Edit [`gdscript_editor.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_editor.h) and [`gdscript_editor.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_editor.cpp) in the event that we need to do more to allow the editor to properly work with the literals (suggest completions, possibly match braces, etc).

And that should be it! 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Adoption of this feature depends on how many Godot users prefer data literals over the use of class constructors. Those coming from C# would likely use this feature fairly little, but those used to languages like python would be more likely to use this feature very often.

That being said, I don't think this can be worked around with a few lines of script, unless GDScript has macro support. Because of the nature of implementing a new literal, we'd naturally need access to the parser/interpreter to make this work. 

**Is there a reason why this should be core and not an add-on in the asset library?:**

- If implemented as an add-on, it would likely need to add a whole new scripting language, forcing users to choose between "GDScript", and "GDScript-more-literals" as their scripting language, and that's not something that's really reasonable.
- It would also make updating more difficult, because if a new version of GDScript comes out, the compiler would have to be re-forked and merged back into the add-on.
- This feature would allow the language to channel more of python's flow-inducing syntax, which, in this case, is a good thing for everyone involved.

**Comment by Calinou** [comment]
I don't see much of a practicel use for this. It's more difficult to understand for beginners and adds further *choice paralysis* as you now have two ways to write Vector2s and Vector3s.

**Comment by Jummit** [comment]
> I actually regret proposing $ as an alias for get_node(), so there's that too…

I used that everywhere when it first came out, but then ended up storing nodes into variables instead, which is cleaner and more scalable. I don't really use it at all anymore.

**Comment by lawnjelly** [comment]
How would this fit in with the use of Vector2i and Vector3i when they are added? This could potentially make things ambiguous, especially with the move towards more strongly typed gdscript (for performance and safety).

**Comment by regakakobigman** [comment]
I like shorthand for common usecases, though I think this has too many complications.

Some advantages I can see:

* Much faster to type
* Integrates well with pattern matching

Disadvantages:

* Conflicts with VectorNi like @lawnjelly mentioned; we can add alternate syntax, but it will add even more complexity
* More complexity makes things harder to read. I think we should be frugal with new syntax or operators like `@/$` to keep the barrier to entry for the language low.

While this isn't a solution right now, future first class functions/classes might allow you to shorten the default constructors. Something like `var v2 = Vector2`.

**Comment by MyriaCore** [comment]
> I don't see much of a practical use for this. It's more difficult to understand for beginners and adds further _choice paralysis_ as you'd now have two ways to write Vector2s and Vector3s.
> 
> I actually regret proposing `$` as an alias for `get_node()`, so there's that too…

Definitely a good point. The use case is certainly more stylistic than practical, and the general consensus in this thread seems to be neutral-negative, so I understand why this might not be pursued anytime soon. 

> How would this fit in with the use of Vector2i and Vector3i when they are added? This could potentially make things ambiguous, especially with the move towards more strongly typed gdscript (for performance and safety).

This is certainly the best argument against this proposal. My solution would honestly be to prefer the common case and implement this only for Vector2/Vector3, but this decision is ultimately messy and arbitrary and creates unnecessary complexity.

**Comment by vnen** [comment]
I don't think this is a bad idea. The question is just when to stop adding shorthands. Do we need it for Quaternion? Color? Plane? Rect2?

We could just make this one for vector and make clear that the others won't be made. We just need to draw a line.

> I actually regret proposing `$` as an alias for `get_node()`, so there's that too…

Honestly if you make any project in Godot you quickly see that the `$` is quite handy. Even if you cache the nodes in variables. It's not harder to read, it just makes GDScript a bit harder to learn.

Though for Vector2/3 I'm not sure if they are that much used to justify. I feel it's more common to be using existing vectors for calculations than creating a bunch yourself.

----

> 1\. Edit [`gdscript_tokenizer.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_tokenizer.h) and [`gdscript_tokenizer.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_tokenizer.cpp)
>   so balanced angle brackets can be properly recognized by the parser as relating to vector literals

I don't think this can be done. A construct like: `if x < 2 and y > 2:` is pretty hard (if not impossible) to distinguish from a vector constructor by the tokenizer. You can get hairy stuff like: `<1 if x > 2 else 3, 4 if y < 5 else 6>` which should be a valid construct, but can't really be caught by the tokenizer. Of course, you don't really *need* that the tokenizer care about this, it just need to emit the `LESS`/`GREATER` token and the parser should know what to do.

> 2\. Edit [`gdscript_parser.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.h) and [`gdscript_parser.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.cpp) to add parsing logic that makes terms of the form `< t₁, t₂>` and `< t₁, t₂, t₃>` legal. Also, add logic to ensure that at the the `<` token relating to less-than checks and the `<` token relating to vector-literals are distinguishably distinct.

This is what worry me most. Though since the vector `<` is kind of a prefix operator and the less `<` is an infix one, it should not be hard to distinguish between both.

**Comment by vnen** [comment]
Quick search in GitHub shows that people use this quite often.

* Vector2: https://github.com/search?l=&q=Vector2+language%3AGDScript&type=Code
* Vector3: https://github.com/search?l=&q=Vector3+language%3AGDScript&type=Code

Though many of those would be replaced by integer variations if we had those. Since AFAIK we plan to add it, the shorthand also needs an integer specification (maybe `i<0, 0>` or `<0, 0>i`?)

**Comment by bojidar-bg** [comment]
Note that if newlines are allowed inside the `<x,y>` construct, we need arbitrary look-ahead to determine whether a vector expression ends at `>` or not.
```gdscript
< 0, 0 >
1 + 1 + 1 + 1 + … > 4
```
Now, if the 4 is missing, this is equivalent to `Vector2(0, 0 > 1 + ...)` Otherwise, it is equivalent to `Vector2(0, 0)` followed by a comparison `1 + ... > 4`.

`i<0, 0>` also requires arbitrary look ahead, regardless of newlines:
```gdscript
f(i<0, 1 + 1 + … > 4)
```
Now, depending on the presence of 4, this is either `f(Vector2(0, 1 + …))` or ``f((i < 0), (1 + … > 4))`.

---

Consider the alternative `v(x, y)` / `v(x, y, z)`, or just `(x, y)` / `(x, y, z)`, as it almost the same length, while not changing the syntax at all.

**Comment by girng** [comment]
I keep getting flashbacks of C++'s Map/Template syntax.  Pair this with the static typing syntax, and gdscript is going to be really hard to read in a few years (and especially for new programmers), a strong no from me.

**Comment by dalexeev** [comment]
What about

```
Vec2(1, 1)
Vec3(1, 1, 1)
```

or

```
Vec(1, 1)
Vec(1, 1, 1)
```
?

**Comment by Calinou** [comment]
@dalexeev If we do that, we might as well rename the type entirely. We'd lose a bit on clarity though – I tend to favor code that reads like prose, without too many abbreviations.

**Comment by dalexeev** [comment]
@Calinou I generally agree with you, but GDScript already has examples of such abbreviations: `int` instead of `integer`, `bool` instead of `boolean`, etc.

**Comment by MyriaCore** [comment]
@vnen
> > 1. Edit [`gdscript_tokenizer.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_tokenizer.h) and [`gdscript_tokenizer.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_tokenizer.cpp)
> > so balanced angle brackets can be properly recognized by the parser as relating to vector literals
> 
> I don't think this can be done. A construct like: `if x < 2 and y > 2:` is pretty hard (if not impossible) to distinguish from a vector constructor by the tokenizer. You can get hairy stuff like: `<1 if x > 2 else 3, 4 if y < 5 else 6>` which should be a valid construct, but can't really be caught by the tokenizer. Of course, you don't really _need_ that the tokenizer care about this, it just need to emit the `LESS`/`GREATER` token and the parser should know what to do.

I think that, realistically speaking, we'd likely need to encode `<` and `>` as something like `angleL` and `angleR` in the tokenizer, and then disambiguate between `lessThan` / `greaterThan` and `openVec` / `closeVec` (or something like that) once we get to the parsing logic. I didn't mean to imply that we should be disambiguate *during the tokenizing stage*, as you're correct in thinking that that would be impossible.

> > 2. Edit [`gdscript_parser.h`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.h) and [`gdscript_parser.cpp`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.cpp) to add parsing logic that makes terms of the form `< t₁, t₂>` and `< t₁, t₂, t₃>` legal. Also, add logic to ensure that at the the `<` token relating to less-than checks and the `<` token relating to vector-literals are distinguishably distinct.
> 
> This is what worry me most. Though since the vector `<` is kind of a prefix operator and the less `<` is an infix one, it should not be hard to distinguish between both.

I'm unsure of how the gdscript parser is actually built, so I'll have to check that to make sure it unifies with my understanding of how parsing works, but to my current understanding, once we have a hypothetical parse tree of code that uses this vector syntax, disambiguating between less/greater than and vector syntax would just mean that we want `< float, float, float >` and `<int, int, int>i` to show up on a different branch of the parse tree than angle brackets relating to if statements. Strictly speaking, the grammar *should* be doable. I think for a lot of people in this thread, the big question is *should* we do it. I mean, for example, Java uses angle brackets for generics.

**Comment by MyriaCore** [comment]
@bojidar-bg:
> Consider the alternative `v(x, y)` / `v(x, y, z)`, or just `(x, y)` / `(x, y, z)`, as it almost the same length, while not changing the syntax that much.

Honestly, I'm really liking this as an alternative to the angle bracket syntax, _especially_ since there's no real tuple type in gdscript besides vectors I think.

**Comment by MyriaCore** [comment]
For those of you who are hung up on the readability of a post-vector-literals gdscript, I'd like to see if I can change your mind. 

@Calinou: 
> I tend to favor code that reads like prose, without too many abbreviations

So python is a very prose-like language, but that's not *in spite* of its support for literals, it's because the literals are very unobtrusive, and leverage clear, pre-existing intuition from other languages. The 'prose' intermingles nicely with the literals in most cases, as I think it would in gdscript, seeing as gdscript borrows a lot from python.

If this is the reason that this feature bothers you, I certainly think that the parenthetical `(v₀, v₁)` / `(v₀, v₁, v₂)` syntax, as suggested by @bojidar-bg, should be significantly more tame in this regard. Not only that, but it mirrors intuition surrounding tuple literals in many other languages as well.

@girng:
> I keep getting flashbacks of C++'s Map/Template syntax. Pair this with the static typing syntax, and gdscript is going to be really hard to read in a few years (and especially for new programmers)

Once again, if the problem here is the obtrusiveness of the angle brackets themselves, than the parenthetical syntax should suffice. The reason C++ template syntax (and Java's generics as well) feel so jarring is usually because of the lack of common intuition (not many other languages before C++ and Java used angle brackets for generic types IIRC) and because of how intrusive angle brackets are as a character, aesthetically speaking.

However, if the problem is with adding literals in general, I think there's a wider point to be made here. I really don't buy the argument that literals are this crazy difficult thing to understand and learn as a newer programmer. In fact, in my early experience programming, _especially_ in languages like python, the difficulty came from learning the semantics of programming languages, as opposed to the syntax. When I was learning languages as a kid, literals regularly seemed to simplify what I was doing, just because it gave me more of a sense of what the data my code described _really looked like_.

**Comment by vnen** [comment]
> Strictly speaking, the grammar _should_ be doable. I think for a lot of people in this thread, the big question is _should_ we do it. I mean, for example, Java uses angle brackets for generics.

The issue, as @bojidar-bg illustrated very well, is disambiguating the end of a vector literal and the use of a greater-than operator. With generics it's less of a deal because those can't happen where an expression may happen.

Using parentheses would be more feasible (still, the disambiguation only appears when the comma arrives, which makes it a bit tricky, but not really difficult).

Then the question is: will we ever add actual tuples to GDScript? Because if we do, this syntax kind of gets in the way. Though for all intents and purposes we could assume that a tuple with 2 floats is compatible with Vector2, and a tuple with 3 floats is compatible with a Vector3 (same for int versions), so syntax-wise they're like vector literals. It does allow some more weak typing to seep in, but it also makes it easier to write. And I *do* want to add tuples in GDScript.

> I think for a lot of people in this thread, the big question is _should_ we do it.

Well, I guess is often the question that remains from the proposals.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on the first post). It's too controversial to consider such a change.
