### ISSUE TITLE
Add a breakpoint list to the editor

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#3740]
### Describe the project you are working on

2D Platform

### Describe the problem or limitation you are having in your project

Currently all breakpoints are only listed for the currently open script and the 'next breakpoint' only navigates between them.

All other IDEs provide a means of navigating and listing ALL breakpoints, and some kind of simple breakpoint management.

use case 1: I wish to put breakpoints in my code  to ensure they are called and know easily when I have seen them all. So whenever I reach a breakpoint I remove it.

use case 2: I'm tracking some errors and whenever I find a potential area I put in a breakpoint. I can then see at a glance every breakpoint in the game.

use case 3: I want to remove every single breakpoint in every part of my project

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make breakpoints (and bookmarks) globally visible

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It's already there, just needs a bit of code to expand the search.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Basic breakpoint management is essential in an editor.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/959.

**Comment by Paulb23** [comment]
See also godotengine/godot/pull/53546
