### ISSUE TITLE
Make EditorQuickOpen dialog available from plugins

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#3745]
### Describe the project you are working on

plugins (gdscript)

### Describe the problem or limitation you are having in your project

I want to open a resource file from a plugin.
I would like to use something like EditorQuickOpen, this looks handy:
![dialogue](https://user-images.githubusercontent.com/16458555/147944418-bd954728-5c78-427c-8d0b-df8ac6f0717e.JPG)

But I can't get access to this class from a gdscript plugin.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Making EditorQuickOpen dialog avaliable from plugins would solve the problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The class and control already exists in Godot, but not available from a plugin.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

A workaround would be creating this dialog from scratch
- inherited from ConfirmationDialog
- a list of files would be ItemList or Tree
- a filter would be LineEdit
etc.

But this looks like reinventing the wheel.

### Is there a reason why this should be core and not an add-on in the asset library?

An addon could just add control scene (tscn) as described above.

**Comment by KoBeWi** [comment]
I devised an ultimate hacky solution that allows to use the editor's quick open:
![B87bgmIGwE](https://user-images.githubusercontent.com/2223172/200183859-fc7dfdde-140b-467c-a635-9f620b77b4bb.gif)
It involves creating hidden EditorResourcePicker and fake signal emissions. It would be impossible to come up with without knowing the source code. But it works, as you can see ¯\\\_(ツ)\_/¯

Here's some test plugin that I quickly glued together:
[editorquickopenultrahack3000.zip](https://github.com/godotengine/godot-proposals/files/9946340/editorquickopenultrahack3000.zip)

**Comment by Zylann** [comment]
There was a PR to do this, but it was closed for no reason https://github.com/godotengine/godot/pull/34292

**Comment by Rennan24** [comment]
This is an extremely useful Dialog that makes picking resources much easier. EditorFileDialog is a litte too cumbersome since it doesn't allow you to search for files and it doesn't have a flat folder heirarchy meaning you have to dig down folders to select the right file.

I think in the context of EditorPlugins this is super useful!

**Comment by nlupugla** [comment]
If we are reluctant to expose the entire dialog, we can expose it via EditorInterface. See for instance: https://github.com/godotengine/godot/pull/81655
