### ISSUE TITLE
Add an `is_zero_approx` method to `Vector2` and `Vector3`

### ISSUE THREAD

**Issue by spindlebink** [godotengine/godot-proposals#3746]
### Describe the project you are working on

FPS controller class.

### Describe the problem or limitation you are having in your project

There's an `is_zero_approx(float)` method provided globally, but it feels inconsistent not to have a similar method for the vector types.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a method `is_zero_approx()` to the `Vector2` and `Vector3` classes that calls `is_zero_approx(float)` on all members.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It's a straightforward change for consistency. The method would be implemented as a simple check on each member of a vector. Then you could call it on the vector:
```gdscript
if input_vector.is_zero_approx():
  # decelerate
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be, but it's a very minor change that seems reasonable to implement for API consistency.

### Is there a reason why this should be core and not an add-on in the asset library?

It's an extension to the core vector classes.

**Comment by Mickeon** [comment]
I suppose that if this is implemented, it would make sense to also include `Vector2.is_equal_approx(a: Vector2)` and its Vector3 equivalent?
Although both definitely *sound* useful for cutting on repetition, I'm struggling to think of particular occasions where they'd be nice to have.

**Comment by spindlebink** [comment]
There actually already is one--that's one of the reasons I figured it'd be reasonable to add the `is_zero_approx` as well. Floats get both, even though `is_zero_approx` is just marginally more convenient/readable than `is_equal_approx(num, 0.0)`. If it's already been deemed important enough to add for floats, it seems like vectors count too.

**Comment by just-like-that** [comment]
> is_equal_approx

https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-is-equal-approx

**Comment by aaronfranke** [comment]
This makes sense, and if added, there are some places in the engine we'd use it. This is entirely a question of how often this feature would be used and if it's used often enough to be worth adding.

**Comment by spindlebink** [comment]
I feel like if a numerical type exposes `is_equal_approx`, it should also expose `is_zero_approx`. It's about consistency for me. Otherwise, rather than coming up with context-specific rules for where it gets implemented and where it doesn't, it might just make sense to remove `is_zero_approx(float)` and always use the more explicit `is_equal_approx(val, 0.0)`.

I'd be willing to suffer the presence of a less than necessary `is_zero_approx` in the `Color` class if it means consistency across the board elsewhere. All or nothing would be my preference.

**Comment by Mickeon** [comment]
> it might just make sense to remove `is_zero_approx(float)` and always use the more explicit `is_equal_approx(val, 0.0)`

`is_zero_approx()` is faster and arguably more explicit. If the GDScript compiler was capable of internally optimising the `is_equal_approx()` function when a constant **0.0** is used, it may warrant removing `is_zero_approx()` and nullify this proposal.
