### ISSUE TITLE
Suggestion to make cartoon shader better . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3758]
### Describe the project you are working on

A barbarian game, 2.5D . . .

### Describe the problem or limitation you are having in your project

Uhh, I use the sort-of grow setting, in a material, to make a cel-shaded look . . It works well in ortho-perspective, bec. everything is flat, however in normal perspective, it sort of doesn't remain same size, as camera moves away . . . The problem is, in a cartoon, a line is always the same sort-of size, the size of a pencil . . . If it's in background, close to the camera, etc . . .

Is there any way one could add so, in perspective mode, the grow is sort-of proportional to, the camera distance, otherwise the line fades, sigh, for distant objects, please, help . . . !

![Skærmbillede (1)](https://user-images.githubusercontent.com/83387915/148160273-70ba9fd1-9f05-4445-8d9e-c632148d6973.png)

![Skærmbillede (2)](https://user-images.githubusercontent.com/83387915/148160285-005842d0-6058-4b84-903d-e7e6480a1591.png)

In a cartoon, the drawer only has a pencil, for near objects, distant objects, it prob. stays the same, is there any way to add this feature, maybe as a paramaters, ' lock grow to zoom ', or camera ?? Thx . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, I want neat cartoon - stuff, but right now, don't know how to make it work, in perspective mode . . Perhaps a ' lock shader to camera ', or ' lock grow to zoom ', not sure, would sort-of work . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, just hope you'll add something, so cartoon style looks as good, in perspective, similar to ortho - mode, where it currently works really well, maybe this is possible . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not sure, a feature to ' lock grow amount to perspective ' ??

### Is there a reason why this should be core and not an add-on in the asset library?

Well, I don't know, I really like cartoon - style, but it's a bit difficult to set up, not sure, if one should make a shader, or this is for the engine, etc . . . .

**Comment by fire** [comment]
I'm not sure if keeping the cartoon shader is a good idea. There are some arguments that oppose anything in Godot Engine that isn't physically based rendering.

**Comment by charlesmlamb** [comment]
Note, there is something called ' fixed size ', but it makes stuff so big, like a 2 x 2 x 2 cube, suddenly becomes 2000 x 2000 x 2000, so the next - pass shader for grow, doesn't work . . .

One needs to set it to 0.00002, to work, the engine doesn't support that low number, for some reason . .

**Comment by fire** [comment]
If people are having trouble with the standard toon shader and the tuning is obtuse because it is a niche feature suitable for the asset library.

**Comment by charlesmlamb** [comment]
Please see above, need some better settings for ' fixed size ', or grow, so I can type 0.000001 in grow, and it works, or ' fixed size ' by default is about same size, as normal objects, thx . . . .

**Comment by fire** [comment]
How is fixed sized related to toon shadingAre you referring to a outline shader?

![image](https://user-images.githubusercontent.com/32321/148161544-7da256f4-dc3e-4e45-a5e3-bda8c69b2143.png)

https://godotshaders.com/?s=outlines

**Comment by charlesmlamb** [comment]
I need the next - pass material, to be fixed size, that makes the sort-of line, around character . . .

Idea is, one makes a next pass material, grow size is 0.01, then use reverse cull mode, it sort-of creates a shell around the character, that works like an outline . 

The problem is, it's based on the mesh, so a 1 x 1 m cube, grow 0.1, adds an extra cube, that's 1.1 x 1.1 m, or so . . .

The size of cube is not dependent on distance to camera, only to size, of object it was based on . . .

One can use ' fixed size ', to make it scale, with the camera, the problem is, ' fixed ' size makes objects really big, compared to default size, in view-port, example . . .

Try making a sphere, in normal viewport, then click fixed size, it disappears . . It's gotten so big, you can't see it . . . Try and scale size, of sphere 0.1, 0.2, you can see it . . . Fixed size would work, if only there was setting, to set ' relative scale ' for, fixed size . . .

So, if a fixed size object was say, a certain size, a parameter to scale it, is what I need . . .

Here's how you make, toon - shader, the way I talk . . It uses a next - pass material, it takes 2 minutes, no need for shaders, only need setting to scale ' fixed size ', for instance to 0.1, or, 0.01, then it works . . . .

https://www.youtube.com/watch?v=ydwhZlSp9k4

Six minute video, how to make it . . Easiest cartoon shader, gives good results . . .

**Comment by Zireael07** [comment]
@charlesmlamb: What you describe (and what the majority of the vid is about) is not (car)toon, that's outline shader.

**Comment by charlesmlamb** [comment]
Uhh, I saw some videos, about how to use next - pass material, to make an outline, too complicated, too explain . . . .

Uhh, add a next - pass material, use grow, then different cull - mode and, then unshaded . . .

It works really well for orthogonal perspective, but in other perspective, it sort-of bec. smaller, with distance . . .

I was wondering, does it make sense to add a scale value to ' fixed size ', it's usually based on some object, and one has to scale that, to non - correct size, to get the look one wants or, needs . . . So, one can't have a PBR size, of an object, IF one uses fixed size, atm . . . The problem is, for outline stuff, one can't set it after one has done it, at least, in material . . .

**Comment by charlesmlamb** [comment]
Sorry, I had to scale the sphere to 10 %, then it looks normal, problem is, the original object then isn't the well correct size . . . .

**Comment by charlesmlamb** [comment]
Sorry, I might have reported it the wrong place, it looks like a bug, not sure . . . No matter how much I zoom out, it never really, is on screen . . .

![Skærmbillede (4)](https://user-images.githubusercontent.com/83387915/148312996-2b0229ce-3482-473c-8af1-3629e6cef02e.png)

I'm not sure, this is sort-of a simple feature, maybe someone could look at it, is it a bug, or how should one use it . . .

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP and general lack of activity).
