### ISSUE TITLE
GDScript: Add support for semicolon in if-statements act as concatenation (glueing mechanism)

### ISSUE THREAD

**Issue by just-like-that** [godotengine/godot-proposals#3759]
### Describe the project you are working on

A sketching-like app/program. Idea applies to any kind of program using if-statements.

### Describe the problem or limitation you are having in your project

GDScript is a structured language. 

- **That said the indentation of statements in the context of if-statements have a meaning. Everything indented is regarded to be part of the if-statement and only processed if the if-condition is met.**

- **On the other hand the semicolon is used to combine two lines in one which are usually written in two separate lines.**

Now it's possible to combine an if-statement with a semicolon.

So when I use this (case a):
```
if condition: print("condition met"); print("condition met again")
```
always outputs ```condition met again``` at minimum even if the condition is NOT met yet

instead of (case b):
```
if condition:
	print("condition met")
	print("condition met again")
```
which outputs NOTHING at all if the condition is NOT met.

**At the moment both cases act differently although they look very similar.**

Case a always prints "condition met again" regardless if the condition is met or NOT leading to a completely different logic in code. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

**Add support for "glueing mechanism" in situations where an if-statement is combined with a semicolon.**

**By doing so GDScript would process both statements on the right side (case a) only if the condition on the left side is met.** That means it acts like in the regular case (b).

You might ask why?

- As said before GDScript is a structured language. As such both statements are indented (residing on the same side). 
- It looks more natural - even for a person who has no programming experience.
- All statements on the right side are only processed if the condition on the left side is met.
- This is common behaviour in other languages like C/++ or Java, too.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
var vec := Vector2(1, -1)
var condition := true
if condition: vec.x = vec.x + 1; vec.y = vec.y - 1
```
Note: This is just meant as an example.

**In case the condition is met the one-liner increases x-axis and decreases y-axis at the same time.**

In this particular situation it's like a pattern if I increase one axis I decrease the other axis at the same time.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can - just write separate lines indented. 

I find it less intuitive that the semicolon acts like a line-break and so the structure/indentation is broken
which is usually followed by GDScript.

Both statements are on one line for a reason. Process both (all of them) if condition to the left is met.

### Is there a reason why this should be core and not an add-on in the asset library?

Can only be core. As both keywords if and ; are part of GDScript.

As this change breaks compatibility with GDScript 1.0 it makes sense to introduce this change together with Godot 4.0/GDScript 2.0.

**Comment by just-like-that** [comment]
Minimal test project:
[semicolon_test.zip](https://github.com/godotengine/godot-proposals/files/7814128/semicolon_test.zip)

**Comment by just-like-that** [comment]
Minimal test project:
[semicolon_test.zip](https://github.com/godotengine/godot-proposals/files/7814175/semicolon_test.zip)

```
extends Node

func _ready() -> void:
	var strval := ""

	for condition in [true, false]:
		print("condition is %s:" % [condition])
		if condition:
			strval = "condition met."
			strval += "condition met again."
		print("1.>%s" % strval)
		strval = ""

		if condition: strval = "condition met."; strval += "condition met again."
		print("2.>%s" % strval)
		strval = ""

		print()
	# end for

	get_tree().quit(0)
	return
```

leads to following output:

condition is True:
1.>condition met.condition met again.
2.>condition met.condition met again.

condition is False:
1.>
2.>condition met again.

**Comment by Mickeon** [comment]
Although it's really **not** recommended to concatenate instructions sideways, I suppose the proposed behaviour makes total sense.
It would be logical to apply it to most branching keywords, as well: `else`, `elif`, `for`, `while`.

**Comment by Calinou** [comment]
I think supporting one-liner `if:` statements was a mistake in the first place. It doesn't make for very readable code. For comparison, Python does not support one-liner `if:`s and people seem to be fine with it.

**Comment by Mickeon** [comment]
Seeing as
```
if condition:
	print("condition met"); print("condition met again")
```
is something that is valid, works as one would expect, and leads to more readable code, I see the reason behind removing the feature it entirely.

However, there are some occasions where some users may prefer the not-so recommended one-line `if`, for example:
```
if condition: return

while true:
    if condition: break

if condition: print("something")
else:         print("something else")
```
And, it's true, sacrificing one or two more lines for them is not that big of a deal, but it's worth noting the one-line removal could be deemed unreasonable these users through the transition.

**Comment by just-like-that** [comment]
> I think supporting one-liner `if:` statements was a mistake in the first place. It doesn't make for very readable code. For comparison, Python does not support one-liner `if:`s and most people seem to be fine with it.
> 
> If anything, I'd vouch for removing one-liner `if:` statements in 4.0 for consistency with most other statements. (For example, `func()` does not allow defining the body on the same line.)

As @Mickeon pointed out, one-liner if: statements are common practice.
It helps to tidy up code.

**Comment by just-like-that** [comment]
> I think supporting one-liner `if:` statements was a mistake in the first place. It doesn't make for very readable code. For comparison, Python does not support one-liner `if:`s and most people seem to be fine with it.
> 
> If anything, I'd vouch for removing one-liner `if:` statements in 4.0 for consistency with most other statements. (For example, `func()` does not allow defining the body on the same line.)

**Just wanted to point out this is valid GDScript:
func foo() -> void: print("hello world")**

**Comment by pycbouh** [comment]
I think this is a bug, or an oversight at least. There is no reason why this

```
if condition: print("condition met"); print("condition met again")
```

would expand into
```
if condition:
    print("condition met");
print("condition met again")
```
instead of
```
if condition:
    print("condition met");
    print("condition met again")
```

But it is very tempting to remove this kind of syntax from GDScript 2.0, because it doesn't follow the codestyle guidelines and best practices, and, as evident, isn't even behaving expectedly. So whoever used it so far would lose nothing if semicolon syntax is removed.

**Comment by cdemirer** [comment]
> This is common behaviour in other languages like C/++ or Java, too.

If you put braces, I guess that would be the case, but otherwise the `if` would only apply to the first one. 
So in a way, the current GDScript behavior with one-liner `if`s is similar to `if`s without brackets in C/C++.

---

> For comparison, Python does not support one-liner `if:`s

That doesn't seem to be the case. In fact it behaves exactly the same way as the proposed behavior.
```py
$ python
>>> if False: print('a'); print('b')
```

---

> There is no reason why this ... would expand into this ... instead of this ...

One reason I can see is the similarity to the `if` without braces in C/C++. But I agree that it would make more sense to follow Python's behavior in this case.

---

I think that the one-liner `if` is particularly useful with control flow (`return`, `break`, `continue`), so I'm against the complete removal of one-liner `if`.

---

In Python, the semicolon binds together statements into compound statements so they aren't separated into different scopes.
https://docs.python.org/3/reference/compound_stmts.html
This makes it useful beyond an optional cosmetic for the newline. So if GDScript should have the semicolon, I'd say it should at least be useful. (Or not have the semicolon at all.)

**Comment by me2beats** [comment]
> Python does not support one-liner `if:`s and most people seem to be fine with it.
@Calinou what do you mean by one-liner if?
`if 1: print(2); print(3)` is valid in Python

> `func()` does not allow defining the body on the same line.
Something like `func f(): pass`?
It's allowed in GDScript

**Comment by just-like-that** [comment]
> If anything, I'd vouch for removing one-liner `if:` statements in 4.0 for consistency with most other statements. (For example, `func()` does not allow defining the body on the same line.)

I vouch for 
A) removing the semicolon as this is more alien to GDScript. 
B) remove the support to write other statements after a semicolon
to circumvent this issue. By doing so one-liner if-statements are still possible and all the other siblings like with func or lambdas. It's all about consistency.

Closing and out as this seems to be more like a bug than a wanted feature.

**Comment by Mickeon** [comment]
> A) removing the semicolon as this is more alien to GDScript - even more so as || && is being deprecated in GDScript 2.0

Judging by the reception of [this proposal](https://github.com/godotengine/godot-proposals/issues/3763#issuecomment-1006353421) I don't believe the `&&` and `||` operators will be deprecated any time soon. Just putting it out there, as a counterpoint to outright remove concatenation.
