### ISSUE TITLE
VisualShader add Vector2 & Vector4 input/output node connections

### ISSUE THREAD

**Issue by Xyotic** [godotengine/godot-proposals#3761]
### Describe the project you are working on

3D Dungeon Keeper like game

### Describe the problem or limitation you are having in your project

Currently it isn't possible in to use Vector4 input/output node connections for expression nodes in VisualShader.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add missing Vector2/4 input/output node connections.
If you are working with vector4 you always first need to convert it into a vector3 and use two input/outputs (vec3 and one float) which is very anoying.
Same can be said for mat2 and mat3 which are also missing

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add the missing connection types to the input/output selection of the Expression node.

![grafik](https://user-images.githubusercontent.com/8405059/148265392-eb0705a4-ca23-465e-8a41-e6e6f04055bd.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There are workarounds to use a GlobalExpression node to store Vector2/Vector4 variables and use them in Expression Nodes.
But this solution would defy the reason to use VisualShader in the first place.

### Is there a reason why this should be core and not an add-on in the asset library?

Its a feature to be exprected in a visual shader editor.
Like Unity's shadergraph or Shader Forge.

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by Chaosus** [comment]
That's would be a big change to that system, initially, @reduz wanted that system to be compact and use only current types. Maybe I should work on it after 4.0 release...

**Comment by Xyotic** [comment]
To make it stay compact you could use a tree select for those types which is initally collapsed
For instance:

- Vector
  - Vector2
  - Vector3
  - Vector4
- Scalar
  - int
  - float
  - double

 and so on...

When Scalar or Vector will be selected then it could default to float or vector3

**Comment by fire** [comment]
Vector4 doesn't exist anywhere else in Godot Engine.

Common suggestions are Plane and Color.

**Comment by Xyotic** [comment]
Color could be missleading because color is usually clamped between 0 and 1...
Maybe Vector4 schould exist in the engine too... 😏

**Comment by Calinou** [comment]
> Maybe Vector4 schould exist as a struct in the engine too... smirk

This is being tracked in https://github.com/godotengine/godot-proposals/issues/629.

**Comment by Chaosus** [comment]
Part of this proposal (regarding Vector2 representation) was implemented by https://github.com/godotengine/godot/pull/57504.
