### ISSUE TITLE
Print in gdscript should show script/line number

### ISSUE THREAD

**Issue by jruiss** [godotengine/godot-proposals#3762]
### Describe the project you are working on

Just a simple game, my script folder has started to grow with multiple folders and scripts and more than less I forget where my print-statements are. Rustlang have a very nice dbg!("x = {}", x) https://stackoverflow.com/a/54431057 feature that would be very much appreciated in Godot.

### Describe the problem or limitation you are having in your project

Print statements get lost in files/great number of lines of code

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A print which in the godot output show script/line number or a debug print which does it would be a great benefit

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Godot output panel currently shows
`Godot Engine v4.0.dev.custom_build.a8a20a0e0 - https://godotengine.org
Vulkan API 1.2.182 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050
 
rolled [4, 3, 2, 3]
rolled [3, 1, 3, 2]
`

Instead it would show
``Godot Engine v4.0.dev.custom_build.a8a20a0e0 - https://godotengine.org
Vulkan API 1.2.182 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050
 
[res://Scripts/Dices.gd:14] rolled [4, 3, 2, 3]
[res://Scripts/Dices.gd:14] rolled [3, 1, 3, 2]
``

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's fundamental to the editor

### Is there a reason why this should be core and not an add-on in the asset library?

It's not possibly to make a addon without re-writing lots of core stuff

**Comment by Zireael07** [comment]
Have a feeling this was already suggested, but my git-fu is not up to snuff today...

**Comment by Calinou** [comment]
This already exists as `print_debug()`.
