### ISSUE TITLE
Sort the TileSet work area in the new TileSet editor

### ISSUE THREAD

**Issue by SoyoTamo** [godotengine/godot-proposals#3765]
### Describe the project you are working on

Just testing.

### Describe the problem or limitation you are having in your project

I don't plan on saying here how to help make it more intuitive, but I do plan on a couple of things that are wrong with regards to the layout.

![Captura de pantalla de 2022-01-05 20-40-29](https://user-images.githubusercontent.com/95949771/148313526-264efdbc-6b2f-4115-934c-f12f6fa031d9.png)

The difference in how an image looks in the image bar to a normal file is inneseary, it would be enough for all the images and / or elements of the tileset to occupy the same size, and if they are not empty, put a small one on them thumbnail, not outrageously large full image.

![Captura de pantalla de 2022-01-05 20-41-15](https://user-images.githubusercontent.com/95949771/148313849-6ff4ba4a-e464-40cf-a980-e38cd0dd2257.png)

In the editing area the tileset opens with a full column only for a small tab that at the same time is used for a very small set of options, thus leaving almost all the space, in addition to cluttered look.

![Captura de pantalla de 2022-01-05 20-18-00](https://user-images.githubusercontent.com/95949771/148314065-ede86a33-474a-4bd6-85b1-8d64363fd472.png)

Like I said, that little tab open another little tab, it doesn't make a lot of sense and you waste your time going from one to another.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose some renovations:

-Put the edit bar of the tileset to the right of it, this will help not to see everything so mixed and disproportionate.

-Put all the small options of the tileset editor in a single column (in the right, like the inspector), everything in view, more intuitive, and saving clicks, which deserves to be considered separately ordering it by tabs

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It is part of the editor

**Comment by Calinou** [comment]
cc @groud
