### ISSUE TITLE
Improve the appearance of colored buttons in the editor

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot-proposals#3768]
### Describe the project you are working on

It doesn't matter in this case.

### Describe the problem or limitation you are having in your project

When pressed, the Output Panel buttons are colored in the Accent Color, which does not look very clear, since inactive icons are brighter than active ones.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

See the mock-up.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![](https://user-images.githubusercontent.com/47700418/148426956-129f9676-09eb-4aea-9773-183cc9b54963.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's editor.

### Is there a reason why this should be core and not an add-on in the asset library?

It's editor.

**Comment by pycbouh** [comment]
Disabled and inactive are different states. Buttons there are not disabled, they are inactive. In your proposal they do look disabled, but they shouldn't. They should look like something that can be activated.

This was also already reported as an issue https://github.com/godotengine/godot/issues/56158, which it is. We can track and discuss proposed changes there, I think.
