### ISSUE TITLE
High Perf Optimization Demo, showing batch 3d object workflow from Script

### ISSUE THREAD

**Issue by jasonswearingen** [godotengine/godot-proposals#377]
**Describe the project you are working on:**
C# Async Job System for high performance.

**Describe the problem or limitation you are having in your project:**
Lack of information showing the highest performance way of creating 3d objects, moving them, and applying physics.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
A demo showing the highest possible efficiency for batch 3d object creation, movement, and physics  would be a great reference for me, and anyone else looking to write a high performance game in C# or GDScript.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

A worker thread that creates 100 cubes, moves them around randomly, and haves them bounce off of eachother.

**Describe implementation detail for your proposal (in code), if possible:**
Needs someone familiar with core features (espcially VisualServer and Physics) to make a demo.  

Care taken to verify race conditions don't occur.    Maybe this can be verified by a seperate demo where a single object moves in a pre-determined loop, and the previous position is validated in code and visually.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
not impacting.

**Is there a reason why this should be core and not an add-on in the asset library?:**
this should be in the demo repo, and a link provided in the docs.

**Comment by Calinou** [comment]
This repository is intended to be used for engine feature proposals. Please use the [godot-demo-projects](https://github.com/godotengine/godot-demo-projects) issue tracker for demo requests, or [godot-docs](https://github.com/godotengine/godot-docs) for documentation requests.
