### ISSUE TITLE
Hide Caret In Line Edit

### ISSUE THREAD

**Issue by ccuntd** [godotengine/godot-proposals#3770]
### Describe the project you are working on

Console

### Describe the problem or limitation you are having in your project

I Want to make my own caret, and now i have 2

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

hide it pls

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

make it a checkbox in the line edit caret section

### If this enhancement will not be used often, can it be worked around with a few lines of script?

not possible as far as i know

### Is there a reason why this should be core and not an add-on in the asset library?

can't be

**Comment by Mickeon** [comment]
I believe you can hide the caret by going to the LineEdit's theme properties and setting `cursor_color` 's alpha to 0, rendering it fully transparent.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/1220.

Either way, this is already possible as mentioned by @Mickeon.

**Comment by ccuntd** [comment]
ahh, right.
that worked, thanks.
