### ISSUE TITLE
Expose additional NodePaths to VisibilityEnabler (and VisibilityEnabler2D)

### ISSUE THREAD

**Issue by hunterloftis** [godotengine/godot-proposals#3781]
### Describe the project you are working on

A side-scrolling 2D game with levels that are heavily populated by NPCs with non-trivial scene trees.

### Describe the problem or limitation you are having in your project

Several VisibilityEnabler2D nodes, whose transforms and rects must be manually kept in-sync, are required in order to disable the NPCs when off-screen. For instance, take even a simple enemy scene tree such as:

- Shroom
  - Damagee
  - Animation
  - Voice
  - Facing
    - Shadow
    - Sprite
    - Blood

VisibilityEnabler2D controls its parent and siblings, so in order to comprehensively disable this enemy, two must be added:

- Shroom
  - Damagee
  - Animation
  - Voice
  - **VisibilityEnabler2D**
  - Facing
    - Shadow
    - Sprite
    - Blood
    - **VisibilityEnabler2D**

It is common to have nested trees of nodes in a scene, for things like offsets and groups that must be transformed together. Any such organization requires multiple enablers. Changes to one must be manually replicated in others, violating the DRY principle.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

VisibilityEnabler scans a single node (its parent) for nodes that can be disabled (inclusive of the parent). Here are two suggestions for how it might be simplified and DRY'd up:

1. Expose a boolean `recursive` option, such that only the top-level node would need an enabler.
2. Expose a `roots` option (an array of NodePaths), which when empty (default) will resolve to `[get_parent()]`, but which can be overridden by the user. For the example above, `[Shroom, Shroom/Facing]`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user checks `recursive`, the `VisibilityEnabler2D` will recursively walk the tree from its parent downwards, following the same rules it does today to build a list of nodes that it can disable.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure if there's an elegant way to work around this right now. None of these are particularly good:

1. Manually copying enablers throughout the tree (the simplest solution today)
2. Writing a custom FlexibleVisibilityEnabler2D that's more-or-less a clone of the implementation of the built-in one, with the ability to find nodes recursively.

### Is there a reason why this should be core and not an add-on in the asset library?

An add-on would be a re-implementation of the core functionality.

**Comment by KoBeWi** [comment]
This can be easily achieved in 4.0 using a script:
```GDScript
extends VisibleOnScreenNotifier2D

func _ready() -> void:
	screen_entered.connect(enable_parent)
	screen_exited.connect(disable_parent)

func enable_parent():
	get_parent().process_mode = Node.PROCESS_MODE_INHERIT

func disable_parent():
	get_parent().process_mode = Node.PROCESS_MODE_DISABLED
```

**Comment by hunterloftis** [comment]
Are pre-4.0 changes no longer being made? I'm using 3.4.2 since, the last time I checked, 4.0 was nowhere near stable. And in 3.x, VisibilityEnablers don't emit signals.

**Comment by KoBeWi** [comment]
New features are either added only to 4.0 or both to 4.0 and 3.x.

Also VisibilityEnablers (actually, VisibilityNotifiers) DO emit signals in Godot 3.x. But that script will only work in 4.0, because the pause system was reworked to allow pausing parts of the scene tree.

**Comment by hunterloftis** [comment]
Ah, I see. The docs for them don't mention any signals, but they inherit from notifiers.

No worries, I'll just use multiple enablers until 4.0 gets to a stable state.
