### ISSUE TITLE
get_tree().get_fps()

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#379]
**Describe the project you are working on:**
Spaceship game

**Describe the problem or limitation you are having in your project:**
I am trying to use asynchronous methods to make a flash animation but I need to know the fps so I can divide seconds into frames

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
this would help alot since godot by default doesn't have a framerate cap or if there is one its really high.
this would basicly return the setting cap is there is one and if not whatever godot uses as its base framerate

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
not needed
**Describe implementation detail for your proposal (in code), if possible:**
```
func get_fps():
	var fps = ProjectSettings.get("debug/settings/fps/force_fps")
	if (fps == 0): return internal_godot_uncapped_framerate;
	return fps
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
idk if it would be used alot but its cannot really be worked around with a script since godot may not even have a framerate cap and in this case godot would have to implement a really high one
 
**Is there a reason why this should be core and not an add-on in the asset library?:**
see above

**Comment by groud** [comment]
That's basically what the delta parameter of the `_process(delta)` function is. You just have to a compute `1/delta` to get the FPS.

**Comment by Janders1800** [comment]
You can also use `Engine.get_frames_per_second()`

**Comment by groud** [comment]
As per the comments above, the feature is already implemented.
Closing.

**Comment by Shadowblitz16** [comment]
isn't delta the frame per second and not the actual cap?
dividing by the current fps seems wrong

**Comment by groud** [comment]
Delta is the time elapsed since the previous frame. Whether or not FPS are caped or not.
So `1/delta` gives you the exact FPS, whatever the configuration is.

**Comment by Shadowblitz16** [comment]
ok I will try this thankyou. :D
