### ISSUE TITLE
Add a BaseMaterial3D property to prevent a material from receiving any reflections

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#3792]
### Describe the project you are working on

Open World

### Describe the problem or limitation you are having in your project

All materials render Reflections on them, however slight even with Roughness set to 1 and Metallic/Specular at 0

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a Disable Reflections to Shading (much like Disable Ambient) would allow for removing reflective effects when in the presence of Reflection Probes completely, instead of just partially hiding them. This is especially visible in the Vulkan Mobile Renderer.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Under Shading add "Disable Reflections" that prevents the Material from getting any type of Reflections (Background, Reflection Probe, Voxel GI, SDFGI..)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Materials are Core

**Comment by clayjohn** [comment]
Related: https://github.com/godotengine/godot/issues/40753

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4818, which is more detailed.
