### ISSUE TITLE
Remove the misleading velocity property from InputEventMouseMotion

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot-proposals#3796]
### Describe the project you are working on

A throwing game, where I use the mouse movement to control the speed and direction of the projectile.

### Describe the problem or limitation you are having in your project

The [InputEventMouseMotion](https://docs.godotengine.org/en/stable/classes/class_inputeventmousemotion.html) has a [`speed`](https://docs.godotengine.org/en/stable/classes/class_inputeventmousemotion.html#class-inputeventmousemotion-property-speed) ([`velocity`](https://github.com/godotengine/godot/pull/56322) in 4.0) property. However, the speed value has nothing to do with the event. It is calculated within the engine and only updated every 0.1&nbsp;s. It is the same value that can be retrieved using [`Input.get_last_mouse_speed()`](https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-get-last-mouse-speed) (`Input.get_last_mouse_velocity()` in 4.0). Therefore, adding this value to the event is misleading. Furthermore, the speed calculation is also inaccurate (see godotengine/godot#56764) and deliberately smoothed (by only calculating it every 0.1&nbsp;s using accumulated mouse movements).

As detailed in #552, a more useful property would be the event time. Users could then calculate their own speed, velocity and acceleration.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Remove the misleading `velocity` property from `InputEventMouseMotion` (and implement #552). If a user wants this separately calculated value they can use [`Input.get_last_mouse_speed()`](https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-get-last-mouse-speed) (`Input.get_last_mouse_velocity()` in 4.0).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See godotengine/godot#56789.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core input event code.

**Comment by Mickeon** [comment]
Not that big of a deal, but it'd be pretty nice if the `velocity` property was adjusted to work as expected, instead of outright removing it. The class is called InputEventMouse**Motion**. It sounds fairly reasonable to expect there should be information about mouse _motion_ somewhere in there.

**Comment by madmiraal** [comment]
@Mickeon I agree it would be nice. The problem is that `InputEventMouseMotion` generates events at the pixel level, which is not granular enough to calculate velocity without jitter (steps). This is why it is calculated separately within the engine using an accumulation of `InputEventMouseMotion` events over a 0.1&nbsp;s interval to low-pass filter the results. Think about how pixel art needs anti-aliasing. With #552, the user will be able to use the `relative` property, to calculate their own velocity (and acceleration, etc.) using their own intervals, but they will still need to filter it to get a realistic velocity.

**Comment by YuriSizov** [comment]
There doesn't seem to be a lot of support, or any consensus on this change, and we can no longer consider such breaking changes for Godot 4. I've closed the PR, and I'm closing this proposal as well. If there is a way to make the velocity property more useful, a PR for that is more than welcome.

**Comment by jamie-pate** [comment]
Sane behavior would be to smooth mouse inputs starting with any button press instead of random time intervals..
