### ISSUE TITLE
Add hotkeys for the editor's bottom panels [output, debugger, search results, audio, animation]

### ISSUE THREAD

**Issue by laubblaeser** [godotengine/godot-proposals#380]
**Describe the project you are working on:**

Recently started out so I don't have a project that directly relates to my proposal. In using the Godot editor, often times the output window opens automatically and has to be closed with a mouse click. This could be done quicker with the press of a hotkey. Same applies for the debugger which is needed often to view hints/error messages. A quick "open, read and close" cycle could be done with keyboard via hotkeys for it.

**Describe the problem or limitation you are having in your project:**

I often find myself in the position to have to switch between keyboard and mouse controls. This workflow for coding/testing could be smoothened by introducing keyboard hotkeys.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

Faster access to opening and closing the respective panels without having to grab the mouse.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

In my humble opinion, a mocked up screenshot would not be very helpful to better understand my proposal.

**Describe implementation detail for your proposal (in code), if possible:**

Set hotkeys "Alt + [1, 2, 3, 4, 5]" as default for opening/closing [output, debugger, search results, audio, animation]. These key combinations are easily accessible with one hand.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I do not know if others would be interested in this as well. Personally I could see myself using the feature quite often. Thus I also cannot tell if a few lines of script might fix the problem because I cannot code in C++ and don't know the inner workings of the editor.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It covers core features of the engine which are used very frequently. An add-on might fix the issue but the proposal is to include it as a core feature for reasons of fundamentality.

**Comment by Calinou** [comment]
> Set hotkeys "Alt + [1, 2, 3, 4, 5]" as default for opening/closing [output, debugger, search results, audio, animation]. These key combinations are easily accessible with one hand.

These shortcuts are currently unused, but they unfortunately won't work out of the box on non-QWERTY keyboard layouts until Godot 4.0 where physical key actions are supported.

**Comment by passivestar** [comment]
Struggling with this too, every time the output panel pops out I have to click the thing. Would be great to at least be able to toggle the whole bottom panel with a shortcut, if not individual tabs

Also a related video: distraction-free mode doesn't affect the bottom panel, and the bottom panel is... well... distracting 😅

https://github.com/godotengine/godot-proposals/assets/60579014/0326e5b6-7a8b-4d0c-ad52-73fa9e4762e1

**Comment by passivestar** [comment]
And it looks like it opens every single time I run my game, even if there are no errors? So every time I run the game I have to manually close it afterwards 🤔

**Comment by AThousandShips** [comment]
Yes, control it with `run/output/always_open_output_on_play` and `run/output/always_close_output_on_stop`

**Comment by passivestar** [comment]
@AThousandShips I just tried it and it still opened it. The debugger tab. But it only has warnings about stuff that I don't care about, like unused parameters or whatnot. Maybe there could be more control there, like  `Open [Always/Only On Errors/Errors And Warnings/Never]`?

<img width="452" alt="image" src="https://github.com/godotengine/godot-proposals/assets/60579014/2bb9354b-471f-4912-a9d3-0be0083ac0d1">

**Comment by AThousandShips** [comment]
Okay, you said the output panel so that's why I assumed you meant it, unsure about that one

**Comment by Kylemcarthur** [comment]
I also think this would be a very useful workflow improvement, and I can't find any viable alternatives.

**Comment by Calinou** [comment]
@Kylemcarthur Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Calinou** [comment]
Should the shortcut key be set based on the button's position, or the button's function?

In other words, should we use number keys for shortcuts to refer to the button's order (e.g. 3rd item in list is always <kbd>Alt + 3</kbd>, regardless of what item it actually is)? Or should each item be assigned its own key with its own shortcut, so it works even if it's been reordered for some reason?

**Comment by viksl** [comment]
I'd prefer, if there's a way to identify the panel, to have shortcuts based on which panel it is (Output/FileSystem/...), with ordered approach couldn't it end up with impossible shortcuts if someone added couple plugins which would all end up in the bottome panel (such as "alt + 12")?

Calinou: Thanks for close the other, I searched but did not notice this, my bad and thanks again :-) !).

Secondly if you don't mind, how un/realistic this is with current implementation/plans? Since a function to open these is already in would this fit into some more beginner friendly PR or do you think this is more involved toget working (I remember there's some docker rework ongoing?)?

**Comment by Calinou** [comment]
> Secondly if you don't mind, how un/realistic this is with current implementation/plans?

This turned out to be straightforward to implement, at least with "fixed" shortcuts for each bottom panel: https://github.com/godotengine/godot/pull/88081

Editor plugins can specify their own shortcuts too.

@passivestar Maybe you'd like to give the above PR a try :slightly_smiling_face:

**Comment by passivestar** [comment]
@Calinou I think it might be more practical to put the hotkeys for the regular buttons onto the top row in order of appearance:

`Alt+Q` - `Output`
`Alt+W` - `Debugger`
`Alt+E` - `Audio`
`Alt+R` - `Animation`
`Alt+T` - `Shader Editor`
etc

Because the most used one is going to be the `Output`, and `Alt+O` is practically unreachable without lifting the right hand from the mouse. I'd be remapping that first if it was on `Alt+O`

I understand why you want to make them all match the words, but there's a reason the default shortcut for Undo is `Ctrl+Z` and not `Ctrl+U` 🙂

So some compromises probably have to be made

**Comment by viksl** [comment]
One thing to check is how it interacts with pinned state which I think currently the Animation has.

**Comment by Cammymoop** [comment]
Please include a key to hide the panel regardless of which one is open. A shortcut that toggles the current/last open panel would be ideal imo.

**Comment by Calinou** [comment]
> Please include a shortcut for hiding the panel regardless of which one is open. A shortcut that toggles the last open panel would be ideal imo.

I just implemented this: https://github.com/godotengine/godot/pull/88081#issuecomment-1948944571
