### ISSUE TITLE
Custom property description 

### ISSUE THREAD

**Issue by alvinseptiano** [godotengine/godot-proposals#3802]
### Describe the project you are working on

So I have been creating my own game that i have maybe a good idea to add a custom parameter description.

### Describe the problem or limitation you are having in your project

So it come to realization that godot does not have a custom description for custom parameter. it limit the understanding of the game component to my designer friend.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Being able to see custom parameter description when you hover your cursor. just like built in one.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When user hover their cursor it show the parameter description.
![feature_proposal](https://user-images.githubusercontent.com/55371083/149630439-f3ee6e6d-2ed4-4fe5-a527-b587ee290a62.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, and that might be the only way to create one.

### Is there a reason why this should be core and not an add-on in the asset library?

Working with large amount of people especially with designer with basic knowledge of code. it safe to assume that they should be  able access the custom component and read it's description and what it do without having to access script.

**Comment by alvinseptiano** [comment]
Sorry if this a duplicate. i have search the entire github issue.

**Comment by pycbouh** [comment]
That's been implemented in 4.0 with https://github.com/godotengine/godot-proposals/issues/993.

**Comment by alvinseptiano** [comment]
didn't know that. that is a good news thanks guys
