### ISSUE TITLE
add a str2vec2 function

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot-proposals#3803]
### Describe the project you are working on

I'm working on a pseudo3D framework on Godot.

### Describe the problem or limitation you are having in your project

Well, it's not a problem at all, it actually is pretty simple. I've instanced nodes linked to coordenates and named them based on it, so I can use it later. When I do, sometimes I have to convert it back,

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As I've said, is pretty simple really and I'd made a function to convert it back, I'm proposing because it looks like a feature that is missing, since you can convert many types of variables, etc...
It would be a function that would take the string separated by comma and returns the Vector.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is the function I've used, so  it's in GDScript:

```
func str2vec2(str2convert):
	var strX = str2convert.trim_suffix(",")
	var strY = str2convert.trim_prefix(",")
	return Vector2(nX,nY)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it could.

### Is there a reason why this should be core and not an add-on in the asset library?

Because it looks like a function that could be used very often and because it would make sense to have a converter for Vector2 as well (even Vector3, maybe).

**Comment by Calinou** [comment]
> ### If this enhancement will not be used often, can it be worked around with a few lines of script?
>
> Yes, it could.

In this case, this is better suited to a function that you add to an autoloaded scrip :slightly_smiling_face:

**Comment by Xrayez** [comment]
There are [`str2var()`](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-str2var) and [`var2str()`](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-var2str ) functions for this (works for every built-in type).

**Comment by Mickeon** [comment]
I do not feel like a specific function to this is necessary to have in the Global Scope. `str2var()` already does its best to convert a **String** into a matching built-in type, and should work just fine for anything that was previously converted into **String** with `var2str()`.

**Comment by fire540** [comment]
`str2var` already exists, and if `str2vec2` were added then functions for other types would need to be added too, like `str2vec3`, `str2rect2`, `str2aabb`, etc. and that would be a lot of functions to add.

**Comment by JeffVenancius** [comment]
> There are [`str2var()`](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-str2var) and [`var2str()`](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-var2str) functions for this (works for every built-in type).

Oh, that makes sense. Thanks!
