### ISSUE TITLE
Improve "Folder already exists" error messages in the editor

### ISSUE THREAD

**Issue by duianto** [godotengine/godot-proposals#3809]
### System info
v3.4.1.stable.official [aa1b95889]
Windows 10 21H1

### Describe the project you are working on

Not project-specific.

### Describe the problem or limitation you are having in your project

The new folder name already exists message is not descriptive.
>Alert!
Please select a base directory first.

When creating a new folder, when moving a file, in the FileSystem panel,
and choose a folder name that already exists.

### Reproduction steps
In the FileSystem panel
- right-click and choose `new folder...`
- press `ok` to use the default name `new folder`
- right-click on `icon.png`
- choose `move to...`, now the `choose a directory` window opens
- select `res://`
- press the `create folder` button
- type `new folder`
- press `enter`

### Observed
This message appears:
>Alert!
Please select a base directory first.

### Expected
It should probably state that a folder with that name already exists.

### Notes
A similar issue occurs when trying to create a new folder with an existing name, in the FileSystem panel:
>Warning!
Could not create folder.

That could also be improved.
It's not clear why the folder can't be created.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

See above.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used every time someone tries to create a new folder with an existing name.

### Is there a reason why this should be core and not an add-on in the asset library?

Alert and Warning messages are probably part of the core.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/59495.
