### ISSUE TITLE
animation retarget

### ISSUE THREAD

**Issue by yuyubibibobibo** [godotengine/godot-proposals#381]
**Describe the project you are working on:**
i am working for 3d game
**Describe the problem or limitation you are having in your project:**
animation cannot retarget
**Describe how this feature / enhancement will help you overcome this problem or limitation:**
animation retarget
**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
i think it cannot
**Is there a reason why this should be core and not an add-on in the asset library?:**
because it is useful and normal 3d engine have it

**Comment by groud** [comment]
The issue template is here to be filled. Sorry, but your description isn't precise enough to be considered.
