### ISSUE TITLE
Make so NavigationMeshes can be set to only bake an area in a bounding box

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot-proposals#3811]
### Describe the project you are working on

3D Fps with a large open world

### Describe the problem or limitation you are having in your project

It's difficult to set up multiple navigation regions because a lot of times meshes overlap multiple regions. 
![image](https://user-images.githubusercontent.com/7292421/149679681-1caf1a6c-0dda-4027-a727-54d59fb52873.png)
Especially around the edges of the world:
![image](https://user-images.githubusercontent.com/7292421/149680089-795921f6-0852-4de6-bb1b-5a3fb744fbe5.png)

I can't easily do node hierarchies like the ones shown in the Navigation Server docs (https://godotengine.org/article/navigation-server-godot-4-0)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice if a NavigationRegion could have an optional bounding box, with a similar GUI to the one on the VisibilityEnabler node, that would restrict navigation mesh baking to be only inside it. For example, only bake inside this box: 
![image](https://user-images.githubusercontent.com/7292421/149680069-da95bbbc-1658-4be3-9d5d-a62eebfd127e.png)

Then it would be trivial to set up multiple NavigationRegions, set each to bake a group+children, then you could completely avoid awkward node hierarchies.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A checkbox, maybe under the 'Filter' section of a navmesh, that says 'restrict to area', when checked on an AABB box appears with corresponding settings and GUI similar to VisibilityEnabler.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This could likely be done in a hacky way with existing code in a plugin that just does a PhysicsQuery in a box area, gets all colliders in that area, adds them to a temp group, instances a NavigationMesh node, sets it to bake nodes in that group, bakes, then removes the colliders from that group.

### Is there a reason why this should be core and not an add-on in the asset library?

This would make setting up navigation regions a much easier process since you can overlap meshes across different regions.

**Comment by Killfrra** [comment]
I'm not sure about the bounding box, but imagine unifying meshes and navmeshes (they are very similar when saved) and then cutting out the necessary fragments of the navmesh using CSGBox... That's pretty much what I did today

**Comment by smix8** [comment]
@Miziziziz
We can limit the baking to an "AABB" centered around the NavigationRegion.
The "box" movement would need to happen by moving the parent region node.

As baking can happen without any NavigationRegion node involvement the limits must work for a pure NavigationMesh resource which has no transform and also ReCast positions the grid and all limits at the center when baking. While not impossible a flexible bounding box that can be moved would require a full recalculation of the entire parsed source geometry everytime the AABB is changed even a little but if it is centered it can be changed without any additional performance cost.

Would that be sufficient?
