### ISSUE TITLE
Add the ability to select an obstacle or an agent as a target

### ISSUE THREAD

**Issue by Killfrra** [godotengine/godot-proposals#3812]
### Describe the project you are working on

Simple League-of-Legends alike MOBA

### Describe the problem or limitation you are having in your project

Sometimes a character needs to chase another character, or simply approach him at a certain distance (or close), bypassing other characters as usual. RVO prevents this by initiating an evasive maneuver on approach.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Therefore, it would be useful to be able to temporarily disable avoidance for one agent in relation to another.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I suggest, along with the `set_target_location` function, implement the `set_target` function, which will accept a 2d / 3d object or agent and, if it is an agent, do not avoid it. Or `add_to_blacklist` / `remove_from blacklist` functions or something like that. In the worst case, implement through layer selection by analogy with physics.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, probably. By writing my own implementation of avoidance.

### Is there a reason why this should be core and not an add-on in the asset library?

A task, for example, chasing a player sounds very simple and can be in demand in many games, it's a pity that the engine does not provide such an opportunity "out of the box".

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/1966.
