### ISSUE TITLE
Make a button inherit Label

### ISSUE THREAD

**Issue by ccuntd** [godotengine/godot-proposals#3815]
### Describe the project you are working on

Me

### Describe the problem or limitation you are having in your project

Buttons don't have a fill text mode, and it would be shitty to maintain 2 label types instead of making the button inherit a label

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Buttons don't have a fill text mode, and it would be shitty to maintain 2 label types instead of making the button inherit a label

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Me

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Insert a label into the button

### Is there a reason why this should be core and not an add-on in the asset library?

This should make maintaining buttons and label easier

**Comment by Calinou** [comment]
BaseButton does not need to do everything labels can do – especially in the case of TextureButton which doesn't display any text in the first place. (Button inherits from BaseButton, so any inheritance done there will also affect BaseButton.)

**Comment by ccuntd** [comment]
fine, then at least a text fill mode for a button

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP).
