### ISSUE TITLE
godot padding for controls

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#382]
**Describe the project you are working on:**
spaceship game

**Describe the problem or limitation you are having in your project:**
I need to be able to set separate margins for each control in a hbox

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
basically this would make it so controls could have a padding or margin that gets taken in account when godot sizes your controls.

this would be for not just containers but Layouts as well

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
it would just be top, bottom , left and right fields

**Describe implementation detail for your proposal (in code), if possible:**
not sure how

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
this feature would probably be used quite often to make form style controls.
and no it probably couldn't be worked around without hacky solution.

**Is there a reason why this should be core and not an add-on in the asset library?:**
because godot's gui system sucks right now and this would help it out alot.

**Comment by groud** [comment]
If you need to precisely position nodes with very diverse positions, you should likely use the anchors and margins workflow instead of the containers-based one. Also, your problem might also be workarounded by using margins containers as children of your HBoxContainer.

> because godot's gui system sucks right now

Maybe you should also try to understand how the Godot GUI system works first ? You have been opening countless issue about the system without even taking the time to understand how it works. Please take this time, and instead of asking the engine to adapt to your needs, try to adapt yourself to the engine system first, so that we can start discussing improvements on a solid base.

**Comment by groud** [comment]
Though I understand the documentation is still lacking a detailed explanation of the whole GUI system, and how the two different workflow work together. I am still working on a large documentation page explaining the system in details, but it take times to write.

**Comment by lentsius-bark** [comment]
Although documentation is lacking a bit, I must say that after getting used to the Godot's GUI system I enjoy using it very much. There are only minor nitpicks here and there but overall the Control system is just great. Took me some time to learn the ins and outs but boy was it worth it.

**Comment by Shadowblitz16** [comment]
@groud I didn't realize there was a node for this. 
however I kinda feel no matter what I suggest people dislike it. even if its to improve godot.
I only open these issues because they make sense for beginners like me and to improve the usability of godot.


Its also hard to get help when we need it, and sometimes I feel like I am being ignored.

I will close this issue due to there already being a node for it.
however I still think the control node should have default support for this.

**Comment by mhilbrunner** [comment]
We appreciate the time you take to let us know about it. :)

If you need help, I found the Discord very helpful, and always feel free to open issues on the docs repo or let us know in the `#documentation` Discord channel if something is unclear on the docs.

Again, thanks for your time!
