### ISSUE TITLE
C#: Change RefCounted lifetime management (new Ref<T> container)

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot-proposals#3820]
This proposal evaluates the possibility of changing the way we manage lifetime of `RefCounted` instances in C#.

## How `RefCounted` lifetime works in C#

The lifetime of a managed Godot object instance is tied to that of the native instance it's attached to. As long as the native instance stays alive, so should the managed one.

The native instance holds a strong managed reference in order to prevent the GC from collecting it prematurely:

```
native --- (strong ref) --> managed
```

When the native instance is freed, it calls `Dispose()` on the managed instance and releases the strong reference.

This works because the lifetime management of native instances is either manual (`free`/`queue_free`) or delegated to the parent/child relationship of `Node`'s.

This is different when it comes to `RefCounted` instances, which use automatic reference counting. If we were to handle their lifetime the same way as other types, we would find that often the object ends up being freed prematurely:

```cs
// Note: Resource inherits RefCounted
// If this resource isn't referenced anywhere else in native code, by the time `GD.Load` returns, the ref-count has
// reached 0. As such, the native instance has been freed (and consequently, the managed instance, disposed).
Resource res = GD.Load("...");
// The next line throws an `ObjectDisposedException`
Console.WriteLine(res.ResourcePath);
```

In order to prevent that, the managed instance must keep a strong native reference. That is, to increment the reference count on creation and decrement it when garbage collected or manually disposed (`Dispose()`).

However, again, we don't want the managed instance to be prematurely collected either, as its lifetime must be tied to that of the native instance. There can be other references in native code keeping it alive, and it could eventually end up back in managed code.

What we have is a circular reference:

```
native  --- (strong ref) --> managed
managed <-- (strong ref) --- native
```

We solved this by adding hooks to the reference count operations. When the ref-count reaches `1`, there are no references in native code (remember the managed instance count as `1`). When this happens, the native instance must release the strong managed reference, thus allowing the garbage collector to handle the lifetime. If the reference count is incremented once again, we switch back to a strong reference:

```
if refcount > 1
native --- (strong ref) --> managed
native <-- (strong ref) --- managed

if refcount == 1
native --- (weak ref) --> managed
native <-- (strong ref) --- managed
```

# Why should this change?

The current solution has the following problems:

- Non-deterministic collection. The current approach ultimately leaves it up to the garbage collector to take care of the lifetime. We can't determine when an object will be collected once it becomes available for garbage collection.
  We have received several issue reports of object leaks where, after testing, we concluded there were no leaks, just objects waiting to be collected for an indefinite amount of time. This causes confusion in users that see the instances count increasing in the Godot profiler monitor, and never (in reality, just "not yet") decrementing.
  You can call `Dispose()` manually, but this is only a good idea when you know you're the last once holding a reference. Otherwise, you can be prematurely disposing it.
- Performance hit. It needs callbacks that are called every time the reference count changes.
- There's actually a multithreaded scenario in which a managed instance can end up being collected prematurely.
  This can happen when a resource is no longer referenced and is being garbage collected but, before the finalizer has a chance to free the native instance, another thread acquires the same resource from a call to `GD/ResourceLoader.Load`.
  In this scenario, the native instance stays alive as it's once again being referenced in code, but the managed instance has been garbage collected. If the instance is needed once again in managed code, [a new managed instance will be created](https://github.com/godotengine/godot/blob/846c14eee9bad75f31df94f7072331e85d24cff5/modules/mono/csharp_script.cpp#L2051-L2059).
- The strong-to-weak solution works as long as there's only one GC language relying on it.
  What if, in addition to C#, there's also a Python script holding the same `RefCounted` instance. In this case the ref-count will never be lower than `2`, the native-to-managed reference will remain strong, and the managed object will not become available for collection in neither of the two languages.
  In order to support this scenario, we would need a separate ref-count for GC language references.

# The `Ref<T>` alternative

The proposed alternative is to do reference counting via a `Ref<T>` container, similarly to how it's done in native engine code and some language bindings, like [godot-d](https://github.com/godot-d/godot-d/blob/e82608b55ba60ac69e4f5dae8535f60b7425bb85/src/godot/d/reference.d#L10-L11) and [godot-cpp](https://github.com/godotengine/godot-cpp/blob/dfa395c5ed8d075102bb116cef53ca494379e093/include/godot_cpp/classes/ref.hpp#L44-L49).

This would solve all the problems I just mentioned. In addition, it would considerably simplify internal code that deals `RefCounted` lifetime management.
However, due to the nature of the C# language, a `Ref<T>` container cannot be as easy to use and error-averse as in C++ or D.
C# lacks 3 important features for us here:

1. Member dispatch/forwarding. Accessing the target members directly from the container, e.g.: `ref.Foo()` vs `ref.Target.Foo()`.
  This is done by overloading [`operator->` in C++](https://github.com/godotengine/godot-cpp/blob/dfa395c5ed8d075102bb116cef53ca494379e093/include/godot_cpp/classes/ref.hpp#L99-L101), and [`alias this` in D](https://github.com/godot-d/godot-d/blob/e82608b55ba60ac69e4f5dae8535f60b7425bb85/src/godot/d/reference.d#L41).
2. RAII. You have to use `using` directives. A bit more verbose, and the coder may forget to do so.
3. Copy constructors. A serious problem if `Ref<T>` is going to be a struct, as you shouldn't copy it without incrementing the reference count.
  Also, creating a valid incrementing copy requires a method call (e.g.: `ref.NewRef()`) compared to it being implicit in other languages.

Lack of **1.** will result in code needing to access the actual `RefCounted` instance via the `Target` property. It's an increase in verbosity and will require more typing, but I know no other way.

For **2.**, we will need to create analyzers that ensure `Ref<T>` are disposed properly.

**3.** is only relevant if `Ref<T>` is a struct. In that case, we will need analyzers to make sure no copies of the struct are created, other than the one created by `NewRef()`. Tricky, but there are existing ones we could learn from.

## `Ref<T>` as a struct

The previous part should make it clear what the challenges are for `Ref<T>` as a struct. Those should be solvable with, but there are other concerns:

- A `Ref<T>` stored in a field must be disposed by the owner class. Analyzers should be able to enforce that. However, it's not possible to ensure the owner itself is disposed. The owner may be a class and get garbage collected, but managed code disposal is not possible when `Dispose(bool disposing)` is called by the finalizer (`disposing` is `false`, only native code can be released in this case).
- I haven't yet studied what the consequences of a "no-copy" analyzer would be when it comes to boxing, state machines, closure captured locals.

## `Ref<T>` as a class

- Classes don't have the copy problem structs do, as they are passed by reference.
- Classes don't have the copy problem structs do, but that doesn't prevent the reference from being assigned to two different owners by mistake, when a valid incrementing copy should have been made. In this case, one of the owners will likely end up with an `ObjectDisposeException` when the other owner is done with it.
- The previous issue is actually very likely to occur in the real world. Method arguments are meant to be owned by the caller, not the callee, yet it's not wrong to expect users will make the reference escape lexical scope.
  We would need an analyzer to prevent this and suggest making a copy instead.
- A class prevents leaks when you forget to dispose (`using`/`Dispose()`), as the GC can collect it. **However,** forgetting to dispose and leaving it to the GC will result in non-deterministic release of the reference, which ideally we want to avoid.
- Class allocation increase GC pressure. This is important to keep in mind if we're going to create a lot of them.

## Code before and after

These are just some examples of how code could look like after the switch to `Ref<T>`. The code here should be apply whether the container is a struct or a class:

```cs
// before
public void Foo(Resource res)
    => resField = res;

// after
public void Foo(Ref<Resource> res)
    => resField = res.NewRef();
```

```cs
// before
var tex = (Texture)GD.Load("...");
UseTexture(tex);

// after
using var tex = (Ref<Texture>)GD.Load("...");
UseTexture(tex);
```

```cs
// before
_ = tex.GetData();

// after
_ = tex.Target.GetData();
```

```cs
// before
using var _ = new Sprite()
{
    Centered = true
};

// after
using var _ = new Ref(new Sprite()
{
    Centered = true
});
// I haven't thought deal with the initial ref-count before being wrapped by the Ref<Sprite>
// but we should aim to support this to benefit from syntax sugar like object initializers.
```

As you can see, the language makes it difficult to implement this in a way that's as intuitive as it would be in some other languages, the best option still seems more error-prone than desired, and it increases verbosity. However, the gains still make it worth considering.

I want to know what others think of this. Is it too annoying to write `.Target` each time you need to access a member? Or `NewRef()` each time you need a copy? Does the increase in verbosity make you worry about readability? Please, share your opinion or feedback.
Also, please let me know if there's any language feature I missed that could help with containers like this.

**Comment by paulloz** [comment]
My two cents, even though I am not entirely confident in my ability to talk about memory management concerns in C#.  

For starters, I definitely have seen a fair amount of reports regarding objects not being GC'd and "leaks" (which... they aren't but oh well), both on and off the issue tracker. It undoubtedly needs to be addressed in a way or another. And the proposed solution sounds (at least to my ears) technically fine, and more manageable than the current codebase dealing with `RefCounted`.

Having said that, I share a lot of concerns with @derkork's message about the syntax issues.  
I tend to agree that developers using the API shouldn't have to think about the reference management of objects as mundane as (e.g.) a `Resource`.  
C# limitations you highlight in the proposition end up creating a more brittle API. Even circumvented with clever analyzers, the need for a `.NewRef()` call in itself is imho a red flag. I could personally could get over the `.Target` thing, although I'm pretty sure it is something that'll annoy a majority of people.  
All in all, a few non-idiomatic syntaxes makes the whole thing look like a big band-aid, even though it fixes a very real issue.

**Comment by neikeq** [comment]
> P.S. Hate to be the "here's what I think isn't good, but I don't have any better proposal" kind of person here.

Funny, that's me when writing this proposal 😅 I began writing this with optimism, but the more it progressed the worst it felt.

Still I like to have on record what our problems are with RefCounted and why we can't solve them.

**Comment by neikeq** [comment]
One crazy idea is to edit the generated IL post compilation (with something like Fody) to insert ref-count increments and decrements. This may be possible.
It would be an optional optimization that requires no API changes.

**Comment by paulloz** [comment]
I was actually thinking about IL weaving earlier when writing my comment. I have no real experience in it though, so I don't know how complex it'd be to go that way.

**Comment by neikeq** [comment]
The challenge with that would be how to deal with it when the reference is stored in a field/property of a non-disposable type. In that case we don't have a way to decrement it and it's back to the GC.

**Comment by neikeq** [comment]
> The challenge with that would be how to deal with it when the reference is stored in a field/property of a non-disposable type. In that case we don't have a way to decrement it and it's back to the GC.

That being said, I think most code out there doesn't store RefCounted outside Godot objects, so this would still be a big win.

**Comment by derkork** [comment]
I've been thinking over this quite a while and have realized that I have not the full picture yet. Specifically this part is puzzling me, so I hope some more knowledgeable person could explain this to me:

> Also, creating a valid incrementing copy requires a method call (e.g.: ref.NewRef()) compared to it being implicit in other languages.

How does this work in other languages? I can see how counting up works by say overloading the assignment operator. But how can counting down be implicit when you have no garbage collector triggering this for you?

**Comment by neikeq** [comment]
The destructor takes care of decrementing the ref-count back. It's called when a copy goes out of scope.
The compiler does this by either surrounding the scope with try/finally or by inserting the destructor call on each scope exit point.
It's as if the `using` directive in C# was implicitly added to each copy of a `IDisposable` value.
This is known as RAII.
When used together with copy constructors and assignment overload, it allows things like shared ownership (`Ref`/`shared_ptr`), which has the benefit of deterministic destruction and no GC overhead (ref-counting adds its own overhead that can be considered worse depending on the scenario). They can't detect circular references like the GC though, hence the need for weak refs.
As seen in this proposal, there's no practical way in C# to have shared resources with deterministic disposal.

**Comment by andy-noisyduck** [comment]
When anyone new asks for help on some part of the Godot C# API, I normally respond with "It's the same as GDScript, but it's PascalCase". This is very useful for people getting started. Whilst there are already a small number of exceptions to this "rule", I would be hesitant of any change which resulted a large number of Godot types having different usage (e.g.. `.Target`). Having behaviour close to GDScript is, at least in my view, something that we should value.

(I also don't have any better ideas though)

**Comment by neikeq** [comment]
Closing as the change is clearly not desired, and the language doesn't allow any better way to do this. The other options we discussed are also not very convincing.
