### ISSUE TITLE
Animationplayer: bezier curve from arbitrary positions(etc.) into animation's first positions

### ISSUE THREAD

**Issue by WeirdosKlamber** [godotengine/godot-proposals#3828]
### Describe the project you are working on

Action/sport game, main character has 50+nodes

### Describe the problem or limitation you are having in your project

When playing an animation at the end of a level, all the character's nodes, which move around in-game, would have to 'jump' into position for the animation to begin.
It would be nice if they could transition into the start of the animation smoothly 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Suggest that if the the first keys on a track are not at time 0 then there is an option to have a bezier curve from the node's existing arbitrary position(etc.) at time 0 into that specified at the first key on the track

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

func animtrans(anim):

	for trax in $"AnimationPlayer".get_animation(anim).get_track_count():		
		animvar1=$"AnimationPlayer".get_animation(anim).track_get_path(trax)
		animvar2=get_node(str(animvar1).split(":")[0])
					
		if str(animvar1).split(":")[1]=="position":
			$"AnimationPlayer".get_animation(anim).track_insert_key(trax,0.1,animvar2.position,1)
		if str(animvar1).split(":")[1]=="rotation_degrees":
			$"AnimationPlayer".get_animation(anim).track_insert_key(trax,0.1,animvar2.rotation_degrees,1)
	$"AnimationPlayer".play(anim)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes but I think it would be a worthwhile GUI option, probably would be used often

### Is there a reason why this should be core and not an add-on in the asset library?

Too simple to work around it with code compared to downloading the add-on, too useful to have to write the code

**Comment by Calinou** [comment]
Isn't this what the Capture mode achieves on each track?

**Comment by WeirdosKlamber** [comment]
Ah yes it probably is (did not understand that in the documentation)

**Comment by Calinou** [comment]
There is the question of whether we should default to Capture mode, but this would break compatibility with existing projects.
