### ISSUE TITLE
Add an OS method to return the size of the current system mouse cursor

### ISSUE THREAD

**Issue by just-like-that** [godotengine/godot-proposals#3842]
### Describe the project you are working on

A drawing program.

### Describe the problem or limitation you are having in your project

In my drawing program I want to show the user some useful information like mouse position, ... right beside the mouse cursor hence NOT at the tip of the cursor. I'm using the system cursor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By knowing the size of the current system mouse cursor I may align the text output - could also be another node - exactly where I want it to be.
At the moment I use a hard-coded value of Vector2(16, 16) which might work on some systems and not on others.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In Singleton Input add method get_current_cursor_size() which returns the currently assigned cursor size as Vector2.
```
● Vector2 get_current_cursor_size() const
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A. Knowledge of the underlying host system is needed. The proposal is mainly about the system cursor. 
For custom cursors the size is usually known although it'd be handy if this method also returns the size for custom mouse cursors.

### Is there a reason why this should be core and not an add-on in the asset library?

Singleton Input already returns similar data from the host system.
● CursorShape get_current_cursor_shape() const

**Comment by Calinou** [comment]
There is no standard API for changing the mouse cursor *size*. You need to load your own custom mouse cursor with the desired size instead. (Note that on hiDPI displays, you will need to load an even larger custom mouse cursor for it to have the same physical size as it would have on a low-DPI display.)

**Comment by just-like-that** [comment]
@Calinou thank you for your answer. I understand the solution.  

I like to write programs which are self-contained and adapt themselves to their environment without any user interaction if possible.

I understand that it is difficult and expensive to offer such functionality just for this particular case as you also would have to consider different OSs.
For example for Windows maybe like so:
[[GetSystemMetrics](https://stackoverflow.com/questions/63287678/extract-cursor-size-via-winapi-windows-10)]

Therefore I have another idea as retrieving registry info might not always deliver the exact size as cursors tend to have transparent areas, too.

My next approach: making a screenshot of an empty canvas with the system cursor included and analyzing the content of the area where the cursor is residing.
Yet I didn't manage a screenshot of a viewport in Godot WITH the cursor image on it.

Is there a way/do you know a way how to make a screenshot of the actual viewport including the OSs system cursor?

**Comment by Calinou** [comment]
> @Calinou :
Is there a way/do you know a way how to make a screenshot of the actual viewport including the OSs system cursor?
I did what was recommended in the official screenshot demo with the cactus. The cursor is missing on the screenshot.

This is not possible without using system APIs to take a screenshot of the entire screen, then crop it to the window area.

**Comment by bruvzg** [comment]
> GetSystemMetrics

`GetSystemMetrics` won't give you a real cursor size, but it seems to be possible to get actual cursor size, see https://devblogs.microsoft.com/oldnewthing/20210820-00/?p=105593

On macOS, you can get base cursor size from the `NSCursor` and cursor scale from the accessibility settings:

```obj-c
	NSDictionary *dict = [[NSUserDefaults standardUserDefaults] persistentDomainForName:@"com.apple.universalaccess"];
	float cur_scale = [dict[@"mouseDriverCursorSize"] floatValue]; // returns 1.0 to 4.0
	NSSize cur_size = [[[NSCursor currentSystemCursor] image] size];
```

**Comment by just-like-that** [comment]
@vnen @bruvzg thank you for your inputs. it was helpful.
