### ISSUE TITLE
Add color options for script comments

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot-proposals#3845]
### Describe the project you are working on

I'm pulling strings from a few of my .gd files via regex to feed into my database manager so that I can reference functions and some relevant data surrounding the function.

simplified example:
```gdscript

#i would pull this string via regex to create a table structure (interpreted by my database manager) that allows me to fill all the parameters needed within param_dict for the ABC function:
#it's desirable to have this data be right here because if I make any changes to the ABC function's required params, I don't have to go into my database manager to edit this data and can just do it from here.

#$param_dict_input_structure: #<Bool Col>:B , <Int Col>: I

func ABC(param_dict):
    pass #...
```

### Describe the problem or limitation you are having in your project

It's hard to distinguish one comment from another and if certain comments are being used as scripts by another it's hard to show that these lines of comments are being used for something as script.

I'm going to be using multi-line comments like this: `"""..."""` since they are a distinct color from hashtag columns.
BUT WHY DO THEY LOOK LIKE STRINGS!? (or the same color as strings to be precise)

They are comments, not strings, so why make it look like a string?

_Edit: Turns out these ARE actually strings and I've been scammed into thinking they weren't._

So either option I have to try and make these comments stand out from other comments and from my code aren't too great.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A way to color comments would help.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

They'd work something like an additional character that functions as a marker for what color the comment is:
```
#! = Red
#!@ = Yellow
#@ = Green
#@# = Cyan
## = Blue
#!# = Purple

// and these combinations would apply to multi-line comments by putting the one or two characters after the triple quotations.
// like so:
"""!  Red  """
//Or add key shortcuts for adding these color symbols to selected lines if a real multi-line comment isn't feasible.

```
Make these colors faded/low-opacity colors to have them still be identifiable as comments that are distinguishable from code.
Maybe also leave the #!@ symbols grey to show that they aren't part of the comment.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's a quality of life feature that could be used to distinguish comments it is more pertinent to the way I happen to be using comments but I don't see why it it wouldn't be used to say: make the header summary of a script stand out, or if you have a really long script, you could use these colored comments to make distinct sections of that script more easily identifiable.

### Is there a reason why this should be core and not an add-on in the asset library?

it likely cannot be made for the asset library.

**Comment by Mickeon** [comment]
> BUT WHY DO THEY LOOK LIKE STRINGS!? (or the same color as strings to be precise)
> They are comments, not strings, so why make it look like a string?

Because they're not comments. They are, indeed, Strings. Multi-line Strings that are not assigned to anything and due of GDScript's internals, they qualify as valid syntax.

```
var a = "something"
a
"this string is floating in code"
```
Is normally valid syntax, but those lines are actually processed.

**Comment by KnightNine** [comment]
@Mickeon 
Oh darn, nvm, thought triple quotations were a special syntax for a multi-line comment.
GDscript just doesn't care for free floating strings.

Maybe the multiline comment needs to actually exist for gdscript or make GDscript identify triple quotations as a multi-line comment and grey it out.

Or do what C# does and  `#*    multi-line comment    *#`...

**Comment by pycbouh** [comment]
I don't think there are any other programming tools that allow coloring comments, so that's a very unusual request for the medium. Besides, introducing special syntax just for color means it will be impossible to use it for some meta comments (e.g. we now use double hash for built-in documentation support).

On a flip side, you should be able to make a plugin in 4.0, or even with 3.4.1 and later. A plugin would need to parse syntax to find interesting parts, and can then draw over the text editor to modulate the text.

**Comment by Calinou** [comment]
I've seen some editors that use different colors for documentation comments (as opposed to inline comments), but that's about it.

**Comment by Mickeon** [comment]
There are a few "TODO" plugins such as [this](https://godotengine.org/asset-library/asset/768) in the Asset Library you could add to your project that recognise some keywords in comments (even custom ones), allowing for more easily displaying important messages on a project scale.

Other than that, the ability to colour comments would lead into scripts turning into confusing, rainbow soup, rendering comments much more intrusive that they should ever be.

Not that GDScript would ever incorporate it with an arbitrary syntax of symbols mapped to each colour.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4942, which has received more community support.
