### ISSUE TITLE
Scroll to newly set `current_tab` in TabContainer and Tabs

### ISSUE THREAD

**Issue by MartinAppDev** [godotengine/godot-proposals#3846]
### Describe the project you are working on

Game with controller support

### Describe the problem or limitation you are having in your project

If there is more tabs than can be seen at once, setting current_tab should make the tab visible.
Currently there is no way to make tabs scroll to right and left with code, like you can do with increment and decrement buttons. This makes it impossible to properly implement controller support to tabs if there are more tabs than can be shown at once.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like the behavior to be similar like the one in for example Firefox.

In Firefox:

https://user-images.githubusercontent.com/590170/150645355-5dde7556-da81-462b-bbb3-a6e0f79f65d9.mp4

In Godot currently:

https://user-images.githubusercontent.com/590170/150645362-ad018ff0-0dff-4646-8a7f-b0bd2069cc15.mp4

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

TabContainer and Tabs should have a new property to set the feature on and off.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think there is a way.

### Is there a reason why this should be core and not an add-on in the asset library?

I think it is a good UI usability feature for the editor and games.

**Comment by Calinou** [comment]
cc @YeldhamDev

**Comment by YeldhamDev** [comment]
Once https://github.com/godotengine/godot/pull/56970 is merged, this option will be available for `TabBar`, and since the plan is to integrate it in `TabContainer`, an option there will also be available.
