### ISSUE TITLE
Make EditorInspector follow focus when navigating with keyboard

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot-proposals#3852]
### Describe the problem or limitation you are having in your project

when i open ProjectSettings or EditorSettings, there's an EditorInspector node, clear with yellow in the image, when you select any property and you edit , it becomes focused for keyboard input, when you press tab button to focus next property the ScrollContainer->EditorInspector don't follow focus when this property is out of the visible area of the container!! so it should always focus the property that is active to see it !! do you need more information ?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

<H4 align=center>

I know it could be done with an `EditorPlugin`, but it's enabled already in other Editor `ScrollContainers` derived nodes so i think it should be enabled in `EditorInspector` class too.

</H4>

#

![Screenshot from 2022-01-24 15-56-30](https://user-images.githubusercontent.com/53877170/150797491-f2c19b19-e228-48c2-a383-d4a06b88a46a.png)
 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
tool
class_name EditorInspector
extends ScrollContainer


func _init():
    follow_focus = true
    # thank you!
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

..

### Is there a reason why this should be core and not an add-on in the asset library?

i will leave the answer for you !

**Comment by AnidemDex** [comment]
This proposal needs more information.

**Comment by pycbouh** [comment]
Agreed, this proposal doesn't provide enough information for discussion and doesn't answer the main questions provided by template. Please, do follow the template and try to explain the limitation that you are facing and what solution you propose to overcome it.

I will close the proposal for the time being to indicate that this proposal is not ready for discussion. Please, comment when you've updated it so I can reopen it.

**Comment by WhalesState** [comment]
@pycbouh edited !

**Comment by WhalesState** [comment]
@AnidemDex sorry but this may appear useless for you but not for godot users since we live with GodotEditor for years while learning and making games, we are not smart as you to use GodotEngine without GUI ! thanks in advance.

**Comment by pycbouh** [comment]
> @pycbouh edited !

Thanks, I think I can see what the problem is now. This is more of a bug than a proposal material, but it's okay, we can work with that.

**Comment by WhalesState** [comment]
@pycbouh i wanted to open a bug but it asked me for more information like my OS and my project and this bug exist in every project and every OS so i saw the Questions here are simpler to describe this issue. thanks in advance ^^

**Comment by AnidemDex** [comment]
@WhalesState Sorry, I misunderstood the proposal (basically, because wasn't clear what the proposal was). As pycbouh says, this is more a bug than a proposal _but_ maybe the follow focus/add focusable part was disabled on purpose for _reasons_ and this serves as a proposal to enable it again.

Maybe there's a hint somewhere here? https://github.com/godotengine/godot/blob/master/editor/editor_settings.cpp

**Comment by WhalesState** [comment]
@AnidemDex i'm not a CPP programmer but it can be easily fixed by a single line which enables the `ScrollContainer` follow_focus on the `EditorInspector` node initialize , maybe from here
https://github.com/godotengine/godot/blob/master/editor/editor_inspector.h

**Comment by AnidemDex** [comment]
Yeah, you're right.
EditorInspector extends from ScrollContainer:

https://github.com/godotengine/godot/blob/b25c7fef04499a7bee2333184bd7e5879d304eee/editor/editor_inspector.h#L405

but on its constructor is never enabled the follow focus property:

https://github.com/godotengine/godot/blob/b25c7fef04499a7bee2333184bd7e5879d304eee/editor/editor_inspector.cpp#L3554

They "scroll" it manually instead:

https://github.com/godotengine/godot/blob/b25c7fef04499a7bee2333184bd7e5879d304eee/editor/editor_inspector.cpp#L3554
https://github.com/godotengine/godot/blob/b25c7fef04499a7bee2333184bd7e5879d304eee/editor/editor_inspector.cpp#L3362

**Comment by WhalesState** [comment]
> @WhalesState Sorry, I misunderstood the proposal (basically, because wasn't clear what the proposal was). As pycbouh says, this is more a bug than a proposal _but_ maybe the follow focus/add focusable part was disabled on purpose for _reasons_ and this serves as a proposal to enable it again.
> 
> Maybe there's a hint somewhere here? https://github.com/godotengine/godot/blob/master/editor/editor_settings.cpp

no i think it's not disabled for a reason, it's the default value of follow_focus in the `ScrollContainer` Class and for a reason they have made the enable as an option maybe because it will be mainly used as a `Viewport` scroll container, it's tricky, you need to remember that it's disabled by default whenever you derive a class from it so you decide if you need it enabled or not.

**Comment by WhalesState** [comment]
> Yeah, you're right. EditorInspector extends from ScrollContainer:
> 
> https://github.com/godotengine/godot/blob/b25c7fef04499a7bee2333184bd7e5879d304eee/editor/editor_inspector.h#L405
> 
> but on its constructor is never enabled the follow focus property:
> 
> https://github.com/godotengine/godot/blob/b25c7fef04499a7bee2333184bd7e5879d304eee/editor/editor_inspector.cpp#L3554
> 
> They "scroll" it manually instead:
> 
> https://github.com/godotengine/godot/blob/b25c7fef04499a7bee2333184bd7e5879d304eee/editor/editor_inspector.cpp#L3554 https://github.com/godotengine/godot/blob/b25c7fef04499a7bee2333184bd7e5879d304eee/editor/editor_inspector.cpp#L3362
> 
> _Edit: huh, no idea why there are no code preview_

i dunno but maybe it's old related stuff since the EditorInspector class is as old as `Godot` i don't see a reason to keep scrolling the EditorInspector manually while we have an option to follow_focus in the parent class, you may need to ask someone with more experience than me if it will be ok to enable it on initialize and to remove the manually scroll option because it can be done with the `ScrollContainer` properties, it's like a duplicate of an existing feature

**Comment by AnidemDex** [comment]
Now that I point that on my previous comment, EditorInspector dock is not able to scroll properties using `ui_focus_[next|prev]`

**Comment by WhalesState** [comment]
> Now that I point that on my previous comment, EditorInspector dock is not able to scroll properties using `ui_focus_[next|prev]`

maybe it can't because the `ScrollContainer.follow_focus` is = false in the parent class, try to set it enabled while initializing the `EditorInspector` and check again if `ui_focus_[next|perv]` will work

**Comment by WhalesState** [comment]
@pycbouh can you please open an issue in the main branch bugs section and close this one as a duplicate? it will be better if it's added as a bug in the main branch so it becomes noticeable in godot 4 too, thanks in advance.
