### ISSUE TITLE
Disable and re-enable EditorPlugins when saving

### ISSUE THREAD

**Issue by rossunger** [godotengine/godot-proposals#3856]
### Describe the project you are working on

An EditorPlugin

### Describe the problem or limitation you are having in your project

Sometimes when you save the project, and there's problems with the code, the editor crashes or certain contols get stuck where they shouldn't... or when you disable the plugin, it's lost references to it's controls and when you re-enable it it adds a second version of the control. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I have a few thoughts about possible solutions:
1) Have a EditorPlugin setting that marks it as "in development" and have the editor treat those plugins differently
2) When saving, have the editor disable the plugin, perform the save, and re-enable the plugin... or at least the option for it to behave this way
3) Have an editor debug mode that allows you to see the editor's scene tree, so you can manually delete stray nodes. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1) Settings in the plugin config file

2) 
Disable Plugin
Project save
Enable plugin

3) A second scene tree (kinda like the "remote" option) that displays the editor's scene tree... and maybe a property inspector too?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The work around is to restart the editor every time something goes wrong (which is frequently when working on tools scripts and plugins)

### Is there a reason why this should be core and not an add-on in the asset library?

EditorPlugins are engine core?

**Comment by rossunger** [comment]
Or does it do this already? am I just forgetting to free() some objects?

**Comment by pycbouh** [comment]
It’s the scripts hot-reloading that cause the issues. It’s not as simple as just disable, save, enable (and even that is not simple in itself). See https://github.com/godotengine/godot-proposals/issues/1659 which discusses this issue.
