### ISSUE TITLE
Add a project upgrade tool for Godot 4.0

### ISSUE THREAD

**Issue by BenjaminNavarro** [godotengine/godot-proposals#387]
**Describe the project you are working on:**
I mostly make games on the side for fun using Godot 3.x but I follow its development quite closely.

**Describe the problem or limitation you are having in your project:**
When Godot 4.0 is released I would like to easily be able to switch to the new version with my current 3.x projects.

But being a major release, some parts of the API will change, as outlined in this [issue](https://github.com/godotengine/godot/issues/16863). This can make the transition phase a bit tedious if it has to be done manually.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Since the mapping between the old names and the new ones is known the project imported can probably be modified to upgrade 3.x projects to be 4.0 compatible automatically. If some parts of the project cannot be upgraded automatically (e.g. removed feature) they should be clearly listed along with some guidelines on how to deal with these issues.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
It's a bit early for this, but I can make one once I know if it's theoretically possible to do it and what would be the best solution for it.

**Describe implementation detail for your proposal (in code), if possible:**
Again, too early

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It probably can't.

**Is there a reason why this should be core and not an add-on in the asset library?:**
So that current users can migrate to 4.0 as smoothly as possible. If it's separated from the editor, most people probably won't know about it and struggle to upgrade their projects.

**Comment by Boivin92** [comment]
I love this idea but I think it should be a separate tool, not integrated to the editor. The main reason being that once 4.0 is a few months old, this feature would instantly be deprecated.

We could still make the tool easy to find on the website, maybe a subsection of the "Download" page

**Comment by BenjaminNavarro** [comment]
Well, I would say that it mainly depends on the impact of the feature on the editor. Meaning that if it's small enough and doesn't bother anyone we might just leave it in the editor/project manager. And that's what most software do, including Unity (don't know much about other game engines).

That way, even if people start with 4.0 but want to import some 3.x demo project found online, it can be done seamlessly.

But I'm not in charge of the engine development so it will be what is decided to be.

Also, I'm willing to work on this when the 4.0 branch become a thing.

**Comment by BenjaminNavarro** [comment]
I just realized that something similar was already (briefly) discussed by @reduz (https://github.com/godotengine/godot/issues/30736, https://github.com/godotengine/godot/issues/30736#issuecomment-513615955). 

Considering this, do we need to keep this proposal open ?

**Comment by golddotasksquestions** [comment]
I think it can be closed once the "internal compatibility system" is added, no?

**Comment by KoBeWi** [comment]
> Considering this, do we need to keep this proposal open ?

A formal proposal is always good to keep, I think.

As for this system, I thought it could be included in the breaking versions, but removed in the next version. So e.g. to upgrade from 3.2 to 4.0.1, you'd first need to import your project in 4.0. It requires some manual work, but is still less tedious than doing it yourself and we avoid uneccessary bloat.

btw, bringing up Unity here is not very good example. Upgrading from x.0.1 to x.0.1a requires 2GB download and 15 minutes of importing. In Godot you can juggle between versions pretty seamlessly and the lightweightness is a pretty good selling point we'd rather not loose.

**Comment by qarmin** [comment]
For anyone who want to try implement this, I prepared test project in Godot 3.4 with almost all available functions which for now after opening in Godot 4 shows ~1400 errors. It would be great if the number of errors would decrease to ~100-200 using this tool.

[GDScript3.4.zip](https://github.com/godotengine/godot-proposals/files/6888233/GDScript3.4.zip)

**Comment by Calinou** [comment]
There's a Python script to convert scripts: https://gist.github.com/aaronfranke/79b424226475d277d0035b7835b09c5f

**Comment by qarmin** [comment]
Is there any preconception how it should look like(I haven't heard anything about it lately and it's quite a serious topic)?
Will it be a separate script(which I doubt) or an additional feature in the editor?
Will it convert only .gd files or also other for example .tscn?
Will it be possible to choose individual files for conversion or will I have to convert whole project like in 2.1?

**Comment by aaronfranke** [comment]
@qarmin For the Bash script I wrote, it operates on all types of files (scenes, GDScript, C#, project.godot, .import, etc), and it operates on the entire repository at once.

**Comment by qarmin** [comment]
I'm curious what is the better option to upgrade project:
- When opening project from Godot 3 in Godot 4, prompt with question about upgrading should become visible(should be possible to not allow to broke project)
or maybe
- Command line argument like `godot4 --upgradeTo4 .` should be added

This is how it upgrade tool works in 2.1 branch
https://github.com/godotengine/godot/blob/2.1/editor/editor_export_godot3.cpp

**Comment by akien-mga** [comment]
For the reference, here's another conversion script developed by @lyuma and @fire: https://github.com/V-Sekai/gd3to4

**Comment by lyuma** [comment]
I already submitted most of what I had in my script to be integrated into qarmin's pr godotengine/godot#51950 and so far qarmin has done really good work implementing most of the rules I had in my script.

A couple properties are hard to integrate because they require type information to know (such as `toplevel` -> `top_level`)  if they are the builtin one or a user-defined function. Also `pause_mode` -> `process_mode` is especially confusing because the enum changed, so 2 needs to become 3 or whatever.

Also still missing some of the EditorPlugin type apis and importers, like _edit, _handles, _get_extensions etc.

One of the other things missing might `FuncRef.new` -> ` Callable` : because Callable is a builtin type, you can't use .new but instead have to just create it with arguments.

**Comment by Cerno-b** [comment]
As discussed here (https://github.com/godotengine/godot-docs/issues/4960), would it make sense to integrate documentation into the converter? Bear in mind that not only the projects need to be converted from 3 to 4, the developers need to as well.

If we could have a string lookup generator closely coupled to the code conversion function that map the conversion to human readable format, we could generate a reST code out of the lookup table that we could drop into the Godot docs, e.g. in the form of a table "old code" --> "new code". 

I think this would be a very convenient way to get Godot 3 devs up to speed with changed syntax.

**Comment by akien-mga** [comment]
An initial version of @qarmin's upgrade tool has been merged and is available in 4.0 alpha 10: https://github.com/godotengine/godot/pull/51950

We can keep this proposal open for now to keep track of further improvements to make to this tool, especially sourced from the other existing conversion tools which may handle other stuff.

**Comment by Zireael07** [comment]
First order of business, I couldn't see shader hints in that, and they're bound to break people's shaders.
PR that renamed them is https://github.com/godotengine/godot/pull/60803 so way before alpha10

**Comment by KoBeWi** [comment]
Some random conversions missing in the official converter that you can find in [mine](https://github.com/KoBeWi/Another-Godot-4-Converter):
- conversion of some properties of specific Controls, e.g. Label alignment or TextureRect stretch mode
- theme overrides
- animation `rotation_degrees` (it should be changed to `rotation` and converted to radians)
- better conversion of setters (right now the converter creates stumps, but actually `var test setget set_test` can become `var test: set = set_test`)
- particle randomness became min/max values. It's possible to convert it based on the old formulas

I'm actually surprised that this handles built-in scripts 🤔

Other things to consider:
- convert SceneTreeTween to Tween. The only API difference is class name (relevant if someone uses explicit type) and callback/method Tweeners, which use Callable in 4.0
- conversion of `connect()` to the new syntax? `other.connect("signal", target, "method", [binds])` becomes `other.signal.connect(target.method).bind(binds)`. This is handled in my converter, but the official one handles connections in a different way (which works), so it's ok too

**Comment by FeralBytes** [comment]
Seems that Threads has changed quite a bit and now uses a Callable.bind, as such my threading library is broke on conversion. I am working on figuring out how the change works, then I will report back.

**Comment by KoBeWi** [comment]
> String.plus_file() becomes String + "/" + file

This was actually renamed to `String.join_path()`.

> var the_callable = Callable(self, "__threaded_background_loader").bind([resource_path, thread_num])
start_success = new_thread.start(the_callable)

Or just `start_success = new_thread.start(__threaded_background_loader.bind(resource_path, thread_num))`

**Comment by FeralBytes** [comment]
FYI I have [added many more notes to my previous comment](https://github.com/godotengine/godot-proposals/issues/387#issuecomment-1251909261) to help with the conversion process.

**Comment by Calinou** [comment]
@FeralBytes Could you open a pull request to update some of the renames performed by the project converter? The code is here: https://github.com/godotengine/godot/blob/master/editor/project_converter_3_to_4.cpp

**Comment by aaronfranke** [comment]
This proposal has been implemented by https://github.com/godotengine/godot/pull/51950
