### ISSUE TITLE
Make right click clear terrain paint in the new TileSet editor

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot-proposals#3873]
### Describe the project you are working on

Generic TileSet workflow, tidying up discussion in #1769.

### Describe the problem or limitation you are having in your project

When painting terrain in the TileSet editor, a small mistake can take multiple clicks to correct, slowing the process down significantly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It will speed up the terrain painting process by preventing users form having to constantly switch to "No Terrain" to clear the terrain paint.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user right clicks a square in the terrain painter, that square is set to "No terrain". Ideally, could click and drag etc with right click too.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The user can select "No terrain" in the drop down menum make the changes they want and then reselect the terrain they were previously using.

### Is there a reason why this should be core and not an add-on in the asset library?

Improves terrain painting workflow in almost all instances.

**Comment by KoBeWi** [comment]
This was implemented for regular tiles here: https://github.com/godotengine/godot/pull/51695
Terrains will probably have similar code.

**Comment by groud** [comment]
Sounds reasonable. If I am not mistaking right-click isn't used for panning anymore so that could work.
I am not sure I implemented something like that but I suppose ctrl+click could also be used as a "terrain picker", that might help.

**Comment by arkology** [comment]
I spend several minutes right-clicking and ctrl+clicking with no effect before I remembered the  "no terrain" option in dropdown menu :D
