### ISSUE TITLE
Project Manager hotkey system is crap in 3.2. Set another default key to button selection.

### ISSUE THREAD

**Issue by thottee** [godotengine/godot-proposals#388]
**Describe the project you are working on:**
It's a default godot issue/discomfort in 3.2.

**Describe the problem or limitation you are having in your project:**
In the godot project manager, I always use arrow keys for quick selection, and in 3.2 this new solution is really discomfort, and crap.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Set back arrow keys to select projects easily, and put another key to button selection. (etc TAB)

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
I don't think it is need for that.

**Describe implementation detail for your proposal (in code), if possible:**
Unfortunatelly I don't have C++ skills.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
-

**Is there a reason why this should be core and not an add-on in the asset library?:**
-

**Comment by Calinou** [comment]
This is technically a bug, so it shouldn't be tracked in this repository (which is intended to be used for feature propopsals). See https://github.com/godotengine/godot/issues/8149.

Also, I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.
