### ISSUE TITLE
Allow opening the same script multiple times in the editor

### ISSUE THREAD

**Issue by SolsticeProjekt** [godotengine/godot-proposals#3883]
### Describe the project you are working on

Edit ----------------------------------------
 Please note that I am not talking about split views.

What I am talking about is more like using tabs, like in Sublime.
Fast switching between two different spots on the same script using CTRL+Tab,
simply by having the file open twice.

"Split views" implies that there is a second visible section of the file,
which means I have to move my eyes to look there,
which with CTRL+Tab I don't.

I'm definitely NOT asking for split views ...
... and yes, the difference is significant!

--------------------------------------- end of Edit.

It's a suggestion for the editor, unrelated to any specific project.

Editors don't just allow to create,
they also define *how* things are created.

Thank you for reading.

### Describe the problem or limitation you are having in your project

Time and time again I have to scroll up, scroll down, etc.

I need to add or change code "here", then "there",
look up the name of a variable,
add a constant,
change a constant,
maybe add a parameter to a function, etc.

I'm being active in several parts of the code, not necessarily in rapid succession,
but that does not change the fact that I've caught myself scrolling around *a lot*.

This isn't "just" about workflow, but also about code structure.
It's about not being *lazy*, like, for example, just dropping a "var" anywhere.

The editor is a massive influence for how one structures his code,
because an undisrupted workflow matters a lot!

I have ...
... exports at the top,
... followed by onreadys,
... followed by const,
... followed by var.

I also have separate paragraphs for special considerations,
like constants and variables for threads.

Having a good structure is immensely useful.
Having the editor hinder that, isn't.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Being able to CTRL+Tab to a different spot in the same script is a massive time saver.

The limitation is that I can't do that, which forces me to use any of the other, slower, options.

My current workarounds to this limitation are ...
... scrolling ...
... using the search.

There is nothing quicker than just CTRL+Tabbing.

Please note that the argument "Just use a different editor" would cause a chain of arguments ending at
"there's no need for a text editor in Godot, simply because there's so many *better* editors out there."

I understand that Godot is not trying to compete with other editors,
but being able to open the same file multiple times isn't actually a ground-breaking feature,
but rather something which should be expected.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/23191574/151522036-5a235474-6331-4d0b-9254-a38d3d68a6df.png)

I propose having the scripts as actual tabs listed in all that waste of space shown in the provided image.
At least that would be a good use of *all that wasted space*.

If that's not a good option, then how about having the scripts in the vertical list being marked as "multiple",
with the ability to CTRL+Tab in between these multiple editor-instances of the same script?

Did I mention all that wasted space just *waiting* to be used?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I've looked into that. It looks possible.
Regardless, I'd have to learn how, unlike you, who don't.

I'd be only doing it for myself, with no benefit to anyone else.

Trying to make it for the benefit of everyone would turn it into a whole project,
with considerations and decisions to make, distracting from my own project.

If I started this, I'd also be faced with the fact that it would get integrated into the main editor eventually,
(because it should be a default feature!), which means you'd have to rewrite a lot of it anyway.

Being able to open multiple scripts at the same time should be a *default* feature for a text editor.

Alternatively I could launch the editor twice, or even thrice, but ...
- that's not just a waste of RAM,
- it also messes with the ALT+TAB chain,
- meaning that reaching the browser window gets a lot more annoying,
- which would cause me to switch to "Virtual Desktops" ... 

... yeah, this isn't really a good option.

I'm sorry for all the rambling.

Thank you.

### Is there a reason why this should be core and not an add-on in the asset library?

A text editor should be able to open the same script multiple times.
If it were just an add-on, people would still not know what they're missing.

That's a problem with editors in general.
People can not know they're missing a feature they didn't even know existed.

It's easy to ignore the ability to open the same file multiple times,
because theoretically it's not required at all,
but practically it makes a huge difference.

There is no faster way of jumping around in between different spots in a file,
than just by switching to the tab that's already there.

Again, I'm sorry for my rambling.

Thank you.

**Comment by Mickeon** [comment]
Isn't this what Bookmarks are for?

Perhaps that aspect of the editor should be improved upon to be more effective, instead of allowing the same script to be opened more than once which, be it a matter of personal taste, has its own set of complications and is often undesired.

**Comment by Mickeon** [comment]
> having the scripts as actual tabs listed in all that waste of space shown in the provided image.

Sorry, I don't see how this would solve the main issue of this proposal.
In fact, it sounds worthy of its own, separate suggestion.

**Comment by pycbouh** [comment]
> Isn't this what Bookmarks are for?

I think this proposal is about split views, which are admittedly useful very often when you have bigger scripts.

**Comment by KoBeWi** [comment]
It is about split views, but the original problem is the need to jump back and forth between few places in a script, which can be solved by using bookmarks.

**Comment by Mickeon** [comment]
> I think this proposal is about split views.
> It is about split views

If true, it would indeed be a pretty useful feature and solve the issues brought by the proposal anyhow.

**Comment by pycbouh** [comment]
I think the context is that you needs to look at two different places at once sometimes, and you _have to_ jump around, back and forth. It's not that you _want to_, it's just the only option without split views.

**Comment by WhalesState** [comment]
I use vscode with gdscript, i think it will be more useful if we can create plugins for the script editor in godot the same way how vscode is rich with extenstions, splitting the views is one thing that i can't work without it, not to open the same script twice only but because i work with classes most of the time and i need to open the class alongside the existing script that uses the class to edit both of them at same time.

**Comment by SolsticeProjekt** [comment]
> > having the scripts as actual tabs listed in all that waste of space shown in the provided image.
> 
> Sorry, I don't see how this would solve the main issue of this proposal. In fact, it sounds worthy of its own, separate suggestion.

I take those too, but it's ultimately about being able to CTRL+Tab to the same file on a different spot. Split view implies I have to move my eyes, which with CTRL+Tab I don't. Yes, it's quite the difference.

**Comment by SolsticeProjekt** [comment]
> It is about split views, but the original problem is the need to jump back and forth between few places in a script, which can be solved by using bookmarks.

Not with those shortcut keys. CTRL or SHIFT and F2. No effing way.

**Comment by pycbouh** [comment]
> No, it's not about split views. It's about tabs, like in sublime.

If it's not about split views, then this proposal doesn't provide any more functionality than the bookmarks do.

> And using bookmarks? Not with those shortcut keys. CTRL/SHIFT and F2. No way.

You can rebind them however you want:

![image](https://user-images.githubusercontent.com/11782833/151665570-f1e2e2bf-cc7b-452a-bbb2-003c7b4974b2.png)

**Comment by WhalesState** [comment]
Blender 2.79 reacts sad, we used to reach some keys with our tongue and feet :smile:
![image](https://user-images.githubusercontent.com/53877170/151667136-dd5b036c-940d-4c20-8f50-a093177547bf.png)

**Comment by SolsticeProjekt** [comment]
You're right! It does not work with CTRL+TAB (I can set the hotkey, but it ignores them), but it works using CTRL+SHIFT.

I can work with that.
I had no idea bookmarks even existed.

Thank you!

**Comment by WhalesState** [comment]
@SolsticeProjekt close the issue if it was solved, feel the devs :smiling_face_with_tear: 2.3k issues are open
