### ISSUE TITLE
Add FPS to window title

### ISSUE THREAD

**Issue by cobrapitz** [godotengine/godot-proposals#3896]
### Describe the project you are working on

/

### Describe the problem or limitation you are having in your project

I want to see fps without filling the output panel with prints

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

makes the developer the FPS visible

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Format:
From <project title> (DEBUG) to <project title> (DEBUG - FPS 123)

which updates once every second (or 2 seconds)

Also I would only output it in debug (since the printing is also just in the debug build)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

```GDScript
# updates fps counter every 2 seconds
func _process(delta: float):
    if OS.is_debug_build():
        if OS.get_system_time_secs() % 2 == 0:
            OS.set_window_title("my title (Debug - FPS %s)" % str(Engine.get_frames_per_second()))
```

### Is there a reason why this should be core and not an add-on in the asset library?

I think this should be core worthy since it's one of the first things I implement as a Label or enable the printing

**Comment by arkology** [comment]
Godot already has it, just read the docs.

https://docs.godotengine.org/en/stable/tutorials/scripting/debug/debugger_panel.html#monitors

**Comment by KoBeWi** [comment]
Changing window title shouldn't be done often, because it may lower performance.

**Comment by cobrapitz** [comment]
My point was to have it visible without having to switch the output tab in the editor ^^

Well, if it's so bad then I'll close it here, sorry.

**Comment by Mickeon** [comment]
> My point was to have it visible without having to switch the output tab in the editor ^^

Have a Label with its text continuously updated with the FPS.
Alternatively, you could overwrite the `_draw()` method of a CanvasItem to draw a String and update it every frame.
There's a bunch of ways to do this that are way more performant than changing the window title. I'm sure there's addons for it, as well. It's a common necessity.

**Comment by Calinou** [comment]
You can add a Label node and attach the following script:

```gdscript
extends Label


func _process(delta):
	text = "%d FPS (%.2f mspf)" % [Engine.get_frames_per_second(), 1000.0 / Engine.get_frames_per_second()]

```
