### ISSUE TITLE
Add `@private` annotation 

### ISSUE THREAD

**Issue by tischenkob** [godotengine/godot-proposals#3910]
### Describe the project you are working on

Any project  with GDScript

### Describe the problem or limitation you are having in your project

I want to hide some methods and variables from autocompletion and don't want to rely on the convention of adding an underscore which is also used for virtual methods

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A `@private` annotation that both hides a class member from autocompletion and speaks for itself for other people reading the code. Could also throw a warning or an error if a member is still accessed from other places

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
@private
var can_jump := true

@private
func set_state(new_state) -> void:
 ...
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. An underscore is not a workaround either

### Is there a reason why this should be core and not an add-on in the asset library?

Custom annotations are not supported

**Comment by tischenkob** [comment]
Suggested here https://github.com/godotengine/godot-proposals/issues/641#issuecomment-722636628

**Comment by pycbouh** [comment]
https://github.com/godotengine/godot-proposals/issues/641 suggests we add proper access modifiers. This proposal seems to suggest we add a shorthand for setting a getter that warns about public access:

> A `@private` annotation that both hides a class member from autocompletion and speaks for itself for other people reading the code. Could also throw a warning or an error if a member is still accessed from other places

**Comment by tischenkob** [comment]
In that or some other related thread, it was discussed that GDScript is meant to be as simple as possible and adding another language construct instead of reusing an already existing one would undermine the purpose of the language. How is an annotation with an actual meaningful name a fake convention? 
As for warnings, I was thinking of something that works like `@Override` annotation in Java which is just a sanity check that does nothing under the hood

**Comment by pycbouh** [comment]
> How is an annotation with an actual meaningful name a fake convention?

It creates an impression of a private field, but the field is not actually private. Is an annotation better than an underscore for parsing the code by humans? Somewhat. An underscore is a convention across several languages that don't have access modifiers to indicate a field or a method that you should not touch from the outside. So there are plenty of users who would have no problem with it. However, for a user who knows what `private` in programming is your proposed change would be misleading, unless we actually implement access modifiers (and that's what #641 is for).

**Comment by tischenkob** [comment]
I don't see why it cannot function like an access modifier but still be an annotation in favour of keeping the language simple

**Comment by dalexeev** [comment]
> I don't see why it cannot function like an access modifier but still be an annotation in favour of keeping the language simple

`static` is also a keyword, not an annotation. And I think implementation complexity is more important than language complexity.

**Comment by pycbouh** [comment]
> I don't see why it cannot function like an access modifier but still be an annotation in favour of keeping the language simple

It can. I don't see much difference if it's a keyword or a keyword with an `@` symbol preceding it.

My point was that if we add actual access modifiers, we already have a proposal for that: https://github.com/godotengine/godot-proposals/issues/641. Whatever syntax we pick is not the important decision here, it's the feature itself.

But you've made this dedicated proposal to add an annotation without the access modifier feature. I don't think that it's a good idea.

**Comment by tischenkob** [comment]
Then my proposal holds pop no additional value
