### ISSUE TITLE
Add Color.transparent_black constant

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#3913]
### Describe the project you are working on

A typical 2D Godot game

### Describe the problem or limitation you are having in your project

I'm using admittedly quick and dirty solutions to fade fully black **CanvasItems** out, for transitions. Godot is generally pretty good for quick prototypes.
I was a bit puzzled by the `Color.transparent` constant being transparent white, which makes perfect sense in a game environment, for sure, but didn't yield intended results when used in interpolation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add `Color.transparent_black`.

Most drawing programs I've used also default to transparent_black when erasing or cutting part of the canvas. I believe it would also make scripts in Godot that intertwine a lot with Colours like this more readable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
tween.interpolate_property(sprite, "modulate", Color.black, Color.transparent_black, 2)
tween.start()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yeah, it's not too big of a deal, actually. Just not as readable in some contexts.
At the end of the day transparent black is just a fully empty Colour.

```
const TRANSPARENT_BLACK := Color(0)

# Pseudocode
tween.interpolate_property(sprite, "modulate", Color.black, TRANSPARENT_BLACK, 2)
tween.start()
```

### Is there a reason why this should be core and not an add-on in the asset library?

The Color type itself is core

**Comment by Xrayez** [comment]
You may use indexed property access to simplify this, regardless of color:
```gdscript
tween.interpolate_property(sprite, "modulate:a", 1.0, 0.0, 2)
```

Having both `Color.transparent` and `Color.transparent_black` may be ambiguous. To resolve this, we'd probably need to rename `Color.transparent` to `Color.transparent_white`.

**Comment by dalexeev** [comment]
Use `Color('black', 0)` (`ColorN('black', 0)` in 3.x).

**Comment by aaronfranke** [comment]
In Godot 4.0, `Color(Color.BLACK, 0.0)` is more efficient than using strings (constructs a Color from an existing Color plus an alpha value).

**Comment by Mickeon** [comment]
Closing due of lack of support. The suggested alternatives are beyond satisfactory.
