### ISSUE TITLE
VisualShaderNodeCustom decouple node instantiation in vertex/fragment/light from ability to inject code in the stages

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#3916]
### Describe the project you are working on

VFX tools and Godot Engine

Specifically, I'm trying to have all the high level functionalities of spatial/canvas/process material as visual shader nodes (triplanar mapping, canvas animation .. etc.)

### Describe the problem or limitation you are having in your project

It is currently not possible to inject shader code in stages where the node is not instanced.

What I want users to do:
- drag ParticleAnimation node to fragment stage

Particle animation is a great example of this because it requires code on both the vertex stage and the fragment stage.
In vertex stage, INSTANCE_CUSTOM (vertex stage only) is read and it's used to compute new UVs. These new UVs are then used in the fragment shader.
This means that the user needs to instance twice the node, once in vertex stage, and another in fragment stage.
This is not good UX for users, especially because this work that I'm doing is meant to simplify the workflow for non-techincal people. Instancing the node twice requires knowledge of how internally vertex/fragment works.

For comparison, this is how it looks in Unity: 
![Screenshot from 2022-02-05 10-30-11](https://user-images.githubusercontent.com/7917475/152636291-32402824-2904-4e97-8103-6f1ba4e92928.png)
This is plugged directly in the fragment stage.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'm not highly opinionated about the technical implementation for this, as long as the following workflow is possible:

- User creates a visual shader
- user adds "ParticleAnimation" node in fragment stage and can use output UV to plug in a texture sampler
- no other user action required

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example implementation:
Add a function to VisualShaderNodeCustom `_is_available` (name up for discussion) that tells VisualShaders wheter or not the node should show up in the "add" popup.
`_get_code` gets executed if the node is present in **any** stage.
This way, as a plugin creator, I am able to inject code in vertex stage even if my node is instanced only in the fragment stage.

This is my own idea for the solution to this problem, but I am not picky on the solution as long as it's possible to give the workflow described above to the users.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is not possible to deliver this UX with the current VisualShaderNodeCustom implementation.

### Is there a reason why this should be core and not an add-on in the asset library?

This will be a base for addons, or built-in high level shader nodes.

**Comment by Chaosus** [comment]
@QbieShay Look at `VisualShaderNode::generate_global_per_func` internal function - currently, it is not exposed to custom nodes and is used only by the `VisualShaderNodeTextureUniformTriplanar`. It will insert the required code to the beginning of each function (but only one time per each node type instantiate) - I guess that is what you want?

**Comment by Chaosus** [comment]
```
tool
extends VisualShaderNodeCustom
class_name CanvasAnimationNode

func _get_name() -> String:
	return "CanvasAnimatioNode"

func _get_category() -> String:
	return "Animation"

#func _get_subcategory():
#	return ""

func _get_description() -> String:
	return "CanvasAnimation"

func _get_return_icon_type() -> int:
	return VisualShaderNode.PORT_TYPE_SCALAR

func _get_input_port_count() -> int:
	return 3

func _get_input_port_name(port: int):
	match port:
		0:
			return "h_frames"
		1:
			return "v_frames"
		2:
			return "looping"

func _get_input_port_type(port: int):
	match port:
		0:
			return VisualShaderNode.PORT_TYPE_SCALAR
		1:
			return VisualShaderNode.PORT_TYPE_SCALAR
		2:
			return VisualShaderNode.PORT_TYPE_BOOLEAN

func _get_output_port_count() -> int:
	return 1

func _get_output_port_name(port: int) -> String:
	return "uv"

func _get_output_port_type(port: int) -> int:
	return VisualShaderNode.PORT_TYPE_VECTOR

func _get_global_code(mode: int) -> String:
	return "varying vec2 anim_uv;\n"

func _get_code(input_vars: Array, output_vars: Array, mode: int, type: int) -> String:

	match type:
		VisualShader.TYPE_FRAGMENT:
			return output_vars[0] + " = vec3(anim_uv, 0.0);"
		VisualShader.TYPE_VERTEX:
			var h_frames = input_vars[0]
			var v_frames = input_vars[1]
			var looping = input_vars[2]
			var out = output_vars[0]
			return """
			float particle_total_frames = float("""+h_frames+""" * """+v_frames+""");
			float particle_frame = floor(INSTANCE_CUSTOM.z * float(particle_total_frames));
			particle_frame = mod(particle_frame, particle_total_frames);
			anim_uv = UV;
			anim_uv /= vec2("""+h_frames+""", """+v_frames+""");
			anim_uv += vec2(mod(particle_frame, """+h_frames+""") / """+h_frames+""", floor(particle_frame / """+h_frames+""") / """+v_frames+""");
			"""
	return ""
```

I think there is a direct violation of the logic of visual shaders. You want a node to be declared on the Fragment shader graph but the input ports used to translate the values to Vertex function varying but how it is possible with the current system is not clear for me - for example, what happened if you attempt to connect input from Fragment to such port? - the Vertex function does not recognize it and the shader will fail to compile.

**Comment by QbieShay** [comment]
> I think there is a direct violation of the logic of visual shaders. You want a node to be placed only on the Fragment shader graph with the input ports used to translate the values to Vertex function varying but how it is possible with the current system is not clear for me - for example, what happened if you attempt to connect an input exists only on Fragment to such port? - the Vertex function does not recognize it and the shader will fail to compile. So we should add some complex checking to prevent this connection.

The fragment function works because the varying is defined in the global scope, it's just never assigned. So the shader does compile, but doesn't work at all.

I'll look into the texture uniform triplanar and respond further

**Comment by QbieShay** [comment]
> @QbieShay Look at VisualShaderNode::generate_global_per_func internal function - currently, it is not exposed to custom nodes and is used only by the VisualShaderNodeTextureUniformTriplanar. It will insert the required code to the beginning of each function (but only one time per each node type instantiate) - I guess that is what you want (regarding the _get_code part)?

Oh yes! I think that would work perfectly for what I need. In that case it can just be exposed?

**Comment by Chaosus** [comment]
> In that case it can just be exposed?

The problem is it does not accept any input port data and in the provided example you want to pass some input data to a varying. It's better to behave internally but a new virtual function to created and attached to the definition of this function in `VisualShaderNodeCustom` if you need such functionality (like `_get_func_code`).

**Comment by QbieShay** [comment]
@Chaosus the input data is the `INSTANCE_CUSTOM` which is built-in .. This is a problem that applies to anything in fragment shader that needs to read particle lifetime

**Comment by Chaosus** [comment]
Yeah, built-ins would work as expected so if the provided example:

```
VisualShader.TYPE_VERTEX:
			var h_frames = input_vars[0]
			var v_frames = input_vars[1]
			var looping = input_vars[2]
			var out = output_vars[0]
			return """
			float particle_total_frames = float("""+h_frames+""" * """+v_frames+""");
			float particle_frame = floor(INSTANCE_CUSTOM.z * float(particle_total_frames));
			particle_frame = mod(particle_frame, particle_total_frames);
			anim_uv = UV;
			anim_uv /= vec2("""+h_frames+""", """+v_frames+""");
			anim_uv += vec2(mod(particle_frame, """+h_frames+""") / """+h_frames+""", floor(particle_frame / """+h_frames+""") / """+v_frames+""");
			"""
```
is not what you want - I may add a new virtual function to do it (as I said in the previous post). `_get_code` cannot be used for it since it is expected to be connected to the Output node at all times and not have a role to code insertion into each function.

**Comment by QbieShay** [comment]
Oh I see. I think in that case I'd just declare them as uniforms. For me the main pain point was the lack of something similar to `geenrate_global_per_func`, I think that once i have that, I can work an implementation that makes it work

**Comment by QbieShay** [comment]
Ideally we can have a node ID to append to the variables? just in case i want to use two of them, so i can declare the uniforms with uniform_name + nodeID
