### ISSUE TITLE
Pixel rounding

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#3924]
### Describe the project you are working on

A game for smartphones.
I want to get an authentic retro style.
To do this I would like the sprites to render and move in whole pixel positions.
Construct has an option for this:

![Captura2](https://user-images.githubusercontent.com/19652075/152679156-71713d36-8cb2-4624-a09a-09868ab8e2ee.PNG)

Why doesn't godot have this option?

### Describe the problem or limitation you are having in your project

It is not possible to achieve a true retro style without being able to move the sprites only in integer positions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The engine will process the positions only in integers.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The engine will round all positions to integers and everything else will be processed from there.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

IDK

### Is there a reason why this should be core and not an add-on in the asset library?

IDK

**Comment by Calinou** [comment]
This already exists in the form of 2D pixel snap in the project settings. However, the option may not work as expected, especially in Godot 4: https://github.com/godotengine/godot/issues/55006, https://github.com/godotengine/godot/issues/56793

**Comment by Torguen** [comment]
Do you mean this option?
![Captura2](https://user-images.githubusercontent.com/19652075/152679715-f139c0b3-62e6-4884-8678-e64f0bd9dea8.PNG)
Obviously if the option already exists then this can be closed.
I simply enabled the option and saw that it does not do what I was looking for, so I opened the proposal.

But this "pixel snap" option it doesn't seem to work at all

https://user-images.githubusercontent.com/19652075/152679726-c2899416-02db-43a1-9ea6-6b9b7e7399f0.mp4

**Comment by Calinou** [comment]
> But this "pixel snap" option it doesn't seem to work at all

Pixel snap only rounds coordinates to integer values when *rendering*, not within your game logic. If you want to avoid floating-point values in your game logic[^1], you need to write your own physics in GDScript as the built-in physics engine uses a lot of floating-point logic.

[^1]: This is mainly useful to ensure determinism. Most of the time, you do _not_ need to avoid floating-point logic, even in a pixel art game.

**Comment by Torguen** [comment]
> > But this "pixel snap" option it doesn't seem to work at all
> 
> Pixel snap only rounds coordinates to integer values when _rendering_, not within your game logic. If you want to avoid floating-point values in your game physics[1](#user-content-fn-1-44e4df3d66f48e666669899f583c6ef3), you need to write your own physics in GDScript as the built-in physics engine uses a lot of floating-point logic.
> 
> ## Footnotes
> 1. This is mainly useful to ensure determinism. Most of the time, you do _not_ need to avoid floating-point physics, even in a pixel art game. [↩](#user-content-fnref-1-44e4df3d66f48e666669899f583c6ef3)

Ok, so the sprites are drawn at integer positions?
So that's what I wanted to achieve.
