### ISSUE TITLE
Allow defining a folder as the root folder in FileDialog to prevent users from accessing outside files

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#3929]
### Describe the project you are working on

A project (tool) which allows users to save custom files in the `user://somedirectory` directory.

### Describe the problem or limitation you are having in your project

Currently the user has access to the full `user://` folder, which I would like to disallow.

When the user presses the up button, I would like this subfolder of `user://` to be the toplevel folder.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding some way to limit the user to the folder specified in `CurrentDir` or subdirectories, perhaps a checkbox `make root hidden`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A checkbox or other filter which allows specifying that I don't want directory traversal except allowed directories

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This should be part of the core FileDialog

### Is there a reason why this should be core and not an add-on in the asset library?

See above

**Comment by akien-mga** [comment]
Could you provide more details on the use case? The proposal is a bit light on details and it's not clear what real life use case would require this.

If you only want users to save files to a given subdirectory, the easiest is likely to not use FileDialog at all but simply ask them for a file name and you save it yourself.

**Comment by tavurth** [comment]
> Could you provide more details on the use case? The proposal is a bit light on details and it's not clear what real life use case would require this.

@akien-mga a good example use case for this would be some form of utility or tool which allows saving to a file (Aseprite jumps to mind)

As a developer I would like to save the users configuration to the `user://` folder, and perhaps cache some data there as well.

However I would also like to allow the user access to some `user://subfolder` where their created artworks can be saved and loaded from (with full filename access)

In this case I'd rather not have the user messing or deleting caches or configs accidentally, and so restricting them to some subfolder would be a useful solution.
