### ISSUE TITLE
Port the Godot editor to Android

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot-proposals#3931]
### Describe the project you are working on

Running the Godot Editor natively on Android devices.

Note this proposal is a subset of https://github.com/godotengine/godot-proposals/issues/1061 as it focuses on issues specific to the Android port of the Godot Editor.

### Describe the problem or limitation you are having in your project

Ability to use the Godot Editor natively on an Android device.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The Godot Editor is itself a Godot app and thus can be made to run on Android devices since Godot can create / build / export Android apps and games.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This proposal tracks the work of getting the Godot Editor running natively on Android devices:

- 3.x version: https://github.com/godotengine/godot/pull/57747
- 4.x version: https://github.com/godotengine/godot/pull/58160 (original PR: https://github.com/godotengine/godot/pull/36776)

This proposal will centralize developers / users feedback as well as suggestions to the editor core logic and UX in order to produce a high quality port of the Godot Editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This is about expanding the reach of the Godot Editor to the Android platform.

**Comment by m4gr3d** [comment]
Note this proposal is a subset of https://github.com/godotengine/godot-proposals/issues/1061 as it focuses on issues specific to the Android port of the Godot Editor.

**Comment by SoyoTamo** [comment]
It would also be the easiest way for someone from the third world (like me) to use Godot 4 with Vulkan. Since the mobile hardware equipped with the latest technologies is much easier to get than the desktop.

**Comment by fire-forge** [comment]
Using Godot on a phone would probably be difficult because of how small it is, but this will really be great for Chromebook and tablet users who have to use the web version right now.

**Comment by MichaelGlenMontague** [comment]
> Using Godot on a phone would probably be difficult because of how small it is, but this will really be great for Chromebook and tablet users who have to use the web version right now.

My main reason for wanting an Android port is to have both the API documentation and an experimentation environment available from a single app on the phone in my pocket. But for such a small screen, it has to support portrait mode and fullscreen docks, hide the navigation bar, and use long-press in place of right-click.

**Comment by HammerFox** [comment]
Using this on something like a foldable phone is such an interesting use case. I have a Z Fold 3 and, from my simple testing, the interface, while small, is honestly fairly easy to navigate with the S Pen. I really want to see this come to fruition, as I've been using Construct 3 for development across my laptop and Fold but having something as powerful as Godot on my phone would be amazing!

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/57747

**Comment by m4gr3d** [comment]
@akien-mga I'm keeping the proposal open to gather feedback for updates and improvements!

**Comment by HammerFox** [comment]
The fact that this is now gonna be official is so freaking cool. Having a REAL full featured game engine on a mobile device is absolutely insane. Are touch gestures planned? Like gestures for moving around the viewport? And also maybe long press for right click or something? Thank you for all of your hard work guys! You guys are amazing!

**Comment by AlphinAlbukhari** [comment]
My feedback: 
- Maybe two (close) fingers gesture for right click? Just like how it is on most touchpads
- PopupMenus should be scrollable
- WindowDialogs are hard to resize, maybe enlarge the resize area?

**Comment by HammerFox** [comment]
> > The fact that this is now gonna be official is so freaking cool. Having a REAL full featured game engine on a mobile device is absolutely insane. Are touch gestures planned? Like gestures for moving around the viewport? And also maybe long press for right click or something? Thank you for all of your hard work guys! You guys are amazing!
> 
> This is all planned, but it'll take a while to be fully implemented. We need to focus on releasing 4.0 as well 🙂

Ah okay! Awesome :). It's already super usable with a mouse and keyboard,  so no biggie!

**Comment by Starkium** [comment]
I just loaded this onto an oculus quest and for the most part the editor works! I lost input when the 3d editor got summoned and I have a grey screen when trying to run a downloaded project, but still it loads up and even accesses the keyboard and file directory. This is sick!

Can we get a native vr editor? IE: launches into a vr environment when working on the 3d stuff? I would LOVE to be a part of the development of this. Godot Editor Android VR could be THE tool that the metaverse is founded on, this is absurdly interesting. :)

**Comment by m4gr3d** [comment]
> Can we get a native vr editor? IE: launches into a vr environment when working on the 3d stuff? 

@Starkium This is definitely on the roadmap (see https://godotengine.org/article/godot-engine-receiving-new-grant-meta-reality-labs)!

> I would LOVE to be a part of the development of this. 

We'd appreciate all the help we can get! 
One of the initial tasks that would improve the experience on the Quest is support for touch interaction. If you try it on a Android device or tablet today, and as reported by several folks in the thread, the touch interaction is basic and doesn't give you full access to the functionality.
By improving it, we'd also be improving interaction on the Quest with the controllers or hand tracking.

> Godot Editor Android VR could be THE tool that the metaverse is founded on, this is absurdly interesting. :)

Couldn't agree more!

**Comment by AMAIOLAMO** [comment]
I booted it up and it was super awesome!

I tried to do a simple platformer and realized some problems that requires improvement ( all the problems below are which I didn't use a mouse and keyboard ):

- Scenes are hard to drag and move around.

- There doesn't seem to have a delete button for nodes lol.

- There's one problem in code editor when using specific keyboards that checks for the current typing word, it glitches out and might accidentally type the same thing 2 times in a row, switching to another keyboard that doesn't do it fixes the problem.

- There are still some problems in quitting back to editor while play testing, it sometimes doesn't quit back to editor when I tried to return, it just allows me to quit the whole app.

- Sliding on mobile is hard, the code completion isn't scrollable by dragging, and sometimes pressing on one of the code completion to select it isn't possible ( not sure how that works )

Those are my first impressions while making a super basic platformer game

wish it'll help improve the android port more, I'm super excited to see how this is gonna work out!

**Comment by filipworksdev** [comment]
Just built this and works well so far. I cannot pan with 2 fingers . I guess that behavior hasn't been implemented yet.

- I keep getting error spam in Output such as base_button.cpp:351, viewport_container.cpp:171 , script_editor-plugin.cpp:2733, input_map_cpp:129 mostly around this `p_event.is_null()` some issue with unhandled input. Anyone else getting this? 
- The flicker is gone but I still see occassional glitchy graphics especially in 3D or if I scroll very quickly but is actually usable so is no longer an issue.  It actually works now.
- Due to small screen space built in documentation is mostly unreadable and AssetStore can push the right panel off screen if you have an asset item with long name.
- After specifi setting changes ask me to restart it will never restart. In fact setting is reversed. You need to change the setting. Close settings. Quit the application and load it again manually.
- GLES3 appears  very slow on my system Samsung Tab S6 Lite but GLES2 works okay.
- There is no way to open FileSystem items since double-tapping doesn't appear to be working. You need a mouse to effectively use this but works alright. 
- There is no way to show the right click context menu either. I tried tap and hold and two finger tap and doesn't appear to do anything. I assume those functions have not been implemented yet.

Overall I'd say this is great. Is about 99% working minus the ui stuff. My tablet actually supports DEX mode with mouse cursor so I can use it just like a regulat computer but I suspect other tablets will have a bit of a hard time making it work properly.

**Comment by Calinou** [comment]
> GLES3 appears very slow on my system Samsung Tab S6 Lite but GLES2 works okay.

The GLES3 renderer has a high base cost which isn't suited to mobile devices. It can run a bit better if you disable HDR and depth prepass in the project settings, but it will still have a higher base cost compared to GLES2.

We should probably default newly created projects to GLES2 on Android, and use GLES2 for the project manager too.

**Comment by almirpask** [comment]
Loving this port! running on samsung galaxy tab s7 FE my main problem was going back to the editor after running my games, it seems that the editor is closed by the game and to continue to editing the project you need to open everything from the beginning, using a bluetooth keyboard I had no problems with the UI.

**Comment by HammerFox** [comment]
> * S-Pen draws blue lines like Godot Editor is a drawing application when I start drawing from the very top downwards.

That blue line is actually from S-Pen to text, so maybe the whole editor is somehow being treated as a text field? I get the same thing on my Fold 3.

**Comment by Calinou** [comment]
> That blue line is actually from S-Pen to text, so maybe the whole editor is somehow being treated as a text field? I get the same thing on my Fold 3.

This is likely the culprit. Virtual keyboard support on Android requires an invisible text input: https://github.com/godotengine/godot/issues/59705

**Comment by HammerFox** [comment]
Ahhhh okay that makes sense. It's a pretty minor thing, but hopefully there's some solution for it because pen support would make the editor amazing even on small slab phones like the S22 Ultra/Note

**Comment by koenvaneijk** [comment]
> > Can we get a native vr editor? IE: launches into a vr environment when working on the 3d stuff?
> 
> @Starkium This is definitely on the roadmap (see https://godotengine.org/article/godot-engine-receiving-new-grant-meta-reality-labs)!
> 
> > I would LOVE to be a part of the development of this.
> 
> We'd appreciate all the help we can get! One of the initial tasks that would improve the experience on the Quest is support for touch interaction. If you try it on a Android device or tablet today, and as reported by several folks in the thread, the touch interaction is basic and doesn't give you full access to the functionality. By improving it, we'd also be improving interaction on the Quest with the controllers or hand tracking.
> 
> > Godot Editor Android VR could be THE tool that the metaverse is founded on, this is absurdly interesting. :)
> 
> Couldn't agree more!

I was working on a project last night and remembered this issue from mid-Feb, just thinking of the possibilities. It could even run fully native on the Quest with optimized 3D scene viewport. Jumping straight into the game. 

It blows my mind to see what progress is already being made and I can’t even describe how excited I am for the future!

I need to brush up on C++ syntax a bit as I’m coming from Python, but very eager to find out how I can contribute to this.

**Comment by idchlife** [comment]
@m4gr3d hey, responding in this thread.

So I am using this thing: http://innov8tiv.com/wp-content/uploads/2021/06/14-inched-Samsung-Galaxy-Tab-S8.jpeg

I did not yet test with separately connected mouse, so I cannot yet say if it works or not.
Touchpad works in the way it kinda resembles macbook touchpad. It has mouse cursor, it has gestures, but it's not yet full-blown mouse.

I made screen recording of my usage of template project. As you can see, I often do "something" which makes sliders highlight. I am using 2 fingers to scroll, but it results in something odd, "real" cursor seems to obtain some kind of offset, while it's gui representation stays as it was. You can see later, that I cannot normally click things despite the fact of pointing at them.
Also about usage of viewport, my mistake, I meant I cannot rotate the camera, look anywhere using touchpad, because I assume - there is no wheel mouse button. And 2/3/4 fingers do nothing. I also tried holding alt, ctrl, shift - nothing.

https://easyupload.io/edj5xr

I am aware of a niche setup here, with my touchpad for tablet, so I think I better help with testing keyboard/mouse duo instead, because this will be the most used setup I predict (connect android phone to external display - connect mouse/keyboard - voila, you are a game dev).

**Comment by FlykeSpice** [comment]
1000x thumbs up.

**Comment by Calinou** [comment]
@FlykeSpice Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Starkium** [comment]
Has there been any progress with usage within a VR environment like the quest yet?

**Comment by m4gr3d** [comment]
> Has there been any progress with usage within a VR environment like the quest yet?

@Starkium Not yet. We're focusing on stabilizing the Android port first (getting fairly close to a beta state!), and we'll follow up with the Quest port.

One of the major remaining issue before beta is improving touch interactions for the port on Android devices. Solving this issue should also improve the current state of the port when sideloaded to a Quest device.

**Comment by VoxSkynned11** [comment]
> > Has there been any progress with usage within a VR environment like the quest yet?
> 
> @Starkium Not yet. We're focusing on stabilizing the Android port first (getting fairly close to a beta state!), and we'll follow up with the Quest port.
> 
> One of the major remaining issue before beta is improving touch interactions for the port on Android devices. Solving this issue should also improve the current state of the port when sideloaded to a Quest device.

How closer would you say :3 sorry I'm anxious about it, will itt be for 3.5?

**Comment by Calinou** [comment]
> How closer would you say :3 sorry I'm anxious about it, will itt be for 3.5?

[New features will only land in 3.6 and 4.0, not 3.5.x.](https://docs.godotengine.org/en/stable/about/release_policy.html)

**Comment by Starkium** [comment]
> That said, I'd be very surprised if a VR editor was completed before 4.0 is released. This is probably 4.1 material _at best_, considering it's something only a few people will be able to use effectively.

I think you're grossly underestimating what the android editor with vr mode on quest really means for the entire vr community at large.

**Comment by VoxSkynned11** [comment]
> > That said, I'd be very surprised if a VR editor was completed before 4.0 is released. This is probably 4.1 material _at best_, considering it's something only a few people will be able to use effectively.
> 
> I think you're grossly underestimating what the android editor with vr mode on quest really means for the entire vr community at large.

No you misunderstood me, i was talking about the touch support

**Comment by VoxSkynned11** [comment]
Noo please don't hate me, i didn't mean the VR i meant the touch support
for android.. 😢 i know android OS sucks for development

Em 31 de ago de 2022 11:29, "Aaron Benjamin" ***@***.***>
escreveu:

**Comment by m4gr3d** [comment]
FYI, we should have a beta build ready once #65398 & #65434 are submitted!

**Comment by VoxSkynned11** [comment]
> FYI, we should have a beta build ready once [godotengine/godot#65398](https://github.com/godotengine/godot/pull/65398) & [godotengine/godot#65434](https://github.com/godotengine/godot/pull/65434) are submitted!

UwU

**Comment by m4gr3d** [comment]
> FYI, we should have a beta build ready once [godotengine/godot#65398](https://github.com/godotengine/godot/pull/65398) & [godotengine/godot#65434](https://github.com/godotengine/godot/pull/65434) are submitted!

Update beta build of the Godot Android Editor with numerous bug fixes and updates!

[Godot Android Editor v3.6.0.beta.0](https://drive.google.com/file/d/1dUV8XWYUe_l3CQJc-OOFMqYjj2QzkGTO/view?usp=sharing)

**Comment by VoxSkynned11** [comment]
> > FYI, we should have a beta build ready once [godotengine/godot#65398](https://github.com/godotengine/godot/pull/65398) & [godotengine/godot#65434](https://github.com/godotengine/godot/pull/65434) are submitted!
> 
> Update beta build of the Godot Android Editor with numerous bug fixes and updates!
> 
> [Godot Android Editor v3.6.0.beta.0](https://drive.google.com/file/d/1dUV8XWYUe_l3CQJc-OOFMqYjj2QzkGTO/view?usp=sharing)

Can you tell if this is a known issue:
While testing the game, the game doesn't recognize the keyboard input(android keyboard) in the project input map it does recognize it but while playing it simply doesn't work, i remember i tried some weird stuff like running godot under proot and still no luck, i tried different keyboard apps

**Comment by VoxSkynned11** [comment]
> > > FYI, we should have a beta build ready once [godotengine/godot#65398](https://github.com/godotengine/godot/pull/65398) & [godotengine/godot#65434](https://github.com/godotengine/godot/pull/65434) are submitted!
> > 
> > 
> > Update beta build of the Godot Android Editor with numerous bug fixes and updates!
> > [Godot Android Editor v3.6.0.beta.0](https://drive.google.com/file/d/1dUV8XWYUe_l3CQJc-OOFMqYjj2QzkGTO/view?usp=sharing)
> 
> Can you tell if this is a known issue: While testing the game, the game doesn't recognize the keyboard input(android keyboard) in the project input map it does recognize it but while playing it simply doesn't work, i remember i tried some weird stuff like running godot under proot and still no luck, i tried different keyboard apps , i think i saw someone talking about it but i couldn't find it anymore..

Oh wait actually it works with the bt controller (you van doenload from playstore) but you'll need a second smartphone

**Comment by SBHattarj** [comment]
it seems I can't add new script language to my project with addons

**Comment by m4gr3d** [comment]
> it seems I can't add new script language to my project with addons

We haven't tested the use of add-ons yet with the Android port but it's unlikely that scripting languages other than gdscript will work out of the box.

**Comment by SBHattarj** [comment]
> unlikely

Is there plans for supporting addons, also after using the editor a while without removing the addon, on the debugger it gave the following error:
E 0:00:00.199   open_dynamic_library: Can't open dynamic library: libpythonscript.so, error: dlopen failed: library "libpythonscript.so" not found.
  <C++ Error>   Parameter "p_library_handle" is null.
  <C++ Source>  platform/android/os_android.cpp:274 @ open_dynamic_library()


I had installed an addon called godot python. I don't know if this will help in any way, but thought I should mention it. I'm not sure, if this is an error with the editor though.

**Comment by SBHattarj** [comment]
> > it seems I can't add new script language to my project with addons
> 
> We haven't tested the use of add-ons yet with the Android port but it's unlikely that scripting languages other than gdscript will work out of the box.

Is there any plans for supporting addons or custom scripting language also, I don't have long access to a computer, so would like to work on my android, and I really want to use python for my project which can be added by godot python addon which works on desktop.

Also after working on got this error on the debugger, which doesn't occur on desktop:
E 0:00:00.199   open_dynamic_library: Can't open dynamic library: libpythonscript.so, error: dlopen failed: library "libpythonscript.so" not found.
  <C++ Error>   Parameter "p_library_handle" is null.
  <C++ Source>  platform/android/os_android.cpp:274 @ open_dynamic_library()

I'm not sure if this'll help, but thought this might be usefull info.

**Comment by Zireael07** [comment]
This is an android version, I strongly doubt custom scripting languages are possible on Android.

**Comment by SBHattarj** [comment]
> This is an android version, I strongly doubt custom scripting languages are possible on Android.

Actually certain languages can be ran on android through proper binaries, termux and pydroid being great example, so if an adon can give proper binaries to run the language, I believe it maybe posible to be ran on android

**Comment by Calinou** [comment]
C# is not supported on Android yet due to missing/incomplete upstream support. It won't be done in time for 4.0.

GDExtension support is technically feasible, but also missing in 4.0.

**Comment by ShalokShalom** [comment]
What is missing for dotnet support?

**Comment by m4gr3d** [comment]
Port of the Godot Editor on Android released on the Play Store!

https://godotengine.org/article/android_godot_editor_play_store_beta_release/
