### ISSUE TITLE
Add support for dragging and dropping materials and textures onto MeshInstances and CSG shapes

### ISSUE THREAD

**Issue by BlueCannonBall** [godotengine/godot-proposals#394]
**Describe the project you are working on:** I'm working on a small-scale Battle Royale style shooter game.

**Describe the problem or limitation you are having in your project:** It takes me too long to apply materials to meshes with lots of material slots. Because of of the lack of a feature to drag and drop materials straight onto the editor viewport, it takes me hours to days to implement new assets.

**Describe how this feature / enhancement will help you overcome this problem or limitation:** If I were able to simply drag an image (to automatically make a material) or material onto a mesh, the time it takes to finish meshes would be cut in half.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/35404206/72690216-3852de00-3ae8-11ea-9988-39b718b613b5.png)

**Describe implementation detail for your proposal (in code), if possible:** Not sure how.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** Not that I know of.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not really, assuming it's possible to make such an asset. Though I don't know how.

**Edit:** Forgot to mention that the screenshot isn't the project I mentioned above.

**Comment by Calinou** [comment]
> If I were able to simply drag an image (to automatically make a material) or material onto a mesh, the time it takes to finish meshes would be cut in half.

Note that if you need textures other than albedo in your material, you'd still have to add them manually in the SpatialMaterial. That is, unless we add a method to load all texture maps automatically (e.g. using convention-based filenames).

**Comment by BlueCannonBall** [comment]
Yes, I do realize that it would still be manual for texture slots other than albedo. It would still make my workflow far more more efficient.

**Comment by me2beats** [comment]
Duplicate/Supersede?
https://github.com/godotengine/godot-proposals/issues/1938

This proposal has a clear screenshot example and more likes

**Comment by Jummit** [comment]
For the time being, you can use this plugin: [material_dropper.zip](https://github.com/godotengine/godot-proposals/files/6215365/material_dropper.zip)

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/56597.
