### ISSUE TITLE
Add a Duplicate button and context menu to the SpriteFrames editor

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot-proposals#3942]
### Describe the project you are working on

Game Jam

### Describe the problem or limitation you are having in your project

Creating Animations for an AnimatedSprite node is missing the duplicate feature that the rest of the UI has.

Create an AnimatedSprite node and edit its "SpriteFrames".
![image](https://user-images.githubusercontent.com/3934352/153078889-0454d6ff-c949-4128-9c70-1e412e7ce939.png)
Above the animations are buttons for [New Animation] and [Remove Animation] but it is missing a [Duplicate Animation]
Right clicking an animation, doesn't bring up a context menu.
The context menu should at least list [Duplicate Animation] and [Remove Animation].

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Some animations are really complicated, which is why there is a dedicated tool to edit them. To have a new animation with just 1 change, you currently have to restart from scratch for each animation which can take a long time for a single animation, let alone if you have to do this 20 times.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Edit the "SpriteFrames" of an AnimatedSprite and try to open the right click context menu on an Animation. There should be a Duplicate option.
![image](https://user-images.githubusercontent.com/3934352/153078889-0454d6ff-c949-4128-9c70-1e412e7ce939.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Some animations are really complicated, which is why there is a dedicated tool to edit them. To have a new animation with just 1 change, you currently have to restart from scratch for each animation which can take a long time for a single animation, let alone if you have to do this 20 times.

### Is there a reason why this should be core and not an add-on in the asset library?

In the Scene Tab, you can right click a node to get a context menu with a Duplicate option.
In the FileSystem Tab, you can right click a file to get a context menu with a Duplicate... option.
In the Animations Tab for AnimatedSprite, you can NOT right click an animation to get a context menu with a Duplicate option.

**Comment by RefinedSoftwareLLC** [comment]
https://github.com/godotengine/godot/issues/57823

**Comment by Mickeon** [comment]
> Some animations are really complicated, which is why there is a dedicated tool to edit them. To have a new animation with just 1 change, you currently have to restart from scratch for each animation which can take a long time for a single animation, let alone if you have to do this 20 times.

Fortunately, because .tres files are inherently _text resources_, it's possible to mitigate this issue by saving the **SpriteFrames** on disk, opening the resource as text and copy-pasting the desired animation. It may look like something this:

![SpriteFrames copy pasting example](https://user-images.githubusercontent.com/66727710/153278931-0fd3bf31-d41e-4670-9250-a9e60adafef4.gif)

**Comment by RefinedSoftwareLLC** [comment]
Thanks for posting a workaround! It is hard to know what can be changed like this and what can't. Like renaming a file makes changes in multiple files, if you only did the change in 1 file it would break. I am glad to know this can be edited this way safely.

**Comment by Kiaazad** [comment]
Also ability to select multiple frames for different operations would be nice, including copy-pasting them into another animation as a workaround to this issue.

**Comment by Mickeon** [comment]
Your suggestion is not related to this proposal and you may want to open another one. But if it is of any consolation, [the implementation took steam again](https://github.com/godotengine/godot/pull/93624) and should be good to merge for 4.4
