### ISSUE TITLE
Add a $1/month donator level to the Patreon.

### ISSUE THREAD

**Issue by baphomutt** [godotengine/godot-proposals#3952]
### Describe the project you are working on

Many games and a desire to support the engine.

### Describe the problem or limitation you are having in your project

I am currently a destitute creative and cannot afford to spare $5 a month towards the engine's development. However, I would be able to set aside $1/month (and have been for the past several years).

Currently the description for the $5/month donation level at the Godot Patreon contains:
` Even if just a bit, every contribution makes a difference.`
However, Patreon _does_ allow for levels as low as $1/month, as I have seen many of them in the wild.
As someone who knows that Patreon allows a $1/month level, I must admit I have unfortunately sometimes bitterly thought "every contribution makes a difference, as long as it's above $_x_" anytime I perused the Godot Patreon over the years. And I don't like feeling that, and would prefer to be able to contribute. And in fact I feel there would be more supporters if such a level were added.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a $1/month donation level to Patreon.

A $1/month donator allows more supporters, especially those (like myself) who are unable to set aside the current minimum, which is $5/month.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This proposal is related the Patreon and not the codebase itself, therefore this section of the proposal template does not apply to this proposal.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

If a $1/month level is not added, I cannot afford to monetarily support the engine. I am sure this is the same for many others.

Therefore, it is my belief that a $1/month level being added to the Godot Engine's Patreon will allow many more who are passionate about Godot to support the project.

**Comment by pycbouh** [comment]
> One-time donations via PayPal are also feasible

They can also be recurring.

**Comment by baphomutt** [comment]
Was not aware of what the % was specifically for a $1 level, so do appreciate the clarification on that, and that reasoning does make sense.

> One-time donations via PayPal are also feasible: https://godotengine.org/donate

Thank you, I actually did not know about that donate page!! I'm realizing just now that it is deep in the "More" section on the website..
The Patreon, however, is featured prominently on the Godot homepage (top right), therefore that was the only method of financial support that I was aware of when submitting this proposal. 😅

**Comment by StuartIanNaylor** [comment]
Just on the topic of donations in any discourse or post all the community should have a donation url with tags of who and what.
Doesn't mean there is any dictate with the tail wagging, but allow the community to express who and what and you never know the dog might wag its tail.
Unitary monolithic donation models lose the expression of a purchase one of individual choice and as said tags on the end of a url could easily be collated for metrics even if there is no dictate.

**Comment by baphomutt** [comment]
> The issue with very low donation tiers (below $3) is that transaction fees represent a high percentage of the total donated amount.

I've researched this a bit more, and it appears as if Patreon would only be taking 5% + 10 cents for donations less than $3. It's definitely a slightly higher percentage than for greater donations, but a 15 cent fee is a lot less than I was expecting based on your response. Is receiving 85 cents per dollar donation not reasonable?

**Comment by Calinou** [comment]
> I've researched this a bit more, and it appears as if Patreon would only be taking 5% + 10 cents for donations less than $3. It's definitely a slightly higher percentage than for greater donations, but a 15 cent fee is a lot less than I was expecting based on your response. Is receiving 85 cents per dollar donation not reasonable?

Since you don't receive perks by donating less than $5/month, it doesn't really matter if you donate $1/month or if you donate $5 with a one-time donation. We don't have plans to add perks for amounts lower than $5, as we want to avoid donors from paying lots of fees.

**Comment by akien-mga** [comment]
You can already donate $1/month on Patreon, you can choose the amount.

The available tiers are only suggestions (and thresholds for related perks).

**Comment by Calinou** [comment]
Closing per the above comments.
