### ISSUE TITLE
Add visual feedback when drag and dropping from scene tree to file-system

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#3960]
### Describe the project you are working on

unrelated

### Describe the problem or limitation you are having in your project

Currently you can drag a subtree of the current edited scene to the file-system tab to trigger the "save branch as scene" dialog, with the file explorer starting in the folder you dropped the node in:

https://user-images.githubusercontent.com/71937306/153723485-8c125727-00b2-4d37-b0d6-70d57aa53283.mp4

The problem is however that there is no indication that the file-system accepts such action, making it nearly impossible to discover and making it feel clunky (as you have no real-time visual feedback of which directory you're dropping to).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think that when dragging a node from the scene tab to the file-system tab the currently hovered directory should be somehow highlighted:
![drag_and_drop_highlight_directory](https://user-images.githubusercontent.com/71937306/153724030-399fbadd-187d-4007-8b32-b4728fcaef29.png)

Additionally, there could be a tooltip while dragging to indicate explicitely the action: "save branch as scene". Maybe the text with the node name could become "save DraggedNodeName as scene"?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

it can't

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/58842
