### ISSUE TITLE
Reimplement ability to flip/rotate/modulate individual tiles in a TileMap (as opposed to creating flipped/rotated/modulated tiles in the TileSet)

### ISSUE THREAD

**Issue by seocwen** [godotengine/godot-proposals#3967]
### Describe the project you are working on

A top-down procedurally generated rogue-like.

### Describe the problem or limitation you are having in your project

Godot 4.0 Tilemaps no longer support the flipping and transposition of individual tiles. This feature is useful for reusing assets, preventing resource bloat, and synchronizing symmetrical features. The project I'm attempting to test-port from 3.0 to 4.0 relies heavily on this functionality. Because there's no support for this feature, and my maps are built for it, 4.0 isn't currently a viable option for my existing projects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The way Godot 3.0 handled flipping and rotation was excellent. I suggest adding that part back into 4.0, which is otherwise superior.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I recommend reinstituting the previously existing buttons back on the icon bar of the tilemap editor. The icons for rotate left, rotate right, flip horizontally, flip vertically, and clear transforms would appear next to the other buttons, or become accessible after clicking on a "transform" button.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is an editor issue, not a coding issue.

As for work-arounds, not everyone will need this, but for those of us who do, the alternatives are rather painful. It is possible to make an "alternate tile" with these transforms set. This should theoretically work alright for a small number of individual tiles.

Attempting this for an entire tileset, the result is an unusable mess, especially as there is no way to cleanly match an alternate to its corresponding primary tile. It is far less painful being able to make these transformations as needed on the fly in tilemaps rather than in tilesets. You can't necessarily plan in advance what might need to be flipped, it's impractical to flip everything, and in general, the current layout of the alternatives panel leads to bad organization even if you were to try planning this out. Likewise, with the current alternative tiles panel, you lose the functionality to paint "patches" of tiles because they appear out of their intended ordering.

The thought also occurred to me of making a separate layer and using costum dummy tiles to mark where I'd like transformations, but these changes would be non-obvious in the editor, which is required for design best practices.

### Is there a reason why this should be core and not an add-on in the asset library?

Mostly, because this is re-implementing a 3.0 feature that got lost in the shuffle. In my opinion, an add-on should not be necessary for porting projects to 4.0.

**Comment by groud** [comment]
I don't think bringing them back is worth the trouble. 
Most of the time, if you want flipped tiles, tile alternatives are fine for objects (as you place them once and you are done).
The remaining difficult part is likely about painting ground, but 99% of the cases, this can be handled using the terrain system (there are still some issues there but I hope they will eventually be fixed).

Also, remember that this feature only works for square tilemaps, and that the new TileMap features a lot more different shapes now. So I am not in favor of implementing a workaround specific to this situation.

**Comment by seocwen** [comment]
> Most of the time, if you want flipped tiles, tile alternatives are fine for objects (as you place them once and you are done).

I don't think "most of the time" is a fair characterization. There are diverse workflows for working with art assets. If your tileset only contains right-facing walls and corners, and you flip them to get the the rest, you've just halved your total texture count. And if you do make two corners, you can flip both versions to get that diversity on either side.

What works for objects does not work for walls, and it's certainly not a "place once" fix. The tileset I've been working with is "all wall," because my objects are composed of tiles smaller than themselves so that they can be mixed and matched. This is more like how many SNES games like Chrono Trigger handle tesselation (trees in particular)--which is quite different from the Link's Awakening style tiles I noticed from most of the demos.

Flips would be useful at least for all rectangular sets. Horizontal flips at least would be useful for isometric sets. I don't think it make sense to deny functionality simply because not every use case will require it. Besides, other users of more exotic tiles might surprise you with their creative uses of this feature if it's available.

If there's something I'm missing in terms of the functionality that will be offered through patterns, please do explain.

It's not inconceivable that the alternatives system could work for the use case I'm describing. The best case I can imagine is selecting my entire tilemap, hitting "make alternative," selecting h-flip, and getting an identically laid out copy of the entire tilemap, flipped. This would work, but it would be extremely inelegant for half the tiles used for related objects to appear on opposite sides of the tile palette. And then, if I needed v-flip on top of that, I'd be doubling everything again.

Now that I think about it, the same could hold true for modulate, too, but my actual plan there is to use palette swapping by drawing custom values on a separate layer, which I don't ever expect editor support for. Regardless, IMHO, most of what appears in the alternatives system belongs in the TileMaps, not TileSets.

**Comment by Mickeon** [comment]
I'm not sure about implementing them *exactly as they were*, but I do have to agree that these features are pretty standard for a tile-based... well, anything, and that they will be missed by users making use of them, forcing them to spend plenty of time implementing an alternative that can be considered a mere downgrade for this purpose.

Perhaps, there could a way to set them up in the TileSet without wasting texture space, unlike autotiles, and have them easily accessible through similar shortcuts as the 3.x's existing buttons on the TileMap editor.

**Comment by KingBrainlord** [comment]
Its nice the new system integrates tilesets and tilemaps closely, but it confuses their roles. Tilesets represent the semantics of what a tile is while tilemaps control where and how they're placed and rendered. Flips, transposition, modulation, and z-index concern the latter. Moving the alternatives properties to tilemaps will give the user finer control without needlessly creating new objects.

I've been thinking I'd like to have very gradual, subtle, color shifts in all my tilemaps using modulate, for instance. That would require hundreds, even thousands of tilemap alternatives - or it could just be painting onto the tilemap.

I strongly recommend that this be fixed before the 4.0 release. The new tilemaps are an important breaking change so its important that their design be good.

**Comment by PoisonousGame** [comment]
How to flip the pattern?

**Comment by Mickeon** [comment]
You cannot, in Godot 4.0 as of yet. This is in the milestone, so it will have to be added at some point down the line.

**Comment by jonSP12** [comment]
I was going to post about this issue, but then saw one was already open.
The flip horizontal and flip vertical, was always been present in all tileEditors. Iam constantly being blocked for not being able to use it.

The FLIP TILE may not be usefull, for when someone is working with tiles downloaded from the internet. But when making your own, saving the image with both sides LEFT and RIGHT will take 2x the space in view. This also requires to edit and remake all the tilesets images, and saving them with 2x the memory.

Here's an example of tiles stack togheter, the left side is always diferent from the right
![tileFace](https://user-images.githubusercontent.com/77213594/204488680-3aa9df34-c2e3-4a80-87f1-1807b1c1e40d.png)

another tile using shadows, ( a layer that goes on top of any tile texture )
![tileFaceShadow](https://user-images.githubusercontent.com/77213594/204488856-d8a53ff8-ecf9-40ce-8992-bb0c245a9463.png)

Its not very good, to make all of this stuff facing left and right in the same image...

**Comment by feendrache** [comment]
Are there any updates for this topic? 
I think this feature is really needed

**Comment by Calinou** [comment]
> Are there any updates for this topic? I think this feature is really needed

There is no ETA for features being completed, as contributors are working on a best-effort basis.

**Comment by jonSP12** [comment]
It would be important to have this feature ON, even if it wanst working 100%.
People would be able to go on with their 2D projects in gd4, and the bugs report would flow normally without any worries...
This way all of the time is spent waiting, and gd4 is not being used.

**Comment by zurasuta** [comment]
I'm curious, is this feature going to be implemented? Cause I'd love to have it too.

**Comment by Mickeon** [comment]
Judging by the overwhelmingly positive feedback, yes, and absolutely it should. Not now, perhaps a later 4.x version. No one that I've seen came up with an actual implementation yet, so it may only be 4.1 is we're being cautiously optimistic, or if it's deemed to be a quite urgent feature to have.

**Comment by groud** [comment]
Alright, I guess I need to write a follow up to my previous message. Sorry if it sounded dismissive of the problem, but that was not my intention. It is indeed clear now, considering on my message downvotes, that a lot of people relied on that feature and that it should be brought back one way or another ASAP.

Sadly it's now a bit late for 4.0, but I think it should be easy to bring it back for 4.1.

**Comment by Gnumaru** [comment]
The workflow for flipping and rotating tiles could perhaps be implemented by automatically selecting or creating alternative tiles.

Consider the following workflow:

1. The user selects a tile to paint
2. The user press 'X' on the keyboard
3. The editor searches among the alternative tiles one that is identical to the current except for flip_h property which will have the opposite value of the current alternative
4. If such alternative is not found, it is created.
5. Then, it is selected by the editor.

The same would be done with the other keyboard shortcuts, Z, A and S. This way the users would paint flipped and rotated tiles the same way they did in 3.X, but behind the curtains alternative tiles would be used as it is currently designed.

**Comment by securas** [comment]
I would like to add to the proposal the possibility of flipping tiles via code. This is pretty important for procgen. However, it is unclear to me if it should be discussed here or on a issue.

**Comment by feendrache** [comment]
i recreated the functionality with my Tiled Importer Plugin for Godot 4 with creating alternative tiles for each tile in the tileset and using the alternatives in the imported maps.
But this is only really useable when you import maps from tiled, to use flipped tiles in godot mapmaking this is no alternative

**Comment by jonSP12** [comment]
I would leave the 1000x tiles on screen, and alternate tiles, and let user deal with problem. Iam sure a solution will came up, something like a viewPort that only draws the size of the camera, or something else.

There is a possibility that duplicating the entire tile sheet into 3 or 4 will make things worse. I have a 1 sec delay when changing between levels ( I think its a for loop somewere, might need to pre-load the level scenes )

**Comment by thelordofscrubs** [comment]
As someone who really only writes code, I am very much struggling with importing my project to godot 4 because of this. I relied on tile rotating and flipping for my tilemap, and now that that is no longer available I need to figure out how to flip selections in paint.net, which apparently isnt really possible :/

**Comment by Gnumaru** [comment]
Tiled 1.10 RC

https://github.com/mapeditor/tiled/releases/tag/v1.9.91

Added a godot 4 export plugin

https://github.com/mapeditor/tiled/pull/3550

It handles flipped and rotated tiles by creating 7 variants for each tile in the tileset (3 rotations for the default non flipped tile + 1 horizontally flipped tile + 3 rotations for the horizontally flipped tile).

**Comment by Skrapion** [comment]
I'm the author of the Tiled exporter.

Note that you need to [turn on exportAlternates](https://doc.mapeditor.org/en/latest/manual/export-tscn/) to get the flipping/rotating feature, because I wasn't comfortable with octupling the tileset size by default. I imagine it doesn't have much impact on performance, but actually using the generated TileSet in Godot is very unwieldy with so many alternates.

If there was a way to flip/rotate tiles in the TileMap instead of the TileSet, I would definitely have used that option instead. Or perhaps a way to make an alternate class, which applies the same transformation to the whole sheet, and shows the whole sheet transformed.

**Comment by jonSP12** [comment]
This is the changing levels using PNG images instead of tiles

https://user-images.githubusercontent.com/77213594/234847129-c789b589-118e-40d9-b596-6cb020472729.mov

Using png images instead of tiles the change is instantaneous, it doesnt take any milisecond...

//----------------------//---------//-------------------------------

This is the changing levels using tileMaps made in Tiled exported to godot has *.tcsn

https://user-images.githubusercontent.com/77213594/234847388-bf377fbf-33f1-4076-8b3c-2b1bad93b56b.mov

In here it takes about 1 sec to change between levels, like is processing something....

//-------------------------//------//----------------

the tilesets are no longer has they used to be in the 90's
or later the spectrum 128k era... I could be wrong in this... But has far was i know, The objective was to reduce texture space by reusing some of the textures.

![TEXTUREpAGE](https://user-images.githubusercontent.com/77213594/234847706-29e12b09-c5d1-47dd-9861-5d2f8493f3fa.png)

Now tiles are used has objects with lots of properties, that get instantiated/spawned on screen with the intent of doing completely diferent things,
instead of drawing a level/background faster than a png...
Its a totally diferente thing only the name is the same 'TileMap'
The tileSet in godot like i said previously in my spitefully critical comment, seems to drawing the tiles on the console window then passing them on into the level... 
( totally diferente thing )

.

**Comment by KoBeWi** [comment]
There's PR that implements this feature: https://github.com/godotengine/godot/pull/80144
You can test it using this build: https://github.com/godotengine/godot/suites/15001107777/artifacts/856191715

Note that not all default shortcuts will work until https://github.com/godotengine/godot/issues/80221 is fixed, so you need to rebind them.
Also the PR does not implement per-tile modulate and will not implement it. It's impossible to add given how the tile data is stored.

**Comment by jonSP12** [comment]
- shortcut key (V) doesnt seem to work
- Select a single tile, rotate it (X) paint it on canvas, then select multiple tiles blocks and they are all scrambled ( they appear pre rotated and rotate or flip using shortcut keys )
- the editor keeps crasing multiple times, always after creating ( new node ). I was using MSI afterBurner along with Riva Tuner with max fps set to 60, closed MSI afterBurner Ran the editor again and it seems to be better now.
- I dont know how to turn visibility on for the editor console, but manage to snatch a photo right before it colses when opening a project

![gdERROR](https://github.com/godotengine/godot-proposals/assets/77213594/ed0f578f-5fd9-4323-a48c-9ef88769bad5)

**Comment by KoBeWi** [comment]
Thanks for testing @jonSP12!

> shortcut key (V) doesnt seem to work

I already mentioned that this shortcut won't work. It conflicts with another shortcut in 2D editor; for now you need to bind another key as a workaround.

> Select a single tile, rotate it / flip it (Z) (X) (C) paint it on canvas, then select multiple tiles blocks and they are all scrambled ( they appear pre rotated/flipped and rotate or flip using shortcut keys )

Fixed.

https://github.com/godotengine/godot-proposals/assets/2223172/dc114d77-2b5e-4226-84af-e67b99e6b630

> maybe in the future, add an option for viewing the flipped/rotated duplicates... people using radom generated levels might want to access their ID

I exposed the transform bits in TileSetAtlasSource and documented some example how they can be used. Is that enough?

Other points are unrelated. I'll link an updated build once it's finished.

**Comment by securas** [comment]
Is it possible to flip tiles via gdscript?

**Comment by KoBeWi** [comment]
Yes. You can achieve that by manipulating their alternative tile ID, as described in the example I linked.

**Comment by securas** [comment]
Thanks! I'll check it out very soon.

**Comment by jonSP12** [comment]
I tested the animation with flip/rotation and it works, everything is working...

Problem was... The Tile animation doesnt make much sense, I cant use the tiles i want..?! If i want to animate a tile i have to delete the other tiles to use them has frames. ( This way i cant use them anymore )

Cant an array be used in the editor, and loop that array to animated ?
Ive made this in code, 
but it would be nice to have it this way in the editor, for a normal animation,
the animation has it is now, the user is no longer able to use the tiles that are set has frames....



https://github.com/godotengine/godot-proposals/assets/77213594/731e407f-b344-42f1-952a-b35c923240ed


![animCode](https://github.com/godotengine/godot-proposals/assets/77213594/a83f5085-24f7-4f98-bac5-c4069fefce43)

***********Label****

```
extends Label
@onready var myTile = get_node_or_null("../TileMap");

var font;
var fontSize = 20;

func _ready():
	font = FontFile.new();

func _process(delta):
	queue_redraw();

func _draw() -> void:
	draw_rect( Rect2( Vector2(10, 10), Vector2(250, 50)),  Color.BLACK);
	draw_string(font, Vector2(30, 40), "CURRENT FRAME: " + str( round( myTile.frame1 ) ) , HORIZONTAL_ALIGNMENT_LEFT, -1, fontSize );


```

*********TileMap********

```
extends TileMap

var arrayTile = [ Vector2(6,1), Vector2(7,1), Vector2(8,1) ];

var frame1 = 0;
var speed = 0.5;


func _ready():
	pass # Replace with function body.

func _process(delta):
	if ( frame1 < 3 ):
		frame1 += 1.5 * delta;
		if ( frame1 > 3 ):
			frame1 = 0;
	
	set_cell(0, Vector2(11,6), 0, arrayTile[ frame1 ] );
	#the layer nr ,level coords, tileMap Source, tileMap coords

```
