### ISSUE TITLE
Rework BaseMaterial3D billboard modes for greater flexibility

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#3968]
*Related to https://github.com/godotengine/godot-proposals/issues/3211, https://github.com/godotengine/godot-proposals/issues/3703 and https://github.com/godotengine/godot/issues/58097.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

The current BaseMaterial3D (StandardMaterial3D/ORMMaterial3D) billboarding options are too limited in many scenarios:

- It's not possible to use both Particle Billboard *and* Y billboard at the same time.
- Mesh impostors could be made more convincing by *partially* constraining their billboarding to the Y Axis, and in some cases, making them align to the camera position instead of the view plane.
- For 2.5D games using sprites to represent items or enemies, Y billboarding will make those look flat when viewed from above or below. This can be problematic from a gameplay perspective. Standard billboarding is not always a good fit either, especially for enemies as their feet would appear to be floating when viewed from above or below. Partial billboarding can be a good solution here.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would also be a good opportunity to implement two new billboard options that can be combined with others:

- Move Particle Billboard's functionality (such as flipbook animation) to a separate boolean property.
- Add **Billboard Y Align** (float between `0.0` (default) and `1.0`):
  - `0.0` is the current **Billboard / Particle Billboard** behavior.
  - `1.0` is the current **Y Billboard** behavior.
  - Values between `0.0` and `1.0` will interpolate between the two behaviors. This can be used to create more convincing mesh impostors, especially for vegetation. See the video below for an example.
- Add **Billboard Projection** (enum with values **Align To View Plane** (default) and **Align To Camera Position**):
  - This can result in better-looking impostors at a distance as well, since they will look less "flat" and won't rotate along with the camera.

Here's an example of the vegetation rendering in Trackmania² Canyon. In this game, all vegetation is _always_ rendered as an impostor. The normal mapped sprites and clever billboarding logic manage to make the approximation convincing while racing. Even when using the free camera mode and flying nearby, it still holds up fairly well:

https://user-images.githubusercontent.com/180032/153895888-6e890487-514f-445e-a05b-4625120c5e9c.mp4

By setting the proposed **Billboard Y Align** property to something like 0.5, you could get a similar effect easily.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The new billboard options should also be exposed in Sprite3D and AnimatedSprite3D.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The additional functionality proposed here can already be implemented with custom shaders. However, this proposal also involves compatibility-breaking changes in the interest of greater flexibility.

### Is there a reason why this should be core and not an add-on in the asset library?

This proposal is about reworking the default functionality for better usability.

**Comment by mrjustaguy** [comment]
We should also have a Billboard mode that is user fed an eigenvector around which it is to rotate. This would allow for really easy usage of Quads for things such as Lasers, and would allow for even more flexibility.

**Comment by Calinou** [comment]
> We should also have a Billboard mode that is user fed an eigenvector around which it is to rotate. This would allow for really easy usage of Quads for things such as Lasers, and would allow for even more flexibility.

The issue with this is that you'll need a different vector for every possible orientation of your laser. Therefore, you'd need to duplicate the laser material for every possible orientation, which is bad for performance.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/8367, which is more flexible and addresses billboarding inconsistencies across nodes/resources as well.
