### ISSUE TITLE
Add option to create groups with names in Proyect settings

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#3972]
### Describe the project you are working on

mobile project

### Describe the problem or limitation you are having in your project

The problem is that every time you want to add an enemy to a group, you have to go through the same steps.

I wonder:
Why do I have to do the same steps every time?
Then I thought that I was doing something wrong and that in the project options there is an option to create groups (just like the physics layers option, you assign a name to each layer) and I was not using it, but that option does not exist.

My suggestion.
Enable an option in the project options to create groups so that each scene can be assigned to a predefined group (just like physics layers but with groups).
![Captura](https://user-images.githubusercontent.com/19652075/154039580-dedb6564-f383-487f-9cec-f37f1187ad93.PNG)

So, when you click on "Manage groups" the groups that you predefined in the project options will appear and you only have to select one of them and click on "Add"

![Captura](https://user-images.githubusercontent.com/19652075/154041311-56668779-8701-4bbe-a236-9fe89e357220.PNG)

In this video you can see that I have to go through the same steps every time I want to add an enemy to the "enemigos" group.

https://user-images.githubusercontent.com/19652075/154039250-db82d23f-3c3d-4e75-960d-49d5e73f289c.mp4

I also explained it here:
https://discord.com/channels/212250894228652034/610347507222052867/943080670027218964

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Enable an option in the project options to create and name groups (in the style of physics layers).
This option will save repetitive steps when adding a scene to a group.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

IDK

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure it can be created with an add-on

**Comment by Zireael07** [comment]
Duplicate of https://github.com/godotengine/godot-proposals/issues/3789 ?

**Comment by Torguen** [comment]
Ok, yes, it's a duplicate, it's practically the same.
