### ISSUE TITLE
Allow DirectionalLight3D to inherit modified values from sky_material

### ISSUE THREAD

**Issue by Ophiolith** [godotengine/godot-proposals#3981]
### Describe the project you are working on

A semi-open 1st-person immersive sim

### Describe the problem or limitation you are having in your project

When using sky shaders, PhysicalSky, or any other sky type where the position, energy and colour of the sun is inherited from a controlling DirectionalLight3D, changes that the shader makes to these parameters are not taken into account in direct scene lighting. Without careful 'fudging' of values, this can often look implausible, and inherently cannot be physically accurate. See below for example:

![image](https://user-images.githubusercontent.com/24281932/154260633-70f66e55-2bb7-4d92-8064-6d995746bf7e.png)
This shows a DirectionalLight3D with 0.05 energy, controlling the sun in @clayjohn 's clouds demo shader. Even at very low energy, the light is totally incongruent with the expected brightness and colour of direct lighting from the sun. As the sun inherits its base energy and colour values from the directional light, and is then modulated by values in the shader, it is impossible to get the values to accurately match.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I am by admission not a coder, and am not intimately familiar with how Godot renders a scene, so there may be better ways to do this. However from studying the shader code, there appear to be built-in parameters for adjusting the sun's lighting, which inherit directly from the controlling light, and then can be modified by the shader itself.

Based on this, the simplest solution I can think of would be for there to be an additional toggle added to the DirectionalLight3D node to inherit the final sun values the shader outputs, i.e. 'Inherit Lighting From Sun' or similar. Possibly with a slider to modulate how much the light is affected for artistic control.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Once the final sun energy and colour values are calculated by the shader to be rendered, pass these modified values back to the controlling DirectionalLight3D. In lieu of even decent pseudocode, please find a terrible and no doubt highly inaccurate diagram of how I propose this should work:

![image](https://user-images.githubusercontent.com/24281932/154266960-13f1dc35-c614-40bf-9687-2370cd52b2f8.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If my guesswork is correct, this would ease a lot of lighting headaches for open-world 3D environments, so could potentially be used widely. It also affects a lot of what seem to be hardcoded parameters, so likely could not be scripted around.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a proposed improvement to how Godot handles lighting as a whole and touches parameters that from what I can tell are hardcoded. From what research I have done this would make it difficult, hacky or both to achieve via an add-on, and would be handled in a more elegant and maintainable manner via engine code.

This all of course comes with a caveat that code is not my strong suit, and there may be simpler solutions that I have not considered.

**Comment by clayjohn** [comment]
Very interesting idea! Unfortunately we can't read data back from the GPU as you suggest for two reasons
1. Shaders don't hold on to that kind of data, once they figure out the colour for a pixel, everything else is thrown out
2. Even if we made a special kind of shader that could save extra data, passing data from GPU to the main program introduces a GPU/CPU sync point meaning the GPU will freeze all operations to pass data to the CPU, this would be disastrous for performance. 

That being said, I'm sure we can solve your problem another way. It sounds like your real issue is with some of the tricks I used in the cloud demo rather than how sky shaders work in general. For example I multiply the sun color by the color of the atmosphere to add in red and orange during the sunset. I did that for artistic effect for the demo, there is no reason you have to do the same in your game. Instead you could change the colour of the sun by changing the colour of your directional light.

**Comment by Ophiolith** [comment]
Hey, thanks for taking the time to respond @clayjohn  - I'm pretty unversed in how data is passed to the GPU and back but that makes total sense that readbacks like that are extremely costly.

> That being said, I'm sure we can solve your problem another way. It sounds like your real issue is with some of the tricks I used in the cloud demo rather than how sky shaders work in general. For example I multiply the sun color by the color of the atmosphere to add in red and orange during the sunset. I did that for artistic effect for the demo, there is no reason you have to do the same in your game. Instead you could change the colour of the sun by changing the colour of your directional light.

In terms of how sky shaders work overall, I was using your demo as an example mainly due to me losing a fair bit of time to it recently, but PhysicalSky also has this issue, and isn't as readily 'hackable' as a regular material. I agree that having the actual colour shifts happen directly on the light is a far more elegant solution - would something like having a 'Sunlight', distinct from a regular directional light, with parameters to adjust the colour based on rotation that explicitly _does not_ pass these values to the shader be more feasible? Or, simply refactor PhysicalSky to not observe atmospherics-based hue-shifts?

I'm somewhat outside my wheelhouse here in terms of how something like that would be implemented, but I appreciate your thoughts on this!

**Comment by clayjohn** [comment]
>  I agree that having the actual colour shifts happen directly on the light is a far more elegant solution - would something like having a 'Sunlight', distinct from a regular directional light, with parameters to adjust the colour based on rotation that explicitly does not pass these values to the shader be more feasible? Or, simply refactor PhysicalSky to not observe atmospherics-based hue-shifts?

I have wondered about that too. I think in Unreal they go so far as to tie Sun and Sky into a single object. 

Another option we have that might be more the "Godot way" of doing things is to add a setting to make it so certain DirectionalLights are not included in the Sky (discussed here https://github.com/godotengine/godot/issues/53985). That way you could use two DirectionalLights, one in "sky only" and the other in "scene only" and then you can tint the brightness or color of one without impacting the other.
