### ISSUE TITLE
Accessing big files (greater than ~2GB) requires changing the File API to use 64-bit integers

### ISSUE THREAD

**Issue by MrMrBlackDragon** [godotengine/godot-proposals#400]
**Describe the project you are working on:**
I want to make a file manager, for making it easier to arange data.

**Describe the problem or limitation you are having in your project:**
Godot is not able to deal with data bigger than 2^31 -1 // (~2GB) bytes.  So I can't seek behind that point or get the size (wich is just equal to seek_end() -> get_position()). So it's not possible to store or read data behind this value. And working with files beeing that big is very likely espacialy when managing "zip" folders or movies. I see no way to avoid that problem.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It would be possible to accese the size of files bigger than ~ 2GB and data behind that point, e.g for compressing purpose. In Godot 3.2 it even it's not possible anymore to get the last date due the size limitaion.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
For e.g accesing the file's size:
`var file : File = File.new()`
`var err : int = File.open(Path)`
`File.get_len()`

**Describe implementation detail for your proposal (in code), if possible:**
I see no solution in GDCode. I googled a lot to find a way, but it's just not possible to overcome the problem

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Here goes the same as for the last question: I see now way in native Godot

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is for internal use in the engine only.

**Comment by Calinou** [comment]
This will be handled by https://github.com/godotengine/godot/pull/27247, but since it breaks compatibility, it's on hold until 4.0.

**Comment by MrMrBlackDragon** [comment]
Oh, I didn't saw that issue because I didn't knew that was because of the 32 bit system to read data. :)

**Comment by pinkylabs** [comment]
I have played around the 2G problem under x64 windows, made minor playground changes in the file_access_windows.cpp. The .pck export went well and the project started ok for now...

[Godot_v3.2.3-stable-windows-bigfile.diff.txt](https://github.com/godotengine/godot-proposals/files/6003313/Godot_v3.2.3-stable-windows-bigfile.diff.txt)

**Comment by RandomShaper** [comment]
You may want to have a look to this old PR of mine. It's of course outdated, but I think the changes to the file system classes are still relevant: https://github.com/godotengine/godot/pull/27247

It also can serve as a guide about other parts of the engine that can benefit.

**Comment by pinkylabs** [comment]
@RandomShaper I skimmed thru your commit. The move to switch to 64bits for file i/o api was a very good! I was happy that "it only needed" to fix file_access_windows.cpp. I'm not brave enough to make a pull request yet, because It was not tested/used enough. I also did not even try to compile for win32 at all...

**Comment by akien-mga** [comment]
This is now handled in https://github.com/godotengine/godot/pull/47254.
