### ISSUE TITLE
Make move_and_slide_with_snap() floor_max_angle 46 degrees instead of 45 degrees. 

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#402]
**Describe the project you are working on:**

Generic platformer with slopes

**Describe the problem or limitation you are having in your project:**

Currently move_and_slide_with_snap() floor_max_angle is 45 degrees this is not ideal. We use move and snap so character snaps to the floor in platformers. In majority of platformers slops are either 30 or 45 degrees. If someone is using move_and_slide_with_snap majority of time they will want to snap to both slopes. 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

By Increasing this slightly we will achieve what people want for 90% of cases without needing to override default values for anything. 

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

https://youtu.be/9l-tf97z2bg?t=868 example of how it works when overriden 

**Describe implementation detail for your proposal (in code), if possible:**

I am unsure precisely but my understanding is that we will need to to edit `physics_body_2d.cpp` file 

`ClassDB::bind_method(D_METHOD("move_and_slide_with_snap", "linear_velocity", "snap", "up_direction", "stop_on_slope", "max_slides", "floor_max_angle", "infinite_inertia"), &KinematicBody2D::move_and_slide_with_snap, DEFVAL(Vector2(0, 0)), DEFVAL(false), DEFVAL(4), DEFVAL(Math::deg2rad((float)45)), DEFVAL(true));`

into 

`ClassDB::bind_method(D_METHOD("move_and_slide_with_snap", "linear_velocity", "snap", "up_direction", "stop_on_slope", "max_slides", "floor_max_angle", "infinite_inertia"), &KinematicBody2D::move_and_slide_with_snap, DEFVAL(Vector2(0, 0)), DEFVAL(false), DEFVAL(4), DEFVAL(Math::deg2rad((float)46)), DEFVAL(true));`

probably do the same with `physics_body.cpp`

I am unsure what else should be change as I have limited understanding which files need updating after that however with some guidance from experienced person as to what files need editing I would like to attempt this. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It will be used often in any platform game with slopes. It can be easily worked around by manually setting floor_max_angle to 46 degrees but it's a pain and 99% of a time it's what user wants anyway.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It's a core feature being modified.

**Comment by MCrafterzz** [comment]
Why not? If it's allows for more game mechanics and doesn't prevent anything else.

**Comment by aaronfranke** [comment]
To clarify for the record, this issue was fixed, but not in the way this proposal... proposes :)
