### ISSUE TITLE
Godot Editor personalized marks

### ISSUE THREAD

**Issue by CptnRoughnight** [godotengine/godot-proposals#404]
Hi, 
I'm working on a larger project and would like to set brands in the editor like "#TODO:". 
These should then be displayed in a window and the code called with a click.

 Optimally, you can still personalize this literal and have these brands displayed in the display window with text search.

**Comment by groud** [comment]
Please fill in the issue template, it's mandatory.

**Comment by Jummit** [comment]
https://godotengine.org/asset-library/asset/253

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/6371.
