### ISSUE TITLE
Add a way to filter nodes by type in the Scene tree dock

### ISSUE THREAD

**Issue by d4rkd0s** [godotengine/godot-proposals#4040]
### Describe the project you are working on

Fish & Bubbles (available on Steam)
https://store.steampowered.com/app/960070/Fish__Bubbles/
A 2d game where you have a fish tank and try to grow it.

### Describe the problem or limitation you are having in your project

I'm looking to edit a bunch of nodes, of a certain type.

However, it appears there's no way to filter by node type in the scene search...

![image](https://user-images.githubusercontent.com/2348814/154809982-8d40f99e-7553-462c-aa38-89a516b47807.png)

![image](https://user-images.githubusercontent.com/2348814/154810293-4bc507ab-d293-482e-b64a-fd6bf4718203.png)

You can filter by "name" for me, this kind of works, I then unselect the ones I don't want after highlighting a list of them.

![image](https://user-images.githubusercontent.com/2348814/154810066-76fe2848-1668-405e-90ce-831647608e71.png)

It seems like this should be a small snippet of code to add to filter by node type instead of name. I couldn't find it on the docs.

I searched for other proposals like this, but couldn't find any. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It seems like the feature was originally added in 2016 https://github.com/godotengine/godot/issues/2176
This is a nice small improvement in my opinion to the already useful search/filter tool on the Scene tab.

Since Godot has powerful multiselect/multiedit features when selecting nodes of the same type. 
**This would pair powerful and nicely with that.**

Here are a few examples:

- Selecting all Sprites to adjust Modulation/Color
- Selecting all Lights in your game to adjust Colors (they may be all over your tree structure)
- Selecting all Labels to adjust Font/Color if you're not using Themes

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's a mockup of what I would think it would do/look like,

![image](https://user-images.githubusercontent.com/2348814/154810474-3e670d65-2821-4555-9179-11af465fffd4.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The workaround depending on the scene tree can be brutal. For me, I had about 20 nodes, so it was a time saver of 10-15 seconds. But the code change seems small (I'd love to hear a GD dev's feedback on that area). 

### Is there a reason why this should be core and not an add-on in the asset library?

So I wanted to introduce this proposal, as this seems helpful for many other use cases since Godot has the powerful multiselect/multiedit features when selecting nodes of the same type. (See my examples above under "describe the feature")

**Comment by Calinou** [comment]
My issue with `type:` filters is that they tend to not be very discoverable, even if you add a tooltip for them. Changing the placeholder to mention `type:` would be possible, but it would most likely only be visible if you make the Scene tree dock wide enough to see the entire placeholder.

Something like `Filter nodes (by name or type:Node)` would be too long already.

**Comment by fire** [comment]
I recall that visual studio code uses the search without `>` for this purpose. `>` is the command palette search.

**Comment by MrBBBaiXue** [comment]
Hi. I've made a PR for this (godotengine/godot#58362), please try it and give me your suggestions!

- [ ] Acutally I'm new to the code and don't know how to dynamically change the placeholder.
- [ ] Maybe we can add other filters keywords like "subscene:" or something in the future?

**Comment by Mickeon** [comment]
> My issue with `type`:-style filters is that they tend to not be very discoverable, even if you add a tooltip for them 
> A placeholder like Filter nodes (by name or type:Node) would be too long to fit within the default Scene tree dock width already.

I don't know how hard it would be to implement such a thing considering the entire editor is built with Control nodes, but what about right-clicking on the search window or clicking the Lens Icon to display additional search options?

![image](https://user-images.githubusercontent.com/66727710/155119711-83f16c96-45d5-44ba-beb6-ae05e5d8f805.png)
Selecting "Filter by Type" would just write "`type:`" and bring the caret to the end of the line.

It could be easy to maintain and expand upon with more search options, but I'm not sure it improves discoverability. What it would do is help users that cannot memorise every possible filter have a reference point, akin to most keyboard shortcuts being available on dropdown menus, as well.

**Comment by fire** [comment]
Since Godot Engine 4 has a command pallete.

Can't we be like Visual Studio Code and use?  `> command` and `Node/Bullet" to seearch?

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/58377.
