### ISSUE TITLE
_ready function doesn't call when the script is extended extends.

### ISSUE THREAD

**Issue by M77mdsD** [godotengine/godot-proposals#4085]
### Describe the project you are working on

I'm working on a game that has an Actor that contains some of the movement functions.

### Describe the problem or limitation you are having in your project

When I tried to create a script and call it Actor and write a `_ready` in it and extended it in the player script and run the game, The `_ready` function in the Actor script didn't call and the only one called is the one in the player script (That wasn't the case in Godot 3).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think it will be better to call every copy of a function when extends.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
(in Actor.gd)
class_name Actor
entends Node2D

func _ready() -> void:
     play()

func play() -> void:
     print("1")

(in Player.gd)
entends Actor

func _ready() -> void:
     play_again()`

func play() -> void:
     print("2")`

func play_again() -> void:
     print("3")
```

This will print 1, 2, 3 in the same order. What happened is that the `_ready` function in the Actor script is called and after that the 'play' function and when called the 'play' function it ran the code in the Actor first and then the player and the same for `_ready` function in the player script. This will also will work for the functions that will return a value but it will just return the last value ( the return functions from the extended script will just be for starting the extender code). This will give an error if the function in every script has the same arguments and the same output.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

For a thing like the `_ready` function, it will be easy to solve by just using the 'ready' signal itself. but I don't know how to make it for `_physics_process` function other than calling a signal from it.

### Is there a reason why this should be core and not an add-on in the asset library?

This feature will be useful when you want to write more code in the same function for a lot of the scripts that will extend from another script. Like maybe when you for example want to write more code in the `_ready` or `_physics_process` but from an extended script or even add more code to the scripts that you made like for example adding more code to the 'attack' function for every enemy and more and more things.

**Comment by SilencedPerson** [comment]
I am not sure about this but this sounds like the intended change in Godot 4.0
now you have to call super() inside the function to call it's overridden version.

**Comment by KoBeWi** [comment]
As commented above, just use `super()`. It's the equivalent of `.some_function()` (i.e. calling function from parent class) in 3.x
This problem is covered by #3936, so closing.

**Comment by M77mdsD** [comment]
Thank you, It worked!

**Comment by M77mdsD** [comment]
I hope also you update the latest online docs as possible because it has both the old and the new code or just make a new 4.0 one.

**Comment by Calinou** [comment]
> I hope also you update the latest online docs as possible because it has both the old and the new code or just make a new 4.0 one.

Can you link to the page where you found the documentation in question? Most of the documentation upgrade work hasn't started yet, so it will take a while for documentation to be fully ready for 4.0.
