### ISSUE TITLE
Restore optional pivot based sorting with offset

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#4099]
### Describe the project you are working on

Various VFX

### Describe the problem or limitation you are having in your project

Render priority works great for global objects, but very poorly for collection of particle systems (VFX).

Using the render priority of the material would make it so that two effects that make use of it, spawned in different part of the map, would intersect in funny ways
See video below for practical example

https://user-images.githubusercontent.com/7917475/155396744-1bf5cd10-1a95-482c-adbb-89b7f725ec2a.mp4

.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rendering objects with pivot+sorting offset would allow to define a spatial aware rendering order for particle system.
The renderer would calculate the rendering order by sorting object by distance from the camera, but in this case to that distance it would add the sorting offset (which is used only for the purpose of this calculation)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Make sorting based on AABB center default but optional, with another option for pivot+fudge

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Can't be worked around as it is internal of the renderer

### Is there a reason why this should be core and not an add-on in the asset library?

See above

**Comment by neikeq** [comment]
I don't know if I understand well this proposal, but godotengine/godot#59404 among other things implements a depth offset property in `GeometryInstance3D`. Can you check if this is what you needed (or in part)?

**Comment by akien-mga** [comment]
Implemented for 3.6 by https://github.com/godotengine/godot/pull/63040.

Still needs an implementation for 4.0 too.
