### ISSUE TITLE
En-masse modification of ArrayMesh vertices in one shot

### ISSUE THREAD

**Issue by slapin** [godotengine/godot-proposals#41]
**Describe the project you are working on:**
I work on character customization system. Some small subset of it can be seen on 
https://github.com/gamedev-kindness/make-target - just hit F5, and push Generate and run. Just wait 10 minutes or so (depends on computer power) and the editor with sliders will show up.
(need master branch)

**Describe how this feature / enhancement will help your project:**
That will help a lot, as there is no good mechanism to modify mesh fast en masse, so that lots of vertices are updated. GDScript loop is quite slow, it takes up to 10 seconds to update mesh sith 20K vertices.

**Describe implementation detail for your proposal (in code), if possible:**
I'd propose implementation like the following:
```c++
void apply_delta(Array array);
```
where array is all changed items deltas, same format as with other ArrayMesh arrays. Should require mesh to have index; should update only selected indices.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be implemented in GDScript but it is very slow. See https://github.com/gamedev-kindness/make-target/blob/6560f6ca7d3aca815ea94016e8b37ffef9ceb243/map_test.gd#L32

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is small things and aligns nicely with the rest of ArrayMesh function.

**Comment by clayjohn** [comment]
We discussed this at today's proposal review meeting. The consensus was that there are already built in solutions that should work better for this use case. For quick updating of a mesh at run time, [ImmediateMesh](https://docs.godotengine.org/en/latest/classes/class_immediatemesh.html) will be much more efficient than updating an entire ArrayMesh. 

If you are only updating a few vertices and are doing updates infrequently [ArrayMesh.surface_update_attribute_region](https://docs.godotengine.org/en/latest/classes/class_arraymesh.html#class-arraymesh-method-surface-update-attribute-region) can be used (note, this overwrites positions, it does not apply a delta like in the proposal).

The primary problem here is that Godot does not store a copy of the Mesh behind the scenes. When a mesh is loaded, the data is passed to the GPU and then forgotten from the CPU. Maintaining a copy of the mesh in the RenderingServer would waste a lot of memory. This proposal would require Godot to either load the mesh information from the GPU each time the function is used, or to store a copy of the mesh in the RenderingServer to apply these modifications too. Either case is likely to be inefficient and complex.
