### ISSUE TITLE
Add Environment properties to make fixed and volumetric fog not affect sky rendering

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#4102]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Fog rendering in Godot 4.0 always affects the sky rendering. This may not always desired, especially when you are using fog as an atmospheric effect (without intending it to be used for [open world fog fading](https://github.com/godotengine/godot-proposals/issues/3429)). For fixed (non-volumetric) fog, setting Aerial Perspective to 1 will let you see the background sky again, but it has a performance cost.

In comparison, fog in Godot 3.x never affects sky rendering.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to make fog rendering not fully affect sky rendering, so that the background sky can still be partially visible.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add **Fog Sky Affect** and **Volumetric Fog Sky Affect** properties to Environment. By default, both would default to `1.0`. If set to `0.0`, then fog rendering will not affect the sky at all. Intermediate values will only partially affect sky rendering.

I have a WIP pull request implementing this: https://github.com/Calinou/godot/tree/environment-fog-add-sky-affect

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as this is core rendering functionality (implemented in the sky GLSL shader, which is not user-overwritable).

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by clayjohn** [comment]
Keep in mind, sky shaders have a ``disable_fog`` render mode and they can override the fog value using the ``FOG`` built-in. This allows the sky to show through the fog even if the fog is quite thick.

**Comment by Calinou** [comment]
> Keep in mind, sky shaders have a `disable_fog` render mode and they can override the fog value using the `FOG` built-in. This allows the sky to show through the fog even if the fog is quite thick.

I see, maybe `disable_fog` should be exposed in the inspector for the various default Sky resources (like https://github.com/godotengine/godot/pull/55551)?

**Comment by clayjohn** [comment]
@Calinou I think thats the way to do it if this is desired! We could also expose the FOG builtin as a uniform as well if users desire it.

**Comment by mrjustaguy** [comment]
Having that option is very much desired, it greatly increases the flexibility of the fog and is very straight forward.

**Comment by clayjohn** [comment]
Related to this proposal, I noticed that the current dependency on z-far distance also breaks when using reflection probes as the z-far distance changes between probes. Unless you set the probe's ``max_distance`` to be the same as the camera's z-far you end up with a different amount of fog between the sky and the reflected sky.
