### ISSUE TITLE
physics body network replication

### ISSUE THREAD

**Issue by CrezyDud** [godotengine/godot-proposals#4103]
### Describe the project you are working on

multiplayer game

### Describe the problem or limitation you are having in your project

i wanted some in-engine fast physics body replication
many people can benefit from this

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

an integrated way could be fast and light on the network

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

like a bool for physicsbodies

### If this enhancement will not be used often, can it be worked around with a few lines of script?

haven't found a way yet

### Is there a reason why this should be core and not an add-on in the asset library?

this would be so much faster than doing it in gdscript

**Comment by Calinou** [comment]
This was already implemented in 4.0 by https://github.com/godotengine/godot-proposals/issues/3459. This can't be backported to `3.x` as it relies on backwards-incompatible changes.
