### ISSUE TITLE
Add an height fog orientation property to Environment

### ISSUE THREAD

**Issue by Toshiwoz** [godotengine/godot-proposals#411]
**Describe the project you are working on:**
https://digitalki.itch.io/mars/
A 3D mobile game, where you colonize Mars. It has a view where you see from a classical RTS view your units, bases, etc.

**Describe the problem or limitation you are having in your project:**
As it is a game for mobile I'm using GLES2. And I wanted to have a fog effect similar to the game "surviving mars", where the fog is both height and depth.
![image](https://user-images.githubusercontent.com/21297356/73225340-564cbe00-413a-11ea-87db-3e501a15f9db.png)
And in particular something like this:
![image](https://user-images.githubusercontent.com/21297356/73226240-55695b80-413d-11ea-8e37-74c84f7b1329.png)
The problem in my case is that the planet is rendered on a sphere, so the axis where the fog should grow is not always the Y axis. As it is possible to orient the sky vector with the procedural sky it would be nice to be able to do the same with the height fog.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The feature I'm requesting is the same feature procedural sky have, a vector that determines the sky orientation. Being able to change it with GDScript, I'll be able to load the part of the planet I want with the correct height fog orientation.  Having a cheap, but cool effect on my game.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/21297356/73227876-f6a6e080-4142-11ea-965b-b214fb9219af.png)

**Describe implementation detail for your proposal (in code), if possible:**
I have no idea how to do it with GDScript.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so, I wish it would be possible.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it can be applied in many other kind of games, and would be part of WorldEnvironment.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2261 – note that this may already be feasible thanks to https://github.com/godotengine/godot/pull/41415
.
