### ISSUE TITLE
Godot 3.x and 4.x - Include in AStar2D the possibility to check if a connection is unidirectional or bidirectional, making it works the same as the 3D version of AStar.

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot-proposals#4142]
### Describe the project you are working on
A 2D adventure.

### Describe the problem or limitation you are having in your project

At the moment, there is no way to check if a connection between two points is bidirectional or not in AStar2D, unlike what happens in the 3D version of AStar.

AStar2D:
https://docs.godotengine.org/en/latest/classes/class_astar2d.html#class-astar2d-method-are-points-connected

![image](https://user-images.githubusercontent.com/25422687/156218647-3eeec173-6b76-41fc-9bf7-575825422d6d.png)

AStar(3D):
https://docs.godotengine.org/en/latest/classes/class_astar.html#class-astar-method-are-points-connected

![image](https://user-images.githubusercontent.com/25422687/156218762-85fc6d45-4de7-490c-b5df-e0de3a5294a0.png)

This happens in godot 3.x and 4.x.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The goal is to give AStar2D the same possibility to check if a connection between two points is bidirectional or not as in the 3D version of AStar.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Including a third argument in the `are_points_connected` to check if the connection is bidirectional.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, the only moment that you will know if a connection is uni or bidirectional is when creating the connection or with not simple workarounds.

### Is there a reason why this should be core and not an add-on in the asset library?

Because there is already a 3D version of this feature and the workarounds are not easily implemented.

**Comment by Calinou** [comment]
This may be an oversight in the AStar2D port (which uses the 3D implementation behind the scenes). Feel free to open a pull request for this :slightly_smiling_face:

**Comment by theraot** [comment]
> This may be an oversight in the AStar2D port (which uses the 3D implementation behind the scenes).

The bidirectional feature was added after AStar2D. See https://github.com/godotengine/godot/pull/30556 - The oversight was not adding it to AStar2D at the same time.

> Feel free to open a pull request for this 🙂

Don't mind if I do.
