### ISSUE TITLE
Glitchy visuals in 3d editing window

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot-proposals#415]
![editproblem](https://user-images.githubusercontent.com/53994293/73357233-f81ef880-4269-11ea-8d6b-37960f802f52.gif)

**Describe the project you are working on:**
I'm working on a puzzle game about rotating things

**Describe the problem or limitation you are having in your project:**
It just bugs out when I'm zoomed in and rotating in the editing window

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It would allow me to view my project in a normal way in the editing window.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Idk what the issue is

**Describe implementation detail for your proposal (in code), if possible:**
Don't know why this is happening

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it presumably effects other people with the same problem

[Gater.zip](https://github.com/godotengine/godot-proposals/files/4127968/Gater.zip)

If you click on any scene with assets in it, and view it in the 3d editor it will do the bug (or at least on my computer)

**Comment by Zireael07** [comment]
This is a bug, not a feature proposal - go back to the main engine repo ;)

**Comment by lukostello** [comment]
sorry I only saw the one button
