### ISSUE TITLE
Make EditorSpinSlider label color a theme property

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot-proposals#4154]
### Describe the project you are working on

I'm working on implementing this proposal (https://github.com/godotengine/godot-proposals/issues/3800). In the current stage I'm creating it as a plugin in GDScript, which I'll then convert to C++ when it's done.

### Describe the problem or limitation you are having in your project

It isn't possible to change the label color of an EditorSpinSlider. EditorSpinSlider has a `set_custom_label_color()` method which is used internally, but since it isn't exposed to GDScript it can't be used by plugins. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add two new theme properties for EditorSpinSlider label color: `label_color` and `read_only_label_color`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I already have a working version of this. Here's an example with two EditorSpinSliders with custom label colors:
![image](https://user-images.githubusercontent.com/67974470/156698166-6509bd4e-cc5f-4393-b0af-cb6dd5fd2284.png)

```gdscript
editor_spin_slider.add_theme_color_override("label_color", get_theme_color("property_color_x", "Editor"))
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, there is no way to change an EditorSpinSlider's label color outside of the engine's C++ code.

### Is there a reason why this should be core and not an add-on in the asset library?

This functionality already exists in core; this is just a matter of exposing it to GDScript.

**Comment by Calinou** [comment]
Reopening, as the associated PR hasn't been merged yet.
