### ISSUE TITLE
Add an AudioServer property to force mono audio playback

### ISSUE THREAD

**Issue by dylanjaide** [godotengine/godot-proposals#4159]
### Describe the project you are working on

Simple Godot game

### Describe the problem or limitation you are having in your project

A play-tester has requested we add an accessibility option to disable stereo sound (see [this Game accessibility guidelines page](https://gameaccessibilityguidelines.com/provide-a-stereomono-toggle/)). With positional audio nodes or panning, this is possible to achieve purely through code. However our game makes heavy use of .wav and .ogg audio files which are already stereo.

I raised this issue in the Godot discord server, where I received help from @ellenhp. While there does exist a "mono" checkbox which can be selected at import-time, it seems that there is currently no way to toggle this at run-time for stereo audio files using a standard `AudioStreamPlayer` node.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a stereo/mono toggle option to `AudioStreamPlayer` that can be toggled at runtime. Alternatively, add a new `AudioEffect` that does the same thing, but which could be applied to an audio bus instead.

AND/OR

Add a global option in the Audio section of project settings that will filters the audio of the entire project to be made mono.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The global option under project settings could easily be toggled at run-time with something like `ProjectSettings.set_setting("audio/enable_mono_output", true)`. This would make implementing this accessibility feature in future games as easy as adding a couple of lines of code.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Following the discussion had in the Discord, it appears that there is currently no way to achieve this.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about adding an accessibility feature, which should be considered a core part of creating games, and not an optional extra.

**Comment by Calinou** [comment]
> The global option under project settings could easily be toggled at run-time with something like ProjectSettings.set_setting("audio/enable_mono_output", true). This would make implementing this accessibility feature in future games as easy as adding a couple of lines of code.

Most project settings are not read at run-time for performance reasons. Instead, a property to AudioServer should be added to toggle mono output.

By the way, it might make more sense to expose an enum property with the following options:

```
MIX_OUTPUT_MONO
MIX_OUTPUT_STEREO
MIX_OUTPUT_5_1
MIX_OUTPUT_7_1
…
```

This way, this also allows for toggling 5.1/7.1 support.

**Comment by dylanjaide** [comment]
> Most project settings are not read at run-time for performance reasons. Instead, a property to AudioServer should be added to toggle mono output.

This makes sense, thanks for correcting this! I've only made a couple of small games with Godot so far, so I'm not massively familiar with the engine.

I think that it wouldn't be a problem if sounds from only one channel became quieter in the final mono mix, although I'm not very familiar with the mechanics of mono downmixing either. Perhaps if there are a few alternative downmixing methods, it might be possible to have an additional enum for this so people can choose between them?

**Comment by ellenhp** [comment]
Instead of adding a property to a player that you have to set for every single player, what if we added a Downmixer AudioEffect that progressively turned multi-channel audio into mono as you tweak a strength parameter from 0 to 1?

**Comment by Calinou** [comment]
Sounds good to me.

**Comment by ellenhp** [comment]
I implemented what I suggested in https://github.com/godotengine/godot/pull/58823

It seems to work but I'd appreciate if someone could give it a quick test, especially since I don't have headphones so judging stereo panning on my laptop speakers is difficult.

This has lots of use-cases. In addition to accessibility like @dylanjaide mentioned this is really nice for people with concerns about Godot's default stereo panning intensity.

**Comment by Calinou** [comment]
This was indirectly implemented by https://github.com/godotengine/godot/pull/58841 in 4.0 and https://github.com/godotengine/godot/pull/64579 in 3.6. You can set the panning strength to `0.0` in the project settings or at run-time, which will make audio attenuation still work but panning will not be directional *at all*.
