### ISSUE TITLE
Allow dragging a node from the scene tree to NodePath export in inspector

### ISSUE THREAD

**Issue by 2nafish117** [godotengine/godot-proposals#4165]
### Describe the project you are working on

This is applicable to any project that uses NodePath exports.

### Describe the problem or limitation you are having in your project

I have a lot of nodes in a main level scene, this makes it difficult to select the target node for a nodepath in the new window that pops up.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow dragging a node from the scene tree to NodePath export in inspector. It reduces the number of clicks the user has to do and potentially not having to search the target once again from the nodepath window.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When i drag a node from the scene tree to a NodePath export, it should set the NodePath as the path to that node. 
Currently the inspector switches to the properties of the node you drag immediately on mouse button down, instead the properties of the new node can be shown on mouse button up, and allow the user to drag the node to the NodePath.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, i dont think a script/addon can solve this issue.

### Is there a reason why this should be core and not an add-on in the asset library?

It improves the usability of the editor.

**Comment by Calinou** [comment]
This is already implemented in 3.5beta1 and 4.0alpha: https://github.com/godotengine/godot/pull/55761

**Comment by 2nafish117** [comment]
Oh, this is good. Any reason why it was decided to have to have to hold `Alt` instead of the inspector showing the dragged nodes properties on mouse up?

**Comment by Calinou** [comment]
> Oh, this is good. Any reason why it was decided to have to have to hold `Alt` instead of the inspector showing the dragged nodes properties on mouse up?

Implementing this would require a lot more work, as selection in the scene tree dock would need to be separated from the inspector editor.

**Comment by KoBeWi** [comment]
Alternatives for preventing inspector switching are discussed here: https://github.com/godotengine/godot/issues/39539
