### ISSUE TITLE
Improve the Ctrl + K shortcut's comment line toggling behavior

### ISSUE THREAD

**Issue by derac** [godotengine/godot-proposals#417]
**Describe the project you are working on:**
I'm working on a multiplayer game for 4+ people in which players get a phrase and draw it, then "pass" the drawing to the next player, who writes a word describing the drawing. This continues for the rest of the players, then the players view the resulting assets, possibly save them, laugh, you get points for making a drawing which the guesser gets the correct phrase from, guessing the correct phrase, having your phrase go from start to finish without the guess changing and so on.

**Describe the problem or limitation you are having in your project:**
When using Ctrl+k to quickly comment - I find that when I have two lines together and I am quickly testing between them, what I really want to do is select both and hit ctrl, causing both lines to toggle between the comment state. The current behavior requires selecting the first desired line(s), hitting the hotkey, then selecting the second desired lines and hitting the hotkey again. This ends up taking more than twice as long compounded by the many times this happens over time.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Rather than two actions, as described above, the functionality

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Starting with the below code:
```
#		draw_pen(history[-2], history[-2].size() - 1)
		draw_brush(history[-2], history[-2].size() - 1)
```

The current process is:
1. select both lines
2. hit ctrl+k
3.
```
##		draw_pen(history[-2], history[-2].size() - 1)
#		draw_brush(history[-2], history[-2].size() - 1)
```

My proposal is:
1. select both lines
2. hit ctrl+k
3. a commented line becomes uncommented and an uncommented line becomes commented
```
		draw_pen(history[-2], history[-2].size() - 1)
#		draw_brush(history[-2], history[-2].size() - 1)
```

**Describe implementation detail for your proposal (in code), if possible:**
```
for line in selection:
    if line is comment:
         line.is_comment = false
    else:
         line.is_comment = true
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I believe it would be used often, the obvious counterpoint to changing this functionality is that someone may want to comment a large select of code which itself has comments in it, however this can easily be achieved with the ''' multi-line comment syntax.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a basic workflow improvement which anyone who uses ctrl+k would benefit from.

**Comment by Calinou** [comment]
> however this can easily be achieved with the ''' multi-line comment syntax.

GDScript treats those as multiline strings and not as actual comments. This means they will be evaluated as standalone expressions by the parser.

**Comment by golddotasksquestions** [comment]
I use # in many different ways. If your proposal would be implemented, I could not use the versitility any more.

```
#func _on_state_changer_timeout():
#        $state_changer.wait_time = rand_range(1.0, 5.0)
#        #state = randi() %3
#        state = STATE_ATTACK
#        facing = ["left", "right", "up", "down"][randi()%3]
#        pass # Replace with function body.


func _on_hurtbox_area_entered(area):
        if state != STATE_DIE and area.name == "player_sword":
                hitpoints -= 1
                var pushback_direction = (global_position - area.global_position).normalized() #*5000 #try 3000
                move_and_slide( pushback_direction * 5000)
                #state = STATE_HURTING
                state = STATE_HURT #check if this is consistent with other states
                $state_changer.start()
#                if hitpoints <= 0:
#                        $state_changer.stop()
#                        state = STATE_DIE
```
Ctrl+K mostly for blocks of code and sometimes for single lines, to "deactivate" them. Mostly when rewriting or as reference.
The # right at the beginning of the line (#state = STATE_HURTING) indicates to me this line is something very temporal. I only do this with single lines or at max two. I will try to run the code and probably remove or activate it again right after.
The # in between a line (#*5000) I use when I have a value that I know that works, and I don't want to throw it out, but try other stuff without having to duplicate the whole line.
The # at the end (#try 3000) is a classic comment regarding that specific line.

The current implementation allows me to select any block of code, regardless if it already has comments or not and "deactivate" is just by hitting Ctrl+K.
This works, because I know if I select and Ctrl+K again, everything is as it was before. 
With your proposal implemented, it would not be like it was before and I could not use the # in the versatile ways like I have been until now.

**Comment by der-ac** [comment]
@golddotasksquestions 

I'm not sure I understand what you're saying there, I'm suggesting that hitting k will only toggle # at the start of the line, as it does now. # that are not at character 1 of the line will not be effected. 

@Calinou 

That's a good point, the multi-line strings can also be seen in the binary, I presume. Not sure there is a good way around that.

**Comment by golddotasksquestions** [comment]
@der-ac 
If you look at the code sample in my last comment. Imagine I want to completely disable `func _on_hurtbox_area_entered(area):`, I just can select the whole code block and press Ctrl+K. I don't have to worry about any of my previous CrlK to be inverted.

With your proposal, I could not select the whole code block, I would have to carefully select only the lines that are not already commented out in the first line. This is a massive efficiency reduction.

The way it is now, I can just select the whole code block again and Ctrl+K to undo my last step.
This would also not be possible anymore with your proposal.

I see where you coming from, but in day to day use, this would reduce the power, versitility and functionality of the select and Ctrl+K massively.

**Comment by MaaaxiKing** [comment]
I think this proposal should work like this:
Doing Ctrl + K: Every selected line that isn't commented at the first char should be commented; every selected line that is already commented at the first char should get one # more. _Nothing changed until here._
Doing Ctrl + Shift + K: It should work like @derac wrote at the top, so every selected line that isn't commented at the first char should be commented; every selected line that is already commented at the first char should lose one #, if it only has one # at the beginning, thus it would be uncommented.

**Comment by Calinou** [comment]
Closing due to lack of support. If you have a different implementation idea that could improve the existing situation, please open a new proposal.
