### ISSUE TITLE
Add extra support for Android

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#4175]
### Describe the project you are working on

Both 2d and 3d

### Describe the problem or limitation you are having in your project

I think there should be something to implement android sdk directly in godot. so that developer should'nt waste time on creating plugin and its also a hassle because most of the android developer don't know how to create a plugin . Instead of providing aar file to create plugin Godot developer should make a system to use sdk or api directly.

Note:
If you don't know what is an sdk you should google it. And i think every android studio user knows about sdk

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Sdk makes it easier to bring android game to the next level . 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If someone thinks that  this feature will increase the size of godot then this feature can be implement on mono version. Because Mono version user don't care of the size only there care about their needs.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. I don't think

### Is there a reason why this should be core and not an add-on in the asset library?

I think this can't be use as a asset library. But if it can then it will be a great news for every android game developer ...

**Comment by Calinou** [comment]
Closing, as this is out of scope for the Godot project: https://github.com/godotengine/godot-proposals/issues/2676
