### ISSUE TITLE
Add class to work with Windows Registry

### ISSUE THREAD

**Issue by q4a** [godotengine/godot-proposals#418]
**Describe the project you are working on:**
I'm working on Godot plugin, that can import custom games resources. There is list of supported games and for selected game I need to check: is it installed and folder where it was installed.

**Describe the problem or limitation you are having in your project:**
To find installed game folder, I need to check `if OS.get_name() == "Windows"`, then check if Registry key exists and read value of game folder.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
There is no class to work with Windows Registry, so I need to ask user to find game folder. With this class many installed games will be found automatically.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
It's internal class for GDScript. Please, add comment, if you really need flow diagram.

**Describe implementation detail for your proposal (in code), if possible:**
There is `OS` class and it has some platform-specific methods like `get_ime_text` or `kill` with note:
`This method is implemented on X.`
So, it looks possiible and not so hard to add platform-specific class `RegistryKey`, take API from microsoft docs for the baseline
https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registrykey?view=netframework-4.8
and check how is it done in C# module:
https://github.com/godotengine/godot/blob/master/modules/mono/utils/mono_reg_utils.cpp

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think, that my case (check and read Registry keys) is not the only one. `RegistryKey` class is needed if you want to recreate old game engine, that uses Registry to save some values or configs.
So looks like this class will be used often enough.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It looks not possible or very hard to get access to Windows Registry from add-on via reading binary files and parse it.

**Comment by fire** [comment]
See https://stackoverflow.com/questions/34065/how-to-read-a-value-from-the-windows-registry

**Comment by q4a** [comment]
> See https://stackoverflow.com/questions/34065/how-to-read-a-value-from-the-windows-registry

As I can see - there is code on C++, which can be included in Godot core, but can be executed from plugin in GDScript. Btw, I found C# bindings to Windows Registry API and it's just wraped by`#ifdef WINDOWS_ENABLED`
https://github.com/godotengine/godot/blob/master/modules/mono/utils/mono_reg_utils.cpp

**Comment by Calinou** [comment]
Closing due to lack of support. This feature can be provided by a third-party GDNative add-on or even a GDScript add-on by using `OS.execute()` and a [Batch script](https://stackoverflow.com/questions/445167/how-can-i-get-the-value-of-a-registry-key-from-within-a-batch-script).
