### ISSUE TITLE
Sort autocomplete options in a more useful way

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot-proposals#4189]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

The sorting of autocompletion options is not very productive.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Improve the sorting of the options to take into account the contents of (in order)
* The immediate context (e.g. the containing file (see image 1 and 2 below), or the class referenced (see image 3 below))
* The inherited classes (in order of inheritance)
* Other global identifiers

**Godot Currently (4.0)**
![godot windows tools 64_CpZ2wr9u1x](https://user-images.githubusercontent.com/41730826/157205514-d5d6be7b-4a03-4592-be74-d9da4f09aa1d.png)
![godot windows tools 64_Oi134QFhdJ](https://user-images.githubusercontent.com/41730826/157205519-0ed40675-69c9-456b-bd26-603c74f13f88.png)
![godot windows tools 64_8p2M0towMt](https://user-images.githubusercontent.com/41730826/157207244-4e43b3d0-1aea-48f2-8707-14c2b61e6189.png)

**Good Example, Visual Studio**. Just some random WPF project I had lying around
![devenv_lpRJ7yu6Y9](https://user-images.githubusercontent.com/41730826/157205647-55283135-30b5-4138-a360-512e36d9da53.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I looked at the code... would require a bit of work changing how code completion works, see `GDScriptLanguage::complete_code`.
I am not really familiar with the code, there is heaps of it, and it's not really commented so I tried and promptly gave up on trying to do it. 

Probably done by adding an additional property to `ScriptCodeCompletionOption`, something like 'location', which would specify the script path or class name from which the option comes from. e.g. 'Node', 'res://test/my_script.gd', 'Object', 'res://test/base_script.gd'

Then, when filtering (in `CodeEdit`) use the value of the 'location' to determine the "weight" of the option. You would have access to the `Script` there, so would be able to get a list of all the classes from which the script inherits (if any), and then loop through that list and assign weight to each. `This File` = highest weight, `Last base class` = lower weight, `globals` = lowest weight.

Just thinking out loud here, such a simple method may not work with some complexities, like accessing members of a 'static' class, like the `Input.` example in the images above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope

### Is there a reason why this should be core and not an add-on in the asset library?

Its the editor

**Comment by KoBeWi** [comment]
I created an issue about it once: https://github.com/godotengine/godot/issues/21726
There was even a nice PR fixing it, but it was never merged and then author gave up :<

**Comment by EricEzaM** [comment]
@KoBeWi Ah, sorry, I tried to search but did "code complete" as my query. It may have come up anyway, but I missed it. I thought there would be an issue regarding it as I noticed it clearly coming from VS/Rider.

**Comment by EricEzaM** [comment]
Ok, I tried something. Here is the commit so you can see the changes: https://github.com/godotengine/godot/compare/master...EricEzaM:better-code-completion

Basic logic:
* Add location property to `ScriptCodeCompletionOption`. It is an enum, but importantly one of the enum values is a mask, `LOCATION_PARENT_MASK = (1 << 8),`. This allows you, for example, to sort closer ancestors differently from more distant ancestors. The class itself will be value 256, while the class it inherits will have its options at 257, and then its parent at 258, etc.
* When creating options, pass a location. This can be easily calculated if the options are created in a loop, where the loop is looping over parent classes. `const int location = classes_processed | ScriptCodeCompletionOption::LOCATION_PARENT_MASK;`
* When you have all the options, simply sort on `location`. The lowest values will be highest priority. If two locations are the same, sort alphanumerically.

Note as of writing that implementation ONLY works for attributes on "Native", like `Input`, as shown below.

![image](https://user-images.githubusercontent.com/41730826/157254905-30f6ccbe-7d94-4dce-9dcc-ed6cab9ef756.png)

**Comment by LightningAA** [comment]
See also https://github.com/godotengine/godot-proposals/issues/99, https://github.com/godotengine/godot-proposals/issues/1216

**Comment by EricEzaM** [comment]
Haha wow, yep, a straight up dupe of 99. Oops! I knew it was likely to be have reported somewhere before.

**Comment by LightningAA** [comment]
> Haha wow, yep, a straight up dupe of 99. Oops! I knew it was likely to be have reported somewhere before.

If it makes you feel better, I knew the issue I was looking for and it still took me a few minutes to find it 😃

**Comment by EricEzaM** [comment]
Rider also makes options from the direct class bold:
![image](https://user-images.githubusercontent.com/41730826/157678579-20161c10-bc7a-4042-9e2b-222608ef6030.png)

**Comment by Calinou** [comment]
> Rider also makes options from the direct class bold: ![image](https://user-images.githubusercontent.com/41730826/157678579-20161c10-bc7a-4042-9e2b-222608ef6030.png)

It might be worth opening a dedicated proposal for this. I'd really like to see this :slightly_smiling_face:

**Comment by Zireael07** [comment]
At any rate, it should be reopened temporarily as the PR was reverted pending some improvements to the code.

**Comment by Calinou** [comment]
Reopening, as this was reverted by https://github.com/godotengine/godot/pull/59629.

**Comment by EricEzaM** [comment]
> It might be worth opening a dedicated proposal for this. I'd really like to see this 🙂

Theoretically it should be pretty easy with the additions in the linked PR. _Theoretically_ :D
