### ISSUE TITLE
Allow using `self` inside lambdas

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#4191]
### Describe the project you are working on

Just slowly migrating to 4.0

### Describe the problem or limitation you are having in your project

Lambdas in GDScript 2.0 are a wonderful thing to ~~ab~~use. The only problem is that you can only capture local variables, but most of the uses (in my case Tween animations) require you to access properties/sub-nodes of the current object.
```GDScript
create_tween().tween_method(func(t): $Sprite.position = Vector2.from_angle(t) * 100) # not possible
```
The usual workaround is doing this:
```GDScript
var sprite = $Sprite
create_tween().tween_method(func(t): sprite.position = Vector2.from_angle(t) * 100)
```
Or a more general one:
```GDScript
var this = self
create_tween().tween_method(func(t): this.sprite.position = Vector2.from_angle(t) * 100) # assuming sprite is onready variable
```
The problem is that if every single one of your lambdas require a single variable created beforehand, it's getting old and annoying.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The solution could be explicitly capturing the `self` from the scope the lamda is created in. This way, if you want to access any property or sub-node, you can use `self`, like
```GDScript
create_tween().tween_method(func(t): self.sprite.position = Vector2.from_angle(t) * 100)
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The `self` capture could just be a syntactic sugar.
```GDScript
func(): self.something
```
would do
```GDScript
var this = self
func(): this.something
```
behind the scenes (i.e. implicitly create a local variable that stores `self`), so user can write less code.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by adding one line for each created lamda.

### Is there a reason why this should be core and not an add-on in the asset library?

Can't be add-on.

**Comment by Mickeon** [comment]
Oh, I didn't even think this was a limitation, as I took it for granted. I don't see any reason NOT to add this, unless it would cause... some sort of performance loss that can't be avoided.
