### ISSUE TITLE
Add `step` and `step_angle` math functions

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot-proposals#4194]
### Describe the project you are working on

2D top-down game with tanks (Godot4 custom Mono)

### Describe the problem or limitation you are having in your project

Rotate the tank's cannon towards the cursor with a fixed rotation speed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add  `move_angle_towards` function to the `GlobalScope` (and `Mathf` for C#).

- `move_angle_toward(from: float, to: float, delta: float) -> float`
  - return `start` + `delta` towards `to` wrapped around `TAU`
  - like `move_toward` for angles
  
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```csharp
static class Mathf {
	[...]
	static float MoveAngleToward(float from, float to, float delta) {
		var diff = Mathf.PosMod(to - from, Mathf.Tau);
		if (diff <= Mathf.Pi) {
			return from + Mathf.Min(delta, diff);
		} else {
			return from - Mathf.Min(delta, Mathf.Tau - diff);
		}
	}
}

partial class Example : Sprite2D {
	[Export] float rotationSpeed;

	public override void _Process(float delta) {
		var toRotation = GetAngleTo(GetGlobalMousePosition());
		Rotation = Mathf.StepAngle(Rotation, toRotation, delta * rotationSpeed);
	}
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The user can define the method themself, but they would be at another location as the other math functions.

### Is there a reason why this should be core and not an add-on in the asset library?

Add-ons can't add core functions.

### Edit
- removed `step`, because `move_toward` already solves the issue

**Comment by Mickeon** [comment]
Do correct me if I'm wrong, but the already existing `move_towards()` function (also available for **Vector2** and **Vector3**) is exactly how `step()` is being described here.

I believe there's no equivalent for angles, however.

**Comment by antonWetzel** [comment]
> Do correct me if I'm wrong, but the already existing `move_toward()` function (also available for **Vector2** and **Vector3**) is exactly how `step()` is being described here.
> 
> I believe there's no equivalent for angles, however. Hence I approve the proposal for _that_ specifically.

I overlooked `move_towards` because I only searched for `step`.
I edited the  issue remove `step`.

**Comment by antonWetzel** [comment]
Self closed (see https://github.com/godotengine/godot/pull/59162)
