### ISSUE TITLE
Use the standard macOS shortcut for closing scene and script tabs (Command + W)

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot-proposals#4195]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

Command + W closes any tab on any app on macOS, the current shortcut is Shift + Command + W which is unintuitive and Close Script does use Command + W unlike Close Scene. Using the same standard would be great

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Using the same shortcut for Close Scene and Close Script would improve UX and efficiency

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same shortcut to close depending on the context, script if on Script editor or Scene if on 3D viewer

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is used all the time for navigation and closing tabs and windows

### Is there a reason why this should be core and not an add-on in the asset library?

To have a solid UX and UI, using streamlined shortcuts (just like Command + Q quits the editor)

**Comment by Calinou** [comment]
This can probably be done in 4.0, but it'll be tricky to do in 3.x (if even possible) due to the various input focus stealing issues present there.

**Comment by Cass-dev-web** [comment]
> Related to https://github.com/godotengine/godot-proposals/discussions/4098.
> 
> 
> 
> This can probably be done in 4.0, but it'll be tricky to do in 3.x (if even possible) due to the various input focus stealing issues present there.

Shortcuts already exist, it's a matter of overwriting them.
