### ISSUE TITLE
Improve coding UX on small (eg 11-14 inch) touch devices by adding scroll by drag support for the code editor & the docs reader

### ISSUE THREAD

**Issue by kanevbg** [godotengine/godot-proposals#4210]
### Describe the project you are working on

not related at all

### Describe the problem or limitation you are having in your project

Coding UX on lenovo ideapad 13.3' is not good.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Currently there is no scroll support by dragging the screen anywhere in the Godot Engine UI. Adding that to at lease the code editor and the docs reader will greatly enhance coding experience. Now we have to drag the side scroll bar or use the touch-pad which is less productive on these devices.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Not related.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can not be natively.

### Is there a reason why this should be core and not an add-on in the asset library?

There is no reason for not being core feature.

**Comment by kanevbg** [comment]
@Calinou I looked at the issue you referenced, however is not true that it is for core engine types related to dragging? My feature request was for drag support trough gestures but in the IDE (eg the Godot's code editor and the Godot's documentation reading window itself) not about the build-in types for game development.

**Comment by Calinou** [comment]
> @Calinou I looked at the issue you referenced, however is not true that it is for core engine types related to dragging? My feature request was for drag support trough gestures but in the IDE (eg the Godot's code editor and the Godot's documentation reading window itself) not about the build-in types for game development.

For this to be supported in the editor, it also requires touch events to be recognized as such in the engine.

**Comment by kanevbg** [comment]
Thanks for the clarification. In that case is that request still valid to persist as feature request? I understand that the basics on which that request have to depend are work-in-progress, however it will be better to leave that open and link the dependency.

**Comment by Calinou** [comment]
> Thanks for the clarification. In that case is that request still valid to persist as feature request? I understand that the basics on which that request have to depend are work-in-progress, however it will be better to leave that open and link the dependency.

Once https://github.com/godotengine/godot/issues/13139 is implemented, touch scrolling will work automatically in the editor as it's already implemented on macOS.
