### ISSUE TITLE
Migrate Godot Splash Screen to Android 12

### ISSUE THREAD

**Issue by MiqueiasDevGames** [godotengine/godot-proposals#4221]
### Describe the project you are working on

On android SplashScreen must be migrated to android 12.

When making the migration in one of my projects, I realized that I could control the SplashScreen through Godot using GodotPlugin tools, so that the SplashScreen is only closed when the main scene of the game is fully loaded.

I uploaded a project to Github where I show how I made these changes, changes that can be adapted to Godot, in the android template part and in the Godot part where the end of SplashScreen could work natively.

More information: https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12

### Describe the problem or limitation you are having in your project

The way I did it, I need the Background Loading Script I learned how to do here: https://docs.godotengine.org/en/stable/tutorials/io/background_loading.html

This Script with some adaptations calls the PluginSplashScreen's ExitSplashScreen() function when the defined scene is fully loaded.

So Godot could have this part natively, all this SplashScreen control would be closed when the main scene is fully loaded and the new android templates already come with the necessary changes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding the functionality to close SplashScreen natively would be useful for everyone

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the part of Android SplashScreen that ends when a variable becomes false.

In the Godot part, make this variable false when the main scene is fully loaded.

All this is done here: https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12/

But you can definitely adapt to work natively in godot and update the android templates to use.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Enhancement working here:
https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12/tree/main/Script_SplashScreen

Godot is missing, I'm already configured and the android templates updated

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, as it works with the main scene and depends on knowing when this scene is fully loaded.

**Comment by MiqueiasDevGames** [comment]
Export your game to android using my other project and see everything working: https://github.com/MiqueiasDevGames/export-godot-to-android-without-gradle-32bits-and-64bits

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/92965
