### ISSUE TITLE
Get a warning when restarting to set a custom theme to avoid loosing unsaved Scenes

### ISSUE THREAD

**Issue by Rotekoppen** [godotengine/godot-proposals#4222]
### Describe the project you are working on

I made a test project to learn themes, just some random ui elements.

Most notably not saved

### Describe the problem or limitation you are having in your project

When setting the default theme for the project, not the editor, it prompts about having to restart to apply.
With no further warning about unsaved work it closes

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a warning to save the scene

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a warning to save the scene just like you were closing the editor

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Im not familliar with what editor plugins can do and not, but it would not be the best UX

### Is there a reason why this should be core and not an add-on in the asset library?

This is an issue with core godot

**Comment by KoBeWi** [comment]
This is a bug actually: https://github.com/godotengine/godot/issues/43302
