### ISSUE TITLE
Add option for OptionButton to fit to longest item size

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#4231]
### Describe the project you are working on

A game with advanced level editor that heavily uses GUI nodes.

### Describe the problem or limitation you are having in your project

I use OptionButton in a few places. They are mostly in containers. The problem is that OptionButton's size depends on the currently selected item.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/2223172/158640902-ee423f46-8118-4aef-88c7-b298c0e4bb80.gif)
Sometimes I can expand it to maximum size, but sometimes the OptionButton determines the container size, so it just looks bad.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There should be a property in OptionButton called `fit_to_longest_item` (or something similar), which when enabled, makes the OptionButton size constant. It would always take the size of longest item.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When `fit_to_longest_item` is enabled, minimum size is calculated based on longest item, instead of the currently selected one.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It might be possible to write a script that sets `rect_min_size` to the desired value, but you need to calculate the width properly, taking styleboxes into account and text size etc. Also the text might change with a translation, so it just requires writing a bit of logic that already exists in the node.

### Is there a reason why this should be core and not an add-on in the asset library?

It enhances a core node with rather basic functionality.

**Comment by Calinou** [comment]
I think that property should be enabled by default.

**Comment by fire-forge** [comment]
This will be useful in some places around the editor. For example, the Add Metadata dialog expands when selecting a longer type and then stays at the same size when a shorter type is selected, which looks weird. When this feature is added, the dialog can stay the same size for all types. There are probably a lot of other places like this.

![image](https://user-images.githubusercontent.com/67974470/160524027-7f45b2d2-6503-41ed-a5b3-48e8f13e392a.png)
![image](https://user-images.githubusercontent.com/67974470/160524121-ec561907-b940-4f8c-8d6d-68001db0ac45.png)
![image](https://user-images.githubusercontent.com/67974470/160523699-d91c308f-cb9a-4556-a4b3-a45a03da44ce.png)
