### ISSUE TITLE
`move_and_slide` should not alter scale

### ISSUE THREAD

**Issue by XPhyro** [godotengine/godot-proposals#4235]
### Describe the project you are working on

2D platformer

### Describe the problem or limitation you are having in your project

`move_and_slide` arbitrarily changes the rotation and scale of `KinematicBody2D`s. The new value is equivalent to the old value, but this requires the programmer to constantly keep track of rotations/scales independent of `Node2D`.

If one has any mechanic that feeds from rotation or scale, that mechanic will be broken after a `move_and_slide` call. For instance, I keep track of whether the player is facing left or right and assign -1 or +1 to the x-axis of the scale depending on it. As `move_and_slide` may alter the rotation and scale, I have to keep track of the desired rotation and scale separately and assign both.

This is a big potential for bugs in games (especially if one is unaware of this behaviour) and a hassle in usage. The reason I found out about this behaviour in the first place is that I was trying to fix a bug caused by it.

----------------

To reproduce the bug:

Open the Platformer 2D demo, create a child `Node2D` under the player `KinematicBody2D` and assign the child the following script:

```gd
extends Node2D

func _physics_process(delta):
    var parent = get_parent()
    prints("first", parent.rotation, parent.scale)
    parent.scale = Vector2(-1, 1)
    prints("second", parent.rotation, parent.scale)
    parent.move_and_slide(Vector2(0, 0))
    prints("third", parent.rotation, parent.scale)
```

Optionally remove the `Player.gd` script from the player. Reproducible whether it is removed or not.

Output:

```
first 0 (1, 1)
second 0 (-1, 1)
third 3.141593 (1, -1)  <-- move_and_slide changed rotation and scale to something equivalent
first 3.141593 (1, -1)
second 3.141593 (-1, 1)  <-- we created a bug
third 0 (1, -1)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In comparison, Unity's `RigidBody2D.MovePosition` never changes scale and only changes rotation if it needs to, whereas `move_and_slide` arbitrarily transforms the values (to something equivalent). I believe Godot should follow the same policy as Unity.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know how `move_and_slide` is implemented, so I can't comment.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Changing scale to flip nodes and calling `move_and_slide` is a common use case in 2D games.

### Is there a reason why this should be core and not an add-on in the asset library?

`move_and_slide` is a core function in the engine and the current behaviour may (and in my case *did*) lead to bugs.

**Comment by Calinou** [comment]
This change would likely be considered compatibility-breaking, so it can only be considered for 4.0. There's probably someone out there relying on the current behavior, especially for rotation :slightly_smiling_face:

**Comment by dimi3tron** [comment]
The behavior remained the same in 4.0 (beta5)

I worked around it by placing everything I want to mirror (scale.x * -1) under a `Node2D` under the root `CharacterBody2D` and apply the scaling to the new node instead. This seems to work as intended.

Note that the `CollisionShape2D` associated with the `CharacterBody2D` node needs to be a direct child of that `CharacterBody2D` node, and cannot be placed under the new `Node2D`. So you will need to apply the scaling to the collision shape  separately.

**Comment by aaronfranke** [comment]
This is not possible to do because Godot's decomposition of the rotation and scale from the transformation matrix uses the X axis for rotation and can only decompose negative Y scales. See https://github.com/godotengine/godot/issues/17405 and all the issues linked in there for further discussion.

As a work-around, you should not scale your `CharacterBody2D` nodes, instead you should scale the sprites.
