### ISSUE TITLE
Split Tilemap Layers `enabled` property into `visible` and `enabled` properties

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot-proposals#4236]
### Describe the project you are working on

Playing around with the new tile map in Godot 4.

### Describe the problem or limitation you are having in your project

When I first saw the Tilemap Layer option i thought I could use it to create background decoration with my existing tiles. I did this by adding a background layer an giving it a darker modulate than the foreground. The problem is, that the collision shapes of the background also affect the player.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Splitting the `enabled` property of a Tilemap Layer into two diffrent properties.
- `visible` should enable visual processing (rendering, animations)
- the other should enable game logic processing (physics, navigation)

In this way a layer can be used only as visual element without creating new tiles for it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The current setup and updating logic should be split in two functions. (I hope this is doable with the implementation)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As far as I know not. The only workaround would be to create an alternative tile for each tile. But the current painting of alternative tiles does not seem to work well with large amounts of tiles from an usabillity point of view.

### Is there a reason why this should be core and not an add-on in the asset library?

The tilemap implementation is part of core.

**Comment by Calinou** [comment]
cc @groud

**Comment by KoBeWi** [comment]
This sounds similar to #3092
AFAIK it's difficult to split layer visibility from other of it's properties. I [once made an attempt to allow disabling collisions](https://github.com/godotengine/godot/pull/53653), but the solution wasn't very good and instead an alternative was implemented instead.

Attach this script to your TileMap to disable collisions or just do anything per layer:
```GDScript
extends TileMap

const DISABLE_THIS = 1 # you can change it to array or whatever

func _use_tile_data_runtime_update(layer: int, coords: Vector2i) -> bool:
	return layer == DISABLE_THIS

func _tile_data_runtime_update(layer: int, coords: Vector2i, tile_data: TileData) -> void:
	tile_data.set_collision_polygons_count(0, 0) # this removes tile collision for the specified layer
```

**Comment by RoniPerson** [comment]
Thanks for the hint.
