### ISSUE TITLE
Move GLTF export under scene menu

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot-proposals#4239]
### Describe the project you are working on

An addon for faster prototype blocking 3D levels.

### Describe the problem or limitation you are having in your project

I remembered hearing that Godot supports exporting the scene in GLTF format. I wanted to test it, but couldn't find the option. After googling it I found that the exporter is located in `Project/Tools/Export GLTF...` . This feels semantically wrong place, as this isn't project-wide operation but scene.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There's literally a "convert to" menu in scene menu. So the logical step would be to move the option into `Scene/Convert to/Export GLTF...`. I believe that's the place most would be searching this feature in.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![Untitled-1](https://user-images.githubusercontent.com/1621768/159113242-5e0b594c-b589-4601-93d7-947c17d2e0bd.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is an accessability/discoverability/consistency issue.

**Comment by fire** [comment]
I agree! It was something done a long time ago. (Back in 2019...)
