### ISSUE TITLE
Add proper filters for picking export template

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#4244]
### Describe the project you are working on

Not related to particular project. I'm just using custom builds.

### Describe the problem or limitation you are having in your project

This option here:
![image](https://user-images.githubusercontent.com/2223172/159141807-de44b520-5d23-4be2-a768-b0f39846cb08.png)
It's very useful when you have a custom build, because you can just pick a custom template and compile without "installing" the template (which is problematic, because you'd need to do it after every recompilation).

The problem is this:
![image](https://user-images.githubusercontent.com/2223172/159141826-c25ce29a-8cbb-4a41-b4e7-f8ec2c26c8b6.png)
Here, I'm trying to pick a template file. But I'm presented with a list of useless files, most of which don't even display full name. Due to cut-off names, to pick my template I have to guess or check every file. I can't show only relevant files, because the only available filter is "All Files".

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be much easier to find my template if the list instead displayed only the files that can be a template. Even if they displayed full names, only 3 out of all these files can be picked as template (in my case the `exe` files).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add extension filters to the export template picker. The list could just only include files that can be templates (`.exe`, `.apk` etc.) or maybe it could only display extensions for the selected platform.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

You can't really customize this dialog with an addon.

**Comment by akien-mga** [comment]
This was only relevant for Windows since other presets already had a filter. Fixed by https://github.com/godotengine/godot/pull/59447.
