### ISSUE TITLE
Expose navigable layers for NavigationAgent2D/3D

### ISSUE THREAD

**Issue by bartekd97** [godotengine/godot-proposals#4245]
### Describe the project you are working on

Kind of hack'n'slash where I use many navigation agents and I want some of them to omit specified areas.

### Describe the problem or limitation you are having in your project

I see that you can set navigation layer for navigation region but you can't do this for agents - they always use first layer only.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I see that in navigation server API there is option to specify layer mask of region to use for path finding - so exposing to to navigation agent as an additional property shouldn't be a problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Additional bitfield property in NavigationAgent2D/3D node - just like other layer fields like collisions

```
	if Input.is_action_just_pressed("1"):
		agent.navigable_layers = 3 # use now layer 1 and 2
	if Input.is_action_just_pressed("2"):
		agent.navigable_layers = 1 # use now only layer 1
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can't be simply worked around, if even possible at all.

### Is there a reason why this should be core and not an add-on in the asset library?

It's already exposed in navigation server API and regions actually make use of layers. Only agent nodes not so whole system is quite useless because there is no use of this right now.
Also, I've already made a PR for this: https://github.com/godotengine/godot/pull/59331

**Comment by tavurth** [comment]
This is really useful for making people follow roads & paths instead of walking on the grass.

**Comment by groud** [comment]
This makes sense to me. I agree those should be exposed.
