### ISSUE TITLE
Implement camera icon as 3D model facing the correct direction

### ISSUE THREAD

**Issue by inDigiNeous** [godotengine/godot-proposals#425]
**Describe the project you are working on:**
Any project.

**Describe the problem or limitation you are having in your project:**
When zooming the scene far away,and looking at  the camera in the scene, it can be confusing to think that the camera _icon_ is showing which way the camera is looking at in the scene. 

For example, here looking at the camera from far away where the camera detail is not shown, I see this, and might think that the camera is facing outwards from the center of the scene:

![image](https://user-images.githubusercontent.com/1212726/73545521-235d3f80-4444-11ea-8a43-9b809305ebed.png)

Now when I zoom in on the scene, actually the camera is facing the other way

![image](https://user-images.githubusercontent.com/1212726/73545621-58699200-4444-11ea-8e21-58ea09e95881.png)

I notice myself being constantly confused by this fact that the icon is facing whatever direction that is not related to the actual camera looking at direction in 3D space.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

Would suggest implementing the camera icon as an actual 3D model of a camera, that is always facing in the correct orientation. Would help to see better anyway where the model is looking at.

Or possibly replacing the icon with a direction neutral one. 

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:*

Unreal engine seems to do this already:

![image](https://user-images.githubusercontent.com/1212726/73546140-5ce27a80-4445-11ea-89e2-ee13b913166a.png)

Or as an easier solution, use a direction neutral camera icon like this:

![image](https://user-images.githubusercontent.com/1212726/73546939-bb5c2880-4446-11ea-8c87-f1115ae79b7f.png)

**Describe implementation detail for your proposal (in code), if possible:**
Figure out a 3D model for the camera, replace the icon with this 3D model. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Dont think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Part of the core mechanics. Would make it more user friendly.

**Comment by Calinou** [comment]
We can remove the camera billboard sprite entirely and just enlarge the purple gizmo we currently have. This is a very simple solution to the problem described here. What do you think?

**Comment by inDigiNeous** [comment]
> We can remove the camera billboard sprite entirely and maybe enlarge the purple gizmo we currently have. This is a very simple solution to the problem described here. What do you think?

I would say this is a good simple solution. Probably no need for an actual 3D model. Thank you for thinking about this.

**Comment by Tanza3D** [comment]
![image](https://github.com/godotengine/godot-proposals/assets/33783503/5a27d690-c937-4deb-b459-f394d042859f)
how about something similar to what blender has?

**Comment by Calinou** [comment]
@Tanza3D This was addressed recently by readding the camera gizmo icon and keeping the lines.

There's already a triangle at the top of the Camera3D gizmo lines, but it's an outline instead of being solid.
