### ISSUE TITLE
Add way of telling elapsed time to Tween

### ISSUE THREAD

**Issue by RuthgerD** [godotengine/godot-proposals#4251]
### Describe the project you are working on

A declarative UI library for godot 4

### Describe the problem or limitation you are having in your project

I want to carefully control tweening node properties,
whenever something changes I need to change the tween to accommodate the target and also the duration so that relative time spent stays the same.
 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add **back** the Tween::tell method that was present in godot 3.x as this provides the necessary info I need

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Have Tween return the elapsed time (which it undoubtedly already knows internally) when the method `tell` is called on it

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no way to access this information otherwise

### Is there a reason why this should be core and not an add-on in the asset library?

Only the Tween class knows about it

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
> which it undoubtedly already knows internally

Actually it doesn't. The elapsed time is tracked only inside Tweeners, there is no global time tracking, hence why `tell()` is missing. It can be added though.

**Comment by KoBeWi** [comment]
Nah, Tweeners may have different duration, so calculating total time based on their time would be needlessly complex. The best would be to add `total_time` internal variable to Tween, which would be incremented with each step, just like normal timer.
