### ISSUE TITLE
Expose AnimatedSprite's `playing_backwards` property

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#4252]
### Describe the project you are working on

Your typical 2D project with extensive use of **AnimatedSprite**.

### Describe the problem or limitation you are having in your project

In my project, I have a AnimatedSprite that plays a charge animation **forward** so long as the button is held. When released, it plays **backwards** from where it left off, then switches back to the idle animation.

For this to work, I require some way of knowing whether or not the animation is playing backwards. To my surprise, this is not easily accessible. The only time one could know is while passing the second argument of the `play()` method. Behind the scenes, **something** is being set, whatever dictates **AnimatedSprite**'s animation direction in the long run. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose **AnimatedSprite**'s `playing_backwards` property, or something similarly named. (such as `backwards`, `reversed`...).

Simple enough, if `playing_backwards` is `true`, the animation is playing (or will play) backwards.
This is the same boolean property being set by the `play()` method's second argument.

It'd be nice if it wasn't just read-only (only accessible with `is_playing_backwards()`). It would allow setting up the property within the Inspector, as well as avoiding repetition _(need the current animation to play backwards, no need to recall `play()` )_. However, I do see an issue with the main name I've chosen for the proposal: it being confused with the `playing` property.

Of course, the addition would also apply to **AnimatedSprite3D**.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```GDScript
var sprite : AnimatedSprite = $AnimatedSprite

sprite.play("default", false)
print(sprite.playing_backwards) # returns "false"

sprite.play("default", true)
print(sprite.playing_backwards) # returns "true"
```
```GDScript
# The following code is a simplification of my actual use-case
if sprite.animation == "charge":
	if (not is_charging_shot):
		sprite.playing_backwards = true # Same as sprite.play("charge", true)
		
	if (sprite.playing_backwards and sprite.frame == 1): 
		sprite.play("idle")
		sprite.frame = sprite.frames.get_frame_count("idle") - 4

else if (is_charging_shot):
	sprite.play("charge")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

One easy way to do it is append a custom Script to the **AnimatedSprite**, override `play()` and add a `backwards` property on your own.
A bit hacky but more contained, I use a *meta* property, to check if my charge animation is being undone.

### Is there a reason why this should be core and not an add-on in the asset library?

AnimatedSprite and AnimatedSprite3D are core.

**Comment by KoBeWi** [comment]
Someone actually implemented this: https://github.com/godotengine/godot/pull/30920 The PR looks abandoned though.

**Comment by Mickeon** [comment]
Closing due of lukewarm reception. Opened a proposal that is **specifically** about exposing this as a getter function, because at least I really believe it to be an odd omission.
