### ISSUE TITLE
Rename "Ss Reflections" to "SSR" in `Environment`

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#4254]
### Describe the project you are working on

not relevant

### Describe the problem or limitation you are having in your project

![image](https://user-images.githubusercontent.com/71937306/159315416-6a39ee2e-6850-4797-8f1a-00d6cd64a35e.png)
![image](https://user-images.githubusercontent.com/71937306/159315604-d28d5dc0-34a4-458a-b4da-f13b5bd1d04d.png)

There is an inconsistency between how "Ss Reflections" is named relative to other screen-space effects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The naming convention seem to be "use the abreviation for whatever has an abreviation and use the full name for the rest".
SSR is a well-known abreviation for screen-space reflections.
I propose that "Ss Reflection" be renamed to "SSR" for consistency.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

 `Environment` properties should be renamed from `ss_reflections_*` to `ssr_*` and the category in the inspector should be `SSR` rather than `Ss Reflections`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

it can't

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:

**Comment by fire-forge** [comment]
I opened a PR for this here: https://github.com/godotengine/godot/pull/59526
