### ISSUE TITLE
Add option to import simple glTF, FBX and Collada files as Mesh

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-proposals#4256]
### Describe the project you are working on

Various visual effects using meshes as their base.

### Describe the problem or limitation you are having in your project

Often when you need a single mesh for a VFX it doesn't make sense to import a 3D file as a scene. 

OBJ has the option to import as mesh, which is great for this, but OBJ does not support Vertex colors which are often used in VFX meshes.

This means you'll have to open up the file as an inherited scene and save out the mesh to get a mesh file to work with, then delete the orginal imported file. If you then make any changes to mesh and want to update it you'll need to repeat the process.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding the option to import glTF, FBX and Collada files as meshes when they only contain a single mesh would be very practical in these cases.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An additional option of "Mesh" under "Import As" for glTF, FBX and Collada. It might be possible to only show the option if the file contains a single mesh.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't really think this can be worked around as it relies on import.

### Is there a reason why this should be core and not an add-on in the asset library?

Addons can't change how files are imported.

**Comment by Calinou** [comment]
In `master`, this can be done in the Advanced Import Settings menu:

![image](https://user-images.githubusercontent.com/180032/159472078-e231ec0c-6330-4298-896e-742b9b3af77a.png)

You can then use the resulting `.res` resource in any MeshInstance or Particles node.

**Comment by lewiji** [comment]
I believe there's already a property in the 3.x importer for GLTF/FBX to save meshes as external files - you still get an imported scene file, but it can be ignored, the meshes can be saved as `.tres` or `.mesh` alongside them or in a subfolder (via the "Store in Subfolder" option under external files) - so no need to manually save from the scene. 

The option for FBX/GLTF is under the `Meshes` section, `Storage` option, change from `Built-In` to `Files (.mesh)` or `Files (.tres)`. I don't know if this applies to the other formats' importers.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/7494, which is more detailed.

**Comment by xne** [comment]
Anyone looking to do this while #7494 is worked on can use this import script:
```gdscript
@tool
extends EditorScenePostImport

func _post_import(scene: Node) -> Object:
	return scene.get_child(0)
```

**Comment by nameOfUser0236** [comment]
> Anyone looking to do this while [#7494](https://github.com/godotengine/godot-proposals/issues/7494) is worked on can use this import script:
> 
> @tool
> extends EditorScenePostImport
> 
> func _post_import(scene: Node) -> Object:
> 	return scene.get_child(0)

Modified this to resolve some errors. (very elegant solution BTW)

```gdscript
@tool
extends EditorScenePostImport

func _post_import(scene: Node) -> Object:
	var mesh = scene.get_child(0)
	mesh.owner = null
	scene.remove_child(mesh)
	return mesh
```
