### ISSUE TITLE
Add a system for storing, displaying, and warning about incompatible features in the Project Manager

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#427]
**Describe the project you are working on:**

Various projects with various versions of Godot, some of which are incompatible with each other.

**Describe how this feature / enhancement will help your project:**

Currently, when you have C# projects, and open Godot without Mono support, then Godot will fail to load the C# scripts when it opens the project. There is currently no visual indication that you will be unable to load the project:

![1](https://user-images.githubusercontent.com/1646875/62403901-5c743000-b545-11e9-8f6f-c4b11ab862d7.png)

My proposed solution for this is to add a system for storing which features are used in each project. A project with a C# solution generated would be given a "feature tag" for C#. If you open the project with Godot with Mono support, it will detect the tag and detect that it supports it, and it will work fine. If you open the project with Godot without Mono support, then it will see the tag and display a yellow "C#" message in the project manager, followed by a warning if you try and open it.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

![2](https://user-images.githubusercontent.com/1646875/62403918-7b72c200-b545-11e9-8b5c-26dec41f1c03.png)

The warning could be something like "Warning: This project uses the following features not supported by this version of Godot: C#. Open anyway?".

The reason I'm suggesting that the feature tag system is generic is because this would be useful in several other areas. For example, we can make Godot versions be feature tags, so this system would fit the use case of https://github.com/godotengine/godot/issues/25497. If Godot detects that the version used is different, it will display the project's version in yellow, and show a warning if you try and open the project. This system would also be useful for when Godot has double support, and we don't want users to accidentally open their double-precision projects with normal Godot and vice versa.

For example, this could display if a project is using Godot 4.0, C#, and doubles, and it's viewed in the project manager of Godot 3.2 without C# support (EDIT: This is a theoretical parallel universe where the PR was merged in time for 3.2):

![3](https://user-images.githubusercontent.com/1646875/62404086-a4e01d80-b546-11e9-9209-06c305b95d2f.png)

One of the key things is that if the system is generalized like this, then non-double Godot wouldn't even need to know what the "double" tag is, and Godot without C# wouldn't need to know what "C#" is, all they know is that the project uses it, and it doesn't have that feature, so show a warning.

**Describe implementation detail for your proposal (in code), if possible:** https://github.com/godotengine/godot/pull/31171

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, because it's about the project manager.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Yes, because it's about the project manager.

**Comment by Calinou** [comment]
Should tags be stored on the project manager side (i.e. outside the project data) or in the project (i.e. in the project files, stored in version control)? If we were to store tags in the project, it could become messy if you clone lots of random projects. That is, even if we impose some kind of standardized syntax like GitHub Topics (lowercase only, dashes instead of spaces).

**Comment by aaronfranke** [comment]
It should be in the project file in version control, so that tags are preserved for other users. If someone opens and saves the project in another Godot version, that should be saved. If the project requires a custom build of Godot to open, that should also be saved so anyone cloning sees the warning.

> Some people may be creating GDScript-only projects with a Mono-enabled version of Godot after all.

Yeah, the idea is to detect if there's a C# project generated. The PR doesn't currently do this.
