### ISSUE TITLE
Consider hiding everything in Object behide a Type type and having a single get_type() member

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#4279]
### Describe the project you are working on

Just looking at godot 4.0 and gdscript

### Describe the problem or limitation you are having in your project

So this one kinda does have a problem.
The main issue is that when your trying to auto complicate something you get a bunch suggestions that you may not be looking for.
For example you might want a object with two consts and then when you try to do `MyObject.` you get flooded with members from Object instead of what your looking for.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Consider refactoring members of the base type Object to be part of a engine type called Type and having a single get_type() that returns it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
class_name MyVeryBasicObject : Object

var my_variable : int

func my_function()->String:
    get_type().set("my_variable",  1)
    return get_type().to_string()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think it would be used its basically what C# does

### Is there a reason why this should be core and not an add-on in the asset library?

Again it reduces the amount of info you get in autocomplete when you do something like...
```
MyVeryBasicObject.
```
without removing any features

**Comment by KoBeWi** [comment]
This will be resolved by https://github.com/godotengine/godot/pull/58931, no? The base problem is the same.

**Comment by Shadowblitz16** [comment]
Idk I would have to try it but I can close this issue for now at least.
