### ISSUE TITLE
Input Map should not have forced defaults, but optional default sets.

### ISSUE THREAD

**Issue by AlexZan** [godotengine/godot-proposals#428]
I have seen similar requests, and the similar arguments made against them:

https://github.com/godotengine/godot/issues/17210
https://github.com/godotengine/godot-proposals/issues/303

The main argument against this type of request is that these default input mappings are required for the ui. My argument against that is as follows:

Input Map, or anything for that matter should be opinionated, by default. Behaviour/Opinion should be contextual. For example, If I am making a simple 3d prototype, that has no interest in ui, and does not want the clutter of current default settings, it should not be forced.

If a developer is working on a project that requires the type of UI that the current default input map is made for, they can load it in from a list of default presets, or download/add it. There could eventually be several for different common game types.

Starting with a blank state will allow developers to have better focus and more organic growth to their project.

I am prototyping about 20 different projects, many of them have conflicts with the default input map. It should not be forced, but optional.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
