### ISSUE TITLE
Integrate AMD FSR 2 in the Vulkan renderer (currently, FSR 1.0 is supported)

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot-proposals#4280]
*Bugsquad edit: Related to https://github.com/godotengine/godot-proposals/issues/2809, which is about the FSR 1.0 implementation (which is now in `master`).*

### Describe the project you are working on

This feature will help almost any project to improve FPS on low-end systems.

### Describe the problem or limitation you are having in your project

There is never too many FPS.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

AMD showcased their new FSR 2.0 that has vector data and previous frames data included into the algorithm, so the quality is way better, than the original FSR 1.x branch. It allows to properly work with thin lines, like ropes or netting fences. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

**AMD Described it better:** https://gpuopen.com/fidelityfx-superresolution-2/

![image](https://user-images.githubusercontent.com/19660324/160098931-0da5de3b-3d96-43ae-8de7-295cd5086bcc.png)

[[All images ZIP – 155MB](https://gpuopen.com/wp-content/uploads/2022/03/AMD_FSR2_Deathloop_GDC_comparison_all_images.zip)]

[Scene 1 – Native](https://gpuopen.com/wp-content/uploads/2022/03/1C-AMD%20FSR%202%20Deathloop%20GDC%20comparison%204K%20native%20screenshot.png?imbypass=true)
[Scene 1 – Quality](https://gpuopen.com/wp-content/uploads/2022/03/1D-AMD%20FSR%202%20Deathloop%20GDC%20comparison%20Quality%20Mode%20screenshot.png?imbypass=true)
[Scene 1 – Balanced](https://gpuopen.com/wp-content/uploads/2022/03/1E-AMD%20FSR%202%20Deathloop%20GDC%20comparison%20Balanced%20Mode%20screenshot.png?imbypass=true)
[Scene 1 – Performance](https://gpuopen.com/wp-content/uploads/2022/03/1F-AMD%20FSR%202%20Deathloop%20GDC%20comparison%20Perf%20Mode%20screenshot.png?imbypass=true)
[Scene 2 – Native](https://gpuopen.com/wp-content/uploads/2022/03/2C-AMD%20FSR%202%20Deathloop%20GDC%20comparison%204K%20native%20screenshot.png?imbypass=true)
[Scene 2 – Quality](https://gpuopen.com/wp-content/uploads/2022/03/2D-AMD%20FSR%202%20Deathloop%20GDC%20comparison%20Quality%20Mode%20screenshot.png?imbypass=true)
[Scene 2 – Balanced](https://gpuopen.com/wp-content/uploads/2022/03/2E-AMD%20FSR%202%20Deathloop%20GDC%20comparison%20Balanced%20Mode%20screenshot.png?imbypass=true)
[Scene 2 – Performance](https://gpuopen.com/wp-content/uploads/2022/03/2F-AMD%20FSR%202%20Deathloop%20GDC%20comparison%20Perf%20Mode%20screenshot.png?imbypass=true)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope, not even close. Unlike FSR 1.0 this feature must be enabled on rendering pipeline, so Vector Data and Previous Frames will be available for the algorithm.

### Is there a reason why this should be core and not an add-on in the asset library?

Unlike FSR 1.0 this feature must be enabled on rendering pipeline, so Vector Data and Previous Frames will be available for the algorithm. Only with this data small and thin details can be saved on the output.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/3401, which is a prerequisite for this proposal to be implemented (as motion vectors are required).

Some notes:

- FSR 2.0 does not have a Vulkan version yet – it's currently limited to Direct3D 12.
- FSR 2.0 isn't open source yet.

**Comment by Rinocrosser** [comment]
> Remember that this is a temporal upscaling algorithm, and these aren't cheap to run on very low-end GPUs (like integrated graphics). FSR 2.0 should work out nicely on mid-range dedicated graphics, but old/low-end dedicated GPUs might struggle with it too (except if targeting 30 FPS).

> For mobile, https://github.com/godotengine/godot-proposals/issues/3786 (which is a derivative of FSR 1.0) will likely remain the best approach for the foreseeable future.

For my own projects Mid-range devices are probably even more important area, and also, if internal solution with TAA is possible outside of FSR, it's fine to have it. If FSR 2.0 will have Vulkan version, it's also fine to see, which one is better.

**Comment by yhyu13** [comment]
@Calinou 

> FSR 2.0 does not have a Vulkan/GLSL version yet – it's currently limited to Direct3D 12/HLSL.

Do you mean the shader code or does FSR 2.0 relies on DX specific APIs?

**Comment by Calinou** [comment]
FSR 2.0 is out in Deathloop (but its code hasn't landed on GPUOpen yet). Here's a comparison against native rendering and DLSS: https://www.techpowerup.com/review/amd-fidelity-fx-fsr-20/

FSR 2.0 seems to compare favorably to DLSS, and it can even be paired with dynamic resolution scaling.

**Comment by Zireael07** [comment]
> motion vectors

Does that mean we're finally getting built-in motion blur in Godot?

**Comment by Rinocrosser** [comment]
> Does that mean we're finally getting built-in motion blur in Godot?

Yes, it would be great to have the ability to build a proper motion blur (currently, you can make camera-based one)

**Comment by Rinocrosser** [comment]
In addition, it seems, that FSR 2.0 is not just good, but "Better than native" even at 4K resolution, it nearly eliminates common AA artifacts, like shimmery lines:

https://www.youtube.com/watch?v=s25cnyTMHHM

**Comment by Calinou** [comment]
> > motion vectors
> 
> Does that mean we're finally getting built-in motion blur in Godot?

Motion blur is not planned for 4.0, but contributions on this subject are welcome. Since motion vectors will be exposed to custom shaders, it should also be possible to write a shader that makes use of it.

**Comment by Rinocrosser** [comment]
> https://github.com/GPUOpen-Effects/FidelityFX-FSR2 The source code for FSR 2.0 is now available.

The recent Alpha 10 also features TAA, which means, they implemented vector data and are able to implement FSR 2.0 (or the equivalent).

**Comment by Anutrix** [comment]
With Beta(feature freeze) being so close, just wanted to know if this will make it to 4.0.

It took less than 90 mins for Spartan Engine on live stream(https://www.youtube.com/watch?v=QhyMal6RY7M). And we know that every engine is different, we think it's possible for interested Godot Devs to make it before Beta.

**Comment by Anutrix** [comment]
Thx for the info.

> It's debated whether removing TAA in favor of FSR 2.0 is currently a good idea, as FSR 2.0 is currently not designed to provide TAA at native resolution. It can be done, but it'll have a much larger performance impact compared to traditional TAA (albeit with higher quality/less blurriness, I presume). [↩](https://github.com/godotengine/godot-proposals/issues/4280#user-content-fnref-1-eae18f9eba63576a25da7f3404d739c2)

I agree that it shouldn't replace TAA. And if it's possible to keep it neat and maintainable, keeping both TAA and FSR 2.0 as options would nice. Good to know the status.
Will Wait For it in Godot 4.1, if not 4.0.

**Comment by SegoItCh** [comment]
There is FSR 2.2 already, very thicc

**Comment by TheJackiMonster** [comment]
I've implemented [a way](https://github.com/GPUOpen-Effects/FidelityFX-FSR2/pull/60?notification_referrer_id=NT_kwDOANOZhbM0NTEyMTY5NDY0OjEzODY3Mzk3#issuecomment-1452817440) to build FSR2 for UNIX-based operating systems without relying on Wine now. Maybe this helps getting FSR2 into Godot. Let me know if you need any further help to build it.

**Comment by duplexsystem** [comment]
I would like to note here that the first step integrate AMD FSR 2.x into Godot it to migrate the existing FSR 1.0 implementation to ffx-fsr2-api because the original version appears to be unmaintained. For those unaware ffx-fsr2-api contains a spatial upscaler (fsr1) in addition to a temporal upscaler (fsr2). This should be an easy PR I can do if no one has any objections, also thanks @TheJackiMonster that was the reason I didn't try and make the aforementioned PR a while ago (I have been watching this issue for sometime)

**Comment by clayjohn** [comment]
> duplexsystem

Feel free to look into it! I am not certain that the FSR2 spatial upscaler is a drop-in solution for FSR 1 as I understand they are processed in different stages of the pipeline. But it is definitely worth checking out. It would be nice to reduce our external dependencies . 

Are you comfortable taking a stab at implementing FSR 2.x at the same time?

**Comment by TheJackiMonster** [comment]
> I would like to note here that the first step integrate AMD FSR 2.x into Godot it to migrate the existing FSR 1.0 implementation to ffx-fsr2-api [...]

I would recommend to offer both (FSR 1 and FSR 2) since they might have different advantages depending on the game. For example FSR 2 can not handle animated textures without manually hacking in proper motion vectors for those. FSR 1 on the other hand does not have issues with those.

So since we can't estimate what kind of games people create and which features they use, it should be best for developers to decide which option they include for upscaling.

**Comment by duplexsystem** [comment]
> > duplexsystem
> 
> Feel free to look into it! I am not certain that the FSR2 spatial upscaler is a drop-in solution for FSR 1 as I understand they are processed in different stages of the pipeline. But it is definitely worth checking out. It would be nice to reduce our external dependencies .
> 
> Are you comfortable taking a stab at implementing FSR 2.x at the same time?

Yeah I think there are some nuances with tone-mapping and such but considering it's already a part of FSR 2's api it's probably the right path forward to use it. And I can take a stab at FSR 2 (spatial) but no promises :P.

**Comment by duplexsystem** [comment]
> > I would like to note here that the first step integrate AMD FSR 2.x into Godot it to migrate the existing FSR 1.0 implementation to ffx-fsr2-api [...]
> 
> I would recommend to offer both (FSR 1 and FSR 2) since they might have different advantages depending on the game. For example FSR 2 can not handle animated textures without manually hacking in proper motion vectors for those. FSR 1 on the other hand does not have issues with those.
> 
> So since we can't estimate what kind of games people create and which features they use, it should be best for developers to decide which option they include for upscaling.

Sorry I don't thank you understood what I said. FSR 2 the API/Gtihub repo has a spatial upscaler (named fsr1) which should take the place of the spatial upscaler from the FSR 1 API/Github repo as it's currently unmaintained. I was saying I think the first step to adding FSR 2 the temporal upscaler (named fsr2) into Godot would be to replace the spatial upscaler from the FSR 1 API/Github repo with the one from the FSR 2 the API/Gtihub repo. This has nothing to do with getting rid of a spatial upscaler :)

**Comment by Butzwack** [comment]
AMD just released their FidelityFX SDK.
Announcement:    https://gpuopen.com/learn/fidelityfx-sdk-available-now/
Github repo:   https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK

I don't know much easier this would make the FSR2 implementation, but it includes Variable Rate Shading #3859, Constrast-adaptive Sharpening #1519 and Single Pass Downsampler #3179, effectively killing multiple birds with one stone.
Ray tracing isn't a priority for Godot right now, but the SDK also provides a denoiser and hybrid implementations of reflections and shadows with a reasonable performance cost, which could be useful a few minor versions down the line.

**Comment by Calinou** [comment]
> but it includes Variable Rate Shading https://github.com/godotengine/godot-proposals/issues/3859

Note that VRS is already implemented in the engine since Godot 4.0. What we're missing is a built-in way to automatically generate a VRS density map based on motion vectors, previous frame brightness, etc.

**Comment by TheJackiMonster** [comment]
> AMD just released their FidelityFX SDK. Announcement: https://gpuopen.com/learn/fidelityfx-sdk-available-now/ Github repo: https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK
> 
> I don't know much easier this would make the FSR2 implementation, but it includes Variable Rate Shading #3859, Constrast-adaptive Sharpening #1519 and Single Pass Downsampler #3179, effectively killing multiple birds with one stone. Ray tracing isn't a priority for Godot right now, but the SDK also provides a denoiser and hybrid implementations of reflections and shadows with a reasonable performance cost, which could be useful a few minor versions down the line.

The most issues will be related to AMD only releasing the SDK for Windows at the moment using Windows specific binaries. It's pretty similar to many of the FidelityFX projects using HLSL shaders which do not work properly with [glslangValidator](https://github.com/KhronosGroup/glslang) yet. For their ray tracing tools you need the denoiser for example which relies on HLSL shaders and those seem to require a different shader compiler than glslangValidator (most likely [DXC](https://github.com/microsoft/DirectXShaderCompiler) which has some issues on Linux from my [experience](https://gitlab.uni-koblenz.de/vulkan2021/vkcv-framework/-/merge_requests/114)).

Two things I definitely like about that release:
- They finally published the [source code](https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/blob/main/sdk/tools/ffx_shader_compiler/src/hlsl_compiler.cpp) used for their custom shader-compiler front-end (which I needed to reverse engineer for FSR2 to have something similar on Linux without wine). ^^'
- Given that they bundle FidelityFX projects now, they will likely all have Vulkan support in the future (The newest projects already supported Vulkan and DirectX but it was never fully clear they would implement Vulkan support in every case).

**Comment by DarioSamo** [comment]
I've been prototyping (at least on Windows so far) what exactly an integration would require and ran into some key decisions that might be necessary.

I've posted all my findings in a [document](https://docs.google.com/document/d/1ojG_OcoXFwlP4qG2VpKu0WyDBEGLK0qyvbn_ccsDRn4/edit) for anyone who wishes to take a look and provide some feedback.

The one key decision as explained in the document would be to decide to choose either integration route: use the existing (and more convenient) APIs that take native resource handles or spend the time and effort for an implementation that uses the FSR interface and integrates into Godot's RenderingDevice (which is up for debate as it'll possibly get refactored in the near future).

There's some other key problems that have been identified due to lack of motion vector information which might need to be split off into its own issue reports and PR as they'd fix problems in the existing TAA implementation as well.

**Comment by Calinou** [comment]
> The one key decision as explained in the document would be to decide to choose either integration route: use the existing (and more convenient) APIs that take native resource handles or spend the time and effort for an implementation that uses the FSR interface and integrates into Godot's RenderingDevice (which is up for debate as it'll possibly get refactored in the near future).

I'm split about which approach is best for Godot here.

Solution A would allow shipping FSR2 as a DLL on Windows, but it can't be used on macOS at all (and not on Linux either to my knowledge, or not with dynamic libraries at least). The nice thing about shipping FSR2 as a DLL is that it allows players to update the library themselves without requiring developer intervention. This can be used to improve the appearance of upscaling post-launch if a game is no longer being supported by its developer, and is a common tweak performed with DLSS. With FSR2, it's possible to link statically or dynamically. It seems AAA games roughly have a 50/50 split there.

Solution B would better fit Godot's single-binary ethos, which aims to avoid requiring any auxiliary files to work (for non-Mono builds).

**Comment by DarioSamo** [comment]
> Solution A would allow shipping FSR2 as a DLL on Windows, but it can't be used on macOS at all (and not on Linux either to my knowledge, or not with dynamic libraries at least). However, it also has a significant upside: shipping FSR2 as a DLL allows players to update the library themselves without requiring developer intervention. This can be used to improve the appearance of upscaling post-launch if a game is no longer being supported by its developer, and is a common [tweak performed with DLSS](https://github.com/emoose/DLSSTweaks). With FSR2, it's possible to link statically or dynamically. It seems AAA games roughly have a 50/50 split in terms of whether they go with static or dynamic linking for FSR2. DLSS doesn't provide a choice – it's always dynamically linked. Another upside of this approach is that we could use the D3D12 version of FSR2 directly when using the D3D12 rendering backend in Godot.

I should note that Solution A is actually using static linking even on my prototype. Using the DLL was phased out by AMD a while ago with 2.2 and static linking is the preferred way of shipping FSR2. In fact, integrating Solution A would require the work of porting over the build system from the repository and compiling the shaders, so I'm fairly sure it'd still work in the supported platforms with enough effort.

I believe the shimmering in Bistro is possibly related to the jittering suffering from deviation at long distances with very thin objects, but I'm unaware how other engines fix this issue in raster (as my background for using this comes from RT rendering and it's not so visible there). It'd be interesting to get some input from people who've experienced this issue if possible.

**Comment by DarioSamo** [comment]
After some discussion with @clayjohn we determined Solution B seems like the most reasonable long term approach, so I'll likely dive into prototyping that later and see if there's any blockers with the current RD.

**Comment by DarioSamo** [comment]
Happy to report my prototype with Solution B is currently working in this branch. Feel free to give it a go if you're curious, but ghosting issues are expected until the rest of the problems identified in the document are solved.

https://github.com/DarioSamo/godot/tree/fsr2-rd

Most of the issues pointed out in the document still remain to be solved, although some of them like motion vectors for animated meshes are now part of the upstream as of this month. 

There's a PR which might be of interest to use as the basis for refactoring this implementation into a rendering effect instead of adding the option as it is right now.

https://github.com/godotengine/godot/pull/80925

**Comment by romulasry** [comment]
fsr 3, some may guess in early september (6th?)https://www.pcworld.com/article/2041810/fsr-3-amds-open-dlss-3-rival-starts-supercharging-games-in-september.html. See:

**Comment by Rinocrosser** [comment]
> fsr 3, some may guess in early september (6th?)

Open Source version will be available much later

**Comment by TheJackiMonster** [comment]
@Rinocrosser They stated though it will be part of their [FidelityFX SDK](https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK) which aims to support DX12 and Vulkan. So I assume we will see Vulkan support when it's released open-source on Github or at least after some delay.

**Comment by mrjustaguy** [comment]
That doesn't mean that AMD's Driver solution that he's talking about will be able to work on Vulkan.

**Comment by Rinocrosser** [comment]
> FSR 2 PR is out as a draft - [godotengine/godot#81197](https://github.com/godotengine/godot/pull/81197)

Thanks a lot! Any known issues?

**Comment by mrjustaguy** [comment]
Likely, but I'm unaware of any right now, but I'll get to testing it as soon as the artifacts are done

**Comment by TheJackiMonster** [comment]
> That doesn't mean that AMD's Driver solution that he's talking about will be able to work on Vulkan.

DXVk exists, right?

**Comment by TheJackiMonster** [comment]
> That doesn't mean that AMD's Driver solution that he's talking about will be able to work on Vulkan.

As far as I understand it AMD's driver solution only applies to Windows since it will be available as toggle via their Radeon driver software. So I'm not sure whether it makes sense to consider supporting that over an FSR3 implementation inside the engine or game anyway? I think they pitched it as optional feature for older games which do not see any integration ever.

**Comment by DarioSamo** [comment]
There should be no concern over APIs right now if the implementation on the PR is followed. It's implemented on top of Godot's own abstraction which should run in all backends supported by Forward+ at the moment (which is just Vulkan but DX12 backend is in another PR).
