### ISSUE TITLE
Objects in 3D or 2D editors should have to be selected before moving

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#431]
**Describe the project you are working on:**

Non-released project

**Describe the problem or limitation you are having in your project:**

The user experience of editing 3d objects in the scene is frustrating.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

When a developer wants to edit a potted plant in the 3d scene, they will often misclick the ground and move it directly.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

Behaviour before: 

* Wants to edit the shader of a potted plant in the 3d scene
* Misclicks the ground and moves it directly
* Must reset the ground transform
* Clicks on the potted plant
* Edits shader

Behaviour after:

* Wants to edit the shader of a potted plant in the 3d scene
* Clicks on the ground will select the ground, not moving the ground
* Clicking on the potted plant model will select not *move* it
* Can now change the shader

Here are some test cases. Please comment if they're in error.

* Given any unselected objects, clicking on one will select it and it will not be moved.
* Given selected objects, clicking on any unselected object will select it and it will not be moved.
* Given selected objects, shift clicking on any unselected object will add to selection and it will not be moved.
* Given one or more selected object, with shift clicking on an selected object will cause all objects to be moved.
* Given any objects and one is selected, clicking on the unselected object will cause it to be selected and not moved.
* Given selected objects, clicking on any selected object will move the group.

**Describe implementation detail for your proposal (in code), if possible:**

https://github.com/fire/godot/tree/select_usability 

A buggy prototype.

Not implemented yet, an editor setting to revert to current behaviour.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, the behaviour of the 3d editor cannot be modified through script.

**Is there a reason why this should be core and not an add-on in the asset library?:**

3d editing is a core feature.

**Comment by fire** [comment]
Here's a video of my prototype:

[Video](https://imgur.com/IwfCycO)

Flaws in my implementation, there's an off by one in selecting.

**Comment by fire** [comment]
Here is the existing behaviour.

https://imgur.com/rQPdlSS

**Comment by fire** [comment]
Here is the existing behaviour:

https://imgur.com/AVXbu5A

**Comment by golddotasksquestions** [comment]
> Given selected objects, clicking on any selected object will move the group.

I don't know a single usecase where a simple click should move anything in the editor.
Do you mean "Given selected objects, **left-click** on any selected object **+ drag** will move the group."


> Given one or more selected object, with shift clicking on an selected object will cause all objects to be moved.

May I ask what the purpose of this rule would be?
Assuming you meant "Given selected objects, **left-click** on any selected object **+ drag** will move the group." with the other rule, pressing shift would be of no effect.

I would much rather have:

- Given selected objects, **left-click** on any selected object **+ drag** will move the group.

and

- Given one or more selected object, with shift clicking on an selected object will cause **the object that is left clicked to be removed from the selection group.**

**Comment by fire** [comment]
How would you solve this?

When a developer wants to edit a potted plant in the 3d scene, they will often click the ground and move it. They would rather edit the shade of the potted plant to be a different colour.

> Given selected objects, left-click on any selected object + drag will move the group.

This is the wrong behaviour. 

What I did in this prototype is, you must first select the object and then drag on it again to move it.

After an object is selected, you can select more objects. The second click does the transform move.

> Have the ability to lock objects as being not selectable and not movable. This already exists, it's not reliable because of nested scenes.

**Comment by fire** [comment]
> Given one or more selected object, with shift clicking on an selected object will cause all objects to be moved.

Another way of saying this is:

There are two modes. 

1. Objects are not selected.
2. Once selected, you can move the object. There is a ray trace to the object and it returns true and shift is not held, moving the mouse will move the object.
3. Once selected, you can move the object. Clicking on an selected object will cause the object that is left clicked to be removed from the selection group.

What you're saying makes sense.

**Comment by fire** [comment]
Once selected, there is a behaviour where clicking any object will deselect all objects and then pick the current object under the mouse.

With selection and shift, clicking on an additional object will deselect it!? and then the behaviour for moving objects triggers. So it deselects and then moves the other members of the selection group. However you mouse is still at the deselected object's x-y screen position.

I got stuck here. Any suggestions? See the video.

**Comment by golddotasksquestions** [comment]
Left click select and drag should be left click select and drag. It's like that everywhere with (universal) multi tools.
If we change that behaviour to left click then leftclick again to move, it's again a Godot-unique ideocracy. That's muscle memory people will have to unlearn and relearn just for Godot.

Leftclick select and leftclick select + drag are two different inputs. With one the user wants to only select, with the other the user has made up their mind they also want to move the object (provided they do this with the universal multi tool.

Currently, neither seems to work for me:
https://i.imgur.com/4IrLidk.mp4

I gave up figuring out how and select objects in the scene tree and only move them with the gizmo arrows. Which sucks and is slow as fukc.

**Comment by fire** [comment]
Here is the comparison in Blender. https://www.youtube.com/watch?v=RWjlA7ggTXg&feature=youtu.be

Notice that Godot Engine matches neither tool.

This patch attempts to implement the second tool in the video from Blender. I think the second tool is the functionality people expect.

**Comment by golddotasksquestions** [comment]
Myself and many of my colleagues have shied away from using Blender for as long as they could **exactly** because Blender does many things it's own way. Even though blender is free. Even though they then have to use expensive proprietary software. Blender is really not the best example.

**Comment by fire** [comment]
I didn't want to record Unity...

Anyways, here's a video of the blender tool. https://youtu.be/kUlF6HkXPus

**Comment by fire** [comment]
Given the difficulty of changing defaults, I was thinking of adding a "transform" mode button that does this mode.

**Comment by Seel** [comment]
What about adding a bit of hysteresis. When you click on something you often move the mouse a bit just coincidentally, if those small movements are disregarded for starting movement it might already help a lot.

**Comment by southpaw-decoy** [comment]
This aggravates me so much. Especially since the tool tip shows that alt drag should move. 

![image](https://user-images.githubusercontent.com/67489028/85909331-5b945e80-b7e7-11ea-82dc-cfa0d5d4ed5d.png)

So how this should work, is dragging should always box select. Holding alt and dragging should move whatever you were on when started the click on the drag.

**Comment by Flavelius** [comment]
Still an issue in 3.2.4.rc4 this accidental displacement happens way too often.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/49310, closing. The exact implementation is different from the original proposal, but it fulfills the same need.

**Comment by Flavelius** [comment]
Does the linked commit prevent unwanted drags? Because rect-select is not possible while dragging implicitly moves an object no matter If it's thresholded.

**Comment by Calinou** [comment]
> Does the linked commit prevent unwanted drags? Because rect-select is not possible while dragging implicitly moves an object no matter If it's thresholded.

It should prevent unwanted drags regardless of the node is previously selected or not.
