### ISSUE TITLE
Add a GDScript <-> VisualScript converter

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#4312]
### Describe the project you are working on

Games

### Describe the problem or limitation you are having in your project

it isn't a limitation, but it is an enhancement.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like to see and option to convert/switch between visual script and GDscript, also if we get inheritance between the two that would be better,
now a workflow like this would help a designer to view or edit a script using visual script, and a normal programmer would open the GDscript to write his code fast.
I believe it is a very good feature for teams.
or even if someone makes a system in Godot(ex: a third person shooter) he writes it normally in GDscript, then if there is a game designer who is going to use the template, he opens it in visual script.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I am not sure about the best way to implement a feature like this, but there are two options in my mind:
1- make visual script generate always GDscript instead of binary and get rid of the visual script virtual machine.
2- make a converter between the two and when you click a button "switch language" it converts the stuff behind the scenes, but I think this won't allow inheritance between the two languages.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I don't think a few lines of script could implement this :)

### Is there a reason why this should be core and not an add-on in the asset library?

maybe someone could make an asset converter between visual script and GDscript, but I think it won't be working the right way because it isn't done directly in the engine.

**Comment by Calinou** [comment]
In the past, this was already proposed in https://github.com/godotengine/godot-proposals/issues/1135, but it was rejected.

**Comment by ywmaa** [comment]
also how about a Visual Script node that can hold "GD script expressions/code", for example any GDscript converted to Visual script converts stuff like (Functions,variables,signals) and if there is a advanced GD script code that doesn't exist in Visual script, Visual script creates an expression node and puts the advanced code in it.

the problem is that the stuff above is a whole another feature.

**Comment by mrjustaguy** [comment]
VS is not really that limited, it's more that it's horribly complex compared to GDScript, while not even totally following it's workflow making such a converter a stupidly hard thing to implement.. I've tried, and ended up with a 10k lines of GDScript, and that was without the logic to deal with any complex noodles of arguments.. For this to be implemented, one would have to scrap the current Visual Script, and build one from the ground up with the conversion in mind.. Such a feat is just a ton of wasted resources, however it'd probably even improve VS usability a ton even if you ignore the conversion capabilities it'd have.

Here are some examples of issues that a VS<->GDScript converter would have to deal with:
1) Figure out I/O, as some Inputs are vastly different syntax in GDScript compared to others
2) Correctly detect and Construct/Deconstruct Arguments
3) Make special behavior for dealing with some Specific VS Node Types

**Comment by ywmaa** [comment]
I also love GD script, I feel that text-based programming is better for organizing the code.

but I see this feature as a big feature for designers.

now for how hard GD script/visual script converter

that's why I suggested making visual script generate GD script code instead of binary code, but it looks like this is also hard and can't be altered on the current VS script(it will need to be built from the ground ).

now for the visual look for VS script 
we can do something like unreal engine does which is group nodes in one node that makes a seperate graph (**not generating seperate script**, same script but with multiple graphs)
but I think this is another feature that isn't really related to our topic here (I mean that this could help our situation with how complex the look of visual script).

**Comment by Zireael07** [comment]
@ywmaa: I understand grouping is being now done as part of GSOC

**Comment by ywmaa** [comment]
Since visual script is going to be removed, I think I should close this issue,
Also I think removing visual script is good,
For me I may have some time to try to build a visual script for Godot with converter in mind and high level visual scripting for artists
