### ISSUE TITLE
Allow dragging particles "Min" and "Max" values at the same time

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-proposals#4315]
### Describe the project you are working on

Godot Kart Racing

### Describe the problem or limitation you are having in your project

When you mess with particles, and want the size to be always the same value in min-max parameters  you have to do manually!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

the solution is a shortcut key, look the image below:

![image](https://user-images.githubusercontent.com/58845030/161064379-aafc2a6c-553a-4695-819f-5a30e1baab14.png)

when the user want the both min and max to be the same he can simply HOLD `ALT` key and move the slider of min or max param and both will have same value!

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

* User hold ALT key and params move at same time!

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Its an usability feature.

### Is there a reason why this should be core and not an add-on in the asset library?

its essential to core usability!

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/144.

**Comment by KoBeWi** [comment]
As a workaround, change `min` when increasing value and change `max` when decreasing. The other value will get automatically clamped.

**Comment by Calinou** [comment]
We could also provide an additional way (e.g. a key modifier) to adjust min/max properties to be closer or further away from each other, so that you can effectively adjust randomness in one go.
