### ISSUE TITLE
Disable 3D depth prepass by default to improve performance

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#4322]
### Describe the project you are working on

Complex 3D Game

### Describe the problem or limitation you are having in your project

Depth Prepass adds insignificant performance improvements in Complex Scenes (1920x1080, Full Screen 20+ Overdraws, 32m primitives drawn, no shadows (aren't affected by setting), 30 Full Screen Lights, on a GTX 1050 Ti)

20 Full Screen overdraws, 30 Full Screen Lights, 32m primitives drawn

DP On +5% perf
With Depth Prepass On - ~210ms/frame
With Depth Prepass Off - ~220ms/frame

Remove artificial 20 Full Screen overdraws into a more realistic 10 Full Screen overdraws

10 Full Screen overdraws, 30 Full Screen Lights, 32m primitives drawn

DP On +0% perf
With Depth Prepass On - ~120ms/frame
With Depth Prepass Off - ~120ms/frame

5 Full Screen overdraws, 30 Full Screen Lights, 32m primitives drawn

DP On +0% perf
With Depth Prepass On - ~70ms/frame
With Depth Prepass Off - ~70ms/frame

Two Full Screen overdraws, 30 Full Screen Lights, 32m primitives drawn

DP On -12% perf
With Depth Prepass On - ~45ms/frame
With Depth Prepass Off - ~40ms/frame

20 Full Screen overdraws, 15 Full Screen Lights, 32m primitives drawn

DP On +3% perf
With Depth Prepass On - ~115ms/frame
With Depth Prepass Off - ~118ms/frame

10 Full Screen overdraws, 15 Full Screen Lights, 32m primitives drawn

DP On -11% perf
With Depth Prepass On - ~78ms/frame
With Depth Prepass Off - ~70ms/frame

10 Full Screen overdraws, 15 Full Screen Lights, 33k primitives drawn

DP On -3% perf
With Depth Prepass On - ~60ms/frame
With Depth Prepass Off - ~58ms/frame

5 Full Screen overdraws, 15 Full Screen Lights, 33k primitives drawn

DP On -8% perf
With Depth Prepass On - ~37ms/frame
With Depth Prepass Off - ~34ms/frame

5 Full Screen overdraws, 15 Full Screen Lights, 32m primitives drawn

DP On -9% perf
With Depth Prepass On - ~45ms/frame
With Depth Prepass Off - ~41ms/frame

3 Full Screen overdraw, 15 Full Screen Lights, 32m primitives drawn

DP On -8% perf
With Depth Prepass On - ~36ms/frame
With Depth Prepass Off - ~33ms/frame

Conclusion: Depth Prepass is useful when there is very extensive overdraw, with a ton of lights covering large portions of the screen, however when this is not the case (which is most often the case, especially with occlusion culling), it harms performance, especially when there is a ton of geometry being rendered.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Turning off Depth Prepass by default and advising users to use it only if they aren't using Occlusion culling and are using a lot of lights and have a ton of overdraw issues. This will improve performance in 95% of real world scenes, with the 5% of scenes that would suffer from performance issues being scenes that are most likely due some optimizations like Occlusion culling anyway.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change Default from on to off.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but often times users stick to defaults due to a lack of understanding of what's going on.

### Is there a reason why this should be core and not an add-on in the asset library?

Core Setting.

**Comment by Calinou** [comment]
Could you upload the scenes in question somewhere so other people can try to reproduce your results on various GPUs and screen resolutions?

**Comment by clayjohn** [comment]
This warrants some investigation, currently there is a bug in the depth prepass where it runs much slower than it should. Oddly enough, the cost of the depth prepass reduces when using screen-space effects like SSAO (in such cases the depth prepass also writes out roughness and normals). This was a huge problem for me when porting ASSAO because the engine was reporting a higher frame rate when SSAO was enabled than when it was disabled. 

I have a feeling that, once we fix the bug in depth prepass, your results will be different.

**Comment by mrjustaguy** [comment]
The Scene is just N number of Quads (100x100) a couple of units from the camera, and M number of 500 range 100 energy omni lights at camera, with a 8 instances of I think about ~1.3m triangle meshes each taking about 30% of Screen Space each, However I'm not able to provide those specific Meshes, behind the quads and a couple of instances of Godot's Spheres also behind the quads.

**Comment by mrjustaguy** [comment]
Hm, Godot's getting a Deferred renderer Right? 
If so I think it might be ok to stick this setting as is (especially if it's currently broken and not representative of what it'll be like), as with it off, if you go make too much of overdraw even on simple geometry like 1k full screen quads in overdraw performance goes to hell without it due to lighting calculations, so this would probably keep performance more stable for users that don't bother to do occlusion culling and if users desire more performance they'll probably go with the Deferred renderer which won't suffer from this type of issue as well as use Occlusion Culling...

**Comment by mrjustaguy** [comment]
Upon further investigation, this is setting should be kept enabled, as the performance hit isn't sufficient, and in more diverse environments that are quite dynamic, the Framerates are more consistent with Depth Prepass enabled, and while there is a 5-10% avg performance improvement from disabling it, the lows can get hurt by up to 20% by doing so, as it seems Depth Prepass can be of massive help in some very hard to pin point for benchmarking cases that would aren't all that uncommon to crop up during actual gameplay.

In addition Depth Prepass seems to not perform as well as it should right now ( https://github.com/godotengine/godot-proposals/issues/4322#issuecomment-1086181257 )

**Comment by clayjohn** [comment]
Thank you for your detailed investigation!
