### ISSUE TITLE
Implement OpenReEncab software-defined encabulation functions

### ISSUE THREAD

**Issue by novaplusplus** [godotengine/godot-proposals#4328]
### Describe the project you are working on

A deeply-geared and emotional simulation project detailing the progression of the Carlyle Brigade in the 1640s, but this proposal is applicable to a great many games and even software designs.

### Describe the problem or limitation you are having in your project

A lack of encabulation deeply limits the fidelity and fungibility of many assets in the simulation which focus testing has shown results in a greatly degraded player experience and tangible connection without the increased audiovisualneural (AVN) fidelity offered by what could be achieved with the inclusion of proper encabulation libraries.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

See below.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The crux of this proposal is simply implementing the OpenReEncab library into the Godot engine. It has the simpler alpha AND gamma function syntax compared to previous libraries and, unlike most others, is a ground-up reimplementation from the same paganic linear algebraeic principles that was both highly optimized and human readable, as well as licensed under MIT instead of the usual GPL (so, arguably more compatible with Godot). The dependancies are small (mainly consisting of the `prefamulated_amulite.h` header commonly available and thankfully originally released into public domain in 1987)

The Buddington encabulation string syntax can be difficult to understand at first, and the libraries will require some deeper engine hooks than a simple module (hence this being a proposal and not a PR!) but it would enable some extremely modern neuro-graphicular advancements. Take this code snippet for example:

```
auto x = Encabulation::encabulate("A¡ºØØÍÝç¬ÛUÆätèUvèe/Wáô¯,d<C¢TôoÌÚíú×ÍgÙI»Ò¯57¹&ý3A5ËC!UÅÕaQù\}Pt"KçR°1³`ª²Ì9æäÏ},Y×ïÍ¯Ô²ûÉzÞt^©qËw.JèZ:ÂÑkûóa¹¢%ÒÇfÂ+»n³¦4Þ¹Îr£yÿm®)Ù{C»¯j[¹o/öø.õ#µfÝÏ¯üh{æËöÞ³o"D²²â¬gËH8åô^½^i0×ú-Éâr@KµOËHä5p;+1å8øïâù.ë1|QNàD!4·Ë¯;help&3LBÔi'mõ^æ_lKv´ästucköúí3MÅgÒ'âsin¸T«akF|=ºCan3Ìª8=_ÊjMHrílùencabulationÌD¨¬÷íXsöÆsÜ!*Ëtífactory¶Ç*ÉsCqÏï±Æ3'\±6úEí9C}¾Ï^«VENpTó<~ºJÍaÇ÷"ê®(ù.^Õ§ÌY§TO¯ÎÛªèÃLÃG/r.©þÎ:*¥[åªsÏ<?1ÖËäøapOÑè1àU3/÷ÔdØRêj7|ugs¸å_3Ñ¨Õ·`}%ü\1úü°VåF§<Én,EY¢>b5nüt:ÎÒ|yÂ~~PÀ94~u¸Õý0g,÷®ÚÞÛpÅhAnsyéì`ÃVD$¹5²O>5zIÔ,ÿiê§[Ü^·Jí4QÆ,jÚÍ»%þó¥É¥ÕÝG²¦öøì=ñØ¼F?+Ø");
```
With that simple input string, it will output the following:
```
:PJS]ZK{VLWMZ[[JSHXCMP:YZRV,ED,J;)K;)ETF}A()TPK:M.WVF,MTDHNE]WFHL
,DRDVECPEWCY.;Z[NTCU;QRHWVEVEHHSJAUZCKUQJHM)U]NYQDD)[KCVZFLP
{:}[Z,L){,CVXHE}RPZ{ZFNZ}MM;A,(N][LU}Z{W)F[PE;FZ(S,ZJ,(JXAUS{:ACRU
X]MT.TZNCRAFPFA:U].DNLY.)]X,JYYYMRPLKN}{CSAVSWCZQKCR}YAARM])E];E
KW)XAMDQXPEKQ)E]R()EZYY[(W..EV]RFMAEHZ}]SU}(N[AM][LKT{,CX[MN:[RZ
(CJW:KZ.KSQJERDKRND]FMRVACC].DN.TFH{PR;XT)T[W;)WEDAA
{}UCMA]SPMUFX{MA}JVSC[LN.MHY;NRZXKVVTMHQ[{MFZQHA]LJ,;(PS(;)WHFCTX[,VM}C};HD}DZ[;.JHNJZXHX,J.F]ZNX)

(KF:RAPNC(L;VYU:YR,CVXY:EVN(W,Z:Y{Y]KH:.UYP.WWSZ.XWL;:W]TP,
CVVZH:{Q,X)K}.(UMWPRA,KMMZX]Q.RFTMAS{N]MRAV.HJ;]R]NRP)LP
HL[WP)M]MC(UPLWM(XT:Z.PCHK
(TNYT;.XM:XRJVECKMR{[Z:X(}.T,,UFK:,S}N;HWTVQJQYRSD}(ER:Y].K;.QD]KCALSRCC.MV[{:P))U{K]EERVWZU}A}.H};DDLFA;{K}H}ECR,)VK)QQ(.SRTYQV.PT{DVM{{XYKQA.QXV,

{NCW)HZU(EYP}T;CY]J[EEPKL[K;:N;UWENME;A:Z.FYU.EVXEZERFA};
(WLRZZ.KSW(JV]K]XY]AU;LK]E(WRURW.(::(DEXQRKX}].ZSUAEE}WNXSJHVQLP[UEPAT;QL(U,R
{{FW.VW)XDV.]SDD,ZNKZ,ENAEZWXSYEMSV;LKZ{{(W:V{VZP{}
PU.NSMUXNUH}[J.(QJN)PKX,CMK,X;)[TP;:SD)LKJ.LFL(V{T(HXNFX
```

Which as you can see is a standard AVN string! So, that output, when connected to the proper audiovisualneural harness, can then be processed into an even more proper Turing-Gupta code compatible with all AVN systems. Even better - a 512-character and 3752-bit entropy Buddington-format input string like the one above can be encabulated in only _1.9 milliseconds_ with OpenReEncab, which opens the possibility for doing this not just via desktop but in VR as well. (although caution should be applied as the effects of encabulation in such an immersive environment are not fully understood)

There are OpenReEncab libraries available for x86, Arm, and even a RISC-V version, so there should be plenty of resources available for engine implementation here.

As stated - I would have made this a PR, but it requires deeper knowledge of the engine than I really possess. I think this could help a lot of developers really achieve their visions.

Lots of details on implementation can be found on [openreencab.org](https://en.wikipedia.org/wiki/April_1)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

While modern-syntax encabulation _could_ technically be implemented in GDScript, the language would need to have numerous extensions (AVN hooks, for instance) written for it to be practical, so the C++ side is the primary avenue I would suggest.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes there is

**Comment by Calinou** [comment]
Happy late April fools' day :slightly_smiling_face:
