### ISSUE TITLE
Add a `closed` property to Line2D

### ISSUE THREAD

**Issue by SquiggelSquirrel** [godotengine/godot-proposals#4330]
### Describe the project you are working on

I have been attempting to create 2D puppets/cut-out animations for RPG cutscenes and dress-up games.
I have found it helpful to create shapes with fill & stroke using Polygon2D and Line2D nodes, based on Curve2D objects generated from the position of other Node2D objects (in order to allow the shape to be animated).

I have most recently been working on a plugin to generalise this, which I believe will improve my workflow and may be of help/interest to others:

https://github.com/SquiggelSquirrel/VectorNode

### Describe the problem or limitation you are having in your project

The "stroke" on such shapes will often be closed, however Line2D has no support for closed paths, and no other node seems to be a suitable alternative.

This means that there is always one "joint" which is actually drawn using the start/end caps instead of the joint mode, making it impossible to create a continuous outline render correctly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Before:
![image](https://user-images.githubusercontent.com/6305593/161343489-9c68fcd5-b296-43d9-8840-758b92620051.png)

After (rough drawing):
![image](https://user-images.githubusercontent.com/6305593/161343516-0634c275-3a16-41ad-9ef0-26f08e566a49.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a "closed" boolean property to the Line2D node. If set true, the last point will connect to the first point, rendered as per the joint mode, with no start/end caps.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Sometimes.
For example, if the line has a solid fill, it may be possible to select a different place for the start and end to meet. If both points share the same position and tangent, with no caps, it may look sufficiently like a smooth line.
It can be difficult to select an appropriate place however, especially for lines based on Curve2D baked points, and if gradients, width curves, and textures are applied.

### Is there a reason why this should be core and not an add-on in the asset library?

The add-on would essentially need to re-create Line2D functionality, with this enhancement added on, and would need to be maintained alongside the existing Line2D code. This would result in unnecessary duplicated work on the part of whomever developed/maintained such an add-on.

**Comment by SquiggelSquirrel** [comment]
This is possibly a duplicate (or at least alternative solution) to https://github.com/godotengine/godot-proposals/issues/138

**Comment by Calinou** [comment]
> This is possibly a duplicate (or at least alternative solution) to #138

I prefer this solution to #138 personally – it seems more self-contained and less intrusive to develop and maintain.
