### ISSUE TITLE
Give a consistent name to Godot's shading language

### ISSUE THREAD

**Issue by DeeJayLSP** [godotengine/godot-proposals#4350]
### Describe the project you are working on

A long term game project that, of course, makes use of shaders.

### Describe the problem or limitation you are having in your project

It feels like we're working with a shading language that doesn't have a name, or is named "shader", "shaders" or "Godot". There's no consistent name for the language in the editor or the docs.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Formally give a proper name to Godot's shading language, even if it's the long "Godot Shader Language". Short forms could also be considered.

(I'm aware that .shader files are now .gdshader in 4.0, so maybe that could be considered as a short form).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the documentation, bits of text that look like these:

```
In Godot, all shaders start with a line specifying what type of shader they are.
Shaders style guide
```

Would look like these:
```
In <the chosen language name>, all shaders start with a line specifying what type of shader they are.
<Chosen language name> style guide
```
(These bits have actually been taken from the docs)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is a naming change (or should I say addition) so it's not code related.

### Is there a reason why this should be core and not an add-on in the asset library?

You can't do a core naming change through an add-on.

**Comment by tetrapod00** [comment]
Updated, more specific proposal https://github.com/godotengine/godot-proposals/issues/10784.

**Comment by Mickeon** [comment]
We may want to close this proposal in favour of the latter

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/10784.
