### ISSUE TITLE
Add method to get `MarginContainer` content rect

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-proposals#4360]
### Describe the project you are working on

Making MRP for some GUI related bug.

### Describe the problem or limitation you are having in your project

It's cumbersome to get the content rect / width / height of a `MarginContainer`.

```gdscript
var content_rect := Rect2(
    get_constant("margin_left"),
    get_constant("margin_top"),
    rect_size.x - get_constant("margin_left") - get_constant("margin_right"),
    rect_size.y - get_constant("margin_top") - get_constant("margin_bottom")
)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a `get_content_rect()` method to `MarginContainer`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See problem description.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, about six lines. But still lots of typing.

### Is there a reason why this should be core and not an add-on in the asset library?

Too simple for an add-on. And add-on won't be able to add methods to built-in types.

**Comment by KoBeWi** [comment]
Why do you need the content rect?

**Comment by timothyqiu** [comment]
I want to calculate word wrapped text rect with `get_wordwrap_string_size()`, and draw it on the `MarginContainer`. (... and compare it with how `Label` wraps text.)

**Comment by KoBeWi** [comment]
Eh, that doesn't sound like common problem. You can put an empty Control node into your container and use `get_rect()` on it. But then again, MarginContainer doesn't have any method, so maybe it's ok to add it 🤔

**Comment by YuriSizov** [comment]
I agree with KoBeWi, this is perfectly solvable in the userland. That bit of code is not the most cumbersome you have to write when making more complex and interesting UIs anyway, and can be perfectly put into a helper/util class.

If we were to implement a method like this, it would be reasonable to implement it for other containers, at least some of them. Like panel container that has similar properties, but controlled with a stylebox.
