### ISSUE TITLE
Add an editor setting to control the TextureRegion editor step value

### ISSUE THREAD

**Issue by boruok** [godotengine/godot-proposals#4362]
### Describe the project you are working on

Project with a lot of items and icons

### Describe the problem or limitation you are having in your project

When you add/redo a lot of icons you'll notice that you making following 2 steps:
1. Change snap mode to grid snap
2. Change x step to value power of 2
3. Change y step to value power of 2
4. Drag to mark region

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

You can skip step 2 and 3 if you have preset, value of power of 2 (4, 8, 16, 32...) There is 2 ways to solve this:
1. Expose step value to editor settings
2. Make default value to nearest power of 2 value, which are **8px**

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is core

### Is there a reason why this should be core and not an add-on in the asset library?

This is core

**Comment by RemyAlves** [comment]
Agreed, the time benefit can be pretty amazing!

**Comment by Calinou** [comment]
@RemyAlves Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
