### ISSUE TITLE
Add `find_ancestor` node function

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#4372]
### Describe the project you are working on

A project which divides views into different node trees. 

### Describe the problem or limitation you are having in your project

I would like to get the first parent of a specific type. At the moment I have to do something like this:

```gdscript
const Workspace = preload("res://Workspace.gd")


func find(node: Node):
	var parent = node.get_parent()
	var root = get_tree().root

	while not parent is Workspace:
		if parent == root:
			return null

		parent = parent.get_parent()

	return parent
```

I would like to have a function which can do this faster and more efficiently.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I use this quite commonly and it would be great to have this run in C++ time instead of GDscript time.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`self.find_ancestor("Workspace")` or `self.find_ancestor(Workspace)` when class_name is used.

Will return `null` on failure.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Engine core

### Is there a reason why this should be core and not an add-on in the asset library?

Engine core

**Comment by Mickeon** [comment]
The name of the function could be likely misinterpreted with the already existing [`Node.find_parent()`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-find-parent) or [`Node.is_a_parent_of()`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-is-a-parent-of) (which is actually called [`Node.is_ancestor_of()`](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-is-ancestor-of) in Godot 4.0 to better reflect its functionality)

Is it necessary to have it run as fast as it possibly can? It really does sound like something that would only require updating every so often, as its result can be cached.

> ### If this enhancement will not be used often, can it be worked around with a few lines of script?
>Engine core

That code snippet is technically a valid alternative to the proposition, above.

**Comment by tavurth** [comment]
> as its result can be cached.

I'm looking more for something along the lines of React context, which is updated automatically. Yes it uses caching, but writing memoization for each node is another level and is I believe a good proposal for the core.

If it's not cached in the godot base, then yes speed is important because I'd like to call it often.
