### ISSUE TITLE
Replace root_scale import option with permanent modification to an imported scene's scale

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot-proposals#4379]
### Describe the project you are working on

Shared user-generated content framework for Godot

### Describe the problem or limitation you are having in your project

Kitbash prototyping frequently results in a variety of inconsistently scaled objects, and the current option, root_scale feels both insubstantial and something of a beginner's trap as an approach to the problem.

The reason I consider this approach bad is because it feels inconsistent with workflow that the asset import pipeline is theoretically meant to provide to development; it only affects the base node scale of the root node at the point the instance is added to an existing scene, it is not a permenant change and any attempt to rescale the imported scene after it has already been instantiated will have no effect. I feel very strongly this is a bad approach and would much prefer an option to have the scale applied permentantly to the underlying geometry of the scene.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

My approach would be to provide a different scaling options (and potentially removing the existing root_scale option in the interest of not creating confusion) which instead of just applying a one-off scaling to the root node instead, at import, recursively walks the scenes tree and applies permentant modifications to the underlying imported scene.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Draft PR here
https://github.com/godotengine/godot/pull/60115

After the scene has been imported, the code will recursively walk the tree, checking of any nodes, meshes, or animations and apply the appropriate scaling to them in order to make the effect permenant. Altering this scale and reimporting the scene will affect any existing instances, unlike the root_scale option.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

While an importer script could provide similar functionality, I feel this makes sense as a built-in option since I feel it preferential over the existing approach for the reasons I have laid out, and would I feel it does a better job of encouraging the usage of non-destructive workflows.

### Is there a reason why this should be core and not an add-on in the asset library?

This approach seems vastly more understandable and consistent than the built-in root_scale options, and is also consistent with the import pipeline of other engines.

**Comment by reduz** [comment]
Sounds good, but this is not very easy to do, very welcome if you want to do it.

**Comment by fire** [comment]
Fixed by https://github.com/godotengine/godot/pull/60115.
