### ISSUE TITLE
【HTML5】Will the official version of Godot 4.0 support the HTML5 platform? If so, when will it be available for testing?

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot-proposals#4383]
### Describe the project you are working on

1、Will the official version of Godot 4.x support the HTML5 platform? 

### Describe the problem or limitation you are having in your project

#

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

#

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

#

### If this enhancement will not be used often, can it be worked around with a few lines of script?

#

### Is there a reason why this should be core and not an add-on in the asset library?

#

**Comment by Zireael07** [comment]
Not the place to ask support questions.

**Comment by Calinou** [comment]
Godot 4.x will only support HTML5 once a production-ready OpenGL renderer is implemented. This will take a while to materialize, and may only be done by the time Godot 4.1 is released. Godot 3.x will remain supported for a while anyway.

PS: Please don't ask support questions here, as this issue tracker is meant to be used for feature proposals only. Use one of the other [community channels](https://godotengine.org/community) instead.
