### ISSUE TITLE
New scene save system with JSON

### ISSUE THREAD

**Issue by theludovyc** [godotengine/godot-proposals#4400]
### Describe the project you are working on

I work on this project in a team https://github.com/TeamConfiture/GWJ-43 . You can play it there https://pepotrouille.itch.io/slime-patrick.

### Describe the problem or limitation you are having in your project

When we work on features, we create a branch on master, work on it, and merge it. Sometimes we work on same scene, but not on same things. So in .tscn sub and external Ids can be differents. Plus this thing [gd_scene load_steps=79 format=2].

When I merge, and have conflicts with Ids. I need to change them by hand.

Sometimes merge do not have conflicts but broke things.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

So to improve scene save system, I think use JSON format can be a good start. And after, remove Id numbers, and use Id strings.

I think sub resources can be register in node wich use them to avoid references.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

JSON is already supported by GodotEngine.

First, just change format. I think I can rewrite this function https://github.com/godotengine/godot/blob/12cb05b3040242deebb87262aed8c04218b69044/scene/resources/resource_format_text.cpp#L1587
And do same for load.
I give a link in master, but I'll start with 3.X branch.
I will start try to do this here https://github.com/theludovyc/godot (I am bored to resolve conflicts by hand ^^').

Two, remove Id numbers

Three, test if there are still conflicts in git

Four, make a tool to convert files in old system to new system

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N / A

### Is there a reason why this should be core and not an add-on in the asset library?

Beacause it's save file system

**Comment by Mickeon** [comment]
> When we work on features, we create a branch on master, work on it, and merge it. Sometimes we work on same scene, but not on same things. So in .tscn sub and external Ids can be differents. Plus this thing [gd_scene load_steps=79 format=2].

Regarding Unique Subresource IDs, [it's been implemented](https://github.com/godotengine/godot/pull/50676) and it [may be backported to 3.x](https://github.com/godotengine/godot/pull/50693)

**Comment by theludovyc** [comment]
> Regarding Unique Subresource IDs, [it's been implemented](https://github.com/godotengine/godot/pull/50676) and it [may be backported to 3.x](https://github.com/godotengine/godot/pull/50693)

Hello, thanks for you answer :) !

Look there https://github.com/godotengine/godot/pull/50676#issuecomment-884265363
And there https://github.com/godotengine/godot/blob/12cb05b3040242deebb87262aed8c04218b69044/scene/resources/resource_format_text.cpp#L1620

Use of "itos(index)"

For sub, look there https://github.com/godotengine/godot/blob/12cb05b3040242deebb87262aed8c04218b69044/core/io/resource.cpp#L98

Same problem, but in other place

**Comment by KoBeWi** [comment]
`Resource::generate_scene_unique_id()` generates a unique ID and you are *extremely unlikely* to run into a conflict. The only issue that remains is that `load_steps` might differ.

Also changing format to JSON won't really help as the IDs need to somehow be stored anyway. So you'd get the same result, but with ugly JSON syntax.

**Comment by Mickeon** [comment]
Yeah, I thought the main focus of .tres and .tscn was its readability and general ease of access. JSON is widely used, and there's some editors out there for it, but you can't do this nearly as easily, for instance: https://github.com/godotengine/godot-proposals/issues/3942#issuecomment-1034135636

![SpriteFrames copy pasting example](https://user-images.githubusercontent.com/66727710/153278931-0fd3bf31-d41e-4670-9250-a9e60adafef4.gif)

Not to mention how awkward it'd be to store all the Variants Godot has to offer within it, since doing it simple wouldn't be standard (`"position": Vector2(0,0)` isn't valid JSON), and doing it appropriately would seriously impact readability.
```json
"position": {
    "type" : "Vector2",
    "x" : 2.0,
    "y" : 3
}
```

**Comment by KoBeWi** [comment]
Ah right, JSON doesn't support ints, so we can't even use it.

**Comment by theludovyc** [comment]
> `Resource::generate_scene_unique_id()` generates a unique ID and you are _extremely unlikely_ to run into a conflict. The only issue that remains is that `load_steps` might differ.

Yep sub is great. But I worried about use of itos(index). I found this https://github.com/godotengine/godot/blob/12cb05b3040242deebb87262aed8c04218b69044/scene/resources/resource_format_text.cpp#L484. So I think everything is good. Just wait new version 😄
