### ISSUE TITLE
Allow AStar2D to override _compute_cost & _estimate_cost like AStar

### ISSUE THREAD

**Issue by eltharionx** [godotengine/godot-proposals#441]
**Describe the project you are working on:**
Game using TileMap

**Describe the problem or limitation you are having in your project:**
I have 2d game, but must use an AStar (not AStar2D) since I require overriding the _compute_cost & _estimate_cost methods

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It would complete the AStar2D wrapper.  It would simplify game design to allow use of an AStar when only 2 dimensions/vectors are needed.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Basically, you would add the _compute_cost & _estimate_cost methods to the AStar2D class.

**Describe implementation detail for your proposal (in code), if possible:**
It seems like AStar2D is simply a wrapper around AStar which strips out the 3rd dimension/vector.  Not sure how to code that same functionality for the _compute_cost & _estimate_cost methods.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
If so, please let us all know of a work around.

**Is there a reason why this should be core and not an add-on in the asset library?:**
If the AStar2D is really supposed to be a wrapper for the AStar class which uses 2D vectors, it should  fully support all the methods that the AStar class has.

**Comment by Calinou** [comment]
cc @Chaosus, as they implemented AStar2D.

**Comment by eltharionx** [comment]
See: https://github.com/godotengine/godot/pull/37039
