### ISSUE TITLE
Make documentation of position testing of Navigation2D clearer or add new functions

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot-proposals#4410]
### Describe the project you are working on

2D RPG with overworld enemies, they can roam in small zones and walk back to their spawn position if the player leaves that zone. The enemies check if the player has exited their navpoly in order to decide if they should walk towards the player, or walk "home".

### Describe the problem or limitation you are having in your project

I spent at least 5 hours, maybe closer to 8, trying to figure out how to test if the player was inside of a NavigationPolygon before I realized that `Navigation2D.get_closest_point()` could be used to check for this in a roundabout way. I was attempting to copy the polygons so I could test them against `Geometry.is_point_in_polygon()`, but the correct order to string the points together would always get lost and result in strange shapes. Even so afterwards, it only has the ability to check in the local coordinate space so you need to manually add the global position of the Navigation2D in order to check globally.

Example of one of my tests where I was figuring out the polygon ordering issue, embarrassing. (Cyan are points `is_point_in_polygon()` were considering to be within the polygon.)
![image](https://user-images.githubusercontent.com/28269330/163692638-1b92a1a4-ab3b-4e25-82df-c2907580d8bc.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The simplest solution would be to modify the [documentation of get_closest_point()](https://docs.godotengine.org/en/stable/classes/class_navigation2d.html#class-navigation2d-method-get-closest-point) to make it clearer that it can be used to achieve this effect. I might just be stupid, but I feel like I can't be the only one to not think outside the box like this immediately.

--

An alternative harder solution that seems worth considering is adding an extra functionality to smooth this out. A function could be added with an explicit check for if the player is in a Navigation2D which returns a boolean. Ie: `Bool Navigation2D.is_point_in_navpoly(Vector2 to_point, Bool global_coordinate=false)` It also has an option to translate the point to global coordinates to simplify what it would take to write this check, no having to deal with adding global positions of parents manually.

I also think that the pre-existing `Navigation2D.get_closest_point()` could use a similar default false argument to automatically check the coordinate globally. Ie: (`Bool Navigation2D.get_closest_point(Vector2 to_point, Bool global_coordinate=false)`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The functions would just be a remix of things the engine could already do, so I don't think it would be very complicated to add. I think the debate is more as to if this is "too redundant" as you can hack this function together manually.

I think in the case where the function idea is rejected, I think adding a line or two to the documentation of `Navigation2D.get_closest_point()` feels warranted.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure how often this would come up in other projects. It seems like it has the potential to, but I'm not versed enough in how people create different types of projects.

### Is there a reason why this should be core and not an add-on in the asset library?

Making it an add-on would not help make this use more obvious to anyone who might repeat my mistake or a similar one.

**Comment by Calinou** [comment]
Navigation got a complete rewrite for Godot 3.5 and 4.0. Give [3.5beta4](https://godotengine.org/article/dev-snapshot-godot-3-5-beta-4) a try after making a backup of your project :slightly_smiling_face:

**Comment by Calinou** [comment]
For reference, this was implemented for 3.5 with https://github.com/godotengine/godot/pull/62353.
