### ISSUE TITLE
Add ceiling moving platforms for CollisionObject2D

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#4412]
### Describe the project you are working on

A 2D Platformer where the player can stick to ceilings

### Describe the problem or limitation you are having in your project

CollisionObject2D's moving platform options are quite useful, but they are limited to floors and walls. This causes problems when trying to achieve the following:
- Make my player stick to the ceiling of a moving platform.
- Make moving platforms push the player if he bonks his head on them.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Identically to how Moving Platform Wall Layers help with sliding on walls and wall-jumping.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Under the moving_platform_wall_layers property, add an nearly-identical moving_platform_ceiling_layers one that would apply the velocity of moving platforms when the player hits their ceilings.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be somewhat worked around by changing up_direction to act as if the ceiling is a floor. The workarounds get way harder if the ceiling layers are different from the player's ones.

The worst part of these workarounds is not the lines of script, it's that you'd have the movement platform logic spread over the properties and the script, which could lead to inconsistencies.

### Is there a reason why this should be core and not an add-on in the asset library?

Floor and Wall layers for moving platforms are already supported, so Ceiling layers make sense to be supported in Core, too.

**Comment by Calinou** [comment]
cc @fabriceci

**Comment by fabriceci** [comment]
We talked about it at the time and it was decided to wait and see if the feature was requested by users (as it complicates the code and the interface a bit) but I'm not against it.

> Make moving platforms push the player if he bonks his head on them.

Can you explain this in detail? If the player touches the platform with his head he should be pushed back.

**Comment by MewPurPur** [comment]
From what I've seen, if my player collides with the floor, even if for just one frame and then he jumps immediately, it applies the moving platform's velocity on leave. I was thinking of the same - if the platform is quickly moving to the left, you're pushed to the left as well.

**Comment by fabriceci** [comment]
> From what I've seen, if my player collides with the floor, even if for just one frame and then he jumps immediately, it applies the moving platform's velocity on leave.

Yes according to the `MovingPlatformApplyVelocityOnLeave` parameter.


There is one thing that worries me tbh, and that might be counter intuitive.

If I am not mistaken, on a vertical moving platform if we add this feature:

When the character touches the rising platform with his head, he will stay "stuck" on it (need to be tested if you continue to apply the gravity), you will probably have to deactivate the ceiling layer to unhook him.

However when the platform goes down, with the gravity the player will go down faster and be unhooked and so, will not follow the platform when it will rise up again (it will probably be necessary to deactivate the gravity).

These are not obvious behaviors unlike others.

Moreover, we might want an "on leave" behavior according to the platform type (floor/ceiling/wall), which will further complicate the API.

**Comment by MewPurPur** [comment]
The point of MovingPlatformApplyVelocityOnLeave seems to be to translate the player's velocity from a global reference point to the moving platform's reference point. So even if the moving platform moves up really fast and from a global reference point it makes the player's movement speed positive, the player should still move away from its reference point, rather than get stuck. Maybe with extremely fast deceleration getting stuck could become a thing, but this isn't unique to ceil.

Idk about getting unhooked, I don't really understand what would go wrong. You understand the system better, so if you think it wouldn't work in practice the way people would want it to, then that's probably the case.

**Comment by MewPurPur** [comment]
Closing this in favor of a discussion.
