### ISSUE TITLE
Export ArrayMesh as .obj or other industry standard

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot-proposals#442]
I like to use CSG objects to prototype my models. I can already use `.get_meshes()` to output an ArrayMesh resource. I'd like to be able to export this mesh and refine it on Blender afterwards, but I can only use ResourceSaver to export it in `.tscn`, `.tres` or `.mesh`, none of which are recognized by Blender. We can import meshes in `.obj`, form, but I can't see how to export them.

Most of the Blender workflow is tailored in the Blender -> Godot direction, but there isn't much in the reverse.

It would be much easier to be able to open this mesh on Blender instead of working on Blender from scratch, because the important shapes are already aligned with my collision objects, which I did on Godot.

A simple option to save ArrayMesh as .obj on ResourceSaver would suffice, but adding the option in the `Save As` button in the resource dropdown menu would be more helpful.

I'm not interested in saving the materials, I'm only interested in the shape. The materials will be added on Blender afterwards and the scene reimported as `.glb`.

**Comment by groud** [comment]
Please fill in the issue template, it is required to ensure the quality of the proposal in this repository. I will reopen when this is done.

**Comment by Calinou** [comment]
For anyone stumbling upon this proposal via a search engine, note that scenes can now be exported to glTF 2.0 since Godot 3.4: https://github.com/godotengine/godot-proposals/issues/885
