### ISSUE TITLE
MultiplayerSynchronizer - Add an option to sync properties only when they are changed

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#4429]
### Describe the project you are working on

Real Time Strategy, but this applies to almost all multiplayer game types

### Describe the problem or limitation you are having in your project

A lot of network bandwidth is consumed idly by properties that rarely change.

Examples:
- Whether the game has started
- What map is being played
- Player names/info

I could increase the MultiplayerSynchronizer interval (e.g. to 1 second) but that means all changes will be delayed up to 1 second later.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It is important to have the current system as an option since it is unreliable (faster) and works great for stuff like player position.

I propose an alternate option that only updates when needed and does so reliably.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This proposal serves as more of a discussion topic so I'm not strictly proposing any UI.

![image](https://user-images.githubusercontent.com/14253836/164838379-d64c92c8-9104-411a-8f25-0d2905099dc4.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The only way to work around this currently is writing setter RPCs rather than using the synchronizer feature, which requires a lot of boilerplate code.

### Is there a reason why this should be core and not an add-on in the asset library?

There is already a synchronizer in core, so it makes more sense to extend it.

CC @Faless

**Comment by Xrayez** [comment]
I agree it should be there. I proposed to add this 3 years ago, see https://github.com/godotengine/godot/issues/16793#issuecomment-493745860.

**Comment by Faless** [comment]
> If the variable is watched and immediately synced, however, this wouldn't be an issue.

Well, that would actually be an issue.
Even if we add watched variables, they would still not be synced immediately, since that would mean generating one reliable packet for every changed property, which most definitely you do not want.

**Comment by Faless** [comment]
> I don't really see an issue with sending a reliable packet when a variable is changed. If the user doesn't want the transfer to be reliable, they can use the unreliable synchronization.

The problem is that reliable packets, to be reliable, have to be acknowledged.

So if I change 5 properties in one frame, and we send one reliable packet for every property changed the underlying system must:

- send the first
- wait for ack
- (upon receiving the first ack) send the second
- wait for ack
- (upon receiving the second ack) send the third
- etc.

As you can see, this piles up a lot of latency, and gets out of hand quickly (when you change 10/15 properties in a frame).

(note: libraries do sometime send more then one without waiting, queuing/reordering them on the receiving end, but that number is still going to be very limited to ensure low latency.)



> How would you suggest resolving the issue in my use case?

`on_game_started.rpc(spawn_position_array: PackedVector2Array)`

**Comment by nathanfranke** [comment]
> So if I change 5 properties in one frame, and we send one reliable packet for every property changed the underlying system must:
> 
>     * send the first
> 
>     * wait for ack
> 
>     * (upon receiving the first ack) send the second
> 
>     * wait for ack
> 
>     * (upon receiving the second ack) send the third
> 
>     * etc.

This is not the case and it should never be.

Some basic test code (Using Godot 3.4.4):

```gdscript
extends Node

func _ready() -> void:
	if "--server" in OS.get_cmdline_args():
		print("Starting server")
		var server := NetworkedMultiplayerENet.new()
		var err := server.create_server(12345)
		assert(err == OK)
		get_tree().network_peer = server
	else:
		print("Starting client")
		var client := NetworkedMultiplayerENet.new()
		var err := client.create_client("my.ser.ver.ip", 12345)
		assert(err == OK)
		get_tree().network_peer = client
		
		yield(get_tree().create_timer(3.0), "timeout")
		
		print("starting at ", OS.get_ticks_msec())
		for i in 1000:
			rpc("hello", i)

remote func hello(i: int) -> void:
	print(i)
	if i == 999:
		rpc("done")

remote func done() -> void:
	print("finished at ", OS.get_ticks_msec())

```

All packets are sent to my server in ~130ms (server is 1,100 miles away)

**Comment by Faless** [comment]
> All 1000 packets are sent to my server in ~130ms (server is 1,100 miles away)

indeed, 130 ms is a lot for <2000 km some queuing is clearly happening.

**Comment by Faless** [comment]
While I clearly over-simplified the send-ack-send-ack (though I did mention that libraries do optimize it), it obviously need to ack packets, and re-trasmit if acks does not arrive in time, and wait for the correct order to deliver them (even it it can buffer out-of-order packets for a while).

From ENet docs http://enet.bespin.org/Features.html:

> ENet provides sequencing for all packets by assigning to each sent packet a sequence number that is incremented as packets are sent. ENet guarantees that no packet with a higher sequence number will be delivered before a packet with a lower sequence number, thus ensuring packets are delivered exactly in the order they are sent.

> ENet provides an in-flight data window for reliable packets to ensure connections are not overwhelmed by volumes of packets. It also provides a static bandwidth allocation mechanism to ensure the total volume of packets sent and received to a host don't exceed the host's capabilities. Further, ENet also provides a dynamic throttle that responds to deviations from normal network connections to rectify various types of network congestion by further limiting the volume of packets sent.

**Comment by nathanfranke** [comment]
It is not nearly as dramatic as you suggest.

Task | 1 RPC | 10 RPCs | 100 RPCs | 1000 RPCs
--- | --- | --- | --- | ---
Average Duration after 1000 trials | 35ms | 34ms | 36ms | 63ms

This is only suggesting to add an **option**, I am not saying we should force all users to use reliable variables. There are many cases in my own game where I would prefer to use unreliable packets (e.g. transforms)

**Comment by nathanfranke** [comment]
End of the frame is not a big deal I guess, I will use `await get_tree().idle_frame`

**Comment by Cretezy** [comment]
The ability to configure reliability for a synchronizer is pretty core. Having at least an option for reliable/unreliable would be good.

Additionally, it would be nice to be able to configure channels for individual MultiplayerSynchronizers (or optionally, individual properties).

**Comment by Norrox** [comment]
I think having an option to do a reliable sync is good, and an "on change" sync as well.

Would bigger packet buffer for the reliable ones solve the problem with sending many small packages and waiting for response?

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/75467.

**Comment by agrimminck** [comment]
I have tested this "Watched" property, but the my function which is synchronized through it prints its set on every frame
`@export var players_searching := 0 :
  set(value):
    print(players_searching)
    players_searching = value
    $CanvasLayer/PlayersSearchingNumber.text = str(value)`

So I guess this is not working yet

**Comment by Calinou** [comment]
@agrimminck Please open a separate issue on the main Godot repository **with a minimal reproduction project included**.

PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by agrimminck** [comment]
Will do!

**Comment by nathanfranke** [comment]
@agrimminck's issue is tracked here: https://github.com/godotengine/godot/issues/77896
