### ISSUE TITLE
Can't get specific collisionShape when KinematicBody has multiple collisionShapes

### ISSUE THREAD

**Issue by AlexZan** [godotengine/godot-proposals#443]
I am working on a block building vehicle prototype. A vehicle can have thousands of blocks. There can be many vehicles per game.

I have one kinematic body for a vehicle so that I can move it, then I load all the blocks in as collision shapes with mesh instances within them. 

I cannot seem to get reference to the collision shape I am "hitting": My player has a melee attack block, it has an attack script with an area and a collision shape.

I have tried get_overlapping_bodies()

and the signal

func _on_Area_body_shape_entered(body_id, body, body_shape, area_shape):
	print(body_id, body, body_shape, area_shape)

I am always getting reference to just the kinematic body. But it does not seem possible to get the collision body I am actually hitting.

The work around would be to check each collision body for collision, but thats on potentially 10,000+ blocks. Also I dont want my blocks to have any attack checking responsibility.

**Comment by groud** [comment]
Hi, please fill is the issue template, it is mandatory to ensure the quality of the proposal in this repository. I will reopen when this is done.
