### ISSUE TITLE
Add Option to not render Directional Shadows for Occlusion Culled meshes

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#4430]
### Describe the project you are working on

Open World game

### Describe the problem or limitation you are having in your project

Shadow rendering in complex environments with plenty of Occlusion culling taking place, can get really expensive compared to the rest of the rendering pipeline

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In Most cases, if something is occlusion culled, both it and it's shadows are usually occluded, so it often makes sense to not bother rendering them in the Directional Shadow Map. This can Heavily help with Performance in Geometry intense scenes where most geometry is occluded.

***WARNING - This is NOT a Safe Optimization (Relative to Occlusion Culling itself), and use Can and Will Cause Missing Shadows in Some Cases and Should NOT be enabled by default as it requires the User to Know what they're doing and be ok with the Potential Visual Quality Sacrifices!***

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add Toggle to Directional Light Shadows (or Project Setting under Occlusion Culling) "Disable Shadow Rendering for Occlusion Culled Meshes" and add Toggle to Mesh Instance "Ignore Shadow Occlusion Culling" Which would ignore the Directional Light setting, generally useful for large, low poly meshes that tend to be more impactful on the scene shadows and don't cost as much.

Additionally, Do a Cube Map Occlusion culling test, instead of just viewport, albeit with the side faces at a much lower res to also occlude shadow casters not in the camera's viewport, if Directional Light Shadow Occlusion Culling is used. This Shouldn't Prove too expensive even on lower end systems, as even without SSE4.2 Occlusion Culling can do 60 FPS with 259200 rays a thread (8 threads, resulting in ~2.073mpx a frame which is pixel perfect occlusion for a 1080p display, which is a stupid overkill, Don't use that many rays!!!) on High, with an i3 10105f at 3.7 GHz, with a bunch of various (both in terms of complexity and position) occluders scattered around
This can also be used for a Camera Centric Reflection Probe which I'm using, albeit this is a bit of a niche use case, but it's ~~unclear how beneficial it'd be to normal use cases for Reflection Probes~~ Scratch that, it'd be useful, at default 64 reflection probes, times 6 faces, that's 384 faces it'd need to render, at let's say 128 rays/face that's 49152 OC pixels for all 64 reflection probes, given the result above, and the fact that you could do this on a per reflection probe basis (probes under the size of 10m view distance probably wouldn't benefit, but those with 50m+ totally would in scenes of even mediocre complexity with OC setup) it'd totally be worth investigating too

A way to mitigate too aggressive Directional Shadow Culling, and thus reduce wrongful culling, one could increase the size of each Shadow Casters AABB by a certain length using the Directional Light's Normal. This could be added alongside the extra cull margin property on meshes.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No (Occlusion Culling is not exposed to the user)

### Is there a reason why this should be core and not an add-on in the asset library?

Both are in Core, and the needed stuff to implement as an addon isn't exposed.

**Comment by fire** [comment]
Optimization is not a goal in itself, if it's not solving a problem.

Can you provide a "really expensive minimal viable project" for testing?

**Comment by mrjustaguy** [comment]
I don't even need to make a particularly heavy scene to show the problem.
Shadow Rendering GTX 1050 Ti
Occluded cast Shadows - 3.4ms/frame for Shadow Rendering
Occluded don't cast Shadows - 2ms/frame for Shadow Rendering
[Test.zip](https://github.com/godotengine/godot-proposals/files/8550013/Test.zip)

If you turn off Mesh LOD, each of the 288 (half of which are occluded) characters is ~30k triangles
Results are as follows
Occluded cast Shadows - 33ms/frame for Shadow Rendering
Occluded don't cast Shadows - 16ms/frame for Shadow Rendering - That is 16ms Lower!

Delta for just switching between the Current Occlusion Culling is only 10ms/frame in the Mesh LOD off case. do keep in mind, Shadows for the sun are also rendered in multiple splits, adding to the expense.

This makes a GIGANTIC difference in a game with 4km view distance, where the Sun casts shadows across the ENTIRE view distance in real time (the sun is going to have day/night cycle, baking shadows as such isn't possible)

**Comment by Calinou** [comment]
> If you turn off Mesh LOD

That doesn't sound like a very realistic use case though.

**Comment by mrjustaguy** [comment]
Mesh LOD was disabled to simulate a much more complex scene, as 288 humans with lod at the distance ain't really a complex scene

**Comment by mrjustaguy** [comment]
Closing as a Suitable workaround exists, for this fairly niche optimization and complicated to get right, using VisibileOnScreenNotifier, simply by setting the AABB to be the same between it and the Shadow Casting Mesh, and using the on/off screen signals to enable/disable shadow casting
