### ISSUE TITLE
Rename Transform2D and Basis `elements` to `columns` and `rows` respectively

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#4446]
### Describe the project you are working on

I'm working on Godot itself. This change is only relevant for internal code and third-party modules.

This proposal is a prerequisite of #4445, at least if we want to use the `elements` name for primitive elements.

### Describe the problem or limitation you are having in your project

Currently, Transform2D stores a Vector2 array of size 3 called `elements` and Basis stores a Vector3 array of size 3 called `elements`. This name works fine, but it's sub-optimal, as it doesn't explain what these elements are - it's not very semantic. Transform2D's `elements` stores matrix columns, while Basis's `elements` stores matrix rows.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As mentioned above, Transform2D and Basis store different things, so I propose renaming Transform2D's `elements` to `columns`, and Basis's `elements` to `rows` to better reflect what they are.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Let's look at some examples to see how this would improve readability.

```cpp
m.basis.elements[0][0] = t.elements[0][0];
m.basis.elements[1][0] = t.elements[0][1];
m.basis.elements[0][1] = t.elements[1][0];
m.basis.elements[1][1] = t.elements[1][1];
m.origin[0] = t.elements[2][0];
m.origin[1] = t.elements[2][1];
```

This code from `variant.cpp` is for converting a Transform2D to a Transform3D. The order of the numbers are switched, and it's not immediately obvious why if you aren't already familiar with why. If we name these "rows" and "columns", the reasoning becomes obvious:

```cpp
m.basis.rows[0][0] = t.columns[0][0];
m.basis.rows[1][0] = t.columns[0][1];
m.basis.rows[0][1] = t.columns[1][0];
m.basis.rows[1][1] = t.columns[1][1];
m.origin[0] = t.columns[2][0];
m.origin[1] = t.columns[2][1];
```

Another example, more trivial:

```cpp
_FORCE_INLINE_ Vector3 get_column(int i) const {
	return Vector3(elements[0][i], elements[1][i], elements[2][i]);
}

_FORCE_INLINE_ Vector3 get_row(int i) const {
	return Vector3(elements[i][0], elements[i][1], elements[i][2]);
}
```

We could just take it for granted that these methods behave correctly, but if we wanted to verify this it would take some mental effort. However, if we change it around to use the `rows` name, it becomes obvious that `get_column` grabs each row and takes the `i`-th element from each, which gets a column. It also reveals that the `get_row` method could be simplified a lot, since `rows` stores rows, we just grab one of them and return it.

```cpp
_FORCE_INLINE_ Vector3 get_column(int i) const {
	return Vector3(rows[0][i], rows[1][i], rows[2][i]);
}

_FORCE_INLINE_ Vector3 get_row(int i) const {
	return rows[i];
}
```

I have some branches that implement this change:

Transform2D: https://github.com/aaronfranke/godot/tree/t2d-col

Basis: https://github.com/aaronfranke/godot/tree/basis-row

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A, this is about internal code quality.

### Is there a reason why this should be core and not an add-on in the asset library?

This is code already in the core engine.

**Comment by fire-forge** [comment]
I don't see any reason not to make this change, especially if you've already done it on your own branch. It just makes working with Transform and Basis easier and less confusing.

**Comment by aaronfranke** [comment]
Implemented by https://github.com/godotengine/godot/pull/60627 and improved upon by https://github.com/godotengine/godot/pull/60727.
