### ISSUE TITLE
Implement particle seeking

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#4449]
### Describe the project you are working on

Various VFX (including networked scenarios)

### Describe the problem or limitation you are having in your project

Godot currently does not support seeking inside particle systems.
For VFX scpecifically, seeking is very important to be able to fine tune all the timings of the VFX. Without being able to seek, the result vfx are either lower quality (some things are slightly de-synchronized) or require more effort (recoridng a video and frame skipping it).
On the contrast, both Unity (with shuriken) and Unreal (Niagara only) offer the ability to seek through the timeline of a particle system.
Niagara in particular treats particle systems as something that is a collection of particle systems (our particle nodes) and a timeline (our animator).
The above are editor only features. Note that seeking particle systems could be used also for reconciliation in online games.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement seeking for particles: being able to tell the engine "show me particle system X at time Y".
I'd love input from others (CC @Calinou , @Chaosus , @clayjohn, @picster and @reduz ) on how to solve this issue. See proposal below.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is something I'd like input from people, because seeking particles may prove challenging depending on how it is implemented.
As discussed with @reduz , probably the best way of doing this is to record particle system's state when playing it back the first time and being able to seek in this data.
This has a significant memory cost, which should be taken into consideration (probably with the engine refusing to do seek for particle systems with more than N particles).

It could be worth considering making the recording of the particle into a datatype, and add a "particle playback" node which needs to be supplied with a particle system recording and it will play it back.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No - this is far too deep in the renderer to be worked on with GDScript, and particle data isn't exposed to GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

See above

**Comment by Calinou** [comment]
I wonder if the `preprocess` property could be (ab)used to achieve this. It will not be possible without C++ changes, but it sounds like a reasonable avenue to explore.

**Comment by QbieShay** [comment]
I think that seeking in editor should always be possible, for ease of use (unless there are too many particles), but i agree for in-game.

**Comment by clayjohn** [comment]
I don't know much about niagra and shuriken, are they fully deterministic? If so, do they support things like attractors and collision?

**Comment by Calinou** [comment]
> I think that seeking in editor should always be possible, for ease of use (unless there are too many particles), but i agree for in-game.

We could have shortcuts to control the engine time scale within the editor, which would also affect shaders using `TIME`. However, this wouldn't allow *fully* pausing the simulation or going back in time.

**Comment by QbieShay** [comment]
This is actually a very good proposal @Calinou , I will try to implement a plugin for that and see if it serves my usecase enough to push back seeking.

**Comment by mhilbrunner** [comment]
(Removed the network label for now. I'd hope whatever implementation we'd come up with should just work with the new spawner/sync facilities, and if not, we can revisit at that time. As of now, I don't see this needing attention by the networking team specifically.)
