### ISSUE TITLE
Please add Right-to-left alignment to HFlowContainer

### ISSUE THREAD

**Issue by biblical-text** [godotengine/godot-proposals#4453]
### Describe the project you are working on

Any project that users HFlowContainer.

### Describe the problem or limitation you are having in your project

HFlowContainer appears to allow left-to-right alignment:

```
--------
a b c
d  e
--------
```

But does not appear to allow:

```
---------
    a b c
     d  e
---------
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow right justification like this:

```
---------
    a b c
     d  e
---------
```

NB: I initially used the term 'right-to-left' here, but that term doesn't appear to imply what I had intended.

### Is there a reason why this should be core and not an add-on in the asset library?

It doesnt make sense to support HFlowContainer left-to-right but not allow right-to-left.

**Comment by KoBeWi** [comment]
In 4.0 this is kind of supported using `layout_direction`, but it's not intended usage of that property and it doesn't handle VFlowContainer.

**Comment by bruvzg** [comment]
`layout_direction` is not intended for something like this, and will result in layout like this instead:

```
---------
    c b a
     e  d
---------
```

**Comment by biblical-text** [comment]
That would be a genuine right-to-left. So I guess the request should be:

Lets allow left align, centre align, and right align.

**Comment by Koyper** [comment]
Center alignment is also an essential improvement to FlowContainer. It's pointless to do it with a script because you have to compute the number of lines with the script and calculate the number of rows and add spacing before setting a width to center, which is the entire point of having a FlowContainer class.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/67788.
