### ISSUE TITLE
Shading language: Allow using `hint_color` with `vec3` to designate a uniform as a color with no alpha

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot-proposals#4469]
### Describe the project you are working on

An app for creating wallpapers

### Describe the problem or limitation you are having in your project

The shader language doesn't allow using `hint_color` with a `vec3` uniform.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When using `hint_color` with a `vec3` uniform, it should export it to the inspector as a color without alpha.

Colors can be added to the inspector with no alpha, using the `PROPERTY_HINT_COLOR_NO_ALPHA` property hint enum. This is how the the `@export_color_no_alpha` annotation in GDScript works.

#### Example Shader:
```glsl
shader_type canvas_item;

uniform vec3 color : hint_color;

void fragment() {
	COLOR.rgb = color;
}
```

![image](https://user-images.githubusercontent.com/67974470/166073902-47d83d9e-fe01-440e-a50b-9dc54c61be22.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Using a `vec4` instead of a `vec3` and ignoring the alpha value.

### Is there a reason why this should be core and not an add-on in the asset library?

The shading language can't be modified by a script or add-on, and this would improve the performance of shaders because the extra float value for alpha wouldn't have to be included when it isn't needed.

**Comment by clayjohn** [comment]
Sounds like a good idea!
