### ISSUE TITLE
RGB Curves / HUE Correct / Levels: to Environment node.

### ISSUE THREAD

**Issue by alexfreyre** [godotengine/godot-proposals#447]
**Describe the project you are working on:**
This proposal applies in general to any type of project.

First of all, I am an artist from the field of Fine Arts. I am focused on developing works of art with what is called emerging media. I am currently using Godot to do interactive virtual jobs. Therefore, I am very concerned about the development of Godot and I want to humbly provide my point of view.

**Describe the problem or limitation you are having in your project:**
For human perception, contrast and gray values ​​are very important before other phenomena such as color and saturation, which are subsequently evaluated. In my opinion Godot lacks a deep control over this fact. Therefore, I propose different things so that the user has more control in this regard.

In my humble opinion with these characteristics, we could adjust our visuality with total control over contrast, gray levels and saturation, in addition to generating very specific effects without having to code a shader, which is not so easy for everyone.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
In the "Environment" node, we can control the "contrast, brightness and saturation", although in a simple way.

I propose to give the user the possibility of use:
1. LEVELS, to control the "hightlights" or "Gain", "midtones" or "Gamma" and "Shadows" or "Lift", and the possibility of changing each color as described above. For specific visual effects.
2. RGB_CURVES, for the control of each channel "RGB" and "all three together in the fourth parameter", with the possibility of adding several points to the curve.
3. HUE_CORRECT, for the HSV control of the different colors of the visible spectrum. This could be useful, for example, to emphasize color effects, perhaps desaturate all but one, among other effects.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Original image
![original](https://user-images.githubusercontent.com/42384785/73957860-06f25480-48d5-11ea-8928-25dd15c07e9b.jpeg)

RGB_Curves
![RGB_CURVES](https://user-images.githubusercontent.com/42384785/73957875-08bc1800-48d5-11ea-9c57-5d9ec98e541c.png)

HUE_Correct
![HUE_CORRECT_HSV](https://user-images.githubusercontent.com/42384785/73957883-0c4f9f00-48d5-11ea-896d-8d3250013cb5.png)

LEVELS
![LEVELS](https://user-images.githubusercontent.com/42384785/73959230-0e1a6200-48d7-11ea-80dc-a7ce4c62bb59.png)

![LEVELS_2](https://user-images.githubusercontent.com/42384785/73959261-196d8d80-48d7-11ea-92f3-f77a7c2ab20b.png)

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It would be used very often.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Personally, I think this is a really important and essential feature for any software that focuses on the creation of images, video, games or visual interactive applications like Godot. This feature could be part of the core as part of the post-process workflow of the entire scene in Godot 4.0.

**Comment by fire** [comment]
See https://github.com/godotengine/godot/pull/26101

**Comment by Calinou** [comment]
3D LUTs allowing any kind of color correction were implemented in https://github.com/godotengine/godot/pull/42761, closing. (
This method is color correction is similar to the one found in most AAA games out there.)
