### ISSUE TITLE
Rename TextureRect.expand to something descriptive of what it does

### ISSUE THREAD

**Issue by selamba** [godotengine/godot-proposals#4472]
### Describe the project you are working on

A project that uses `TextureRect` for GUI.

### Describe the problem or limitation you are having in your project

`TextureRect` has a property called `expand`. It allows the texture (from the `texture` property) to be scaled to the bounding rect.
The description of the property as found in the documentation:

> If `true`, the texture scales to fit its bounding rectangle.

Problem is, **the `expand` name is wrong**. It doesn't just expand, it can shrink too, if the bounding rect is smaller than the texture). The current name `expand` doesn't suggest that the texture is actually going to get shrunk.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename `expand` to something that actually describes what it does, something like `scale` or `fit_to_rect`. Although `scale` might be a bad option due to the collision with `Node2D`'s and `Spatial/Node3D`'s `scale` properties, which are vectors, not booleans.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Rename the property.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It fixes a property's incorrect name.

**Comment by Mickeon** [comment]
This property has already been [renamed to `ignore_texture_size` and given a nicer description](https://docs.godotengine.org/en/latest/classes/class_texturerect.html#class-texturerect-property-ignore-texture-size) across the board. https://github.com/godotengine/godot/pull/55456

**Comment by KoBeWi** [comment]
Yep, and then I made a PR that renames it again: https://github.com/godotengine/godot/pull/58517

**Comment by KoBeWi** [comment]
Closing in favor of #4509
