### ISSUE TITLE
Add an expression evaluator (REPL support with inspector sequent results)

### ISSUE THREAD

**Issue by rohanrhu** [godotengine/godot-proposals#4473]
### Describe the project you are working on

Meow... I made an expression evaluator:

https://github.com/godotengine/godot/pull/60134

![image](https://user-images.githubusercontent.com/1125150/162683405-553b9acc-1539-4a56-accc-693e9edb057b.png)

### Describe the problem or limitation you are having in your project

We need an expression evaluator in debugger, it is a very common need 😊

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The evaluator has sequent results for expressions. It can get locals and members. When you click objects on results, it opens the object on inspector.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Evaluator is using `Expression` class.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Meow

### Is there a reason why this should be core and not an add-on in the asset library?

Meow

**Comment by marcelb** [comment]
This is so cool.

**Comment by visuallization** [comment]
Looking forward to this. :)

**Comment by Calinou** [comment]
@visuallization Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by The3DWizard** [comment]
Is there any active development going on for this issue? I see that it has been bumped to 4.3, but none of the dev snapshots of 4.3 mentions anything about debugging. Just curious about what the current state is.

**Comment by Calinou** [comment]
> Is there any active development going on for this issue? I see that it has been bumped to 4.3, but none of the dev snapshots of 4.3 mentions anything about debugging. Just curious about what the current state is.

The [pull request](https://github.com/godotengine/godot/pull/60134) needs to be rebased, but since 4.3 is entering its beta stage soon (where no large new features may be added), I doubt it'll make it for 4.3.

**Comment by rohanrhu** [comment]
> > Is there any active development going on for this issue? I see that it has been bumped to 4.3, but none of the dev snapshots of 4.3 mentions anything about debugging. Just curious about what the current state is.
> 
> The [pull request](https://github.com/godotengine/godot/pull/60134) needs to be rebased, but since 4.3 is entering its beta stage soon (where no large new features may be added), I doubt it'll make it for 4.3.

Hi @Calinou, I made the latest requests but seems like (I'm not %100 sure though) a weird behavior is coming from inspector component's internal behavior; it is refreshing expression values when debugger's current stack frame is changed.

**Comment by johnmiko** [comment]
Sorry if this is a dumb question, this is available now? Or not until godot 4.4? Currently have godot 4.3 installed and would like to use this feature

**Comment by clayjohn** [comment]
It's in 4.4, you can test it out in 4.4 dev 3 (https://godotengine.org/article/dev-snapshot-godot-4-4-dev-3/) or wait for the full 4.4 release.
