### ISSUE TITLE
Open Visual Studio Code workspace if available when configured as external editor

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot-proposals#4476]
### Describe the project you are working on

Project with CSharp as main language, vsCode as preferred IDE and extensions for the project.
- Prefered Structure
  - *project-name*
    -  project.godot
    -  *project-name*.code-workspace (reference '../godot extension' and '../vsCode extension')
    - ...
  - godot extension 
    -  project.godot
    - ...
  - vsCode extension
    - package.json
    - ...

### Describe the problem or limitation you are having in your project

If I use a workspace, godot will open a second instance of vsCode.
If I don't use a workspace, I can't edit/inspect the extensions with the editor started by godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Detect if a 'res://*.code-workspace' exist and open it instead of 'res://'

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- simple solution
  - sequence
     - if 'res://*project-name*.code-workspace' exist open it
     - if 'res://code.code-workspace' exist open it
     - if any 'res://\*.code-workspace' exist open it
     - default open 'res://' as folder
  - problem: 'res://' could contain mutliple workspaces and the user wants to change the preferred (pretty unlikly)
- sophisticated solution
  - sequence 
    - add project specific setting for the prefered workspace
      - only if vscode is selected
      - default as *project-name.code-workspace*
    - if specified open the corresponding workspace
     - default open 'res://' as folder
  - problem: mix of editor and project settings for the external editor

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Not possible

**Comment by dsnopek** [comment]
I've recently started using VS Code more, and I've also been very annoyed at Godot not opening scripts in the workspace! :-)

However, I was planning to experiment with a wrapper script (that I'd set as my external editor, rather than directly pointing to VS Code) which would do logic similar to what you described above. I haven't tried it yet, so maybe it's not possible, but if it is, I think it'd probably be better not to put code specific to VS Code into Godot itself.

**Comment by dsnopek** [comment]
Ah, so you're _only_ looking at this from the perspective of Mono Godot? I use VS Code for both C# and GDScript projects.

In any case, your proposal pushed me over the edge, and I finally made my wrapper script - you can find the code here:

https://gitlab.com/-/snippets/2310795

Here's the settings I used to add this to Godot:

![Selection_374](https://user-images.githubusercontent.com/191561/166394851-6f39bb32-bd8c-476e-b2e8-d9611bb806e1.png)

It will open the file in the VS Code workspace for the project (if one exists) and will even jump to the right line and column.

**It works for both C# and GDScript projects!**

I only tried it on Linux, but I think it'll work on Windows too. MacOS is a whole other beast, so I'm not sure what will happen there.

**Comment by antonWetzel** [comment]
Did not know there were 2 settings for external editor.
The following GDScript opens vsCode workspaces (Windows tested, Linux probably, MacOS ?).
The file can be in any directory and no other scripting language is required.

```gdscript
# Use vsCode as External Editor for Godot
#
# Settings to edit ( <...> must be replaced )
# Editor Settings > Text Editor > External
#   > Use External Editor : On
#   > Exec Path           : <path-to-your-godot-executable>
#   > Exec Flags          : -w --resolution 1x1 -s <this-file-location> {project} {file} {line} {col}
#
#
#             argument |                            effect
# ---------------------|----------------------------------
#                   -w |                      run windowed
#     --resolution 1x1 |                     make it small
#                   -s | run script (must extend MainLoop)
# <this-file-location> |                   run this script
#                  ... |                  passed arguments

extends MainLoop

func _initialize():
	# read args and remove the first 2
	# OS.get_cmdline_args() = [-s, vsCode.gd, ...]
	var args := OS.get_cmdline_args().slice(2)

	# replace the project directory with a workspace
	var dir := Directory.new()
	var path := args[0]
	if dir.open(path) == OK:
		dir.list_dir_begin()
		while true:
			var filename := dir.get_next()
			if filename == "": # end of files
				break
			if dir.current_is_dir():
				continue
			if not filename.ends_with(".code-workspace"):
				continue
			path = filename
			break

	# get correct vsCode name
	var name := ""
	match OS.get_name():
		"Windows", "UWP":
			name = "code.cmd"
		"macOS":
			name = "code" # not sure
		"Linux", "FreeBSD", "NetBSD", "OpenBSD", "BSD":
			name = "code" # not sure
		_:
			push_error("unknowns OS: " + OS.get_name())
			name = "code"

	# start vsCode in seperate process (not blocking)
	OS.create_process(name, [
		path,
		"-g",
		args[1]+":"+args[2]+":"+args[3]
	])

func _process(delta):
	return true # close Godot after the first frame

```

**Comment by Calinou** [comment]
Please consider updating the [documentation](https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html) by opening a pull request on https://github.com/godotengine/godot-docs :slightly_smiling_face:
