### ISSUE TITLE
Improve Directional Shadow Auto LOD

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#4479]
### Describe the project you are working on

Open World Game

### Describe the problem or limitation you are having in your project

Directional Shadows currently Use the same Auto LOD level as the Player Camera, even for Meshes set to Shadows Only

This has Two Problems:
1) If the Shadow Caster is Very far from the Camera, but the Camera is Very Close to it's Shadow, the Shadow LOD will be very low, Resulting in horrible Shadows, and Shadow Popping as you move to/away from the Shadow Caster
2) If the Shadow Caster is Very close to the Camera, the Shadow will use High Quality LODs, even if the resolution of the Shadow map is relatively low, thus wasting a ton of performance

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Directional Shadows Render in Orthogonal Perspective, as such, using the LOD quality as determined by the Directional Shadow's Orthogonal View are going to be the best suited to Minimize Shadow Processing required and Maximize Shadow Quality and Consistency
1) LODs are set to their ideal values for a given Split, and thus, this scenario cannot exist any longer
2) LODs are set to their ideal values for a given Split, meaning it's using LODs based on the actual Resolution of the Shadow map, which often means significantly lower LODs required for the same result, as Shadow Resolution generally isn't really that high, and Meshes only occupy a tiny portion of the Shadow map.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Treat Directional Shadows as Orthogonal Cameras in ALOD logic.
For Each Split Determine ALOD Shadow LOD (same logic as Orthogonal Cameras use)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as ALOD is not exposed to the user.

### Is there a reason why this should be core and not an add-on in the asset library?

ALOD and Directional Shadows are core.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/2600.

**Comment by clayjohn** [comment]
There are two things to consider when choosing LODs for shadows:
1. The resolution of the shadow map (as you point out here). This is important so you aren't wasting time on detailed meshes when the underlying resolution is low
2. You want the mesh to line up with the mesh being rendered. Using a different LOD is a recipe for shadow acne on the mesh itself. 

Using a different LOD between the shadow mesh and the rendered mesh can lead to bad shadow acne issues. I beleive our LODs are designed to never have a larger outline than the base mesh, so as long as shadow LOD's are kept equal to or higher than the mesh being rendered, we should be able to tweak them.

Adjusting automatically based on the resolution of the shadow map makes sense to me. So does having a shadow_lod_bias parameter so users can choose to sacrifice some quality if they want.

**Comment by mrjustaguy** [comment]
Potentially we could actually make an option of how ALOD works for Shadows, based on camera distance or based on what the Shadows detect (aka this proposal) and have that be a Project Setting..

**Comment by mrjustaguy** [comment]
Closing as this seems to be in effect already, not to mention https://github.com/godotengine/godot/pull/76291 significantly improves shadow performance by only rendering 2 splits at a time, making the impact of wasteful shadow geometry much less significant, especially should the triangle processing regression (https://github.com/godotengine/godot/issues/68959) be successfully resolved.
