### ISSUE TITLE
Using additional textformats like utf16

### ISSUE THREAD

**Issue by MrMrBlackDragon** [godotengine/godot-proposals#448]
**Describe the project you are working on:**
I'm working on a texteditor

**Describe the problem or limitation you are having in your project:**
It's getting problamatic when using texts which aren't formated as in utf8. 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It would be great improvement if Godot could acces utf16 files as well. The possibilty to differ between low endian and big endian does already exist.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**
Like getting the text from utf8:
`get_string_from_utf16`

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It is probably possible but not in a few lines of code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is more userfriendly giving the possobilty to choose between a amount of textcoding. Futhermore it is necessairly if you try to keep files (e.g savegames) small, espcially when working with non western chracters.

**Comment by MrMrBlackDragon** [comment]
Godot already supports a great range of picture formats, so why no go the same step with supporting a bigger range of textformats?

**Comment by Calinou** [comment]
> Godot already supports a great range of picture formats, so why no go the same step with supporting a bigger range of textformats?

There needs to be a valid use case for it :slightly_smiling_face: 

See the beginning of [UTF 8 Everywhere](http://utf8everywhere.org/:

> In particular, we believe that the very popular UTF-16 encoding (often mistakenly referred to as ‘widechar’ or simply ‘Unicode’ in the Windows world) has no place in library APIs except for specialized text processing libraries, e.g. ICU.

**Comment by MrMrBlackDragon** [comment]
Well, I created an converter for UTF8 and UTF16, so this issue isn't needed any longer. Here is a link to the converter: https://gist.github.com/MrMrBlackDragon/f34fe483ca2f78020726121fac4fbf1a
