### ISSUE TITLE
Document and fix OptionButton/PopupMenu/ItemList

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [godotengine/godot-proposals#4483]
### Describe the project you are working on

3D landscape visualization/editor

### Describe the problem or limitation you are having in your project

I could not explain why this is the case, but for all three classes ``OptionButton``, `PopupMenu`, `ItemList` there is a "hidden" property called ``items``. This property i mentioned nowhere in the docs: 

1. https://docs.godotengine.org/en/stable/classes/class_optionbutton.html
2. https://docs.godotengine.org/en/stable/classes/class_popupmenu.html
3. https://docs.godotengine.org/en/stable/classes/class_itemlist.html

I found it randomly as i wanted to use a variable items and it got highlighted. More importantly though, iterating through this this property with a ``for item in items`` will go not through something like an item object, but through 5 individual entries for each actual entry:

![image](https://user-images.githubusercontent.com/33001106/166299942-0e01aa27-3616-4d64-8a74-e72f29b846b8.png)

When the items look like:

![image](https://user-images.githubusercontent.com/33001106/166300014-352f2c3f-c150-469d-8298-a028fcadd6f2.png)

I really do not understand what is going on and (why 5 entries???). Since this is not documented anywhere, I see a hard limitation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If not fixing this properly by inventing something like a ``ListEntry`` class that just properly holds its properties, I would at least wish for some documentation of this somewhere (found by coincidence and then completely unclear what it does). Also I was wondering many times there is no ``get_items()``-function for those classes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Guess it is self-explaining

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Guess if it was documented some people would use it :) 

### Is there a reason why this should be core and not an add-on in the asset library?

Yes - basic feature.

**Comment by Calinou** [comment]
Items are already exposed as actual properties in the `master` branch: https://github.com/godotengine/godot/pull/54533

**Comment by MathiasBaumgartinger** [comment]
> Items for those nodes are already exposed as actual properties in the `master` branch: https://github.com/godotengine/godot/pull/54342 and https://github.com/godotengine/godot/pull/54533
> 
> Unfortunately, this can't be backported to `3.x` in a backwards-compatible manner.
> 
> > I would at least wish for some documentation of this somewhere (found by coincidence and then completely unclear what it does). Also I was wondering many times there is no get_items()-function for those classes.
> 
> Please open an issue for this on https://github.com/godotengine/godot-docs, as this repository should be used for feature proposals only.

Good to hear - sorry for the poor research!

Will open another issue

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-docs/issues/5796, as the feature itself was already implemented in 4.0 (and can't be backported to `3.x`).
