### ISSUE TITLE
Expose Physics Interpolation setting as a property in the editor

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot-proposals#4487]
### Describe the project you are working on

I'm working on Beat Invaders

### Describe the problem or limitation you are having in your project

Against all what is sane I ported the project from 3 stable to 3.5 beta to start using the phyics interpolation.
I already used the smoothing plugin for some things and was eager to implement it.

Now having interpolation in a big project, there are a TON of challenges involved. Tweens, Animation Players, and more.
Controlling streaking and adding the resets at the right spot is really brain wrecking, especially as it all has to be done via code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be extremely useful to have the interpolation setting exposed as an editor property. A lot of things to not need to be interpolated or even create problems. Having the need to disable it via code `set_physics_interpolated(false))` is very cumbersome and annoying.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/9423774/166493386-ea95b9f0-591e-46b0-91a0-d2ee75321933.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around in theory. But - working on a "bigger" game (I am sure there are bigger and more complex games than mine, but it is a full game and has a ton of Nodes, Objects, effects. etc.) it is just so cumbersome to do it via Script.

Physics Interpolation is a fantastic feature, but also a feature that influences basically EVERY aspect of a project.
I think if there is a property that influences a lot of things, it should be easily accessible as a editor element.

### Is there a reason why this should be core and not an add-on in the asset library?

It will influence every Godot project using this feature.

**Comment by lawnjelly** [comment]
The interpolation flag was exposed as a property during development of all the interpolation PRs, so this is very doable.

**Comment by HarmonyHoney** [comment]
i hope to see this implemented!(:

**Comment by Calinou** [comment]
@HarmonyHoney Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/60858.
