### ISSUE TITLE
Export files of unsupported import types

### ISSUE THREAD

**Issue by 2dogtwo** [godotengine/godot-proposals#4492]
### Describe the project you are working on

use other exe file profile

### Describe the problem or limitation you are having in your project

Is there any way to export any kind of files in the project folder. Let some file types that cannot be imported in the editor can also be put into the pck file. For example, the exe file, I know that it may not be used directly after export, but it can also be copied to other locations and used again, and now I can only package it again with other tools. Does the pck resource file really need to be so demanding?
This is the content translated from the Internet, please forgive me if there is any incomprehension.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

。。

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

。。

### If this enhancement will not be used often, can it be worked around with a few lines of script?

。。

### Is there a reason why this should be core and not an add-on in the asset library?

。。

**Comment by KoBeWi** [comment]
In the export dialog, in the second tab there is a filter for additional files that you want to include. I think this is what you are looking for?

**Comment by Calinou** [comment]
This is already supported (see KoBeWi's comment above).
