### ISSUE TITLE
Pop-Out Script Tab (Or any other)

### ISSUE THREAD

**Issue by MintStudios** [godotengine/godot-proposals#45]
Hi!
A feature that would help my workflow in general would be a pop-out script tab. (Script Tab open as another window) I use dual monitors like most others and I find the external editor option unusable. I like the Godot's text editor. I know this was a feature request in the issues tab in the godotengine/godot, but I am opening this so it's in here and contributors and maintainers see it.

I am working on a Sudoku puzzle.

I will be able to be more productive by having the visual editor and the text editor side by side

![image](https://user-images.githubusercontent.com/54677274/64478252-dc5c6e00-d173-11e9-90bc-d23a0d758e3b.png)

???**Describe implementation detail for your proposal (in code), if possible:**???

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** = No

**Is there a reason why this should be core and not an add-on in the asset library?:** = I don't think it's possible.

**Comment by MintStudios** [comment]
I just saw a duplicate of this! Sorry!

**Comment by Calinou** [comment]
For the record, this is a duplicate of #28.
