### ISSUE TITLE
Rename C# enum values containing acronyms to uppercase

### ISSUE THREAD

**Issue by AntonioNoack** [godotengine/godot-proposals#4500]
### Describe the project you are working on

A C# project, trying to implement Raytracing 😄 (still, irrelevant for this proposal)

### Describe the problem or limitation you are having in your project

When looking for the enum Image.Format, I was having trouble finding the correct name for the enum.
It turns out, they have PascalCase instead of UPPERCASE in C#.

For an enum like RGBAF this shouldn't be the case. It should be UPPERCASE, because it is an abbreviation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It makes it easier to work with the GdScript documentation in a C# project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Rename it... idk how exactly you generate your mono libraries, but this probably will be some script, and you'd create an exception for cases like this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is purely cosmetic.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot really be added as an addon.

**Comment by Calinou** [comment]
Renaming enum values is a compatibility-breaking change, so it can only be done for 4.0.

The conversion is automated, which is why acronyms such as RGBAF become `Rgbaf`.

**Comment by Mystiick** [comment]
.NET standard would be PascalCase for abbriveations, not UPPERCASE, so `Image.Format.Rgbaf` is correct according to MSDN's guidelines (ignoring the fact that old .net code does break this rule). 

From: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions
> The PascalCasing convention, used for all identifiers except parameter names, capitalizes the first character of each word (including acronyms over two letters in length)

**Comment by Calinou** [comment]
> (including acronyms over two letters in length)

I think this is the only thing we should change, if needed. I haven't checked whether two-letter acronym constants use two uppercase characters (such as `AI`).

**Comment by aaronfranke** [comment]
Closing as rejected because we are going in the opposite direction as of https://github.com/godotengine/godot/pull/69547
