### ISSUE TITLE
Add a vertical fill mode to ProgressBar

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [godotengine/godot-proposals#4514]
### Describe the project you are working on

A non-game software application w/ a variety of custom controls.

### Describe the problem or limitation you are having in your project

Currently, the `Progress Bar` node is meant to be oriented horizontally where it fills from left to right. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A simple toggle to allow for vertical orientation. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This patch would add orientation option to the progress bar as a orientation enum in the inspector. Changing this would change the way the progress bar is drawn to either horizontal (Left to Right) or vertical (Bottom to Top) modes.  

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be nicer to allow people to reuse the existing node instead of asking users to re-implement the rendering to be thematically consistent with the original, C++ implementation. 

### Is there a reason why this should be core and not an add-on in the asset library?

See previous question.

**Comment by Calinou** [comment]
For reference, this is already implemented in TextureProgressBar (TextureProgress in `3.x`), but not in ProgressBar.

**Comment by Eoin-ONeill-Yokai** [comment]
@Calinou I was actually about to post my own MR for this but I guess one is already open. I didn't see a godot proposal for it, so I must have just missed it. Thanks for directing me to it!
