### ISSUE TITLE
Merge PlaneMesh and QuadMesh into a single primitive mesh

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#4516]
### Describe the project you are working on

Various VFX

### Describe the problem or limitation you are having in your project

When doing billboard VFX, due to the billboard code which expects the quad to face the z axis, planes cannot be used.
But sometimes, vertex displacement can be desired even with billboard quads, but it's not possible currently to do it without an external mesh, because quads can't be subdivided.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a "normal" property to the plane mesh and merge it with the quad mesh. 
Specifically:
Add a dropdown menu to choose between 3 options for the normal of the plane:
- UP
- FACING
- CUSTOM
When custom is selected, allow the user to enter a custom normal.
Mark Quad mesh as legacy.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by either rotating the mesh in the shader or by making a quad in an external modeling software, it's just less convenient.

### Is there a reason why this should be core and not an add-on in the asset library?

It could be done with an addon but to me it is an inconsistency/ux problem of the editor. I believe that adding it to the editor will not bloat the editor itself, but will instead speed up workflow for VFX.
In the end this doesn't create new features but reworks existing ones to be more compact and consistent.

**Comment by Calinou** [comment]
I was also confused why we had separate QuadMesh and PlaneMesh at first, but the separate orientation makes a lot of sense. That said, we can merge it into a single node with different properties.

**Comment by BastiaanOlij** [comment]
@Calinou I think this was still Godot 2.0 days so I didn't want to remove Quadmesh and break peoples games at the time, it made more sense to add a new node that had more functionality. By now it makes sense to retire Quadmesh in Godot 4 and add the property indeed.

**Comment by Calinou** [comment]
What should be the default value of the orientation property? I think **Facing** will be the most common choice (due to billboards).

**Comment by Zireael07** [comment]
@Calinou: I'd default to positive Y, as plane does (because well, facing, means facing which direction..?)

**Comment by Calinou** [comment]
> @Calinou: I'd default to positive Y, as plane does (because well, facing, means facing which direction..?)

"Facing" would be identical to QuadMesh's current orientation. The point is to make billboards look correct with as little setup as possible. If we default to facing upwards by default, billboards will be almost invisible.

**Comment by QbieShay** [comment]
Or: Horizontal, vertical, custom

**Comment by clayjohn** [comment]
We discussed this in today's proposal review meeting. The consensus was that it is acceptable and there is no strong preference for how it is implemented. 

One easy option is to add the ``normal`` property to PlaneMesh and remove QuadMesh altogether. The upgrade tool could easily just replace all uses of QuadMesh with a PlaneMesh set to ``FACING``.

In my opinion, this is the preferable approach.

Other options are to add the property to PlaneMesh and leave QuadMesh as-is (but marked as deprecated), or to add the property to PlaneMesh but make QuadMesh inherit from PlaneMesh so it gets the new property, and subdivision and is still available to use. 

These solutions are nice as they minimize compatibility breakage, but there is no reason to minimize compatibility breakage in 4.0.

**Comment by QbieShay** [comment]
I wonder which mesh should be the default, if plane or quad ..

**Comment by fire** [comment]
Quad was the recommended choice due to the fact that plane causes rendering issues.

**Comment by Calinou** [comment]
> Quad was the recommended choice due to the fact that plane causes rendering issues.

Are you referring to https://github.com/godotengine/godot/pull/44525 ? This is a problem that would also happen with QuadMesh if used to cover a very large surface without subdivision.

**Comment by clayjohn** [comment]
> I wonder which mesh should be the default, if plane or quad ..

Flip a coin :) 

But really, I would just do a quick survey of other engines and Blender and see what is more common. I lean towards PlaneMesh as it is has been around much longer than QuadMesh.

**Comment by Calinou** [comment]
I think the "Plane" term is more intuitive than "Quad", so I'd go for plane too.

**Comment by BugBiteSquared** [comment]
This seemingly breaks post-process shaders that formerly used a fullscreen QuadMesh MeshInstance. Upon copying my project & porting the copy to Godot & setting up new shaders & materials (syntax updated for Godot 4's shader language, of course), the exp-squared distance fog post-process shader I implemented in Godot 3.5 no longer works.

This is consistent with attempting to use a PlaneMesh instead of a QuadMesh for a fullscreen post-process shader in Godot 3.5. I'm actually not entirely sure what would cause this since PlaneMesh & QuadMesh seem like they *should* be interchangeable for this use case.

**Comment by clayjohn** [comment]
@BugBiteSquared You need to set the ``orientation`` parameter to ``FACE_Z``. The documentation will be updated to reflect this change. We unfortunately do not have a tool to automatically replace QuadMeshes with PlaneMeshes _and_ update an internal property.

**Comment by BugBiteSquared** [comment]
> @BugBiteSquared You need to set the `orientation` parameter to `FACE_Z`. The documentation will be updated to reflect this change. We unfortunately do not have a tool to automatically replace QuadMeshes with PlaneMeshes _and_ update an internal property.

Ah, I did actually try that & it didn't work, hah. I found that ticking the "Flip Faces" box in the inspector for the PlaneMesh did the trick though!

**Comment by RPicster** [comment]
I just tested another PR regarding Particles and saw that QuadMesh was missing.

I don't feel like this was thought through because as is, it's not possible to create a simple particle system using billboard mode + plane mesh.

Also, wanting to create a simple particle system is now much more painful since the user needs to "find" the right orientation on the plane mesh to make it work with billboard mode. There is no setting available to make it work like it should.

Overall, from a user perspective I find it extremely annoying that now I have to play around with settings to get a simple working billboard particle system.

**Comment by clayjohn** [comment]
If it's too much of a pain to set the orientation, we can just default to FACE_Z.

**Comment by fire** [comment]
For usability please do this!
