### ISSUE TITLE
Change Shadow Rendering Pipeline

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#4517]
### Describe the project you are working on

Open World Game

### Describe the problem or limitation you are having in your project

Having to tweak settings around a lot to balance out Shadow Acne and Peter Panning

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By Default Render Shadows with Reverse Face culling, and ignore all Biasing (so as if bias and normal bias were both at 0, for all shadows), instead, Shrink the Shadow Meshes by some user defined value (Default of 0.0025 seems to do the trick really well)

Pros:
1) It is a "Just Works" Solution, with way fewer edge cases compared to the Current normal Face Culling with biasing, so User is generally care-free.
2) Shadow Acne is a thing of the Past, as it is moved to the area within the mesh between the Original Mesh and the Shadow Mesh (which is typically never visible)
3) Peter Panning is also a thing of the Past * (a light leak might appear where two objects intersect, however that is why the shadow mesh is shrunk to hide that)
4) Allows for Significant reductions in Shadow Mesh Polycount for essentially the same shadow quality, without introducing Self Shadowing (aka Shadow Acne) allowing the user to Improve Shadow Performance Significantly
5) All Shadow Types Benefit (Directional Shadows (moderate benefits), Omni Shadows (huge benefits), Spot Shadows (small benefits))

Cons:
1) Shadows are slightly Uniformly shrunk, by a constant value, This is only clearly observable in a direct side-by-side comparison
2) Some meshes might exhibit holes, due to the shrinking, because of some faces not being connected properly. This is solved in Blender with Weld, but the exact values needed might vary from mesh to mesh (Default of 0.001 seems to do the trick well), as going to aggressive with the merge distance can incorrectly merge stuff (thus losing geometry detail), however probably not a big problem when only dealing with Shadows

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Have Two Shadow Rendering Modes:
1) Enhanced/Automatic/... Find appropriate name (this method)
2) Classic (current)

Using this Method Do the following:
1) Flip all Shadow Mesh Triangles (so Reverse Face Culling On)
2) Shrink all Shadow Meshes by Shrink Value (default 0.0025 probably) This setting should be on a Per Surface Basis
3) Set All Shadow Bias and ~~Normal Bias~~ values to 0  - Normal Bias is actually still useful for really low Res Shadows, so a Value of 1 still makes sense, but nothing higher
4) Optionally Reduce Shadow Mesh LOD (like https://github.com/godotengine/godot-proposals/issues/2600#issuecomment-991765784 for example)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, you can set Lights to Reverse Face Cull and Shrink them a little in Blender or using only Base/Standard Material 3D with separate Meshes for Shadows and Normal Rendering.

### Is there a reason why this should be core and not an add-on in the asset library?

It turns the Shadow Rendering (which is core) into "It just Works"

### NOTES
Flip Mesh Triangles can be Done by Changing Cull Mode to Front in Base/Standard Material 3D
Shrink can be done using Base/Standard Material 3D Grow

**Comment by mrjustaguy** [comment]
Some Comparisons:
Omni-Spot With Proposal (Left to Right) - Bias 0, Reversed Face Culling, Shrunk by 0.003 - 3k Shadow Triangles
![image](https://user-images.githubusercontent.com/50302479/167910137-cd67c131-32c0-4335-9a35-3b5b9d256951.png)

Omni-Spot Without Proposal (Left to Right) - Default Bias G4 A7, Normal Face Culling, No Shrinking - 30k Shadow Triangles
![image](https://user-images.githubusercontent.com/50302479/167910756-3e9bc95c-6e67-4e72-a65c-b10f18ada970.png)

Directional Light with Proposal - Bias 0, Reversed Face Culling, Shrunk by 0.003 - 3k Shadow Triangles
![image](https://user-images.githubusercontent.com/50302479/167911452-12b2c9c7-4b36-464e-a1c0-1d5709cd5922.png)

Directional Light Without Proposal - Default bias G4 A7, Normal Face Culling, No Shrinking - 30k Shadow Triangles
![image](https://user-images.githubusercontent.com/50302479/167911239-c74c3274-0fc1-452f-9d8c-489b3017f721.png)

30k Triangle Shadow Mesh
![image](https://user-images.githubusercontent.com/50302479/167911818-5b2fc8ac-9c91-4d0e-b8df-038d6445bdcb.png)

3k Triangle Shadow Mesh
![image](https://user-images.githubusercontent.com/50302479/167911981-cb25aaca-6c32-4a55-a3b9-8b62e04bcd76.png)

**Comment by mrjustaguy** [comment]
Closing as users can already do this, and would be a fairly big compatibility breakage that's probably not worth it for most users, especially if/when newer shadowing techniques become available

**Comment by ODtian** [comment]
Will this approach improve quality of self-shadow (mean it by object casting shadows on it self) and shadows that casted by close distance object?
