### ISSUE TITLE
Allow moving only one side of extents-based rectangles/boxes using editor gizmos

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#452]
**Describe the project you are working on:**
2D game.

**Describe the problem or limitation you are having in your project:**
I often use CollisionShape2D nodes with rectangle shapes. Their problem is that you need to place the rectangle in the middle of the object and expand the extents to match the object's size. Because the extents increase from both sides and it's not always obvious where object's center may be, it often requires trial-and-error to get done correctly, which is simply a waste of time.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If I could change the rectangle's extents with handles on any side, like this is done with scaling Sprites or resizing Control nodes, it would save some time and make adding colliders more friendly.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/2223172/74072612-9bf56a80-4a07-11ea-8946-a53a21d07d3e.png)
![image](https://user-images.githubusercontent.com/2223172/74072622-a57ed280-4a07-11ea-9dbf-f0bff2e9ce48.png)

**Describe implementation detail for your proposal (in code), if possible:**
RectangleShapes2D should be edited like Control rectangles. This can be achieved by editing `extents` of RectangleShape2D and `position` of CollisionShape2D simultaneously.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it would require a plugin.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a QoL thing for collision shapes.

**Comment by Calinou** [comment]
This is also an issue with 3D shapes (such as many CSG nodes).

**Comment by Calinou** [comment]
@JamesC01 Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Zireael07** [comment]
Leaving a comment here to say this also applies to 3D, not just 2D.
