### ISSUE TITLE
Curve Texture

### ISSUE THREAD

**Issue by mashumafi** [godotengine/godot-proposals#4525]
### Describe the project you are working on

I want to use a curve's data in a shader. A texture generated using a `Curve` resource could make this possible.

### Describe the problem or limitation you are having in your project

`Gradient` can be a bit awkward to use

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Generates a texture similar to noise texture (black/white) but controlled with a `Curve`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See noise or gradient textures

### If this enhancement will not be used often, can it be worked around with a few lines of script?

`Gradient` could be used

### Is there a reason why this should be core and not an add-on in the asset library?

`Texture` is abstract and cannot be created as a script

**Comment by clayjohn** [comment]
[CurveTextures](https://docs.godotengine.org/en/latest/classes/class_curvetexture.html) are already implemented in the engine! There is also the [CurveXYZTexture](https://docs.godotengine.org/en/latest/classes/class_curvexyztexture.html) coming in 4.0 if you want to bake 3 curves into a single texture.
