### ISSUE TITLE
Add a `VideoStream.get_length()` method

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#4529]
### Describe the project you are working on

A NO-GAME app

### Describe the problem or limitation you are having in your project

I want implement a videoplayer, the user can seek any position to play.
But now I can't get the VideoStream's length. So I can't set my slider's range.
IMO, AudioStream and VideoStream should have then most same methods and AudioStream was a get_length() method,
so VideoStream should have this method too.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I can set my slider's range to:
```
slider.set_range(0,video_stream.get_length())
```
And user can adjust the slider for seek right position

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know how to implement with GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

It should be core, I think.

**Comment by rsubtil** [comment]
Should be closed by https://github.com/godotengine/godot/pull/77858
