### ISSUE TITLE
Add a SCons option for Mold linker

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot-proposals#4531]
### Describe the project you are working on

With `LDFLAGS="-fuse-ld=mold"` and `LD="ld.mold"` env vars it's possible to compile any project with gcc/clang compiler while using mold as linker: https://github.com/rui314/mold.git

### Describe the problem or limitation you are having in your project

Currently there are only `llvm=yes`, `lld=yes` and `thinlto=yes` scons options to define compiler/linker.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add scons option `mold=yes` for linking final executable with mold.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change `a/platform/x11/detect.py` and add scons option / env args for mold linker.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Adding `LINKFLAGS="-fuse-ld=mold"` to scons command line should work too.

### Is there a reason why this should be core and not an add-on in the asset library?

Proposal is about build system configuration when compiling godot from source.

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face: 

> Currently there are only llvm=yes, lld=yes and thinlto=yes scons options to define compiler/linker.

These are actually `use_llvm=yes`, `use_lld=yes` and `use_thinlto=yes`.

That said, now might be a good time to change the options to enums to avoid incompatible choices:

- Replace `use_lto=yes` and `use_lto=yes` with `lto=none|thin|full`.
- Replace `use_lld=yes` with `linker=ld|gold|lld|mold`.
