### ISSUE TITLE
OptionButton should allow reselection

### ISSUE THREAD

**Issue by okla** [godotengine/godot-proposals#4539]
### Describe the project you are working on

An open world aircraft simulator

### Describe the problem or limitation you are having in your project

In the project I want to select multiple objects and paint them with a color selected from OptionButton. Then I may want to select another objects and paint them with the same color. But since OptionButton doesn't allow reselection of already selected item, I cannot do this.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

OptionButton should allow reselection to let me color objects with the same color

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

OptionBUtton should emit item_selected() signal after selection of already selected item

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think this can be done as add-on

**Comment by okla** [comment]
Have added possible implementation as a draft PR (not sure that made everything right): https://github.com/godotengine/godot/pull/61009

**Comment by Calinou** [comment]
This has potential performance implications for OptionButtons that trigger an expensive recalculation when changed. That said, nothing prevents you from checking if the old value is equal to the new value in the receiver function of the signal.

**Comment by KoBeWi** [comment]
This could be optional and enabled by `allow_reselect` property, like in ItemList for example.

**Comment by okla** [comment]
Maybe we can add an argument to signal, something like `item_selected(bool reselected)` and perform the check before emitting? Or this will break compatibility with current receiver functions?

**Comment by okla** [comment]
I've messed up implementation branch, here's the new one https://github.com/godotengine/godot/pull/61051

**Comment by KoBeWi** [comment]
IMO it should be a property, not signal argument. When signal arrives, you don't really care if it was selected or reselected.

**Comment by kilojool** [comment]
I'd really like to see this implemented.
Any reason that https://github.com/godotengine/godot/pull/61051 wasn't merged? Would it be better with an `allow_reselect` flag as suggested above by KoBeWi?

**Comment by KoBeWi** [comment]
The PR was closed (likely by the author's action).

**Comment by YuriSizov** [comment]
They've deleted the branch, so a pull cannot be performed and GitHub automatically closes the PR.

**Comment by okla** [comment]
@YuriSizov oops, didn't know about that.

@kilojool you can recreate the PR if you wish, probably with @KoBeWi's improvements
