### ISSUE TITLE
Allow to disable TextEdit scroll

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#4546]
### Describe the project you are working on

Kanban-like plugin that allow to organize random notes in columns.
https://github.com/KoBeWi/Godot-Simple-TODO

### Describe the problem or limitation you are having in your project

I have a kanban-like plugin that allows to create random notes and put them in columns (see above). Each column is a huge VScrollContainer with many TextEdit nodes. It needs to be TextEdits, because I want the notes to be multiline. But I also want them to have minimal height, so they don't take space. Unfortunately, TextEdit comes with scrollbars and I end up with single-line cards with tiny scroll.

Previously I hacked it by using a hidden label that syncs text with the TextEdit. The TextEdit would just take the minimum size from the label, assuming that it wraps the same etc. It worked better than expected, but then I upgraded the plugin to 4.0, wrapping has changed and I can no longer reliably sync the nodes. I could try tweaking it more to achieve desired effect, but it's an ugly hack that should just die.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Instead of playing with invisible labels, it would be extremely useful to be able to disable vertical scrolling. Just like in ScrollContainer, if you disable scroll, the content will just force minimum size. I want this in TextEdit.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a property called `vertical_scroll_enabled`. When disabled, calculate minimum height of TextEdit based on text size.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Please don't make me use the workarounds again :<

### Is there a reason why this should be core and not an add-on in the asset library?

I would gladly welcome a reliably working add-on that solves this problem.

**Comment by Nukiloco** [comment]
I would like to have this as well since I have made multiple of projects where I wanted to disable the scrolling on TextEdit and had to use hacks just to bypass it. 👍

**Comment by ignurof** [comment]
I came across this a few days ago too and found it to be real annoying.
This would be a very welcome change for sure!

**Comment by Calinou** [comment]
@ignurof Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
