### ISSUE TITLE
Allow adding custom ResourceFormatLoaders and ResourceFormatSavers with GDExtension

### ISSUE THREAD

**Issue by leogeier** [godotengine/godot-proposals#4548]
### Describe the project you are working on

A [language binding for Squeak/Smalltalk](https://github.com/hpi-swa-lab/godot-squeak). More specifically, I want to port my existing prototype from Godot 3 to 4.

### Describe the problem or limitation you are having in your project

Currently, ResourceFormatLoaders and -Savers defined in a GDExtension plugin cannot actually be used by the engine. The mechanism that adds custom loaders and savers is based on global classes, such as GDScripts with `class_name`, and thus depends on them being present as script files in the file system. It is also not possible to register loaders and savers directly because `ResourceLoader::add_resource_format_loader` and `ResourceSaver::add_resource_format_saver` are not exposed in the ClassDB.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

ResourceFormatLoaders and -Savers should either be registered automatically like ones defined with GDScript, or it should be possible to do so with directly with GDExtension.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The first and easier solution I see is to simply expose `ResourceLoader::add_resource_format_loader` and `ResourceSaver::add_resource_format_saver` in the ClassDB. This would allow adding Loaders and -Savers from within the GDExtension plugin directly. I attempted an implementation [here](/leogeier/godot/tree/expose-adding-resource-loaders-savers). I believe that this would be easier to understand for GDExtension developers since you only have to call a single method instead of preparing your classes so they can be picked up by the global class mechanism. However, I can also imagine that this could be confusing for GDScript (and other) developers, since the newly exposed functions would be visible in the docs--this might wrongly imply that they would need to be called in all cases.

The second solution would be to allow adding GDExtension classes to the global class list. This in turn would enable them to be picked up by the existing mechanism for registering ResourceFormatLoaders and -Savers. This might include adding an additional field to `GDNativeExtensionClassCreationInfo` that designates the extension class as global and updating the Loader and Saver lists at plugin load. However, it seems to me that global classes are supposed to be scripts, and since GDExtension classes are closer to internal classes, this solution might not fit the architecture.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It might be possible to create global ResourceFormatLoaders and -Savers with GDScript that forward method calls to their GDExtension counterparts.

### Is there a reason why this should be core and not an add-on in the asset library?

The first solution extends the ResourceLoader and -Saver singletons, the second requires changes to GDExtension. Both are core changes.

**Comment by kleonc** [comment]
The first solution. :+1:
But I'd also expose `remove_*` counterparts.

BTW is there a way to obtain built-in ResourceFormatLoaders/Savers? Would be nice to be able to. This way with these methods exposed it would be possible to potentially remove the built-in ones, in case someone wants to customize things (for whatever reason).

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/61096.
