### ISSUE TITLE
Dialog windows should not resize below the minimal size of their children

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot-proposals#455]
Dialog windows should not resize below the (minimal) size of their children. (maybe optionally?)
Currently, it's possible to resize any window (even FileDialog!) to a very small size, and then its elements "hover in the air".

Of course, there is rect_min_size, but calculating a min_size and statically setting it for each window feels like a dirty workaround (different DPI? Adding children at runtime? Adding children and forgetting to recalculate min_size?).

**Describe the project you are working on:**
An editor plugin that mostly uses dialog windows rather than toolbars.

**Describe the problem or limitation you are having in your project:**
I have a WindowDialog with a few buttons in a VBoxContainer. There are expandable separators between buttons, so the container is resized along with the window. This window being resizeable is good, because it's an editor plugin and everyone has different resolutions. The problem is, I can resize this window to be almost (0,0) - with only the window title visible, and all its elements "float in the air". This "looks bad", which is technically not a big problem, but "looking good" may be quite important for the general impression on the user. I remember Godot being praised as "the best engine for 2D" and particularly for its editor interface, so I think improving in this area would be worthwhile.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
I think windows should not resize below the size of their elements by default. AFAIK this is the "expected" behavior based on any other UI library (Lazarus, Qt, whatever is dealing with windows). I think this will "feel more polished" to the new users, rather than what we have now.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
It makes more sense to show what we have now instead:
![test1](https://user-images.githubusercontent.com/16963337/74084193-d7328080-4a7d-11ea-9919-6bb12d3cdd58.png)
![test2](https://user-images.githubusercontent.com/16963337/74084195-d994da80-4a7d-11ea-8aa8-9441635ad1ad.png)
However, this is not a "bug", but "lack of functionality" or "intentional decision", so I think it belongs to the "Proposals" section.

**Describe implementation detail for your proposal (in code), if possible:**
There are many ways to implement this. I think the easiest one would be calculating rect_min_size automatically based on the elements that are currently on that window. Maybe do that by default, but let the user modify it if necessary?.. Maybe make it modifiable, but not below the "hard" limits calculated from its children?.. That depends on whether anyone needs this behavior to remain as it is, and for what reasons.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Workarounds include:
- either setting rect_min_size manually once, which is not a good idea in case something changes,
- or checking the window size on each update and fixing it if necessary, which might be fairly complex (I don't even know how would I do that "in a good way" - that's too hard).

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think this is one of the very basic behaviors expected from the core UI functionality, so fixing it right in the window code would be most suitable. Also, I don't think anyone would miss the current behavior (but that has yet to be confirmed).

**Comment by girng** [comment]
Yeah, when resizing the the `WindowDialog`, it should not exceed the min_height:
https://i.gyazo.com/462c02f11ae50e4214903c7209b14db4.mp4

It's a bug

**Comment by dark-penguin** [comment]
What's "min_height"? (I don't see it in WindowDialog class documentation.) Maybe you mean rect_min_size ?

Is it really specified for this window? I thought it is set to 0 by default, so this looks like intended current behavior. If you set rect_min_size to something other than (0,0), then the window does not resize below that.

The idea is, it should probably not be 0 - it should be calculated automatically in runtime based on the size of its elements.

**Comment by girng** [comment]
Yeah `rect_min_size`, my bad.  Not sure on internals, @groud is the expert there. But it should constrain itself to the total min height of a container

**Comment by dark-penguin** [comment]
On 3.2.3, Dialogs still suffer from this problem, but FileDialogs seem to have been fixed!

**Comment by KoBeWi** [comment]
This was resolved in Godot 4 with the dialogs rework.
