### ISSUE TITLE
CylinderMesh should have flags indicting if end caps should be drawn

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#4560]
### Describe the project you are working on

Special effects for spells and item usage.

### Describe the problem or limitation you are having in your project

I need a cylindrical mesh that I can apply a texture to that represents things like magical glows and electric arcs.  Cylinders are good for this.  The trouble is, I need a hollow cylinder that does not include the end caps.  It would be useful if flags were added to CylinderMesh that indicate if the end caps should be drawn.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If  the caps are absent, the special effect will render correctly.  Otherwise I need to create a custom mesh of a cylinder and import it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add boolean parameters named 'top cap' and 'bottom cap' to CylinderMesh.  They will be true by default.  If false, the generated mesh will omit that part of the cylinder.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I would need to create and import a cylinder mesh.

### Is there a reason why this should be core and not an add-on in the asset library?

It would involve changing code in the core.

**Comment by clayjohn** [comment]
Sounds like a good idea to! Should be easy to do without adding overhead or compatibility breakage as long as both properties are true by default.

**Comment by Calinou** [comment]
Is there an use case for generating a CylinerMesh with only *one* cap?

**Comment by blackears** [comment]
I can't think of one, but some user might find it useful.  It should not be much extra work to toggle them independently.
