### ISSUE TITLE
Move "center offset" to base mesh class to use it for all types of meshes

### ISSUE THREAD

**Issue by Drachenbauer** [godotengine/godot-proposals#4570]
### Describe the project you are working on

A 3D-sokoban with a gridmap that displays meshes from a mesh library

### Describe the problem or limitation you are having in your project

meshlibrary and gridmap do not support the translation in the transform section of meshinstance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

the mesh-types planemesh and quadmesh have a variable/property "center offset", that´s applied in meshlibraries and gridmaps as well and allows to position these mesh types easily in the gridmap-cell.

If this property with everything, it needs to work is removed from there and added to the basic mesh-class, where all mesh types inherit from, all types of meshes can be positioned so easy for gridmaps.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the basic class gets a function, for sample:

`func add_center_offset(vertices):
    for vertex in vertices:
        vertex += center_offset`

"center_offset" is the variable for the user to set values to offset the mesh from it´s origin.
"vertices" receives an array of all vertex-positions, which the engine uses to render the mesh.
The best solution is, if it is able to directly override the values, which go to the renderer, that draws the mesh on the game-screen.

maybe it´s already coded a good way in planemesh and quadmesh to just move it to the parent class.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

the only walk around i found is by redrawing the mesh in blender or something similar with the needed offset and use this obj-file instead of the godot build in mesh

### Is there a reason why this should be core and not an add-on in the asset library?

Because it´s directly part of the mesh-classes.

**Comment by Zireael07** [comment]
I have a feeling this is a dupe/related to an existing proposal, which may be meshlib specific... but can't find it?

**Comment by Drachenbauer** [comment]
i couldn´t find it

**Comment by Calinou** [comment]
Which Godot version are you using? Transforms in individual GridMap items are supported since Godot 3.4: https://github.com/godotengine/godot-proposals/issues/3716

**Comment by Drachenbauer** [comment]
having the center offset for all meshes looks more intuitive than this mesh-transform with the twelve values.

**Comment by Drachenbauer** [comment]
all the time before i taught, these values are three groups, each beginning with one, that is 1 by default.

**Comment by Calinou** [comment]
Closing, as this feature is already implemented as said above. The value is only stored as a single transform for optimization reasons.
