### ISSUE TITLE
Make array and dictionary constants deep

### ISSUE THREAD

**Issue by Trioct** [godotengine/godot-proposals#4576]
### Describe the project you are working on

Typical simple project to test Godot 4.

### Describe the problem or limitation you are having in your project

`const` has an unintuitive and error-prone implementation.
A few open (there are more that are closed) issues related to the current definition of const:
[#56306](https://github.com/godotengine/godot/issues/56306)
[#52422](https://github.com/godotengine/godot/issues/52422)
[#61274](https://github.com/godotengine/godot/issues/61274)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Constant arrays and dictionaries should be made permanently read-only. A few days ago we got [#61087](https://github.com/godotengine/godot/pull/61087) and [#61127](https://github.com/godotengine/godot/pull/61127), allowing a simple mechanism. With being read-only, they'll be copied on assignment(? whatever is implemented these prs. I think it's copy on assignment) Consts would be constant expressions instead of one-time assignable variables, as the compiler expects. #820 would be a better fit for what const arrays/dictionaries are now.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My take on the problem is https://github.com/Trioct/godot/commit/b044060fe03e6f1e9ec056ef2c6180a596ca689e, making const arrays/dictionaries permanently read-only. This allows [#41983](https://github.com/godotengine/godot/pull/41983) to be reverted as well, fixing [#52422](https://github.com/godotengine/godot/issues/52422).

Example:
```gdscript
const x := [3,2,1]
x.append(0) # Runtime error, x is read-only

var y := x
y.append(0) # Works, x is copied to y. x remains unchanged.
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Doesn't really apply.

### Is there a reason why this should be core and not an add-on in the asset library?

Don't think this applies either.

**Comment by Mickeon** [comment]
And to perhaps keep tbe current functionality (which I use greatly may I add), `static` could finally be used for variables as well?

**Comment by Calinou** [comment]
> And to perhaps keep tbe current functionality (which I use greatly may I add), `static` could finally be used for variables as well?

`static var` won't be added in the interest of thread safety. https://github.com/godotengine/godot/issues/6840
