### ISSUE TITLE
Allow accessing Scene Unique Nodes without quotes in GDScript

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot-proposals#4583]
### Describe the project you are working on

An application for procedurally generating 2D maps.

### Describe the problem or limitation you are having in your project

Scene Unique Nodes require using quotes to access them in GDScript, which causes syntax highlighting to turn yellow instead of green in 3.x. I frequently use the green syntax highlighting color to quickly identify node references in scripts, but this does not work with the Scene Unique Nodes feature.

In 4.0 paths after the `$` sign are green even with quotes, but it would still be more convenient to not require typing quotes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow accessing Scene Unique Nodes without quotes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Current:
```gdscript
$"%NodeName"
```

After:
```gdscript
$%NodeName
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, GDScript syntax cannot be modified by a script.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be made as an addon.

**Comment by fire-forge** [comment]
> It seems like the plan may be to be able to use `%` alone without need of `$` or `get_node()`

That would be nice, but how would that work with `%` also being the modulo operator? For example, is `%NodeName` accessing a scene unique node named `NodeName` or using the modulo operator on a variable named `NodeName`?

**Comment by Mickeon** [comment]
It would definitely work, but personally, it really would make the "`%` is not used by anything else" argument for choosing the symbol really flimsy! (it's also used for [string formatting](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_format_string.html)!)
