### ISSUE TITLE
Add methods `save_to_string()` and `load_from_string(String x509str)` to X509Certificate

### ISSUE THREAD

**Issue by tx350z** [godotengine/godot-proposals#4585]
### Describe the project you are working on

Distributed MMO app that relies on WebSockets using self-signed X509 Certificates.

### Describe the problem or limitation you are having in your project

I need to save X509 certificates in a config file 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Would like to store X509 certificate PEM in a config file similar to how CryptoKey can be saved/loaded using a String.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
var crypto:Crypto = Crypto.new();
var cert_key:CryptoKey = crypto.generate_rsa(4096);
var cert:X509Certificate = crypto.generate_self_signed_certificate(cert_key,"CN=example.com,O=A Game Company,C=IT");
var cert_pem:String = cert.save_to_string();

var cert2:X509Certificate = X509Certificate.new();
cert2.load_from_string(cert_pem);

```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The current work around is to save the certificate to a temp file, read it as as text, then delete the temp file. To load requires saving the PEM string to a temp file, loading the certificate from the file, then deleting the file.

### Is there a reason why this should be core and not an add-on in the asset library?

An add-on would have to use the above described work around.

**Comment by ScorpionInc** [comment]
I made an example project to see it in action as well.
https://github.com/ScorpionInc/godot-projects/tree/main/SerialCertificateTest
![Untitled7](https://user-images.githubusercontent.com/19487319/230233668-88a50224-872c-474f-8517-97fd3c2d016e.png)
