### ISSUE TITLE
Adding options to godot's downscaling/downsampling

### ISSUE THREAD

**Issue by rageboi1011** [godotengine/godot-proposals#4586]
### Describe the project you are working on

Godot can downscale textures perfectly fine, but when you change the window's size while using keep in the window stretch settings, everything gets pixelated. Most likely this is because Godot uses something like nearest neighbour to downscale the window's contents, instead of something like bicubic scaling.

![image](https://user-images.githubusercontent.com/60071448/170122451-ee443fa7-ab4c-4f98-a6d8-a7516a17e5cb.png)

### Describe the problem or limitation you are having in your project

Both of my current projects are mainly UI based and it's really bugging me how they look janky when they're windowed

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'd like to ask for a way to change this downscaling from whatever Godot is currently using, to bicubic for example.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't think this needs any further explanation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Possibly, if someone were to not use keep and viewport in the window stretch options and instead scale stuff according to the window's size using a camera or something, but I feel like it should be a default option.

### Is there a reason why this should be core and not an add-on in the asset library?

People shouldn't have to look for a feature that can be so essential for making your UI look nice.

**Comment by Calinou** [comment]
If you use the `2d` stretch mode, Godot will render at native resolution. Textures will be scaled with bilinear filtering if filtering is enabled on them (which is the default), or nearest-neighbor filtering if filtering is disabled on them.

Do not use the `viewport` stretch mode for applications. In fact, for applications, you probably want to use the `disabled` stretch mode to get more control over the scale factor.

**Comment by rageboi1011** [comment]
Oh wow I did not expect a reply this fast. Thanks for the advice dude 👍
