### ISSUE TITLE
Retrieve normal map from CanvasTexture atlas in TileSet/TileMap

### ISSUE THREAD

**Issue by MyStarrySpace** [godotengine/godot-proposals#4587]
### Describe the project you are working on

A procedurally generated top-down 2D pixel art factory game

### Describe the problem or limitation you are having in your project

Using a CanvasTexture with a diffuse and normal map attached will only render tiles with the diffuse map, but will not add normals to the tiles. There is seemingly no way in Godot 4.0 to use normal maps with TileSets. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When tiles are pulled from the atlas to draw the tiles, normal map data should also be retrieved and added. This provides the normal map data that is currently missing.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When a user configures an atlas texture with a CanvasTexture and the TileSet is drawn, during the draw step, information about the normals can be drawn and used.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I tried to overcome this using GDScript and shaders, but nothing worked

### Is there a reason why this should be core and not an add-on in the asset library?

It should be intuitive that a TileMap made with tiles from a texture with normals should also have normals. Adding normals to tilesets in 3.x was possible, but I can't figure out a way to do it in 4.0, and nobody in the Godot discord seems to be able to either.

**Comment by groud** [comment]
This is a bug not a proposal. Please open a bug report there instead: https://github.com/godotengine/godot/issues

**Comment by mrcdk** [comment]
The issue was identified here https://github.com/godotengine/godot/issues/61832#issuecomment-1296140322 and how to solve it for now. I'd close this proposal as this is a bug.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/61832#issuecomment-1296140322.
