### ISSUE TITLE
GGXrd GDC anime NPC techniques on Godot.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#459]
**Describe the project you are working on:**
2D action platformer.

**Describe the problem or limitation you are having in your project:**
Needs to imitate the GGXrd anime look to be as good as the original project.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It's mostly related to rendering techniques from the video that helps overcome the bad look of average toon shading.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Basically, the most important step is to have a 2D Ramp texture that controls the threshold of the toon shading look, coupled with the normal direction editing of the mesh.

**Describe implementation detail for your proposal (in code), if possible:**
Basically, after watching the GDC lecture, I could come with the following:
- A 2D ramp texture, which is their secret sauce to making the 3D model look like 2D.
- Normal direction editing (dunno if custom normal directions are implemented on godot).
- Custom light points for every individual characters that aren't effected with the other lights (optional).
- An albedo texture, but another tint albedo texture for the shadows
- No Interpolation on the keyframe 3D animation (low FPS limited animation)
- A second UV for another texture with the interior lines properly aligned to X/Y horizontal, vertical lines.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This really doesn't require newer tech for godot, and is mostly shader stuff.

**Is there a reason why this should be core and not an add-on in the asset library?:**
My particular reason to make this proposal is to get the godot comunity to discuss the proper ways to imitate the GGXrd tech inside godot, maybe have a nice shader demo other people can study.

**Comment by Calinou** [comment]
> My particular reason to make this proposal is to get the godot comunity to discuss the proper ways to imitate the GGXrd tech inside godot, maybe have a nice shader demo other people can study.

This repository isn't intended to be used for demo requests. Please use [godot-demo-projects](https://github.com/godotengine/godot-demo-projects) for this instead.

**Comment by clayjohn** [comment]
Proposals are not places to discuss how you would implement a particular shader. For discussion about the usage of the engine please use the [Community Channels](http://docs.godotengine.org/en/latest/community/channels.html). IMO this is a good discussion for reddit or discord in particular.
