### ISSUE TITLE
Html5 Rendering Godot 4

### ISSUE THREAD

**Issue by SchneckeddeF** [godotengine/godot-proposals#4594]
### Describe the project you are working on

A 3d gta like game in Godot 4.x

### Describe the problem or limitation you are having in your project

I cant use html5 export because of vulkan.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

![image](https://user-images.githubusercontent.com/87531743/170450124-31d436bd-bd4c-4b86-acdd-2d181f2362b2.png)
Have an option here to use opengl for html export just like vulkan mobile in backend.mobile

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will work just like in Godot 3.x where you can change the render mode between open gl es 2 and 3

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

It is much more convenient.

**Comment by YuriSizov** [comment]
Web exports require OpenGL support that is still in works. Look for an update news post when it finally gets released.

Also, please use the discussion section of this repo for general inquiries. Create a proposal issue only if you have a detailed plan for a feature.

**Comment by SchneckeddeF** [comment]
> opengl3

Well no it just crashes I change the renderer but yeah I'll be waiting.
