### ISSUE TITLE
Add a feature to dim certain lines in visual script . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#4595]
### Describe the project you are working on

A Godot 4.0 project, very hush - hush . . $ ;-PP

### Describe the problem or limitation you are having in your project

I see the problem of spaghetti - code all the time, it's esp. bad when zoomed in graph edit, bec. the lines sort-of don't scale down, when zoomed . .

![image](https://user-images.githubusercontent.com/83387915/170605934-5535bc71-a4da-488b-85fc-cbfe1cb32474.png)

When zoomed, the line - stuff stays the same . . It makes it very difficult to read spaghetti, so on . .

What I'd like, is a setting to ' dim ' certain types of lines, for me, the non-logic lines . .

![image](https://user-images.githubusercontent.com/83387915/170606195-51457414-bfff-4690-82a3-9585e4ddc276.png)

Not dimmed . .

![image](https://user-images.githubusercontent.com/83387915/170606213-bebcfb18-e737-4c76-a788-87ec2b146a0a.png)

It allows one to see the logic a bit better, get an overview, it's esp. bad when zoomed, bec. the lines don't scale, making spaghetti really difficult, when zoomed . .

Ex. from Unreal engine . .

![image](https://user-images.githubusercontent.com/83387915/170606341-4586aa05-411f-4dbb-971f-1c5db1940e07.png)

I think having some features, for instance to dim non-logic lines, could make it easier to read graph edits, esp. when zoomed to a high level, etc . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, it's a user - interface, here ' readability ' feature, I think being able to dim certain types of lines, prob. just non - logic, could make it easier to read scripts, that's the idea . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a button, or setting, where one can ' dim ' non - logic lines, to 20 %, 10 %, and, see if it doesn't make spaghetti go away, or, make it easier to read . . It might be possible to make it even better, by dimming ' math ' lines, other types, atm think dimming non - logic is what is needed, etc . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Can't re-code the engine, it's a sort-of readability feature, so on . . .

### Is there a reason why this should be core and not an add-on in the asset library?

It's a simple setting, might make spaghetti go ' away ', or much easier to read, and allow to read bigger scripts, at a higher zoom - level, #thx . . . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
