### ISSUE TITLE
Add a CSGCone3D node

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot-proposals#4596]
### Describe the project you are working on

in general i use the CSG objects to avoid any extra dependancies for my addon

### Describe the problem or limitation you are having in your project

i am making a line drawing addon that stretches these shapes as lines, the Cylinder you cannot tell where it starts from for a direction indication

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

this shape would be very useful to me

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

self described except it would be best to have a parameter choosing the amount of sides... in Blender this means setting 4 sides creates a pyramid. The parameter must set the amount of points of the circular base of the mesh.... maybe another pars for "radius" and "height"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

when lacking the right shapes we are forced to import models from a program like Blender

### Is there a reason why this should be core and not an add-on in the asset library?

a few extra csg shapes if we think of them honestly are very useful for prototyping, even icospheres and whatnot...... if someone requires 3D coordinates and that would make this easier i will try to hunt them out... i have already found various shapes around the internet like icospheres etc... i'm not personally aware of the internals of Godot here..... not sure how the UV mapping might be approached being a complication perhaps

**Comment by Calinou** [comment]
> i am making a line drawing addon that stretches these shapes as lines, the Cylinder you cannot tell where it starts from for a direction indication

You don't need CSG for this. Use a MeshInstance3D node with a CylinderMesh, and set the Top Radius property of the CylinderMesh to 0.

That said, if you actually need CSG operations with a cone shape, you should be able to use a CSGMesh with a CSGCylinder node that has its Top Radius property set to 0.

**Comment by kleonc** [comment]
Actually `CSGCylinder(3D)` has `cone` property:
![Godot_v3 4 4-stable_win64_u6lCjsQhxA](https://user-images.githubusercontent.com/9283098/170660907-a84178b6-c9d1-46da-95b2-5882ebca9218.png)

**Comment by Calinou** [comment]
I toyed around with exposing Top Radius and Bottom Radius in CSGCylinder3D (like in CylinderMesh): https://github.com/Calinou/godot/tree/csgcylinder3d-separate-top-bottom-radius

**Comment by RichardEllicott** [comment]
ah okay thanks i also had a look closer and it seems in the multimesh, the thing i wanted it to work with, i do have a cylinder that allows me to adjust it into a cone

thanks for the advice i will close, i will also have a look at what you did i just like built ins if i can think of any, but that covers the cone
