### ISSUE TITLE
Improve / rework SSAO

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot-proposals#46]
**Describe the project you are working on:**
Some simple 3d project.

**Describe how this feature / enhancement will help your project:**
Better visual quality, aswell as SSAO looking more like what you'd expect from it. It may also be a performance increase

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
This is a test implementation (not in godot) at the lowest usable quality in my case, which is 3 samples per pixel at 1/4* resolution. (Edit: I was able to push the quality a bit more by optimizing the sample offsets)
\* Edit2: note that by *1/4* I mean half the width and height, so a quarter of the area / #pixels.
![grafik](https://user-images.githubusercontent.com/3957610/64487383-31fb4e00-d23a-11e9-9226-0be5e11067c8.png)
![grafik](https://user-images.githubusercontent.com/3957610/64487509-e0ec5980-d23b-11e9-872a-2707657f1c79.png)

In comparison, at the lowest setting godot uses **8 samples per pixel at full resolution** which looks like this:
![grafik](https://user-images.githubusercontent.com/3957610/64487482-a08cdb80-d23b-11e9-9175-c9bb9724009d.png)

Even on higher settings this doesn't improve much and isn't worth the performance impact in my opinion.

**Describe implementation detail for your proposal (in code), if possible:**
Using better sample distributions and filtering it's possible to improve the quality of SSAO a lot.
**EDIT:** I will upload a reference implementation [here](https://github.com/CptPotato/SSAO)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no

**Is there a reason why this should be core and not an add-on in the asset library?:**
As it is an improvement of existing core functionality it doesn't make much sense to provide it as an addon.

**Further notes:**
I'd target this for 4.x or 4.0. I'm not sure if I'll have the time to integrate this into godot but providing a reference implementation shouldn't be a problem.

**Comment by VicentGJ** [comment]
This will be great really!!! Right now the main problem with SSAO is that performance sucks, so please prioritize that if you want to improve it

**Comment by CptPotato** [comment]
The performance range should be fairly large with this, as both the sample count and resolution (full vs quarter) can be tweaked without affecting how optimal the algorithm works all that much.

Obviously there will be artifacts on low settings as there has to be some trade-off.

**Comment by CptPotato** [comment]
Small update on the quality range:

<details>
  <summary>Click to view pictures</summary>
  
  This is the lowest possible setting, but at 2 samples/pixel and insufficient filtering you might as well   keep it off.
  ![grafik](https://user-images.githubusercontent.com/3957610/64593852-22e9dc80-d3af-11e9-903c-c2eaf5478efa.png)
  
  ----
  This one is low-ish quality, but usable.
  ![grafik](https://user-images.githubusercontent.com/3957610/64593428-5e37db80-d3ae-11e9-8d95-024ed3997987.png)
  
  ----
  This is everything maxed out (16 samples, full resolution and best filtering).
  ![grafik](https://user-images.githubusercontent.com/3957610/64593473-70b21500-d3ae-11e9-974b-68df3e11a0f1.png)
</details>

**Comment by clayjohn** [comment]
This blog post may be useful. I know the current reconstruction of normals is quite poor. https://wickedengine.net/2019/09/22/improved-normal-reconstruction-from-depth

**Comment by CptPotato** [comment]
@clayjohn interesting. I assumed Godot uses the same normals that are used for lighting. Also thanks for the interesting article.
However, with SSAO this type of self shadowing can actually look pretty good as it pronounces the shape of the object a bit more. I haven't tried it on lower resolution SSAO, though, it may look pretty bad in that case.

**Comment by clayjohn** [comment]
Well. I'll leave it up to you. Your results are already looking very nice. Just thought the article may be useful. :)

**Comment by Calinou** [comment]
@CptPotato Could you provide an example project here (or as a repository on GitHub)? Thanks in advance :slightly_smiling_face:

It doesn't matter if it's not Godot, it could still help another developer implement this in Godot.

**Comment by CptPotato** [comment]
> 
> 
> @CptPotato Could you provide an example project here (or as a repository on GitHub)? Thanks in advance 🙂
> 
> It doesn't matter if it's not Godot, it could still help another developer implement this in Godot.

I'll see if i can setup an implementation in SHADERed this weekend.

**Comment by CptPotato** [comment]
I've [set up a repo](https://github.com/CptPotato/SSAO) where I'll upload the code as SHADERed project soon.
I'm currently still cleaning up the code and fixing / improving some things.

**Comment by Calinou** [comment]
New SSAO has landed a while ago in the `master` branch.

@CptPotato Could you test the new implementation if you have some free time? I could still notice some artifacting when the half-resolution project setting is enabled, but this is a bug more than a feature request.

**Comment by Zireael07** [comment]
Note that this is only in 4.0 (Vulkan).
