### ISSUE TITLE
Add a 'clean' task to C# task list

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#4602]
### Describe the project you are working on

A fighting game.

### Describe the problem or limitation you are having in your project

I like to code in C# and am finding I am sometimes encountering odd bugs where my code is behaving as if other code I have written does not exist or has not been edited.  When I encounter similar situations in a C++ environment, it usually means my object files have become out of sync with my source and usually running a 'make clean' will fix it.  It would be very helpful to have a similar feature in the C# tasks so that you can make sure that your bugs are actually there and not the result of out of date assemblies.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I can be sure my build is up to date.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add an extra task to tasks.json that will clean the project.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is not a Godot script.

### Is there a reason why this should be core and not an add-on in the asset library?

Many users will find this new task useful.

**Comment by Calinou** [comment]
> Add an extra task to tasks.json that will clean the project.

I assume you're referring to VS Code's `tasks.json` file, but Godot does not integrate with VS Code in any way. This is something that should be handled by the C# add-on you're using in VS Code (likely https://github.com/godotengine/godot-csharp-vscode).

**Comment by blackears** [comment]
I've created a separate issue over there.
https://github.com/godotengine/godot-csharp-vscode/issues/45
