### ISSUE TITLE
Godot needs more targeted development

### ISSUE THREAD

**Issue by nickname76** [godotengine/godot-proposals#4618]
### Describe the project you are working on

-

### Describe the problem or limitation you are having in your project

It's acceleration of the development

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Better target for getting fund and getting more industrial use

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The future of game engines, VR Gaming, great **interactivity** of every pices in game world (not only physicial, but mechanical and animational), performance with **little geometry-complex** graphics,  and advanced baked **SPATIAL AUDIO**, which includes all of the available simulation of physical distortion of audio coming to human ears and in human ears.

And by interactivity, more advanced handling of logical interactions between physical objects, that are the main interface in VR games.

Godot basically must handle as much as it can of VR world delivery to human organs and VR world building

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Godot must be for people, who want to use it for VR games ALWAYS

### Is there a reason why this should be core and not an add-on in the asset library?

Godot life

**Comment by YuriSizov** [comment]
Hey, thanks for showing interest in Godot development! Please use community platforms to share your thoughts and reserve this repository for concrete technical enhancement proposals.
