### ISSUE TITLE
Add a distortion texture to WorldEnvironment

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#4622]
### Describe the project you are working on

Various VFX

### Describe the problem or limitation you are having in your project

Right now it's possible only to read SCREEN_TEXTURE pre-alpha pass. this means that any distortion effect will not distort alpha objects.
While this is generally a hard topic in the broader context, in VFX it is common to want to have a shockwave that also distorts the alpha objects (aka the rest of the VFX)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a distortion feature to the world environment, so that the final output can be grabbed before it's rendered to screen.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a feature in world environment that accepts the following parameters:
- enable/disable
- pixel size of max distortion
- distortion texture

The distortion texture will be generated by users and supplied as necessary. 
Example:
I want my VFX to have distortion, so i render a sphere with a shader that colors based on normal in a separate viewport/render layer.
I will obtain something similar to a flow texture and i will assign this texture to the world environment.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is possible to distort by rendering the game in a viewport and then runnign a shader on the viewport, but doing so is less optimised.

### Is there a reason why this should be core and not an add-on in the asset library?

See above

**Comment by QbieShay** [comment]
I'm not even sure this is a good idea anymore, especially my proposed solution of rendring distortion to a separate viewport. Would be superseded if #5257 is implemented

**Comment by Calinou** [comment]
In general, I feel we should have a proper custom post-processing effects solution for effects like these: https://github.com/godotengine/godot-proposals/issues/2196

We can only make the tonemapping shader so complex, and its push constant size is already nearly full (120 bytes of out of 128 last time I checked).
