### ISSUE TITLE
Add "F17 to F24" Keys to KeyList

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#4628]
### Describe the project you are working on

3D Game and 3D Asset Editor

### Describe the problem or limitation you are having in your project

In Godot's KeyList, function keys exist from F1 to F16, but the OS can actually scan up to the F24 key.

Since Godot only handles keys up to F16, it is not possible to subscribe the keys from F17 to F24, and users can't assign shortcuts to that keys.

If there is no particular reason, it should be available up to F24.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since those keys are basically never assigned shortcuts by default, they are useful for assigning user shortcuts without conflicts with default shortcuts in DCC softwares or desktop games such as MMOs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add constants value to `keyboard.cpp` and `@GlobalScope`. However, since `KEY_SUPER_L` is already assigned to the next value after F16, we may need to consider whether to insert or pushback F17-F24 for implementation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

That is Godot's GlobalScope and need to fix the core.

**Comment by gregcsokas** [comment]
Hi,

For fun, I've started solving it, I never contributed anything, so I have some questions.
The keyboard.cpp was easy (I think) 

```diff
diff --git a/core/os/keyboard.cpp b/core/os/keyboard.cpp
index 24907d34c8..54f9705a8d 100644
--- a/core/os/keyboard.cpp
+++ b/core/os/keyboard.cpp
@@ -86,6 +86,14 @@ static const _KeyCodeText _keycodes[] = {
 	{Key::F14                   ,"F14"},
 	{Key::F15                   ,"F15"},
 	{Key::F16                   ,"F16"},
+	{Key::F17		   ,"F17"},
+	{Key::F18		   ,"F18"},
+	{Key::F19		   ,"F19"},
+	{Key::F20		   ,"F20"},
+	{Key::F21		   ,"F21"},
+	{Key::F22		   ,"F22"},
+	{Key::F23		   ,"F23"},
+	{Key::F24		   ,"F24"},
 	{Key::KP_MULTIPLY           ,"Kp Multiply"},
 	{Key::KP_DIVIDE             ,"Kp Divide"},
 	{Key::KP_SUBTRACT           ,"Kp Subtract"},
@@ -333,6 +341,14 @@ bool keycode_has_unicode(Key p_keycode) {
 		case Key::F14:
 		case Key::F15:
 		case Key::F16:
+		case Key::F17:
+		case Key::F18:
+		case Key::F19:
+		case Key::F20:
+		case Key::F21:
+		case Key::F22:
+		case Key::F23:
+		case Key::F24:
 		case Key::SUPER_L:
 		case Key::SUPER_R:
 		case Key::MENU:
```

Now the problematic part, the keyboard.h file, you mentioned `KEY_SUPER_L` is already assigned, for sake of consistency I just continued the values and moved the other 8 like this

```diff
diff --git a/core/os/keyboard.h b/core/os/keyboard.h
index 3176a8a210..57604e96d9 100644
--- a/core/os/keyboard.h
+++ b/core/os/keyboard.h
@@ -85,6 +85,14 @@ enum class Key {
 	F14 = SPECIAL | 0x29,
 	F15 = SPECIAL | 0x2A,
 	F16 = SPECIAL | 0x2B,
+	F17 = SPECIAL | 0x2C,
+	F18 = SPECIAL | 0x2D,
+	F19 = SPECIAL | 0x2E,
+	F20 = SPECIAL | 0x2F,
+	F21 = SPECIAL | 0x30,
+	F22 = SPECIAL | 0x31,
+	F23 = SPECIAL | 0x32,
+	F24 = SPECIAL | 0x33,
 	KP_MULTIPLY = SPECIAL | 0x81,
 	KP_DIVIDE = SPECIAL | 0x82,
 	KP_SUBTRACT = SPECIAL | 0x83,
@@ -100,14 +108,14 @@ enum class Key {
 	KP_7 = SPECIAL | 0x8D,
 	KP_8 = SPECIAL | 0x8E,
 	KP_9 = SPECIAL | 0x8F,
-	SUPER_L = SPECIAL | 0x2C,
-	SUPER_R = SPECIAL | 0x2D,
-	MENU = SPECIAL | 0x2E,
-	HYPER_L = SPECIAL | 0x2F,
-	HYPER_R = SPECIAL | 0x30,
-	HELP = SPECIAL | 0x31,
-	DIRECTION_L = SPECIAL | 0x32,
-	DIRECTION_R = SPECIAL | 0x33,
+	SUPER_L = SPECIAL | 0x34,
+	SUPER_R = SPECIAL | 0x35,
+	MENU = SPECIAL | 0x36,
+	HYPER_L = SPECIAL | 0x37,
+	HYPER_R = SPECIAL | 0x38,
+	HELP = SPECIAL | 0x39,
+	DIRECTION_L = SPECIAL | 0x3A,
+	DIRECTION_R = SPECIAL | 0x3B,
 	BACK = SPECIAL | 0x40,
 	FORWARD = SPECIAL | 0x41,
 	STOP = SPECIAL | 0x42,
```

The other question is, do I need to modify the key_mapping_x11.cpp in the platform -> linuxbsd and other related folders?

**Comment by TokageItLab** [comment]
Basically, anything that is related to key mapping and has constants should be changed. Perhaps the following:

- core_constant.cpp
- keyboard.h
- keyboard.cpp
- key_mapping_x11.cpp
- key_mapping_osx.mm
- key_mapping_windows.cpp

However, I am not that familiar with input implementation, so please send a pull request after you work on it and get it reviewed by other maintainers :)
https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

**Comment by Calinou** [comment]
> resolve [godotengine/godot#62000](https://github.com/godotengine/godot/pull/62000)

For automatic closing on merge to work, you need to write that in the pull request description (with a link to the proposal), not the original issue's description.

**Comment by gregcsokas** [comment]
> > resolve [godotengine/godot#62000](https://github.com/godotengine/godot/pull/62000)
> 
> For automatic closing on merge to work, you need to write that in the pull request description (with a link to the proposal), not the original issue's description. I edited your pull request's description accordingly slightly_smiling_face

Thanks, this is my first contribution :D I promise next I'll be better in this

**Comment by greenfox1505** [comment]
I ran into this bug today on 3.5. Is there any reason this can't/won't be merge back to 3.4.x/3.5.x? I'd like to bind my F13-F24 macro pad to debugging shortcuts

**Comment by Calinou** [comment]
> I ran into this bug today on 3.5. Is there any reason this can't/won't be merge back to 3.4.x/3.5.x? I'd like to bind my F13-F24 macro pad to debugging shortcuts

If you find a way to backport this in a backwards-compatible way, PRs are welcome :slightly_smiling_face: 

That said, even if a pull request is merged in `3.x`, this will only be available in 3.6 as new features are not backported to 3.5.x (and even less 3.4.x).

**Comment by gregcsokas** [comment]
> I ran into this bug today on 3.5. Is there any reason this can't/won't be merge back to 3.4.x/3.5.x? I'd like to bind my F13-F24 macro pad to debugging shortcuts

I never tried to backport anything yet, but I can give it a try

**Comment by greenfox1505** [comment]
> new features 

IMHO **missing keys** is a bug fix, not a "new feature", but I won't argue that point. I'm using Godot-Rust.

The backport should be pretty easy. The keymap files are basically the same. I asked for it, I can do the PR, but you're welcome to if you want.

**Comment by gregcsokas** [comment]
> > new features
> 
> IMHO _missing keys_ is a bug fix, not a "new feature". I'm using Godot-Rust, and they tend to lag behind so I was hoping to get it merge into 3.4.x, but I won't argue that point.
> 
> The backport should be pretty easy. The keymap files are basically the same. I asked for it, I can do the PR, but you're welcome to if you want.

just do it :)

**Comment by greenfox1505** [comment]
Aight. I've gotten to that. It looks like the Mac keyboard system has changed quite a bit and I can't find a Mac scancode map.

https://github.com/godotengine/godot/commit/92e19b2f988db7b2f969c8961629c4c952fac042
