### ISSUE TITLE
Add a text editor setting to enable or disable dragging and dropping text with the mouse

### ISSUE THREAD

**Issue by MiloThatch4** [godotengine/godot-proposals#4629]
### Describe the project you are working on

This would apply to all of my projects.

### Describe the problem or limitation you are having in your project

In the 3.5 RC 3 and 4.x you can drag and drop selected text with the mouse. When I have something selected and I want to make a new selection I have to click somewhere else and then make the new selection. This often causes accidental rearrangement of text, which is inconvenient.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If there were an option to disable this feature, it would solve my problem. If this already exists, I wasn't able to find it. Other text editors I have used allow you to disable this feature.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There could be a check box somewhere in the Editor Settings under the Text Editor tab. It could be enabled by default.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I can think of.

### Is there a reason why this should be core and not an add-on in the asset library?

This is part of the text editor.

**Comment by fire-forge** [comment]
+1 for this, I have accidentally rearranged text by dragging it several times but I have never used that feature intentionally. When i want to move a piece of code I generally use Ctrl+X and Ctrl+V instead of dragging it with the mouse.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/62221.
