### ISSUE TITLE
Add a timescale to individual animations in AnimationNodeStateMachine

### ISSUE THREAD

**Issue by that-richard** [godotengine/godot-proposals#463]
**Describe the project you are working on:**
A top-down survival adventure sandbox game.

**Describe the problem or limitation you are having in your project:**
I use the State Machine to build up my player animations. I would like to have an attack speed "stat", which will make my attacks faster / slower. I cannot make this happen without changing the time scale on the attack animation depending on what I have equipped.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
When equiping a certain weapon, I will easily just change the animation time scale on my attack animation node, in which I have a script which is handling when the "action" has been done. (It will get triggered sooner or later, along with the visual being in the right place)

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/11839880/74252697-4ca48800-4cee-11ea-9043-962dca607416.png)

**Describe implementation detail for your proposal (in code), if possible:**
Will be a simple input box (**same as the one that is in the AnimationPlayer node**) located in the properties of the individual animations in which you put the scale of how fast the animation should play. (Of course, a way to change it in code, too)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
First answer (David-Ochoa)

**Is there a reason why this should be core and not an add-on in the asset library?:**
More of a consistency issue than a new feature request. If there is a feature in one Animation node, why shouldn't it be in others?

**Comment by David-Ochoa** [comment]
You could use a BlendTree in the StateMachine and call it Attack (click the pencil to edit it),
![image](https://user-images.githubusercontent.com/13645633/74402664-878be600-4dea-11ea-916e-0752c4d32f12.png)
Inside it you can set a TimeScale:
![image](https://user-images.githubusercontent.com/13645633/74402500-0896ad80-4dea-11ea-8d5c-67c47a8af081.png)
Now you can access the TimeScale variable from script:
`animation_tree["parameters/Attack/TimeScale"] = 0.75`

I have few videos I think they can help you:
[Godot's State Machine videos ](https://www.youtube.com/playlist?list=PLtIKE84wQrv8mbVIe5PeAzFR7eDW_E_tL)

**Comment by ctnilpp** [comment]
> You could use a BlendTree in the StateMachine and call it Attack (click the pencil to edit it), ![image](https://user-images.githubusercontent.com/13645633/74402664-878be600-4dea-11ea-916e-0752c4d32f12.png) Inside it you can set a TimeScale: ![image](https://user-images.githubusercontent.com/13645633/74402500-0896ad80-4dea-11ea-8d5c-67c47a8af081.png) Now you can access the TimeScale variable from script: `animation_tree["parameters/Attack/TimeScale"] = 0.75`
> 
> I have few videos I think they can help you: [Godot's State Machine videos ](https://www.youtube.com/playlist?list=PLtIKE84wQrv8mbVIe5PeAzFR7eDW_E_tL)

helpful, thank you very much!!!
