### ISSUE TITLE
Disable Local Coords by default in Particle nodes (and use global coordinates instead)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#4633]
*Related to https://github.com/godotengine/godot-proposals/issues/2533.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

The default local coordinate system for particles makes all particle moves when the node (or one of its parents) is moved. This is generally unexpected of particles, which should behave independently from what their parent is doing in *most* situations. There are some valid exceptions to this, but for the 90% use case (such as smoke emitted from a vehicle), it feels like global coordinates are a better fit.

| Local coordinates *(current default)* | Global coordinates *(proposed new default)* |
|-|-|
| ![](https://docs.godotengine.org/en/stable/_images/paranim20.gif) | ![](https://docs.godotengine.org/en/stable/_images/paranim21.gif) |

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Disable **Local Coords** in GPUParticles3D, GPUParticles2D, CPUParticles3D and CPUParticles2D by default.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change the default value of the `local_coords` member to `false` in the various Particle nodes' code.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about changing a default setting to improve out-of-the-box appearance of particles.

**Comment by QbieShay** [comment]
Up!
