### ISSUE TITLE
Project Record - revolutionary learning function

### ISSUE THREAD

**Issue by Quarnion** [godotengine/godot-proposals#4638]
### Describe the project you are working on

3d sandbox

### Describe the problem or limitation you are having in your project

Not everyone is so easy to start learning the engine and understand how it works

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose to introduce a new function in the engine, called project record, adds a project record button to the menu, this function records every action in the editor, moving the mouse from point A to point B, writing a script in column 27, adding a node, and then save it to project with the ability to remove unnecessary actions.
Then a new user of the engine will be able to install the source of the example, and run this entry in the engine in real time, see how the project was built, at any time you can stop the work, and see how it is implemented (sorry for my English)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

project record file layout:
[action 1]
 added node:
 Sprite
[action 2]
rename node:
Sprite = SpriteBlock
[action 3]
inspector edit:
texture = sprite_example.png
[action 4]
added script:
 node = SpriteBlock
 script_column = 3
 code:
 var score = 0

### If this enhancement will not be used often, can it be worked around with a few lines of script?

 No.

### Is there a reason why this should be core and not an add-on in the asset library?

Learning would be unforgettable and simple :)

**Comment by Nukiloco** [comment]
It sounds like a cool feature, but in my opinion this should be an add-on since I'm pretty sure not a lot of people are going to use it.

**Comment by YuriSizov** [comment]
Something like that requires a more concrete technical proposal for implementation. Please use discussions or social platforms to share general ideas, and maybe someone will be able to come up with a possible. solution.
