### ISSUE TITLE
Add an optional `default` parameter to `ProjectSettings.get_setting()`

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot-proposals#4649]
### Describe the project you are working on

I'm working on a plugin (Dialogic)

### Describe the problem or limitation you are having in your project

It is not a problem or a limitation, but while using the ProjectSettings singleton to load settings from the `project.godot` file, the function only has one argument `(String name)` to get the setting.

https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-method-get-setting

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would love for the `ProjectSettings.get_setting()` function to have a second argument as a fallback in case the setting doesn't exists. This is present in many other built in functions to read settings but somehow it is not present here. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would work like: `ProjectSettings.get_setting('quick_timeline_test/timeline_file', 'whatever')`

If the setting `'quick_timeline_test/timeline_file'` exists, it will return its value from the `project.godot` file.

If the setting `'quick_timeline_test/timeline_file'` doesn't exists it will return `'whatever'` instead. 

The second argument is optional.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around with the `ProjectSettings.has_setting()` and a conditional. But this is not consistent with other similar methods and I feel a fallback is a good option to have in the `get_setting` call.

### Is there a reason why this should be core and not an add-on in the asset library?

For consistency in the API.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/56598.

**Comment by MarioLiebisch** [comment]
Would be useful, but wouldn't this be better covered using #1321?
