### ISSUE TITLE
Disable VRAM compression by default for small textures in Detect 3D

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#4669]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Godot currently forces VRAM compression when a texture is detected to be used in 3D, regardless of its size.

However, VRAM compression is only really beneficial when using high-resolution textures (1024×1024 or more, sometimes 512×512). For small textures such as pixel art, it can decrease quality a lot while not saving much video memory.

Example with a 128×128 texture up close, a 256×256 texture in the middle and a 512×512 texture further away:

| Lossless | VRAM Compressed |
|-|-|
| ![2022-06-14_20 18 16](https://user-images.githubusercontent.com/180032/173661482-0c5d4b5c-eeb1-4e26-b98d-56408bb24217.png) | ![2022-06-14_20 18 45](https://user-images.githubusercontent.com/180032/173661470-dc34b8a3-9ccd-4994-9300-ea42fb3f37d4.png) |

Notice how the 128×128 texture has lost most of its intricate detail (such as the inner mortar) and is almost unrecognizable. The 256×256 texture is not as impacted thanks to its higher resolution, but it still loses its intended appearance in a noticeable manner.

The 512×512 texture does a reasonable job at keeping its quality level, so it's fine to use VRAM compression for those in most cases.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Disable VRAM compression by default for small textures in Detect 3D.

___

***Question:** How much will memory usage increase by doing this?*

Probably not much in practice, even in real world projects with hundreds of small textures used in 3D.

Here's a table with the amount of video memory taken for a RGB8 texture in various sizes. This table assumes a 1:6 compression ratio for VRAM compressed textures, which is the fixed compression ratio offered by S3TC (the most common VRAM compression algorithm on desktop platforms).

| Size | Uncompressed size (Lossless) | VRAM Compressed size | Memory saved by VRAM compression |
|-|-|-|-|
| 64×64 | 12 KB | 2 KB | **-10 KB** |
| 128×128 | 49 KB | 8 KB | **-41 KB** | 
| 256×256 | 197 KB | 33 KB | **-164 KB** |
| 512×512 | 786 KB | 131 KB | **-655 KB** |
| 1024×1024 | 3.15 MB | 525 KB | **-2.63 MB** |
| 2048×2048 | 12.58 MB | 2.10 MB | **-10.48 MB** |
| 4096×4096 | 50.33 MB | 8.39 MB | **-41.94 MB** |

For textures with an alpha channel, the uncompressed size grows by 33% and the VRAM compression ratio is only 1:4 (compared to the uncompressed RGBA8 size).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- Add a project setting to control the minimum size upon which VRAM compression is enabled. By default, I suggest this to be 512×512. This means that all textures smaller than 512×512 use lossless compression instead of VRAM compression.
  - This measurement is done in pixel count, so a 512×256 texture will use lossless compression (as it has twice as less pixels compared to a 512×512 texture).
  - To get the old behavior back, set this to the lowest possible value (16, as VRAM-compressed textures exhibit strange behavior when applied to textures smaller than 16×16).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Automatic VRAM compression can be disabled in the Project Settings' Import defaults by setting **Detect 3D > Compress To** to **Disabled**. However, this applies to all textures regardless of their size, so it's not always optimal.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the out of the box experience for developing 3D games in Godot, especially games with a pixel art aesthetic.

Newcomers to the engine sometimes don't even know why their textures look worse in Godot, so this provides an automatic solution that is still efficient.[^1] Also, this would benefit anyone using `icon.png` in their 3D projects as it wouldn't be reimported with VRAM compression enabled as soon as you use it in 3D.

[^1]: If there are concerns about it feeling too "magic", note that https://github.com/godotengine/godot/pull/62023 prints a special message when a small texture is detected as used in 3D. This way, the user is aware that such textures are treated differently from others.

**Comment by Zireael07** [comment]
+1. Most of my textures, while not pixel art, suffer from artifacts due to a combo of VRAM and mipmapping.

**Comment by Calinou** [comment]
> +1. Most of my textures, while not pixel art, suffer from artifacts due to a combo of VRAM and mipmapping.

To clarify, this proposal does not suggest disabling mipmap generation for small textures. They're still needed to prevent textures from looking grainy at a distance, even for very small textures (16×16 or so).

**Comment by fire** [comment]
I think the proper solution to this is using modern codecs like BPTC BC7 and ASTC for Apple / mobile.

Not sure the impact of decoding webp in the cpu on load.

**Comment by Calinou** [comment]
> I think the proper solution to this is using modern codecs like BPTC BC7 and ASTC for Apple / mobile.
> 
> Not sure the impact of decoding webp in the cpu on load.

Modern compression codecs will still decrease quality a lot on small textures, and lossy compression should also be avoided.

**Comment by Calinou** [comment]
Note that this was reverted by https://github.com/godotengine/godot/pull/62245 (see comments in that PR for rationale).
