### ISSUE TITLE
Please make a better particle engine

### ISSUE THREAD

**Issue by GreatRash** [godotengine/godot-proposals#467]
Current patricles in Godot are bad. Here are some features they lack:

- Sub-emitters
- Physics collisions with scene geometry
- Prewarm flag for looping particles
- Custom emitter shapes
- Ability to emit from shell, but not from whole volume
- Curtom particle geometry
- Ability to align particle rotation with velocity vector

And etc. Particles in Unity or Unreal are way better. I found Open-Source particle engine called [SPARK](https://github.com/Synxis/SPARK), written in C++. It would be great if some functions from it were implemented in Godot.

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
