### ISSUE TITLE
Allow editing a MeshLibrary resource directly

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot-proposals#4678]
### Describe the project you are working on

working with some 3D, sometimes need quick prototype stuff

### Describe the problem or limitation you are having in your project

you can only generate a MeshLibrary by script, but not edit them as a resource

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

i think it's a feature that may just be missing

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

okay their must be a reason for this.... is there a reason you can't edit the MeshLibrary directly

### If this enhancement will not be used often, can it be worked around with a few lines of script?

i am not aware myself how this works, i wanted to make a proposal to ask if this is concidered a missing feature, in the works, or good reason it's not possible etc

### Is there a reason why this should be core and not an add-on in the asset library?

definatly fundamental behaviour

**Comment by RichardEllicott** [comment]
it didn't occur to me to ask if there was another way, i'd prob be quite happy with that for my purposes thanks

I was wondering is it hard to imagine the design for it then is it sorta like of course i just make a general proposal but it's not clear how it would look?

what i might have expected would have been it's just a list of meshes..... anyway i can't complain for my workflow now i will add a little helper script to my project

**Comment by Calinou** [comment]
> I was wondering is it hard to imagine the design for it then is it sorta like of course i just make a general proposal but it's not clear how it would look?

Please use the [Discussions](https://github.com/godotengine/godot-proposals/discussions) page of this repository if you do not have a clear idea about the implementation.

I'll close this proposal as there isn't anything actionable now. If you need better documentation on a feature, please open an issue on [godot-docs](https://github.com/godotengine/godot-docs) after searching for possible duplicates.
