### ISSUE TITLE
Please make gui for wrapping properties like rotation in godot 4.0's MultiplayerSyncernizer node

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#4688]
### Describe the project you are working on

Spaceship game.

### Describe the problem or limitation you are having in your project

Rotations need to be properly interpolated since they wrap around

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the MultiplayerSyncernizer gui for clamping or wrapping properties around a min and max value.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not sure I am guessing it would be part of the gui.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it would be used for things like rotations

### Is there a reason why this should be core and not an add-on in the asset library?

It's already in the core library it's just a improvement.

**Comment by YuriSizov** [comment]
Please use the Discussion section for suggestions, and open proposals only when you can provide implementation detail.
