### ISSUE TITLE
Change path of a Node in Animation Player

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot-proposals#469]
**Describe the project you are working on:**
I'm working on a 2D turn-based RPG.

**Describe the problem or limitation you are having in your project:**
Well, you see, I work a lot on Animation Player, but sometimes I have to change the path of a node I'm working on, and the Animation Player won't follow it. 

![Tip1](https://user-images.githubusercontent.com/43701418/74460282-6919ff00-4e6b-11ea-93e9-e88e4c100ac2.png)

![Tip2](https://user-images.githubusercontent.com/43701418/74459782-a467fe00-4e6a-11ea-8c36-22723c23741b.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Change the Node path on Animation Player. I'm doing by hand, but if I could change just the node and keep all the timeline and properties then it would be save a lot of time.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

It could be automatic, but I think it would be better if you could just click here and put where the node is right now:

![Tip1](https://user-images.githubusercontent.com/43701418/74460515-c3b35b00-4e6b-11ea-9083-27c486098837.png)

I think it would be better because then you could put the same properties, methods, etc in different nodes.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Oh, I think it would be used a lot. I don't actually know if I could do it myself (because I'm kind of a newbie). 
I think this is something that could be built-in.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because everybody would use it. In the way it is, I'm doing all by hand, but if I could change just that, it would save a lot of time. Maybe even with instancing later, I don't know.

**Comment by Calinou** [comment]
See also #444.

**Comment by Calinou** [comment]
Upon reading this proposal again, it seems this is one is a d
uplicate of https://github.com/godotengine/godot-proposals/issues/444.

**Comment by ThomasGysemans** [comment]
Is it possible now?

**Comment by Calinou** [comment]
@ThomasGysemans Please don't ask the same question on several proposals, especially if the proposal in question is closed.
