### ISSUE TITLE
Make GDScript easier to read

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot-proposals#4690]
### Describe the project you are working on

Checking out GDScript 2.0

### Describe the problem or limitation you are having in your project

I noticed in some expressions, readability suffered in GDScript 2.0 compared to Godot 3.x

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Assuming that *code is easier to read, the closer it is to the english language*, let's try to get a bit closer to english and avoid visual noise.

### **is not** - operator

    if not object.get_item() is String:
    
    if object.get_item() is not String:

The second line is easier to read, for one part because it is closer to english. But also, in the first line, *not* and *is* build a large gap which renders the expression harder to read.

### **not in** - operator

    if not object.get_item() in list:

    if object.get_item() not in list:

Same reasoning as before, the expression is closer to english and we removed the awful gap between *not* and *in*.

### truthy expressions:
```
if object!=null:
if object:

if list!=null and not list.is_empty()
if list:

if a!=0:
if a:
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This proposal is about improving readability of GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

It changes GDScript

I'd like to use this ticket to collect expressions that would simplify and improve readability. If you got something in your mind, please leave a comment.

### other proposals
* enum block syntax #4278

**Comment by Mickeon** [comment]
Doesn't GDScript already have a loose concept of truthy `if` expressions? Could this be elaborated further or made into its own proposal? Since, `is not` and `not in` seem to be what the core of this proposal is about.

**Comment by mrimvo** [comment]
Last time I checked, GDScript 2.0 was incapable of truthy expressions, which (being used to them) I missed quite a bit. Can't check now, but if truthy expressions are part of GDScript now, I'd remove them from this proposal.

**Comment by Calinou** [comment]
I've seen a pull request implementing either `is not` or `not in`, but I can't find it right now.

**Comment by me2beats** [comment]
if count
if object
if array
this is what already possible in Godot (3 at least)

**Comment by mrimvo** [comment]
I agree, one ticket per issue. I'm happy part of this ticket is tracked elsewhere already.

Last time I checked, GDScript 2.0 in Godot 4.x did not support truthy expressions, which I really missed.

To me (my personal perception) truthy expressions are easier to write and also easier to read, because to me `if object!=null` requires more effort to read and check the single characters than reading two noon technical English words `if object`. I love this very intuitive feel. In my mind, I understand it like "if object (is something useful)" or "if list (has something useful)".

**Comment by YuriSizov** [comment]
Please use the [Discussions](https://github.com/godotengine/godot-proposals/discussions) section for general suggestions and discourse. Open proposals only if you have an idea about how to implement it. (And, like mentioned above, one feature per proposal).

**Comment by mrimvo** [comment]
Cutting off the discussion like this feels quite discouraging to be honest.

**Comment by YuriSizov** [comment]
> Cutting off the discussion like this feels quite discouraging to be honest.

The issues are not a place for a free form discussion. They are a place to track actionable tasks so we can organize our work and approve a specific implementation. I've redirected you to the place where you can have a free form discussion, a place where you should've opened your thread to begin with.

Make sure to read the proposal submitting guidelines in the repository's readme document. This is not personal and has nothing to do with you, just maintenance of our task tracker.

**Comment by KoBeWi** [comment]
Truthy expressions are still supported, but not all of them and they don't work with logical operators. GDScript 2.0 is more strict with types, so to resolve this fully we'd need to explicitly define logical operators between each pair of variant types. I actually attempted that once, but couldn't get the code to compile due to the source file being too big xd

Anyway, this is tracked here https://github.com/godotengine/godot/issues/44688
