### ISSUE TITLE
Rename `Object.get_indexed()` to `Object.get_by_path()`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#4727]
### Describe the project you are working on

Games

### Describe the problem or limitation you are having in your project

`Object.get_indexed()` doesn't sound intuitive

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename `Object.get_indexed()` to `Object.get_by_path()`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`Object.get_by_path()`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

not related

### Is there a reason why this should be core and not an add-on in the asset library?

not related

**Comment by gregcsokas** [comment]
I assume, there is a set_indexed method too, and for consistency, it has to be renamed to set_by_path() maybe.

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting and don't agree about the `get_by_path` proposal, it doesn't make the name more intuitive but actually more confusing. `get_indexed` is a fairly advanced method which is only relevant for use cases such as animation blending to index property paths like `position:x`.

We didn't find a better name, @reduz proposed `get_node_with_subpath_and_index` but that doesn't sound great and it will show up in completion whenever using `get_node`.

**Comment by aaronfranke** [comment]
Closing due to the lack of consensus on a clear path forward.
