### ISSUE TITLE
Add `position_changed` signal for Node2D and Node3D

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#4729]
### Describe the project you are working on

NO-GAME App

### Describe the problem or limitation you are having in your project

I want listen some node's position but I don't want add script for this nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add `position_changed` or `transform_changed` signal for Node2D and Node3D

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I must add script for all this nodes. I'm lazy.

### Is there a reason why this should be core and not an add-on in the asset library?

No, It's core.

**Comment by Calinou** [comment]
> I must add script for all this nodes. I'm lazy.

This is not a sufficient reason for a feature to be added to core.

**Comment by CsloudX** [comment]
> > I must add script for all this nodes. I'm lazy.
> 
> This is not a sufficient reason for a feature to be added to core.

^V^, I think `position_changed` was used often, IMO, add the signal make GODOT better.

**Comment by KoBeWi** [comment]
We have `NOTIFICATION_TRANSFORM_CHANGED`, which needs to be explicitly enabled with `set_notify_transform()`. Maaybe the signal could be emitted together with that notification.

It's not very common though, not sure why would you need it as frequently as you claim.

**Comment by smix8** [comment]
Transform changed is already disabled by default because it wreaks havoc on performance if enabled on to many nodes but it costs nearly nothing and is very fast compared to signals. Sending by default a signal for every slightest transform change is the next best thing for crashing the Engine with the MessageQueue.

**Comment by Mickeon** [comment]
What's the use-case? What's the **actual** necessity to implement this natively without using a script (the latter of which is very much possible to accomplish)?

**Comment by YuriSizov** [comment]
> I want listen some node's position but I don't want add script for this nodes.

As Calinou stated, this is not a valid justification for a proposal. And as mentioned by others, performance ramifications is something that must be investigated before discussing this feature. So closing as not a valid proposal. Please use the Discussions section or our social and community platforms to look for a solution that works for you. Then a proper proposal may be born, if there is a good legitimate need for an improvement.

**Comment by Nodragem** [comment]
Here is a use case:

<img width="771" height="604" alt="Image" src="https://github.com/user-attachments/assets/2a55dd45-6997-47c4-9867-3d80571d2189" />

I have a switch hub, and the switch hub gizmo needs to draw an arrow from the input objects to the switch hub, and from the switch hub to the output objects.

This means that the gizmo needs to update whenever I move an input objects or output objects of the switchhub.

I don't see why a signal that has no listener by default would have a detrimental effect on performance?

**Comment by Mickeon** [comment]
> I don't see why a signal that has no listener by default would have a detrimental effect on performance?

There's a possibility you wanted to comment this onto https://github.com/godotengine/godot-proposals/issues/9027 .
Still, this is all already possible in the engine. You can listen to `NOTIFICATION_TRANSFORM_CHANGED` or similar, emitting your own custom `transform_changed` signal.

**Comment by Nodragem** [comment]
I am aware of `NOTIFICATION_TRANSFORM_CHANGED` but it does not allow you to track the movement of other objects. 

In this use case, the switch hub could be connected to any sort of objects, which have their own scripts and could be inheriting from any descendants of Node3D. Hence it is impossible to attach a custom script to them.

Maybe traits could be a way of solving it, but really, one would expect that we can track movements of another object with signals.

Thank you for pointing me to 9027, I will have a look now.
