### ISSUE TITLE
Add a way to copy a property description text

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#4746]
### Describe the project you are working on

A game

### Describe the problem or limitation you are having in your project

I want to copy this but I can't

![изображение](https://user-images.githubusercontent.com/16458555/175774499-2d43c40e-0236-48ec-b929-10666be7a5b7.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement such tooltips as Controls with text that can be selected and copied.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When a tooltip shown, you can hover the mouse on it, then select some text then copy with Ctrl+C.

Or there can be a button to copy all the description text, this can be not so handy tho if you want to copy just a small piece of the description and paste it in the script

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it's possible to search it in built-in Docs, but this not so handy

### Is there a reason why this should be core and not an add-on in the asset library?

This can be used often I think.

**Comment by KoBeWi** [comment]
> I want to copy this

why tho?

**Comment by me2beats** [comment]
> why tho?

for example to paste the line to ScriptEditor

**Comment by Mickeon** [comment]
I think being able to go from Inspector property to Documentation of the selected property would solve this proposal as well as being generally more useful

**Comment by me2beats** [comment]
I'm for both options)
sometimes you just want to copy some text without a need to go anywhere

**Comment by fire-forge** [comment]
The text in the tooltip is the same as the description in the documentation page, which you can copy and paste from. I actually have a PR open that adds a button to the property context menu to open the property's documentation: https://github.com/godotengine/godot/pull/59680. It's just been sitting for 3 months though, but I'll give it a rebase soon. So if that's merged, then it will be super easy to get to the documentation page quickly to copy and paste from there and then this might not be needed anymore?

**Comment by fire-forge** [comment]
https://github.com/godotengine/godot/pull/59680 has been merged, so when you want to copy a property's description you can right-click, press "Open Documentation", and copy the description from the documentation page. Is that good enough to close this proposal?

**Comment by me2beats** [comment]
Closed in favor of https://github.com/godotengine/godot/pull/59680
