### ISSUE TITLE
Implement pressing Escape to clear text selection in LineEdit and TextEdit

### ISSUE THREAD

**Issue by ZachIsAGardner** [godotengine/godot-proposals#4766]
### Describe the project you are working on

Just messing around in Godot 3.X and 4.0 alpha.

### Describe the problem or limitation you are having in your project

I'm used to being able to press Escape to clear my current selection in a code editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having a configurable shortcut for clearing the current selection would be helpful.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is something that could be added as it's own shortcut in the Script Text Editor category. Or it could be hooked into the existing ui_cancel shortcut. This would be similar to Evaluate Selection, it just wouldn't move the cursor around.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure.

### Is there a reason why this should be core and not an add-on in the asset library?

I think most people would appreciate this.

**Comment by Calinou** [comment]
This needs to be implemented in LineEdit and TextEdit in general. The script editor (which uses CodeEdit under the hood) will automatically benefit from this as a result.

**Comment by kitbdev** [comment]
- In TextEdit, implemented as `ui_text_clear_carets_and_selection` in https://github.com/godotengine/godot/pull/68170 
- In LineEdit, pressing Escape (`ui_cancel`) unfocuses it which deselects text in https://github.com/godotengine/godot/pull/81128

**Comment by Calinou** [comment]
Closing, as this proposal is implemented since 4.2 as per the above comment. I've tested it in the script editor and it works too.
