### ISSUE TITLE
(4.0a) Quick Open should focus 2D or 3D tab when selecting a .tscn file

### ISSUE THREAD

**Issue by ZachIsAGardner** [godotengine/godot-proposals#4767]
### Describe the project you are working on

Just messing around with 4.0 alpha.

### Describe the problem or limitation you are having in your project

When using the Quick Open popup to select a .tscn file while away from 2D and 3D tabs the appropriate 2D or 3D tab isn't selected.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Auto focusing 2D or 3D depending on the root node would fix the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

After selecting a .tscn file using the Quick Open popup, the appropriate 2D or 3D tab should be selected.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure.

### Is there a reason why this should be core and not an add-on in the asset library?

I think most people would appreciate this.

**Comment by KoBeWi** [comment]
Well, it does switch correctly when you are in the editor. While inside script editor, some people would prefer to stay there and changing to 2D/3D would break their workflow.

**Comment by ZachIsAGardner** [comment]
> Well, it does switch correctly when you are in the editor. While inside script editor, some people would prefer to stay there and changing to 2D/3D would break their workflow.

ah gotcha, i initially expected it to work the other way around. but i understand.
