### ISSUE TITLE
AnimationTree support AnimatedSprite 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot-proposals#4768]
### Describe the project you are working on

A 2d TowerDefense game 

### Describe the problem or limitation you are having in your project

AnimatedSprite is an easy way for frame based animation，however animation tree only supports animation player.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make it easier for animation transitions in AnimatedSprite 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

AnimationTree can select an AnimatedSprite.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Lots of if else script code 

### Is there a reason why this should be core and not an add-on in the asset library?

It’s not possible

**Comment by Calinou** [comment]
In the interest of usability, AnimatedSprite is intended to be suited for simple use cases only. For complex cases, use a Sprite + AnimationPlayer or Sprite + AnimationTree setup.
