### ISSUE TITLE
A character/enemy/object editor inspired by Pixel game maker.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#4780]
### Describe the project you are working on

2D games.

### Describe the problem or limitation you are having in your project

It takes at least multiple hours to properly develop the node setup that will allow for a basic 2D character, be it the player or the enemies or something as basic as ingame items like chest, or loot dropped ingame.

Even by reusing your code, It takes hours of playtesting to properly setup ingame characters and enemies to do what you want the to make.

It's not an issue of me not being able to make them, It's a core issue of wasted effort and time I waste on every new project, when a simpler interface wizard would allow me to easily set up in a few minutes my sprites and just tweak a few settings and have a working character or enemy or object in the game.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Just try to copy the character and object editor of Pixel game maker.
It's such a solid editor that is begginer friendly, but can pretty much cover most major 2D genres, to generate easily and quickly characters, enemies, items and objects.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Pixel Game maker has a visual flowchart FSM machine where you can easily plug the conditions that makes the object to switch to another state, like certain input, no input being detected or conditions such as Is a platfomer jump or has collided with walls or player/enemy groups.
And there's an easy to use animation editor where you simply add the sprites, set up the collision, hitbox and attackbox collision layers and just pick one of the 8 directions the sub animation will play.
There's also a big major animation menu, and some sub animation list where each individual angle of said animation can be easily made and a third list with every frame this sub animation angle has.
The FSM will simply connect each state to one of the animations and the correct angle animation will eventually play.
Also, each state can contains a list of commands like move or check for a collision that will trigger changes to the game, or basic configuration options, like not jumping, or not reacting to gravity or moving input.

To have a clear picture, is better to check pixel game maker demo to understand how it works.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this is a core new editor for godot.

### Is there a reason why this should be core and not an add-on in the asset library?

Every game needs objects like characters or enemies or items.
This will basically be a feature used by every project, specially beneficial to begginers who can easily now create a few characters and make it walk around the screen, in a few minutes, no coding skill needed.
Also, it will be a HUGE productivity improvement to godot workflow, in terms of hours of work saved in every project.

**Comment by Zireael07** [comment]
There are a lot of graphical FSM (or more) editor addons in Godot.

**Comment by YuriSizov** [comment]
Like mentioned above, FSM is already covered by third-party addons and plugins. Godot development has a policy not to bloat core with features that can be reasonably outsourced by third-party tools. So in this case, this already happened.

What you describe is also related to visual scripting, which Godot has but we have no capacity to maintain at the moment and will likely deprecate in Godot 4.0 until we can find knowledgeable contributors in the area. In other words, there are no current plans or capacity to consider new visual programming tools for the core.

Overall, a proposal for a new major editor tool must come with a bit more research than "Just copy this other tool", sorry.

**Comment by YuriSizov** [comment]
You also already made this proposal 2 years ago?

https://github.com/godotengine/godot-proposals/issues/405

**Comment by ca3games** [comment]
> You also already made this proposal 2 years ago?
> 
> #405

Yes, I suppose I'm not aware of a FSM addon for godot, is a core issue I have right now.

**Comment by Zireael07** [comment]
@ca3games: This is one I'm aware of https://github.com/kubecz3k/FiniteStateMachine that uses tree structure. There is at least one other that uses just a tree of Nodes
