### ISSUE TITLE
Make export nodes work with custom node types

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#4785]
Export node types: https://github.com/godotengine/godot-proposals/issues/1048
Export custom resources (similar): https://github.com/godotengine/godot-proposals/issues/18

### Describe the project you are working on

RTS with a lot of export nodes to link properties (e.g. the owner of an entity is a player node).

### Describe the problem or limitation you are having in your project

I can't limit the class of an export node to my custom class.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allowing users to export custom node classes reduces the chance of mistakes when a specific node is expected in a variable. Also helps a ton with auto-completion.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For example, in my entity class, I can have

`@export var player: Player`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Will be used often. Can only be worked around with an additional variable.

### Is there a reason why this should be core and not an add-on in the asset library?

GDScript is core

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/67055.
