### ISSUE TITLE
Remember directory folding state across restarts in the FileSystem dock

### ISSUE THREAD

**Issue by deanrih** [godotengine/godot-proposals#4789]
### Describe the project you are working on

A 2D side-scrolled turn-based game.

### Describe the problem or limitation you are having in your project

Every time I open Godot Editor, I have to open the folder to where the last time I use/opened it from the last session, this is really tedious and annoying if you have a lot of folders or a lot of nested folders (mainly in terms of depth)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the Godot Editor retain or remember the status of all folders in the FileSystem from the previous session, whether the folder is opened or not from the previous and then apply it when you begin a new session or resume your work the next day.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is the simplest sample of what FileSystem might look like when being worked on:
![image](https://user-images.githubusercontent.com/16235605/176843649-689220e7-c252-4aa2-9acb-38d67b54c053.png)

This is what FileSystem looked like whenever the Godot was opened, not remembering the state of the previous session:
![image](https://user-images.githubusercontent.com/16235605/176843876-8ea0a9a6-f7c1-4d0c-bc92-69ce2116cdaa.png)

The fix should make the editor open the FileSystem like this whenever a project is resumed:
Note that the picture below is the exact same picture as above, but what is important here is the Godot Editor remembers the state of the folders whether it is opened or not, retaining/remembering the selection state is not important and can be ignored.
![image](https://user-images.githubusercontent.com/16235605/176843649-689220e7-c252-4aa2-9acb-38d67b54c053.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As I'm not familiar with Editor scripting I'm not sure, but my guess is not, especially if you need to write those "few lines of script" into the main editor source code for this to happen.

### Is there a reason why this should be core and not an add-on in the asset library?

This is an essential quality of life niceness that other editors do have, and it is quite annoying as you regularly need to open a folder to open some scene or script to edit them.

Unless I'm stupid and blind, I can't seem to find the settings for the editor to make this happen if there's one, if Godot actually has this feature already, feel free to close this issue and please guide me on how to enable this, and if it indeed exists and an opt-in feature, please consider making it the default behaviour, if it's already the default and it works as intended for other, I... don't know, maybe I need to re-install my Godot installation.

**Comment by Calinou** [comment]
> Unless I'm stupid and blind, I can't seem to find the settings for the editor to make this happen if there's one

This isn't implemented yet, so there is no setting for it.

**Comment by deanrih** [comment]
> > Unless I'm stupid and blind, I can't seem to find the settings for the editor to make this happen if there's one
> 
> This isn't implemented yet, so there is no setting for it.

Ah I see, quite surprising that it hasn't been implemented yet, but I guess this is what the proposals are for.
