### ISSUE TITLE
Make Connections to method window expand to fit the text

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#479]
**Describe the project you are working on:**

2d card based tower defence

**Describe the problem or limitation you are having in your project:**

New 3.2 Connections to method button is great addition to the engine and I enjoy it a lot but it has one small limitation that it doesn't dynamically scale to a text inside the window reducing it usability.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Window size should scale to show whole text of the methods source and target rather than cut it the way it does at the moment. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This just bigger. 

![1](https://user-images.githubusercontent.com/30668026/74588377-f8eab500-4ff3-11ea-8563-66bf522adb7b.PNG)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

you can hover over the text but this is unnecessary wast of time. 

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is improvement on existing feature

**Comment by Zireael07** [comment]
I believe this is a bug - the text shouldn't be cut off, not a proposal?

**Comment by Feniks-Gaming** [comment]
should I issue bug report on main repo?

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/36245, as this is actually a bug.
