### ISSUE TITLE
Move recursive folding functionality from the Scene Tree dock to the Tree node, so that it can also be used in projects

### ISSUE THREAD

**Issue by AThousandShips** [godotengine/godot-proposals#4791]
### Describe the project you are working on

A PR involving large trees

### Describe the problem or limitation you are having in your project

Folding items in large nested trees can become highly cumbersome and impractical

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add recursive folding of tree nodes, folding children and grandchildren, etc.

Additionally allow folding of children of an item (both recursively and not)

This would make getting an overview of the tree easier by collapsing all the children of the node, or the node itself, when unfolded it would then be easier to get an overview once again.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Folding and unfolding would be handled directly by TreeItem, through new function(s), a small mockup I made appears to work well. I believe I would be able to implement this feature.

For input I would suggest the following:
- Right click on the fold icon collapses/uncollapses recursively
- Shift left click on the fold icon collapses/uncollapses the children of the item (based on the collapsed status of the first visible child, collapsing if uncollapsed and vice versa) but leaving the item itself uncollapsed, if the item was collapsed it uncollapses and uncollapses all its children.
- Shift right click does the same but recursively

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The direct behavior of recursive folding is straight forward to do in script with `call_recursive`, I would like to see this as a feature in the editor in general.

### Is there a reason why this should be core and not an add-on in the asset library?

I believe this would be a quality of life improvement for the editor.

**Comment by AThousandShips** [comment]
Both, but I encountered the frustration in the editor, though I feel I could be benefitted by it in my own projects as well but I have not used the Tree much in those projects. In this case it was related to the Editor Help Search which I'm working on a PR for

**Comment by AThousandShips** [comment]
I don't see how doing this in script would be possible as there is no propagation of input for the fold arrow

**Comment by KoBeWi** [comment]
This seems to already exist though? Shifth+click on the fold icon collapses recursively. At least in scene tree dock.
![godot windows tools 64_g1XYh3G1k7](https://user-images.githubusercontent.com/2223172/176924681-0af5ce3e-ed1a-4dfd-841e-6612497320e0.gif)

**Comment by AThousandShips** [comment]
Oh I didn't realize it was a thing for Scene Tree dock, and there I saw how that was solved so now I see how to do it in script reasonably well, thank you!

**Comment by AThousandShips** [comment]
My apologizes I was far to focused on the Help Search where I was working, I still think it could be useful as a general feature of the tree node though

**Comment by AThousandShips** [comment]
I'm sorry I was far to focused on the Help Search where I was working
