### ISSUE TITLE
Add option to convert 3.x projects to 4.0 from Project Manager

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#4801]
### Describe the project you are working on

Godot etc

### Describe the problem or limitation you are having in your project

Godot 4.0 has lots of compatibility-breaking changes. If you open your old Godot 3 project in 4.0, it will be immediately rendered unusable in the old version and saving any scene will potentially cause data loss.

We already have some code here and there that tries to keep some compatibility with the old projects, but adding more such code (like https://github.com/godotengine/godot/issues/44820 suggests for example) is not worth it in the long run.

Instead we have an official built-in project converter that does really good job in upgrading the old scenes and code to make them more usable and prevent data loss from incompatible properties. It's great, because it's self-contained and doesn't require redundant code code all over the codebase. The only problem is that the converter can only run from CLI. Most non-advanced users might not be aware about the magnitude of changes; they will just randomly open their small project and possibly break it. We should make converting more convenient, so that anyone can easily run the converter if they are upgrading the project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot already detects when a Godot 3 project is opened in 4.0 - it will display a warning. My proposal is to point to the converter in that warning and offer an option to automatically convert the old project.

The converter option could also be a button in Project Manager's sidebar, although that's less useful when you don't have Godot 3 projects on the list.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The warning we have now already mention converting, but it doesn't use the converter - it just updates `project.godot` to a new format. We could either make it use the converter or add a button to run full project conversion:
![image](https://user-images.githubusercontent.com/2223172/177047123-fd83ced2-0fc2-4473-a915-f1fb7c8f4100.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You'd need a custom project manager.

### Is there a reason why this should be core and not an add-on in the asset library?

Must be core as it helps migrating projects.

**Comment by stebulba** [comment]
Can we add a option to clone the project and save the 3.x before to convert it ?

**Comment by Calinou** [comment]
> Can we add a option to clone the project and save the 3.x before to convert it ? If we import a 3.x file in godot 4 from the old 3.x directory, godot should clone it to the 4.0 setting directory before to convert it. That will probably avoid a lot of user mistake.

I think the converter should *always* make a copy of the old project (after checking for whether there's enough available disk space to make a copy).

If there isn't enough available disk space to make a copy, don't allow the user to convert projects.
