### ISSUE TITLE
Expose the sampling mode of textures in `Decal`

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#4809]
### Describe the project you are working on

prototyping with 4.0

### Describe the problem or limitation you are having in your project

Texture sampling (linear, nearest...) is not configured per-texture anymore but rather per user at the material or node level (for `Sprite` and others).
However this is not exposed in the new `Decal` node making it impossible to use non-linear-filtered decals.

The current way to circumvent this limitation to use a scaled up version of the small texture where filtering is less noticeable.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose a `texture_filter` property like in `Sprite3D`:

![2022-07-04_21-57-48 decal texture sampling](https://user-images.githubusercontent.com/71937306/177211497-f68c4fc9-e9b1-42ea-8d2a-b6c97aa45f0e.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

it can't

**Comment by Calinou** [comment]
Decal filter sampling mode is configured in the Project Settings (like projector textures):

![image](https://user-images.githubusercontent.com/180032/177212417-72896c74-b0b9-44d8-8eb6-9e714fdb7466.png)

The filter mode can't be adjusted on a per-node basis as a texture atlas is used for efficiency reasons.

The Nearest + Mipmaps + Anisotropic option is currently missing, but https://github.com/godotengine/godot/pull/51531 adds it.
