### ISSUE TITLE
Implement XMLParser.get_current_line()

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#4810]
### Describe the project you are working on

A documentation editor for Godot's documentation.

### Describe the problem or limitation you are having in your project

I'm making a documentation editor. It's parsing Godot's XML files, allows editing them and then save.

To support proper saving, I'm just storing file's lines in an array and then save them back to the file. My problem is that I want to save the edited file, not the original (bruh), so I need to know which line exactly was modified. The easiest way to do this is the `get_current_line()` method in XMLParser, but it's currently not implemented.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If I could use this method, it'd be easy for me to replace the relevant lines in the original file, so that saving edits is possible.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot/pull/62724

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really. XMLParser doesn't expose any way to know what it parses. It only gives you the final data.

### Is there a reason why this should be core and not an add-on in the asset library?

XMLParser is a core class and this method is already there, it just does nothing currently.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/62724.
