### ISSUE TITLE
Add support for horizontal scrolling in `Tree` using mouse buttons (`WHEEL_LEFT`/`WHEEL_RIGHT`)

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#4816]
### Describe the project you are working on

No relevant

### Describe the problem or limitation you are having in your project

The editor FileSystem and Scene tabs are usually not wide enough to display their whole content on my display and editor interface scale.
As such I often need to scroll horizontally to read e.g. a full file name which I can't do using the secondary mousewheel of my mouse at the moment.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make horizontal mousewheel event scroll horizontally in ScrollContainers.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I would use it often

### Is there a reason why this should be core and not an add-on in the asset library?

its kinda core already

**Comment by AThousandShips** [comment]
It should be, but the Editor Filesystem isn't a scroll container but a Tree, that does *not* have this as far as I can see

**Comment by YuriSizov** [comment]
Indeed, this is `Tree`, and `ScrollContainer` already supports WHEEL_LEFT/WHEEL_RIGHT.
