### ISSUE TITLE
Improve professional gamedev workflows

### ISSUE THREAD

**Issue by jasonswearingen** [godotengine/godot-proposals#482]
**Describe the project you are working on:**
as a skilled developer and former gamedev, spent last 2 months learning godot. (C#)

**Describe the problem or limitation you are having in your project:**
These are the two systemic (biggest) problems I have run into, both revolve around performance:
Lacking tools to measure/create high performance code:
- no ability to profile code in C# (thus  godot is a black box).  
- unknown how to create high performance workflows (eg: for collisions).

Probably professional gamedevs would have realized these issues as a roadblock to adoption immediately.  It took me a couple months to realize because I've been out of gamedev for so long (13 years) but now it seems rather silly that I"m trying to create high performance C# code using Godot.  It's already great for simple games and prototyping, and maybe the GDScript workflows are better with perf analysis (never tried gdscript).  But if I want to do something like create a spatial partition, I need to debug+test it outside of godot.  

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
- If these features are planned, a more visible roadmap so there is some comfort as to them being available at some time in the future.
- If they are not planned:  Please do so.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
N/A

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
N/A

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by jasonswearingen** [comment]
@Calinou if this is in regard to my proposal putting ```N/A``` for code, that's the problem I'm trying to describe.  There (seems to be) no way to do these things.   I'll try to elaborate more:

- Profiling:   The suggested OSS profiling method does not work:   https://docs.godotengine.org/en/3.2/getting_started/scripting/c_sharp/c_sharp_basics.html#profiling-your-c-code
  - The mono log profiler does not work:    https://github.com/godotengine/godot/issues/29005
  - Maybe the jetbrains profiler works?  I didn't try as it's a USD$300 cost.  maybe I should.
  - VS2019's (free) profiler doesn't work:  I actually did spend the time to get the VS2019 debugger working with Godot (I added the docs entry on it) but VS doesn't support debugging mono.  I can dream of workarounds for that but it's outside the scope of this topic....

- Collision objects:  There is no instruction in the docs on using the Physics server for 3d objects and I can not find any examples/tutorials on the subject.  

- Other perf stuff I didn't mention:  I spent the time to learn how to use MultiMeshInstance and it works great.   The reason I'm so "picky" about perf is that the very first introduction to Godot was this tutorial series:  https://www.youtube.com/watch?v=VeCrE-ge8xM  Which is a great introduction (it's GDScript but I successfully did everything in C#).  However it actually has pretty bad performance for being such a simple game.   The game loop spikes to 11ms every couple seconds.   I have a feeling it's the rendering (the tutorial uses the GridMap with all blocks using triplanar UV's).   but **The code causing the perf hit doesn't actually matter.  The problem is that I don't have any way of telling what's the cause**.   Again, maybe GDScript-only version of the engine is better, but via the mono build, the built-in perf tools show nothing about what nodes or servers are taking the time.   I have a feeling the 

If you **need** more specific code, I open source everything here:  https://github.com/jasonswearingen/godot-csharp-tech/  and my "example" is the "CSharp Tools Demo - Ball Run" project located under ```./demo-projects/ball-run```  but again, I don't think source code is important regarding this issue.



I actually am donating via Patreon because I want to see godot succeed, and I created this "proposal" because I can now see this as a serious issue for C# adoption.     


**And finally, I'm actually OK if you leave this proposal closed.**   I just wanted to give (hopefully) constructive feedback from a professional C# developer who spent literally 2 months working with Godot (more than 20hrs/week too)

**Comment by akien-mga** [comment]
The reason for closing this proposal is not because it doesn't refer to valid issues, but because there's nothing actionable for us and it's a broad and generic discussion about "professional gamedev workflows" (whatever that means) instead of something addressing specific shortcomings of the engine.

So to your specific points:

- Mono profiler: Mono integration in Godot is a work in progress, so for sure some things don't work. You can open specific bug reports on godotengine/godot (for things that should work and apparently don't, like the documented profilers) or feature proposals here for things which you want to see implemented (like support for the VS profiler). In either case, the issue should be about a specific profiling tool that you want supported, not "professional gamedev workflows".

- Collisions: It's unclear what you're asking, and thousands of users are making physics-based games in both 2D and 3D with Godot, so obviously it's possible to use it. That's again something that you are welcome to open a proposal about if you have something concrete that you tried and that you think should be improved. "High performance workflows" is not an actionable concept in this case.

- Bad performance in a thirdparty video tutorial: That's *definitely* not actionable...

**Comment by WizzardMaker** [comment]
Debugging with Visual Studio is actually supported with an extension, I linked the guide from the wiki for reference
I don't know about profiling with it though

https://docs.godotengine.org/en/3.2/getting_started/scripting/c_sharp/c_sharp_basics.html#configuring-vs-2019-for-debugging

Rider for example has working profiling and debugging (you can try the trial edition) for every platform (you need to compile windows yourself though for working profiling)

**Comment by van800** [comment]
Personal license for Rider with profilers is around 180$, not 300. And It has a free trial. Each EAP build provides a new trial period.

**Comment by jasonswearingen** [comment]
> Debugging with Visual Studio is actually supported 

yes you can debug with VS2019.  Though the VS Profiler does not work with Mono unfortunately.

> Bad performance in a thirdparty video tutorial: That's definitely not actionable

The bad performance is in the demo project I coded based on the tutorial.  source code here: https://github.com/jasonswearingen/godot-csharp-tech/tree/master/demo-projects/ball-run  The bad performance is actually only visible based on the Performance Diagnostics I wrote (MonoDiagLabel) which is also in the same repository.     If you run the demo it looks like perf is great (above 100fps) but with my perf diagnostic tool you will see that aprox 1% of the frames are taking more than 11ms.    This spike is not attributable to the Mono GC.  I did a 10,000 multimesh demo (in same repo) from scratch and that didn't suffer the perf spike, so it's something in how that "ball run" project is coded.   And I have no way to track it down unless I resort to disabling systems /code section by section.       **So my whole rant really comes down to not being able to determine the cause of the spike**, and associated, suggested best practices for creating high performance simulations.

> Rider for example has working profiling and debugging (you can try the trial edition) for every platform (you need to compile windows yourself though for working profiling) 

> Personal license for Rider with profilers is around 180$, not 300. And It has a free trial. Each EAP build provides a new trial period.

Thank you for the suggestion.  I'm feeling rather burnt out right now but next time I play with Godot I will give it a try.
