### ISSUE TITLE
Enable FXAA by default for better visuals out of the box

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#4832]
- *Related to https://github.com/godotengine/godot-proposals/issues/348.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

A common complaint about out-of-the-box visuals in Godot's 3D renderer is the lack of any form of antialiasing. This, combined with the [lack of anisotropic filtering by default](https://github.com/godotengine/godot-proposals/issues/3134), gives the renderer an amateurish image until you tweak it to give better results.

This issue creeps up even in [official development blog articles](https://godotengine.org/article/fog-volumes-arrive-in-godot-4), which shows that it's something that should be resolved somehow :wink: 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

**Note:** This change only affects 3D projects, not 2D, as FXAA only operates on 3D rendering.

Enable FXAA by default. This will lead to higher-quality visuals out of the box, which will also be visible on screenshots and videos taken by Godot users.

This proposal suggests enabling FXAA on both desktop and mobile, but we can also choose to enable it only on desktop platforms using [feature tags](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html).

While this change targets Godot 4.0, this change can also be backported to *new projects* in Godot 3.x by changing the generated `project.godot` file's contents. This only occurs when the project manager is used to create a new projects, so existing projects wouldn't be affected by this change.

FXAA has many attractive traits for use as a default antialiasing mode in Godot:

- FXAA has a very low cost on the GPU compared to other antialiasing solutions. For games with complex 3D visuals, it's generally the only AA solution that is viable on mobile and integrated graphics. When targeting 1440p or 4K, FXAA may be all you need, especially on higher DPI displays.
- FXAA smooths out the edges of alpha-tested materials, which are often used in foliage.
- FXAA helps hide dithering patterns, such as the one visible in shadow rendering. Taken from the screenshots below:

No FXAA | With FXAA
-|-
![image](https://user-images.githubusercontent.com/180032/177866276-21d7396c-653e-4c2b-8207-58ff25a4ac15.png) | ![image](https://user-images.githubusercontent.com/180032/177866229-f4dde383-41f3-47f1-ba19-9d7a8f896b07.png)

The main downside of FXAA is the blurriness it adds, which is especially noticeable at lower resolutions. This can be alleviated in several ways, such as https://github.com/godotengine/godot-proposals/issues/4657 or https://github.com/godotengine/godot-proposals/issues/1519. If we end up accepting either of those proposals, the former could help reduce the added blurriness out of the box (while sharpening is something that should be enabled by the user manually).

___

***Question:** Why not enable multisample antialiasing (MSAA) instead?*

MSAA is a good solution for edge antialiasing, but it has several downsides:

- MSAA is very expensive on the GPU in modern renderers, especially at higher resolutions. We could only realistically consider using 2× MSAA, which isn't that good on its own. (2× MSAA is pretty alright if you use FXAA or TAA *on top*, but it becomes even more demanding.)
- MSAA doesn't affect alpha-tested surfaces and doesn't reduce specular aliasing in any way. While FXAA doesn't resolve specular aliasing, it does alleviate specular aliasing a little in some scenarios.
- MSAA doesn't reduce the shadow dithering pattern's visibility like FXAA or TAA can do.

___

***Question:** Why not enable temporal antialiasing (TAA) instead?*

TAA is a good solution in some cases, but has several caveats:

- Due to its temporal nature, TAA leaves visible disocclusion and ghosting artifacts which can be distracting. This happens even if proper motion vectors are generated. People may think that these are engine bugs (and some will file issues as a result[^1]), while these are actually limitations of any TAA solution in any engine.
- Not everything in Godot will generate proper motion vectors for TAA yet (such as UV scrolling, skeletons, soft bodies, etc). This results in visible ghosting trails when one of those objects moves.
- TAA is more demanding than FXAA, even if https://github.com/godotengine/godot/issues/61905 is resolved.

[^1]: We regularly get issues opened about ghosting trails left behind moving sprites in 2D, while it's actually due to an hardware issue (monitor ghosting/slow display response times).

___

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have a branch implementing this change: https://github.com/Calinou/godot/tree/viewport-default-fxaa

Here are some comparison screenshots in scenes with the default environment settings:

### 1152×648

*[New proposed default window size.](https://github.com/godotengine/godot/pull/55032)*

### Basic scene, VoxelGI

No FXAA | With FXAA
-|-
![2022-07-07_22 04 08](https://user-images.githubusercontent.com/180032/177864220-68308daf-8678-43c3-b86c-2c121c8c3700.png) | ![2022-07-07_22 04 25](https://user-images.githubusercontent.com/180032/177864221-41f1d378-0268-4c65-80b9-cabb14ef4846.png)

### Textured Octavus, SDFGI

No FXAA | With FXAA
-|-
![2022-07-07_22 06 03](https://user-images.githubusercontent.com/180032/177864206-7fed1b97-cc0d-40b8-99f5-f9c5d1a6311f.png) | ![2022-07-07_22 06 15](https://user-images.githubusercontent.com/180032/177864208-992790a4-33ca-4165-8428-c60e56f9b83a.png)

### 1920×1080

*Typical fullscreen resolution.*

### Basic scene, VoxelGI

No FXAA | With FXAA
-|-
![2022-07-07_22 06 36](https://user-images.githubusercontent.com/180032/177864191-ffc04017-aeea-4a1f-96fb-2ddd23af52dd.png) | ![2022-07-07_22 06 49](https://user-images.githubusercontent.com/180032/177864195-c80dc2e7-437e-439d-bec4-005f881124d4.png)

### Textured Octavus, SDFGI

No FXAA | With FXAA
-|-
![2022-07-07_22 07 01](https://user-images.githubusercontent.com/180032/177864153-802c0e5e-3e34-41a8-baaa-67821b6353e2.png) | ![2022-07-07_22 07 12](https://user-images.githubusercontent.com/180032/177864159-bbaa9f87-98cd-447a-b0af-f4af94738774.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about changing a default setting to improve the out-of-the-box experience with Godot's 3D renderer.

**Comment by jcostello** [comment]
FXAA has some problem with lines. The AA looks weird and also as it well know, it blurs textures

**Comment by clayjohn** [comment]
I agree with jcostello, I don't think FXAA should be on by default. It can cause significant blurriness in textures and makes a mess out of lines.

**Comment by Calinou** [comment]
> I agree with jcostello, I don't think FXAA should be on by default. It can cause significant blurriness in textures and makes a mess out of lines.

Do you have any other solution in mind? I would prefer to have *some kind* of AA enabled by default in 3D, as screenshots/video screencasts will look bad by default otherwise.

[SMAA](https://github.com/godotengine/godot-proposals/issues/2779) does not blur the image nearly as much as FXAA, but it's not implemented in Godot yet. I'd have proposed that otherwise :slightly_smiling_face: 

If we find a way to reduce MSAA's cost, perhaps 2× MSAA will be fast enough on dedicated GPUs. We'd still need to add an `.integrated` feature tag or similar to automatically disable it on integrated graphics.

**Comment by Jamsers** [comment]
>What do other engines do here?

Unity has no antialiasing by default, Unreal defaults to TAA

MSAA 2x is the most "lossless" default option IMHO, but cost is too heavy.

I agree that if SMAA were implemented into Godot, it'd make for an excellent middle ground default.

**Comment by xxSeys1** [comment]
Maybe we could have a checkbox when creating a project called something like `2x MSAA` or `Anti-Aliasing` that is ticked by default with a warning that this may cause performance problems.

This could of course also be done with FXAA (+ a warning of maybe causing blurry textures/ lines etc) or TAA (+  a warning that this may cause noticeable ghosting).

**Comment by Calinou** [comment]
> Maybe we could have a checkbox when creating a project called something like `2x MSAA` or `Anti-Aliasing` that is ticked by default with a warning that this may cause performance problems.
> 
> This could of course also be done with FXAA (+ a warning of maybe causing blurry textures/ lines etc) or TAA (+ a warning that this may cause noticeable ghosting).

Having project templates is planned at some point, but I don't think it should be as granular as providing antialiasing settings directly in the creation dialog. It could however automatically enable antialiasing if you choose a 3D template focused on high-end visuals (most likely TAA).

**Comment by thygrrr** [comment]
Absolutely against. FXAA is poor quality and incompatible with a variety of rendering techniques.

I would suggest MSAA 4x as the default instead

**Comment by Jamsers** [comment]
I agree that FXAA as a default in the year of our lord 2023 is terrible, not to mention Godot's FXAA implementation is quite low quality and has issues.

That being said, MSAA is still unfortunately a no go. MSAA is great and is about as "lossless" as it gets, but for lower end systems (think Intel iGPUs) even the lowest 2x setting is too heavy to enable by default.

If we can get [SMAA implemented](https://github.com/godotengine/godot-proposals/issues/2779) it could serve as a good default, or better yet [CMAA2](https://github.com/godotengine/godot-proposals/issues/2779#issuecomment-1752136968), which is even more "lossless" than SMAA and performs better, although at the cost of more aliasing.

**Comment by thygrrr** [comment]
AFAIK, MSAA 2x is considered "free" even on most mobile GPUs these days. On PC, it is generally considered that 4x still is a low impact measure. I'm rather sure it also applies to Iris graphics. I'll try to find a few test devices.

MSAA is not SSAA.

**Comment by Calinou** [comment]
> On PC, it is generally considered that 4x still is a low impact measure.

This isn't the case on integrated graphics due to memory bandwidth constraints.

**Comment by Jamsers** [comment]
>we're even starting to see mobile/Switch games starting to adopt TAA, despite these platforms not being ideal fits for it.

No Man's Sky's custom FSR 2 implementation on Switch is a revelation 😔🙏

Anyway yeah I am noticing more and more high end mobile games moving away from MSAA - Genshin Impact notoriously only has TAA on mobile, for example. I wonder if the old "MSAA is free on mobile" adage doesn't hold up anymore for games pushing the cutting edge of graphics on mobile?

**Comment by thygrrr** [comment]
> > On PC, it is generally considered that 4x still is a low impact measure.

> This isn't the case in modern renderers for 2 reasons:

I am indeed happy Godot doesn't use deferred shading, because I'd much rather use my (non-IGPU) Hardware's ability to anti-alias cleanly in properly subdivided fragments of depth, stencil, and framebuffer for practically free; than have cheaper point lights, more expensive directional lights, and much, much more expensive anti aliasing costs, with the added overheads of sampling depth normals, motion vectors, past framebuffers, etc. (or whatever modern TAA samples)
 
> In recent times, we're even starting to see mobile/Switch games starting to adopt TAA, despite these platforms not being ideal fits for it.

I'm not a huge fan of TAA; but I admit this is a personal preference. I consider its visual stability even in the best of the best AAA games (e.g. RDR2, Battlefield 1, Cyberpunk 2077) leaves much to be desired. I always run these with 8x MSAA, even if intra-texture and transparency antialiasing isn't always the best.

Thank you for explaining. I can accept that if you need to ensure support for integrated low-end graphics from a pre-2018 generation, then yes, MSAA by default is out of the question. 

FXAA is incompatible with many types of renderers as well, though.

**Comment by Jamsers** [comment]
>I consider its visual stability even in the best of the best AAA games (e.g. RDR2, Battlefield 1, Cyberpunk 2077) leaves much to be desired.

Funnily enough, the "best of the best AAA games" tend to also have some of the worst implementations of TAA in the industry: RDR2 is kinda famous for its utterly unsalvageable image quality at 1080p due to its horrendous TAA, and Cyberpunk has some of the smeariest TAA in the industry.

I too am glad Godot still provides options to make your game look good without having to rely on TAA. TAA is a nice tool to have in your arsenal but I hate it when it's the only tool and you're forced to use it.

**Comment by jams3223** [comment]
> > we're even starting to see mobile/Switch games starting to adopt TAA, despite these platforms not being ideal fits for it.
> 
> No Man's Sky's custom FSR 2 implementation on Switch is a revelation 😔🙏
> 
> Anyway yeah I am noticing more and more high end mobile games moving away from MSAA - Genshin Impact notoriously only has TAA on mobile, for example. I wonder if the old "MSAA is free on mobile" adage doesn't hold up anymore for games pushing the cutting edge of graphics on mobile? Although when I last worked in mobile a year ago MSAA was still the standard for the simple hypercasual games we were making on Unity.

Yes, I've analyzed their FSR 2 implementation, and I am baffled by how well they implemented it. I am praying for Godot to also improve upon it so it can look better than the other implementations.

**Comment by Calinou** [comment]
Closing, as we clearly need a project template system where you can choose between predefined settings. A blanket default option won't be able to address all use cases without significant downsides in some scenarios.

**Comment by felipefacundes** [comment]
Help me with the code please, Godot 4, MSAA simply doesn't give an error, but on the other hand it has no effect. This is a slide button:

```gdscript
func _on_msaa_value_changed(value):
	match value:
		0:
			RenderingServer.viewport_set_msaa_2d(Viewport, RenderingServer.VIEWPORT_MSAA_DISABLED)
		1:
			RenderingServer.viewport_set_msaa_2d(Viewport, RenderingServer.VIEWPORT_MSAA_2X)
		2:
			RenderingServer.viewport_set_msaa_2d(Viewport, RenderingServer.VIEWPORT_MSAA_4X)
		3:
			RenderingServer.viewport_set_msaa_2d(Viewport, RenderingServer.VIEWPORT_MSAA_8X)
		4:
			RenderingServer.viewport_set_msaa_2d(Viewport, RenderingServer.VIEWPORT_MSAA_MAX)
```

Checkbox for FXAA:

```gdscript
func _on_fxaa_toggled(toggled_on):
	if toggled_on:
		get_viewport().SCREEN_SPACE_AA_FXAA
	else:
		RenderingServer.VIEWPORT_SCREEN_SPACE_AA_FXAA
```

Please help me, I'm a beginner at Godot

**Comment by felipefacundes** [comment]
Thanks! I sent it on Discord!
