### ISSUE TITLE
Extend `Resource` ownership functionalities to `preload`s in GDScript

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#4840]
### Describe the project you are working on

not relevant

### Describe the problem or limitation you are having in your project

The FileSystem tree has a RMB option to `View Owners...` of a resource, that is other resources that reference this file.

- Scripts in which a resource is `preload`ed are not listed as such but they should be (since the resource existence is mandatory for the script not to fail).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1. Take scripts preloading resources in account in resource ownership deduction.
2. For consistency, make the modification of said resources possible via the `Edit dependencies...` dialog (that is change the referenced resource path in the script via this interface).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

can't be an addon

**Comment by Mickeon** [comment]
As is now, `preload()` isn't a "hard link" to a resource, even though it should probably be in some way or form, as an error is thrown if its resource can't be found at compile-time.

That would probably need to be addressed first, in some way or form, like, say for example, have Godot automatically update the path of `preload()` if the resource is moved in the File System and the path is a constant String.

**Comment by mieldepoche** [comment]
> As is now, preload() isn't quite a "hard link" to a resource, even though it should probably be in some way or form, as an error is thrown if its resource can't be found at compile-time.

Yes, at compile time.

When deleting an owned resource, the editor show a warning.
Having the path automatically update would be convenient but what happens when you remove the resource?

**Comment by KoBeWi** [comment]
I was pretty sure this is already supported 🤔

As for updating paths, in 4.0 you can use UIDs (e.g. `preload("uid://fdksgifdgnfdgfd")` and it will work no matter where you put the resource.

**Comment by mieldepoche** [comment]
> I was pretty sure this is already supported

Related proposal is #531

**Comment by YuriSizov** [comment]
> I just checked, the "View Owners..." part works in 3.x, so it's a 4.0 bug (report: [#62853](https://github.com/godotengine/godot/issues/62853)) The "Edit dependencies" dialog refuse to change the resource when it's listed from a preload.
> 
> Related proposal: #531

So is your proposal completely covered by another proposal and a bug report?

**Comment by mieldepoche** [comment]
> So is your proposal completely covered by another proposal and a bug report?

Almost entirely yes.
The `Edit dependencies...` feature not working is a bug so I'll open a report.
