### ISSUE TITLE
Increase resizing flexibility of Godot Engine Editor window(s) like in Visual Studio

### ISSUE THREAD

**Issue by Dante3085** [godotengine/godot-proposals#4845]
### Describe the project you are working on

Independant of any specific project.

### Describe the problem or limitation you are having in your project

When working with the engine editor and another window side-by-side I am frequently confronted with the editor's limitations in terms of resizing the sub-windows in the SplitContainers. See the following images/gifs:

In the following image the editor can not be any smaller:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26558776/178110734-ac6c95b2-5aff-4bdf-9f93-bc559f12e817.png">

Windows can also only be minimally resized like the following gif shows:
![resizing_editor_windows](https://user-images.githubusercontent.com/26558776/178110986-3fdcdebe-0612-4ce0-a786-fb7b28de5cb7.gif)

For context I am mostly working on a laptop screen ():

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like the editor to be as flexible in terms of resizing as Visual Studio is:
![visual_studio_editor_very_flexible](https://user-images.githubusercontent.com/26558776/178111733-6d3debd4-137a-41e8-b970-96e1fd41d09c.gif)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

/

### Is there a reason why this should be core and not an add-on in the asset library?

I think this should be core as it will improve the usability for everyone, no matter the specific project.

**Comment by Calinou** [comment]
The minimum dock sizes are usually set to prevent docks from being unusable at very small sizes. The bottom panel's height in particular is set relatively tall as this is the only way to consistently set a "default" height for the panel when it's first opened.

**Comment by Dante3085** [comment]
> The minimum dock sizes are usually set to 
> prevent docks from being unusable at very 
> small sizes
Why not let the user decide what they want to use at any given moment? I might not need a specific window sometimes, so I make it very small. But I might need another window that is completely hidden by distraction free mode. When I can't find a window that I made small previously I just reset all sizes to default by pushing a button in the settings.

> but there needs to be a way to easily show the 
> panels/docks by resizing them again in this 
> case.
You mean the SplitContainer's drag thingy will completely disappear?

**Comment by YuriSizov** [comment]
While we try to make Godot editor support relatively small screen sizes, this mostly means supporting valid resolutions of small form-factor laptops. We have a couple of issues where the editor cannot get any smaller because of the toolbars, but overall this is  a conscious choice, like Calinou mentions, to have a minimum size that is actually usable.

**Comment by Dante3085** [comment]
@YuriSizov Yeah, the last thing you said is definetly true. Had some problems like that myself in the past ;) I will try to get used to it then.

**Comment by Dante3085** [comment]
@YuriSizov @Calinou Sorry, quick question after already having closed the issue ;)
Is it maybe possible to expose some functionality that would allow people like me to make a plugin that has something similar to the functionality I described? That way, both get what they want.

**Comment by YuriSizov** [comment]
@Dante3085 It's not a matter of exposing some kind of functionality. The UI of the editor is made with container nodes. This means they are reactive to content and try to fit their children properly. Making things ignore sizes of children and overflow completely would likely require changing layouts of individual panels. You can certainly try doing it, but it won't be easy and may break at any moment.

**Comment by Dante3085** [comment]
Ok
