### ISSUE TITLE
Add filter and quick navigation options to the signal connection dialog

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#4848]
### Describe the project you are working on

Game with very big scenes.

### Describe the problem or limitation you are having in your project

There is this dialog:
![image](https://user-images.githubusercontent.com/2223172/178157548-e3971fb1-2e79-43eb-a34d-6593856f7703.png)

It allows you to pick a node, pick a method. It's a nice dialog. Until you have this:
![godot windows opt tools 64_ZG4hxpUqj4](https://user-images.githubusercontent.com/2223172/178157725-cf0ab458-e710-48a8-bec5-fbe715138820.gif)
Good luck finding your node here. Unlike every other dialog, this one doesn't have any way to filter nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The dialog should obviously have some filter bar that allows you to search for nodes, like in scene tree dock.

Another nice thing would be having a button that scrolls to the currently connected node. Or it could be done automatically when the dialog is opened. The node you want to connect to is most often close to the node being connected.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/2223172/178157855-358f7666-29d3-409d-b234-0284851f57c8.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It requires editor modifications.

### Is there a reason why this should be core and not an add-on in the asset library?

The usability of this dialog could be better.

**Comment by YuriSizov** [comment]
> Or it could be done automatically when the dialog is opened.

Well, the currently connected node is the one emitting the signal, so I'm not sure it would be universally useful, but a button, next to the filter input perhaps, does sound useful. Overall, I approve.

**Comment by KoBeWi** [comment]
> Well, the currently selected node is the one emitting the signal, so I'm not sure it would be universally useful

If you have small scene, you will most likely want to connect to root. In worst case you'd have to scroll up (root node is super-easy to find), but very often you won't even need to scroll.

In big scenes, you will likely want to connect to some node in the current node's vicinity. Like, you have some UI scene divided into smaller parts that you didn't save as separate scenes. The emitted signals will most often need to be received within the signal's area and it's somewhere in the middle of your node list. Finding it is much more difficult.

But having a jump button would be ok too.

**Comment by me2beats** [comment]
I think it just should by default select the node connected from, and jump to it.
I connect a node to itself really often
