### ISSUE TITLE
Is is possible to have [system menu bar] on Mac OS X? 

### ISSUE THREAD

**Issue by zzz6519003** [godotengine/godot-proposals#485]

**Comment by bruvzg** [comment]
It's already possible to use system menu from Godot (but support is limited):

```gdscript
func global_menu_action(id, meta):
	if id == 1:
		print("X1 pressed")
	elif id == 2:
		print("X2 pressed")
	elif id == 3:
		print("X3 pressed")

func _ready():
	OS.global_menu_add_item("My menu", "X1", 1, "")
	OS.global_menu_add_item("My menu", "X2", 2, "")
	OS.global_menu_add_separator("My menu")
	OS.global_menu_add_item("My menu", "X3", 3, "")

	get_tree().connect("global_menu_action", self, "global_menu_action")
```

![Screenshot 2020-02-16 at 10 30 44](https://user-images.githubusercontent.com/7645683/74601609-b505b780-50a8-11ea-8766-52e1658bf120.png)

**Comment by KoBeWi** [comment]
Yep, this is already possible. If you think that some functionality is missing or could be improved, feel free to fill the proposal with some actual content.
