### ISSUE TITLE
Split User Suggestions from Developers Proposals

### ISSUE THREAD

**Issue by doradoro** [godotengine/godot-proposals#486]
If you close this issue without my permission i will open another with your name in the title asking for your ban to the proposal system. OK? Great.

Let's use this script to filter proposals taking in count users suggestions and stopping "uncollaborative" behaviours so spreaded on here like "do it yourself and don't talk to me, closing issue" "fill this absurd papers before let my humongous ego read you" "go to other place to do another non related thing", "i did not read you but you are wrong because i'm the master of the muppets" and the most famous "i'm closing this because yes and you will not be able to reopen it because Yisus" = don't COllaborate, don't let people learn to collaborate, don't let people do things by themselves = stop collaboration.

Collaboration means that you and me work for the issue, not only me, not others, not closing it... but YOU and ME. If i'm wrong proof it, teach me, explain me, HELP me. Not close it like a nazi (put your preferred radical dictatorship here).

![Jerry](https://user-images.githubusercontent.com/495093/74604543-4ed85f00-50bf-11ea-949f-6db6454dcdd2.gif)

Solution, avoid unrelated suggestions and idiot newbie questions splitting them into two splitted systems. Newbie godot users in one side, developers and their egos in the other using a feature asking system: 

http://www.phpback.org/

or 

https://github.com/riggraz/astuto

Why? Because people like me should not be here being this impolite or touching the Godot code.

Example case:

- People Suggestion: Let's destroy Godot!
- Developers Proposal: Let's create an Uninstall button!

Thanks for your 30 seconds.

**Comment by akien-mga** [comment]
I haven't had time to review all the recent activity on proposals (also trying to have a personal life on my weekends), but this tone is definitely not welcome on this issue tracker, and no amount of frustration in the handling of proposals can excuse it. It's in clear breach of our [Code of Conduct](https://godotengine.org/code-of-conduct) and highly unconstructive behavior.

Given the additional threat, I am banning you from interaction with @godotengine repositories on GitHub.
