### ISSUE TITLE
Additional Name Casings

### ISSUE THREAD

**Issue by filipworksdev** [godotengine/godot-proposals#4865]
### Describe the project you are working on

Various games

### Describe the problem or limitation you are having in your project

While I tend to use `snake_case` a lot, I also find capital `SNAKE_CASE` useful as well as more recently I have been experimenting with `kebap-case` for files and node naming. I think adding more node/file/resource name cases could add more flexbility to the editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Current casings: `PascalCase`, `camelCase`, `snake_case`

I propose adding the following new casings:
- `UPPER_SNAKE_CASE`
- `kebap-case`
- `UPPER-KEBAP-CASE`

`UPPER` can also be `CAPITAL` or `SCREAMING` in the code but as you see in the screenshot below the user desn't see the UPPER naming as is used just for the code enums internally.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have this already implemented in my custom build to test it out.  PR for Godot 3.x is here https://github.com/goblinengine/goblin/commit/6c8d9bd6a53d645be8bfa82f34da8f68b30b1d33

![image](https://user-images.githubusercontent.com/99937119/178584359-9675856f-6603-483b-821d-c75ebda6e1d7.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

In script yes but not as a feature of the editor

### Is there a reason why this should be core and not an add-on in the asset library?

I think it provides more flexibility to the user.

**Comment by Calinou** [comment]
I wouldn't add support for more casings unless there's a lot of people that would actually use them.

**Comment by filipworksdev** [comment]
@Calinou  I will close this due to lack of support 😀 

However, I want to defend the use of `kebab-case` for Godot. First is not relevant if is popular or not in scripting since Engine case name propert is for naming resources, files and nodes and not variables. Second for organization purpose I find that using dashes in non script property names makes it instantly more recognizeable. Only a node, resource or file can have a dash so I know instantly where it comes from.  I find it very useful even though is not immediately apparent from the proposal above.  

```gdscript
my_node = $"my_node"
my_node = $"my-node" #only non script properties can have dashes so i instantly know where this is from
```

But UPPER cases are irrelevant and only added them for completeness 😁
