### ISSUE TITLE
Allow setting custom unit-hints for exported variables

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#4866]
### Describe the project you are working on

prototyping with godot 4.0

### Describe the problem or limitation you are having in your project

(discussion: https://github.com/godotengine/godot-proposals/discussions/4839)

In godot 4 some exports have units hints:
![image](https://user-images.githubusercontent.com/71937306/178089636-ffa8912b-c538-4ea1-a966-46f68a10ecca.png)

AFAIK it's not possible to specify your own unit hints for exports yet.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow using `@export("unit hint") var foo` to show a custom unit.
The unit would be shared among vector components if needed.

Examples:
```gdscript
@export("m/s") var speed := 10.0
@export_range(1, 60, 1, "", "s") var lifetime := 10.0
```

This solution is not perfect since it doesn't allow for prefixes `10000 m` -> `10 km` or special cases like `3600 s` -> `1 h` but I can't see how to expose such feature right now.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

can't

**Comment by YuriSizov** [comment]
> If this enhancement will not be used often, can it be worked around with a few lines of script?
> no

Everything that is done in the editor can be done with `_get_property_list`. And this could be done as an addon too, the one that recreates widgets with a customization option for the unit label.

-----

That said, while only some export options support suffixes, you can in fact already use them in your properties. Your hint must be `suffix:unit`, not just `unit`. Radians and degress have a dedicated hint that can be used instead — "radians", "degrees" — with the suffix hint overriding them.
