### ISSUE TITLE
Improve unary operator highlighting

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#4874]
Edit: Read my first comment.

### Describe the project you are working on

A game using GDScript.

### Describe the problem or limitation you are having in your project

There are two problems, but they are similar so I decided to make one proposal.

1. Operators do not change their color based on whether their context is as a unary or a binary operator. Or neither.

![image](https://user-images.githubusercontent.com/85438892/178993942-da34445b-b877-4317-8348-eaac4d3e4023.png)
Here, the `-` operator is light blue and the number is light greenish, although the operator should feel like part of the number.

![image](https://user-images.githubusercontent.com/85438892/178994301-be74daeb-ba15-41f3-93f8-5f8962887323.png)
Here, `%` colors the number as though it's a scene-unique node name, although it's actually a binary operator.

2. Unary operators obfuscate the stuff they are next to.

![image](https://user-images.githubusercontent.com/85438892/178994849-692320f7-d98d-4d46-a3c1-d41ce6f1b5f1.png)
This is a bit hard to read. Where does the operator end and where does the node name start?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When an operator like `-` or `+` is unary, give it the number color.
![image](https://user-images.githubusercontent.com/85438892/178993907-b6abb75e-c389-4adc-98eb-68dc283a7ab5.png)

When an operator like `%` is not unary, color it like a regular operator.

Dim unary operators when they aren't part of the true content like the minus sign.
![image](https://user-images.githubusercontent.com/85438892/178998292-70445fbb-20a5-458a-9a97-e7523abbfe60.png)

The unary highlighting would be rigid and unchangeable, but if the idea with the dimming is to be implemented, there should be an editor setting to adjust it. In the above illustration, the unary operator `$%` has a 60% opacity; I think somewhere between 60-70% looks the best. If an operator has highlighting specific to its context as unary or binary, when used alone, it should default to the binary highlighting.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You write code and the highlighter does its magic on the go. For example, if you write `%`, it will get binary highlighting (Symbol), then, if you change it to `%5`, it will get unary highlighting (NodePath), as well as dimming, and finally, if you then change it to `8%5` it will return to the binary highlighting (Symbol).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This enhancement would be used all the time by pretty much everyone.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving syntax highlighting out of the box.

**Comment by MewPurPur** [comment]
In hindsight, most of what's in the proposal is about decorators, only the minus/plus sign thing is about unary operators. I'm not going to edit this proposal, but I've opened PRs with the highlighting fixes, which is mostly like I described it here.

So... What do you guys think about the idea with the dimming? This one:

![image](https://user-images.githubusercontent.com/85438892/179371591-8599d32a-caf6-42a0-a512-a3d33e41f991.png)

It's likely the less popular of the two and it might also make sense outside of decorators. Here's what's on my mind:
- 0.67 transparency by default, a little higher than what's shown here.
- Dims the following: `$` and/or `%` in NodePath; `^` in ACTUAL NodePath; `&` in StringName; `@` in annotations
- Can be adjusted in Editor Settings, and is called "Decorator dimming"

**Comment by dalexeev** [comment]
> Here, `%` colors the number as though it's a scene-unique node name, although it's actually a binary operator.

It's a bug.

In general, I'm satisfied with the way operators are highlighted in the editor. We could add a separate operator color in the settings, but that would also require changes to the highliter code.

**Comment by MewPurPur** [comment]
@dalexeev
I fixed the bug and have a PR for it, also I did the unary - and + thingy. ![minusplus](https://user-images.githubusercontent.com/85438892/179393342-e1bc6c41-d3e0-424f-b6f8-a2ff8a4cee00.png)

What do you think of the idea with dimming?

**Comment by dalexeev** [comment]
Your screenshot shows different colors. But I like both options:

![](https://user-images.githubusercontent.com/47700418/179394858-51f7c056-18ba-4ab1-9dee-f4835db4b686.png)

**Comment by MewPurPur** [comment]
Yeah, the colors of numbers and operators are similar so I changed them to not make people squint.

Also experimented with the dimming, won't PR yet but this is how it looks right now.
![image](https://user-images.githubusercontent.com/85438892/179396761-374f3f2b-f78b-4e45-97b4-06d5bcfd524b.png)

**Comment by MewPurPur** [comment]
https://github.com/godotengine/godot/pull/62433

I know this screws with bitwise operators. I'll address it as well.

**Comment by mhilbrunner** [comment]
Most of this should now be implemented as of https://github.com/godotengine/godot/pull/63326. Consider closing this proposal if you consider it sufficiently handled :)

**Comment by MewPurPur** [comment]
Sure, I'll open a separate proposal for the dimming idea since it's more bikesheddy
