### ISSUE TITLE
Add a syntax for documenting method parameters

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#4880]
Reference to existing documentation comments: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_documentation_comments.html

### Describe the project you are working on

Writing documented code for sharing with others

### Describe the problem or limitation you are having in your project

Right now everyone uses `[code][/code]` for documenting parameters, but it's a pretty tedious string to type, and it doesn't differentiate from other code snippets.

`[code]` is even used for parameters in the engine itself. Using something like `[parameter foo]` would at least be future proof if for example we make parameters URL linkable.

![image](https://user-images.githubusercontent.com/14253836/179209356-cdfdfa5b-e29c-4f97-9fc1-5ecede457faa.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make `[parameter foo]` valid in documentation.

Alternative syntax:

- `[parameter foo]`
- `[param foo]`
- `[argument foo]`
- `[arg foo]`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
## Says hello to [parameter who].
func hello(who):
	print("Hello, ", who)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This will be used all over Godot's official documentation

### Is there a reason why this should be core and not an add-on in the asset library?

Documentation is part of the editor

**Comment by aaronfranke** [comment]
@YuriSizov Parameters and arguments are not the same thing. An argument is the value of a parameter. I would prefer either `[param foo]` or `[parameter foo]`. Also, C# uses `param` as the name in the XML doc comments.

**Comment by YuriSizov** [comment]
@aaronfranke I don't think there is a meaningful distinction between the two terms, and it mostly depends on how much you're used to seeing either one of them. But regardless, I chose to pick arg because that's what we call them in the XMLs already, arguments, and all our other reference bb tags map to these names.

If you think this is a point of principle worth correcting, then we need to change it for docs in general.

**Comment by YuriSizov** [comment]
We've discussed it a bit on RC and agreed that `[param foo]` is more consistent, and that we'd be up to change XML structure to use `<param>` or `<parameter>` in place of `<argument>`. Shouldn't go beyond that, though, even if there are some internal structures that call these arguments as well.
