### ISSUE TITLE
Use COLLADA2GLTF instead of our own collada importer

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#4885]
### Describe the project you are working on

Godot Engine and supporting asset creators as they are.

### Describe the problem or limitation you are having in your project

Many developers are troubled by the different Collada exporters and the official Godot Engine Collada importer is not well supported.

These developers want to directly use the export from their existing Collada application with no modifications.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use the same workflow as fbx to gltf but with collada to gltf.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. Duplicate the fbx2gltf code
2. Replace it with collada2gltf.
3. Submit for compatibility testing.
4. Refactor if needed for code clarity

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is trying to move Collada import to an asset library style.

**Comment by YuriSizov** [comment]
> These developers want to directly use the export from their existing Collada application with no modifications.

Example being SketchUp: https://github.com/godotengine/godot/issues/51148

**Comment by DarkKilauea** [comment]
Why would this make `fbx2gltf` obsolete?

**Comment by akien-mga** [comment]
This was attempted but results were pretty bad, and COLLADA2GLTF doesn't seem actively maintained by Khronos. So closing for now, we'll likely keep our own legacy hacky importer.
