### ISSUE TITLE
Allow Newline for arrays and dictionaries

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#4892]
### Describe the project you are working on

Spaceship game

### Describe the problem or limitation you are having in your project

Godot 4.0 is moving towards beta fast and along side https://github.com/godotengine/godot-proposals/issues/4278 I would like to propose this issue. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest that using '[' or '{' after '=' should be allowed after a newline.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Please support this as a valid syntax

```
var array = 
[
    0,
    1
]
```
```
var dictionary = 
{
    0,
    1
}
```

Right now it throws a error.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be used when people prefer...
```
var a =
{

} 
``` 

over... 
```
var b = {

}
```

### Is there a reason why this should be core and not an add-on in the asset library?

It's a simple feature and it would be consistentish with `:` blocks
```
func a():  
    pass 
```  

```
func b():  pass 
```

**Comment by dalexeev** [comment]
Use

```gdscript
var array = \
[
    0,
    1,
]
```

or

```gdscript
var array = [
    0,
    1,
]
```

**Comment by YuriSizov** [comment]
> Godot 4.0 is moving towards beta fast and along side #4278 I would like to propose this issue.

GDScript is already in the feature freeze mode, we aren't accepting or considering changes to the syntax at this point, unless they have already been approved before.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP and general lack of activity).
