### ISSUE TITLE
Have a visual indication that properties in a group are overridden

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot-proposals#4893]
### Describe the project you are working on

Would apply to any mid to big sized project.

### Describe the problem or limitation you are having in your project

Often you open a scene made by someone else, or even by yourself either time ago or complex enough for you to forget the details, you want to check which properties are overridden and your only option is to manually unfold many property groups in the inspector until you find what you were looking for.

For instance, you want to know in which property the material that you are seeing applied to a mesh comes from and you have no alternative to expand some of _Geometry_, _Material Override_, _Surface Material Override_ and every _Surface N_.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It is just a visual indication in the property group caption that there are properties insisde with non-default values.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/11797174/179394370-3a3adee5-aea9-4252-9183-7e48512399a1.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No way.

### Is there a reason why this should be core and not an add-on in the asset library?

Not possible.

**Comment by 98teg** [comment]
I'm not sure about the pencil icon. It seems to me that it is clickable rather than informative. Maybe something like an asterisk would work better? Other than that I would find this very useful

**Comment by RandomShaper** [comment]
An asterisk may be good (less intrusive and text-based). I'll give it a thought.

**Comment by cassandrus** [comment]
![image](https://user-images.githubusercontent.com/97176349/179395142-fe7413e6-7bd8-47e0-9642-5137179854e9.png)
Then perhaps it can be accompanied by "Expand Non-Default" here? Thus "Collapse All" + "Expand Non-Default" will give you ultimate view of all node changes.

**Comment by bitbrain** [comment]
The pencil icon is universally an indicator for "Click me to edit" so this might make things more confusing, especially to people new to Godot.

Alternatively, I'd suggest the following:

- use something like an asterisk
- maybe different font (italic?)
- different colour?
- custom icon (not a pencil but maybe something like 🛠)

**Comment by cassandrus** [comment]
Non-Default values on properties are marked by "reset" icon, perhaps it's better not to invent a new icon and use "reset" for groups too. But user will expect "group reset" functionality from it. :/

**Comment by RandomShaper** [comment]
> Non-Default values on properties are marked by "reset" icon, perhaps it's better not to invent a new icon and use "reset" for groups too. But user will expect "group reset" functionality from it. :/

I considered that and came to the same conclusion. I think the bright text or asterisk or italic, or a combo will be better.

**Comment by bodamat** [comment]
I saw that other recommend asterisk, but in my opinion would be good just point or dot instead pencil icon

**Comment by RabbitB** [comment]
> I saw that other recommend asterisk, but in my opinion would be good just point or dot instead pencil icon

I'd like to second a font-style change and just a simple dot or point to mark the changes. Asterisk implies there's additional information elsewhere about what you're placing it next to. In a number of fields, filled dots are a common shorthand for "changes were made here." Followed by notes on the changes.

**Comment by reduz** [comment]
In general, the properties you modified are unfolded, and objects that you never edited (have a saved sate) unfold by default to show edited properties, so I am not entirely sure under which situation you have folded modified properties unless you re-folded them yourself. Not against this, just curious of the use case.

**Comment by RabbitB** [comment]
> ...so I am not entirely sure under which situation you have folded modified properties unless you re-folded them yourself. Not against this, just curious of the use case.

Some properties have a large footprint when unfolded, so I tend to fold them again after I've made my changes. There's also times where you have heavily modified nodes and there's simply so many unfolded properties, that it becomes cumbersome to scroll through them.

Sometimes I wish we could develop a better UI for listing properties. Not that any other engines do it much better, in-fact I think Godot's implementation of a property editor is one of the better ones. I just feel like there must be a better way than just listing everything out in a big list of foldable groups. But that's a topic for another issue.

**Comment by phantomdesvin** [comment]
> Non-Default values on properties are marked by "reset" icon, perhaps it's better not to invent a new icon and use "reset" for groups too. But user will expect "group reset" functionality from it. :/

I love this solution. It's coherent and intiutive and group reset would be a handy feature to have. It doesn't sound difficult to implement and it's a win-win in my opinion.

**Comment by RandomShaper** [comment]
I see issues with the group reset idea. First, I think it has more potential for being accidentally clicked than for being used intentionally in a legit case where the user knows they want to reset the specific properties in a group. Second, click to expand/collapse would not be possible in the whole width of the caption anymore, since the user should need to be careful not to click the reset icon.

I can somehow understand the consistency argument, but I believe it's only a theoretical principle that doesn't pass the test of reality in this case.

**Comment by AaronRecord** [comment]
If the problem is wanting to find what properties are overridden, why not have a button that filters out and expands all properties that are overridden, like what you can already do with the "filter properties" search bar.

**Comment by loteque** [comment]
> Non-Default values on properties are marked by "reset" icon, perhaps it's better not to invent a new icon and use "reset" for groups too. But user will expect "group reset" functionality from it. :/

A greyed or dimmed reset icon on the group would indicate edited or "resetable" properties within the group while telegraphing the indicator itself in non-clickable.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/63429.
