### ISSUE TITLE
Re-implementing "Texture" mode for Environment Background

### ISSUE THREAD

**Issue by OBKF** [godotengine/godot-proposals#491]
**Describe the project you are working on:**
3D Arcade High Speed Racing Game

**Describe the problem or limitation you are having in your project:**
The ability to add a simple texture as background in the environment was removed in 3.x.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I want to be able to use dynamic backgrounds like Night/Day cycles, Clouds and many more things by rendering them to a viewport from a camera in another scene, then using that texture as my background, I know this has a limitations (no sky reflections), but It works great for many cases.

_See the following videos for implementations done in 2.1 with the amazing results:_
Tutorial: https://www.youtube.com/watch?v=WdyEoJw0EjE
Demo: https://www.youtube.com/watch?v=ThMOcOPPsMA

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The feature works in Godot 2.x and It can be simply implemented from there.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Unfortunately NO, the only way is to fight with setting up multi-viewports on top of each other for each scene you have in the stage.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It can't be done using addons (correct me if I'm wrong).

**Comment by clayjohn** [comment]
I think you can do this with the "canvas" type background. 

Set up a canvas layer with your texture on a full screen textureRect and then set the background mode to "canvas", make sure it is pointing to the right canvas layer and you should be good to go!

**Comment by OBKF** [comment]
I tried that and I am trying that right now and it doesn't work!
Do you have a screenshot or something, I can reference?
![sss](https://user-images.githubusercontent.com/12987951/74615787-030bd100-5124-11ea-9a9a-3845a6657a5a.png)

**Comment by clayjohn** [comment]
Canvas max layer needs to be higher than the canvas layer you intend to use. I'll put something together for you. :)

**Comment by OBKF** [comment]
Ok it is working inside the game (not in the editor), Man this is counter intuitive.
The problem is that the 2D elements now are behind 3D elements, see the following labels in the left:
![ss](https://user-images.githubusercontent.com/12987951/74616372-a90d0a80-5127-11ea-918b-0b4df4e92494.png)

**Comment by clayjohn** [comment]
For some reason it only works in game and not in editor.

If you want the elements to appear on top, then you shouldn't render them to the background layer. Create a new canvas layer to render them to.

**Comment by OBKF** [comment]
I am rendering them to my main scene, and according to the docs it should be Layer0 or Layer1 by default: https://docs.godotengine.org/en/latest/tutorials/2d/canvas_layers.html#canvaslayers

Do I need to report bugs on this or is it like that by design?

**Comment by clayjohn** [comment]
I'm not sure. It worked fine in my test scene so I am guessing you are just making a mistake. But if you are rendering your text to a canvas layer greater than zero and less than the canvas background layer then it sounds like a bug.

**Comment by OBKF** [comment]
I am only using a canvas layer for the sake of the background, and purposefully putting it at -128. 
Please double check this when you have sometime.
This method works, but it is not an intuitive method as just putting a texture from viewport source, not sure if I should close it or not.  
Thank you for the help.

**Comment by clayjohn** [comment]
I just checked it out on my test scene using a Label without a CanvasLayer. Everything worked fine as long as my CanvasLayer for the background as a negative layer and it corresponded to the max_canvas_layer for the background.

**Comment by OBKF** [comment]
> Maybe so, but this allows users to do way more than a texture background does. You can have an entire 2D game running in the background of a 3D scene and all without the overhead of rendering to a separate texture.

I actually didn't know about the performance benefit here, so I will be closing it cause It doesn't bother me much personally.
