### ISSUE TITLE
Add easing options to AnimationNodeStateMachineTransition

### ISSUE THREAD

**Issue by jeronimo-schreyer** [godotengine/godot-proposals#4913]
### Describe the project you are working on

Platformer 3D

### Describe the problem or limitation you are having in your project

I just wanted to ease the cross fading function when transitioning states instead of using linear

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Using a Curve resource you can interpolate the blending factor between the 2 animations

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I just changed /scene/animation/animation_node_state_machine.cpp :: lines 423 and 426 to use a fade_blend value interpolated with a Curve resource and it worked!

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would take someone to extend AnimationNodeStateMachineTransition and use that

### Is there a reason why this should be core and not an add-on in the asset library?

I think this needs to be compiled in the engine

**Comment by TokageItLab** [comment]
Closed by https://github.com/godotengine/godot/pull/63802.
