### ISSUE TITLE
Make nodes acts as Tilemaps.

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot-proposals#493]
**Describe the project you are working on:**
I'm working on a top-down RPG.

**Describe the problem or limitation you are having in your project:**
When you use YSort on Tilemaps, it works, but not in the best way. Also, there are thinks that you could only make on a self-contained node, so you tend to put a lot of nodes into a scene and it can get messy.

![YSort](https://user-images.githubusercontent.com/43701418/74669499-fd46d780-5185-11ea-8f58-90f07367ba82.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
My idea is to set a collection of self contained Nodes and turn them into a Tileset.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm still learning, so what I can really show is a mock-up, it would be like this:

![YSortIdea](https://user-images.githubusercontent.com/43701418/74668601-4d249f00-5184-11ea-8b70-201efadf1523.jpg)

You see? When you're making an Animated Sprite, for example, you put various sprites in it. Personally, I just drag and paste. My idea is to make this with scenes, so you end up with a collection of instanced scenes , but on the editor, you'll see only one Node, that is the Tilemap (or Nodemap, I think that name would fit best). You could also work with all their properties just the same. Well, atleast that's what I'm thinking.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I would use it a lot, personally. it's not something that chains a project, but it makes a lot easier to work with.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It could be a add-on, but I think that it would really help the workflow for everyone, it's not something to fix a particullar need, but to fix every need. You could use this to insert NPC's, enemies, etc... I saw people doing something simillar on Maker's projects, and they did on Godot, so I think it would be possible to.

**Comment by bojidar-bg** [comment]
Was also discussed in https://github.com/godotengine/godot/issues/9180.
(But, do not close this issue, as proposal issues will be moved out of the main repository eventually)

**Comment by Calinou** [comment]
Scene tiles were added in the new TileMap and TileSet editor, closing.
