### ISSUE TITLE
Thread checking annotations in GDScript

### ISSUE THREAD

**Issue by derammo** [godotengine/godot-proposals#4934]
### Describe the project you are working on

I don't produce commercial software with Godot.

### Describe the problem or limitation you are having in your project

This isn't causing me any difficulty.  I am proposing this to be included since it is helpful to me, so I assume others would benefit also.

With the upcoming WorkerThreadPool, threads are going to be much easier to use, so hopefully more users can start to employ them.  This proposal is trying to help them not shoot themselves in the foot. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This proposal is about a GDScript language extension that allows the user to annotate which functions in their class are intended to be used by worker threads.   If a thread other than the main thread enters a function that is not marked, a runtime error is raised (in DEBUG builds only.)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have fully implemented this proposal already in my fork.  It works as shown in this example code:

```extends Node

# example class that does some work on worker threads

# within this class, functions will check that they are only called by main, unless
# they are marked @threaded 
#
# without this annotation, the byte code emitted is entirely unchanged and nothing
# special happens, so this can be used to opt into this feature selectively and
# without changing compiler settings
@thread_checked

# stand-in for WorkerThreadPool that will be natively provided in Godot
@onready var _runner: WorkerThreadPool = WorkerThreadPoolFactory.get_runner()

var _tasks: Array = []

# an example of a value with a setter that isn't safe to use on worker threads
var shared_value: int:
	# GDScript limitation: no place to attach annotations, since this generates a
	# function AFTER parsing the get/set.  So we need to use PROP_SETGET
	# style assignments to get named functions to annotate (see below.)
	get:
		return shared_value
	set(value):
		shared_value = value
		do_something_to_scene()
		
# this is a really gross atomic flag to use while I look for one
var _canceled_mutex: Mutex = Mutex.new()
var canceled: bool = false:
	# PROP_SETGET format, so we can annotate the setter and getter
	set = set_canceled, 
	get = get_canceled
	
@threaded func get_canceled() -> bool:
	var temp: bool
	_canceled_mutex.lock()
	temp = canceled
	_canceled_mutex.unlock()
	return temp
		
@threaded func set_canceled(value):
	_canceled_mutex.lock()
	canceled = value
	_canceled_mutex.unlock()
	
func _ready():
	_test_unsafe_thread_function()
	
	_tasks.push_back(_runner.add_task(self._load_task.bind("res://foo.png")))
	_tasks.push_back(_runner.add_task(self._load_task_with_arg.bind("res://bar.png", 5)))			
	
func _exit_tree():
	canceled = true
	for task in _tasks:
		_runner.wait_for_task(task)
	_tasks.clear()
	_runner = null
	
@threaded func _load_task(path: String):
	if canceled:
		return
		
	# pretend do some special loading or similar
	print(path)
	
	# oops, used a function that we were not supposed to (the setter is 
	# indirectly not thread safe) so worker thread will error out here
	shared_value = 3
		
@threaded  func _load_task_with_arg(path: String, arg: int):
	if canceled:
		return

	# pretend do some special loading or similar
	print(path, arg)
	
	# populate something in the scene graph maybe
	self.do_something_to_scene.call_deferred()
	
func do_something_to_scene():
	# must only run on main thread
	# this is the code we get automatically because of the annotations:
	# assert(OS.get_thread_caller_id() == OS.get_main_thread_id(), "message here")
	name = "hello"

func _unsafe_function():
	print("this should never be printed by a worker thread")

func _test_unsafe_thread_function():
	# test thread safety check
	var test_thread: Thread = Thread.new()
	# worker thread errors out on entry to _unsafe_function
	test_thread.start(_unsafe_function)
	test_thread.wait_to_finish()
		
```

It is much more attractive with the syntax coloring.  It clearly calls out the functions that are supposed to be used by the worker threads, so that hopefully developers and maintainers know to take extra care.

![image](https://user-images.githubusercontent.com/817160/180673990-ad02bebf-e312-43aa-83ae-4cdfb6059012.png)

It is implemented by emitting extra byte code on function entry.  This code is only emitted if the containing class has the @thread_checked annotation to opt in.    Any function that does not have @threaded gets extra entry code that does exactly the same as 

```assert(OS.get_thread_caller_id() == OS.get_main_thread_id(), "... message here... ")```

In non-DEBUG builds, nothing is emitted from this feature.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

In its current form, you could simply comment the functions to say they are used by worker threads and then add the code block at the entry of every other function to do the assertion yourself.    Then you could customize syntax highlighting to color your special comments.

### Is there a reason why this should be core and not an add-on in the asset library?

It requires new annotations and changes to the parser and compiler.  It does not require changes to the VM (other than PR 63267), so it could potentially be a plugin to the script language, but not at the current time, from what I can tell from the code.

If this sort of thing was wildly successful, I would like to grow it to add some features:

- based on the API JSON and additional markup, track which API functions are allowed to be used by worker threads.  Then make the analyzer check for thread safety in cases where the called function can be statically deduced.  

- eventually maybe even annotate the native API functions so that whether something is safe for worker threads is always known and enforced via runtime checks. 

This would make working with threads much safer for Godot users.  Threaded programming is a known problem for people who aren't primarily computer science types, and even for some who are.  Anything that helps find problems faster is worth something.

**Comment by derammo** [comment]
This is what happens when you run the example program:

![image](https://user-images.githubusercontent.com/817160/180134876-b9bf9558-0fd6-474d-9d56-811f5aa5326d.png)

**Comment by derammo** [comment]
Also note that once threads can actually be debugged, these would be breakpoints.  For now, they are just errors that will pop in the Editor (assuming PR 63267).

**Comment by derammo** [comment]
Follow-up:  If you are curious about the implementation, the code is here: https://github.com/godotengine/godot/compare/master...derammo:godot:derammo_thread_checked

However, all the code from https://github.com/godotengine/godot/pull/63267 is in that branch too, to make it work.  So just ignore the parts in \*Debugger.\*

**Comment by vnen** [comment]
My main concern here is the usefulness of this. I understand that it helps avoiding mistakes, but the limits might make it too constricted to be used enough.

In particular because only applies for scripts with the `@thread_checked` annotation. So if it's calling functions from other scripts won't have the same checks. This might be a problem when refactoring as you might start calling outside functions and lose the checks. This would be a user mistake, but the annotation in this case would be detrimental as they might not look so closely thinking the annotation would catch the problems.

I also fear that some users mistake the `@thread_safe` annotation by something magical that automatically turns the function into a thread safe version. At the least it would need to be very well explained in the documentation.

**Comment by Zireael07** [comment]
@vnen: Maybe rename @thread_safe to @thread_use?

**Comment by derammo** [comment]
@vnen I guess this is always true, but just to make it clear.  I don't plan to defend the usefulness of this.  I made it a proposal rather than a PR because I don't care at all if it gets picked up :).   My version of Godot has it and that's useful to me.   If I could have made it a script extension (there seems to be the beginnings of such a thing in the code, but only for completely replacing the language?) then I would have done that.   I am completely not bothered if you decide not to include it.

**Comment by derammo** [comment]
> In particular because only applies for scripts with the `@thread_checked` annotation. So if it's calling functions from other scripts won't have the same checks. 

This represents the reality that you aren't responsible for other people's code.   I considered making a statement-level annotation next (on the calling side) that allows you to say "I am calling this external function and I have made sure it is thread safe also".   Then checking code could be emitted on the calling side also.   Meaning either you have to call things we know from the API docs is thread safe or you need to annotate your calls as saying "take my word for it, I checked it."    It does grow rather quickly... ;)    Like I said above I thought this was a good start and it does something useful.  If it became very popular it could grow to cover a lot more cases.

> I also fear that some users mistake the `@thread_safe` annotation by something magical that automatically turns the function into a thread safe version. At the least it would need to be very well explained in the documentation.

100% agree, implementing the name change suggested

**Comment by derammo** [comment]
Regarding using this without having it included in the core, I just learned what I was missing.  I can create a GDExtension that extends GDScriptLanguage and replaces create_script(...) with something that returns an extended GDScript with an extended parser and compiler.  Then it can use a different file extension for my extended GDScript files with this and other language extensions in it.  

That has nothing to do with ScriptLanguageExtension, which is an empty language implementation skeleton that extensions can use to build their own language support, like the python support etc.

**Comment by derammo** [comment]
Update: renamed @thread_use to @threaded for grammar reasons.

**Comment by derammo** [comment]
I don't plan to pursue this, and it doesn't seem important enough to ever meet criteria for inclusion.  Really this should be an optional extension on the asset library, but that isn't going to happen.  It would require extension being able to add to the compiler, and that would likely be a mess.

Withdrawn.
