### ISSUE TITLE
Option to not start in full screen by default and to define window options

### ISSUE THREAD

**Issue by DCowboy** [godotengine/godot-proposals#494]
**Describe the project you are working on:**
Irrelevant to proposal, but, dungeon management/crawl-card game fusion
**Describe the problem or limitation you are having in your project:**
Every time I start my Godot project it opens to full screen like the devs think I'm too stupid to focus on more than one window at a time or something. Plus, when taken out of full screen the window doesn't always render correctly, instead  part of the bottom and right of the viewport is out of window bounds which requires resizing or maximizing to fix. 
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding options to not start in full screen and options for position and screen size will allow people who are capable of working with more than one application at a time to do so. Also, it will help fix the issue of the whole viewport not displaying in window bounds as specific values will be given for the viewport to properly adjust to.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

In Editor settings:
Label: "Start in full screen"   Checkbox - variable: full_screen(boolean) 
Active if above checkbox unchecked:
Label: "Starting Screen Position:"  Label: "x:" LineEdit (0) Label "y:" LineEdit(0) - variable - viewport.postion(x, y)
Label: "Starting Screen Size:"  Label: "w:" LineEdit (0) Label "h:" LineEdit(0) - variable - viewport.size(w, h)
Save values to editor_settings.tres in an appropriate place

Editor start function: (not sure the name and it's already too late to go look it up.) and assuming it's done in GDScript as the editor was once advertised to be made with itself - add:

    If !full_screen:
        **Can't seem to find method to set viewport rect's postion - Obviously set to value gotten from configuration**
        viewport.set_size(*size from cfg*)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Perhaps, but difficult on the user's end, especially concerning position. But it would be better if the editor was fixed by the maintainers of the editor.
**Is there a reason why this should be core and not an add-on in the asset library?:**
Because this is something that has gotten broken and lost from previous versions.

**Comment by clayjohn** [comment]
Is this related specifically to starting the editor? If so, it likely wouldn't be stored in the project settings but in the editor settings. 

Also, the proposal could likely do without the rudeness and sarcasm.

**Comment by DCowboy** [comment]
Actually, it needs the rudeness and sarcasm as it once worked right and had those options. Until some people who couldn't concentrate if more than one application was visible at a time wanted it to be changed to full screen by default. Then, as late as it is for me I had to jump through hoops to find this place from the original post that suggested to make a new issue about it. If you're upset by what actually made it  in the post, you'd have a heart attack if I would have let my full feelings on the matter show.

**Comment by clayjohn** [comment]
@DCowboy it was just a helpful suggestion. In projects like this you are often more successful convincing others you have a good idea than you are insulting them. 

But that's just a tip!

**Comment by DCowboy** [comment]
@clayjohn Oh you mean projects like this licensed under MIT where I could just as easily fix it myself and turn around and re-market it as Not-broken Godot If I wanted to be meaner than just grumpy? I'm offering the suggestion because of a good feature that was lost, a feature that was once a DIY add to the editor's cfg in 1.x if I remember correctly.

You seem like a bright and fairly nice kid. If you're not going to be useful, then please go play elsewhere.

**Comment by Kequc** [comment]
I'm not sure how it's decided which features are implemented but if you could fix it yourself as suggested I'm sure many maintainers would be very happy to find a pull request. It may be the fastest way to see something like this implemented.

**Comment by DCowboy** [comment]
If I was at a point that it was worth it for me to compile the engine from source, it probably would be worth it to fix it myself instead of put a request out. As long as my project doesn't need me to compile from source, I see no reason for me to need to be on the bleeding edge of development. Perhaps when/if my project gets advanced enough to require it, perhaps I will at that time.

**Comment by Xrayez** [comment]
See existing similar proposal at godotengine/godot#5114 with possible workarounds/solutions, and a fix godotengine/godot#32056.

**Comment by groud** [comment]
@DCowboy It seems that we have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). 

Those kind of sentences :
> You seem like a bright and fairly nice kid. If you're not going to be useful, then please go play elsewhere.

Is neither courteous or constructive. So please refrain from such comment, or you might be the one invited to go somewhere else. Thanks.

**Comment by DCowboy** [comment]
@groud I wish I could say you were as bright as clayjohn. he seemed to at least understand that I was talking about this issue. So since you seem to need it I will be more specific for you.

If you're not going to be useful to this subject, please go find another issue to play on. It's really irritating to have to discuss things that have little to nothing to do with the actual topic.  So, please either get back to the actual topic or find another issue to play on and have a nice day!

**Comment by groud** [comment]
Indeed, as you pointed out, this issue went off topic and flaming too fast, likely thanks to the unneeded aggressive tone of the original post... Closing and locking.

To anyone having the same problem, please feel free to open another proposal without the aggressive tone. Please keep this place professional and welcoming  to everyone.

**Comment by akien-mga** [comment]
@DCowboy Banned for a week. You're welcome to come back once you've calmed down and accepted to be constructive in your interactions with the Godot community. Otherwise we'll have to leave it to others to make constructive proposals.

For the record, I think giving an option to start the editor non-fullscreen is a good idea, but I couldn't care less when it's presented with such saltiness and condescending attitude.
