### ISSUE TITLE
Highlight TODO, FIXME and similar keywords in comments in the script editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#4942]
### Describe the project you are working on

*Related to https://github.com/godotengine/godot-proposals/issues/602 and https://github.com/godotengine/godot-proposals/issues/3845.*

The Godot editor :slightly_smiling_face:

### Describe the problem or limitation you are having in your project

Not a particular limitation, but a quality of life feature for the script editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Other editors such as Visual Studio Code highlight keywords commonly used for important notes and todos. Here's an example with commonly used keywords in the Python language:

With `:` | Without `:`
-|-
![image](https://user-images.githubusercontent.com/180032/180268086-bd3bbf13-1401-4602-a8d4-fbd2b6cef2f7.png) | ![image](https://user-images.githubusercontent.com/180032/180268160-d9713c6a-d51d-47ce-a5bb-012bef31fe6b.png)

Some editors will also highlight the entire line, but this is more complex to implement, especially if you want to handle continuation lines like this:

```python
# TODO: This is a thing that should be done for a future version of the game.
#       This line is still highlighted as TODO due to the spacing.
#
# This comment is not highlighted as TODO.
```

<details>
<summary>File contents - Copy-paste this in various editors for testing purposes</summary>

```python
# todo: Example comment.
# TODO: Example comment.
# FIXME: Example comment.
# fixme: Example comment.
# NOTE: Example comment.
# note: Example comment.
# CHANGED: Example comment.
# changed: Example comment.
# HACK: Example comment.
# hack: Example comment.
# XXX: Example comment.
# xxx: Example comment.

# todo Example comment.
# TODO Example comment.
# FIXME Example comment.
# fixme Example comment.
# NOTE Example comment.
# note Example comment.
# CHANGED Example comment.
# changed Example comment.
# HACK Example comment.
# hack Example comment.
# XXX Example comment.
# xxx Example comment.
```
</details>

**Note:** Unlike https://github.com/godotengine/godot-proposals/issues/602, this proposal does *not* suggest adding a bottom panel to track all TODOs/FIXMEs within the project. It only suggests highlighting those keywords in comments in the script editor. Project management tools such as issue trackers or Kanban boards are usually more suited for long-term TODO/FIXME tracking.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Highlight specific keywords *in comments only*, but probably don't bother with highlighting the entire line (as handling multiline comments is difficult).

I'd suggest supporting the following keywords for highlighting: `TODO`, `FIXME`, `NOTE` and `HACK` (all case-sensitive). Like in Visual Studio Code, these do not have to be at the beginning of a comment line, and these do not have to be followed by a `:` symbol.

`XXX` ("dirty hack") is rarely used nowadays, so there's probably not much point in supporting it. I haven't seen it in years myself :slightly_smiling_face: 

From an implementation perspective, I haven't found a way to add a keyword highlight that works within a color region (i.e. comments). Let me know if you can find a way to work around this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the script editor usability and bringing its functionality on par with popular IDEs.

**Comment by fire-forge** [comment]
Another way to implement this would be to add an editor setting of an array of strings to highlight. The default value would have TODO, FIXME, NOTE, and HACK, but then users could add or remove other words if they want. That would solve the same problem but in a more flexible way.

**Comment by Calinou** [comment]
> Another way to implement this would be to add an editor setting of an array of strings to highlight. The default value would have TODO, FIXME, NOTE, and HACK, but then users could add or remove other words if they want. That would solve the same problem but in a more flexible way.

I don't think the keywords should be made configurable, so that they can also be reliably highlighted by external editors (most importantly, VS Code).

**Comment by seppoday** [comment]
Can't we do both (if possible)?

- Dafault 4 values for internal and external editors
- Possibility to add your own keywoards via settings for non-english people and for editors that want to use it

if it will be too much work then 4 defaults are totally fine.

**Comment by dalexeev** [comment]
We can use [this list](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/alert.xml) as a basis.

**Comment by Copperplate** [comment]
This is an incredibly useful feature, thank you for adding it! One thing I wish is that there was a way to separate regular comments (# with space) from inline comments (# no space) **by color.** Currently, I am using ## _documentation comments_ in place of regular comments to achieve this, but it would be nice to trigger the color distinction just by adding a space after the #.

Again, thank you for so many innovative features in this engine!

**Comment by Calinou** [comment]
> One thing I wish is that there was a way to separate regular comments (# with space) from inline comments (# no space) **by color**.

Please open a new proposal for this.

**Comment by Copperplate** [comment]
@Calinou  Thank you, Hugo. Will do! I appreciate all your work.
