### ISSUE TITLE
UWP on Godot

### ISSUE THREAD

**Issue by ALipAkrohk** [godotengine/godot-proposals#4943]
### Describe the project you are working on

I am not currently working on a specific project.

### Describe the problem or limitation you are having in your project

Game compilation for Xbox console.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Full support for .net 6 and adding UWP to GDscript.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not working on a project, this is a suggestion and question to add a feature.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide
It might be useful for many developers coming to Godot from other game engines, I don't have enough knowledge to add it to Godot.

### Is there a reason why this should be core and not an add-on in the asset library?

Hello, you can use the UWP API to generate xbox output, why doesn't Godot support it if you are developing a version for mono and dotnet?

**Comment by Calinou** [comment]
Godot already has an UWP port, but it's in a broken state (for 3D at least). We welcome contributions on fixing it, but most core contributors don't have enough motivation to work on it anymore (especially with UWP being mostly deprecated by now).
