### ISSUE TITLE
Changing `[Reference]` to `<Reference>` or `(Reference)` for printing 

### ISSUE THREAD

**Issue by skejeton** [godotengine/godot-proposals#4944]
### Describe the project you are working on

A simple dice game where I record each action as a list of Action classes

### Describe the problem or limitation you are having in your project

When you print an array of references, this comes up:
```
[[Reference:2937], [Reference:2938]]
```
This makes it look like an array of 2 arrays containing references, but it's an array of 2 reference, because if we print reference by itself it becomes `[Reference:2937]`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Changing to `<Reference:2937>` or `(Reference:2937)` would remove this confusion.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will fix this in default functionality.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can write your own formatting/printing functions.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think there's a particular reason for using [] for formatting references, so using <> or () would fix this issue.

**Comment by Calinou** [comment]
This should apply to any object being printed without a `_to_string()` override, not just Reference.

**Comment by skejeton** [comment]
I agree, <Reference> looks nice and familiar

**Comment by lentsius-bark** [comment]
I can confirm that my colleagues who came over from other engines initially thought that these were nested arrays with objects in them, this would really help in clarity when debugging.

**Comment by kleonc** [comment]
Lately I saw a user thinking that `[null]` showed in the debugger is a list/array containing a null but currently (at least in `3.x`) that's what is shown for a reference to an already freed object. So this should probably also be taken into account when making changes (it may need to be changed separately in the debugger or something like that).

**Comment by just-like-that** [comment]
> I also wonder if the `:` should be replaced with a `#`

What about '@' instead. That reminds me more of an id?
