### ISSUE TITLE
Don't print `ERR_PARSE_ERROR` and C++ filepaths when GDScript fails to parse

### ISSUE THREAD

**Issue by dallonf** [godotengine/godot-proposals#4945]
### Describe the project you are working on

Just generally learning Godot.

### Describe the problem or limitation you are having in your project

When you save a GDScript file that has a static error in it, you'll get a message like this in the Output:

```
 res://addons/asset_preview/AssetPreviewDock.gd:19 - Parse Error: The identifier "blablabla" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:577 - Method failed. Returning: ERR_PARSE_ERROR
```

This first line is helpful. The second is confusing, alarming, intimidating, and unhelpful.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If those messages are suppressed, there would be much less clutter in the Output, and it would be clear for newer developers when I just made a typo vs. when something has gone catastrophically wrong in the engine internals.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A parse error should only result in one error line in the Output, for example:

```
 res://addons/asset_preview/AssetPreviewDock.gd:19 - Parse Error: The identifier "blablabla" isn't declared in the current scope.
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not with script, but you can just keep clicking "Clear" to remove these lines, I suppose.

### Is there a reason why this should be core and not an add-on in the asset library?

You shouldn't need third-party code to stop your engine from spewing implementation details during very common use cases 🙃

**Comment by YuriSizov** [comment]
> If those messages are suppressed, there would be much less clutter in the Output, and it would be clear for newer developers when I just made a typo vs. when something has gone catastrophically wrong in the engine internals.

Well, parser wouldn't know which one is the case. It may indeed be a critical failure on its part, and not your mistake. Error reporting like that is at the very core of the engine, I doubt it would be possible to hide _some_ internal error messages in a manageable way.

**Comment by dallonf** [comment]
I haven't done much digging into the Godot source code, but it seems to me the parser _does_ know that this is just a typo, since it was able to print that first line with a much friendlier and more helpful message. It just _also_ prints a line with internals.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/63317.
