### ISSUE TITLE
Property to treat Viewport as basic Node inside the editor

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-proposals#4956]
### Describe the project you are working on

Game where I need to have game rendered in a Viewport mode but the camera in 2D mode.

### Describe the problem or limitation you are having in your project

Putting nodes inside `Viewport` makes them disappear. Making them impossible to edit.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`Viewport` should have property to disable it's function inside the editor to preserve editing capabilities.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

User turns on property and the editor is treated as plain `Node` inside the editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around with messy code.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think this can be done as plugin.

**Comment by SilencedPerson** [comment]
https://www.youtube.com/watch?v=AsrmXTUB6tI
For illustration purposes.

Alternatively this could be done by property to have `Camera2D` move in screen coordinates instead??

**Comment by Calinou** [comment]
@SilencedPerson Did you find a workaround for this, or do you no longer have a need for this proposal?
