### ISSUE TITLE
Only display GeometryInstance3D's material override/overlay properties for meshes that already have a surface material defined

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#4967]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

As of Godot 3.5, there are **four** different ways to set materials on a newly created MeshInstance3D node. This is overwhelming for beginners who are just wondering how to assign a material to a mesh.

In general, you don't need to use Material Override and Overlay unless you've already assigned at least one material to either the Mesh resource or the Surface Material Override properties in MeshInstance3D.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Only display GeometryInstance3D's material override/overlay properties for meshes that already have a surface material defined.

With this proposal, there are still 2 ways to set materials on a newly created mesh (either inside or outside the Mesh resource depending on your use cases). Still, 2 ways to set materials is much less confusing than 4 :slightly_smiling_face:

**Note:** This proposal only affects editor display, not storage. Materials will not be discarded from the scene file if they're hidden for any reason.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There are 5 possible scenarios. Here's how they look like with the [pull request that implements this proposal](https://github.com/godotengine/godot/pull/63396).

This is what users would see when creating a MeshInstance3D node with a primitive mesh assigned:

No material anywhere
|-|
*Override and Overlay both **hidden***
![2022-07-24_19 26 17](https://user-images.githubusercontent.com/180032/180659087-b51a1110-5aa9-4852-9605-77fe78d502ec.png)

After assigning at least one material on either the Mesh resource or in the MeshInstance3D surface override, you'll have access to the material override and overlay properties as it now makes sense to use them:

Material defined on Mesh resource | Surface material override
-|-
*Override and Overlay both shown* | *Override and Overlay both shown*
![2022-07-24_19 25 28](https://user-images.githubusercontent.com/180032/180659081-46df21a4-fcff-4353-a1aa-fe608fa83961.png) | ![2022-07-24_19 25 36](https://user-images.githubusercontent.com/180032/180659083-84c39b0f-3e74-4844-bdce-4637cba1ae90.png)

Additionally, if you're porting over an existing project or are defining material overrides via  plugin or script somehow, existing material overrides/overlays will be shown even if they would otherwise not be:

Material override only | Material overlay only
-|-
*Override and Overlay both shown* | *Override **hidden** (overlay kept so you can edit the existing material)*
![2022-07-24_19 25 43](https://user-images.githubusercontent.com/180032/180659084-1a0cad5d-f5de-4914-86e3-59ed240f44c1.png) | ![2022-07-24_19 25 49](https://user-images.githubusercontent.com/180032/180659085-31c9f3f5-9a71-401c-a3d1-d5a50121af1e.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the 3D editor usability, especially for people creating their own materials from scratch.

**Comment by clayjohn** [comment]
I'm not sure that I agree. Each property has a specific use case and comes with performance tradeoffs. They are not only useful after a material has been assigned to the mesh/surface override.

The material override assigns a material on all surfaces at once. Why should you have to assign a material to one surface before you are allowed to assign a material to all surfaces?

The material overlay draws the mesh again with a new material. Similar to render_pass but it applies to all surfaces at once. It is useful whether or not a material has been assigned to the base mesh. 

I'm not sure we gain anything by hiding these properties. Especially since they are already collapsed by default. Instead I think we should be making the other material properties more visible in UI/Documentation.

**Comment by Calinou** [comment]
> I'm not sure that I agree. Each property has a specific use case and comes with performance tradeoffs. They are not only useful after a material has been assigned to the mesh/surface override.

I forgot about this use case while working on this proposal, but I'm not sure how often it pops up in practice.

One scenario I can think of is when importing a [full scene OBJ map](https://github.com/Calinou/game-maps-obj) into a Godot project for prototyping, and using a custom material to texture it (typically with triplanar projection). However, this is very much an edge case, and textures aren't mandatory during the prototyping stage.

**Comment by QbieShay** [comment]
I am against this. I should be allowed to put a material overlay/override on meshes that i have imported from another content creation software without having to assign materials so i can use the overlay/override.

**Comment by Calinou** [comment]
What about only hiding Material Overlay if no other materials are specified in a MeshInstance (i.e. Material Override would be shown at all times again)? While this will not improve the situation over the status quo compared to 3.4, it should avoid worsening usability in 3.5 and 4.0 compared to 3.5.

**Comment by QbieShay** [comment]
My normal usecase is a character composed of a number of surfaces. In that case I'd want to apply overlay for certain effects and override for others.

I don't know, I get the confusion, but this complexity is worth keeping imo.

**Comment by Zireael07** [comment]
I must admit having slept on this, I am of two minds on this. On one hand, in 90% of cases, the proposal makes sense. On the other, there's the 10% where it would make usability worse. Example: character with multiple surfaces imported from GLTF. It has some materials imported, but I don't set them manually in Godot. When I want to change the uniform to camo, I use override. When I want to apply an effect to the entire character (e.g. thermal camera, sci-fi camo), I use the overlay. It would be a hassle to require me to apply materials in Godot before using either...

**Comment by QbieShay** [comment]
I disagree. I think this proposal makes too many assumptions on when i want or do not want to use override materials.
I think users will be very confused if they want to add an override/overlay effect and can't find the property. I can imagine telling people "no the property exists, but you need to assign materials to see it".

I feel like in an attempt of making something more intuitive, we make something way less intuitive.

**Comment by Calinou** [comment]
Closing due to lack of support.
