### ISSUE TITLE
Allow accessing glTF extras/extension data in asset import

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot-proposals#4968]
### Describe the project you are working on

3D games with heavily customized asset pipeline

### Describe the problem or limitation you are having in your project

With glTF becoming the main path to import 3D assets into Godot, it should be easily possible for a game developer to create a script that take advantage of the [glTF extension system](https://github.com/KhronosGroup/glTF/blob/main/extensions/README.md#about-gltf-extensions) (as well as [extras](https://kcoley.github.io/glTF/extensions/#extensions-vs-extras), which are a less standardized version of extensions). This would allow artists to e.g. toggle a checkbox in Blender which automatically runs code to replace the shader, set the model up for direct usage, etc.

The current methods of interacting with the loading of 3D assets are:
- Per-Asset Import Scripts (`EditorScenePostImport`)
  - Problem: They get the fully parsed scene as input, no access to the parsed glTF data
- `EditorScenePostImportPlugin`
  - Problem: Same as above
- `GLTFDocumentExtension` (not to be confused with glTF extensions!)
  - Problem: They can currently only be registered if you have access to the `GLTFDocument` (e.g. if you import a model via code).
- `EditorSceneFormatImporter`
  - Problem: While you can override `_import_scene`, you can not intercept the `GLTFDocument`.

So if you are importing e.g. a .blend asset via the editor, there is no easy way to retrieve the glTF extensions dictionary.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It seems best to use the already existing `GLTFDocumentExtension` and merely provide access to it.

This is done by

- Creating a new `EditorSceneFormatImporterGLTFBase` class that the gltf, fbx and blend importers inherit from. This allows sharing the creation logic for `GLTFDocument` and `GLTFState`.
- This new class gets a virtual method `_initialize_gltf` that is run before loading the file, but after document/state are already instantiated.

The user can now create their own importer plugin which inherits from an existing one, but can modify the `GLTFDocument.extensions` array.

Since the importer gets access to the file it is handling, it can do additional filtering by path to either function globally or only for a subset of scenes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above section for more details.

An example importer would look like this:

```gdscript
# Create a plugin in project settings, then replace the plugin.gd contents with:
@tool
extends EditorPlugin

var importer

func _enter_tree():
	importer = MyImporter.new()
	# Without the "true" parameter, our importer will not be used since it is added
	# to the end of the list by default (and we use the same file extensions as the
	# "default" format importer).
	add_scene_format_importer_plugin(importer, true)

func _exit_tree():
	remove_scene_format_importer_plugin(importer)

# Can be changed to FBX, Blend, etc.
class MyImporter extends EditorSceneFormatImporterGLTF:
	func _initialize_gltf(original_path, gltf_path, document, state):
		# Intercept the GLTFDocument generation. Main use case is to add to the
		# list of document extensions, as it's done here. Check for the path parameter
		# to only conditionally use extensions.
		prints("orig path:", original_path, "// gltf path:", gltf_path)
		document.extensions.append(MyDocumentExtension.new())

class MyDocumentExtension extends GLTFDocumentExtension:
	func _import_node(state, gltf_node, json, node):
		# Do more complex changes to the imported node tree. Since we get access
		# to the JSON data, we can read "extras" and "extensions" here and act accordingly.
		prints("parent:", node.get_parent().name)
		prints("scene_name:", state.scene_name)
		prints("json:", json)
		# Basic example of manipulating the scene tree:
		node.scale.y *= json.get("extras", {}).get("squash", 1.0)
		return 0
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It theoretically is possible to create a custom Import Script, which...

- In case of non-.glTF files: finds the corresponding generated .gltf file in `.godot/imported`
- Parses the GLTFDocument and redundantly generates a scene from it (otherwise the `_import_node` method is not called)
- Discards the scene (as it does not have the correct import settings) and copies the relevant information from the extension to the scene that was passed into the import script

But this affects import performance negatively (due to parsing the file twice), depends on the structure of the .godot folder, and needs many lines of code which are not intuitive to come up with.

### Is there a reason why this should be core and not an add-on in the asset library?

There is no API that would make it possible to implement this via an add-on. The workaround is not good enough to be relied upon.

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
I tried `get_document_extensions() method to EditorScenePostImport` previously and it didn't work.

Putting it as a gltf importer option is good.

**Comment by RedMser** [comment]
Since `GLTFDocumentExtension` is now registered globally after https://github.com/godotengine/godot/pull/66026, this proposal is no longer relevant.
