### ISSUE TITLE
Add a `%v` format specifier to round Vector2/3 when printing

### ISSUE THREAD

**Issue by just-like-that** [godotengine/godot-proposals#4972]
### Describe the project you are working on

A 2D block-based game.

### Describe the problem or limitation you are having in your project

I output vector values frequently.

As most values are usually NOT integer I end up with this:
(234.46454545, 434.5435435)

or this in case of an array:
[(234.46454545, 434.5435435), (234.46454545, 434.5435435), ..., (234.46454545, 434.5435435)]

That's hard to read and floods the output console too.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Support for format specifier "%v" for vectors(2/3) which behaves exactly like "%f" with all its combinations including padding.
[Format Specifier](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_format_string.html)

"%v" % Vector2(234.46454545, 434.5435435) 
returns the familiar looking string
(234.46454545, 434.5435435)

whereas 
"%.2v" % Vector2(234.46454545, 434.5435435) 
would return the much more readable and compact string
(234.46, 434.54)

To support an array I propose the use of "[]" like so:
"%.2[]v" % [Vector2(234.46454545, 434.5435435), ....]
with a result of:
[(234.46, 434.54), (234.46, 434.54), ..., (234.46, 434.54)]

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

By introducing of format specifier "%v" for Vector2/3 in the exact same way as "%f" works as vectors are just two or three float numbers structures.

**"%v" always works on all parts of a vector x, y and z if suitable.**

Format specifier "%[]v" makes the same for an array of vectors.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think output of vectors is a quiet common use case. So many devs would probably benefit from it.

### Is there a reason why this should be core and not an add-on in the asset library?

Format specifier are a core feature and it makes sense to have support for it in one place.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/63728.
