### ISSUE TITLE
Rename RichTextLabel's `percent_visible` to something else

### ISSUE THREAD

**Issue by TrickyWidget** [godotengine/godot-proposals#4978]
### Describe the project you are working on

Anything that uses a node with that property

### Describe the problem or limitation you are having in your project

The "percent_visible" property on various nodes is confusingly named.  A percentage is a value between 0 and 100.  But the percent_visible property takes a value that is between 0 and 1.  I suggest renaming the property to reflect its actual function.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest renaming the property to reflect its actual function.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

"Label.portion_visible = 0.7" or some such thing.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

NA

### Is there a reason why this should be core and not an add-on in the asset library?

The property exists in the core.

**Comment by Calinou** [comment]
See discussion starting from https://github.com/godotengine/godot/issues/54161#issuecomment-1173065060.

**Comment by TrickyWidget** [comment]
> In programming a percentage is often conveyed with a floating point number between 0 and 1

In programming, _portions_ are often conveyed with a floating point number between 0 and 1.  Those portions are usually termed "scale" or "fraction" or the like.  That portion is not typically termed a "percentage".  Probably because it's not a percentage.

**Comment by Mickeon** [comment]
How about `ratio`?

**Comment by Mickeon** [comment]
Actually, upon second thought and looking at all properties of RichTextLabel, I think I will go for... `text_visiblity`. It will group pretty nicely with `text` and `text_direction`.
