### ISSUE TITLE
Tranform a Plane in Godot 4

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#4985]
### Describe the project you are working on

making a portal and I need to tranform a plane

### Describe the problem or limitation you are having in your project

previos godot engine versions 3.x we had a function "xform" :
transform.xform(Plane)
, it was removed in favour of the operator *
but Planes weren't added to the operator *
 only Vector3 
Edit :
checked it now most types that worked with "xform" before are now using the operator * except Plane it was not added with them.
so AABB, PackedVector3Array, Vector3 are there except the type "plane" 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I can't transform a plane.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know how is it done.
N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am not sure, but it was an engine core

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by YuriSizov** [comment]
Please open a bug report instead, providing the version of Godot 4 that you use and other information outlined by the template there.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/63489.
