### ISSUE TITLE
Implement pinning in the text shader and visual shader bottom panels

### ISSUE THREAD

**Issue by viksl** [godotengine/godot-proposals#4988]
### Describe the project you are working on

Just some visual shaders.

### Describe the problem or limitation you are having in your project

Everytime you click outside the shader window it disappears.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Animation already has the pin button to keep the window open.
If you click into the FileSystem the window also doesn't just close.

It would be great if this functionality could be extended to the visual shaders/shader window in general, of ten you need to check some other node, or just assign something into Shader Param which is (in)conviniently placed otuside the shader which means if you set a uniform you need to click back, shader window closes, you set the param, open window again, you realize you forgot a param or wanted a different value to test then you have to repeat this entire cycle again and again.

I know there are plans for 4.0 which make changes to UI but since the functionality already exists I think many would welcome extending it to the shader window, this way the changes don't realy on the new functionality at least and since this at least partially exists hopefully it would be too much work to extend 3.x?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Click on the pin button, the window remains open even if you click around (other nodes, editing shader params, ...).
To see how this can work check the AnimationPlayer and the Animation window and its pin button.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

No other way except building a new custom shader window I guess?

**Comment by Calinou** [comment]
This should be addressed by https://github.com/godotengine/godot/pull/61459 in 4.0, as well as https://github.com/godotengine/godot/issues/32002.

**Comment by KoBeWi** [comment]
Isn't this solved by the new Shader editor? It's now always visible and has persistent shader list.

**Comment by Calinou** [comment]
Closing per the above comment.
