### ISSUE TITLE
Push jumps to script editor history

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot-proposals#4989]
### Describe the project you are working on

The Godot Editor

### Describe the problem or limitation you are having in your project

Just like Godot, other script editors like Visual Studio (Code) also feature a file history that can be navigated e.g. via the extra mouse buttons.

Their history is a bit more in-depth however, as it records not just navigation between files into the history, but also navigation *within* the same file. Especially for larger scripts, it can be very useful to quickly navigate inside of the file.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The navigation history feature would be extended to not only record a list of opened files, but also a list of **jumps** that happened within any file.

A jump is considered any of the following:
- Ctrl+Click onto a member (method, signal, property) which resides within the same file
- "Go to function" menu option
- "Go to line" menu option
- "Go to previous/next bookmark" menu options
- "Go to previous/next breakpoint" menu options

Great care must be taken to not push the same history item twice (e.g. recording both the jump and the tab switch as separate history entries).

A new editor setting could be introduced to disable this new behavior.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

By calling `ScriptEditor::_save_history` for these operations, new history entries are added that automatically include the current line/column and scroll position.

Navigating within the file multiple times will cause the "script temperature" feature to lose its saturation more quickly, so it may need to be changed so it does not increment if there has not been a switch between files.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this is core functionality that can not be edited externally.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core functionality that can not be edited externally. It also is a common feature of other IDEs.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/954#issuecomment-635672178, which proposed this a while ago.
