### ISSUE TITLE
Improvement Track Optimizer in Importer

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#4997]
### Describe the project you are working on

3D Character Project

### Describe the problem or limitation you are having in your project

The current track optimizer's algorithm for removing keys is very rough. So motion tracked animations like Mixamo have many small value keys, and the algorithm frequently corrupts them.

In fact, similar issues have been posted many times in the past.

https://github.com/godotengine/godot/issues/53864
https://github.com/godotengine/godot/issues/58968

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It will provide better default settings when importing animations.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

After looking into the algorithm, here are two suggestions for improvement that came to mind for now:

- Make RotationTrack's default tolerance much smaller
    - RotationTrack can vary in appearance by several degrees. Furthermore, in character animation, there are many bones in a chain, so small differences in RotationTrack can add up to big differences
- Instead of value-based comparisons, use velocity-based comparisons
    - For example, when comparing value matches, an animation of `0, 1, 2, 2, 2, 3` would be optimized as `0, 1, 2, X, 2, 3`, but if this is linear and equally spaced, it can be optimized as `0, X, 2, X, 2, 3`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Track optimizer is in the core.

**Comment by Zireael07** [comment]
Literally today I helped someone with "waaah my animations are messed up" kind of a problem by suggesting they turn off the optimizer first.

Definitely needs to be improved or turned off by default. IIRC we tried the latter and decided to improve?

**Comment by TokageItLab** [comment]
We may will try to improve it for now. At worst, we will not disable it, and it should be possible to lighten the animation by removing only those keys whose values and velocities match perfectly by setting the tolerance to 0 without corrupting animation.

**Comment by Calinou** [comment]
> Make RotationTrack's default tolerance much smaller 

I'd do this first. Automatic optimizations should strive to be *perceptually* lossless by default (like automatic mesh LOD generation works right now).
