### ISSUE TITLE
Add a PacketPeerBuffer

### ISSUE THREAD

**Issue by evandikt** [godotengine/godot-proposals#500]
**Describe the project you are working on:**
Communicate between Godot 3.X and nodejs
[gd-com](https://github.com/gd-com/utils)

**Describe the problem or limitation you are having in your project:**
Data send does not seems to be exact cause of header ...
[Godot QA](https://godotengine.org/qa/57245/how-put_var-works)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a `PacketPeerBuffer` who work like `StreamPeerBuffer` but for packet.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just same class but it doesn't add packet length header on top of data look at the 
[Godot QA](https://godotengine.org/qa/57245/how-put_var-works).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yeah, just don't use `StreamPeerBuffer` but it's hard to make some Buffer in code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a low level networking feature

Thx for your work

**Comment by Faless** [comment]
This can be achieved via `StreamPeerBuffer` and `put_packet`:

```gdscript
var sp = StreamPeerBuffer.new();
# Write packet
sp.put_8(0x7F)
sp.put_float(0.2)
# Send via a PacketPeer.
udp.put_packet(sp.data_array)
```
