### ISSUE TITLE
Allow signals to be called without a argument

### ISSUE THREAD

**Issue by IsotoxalDev** [godotengine/godot-proposals#5001]
### Describe the project you are working on

I am working on a UI project that is called GoDAW: A DAW being made using godot.

### Describe the problem or limitation you are having in your project

![image](https://user-images.githubusercontent.com/62714538/181545994-bc6f6dc3-8fd5-4c47-9703-1fe666e4aa2d.png)
If i want to update the grid which is made of draw() function i just need the signal to call the function without any argument. now as a workaround I have to create a function to call the update function

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If there was an option to connect a signal to a function and don't pass in any argument It would make the code rater clean and reduce me from writing a meaningless function.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As of now, godot has this option to add on extra arguments to the connected function. This can be done in the GUI interface of godot using the Advanced CheckButton. In the same menu an option to remove the already set argument would be great!!

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The work around is as simple as `_on_hsplit_dragged(offset): grid.update()` but this is extremely inconvinient. when i could have done the same with a signal with no arguments.

### Is there a reason why this should be core and not an add-on in the asset library?

The signal connect thingy is defined in the core iirc.....

**Comment by Mickeon** [comment]
Someone correct me if I'm wrong, but because Godot 4 allows arguments to be unbound, this proposal is already done?

**Comment by kleonc** [comment]
> Someone correct me if I'm wrong, but because Godot 4 allows arguments to be unbound, this proposal is already done, in a way?

Yeah:
![godot windows tools 64_b805MXn4cH](https://user-images.githubusercontent.com/9283098/181605716-e95297ef-41b7-49ff-b82e-d8eab15968c9.png)
![ANOedG1p2t](https://user-images.githubusercontent.com/9283098/181605729-15e21ef8-4eae-4246-8c4c-69395f9dd91d.png)

The UI in this dialog could definitely be improved though.

**Comment by KoBeWi** [comment]
Closing as this is already implemented.

As for the connection dialog UX, there are some PRs that improve it:
https://github.com/godotengine/godot/pull/60478
https://github.com/godotengine/godot/pull/27988
Feel free to open proposals if you have more ideas for improvements.

**Comment by IsotoxalDev** [comment]
Can this feature be added to 3.x.

**Comment by KoBeWi** [comment]
It can't be done in the same way as 4.0, but I guess for 3.x https://github.com/godotengine/godot/pull/38289 could be revived. It doesn't make sense to add a unique feature in older version of Godot though, so no.

**Comment by IsotoxalDev** [comment]
until 4.0 is out 3.x can't be older....
