### ISSUE TITLE
Add Brotli (de)compression support to core

### ISSUE THREAD

**Issue by DeeJayLSP** [godotengine/godot-proposals#5002]
### Describe the project you are working on

Playing around with data manipulation for my game.

### Describe the problem or limitation you are having in your project

Limited only to FastLZ, DEFLATE, Zstd and GZip, it would be cool if we have more compression options.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add brotli as an option to File compression modes and maybe ENetConnection compression modes.

In fact, the brotli library is already present in Godot's source code (it was added as a dependency for WOFF2 support).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The user would be able to use File.COMPRESSION_BROTLI as a compression mode.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Part of it is already in the source, it just needs to be coded in.

**Comment by Calinou** [comment]
Since Godot 3.5, there's a Brotli decompression library compiled so that Godot can read WOFF2 fonts, but the compression library isn't compiled IIRC.

**Comment by Calinou** [comment]
Brotli decompression is now exposed to the scripting API: https://github.com/godotengine/godot/pull/75447

Brotli compression isn't implemented in the engine for binary size reasons, so it can't be exposed.
