### ISSUE TITLE
Add "disabled" Property to TouchScreenButtons

### ISSUE THREAD

**Issue by ACB-prgm** [godotengine/godot-proposals#5006]
### Describe the project you are working on

any smart phone project using touch buttons

### Describe the problem or limitation you are having in your project

I would like to disable a button as I would with the typical control nodes without having to create my own method that changes the TouchScreenButton's textures and mutes its signals.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

adding a disabled property would make TouchScreenButtons more user friendly and put them on par with the Control Buttons

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

NA

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe it would be used as often as the disabled property of regular buttons would.  It can be circumvented with a few lines of script, however.

### Is there a reason why this should be core and not an add-on in the asset library?

The TouchScreenButtons should be on par with the rest of Godot's buttons.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/3976.

I think replacing TouchScreenButton with ordinary buttons makes more sense at this point.

**Comment by ACB-prgm** [comment]
Yeah agreed.  I did not know that was in the works.
