### ISSUE TITLE
Make Raycast2D's debug shape more representative of its `cast_to` position

### ISSUE THREAD

**Issue by ACB-prgm** [godotengine/godot-proposals#5009]
### Describe the project you are working on

any project using Raycast2D

### Describe the problem or limitation you are having in your project

Many users, beginners to experienced, will be confused that the cast_to of a Raycast2D actually corresponds to the base of the arrow in the editor, not the tip of the arrow.  This leads to a lot of frustration.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the raycast shape more representative of Cast_to to make it more visually interpretable for users.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have two possible solutions,
1. just make the cast_to the tip of the arrow
2. add points like what is done for objects using PoolVector2Arrays (Line2D, CollisionPolygon2D, ETC) so that it is clear.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

as it is a visual enhancement, not really.  

### Is there a reason why this should be core and not an add-on in the asset library?

People would not think to look for this feature until after having already experienced the issue.

**Comment by Calinou** [comment]
I don't understand. Isn't the tip of the arrow already drawn at the `cast_to` position (in local space)?

Remember that `cast_to` is relative to the RayCast's position.

**Comment by ACB-prgm** [comment]
> 

No.  `cast_to` draws to the base of the arrow, and the arrow head is of some arbitrary length.  In this picture, I have the `cast_to` set to `(50,0`) and a `Line2D` with points `[(0,0), (50,0)]`

<img width="574" alt="Screen Shot 2022-07-29 at 4 43 00 PM" src="https://user-images.githubusercontent.com/63984796/181840368-cf79ed2c-705d-4463-a805-f372cc447544.png">

**Comment by fire-forge** [comment]
This has already been done in 3.5. Example with 2 RayCast2Ds with the same length:

### 3.5:
![image](https://user-images.githubusercontent.com/67974470/182001872-9b06ed5c-cd1e-4acd-b574-26b3818c95ba.png)

### 3.4.3:
![image](https://user-images.githubusercontent.com/67974470/182001933-a92dc3e5-16d6-4460-9943-f3db5ba79391.png)

**Comment by Calinou** [comment]
This is already implemented in 3.5 as mentioned by @fire-forge, closing.
