### ISSUE TITLE
Improve Ambient Light Rendering

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#5018]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Mono color (or low variance color) Ambient Lighting result in loss of Object Depth resulting in a Very flat look of Geometry.
This issue is also Present with other Ambient Lighting, (such as the Default Skies and the like) just not to the same extent, as the variance in lighting does add a little bit of the depth back
Left: Proposed
Right: Current
![Irradiance](https://user-images.githubusercontent.com/50302479/181908961-01c837a1-2ff4-4447-82a9-86981a035995.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding the depth to Radiance and Irradiance would resolve this issue at minimal performance impact.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add the equivalent to these GDShader Fragment snippets To Shaders resolves this issue for both Metallic and Non-Metallic Materials when in the presence of low variance Ambient/Reflected Lighting
`	IRRADIANCE+=vec4(0.0,0.0,0.0,-clamp(dot(VIEW,NORMAL),0.25,1.0)*multiplier);`
`	RADIANCE+=vec4(0.0,0.0,0.0,-clamp(dot(VIEW,NORMAL),0.25,1.0)*multiplier);`
multiplier is a user controlled variable, that determines how strong the depth should be, and should be added to the Materials, a base of 0.5 should probably be default for best overall results, and value of 0 reverts to old behavior.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but you have to create a shader for each material.

### Is there a reason why this should be core and not an add-on in the asset library?

Drastically Improves Core Rendering.

**Comment by mrjustaguy** [comment]
Here are a few Extra References:
Godot Icon Sky
![image](https://user-images.githubusercontent.com/50302479/181909528-bb123f32-999d-4418-a3ae-ed2867870102.png)
Noise Sky Default Frequency
![image](https://user-images.githubusercontent.com/50302479/181909606-b66716e7-6c70-46ea-a030-f47467976396.png)
Procedural Sky
![image](https://user-images.githubusercontent.com/50302479/181909627-5175cd57-223c-4799-b9fd-4f7fa7b77a8e.png)

**Comment by Calinou** [comment]
cc @clayjohn 

Is this a physically accurate change?

**Comment by mrjustaguy** [comment]
I do not know if it is the most Physically accurate change, as in I'm unsure if there is a better more accurate way of getting the Ambient Light/Reflected Light to not result in totally flat looking geometry with the problematic lighting conditions, But I do know that even if it's a Hack, it's significantly more accurate to the current behavior.. Just turning on SDFGI in such scenarios gives the current Ambient Lighting a similar look, but is Significantly more expensive
SDFGI ON
![image](https://user-images.githubusercontent.com/50302479/181936239-14c8c995-983d-4568-8978-80486a5b4344.png)
SDFGI OFF
![image](https://user-images.githubusercontent.com/50302479/181936263-40f35022-db17-44a4-9063-81f45267b911.png)

As for the Brightness issue, that can probably be fixed, although I'm not exactly sure how (Not that great with Shaders tbh)... Possibly Normalizing the Radiance and Irradiance would help?

**Comment by mrjustaguy** [comment]
Ok, well I've found one unexpected side effect.. in a cube, when rotating the camera, the faces change their light intensity...

**Comment by WrobotGames** [comment]
> cc @clayjohn
> Is this a physically accurate change? This sounds like a form of [fake contrast](https://doomwiki.org/wiki/Fake_contrast) to me 🙂

This doesnt seem physically accurate to me after checking how its done in unreal and blender. (And a bit of light theory)  Basically every single material should get brighter the smaller the angle gets. (the [Fresnel effect](https://www.dorian-iten.com/fresnel/)). 

Here is a sphere mesh in Godot, Unreal, and cycles. (Albedo = white, Metallic = 0, Specular = default (0.5), roughness = 0)
![image](https://user-images.githubusercontent.com/66079814/182034651-2e9d1f8f-b543-4907-ad7c-d316c1704c81.png)

I think that the material on the images that mrjustaguy had a roughness of 1 (Godots default). This effect ins't there in any of the real-time renderers that I tested.
Here is the same image but with a roughness of 1, (Blender eevee instead of cycles in this image)
![image](https://user-images.githubusercontent.com/66079814/182034964-8c5ab764-5999-4009-8159-4fa3dc4e06e4.png)
yes it looks flat, but this is to be expected. the fresnel is there is blender cycles (not in the image) but this a completely different technique of rendering.

If this 'fake shading' were to be added to godot, it should be an option in the project settings, and should definitely NOT be the default.

**Comment by mrjustaguy** [comment]
My current Implementation seems to be getting fairly close to what Blender Cycles is Getting so I'm not getting what you're talking about exactly...

Godot My Proposal:
![image](https://user-images.githubusercontent.com/50302479/182035711-6079f077-00cb-4685-88f1-3221f988cf64.png)
Blender Cycles:
![image](https://user-images.githubusercontent.com/50302479/182035739-f30a99d3-6072-4ccd-856d-8e5e94326e20.png)
Godot Current (Fully Flat, unable to see geometry):
![image](https://user-images.githubusercontent.com/50302479/182035769-cc89a5ad-c746-41b9-9385-9fb489775ba5.png)

**Comment by Calinou** [comment]
> If this 'fake shading' were to be added to godot, it should be an option in the project settings, and should definitely NOT be the default. I hope this makes stuff clear :)

At this point, I'd prefer to have a way to override BaseMaterial3D in a project so you can add your own customizations. Project settings that are disabled by default will barely ever be used, so I'd prefer not to bloat the engine with optional tweaks like these.

**Comment by Zireael07** [comment]
>  I'd prefer to have a way to override BaseMaterial3D in a project so you can add your own customizations without having to use a ShaderMaterial everywhere.

Please please, this would be *so* useful for many things.

**Comment by WrobotGames** [comment]
> At this point, I'd prefer to have a way to override BaseMaterial3D in a project so you can add your own customizations without having to use a ShaderMaterial everywhere. 
A slot somewhere in the project settings where you could use your own shader as defaultshader would indeed be really handy for projects with a more stylized art direction. 
Tweaks like the one mentioned in this issue could probably be done in de light shader.

**Comment by clayjohn** [comment]
This is a very cheap and very fake way to approximate ambient occlusion. Comparing the blender cycles render to the proposed implementation makes that very clear. This adds occlusion to every tangential surface in motion you will see the occlusion swimming across the surface of objects. It essentially is faking a large light source between the camera and object. 

In the cycles render you can see occlusion is only present in occluded areas (between the model's legs for example).

In Godot you can achieve this looks by either specifying ambient occlusion maps in the baseMaterial (most accurate) or by turning on SSAO (easier but less accurate). 

I do not think we should add such a specific hack to the engine.

**Comment by mrjustaguy** [comment]
Closing as a suitable workaround for the issue was found (Calculating irradiance with a Gradient 2d texture with the top being Bright and bottom being Dark, providing Neutral Lighting that also makes depth visible, while also being done in a single shader (sky shader) and easy to control)
