### ISSUE TITLE
Add ability to move individual CSG faces as opposed to scaling from both sides. (and for CollisionShapes)

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot-proposals#5019]
### Describe the project you are working on

Making 3d games.

### Describe the problem or limitation you are having in your project

When you want to add CollisionShapes to a mesh, or block out a level with CSG, it's quite tedious and takes a bit longer than it needs to.

If you want to line up a CollisionShape, you have to move it to approximately the center of your object, then resize and hope that it lines up. And when it doesn't line up, you have to move it again, resize it again and keep repeating until it's correctly positioned. Same with CSG shapes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There should be an ability to pull one side only for CollisionShapes and CSG nodes (and other nodes where it seems useful voxelgi, reflection probe etc.). Exactly like the way control nodes are resized by default. If you want to, try to lay out a user interface by holding alt each time you want to resize a control node. It's not the most fun, and it's even more tedious in 3D. This feature would improve enjoyment and speed at blocking out levels and setting up collisions for objects.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

These objects would behave like control nodes by default, and just like control nodes, when you hold alt, you get the original behaviour, where it resizes from both sides.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but setting up collisions is very common.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, like above, these things are very common, and this is such a small (but useful) feature that it really should be built in, and the default.

**Comment by KoBeWi** [comment]
Related #452 (it only mentions collision shapes)
The feature already exists in 2D.

**Comment by Calinou** [comment]
Unfortunately, this is difficult to implement from an editor perspective as you need to adjust both the node's position and its extents at the same time. Last time I tried, the editor didn't like doing that and it never behaved as expected.

**Comment by WickedInsignia** [comment]
This is the ideal behavior and the one that Unity has by default. Reflection probes are a headache to place correctly right now. Being able to adjust each face individually is ideal.
![RefProbeHandles](https://user-images.githubusercontent.com/70243134/226090844-521d555a-227c-4235-9326-5bd78d1baddc.png)
