### ISSUE TITLE
Allow changing the editor help's font size

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#5020]
### Describe the project you are working on

prototyping with godot 4

### Describe the problem or limitation you are having in your project

The size of the font in the editor documentation is tied to the editor font size (`interface/editor/main_font_size` editor setting).
https://github.com/godotengine/godot/issues/10850#issuecomment-601441330 mentions changing the editor scale, but that means that if one want big docs text the price is having a huge interface.

I personally find such quantities of small text hard to read.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1. Provide an `interface/editor/docs_font_size` editor setting that controls the editor interface scale,
2. allow changing this setting by `ctrl + mousewheel`-ing in the docs view, similar to the script editor, to easily adapt to the case-by-case need.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

UX would be the same than in the script editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

used often

### Is there a reason why this should be core and not an add-on in the asset library?

it's core already

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-proposals/issues/1914.
