### ISSUE TITLE
Add a GUI for editing `Quaternion`

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#5021]
### Describe the project you are working on

3D Character Project

### Describe the problem or limitation you are having in your project

We cannot edit Quaternion intuitively.

Related issues:
https://github.com/godotengine/godot/issues/39229
https://github.com/godotengine/godot/issues/60023

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Bone animation/pose is handled by the quaternion, but it is difficult to directly edit the values of the quaternion elements.

Node3D::transform can have separate Euler and scale values with rotation_edit_mode, but it is impossible to add such additional properties to all classes that use quaternions. At least in animation, they must be Quaternion to avoid incompatibilities due to gimbal lock and rotation_order.

So we need to implement a feature that provides a temporary Euler GUI for editing Quaternion.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/61938263/181924891-f5fb19e2-88c7-40e4-9865-2d36d7f5ff25.png)

You can temporarily edit the Euler value by pressing the Edit button. Note that this Euler value will be discarded by the Quaternion transformation after it is determined. For example, a rotation of 540 degrees will probably be 180 degrees the next time it is edited.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

EditorInspector is core.

**Comment by me2beats** [comment]
Is this related to https://github.com/godotengine/godot-proposals/issues/4504

**Comment by TokageItLab** [comment]
Ah yes, I had forgotten about that.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/64691.
