### ISSUE TITLE
class OS: Implement funcs for fetching distribution name and version

### ISSUE THREAD

**Issue by MJacred** [godotengine/godot-proposals#5022]
### Describe the project you are working on

Videogame - features **bug reporting**, therefore requires collecting system info

### Describe the problem or limitation you are having in your project

* `get_name` returns for Linux and BSD systems `X11` (in Godot 3) or `linuxbsd` (in Godot 4), but not a better fitting value such as the distribution name
* cannot get OS version to narrow down issues to specific OS versions

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Picking up on https://github.com/godotengine/godot/issues/31895

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

new funcs
* `OS.get_version() String`
* `OS.get_distribution_name() String`

#### Add OS.get_distribution_name for Linux and BSD

This func returns for Linux and BSD the value `X11` in Godot 3, `linuxbsd` in Godot 4.  
Even the name change in Godot 4 basically only lists the OS family name (joined together). But these families have many members, which do their own thing: `Ubuntu`, `Manjaro`, `OpenBSD`, etc.

Therefore, there is the suggestion to add a `OS.get_distribution_name()` func, which returns values such as
* `Ubuntu`, `Mageaia`, `Manjaro`, `Ubuntu`, `Linux Mint`, `Arch Linux`, `Linux Mint` etc. (i.e. distribution names for **Linux OS family**)
* `OpenBSD`, `FreeBSD`, etc. (i.e. distribution names for **BSD OS family**)

Proposed API func description:
```gdscript
String get_distribution_name ( ) const
# Returns on Linux and BSD platforms the user OS' distribution name (e.g. Ubuntu, Manjaro, OpenBSD, etc.). For other platforms, the OS name is returned.
```

#### Add OS.get_version

```gdscript
String get_version ( ) const
# Returns the OS' actual technical version number and not its user-friendly version used in marketing. This helps distinguishing between minor versions or even insider and custom builds.
# For Windows this returns e.g. version `10.0.9926` instead of `10`, and `6.0…` instead of the marketed version `Vista`.
# For rolling distributions, such as Arch Linux, it returns an empty String.
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Cannot be worked around with a few lines. Would require system calls which are OS-specific.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving collecting system info for video games, apps and Godot itself (at least giving Godot the potential to copy&paste system data in github issues - which should be approached in a separate proposal).

**Comment by MJacred** [comment]
### Or alternatively…

return values such as `Ubuntu`, `Mageaia`, etc. in `get_name()`, reduce `get_version()` to really only version (yes, that would return for Arch Linux an empty String)

and add new func `get_os_family_name()`
* would return empty String for Windows
* but for Linux:  `Ubuntu`, `Mageaia`, etc
* but for BSD: `FreeBSD`, etc.
* and argue about what iOS, macOS and Android should return

**Comment by Calinou** [comment]
> `get_name()` returns values such as

No, I don't think `OS.get_name()` should return anything but the name of the platform Godot was compiled for. A lot of people rely on the existing behavior.

There could be `OS.get_distribution_name()` and `OS.get_version()` methods, but I wouldn't go any further. As for getting the display server's name, this should be `DisplayServer.get_name()` instead :slightly_smiling_face:

**Comment by MJacred** [comment]
I find your mentions and suggestions totally fine.

For Windows, I'd also prefer the actual version numbers.

**Comment by MJacred** [comment]
@Calinou: ok, I finished rewriting the proposal. It should not break compatibility now.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/65525.
