### ISSUE TITLE
Default GI & ambient inject value for volumetric fog should be 1

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#5024]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Not taking ambient and GI into account by defaults means the fogs look kind of unnatural by default as they are not picking up ambient lights.

Default:
![image](https://user-images.githubusercontent.com/25323231/181934953-0c05ed0e-a9f0-40f4-b8d8-ab1b1d087d72.png)

Ambient Inject at 1:
![image](https://user-images.githubusercontent.com/25323231/181934969-7355e3c6-542c-439f-bb1c-2c568e9ff002.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Increasing the inject values to at least 1 make the fogs look much better. Maybe someone can come up with better defaults but 1 works for me.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Changing default values should be super simple but I don't know where they're defined.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Can probably work with a singleton hooked with certain signals that are emitted after scene loads.

### Is there a reason why this should be core and not an add-on in the asset library?

Improving the default values is the better choice in my opinion.

**Comment by Calinou** [comment]
GI Inject greater than 0 has a performance cost, so I don't think it should be enabled by default.

Ambient Inject greater than 0 also has a performance cost (slightly lower than GI Inject), but it can cause volumetric fog to "leak" in indoor portions of a level. Therefore, I'd prefer it to remain disabled by default as well.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/55276, although Ambient Inject remains 0 for the reasons I mentioned here.
