### ISSUE TITLE
Add a way to show a resource in FileSystem by selecting its uid in ScriptEditor

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#5028]
### Describe the project you are working on

Games

### Describe the problem or limitation you are having in your project

If there is uid in the code, you may want to quickly jump to the file in Godot FileSystem.
The feature could work with https://github.com/godotengine/godot-proposals/issues/5027

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A way to show a resource in FileSystem for example by selecting its uid in ScriptEditor when RMB and selecting "Show in FileSystem" would solve the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Select  the code like "uid://btj0bxdws38cd" then RMB then select "Show in FileSystem"
Or just put a caret insid the uid string then RMB then select "Show in FileSystem"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

A plugin can help, but not with a few lines tho

### Is there a reason why this should be core and not an add-on in the asset library?

I think the feature will be popular

**Comment by KoBeWi** [comment]
Implemented by https://github.com/godotengine/godot/pull/81927
