### ISSUE TITLE
Warn when void function's result is assigned to a variable

### ISSUE THREAD

**Issue by DanaFo** [godotengine/godot-proposals#5037]
### Describe the project you are working on

I'm just having fun moving sprites around in 2d.  This arose when I was calculating a vector to a target relative to the self.

### Describe the problem or limitation you are having in your project

For an hour or so I could not figure out why ptVelAngle here was no getting a value.  There was no error or warning via vs code/godot plugin so I was doing alot of weird testing to figure it out.  
var ptVelToAngle = _get_target_velocity(targetAcquired)

The definition (lol):
func _get_target_velocity(target):
	enemyVelocity = target.get_global_position() - global_position
	
So I mean it's obvious that it's not returning anything, but why am I not getting a warning or error?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This case should generate an error, feels like it could cause catastrophic issues.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Whatever godot's error system looks like on play/debug.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

n/a

### Is there a reason why this should be core and not an add-on in the asset library?

Don't think so.

**Comment by Calinou** [comment]
Your `get_target_velocity()` function lacks a type hint. Try adding a `-> void` return type hint to its definition.

**Comment by DanaFo** [comment]
> Your `get_target_velocity()` function lacks a type hint. Try adding a `-> void` return type hint to its definition:
> 
> ```gdscript
> func _get_target_velocity(target) -> void:
> ```

So the real issue here is I forgot a return 'value' statement and I didnt' get a notification.  ie:
func _get_target_velocity(target):
enemyVelocity = target.get_global_position() - global_position
return enemyVelocity

**Comment by Calinou** [comment]
> So the real issue here is I forgot a return 'value' statement and I didnt' get a notification. ie:

GDScript is a dynamically typed language with *optional* static typing, so that's expected. There's work being done to add an optional warning when type hints are missing: https://github.com/godotengine/godot/pull/59428

**Comment by DanaFo** [comment]
> > So the real issue here is I forgot a return 'value' statement and I didnt' get a notification. ie:
> 
> GDScript is a dynamically typed language with _optional_ static typing, so that's expected. There's work being done to add an optional warning when type hints are missing: [godotengine/godot#59428](https://github.com/godotengine/godot/pull/59428)

Right, I understand now, I'm so used to c# lol.  thank you for your time.
