### ISSUE TITLE
Rename ParticleMaterial to ParticlesProcessMaterial

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#5047]
### Describe the project you are working on

Various VFX and Godot

### Describe the problem or limitation you are having in your project

Process material is a confusing name. Especially if we add another particle-first material (https://github.com/godotengine/godot-proposals/issues/5046) it could get confusing very fast.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename ParticlesMaterial to ~~ParticleMotionMaterial~~ ParticlesProcessMaterial

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's the name of a resource in godot

### Is there a reason why this should be core and not an add-on in the asset library?

It's the name of a resource in godot

**Comment by Mickeon** [comment]
I know it's been two weeks but **ProcessMaterial** is not a thing in Godot 4, did you mean **ParticlesMaterial**?

**Comment by QbieShay** [comment]
Ohw that's embarassing ahah
I'll fix the proposal

**Comment by Mickeon** [comment]
Just making sure, I was about to be up for the task!

**Comment by QbieShay** [comment]
@Mickeon thanks for working on this, although please beware that this hasn't been officially approved, so it could be that your PR won't be merged. Either way, thanks a lot for putting the time and effort.

**Comment by Mickeon** [comment]
I didn't do it for approval, I did it for completion's sake.

**Comment by Zireael07** [comment]
Hm, one counter point to this that has been raised in the PR is that the material affects more things than just motion...

**Comment by Mickeon** [comment]
I don't think this rename will go through. It looks controversial, and the rename is too verbose.

**Comment by QbieShay** [comment]
> Hm, one counter point to this that has been raised in the PR is that the material affects more things than just motion...

It does but I didn't find a term that's as intuitive and short at the same time

**Comment by clayjohn** [comment]
My preference is for ParticleProcessMaterial. While verbose its clear and process material is the naming we using within the GPUParticles node to begin with.

**Comment by Mickeon** [comment]
@QbieShay Changing this proposal's entire purpose through an edit is not... exactly fair game for anyone that has voted prior.

**Comment by clayjohn** [comment]
> @QbieShay Changing this proposal's entire purpose through an edit is not... exactly fair game for anyone that has voted prior.

Don't worry. Votes just help us determine how much interest a proposal has. They are not used as a means to decide whether a proposal is accepted. In this case my last comment has almost as many reactions as the original proposal, so it's not a big deal either way

**Comment by QbieShay** [comment]
Sorry @Mickeon ! I didn't mean to disrupt anything. But i thought, as new consensus is reached, it's easier to read on the original post. next time i'll make clear what is an edit.
