### ISSUE TITLE
Add annotations to the core ClassDB/Object/Script API.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot-proposals#5052]
### Describe the project you are working on

Plugins for use by GDScript, C#, and other possible languages.

### Describe the problem or limitation you are having in your project

Godot 4.0 adds annotations to GDScript, so the two primary scripting languages (w/ C#) will both support them. Godot 4.0 also adds the ability for Scripts to contribute to the engine's internal documentation system. Unfortunately, the documentation system is powered directly by the Object / Script APIs' property/method/signal/constant content. That means that neither the built-in annotations being added to GDScript nor any custom annotations you add to C# or possibly add to GDScript (once custom annotation support is added) can be documented by the core engine or addon/plugin developers.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Update the core API to include annotations as part of the content that an Object or Script can describe, and then update the documentation systems / GUI to incorporate annotations into their rendering. Since annotations themselves never involve any data per instance, this should mostly be stuff that shows up on `ClassDB` and `Script` + derivatives.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

More or less, mimic how `PropertyInfo` is defined, stored, exposed, and used elsewhere in the engine, but do it for `AnnotationInfo` instead and only apply it at the `ClassDB`/`Script` level, not at the `Object` or `ScriptInstance` level. Use your brain to figure out where the update isn't really applicable. That should cover most places where it would be relevant such as `object.h`, `script_language.h`, the GDExtensions API, anything involving the editor or `DocData`, places in `gdscript.h` and `gdscript_parser.cpp` where you'll have to tie GDScript's annotations into the core representation of them. Etc.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Core engine changes. Not exposed to script.

### Is there a reason why this should be core and not an add-on in the asset library?

Core engine changes. Not exposed to script.

**Comment by YuriSizov** [comment]
> That means that neither the built-in annotations being added to GDScript

Built-in annotations are already documented.

**Comment by willnationsdev** [comment]
@YuriSizov Oh! This is good to know. And yeah, that actually makes a lot of sense. I simply didn't realize that that had all already been implemented. Nevermind then. I'll close this. :-D
