### ISSUE TITLE
backport Image.save_jpg_to_buffer from Godot 4 to Godo 3.5

### ISSUE THREAD

**Issue by skadge** [godotengine/godot-proposals#5059]
### Describe the project you are working on

I'm developing a websocket bridge between Godot and the [robotics middleware ROS](www.ros.org). I want to use Godot as a robotic 'simulator' and I need to efficiently export OpenGL cameras texture outside of Godot, via websockets.

### Describe the problem or limitation you are having in your project

In Godot <=3.5, only `Image.save_png_to_buffer` is available to export a texture to a byte stream that can be send over the wire. PNG are large, and the performance is poor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot 4 adds `Image.save_jpg_to_buffer` (introduced by @reduz in https://github.com/godotengine/godot/commit/5786516d4d6b517e6a28aec191f944aecf2f544d). It would allow to generate much smaller images, better suited for streaming.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My proposal is to backport the feature from Godot 4 to Godot 3.5.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it is actually difficult to encode an image to a jpg buffer without that API (short of saving a jpg as a file, and re-opening it, which would be inefficient)

### Is there a reason why this should be core and not an add-on in the asset library?

(NA as backport proposal)

**Comment by YuriSizov** [comment]
You don't need a proposal to backport a non-compatibility-breaking feature (and breaking features are not considered for 3.x anyway). Feel free to open a PR that adds support for saving JPG images (as this is not just `save_jpg_to_buffer`, it's `save_jpg` as well).

> PNG are large, and the performance is poor.

Note that the feature in 4.0 is not aiming to be quick either, as MovieWriter is used to capture gameplay at a fixed video framerate and not in real time.
