### ISSUE TITLE
Greatly improving readability of Visual Scripting in Godot 3.2

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#506]
**Describe the project you are working on:**

I am working on a Tomb Raider project, with a new character, and I can only use Visual Scripting, as a beginner, and will use it to learn code, over time . . Also, an RTS-like game, StarCraft inspired . . .

**Describe the problem or limitation you are having in your project:**

When I make boxes in Visual Script, the arrows are all over the place, and it ends up looking like this . .

![2020-02-23 0306 Visual Script Proposal](https://user-images.githubusercontent.com/61069740/75102295-89735780-55e9-11ea-8422-18c264b94dea.png)

I want to make it look as much as possible, as normal writing, with the ' black ' lines going directly through, so it reads like a flow-chart, very easily read, in engine . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

It would be a lot easier, if one could change the position, of the input, and output node, in the Visual Script boxes, like this . . .

![2020-02-16 0457](https://user-images.githubusercontent.com/61069740/75102307-d48d6a80-55e9-11ea-9d63-1374cb08af3e.png)

![2020-02-16 0507](https://user-images.githubusercontent.com/61069740/75102308-d5260100-55e9-11ea-924f-64839d1c3d06.png)

Especially, if there was a little button in the corners, of each node, where you click it, and the input side switches from top-side-left-right . . Like this . . .

![2020-02-23 0319](https://user-images.githubusercontent.com/61069740/75102419-6a75c500-55eb-11ea-9b22-5a0f6c9949cf.png)

Also, if the other inputs, could somehow be moved around, a purely visual update, no changes to the code framework, behind it, it would make visual scripts look much nicer, and be much easier to read, for any team, in the world, also for me, who can't code YET, but need Visual Script to build my first games, and learn code, as I watch Godot, on youtube . . Ideally, one would be  able to change the input anywhere, perhaps by giving everything a different color, like this, everything can be moved to one of four sides, of the nodes, just a visual thing, to make nicer flow-charts . .

![2020-02-16 0507](https://user-images.githubusercontent.com/61069740/75102442-c50f2100-55eb-11ea-9af7-8905b225ca6c.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Well, it's not a big change, to the code, in Godot, more of an update to a few visual tweaks, on the boxes, in visual script . . But, a programmer needs to do it, and I think everyone using visual script, either for their games, or for learning Godot, will have a much easier time, if this was possible, but done well, by good programmers, Godot-experts . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

As a beginner, I can't do this . . It would take a lot of work, for me, too much . . :(

**Is there a reason why this should be core and not an add-on in the asset library?:**

Every single person wanting to make Godot games could benefit from this, and Visual Script could become a nicer way, for people to get into Godot, so more people would like the engine, especially artist-minded people, but also new people, that want to learn coding through Visual Scripting, in the beginning . . Also, with nicer flow-charts, productivity might increase for bigger teams, where artists could make better ' visual ' coding, and in the end, mean more games . . Also, people wanting to learn Godot, but scared of code ( like me ), would have an easier way of learning node names, for later coding, if visual script was even MORE appealing, like it is now, really good . . This feature would just make the scripts 200 % more readable, and make Godot more appealing, to the world, to game makers, on all levels . . But, it has to be done well, my suggestion is pretty rough, a smart coder, or Godot-expert could probably make this nicer, so the charts read MUCH nicer, also for programmers . .

**Comment by jasperbrooks79** [comment]
Add : If this could be done well, the flow-chart in visual script would be so much easier to read, even programmers, and code-masters would find them more enjoyable, and that means more artists can contribute to games, and so make more games, and Godot will become the place, that has the best Visual Script environment, benefitting the engine . .

**Comment by jasperbrooks79** [comment]
Here's sort of a proposal, for how it could be done . .

![2020-02-23 0344 Godot Suggestion Idea](https://user-images.githubusercontent.com/61069740/75102653-65b31000-55ef-11ea-9015-ba6b5ef253e9.jpg)

![2020-02-23 0347 Godot Suggestion Idea](https://user-images.githubusercontent.com/61069740/75102654-664ba680-55ef-11ea-87e4-569400a4566f.jpg)

By changing the ' structure ' of the nodes, the visual script ' boxes ', so they have an ' outer ' layer, and ' middle ' layer, and a ' center ', the ' inputs ' and, ' outputs ' could be moved there, and if one could change the color of the boxes, in a setting manager, like make add boxes blue, or green, instead of red, scripts could be a lot easier, to read, also for coders, and artists could have more fun . . I think, everyone would win, and more people would get into Godot, enjoy it . .

**Comment by jasperbrooks79** [comment]
Here's a first, quick suggestion, for how the boxes could look . .
![2020-02-23 0431](https://user-images.githubusercontent.com/61069740/75103028-69499580-55f5-11ea-95ed-3af298be9897.jpg)

So, if a box takes a bool, it has a unique ' dot ', for the arrow to connect, that can be moved around the node, just a visual change, no change to what the node does, or hard code . .

**Comment by jasperbrooks79** [comment]
If the grid was made a bit smaller, the boxes could move the ' inputs ' on the grid, and all the lines would be vertical, for all boxes, in Visual script, like this . . .

![2020-02-23 0501](https://user-images.githubusercontent.com/61069740/75103372-fee72400-55f9-11ea-96ad-6d4ac26d728f.jpg)

ps. Sorry for the many posts, I have some mental issues, OCD, PTSD . . :(( <3

**Comment by jasperbrooks79** [comment]
Maybe the boxes ( visual script nodes ) could look like this, where one could click a button, to edit how they ' look ', on each box . .

![2020-02-23 0527](https://user-images.githubusercontent.com/61069740/75103617-710d3800-55fd-11ea-82e6-2c63464f6596.jpg)

So, they follow the grid ( the grid could be made smaller ), and still was readable, and one could resize the boxes, as needed . . Anyway, I would like that, it would really help, at least for me, maybe other artists, noobs, beginners <3

**Comment by aaronfranke** [comment]
So what you're basically saying is that you want the ability to move input and output "dots" and arrows to arbitrary places around the edge of each VisualScript "box"?

**Comment by jasperbrooks79** [comment]
Yes, that way the scripts can be a lot easier to read, like in this picture . .

![2020-02-23 0638](https://user-images.githubusercontent.com/61069740/75218129-9040cc80-5799-11ea-8201-7ec1ff478be0.jpg)

That way, all the scripts would look like this . . .

![2020-02-23 0417](https://user-images.githubusercontent.com/61069740/75218153-a8185080-5799-11ea-969a-f27bc46c92f5.jpg)

**Comment by jasperbrooks79** [comment]
Like, an architect sketch . .
![2020-02-25 0651](https://user-images.githubusercontent.com/61069740/75218829-7d2efc00-579b-11ea-81f1-b40f9260ca04.jpg)

![2020-02-25 0652](https://user-images.githubusercontent.com/61069740/75218830-7ef8bf80-579b-11ea-9acd-2b434a9cbe97.jpg)

**Comment by Jummit** [comment]
I think having the flow in visual scripts on both axis would make them harder to read, but I haven't tried it, so I don't really know for sure.

**Comment by jasperbrooks79** [comment]
The problem right now is, the main lines look like this, and it gets hard to read, because it's not natural for eyes to read a chart, like this . .
![2020-02-28 0246](https://user-images.githubusercontent.com/61069740/75502979-a5ee0600-59d4-11ea-9473-f085acf5a616.jpg)

It just gets confusing, especially with big scripts, it's like it's ' not logical ', that it looks like this . .

To make it look more like a chart, more ' organized ', into logic, this would be nicer, I use it all the time, and one of the reasons they are so hard to read, especially later, is that the lines flow in a ' confusing ' way, compared to logic . . This would be more readable, to analytical minds, and also be beautiful, to artists, non - coders . . .

![2020-02-23 0413](https://user-images.githubusercontent.com/61069740/75503071-f2d1dc80-59d4-11ea-9b92-be56b32c30d4.png)

Ideally, one wants the ' main ' line to be logical, and be easily identifiable, right now it sort of ' disappears ', in all the lines . . It would just be easier to read, if it was more ' linear ', one would always know where to look, when looking at a particular box, or node, if the lines could be straight, ' run ' through . . For me, it would make them more like a schematic, and make reading scripts almost twice as easy, and natural . .

**Comment by jasperbrooks79** [comment]
Here's how I think the boxes should look like, roughly . . The ' bendy ' lines are ' inside ' the nodes, and the charts are more ' linear ', but still visually appealing, beautiful . .

![2020-02-28 0303](https://user-images.githubusercontent.com/61069740/75503836-1a29a900-59d7-11ea-963e-d8667c105c71.jpg)

I should still be appealing to artists, by making the whole things look like a nice architect chart . .
![2020-02-28 0307](https://user-images.githubusercontent.com/61069740/75504015-886e6b80-59d7-11ea-89fc-8c739d3f7ca4.jpg)

It would be both logically, and aesthetically pleasing, in the end . .

**Comment by Gianclgar** [comment]
I would suggest taking a look at [Cycling74's Max](https://cycling74.com/products/max) programming environment and visual programming. And also it "original" open-source origins [(Pure Data)](https://duckduckgo.com/?q=pure+data&t=brave&iax=images&ia=images&iai=http%3A%2F%2Fbooki.flossmanuals.net%2Fpure-data%2Fdataflow-tutorials%2F_booki%2Fpure-data%2Fstatic%2FPureData-DataFlow-send_receive_delays-en.png) 

It's a different concept, as it's oriented to real-time audiovisual programming. But they managed to make visual programming in a very intuitive way, and also has an "abstraction" system that expands a lot its possibilities. Also the programming system itself is highly customisable. For more visual people like me it meant a lot and got me into programming from a totally different perspective. So sad Max it's paid and closed-source. 

I think it would be awesome if Godot VisualScript becomes more "Max-ish" and would be really happy to contribute to that.

I'm attaching a few screenshots for visual reference. The first ones from Max help files (equivalent to control-click anything in GDScript) and the rest from programs I made.

![Captura de pantalla 2020-04-02 a las 8 25 50](https://user-images.githubusercontent.com/20739619/78217962-4bf1cc00-74bd-11ea-91e2-ce52dc5587a6.png)
![Captura de pantalla 2020-04-02 a las 8 26 03](https://user-images.githubusercontent.com/20739619/78217985-5318da00-74bd-11ea-883a-cb5696b58134.png)
![Captura de pantalla 2020-04-02 a las 8 26 44](https://user-images.githubusercontent.com/20739619/78217998-5a3fe800-74bd-11ea-9a6e-6d22813fecfd.png)
![Captura de pantalla 2020-04-02 a las 8 24 06](https://user-images.githubusercontent.com/20739619/78218026-662baa00-74bd-11ea-8467-aa1dbdd7d098.png)
![Captura de pantalla 2020-04-02 a las 8 24 27](https://user-images.githubusercontent.com/20739619/78218042-6d52b800-74bd-11ea-9717-7ce7476328ac.png)
![Captura de pantalla 2020-04-02 a las 8 25 14](https://user-images.githubusercontent.com/20739619/78218067-780d4d00-74bd-11ea-9910-390fce670352.png)
![Captura de pantalla 2020-04-02 a las 8 24 37](https://user-images.githubusercontent.com/20739619/78218084-7f345b00-74bd-11ea-8068-631c11b69eba.png)

**Comment by Gianclgar** [comment]
I think the two key aspects for improving readability are the "patchcord" system (where you can define the path of the connections, as they are objects on its own, and even have an "automatic routing" option), and the order of execution based on top-to-bottom.

I've been doing some research and reverse engineering and found this:

-Boxes are just compiled chunks of code, mostly made in C or C++
-[Max itself is written in C++ using JUCE framework](https://juce.com/discover/stories/building-max-with-juce)

Then I started looking for the savefiles (patches) it self and found that tey're just JSON files with the extension changed to .maxpat

![Captura de pantalla 2020-04-02 a las 8 51 16](https://user-images.githubusercontent.com/20739619/78219183-4d23f880-74bf-11ea-98db-4058ed2b2f98.png)

![Captura de pantalla 2020-04-02 a las 8 52 00](https://user-images.githubusercontent.com/20739619/78219154-3f6e7300-74bf-11ea-98e2-607927f5f785.png)

While VisualScript files look like this (Binary hex?)
![Captura de pantalla 2020-04-02 a las 9 02 06](https://user-images.githubusercontent.com/20739619/78219983-f7e8e680-74c0-11ea-9618-167961d5dee6.png)

Then just took me a few hours (maybe it would have been minutes if I remembered the most basic code-programming stuff) to make a very basic godot program that opens a .maxpat file and replicate some aspects of its elements:

![Captura de pantalla 2020-04-01 a las 18 13 26](https://user-images.githubusercontent.com/20739619/78219493-ea7f2c80-74bf-11ea-9bf8-080f0907d3e9.png)

I'm not saying Godot VS should be like Max, as they are different approaches for different "problems" but it could be use a nice reference for improving readability and it make Godot EVEN MORE accessible.

**Comment by fire** [comment]
You can decode visual script files by saving them as tres. @Gianclgar

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
