### ISSUE TITLE
Change linear2db to return -60.0 when inputted 0.0

### ISSUE THREAD

**Issue by Master070900** [godotengine/godot-proposals#5065]
### Describe the project you are working on

Recently I have started to work on adding a audio system to my game. I was using the new Tween system added in Godot 4.0 to make the audio slowly fade in and out.

### Describe the problem or limitation you are having in your project

I figured I could do something like this:
```
var tween = get_tree().create_tween()
tween.tween_property(old_player, "volume_db", linear2db(0.0), change_time).from(linear2db(1.0))
tween.parallel().tween_property(current_player, "volume_db", linear2db(1.0), change_time).from(linear2db(0.0))
```
The only problem is, current `linear2db(0.0)` returns `-inf`, not allowing the tween to change the value of `volume_db`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Changing `linear2db(0.0)` to return `-60.0` or whatever is set in the project settings (`audio/buses/channel_disable_threshold_db`) would fix this issue. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
print(linear2db(0.0)) # -60.0
print(linear2db(1.0)) # 0.0
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can work around this issue by not using Tweens, but I feel as if that would be more of a headache to work around.

### Is there a reason why this should be core and not an add-on in the asset library?

An add-on seems overkill to change one thing.

**Comment by Calinou** [comment]
> Changing linear2db(0.0) to return -60.0 or whatever is set in the project settings (audio/buses/channel_disable_threshold_db) would fix this issue.

I'm not fond of making behavior of core math functions depend on project settings. If we carry ovr with this change, we should use a fixed value like -80 dB (which is silent on pretty much any hardware).

**Comment by JoNax97** [comment]
Couldn't this issue be worked around by keeping from a very small value (say 0.001) instead of 0?

It feels wrong to change a well known, mathematically correct implementation to fit a specific use case.

**Comment by Master070900** [comment]
> Couldn't this issue be worked around by keeping from a very small value (say 0.001) instead of 0?
> 
> It feels wrong to change a well known, mathematically correct implementation to fit a specific use case.

I guess you could do that, didn't really think of it when I made the issue.

**Comment by Master070900** [comment]
Actually, just thought that maybe this could be an issue to fix. That Tweens are not able to change values from `-inf` or `inf`?

**Comment by YuriSizov** [comment]
You can interpolate a method instead of a property, so your interpolated value is between 0 and 1, and the method converts linear to db and assigns it to the bus.
