### ISSUE TITLE
Expose Options-Drop-Down in Visual Shader CustomNodes

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot-proposals#5075]
### Describe the project you are working on

Visual Shader Library add-on

### Describe the problem or limitation you are having in your project

When writing several noise functions that all have the same inputs but where there could be several options for a single input it's extremely cumbersome to write a new CustomNode for every possible combination.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

What I invision is that it makes it way easier to use different variations of ShaderFunctions that have the same input and are topic-bundled anyway. These could then be bundled in one Shader CustomNode.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The API to get this to work could look similar to the one in [visual_shader_nodes.cpp](https://github.com/godotengine/godot/blob/8cce479c01f73b7f0b65e65a431bc4d0312db00e/scene/resources/visual_shader_nodes.cpp). 
The visuals would work like this as well:
![image](https://user-images.githubusercontent.com/38077837/182931649-c7bd29e7-58ac-40f5-acdd-1aa4ec2a6b09.png)

Blender version:
![image](https://user-images.githubusercontent.com/38077837/182932060-b080d826-738f-4db8-ab6d-5af53e95d269.png)
![image](https://user-images.githubusercontent.com/38077837/182932099-9419aeb2-b165-4f15-833a-ebe2c385fae0.png)
![image](https://user-images.githubusercontent.com/38077837/182932120-dbd59192-57b9-4ad0-9112-1f1e9506f2ed.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, since it's a proposal to actually expose this to GDScript and to make it available for add-ons

### Is there a reason why this should be core and not an add-on in the asset library?

See above

**Comment by Chaosus** [comment]
Yes, this sounds like a not bad idea. I would propose the new functions like `add_drop_down_list_property(name, options, caption_visible)`/`get_drop_down_list_property(name)`. I may try to implement them if you wish...

**Comment by paddy-exe** [comment]
> Yes, this sounds like a not bad idea. I would propose the new functions like `add_drop_down_list_property(name, options, caption_visible)`/`get_drop_down_list_property(name)`. I may try to implement them if you wish...

That would be awesome if you could give it a go. I would be happy to review/test the PR then
