### ISSUE TITLE
Add a map/remap function to simplify remapping/rescaling values

### ISSUE THREAD

**Issue by alxpettit** [godotengine/godot-proposals#5077]
### Describe the project you are working on

An open source VR environment that makes use of a lot of dynamic graphical effects

### Describe the problem or limitation you are having in your project

There is no `remap` function that we've been able to find, so for the time being we've had to make one ourselves as boilerplate.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Reduces boilerplate, improves the cohesion of the communities' codebase, and may improve readability in some projects.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# remaps color for health bar in a minigame,
# to make it become progressively more red as health drops
# Arguments: min_a, min_b, max_a, max_b, input
var health_bar_red = remap(0, 255, 0 1000, health)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

My guess is that it will be used very often. There is probably at least one use case for it in every project. It can be worked around with a couple lines of code... or implementing the function yourself... or worse yet, combining `lerp` and `inverse_lerp` without the context of the purpose, thus significantly degrading the readability of your function to those who aren't familiar with the use case.

### Is there a reason why this should be core and not an add-on in the asset library?

My concern is slightly improving out-of-the-box tools available. A trivial function that's used constantly, being reimplemented hundreds of times across many different projects can add up in terms of inefficiency and duplication of effort. It also leads to inconsistencies in convention. Does the Godot community call this function `map`, `remap`, or `rescale`? Does the input value go in the beginning or end of the argument list? Does it use scalar floats or range objects?

Going from one project to another can get that little bit more difficult if the rules change -- whereas, if the toolset already provides a solution, it provides a convenient focal point for the community, as well as a piece of common terminology around which we can organize technical documentation and explanations.

**Comment by Calinou** [comment]
Have you tried `range_lerp()`?

**Comment by RedMser** [comment]
Having searched for this method in the past without success (also searching "map", "remap"), I am surprised to see it already implemented. I wonder how to make it easier to find a method without knowing its full name, since searching for similar terms in the docs site yields way too many results.

Additionally, `range_lerp` does not exist in (visual) shaders. Lerp is also called "Mix" in visual shaders, might be worth considering a synonyms system for the visual shader nodes search...

**Comment by Calinou** [comment]
> I wonder how to make it easier to find a method without knowing its full name, since searching for similar terms in the docs site yields way too many results.

Keyword aliases could be supported for individual properties/methods in the class reference, in the form of an optional `keywords="keyword1, keyword2"` attribute in the XML. This would be used for matching results in the editor help search.

**Comment by Mickeon** [comment]
I was about to say that `range_lerp()` exists and does what's required already, but something about `remap()`... It sounds cleaner, more to the point... more user-friendly, even if it's not the common term.

**Comment by alxpettit** [comment]
`range_lerp` does indeed do what we wanted! We had no idea that function existed, but I'm happy that we know about it now :D

I was thinking about it in terms of rescale or `remap`, owing to the function being named along those terms in the [Arduino framework](https://www.arduino.cc/reference/en/language/functions/math/map/), alongside community discussions on broader game design and game engine math.

It's notable that if you look this stuff up, as of today, you won't find much on `range_lerp` but you'll find an awful lot of tutorials/instructions/suggestions to [implement it yourself](https://victorkarp.com/godot-engine-how-to-remap-a-range-of-numbers/), which suggests to me that a _lot_ of people don't know about this. (Although to be fair, many of them may predate the addition of the function.)

Since the specific subject of this issue isn't applicable, I'll go ahead and close it, but I'm happy that it helped contribute to a discussion on improving the discoverability of Godot features and toolsets! :)
