### ISSUE TITLE
A better instance system

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#509]
**Describe the project you are working on:**

A Tomb Raider game, but also a RTS, like StarCraft . .

**Describe the problem or limitation you are having in your project:**

I have a lot of problems, as a beginner understanding, why I should make a new scene, to create what's an instance, in other programs, as I see it, scenes are more correctly ' levels ', and I would like to make it like that, and make smaller scenes, potentially, as sub-levels, or nested stages . .

I would like an ' instance ' dock, where I can make an instance, or move a ' tree ', from the scene view, and make an instance, like this . . Right now, there's a movie icon, referring to a ' scene ', or stage next to ' child scenes ', and it gets very confusing, also having to save a new hard-disk file, every-time I want to make a new ' instance ' . . It works, but it's not friendly, for noobs . . Basically, I would like a new dock, called the ' instance ' dock, similar to the ' scene ' dock, but where one can create instances, or ' trees ', of nodes, and drag them into the main 3D window, like an object . . When that happens, it creates an instance, with it's own rotation, location, scale, that gets updates everytime the ' instance ' is change, and appears in the ' scene ' dock, as maybe Tree1, if the instance is called Tree . . More beginner friendly, right now it feels contra-intuitive, to use ' scenes ' ( which means levels, in my mind ), and also having to click the ' movie editor clapboard ', which I want to modify an instance . . If one clicked an ' instance ', in the scene, it could have an icon next to, that opens the instance, or selects it, in an ' instance ' dock . . For me, it would make Godot a lot easier to use, one could also call them ' original ', ' templates ', or ' prefabs ' . . Or, ' Parent Entity ' . .? So, when one makes an instance, one does not have to save a new file, and name it, and keep track of it, it's just another ' object ', of a slightly different kind, or construction . . Right now, it feels as if Godot is working a bit against me, when I want to make an ' instance ', or ' original reference ', and I would like to suggest an update, to help people . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

It would make it a lot easier to make a level, and make games . . . Right now it feels like one is doing it the wrong way, and it pushes new users away, sadly . . It could be improved, anyway I'm suggesting it, if possible . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I think you just need to create another ' scene ' dock, with some added features, to make instance, or ' originals ' . . ' referenced objects ' . . And, add a menu right-click, to the ' scene ' dock, so if you select some nodes, a ' tree ', and right-click, you can select ' make new instance ', and it gets moved, to the ' instance ' dock, or so . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I think most users would use it all the time, I would, and it would make Godot a lot nicer, for new users, especially . . Also, experienced users might find it nice, as well . .

**Is there a reason why this should be core and not an add-on in the asset library?:**

It would make Godot a lot more appealing, user-friendly, and ' fast ', for making stuff . . . :)

A suggestion, for what the ' instance ' icon could look like . .

![2020-02-23 0939](https://user-images.githubusercontent.com/61069740/75106669-51870700-561f-11ea-9c12-50128c3ef3de.jpg)

Other than that, Godot is pretty much perfect, we only need more Godot, fast . . It's good program, really nice . . :) <3

**Comment by pycbouh** [comment]
I find it hard to understand, what exactly is your problem and what do you suggest, but...

Scenes are not "levels" or "stages". Not in Godot. In Godot a "scene" is an abstraction of some functionality. A player entity can be presented as a scene. Some pure logic can be packed into a separate scene as well. You should not think about "scenes" as you think about stages and levels, or movie scenes. You should think about them as components.

If there is something you still find in need of improving, can you better explain your proposal? Maybe structure it a bit clearer and add some visual examples?

**Comment by KoBeWi** [comment]
If you can't understand the scene/node system, you should [try to read documentation first](https://docs.godotengine.org/en/latest/getting_started/step_by_step/scenes_and_nodes.html#introduction) instead of proposing a change to the whole system. Majority of users find the scene system intuitive and even praise it saying it's better than in other engines.

What you are proposing is already there. You can save nodes as prefabs, but instead of storing "instances" in "instance tab", you store scenes as files and then you instantiate scenes from files. It's really intuitive when you give it a try. It *might* be problematic when you want to create lots of instances, but things like painting scenes on a TileMap (to make something similar to Game Maker) were already proposed.

**Comment by jasperbrooks79** [comment]
I know it's already there, but it's an uphill fight, I think it could make the software nicer, more user-friendly . . But, I know it's already there, it's just difficult for new users to understand, want to make an instance, that they have to make a scene, and make a file . . It shouldn't be necessary . . .

**Comment by akien-mga** [comment]
The scene instancing system is good as it is, what you suggest would only make it match your own understanding of a level / instance paradigm, but that's not what the scene system is.

As mentioned, this is covered in the docs, and while it might not be very easy to understand for a beginner, most things in programming aren't. It takes patience and work to reach a good understanding of the underlying concepts.

**Comment by akien-mga** [comment]
Please note that this repository is for technical proposals from users who already have a good understanding of the engine, and a good vision of how to improve what they are already experienced with. General ideas on how to simplify something that you do not understand fully are not constructive for engine developers, and better discussed more loosely in community channels such as the Facebook group or Discord.
