### ISSUE TITLE
Improve EditorScenePostImport/EditorScenePostImportPlugin processing discrepancies

### ISSUE THREAD

**Issue by dpalais** [godotengine/godot-proposals#5093]
### Describe the project you are working on

A 3D game with stylized NPR materials and a library of assets for modular characters. Repetitive asset import work is automated with import scripts and plugins.

### Describe the problem or limitation you are having in your project

My project relies on **EditorScenePostImportPlugin** to automate the setup of 3D assets by creating materials, cleaning up the scene tree of undesirable nodes, and other things. By cleaning up undesirable nodes I mean removing nodes from the tree, including the scene root node. For example, I import a 3D asset as a single **Skeleton3D** node tree. For this I use the following **EditorScenePostImport** script:

```gdscript
tool
extends EditorScenePostImport

func _post_import(scene):
	var skeleton : Skeleton3D = scene.find_child("Skeleton3D")
	var parent : Node3D = skeleton.get_parent()
	
	skeleton.position = parent.position
	
	for child in skeleton.get_children():
		skeleton.remove_child(child)
		child.free()
	
	parent.remove_child(skeleton)
	scene.free()
	
	return skeleton
```

Ideally you should be able to do everything **EditorScenePostImport** can do with **EditorScenePostImportPlugin**, but the feature of selecting the scene root node isn't there on the latter.

Another problem I noticed when using both classes with the same asset at the same time is that the execution of **EditorScenePostImport** occurs in the middle of **EditorScenePostImportPlugin** processing, which can lead to unexpected behavior for the latter. After **EditorScenePostImport**'s `_post_import` runs and potentially returns a radically different scene tree, only then does **EditorScenePostImportPlugin**'s `_post_process` begin execution. This can be a problem when the plugin hasn't been able to finish its node processing.

Additionally **EditorScenePostImport** has `get_source_file` which lets the import script be aware of the imported scene source file location and save extra resources relative to it.

The implementation of this proposal may make **EditorScenePostImport** redundant in favor of its more capable cousin.

#### EditorScenePostImport runs before EditorScenePostImportPlugin post_process
EditorScenePostImport's `_post_import` should run after all the EditorScenePostImportPlugins have run `_post_process`

#### EditorScenePostImportPlugin doesn't allow to change the scene root
Add a `get_custom_scene_root` method to EditorScenePostImportPlugin with the same parameters as `_post_process` but it returns a Node that replaces the scene root in the importer. In case that multiple EditorScenePostImportPlugin return a custom scene root, the user is notified of an unsupported behavior error.

#### EditorScenePostImportPlugin source file aware
Implement `get_source_file` for EditorScenePostImportPlugin

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the scene importer code the order of instructions would be as follows:
```python
for import_plugin in scene_import_plugins:
    import_plugin.set_source_file(source_file)
for import_plugin in scene_import_plugins:
    import_plugin.post_process(scene)
for import_plugin in scene_import_plugins:
    new_root = import_plugin.get_custom_scene_root(scene)
    if new_root != null:
        if custom_scene_root != null
            ERROR AND CONTINUE
        custom_scene_root = new_root
if custom_scene_root != null
     delete scene
     scene = custom_scene_root
if import_script.is_valid():
    scene = import_script.post_process(scene)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is a core feature that scripts or plugins can't change.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core feature that scripts or plugins can't change.

**Comment by dpalais** [comment]
### Update
With a better knowledge of the internal workings of the scene importer and its interaction with importer scripts and plugins I've made some adjustments and workarounds.

To explore all the scene materials regardless of import settings now I iterate over all the MeshInstance3D nodes and their materials in `_pre_process` and `_post_process`. Is this perhaps the desirable way to do it? If so it probably should be clarified in the class documentation.

I've adjusted the EditorScenePostImport and EditorScenePostImportPlugin scripts I use in order to workaround the current order of execution. As it is today it should be documented.

**Comment by dpalais** [comment]
I have come up with a scripting solution that doesn't involve modifying Godot's core, thus this proposal has lost validity.
For that reason, I close now this proposal.

**Comment by GalanCM** [comment]
I'm not sure what solution @dpalais used to work around this issue, but for anyone looking at this in the future, I managed it by adding an import option:
```gdscript
@tool
extends EditorScenePostImportPlugin


# this function is the only place where EditorScenePostImportPlugin can get the file path
func _get_import_options(path: String) -> void:
	# save the file path to the import setting
	add_import_option("file_path_hack", path)
```
The file path can then be retrieved using `get_option_value("file_path_hack")`. For existing files, you'll have to populate the option field manually, or reset the import settings by applying the "Default" import preset.

This is admittedly a messy hack, but it's the best way I could find.

**Comment by zwische** [comment]
@dpalais  May I ask how you managed to remove the root node in the EditorScenePostImport**Plugin**? I am having the same problem and couldn't find a solution without crashing the editor
