### ISSUE TITLE
Add animation groups to the animation Player

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#51]
**Describe the project you are working on:**
2D Action games like 2D Zeldas and 2D fighting games.

**Describe how this feature / enhancement will help your project:**
Will help avoid to repeat a lot of actions and speed workflow.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
A simple dropout button to add a keyframe from the animationplayer to all the animations with the same TAG (like basic_movement, punches, spells, getting_hit).

**Describe implementation detail for your proposal (in code), if possible:**
Add some Tag system to group diferent animation types like basic movement, melee attacks, spells, jumping and allow to copy or delete keyframes from all the animations under the same tag.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
A right click command to clone a keyframe in all the same tag of animations will be a saviour for 2D action games or other types of games with dozens of animations.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Will help clasify the list of animations and speed up the workflow.

**Comment by MagdielM** [comment]
I'd like to add that this would make mirrored animations much easier to work with. For instance, someone working on combat animations for a 2D action platformer may want to control the position of hitboxes through the animation editor. To do this for a player controller that can look either left or right, duplicates of each attack animation must be made, typically with redundant names ("Attack 1 Left", "Attack 1 Right", "Attack 2 Left"...). Selecting the correct one through code then becomes needlessly verbose.

```
#. . .

if facing_left:
   match attack:
      ATTACK_1:
         animation_player.play("Attack 1 Left")
      ATTACK_2:
         animation_player.play("Attack 2 Left")
      ATTACK_3:
         animation_player.play("Attack 3 Left")
else:
   match attack:
      ATTACK_1:
         animation_player.play("Attack 1 Right")
      ATTACK_2:
         animation_player.play("Attack 2 Right")
      ATTACK_3:
         animation_player.play("Attack 3 Right")
```

Being able to group animations could turn that into something like this:
```
var group := "left" if facing_left else "right"

match attack:
   ATTACK_1:
      animation_player.play_from_group(group, "Attack 1")
   ATTACK_2:
      animation_player.play_from_group(group, "Attack 2")
   ATTACK_3:
      animation_player.play_from_group(group, "Attack 2")
```

**Comment by akien-mga** [comment]
We discussed this in a proposal review meeting and this seems to us more like plugin/tool script material. It's not very clear from the proposal what is required exactly and how this would work, but it sounds very game / use case specific and something better handled by writing an EditorPlugin or a tool script that modifies related animations at once using your own interface.

For grouping purposes specifically, Godot 4.0 comes with Animation Libraries which could serve the need of grouping / tagging animations together. But for what seems to be requested here (being able to add a keyframe to a group of animations at the same time), this would be up to you to implement.

Either way, as it stand this proposal is not detailed enough for a proper assessment so we're closing it. Feel free to provide more details so it can be assessed further and reopened, or open a Discussion about this to give this the opportunity to get more input from potentially interested users.
