### ISSUE TITLE
Feature : CTRL-C copy Shader trees from Blender into Godot . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#510]
**Describe the project you are working on:**

A Tomb Raider game, also an RTS . .

**Describe the problem or limitation you are having in your project:**

Right now, there is an amazing shader functionality in Blender, and a lot of tutorials, for making stuff . . It would be nice if I could ' Ctrl+c ' my node trees, in Blender, directly in Godot, super-fast . . I don't know if this is difficult, but a lot of users could benefit from this, especially the more advanced . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Well, it would be nice if one could copy the nodes from Blender, for shaders, into Godot and it just worked, sort of . . That way, the integration with Blender would become stronger, and benefit all, all users . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I don't know if the two programs are compatible, or you can get access to their code, I think Blender is open source, it's free, maybe they wouldn't mind making a project with you, and strengthen the connection with Blender, and make Godot the favorite game platform, for Blender users, that are heavy artists . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I think a lot of people using Blender would move to Godot, for their games, because of less work, good working-efficiency . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**

Well, Godot already uses the principled shader, and works so well with Blender . . Why not add this, to top it off, make it better . . . :) <3 <3

**Comment by KoBeWi** [comment]
It depends on whether Blender uses system clipboard or copies the shaders internally.

**Comment by jasperbrooks79** [comment]
I just wish it was there, Godot uses the same shader, works really well with Blender, this could be the next step, new improvement, and make artists super happy, increase productivity . . :)

**Comment by akien-mga** [comment]
This is impossible, shaders in Blender and in Godot are not compatible. Those are fully different rendering engines, even if both are physically based.

**Comment by SIsilicon** [comment]
I wouldn't say it would be _totally_ impossible, but there would definitely be some limitations to it. Some people are already making an exporter add-on for blender, and they are doing their best to make a good conversion between Blender and Godot's material system.
