### ISSUE TITLE
Add automatic GridMap interior culling

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot-proposals#5107]
### Describe the project you are working on

this voxel game
https://codeberg.org/Sosasees/godot-4-voxel-test

### Describe the problem or limitation you are having in your project

at the moment, the Gridmap renders all tiles, reguardless of wether they're visible or hidden from outer tiles,
which is one of the things that makes my voxel game run poorly

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

hiding inner tiles that are not visible because they're hidden by outer tiles makes the rendering much faster

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

check if the tile is visible from the outside before rendering it. this needs to be done only once for every time the Gridmap updates.

a 2D slice example:
![](https://user-images.githubusercontent.com/66305550/183383736-256b85fe-41f9-4498-955c-9a362e92daea.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

i could setup 2 Gridmaps in the scene:
the 'full' version and the 'visible' version.

on ready, i use the interior culling algorithm to create the 'visible' version from the 'full' version.

every time a tile changes, i first change it in the 'full' version before updating the 3×3 surrounding area in the 'visible' version.

this workaround would be very complex and i would have to change the inner workings of the game completely, but i feel like it Can be done

### Is there a reason why this should be core and not an add-on in the asset library?

i don't see why this can't be an add-on.

this would help in games with changing level geometry like the voxel game — but many games have fixed levels that don't have invisible 'inner tiles' in the first place, so they don't need this feature

**Comment by Calinou** [comment]
This can already be done manually by using additional tiles specifically designed for this. Doing this automatically is not possible except for perfect voxel meshes, which are not the only thing GridMap is useful for.
