### ISSUE TITLE
Add first-class support for YAML

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot-proposals#5108]
### Describe the project you are working on

Several projects where YAML is heavily used for dialogs due its human-friendliness and practicality.

### Describe the problem or limitation you are having in your project

The built-in support for JSON is great, however, it's tedious to write JSON manually, especially in the inspector fields. YAML is a widely used drop-in alternative for JSON, so I believe it could be bundled with Godot.

There are things like godot-yaml which utilize GDNative - https://godotengine.org/asset-library/asset/254 - but they come with a few limitations:

- Windows & OS X problems: since GDNative addons come as DLLs, they trigger various signing issues on those platforms.
- Versioning: whenever there's a new version of Godot, a lot of addons must be recompiled.

Recently we've been forced to switch back to JSON simply because 3.5-rcX didn't play well with existing godot-yaml builds.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

godot-yaml uses rapidyaml - https://github.com/biojppm/rapidyaml - which is a single-header library that seems to be very lightweight and wouldn't provide too much overhead to Godot's binary. Thus I suggest adding it to the Godot code.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The interface can be exact same as JSON:

```gd
# 3.5
var data = parse_yaml(text)
# 4.0
var yaml_conv = YAML.new()
yaml_conv.parse(text)
data = yaml_conv.get_data()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The workaround is to use addons written in GDNative such as https://github.com/biojppm/rapidyaml, but they cause some problems described above.

### Is there a reason why this should be core and not an add-on in the asset library?

Having this as an add-on causes various problems as described above.

**Comment by Calinou** [comment]
This was proposed in https://github.com/godotengine/godot-proposals/issues/941 a while ago and was rejected.

**Comment by YuriSizov** [comment]
As mentioned, this was just recently rejected in https://github.com/godotengine/godot-proposals/issues/941. Please give it a bit more time, if you think that this needs to be reconsidered (and feel free to comment in the original proposal so we can reopen it then).

**Comment by KoBeWi** [comment]
> Versioning: whenever there's a new version of Godot, a lot of addons must be recompiled.

GDNative doesn't change anymore (API-wise), so you can use most 3.4 plugins in 3.5.
