### ISSUE TITLE
Implement SceneTreeTween Node with clear() function.

### ISSUE THREAD

**Issue by zuckey2** [godotengine/godot-proposals#5110]
### Describe the project you are working on

A 2D mobile game with lots of tween animations.

### Describe the problem or limitation you are having in your project

I want to use the same SceneTreeTween for multiple animations, when using multiple SceneTreeTween with create_tween(), animations overlap each other and one starts before another one finishes. I want to abort the current animation but since you can't create one with no Tweeners in _ready(), it automatically invalidates itself and is not usable.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A SceneTreeTween Node manually added to the SceneTree with clear() or abort() animations functionality to stop and clear the current playing animation and move on to the other one.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Described above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know enough C++ yet so I can't estimate how many lines of code it will take. Although it can be solved with a few lines in GDScript I think it would be a optional but useful thing. 

### Is there a reason why this should be core and not an add-on in the asset library?

It would benefit lots of standard Tween node users with chain and parallel functionality.

**Comment by YuriSizov** [comment]
You can store references to your tweens in your script, and abort them at your leisure. The new system specifically changed the paradigm to move away from nodes and allow for more fluid creation of tweens.

**Comment by zuckey2** [comment]
Don't get me wrong, I love the idea of creating tweens on the go without having to deal with Node overhead and freeing, adding it. I already use SceneTreeTween in my project a lot this way; I haven't found a valid and simple way to store those tweens as references because I have to create_tween() in _ready() and first kill the tween in every animation I want to do.

**Comment by KoBeWi** [comment]
```GDScript
var tween: SceneTreeTween
func animate():
    if tween:
        tween.kill()

    tween = create_tween()
    tween_stuff....
```
Just call `animate()` when you want to (re)start the animation.

**Comment by zuckey2** [comment]
I guess @KoBeWi 's solution is the best I can use right now.
