### ISSUE TITLE
Support playing animation backwards in AnimatedSprite3D (like in AnimatedSprite2D)

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#5111]
### Describe the project you are working on

A typical 2D Godot project, but in reality I was just surfing around the Godot source code.

### Describe the problem or limitation you are having in your project

I thought this proposal was going to be longer, but I'm going to make it brief.

Assuming **AnimatedSprite2D** is the "leading" Node between the two, animations can't play backwards in **AnimatedSprite3D**. This is an inconsistency.

_Also, **playing** is both a normal property and a separate get method entirely (**is_playing**). (This looks like an error to me)_ https://github.com/godotengine/godot/pull/64157

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the backwards parameter to **AnimatedSprite3D**.`play()`, as is already present in **AnimatedSprite3D**.

This may or may not all be a copy-pasting job.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```GDScript
var sprite_2D = $AnimatedSprite2D
sprite_2D.play("animation", true)
# Why is it not possible-?
# It's just not.
# WHY-NOT? You stup-
var sprite_3D = $AnimatedSprite3D
sprite_3D.play("animation", true)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, as complex as it may be for a beginner. Problem is, AnimatedSprite3D doesn't even have the piece of code to support it, unlike **AnimatedSprite2D**.

### Is there a reason why this should be core and not an add-on in the asset library?

**AnimatedSprite3D** is a core class.

**Comment by Calinou** [comment]
This was added by https://github.com/godotengine/godot/pull/27153, but it was never implemented for 3D.

**Comment by Mickeon** [comment]
A pleasure, now that I know how to compile the code!

**Comment by Mickeon** [comment]
I just realised, `speed_scale` is also missing from AnimatedSprite3D. Would it be okay to port both in the same PR?

**Comment by Calinou** [comment]
> I just realised, `speed_scale` is also missing from AnimatedSprite3D. Would it be okay to port both in the same PR?

Sure :slightly_smiling_face:
