### ISSUE TITLE
Use rcodesign CLI tool to sign / notarize mac binaries without a Mac.

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#5115]
### Describe the project you are working on

Godot VR multiplayer game.

### Describe the problem or limitation you are having in your project

Notarizing Godot Engine binaries is troublesome and requires a mac.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use rcodesign CLI to sign and notarize the binaries as part of Godot Engine export.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://gregoryszorc.com/blog/2022/08/08/achieving-a-completely-open-source-implementation-of-apple-code-signing-and-notarization/

> just-released 0.17 release of the apple-codesign Rust crate and its corresponding rcodesign CLI tool, you can now rcodesign notary-submit to speak to Apple's Notary API using a pure Rust client. No more requirements on 3rd party, proprietary software. All you need to sign and notarize Apple applications is the self-contained rcodesign executable and a Linux, Windows, macOS, BSD, etc machine to run it on.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No!

### Is there a reason why this should be core and not an add-on in the asset library?

Exporting integration is the feature here, we can also do this outside of the import process.

### References

https://github.com/indygreg/PyOxidizer/tree/main/apple-codesign

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot-proposals/issues/5115.

**Comment by fire** [comment]
@akien-mga wrong link :P
