### ISSUE TITLE
Rename API around shaders to use the word "parameter" and not "uniform" (except text shaders)

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#5123]
### Describe the project you are working on

VFX

### Describe the problem or limitation you are having in your project

"Uniform" is a highly specific keyword which isn't really related to its meaning. Godot is the only widespread engine to use it and it's highly counter intuitive.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Prefer the keyword "parameter" over uniform. Specifically:
1. ShadeMaterial `set_shader_uniform` should be named back to `set_shader_param`
2. VisualShader FloatUniform, ColorUniform
3. Global/Instance uniform -> param

Text shaders still use the keyword **uniform**!!!

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Changes core API

### Is there a reason why this should be core and not an add-on in the asset library?

Changes core API

**Comment by FroggEater** [comment]
It fits with most shader languages though, and makes it way less obtuse to port pure GLSL/HLSL shaders to Godot. Seems weird to indirectly obfuscate stuff and make it harder to find documentation for - allegedly - the sake of intuitiveness, especially when:

1. Godot specific resources are already difficult to come by in some scenarios, especially for shaders
2. Godot already has circonvoluted syntax - that sounds more intuitive on paper, but is a pain to deal with because of my first point - such as the `light()` function
3. Godot shader syntax is already close to GLSL apart from some specific stuff (`light()` function, uniform grouping, etc) and making it deviate even more seem counter-productive

Bouncing off the subject though, I'd love to have direct access to the rendering code/to GLSL rather than have the intermediary of Godot's stripped down shader access (which has already been proposed iirc, and is a big subject to tackle anyway).

**Comment by QbieShay** [comment]
The issue is that correctness isn't really relevant depending on who we want to target. I think VS shouldn't target people that port shadertoy, but rather people that watch unity/unreal shader tutorials. In addition to that, "parameter" is a word that encompasses uniforms. It's a super set. Uniform is a highly specific word used by shader languages that doesn't have an intuitive meaning. Other engines sacrifice correctness for the sake of usability and I think in this case we should do the same.

**Comment by Calinou** [comment]
For reference, "params" were renamed to "uniforms" in https://github.com/godotengine/godot/pull/59840 and https://github.com/godotengine/godot/pull/59844.

**Comment by h0lley** [comment]
everybody who has dabbled in the basics of shaders is accustomed to the term uniform though.
it's one of the first things any [introduction to shaders](https://thebookofshaders.com) teaches you.
is this meant to be more friendly for people who never touch shader code but want to set parameters on copy/pasted shaders?

**Comment by QbieShay** [comment]
No, not everyone learns shader on the shader book. It's actually full of very good VFX artists that don't know what a uniform is, just because other engines use the term parameter, and they normally work with visual shaders.

**Comment by FroggEater** [comment]
Honestly, in my eye, it'd be like renaming `int` to `number`, or `string` to `text` - more intuitive in a closed-off context, but less so in a more general learning sense (and taking into account existing conventions). Trying to fit with arbitrary engine conventions also feels off, and I can't help but be reminded of [this](https://xkcd.com/927/) when there's already a perfectly fine, engine-agnostic standard to go from.

It'd also feel like trading intuitiveness for people who are less experimented or using visual shaders (which is not, to be clear, a bad thing), for increased frustration (and more difficult research in general) for people who got more used to shaders and are starting/writing their own (which definitely is in my eye).

**Comment by Zireael07** [comment]
@QbieShay: The old intro to Shadertoy by iq aka Inigo Quilez linked on their main page uses the term "uniform", actually. I know currently they are more hidden than in that intro, but still point in favor of "uniform".

"Parameter" has a downside of being really generic, newbies will get confused whether the parameter is on the shader, on the material, on the node etc.

Personally I think it's sorta a case for #5085 (have "shader parameter" redirect to uniform or the other way round if the team does indeed decide on the rename proposed)

**Comment by QbieShay** [comment]
@FroggEater i disagree. Shader params have been called Params in 3.x and it has been changed only now in 4.x. Note i'm not suggesting we change the keyword uniform in text shaders, but I just want to restore the previous names in VS and in the API.

**Comment by Chaosus** [comment]
I'm not a big fan of renaming things just for easier perception of newcomers. Sorry, @QbieShay I'm against.

**Comment by QbieShay** [comment]
I asked in a VFX server with a number of pros, received 8 responses, 3 knew what uniform meant, 5 didn't.
And these people are not newbies to VFX, they're professional artists.

**Comment by Chaosus** [comment]
Well, of course if the majority of votes will agree, this change is welcome. It's just my personal feeling, nothing more. Maybe you're right, and this change will be good and make users happy.

**Comment by Chaosus** [comment]
Then maybe we should add `param` as an alternative alias for uniform in the text shaders.

**Comment by QbieShay** [comment]
To me text shaders are "advanced" usage, it's fine if they use the "proper" keyword: if someone goes to text shaders chances are they are more experienced in the graphics side. Especially after all the good work you've put in VS, i think a lot of people will be comfortable using VS over text, so text shaders will be left to people that either already prefer it, or that really need it. I don't want to bother those people, I want to make it easier for others.

**Comment by Zylann** [comment]
`RenderingServer::global_shader_uniform_type_get_shader_datatype` still uses `uniform`.
Also `ShaderMaterial` still uses `shader_uniform/` in TRES, and as a result, I guess animations will get that property name too? But at this point every change is annoying as I had to fix my repos several times now (and `shader_params` was never a problem to me)
