### ISSUE TITLE
Add touch-based movement controls for the 3D editor viewport

### ISSUE THREAD

**Issue by werryxgames** [godotengine/godot-proposals#5124]
### Describe the project you are working on

Empty project

### Describe the problem or limitation you are having in your project

Can't easily rotate, scale in 3D space like in PC, absolutely can't move

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

You can add better movement, when no object selected, it will solve problem with decrease time, needed to scale, rotate and solve problem with movement

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1 finger - rotate

2 fingers - scale (-> <- or <- ->), move (-> -> or <- <-)
*Arrow is finger direction

Press and hold 1 finger without moving (~0.5 seconds) - select

1 finger click on object - select 1 object

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be very often used. <1000 lines

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the 3D editor usability out of the box

**Comment by Calinou** [comment]
- This was implemented by https://github.com/godotengine/godot/pull/69364.
