### ISSUE TITLE
Add option to change the editors free-look camera sensitivity

### ISSUE THREAD

**Issue by 1abinitio1** [godotengine/godot-proposals#513]
sorry if this looks a little weird, but tried to fill the form as it looked.
would add this myself, just cant figure out c++ and git (come from unity ¯\\_(ツ)_/¯ )

**Describe the project you are working on:**
Nothing specific just a generally needed tweak

**Describe the problem or limitation you are having in your project:**
Cannot change the camera sensitivity for the editors free-look camera
this exists for the orbit camera but not free-look for some reason

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
An option in the settings to change the sensitivity

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
something like 
camera.rotation.x+=mouseDelta.x*sensitivity

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
nope

**Is there a reason why this should be core and not an add-on in the asset library?:**
its a core thing

**Comment by willnationsdev** [comment]
Took a quick peek at the `SpatialEditorViewport::_update_camera()` function. Looks like there are some EditorSettings that configure it? `editors/3d/freelook/freelook_inertia`

**Comment by Calinou** [comment]
This already exists, but it's linked to the orbit (non-freelook) mouse sensitivity. Adjust **Editors > 3d > Navigation Feel > Orbit Sensitivity** in the Editor Settings. I'm not sure if we should add a dedicated setting. Are there situations where the orbit sensitivity would be too high and the freelook sensitivity too low for a given value?

@willnationsdev Changing the freelook inertia setting won't affect freelook mouse *sensitivity*, as they are unrelated properties.
