### ISSUE TITLE
Add Multi-line to TextMesh

### ISSUE THREAD

**Issue by raietracer** [godotengine/godot-proposals#5132]
### Describe the project you are working on

A 3D game, this feature wouldn't necessarily be 'core' to my game, but it does have a large impact being seen constantly throughout the game's HUD and diegetic UI.

### Describe the problem or limitation you are having in your project

After working with TextMesh nodes for a while I decided to use them for scrolling intro text like the Star Wars intro text scenes.
Then I realized that I would have to use a separate TextMesh for each line because it does not understand \n or multi-line strings applied via code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I don't want to assume that one could simply use the same multi-line string compatibility present in other font-related nodes, but if that's possible, making it work just like the text entry for Label3D.  🤷🏻‍♀️

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I imagine this is where the gritty godot engine programming details would go and I'm not familiar with all that, most importantly, the end result is that TextMesh.text strings can be multiline and the resulting mesh will reflect that visually.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Short answer:  No,  Long answer:  No
At first I tried making the exposed text a multiline setget export string in the MeshInstance's script but as you can see this does not work as I assumed it would.  Screenshot from testing project:
![issue_screencap](https://user-images.githubusercontent.com/10767425/183780645-b62e30c7-623b-4dcd-8b42-9687661bdf20.png)

### Is there a reason why this should be core and not an add-on in the asset library?

Other text display nodes seem to universally support multi-line strings, this lone exception feels very much like an outlier as if it were meant to be implemented and forgotten 😭

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
The only reason I have not added it in a first place, mesh generation is much slower than text controls. But it should be easy to add.

**Comment by bruvzg** [comment]
https://github.com/godotengine/godot/pull/64243

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/64243.
