### ISSUE TITLE
Move rotation interpolation logic from `PathFollower`2D/3D to `Curve`2D/3D

### ISSUE THREAD

**Issue by xiongyaohua** [godotengine/godot-proposals#5136]
### Describe the project you are working on

Some urban road traffic simulator.

### Describe the problem or limitation you are having in your project

I represent road with Curve, and the position of cars are stored as their distance from the beginning of the road. In order to the desecrate coordinate and heading direction of a car, currently I need to:
1.  bind a `PathFollower` to the curve
2. set its `offset` property
3. read `position` and `rotation` property of the `PathFollower`
4. repeat 1-3 for all cars

This procedure is OK for a few cars, but for thousands of car it is both awkward and inefficient. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Move the rotation interpolation logic from PathFollower to Curve, for two reasons:

1. theoretically sampling is a natural operation on curve
2. practically sample curve directly without instantiate PathFollower is more efficient

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a method  `Transform2D interpolate_baked_with_rotation(real_t offset)` to `Curve2D`, which directly return a `Transform2D` that contains both the position and rotation at given offset on the curve .

```
var road_curve: Curve2D
var car_offset
var car_transform = road_curve.interpolate_baked_with_rotation(car_offset)
```

Similar idea applies also to Curve3D

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, need to add a new method on a core type.

### Is there a reason why this should be core and not an add-on in the asset library?

need to add a new method on a core type

I submitted several PR as part of this effort. see [#64043](https://github.com/godotengine/godot/pull/64043), [#63956](https://github.com/godotengine/godot/pull/63956), [#64212](https://github.com/godotengine/godot/pull/64212)

**Comment by Zireael07** [comment]
Tangentially related: for perf reasons I'm not using Curve2D but a series of vectors and I'd like to be able for PathFollower to be able to follow just a series of Vector2/3, not needing Path/Curve....

**Comment by Mickeon** [comment]
What if the interpolation logic is in both, but **PathFollower** can overwrite it? By default it would be set still to use the **Path**'s interpolation logic

**Comment by xiongyaohua** [comment]
> Tangentially related: for perf reasons I'm not using Curve2D but a series of vectors and I'd like to be able for PathFollower to be able to follow just a series of Vector2/3, not needing Path/Curve....

The interpolation code of the Curve2D/3D already works on  baked points, which are stored in packed Vector2/3 array, so technically it is easy to factor out as an independent function.  But I think it is not necessary, for two reasons:
1. this probably makes no performance difference; 
2. we need to find a new place for the code other than `resource/curve.cpp`

The only scenario that I can think of is that you do your own baking for curves(for example, NURBS instead of the current Cubic Bezier), then you interpolate the resulting Vector2D/3Ds. But in this case it is probably better to add a new baking mode for Curve2D/3D and integrate your baking code.

**Comment by xiongyaohua** [comment]
> What if the interpolation logic is in both, but **PathFollower** can overwrite it? By default it would be set still to use the **Path**'s interpolation logic

The Path have no interpolation logic, as it have no data; all the data is in the **Curve** that connect with the Path. Currently when the PathFollower want to get its position, it get the **Curve**, then ask the Curve to do the interpolation for the position. Then the PathFollower calculate the rotation based on the positions of three nearby nodes.

This idea of the proposal is to move the calculation of rotation also to `Curve`. Then when the PathFollower updates, it gets the `Curve`, then ask for both `position` and `rotation` from Curve
