### ISSUE TITLE
Emit `AnimatedSprite.frame_changed` when switching animation, NOT just on `frame` index change

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#5137]
### Describe the project you are working on

A small 2D prototype to impress my friend, that he's going to probably use for later.

### Describe the problem or limitation you are having in your project

Here's some very simple code: if the character is attacking, play "_hammer_" or "_hammer_air_" animation:
![image](https://user-images.githubusercontent.com/66727710/183927507-3a64bd86-abe3-42a1-871b-a3a5161763f2.png)

In this case, I want the Hammer hitboxes to be enabled as soon as the animations change. 
Therefore, the **AnimatedSprite** is appropriately connected to the two following methods _(Irrelevant code stripped away_):
![image](https://user-images.githubusercontent.com/66727710/183925602-709167a8-b98f-4880-b970-1880b502b97e.png)

By looking at the output, it's clear to see something:
_It's worth noting that the "_idle_" animation is composed by a single frame._

![image](https://user-images.githubusercontent.com/66727710/183472920-d131f06a-cc37-45a4-badd-7c19051513a7.png)

Notice how `frame_changed` isn't called during the switch because, although the animation has changed (from "_idle_" to "_hammer_"), technically, the `frame` index is the same (from _`0`_ to _`0`_), but in reality, the perceived frame has actually changed.
In this case, _"idle"_  is composed by a single frame, but if there was one more, `frame_changed` would emit randomly half the time (from _`0 or 1`_ to _`0`_).

This means that, for my code to work as intended, I have to manually call `_on_Sprite_frame_changed()` as `play()` is called, otherwise the hitboxes will **not** be active on the first frame.

While this behaviour *is* intentional, I am not convinced if it's exactly useful. The example above is very trivial, it's true, but especially for more complicated behaviours, relying on this signal for this type of logic makes the code look much, _much_ clearer and simple to understand, by not bloating the rest of the logic.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Change the behaviour of **AnimatedSprite**.`frame_changed()` to emit when the animation changes, as well.

An alternative to this proposal would be to add a new signal `animation_changed`. This would allow connecting both `animation_changed` and `frame_changed` to the same method. However, it may cause the receiving method to needlessly trigger twice at a given time, and I honestly can't think of any proper reason to need this signal over the above proposal.

Whatever solution will be implemented should also apply for **AnimatedSprite3D**.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't think there's much to display as a mock-up.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes. One simple, scalable way to do it requires appending this Script to a given AnimatedSprite:
```GDScript
# Godot 3.x
extends AnimatedSprite

func set_animation(_anim: String):
    var previous_animation = animation
    var previous_frame = frame
    super(_anim)
    if animation != previous_animation:
         if frame == previous_frame: # Means frame_changed hasn't been called by set_frame() already
              emit_signal("frame_changed")
```

### Is there a reason why this should be core and not an add-on in the asset library?

AnimatedSprite and AnimatedSprite3D are core classes.

**Comment by Diddykonga** [comment]
+1 For the Alternative solution, a separate `animation_changed` is more semantically correct, and also provides for your use case, as well as others. 
For example, If we only wanted to run code on animation changes, and not frame changes, or If we wanted to run on frame changes only, similiar to the current behaviour, or If you have some kind of setup/init on animation changes, and then update/tick on frame changes type of code, this separation makes the code more clear.

**Comment by Mickeon** [comment]
Closing in favour of https://github.com/godotengine/godot-proposals/issues/5146
