### ISSUE TITLE
SceneTreeTween: Add a way to identify looping tweens

### ISSUE THREAD

**Issue by Pennycook** [godotengine/godot-proposals#5141]
### Describe the project you are working on

A turn-based RPG using tweens for battle animations and UI updates.

### Describe the problem or limitation you are having in your project

Each turn, a number of different (unknown) events may create one or more tweens.  As a simple example, using a healing item may create a tween to modulate the player's color, a tween to make some numbers appear, and a tween to interpolate the player's health bar.

At the end of each turn, I'm using the following code to check that all tweens created this turn have finished:

```gdscript
# If there are any Tweens still running, wait for them
for tween in get_tree().get_processed_tweens():
    if tween.is_valid() and tween.is_running():
        yield(tween, "finished")
```

This code won't work if there is an infinitely looping tween, because the tween will never emit the finished signal.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an `is_looping()` method and access to the `loops` property.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The new methods and properties would allow the snippet above to be written safely as something like:
```gdscript
# If there are any non-looping Tweens still running, wait for them
for tween in get_tree().get_processed_tweens():
    if tween.is_valid() and tween.is_running():
        if tween.is_looping() and tween.loops == 0:
            continue # Ignore infinite tweens
        else:
            yield(tween, "finished")
```

(I can also imagine situations where this proposal would allow developers to know whether they should be expecting the "finished" or "loop_finished" signals, but this is not my immediate use-case.)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The simplest workaround (as [suggested by](https://github.com/godotengine/godot-proposals/issues/5141#issuecomment-1211282860) @SilencedPerson) is to manually add metadata to infinitely looping tweens.

### Is there a reason why this should be core and not an add-on in the asset library?

Providing these getters makes the list of tweens returned by `get_processed_tweens()` more useful.

The `SceneTreeTween` already has a `loops` member that could be used to implement this functionality, there just isn't any way to access it from GDScript.

**Comment by SilencedPerson** [comment]
You are already storing all tweens, just set meta to them:
```gdscript
tween.set_meta("infinitely_looping", true)
```
and check for it inside your existing loop with:
```gdscript
tween.has_meta("infinitely_looping")
```
Here are the docs for object: [DOCS](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-set-meta)

**Comment by Pennycook** [comment]
> You are already have access to all tweens, just set meta to them, that way you can filter them with much greater granularity:

That's a very clever workaround, thanks!  I'll update the original post.

**Comment by SilencedPerson** [comment]
You could also store number of loops inside the meta to ensure the tween looped at least once. Meta is probably my favorite thing in Godot.

**Comment by Pennycook** [comment]
@KoBeWi Now that 4.0 is stable, I'm interested in poking around in the internals a bit more.  How would you feel about me trying to implement this for 4.1?

**Comment by KoBeWi** [comment]
Sure.

Two notes though. `loops` shouldn't be a property, because `set_loops()` returns a value and it has to be used directly.
Also `is_looping()` method is redundant, because you can just check `get_loops() != 0`

The only method that should be added is either `get_loops()` that returns the `loops` member or `get_loops_left()` that returns remaining loops (and probably `-1` for infinite looping).

**Comment by Pennycook** [comment]
> Two notes though. `loops` shouldn't be a property, because `set_loops()` returns a value and it has to be used directly. Also `is_looping()` method is redundant, because you can just check `get_loops() != 0`

After looking at this example, I now think `get_loops()` might be confusing.  If I understand the code correctly, the default value of `loops` (the member variable) is actually 1, and so a tween that plays once is the same as a tween that "loops" once.  This seems like it could be a common mistake.

> The only method that should be added is either `get_loops()` that returns the `loops` member or `get_loops_left()` that returns remaining loops (and probably `-1` for infinite looping).

I like the idea of `get_loops_left()`, but I want to make sure I understand the behavior you're proposing:
- If it returns -1, the tween was created with `set_loops(0)` and represents an infinite loop.
- If it returns any other value, the tween was created without specifying `set_loops`, or `set_loops` was called with a non-zero argument.
- If it returns > 1, the next signal emitted by the tween will be `loop_finished`.
- If it returns 1, the next signal emitted by the tween will be `finished`.
- If it returns 0, the tween has already finished.

Is that right?

**Comment by KoBeWi** [comment]
Yes.

**Comment by Calinou** [comment]
For reference, this was implemented by https://github.com/godotengine/godot/pull/74454.
