### ISSUE TITLE
Add `AnimatedSprite3D.frame_refreshed` signal

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#5146]
### Describe the project you are working on

A small 2.5D prototype to impress my friend, that he's going to probably use for later.

### Describe the problem or limitation you are having in your project

Here's some very simple code: if the character is attacking, play "_hammer_" or "_hammer_air_" animation:
![image](https://user-images.githubusercontent.com/66727710/183927507-3a64bd86-abe3-42a1-871b-a3a5161763f2.png)

In this case, I want the Hammer hitboxes to be enabled as soon as the animations change. 
Therefore, the **AnimatedSprite** is appropriately connected to the two following methods _(Irrelevant code stripped away_):
![image](https://user-images.githubusercontent.com/66727710/183925602-709167a8-b98f-4880-b970-1880b502b97e.png)

By looking at the output, it's clear to see something:

![image](https://user-images.githubusercontent.com/66727710/183472920-d131f06a-cc37-45a4-badd-7c19051513a7.png)

Notice how `frame_changed` isn't called during the switch because, although the animation has changed (from "_idle_" to "_hammer_"), technically, the `frame` index is the same (from _`0`_ to _`0`_), but in reality, the _perceived_ frame texture has actually changed.
In this case, _"idle"_  is composed by a single frame, but if there was one more, `frame_changed` would emit randomly half the time (from _`0 or 1`_ to _`0`_).

This means that, for my code to work as intended, I have to manually call `_on_Sprite_frame_changed()` as `play()` is called, otherwise the hitboxes will **not** be active on the first frame.

While this behaviour *is* intentional, it's not exactly useful for these, and I would argue, most use cases. It would be nice to just, know if there's any perceivable change to the frame, so that associated logic can update accordingly. The example above is very trivial, it's true, but especially for more complicated behaviours, relying on a signal for this type of logic makes the code look much, _much_ clearer and simple to understand, by not bloating the rest of the logic.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement a **AnimatedSprite**.`frame_refreshed` signal. Although the signal is reasonably self-explanatory, It will be emitted **only once** per frame, if one of the following happen:
- The `animation` changes;
- The `frame` changes;
- `flip_x` and `flip_y` are toggled;
- The **SpriteFrames** `frames` is changed;

Therefore, any method connected to this signal will act whenever there's a somewhat perceivable change, **even if the AnimatedSprite is not visible**.

This signal should be implemented for **AnimatedSprite3D**, but I'd not be against including it in **AnimatedSprite2D**, for consistency

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

_Very dumbed down example, which I may or may not update later on_:
```GDScript
var sprite := $AnimatedSprite as AnimatedSprite

func _on_AnimatedSprite_frame_refreshed():
    print(sprite.animation,":  ", sprite.frame) # Will appropriately print every perceivable frame change
    
    var attacking := sprite.animation == "hammer" or sprite.animation = "hammer_air":
    
    $AttackArea.monitoring = attacking
    $AttackArea.position.x = -10 if sprite.flip_x == -1 else 10
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's not a few, but here's an example of what Script could be appended to an **AnimatedSprite** to replicate a similar behaviour:
```GDScript
signal frame_refreshed

func _set(property: String, value):
	if property == "flip_h":
		if flip_h == value:
			return
		emit_signal("frame_refreshed")


func play(anim := ""):
	var previous_animation = animation
	var previous_frame = frame
	.play(anim)
	
	if animation != previous_animation:
		if frame == previous_frame:
			emit_signal("frame_refreshed")
```

### Is there a reason why this should be core and not an add-on in the asset library?

**AnimatedSprite** is a core class.

**Comment by Mickeon** [comment]
This is an alternative to https://github.com/godotengine/godot-proposals/issues/5137 which I feel much more confident about.

**Comment by Mickeon** [comment]
I was very close to close both proposals, as upon looking at the code, this is almost equivalent to the **CanvasItem**.`draw` signal. *However*, this is cannot easily be done in **AnimatedSprite3D**, as it doesn't have anything of the sort.

**Comment by Zireael07** [comment]
Speaking of the draw signal, it seems to be almost completely undocumented :/

**Comment by Mickeon** [comment]
> Speaking of the draw signal, it seems to be almost completely undocumented :/

That's true. With a bit of thought, it's understandable *when* it is called, but going by the description I had a hard time realising it would work for my use case (**only in 2D** and **ONLY** when the Sprite is visible, however). I can imagine how confused the casual user may be. Is it only called when `update()` is written in any given Script (_no_)? Is it called when the **Sprite** is invisible (_it's actually not_)? Does it have anything to do with the `_draw()` callback method (_yes_)?
