### ISSUE TITLE
Indicate in the code editor if an exported variable is used.

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot-proposals#515]
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Sometime in rare case, you can set by accident an exported variable in the node that override the default. As there is no indicator in the code editor that tell you if the variable use the default value or not, that's can lead to a "transparent" issue.

**Describe how your proposal will work, with code, pseudocode, mock-ups, and/or diagrams:**

I suggest to add an icon left to the variable when the value is "overrided" in the node (like signals).

**Comment by willnationsdev** [comment]
So, this would involve needing to iterate through all the scenes in which the script is owned, i.e. where the script is on a Node, and then load each of those scenes into memory to check and see if they have an overridden value for the exported property. Could potentially become pricey on larger projects if a given script is used in a lot of places. Perhaps have a background thread that does it?
