### ISSUE TITLE
GDScript: Change `static` to an annotation

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#5165]
### Describe the project you are working on

2D Platformer – not relevant though.

### Describe the problem or limitation you are having in your project

- Hard to find out in the docs what `static` does
- Can't use `static` as a variable name
- I'm interested in proposals for some annotations like `@tool_only` #729 that may be implemented in the future to be appended before functions, so it would be better for `@static` to not become an exception when/if that happens.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`static` follows the idea of other keywords that turned into annotations: It's placed at the beginning of a line, prepended behind a first-class member to configure its functionality.

So the idea is to change `static` to a `@static` annotation. As an annotation, it would be Ctrl+clickable and lead you to the docs where it explains itself. "static" would be changed to non-keyword, so it would become usable for variable names.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know what it would take.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Will be used often.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by fire** [comment]
Static would still be a non usable name in all languages to avoid binding problems.

You can add editor search for static without this.

**Comment by MewPurPur** [comment]
Makes sense. To answer the question – none, as it's an enhancement suggestion.

**Comment by Mickeon** [comment]
If anything I would rather love if `static` did more other than being associated to function definitions and nothing else...

**Comment by KoBeWi** [comment]
> As an annotation, it would be Ctrl+clickable and lead you to the docs where it explains itself.

You could say the same about any keyword...

> it doesn't solve anything

https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#the-problem-always-comes-first

**Comment by MewPurPur** [comment]
Hey, let's be fair, many enhancements are quality-of-life changes that don't solve anything. Either way, clearly a majority believes this is not a case for annotations.
