### ISSUE TITLE
Make 1920x1080 the default base resolution

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-proposals#5169]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

Godot 4 alpha 14 still comes with 1024x600 as base resolution. This is a very uncommon resolution today and based on my experience as a teacher most new users will start designing the UI of their games using that default, only for them to notice it looks tiny on any modern monitor resolution. Sometimes they'll even attempt to fix it by scaling UI nodes, making things even worse. 
The most common resolution on Steam is 1920x1080. The latest docs accurately state that in _[Multiple Resolutions](https://docs.godotengine.org/en/latest/tutorials/rendering/multiple_resolutions.html#one-size-fits-all)_. They also accurately state that it should be thought as the "design size". 
I'm sure there must've been a historical reason for choosing 1024x600 but now it means that Godot has a default that's not useful for almost all of its users, and that it is expected that new users read the documentation on multiple resolutions and change the default value before they start working on their game. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make 1920x1080 the default viewport size for new projects

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

🙂
![image](https://user-images.githubusercontent.com/526829/184552779-fb6ea5cc-077b-444f-b1c3-ccc390eec43c.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is trivial to change this when starting a new project if you already now it will be an issue, but it's much harder to do it later when the UI is already design. A counter argument could be that the layout system automatically resizes elements but this not completely true. Margins are updated but everything else is defined in pixels and stays the same, with font sizes being the biggest issue. It does work correctly if the scaling is set to canvas_item but that's also another default setting issue. See https://github.com/godotengine/godot-proposals/issues/3939

### Is there a reason why this should be core and not an add-on in the asset library?

"This is about improving the UI usability out of the box"

**Comment by SilencedPerson** [comment]
It should default to the screen resolution of the device. 1920x1080 is too big for the display on my laptop.

**Comment by KoBeWi** [comment]
The problem with 1920x1080 is that it's most common screen resolution, which means that the window will take whole screen. It's more convenient to develop with windowed project, at least when you have only 1 screen.

Although the default could still be changed, but to something different. Preferably 16:9, given it's a popular format.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/pull/55032.

**Comment by Calinou** [comment]
Closing, as changing this value now would break compatibility with existing projects (and applying it to new projects only could be confusing). Note that Godot 4.0 uses a [default window size of 1152×648](https://github.com/godotengine/godot/pull/55032), which is 16:9 and a multiple of 8 on both axes. This already greatly improves its usefulness out of the box, on top of being slightly larger :slightly_smiling_face:
