### ISSUE TITLE
Allow Physical Keys for different keyboard layouts (in-Editor hotkeys)

### ISSUE THREAD

**Issue by KiwwiPity** [godotengine/godot-proposals#5185]
### Describe the project you are working on

[any Godot project]

### Describe the problem or limitation you are having in your project

My keyboard has Spanish layout.
Any hotkey that needs `Alt Gr`, like `\`, for example `Ctrl + \` for toggling the scripts panel needs also `Alt Gr` to work.
So `Alt Gr + Ctrl + \`

For frequent hotkeys its tedious.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allowing physical keys for different keyboard layouts (localization) could solve it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The idea is to have different configs for any keyboard layout, and dispatch the correct one, by detecting the keyboard layout, something that OSs already do.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

For any Spanish user its relevant. No.

### Is there a reason why this should be core and not an add-on in the asset library?

No, its Editor core.
Its expected from the official editor to have good international support.

**Comment by Calinou** [comment]
> The idea is to have different configs for any keyboard layout, and dispatch the correct one, by detecting the keyboard layout, something that OSs already do.

We don't need different configurations per keyboard layout, as Godot already supports physical keys (and multiple keys per editor shortcut).

**Comment by KiwwiPity** [comment]
> > The idea is to have different configs for any keyboard layout, and dispatch the correct one, by detecting the keyboard layout, something that OSs already do.
> 
> We don't need different configurations per keyboard layout, as Godot already supports physical keys (and multiple keys per editor shortcut in 4.0).

Godot 3 has no option for detect if my keyboard is Spanish and use its hotkeys? (instead of the English ones)

**Comment by Calinou** [comment]
> Godot 3 has no option for detect if my keyboard is Spanish and use its hotkeys? (instead of the English ones)

Godot 3.4 and later also has support for physical keys, but editor shortcuts don't support using those.

**Comment by KiwwiPity** [comment]
> Godot 3.4 and later also has support for physical keys, but editor shortcuts don't support using those.

That's exactly what I was referring to: Allow to use different keyboard layouts, depending on the keyboard localization, without being it coupled to the current editor traduction.

**Comment by Gatada** [comment]
So it seems like this issue is solved from Godot 4 and later.

**Comment by Calinou** [comment]
> It seems like this issue is solved from Godot 4 and later - so why is this issue still open?

Indeed, this is now implemented as of 4.0.beta1. Making some of the default editor shortcuts use physical keys is tracked in a separate issue: https://github.com/godotengine/godot/issues/65275
