### ISSUE TITLE
Change project file ending from project.godot to project.godot4 (for Godot 4)

### ISSUE THREAD

**Issue by creadicted** [godotengine/godot-proposals#5187]
### Describe the project you are working on

I work with a lot of different smaller projects. Some are on version 3.x some on 4.alpha.x

### Describe the problem or limitation you are having in your project

I double-click on a project.godot, and it is opened with the editor version 4 but it's a version 3 project. The Godot 4 editor changes on startup some settings on the project (which is something that also should not happen without a prompt) and the project can not start. I reopen the project with the correct editor version but now I get the prompt that the project can not be opened becuase its for a newer version ... the hole process can be frustrating. 
I 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If the file ending is changed to project.godot4 and the icon would be a bit different, it would really help when navigating between different projects. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When opening an editor, it will not change anything without a prompt.
The project.godot file will be renamed to project.godot4

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Its core of the editor

**Comment by YuriSizov** [comment]
> When opening an editor, it will not change anything without a prompt.

If you open it from the project manager, there is a prompt. Once the project has started loading, I don't think it's possible to halt it and prompt for a convertor. And without any conversion your project won't work anyway.

You can also solve your problem by using [Hourglass](https://hourglass.jwestman.net/) which lets you maintain multiple versions of Godot and build association between your projects and the version they are designed for. Issues can occur between any two versions of the engine, so this tool is inherently useful.

**Comment by 2439905184** [comment]
I think maybe different verison of godot can use a version string in project.godot file instead of use "project.godot4"
use file extends name is not the best.

> ### 描述您正在处理的项目
> 我从事许多不同的小型项目。有些在3.x版本上，有些在4.alpha.x上
> 
> ### 描述您在项目中遇到的问题或限制
> 我双击一个项目.godot，它与编辑器版本4一起打开，但它是一个版本3的项目。Godot 4编辑器在启动时更改了项目的某些设置（如果没有提示，也不应该发生这种情况），并且项目无法启动。我使用正确的编辑器版本重新打开项目，但现在我收到提示，该项目无法打开，因为它适用于较新版本...孔过程可能令人沮丧。 我
> 
> ### 描述功能/增强功能以及它如何帮助克服问题或限制
> 如果将文件结尾更改为 project.godot4，并且图标会有所不同，那么在不同项目之间导航时会很有帮助。
> 
> ### 描述您的提案将如何工作，包括代码、伪代码、模型和/或图表
> 打开编辑器时，如果没有提示，它不会更改任何内容。 project.godot 文件将重命名为 project.godot4
> 
> ### 如果此增强功能不经常使用，是否可以使用几行脚本来解决？
> 不
> 
> ### 为什么这应该是资源库中的核心而不是附加组件？
> 其编辑器的核心

**Comment by 2439905184** [comment]
if godot can show godot project version , I think it will be good for every users.(Just my advice).

**Comment by 2439905184** [comment]
Because cocos creator use this function.But I dont't use cocos creator. Godot is very good!

**Comment by 2439905184** [comment]
> > When opening an editor, it will not change anything without a prompt.
> 
> If you open it from the project manager, there is a prompt. Once the project has started loading, I don't think it's possible to halt it and prompt for a convertor. And without any conversion your project won't work anyway.
> 
> You can also solve your problem by using [Hourglass](https://hourglass.jwestman.net/) which lets you maintain multiple versions of Godot and build association between your projects and the version they are designed for. Issues can occur between any two versions of the engine, so this tool is inherently useful.

Hourglass is just do the thing, add project version data when start import project.
If people use git to clone their project for a new computer whithout Hourglass , This verison data will get lost.
My way is to write a issue to sign the game project on github or just write a txt file in projet files.
Sometimes people may forget to singn the project verson of godot.
To me, I spent sometime to update 3.2.1 project to 3.4.4.
New 3.4.4 version is better.
For example 3.2.1's gdscript has a difference between 3.4.4 (For loop)
```gds
var index = 1
for index in 20:
  pass
```
this code in godot 3.2.1 will run. But will not run with godot 3.4.4 . I think gdscript has a update

**Comment by KoBeWi** [comment]
> I double-click on a project.godot, and it is opened with the editor version 4 but it's a version 3 project.

It happened to me a couple of times. My solution was just hiding the `project.godot` file, because I most often open the project from VS Code anyway.

Changing the ending will basically force us to follow this with every upcoming major version. Godot 5 project ending with `godot4` is not right. IMO it's not worth it.

**Comment by creadicted** [comment]
I can follow your arguments and agree with them. So my suggestion is not a good way to solve the underlying problem. 
Would it make sense then to add the last version the project was edited with in to the project.godot file and if it is opened with a newer version we add a prompt "This version was created with version "xyz" do you want to open it?"
