### ISSUE TITLE
Rename CanvasItem's `update()` to `redraw()` for Godot 4

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#5190]
### Describe the project you are working on

2D Platformer, using some tool classes to draw things in the editor.

### Describe the problem or limitation you are having in your project

I wrote bad logic, calling reduntantly the `CanvasItem.update()` method, because it was too vague. I thought it was part of Node and responsible for updating configuration warnings too. Even if I'd seen docs, the name is SO vague I might not have thought much of it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As suggested in old comments from Rename Tracker proposals and from https://github.com/godotengine/godot/pull/64377 , rename the method to `redraw()`.

It wouldn't solve anything in my project anymore, but it would spare future users from misunderstanding the method and making mistakes like mine.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by SilencedPerson** [comment]
I kept trying to name functions "update" only to remember it's already in use when I started with Godot.. I would appreciate this one.
