### ISSUE TITLE
Reopen debug drawing 

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#5191]
### Describe the project you are working on

Debug drawing

### Describe the problem or limitation you are having in your project

Can we reopen https://github.com/godotengine/godot-proposals/issues/112
To discuss the proposal, 
It should have been long time enough so it will be probably calm now.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

N/A

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by clayjohn** [comment]
I would prefer someone open a new proposal summarizing the main points in that one and suggesting a solution/way forward. There is too much heated discussion in #112 to be of much use.

**Comment by Zireael07** [comment]
**Describe the project you are working on**
3D free roaming racer, 3D stealth fps, 2D space game (think Asteroids or Escape Velocity)

**Describe the problem or limitation you are having in your project**
Need a way to conveniently draw debug stuff such as lines/spheres/rays(arrows), both in 2D and 3D

The more complex the shape, the bigger the current workarounds are, and obviously the engine already can do it judging by switching visible collision/nav/paths (the latter is 4.0 only) to ON.

Describe the feature / enhancement and how it helps to overcome the problem or limitation
No need to write 500 lines of code just to get what competitor engines offer out of the box. (Also haven't figured out yet how to draw an arrow/ray in 3D yet :( )

Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
API example from closed proposal:

```
func _targetEnemy():
	# have some math or gameplay logic here..
	var selfPos: Vector3 = ...
	var targetPos: Vector3 = ...
	# params: from, to, color, duration, view space transform
	Debug.draw_line(selfPos, targetPos, Color.red, 0.0, maincamera3D)
```

If this enhancement will not be used often, can it be worked around with a few lines of script?
500 or more lines is not a few lines (I have a 100 line script just to draw arcs and circles that I created myself). Kidscancode has an awesome 2D on 3D solution that means lines are always visible (unaffected by perspective) but that's over 100 lines just to draw vectors/lines. The newest addon on the library is 400 lines, just to draw boxes/arcs/circles/spheres...

Is there a reason why this should be core and not an add-on in the asset library?
Several addons exist, no one is complete, also competitor engines (Unity. UE4) have this out of the box. We have more and more people coming to Godot from Unity... and I assume EVERY project needs to draw a line/arc/box/sphere at some point.

**Comment by Calinou** [comment]
I wrote a new proposal about it based on my comment in #112: https://github.com/godotengine/godot-proposals/issues/5196
