### ISSUE TITLE
Add a method dropdown list to the signal connection popup

### ISSUE THREAD

**Issue by poohcom1** [godotengine/godot-proposals#5193]
### Describe the project you are working on

A 2D platformer/action game with a lot of signal connections

### Describe the problem or limitation you are having in your project

In my projects, most signal connections are connected to existing methods, such as `Character::on_hit` -> `HPBar::update_hp` or `Enemy::on_damage` -> `Shaker::shake`, as opposed to creating unique methods tied to signals like `HPBar::on_Character_on_hit`. 

When connecting signal via the signal connection popup, this becomes cumbersome as I would have to type out the specific method name each time. Furthermore, if there is a typo, it would create an entirely new method. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a drop-down to select the method from the target node would make this process much more convenient and ensures that there are no typos.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A simple drop-down (OptionButton) popup activated by a button next to the method TextField should be sufficient.

![godot signal method dropdown](https://user-images.githubusercontent.com/74857873/185375261-12d5ff92-c945-4102-be1d-8a012f475ab1.png)

I considered the idea of replacing the text field with the drop-down entirely and adding "New method..." as the final option which then displays the text field, but this would make the UI less convenient for users who prefer connecting signals the old way (creating new methods). Since I'm unsure what most user would prefer, I think the example above would be the most appropriate implementation.

The screenshot is from a basic implementation I made off the 3.5 branch: https://github.com/poohcom1/godot/commit/8f8f49f0d9d86f6ee1e9ce6a20dd8d91205e66ba

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really, as this is about the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a simple editor change that would be applicable to most projects.

**Comment by YuriSizov** [comment]
We have a big PR that addresses this among other things, but it's in a bit of a limbo: https://github.com/godotengine/godot/pull/27988. However, its implementation of the feature would be preferable to what is proposed here.

**Comment by poohcom1** [comment]
> We have a big PR that addresses this among other things, but it's in a bit of a limbo: [godotengine/godot#27988](https://github.com/godotengine/godot/pull/27988). However, its implementation of the feature would be preferable to what is proposed here.

Ah, that is definitely what I am looking for, thanks for pointing that out. Wasn't aware that there was already an on-going PR for this, so I'll close this thread now.

**Comment by YuriSizov** [comment]
Let's keep it open. A proposal can be closed when the feature is implemented and merged. And in this case that PR may need to be salvaged and implemented in steps, one of which can be adding a method selector.

**Comment by tom-jk** [comment]
I don't think godot supports this natively at the moment, but assuming it might one day:
how about an editable combo box?

![godot_gp_5193_editablecombobox0](https://user-images.githubusercontent.com/64640811/185477661-4fa0cd2e-0296-42dc-8bd9-38b7728c2e91.png)

you could type a name in, or set one from a dropdown of existing function names.

This would save a click and a little mouse travel time over opening a dialog.

**Comment by Frontrider** [comment]
Might be closable, godot 4 supports this.
