### ISSUE TITLE
Tweak dictionary printing to avoid confusion with arrays

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#5198]
*Related to https://github.com/godotengine/godot-proposals/issues/538.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

This code prints various dictionaries and arrays:

```gdscript
print({})
print([])
print({12: 34})
print([12, 34])
print(["12:34"])
```

It results in the following, where arrays and dictionaries aren't always easily distinguishable at a glance. (This may be more of a problem if you have low vision, but even if you have good vision and have to work while tired, you may not immediately notice it.)

![image](https://user-images.githubusercontent.com/180032/185433482-b03ecfc5-bfac-4fb3-94a1-71c6bd6836f3.png)

If you use the 75% editor scale (which is the default on small displays like 1366×768), it's even harder to distinguish `[]` and `{}` at a glance:

![image](https://user-images.githubusercontent.com/180032/185433823-bc9bdbd8-bd73-48ba-9709-18a6917e2a6f.png)

While the string-in-array case is now nicely handled in 4.0, other cases like empty/arrays can still look confusing at a glance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Tweak dictionary printing to avoid confusion with arrays.

This is complementary to proposals like https://github.com/godotengine/godot-proposals/issues/538 – both can coexist at the same time.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change dictionary printing to feature leading and trailing spaces, and add a space between key and value:

#### Before

```
{}
[]
{12:34}
[12, 34]
["12:34"]
```

#### After

```
{ }
[]
{ 12: 34 }
[12, 34]
["12:34"]
```

For reference, this is the approach used by Firefox's web developer tools:

![image](https://user-images.githubusercontent.com/180032/185435188-51b2bf31-20a5-4596-8552-821aa4dc2c62.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving project debug-ability and troubleshooting. Let's make "my code doesn't work" moments a bit less frustrating :slightly_smiling_face:

**Comment by RabbitB** [comment]
Now that the output panel supports colors and unicode, it might be a smart idea to highlight them differently so they stand out from each-other. It's not a perfect solution, but there should be a set of color-blind friendly options that allow for quick distinction between printed arrays and dictionaries.

Human vision is an iterative process--while not a direct 1:1 comparison, you can think of it as your brain interprets what you see in passes. Colors are one of the very first things to be processed along with motion, followed by shapes, etc.

**Comment by Calinou** [comment]
> Now that the output panel supports colors and unicode, it might be a smart idea to highlight them differently so they stand out from each-other. It's not a perfect solution, but there should be a set of color-blind friendly options that allow for quick distinction between printed arrays and dictionaries.

I think pretty-printing is best left to a different function, as mentioned in https://github.com/godotengine/godot-proposals/issues/538.
