### ISSUE TITLE
Rename Position* Nodes to Marker*

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#5199]
### Describe the project you are working on

Typical 2D Godot game, taking a look at Godot 4.

### Describe the problem or limitation you are having in your project

Godot 4 changes a lot of **Node** names to be more explicit and explanatory. Despite this, through the transition, one **Node** feels like has been left out...

The name of **Position2D** and **Position3D** is beyond unusual. 
Firstly, It's vague! What is it? The Node that has a position? Don't all 2D/3D nodes have that?
Indeed, it shares its name with one of its properties. Thus, assuming its name is unchanged, when fetching the `position` _(you're going to probably do that to make use of its specialty)_, it's totally possible to be in this situation:
```GDScript
@onready var position_2d := $Position2D
...
position_2d.position += Vector2.ONE
```

Needless to say, this is very confusing, especially for learning users that have yet to properly grasp the concept of Nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As brought up in https://github.com/godotengine/godot/issues/54161#issuecomment-1202585534.

Rename these nodes to **Marker**. Therefore:

- **Position2D** -> **Marker2D**
- **Position3D** -> **Marker3D**

This name is much simpler and suits their purpose to a tea. They're Nodes, used to mark noteworthy spots. The icon fits much better, too!

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/66727710/184504073-b4077050-812f-4a2e-80db-85aa86eba655.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It cannot. At least, not properly. One can just live with the current name, as is, and rename every **Position** node to to **Marker** on their own.

### Is there a reason why this should be core and not an add-on in the asset library?

**Position2D** and **Position3D** are core classes.

**Comment by mieldepoche** [comment]
I would be happy with Marker instead of Position.

But why not remove Markers in favor of having a toggle on `Node2D/Node3D` to toggle the display of the axes instead?
The fact that the marking feature ("this point is important") is separated in inheritance from the transform feature ("this point exist") is weird imo.

**Comment by aaronfranke** [comment]
I think this is a good idea. I thought about it before, since the name Position is indeed confusing, and the name that came to mind at the time was Gizmo2D and Gizmo3D. However, I like the name Marker a lot better. 👍

**Comment by Mickeon** [comment]
Edited the proposal accordingly.

**Comment by Riteo** [comment]
> I would be happy with Marker instead of Position.
> 
> But why not remove Markers in favor of having a toggle on `Node2D/Node3D` to toggle the display of the axes instead? The fact that the marking feature ("this point is important") is separated in inheritance from the transform feature ("this point exist") is weird imo.

Nah, the base nodes should stay as pure and clean as possible IMO. `Marker*`/`Position*` nodes have a clearly defined scope: marking positions.

**Comment by Diddykonga** [comment]
> Nah, the base nodes should stay as pure and clean as possible IMO. Marker*/Position* nodes have a clearly defined scope: marking positions.

I just want to point out, this is not a clearly defined purpose, and personally I would remove these as they are a waste of a class name. Every Node2D/Node3D already has an transform and therefore a position. 

As suggested if the debug/visual information is the only unique thing, and could be relevant for other classes to also posses, then it should just be added to Node2D/Node3D.

**Comment by Mickeon** [comment]
The class could be firstly and foremost renamed, and then expanded upon with more features.

**Comment by Diddykonga** [comment]
> The class could be firstly and foremost renamed, and then expanded upon with more features.

If we wish to keep the Node, then I suggest what @aaronfranke mentioned above, with `Gizmo2D/3D`. 
An editor-only node for custom Gizmo creation/display, although it would need to be quite complex to support all the different types of Gizmos developers could want.
