### ISSUE TITLE
Rename platform JavaScript to Web

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot-proposals#5205]
### Describe the project you are working on

-

### Describe the problem or limitation you are having in your project

I plan to develop JavaScript bindings for godot. `JavaScript` is a well-known programming language, but in godot it represents the name of a platform. 

Namespaces are not supported in godot, so I can't provide another JavaScript class to represent real JavaScript. Even if I named it something else, existing JavaScript would be misleading.

What about rename it to `Web`?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As the name suggests, intuitive

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This isn't anything difficult, but will break compatibility, so the name change before the 4.0 release is an opportunity.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by dsnopek** [comment]
At a high-level this makes sense: the web browser is the platform, not the Javascript language.

> I plan to develop JavaScript bindings for godot.

FYI, there are already a couple of Javascript bindings for Godot:

- https://github.com/godot-js/godot-js
- https://github.com/Geequlim/ECMAScript

**Comment by YuriSizov** [comment]
@dsnopek Your second link deserves a second look 😛

**Comment by dsnopek** [comment]
Heh, ah, yeah... That link should probably be promoted to the proposal description! And "I plan to develop" should perhaps be changed to "I have developed"? :-)

**Comment by Faless** [comment]
From https://github.com/godotengine/godot/pull/65094#issuecomment-1235322319 :

> The JavaScript singleton is mainly an interface for interacting with JavaScript code, like JavaClassWrapper in the android platform, so I'm not sure calling it Web* makes much sense.
> Maybe JavaScriptWrapper or JavaScriptBridge?

**Comment by Geequlim** [comment]
> Maybe JavaScriptWrapper or JavaScriptBridge ?

`JavaScriptBridge` looks more suitable. 

The `JavaScriptObject` will be confusing if there is a `JavaScript` class representing the script resource of JavaScript binding. How about rename the `JavaScriptObject` to `WebObject`, `WebNativeObject` or any suggestion ?

**Comment by Faless** [comment]
> The `JavaScriptObject` will be confusing if there is a `JavaScript` class representing the script resource of JavaScript binding.

Well, tbh, a `Script` resource called `JavaScript` is confusing anyway, I would assume it's `Java` bindings in case, not JS.
