### ISSUE TITLE
Rename `str2var` and similar functions to `str_to_var`

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#5206]
### Describe the project you are working on

A typical 2D game, testing Godot 4 and introducing the engine to some friends.

### Describe the problem or limitation you are having in your project

The **`@GlobalScope`** offers some useful functions to quickly convert values into other values. For example, `str2var()`. These are mostly fine, but the "_2_" in the middle of their name presents inconsistencies with the way other methods and properties are defined across Godot 4.

For one, it's not always used. `String.bin_to_int()` exists, not `bin2int()`. Likewise, `Object.to_string()` exists, but not `2string()`.

Second, perhaps more importantly, using the number "2" over "to" because they're homophones isn't quite correct English. It certainly looks nice, as an "old" programming convention, but it can prove odd to read for non-English speaking users. The "_2_" doesn't bear significant meaning, unlike other existing variants, classes, functions...

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

| Before | After|
| --------| ---------|
| `var2str` | `var_to_str`
| `str2var` | `str_to_var`
| `bytes2var` | `bytes_to_var`
| `bytes2var_with_objects` | `bytes_to_var_with_objects`
| `var2bytes` | `var_to_bytes`
| `var2bytes_with_objects` | `var_to_bytes_with_objects`
| `linear2db` | `linear_to_db`
| `db2linear` | `db_to_linear` 
| `deg2rad` | `deg_to_rad`
| `rad2deg` | `rad_to_deg`

The wording of these renames is not exact.
There indeed is an argument to be made about whether or not it's even worth it to shorten all words at this point. It may be totally valid, in fact, to rename some functions to `variant_to_string`, for example, to reduce confusion.

But there needs to be a good balance between actual readability, and verbosity. Fully writing some of these can prove annoying in some cases, **especially** if what the shortened words mean can be inferred by context (E.g. `deg_to_rad` can only mean `degrees_to_radians`, as it's about working angles, names of passed variables that are called "angle, rotation, yaw, tilt, pitch...", and it's also pretty common to use).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```GDScript
var_to_str(a).length()
type_of(str_to_var(b))

bytes_to_var(c)
var_to_bytes_with_objects(d).compress()

db_to_linear(e) * 0.75


var vector = Vector.UP.rotated(rad_to_deg(user_input))

```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Technically? You can create an Autoload, define static methods with the new names, or just keep sticking with the current naming scheme.

### Is there a reason why this should be core and not an add-on in the asset library?

These methods are core.

**Comment by Lielay9** [comment]
> Second, perhaps more importantly, using the number "2" over "to" because they're homophones isn't quite correct English. It certainly looks nice, as an "old" programming convention, but it can prove odd to read for non-English speaking users. The "2" doesn't bear significant meaning, unlike other existing variants, classes, functions...

As a non-native English speaker and someone who often teaches non-native speakers, the above holds true. It isn't a great obstacle by any means but it sticks out as a little odd as it doesn't adhere to the naming convention used elsewhere in the engine. I think the spelt-out name would be more beginner-friendly and improve readability. I guess it is just a decision between writing extra 3 characters and clarity.

**Comment by just-like-that** [comment]
> Second, perhaps more importantly, using the number "2" over "to" because they're homophones isn't quite correct English.

I'm also opting for using plain English for the sake of readability and align it with the rest of all commands w/o any fanciness.
Next some users like to use 4 in favor of "for" or even 8 instead of "at" ... Mercy!

**Comment by Mickeon** [comment]
Less than 24 hours until a final decision on the matter has to be made before Godot 4 beta...

**Comment by just-like-that** [comment]
> Less than 24 hours until a final decision on the matter has to be made before Godot 4 beta...

There is another vital argument to this:
In search help nothing shows up if you enter just "2" but many methods show up if you enter "to".
The search needs at least two characters. So that's a real time safer if you have forgotten the exact name and it's enough to enter: "to" (!)

**Comment by Mickeon** [comment]
I do understand the core argument, but think about the _reason_ as to why you frequently forget these names. Even if it's the core argument, the proposal isn't just about converting a "2" to "to", it's also about making these methods clearer and easier to understand.

**Comment by Mickeon** [comment]
In fact, now that I am thinking about it absolutely last minute, *why* is `str2var()` even here? It could just be a **String** method called "`to_variant()`". `str()` and `var2str()` pretty much serve the same purpose, too...
