### ISSUE TITLE
Better fonts and comment functionality in Visual Script . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#521]
**Describe the project you are working on:**
I am working on a Tomb Raider game, and a RTS, StarCraft-like . . ::)

**Describe the problem or limitation you are having in your project:**
I like to use visual script, but right now making comments is really tough, it takes a lot of time, the ' enter ' at the end of each line, has to be made manually, and the boxes are tough to size, often they get ' lost ' in other boxes, and the ' corner ' one can move them with, is very small . . . I like writing good documentation, for my scripts, for later, and others to see, study . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If we got a functionality, where one could write directly on the script canvas, and had some better fonts, more readable, it would be a lot nicer . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It would just be a text editor, sort of, where one could write quickly on the screen, almost like grease pencil, and have a few fonts, nice ones . .

![2020-02-25 1420 Script Boxes](https://user-images.githubusercontent.com/61069740/75251041-154bd600-57da-11ea-8d6d-4131734ba9d3.jpg)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Right now I don't think you can change the font, or make text bold, or italic . . As an artist-minded dev, having the ability to make my scripts look nice, and inviting, also for tutorials where youtubers could stop the video, and read the box, along with the tutorial, if needed, would really make me happy . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, for me it would really be nice, a faster, more user-friendly comment system, so I can make better documentation, for myself, also if others ask for my scripts, they can download them with good instructions, or for showing others, on a team . .

It's a small request, but it would be really nice, very helpful . . :) As an artist, I like beautiful, appealing scripts, so a few more fonts, ability to make bold, italic, or underlined, and different sizes . . <3 Then, it'd be an artists dream, Visual script . . . I know this isn't super-techy, maybe there are some MIT fonts, that are nice, it would just make it much nicer, also for later, remembering what the boxes do . . . And, also other users, for sharing . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
