### ISSUE TITLE
Add support for multiple Android custom build export directories

### ISSUE THREAD

**Issue by novalis** [godotengine/godot-proposals#5212]
### Describe the project you are working on

A series of small mobile-first games: the first one, [Surfwords](https://surfwords.com), is available now.  

### Describe the problem or limitation you are having in your project

I want to have two different Android exports (using custom templates):

One has a "Unique name" of com.surfwords.surfwords and the other of com.surfwords.surfwordstest.  I want this so that I can have both the release version and the testing version installed at the same time on my phone.  I also want them to have different "Name" fields (so that I can tell which one I'm tapping to run!).  Unfortunately, there's only one "android" subdirectory in my Godot project, so whichever one I've exported last overwrites what the other one has done.  This is annoying, since some of the files under `android/` are under version control (and I don't know which ones are supposed to be and which ones aren't).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If it were possible to have two different android directories, one per export, that would make my life simpler.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The directory would be just another field in the android export screen

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Of course, I could have different git branches and merge frequently, or maybe it turns out that everything that gets overwritten shouldn't go into version control -- but the gitignore functionality for Android doesn't seem to be quite there yet, per [this comment](https://github.com/godotengine/godot-proposals/issues/1813#issuecomment-926983202) -- and the gitignore linked from that comment wouldn't work for me, because my build.gradle file has custom stuff to work around Play Games Services v2 badness. 

### Is there a reason why this should be core and not an add-on in the asset library?

The android path seems to be controlled by core Godot; I'm not sure an add-on could easily fix this, and it's something that I would imagine every Android developer would want.

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/88297
