### ISSUE TITLE
Add `Node` attribute for C#

### ISSUE THREAD

**Issue by tvardero** [godotengine/godot-proposals#5216]
### Describe the project you are working on

Simple project with C# scripts.

```c#
public class MyNode : Node
{
    public Camera MyCamera { get; set; }
    
    public override void _Ready()
    {
        Camera = GetNode<Camera>("MyCamera");
    }
}
```

### Describe the problem or limitation you are having in your project

I don't like to use `GetNode<MyNodeClass>("NodeName")`. This code feels to be a boilerplate to me. Also, sometimes I need to override `_Ready` only the one purpose: to assign my nodes to properties.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Attribute `Node`, which will automatize node assignment to class' properties. Usage example:

```c#
public class MyNode : Node
{
    [Node]
    public Camera MyCamera { get; set; }
    
    public override void _Ready()
    {
        // Camera = GetNode<Camera>("MyCamera"); // <-- Don't need this anymore, already have my camera before _Ready execution
    }
}
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. Before `_Ready` is executed, Godot uses [C# reflection](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/reflection) to get all members of the class.
2. If class' member is a property and has attribute `Node` - go to step 3, otherwise - scan next class member.
3. Godot uses property's type (Camera, KinematicBody, etc., or any other custom type which inherits from Godot's nodes types) to scan scene for a node of the same type. If this node is singular - assign it to the property. If no node is found - throw KeyNotFound, InvalidOperation or something else. If the are >1 nodes of the type - go to step 4. 
4. Godot uses property's name. For example if we have `Camera1P` and `Camera3P`, both of type `Camera`, we use property's name to determine which camera to assign. If no node is found - throw KeyNotFound, InvalidOperation or something else.

`NodeAttribute` could have an argument to change it behavior: `bool setNullOnNotFound = false`. If it was set to `true`, then Godot skips the property on step 3 when Godot doesn't find any node of property's type. If we are in nullable context and property is not of nullable reference type - generate a warning in console.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

My proposal is mostly a syntax sugar.

### Is there a reason why this should be core and not an add-on in the asset library?

I can't say could this be an external Nuget package or should it be a core feature.

**Comment by raulsntos** [comment]
You might be interested in https://github.com/31/GodotOnReady which allows you to do this with an `[OnReadyGet]` attribute:

```csharp
public class MyNode : Node
{
    [OnReadyGet("MyCamera")]
    public Camera MyCamera { get; set; }
}
```

This NuGet package is already available for 3.x.

If we were to add this feature to the engine I think it'd be better to add it through an OnReady attribute which more closely resembles the `@onready` annotation from GDScript than the `[Node]` attribute you propose.

**Comment by rick551a** [comment]
This is a good idea, my onReady is choc full of GetNode("...") statements.

A Question:

What would be the proposed syntax for nested nodes?
For example, if myCamera was nested beneath a springArm node?

**Comment by tvardero** [comment]
> This is a good idea, my onReady is choc full of GetNode("...") statements.
> 
> A Question:
> 
> What would be the proposed syntax for nested nodes? For example, if myCamera was nested beneath a springArm node?
@rick551a 

If your `springArm` has its own class (lets name it `SpringArm`), then
```c#
class MainNode : Node
{
    [Node]
    public SpringArm Arm { get; set; }
    
    public Camera MyCamera => Arm.MyCamera;
}

class SpringArm : Node
{
    [Node]
    public Camera MyCamera { get; set; }
}
```

If it does not have a class, then i'm kinda out of ideas.

**Comment by tvardero** [comment]
Closing as an duplication of https://github.com/godotengine/godot-proposals/issues/2425.
