### ISSUE TITLE
Add collision inclusions to RayCast (opposite of exclusions)

### ISSUE THREAD

**Issue by Ivorforce** [godotengine/godot-proposals#5219]
### Describe the project you are working on

A 3D game with custom gravity.

### Describe the problem or limitation you are having in your project

Ray casts cannot be limited to specific collision objects. They can be limited through a number of parameters (blacklists, layers, area or body), but not with a whitelist. When a ray should be cast against a known object, this has to be worked around.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Providing a whitelist could limit collisions to one or a list of known and expected objects.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A new parameter `whitelist = null` could be added to relevant functions in [PhysicsDirectSpaceState](https://docs.godotengine.org/en/stable/classes/class_physicsdirectspacestate.html), as well as [RayCast](https://docs.godotengine.org/en/stable/classes/class_raycast.html#class-raycast). 

One might consider exposing [PhysicsShapeQueryParameters3D](https://github.com/godotengine/godot/blob/edf07ee7a66ae4405c80b658434ee53f85e8fa88/doc/classes/PhysicsShapeQueryParameters3D.xml) for callers to construct, such that these calls are simplified.

In Godot 4, where that object is already exposed, a whitelist parameter [is still not provided](https://docs.godotengine.org/en/latest/classes/class_physicspointqueryparameters3d.html#class-physicspointqueryparameters3d).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It has [previously been proposed](https://www.reddit.com/r/godot/comments/hzen7x/comment/fzio3pw/?utm_source=reddit&utm_medium=web2x&context=3) to manipulate layers temporarily during checks.

An alternative solution would be gathering all objects from the scene tree and adding them to the blacklist. Then, the target objects are erased before calling the function:

```gdscript
func get_all_children(in_node, arr:=[]) -> Array:
	arr.push_back(in_node)
	for child in in_node.get_children():
		arr = get_all_children(child, arr)
	return arr

func intersect_ray_to(position: Vector3) -> Dictionary:
	var exclude_objs := get_all_children(get_tree().root)
	exclude_objs.erase(collision_body)
	return get_world().direct_space_state.intersect_ray(position, global_transform.origin, exclude_objs)
```

Either solution is very harsh on performance.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be provided by a library without copying function implementations.

**Comment by KoBeWi** [comment]
What's the use-case for colliding only with specific objects?
Layers are a feasible solution. There's 32 of them, while most projects only use less than 10.

**Comment by Zireael07** [comment]
@KoBeWi I suppose raycasts for AI detecting obstacles and the like.

In my own FPS game, I use raycasts to detect background things that should affect player's ability to hide (walls, trees etc.)

But yes, seconding layers suggestion. Haven't seen a project that would require 32 of them either!

**Comment by Ivorforce** [comment]
There are plenty of use-cases. AI / visibility testing may be one, but in general casting rays against singular shapes is something I do in my games on the regular.

I thought about your comments a bit more and found a decent solution using the last layer as a one-off toggle:

```python
func intersect_ray_only(from: Vector3, to: Vector3, objects: Array) -> Dictionary:
	var one_off_layer := 1 << 31
	
	for object in objects:
		object.collision_layer |= one_off_layer
		
	var intersection := get_world().direct_space_state.intersect_ray(from, to, [], one_off_layer, true, true)

	for object in objects:
		object.collision_layer ^= one_off_layer

	return intersection
```

I'm ok with this since it's decently fast. I wouldn't mind dedicated functionality for this feature, but feel free to close the issue if you don't think it's needed.

**Comment by Mickeon** [comment]
That's great there's a way to solve your issue. It's better to avoid adding features not many users are going to find an use of.
