### ISSUE TITLE
Rename PhysicsMaterial to PhysicsSettings (or something else)

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#5221]
### Describe the project you are working on

A typical 2D project, getting my hands in Godot 4 as it's approaching beta.

### Describe the problem or limitation you are having in your project

Although I do not agree with the solution proposed in [this discussion](https://github.com/godotengine/godot-proposals/discussions/5215), it has brought up a nice point.

I never personally had an issue with it. **PhysicsMaterial** looks to be the industry standard, it's reasonably intuitive, and I got used to it. But, I can totally understand the confusion, from a beginning user point of view:
Among all Resources ending in "_Material_", **PhysicsMaterial** is the only one not inheriting from the base **Material** class.
![image](https://user-images.githubusercontent.com/66727710/185783884-a75d3998-4ac5-4b0b-bb56-98f8412ecf97.png)
Most other classes don't leave much space for confusion _(e.g. every **Node** ending with "_Container_" inherits from **Container**)_, or at least, are not using the same word to describe two different sets of attributes. In this case, how the item is _visualised_, versus how it _behaves_ in a physics simulation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename **PhysicsMaterial** to **PhysicsSettings**.

Or something else, so long as it no longer contains _"Material"_ in its name.

I chose this name to represent this proposal because **EditorSettings** and **LabelSettings** already exist as resources, whose naming scheme make their meanings are rather clear. However, I do understand that **PhysicsSettings** can be easily mistaken for a project setting, and the adjacent double "S" may prove annoying to write.

Other suggestions that came to my mind as I was making this proposal include "_PhysicsAttributes_", "_PhysicsProperties_"

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```GDScript
var settings = PhysicsSettings.new()
settings.friction = 0.5
physics_settings_override = settings

```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really.

### Is there a reason why this should be core and not an add-on in the asset library?

**PhysicsMaterial** is a core class.

**Comment by lyuma** [comment]
I disagree with this proposed rename, physics materials are analogous to visual materials, so renaming one would create confusion. PhysicsSetting doesn't seem like the name for a resource, but it sounds like something that would be global, like ProjectSettings or EditorSettings.

Every other major game engine calls this concept a PhysicsMaterial. Physics libraries also usually have a "material" concept, or refer to the properties here as "material properties".

I also disagree with renaming Material to GraphicsMaterial because it would break a lot of code and for very little benefit except reducing a bit of confusion when you have a class that needs both graphics and physics material.

**Comment by Zireael07** [comment]
> Every other major game engine calls this concept a PhysicsMaterial.

Agreed. Let's not have a repeat of the physics body naming..

**Comment by Mickeon** [comment]
I concur too, but I will still keep the proposal up for completeness' sake

**Comment by YuriSizov** [comment]
Well, I guess this is still rejected then.
