### ISSUE TITLE
Implement AudioStreamRoundRobin

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#5231]
### Describe the project you are working on

3D platformer

### Describe the problem or limitation you are having in your project

It is necessary to generate an array and cache each time to play audio at random.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

With AudioStreamRoundRobin, which can play audio at random, it would be easy to prepare and playback several patterns of footsteps or voices.

In addition, presuming the AudioTrack commented on in https://github.com/godotengine/godot/pull/55218#issuecomment-1195201039 is improved, it is expected to work well with the AudioTrack in Animation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would be implemented similar to AudioStreamPlaylist in https://github.com/godotengine/godot/pull/64488.

The difference is that only one audio from the list will be played each time, and it is possible to set the percentage of audio occurrence for each audio.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Creating a controller is not that difficult, but combining it with AudioTrack is difficult.

### Is there a reason why this should be core and not an add-on in the asset library?

The audio stream relates deeply to the core.

**Comment by KoBeWi** [comment]
This already exists. It's called AudioStreamRandomizer.

**Comment by TokageItLab** [comment]
@KoBeWi Wouldn't that just change the pitch, and it be impossible to replace the audio stream itself?

**Comment by KoBeWi** [comment]
You can disable pitch randomization. And it supports adding and removing streams and also you can specify in what order they are played. I'd suggest reading the docs :v

**Comment by TokageItLab** [comment]
Oh, I didn't notice it because it was folded. That might be enough, thanks.
