### ISSUE TITLE
Readd a method to center window (lost during DisplayServer refactoring)

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot-proposals#5232]
### Describe the project you are working on

Works for every project type.

### Describe the problem or limitation you are having in your project

In Godot 3.x, there was OS.center_window(). Godot 4.0 does not have any equivalent function as far as I can find, but obviously still has the ability to center the window as when the project is run initially it is centered.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This restores the functionality already found in Godot 3.x.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Running this function will place the window in the center of the screen.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be, but the function already existed in Godot 3.x.

### Is there a reason why this should be core and not an add-on in the asset library?

Functionality existed in Godot 3.x.

**Comment by Calinou** [comment]
The removal of this function is probably not intentional, so feel free to open a pull request to readd it :slightly_smiling_face:

**Comment by ztc0611** [comment]
@Calinou any tips as to where the code that runs when the project opens is, so I can look at that for tips? That window always opens centered on the screen so I presume something is up there.

**Comment by YuriSizov** [comment]
@ztc0611 Probably should be `DisplayServer.window_set_centered` and `DisplayServer.window_is_centered`.

**Comment by ztc0611** [comment]
Alright I have `DisplayServer.window_set_centered` and `DisplayServer.window_is_centered` implemented on macOS. I should be able to do Windows too, but I will require some assistance with Linux, as I don't have a Linux computer to 100% confirm the code works. Once I finish Windows, should I open the PR and note in the body that a Linux tester is required, or is there a different procedure for this?

**Comment by YuriSizov** [comment]
Yes, go ahead and open a PR and we can ping Linux folk, of which we have plenty, to offer a hand.

**Comment by ztc0611** [comment]
Even if my own attempt at resolving this is not used, I would really appreciate the return of this function. 🙁
