### ISSUE TITLE
Add ability to control rotation direction in AnimationPlayer

### ISSUE THREAD

**Issue by poohcom1** [godotengine/godot-proposals#5245]
### Describe the project you are working on

A 2D action side-scroller with a lot of cutout animations

### Describe the problem or limitation you are having in your project

When blending between two animations with rotation, the rotation will always blend between absolute degree values. However, in most cases, the blend direction I want is between the *nearest* angles. This managing multiple animations very hard as you have to constantly keep track of what the final rotation value is to prevent blending in the wrong direction.

Furthermore, if a node rotates a 360+ degree, there's no way to return to the original rotation without doing a full reversal. I tried multiple workarounds like resetting the rotation between animation change or using discrete update mode, but couldn't find a working solution that would allow blends along with smooth animation.

![anim_player_rot_example_compress](https://user-images.githubusercontent.com/74857873/186396835-71bf4a20-d8d4-4b10-9cfa-0f5296b90e0f.gif)
*After the third animation, the rotation goes from 408 to 11, which looks very unnatural*

Related old issue: https://github.com/godotengine/godot/issues/18049

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the ability to control the way rotation blends are done, either absolute interpolation (the existing one) or nearest angle interpolation. Aside from blends between animation, this could also be applied to interpolation between keyframes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

While the [old issue](https://github.com/godotengine/godot/issues/18049) suggested making a new track type, I think the more logical place to add this option is in the keyframe inspector. 

![anim_player_rot_example2](https://user-images.githubusercontent.com/74857873/186399903-c36797bb-505f-48a4-aeff-8a3e13c74280.png)

This would allow fine grain control over frame interpolation, or animation blends if it is the final frame. This option should probably only appear for rotation tracks (or are there other properties with similar looping nature?).

The option UI could be a boolean checkbox or a dropdown. Also, I'm not sure if terminology I've been using (absolute/relative/nearest) is correct or the most appropriate, so some suggestions would be nice.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

AFAIK there's no easy way around this if you want smooth animation and blends. 

### Is there a reason why this should be core and not an add-on in the asset library?

This would be useful to anyone doing 2D puppet/cutout animations.

**Comment by TokageItLab** [comment]
Since ValueTrack is not exclusive to 2DRotation, I feel it would make more sense to implement a new track type for this.
Or maybe Node2D needs a rotation that does not exceed 180 degrees or a Complex type, just like Node3D::RotationEditMode.
