### ISSUE TITLE
[3.x] BakedLightmap force scale of lightmap texture 

### ISSUE THREAD

**Issue by marcinn** [godotengine/godot-proposals#5253]
### Describe the project you are working on

A Quake-like first person shooter with maps created using TrenchBroom

### Describe the problem or limitation you are having in your project

A Quake-like game, where level design requires a lot of lights (omni or spots, and optionally directional light), gives the best looking results, the best performance, and possibility to use many lights for a big level mesh (without hitting the limits), when all lights are fully baked into lightmaps (direct + indirect).

The problem is that baking a lightmap takes too long time even on low settings, and can crash the editor due to out of system memory.

Problems I found in Godot Editor:
* Denoising a lightmap consumes huge amount of memory. The bigger size of lightmap texture is created, the denoiser needs more memory.
* Meshes rasterization also slows down when lightmap texture size increases. 
* Overall baking time can be very slow regardless of the quality settings.

I found that reducing the final texture size significantly speeds up baking ligths, and avoids out-of-mem crashes in denoising phase, 

It's worth mentioning that high resoultion of the lightmap is not always needed:
* When a developer wants to preview a level in a typical workflow, i.e. 1. update the level in Trenchbroom, 2. build it with Qodot, 3. bake lighting from scratch, the high resolution of light and shadows are not required. The most important is to get the overall look in a short time (and without crashes of the tool)
* Good looking lightmap resolution can be dependent on the level design. Not all levels require lightmap textures of high precision.

Since reducing the resolution of lightmaps not only gives the opportunity to improve such workflow, but actually even makes possible to work with the editor, having possibility to change the resolution of the final lightmap texture becomes necessary.  But how to reduce the lightmap texture size? There are two possibilities in Godot:
* set `lightmap_size_hint` on each MeshInstance 
* reduce default_texels_per_unit on BakedLightmap node.

The problem is that "default_texels_per_unit" are overridden by lightmap_size_hint and in most cases gives nothing, so you must adjust lightmap_size_hint manually for each mesh. This is problematic when the scene is composed of many meshes or imported via tools like Qodot.

Link to thread on the forum: https://godotforums.org/d/30799-35-i-solved-lightbaking-issues

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I solved the issue by introducing an experimental parameter to BakedLightmap: `force_lighmap_scale`. It scales down / up the final lightmap texture size.

![image](https://user-images.githubusercontent.com/139032/186500817-9da94e67-3f64-48f8-8d26-c312b6e63084.png)

Setting it to 0.1 or 0.2 results in very fast light baking and solves crashing issues during denoising, also for high quality settings. Downscaling the lightmap about 5x times gives still very good results. For my scene sized about 300 x 60 x 200 units, setting lightmap_scale to 0.2 gives final exr texture of 1024x2048 size and short baking time (about 1-2 minutes for all lights direct+indirect+shadows, HDR, color, comparing to not achieving the result due to crash of the editor).

This proposal is fully backward compatible, when `force_lightmap_scale` is set to `1.0` (a default value).

My proposal is to add this property to the BakedLightmap node, but maybe called a `Lightmap Scale`. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is my experimental patch:

```diff
diff --git a/doc/classes/BakedLightmap.xml b/doc/classes/BakedLightmap.xml
index 5551290010..57dc4096d9 100644
--- a/doc/classes/BakedLightmap.xml
+++ b/doc/classes/BakedLightmap.xml
@@ -54,6 +54,9 @@
 		<member name="default_texels_per_unit" type="float" setter="set_default_texels_per_unit" getter="get_default_texels_per_unit" default="16.0">
 			If a baked mesh doesn't have a UV2 size hint, this value will be used to roughly compute a suitable lightmap size.
 		</member>
+		<member name="force_lightmap_scale" type="float" setter="set_force_lightmap_scale" getter="get_force_lightmap_scale" default="1.0">
+            Force scale generated lightmaps (scale up/down UV2 size hint / default_texels_per_unit)
+		</member>
 		<member name="environment_custom_color" type="Color" setter="set_environment_custom_color" getter="get_environment_custom_color">
 			The environment color when [member environment_mode] is set to [constant ENVIRONMENT_MODE_CUSTOM_COLOR].
 		</member>
diff --git a/scene/3d/baked_lightmap.cpp b/scene/3d/baked_lightmap.cpp
index 3b4147183b..427b3e7397 100644
--- a/scene/3d/baked_lightmap.cpp
+++ b/scene/3d/baked_lightmap.cpp
@@ -318,7 +318,7 @@ Size2i BakedLightmap::_compute_lightmap_size(const MeshesFound &p_mesh) {
 		uv_area = 1.0;
 	}
 
-	int pixels = Math::round(ceil((1.0 / sqrt(uv_area)) * sqrt(area * default_texels_per_unit)));
+	int pixels = Math::round(ceil((1.0 / sqrt(uv_area)) * sqrt(area * default_texels_per_unit))) * force_lightmap_scale;
 	int size = CLAMP(pixels, 2, 4096);
 	return Vector2i(size, size);
 }
@@ -655,6 +655,10 @@ BakedLightmap::BakeError BakedLightmap::bake(Node *p_from_node, String p_data_sa
 			lightmap_size = _compute_lightmap_size(mf);
 		}
 		lightmap_size *= mf.lightmap_scale;
+        float _nw = lightmap_size.x * force_lightmap_scale;
+        float _nh = lightmap_size.x * force_lightmap_scale;
+        lightmap_size.x = int(_nw);
+        lightmap_size.y = int(_nh);
 
 		Lightmapper::MeshData md;
 
@@ -1143,10 +1147,18 @@ void BakedLightmap::set_default_texels_per_unit(const float &p_bake_texels_per_u
 	default_texels_per_unit = MAX(0.0, p_bake_texels_per_unit);
 }
 
+void BakedLightmap::set_force_lightmap_scale(const float &p_bake_force_lightmap_scale) {
+	force_lightmap_scale = MAX(0.001, p_bake_force_lightmap_scale);
+}
+
 float BakedLightmap::get_default_texels_per_unit() const {
 	return default_texels_per_unit;
 }
 
+float BakedLightmap::get_force_lightmap_scale() const {
+	return force_lightmap_scale;
+}
+
 void BakedLightmap::set_capture_enabled(bool p_enable) {
 	capture_enabled = p_enable;
 	_change_notify();
@@ -1541,6 +1553,9 @@ void BakedLightmap::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("set_default_texels_per_unit", "texels"), &BakedLightmap::set_default_texels_per_unit);
 	ClassDB::bind_method(D_METHOD("get_default_texels_per_unit"), &BakedLightmap::get_default_texels_per_unit);
 
+	ClassDB::bind_method(D_METHOD("set_force_lightmap_scale", "factor"), &BakedLightmap::set_force_lightmap_scale);
+	ClassDB::bind_method(D_METHOD("get_force_lightmap_scale"), &BakedLightmap::get_force_lightmap_scale);
+
 	ClassDB::bind_method(D_METHOD("set_capture_propagation", "propagation"), &BakedLightmap::set_capture_propagation);
 	ClassDB::bind_method(D_METHOD("get_capture_propagation"), &BakedLightmap::get_capture_propagation);
 
@@ -1566,6 +1581,7 @@ void BakedLightmap::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "use_color"), "set_use_color", "is_using_color");
 	ADD_PROPERTY(PropertyInfo(Variant::REAL, "bias", PROPERTY_HINT_RANGE, "0.00001,0.1,0.00001,or_greater"), "set_bias", "get_bias");
 	ADD_PROPERTY(PropertyInfo(Variant::REAL, "default_texels_per_unit", PROPERTY_HINT_RANGE, "0.0,64.0,0.01,or_greater"), "set_default_texels_per_unit", "get_default_texels_per_unit");
+	ADD_PROPERTY(PropertyInfo(Variant::REAL, "force_lightmap_scale", PROPERTY_HINT_RANGE, "0.001,16.0,0.01,or_greater"), "set_force_lightmap_scale", "get_force_lightmap_scale");
 
 	ADD_GROUP("Atlas", "atlas_");
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "atlas_generate"), "set_generate_atlas", "is_generate_atlas_enabled");
@@ -1616,6 +1632,7 @@ BakedLightmap::BakedLightmap() {
 	extents = Vector3(10, 10, 10);
 
 	default_texels_per_unit = 16.0f;
+	force_lightmap_scale = 1.0f;
 	bake_quality = BAKE_QUALITY_MEDIUM;
 	capture_quality = BAKE_QUALITY_MEDIUM;
 	capture_propagation = 1;
diff --git a/scene/3d/baked_lightmap.h b/scene/3d/baked_lightmap.h
index b5a1969175..67045a3444 100644
--- a/scene/3d/baked_lightmap.h
+++ b/scene/3d/baked_lightmap.h
@@ -157,6 +157,7 @@ public:
 private:
 	Vector3 extents;
 	float default_texels_per_unit;
+	float force_lightmap_scale;
 	float bias;
 	BakeQuality bake_quality;
 	bool generate_atlas;
@@ -217,6 +218,9 @@ public:
 	void set_default_texels_per_unit(const float &p_extents);
 	float get_default_texels_per_unit() const;
 
+	void set_force_lightmap_scale(const float &p_extents);
+	float get_force_lightmap_scale() const;
+
 	void set_capture_propagation(float p_propagation);
 	float get_capture_propagation() const;
 
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often during a typical development cycle, and cannot be worked around easily with a script. 

A possible workaround will require to change `lightmap_size_hint` for all meshes used on the scene. This can be done easily with Qodot, but *only* for level-related mesh instances (created during the build stage), and *not for all* mesh instances used in the scene. Also dividing the `lightmap_size_hint` for meshes not genereated by Qodot, can give no possibility to revert to the original values.

### Is there a reason why this should be core and not an add-on in the asset library?

Lightbaking is in the core.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-proposals/issues/3893.

**Comment by marcinn** [comment]
Sorry, I didn't know your proposal. I'll try to create PRs for master and 3.x.
