### ISSUE TITLE
Add option for HDRs to cast shadows in LightmapGI

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#5266]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

In 3.5, HDR skybox can cast directional shadow if it has a sun in it(very ugly denoising, no idea why):
![image](https://user-images.githubusercontent.com/25323231/186894084-7657c96c-0d81-422b-878a-bd930de5ff12.png)

This is no longer the case in 4:
![image](https://user-images.githubusercontent.com/25323231/186894475-9b4d5e59-6d11-42ca-b98b-8e3356d91381.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

While this might be more of a quirk with 3.x's lightmapper, it would be nice if there's an option for this behavior in 4.x. I think it might be more convenient than lining up a directional light with the HDR's sun and if done right, could look better. Maybe even as good as in Blender's Cycle renderer since lightmaps in 4 are now ray-traced.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An option under LightmapGI's Tweak section is probably good enough.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Rendering is core

### Is there a reason why this should be core and not an add-on in the asset library?

See above

**Comment by Calinou** [comment]
> In 3.5, HDR skybox can cast directional shadow if it has a sun in it(very ugly denoising, no idea why):

The HDRI doesn't cast a shadow. It's just that its radiance map happens to have a contrast difference that *looks* like a shadow.

**Comment by atirut-w** [comment]
> Are you referring to the lightmapper or real-time shadowmapping?
>
> Do any other engines support this without relying on expensive raytracing? As far as I know, you need some kind of baking step to simulate this accurately at a real-time speed (VoxelGI or LightmapGI), or use SDFGI.

Lightmap shadows. Like then you have shadows cast by an emissive surface(existing feature). Massive thanks to Clayjohn for making the title more clear.

> Remember that an HDRI sky will not give you real-time shadows, while adding a DirectionalLight3D will.

Of course. If this is to be implemented, it will mostly be convenient for quick and dirty static shadows without a DirectionalLight.

**Comment by Calinou** [comment]
Closing, as this is not technically possible (and would also prevent having real-time sun shadows). If performance is a concern, use the Static bake mode for DirectionalLight3D (but remember that this also prevents having real-time sun shadows).
