### ISSUE TITLE
Name methods `_on_signal` rather than `_on_NodeName_signal` when connecting signals to self in the signal connection dialog

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#5273]
### Describe the project you are working on

prototyping with 4.0

### Describe the problem or limitation you are having in your project

![image](https://user-images.githubusercontent.com/71937306/187038611-fcf20db3-2714-429e-8296-b1b6d9be3f12.png)

Target methods are automatically named `_on_NodeName_signal`. This does not make sense when connecting a signal to the node that emits it, it should be named `_on_signal`.
Changing this manually each time is tedious.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Using the editor signal connection interface, the target method's name should be set dynamically on node selection and not contain the name of the node in cases where the receiver script is attached to the emitter node:

![image](https://user-images.githubusercontent.com/71937306/187038591-6a980117-4428-4be6-bf87-52dd3f24c51c.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The behavior should be the following:

- When clicking on a node in the selection dialog, the target method name should be automatically updated (using `_on_signal` or `_on_NodeName_signal` as needed)
- You can edit the method name manually. I you do, automatic naming stops.
- Automatic naming can be brought back without restarting the connection dialog thanks to a ![image](https://user-images.githubusercontent.com/71937306/187039538-26ddeb56-8811-4207-aecf-dbe45802e619.png) button here:
![image](https://user-images.githubusercontent.com/71937306/187039441-5cf4c897-5066-46e6-bef3-54f39f21dd9e.png)
- This button is only shown if the name was modified and hidden otherwise but it has to be drawn on top of the LineEdit to avoid changing its size when toggled.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

used often

### Is there a reason why this should be core and not an add-on in the asset library?

here already

**Comment by Mickeon** [comment]
I thought this was my silent, personal rule but it seems like it's pretty common to do. Huh...

**Comment by KoBeWi** [comment]
Check `interface/editors/default_signal_callback_name` editor setting in Godot 4.0. It allows you to customize the default callback.

**Comment by Mickeon** [comment]
But it doesn't allow you to modify it in the case the signal is attached to the same object emitting it.
