### ISSUE TITLE
Add "experimental" and "deprecated" flags for classes, methods, properties, and signals

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot-proposals#5279]
### Describe the project you are working on

Godot Engine Maintainence

### Describe the problem or limitation you are having in your project

Introducing new APIs can be problematic since without hindsight, it's hard to tell if a decision was the right one. If we add something to a point releases and large number people utilize a particular part of the API as a core part of their game, we're somewhat forced to continue supporting it for the long-term so as not to break people's projects. It would be nice if we could have a means of 'staging' certain APIs we're not completely confident about, still getting them into point releases, but giving freedom to change or break them at our discretion.

Likewise, for old APIs, we sometimes need to deprecate them, and we don't currently have a means to tell the user that while we will continue to support these APIs, to avoid using them in *new* projects and attempt to migrate away from them due to the fact that we intend to remove them in future releases of Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like to introduce an 'experimental' and 'deprecated' flag to the documentation system which will show provide a clear warning about the status of a particular API feature.  For instance, informing the user a feature is experimental and may be broken/unfinished/subject to major future revisions, or deprecated and subject to removal in a later version of the engine.

I would also propose to add editor settings for both flags which would allow experimental or deprecated API features to be hidden from the user at their discretion.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There are several ways we can communicate warnings about experimental APIs and deprecation, and the most obvious is in the documentation system. I propose adding two fields to the XML documentation: is_experimental and is_deprecated. When these flags are set to true, warning symbols and explanations can be added places such as:

In-Editor Documentation:
![fixed_doc](https://user-images.githubusercontent.com/12756047/187062103-e9338698-1c4d-4fe4-9e0b-5f5dfedefe42.png)

In-Editor Help Search:
![godot windows tools x86_64_EJz6MZ50Sk](https://user-images.githubusercontent.com/12756047/187061216-04412169-17dc-4226-b1c3-ca3a487608d0.png)

Node/Resource creation windows
![godot windows tools x86_64_ZAyH7laOoC](https://user-images.githubusercontent.com/12756047/187061186-2758a898-2ae2-4c83-97a0-363d33958e4a.png)

It would also be useful for experimental/deprecation status to show up for web documentation too, if feasible.

We may also wish to implement a flag to class properties so that experimental features will also show a warning symbol which, when clicked on, will explain to the user that the property is considered experimental. This will likely have to be added as a dedicated property flag, but it shouldn't be too difficult to support.
![experimental_property_example](https://user-images.githubusercontent.com/12756047/187061385-2c2775f8-3747-4059-9177-696b176b4b67.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it is a core feature required to built into the engine itself.

### Is there a reason why this should be core and not an add-on in the asset library?

No, it is a core feature required to built into the engine itself.

**Comment by SaracenOne** [comment]
WIP PR for this feature is avaliable here only covering experimental/deprecated classes so far https://github.com/godotengine/godot/pull/64982

**Comment by jtnicholl** [comment]
There's already a GDScript warning for using deprecated keywords (I think currently it only warns for the `slave` keyword). If this is implemented it would be good to expand that to include anything deprecated, and probably add a warning for experimental features too.
Also, allowing GDScript code to be flagged as deprecated or experimental using annotations might be useful for plugin authors.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/64982.
