### ISSUE TITLE
Automatically cast 4.0 tween's `final value` to the property type

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#5283]
### Describe the project you are working on

playing with 4.0

### Describe the problem or limitation you are having in your project

```gdscript
var rotation_speed := 0.0

[...]

create_tween().tween_property(self, "rotation_speed", 0, 1.0) \
    .set_trans(Tween.TRANS_SINE)
```
The above snippet fails. Why? Because `0` is an int and `rotation_speed` is a float.
Having to think of writing `0.0` instead of `0` each time I want to tween something to 0 is very cumbersome.

Moreover it can be hard to track where the error comes from when it occurs.
In the code above, execution is stopped not on `tween_property`'s failure but when trying to call `set_trans` on the returned value. The error you're shown when the editor grabs the focus is:
![image](https://user-images.githubusercontent.com/71937306/187085793-848f57e2-0ca0-4b79-89ec-52c1704bd40f.png)

While the actual problem is hidden in the error log:
![image](https://user-images.githubusercontent.com/71937306/187085799-c9f48f0e-3c5f-46c1-b3c3-c794dd438566.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Perform an automatic cast on the provided value and only complain if no conversion is possible (still in the error log).
Or ignore the error check if types are int and float, I don't know the internals.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# works
var asd := 0.0

[...]

create_tween().tween_property(self, "asd", 0, 1.0) \ 
    .set_trans(Tween.TRANS_SINE)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's an annoying edge case of a feature here already.

### Is there a reason why this should be core and not an add-on in the asset library?

/

**Comment by Mickeon** [comment]
As an extra small oddity:
https://github.com/godotengine/godot/blob/cb62d319387c74b517897a06b30410916085753a/scene/animation/tween.cpp#L78-L81

This means that in a release build, this would not fail here, and simply go through. It would still fail during interpolation, however.

**Comment by KoBeWi** [comment]
The float/int incompatibility is an unintended consequence of type checking, I opened an issue about it once: https://github.com/godotengine/godot/issues/53879
I think only conversion between these two types should be allowed.
