### ISSUE TITLE
HIGH delta at 30 second mark.

### ISSUE THREAD

**Issue by KungTwo** [godotengine/godot-proposals#529]
At the 30 seconds exactly there is a HUGE spike on the delta. it goes from being roughly from ~0.0069 to 0.08333 1/144 to 1/12 exactly at the 30 second mark, happens almost every time right at 30 seconds, the delta goes from 144FPS to just 12, even if you have a mostly empty project!
Also Engine.get_frame_rate() has a discrepancy with 1/delta and does not pick up on this colossal drop on the delta at the 30 second mark.

I'm running a Intel core i5 9th gen 9300H and a 1660Ti mobile laptop on a mostly empty game project.

**Comment by KungTwo** [comment]
This is the code for the text in the project
extends RichTextLabel

> var current_FPS = 0
> var lowest_FPS = 999
> var timer = 0
> 
> 
> 
> func _process(delta):
> 	if(timer < 3):
> 		timer += delta
> 	else:
> 		#I have to write this delta can't be zero code or else I get an error divide by zero after 20 
>             #seconds HOW can delta be 0?
> 		if(delta!=0):			
> 			current_FPS = 1/delta
> 			if(current_FPS<lowest_FPS):
> 				lowest_FPS = (current_FPS)
> 				self.text = "Lowest FPS: " + str(lowest_FPS)
>

**Comment by Zireael07** [comment]
Sounds like a bug, and not a proposal - head to the main Godot repo.
Also, the templates are for a reason ;)

**Comment by groud** [comment]
Indeed, this is not the right place to discuss this. Please open an issue in the godot repository, filling the template.
