### ISSUE TITLE
Allow specifying environment variables for spawned processes

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot-proposals#5293]
### Describe the project you are working on

Godot Editor

### Describe the problem or limitation you are having in your project

I want to add an Editor Setting for the Blender importer which allows specifying environment variables for the [user preferences / addons](https://docs.blender.org/manual/en/latest/advanced/command_line/arguments.html#environment-variables) directory.

But both `OS.execute` and `OS.create_process` do not allow for specifying environment variables.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow specifying the environment variables of a spawned process using a dictionary parameter.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a new `HashMap<String, String> p_environment` parameter to both process spawn functions, so that the environment variables can be set easily. This gets exposed in GDScript as a `Dictionary`.

Alternatively, we could think about a builder pattern for process creation (like [PhysicsShapeQueryParameters](https://docs.godotengine.org/en/stable/classes/class_physicsshapequeryparameters.html)), since there are a lot of other parameters that could be added in the future (such as working directory) as well as better error handling for OS-specific flags like `open_console`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would need multiple workarounds, one for each supporting platform. They would also not be as portable as modifying the native API calls directly.

### Is there a reason why this should be core and not an add-on in the asset library?

OS is a core class, and this feature would be used for another core feature.

**Comment by KoBeWi** [comment]
You can set environment variables with `OS.set_environment()` and any spawned child process will inherit them.

**Comment by RedMser** [comment]
Indeed, environment is inherited for the spawned Blender process. I suppose we can avoid polluting the parameter list further then :D
