### ISSUE TITLE
Add support for instance child scene grouping

### ISSUE THREAD

**Issue by DissonantVoid** [godotengine/godot-proposals#5298]
### Describe the project you are working on

A medium scale game with many custom scenes meant to be instanced and placed in the many in game levels

### Describe the problem or limitation you are having in your project

When the instance scene button is pressed
![1](https://user-images.githubusercontent.com/69814029/187674865-123fdd00-5acc-4cbc-85e0-b2014e2fb264.PNG)
it would be helpful if we could group scenes together under group names for ease of use when we have many custom scenes.
![2](https://user-images.githubusercontent.com/69814029/187674998-1e518b49-fbbf-4544-8a25-94644482c055.PNG)
I have a lot of objects I can instance in a level, but it gets counterproductive when I have to manually scroll through them to find what I'm looking for or have to remember their exact names in order to search in the search bar.
another problem is that sometimes I would like to spawn say an Item into the level but I'm not sure which one to pick, so I have to open the Items folder in the FileSystem and see what my choices are, and even then it is not uncommon for different items to be in separate subforlders

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

So the new feature would allow users to add group names in the "Instance Child Scene" menu, and assign scenes to groups
(maybe more than one group per scene, I'm not sure)
And when trying to instance a custom scene we could pick the pre-assigned group where similar nodes are and find the scene we're looking for, this way the instancing menu is less cluttered and more productive

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not sure.. but maybe something similar to how Files can be added to "Favorite" in the FileSystem or how nodes can be added to "Favorite" in the "Create New Node" menu, but instead of having a Favorite option we can have custom names that can be added and removed by the user

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes of course, there are addons that allow you to use instancing, and with nice GUI too, some of them more advanced than others.
But what I'm proposing is merely a simplified version or a quality of life improvement that comes out of the box

### Is there a reason why this should be core and not an add-on in the asset library?

Because of its simplicity, and since the problem it would solve is not uncommon in med/big projects it would be beneficial to a large number of users

**Comment by Calinou** [comment]
> So the new feature would allow users to add group names in the "Instance Child Scene" menu, and assign scenes to groups
(maybe more than one group per scene, I'm not sure)

Shouldn't we use a tree structure to represent the list of instantiable scenes based on folder names instead?

**Comment by Zireael07** [comment]
Sounds like a use case for improved scene tree filtering #4986

**Comment by xX-Void-Xx** [comment]
I'm not sure if adding a tree structure would do the trick here, I mean it could add more complexity depending on how users structure their files or force them to follow a specific file structure for this to work
for example if someone had a folder that looks like this:

res://
--Characters
----character1
------scene, scripts, resources etc

----character2
------scene, scripts, resources etc

----character3
------scene, scripts, resources etc

and so on, the tree structure would look quite ugly

**Comment by DissonantVoid** [comment]
Closing in favor of #4986 which does it better.
