### ISSUE TITLE
vector3.inverse()

### ISSUE THREAD

**Issue by godotludos** [godotengine/godot-proposals#530]
**Describe the project you are working on:**
A project that makes use of vectors for custom physics.

**Describe the problem or limitation you are having in your project:**
Have to use my custom inverse function for vector3 cause the default one does not work has expected.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I might be not geting what godot means by "inverse" of a vector, but to me an inverse of a vector is a vector with same magnitude that lays on the same line but has opposite direction.
example Vector3(2, 1, 0.5):
    the inverse would be Vector3(-2, -1, -0.5)
    but godot inverse() function returns Vector3(0.5, 1, 2)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
We would simply change core\math\vector3.h
from:
```
Vector3 Vector3::inverse() const {

	return Vector3(1.0 / x, 1.0 / y, 1.0 / z);
}
```
to:
```
Vector3 Vector3::inverse() const {

	return Vector3(x + -(x*2.0), y + -(y*2.0), z + -(z*2.0));
}
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It is literely a change in one line of code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is already core.

**Comment by Zylann** [comment]
> example Vector3(2, 1, 0.5):
the inverse would be Vector3(-2, -1, -0.5)

Use `-`

```gdscript
print(vec)
print(-vec) # your inverse
```

**Comment by godotludos** [comment]
I see. so an inverse is prety much a reflected vector when what i want is an opposite.
Your solution is also simpler, don't know why i overcomplicated this.
thanks for clarifing this for me.
