### ISSUE TITLE
Add a Cursor Node

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-proposals#5300]
### Describe the project you are working on

Launcher for games made by my students.

### Describe the problem or limitation you are having in your project

I was trying out the new Movie Writer mode in Godot 4 and realized that my cursor was not visible in the capture.
That made me realize that in UI heavy game, I would have to have the cursor be sprite in the game.
Which made me realize, there is much more problems that having dedicated Cursor Node would solve.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Node that would I will describe few scenario where cursor being Node would be extremely useful.

1) Being able to set the sprites for each of GUI events, hovering over Button for example or clicking.
2) Making custom logic for drag and drop. Now it would be transparent where the dragged data is being held.
3) Now the node would show up in the movie while using the Movie Writer.
4) Having multiple cursors on the screen, be it multiplayer or touch screen controls.
5) It would also help with making game that doesn't have Cursor input by being capable of overriding the default logic.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Cursor Node would always have the position of a mouse and rendered on top of everything.
When present in the Scene, Control nodes would accept input from this node so additional logic could be written.
The node would have texture inputs for the Cursor Shapes and several desired Signals.
Cursor shapes and MouseMode could be moved to this node and Control nodes could have Signals making use of this node.

Main usage would be to have it as a Singleton.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The Node can be sort of done with any node extending Node2D.
However it will miss the discoverability (the drag and drop feature of Godot is still relatively obscure or tight integration with the Control system as proposed).

### Is there a reason why this should be core and not an add-on in the asset library?

Cursor in Godot is kind of hardcoded as is, this would make it's customization significantly easier and more transparent.
Furthermore, I think these changes affect the core too much to be addon.

**Comment by Calinou** [comment]
> The Node can be sort of done with any node extending Node2D.

This doesn't seem like a very common use case for me, so implementing this with a sprite that follows the mouse cursor sounds fine.

**Comment by SilencedPerson** [comment]
Do you think the rest of the proposal is valid or is it waste of time?

**Comment by Calinou** [comment]
> Do you think the rest of the proposal is valid or is it waste of time?

I don't think the rest of the proposal makes much sense to implement.

**Comment by Shadowblitz16** [comment]
@Calinou I don't think gamepad can interact with ui at all though.
We need a way for the ui to pick up controller input like mouse clicks
