### ISSUE TITLE
Make AnimatedTexture more similar to AnimatedSprite: turn `fps` into `speed_scale`

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#5311]
### Describe the project you are working on

A typical 2D project, testing Godot 4 quite a bunch

### Describe the problem or limitation you are having in your project

While making and developing numerous projects and PRs to test my waters, I've noticed something:
**AnimatedTexture** feels... archaic. Old, like from a lost era. It may have been one of the oldest classes introduced in the engine. It really shows. 
It should be incredibly neat and easily accessible to, say, animating a tile... But, in practice, it's more complicated than it looks. 
Case and point, its documentation has been abandoned, and quite sloppily tries to explain... Something that really shouldn't be _that_ hard:
![image](https://user-images.githubusercontent.com/66727710/188198288-ba2cc03a-fdd3-4081-919c-e5cf239b9704.png)

All of this to say that the higher `fps` is, the faster the animation plays... right?
No, but actually. The `fps` property has somewhat confusing behaviour:
The delay in frames per second is first calculated, and then **added** on top of the current frame's individual delay, in seconds. This used formula renders `fps` completely useless if set to **0**, or essentially unnoticeable if set to a value higher than **60**.

What stands out to me most is, there's no other _animation-related_ **Object** works this way in the engine, at least that I know of!

Overall, this system is massively discouraging, annoyingly headache-inducing and difficult to work with. 
To get exact results, or to speed or slow down the animation, it's easier to change each frame's individual delay and keeping the `fps` to 0.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Replace the `fps` with **`speed_scale`**. 
Rename the individual `delay` of each frame to **`duration`**.

`speed_scale`, by default **1**, affects the entire animation **AND** divides each frame's individual duration. 
`duration`, now by default **1**, is the duration of the singular frame, in seconds. Should this value is 0, the frame is completely skipped to the next one.

Very simply, an **AnimatedTexture** with `speed_scale` set to **2** plays its animation at double the speed. If set to **0.5** it plays at half the speed.

As a bonus, just like **AnimationPlayer**'s `playback_speed`, if `speed_scale` is set to a negative value, the animation plays in **reverse**!

This entire solution makes way more accessible and way easier to work with, both in the editor and in code. For example, imagine occasionally changing the speed of a **TileSet**'s animation in a tense battle, or temporarily cutting a few frames out of the **AnimatedTexture** by merely setting their `duration` to 0.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See this PR hot and ready: https://github.com/godotengine/godot/pull/65188

![Showcase](https://user-images.githubusercontent.com/66727710/187890340-ff97d3c2-b3d3-4135-86c7-ae8613821e65.gif)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Kind of. It'd still be quite the headache for the casual user to set up a custom Script for their **AnimatedTexture** to handle a theoretical `speed_scale`

### Is there a reason why this should be core and not an add-on in the asset library?

**AnimatedTexture** is core.

**Comment by dalexeev** [comment]
* Related: #2214

**Comment by Mickeon** [comment]
Kind of? But I do appreciate it being brought to my attention.

**Comment by dalexeev** [comment]
Yes, the problem is that `AnimatedTexture` delays are absolute, while self-length is relative and depends on fps and number of frames.

> `speed_scale`, by default **1**, affects the entire animation **AND** divides each frame's individual duration.
> `duration`, now by default **1**, is the duration of the singular frame, in seconds.

I agree with this, but it seems to me that the frame duration should not be in seconds, but in "units", the default frame duration is 1. And there should be a property setting the duration of one unit (or how many units changes in a second - `ups`? :smile:). Essentially the same, but without mentioning seconds, just "relative duration".

> Kind of? But I do appreciate it being brought to my attention.

These proposals are related in the sense that `AnimatedTexture` and `AnimatedSprite` should become consistent.
