### ISSUE TITLE
Add ASTC to image and VRAM compression for better quality on mobile platforms

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#5313]
### Describe the project you are working on

Godot Engine, and Social VR 3d game.

### Describe the problem or limitation you are having in your project

As described by @reduz, Godot Engine doesn't understand what ASTC is and this means that visual quality is poor on mobile platforms.

Also ASTC in my experience tends to slowly encode.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Mobile devices uses ASTC, while PC uses BPTC and DXT5. So we need to support both.

ASTC also supports hdr textures.

Basisu is also able to transcode to ASTC.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. Add support for ASTC to Image. Image is designed for blocksizes powers of 2. ASTC has all sorts of blocksizes. 
1. Add 
https://github.com/ARM-software/astc-encoder to image and compression / or transcode UASTC.

2. Pick fastest encoding quality because past experience says astc is slow

3. Investigate https://github.com/Themaister/Granite/blob/master/assets/shaders/decode/astc.comp ASTC compute shader decoder

4. Create a "default, quality" toggle in the texture import.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

ASTC is not trivial in compute time to encode.

### Is there a reason why this should be core and not an add-on in the asset library?

Mobile platforms is part of our supported list.

**Comment by reduz** [comment]
The way I was proposing this to work is to have a "high quality" toggle in the texture import. If on, PC will import BPTC while mobile will use ASTC (high quality).

**Comment by Calinou** [comment]
> The way I was proposing this to work is to have a "high quality" toggle in the texture import. If on, PC will import BPTC while mobile will use ASTC (high quality).

For context, this approach is needed because BPTC/ASTC are notoriously slow to compress compared to S3TC and ETC2 (with libsquish and etcpak respectively).

**Comment by reduz** [comment]
@Calinou M1 supports ASTC, so I guess if you want to use high quality stuff, either you support both or make two separate builds.

**Comment by Calinou** [comment]
Is this implemented by https://github.com/godotengine/godot/pull/72031?

**Comment by fire** [comment]
As far as I know this is complete. I don't have a android device and exporting to ios is a pain.

**Comment by clayjohn** [comment]
Yep, this is implemented by https://github.com/godotengine/godot/pull/72031. I tested on Android and ASTC is working there
