### ISSUE TITLE
Introduce External Method Calls

### ISSUE THREAD

**Issue by manglemix** [godotengine/godot-proposals#5322]
### Describe the project you are working on

I am working on a simple board game with a friend. During development, I've found myself having to repeat the same pattern over and over again for the sake of separation.

### Describe the problem or limitation you are having in your project

I use signals to call methods, but I also need to know the return value of some of these methods. To fix this, I emit a signal with an object being passed. The receiving method can no longer be the true method, it must be a wrapper method that accepts this object, and calls the actual method and sets a field in the object to the return value of the actual method.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This could be solved by having a new type of signal connection that I call an External Method Call (not to be confused with Remote Procedure Call). It is a type of signal that can only be connected to one other node's method, and will return the output of that method when emitted. Preferably, this new signal can be defined strongly, so that it can only connect to methods with the same parameters and return value as the signal expects.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not too familiar with how Godot works under the hood. This could be implemented using the existing signal implementation under the hood, and doing all this return value storage behind the scenes.\

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This could theoretically be done with an editor plugin, but the signal inspector has to be reworked to display these special signals because they can only be connected to one target, unlike regular signals.

### Is there a reason why this should be core and not an add-on in the asset library?

I feel like this can be a very common and useful pattern, so implementing it in the core will encourage people to write better segmented code in the long run

**Comment by kleonc** [comment]
Sounds like misusing signals to me. I'd suggest using `Callable`/`FuncRef` (in `4.x`/`3.x`) instead.

**Comment by YuriSizov** [comment]
I agree with kleonc. Can you provide code samples at least to demonstrate what the limitation is and how your suggestion would improve it?
