### ISSUE TITLE
Adjust the window title bar on macOS to make it consistent with platform standards

### ISSUE THREAD

**Issue by samdze** [godotengine/godot-proposals#5327]
### Describe the project you are working on

Not relevant.

### Describe the problem or limitation you are having in your project

The 4.0 implementation in macOS allows the user to choose to use a transparent window title bar.

That's great, but the issue with it is that the spacing of window buttons and the toolbar at the top of the window don't match macOS standards. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Here's an example of the proposed setup (top), vs. the current one (bottom).
![Godot title bar mockup misured-3](https://user-images.githubusercontent.com/19392104/188316763-dd0b5bc7-c172-43ee-b9ea-e5c8c6c24f62.png)

Main highlights:
1. Even spacing (top, left, bottom) around the red close button. 
2. Godot toolbar buttons vertically aligned with the native window buttons.

The proposed title bar style matches the one used in apps like Calendar (NSWindowToolbarStyleUnifiedCompact):
![Fbu_hljWQAAQEYQ](https://user-images.githubusercontent.com/19392104/188316375-4298a64e-d496-4dc4-b279-877dabdd014e.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The title bar style has to be changed in the macOS platform code, a higher one is needed.
The Calendar app has a medium-height title bar.
Apart from that, slight spacing changes could be needed in the Godot top bar too.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Cannot be done with an add-on.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
Implemented by https://github.com/godotengine/godot/pull/66152
