### ISSUE TITLE
CanvasLayer is NOT affected by Camera2D... give me the option to make it possible!

### ISSUE THREAD

**Issue by ALBATI-2005** [godotengine/godot-proposals#5329]
### Describe the project you are working on

A 2D game with many in-game items set as children of several CanvasLayers of different layer values.

### Describe the problem or limitation you are having in your project

I found using CanvasLayers to be much more organized than simply assigning different z_index values everywhere. However, when implementing Camera2D into my project, every node as a child of a CanvasLayer of any layer value will remain "frozen" in the middle of the screen despite moving my Camera2D node. Now, I know I can use this to my advantage in some cases (e.g. pause_menu), but in my case where in-game objects are placed as children of CanvasLayers, this "feature" becomes a limitation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make a property specific to CanvasLayer class, named e.g."Follow Camera2D", where if this is checked off the CanvasLayer acts as usual, but if checked on the CanvasLayer acts more like a group of nodes all assigned a specific index value. Something like that will allow the game-building process to be both more flexible and more organized.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As explained above, make a property specific to CanvasLayer class, named e.g."Follow Camera2D". I'm not totally sure, but implementing this could be very simple. I mean, normally added nodes are essentially part of a CanvasLayer, so why not make it possible for other CanvasLayers to follow the camera as well?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The workaround is not easy, especially in a case like mine. Imagine building a game from scratch, with a mindset of having several CanvasLayers with in-game objects as their children. Then, later in development, I decided to use Camera2D node. But, surprise surprise, it doesn't work as expected, and everything is stuck on the same screen except for a few objects, messing everything up.

### Is there a reason why this should be core and not an add-on in the asset library?

I mean, even besides the fact that I will have to change the whole structure of my scene, just discovering what was actually going on wasted lots of time and made me some headaches. All this could turn off some newbies who have no way of knowing this (such a "limitation" of CanvasLayers is not well explained in the official documents). And, all could be avoided by a simple feature :)

**Comment by Mickeon** [comment]
![image](https://user-images.githubusercontent.com/66727710/188319265-d4d0a581-6642-4786-8375-89bf32a6bc47.png) 

:)

Your confusion hints that this part of the documentation, and the tutorials, may not be clear enough on it.

**Comment by Mickeon** [comment]
![image](https://user-images.githubusercontent.com/66727710/188319265-d4d0a581-6642-4786-8375-89bf32a6bc47.png) 

:)

Your confusion hints that this part of the documentation, and the tutorials, may not be clear enough on it.

**Comment by ALBATI-2005** [comment]
Wow, I mean I read this, but didn't understand what "stimulate a pseudo 3D effect." I will try it and report back (soon) if it has the same effect as what I want.

**Comment by ALBATI-2005** [comment]
PERFECT!!!

**Comment by KoBeWi** [comment]
Yeah the description is bad. I use this option, but never for the pseudo-3D thing.
