### ISSUE TITLE
Rename `range_lerp` to `lerp_range`

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#5335]
### Describe the project you are working on

having fun with 4.0

### Describe the problem or limitation you are having in your project

`range_lerp` is alone in the docs next to totally unrelated methods :disappointed: 

![image](https://user-images.githubusercontent.com/71937306/188334066-51be3689-e50c-4225-860a-6f49d8de7972.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename `range_lerp` to `lerp_range` for consistency and bring it back next to its friends:

![image](https://user-images.githubusercontent.com/71937306/188334051-4425883d-eb74-46ab-96f0-f819c8e1b832.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

its about renaming a function

### Is there a reason why this should be core and not an add-on in the asset library?

its about something core already

**Comment by paddy-exe** [comment]
Related shader proposal: https://github.com/godotengine/godot-proposals/issues/5112

I also implemented the same code as a Remap node for Visual shaders:

**Comment by JoNax97** [comment]
I'd argue that remap is a better name and more widely understood.

But if the consensus is that lerp is a better name, I agreed with turning the name around.

**Comment by paddy-exe** [comment]
> I'd argue that remap is a better name and more widely understood.
> 
> 
> 
> But if the consensus is that lerp is a better name, I agreed with turning the name around. 

I do agree with the Remap node. But most importantly, imo it should be consistent naming for both shading language (if that proposal will be implemented), visual shader nodes and GDScript

**Comment by Mickeon** [comment]
Oooo this is a tight decision before the beta comes out. 

I honestly favour "`remap()`" as well. It's just more intuitive, but it would then miss the "_lerp_" that implies this is indeed an interpolation. 
But `lerp_range()` would be more consistent with methods like `randf_range()`, although they're not related at all...

**Comment by Mickeon** [comment]
But then there's another issue. What about `inverse_lerp()`? Going by this proposal, that function should be renamed, too.

**Comment by dukemagus** [comment]
> But then there's another issue. What about `inverse_lerp()`? Going by this proposal, that function should be renamed, too. And personally, `inverse_lerp` sounds more... natural.

More natural, but less consistent. 

lerp_inverse implies <inverse> function from the <lerp> family

i have no idea how to add remap to it without botching the meaning, though (lerp_remap is wrong and lerp_remap_range is redundant)

**Comment by RPicster** [comment]
I favor `remap()` as it feels more descriptive. But there are a bunch of things to consider.
Your point about the documentation is correct, but then again... `lerp_inverse()` feels a bit weird.

**Comment by aaronfranke** [comment]
To me, `remap` seems like a better name because this method doesn't have much to do with lerping. With lerping you are interpolating between two values by a weight. However, this method doesn't accept a weight, it accepts a value on a starting range which is then remapped to a secondary range.

**Comment by Mickeon** [comment]
I think there's been enough saying on this to believe that `remap` is the better name, if a rename is necessary in the first place. I will update my PR accordingly.

**Comment by TheDuriel** [comment]
Fairly sure I suggested `map_range` many years ago.

remap is fine. Has my vote.
