### ISSUE TITLE
The index.y and index.x do not work in Visual Script in 3.2 . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#534]
**Describe the project you are working on:**
A Tomb Raider game, also an RTS, like StarCraft, same characters, same universe . .

**Describe the problem or limitation you are having in your project:**

In 3.1, when I changed to ' index ' for a visual script get_rotation or get_translation it changed the ' box ' output from a vc3 to a float, but now it just says it's a vc3, and now I need an extra box, to deconstruct it, the SET_rotation and SET_translation boxes still work, like in 3.1, just change the index ( in inspector ) and it changes type from vc3, to a float ( for y-value, z-value ) . .

Picture . .
![2020-02-28 1543](https://user-images.githubusercontent.com/61069740/75557860-1df21580-5a41-11ea-94a1-28d3461845e6.jpg)

A short video, showing it . .
1 minute : https://www.youtube.com/watch?v=LwRf3WVFX5U

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Well, it was really easy for me to get the values I wanted in 3.1, I wish it was that way again, for a beginner . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I don't know, can't code . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't think so, don't know . .

**Is there a reason why this should be core and not an add-on in the asset library?:**

It was in Godot 3.1, and worked better :)

**Comment by Jummit** [comment]
This is a bug and should be reported here: https://github.com/godotengine/godot/issues

**Comment by groud** [comment]
Indeed, this is a bug. Please report it on the [main repository](https://github.com/godotengine/godot/issues)
