### ISSUE TITLE
Improve Script Editor's Gutters

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#5369]
### Describe the project you are working on

2D Platformer written in GDScript (Godot 4)

### Describe the problem or limitation you are having in your project

Horizontal space on my device is limited, so I wanted to make my script editor as compact as I reasonably could without reducing code readability or functionality. Gutters were an obvious avenue, but then I was reminded of how messy they are and felt inclined to open a proposal to suggest some improvements.

If you don't know what gutters are, it's this space behind the code:

![image](https://user-images.githubusercontent.com/85438892/188997342-653c0709-bd03-48c4-b13c-16bbc60322cf.png)

The gutters for code folding and for showing numbers, as well as their related editor settings are all well and dandy in my opinion, so I'll not mention them.

**Status quo:**

- Info Gutter: Displays a slot icon next to method declarations if signals are connected to said function. Clicking this icon opens a menu that shows a list of connections.
- "Show Info Gutter" editor setting that can hide this gutter, completely obscuring the information it provides.
- Main Gutter: Displays breakpoints, execution lines, and bookmarks. Clicking on it toggles breakpoints.
- "Show Bookmark Gutter" editor setting that can hide bookmarks, but has no effect on the gutter itself. Seems like a broken/outdated setting.
- Editor settings in the highlighter for changing the color of each icon used in the Main Gutter

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The jank was too much to separate proposals (there's also bugs and minor usability issues but I'll not talk about that), so I decided to combine my ideas for a rework here.

*I've made major edits after discussion with Paulb*

**Proposal 1**

Add Shift+LMB as an alternative way to toggle bookmarks, similar to breakpoints (somewhat related to https://github.com/godotengine/godot/issues/53685).

This would make bookmarks more discoverable and nicer to use for many users.

**Proposal 2**

Rename the "Show Bookmark Gutter" editor setting to "Show Main Gutter". This would save horizontal space and use a highly translucent version of the Bookmark color the user has chosen.

The default at 20% translucency would look like this:

![image](https://user-images.githubusercontent.com/85438892/189004035-b97d637d-e547-4458-8741-7142491d8cb4.png)

And breakpoints and execution lines would look like this:

![image](https://user-images.githubusercontent.com/85438892/189005833-25685699-37e9-4d48-99b0-c72bbae059e3.png)

*Paulb was not convinced about bringing back the pre-4.0 functionality. An alternative thing would be to avoid confusion by renaming "Show Bookmark Gutter" to "Show Bookmarks in Gutter", or shifting bookmarks and breakpoints around when displayed at once to avoid clutter, rendering the setting pointless.*

**Proposal 3**

Add an extra functionality to the Info Gutter – for functions that are overriding a function in a super class. Show an icon of the class that is being overridden.

This would rarely clash with the Connections icon, but if it does, don't show both – prioritize the Connections one.

Mock-up using an 80% opacity class icon.

![image](https://user-images.githubusercontent.com/85438892/189007924-056c6765-a577-4a1c-8234-35648c6722a9.png)

Rework the dialog that shows up when you click on the Connections icon, or the new Function Override icon. Rename it from "Connections to method:" to "Method Information". In a small panel at the top, show which function it overrides in which class, then in a big panel show the signal connections like before.

**Proposal 4**

Add the icons from the info gutter to the methods list. Probably appended at the end, after the text, and clickable too. Just an alternative, since the info gutter and methods list are all about function declarations. I'm mentioning it here as it has the benefit of keeping the information available somewhere when the info gutter is hidden.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Proposal 3 would probably act on parse time, like with signal connections and type safety. I assume it would involve iteratively looking if the base class contains the method and displaying its icon if a match is found.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often. It can't be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about enhancing existing features.

**Comment by AttackButton** [comment]
Nice. As a user, I can say the function override icon will help a lot. With that, would it be possible to rename the engine's default virtual functions, removing the "_" character? Something like:

`_unhandled_input` -> `unhandled_input`,
`_ready` -> `ready`, 
`_process `-> `process`, 
etc.

That way, it would be easier for the users to use the convention with that character to name functions as private without confusing them with the virtual function convention from the engine.

**Comment by MewPurPur** [comment]
@AttackButton No - functions have underscores when they are not called in code. You don't need to call _ready() or _process(), they just happen. But you do need to call somethong like `queue_free()` hence, no starting underscore.

**Comment by AttackButton** [comment]
Thanks. This makes sense.
