### ISSUE TITLE
use relative paths instead of absolute paths

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#5371]
### Describe the project you are working on

I am working on open source project :
https://github.com/ywmaa/Advanced-Movement-System-Godot

### Describe the problem or limitation you are having in your project

I wanted to include it in another personal project in another repo, so I used git submodule, but then the project would not work because when I open it, it has incorrect paths, because it looks for the files by the project root "res://" instead of making it a relative path

so when it is a submodule it will be in an extra folder I will call it "example"
now all of the files will be in "res://example/" instead of "res://"
so now all of the refrences to the files are incorrect which makes all of the project files corrupted.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think if there is an option, or godot by default stores paths as relative paths like "../refrencedfile.gd"
instead of project root "res://refrencedfile.gd" will solve the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no I can't even find a way to workaround this.

### Is there a reason why this should be core and not an add-on in the asset library?

it solves project paths structure and I think it will help in a lot of other stuff not only this problem.

**Comment by hilfazer** [comment]
A duplicate of #2327?

**Comment by ywmaa** [comment]
Yeah, he says what I want, I couldn't find it, so closing this issue.
