### ISSUE TITLE
Ability to jump to drop down menu options by typing the first letters

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#539]
**Describe the problem or limitation you are having:**

Navigating large drop down menus with the keyboard is quite tedious.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

In many applications you can start typing in the drop down menu and it will jump to the option that matches the typed text.
This feature is implemented in Godot's menus, but sadly never used in engine.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Set `allow_search` when creating PopupMenus in the editor.

It could also be enabled by default here:
https://github.com/godotengine/godot/blob/e539b187a5add6951b25b07c9c22826cc8be6b1a/scene/gui/popup_menu.cpp#L1539

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It is core functionality.

**Comment by simpuid** [comment]
Does providing an editor setting to turn this feature on/off an overkill?

**Comment by Jummit** [comment]
Probably. This is standard UI behavior.

**Comment by Calinou** [comment]
Indeed, this should be enabled by default as I don't see any downsides to it.

**Comment by Calinou** [comment]
This was done in https://github.com/godotengine/godot/pull/38811, closing.
