### ISSUE TITLE
Add shader include relative path support

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#5399]
### Describe the project you are working on

3D game.

### Describe the problem or limitation you are having in your project

Often I like put my project to deferent directories and move, so for most shader files for include, it's absolute path was changed but relative path not. 
eg:
Tree look:
![image](https://user-images.githubusercontent.com/35988767/189505776-803e01b2-def5-4915-b8e1-07687ad15b80.png)
And `comm.gdshaderinc` was incluced by `node_3d.shader`:
![image](https://user-images.githubusercontent.com/35988767/189505795-820b583b-3eb8-4451-9cc9-b0d71d47d5c2.png)
![image](https://user-images.githubusercontent.com/35988767/189505809-e61baefc-8fa6-404e-9e67-227d1b994ca1.png)

If I change my `shaders` folder to `xd/shaders`, I must change the `node_3d.gdshader` file because the `comm.gdshaderinc` file's absolute path was changed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For shader `include` preprocessor, support absolute and relative path.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I must change many files, if my project was big, i'm afraid to do that.

### Is there a reason why this should be core and not an add-on in the asset library?

/

**Comment by Calinou** [comment]
This would only work in shader files that are saved as external resources, not built-in shaders in scenes.

**Comment by autofool** [comment]
> ### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think the greatest enhancement is about re-usability. Lets say we want to write some common shader code that can be used in multiple projects. Plus this code has shaderincs that depend on other shaderincs. In that case having relative is really necessary. Otherwise absolute path will force us to either make consistent dir structure or change include lines in individual files every time files are moved.
