### ISSUE TITLE
Godot mono should qualify Object with Godot namespace when generating glue.

### ISSUE THREAD

**Issue by Atlinx** [godotengine/godot-proposals#5404]
### Describe the project you are working on

I was attempting to build a mono version of [sg-physics-2d](https://gitlab.com/snopek-games/sg-physics-2d).

### Describe the problem or limitation you are having in your project

I was attempting to build a mono version of [sg-physics-2d](https://gitlab.com/snopek-games/sg-physics-2d) when I got an error about the generated `Object` class (which originates from the `Object.base.cs`). Turns out this module had a getter named `get_object`, which ended up getting converted to a property named `Object`, thus causing name collisions and superseding the `Object` from `Object.base.cs`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The glue code should be generated with a namespace for Object. Ex.

```C#
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private static IntPtr method_bind_1 = Godot.Object.godot_icall_Object_ClassDB_get_method(nativeName, "get_shape");
``` 

Or in this, case, it seems like Object is necessary and can be omitted (because the parent class already inherits from Object).
```C#
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private static IntPtr method_bind_1 = godot_icall_Object_ClassDB_get_method(nativeName, "get_shape");
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'll have to leave the how up to @neikeq, because I'm not too familiar with the glue generation. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The current workaround is for module developers to be aware of these pitfalls and avoid naming anything that could conflict.

### Is there a reason why this should be core and not an add-on in the asset library?

Engine development related, therefore, cannot be an add-on.

**Comment by neikeq** [comment]
Is that the only occurrence? If so, the fix here should be easy:

https://github.com/neikeq/godot/blob/5e495750a37e3314a8cd85cb3f7be9a676420c44/modules/mono/editor/bindings_generator.cpp#L1598

That being said, it may be better to make the generator rename the property to something like `Object_`. I already plan to do the same for classes named `System`.

**Comment by raulsntos** [comment]
- Likely fixed by https://github.com/godotengine/godot/pull/69547 which implements the following changes:
	- `Godot.Object` is renamed to `GodotObject`.
	- If there is a class named `System` it will be renamed to `System_`.
