### ISSUE TITLE
Remove the warning "ScrollContainer is intended to work with a single child control."

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#5409]
### Describe the project you are working on

A menu system for my game. One element I need is a scroll container with a list of levels, or a label saying you don't have any levels.

### Describe the problem or limitation you are having in your project

There is an elegant way to design this element, but at the cost of an editor warning

![image](https://user-images.githubusercontent.com/14253836/189661617-9ac0cf38-9abf-4db8-a8e9-db68ac0475fd.png)
![image](https://user-images.githubusercontent.com/14253836/189661662-1f942693-f302-4a79-8b3a-f08b8f1a1a7c.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose removing this warning, and making `ScrollContainer` work with multiple children, similar to a `PanelContainer`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/14253836/189670126-f0547e8c-e389-41e6-bd2b-b99c8f085fb1.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Can be worked around with a proxy container

![image](https://user-images.githubusercontent.com/14253836/189670294-11e66dcc-d28e-4a96-845e-69cfd1cf2a15.png)

### Is there a reason why this should be core and not an add-on in the asset library?

ScrollContainer is core

**Comment by YuriSizov** [comment]
I think it's okay to have this warning. It's not intrusive and it helps people new to the UI system to understand that the contents won't magically arrange itself and you need to use a container if you want to display a series of controls. Your use case assumes you already understand that, so the warning is not important to you.
