### ISSUE TITLE
Currently, in Tree, it seems that `item_mouse_selected` is not working with right click. Then, How to handle this event?

### ISSUE THREAD

**Issue by Fran6nd** [godotengine/godot-proposals#5423]
### Describe the project you are working on

I am working on a game which is a robot simulator. The user can code in Lua and then see the robot moving, interacting accordingly. I do not use any external editor. All in-game. And to manage files (user written Lua scripts), I am using a `Tree` node with `TreeItems` as files or folders.

### Describe the problem or limitation you are having in your project

I would like to open a popup on right-click to ask for example to delete the file. 
I figured out I should use the signal `item_mouse_selected` which provide a `mouse_button_index `.
However, this signal is only triggered on left click. So why having `mouse_button_index ` if not to handle both mouse buttons?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would allow managing right-click and triggering various actions.
Maybe the signal is not triggered as only the left click seems to select the `TreeItem`. We should be able to change this? Like having a param to allow or not right-click selection.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

-

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not at all as far as I know.

### Is there a reason why this should be core and not an add-on in the asset library?

Because it's touching a core component.

**Comment by Zireael07** [comment]
Offtop: does that mean the Lua bindings work with Godot 4?

**Comment by YuriSizov** [comment]
`item_mouse_selected` is a signal that fires when the item is _selected_. You can select items with the left mouse button by default, and with the right mouse button if you enable "Allow RMB Select" for the tree.

**Comment by Fran6nd** [comment]
> Offtop: does that mean the Lua bindings work with Godot 4?

I am using this one for in game scripting:
https://github.com/Trey2k/lua
