### ISSUE TITLE
Rename AudioStreamPlayer3D's `unit_db` to `volume_db`

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot-proposals#5426]
### Describe the project you are working on

A card game with 3d visuals

### Describe the problem or limitation you are having in your project

I wanted to transfer my sfx managing code from 2d to 3d, and surprisingly, `volume_db` isn't a thing. I then found out that `unit_db` does the thing but I was left without explanation why it's named like that. Is it volume which the sound plays at one unit distance? Or what "unit" is referring to? I guess it is somehow more explicit or related what it technically does, but why wouldn't volume be called just that, volume. It feels inconsistent with AudioStreamPlayer and AudioStreamPlayer2D.

However, if there is some fundamental reason it should be `unit_db`, docs should have explanation what it means. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename `unit_db` to `volume_db`. It's easy to remember and consistent. If you're instancing players from code, volume is the first thing you search for to make sound louder or softer.

Alternative (for both 3d and 2d variants): `base_volume_db`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
		var new_player = AudioStreamPlayer3D.new()
		new_player.volume_db = -3
		add_child(new_player)

```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's about naming consistency and accessibility.

### Is there a reason why this should be core and not an add-on in the asset library?

It's about naming consistency and accessibility.

**Comment by Mickeon** [comment]
Before I do something undesired, is the "_db" of "volume_db" even needed anymore, since the suffix can be seen in the Inspector? One part of me says yes, because the actual unit of measurement may be vague, but the other part of me believes that, in the future, this property should be exposed in linear units for the Inspector for ease of use _(like rotation is exposed in degrees in the editor, but is actually converted into radians internally). Therefore, having it espressed with a percentage, while still being prefixed with "_db" would be pretty odd, to say the least.

**Comment by Mickeon** [comment]
Afterthought:

There's `unit_size`, and its description is as follows:
> The factor for the attenuation effect. Higher values make the sound audible over a larger distance.

If `unit_db` is renamed, so should `unit_size` to be much less vague. Something like, `attenuation_strength`, right off the bat. That may not fully fit the Inspector, but it is what it is.

**Comment by aXu-AP** [comment]
Good point about db. Hard to say. If I was using scripting I'd try setting linear values first as it's more intuitive. However, script editor has shows documentation so I'd say `volume` is ok.

I'd suggest `attenuation_rate`. Distance sounds wrong, as it's more than given value.

**Comment by Mickeon** [comment]
`rate` in the engine is mostly used to mean "the speed at which something happens or changes", which I don't feel like suits this particular case. What other similar words are there?

**Comment by aXu-AP** [comment]
That's true. I guess `attenuation_factor` is good and descriptive.

**Comment by aXu-AP** [comment]
Oops, a big mistake. These names are good and all, but the meaning is inverted. Bigger `unit_size` means slower rate of attenuation when distance grows. In that case, `attenuation_distance` is the best variant. But it doesn't feel right. Easy to mix with `max_distance`. 
Anyway, having word attenuation in that property name is good (maybe even consider grouping them).

Of course, one possibility is to change the functionality to match name. Ie change division to multiplication where is `unit_size`:
https://github.com/godotengine/godot/blob/5fb84e5702d7fbfc011c05304500c0b61ef2ef92/scene/3d/audio_stream_player_3d.cpp#L214-L225
But this is a last resort thing 😄

**Comment by aXu-AP** [comment]
If it's not too much of a mouthful, `attenuation_distance_factor` should be accurate.
