### ISSUE TITLE
Prevent changing node order when reparenting nodes

### ISSUE THREAD

**Issue by mathias17** [godotengine/godot-proposals#5427]
### Describe the project you are working on

Just another 2D game.
(This issue post isn't specific to any of my current Godot projects.)

### Describe the problem or limitation you are having in your project

(similar issue post: https://github.com/godotengine/godot-proposals/issues/1652)

This issue post pertains to fundamental scene tree ui behavior in the editor - basically a ux complaint I have.

When reparenting one or more nodes, the newly reparented node(s) are sent to the bottom of their siblings in the hierarchy.
This can be inconvenient because then manually re-ordering the newly parented nodes is almost always necessary.

Can efforts be made to try to leave the newly reparented nodes as close as possible to their pre-reparented place in the hierarchy?

In cases where a random selection of nodes from all over the scene tree are reparented, I can understand the newly reparented nodes needing to be moved to an arbitrary place in the hierarchy, but this happens even when only one node is being reparented.

_Screen recording of two adjacent sibling nodes being reparented:_
https://www.youtube.com/watch?v=7ZhjoytNk2c

^ Here I'm selecting two adjacent siblings and reparenting them. They're sent to the bottom of their siblings level instead of staying place.
After reparenting, I use Undo and Redo to show that reparenting is actually doing two operations - it creates the new parent node at the bottom of the current hierarchy level then the selected nodes are nested as children.
Notice how the water caustics animations need to be moved back to their intended place so the draw order is correct.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Normally, I avoid the Reparent feature because of this. Instead, I'll add the new parent node manually, move it into place, then nest whichever nodes under it I need to.

If Reparent could be a little more intuitive and not arbitrarily add the new parent node at the bottom of the current node level it could save on time and frustration.

Can the editor recognize the lowest selected node when reparenting and spawn the new parent at that lowest node's place in the scene tree? Instead of all the way to the bottom of the current tree level.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

No. I'm trying to suggest a basic quality-of-life improvement for a specific scene tree behavior in the editor.

**Comment by YuriSizov** [comment]
> Can the editor recognize the lowest selected node when reparenting and spawn the new parent at that lowest node's place in the scene tree? Instead of all the way to the bottom of the current tree level.

I'd expect it to add the new node at the topmost node's position, not the lowest's. 🙃

**Comment by mathias17** [comment]
> I'd expect it to add the new node at the topmost node's position, not the lowest's. 🙃

Hey there.
It seems like the more preferable behavior would be for the new parent node to spawn lower on the tree, not higher. The higher up a node is the more likely it is to be buried in the draw order and not be initially visible.

In my own experience I tend to prefer newly added stuff being visible right away so I can more easily interact with it, and not need to search for it in the scene tree before making my next move.

**Comment by YuriSizov** [comment]
That only makes sense for 2D nodes, and reparenting is a general usability tool. It's basically like grouping from the UX standpoint, which is why I'd expect the group node be placed at the topmost node's position.

**Comment by mathias17** [comment]
That's true. Scene tree management is different for 3D scenes - the order of nodes is way less important.
This issue has stronger implications for 2D scenes, but the end result of reparenting nodes being more predictable would improve 3D scenes as well.

Although, if reparenting is to change at all then the largest problem is probably that reparenting is more like an editor macro than an actual function. Reference KoBeWi's post here: https://github.com/godotengine/godot/pull/42730#pullrequestreview-507285911

**Comment by KoBeWi** [comment]
I never used this option, but I think it makes sense to make it keep the node position.

**Comment by Zireael07** [comment]
I was kinda thinking that we could keep the current behavior for 3D and change for 2D because of the draw order implications

Alternately drop to last by default and drop to first with Shift or Ctrl or something?

**Comment by mathias17** [comment]
Is it currently possible for SceneTreeDock to behave differently depending on whether current scene is 2D or 3D?

**Comment by YuriSizov** [comment]
Scenes can contain both kinds of nodes, and non-spatial nodes to boot.
