### ISSUE TITLE
Adding gIMP image filters to post-processing node ( real-time 

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#543]
**Describe the project you are working on:**

I'm working on a Tomb Raider game, also an RTS . .

**Describe the problem or limitation you are having in your project:**

I would like to change the ' effect ' of the engine, to look like the gIMP filters, on this list, in post-processing, so I can get various effects . . . The engine might be able to go to a lower resolution ( like from 1080p, to 720p ) during the cut-scenes ( it's mostly for giving the cinematics a unique feel, or appearance ) . . Here's an example, of what I'd like to do to each frame, or perhaps go to 30 fps, or 15 fps in cut-scene, to make it run well . . .

![2020-03-02 0256 compactness](https://user-images.githubusercontent.com/61069740/75639711-70465880-5c32-11ea-81e1-3b7a513dae24.jpg)
![2020-03-02 0251 mosaic filter](https://user-images.githubusercontent.com/61069740/75639712-70465880-5c32-11ea-9df2-89c756cc08c9.jpg)
![2020-03-02 0249 Mosaic](https://user-images.githubusercontent.com/61069740/75639713-70deef00-5c32-11ea-95b6-4b77da6e83e6.jpg)

It would be really nice, for Godot, if one could apply perhaps simpler versions of these classic filters, at run-time, to any frame, or perhaps a camera, for effects, special look, or ' image style ' . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Right now, I want to make the game look like an oil painting, during the cut-scenes, I can just pre-render the scenes, record them with OBS, and apply the filters to each frame, put them back together, but it could be cool if this was a built-in feature, as it would allow ANY game to have a very unique custom look, not just mine, here's a list of some of them, from gIMP ( it's open source, so the code should be available, for free, to use in Godot ) . . .

https://docs.gimp.org/en/filters.html

For instance, Distortion filters . .

5. Distort Filters 
5.1. Introduction 
5.2. Apply Lens 
5.3. Emboss 
5.4. Engrave 
5.5. Lens Distortion 
5.6. Mosaic 
5.7. Polar Coordinates 
5.8. Ripple 
5.9. Shift 
5.10. Spherize 
5.11. Value Propagate 
5.12. Video 
5.13. Waves 
5.14. Whirl and Pinch 
5.15. Wind 
5.16. Curve Bend 
5.17. Emboss (legacy) 
5.18. Newsprint 
5.19. Page Curl

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Well, it should just be another post-processing node, or effect, like where you set the environment, film space, GDQuest had a video where he talked about it, adding camera effects, post-processing effects, to a game, in the EnvironmentNode . . Maybe make a post-processing node, one could add to a camera, or a Environment node, that runs ' live ', even at 60 fps, if one limits the number of polygons in the cut-scenes, but removing background, focusing on characters . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

For a beginner, it would take a long time to implement one feature . . But, if Godot added this feature, everyone would benefit, and every single frame could look like a work of art, live, at 60 fps <3

**Is there a reason why this should be core and not an add-on in the asset library?:**

I think it is too much work for one person, to make all these filters, it would also give Godot game makers tools to create any art-style, at least for cut-scenes, or slowly moving images, like slow panning, where fps can be lower, so cut-scenes, or even entire games, could have amazing effects, visuals . . . Here's another example, from Photoshop, but the ones from gIMP are nicer, and open source, could be made part of Godot, since the code is public . . <3

![2020-03-02 0102 Oil paint f24](https://user-images.githubusercontent.com/61069740/75639950-5f4a1700-5c33-11ea-82fd-58070a0ef3c0.jpg)

**Comment by Jummit** [comment]
> I think it is too much work for one person, to make all these filters...

Making it a core feature doesn't change that.

**Comment by bruvzg** [comment]
> but the ones from gIMP are nicer, and open source, could be made part of Godot, since the code is public . . <3

GIMP is GPLv3+ licensed, which can't be integrated to Godot, it's incompatible with closed platforms like iOS, UWP Windows Store and consoles.

**Comment by jasperbrooks79** [comment]
I meant, for a person with no coding experience, or knowledge of shaders, to code it, for themselves . . Maybe someone at Godot with expertise could do it, anyway it could add a whole new layer of visual effects choices, to the engine . .

I didn't know gIMP was closed, it says it's open source . .

Maybe it's a bad idea, it just seems like one could do a lot with those filters . .

**Comment by alexfreyre** [comment]
I have seen how for example are for image and video there are libraries to apply filters to itand there are a lot of possibilities.

I currently use:
For image I have found "imagemagick" suite with a lot of features/filters for images.
For video  I have found "ffmpeg" with a lot of features/filters for video. This could be a great great feature inside Godot.

For example ffmpeg runs video a lot faster than Godot, with the application ffplay, which apply any effect in real-time to any video, it's insane how fast it work.

I think this could be evaluated in order to expand the possibilities of Godot.

**Comment by bruvzg** [comment]
> I currently use:
For image I have found "imagemagick" suite with a lot of features/filters for images.
For video I have found "ffmpeg" with a lot of features/filters for video. This could be a great great feature inside Godot.

Godot already have gdnative interface for the video decoders, add plugins using FFmpeg - https://github.com/KidRigger/godot-videodecoder, support for the filters could be added to the same interface. But the same licensing issues apply to FFmpeg (LGPL or GPL depending on config) and some of its components might have issues with software patents in some countries.

**Comment by Calinou** [comment]
Closing, as this can't be added in core Godot due to licensing reasons (see the discussion above).

> Maybe make a post-processing node, one could add to a camera, or a Environment node, that runs ' live ', even at 60 fps, if one limits the number of polygons in the cut-scenes, but removing background, focusing on characters . .

You need shaders for this. CPU-based operations will never be fast enough for 60 FPS filters :slightly_smiling_face:
