### ISSUE TITLE
Add support `Object` as argument for `String.format()`

### ISSUE THREAD

**Issue by 4d49** [godotengine/godot-proposals#5434]
### Describe the project you are working on

Game.

### Describe the problem or limitation you are having in your project

For debugging in my project, needs display useful information.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To format an Object into text, needs create temporary Dictionaries.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Implementation: https://github.com/4d49/godot/commit/6f809c77cdef8552928b32d5181ea9f734c58099

### If this enhancement will not be used often, can it be worked around with a few lines of script?

```gdscript
static func format_object(string: String, object: Object, placeholder:= "{_}") -> String:
	for p in object.get_property_list():
		string = string.replace(placeholder.replace("_", p.name), str(object.get(p.name)))
	
	return string
```

### Is there a reason why this should be core and not an add-on in the asset library?

It looks useful and like part of the engine.

**Comment by Calinou** [comment]
Can't you override `_to_string()` in the object instead?

**Comment by 4d49** [comment]
> Can't you override `_to_string()` in the object instead?
In different contexts, different templates can be used to format strings.
