### ISSUE TITLE
Add long-distance directional shadows

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#5464]
### Describe the project you are working on

Large Open World Environment

### Describe the problem or limitation you are having in your project

Raw Shadow mapping is unable to handle Large distances because Resolution starts dropping off a cliff the larger the Shadow Map distance becomes, resulting in pixelization. This has several downsides.
1) You have to increase Shadow Resolution, resulting in lower performance and a massive increase in video memory consumption
2) Shadows are of Lower Quality
3) Lots of triangles processed every single frame due to inefficient culling, even if there is little to no change in the shadow conditions

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The Feature I propose is a combination of Traditional Shadow mapping for close up for better quality (Proposed feature wouldn't have shadow blur, which is fine as it becomes essentially non-existent at a distance without PCSS, which also wouldn't be supported) with a simplified Vectorized Shadowmap

This would allow for Lower Resolution Shadow maps to be used for local Directional Shadows, saving on video memory consumption*, while keeping the Effective Shadow resolution High, and would allow for shadows outside of the Traditional Shadow Map to be stored on the Objects

*This depends on the total number of shadow vertices

Something like UE5's Virtualized Shadow Maps would be a more flexible alternative to this, but those require nanite like tech.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Note: This is probably best to be CPU Baked for static objects and not support dynamic objects due to step 2 as overdraw elimination could be fairly compute intensive and not practical for real time.
1) Project all vertices to the Global XZ Plane with the Light Direction being the direction you're moving the vertices. This will result in 2D Vector, with the 3rd dimension being Distance from the Original Vertex, to act as depth
2) Simplify the Projection, as there is currently likely to be a bit of overdraw on the 2D Plane, so eliminating it is required
3) Determine which pixels are out of the Max Distance and thus not getting Traditional Directional Shadow Mapping
4) Project all resulting pixels the same way as with the Vertices
5) Query the plane for depth information where those pixels land, to see if occlusion happened or not

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Shadows are currently impossible to edit in an addon without rewriting the entire logic.

**Comment by Calinou** [comment]
> 2. Shadows are of Lower Quality

You mentioned an approach with tweaked directional shadow split distances to have high-quality shadows when up close. I'd say this looks good enough if you need long-distance shadows to remain visible, as long-distance shadows don't need to be very sharp.

> 3. Lots of triangles processed every single frame due to inefficient culling, even if there is little to no change in the shadow conditions

Shouldn't we find ways to improve culling and reduce redraws instead?

**Comment by mrjustaguy** [comment]
both VoxelGI and SDFGI would be completely and utterly useless for this, as they don't really work over a few km of view distances, and Directional Shadow Maps can get passably (albeit now with blur changes with visible pixelization) up to about 10km, though with maxed out resolution, and it can in some instances be observed how the resolution is clearly too low even without said changes due to the enormous distances..

With Lightmaps are probably the way to go, however they would likely still be very memory intense, because not only do you have the lightmaps taking up memory, but also the shadow map cannot get it's memory footprint shaved significantly without again running into cases where shadowing issues become apparent, because of transitioning between two possibly fairly different shadow qualities.

**Comment by mrjustaguy** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/discussions/6046 (virtual shadowmaps) or https://github.com/godotengine/godot-proposals/discussions/5162 (RT shadows)
