### ISSUE TITLE
Add a global asset list for easier asset management

### ISSUE THREAD

**Issue by UsernameBillion** [godotengine/godot-proposals#5465]
### Describe the project you are working on

A game, with assets

### Describe the problem or limitation you are having in your project

Locating and instancing a lot of different scenes can be tedious

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

My idea would be to introduce a kind of global asset list dictionary, which the user can add anything to, with a simple name. That way, you dont need to remember file paths or keep searching for things.
The objects in this list would show up in the add node screen too, in the same way that users can already introduce their own classes which show up there.

Sure, the user could implement their own singleton and keep adding to and referencing variables contained in that, but that is an extra step being shifted to the user. It also would never be able to affect the add node screen of godot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You would be able to open an asset list screen. It would be a dictionary; you get to set a custom name for an object and you get to set its filepath. Any kind of asset at all, not just instanceable ones.

In code, you would then be able to just do load(objectname) and it would work. It would also show up in the create new node list if instanceable. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is a quality of life feature, it would be used as often as people want easier ways to keep track of and manage assets. Not a necessity by any means but nice to have.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by Calinou** [comment]
You may be interested in the ResourcePreloader node, which you can add as an autoload if you save it to a scene file.

**Comment by Zireael07** [comment]
What resource preloader? Godot docs doesn't know anything like this...

**Comment by UsernameBillion** [comment]
> You may be interested in the ResourcePreloader node, which you can add as an autoload if you save it to a scene file.

I didn't know that existed, but really that doesn't introduce what I'm suggesting. 

But thinking about it, this is more pointless than I thought. I'd forgot about the quick "instance child scene" button.
