### ISSUE TITLE
Optional Toggle of GDScript Operand Symbols

### ISSUE THREAD

**Issue by froggestspirit** [godotengine/godot-proposals#5482]
### Describe the project you are working on

Any

### Describe the problem or limitation you are having in your project

Code formatting

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In the newer verion of GDScript, some operands will be displayed as symbols when typed in the code editor window. For example, != will look more like =/=. Others include /=, >=, <=

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the Editor Settings > Text Editor > Appearance, add a checkbox to enable/disable this behavior

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think this would make sense as a script if possible

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think it'd be beneficial to get rid of it completely, since it can be nice for some people, though veterans to code may be used to the traditional look, making it easier to tell what's going on at a glance.

**Comment by Calinou** [comment]
This is already supported:

![image](https://user-images.githubusercontent.com/180032/192063250-545e9465-8b5f-47de-a7bc-4e4a24d95257.png)

Closing in favor of https://github.com/godotengine/godot/issues/63865.
