### ISSUE TITLE
Create an emit_deferred on signals for easy access to main thread 

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot-proposals#5485]
### Describe the project you are working on

A game with heavy procedural generation, taking advantage of the new WorkerThreadPool.

### Describe the problem or limitation you are having in your project

There are many times I want to emit a signal, but have the execution of that signal be done on the main thread (as it interacts with the scene tree). Currently, the thread that emits the signal processes the connected functions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose there is a `emit_deferred` function on signals, which mirrors the pairing `call_deferred`/`call` - which would defer the emitting of the signal until next frame, gaining easy access to the main thread - as well as other benefits of using `_deferred` calls. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Using `emit_deferred` would delay the signal until the next idle frame. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes. You can create a function for each signal and use `call_deferred` on that function.

### Is there a reason why this should be core and not an add-on in the asset library?

Signals are an important part of Godot's architecture and with Godot 4, multithreading is becoming an important part as well. This could save a lot of boilerplate when needing to jump back to the main thread.

**Comment by zinnschlag** [comment]
Wouldn't such a signal always be deferred? In this case it should be much safer to set the CONNECT_DEFERRED flag when connecting the signal. Having to remember to use the deferred form on every emit seems rather error prone.

**Comment by cridenour** [comment]
> Wouldn't such a signal always be deferred? In this case it should be much safer to set the CONNECT_DEFERRED flag when connecting the signal. Having to remember to use the deferred form on every emit seems rather error prone.

Yes that is correct. 

When I wrote the proposal I had in my head CONNECT_DEFERRED was globally applied to the signal but of course it's per connection. 

Will close the proposal as that's the correct answer to my issue.
