### ISSUE TITLE
Add PackedVector2iArray and PackedVector3iArray

### ISSUE THREAD

**Issue by alazifk** [godotengine/godot-proposals#5486]
### Describe the project you are working on

I would like to create a GDScript-function in C++ that takes an array of Vector2i.

### Describe the problem or limitation you are having in your project

E.g. `void foo(const Vector<Vector2i>& points);` will throw an error.

In `type_array.h` only  
```
MAKE_TYPED_ARRAY_INFO(Vector<Vector2>, Variant::PACKED_VECTOR2_ARRAY)
MAKE_TYPED_ARRAY_INFO(Vector<Vector3>, Variant::PACKED_VECTOR3_ARRAY)
```
are defined, but there is nothing analogous for Vector2i and Vector3i. I know very little C++ so I might be mistaken but it seems this simply has not been implemented yet.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would allow to have GDScript-functions take an array of Vector2i/Vector3i.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`void foo(const Vector<Vector2i>& points);`
`void foo(const Vector<Vector3i>& points);`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You could use Vector with floats, but that is not as nice.

### Is there a reason why this should be core and not an add-on in the asset library?

It has to be.

**Comment by Calinou** [comment]
Adding new Variant type has a performance cost, so it should be carefully considered.

> You could use Vector with floats, but that is not as nice.


An alternative is to use a Vector that accepts a PackedInt32Array (or PackedInt64Array) with a defined stride in the method's documentation (2 for Vector2i, 3 for Vector3i, 4 for Vector4i).

**Comment by alazifk** [comment]
My specific use case was to to pass directions. But since there are not that many bools or flags will do. For lists of points I prefer PackedIntArrays anyways, because they have less overhead. So I do not consider the change worth it if any performance costs are involved.

**Comment by MisterMX** [comment]
Can this be reopened because there are actual cases in core where these types are needed (see https://github.com/godotengine/godot/issues/66541)?

@Calinou can you pin-point to the place that causes performance implications? Because I don't see anything.

**Comment by Calinou** [comment]
> can you pin-point to the place that causes performance implications? Because I don't see anything.

Variant is full of `switch` statements that iterate over all types, so adding more types makes those `switch` statements slower by definition.

**Comment by Mickeon** [comment]
Where would **PackedVector2iArray** and **PackedVector3iArray** be used in, other than in the case made for the proposal? It feels very situational, I'm not too sure about this.

**Comment by Chaosus** [comment]
If introducing new types is not desired, maybe it makes sense to use an `Array` class instead (just need to add a note to the documentation).

**Comment by Mickeon** [comment]
I think it would also make sense to natively support typed arrays with core methods. There's some that return Arrays of Dictionaries that as of now merely describe they do in the documentation, so in these cases an Array of Vector2i would also make sense, I suppose, especially if access speed is no concern.

**Comment by kleonc** [comment]
> I think it would also make sense to natively support typed arrays with core methods.

It's already supported, check out e.g. https://github.com/godotengine/godot/pull/63959 or [the latest docs](https://docs.godotengine.org/en/latest/classes/class_object.html#class-object-method-get-property-list).

**Comment by Mickeon** [comment]
Alright then, I do see this proposal as being very unnecessary for now, yeah...

**Comment by MisterMX** [comment]
I didn't know about `TypedArray` yet. Thanks @Chaosus for the hint.

I opened #66655 that would remove the necessity of this extension.

**Comment by acgc99** [comment]
I recently requested this feature in the discussion #5713 , but @Calinou notified me that this is already tracked here. Since someone may think this proposal is unnecessary, I expose my case where it would be useful.

I have an 2D hexagonal grid (it is a 3D game, but the grid is 2D), that means that the hexagons positions are `Vector2` (`Vector3` in fact, but one component is the same for all). As the page of [Red Blob Games](https://www.redblobgames.com/grids/hexagons/) suggests, using other system of coordinates than the cartesian one is better for algorithms. So I implemented the axial coordinates, so now I have a set of `Vector2i`s. This also prevents floating point errors with the cartesian coordinates when performing operations with the positions. Now I have functions that return an `Array[Vector2i]`, but it would be nicer to have a `PackedVector2iArray`.

So they might also be useful for other coordinate systems rather than cartesian.

**Comment by MajorMcDoom** [comment]
> I recently requested this feature in the discussion #5713 , but @Calinou notified me that this is already tracked here. Since someone may think this proposal is unnecessary, I expose my case where it would be useful.
> 
> I have an 2D hexagonal grid (it is a 3D game, but the grid is 2D), that means that the hexagons positions are `Vector2` (`Vector3` in fact, but one component is the same for all). As the page of [Red Blob Games](https://www.redblobgames.com/grids/hexagons/) suggests, using other system of coordinates than the cartesian one is better for algorithms. So I implemented the axial coordinates, and now I have a set of `Vector2i`s. This also prevents floating point errors with the cartesian coordinates when performing operations with the positions. Now I have functions that return an `Array[Vector2i]`, but it would be nicer to have a `PackedVector2iArray`.
> 
> So they might also be useful for other coordinate systems rather than cartesian.

I also have very similar cases:
- A list of coordinates for any kind of grid system (hex, voxel, square, whatever)
- A list of index tuples (edges or triangles)

It is quite common for me, but I totally understand if the underlying performance implications outweigh that. It's nothing I can't work around.

**Comment by produno** [comment]
Likewise I also use Vector2i extensively in my game as I work with 2D grids of cells. I'm surprised there are not lots of cases like this considering there are plenty of games in Godot that also use 2D grids.

**Comment by Revahn** [comment]
Same situation here, with a grid of 3D cells. I need to store coordinates in arrays and I wanted to make it the best way, but now I need to choose between Array[Vector3i] and PackedVector3Array...
(btw, I suppose PackedVector3Array is still the best solution, but can someone confirm?)

**Comment by AThousandShips** [comment]
If you want to use integer coordinates you shouldn't use `Vector3`, so use `Array[Vector3i]` or `PackedInt32Array`

**Comment by ssaenger** [comment]
> Variant is full of `switch` statements that iterate over all possible types, so adding more types makes those `switch` statements slower by definition. 
> ...

I wouldn't be too concerned about this. The C++ compiler should treat a switch statement as a look-up-table. I am more certain that this is true if the cases are ordered from least to greatest. See https://github.com/pkivolowitz/asm_book/blob/main/section_1/jump_tables/README.md.

**Comment by Naros** [comment]
> I wouldn't be too concerned about this. The C++ compiler should treat a switch statement as a look-up-table. 

That's the case for C++, but you don't get look-up tables in GDScript or other scripting languages. In those, like GDScript, it creates a chain of if/else conditional jumps, so the larger the switch/match, the more cycles that operation takes.

**Comment by MajorMcDoom** [comment]
> > I wouldn't be too concerned about this. The C++ compiler should treat a switch statement as a look-up-table.
> 
> That's the case for C++, but you don't get look-up tables in GDScript or other scripting languages. In those, like GDScript, it creates a chain of if/else conditional jumps, so the larger the switch/match, the more cycles that operation takes.

This is a core feature proposal. There's no GDScript match statement of types involved here.

**Comment by Naros** [comment]
> This is a core feature proposal. There's no GDScript match statement of types involved here.

You're missing the point.

Those enums are represented in GDScript and other scripting languages, aren't they?  So while it starts on the C++ side, and a switch in C++ translates into a jump table, the equivalent scripting-layer feature to support the same semantics is a fancy series of if/else blocks.  The longer the if/else blocks are to support more variant types, the more cycles it takes.  So at the scripting layer, yes, there is some performance loss.

**Comment by MajorMcDoom** [comment]
> > This is a core feature proposal. There's no GDScript match statement of types involved here.
> 
> You're missing the point.
> 
> Those enums are represented in GDScript and other scripting languages, aren't they? So while it starts on the C++ side, and a switch in C++ translates into a jump table, the equivalent scripting-layer feature to support the same semantics is a fancy series of if/else blocks. The longer the if/else blocks are to support more variant types, the more cycles it takes. So at the scripting layer, yes, there is some performance loss.

I think I'm still missing your point. What exactly is the "equivalent scripting-layer feature to support the same semantic" you're referring to here?

Even GDScript bindings are written in C++, right? Are we talking about the performance of GDScript match statements that _users_ write?

**Comment by Naros** [comment]
> Even GDScript bindings are written in C++, right? Are we talking about the performance of GDScript match statements that users write?

Correct. 

This is one reason we opted for GDExtension for plugins rather than GDScript, because of the ability to take something like a match where you need to do different things for each `Variant::Type`, and in C++, this compiles down to a jump table, where it does not in GDScript. 

So as match statements get longer because more variant types are added, there is some performance drop due to how the VM handles matches differently from machine code.

**Comment by MajorMcDoom** [comment]
> > Even GDScript bindings are written in C++, right? Are we talking about the performance of GDScript match statements that users write?
> 
> Correct.

Ok then I did understand correctly the first time. If this was just a general warning to GDScript users that their match statements don't compile down to tables, I don't think it's directly relevant to the implementation of the proposal.

The performance concerns were raised originally as a reason against adding this new type. Then the response about lookup tables was to alleviate this concern. Your first response then, in context, made it seem like there was actually still a performance concern blocking the proposal that was overlooked. If that isn't the case, that's good to know.

**Comment by Naros** [comment]
From the pure C++ perspective, there's no issue w/performance.

**Comment by dalexeev** [comment]
> From the pure C++ perspective, there's no issue w/performance.

I'm not a performance expert, but optimization issues are not as simple as they may seem. Using jump tables isn't a silver bullet. For example, due to the increasing size of machine code, some things may no longer fit in the processor cache, and adding a single `case` statement can have a significant impact on performance (considering that `switch` statements on `Varaiant::Type` occur in many places throughout the engine).
