### ISSUE TITLE
Implement Editor Settings for autocomplete with StringNames and NodePaths

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#5496]
### Describe the project you are working on

A 2D platformer, recently started using NodePaths and StringNames where I can.

### Describe the problem or limitation you are having in your project

Autocomplete tools and similar are not respectful of my wishes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

After implementing https://github.com/godotengine/godot/pull/66332 I realized we don't actually have any consistent way to tell the editor when we want to use NodePaths or StringNames.

Naturally, both should be editor settings. They would affect autocomplete and dropping properties in editor and cause them to use the NodePath literal `^` and StringName literal `&`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simply append the literals at the beginning of the string when the setting is enabled.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not possible

### Is there a reason why this should be core and not an add-on in the asset library?

Dunno, seems too basic to not be in core, given NodePaths and StringNames are so easy to use.

**Comment by Mickeon** [comment]
After this setting I suppose it would make sense to refactor autocompletion to take it into account, because for example:
![image](https://user-images.githubusercontent.com/66727710/192231889-47ab200f-c899-4980-bb4f-54f6cb666af9.png)

This is *technically* slower but it's much, so much easier to grasp for beginners. With the setting enabled, these would display with the **^** prefix.

**Comment by MewPurPur** [comment]
That's the main thing the proposal aims to solve. I think the settings should be off by default.

**Comment by KoBeWi** [comment]
I think the names in autocompletion should just be unquoted:
![image](https://user-images.githubusercontent.com/2223172/192335950-8bb602f8-a89c-4050-ab81-6f83ec870cf4.png)
And only add `"^&` after accepting.

**Comment by MewPurPur** [comment]
@KoBeWi Didn't implement that, so the PR stays focused on more advanced autocompletion. I think removing the quotation marks would be controversial, or warrant a setting of its own. I would personally rather not be misguided about exactly what autocompletion will do. Only for things like braces after methods I think it's acceptable to not show the full thing, but with your idea, I can see a lot of people adding strings thinking autocomplete won't sort it out for them.

**Comment by KoBeWi** [comment]
I mean, I attached an actual screenshot from 3.5. Signals display this way and so far no one complained.

**Comment by Mickeon** [comment]
> ![image](https://user-images.githubusercontent.com/2223172/192335950-8bb602f8-a89c-4050-ab81-6f83ec870cf4.png)

I need to see and understand how code completion works for these more hard-coded options because it's not just a matter of appending a String. The signal symbol to the left and the lack of quotes, which are added only afterwards...

**Comment by MewPurPur** [comment]
@Mickeon There is an autocompletion options struct, which has a string for what's shown and another string for what's gonna actually be filled. Idk how it's in 3.5 though. My PR dances around those areas of autocompletion, you can check it out.

**Comment by Mickeon** [comment]
Oh that I'm aware. The question was more about, what actually assigns these specifically hardcoded options (e.g. the signals in 3.x, or a list of Nodepaths when inputting "$"). Because that part may be the one needing of some refactoring, to account for this Proposal's feature.
