### ISSUE TITLE
Enhance RichTextLabel

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#5513]
### Describe the project you are working on

A dictionary app, and I want implement a RichTextEdit extends RichTextLabel, now I was implemented some features.
![GIF](https://user-images.githubusercontent.com/35988767/192995845-bd8d7afe-c028-47ae-9e11-f385cb5ed770.gif)

### Describe the problem or limitation you are having in your project

But there was some problem on current RichTextLabel:
1.  When I added some tag like bold, the selection was gone, and I can't select text by code because where was only `deselect` and `select_all`, so I need a `select(from,to)` api for that.
2. I can't draw my flash cursor at correct position because there have not api get a character position, so I neet a `get_position_for_character_at(index)` api for that

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1. Implement `select(from,to)` api.
2. Implement `get_position_for_character_at(index)` api.
OR:  Implement a `RichTextEdit` by core, I realy wish it.

I often use GODOT for GUI-application, I realy need a `RichTextEdit`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I can't!

### Is there a reason why this should be core and not an add-on in the asset library?

/

My project:
[RichTextEditTest.zip](https://github.com/godotengine/godot-proposals/files/9673360/RichTextEditTest.zip)

**Comment by Calinou** [comment]
@CsloudX Please open one separate proposal per feature requested.

**Comment by CsloudX** [comment]
@Calinou Thanks, I was separate to 2 proposal for this yet, and should I need close this proposal?

**Comment by Calinou** [comment]
> @Calinou Thanks, I was separate to 2 proposal for this yet, and should I need close this proposal?

You can open just one more proposal, and edit this proposal to only reference the other proposal.

**Comment by Calinou** [comment]
> @Calinou Thanks, I was separate to 2 proposal for this yet, and should I need close this proposal?

You can open just one more proposal, and edit this proposal to only reference the other proposal.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5517, https://github.com/godotengine/godot-proposals/issues/5518 and https://github.com/godotengine/godot-proposals/issues/5519.
