### ISSUE TITLE
Put language names in the editor settings

### ISSUE THREAD

**Issue by realcoloride** [godotengine/godot-proposals#5516]
### Describe the project you are working on

No project

### Describe the problem or limitation you are having in your project

I do not have any problems or limitations on my project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The current drop down menu to select the language looks like this: 
![image](https://user-images.githubusercontent.com/108619637/193096399-4c758e03-6c28-4829-8003-a754b33cac19.png)

Which is kind of messy and even though for some people can be obvious to find their language, I feel like it could still be a neat addition for non english speakers.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I wish that instead of two letters or a few in order to name the language, a name with its name in english and in its language could be better to understand for non english speakers.

For example, instead of:
en = English or fr = French (Français)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know how the godot engine works itself so I do not know how it can be changed, but I feel like the drop down menu could store its name and how it should be described as above somewhere.

### Is there a reason why this should be core and not an add-on in the asset library?

It should be a core addition because I feel like it should be something that a non english speaker wants a dedicated asset library to have names on the languages in order to find their language.

**Comment by Calinou** [comment]
The option stores the language name directly – it's not an enum. Therefore, we'd either have to:

- Change the language setting to store an enum (which breaks compatibility every time a language is added, as the list is always sorted alphabetically).
- Store the string with the language name, which is redundant information and may change if a translation is updated (unlikely, but not impossible).

**Comment by dalexeev** [comment]
I think we are talking only about the visual representation of the locale. It does not matter in what form it is stored in the config.

**Comment by Calinou** [comment]
> I think we are talking only about the visual representation of the locale. It does not matter in what form it is stored in the config.

When using a String property type with a enum property hint, the displayed value always matches the stored value.

**Comment by timothyqiu** [comment]
It's not difficult to add a similar syntax for string enums, e.g. `Display A:ValueA,Display B:ValueB`, but it breaks compat.

**Comment by realcoloride** [comment]
Was added & pushed.
