### ISSUE TITLE
Add PackedFloat16Array class

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot-proposals#5520]
### Describe the project you are working on

FPS shooter with hexagonal world chunks using heightmap.

### Describe the problem or limitation you are having in your project

I'm generating the world chunk meshes using ArrayMesh and need to add custom data to the vertices. Two of the custom formats are "Indicates this custom channel contains half precision float colors, encoded as [PackedByteArray](https://docs.godotengine.org/en/latest/classes/class_packedbytearray.html#class-packedbytearray)" and Godot lacks an easy method to create such arrays.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A PackedFloat16Array with a to_byte_array() method would help, similar to how PackedFloat32Array and PackedFloat64Array works.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I think it's pretty self-explanatory in this case, right?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I *think* the workaround is to use PackedByteArray encode_half, but it feels a bit strange that I have to do that for halfs

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think it could be an add-on

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/5486#issuecomment-1257082004.

**Comment by JohanAR** [comment]
Don't know much about how GDScript works internally, but I suppose there is no way to have types/classes that aren't part of the variant?

What would you think about adding "append_half" and similar convenience methods to PackedByteArray? The encode functions seem to low level compared to how most of GDScript feels. I.e. you have to pre-allocate space for what you want to encode, and you have to think about the byte size of whatever you're encoding.

I mean it's not difficult for a non-beginner programmer, but most of the time writing GDScript feels like a high level language, like Python, and then occasionally having to use methods like these feels more like you're suddenly working with a low level language like C. :)

**Comment by Zireael07** [comment]
> but I suppose there is no way to have types/classes that aren't part of the variant?

No :(

Personally I'd love it if PackedByteArray received more convenience methods, including converting to/from int (currently packing my numbers straight into an int, but packedbytearray would be more readable)
