### ISSUE TITLE
Make the D in "2D" and "3D" uppercase by default for node names

### ISSUE THREAD

**Issue by DoomSpace93** [godotengine/godot-proposals#5529]
### Describe the project you are working on

This issue applies to most projects

### Describe the problem or limitation you are having in your project

In Godot 4, creating a new node with the -2D or -3D suffix will have a default name with a lowercase d, i.e. "Node3d". (Shown below) This looks really strange, since it doesn't match the way the suffix is capitalized in the rest of the editor, such as in the script editor, the docs, the inspector panel, and the "add node" dialog. Even outside of Godot, "2D" and "3D" are usually formatted with an uppercase D.
![godot4](https://user-images.githubusercontent.com/114851711/193443897-d2575212-efa6-49e0-a0d4-df274eaca6b6.png)
Capitalizing the D was the default behavior in Godot 3, as seen below. The lowercase D appears to have started with Godot 4.
![godot3casing](https://user-images.githubusercontent.com/114851711/193444021-9469f7e7-95f8-4191-b5f9-5b302aea8367.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Restore the Godot 3 convention for node casing, which would make the D in -2D and -3D capital for node names.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![godot4casing](https://user-images.githubusercontent.com/114851711/193443963-5f7b0c33-c6b4-4864-bf8c-d8e7f6ac7578.png)

This is how the default casing should look when using the PascalCase convention in the editor, which is the default casing. camelCase would look like "node3D", "node2D", etc. This would not affect snake_case, which uses all lowercase letters anyways.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It doesn't seem to be possible to do this via script.

### Is there a reason why this should be core and not an add-on in the asset library?

This is an improvement to consistency in the editor.

**Comment by Mickeon** [comment]
This is a bug, actually.

**Comment by KoBeWi** [comment]
Yes: https://github.com/godotengine/godot/issues/65803
