### ISSUE TITLE
Make Camera2D Scale affect the screen size, and a rework of the zoom.

### ISSUE THREAD

**Issue by ettiSurreal** [godotengine/godot-proposals#5532]
### Describe the project you are working on

Continuing from https://github.com/godotengine/godot-proposals/issues/5525

### Describe the problem or limitation you are having in your project

As described well in https://github.com/godotengine/godot/pull/66757, the changes brought in https://github.com/godotengine/godot/pull/57392 make the `zoom` property difficult to work with, giving higher precision to zooming in and restricting zooming out.
Additionally addressing zooming in requiring increasingly large values depending on the zoom level.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

At first my idea was to just revert the behavior back to how it worked pre-4.0, but a few users did not like the idea. So tried thinking of something that could get the best of both worlds.

The screen size is now based on inherited Node2D's `scale` property, which would functionally work exactly how it did pre-4.0, except with a possible support of scale of 0, which would logically just render a single row of pixels.
This also has the added benefit of the Scale Mode being able to control the view size.
Alternatively, if it's too difficult to implement or if there are existing use cases of changing Camera2D's scale, a new property could be added to Camera2D that works exactly as described above.

Instead of a XY value, the zoom would now be a 0-1 range slider, 0 being the original camera view, 1 being fully zoomed in (equivalent of the scale of 0), 0.5 being halfway through. Additionally, we could have a smaller (optimally differently colored) rectangle showing the current zoom level compared to the camera size.
_What about zooming out?_
For unlimited zooming out you would use `scale`, if you want to have a built in limit to zooming out, you can always have the starting value be between 0 and 1.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`scale` under `Node2D` now affects the view size in the same way `zoom` did pre-4.0.

`zoom` is now a slider, interpolating between the starting view size to fully zoomed in.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can see it being possible to make with a script with pre-4.0 behavior, not so much with 4.0.

### Is there a reason why this should be core and not an add-on in the asset library?

Changing the functionality of a built-in node.

**Comment by Zireael07** [comment]
Seems like a good compromise - but please remember to document it!
