### ISSUE TITLE
4.x Add grid snapping to tileset physics editor

### ISSUE THREAD

**Issue by boruok** [godotengine/godot-proposals#5534]
### Describe the project you are working on

Pixel-art city builder.

### Describe the problem or limitation you are having in your project

Having bad times with aligning exact size for polygon points in physics editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Option for snapping polygon points will be helpful, as in 3.x branch.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

XY spinboxes for size and snap button for toggle.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

core feature

### Is there a reason why this should be core and not an add-on in the asset library?

core feature

**Comment by TheDuriel** [comment]
Isn't this a thing though?

At least on 3.x I am fairly sure you can set a size for grid snapping of the various polygons.

**Comment by dalexeev** [comment]
No, there is no grid snapping in 4.0.

https://user-images.githubusercontent.com/47700418/193739921-9c38fcb5-fb56-4acb-8ee3-d4e9785d2a4c.mp4

**Comment by KoBeWi** [comment]
Closing in favor of #5847, which is more detailed.
