### ISSUE TITLE
Blender FBX2glTF path intuitive

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-proposals#5547]
Blender and FBX2glTF are being moved around project settings and editor settings. You may find the "enabled" boolean but not the other. The tooltip of the boolean redirects to the file, not the editor settings.

I do believe the paths should remain on Editor settings instead of being project-specific (imagine setting this for every project lol), so the locations of paths and booleans are perfect imo.

Anyway, my suggestion is quite simple. A button (with an arrow icon or sth) on the ProjectSettings/FileSystem/Import, which opens EditorSettings/FileSystem/Import

In this way, anyone who finds the boolean "enabled" will easily find the path to change or set as well. It's far better than even a lengthy tooltip explaining to open EditorSettings (which would also help btw)

Lastly, a button to check file validation (if any file exists in the string path the user has set) with a green tick box (like the one in import project or new project is great)

------------------------

Off-topic: Is this repo for bigger features, instead of "just add a button"? godot main repo issues has only bugs (this is not a bug) and redirects here for feature proposals

**Comment by Zireael07** [comment]
This repo is for "bigger features" or at least those that have a mockup/code attached, what you posted should be under "Discussions" as there is no code/mockup here.

**Comment by Calinou** [comment]
Closing per @Zireael07's comment.

Also, the project settings dialog doesn't make it possible to add buttons with custom behavior for individual settings. It's a key-value mapping system – nothing else can be done within the project settings.
