### ISSUE TITLE
Only show named layers in layer menu

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-proposals#5548]
### Describe the project you are working on

A simple FPS game.

### Describe the problem or limitation you are having in your project

Clicking the dots button of a physics/render/navigation layer property brings up the layers menu. In most cases, I will only name a few of them. Unnamed layers take up lots of screen space. It's wasteful since I only use named layers.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Only show named layers in the layers menu and add a menu item at the bottom that directly sends you to the corresponding project settings page.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I've implemented this on my own branch:  https://github.com/timothyqiu/godot/tree/named-layers

The layers menu only show named layers. There's also an "Edit layer names" option that sends you directly to the corresponding project settings:

![Peek 2022-10-06 19-16](https://user-images.githubusercontent.com/372476/194299542-8a163420-1fd9-45ac-a669-0171bbf48971.gif)

When there're no named layers:

![ksnip_20221006-191747](https://user-images.githubusercontent.com/372476/194299608-cca1ea4a-28aa-408b-8d3a-d61a27b1a796.png)

I've considered adding an entry for unnamed layers that are checked in the grid. But because these properties checks the first bit by default, there would always be one "Layer 1" entry in that menu by default, which looks weird.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

Impossible to implement.

**Comment by Zireael07** [comment]
That was really fast :rocket:

**Comment by Mickeon** [comment]
Sometimes it's really about "Huh, I never thought of that"
