### ISSUE TITLE
Add support for yielding upon a `call_deferred()` call. 

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot-proposals#5556]
### Describe the project you are working on

I am working with multithreading and certain functions that interact with the scene tree need to be called with `call_deferred()` in order to be [thread safe](https://docs.godotengine.org/en/stable/tutorials/performance/threads/thread_safe_apis.html#doc-thread-safe-apis). 

### Describe the problem or limitation you are having in your project

I'd have to write proxy functions that emit a completion signal that would add additional clutter to the spaghetti monster for anything that interacts with the scene tree.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

make this possible: `yield(call_deferred("function_name"),"completed")`, It would be a lot more straight foreword and easier to understand. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
#proxy function
signal completed()
func add_child_and_signal(child):
	add_child(child)
	emit_signal("completed")

#thread
func thread_func():
	var child = Spatial.new()
	#call_deferred required for thread safety
	call_deferred("add_child_and_signal",child)
	yield(self,"completed")

```

could be shortened to:

```gdscript
#thread
func thread_func():
	var child = Spatial.new()
	#call_deferred required for thread safety
	yield(call_deferred("add_child",child),"completed")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I just thought it would be convenient to have this functionality, and the "few lines of code" starts to add up if this basic functionality is needed for multiple functions.

### Is there a reason why this should be core and not an add-on in the asset library?

It is to do with gdscript itself.

**Comment by dalexeev** [comment]
The purpose of the `call_deferred` method is to "schedule a method call in the next frame". After this task is completed, the method ends. Therefore, this proposal violates the logic of this method.

If you need to call the function and wait for the signal in the next frame, you can:

```gdscript
yield(get_tree(), "idle_frame")
add_child_and_signal(child)
yield(self, "completed")
```

Or you can make the `add_child_and_signal` function asynchronous:

```gdscript
func add_child_deffered(node):
    yield(get_tree(), "idle_frame")
    add_child(node)

func another_func():
    var node = Node.new()
    yield(add_child_deffered(node), "completed")
```

**Comment by sairam4123** [comment]
Here's implementation in GDScript:

```gdscript
func call_deferred(method, params):
    yield(get_tree(), "idle_frame")
    self.call(method, params)
    emit_signal("completed")
```
Code may not be runnable.

**Comment by KnightNine** [comment]
@dalexeev 

> The purpose of the `call_deferred` method is to "schedule a method call in the next frame". After this task is completed, the method ends. Therefore, this proposal violates the logic of this method.

 I didn't think it actually advances any frames, I was pretty sure that it scheduled then merges the call with the main thread when it is unoccupied, and that it would happen all within whatever frame the game happens to be on.  But I have tested it and have found out that I am wrong about how I thought it worked.

I still don't really get how waiting a frame with `yield(get_tree(), "idle_frame")` or even with `yield(get_tree().create_timer(1),"timeout")` is removing the function call from the thread it was initially called from.

This also makes it pretty difficult to interact with the scene tree from a thread without also merging the thread back into the main thread. Since if I were to yield upon  `emit_signal("completed")` (from the second comment's example) within my "thread_function" (which I would've started with another thread), the "thread_function" has then merged with the main thread and I am no longer able to get any use out of the thread. 

```gdscript
#called with thread.start(self,"thread_func")
func thread_func():
	custom_call_deferred("func_name",null)
	yield(self,"completed")
	# at this point the purpose of calling this function from a thread is defeated
	#i can call wait_to_finish() from here because this function is now in the main thread
	thread.wait_to_finish()
```

so rip... 💀
