### ISSUE TITLE
Add Input.MOUSE_MODE_CONFINED_HIDDEN flag

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-proposals#557]
**Describe the project you are working on:**
Turn-based strategy

**Describe the problem or limitation you are having in your project:**
I want animated custom cursors to be implemented but also want the cursor to be confined within the window. By hiding system cursor I draw a sprite instead of it. I don't want to apply custom cursor using `Input.set_custom_mouse_cursor` - it's limited and does not support effects like rotation and animation which I needed.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
By adding this flag the system cursor will be hidden while still be confined within the window...

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I didn't found an easy way.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a core thing by its nature.

**Comment by KoBeWi** [comment]
> Input.set_custom_mouse_cursor

What if you use this to set an empty texture? That's effectively invisible.

**Comment by Chaosus** [comment]
It's inelegant and produces a strange color-invert effect if texture is empty (unable reproduce it here cuz Print-screen handles it correctly.

**Comment by Chaosus** [comment]
If I decreased the size to 1x1 of an empty png texture the inverted effect is shrinking down to that size but the small inverted dot will still be visible which is undesired.

**Comment by golddotasksquestions** [comment]
How is that different from using MOUSE_MODE_CAPTURED and a Sprite+Animationplayer?

**Comment by Xrayez** [comment]
@golddotasksquestions `MOUSE_MODE_CAPTURED` keeps the mouse pointer centered (cannot be moved, but mouse acceleration is still registered, useful for FPS games), while `MOUSE_MODE_CONFINED` restricts the mouse to game window (useful for RTS games).

**Comment by golddotasksquestions** [comment]
@Xrayez Sorry, I meant MOUSE_MODE_HIDDEN. Done some experimenting and I guess the difference is with HIDDEN the mouse would be able to leave the window if the game is running in windowed mode and not full screen. 
This has nothing to do with cursor Animation, I suppose that was what confused me.

**Comment by Chaosus** [comment]
The problem is solved if I take a texture filled with 1 value on alpha-channel, I don't know if this issue should be closed for now - I still think this hack is not obvious thing and the engine should provide a correct way to solve it.

**Comment by Calinou** [comment]
The workaround works nicely, but make sure to re-apply it when the user focuses back on the window (e.g. when alt-tabbing):

```gdscript
func _ready() -> void:
	Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)
	hide_hardware_mouse_cursor()


func _notification(what: int) -> void:
	match what:
		NOTIFICATION_WM_FOCUS_IN:
			call_deferred("hide_hardware_mouse_cursor")


func hide_hardware_mouse_cursor() -> void:
	# Use a transparent cursor texture to hide the hardware cursor.
	Input.set_custom_mouse_cursor(null)
	Input.set_custom_mouse_cursor(preload("res://data/textures/transparent.png"))
```

**Comment by jsoeller** [comment]
Amazing. It must be the quality of the .png you used, because I tried Input.set_custom_mouse_cursor(preload("...")) with another transparent image and all I got was black. I'm also getting further success using [](http://www.1x1px.me)

Thank you! Was banging my head against the wall for a loooong time. And yes, we should have a HIDDEN + CONFINED flag option. I believe aaronfranke has[ set up a Godot 4.0 branch that changes the enum constants to bitwise](https://github.com/godotengine/godot-proposals/issues/1810). Referenced by **Chaosus** in that link

**Comment by sk33z3r** [comment]
Just want to add another note to this for those still using v3.5 that come across this. All the 1x1 fully transparent pixels I attempted kept giving me black boxes, even the ones linked here. Keep in mind I am adding the cursor image under Project Settings, as I want to `CONFINE` _and_ show a custom cursor.

I guess Godot forces the full alpha value of all transparent pixels if there are no pixels with alpha > 0; so if you make a 1x1 pixel that has an alpha value of `1` then Godot is happy and the cursor is fully hidden.
