### ISSUE TITLE
Add support for Android Themed Icons

### ISSUE THREAD

**Issue by lucasnlm** [godotengine/godot-proposals#5572]
### Describe the project you are working on

Android 13 introduces a new kind of customization: Themed Icons.
With it, it's possible to make the app's icons use the theme color.

Example:
<center>
<img src="https://user-images.githubusercontent.com/1326126/195114364-2dfef24a-d6ec-4f61-bccd-d01560371065.png" width="300px" /></center>

- Godot already supports Adaptive Icons.

### Describe the problem or limitation you are having in your project

Currently Godot doesn't support Themed Icons without create a custom project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot could have a `theme icon` field in the Launcher Icons options.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Basicly, Godot supports adaptive icons with the following XML:

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/icon_background"/>
    <foreground android:drawable="@mipmap/icon_foreground"/>
</adaptive-icon>
```

By adding one line, it will support themed icons (`<monochrome android:drawable="@mipmap/icon_monochrome"/>`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/icon_background"/>
    <foreground android:drawable="@mipmap/icon_foreground"/>
    <monochrome android:drawable="@mipmap/icon_monochrome"/>
</adaptive-icon>
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If not used, all we have to do is omit the `<monochrome android:drawable="@mipmap/icon_monochrome"/>` line and it will work as is today.

### Is there a reason why this should be core and not an add-on in the asset library?

We already support Adaptive Icons and Themed Icons is part of it.
By adding this Godot will also to encourage the right Android customization support.

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:

**Comment by RustoMCSpit** [comment]
update?

**Comment by Calinou** [comment]
> update?

To my knowledge, nobody is currently working on this, but we welcome pull requests.
