### ISSUE TITLE
Add Project Setting to show iOS Status Bar

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot-proposals#5573]
### Describe the project you are working on

A portrait mode app that does not require the iOS status bar to be disabled. It also does not require Control Center and going home to take two swipes, which is default behavior for Godot exports on iOS.

To make sure we're all on the same page, this is what I mean by the status bar.
![image](https://user-images.githubusercontent.com/28269330/195108319-dc62e9b8-74e4-45f4-a1ac-87f0a6d3eb46.png)

I'm already in the process of implementing this for myself to be used on a custom engine build, so if this preposal is considered fine I'll probably be able to just submit that.

### Describe the problem or limitation you are having in your project

There isn't a project setting to show the status bar, just a setting to show the navigation bar.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would allow the status bar to be visible while the app is open, something which appears to be impossible without editing the engine source at the moment. I've even tried toying with Xcode settings to turn show status bar on, and turn full screen mode off, and all of them seem to be ignored by the built app.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A project setting in either Display/Window/iOS, or in the export settings. There is a similar setting for Android in exports, for Immersive Mode.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't believe it can, I think it requires recompiling the engine from source.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think this could be an add-on, but even if it could, there is already a setting to control the home bar on iOS, and a setting to toggle Immersive Mode on android. This functionality is also built in to Unity, which can be seen in their docs and utilized notably by Pokemon Go.

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:
