### ISSUE TITLE
Ability to turn off Texture Filtering for StyleboxTexture

### ISSUE THREAD

**Issue by petterthowsen** [godotengine/godot-proposals#5577]
### Describe the project you are working on

Pixel art GUI Theme

### Describe the problem or limitation you are having in your project

It is not possible to use pixel art for StyleboxTexture since import flags were removed and StyleboxTexture does not have a filter option.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Pixel art should work for styleboxes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Self-evident

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Obvious reasons

**Comment by Mickeon** [comment]
See also https://github.com/godotengine/godot-proposals/issues/5225

**Comment by KoBeWi** [comment]
But you can set filtering in the node that draws your stylebox.
