### ISSUE TITLE
Add bitfield enums to GDScript

### ISSUE THREAD

**Issue by Germenzi** [godotengine/godot-proposals#5578]
### Describe the project you are working on

I am workin on tbs game. As for me, It will be useful for finding and filtering game objects having necessary properties.

### Describe the problem or limitation you are having in your project

A lot of boilerplate code, like creating an object, adding flags to it and comparing objects' fields instead of just integers.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Just create new type, like an enum, but where values will grow exponentially. Instead of `1, 2, 3, ...` there will be`1, 2, 4, 8, ...`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Sintax like that may make constructing bitflags a lot easier:
``` gdscript
bit_enum Properties {
    ON_FIRE, # 1
    SLOW, # 2
    ANGRY # 4
    # etc.
}
```
Just write:
`ON_FIRE|SLOW|ANGRY`
Readable and short.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, you can use `const` like [here ](https://godotengine.org/qa/22370/bit-flags-in-gdscript).
Bit doing so it will be difficult to add new bitflags at the middle of constants list.

### Is there a reason why this should be core and not an add-on in the asset library?

Becouse it's new gdscript sintax

**Comment by Calinou** [comment]
4.0 already exposes bitfields, but there is no way to define them in GDScript. I suppose adding a `@bitfield` annotation you can add in front of `enum` makes the most sense, as this is mostly for documentation purposes.
