### ISSUE TITLE
Add comment blocks to visual shaders

### ISSUE THREAD

**Issue by Malcolmnixon** [godotengine/godot-proposals#5592]
### Describe the project you are working on

Maintaining godot-xr-tools asset and demo project

### Describe the problem or limitation you are having in your project

Complexity in understanding what different parts of visual shaders are responsible for.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a "comment" block to visual shaders.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The following is a mockup of drag-drop comments if they were just to be positioned on the graph:
![image](https://user-images.githubusercontent.com/1863707/195925347-354f8578-4138-4893-9512-0d4b70c9036e.png)

An alternate approach would be to drag a region around the blocks. This approach *might* actually make it possible for the comments to be emitted into the generated code (although that may be challenging with emitter-order):
![image](https://user-images.githubusercontent.com/1863707/195926067-423834df-c03a-41c9-ad07-b5f9edad8c38.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It might be possible to write an accompanying README.md or equivalent, but a separate document *always* ends up getting out of sync with the implementation.

### Is there a reason why this should be core and not an add-on in the asset library?

I believe this would need to be part of the visual shader editor which is part of the core.

**Comment by paddy-exe** [comment]
@Malcolmnixon This is already possible though if I am understanding your proposal correctly:
![image](https://user-images.githubusercontent.com/38077837/195947609-d0f06910-5420-43f5-a838-a5a0c13fc6ca.png)

**Comment by Malcolmnixon** [comment]
Lol, just found it. Sorry, I was looking in Godot 3 and online and couldn't find anything about godot shader graph comments.
