### ISSUE TITLE
Add distance fog and more non-volumetric fog options (improved 3.x-style fog)

### ISSUE THREAD

**Issue by ettiSurreal** [godotengine/godot-proposals#5625]
### Describe the project you are working on

Mostly just messing around, i guess possible projects people could need this for are horror games with low field of vision, retro style games, and open-world games with distance cutoff.

### Describe the problem or limitation you are having in your project

The new fog implementation doesn't offer nearly as much artistic freedom, and is a harder to set up for specific needs and distance.
A different take of https://github.com/godotengine/godot-proposals/issues/4619.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Bring back an implementation of the 3.X fog, as either dropdown options for the regular fog or separate tabs in Environment, i'll continue with the latter.

The current fog would be renamed to Exponential Fog
There would be two new options called Distance Fog and Height Fog.
The idea is that these could be stacked as the user wants, although i am not sure how feasible/practical that is, like in case the different fog types have different colors. If anyone knows how it could be handled let me know!

Distance fog would works the same was as depth fog works in 3.X, possible improvements i could see are:
- Spherical and Cylindrical modes, spherical is the default one, and cylindrical ignores the Y axis.
- Gradient color, either replacing Color if there are no performance concerns or being a toggle. Would work by mapping values based on their distance to the gradient Depth Begin being far left of the gradient and Depth End being far right.
- Sky affect, working the same way as exponential fog.

Height fog would also work the same way as height fog in 3.X, with:
- Possibly a way to handle fog from below and above at once, an idea is to have a toggle with options "One Sided" and "Two Sided", one sided would only have Min and Max, while Two sided would have Lower and Upper Min and Max.
- Gradient color and Sky affect, working the same way as Distance fog.

If stacking different colored fogs isn't possible, Exponential, Depth and Height fog could be under the same dropdown, each individually toggle-able, although sharing some common settings as they need them.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would work like in 3.X, with some extra features.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Could probably be made as a shader, but they are a quite advanced topic, especially for beginners.

### Is there a reason why this should be core and not an add-on in the asset library?

Missing functionality from previous versions.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/66030 implements this, but as I wrote in that PR, I wonder if there are real world use cases to exponential non-volumetric fog. While specialization constants make it possible to support both with a performance penalty, the size of the specialization constant map is finite. We'd like to make greater use of SCs in other parts of the renderer, so we need to make sure each use of a specialization constant is well-justified.

**Comment by Calinou** [comment]
For future reference, this was implemented in 4.3 by https://github.com/godotengine/godot/pull/84792.
