### ISSUE TITLE
Physics

### ISSUE THREAD

**Issue by Piotrek94K** [godotengine/godot-proposals#5628]
### Describe the project you are working on

#player start spawn = x at speed = 0 km/h
if user clicked on the variable="up arrow" then  
at every second with each second held
accelerate +1 km/h and move the vehicle:
if the speed is x km/h move the player
 forward about 0,27 m/s * x km/h 
about every second.
I don't know how to turn it into a code (so far I'm only modifying one game and trying to create my own) but maybe someone can and maybe we will have better vehicle physics in Godot.  Thanks for your time.  Constructive criticism is welcome.

### Describe the problem or limitation you are having in your project

As we know the physics of Godot is not the best (at least that's the opinion)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This or a similar code would make it easier and more realistic to create a game with vehicles

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

#player start spawn = x at speed = 0 km/h
if user clicked on the variable="up arrow" then  
at every second with each second held
accelerate +1 km/h and move the vehicle:
if the speed is x km/h move the player
 forward about 0,27 m/s * x km/h 
about every second.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know

### Is there a reason why this should be core and not an add-on in the asset library?

This can improve Godot physics and make game development easier

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for feature proposals *with concrete technical implementation ideas* only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by KoBeWi** [comment]
This was not a support question.
But still, it should go to [discussions](https://github.com/godotengine/godot-proposals/discussions).
