### ISSUE TITLE
Move _global_script_classes from godot.project to local cache

### ISSUE THREAD

**Issue by c3-hoge-fuga-piyo** [godotengine/godot-proposals#5631]
### Describe the project you are working on

Team game development using Godot ang Git

(I am sorry if it is rude or inappropriate to you, since I use the online translation site)

### Describe the problem or limitation you are having in your project

Using `class_name` in different working branches conflicts with changes to `_global_script_classes` in `godot.project` when merging.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since `_global_script_classes` is synchronized with the state of the scripts in the project, there is little need for version control, and it is appropriate to store them in a local cache such as `.import/*` (Godot 3.x) or `.godot/*` (Godot 4.x).

Improve your development experience with branches while benefiting from `class_name`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Store `_global_script_classes` on local cache and get class information from local cache instead of `ProjectSettings`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it is a core behavior.

### Is there a reason why this should be core and not an add-on in the asset library?

Cannot be supported by add-ons as it is a core behavior.

**Comment by dalexeev** [comment]
While I support the idea of this proposal, the reason may be technical (`project.godot` is available early in initialization or this cache is required after the project is exported). Need a response from GDScript team.

**Comment by c3-hoge-fuga-piyo** [comment]
https://github.com/godotengine/godot/pull/43877

There is evidence of a previous attempt to respond with PR here.
