### ISSUE TITLE
Add a way to precompile specific shader permutations and identify shaders compiled during gameplay

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot-proposals#5654]
### Describe the project you are working on

2.5D platformer.

### Describe the problem or limitation you are having in your project

I'm constantly running into hitches as shaders get built, even though I tried to do the hacky things like throw all the materials on quads and display them when the game launches to force shaders to build, but I've found there are a huge number of different conditions that cause different permutations of shaders to build, such as:
- Octahedral compression enabled/disabled on mesh.
- Meshes with/without skeletons.
- Meshes with/without lighting
- Meshes that cast shadows (only seems to trigger when rendering with a light in the scene).

Trying to accommodate for all these possibilities (and not use a slow brute force method to compile every shader for every possible permutation) is a LOT to manage, especially since there's not any output to indicate what shader is being built and why.

This is a major problem that a number of people using Godot have complained about and tried to hack around, but it's very complicated and not user friendly at all!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Keep track of what shaders are built as the game runs (so we're not building every POSSIBLE permutation of shaders, just the used ones) and store them in a list that can be compiled at load time to avoid hitches while playing.  Ideally, this could just be something enabled and handled automatically, but it would be nice to, at the very least to:
- Have a project setting with a list shaders that you could add to with checkboxes for the flags you needed the shader compiled for.
- Output a list of shaders that were NOT compiled by that list as well as the conditions used in the compile (compression, lighting, etc) so they can easily be added.
- Option to disable this in editor debug mode so we don't have to wait for all the shaders to build when testing.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In my project, I have this:
![image](https://user-images.githubusercontent.com/7751182/197906801-be5742dd-2c2c-47e0-a100-932bf0b8e682.png)

And would display the materials 1 per frame to a quad that's shown on game startup, but this doesn't account for the different mesh/lighting conditions, so imagine there are checkboxes for that.

Also, if this could be handled at the engine level, users wouldn't need to do hacky things like display a mesh somewhere in front of the camera.

BONUS POINTS: If the shaders could be compiled in the background so an animated loading screen or something can be shown, that'd be amazing.  On some hardware, the shaders take a while to compile.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I imagine any larger project is going to want to use this.  It *can* be worked around, but it's more than a few lines of script, requires a lot of data setup, and it's very difficult to determine why shaders are being built.  I had to actually hack the engine to output what shaders were being compiled, and even with that, it was a challenge, because all the comments, blank lines, etc. are removed from the godot shader before being passed in there.

### Is there a reason why this should be core and not an add-on in the asset library?

Every game having hitches in it isn't really a good look for Godot, and fixing that should be the default behavior.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/4754.

**Comment by jitspoe** [comment]
Yeah, I think this can be closed out with https://github.com/godotengine/godot-proposals/issues/4754 -- pretty much the same thing with a more detailed proposal.  Guess I didn't search for the correct things to find it.

I had messed around with the async stuff, but it seems it needs to build the ubershader synchronously, which completely defeats the purpose of async building, and it's even worse than just building the regular shaders at the start because the ubershaders take WAY longer to build.
