### ISSUE TITLE
Ajuda mais eficiente ao digitar linhas com erros

### ISSUE THREAD

**Issue by MoisBR** [godotengine/godot-proposals#5664]
### Describe the project you are working on

Sao varios projetos. Mas no momento estou focado em criar um jogo de sobrevivencia ao estilo de minidaz + stranded2(tudo em 2d) onde estou tendo dificuldades em corrigir as linhas de erro.

### Describe the problem or limitation you are having in your project

O godot some com as opções de texto/syntaxe que só aparece quando não ha erros. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Ajuda na correção de linha de codigo sugestões de texto

Sou usuario do game maker 8.0 free e estou tentando migrar pro godot.
Sugiro que dê uma olhada no editor de script(gml) desse programa, para entender o que tento dizer.

Esse app ajuda muito na correção de codigo.
Nele, nao importa se o codigo está correto ou nao, as opcoes de syntaxe continuam, as vezes ate pertubam um pouco, pois, ao digitar se intromete atrapalhanddo a digitação. 

Se o godot usar esse recurso so no momento de erro seria muito util.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Quando escrever alguma linha de codigo, ao mostrar o alerta de erro, mostrar também uma possível solução ao passar o mouse ou selecionar o "erro"

Estou falando de opcoes do priprio godot. Por exemplo se eu comecar dugitar um método, normalmente as opções surgem. Mas no erro onde mais precisamos não tem!

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Apenas se nao houver erro de syntaxe, podendo ser ignorado.
Mas o que incomoda é no momento de corrigir, as opções ja conhecidas somem.

### Is there a reason why this should be core and not an add-on in the asset library?

Não sei.sou novo por aqui

**Comment by Calinou** [comment]
Godot 4.0 has already resolved this issue by allowing autocompletion to work while there are errors. Multiple errors can now be displayed at once too.

PS: This is an English-speaking platform. Please write issues and comments in English in the future (even if it requires you to use a translator).
