### ISSUE TITLE
Move godot aar library to gradle

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#5670]
### Describe the project you are working on

android both 2d and 3d

### Describe the problem or limitation you are having in your project

the limitation is if we trying to upgrade our previous android library we can't check either our godot arr library needs an update.. Besides it is complicated to import a aar library then  gradle implementation..

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

it will saves the developer time and hassle 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

no idea

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no idea

### Is there a reason why this should be core and not an add-on in the asset library?

as its already library it just needs to port into gradle

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
@hani09876 Well good news, it's already available as a gradle dependency! 

This was added in https://github.com/godotengine/godot/pull/59146 and here's the [maven repo](https://repo1.maven.org/maven2/io/github/m4gr3d/godot/).
For the latest version, that should be:
```
dependencies {
    ...
    implementation 'io.github.m4gr3d:godot:3.5.1.stable'
    ...
}
```

The process still needs to be automated so that each stable release gets automatically uploaded to mavencentral.

**Comment by hani09876** [comment]
> @hani09876 Well good news, it's already available as a gradle dependency! 
> 
> This was added in https://github.com/godotengine/godot/pull/59146 and here's the [maven repo](https://repo1.maven.org/maven2/io/github/m4gr3d/godot/).
> For the latest version, that should be:
> ```
> dependencies {
>     ...
>     implementation 'io.github.m4gr3d:godot:3.5.1.stable'
>     ...
> }
> ```
> 
> The process still needs to be automated so that each stable release gets automatically uploaded to mavencentral.

Does it available for godot 4?

**Comment by Calinou** [comment]
> Does it available for godot 4?

Yes, but it's not pushed to Maven Central yet either.

**Comment by m4gr3d** [comment]
@hani09876 Now that Godot 4 stable has been released, the Godot Android library has also been made available on mavencentral

https://repo1.maven.org/maven2/org/godotengine/godot/4.0.0.stable/
