### ISSUE TITLE
Make Godot support "ProMotion" (High Refresh Rate) on iOS

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot-proposals#5676]
### Describe the project you are working on

A mobile game with simple graphics where added frames are both feasible and could improve player experience.

### Describe the problem or limitation you are having in your project

Godot does not support refresh rates over 60fps on iOS, even if the device supports it. This is confirmed for the iPhone 13 and 14 Pro families, but not iPads as I do not currently own one. The methods for how to enable this feature differ between iPad and iPhone ([src](https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro#Enable_faster_ProMotion_refresh_rates)), but due to how the Godot iOS render code's comment on FPS is written, I presume it affects both.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would allow iOS, and possibly iPadOS, games to run at frame rates above 60fps.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

platform/ios/godot_view.cpp line 210 appears to control this, although there may be further things which affect it. As per Apple docs, key `CADisableMinimumFrameDurationOnPhone` needs to be set to `true` as well for iPhones.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be done via an add-on, it requires recompiling export templates.

**Comment by Calinou** [comment]
For reference, high refresh rate support on Android is automatic, but the app needs to be modified on iOS.
