### ISSUE TITLE
Sync editor theme with system settings

### ISSUE THREAD

**Issue by tvardero** [godotengine/godot-proposals#5678]
### Describe the project you are working on

not related

### Describe the problem or limitation you are having in your project

not related

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It is a QoL feature.

Ability to sync Godot editor theme with current system settings. Light/dark sync is enough for me. But if you wish, you can also implement high/low contrast themes, like in VS Code (screenshots below).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example of VS Code:
![image](https://user-images.githubusercontent.com/45442278/198874609-83a8ba38-0a16-4ce3-b4c4-493a99237476.png)
![image](https://user-images.githubusercontent.com/45442278/198874648-fa12a291-82bc-4af1-9486-e0e45d2feb5f.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Frequency: It is used on system theme change.
Scriptable: yes.

### Is there a reason why this should be core and not an add-on in the asset library?

It could be an asset, if asset is allowed to modify Editor settings GUI.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/5312.

**Comment by raulsntos** [comment]
Support for detecting the system dark mode preference was implemented for Windows and macOS in https://github.com/godotengine/godot/pull/65026 and for Linux in https://github.com/godotengine/godot/pull/65115, but the editor currently doesn't use the API.

This is how the new API can be used:

```c++
if (DisplayServer::get_singleton()->is_dark_mode_supported()) {
    if (DisplayServer::get_singleton()->is_dark_mode()) {
        // Dark theme.
    } else {
        // Light theme or no preference.
    }
} else {
    // Platform does not support or hasn't implemented dark mode detection.
}
```

 **bruvzg** includes a sample of how something similar can be achieved as an auto theme in https://github.com/godotengine/godot/pull/65026.

---

This API is also available in scripting so it can be used to create an EditorPlugin that sets the editor theme like this:

```gdscript
var settings = get_editor_interface().get_editor_settings()

if DisplayServer.is_dark_mode_supported():
    if DisplayServer.is_dark_mode():
        # Dark theme.
        settings.set_setting("interface/theme/preset", settings.get_setting("interface/theme/dark_preset"))
    else:
        # Light theme or no preference.
        settings.set_setting("interface/theme/preset", settings.get_setting("interface/theme/light_preset"))
else:
    # Platform does not support or hasn't implemented dark mode detection.
```

_The EditorPlugin implementation should also define the `interface/theme/dark_preset` and `interface/theme/light_preset` settings and listen for changes to editor settings (see `NOTIFICATION_EDITOR_SETTINGS_CHANGED`)._

**Comment by Calinou** [comment]
> Support for detecting the system dark mode preference was implemented for Windows and macOS in https://github.com/godotengine/godot/pull/65026 and for Linux in https://github.com/godotengine/godot/pull/65115, but the editor currently doesn't use the API.

I remember why it's not used now: we don't want to have the editor default to a light theme, as most operating systems use a light theme preference by default (or at least signal "no preference", such as web browsers). People would riot if that occurred :slightly_smiling_face:

**Comment by tkgalk** [comment]
`"gsettings get org.gnome.desktop.interface color-scheme"` checking this in GTK helped me with my other projects. Not sure how other desktop environments do it.

**Comment by tkgalk** [comment]
>  Some people may riot if they start up Godot and find out it uses a light theme 🙂
Then don't have it as a default, but still allow us to use that option. VSCode by default uses Dark Mode, but you can go into settings and set a preferred Light mode and Dark mode.

**Comment by Calinou** [comment]
> Then don't have it as a default, but still allow us to use that option.

I agree it makes sense to provide this as an option, but this depends on https://github.com/godotengine/godot-proposals/issues/2938 to be usable with the non-default editor syntax highlighting theme.

**Comment by tkgalk** [comment]
This actually goes for both the Godot editor and script editor themes.

**Comment by sosasees** [comment]
> Windows, macOS, Android and iOS have an API for getting the current system theme, but Linux seems to be more messy on this aspect. It should be possible to implement this on Linux as well, but it may require dbus/GTK trickery.

this trickery should be no longer needed once the
Freedesktop dark style preference specification
is finalised, but i have no idea when that will happen

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/86610.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/godotengine/godot-proposals/issues/5678#issuecomment-1959722381

@akien-mga, per https://github.com/godotengine/godot/pull/86610#issue-2060231672, that appears to merely synchronize the accent colour, rather than adhere to the DE's theme. The example screenshots demonstrate different background colouration between Godot and Windows Settings.
