### ISSUE TITLE
Godot Location Manager For Mobile Devices

### ISSUE THREAD

**Issue by cagdasc** [godotengine/godot-proposals#57]
**Describe the project you are working on:**
Location manager for Android and iPhone

**Describe how this feature / enhancement will help your project:**
I am working on location manager for Godot. I have already implement [Android location best practice](https://developer.android.com/training/location). With this feature developer can use user locations data and make creative games like Pokemon.

**Is there a reason why this should be core and not an add-on in the asset library?:**
You can check-out [my branch ](https://github.com/cagdasc/godot/tree/3.1-location-manager) and see how it's implemented. But I am confused about it should be a module or implemented in core. It's available only mobile devices and I need to make it singleton. Maybe you can evaluate module or core options. I have not enough info about assets so I do not decide it can be asset library. My main stopper condition make choice it will be module or core functionality

**Describe implementation detail for your proposal (in code), if possible:**
I have add basic implementation but it will change with iOS implementation.

```
extends Node2D

func _ready():
	var singleton = Engine.get_singleton("LocationManager")
	if singleton:
		print(singleton)
		singleton.connect("last_known_location_update", self, "locations")
		# 6 * 1000 - interval
		# 10 * 1000 - max wait time
		# 100 - priority for android, it will be enum value
		singleton.start_periodic_location_update(6 * 1000, 10 * 1000, 100)

func locations(long, lat):
	print("Longitude: ", long, " Latitude: ", lat)
```
Thank you.

**Comment by lentsius-bark** [comment]
I've worked on several projects (and others I haven't because of this issue) where I thought having user location on android devices would have rocked.

**Comment by cagdasc** [comment]
@lentsius-bark you can review pr and try it with [godot-samples](https://github.com/cagdasc/godot-samples)

Thank you.

**Comment by m4gr3d** [comment]
@cagdasc As discussed in the original PR, this can (and should) be provided as a plugin for each platform.

**Comment by cagdasc** [comment]
@m4gr3d I have create a [location plugin](https://github.com/cagdasc/godot-location-plugin) and write detailed [plugin tutorial](https://medium.com/@cagdascaglak/godot-location-plugin-2afec88dbb72) maybe you can promote it. Thank you.

**Comment by m4gr3d** [comment]
cc @akien-mga 

@cagdasc Nice job! Especially your plugin tutorial should be useful to anyone trying to write a plugin for the v1 plugin system! 
@akien-mga Can we link to external docs/tutorials from the Godot docs or should @cagdasc adapt the tutorial for Godot docs?

@cagdasc In your plugin, you can leverage [Android manifest merging rules for `<permission>` tag](https://developer.android.com/studio/build/manifest-merge) and add the desired permissions in the plugin manifest file. This will cause them to be directly added to the app manifest at build time instead of requiring the user to do it.

**Comment by cagdasc** [comment]
@m4gr3d thank you for promotion. I will fix permission issue.
