### ISSUE TITLE
Allow generating UV2 on GridMap meshes when converting to MeshLibrary

### ISSUE THREAD

**Issue by Lasuch69** [godotengine/godot-proposals#5701]
### Describe the project you are working on

Nothing.

### Describe the problem or limitation you are having in your project

when testing an idea i saw that you cannot bake lightmaps on a gridmap which is a huge deal with this type of nodes as in 90% of cases uses gridmap as a static foundation for maps

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

add a support for baking lightmaps in grid map node 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

baking would be exactly the same as with any mesh instance

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

this is core feature

**Comment by Calinou** [comment]
This should work already, but only if the meshes in the MeshLibrary have an UV2. The issue is that OBJ meshes cannot store an UV2, so you need to set it manually with a script.

**Comment by Lasuch69** [comment]
Doesn't work :(

**Comment by Calinou** [comment]
In 4.0, it should be feasible to use the Advanced Import Settings dialog to save specific meshes to `.mesh` resources, then use them in a MeshLibrary. However, LightmapGI will currently ignore GridMaps: https://github.com/godotengine/godot/issues/56030
