### ISSUE TITLE
Change the "position" parameter in CollisionObject3D::input_event signal to avoid shadowing Node3D::position

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-proposals#5715]
### Describe the project you are working on

Under NDA ( Task in question involves ray pickable 3d objects)

### Describe the problem or limitation you are having in your project

Godot 4 changed Spatial into Node3D and added `position` as a property.
Additionally CollisionObject3D has an `input_event` signal which also uses `position` as a parameter. This means every time you connect `input_event` to any 3D node, if you use the editor-generated callback you are guaranteed to be shadowing that node's `position` property.

This of course can happen with any signal and the solution is as simple as renaming the parameter in the callback or doing nothing if you don't need to access the property. 

In this case however, the shadowing is guaranteed to happen every single time you connect that signal to any 3D node
![image](https://user-images.githubusercontent.com/526829/199594063-491ea792-d6ea-4051-8fdd-f7e6b4bae3ac.png)
This is a really minor usability annoyance for (well rested) experience users, but it might mean hours of debugging for newbie users based on similar experiences posted in r/godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In the signal parameters, change `position` into `hit_position` and, for consistency `normal` into `hit_normal`.
Could also be `event_position` or anything we agree on as long as it doesn't collide. 
This is not API breaking since it just affect the default parameter names for editor-generated callbacks.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I understand chaning `PropertyInfo(Variant::VECTOR3, "position")` into `PropertyInfo(Variant::VECTOR3, "hit_position")` should be enough, but I'm not entirely sure

https://github.com/godotengine/godot/blob/754552b34d3523a76656940145bd37328536292d/scene/3d/collision_object_3d.cpp#L475

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes it can be worked around, it just impacts usability, especially for new users.

### Is there a reason why this should be core and not an add-on in the asset library?

Can't be done in any other way.

**Comment by golddotasksquestions** [comment]
I'm in favour of `event_position`. 
`hit_position` sounds like it has something to do with hit boxes or hurt boxes or some kind of impact.

**Comment by noidexe** [comment]
Well it's a 3D position obtain via raycast hit against a collider, but I think `event_position` might be better since you don't care about the internals of how it was obtained.
