### ISSUE TITLE
Add "fish bones" visualization to the Path3D in the Editor

### ISSUE THREAD

**Issue by xiongyaohua** [godotengine/godot-proposals#5716]
### Describe the project you are working on

Some urban traffic game, which model roads with `Path3D`

### Describe the problem or limitation you are having in your project
![image](https://user-images.githubusercontent.com/6020486/199636655-e3cc02ef-a243-4f64-9d85-963c50abd840.png)

Currently Godot Editor visualize the Path3D as bare curves, and it is difficult to tell the direction and tilt of this path.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

![image](https://user-images.githubusercontent.com/6020486/199632868-4ca525b5-2b9c-4923-931c-bdcd47bd4469.png)
Following the established convention of Blender, visualize the path with "fish bones".

And suggest by https://github.com/godotengine/godot-proposals/issues/5729, we can make the fish bones one sided, or two sides with different colors, to distinguish "left" from "right".

I got an initial implementation. Currently I use long and short bones to distinguish "up" from "down". Adjusting curve tilt becomes much easier.

I am not sure what is the best way to visualize. Open to suggestions.

![image](https://user-images.githubusercontent.com/6020486/201499263-b256a6d2-3611-464d-8557-6faafacff5b6.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change the  `Path3D::redraw()` method, draw the additional "bones".

We need to sample the rotation frames along `Path3D` to get the direction of "bones". Since `Path3D` is just a thin wrapper of `Curve3D`, the rotation sampling logic need to be add on the `Curve3D`  first. see [this PR](https://github.com/godotengine/godot/pull/64212)

~~I will make an PR once https://github.com/godotengine/godot/pull/64212 merged, as managing PR based on another unmerged PR could be a headache.~~
PR is submitted. https://github.com/godotengine/godot/pull/68860

### If this enhancement will not be used often, can it be worked around with a few lines of script?

For performance reason, script is not a good choice.

### Is there a reason why this should be core and not an add-on in the asset library?

It is part of the core plugins

**Comment by xiongyaohua** [comment]
By the way, based on the code it seems there was an effort to implement "fish bone" before, but commented out 7 years ago due to some bug. What was the bug and is it solved? Could the original authors give me some direction on this? @tagcup @reduz 

https://github.com/godotengine/godot/blob/889868cbbc8beac74d5f49f9b7ef41efc4ae7d5a/editor/plugins/path_3d_editor_plugin.cpp#L252-L258

**Comment by Calinou** [comment]
Would it make sense to implement those for 2D as well? (This can be tracked in a separate proposal.)

**Comment by xiongyaohua** [comment]
> Would it make sense to implement fish bones for 2D as well? 

sure. will do.
