### ISSUE TITLE
Make `String.split("")` split a string by characters

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#5719]
### Describe the project you are working on

A game

### Describe the problem or limitation you are having in your project

I have a string "absde" and I want to get ["a", "b", "c", "d", "e"]
Now I only can use `for` loop or `while`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Making `String.split("")` split a string by characters would solve the problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`absde.split("")` --> ["a", "b", "c", "d", "e"]

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Using for/while

### Is there a reason why this should be core and not an add-on in the asset library?

can't be done as an addon

**Comment by dalexeev** [comment]
`for chr in string` iterates over characters:

```gdscript
for chr in "abcde":
    print(chr) # a, b, c, d, e
```

Now `split("")` returns a one-element array from the original string:

```gdscript
print("abcde".split("")) # ["abcde"]
```

In some other languages (JavaScript) it works as described in this proposal:

![](https://user-images.githubusercontent.com/47700418/199966507-8f4b4c12-395b-4504-a1cf-1e2cf39e4ac8.png)

or throws an error (Python):

![](https://user-images.githubusercontent.com/47700418/199967812-e88d5430-d203-4d4a-b212-60901f81bb6d.png)

**Comment by zinnschlag** [comment]
Another use-case for #2972 ?

`[c for c in "abcde"]`
