### ISSUE TITLE
Make debug --debug-server enabled by default and change command line flag to --disable-debug-server

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot-proposals#5720]
### Describe the project you are working on

I am working on The Mirror game.

### Describe the problem or limitation you are having in your project

I wanted to test my exported game so I ran the exported game like this:
```shell
./TheMirror.exe --remote-debug tcp://127.0.0.1:8006
``` 

This is documented in our documentation but it doesn't document that you **need to** use --debug-server if you are launching the exported game.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I believe we should just enable the debug server all the time, I can't see a reason to add an extra step to the editor launch.

So the user only has to use on their launched client.
```shell
./TheMirror.exe --remote-debug tcp://127.0.0.1:8006
```

We should expand the documentation additionally to explain "How to debug your exported games"

I don't see a reason we should have the debug server off by default so I think better to make the default here, the correct one for this use case. If there is another use case I do not see please let me know.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. Swap ```---debug-server``` to ```--disable-debug-server```
2. Modify the debug server to start if this command is not supplied

### If this enhancement will not be used often, can it be worked around with a few lines of script?

yes, its just a UX improvement

### Is there a reason why this should be core and not an add-on in the asset library?

yeah its just a more sensible default for me

**Comment by Calinou** [comment]
> I believe we should just enable the debug server all the time, I can't see a reason to add an extra step to the editor launch.

If multiple game instances are started on the same time, automatic port assignment would have to kick in. This needs to print a message to stdout when starting the project.

**Comment by RevoluPowered** [comment]
Doing some housekeeping of my own proposals, feel free to ask if you want it re-opened.

A workaround I found to this was simply making sure to launch my app with the debug URL, if I am doing something in the future again where I need this I will re-open it.
