### ISSUE TITLE
Improve usability of polygon and path editors

### ISSUE THREAD

**Issue by ettiSurreal** [godotengine/godot-proposals#5729]
### Describe the project you are working on

Still mostly testing different features.

### Describe the problem or limitation you are having in your project

Transforming the custom gizmos of 2D and 3D nodes such as Path, Line, Polygon, CSG nodes, etc is often times very cumbersome and barebones, and slow to work with.
Some of the improvements i'm suggesting have likely already been proposed, but i might as well have my own take at the functionality.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

**All applicable nodes**

**Multi Selection Support**
Clicking on points while holding a key such as shift allows you to select multiple of them, allowing you to transform them at once. Also works with box selection.
The last clicked point is set as "active", clicking again on an active point deselects it.

**Move/Rotate/Scale mode support with pivot point**
Support for transforming the points using Move/Rotate/Scale modes, based on a pivot point.
As the points don't have a "scale" property, it would just move them apart.
The pivot system was originally going to be a part of this proposal, but i decided to make it it's own thing, see https://github.com/godotengine/godot-proposals/issues/5727

**Path, Polygon and Line drawing parity.**
Currently Path, Polygon and Line have a lot of inconsistencies.

- Path's Select Mode has the ability to transform, add, erase and edit handles.
- Polygon's Select Mode has the ability to transform and erase points, but not add new ones (apart from in between existing ones), and the Add Mode always resets the polygon after it's already been closed.
- Line's Select mode transform and remove points, but the Add Mode can do both of those as well as add new points when clicking on empty space.

I am proposing a unified way of editing them based on Paths (both in 2D and 3D).

- LMB without holding down any other keys is for editing existing points
- RMB is for removing points.
- Ctrl+LMB is for creating new points, connected to the one last in the array.
- Shift+LMB is for editing curve handles in Paths
- Alt+LMB is for adjusting tilt where applicable.

Individual Add, Erase and such modes would be removed, as they wouldn't be needed anymore.

**3D Node Specific**

**Top bar icon parity**
Currently, some of the 3D nodes use different icons from the 2D nodes at the top bar.
![image](https://user-images.githubusercontent.com/98223724/200134585-b0c351d3-515e-4ae6-81ab-e1fcb2fff3c4.png)
![image](https://user-images.githubusercontent.com/98223724/200134597-b312bf24-5f61-4c03-82ce-054882ddbd3a.png)
Example with Polygon2D and 3D.

**Adding new points in between existing points**
Missing functionality available in the 2D nodes, and it's very annoying having to redo them or mess with the array.

**Snap to grid upon adding new points.**
Also missing 2D functionality.

**Path Node specific**

**Open path after closing it**
Pressing "close curve" when it's already closed, removes the last point, opening it again.
Though i would like to point out placing a new point at the end of the path does seem like a bit of a hacky solution, wouldn't it be better to have a "cyclic" toggle for Curve2D/3D that connects the first point with the last? Let me know if there is a reason for it being this way.

**Quickly adjusting the handles (control points) right after adding them**
Adding new points while holding a key immediately lets you set the handle size, example using Blender's curve pen.

https://user-images.githubusercontent.com/98223724/200135396-6a6535bd-1fec-4233-b6e6-f7589b806db8.mp4

**Snap support for handles**
Self explanatory.

**Allow closing paths by clicking on the starting point**
Similar to how Polygon2D/3D currently works.

**Zoom dependent Path2D scale**
Line remains the same thickness no matter of the zoom level, essentially the same behavior as Path3D.

**Visualize Path3D tilt**
Recently suggested in #5716, but i would like to suggest it being on either only one side, or having one be a different color, to be able to tell which way is positive and negative.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- You can now select multiple control points at once, and transform them with Move/Rotate/Scale mode.
- Drawing paths/polygons/lines now works the same way, and the individual tools for Adding/Removing/Editing handles are removed in favor of the main Select Tool doing it all of it using key modifiers.
- You can now new points in between existing ones in 3D paths and polygons.
- Paths can be "opened" after pressing the close path button after closing them.
- Path2D is now displayed like Path3D
- Paths can now be closed by pressing on the first point, similar to Polygons.
- Path3D tilt is visualized, with a way to tell which way is positive and negative.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think it can, and it will most likely be used often.

### Is there a reason why this should be core and not an add-on in the asset library?

Major out of the box usability improvements.

**Comment by Calinou** [comment]
> Alt+LMB is for adjusting tilt where applicable.

<kbd>Alt + LMB</kbd> is not usable by default on Linux due to window managers intercepting the shortcut. We need to find another default shortcut, or have an alternative shortcut that can be used.

**Comment by speakk** [comment]
This would be a fantastic addition to the usability of the node based edit tools

**Comment by Calinou** [comment]
@speakk Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by ettiSurreal** [comment]
I will split this proposal into individual ones, as i feel like having many, mostly unrelated suggestions is probably confusing and hard to read.
