### ISSUE TITLE
Make it easier to save all glTF meshes to external files

### ISSUE THREAD

**Issue by gelvinp** [godotengine/godot-proposals#5730]
### Describe the project you are working on

I'm working on a 3D game that takes place in an underground tomb. As such, I have several gltf files, each with many meshes. I create a new inherited scene from these gltf files, which I then add colliders and scripts to. Without saving the meshes externally, these tscn files are hundreds of megabytes (one of mine, with three empty rooms, is 383 MB). This has the added effect of taking several minutes for Godot to open my project. If I go to these scenes and check the "Save to file" option for each mesh, these scenes go back down to a few dozen KB, and Godot becomes more responsive.

### Describe the problem or limitation you are having in your project

Currently, to save these meshes externally, I have to go one by one and manually set the "Save to File" option, and manually set the path and filename. When I have 20-30 meshes in each of my scenes, this becomes a non-insignificant chore.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like for a scene-wide "Save meshes externally" option, where I could give it a folder, and all the meshes inside would be saved in that folder, with the name of the mesh as the filename.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Ideally, this "Save To File" menu as seen when selecting a mesh could be reused (with the exception of having the path select a folder, instead of a file).

Here's a quick paint.net mockup:
![image](https://user-images.githubusercontent.com/61520531/200149170-d6a09969-5c33-46f1-8ebb-57bc0c851eb6.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I suspect this might be able to be worked around with an import script, though I'm not certain how I would navigate a node tree, save all the meshes into a user-specified folder (I don't think you can pass parameters into these import scripts, potentially an avenue for another proposal?), and then set these meshes to use the external resources instead.

### Is there a reason why this should be core and not an add-on in the asset library?

Opening a scene in the editor with external meshes is basically instant. while opening the same scene with internal meshes takes around 10 seconds on my machine. An improvement to editor performance of this scale should not be left to an asset downloaded separately.

**Comment by Calinou** [comment]
Resource importing requires a 1:1 mapping between input and output. If you save each mesh to a file, there is no longer a 1:1 mapping between input and output.

**Comment by gelvinp** [comment]
I'll definitely look into binary `.scn` files, as the actual project exports with external mesh resources are larger (750 mb -> 1.15 gb), but git is definitely more annoying with binary files. As workaround it looks like I can inherit the gLTF files as a .scn, and then have a second scene instance that first scene for the level geometry, and then add the lights/scripts/etc... on top. I'd love to not need intermediary scenes but it sounds like that's a consequence of larger structural choices. Either way it's easier than manually setting "Save to file" for every mesh during import.

> I get a feeling inherited scenes shouldn't cause mesh/texture data to be duplicated from the glTF files.

I'd like to think this would be true, but when the only change I made was saving meshes externally my scenes went from this:
![image](https://user-images.githubusercontent.com/61520531/200149771-ca2d8483-058c-4f93-ad93-8f8a42a5b4db.png)
to this
![image](https://user-images.githubusercontent.com/61520531/200149779-46e7b1c3-2d92-4b79-a5d1-f6815ae8ce4d.png)

Additionally there were definitely performance implications in editor
Here's opening a scene without external mesh resources:
https://user-images.githubusercontent.com/61520531/200149806-410d165a-3d6c-4ad5-a5c5-796828790cc6.mp4
and here's with external mesh resources:
https://user-images.githubusercontent.com/61520531/200149810-43867310-8806-4e98-a771-41f09a249012.mp4

**Comment by gelvinp** [comment]
I've done some more testing, and exporting from blender as `.glb` instead of `.gltf` has the expected behavior. Making a new inherited scene is only 232 bytes and loads quickly. Not sure if this is the intended behavior, where `.gltf` inherited scenes copy all the mesh data, and `.glb` inherited scenes do not, but I'll just re-export all my level geometry as `.glb` files, call this an alpha quirk, and move on.
