### ISSUE TITLE
Remove hardcoded Camera3D size limitations

### ISSUE THREAD

**Issue by iiMidknightii** [godotengine/godot-proposals#5736]
### Describe the project you are working on

A simcity 4-esque orthographic city builder with very large regions.

### Describe the problem or limitation you are having in your project

I want the regions to be rather large, on the order of 16x16 or 32x32 km wide, but the Camera3D node has a check in set_size() that bounds the size between 0.001 and 16384.  In order to view regions as large as I'm working with, I need to increase the camera size beyond that limit.  Additionally, attempting to set the size above 16384 quietly fails, with no warnings printed in the editor and no documentation mentioning the limit.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose the first line of set_size() to change the conditional check to only ensure the size is > 0.  All positive values of size are valid for an orthographic camera.  If someone were working on orthographic games with very small or very large scales, this enhancement will allow for orthographic cameras to suit those needs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simply change the line `ERR_FAIL_COND(p_size < 0.001 || p_size > 16384);` to `ERR_FAIL_COND(p_size <= 0.0);`, and possibly change the documentation to mention this limitation.  I have recompiled the engine with this change and worked with it for 2 weeks without any issues.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know of any way to work around this as it seems to be hard-coded into the core implementation of Camera3D.

### Is there a reason why this should be core and not an add-on in the asset library?

Camera3D is core.

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face: 

Make sure to also change the property hint for the `size`, so that the value can be set to anything in the inspector. You can add `or_greater` at the end of the property hint as follows: `min,max,step,or_greater`

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/72000.
