### ISSUE TITLE
Impove Tileset UX/UI

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#574]
**Describe the project you are working on:**
2D games with Tilesets.

**Describe the problem or limitation you are having in your project:**
Navigating Tileset is an exercise in pain resilience.
Imagine a user want to rename a Tile, this is what they have to go through:
![trying_to_rename_tile](https://user-images.githubusercontent.com/47016402/76342430-e0be3b00-62fe-11ea-8dbf-f68e0dba2c3a.gif)

That is, if they even manage to figure out all the necessary things to click ... because why you would have to click them, nor their order, is in any way obvious, intuitive, or reasonable.
It's a similar story when you try to do something as simple as deleting a tile or when you try to get to a specific Tile to edit it's parameters.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Bring basic Tile options to the Tilemap panel:
**Right click** on the Tile to bring up a context menu to edit, rename or delete the tile.
**Double click** the Tile to edit the Tile (brings up the Tileset bottom panel and Inspector info with all the selected tile info):
![tilemap_doubleclick_to_edit](https://user-images.githubusercontent.com/47016402/76351712-3817d780-630e-11ea-97e5-8fbe2945f313.png)

When there is no Tileset loaded or created yet, provide buttons similarly to the Scene Panel on an empty scene, that when clicked, create a Tileset for the user, brings up the bottom panel, and prompts the user to select a texture:
![tilemap2](https://user-images.githubusercontent.com/47016402/76348968-6e068d00-6309-11ea-8622-94a47dfb0c71.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See mockups above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think it's a desperately needed UI/UX improvement, that would be used often by anyone working with Tilesets (so a lot).

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it's a desperately needed UI/UX improvement, that would be used often by anyone working with Tilesets (so a lot).

**Comment by Castlemark** [comment]
I like a lot your mockups! But I think we should do the same improvements for gridmap/meshlibrary to keep consistency.

**Comment by golddotasksquestions** [comment]
@Castlemark Thanks, so far I have never useds gridmaps, so I can't say anything about them.

**Comment by samgreen** [comment]
It has always seemed strange to me that there is a list of tiles that is separate from the editor. I think this will simplify the workflow for everyone, and as it doesn't remove existing workflows it's pretty hard to argue against this change.

**Comment by Poobslag** [comment]
I had resorted to editing the .tscn files in a text editor when I needed to rename or delete tilemaps, I was not even aware it could be done through the editor. Making this more apparent would be beneficial.

**Comment by KoBeWi** [comment]
The new tileset editor improves UX a lot. Not exactly in the way proposed here, but it's better. You can give it a try in a nightly build.

**Comment by golddotasksquestions** [comment]
@KoBeWi I would like to, unfortunately I can't. When I start Godot 4 it immediately crashes to a white screen. [See issue here](https://github.com/godotengine/godot/issues/49656#).
