### ISSUE TITLE
Expose an optional explicit path to an external mono editor within editor settings, or add a "silent" option to the external editor field.

### ISSUE THREAD

**Issue by ax95** [godotengine/godot-proposals#5760]
### Describe the project you are working on

I'm working on a Godot project using a portable development environment inside of a USB, for ease of transport and for fun. It contains installations of Godot 3.5.1, Visual Studio Code, and Git, all in portable mode. I launch my project using a custom-made batchfile. I have another copy of Visual Studio Code on my personal machine that is more "global" i.e. probably registered under %path% on windows, which has a different and more generic purpose than my local portable copy of Visual Studio Code.

### Describe the problem or limitation you are having in your project

Whenever the Godot editor settings has the option "External Editor" under Mono set to _Visual Studio Code_, and I create or load a C# script onto a node, it does not launch the local version of my editor installed on my USB (as there is no way to specify Godot to look for it), but instead my "global" version installed on my C:\ drive. Whenever I add or create a script, I must close down this secondary instance of Visual Studio Code, which is not ideal and hampers both iteration time and user experience.

Likewise, if I set the mono editor setting to _Disabled_, it does not open an external editor, but it still opens the script internally within the Godot editor. I must then tab over to the Script view to close the opened C# file, lest I deal with "This script was externally changed" prompt dialogue boxes whenever I tab back into Godot from Visual Studio Code, alongside "cyclical reference" errors inside of the terminal.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose a text field under Editor Settings > Mono with the name "External Editor Path". Ideally, this field should be able to interchangeably handle absolute and relative paths. See also my proposal for an _Arbitrary_ option and an additional "External Editor Command" field to make Godot be able to be External Editor agnostic.

Alternatively/additionally, add a _Silent_ option to the existing "External Editor" dropdown field, which acts much like _Disabled_ except it also does not trigger an automatic load of the script file into Godot's internal Script editor.

### External Editor Path
Whenever a script is detected by the editor as having been created or loaded, it will normally check the "External Editor" settings under Editor Settings > Mono. Before using and launching the executable associated with this field, check instead first the "External Editor Path" setting on the same page, unless the "External Editor" field has the _Disabled_ option. If "External Editor Path" is empty, proceed as normal, otherwise attempt to launch the executable while passing along the script file, as the editor already does using existing "External Editor" behavior. 

Use the "External Editor" field to determine the external editor's command parameter terminology. I.e., if "External Editor" is set to Visual Studio Code, and "External Editor Path" points to a legitimate Visual Studio Code executable, launch it while passing along the Visual Studio Code parameter for loading a file on launch, ensuring correct parameter terminology when executing.

If the executable cannot be found on the given path firstly interpreted as an absolute path, and then secondly relative to the Godot executable, throw an error ("_Manually specified external editor cannot be found!_") and then attempt to launch the defined External Editor using existing behavior.

**Optionally**, also add a "External Editor Command" field under Editor Settings > Mono, and a _Arbitrary_ option for the "External Editor" field. Whenever _Arbitrary_ is chosen as an external editor, Godot will attempt to launch the executable defined in the "External Editor Path" while passing in the parameter specified within "External Editor Command" (for example "--load"), followed by the absolute path to the specified script file. This would allow Godot to be External Editor agnostic.

### Silent Option
If "External Editor" has the _Silent_ option enabled, it acts just like the _Disabled_ option, except you also neglect or interrupt the loading of the script file inside the internal Godot script editor as well. In other words: whenever the _Silent_ option is active and a script is created or loaded, do nothing.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The simplest workaround is to just choose an external editor that isn't installed on the user's machine, such as JetBrains Rider in my case. This is however not ideal, given that this will constantly spew errors and clutter up the terminal, and this workaround also requires a user to be mindful and restrictive of applications installed outside the scope of Godot.

### Is there a reason why this should be core and not an add-on in the asset library?

I am uncertain whether this is even possible in regards to my proposal.

**Comment by raulsntos** [comment]
Related: https://github.com/godotengine/godot/issues/66904

**Comment by raulsntos** [comment]
- Implemented by https://github.com/godotengine/godot/pull/74517

![image](https://github.com/godotengine/godot/assets/3903059/ba0e74d9-62e6-40cf-bca1-5a0fc6e2aca4)
