### ISSUE TITLE
Make hint_range accept shader preprocessor macros

### ISSUE THREAD

**Issue by RabbitB** [godotengine/godot-proposals#5777]
### Describe the project you are working on

A 2D space-mining game with nbody gravity simulation applied to all objects w/ mass.

### Describe the problem or limitation you are having in your project

Some shaders, such as the shader that produces the star-field backdrop, have a number of parameters that allow for rapid adjustment of the output image. The way these parameters are used, often requires knowledge of the range of values allowed. In example, the star-field shader has a parameter `star_density` that directly controls how densely packed the generated stars will be. This has a range of `0.0 to 10.0` (any value over `10.0` produces output that is too noisy to be usable), so this value must be set in both `hint_range` and within the shader itself.

```glsl
uniform float star_density : hint_range(0.0, 10.0, 0.001);

vec3 nrand3(vec2 co)
{
	vec3 a = fract(cos(co.x * 8.3e-3 + co.y) * vec3(1.3e5, 4.7e5, 2.9e5));
	vec3 b = fract(sin(co.x * 0.3e-3 + co.y) * vec3(8.1e5, 1.0e5, 0.1e5));
	return mix(a, b, star_density / 10.0);
}
```

This creates a code-debt within the shader, so that if the shader ever changes in a way that affects the allowed range of such a parameter, all instances of those range limits must be modified by hand.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The described limitation is a perfect use-case for preprocessor macros. A macro can be defined and then substituted in both hint_range and throughout the shader. If ever the shader is modified in a way that requires the allowed range to change, only the macro must be updated.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```glsl
// Change me to update the entire shader.
#define MAX_STAR_DENSITY 10.0

uniform float star_density : hint_range(0.0, MAX_STAR_DENSITY, 0.001);

vec3 nrand3(vec2 co)
{
	vec3 a = fract(cos(co.x * 8.3e-3 + co.y) * vec3(1.3e5, 4.7e5, 2.9e5));
	vec3 b = fract(sin(co.x * 0.3e-3 + co.y) * vec3(8.1e5, 1.0e5, 0.1e5));
	return mix(a, b, star_density / MAX_STAR_DENSITY);
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

`hint_range` cannot take a constant or any other variable. Currently it can only be hard-coded, so there is no work-around solution.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a change in how the shading language functions, particularly its preprocessing step. It cannot realistically be done outside of core.

**Comment by bitsawer** [comment]
Are you sure that example doesn't work? I just tried your lower code snippet and it seems to work just fine, changing the MAX_STAR_DENSITY value updates the inspector slider max value correctly too.

**Comment by RabbitB** [comment]
> Are you sure that example doesn't work?
Just tested it again in the Beta 17 release and confirming it still doesn't work. Using either a define statement or a constant causes a syntax error when using it in the hint.

**Comment by bitsawer** [comment]
What error does it give you? Did you remeber to add `shader_type spatial;` at the beginning? I just tested and this code works in the lastest beta, including the inspector for setting the density:

``` cpp
shader_type spatial;

// Change me to update the entire shader.
#define MAX_STAR_DENSITY 10.0

uniform float star_density : hint_range(0.0, MAX_STAR_DENSITY, 0.001);

vec3 nrand3(vec2 co)
{
	vec3 a = fract(cos(co.x * 8.3e-3 + co.y) * vec3(1.3e5, 4.7e5, 2.9e5));
	vec3 b = fract(sin(co.x * 0.3e-3 + co.y) * vec3(8.1e5, 1.0e5, 0.1e5));
	return mix(a, b, star_density / MAX_STAR_DENSITY);
}

void fragment() {
	ALBEDO = nrand3(UV);
}
```
![cap](https://user-images.githubusercontent.com/22456603/216907455-5b20d343-cd23-451a-be4b-fa29a8e5a76c.png)

**Comment by RabbitB** [comment]
Physically retyping it I spotted the error. I'm including the semi-colon and as a define, it's unrolling the entire line into the expression. Constants still don't work, but that's a separate discussion of whether constants _should_ work or not. I'll give some time if anyone would like to make an argument for or against that, but otherwise I'll close this issue
