### ISSUE TITLE
Add font that support every language and make label able to show emoji

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#5779]
### Describe the project you are working on

3d and 2d

### Describe the problem or limitation you are having in your project

The limitation is currently Godot label doesn't support emoji. (I am trying to use gboard emoji). And there is no font that supports every language..

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In Android studio, text input support every language and emoji. So if the feature can't be implemented in godot i think developer can adopt the textinput from Android studio.. 

I am using godot 4 beta 4. And i know that developer worked hard and gives us a better label in this version. But it would be more helpful if the label support emoji and multiple languages.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

No idea

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Don't know

### Is there a reason why this should be core and not an add-on in the asset library?

It should be in core because we want to make our game multi national and attractive..

**Comment by Zireael07** [comment]
Fonts that support every language are very large (unless you mean bitmap fonts, but the only one that fits would be Unifont, which is... NOT the prettiest)

Most of the users do not need all the Unicode codepoints anyway (and I say it as someone who dabbles in Russian, Arabic and Japanese)

**Comment by hani09876** [comment]
> Fonts that support every language are very large (unless you mean bitmap fonts, but the only one that fits would be Unifont, which is... NOT the prettiest)
> 
> Most of the users do not need all the Unicode codepoints anyway (and I say it as someone who dabbles in Russian, Arabic and Japanese)

Can you share me the link of unifont

**Comment by Zireael07** [comment]
When I made a fancy roguelike with lots of fancy characters (SDL2+Lua+BearLib) I think I used this site https://unifoundry.com/unifont/
But that was years back and maybe there are other, more updated sources?

**Comment by TheDuriel** [comment]
Really not a fan of adding 8MB to my godot game for a chinese character set I will never use.

**Comment by bruvzg** [comment]
> The limitation is currently Godot label doesn't support emoji. 

Bitmap emoji fonts are supported, but you need to provide a font or load a system font. It's not in beta 4, but Godot editor is doing it by default now, so you can add the same system font config to your project, see https://github.com/godotengine/godot/pull/68090.

**Comment by Calinou** [comment]
As mentioned above, we should avoid increasing binary size for a font that will not be displayed in most projects.

What we can do though is load CJK fallback fonts as system fonts, as a fallback to the default project font.

**Comment by hani09876** [comment]
> As mentioned above, we should avoid increasing binary size by several MBs for a font that will not be displayed in most projects.
> 
> What we can do though is load CJK and emoji fallback fonts as system fonts, as a fallback to the default project font (which will remain bundled with projects to ensure consistent metrics across platforms).

I think as the motive is not to increase godot size then a label can be added to the asset store which will support every language and image. @Calinou what do you think

**Comment by bruvzg** [comment]
> What we can do though is load CJK and emoji fallback fonts as system fonts, as a fallback to the default project font (which will remain bundled with projects to ensure consistent metrics across platforms).

We need to compose a good list of fonts to use (choosing a first available one is usually bad, since it might have completely different style).

On Windows and macOS it's gonna be pretty straightforward, but not on Linux (I guess we can compose a list of commonly available fonts).

Also, system fonts are not supported on Android (loading can be implemented, but not listing) and Web (only possible with experimental Chrome Canary API).

**Comment by hani09876** [comment]
> > What we can do though is load CJK and emoji fallback fonts as system fonts, as a fallback to the default project font (which will remain bundled with projects to ensure consistent metrics across platforms).
> 
> We need to compose a good list of fonts to use (choosing a first available one is usually bad, since it might have completely different style).
> 
> On Windows and macOS it's gonna be pretty straightforward, but not on Linux (I guess we can compose a list of commonly available fonts).
> 
> Also, system fonts are not supported on Android (loading can be implemented, but not listing) and Web (only possible with experimental Chrome Canary API).

You are right.. but what about emojis.. the emoji can be  shown if the label support. Because the a font which supports emojis on Android studio don't support emojis on godot.

**Comment by Calinou** [comment]
WIP: https://github.com/Calinou/godot/tree/default-project-font-add-system-font-fallbacks

Testing project: [test_default_project_font_system_fallback.zip](https://github.com/godotengine/godot-proposals/files/10048072/test_default_project_font_system_fallback.zip)

Also, the `sans-serif` system font doesn't appear to be working here.

Unfortunately, this noticeably slows down project startup and shutdown, even if no glyphs from the loaded system fonts are displayed:

```
❯ hyperfine -iw1 "bin/godot.linuxbsd.editor.x86_64.llvm --path ~/Documents/Godot/test_default_project_font_system_fallback/ --quit" "bin/godot.linuxbsd.editor.x86_64.llvm.modified --path ~/Documents/Godot/test_default_project_font_system_fallback/ --quit"  
Benchmark #1: bin/godot.linuxbsd.editor.x86_64.llvm --path ~/Documents/Godot/test_default_project_font_system_fallback/ --quit
  Time (mean ± σ):      1.578 s ±  0.316 s    [User: 594.2 ms, System: 56.2 ms]
  Range (min … max):    0.682 s …  1.720 s    10 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Benchmark #2: bin/godot.linuxbsd.editor.x86_64.llvm.modified --path ~/Documents/Godot/test_default_project_font_system_fallback/ --quit
  Time (mean ± σ):      1.924 s ±  0.019 s    [User: 738.0 ms, System: 156.9 ms]
  Range (min … max):    1.886 s …  1.944 s    10 runs
 
Summary
  'bin/godot.linuxbsd.editor.x86_64.llvm --path ~/Documents/Godot/test_default_project_font_system_fallback/ --quit' ran
    1.22 ± 0.24 times faster than 'bin/godot.linuxbsd.editor.x86_64.llvm.modified --path ~/Documents/Godot/test_default_project_font_system_fallback/ --quit'
```

**Comment by bruvzg** [comment]
> Also, the sans-serif system font doesn't appear to be working here (but the emoji fonts do).

Usually the default `sanf-serif` font is Latin only, so it's not helpful to add it. And a way to request fallback fonts for other languages is quite different on different platforms (and not always directly available if you aren't using the system shaping engine).

**Comment by hani09876** [comment]
> > Also, the sans-serif system font doesn't appear to be working here (but the emoji fonts do).
> 
> Usually the default `sanf-serif` font is Latin (or a limited set of most used scripts) only, so it's not helpful to add it. And a way to request fallback fonts for other languages is quite different on different platforms (and not always directly available if you aren't using the system shaping engine).

The think the label should be modify to show  emojis from keyboard. Because a font that can show emojis on Android studio but can't show emojis on godot

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/68995, closing.
