### ISSUE TITLE
Log project and port number

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-proposals#578]
**Describe the project you are working on:**
client server project
**Describe the problem or limitation you are having in your project:**
Every time I debug my client and my server at same time  I have to set different port to show the debug result in dock
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
move the port setting in project only
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
NA
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
nope
**Is there a reason why this should be core and not an add-on in the asset library?:**
NA

**Comment by KoBeWi** [comment]
This needs more details.

**Comment by Calinou** [comment]
You can create custom project settings that are then read in the client or server code:

```gdscript
ProjectSettings.get_setting("application/server/port")
```

**Comment by git2013vb** [comment]
I'm talking about this:

![image](https://user-images.githubusercontent.com/13235119/76785676-bf9d9480-67ad-11ea-9758-5aa6119937e4.png)

**Comment by Calinou** [comment]
Wouldn't this proposal become obsolete if https://github.com/godotengine/godot/pull/37067 is merge anyaway?

**Comment by git2013vb** [comment]
Both solution are valid. In my case we will have more control?
My question is: what will happen if some ports are already reserved or we have in mind to use for any reasons? 
If i consider this aspect I will prefer to be able to set by myself for each project. But for someone else maybe is better the automatic solution.

**Comment by git2013vb** [comment]
> You can create custom project settings that are then read in the client or server code:
> 
> ```gdscript
> # Default to 25000 if the setting evaluates to `false`
> # (which will happen if it's not defined, as it will return `null`).
> var port = ProjectSettings.get_setting("application/server/port") or 25000
> ```

How I can access to editor settings likewise? - i use C# but I guess will be the same as gdscript.

**Comment by tanjunior** [comment]
I recently made a plugin to make changing ports more convenient
https://godotengine.org/asset-library/asset/641

**Comment by git2013vb** [comment]
@tanjunior Thank you for your suggestion but I have already found a workaround with a plugin of mine as described here [#37687](https://github.com/godotengine/godot/issues/37687#event-3264349058) . It work setting to port when the project start.
Here I was asking to "move" the current editor settings in "project" settings.. Or make some sort of priority where if I set it in "project" settings it became the current setting for that project otherwise it will get the "editor" value setting instead.

**Comment by tanjunior** [comment]
@git2013vb That is a good idea, i will try to add it to my plugin.

**Comment by tanjunior** [comment]
I successfully added that to my plugin. It now saves the port in project settings. And everytime you open up the project it will retrieve the setting and apply it to editor settings. Waiting for it to be approved on Asset Library.
Meanwhile you can get it from my git https://github.com/tanjunior/Remote-Port-on-Toolbar

**Comment by KoBeWi** [comment]
So this was basically solved by plugin?

**Comment by git2013vb** [comment]
I still think that will be better to move it in Project property without be forced to use a plugin.
For something so simple its worth, too many plugins to load if not.

**Comment by tanjunior** [comment]
Yea I made this plugin to use just until godot release new version with #37067 committed.

**Comment by git2013vb** [comment]
So it is the same so we can close this :)
Thanks :)
