### ISSUE TITLE
Add .NET 7 support

### ISSUE THREAD

**Issue by squidink7** [godotengine/godot-proposals#5780]
### Describe the project you are working on

Small games in C#

### Describe the problem or limitation you are having in your project

Right now Godot uses .NET 6, and .NET 7 recently released as stable. This new release has new features and a performance boost, and as I use it for non-godot projects I already have it installed. This means I need 2 SDK versions, one for Godot and one for everything else.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

.NET 7 is newer and has several features not present in version 6, and will start to be used in more projects as time goes on. It also features new functionality which could be quite beneficial to Godot, such as Native AOT compilation, however support for this is outside the scope of this issue.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I haven't delved too deep into the Godot .NET glue code, however presumably it would be a matter of updating the generators to output .NET 7 compatible projects.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

C# support is already in core, this is just an update.

**Comment by ShalokShalom** [comment]
Did you try to just use 7, and see whats happening?

**Comment by squidink7** [comment]
I have set the target framework in my project to net7.0, but when I ran my game Godot couldn't find any of my scripts.

**Comment by squidink7** [comment]
Closing as completed: https://github.com/godotengine/godot/pull/71825
