### ISSUE TITLE
[Godot 4]Add a new property usage to specify property only used in editor or not be a property of object.

### ISSUE THREAD

**Issue by Daylily-Zeleen** [godotengine/godot-proposals#5807]
### Describe the project you are working on

Related to to [#68780](https://github.com/godotengine/godot/issues/68780), plese check it first.

### Describe the problem or limitation you are having in your project

The implement of [#68780](https://github.com/godotengine/godot/issues/68780) is not perfect, some wrong properies still can be get, such as "script" and "_import_path".

They are not be used as `PROPERTY_USAGE_CATEGORY`, `PROPERTY_USAGE_GROUP`, `PROPERTY_USAGE_SUBGROUP`, and not `PROPERTY_USAGE_ARRAY` with `TYPE_NIL`, but still unsuitable to be a property for object, like `script`:
A specific type of object's behavior is defined by a script, it means that a script let object become a specific type object.
We can using `obj.set_script(script)` method to change a object to another type of object, but we should not using `obj.script = script` to change. In my opinion, it should be to expose for editor to attach a script in inspector, but should not be a property of object.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a new property usage, for convenience，call it `PROPERTY_USAGE_EDITOR_HACK`.
So I can exclude properties which not be a property of object by check `PropertyInfo::usage`, let the behaviod of `Object::get_property_list()` and  `Script::get_script_property_list()` can be optionaly like in 3.x(without categories, groups, sub groups and so on).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. Add a new property usage `PROPERTY_USAGE_EDITOR_HACK`.
2. Specift every property, which not use `PROPERTY_USAGE_CATEGORY`, `PROPERTY_USAGE_GROUP`, `PROPERTY_USAGE_SUBGROUP`, and not `PROPERTY_USAGE_ARRAY` with `TYPE_NIL`, but unsuitable to be a property of object, to use this new usage.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Impossible.

### Is there a reason why this should be core and not an add-on in the asset library?

It is a core change.

**Comment by YuriSizov** [comment]
I'll close this and the other proposal so that the discussion of your issue can stay focused in one place (you've now opened 1 issue, 2 proposals, and 1 PR, which makes it impossible for people to keep track of what is being said). We can reopen it later if there is a conclusion for this.

For now, refer to https://github.com/godotengine/godot/issues/68780.
