### ISSUE TITLE
Add "fish bones" visualization to the Path2D in the Editor

### ISSUE THREAD

**Issue by xiongyaohua** [godotengine/godot-proposals#5811]
### Describe the project you are working on

City traffic game

### Describe the problem or limitation you are having in your project

The direction of Path2D is not clear

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Related with https://github.com/godotengine/godot-proposals/issues/5716, add fish bones also to `Path2D`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change the drawing method of `Path2D`. Something like this

<img width="704" alt="Screenshot 2022-11-19 at 15 21 47" src="https://user-images.githubusercontent.com/6020486/202839862-14b97664-76c1-47b6-bfc4-302517dd4a47.png">

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Path2D is core

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/68860.
