### ISSUE TITLE
Allow for math operations between floating point and integer coordinate Vectors

### ISSUE THREAD

**Issue by ClarkThyLord** [godotengine/godot-proposals#5818]
### Describe the project you are working on

Plugin for the Godot game engine(v. beta 5).

### Describe the problem or limitation you are having in your project

My plugin makes use of various types of vectors throughout it's codebase(e.g. Vector2, Vector2i, Vector3, Vector3i), and sometimes math operations between these two types of vectors is needed(e.g. addition, multiplication, division). However, when attempting to multiple different type of vectors a `Invalid operands to operator` error is thrown. For example:
![image](https://user-images.githubusercontent.com/17155529/202890451-92ffbf98-fadb-4674-8178-d7fcccc01d70.png)
Above you'll see variable `b` is the product of `Vector2i(1, 1)` multiplied by `0.1` resulting in a Vector2.
However, for variable `c` when attempting the same operation with `Vector2i(1, 1)` and `Vector2(0.1, 0.1)` a `Invalid operands to operator *, Vector2i and Vector2.` is thrown.
This makes for some odd logic as the two operations are fundamentally the same.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow for math operations(i.e. multiplication, division, addition, subtraction) between floating point and integer coordinate Vectors of all types(i.e. Vector2, Vector2i, Vector3, Vector3i Vector4, Vector4i). This can already be done between other types, for example: 
- We can multiply a integer with a floating point and the product is a floating point without any error.
- We can multiply a Vector2i with a floating point and the product is a Vector2 without any error.

Not having the same behavior we see between integers and floating points applied to different Vector types seems odd. 
And, allowing this would make for a simpler and cleaner code base.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Vector types can already do various math operations with other types including single integer and floating point values, so the this should just be another few cases added.

Math operations can only be done between floating point and integer coordinate Vectors of the same type(e.g. a Vector2i can multiply a Vector2, but can't multiply a Vector3).

The product between floating point and integer coordinate Vectors should always be the floating point type of the given Vectors(e.g. Vector2i * Vector2 returns Vector2).

For example, the Operator table for a Vector type using floating point coordinates would look as follows: (in the case of Vector2)
![image](https://user-images.githubusercontent.com/17155529/202889817-e11c16eb-1bc8-4d7b-b07c-8e8497ad5d50.png)

For example, the Operator table for a Vector type using integer coordinates would look as follows: (in the case of Vector2i)
![image](https://user-images.githubusercontent.com/17155529/202889934-89ac7a7d-a4cf-415a-8cb8-3fc4bfc597f8.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, the current solution is to type cast a Vector type from one to another, for example:

>var a : Vector2i = Vector2i(1, 1)

> var b : Vector2 = Vector2(1, 1) * Vector2(a)

> var c : Vector2 = Vector2(1, 1) * Vector2(Vector2i(1 ,1))

But I feel this "dirties" the code base, after all you wouldn't cast a integer every time you want to multiply it with an floating point.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core feature.

**Comment by Mickeon** [comment]
This may be related to a proposal I cannot recall. Regardless, the community consensus is clear. The new integer type variations (and String VS StringName) have generated a whole slew of issues that prove to be annoying to knowledgeable users, and a mere source of confusion to incoming users.

**Comment by Calinou** [comment]
Thganks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/5545.
