### ISSUE TITLE
Expose the peer ID in ENetConnection

### ISSUE THREAD

**Issue by YukenK** [godotengine/godot-proposals#5819]
### Describe the project you are working on

I'm working on a 2D MUD, and wanted to use Godot + low-level ENet.

### Describe the problem or limitation you are having in your project

It appears that there is no way to get a peer ID (with ease) from a client, as far as I can tell. The only potential solution I see right now is creating a dictionary of address + port -> client ID.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It is difficult to impossible to get IDs from clients sending packets to the server. Working with ENet requires client IDs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Peer ID of whoever sent the packet could be put in the Array returned by service.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

In theory, one could create a dictionary that looks like {"address:port" -> ID).

### Is there a reason why this should be core and not an add-on in the asset library?

This is to improve low-level ENet connections, which are currently being worked on in Godot 4.0.

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
`EnetConnection::service` returns and Array containing the `EnetPacketPeer` instance that generated the event.
As ID, you can use the object ID (`peer.get_instance_id()`) or assign your own during connection via `set_meta` (which is what the multiplayer peer currently does).

**Comment by YukenK** [comment]
I don't know how I managed to miss get_instance_id, oops. Thanks, both options seem to work depending on what I wanna do.
