### ISSUE TITLE
Add vertical alignment for [img] in RichTextLabel

### ISSUE THREAD

**Issue by Essojadojef** [godotengine/godot-proposals#582]
**Describe the project you are working on:**
An adventure game.

**Describe the problem or limitation you are having in your project:**
Currently the images are displayed with their bottom side aligned to the text baseline. This may be a problem as the top side and middle are misaligned.
![example](https://user-images.githubusercontent.com/33575693/76662577-ab278500-657e-11ea-9d5c-f2e491e2545f.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Align vertically the images in the center of the font or add a parameter (like the custom bbcodes' ones) to the img tag to allow different vertical alignments. For example: `[img valign=center]{path}[/img]`

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
In the RichTextLabel code `img->size.height + font->get_descent()` is used to calculate the image's position. I think this can be changed to `(img->size.height + font->get_descent()) / 2` to align to the center and `(img->size.height - font->get_height())` to align to the top of the font, but I didn't test these.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The problem can be reduced by changing the font top and bottom extra_spacing. But this may not work if there are images of different sizes.
![example_extra_spacing](https://user-images.githubusercontent.com/33575693/76662586-afec3900-657e-11ea-97d2-2d7d336941a6.png)
Edit: This only works in the editor and doesn't work at runtime so it doesn't solve the problem.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think this is the way users expect the RichTextLabel to handle images.

**Comment by Silvallis** [comment]
Is there any update on this. This seems to be a good QoL feature and for me the workaround doesn't seem to work if you run the game. In the editor it looks fine with reducing the extra spacing bottom of the font.

**Comment by Calinou** [comment]
> Is there any update on this.

As far as I know, nobody has started implementing this feature yet.

**Comment by bruvzg** [comment]
It is implemented in master, as part of Text Server.

**Comment by Calinou** [comment]
> It is implemented in master, as part of Text Server.

What's the syntax of that feature in `master`?

**Comment by bruvzg** [comment]
> What's the syntax to use that feature in master?

`[img=t]` or `[img=top]`, `[img=c]` or `[img=center]` and `[img=b]` or `[img=bottom]` places image above, in the center or below baseline respectively.

<img width="310" alt="Screenshot 2021-02-01 at 11 13 31" src="https://user-images.githubusercontent.com/7645683/106438052-a1508e00-647e-11eb-9546-ec137da4dbe6.png">

**Comment by Essojadojef** [comment]
I'm closing this since the issue is solved in Godot 4.0. It would be cool to have this also on Godot 3 since the workaround doesn't seem to work.

**Comment by takhimi** [comment]
Hi. Does Godot 3 supports this or currently only for Godot 4 ?

**Comment by Calinou** [comment]
> Hi. Does Godot 3 supports this or currently only for Godot 4 ?

This was only implemented in 4.0 because it relies on the backwards-incompatible TextServer and RichTextLabel. It can't be backported to `3.x` as-is, but pull requests to reimplement the feature in a backwards-compatible manner are welcome.

**Comment by NiklasRiewald** [comment]
For people looking for a workaround in Godot3: https://docs.godotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel.html#image-vertical-offset

**Comment by Minimuino** [comment]
> For people looking for a workaround in Godot3: https://docs.godotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel.html#image-vertical-offset

New link to Godot 3 workaround: https://docs.godotengine.org/en/3.5/tutorials/ui/bbcode_in_richtextlabel.html#image-vertical-offset
