### ISSUE TITLE
Change AudioServer properties 'device' and 'capture_device' and their method names for clarity

### ISSUE THREAD

**Issue by souplamp** [godotengine/godot-proposals#5839]
### Describe the project you are working on

A multiplayer game with proximity voice chat.

### Describe the problem or limitation you are having in your project

The properties and methods of AudioServer are not named in an obvious way.

Take for example ['device'](https://docs.godotengine.org/en/latest/classes/class_audioserver.html#class-audioserver-property-device):
```
String device
Setter: set_device(value)
Getter: get_device()
```

This seems straight forward enough; this is a device used to handle audio. But take a look at the description just below it.

```
Name of the current device for audio output.
```

The device is only used for _audio output_? I assume since its simply named 'device' that I would be able to switch between input and output audio. It's not really clear that 'device' is _only_ an output audio device.

This is not all that confusing on its own, to be honest. But take another example from ['capture_device'](https://docs.godotengine.org/en/latest/classes/class_audioserver.html#class-audioserver-property-capture-device):

```
String capture_device
Setter capture_set_device(value)
Getter capture_get_device()
```

Not all that strange, but it does make you ask two questions:
1. Is capture_device on the same level as device? It seems capture_device is just a specialized version of device, so device could be used for either capabilities.
2. Is "capture" the verb in the set/get functions? Typically functions start with a verb and end with the subject/object. This seems like its breaking the function naming convention.

Again, we can read the description:

```
Name of the current device for audio input.
```

Aha, so a 'device' is an audio output device while 'capture_device' is an audio input device.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

My proposal is that we change the property and function names to make more sense with their descriptions.

### Properties:
- **device** -> output_device
- **capture_device** -> input_device

### Methods:
- **set_device(value)** -> set_output_device(value)
- **get_device()** -> get_output_device()
- **get_device_list()** -> get_output_device_list()
- **capture_set_device(value)** -> set_input_device(value)
- **capture_get_device()** -> get_input_device()
- **capture_get_device_list()** -> get_input_device_list()

Changing these names will make a little more sense from the outset as the distinction will lessen any confusion, as well as making it easier to predict the function and property names without needing to read the docs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simply change all of the examples listed above to their new counterparts.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Technically yes, you could simply use a helper function to mask the function, property names. But boilerplate code just to rename functions and properties is not as efficient.

### Is there a reason why this should be core and not an add-on in the asset library?

This would improve the naming clarity of core functionality.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/69120.
