### ISSUE TITLE
Add a snapping grid to polygon editors in the TileSet editor

### ISSUE THREAD

**Issue by nix365** [godotengine/godot-proposals#5847]
### Describe the project you are working on

2D game with a tile map

### Describe the problem or limitation you are having in your project

In comparison to Godot 3 adding proper collisions to a tile map is tedious<br>

In godot 3 by changing the steps in "Snap Options" it was possible to quickly add collisions in a smaller grid
![image](https://user-images.githubusercontent.com/72159736/203963471-699119f4-361a-4ddd-bf2a-4e7d5435830a.png)

Now in godot 4 it's no longer possible to change the snap options to quickly add collisions
![image](https://user-images.githubusercontent.com/72159736/203963960-1dc21e80-a2f8-405f-be8d-ebc7c34f4a1c.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the old snap options from Godot 3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will work like in Godot 3 by setting the step size different to the tile size

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It is a good feature that was already in Godot 3 and should be available in Godot 4

**Comment by KoBeWi** [comment]
You can add one shape and copy it to other tiles, mirroring and rotating as needed.

**Comment by nix365** [comment]
Thank you for your response, I already did try it with mirroring the shape. But as you can see, I don't get it lined up correctly. With no clear line to orientate getting the corners collision line up is not as easy as with the old step size. As an alternative a sub grid in the "Painting" area to easily draw the shape could help here.

**Comment by dalexeev** [comment]
* #5534

**Comment by ygypt** [comment]
Is it foreseeable that this feature make it into 4.0? In what will likely be Godot's largest launch,  bringing many new devs from other engines, the lack of snapping collisions will be a major pain point for anyone looking to work on tiling textures larger than 32x32. The issue becomes far more evident when you attempt to move_and_slide() along a tilemap with even slightly off-balanced collisions. As it stands the tilemap feature is seemingly unusable outside of pixel art unless you very meticulously alter each and every pixel until everything lines up. (which I did and it took me over an hour)

**Comment by Zireael07** [comment]
@ygypt It was just added to 4.x milestone, not 4.0, which means it won't go into 4.0

**Comment by Calinou** [comment]
4.0 is currently in RC stage, which means no new features can be added to it. Future feature development will have to wait for 4.1 at the earliest.

**Comment by dalexeev** [comment]
As a temporary workaround, you can change the numbers in the scene file (make sure the editor is closed and you have backups).

**Comment by nklbdev** [comment]
Wow! Great!
Maybe my small [plugin](https://github.com/nklbdev/godot-4-tile_set_polygon_snapper) can also help you on it
