### ISSUE TITLE
AnimationPlayer: "Save all animations"

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#585]
**Describe the project you are working on:** 2D 8-directional action game with lots of animations

**Describe the problem or limitation you are having in your project:** Bulk sharing Animations between projects is impossible from the editor and very hard and error prone to so outside of the editor. I dread it every time I have to do this.
It's very easy to save a single animation as resource in the Editor and pop that over to another project. However when you have 10s or hundreds of animations (sometimes even multiplied by the amounts of directions your game has), saving a single animation to drag it over to another project where one can load it and "make unique", very quickly becomes completely infeasible.

The only alternative is opening up the scene.tscn in a text editor, selecting all lines that belong to the AnimationPlayer and copying it over to the other scene.tscn at exactly the right place and hope that you did not miss anything and everything works. Halve the time it does not work. Maybe you forgot a line or two to copy, maybe there is some sub_resource id that does not match, maybe there are NodePaths that don't match, I don't know. Debugging this without expert knowledge is incredibly tedious and due to no feedback whatsoever.  Copying, cutting and pasting thousands lines of text back and forth multiple times is also super prone to error.

Currently my approach is to just leave the AnimationPlayer, and just rebuild everything around it in the Editor. This is incredible stupid though if all you actually want to change is the Animations.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
"Save all Animations" option next to "Save" (which imho should be called "Save this Animation")
I'm not sure if this would need a new file format, or if it could be .tres, I'm sure someone else knows more what would be the right way to do this.
Upon loading the file, I I think it would be really great if Godot would check if the Nodepaths are all valid. If they are not, let's say because the nodes are named differently or at a different location, a popup should show up to let me select which replacement nodes I want to use in my current scene tree to replace the missing ones.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A "Save all Animations" option next to "Save" ... 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I would have no idea how.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I believe saving all animations of an AnimationPlayer node is much more needed, and has much broader usecase, than the currently in core existing "save" that only allows to save a single Animation.

**Comment by KoBeWi** [comment]
> The only alternative is opening up the scene.tscn in a text editor, selecting all lines that belong to the AnimationPlayer and copying it over to the other scene.tscn at exactly the right place and hope that you did not miss anything and everything works.

Or you can save the AnimationPlayer as scene and copy that to the other project?

**Comment by golddotasksquestions** [comment]
Thanks @KoBeWi this sounds like the obvious solution I've always missed!
