### ISSUE TITLE
Record option to camera 2d

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#5856]
### Describe the project you are working on

2d project  android 

### Describe the problem or limitation you are having in your project

The camera 2d can't record video. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Please add a recording system to the camera 2d with audio recording support. This will help the user to record there game play and share with friends. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Don't have idea 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Don't know

### Is there a reason why this should be core and not an add-on in the asset library?

This should be in core . Because camera 2d is a node

**Comment by Calinou** [comment]
This is already available in 4.0.beta: https://godotengine.org/article/movie-maker-mode-arrives-in-godot-4

There are no plans to backport this to 3.x though.
