### ISSUE TITLE
Expose more info about state machine transitions

### ISSUE THREAD

**Issue by HitalloExiled** [godotengine/godot-proposals#5860]
### Describe the project you are working on

Working in a 3D game with complex animations.

### Describe the problem or limitation you are having in your project

Currently the godot api doesn't provide much information about running state machine transitions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add new methods and properties to AnimationNodeStateMachine, AnimationNode and AnimationNodeStateMachineTransition, which will expose more information about transitions and their execution.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```cs
// Adds more ways of get transition
class AnimationNodeStateMachine
{
    // Get playing transition, null if no transition is playing
    AnimationNodeStateMachineTransition? CurrentTransition { get; }

    // Or make AnimationNodeStateMachineTransition a subclass of AnimationNode and add a property that returns the current running node, which in this case would also include transitions.
    AnimationNode? CurrentNode { get; }

    // returns a transition between two nodes, null if the transition does not exist
    AnimationNodeStateMachineTransition? GetTransition(StringName from, StringName to); }

class AnimationNode
{
    AnimationNodeStateMachineTransition[] From { get; }
    AnimationNodeStateMachineTransition[] To { get; }

    AnimationNodeStateMachineTransition GetTransitionFrom(StringName node);
    AnimationNodeStateMachineTransition GetTransitionTo(StringName node);
}

// Adds executing info
class AnimationNodeStateMachineTransition
{
    bool IsPlaying { get; }
    float Progress { get; } // 0 to 1 considering xFade curve
    AnimationNode From { get; }
    AnimationNode To { get; }
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Building the transition graph is possible on the client side, but I can't find any way to get the state of the transition running.

### Is there a reason why this should be core and not an add-on in the asset library?

It's part of the core engine

**Comment by RedMser** [comment]
This info is already available: https://docs.godotengine.org/en/stable/classes/class_animationnodestatemachineplayback.html
I don't see anything for transitions, but I also don't think that makes much sense. Should be signals that notify whenever a transition is traversed - there's already a PR open for adding this.

**Comment by TokageItLab** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/7885
