### ISSUE TITLE
Support KHR_texture_basisu extension when loading glTF scenes

### ISSUE THREAD

**Issue by AllenDang** [godotengine/godot-proposals#5873]
### Describe the project you are working on

A metaverse which allows users to upload their own model, trade them, place them and construct world together, which means there will be hundreds and thousands model will be placed in one scene, so the file size of each model becomes crucial.

### Describe the problem or limitation you are having in your project

Currently godot cannot load glb file which is compressed with KHR_texture_basisu texture, which will increase model download/load time, and also will occupy much more storage space.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The KHR_texture_basisu extension of GLTF 2.0 could compress all the textures to KTX2, which is GPU compatible with very small size.
Invoke `gltfpack -tc -i input.glb -o output.glb` will compress the model from 180MB to 28.5MB with nearly no notable difference which is a huge improvement.  

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Compile GLTF model with KHR_texture_basisu enabled and support KTX 2.0 texture format.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, cannot worked around with script.

### Is there a reason why this should be core and not an add-on in the asset library?

GLTF support is i core itself.

**Comment by Calinou** [comment]
Godot features Basis Universal encoding support, but it's only available in the editor. Basis Universal decoding support should be usable from an exported project though.

**Comment by fire** [comment]
I wanted this feature too, but looking forward to this.

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/76572 is ready for review
