### ISSUE TITLE
Add a position offset to control nodes

### ISSUE THREAD

**Issue by djrain** [godotengine/godot-proposals#589]
**Describe the project you are working on:**

An RPG with a fair bit of UI.

**Describe the problem or limitation you are having in your project:**

I have a TextureRect inside of a CenterContainer. I would like the texture to be offset by a few pixels. There is no convenient way I know of to accomplish this, since containers always set the position of children control nodes. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

A simple fix for this particular problem would be to add a texture offset to TextureRect, similar to what Sprite has. However I think this problem applies to other controls as well. So my idea for a general solution is to add an "offset" Vector2 to all control-derived nodes which would allow for minor positioning tweaks. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

The offset would be added to the control's position, after any parent container has done its auto positioning. Perhaps there could also be an option for whether you want this offset to affect the rect_position, or only used for rendering.

But honestly I'm not super experienced with GUI stuff, so I'm not sure if this is even plausible. I welcome discussion of other potential solutions.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I think this enhancement would be used often. Not entirely sure about the workarounds.

**Is there a reason why this should be core and not an add-on in the asset library?:**

I imagine lots of people would find it useful to add an offset to control nodes inside containers.

**Comment by Kequc** [comment]
I'm in the middle of a deep dive into godot's control and container nodes. My understanding of intended use is to use a margin container. Would that solve your case?

My hesitation about your suggestion is that it creates a lot of questions. For example if a control is offset does that affect margins? If not, what about offsets other than by a number of pixels? I think this type of thing would be ripe for additional feature requests if implemented.

Perhaps a solution in code would be best, for example altering the texture and then setting it again. Or by creating a custom control node.

**Comment by Kequc** [comment]
For example this is the code I'm using to have a nicer looking icon... I'm not sure if it's the best solution but downscaling in texturerect it's the best solution I've found.

```
const icon_texture = preload("res://hud/textures/icon_texture.png")

onready var icon: TextureRect = get_node("icon")

func _ready():
	icon.texture = get_resized_texture(icon_texture, icon.rect_size)

static func get_resized_texture(texture: Texture, size: Vector2) -> ImageTexture:
	var image: Image = texture.get_data()
	var result: = ImageTexture.new()
	image.resize(size.x, size.y)
	result.create_from_image(image)
	return result
```

**Comment by djrain** [comment]
> I'm in the middle of a deep dive into godot's control and container nodes. My understanding of intended use is to use a margin container. Would that solve your case?

Wow, okay. So I had in fact tried this node, but it wasn't working so I figured it must be for something else. I probably edited the wrong margin values or something stupid.

So yeah MarginContainer provides the functionality I needed. Thank you. I will go ahead and close this now.
