### ISSUE TITLE
Add one, or two customization options to visual script in Godot 3.5 . . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#5895]
### Describe the project you are working on

A card game, also 3D content . . .

### Describe the problem or limitation you are having in your project

After Godot 4.0 lost visual script, there are perhaps a chance of getting bit of the newer look in Godot 3.5, some simple customization, here's what I had in mind, more updates . . .

1. set grey-scale for the boxes, perhaps from 0.4 - 1.0, so one can tweak saturation . . .
2. Having a different font for node headers make it easier to read, when zoomed . . . 

Those two things might make 3.5 visual script more enticing, or bit easier to read, the reason is also it looks like the new visual script module sort-of has stopped development, or at least there's no one there, sort-of hoping for some -very- simple customization, that might make it slightly nicer, also for different teams, perhaps last an easy setting, for rounded corners . . .

So, not sure if anyone has some better ideas, sort-of to make it appeal to more people, while not adding ton, of stuff, perhaps a few more settings, or so . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Really like visual script, though I realize it didn't belong in core, it's still a nice feature, and the 3.5 branch is simple, also relatively fast, a few more settings, not sure there are better ideas, that's all . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Not sure, a few extra settings, that make sense for 3.5, perhaps esp. the grey-scale, or similar icon saturation, it'd be really nice for someone that want to use 3.5 for semi - professional work, within reason . . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not sure, sort-of hoping for a short debate, mostly to improve appeal a bit, etc . . . 

### Is there a reason why this should be core and not an add-on in the asset library?

It's more to have something, bef. Godot 4 is ready for serious production, perhaps add a few tweaks, extra settings . . . .

**Comment by Calinou** [comment]
Visual script will not receive additional features in 3.x, as it will be removed in 4.0.
