### ISSUE TITLE
Add "Replace node" to context menu

### ISSUE THREAD

**Issue by rafaelcastrocouto** [godotengine/godot-proposals#5897]
### Describe the project you are working on

Shotcaller - https://github.com/spicylobstergames/shotcaller-godot

### Describe the problem or limitation you are having in your project

Every time I need to replace a node (by removing it and giving it's name to a new node), I need to manually update each animation on the Animation Player before removing the old node. If I skip the manual update I lose all animations for that node. Also if the node has signals, I have to copy paste them before removing.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'm aware that the node tree context menu is already a bit bloated, but it would be very handy to have some kind of 'replace node' option that would handle all of this and allow our future modders that can't code to quickly replace for eg. a weapon node without losing the weapon animation and signals.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would work like 'paste' but instead of creating a new node with a new name it would remove the selected node and give it's name to the new node along with the signal info.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I've seem some replace scripts on a few forums but the idea here it to make it quick via user interface.

### Is there a reason why this should be core and not an add-on in the asset library?

I feel this is a bit too specific for an external lib.

**Comment by AThousandShips** [comment]
Have you seen #4991

**Comment by rafaelcastrocouto** [comment]
> Have you seen #4991

No, I only searched for other replace proposals, sorry.
 
This seems like a better and broader proposal, plz close this one and thank you.
