### ISSUE TITLE
Replace deprecated altool with notarytool for macOS notarization

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-proposals#5898]
### Describe the project you are working on

Multi-platform game with macOS version

### Describe the problem or limitation you are having in your project

Currently the godot export process for macOS uses xcode altool for notarization, however, using it you get a warning that this tool is deprecated. As described here:
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow/notarizing_apps_when_developing_with_xcode_12_and_earlier?language=objc
It has been replaced by the newer notarytool and altool will stop being supported in late 2023.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

While notarization currently works (great work!) it seems that it will stop working with the current solution in 2023. Changing to using notarytool as described here:
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow?language=objc
Will esure future support for exporting notarized apps to macOS with Godot

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

From a quick glance it seems it mostly changing the current lines that invoke altool to instead invoke notarytool 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Technically you could manually do the notarization from terminal after exporting from Godot, but it would be convenient if this kept working from godot's export process. Especially as notarization is now more or less mandatory these days for macOS app distribution since macOS Gatekeeper will block apps without it in most cases.

### Is there a reason why this should be core and not an add-on in the asset library?

see above

**Comment by YuriSizov** [comment]
cc @bruvzg
