### ISSUE TITLE
Inform the users that non-default-constructible nodes are a bad thing

### ISSUE THREAD

**Issue by red1939** [godotengine/godot-proposals#5899]
### Describe the project you are working on

2D strategy game

### Describe the problem or limitation you are having in your project

When I created a new script that inherited from Node and put in into the scene, which I tried to later instantiate I got the following, cryptic error:

```
E 0:00:00:0302   _create_instance: Error constructing a GDScriptInstance.
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   modules/gdscript/gdscript.cpp:183 @ _create_instance()
```

Worst of all, is that you can ignore the error and everything seems to work fine, until you access the object and find out that only the base class was constructed...

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Currently, the above error is the only thing that is telling us that we have a type which cannot be default constructed and we try to instantiate the scene or duplicate it.

*NDC* = *N*on *D*efault *C*onstructible

There are several ways we can help user. From the cheapest, but least useful, to more intrusive ones.

1. Be more explicit in the documentation about this issue. The only mention about this issue is present ... in the documentation of `Object` which is a place that users won't go into, I guess. Text there states as follows:
"Note: If [_init](https://docs.godotengine.org/en/latest/classes/class_object.html#class-object-method-init) is defined with required parameters, the Object with script may only be created directly. If any other means (such as [PackedScene.instantiate](https://docs.godotengine.org/en/latest/classes/class_packedscene.html#class-packedscene-method-instantiate) or [Node.duplicate](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-duplicate)) are used, the script's initialization will fail."

We should at least add this information where we introduce users to Nodes or GDScript language.

As the biggest offender of this rule are custom `Node`-derived classes, subsequent proposals are aimed towards them.

2. In text editor when a NDC class is detected, a code warning can be added, so that the user knows that he/she limits the usage of this Node to dynamic instantiation.

3. In the Editor when a node is added which is NDC add a configuration warning (originating from the Node I guess) that this won't go well when trying to do `instantiate`.

4. When doing a `pack()` of the scene (or during construction of `PackedScene`) raise an error specifying that trying to continue will fail in the long run.

I believe 1, 3 & 4 would be perfect. Documentation wouldn't be harmed. You could continue writing your `func _init(arg) -> void` `Node`s without interruptions. When trying to instantiate them you could get some friendly warnings and finally, when you are stubborn, you would get a flat error (and no scene).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Described above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It cannot be worked around - it's just a gotcha that every new user of Godot engine has to go through. Needlessly, might I add.

### Is there a reason why this should be core and not an add-on in the asset library?

No asset library is concerned with creation of your custom types.

**Comment by pseidemann** [comment]
relevant proposal: #1513
