### ISSUE TITLE
Name the Node deleting

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#59]
**Describe the project you are working on:**
I have been using Godot for about a year and a month, and started many small minimal test projects, and working at two long term projects.

**Describe how this feature / enhancement will help your project:**
When learning and testing out the engine I add nodes all the times to my projects to learn about them, see if they have something I need, to test ect. Because I create many create many nodes to learn about them, I also delete many nodes. 

Whenever I delete a node, using RMB > Delete Node in the Scene Panel, I am prompted with a popup asking if I am sure I want to delete the node. This is fine and a standard in many applications.
However because Godot dims everything but the prompt (which is good, because so my attention is on the only permissive action I can take: either accept or cancel the prompt), it's hard to confirm I actually right-clicked on the correct node before. 
**The prompt does not say what node I am about to confirm deleting.**

**Proposal:** 
Add the `name of the node and it's symbol` in the prompt popup and if the node has children, also add `"and it's children?"` 
If more than one node was selected before RMB > Delete Node, it should say: `"Delete X Nodes?"` no brackets around the (s). X is the number of nodes
If one of these nodes has children: `"Delete X Nodes and their children?"`

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

![delete_node_proposal](https://user-images.githubusercontent.com/47016402/64697284-c8c94400-d4a0-11e9-84ff-42118ba677c6.png)

**Describe implementation detail for your proposal (in code), if possible:**
I'm not familiar with C++ 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's an editor UI/UX improvement, so no.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I believe it's too small of an improvement to actually make anyone download any addons, yet it would improve general UI/UX for everyone if it were present.

**Comment by Xrayez** [comment]
> Whenever I delete a node, using RMB > Delete Node in the Scene Panel,

For me it was more like when I hit `Delete` button on keyboard, I wasn't completely sure what node I'm deleting exactly at times.

But personally I just turned off delete confirmation at all, one can go back in history to restore a deleted node anyway: godotengine/godot#30816.

Can be configured in editor settings by overriding a shortcut:
![delete-no-confirm](https://user-images.githubusercontent.com/17108460/64699388-54e16880-d4ad-11e9-9886-e3eeb9819488.png)

**Comment by golddotasksquestions** [comment]
I do think confirm to delete in general is good UX though. Imagine someone accidentally miss-clicking or accidentally touching the `Delete `button and maybe not realizing the damage until much later.
It's great you can disable it though for those who rather not have confirmation dialogs at all. I did not know that.

**Comment by KoBeWi** [comment]
Would be cool to have this for files too.

**Comment by Calinou** [comment]
This was implemented in https://github.com/godotengine/godot/pull/31942, and could likely be cherry-picked in the `3.1` branch.

**Comment by girng** [comment]
the `(s)` implies the children are going to be deleted :P

**Comment by Calinou** [comment]
I'll close this as https://github.com/godotengine/godot/pull/31942 was merged in the `master` branch. It won't be cherry-picked to the `3.1` branch due to https://github.com/godotengine/godot/pull/31942#issuecomment-551757216 though.
