### ISSUE TITLE
Initial size for viewport nodes

### ISSUE THREAD

**Issue by rmvermeulen** [godotengine/godot-proposals#590]
**Describe the project you are working on:**
Many small toy projects

**Describe the problem or limitation you are having in your project:**
Forgetting to set the viewport size to anything buy (0, 0). Now it's one of the first things I check, but this has cost me several times. And now I've been helping out some others online and noticed it's not uncommon for people to miss this completely. It seems people generally expect _some_ result, which any size but zero will yield.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Setting the default viewport size to some size, e.g. ProjectSettings/display/window/size (1024, 600)
This means the default result is not a black texture, and it will be more obvious what is going on.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It would probably be most effective to use this just for those nodes that are added via the editor, It's just to make the simple case more intuitive.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's to help out users who are less familiar with godot, and will probably not use the asset library to get this behavior at that point.

**Comment by Calinou** [comment]
I remember there being a reason for the default viewport size being `Vector2(0, 0)`, but I can't remember why. I guess you could open a pull request and see if anything regresses :slightly_smiling_face:

**Comment by rmvermeulen** [comment]
I didn't think of this yesterday; maybe it would be safer to add a warning to the viewport if the size is `(0, 0)`, like physics bodies do when they don't have a collision shape.
I can add another message for the shadow atlas, or include it in the size warning.

Either way, I'll be looking into the code first and see what I can do.

**Comment by Calinou** [comment]
> I can add another message for the shadow atlas, or include it in the size warning.

You can have a shadow atlas of size 0 in a 2D-only viewport, or in a 3D viewport where you don't intend to use shadows.

**Comment by rmvermeulen** [comment]
I've added a single message now, I can make a PR. I'm still downloading the build tools but I don't expect any errors. I did not include a shadow_atlas_size message, for the reasons you mentioned as well as that it's not a beginner issue IMO.
I can still look into changing the size when created via menu, but I think this is actually better.

**Comment by akien-mga** [comment]
Fixed by godotengine/godot#37122.
