### ISSUE TITLE
Display placeholder for missing glyphs

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-proposals#591]
**Describe the project you are working on:** the Godot editor

**Describe the problem or limitation you are having in your project:**

Godot silently "eats" the character if it can't be provided by the font chain. It's hard to tell if it's a editor/game programming bug or it's just because the font does not have the glyph.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Use a placeholder glyph to provide a visual representation of the missing glyph, like the `.notdef` glyph in dynamic fonts.

![The .notdef glyph](https://docs.microsoft.com/en-us/typography/opentype/spec/images/notdef.gif)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

For dynamic fonts, use the `.notdef` glyph when the glyph is missing in the current font, and there are no fallback fonts available.

![example](https://user-images.githubusercontent.com/372476/76817198-274ef080-683d-11ea-8161-563544c4c0a8.png)

Bitmap fonts can also be modified to provide a similar "undefined" glyph. For example, automatically generate a checked rectangle box bitmap.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:** 

It seems impossible to load the `.notdef` glyph through GDScript.

**Comment by bruvzg** [comment]
At least for the editor, I would prefer something more informative, like character codes.

![Screenshot 2020-03-17 at 07 45 51](https://user-images.githubusercontent.com/7645683/76826085-3c6b5580-6824-11ea-9d4f-4a0345726d42.png)

**Comment by Calinou** [comment]
This was implemented in https://github.com/godotengine/godot/pull/41100, closing.

Since this relies on backwards-incompatible changes, this feature can't be backported to the `3.x` branch.
