### ISSUE TITLE
Single line node path export and initialization

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#5913]
### Describe the project you are working on

An FPS.

### Describe the problem or limitation you are having in your project

Since 3.x it's been possible to "hack" doing a node export in one line using:
`export(NodePath) onready var some_node = get_node(some_node) as TypeOfTheNode` (courtesy of https://www.reddit.com/r/godot/comments/kuagbx/exportnodepath_onready_var_some_node_get_nodesome/)

In 4.0 docs it's still suggested to be done with two lines:
![image](https://user-images.githubusercontent.com/16231628/206319708-e79a902e-1db4-473d-82b0-07d44763428f.png)

There should be a way of doing this in one line as of 4.0.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be more convenient than two lines.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Something like:
`@export @onready var node_name = get_node(node_name )` but more elegant.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

It would be GDScript 2.0.

**Comment by Spartan322** [comment]
Godot 4 already supports
```gdscript
@export
node : Node
```
since godotengine/godot#67055

**Comment by Calinou** [comment]
Closing per @Spartan322's comment. This won't be backported to 3.x, unless a motivated contributor does the required work (it's not trivial).

**Comment by elvisish** [comment]
> Godot 4 already supports
> 
> ```gdscript
> 
> @export
> 
> var node : Node
> 
> ```
> 
> since godotengine/godot#67055

Thanks, the docs should probably be updated to mention this?
