### ISSUE TITLE
Add Camera feature to copy editor's camera transform

### ISSUE THREAD

**Issue by pseidemann** [godotengine/godot-proposals#5916]
### Describe the project you are working on

any scene with a (static) Camera

### Describe the problem or limitation you are having in your project

positioning the Camera node to properly capture a specific region of a scene is quite hard and, without using the "preview camera" feature, almost impossible.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

it would be really nice if I could just set a Camera to the current position+angle of the editor's camera.
this way, I can just look at what I want with the editor (which is already very easy) and do, for example, one click on a new button, to copy the transform of the editor's camera, which will then position the Camera node so that it sees exactly the same what the editor sees.
this should make positioning a camera a work of seconds instead of minutes of tweaking angle and offsets.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

focus a Camera node in the scene tree. now a new button "Copy Editor Camera Transform" (suggestions for shorter names appreciated) next to the existing button "Transform" of the action bar (not sure how it is called exactly, I'm talking about the horizontal buttons bar right below the open scenes tabs) appears.

pressing this button will copy the current editor's camera transform to the focused Camera node, effectively copying what the editor sees, to the Camera.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

unknown

### Is there a reason why this should be core and not an add-on in the asset library?

- positioning a Camera manually is a very common task
- new button in the editor

**Comment by KoBeWi** [comment]
![godot windows editor dev x86_64_YPWLwoZ7gU](https://user-images.githubusercontent.com/2223172/206529685-dc579874-34e0-459a-831d-e6a9c926c691.gif)

**Comment by pseidemann** [comment]
I saw a lot of youtube tutorials but never someone who used this, apparently existing, feature.
maybe it's not visible enough?

**Comment by pseidemann** [comment]
follow-up proposal: #5917
