### ISSUE TITLE
Add a way to change InputMap using string or integer

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot-proposals#5936]
### Describe the project you are working on

im working on control remap and saving the control remap using config file.

https://docs.godotengine.org/en/stable/classes/class_configfile.html

however config file cannot save InputEvent type of data. instead, i'm saving it with String or integer.

let just say i want to remap sprint input with G keycode, that will return 71.

so, the config file will be  :

[input]

sprint = 71

so far so good!

well then,  i reopen the game and try to execute this remap

        InputMap.action_erase_events("sprint")
	InputMap.action_add_event("sprint", 71) <---- this does not work

because second parameter only accept InputEvent, not interger nor string.

InputMap.action_add_event("sprint", InputEvent)

is there any work around this?
maybe something like :

InputMap.action_add_event("sprint", InputMap.integer_to_inputevent(71))  <==== something like this

please consider this, because i already finish everything with main menu, except input remap.

thanks!

### Describe the problem or limitation you are having in your project

there is no method to convert integer or string into InputEvent

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

i want to able to convert integer or string into InputEvent

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

already done

### If this enhancement will not be used often, can it be worked around with a few lines of script?

so far, i dont find any works around this

### Is there a reason why this should be core and not an add-on in the asset library?

absolutely, this will make input remapping easier to implement

**Comment by KoBeWi** [comment]
> im working on control remap and saving the control remap using config file.

This already exists tho: https://github.com/KoBeWi/Godot-Input-Remap

> is there any work around this?

Yes
```GDScript
var event = InputEventKey.new()
event.scancode = 71
InputMap.action_add_event("sprint", event)
```
