### ISSUE TITLE
Remove delta param from _process and _physics_process to solve float/double cast issues

### ISSUE THREAD

**Issue by AndreSacilotto** [godotengine/godot-proposals#5943]
### Describe the project you are working on

RPG

### Describe the problem or limitation you are having in your project

Sometimes I do scripts that need to update every frame, but they do not need to use delta in any way. So needing to have it there is annoying and less performatic.

`I'm a bit skeptical about performance, because removing the delta would imply in 2 engine calls instead of one, when delta is needed. But of course this probably is in the field of micro-optizimation, so the comfort may be worth it.`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

First, there is no limitation, this is just an enhancement.

There is already other forms of getting delta - `Node::get_process_delta_time` and `Node::get_physics_process_delta_time`  - so having it as a parameter seems redundant.
Seems even more redundant when you notice that these methods are used when the engine calls process.

But this change would also help on #5403 problem. More on that next section.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

So the engine now uses doubles for delta, but certain things still uses floats (which is good thing) and on c# this is very noticeably. That problem is most encountered when dealing with delta, so we can add to the engine:
`float Node::get_process_delta_timef`
`float Node::get_physics_process_delta_timef`
Where it would have a simply cast the double to float, so the user can choose if he wants the double or float version. 
If this is implemented, it would cause the delta param to be even more redundant. So it remove would be necessary, otherwise it would make the engine call the same method two times.

So I think removing the delta param and adding this two functions, would be the ideal solution to the double->float delta issue. And no more unused variables, and ~NOT~ less important the micro performance gain.

I can think a few reasons to not implement this:
1. Break backward compatibility, but it's easy change;
2. Less noob friend, because they will gonna the method multiple times in the code instead of caching it;
3. Something that I'm not aware, about delta calculation;

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's a core change, but a workaround is possible (thx to comments)

```gdscript
func _notification(int what):
    if what == NOTIFICATION_PROCESS:
        //delta = get_process_delta_time()
        ...
```
#### C# (with extension methods)
Extension.cs
```c#
public static float GetProcessDeltaTimef(this Node nd) => (float)nd.GetProcessDeltaTime();
```
Code.cs
```c#
public override void _Notification(int what)
{
    if (what == NOTIFICATION_PROCESS)
         //delta = this.GetProcessDeltaTimef()
         ...
}
```

### Is there a reason why this should be core and not an add-on in the asset library?

Impossible

**Comment by AndreSacilotto** [comment]
Someone could argument that this proposal are 2 proposals, they would not be wrong.
1. Remove of the delta param from process;
2. Addition of `get_delta_float` methods;

So why have I done this way? Well the (2) makes no sense to implemented without the (1).

**Comment by Zireael07** [comment]
> So the engine now use doubles

Not true. It only uses doubles if built to do so.

And having a different API for doubles build vs normal isn't a good idea

**Comment by YuriSizov** [comment]
> There is already other forms of getting delta - Node::get_process_delta_time and Node::get_physics_process_delta_time - so having it as a parameter seems redundant.
> Seems even more redundant when you notice that these methods are used when the engine calls process.

The engine doesn't have handy methods for processing logic at all, it's all done in the notification handling code. You can do that as well, if you think it would improve your performance. Just implement `_notification` and do everything there.

Virtual helpers like `_process` exist specifically to make life easier for those who use the scripting API. Removing the delta argument would make them a very thin abstraction over notification handling, so not that useful to the end users.

**Comment by KoBeWi** [comment]
> The engine doesn't have handy methods for processing logic at all, it's all done in the notification handling code. You can do that as well, if you think it would improve your performance. Just implement _notification and do everything there.

This.

```GDScript
func _notification(int what):
    if what == NOTIFICATION_PROCESS:
        code
```
Process function without delta.

**Comment by AndreSacilotto** [comment]
So there is a workaround in the end. I was really not aware that `process` was only a abstraction of `notification`.

Anyway, the proposal still makes sense, but if the current team thinks the design is good, what can I do.

Good that I learn something from it, a good reference for someone that thinks the same as me in the future. I don't know if I should close this or not, I will leave to moderators to decide.
