### ISSUE TITLE
Implement ANSI-to-BBCode conversion in RichTextLabel

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#5947]
### Describe the project you are working on

A Terminal App, I can work on this feature if it is agreed to add it to Godot.

### Describe the problem or limitation you are having in your project

no ANSI Parsing 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

add ANSI parsing to RichTextLabel

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I can think of two options :
convert ANSI to bbcode 
directly parse ANSI

I think with the first option we can just provide a global function to convert ANSI to bbcode, but converting ANSI to bbcode can be limiting in the terms of colors ?

ansi to bbcode example : https://github.com/rubyworks/ansi/blob/master/lib/ansi/bbcode.rb#L101

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it can be worked around for me by converting ANSI to BBCode, but I think this is limiting.

### Is there a reason why this should be core and not an add-on in the asset library?

no, but maybe it could be better to have it built-in like bbcode ?

**Comment by Calinou** [comment]
This can be done with an add-on just fine :slightly_smiling_face:

**Comment by ywmaa** [comment]
I think this feature has very low interest, so closing this proposal.
