### ISSUE TITLE
Remove blending feature `Default Blend Time` from AnimationPlayer

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#5952]
### Describe the project you are working on

Stabilization for Godot animation features

### Describe the problem or limitation you are having in your project

See also
- https://github.com/godotengine/godot/issues/70207

![image](https://user-images.githubusercontent.com/61938263/208278742-a54c39ae-13ee-42e3-bdb8-654c77580ef0.png)

I have tried to apply the same blending algorithm as AnimationTree to AnimationPlayer, but have encountered some problems. 

First, the new AnimationTree blending algorithm has a reference value as "rest" or "reset" in case the blend value does not exist. However, for example, if you set a BlendTime of 0.5s for the AnimationPlayer and play a new animation, the animation will start from the reference value. If this BlendTime is intended for something like a crossfade, it is necessary to make a special case for the first animation or make some other method.

Another problem is that this AnimationPlayer blending has the potential to blend animation with itself. **Not only is it the same animation, but it is also the same animation "cache".** This causes confusion about playback position and direction. Currently, this is manifesting as a problem with the animation playback button not working correctly when spamming it with BlendTime set.

https://user-images.githubusercontent.com/61938263/208279090-9165c9ca-683e-4eb9-b344-ce16fe52fa53.mp4

Moreover, AnimationPlayer blending is causing code duplication with AnimationTree (currently, the old blending algorithm remains).

For the above reasons, I propose to remove blending feature from AnimationPlayer. By the way, Capture mode is not an issue here, so it can remain.

**If this functionality is removed, it should not be a problem because there are already features that cover it as AnimationTree and AnimationStateMachine. And that is what should generally be used.**

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It removes duplicated code and makes the behavior more stable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

To begin with, Godot 3 and 4 animations are already incompatible.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

AnimationPlayer is in the core

**Comment by jitspoe** [comment]
Not sure if I agree with this. I and others I know use animations with blends almost exclusively because setting up a whole AnimationTree is very cumbersome and awkward to use.  I would actually argue that more functionality for blending (such as being able to do blend trees and such) should be brought to the animation player and accessible via code and have the tree just be a visual thing.

**Comment by TokageItLab** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/5972
