### ISSUE TITLE
Make C# script names default to PascalCase in the "attach new script" popup

### ISSUE THREAD

**Issue by lewiji** [godotengine/godot-proposals#5956]
### Describe the project you are working on

Any Godot 4 C# project

### Describe the problem or limitation you are having in your project

This PR:

https://github.com/godotengine/godot/pull/52597

Changed the behaviour of this script creation dialog to autofill the script filename with a lowercased version of the node name. This changed previous behaviour in 3.x which respected the node name casing setting.

C# documentation recommends, and most C# developers use the PascalCase convention for class names, and Godot expects C# source filenames to match their class names to work.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Change the behaviour of the dialogue to suggest PascalCase when switching to the C# script type and lowercase when switching to gdscript.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Either revert to the old behaviour of the dialog when the c# script type is selected, or else add a configurable option for how this name is determined in all cases.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core godot component.

**Comment by lewiji** [comment]
I've just realised this isn't quite what I thought it was; the change is for *scene filenames*, and you can indeed change the project settings to make scene filenames PascalCase instead. I suppose someone might want snake case scene names and PascalCase script names if working with C#, but I interpreted the problem incorrectly, so I'm going to close this.

**Comment by lewiji** [comment]
Ok, I've heard from a couple of people that this actually did impact them as they prefer snake case resource names, but there's no option to default to PascalCase script names. Reopening!

**Comment by brunoamancio** [comment]
Nothing else matters other than if the script being created is c#, PascalCase

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/5446.
