### ISSUE TITLE
Add a subgraphing system to visual scripting

### ISSUE THREAD

**Issue by sps014** [godotengine/godot-proposals#596]
#### Current Scenario:
The essential missing feature in Visual Scripting is the ability to collapse a selection of nodes into a function, expand them and then store them in an accessible function library. This function library is retrievable as a resource to be shared in plugins and the current project.
Imagine if I have to do a repeated operation multiple times for some different inputs.
Currently we can not reuse the nodes for a different set of input values.
![problem](https://user-images.githubusercontent.com/45932883/76952151-ae31c500-6932-11ea-9740-e5f2293ee40c.PNG)

#### Idea
For reusing these set of the node  the idea is to isolate the set of nodes 
![Capture](https://user-images.githubusercontent.com/45932883/76951521-d5d45d80-6931-11ea-9214-aa0df451e963.PNG)
We will box reusable Nodes within the function, with a validated function unit name.
Input and output are connected to Input function and Output function Nodes.
This approach is inspired by the working of functions that enables modularity.

And we can generate a custom node at design time similar to 
![capt2](https://user-images.githubusercontent.com/45932883/76952645-695a5e00-6933-11ea-8aab-b9ad56bd99b5.PNG)

It can be used multiple times and we can also make it exportable as a Library so it can be called from other Godot supported language runtime if we will be able to bind or transpile it.

#### My Background With VS Systems
I had developed a VS System from  Scratch in C++, even wrote controls myself [here](https://github.com/sps014/Operator).

#### Thanks
Your feedback will be certainly valuable to me.

**Comment by sps014** [comment]
I am confident to achieve this, will love to hear about this approach  
Please  provide your valuable feedback.

**Comment by girng** [comment]
Not a visual programmer, however, whatever makes the life better for you guys, I'm for 100%.

**Comment by sps014** [comment]
Thanks @girng

**Comment by willnationsdev** [comment]
iirc, @fire was helping to put together this exact topic as a proposal for GSoC.

**Comment by sps014** [comment]
I am part of GSOC 2020, have decided to take feedback on the above-discussed design system.

**Comment by fire** [comment]
PR for Reviewing VisualScript Module(aka Submodules) Patch #7 

https://github.com/swarnimarun/godot/pull/7

Here's a notification for those who are interested.

**Comment by fire** [comment]
Here's the newer module waiting to be completed. @swarnimarun https://github.com/godotengine/godot/pull/45294

**Comment by theoway** [comment]
@sps014 If you're a student & meet the GSoC eligibility, you can also apply for this proposal for GSoC '22. A PR  has already been made, it needs major refactoring and bug fixing. 
You might wanna check this [PR](https://github.com/godotengine/godot/pull/45294)

**Comment by sps014** [comment]
> @sps014 If you're a student & meet the GSoC eligibility, you can also apply for this proposal for GSoC '22. A PR  has already been made, it needs major refactoring and bug fixing. 
> You might wanna check this [PR](https://github.com/godotengine/godot/pull/45294)

Thanks for opportunity, i do not meet the eligibility criteria now, Will keep contributing in my free time though.

**Comment by fire** [comment]
Read carefully, the eligibility criteria changes and you do not need to be a student.

**Comment by Geometror** [comment]
Just for reference: The equivalent to this for VisualShader will be discussed at https://github.com/godotengine/godot-proposals/issues/5271.
