### ISSUE TITLE
Port geometry-based occlusion culling to Godot 4

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot-proposals#5967]
### Describe the project you are working on

One game is a first person shooter in a roguelite vein with procedural level generation. Also, a first person puzzle game. I am trying to port these over from 3.5 to 4.0

### Describe the problem or limitation you are having in your project

Case 1: This game is a first person shooter in a roguelite vein with most levels created procedurally. The way I have it set up in 3.5 is that I use the occluder shape polygons on just certain base structures that are at the eye level. This means that in the main city levels I only need 2 - 4 planar occluders per perimeter object for the whole level. This perimeter object is a scene that swaps out meshes as needed and is then instanced with other meshes to create the perimeter walls of the city. To do this with the 4.0 raster occlusion, I would have to try and bake out a solution after level generation in game, which could lead to unknown results as well as add a large pause for the player while this is happening. Not sure it is even designed to bake in game? Conclusion: I wouldn't try and use baked occlusion in 4.0 for this game.

![battletronik_ui](https://user-images.githubusercontent.com/7741669/208583191-62fdac13-01c4-4170-b106-244d0dcd1f54.jpg)

![battletronik_screen](https://user-images.githubusercontent.com/7741669/208583259-8a69b0df-0d4b-430b-8923-cd8462fee48a.jpg)

Case 2: This game is a first person puzzle game. In 3.5 I have setup manual occluder shape polygons inside the walls that are double sided. This means I can have one occluder that will work for either wall direction. This is simple to layout and very efficient, and can be put exactly where I need them. For instance, I wouldn't put them on the outer walls, since there is nothing behind them.

One of the big issues with occluders for a game like this are the doors that open and close. In this case I am using sliding doors. With the 3.5 solution I can either parent the occluder to a door so that it slides out of the way. This can lead to items popping into view, so is generally better to disable it or move it up out of view. Once again the manual solution gives me runtime choices that a baked solution doesn't provide.

![headcase_screen2](https://user-images.githubusercontent.com/7741669/208583695-3fdc7f05-391f-4db3-b4e7-8c92a0c3d7a5.jpg)

![headcase_ui2](https://user-images.githubusercontent.com/7741669/208583737-b268832c-0d0e-434c-b6be-ca356509a147.jpg)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Case2: In contrast, the 4.0 baking method will use all meshes by default. This means that it is an opt out system, requiring the user to flag each mesh in the game that doesn't require culling. For instance, small objects inside rooms need to be removed from culling as they will tend to pop in and out as you move around the scene. In general, you probably don't want any small - mid sized objects inside the room to be occluders, so they will all need to be flagged as not part of the occlusion baking. 

This is not a a big deal in itself, but it is the doors that are the real issue. Since they are not occluding, if you happen to be looking in the direction of several doors, you will get significant overdraw as everything behind all these doors is drawn leading to fps spikes. Unlike the 3.5 system, with baked occlusion you can't toggle a door occlusion on and off in game or use moving occluders.

I would imagine that the 3.5 method is also more performant than the raster baked method, so is more suitable for mobile games, web games, switch games, etc.

As a general note, I was recently able to revive development of this old project when the 3.5 occluder system came out as it finally allowed me to get a good 60fps on moderate hardware. Previously I was getting poor performance and massive overdraw since there are lots of objects and custom shaders behind all the walls/doors that were being rendered. Conclusion: While I could use the 4.0 occlusion baking method for this game if it was all that was available, it wouldn't be as useful as the 3.5 system. (Additional note: this game uses voxelgi which is quite taxing on a gpu so I need any performance advantage that I can get. It is currently running significantly slower with the new forward renderer in 4.0 than in does in 3.5 with opengl.)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would be exactly how it is currently in 3.5. Personally, I only use the shape occluders and not the spherical ones. I would also like the ability to disable/enable the occluder at runtime with a "disabled" flag as is possible with colliders.

@lawnjelly who created the 3.5 occlusion system has told me that he is willing to port it to 4.x if there is enough community demand for it, hence why I have written this proposal.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Because it is a fundamental engine feature that needs to be as fast as possible in conjunction with the renderer.

**Comment by reduz** [comment]
The ones in 4.0 can be baked in-game and it happens threaded, so you should have no problem using them. The way the renderer in 4.0 works makes it impossible to implement the same system as in 3.x, so that's likely not going to happen.

**Comment by fracteed** [comment]
@reduz That is a bummer. Would it work for the mobile vulkan renderer? Is there any way of getting dynamic occlusion for things like doors or large objects that need to be disabled or enabled in game play?

I don't think I would ever risk baking occlusion for a procedural level. Aside from the additional baking time, it could be risky, not knowing the baked solution ahead of time.

**Comment by reduz** [comment]
@fracteed Again, the baking is always dynamic and pretty much immediate (much less than a second). This uses Intel's code for BVH generation, which is insanely fast, so you have no risk.

**Comment by reduz** [comment]
If your occluder geometry is basic (as you are showing in your screenshots) updating a BVH based on it is instantaneous.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/3920.

**Comment by alib86** [comment]
Haven't checked out the occlusion system in 4.0 yet but found the 3.5 occluder shapes to be very easy to use and efficient for procedurally generated scenes - specifically for urban settings (tall buildings as occluders) with first person perspective.

**Comment by fracteed** [comment]
@Calinou thanks for the tips, there as some good ideas there!

The voxelgi game uses only emissive surfaces for lighting ,so I can't build in a toggle off without either using baking (which I find problematic) or reducing the visual style to use omnis. In 3.5 with culling I am able to reach a 60fps 1080p on a moderate system, which renewed my interest in starting dev on the game again.

When bringing this to 4.0 I have found that since the forward renderer is less performant than 3.5, I can only reach the 60fps with halfres gi option and very low aa. The baked occlusion is working but I would imagine is less performant than the 2 solutions in 3.5. I will have a play with some of the options you mentioned, and I do have some faith that the render performance will increase in the 4.1 cycle! Btw the depth pass alone did not help a great deal, as compared to the culling.

For my fps shooter game, I will most likely move to the Vulkan mobile renderer for this when some of the bugs are fixed. It is a good fit for that and in my early tests it is faster than 3.5 even without any occlusion. I will not bother with the culling any more on that one.

**Comment by fracteed** [comment]
I am going to close this as when you get used to it., the manual occluders are very similar to the 3.5 system. Calinou has a lot of good workflow tips there that I am playing with, so not really necessary to keep this issue open any more!
