### ISSUE TITLE
Unify accessors for native and script enums

### ISSUE THREAD

**Issue by anvilfolk** [godotengine/godot-proposals#5968]
### Describe the project you are working on

The project is Godot's GDScript :) Or any project which uses GDScript enums!

### Describe the problem or limitation you are having in your project

Accessing enums in GDScript classes and native classes is inconsistent.

For example, using the native tileset [Tileset](https://docs.godotengine.org/en/latest/classes/class_tileset.html#enum-tileset-tileshape) has an enum named `TileShape`. To access its values in GDscript, you have to do `TileSet.TILE_SHAPE_SQUARE`, or even just `TILE_SHAPE_SQUARE` which is a global constant.

However, for a GDScript class, the following does not work.

```GDScript
class_name MyClass

enum MyEnum { V1, V2 }

func _ready():
  print(V1) # Does not work
  print(MyClass.V1) # Does not work
  print(MyEnum.V1) # Does work
```

There are other issues with consistency between native enums and gdscript enums, but concerns are specifically about exporting named enum value identifiers into the surrounding class scope, which is a change from 3.x.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The enhancement is to unify how enums are accessed between native classes and gdscript classes, therefore permitting accessing the `V1` value in the 3 ways described above.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

All we have to do is add a check for named enum members of a class in `GDScriptAnalyser::reduce_identifier_from_base()`.

This is already implemented in https://github.com/godotengine/godot/pull/69590. That PR does not currently throw errors or warnings for name clashes or shadowing while we wait for a couple other PRs that are dealing with identifier scoping.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can always access named enum values using their enum name first. It is just more verbose and inconsistent with how native enums work.

### Is there a reason why this should be core and not an add-on in the asset library?

Has to be implemented within the GDScript analyzer/module.

**Comment by HolonProduction** [comment]
There is a difference in naming between native enums and gdscript enums. For the native enums the enum name is part of the constant name. `TILE_SHAPE_SQUARE` contains the name `TileShape`. In this way there is still some sort of grouping. Furthermore it is possible to understand the meaning of the constant. `TileSet.SQUARE` would be quite confusing.

When creating an own enum I do not add the enum name to the constants. If it were possible to access them on the class it would be hard to understand their meaning. Think of `CustomUIElement.COPY` instead of `CustomUIElement.TEXT_OPERATION.COPY`. The grouping which is often the reason for using an enum  would be lost as well.

Apart from this I see a problem with the implementation when a class constant is contained as key in an enum too. Or when two enums contain the same key. Those cases would not be possible anymore. The sense of enums is to seperate some constants. I would not expect constants from the outer scope to have influence on the naming inside. This also means that this feature is a breaking change.

Also I had a look at https://github.com/godotengine/godot/pull/69590 and IMO `TileSet.TileShape.TILE_SHAPE_SQUARE` does look wrong as it contains `TileShape` twice.

**Comment by anvilfolk** [comment]
No, these are valid criticisms and really good points :)

> There is a difference in naming between native enums and gdscript enums. 

I think you're right, most of the native enums to have a prefix that details what enum they belong to, though some don't, such as in `performance.h`. 

```enum Monitor {
	TIME_FPS,
	...
	MEMORY_STATIC,
	...
	OBJECT_RESOURCE_COUNT,
	...
	RENDER_TOTAL_DRAW_CALLS_IN_FRAME,
	...
	RENDER_BUFFER_MEM_USED,
	PHYSICS_2D_ACTIVE_OBJECTS,
	...
	PHYSICS_3D_ISLAND_COUNT,
	AUDIO_OUTPUT_LATENCY,
	MONITOR_MAX
	};```

Most of the cases where they don't seem to be very specific to certain issues, like here for performance evaluation, so not an issue for regular users.

> When creating an own enum I do not add the enum name to the constants.

I understand that, but I'd also argue that things like `Character.MOVING` are easier to use & more accessible than `Character.State.MOVING`, which you would need to do from outside the `Character` class.


> Apart from this I see a problem with the implementation when a class constant is contained as key in an enum too. Or when two enums contain the same key. Those cases would not be possible anymore. The sense of enums is to seperate some constants. I would not expect constants from the outer scope to have influence on the naming inside. This also means that this feature is a breaking change.

The PR currently does not implement error reporting because there was already a lot in it and there is subtle ongoing work around scoping issues in # that I would like to see resolved before I implement errors here. Maybe that's the wrong approach and I should just add it, then deal with merge conflicts later.

Here's what I had to say about name clashes & shadowing regarding @rune-scape 's comment:

```GDScript
const VALUE = 42

class Inner:
    enum MemberEnum1 { VALUE = 1 }
    enum MemberEnum2 { VALUE = 2 }
    enum MemberEnum3 { Node = 3 }

    class Inner2:
        const V1 = VALUE
        const V2 = Node
```

My answer:

- `enum MemberEnum1 { VALUE = 1 }` should throw a clash error since now you can't reach outer class `VALUE`.
- `enum MemberEnum2 { VALUE = 2 }` should at least throw a shadow warning for `MemberEnum1.VALUE`. I think a warning is enough since disambiguation can always be done with `MemberEnum1.VALUE`.
- `enum MemberEnum3 { Node = 3 }` should throw a clash error since `Node` is a native type.

This effectively makes named enums behave the same as regular enums. We just need to make sure the warnings & errors are there.

But adding in all the errors, I'd like to see the results of #70246 so the warnings are consistent with that behavior too :)

**Comment by anvilfolk** [comment]
> Also I had a look at [godotengine/godot#69590](https://github.com/godotengine/godot/pull/69590) and IMO `TileSet.TileShape.TILE_SHAPE_SQUARE` does look wrong as it contains `TileShape` twice.

Also fair! :) but we are having to allow access to `TileSet.TileShape` so we can typecheck things such as `func test(v : TileSet.TileShape)`, so it doesn't feel like a stretch that it is at least possible to write `TileSet.TileShape.TILE_SHAPE_SQUARE` either.

**Comment by HolonProduction** [comment]
> I understand that, but I'd also argue that things like `Character.MOVING` are easier to use & more accessible than `Character.State.MOVING`, which you would need to do from outside the `Character` class.

I agree that there may be alot of cases where the cosntant name is enough to understand the meaning. In this cases using the constant directly provides a usability advantage. But I think unnamed enums are the way to go for this.

In my opinion the way enums work in GDScript is the better way compared to the behaviour of native enums. To solve the discrepancy I would prefer to only change the way of accessing native enums.
`TileSet.TileShape.SQUARE` is as good as `TileSet.TILE_SHAPE_SQUARE`. But solving this inconsistency is propably not worth such a breaking change.

**Comment by HolonProduction** [comment]
> Also fair! :) but we are having to allow access to `TileSet.TileShape` so we can typecheck things such as `func test(v : TileSet.TileShape)`, so it doesn't feel like a stretch that it is at least possible to write `TileSet.TileShape.TILE_SHAPE_SQUARE` either.

Yeah this is just a small beauty issue. It is a good solution considering that it does not break compatibility. Typing native enums is a great thing that should be added regardless of this proposal.

**Comment by anvilfolk** [comment]
> I agree that there may be alot of cases where the cosntant name is enough to understand the meaning. In this cases using the constant directly provides a usability advantage. But I think unnamed enums are the way to go for this.

I do think there are two (minor!) issues with that. The first one is that you might have different categories that you're interested. `Character.MOVING` could be part of a state machine, whereas `Character.BIG` could reflect on a character's size. Two different things, two different enums.

Once you go to unnamed enums, you lose the ability to typecheck things also. Either everything is untyped, or they are typed as `int` and then explicitly cast into the enum. This has the unfortunate side-effect that you lose one of the few optimizations that GDScript can do, which is taking things which are absolute constants and just using that value instead of doing lookups at runtime.



But anyway, though we may still somewhat disagree, I really appreciate you taking time to think about this and offering your opinions! <3 You are right that scoping named enum values into the class would break compatibility if people are using enum value names as e.g. variable or class names.

**Comment by rune-scape** [comment]
i agree that adding a cleaner shorthand like `TileSet.TileShape.SQUARE` would be a good way to make enums much more consistent, i feel that native enums values are lacking because they act like constants, and not a values in a named scope

**Comment by anvilfolk** [comment]
I don't think we can do that without being a little too hacky for my personal taste in the analyzer. We'd need to check in `reduce_subscript` whether `base` resolved to a native enum, then go into `attribute` and change the string name to add the `base`'s name changed from `ThisNamingPattern` to `THIS_NAMING_PATTERN`.

Either that or change the `BIND_ENUM_CONSTANT` macro to add multiple names for the same constant, which may just be overpolluting the constant namespace?

**Comment by adamscott** [comment]
> i agree that adding a cleaner shorthand like `TileSet.TileShape.SQUARE` would be a good way to make enums much more consistent, i feel that native enums values are lacking because they act like constants, and not a values in a named scope

Especially [when the documentation clearly says that it's an enum](https://docs.godotengine.org/en/latest/classes/class_tileset.html#enumerations).

**Comment by anvilfolk** [comment]
Alright friends, looks clear enough that there isn't any support for this - I have removed it from my PR :)
