### ISSUE TITLE
Implement Blender-style vertex colour support for OBJ import

### ISSUE THREAD

**Issue by OlivierVanHoutte** [godotengine/godot-proposals#5973]
### Describe the project you are working on

For my project I am creating a lot of meshes. 
I batch export these meshes use them in MultiMeshInstances.
Now I want to add some shader magic through vertex colours.

 

### Describe the problem or limitation you are having in your project

I could export all my meshes as GLTF2, then go to import settings and define a path where It should save the mesh. This is fine for a couple of meshes, but when you have 100+ meshes, this is very tedious work. 
An easier way would be to export to obj, and not having to think about it any further.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I know, obj doesn't support vertex colours. But a lot of 3D modelling software does support exporting these values in one way or another.

Seeing as Godot is establishing a closer relationship with blender (through loading blend files), I think it can be a time saver (at least for me) if we would support blender style vertex colours. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

	if (l.begins_with("v ")) {
			//vertex
			Vector<String> v = l.split(" ", false);
			ERR_FAIL_COND_V(v.size() < 4, ERR_FILE_CORRUPT);
			Vector3 vtx;
			vtx.x = v[1].to_float() * scale_mesh.x + offset_mesh.x;
			vtx.y = v[2].to_float() * scale_mesh.y + offset_mesh.y;
			vtx.z = v[3].to_float() * scale_mesh.z + offset_mesh.z;
			vertices.push_back(vtx);
			
			//colors
			if (use_blender_style_vertex_colours){
				ERR_FAIL_COND_V(v.size() < 7, ERR_FILE_CORRUPT);
				Color color;
				color.r = v[4].to_float();
				color.g = v[5].to_float();
				color.b = v[6].to_float();
				colors.push_back(color)
			}

}

We add a bool "use_blender_style_vertex_colours" to the obj import settings
only a few extra lines needed to load these colours.  

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Other options are possible, but take more work
- Custom importer.
- Manually editing the import settings for a ton of GLTF2 files
- Writing a script that loads, and extracts each mesh from their respective  GLTF2 file.

### Is there a reason why this should be core and not an add-on in the asset library?

Creating an add-on for a file type that is already supported feels kind of strange.
The addition is very small code wise, would not require a lot of work compared to writing a custom importer.
Easy to disable if you don't need vertex colours.

**Comment by Calinou** [comment]
> `if (use_blender_style_vertex_colours){`

Does it *have* to be made an import option? Can't we just read the fields conditionally if they exist?

**Comment by OlivierVanHoutte** [comment]
As far as I'm concerned, the import option isn't really necessary. I just added it in case some other software exports some different data but with the same formatting. In that very specific, and pretty unlikely case, it might cause problems. 

As far as I can tell blender doesn't support alpha channel in vertex colours no. But i'm no blender expert. There may a way to add alpha somehow. 
![image](https://user-images.githubusercontent.com/33663275/208990720-502e891f-0c5e-4e88-a1b7-6b00b8d7b9f4.png)
