### ISSUE TITLE
Readd renderer selection dropdown to the editor window

### ISSUE THREAD

**Issue by hakro** [godotengine/godot-proposals#5979]
### Describe the project you are working on

No specific project.
This is a generic proposal regarding the Godot 4.0 main editor and the renderer that has been chosen.

### Describe the problem or limitation you are having in your project

In Godot 3, the project renderer used to be visible in the main editor: 

![2022-12-23_18-44](https://user-images.githubusercontent.com/3624853/209381197-5b697fea-4a95-41f1-b536-e651f63d550a.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot 4 allows choosing the renderer (Forward+, Mobile, OpenGL) when creating a new project. You can change this afterwards in the project settings.

However, this info is a bit hidden from view.
There will probably be an increase of Godot 4 3D tutorial in the near future. And the renderer used is an important information to have on first sight, since the visual quality and performance changes drastically from one renderer to the other.

I don't think it's necessary to allow the user to change the Renderer from the main editor screen, they will still need to do that from the project settings. But it's a good idea to display it, just like the Godot version in the bottom bar : 

![2022-12-23_18-55](https://user-images.githubusercontent.com/3624853/209384009-ca710650-db4e-40b8-a5c6-63ed8ef9e8e8.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just an information display on the editor

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This probably should be core stuff

### Is there a reason why this should be core and not an add-on in the asset library?

It should be on the editor

**Comment by dsnopek** [comment]
This would be helpful for contributors/maintainers working on issues, because if the reporter posts a screenshot, it'll immediately be clear which renderer is being used.

**Comment by Calinou** [comment]
I remember this dropdown was intentionally hidden at some point. Its code is still present in latest `master`:

https://github.com/godotengine/godot/blob/03694757735d2331b157478f2337b3a87421ac92/editor/editor_node.cpp#L6958-L6981

**Comment by hakro** [comment]
Cool !

I toggled the flag back to true `renderer->set_visible(true);` and ran a build.

![2022-12-23_20-50](https://user-images.githubusercontent.com/3624853/209400142-7a71a286-259d-4637-ba97-e43945963252.png)

![2022-12-23_20-53](https://user-images.githubusercontent.com/3624853/209400324-d3bd687a-bb6b-4c57-b164-73611acbaf84.png)

But the style seems a bit "out of place" imho.
Any quick suggestion on how to make look it better ? I'll open a PR once it looks decent.

Cheers !

**Comment by Calinou** [comment]
The OptionButton is reserving space for the name of its longest option (`gl_compatibility`). This can be made a bit better by mapping renderer names to full names (Forward+, Mobile, Compatibility), but it'll still be quite long.
