### ISSUE TITLE
Hide baked light properties on ArrayMeshes

### ISSUE THREAD

**Issue by sanyi12** [godotengine/godot-proposals#5997]
### Describe the project you are working on

a 3d simple project

### Describe the problem or limitation you are having in your project

multitude of simple blocks objects that are created with godot and blender

The blocks created in blender do work out and the lights are baked. The ones created in godot do not work and do not create proper baked shadows. Even so, the properties for them to be used as baked light do show up. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

ArrayMeshes cannot be UV2 unwrapped in godot for some reason so that it would bake the light map. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

if a 3d object would be of type ArrayMesh it should automatically disable baked light properties

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it can be ignored completely. 

### Is there a reason why this should be core and not an add-on in the asset library?

it would make things so much easier for newcomers.

**Comment by Calinou** [comment]
The baked light properties should be hidden on meshes that don't have UV2, not on all ArrayMeshes. It is possible to generate ArrayMeshes with UV2 with a script.

**Comment by Calinou** [comment]
This no longer an issue as of Godot 4.0, closing. The **Bake UV2** option in the Mesh menu now works on any mesh type (for PrimitiveMeshes, it'll enable the **Add UV2** property within them).
