### ISSUE TITLE
Add DPI settings to allow for Object-based Display Scaling

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot-proposals#6]
Display Scaling for changing the scale of Nodes
----

![image](https://user-images.githubusercontent.com/19930870/57303717-890ddc80-70fb-11e9-958f-245c6796137b.png)

> Here I changed the Display Scaling of Editor itself to show how well it works.

The Display Scaling is used by the Editor globally making it problematic for the Visual Scripting system to discretely use it.

I see a few simple ways of achieve the solution to this problem,
- First, is to give all the UI Nodes a `zoom`/`dpi`/`display_scale` variable that holds zoom factor propagated by the Graph Edit Node. This will allow for Graph Nodes to have different Scaling.
- Second, is to add the `display_scale` variable to the Theme which will allow for inheritance based Display Scaling. This is a more clean solution but can have bugs like opening windows from one context will open weirdly themed windows(probably can be fixed with some planning).

Even though this is mostly for Visual Scripting but adding display_scaling to UI Nodes can be useful for scaling of menus in the actual games.

**Comment by swarnimarun** [comment]
cc: @fire @toger5

**Comment by toger5** [comment]
This is something i also have thought about. I currently have a working branch on my system with full dpi support. You can change any Theme to use and a dpi scale. This will scale the styleboxes and constants. (Also works for image based style boxes)
I really want to get the pr open. I have it on my pc for such a long time now...

Makes me want to finally open the pr.

**Comment by swarnimarun** [comment]
@toger5 if you do open it let me know. I tried seeing your fork of Godot didn't find it. At least not all of it.
I can fake by using a display scale variable but not sure about what will the best approach be.

**Comment by fire** [comment]
@toger5 Is this your branch? https://github.com/toger5/godot/tree/theme_dpi_sb_draw_api

**Comment by toger5** [comment]
Yea that is actually it. just not up to date. Just found the code and made a temp commit. I will push it now but history will change so dont work on it ;)

**Comment by fire** [comment]
@toger5 Shared https://gist.github.com/toger5/935ce8b29d533d5a258683b6173f9f6a

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/52170 should address this once it's merged. Its `3.x` counterpart was already merged in Godot 3.4: https://github.com/godotengine/godot/pull/52137

**Comment by fire** [comment]
Fixed by: https://github.com/godotengine/godot/pull/52170
