### ISSUE TITLE
3d Scene 'Dummy Camera' on play

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot-proposals#60]
**Describe the project you are working on:**

When working on 3D Scenes, it is painful to have to temporarily add a Camera node and position it accordingly just to be able to see how the scene looks. If you fail to do this, the scene is simply rendered as a black window and is a waste of time either way.

**Describe how this feature / enhancement will help your project:**

Development workflows and prototyping can go much faster if users can simply play a scene, and if there are 3d nodes found and no camera available, it will copy the position and orientation of the Editor camera to instance a new 'temporary' camera for viewing.

Additionally, this camera could be fitted with a simple 'fly-through' controller to allow users to quickly travel around their scene in-game without having to go through constant camera setup and teardown just to work on their scenes.

**Describe implementation detail for your proposal (in code), if possible:**

Some possible Psuedocode:

```
scene_launched():
  if scene_is_2d():
    return
  if scene_is_3d():
    
    if current_camera():
      return
    
    var editor_camera_transform = editor_camera.transform
    var new_flythrough_camera = FlyThroughCamera.instance()
    new_flythrough_camera.transform = editor_camera_flythrough
    scene_tree.root_node.add_child(new_flythrough_camera)
```

Of course, this psuedocode is very optimistic, and does not go through the FlyThrough camera controller, but those are straigtforward and can be implemented easily.

It can be non-trivial to determine what is a 2D scene vs. a 3D scene, especially with viewport trickery, but I think that if a scene ONLY has 3D nodes (and possibly GUI nodes) in the tree then it is obviously a 3D scene. Additionally, you can traverse the scene tree looking for any camera nodes set to Current, and if none are then make the camera.

I'm unsure of the specifics for passing through the current editor camera view, especially if there are multiple views (or none!) in the editor but then it could simple pick one at random (or the 'oldest' one), or simply add a default camera in the 'middle-ish' of the scene.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I believe that all developers working on 3D games, including artists, will be utilizing this feature heavily. Additionally, this greatly reduces the barrier of entry for new developers to get started making games. By reducing frustrations and improving general workflows, the Godot engine will benefit with growth and interest, especially from users who are used to other game engines who are interested in switching over.

Thanks,
-Devin

**Comment by HeadClot** [comment]
Hey @DevinPentecost
> I haven't used Unity or Unreal in years, do they still do this?

I use Unreal 4 and it does this by default and it is really helpful to new comers to the engine :)
Unity does not unless you import the correct package into a project. Which can be confusing IMO. That said I am happy to see this being tackled. :)

**Comment by Calinou** [comment]
I'll close this, as this is now provided by https://github.com/godotengine/godot/pull/27742 which has been recently merged. Click the camera icon in the 2D or 3D viewport while the project is running:

![image](https://user-images.githubusercontent.com/180032/69482694-dd21a980-0e1e-11ea-9ee6-0aec6ac2b51f.png)

It works even if no Camera node is present in the running scene.
