### ISSUE TITLE
Find in script: Mention the current match number (e.g. "X of 14 matches")

### ISSUE THREAD

**Issue by DDoop** [godotengine/godot-proposals#600]
**Describe the project you are working on:**
Software that traces cycloids, not relevant to issue.

**Describe the problem or limitation you are having in your project:**
Find in script feature in the editor is lacking a key component that is typical of most "ctrl+f" find tools, making it difficult to keep track of where in the file the user is, and how the specific instance of the matched text relates to all other instances of the matched text. Finding the first use of a function is sometimes extremely useful. I am re-writing my `print()` statements to be more debug friendly, and this is one time I would like to have a better understanding of how each `print()` follows the last in my script. Just being able to +/- through the list of results is insufficient. From what I can tell, there is not a "find first," or "find last," either, both of which I have become accustomed to from other "ctrl+f" tools in other software.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It should display what count of the total the user has highlighted while scrolling through results. For instance, if the user looks for "foo" and has 14 results, when they are 'on' the 5th result of 14, Godot should say so, ideally nearby where the "X matches" text is displayed.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I know just about 0 things how Godot's UI is constructed, but this should be as easy as adding a label beneath the current "X matches" text that appears when "ctrl+F" is used. How does Godot's editor text search store results? Accessing that information might make the issue easier to resolve.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not by me. Yet.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I have never heard of any software asking for users to install an add-on in the asset library to see what item out of a list of search results they are in. I personally struggle to see the issue from this perspective, since I consider this a basic feature. I am surprised this seems to be the first time the issue has been raised, though, given how important I assumed this was.

**Comment by Calinou** [comment]
It seems the script editor doesn't keep track of which match it is currently in, so adding a counter like this isn't trivial.

**Comment by me2beats** [comment]
> It seems the script editor doesn't keep track of which match it is currently in, so adding a counter like this isn't trivial.

`cur_match:int = text.slice(0, get_selection_end()).count(get_selected_text())`  something like that
