### ISSUE TITLE
Open scenes are displayed only when the corresponding scene editor is opened

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot-proposals#6005]
For example, when "2D" or "3D" is selected, the red circle position shows the currently open scene, and when "Script" or "AssestLib" is selected, the tab of the red circle position is hidden

![image](https://user-images.githubusercontent.com/119792950/209639860-accb61a4-0639-4210-a081-aafc60090232.png)

**Comment by KoBeWi** [comment]
You need to fill all template fields (with unique and relevant text), not skip it. If you can't, open a [discussion](https://github.com/godotengine/godot-proposals/discussions) instead.
