### ISSUE TITLE
Implement a task list (TODO list) in the editor

### ISSUE THREAD

**Issue by Saitodepaula** [godotengine/godot-proposals#602]
**Describe the project you are working on:**
3D racing game

**Describe the problem or limitation you are having in your project:**
The only way to track the many TODOs in my scripts right now is to open one by one, and searching for "TODO".

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add an item in the PROJECT or DEBUG menu, called TASK LIST, like [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2019), where one can see all the TODOs and/or other tagged (or token) comments, like TODO, BUG, HACK etc.
This way, it will be very fast and easy to track tasks, and, in a project with many people working on, everyone can see the task list easily.
Also, syntax highlighting for TODO, BUG, HACK and other tags would be useful.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The example is the same from the link above, from Visual Studio. It is simply a list of comments with the defined tags to be tracked down.

![image](https://user-images.githubusercontent.com/22160489/77087102-746bc780-69e1-11ea-8fb1-0893336fc248.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think it will be used often, all the time actually.

**Is there a reason why this should be core and not an add-on in the asset library?:**
There is an [add-on already actually](https://godotengine.org/asset-library/asset/53), but it is old. In my opinion, programmers in general are used to task lists, so they expect this functionality when they arrive in a new system. The task list is like a basic feature, so I think it should not be relegated to be an add-on that you have to search for.

**Comment by Xrayez** [comment]
> There is an add-on already actually, but it is old.

Seems like there's a fork for 3.x, it's not on AssetLib though:
https://github.com/JavaryGames/godot-todo

**Comment by Jummit** [comment]
> …programmers in general are used to task lists, so they expect this functionality when they arrive in a new system.

In which applications do task lists exist?

**Comment by Saitodepaula** [comment]
> 
> Seems like there's [a fork for 3.x](https://github.com/JavaryGames/godot-todo), it's not on the AssetLib though.

Didn't know about this one. But, as I've said, I think that a plugin is not what a task list deserves.

> In which programs do task lists exist?

Visual Studio (link in the first message), [Eclipse](http://www.eclipse.org/mylyn/new/new-2.0.html) and [Spyder](https://docs.spyder-ide.org/overview.html). I'm not a professional or experienced programmer, but I know these ones, and they are widely used (each one in a respective context and type of user), as far as I know.

**Comment by KoBeWi** [comment]
> The only way to track the many TODOs in my scripts right now is to open one by one, and searching for "TODO".

Are you aware of Search in Files? (Ctrl + Shift + F)
It will list all your TODOs nicely.

**Comment by Saitodepaula** [comment]
> Are you aware of Search in Files? (Ctrl + Shift + F)
> It will list all your TODOs nicely.

No, I was not! And thanks for that! I think I should know that already...

Still, a task list, like the Visual Studio or Spyder ones, work with many tags/tokens. And if the feature is an item in a menu, it is better than a shortcut (even if the result is almost a good one, Search in Files ideed display a list nicely, with files and lines identified).

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/6371.

**Comment by inDigiNeous** [comment]
Would suggest looking into issue trackers, like in github. Building such a tool is a complex task.

**Comment by YuriSizov** [comment]
We've discussed this in a proposal review meeting, and it seems like the use case is already well covered by addons/plugins. What we could do on the engine side is make it easier to extract TODO comments, like we do with documentation comments. I'll close this proposal as not wanted on the engine side, but if anyone wants to work on it, feel free to open a proposal or a direct PR to fetch TODO comments.

Can possible use LanguageServer.
