### ISSUE TITLE
In-Editor translation editor

### ISSUE THREAD

**Issue by Khhs167** [godotengine/godot-proposals#6036]
### Describe the project you are working on

I am currently working on a small sory-based game, and I want to prepare for localization early on.

### Describe the problem or limitation you are having in your project

The fact is: the method i've been using for editing the translation CSVs has been to use gedit, since google sheets takes a lot of work to copy over data etc

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Really, just a really simple table editor so that we can edit translations
This could be something in the style of the Input Mappings editor, or a basic 2D grid. Not sure

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/34920681/210244713-6f43e43c-05ef-41b8-a4ac-fd8f48e87422.png)
Extremely poorly made mock-ups of editors lol
Hope they're understandable lol

### If this enhancement will not be used often, can it be worked around with a few lines of script?

nope.

### Is there a reason why this should be core and not an add-on in the asset library?

I think it is a small and simple feature, but it will encourage localization, and ease of use when it comes to the localization system

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/13.
