### ISSUE TITLE
Add a setting to change the inspector display color of CurveTexture (from the default red)

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-proposals#604]
**Describe the project you are working on:**
UI scenes
**Describe the problem or limitation you are having in your project:**
![image](https://user-images.githubusercontent.com/13235119/77098283-04256c00-6a0a-11ea-9b4b-454479a54b22.png)
I can't change the red - default? - color
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I think it will be useful if we can change the color
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
NA
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
NA
**Is there a reason why this should be core and not an add-on in the asset library?:**
NA

**Comment by Xrayez** [comment]
I think this is not meant to be used for UI, see [reduz introducing this feature on Twitter](https://twitter.com/reduzio/status/849246250138570752).

> Godot gets a general purpose curve texture (with editor). It can be used to affect particle parameters over time, or in your own shaders.

I suppose the red (R) channel is just the first component so it's more obvious to operate in shaders?

Each of the RGB components could be used to decode their own curve, so it makes sense to me to have this, but this would also make the editor more complex perhaps. Would be nice to just switch different curves and edit them one at the time for each component (so you'll have 3 curves to edit now).

 The `CurveTexture` class is also poorly documented it seems.

**Comment by git2013vb** [comment]
> The `CurveTexture` class is also poorly documented it seems.

That's the BIGGEST problem with any feature that is not documented.
It is a **unbearable** effort to a developer to EXPLAIN how to use a feature RIGHT after they implement it? This is laziness multiply to infinite. 
How make any sense to have something that NOBODY can use it?  Someone can explain me please?  And don't tell me that because is OPEN SOURCE people are allowed to what they want and nobody can force them do do the right thing. 
I believe there is someone in charge to check if people are following rules. Right?
Also who better that who did that feature to explain how to use it? We still need OTHER people to come in to do reverse engineering and try to GUESS what that feature do?

Apologies for my "rant" but I'm one of many who love Godot. Imagine everyone else who don't know what godot is or have to use it because have to. After 1~2 weeks they give up.

Thank you.

**Comment by groud** [comment]
@git2013vb Sorry, but ranting like that is not acceptable. Such comments are not really welcome as they bring nothing good to the conversation.

> It is a unbearable effort to a developer to EXPLAIN how to use a feature RIGHT after they implement it? This is laziness multiply to infinite.

The CurveTexture was implemented by reduz himself, who basically built more than half of the engine. Calling him lazy does not make a lot of sense, sorry...

Godot is a community effort by a lot of people using their free time to contribute to the engine, we cannot force people to document everything they do, as this would prevent a lot of needed features to be implemented. So we sometimes prefer to merged undocumented feature than not merging them at all. This is something we have discussed a lot and is unlikely to change.

PS: please refrain from expand on this topic, this is not the place to do so.

**Comment by Calinou** [comment]
I think it's better to display it in red to make it more explicit. If we display it in grayscale, it may mislead people who think it's actually a grayscale gradient when it's not.

**Comment by Xrayez** [comment]
The point is that you could define 3 different curves. If all curves share the same parameters, the texture *will* be grayscale, but if they're all different, it's going to display a blend of colors because each curve will contribute to the color differently at each offset.

The red would still be the default one, because that would be the first component in the editor. That's kinda my own proposal inspired by this one.

I'd imagine this having 3 buttons up there: `R`, `G`, `B`, clicking on each will display the available curve (unless I'm mistaken and the texture is actually not RGB but only has R component).

**Comment by Calinou** [comment]
A RGB CurveTexture was implemented by https://github.com/godotengine/godot/pull/50054 (now called CurveTextureXYZ), closing.
