### ISSUE TITLE
Make `AnimatedSprite`'s playback API consistent with `AnimationPlayer`

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot-proposals#6043]
### Describe the project you are working on

Stabilization of Godot's animation system

### Describe the problem or limitation you are having in your project

`AnimatedSprite`'s playback API is inconsistent with `AnimationPlayer`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`AnimatedSprite` exposes a `playing` property, but it also has `play()` and `stop()` methods. This means that there are two playback APIs and the `playing` property may be rewritten without a setter.

The `set_playing` looks like a pause/resume function, but it is not exactly that function because it discards timeouts. https://github.com/godotengine/godot/pull/65986 tries to address that, but in the first place, considering the approach of AnimationPlayer, `playing` should be readonly.

Perhaps exposing `playing` is just a hack to give the inspector playback functionality. So I suggest that the correct way is to place the play and stop buttons in SpriteEditor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

First, make `set_playing()` private.

Next, change the `play()` and `stop()` APIs:

- `play()` resume if the animation is the same, and if the animation is different or the animation is finished, it will restart from the beginning. And remove `backward` option by separating method to `play_backward()`.

- `stop()` has a reset option, refer to the [AnimationPlayer API](https://docs.godotengine.org/en/latest/classes/class_animationplayer.html#class-animationplayer-method-stop).

And finally, place the playback button in SpriteEditor.

![image](https://user-images.githubusercontent.com/61938263/210683625-a99f6ed1-a5f1-4255-9f63-82aacecc487c.png)

I don't know if there is a need for multiple playback options, considering the current `playing` property implementation, just toggling the play button seems sufficient.

In the end, this change looks like the button to set the boolean value of playing would just be moved from the inspector to SpriteEditor except for the need to explicitly fire `play()` when creating the `AnimatedSprite`.

> except for the need to explicitly fire `play()` when creating the `AnimatedSprite`

And if necessary, an `autoplay` property could be added for that case. See also [AnimationPlayer::autoplay](https://docs.godotengine.org/en/latest/classes/class_animationplayer.html#class-animationplayer-property-autoplay).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

AnimatedSprite is core.

**Comment by Mickeon** [comment]
I have personally been busy but I'm going to give my personal 2 cents on this.

I think that consistency is good. This overall makes sense. However, I do still firmly believe that the current `stop` name is not very good for its current purpose. Taking inspiration from very, VERY basic playback controllers _(think of a remote, or your music player of choice, for example)_, there's three core commands that this API should expose for simplicity:

![image](https://user-images.githubusercontent.com/66727710/211078506-39f4aa3a-0877-4297-b5f8-257f694464f2.png)

**Play**, **Pause**, **Stop**.

To put it briefly, currently, `stop` behaves like the common "pause". This doesn't make much sense in the grand scheme of things.

Hence why, I would very much be in favour of something like the following, but across all of the playback API's:
- https://github.com/godotengine/godot/pull/66264

**Comment by Mickeon** [comment]
I'm aware it'd be compatibility-breaking and probably not something to be scheduled anytime soon, but I do believe it makes the API overall more consistent and easier to grasp. Even in the current API, a lot of things use `pause()` over `stop()`.

**Comment by TokageItLab** [comment]
The problem with pause() is that Node itself has a pause() api for stopping the process. It will cause confusion, so we recommend unifying it with stop(bool reset) if it does not imply stopping the process.

But in any case, those api proposals are off-topic here. You should open another proposal.

**Comment by TokageItLab** [comment]
Note: pause() has been added to AnimationPlayer and stop() api is working for stabilization now.

**Comment by Zireael07** [comment]
Awesome :fireworks:
