### ISSUE TITLE
Add static typing hint "Variant" to improve code clarity

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot-proposals#605]
**Describe the project you are working on:**
Proprietary information

**Describe the problem or limitation you are having in your project:**
Inconsistent static typing hints in GDScript, which do not aid the programmer to 
identify variant type variables, when their use is required.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add static typing hint called "Variant". Adding this would make the static typing hints uniform, so
I could add hints to all variables and clearly see, where I need to take into account Variants, when
debugging my code.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
func myfunc(myparam:Variant) -> Variant:
   var myvar:Variant = myparam
   return myvar
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
Cause static typing hints are hardcoded into engine source code.

**Comment by bojidar-bg** [comment]
This was also discussed in https://github.com/godotengine/godot/issues/26228.

**Comment by FaultyFunctions** [comment]
This would be a great addition to static typing.

**Comment by Calinou** [comment]
@FaultyFunctions Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Calinou** [comment]
This is now supported since the [new GDScript](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged) was merged, closing.

![image](https://user-images.githubusercontent.com/180032/93595430-05832180-f9b8-11ea-92b0-390eb05a44f4.png)
