### ISSUE TITLE
SceneTreeTween seek method

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#6058]
### Describe the project you are working on

Migrating to 3.5

### Describe the problem or limitation you are having in your project

Apologies if I'm being a bit dumb, but I'm moving away from Tween node to SceneTreeTween to allow 4.0 migration and there is no seek method. That's it really. 

set_speed_scale isn't really an alternative and seek is pretty important.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

provide means of moving the tween to a specific time

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

seek(time)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I have no idea

### Is there a reason why this should be core and not an add-on in the asset library?

You need to seek in a tween, for example a text reveal option, or skipping a tween to a certain cut scene point

**Comment by KoBeWi** [comment]
You can only seek forward using `custom_step()` method. Seeking backward is difficult to implement, because Tweens may have multiple steps.

**Comment by chucklepie** [comment]
In that case, my fault. Who came up with the name 'custom_step'. The most non-obvious name ever ;)

**Comment by KoBeWi** [comment]
Well, the method was meant as a way to manually process the Tween.
