### ISSUE TITLE
Provide bind constructor parameter for create_tween to make it function equivalently to Tween node/support inherit pause

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#6061]
### Describe the project you are working on

A 2D game stuck at 80% completion :)

### Describe the problem or limitation you are having in your project

I have moved to SceneTreeTween in 3.5 to pave the way to 4.0 and to avoid the unnecessary need to add a Tween node to the scene. My code then stopped working for a dialog box system.

After a lot of hunting, the problem was I was pausing the game to show my dialog and the dialog node pause is set to 'process' with all children set to inherit. So, given Tween was a node, it just paused, but with an instantiated object, SceneTreeTween didn't.

So, when you code your game and you call create_tween how do you know you might have a pause mode, or more to the point it means every time you create a tween you have to do something like this which seems very unnecessary and if not, you have the potential for lots of people breaking their code on moving away from tween nodes:

my_tween  = get_tree().create_tween().bind_node(self)

On top of that, there were other nodes added to this dialog mentioned above that also failed, so I had to essentially go through my entire code and just append 'bind_node(self)' to every call to make things work as they used to with Tween nodes.

I get why (well, not the 'TWEEN_PAUSE_BOUND' that seems to have replaced inherit), but there must be a better way?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Provide a means of injecting or automating/defaulting a tween bind on creation

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

One simple way is existing:
SceneTreeTween create_tween()

to be changed to:
SceneTreeTween create_tween(bind_node)

So you can pass in a binding as part of creation, i.e. instead of 
my_tween  = get_tree().create_tween().bind_node(self)

It could be:
my_tween  = get_tree().create_tween(self)

Or if in the back-end there is a means of knowing the parent just set create_tween to bind to the parent by default with a method/constructor parameter to unbind then it will mimic how Tween works.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but as above, it's counter-intuitive

### Is there a reason why this should be core and not an add-on in the asset library?

Tweens become part of a scene so should use parent bindings/pause mode.

**Comment by KoBeWi** [comment]
Node has a method `create_tween()` which creates the Tween and binds it to self.

**Comment by chucklepie** [comment]
ah, my mistake. I did read the doc, I must have just missed the relevance as I was just busy reading the examples in the SceneTreeTween and following what it was doing. tbh, the whole 'binding' bit, especially for variables, is slightly confusing. Well to me anyway :)
