### ISSUE TITLE
Remove auto compute floor velocity for move_and_slide

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot-proposals#6066]
### Describe the project you are working on

2D platformer with physics work with rigid body and kinematicbody.

### Describe the problem or limitation you are having in your project

When use move_and_slide, it automatically add floor constant velocity to the kinematicbody velocity. But in some use cases, we want to let kinematicbody can control how it interact with the staticbody with a constant velocity(e,g, a conveyor), like when the friction low or high, player should has different action, but it wont change the rigidbody interaction behavior.

And now the implemtation has some bugs either, it adds the floor velocity to kinematicbody when it just leaves, which will cause player will stick on platform when jumping if the staticbody is pushing player upwards. And the floor velocity just use the origin constant velocity without compute slide normal, which is mean a player stand on a rotated conveyor, the player's velocity,x = constant velocity.x, but it should has same speed along the conveyor surface.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

User can easily has total control of kinematicbody2d moving.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Complete remove the floor velocity add to kinematicbody velocity part, or expose a parameter to let user decide if they want it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

move_and_slide is internal function, cannot use addon or scripts to fix this.

### Is there a reason why this should be core and not an add-on in the asset library?

Addon wont fix this.

**Comment by AttackButton** [comment]
> When use move_and_slide, it automatically add floor constant velocity to the kinematicbody velocity. But in some use cases, we want to let kinematicbody can control how it interact with the staticbody with a constant velocity(e,g, a conveyor), like when the friction low or high, player should has different action, but it wont change the rigidbody interaction behavior.
> 
The godot 4 `AnimatableBody2D(3D)` has the `constant_linear_velocity` created just to use when you want a conveyor. It works very well.
