### ISSUE TITLE
Replace orthogonal shadow maps with perspective shadow maps

### ISSUE THREAD

**Issue by myaaaaaaaaa** [godotengine/godot-proposals#6071]
### Describe the problem or limitation you are having in your project

Orthogonal shadow maps provide less resolution closer to the camera, and upgrading to PSSM requires making a performance tradeoff.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Replacing orthogonal shadow maps with a PSM solution would allow for better utilization of shadow map resolution without affecting performance, allowing for higher quality shadows without having to upgrade to PSSM.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See relevant papers below

https://www.researchgate.net/publication/220852877_Light_Space_Perspective_Shadow_Maps
https://www.researchgate.net/publication/220853011_Anti-aliasing_and_Continuity_with_Trapezoidal_Shadow_Maps

### If this enhancement will not be used often, can it be worked around with a few lines of script?

PSSM can be used for even higher quality shadows for developers who don't mind the increased hardware requirements.

### Is there a reason why this should be core and not an add-on in the asset library?

It's easier (presumably) to replace orthogonal shadow mapping with PSM than to refactor all of it out

**Comment by myaaaaaaaaa** [comment]
See relevant papers below

https://www.researchgate.net/publication/220852877_Light_Space_Perspective_Shadow_Maps
https://www.researchgate.net/publication/220853011_Anti-aliasing_and_Continuity_with_Trapezoidal_Shadow_Maps

**Comment by myaaaaaaaaa** [comment]
After further investigation, the PSM family of techniques (PSM, LiSPSM, TSM below) appears to be behind PSSM in terms of quality. While there would still be value in implementing them as a replacement for the current orthogonal shadow maps (referred to as SSM below) as they offer better quality for the same performance, given the more complicated math involved, I'm not convinced that it's a good use of developer time compared to focusing on raytraced shadows.

![1673330585](https://user-images.githubusercontent.com/103326468/211473689-d0989b31-fcc7-4315-80a5-224d3a9d89f8.jpg)

**Comment by clayjohn** [comment]
We already use PSSM with 4 sections by default. Orthogonal shadow maps are totally optional.

**Comment by myaaaaaaaaa** [comment]
Unlike PSSM, the PSM family of techniques perform identically to orthogonal [since they all render to a single warped shadow map](https://slideplayer.com/slide/14000490/). This issue is essentially proposing it as a drop-in replacement for orthogonal as a free quality improvement for low end settings, sorry for being unclear about this.

Although I did originally open this because I thought PSM would have higher quality than PSSM with the same cost as orthogonal, which would have made it worth pursuing. But after further investigation, it turns out that its quality is actually between orthogonal and PSSM, as you can see in the above comparison.

The performance gap also isn't particularly big:
![image](https://user-images.githubusercontent.com/103326468/211605774-47660e99-fa8d-46b9-9471-ce7d56615da9.png)
[(Source)](https://www.researchgate.net/publication/220805307_Parallel-split_shadow_maps_for_large-scale_virtual_environments)

Knowing this, I think it's better for anyone who wants higher quality shadows to just upgrade to PSSM and accept the performance hit, and developers should probably focus on more important things like raytraced shadows.

I'll leave the final decision to you on whether to close this or keep it open just in case an independent contributor is interested :slightly_smiling_face:

**Comment by Calinou** [comment]
Godot 2.x supported perspective shadow maps, but they were removed as they only worked well for games where the camera *never* faces the sun directly (or directly away from it). Otherwise, the effective shadow resolution plummets to unusable levels.
