### ISSUE TITLE
Implement associated data for enums

### ISSUE THREAD

**Issue by jordigcs** [godotengine/godot-proposals#6076]
### Describe the project you are working on

A 2D RPG Game with a battle system that needs to handle complex states.

### Describe the problem or limitation you are having in your project

Enums have the potential to be a lot more useful. Right now, enums don't do much but allow you to group const ints. Making enums more rust-like will allow for cleaner code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Enums can still be a Dictionary, but allow Enum values to have associated data. Enum values will then be their own Variant type that can only be constructed as part of the enum they're associated with.

This is beneficial because your code is coupled and easy to read. You don't have to define variables that are only needed by one state. Read: [Rust Enums By Example](https://dwbrite.com/blog/post/rust%20enums%20by%20example )

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An example of limitations and syntax
```gdscript
enum Animal {
    DOG, # 0
    # Enum variants with values. Only the type's names need to be defined here.
    # Variants with values cannot be assigned a value. (ex: NEITHER is set to -1)
    PERSON(String, int), # 1
    NEITHER = -1,
}
var animal:Animal = Animal.DOG;
@export var inspector_animal:Animal; # Cannot be exported because the enum contains associated data.

func test():
    assert(animal== 0); # true
    animal = Animal.PERSON("John", 21);

    # When using the enum variant without constructing it, it'll return the enum index associated with it.
    assert(animal == 1); # true
    assert(Animal.PERSON == 1); # true
    assert(animal == Animal.PERSON); # true
   
    # Accessing an enum variant's values can only be done through destructuring for safety.
    print(animal.name): # Error: Must use `match`
    print(get_name(animal)); # John

func get_name(animal:Animal) -> String:
   # Enum destructuring
    match animal:
        Animal.PERSON(var name, _):
             return name;
        _:
            return "";
```

An example of how this would be useful for my use-case:
```gdscript
class_name BattleManager

# Coupled data that is easy to read and understand
enum State {
    PLAYER_TURN(Player),
    ENEMY_TURN(Enemey),
    GAME_OVER,
    VICTORY(int), # int: Coins gained
}

var state:State;
var enemies:Array; # Array of enemies, Implementation hidden

func parse_state():
    match state:
	State.PLAYER_TURN(var player):
		await player.attack();
		var coins_gained:int = 0;
		for i in enemies:
			if i.is_alive():
				return;
			coins_gained += enemies.coin_gain;
		state = State.VICTORY(coins_gained);
		parse_state();
		return;
        State.ENEMY_TURN(var enemy):
		await enemy.attack();
		# etc, etc
        ...
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Technically yes, using Variant, but you don't have any type safety besides using the `is` operator everywhere, cluttering your code. You also don't have the benefits of enums.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by YuriSizov** [comment]
This looks interesting, but breaks the simplicity and familiarity of enums. It also negatively affects their ability to be edited in the inspector or serialized. There are probably better ways to organize your code to pass typed associated data together.

**Comment by jordigcs** [comment]
Thanks for your input!
