### ISSUE TITLE
Sprite Overlays

### ISSUE THREAD

**Issue by SpyrexDE** [godotengine/godot-proposals#608]
**Describe the project you are working on:**

I am working on a pixel-art top-down shooter with focus on animations.

**Describe the problem or limitation you are having in your project:**

I want to make sprite overlay animations. But Godot is only able to do that using shaders, what realy is a pity.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

There could be a feature for that like how it is in GameMaker: (https://www.youtube.com/watch?v=ZrvKmDpVP6I) or maybe a "Sprite Overlay"-Node. I would prefer the second option.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

 The "Sprite Overlay"-node could be a node you can put as a child on a Sprite-Node. It inherits from the normal sprite node and there could be some extra options I don't know at the moment because I am extremely new to programming.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I saw a lot of Indiegames using sprite overlays. But depending on the engine they are used more often because there is a feature like this. It would help a lot of people to develop their games. I 
 already asked for a sloution on reddit(https://www.reddit.com/r/godot/comments/flshso/is_there_a_way_to_create_sprite_overlays_in_godot/) but only received a way to do that with shaders. And when you do it in that way you are not able to animate the sprite overlay. 

**Is there a reason why this should be core and not an add-on in the asset library?:**

Because it is an elemental feature you can use in nearly every game. In addition to that you can include it into the node/scene-system what effect, that you can put overlays on overlays, animate/tween them or get the input  the overlays received.

**Comment by Jummit** [comment]
I think this should be a blend mode of CanvasItemMaterial.

**Comment by Xrayez** [comment]
> I think this could be a blend mode of CanvasItemMaterial.

Related proposal: #470.

**Comment by avencherus** [comment]
Not exactly sure, but isn't this masking?  Would be great to have built-in, I agree, would save a lot of time.
