### ISSUE TITLE
Non-Y sort

### ISSUE THREAD

**Issue by SlugFiller** [godotengine/godot-proposals#6080]
### Describe the project you are working on

Spine import plugin

### Describe the problem or limitation you are having in your project

Objects are generally drawn in the order they appear in the tree. However, you do not always want objects drawn in the same order, as animated bits and pieces can go in front or behind other elements.

`YSort` allows changing the drawing order of child elements, but only based on their Y value.

Z-index allows causing elements to draw in a different order, but this is global, not local to a parent, so if you try to re-order elements inside a game object, they end up in front or behind of other game objects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a SortChildren2D element. It would have an `order` variable, which is a PoolIntArray, which is the permutation of children.

Setting `order` to an array that is not the same size as the number of children, or one that does not contain all the numbers from 0 to the number of children minus 1, would either be undefined behavior, or should simply turn off sorting.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For instance, for the scene tree:
```
SortChildren2D
-Sprite1
-Sprite2
-Sprite3
```
If the `order` variable is set to `[2,0,1]`, `Sprite3` would be drawn behind the other two, while `Sprite2` would be drawn in front of the other two.

(P.S. Why is this entry separate from the above one? I always get confused as to how to split a request into the two)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's possible to reorder the children in the tree itself. However:
-It's difficult to keep track of the original order of the children in order to consistently apply permutations.
-It modifies the tree itself, and hence any assumptions that could be made about process ordering, or other aspects of tree order. For comparison, `YSort` influences only the render order.

It might also be possible to solve this with `CanvasGroup` combined with z-index, but that would mean allocating a back-buffer just for the sake of changing a drawing order.

### Is there a reason why this should be core and not an add-on in the asset library?

It's impossible to directly manipulate rendering order from an add-on without manipulating the tree.

**Comment by dalexeev** [comment]
![](https://user-images.githubusercontent.com/47700418/212022828-4b1e5eae-8953-4ece-9fce-31f2782749bc.png)

**Comment by SlugFiller** [comment]
@YuriSizov Setting a padding in Z-index would mean having to set Z-index for every element in every scene in the game (simply letting the tree order sort out 99% of the elements is no longer an option). And you'd need to know in advance how much padding is needed. This would be insane to maintain. It completely undermines the concept of self-contained children/scenes that can be inserted anywhere. Also, if you wanted to cascade this (That is, emulate a sort inside a sort), you'd need to make the padding exponential, so you can have more sorted items stored inside other sorted items.

@dalexeev I'm not sure what you were trying to point out there, but I tested Z-index with relative, and the issue is that Z-index for all elements (including the parent, to which the Z-index is relative) is 0 by default, not an incremental value. Even if you take the bottom most element, and set its Z-index to relative+1, it will go on top of every object in the scene, including later children of any ancestors.

As far as I can tell, unless it's a bug, Z-index is intended for HUD elements, not for re-ordering game elements.

**Comment by YuriSizov** [comment]
> Setting a padding in Z-index would mean having to set Z-index for every element in every scene in the game

Quite the opposite. The purpose of padding is to give your core branches specific, spread apart values, and use tree order and relative z-indices for the rest. It works perfectly fine in practice.

> simply letting the tree order sort out 99% of the elements is no longer an option

I don't see why not.

> And you'd need to know in advance how much padding is needed. This would be insane to maintain.

You would need to make an educated guess, and it does rely on hardcoded values (which many aren't happy with and there are proposals to make those values more organized), but it's not insane at all. You don't need this too often to use truly large numbers, you mostly only need it to separate different major planes. For individual nodes in your scene some occasional overlap wouldn't be an issue in a released project.

> Even if you take the bottom most element, and set its Z-index to relative+1, it will go on top of every object in the scene, including later children of any ancestors.

It's just simple addition/subtraction. The branch that you give +1 will have whatever value was before it + 1. Siblings of this branch would still have the base value, and so yes, the branch will be displayed on top of them.

- Root (10)
  - Child 1, +1 (11)
    - Subchild 1, 0 (11)
    - Subchild 2, -1 (10)
  - Child 2, 0 (10)
  - Child 3, -1 (9)

**Comment by SlugFiller** [comment]
@YuriSizov Either your'e not following, or I'm not following. With the difference that I actually made a test project, filled it with colored `Polygon2D`s, and actually tested how Z-index behave.

From the moment your example has "10" as the root, it's an unorthodox example. The default for all nodes is "0". If you want to move just one element using Z-index, you have to set a Z-index for all elements in the scene.

Here's a more practical example

- Root
  - Game
    - Background
    - NPC 1
      - Rear arm
      - Rear hand
      - Rear leg
      - Body
      - Head
      - Front leg
      - Front arm
      - Front hand
    - NPC 2
      - Rear arm
      - Rear hand
      - Rear leg
      - Body
      - Head
      - Front leg
      - Front arm
      - Front hand
    - NPC 3
      - Rear arm
      - Rear hand
      - Rear leg
      - Body
      - Head
      - Front leg
      - Front arm
      - Front hand
    - Player
      - Rear arm
      - Rear hand
      - Rear leg
      - Body
      - Head
      - Front leg
      - Front arm
      - Front hand
    - Shot 1
    - Shot 2
    - Shot 3
    - Shot 4
    - Hud
  - Menu
    - Menu item 1
    - Menu item 2
    - Menu item 3
    - Menu item 4

Now suppose you want NPC 2 to scratch his head with his front hand, so you need the front hand to move behind the head during the scratch animation. If you give the head a +1, it will become in front of all other NPCs, the player, the shots, the hud, and even the menu. If you give the hand a -1, it goes behind the background.

To prevent this, you need to give incremental Z-indices to literally every object in this scene. To create "padding", you need each NPC and shot to add around 10 to the Z-index, while Menu should be about 1000 above the game, to avoid any shots getting on top of it. Basically, you now need to manually manage the Z-indices of each node in the entire tree, instead of having it managed automatically by virtue of, you know, it being in the form of a tree.

**Comment by YuriSizov** [comment]
> From the moment your example has "10" as the root, it's an unorthodox example. The default for all nodes is "0". 

That's not unorthodox, it's just to demonstrate the workings better, and that's also how you add padding that I've been mentioning before. You uncheck `z_as_relative` and give the root of your branch a big number. That way you establish a large gap that nodes _below_ your branch can play with (using positive relative z-indices), and that _children_ of your branch can utilize with negative relative z-indices.

With 2D projects in Godot you don't actually maintain base index 0 throughout. It is normal to disable relative z-index and give your branches more spaced out base values.

> Here's a more practical example

You would have your background at 100, your characters and effects at 200, and your menu at a separate CanvasLayer (which acts like a second level of z-sorting, with each layer being sorted internally, and all layers being sorted according to their own layer index).

**Comment by dalexeev** [comment]
Sorry, you're right. `z_as_relative` does indeed work on simple addition/subtraction, and `z_index` is still global, not constrained relative to the parent (the closer to the root, the larger the `z_index` values should be).

> Add a SortChildren2D element. It would have an `order` variable, which is a PoolIntArray, which is the permutation of children.

The closest thing to what you're asking for are the `show_behind_parent` and `show_on_top` properties:

![](https://user-images.githubusercontent.com/47700418/212063306-f3fd3bf0-07fc-4caa-a16a-5a8c5a0d7ec5.png)

I think a new property (say `order_in_parent`) could solve your problem (default is `0`, equal values means use tree order, `show_behind_parent = true` means `order_in_parent = MIN_ORDER_IN_PARENT`, `show_on_top = true` means `order_in_parent = MAX_ORDER_IN_PARENT`). This is similar to the [`order`](https://developer.mozilla.org/en-US/docs/Web/CSS/order) CSS property. In my opinion, this is better than the proposed `SortChildren2D` (since there is no need to keep track of the array's correspondence to children). The only question is how `order_in_parent` should work with `z_index`.

Another possible solution is to change the order of the children in the parent, see the `Node.move_child()` and `Node.raise()` methods.

**Comment by SlugFiller** [comment]
@YuriSizov You don't have "characters and effects at 200", you need each character, and each effect at a different Z-index, with a significant gap, so that you can have wiggle room for the body parts of each character. If you then have a character spawner, or have the characters fire shots, you need to assign a unique Z-index for each new spawn object. If you also had a regular Y-sort on the characters, or maybe a tilemap, then you're screwed, because you'd need to reimplement the whole thing with Z indices. It is not a sustainable solution.

It is NOT normal to set a spaced Z-index for each individual entity and character in your game.

@dalexeev I mentioned that it's possible to reorder children (e.g. with `move_child`), but the issue is that you lose track of what their original order was. Going to the same example I gave @YuriSizov above, when the character finishes scratching their head, you want their hand to go back to where it was. Also, moving children around can't be done directly from `AnimationPlayer`, and has to be done through a proxy script.

I don't think a per-child `order_in_parent` is good, because it becomes ambiguous. With a permutation array, you can require that no index repeats twice. For `order_in_parent` to be unambiguous, I have to set a unique value for every child of the parent, which may be miles better than setting a Z-index for every node in the scene, but is not any better than setting a single array on the parent.

I also don't think this should be a behavior that is applied to every node. The vast majority of nodes do not need to be reordered within their parents. Also, since you compare it to `show_behind_parent`, it gets even more complicated if the parent is not a "pure" `Node2D`, but rather a `Sprite` or `Polygon2D`, or, worst case scenario, `YSort`. The issues range from "Where does the parent's draw fit in the sort" to "Which of the sorts wins". Most of the elements in the scene are not going to require special sorting, so making a parent that does have specially-sorted children be marked as different from other parents, and also be forced to be a non-drawing parent, makes more sense.

**Comment by Zireael07** [comment]
> @YuriSizov You don't have "characters and effects at 200", you need each character, and each effect at a different Z-index, with a significant gap, so that you can have wiggle room for the body parts of each character.

Why do you need "wiggle room for body parts"? I'm confused. I'm using Z index in my own space game to make ships/planets/whatever else be arranged in a sensible order, and don't recall having any problems.

**Comment by YuriSizov** [comment]
@SlugFiller You assume that it's important that each character is shown on their own plane and never clips over any other character who is supposed to be in front/behind them. Maybe you're right and it's important for your project, but then you should probably use 3D with an orthographic camera, just like in any other engine. That will give you the most control with the least amount of hassle, and the game would still look 2D.

What I'm trying to say that in practice it's not that important that each character has its own plane; that Y-sort and having a hand at z-index -1 or +1 sometimes clipping with other characters is not a big deal; and that many games have these quirks without any impact to the perceived quality.

**Comment by dalexeev** [comment]
> I don't think a per-child `order_in_parent` is good, because it becomes ambiguous. With a permutation array, you can require that no index repeats twice. For `order_in_parent` to be unambiguous, I have to set a unique value for every child of the parent

I see a much bigger problem in having an array of numbers that is not directly related to the children, but must match them. This is inconvenient to work with in the editor and requires additional checks in the user code: adding/removing a child, checking the type if some node is not a `Node2D` (`CanvasItem`).

When working with `order_in_parent` , you separate the children into several "layers", and you can switch the "layer" by changing `order_in_parent` (and you can also easy switch the "layer" back). It's the same `z_index` but limited to the parent, a way to change the order without changing the index.

With the same `order_in_parent` for several nodes, the index in tree is used. I don't see a problem with this and I think the requirement of no repetitions is unnecessarily strict. One of your problems with indexes is that when you change the index of one child, the indexes of some of the other children automatically change as well. This is why you have difficulty returning the node to the old "layer". With `order_in_parent` it should be easier:

![](https://user-images.githubusercontent.com/47700418/212083207-54b67cd2-a58c-46ec-88a7-9b2f86aaad29.png)

**Comment by SlugFiller** [comment]
@Zireael07 I gave a practical example: Character scratches their rear cheek with their front hand. During the scratching animation, the hand needs to be behind the head. But, if they instead do a Home Alone "surprised face", then the hand needs to be in front of the head.

If all you're doing with Z-index is ensuring that planets are behind ships, then a global Z-index is fine, but so would having a different parent for planets vs ships. Unless you face a situation where one specific ship needs to be above others (but not above shots), or one specific part of the ship needs to be temporarily behind it, you're not really having the same situation. Honestly, "space game" is actually a rather extreme example, because you're also not using `Skeleton2D`, and probably hardly using `AnimatedSprite`, either one of which would be considered a common tool.

@YuriSizov Characters each appearing in their own plane is the common way 2D games work. I have a hard time thinking of any 2D game I've played where characters are "interleaved" with each other. Normally, it would look like a bug if a character is scratching their own hand, but suddenly it is drawn behind another character's back, making it look like it got cut off the arm. But that's exactly what you'd end up with orthogonal 3D.

I'd honestly want to know which "many games" have that quirk, because I don't recall ever seeing one. At least, not one that was sold commercially.

@dalexeev 
> One of your problems with indexes is that when you change the index of one child, the indexes of some of the other children automatically change as well. This is why you have difficulty returning the node to the old "layer".

In a workaround where children are literally moved in the tree, I have a problem moving them back, because their previous location isn't stored. If an array was used, moving them back would be as simple as setting it to `[0, 1, 2, ..., get_child_count()-1]`

But consider this: What happens if you have a `YSort`, and one of its children has an `order_in_parent` set? The `YSort` wants the node in one position, but the `order_in_parent` wants it in a different one. How is this resolved?

Also, suppose all I want to do is swap two adjacent nodes. In an `order_in_parent` situation, if the default for all children is 0 (same as Z-index), Setting any one of them to +1 or -1 would make it go above or below all of the others. I first need to set incremental numbers for all children, and only then swap the two I wanted to swap. Meaning I _already_ need to be aware of all of the parent's children anyway. So, the need to keep track of all the children is not removed compared to an array, merely obfuscated. The array makes the situation clear: Yes, you need to set a value for _every_ child. You can't skip one.

The only way for a swap to be applicable to only one node, is if `order_in_parent` is relative to an automatically calculated incremental value of the original tree order. But then, calculating that value would be extra strain on the engine, which, due to the feature being applied indiscriminately to every node, would be extra effort on the engine even in games where the feature is unused.

By contrast, making it a special node type on the parent, means that games that don't need it, or parts of the game that don't need it, simply don't use it. It's also consistent with how `YSort` is used.

The core issue is the same as with Z-index: The default is 0 for all nodes, not 1, 2, 3, 4.

**Comment by Zireael07** [comment]
> @Zireael07 I gave a practical example: Character scratches their rear cheek with their front hand. During the scratching animation, the hand needs to be behind the head. But, if they instead do a Home Alone "surprised face", then the hand needs to be in front of the head.

Relative Z index is a property like anything else - animate it so that for the rear, the relative Z of the hand is lower than the head (which can likely stay 0, i.e. same as parent character) and for the face, the relative Z is higher.

**Comment by SlugFiller** [comment]
@Zireael07 I explained it again and again above, but I'll do it one more time, just for you. The default Z for all nodes is 0. Relative Z is relative to the Z of the parent, which is, by default 0. If you set a relative Z to -1, the node you set it to now has an absolute Z of -1, while every other node in the game has a Z of 0, means the node is now behind literally everything in the game.

Going back to my example, if you merely want the hand to go behind the head, and nothing else, you first need to realize that a character's head is the same Z as every other object in the scene, including other body parts of the character, other characters, and even other elements like background, etc. To create a space that's "between" the head and everything that is drawn behind it, you not only need to set a Z value for the head, you need to set a Z value for every object in the game, to make sure every object is either strictly in front of or behind of the hand and head. If your game has 100 characters on the screen, and each of these characters could scratch its head, then each of these 100 characters needs to have a different Z-index set (with enough of a gap to allow the head and hand to have wiggle room), so they don't clash with each other.

**Comment by Zireael07** [comment]
Sounds like you should be using 3d not 2d if you want that level of Z fidelity (because you can't get that even with assigning every character scene a different Z, you don't get enough gaps)

**Comment by dalexeev** [comment]
I think you can implement the proposed `SortChildren2D` using `move_child` and not changing `z_index` at all. It seems to me that this suggestion is too specific to your project, and that it is unlikely to be useful for most users and different use cases in the way it is described (with an array of numbers).

**Comment by dalexeev** [comment]
Another possible solution is the `VisualServer.canvas_item_set_draw_index method()`. For example:

```gdscript
onready var sprite_a: Sprite = $Node2D/SpriteA
onready var sprite_b: Sprite = $Node2D/SpriteB
onready var sprite_c: Sprite = $Node2D/SpriteC

func _ready() -> void:
    VisualServer.canvas_item_set_draw_index(sprite_a.get_canvas_item(), 2)
    VisualServer.canvas_item_set_draw_index(sprite_b.get_canvas_item(), 1)
    VisualServer.canvas_item_set_draw_index(sprite_c.get_canvas_item(), 0)
```

**Comment by SlugFiller** [comment]
@Zireael07 In 3D, the same problem would persist: The depth range is shared, and there's no mechanism for "allocating" depths to sprites, so one would have to be written and applied to the entire scene. A solution is only possible in 2D, where it's simply a matter of drawing things in a different order.

Yes, trying to force Z-Index as the solution would not work, due to the need for many gaps. That's why I'm requesting a solution that WOULD work.

@dalexeev A couple of tests show that `VisualServer.canvas_item_set_draw_index` does work as expected. So this removes the "add-on" argument above, assuming that `VisualServer.canvas_item_set_draw_index` is a stable API that won't be unexpectedly deprecated.

Actually, I was able to use it to implement a custom `SortChildren2D` that seems to work as expected, so I'm going to go ahead and close this.
