### ISSUE TITLE
Expose LineEdit selection begin and end

### ISSUE THREAD

**Issue by olivergs** [godotengine/godot-proposals#61]
**Describe the project you are working on:**
An editor for interactive fiction stories based on Godot UI

**Describe how this feature / enhancement will help your project:**
I will be able to get currently selected text at a LineEdit so I can manipulate text if needed (wrapping, replacing)

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
No mockup. Just functions to access data from scripts

**Describe implementation detail for your proposal (in code), if possible:**
Just add two methods that returns current LineEdit selection struct begin and end fields

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
RIght now the selection struct is private so I can not get the information from scripting

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is a very basic function for general use.

**Comment by me2beats** [comment]
I need this too. I'm creating a plugin that should know current selection of a LineEdit node.
Surprisingly I haven't found a way to get the selection.

As I can see, selection is a struct,
https://github.com/godotengine/godot/blob/e92064fbef13e651722ee47ae826de080757bc2e/scene/gui/line_edit.h#L131
so I think 2 methods could be added:
`int get_selection_start()` and `int get_selection_end()`
`get_selection_start()` could be also named `get_selection_begin()`

they also could be named
`get_selection_from()` and `get_selection_to()` (simirarly to `TextEdit` methods)
