### ISSUE TITLE
Change "Quit" shortcut "CTRL+Q" to maybe "CTRL+SHIFT+Q"

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot-proposals#6100]
### Describe the project you are working on

Not relevant
Godot 4 Beta 12

### Describe the problem or limitation you are having in your project

I don't know maybe I am weird, but I press CTRL + Q accidentally a lot when for example I am trying to press CTRL + A (to add node). That shortcut makes editor Quit without asking YES/NO.

Also at the beginning I just thought that Godot crashed when trying to add node....

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I can change it to whatever I want, but I though that maybe we should change it globally for everyone to for example CTRL+SHIFT+Q?

CTRL + A is used a lot in Godot and to have quit shortcut right next to it is kinda bad idea in my mind.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change it to CTRL + SHIFT + Q or smth else.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by MewPurPur** [comment]
I agree that disruptive shortcuts should be harder to press. For me that's Ctrl+Q and Ctrl+W. Thing is, both of these do already have a useful Ctrl+Shift variant.

**Comment by Calinou** [comment]
<kbd>Ctrl + Shift + Q</kbd> is already used for quitting to the project list.

**Comment by KoBeWi** [comment]
Ctrl+Q is a common quit shortcut.
But it's also useless, because Alt+F4 already exists. Maybe we should just remove the bind?

**Comment by Calinou** [comment]
> But it's also useless, because Alt+F4 already exists. Maybe we should just remove the bind

<kbd>Alt + F4</kbd> doesn't exist on macOS, but <kbd>Cmd + Q</kbd> is the default shortcut for quitting on macOS anyway (per Apple convention).

**Comment by sairam4123** [comment]
Why was confirmation removed? Or it is just not being shown? Showing the confirmation dialog should atleast be a partial fix for this issue?

**Comment by Calinou** [comment]
> Why was confirmation removed? Or it is just not being shown? Showing the confirmation dialog should atleast be a partial fix for this issue?

See https://github.com/godotengine/godot/pull/32321.

**Comment by SlugFiller** [comment]
Is no one going to point out that you can just go to Editor->Editor Settings->Shortcuts, and change it?

I don't see a reason to change something in the code that can be changed in 3 seconds of going through the settings. That's what settings are for. And it's global settings, at that, so you don't even have to change it per project.
