### ISSUE TITLE
I think Tutorials are great, there should premade walkthroughs, if there isn't already.

### ISSUE THREAD

**Issue by SirenWhale** [godotengine/godot-proposals#6106]
### Describe the project you are working on

Hi there!
This may be silly, but when I go to learn how to use the engine, I find one thing missing.
A previous engine I used was GB Studio, which came with a sort of tutorial where there is a premade game for you to observe.
Does Godot have something like this? Not a template but a step by step walkthrough?

When I first started with Godot, it gave the impression that I already should know what is expected. If I didn't have internet, I wouldn't be able to see the tutorials from youtube or see the Godot docs. So I think in the next version of Godot, there should be a beginner friendly tutorial that has stuff built in. 

There's a lot of buttons and whistles on Godot compared to my old engine, so if a tutorial could be used over and over when I forget something, that would help too.

### Describe the problem or limitation you are having in your project

Tutorials online are troublesome, I think built in tutorials made by Godot would help me achieve my goals.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Built in Tutorials should be standard for Godot, it is for GB Studio, and GB Studio is less powerful.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not a expert programmer, so I can't really explain with code.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Perhaps putting a yes or no option would let you skip the tutorial if starting a new project.

### Is there a reason why this should be core and not an add-on in the asset library?

It should be a core feature for beginners, or devs that used another engine. Not an add-on asset, because it should be built in.

**Comment by YuriSizov** [comment]
Godot comes with multiple demo projects, which you can download from the Asset Library, or directly from GitHub: https://github.com/godotengine/godot-demo-projects (If you use a Steam version, they also come pre-downloaded).

For a step-by-step walkthrough there is a perfect tutorial in the official documentation, https://docs.godotengine.org/en/stable/getting_started/step_by_step/index.html. There are also many third-party guides for people who are just starting out.

The number of features in Godot is vast, and the variety of projects you can make with the engine is practically unlimited. So it's basically impossible to provide some kind of example project that would demonstrate most of it, and picking what's important for you on your behalf is counter-productive (we don't know what kind of game or app you want to make). So we recommend playing around with demo projects if you want some hands-on experience, and following tutorials, guides, or courses if you want to learn the engine step by step. There is no one single path that everyone should or need to take. Find what makes sense for you.
