### ISSUE TITLE
Make it possible to run a game without sound

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot-proposals#6108]
### Describe the project you are working on

Any game that has sound

### Describe the problem or limitation you are having in your project

Other engines provide the ability to mute the game when hitting play from within the editor. Godot doesn't do this. I (and I'm sure many other) developers like to work on games with some relaxing music on in the background when I don't have to work on audio features. This can get really annoying really quickly when working on a game that has its own music. A "simple" workaround for this is to turn off sound in the mixing panel, but I don't want to run the risk of pushing such a change to my team.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

An editor setting or a little checkbox near the play buttons in the top right would be the perfect way of dealing with this.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An editor setting or a little checkbox near the play buttons in the top right would be the perfect way of dealing with this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used all the time

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think this is easily done from an add-on, it would become an integral part of any game for it to work through an autoloaded script which isn't desirable.

**Comment by Calinou** [comment]
This is already feasible using the `--audio-driver Dummy` command line argument. You can add this to the **Editor > Main Run Args** project setting to make this only effective when running the project from the editor.

**Comment by robbertzzz** [comment]
Adding the command line argument to the project settings will have the same effect of it being potentially synced with other team members, so that's not a viable solution.
