### ISSUE TITLE
Scene Tree Timer Process Optimization

### ISSUE THREAD

**Issue by MrSametBurgazoglu** [godotengine/godot-proposals#6113]
### Describe the project you are working on

This optimization is for engine not for a game.

### Describe the problem or limitation you are having in your project

I looked godot's source code and I learned how scene tree timer working. I think we need a better idea for processing scene tree timers. Let me explain. This is how scene tree timer works now:

![scene tree timer progress](https://user-images.githubusercontent.com/16630690/212841960-f12fc5e8-e0a7-459f-87db-be36299db33e.png)

We look at each timer one by one to see if it has expired. I think this can be done by only looking one of them.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If this optimization can be implemented I think we can handle timers in scene more smoothly.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If we can order the timers then we don't need to look all of them. We only need to ask the first one "Did you finished" if it is not finished then non of them can be finished.
![New System drawio](https://user-images.githubusercontent.com/16630690/212842707-fa4a3f6a-9656-4c07-aad8-4ebf2964639c.png)

For this implementation we don't need to hold their left time. We need to hold difference left time between front of them.

I am not experienced in godot engine source code but I write some code to explain how system works.

For  creating timer
```
Ref<SceneTreeTimer> SceneTree::new_create_timer(double p_delay_sec, bool p_process_always, bool p_process_in_physics, bool p_ignore_time_scale) {
	Ref<SceneTreeTimer> stt;
	stt.instantiate();
	stt->set_process_always(p_process_always);
	stt->set_time_left(p_delay_sec);
	stt->set_process_in_physics(p_process_in_physics);
	stt->set_ignore_time_scale(p_ignore_time_scale);

	double cumulative_time = 0.0;
	bool timer_added = false;
	List<Ref<SceneTreeTimer>>::Element *L = timers.back(); //last element
	for (List<Ref<SceneTreeTimer>>::Element *E = timers.front(); E;) {
		List<Ref<SceneTreeTimer>>::Element *N = E->next();
		if ((paused && !E->get()->is_process_always()) || (E->get()->is_process_in_physics() != p_physics_frame)) {
			if (E == L) {
				break; //break on last, so if new timers were added during list traversal, ignore them.
			}
			E = N;
			continue;
		}
		if(p_delay_sec > cumulative_time){
			cumulative_time += E->get()->get_time_left();
		}
		else if(!timer_added){
			stt->set_time_left(cumulative_time-p_delay_sec);
			timers.insert_after(E, stt);
			timer_added = true;
		}
		else{
			double time_left = E->get()->get_time_left();
			time_left -= cumulative_time-p_delay_sec
												   E->get()->set_time_left(time_left);
			break;
		}
	}
	return stt;
}
```
For processing timers
```
void SceneTree::new_process_timers(double p_delta, bool p_physics_frame) {
 list will be sorted so the first one is the closest one to end
	List<Ref<SceneTreeTimer>>::Element *L = timers.back(); //last element
	List<Ref<SceneTreeTimer>>::Element *F; //first element
	List<Ref<SceneTreeTimer>>::Element *S; //second element

	for (List<Ref<SceneTreeTimer>>::Element *E = timers.front(); E;) {
		List<Ref<SceneTreeTimer>>::Element *N = E->next();
		if ((paused && !E->get()->is_process_always()) || (E->get()->is_process_in_physics() != p_physics_frame)) {
			if (E == L) {
				break; //break on last, so if new timers were added during list traversal, ignore them.
			}
			E = N;
			continue;
		}
		if (!F){//if first one is null
			F = E;
		}
		else{// if second one is null
			S = E;
			break;
		}
	}
	double time_left = F->get()->get_time_left();
	if (F->get()->is_ignore_time_scale()) {
		time_left -= Engine::get_singleton()->get_process_step();
	} else {
		time_left -= p_delta;
	}
	F->get()->set_time_left(time_left);
	if (time_left <= 0) {
		F->get()->emit_signal(SNAME("timeout"));
		if(S){
			time_left = S->get()->get_time_left();
			time_left += F->get()->get_time_left();
			S->get()->set_time_left(time_left);
		}
		timers.erase(E);
	}
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is possible to implement this system by using an autoload script, one timer and few scripts.

### Is there a reason why this should be core and not an add-on in the asset library?

I am not sure how many people use scene tree timer in their games. But if we can implement this optimization it can also be done for timer node and tweens.

**Comment by Flynsarmy** [comment]
You'll need to reorder your list when timers are paused, resumed, or have their durations changed.

**Comment by MrSametBurgazoglu** [comment]
I didn't know that scene tree timers can be paused. Even if they can be paused all we have to do increase the remaining time of the stopped one and decrease the remaining time of the next one. And if they need to swap just swap these two timer. Isn't it better than current process?

**Comment by TheDuriel** [comment]
What does this achieve for users of these timers?...

**Comment by KoBeWi** [comment]
Nothing. SceneTreeTimer already have excellent performance. With this optimization you can have e.g. 1000000 of them instead of 100000, which doesn't really make difference xd

**Comment by Flynsarmy** [comment]
While it probably won't result in a noticeable performance boost, his idea is good and shouldn't be scoffed at. He's turning an order n operation to an order 1. That can only be seen as a good thing.

**Comment by KoBeWi** [comment]
Except it complicates the code.

**Comment by Flynsarmy** [comment]
Not by much. He's just keeping an ordered list and popping the front one off on timer expiry. If the code is commented explaining what's going on and the reasoning for it (which is what should be done in all scenarios) it's really not adding a lot of complexity forthe benefit it's giving.

**Comment by TheDuriel** [comment]
There is 0 benefit, but X complexity.

Complexity great enough to require explaining and commenting. Sounds like it outweighs the benefit by quite a bit.

**Comment by Zireael07** [comment]
O(n) to O(1) sounds like a benefit though?

**Comment by TheDuriel** [comment]
No actually https://www.youtube.com/watch?v=o4-zpAI7qBc

**Comment by Zireael07** [comment]
Thanks for claryfying

**Comment by MrSametBurgazoglu** [comment]
I don't think it is complex.

When adding timer to list just find cumulative sum until it bigger than timer's left time. Add timer after it and get difference between cumulative sum and timer's left time and make this timer's left time. If there is a timer after the timer we decrese its value by that value.

When processing timers
Find that timer can proceed and decrease its left time by delta. If there is a timer can't proceed after this timer add delta to timer that shouldn't proceed. Finally if that timer becomes negative or less that front of it swap them.

Sorry for my english. Its not great.

**Comment by TheDuriel** [comment]
> When adding timer to list just find cumulative sum until it bigger than timer's left time. Add timer after it and get difference between cumulative sum and timer's left time and make this timer's left time. If there is a timer after the timer we decrese its value by that value.

I can't follow that paragraph.

It's complex.

And there is still no benefit to the **users**.

If I am making a game. How does this improve my game?

**Comment by JoNax97** [comment]
Maybe it would be useful to have some actual performance comparisons before jumping to conclusions for or against the idea

**Comment by KoBeWi** [comment]
Testing this might be interesting, because while the proposed code changes O(n) processing to O(1), it also changes O(1) creation into O(n). I imagine the test would just involve creating e.g. 10000000 timers and measuring FPS. With the proposed changes, the script would more likely freeze during initialization.

**Comment by Flynsarmy** [comment]
A performance test would definitely be good. It may sound strange to have a thousand or ten thousand scene tree timers but perhaps there are use cases in some games we haven't yet considered that someone may need in the future.

> while the proposed code changes O(n) processing to O(1), it also changes O(1) creation into O(n).

Creation happens once and processing happens repeatedly per timer. Overall it sounds like an improvement. If we can make something scalable there really isn't a reason not to. Especially when the implementation is as relatively simple as this one.

**Comment by Calinou** [comment]
>  It may sound strange to have a thousand or ten thousand scene tree timers but perhaps there are use cases in some games we haven't yet considered that someone may need in the future.

We should avoid designing features around speculation: https://docs.godotengine.org/en/stable/community/contributing/best_practices_for_engine_contributors.html#to-solve-the-problem-it-has-to-exist-in-the-first-place

**Comment by MrSametBurgazoglu** [comment]
Thank you everyone who comment this issue. After this discussion I realized this so called "optimization" is unnecessary for most of the developers. No one going to need more than ten timer. So it shouldn't be in core because it is making expensive and complex to create timer. And this makes bad for a lot of use cases.

For the record, more simpler solution can be splitting array into four array(it's because there is 4 possible timer for 2 variable always process and in_physics_process. That way its become more simpler to implement.

Probably I am going to make this as an extension. Even I don't need this extension know. But who knows maybe someday somebody need this.
