### ISSUE TITLE
Implement the ability to add plugin related actions/events to the InputMap

### ISSUE THREAD

**Issue by addmix** [godotengine/godot-proposals#6116]
### Describe the project you are working on

A 3D aerodynamics plugin

### Describe the problem or limitation you are having in your project

There is no way to add inputs to the InputMap from a plugin, and have those inputs save, and be editable, while still being part of the in-game InputMap. You can add actions and inputs, they just do not appear in the InputMap, and do not save.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow plugin scripts to save inputs in the InputMap.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Being able to use the existing `InputMap.add_action()` and `InputMap.action_add_event()` functions, but give users an option to save the current InputMap configuration, and refresh the InputMap UI.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can only be worked around with hard-coded control schemes, or custom editor settings panels.

### Is there a reason why this should be core and not an add-on in the asset library?

It is an error of the existing plugin system.

**Comment by addmix** [comment]
Related: #2024 https://github.com/godotengine/godot/issues/44776

**Comment by KoBeWi** [comment]
You can add a project setting of type Shortcut (`ProjectSettings.set_setting("shortcut", Shortcut.new())`). It will appear in settings and will be editable, but in different place.

**Comment by krazyjakee** [comment]
Related: https://github.com/godotengine/godot/issues/25865

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/25865 (this is a bug).
