### ISSUE TITLE
Overlap Text with Icon in Button Control

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-proposals#612]
**Describe the project you are working on:**
UI items
**Describe the problem or limitation you are having in your project:**
I need add TextureRect as Button's child:
![image](https://user-images.githubusercontent.com/13235119/77230182-4b3a6b00-6b8a-11ea-8c39-e8aa75cdc62f.png)

to obtain this effect:
![image](https://user-images.githubusercontent.com/13235119/77230166-36f66e00-6b8a-11ea-8eda-cc33978614b7.png)

I cannot use the icon field to add my image/icon/texture because the text will be moved aside.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It will be nice to add a checkbox where users can decide if the text can overlap the icon.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
NA
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
NA
**Is there a reason why this should be core and not an add-on in the asset library?:**
NA

**Comment by Calinou** [comment]
It seems https://github.com/godotengine/godot/pull/37181 implements this feature if you set the icon alignment mode to Center.

**Comment by git2013vb** [comment]
It will be in 3.2?

**Comment by Calinou** [comment]
@git2013vb It could be cherry-picked to 3.2.x (or remade specifically) as it's backwards-compatible, but no guarantees.

**Comment by KoBeWi** [comment]
You can achieve that effect with a proper StyleBox.

**Comment by git2013vb** [comment]
I'm forced to use texturerect :) To add the top effect

**Comment by KoBeWi** [comment]
Ok, I checked and indeed it's impossible right now. You'd need StyleboxTexture with border.

**Comment by git2013vb** [comment]
> Ok, I checked and indeed it's impossible right now. You'd need StyleboxTexture with border.

Nope I need a button with overlapped Icon where I can use Gradient with corner radius ;)

**Comment by YuriSizov** [comment]
There doesn't seem to be much traction here, and there are workarounds. Button's icon is supposed to be used for adding an icon, not an effect. Usage of styleboxes, panels, and texturerects is preferred here to achieve the custom look you want.
