### ISSUE TITLE
Rename Tilemap to Tilemap2D and GridMap to Tilemap3D

### ISSUE THREAD

**Issue by PoolloverNathan** [godotengine/godot-proposals#6125]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

The names of `Tilemap`/`GridMap` and related objects may be unclear to beginners.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The existing `TileMap` node should be renamed to `Tilemap2D`, `GridMap` to `Tilemap3D`, `TileSet` to `Tileset2D`, and `MeshLibrary` to `Tileset3D`. I believe that this would clarify the usages of the nodes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, node classes cannot be renamed from script.

### Is there a reason why this should be core and not an add-on in the asset library?

It is a node class rename.

**Comment by KoBeWi** [comment]
Duplicate of #789?

**Comment by PoolloverNathan** [comment]
You're a lot better at searching than me. I think that this one is most like #3518.
