### ISSUE TITLE
Add and expose PackedVector4Array to Variant

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot-proposals#6129]
### Describe the project you are working on

VRM library for Godot

### Describe the problem or limitation you are having in your project

I wish to efficiently store an array of quaternions representing orientations of each bone in a spring joint chain. This is used for the spring bone implementation for VRM.

Currently the only options I have are to use a `PackedColorArray` and mush that data into `Quaternion`s; or use a `PackedFloat32Array` and perform error-prone indexing (`arr[idx* 4 + 3]` etc.) when looping through data; or use `Array[Quaternion]` TypedArray

I'm not sure if Packed*Array have a significant performance difference compared to TypedArray. This to me is more of a question of consistency, since other packed types exist and are widely used.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This proposal is to add a new variant type `TYPE_PACKED_VECTOR4_ARRAY` and expose conversion methods for `PackedVector4Array`

It may also be useful to allow for easy conversion to/from Vector4 and the other 4d types `Plane`, `Quaternion`, `Rect2` and `Color`, so that these can be stored in this packed array without needing additional types.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would involve adding:
`MAKE_TYPE_INFO(PackedVector4Array, Variant::PACKED_VECTOR4_ARRAY)`

as well as all 100 of the various Variant methods and operators and boilerplate functions needed to make a new variant type work.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is possible to use TypedArray, such as `Array[Vector4]`

Having a native PackedVector4Array would allow for using this data in APIs such as shader material uniforms, or mesh functions (for example, tangents arrays).

### Is there a reason why this should be core and not an add-on in the asset library?

Variant is a core type.

**Comment by Calinou** [comment]
> I'm not sure if Packed*Array have a significant performance difference compared to TypedArray. This to me is more of a question of consistency, since other packed types exist and are widely used.

[GDScript benchmarks](https://github.com/godotengine/godot-benchmarks/tree/main/benchmarks/gdscript) from godot-benchmarks give me this result with 4.0.beta13:

![image](https://user-images.githubusercontent.com/180032/213653534-1b3c6bd0-65c8-45fb-93b6-261ffbecd0af.png)
