### ISSUE TITLE
Add option to expand/set icon size in PopupMenu

### ISSUE THREAD

**Issue by rsubtil** [godotengine/godot-proposals#6139]
### Describe the project you are working on

Game launcher frontend, which constantly loads and uses user supplied assets in it's UI nodes

### Describe the problem or limitation you are having in your project

`OptionMenu` has an option to expand icon size. Together with a custom minimum size, developers can tweak the final icon size to their needs. However `PopupMenu` doesn't offer such option, so icons display at their original resolution, which looks bad:
![image](https://user-images.githubusercontent.com/6501975/213867774-e2b9f168-d333-49a1-8b06-e5efb7062523.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Major improvements have been made (https://github.com/godotengine/godot/pull/41640) to `PopupMenu`'s usability, and I believe this issue is one of the last long standing nuisances of it. In a similar vein to the implemented `max_size` property, there should be a way to define a given menu item's maximum size. It's not enough to just add an "Expand Icon" option to it, as the icon can become too small due to the text size. Like with `OptionButton`, there should be a way to specify some minimum size:
![image](https://user-images.githubusercontent.com/6501975/213868068-9e8e0c52-38f3-47ff-86a5-1dfbb11c2ccc.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For `PopupMenu`:
- Add a `max_item_size` Vector2 property that controls the maximum size for a menu item.
    - It should still respect minimum size requirements (e.g. for text), in which case the final size would be bigger than requested

For `OptionButton`:
- Add an `expand_item_to_size` bool setting, that will set the maximum size of menu item's to the control's minimum size. This makes all menu items have the same size as the button itself, which looks better.
    - If another size is desired, it would still be possible to set it in code:
```gdscript
$OptionButton.get_popup().max_item_size = new Vector2(...)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

AFAIK there's no way to change icon sizes of `PopupMenu`s from scripts.

### Is there a reason why this should be core and not an add-on in the asset library?

Modifies core behavior

**Comment by KoBeWi** [comment]
I think OptionButton should automatically adjust the menu to it's expand option. I reported is as a bug: https://github.com/godotengine/godot/issues/58283

**Comment by rsubtil** [comment]
> I think OptionButton should automatically adjust the menu to it's expand option

I can implement that behavior as default then :+1:.

**Comment by rsubtil** [comment]
Implemented with https://github.com/godotengine/godot/pull/75472
