### ISSUE TITLE
Android cleartext support

### ISSUE THREAD

**Issue by combsbt** [godotengine/godot-proposals#614]
**Describe the project you are working on:**
I am working on a game that involves connecting a phone client (as a controller) to a game on a PC run server.

**Describe the problem or limitation you are having in your project:**
Android versions starting with 9 do not support "cleartext"  by default.  See here: https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

This means that you cannot use http or ws but have to use https or wss.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This feature will allow you to enable cleartext support for android.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I have made a custom android build using the new feature in 3.2.  All that was required was adding android:cleartextTrafficPermitted="true" in the manifest.  It would be nice if this could be an option in the standard android build template so the whole custom build process could be avoided.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be worked around by using a custom android build but would be beneficial to have it as an option in the standard build.

**Is there a reason why this should be core and not an add-on in the asset library?:**
ws and http are broken on all current android versions unless this option is enabled.

**Comment by m4gr3d** [comment]
@combsbt While this is inconvenient, I think it's safer to leave it as an advanced option (e.g: require custom build).
The use of `cleartext` traffic is disrecommended for security reasons. While for your use-case it makes sense, for the majority of Godot users it doesn't and having the option easily accessible means that it can be easily toggled by users who are unaware of its impact.
