### ISSUE TITLE
Display a description for the currently selected value in enum property inspector tooltips

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-proposals#6154]
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

In the inspector, hovering a property displays a description. However, for enum properties, this is limited to the property, not its value:

![Screenshot_20230123_190309](https://user-images.githubusercontent.com/180032/214116773-ec19b7de-b758-4a25-bfcf-5bf710a15ed8.png)

This can be inconvenient, as you manually have to go to the class reference to check the associated constant's description.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Display a description for the currently selected value in enum property inspector tooltips.

Some constant descriptions can take a lot of space, so I recommend only displaying a description for the currently selected value, rather than all of them.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Modify EditorHelpBit to display the description of the constant that matches the enum's value in the inspector.

The result should look like this:[^1]

![Screenshot_20230123_190858](https://user-images.githubusercontent.com/180032/214116762-6425e3e3-decf-49c6-be3e-d49e638c0bd5.png)

[^1]: This is just a mockup made by modifying the class reference XML for that property, not an actual implementation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving editor usability and documentation discoverability out of the box.

**Comment by RedMser** [comment]
Since tooltips can also be added to individual OptionButton items, I propose this as an alternative implementation to avoid having to select each item just to see their documentation.

**Comment by Calinou** [comment]
> Since tooltips can also be added to individual OptionButton items, I propose this as an alternative implementation to avoid having to select each item just to see their documentation.

This would require custom tooltips for individual items if you want to preserve formatting that can only be displayed by EditorHelpBit (not standard tooltips).
