### ISSUE TITLE
Backport 4.0 GodotPhysics fixes for 3.6

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#6158]
### Describe the project you are working on

FPS.

### Describe the problem or limitation you are having in your project

Many bugs with GodotPhysics, all of them have been documented.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Recent updates to 4.0 such as https://github.com/godotengine/godot/pull/71447 and https://github.com/godotengine/godot/pull/70660 would be beneficial to projects close to completion in 3.x, but not using Bullet Physics (Gridmaps, for instance, have collision issues in 3.5 when using bullet that doesn't happen with GodotPhysics).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would be specific backported work to merge the fixes to 4.0 with 3.6.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Definitely not.

### Is there a reason why this should be core and not an add-on in the asset library?

It's physics engine fixes.

**Comment by YuriSizov** [comment]
This doesn't need a proposal, just like most backports. It needs someone willing to do the work.

**Comment by elvisish** [comment]
> This doesn't need a proposal

Not sure about that, I'm pretty sure @Calinou has mentioned opening a proposal for backporting if it isn't currently being backported (and I don't know that it is being done).

**Comment by Calinou** [comment]
> Not sure about that, I'm pretty sure @Calinou has mentioned opening a proposal for backporting if it isn't currently being backported (and I don't know that it is being done).

This isn't needed for bugfixes, oinly for new features.

**Comment by elvisish** [comment]
> > Not sure about that, I'm pretty sure @Calinou has mentioned opening a proposal for backporting if it isn't currently being backported (and I don't know that it is being done).
> 
> Proposals are never needed for bug ixes, only for new features.

Sorry, I was thinking it was a proposal. I've re-opened it as a bug issue: https://github.com/godotengine/godot/issues/71961
