### ISSUE TITLE
Support mouse controls on Android

### ISSUE THREAD

**Issue by thebestnom** [godotengine/godot-proposals#616]
**Describe the project you are working on:**
Godot Editor port for Android

**Describe the problem or limitation you are having in your project:**
I need to use mouse controls for full expirience on Android

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Full mouse controls for Android devices

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
full mouse event support to `onGenericMotionEvent`, PR already opened as I cherypicked it from the android editor port

PR: https://github.com/godotengine/godot/pull/37158

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Works out of the box for any android port, which is a great addition for developers who want to support chromeOS (I think) and table tablet (which most likly already have mouse) almost immidiatly (or even phones for lazy developers who just want to test the game port quickly)

**Is there a reason why this should be core and not an add-on in the asset library?:**
a little bit of a problem, right click and middle click on some devices are mapped (in kernel or ROM) to BACK and HOME, which may look like a crush on testing with that kind of device (my oneplus oxygenOS does that and I know that a lot of samsung devices does that).
Also, drag is a little bit of a hack as `onGenericMotionEvent` for some reason doesn't fire when mouse is clicked, only `onTouch`)
Also unlike most platforms, there is no way to directly control the pointer (except hiding it on listening to it and sticking it on specific View by https://developer.android.com/training/gestures/movement#pointer-capture )

**Comment by aaronfranke** [comment]
Fixed in https://github.com/godotengine/godot/pull/37158 and https://github.com/godotengine/godot/pull/42360
