### ISSUE TITLE
Do not include export_presets in exported binary

### ISSUE THREAD

**Issue by boruok** [godotengine/godot-proposals#6163]
### Describe the project you are working on

City builder with rpg elements

### Describe the problem or limitation you are having in your project

I know that encrypting export not perfect for assets security, but i want to make crackers life as hard as possible. So, to the problem:
Noticed that exported `*.apk` include `export_preset.cfg` file, which includes my `AES` key and system `username`, you can literally open it with any text editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

please exclude config file from binary that can opened with archive manager. There is no use-case to have em in exported project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

i didn't have knowledge how exporting works.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

this is core

### Is there a reason why this should be core and not an add-on in the asset library?

this is core

**Comment by dalexeev** [comment]
Have you tried this:
![](https://user-images.githubusercontent.com/47700418/214235800-9484e075-f67d-4dd8-b714-15692d211c19.png)
?

**Comment by boruok** [comment]
@dalexeev dang, this works! always used this to include all files with exact extension and all files within folder, but not for specific file. thanks!

**Comment by Calinou** [comment]
This sounds like a bug – `export_presets.cfg` should never be included in an exported project. I'd go as far it shouldn't be included even if you try to export it with the non-resource export filter (for security reasons).

Please open an issue on the main Godot repository with a minimal reproduction project attached.

**Comment by boruok** [comment]
@Calinou found why this happens, i'm using `.cfg` files to store game data and i marked to include include all `*.cfg` files within project, so that's why `export_presets.cfg` exists in exported project.
There is no error on engine side.

**Comment by Zireael07** [comment]
Even if technically speaking there is no error, I think it's worth changing so that *.cfg just silently ignores export_presets...
