### ISSUE TITLE
Add a boolean flag in MultiplayerAPI that prevents clients from being notified when other clients connect or disconnect

### ISSUE THREAD

**Issue by Jordyfel** [godotengine/godot-proposals#6164]
### Describe the project you are working on

A multiplayer card game in Godot, with a dedicated server.

### Describe the problem or limitation you are having in your project

The `MultiplayerAPI.peer_connected` and `MultiplayerAPI.peer_disconnected` signals are triggered when a client connects or disconnects in every client. This is convenient for self-hosted games, but for dedicated servers with thousands of clients it wastes a lot of messages, since a client doesn't need to know about most of the other clients. Especially so for use cases similar to a card game, where processing is light, so a server would otherwise be able to handle a lot of clients.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a boolean flag to MultiplayerAPI, which, when triggered, makes `MultiplayerAPI.peer_connected` and `MultiplayerAPI.peer_disconnected` be called only on the server. The programmer will notify clients about other clients as needed.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Not sure what the best syntax would be.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I hope I'm not overlooking something.

### Is there a reason why this should be core and not an add-on in the asset library?

`MultiplayerAPI` is core, using it for a dedicated server is a common use case.

**Comment by Calinou** [comment]
cc @Faless

**Comment by lilrooness** [comment]
https://docs.godotengine.org/en/stable/classes/class_scenemultiplayer.html#class-scenemultiplayer-property-server-relay

What you are looking for here is server_relay property :) 

I was looking for this myself and stumbled across your question. So for anyone else that wonders about this and ends up here, here is the answer :)

**Comment by Jordyfel** [comment]
Good to know
