### ISSUE TITLE
Make object manipulation gizmos less transparent for better visibility

### ISSUE THREAD

**Issue by Sakari369** [godotengine/godot-proposals#617]
**Describe the project you are working on:**

Any project.

**Describe the problem or limitation you are having in your project:**

Hard to see eg. camera manipulation gizmos on a dark background and especially when aligned with the axis, see image attached:

![Screenshot 2020-03-22 at 2 13 54](https://user-images.githubusercontent.com/1212726/77239478-d562ed80-6be3-11ea-9da3-76cbef2df4a3.png)

Can you spot the blue axis movement gizmo ? You can, if you focus closely, but took me some time to figure out where it is. Can be difficult on a night mode screen especially or not using very bright screen settings.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Would lessen the transparency for the non-selected gizmos by default. Would make it easier to spot the manipulation gizmos.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Make all the gizmos less transparent by default when not selected. See attached screenshot from Blender:

![Screenshot 2020-03-22 at 2 19 12](https://user-images.githubusercontent.com/1212726/77239495-28d53b80-6be4-11ea-8d0a-ff0d4a251a09.png)

In blender the gizmos are still slightly transparent, but only slightly. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Part of core mechanics.

**Comment by Calinou** [comment]
If we do this, we'll have to make the arrow gizmos smaller as to not take too much screen real estate.

**Comment by inDigiNeous** [comment]
@Calinou Well more opacity first would be already a big improvement. But yeah would probably have to scale the arrow gizmos down a bit, to a region where they still are usable but not so much obstructing.

**Comment by Calinou** [comment]
@inDigiNeous Does this look small/opaque enough to you? I decreased the size from 80 to 60 and increased the opacity from 0.4 to 0.65.

### Before

![before](https://user-images.githubusercontent.com/180032/80528966-08dd2880-8997-11ea-9f46-fe2b909f8390.png)

### After

![after](https://user-images.githubusercontent.com/180032/80528962-07abfb80-8997-11ea-84f2-67cd3c0cbecd.png)

**Comment by inDigiNeous** [comment]
@Calinou Would have to see in practice of course, but I think any rise in opacity in this case is an improvement, this screenshot is a bit difficult to see the difference. Would maybe raise the opacity a bit more, or look at blender 2.8 for good reference point. Thanks for the work :)

Would suggest testing with a black/very dark background and seeing how it feels.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/44384, closing.
