### ISSUE TITLE
Add an option to ignore type annotations when debugging projects

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-proposals#6178]
### Describe the project you are working on

Under NDA - Applies to any large-ish project with different components interacting with each other and using static typing and class_name

### Describe the problem or limitation you are having in your project

Gradual typing is an amazing feature in GDscript that allows you to focus on algorithms when prototyping and be strict when and where you need it. 

The problem is when types are defined using class_name and that global script has errors. 
Say I have class A using class B somehere as a type, which in turn uses class C
If there is an error in class C, B won't load, and A won't load. 

This happens not only with the type annotation is on member variables or function returns, but with any type anywhere, even in a local variable and it means you cannot even run a specific scene even if that scene will never call the method with the missing type. 
This forces you to debug code that your scene would never even execute and, on larger projects, code that maybe you don't own

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Not really sure if it's the right solution but it'd be useful if we could have an "ignore type annotations" where every variable and return type is considered Variant and you can still run the game and you get runtime errors instead of compile/parse time errors.

That way class_A doesn't fail to load because it couldn't load class_B because it uses class_C somewhere inside a method and class_C has a bug. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the main menu you click on Debug and toggle Ignore Type Annotations

It causes the following:
1 - `var a : SomeType` is interpreted as `var a`
2 - `var a:= some_method()` is interpreted as `var a = some_method()`
3 - ` func foo() -> Bar` is interpreted as `func foo()`
4 - any `extends` lines referencing a global script class are ignored if that class couldn't be loaded
5 - SomeGlobalScriptClass.new() throws a runtime error if that class couldn't be loaded
6 - SomeGlobalScriptClass.some_static_method() throws a runtime error if that class couldn't be loaded
7 - accessing a method or property defined in a parent class throws a runtime erorr if the parent class couldn't be loaded (see 4)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not possible AFAIK

### Is there a reason why this should be core and not an add-on in the asset library?

Cannot modify how gdscript is parsed and executed form an addon AFAIK

**Comment by YuriSizov** [comment]
What stops you from removing the type annotation in the code that you do own? It would lead to the same effect as you describe, but you would also be able to add a FIXME note to remind yourself that there is an issue here that needs to be resolved, without jeopardizing type safety of the entire project.

**Comment by noidexe** [comment]
> without jeopardizing type safety of the entire project. 
I just mean being able to run a scene to keep working on your stuff while someone else fixes an error in code that your code never reaches but's causing a chain of unloaded scripts. As soon as that is resolved you debug normally and you get type errors and type safety again.

> What stops you from removing the type annotation in the code that you do own? 
I can do that if it's one or two lines but sometimes it's not trivial, or it could be deep in some singleton that otherwise works ok. Again, what might be causing a big chain of scripts not loading might be a type annotation for a local variable in one method that's never executed. But tracking it down can be very time consuming. 

As I mentioned in the proposal, I'm not sure if my solution is the right one but I think we should have a way to solve the problem. An alternative could be to select a script and display a tree view of all the types it depends on and whether they're failing or not. Right know you only get `"SomeClass" was not found in the current scope` and you have to manually find and open the associated .gd file, and then do the same recursively till you find the script with the actual error.

**Comment by YuriSizov** [comment]
I wouldn't mind having such a dependency tree for a script error myself, though that is said through my 3.x experience. Not sure how these errors are currently reported in 4.0.

However, and that is especially true for a big project as that's what you reference, such issues shouldn't arise in practice because such faulty code several levels removed from the code you own should not be committed to the branch. CI, unit tests, static checks, and QA should be in place in a big team. Not saying it will catch everything, of course. But it's unlikely enough that an ad hoc patch to remove a type hint would be enough should this happen.

**Comment by vnen** [comment]
I believe the system is much better in 4.0, it doesn't need to load scripts just for the type annotations, which is causing some of the problems you have. However...

> 4 - any `extends` lines referencing a global script class are ignored if that class couldn't be loaded
> 5 - SomeGlobalScriptClass.new() throws a runtime error if that class couldn't be loaded
> 6 - SomeGlobalScriptClass.some_static_method() throws a runtime error if that class couldn't be loaded
> 7 - accessing a method or property defined in a parent class throws a runtime erorr if the parent class couldn't be loaded

None of this could really work. If you extend a script that has errors, your script inherits the errors as well. If the dependent scripts are failing parsing, there's not really a way for yours to work either. There's not much reason to let it happily error-free in the editor when it can tell it will fail at runtime.

Like Yuri pointed out, this seems to me like a workflow problem. The team should never allow a script that fails loading to enter the main codebase. It might be tough to enforce (and perhaps a proposal for a tool that checks this would be in order), but it sounds to me more like a team policy issue than an engine problem.

**Comment by noidexe** [comment]
> I believe the system is much better in 4.0, it doesn't need to load scripts just for the type annotations, which is causing some of the problems you have. However...

Ok I was on beta 9, tried beta 17 and the experience is totally different.
- On beta 9 I get "identifier" not declared in current scope and cannot ctrl click the class name to go to the script,  while on beta 17 I get the exact error "could not resolve class ... because of parser error" and ctrl click still works
- On beta 9 if I try to hit f12 to try to continue I get a chain of "couldn't load global class ...", while on beta 17 I hit f12 once to skip the error and I can keep working without problems as long as I don't try to run any code relying on the broken class. 

That's good enough for what I need so it'll be a matter of updating whenever possible.

[Issue6178.zip](https://github.com/godotengine/godot-proposals/files/10564071/Issue6178.zip)
