### ISSUE TITLE
Adding tooltips for export variables

### ISSUE THREAD

**Issue by VitaZheltyakov** [godotengine/godot-proposals#618]
**Describe the project you are working on:**
Kinetic scrolling plugin

**Describe the problem or limitation you are having in your project:**
The absence of tips for export variables
![1](https://user-images.githubusercontent.com/5693437/77251864-42b96180-6c6a-11ea-9feb-0f95b3ac43de.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add the ability to set a hint for export variables

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I think that it will be most convenient to display the previous
comment as a hint for a export variable

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, It is Immpossible

**Is there a reason why this should be core and not an add-on in the asset library?:**
This feature improves the usability of export variables.

**Comment by Jummit** [comment]
Fixed by #godotengine/godot#35716

**Comment by mhilbrunner** [comment]
Reopening until https://github.com/godotengine/godot/pull/35716 is merged.
