### ISSUE TITLE
Auto-minimize the full-screen game window when the debugger breaks

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-proposals#6183]
### Describe the project you are working on

It's an QoL enhancement for the development process.

### Describe the problem or limitation you are having in your project

It's just a regular annoying thing, see below.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When the debugger breakpoint handled, the game window is freeze, and if it on the same monitor (and if fullscreen mode enabled) - user need to manually press Alt+Tab to back the editor window and handle that breakpoint. I propose to eliminate this annoying step by doing it automatically.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Call the `DisplayServer.window_set_mode(WINDOW_MODE_WINDOWED)` at the breakpoint call if the game window is on the same monitor as the editor, and it's in full-screen mode.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by Calinou** [comment]
Should this also be done for maximized (but not fullscreen) game windows?

**Comment by Chaosus** [comment]
And also this should be added when the unhandled error occurred.

**Comment by YuriSizov** [comment]
Important to note that this should only happen if the game and the editor are on the same screen. I used a second screen for debugging quite a lot in the past, would be at the very least very jarring to have the game minimize when the editor is not obscured.

**Comment by Chaosus** [comment]
It seems to be resolved by https://github.com/godotengine/godot/pull/94452, so closed.
