### ISSUE TITLE
Improve discoverability of "Open Project Folder" button in the Project Manager

### ISSUE THREAD

**Issue by stebulba** [godotengine/godot-proposals#619]
**Describe the project you are working on:**
All my projects

**Describe the problem or limitation you are having in your project:**
I am managing all my projects, changing theirs folder. Making clean. But they miss one feature to help to mange all my projects, or help to add new assets on projects folder. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a new button ( Open Folder ) of the selected projet in the Projet Manager.
![godot-new-folder](https://user-images.githubusercontent.com/26193340/77254753-6617e880-6c39-11ea-8876-2d180a45661f.jpg)

**Comment by Jummit** [comment]
There is already a little folder icon next to the project icon you can click to view the project folder. I don't think a sidebar button is necessary, but well see what the general opinion is.

**Comment by stebulba** [comment]
Ok thanks, I tried to click directly on the folder path, not working. I missed the small icon.
I thinks should be helpfull, because I didn't found the icon . If I missed, maybe more people will miss it.
Thanks you save my time ;-)

**Comment by Calinou** [comment]
I'm not sure if the cursor should change when hovering that button, as that would be inconsistent with other buttons. Maybe we could make an exception for that particular button as it's difficult to notice.

I'd prefer keeping the sidebar tidy, so I'd rather not add another button to it.

**Comment by volzhs** [comment]
what about having underline with pointing hand cursor when hovering on a project path?
and opening the path when clicking it.

**Comment by Calinou** [comment]
@volzhs I fear this could be easily misclicked when double-clicking a project in a hurry.

**Comment by Jummit** [comment]
The path and the open folder button is in a very unnatural place IMO. I don't know a better place though.

**Comment by Calinou** [comment]
@Jummit I guess we could add a right-click context menu to be consistent with the FileSystem dock, but it's a fair amount of work.
