### ISSUE TITLE
Make AnimationPlayer editor zoom on the current cursor position instead of the beginning of the track

### ISSUE THREAD

**Issue by CookieBadger** [godotengine/godot-proposals#6204]
### Describe the project you are working on

A 2D rythm-platformer (it's complicated)

### Describe the problem or limitation you are having in your project

Currently, there are several issues, that constantly throw me and my colleagues off when using the Animation Player. I think it could use some usability improvements. One of them is the Zoom tool. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The Zoom tool (or CTRL+Mouse wheel) should zoom in on the current position, not the beginning of the track as it does right now. The current behavior is bad UX, any other timeline-based editing tool (animations, video, audio, etc.) zooms in on the cursor position, because that way you can zoom in onto the thing you are currently working on.

![214716432-f7cbd59e-de5b-472b-b07e-32dbb09b3820](https://user-images.githubusercontent.com/53947784/215361363-7d81ae60-c734-407d-a46d-984193259f1c.gif)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

After zooming in one step (with the UI slider, or with the mouse wheel), move the scroll position, such that the cursor is centered.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is used very often.

### Is there a reason why this should be core and not an add-on in the asset library?

AnimationPlayer is core.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/85142
