### ISSUE TITLE
Functions to replace an extension from a string file path.

### ISSUE THREAD

**Issue by GianptDev** [godotengine/godot-proposals#6209]
### Describe the project you are working on

Small tool wich need to find a file by a given path and search if exist similar paths with different extensions.

### Describe the problem or limitation you are having in your project

It would be nice to have a simple function to replace the extension from the file path.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Trying to manipulate or edit the extension from a string with a file path is very tedious and `get_extension` is not very good at make this process easy.

### `replace_extension(new_extension: String)`
Will append or change the extension from the path and replace it with `new_extension`.
```gdscript
"path/to/file".replace_extension("svg"); # this will append: "path/to/file.svg"
"path/to/file.png".replace_extension("svg"); # this will replace: "path/to/file.svg"
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Sure, these are 2 ways to do it in gdscript:

```gdscript
# doing it with find.

var path: String = "path/to/file.png";
var findDot: = path.rfind(".");

if findDot != -1: # disgusting!
  print(path.left(findDot) + ".svg");
```

```gdscript
# doing it with get_extension

var path: String = "path/to/file.png";

# compact, but still horrible to see.
print(path.left(findDot.lenght() - findDot.get_extension().lenght()) + ".svg");
```

### Is there a reason why this should be core and not an add-on in the asset library?

yes

**Comment by KoBeWi** [comment]
```GDScript
file = file.get_basename() + ".svg"
```

**Comment by GianptDev** [comment]
Well, i forgot about that method...
Then the engine has already what I was looking for, lol.
