### ISSUE TITLE
Add `String.to_uint()` method for C++

### ISSUE THREAD

**Issue by Withaust** [godotengine/godot-proposals#6212]
### Describe the project you are working on

I am working on a game that utilizes `SteamWorks SDK`, which uses `uint64_t` as unique account identification.  

### Describe the problem or limitation you are having in your project

You can easily pass `uint64_t` to a string, but there is no way of getting it back

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Addition of a method `to_uint()` to the `String` class would solve this issue.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`to_int()` => `int64_t`
and so by that logic
`to_uint()` => `uint64_t`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This underlies a problem with a core engine class, so it should be considered to be added as a part of the engine instead.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by Zireael07** [comment]
Why close?
