### ISSUE TITLE
Replace invalid node name symbols with an underscore instead of nothing

### ISSUE THREAD

**Issue by roalyr** [godotengine/godot-proposals#6225]
### Describe the project you are working on

Making GDTLancer, and I tend to rename nodes in a way that name is indicative of data (i.e. star size).
And I am actually copying it all from a spreadsheet.

### Describe the problem or limitation you are having in your project

![image](https://user-images.githubusercontent.com/46825200/216569651-03308f0f-361b-4a3c-93c5-388a4848010e.png)

An example of entering an invalid name symbol (dot):
![image](https://user-images.githubusercontent.com/46825200/216569876-515fe86c-1747-4c2d-9d05-df3037558108.png)

Results to:
![image](https://user-images.githubusercontent.com/46825200/216569989-f65caad0-226f-4f4e-96b1-3945b75e94e9.png)

Would be better this way:
![image](https://user-images.githubusercontent.com/46825200/216570215-7ff816df-ff5d-4d07-b816-5e578814b7cc.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

See above.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will put underscores in place of illegal symbols in node names, instead of just removing them.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Otherwise it should be done manually.

### Is there a reason why this should be core and not an add-on in the asset library?

I assume it is a matter of adding a singe symbol in the code where it handles the node names and replaces illegal symbols with empty character, but I don't know where it is to adjust it myself.

**Comment by dalexeev** [comment]
Related: godotengine/godot#67701. Curiously, the current behavior of `validate_identifier()` is to replace rather than remove an invalid character, unlike `validate_node_name()`. Removal is the most straightforward option, unlike replacement. If several characters in a row are invalid, should they be replaced with several `_` or one? Should it be possible to specify a different replacement character?

If you're generating these names with code, then what's the problem with replacing `.` with `_` _before_ assigning a name?

**Comment by roalyr** [comment]
I have pondered this issue a while ago, because I have a document archive in which I am trying to sanitize names prior to backing it up, and honestly - I haven't figured out what is the best way to do it.

```
If you're generating these names with code, then what's the problem with replacing . with _ before assigning a name?
```
It is not like that. I am just copying values from spreadsheet manually, and renaming things manually too.
I know I can pre-format the fields to ease it up otherwise, but it is just weird that invalid characters are not replaced with placeholders.
