### ISSUE TITLE
Add an 'Apply override to base' option to property inspector for inherited scenes

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot-proposals#6228]
### Describe the project you are working on

A game needing to make heavy use of scene inheritance

### Describe the problem or limitation you are having in your project

One of the stronger features of godot is scene inheritance.
But while chaining and composing inherited scenes with deviating properties is the basis of what makes this feature powerful - the more properties are edited or available the harder it currently is to manually copy the changed values back to the base scene when required.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There needs to be a way to apply changes to properties done to scene instances and edited children back to their base scene.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A rightclick menu on properties could reveal an option to apply the property value to the base instance, or better yet - the menu could feature a list of the inheritance chain so one can chose where to apply the property value (basically what unity does in their nested prefab modification system).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It cannot be worked around in script as it's core editor functionality. 
Maybe by implementing custom property editors for all property types, but that doesn't seem feasible and will easily break or interfere with other addons.

### Is there a reason why this should be core and not an add-on in the asset library?

For the reason stated above

**Comment by YuriSizov** [comment]
You already have a proposal for that: https://github.com/godotengine/godot-proposals/issues/4820.

**Comment by Flavelius** [comment]
Very strange, I could have sworn I already had something like that, but a search for inheritance or apply override didn't bring anything up for me so I thought I may have just commented on something.
