### ISSUE TITLE
Bring back find_tile_by_name in 4.x

### ISSUE THREAD

**Issue by Jeb187** [godotengine/godot-proposals#6234]
### Describe the project you are working on

A 2D top-down RPG with procedurally generated tilemap

### Describe the problem or limitation you are having in your project

In 3.5, you could name single tiles and find them in the tileset by name. I had a dictionary with tiles and their properties (walkable, walk_speed, liquid, an so on) I could use for world generation.

In 4.0, you can name an atlas, but then you still need the atlas coordinates to get a specific tile. Maintaining a dictionary with tile properties is a lot less comfortable, should the graphics of the tileset/spritesheet change.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the property "name" for base tiles and an acompaning function find_tile_by_name.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See documentation for [find_tile_by_name](https://docs.godotengine.org/de/stable/classes/class_tileset.html#class-tileset-method-find-tile-by-name), which returns a unique tile_id that can be used with $TileMap.set_cell.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Right now, I have split up my spritesheet into single 16x16 sprites and added them to the tileset. So the atlas coordinates are always Vector2i.ZERO and i can address the source_id by name.

But editing a spritesheet is a lot easier than editing single sprites.

### Is there a reason why this should be core and not an add-on in the asset library?

It's  a regression to 3.5.

**Comment by groud** [comment]
I don't think it would help much. You can easily create your own custom property of type string and assign it to tiles in the tileset editor now, as 4.0 supports custom data assigned to tiles. And iterating over the tiles should build a dictionary should be rather easy to do in GDscript.

As a consequence, I am not in favor of bringing these property and function back.

**Comment by Jeb187** [comment]
I looked into your suggestion to use custom data layer. While it is not very [pretty](https://www.reddit.com/r/godot/comments/sd4sbc/how_to_use_custom_data_in_godot_4_tilemap/), it is a working solution I can live with. I rest my case.

**Comment by PatrickKunz** [comment]
It would be useful and intuitive to have access to the name somewhere. I import the tilesets and this information would make life much easier.
