### ISSUE TITLE
Don't emit body_exited and area_exited signals while quitting the scene tree

### ISSUE THREAD

**Issue by mphe** [godotengine/godot-proposals#6237]
### Describe the project you are working on

A game where entering and leaving an `Area2D` updates certain UI elements.

### Describe the problem or limitation you are having in your project

When the player leaves the `Area2D`, certain UI elements are modified.
When quitting the scene tree while the player stands inside the `Area2D`, the `Area2D` will emit a `body_exited` signal when the player gets freed. This causes the respective handler to execute. This handler references said UI elements that might already have been removed aswell at this point. This causes a crash.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose not emitting `body_exited` and `area_exited` signals in `Area2D` (and probably also `Area`) while the scene tree is quitting.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I've implemented the proposal in https://github.com/godotengine/godot/pull/72541 for `Area2D`.
It adds a `is_quitting()` method to `SceneTree` and `Area2D` now checks if the scene tree is quitting before emitting a `body_exited` or `area_exited` signal.

I haven't implemented the same for `Area` yet and I've only made the changes for 3.x so far.
Before wasting any time on doing this properly, I wanted to see if this is actually considered useful.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by using `is_instance_valid()` to check if referenced nodes still exist. However, I don't think you should need to guard every `body_exited` code with `is_instance_valid()` in order to prevent the game from crashing during quitting.

### Is there a reason why this should be core and not an add-on in the asset library?

It's part of the Area implementation.

**Comment by TheDuriel** [comment]
Note that this creates scenarios in which a user might expect an instance to be valid, since they rely on the existed signal to discard the reference, and it unexpectedly becomes invalid.

Like, a common way of using Areas is to keep an array of entered bodies, populated by those signals. This was safe and no is_instance_valid() check is required there. With your proposal there would be.

Essentially it just shifts the burden to check if an instance is valid from one place to another.

**Comment by mphe** [comment]
True, that's a scenario where this patch breaks. I guess this is done then.
