### ISSUE TITLE
Implement support for `#!` "important" comment syntax highlighting

### ISSUE THREAD

**Issue by GuyUnger** [godotengine/godot-proposals#6238]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Important comments are easy to overlook because it gets grayed out.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have a way to mark a comment as important. These would be displayed in brighter, maybe even bold letters.
I propose `#!` as there is already a code ligature for it and makes it clear that this is important.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![Photoshop_ZE2eFEMXKv](https://user-images.githubusercontent.com/7023847/216797782-d040bd7f-aace-4ee8-98f3-83d99d252bcd.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by dalexeev** [comment]
`#!` may be confused with [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) or users may think `#!` comments have some special role (for example, some directives).

But we can add highlighting for [common markers](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/alert.xml) in comments (`TODO`, `FIXME`, etc.). Here is how it looks in Kate:

![](https://user-images.githubusercontent.com/47700418/216805686-77e98cbe-dca1-4a91-9793-ca4c30ba7f7b.png)

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP).
