### ISSUE TITLE
Expose ZIP tools through the API

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#6239]
### Describe the project you are working on

A webpage that can create 3D files for download.

### Describe the problem or limitation you are having in your project

I would like to be able to create a ZIP archive with several files in it which the user can save to disk.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having access to a ZIP library through the API would make it easy to create zip files.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A class would be added to the API which allows users to create ZIP archives.  

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I cannot figure out a way to do it through script without implementing the entire ZIP algorithm in GDScript. 

### Is there a reason why this should be core and not an add-on in the asset library?

It would take a lot of effort to implement a full ZIP script in GDScript.  I would expect that Godot already contains a ZIP library, so it would be helpful to expose that through the API.

**Comment by arkology** [comment]
Exposed in master:
https://docs.godotengine.org/en/latest/classes/class_zippacker.html
https://docs.godotengine.org/en/latest/classes/class_zipreader.html
