### ISSUE TITLE
RichTextLabel scroll handle visibility option in Inspector

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot-proposals#624]
**Describe the project you are working on:**
I am working on a mobile app. Nice text scrolling is one of the things I need. 

**Describe the problem or limitation you are having in your project:**
I use RichTextLabel for smooth and good looking text scrolling, but I noticed, that there is no way to hide or make invisible scroll handle from Godot's UI. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In node inspector there are options/properties like Scroll Active, Selection Enabled etc., but there is no option 'Scroll Handle Enabled' nor something similar.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Simple check box 'Scroll Handle On that basically would to what 
RichTextLabel.get_child(0).modulate.a = 0
![scroll_handle_example](https://user-images.githubusercontent.com/11817561/77375927-3b2fb080-6d6f-11ea-99d6-aaf5792b8cd8.png)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It expect it to be used often. Yes, there is RichTextLabel.get_child(0).modulate.a = 0 that does the trick, but if we put check boxes for CanvasItem Visible, or Clip Content, then why not do something about visibility of the scroll handle?

**Is there a reason why this should be core and not an add-on in the asset library?:**
RichTextLabel is already in the core.

**Comment by Calinou** [comment]
RichTextLabel now has a `get_v_scroll()` method (in `master` at least). This allows you to get the VScrollBar node reference and set `visible` on it to `false` (or do anything else other than freeing it).
