### ISSUE TITLE
Improving the online documentation faster . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#625]
**Describe the project you are working on:**
Various games, a Tomb Raider style game . .

**Describe the problem or limitation you are having in your project:**
Sometimes the online docs are a bit missing, or need more info . . It would be nice if the docs were more inclusive, towards more genres, game - styles . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

If in the online docs, there was an option to send a message, to the game devs, and sort of tell them of problems in the documentation, or add stuff, and then they could read that stuff, so when systematically reviewing the docs, perhaps each year, or for major releases, it would be easy to add the information the users want, so it was just a matter of going through each page, and take input, from all users, regarding each page, of documentation . . That way, the docs could become what the users wanted, and needed, from a ' learners ' perspective, sort of . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Well, you would just add a button at top, or bottom of each documentation page, where one could send a quick form, describing a problem, or perhaps limitation, from the users . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I have got no idea, looking around in the docs is often confusing, and it seems it's a mix of old pages, and new ones, sometimes not accounting for changes, smaller bugs, or errors . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think Godot would benefit from it, as more people would be able to jump in, and quicker find solutions, without having to ask on the internet, or forums, pages . . .

I don't know if it has ever been done before, but Godot does things differently, is more community-driven, it would help new users explain problems, as they meet them, making their game, or so . . <3 <3

**Comment by jasperbrooks79** [comment]
Like, I mean, the requests for each page sort of get stored together, so when updating an individual page, like for a function, or method, also it could link to tutorials, expanded knowledge, relevant pages, and work better . . . .

I often need more information, to get started . . . .

**Comment by jasperbrooks79** [comment]
Add . . To begin with, you can just forward the e-mail to a master account, and set a structure, sort of . . So all the things under a certain docs tree, get forwarded to the master e-mail, then there's less work, and people specializing in a certain branch can get forwarded the relevant messages, when they begin updating, checking the docs, perhaps when there is time, or so . .

So, a sort of e-mail ' forwarding ' tree, where all complains about say the ' Audio ' section gets forwarded to a ' grouping ' e-mail . . .

https://docs.godotengine.org/en/stable/tutorials/audio/index.html

That way, keeping the reports organized should be easy, if each major branch of documentation, maybe sub-branches, get a separate e-mail account, then you can see problem-spots in a combined e-mail program, using ' forwarding ' . . It takes a little time, setting it up, a few days, or so . . . Then, it's all automated, the reports go to the right place, no work . . <3 <3

**Comment by orchym** [comment]
You can submit errors, bugs, and content suggestions to the documentation at https://github.com/godotengine/godot-docs. Any annoyances you or others find can be fixed by adding an error or merge request at that repository.

As that is already an option, i don't believe that adding a system separate from the repository would be good for organizing requests.

**Comment by jasperbrooks79** [comment]
I guess it's sort of there already, but doing it this way, with some simple e-mail accounts, possibly with a link to a standard reply form, like making proposals for Godot, would be a better alternative, as people see it, when reading the pages, anyway thank you, I didn't know you could actually do that, I thought only super-hard core people came here, or beginners with a very big wish, for the engine, or idea . . . It's not super-good, using e-mail accounts, but it would work, and be very easy to follow, especially problem areas in the docs, as they get a lot of e-mails, just check the top 10 - 20 e-mails, in the ' e-mail tree ', you can even see the name of the sender, so one could see which areas gave the most trouble . .

Maybe it's not necessary, but having to find a special place on github, normally for hard-core coders, to make a request for the documentation seems weird, like too much work, beginners that notice important faults, or bugs also won't find this page until like using the engine for months, even 6 - 12 months, maybe . . Anyway, it's a dumb suggestion, but it would work, be cheap . . . Add a sort of ' standard ' form, and you got a decent system, that everyone can use . . But, the devs know what's best for the engine, so it's up to them, I don't know . . . :( <3 <3

**Comment by Zireael07** [comment]
We used to have a "request docs" button which opened issues on the godot-docs repository - and it was recently removed because all it did was attract spam/low quality requests.
I'm afraid the same would happen under your proposed e-mail system.

**Comment by jasperbrooks79** [comment]
Okay, you know best, don't have experience, but it would be nice . . <3

Den tir. 24. mar. 2020 kl. 15.18 skrev Zireael07 <notifications@github.com>:

**Comment by Calinou** [comment]
Indeed, there are already several proposals related to adding a feedback system to the documentation such as #481. I'll close this one as a duplicate.
