### ISSUE TITLE
Add support to other external editors

### ISSUE THREAD

**Issue by CptnRoughnight** [godotengine/godot-proposals#6261]
### Describe the project you are working on

every Godot-Mono project

### Describe the problem or limitation you are having in your project

I don't like Visual Studio and VScode 

I would rather be able to use editors like Notepad++ or the new 10XEditor (https://10xeditor.com/).
These editors don't have direct godot support, but with a standard calling convention (how to tell the editor which files to show and open) someone can write plugins.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a list entry for not-supported editors in external-editor select. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If you open a C# script in the Godot Editor the desired Editor (NP++/10X) will be openend.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think this can be achieved by a script.

### Is there a reason why this should be core and not an add-on in the asset library?

This will users free choice of editors.

**Comment by KoBeWi** [comment]
What do you mean by external editor select? You can select any executable in `text_editor/external/exec_path`.

**Comment by CptnRoughnight** [comment]
> What do you mean by external editor select? You can select any executable in `text_editor/external/exec_path`.

Holy.... my bad... didn't know this exists! Thank you! The issue can be closed then, I think.

**Comment by Calinou** [comment]
Closing per the above comment.
