### ISSUE TITLE
Add support for the tile stretch mode for AtlasTexture in TextureRect

### ISSUE THREAD

**Issue by vvvvvvitor** [godotengine/godot-proposals#6265]
### Describe the project you are working on

A 2D pixel art bullet hell game.

### Describe the problem or limitation you are having in your project

Currently the tile stretch mode in TextureRect does not work with AtlasTextures, making it simply expand instead.
![image](https://user-images.githubusercontent.com/119557151/218182413-b26412cd-180c-43d6-b55e-0debe64962a7.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add support for repeatable TextureAtlas in TextureRect.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I propose adding support for said feature, it would look somewhat like this.

![image](https://user-images.githubusercontent.com/119557151/218182620-a3a9ff76-1e42-44d2-842e-c08a56fca509.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around with a shader but it should work out of the box for the sake of convenience.

### Is there a reason why this should be core and not an add-on in the asset library?

This would improve the usability of TextureAtlas and TextureRect.

**Comment by arkology** [comment]
https://github.com/godotengine/godot/issues/20472

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/20472 (this is a bug).
