### ISSUE TITLE
Use triple fingers to pan the editor on Android

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#6270]
### Describe the project you are working on

Using Godot editor on Android

### Describe the problem or limitation you are having in your project

Currently, Godot 4 uses single finger drag to pan in 2D, which conflicts with dragging around nodes in the system.In many touch devices, pan is done with triple finger. i think the editor should do the same. Perhaps related to https://github.com/godotengine/godot-proposals/issues/4340 and https://github.com/godotengine/godot/issues/72385

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

see above

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no it's the editor

### Is there a reason why this should be core and not an add-on in the asset library?

see above

**Comment by m4gr3d** [comment]
This was an issue that's being addressed by https://github.com/godotengine/godot/pull/75113. 
Panning the editor can also be done using two fingers.
