### ISSUE TITLE
Disable long-press rename in the Scene tree dock to avoid conflicts with the node context menu in the Android editor

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#6273]
### Describe the project you are working on

Game, developed using the android editor

### Describe the problem or limitation you are having in your project

When trying to delete nodes from the scene tree, Godot attempts to rename them. To popup the right click menu, you have to long-press onto the icon of the node in the scene tree. I have big fingers, it's hard :D

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

disabling the long-press-rename helps accessing a menu that also offers the rename ability. renaming is a bit more tedious, perhaps the node name can be made editable with a textbox at the top of the inspector, if that isnt already the case

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it's the editor

### Is there a reason why this should be core and not an add-on in the asset library?

it's the editor

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
This is actually a bug in the Android input logic. I've sent https://github.com/godotengine/godot/pull/73197 for review to resolve it.
