### ISSUE TITLE
Add low-level physics queries to KinematicBody

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot-proposals#628]
**Describe the project you are working on:**
I'm working on a project that have some objects that moves in the scene with custom behaviours:
- Projectiles that moves strangely.
- Characters that perform complex movements like wall running or wall to wall jumping, etc...

**Describe the problem or limitation you are having in your project:**
The current kinematic body is designed to support only basic character motion through the APIs  `move_and_slide` and the `move_and_collide`, and doesn't give much room for customization.

If you need to integrate anything different from a character, an animal movement (horse mount) or a kinematic car (see crash bandicoot) or even a simple projectile that needs to penetrate walls or a more complex character motion, you will notice that the two functions above are not enough.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
To make the kinematic body more flexible, I propose to add some low level queries directly on the 'Kinematic Body', that together with `move_and_slide` and `move_and_collide` will allows integrating any motion mechanism directly from GDScript.

This enhancement will give enough freedom to anyone, to integrate its specific motion mechanism without having the needs to ask for a feature proposal.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It's just matter of exposing what's already into Godot, and this is an integration example: https://github.com/godotengine/godot/pull/37225

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No because, it's about adding some low level APIs to get more freedom from the script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This change is about exposing some core functions, that will eventually add the possibility for new plug-ins to land in the assets library.

**Comment by reduz** [comment]
Can you explain better without referencing the pull request what is it you want to implement, and why the queries present for space in the physics server are not enough?

**Comment by eon-s** [comment]
I would not like to see even more things on this class, I think that KB is already too bloated (too many move functions that are useful but not normal on other KB implementations), maybe an extended KB should be made with all the extra functionality instead, it also lacks of "velocity" which is present on many engines to simplify kinematic motion code.

Also lot of `move_*` parameters could be made class properties instead (better on a subclass) to reduce function bloat.

**Comment by reduz** [comment]
@eon-s we discussed in Godot Sprint about moving all the move and slide stuff to a separate class, KinematicCharacter and make most of those actual class properties.

**Comment by AndreaCatania** [comment]
To keep this simple I'm mentioning just few things that I need to implement; for example I need to implement motions like this one:
![ezgif com-video-to-gif(23)](https://user-images.githubusercontent.com/8342599/77510125-56cdb080-6e6e-11ea-912a-d6af4c97d31b.gif)
where the character have to climb walls that are not perfectly smooth, and to run along any walls (see Lucio in Overwatch) without being stopped by the wall imperfections https://www.youtube.com/watch?v=QNtm0fr2H4o.

---

The queries on the space are enough, but not comfortable to use, in this case. I would prefer to rely on functions directly on the `KinematicBody` that allow me to use the the kinematic body shape directly.

As I see this is that the `KinematicBody` should provide all the low level tools to integrate any kind of motion, so that the children classes will use those to integrate what they require.

This mean that, functions like this one: https://github.com/godotengine/godot/blob/master/modules/bullet/space_bullet.cpp#L894-L1043 should be integrated by the specific godot nodes (e.g. `KinematicCharacter`) using the low level functions provided by `KinematicBody`.

**Comment by Jummit** [comment]
I think you could do that with raycast that point in the direction the player looks. If the raycast collides with a wall, you can move it up.

**Comment by Calinou** [comment]
Is this still relevant with https://github.com/godotengine/godot-proposals/issues/2184 being implemented?

**Comment by Diddykonga** [comment]
There is now:
 `test_move()` on `PhysicsBody3D` https://docs.godotengine.org/en/latest/classes/class_physicsbody3d.html?highlight=physicsbody3D#class-physicsbody3d-method-test-move
 
 `test_motion()` on `PhysicsServer3D` https://docs.godotengine.org/en/latest/classes/class_physicsserver3d.html?highlight=physicsserver3d#class-physicsserver3d-method-body-test-motion
 
 That should cover this proposal.

**Comment by Calinou** [comment]
Closing per @Diddykonga's comment.
