### ISSUE TITLE
Add `get_tree_string()` and `get_tree_string_pretty()` methods to Node to complement printing methods

### ISSUE THREAD

**Issue by vPumpking** [godotengine/godot-proposals#6288]
### Describe the project you are working on

ingame 3d level editor

### Describe the problem or limitation you are having in your project

Each time I want to get the scene tree in a project, I have to rewrite the entire `print_tree_pretty` function in order to put the result into a variable, but godot has the right function, it's just that it works only on the output

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Moving `print_tree_pretty` and `print_tree` to `get_tree_string` and `get_tree_string_pretty` enables to use the value returned as well as to print it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the user can call it as it: `var test = get_node("node").get_tree_string_pretty()
print(get_node("node").get_tree_string_pretty())`
(the arguments are no needed because this function have an overloaded definition that makes default arguments if it's empty)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

we can rewrite it each time we want to use it, but it's less convenient

### Is there a reason why this should be core and not an add-on in the asset library?

the `Node` class is a part of the core

**Comment by Calinou** [comment]
It may be better to move `print_tree()` and `print_tree_pretty()` to `get_tree_string()` and `get_tree_string_pretty()` functions, which you could then wrap within `print()`. However, this is a breaking change.

**Comment by vPumpking** [comment]
you're right @Calinou
I made it
thx for your precision!

**Comment by vPumpking** [comment]
a PR is open at https://github.com/godotengine/godot/pull/74321
