### ISSUE TITLE
Old WindowDialog nodes in Godot 4

### ISSUE THREAD

**Issue by Blockyheadman** [godotengine/godot-proposals#6290]
### Describe the project you are working on

I'm working on an 'OS' that uses a window system that's custom made/

### Describe the problem or limitation you are having in your project

When I update to Godot 4, I converted my project and noticed that WindowDialog's are now Windows. It breaks my system where I can use TextureButton's to make usable window controls that are on the window title bar. In 4, it just doesn't show the buttons unless they are on the window's visible area.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would allow for developers to use their old window systems much easier and have custom controls like I have on my windows.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Hopefully this explains it.
![BOS](https://user-images.githubusercontent.com/80011716/218933930-d1e605ce-25c5-4729-b43f-491963bfa1b3.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be recreated but the way the WindowDialog node works makes resizing, moving, and customizing the window much, much easier. Especially in my case

### Is there a reason why this should be core and not an add-on in the asset library?

Yes and no. Yes, it could be on asset library in case people want to use the old system. No because it becomes more available to users and when converting a project, it can just use the old system instead, so the user doesn't need to fix all the errors.

**Comment by dalexeev** [comment]
Use `gui_embed_subwindows = true`.

**Comment by YuriSizov** [comment]
> WindowDialog's are now Windows

WindowDialogs are actually gone now. Window is a more general purpose class, and for a WindowDialog you want to use AcceptDialog and hide its sole button. I want to bring back WindowDialog to have the most basic dialog available again, as I was relying on it myself.

**Comment by Blockyheadman** [comment]
Oh. Well when I used godot 4, I had them embedded into the game window. It's just when I try to add my custom close, maximize, and minimize buttons, it just doesn't show on the toolbar area. Similar to how my picture shows the windows in godot 3 were made, those TextureButtons just wouldn't show. Is there a way to make them show on the window's handle then?

**Comment by YuriSizov** [comment]
You should be able to do it like before for embedded windows. If you can't, please open a bug report with a repro.
