### ISSUE TITLE
Hide tooltips and clear hover when mouse exits editor window

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot-proposals#6295]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Currently, when the mouse leaves the window in any Godot game (including the Editor itself), the mouse no longer has its position updated. This causes tooltips to appear through other applications occasionally, and also makes control appear to be hovered.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

N/A

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See next section.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

In your own game, this can be worked around by using:

```cs
public override void _Notification(int what)
{
    switch ((long)what)
    {
        case NotificationWMMouseExit:
            Input.ParseInputEvent(new InputEventMouseMotion());
            break;
    }
}
```

Implementing this into the editor would be trivial, but making it work at an engine-level would fix the issue for the editor and all games made with Godot.

### Is there a reason why this should be core and not an add-on in the asset library?

To implement this fix in both the editor and all Godot games.

**Comment by RedMser** [comment]
This is probably better off as a bug report instead of a proposal. See https://github.com/godotengine/godot/issues/48634 and https://github.com/godotengine/godot/issues/46737

**Comment by KoBeWi** [comment]
Yes, this was already reported as a bug.
