### ISSUE TITLE
Add network-enabled actors

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot-proposals#631]
**Describe the project you are working on:**
My company SummerPlay is working on an online RPG similar to the likes of Phantasy Start Online or Diablo. It uses a client-server model where the server is authoritative. This is a common model for modern online games that presents a number of interesting challenges to developers.

**Describe the problem or limitation you are having in your project:**
I wouldn't necessarily call it a problem or limitation, however for online games with character locomotion and authoritative server, there are some things that pretty much always need implemented. These include:

1. server reconciliation
2. entity interpolation
3. client-side prediction

The solutions to these problems are mostly the same in every game, yet the knowledge of how to implement them is not super widely disseminated. As such, it's a common pain point for developers new to creating online games. So far, the only engine I know of that is working to make these tasks easier is Unreal Engine. I think that Godot could benefit form such an out-of-the-box implementation of these common features as well.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
For our (yet unannounced) game, we had to solve these problems ourselves and after much iteration, ended up with something that is generic enough to easily rip out of our project and contribute back to the community. Originally, we considered simply creating a GDScript addon, but when I brought the idea up to the devs in IRC, Fales agreed that it would be a nice addition to the engine core. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm thinking something like a `NetworkedKinematicBody[2D]` that functions the same as `KinematicBody[2D]`, but handles things like client-side prediction, server reconciliation, and entity interpolation behind the scenes. Alternatively, a `NetworkedCharacterController[2D]` node could be created that requires a `KinematicBody[2D]` child. I'm not sure which would be more idiomatic, but it's the same in the end, so yea.
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It would be used often for online games, but not at all for single player games. That said, the implementation is non-trivial so I believe it makes sense to provide out of the box.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I was torn between core or assetlib, but after discussing with Fales, we think core makes sense, as it can be come a starting point for more network-related utility nodes.

**Comment by Calinou** [comment]
Is this implemented by https://github.com/godotengine/godot/pull/37200? :slightly_smiling_face:

**Comment by jonbonazza** [comment]
Oh wow, yes. That's actually a much more feature complete and much more efficient (bandwidth wise) implementation. Perfect. Any chance we can get this back ported to 3.2 when it is complete? I'd love to take advantage of his compression code if possible.

**Comment by jonbonazza** [comment]
@Calinou it looks like Andrea's implementation has deviated significantly from what is proposed here.

In the latest implementation in Andrea's PR, it's focused on replicating properties to all peers, and less about implementing networked character controller.

What I suggest here is specifically a `NetworkedKinematicBody[2D]` that functions the same as `KinematicBody[2D]`, but handles things like client-side prediction, server reconciliation, and entity interpolation behind the scenes. Alternatively, a `NetworkedCharacterController[2D]` node could be created that requires a `KinematicBody[2D]` child. I'm not sure which would be more idiomatic, but it's the same in the end, so yea.

**Comment by jonbonazza** [comment]
Discussed with @AndreaCatania @Calinou and @reduz on IRC. Decided just to go with what @AndreaCatania is working on for now. Closing this.
