### ISSUE TITLE
Add "delta unit" to _process and _physics_process method

### ISSUE THREAD

**Issue by nthung-2k5** [godotengine/godot-proposals#6311]
### Describe the project you are working on

A normal Godot game.

### Describe the problem or limitation you are having in your project

So, many people are talking about using delta value instead of framerate-dependent, but usually some people prefer the latter more. And in order to port to delta value, one must multiply their "desired FPS" and delta, which makes the code much longer.

E.x.: A node moves at 12 px/FPS horizontally and the games runs at 60 FPS, so that node will move at 720 px/s. In a normal framerate-dependent scenario, it will look like this: ("Max FPS" configuration set to 60)
```gdscript
func _process(delta):
    position.x += 12
```
```cs
public override void _Process(double delta)
{
    Position += new Vector2(12, 0);
}
```
(also the property feature in C# has made even more redundant code, but I'm not talking about it in this post.)

Of course, it will suffer when framerate drops. So, its delta implemtation is like this:
```gdscript
func _process(delta):
    position.x += 12 * 60 * delta
```
```cs
public override void _Process(double delta)
{
    Position += new Vector2(12 * 60 * delta, 0);
}
```
Adding "* 60 * delta" to literally every single line of code would increase the complexity of code, make the code less readable, and can be quite annoying because of repeating code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The solution I'm proposing is to add a new thing called the "delta unit", which basically means the unit that is used in each delta parameter in the process methods.
That way, people just need to multiply once, and make the code cleaner.

Also using the example above: (the delta in the parameter has a unit of frames, instead of seconds)
```gdscript
func _process(delta):
    position.x += 12 * delta
```
```cs
public override void _Process(double delta)
{
    Position += new Vector2(12 * delta, 0);
}
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I come up with 2 solutions:

1. **Set the unit globally**
    Add a new global configuration called "Delta unit" which has these 2 enums:

- Seconds : pass the normal delta to the 2 process methods.
- Frames: if it's selected, the user will have to provide their "target FPS", from that, the delta in every node is calculated as ```delta_frames = delta_seconds * target_fps```, with delta_seconds is the normal delta value used in the normal process methods.

    With that, the delta value in all of the nodes in game will be either by seconds, or by frames.

    Despite the lack of changing the unit per each node, it is much simpler and require less change of engine code compared to the solution below.
2. **Set the unit locally (means per node)**
    Each node will configure its delta unit separately, using the 2 enums above. It can also be used in conjunction with the method above as well, with each node can "inherit" it or define their own unit.

    And in order to call the parent / base process methods, there needs to be a new method which handles the conversion between the seconds-frames delta and then call the parent / base method.
   
    A simple implementation: (psuedocode in C#)
    ```cs
    public void CallBaseProcess(double delta)
    {
        if (DeltaUnit != base.DeltaUnit)
        {
            if (base.DeltaUnit == DeltaUnit.Seconds)
            {
                delta /= TargetFPS;
            }
           else // base.DeltaUnit == DeltaUnit.Frames
            {
                delta *= base.TargetFPS;
            }
        }
        else if (base.DeltaUnit == DeltaUnit.Frames)
        {
            delta *= base.TargetFPS / TargetFPS;
        }
        base._Process(delta);
    }
    ```
    On the engine side, when iterating to call the process method in each node, it must consider the delta unit of each node (or globally) and pass the desired value.

    I don't recommend this solution because it will break inheritance call of parent / base process method, and require changing more code, both on the engine and user side.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but like said above, the code will have lots of boilerplate.

### Is there a reason why this should be core and not an add-on in the asset library?

This code needs to be in the engine, and several other places throughout it.

**Comment by the-sink** [comment]
Personally I'm a little confused by this suggestion. I wouldn't personally suggest leaving ``12 * 60 * delta`` all over your code in the first place, considering you'd need to Ctrl+F and replace everything unnecessarily if you ever need to change either of those numbers. Why not just store ``12 * 60`` as a constant at the top of a script that needs it? Or if you need it in multiple scripts, put it in an autoload singleton or custom class. That way all you need to do is something like ``DIST_PER_FRAME * delta``.

If your issue is that repeatedly adding another number to multiply all over the place is adding complexity and reducing readability, it sounds to me like your issue could be solved just by avoiding magic numbers, and doesn't really need any engine implementation like this.

**Comment by AThousandShips** [comment]
A lot of the example code uses the same method as suggested by @the-sink and is the generally preferred way as far as I know, if you explicitly want a delta unit you can just add that as a global constant and use it, but save for relatively simple cases you're not likely to have a universal unit for things like would be helped by your proposal
