### ISSUE TITLE
Add a function to select item from a Tree class

### ISSUE THREAD

**Issue by ArMM1998** [godotengine/godot-proposals#6315]
### Describe the project you are working on

I'm working on a simple animation editor for a specific game format.

### Describe the problem or limitation you are having in your project

I am using a Tree to represent objects on the scene (eg: body, head, arm, leg) and their nesting.  
When i click on an item on the tree, the given object is "selected" and can be moved around and transformed with the cursor.
But i also want to have the ability to simply click the object on screen to select it, but then the tree no longer higlights which object is selected and it's instead only highlighting the item clicked.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There should be a way to select an item via a script without needing the user to click on it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I think a function like ItemList's `select(item_id)`, where it selects the item as if you had clicked it, would be great for the Tree class.  
Perhaps something like `select(column_id, row_id)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I have not found a way to work around it other than using something other than a Tree class.

### Is there a reason why this should be core and not an add-on in the asset library?

I think for the sake of consistency and usability, there should be a way to select an item via script just like you can with an ItemList.

**Comment by YuriSizov** [comment]
This method already exists in Godot 4: https://docs.godotengine.org/en/latest/classes/class_tree.html#class-tree-method-set-selected. It was added in https://github.com/godotengine/godot/pull/68448. Should be possible to backport, if there is anyone willing.

**Comment by AThousandShips** [comment]
Opened PR for this: godotengine/godot#74085
