### ISSUE TITLE
Signals can't be named same as properties / methods

### ISSUE THREAD

**Issue by marcinn** [godotengine/godot-proposals#6324]
### Describe the project you are working on

The component based player controller addon.

### Describe the problem or limitation you are having in your project

Because of https://github.com/godotengine/godot/issues/38937 I'm not able to use straightforward signal names:

```gdscript
signal hit

func hit():
  pass
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The goal is to make signals registry not sharing class properties namespace in terms of their names. 

Signlas should be managed/accessed via methods like `register_signal(name)`, `unregister_signal(name)`, `get_signal(name)`, `get_registered_signals()`.

A `signal` keyword should be a shortcut to `register_signal()`.

I know this proposal changes a core concept of signals refactoring done in early 2020. But in fact signal names and property names are two different things. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There are two concepts:
1.  Same as for 3.x: `object.connect("hit", ...)`
2. Through a shortcut like `signals` property (a reserved one): `object.signals.hit.connect(...)`.

The 2nd one will be similar to the current one (`object.hit.connect`), but will solve name clashing issues (excl. `signals` reserved keyword).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by prefixing signal names, i.e. `signal_hit` instead of `hit`, or alternatively - changing a method name. But this will ma the addon's api less readable and messy just because limitations of a gdscript 2.0.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a part of GDScript 2.0 design.

**Comment by YuriSizov** [comment]
Signals were made first class citizens in Godot 4 on purpose. There are no plans to avoid naming collisions, since these are all parts of the class' API.

**Comment by marcinn** [comment]
Oh, thats pity. Just for curiosity - what's the benefit of mixing them with other properties of the class api? As far I see it is not about performance (signal's api is used rarely), readability (indistinguishable from properties), nor convenience (because of introduced name clashing).

**Comment by Mickeon** [comment]
Greatly reduces usage of strings which are fairly error-prone and more difficult to remember. If you try to connect a signal that does not exist the compiler will outright tell you about it before running the project, instead of failing at run-time.

**Comment by marcinn** [comment]
Thanks. That's fair enough. My proposal about accessing signals via proxy object (like `object.signals.hit.connect`) would give same benefit without introduction of name conflicts.  But I understand that it is too late to make such design changes.

**Comment by YuriSizov** [comment]
I disagree about readability and convenience. For an average user currently it is what you see is what you get. You know class has a signal and you can access it in a predictable manner, by its name. You don't need to remember proxy properties or prefixes, just the class and the signal name.

Signals are also their own type, so they can be used in different languages where signals are not a first class concept, but just a property of Signal type. Adding special treatment for those would be once again introducing complexity for something that is currently accessed in a straight forward manner.

As for naming conflicts, it's no different than having both your property and your method named the same. It's a problem for anyone reading the code if it was supported, it's a problem when you describe the code, and ultimately it means you don't have a naming scheme that reflects the contents well.

Granted, we have been hurt ourselves by this change, with the cases like Button's pressed signal and property (allowing for loooong discussions and a kind of hacky and quirky solution). But that's an outlier that IMO once again underlines the problem with the initial naming.

**Comment by marcinn** [comment]
I had to rethink what wasn't/isn't readable for me.

1. I have an experience with Python/Django signalling, where signals are separated objects and can be reused between any objects. Godot's design is strongly coupled to classes, i.e. signal "x" of class "A" is a different thing than "x" of "B", and you decided to make signals as class members same as properties and methods (it isn't quite popular design decision).

2. In 4.0 rc2 there are two different ways to work with signals: a legacy one (accessing via strings), and a new one. I thought that the only one difference is in handling callables in `connect()`, but I was wrong. I think that having both interfaces introduces some confusion, especially for people migrating from Godot 3.x.

----

I'm not comfortable looking for workarounds that may introduce inconsistency or redundancy in naming things, but I can understand the motivation.

I was also a bit afraid of future conflicts where the introduction of new base signals may break compatibility, which will force add-on developers to break compatibility in their API, which will introduce incompatibility in projects based on these add-ons. I understand that a similar problem applies to methods and properties, but due to the introduction of signals as class members, the problem will simply occur more often. But my experience is related to projects that have been developed and maintained over the years, where backward compatibility is quite important. Games are different kind of beasts, I think.

**Comment by YuriSizov** [comment]
Godot 4 breaks compatibility as it's a major release. Such changes would be impossible within a minor release. Games that have been in development for years probably shouldn't just engine versions, likely even minor versions.
