### ISSUE TITLE
Save code folding state for closed scripts

### ISSUE THREAD

**Issue by djrain** [godotengine/godot-proposals#633]
**Describe the project you are working on:**

A project using GDScript.

**Describe the problem or limitation you are having in your project:**

When I close a script, I would hope for the code folding state to be saved and restored the next time I open it. But when I reopen a script, all code is unfolded. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Save the code folding state of the script so it restores exactly how I left it. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Nothing more to say really. There can be an option to toggle this behavior, but it should be enabled by default IMO.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Nope. Workaround is to keep all scripts open, but that's cluttery and bad for editor performance.

**Is there a reason why this should be core and not an add-on in the asset library?:**

I think most people who use code folding would appreciate this option. Probably needs to be core anyway.

**Comment by Ramh5** [comment]
I think this would be a great quality of life feature.

**Comment by Paulb23** [comment]
Going to close this in favour of #37 as it's the same root issue.
