### ISSUE TITLE
Change the Region Editor's "Grid Snap" default from 10px to 8px

### ISSUE THREAD

**Issue by EchoingLogos** [godotengine/godot-proposals#6331]
### Describe the project you are working on

Tile-based game.

### Describe the problem or limitation you are having in your project

The region editor keeps defaulting to 10px. Most tile assets work on powers of two, while almost none work on multiples of 10. Also, the Godot 2D scene editor itself defaults to 8px.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The region editor would now default to 8px width and height when choosing the "Grid Snap" snapping option.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I imagine this would just be changing a constant.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by akien-mga** [comment]
Related to #4362.
