### ISSUE TITLE
Add Horizonal Split Mode to the editor FileSystem dock

### ISSUE THREAD

**Issue by AndreSacilotto** [godotengine/godot-proposals#6333]
### Describe the project you are working on

A project with too many folders

### Describe the problem or limitation you are having in your project

The "Split Mode" option on file system only split vertically and since most monitors have more horizontal space than vertical, would be more reasonable to be able to split horizontally.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a tree toggle state to "split mode":
1. No Split
2. Split Vertically
3. Split Horizontally

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just as it already is, with one additional state

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No - Editor Feature

### Is there a reason why this should be core and not an add-on in the asset library?

Editor Feature

**Comment by Calinou** [comment]
Docks are generally not resized to be very wide, so this may not be very usable on most displays.

**Comment by kitbdev** [comment]
It might be better to automatically detect if the FileSystemDock is wider than it is tall and automatically change between vertical and horizontal split mode.

**Comment by kitbdev** [comment]
implemented by https://github.com/godotengine/godot/pull/80241
