### ISSUE TITLE
Remember last Find in Files / Replace in Files search text

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-proposals#6340]
### Describe the project you are working on

A platformer, but what matters is code

### Describe the problem or limitation you are having in your project

I keep searching for the same things again and again with Find in Files, but the search text field keeps being cleared. I need to remember to copy the string before each search to be able to search again.

The reason why I repeat my search is to make sure I removed all references of a certain variable.

Unlike simple Find, the field is not preserved when the selection is empty. When something is selected, I understand that it auto-fills the search text like simple Find, but when it's empty, it may be good to reuse the last selection.

Visual Studio has exactly the same issue. The only way to fix it is to disable "fill search field with selection" so last selection is reused, but then you also lose that nice behaviour when you actually select something. Simple Find does it well already, we just need to copy this behaviour for Find in Files.

There is no way to _go up_ to see previous search as you'd do in a terminal to navigate history (unlike Visual Studio and others, although the former may require move down instead) either.

The same thing applies to Replace in Files.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Reuse last search text in Find / Replace in Files popup, if selection is empty.

Alternatively, offer history navigation with up/down arrows (but requires more work).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If no text is selected: reuse last search text to fill Find/Replace in Files search field
If some text is selected: fill Find/Replace in Files search field with it, as usual

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's built-in functionaliry

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, it's built-in functionaliry

**Comment by okla** [comment]
+1 for keeping the history of searched prompts (ideally, with autocomplete). 
A good example of such functionality is Qt Creator IDE.
