### ISSUE TITLE
Global and project based add-on handling

### ISSUE THREAD

**Issue by gregcsokas** [godotengine/godot-proposals#6350]
### Describe the project you are working on

It's related to all of my projects.

### Describe the problem or limitation you are having in your project

Anyone can use addons, addons are great and convenient stuff. But sometimes it would be perfect if I would be able to install some addons globally.

For example:
I really like to use the waka-time plugin for Godot, but I need to install it for every project.
So instead of installing it everywhere, it would be really handy if I could use it as a global addon, which loads with every project.

Another example:
WAT or any testing framework/plugin for Godot. Literally the same story.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A few plugins/addons could be global, so you can easily update them through all of your projects, you can use them anywhere, in a new project, or in old ones.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the project settings, when someone wants to create a new plugin, there will be a global checkbox, if it's checked, the new plugin will be global, so instead of installing it in the `project_name/addons` folder, these would be installed in the `.config/godot/addons` folder (in Linux). 

Then basically the only necessary thing I guess is adding 

```
[editor_plugins]

enabled=PackedStringArray("???://addons/addon_name/plugin.cfg")
```
into the `editor_settings.tres ` or a different file in the config folder.

When you install a new global addon, the editor will install it in the config folder, then if you open a project which doesn't use that addon, You can enable it from the project settings, or the editor can ask a question about the global addon activation.  If you start a new project, the global add-ons will be enabled.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's a quality-of-life improvement.

I can force Godot to use addons from a different place, basically, this feature could make easier this.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the editor a little bit.

**Comment by Zireael07** [comment]
Dupe/related to #831

**Comment by gregcsokas** [comment]
Ohh, sorry I don't find it. Thanks :)
