### ISSUE TITLE
Add an option Close Tabs Below in GDScript editor

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot-proposals#6351]
### Describe the project you are working on

A 2D shmup.

### Describe the problem or limitation you are having in your project

I open a lot of scripts, like using CMD/CTRL + click to go to a file, then go back to my script, open the documentation, and without knowing it, I have a lot of files opened. If I want to keep two files open, I need to close all others one by one or use "Close Other Tabs" but reopen the second file I was working on.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be lovely to have an option to close tabs below the selected tab.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user right-clicks on a GDScript and clicks "Close Tabs Below," all files below the selected one will be closed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure it can be done by scripting it with plugins.

### Is there a reason why this should be core and not an add-on in the asset library?

This could be a time-saver feature for everyone.

**Comment by Sauermann** [comment]
"Close Tabs Below" feels like a very narrow solution.
How about a "favorite"-flag for opened files and a "close non-favorites" button?

**Comment by vnen** [comment]
I would also add "close tabs above", since after opening a few scripts, it's normal to want to close the previous ones that are not being edited anymore.

> "Close Tabs Below" feels like a very narrow solution.
> How about a "favorite"-flag for opened files and a "close non-favorites" button?

I believe this a different use case, if I had to favorite a bunch scripts to close the others it would be pretty annoying, I'd rather just close the others manually. I do see the benefit of a "pin" option that excludes the script from "close others", but it's not mutually exclusive with this one.

**Comment by Cronos87** [comment]
I share @vnen's point of view. A "Close Tabs Above" would be excellent too.

@Sauermann Favorite, or pin, is a good idea, but as @vnen said, it's two different ways to work with scripts.

**Comment by TheDuriel** [comment]
This was only just proposed a few weeks ago iirc.

Feels like more context menu bloat to me. Using the search and the file dock allows you to access scripts quite easily even if the list within the script editor ends up bloated. There are various options to close tabs, like closing all documentation tabs, already implemented in the script editor menus.

**Comment by AThousandShips** [comment]
Duplicate of #5976

**Comment by Cronos87** [comment]
Indeed. A PR is already opened for this here: https://github.com/godotengine/godot/pull/71432.

Thank you @AThousandShips.
