### ISSUE TITLE
Make basisu in godot engine unpack to astc

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#6357]
### Describe the project you are working on

V-Sekai is developing a free, open source virtual reality platform.

### Describe the problem or limitation you are having in your project

Meta Quest 2 only supports ASTC / ETC2.

PC only supports DXT5 / BPTC.

These image formats are incompatible. The goal of BASISU is to use one runtime file for all devices.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We would like to make basisu also extract to ASTC. This is a quality enhancement over ETC2.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In `static Ref<Image> basis_universal_unpacker_ptr(const uint8_t *p_data, int p_size)`:

We handle: rgtc, s3tc and etc2.

We can also decompress to ASTC by changing a few lines.

```
format = basist::transcoder_texture_format::cTFASTC_4x4_RGBA; // get this from renderer
imgfmt = Image::FORMAT_ASTC_4x4;
```

The problem is that to verify that this works, I need to test on an Android device like the Meta Quest or the HTCVIVE Focus or [VIVE XR](https://www.vive.com/ca/product/vive-xr-elite/overview/) or a M1 Apple Mac, or something similar.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is deep inside of the core texture code.

### Is there a reason why this should be core and not an add-on in the asset library?

The internal formats of Godot Engine are core.

**Comment by Calinou** [comment]
Isn't the goal of Basis Universal to perform transcoding at load-time? Doesn't this mean we can use the best supported format at run-time?

**Comment by fire** [comment]
Yes, this is about the run-time decompression.

**Comment by fire** [comment]
Another way of saying the above is that we want to support transcoding to ASTC rather than only ETC2.
