### ISSUE TITLE
Allow the Shrink value in Project Settings Display/Window to be set to a value < 1

### ISSUE THREAD

**Issue by deaton1337** [godotengine/godot-proposals#636]
I'm working on a project with a display of 1080 x 1920

I want to have the display size to be 540 x 960 while I develop the game, and have all images display at that size.

When I set the display size to 540 x 960, the images do not resize.

The shrink value in the display/window settings can't be set to a value less than 1. Setting this value to .5 would achieve what I want.

I did manage to achieve what I wanted to do in script: `get_tree().set_screen_stretch(2,1,Vector2(540,960),.5)`  
but I think it should be a setting.

**Comment by Calinou** [comment]
> I want to have the display size to be 540 x 960 while I develop the game, and have all images display at that size.

You don't need to use the Shrink setting for that. Just set **Test Width** and **Test Height** to 540 and 960 (respectively) in the Project Settings while leaving **Width** and **Height** to 1080 and 1920.

**Comment by deaton1337** [comment]
I spent ages trying those settings and I was sure I'd tried that. I just set the test settings and the stretch mode to viewport and aspect to keep and it worked. 
Thought I'd tried that. Thanks :)
