### ISSUE TITLE
Blend import: Ability to import only the active collection

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#6363]
### Describe the project you are working on

V-Sekai is developing a free, open source virtual reality platform.

### Describe the problem or limitation you are having in your project

Improving the blender ecosystem of Godot Engine is important to our work.

Artists may want to use a blender file imported in a different way that has unexported raw sources but exporting only the relevant output.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Import blend files that have collections that are instanced, but not active.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot/pull/73941

> Expose `Include > Limit to > Active Collection GLTF` export option in Blender and is useful when using collections which are instanced in a "main" collection.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The previous workaround was a series of error prone ui actions in Blender.

### Is there a reason why this should be core and not an add-on in the asset library?

Modifying the godot blender importer is outside the range of the target audience.

**Comment by PPillau** [comment]
How exactly do I use this? What exactly is an "active collection" in Blender? Cannot possibly be the one that is currently selected right? Can I mark a collection as active somehow so that it gets included in the import? Right now it just imports everything...
neither the checkmark, nor the eye nor the camera in the blender hierarchy do anything either...

**Comment by Calinou** [comment]
@PPillau Please open an issue on [godot-docs](https://github.com/godotengine/godot-docs) to request documentation improvements.
