### ISSUE TITLE
@export "required" option for editor-time or start-time check that field has been assigned

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-proposals#6368]
### Describe the project you are working on

A platformer

### Describe the problem or limitation you are having in your project

Every time I add an @export-ed variable to my script that is required for good functioning, I add an assert statement for it, such as:

```gd
## Label displaying current frame number
@export var label_frame_number: Label

func _ready():
	assert(label_frame_number, "label_frame_number is not set on %s" % get_path())
```

It would be nice to integrate this as an export option. This could automatically verify that variable was assigned at runtime start, or even better, at edit time (e.g. showing a warning icon like AnimatedSprite2D and AnimationTree when not properly configured).

It could possibly prevent Play too, but I suspect it would be more complicated as we'd need to inspect all scenes, and we may not want to prevent Play from a UX perspective.

For Unity users:

This is similar to Unity's exposed variables where you must add a Debug.Assert in Awake(), but a few third-party plugins offer a C# attribute to tag the field as required:
- https://github.com/Deadcows/MyBox/wiki/Attributes#mustbeassigned [MustBeAssigned] -> works at Awake time
- https://odininspector.com/documentation/sirenix.odininspector.requiredattribute [Required] -> shows error in inspector at edit time

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a syntax to indicate an exported variable as required.

This would show a warning similar to the ones that exist with built-in classes like AnimatedSprite2D and AnimationTree.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

a. We could add an option to @export and its variants like @export_range:

`@export(required: bool) var a: int`

(on @export_range, it may be harder to read as there would be a bool after a bunch of other arguments, and we don't support named attributes)

b. We could add another annotation on top:

```gd
@required
@export var a: int
```

When required exported var is not assigned:

1. In the Scene tree, we could see a warning:

![Godot 4 suggestion - required export - node warning](https://user-images.githubusercontent.com/1067772/221693888-869cf08a-8b5d-45e2-a268-f47a1c84ad6c.png)

and hovering the warning icon would tell us about the unassigned field(s)

2. In the inspector, we could see a warning icon in front of the unassigned field:

![Godot 4 suggestion - required export - inspector warning](https://user-images.githubusercontent.com/1067772/221693905-c3607310-2044-4cfb-97e8-3b5a1e4ed346.png)

Of course, we shouldn't use the `required` annotation/option if the field is meant to be assigned at runtime.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but we need an assert in _ready() for every required exported var. And this doesn't work for edit-time.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about annotations in code. Plus, the engine already uses warning symbols, we could reuse them.

**Comment by Yagich** [comment]
I like the idea!

I think it should be an annotation, but I'm not sure if there are any other annotations that can only be used in conjunction with another annotation and if that's idiomatic.

Also, it would probably only make sense on variables whose falsity can not be mistaken with usable values, e.g.:
```gdscript
# Initialized to Vector2(0, 0) which may be a valid coordinate point, but is falsy
@export var vector: Vector2

# Initialized to 0, which is also a valid number in many instances, but is falsy
@export var number: int

# Initialized to null, which is falsy and usually not desired, so @required would make sense
@required @export var resource: Resource
```

**Comment by Calinou** [comment]
I think @clayjohn is working on adding per-property warnings (if I'm not mistaken), so that you can expose warnings for any property in tool scripts.

**Comment by hsandt** [comment]
I just discovered _get_configuration_warnings / update_configuration_warnings, so indeed, it's already possible to add custom warnings, but auto-generating them for each field and adding a warning icon locally on that field would be great!

**Comment by Calinou** [comment]
- Duplicatge of https://github.com/godotengine/godot-proposals/issues/550.

**Comment by hsandt** [comment]
Thanks for the reference. I see that [RedMser](https://github.com/RedMser) is working on it, not [clayjohn](https://github.com/clayjohn), and I don't see another PR by the latter either. So just check with clayjohn that they are not working on a redundant feature on their side.

Otherwise, I'm good, the demonstration on the other issue's PR looks promising!
