### ISSUE TITLE
A easier and direct way to move a RigidBody

### ISSUE THREAD

**Issue by rafahpdm** [godotengine/godot-proposals#637]
(I'm not native english speaker, so I'm having a hard time trying to explais this, sorry)

**Describe the project you are working on:**

I'm trying some game engines to study more  about 3D game development.

**Describe the problem or limitation you are having in your project:**

I'm having difficulties in implement systems that require more advanced interactions between KinematicBody and RigidBody.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
 
In other game engines (Armory3D, Unity, UE4) you are able to move the RigidBody, by just changing the Position/Rotation directly, that will make the RigidBody move and feel like a KinematicBody, while stils interact with others RigidBody.

In Godot, if you want move a character or do something like "drag-and-drop" a RigidBody, you will need to use KinematicBody and move_and_...() functions. This adds many complexities and makes the process less straightforward.

I tried to showcase this on Armory3D, in this demo, the RigidBody is being moved by changing the position directly, behaving like a Kinematic Body, while interacting with others RigidBody.
[Armory3D demostration](https://www.youtube.com/watch?v=vlKcezeTSdc)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This is a feature that needs changes on the Physics system, but since I saw others also ask about this, I decided to create a proposal about. 
Also since some breaking changes are coming in future versions, this can be a great oportunity to make Godot RigidBody's more simple to use, like in other game engines.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** 

No, right now I'm having several problems with move_and_slide() that requires lots of hacks and workarounds, in comparison with just a few lines of code on Armory3D/Unity.

**Is there a reason why this should be core and not an add-on in the asset library?:** 

This would make programing games that requires Rigidbody so much more easier and accessible.

**Comment by Calinou** [comment]
One of the reasons you can set the position directly is to allow for teleporting (without collision checks). If we remove the distinction, teleporting RigidBodies/KinematicBodies would become more difficult.

**Comment by rafahpdm** [comment]
> One #of the reasons you can set the position directly is to allow for teleporting (without collision checks). If we remove the distinction, teleporting RigidBodies/KinematicBodies would become more difficult.

I didn't understood the comment... In Armory3D/Unity/etc you can easily teleport Rigidbodies, while also having collision checks, you are just teleporting from one place to another, not moving...

From the mainstream engines, Godot is the hardest one to work with Rigidbodies. Having a workflow similar to the other engines would bring so many benefits... From easy to use to make transition easier for people that use this others engines.

As a said above, I didn't have any issues using Rigidbodies on Unity, but in Godot the KinematicBodies/Rigidbodies are being really difficult to deal.

**Comment by rafahpdm** [comment]
@Calinou Hello, I decided experiment with other engine, can you delete this issue for me? I realize that I can't delete, I'm new to Github :D, thanks

**Comment by Calinou** [comment]
@rafahpdm We don't delete proposals, but we can mark them as archived (which I just did).

**Comment by rafahpdm** [comment]
@Calinou I understand, but if you could delete this one, It would make me feel more comfortable. Thanks :D

**Comment by Calinou** [comment]
@rafahpdm We can't delete them in the first place anyway.
