### ISSUE TITLE
Tree with column alignment

### ISSUE THREAD

**Issue by supagu** [godotengine/godot-proposals#638]
**Describe the project you are working on:**
Trains & Things - an economic RTS

**Describe the problem or limitation you are having in your project:**
I displaying lots of data, in the Tree view, and particularly the numbers I want to display right aligned.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
an alignment method would be very helpful on the Tree class

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
tree.set_column_alignment(0, END)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I am not sure

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by groud** [comment]
Could you make a simple mockup ? I don't really how would you add a right-aligned thing in a hierarchical tree aligned left.

**Comment by supagu** [comment]
![image](https://user-images.githubusercontent.com/11153232/77716177-73fcad80-702d-11ea-9aca-573fff7a1c99.png)

Hopefully this picture explains it, just the label within the column needs to be right aligned to make the currency fields look right.

**Comment by dankan1890** [comment]
There is `set_text_align` for aligning the text of the individual TreeItems :) https://docs.godotengine.org/en/3.2/classes/class_treeitem.html#class-treeitem-method-set-text-align

**Comment by supagu** [comment]
Thanks! thats why I couldn't find anything! well this task is irrelevant then!
