### ISSUE TITLE
Backport circular fade instead of linear fade for distance fade to 3.6

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#6382]
### Describe the project you are working on

FPS.

### Describe the problem or limitation you are having in your project

The spatial material distance fade is dependent on the facing angle of the camera, not the distance of the objectas distance fade is going on the depth rather than the distance:
![image](https://user-images.githubusercontent.com/16231628/222217678-49f5ef64-b7ef-4d53-a924-def85770e835.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This can be an issue in particular if distance fade is used to obscure objects from the player unless very close to them, as the distance of visibility changes drastically depending on the angle it's viewed from.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It was reworked for 4.0 by @clayjohn here:
https://github.com/godotengine/godot/pull/50294

and discussed in depth here:
https://github.com/godotengine/godot/issues/53853

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, here is a workaround:
https://github.com/godotengine/godot/issues/53853#issuecomment-944808540

But it should be the default setting as it is incorrect currently.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think this could be an addon, though it can be worked around with a ShaderMaterial.

**Comment by Calinou** [comment]
This is already merged in the `3.x` branch: https://github.com/godotengine/godot/pull/69959

**Comment by elvisish** [comment]
> This is already merged in the `3.x` branch: https://github.com/godotengine/godot/pull/69959
> 
> 
> 
> > But it should be the default setting as it is incorrect currently.
> 
> 
> 
> This change isn't configurable. Therefore, it's already the default :slightly_smiling_face: 

Oh I thought it was fixed for 4.0 and removed from 3.x brand, really good to know!

**Comment by elvisish** [comment]
> This is already merged in the `3.x` branch: [godotengine/godot#69959](https://github.com/godotengine/godot/pull/69959)
> 
> > But it should be the default setting as it is incorrect currently.
> 
> This change isn't configurable. Therefore, it's already the default 🙂

It doesn't look like this made it to 3.6 beta?

**Comment by Calinou** [comment]
> It doesn't look like this made it to 3.6 beta?

I just tested 3.6.beta1, it works as expected:

![Screenshot_20230416_011235](https://user-images.githubusercontent.com/180032/232257612-c66ea813-32ba-4156-bb61-cf371110c487.png)

**Testing project:** [test_distance_fade_circular_3.x.zip](https://github.com/godotengine/godot-proposals/files/11240860/test_distance_fade_circular_3.x.
