### ISSUE TITLE
Add bottom to top option to HFlowContainer

### ISSUE THREAD

**Issue by TheSecondReal0** [godotengine/godot-proposals#6386]
### Describe the project you are working on

Anything using HFlowContainers

### Describe the problem or limitation you are having in your project

I want the HFlowContainer to be able to expand like this:
```
f g h
a b c d e
```
But right now it can only expand like this:
```
a b c d e
f g h
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding an option for HFlowContainers to grow upwards instead of downwards would fix the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's a video:

https://user-images.githubusercontent.com/66881186/222279023-868605f4-1224-43b4-b69e-ad892e4c748f.mp4

Here's a PR with a basic implementation:
https://github.com/godotengine/godot/pull/74195

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Maybe, but this seems like a feature that should just be included in HFlowContainer

### Is there a reason why this should be core and not an add-on in the asset library?

Must be core

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/4453.
