### ISSUE TITLE
Add a `hex_decode()` method to complement `PackedByteArray.hex_encode()`

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot-proposals#6392]
### Describe the project you are working on

A racing game

### Describe the problem or limitation you are having in your project

`hex_decode` counterpart to `hex_encode` doesnt exist

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

add `hex_decode`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
func _ready() -> void:
	var text = "hello world"
	var buf = text.to_ascii_buffer()
	var compressed = buf.compress(FileAccess.COMPRESSION_ZSTD).hex_encode()
	print(compressed.hex_decode().decompress(len(buf), FileAccess.COMPRESSION_ZSTD).get_string_from_ascii())
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

yes: 
```gdscript
static func hex_decode(s: String) -> PackedByteArray:
  var result := PackedByteArray()
  var half_len := len(s)/2
  result.resize(half_len)
  for i in half_len:
    result[i] = (s[i * 2] + s[i * 2 + 1]).hex_to_int()
  return result
```

### Is there a reason why this should be core and not an add-on in the asset library?

consistency; theres a `hex_encode`, why no `hex_decode`?

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/74463.
