### ISSUE TITLE
Debug Play vs Normal Play

### ISSUE THREAD

**Issue by nuke-makes-games** [godotengine/godot-proposals#64]
**Describe the project you are working on:**

I'm working on a simple game in C#.

In order to step through code in C#, you have to attach VS Code to the running game process. In order to do this, you enable "Wait For Debugger" in project settings under Mono -> Debugger Agent. Once this is toggled on, you can attach VS Code to the running game and set breakpoints.

**Describe how this feature / enhancement will help your project:**

If I need to debug, I go into project settings and enable "Wait For Debugger". If I don't need to debug, i have to go into project settings and disable "Wait For Debugger". If i leave that option on, the game will just automatically close since it does not detect VS Code as a debugger.

This is moderately annoying. Every time i need to debug, i have to toggle on "Wait For Debugger" and if i don't need to debug then i have to toggle it off or else i have to attach VS Code every time i run the game which is added work for no reason.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

No diagram really needed. Perhaps have a secondary play button next to the ordinary play button in the top right corner that is for debugging.

The "Debug Play" button would be for situations when i want to attach VS Code to the process, and the "Normal Play" button would not wait for a debugger to attach.

**Describe implementation detail for your proposal (in code), if possible:**

See above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It wouldn't need to be worked around, either you click on the Debug Play button or you click the Normal Play button.

**Is there a reason why this should be core and not an add-on in the asset library?:**

I can't see why it shouldn't be a standard feature, it would save time and make the workflow more intuitive.

**Comment by neikeq** [comment]
This will not be needed once we have a VSCode extension (should happen in March). We already have a MonoDevelop and Visual Studio for Mac extension that can be used to debug without any of these annoyances. It will be announced at the end of this month together with other new stuff.

**Comment by giulianob** [comment]
@nuke-makes-games FYI for now I recommend using https://github.com/exts/MonoDebuggerQM which just gives you quicker access to the "Wait for debugger" toggle. It's still not perfect since you have to keep toggling it but it does help.

**Comment by neikeq** [comment]
We have a MonoDevelop and Visual Studio for Mac add-in now: https://github.com/godotengine/godot-monodevelop-addin
Running from MonoDevelop will automatically attach the debugger.

Extensions for VS Code and Visual Studio will be coming in the future. I'll probably make one for Rider as well, but that's not part of my current roadmap.

You can also create one for your preferred editor by using the [IdeConnection](https://github.com/godotengine/godot/tree/master/modules/mono/editor/GodotTools/GodotTools.IdeConnection) library. You can check [this](https://github.com/godotengine/godot-monodevelop-addin/blob/master/GodotAddin/GodotMonoDevelopClient.cs) as an example.
I plan to create a NuGet package for it. I will also make a js port as I'll need it for the VS Code extension.

**Comment by giulianob** [comment]
@neikeq would it be possible to add an option so that after the debugger times out the game just starts up anyways? I could then set the timeout to 1 second or so and just leave the option enabled at least I don't have to keep toggling it.
