### ISSUE TITLE
Implement hardware accelerated Movie Maker encoding using Vulkan Video

### ISSUE THREAD

**Issue by myaaaaaaaaa** [godotengine/godot-proposals#6409]
### Describe the problem or limitation you are having in your project

Godot's Movie Maker mode is currently slow due to a lack of available high-performance codecs, see #4751 for more details.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The recently introduced Vulkan Video extensions allow for hardware accelerated video encode/decode of modern codecs like h264, h265, VP9, and AV1 under the standardized Vulkan banner, as opposed to the previous situation involving having to pick between one of many fragmented hardware video APIs.

Integration with Vulkan also allows for zero-copy encoding of frames from the framebuffer straight to the GPU's hardware encoder, which would result in very little overhead, unlike other proposed methods like #4710 which involve downloading raw video frames from GPU memory and piping them to an external process for encoding.

Contrary to what is stated in godotengine/godot#62122 , this means that Movie Maker mode would absolutely become suitable for capturing real-time footage, beating out even OBS/FRAPS except when Twitch streaming. :slightly_smiling_face: 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See relevant links:

https://www.khronos.org/blog/an-introduction-to-vulkan-video
https://www.khronos.org/blog/khronos-finalizes-vulkan-video-extensions-for-accelerated-h.264-and-h.265-decode

https://airlied.blogspot.com/

Please note that the encoding extensions have not been finalized yet, so consider this proposal more about discouraging people from working on other methods of integrating advanced codecs into Movie Maker. Since they appear to be [intending to support old GPUs with these extensions](https://airlied.blogspot.com/2023/02/vulkan-video-status-update-anv-radv.html), other methods would probably become obsolete once Vulkan Video encoding is released :slightly_smiling_face: 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Movie Maker mode is usable as-is, but will be slow.

### Is there a reason why this should be core and not an add-on in the asset library?

Hardware accelerated Vulkan Video encoding would provide the best possible out-of-the-box experience for Movie Maker mode. Dropping mjpeg/AVI support may even be feasible once it is implemented.

**Comment by Calinou** [comment]
> Hardware accelerated Vulkan Video encoding would provide the best possible out-of-the-box experience for Movie Maker mode.

This only applies if driver support becomes widespread and reasonably bug-free though. Given how Vulkan Video has garnered relatively little adoption so far, I'm not very hopeful.

**Comment by GithubPrankster** [comment]
>So it'd need to be a dedicated format (or perhaps QOI, but support in third-party apps remains scarce).

The pixel art editor Aseprite recently added QOI support to 1.3-rc1 so I'd keep an eye out for more editors joining in (maybe even Godot-based ones) ^-^
![image](https://user-images.githubusercontent.com/33995085/222590130-3371c934-4733-431b-bdfe-f4eac1f9a425.png)

**Comment by myaaaaaaaaa** [comment]
> > Hardware accelerated Vulkan Video encoding would provide the best possible out-of-the-box experience for Movie Maker mode.
> 
> This only applies if driver support becomes widespread and reasonably bug-free though. Given how Vulkan Video has garnered relatively little adoption so far (for video decoding), I'm not very hopeful.
> 
[The decoding spec was finalized three months ago](https://www.khronos.org/blog/khronos-finalizes-vulkan-video-extensions-for-accelerated-h.264-and-h.265-decode), I'll cut them some slack :slightly_smiling_face: 

There's also an argument to be made that hardware video decoding wasn't as necessary before AV1, since CPU decoding was fast enough to decode previous formats.

> I think the benefit of implementing threading in Movie Maker (and/or hardware GPU readbacks for getting the texture) is far greater right now. Implementing an uncompressed save format could also help improve write speeds while avoiding lossy compression – writing a PNG is slow, and it's not much faster with compression disabled in my experience. So it'd need to be a dedicated format (or perhaps QOI, but support in third-party apps remains scarce).

According to that same blog post, Khronos is expected to finalize encoding extensions this year, although I'm not familiar enough with their past record to know if they're good at sticking to roadmaps:

> The following encode-related extensions remain provisional and are expected to be finalized in 2023 along with new extensions to be introduced for VP9 decode and AV1 decode/encode operations:
> 
> [VK_KHR_video_encode_queue](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_encode_queue.html): common APIs for all video encode operations.
> [VK_EXT_video_encode_h264](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_video_encode_h264.html): H.264 encode-specific capabilities and parameters.
> [VK_EXT_video_encode_h265](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_video_encode_h265.html): H.265 encode-specific capabilities and parameters.
> 

That said, this proposal only covers lossy formats, so multithreaded PNG sequences would probably still be fine to implement - It's mainly #4710 that I'm advising against :slightly_smiling_face:
