### ISSUE TITLE
Signal for change of locale

### ISSUE THREAD

**Issue by GTcreyon** [godotengine/godot-proposals#6421]
### Describe the project you are working on

A 2D platformer that offers multiple language options for dialogue and UI.

### Describe the problem or limitation you are having in your project

Text created dynamically and translated using the `tr()` function is not immediately translated when the locale changes. Its text has to be manually updated by checking if the locale has changed within `_process()` or other repeating function, and changing it if so.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A signal, likely emitted by TranslationServer, that would emit when the locale is changed. This could be connected to by scripts, removing the need for a continuous check.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
func _ready():
  connect("locale_changed", TranslationServer, "update_locale")


func update_locale():
  text = tr(some_variable)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around with a few lines in a `_process()` call, but this would have to either be duplicated between all instances of dynamic translated text, or placed within a Singleton class, which would be cumbersome.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure if this is possible via the asset library.

**Comment by Calinou** [comment]
There's already a `NOTIFICATION_TRANSLATION_CHANGED` you can listen for using a `func _notification(what: int) -> void` function: https://docs.godotengine.org/en/latest/classes/class_node.html#:~:text=notification_translation_changed

**Comment by GTcreyon** [comment]
Oh, oops. Thank you. That covers my use case precisely.

**Comment by GTcreyon** [comment]
Sidenote, I realise that the code I provided is nonsense, and doesn't do what it should do.

**Comment by Zireael07** [comment]
Drive by comment: is there an equivalent for *keyboard layout*?
