### ISSUE TITLE
RID shouldn't be a reference type

### ISSUE THREAD

**Issue by gitcatrat** [godotengine/godot-proposals#646]
**Describe the project you are working on:**
Big if not huge sim type game with lots of static and moving instances which are rendered using visual and physics Servers. Moving objects have "hot state" _struct_ that only contains data required to calculate the next position. These structs are added into list which gives me linear, CPU cache and prefetch friendly, reference-free iteration (can be up to 50x faster). It borrows concepts from (Unity) ECS.

**Describe the problem or limitation you are having in your project:**
If I'm wrong at something, please correct me! C# and C++ are not my strongest language yet.

Because _RID_ is a _class_ and reference type (both C++ and C# which I'm using), it's not passed to _struct_ by value which means that while CPU chases the reference, I could probably complete processing several other states if there wouldn't be a reference. It's a bummer because Servers are a good performance-sensitive alternative to nodes but EVERYTHING about Servers use _RIDs_.

```csharp
// basic example

struct HotState {
  RID Body;
  RID Instance;
  Transform Transform;
  Vector3 Target;
  Vector3 Direction;
}

for (int i = 0; i < states.Count; i++) {
  HotState s = states[i];
  s.Transform = s.Transform.Translated(...);
  // both Instance and Body are reference type :(
  VisualServer.InstanceSetTransform(s.Instance, s.Transform);
  PhysicsServer.BodySetState(s.Body, PhysicsServer.BodyState.Transform, s.Transform);
  states[i] = s;
}
```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
_RID_ should be value type.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
_RID_ could be an _int_, _string_ (or longer siblings) or even a _struct_. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not really, I'd still need to loop over _RIDs_ (or instances containing _RIDs_) and commit new state to Servers at some point of time in a frame. Only workaround? Don't do so much stuff. 

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is as low level and part of the core as it gets.

**Comment by reduz** [comment]
RID is already an int in Godot 4.0 master branch and access time internally to the data inside the servers is O(1).

**Comment by groud** [comment]
Closing as solved then. :)

**Comment by gitcatrat** [comment]
Thanks guys, awesome news!

@reduz It isn't the case in 3.2 yet right? _RID_ in 3.2:

```csharp
// total size ~121 bytes
struct HotState {
  RID Body; // RIDs are ~20-25 bytes each, reference right?
  RID Instance;
  Transform Transform; // 48 byes
  Vector3 Target; // 12 bytes
  Vector3 Direction; // 12 bytes
}

**Comment by Calinou** [comment]
@gitcatrat RID was only changed in 4.0 since this is most likely a breaking change.

**Comment by garettbass** [comment]
I think there has been a misunderstanding of the original request.  @reduz statement does not appear to be true in C#.  In `RID.cs`, on branch `master` as of today, we see the following:
```
public sealed partial class RID : IDisposable
{
    private bool _disposed = false;
    
    internal IntPtr ptr;
    //...
```
What I believe @gitcatrat is requesting, and what I also wish were true, is that `RID.cs` be rewritten as follows:
```
public struct RID : IDisposable
{
    internal ulong ptr; // equivalent to C++ uint64_t
    //...
```
The goal here is that, in C#, the `RID` type should be a **value type** (`struct`, not `class`), of exactly the same size as a 64-bit integer.  Instead of tracking the `_disposed` state as an explicit `bool` member, it would be better to simply set the `ptr` member to zero when the `RID` is disposed.

This change will allow us to write more performance code in C# where we can interact directly with the various `*Server` APIs using `RID`s in an immediate context with no GC overhead, and will be similar to how `RID`s can be handled as `int`s in GDScript.

**Comment by garettbass** [comment]
I see now that @reduz is probably referring to the `dotnet6` branch, not `master`.  Is the `dotnet6` branch DOA?  It hasn't received any commits since Oct 3 2021.

**Comment by gitcatrat** [comment]
Yes, @garettbass is right. I've been away for some time but I want to return for 4.0 alpha/beta and I'd love to see C# RID passed by value and not reference. Because RID is required for almost any server interaction, it's one of the keys to unlock extreme performance _in C# side_.
