### ISSUE TITLE
Allow built-in math functions to work in the precision of their operands

### ISSUE THREAD

**Issue by hilajour** [godotengine/godot-proposals#6465]
### Describe the project you are working on

Various learning projects using GDScript arithmetic functions

### Describe the problem or limitation you are having in your project

As the float type description says, "Many methods and properties in the engine use 32-bit single precision floating-point numbers"

This limits the accuracy of results from built-in math functions unnecessarily, and it may not be obvious to users why it happens, when both the arguments and return value of those funcs are 64-bit floats. An example:
`var nineones := 111_111_111`
`print(nineones*nineones) # 12345678987654321`
`print(pow(nineones, 2)) # 12345678987654320`

See also this issue about logarithm precision, which was closed with the conclusion that it is not a Godot issue because of 32-bit floats: [#30194](https://github.com/godotengine/godot/issues/30194) 

This proposal is not about enabling double-precision for Vectors by default, I understand and agree that memory and processing speed concerns for turning all spatial calculation to 64-bit may be too much for many users and platforms. [#5610](https://github.com/godotengine/godot-proposals/issues/5610) 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

GDScript float is 64-bit. Use this for calculation in built-in (GlobalScope) functions which are documented as accepting float arguments, instead of converting to 32 bits and back.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Not familiar enough with the engine internals to suggest a detailed change, but this should be true:
`111_111_111*111_111_111 == int(pow(111_111_111, 2))`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not with a few lines and even if possible, it would be very bad for performance.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about built-in functions in the engine core.

**Comment by AThousandShips** [comment]
Where are you getting single precision results? The `pow` function uses double precision, the difference between those two results are not from that as the second result cannot be represented as single precision. Also there's no guarantee that `pow(x,2)` is equal to `x*x` it should be equivalent to `x**2` though. This likely also depends on the implementation and compiler.

**Comment by AThousandShips** [comment]
The implementation of `pow` likely does no actual exact calculation of values where the exponent is a whole value, as that would give slow results, since it would require you to repeatedly multiply values, which also comes with issues of cumulative error. All the math functions as far as I can see use double precision just like the internal representation of the `float` value in GDScript.

**Comment by AThousandShips** [comment]
Further, single precision values aren't really available in GDScript as arguments in themselves unless I'm mistaken, as they all use `Variant`, so even calling `pow(vec.x,y)` would treat it as a single precision value (if compiled with vectors having single precision) converted to a double precision one, and the calculations are correct, though it of course can't be assigned back without a truncation

**Comment by hilajour** [comment]
You are right, the result from pow() could not be from 32-bit float since it falls between 2^53 and 2^54, but is not a multiple of 2^30. Should have tested more thoroughly beforehand, but having read the remark about 32-bit floats in the docs just assumed it had to be about that. I had no idea that the result might not equal the integer multiplication when calculating with double floats of this (quite reasonable) magnitude.

**Comment by AThousandShips** [comment]
The result is close to the range of double though, it is around the representation limit of 15-17 digits, the fact that the input is just 9 digits isn't the magnitude that is important, if you do it for `1111_1111` it gives the same result for both multiplication and `pow`
