### ISSUE TITLE
Inconsistent capitalization from Godot 3 to 4

### ISSUE THREAD

**Issue by faefiction** [godotengine/godot-proposals#6467]
### Describe the project you are working on

Various projects.

### Describe the problem or limitation you are having in your project

When saving a scene branch, it defaults the name to starting with a lower case, even if the root node is capitalized.
Godot 3 didn't do this, 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A simple option in the editor to revert this functionality would be great.

Furthermore, I also advocate for an option to enable making scripts always start lowercase, (since if you have a node that isn't saved as a lowercase scene, it will keep it defaulted to staying capitalized. Either way I can't keep my projects capitalization correct.

I'm not sure if the default_property_name_style in the editor (set to Capitalized, Localized, and Raw) Is supposed to help with this, but I had no results.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You open to the editor settings to change the default capitalization for saving scenes, creating nodes, and creating scripts.

With drop downs such as "snake_case, CamelCase, matchCase" (The last option could carry the case over from the scene/nodes name)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a simple setting to let people default their capitalization to Godot or there own standards. (Neither are fullfilled right now.)

**Comment by AThousandShips** [comment]
The setting you are looking for is `editor/naming/scene_name_casing`

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/52597, and can be adjusted using the scene name casing project setting as mentioned above.

**Comment by faefiction** [comment]
> This was implemented by [godotengine/godot#52597](https://github.com/godotengine/godot/pull/52597), and can be adjusted using the scene name casing project setting as mentioned above.

Any reason for project settings instead of editor settings? and is there any way to default my project settings for each new project I make?

**Comment by AThousandShips** [comment]
So it can be configured on each project, as that can't be done at the moment with editor settings

**Comment by faefiction** [comment]
> So it can be configured on each project, as that can't be done at the moment with editor settings

must I configure it each time for each project, or is it possible to have a templated projected when creating a new one

**Comment by AThousandShips** [comment]
I think you have to set it up each time
