### ISSUE TITLE
Add a "try_yield" function.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot-proposals#6477]
### Describe the project you are working on

I have a lot of functions in my code which may or may not yield and they need to be completed before moving on to anything else.

### Describe the problem or limitation you are having in your project

I have to write this code for each function call that may do this:
```gdscript
        var func_state = test_may_yield()
	var result
	if func_state is GDScriptFunctionState:
		result = yield(func_state,"completed")
	else:
		result = func_state
```

I cant make a global function which does this using `callv()`  like so:...
```gdscript
#this does not yield the function calling it though
func try_yield(function_name,params_arr):
	var func_state = callv(function_name,params_arr)
	var result
	if func_state is GDScriptFunctionState:
		result = yield(func_state,"completed")
	else:
		result = func_state
	return result
```
since I would then need to use this same code to call this caller function.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a `try_yield()` function which is basically `yield()` but it just returns the result of the function if it isn't an `GDScriptFunctionState` instead of throwing an "first argument of yield() not type of object" error.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
#replaces the effect of the first code, is exactly like yield
var func_state = try_yield(test_may_yield(),"completed")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes it can be worked around pretty easily but the same workaround must be done every time, for every function call that needs it, which makes the code look bloated and more complicated than it actually is. 

### Is there a reason why this should be core and not an add-on in the asset library?

Part of core functions.

**Comment by KoBeWi** [comment]
This is solved in Godot 4.
If a function is a coroutine, you *always* have to use `await`, which is guaranteed to return the function's return value.
