### ISSUE TITLE
Tileset editor - create square collisions in one click, not three

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot-proposals#648]
**Describe the project you are working on:**
Heartbeast's action rpg tutorial. See his comment on this feature too
https://youtu.be/RPgTlxb7Bno?t=469

**Describe the problem or limitation you are having in your project:**
The process of creating square collisions for each tile is painfully laborious.  I raised an issue about this in the past here, but my request was only half addressed
https://github.com/godotengine/godot/issues/13283

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Basically right now if you want a tile to be a collision, you are required to go through three steps: select it, select the square button, click. Now try doing this 500 times

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I am going to point you to the gif I made from years ago
![colusionshapefilltool](https://user-images.githubusercontent.com/6495061/33233521-17f98e86-d20f-11e7-9c5e-515e338e0241.gif)

See how in the gif, one click is required.You click/select a cell while the tool is active, it gets filled with a square. Also holding a modifier such as ctrl when clicking clears the cell or right clicking.
One thing that might be tricky is in telling the tool not to fill a cell if that cell is already filled .

I guess the hardest part of implementing this would be in coming up with a function that detects if a cell contains a 4 point collision shape already - to prevent it from filling a cell twice if someone double clicks on it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, its an enhancement that is constantly used and needs to be done with the tileset editor directly. It will save hours of laborious boring work 

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because we already have this tool, but it's not doing what its supposed to do in an efficient way. Writing an addon would be like patching a hole instead of fixing it

**Comment by Jummit** [comment]
I'd like a copy-paste feature better, because It would be useful in more cases than just square collisions.

**Comment by itsjavi** [comment]
![Jun-14-2020 03-07-45](https://user-images.githubusercontent.com/122741/84582442-4df4d700-adec-11ea-8cee-0b4ead8f49f7.gif)

We already have the square collision button. But it's a bit slow because we have to select first the tile, click on the button and click again on the tile.

It would be faster to be able to navigate through the collision tiles and fill them with a hot key like `F` or delete them with `backspace`. Copy paste would also be great and intuitive to use.

**Comment by Calinou** [comment]
@groud Is this proposal still relevant with the new TileMap and TileSet editor?

**Comment by groud** [comment]
> @groud Is this proposal still relevant with the new TileMap and TileSet editor?

Not anylire, à similar feature has been implemented and it's really easy to paint squares everywhere now.

**Comment by Calinou** [comment]
Closing per @groud's comment.
