### ISSUE TITLE
Move all hardcoded editor element sizes into theme constants, so that they can be customized

### ISSUE THREAD

**Issue by davthedev** [godotengine/godot-proposals#6482]
### Describe the project you are working on

A custom theme to make the editor more compact

### Describe the problem or limitation you are having in your project

These two measurements cannot be changed using an editor theme:

- The editor window margin (green)
- The separation between top bar and the rest (purple)

![image](https://user-images.githubusercontent.com/26961646/224489024-77c4b347-ba93-4b18-acc1-0878d505eff7.png)

They are both fixed to 8px in the source code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose those values in the editor theme, so that they can be customized.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Already done! PR: https://github.com/godotengine/godot/pull/74767

The values are moved from hardcoded numbers to theme constants under the "Editor" family, with the same default values.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, since the values are hardcoded.

### Is there a reason why this should be core and not an add-on in the asset library?

Affects the editor core.

**Comment by YuriSizov** [comment]
Yeah, we should move all the hardcoded styling properties to the editor theme. I'm going to close this proposal, as you don't need one. Just make a PR for the things that you find.

Would be nice to bring some organization to the table, because currently the editor theme is a mess. But it's not to critical and can be patched later.
