### ISSUE TITLE
Add Color + alpha constructor for Color

### ISSUE THREAD

**Issue by GianptDev** [godotengine/godot-proposals#6492]
### Describe the project you are working on

A selection rectangle of the cursor, like the one in most OS to select an area, it must have a border and fill of solid color but with different alpha.
The border and fill is the same color but with different alpha.

I'm using Godot `3.5.1.stable.mono`.

### Describe the problem or limitation you are having in your project

I want to clone a color but I also want to change the alpha value and it would be handy doing this in the same call of the constructor and in the same line of code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

it could be done by adding this new constructor:

```gdscript
Color (color: Color, alpha: float)
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It could work like this:

```gdscript
var alpha_blue: = Color (Color.blue, 0.5);
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

```gdscript
var alpha_blue: = Color.blue;
alpha_blue.alpha = 0.5;
```

or

```gdscript
# ugh, terrible.
var alpha_blue: = Color(Color.blue.r, Color.blue.g, Color.blue.b, 0.5);
```

### Is there a reason why this should be core and not an add-on in the asset library?

yes.

**Comment by AThousandShips** [comment]
You can already do this in 4.0

**Comment by GianptDev** [comment]
but not on 3.5 , can this be back-ported for older versions?

**Comment by GianptDev** [comment]
yes is possible, there are already some overloads in gd for Color: 
![immagine](https://user-images.githubusercontent.com/89723855/224748369-e3b1bcbc-09f5-4a37-8981-e2660abfd23e.png)
Unless you are talking about something else...

**Comment by AThousandShips** [comment]
I meant that specific overload, but I was confused that it had another 2 argument overload, but it wasn't backported when first added so not sure if it would be or if it is possible

**Comment by GianptDev** [comment]
![immagine](https://user-images.githubusercontent.com/89723855/224750388-d8272a8d-2484-4851-b97e-8e06c77ce151.png)
An overload with only the color exists, so it just need to add the alpha value.

**Comment by Calinou** [comment]
The current workaround is to use `Color.RED * Color(1, 1, 1, 0.5)`.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/74973.
