### ISSUE TITLE
Implement lazy-loading of SVG textures

### ISSUE THREAD

**Issue by TechnoPorg** [godotengine/godot-proposals#6495]
### Describe the project you are working on

A desktop application making use of SVG files to store textures of UI elements. This is also relevant for the Godot editor, which stores all editor icons as SVGs.

### Describe the problem or limitation you are having in your project

Currently, Godot handles SVG textures in exported programs by rasterizing them upon import, and using the resulting bitmap image as the texture. Since SVGs are not a vitally important file format in the world of game development, this works fine for the most part, but I believe that a small improvement could be made on the existing system, as rasterizing SVGs ahead of time results in increased binary size in exported games, which can be significant when working with many textures.
Additionally, the Godot editor rasterizes all SVG editor icons immediately on launch, which increases startup times for the editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest that users be presented with an option to have SVG textures lazily loaded in exported games, rather than pre-rasterized. The lazy texture would contain some metadata like size and channels, but the texture will only be rasterized from the SVG when the actual texture data is queried. Once rasterized, the texture will be cached for the rest of the application run session and not rasterized again.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A new resource type, `SVGTexture`, can be added to implement this proposal. It will have a property `Lazy Import`, to toggle whether or not it is rasterized ahead of time. Rasterization at runtime will briefly impact performance, so this choice should be left to developers. If `Lazy Import` is false, SVGs will be handled as they are currently. If not, the `SVGTexture` will initially hold only the SVG file vector data, and some already known metadata like the size of the texture. When an actual pixel is requested, it will check to see if the texture has been rasterized yet. If not, it will first rasterize and cache the SVG texture. Then, it will return the pixel from the cached rasterized texture.
In the editor, this will mean that icons are only rasterized when they appear on screen, which will stagger their loading and decrease their impact on start times.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe it can be worked around in a cumbersome way, by only importing SVG textures at runtime through code, but this is obscure and unnecessarily complex.

### Is there a reason why this should be core and not an add-on in the asset library?

This would be an extension of the core asset handling system.

**Comment by fire** [comment]
This is a feature of the thorvg tech, but it was not exposed. I think this can be done.

Perhaps @hermet and @mgrudzinska can give some suggestions.

**Comment by hermet** [comment]
Firstly, I'm surprised at how SVG icons have increased the Godot editor's launch time. I'm curious about some factors before suggesting my idea: How much time in ms would it take? How many SVG resources would be loaded on launch time? What is the average resolution of the icons? This information would help me understand the situation clearly.

By the way, when I read the issue description, it sounds like the Godot editor currently loads all the available resources on launch time. This is obviously bad for performance, especially if the number of resources is large or could be linearly increased. Definitely, it should be refactored by redesigning the loading mechanism as @TechnoPorg suggested. This sounds quite reasonable, and I like it. It suggests a proxy style to achieve deferred loading, and this must be done on the Godot engine (editor) side.

Alternatively, I guess the editor could selectively choose the necessary resources to load based on the current viewport UI. It's up to the UI composition design and workflow.

Another approach we can consider is parallelizing the SVG loading by threading. If Godot hasn't considered this, it would somewhat enhance performance. Currently, ThorVG provides APIs in the future/promise style for multi-tasking. The Godot editor could read SVGs somewhere earlier and draw the canvas later around Godot texture loading time.

I think the enhancement should be done on the Godot side. Maybe ThorVG could only help with the last idea to make Godot use ThorVG properly.

**Comment by fire** [comment]
In the Discord conversation, iFire and Hermet discuss using a proxy data type to handle SVGs in the Godot game engine. This is meant to address concerns about the editor's size and launch time. The proxy would only draw visible SVGs in the viewport and rasterize others as needed, potentially speeding up the launch process. However, Hermet notes that even if only visible icons are loaded at launch time, the proxy mechanism may not be useful if it is still too slow. We suggest testing the approach and considering the following factors:

1.  Number of icons loaded at launch time
2.  Visibility of the icons in the initial viewport
3.  Resolution of the icons
4.  Threading mechanisms

By evaluating these factors, we hope to determine the effectiveness of the proxy approach.

Summarized by ChatGPT4.

**Comment by TechnoPorg** [comment]
Would the proxy type you describe function in the same way as the SVGTexture type I proposed?

**Comment by fire** [comment]
Yes

**Comment by TechnoPorg** [comment]
Should I close this proposal and open a general proposal about lazily loading objects, which this concept would fall under? I believe that would be more desirable / useful for the community.

**Comment by TechnoPorg** [comment]
That's an excellent point. What about adding something like C#'s `Lazy<T>` type, which has no intrinsic object creation features, but just has a `Value` property that, when called, is initialized with the return value of a callable passed to the `Lazy`?

**Comment by felaugmar** [comment]
Hey @TechnoPorg, I'm working out in a `SVGTexture` implementation that follows pretty much what was said here https://github.com/godotengine/godot-proposals/issues/3422#issuecomment-1592302969.

> ...should be a dedicated SVGTexture with a `scale` property and a `source` property where you write the SVG code. The texture is updated when `scale` or `source` are modified. This would make it similar in spirit to GradientTexture, CurveTexture, etc.

Do you think this implementation of `SVGTexture` solves your proposal?

**Comment by TechnoPorg** [comment]
Yes, I do think that your implementation would fit what I had in mind quite nicely, as long as it defers rendering of the SVG until the first time a texture lookup is actually performed!

**Comment by felaugmar** [comment]
In my implementation, rendering happens (*threaded* if enabled) when `svg` and `scale` are provided.

> defers rendering of the SVG until the first time a texture lookup is actually performed!

I feel this must be handled by another layer of abstraction, not direcly into `SVGTexture`.

**Comment by TechnoPorg** [comment]
Without knowing the details of your `SVGTexture` implementation, I don't know that it **must** be handled by another layer of abstraction. I feel like it would be cleaner, and more performant in terms of load times, to put some kind of code like `if(!image) image.render()` at the start of the various Texture2D functions, rather than doing it as soon as `svg` and `scale` are provided.

**Comment by Calinou** [comment]
> I feel like it would be cleaner, and more performant in terms of load times, to put some kind of code like if(!image) image.render() at the start of the various Texture2D functions, rather than doing it as soon as svg and scale are provided.

Rendering textures on first sample is prone to causing stutters during gameplay. It's better to pre-render textures in advance when the scene loads.

**Comment by TechnoPorg** [comment]
> Rendering textures on first sample is prone to causing stutters during gameplay, which we should aim to avoid at all costs.

I see your point! When it's put that way, longer load times are definitely preferable. Since rendering textures on first sample was the aim of this proposal, I realize that it was misinformed, and not particularly desirable. I'm going to close it in favour of #3422, since this is the case.
