### ISSUE TITLE
wrap rect for graphics and colliders both 2d and 3d 

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#650]
**Describe the project you are working on:**
spaceship game

**Describe the problem or limitation you are having in your project:**
I want to acheave a seamless wrap for objects however having 8 copies of sprites and colliders for the edges is getting tricky because sprites need to be synced to the parent sprite and colliders need to be a child of a physicsbody.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
implement a wrap rect2 for all 2d drawables and colliders and implement a wrap rect3 for all 3d drawables and colliders

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
basically it would make 8 copies of 2d drawables and colliders and 14 copies of 3d drawables and colliders.
each copy is only visible in playmode or if a show_wraps flag is set and the copies are only active if visible both 2d and 3d in playmode

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
this could be worked around if you could parent a collider to another collider and have it still work but getting it to be opimized could be trouble

**Is there a reason why this should be core and not an add-on in the asset library?:**
while this could be gotten around technically in 2d, 3d is a bit more complicated, noone wants to make 14 copies of every drawable and 14 copies of every collider each object has.

I think this would be used quite often in any space game

**Comment by clayjohn** [comment]
Could you provide a little more context? After reading the proposal I still have no idea what it is you are proposing. What are you explaining when you say you need a "seamless wrap" for objects. Further, why 14? I have a feeling diagrams and example images may be very useful here.

**Comment by Shadowblitz16** [comment]
sorry what I mean by seamless wrap is both graphics and collisions
a I said 14 for 3d because a cube has 6 sides and 8 corners

**Comment by clayjohn** [comment]
I'm sorry, I still have no idea what seamless wrap is.

**Comment by Calinou** [comment]
@clayjohn @Shadowblitz16 wants a physics object that will be displayed on both sides of the viewport if it touches (and partially enters) one edge of the viewport.

**Comment by Shadowblitz16** [comment]
I think this might be doable with a parallax layers however I am worried about overflow and underflow of the positional values if they get too large or small

**Comment by Shadowblitz16** [comment]
nope paralax layers don't really work after doing some tweaks on my scenes.

this feature would probably best be suited for implementation on node2d and node3d if it was done
that way sound could be wrapped as well

**Comment by Shadowblitz16** [comment]
this actually needs parallax layers and cameras to have wrapping as well.
a objects position only can hold a value so large and so small and right now seamless space is not very feasible.

**Comment by Shadowblitz16** [comment]
better idea https://github.com/godotengine/godot-proposals/issues/658
