### ISSUE TITLE
Light3D Orthographic Projector

### ISSUE THREAD

**Issue by Duskitten** [godotengine/godot-proposals#6510]
### Describe the project you are working on

The project I'm working on is an RPG of sorts

### Describe the problem or limitation you are having in your project

The idea is for there to be a selection under a character, a normal flat plain wouldnt work for this, as uneven terrain would make it clip through stuff, or walls.

However, the current form of projection on the Light3D nodes has no capability to do orthographic rendering of a projection. This makes the light grow in size assuming there's distance under the character.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Essentially, adding an orthographic projected version of this, It would essentially make the projection stay a consistant size when put over an object, and there was any depth added, making it distort, and stay a consistant size, but not grow bigger or smaller on distance.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I dont know code for this, but, essentially

If something is projected in orthographic view, it has no depth, which means distance has no effect
This means that if a circle is in view, it will consistantly stay that size unless rotated on an off axis

Essentially, This would be a system to make it so that consistantly sized projections would work

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It cannot, due to the nature of it requiring removing depth entirely from a Light3D Projector

### Is there a reason why this should be core and not an add-on in the asset library?

This should be in the core, as it would allow for more special effects, and more control over how the lighting system works. I feel if this was in the asset library, it would be extremely laggy as it wouldnt be optimized since it would need to access core components.

**Comment by Calinou** [comment]
You can use a Decal node to achieve what you want :slightly_smiling_face:
