### ISSUE TITLE
Set camera position and rotation to current editor view look.

### ISSUE THREAD

**Issue by twoco** [godotengine/godot-proposals#6517]
### Describe the project you are working on

General useful feature, read on...

### Describe the problem or limitation you are having in your project

It is difficult to position the camera where you want it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be great to place the camera on the current view position (editor virtual camera). Maybe an option for every node. Not only cameras. For example right click on the node or a menu in the view port and select "object to view" which moves the selected object to the position and rotation (look to) of the view. The camera will now have the exact same view as you have in editor e.g. by using Shift + F for fly mode. This will help you position your camera perfectly. Ok, the POV and aspect ratio can be different. But this does not really care. Get inspired by Blender. You can fly your camera to a position and see the view of the camera. The POV and aspect ratio is darker/masked. But this can be implemented later if we want. A simple "move object and rotation to the current view" would be awesome.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We could add a new entry to the "Transform" menu of the viewport editor. A menu like "Move object to view" and open a dialog to select "Position" and/or "Rotation". This moves e.g. the selected camera to the view position and rotation. The camera will have the same view by transform position and rotation.

![proposal](https://user-images.githubusercontent.com/53160891/225762950-e483e90f-0a0b-486e-8f09-fbcd7e319813.png)
<sup>Photo montage added "Move Object to View..."</sup>

We could also just add a button/option to the "Transform Dialog" to fill the form with data set to view position/rotation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I could write a script with similar behavior like the editor view fly camera. And log the position and rotation to set it later manually in editor inspector. But ...

### Is there a reason why this should be core and not an add-on in the asset library?

 ... I think it's a nice simple but helpful feature in Godot.

**Comment by Calinou** [comment]
This already exists with **Align Transform To View** feature that is part of the **Perspective** menu. Its keyboard shortcut is <kbd>Ctrl + Alt + M</kbd>.

**Comment by twoco** [comment]
Great 👍 I missed that.
