### ISSUE TITLE
Add an "Adaptive" line wrapping mode for TextEdit

### ISSUE THREAD

**Issue by gelvinp** [godotengine/godot-proposals#6519]
### Describe the project you are working on

I am prototyping a notion-like text editor.

### Describe the problem or limitation you are having in your project

I have an issue with the "Boundary" line wrapping mode. While it works for most reasonable lines with spaces in them, any lines that don't have spaces in them are simply cut off. See below:

https://user-images.githubusercontent.com/61520531/225768627-41b51d01-33ca-43f3-9458-55d753f8dd2e.mp4

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a new "Adaptive" case to the `LineWrappingMode` enum, and an if statement to the `set_line_wrapping_mode` function that checks for this adaptive case, and if found, uses the `TextServer::BREAK_ADAPTIVE` break flag on the contained TextParagraph. See below:

https://user-images.githubusercontent.com/61520531/225768997-37614e26-ee22-477f-ad72-2bdb9d1b490b.mp4

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have implemented it in this commit:
https://github.com/gelvinp/godot/commit/e1ef595ed947e7ba66846abc638972e3a99ea545

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can't access the TextParagraph to change the break flags from within GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

The functionality to do this wrapping is already included in TextServer and used for RichTextLabel, it is just exposing that option to TextEdit.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by gelvinp** [comment]
Forgot to propagate break flags to newly created lines within TextEdit, so I added a commit to fix that.

Here's a link to compare the combined change against master:
https://github.com/gelvinp/godot/compare/master...gelvinp:godot:linewrapping-character?expand=1

**Comment by bruvzg** [comment]
It's probably should use the same wrap modes as other controls - https://github.com/godotengine/godot/pull/74813 (need more scrollbar / auto-scroll fixes).

**Comment by gelvinp** [comment]
:+1: That probably works better, yeah
