### ISSUE TITLE
Rename `Reference` to `RefCounted`

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot-proposals#652]
**Describe the project you are working on:**
This affects engine development rather than projects. Users can still see the name of the class, but won't matter much in projects.

**Describe the problem or limitation you are having in your project:**
N/A

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
We have a reference-counted base class called `Reference`. That name is confusing, since they are not references, but things that are referred to.
The idea is to rename it to `RefCounted` so it describes better what it names and also to avoid hard to understand types in the C++ side, like `Ref<Reference>` (what?, a reference to a reference?).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`class Mesh : public Reference` would become `class Mesh : public RefCounted`. Much easier to understand, right?

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not possible.

**Comment by IronicallySerious** [comment]
I think I have seen that terminology in some Lua binding library (probably LuaBridge). This means that the term `RefCounted<T>` is widely known outside of the engine too. But in the end, it is up to the core devs

**Comment by Xrayez** [comment]
I think anything will do!

`RefCounted` asks for completion → `RefCountedObject`. What about `RefObject`?

I imagine reduz would be in favor of the verbose version. 😉

**Comment by neikeq** [comment]
I've also seen RefCounted in other game engines, so it's indeed pretty common.

**Comment by aaronfranke** [comment]
Makes sense. The name `ReferenceCounted` occurred to me, I'm not necessarily in favor of it, but posting it for consideration.

**Comment by Xrayez** [comment]
`ReferenceCounted` could be a good compromise between the old and new, especially when it's more explicit. We do already have even more verbose names like `RandomNumberGenerator` over `RNG` etc.

**Comment by Xrayez** [comment]
I have looked at godotengine/godot#49312 and noticed this:
```c++
Ref<RefCounted> rc;
```

When we compare this usage against suggested `ReferenceCounted`:

```c++
Ref<ReferenceCounted> rc;
```

What looks more readable to you?

**Comment by RandomShaper** [comment]
Judging just by that example, I'd say the second is more readable.

However, I still believe `RefCounted` wins overall. One reason is that 'reference' tends to be abbreviated as 'ref' in many other cases, like `SafeRefCount` and `Ref` itself.

I'd say it's better to go for `RefCounted` and maybe consider the univeral expansion of `Ref` to `Reference` in a separate proposal.

**Comment by Xrayez** [comment]
> I'd say it's better to go for `RefCounted` and maybe consider the univeral expansion of `Ref` to `Reference` in a separate proposal.

I'm not sure whether it makes sense to discuss this in isolation, because we're talking about consistency here (even if we don't necessarily have consistency/clarity as of now). I'm mainly talking about:

> The idea is to rename it to `RefCounted` so it describes better what it names and also to avoid hard to understand types in the C++ side, like `Ref<Reference>` (what?, a reference to a reference?).

---

That said, if there are other occurrences which make it potentially ambigious with `Ref<>`, then perhaps they are worth to consider renaming in the same proposal (which could've been renamed to **"Resolving Ref vs Reference name inconsistencies and confusion"**). But yeah, if that's what makes the review and approval process easier, so be it!

I'm also talking from the standpoint of Godot's development principles (the way I see it). I rarely see reduz copycatting names from other game engines. 😛

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/49312.
