### ISSUE TITLE
add support for MOONRAY Renderer

### ISSUE THREAD

**Issue by eddilara** [godotengine/godot-proposals#6525]
### Describe the project you are working on

add support for MOONRAY Renderer directly in the engine since its open source now

https://github.com/dreamworksanimation/openmoonray

### Describe the problem or limitation you are having in your project

better renderer

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

the code is already there and pretty good...might as well 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

not a programmer

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

since its a renderer it really needs to be part of the main program

**Comment by Mickeon** [comment]
Not many details on the reasoning, or the implementation. This proposal should probably be a discussion in this repository, instead.

**Comment by smix8** [comment]
Moonray is an MCRT renderer e.g. for movie production, not a realtime renderer. Pointless for a game engine that wants to stay above 0.01 fps.

**Comment by Calinou** [comment]
This is out of scope for Godot; closing per the above comments.

Note that since Godot 4.0 and later can export the scene to a glTF file, you can use this to perform offline rendering of a Godot 3D scene in another rendering engine.
