### ISSUE TITLE
Improve presentation of "Advanced Settings" in project settings

### ISSUE THREAD

**Issue by trollusk** [godotengine/godot-proposals#6530]
### Describe the project you are working on

Assisting a new user to learn Godot via a 2D tutorial series.

### Describe the problem or limitation you are having in your project

Several quite basic settings are hidden behind "Advanced Settings" in the project settings dialog. For example:
- Resizing the window independent of the viewport (the first thing everyone does when they make a pixel art game)
- All debug options

This is frustrating for new users as the Advanced Settings toggle is very non-obvious.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

One of:

When a filter search fails in the Project Settings dialog, but there are hidden advanced settings which match the search string, then show a message in the right panel indicating this (see below for example)

Get rid of the Advanced Settings toggle, and instead show the settings as visually separate from basic settings within each setting category, eg in a different colour, grouped at the bottom, or with "(Advanced)" after their name. This way they will still show up in a search.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![Untitled](https://user-images.githubusercontent.com/220468/226141691-d6b5f260-83d0-4f28-ba70-5dae040b0e78.png)

![Untitled](https://user-images.githubusercontent.com/220468/226142101-9cd5ec89-7adb-4710-a737-117fcb093246.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's an editor UI issue.

### Is there a reason why this should be core and not an add-on in the asset library?

Improving editor usability for new users.

**Comment by YuriSizov** [comment]
> When a filter search fails in the Project Settings dialog, but there are hidden advanced settings which match the search string, then show a message in the right panel indicating this (see below for example)

I think there is an agreement already that when filtering advanced options should pop up regardless of the toggle.

**Comment by timothyqiu** [comment]
See also https://github.com/godotengine/godot/pull/70430 and https://github.com/godotengine/godot/pull/69324.

**Comment by RedMser** [comment]
This has been merged and can be closed.

**Comment by Calinou** [comment]
Implemented by https://github.com/godotengine/godot/pull/69324.
