### ISSUE TITLE
Add toggle to remove blending filter effect on viewport textures in 4.0.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot-proposals#6531]
### Describe the project you are working on

I am translating my Atlas-viewport texture to 4.0 which generates solid colors using color rects (in a grid-like formation) for block UVs in my (minecraft-like) terrain meshes. Basically the viewport texture is my color palette.

### Describe the problem or limitation you are having in your project

I found that there's a filter over viewport textures which blends colors together, this means that there's a risk of the edge of my mesh tris bleeding with other colors in the atlas texture if they are too close. So I will have to fiddle with adding extra spacing between my UVs so they aren't too close to other colors. 
As well as making the viewport resolution very high so that the blurring effect is minimized depending on how many colors I use in the color palette I generate.

This is a 2x2 subviewport with 2, 1x1, `Color Rects` beside each other as the viewport texture of a quadmesh:

# 3.5:
![3 5](https://user-images.githubusercontent.com/34152090/226148694-05c151e9-0582-40e8-a6c7-2a4ca2b43950.PNG)
# 4.0:
![4 0](https://user-images.githubusercontent.com/34152090/226148700-7e65e76a-0fb6-412a-90c3-b76f301f1124.PNG)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to disable this blending effect so that I can easily map my UVs onto the color rects without needing to worry about colors bleeding together.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

checkbox somewhere.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be finnicky to work around. 

### Is there a reason why this should be core and not an add-on in the asset library?

Is this tied to the Vulcan renderer?

**Comment by Calinou** [comment]
Filter properties are set on the material rather than the texture now. Check the **Sampling** section of the BaseMaterial3D.
