### ISSUE TITLE
A function to generate 1d parabolas

### ISSUE THREAD

**Issue by Flipkickisreal** [godotengine/godot-proposals#6532]
### Describe the project you are working on

A space warlord organ trading style management sim for gun building

 

### Describe the problem or limitation you are having in your project

I want to have charts showing the breakeven points for price per unit vs price for tooling to produce anything.   simple ask mathematically, complicated graphically, the current workaround (which doesn't work in compatibility mode) is to make a trailed particle, and adjust the gravity as needed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Generating 1d parabolas from defined parameters in engine would allow for more uses of Godot in more fields, being able to generate graphs automatically from provided data and such.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/42154453/226150041-ac84d181-6cec-4876-8e5f-9b72d2eb6d8b.png)

enter code, get graph. I'm sorry but I haven't the foggiest where to start to program this

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around with an editor program, but it has not been upgraded to GD 4

### Is there a reason why this should be core and not an add-on in the asset library?

Maybe split the difference and make it an official add on

**Comment by Flipkickisreal** [comment]
NVM

**Comment by Calinou** [comment]
Closing per the above comment.
