### ISSUE TITLE
Allow copy-pasting node property names in the inspector

### ISSUE THREAD

**Issue by rezgi** [godotengine/godot-proposals#655]
**Describe the project you are working on:**
Making a UI for my game and I wanted to change the font color of my label on a certain event.

**Describe the problem or limitation you are having in your project:**
To change a property within my code, I hover on the said property shown in the inspector, then have to remember it and write it in my code. My brain is the limitation here.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I propose to be able to right-click on any inspector property to copy its code equivalent in order to quickly use it in code.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If I want to change dynamically a label font color for example : Select the Label node > Go to Control / Custom Colors / Font Color. On hover the info tip shows the code property `custom_colors/font_color`. Then I right-click on the property and select 'Copy property code' or something like that. Now I can juste paste it in my code !

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yeah no big deal, just use our code-overloaded brain to remember one more information :)

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a quality-of-life improvement, saves you milliseconds ! It has no price.

**Comment by Calinou** [comment]
> If I want to change dynamically a label font color for example : Select the Label node > Go to Control / Custom Colors / Font Color. On hover the info tip shows the code property custom_colors/font_color. Then I right-click on the property and select 'Copy property code' or something like that. Now I can juste paste it in my code !

Actually, that one is a special case. This is a Control "custom color", not a property, so you have to set it using `add_color_override("name", Color())`.

**Comment by rezgi** [comment]
Yeah I know but I was submitting the idea for all properties in all nodes, but I guess that it's a bit redundant to copy `visible` just for 'Visible' or `modulate` for 'Modulate'. So maybe this proposal isn't really useful for most cases. Should I close the proposal ?

**Comment by Calinou** [comment]
@rezgi No, I definitely think it's useful. We just need to figure out how to add a context menu to EditorInspector.

**Comment by rezgi** [comment]
Ok. In this case, adding a context menu could open many more possibilities, not only to copy property code. Another way of using this feature is by having a quick-find menu like in other IDEs (search for a property keyword and having its doc link as well as an option to copy the code equivalent), but I guess it has already been proposed in some other thread ?

**Comment by Calinou** [comment]
> Another way of using this feature is by having a quick-find menu like in other IDEs (search for a property keyword and having its doc link as well as an option to copy the code equivalent), but I guess it has already been proposed in some other thread ?

I remember seeing a proposal about this, but I can't find it right now.

**Comment by rezgi** [comment]
Yeah I've searched for it but didn't find it neither. I think that maybe this proposal would be better implemented in a more general UX feature like the quick menu. If I find it I'll link this feature there.

**Comment by pycbouh** [comment]
It is now possible to drag and drop the property path from the inspector into the code https://github.com/godotengine/godot/pull/51628. I think that rules out the right-click, or double-click approach. If we were to handle the right click, a context menu would be a better option https://github.com/godotengine/godot-proposals/issues/3098.

So I think it's okay to close this in favor of all the other linked proposals.

**Comment by elvisish** [comment]
> It is now possible to drag and drop the property path from the inspector into the code [godotengine/godot#51628](https://github.com/godotengine/godot/pull/51628). I think that rules out the right-click, or double-click approach. If we were to handle the right click, a context menu would be a better option #3098.
> 
> So I think it's okay to close this in favor of all the other linked proposals.

Thanks, I didn't know this was possible! I think since it's so unobvious that it can be done it should be a little more explicitly labeled as it's really useful when you need a long path name.
