### ISSUE TITLE
Add a more precise way to edit gradients

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#6555]
### Describe the project you are working on

A lowres pixel art game

### Describe the problem or limitation you are having in your project

Having exact values on a gradient is difficult and while possible, it forces you to go edit its raw data.

Here are some places where easier exactness of values would have helped:

- Matching up to pixels, i.e. a set of gradients with constant interpolation representing all possible states of a 6px wide healthbar.
- Two gradients with timing that must match up.
- A gradient that represents the color ramp of particles that need to stay for a few seconds, then blink a few times with equal timing between blinks and then disappear. (special effect after breaking something)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A few things could help.

- Showing the exact offset somewhere
- Having a way to edit a point's offset exactly directly from the editor
- Adding a snap button

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/85438892/213755937-c378c101-97ed-44f9-ad43-a845e14669ac.png)

![image](https://user-images.githubusercontent.com/85438892/213762435-30277c4c-1bf4-445e-9a09-72748e359bda.png)

Quite straightforward, when adding or moving points they get snapped to the "grid".

The first example use case would be solved by having 6 snapping partitions. The second use case can be solved by the two gradients having the same number of partitions and choosing the same place on the "grid". The third use case can be solved by having a larger number of partitions and displacing the last few points by 1 section of the grid.

Showing the offset to edit manually is also a nice idea, but two clicks already show the color editing popup, and it might not be the best idea to concern people with offsets when editing gradients.

A little unfortunately, but the snapping grid would be hard to see when working with some colors, but it shouldn't be too bad

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Would be used often, both for legit use cases and because people like clean numbers.

### Is there a reason why this should be core and not an add-on in the asset library?

Simple usability feature to an editor that has plenty of free space to spare.

**Comment by hsandt** [comment]
Another issue I often have is that I click on gradient key points with are also handles, only to modify the colors. But if you hold the mouse button for a few tenths of seconds, it triggers a drag and moves the handle. It's super sensitive so I often move the handle by a few pixels inadvertently.

I was about to suggest a new proposal for more stable handles: make the gradient handles stay still if you click on one and release within a short amount of it, but it seems snap could cover that case (assuming the handle is already snapped, or we use snap relative to the previous position).

If snapping is purely absolute though, for cases when handles are not already snapped but we don't want to move them either, more stable handles may need a separate proposal.
