### ISSUE TITLE
Camera2D zoom smoothing

### ISSUE THREAD

**Issue by twoco** [godotengine/godot-proposals#6557]
We could add "Zoom Smoothing" in addition to "Position Smoothing" and "Rotation Smoothing" (see screenshot).

<img src="https://user-images.githubusercontent.com/53160891/227042488-68a11cd1-58b6-4ed6-9500-fcf7638a3eea.png" width="300" />

Of course, a simple script can do the job too. But I think for the sake of completeness to position and rotation we could add this.

```gdscript
func _process(delta):
  zoom = lerp(zoom, zoom_target, 0.1)
```

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
