### ISSUE TITLE
Add global "editor-only" addons/plugins

### ISSUE THREAD

**Issue by rsubtil** [godotengine/godot-proposals#6561]
### Describe the project you are working on

Multiple Godot projects with different addons

### Describe the problem or limitation you are having in your project

There are some plugins that are essentially "global", in the sense that they don't introduce any changes to the project that require the plugin to be active on released versions, are are thus only used in the editor. Generally speaking, this encompasses plugins that only add or modify existing editor tools.

Here are some examples:

- [godot-wakatime](https://github.com/thomazthz/godot-wakatime) - Interface for [WakaTime](https://wakatime.com), a metrics platform to track development time in projects.
- [godot-aseprite-wizard](https://github.com/viniciusgerevini/godot-aseprite-wizard) - Import plugin for [Aseprite](https://www.aseprite.org/), an "animated sprite editor & pixel art tool".
- [Selection Shortcuts](https://github.com/DaelonSuzuka/SelectionShortcuts) - Shortcuts for 2D editing.
- [Node Referencer](https://github.com/SanderVanhove/node-referencer) - Reference nodes quickly in scripts.
- [Code Snapshot](https://github.com/fenix-hub/godot-engine.code-snapshot) - Generate beautiful screenshots of code snippets.

However, currently, all of these plugins need to be installed on a given project to be used. This becomes a pain when dealing with multiple projects, especially with cooperative projects. Solutions such as `gitignore`'ing plugins are also not ideal, as there's always new plugins and requires constant maintenance of such cases.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The proposal is about introducing another plugin type that runs separately from the project, and only at the editor level. Likewise, these plugins wouldn't be stored in project files, instead being saved in the editor's settings folder.

Beyond separating plugins from project files, it also allows plugins to be used globally in every project, which improves the workflow a lot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The idea is to introduce a new plugin type (e.g. `EditorOnlyPlugin`). Such plugins would effectively be restricted to editor actions only, and any modifications to project files need to take into consideration that this plugin will not be running during the project.
Likewise, these plugins would not included on project exports. Since they would be stored separately from project files, this should be very easy to enforce.

Likewise, extra interfaces should be added to both the AssetLib section and Editor Settings to install and manage these editor-level plugins.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Possibly with a plugin to manage plugins? But that's just going "turtles all the way down"

### Is there a reason why this should be core and not an add-on in the asset library?

This is core functionality that AFAIK cannot be bypassed.

**Comment by KoBeWi** [comment]
Related: #831

**Comment by rsubtil** [comment]
Thanks, I'll close this since there's plenty of discussion and existing issues related to this *(I can never find the right keywords to search for, dammit :sweat_smile: )*
