### ISSUE TITLE
Add support for automatic LOD generation

### ISSUE THREAD

**Issue by WilliamTambellini** [godotengine/godot-proposals#657]
**Describe the project you are working on:**
no specific project but evaluating godot over other solutions

**Describe the problem or limitation you are having in your project:**
Import a mesh but see that godot does nt seem to be capable to generate any lod automatically ("autoLOD")

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
autoLOD : 
![image](https://user-images.githubusercontent.com/109458/78087730-e0054b80-7376-11ea-88cc-3d336d4f4250.png)
https://docs.unrealengine.com/en-US/Engine/Content/Types/StaticMeshes/HowTo/AutomaticLODGeneration/index.html
how it helps: import a model (whatever the format), godot to generate 1 or more lods : 
- at runtime  
- and/or import time

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
As a 1st implementation, a gdscript only solution would be good enough (no ui/editor):
- import a model
- call a gdscript function to generate a LOD of a MeshInstance at a given precision level

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
should be used pretty often

**Is there a reason why this should be core and not an add-on in the asset library?:**
A quadratic mesh simplification style algo has to be in core cpp. I have searched and did nt find an asset lib to do generate lod but perhaps I missed something.
Refs:
https://docs.unrealengine.com/en-US/Engine/Content/Types/StaticMeshes/HowTo/AutomaticLODGeneration/index.html
https://docs.unrealengine.com/udk/Three/MeshSimplificationTool.html
https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification
https://doc.cgal.org/latest/Surface_mesh_simplification/index.html
https://software.intel.com/en-us/articles/3d-modeling-and-parallel-mesh-simplification/

kind

**Comment by Calinou** [comment]
This is planned in Godot 4.0.

**Comment by gitcatrat** [comment]
There should definitely be a programmatic API for this as well, let's not exclude procedural meshes.

**Comment by fire** [comment]
The approach for singular meshes I described to reduz was.

1. have a static vertex array
1. indexes are changed based on lod
1. https://github.com/godot-extended-libraries/mesh_lod/tree/master
1. https://github.com/HungryProton/concept_graph/issues/44#issuecomment-629863488

I have done the implement of this as a module and as a gdnative code for concept graph.

**Comment by lupoDharkael** [comment]
Closed by https://github.com/godotengine/godot/pull/44468 ?

**Comment by clayjohn** [comment]
@lupoDharkael thanks. :) 

Closed by https://github.com/godotengine/godot/pull/44468
