### ISSUE TITLE
Add more Panel and PanelContainer styles

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#6584]
### Describe the project you are working on

Windows 95 theme

### Describe the problem or limitation you are having in your project

Windows 95 has an idea of sunken 3d, raised 3d, sunken, raised, and flat.
This is not just win32 api but also other retro desktop look alikes

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

And add the following to the category...
Add sunken 3d style
Add raised 3d style
Add sunken style
Add raised style
Rename panel style to flat
Add property called border_style to Panel and PanelContainer which takes in a PanelBorderStyle enum
..Which would contain the enum values...
Flat,
Sunken
Raised
Sunken3D
Raised3D

Flat may be a bad name maybe it might be better to keep it called Normal but I suggested Flat due to the fact that's would it would be used for in most cases

I don't know about the 3D in the enum and style name that's just how I would do it. It could be called something like Sunken2 and Raised2 but idk.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Examples of what the styles would be used for...

sunken 3d style
![image](https://user-images.githubusercontent.com/2453707/228097206-d6ea0eb1-b9eb-4bd5-bd29-bfa125cc309b.png)

raised 3d style
![image](https://user-images.githubusercontent.com/2453707/228097122-a3114dd5-63fb-46cf-a230-ab1ec46720c9.png)

sunken style
![image](https://user-images.githubusercontent.com/2453707/228097308-39e85b06-ce3d-4061-b135-0ff31e203426.png)

raised style
![image](https://user-images.githubusercontent.com/2453707/228097406-d584bedd-8f28-4e23-b560-7dd0f869b33d.png)

flat
![image](https://user-images.githubusercontent.com/2453707/228097444-226cadd9-9aba-4430-8faa-62c3ce67038f.png)

here is a picture of me using it for Panel and PanelContainer
![image](https://user-images.githubusercontent.com/2453707/228098454-e60e84a7-e6f5-4b9b-bd19-ba9488dc2027.png)

The TaskBar is a Panel and the rect around the time is a panel container whos PanelBorderStyle might change depending on where it is and what it's used for
### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around but not with themes

### Is there a reason why this should be core and not an add-on in the asset library?

It makes Godot Themes more customizable

**Comment by Shadowblitz16** [comment]
Note things like modern ui wouldn't use this and would probably set all the styles to the same thing

**Comment by Calinou** [comment]
Sunken/raised styles require support for per-border colors in StyleBoxFlat, which weren't implemented when StyleBoxFlat was added as it was complex to get right with rounded corners.

**Comment by Shadowblitz16** [comment]
Ye borders tend to require lines which are not the best in GPU drawn graphics, I can't imaging also doing rounded corners. 

Anyways textures do just fine for this sort of thing.

**Comment by YuriSizov** [comment]
This is very specific to your particular theme, and can be easily achieved with StyleBoxTexture.

**Comment by Shadowblitz16** [comment]
> This is very specific to your particular theme, and can be easily achieved with StyleBoxTexture.

it specific to any retro desktop theme.
All old school desktop gui's had this feature.
It's not specific to just my needs

**Comment by YuriSizov** [comment]
> It's not specific to just my needs

What I mean is that this is very specific to the exact style you are trying to replicate. It's not a general problem, and there are many more styles of UI that this does not help. So adding specific settings here wouldn't be a proper solution. Especially, when you can already implement the look with StyleBoxTexture. These are a perfect solution for this kind of look.

**Comment by davthedev** [comment]
Beveled StyleBox is implemented. While I arranged the gradient feature, I could add some color calculation logic that made the frame looks like a button or a sunken frame quite easily.
See https://github.com/godotengine/godot/pull/77215

You can make a simple bevel with one color.

**Comment by Shadowblitz16** [comment]
There are currently suggestions that would revamp the themes system to be more dynamic so I'm closing this.
