### ISSUE TITLE
TileSet:  `#/shapes` field not properly represented in inspector context

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot-proposals#66]
**Describe the project you are working on:**
Game relying on autotile sets with varying Material properties but identical Textures

**Describe how this feature / enhancement will help your project:**
For `TileSet` specifically and not `TileSetContext`,  the tile properties for `#/shape` are always set to what seems to be the first index in the `#/shapes` subresource collection.  This makes it impossible to copy the collection container from one tile and paste it inside another in the inspector when a `TileSet` is the current item.  

This may not be considered a bug, so I filed it here to the proposals repo.  ~~I will file a separate bug in the main repo and link it here explaining why this functionality is important.~~ *(edit:  [here](https://github.com/godotengine/godot/issues/32136))*  Short reason:  It seems not possible at the current time to get `TileSetContext` to stay "focused" on the correct tile resource when editing collision shapes sharing a texture, making it impossible to alter the collision mask collection inside the editor.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/1023003/64911453-92c9d100-d6e7-11e9-8a3e-ca174301a9f9.png)

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Possibly.  An extension or seperate application could be written using the exposed functionality of `TileSet` to get an ID's shape array, copy it, and manually re-add each shape to another ID.  The underlying implementation of `TileSet` changed between 3.0->3.1, however, and it's unclear if the implementation will break compatibility for future scripts, or if subresource references for shapes will confuse the TileSet tab in the editor or the TilesetEditorContext.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is "missing functionality" which makes it difficult to modify tilesets in editor.  If the TileSet editor tab itself didn't get confused about which tileID it's on when changing "Coordinate" in the Collision subtab, collision shapes could be manually re-made.  The relevant bug necessitating some kind of feature (such as this proposal) or a fix is located here:  https://github.com/godotengine/godot/issues/32136

**Comment by fire** [comment]
Something similar is that in GridTiles in 3d, the physics properties are lost when combined, I took a look a few months ago but it seems like the same problem as this one.
