### ISSUE TITLE
[Font] Implement font_get_glyph_index_from_char function

### ISSUE THREAD

**Issue by LucasParsy** [godotengine/godot-proposals#6602]
### Describe the project you are working on

Godot program with custom RichTextEffect from https://github.com/teebarjunk/godot-text_effects
the effect I wanted to use  replaced characters with their capitalized version.

### Describe the problem or limitation you are having in your project

Cannot easily replace characters from ascii codes 
in Godot 3 you had the `CharFXTransform.character` field
But now in Godot4, using glyphs, this property was removed.

example of a text FX that replace all characters 'R' with "W"
on Godot 3 we could do:
```gdscript
func _process_custom_fx(char_fx: CharFXTransform):
   if char_fx.character == ord("R"):
      char_fx.character = ord("W")
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

inverse of  https://github.com/godotengine/godot/pull/74149 (`get_char_from_glyph_index` implementation)
a method to get the ascii / utf-8 code from a font and a glyph index

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

On Godot 4, as we are using glyphs, the code would be more complicated:
example of a text FX that replace all characters 'R' with "W"

```gdscript

static func ord(char: String) -> int:
	return char.to_ascii_buffer()[0]

static func get_character(char_fx: CharFXTransform) -> int:
    return font_get_char_from_glyph_index(char_fx.font, 1, char_fx.glyph_index)

static func set_character(char_fx: CharFXTransform, index: int):
   char_fx.glyph_index =  font_get_glyph_index_from_char(char_fx.font, 1, index)


func _process_custom_fx(char_fx: CharFXTransform):
   if get_character(char_fx) == ord("R"):
      set_character(char_fx, ord("W"))
```

looks a bit more complex and less efficient, but it would work!
( or reimplement `CharFXTransform.character`, but it may not be possible) 

Note that I am not certain of the usage of the parameter "size" (2nd one) of `get_char_from_glyph_index`, and I didn't tested it yet.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

nope, or please tell me!

### Is there a reason why this should be core and not an add-on in the asset library?

because it's reimplementing previously working features.

**Comment by LucasParsy** [comment]
... thank you for your knowledge, I prefered writing a long issue than reading the doc apparently.
thanks for the quick reply!

**Comment by AThousandShips** [comment]
No problem!
