### ISSUE TITLE
Add a compact lambda syntax

### ISSUE THREAD

**Issue by PoolloverNathan** [godotengine/godot-proposals#6614]
### Describe the project you are working on

A city-building game (currently the file manager)

### Describe the problem or limitation you are having in your project

The `func()` syntax for a lambda is slightly too verbose, especially compared to JS's `() =>`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This enhancement will add additional syntax for specifying a lambda that is less verbose than the existing syntax.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# No arguments:
var no_arguments = () ->
  return 1
var no_arguments_oneline = () -> return 1
# No arguments, with implicit return:
var no_arguments_implicit = () => 2
# Arguments:
var one_arg = (a) => a * 2
var one_arg_typed = (a: float) => a * 2
# Argument list can be omitted for 0 arguments:
var no_arguments_no_list = => 2
# Possible other syntax for specifically variable definitions:
#var no_arguments_no_list_var => 2
# Parentheses can be omitted for 1 argument:
var one_arg_no_parentheses = a => a * 2
var one_arg_typed_no_parentheses = a: float => a * 2
```

### Is there a reason why this should be core and not an add-on in the asset library?

As far as I know, it is impossible to modify GDScript syntax with a script or addon.

**Comment by AThousandShips** [comment]
This was already mentioned and rejected in the original proposal for lambdas #2431

**Comment by dalexeev** [comment]
* See also: #5925

**Comment by KoBeWi** [comment]
`() =>` is just 2 characters shorter than `func():`...

**Comment by dalexeev** [comment]
I would prefer `func (x) => x + 1` (or `fn` like in PHP) since we can't use arrow functions due to parser limitations. Just removing `return` without any other difference is a bad idea in my opinion as it adds ambiguity.

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP).
