### ISSUE TITLE
Optimize for size when exporting

### ISSUE THREAD

**Issue by BenStigsen** [godotengine/godot-proposals#662]
**Describe the project you are working on:** None at the moment, but I intend to use it for software development as well as games in my spare time.

**Describe the problem or limitation you are having in your project:** So currently there's ability to enable/disable debug when exporting, but it'd be nice if there was the ability to disable stuff like 3D when it's unnecessary and a bunch of other options. Options like these: https://docs.godotengine.org/uk/latest/development/compiling/optimizing_for_size.html but available in the GUI instead.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** This would lower the file size of games (and software, which I was actually planning to use it for). The Godot project is of high quality and I think a small file size for games / applications helps reflect that. _(I'm also of the personal opinion that I don't like arguments such as "why would you need to lower the file size a couple of MB when everyone's harddrive has several GB". Just because someone's computer **can** handle that much, it shouldn't have to be necessary)_

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** Export > Advanced Settings > "disable 3D", "some more settings", etc...

**If this enhancement will not be used often, can it be worked around with a few lines of script?: This enhancement will definitely be used quite often.**

**Is there a reason why this should be core and not an add-on in the asset library?:** The ability to export with advanced settings should definitely be core. Why? I'm not quite sure what a good reason is. To put focus on the quality of Godot and doing this by also avoiding unnecessarily large games/applications.

**Comment by Calinou** [comment]
> Options like these: https://docs.godotengine.org/uk/latest/development/compiling/optimizing_for_size.html but available in the GUI instead.

This is unfortunately not feasible due to all the dependencies you need to install to build Godot for various platforms. It gets even worse for macOS and iOS as you can only build for those if you're already on macOS.

**Comment by BenStigsen** [comment]
Okay I understand, I've found another solution though that I'm going to make available online. 

I just tested this with my simple GUI text editor. With 3D disabled it went from 33 MB to 24 MB. That's a 27% decrease in file size. And with several modules disabled I got it to 22 MB, a 33% decrease in file size. Which for me matters quite a lot since it didn't require a lot to do.

Should I close this issue?

**Comment by Calinou** [comment]
@BenStigsen Since this repository is intended to host proposals that can be reasonably integrated into Godot core, I think this issue should be closed.

The only way I could see this being officially supported is by providing prebuilt export templates that have 3D disabled, but it's a lot of work and will require much more time to build all export templates. (Remember that we already have to build two sets of export templates: one without Mono, one with Mono.)

**Comment by BenStigsen** [comment]
Oh right, forgot about the mono version as well. How would I export with/without mono version?

**Comment by BenStigsen** [comment]
I'm guessing the Godot source is Mono by standard?

**Comment by BenStigsen** [comment]
As a side note, I've now been able to get the file size down to 19.9 MB from 33 MB, a 40% decrease in file size.
