### ISSUE TITLE
Add an honeycomb/hexagon collision shape

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-proposals#663]
**Describe the project you are working on:**
client server
**Describe the problem or limitation you are having in your project:**
I have difficult to setup team in field when I use current collision shapes
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

I wold like to have a honeycomb collision shape
https://en.wikipedia.org/wiki/Honeycomb_structure
https://en.wikipedia.org/wiki/Hexagon

to minimize space
to set an ordered structure
to allow a more fluid and structured movement  (using move and slide)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

We have already a "circle" shape that isn't really a circle but a https://en.wikipedia.org/wiki/Icositetragon

It will suffice to make a new shape from it and divide its sides by 4 :)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I have no idea :)
**Is there a reason why this should be core and not an add-on in the asset library?:**
Of course :)

**Comment by groud** [comment]
> We have already a "circle" shape that isn't really a circle

If I am not mistaking, only the visible circle is a polygon. Internally the collisions behave as if it was a perfect circle.

**Comment by git2013vb** [comment]
> > We have already a "circle" shape that isn't really a circle
> 
> If I am not mistaking, only the visible circle is a polygon. Internally the collisions behave as if it was a perfect circle.

No idea. :)
Off-Topic:  How I can show just the perimeter for any collision shape? Silly question I know :)

**Comment by Calinou** [comment]
> Off-Topic: How I can show just the perimeter for any collision shape? Silly question I know :)

Do you mean displaying only the edge without filling the inside? I'm afraid that's not possible unless you write a script to do this manually.

**Comment by aaronfranke** [comment]
> **If this enhancement will not be used often, can it be worked around with a few lines of script?:**
> I have no idea :)
> **Is there a reason why this should be core and not an add-on in the asset library?:**
> Of course :)

Closing due to the proposal template not being properly filled out.

If you are proposing an addition to Godot, you must provide justification.

**Comment by git2013vb** [comment]
You close my request due of no reasonable motivations
Thank you for your effort.
 There are my justifications:
If you even bother to read my post.
> to minimize space
> to set an ordered structure
> to allow a more fluid and structured movement (using move and slide)

**Comment by aaronfranke** [comment]
Those are not justifications for being included in the engine, they are justifications for your use case.

**Comment by git2013vb** [comment]
> Those are not justifications for being included in the engine, they are justifications for your use case.

If I can use for my case so everyone can do the same.  I still not understand your hidden meaning

**Comment by aaronfranke** [comment]
This is why the question "Is there a reason why this should be core and not an add-on in the asset library?" exists. If other people can find it useful, then this feature can be placed in an asset. Then anyone can open Godot, [search the asset library](https://godotengine.org/asset-library/asset) for "hexagon", and download an asset with this feature.

GitHub is not a support forum, if you'd like help consider asking on Discord or Reddit or [elsewhere](https://godotengine.org/community).

**Comment by git2013vb** [comment]
> This is why the question "Is there a reason why this should be core and not an add-on in the asset library?" exists. If other people can find it useful, then this feature can be placed in an asset. Then anyone can open Godot, [search the asset library](https://godotengine.org/asset-library/asset) for "hexagon", and download an asset with this feature.
> 
> GitHub is not a support forum, if you'd like help consider asking on Discord or Reddit or [elsewhere](https://godotengine.org/community).

Is related with Collision Shape. Nothing else. If you can read again my post you understand that is not related to any plugin.

**Comment by aaronfranke** [comment]
For example, [CollisionPolygon2D](https://docs.godotengine.org/en/latest/classes/class_collisionpolygon2d.html) can become any shape if you specify vertices.
