### ISSUE TITLE
Implement Eye Dome Lighting post-processing effect

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot-proposals#6633]
### Describe the project you are working on

tunnelvr, a VR cave map drawing application, which can work from point clouds

### Describe the problem or limitation you are having in your project

I spotted a really nice feature in the potree point cloud system that makes depth changes stand out in spite of the fact that points are usually flat shaded.  

Here is a demo from [potree](http://potree.org/potree/examples/classifications.html)

With EDL:
![image](https://user-images.githubusercontent.com/677254/229559936-cf7301ac-cb66-4ce2-9395-bcf9939d68f8.png)
Without EDL:
![image](https://user-images.githubusercontent.com/677254/229559766-a4a04908-0e7a-404c-9bcd-befaa8164d1a.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This is now a pretty standard post-processing feature that is applied to point cloud data to make it the depth changes in the points visible.

It's important enough to be a tickbox feature in [Unreal Engine](https://docs.unrealengine.com/4.27/en-US/WorkingWithContent/LidarPointCloudPlugin/EnableEyeDomeLightingMode/) and [Unity](https://www.youtube.com/watch?v=Wh2bRURxjaA), as well as any point cloud visualizers such as CloudCompare and Potree.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There are a set of post-processing features controlled by the World Environment node, such as Glow and Fog, that involve running a pixel shader across the whole of the image with access to the depth buffer.  This feature should exist as one of those on/off options, with the various settings (radius, strength, opacity) opened up when it is enabled.    

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Unfortunately there is no way to edit the image post processing GPU shader defined by the World Environment, in the same way that we can edit the Material Shaders (by converting them from Spatial Material to Shader Material is which it is possible to hand edit the shader code), or there would be a potential work around by adding code to that.

The code that can be used in Unity to implement it is here:
https://github.com/SFraissTU/BA_PointCloud/blob/master/PointCloudRenderer/Assets/Resources/Shaders/EDL.shader

### Is there a reason why this should be core and not an add-on in the asset library?

As stated above, unless the post-processing World Environment shader is editable, it can't be done other than as a feature that is directly included in this core node.

**Comment by Calinou** [comment]
> Unfortunately there is no way to edit the image post processing GPU shader defined by the World Environment, in the same way that we can edit the Material Shaders (by converting them from Spatial Material to Shader Material is which it is possible to hand edit the shader code), or there would be a potential work around by adding code to that.

It is possible to create [custom post-processing effects](https://docs.godotengine.org/en/stable/tutorials/shaders/advanced_postprocessing.html), including [effects that use the depth buffer](https://docs.godotengine.org/en/stable/tutorials/shaders/advanced_postprocessing.html).

**Comment by Calinou** [comment]
> I still feel it would make more sense if this sort of post-processing step could be done by attaching a shader to the WorldEnvironment or the Camera in order to apply the effect across the whole picture, instead of to some random mesh that you have to keep in view of the camera. It seems like a hack to do it that way.

- See https://github.com/godotengine/godot-proposals/issues/2196.
