### ISSUE TITLE
Show a hint on script-editor if signal args not match on connect() / emit() in compile time rather than runtime

### ISSUE THREAD

**Issue by jzq740176597** [godotengine/godot-proposals#6636]
### Describe the project you are working on

3d

### Describe the problem or limitation you are having in your project

> signal mouse_clicked(event: InputEventMouseButton)

1. > mouse_clicked.connect(func(evt): selected = true)

I can only be notified the error if lamda function missing evt ON RUNNING

2. > mouse_clicked.emit(event)
see above

running to debug is cubersome, rather than if **spot it earlier before running **

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Show a hint/warning on script-editor if signal args not match

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

*

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

core

**Comment by YuriSizov** [comment]
Signals contain no type information, so this is currently not possible. There are plans to introduce a way for the engine to type signals and callables, but no ETA on that yet.

Please stop opening low effort proposal issues in bunches. Use discussions and community platforms instead.
