### ISSUE TITLE
support unary 'not' for types that support implicit to bool

### ISSUE THREAD

**Issue by jzq740176597** [godotengine/godot-proposals#6644]
### Describe the project you are working on

3d

### Describe the problem or limitation you are having in your project

> 	var pos:= Vector3.ONE
> 	
> 	if pos:
> 	____	pass
> 	else:
> 	_____#acutual code

I have to wirte additional **ELSE CLAUSE** while should exec code on [**!pos**], it's mess & tedious

> 	if !pos:
> 	____#acutual code

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

> 	if pos:
> 	____pass

why not /can't support:

> 	if !pos:
> 	____pass

it's reasonable & neat!

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

core

**Comment by AThousandShips** [comment]
This is already tracked as a bug in godotengine/godot#44688
