### ISSUE TITLE
Add newline after issueing a line comment

### ISSUE THREAD

**Issue by sanderfoobar** [godotengine/godot-proposals#6647]
### Describe the project you are working on

Any project that has GDScript

### Describe the problem or limitation you are having in your project

cant create comments quickly enough

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Toggling line comments with `CTRL-K` should, in my opinion, also advance to the next line. That way, if one spams the `CTRL-K` shortcut, one may quickly add multiple lines of comments. This prevents one from first having to select a block of text with the mouse. So it's more efficient.

This 'line commenting behavior' is the default in any of the intellij IDEs; pycharm, clion, etc (I did not just make this up).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add `\n` ? :P

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Everyone will use this feature

### Is there a reason why this should be core and not an add-on in the asset library?

the code editor is core

**Comment by Calinou** [comment]
Visual Studio Code doesn't behave like this:

https://user-images.githubusercontent.com/180032/230445807-ddfd48b5-8673-4122-946c-a7de19f5156b.mp4

I prefer keeping the current behavior in the Godot script editor too.
