### ISSUE TITLE
Add tab metadata to TabBar & TabContainer

### ISSUE THREAD

**Issue by ShadyChibinko** [godotengine/godot-proposals#6664]
### Describe the project you are working on

A GUI heavy add-on with multiple editors that use tabs.

### Describe the problem or limitation you are having in your project

In nearly every instance of using a TabBar, I've had the need to associate each tab with its own set of data. This way when the tab is changed, the last tabs data can be swapped out for the current tabs. This is doable through use of an Array, where each index mirrors a tab. Originally I was just copy pasting the Array approach in all scripts that used a TabBar, but it eventually became so commonplace that I settled on a "TabBarWithData" script to attach to every TabBar. In seeing the amount of usage I got out of such a simple script, I figured tab metadata should just be an inherent part of the TabBar class.

As far as TabContainer goes, metadata isn't as much of an issue as the associated data of each tab is generally considered to be the child node it represents. So you can just store all the data you need in the child node itself. However, that's not to say there haven't been instances where children are independent enough from the TabContainer, that storing metadata on them feels improper. Regardless, I figure if TabBar has metadata methods, it makes sense for TabContainer to include them as well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

TabBar & TabContainer will implement two new methods for getting and setting metadata on tabs, This would eliminate the need to manually track and manage it through use of an Array or script. Metadata should stick to whatever tab it's set on so if tabs are ever repositioned, their metadata stays with them. Much like how ItemList, PopupMenu, OptionButton and TreeItem implement metadata, these new methods could be as follows:

- `set_tab_metadata(index: int, data: Variant)`: Sets the metadata at tab 'index' to 'data'.
- `get_tab_metadata(index: int)`: Returns the metadata stored at tab 'index'.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's an example script demonstrating how TabBar metadata could work in a basic text editor. TabContainer usage would look identical:

```
extends MarginContainer

onready var tab_bar : TabBar = get_node("VBoxContainer/TabBar")
onready var text_edit : TextEdit = get_node("VBoxContainer/TextEdit")


func _ready() -> void:
	tab_bar.tab_changed.connect(_on_TabBar_tab_changed)
	
	# Create example tabs.
	tab_bar.add_tab('Document 0')
	tab_bar.add_tab('Document 1')
	tab_bar.add_tab('Document 2')
	
	# Set arbitrary data for each example tab.
	tab_bar.set_tab_metadata(0, {'text': 'Hey Hello Hi', 'minimap_draw': true, 'draw_spaces': true, 'draw_tabs': true}
	tab_bar.set_tab_metadata(1, {'text': 'Adieu Goodnight Bye', 'minimap_draw': true, 'draw_spaces': false, 'draw_tabs': false}
	tab_bar.set_tab_metadata(2, {'text': 'Yes Maybe No', 'minimap_draw': false, 'draw_spaces': false, 'draw_tabs': false}
	
	# Initialize TextEdit with the current tab.
	var initial_tab_data : Dictionary = tab_bar.get_tab_metadata(tab_bar.current_tab)
	
	text_edit.text = initial_tab_data['text']
	text_edit.minimap_draw = initial_tab_data['minimap_draw']
	text_edit.draw_spaces = initial_tab_data['draw_spaces']
	text_edit.draw_tabs = initial_tab_data['draw_tabs']


func _on_TabBar_tab_changed(tab: int) -> void:
	var prev_tab : int = tab_bar.get_previous_tab()
	
	# Save current TextEdit properties as previous tabs data.
	var prev_tab_data : Dictionary = tab_bar.get_tab_metadata(prev_tab)
	
	prev_tab_data['text'] = text_edit.text
	prev_tab_data['minimap_draw'] = text_edit.minimap_draw
	prev_tab_data['draw_spaces'] = text_edit.draw_spaces 
	prev_tab_data['draw_tabs'] = text_edit.draw_tabs
	
	# Load the next tabs data into the TextEdit.
	var next_tab_data : Dictionary = tab_bar.get_tab_metadata(tab)
	
	text_edit.text = next_tab_data['text']
	text_edit.minimap_draw = next_tab_data['minimap_draw']
	text_edit.draw_spaces = next_tab_data['draw_spaces']
	text_edit.draw_tabs = next_tab_data['draw_tabs']
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not necessarily a few lines, but the solution is as simple as having an array that mirrors the tabs in a TabBar / TabContainer, and reading & writing data accordingly in response to the tab changed, repositioned, and closed signals.

### Is there a reason why this should be core and not an add-on in the asset library?

The idea of data being mapped to individual tabs is so fundamental, it makes sense for it be core.

**Comment by YuriSizov** [comment]
This matches what we provide for Tree and ItemList, which are similar in a way. So it makes sense to add this to the TabBar as well. Feel free to open a PR.
