### ISSUE TITLE
Ability to set export variables on Scene Collection tiles in GD4

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#6672]
### Describe the project you are working on

2D Platformer.

### Describe the problem or limitation you are having in your project

I'd like to use Scene Collection tilemaps to place items, but I'd like individual items to be able to have  individual instances of the scenes to have different export variables set.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For instance, using tilemaps to place door scenes, but have the export variables determine which position the player would be placed on when going through the door (the export variable on the door may even be a reference to another door tile in the scene, where the player would teleport to).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I imagine it would be some code in the tilemap/tileset.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

Tight integration with the tilemap.

**Comment by dalexeev** [comment]
Note that you cannot set properties for each individual **cell**, only for the tile **type**. This applies to both Custom Data Layers and Scene Tiles, since the cell (for each layer) is mapped to the tile id (int, Vector2i, int). The cell has no metadata as far as I know.

**Comment by elvisish** [comment]
> Note that you cannot set properties for each individual **cell**, only for the tile **type**. This applies to both Custom Data Layers and Scene Tiles, since the cell (for each layer) is mapped to the tile id (int, Vector2i, int). The cell has no metadata as far as I know.

This is what this proposal is hoping to improve on, if we have the ability to use scenes in tilemaps, they should be as flexible as dragging scenes into the level.

**Comment by elvisish** [comment]
Related: https://github.com/godotengine/godot-proposals/issues/6606

**Comment by Beebster-UK** [comment]
Ah someone else that share my frustration this would be amazing and very powerful feature to add. I'm surprised it's not already present.

You can hear me ranting on about it here! https://discord.com/channels/212250894228652034/1101264450599788574

**Comment by KoBeWi** [comment]
Closing in favor of #7249, which is more detailed.
