### ISSUE TITLE
Add vertical alignment option to RichTextLabel

### ISSUE THREAD

**Issue by muno777** [godotengine/godot-proposals#6674]
### Describe the project you are working on

A menu system for my game, using RichTextLabels instead of regular Button text for more flexibility.

### Describe the problem or limitation you are having in your project

There's currently no way to vertically center or bottom-align the text within a RichTextLabel, which is needed for the style of my menu elements.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an option to apply vertical alignment to the entire RichTextLabel's contents, similar to the vertical alignment property on a regular Label.

This is distinct from [#4458](https://github.com/godotengine/godot-proposals/issues/4458), since that proposal includes dedicated vertical centering _BBCode tags_. This proposal instead applies the centering to the _entire RichTextLabel_ - which I suspect would be a little simpler to implement, while still fulfilling most/all use cases.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The option could be a simple drop-down property:

![image](https://user-images.githubusercontent.com/37985497/230910340-ffdd1a66-e83e-48cb-9969-bbf3e81b1e6c.png)

Top:

![image](https://user-images.githubusercontent.com/37985497/230910556-7e9659af-26aa-41ea-8be2-8fb1a79c3b44.png)

Center:

![image](https://user-images.githubusercontent.com/37985497/230910579-94d09c37-a582-47f6-a5fe-407b6262ec97.png)

Bottom:

![image](https://user-images.githubusercontent.com/37985497/230911394-0ab6be5c-74c3-4f3c-bfce-85c7c2706995.png)

(All of these are just screenshots of a regular Label)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be [worked around](https://godotengine.org/qa/27229/how-to-vertically-align-text-in-a-richtextlabel?show=92485#a92485) by adding a container around the RichTextLabel, but this is less convenient than having it built-in like with a regular Label.

### Is there a reason why this should be core and not an add-on in the asset library?

This is basic functionality for the RichTextLabel.

**Comment by muno777** [comment]
Yeah it would be a little weird to have just the vertical alignment as a property while the horizontal alignment is done thru bbcode haha.

On the other hand, I think vertical alignment is maybe better suited as a textbox-wide property anyway? It's not clear to me what should happen if, for example, only part of a textbox's contents are vertically centered. Horizontal alignment is a lot easier to imagine mix-and-matching since it just happens on a new line. Plus, horizontal alignment is a common bbcode tag, whereas vertical alignment [isn't](https://www.bbcode.org/reference.php) (possibly for this reason?).

I also think it'd be pretty reasonable to add horizontal alignment as a property to go along with the vertical, but of course it isn't as necessary since you can just use bbcode.

**Comment by NuclearPhoenixx** [comment]
Feel like this would be handled better using BBCode like in this proposal: https://github.com/godotengine/godot-proposals/issues/4458

**Comment by animentork** [comment]
Hardly a solution, but I get around this by putting RichTextLabel in a VBoxLayout with alignment set to ALIGNMENT_CENTER and size_flags_vertical to SIZE_FILL | SIZE_EXPAND.
