### ISSUE TITLE
Physics Petition

### ISSUE THREAD

**Issue by Regrad** [godotengine/godot-proposals#6686]
### Describe the project you are working on

My game studio is forced to switch to Unreal Engine as Godot physics don't actually work in 3D. We really don't want to do this, so I'll try as a last resort to asking the developers to put Bullet's physics back into the engine until the engine's own physics are ready. Anyone who thinks the same - please vote like and write a comment.

### Describe the problem or limitation you are having in your project

_

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

_

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

_

### If this enhancement will not be used often, can it be worked around with a few lines of script?

_

### Is there a reason why this should be core and not an add-on in the asset library?

_

**Comment by AThousandShips** [comment]
You need to actually fill in the form, open a discussion otherwise (as this will be turned into most likely)

**Comment by AThousandShips** [comment]
Also this won't happen, plain and simple

**Comment by Regrad** [comment]
https://github.com/godotengine/godot-proposals/discussions/6687
