### ISSUE TITLE
Expose a method to get the next control to be focused based on direction of the input

### ISSUE THREAD

**Issue by pavlexander** [godotengine/godot-proposals#6690]
### Describe the project you are working on

local coop game with up to 4 players

### Describe the problem or limitation you are having in your project

currently there can't be more than 1 controls focused on the same type. This becomes a problem in local coop where multiple players must be able to "navigate" in UI at the same time. For example accessing the shop, selecting rewards etc.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Currently I am tracking the arrow keys and controller navigation keys to track what each player is doing in the menu. I track the current selected item of a particular player and then finding the next selectable item using the two methods:

```csharp
var previousFocus = focusedControl.FindPrevValidFocus();
var nextFocus = focusedControl.FindNextValidFocus();
```

after a bit of testing I have come to conclusion that these 2 methods are practically useless in cases when I need to find a control for focus that is above or below the current line of control

consider a use-case with following controls structure:

```
control 1
control 2 | control 3 | control 4
```

if we are at control 3 then the previous control for focus is control 2 (FindPrevValidFocus) and the next control is 4 (FindNextValidFocus). **However if you click on an UP button (arrow up) then the control that will take focus will be `control 1`!** 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

therefore my proposed enhancement is to have a generic method `FindValidFocus(direction)` that accepts the direction in which the focus control must be found. Be it up, down , left or right.

```csharp
var previousFocus = focusedControl.FindValidFocus(UP);
var nextFocus = focusedControl.FindValidFocus(DOWN);
// ...
```

the UP and DOWN could either be enums or a 2D vector

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no workaround that I know of

### Is there a reason why this should be core and not an add-on in the asset library?

currently it's possible to detect controls on the left and on the right of the current control. But no way to find the controls on the top or the bottom relatively to current control. I think this is a core feature that is missing.

**Note:** engine does this navigation out of the box, so I think that the least we could do is just to expose some existing APIs so that the users could build the navigation system themselves. The next evolution of the solution is to actually support multiple focuses, but I do not want to bring this topic up in this discussion as it requires more work and more analysis than just exposing a couple of functions.

**Comment by AThousandShips** [comment]
Is `get_focus_neighbor` not sufficient?

**Comment by AThousandShips** [comment]
There's also work on enabling multiple focus #62421

See also:  #4295

**Comment by KoBeWi** [comment]
Controls have `focus_neighbor_bottom/left/right/top` properties. There's also this method
```C++
Control *_get_focus_neighbor(Side p_side, int p_count = 0);
```
but it's not exposed. I guess that would be what you want.
(although https://github.com/godotengine/godot/pull/62421 also solves your problem)

**Comment by AThousandShips** [comment]
> this method returns whatever is set into properties

it uses the same feature to detect in the directions, it is whats used when pressing direction keys in controls

**Comment by pavlexander** [comment]
> > this method returns whatever is set into properties
> 
> it uses the same feature to detect in the directions, it is whats used when pressing direction keys in controls

is it? I am sorry then :) Let me test a couple of things and get back with response :)

**Comment by AThousandShips** [comment]
It is what the engine uses to navigate:
https://github.com/godotengine/godot/blob/68b8156fe3075e0e45b070d26fce2a0baae6f293/scene/main/viewport.cpp#L2137-L2151

And does visual detection if it can't find a neighbor:
https://github.com/godotengine/godot/blob/68b8156fe3075e0e45b070d26fce2a0baae6f293/scene/gui/control.cpp#L2147-L2226

**Comment by pavlexander** [comment]
> It is what the engine uses to navigate: https://github.com/godotengine/godot/blob/68b8156fe3075e0e45b070d26fce2a0baae6f293/scene/main/viewport.cpp#L2137-L2151
> 
> And does visual detection if it can't find a neighbor: https://github.com/godotengine/godot/blob/68b8156fe3075e0e45b070d26fce2a0baae6f293/scene/gui/control.cpp#L2147-L2226

Yes you are correct! The method `_get_focus_neighbor` is exactly what I want to be exposed since it searches for a node to focus

I have also tested the 4 properties above and I can confirm that none of them return a value unless a value in question is set.

I applied following method to all controls that could take focus:

```charp
    private void OnFocusEntered(Control focusedControl)
    {
        GD.Print("Focused control name: " + focusedControl.Name);

        GD.Print("FindPrevValidFocus: " + focusedControl?.FindPrevValidFocus());
        GD.Print("FindNextValidFocus: " + focusedControl?.FindNextValidFocus());
        GD.Print("FocusNext: " + focusedControl?.FocusNext);
        GD.Print("FocusPrevious: " + focusedControl?.FocusPrevious);
        GD.Print("FocusNeighborTop: " + focusedControl?.FocusNeighborTop);
        GD.Print("FocusNeighborLeft: " + focusedControl?.FocusNeighborLeft);
        GD.Print("FocusNeighborRight: " + focusedControl?.FocusNeighborRight);
        GD.Print("FocusNeighborBottom: " + focusedControl?.FocusNeighborBottom);
    }
```

The output is:

```
FindPrevValidFocus: <Button#39762003320>
FindNextValidFocus: <PanelContainer#40433091964>
FocusNext: 
FocusPrevious: 
FocusNeighborTop: 
FocusNeighborLeft: 
FocusNeighborRight: 
FocusNeighborBottom:
```

Which is an expected behavior.

So yes, in conclusion `_get_focus_neighbor` would be something I would like to see exposed. Do you know if there is someplace I should submit the request to in order for the change to be considered for implementation or is it automatically reviewed upon backlog grooming of some sort?

**Comment by AThousandShips** [comment]
I can set up a test for this, will have to see if there's any possible issues with exposing it, but should be good
