### ISSUE TITLE
Add AFR(see details) support to greatly reduce power usage and increase performance.

### ISSUE THREAD

**Issue by EllesarDragon** [godotengine/godot-proposals#6693]
### Describe the project you are working on

Making games and software of roughly any type(2d, 3d, platformer, fps, story, openworld, etc.) much more energy efficient(saving power), without trading in performance experience.  And while also greatly increasing performance experience due to much lower and more stable latency.

It started with the steamdeck which is great, but often people have to make tradeoffs, either choose for long battery life by limiting FPS increasing latency, or choose for good responsiveness. I noticed people faced that problem so invented a solution(came up with and designed a solution) for it: AFR
which happens to also be usefull for almost any game and almost all hardware as long as it is capable enough of actually running a/the game at a atleast decent fps. due to energy savings, lower thermals, and much lower latency due to increased efficiency.

### Describe the problem or limitation you are having in your project

Power usage is way to high, performance is also way to low due to a very inefficient/low ITF(similar to IPC but in software rendering), this causes large coputational and power stress on the hardware, and lowers effective performance greatly. Implementing AFR can increase effecive performance(aka. Lower latency by) more than 2 times, while saving processing power and electric power, meaning that you get lower latency even when playing at a much lower FPS, while saving energy.  
note to keep it short more info is below in the “More dedicated/detailed Text/description”
note the bellow description is very simplified and doesn’t bring out the advantages as clearly, read the dedicated description for a better understanding.

AFR-Adaptive Frame Rendering, is a smarter Frame rendering manager which adapts itself to the important events. Where modern methods rely on brute force and dumb luck, AFR takes a more delicate approach of just doing whatever is needed whenever it is needed and actually when it is needed. It needs to render way less frames, while still reducing the latency the player experiences. So less frames are needed to be rendered, but still it performs as if it renders at a much higher fps than the original.
Above a certain fps like 24fps or 30fps, people only notice a higher fps due to a decrease in latency in general, that problem is fixed by AFR since AFR actually reduces latency by rendering les frames so it can render them when they are actually needed.

![LatencyFrameVisualisation](https://user-images.githubusercontent.com/130708460/231903293-d1b8b3bb-9012-45e4-a395-1b9b2ae5a1b3.png)
image is A simplified graph showing latency issues in normal FRM and why AFR keeps working well, note that I mispelled IAFR as IRFR, since I spelled adaptive as responsive because they basically mean the same in that context, the AFR in this drawing also uses no baseframepostponing, using that would actually make it much more efficient.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

AFR-Adaptive Frame Rendering, is a smarter Frame rendering manager which adapts itself to the important events. Where modern methods rely on brute force and dumb luck, AFR takes a more delicate approach of just doing whatever is needed whenever it is needed and actually when it is needed. It needs to render way less frames, while still reducing the latency the player experiences. 
AFR is a new Frame rendering manager, which is originally meant to save power without sacrificing experience performance, as a side effect it also greatly improves performance by greatly reducing Latency at important places like input.
Combining these 2 factors results in a very big overall increase in efficiency.

### **AFR Super Short** 
AFR is a smarter Frame Rendering manager, it works by rendering only a base FPS so everything looks smooth like a movie, but it also has a way to make it adaptive, in the case of AFR it makes it adaptive by rendering extra frames or shifting the moments at which frames are rendered around, but mostly just by rendering extra frames.
One way this can be used in almost all games is by using user Input to trigger rendering those extra frames, when significant use input happens it will trigger and directly render a new frame, the gpu is still as fast as before but the frame on average will start much faster after getting input greatly reducing input latency, even compared to when you would run the game at the highest fps your hardware can handle latency is reduced by 33,3% on average which is a similar decrease as which you would get from increasing the fps with 50%.
it also still needs to render way less frames, this results in large power savings, and heat reduction.

Input however isn’t the only thing AFR can adapt to, it can also adapt to speciffic internet packages or AI updates , for example in a online FPS you can make it so that AFR also directly renders a new frame when another player within range, vision, etc. does a certain thing that migth be important for you to notice, while simple IAFR doesn’t check what they are done, normal AFR and EAFR can be used like that to opimize online games with many players and such, it allows you to let it trigger when things that might actually be important to get to the player as fast as possible happen.

**Some basics for AFR, recommended as required but you can choose not to use all of them.**
-AFR_BaseFps: A user settable Base framerate that automatically keeps going, that way it keeps looking smooth like a movie.
-AFR_Queue: A bool for a queue, if a frame is already rendering and it can’t directly render the new extra frame then  this bool is/can be set to true, so that directly after finishing what was happening it will render a new frame. You might also sometimes want to use this as a parameter. It only needs to store one  or zero,
-AFR_BaseFramePostPoning: when a extra frame is rendered the baseframe after it can and optimally should be postponed, basically the delay until the next base frame is reset, so it takes longer before the extra frame renders, increasing power savings, and if Priority isn’t used also increasing performance ITF
-AFR_Priority: a int to allow to give frames priority if another frame is already rendering these can be used to see if a new extra frame should directly be rendered disposing the frame that is currently rendering.
-AFR_MaxEFPS: a user settable max EFPS, this allows especially low end systems to save some extra power if somewhere  it would get tons of input, this acts like a real fps limit but then for efps, it could also be used with real fps instead of efps.
-AFR_Enabled: general bool that when set to true lets AFR work (if enabled and/or implemented), might sound useless at first, but when set to false it easily allows people to disable it in a game without needing to add things like if statements or other logic to disable it, this allows to easily be able to disable it.

### **Latency improvements:**
![LatencyFrameVisualisation](https://user-images.githubusercontent.com/130708460/231904200-3b77479e-4883-4473-9954-13f56694eef6.png)
in this image you can see 2 examples of how even a very poor implementation of AFR can greatly reduce Input To Frame Latency. This example in the immage uses a very bad/poor AFR implementation where normal BaseFramePostponing isn’t used, and which actually only uses a functionality to render extra frames when input comes, and combines that with normal frame rate limiting. In reality a better implementation is recommended but by using such a poor implementation here it shows how even those already are quite effective. It also makes it more easy to compare them with eachother.
The first input event shows the average difference in latency, the right one shows a best case schenario for nomal Frame rendering management. I didn’t add a close to worst case for normal frame render management in this drawing, but the general idea should be clear AFR is much more stable in latency on average and is also has much less latency.
The drawing shows InputResponsiveFrameRendering, but that was a misspelling of InputAdaptiveFrameRendering which is a implementation of AFR(adaptive frame rendering).

In case it still isn’t clear, when watching a movie latency isn’t important, in games it is because there are things like user input or events, internet packages, etc. which the user needs to be able to rapidly respond to, it are the speciffic parts of a game that would be significant in the way that you would notice a higher latency or that it might cause problems. The most easy example is input.
But since a normal FRM doesn’t care about when it renders frames, it just renders them either to match the fps limit, or as much as possible, this causes a huge increase in latency, since when a frame is rendering it no longer takes the input that you give then into account. So when you give input it is only first shown in the next frame that will start to render after you gave the input. Here it is important to focus on the part about “start to render”, that means that if a frame is already rendering that will not show it yet.
Due to this a normal FRM takes random numbers in between 1 and 2 frames before it is show on the frame, so while playing a game it should average at around 1,5 frame times. This results in a ITF of around 0,66.
AFR manages to almost always take around 1 frame to show the input on the frame, this results in a ITC close to 1.
Allowing AFR to only have half the latency in at the peak moments, and a normal FRM having 1,5 times as much latency on average.

FRM is great because it can reach that ITF very simplistic, easy, and without much compute power or special hardware. Getting a ITF above 1 would require some kind of AI that renders focus zones directly over the current frame allowing it to be faster than rendering a extra frame or something like that. AFR actually has this included but optional for the future in highly competitive games.
(AFR_Focus) for example
 
### Enegy savings improvements
less frames are rendered, because frames are only rendered when they are needed.
In a game the only frames you really need is a base framerate to make it look smooth like a movie, this is somewhere in between 16 to 32 fps typically, but 24fps and 30fps would be more standard numbers.
Next to that there are certain things in a game that require low latency, things like user input, and very important other events. normally a high fps is used for this, but in AFR these are dealt with by making the frame rendering adaptive, so a typical implementation would be by rendering a extra frame directly at one of those things or moments that require very low latency.
This is around all the important stuff about why it can save so much energy without making a trade-off in performance/latency.
When doing it smart and adaptive you just need to do way less work, which results in saving energy.

### summary
AFR is like limiting FPS and helps you save lots of power, but it doesn’t have the drawback of getting higher input latency and it can actually reduce latency greatly so increasing EffectiveFpsExperience by 50%, it also could increase EFPS if desired using the lower temps and more free compute and TDP headroom to render frames at a higher clock or compute things in the background, increasing EFE even more.

### Some basics for AFR, recommended as required but you can choose not to use all of them.
-AFR_BaseFps: A user settable Base framerate that automatically keeps going, that way it keeps looking smooth like a movie.
-AFR_Queue: A bool for a queue, if a frame is already rendering and it can’t directly render the new extra frame then  this bool is/can be set to true, so that directly after finishing what was happening it will render a new frame. You might also sometimes want to use this as a parameter. It only needs to store one  or zero,
-AFR_BaseFramePostPoning: when a extra frame is rendered the baseframe after it can and optimally should be postponed, basically the delay until the next base frame is reset, so it takes longer before the extra frame renders, increasing power savings, and if Priority isn’t used also increasing performance ITF
-AFR_Priority: a int to allow to give frames priority if another frame is already rendering these can be used to see if a new extra frame should directly be rendered disposing the frame that is currently rendering.
-AFR_MaxEFPS: a user settable max EFPS, this allows especially low end systems to save some extra power if somewhere  it would get tons of input, this acts like a real fps limit but then for efps, it could also be used with real fps instead of efps.
-AFR_Enabled: general bool that when set to true lets AFR work (if enabled and/or implemented), might sound useless at first, but when set to false it easily allows people to disable it in a game without needing to add things like if statements or other logic to disable it, this allows to easily be able to disable it.

### **Some possible Implementations:**
**1:**
AFR can be implemented as automatic IAFR, this is enough for most games and so it could be like a setting which you can just enable or disable from code or the settings menu, IAFR just looks at user input, just when it gets it before the game logic even starts to process it, it is recommended however to add a option to easily link different types of events, if not then functions like the EAFR implementation below could also be used in combination with this, while they also could be used as standalone without the automatic AFR.
What IAFR needs at least is(what is recommended to atleast have):

-AFR_BaseFps: A user settable Base framerate that automatically keeps going, that way it keeps looking smooth like a movie.
-AFR_Queue: A bool for a queue, if a frame is already rendering and it can’t directly render the new extra frame then  this bool is/can be set to true, so that directly after finishing what was happening it will render a new frame. You might also sometimes want to use this as a parameter. It only needs to store one  or zero,
-AFR_BaseFramePostPoning: when a extra frame is rendered the baseframe after it can and optimally should be postponed, basically the delay until the next base frame is reset, so it takes longer before the extra frame renders, increasing power savings, and if Priority isn’t used also increasing performance ITF
-AFR_MaxEFPS: a user settable max EFPS, this allows especially low end systems to save some extra power if somewhere  it would get tons of input, this acts like a real fps limit but then for efps, it could also be used with real fps instead of efps.

-Input directly triggering IAFR, even if the game logic and loop doesn’t yet use it.
**2:**
AFR could also be implemented like EAFR, in a engine like godot both could be used together and they should easily work together, IAFR might just work by automatically using the EAFR functions.
AFR.SetBaseFPS(int fps)
AFR.SetMaxEfps(int efps)
AFR.RenderExtraFrame()
AFR.RenderExtraFrame(int priority, bool QueueOnFail=true)#render frame with 2 basic parameters would check for priority and also allows to set it to not turn queue to true on a fail by setting  QueueOnFail to false.
AFR.RenderExtraFrameNow() ## always rendes with priority without checks for priorty
AFR.SetQueue(bool queue)

AFR.Queue : bool = false
AFR.MaxEFPS: int = -1
AFR.BaseFPS: int = 30
AFR.CurrentPriority: int = -1 ## no frame rendering has priority of -1 or 0 / done rendering

##AFR.BaseFramePostPoning should be enabled by default. Queing as well, the bool for que is just for storing if It needs to render a extra frame

Setting:IAFR.enable()

_to work well this also requires input to be able to directly be processed, instead of it being synced to the gameloop, physics loop, or rendering loop.  If the current on input methods don’t directly trigger when they receive input it might be usefull to make them, or to have a dedicated realtime input method or event handler or such, so that you can directly run code whenever input is received instead of having to wait for something else(perhaps this already works like that right now, just mention it since it is important and perhaps someone in the past thought, let’s link it to something since with the old fps based method that poses little problem)._
note this is just a example, there are many more ways to implement it.

AFR:Adaptive Frame Rate.
Only renders frames when needed/desired and renders them much closer to those important moments. It just renders it when something important triggers it, such as significant user input, or some events that the programmer wanted it to respond to, to prevent the movie/film effect stopping if there is no input or events or such to adapt to there also is a base framerate which tells it that it atleast needs to render a frame after every certain period of there not having been rendered a frame, so that it keep looking smooth like a movie even when you don’t give input or when there are no speciffic other events that trigger it.

### Definitions:
ITF: Input To Frame, if you divide 1 by ITF you get how many frames it on average takes before new user input is shown, the current default method has a ITF of around 0,66 while AFR comple close to a ITF of 1.
FRM: Frame Rendering Management, refers to how frame rendering is managed. AFR is a new typs of FRM that replaces the old/current FRM.
EFE: Stands for Effective FPS Experience, it can be seen like FPS but more accurate, especially for high performance or competitive gaming and such, EFE instead of looking at fixed FPS looks at the average Latency between when the user gives input and when the gpu is done rendering the frame that shows it.
 EFE is calculated by taking the EFPS and multiplying that with the ITF.
N1,5-EFE: or NTO-EFE: or in this case N-EFE: this is similar to EFE, but it is normalized towards the current normal/default FRM. This makes it easy to compare with FPS how people currently are used to it. since if you play a game using the old FRM then if you reach  100fps you actually only reach a EFE of 66,6fps. Due to the lower ITF, so since the actual latency between user input to the frame rendering being done is around equal to FRM with a ITF of 1 which would render at 66fps. Since people are used to measuring in the old FRM and so see 100 fps in the old FRM as 100fps instead of as 66 FPS EFE I defined a custom EFE normalized to the old FRM so everything is amplified by 1,5. so 100fps in the old FRM wich has a ITF of 0,66 is 100fps NTO-efe, instead of showing you the actual effective Performance/FPS experience you would get this shows you how compared to how much fps when using the old FRM this would be equal in experience.

If that sounds to complex N1,5-EFE, NTO-EFE and in this case also N-efe all can just be seen as fps for easy comparison if you aren’t to far in the future(so if games do not yet support AFR or similar technology which improves ITF)
 normalized EFE is calculated by taking EFE and multiplying it with the factor to normalize it which in this case is 1,5.
EFPS: Effective FPS, this is like EFE and any Normalized-EFE, however it doesn’t take experience into account, so it is just like FPS but instead of counting the frames it measures how long it takes to render one frame and uses that to calculate how many frames it could generate per second. So if rendering one frame takes 10ms that would give a EFPS of 100. 

AFR: is a smart frame rendering manager which instead of setting the fps to a certain rate or to uncapped will limit the base fps but will also still render new frames whenever needed exactly when needed, Due to this you need to render a lot less frames and actually get much lower latency and a more smooth and fluent experience than when playing at max fps.
It helps you save a lot of power and increases effective performance experience greatly. The one requirement for making AFR work well in your game is that your hardware is capable enough to play it beyond the FPS which you are comfortable of using as base FPS. While mostly effective if your hardware can handle much higher fps in the software or game, it also already works if you could just barely reach a higher fps than the desired base fps if you let AFR frames postpone base frames. Base frames are just there to keep things looking smooth, so there is a fixed delay between every frame like with normal frame capping, when AFR renders a new extra frame, that delay could be reset saving extra power and increasing performance more on low capable hardware. It is recommended to add that as a setting or as default when used as a setting you could name it AFR-BaseFramePostponing for example.
Frame queueing is also needed, otherwise problems might happen when input comes while rendering a frame, so one frame needs to be able to queued at a time, this can be a bool. If new input comes but it can’t render a new frame yet because it is busy rendering or such and there is no priority, then the bool is set to true. If the bool is true then as rapidly as possible(for example directly after finishing the previous frame) it will render a new frame the bool is also directly reset to false when it starts rendering a frame, so it can again be set to true if it receives input while rendering. If this is not added and there comes input while rendering a frame and it might otherwise wait and not render until the next base frame or input, that is why this 1 bool que is important to implement.

### general/Extra functionality, parameters and such:

-Automatic Rendering at base framerate and setting base the framerate(basic functionality)
-Base Frame Postponing, push back the next base frame after a extra frame as if it was a base frame, since  the base frame isn’t needed as soon anymore then, it is recommended to do this by default since there should be no real drawback and lot of gains.
-Queue, a bool to queue one frame if something like input might happen while rendering a frame or when due to something else it can’t yet render a new frame then this bool will be set to true so that directly after it, it will render another extra frame. This should be used and enabled by default, only in very rare cases might you not want this on.
-User settable mac EFPS(for extra energy saving capability and frame rate limiting for low end hardware)
-Frame queuing(queue up to one frame to directly render after the current frame is done. If an extra frame can’t be rendered directly the bool will be set to true so it directly renders a new frame when it can. When it starts rendering a new frame the queue bool is reset to false.)
-A Method for calling it manually as well as to set things manually from code(call to render a new frame).
-A way to use more advanced settings from the settings directly
-A mostly automated implementation which can be enabled and reacts to all user input.
-Importance OFFSET for analog inputs(this can be used for tracking systems and things like mouse input since those can rapidly change it might be nice to have a parameter that you can set to for example set I to wait 1ms or another amount after receiving the first change in that it before triggering, or to wait for certain amounts of changes or such, possibly even with AI which uses the mouse speed and direction and combines that with the frame render time to predict where the mouse would be when the frame is done rendering when there are big fast mouse or other analog movements such as VR tracking, such AI should probably only be enabled proportionally and at higher speeds and bigger movements mostly, so not on precision such as aiming, this might also be great for VR anyway even when not using AFR since it can reduce nausia by making the movements sync more to your actual movements.)
-event linking for automated IAFR

Some extra things, typically less important than those other ones, but some people might want them eventually at some point:
-Eco mode, No mode(neutral/whatever it does), Boost mode(to try and control things for either boosting more or using less power or using the default, these thing might heavily depend on hardware and drivers, GPU makers could add such things in their drivers.)
-AFR_Resolution(allow extra frames to be rendered at another resolution, also give the possibility to automatically enable the queue function to render a new frame in normal resolution directly after it, this is mostly useful specifically for highly competitive games which need very low latency)
-AFR_Focus(similar reasons and general extra functions as AFR_Resolution, but this one tries to focus on one or a few points and starts rendering as much around those points as efficiently possible, it also will try to directly write those to the display even if the rest isn’t finished yet so if the screen refreshes it will be more likely to show those things, again only for highly competitive games to get minimum latency)
-AFR_Priority(this is a property/parameter which is very useful with almost all these extra functions/properties/parameters, you might not need it with a normal implementation, but this allows you to set priority. Base frames will have a default Priority, higher priorities will start rendering even if another frame of lower priority was already rendering and that lower priority frame will then just be discarded. Frame priority again reduces latency, you could for example overwrite baseframes, or if you use AFR_Resolution and let it render a full resolution frame after it then you could overwrite that if you suddenly get new input).
-AFR_Analog_Predictive_Priority(similar to AFR_Priority, but this one actually also tries to look at things like if it could finish the current or that other frame before the screen updates especially if the screen refreshrate is low, it also estimates how far rendered the frame should be and based on estimated progress(render time per frame and current render time) it requires a larger difference in priority to be overwritten, and can even be set that it won’t be overwritten at all if it reaches a specific point. Etc. it uses things like those to make priority a little more efficient and friendly, and possibly effective).
-BVAE(Body Virtual AI Extension), is actually another technology I came with, but simplified it fits well as a part of AFR, so right now I treat it as included part of AFR for a more complex/advanced implementation, I talk about this before in the dedicated VR section BVAE can be used under the same license as AFR, unless stated otherwise in case of a custom license. BVAE are usefull for constantly changing analog inputs like VR trackers, and reduces nausea in vr. It predicts where your tracking points or other thigns would be at the moment when the frame is done rendering, or is expected to be shown on screen(for example also including screen latency and the moments at which the screen refreshes). I can explain this technology more if requested, but it should be simple enough to understand the basic principles to make a working implementation, if you need help for example with a more optimized one you can ask me to help you understand it more in how to best use it, this is just a request so I am not obligated to do anything, but asking can be done.
-ETC(there are many more possible things but the list has to end somewhere)
-I forgot an important one here, and some others as well.
-EFPS, show how many frames it could render per second based on how long frames take to render instead of how many frames actually rendered, this helps with the placebo effect, since many gamers largely judge with that.
-EFE(or early on N-EFE), this shows more accurate statistic at places where framerates are high enough and where latency is important, since it shows EFPS*ITF. ITF can be precalculated but optimally would also be tested atleast regularly, even though that might not always be needed it is nice to get the most accurate results.

###  Some Implementation examples(theoretical):
while I discussed this already largely before I will state some basics again.
To Implement a minimum version of AFR, you need to be able to set a Base FPS, and to have a way to make it “adaptive” this can be in any way including ways I didn’t state.
One of the most likely ways this could be used in almost all games is by using user input or significant user input.
Another semi-common use might be to trigger at certain input from other player, for example over a network.
Some easy methods for implementation are
** IAFR:** which is like a plug and play or patch and play or enable a setting way to implement and use AFR, it is meant to allow people to support it with minimum effort, or even to have it being supported or enabled by default. IAFR just automatically does it for you, you have a setting for the base fps, and one to enable or disable it and that is basically all of the basic requirement of this one, even though you might not even need those settings they just are really nice to atleast have those. IAFR triggers on any user input.
It is also very recommended to add a MaxAFR setting which can act like a maximum framerate limiter in case you constantly get spammed with input, this just allows it to save some extra power if that is your main goal.
A option to enable it to trigger on for example network input, or a trigger/event which you can use to custom assign things it should trigger to
And some of the extra functionalities described above or below can be useful. 

**EAFR:** this is an implementation of AFR but more Free and modular compared to IADR, EAFR could also be seen as basic or normal AFR in some cases, even though AFR could be implemented in other ways as well. EAFR is just something like function or method, or multiple different ones for different uses or something similar. which you can call manually in code to render a extra frame.
 
EAFR is something which just has the important basic functionalities and gives the users/game/software developers easy and safe methods to use AFR and to control/customize it with quite high precision. Instead of being mostly automatic and just responding to all user input this gives the developers much more freedom in what they want to do with it and what they want it to respond to. Imagine an online FPS game. Triggering on user input from other players is likely desired, but triggering on all players would be stupid, instead a game developer might decide to only cause it to render extra frames when important input from themselves or from other players within range and/or where either of them could target the other realistically(for example in range, no obstacles and in vision) then that could be done using EAFR(EAFR and IAFR could both also be implemented just under the name AFR).
EAFR gives some simple functions/methods like (E)AfrRenderExtraFrame(), or (E)AfrSetBaseFrameRate(), or perhaps also some different ones like a setting/setup function or such, it could even be implemented like an object if needed in case one game uses multiple cameras which render at the same time for example if you want to make it more efficient by treating them all as separate.
In general however you could use many different parameters for methods and/or many different extra methods or fewer depending on what you want and need it to do and be like.

It is nice to add many extra parameters here.
Some other general useful things for when using AFR is to by default display EFPS, or even beter EFE instead of the actual FPS, this helps people accept the effects due to the placebo effect, if you show them It only rendered 40 frames in a certain second the placebo effect will make them think they had a bad experience even if they actually had a good experience, but showing the EFPS which could be around 240fps they will accept the experience a lot better showing EFE instead so 360 efe will help even more, especially early on when people are still used to the old FPS which only reaches a ITF of 0,66 instead of a ITF of 1.

unlike IAFR, EAFR is not fully automatic and instead is manual.

### Using AFR in VR(or other complex/bad schenario's for AFR)
VR is the one place right now whee AFR would be harder to use, however there are ways to make it work.
The reason is because the input is often analog motiontracking, which means contant changes in input.
On a high end enough system it should work anyway because the input systems often also work at a specific frequency, if you can reach a fps over that frequency AFR will still work by default even when your controllers keep moving, even though at that point you might want to just limit fps to the input systems speed.

VR and similar problem facing schenario’s actually are why I came with the parametes/extra functions one could use if desired. That where about only looking for “significant input changes” or allowing one to set a certain time delay before certain inputs trigger it, or just when either of the 2 triggers. Both have some drawbacks and are mostly for speciffic use, the waiting is mostly for slow input where input is send chained but doesn’t come in like instantly, the ofset for significant changes is mostly to not make things like drift or noice in the input trigger the AFR extra frames.

However those still are bad. And I have a good solution for VR, it will however sound way more complicated than it is, and that is using a BodyVirtualAiExtension(BVAE) also something I designed, even though first it was mostly to enhance people, but in AFR a more simple version of this can be used. There is just some basic AI or algorythms, or just some simple calculations which take the movements which come from the input system and use those to determing things like acceleration, direction, direction changes, and possibly even patterns in a more complex version. These things are then used to predict where the controller would be when the next frame is rendered, and possibly beyond that. It can be seen either as some predictive calculations in a simple case, or as a virtual AI version of yourself which syncs itself to you to make you and the AI basically one creature where it causes not only input which is more easy for the game to use, to greatly reduce nausea in VR and for AFR to work well, but can also increase player precision by for example aiming exactly where the player intended or moving to exactly where the player intended. It can remove the aspect of having to think about input and instead is just doing what you inteded to do in a good implementation. this can help to greatly reduce nausea in VR even in lower performance mashines
using this method where essentially you would also break up movements into the general movements/changes, AFR would suddenly work very well in VR games, since then it only needs to trigger at moments where the BVAE(AI) was wrong or has come with a abrupt change. And since humans are rather simple beings, which only tend to actually change movements in strange harder to predict ways either due to external forces, or just only up to around 6 to 12 times per second based on adrealine levels, this would make AFR very effective in VR when combined with something like a BodyVirtualAiExtension.

BodyVirtualAIExtension is just like a implant/extension for kind of extending your body and mind/brain by kind of becoming one with a AI when using It, it can however be fully virtual meaning it doesn’t require something like a actual implant.

original: https://odysee.com/@DaanVanLoon:c/AFR:b 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, the IAFR approach can be enabled or disabled using a setting or parameter, for General AFR or 
EAFR and many of the more custom less automatic AFR implementations(IAFR is mostly automatic) have to be used by the coder of the game, it has to be called to start, IAFR is automatic but can and probably should be a setting, IAFR is just a very simple AFR implementation that automatically implements AFR well enough for most games. But the other more custom implementation require the coder to speciffically call them.

EAFR it could also easily be disabled from code by adding a bool like EnableAFR, which will also disable IAFR. A bool like EnableAFR is just there so if people used AFR methods in their code that
they don’t need to add a statement to check if afr is enabled or not, so they can easily add a setting in the game for people to disable all AFR.

### Is there a reason why this should be core and not an add-on in the asset library?

It should be core because there is almost no reason to not use it once it is there and people understand what it does, it also super small and “simple”, meaning it won’t bloat the core or file.  It is much more efficient in core and people can more easily use it, essentially it would be something you would want on in almost any game even if you don’t think about it, adding it in a module might make it much more difficult and in the result bloat things.
Essentially it is like why the setting for limiting or targeting a fps should be added in core, or that the core should be able to have something like cameras and automatically render, it is just basic functionality, that almost any game would and should use, for example how many games made in godot don’t render something(so how many games made in godot run purely in a os native terminal or such, and don’t use any of godot’s rendering functionalities, there might be one or some, but most will render something.

Also don’t forget, it is small, easy to enable or disable, even to disable it if you manually told in code to use it, and it allows insane energy savings, as well as great performance improvements.

One mayor reason someone might not want to use it, is because it is new and they don’t know what it is and does and why they should enable it. Or if someone makes a game where IAFR(automated one setting afr) doesn’t work optimally well and where they don’t yet get why they should use EAFR or normal AFR which tend to work well in basically any game, even things like fps-esport-MMO’s(as in all those in one since that is where IAFR tends to be at it’s weakest, EAFR and normal AFR still work very well there however) and such.

### **Why should I want AFR?**
-AFR can greatly reduce power usage without making sacrifices in responsiveness, quality and latency.
-AFR can greatly reduce latency up to 2 times but 1,5 times on average when the cpu and gpu run at the same frequencies while rendering, AFR has a 1,5 times better InputToFrame(ITF).
-AFR Powersavings result in Lower temperatures, which result in less wear on your hardware, less need for cooling which also can reduce sound, and it also allows for more temperature and TDP headroom preventing thermal or TDP throtling and allowing the gpu to keep working at max boost speed whenever the gpu is needed instead of at the lower game clock, this on average is around 10% to 20%, but can be more TDP or thermally chalanged chips such as mobile or overclocked chips, ofcource you could lock your gpu to gameclocks to save even more power. Less wear also can reduce waste.
-This increase in boost clock and in ITF actually can give a insane decrease in latency, which in the case of the stock intel arc a770 should be around a 2,4 times reduction in input latency on the frame rendering side. This would mean that if there are no other bottlenecks such as the screen, ram, etc. you would reach a experience comparable to 480fps on a a770 if you could normally run that game at 200fps on that gpu when running at uncapped max performance. Since after the first low framecount responsible for making it seem smooth, anyting beyond that is just to reduce latency. A rtx 3060 with AFR on can actually give you a better experience than a rtx 3080 with AFR off in many games. This can make gpu’s longer usable in competitive games which can again reduce waste.
-AFR is Free and Free, you can implement, use and modify it freely. You aren’t required to fully implement it, or to implement it in a speciffic way.
-AFR is simple, while AFR can be made complex, it can be made and used and implemented very easily and simple, AFR can be extended/supported by more complex things but the base principles are enough for many or most use case, so it can be implemented very easily. 
-It helps reduce strain on nature. Save the nature, Save the world.
-We need advancement and to make things more efficient, especially since the last years most people just relied on using more and more brute force, and didn’t care about efficiency, power usage, or making it work on older hardware, or work better on current hardware, they just assumed that if it works just about fine on new hardware that that was good enough.
-FREEEEDDDOOOOMMMMMMMMM!!!!!!!(Freedom)
-Changes bring forth more and new changes. A lack of changes will only reduce the chance of other changes. When there is a right balance things will advance fast and well, right now it is not really advancing and way to slow, including AFR just shows and stimulates more change happening.
-then perhaps some day you or I or many more can use it(prefferably someday is soon like yesteday or before yesterday).
-other reasons.

_(like I said, change brings change, this is a nice example of it, even though I just now realized it since the “change brings change” from before came from my feeling, but AFR itself is a nice example to show it. computers and laptops existed, and faced the same problems. But it wasn’t yet the change that caused the change that made me come with this change. It was the steamdeck which had people making tradeofs between power usage and responsiveness which was the actual change that caused me to invent/make-up/design(in a few seconds) AFR, if the steamdeck did not launch AFR might not have existed yet, and perhaps might even never exist. So this is that extra reason to use AFR since it might cause other changes as well, advancement brings advancement, change brings change, and a lack of it brings darkness and a lack of things like advancement and change.)
I don’t even own a steamdeck currently. I just noticed people with a steamdeck had those problems. And I noticed it because I like the device and the changes it can bring, just already have a laptop that still works well enough.._

**Comment by Calinou** [comment]
I don't think this proposal is technically feasible to implement. It also lacks community support (no reactions or comments in over a month), so I'll close this.

Frame generation or [reprojection-based](https://github.com/godotengine/godot-proposals/discussions/5892) techniques have shown to be viable though – feel free to pursue those still :slightly_smiling_face:
