### ISSUE TITLE
TileSet editor:  Be able to delete individual tile IDs

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot-proposals#67]
**Describe the project you are working on:**
Game with many tiles in a set sharing texture resources

**Describe how this feature / enhancement will help your project:**
Occasionally, I make autotiles specifically to test the autotile functionality in Godot, or a variation of an existing tile to test minor changes, such as different z-order, collision or occlusion masks.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/1023003/64912067-96615600-d6ef-11e9-9aec-74f1b9e1cba9.png)

**Describe implementation detail for your proposal (in code), if possible:**
Two possible implementations:
1.  Reorder all tile IDs which exist after the deleted ID.  Show warning such as this before deleting:
![image](https://user-images.githubusercontent.com/1023003/64912154-d83ecc00-d6f0-11e9-8570-11958ffec747.png)
2.  Simply remove this ID and re-use the ID when creating a new tile, no re-ordering.  May possibly require minor changes to the underlying implementation of TileSet and TileMap.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes.  `TileSet.remove_tile(id)` exists.  It's not clear if the underlying implementation re-orders IDs or just makes the existing one invalid.  It's also unclear if the ID will be "recycled" by the built-in TileSet editor.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a simple feature with the existing functionality already (theoretically) exposed to the runtime.  A UI element for it in the editor simply doesn't exist yet, as far as I can tell.

**Comment by creikey** [comment]
Working on this now

**Comment by creikey** [comment]
I'm not sure I even understand how this editor is supposed to work, it's not clear to me which tile is selected...

**Comment by creikey** [comment]
Is there a way to deselect the currently selected tile?

**Comment by creikey** [comment]
It seems like there always has to be something selected.

**Comment by creikey** [comment]
Correct me if I'm wrong, but I think that this delete button does the exact same thing?

![image](https://user-images.githubusercontent.com/28424206/73037107-a78b4380-3e02-11ea-8cb9-60ebe707b925.png)

**Comment by nobuyukinyuu** [comment]
That button deletes the region rect from the currently selected tile.

**Comment by creikey** [comment]
Why would a tile ever not have a region rect? Isn't that the whole point of a tile?

**Comment by creikey** [comment]
When I clicked that delete button it removed the tile from the list.

**Comment by nobuyukinyuu** [comment]
You are indeed correct.  It leaves a "hole" in the tileset numbering (which doesn't get re-populated), but that's probably not an issue.  I'll close this issue for now.

**Comment by creikey** [comment]
I'd personally prefer it to keep the order as I use a script to replace every tile with a custom node to create a powerful "level editor" that can use tiles of any node kind
