### ISSUE TITLE
Fix "argument"/"parameter" confusion

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot-proposals#670]
**Describe the project you are working on:**
Godot tutorial

**Describe the problem or limitation you are having in your project:**
Godot refers to function parameters as "arguments", in some places, which is confusing.
For example, if I have this simple function:
```
func add(n1:int, n2:int):
	print(n1 + n2)
```
and I try to do this:
`add("John ", "Doe")`

I get this error message:

`At "add()" call, argument 1. Assigned type (String) doesn't match the function's argument type (int).`

The function's **_parameter_** is an **int**, and the **_argument_** is a **String**, but the error message seemingly has them backwards, or at least uses the word "**argument**" to refer to both a parameter and an argument.

(I'm sure there are other instances where this happens, but that's just one example.)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Replacing "argument" with "parameter" where appropriate could make error messages and other documentation easier to understand.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
An example of a clearer error message:
```
At "add()" call, argument 1:
	Argument-Parameter mismatch: Expected int, received String.
		Function parameter #1 (n1) declared as type int.
		Passed argument #1 ("John") is of type String.
```
The error messages could either be replaced with new ones (like the example I just showed above), or a Find&Replace could be done to change the word "argument" to the word "parameter" where appropriate.
```
1. Find: "argument" (case sensitive) (Choose only confusing/incorrect usages)
2. Replace with: "_TEMP_PARAMETER_"

3: Find: "parameter" (case sensitive) (Choose only confusing/incorrect usages)
4. Replace with: "_TEMP_ARGUMENT_"

5. Find: "_TEMP_PARAMETER_"
6. Replace with: "parameter"

7. Find: "_TEMP_ARGUMENT_"
8. Replace with: "argument"

9-16: (repeat for uppercase "Argument" and "Parameter")
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not possible with an add-on.

**Comment by Calinou** [comment]
I've seen an occasionally-followed convention where "parameter" is used for function declarations only and "argument" in all other cases (function calls, ...).

**Comment by Kequc** [comment]
I've understood "argument" to refer to function definitions as well as calls, and "parameter" to refer to members on an object. Such as `my_object.my_param`.

Been curious for a while what the actual correct terms are but it seems there's a lot of opinions.

**Comment by Calinou** [comment]
@Kequc "property" seems to be a more widely used term for members of an object.

**Comment by clayjohn** [comment]
I agree we should be very clear about separating how we use "argument" and "parameter", I'm sure the docs could also use some clean up as well. 

In my mind "argument" is external to the function while "parameter" is internal. So for the above example, "John" is the argument, while "n1" is the corresponding parameter. Accordingly I think the error message is correct. While you are in the body of "add" it makes sense to refer to the two parameters, but while you are outside the body of add, you never deal with parameters, you only deal with arguments. "John" is a string but it should have been an int. Therefore it would be correct to say that add expected an int argument but received a String argument instead.

**Comment by Error7Studios** [comment]
> Therefore it would be correct to say that add expected an int argument but received a String argument instead.

**Comment by Calinou** [comment]
@Error7Studios Keep in mind error messages can only span one line (even if long), so we have to keep it relatively short for those using less wide displays.

**Comment by Error7Studios** [comment]
> How about this?
> 
> At "add()" call, argument 1. The passed argument's type (String) doesn't match the function's expected argument type (int).

@Calinou  That looks great!
