### ISSUE TITLE
Allow gradients to interpolate in other color spaces besides sRGB

### ISSUE THREAD

**Issue by Giwayume** [godotengine/godot-proposals#6702]
### Describe the project you are working on

Project that needs linear sRGB color interpolation for gradients.

### Describe the problem or limitation you are having in your project

https://docs.godotengine.org/en/4.0/classes/class_gradient.html#class-gradient

When using the gradient class to sample colors, the interpolated colors are made in the (perceptual; gamma corrected) sRGB color space. This is basically the least useful color space for sampling gradients, as the interpolated colors become dark and muddy. In general, linear sRGB makes for prettier gradients. Oklab also does a great job (and became a new web standard color space).

Note that when I say "linear sRGB", this is a markedly different concept from the existing setting `interpolation_mode = Gradient.GRADIENT_INTERPOLATE_LINEAR`.

Here are linear color interpolations between blue and yellow in different color spaces:

![image](https://user-images.githubusercontent.com/4075314/232242516-5a88e1f0-6bdb-4045-ab54-8c4ea89c7204.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Provide a new gradient setting for picking a color space. I suggest, along with the current default of "sRGB", add "linear sRGB" and "Oklab".

This page has a nice live comparison of different color space interpolations:

https://raphlinus.github.io/color/2021/01/18/oklab-critique.html

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
var gradient = Gradient.new()
gradient.color_space = Gradient.COLOR_SPACE_SRGB
gradient.color_space = Gradient.COLOR_SPACE_LINEAR_SRGB
gradient.color_space = Gradient.COLOR_SPACE_OKLAB
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

One could implement their own version of the Gradient class, or instead of using the "sample" method on the gradient class, write their own sample method that takes a Gradient instance as argument. This does not, however, help when generating GradientTexture1D or GradientTexture2D from a Gradient. Those would also need to be custom coded if creating your own sample function.

Or use shaders. The problem with using shaders to generate gradients, is that gradient textures are more performant at runtime once generated. It is also cheaper for a gradient shader to use a GradientTexture1D as a color lookup as opposed to writing some custom looping solution to interpolate colors between stops.

### Is there a reason why this should be core and not an add-on in the asset library?

An addon wouldn't be able to modify the core Gradient class.

**Comment by Calinou** [comment]
Sounds good to me. I wonder if this can be used to create smoother blob/corona textures than with the current implementation – right now, these look kind of "sharp" even when using cubic interpolation.

**Comment by Giwayume** [comment]
If you need a reference implementation for oklab, can look here:

https://github.com/opengraphica/opengraphica/blob/c2da7023e72069add25f37ab4473d3a3f44fb7df/src/lib/color.ts#L269-L336

For sRGB to linear and back (pseudo-code):
```
var color1 = Color(1, 0, 0, 1)
var color2 = Color(0, 0, 1, 1)
color1 = color1.srgb_to_linear()
color2 = color2.srgb_to_linear()
var interpolated_color = color1.lerp(color2, 0.5).linear_to_srgb()
```

For sRGB to Oklab and back (pseudo-code):
```
var color1 = Color(1, 0, 0, 1)
var color2 = Color(0, 0, 1, 1)
color1 = color1.srgb_to_linear().linear_to_oklab()
color2 = color2.srgb_to_linear().linear_to_oklab()
var interpolated_color = color1.lerp(color2, 0.5).oklab_to_linear().linear_to_srgb()
```

**Comment by JoNax97** [comment]
Hi!

I wonder if anyone's working on this one, I'd like to give it a try. Do you think it would be a good first issue?

**Comment by Giwayume** [comment]
The actual change to the interpolation logic is as simple as I mentioned above, I think the main concerns would be:

1. The [Color class](https://docs.godotengine.org/en/stable/classes/class_color.html) doesn't currently have fields to support "l", "a", "b" channels for [LAB colors](https://www.xrite.com/blog/lab-color-space), also "a" means "alpha" in the current Color class, whereas in the LAB model it means red/green value. (this is a problem that only needs to be solved for the Oklab color space mentioned above).
2. Maybe after implementing interpolation all of the rest of this is free, but would need to make sure the editor GUI is generating the gradient previews correctly as well as in-game.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/76545.
