### ISSUE TITLE
Add a secondary light in the Advanced Import Settings preview

### ISSUE THREAD

**Issue by jeronimo-schreyer** [godotengine/godot-proposals#6707]
### Describe the project you are working on

a 3D Game with small objects and details

### Describe the problem or limitation you are having in your project

It's not much, but I want to preview the object with a little more detail

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I added a secondary light to the preview renderer and UI buttons to turn both lights on and off, just how its done in the materials viewer in the inspector

![Screenshot from 2023-04-16 13-47-22](https://user-images.githubusercontent.com/29764541/232328703-310028a9-c4ea-4da7-aa72-8ff0e0c09b4f.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I basically grabbed the code from EditorMaterialPreviewPlugin

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think this should be in core

### Is there a reason why this should be core and not an add-on in the asset library?

This improves the 3D importing experience using the editor

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/pull/75787.
