### ISSUE TITLE
Rename DirAccess to DirectoryAccess

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-proposals#6708]
### Describe the project you are working on

Any project which requires parsing of user files (no editor dialogue)
In my case, an editor tool.

### Describe the problem or limitation you are having in your project

I want to iterate over 4000 folders/directories. I am familiar with FileAccess, and went to use "DirectoryAccess"
Not found.
"Search help" -> "Directory" -> No results
"Search help" -> "Folder" -> No results

In fact, I got misled, as I ended up on EditorFileSystemDirectory!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Literally rename a class. No functionality change. There is no reason to hide some characters from the class definition, as it obscures it from autocomplete + search + user intuition.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but finding it as a user who knows not of DirAccess took time, which was annoying. Should be as straightforward as fileaccess.

### Is there a reason why this should be core and not an add-on in the asset library?

Plugin for a rename is illogical

**Comment by AThousandShips** [comment]
`dir` is used a lot more than `directory` in the codebase, because its more convenient

**Comment by RedMser** [comment]
Additional search keywords for class and method names would help with this without breaking compat. I believe there's already a proposal for that.

**Comment by TheYellowArchitect** [comment]
I love the above suggestion and prefer it to renaming. Basically autocomplete on GDScript and "Search Help", so typing "directory" includes "DirAccess" (as if user typed "dir")

It doesn't break compatibility, and can be expanded for more classes/properties/events/functions :ok_hand:

**Comment by Calinou** [comment]
> Additional search keywords for class and method names would help with this without breaking compat. I believe there's already a proposal for that.

- https://github.com/godotengine/godot-proposals/issues/5085

**Comment by KoBeWi** [comment]
We could also cross-reference FileAccess and DirAccess in their description..

**Comment by TheYellowArchitect** [comment]
>I'd suggest closing this proposal in favor of https://github.com/godotengine/godot-proposals/issues/5085, since we won't accept compatibility-breaking changes of this style for a couple of years at least. (Marking things as deprecated is OK, but "cosmetic" renames aren't.)

I agree fully.
