### ISSUE TITLE
TouchScreenButton as a Control object instead of Node2D.

### ISSUE THREAD

**Issue by michaldev** [godotengine/godot-proposals#6714]
### Describe the project you are working on

Mobile game

### Describe the problem or limitation you are having in your project

TouchScreenButton is a button that is part of the user interface. However, it has been inherited from Node2D instead of Control. Because of this, it cannot be positioned using HBoxContainer and other UI containers.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

-

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

-

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by AThousandShips** [comment]
Please actually fill in the questions, they are not optional, or open a discussion of you can't/won't

**Comment by YuriSizov** [comment]
Thanks for your suggestion, but I think we should close this in favor of https://github.com/godotengine/godot-proposals/issues/3976, which provides an actual proposal for how this could be achieved.
