### ISSUE TITLE
Implement a do...while loop in GDScript for code readability?

### ISSUE THREAD

**Issue by MichaelMacha** [godotengine/godot-proposals#6719]
### Describe the project you are working on

I'm working on implementing Computational Geometry in C in GDScript, as both an exercise to refresh my understanding of it (especially by translating it) and to produce a mesh which can be sliced in a manner similar to Metal Gear Rising: Revengeance.

### Describe the problem or limitation you are having in your project

Do loops are supported in C, but not GDScript; and the typical workaround for using a while(true) with a break just doesn't work for me—the slightest mistake in the loop condition tends to result in a lock-up, and we're all human and make mistakes. It would be much easier if Godot had a do-style loop in its internal language.

Occasions when a loop needs to run at least once, but up to a select number of times, happen frequently in design, and it would be swell if GDScript supproted those too. Usually I would argue for it being extraneous, but reorganizing a do...while to work as a while is a great academic exercise, but a pain in the neck if you're just trying to get an algorithm implemented.

The example C code which I am now attempting to translate is as follows:

```
bool IsDiagonal(tVertex a, tVertex b)
{
    tVertex c, c1;
    
    c = vertices;
    do {
        c1 = c->next;
        if (c != a && c != b
            && c1 != a && c1 != b)
            && Intersect(a->v, b->v, c ->v, c1->v)
                return false
        c = c-> next;
    } while (c != vertices);
    return true;
}
```

I may be able to work around this, but I have to admit that do...whiles are one of the features I miss when working with GDScript.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Some form of loop in a future version which satisfies the specification of a do...while in C, without forcing me to rethink my loop.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The structure of do...while in C kind of runs against the general look and feel of GDScript, but I do believe that a simplification of it, onto one line, may work.

Example:

`do_while(c != vertices):`

This would behave almost exactly the same as a while loop, but would only do the check at the end of the statements, instead of the beginning; son the BNF of the language wouldn't have to be excessively modified.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As said, the usual workaround is a `while(true)` followed by a conditional break; but after thirty years of programming, that feels like "flying too close to the sun" to me. `while(true)` is generally bad form and bad smell. If I want it to run while variable `c` is not the head of my list, I should have a loop checking against it being equal to the head of the list. Telling the interpreter to always run a loop, and then break out of it in the instructions, is arguably a hack.

If I actually wanted the code to run forever, then `while(true)` might work for me just fine; but here, it doesn't adequately express my will and design as a builder.

### Is there a reason why this should be core and not an add-on in the asset library?

Modifications to language syntax seem to be a little too significant and far-reaching to be an asset library element. This should be presented as a direct and universal feature.

Additionally, there's nothing saying that a refactored `while`; something I still do myself, sometimes, when I feel that a do loop is being used unnecessarily; can't still be used simply because a `do` loop is available. It would just give the language a little more pliability.

**Comment by and-rad** [comment]
I wouldn't call it a hack, seeing as that's also how you'd write recursive functions. All `do ... while` loops can easily be refactored to regular `while` loops if you start to feel the wax melting.

**Comment by MichaelMacha** [comment]
> I wouldn't call it a hack, seeing as that's also how you'd write recursive functions. All `do ... while` loops can easily be refactored to regular `while` loops if you start to feel the wax melting.

I have no idea what your "wax melting" analogy means. I've never heard that.

That said, my most familiar definition of a hack is an attempt to use a tool for a purpose other than that which it is intended for. While loops are intended to constrain a list of instructions to continue, until a condition is met. "True" is a condition which is always met. Using a break in the middle is more conventionally used to handle exceptional conditions, not normal operations. (If it was, they might have called it something like "exit" or "leave" in C.)

By that definition, using a while loop with explicit intention to exception out of it before it completes, while giving it a bogus condition to wait for, qualifies as a hack.

Let's dig a little deeper into the underlying issue.

GDScript's big influences, as I understand it, have been Python and Lua; I often think of it as a modernized sort of thread-safe Lua. Lua has this functionality in a `repeat...until` loop. It performs an essential task, until a condition is met.

Python is a language which does not have a do...while structure. The traditional hack is to effectively copy the contents of the loop outside of the loop so that it's run once, and then run a while loop. This results in an expansion (and worse, repetition) of the code, and increased error-proneness, as a mistake inside the loop will carry over to the initial run. This is part of why it's not typically an ideal language for large projects.

What's even worse is that in examples like mine, where you may be dealing with multiple iterators, it isn't always a simple task to copy loop contents into the base code, even if it did keep cleanliness. In this example, I'm looking at what is conceptually an edge, with two vertices; each one progresses after a condition is checked on one of them. If that condition is true, the whole function returns, not just the loop.

This would mean that my final function would look like this:

```
bool IsDiagonal(tVertex a, tVertex b)
{
    tVertex c, c1;
    
    c = vertices;
    
    c1 = c->next;
     if (c != a && c != b
        && c1 != a && c1 != b)
        && Intersect(a->v, b->v, c ->v, c1->v)
            return false
    c = c-> next;
    
    while(c != vertices) {
        c1 = c->next;
        if (c != a && c != b
            && c1 != a && c1 != b)
            && Intersect(a->v, b->v, c ->v, c1->v)
                return false
        c = c-> next;
    }
    
    return true;
}

```

This is unreadable code. I would have to comment the heck out of it. If there's a bug in one place, it essentially in its duplicate. So, let's sacrifice some principles of design and use a while(true), even though that also reduces readability:

```
bool IsDiagonal(tVertex a, tVertex b)
{
    tVertex c, c1;
    
    c = vertices;
    while(true) {
        c1 = c->next;
        if (c != a && c != b
            && c1 != a && c1 != b)
            && Intersect(a->v, b->v, c ->v, c1->v)
                return false;
        c = c-> next;
        if(c == vertices) return true;
    }
}
```

Now, pretend for a moment that there's a structural error in the linked list of points, and it never actually points at the head again. (We'll overlook memory safety since GDScript doesn't usually have to deal with that.) We would have a catastrophic bug. If there's never an intersection, we might have a considerable lock. If it does return false, it will do so for what will almost certainly be the wrong reasons, and we will have no idea why.

Conclusively, do...while is not extraneous; it exists to keep code clean and readable to the human being working on it, whether it's another programmer, or the original a few weeks in the future when he's not at 100% and is recovering from a flu. In either case, clarity is key. Replacing a do...while loop with a while loop serves that about as well as using if statements and gotos instead of a for loop; sure, it would work, and yes, it used to be the standard; but most languages don't accept it because it's error-prone and hard to read.

**Comment by and-rad** [comment]
> I have no idea what your "wax melting" analogy means. I've never heard that.

I was just picking up on your "flying too close to the sun" and assumed you were familiar with the origin of that saying. I apologize if I misjudged.

> Now, pretend for a moment that there's a structural error in the linked list of points, and it never actually points at the head again. (We'll overlook memory safety since GDScript doesn't usually have to deal with that.) We would have a catastrophic bug.

I don't think I get this part. If there is a structural error in the list, `do ... while` would likewise never terminate, right?

What's wrong with this implementation?
```
    tVertex c, c1;
    c = vertices;
    while(c) {
        c1 = c->next;
        if (c != a && c != b
            && c1 != a && c1 != b)
            && Intersect(a->v, b->v, c ->v, c1->v)
                return false;
        c = c1;
    }
```

**Comment by vnen** [comment]
> > Now, pretend for a moment that there's a structural error in the linked list of points, and it never actually points at the head again. (We'll overlook memory safety since GDScript doesn't usually have to deal with that.) We would have a catastrophic bug.
> 
> I don't think I get this part. If there is a structural error in the list, `do ... while` would likewise never terminate, right?

Yeah, I think the same.

The only difference I can see between `do ... while` and `while true` with `if ... break` at the end is if there are any `continue` statement in the loop body, because with `do ... while` it would re-check the condition but with `while true` it would skip the `if` condition.

The workaround for this is using an external variable for the condition:

```gdscript
var end = false
while not end:
	end = should_it_stop()
	# Do stuff.
```

This way even if a `continue` happen at some point the `end` variable will already be updated and the condition check still happens.

**Comment by MichaelMacha** [comment]
> > I have no idea what your "wax melting" analogy means. I've never heard that.
> 
> I was just picking up on your "flying too close to the sun" and assumed you were familiar with the origin of that saying. I apologize if I misjudged.
> 
> ...
> 
> 
> What's wrong with this implementation?
> 
> ```
>     tVertex c, c1;
>     c = vertices;
>     while(c) {
>         c1 = c->next;
>         if (c != a && c != b
>             && c1 != a && c1 != b)
>             && Intersect(a->v, b->v, c ->v, c1->v)
>                 return false;
>         c = c1;
>     }
> ```

I totally forgot about the flying-to-close-to-the-sun thing. Now I get it!

Also, the problem with that implementation is that it would only terminate when c was null (or at least falsish) in C or C++, and a polygon is a closed loop. So, it would never terminate at all. The check is to see if it's pointed at the original (in this case, the designated "head" of the linked list of points), which is much easier with a do...while than a while.

**Comment by MichaelMacha** [comment]
> > > Now, pretend for a moment that there's a structural error in the linked list of points, and it never actually points at the head again. (We'll overlook memory safety since GDScript doesn't usually have to deal with that.) We would have a catastrophic bug.
> > 
> > 
> > I don't think I get this part. If there is a structural error in the list, `do ... while` would likewise never terminate, right?
> 
> Yeah, I think the same.
> 
> The only difference I can see between `do ... while` and `while true` with `if ... break` at the end is if there are any `continue` statement in the loop body, because with `do ... while` it would re-check the condition but with `while true` it would skip the `if` condition.
> 
> The workaround for this is using an external variable for the condition:
> 
> ```gdscript
> var end = false
> while not end:
> 	end = should_it_stop()
> 	# Do stuff.
> ```
> 
> This way even if a `continue` happen at some point the `end` variable will already be updated and the condition check still happens.

This is most definitely cleaner and closer to my intention, but since GDScript is all about readability, does it not make sense to simply implement a fundamental do loop? I really think it would save people some time.

**Comment by vnen** [comment]
> This is most definitely cleaner and closer to my intention, but since GDScript is all about readability, does it not make sense to simply implement a fundamental do loop? I really think it would save people some time.

I would argue that an `if condition: break` at the end is quite readable already.

The big problem is how to make a new syntax actually readable. For instance, nothing in GDScript has a concept of "end block" (apart from indentation). So how can you put the `while` at the end? Consider this:

```gdscript
do:
	# Loop body.
	while not end
	print("oops")
``` 

The `print("oops")` line cannot be allowed because it's already past the "end" of the block. Of course we can have the parser say "hey, you can't do this", but it would something unprecedented in GDScript. Missing the `while` would be a problem too (meaning it would be an error in the editor while you're typing, unless you add the `while` right away).

We could simply remove the indentation for `while` at the end:

```gdscript
do:
	# Loop body.
while not end
``` 

Which introduces a sort of "dangling while" problem. Because the only difference between the end of `do` and a new `while` is the `:` at the end. Makes it more difficult to parse, both for computers and for humans. It has the same problem of missing the `while` bit like the previous example.

We could revisit the rejected Python's [PEP 315](https://peps.python.org/pep-0315/):

```gdscript
do:
	# Setup code.
while not end:
	# Loop body.
``` 

This has this weird split between setup and loop body that no one really cares about. More often than not the "loop body" will just be `pass`.

Another option (also rejected by Python) is adding a new statement for this:

```gdscript
do_while not end:
	# Loop body.
```

That happens to be concise and doesn't get weird with indentation. But since the condition is at the top, it is more difficult to understand that the body will be executed at least once.

----

We could go on and debate more options and the pros and cons of each one, but I believe it's gonna be very difficult to find something that is immediately obvious for both beginners and experienced programmers. I doubt we can do better than Python in this regard (considering they rejected this idea).

**Comment by MichaelMacha** [comment]
@vnen Honestly I think we can do better than Python, simply because Python is attempting to cover far more cases than GDScript. It isn't really fair to compare the two, certainly not in a limiting way. GDScript also has a habit for avoiding unnecessary feature creep and arbitrary syntax, which is most of what usually drives me away from Python.

The only reason I'm making an argument for a do-until style loop is because I legitimately think the language would benefit from a structure like that, and appreciate the constructive feedback.

That said, how about a syntax like this?

```
until(end):
    #loop body

```

This is similar to Lua's syntax, gets around the need for an end block, and is distinctively different from while. The 'do' is implied. I believe that would resolve many of your concerns, including the admittedly weird structure of these loops in C, while allowing for a condition interpreted at the end instead of the beginning?

**Comment by YuriSizov** [comment]
> This is similar to Lua's syntax, gets around the need for an end block, and is distinctively different from while. The 'do' is implied.

I like the idea of having an `until` loop, for the sake of expressiveness, but it is distinctly not a `do...while` loop. In `do...while` you get your body run at least once, and then the condition is evaluated, which can be situationally useful, and IMO is the only reason to use it over the regular `while` variant. But with the syntax like

```
until condition:
  # body
```

you would expect the condition to be evaluated before the execution, so it won't be guaranteed to run at least once.

So, `until` looks interesting, and I wouldn't mind seeing it added, but if you want a `do...while` loop, that's not it.

**Comment by and-rad** [comment]
> you would expect the condition to be evaluated before the execution, so it won't be guaranteed to run at least once.

If I got that right from OP, The point of `until` would specifically be that the block is executed at least once before the condition is evaluated for the first time. Othewise there would be nothing gained over regular `while` and `until condition` would just be an alias for `while not condition`. I like that idea even less than the original proposal.

**Comment by YuriSizov** [comment]
@and-rad Yes, that was the point of OP, which is why I mention that the `until` syntax doesn't read like that. So you wouldn't expect it to run at least once when reading code.

**Comment by and-rad** [comment]
Yeah... I also just don't know if `do ... while` is really worth having. I'm looking at a game with fairly complex mechanics right now and in more than 50.000 LOC there is not a single instance of it in sight.

**Comment by ator-dev** [comment]
To add an unnecessary qualifier, in my experience there have been exactly two reasons for using `do ... while` syntax:
- Avoidance of functional programming, i.e. by extending the while construct to even more cases that "look natural"; often for reasons of efficiency
- Slight efficiency and readability gain of not using an additional variable or having "setup code"

Both of these problems can be solved using functional programming, and neither especially make sense in a language not designed for efficiency. If you need efficiency, you can use something like C# or C++, which in fact *do* have `do ... while` syntax.

I know all of the points have been made, just wanted to add my perception of `do ... while` :slightly_smiling_face:

**Comment by MichaelMacha** [comment]
Fair enough. Feature bloat is a real risk to any language, and Godot is already extraordinarily extensible as it stands. If it becomes that much of an issue for me, I'll just find another language binding.

The people have spoken.
