### ISSUE TITLE
CCD algorithm，raycasting and shapecasting

### ISSUE THREAD

**Issue by wzj18133771025** [godotengine/godot-proposals#6730]
### Describe the project you are working on

Continuous collision detection

### Describe the problem or limitation you are having in your project

I want to konw the CCD algorithm of Godot Engine. The doc mentioned that : Continuous collision detection enabled using raycasting and using shapecasting. But I can not find any information about these to CCD methods. Can anyone give me some help? Paper or algorithm.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1

### If this enhancement will not be used often, can it be worked around with a few lines of script?

1

### Is there a reason why this should be core and not an add-on in the asset library?

1

**Comment by YuriSizov** [comment]
Please refer to the comment in https://github.com/godotengine/godot/issues/76313.
