### ISSUE TITLE
Add a way to load resource pack from project settings.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot-proposals#6731]
### Describe the project you are working on

A frequently updated visual novel, that players have to download from the link I shared from my cloud drive, or itch.io.

### Describe the problem or limitation you are having in your project

I separate the game assets into several resource packs (.pck/.zip).to reduce download size for game updates. (data plan and slow internet is still a thing in many places I believe. ) I load these packs using `ProjectSettings.load_resource_pack` in `_init` of an autoload. 
1. I pack images/animations of each version into single resource packs, eg. img_v100.pck, img_v200.pck. These .pcks are very large, often around 200 MB. When there is a new version, players download only one new pck file.
2. UI, logic, etc. are all exported to the main pack, eg. GameName.pck, and this file is 40MB. When there is a new version, players replace this pck with a new one. ( I had to put *.otf, *.ttf in exclude, or they will be automatically included in the main pck, even if I didn't select them, looks like a bug? )
3. All font files (.otf/.ttf) (32MB) are exposed in the folder, without packing into a pck or zip. This pck, most of the time just remains the same.

Now I want to also pack the fonts in a .zip file too. It works.

**However, the default theme/font (`gui/theme/custom` and `gui/theme/custom_font`), are loaded in ProjectSettings. This process is earlier than any autoload. I have no way to load fonts from a resource pack for default theme to use.**

It will give you this error, and the texts are invisible.

> ERROR: Cannot open font file 'res://fonts/font.otf'.
>    at: _load (scene/resources/dynamic_font.cpp:143) - Method failed. Returning: ERR_CANT_OPEN

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If you can specify the resource packs (.pck/.zip) that needs to be loaded in the project settings, and it is earlier than custom/custom_font, then it is feasible to pack the fonts into a resource pack.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a tab in project settings to specify the resource packs to load.

Another way: allowing to set the default theme for the whole game in runtime.

(Not sure which is better to implement.)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Just set a theme for the root control node in every scene. It's easy, just a little inconvenient.

So this is really just an feature request for a not so useful feature.

### Is there a reason why this should be core and not an add-on in the asset library?

it is core.

**Comment by KoBeWi** [comment]
You can manually assign the font by modifying `default_font` of the project's Theme.

**Comment by rambda** [comment]
> You can manually assign the font by modifying `default_font` of the project's Theme.

Wow, it works. Just reassign the default font to the theme after loading the font.
```
load_pck("fonts.zip")
load("res://src/default_theme.tres").default_font = load("res://src/default_font.tres")
```
 Thanks!
