### ISSUE TITLE
Porting from Godot 3.5.2 to 4.x should be porting the Input Map

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot-proposals#6736]
### Describe the project you are working on

Games with keyboard support

### Describe the problem or limitation you are having in your project

When I ported a game from Godot 3.5.2 to 4.0.2 I always have to readd all the keys. Especially if you have a lot of hotkeys this is very tedious. Would make the transition a lot nicer.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Port the Input Map from Godot 3.5.2 to 4.0.2 - if this can't be done 100%, you can add a little message that the user should check if it was done properly.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Input Map 3.5.2 -> Input Map 4.0.2

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used for every project that is ported from Godot 3.x to 4.x. It can be done manually but is tedious.

### Is there a reason why this should be core and not an add-on in the asset library?

The porting process is essential to the core of Godot 4.x.

**Comment by Zireael07** [comment]
This is a bug, not proposal material

**Comment by Daniel-da-Silva** [comment]
Oh, I thought this was just an oversight. I will open a bug report then.
