### ISSUE TITLE
Add property autocompletion for `tween_property()`

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#6739]
### Describe the project you are working on

Game in Godot.

### Describe the problem or limitation you are having in your project

I use Tweens quite a bit, but I sometimes lack some more friendly way to tween properties. `tween_property()` does not come with autocompletion, so it's one of the very few things that you need to type manually.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`tween_property()` should provide autocompletion for property list, similar to e.g. method list when using old `connect()`:
![image](https://user-images.githubusercontent.com/2223172/233803050-b5912c22-2220-4031-ab85-a58cd1f636e3.png)
The list depends on the previous argument. It would appear here and list properties of the object in the first argument:
![image](https://user-images.githubusercontent.com/2223172/233803086-2a6dec68-1493-4010-9e9f-51ee4f56ed20.png)

It would make it easier to pick properties to tween.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I think it would be implemented similarly to the aforementioned list of methods. I don't know if it's done via `get_argument_options()` or something different. I remember I tried to implement it myself a couple of times, but failed >_>

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Kind of? If you have no autocompletion, the workaround is to just write it I guess.

### Is there a reason why this should be core and not an add-on in the asset library?

Not sure if possible. Tween is core feature tho and it would benefit everyone that uses it.

**Comment by Mickeon** [comment]
This is unfortunately not possible with the current available methods, if not by making a special case for it. `get_argument_options` cannot infer the value of any previously inserted argument.
