### ISSUE TITLE
Add a DisplayServer.get_screen_image() method

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#6742]
### Describe the project you are working on

A screen capture application.

### Describe the problem or limitation you are having in your project

I want screen my screen and use `DisplayServer.get_screen_pixel` method.
And I found this method take me too long time(16ms), if I want take a 16x16 size, it will take 16x16x16=4096ms, if I want take full screen, it will take 1920x1080x16=33,177,600ms=552.96m=9.2h.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a `DisplayServer.get_screen_image()` method, and if I want capture a rect, I can use `Image.get_region()` method, if I want capture a pixel , I can use `Image.get_pixel()` method.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't , `DisplayServer.get_screen_pixel()` take me too long time.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, it's maybe can be implement gde. But I think it should be core. And for me. I don't want use any addon.

**Comment by AThousandShips** [comment]
Being implemented in godotengine/godot#75142

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/75142.
