### ISSUE TITLE
Regenerate all fields when reimport assets

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#6743]
### Describe the project you are working on

A 3D GAME

### Describe the problem or limitation you are having in your project

I don't what's happend, but my project was breaked.
The issue here: https://github.com/godotengine/godot/issues/75525
For long test, I found was there was 3 assets have the same uid.
I'm try delete the uid field or delete .import file all can resolve my problem

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Regenerate all fields when reimport assets (like new import)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For some problem, like https://github.com/godotengine/godot/issues/75525. I can solve it simply reimport. And I think reimport it mean REIMPORT, not use any cache information.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's can't.

### Is there a reason why this should be core and not an add-on in the asset library?

No, it's can't.

**Comment by AThousandShips** [comment]
Regenerating UIDs is a terrible idea and shouldn't be done, UIDs should remain constant for imported assets (which is a separate bug where it doesn't happen for some cases), if the UID is changed then the imported data won't be accessible to scenes etc. and it'll break everything, this is exactly why UIDs exist

This is not the way to solve collisions in UIDs, that does need to be solved though but this is not the way

**Comment by AThousandShips** [comment]
I have no idea how duplicate UIDs happened in your case, but it *shouldn't* and making such a drastic change to fix a bug or user error that broke UIDs is not the solution

**Comment by CsloudX** [comment]
Yes, I'm think again. Change uid was bad idea. When reimport, it should read my changed options and uid was not valid option for  asset.
Maybe add step to check there was same uid for project's assets was a good idea.
