### ISSUE TITLE
[C#] make GetNode return dynamic type

### ISSUE THREAD

**Issue by ChloePrime** [godotengine/godot-proposals#6748]
### Describe the project you are working on

Minecraft-like game, but this is useful for any project.

### Describe the problem or limitation you are having in your project

in C#, get a child node with specific type needs to enter the type in the get method, which is cumbersome

```C#
public class SomeUltraLongNamedActorGameObjectClass : Node3d
{
    public void Test()
    {
         SomeUltraLongNamedActorGameObjectClass another = GetNode<SomeUltraLongActorGameObjectClassName>("subobj");
    }
}
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

C# has a intrinsic type called "dynamic" that supports dynamic typing, like GDScript does.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

in GodotSharp:
```C#
public class Node : GodotObject
{
    public dynamic GetNode(NodePath path) => ......
}
```

in game code:
```C#
public class SomeUltraLongNamedActorGameObjectClass : Node3d
{
    public void Test()
    {
         SomeUltraLongNamedActorGameObjectClass another = GetNode("subobj");
    }
}
```

just like how it is done in GDScript ~

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be done using extension methods, but that extension method must be renamed, which maybe ugly

```C#
public static class Extensions
{
    public static dynamic GetNode2(this Node node, NodePath child) => node.GetNode(child);
}
```

### Is there a reason why this should be core and not an add-on in the asset library?

It's a core method in a core class called Node

**Comment by SeleDreams** [comment]
That's probably not a good idea, because dynamic is very inefficient for game development. it's a typing that should usually be avoided.

**Comment by ChloePrime** [comment]
> 

It's just used for auto casting, after assigning it'll enter static typing again

**Comment by ChloePrime** [comment]
Closing because it's implementation is too slow (and garbageful as it news a CallSite)

**Comment by KoBeWi** [comment]
You can use `var another = GetNode<SomeUltraLongActorGameObjectClassName>("subobj");`
