### ISSUE TITLE
Add support for animated sprites in rich text bbcode.

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot-proposals#6759]
### Describe the project you are working on

Platformer

### Describe the problem or limitation you are having in your project

I'd like to have a prompt that shows an animated controller stick indicating how to crouch, as the static image seemed to confuse some users, but currently, I can only specify static images with the img tag in the RichTextLabel bbcode.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Instead of only allowing image resources in the img tag, also allow for sprites (or possibly whole scenes, but that might get too crazy).  Related to https://github.com/godotengine/godot-proposals/issues/89 as there's a possibility the solution to one of these could resolve them both, but they're slightly different requests.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Instead of just: `[img]path/to/image.png[/img]`

Also allow: `[img]path/to/sprite.tsn[/img]` or possibly a new `[sprite]` tag.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

RichTextLabel is pretty core -- I don't think a simple addon could work around this.

**Comment by YuriSizov** [comment]
Since any texture resource works with that tag, you can use `AnimatedTexture`.

**Comment by jitspoe** [comment]
Oh, cool, I didn't realize that!  Would still be nice to be able to use sprites with shaders and such, but this covers my immediate needs.  Thanks!
