### ISSUE TITLE
Allow 3D Shadows for Godot 4 Compatibility Mode

### ISSUE THREAD

**Issue by mujtaba-io** [godotengine/godot-proposals#6774]
### Describe the project you are working on

A 3D game with the need of shadows similar to godot 3.x shadows.

### Describe the problem or limitation you are having in your project

Shadows require Vulkan backend, but since I a developing for GL3, it needs to be able to render 3D shadows similar to how it did in 3.X versions. - I cannot use 3.X versions since I am using shader sky and other godot 4 features.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Is there a way to port 3.x shadow module to godot 4?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We can somehow port old code if possible.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I dont think so. It is very important.

### Is there a reason why this should be core and not an add-on in the asset library?

Because shadows as an addon can be expensive to compute, rather than being built in.

**Comment by Zireael07** [comment]
This is not a feature request - this is a known bug/incomplete implementation, already tracked on the main repo.

**Comment by Calinou** [comment]
- See https://github.com/godotengine/godot/issues/66596.
