### ISSUE TITLE
Add `FileAccess.set_length(new_length)` to truncate existing files

### ISSUE THREAD

**Issue by tagcode** [godotengine/godot-proposals#6776]
### Describe the project you are working on

Modifying existing files, such as game state, cannot be shortened.

I cannot truncate file. 

### Describe the problem or limitation you are having in your project

File can be enlarged by writing new content, but cannot be shortened.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add FileAccess.set_length()

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Calls OS IO function that shortens file size.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I know of.

### Is there a reason why this should be core and not an add-on in the asset library?

Basic necessity low-level IO function.

**Comment by AThousandShips** [comment]
I'm not sure how common this is in lower level details, or the way truncation of files is supported in various platforms other than copying the data

**Comment by tagcode** [comment]
Really?

On C# there is [FileStream.SetLength()](https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs,d6c30590c2fd88be). On Windows it seems to call [Kernel32.dll](https://referencesource.microsoft.com/#mscorlib/microsoft/win32/win32native.cs,d99b9a53eb067f94).

On Linux I believe it calls (ftruncate)[https://linux.die.net/man/3/ftruncate]?

**Comment by bruvzg** [comment]
> There's no way to do this as far as I know in the standard c++ library for example

Godot is not limited to standard C++ file API, it's already relaying on `unistd.h` and Windows API for it, so this is not an issue.

`ftruncate` should be supported on all Linux/BSD, Android and macOS/iOS systems. And WinAPI have https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setendoffile.

**Comment by Calinou** [comment]
How does this compare to opening a file, reading its first N bytes and saving that over the existing file? I assume a `ftruncate()` call is faster, but by how much on average?

**Comment by AThousandShips** [comment]
@bruvzg I am aware that's why I said "for example" as I was unsure how cross platform supported this was for an open file

**Comment by tagcode** [comment]
> How does this compare to opening a file, reading its first N bytes and saving that over the existing file? I assume a `ftruncate()` call is faster, but by how much on average (on a SSD)?

1. File might be very large, e.g. 1GB
2. OS differences cause unexpected behaviour. There might be open handles to the file. On linux old handles would refer to old file, changes would not be visible. On windows deleting would be forbidden and operation would fail. Truncate, on the other hand, would not forbid open handles.

**Comment by somebody1234** [comment]
i think this is pretty valuable because the handle never gets closed - which is useful for text editors which may want to prevent the file from being deleted from under the engine's nose
