### ISSUE TITLE
Separate Alpha curve from Color curve in the Particle Process input + add emission curve

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#6779]
### Describe the project you are working on

Various VFX

### Describe the problem or limitation you are having in your project

Working with merged alpha and rgb in VFX is very annoying. There's multiple ways this could be solved within Godot.
Please read below my solution to it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I work on a variety of VFX in a professional setting. For the type of VFX that I make, I often end up using alpha dissolve/erosion in my shaders (dissolve from now on).
Example:
https://user-images.githubusercontent.com/7917475/235350251-5f789a5c-4440-4f30-8e81-ca55a96092f1.mp4

Sometimes, I want to change the color palette of an effect to "reskin" it for another purpose. The colors being intrinsically tied to the alpha makes it clunky and makes the palettes non-reusable across multiple VFX.

Color as in the rgb component, is a key part for the effect's palette and personality. We use color to convey the substance effects are made of. Think of classical fire and water, entirely different palettes!

Alpha, in particles, is related to motion and timing. It informs of how long the effect stays on screen, how long it lingers.
This can vary a lot in a single VFX! Some elements are very instantaneous while others linger.

The way I need to manipulate timing across different particle systems within the same effects, makes it impossible to reuse a combined alpha+color gradient even inside the same VFX, just because i need particles to disappear at different rates and with different curves.

This is when things get tricky. Suddenly I don't have a single color gradient anymore, but rather I start having one per different particle systems. And particle systems count go up very very fast. So then, to reskin an effect in term of color, i suddenly need to edit 5, 10, 20 gradients. It doesn't scale at all.

For example, this "simple" hit effect (simple in the sense that in a game this is one of the smallest/simplest VFX you'd have)

https://user-images.githubusercontent.com/7917475/235351270-f9f096af-de53-4537-8c34-c87af8d8ef6a.mp4

Is made of those emitters:

https://user-images.githubusercontent.com/7917475/235351301-3a696d50-708e-467a-b431-612ede0d687a.mp4

![image](https://user-images.githubusercontent.com/7917475/235351307-4e38b17d-0bd7-4f41-baf7-da573874c01c.png)

Imagine a bigger explosion .. :D

Ideally, I'd like to be able to have my "lava palette" and my "water palette" of colors (rgb) in a way that I can apply it to multiple particle systems: this way, the concept of "color" is entirely decoupled for the timing of the effect.

Initial gradients don't cut it here because very often effects have a "hot color" and a "cold color" respectively for when the effect is at the height of the energy, and when the energy disperses. Think of explosions: they start bright yellow, go to red, then grey smoke. If i was using a start gradient, some particle would spawn "hot color" and stay hot and some particle would spawn "cold color" and be cold at the beginning of the explosion!

Gradient textures having the possibility to separate alpha and emission from color would be an improvement but would still not solve the highlighted problems with workflow and reusability of color palettes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the color section of particles
![image](https://user-images.githubusercontent.com/7917475/235350706-809fe1c5-4881-475f-bf2c-d95f636cdfed.png)
add the following properties
- split alpha
- (if split alpha is on) a curve for alpha
- split emission
- (if split emission is on) a curve for emission

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It could be done by a special gradient texture , but it would significantly worsen the proposed workflow

### Is there a reason why this should be core and not an add-on in the asset library?

see above.

**Comment by Calinou** [comment]
This could be done by adding a Curve property to GradientTexture that acts as an alpha multiplier. For your use case, the main gradient would be fully opaque but you'd use the curve property to multiply the gradient's opacity.

**Comment by QbieShay** [comment]
I mentioned the possibility of a solution with GradientTexture 

> Gradient textures having the possibility to separate alpha and emission from color would be an improvement but would still not solve the highlighted problems with workflow and reusability of color palettes.

But that would not be as ideal (and I think even more complicated to implement?) than having it directly in the particle system, and I think UI wise you'd also have an extra nesting layer in the inspector because it would be another sub-resource. 

The way I imagined this working is the following.
You have these 3 elements, color gradient, alpha curve, emission curve.

Inside of the particle shader, you combine them (color gradient's alpha should be multiplied by alpha curve's alpha)

In the shader/material, you can separate them by doing the following:
- emission intensity is the maximum between r, g and b
- alpha is alpha
- rgb is rgb divided by emisssion when emission is above 1

What do you think?

**Comment by reduz** [comment]
Emission curve in process material is not possible because there is no way to pass this information to the material shader. IMO this should go somewhere in the material shader using the lifetime value that you get from the particle to control emission.

**Comment by QbieShay** [comment]
I have a functional prototype in https://github.com/godotengine/godot/pull/79527

**Comment by QbieShay** [comment]
Closed by https://github.com/godotengine/godot/pull/79527
