### ISSUE TITLE
Integrate "Create Root Node" step into "Create Scene" dialog

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-proposals#679]
**Describe the project you are working on:**
Not applicable.

**Describe the problem or limitation you are having in your project:**
Creating a new scene from the context menu in FileSystem dock is a two-step process, and it really does not need to be. There is no reason to have a scene without a root node, so it makes sense to allow a selection of the root node type together with scene creation.

See also #680.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding the "Create Root Node" form similar to the Scene dock for an empty scene should be sufficient.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
This suggestion only affects the context menu in FileSystem dock way of creating a new scene. Only this flow has a dialog prompting the user to enter the scene's name. It is possible to create a new scene from the File menu, or simply by pressing the shortcut combination.

It can be argued that in these cases the dialog is not possible to include, as the scene created this way cannot be associated with a path in the filesystem. I'm not going to suggest we add the same dialog for that flow as well.

Same applies to a new project. It automatically has a virtual scene created and displayed as soon as it is opened. Whether or not we should ask a user straight away if they want a 2d or 3d scene and create it with a corresponding root node I do not know, but it's a possibility.

Here is how it should work for a new scene created via the context menu:
![create-scene-popup](https://user-images.githubusercontent.com/11782833/78782291-74d8fc00-79aa-11ea-8947-bc4b4da1bc98.png)

It should work just the same as it does currently, though instead of outright creating the node it just selects its type until the moment the scene itself is created. Then the node is inserted as well.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It cannot be solved by a simple script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
While I can imagine an extremely hacky plugin that is able to do it, I'd prefer it to be the default experience for everyone using the editor. But I do think it is doable as a plugin, in some form.

**Comment by pycbouh** [comment]
I realized, that this does not cover the case when a scene is created via the "File" menu or an editor shortcut. Well, they can work the same as now as well, for now. I have no proposal what to do about them, as adding a dialog to name such scene would be pointless, because that scene is not yet associated with any directory.

**Comment by pycbouh** [comment]
I've changed the text to reflect only the initial idea to extend the scene creation dialog and extracted parts about disallowing root node deletion into a separate proposal: #680

**Comment by KoBeWi** [comment]
The mock-up looks interesting. Yeah, the scene creation dialog in filesystem dock needs improvements. I would also add a warning about existing file, similar to how scripts dialog work. Right now if you type existing name, the dialog will close with failed result xd

**Comment by LightningAA** [comment]
Silly question, but why is this dialog necessary/better than the other existing ways of creating a scene?

**Comment by pycbouh** [comment]
> Silly question, but why is this dialog necessary/better than the other existing ways of creating a scene?

You'd prefer we removed a way to name a scene here instead?

**Comment by KoBeWi** [comment]
> Silly question, but why is this dialog necessary/better than the other existing ways of creating a scene?

Some people complain that creating new scene from FileSystemDock doesn't create file until you save the scene. We can't do anything about it, because you can't save a scene without root node. So such dialog would solve the issue.

**Comment by pycbouh** [comment]
Just in case there is some mix-up: there is a dialog already, but it only allows you to name a scene beforehand. This proposal is to add a root node selector alongside the name, so that the scene can be saved immediately. This approach can be applied to all the other way to create new scenes, in fact.

**Comment by LightningAA** [comment]
I was asking why there needs to be a dialog in FileSystem in the first place, I've been using Godot for several months and I'm pretty sure this is the first time I've ever used it...

**Comment by pycbouh** [comment]
> I was asking why there needs to be a dialog for creating a new scene in FileSystem, I've been using Godot for several months and I'm pretty sure this is the first time I've ever used it... there's already `Scene->New Scene` and the `+` button

I use the FileSystem dock exclusively as it attaches the future scene to a specific folder and you can name it straight away, with the very first save on it creating the file without any dialogs.

**Comment by KoBeWi** [comment]
Implemented by https://github.com/godotengine/godot/pull/61954
