### ISSUE TITLE
Add Timer.started signal

### ISSUE THREAD

**Issue by feois** [godotengine/godot-proposals#6791]
### Describe the project you are working on

Not important

### Describe the problem or limitation you are having in your project

I have items that have cooldown and I want UI to react when cooldown starts

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think `Timer` should have a `started(duration: float)` signal that is emitted when `Timer.start()` is called

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add signal `Timer.started`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can easily be implemented in scripts using custom signal but it's inconvenient

### Is there a reason why this should be core and not an add-on in the asset library?

`Timer` is a core class

**Comment by Calinou** [comment]
> I think Timer should have a started(duration: float) signal that is emitted when Timer.start() is called

When you call the `start()` function, you can call another function on the node directly. You don't need signals to achieve this.

**Comment by feois** [comment]
> > I think Timer should have a started(duration: float) signal that is emitted when Timer.start() is called
> 
> When you call the `start()` function, you can call another function on the node directly. You don't need signals to achieve this.
> 
> Signals are a good way to _signal_ things up, not signal them down.

Well, my UI isn't in the item's scene and I thought signal is for this purpose? Unless you mean calling nodes from other scenes (which iirc isn't best practice).

For example, my scene tree is like this
Root
-UI
-Item

I want UI to react when item's cooldown timer starts so my original idea is to make custom signal that UI connects to in runtime but I find that inconvenient and so I opened this proposal.

(If my idea from the beginning is not the best practice at the first place, please let me know, e.g. better scene structure)

**Comment by feois** [comment]
Actually, now that I give it more thought, yeah this probably is unnecessary, sorry for taking up your time.
