### ISSUE TITLE
Add AnimationPlayer 2D and 3D

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot-proposals#6800]
### Describe the project you are working on

2D roguelike in 3.5.2

### Describe the problem or limitation you are having in your project

Since the project was getting too big and messy because of various little and quick experiments and tests i decided to make things as encapsulated as possible and properly rewrite the messy code so that a node calls their children's functions and emit signals to the parent. The problem is that AnimationPlayer is designed to sort of break that phylosophy since it can animate children, brothers and even the parent, and even if i try to limit myself by making an AnimationPlayer animate only its children since AnimationPlayer isn't a Node2D its children have transforms not affected by the one of the AnimationPlayer parent.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

No one likes limitations so i guess this won't be a popular request but i think that AnimationPlayer2D and 3D that only animate their children would make things more maintainable. Obviously the original AnimationPlayer could still be there, exacly like there are AudioStreamPlayer 2D, 3D and not 2D/3D. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

They will behave exactly like the existing AnimationPlayer, except that they will have 2D/3D properties and can only animate their children. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm making AnimationPlayer as the root of the scenes and making it control its children's positions, but since AnimationPlayer is not positional you can understand that it causes many inconveniences.

### Is there a reason why this should be core and not an add-on in the asset library?

AnimationPlayer is one of the very core features of Godot.

**Comment by MewPurPur** [comment]
There is not much in common between your suggestion and AudioStreamPlayer2/3D. Those have a 2/3D position that they play their sounds from. But there's nothing to possibly be positional about animations though.

The highly specific requirements you're suggesting (i.e. only acting on nodes) seem arbitrary and only based on how you want to specifically design your project.

> If this enhancement will not be used often, can it be worked around with a few lines of script?

The child-only requirement should be able to be worked around like so:

```gdscript
@tool
class_name ChildAnimationPlayer extends AnimationPlayer

func _process(_delta: float) -> void:
	# No good signal for detecting when an animation changes...
	# So instead, update configuration warnings every few frames.
	if Engine.is_editor_hint() and Engine.get_process_frames() % 30 == 0:
		update_configuration_warnings()

func _get_configuration_warnings() -> PackedStringArray:
	for anim_name in get_animation_list():
		var anim := get_animation(anim_name)
		for track_idx in anim.get_track_count():
			if anim.track_get_path(track_idx).get_name(0) in [&"..", &"."]:
				return PackedStringArray(["AnimationPlayer2D is animating a non-child."])
	return []
```

**Comment by 2plus2makes5** [comment]
@MewPurPur 

If in a scene there's a node that controls all the other nodes then we agree that it's good practice to make that node the root of the scene right?

Well unlike all the other nodes AnimationPlayer _by design_ controls all the other nodes, it should be the perfect fit for a root, but it's not positional so using it as a root is very clunky because it needs lots of workarounds.

It's incredible to me that a node that is designed to control all the other nodes isn't good as a root. 

Am I wrong in thinking that despite AnimationPlayer being almost omnipresent people use all kinds of nodes as roots but not AnimationPlayer? It feels wrong to me and limits the possible usage of AnimationPlayer and the possibilities of scene composition.

Just to be clear the proposal isn't called "make AnimationPlayer operate only on its children" but "Add AnimationPlayer 2D and 3D" because the positional aspect is my priority. Limiting the editing to children was just an idea to promote "better" practices, but if you don't want it I'm ok with that, what I really want is AnimationPlayer to be positional.

Obviously it's all just my opinion.

**Comment by 2plus2makes5** [comment]
@AThousandShips 

I'm not saying that AnimationPlayer 2D and 3D have to be always root, I'm saying that if a very powerful and versatile node like AnimationPlayer is basically never used as a root it means that something critical is missing that limits its potential uses, and imo that something critical is the transform.
I repeat I'm asking to add positional versions of AnimationPlayer, not to remove the current non positional one.

**Comment by AThousandShips** [comment]
I understand that, but I don't see how adding new animation centered nodes like this would help or what it'd achieve other than confusion, it'd involve duplicating functionality and complexity, I don't see anything missing here, where would the `AnimationPlayer2D/3D` be controlled from?

**Comment by 2plus2makes5** [comment]
I understand that having more versions of the same node is a problem and I'm sorry to propose more work to the contibutors but despite animating everything AnimationPlayer always felt detatched from the scene it's in.

AnimationPlayer2D would inherit from Node2D so you would use it exactly like any other Node2D derived node. 

Having for example a KinematicBody2D as a root controlling its children via code and also having an AnimationPlayer child controlling its brothers via animations, basically having 2 different nodes controlling the same nodes with potential conflicts, seems neither clearest nor simplest way of doing things.

Despite all the hassle and clunkyness caused by the lack of positionality I'm already using the current AnimationPlayer as a root in some scenes because having a single node controlling all its children both via animations and via code to me just feels the right, almost natural, approach.

**Comment by AThousandShips** [comment]
So you're specifically looking at cases when there's no physics involved or collisions?

To me the `AnimationPlayer` feels *more* natural as one of several "components" to a character, like it can have a `NavigationAgent` or `NavigationObstacle`, it adds functionality, and it seems that that is the philosophy that made it be designed in that way, it seems that is the preferred and natural approach for the way the engine works, and that unfortunately isn't guaranteed to work for everyone, but it doesn't seem helpful to add complexity to the engine, duplicating functionality, because of that when it appears to work for the vast majority of people using the engine

**Comment by 2plus2makes5** [comment]
KinematicBody doesn't need to be the root of the node, KB can just simulate the movement and pass the result to the root that moves according to that, I stopped using KB as roots long before starting using AnimationPlayer as root. 
KB is to me is as "component" as Area or basically everything else, AnimationPlayer is the less "component" of the two.

**Comment by AThousandShips** [comment]
That's really backwards in my use and the suggested way of using the engine, I don't see your logic sorry

**Comment by 2plus2makes5** [comment]
I understand that it's hard to see the value of an approach that makes things differently from the established norms, but think about KB for example, don't you think it's incredibly limiting the norm that a scene dealing with collisions has a KB as a root? 

If KB can simulate the movement why not using it? 

If for example you want to make a Camera with collisions don't you agree it's more productive to have Camera as the root so when you put the Camera in another scene it exposes the Camera parameters in the editor? For me a Camera with collision is first of all a Camera, so it only makes sense to me that the Camera node should be the root of the Camera with collision scene.

Conventions and norms are neither laws nor immutable, they change all the times.

**Comment by AThousandShips** [comment]
> Conventions and norms are neither laws nor immutable, they change all the times.

Sure but the engine is built around a certain base approach

**Comment by 2plus2makes5** [comment]
Regarding my unusual way of doing things, I wasn't the one adding to KB the ability to simulate the movement, if it's there then it's not "illegal" to use it, the fact that no one else use it like I do means nothing.
Try making a simple Camera with collision with my method and with the usual method and judge by yourself which one is better to use.

I know that having AnimationPlayer2D/3D in addition to AnimationPlayer is a hassle and if it's asking too much then contributors can just close this proposal I will understand, but I don't see how having them, again in addition to AnimationPlayer, would go against the engine's approach.

**Comment by AThousandShips** [comment]
It goes against the general approach of not adding unecessary or duplicate behavior, the engine should be made as lean as possible, and not have redundant content

But we'll see if others think this approach is useful, just because it doesn't make sense to me doesn't mean it won't to anyone else

**Comment by MewPurPur** [comment]
RemoteTransform nodes also don't follow this rule, as well as joint nodes, and physical bones. The node mindset is used for a lot of the engine, but sometimes it hurts.

**Comment by 2plus2makes5** [comment]
After some thought I have decided to close the proposal, 
While I still think this is useful maybe the number of possible use cases is not worth the effort and downsides of maintaning duplicates.
So yeah, I'm closing it.
Thanks everyone for your time.
