### ISSUE TITLE
Show skeleton bones in the Advanced Import Settings preview

### ISSUE THREAD

**Issue by jeronimo-schreyer** [godotengine/godot-proposals#6801]
### Describe the project you are working on

A 3D game where meshes and animations come in different files

### Describe the problem or limitation you are having in your project

I need to preview animations with skeleton bones since meshes come in different files. In this case, the 3D preview window shows an empty scene

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

copy functionality as it is in the Skeleton3DGizmoPlugin to show bones according to 3D Gizmo Editor Settings values

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is a WIP

![Screenshot from 2023-05-01 21-51-16](https://user-images.githubusercontent.com/29764541/235961201-b91bd600-4a42-47ac-9b45-24eb4a283195.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Cant be done using a plugin

### Is there a reason why this should be core and not an add-on in the asset library?

This improves the 3D importing experience overall

**Comment by Calinou** [comment]
On your screenshots, it's interesting how bones appear as thin lines. I thought they appeared as pyramid-like structures with a tip.

**Comment by jeronimo-schreyer** [comment]
That is because I changed the 3D Gizmo Editor Settings. You can also change how they look if you change
editors/3d_gizmos/gizmo_settings/bone_shape (its the option at the end of the list)

**Comment by jeronimo-schreyer** [comment]
Done
added support for editor settings

https://user-images.githubusercontent.com/29764541/236708355-f86d5e22-2bf3-4a00-a085-6769a44f4793.mp4

**Comment by TokageItLab** [comment]
We have discussed this with @lyuma, the main problem is that there is a lot of duplication of code from the SkeletonGizmo.

To begin with, PostImportScene can't display Node3DGizmo. This leads to another usability issue where you select a tree item on the left tree and don't know what it indicates.

It may be necessary to start by making it possible to partially reuse Node3DEditor's Gizmo in PostImportScene.

**Comment by jeronimo-schreyer** [comment]
I see. I dunno how well we can componentize SkeletonGizmo::redraw function for this and even though we did, these two implementations are not exactly the same (even though they use similar mesh creation and shader code)

**Comment by jeronimo-schreyer** [comment]
PR https://github.com/godotengine/godot/pull/76818 has now a static function in Skeleton3DGizmoPlugin that generates the mesh and that is consumed both by itself (as a gizmo) and by the AIS dialog
