### ISSUE TITLE
Add a `get_item_rect()` method to ItemList

### ISSUE THREAD

**Issue by kolunmi** [godotengine/godot-proposals#6823]
### Describe the project you are working on

A 3d platformer.

### Describe the problem or limitation you are having in your project

Hello! I would like to add a tweened cursor and various other effects that are aware of the currently focused item's region to my menu.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a  `get_item_rect` method to the ItemList node, providing the information necessary to accurately place the cursor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
cursor.position = item_list.get_item_rect(0).position
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe this enhancement will be very useful in a variety of situations. As far as I know, a gdscript implementation would be ugly, complex, and unreliable, having to read many theme properties.

### Is there a reason why this should be core and not an add-on in the asset library?

This feature is fairly low-level. Thank you!

**Comment by AThousandShips** [comment]
This should be relatively straightforward to implement, as the data is already cached, will take a look at an implementation

**Comment by AThousandShips** [comment]
Opened a PR for this
