### ISSUE TITLE
Allow Window not to grab all input

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#6827]
### Describe the project you are working on

// a better proposal name is wanted imo

A plugin implemented in AcceptDialog node

### Describe the problem or limitation you are having in your project

I make something like CommandPalette in godot 4.
The problem is when the AcceptDialog with my plugin is poped up, I can't do anything else in the editor, like adding new nodes to scenes etc.
This is an inconvenient limitation, So for now I have to get rid of floating window idea and add my plugin to docks

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

An option to not interrupt input from other controls would solve the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Something like this (Cockos Reaper's Action list, similar to Godot Command Palette):

https://user-images.githubusercontent.com/16458555/236702267-ed44aaca-cd09-49fd-8d49-18ffb3808355.mp4

As you can see here, the window is opened, but it still allows to work with the project.

I want this behavior to be present in Window nodes.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This is core

**Comment by Miskler** [comment]
It would be good if this behavior could be determined when creating a window, since sometimes the old version of interaction with an additional window is also needed.

**Comment by KoBeWi** [comment]
AFAIK you just need to disable `exclusive` flag in Window.

**Comment by me2beats** [comment]
The main problem was that I mostly tried AcceptDialog, but it seems I should use Window instead, at least it works well
