### ISSUE TITLE
Small improvement for artists to visual scripting ( VERY small ) . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#683]
**Describe the project you are working on:**
I was working on some games, but now I'm joining a game jam, tomorrow, and will make a game about the theme . . I am currently working on a Tomb Raider and, an RTS <3

**Describe the problem or limitation you are having in your project:**
Well, it's not really a problem, but as an artist minded visual scripter, I would really appreciate it, if one could make the boxes look like bubbles, a little bit, not very much <3

![2020-04-09 1121](https://user-images.githubusercontent.com/61069740/78879914-deade000-7a54-11ea-8978-101d45807159.jpg)

Not this much, but so it looks like in the above images, like friendly ' thoughts ', in a way <3

![2020-04-09 1122](https://user-images.githubusercontent.com/61069740/78879595-62b39800-7a54-11ea-8461-a559f9378f9b.png)
Not THIS bubbly, just a little rounded, first picture . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I find coding very terrifying, but I am slowly learning the engine through visual scripting, and I plan to move over to real coding, when I can, it's my goal . . . Until then, this could make the Visual scripting experience a little more friendly to artist-minded people, and new people in the engine, or so . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Sort of like above, where the boxes look like this, some-thing friendly, ' nice ' <3
![2020-04-09 1121](https://user-images.githubusercontent.com/61069740/78879780-aad2ba80-7a54-11ea-8f3a-c993df50587e.jpg)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
As a beginner this is beyond me, maybe if there was an option, to switch between the two, so there was a ' more rounded ', a ' little ' rounded and, ordinary square ones, to help people, beginners .. 

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't think it could be done there, don't know . . .

<3

**Comment by jasperbrooks79** [comment]
Maybe shaped a bit like this, where it curves a bit down, so it's not just round, or three options, round corners, ' and a bit ' bent ' corners <3

![2020-04-09 1126](https://user-images.githubusercontent.com/61069740/78880069-1ae14080-7a55-11ea-975c-ef240317657f.png)

Like connecting speech bubbles or, thinking bubbles, in the engine . . . <3 <3

**Comment by Calinou** [comment]
I have a WIP pull request that redesigns the Godot editor theme. Rounded corners are part of the PR in question.

**Comment by jasperbrooks79** [comment]
I hope you can do it, coding feels so scary, I gave up on Unity after 6 - 9 months, took that long to make controller, with move up down, rotate . . . After less than 1 month in Godot, I have a game with characters, simple enemies, cameras, cut-scenes, things that react to player and, so on . .

Visual script is REALLY nice, for beginners, and bigger engines tend to think of super-users first, I hope Godot will make the BEST visual script experience, but also make it super-awesome, as Vulkan, other stuff . . . Also, one more idea, in visual script, one can set ' grid ' size to 12, from 20, or 14, but it doesn't ' remember ' the value, and it has to be reset every time, which there was a button, so it could be set, really for a long time, also, in new scripts . . Other than that, Godot is SUPER-good, and I am going to first game jam in 6 - 7 hours, after only having Godot for 3 - 4 months, I will make Pacman but, with a snake that, eats apples and, berries <3

**Comment by jasperbrooks79** [comment]
I know Godot is in best hands, I can't really suggest big features, not smart enough, but hope this can happen, as a noob, it would make the difference, between good and, awe-some . .

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
