### ISSUE TITLE
Add `get_current_code_completion_results()` method to `ScriptEditor`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#6839]
### Describe the project you are working on

I make code completion plugin, the control that will replace the default code completion list/control, and add some extra features
![](https://cdn.discordapp.com/attachments/923724757390737458/1105315310753566820/image.png)
(this is the screen of default code completion "control")

### Describe the problem or limitation you are having in your project

The main thing I miss is getting current ScriptEditor code completion results

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding `get_current_code_completion_results()` method to `ScriptEditor` would solve problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`get_current_code_completion_results()` method should return all code completion results for current code editor state - depending on caret position that is give the same results we can see then press Crtl+Space.
It could return Dictionary or an array, methods, properties, classes, signals, keywords, other

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it can't

### Is there a reason why this should be core and not an add-on in the asset library?

can't be an add-on

**Comment by dalexeev** [comment]
See [CodeEdit.get_code_completion_option](https://docs.godotengine.org/en/stable/classes/class_codeedit.html#class-codeedit-method-get-code-completion-option) and [CodeEdit.get_code_completion_options](https://docs.godotengine.org/en/stable/classes/class_codeedit.html#class-codeedit-method-get-code-completion-options).

**Comment by me2beats** [comment]
thanks I didn't find that methods before
however it requires a request for openining the code completion "control".
So I request_code_completion() then get_code_completion_options() then cancel_code_completion()

```
	var script_editor: = get_editor_interface().get_script_editor()
	var code_edit:CodeEdit = script_editor.get_current_editor().get_base_editor()
	code_edit.request_code_completion()
	print(code_edit.get_code_completion_options())
	code_edit.cancel_code_completion()
```
Ideally I would like to be able to get options without request_code_completion()
