### ISSUE TITLE
Godot compiling (For android)

### ISSUE THREAD

**Issue by Ezyreme** [godotengine/godot-proposals#684]
Exporting to android is simple but the problem is that the starting size is 17 mb. I know that the solution is to disable modules that are useless in your game example of it is 3D module when your game is 2d.

Now, compiling externally take a lot of time, many programs to download and difficult for those who only know godot and nothing else.  So, It would be better if the modules are visible in the project settings and free to tweek the settings. This could help alot.

**Comment by groud** [comment]
Please fill in the issue template, it is mandatory. I will reopen when this is done.
