### ISSUE TITLE
Add a TileSet property to randomize tile animation frame offset

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot-proposals#6856]
![68747470733a2f2f692e706f7374696d672e63632f6e56345a374347502f416e696d6174696f6e2e676966](https://github.com/godotengine/godot-proposals/assets/962340/99e2ea62-2db5-4692-8c93-4dab776c8154)

how it looks: uniform, bland, homogeneous

![68747470733a2f2f692e706f7374696d672e63632f393059686a6e66682f5368616465722e676966](https://github.com/godotengine/godot-proposals/assets/962340/223a959e-8c7d-4a5c-bfab-0f89177ff6e4)

how i want it to look (please ignore blur): varied, random, heterogeneous

### Describe the project you are working on

tile map with animations
 - some animations need to be synced ( all on same frame at all times ) like water fore and back
 - some animations need to not be synced so there is some variety when placed, like fountains, torches, and banners
 

### Describe the problem or limitation you are having in your project

the Place Random Tile does not work for tile animations
- even though you are able to set probability for each tile in the animation
- and I expected it to work like this

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

if the Place Random Tile button worked for animations like it does for other groups of tiles it would allow placing of both synced and un-synced animations

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The ui exists already but has no effect, i guess because only the first tile of the animation can be selected? It could either allow selection of more then the first tile or just fake a selection of whole animation in code

### If this enhancement will not be used often, can it be worked around with a few lines of script?

i am sure it will be used often, the button prob already is, and the workaround cumbersome

### Is there a reason why this should be core and not an add-on in the asset library?

it is already in ui?

https://github.com/godotengine/godot/issues/57677

**Comment by rakkarage** [comment]
Excuse my ignorance and assumptions... 
I was naively hoping to just change animation to act like a group of cells just to test.
From what I recently came to understand both call pick_random_tile where they pick a tile from a pattern generated from selection which is just one tile for animation and group of tiles for other.
It was at this point I realized that a tile can be both an animation and a member of a group and that the _**Place Random Tile button can be used to place a random animation from selection too**_.
So that option will not work but this feature would still be nice right? No one else wants this? U all like all animations being synced all the time?

So it seems like a fix would need to be in the animation properties itself maybe? like a "Synced" checkbox above the list of frames?

I am gonna explore this direction I guess...

Thanks.

**Comment by Proggle** [comment]
It looks like the value of p_random_animation_offset is limited to a delay of 0 to 1 seconds. This works fine to desync faster and shorter animations, but for longer or slower ones you end up with them being partially synced instead of totally random (worst case is animations that are 1 second+ per frame).

Pull request for the easiest way to fix this, which is just to make it randomize from 0 to 1 days instead, that's definitely long enough that nobody's going to notice that.

https://github.com/godotengine/godot/pull/82227
