### ISSUE TITLE
Add current_frame/pause/oneshot getter setter for AnimatedTexture?

### ISSUE THREAD

**Issue by JiRuifanCR** [godotengine/godot-proposals#686]
**Describe the project you are working on:**
I'm working on a project where I need a dynamic, changing light mask. The level has two layers, I need a somewhat cool swapping effect where the visible part of the first layer becomes smaller and smaller until we can only see the second layer, and then the light mask dilates again, making the first layer again visible. I used a Light2D with an AnimatedTexture for this task.

**Describe the problem or limitation you are having in your project:**
I need to run some other code exactly when the light mask shrinks to a dot, in the middle of the animation. I cannot adjust the size of the Light2D directly because the area outside the light mask is not affected, and leaves a quite ugly rectangular... area.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If getters and setters of the current_frame property is exposed, it would be possible to animate the entire thing from a AnimationPlayer, making the timing a lot easier. We can even play animation from a AnimatedTexture backwards. Adding oneshot to AnimatedTexture would also make the control much, much easier.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
$Light2D.texture.current_frame = 5
$Light2D.texture.oneshot = true

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The oneshot one can be done by disabling the texture exactly when it finishes, but I don't see anyway around the current_frame setter getter, if we for some reason want to skip frames randomly.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it's much easier to implement it inside the AnimatedTexture, in my custom build I did it within a few lines of code. It might mean that we need to duplicate the resource a few times to play it separately but we already did a similar thing for fonts. 

Maybe misunderstood something about the engine structure, or the right way to handle this, please let me know. I'm willing to do a PR for this.
![image](https://user-images.githubusercontent.com/37972124/78896535-3115ed80-7aa3-11ea-8ddb-02a8f46c030a.png)

This is what it looks like after I exposed the current_frame property. (And yes I know the setter need to use visual server a little bit).

**Comment by akien-mga** [comment]
Fixed by godotengine/godot#38287.
