### ISSUE TITLE
Higher-resolution Godot icon when switching between programs with alt+tab (Linux)

### ISSUE THREAD

**Issue by vrbandwagon** [godotengine/godot-proposals#687]
**Describe the project you are working on:**
2D platformer
**Describe the problem or limitation you are having in your project:**
No problem, it just looks unprofessional
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Please add a higher-resolution Godot icon for when we switch between programs in Linux. This might be due to the fact that Linux picks the taskbar icon and stretches it instead of choosing an "alt+tab icon".
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
<a href="https://imgur.com/ENWJAxD"><img src="https://i.imgur.com/ENWJAxD.jpg" title="source: imgur.com" /></a>
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
This does not apply.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/20469.

**Comment by Leleat** [comment]
I am on GNOME 3.34 (Fedora 31) and don't have that issue either.

**Comment by Calinou** [comment]
I'll close this in favor of https://github.com/godotengine/godot/issues/20469 as this is more of a bug report than a feature request.
