### ISSUE TITLE
Allow to set the image format of Noise get_image/get_seamless_image for higher precision

### ISSUE THREAD

**Issue by MackyK** [godotengine/godot-proposals#6872]
### Describe the project you are working on

Open world game with procedural terrain.

### Describe the problem or limitation you are having in your project

When getting the image from a noise it doesn't allow you to set the Format. I want to be able to set it to higher precision (FORMAT_RF). The default format doesn't allow enough precision. The terrain is not smooth enough, has to much jitter.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add format argument to the get_image/get_seamless_image function to set the format of the created image.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

n/a

### If this enhancement will not be used often, can it be worked around with a few lines of script?

n/a

### Is there a reason why this should be core and not an add-on in the asset library?

n/a

**Comment by Calinou** [comment]
> The terrain is not smooth enough, has to much jitter.

Out of curiosity, why do you need an image to generate terrain? Can't you sample values directly from the noise?

**Comment by MackyK** [comment]
Yes this is for 3d.

- Better static storage (Subjective Opinion)
- Exporting of heightmaps for editing/tweaking
- Easier to enumerate over (conversion to HeightMapShape3D, Mesh)

**Comment by MackyK** [comment]
Better solution was found.

**Comment by Calinou** [comment]
@MackyK Please document this solution here by commenting :slightly_smiling_face:

**Comment by MackyK** [comment]
I'm using this to generate a heightmap. The maps width and height are same. If you need to have differing width and height you will need to tweak the code to fit your use case.

The following code creates a float 32 precision heightmap. Allows image export to format `Image.FORMAT_RF` which is float 32 red channel only

```
# Size represents the width and height image. The number is odd to account for the vertices.
# The map size is 128 which makes the vertices size 128+1

var noise : FastNoiseLite = FastNoiseLite.new()
var size : int = 129

func generate_noisemap(normalize : bool = true) -> PackedFloat32Array:
    var data : PackedFloat32Array = []
    data.resize(size * size)

    for y in range(0, size, 1):
        for x in range(0, size, 1):
            if normalize:
                data[x + y * size] = noise.get_noise_2d(x, y) * 0.5 + 0.5
            else:
                data[x + y * size] = noise.get_noise_2d(x, y)
    return data

func generate_image(data: PackedFloat32Array) -> Image:
    return Image.create_from_data(size, size, false, Image.FORMAT_RF, data.to_byte_array())

```

Here is a sample project with the above code working: 
[Heightmap32Precision.zip](https://github.com/godotengine/godot-proposals/files/11472461/Heightmap32Precision.zip)
