### ISSUE TITLE
Add a Cursor node

### ISSUE THREAD

**Issue by vPumpking** [godotengine/godot-proposals#6874]
### Describe the project you are working on

I'm working on a game that contains a mouse cursor, and that will be able to work on both PlayStation and PC. To do so, I have to create a mouse that can be used with both the PC's mouse and the Playstation's Joypad.

### Describe the problem or limitation you are having in your project

The native UI elements of Godot only reacts to the OS' mouse. As PlayStation OS doesn't have one, I'm forced to recreate by myself all UI nodes, like buttons or combo boxes, to work with the emulated mouse. It's long, hard and certainly not convenient.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a Cursor node that has at least a position property (Vector2) on the screen, a LeftClick signal and a RightClick signal. This node has to be considered as a native OS mouse cursor by the UI nodes, so as to the Cursor can interact with them.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![Capture d’écran du 2023-05-13 11-25-53](https://github.com/godotengine/godot-proposals/assets/121762735/40ad8873-f953-4835-8ce5-ea9580827a14)

The user can use this in any scene, and can made easily a mouse by:
* 1 - Adding a sprite node (for the cursor's image¹)
* 2 - Attaching a script to add motion (e.g.: moving alongside a joystick)

¹ The Cursor node doesn't provides any display to enable the user to do low-level things

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm sure it will be used often, and in the other case it's very long and inconvenient to recreate UI elements

### Is there a reason why this should be core and not an add-on in the asset library?

It requires an access to Control class code

**Comment by dalexeev** [comment]
Related:

* #5300
* #74
* #1894

**Comment by Calinou** [comment]
Mouse-driven UI with a controller is generally considered an antipattern nowadays. Instead, set focus neighbors to provide controller-driven UI navigation using the left stick and D-pad.

**Comment by vPumpking** [comment]
Yes but my game is a computer dimulation so I really need it and I seen that other ones are in the same case

**Comment by golddotasksquestions** [comment]
@vPumpking 

> I have to create a mouse that can be used with both the PC's mouse and the Playstation's Joypad.

You don't need a Cursor node for this. All you need is a Sprite node and this minimal bit of code:

```swift
extends Sprite2D

@export var cursor_speed = 10

func _process(delta):
	position += Input.get_vector("ui_left", "ui_right","ui_up", "ui_down") * cursor_speed
```

**Comment by Zireael07** [comment]
@golddotasksquestions Input.get_vector() is known to have issues when using both analog and joystick inputs

**Comment by AThousandShips** [comment]
While this is true it doesn't make sense to solve work around that issue by adding a new feature

**Comment by AThousandShips** [comment]
> But all I want is a thing that can be detected as a mouse by the GUI elements

You can do that with [Input.parse_input_event()](https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-parse-input-event), sending mouse events, don't think this is a big enough use case to warrant adding a feature to the engine

**Comment by vPumpking** [comment]
Thanks! You prevented me to spend hours on an inexistant problem.

**Comment by vPumpking** [comment]
Can we consider closing this issue?

**Comment by stephanbogner** [comment]
@AThousandShips **Thanks for the cursor example** ❤️ 
This is super helpful for games like _Ace Attorney_, _Return of the Golden Idol_ or _Where's Waldo / Wally_ where a cursor is basically unavoidable.

I am posting the basic principle so it's less hidden than in the zip-file (and this issue is easy to find via Google):
```
var new_event := InputEventMouseButton.new()
new_event.device = -1
new_event.position = cursor_position
new_event.button_index = MOUSE_BUTTON_LEFT
new_event.pressed = true
Input.parse_input_event(new_event)
```
