### ISSUE TITLE
Add code editor shortcut to delete a whole line

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot-proposals#6875]
### Describe the project you are working on

Programming a game (aka. using Godots inbuilt code editor)

### Describe the problem or limitation you are having in your project

When I want to delete a whole line I have to mark it and then delete it. This can be done fast -ish with the keyboard, but a shortcut that would make it even faster.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a shortcut (for example Alt + X) that deletes the lines(s) that are currently edited in the code editor. Make this work with the multi edit feature, it should the delete every line you are currently editing.

This shortcut would make deleting (a) line(s) faster and easier.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the shortcut is pressed, the currently edited line(s) should be delete and the lines after the delete one(s) should be move up so that there are no empty lines produced by this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't be worked around with a few lines of script. It can however be worked around by marking the line and then deleting it.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a Godot editor feature.

**Comment by Cykyrios** [comment]
I believe Ctrl+Shift+K is what you're looking for. You can look for "delete line" in the shortcuts list.

**Comment by xxSeys1** [comment]
Thanks, yes that is what I was looking for. I must have overseen it when searching for such a functionality, my bad.

**Comment by Calinou** [comment]
You can also press <kbd>Ctrl + X</kbd> without any selection to cut the current line, which has the effect of removing it.
