### ISSUE TITLE
Add a IsTimerActive signal for timer nodes

### ISSUE THREAD

**Issue by User-385** [godotengine/godot-proposals#6876]
### Describe the project you are working on

Working on a game that uses timer nodes.

### Describe the problem or limitation you are having in your project

Would like to limit the use of the _process function (which runs every frame) every time a user wants to check if a timer is active or not.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a signal called IsTimerActive under the node tab for a timer node (inside the inspector) below the timeout signal.

This signal allows users to check whether a timer is currently active and running or not.
the signal function returns true if the timer is active and running, or false otherwise.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This signal will be available inside the Node tab when clicking on timer nodes (below the timeout signal)

when connected via the inspector the following function will be created
func _TimerNodeName_IsTimerActive(Active):
# Do Things
pass

When connecting via script the user will use the following:
TimerNode.connect("IsTimerActive", _TimerNodeName_Active) 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This signal is convenient and can produce a faster running code.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about not having to necessarily use the _process function (which runs every frame) every time a user wants to check if a timer is active and running or not.

**Comment by Zireael07** [comment]
Signals are performance intensive so absolutely NOT an option for something that runs multiple times a second.

Use _process() instead, or just check for time_left of the timer

**Comment by User-385** [comment]
@Zireael07 Thank you for the response.
