### ISSUE TITLE
Godot cannot be pinned to the taskbar (Linux Mint)

### ISSUE THREAD

**Issue by vrbandwagon** [godotengine/godot-proposals#688]
**Describe the project you are working on:**
2D Platformer
**Describe the problem or limitation you are having in your project:**
No limitation, just really annoying.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Even when installed from the Software Manager, the option to pin Godot to the taskbar isnt' there. Please add this. Also, I am aware there is a workaround for this, but when I do this, there are TWO Godot icons now (one to launch Godot, and one that is the actual program.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
[https://imgur.com/a/Ly8IsHG](https://imgur.com/a/Ly8IsHG)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
This does not apply.

**Comment by Calinou** [comment]
> Even when installed from the Software Manager

I assume this is the Snap distribution?

The Snap distribution isn't officially supported by the Godot developers (see https://github.com/godotengine/godot/issues/18266). Anyway, this is more of a bug report than a feature proposal, so I'll close this.
