### ISSUE TITLE
Godot 4: Ability to toggle collision selectively for a TileMap layer

### ISSUE THREAD

**Issue by ChainedLupine** [godotengine/godot-proposals#6881]
### Describe the project you are working on

I am writing a TileMap-based game in Godot and have been converting it from Godot 3 to 4.  In my game, I rely upon fading/transition layers in TileMaps to improve immersion in my game.  Imagine:  Moving into a cave, which the interior is invisible until you actually enter it, because the interior is covered with another TileMap, or a secret area is covered until the player walks into it.

I also re-use TileSets for both background and foreground tilemap layers.

### Describe the problem or limitation you are having in your project

In Godot 3, since a TileMap == one tile layer, this was easy to do, at the cost of having many individual TileMaps.  In 4, we now have Layers and that allows us to combine multitudes of TileMaps into one.  This is nice from both an implementation stand point but also speeds up TileMap rendering since it can more intelligently cache structures.

However, the idea of TileSet collisions have changed.  Instead of being a property per-TileMap, it is now data attached to the TileSet and this data is re-used across TileMap layers.  Again, this is a good idea and I approve of this change, but it no longer allows me to use TileMaps with collision selectively disabled.  The collision status (mask, layer, etc) is now tied to the TileSet.

I am no longer able to easily disable a layer's collision for a secret/transition zone, nor am I able to re-use a TileSet for a background element (as it will always have collision enabled).

I can work around this by duplicating TileSets and disabling collision polygons, but this is tedious and doesn't allow for TileSet re-use, re: background layers.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To TileSet, add a new per-layer property called "collision enabled" which lets you selectively turn off collisions.  Defaults to "true."

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a getter/setter to TileMap that mirrors the enabled flag for layers, called set_layer_collision_enabled/is_layer_collision_enabled.

In TileMap::_update_dirty_quadrants(), add logic to skip _physics_update_dirty_quadrants when this flag is enabled.  Also, skip _navigation_update_dirty_quadrants() as usually navigation is tied to collision.

TODO: Determine if navigation needs its own enable/disable flag.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There are no script interface which allows selectively disabling collisions per TileMap layer.

You can turn off collision for a TileSet -- but this will effect all TileMaps and all TileMap layers.

### Is there a reason why this should be core and not an add-on in the asset library?

Same as above, inability to do this via GDscript interface.

**Comment by ChainedLupine** [comment]
Already have code to implement this feature.  Will add it as a MR later.

**Comment by KoBeWi** [comment]
You can disable collisions for whole layers or specific tiles using `_tile_data_runtime_update()`.
```GDScript
extends TileMap

func _use_tile_data_runtime_update(layer: int, coords: Vector2i) -> bool:
	return layer in secret_layer_ids

func _tile_data_runtime_update(layer: int, coords: Vector2i, tile_data: TileData) -> void:
	tile_data.set_collision_polygons_count(0, 0)
```

**Comment by ChainedLupine** [comment]
@KoBeWi I wonder if the API changed?  I looked for such functionality in the TileMap/TileSet class but didn't see it.  Maybe it just didn't make it into the documentation until now.  (Using 4.1-dev2.)

I've tried it out and that seems to work.  So if I can modify a TileSet data at runtime, without interrupting other TileMaps that rely upon that data -- That solves this issue.  

Thanks!
