### ISSUE TITLE
Add a function to convert physical_keycode to key_label

### ISSUE THREAD

**Issue by Lielay9** [godotengine/godot-proposals#6888]
### Describe the project you are working on

Input remapping and key/button prompts.

### Describe the problem or limitation you are having in your project

It is not possible to provide accurate key prompts for players using non US QWERTY layout. This hampers the experience of many first time and returning players that now need to create a mental map of how the prompts translate to their keyboard.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A dedicated function to convert physical_keycode to key_label would allow displaying prompts that better match the keyboard of the player.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a function similar to the recently added `DisplayServer.keyboard_get_keycode_from_physical(keycode)`:
```gdscript
DisplayServer.keyboard_get_key_label_from_physical(keycode)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The physical and key-label pairs can be saved whenever the player presses a new key or when they change the default keys for the action but not before it.

### Is there a reason why this should be core and not an add-on in the asset library?

Discoverability and ensuring matching behavior with `InputEventKey.key_label` (when possible)

**Comment by Calinou** [comment]
Should key names be displayed in English or in the user's language? It seems a lot of games on Windows use the keyboard layout's language. This means that if you use English with a French AZERTY keyboard layout, key names will appear in French. I've seen "Press Entrée to start" in Control for instance :slightly_smiling_face:

**Comment by Lielay9** [comment]
> Should key names be displayed in English or in the user's language? It seems a lot of games on Windows use the keyboard layout's language. This means that if you use an English OS with a French AZERTY keyboard layout, key names will appear in French. I've seen "Press Entrée to start" in Control for instance

As there's no unicode for "french Enter" this could be quite cumbersome. Getting the correct codepoint would be a good start. Those wanting to go the extra mile can translate the result to the language at hand.

**Comment by Arecher** [comment]
For those that stumble upon this in the future, in Godot 3.x this can be solved by using [OS.keyboard_get_scancode_from_physical()](https://docs.godotengine.org/en/3.5/classes/class_os.html#class-os-method-keyboard-get-scancode-from-physical).

This allows you to take any Physical scancode, which you can get from [InputEventKey.physical_scancode](https://docs.godotengine.org/en/3.5/classes/class_inputeventkey.html#class-inputeventkey-property-physical-scancode) and transform it into the scancode for the actual key on the keyboard. You can then easily transform that one into a key_label using [OS.get_scancode_string()](https://docs.godotengine.org/en/3.5/classes/class_os.html#class-os-method-get-scancode-string).

I don't believe this with localize keys (Enter -> Entrée), but it will at least allow you to show the accurate key for the users keyboard in keybinding menus.
