### ISSUE TITLE
Add a way to set a user layout as default

### ISSUE THREAD

**Issue by vrbandwagon** [godotengine/godot-proposals#689]
**Describe the project you are working on:**
2D Platformer

**Describe the problem or limitation you are having in your project:**
No limitation, just for Godot's perpetual improvement.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Please add a way to set a user layout as default layout. For example, when the default layout changed from 3.0 to 3.1, those who preferred the old layout had to rearrange the layout, save it, and select it every time they opened a new project. I think you could add a "Set as default for layout", mimicking the great option you added on the Import tab.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Mockup](https://i.imgur.com/CNp8L44.jpg)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not applicable.

**Comment by Calinou** [comment]
For those stumbling upon this issue, you can do this by saving a new layout whose name is "Default" (case-sensitive).
