### ISSUE TITLE
Easier way to accept input event

### ISSUE THREAD

**Issue by feois** [godotengine/godot-proposals#6903]
### Describe the project you are working on

Irrelevant

### Describe the problem or limitation you are having in your project

When coding `Node._input()` and other similar functions (e.g. `Node._unhandled_input()`, `Control._gui_input()`, etc.), you have to use `Viewport.set_input_as_handled()` or `Control.accept_event()` to consume the input event, which is quite tedious imho.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Change the function signature to return `bool`, if `true`, treat the input event as handled.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
func _input(event: InputEvent) -> bool:
    if event.is_action_pressed(&"foo"):
        foo()
        return true # consume the input event
    elif event.is_action_pressed(&"bar"):
        bar() # don't consume the input event
    else:
        baz() # don't consume the input event
    
    return false
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but it's tedious imho.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about core nodes' virtual functions

**Comment by AThousandShips** [comment]
This makes it so you are forced to either only signal that events are accepted from the function, or make any other function that is called from this that might singal this also return a `bool` and handle that value

**Comment by feois** [comment]
> This makes it so you are forced to either only signal that events are accepted from the function, or make any other function that is called from this that might signal this also return a `bool` and handle that value

I don't get what you mean, but if there is technical limit, I'll close this issue.

**Comment by AThousandShips** [comment]
If you want for example the function `foo` to accept input you can't do this in your proposed solution *unless* you also make that function return a `bool`, you're restricting handling event accepting to the `_input`, `_gui_input`, etc. functions

**Comment by feois** [comment]
Good point, well I just thought it's tedious to write `get_viewport().set_input_as_handled()` multiple times.
On the other side, I wonder why is `accept_event()` limited to `Control` only.

**Comment by AThousandShips** [comment]
> I wonder why is accept_event() limited to Control only.

Because it's GUI specific
