### ISSUE TITLE
Add the ability to get the dimensions of a Label3D

### ISSUE THREAD

**Issue by VANN-Universal** [godotengine/godot-proposals#6905]
### Describe the project you are working on

A presentation tool mainly consisting of 3D elements.

### Describe the problem or limitation you are having in your project

I want to create a responsive layout with mixed 2D and 3D elements. Therefore, I need to adapt the size of a mesh to the size of a `Label3D` with autowrap on. Currently, there is no way to get the size of a `Label3D`, so I have no way to adapt anything to it's size dynamically (for example when the user changes the text or font size).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A function to get the size of a `Label3D` would allow me to create responsive layouts around text in 3D.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# example for a vertical layout with a Label3D at the top and a MeshInstance at the bottom
# getting the size
var my_label = $Label3D
var label_size = my_label.size()

# adapting some other elements
my_box.scale.y = total_height - label_size.y
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I did not find a simple workaround, since there is also no way to get the line count with autowrap. If that were possible, the dimensions could be estimated by multiplying the line count with the font size.

### Is there a reason why this should be core and not an add-on in the asset library?

It makes no sense to use an add-on to add one function to a built-in class.

**Comment by AThousandShips** [comment]
Have you tried accessing the AABB?

**Comment by VANN-Universal** [comment]
No, I've never heard of the AABB before. Accessing it solves my problem, thanks!

**Comment by AThousandShips** [comment]
I'm happy it works!

**Comment by Calinou** [comment]
For reference, this is done in the 3D labels and texts demo: https://github.com/godotengine/godot-demo-projects/blob/master/3d/labels_and_texts/label_3d_layout.gd
