### ISSUE TITLE
Add a button to copy a code block in the editor help

### ISSUE THREAD

**Issue by SparkT06** [godotengine/godot-proposals#6922]
The integration of a "Copy Code" button in documentation marks a significant step forward in enhancing the user experience for developers. 

### Describe the problem or limitation you are having in your project

documentation serves as a crucial resource for developers, guiding them through the intricacies of code implementation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It becomes essential to constantly refine and enhance the documentation experience. One such improvement is the inclusion of a "Copy Code" button, a feature that adds significant value and enriches the overall feel of documentation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Current:
<img width="320" alt="image" src="https://github.com/godotengine/godot-proposals/assets/118836956/dd7c24ff-ca08-4ad9-8bb6-616b4047426f">

Implement:
<img width="165" alt="image" src="https://github.com/godotengine/godot-proposals/assets/118836956/5b59d270-24b1-4ed2-bc7b-eee78928aa47">

### If this enhancement will not be used often, can it be worked around with a few lines of script?

NA

### Is there a reason why this should be core and not an add-on in the asset library?

It should be built in Godot engine

**Comment by Zireael07** [comment]
You can already select and copy with your mouse.

**Comment by SparkT06** [comment]
Online documentation already have the copy options.
<img width="874" alt="image" src="https://github.com/godotengine/godot-proposals/assets/118836956/2b115e18-5258-431b-a4dd-11ab080245d1">

Inside engine documentation didn't have the option, I'm suggesting it because enriches the overall feel of documentation.

**Comment by coppolaemilio** [comment]
I think this is expected of most documentations nowadays. It wouldn't hurt to add a copy button on snippets 👍

**Comment by Zireael07** [comment]
@SparkT06 Ah, I totally missed that button online. In this case, yes, it's worth it to have the same in the offline docs

**Comment by Calinou** [comment]
Regarding how to implement this, this should be done by creating a "button" within the RichTextLabel using an `[url]` tag that points to a custom URL. This URL should be handled in `_meta_clicked` and should copy the code block located below. Needless to say, this is nontrivial to implement efficiently.

**Comment by HolonProduction** [comment]
This was implemented in godotengine/godot#87363 for 4.3
