### ISSUE TITLE
Display Autoloads in the inspector node selection window

### ISSUE THREAD

**Issue by thornySoap** [godotengine/godot-proposals#6927]
### Describe the project you are working on

A simple beginner Flappy Bird fake with an `SettingsHandler`-Singleton of type `ResourceHandler` autoloaded. I want to add a settings screen, for which I use a `ResourceElement`-UI element. `ResourceElement` has a variable of the type `ResourceHandler` exported.

### Describe the problem or limitation you are having in your project

I want to assign the Autoload to the settings-`ResourceElement`. But for this simple thing I need to create an extra script for it which seems weird to me:

```gdscript
extends ResourceElement

func _ready() -> void:
    resource_handler = SettingsHandler
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since Autoloads are always "there" no matter if running the main or any other scene alone, they could be shown in the "Select a node" popout in the inspector:
![Screenshot 2023-05-21 17:00:55](https://github.com/godotengine/godot-proposals/assets/115401023/a1ef5233-0be8-41f9-b711-b6faecb426e8)
__

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The Autoloads could be shown above the root node.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by theraot** [comment]
Related: https://github.com/godotengine/godot-proposals/issues/4993

**Comment by thornySoap** [comment]
> Related: #4993

Thanks, if this gets implemented my issue would be fixed as well
