### ISSUE TITLE
Printing node should contain its name

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#693]
**Describe the project you are working on:**
A game.

**Describe the problem or limitation you are having in your project:**
Sometimes it happens that I have to print a node to see if a proper node is where I want it. My problem is that `print(some_node)` doesn't give really useful information. It gives node type and... instance ID. I don't need the ID, I'd like the name. Most often I can't just do `print(some_node.name)` because `some_node` can be null too (safe navigation operator would help here actually...).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Doing `print` on node should display its type and name, not type and ID.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
We should either make `to_string` virtual and override it in node or add an `if` checking if the Object is a node. The latter is quite simple to do actually.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Printing nodes is rather frequent operation IMO.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's core thing.

**Comment by Calinou** [comment]
Could we also print a node's position if it extends from Node2D or Node3D? This may give some additional context. I'm not sure how far we should go to ease debugging.

**Comment by balenol** [comment]
Is there already an implementation for python __str__ in godot?

**Comment by Calinou** [comment]
@balenol Yes, you can override `_to_string()` in any script.
