### ISSUE TITLE
Add "Physics Material Override" option for generated bodies in the Advanced Import Settings dialog

### ISSUE THREAD

**Issue by EMBYRDEV** [godotengine/godot-proposals#6932]
### Describe the project you are working on

AA Indie first person shooter.

Thousands of environment assets.

### Describe the problem or limitation you are having in your project

Currently the "Physics Material Override" property is not exposed when importing a mesh file.

Physics Body type, size and shape are all exposed and configurable so it makes sense to also expose the override.

Physics Material Override is used in-game not only to determine how the surface type responds but we use it to determine the surface type of a collider for footstep sounds, bullet hit particles, decals etc. Therefore every mesh in the game needs to be assigned the correct physics material. "Concrete, Metal, Water" etc.

This is an important feature for projects with many hundreds/thousands of assets since currently, the only way to make sure this field is populated correctly is to create a new inherited scene for every mesh in the game which adds up quickly, reducing productivity and polluting the filesystem.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

![image](https://github.com/godotengine/godot-proposals/assets/20043270/e167ac4d-0c49-48a3-8fc2-3ea20e918549)

My proposal is to add a new option to the Scene Importer's Physics section that will allow you to specify the material for a given body at the import level.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This should be relatively simple as the importer is already generating the physics body for us, it is just one additional propery we need to populate on the new Node.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This modifies an existing core component to add a small additional feature. It has wide ranging use cases and I believe is an important improvements to the core.

**Comment by aaronfranke** [comment]
While it does not completely replace this feature, I want to mention that we also want to add support for specifying the physics information inside of GLTF files, which would include importing physics shapes, bodies, materials, etc from Blender. This way you could set up your physics details before you even get to Godot.
