### ISSUE TITLE
Add import statements to GDScript

### ISSUE THREAD

**Issue by Blade67** [godotengine/godot-proposals#6939]
### Describe the project you are working on

Any project using GDScript

### Describe the problem or limitation you are having in your project

Currently, if you want to "import" functionality from other scripts, you have to preload it. However this approach feels very limiting, especially if there is just one or two functions or variables needed from a file. This proposal aims to mitigate that.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In the ideal case, we'd be able to use it like this:
```gdscript
import myFunction, myOtherFunction from "res://path/to/myFile.gd"

func _ready() -> void:
    myFunction()

func _process(delta) -> void:
    myOtherFunction(delta)
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I would propose the `import` keyword as syntactic sugar to replace the preload, and add additional functionality.
```gdscript
# Currently
const myFile = preload("res://path/to/myFile.gd")

# Proposal
import "res://path/to/myFile.gd" as myFile

# Additional functionality
import myFirstFunction, myVariable, mySecondFunction from "res://path/to/myFile.gd"
import myFirstFunction, myVariable, mySecondFunction from MyAutoloadSingleton

# Alternatives for the syntax
import { myFirstFunction, myVariable, mySecondFunction } from "res://path/to/myFile.gd"
import [ myFirstFunction, myVariable, mySecondFunction ] from "res://path/to/myFile.gd"
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can still use the preload syntax, but that would assume importing the whole file.

### Is there a reason why this should be core and not an add-on in the asset library?

Has to do with the GDScript syntax.

**Comment by YuriSizov** [comment]
> Currently, if you want to "import" functionality from other scripts, you have to preload it. However this approach feels very limiting, especially if there is just one or two functions or variables needed from a file. This proposal aims to mitigate that.

I don't understand in what way is this limiting. Scripts are classes, with a load or a preload you include the entire class and can then use whatever method you need. You just have to use a variable name to refer to the class before accessing the method, but in practical terms it still works the same and allows the same level of flexibility.

And your proposal would only work for static methods, because for others you still need to construct an instance, so you still need to import the entire class. What you may be interested in is a trait system: https://github.com/godotengine/godot-proposals/issues/6416.

**Comment by Blade67** [comment]
> Scripts are classes, with a load or a preload you include the entire class and can then use whatever method you need. You just have to use a variable name to refer to the class before accessing the method, but in practical terms it still works the same and allows the same level of flexibility.

It's mostly meant as syntactic sugar, making the use easier and more intuitive, especially if you come from a web background. Making functions refer to a file and call it there instead of copying content over into the "importing" file would also reduce project size, given there is less duplication. In a way, it's be similar to inheritance in nodes.

Again, syntactic sugar. It's just supposed to make it nicer to use. In the end, the performance implications would be minimal.

**Comment by Blade67** [comment]
Then I don't see any reason against this syntax. Sure, it is arguably redundant, but (at least from a web developer's perspective) considerably nicer to use.

**Comment by AThousandShips** [comment]
It *is* redundant, and involves adding a whole new feature, essentially just to fit a particular developer background?

**Comment by Blade67** [comment]
That's fair. I guess most people disagree with this proposal, so I'm going to close it!

**Comment by mkantorrr** [comment]
A scripting language without a way to import static functions or classes across files. Instead, You need to load the script file as a resource and instantiate it to use beforementioned contained static functions or classes. Fascinating.
