### ISSUE TITLE
Allow to click on AnimationPlayer timeline without moving animation

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#694]
**Describe the project you are working on:**
2D game with animations.

**Describe the problem or limitation you are having in your project:**
Quite often happens that I forget to move cursor on timeline before adjusting property. I.e. I add a keyframe then move object to desired position, but forget to move the cursor before that, so I need to click timeline, but it breaks my perfect position and I need to set it again.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There should be some way to click timeline without moving animation (i.e. updating nodes to the selected time). Could be done with some modifier key.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![NIXwcYScEg](https://user-images.githubusercontent.com/2223172/79019438-9edf1980-7b76-11ea-9057-5cc68eff983e.gif)
_Imagine the Sprite doesn't move back when I move the timeline cursor._

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not sure, but it would be more than few lines.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's about AnimationPlayer.

**Comment by Janders1800** [comment]
This is an expected behavior across all animation tools (blender, maya, etc), so I'm against changing it.

**Comment by KoBeWi** [comment]
But I'm asking to make this an option.
