### ISSUE TITLE
Ability to modulate a single tile within a tilemap

### ISSUE THREAD

**Issue by Modnark** [godotengine/godot-proposals#6947]
### Describe the project you are working on

I'm working on a 2D building game that has many different separate tiles, each of them are in grayscale so they can be modified later on.

### Describe the problem or limitation you are having in your project

I'm currently migrating from Unity and I'm used to being able to set the color of a tile at a specified position. Now, I could just solve this by drawing a semi-transparent white Sprite2D over each tile that's self modulated, but that's not great to work with and also seems unnecessary, it's something that would be great as part of the engine. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would enjoy having something like,, I feel like having something built right in would be greater for performance, and greater for working with code in general.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Something like `TileMap.set_tile_modulate(Vector2 Position, Color modulate)` would look nice, and feel natural with the other TileMap APIs that exist.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There are some ways to work around this, but they aren't pretty. One way is by placing a semi-transparent object above it, the other solution is creating 30 tiles where each tile is a different tile for every tile in my game. This is not efficient, but it's an alternative.

### Is there a reason why this should be core and not an add-on in the asset library?

This isn't something that can really be solved by a script or plugin as far as I'm aware. It's something best to be added to the engine.

**Comment by Calinou** [comment]
Consolidating as part of https://github.com/godotengine/godot-proposals/issues/3967, which proposes something similar.
