### ISSUE TITLE
Bring back bone custom poses

### ISSUE THREAD

**Issue by BR14Nx** [godotengine/godot-proposals#6950]
### Describe the project you are working on

Souls like game where character neck and back slightly bends into turning direction to have a more dynamic animation.

### Describe the problem or limitation you are having in your project

I am refering to my problem described [here](https://ask.godotengine.org/153469/set-a-custom-bone-pose-of-a-skeleton-in-godot-4-0). There is no more functionality to set a custom pose of a Skeleton3D even though the documentation says : "The overall transform of a bone with respect to the skeleton is determined by the following hierarchical order: rest pose, CUSTOM pose and pose."

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Possibility to set, get and delete a custom pose. The global pose override is not setting a custom pose, but instead overriding the normal pose which one might not want to change.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Refer to [Godot 3.0](https://docs.godotengine.org/de/stable/classes/class_skeleton.html?highlight=set_bone_custom_pose%20#class-skeleton-method-set-bone-custom-pose)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Global pose override is also setting a "different pose" but not a custom pose.

### Is there a reason why this should be core and not an add-on in the asset library?

Legacy support for 3.0 Skeleton code and easier to use then custom_pose_override

**Comment by Zireael07** [comment]
@TokageItLab In this case the docs need to be updated asap to not mislead users into thinking custom poses are posslble/supported

**Comment by TokageItLab** [comment]
@Zireael07 Ah, you are right, those are out of date and it is a problem. I will send you a PR later.
