### ISSUE TITLE
Replace nested paths by setting global objects ID

### ISSUE THREAD

**Issue by n-gram-hub** [godotengine/godot-proposals#6956]
### Describe the project you are working on

Any project is affected

### Describe the problem or limitation you are having in your project

Nested paths are not flexible.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since a little change in the code can potentially break your game, I suggest to have an ID field in the Godot GUI, that lets you directly and globally refer an object, without using its full path in the code.

This is not a proposal against nesting itself.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A simple fillable ID textfield in the object panel would let you directly refer to this object. 
Objects created in code could have an ID too.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I haven't seen code without multiple long paths, I suppose it can't be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?

It's clearly a core task.

**Comment by RedMser** [comment]
I might not understand correctly, but aren't you simply looking for [Scene Unique Nodes](https://docs.godotengine.org/en/stable/tutorials/scripting/scene_unique_nodes.html)?

**Comment by YuriSizov** [comment]
Indeed, this is an existing feature for the scene-scope. For global we don't have a way to register particular nodes uniquely, with one of the issues being that a scene containing it can be instantiated multiple times. But you can implement an autoload singleton which either _is_ your unique node or stores a references to that unique node.

**Comment by me2beats** [comment]
see also https://github.com/godotengine/godot-proposals/issues/5029

**Comment by n-gram-hub** [comment]
> I might not understand correctly, but aren't you simply looking for [Scene Unique Nodes](https://docs.godotengine.org/en/stable/tutorials/scripting/scene_unique_nodes.html)?

No, this is limited too. Maybe I'm looking for a smarter version of this: https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-find-child

**Comment by n-gram-hub** [comment]
> Indeed, this is an existing feature for the scene-scope. For global we don't have a way to register particular nodes uniquely, with one of the issues being that a scene containing it can be instantiated multiple times. But you can implement an autoload singleton which either _is_ your unique node or stores a references to that unique node.

I've not understood the latest sentence, could you elaborate a little?

**Comment by YuriSizov** [comment]
> I think this actually works by recursively accessing the subnodes. I'm suggesting a dictionary-like approach, instead: you access a flat, one-level representation of the tree, so that the first subnode can be always directly referenced, without loops.

Scene unique nodes are a flat hashmap, so it's exactly what you describe.

> I've not understood the latest sentence, could you elaborate a little?

While scene unique nodes are, well, _scene_ unique, you may want to have some unique nodes in the project as a whole. Which is where the autoloads feature comes in. You can read about it here and see if you can fit it to your needs: https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html.
