### ISSUE TITLE
Have the option to remove a project from the computer in the project list

### ISSUE THREAD

**Issue by vrbandwagon** [godotengine/godot-proposals#696]
**Describe the project you are working on:**
2D Platformer
**Describe the problem or limitation you are having in your project:**
No limitation, just annoying.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It is tedious for someone who works with a lot of projects to have to manually delete project folders every time they want to remove a project. Since Godot is so well integrated in other areas (you can create, rename and delete folders directly in Godot with the fileSystem), it would also make it consistent. I don't think there are many users who actually want to remove a project from the list while keeping it on their computer.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
<a href="https://imgur.com/9RGl6in"><img src="https://i.imgur.com/9RGl6in.jpg" title="source: imgur.com" /></a>
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
It doesn't apply.

**Comment by Calinou** [comment]
This is a dangerous option, so I think it should be as difficult as possible to accidentally perform it. Instead of adding another button, we could add a checkbox in the confirmation dialog to remove files.

**Comment by vrbandwagon** [comment]
I'm not sure how a person who initially chose to click on "Remove" when operating a computer might not understand that it means that their files will be removed...

Anyway, the checkbox is still better than no option at all. Hopefully if this is what the developers go for, the choice of the checkbox will be remembered next time as well.

**Comment by Jummit** [comment]
> I'm not sure how a person who initially chose to click on "Remove" when operating a computer might not understand that it means that their files will be removed...

I'd click on that all the time by accident.

**Comment by vrbandwagon** [comment]
> > I'm not sure how a person who initially chose to click on "Remove" when operating a computer might not understand that it means that their files will be removed...
> 
> I'd click on that all the time by accident, especially if it is in the bottom right corner and preselected.
That's why there is an additional dialog box that asks the user to confirm their action. We get the same when we delete a file or folder in fileSystem.

Honestly, I just cannot find any use case where the user would like to de-list a project (that's what "remove" is currently) but not delete it from their computer. Even if there is one, I doubt it is as frequent as just wanting to delete a project completely.

**Comment by Calinou** [comment]
> Honestly, I just cannot find any use case where the user would like to de-list a project (that's what "remove" is currently) but not delete it from their computer.

In general, in user interfaces, it's better to err on the side of caution :wink:

Many people aren't using version control, so when a project is deleted from disk, it's gone forever.

**Comment by vrbandwagon** [comment]
Thank you for your answer.
In any case, I would still be grateful with the checkbox option.
Here's a mock-up to show my appreciation.
<blockquote class="imgur-embed-pub" lang="en" data-id="lu92oFM"><a href="//imgur.com/lu92oFM">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
