### ISSUE TITLE
Bring back the ability to import models as a *.mesh file!

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot-proposals#6960]
### Describe the project you are working on

Character generator.

### Describe the problem or limitation you are having in your project

In Godot 3 it was possible to import a 3D model as *.mesh.
The mesh format was clear and convenient. It was easy for me to change it in the code and save it. It took up little space and I could edit it in the code.

This is not a very necessary innovation, but it was there and it was convenient for me.
I just removed all those fbx, gltf, obj and kept my project clean. Now I get the whole meshinstance scene from fbx, which I don't need. I would like to be able to work with pure mesh data.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This is not a very necessary innovation, but it was there and it was convenient for me.
I just removed all those fbx, gltf, obj and kept my project clean. Now I get the whole meshinstance scene from fbx, which I don't need. I would like to be able to work with pure mesh data.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This functionality has already existed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it is possible to convert models to obj, which are close to *mesh and also don't create scenes when imported. But the native engine format is better, I believe.

### Is there a reason why this should be core and not an add-on in the asset library?

Having mesh files, I can change them in the code for the meshinstance node, for example. I can read them like a regular array and store them in a non-video memory. This allows me a lot. Just data in a simple format.

**Comment by Calinou** [comment]
This is already possible. You can use the **Save To Mesh** option in the Advanced Import Settings dialog, or import OBJ files to a Mesh resource (which is still the default in 4.0).

**Comment by Lexpartizan** [comment]
> This is already possible. You can use the **Save To Mesh** option in the Advanced Import Settings dialog on any imported 3D scene (regardless of format), or import OBJ files as a Mesh resource (which is still the default behavior in 4.0 – just like in 3.x).

I don't see such an option.
![image](https://github.com/godotengine/godot-proposals/assets/48552343/29931390-495c-4ae4-b692-557e18b7c41d)

**Comment by Lexpartizan** [comment]
> This is already possible. You can use the **Save To Mesh** option in the Advanced Import Settings dialog on any imported 3D scene (regardless of format), or import OBJ files as a Mesh resource (which is still the default behavior in 4.0 – just like in 3.x).

I don't see such an option. Could you show this window?

**Comment by Calinou** [comment]
> I don't see such an option. Could you show this window?

https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_scenes.html#using-the-advanced-import-settings-dialog

**Comment by Lexpartizan** [comment]
> > I don't see such an option. Could you show this window?
> 
> ["Save to File" after selecting a mesh in the Advanced Import Settings dialog](https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_scenes.html#using-the-advanced-import-settings-dialog)

*.res,*.tres, not *.mesh
But working if mesh manually. Thanks!

**Comment by Calinou** [comment]
> .res,.tres, not *.mesh

`.res` is just a generic extension that can save any resource type, including Mesh.
