### ISSUE TITLE
Asign `Node`s directly to a `Joint2/3D` instead of their `NodePath`

### ISSUE THREAD

**Issue by thornySoap** [godotengine/godot-proposals#6981]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

N/A

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Is there a large (dis)advantage with either of the two options? If not I think it would be better to have `node_b = my_node` instead of `node_b = my_node.get_path()`. After all I waisted some real time to figure out what was wrong. Also, I think it would be cleaner because it doesn't have to be piped through a String then.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by AThousandShips** [comment]
Also none of the entries in the proposal are optional, you need to fill the last three ones in especially

**Comment by thornySoap** [comment]
> Because as far as I know all nodes that point to another node with properties use NodePath, because that's the only way to serialize it for scenes etc., beyond just the safety factor

Ok, I understand. I just haven't seen usecases of NodePath somewhere else, sorry. It would be nice if you could tell me an example

**Comment by AThousandShips** [comment]
> but isn't the risk for having an invalid path higher than an invalid reference?

Simply, no, first of all an invalid path will cause an error, detecting an invalid reference is a different issue.

> is at first a conversion from String to reference

Not from a string, as I said, it's from a path, which isn't treated as a string internally, performance wise

> It would be nice if you could tell me an example

* `MeshInstance3D` to the `Skeleton3D`
* `AnimationPlayer` to the `AnimationTree`
* `Node3D` to its visibility parent
So on, and so on

It's almost everywhere, and is *everywhere* for serialized properties (few exceptions, like `Node.owner`)

**Comment by AThousandShips** [comment]
> `node_a = $path` would have been clear and understandable

Except that's not a path, it's a node, just do `^"path"`

**Comment by AThousandShips** [comment]
> I just tested, it does not

Okay, but it doesn't *break*

> That was the issue of the person mentioned above: ^ needs you to give the absolute path

I'm not sure what they are doing, but this isn't true from the code, will look into if this is in fact the case

**Comment by thornySoap** [comment]
> MeshInstance3D to the Skeleton3D
    AnimationPlayer to the AnimationTree
    Node3D to its visibility parent
    So on, and so on

I agree that it would be bad to have inconsistency

**Comment by AThousandShips** [comment]
And that was not a bug, it was user error
