### ISSUE TITLE
Add primality test to math functions

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot-proposals#6983]
### Describe the project you are working on

I was dealing with some divisions stuff and though to create a primality test into the engine.

### Describe the problem or limitation you are having in your project

None, it just that would be reusable for the engine to have one.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Primality checks, as I'm thinking would be a great way to know how to divide chunks of data. It could be quadrant_size in the TileMap, for example.
Plus, I've saw a function called larger_prime in core/math_func, so  it could help with that too?

Nevertherless, I did made a PR, but it's bad and I would like a green light to translate my Python prototype before actually updating it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It's basically easy tests and, if all fails, AKS.

It could be just AKS or a limit could also be set (AKS is better for large primes). You know, I'd have to compare and benchmark it.

The algorithm I'm basing for the AKS is this: 

https://github.com/Ssophoclis/AKS-algorithm

The pseudo-code for what I'm thinking about (and prototyping in Python is):
```
if number is even: 
    return composite
if number is less than 9 and greater than 1: 
    return prime
if first digit is  5: 
    return composite.
if number is devisable by :
    return composite
if square root of number is integer:
    return composite
if first digit is equal to last digit:
   check if all digits are the same (break if any of them isn't):
         return composite
 If all fails, AKS, but use the information gathered from those rules.
```

I don't know if pure AKS would be better, I'll test it once I'm done with the prototype. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think it could be used often. Of course it's possible to do it with GDScript, but as it's a feature that the engine itself could use, I don't see why.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, the engine could use it internally.

**Comment by AThousandShips** [comment]
> would be a great way to know how to divide chunks of data

In what way? What algorithms are you thinking about?

>  a function called larger_prime in core/math_func, so it could help with that too?

This function is to generate a prime, for use only in `OptimizedTranslation`, this is from a list, this is fundamentally different from testing primality

But I really don't see the usefulness in the engine for this, testing primality is rare in computer libraries not specifically geared towards it

**Comment by AThousandShips** [comment]
Also *do not* base your work on the repository you linked, while it doesn't have an explicit copyright statement it doesn't have a license, open source or otherwise

**Comment by JeffVenancius** [comment]
Sorry, I'll answer everything now.

> > would be a great way to know how to divide chunks of data
> 
> In what way? What algorithms are you thinking about? Please provide concrete examples, things like "it could be useful" is not a strong argument, especially for complex and performance related code like this 
> 

I'm thinking particularly in how quadrant_size is set on TileMaps (atleast my understanding of it).
It divides tiles into chunks so it renders them in chunks on the gpu. 
If you know the number of tiles are not prime, then you can divide them equally and potentially optimize this feature - as in yhe future that shouldn't be let for the user to decide.

> >  a function called larger_prime in core/math_func, so it could help with that too?
> 
> This function is to generate a prime, for use only in `OptimizedTranslation`, this is from a list, this is fundamentally different from testing primality
> 
> But I really don't see the usefulness in the engine for this, testing primality is rare in computer libraries not specifically geared towards it

> 
> > if first digit is  5
> 
> How do you intend to test this efficiently? Also this is wrong (53, 59, 557, etc.), so why are you doing this step?
> 

I think the meaning here was lost in translation, when I've said first digit, I was thinking on the unit (e.g: 25, 45, etc...)
It allways works because 5 is a half of ten.

> > if square root of number is integer
> 
> 1) not going to be efficient
> 2) not going to work
> 

I was looking at the AKS and it pretty much does that on one of the steps (but for more than the square).
The reason I was planing to do this is so I could also implement a naive approach, which is faster for small numbers (atleast from what I've gathered).

> Also as I've pointed out before, you shouldn't create your own algorithm, what are your sources for the efficiency of this?

The easy ones are kind of... Common knowledge, I think? The naive approach is the one that I don't know the real source, but you can find it everywhere and it allways works (try to divide the number by prime factors until you reach the square root of the number, if any of them divides it, you can allways say that the number is composite)

I'm also learning about AKS, but I'm not quite there yet.
The links I'm basing those on are on the prototype (I'll get it and post here, I've updated today and yeah, it was pretty broken).

**Comment by JeffVenancius** [comment]
> Also **do not** base your work on the repository you linked, while it doesn't have an explicit copyright statement it also doesn't have a license, open source or otherwise, afik just publishing code online is *not* relinquishing copyright in any form, it has to be *explicitly* licensed in a compatible way (this includes public domain)
> 
> Accidentally merging plagiarized code would be bad

I'll look for a better one (or even make my own code based on the actual algorithm)

**Comment by JeffVenancius** [comment]
Hmm, I was thinking about the TileMap thing and it could be solved easily by turning making the calculations even and then adding one... Yeah so I guess it's worthless hahahahaha

**Comment by AThousandShips** [comment]
So the simple reason you can't use the square root is that you can't take the square root of a 64 bit number exactly in the standard library implementations, and since *all* the numbers that reach this have the least significant bit set (or they'd be a multiple of a power of two) if the number is wider than 52 bits you are *completely* unable to find the root, as the `sqrt` function is only guaranteed to support double precision (`long double` is not required to have any higher precision than double) this means that you are only guaranteed to have 53 bits of precision

Now it *is* guaranteed to be exact, but only as far as precision allows

**Comment by fire** [comment]
If this doesn't solve a problem or limitation you are having in your project, why would we want to add it to the engine?

That said, I believe that the rsa code in mbedtls has a prime generator as part of its cryptographic certificate generation process.

**Comment by AThousandShips** [comment]
It does, though it uses a probabilistic method, though with very low failure probably

**Comment by Calinou** [comment]
Remember that if you only need to check whether a relatively small number is prime, you could have a precomputed array that contains the first 1,000 prime numbers or so. This is likely enough for the TileMap editor's needs.

**Comment by AThousandShips** [comment]
I don't even see the justification for prime numbers in the tile map

**Comment by JeffVenancius** [comment]
Hmm, yes. 
Well, I guess that's it then, as it doesn't help the engine at all and it seems there is no reason to it, I'll close it.

Sorry for taking your time, thank you for your patience.
