### ISSUE TITLE
Add a "Open Terminal Here" context menu option to the FileSystem dock

### ISSUE THREAD

**Issue by spirit-x64** [godotengine/godot-proposals#6994]
### Describe the project you are working on

An action-adventure survival game 

\*This feature should help in the development process of any other game though\*

### Describe the problem or limitation you are having in your project

Every time I needed to use the terminal for whatever reason (running git or any other CLI software) I had to open the terminal manually (or simply <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>) then manually navigate to the project directory using `cd path/godot/project` (witch I most keep remembering the path) then finally do whatever I wanted

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a shortcut or simply an option in the select menu (when pressing <kbd>RMB</kbd> on the file system dock) to open the terminal in the project directory quickly

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user right clicks on the the file system dock show an option to `Open terminal here` beside the `Open in file manager` option which will open a new terminal in the project directory `res://`. and if the user right clicks on a folder it should open a terminal in that folder.
![image](https://github.com/godotengine/godot-proposals/assets/67455370/d86a8052-dc62-4a08-95c4-9f5654d2dc5f)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm sure it will be used quite often

### Is there a reason why this should be core and not an add-on in the asset library?

This feature is in every file manager out of the box even in file managers that is not developer-focused (like the windows file manager)
It makes sense to add it considering it's an improvement to the editor workflow as a whole

**Comment by Calinou** [comment]
> i find the current way of doing this in Linux super easy and quick, so maybe disabling it in linux by default (But keeping it as an option) would result in a more clean experience.

I wouldn't disable this by default. It's better to open a "wrong" terminal choice than not having any option for doing so at all out of the box.

**Comment by ZynosStudios** [comment]
This would be very helpful since we do most of our work on windowws

**Comment by Calinou** [comment]
@ZynosStudios Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by sosasees** [comment]
> It's better to open a "wrong" (i.e. non-default) terminal choice than not having any option for doing so at all out of the box. That said, we can probably get the choice right in most cases without too much trouble.

when in doubt, add a 'Terminal Executable' editor setting
that is empty by default so that Godot looks for the default terminal
but can be filled so Godot uses the chosen terminal

**Comment by Calinou** [comment]
> when in doubt, add a 'Terminal Executable' editor setting
that is empty by default so that Godot looks for the default terminal
but can be filled so Godot uses the chosen terminal

This is what I did in the WIP branch I linked :slightly_smiling_face:
