### ISSUE TITLE
Android Tools Auto Download

### ISSUE THREAD

**Issue by MintStudios** [godotengine/godot-proposals#700]
**Describe the project you are working on:**
Puzzle Game

**Describe the problem or limitation you are having in your project:**
(Had this problem) Android exports. The first time a did this, I accidentally downloaded the entire android studio. Hard to find android tools for exporting, and hard to import them to godot.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If there was a button in the project drop down that would download needed android tools for export (openjdk, android packages, adb.exe) and automatically set the variables up in godot, it would really help beginners.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Screenshot 2020-04-11 at 11 14 49 PM](https://user-images.githubusercontent.com/54677274/79059637-509b4a80-7c4a-11ea-8b07-344e98e2e47d.png)
Simply making a request to the page of the tool, and installing it. It should be under project tab or editor.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not a godot specialist, so I don't know.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This should be in the core, because this feature is specifically tailored for _**beginners**_. They might not want to or even know about the asset library.

**Comment by Calinou** [comment]
Unfortunately, downloading the Android SDK in an automated manner is a difficult task. This is because it uses "click-through" licensing where you must accept licenses in a terminal before proceeding. If you skip this step, you won't be able to use any of the tools.
