### ISSUE TITLE
Allow users to pick which Resources will be made unique when using "Make Unique (Recursive)"

### ISSUE THREAD

**Issue by joao-pedro-braz** [godotengine/godot-proposals#7009]
### Describe the project you are working on

N/A (Based on feedback from other contributors and artists)

### Describe the problem or limitation you are having in your project

The current behavior of "Make Unique (Recursive)" can be problematic in situations which involve a large amount of Resources, as it'll make all resources unique, without allowing to specify exceptions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We should allow users to pick which resources they want or don't want to make unique, instead of making *all* of the nested Resources unique.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Ideally when selecting "Male Unique (Recursive)" a dialog would pop-up, which would allow the user to pick (in a Tree like fashion) which Resources they *don't* want to make unique.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It must be a core change.

### Is there a reason why this should be core and not an add-on in the asset library?

It can not be an add-on.

**Comment by Calinou** [comment]
For future reference, this was originally tracked in https://github.com/godotengine/godot-proposals/issues/4503.
