### ISSUE TITLE
Visual Scripting.

### ISSUE THREAD

**Issue by Xnut22** [godotengine/godot-proposals#7018]
### Describe the project you are working on

I want to make a zombie story driven game so no open world just story so I can add more details to the zombies depending on how detailed the scene is. I like horror games.

### Describe the problem or limitation you are having in your project

As a beginner I have no coding experience only a little in LUA. I will be getting the lua addon.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

you guy already has the feature y'all just took it off the engine if I could think of anything to add to it, it would be the switch to nodes to code feature I really liked that if you can make that feature Universal for all coding languages even if your addon isn't the best at least everyone and any one can use it would be a perfect way to start coding. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I worked in Linux first I use the nano txt editor it can run scripts but not all because you have to add the Hight light files and other stuff to it maybe instead of having all the coding languages on one addon make them download the code and plug it into the addon. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

if you know what your doing. lol

### Is there a reason why this should be core and not an add-on in the asset library?

it should be a addon depending on the size it should septet.

**Comment by AThousandShips** [comment]
Already tracked in #6954

**Comment by Zireael07** [comment]
Also already available as a module: https://github.com/godotengine/godot-visual-script

**Comment by AThousandShips** [comment]
> Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is supposed to be filled in with actual descriptions of how to implement this

**Comment by Xnut22** [comment]
> > Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
> 
> This is supposed to be filled in with actual descriptions of how to implement this

that's why I want the feature idk how to do that lol.

**Comment by AThousandShips** [comment]
Then open a discussion, as instructed:

> Proposal issues are required to explain in technical detail how the suggested change should be implemented. It is also preferred that the submitter of a proposal is ready to implement it if it was approved. If you have a more general idea for a feature but are not well versed in Godot's architecture or do not possess the necessary knowledge to implement it in the engine, feel free to open a [discussion](https://github.com/godotengine/godot-proposals/discussions/new) instead of an [issue](https://github.com/godotengine/godot-proposals/issues/new/choose).

**Comment by Xnut22** [comment]
> Already tracked in #6954 (and this doesn't really contain a description of how it would work, so not any real added to what's already over there)

like I said how am I going to add a solution if don't know how to code if I could I would.

**Comment by Xnut22** [comment]
> Also already available as a module: https://github.com/godotengine/godot-visual-script

thank you kind sir.

**Comment by Xnut22** [comment]
> Then open a discussion, as instructed:
> 
> > Proposal issues are required to explain in technical detail how the suggested change should be implemented. It is also preferred that the submitter of a proposal is ready to implement it if it was approved. If you have a more general idea for a feature but are not well versed in Godot's architecture or do not possess the necessary knowledge to implement it in the engine, feel free to open a [discussion](https://github.com/godotengine/godot-proposals/discussions/new) instead of an [issue](https://github.com/godotengine/godot-proposals/issues/new/choose).
