### ISSUE TITLE
Add support for Blender's geometry nodes by setting flags before exporting to glTF

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot-proposals#7020]
### Describe the project you are working on

Any 3D game

### Describe the problem or limitation you are having in your project

I am working on the mapss for my game using blender and the .blend importer

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When we import, geometry nodes don't work, as you have to first select the object which has geometry nodes and from Object->make instances real

So if I manually do this I can no longer modify the geometry node values and I have to delete all instance modify the values then make instances real again.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When Godot .blend importer imports objects with geometry nodes modifier it should somehow execute "make instances real"
Then import the GLTF from it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No I don't know a way of doing it with script

### Is there a reason why this should be core and not an add-on in the asset library?

Godot .blend importer feature out of the box.

**Comment by ywmaa** [comment]
it looks like I should use the node "Realize Instances" in geometry nodes, should we consider adding this as a tip in the docs, or is it a common piece of knowledge that I wasn't aware of ?

**Comment by Zireael07** [comment]
This would be awesome for procgen projects <3

**Comment by RedMser** [comment]
If the glTF exporter of Blender handles this improperly, then it should be solved as a feature request there. Alternatively, this could be resolved via #6883

**Comment by ywmaa** [comment]
> This would be awesome for procgen projects <3

Yes, currently importing them works by adding the node "Realize instances" in the geometry node in blender. 

Unfortunately I have to make the materials and assign them myself in Godot, all materials in the geometry nodes are imported as empty material.

Also another problem is that all instances are realized as one mesh, instead of importing them as instances 

Which imports my .blend file with a .bin GLB

**Comment by mikest** [comment]
relatedly, this may be resolved by the following PR. more testing would be helpful.

https://github.com/godotengine/godot/pull/112866
