### ISSUE TITLE
Show indicator for Control nodes which rect_min_size is overrided

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-proposals#703]
**Describe the project you are working on:**
Turn-based strategy game

**Describe the problem or limitation you are having in your project:**
No limitation, just a hint for usability

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I think Control-derived nodes which rect_min_size is not equal to Vector2(0, 0) should be marked in the scene panel like:
![image](https://user-images.githubusercontent.com/3036176/79073962-45035e80-7cf2-11ea-8e70-2c3fc986fc68.png)

This will help a lot to detect which sub-element cause parent Control to shrink to the specified size without manual search through the (possibly huge) tree.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See above

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
Its obvious QoL change

**Comment by groud** [comment]
Hmm, in my opinion, this is too specific to be added as an icon in  the scene tree. For me only very important and common properties should go there.

**Comment by Zireael07** [comment]
Maybe an yellow ! in the inspector next to min size, if it's not 0,0?

**Comment by Chaosus** [comment]
Nevermind, seems like a bad idea
