### ISSUE TITLE
Add Light3D's Negative property as a `light()` shader function built-in

### ISSUE THREAD

**Issue by RichMakeGame** [godotengine/godot-proposals#7036]
### Describe the project you are working on

first person exploration game

### Describe the problem or limitation you are having in your project

shaders using custom light() logic cannot make use of lights Negative property. This would allow it to be used with custom lighting in shaders

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

shaders using custom lighting can make use of a lights Negative attribute

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

accessing the Negative built-in with custom lighting shaders would allow shaders to remove light as well as adding, to allow artistic use of lights with Negative enabled.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no, the only way to access properties of arbitrary lights in the shader is through built-in values 

### Is there a reason why this should be core and not an add-on in the asset library?

shader functionality is a core system and this would benefit anyone working on custom lighting shaders

**Comment by Calinou** [comment]
> accessing the Negative built-in with custom lighting shaders would allow shaders to remove light as well as adding, to allow artistic use of lights with Negative enabled.

Could you describe a concrete use case, i.e. the visual effect you want to achieve? Maybe create some mockups, or use another engine to show what you'd like to achieve.

**Comment by clayjohn** [comment]
The "negative" property is baked into the energy, which is baked into color. So accessing the value in shader should be possible just by using ``sign(LIGHT_COLOR)``
