### ISSUE TITLE
Link back more often to the Web tutorials inside the internal Godot engine docs

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#7043]
### Describe the project you are working on

I've been trying to work with the new `NavigationServer` in `4.x` and while the system seems well designed, the documentation could still use a little work.

I would like to propose that we try and link back to the tutorials (if and when relevant) more often in the docs.

### Describe the problem or limitation you are having in your project

As someone who primarily uses the Godot engine documentation, rather than the web based documentation, I quite often find myself missing important information which is contained in tutorials.

When I look at the `NavigationServer` docs page in Godot, the only reference I have seen to the tutorials is the following:

<img width="287" alt="Screenshot 2023-06-08 at 21 24 18" src="https://github.com/godotengine/godot-proposals/assets/100964/cc70f9ec-7dd1-4ee9-a9ae-8463ff7129c4">

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be so cool to see more references in the docs (on each function doc) to where they have been used in a previous tutorial.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As a single example:

<img width="607" alt="Screenshot 2023-06-08 at 21 27 24" src="https://github.com/godotengine/godot-proposals/assets/100964/69c1f9ae-bc93-4a6c-8ce6-0b9f61f120e1">

This function was also used in this tutorial:

https://docs.godotengine.org/en/4.0/tutorials/navigation/navigation_using_navigationservers.html#waiting-for-synchronization

<img width="894" alt="Screenshot 2023-06-08 at 21 28 06" src="https://github.com/godotengine/godot-proposals/assets/100964/e83ad8c8-d825-4cea-aa26-60a5c71b7b18">

Having a link-back more often would likely help me to find relevant docs more quickly and therefore spam the issues or discord less.

![image](https://github.com/godotengine/godot-proposals/assets/100964/e5ab7c69-0a09-4793-a215-c828362d805c)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Interestingly this could perhaps be done via code?

We could search for `NavigationServer3D.some_function` and then link-back to a relevant tutorial.

Perhaps "This function may have been used in this tutorial"

### Is there a reason why this should be core and not an add-on in the asset library?

This would be amazing to have in the Godot core docs, I don't particularly find the web-docs useful right now, because we still have some issues with the Google SEO.

**Comment by Calinou** [comment]
This sounds very difficult to automate, and not all linkbacks may be worthwhile. We need to be careful about the signal-to-noise ratio of such a feature.

**Comment by tavurth** [comment]
> This sounds very difficult to automate, and not all linkbacks may be worthwhile. We need to be careful about the signal-to-noise ratio of such a feature.

Yes it's very true, perhaps another way to do this would be to have the tutorials available in the Godot built-in docs system?

That way we could actually run a search on the `tutorials` folder?

**Comment by tavurth** [comment]
> This would increase binary size too much, not to mention it means we'd have to synchronize the online docs with the built-in editor docs (which is already proving to be a burden for the class reference).

Hmm yea ok that makes sense. How might we draw more attention to them in this way then?

Are the docs currently compiled on a machine or in the CI?

Perhaps the CI could pull both repos and run a search in that way.

**Comment by tavurth** [comment]
Might I ask why they are divergent?

I see many people surprised that I haven't read some doc or another because "It's the first place you should start", yet I read those docs all the time inside the editor.

Every major update, one must read the entire doc-set anew?

**Comment by AThousandShips** [comment]
What's your point in singling me out? This isn't really professional...

**Comment by AThousandShips** [comment]
The online docs have to be manually updated and this is done periodically, they have to be generated and updated so it's not necessarily reasonable to update them ever single time some PR gets merged

**Comment by tavurth** [comment]
Hi @AThousandShips, I've had you on block for a while and unblocked to give you a chance to say your peace.

> What's your point in singling me out? This isn't really professional...

https://github.com/godotengine/godot/issues/76214#issuecomment-1513515493

**Comment by AThousandShips** [comment]
Singling me out as someone you're upset at for instructing you to read the documentation when it contained the information you needed is unprofessional and tbh in my opinion borders on harassment, if you were upset at my behaviour then you should have either talked to me, or the code of conduct team, not carried some grudge over it...

**Comment by tavurth** [comment]
> but I think docs are the easier way out of the two. Godot updates too fast for the vast majority of external tutorials anyway.

Hmm yes it's true and a little bit frustrating. Godot will never be finished, so it's gonna be a continual learning process sure.

Yet we have a nice 3.x -> 4.x migration tool, would be cool to not have to re-read everything all the time.

Maybe there's some better way to think about changelogs?

This proposal is just what seemed to be a cool idea to me, but maybe there's a better way?

Perhaps highlighting docs-changes since the last time a user read them instead?

> if you were upset at my behaviour then you should have either talked to me, or the code of conduct team, not carried some grudge over it...

Over the many issues I've interacted with you, all of them have left me with a negative feeling, so yes 🤷 Also there's no private chat on github as I have yet found. So not singling out, but just a good bye.

**Comment by YuriSizov** [comment]
Okay, how about we start this issue over without personal attacks? This proposal is burnt at this point with a non-technical and antagonistic discussion. Please make another one and be mindful of the [code of conduct](https://godotengine.org/code-of-conduct/).
