### ISSUE TITLE
Add bitwise implementations for to_lower and to_upper

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot-proposals#7046]
### Describe the project you are working on

I'm learning about bitwise operators and such and, as I was looking in the src, I've found some functions that could use it - As long as it is actually better to do so, of course.

### Describe the problem or limitation you are having in your project

None, I just think some operations could optimize little functions like _to_upper, _to_lower, etc...

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Today I've implemented _to_lower and _to_upper using the number 6 idea from here:
https://codeforwin.org/c-programming/10-cool-bitwise-operator-hacks-and-tricks

It only works from a-z and A-Z, so I've taken that into consideration.

Instead of entering on the loop and look for the respective char in the table, you can do this operation (as long as the char is in range.)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot/commit/edd73a48b52a755bb4a364779913ca8aa873d24a

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think it would be faster since the characters used are mostly the alphabet.

### Is there a reason why this should be core and not an add-on in the asset library?

It's an implementation of a built-in function.

**Comment by AThousandShips** [comment]
This would only work for ASCII no? `to_upper/lower` covers unicode

**Comment by JeffVenancius** [comment]
Yep, but I've taken this into consideration by setting a range.

It won't ignore it, unless it it is ASCII and it is a-z/A-Z.
I don't know if it'd be actually faster, as I didn't benchmarked, but for most use cases I do think it could fasten up a bit.

**Comment by JeffVenancius** [comment]
Yep, but I've taken this into consideration by setting a range.

It won't ignore it, unless it it is ASCII and it is a-z/A-Z.
I don't know if it'd be actually faster, as I didn't benchmarked, but for most use cases I do think it could fasten up a bit.

**Comment by AThousandShips** [comment]
> as I didn't benchmarked, but for most use cases I do think it could fasten up a bit.

Please *do* benchmark, I'm not convinced it'll make any real improvement, even if fixed so it doesn't break characters

**Comment by JeffVenancius** [comment]
It runned around 1ms faster for around 1385700 chars on the editor profiler (without this bounds I've forgot)

**Comment by JeffVenancius** [comment]
Hmmm.... Yeah I was looking and I think it doesn't pay. Sorry.

**Comment by AThousandShips** [comment]
Thank you for your efforts anyway!
