### ISSUE TITLE
A better toon shader . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#705]
**Describe the project you are working on:**
Trying to make a little game, for a jam, for fun . . .

**Describe the problem or limitation you are having in your project:**
The toon shader can use a method, where one uses the ' grow ' parameter, but it pushes the faces out, without connecting them . . . Instead of just pushing the planes out, could one push the vertixes out, along their normal, and then connect the planes, instead . . . It would give a nicer effect, anyway a suggestion . . Alternatively, add a ' scale ' function under ' grow ', so one could scale the ' grow ' faces, as well . . I am a beginner, and I can't code all this stuff, right now . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Well, it would make toon shaders, with a ' grow ' outline look a lot nicer, for beginners . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Here's how it looks right now, when you use ' grow ' . . Could one add an extra feature, so it didn't push the ' faces ' out, but the vertices, and then connected them, with shader planes or, so, is it super-tough code . . .

![2020-04-14 0619](https://user-images.githubusercontent.com/61069740/79189838-16d16c00-7e23-11ea-97cf-e22fce74ec50.jpg)

![2020-04-14 0648](https://user-images.githubusercontent.com/61069740/79189846-19cc5c80-7e23-11ea-9a79-111632293c7c.jpg)

The problem is, when the ' grow ' faces are rendered in ' front ' cull mode, there are these gaps, wish there was a function to grow the vertices, instead of the planes, very simple . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not that I know of, not really . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, it would give a nicer cartoon effect, for most users . . .

**Comment by jasperbrooks79** [comment]
Maybe one could make a grow vertix, a grow line and, a grow face option . . <3 <3

**Comment by jasperbrooks79** [comment]
or, ' grow point ', or ' grow face ' under-option, in shader parameters . . . .

**Comment by Calinou** [comment]
Vertices should be connected with each other if your faces are marked as smooth.

**Comment by aaronfranke** [comment]
I'm not an expert on materials or shaders, but I'm very confident that this can be done with user code (and therefore in an add-on in the asset library).

Have you tried the [material testers](https://godotengine.org/asset-library/asset/123) demo? It has a toon material:

![toon](https://user-images.githubusercontent.com/1646875/79243596-d6ceb100-7e43-11ea-8b37-4dee4143687f.png)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1620.
