### ISSUE TITLE
Add debugging option to execute arbitrary GDScript statements on game start

### ISSUE THREAD

**Issue by myaaaaaaaaa** [godotengine/godot-proposals#7064]
### Describe the project you are working on

Godot rendering

### Describe the problem or limitation you are having in your project

Debugging requires easy access to engine settings from the command line, so that different options can be quickly tested without accidentally persisting any unwanted changes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding support for GDScript debugging hooks allows users to run custom one-shot debugging commands, without having to wait for Godot to officially add command line support for every component that they may wish to debug.

For example, the following debugging hook can be used to diagnose if LOD transitions are too noticeable:

```bash
$ export GODOT_DEBUG_HOOKS_PROCESS='get_viewport().mesh_lod_threshold=32*pow(2,sin(time*2*PI))'
$ export GODOT_DEBUG_HOOKS_READY='get_viewport().debug_draw=Viewport.DEBUG_DRAW_NORMAL_BUFFER'
$ godot

[...]

debug/hooks/ready set to get_viewport().debug_draw=Viewport.DEBUG_DRAW_NORMAL_BUFFER
debug/hooks/process set to get_viewport().mesh_lod_threshold=32*pow(2,sin(time*2*PI))


extends Node
func _ready():
	get_viewport().debug_draw=Viewport.DEBUG_DRAW_NORMAL_BUFFER
var time := 0.0
func _process(delta):
	time += delta
	get_viewport().mesh_lod_threshold=32*pow(2,sin(time*2*PI))


Debug hooks successfully registered as autoload
```

https://github.com/godotengine/godot/assets/103326468/de4d47bd-0665-41af-9c29-4edd843543b0

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See accompanying PR: https://github.com/godotengine/godot/pull/77983

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be implemented via an Autoload script containing the following pseudocode:

```gdscript
func _ready():
	if !DEBUG_BUILD:
		return

	var script := GDScript.new()
	script.set_source_code("func debug_hook():" + cli_input)
	script.reload()
	script.call("debug_hook")
```

### Is there a reason why this should be core and not an add-on in the asset library?

This can also be implemented as an addon/plugin. It may be less convenient if the user would like this to be automatically enabled in every project.

**Comment by Zireael07** [comment]
Workaround is so short and sweet I see no reason to add complex hooks into core itself

**Comment by KoBeWi** [comment]
That's what feature tags are for. Use `if OS.has_feature("editor")` and your code will never run in exported project.
