### ISSUE TITLE
Allow option to update TileMap tiles when changing TileSet Atlas ID

### ISSUE THREAD

**Issue by 2fd5** [godotengine/godot-proposals#7070]
### Describe the project you are working on

Isometric strategy game

### Describe the problem or limitation you are having in your project

I want to rearrange TileSet atlases so that are ordered with some organisation in mind. For that I am changing ID's.
When changing ID's current TileMap, meaning placement of tiles of certain ID is lost.

On top of that the "!" on TileMap is not very useful, it would be more informative to show source ID there as well so that the user can at least know what is missing, rather then just undoing.

There is possibility for a helper process that would ask, 
there is a missing source ID: N, to you want to replace it with a given source ID ?
Then the wizard given a new source ID would update the instances on the TileMap with the new source ID.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Editor could check for changed TileSet atlas ID, are there any on the map, if so propose to update the new ID in TileMap so user does not have to yet another step or replace the tiles on TileMap

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As per FR description. Or alternatively allow to reorder source list in TileSet without affecting source ID

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not aware

### Is there a reason why this should be core and not an add-on in the asset library?

It is an usability FR

**Comment by KoBeWi** [comment]
Note that you can sort atlases by name, so you can effectively order them without changing their id.
Remapping tiles is supported in form of proxies. Not sure if they are available in editor (i.e. outside code) though.

**Comment by 2fd5** [comment]
> Note that you can sort atlases by name, so you can effectively order them without changing their id. Remapping tiles is supported in form of proxies. Not sure if they are available in editor (i.e. outside code) though.

Thanks renaming with some naming convention in place and sorting by name is a valid workaround. 
Personally would prefer to be able to drag and drop the items in the list, but then the complication is when you sort it and loose the manual order, then in sorting it would require another option for manual order. Seems like unnecessary complication.

I suppose that the issue is specific to my use case as I do not use texture atlases, or atlas contains one or two regions as I am in prototyping phase. 
Better approach might be to merge that is available in the editor or external merge to the atlas texture.

Yes proxies are there in the editor, the UI might be improved but it is available.

Thanks for the information. I suppose this ticket could be closed as there are ways of solving both issues described.
