### ISSUE TITLE
Unifying Scene and Script Tabs to reduce UX ambiguity

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot-proposals#7098]
### Describe the project you are working on

Different project across various clients

### Describe the problem or limitation you are having in your project

The way scripts / scenes are presented requires from me a lot more mental capacity then it should

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'm working with Godot since it's 1.0 release, since 2.x times I have occasional problems with understanding what I'm looking at, it's almost like editor is trying to trick me into thinking that I'm looking at something different then I'm, which confuses me. 
Please take a look at this screenshot:
![scene_tab_unification](https://github.com/godotengine/godot-proposals/assets/6129594/fdc0f086-11a4-453b-a6f3-c674c8116406)

Two places are indicating the context I'm working in is 'Enemy' while in reality I'm looking at 'Hero' script.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

To address this issue I would like to propose to extend/replace the functionality of "Open Dominant Script on Scene Change" with something much more comprehensive, I would like to propose mode where we are merging scene tabs with script tabs, so all the tabs are in the same place.
The way I imagine it to look from user perspective is as follows:
1. With the option ON we are removing the side script view completely
2. If user is [opening/switching to] scene which has main script attached to it, it works exactly the same way current "Open Dominant Script on Scene Change" option works
3. If user is opening a script, editor should automatically detect if there is scene associated with this script (root node which has it), it could simply happen in a result of checking if in a directory with a script there is a scene with the same name (more sophisticated approach is to implement  # 1935 proposal)
- - If there is such scene it's being open, and "Open Dominant Script on Scene Change" functionality will kick into play
- - If there is no such scene the editor will open a script, and present it in the top bar, the same bar that's currently reserved for scenes
- - Above also apply to all 'non node' scripts, so basically all resources
4. Each time editor wants to open any script for any reason (ex. runtime crash) all the above should be respected

To **summarize the idea in short words**: the panel that's being used currently for scene tabs, in this mode should be used for scripts as well. Editor should be able to detect the link between Scenes and Scripts and open both when possible (and both of them would be represented by the same tab)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is about editor UX

### Is there a reason why this should be core and not an add-on in the asset library?

This is about editor UX

**Comment by kubecz3k** [comment]
Related to some degree:
https://github.com/godotengine/godot-proposals/issues/1909

**Comment by YuriSizov** [comment]
This was already proposed in https://github.com/godotengine/godot-proposals/issues/966, https://github.com/godotengine/godot-proposals/issues/4457, and https://github.com/godotengine/godot-proposals/issues/5314. And to a degree in https://github.com/godotengine/godot-proposals/issues/4081.

**Comment by kubecz3k** [comment]
I think none of those proposals recognized the need of unification whole context switching (not only the ui behind scripts / scenes but also scene tree).
My problem is with how context of the work is being presented, we should have one button that allows to switch context from one subject to another, not only script but also scene (and therefore scene tree)

**Comment by YuriSizov** [comment]
Well, whatever your reason to have this is, it's still the same proposal. You could lend your voice to any of them to make it more likely that one of them is implemented, and then we could discuss the added QoL that you describe.

Besides, what you describe cannot be implemented in the current version of the editor without some heavy assumptions and needs #1935, yet another proposal, to act as a backbone and provide some context that we could utilize for auto-switching. So you could lend your voice to #1935 as well to give it more support and mention that it would make sense to implement it with auto-switching.

**Comment by kubecz3k** [comment]
Well, fair enough duplicate is a duplicate, will close this one then
