### ISSUE TITLE
Drag a node on a float script window

### ISSUE THREAD

**Issue by Grellim** [godotengine/godot-proposals#7101]
### Describe the project you are working on

A shortcut to extend a onready var when you use ctrl+drag on de script area.

### Describe the problem or limitation you are having in your project

With the float script window, we can't use Ctrl+Drag to make a onready var of a node automatically.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to extend the node on script on de node options or make the float window stay when you drag the node there.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just pressed Ctrl and drag on script area of the node and then the node var will be make on the script folder.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so

### Is there a reason why this should be core and not an add-on in the asset library?

Godot has that mechanic in native code

**Comment by Calinou** [comment]
> or make the float window stay when you drag the node there.

Does it work when you put the floating window on the side of the editor? This is how it's intended to be used (for multimonitor/ultrawide usage).

It's feasible to add an always-on-top toggle, but it would also affect other non-Godot windows.

**Comment by KoBeWi** [comment]
This is a bug.
See https://github.com/godotengine/godot/pull/67531 and linked issues.
