### ISSUE TITLE
Improve color selector editable hex code entry handling

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#7108]
### Describe the project you are working on

Multiple Projects

### Describe the problem or limitation you are having in your project

Currently for Invalid Color Hex Codes like `#012` and `#AE` the color falls back to black `#000000` or behaves erratically.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Suggestion is to improve the handling of codes like in Figma.
e.g., 
if you enter `#5` change it to `#555555`
if you enter `#AE` change it to `#AEAEAE`
if you enter `#F23` change it to `#FF2233`
if you enter `#6459` change it to `#66445599`
if you enter `#32456` change it to `#33224455`
if you enter `#45F235` change it to `#45F235`

Also, IMO I don't see a sense of entering names of colors in the field for game development,
It will also lead to additional overhead of parsing too, but it does not hurt to have it there, but IMO add another small button or icon, which on click will list downs the colors to select from.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This will improve the usability of the Color Selector and less key strokes for entering, hex codes

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The workaround is to enter the full hex code in the field.

### Is there a reason why this should be core and not an add-on in the asset library?

Color Selector is part of the Core.  Any enhancements to the core of that functionality should be part of core.

**Comment by Calinou** [comment]
> Also, IMO I don't see a sense of entering names of colors in the field for game development,
It will also lead to additional overhead of parsing too, but it does not hurt to have it there, but IMO add another small button or icon, which on click will list downs the colors to select from.

Many people have tried to do it instinctively, and they're happy to see the feature as evidenced by reactions in https://github.com/godotengine/godot/pull/75905 :slightly_smiling_face:

**Comment by tokengamedev** [comment]
> While #AE doesn't parse, #012 works correctly on 4.0.3 for me (it results in #001122). Short hexadecimal color codes have been supported since Godot 3.0, if not earlier. The leading hexadecimal character is optional.

I have tested it on 4.1.beta.2 and as you said some of them are possible, but for reference I have listed all possible combinations.

> Many people have tried to do it instinctively, and they're happy to see the feature as evidenced by reactions in https://github.com/godotengine/godot/pull/75905 🙂

Looks like many people would like it too 😃 

> Either way, we can implement what you proposed without having to remove support for parsing named colors. This is because named colors are only attempted if the string isn't a valid HTML color, and I don't think there's any color name between 1 and 5 characters that only features characters between a and f in its name.

I am ok with either way, 👍 .  Also to point out `blue`, `red` and `cyan ` are colors too. 

 > In terms of implementation, this would likely be done by modifying html_is_valid() and html() in [core/math/color.cpp](https://github.com/godotengine/godot/blob/a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee/core/math/color.cpp).

This method names  html_is_valid() and html() raises a concern as it should be rgba_is_valid() and rgba() like we have methods for hsv and others color formats.  It is contextually wrong.

Few more cosmetic change request:
1.  When the user presses `enter` after entering color or after pasting color text. The text should be evaluated, and field updated. (It is kind of happening now for some cases and sometimes don't know what is going on)
2.  When user enters text, change the color of text to Red, if invalid color is entered or change to default color `#000000`. Just don't do nothing. You will only notice the change when you switch the tab(RGB, RAW etc)
3. When color is updated have the caret at the end of the text not at the beginning

**Comment by Calinou** [comment]
> This method names html_is_valid() and html() raises a concern as it should be rgba_is_valid() and rgba() like we have methods for hsv and others color formats. It is contextually wrong.

We can't rename those methods without breaking compatibility with existing projects.
