### ISSUE TITLE
update ``Control`` nodes' size when changing the _window size_ project settings

### ISSUE THREAD

**Issue by sosasees** [godotengine/godot-proposals#7125]
### Describe the project you are working on

a GUI application

### Describe the problem or limitation you are having in your project

when changing the window size project settings, i can't see if the new window size is better (or worse) for the layout until i close the project settings and reselect the root [Control](https://docs.godotengine.org/en/stable/classes/class_control.html) node's anchor preset.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

if the [Control](https://docs.godotengine.org/en/stable/classes/class_control.html)s update their size when changing the _window size_ project settings, i can check how the new window size affects the opened scene instantly, instead of having to close the project settings and reselect the scene root [Control](https://docs.godotengine.org/en/stable/classes/class_control.html)'s anchor preset first.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

when changing the project setting [``display/window/size/viewport_width``](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-display-window-size-viewport-width) or [``display/window/size/viewport_height`` ](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-display-window-size-viewport-height), every [Control](https://docs.godotengine.org/en/stable/classes/class_control.html) that is a scene root or [CanvasLayer](https://docs.godotengine.org/en/stable/classes/class_canvaslayer.html) child updates its [size](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-property-size).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

i can add a tool script to the [Control](https://docs.godotengine.org/en/stable/classes/class_control.html) that is a scene root or [CanvasLayer](https://docs.godotengine.org/en/stable/classes/class_canvaslayer.html) child, that resets its anchor preset every frame:

```GDScript
@tool
extends Control

func _process(_delta:float) -> void:
	set_anchors_preset(Control.PRESET_FULL_RECT)
```

※ you could choose any [LayoutPreset](https://docs.godotengine.org/en/stable/classes/class_control.html#enum-control-layoutpreset) in place of ``PRESET_FULL_RECT``, but my [responsive UI plugin (version 1.1.0)](https://codeberg.org/sosasees/godot-4-responsive-ui-plugin/src/tag/1.1.0) chooses ``PRESET_FULL_RECT`` for its FullRectControl node type

### Is there a reason why this should be core and not an add-on in the asset library?

this is a very useful (and expected) quality-of-life feature,
and it would be much more useful if
- it was enabled in Godot out-of-the-box
- it didn't block a [Control](https://docs.godotengine.org/en/stable/classes/class_control.html)'s script slot
- the [Control](https://docs.godotengine.org/en/stable/classes/class_control.html)s _only_ updated their size when changing the _window size_ project settings — not on every frame, which is the only way to do this in GDScript ∗

∗ maybe i could change the script to only update the size when changing the _window size_ project settings, if Godot adds the [signal](https://docs.godotengine.org/en/stable/classes/class_signal.html)
[``ProjectSettings``](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html)``.setting_changed( name:``[``String``](https://docs.godotengine.org/en/stable/classes/class_string.html)`` )``

**Comment by RedMser** [comment]
+1 I've also been bothered by this a bunch. I personally would file this as a bug, but it depends on *why* it's currently not behaving correctly.
The anchor preset seems to get remembered on the Control, so it probably just isn't notified correctly that the viewport size has changed.

> maybe i could change the script to only update the size when changing the window size project settings, if Godot adds the [signal](https://docs.godotengine.org/en/stable/classes/class_signal.html) [ProjectSettings](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html).setting_changed( name:[String](https://docs.godotengine.org/en/stable/classes/class_string.html) )

There already exists [`EditorPlugin.project_settings_changed`](https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#signals) for this.

**Comment by Sosasees** [comment]
> I personally would file this as a bug, but it depends on _why_ it's currently not behaving correctly.

the disagreement if this is a bug has been there since [the comment where i asked about this issue for the very first time](https://github.com/godotengine/godot/pull/78009#issuecomment-1593368521):

1. @YuriSizov asked if i reported this **bug** ([comment](https://github.com/godotengine/godot/pull/78009#issuecomment-1593505625))
2. i replied that i think this should be a **feature proposal** ([comment](https://github.com/godotengine/godot/pull/78009#issuecomment-1593534053))

**Comment by Sosasees** [comment]
> > maybe i could change the script to only update the size when changing the _window size_ project settings, if Godot adds the [signal](https://docs.godotengine.org/en/stable/classes/class_signal.html)
> > [`ProjectSettings`](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html)`.setting_changed( name:`[`String`](https://docs.godotengine.org/en/stable/classes/class_string.html)` )`
> 
> There already exists [`EditorPlugin.project_settings_changed`](https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#signals) for this.

¡thank you! for finding this signal. i expected it to be in [ProjectSettings](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html).

**Comment by AThousandShips** [comment]
To be clear, is this *only* about the editor or both editor and running game?

**Comment by Sosasees** [comment]
this issue is about updating the [Control](https://docs.godotengine.org/en/stable/classes/class_control.html)s' size when changing the _window size_ project settings in the editor.

changing the [Control](https://docs.godotengine.org/en/stable/classes/class_control.html)s' size in the running game works like expected.

**Comment by YuriSizov** [comment]
Is this the same as https://github.com/godotengine/godot/issues/69208 ? If so, I would prefer to close this in favor of that issue.

**Comment by sosasees** [comment]
yes, this is the same issue. the only real differences are:
- i reported it as a **feature request**, @B-l-u-e-f-i-r-e reported it as a **bug**
- @B-l-u-e-f-i-r-e tells a different way to force update the [Control](https://docs.godotengine.org/en/stable/classes/class_control.html) size
   - my way: reselect the Control's anchor preset
   - @B-l-u-e-f-i-r-e's way: toggle the Control invisible, then visible again

i didn't find this duplicate myself because i didn't think of looking for bug reports when i looked for duplicates.
from my perspective, this is a missing feature and not a bug.

**Comment by B-l-u-e-f-i-r-e** [comment]
@sosasees 
This is why I believe this is a Bug:
Almost always, when settings are changed, they're updated immediately. For instance, when the renderer setting is altered, a window appears asking the user to restart the editor to apply the new settings. This seems to be the standard functionality across most settings, which either apply changes instantly or prompt the user to take an action (like restarting) to implement the change.

In this particular case, however, it doesn't update or require an action for the setting to update, instead nothing happens and the setting is not updated. This leads me to believe that we're dealing with a bug, not a situation where we're discussing a new feature request.

**Comment by sosasees** [comment]
this makes sense, now i know why this _is_ a bug.

**Comment by sosasees** [comment]
closed in favor of https://github.com/godotengine/godot/issues/69208
