### ISSUE TITLE
Import materialx as a godot material shader

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#713]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by fire** [comment]
Duplicate.

**Comment by Calinou** [comment]
Superseded by #714.
