### ISSUE TITLE
Add functions for editor plugins to show simple dialogs and file dialogs more easily

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#7130]
### Describe the project you are working on

~~Poorly written~~ Godot plugins.

### Describe the problem or limitation you are having in your project

When a plugin want to display dialogs and/or file dialogs, the dialogs have to be manually managed. This becomes worse with file dialogs because you have to 1. call an editor function that displays it and 2. unparent it for later use.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be be more convenient if the editor provide functions like `show_message()` or `choose_file()`. Just a QoL thing for plugin devs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
func foo() -> void:
    var path := choose_file(EditorFileDialog.ACCESS_FILESYSTEM, EditorFileDialog.FILE_MODE_OPEN_DIR)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can definitely be put into a sort of editor tools plugin, but seeing how Godot has no concept of plugin dependencies and plugins cannot bundle the same library if it declares `class_name`, making a shared library for editor plugins would be a pain without custom plugin management.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by KoBeWi** [comment]
https://github.com/godotengine/godot/pull/76025 added some helper functions for dialog management. You still need your own node, but it's more convenient.

**Comment by atirut-w** [comment]
I've tried a beta of 4.1 and it has that PR. Unfortunately, the function auto-adding a dialog to the editor is not very good for reusability because you have to unparent it when the dialog closes, which involves connecting multiple functions. I've even implemented a method that's more convenient and doesn't involve the functions exposed by that PR. You literally have a dialog as a child of the editor's base control for the whole plugin lifetime.

**Comment by theraot** [comment]
I have a `FileDialogHelper` (although I made this for `FileDialog` not `EditorFileDialog`):

```
class_name FileDialogHelper

static func open(dialog:FileDialog) -> PathPromise:
	var result := PathPromise.new()
	dialog.file_selected.connect(result.set_succeded, CONNECT_ONE_SHOT)
	dialog.dir_selected.connect(result.set_succeded, CONNECT_ONE_SHOT)
	dialog.files_selected.connect(result.set_succeded_multiple, CONNECT_ONE_SHOT)
	dialog.canceled.connect(result.set_failed, CONNECT_ONE_SHOT)
	dialog.popup_centered_ratio.call_deferred(0.5)
	return result
```

Which requires the `PathPromise` class (I wish promises was a thing in Godot, so I made mine, there are many places where they are useful - and they work well with signals and await - I have slight variations of this for different uses):

```
@tool
class_name PathPromise
extends RefCounted

signal completed(paths:PackedStringArray)
signal succeeded(paths:PackedStringArray)
signal failed()

enum Status {Running, Succeeded, Failed}

var paths := PackedStringArray():
	set(mod_value):
		if paths == mod_value or status != Status.Running:
			return

		paths = mod_value

var status := Status.Running:
	set(mod_value):
		if status == mod_value or status != Status.Running:
			return

		status = mod_value
		var report := func():
			if status == Status.Succeeded:
				succeeded.emit(paths)
			else:
				failed.emit()

			completed.emit(paths)
			unreference()

		report.call_deferred()


func _init():
	reference()

func set_succeded(path:String) -> void:
	paths = PackedStringArray([path])
	status = Status.Succeeded

func set_succeded_multiple(selected_paths:PackedStringArray) -> void:
	paths = selected_paths
	status = Status.Succeeded

func set_failed() -> void:
	paths = PackedStringArray()
	status = Status.Failed
```

Example of consuming it:

```
	var path_promise := FileDialogHelper.open(file_dialog)
	await path_promise.completed
	if path_promise.status == PathPromise.Status.Failed:
		prints("No path selected")
		return

	var files := import_path_promise.paths
```

**Comment by theraot** [comment]
OK, if I had a signal that unified the ways the dialog could be closed, I could await that directly, but I don't have it, the promise approach makes it trivial to unify the signals. Thus, I believe adding such unifying signal would make these dialogs much more usable (and I also believe those extra methods don't help much).

**Comment by atirut-w** [comment]
> You don't have to unparent manually, this PR also added `Window.set_unparent_when_invisible`, which you need to call once for your dialog.
> 
> >

So that's how you use it. I guess this should be closed then.
