### ISSUE TITLE
Add minimum required OS setting and app category to iOS export

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-proposals#7134]
### Describe the project you are working on

A multi-platform I'm exporting to iOS along with other platforms

### Describe the problem or limitation you are having in your project

When exporting for iOS there's no way to specify the minimum required iOS version to run. Instead this is set by default to iOS 11. However, many devices that support iOS 11 do not support the Godot 4.x mobile renderer, so to get a decent confidence in being able to run the game I need to adjust the setting to iOS 16. Similarly, there's no way to set the app category in the godot export panel, so you need to set this as well (not sure if it's required). In both cases it means you need to open the xcode project and find and set these manually. 

Note that I requested this along with some other similar changes for macOS exports in this proposal: https://github.com/godotengine/godot-proposals/issues/6360 . The macOS export changes were implemented (along with some other changes), and therefor the proposal was marked as implemented, even though these two with the iOS export settings were never implemented. So now I'm opening a new proposal for these specifically.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add export configuration fields for minimum OS version and app category for iOS exports

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same way as these same fields were added for macOS exports in https://github.com/godotengine/godot/pull/74644

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Maybe with some custom export scripts that modify the xcode project? Or you can do it manually setting these things in XCode

### Is there a reason why this should be core and not an add-on in the asset library?

The export process is part of the core

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/84162.
