### ISSUE TITLE
Draw Gizmos Icons always on top

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot-proposals#716]
**Describe the project you are working on:**
Adventure/puzzle mobile game

**Describe the problem or limitation you are having in your project:**
In complex scenes is very hard to have a overview on what's in the scene.
![Captura de pantalla de 2020-04-15 23-24-12](https://user-images.githubusercontent.com/27329423/79390814-b2242780-7f70-11ea-8cee-54626d1eb6d0.png)
As you can see the particle gizmo is obstructed by its own geometry. And if some geometry gets in front of the camera then you quickly lose track of how your scene is structured.
![Captura de pantalla de 2020-04-15 23-24-19](https://user-images.githubusercontent.com/27329423/79391037-12b36480-7f71-11ea-9707-fac0ec9b7d85.png)
Sometimes you cant even select a gizmo related node without moving the camera to a specific angle.
![Captura de pantalla de 2020-04-15 23-16-27](https://user-images.githubusercontent.com/27329423/79391190-602fd180-7f71-11ea-9533-792782b36fb9.png)
Those are simple examples, but things can get very ugly, very quickly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Drawing gizmos on top of normal geometry will allow for better overview of the scene composition. Note this is only needed for icon gizmos, other gizmos like boundaries, navmeshes, etc. should be as they are now.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
This is a two way proposal:
- Gizmos Icons will be drawn always on top.
- Gizmos Icons will fade by distance. Maybe configurable on the Perspective menu or in Editor Settings.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Maybe it can be done with a plugin substituting all the gizmos materials, but not in a "few lines of script" that's for sure.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Gizmos Icons are one of the first sources of information users have access to, I think getting them right is important for ease of use.

**Comment by Calinou** [comment]
This is already supported. Open the 3D viewport's **View** menu, go to **Gizmos** and click the gizmo twice to make it use the x-ray mode:

![image](https://user-images.githubusercontent.com/180032/79486161-970bf300-8016-11ea-9249-91af69c0a9cb.png)

Maybe we should enable x-ray mode for some (or all) gizmos, in addition to adding distance fade (probably 50 units by default?).

**Comment by Janders1800** [comment]
Oh nice didn't know that was an option, thank you.

Yeah making it default I think is better if it has the fade.

**Comment by RabbitB** [comment]
@Calinou It sounds to me like we need some sort of notification in there to the end user, to alert them to this functionality. Other menu-items have pop-up help/alerts when hovering the mouse over them, but it looks like these lack anything, so it might be a good stop-gap solution to add a hover item to those, until a better (more readily noticeable) solution can be designed.

**Comment by Anutrix** [comment]
Can this be closed since it seems that it is already supported(x-ray mode) and tooltip related to it was also added in #39365?

**Comment by Calinou** [comment]
@Anutrix I think so. In the future, we can consider making some gizmos use X-ray mode by default, but this needs to be further discussed. We don't want the default gizmo appearance to be too intrusive after all.

**Comment by Calinou** [comment]
Closing, as this feature is already available in Godot 3.2.x.
