### ISSUE TITLE
Add drag and drop of multiple files to exported arrays of type resource.

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot-proposals#718]
**Describe the project you are working on:**
Basic memory game. Flip 2 cards, see if they are right, move to the next 2... etc. Try and flip all cards in minimum moves.

**Describe the problem or limitation you are having in your project:**
For the pics on the cards, I would like to have texture 'sets' so the images displayed on the cards and be swapped out easily, like in an options menu. I would like to do this using a custom resource that has an exported (Array, Texture). Currently adding each of say, 100 textures would be cumbersome.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Drag and drop many files onto the editor button for arrays.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**I have already implemented this for the most part** on the current master branch, as below. I have not done extensive testing on what other interactions it can have that might be unwanted. How would be the best way to discuss the code I have written? Should I just submit a PR, get people to review, and update it as required? Or open an issue and post my code there, separately from a PR?

In the video I first add 3 files manually to the Array, and then add an additional 36 in 1 go. Note that the first 3 are not overridden... the code uses push_back(res) to maintain the existing list. This is because it is so easy to reset a list (set size = 0).

Open in new tab for better view.
![YVF9I0LENr](https://user-images.githubusercontent.com/41730826/79465731-157c8b00-803f-11ea-889e-e656cda62158.gif)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm not sure. 

One method I think that exists is doing an iteration of a directory, and doing `preload([files[0])`, similar to what is done in [the Godot docs](https://docs.godotengine.org/en/3.1/classes/class_directory.html). However, with the drag and drop method you can chop and change what is in the array really easily at any time, without all resources needing to be in 1 folder.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It would be a core editor feature.

**Comment by akien-mga** [comment]
Fixed by godotengine/godot#37965.
