### ISSUE TITLE
Add a node to easilly generate lightprobes in an Area

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot-proposals#7186]
### Describe the project you are working on

3D environment lighting

### Describe the problem or limitation you are having in your project

Currently, manually adding lightprobes is a pain. 

A node to fill an area with light probes would help a lot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A node for example LightProbesGroup which could have a box or sphere shape what allows to generate lightprobes in a subdivision light the LightmapGI does but also to be smart enough to not generate inside geometry.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Read above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

Could be

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-proposals/discussions/7190.
