### ISSUE TITLE
Mutex try_lock() makes no sense whatsoever.

### ISSUE THREAD

**Issue by darthLeviN** [godotengine/godot-proposals#7196]
### Describe the project you are working on

A project that might end up using mutex on the same thread.

### Describe the problem or limitation you are having in your project

try_lock makes no sense if the thread already owns the mutex.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

documentation says try_lock will return OK  if the thread already owns the lock. but it's supposed to return false on failure as well, which would translate into OK!!!

this is while unlock() says that this try_lock counts and you will need to call unlock after it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

PLAIN multithreading features. no funny businesses. you can even combine them with await. make it work just like mutex in c++. there is a reason why there are different mutexes. you should NOT try to simplify this. or it will lead to unreasonable consequences.

`mutex.lock()` : blocks the thread.
`mutex.lock_async()` : would work with await. will check every frame. will not block the whole thread.
`mutex.try_lock()` : would return false if mutex is locked. no matter where it is locked. will return true if operation succeeds.
`mutex.unlock()` : has to be called only ONCE.

i do not understand who made the current mutex. but it looks absolutely stupid.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no!

### Is there a reason why this should be core and not an add-on in the asset library?

common sense.

**Comment by AThousandShips** [comment]
> but it's supposed to return false on failure as well, which would translate into OK!!!

How do you mean? It returns true or false, if you're talking about 4.x

**Comment by AThousandShips** [comment]
> but it's supposed to return false on failure as well, which would translate into OK!!!

How do you mean? It returns true or false, if you're talking about 4.x (this was previously incorrect in the documentation but fixed by https://github.com/godotengine/godot/pull/78700)

> would return false if mutex is locked. no matter where it is locked

This would violate how the mutex underlying it works, and makes no sense, these mutexes are recursive

> i do not understand who made the current mutex. but it looks absolutely stupid.

Please keep your criticism constructive, and especially don't engage in ableist things like insulting peoples' intelligence

**Comment by darthLeviN** [comment]
so this is just a documentation error? then the documentation error needs to be fixed. because it was not changed.

![Screenshot_20230704_001726](https://github.com/godotengine/godot-proposals/assets/73083466/85fa39ce-bab0-4ec7-8668-f7437c1d0b0a)

I apologize if i sound rude but there is nothing much to document on a mutex. People actually need to rely on the documentation of the most basic features.

**Comment by AThousandShips** [comment]
You need to look at the latest, the stable hasn't been updated yet
https://docs.godotengine.org/en/latest/classes/class_mutex.html
