### ISSUE TITLE
Add a new type of StyleBox that draws other StyleBoxes

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#7203]
### Describe the project you are working on

A game using GraphEdit.

### Describe the problem or limitation you are having in your project

I have this StyleBoxFlat defining the style for a selected GraphNode in a GraphEdit:

<img width="300" alt="Screenshot 2023-07-04 at 1 54 45 PM" src="https://github.com/godotengine/godot-proposals/assets/1646875/f4a0e669-af3e-476f-97d6-a8534c7b676c">

I would like to add an outline to it when selected, like this:

<img width="300" alt="Screenshot 2023-07-04 at 1 55 33 PM" src="https://github.com/godotengine/godot-proposals/assets/1646875/95075c7b-7a52-428f-8703-bb70d72c9fcb">

However, since the first StyleBoxFlat uses the border for the lightly-colored title bar, and the second StyleBoxFlat uses the border for the outline, and StyleBoxFlat only supports one border, and there is no way to combine multiple style boxes, it's not possible to have both of these effects at the same time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a new type of StyleBox that can combine together other StyleBoxes, so that I can achieve this appearance:

<img width="300" alt="Screenshot 2023-07-04 at 1 55 51 PM" src="https://github.com/godotengine/godot-proposals/assets/1646875/f0870006-898d-4de5-8d8d-9cb614f16fd9">

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot/pull/79046

This PR implements a new StyleBox type called StyleBoxMulti that has an array of StyleBoxes and draws all of them.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

~~No, it can't be worked around in script. In order to implement a StyleBox that draws other StyleBoxes, you need to be able to call the engine's internal `draw` function from script, which is currently not possible.~~

### Is there a reason why this should be core and not an add-on in the asset library?

~~It should be in core because it can't be worked-around in script. If it's not in core, it will have to be done in a fork.~~

Also, StyleBox and its derivatives are core, so it makes sense to have a type that allows combining them in core.

**Comment by markdibarry** [comment]
Love it! This would be super helpful for message boxes:
![image](https://github.com/godotengine/godot-proposals/assets/21325943/117a13d5-e3cb-4bce-af25-84def5fc5ad2)

**Comment by YuriSizov** [comment]
> No, it can't be worked around in script. In order to implement a StyleBox that draws other StyleBoxes, you need to be able to call the engine's internal `draw` function from script, which is currently not possible.

Which `draw` function are you referring to? `StyleBox.draw` is exposed, https://docs.godotengine.org/en/stable/classes/class_stylebox.html#id1

You can also work around this by drawing any number of styleboxes within the control's `_draw` method.

**Comment by aaronfranke** [comment]
@YuriSizov You're right. Now I feel crazy, because I swear that wasn't working yesterday...

**Comment by aaronfranke** [comment]
@YuriSizov Never mind, it actually still doesn't work but the issue is different than I thought it was. The `draw` method can be called but it just does not work. I must have misremembered not being able to call it.

GDScript:

<img width="1595" alt="Screenshot 2023-07-05 at 11 21 31 AM" src="https://github.com/godotengine/godot-proposals/assets/1646875/76121bab-17d5-495e-8811-ecc83428239e">

C++:

<img width="1595" alt="Screenshot 2023-07-05 at 11 22 44 AM" src="https://github.com/godotengine/godot-proposals/assets/1646875/8878f272-5673-462a-8f68-e2ee9ece6d85">

**Comment by YuriSizov** [comment]
That seems to be a bug. It looks like it's calling a wrong `draw` method (not of the subtype that the stylebox actually has, but of the base type).

**Comment by aaronfranke** [comment]
@YuriSizov Never mind again, adding `@tool` to the script makes it work. So you were correct.
