### ISSUE TITLE
Add "value origin" to Range, to be used by Slider

### ISSUE THREAD

**Issue by dhoverml** [godotengine/godot-proposals#7207]
### Describe the project you are working on

Any Godot project with `Sliders`.

### Describe the problem or limitation you are having in your project

`Sliders` are currently limited to sliding only from left to right (for `HSlider`; even for RTL, which is arguably a bug but that's not the point of this proposal) or bottom to top (for `VSlider`).
It is possible to fake a `Slider` to slide right to left (or top to bottom) by rotating it, but it becomes hard to manage once it is used in a more complex scenario (like, within a `Container`, or scaled).
Additionally, the drawn area, Grabber Area, always extends from `min value` to `value`.  There's no way to draw from `max value` to value, or a value between min and max to `value`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a "value origin" to `Slider` (or more specifically, to `Range` which `Slider` uses).
The Grabber Area is drawn from "value origin" to `value`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

"value origin" acts as the name implies, the origin of `Sliders` `value`.
By default "value origin" is 0, and automatically clamped with the same logic as `value`.

Since this alone will break compatibility for any current `Slider` whose min < 0, there will also be an additional "use value origin".
When false, "value origin" is ignored.
When true, "value origin" is applied.
"value origin" can be assigned while "use value origin" is false, it just won't have any visual effect until "use value origin" is set to true.
"use value origin" is "false" by default.

I have an unsubmitted PR, here's a quick demo:
https://github.com/godotengine/godot-proposals/assets/135338122/c454f5ac-6b89-4dee-833e-d6699ab90b58

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, though it requires much more than a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?

It seems like a good enhancement to the current `Slider`.

**Comment by JoNax97** [comment]
I don't quite get the use case for this, even after watching the video

**Comment by RedMser** [comment]
As a less compatibility breaking alternative, why not have a enum dropdown where you choose between value origin "start" and "end"? Or call them "min" and "max" maybe. Could also include a "zero" choice if you think there's a use for it. Then the bool property isn't needed anymore.

I don't see use-cases for any in-between values.

**Comment by dhoverml** [comment]
The video demonstrates a slider that is offset from a position other than `min value`, not a use case for it.

Here's a possible use case:

You create a settings menu with some pre-hardcoded defaults which looks like this:
![example_part_1](https://github.com/godotengine/godot-proposals/assets/135338122/710ad4b2-4b76-4809-b123-53e2dc413b9c)

When the user adjusts the sliders, they can end up looking like this:
![example_part_2](https://github.com/godotengine/godot-proposals/assets/135338122/a526a558-b77c-4c21-bddb-c60574d4b80d)

However, maybe you wanted to convey to the user how far the slider was adjusted from the default value (the "default value" is the "value origin").
So instead, the sliders initially looked like this:
![example_part_3](https://github.com/godotengine/godot-proposals/assets/135338122/4911f494-8db2-4408-a516-587ba346c4dc)

And after sliding them, they now look like this:
![example_part_4](https://github.com/godotengine/godot-proposals/assets/135338122/b3d8c0e7-e084-4a38-a737-2cfce2be9647)

This tells the user two things at a glance:
1. Setting(s) were changed
2. The magnitude of each changed setting (or conversely, how much will change when `Reset` is pressed)

There's many ways to do the same thing, as in, there are other ways to convey the same information to the user without this proposal.  Also, it may not be necessary to convey this message.  The purpose is to give the designer and programmer another option when designing the menu.

> As a less compatibility breaking alternative
As far as I can tell this won't break compatibility in the sense that existing sliders will be unaffected both visually and how they behave.  Though yes it will break existing ABIs.

**Comment by dhoverml** [comment]
Thanks for the feedback @RedMser and @Calinou .
The change to make this happen is relatively large (a few files, but a lot modified), so I'll hold off on submitting a PR.  If there's more interest shown then I'll look into reviving it.

If it is revived, I'll look into using a dropdown like @RedMser suggested since the bool is kind of disjointed UX-wise.

I did see some bugs while playing around with it, though I don't know when I'll find time to report those bugs.  I want to re-verify them before saying what they are since I could've been the cause.
