### ISSUE TITLE
Provide signtool.exe path in UWP Export for automatic signing.

### ISSUE THREAD

**Issue by crazychenz** [godotengine/godot-proposals#721]
**Describe the project you are working on:**
All projects that I want to use UWP Export with.

**Describe the problem or limitation you are having in your project:**
I'm required to run signtool for all UWP exports. This is acknowledged as the current state of godot in the documentation as well. BUT, there is already a field for the certificate and password in the editor window.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Allow the user to provide the path of the signtool.exe so Godot may automatically run the signature portion of the application.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Simply add a signtool.exe path field to the UWP export configuration (not unlike the ADB path field for Android exports). Godot would then execute the signtool with a given format:
`signtool.exe sign /fd SHA256 /a /f CERTIFICATE_PATH / CERTIFICATE_PASSWORD GODOT_APPX_OUTPUT`
The certificate path and certificate password are already provided fields. Only the signtool.exe path field would need to be added to the user interface.

Note: The user would still be required to generate their own private key, certificate, PFX. But that is a one time thing, versus the need to resign an APPX every single time its exported.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I currently handle this with an external CI process, but could easily be added to core export tools to match the user experiences found with other export platforms.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a change to the UWP platform export that is already in core.

**Comment by bruvzg** [comment]
`signtool` path for UWP export can be set in `Editor Settings` ⇒ `Export` ⇒ `UWP` (it's only available when exporting from Windows).

`signtool` (Windows only) and `osslsigncode` (for exporting from non-Windows platforms) path can be for Windows exports (`Editor Settings` ⇒ `Export` ⇒ `Windows`), I'm not sure `osslsigncode` is capable of signing UWP apps.

**Comment by crazychenz** [comment]
@bruvzg Perfect. That worked. Thanks! I suppose that just needs to be added to the documentation.

Not sure how to report documentation requests.

**Comment by bruvzg** [comment]
> Not sure how to report documentation requests.

Documentation is in this repo: https://github.com/godotengine/godot-docs

**Comment by crazychenz** [comment]
Thanks. Closing this proposal.
