### ISSUE TITLE
Show only compatible nodes in "Select a node" window

### ISSUE THREAD

**Issue by martinboue** [godotengine/godot-proposals#7217]
### Describe the project you are working on

A 2D top-down racing game (https://martinboue.itch.io/drifting-trailer), but same issue apply on my other projects.

### Describe the problem or limitation you are having in your project

When selecting a node in the "Select a node" window, opened from the inspector, finding the node I'm looking can be tricky.
In big scenes with many nodes, the tree/node list is polluted with non-compatible nodes that cannot be selected.

![image](https://github.com/godotengine/godot-proposals/assets/28391199/6d04663a-0278-4e9f-9239-8a7e032638f1)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A filter to hide incompatible nodes would solve this issue. This filter could take one of two forms:

1. Switch button "Show only nodes of type { MyNode }". 
2. Dropdown with all the node types extending { MyNode }, so we could choose a specific Node type from all the compatible ones.

The filter could be added between the current filter by name and the start of the list. It would look like something like this:
![proposal](https://github.com/godotengine/godot-proposals/assets/28391199/d25cecf2-7d6c-4bfb-a040-e8e2a5de5574)

For the 2nd option, it could be something like this instead:
![proposal2](https://github.com/godotengine/godot-proposals/assets/28391199/af3ddd1f-fc47-4b8e-9c9c-5d5909654acc)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For each option:
1. When unchecked, the behavior would be the same as now. When checked, the tree would only show compatible nodes and their parents.
2. When nothing is selected, the behavior would be the same as now. When a node type is selected, only the nodes of the selected type and their parents would be shown in the tree.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It could be helpful for everyone, and it's not going to bother the one not using it.

**Comment by Calinou** [comment]
I prefer the first option as it still allows seeing the tree structure.

**Comment by martinboue** [comment]
I may have wrongly explained the 2nd option. I was imagining a more precise filter where you can select a specific node type in case the compatible type is extended. In my example, I had a base class "Checkpoint" and some other class extending the base one, "SimpleCheckpoint", "SquareCheckpoint", etc. The image represents the options of this filter, not the result in the tree. The result with the 2nd option would still be the tree structure.

To sump up, the difference between option 1 and 2 is the filter, 1st is a switch and 2nd is a dropdown/option button.

**Comment by martinboue** [comment]
I created a PR with the 1st option: https://github.com/godotengine/godot/pull/79213
