### ISSUE TITLE
ColorPicker RGB from 0 to 1 option

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot-proposals#7227]
### Describe the project you are working on

App from tracking user physical exercise progress.

### Describe the problem or limitation you are having in your project

To create a custom `Theme`, I would like to explore [predefined colors](https://docs.godotengine.org/en/stable/classes/class_color.html#constants). However, their are given in RGBA from 0 to 1 and the color picker goes from 0 to 255.

The transformation is simple, but annoying.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest to add the possibility to select RBGA values from 0 to 1.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Another button in the `ColorPicker `to turn on this option in the section with the buttons RGB, HSV and RAW.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not with a script, but with a calculator if you want to set the colors from the inspector.

### Is there a reason why this should be core and not an add-on in the asset library?

For simplicity and completeness.

**Comment by theraot** [comment]
Is writing the color in RAW not good for you?

**Comment by acgc99** [comment]
Is that RBGA from 0 to 1? I don't know too much about colors in computers, but I saw that RGB values in RAW could be bigger than 1, so I discarded it.

After your comment, I suppose it is some kind of extension/generalization.

**Comment by theraot** [comment]
You can consider it an extension.

If you write a values in RAW, the RGB will be that RAW value but multiplied by 255.

So RAW between 0 and 1 behaves like RGB between 0 and 255.

**Comment by acgc99** [comment]
Nice, thanks!
