### ISSUE TITLE
"Smart" project version warnings

### ISSUE THREAD

**Issue by MIfoodie** [godotengine/godot-proposals#7254]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

N/A

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When you are opening a project with a version of Godot that the project wasn't originally created with, you get this error. 

![image](https://github.com/godotengine/godot-proposals/assets/94649676/396e8e97-2773-495c-99a7-2cf0786c9904)

Godot should be "smart" and look at the two different version numbers and figure out which one is bigger than the other one and then change the wording of the warning to be "Opening will upgrade the project to Godot X.Y" or "Opening will downgrade the project to Godot X.Y" rather then "Opening will upgrade or downgrade the project to Godot X.Y".

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. User tries to open a project with a version number that does not match the current Godot version number. 
2. Godot check to see what version number is bigger, the project version number or the engine version number
3. If the project version number is bigger, Godot will set the warning to "Opening will upgrade the project to Godot X.Y". If the engine number is bigger, Godot will set the warning to "Opening will downgrade the project to Godot X.Y"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

(I'm not really sure)

### Is there a reason why this should be core and not an add-on in the asset library?

It is in the project browser not a project...

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/79096.

**Comment by MIfoodie** [comment]
> * Related to [Version upgrade/downgrade confirmation dialog buttons misaligned godot#79096](https://github.com/godotengine/godot/issues/79096).

Wow you're fast 😄.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/79299
