### ISSUE TITLE
Add a built-in way to build export templates with size optimizations

### ISSUE THREAD

**Issue by IoneGod** [godotengine/godot-proposals#726]
![optimize](https://user-images.githubusercontent.com/59492619/82750978-1e424880-9dc5-11ea-9878-b4b4be010fdc.png)

**Describe the project you are working on:**
A simple 2d side scrolling game for android

**Describe the problem or limitation you are having in your project:**
Unable to otimize game for size using scons 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding an Optimization Panel in the project settings 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
With an Optimization Panel developers can remove things they dont need instead of having to use scons from Command line and this will also bring opportunities for speed optimization

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No it cannot  be used

**Is there a reason why this should be core and not an add-on in the asset library?:**
Optimizations cannot be added to the engine through addons

**Comment by Jummit** [comment]
> Unable to otimize game for size using scons
Did you try this tutorial: https://youtu.be/ieTSAlbFmuY

**Comment by aaronfranke** [comment]
So what you're asking for is the ability for Godot to have an in-editor way to recompile the engine with scons to optimize your exported games, rather than having to do it [manually](https://docs.godotengine.org/en/latest/development/compiling/index.html).

This is not really trivial to do, for example, if you're on Windows, this feature would likely require you to have the Visual Studio build tools installed.

**Comment by Calinou** [comment]
By the way, removing unused modules won't help improve performance. It will only help decrease file size.

**Comment by iapps207** [comment]
> 
> 
> By the way, removing unused modules won't help improve performance. It will only help decrease file size.

Reducing file size would also be a good thing especially for Mobile game developers

**Comment by iapps207** [comment]
Okay I saw somebody else post about this and added a new picture to depict what I am saying and really beginners might have problems using scons and even pros thats why I guess this method is better @Calinou

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/62996 makes it possible to automatically generate a build configuration file with unused features disabled. That said, the build process itself remains manual.

**Comment by YuriSizov** [comment]
I think we can close this as a reasonable implementation for the proposed idea. Creating some sort of UI for scons that would be a part of the editor is not a hard requirement, as using scons is pretty easy as is. Setting up the dev environment still requires some consideration on the user part beforehand, and I don't think we can reasonably hide all that complexity without spend too much time on it.

If there are ideas for how that can work, then we need a more detailed proposal for that specifically. Also keep in mind that you can't rebuild the editor that you are currently running.
