### ISSUE TITLE
Add `LocalizedString` type for in-editor locale preview

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot-proposals#7285]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

I need to run the game to test localizations after modifying nodes and I don't enjoy this workflow.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot should be able to provide locale preview in the **editor** like **Unreal Engine** ([Youtube Link](https://www.youtube.com/watch?v=ZOSOFd67WC8&t=14s)).

To make it possible, I propose a new `String`-like type called `LocalizedString`, created with the **msgid** and responsible for fetching the current locale representation (**msgstr**).

1. In the **editor**, nodes with `LocalizedStrings` would normally show the **msgid**, but when a hotkey is kept pressed (like `Ctrl+T`), it shows the **msgstr** (of all `LocalizedStrings`);
2. In the **game**, `LocalizedStrings` shows the **msgstr** and fallbacks to the **msgid**.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The proposed preview could be visually similar to what **Unreal Engine** offers: [Youtube Link](https://www.youtube.com/watch?v=ZOSOFd67WC8&t=14s).

Below is a GDScript snippet of how `LocalizedString` could work in code.

<details> 
  <summary>Click to expand the code.</summary>

```gdscript
"""
For the example, assume these informations:

# en.po
msgid "beginner"
msgstr "Beginner"

# pt_BR.po
msgid "beginner"
msgstr "Novato"

# current locale = ru
"""

extends Control

const _CHARACTER_CLASS_DEFAULT := t'beginner' # or `LocalizedString('beginner')`

@export var character_class : LocalizedString # Display the property in the Editor Inspector similarly to `String` properties.

@onready var _character_class_lbl : Label = $margin/h_box/class_label

func _ready() -> void:
  if character_class.is_empty():
    character_class = _CHARACTER_CLASS_DEFAULT
  
  _character_class_lbl.text = character_class # `Label::text` is a `LocalizedString` too (proposal)

  print(character_class) # prints 'beginner'. (ru locale not found, fallback to `msgid`)
  print(character_class.get_msgid()) # prints 'beginner'

  print(character_class.get_locale_representation()) # prints '' (ru locale not found, fallback to '')
  print(character_class.get_locale_representation('en')) # prints 'Beginner'
  print(character_class.get_locale_representation('pt_BR')) # prints 'Novato'
```

</details>

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Part of it can be implemented by scripting, but the full solution requires built-in types like `Label` and `Button` to also use `LocalizedStrings`.

### Is there a reason why this should be core and not an add-on in the asset library?

The feature should be in the core to replace each `String` that the "user can modify and is auto-translated" with `LocalizedString`, as the **editor's** feature to preview locales will work along with `LocalizedStrings`.

**Comment by YuriSizov** [comment]
> Godot's localization capabilities in the **editor** are not user friendly.

Could you elaborate on that?

**Comment by felaugmar** [comment]
> > Godot's localization capabilities in the **editor** are not user friendly.
> 
> Could you elaborate on that?

I explained better.

**Comment by felaugmar** [comment]
I've updated the proposal with more information, I hope it's clearer.
