### ISSUE TITLE
Add a setting to enable or disable dragging and dropping text with the mouse in LineEdit and RichTextLabel

### ISSUE THREAD

**Issue by danny88881** [godotengine/godot-proposals#7297]
### Describe the project you are working on

I am working on a game that makes heavy use of TextEdit, LineEdit, and RichTextLabel.

### Describe the problem or limitation you are having in your project

While I am able to disable the dragging and dropping feature on TextEdit, both LineEdit and RichTextLabel still have this feature enabled creating an inconsistency.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The feature would be an option to disable this behavior on LineEdit and RichTextLabel just like the drag_and_drop_selection_enabled property of TextEdit.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Extend the drag-and-drop option of TextEdit to LineEdit and RichTextLabel

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I am aware of

### Is there a reason why this should be core and not an add-on in the asset library?

The feature already exists for the TextEdit node.

**Comment by KoBeWi** [comment]
If you don't need other mouse features, you can set `mouse_filter` to IGNORE.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/79563.
