### ISSUE TITLE
Saving a script in a separate window doesn't make the focus on the main window

### ISSUE THREAD

**Issue by jordanlis** [godotengine/godot-proposals#7298]
### Describe the project you are working on

2D plateformer

### Describe the problem or limitation you are having in your project

1. I separate the script window
2. I put the script window on a separate windows virtual desktop 2 (main window is on virtual desktop 1)
3. I code and save with ctrl + S
4. The focus is made on the main window on the first virtual desktop

![script_save](https://github.com/godotengine/godot-proposals/assets/68544949/9893b9d5-28fe-493d-b2ed-68acf49a4e74)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like that the focus doesn't force the OS to switch to the first virtual desktop. 
It means that somewhere, it implies that no focus is made on the main window. 

I can save my script 100 times in 10 min of work so this is very important for the workflow

Another linked issue is maybe that the debugger is not on the script window, but I'll make another proposal. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. I save
2. The focus stays on the script windows

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

Because it's linked to the script editor and the separate window feature.

**Comment by KoBeWi** [comment]
This is a bug: https://github.com/godotengine/godot/issues/78672
As a workaround, change your Save Script shortcut to Ctrl+S (it's Ctrl+Alt+S by default). Normally Ctrl+S saves the scene, which causes focus loss.
