### ISSUE TITLE
Boot Splash Improvements

### ISSUE THREAD

**Issue by iapps207** [godotengine/godot-proposals#730]
**Describe the project you are working on:**
A 2d game for android

**Describe the problem or limitation you are having in your project:**
I want to add my company logo under the Godot logo and change the background to an image instead of just a color

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Under the project settings in the boot splash menu 
 there should be a list of images  something like
![BootSplash](https://user-images.githubusercontent.com/59492619/79639177-f5091980-8181-11ea-9415-061b5eafbd91.PNG)
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The images will be arranged according to the list in the boot splash and have a background image instead of just a color as stated looking like 
![Asteroid Blast](https://user-images.githubusercontent.com/59492619/79683126-b45fdd80-821f-11ea-8078-c9cb033173e9.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No it cannot

**Is there a reason why this should be core and not an add-on in the asset library?:**
The boot splash is already a core project setting

**Comment by Nolkaloid** [comment]
Just replace the whole splash screen with a custom image.

**Comment by iapps207** [comment]
A custom image in which I will probably like to remove the Godot logo because its just more work which means no promotion for Godot engine

**Comment by iapps207** [comment]
> 
> 
> Just replace the whole splash screen with a custom image.
A custom image in which I will probably like to remove the Godot logo because its just more work which means no promotion for Godot engine

**Comment by Nolkaloid** [comment]
Not to be mean or anything but getting an image of the Godot logo and slapping that into Gimp or Photoshop doesn't seem like a lot of work to me. Implementing this feature kinda does...

**Comment by LikeLakers2** [comment]
I can't see this feature being added, as the amount of work it would take to implement this feature would be much higher, compared to just asking people to take the couple extra moments to drag the Godot logo into Photoshop.

However, if you want to avoid putting Godot's logo in (even if it's because we won't add a feature for you), that is your choice, and we will not stop you. Godot's community already grows on its own from the exposure it already has.

**Comment by Calinou** [comment]
I'll close this proposal due to lack of support (see the reactions on the first post). Moreover, this feature would be difficult to integrate to existing splash screens which generally follow their own guidelines when it comes to spacing and stuff like that.
