### ISSUE TITLE
Avoid copying nothing to the clipboard when pressing Ctrl+C with nothing selected

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot-proposals#7307]
### Describe the project you are working on

A mobile app.

### Describe the problem or limitation you are having in your project

When I want to copy and paste some code in the editor, I first do `Ctrl+C` and then, sometimes, by mistake, I press `Ctrl+C` again instead of `Ctrl+V`. Assuming there is no code selected when `Ctrl+V` was intended to be pressed, an empty string will be copied to the clipboard.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If there is nothing selected and you press `Ctrl+C`, don't copy an empty string to the clipboard, just pass.

This feature is implemented in many other text editors.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just change `Ctrl+C` behavior.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, I don't think you can solve it with an add-on.

**Comment by KoBeWi** [comment]
Ctrl+C without selection copies the current line.

**Comment by acgc99** [comment]
I personally would prefer the behavior I proposed for ``Ctrl+C` and another key combination for select current line (to avoid the mistakes I described).

**Comment by Calinou** [comment]
> I personally would prefer the behavior I proposed for ``Ctrl+C` and another key combination for select current line (to avoid the mistakes I described).

Most text editors nowadays copy the current line if you have no selection. We shouldn't change this shortcut as it's important to be consistent with popular editors out there, such as Visual Studio Code and JetBrains IDEs.
