### ISSUE TITLE
Crutch for outside editor code generation issue

### ISSUE THREAD

**Issue by kastromatos** [godotengine/godot-proposals#7314]
### Describe the project you are working on

Your first 2D game Godot tutorial, "Dodge the Creeps!" game.

### Describe the problem or limitation you are having in your project

Old one known bug: [Creating signals generates no code in external editor.](https://github.com/godotengine/godot/issues/41283)
Create signal action in Godot not create related code section in external editor, VS 2022 in my case. Probably it is C# specific issue.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

"Connect a Signal to a Method" window should have additional section where generated template is shown. You can copy&paste template and use it outside of Godot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/52923643/e101e847-c5fd-4ac8-85ed-3640229721a3)

![image](https://github.com/godotengine/godot-proposals/assets/52923643/0c13f89d-cbf7-4797-914b-5144068c42b8)

Or the same way as for turned on advanced option, but with code snippet: 
![image](https://github.com/godotengine/godot-proposals/assets/52923643/104d2445-cfb4-47e9-ab8d-c1dee7d7a5e1)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It should be part of Godot mono, because in most cases C# is used with external editor.

### Is there a reason why this should be core and not an add-on in the asset library?

[No code generation issue](https://github.com/godotengine/godot/issues/41283) totally ruin experience for C# newcomers, it is a brick wall you cannot go through on very first steps in tutorial.

**Comment by kastromatos** [comment]
Two main points:

- issue totally blocks C# newcomers on very first tutorial steps, which is very strange supposed official C# Godot support
- original bug already lives for 3 full year and fix still not expected

For me it is relatively easy implementable feature, which should be documented as official workaround for external editors, such as VS and VS code. It is not fixing the root cause but unblocks novices and allow them to move further.

**Comment by AThousandShips** [comment]
What I mean is that I think it's not the best approach to add a temporary fix instead of prioritising fixing the actual issue, as from that issue report the idea is to make it work correctly, not leave it as is

**Comment by kastromatos** [comment]
@AThousandShips  you are right, of course. That is why I called this issue 'crutch'. How hard is to fix initial issue? Is there some fundamental problem with it? I don't know answers and proposed workaround for this. For some reason initial issue was removed from 4.1 roadmap and milestones. Is it possible to somehow highlight it and include into plans for future mono releases?

**Comment by AThousandShips** [comment]
I don't know why it was removed from that, but no one seem to be working on it right now, so we can't really schedule a fix for it, it needs someone to pick up the issue to solve it

**Comment by rickygai** [comment]
Actually, I understand this is four years old problem, not one year ago story. Therefore, I created a new post. Thank you all for the feedback, will look into #3633 for sure. I asked the forum, well someone asked to fix it myself which I am not that expert to do so honestly, and eventually I leave Godot for sometime, waiting this issues to be solved one day.
