### ISSUE TITLE
Remove AcceptDialog to auto create tiles.

### ISSUE THREAD

**Issue by thiagola92** [godotengine/godot-proposals#7327]
### Describe the project you are working on

Learning to make isometric games.

### Describe the problem or limitation you are having in your project

I downloaded one of the Kenny assets (https://kenney.nl/assets/sketch-town) and the tiles came separeted.

![Many tiles from the kenny asset](https://github.com/godotengine/godot-proposals/assets/9352894/3b5e10cb-8411-4885-aa82-3a9eb85a9575)

When moving all tiles to TileSet there is **no** AcceptDialog asking me to auto create tiles, but when moving one tile the AcceptDialog appears.

![AcceptDialog window asking to create auto tiles](https://github.com/godotengine/godot-proposals/assets/9352894/5ba23d7d-5f21-4ef9-9cdf-4d4fe47f768d)

This means that i would have to go one by one adding the tile.  
If someone doesn't want to auto tile, this person also needs to go one by one to add tile.  

```mermaid
flowchart TD
  drag_many_tiles[Drag many tiles to TileSet]
  needs_auto_tile[Needs auto tile?]
  edit_one_by_one1[Edit one by one to add tile]
  edit_one_by_one2[Edit one by one to add tile]

  drag_many_tiles --> needs_auto_tile
  needs_auto_tile --yes--> edit_one_by_one1
  needs_auto_tile --no--> edit_one_by_one2
```

This problems is also mentioned in issues like:  
1- https://github.com/godotengine/godot/issues/69273  
2- https://github.com/godotengine/godot/issues/79473  

Following with PRs to solve this problem:
1- https://github.com/godotengine/godot/pull/70790  
2- https://github.com/godotengine/godot/pull/79558  

First PR try to solve by remembering all tiles added, opening the AcceptDialog and auto tiling them.  
Second PR try to solve by auto tiling if it's Texture have the same size as the TileSet.  

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would prefer just to remove the AcceptDialog and always try to auto tile.

```mermaid
flowchart TD
  drag_many_tiles[Drag many tiles to TileSet]
  needs_auto_tile[Needs auto tile?]
  do_nothing((end))
  remove_auto[Edit one by one to remove auto tile]
  add_tile[Edit one by one to add tile]

  drag_many_tiles --> needs_auto_tile
  needs_auto_tile --yes--> do_nothing
  needs_auto_tile --no--> remove_auto
  remove_auto --> add_tile
```

Having many tiles with different sizes would probably be the worst case. We could have an option to disable the auto tile but i would prefer not to be an AcceptDialog, maybe some toggle button anywhere (like settings).

Why i'm proposing to remove? I'm a newbie in C++ and i would prefer the code to remain simple.

The first propose (https://github.com/godotengine/godot/pull/79558) is not simple. Shouldn't exist necessity to temporarily store the new atlas to clear right after... It should know if needs to auto create at the moment that is added, like passing a parameter to a function.

The second propose (https://github.com/godotengine/godot/pull/79558) forgot that there is two ways to add atlas: drag & drop, plus button.

![Plus button](https://github.com/godotengine/godot-proposals/assets/9352894/45d19bee-f2d3-4ff0-96d6-798361d7d4d8)  

Each one making almost the same thing.  
https://github.com/godotengine/godot/blob/master/editor/plugins/tiles/tile_set_editor.cpp#L49-L88  
https://github.com/godotengine/godot/blob/master/editor/plugins/tiles/tile_set_editor.cpp#L227-L249  

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/thiagola92/godot/commit/c3f878698df7df72dce0e00703ab63188c7ddde3?diff=unified  
Ignore changes to tile_set_editor.cpp and tile_set_editor.h, I was testing merging two functions.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe not

### Is there a reason why this should be core and not an add-on in the asset library?

This change a core mechanic.

**Comment by KoBeWi** [comment]
The dialog needs to exist, because you don't always want the automatically created tiles. The created tiles are 1x1 and you may want bigger tiles.

As for your problem, I'd suggest merging all tiles into one tileset. A TileSet where every source is a single tile isn't very usable...

**Comment by thiagola92** [comment]
> The dialog needs to exist, because you don't always want the automatically created tiles. The created tiles are 1x1 and you may want bigger tiles.

Sorry, I'm not sure i understand. Bigger tiles wouldn't mean that you would have to manually change anyway?

> As for your problem, I'd suggest merging all tiles into one tileset. A TileSet where every source is a single tile isn't very usable...

My intention was to merge using Godot merging tool but it can't be made fast without auto tiling. Example:

[godot_no_auto_tile.webm](https://github.com/godotengine/godot-proposals/assets/9352894/2c18a2fb-7308-4e71-b98a-fdce82e1198f)

But if apply auto tiling for everyone, can go much faster:

[godot_auto_tile.webm](https://github.com/godotengine/godot-proposals/assets/9352894/d5dcc516-9cf6-4c36-a083-74bf86c1d88d)

**Comment by KoBeWi** [comment]
> Bigger tiles wouldn't mean that you would have to manually change anyway?

You can make tiles bigger than 1x1:

https://github.com/godotengine/godot-proposals/assets/2223172/560f1b18-2b87-40ca-8d30-fe0527f18711

If the tileset is filled automatically, it means you'd need to first delete the small tiles and then create bigger tiles. It would be very inconvenient.

> My intention was to merge using Godot merging tool but it can't be made fast without auto tiling.

tbh I don't know the use-case for the atlas merging tool, but I think it's faster to use an external tool, at least for merging single tiles. You could use e.g. https://github.com/KoBeWi/Godot-Spritesheet-Generator, just set the margin to 0.

**Comment by KoBeWi** [comment]
The author of that PR is inactive for a long time, so feel free to take over.
Closing this in favor of https://github.com/godotengine/godot/issues/69273

**Comment by rakkarage** [comment]
"The dialog needs to exist, because you don't always want the automatically created tiles. The created tiles are 1x1 and you may want bigger tiles."

Is there any reason to show the dialog when a 1x1 image is dragged in? It seems implied since there is only one thing possible to do?
