### ISSUE TITLE
Allow INSTANCE_CUSTOM to be accessed in fragment shaders

### ISSUE THREAD

**Issue by Moonzel** [godotengine/godot-proposals#7340]
### Describe the project you are working on

I am currently working on developing a bullet hell system using c++ and rendering te bullets via a MultiMeshInstance2D node. In order to animate each of the bullets, I am trying to use INSTANCE_CUSTOM to change the UV of the texture (spritesheet) in a shader to effectively animate the bullet. However, it seems the INSTANCE_CUSTOM data cannot be accessed in the fragment shader, making this much harder.

### Describe the problem or limitation you are having in your project

I cannot access the data from INSTANCE_CUSTOM in the fragment shader.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It allows developers to use INSTANCE_CUSTOM in all of the canvas_item function rather than limit it to the vertex shader. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I do not know much about developing the engine, so I do not have much to show for actual code, but here is what it could look like. 
`void fragment() {
     float x = INSTANCE_CUSTOM.r
     COLOR = vec4(x,x,x,1.0)`

This is not the context I use it in, but this is what it could look like to other users. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If there is a workaround, I do not know about it, and would happily use it. I am here because I could not find one. 

### Is there a reason why this should be core and not an add-on in the asset library?

This would be core.

**Comment by AThousandShips** [comment]
Can't you just forward it through a varying?

**Comment by AThousandShips** [comment]
Something like:
```
varying flat vec4 custom;

void vertex() {
    custom = INSTANCE_CUSTOM;
}
```

**Comment by Moonzel** [comment]
> can't be easily passed to the fragment function

Ok, I do understand that not enough people would use this, assuming there is a lot of work to do with it. However, I would say that maybe mentioning this in the documentation would not be a terrible idea.

**Comment by AThousandShips** [comment]
That is mentioned in the shader reference, as you can see in that link, so I think it's a detail that would be excessive to add

**Comment by Moonzel** [comment]
The logic here makes sense. Closing the Issue.
