### ISSUE TITLE
Add a project setting to import glTF materials from Blender as placeholders

### ISSUE THREAD

**Issue by pemguin005** [godotengine/godot-proposals#7341]
### Describe the project you are working on

Any 3D game, where your 3D assets have materials in blender (such as ones that help you with sizing/aligning UV measurements and mappings), but you'd rather use in-engine materials once the model is in godot.

### Describe the problem or limitation you are having in your project

Currently Godot auto autoimports the .blend file using .gltf, and exported materials. Imports are larger because they have those materials included, and there is no intention to use those materials in the game.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By adding a checkbox "Placeholder Materials" to the blender import options in the preferences, it could add to the import flags to use placeholders only. This would reduce import sizes, and speed up workflow.

As it stands currently I either have to export manually my gltfs with placeholders to bring them in myself andnimpoet into Godot, or I have to accept that it's going to automatically import the materials, so I must disconnect the blender materials first before saving into Godot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The simple checkbox in the preferences, could add flags to the export command that Godot uses when calling blender to export the gltf. That way it would by default export without materials and always placeholders.

There are a few proposals here about import materials already, but they're requesting more complex replacements of blender materials with in-game materials. That would be a more complex implementation, this is a nice halfway point.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I imagine this would get a lot of use by others making 3D assets that want to get UV measurements/looks correct in blender, but want to use in-game materials to keep their games more performant and sizes down.

### Is there a reason why this should be core and not an add-on in the asset library?

No, it's more of a core import setting option.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/7238.

**Comment by pemguin005** [comment]
Thisngot renamed to reference the advanced import dialogue. I'm not proposing this change be in that importer, but in the global project settings.

![Screenshot_20230720-134230](https://github.com/godotengine/godot-proposals/assets/43008564/29acb6b9-8e7d-41cf-a8ee-47e8c4d96d5c)

**Comment by Calinou** [comment]
> (Because blender files saved into the project path get auto imported without seeing the advanced import menu)

Not everyone is using the Blender import workflow, and your change sounds logical for other 3D scene formats (such as glTF). I wouldn't restrict the feature to Blender if it can be made to work with other 3D formats.

Internally, Blender files are imported as glTF by calling the Blender glTF exporter.

**Comment by Calinou** [comment]
Nevermind, I realized you're referring to this option from the Blender glTF export dialog:

![Uploading image.png…]()

**Comment by pemguin005** [comment]
I apologize for not sending a screenshot, I was away from from my computer (but thanks to the Godot for Android I speedily installed on the go, I was able to get that settings screenshot for my last comment).

If the "remember export settings" options works, then that will eliminate entirely the need for any changes to Godot. I'll test and return here soon to confirm.

**Comment by pemguin005** [comment]
Turns out changing checking the "remember my settings" option in blender does not solve the issue.

But **what does solve it** is simply double clicking the blend file in godot to open the reimport menu referenced earlier, and under the materials section, changing it to "placeholder." After that setting change, every time you save your blend file, and the export updates in Godot, it remembers your import preference to only use placeholders. 

So turns out Godot will remember that import setting so even though i have materials used in blender, Godot knows to strip those at import. The feature I wanted already exists then. :)

![Screenshot_20230720_161500](https://github.com/godotengine/godot-proposals/assets/43008564/bfed04a7-5e86-4077-8da0-f5201c4b6397)
