### ISSUE TITLE
Add iOS Android pen pressure / tilt support

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot-proposals#735]
**Describe the project you are working on:**
HEAVYPAINT - Multiplatform graphic painting app [www.heavypoly.com/heavypaint](url)
[](https://www.instagram.com/explore/tags/heavypaint/)
**Describe the problem or limitation you are having in your project:**
pen pressure / tilt not working on Android or iOS
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
add pen pressure/tilt support for iOS/ (iPad pro) and Android (Samsung note 9 pen)
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
same as how desktop versions work now
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no
**Is there a reason why this should be core and not an add-on in the asset library?:**
should behave the same as desktop

**Comment by Fonden14** [comment]
Just adding my support for this, and in addition specific support for the Samsung S-Pen(there's a couple different versions across their phones/tablets, but I'm not sure if there's any difference in function relating to pressure sensitivity in apps). 

If this comment is inappropriate to leave here feel free to delete.

**Comment by Calinou** [comment]
@Fonden14 Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by ModProg** [comment]
I would like to work on this for Android.
What I found so far:
- Pressure is obtainable in [MotionEvent.getPressure](https://developer.android.com/reference/android/view/MotionEvent#getPressure(int)).
- in Java:
  - This could be stored in `arr` in [GodotInputHandler.java:187](https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/platform/android/java/lib/src/org/godotengine/godot/input/GodotInputHandler.java#L187) as a 4th value and passed to `GodotLib.touch` in ln. [207](https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/platform/android/java/lib/src/org/godotengine/godot/input/GodotInputHandler.java#L207).
  - It should also be passed in ln. [493](https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/platform/android/java/lib/src/org/godotengine/godot/input/GodotInputHandler.java#L493) & [508](https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/platform/android/java/lib/src/org/godotengine/godot/input/GodotInputHandler.java#L508)
- in cpp:
  - `TouchPos` needs a pressure field [display_server_android.h:43](https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/platform/android/display_server_android.h#L43)
  - `env->GetFloatArrayRegion` needs to be called with size 4 [java_godot_lib_jni.cpp:246](https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/platform/android/java_godot_lib_jni.cpp#L246), pressure also needs to be set for `tp` below
  - in [display_server_android.cpp:627](https://github.com/godotengine/godot/blob/ee44982c4526a2823543d4e9eca5d4e566d645af/platform/android/display_server_android.cpp#L627) `env-> set_pressure()` needs to be called. (prob not in ln. [676]() as that's for hover)
  - in ln. [570](https://github.com/godotengine/godot/blob/ee44982c4526a2823543d4e9eca5d4e566d645af/platform/android/display_server_android.cpp#L570) & ln. [645](https://github.com/godotengine/godot/blob/ee44982c4526a2823543d4e9eca5d4e566d645af/platform/android/display_server_android.cpp#L645) `ev->set_pressure()` needs to be called (not implemented yet)
  - `InputEventScreenTouch` needs a pressure_field [input_event.h:415](https://github.com/godotengine/godot/blob/6054febddea116a170205547e97a00744ce2801a/core/input/input_event.h#L415) and implementation in [input_event.cpp:1082](https://github.com/godotengine/godot/blob/6054febddea116a170205547e97a00744ce2801a/core/input/input_event.cpp#L1082).
  - Same for `InputEventScreenDrag` [display_server_android.cpp:613](https://github.com/godotengine/godot/blob/ee44982c4526a2823543d4e9eca5d4e566d645af/platform/android/display_server_android.cpp#L613), [input_event.cpp:1139](https://github.com/godotengine/godot/blob/6054febddea116a170205547e97a00744ce2801a/core/input/input_event.cpp#L1139) & [input_event.h:441](https://github.com/godotengine/godot/blob/6054febddea116a170205547e97a00744ce2801a/core/input/input_event.h#L441).


These would than need to be made availible for GdScript as well I would expect, but I'm not that experienced with the Godot Engine Development yet, so a direction what would need to be done for that would be great.

**Comment by HEAVYPOLY** [comment]
@ModProg for iOS we are treating pen input as mouse events, because mouse events already have pressure, tilt etc on desktop.  I think it would be good to follow this pattern.

**Comment by ModProg** [comment]
@HEAVYPOLY So you would suggest use mouse for https://developer.android.com/reference/android/view/InputDevice#SOURCE_STYLUS ? I will try that, but we should make sure that that is correctly set on all devices. iOS had force touch for example, I don't know if any android Phones had/have something similar.

**Comment by HEAVYPOLY** [comment]
Yea I think stylus should be handled as mouse event because that's how it behaves on desktop and iOS, to keep consistency across all platforms.  Also because mouse motion already has pressure / tilt properties.

**Comment by ModProg** [comment]
@HEAVYPOLY should `java_godot_lib_jni.cpp` get a new method `mouse` or should touch be used here and the differntiation be done in cpp?

**Comment by HEAVYPOLY** [comment]
I think so although I'm pretty new to cpp.  @m4gr3d might know better.  

On iOS we did it like this:
New pencil_press / pencil_drag / pencil_cancelled functions next to touch_press and touch_cancelled in ios godot_view.mm

pencil events sends a regular mouse event with pressure like this:

void OSIPhone::pencil_drag(int p_idx, int p_prev_x, int p_prev_y, int p_x, int p_y, float p_force) {
	Ref<InputEventMouseMotion> ev;
	ev.instance();
	ev->set_pressure(p_force);
	ev->set_position(Vector2(p_x, p_y));
	ev->set_global_position(Vector2(p_x, p_y));
	ev->set_relative(Vector2(p_x - p_prev_x, p_y - p_prev_y));
	ev->set_tilt(p_tilt);
	perform_event(ev);
};



```
- (void)touchesBegan:(NSSet *)touchesSet withEvent:(UIEvent *)event {
	NSArray *tlist = [event.allTouches allObjects];
	for (unsigned int i = 0; i < [tlist count]; i++) {
		if ([touchesSet containsObject:[tlist objectAtIndex:i]]) {
			UITouch *touch = [tlist objectAtIndex:i];
			int tid = [self getTouchIDForTouch:touch];
			ERR_FAIL_COND(tid == -1);
			CGPoint touchPoint = [touch locationInView:self];

			if (touch.type == UITouchTypeStylus) {
				OSIPhone::get_singleton()->pencil_press(tid, touchPoint.x * self.contentScaleFactor, touchPoint.y * self.contentScaleFactor, true, touch.tapCount > 1);
			} else {
				OSIPhone::get_singleton()->touch_press(tid, touchPoint.x * self.contentScaleFactor, touchPoint.y * self.contentScaleFactor, true, touch.tapCount > 1);
			}
		}
	}
}
```

**Comment by m4gr3d** [comment]
cc @thebestnom for feedback.

**Comment by pfeodrippe** [comment]
One way that I've found to differentiate between the input type is that `InputEvent.get_device()` returns `0` for the apple pencil, while it returns `-1` for the finger. Is this the best way to know it?

**Comment by akien-mga** [comment]
Android support was implemented in https://github.com/godotengine/godot/pull/80644

iOS would still be missing I suppose. Would be nice to have feature parity in 4.2 if we can (cc @bruvzg).

**Comment by bruvzg** [comment]
Support for iOS is implemented in https://github.com/godotengine/godot/pull/70482

**Comment by Calinou** [comment]
Closing, as this is now implemented on both mobile platforms as requested in the proposal.

Support for pen pressure on desktop platforms should be tracked in a separate proposal if you have a project that requires this.
