### ISSUE TITLE
Create a repo on the Godot org for GLTF extensions written in GDScript

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#7353]
### Describe the project you are working on

I am working on support for GLTF extensions in Godot Engine. Godot has support for some extensions in the core engine, and support for creating new extensions via GDScript or GDExtension.

### Describe the problem or limitation you are having in your project

There is currently no place for users to find officially endorsed extensions written in GDScript. Right now the only way to have an official extension is to have it be a part of the core engine. However, not everything should be in the core engine, for a variety of reasons. For example, it could be bloat if most users don't need a GLTF extension, it could be beneficial to update a GLTF extension independently from the engine version, and some GLTF extensions need to be easily modifiable by users in script (like [the Khronos XMP extension](https://github.com/godotengine/godot-proposals/files/12279350/gltf_extensions.zip) I am working on is effectively a general-purpose data format, so it needs to remain extremely hackable, so keeping it written GDScript is the best option).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Create a repo on the Godot organization that will hold GLTF extensions. These extensions would allow Godot to provide officially endorsed GLTF extensions in one place, which can be independently updated, arbitrarily edited by users, and avoids the problem of bloat since users can keep only the files they need.

This repo would be supplementary to the GLTF extensions provided in core. Whether we put an extension in core or in this repo would be decided by how many users would use the feature, how big it is, how hackable it needs to be, if it needs to be updated separately from the engine, etc.

Open question: We would use this repo for `GODOT_`, `KHR_`, and `EXT_` extensions. Do we want to also bring in code for other vendor extensions, like `OMI_` and `VRMC_`? I think the answer is generally yes, and we can make this repo a one-stop shop for Godot users to grab a bunch of GLTF features. Of course there would be a higher quality bar for being officially endorsed in this repo compared to a user publishing separately on the asset library.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

First, I would click this button on GitHub.
<img width="98" alt="Screenshot 2023-07-22 at 3 58 40 PM" src="https://github.com/godotengine/godot-proposals/assets/1646875/ab2fdb5c-114f-4c66-9ab8-8d3047694180">
(btw I do have access to click it, but we want to write down the reasons in a proposal fist)

Then, add content to the repo, publish it on the asset library, link to it from [here](https://github.com/godotengine/godot-proposals/issues/7354), and finally include it in the planned UI for official add-ons described in this proposal https://github.com/godotengine/godot-proposals/issues/7231

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A - this will be an add-on made of many lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A - this will be an add-on in the asset library, and this is about keeping bloat out of core.

**Comment by adamscott** [comment]
I added the proposal to the agenda of the next production team meeting, next Tuesday (August 1st).

**Comment by adamscott** [comment]
We discussed the proposal at the said production meeting. We think that's something that the #members in the chat should discuss. So maybe start a discussion at #members-discuss? Thanks!

**Comment by YuriSizov** [comment]
To elaborate on Adam's comment a bit more, this and https://github.com/godotengine/godot-proposals/issues/7354 are not about opening a repository. The discussion should be about whether or not we want to establish something like this in the first place. Why not integrate into an existing public repository for public extensions? Why have a public repository for private extensions? These would be the typos of questions that need to be discussed by stakeholders. Creating the repo is trivial and anyone can do it.

**Comment by aaronfranke** [comment]
> Why not integrate into an existing public repository for public extensions?

Which existing repository? For this proposal, aside from [omi-godot](https://github.com/omigroup/omi-godot) there is no repo of GLTF extensions in GDScript. For #7354, the Khronos repo's list of third-party extensions is non-comprehensive, and they do not make it their goal to be. Plus there's the opportunity to insert Godot-specific implementation notes.

> Why have a public repository for private/company-specific extensions?

An extension may be published under a non-Khronos name, but that doesn't make it private or company-specific. Extensions are usually not intended to only be used by one company or product, they are intended to be interoperable and used by many vendors, but they may be published under an organization's name if it was primarily driven by them. For example Microsoft's physics extensions use the prefix MSFT_ but they are intended to be used outside of Microsoft products and are developed in collaboration with other parties.

**Comment by YuriSizov** [comment]
> Which existing repository?

This was in reference to the Khronos one for the other proposal.

**Comment by aaronfranke** [comment]
@YuriSizov To clarify, the proposals are not about giving third-party extensions the `GODOT_` prefix. That's not something that anyone is planning to do. An extension specific to The Mirror will use a `MIRROR_` prefix, not `GODOT_`, because `GODOT_` is only for official extensions that are owned by the Godot Engine organization.

I made an implementation of [`KHR_xmp_json_ld`](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_xmp_json_ld) in GDScript. Where should I put it? I doubt Khronos would be willing to host it. I could put it on my personal account, but that seems suboptimal. It shouldn't go in the engine, because this extension is extremely open-ended so it's best to keep it in GDScript and let users hack at it for their needs. So to me the best option is to have a repo on the Godot organization.

The idea in this proposal of hosting other extensions in the same repo is an attempt to make such as repo's purpose more general, so that we don't just have a repo for a small number of Khronos extensions, but instead a bundle of many extensions. This is also part of the goal of https://github.com/godotengine/godot-proposals/issues/7231 - I think it's a good idea to try and make the engine less bloated by moving less commonly needed extensions to GDScript, but without a repo like what I'm proposing the only two options are "put it in the engine" and "unofficial third-party add-on".

**Comment by aaronfranke** [comment]
Closing due to maintainers not desiring this. For KHR_xmp_json_ld, here is an add-on in the asset library for writing KHR_xmp_json_ld data on export, and reading on import: https://godotengine.org/asset-library/asset/2309
