### ISSUE TITLE
Create a repo on the Godot org that lists all supported GLTF extensions

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-proposals#7354]
### Describe the project you are working on

I am working on support for GLTF extensions in Godot Engine.

### Describe the problem or limitation you are having in your project

Godot supports a variety of GLTF extensions, but there is no easy way to find all of this information in one place.

One option would be to create a documentation page which lists every supported extension and links to the upstream specs. This is [what Blender does](https://docs.blender.org/manual/en/dev/addons/import_export/scene_gltf2.html#extensions).

However:

* A documentation page does not make it easy for us to write and publish our own `GODOT_` extensions. The typical way organizations publish extensions is through a GitHub repository. See [Khronos extensions](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos), [Khronos list of vendor extensions](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor), and [OMI extensions](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0).
    * For example, I would like a place to publish [GODOT_single_root](https://github.com/godotengine/godot-proposals/files/12137266/GODOT_single_root.zip) once it's done.
* At the same time as holding `GODOT_` extensions, this repository can serve as a single unified place where the third-party extensions and all details are documented.
* Also, it allows us to ensure we are documenting a snapshot of the specific version of the extension, in case upstream decides to change it later.
* Also, it allows us to document all Godot versions at once, as opposed to a Godot documentation page which is specific to a Godot version, so we can easily list that an extension is supported as of "4.1+" or similar, instead of the user having to click between different versions of the documentation page to find this information.
* Also, it allows us to insert additional text into the READMEs of third-party specs for any implementation notes of how specifically the extension's features map to Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The proposal is to create repo similar in structure to the [OMI extensions](https://github.com/omigroup/gltf-extensions) repo, with an `extensions/2.0` folder containing the extensions that Godot supports. Also, there should be a repo-level README with a table of extensions, what Godot versions support it, and if it's supported in the core engine or [as an official add-on](https://github.com/godotengine/godot-proposals/issues/7353).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

First, I would click this button on GitHub.
<img width="98" alt="Screenshot 2023-07-22 at 3 58 40 PM" src="https://github.com/godotengine/godot-proposals/assets/1646875/ab2fdb5c-114f-4c66-9ab8-8d3047694180">
(btw I do have access to click it, but we want to write down the reasons in a proposal fist)

Then, add content to the repo, and finally link to it in the documentation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A - this is about documentation.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A - this isn't an engine feature.

**Comment by adamscott** [comment]
I added the proposal to the agenda of the next production team meeting.

**Comment by adamscott** [comment]
We discussed the proposal at the said production meeting. We think that's something that the #members in the chat should discuss. So maybe start a discussion at #members-discuss? Thanks!

**Comment by aaronfranke** [comment]
Closing due to lack of interest.

For the use case of listing supported extensions, we can use the documentation instead.

For the use case of writing `GODOT_` extensions, we can just push a PR to Khronos (even if it's not merged and only ever a PR, people can still search the list of PRs for "godot" and find it).
