### ISSUE TITLE
Add native menubar support on macOS (global menu)

### ISSUE THREAD

**Issue by thomas-alrek** [godotengine/godot-proposals#736]
**Describe the project you are working on:**
N/A

**Describe the problem or limitation you are having in your project:**
Godot is currently rendering its menus inside of its window.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
On macOS, native applications have their menus rendered outside of their window, at the top of the screen. This is the expected behavior on macOS, and it would boost my productivity if Godot also followed this UX pattern.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![image](https://user-images.githubusercontent.com/14291825/79744538-cc5e5c80-8306-11ea-87b0-d8e6305bbfe2.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I would see this as a permanent change as this would only affect macOS anyways. Maybe leave in a option to allow the user to revert to the old menu behavior?

**Is there a reason why this should be core and not an add-on in the asset library?:**
I dont know if this would be possible to do as an addon.

**Comment by Calinou** [comment]
#38044 is paving the groundwork for this feature.

**Comment by bruvzg** [comment]
Implemented in https://github.com/godotengine/godot/pull/63950
