### ISSUE TITLE
Separate color option for documentation comments

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#7373]
### Describe the project you are working on

Multiple projects

### Describe the problem or limitation you are having in your project

Currently documentation comments (starting with ##) and general comments (#) displays with the same color in the editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Options for setting colors for both documentation and normal comments. 
This can be done by adding one more option in editor theme for documentation comments and keeping current comment option for normal comments.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Differentiating colors will help readability of the code for people who add comments in code for documentation purpose.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Both the comment types are exhaustively used. It will help in readability.

### Is there a reason why this should be core and not an add-on in the asset library?

parsing of code and comment is part of core

**Comment by dalexeev** [comment]
* See godotengine/godot#72751.
