### ISSUE TITLE
Allow Inspector Property Headers to be opened while dragging a Resource

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#7394]
### Describe the project you are working on

A game project

### Describe the problem or limitation you are having in your project

When creating new scenes, especially for User Interface, there are regularly resources that need to be dragged from the FileSystem to the Inspector. One of the main examples is `fonts` for Labels, as well as any Texture, Material or Shader.

However, when you want to do this, you always need to make sure to open the `theme overrides > fonts` headers first, otherwise it's impossible to drag something in. This workflow makes very little sense. Most users would place a label, think "Alright, time to add that font. Let me search for it in the FileSystem, let me drag it in.... Oh, nevermind, lets open the folders first and then drag again".

![dragfont](https://github.com/godotengine/godot-proposals/assets/10502115/2c4f8b6e-2d61-4342-929d-d17302a69f7b)

It's a pretty common UX problem when adding Resources to the inspector.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In my mind there are multiple routes to go to mitigate this issue:

1. Have headers open by themselves, when they are hovered for a second while the user is holding a Resource.
2. Allow headers to be opened by clicking Right Mouse Button while the user is holding a Resource
3. Open headers that can receive the currently held Resource Type automatically, and close them again after the resource dragging is cancelled or completed. Meaning, if the user is currently dragging a `font`, open all currently hidden properties that can receive a font resource. If the user is dragging a `material`, open all the headers that can receive a material.

Any of these would make the workflow of dragging resources across the editor a lot more smooth.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used a lot. Technically it can be worked around, but giving everything a script with a hardcoded preload reference to the Resource that it needs to set on _ready(), just to avoid having to drag it, seems like to wrong way to handle this :D

### Is there a reason why this should be core and not an add-on in the asset library?

Core Godot Inspector/FileSystem behaviour

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1080.
