### ISSUE TITLE
Add `tween_emit_signal()` method to SceneTreeTween

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#7395]
### Describe the project you are working on

A game project

### Describe the problem or limitation you are having in your project

When using SceneTreeTweens, I often find that I want to emit a signal when a certain point is reached. This is possible, but requires me to make a separate function, usually something called `tween_reached_halfway`, in which I then emit a signal, and nothing else.

![image](https://github.com/godotengine/godot-proposals/assets/10502115/2e4b23d8-5f0d-46e4-97ab-6d8ef7f6f7c7)

This feels wrong, and significantly clutters the script with tons of one line functions when you use Tweens in combination with signals regularly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an additional `tween_emit_signal` function, which does exactly that. It emits a signal when it gets called, the same way a `tween_callback` gets called when it hits that point in the Tween.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/10502115/82cff436-f283-4a32-988c-6b11975e353d)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yep. It absolutely can be worked around. 
However, I think signals are such core functionality of GDScript, that Tweens should integrate nicely with them. This also fits nicely with the recently proposed [Tweener that awaits signal](https://github.com/godotengine/godot-proposals/issues/7337)

### Is there a reason why this should be core and not an add-on in the asset library?

Core part of SceneTreeTween

**Comment by KoBeWi** [comment]
You can use `emit_signal()` directly using `tween_callback()`:
```GDScript
var tween = create_tween()
tween.tween_property(...)
tween.tween_callback("emit_signal", ["tween_finished", true])
```
Godot 4:
```GDScript
tween.tween_callback(emit_signal.bind("tween_finished", true))
# or
tween.tween_callback(func(): tween_finished.emit(true))
```

**Comment by Arecher** [comment]
Thanks, that helps!
I never realised that it would work for all methods

In Godot 3.5+ it does still require an Object to call the `emit_signal` in, so it would be (just in case someone finds this):

> ```gdscript
> var tween = create_tween()
> tween.tween_property(...)
> tween.tween_callback(self, "emit_signal", ["tween_finished", true])
> ```
