### ISSUE TITLE
Allow ReflectionProbe cubemap to use a texture resource

### ISSUE THREAD

**Issue by josefkaragoli** [godotengine/godot-proposals#7396]
### Describe the project you are working on

3D game

### Describe the problem or limitation you are having in your project

Godot renders the cubemap used by ReflectionProbes when starting the scene (Once) or every frame (Always). While this is convenient, it removes user control over exactly what is reflected, and also causes a small delay, where for around 5 frames there are no reflections. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose a system similar to VoxelGI where the cubemap can be baked to a texture and edited by external programs. This way the user has more fine tune control over what is in the reflection, and also allows the reflection to be instantly present, rather than waiting for a 5 frame delay. 

By default, godot will use the current method where the reflectionprobe is created at runtime. However, if a custom texture is set, then godot will use that instead.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user clicks "Bake ReflectionProbe" a popup will prompt the user to choose a save directory. A texture3D resource will be saved there containing the cubemap as an exr file. This texture can be edited by external softwares.
![image](https://github.com/godotengine/godot-proposals/assets/76781125/9af35eaf-4a92-462a-b95f-e18bd079a6c6)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The reflection cubemap cannot be accessed or modified by script

### Is there a reason why this should be core and not an add-on in the asset library?

It changes the way ReflectionProbes are used out of the box.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/4782.
