### ISSUE TITLE
Type Narrowing

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-proposals#7402]
### Describe the project you are working on

Helps with better coding practices in general.

TypeScript has documentation that would be helpful, and similar practices would be nice in Godot's scripting language as well:
https://www.typescriptlang.org/docs/handbook/2/narrowing.html

### Describe the problem or limitation you are having in your project

Variable are not scoped (well) to a type within a scope (func, if/elif/else, loop).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Type Narrowing in the code would help reduce code errors and the need for debugging.

* testing instance types `if my_var is MyClass`
    * The type within the scope of the if would know all references to `my_var` is an instance of `MyClass`.
* testing `primitive` types `if typeof(my_var) == TYPE_STRING`
    * The type within the scope of the if would know all references to `my_var` is string.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```python
class A:
	pass

class B extends A:
	func echoB():
		print("B")

class C extends A:
	func echoC():
		print("C")

class D:
	func a(param: A):
		if param is B:
			param.echoB()
		elif param is C:
			param.echoC()
```

Taking the above code, the parser thinks `param` is of type `D`, it would be nice if it knew that when using the keyword `is` that it would narrow the type to either type `B` or type `C`.

When within scope `if param is B` the parser should know that all references to `param` is of type `B` and when in `elif param is C` it should know that `param` is of type `C`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There isn't a workaround, as the language server doesn't support this.

### Is there a reason why this should be core and not an add-on in the asset library?

This effects the core code syntax.

**Comment by AThousandShips** [comment]
This is already implemented, i.e. if you have `if p is X` it makes the assumption hold

**Comment by nathanfranke** [comment]
In Godot 4.1.1,

```gdscript
extends Node

func _ready() -> void:
	var a = get_parent()
	if a is Node2D:
		var v := a.position

```

> Parse Error: Cannot infer the type of "v" variable because the value doesn't have a set type.

**Comment by TheColorRed** [comment]
Yeah so narrowing doesn't fully work...
