### ISSUE TITLE
Hightlight hovered items even if they are selected already in the FileSystem 

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7404]
### Describe the project you are working on

prototype

### Describe the problem or limitation you are having in your project

As you can see in this recording:

[simplescreenrecorder-2023-07-28_17.47.31.webm](https://github.com/godotengine/godot-proposals/assets/71937306/b5ba4a49-5844-48cd-b17c-b8cd84015d43)

items don't get highlighted on hover if they are part of a selection.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Highlight the hovered item in another color if it happens to be part of a selection. The item alone should be highlighted and *not* the whole selection since clicking it clears the selection.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

use yet another highlight (a slightly brighter one than the current "selected" overlay) and show it when each item is hovered.
Here's how nautilus behaves:

[simplescreenrecorder-2023-07-28_17.51.30.webm](https://github.com/godotengine/godot-proposals/assets/71937306/0eac5931-0196-4f8f-ac38-bc8c726aba04)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it's a minor UX thing that occurs often

### Is there a reason why this should be core and not an add-on in the asset library?

tiny core ux change

**Comment by KoBeWi** [comment]
The Control in question is an ItemList.
