### ISSUE TITLE
Allow to set dark mode on the game window

### ISSUE THREAD

**Issue by reptofrog** [godotengine/godot-proposals#7409]
### Describe the project you are working on

_Not applicable._

### Describe the problem or limitation you are having in your project

I want my game to have a dark title bar even if the light mode is enabled in the OS, but there is currently no option for this.

|Light mode|Dark mode|
|-|-|
|![Screenshot from 2023-07-29 23-45-57](https://github.com/godotengine/godot-proposals/assets/36744029/a1096aae-4c3d-43b9-894c-ff3ac05aa12f)|![Screenshot from 2023-07-29 23-46-00](https://github.com/godotengine/godot-proposals/assets/36744029/4f10b59e-1d7e-4628-a597-1507bc7bcf1f)|

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

An option in Project Settings (`display/window`) that forces the game to use a dark title bar.

Or perhaps a `DisplayServer` method, something like `set_dark_mode` or `set_color_scheme` to change the style dynamically.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

_Not applicable._

### If this enhancement will not be used often, can it be worked around with a few lines of script?

_Currently there is no workaround._

### Is there a reason why this should be core and not an add-on in the asset library?

_This is not possible to achieve with an add-on._

**Comment by bruvzg** [comment]
Normally, tile bar theme is controlled by OS settings, apps are not expected to change it and most systems won't allow it. But you can check if system theme is in dark mode and adjust the rest of UI accordingly `DisplayServer.is_dark_mode` and `DisplayServer.get_accent_color`.

**Comment by reptofrog** [comment]
I haven't considered that some OS may not allow apps to decide on the appearance of windows. 🤔

Linux allows this for sure, and I thought that this is possible in Windows as well. Is it not?

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/5312.
