### ISSUE TITLE
Add `OS::get_compositing_window_manager()` method

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot-proposals#7410]
### Describe the project you are working on

I'm working to find an issue to godotengine/godot#77333.

### Describe the problem or limitation you are having in your project

I need to know if Godot is running with XWayland or if it's running in a pure X.org environment to be able to execute code or not. Right now, there's no way to know this unless we manually parse the environment variables (see godotengine/godot#79396).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A method in `OS` could return the current compositing window manager, regardless of the current platform, as multiple platforms (like Linux/BSD) can share the same compositing window manager.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's how the feature could be implemented. The enum represents the values that could be returned from the function.

```cpp
enum CompositingWindowManager {
    COMPOSITING_WINDOW_MANAGER_NONE,  // Web or Linux/BSD `tty` login
    COMPOSITING_WINDOW_MANAGER_UNKNOWN,
    COMPOSITING_WINDOW_MANAGER_DESKTOP_WINDOW_MANAGER,  // Windows
    COMPOSITING_WINDOW_MANAGER_QUARTZ_COMPOSITOR,  // macOS
    COMPOSITING_WINDOW_MANAGER_X11,
    COMPOSITING_WINDOW_MANAGER_WAYLAND
};
virtual CompositingWindowManager get_compositing_window_manager();
```

Then, each platform could do their tests to return the right value.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it could be manually parsed by the user using GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

Because godotengine/godot#77333 needs to use the result of this detection to be able to run code or not. If it's not in core, this issue could hypothetically never be solved.

**Comment by Calinou** [comment]
Could we detect the actual window manager on Linux and return a string that matches it?

**Comment by bruvzg** [comment]
Since every OS except Linux will have only one option, it seems to be relevant only for XWayland/X.org detection, and it should be possible to do it by reading the value of `OS.get_environment("XDG_SESSION_TYPE")` already.

**Comment by adamscott** [comment]
> Since every OS except Linux will have only one option, it seems to be relevant only for XWayland/X.org detection, and it should be possible to do it by reading the value of `OS.get_environment("XDG_SESSION_TYPE")` already.

This makes it so that every time, in the codebase, that we want to check Wayland/X11, we'd need to to this check manually. This PR makes it so that it would be as simple to compare an enum.

And what about running Godot in base Docker image without any XDG environment variable? There should be a standard way to know without manually checking.

**Comment by adamscott** [comment]
> Knowing the desktop environment name is proportionally less useful, as people generally either use the WM that comes with their desktop environment (e.g. KWin for KDE), or a standalone WM (e.g. i3wm).

Could be nice, but out of scope of this actual proposal.

**Comment by bruvzg** [comment]
> This makes it so that every time, in the codebase

None of the codebase except `DisplayServerX11` internal should have these checks or be compositor dependent in the first place. So I would add a single internal `bool` to the `DisplayServerX11` which is set based on env. variable on DS init instead.

And if it's a public API (I do not see any use for it), it probably should return String instead of enum to support custom DisplayServers as well (e.g., console ports).

**Comment by adamscott** [comment]
With the feedback received, will detect internally the issue inside `DisplayServerX11` and fix it there without exposing anything outside.

**Comment by adamscott** [comment]
Thanks everyone for the feedback, by the way!
