### ISSUE TITLE
InputEvent.as_text() only provides the event text in English. Let's provide a means of obtaining translated text.

### ISSUE THREAD

**Issue by programnoir** [godotengine/godot-proposals#7426]
Edit: Updated title of proposal from "Let's add built-in translations" to "Let's provide a means of obtaining translated text," as there are translations of substrings of InputEvent.as_text() names in the editor.

### Describe the project you are working on

I'm working on a template game project that allows you to map any number of key binds to a specified list of actions. Part of the implementation of this keymapping UI involves the use of InputEvent.as_text() to display what keybind was selected.

![image](https://github.com/godotengine/godot-proposals/assets/1452074/66b3aed6-4397-443d-996c-3ce19e9ec871)

### Describe the problem or limitation you are having in your project

As of https://github.com/godotengine/godot/pull/43660, as_text() will return an English string representation of the InputEvents. However. there are no built-in translations of these InputEvent string representations, even if you change the language in the Editor settings. At this time, my only solution is to manually translate all possible InputEvents in the project.

![image](https://github.com/godotengine/godot-proposals/assets/1452074/3a36ec23-3d63-4c11-86ff-ea735e42cc0d)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By default, InputEvent.as_text() should be modified to return a translated version of the event.
* In the editor, this should translate according to the developer's editor language settings.
* During runtime, this should translate according to the locale that has been set by TranslationServer.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There is a chance that this is not a Godot issue and possibly a user issue. I am still trying to understand how to obtain core translations in Godot. For now, the proposal assumes that this could either be a bug/feature expansion report or a documentation request.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As this is a translation proposal that involves modifying features, third-party solutions and project-specific workarounds are invalid.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving InputEvent.as_text(), a core feature.

**Comment by programnoir** [comment]
Sorry, after looking into it further, it looks like [there are built in translations](https://github.com/godotengine/godot/blob/master/editor/translations/editor/ja.po) for the strings in these InputEvents. I'm not sure why I'm only getting English text when using the function, though.

**Comment by KoBeWi** [comment]
The translations are editor-only. You need to add your own translations to your project.

**Comment by programnoir** [comment]
Thank you for the clarification. Is this basically a principle thing, like "we don't modify any built-in Godot functions to return non-English strings," basically?

**Comment by KoBeWi** [comment]
No, the function uses the currently set locale and translation works by searching the available locale translation for specific strings. Inside editor it will use editor translations, but projects have their own translations. If the string is not provided by the project translation, all texts fallback to English by default.

Related proposal: https://github.com/godotengine/godot-proposals/issues/7334

**Comment by programnoir** [comment]
Thanks for helping me understand this better. I'll close this proposal and add my vote to the related proposal you've linked, since that proposal would solve this one.
