### ISSUE TITLE
please make control + shift == shift + control in tilemap painting mode.

### ISSUE THREAD

**Issue by dosuserx** [godotengine/godot-proposals#743]
**Describe the project you are working on:**

game jam game

**Describe the problem or limitation you are having in your project:**

i have severe joint problems. pressing shift + control for tilemaps is painful. whats worse is that if i jam my hand on the shift and control at the same time, the shift is pressed first, meaning the rect paint for tiles isnt engaged forcing me to hurt my fingers over and over.  if Shift + Control == Control + shift, than godot should accept both so i can just rest my hand on both keys and dont have to hurt my pinky and ring finger. im disabled.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

 if Shift + Control == Control + shift, than godot should accept both so i can just rest my hand on both keys and dont have to hurt my pinky and ring finger. im disabled.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** 

im under the clock cant handle this now, see above for solution

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

im not sure

**Is there a reason why this should be core and not an add-on in the asset library?:**
cuz disabled game devs need a little help once and a while. the time i waste redoing all my painting everytime each stroke as my fingers scream from pain is using up my gamejam time.  its such an easy thing, and it really would help ease my pain so youd actually be doing something really nice for everyone, not just me.

**Comment by KoBeWi** [comment]
But they already work the same. Not sure what's the problem here.

**Comment by dosuserx** [comment]
do they? i must be having some other problem. when i hit shift first, it
wasn't working for me. restart godot usually gives it but not that time.
I'll keep watching it and let you know.

**Comment by KoBeWi** [comment]
> do they?

Yep, I can't seem to reproduce it. Also it would be a bug.

**Comment by groud** [comment]
Maybe it depends of the platform. What is your OS and godot version ?

**Comment by KoBeWi** [comment]
So as I said, it's more likely a bug. If you can still reproduce it in 3.2.3+, please open an issue at the [bug tracker](https://github.com/godotengine/godot/issues).
