### ISSUE TITLE
Expose `Vector*` component-wise `min/max` to scripting

### ISSUE THREAD

**Issue by AThousandShips** [godotengine/godot-proposals#7439]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Manually creating `min/max` vectors in GDScript is tedious and error prone, one use case is https://github.com/godotengine/godot-proposals/issues/7333#issuecomment-1663488833

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The built-in functions accomplish this task directly, and adds parity with other already exposed cases such as `floor`, `clamp`, `round`, etc.

Having access to these would greatly reduce clutter, improve readability, and reduce errors

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Expose the already existing component-wise `min/max` methods of these classes

I already have a branch ready for this

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can, but it is error prone

```gdscript
Vector2(min(a.x, b.x), min(a.y, b.y))
Vector3(min(a.x, b.x), min(a.y, b.y), min(a.z, b.z))
Vector4(min(a.x, b.x), min(a.y, b.y), min(a.z, b.z), min(a.w, b.z))
```

### Is there a reason why this should be core and not an add-on in the asset library?

It relates to binds in core

**Comment by rburing** [comment]
Please explain why one would want to perform these operations, preferably with concrete examples.

**Comment by AThousandShips** [comment]
Here: https://github.com/godotengine/godot-proposals/issues/7333#issuecomment-1663488833

**Comment by yosoyfreeman** [comment]
> Please explain why one would want to perform these operations, preferably with concrete examples.

Just today i was trying to do this to get the maximum velocity vector along the axes.
