### ISSUE TITLE
Reduceable render resolution for mobile VR

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot-proposals#744]
**Describe the project you are working on:**
Not working on a particular project right now. I'm just experimenting and tinkering with mobile VR after I designed and 3D printed a headset.

**Describe the problem or limitation you are having in your project:**
Mobile hardware is really limiting in terms of graphics performance.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Currently the render resolution is the display resolution + oversampling, thus the only thing that can be changed is the oversampling factor, and since it is extra pixels rendered on top of the base resolution, the final resolution can only be increased right now.
What I want is a way to reduce the **base resolution**. Since the framerate in VR is of a much higher importance than resolution, a reduction in rendering resolution from 1920x1080 to 1280x720 for example should help significantly increase the framerate.
Most if not all phones with OLED displays have their subpixels arranged in a ["PenTile"](https://en.wikipedia.org/wiki/PenTile_matrix_family) RGBG configuration, where for each 2 green subpixels, there is only 1 red and 1 blue subpixel, so for a 1920x1080 display, there will be 1920x1080 green subpixels, but only 960x540 (half) red and blue subpixels. This makes the benefit of rendering at display resolution even smaller over the benefit of rendering at a lower resolution in exchange for a better framerate.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The width and height settings in Project Settings > Display > Window could be used to set the render resolution instead when using the mobile VR interface.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This involves modification of the core code, so no it can't

**Is there a reason why this should be core and not an add-on in the asset library?:**
Same as above, it involves modification of core code.

**Comment by Calinou** [comment]
I presume the `viewport` stretch mode doesn't work when using mobile VR?

**Comment by Tooniis** [comment]
> I presume the `viewport` stretch mode doesn't work when using mobile VR?

Yes. It has no effect.

**Comment by Calinou** [comment]
See also #917.

**Comment by m4gr3d** [comment]
cc @BastiaanOlij

**Comment by clayjohn** [comment]
I have an outdated branch implementing this in 3.1 https://github.com/clayjohn/godot/tree/shrink_3d

**Comment by m4gr3d** [comment]
@clayjohn Nice! It gets a bit more complex for VR though since (with the current plugin), device render resolution handling is specific to the VR device api. 
In these scenarios, we'd need a hook to update the device render resolution via the VR device api instead.

**Comment by clayjohn** [comment]
@m4gr3d that makes sense! Should be totally doable.

**Comment by BastiaanOlij** [comment]
The way this works in VR is that the ARVR interface overrules the resolution at which we're rendering and the viewport settings get ignored. This is done by returning the required resolution from the get_render_targetsize method:
https://docs.godotengine.org/en/stable/classes/class_arvrinterface.html#class-arvrinterface-method-get-render-targetsize

This is where this logic should be and already is for various interfaces. For instance, OpenVR has controller sliders for this in OpenVR itself, if we then have additional functionality within Godot that contradicts the users settings in OpenVR, that doesn't make sense. When we look to the future and looking at features such as Fragment Density Maps where those maps are supplied by the VR platform used, straying away from the resolution the platform provides us may break things.

In the end, this is a platform choice and each ARVRInterface implementation will need to decide whether it has to stick to the resolutions dictated by the VR SDK being implemented or whether it is safe to offer an overrule that gives the developer control over increased/decreased resolution without altering the FOV. 

I don't believe it is safe to add something in the core unless we accept that we have a setting that only works "sometimes"

**Comment by Calinou** [comment]
@BastiaanOlij Does https://github.com/godotengine/godot/pull/51870 address this for VR in `master`?

**Comment by BastiaanOlij** [comment]
@Calinou that new setting will probably work with this yes, that said, the real solution as I mentioned belongs in the XRinterface.

We're adding it to the OpenXR plugin, still needs to be exposed properly but should be in the next version.

**Comment by BastiaanOlij** [comment]
Also just to add to this, we're not rendering at screen resolution because of the fisheye effect of the lens distortion. Keep in mind that with VR you have magnifying lenses in front of your eyes that distort the image on screen, and VR uses reverse distortion to counter the effects of magnification. 

So if you render VR content at half the resolution of the screen, the lens distortion has the effect of "zooming in" in the middle of the screen, right where you're focus is. The end result is that you get to 25% or lower quality right where it matters.

Reducing the render resolution is the wrong fix for a very real problem on mobile. The correct fix for this issue is to implement foveated rendering so you can use a high resolution render target, you do render at that resolution where your focus lies, and at much lower resolution the further away you get from this focal point.

This is coming to Godot 4 where we are planning on implementing VRS with a density map though that may not be supported on anything but high end mobile devices.

**Comment by m4gr3d** [comment]
@BastiaanOlij I think this proposal can now be closed.

**Comment by Calinou** [comment]
This was implemented in 4.0, closing. For 3.x, see https://github.com/godotengine/godot/pull/74935.
