### ISSUE TITLE
Add get_ancestor function for any node (recursive get_parent)

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot-proposals#7442]
### Describe the project you are working on

A card game.

### Describe the problem or limitation you are having in your project

I have a scene tree with many nested nodes, so I use get_parent() and get_node() a lot.
get_node("path") with the parameter "path" allows me to fetch any child no matter how deep in the tree.
However, I cannot do the same for parents.

Pic-related is yet another example I stumbled upon.
![cardspanel](https://github.com/godotengine/godot-proposals/assets/25630803/bccb97ce-0800-4e72-b2c8-dc5facdc326d)

I want a child of grid_container (that child is dynamically created), to get a reference to CardsPanel. I would have to do 6 or 7 times get_parent(). Which also hardcodes the problem because if I decide to shake the hierarchy a bit (e.g. add one more container in between), it won't work.

So, I want a function which is like get_parent() but for all above parents. And no, unique node name doesn't help because it accepts children only (if I am wrong on this, close this issue since that would solve my problem but I seem to not be able to make it work for parents)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

^

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

To get the node "CardsPanel" as mentioned above, I would just write:
get_ancestor("CardsPanel")

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The lazy and obviously error-prone way is:
```gdscript
get_parent().get_parent().get_parent().get_parent().get_parent().get_parent().get_parent()
```

The correct way, is to make a Utils singleton/global, so as to basically call this function...
```gdscript
func get_recursive_parent_from_child(child: Node, parent_name: String) -> Node:
	var current_parent: Node = child.get_parent()
	while (current_parent.name != parent_name):
		current_parent = current_parent.get_parent()
		
	return current_parent
```

The function name `get_recursive_parent_from_child` is intuitive for the singleton/global, since it takes the child parameter, but obviously `get_ancestor` is better if the function is placed on the node itself

Ah and ofc, the above function needs some error checks (e.g. what if there are no parents with that name?)
I would suggest an optional int parameter, so it stops after that many iterations (so if it doesn't find one, it won't keep surfacing forever)

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core function for all scene nodes.

**Comment by AThousandShips** [comment]
What would this do that [find parent](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-find-parent) does not?

**Comment by KoBeWi** [comment]
Check unique node names, they are basically essential when navigating complex scenes.

**Comment by TheColorRed** [comment]
You could also use a group and get the item(s) in the group.

```
get_tree().get_first_node_in_group('my_group')
get_tree().get_nodes_in_group('my_group')
```

**Comment by TheYellowArchitect** [comment]
Thank you for the answers, I can't believe I missed find_parent!
I apologize for having opened this
