### ISSUE TITLE
Support covariant return types for overriding functions

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot-proposals#7450]
### Describe the project you are working on

I am working on an addon that manages RPG data.

### Describe the problem or limitation you are having in your project

It is currently impossible to specify a more 'specific' type of a return value of any overriden function, if that returned value is a subtype of the overriding function. Many common languages like Java and ~C#~ C++ support such feature ([see table](https://github.com/godotengine/godot-proposals/issues/7450#issuecomment-1666951033)), as it unlocks additional functionality for polymorphism.

Currently, Godot 4.1 produces an error like this:

<img width="804" alt="Screenshot 2023-08-05 151230" src="https://github.com/godotengine/godot-proposals/assets/822035/dc75dedd-928c-48d5-a585-603d9f8b8345">

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Support covariant return types on functions if the return value is a sub-type of the overriding function's return value.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This script does not compile as part of Godot 4.1 but after this proposal was implemented it would work as expected:
```gdscript
class BaseClass extends RefCounted:

	func greetings() -> void:
		print("Hello!")

class SubClass extends BaseClass:
	
	func greetings() -> void:
		print("Hello Sub Class!")

class BaseGreeting extends RefCounted:
	
	func get_obj() -> BaseClass:
		return BaseClass.new()

class SubGreeting extends BaseGreeting:
	
	func get_obj() -> SubClass:
		return SubClass.new()

func _ready():
	var base:BaseGreeting = SubGreeting.new()
	var obj = base.get_obj()
	obj.greetings() # should print 'Hello Sub Class!'
```
Example project of the above:

[Covariant-Example.zip](https://github.com/godotengine/godot-proposals/files/12267448/Covariant-Example.zip)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can't since this is a GDScript core language feature that cannot be worked around easily.

### Is there a reason why this should be core and not an add-on in the asset library?

Cannot be done via addons nor GDExtension.

**Comment by AThousandShips** [comment]
The code will still work just won't be explicit about the type, no?

**Comment by bitbrain** [comment]
> The code without covariance will still work just won't be explicit about the type, no?

The point of this proposal is to use return types explicitly - yes, functionality like this may be possible by not using any return types at all but in my project I want to enforce the use of types, as it has a lot of advantages (readability, performance)

**Comment by AThousandShips** [comment]
In this case you've explicitly typed `base` as the base type, so you wouldn't be able to get any type hinting, so I'm not sure what the value would be here?

**Comment by bitbrain** [comment]
> so I'm not sure what the value would be here?

If I wanted to use `SubGreeting` somewhere, its returned objects can have additional methods that I want to access with type safety.

For example, let's say I have code like this:

```gdscript
func some_method(obj:SubClass) -> void:
   var sub_greeting = obj.get_obj()
   sub_greeting.some_other_method_unique_to_subgreeting()
```
This would not be possible in your example, but I'd have to guess or do a type check first. The above code is an extreme simplification but this is a common use case in Object Oriented Programming. Especially with the introduction of traits in GDScript at some point, it is even more common that the parent function may specify a very vague type and I want to provide a specific return type (but still be compatible with the trait itself)

**Comment by adamscott** [comment]
I did some tests for some context.

| Language | Test | Behavior |
| :--: | :--: | :--: |
| Java | [Test](https://replit.com/@adamscott/SupportCovariantReturnJava) | Behaves as the proposal suggests |
| Swift | [Test](https://replit.com/@adamscott/SupportCovariantReturnSwift) | Behaves as the proposal suggests |
| Typescript/Javascript |[Test](https://replit.com/@adamscott/SupportCovariantReturnTypescript)| Behaves as the proposal suggests <br> _*it don't really checks for signature changes_ |
| C# | [Test](https://replit.com/@adamscott/SupportCovariantReturnCSharp) | Fails. <br> `error CS0115: 'SubGreeting.greetings()': no suitable method found to override` <br> It cannot override the `greetings()` function as the parent class doesn't have the signature `virtual public SubClass greetings()` |
| C++ | [Test](https://replit.com/@adamscott/SupportCovariantReturnCPlusPlus) | Behaves as the proposal suggests |
| OCaml | [Test](https://replit.com/@adamscott/SupportCovariantReturnOCaml) | Behaves as the proposal suggests <br> _*it don't really checks for signature changes_ |

**Comment by dalexeev** [comment]
Note that in addition to method return value **co**variance, the **contra**variance of parameters also makes sense (for example [PHP](https://www.php.net/manual/en/language.oop5.variance.php)). Both cases are consistent with the Liskov substitution principle.

**Comment by bitbrain** [comment]
💖

**Comment by gcardozo123** [comment]
This thread is already closed, but just wanna point out that it also works in C#, but the linked example used the wrong method name when overriding it. It did:
```c#
class SubGreeting : BaseGreeting {
  override public SubClass greetings() {
    return new SubClass();
}
```
instead of
```c#
class SubGreeting : BaseGreeting {
  override public SubClass getObj() {
    return new SubClass();
}
```

**Comment by sjl057** [comment]
Even though this thread is long closed, this doesn't seem to work with typed Arrays.

**Comment by dalexeev** [comment]
@sjl057 Typed arrays are not covariant because they are passed by reference and there are no "read-only" or "write-only" qualifiers in the type system. See the documentation and other issues.

* godotengine/godot#80586
* godotengine/godot#83876
* godotengine/godot#89959
* godotengine/godot#93063
* godotengine/godot#93084
* godotengine/godot#100798
* #7364
* [Wikipedia - Covariance and contravariance (computer science)](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science))
* [GDScript reference - Typed arrays](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays)
