### ISSUE TITLE
Add `bake_finished` signal to VoxelGI.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot-proposals#7458]
### Describe the project you are working on

Just testing VoxelGI.

### Describe the problem or limitation you are having in your project

When baking VoxelGI from a script there's no signal which triggers at the end of the bake. With more threading (groups and such) I think it makes sense to add a signal to let the user know when the bake is finished so they can do some logic after (for example if they bake procedurally and want to start a game after everything is ready).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having signal `bake_finished` will allow procedural games and any other use of baking through a script to time the start of the project after the GI is ready to do its job.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`voxelGI.bake_finished.connect(_on_bake_finished)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think there's a workaround possible at all especially with move towards threads with groups and such.

### Is there a reason why this should be core and not an add-on in the asset library?

VoxelGI is core.

**Comment by Calinou** [comment]
> I don't think there's a workaround possible at all especially with move towards threads with groups and such.

Can't you use `emit_signal()` with a custom signal after calling `bake()` in the script that calls VoxelGI baking? `bake()` is a blocking method, so it should work.

**Comment by viksl** [comment]
I was thinking of that in case this proposal wasn't ok, I just was not sure how things will be changing with more threading getting in. If that's so then yeah, I think I'll close this, if you are ok with it?

**Comment by Calinou** [comment]
> I just was not sure how things will be changing with more threading getting in. If that's so then yeah, I think I'll close this, if you are ok with it?

I don't know how much VoxelGI will be affected by threading changes (if at all). That said, the general policy for adding signals is:

- We only add signals for things that may change under the hood, without you calling a method or setting a property explicitly in a script. If a property *only* changes with explicit user action, you can emit a custom signal yourself.
- We don't add signals that may be emitted every frame, as signals have a performance overhead.

**Comment by Joy-less** [comment]
> > I just was not sure how things will be changing with more threading getting in. If that's so then yeah, I think I'll close this, if you are ok with it?
> 
> I don't know how much VoxelGI will be affected by threading changes (if at all). That said, the general policy for adding signals is:
> 
> * We only add signals for things that may change under the hood, without you calling a method or setting a property explicitly in a script. If a property _only_ changes with explicit user action, you can emit a custom signal yourself.
> * We don't add signals that may be emitted every frame, as signals have a performance overhead. (This is not applicable to VoxelGI, but it applies to nodes like Timer as it was requested in the past.)

@Calinou

Since `bake` is often called by pressing the button in the editor rather than calling the function, this signal would be useful for tool scripts to run code after baking is finished. Currently, there is no way for a tool script to know when the user presses the bake button.
