### ISSUE TITLE
Make property limits of PrimitiveMesh soft limits

### ISSUE THREAD

**Issue by shBLOCK** [godotengine/godot-proposals#7469]
### Describe the project you are working on

Prototyping VFXs.

### Describe the problem or limitation you are having in your project

Some of the limits of PrimitiveMesh properties are a bit too strict.
e.g. the rings property of a TorusMesh can't go above 128.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Introduce a "soft limit" system. Instead of limiting the property values, we limit the mesh data generation time (allow the generation process to timeout to avoid crashing the editor).
Also, use warnings to inform the use of potential performance problems when they try to make the vertex count too high.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See the description.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Of course, we can write custom scripts to generate the meshes. But isn't that the exact purpose of PrimitiveMeshes?

### Is there a reason why this should be core and not an add-on in the asset library?

It involves changing the engine's builtin code, so it shouldn't be an add-on.

**Comment by Calinou** [comment]
You can set the value in a script if you need to go above the limit set in the inspector.

Inspector hints support a `or_greater` hint to allow using values greater than the limit in the inspector, but there's no upper bound when you do this.

**Comment by shBLOCK** [comment]
Oh, I tried to set them in the script but the inspector panel always shows the max value so I thought it wasn't working.

But when testing things I've noticed that how the limits work is very inconsistent across different PrimitiveMeshes, some of them don't have a limit at all and allow you to easily crash the whole editor by setting the values too high (for example the SphereMesh). (Also see: scene/resources/primitive_meshes.cpp)
Should I open another issue for this?

**Comment by Calinou** [comment]
> But when testing things I've noticed that how the limits work is very inconsistent across different PrimitiveMeshes, some of them don't have a limit at all and allow you to easily crash the whole editor by setting the values too high (for example the SphereMesh). (Also see: scene/resources/primitive_meshes.cpp)
Should I open another issue for this?

I forgot about that. I guess we should make TorusMesh's behavior consistent with those meshes instead.
