### ISSUE TITLE
Allow Customization of Leading and Descent Metrics for Single Line Text Boxes like LineEdit

### ISSUE THREAD

**Issue by Lemonymous** [godotengine/godot-proposals#7470]
### Describe the project you are working on

Prototyping compact ui for 2d games.

### Describe the problem or limitation you are having in your project

I will use LineEdit as my example node. But the issue extends to other nodes as well.

Currently, the LineEdit; a node designed for a single line of text; enforces a minimum height. I am not sure what it is influenced by, though it could possibly be by the leading (line spacing) and descent (baseline offset) metrics of the font used. This design choice limits the flexibility of the LineEdit node and forces me to have larger text boxes than I need or would like.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Under [Theme] > [Font Size] there could be additional options to customize the leading and descent of the font used for the text in the node.
Or, if that should not be the responsibility of the control node, but instead the responsibility of the font object, then that could be options in the font object.
For multiline text, leading and descent makes sense for the most part. However, for single line text boxes, it should not be enforced quite so strictly in my opinion.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am finding it very difficult to work around. To get the text box sizes I want, I feel I have to forgo using any containers that lay out nodes in any way.
The only (bad) solutions I have found so far, are to make the text have no StyleBox; and then use separate nodes to display the graphics for the text box, and then lay them all out manually.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the ui node's usability out of the box.

**Comment by Calinou** [comment]
cc @bruvzg

> Under [Theme] > [Font Size] there could be additional options to customize the leading and descent of the font used for the text in the node.
> Or, if that should not be the responsibility of the control node, but instead the responsibility of the font object, then that could be options in the font object.

I think customizing the leading/descent metric is the responsibility of the font, not the location where it's used.

**Comment by bruvzg** [comment]
It's already possible to do, you can use a new `FontVariation` resource as a theme override and set negative top / bottom extra offsets to adjust it.

**Comment by Lemonymous** [comment]
You are completely right! I totally missed that. I tried looking and asking, but couldn't find anything, so I figured I would open up a proposal.

It is quite well hidden, but sure enough seems to do what this proposal is asking for.

Thank you for the information. I will close this proposal now.
