### ISSUE TITLE
Reimplement ability to rotate/modulate tiles in a TileMap

### ISSUE THREAD

**Issue by AeolianTheComposer** [godotengine/godot-proposals#7473]
### Describe the project you are working on

A rage "I wanna be the boshy" styled platformer with a huge variety of tiles.

### Describe the problem or limitation you are having in your project

Rotating tiles with alternatives is incredibly painful and slow. 

Also drawing the tiles (in scenes) is less convinient without the rotation keys.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Return the ability to rotate tiles individualy

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same as in Godot 3.4, with keys

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. I'm planning on adding several dozens of tilemaps with many tiles of different sizes and colors, consisting of several different collision shapes. I physically cannot make and rotate 3 copies, redraw all the collisions, and adjust center points for EACH tile manually. 

### Is there a reason why this should be core and not an add-on in the asset library?

As far as I can tell, it's a pretty popular request that many people also want

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating with https://github.com/godotengine/godot-proposals/issues/3967.

**Comment by AeolianTheComposer** [comment]
Thank u <3
