### ISSUE TITLE
Add get_hovered_meta() method to RichTextLabel.

### ISSUE THREAD

**Issue by axilirate** [godotengine/godot-proposals#7477]
### Describe the project you are working on

A UI based game with heavy use of tooltips.

### Describe the problem or limitation you are having in your project

I would like to be able to know if a mouse is inside the boundaries of a given word with a meta.
the `meta_hover_started` signal is not reliable for some cases (when the mouse is already inside or something obscures it) and I tend to avoid using signals.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

theres a signal `meta_hover_started` 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`if rich_text_label.get_hovered_meta() == "some text":`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

probably not, the only thing i can think of is manually calculating its position based on character size, distance and offst.

### Is there a reason why this should be core and not an add-on in the asset library?

because probably the code for this exists already (there's is a related signal), its just not exposed.

**Comment by Calinou** [comment]
@axilirate Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by axilirate** [comment]
I've decided to make my custom RichTextLabel instead using labels and containers and getting the rect of each one.
