### ISSUE TITLE
Convert an array into byte stream for SSBO and push_constant uniform fill out.

### ISSUE THREAD

**Issue by pkpro** [godotengine/godot-proposals#7478]
### Describe the project you are working on

Experimenting with compute shaders

### Describe the problem or limitation you are having in your project

Preparing PackedByteArray for SSBO or push constants fill-out is multistep, inconvenient, error prone and slow.
Maintaining consistent variable types and structures in GDScript and compute shaders  is a separate task anyway as there is no builtin functionality in Godot. This is OK for demos or experiments, but this is no go for large projects which you have to maintain.

Consider following parameters that you have to pass to SSBO of a compute shader (or to push_constant):
```GDScript
                 var params:Dictionary = { # Vector3 must be 16-bytes aligned.
		"camera_postion":Vector3(0,0,0),
		"light_energy":$DirectionalLight3D.light_energy, # last 4 bytes of alignment for previous vec3
		"light_direction":$DirectionalLight3D.global_transform.basis.z,
		"seed":int(seed_), # last 4 bytes of alignment for previous vec3
		"sun_disk_size":float(sun_disk_size),
		"phase_g":float(G),
		"clouds_density":float(clouds_density),
		"clouds_coverage":float(clouds_coverage),
		"clouds_low":float(clouds_low),
		"clouds_high":float(clouds_high),
		"weather_scale":float(weather_scale),
		"time":float(time),
		"time_scale":float(time_scale),
		"time_offset":float(time_offset)
	}
```

You can't convert it directly with var_to_bytes, because you will get 156 bytes instead of 72 which are required to fill the SSBO in compute shader, due to encoding. 

You need to convert all of these params into floats then push them into PackedFloat32Array, then convert it to PackedByteArray and then update your SSBO or push to constants uniform. 

Like this:

```GDScript
        var f32a:PackedFloat32Array = PackedFloat32Array()
        for k in params:
		match(typeof(params[k])):
			TYPE_VECTOR3:
				arr.push_back(params[k].x)
				arr.push_back(params[k].y)
				arr.push_back(params[k].z)
			TYPE_FLOAT:
				arr.push_back(params[k])
			TYPE_BOOL: # what value will be stored into float in SSBO if the value is 'true' ?  Ok, it will not be 0 so it will probably be true
				arr.push_back(float(params[k]))
			TYPE_INT:   # I wonder what happens here if in SSBO this is a uint value ... 
				arr.push_back(float(params[k]))
# for the push_constant you will probably need to add some more bytes at the end for alignment.
```

**So this makes a semantic conversion not the bit conversion, and may cause a lot of trouble and debugging.**

Maintaining the code for consistency between params in GDScript is a separate task anyways but this makes it even  more complicated and error prone.

And you do the conversion within GDScript, which is slow especially when you want to use low latency push_constant which suppose to be the fastest. This makes no sense at all. 

The better solution would be to introduce the "SSBO" class that acts as a Dictionary in GDScript, but supports limited amount of types. This can be done in GDScript though and if you inherit from Resource class then it will be serializable out of the box too. You can add a function that generates glsl.inc for your push_constant or SSBO, which partially solves the maintaining problem. 

So no need in additional functionality? 

Nope. 

**There is still a problem of semantic vs bit conversion.**

And performance problem still there but it can be discarded for now.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Introduce the to_raw_bytes() GlobalScope method which is able to convert bit-wise some limited amount of Variants (Array, int, float, bool, Vector2, Vector3,Vector4,Vector2i,Vector3i,Vector4i) . 

This PR solves the bit-wise conversion problem and simplifies the conversion to a byte stream from an Array. 
to_raw_bytes() does not convert the Dictionaries though (yet?). It does not implement anything that can be done in GDScript, but may come handy when you need to create "class_name SSBO extends Resource" which will do the params maintenance for you.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is the PR https://github.com/godotengine/godot/pull/80500

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Bit-wise conversion will be very complicated  in GDScript in this case. I'm not as advanced in GDScript to say that this is impossible, though I found no easy way here.

### Is there a reason why this should be core and not an add-on in the asset library?

Bit-wise conversion functionality should be the "first class support" not the external library or extension.

To improve performance one can consider making an SSBO/push_constant class as an extension/library in C++ instead of GDScript, though, which does not discards the requirement for bit-wise conversion functionality, especially for push_constant which must be low latency.

**Comment by AThousandShips** [comment]
Adding a script specific function to this scope isn't a good idea IMO

It is trivial to work around with the relevant methods on `PackedByteArray` like `encode_float`

**Comment by pkpro** [comment]
> Adding a shader specific function to this scope isn't a good idea IMO, it belongs in `RenderingDevice`
> 

This totally might be. I can't decide on this. Though the functionality itself not 100% belongs to RenderingDevice it does not belong to the GlobalScope either. It might be an ideal solution to make an overload for rd.buffer_update with Dictionary instead of PackedByteArray, which will convert the dictionary into byte stream and update the SSBO. Same goes for push_constant.

> It is trivial to work around with the relevant methods on `PackedByteArray` like [`encode_float`](https://docs.godotengine.org/en/stable/classes/class_packedbytearray.html#class-packedbytearray-method-encode-float)
> 

It is not. It is a lot of slow GDScript code in the place when you measure each micro second.


> The data passed to a shader is known beforehand and having a generic function makes little sense to me, using the availbale methods on `PackedByteArray` is sufficient, and most of the time you'd be passing data through a `PackedFloat32Array` anyhow, as most data passed should be clean and simple
> 

And this involves a lot of GDScript code, that should be used for the flow control and minimally for the computation. 

> I'd instead suggest adding `push_back_X` to `PackedByteArray` making it easier to do encoding without having to resize

This might be  good start. But it is not enough. There should be a function on a C++ level that reduces time to prepare the byte stream.

**Comment by pkpro** [comment]
Wrong place for this functionality, incomplete implementation and doubts if this will ever be needed.
