### ISSUE TITLE
Simplify Collisions

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#7484]
### Describe the project you are working on

I am working on a spaceship game.  

### Describe the problem or limitation you are having in your project

I want to be able to handle both overlaps and collision response at the same time

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like to have area2D and aera3D api moved into CollisionObject2D and CollisionObject3D as abstract function.
This would allow directly querying collisions on contact with PhysicsBody2D and PhysicsBody3D

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

These would be moved into their respective 2d and 3d equivalent of CollisionObject's
![image](https://github.com/godotengine/godot-proposals/assets/2453707/1bfcbe5b-d8e2-44d9-8534-920836029565)

These methods would also be moved
![image](https://github.com/godotengine/godot-proposals/assets/2453707/90b4db33-3619-4109-8275-a31880252f14)

Area2D would simply become a non physical collision object and for implementing physical area changes like low gravity.
PhysicsBody2D and 3D would then implement a solid property which would enable or disable solid collisions

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Scenes are requires to do such a thing it is not possible as far as I know to implement such a feature purely based on scripts or class_name.  

### Is there a reason why this should be core and not an add-on in the asset library?

It is currently not easy to implement a object that both has collision response and collision testing.
CharacterBody's have test_move but that doesn't tell us when it enters or exits

It is also not possible to have a base class with collision due to the splitting hierarchy of areas and physicalBodies

**Comment by aaronfranke** [comment]
> I would like to have area2D and aera3D api moved into CollisionObject2D and CollisionObject3D as abstract function.
> This would allow directly querying collisions on contact with PhysicsBody2D and PhysicsBody3D

I disagree, this goes against the Godot way of doing things. In Godot each node has a singular purpose and you build scenes out of many of them. You can just add an Area node as a child to achieve this affect. Trying to make PhysicsBody do this would be too much for one node.

> Area2D would simply become a non physical collision object and for implementing physical area changes like low gravity.
> PhysicsBody2D and 3D would then implement a solid property which would enable or disable solid collisions

So you want Area to be non-solid, but PhysicsBody can be either solid and non-solid? It doesn't make much sense.
