### ISSUE TITLE
Add `horizontal_alignment` property for RichTextLabel

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot-proposals#7491]
### Describe the project you are working on

UI

### Describe the problem or limitation you are having in your project

This is just a little/minor detail. You can do `[center]` for horizontal alignment on `RichTextLabel`, but when you're assigning the text of that `RichTextLabel` programatically you may "accidentally" wipe that `[center]` (e.g. forget `+=` instead of `=`, or `append_text`).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A `rich_text_label.horizontal_alignment` property which avoids the issue of wiping `[center]` and eliminates its need.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
rich_text_label.horizontal_alignment = CENTER
```

Instead of:

```gdscript
rich_text_label.text = "[center]"
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Y

### Is there a reason why this should be core and not an add-on in the asset library?

GDScript API

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/6674.

**Comment by BaconEggsRL** [comment]
Thank you for this!
