### ISSUE TITLE
Support Class Icon in GDExtesion

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot-proposals#7501]
### Describe the project you are working on

A GDExtension
https://github.com/Gallilus/icospheremesh-gdextension

### Describe the problem or limitation you are having in your project

Using the CPP bindings I have not found how to add an icon like.
https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#registering-named-classes

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow to specify an icon path to a class.

Depending on the implementation it may be needed to add the .svg to the exported extension.
But preferably it will be backed in to the executable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Having a third optional parameter in GDCLASS macro like
`    GDCLASS(IcoSphereMesh, ArrayMesh, "res://bin/IcoSphereMesh.svg")`
or creating an additional macro to add the icon

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I do not see how to work around this.

### Is there a reason why this should be core and not an add-on in the asset library?

It is a core feature supported by GDScript.
So needs support by Extension

**Comment by dsnopek** [comment]
Yes, this is already implemented!

I think the problem is that you've got `[Icon]` in your .gdextension, when it should be `[icons]`.
