### ISSUE TITLE
Move (Un)favorite selected item/ node button in create dialogue away from search bar next to resource/node

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot-proposals#7502]
### Describe the project you are working on

A project using - surprise - nodes and resources

### Describe the problem or limitation you are having in your project

It would make much more sense to move the button next to the resource/ node, cause you don't favorite the entered search string but the selected item.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Moving the button directly next to the selected type.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The implementation of the proposal could look something like this:

When the node is not favorited
![Godot Node Favorite Proposal non Favorited](https://github.com/godotengine/godot-proposals/assets/111653551/1a338134-fe5d-4d86-bb29-1df34f22dfcb)

When the node is favorited
![Godot Node Favorite Proposal Favorited](https://github.com/godotengine/godot-proposals/assets/111653551/bddc2da6-7ab1-40ef-b1d8-5dd3ef865eb9)

Wether the button is only visible when a type is selected or if becomes visible as soon as a type is hovered is up to debate, though I think making the button visible on hover makes more sense.

(Also I just noticed by looking at the images again that the "last used" and "favorites" backrounds have different colors, but I guess that's outside of the proposal)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can not be worked around with a few lines of script

### Is there a reason why this should be core and not an add-on in the asset library?

Creating resource and nodes is something a godot user will do multiple times a day :)

**Comment by theraot** [comment]
> Wether the button is only visible when a type is selected or if becomes visible as soon as a type is hovered is up to debate, though I think making the button visible on hover makes more sense.

If this is implemented, I would rather have it work when it is selected, that way it works - without additional tweaks - for people navigated with keyboard only, and also for people using a touch screen. Plus it does not make the button harder to discover.
