### ISSUE TITLE
Replace "Override pose" checkbox in "BoneAttachement3D" with a dropdown menu 

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot-proposals#7506]
### Describe the project you are working on

A project using a lot of rigs and rig related nodes in Godot

### Describe the problem or limitation you are having in your project

Because the  `override_pose` option is just a checkbox, I only discovered that you can use a `BoneAttachement3D` not only to copy the position of a bone to another `Node3D`, but that you can also override the transform of a bone.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the `override_pose` checkbox in `BoneAttachement3D`  a dropdown menu instead to make it more clear that this fundamentally changes how the node works.

This change would also more clearly communicate with the user that the `BoneAttachement3D` node can not only copy but also override the transform of a bone.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Have a dropdown at the top in the inspector for `BoneAttachement3D` with 2 options: `Copy Pose` and `Override Pose`.

If `Override Pose` is selected, the node will do the same as it currently does when the `override_pose` checkbox is ticked.
If `Copy Pose` is selected, the node will do the same as it currently does by default.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You could make a custom type and create an exported enum with the two suggested options.

### Is there a reason why this should be core and not an add-on in the asset library?

It affects a core node.

**Comment by Calinou** [comment]
Changing a property's type breaks compatibility with existing projects, so a new property needs to be added instead and the current property needs to be deprecated.
