### ISSUE TITLE
Make Line2D be white by default

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#751]
**Describe the project you are working on:**

Testing different ways of drawing circle outlines.

**Describe the problem or limitation you are having in your project:**

Line2Ds have a blue color by default, and added textures have a bluish tint because of this. This is different from other nodes, which are modulated white by default.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The color should be white by default.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Change this to white:
https://github.com/godotengine/godot/blob/b5251eb00f7daa339ad61923f16608432a902f46/scene/2d/line_2d.cpp#L46

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Yes.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It is a very small quality of live improvement.

**Comment by clayjohn** [comment]
I agree, anything that takes a texture should be white by default.

**Comment by Xrayez** [comment]
I have a related PR but for `Path2D`: godotengine/godot#36035.
