### ISSUE TITLE
Add `ColorHTML` function to assign the html-initialized `Color` to constants

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-proposals#7515]
### Describe the project you are working on

Usability enhancement. Any project may receive benefit, mine too. 

### Describe the problem or limitation you are having in your project

Usability problem with the Color's.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Currently, when you attempt to set up a constant with `html` method like this:

`const RED = Color.html("#FF000000")`

The editor emits an error like this:

![image](https://github.com/godotengine/godot-proposals/assets/3036176/e3b0b72c-6899-4476-ad54-bd5bc30eee63)

This can be surpassed if I declare `var` instead of a `const` - but it's uncomfortable, - I want to have a way to declare an exactly constant instead of variable but initialized by the output of this method.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add global method `ColorHTML`, which is similar to already existed `Color8`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by dalexeev** [comment]
You can use `Color()` constructor:

```gdscript
const RED = Color("#ff0000")
```

There is also discussion (godotengine/godot#41673, godotengine/godot#71091) about treating pure methods of `Variant` types called on constants as constant expressions (but for that we need to store the data somewhere, for example `Array.pick_random()` is not pure).

**Comment by Chaosus** [comment]
```gdscript 
const RED = Color("#ff0000")
```

Ah, okay, that seems to be easy enough, there is no need to separate function then.
