### ISSUE TITLE
Expose the get_rid property from joints

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot-proposals#7519]
### Describe the project you are working on

I am working on a godot box2d extension. I wanted to extend the pin joint with angle limits, and I thought a good way for that was just sending a pin_joint_param with an a value that is unused and send angle limits in that.

### Describe the problem or limitation you are having in your project

Extending the default PinJoint2D interface.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Exposing get_rid so I can get the joint rid and call functions with it on PhysicsServer2D

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Expose from PhysicsServer2D the method get_rid for Joint2D and  from PhysicsServer3D the method get_rid for Joint3D.

eg.

get_rid()

the property is already present in PhysicsServers as _get_rid()

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If you create the pin from editor, there is no way to get the rid currently. The only solution would be to create the pin manually and get the rid from there. Eg. by calling PhysicsSpace.joint_create()...

### Is there a reason why this should be core and not an add-on in the asset library?

It can't be implemented in an add-on.

**Comment by AThousandShips** [comment]
This propery isn't in the server, but on the joint itself which handles it

**Comment by Ughuuu** [comment]
Right, sorry, my bad, it's on the joint as get_joint. It's not on the servers. I was thinking about the joint_create methods that return rid, but there is indeed no get_rid method on servers.
