### ISSUE TITLE
Automatically refresh project settings when `ProjectSettings.set_setting()` is called

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-proposals#7525]
### Describe the project you are working on

An editor plugin

### Describe the problem or limitation you are having in your project

When an editor plugin add or remove setting(s) in a new category, the project settings window has to be reopened in order for the category to be shown or removed. This poses a slight inconvenience.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This is a QoL improvement.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Refresh the "General" tab of the project settings window when `ProjectSettings.set_setting()` is called.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Project settings window is core

### Is there a reason why this should be core and not an add-on in the asset library?

See above

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/25865.

I consider this to be a bug, so please open an issue on godotengine/godot with a MRP attached.

**Comment by atirut-w** [comment]
> with a MRP attached

But it's a consistent thing though?

**Comment by AThousandShips** [comment]
It being consistent isn't a factor, attach an MRP to make it easier to test

**Comment by atirut-w** [comment]
Alright. I'll be sure to open an issue (hopefully) this afternoon.

**Comment by atirut-w** [comment]
Done.
