### ISSUE TITLE
Built-in scripts not showing name nor loading on startup in code editor

### ISSUE THREAD

**Issue by lycanhunt3r** [godotengine/godot-proposals#7531]
### Describe the project you are working on

(not important) A voxel game and tools for item/map management.

[NOTE] I don't know if this issue is in the right topic, since it doesn't seem to be a "bug" nor exactly a "feature", but more like the completion of an unfinished feature. Excuse me if I'm posting this in the wrong place.

### Describe the problem or limitation you are having in your project

All Built-in Scripts have the name of the scene instead of their attached node in the code editor, making really confusing to manage through the tabs. They also do not load in properly on startup like normal scripts.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have the tab's text refer to the name of the node it is attached on, it'll help to manage the code files better.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Have the tab's text refer to the name of the node it is attached on. Or perhaps allow to add a custom name to it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think it has work arounds, it's pretty direct.

### Is there a reason why this should be core and not an add-on in the asset library?

It's an essential feature for the code editor while using built-in scripts.

**Comment by KoBeWi** [comment]
Scripts using scene names is intended. The script doesn't know what node it's attached to and also they can be attached to multiple nodes. When you create new built-in script, you get an option to give it a name (you can edit it under Resource inspector section afterwards). It will show in the script editor.

The other issue is already tracked in https://github.com/godotengine/godot/issues/26481

**Comment by lycanhunt3r** [comment]
Thanks for answering, @KoBeWi , that resolves the tab management issue perfectly.

For some reason I thought checking the "built-in" box disabled its naming line, perhaps the attached node's name should be placed as a default to be more intuitive? Anyways, I'll close the issue since it's proposed feature already exists. Thanks again!

**Comment by KoBeWi** [comment]
> perhaps the attached node's name should be placed as a default to be more intuitive?

I considered that when implementing the feature, but most of the time when using built-in scripts in a scene there is only one - in the root node. Thus scene name is usually enough to identify it and name is redundant.
