### ISSUE TITLE
A "void" or "tag" metadata type for when only "has_meta" is used to get all the info

### ISSUE THREAD

**Issue by sammonius** [godotengine/godot-proposals#7538]
### Describe the project you are working on

A 3D game with simple mechanics similar to Baldi's Basics.

### Describe the problem or limitation you are having in your project

I'm using metadata to mark clickable objects, and implementing a "clicked" function inside each of these objects. These objects are marked with a tag called "is_clickable". The value doesn't matter because I'm using "has_meta" only to get all the data (kind of like "#ifdef" in C/C++), but I give it a boolean metadata type since there's no option for none.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A metadata type called "void" or "tag" that can be used in cases like these.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would be added to the list of possible metadata types. Getting it's value would allways return null.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around with zero lines of script :) . I just think it would be a nice feature.

### Is there a reason why this should be core and not an add-on in the asset library?

Adding it would probably be like 5 lines of code.

**Comment by Zireael07** [comment]
"Nice feature" does not explain why it should be in core.

**Comment by KoBeWi** [comment]
Metadata is stored in a HashMap and key is always Variant. `null` is reserved value; setting it will erase the key.
There is zero performance benefit from this proposal and adding a special value that returns null would only complicate the implementation.

Maybe for convenience we could add a default value for `set_meta()`, which would be implementation detail and intended to use with `has_meta()`, but making `get_meta()` return null on this key is not worth it.

**Comment by Calinou** [comment]
I think using a boolean `true` as a value makes more sense, since it makes the key's value *truthy*.

**Comment by Mickeon** [comment]
The example used in the proposal can be simplified in many ways that do not require using metadata.

For one, if implementing a `clicked` method inside each object is a requirement, it would also be possible to define a `is_clickable` boolean property within the script (It _may_ also be more efficient).

Metadata is my personal opinion simple, efficient and good enough for most use cases. When it is not, it's worth considering rethinking the code around it.

**Comment by KoBeWi** [comment]
> For one, if implementing a clicked method inside each object is a requirement, it would also be possible to define a is_clickable boolean property within the script (It may also be more efficient).

If a method exists when `is_clickable` exists, there is also `has_method()`, which doesn't require any variaables.

**Comment by sammonius** [comment]
Yeah, node groups were what I was looking for. I should have dug around in the docs a bit more before making the proposal. Thanks for the help everyone.
