### ISSUE TITLE
Add gdshader support for custom textures

### ISSUE THREAD

**Issue by Redwarx008** [godotengine/godot-proposals#7539]
### Describe the project you are working on

Now that  https://github.com/godotengine/godot/pull/79288 has implemented the creation of custom textures, there is very little that can be done if it is not available for gdshader.

### Describe the problem or limitation you are having in your project

Image does not support many formats, such as RG16 (UInt), so we want to be able to use custom textures.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

as title

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We can add a static abstract function to the class Texture， Texture2D, Texture3D and TextureLayered should all implement it, such as：

``` c++
Texture2D  CreateFromRD(RID textureRD);
```

A warning can be issued if the format of the texture does not support certain operations, users should be responsible for their own behavior.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

can not

### Is there a reason why this should be core and not an add-on in the asset library?

This is the render core

**Comment by Redwarx008** [comment]
> Why close?

I found that texture2Drd can already do it.

**Comment by Calinou** [comment]
- Superseded by https://github.com/godotengine/godot-proposals/issues/7540.
