### ISSUE TITLE
New project, store Default directory for next time New Project, or use same folder as last time

### ISSUE THREAD

**Issue by BdR76** [godotengine/godot-proposals#7544]
### Describe the project you are working on

I'm new to Godot and have created a lot of small projects to how everything works. I'm using a separate Godot folder in a game projects folder. However, every time I create a New Project it defaults to `C:/Users/myusername/OneDrive/Documents`.

### Describe the problem or limitation you are having in your project

It's not project specific, but it's a nice-to-have in the Godot IDE. Especially for new-comers to Godot who create lots of new projects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Store the root folder from the last `New Project` user action, so that the Godot New Project dialog can pre-fill it by default the next time, so that you don't have to go throught the directory lists to find the custom Godot folder.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1) user creates a new project
2) Godot takes the folder name, minus the project folder (=top-level folder)
3) Godot stores this root folder in the internal settings somewhere
4) Next time user creates a new Godot project the dialog defaults to the last root folder

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, but the user can search and select their folder by hand each time

### Is there a reason why this should be core and not an add-on in the asset library?

Because it's not project specific, it's part of the core Godot IDE

**Comment by dalexeev** [comment]
There is `filesystem/directories/default_project_path` editor setting:

![](https://github.com/godotengine/godot-proposals/assets/47700418/9a3b7d00-7e92-4c85-a77e-4829dae94d30)

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1312.
