### ISSUE TITLE
[LSP] Allow language server to be ran independent of Godot Editor

### ISSUE THREAD

**Issue by ryanabx** [godotengine/godot-proposals#7558]
### Describe the project you are working on

Many various Godot projects

### Describe the problem or limitation you are having in your project

When working with Visual Studio Code, the godot editor must be open to get gdscript intellisense.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allowing the language server to be ran independently of the Godot editor would allow external editors to spin up the language server as needed, independent of whether the Godot editor is open.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A potential way this could work is having a command line argument for the godot executable to run the language server only. This would allow the default behavior to work, but 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The default behavior could still be preserved while the command line option exists.

### Is there a reason why this should be core and not an add-on in the asset library?

I could be wrong, but language server code is probably not open to extensions.

**Comment by Calinou** [comment]
This should already be feasible, it just needs documentation: https://github.com/godotengine/godot-proposals/issues/3300

**Comment by ryanabx** [comment]
> This should already be feasible with `--headless --editor` (4.x) or `--no-window --editor` (3.x). It just needs documentation: #3300

Thank you! I might take a stab at modifying the godot-vscode-extension to run a headless version of the editor as a language server on startup of the extension if Godot is not found.

**Comment by Calinou** [comment]
> I might take a stab at modifying the godot-vscode-plugin to run a headless version of the editor as a language server on startup of the extension if Godot is not found.

Sounds good :slightly_smiling_face:

**Comment by ryanabx** [comment]
> > I might take a stab at modifying the godot-vscode-plugin to run a headless version of the editor as a language server on startup of the extension if Godot is not found.
> 
> Sounds good 🙂

I added a customizable config variable to the plugin that lets a user choose to automatically start up the editor or a language server when the extension starts trying to connect to an lsp.
https://github.com/godotengine/godot-vscode-plugin/pull/488
