### ISSUE TITLE
Add customisable guides to 2D view

### ISSUE THREAD

**Issue by JohnGabrielUK** [godotengine/godot-proposals#7569]
### Describe the project you are working on

A 2D Metroidvania with a fixed camera that snaps between screen-sized rooms.

### Describe the problem or limitation you are having in your project

When creating the game world as a `TileMap`, there isn't an easy way to see the boundaries between one screen and the next.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When working on a 2D scene, there would be the option to show guide lines repeating at a given X and Y offset. So, if my rooms are 480x224, I should be able to set the offset as that, and easily see where the boundaries are.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When in the 2D view, I click "View". A new option called "Configure Guides..." is available. I click on it, and enter my desired width/height. When I click okay, the configured lines are visible in the 2D view.

![image](https://github.com/godotengine/godot-proposals/assets/5272862/adc9cb2f-d173-4079-99c2-5c1b7bd59097)

![image](https://github.com/godotengine/godot-proposals/assets/5272862/85d66e57-b7b3-467d-99be-6939db8eec6f)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really. You can make your own references by placing dummy textures or such, but it's an inelegant solution.

### Is there a reason why this should be core and not an add-on in the asset library?

Personally, I believe the ratio of code size versus usefulness to a wide range of users warrants this feature being in the core program.

**Comment by KoBeWi** [comment]
This can be easily achieved by placing a `@tool` script in the root node that draws the lines.  Sure, you need to add it in every scene, but I think it's pretty normal to have some sort of Map script; I have one in every of my projects.

**Comment by aalcutt** [comment]
This is a feature of the editor I have always wanted as well. In the past I have resorted to using the grid rulers and dragging them across the map as needed. The `@tool` idea is a nice suggestion as well and I never thought of that and will likely use that as a work around for the time being. I still think this would be a nice built in enhancement to the 2D view though.

**Comment by Calinou** [comment]
You could also set the grid size to 480×224, but this will make snapping work according to those coordinates.

**Comment by JohnGabrielUK** [comment]
As seen above, duncathan has a similar proposal (#7588), which I believe is a better way of solving the same problem.
