### ISSUE TITLE
Allow arithmetic operators between integer and float Vectors

### ISSUE THREAD

**Issue by ciqven** [godotengine/godot-proposals#7575]
### Describe the project you are working on

A simple demo implementation of 2d Gerstner Waves, but any game involving Vector math should benefit from this.

### Describe the problem or limitation you are having in your project

I just tried to multiply a `Vector2i` by a `Vector2`. I expected this to do the Vector equivalent of multiplying an `int` by a `float` - that is, return a `Vector2` with the result of the (float) multiplication. instead, I got an editor error:

`Invalid operands to operator *, Vector2i and Vector2.`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In PR https://github.com/godotengine/godot/pull/57607, this is briefly discussed as **reduz** comments:
> I also noticed you can't do vector operators between vec2i and vec2 (and vec3i and vec3), I never added those operators and it seems nobody asked for them, but it should not be super difficult to add if somebody asks for it.

So I am asking for at least the addition, subtraction, multiplication and division operators to work with mixed `VectorNi` and `VectorN` operands.

A "stretch goal" could be to allow for the logical comparison operators as well `(==, !=, <, <=, >, >=)`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I propose for the behavior to mimic the same arithmetic on `int` and `float` operands as much as possible. In other words, the returned type would be a floating point vector, and the operation would be performed as if both operands were floating point vectors. Examples:

```
Vector2i(5, 10) + Vector2(2.0, 2.4) # Vector2(7.0, 12.4)
Vector2i(100, 10) - Vector2(25.5, 1.25) # Vector2(74.5, 8.75)
Vector2(0.05, 0.1) * Vector2i(100, 100) # Vector2(5.0, 10.0)
Vector2(50.0, 10.5) / Vector2i(2, 2) # Vector2(25.0, 5.25)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, this can be worked around by doing something like `Vector2(vec2i) * vec2`. 

However, this is not intuitive and diverges from the expectations set by `int * float` working.

This workaround also introduces extra boilerplate that makes the code and intentions harder to read (in my opinion, of course).

### Is there a reason why this should be core and not an add-on in the asset library?

This is an addition to the basic Godot types, therefore should be in the core.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/5545.
