### ISSUE TITLE
Custom Resolutions for movies recorded with movie maker.

### ISSUE THREAD

**Issue by dddnk** [godotengine/godot-proposals#7594]
### Describe the project you are working on

A simple Four dimensional N-Body physics simulator.

### Describe the problem or limitation you are having in your project

I have an annoying limitation in the built-in Movie maker mode where I can record up to 1918 x 1078 due to me having a 16:9 1080p display, when I wish to record in 2160p or 4320p and downscale the high resolution video to get a really well anti-aliased image with no loss of detail.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A menu under editor/movie_writer/ which allows a custom resolution to be set independent of screen resolution.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A menu under editor/movie_writer/ which allows a custom resolution to be set independent of screen resolution.
There will be a check box to enable/disable this feature, and maybe, optionally a dropdown showing downscaling options, so the window size still fits within you screen resolution.
Example: recording 2160p movie. The window is scaled down to fit within a 1080p display, but is still internally rendered at 2160p, so the frames are still at the desired resolution.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I have very limited knowlege of the game engine, but It may be possible to add in a compact way.

### Is there a reason why this should be core and not an add-on in the asset library?

This can double as SSAA (Supersampling Anti-Aliasing), as an option.

**Comment by Calinou** [comment]
This is already technically feasible: https://github.com/godotengine/godot-proposals/issues/5809#issuecomment-1320408195

**Comment by dddnk** [comment]
Thanks for the help!
