### ISSUE TITLE
Separate the language of the "tooltips" and the editor.

### ISSUE THREAD

**Issue by kone9** [godotengine/godot-proposals#76]
I would love to have 2 options for the language one where the language of the program environment is chosen and another option where you can choose the language of the tooltips.
This is something I always say to all program developers, since maintaining the interface in English helps make the tutorials universal, however having the tooltips in the language of each one helps to understand the tool ... I think that it is very important to have the tooltips and the language of the editor separately.
In my case I speak Spanish and use blender3D and what I do is keep the interface in English, but the tooltips in Spanish, it doesn't matter if the guy who does a tutorial speaks in Japanese, while the interface is in English I understand what he does looking the procedure and if I have any doubt, I have there the toolstips in Spanish to understand the tool a little more ... I hope they implement it, I think this is something very necessary and is a concept that I only saw in Blender3D ...
<img width="799" alt="Screenshot_1" src="https://user-images.githubusercontent.com/12847027/64955364-6f756200-d85e-11e9-9d8e-1b97d40ae7f3.png">
<img width="793" alt="Screenshot_2" src="https://user-images.githubusercontent.com/12847027/64955365-700df880-d85e-11e9-931c-ef41feb2bb7c.png">

<img width="799" alt="Screenshot_3" src="https://user-images.githubusercontent.com/12847027/64955768-7cdf1c00-d85f-11e9-8752-dcbf71cf3255.png">

**Comment by willnationsdev** [comment]
Hey again @kone9. Please make sure your post is structured according to the Issue template. This will help us ensure that we get all the information we need from you.

**Comment by kone9** [comment]
> Hey again @kone9. Please make sure your post is structured according to the Issue template. This will help us ensure that we get all the information we need from you.

ok, the issue is that there was no template, I will recreate it ..

**Comment by Calinou** [comment]
For future referencce, this proposal was recreated in #77.
