### ISSUE TITLE
Options for valid characters in LineEdit

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot-proposals#7609]
### Describe the project you are working on

I am very much developing a deep programmer simulator which mainly consists of a user interface.

### Describe the problem or limitation you are having in your project

I often need a LineEdit that only has the ability to enter numbers

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose to add settings for LineEdit to the inspector that determine which characters can be entered, letters, numbers, or both if the checkboxes are enabled both here and there.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When changing these options in real time, remove invalid characters? This is a rather controversial point.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I've tried this with signal processing and character-to-float conversion, but there are various problems.

### Is there a reason why this should be core and not an add-on in the asset library?

This addition is too small for a plugin, but very useful for newbies and for LineEdit itself.

**Comment by timothyqiu** [comment]
See also #7193

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating with https://github.com/godotengine/godot-proposals/issues/7193.

> I often need a LineEdit that only has the ability to enter numbers

The easiest solution is to use the SpinBox node instead of LineEdit.
