### ISSUE TITLE
Editor option:  Don't change the current script when opening or changing scene

### ISSUE THREAD

**Issue by IIGreed** [godotengine/godot-proposals#7621]
### Describe the project you are working on

Affects all kinds of projects

### Describe the problem or limitation you are having in your project

While editing a script you sometimes want to check what the node tree of a scene looks like because it may be relevant for your current script but when doing this the editor will open the scene main script which is easily accessible from other means.
I know I can press ALT+LeftArrow to return to the previous script but having the option would be better.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It gives the user more control over the editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A toggle option in the Editor Settings to ignore the scene script and keep the current script open.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Probably better to have a native solution

### Is there a reason why this should be core and not an add-on in the asset library?

Probably better to have a native solution

**Comment by AThousandShips** [comment]
There's already the setting: `text_editor/behavior/files/open_dominant_script_on_scene_change`

**Comment by KoBeWi** [comment]
As noted above, this option already exists. Closing.

**Comment by Mickeon** [comment]
This is not the first time I recall that an user has "accidentally" requested this feature to be turned off. It highlights how difficult it is to find this option, as well as... most users simply not liking it.

**Comment by IIGreed** [comment]
I always try to search for these things before posting but I never use the right search prompts. I went back and searched it in the editor using only the word "script" and found it no problem at me moment I was convinced it had something to do with tabs so that's what I searched.
