### ISSUE TITLE
Show native documentation in a popup (in Script Editor)

### ISSUE THREAD

**Issue by echebbi** [godotengine/godot-proposals#765]
**Describe the project you are working on:**
Mostly following tutorials to discover Godot.

**Describe the problem or limitation you are having in your project:**
I can't check the documentation of native classes/functions as I read code. The closest feature is _CTRL + click_ but:

- it opens the whole documentation in another tab, and having to systematically switch back is really inconvenient,
- it requires the mouse.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The ScriptEditor could show a popup displaying the documentation of the selected element. This popup could be shown:

- on hover, when the cursor stay above an element without moving for, say, more than one second,
- when a specific keyboard shortcut is hit.

This proposal is highly related to #408 but addresses a complementary use case.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Most IDE have such a feature, [GDScript for VS Code](https://marketplace.visualstudio.com/items?itemName=geequlim.godot-tools) does it as follows:

<div align="center">
<img src="https://user-images.githubusercontent.com/25926433/80584456-fb18b900-8a11-11ea-9818-32fc7b53040b.png" alt="popup documentation for GDScript in VS Code"/>
</div>

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This enhancement would definitely be often used:

- it has been requested in Godot's main repository: https://github.com/godotengine/godot/issues/27607
- the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=geequlim.godot-tools) supports it: https://github.com/godotengine/godot-proposals/issues/177#issuecomment-595926144

**Is there a reason why this should be core and not an add-on in the asset library?:**
I believe that it's a feature that would benefit to everyone and which should be embedded in Godot by default. That being said, since the VS Code extension already supports it I suppose that it may be possible to implement it as an add-on.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/765, as the author of that proposal is developing a working implementation.
