### ISSUE TITLE
Make Jolt core and default 3D physics engine

### ISSUE THREAD

**Issue by Griiimon** [godotengine/godot-proposals#7652]
### Describe the project you are working on

I just upgraded a project from Godot v3 to v4. It's a Basketball game and I was stunned how easy the upgrade process was and how much of the game was converted automatically to the new version.
I only had to make minor changes ( like 10-20 lines total ) in some scripts. 

### Describe the problem or limitation you are having in your project

But the physics weren't behaving correctly. Ball spin and bounce were way off or even not working at all.
I was sure there was something that changed with the Rigidbody implementation and I had to find settings that werent converted correctly. But then I switched to Godot Jolt and all the bugs were gone. It now behaved 1:1 like my previous Godot v3 game. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

( Similar to https://github.com/godotengine/godot-proposals/issues/7308 but takes it 2 steps further and hopefully gets the ball rolling )

This is the final drop in the bucket in my opinion why Godot Jolt should be made a core feature and even the default for 3D physics. It's even better AS the default option now than the current default option.
There have been tons of success stories recently where switching to Godot Jolt solved a lot of problems. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Is it as easy as copying the add-ons code into godots code base? Probably not, i dont know.

_Softbodies_ are still missing in Godot Jolt but have been added to Jolt, so that'll be a non-issue.

Correct me if I'm wrong, but that only leaves _WorldBoundaryShapes_ as missing feature. I dont think it warrants waiting until Godot 5 to make Jolt the default engine. Cant we just add a warning to the node? 
I know breaking compatibility should be avoided at any cost, but here I think the cost is too high. The benefits outweigh it by some margin.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I consider Godot Jolt no longer an add-on but an essential. If it were just for the performance or some additional features it would be fine as a stand-alone add-on, but it basically fixes Godot 4 physics! 
And it seems they won't be fixed otherwise anytime soon.

### Is there a reason why this should be core and not an add-on in the asset library?

All the above.

**Comment by YuriSizov** [comment]
Please continue the discussion in https://github.com/godotengine/godot-proposals/issues/7308. There is no need for a second proposal that makes it harder to follow the discussion and the consensus.
