### ISSUE TITLE
Real-time Reflection Probe Rendering split to multiple frames

### ISSUE THREAD

**Issue by SpaceJellyfishDev** [godotengine/godot-proposals#7655]
### Describe the project you are working on

A 3D space shooter

### Describe the problem or limitation you are having in your project

Real-time reflection probe rendering is expensive. 

It doesn't have the necessary time slicing options to give better performance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add Time Slicing Mode option that allows the reflection probe to render one face per frame, so that the render takes 8 or more frames to render. 

This will significantly improve the performance of Real-time reflection probe, so that more developers can use it. 

An example doc of Unity's probe with this feature:

https://docs.unity3d.com/ScriptReference/Rendering.ReflectionProbeTimeSlicingMode.html

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I can't

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Reflection probe is core

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/4739.
