### ISSUE TITLE
Enum and match statement like Rust lang have to write Robust code by eliminating null references

### ISSUE THREAD

**Issue by indierusty** [godotengine/godot-proposals#7671]
### Describe the project you are working on

I'm working on 3D plane racing and shooting game my second project and first in Godot.

### Describe the problem or limitation you are having in your project

Overhead I have when scripting using null values and Err reporting makes me under confident.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Enums and Match statement like Rust will help to write more robust and readable code.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add support of Enums and match statement in GDScript.
Option and Result enum should be built in and must use thing. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes it very possible to script anything with what we have in GDScript for now but this enhancement will make GDScript much powerful.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm a beginner programmer yet I see how Enums in rust is so much powerful. Add support for Enums and match statement in GDScript will enhance coding experience in Godot.

**Comment by TheColorRed** [comment]
Enums and Math already exist:

[Enums](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#enums):

```gdscript
enum Example {ONE, TWO}

func _ready():
  print(Example.ONE) # prints 0
```

[Dictionaries](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#dictionary):

```gdscript
var dict1 = {"one": 1, "two": 2}
var dict2 = {one = 1, two = 2}

func _ready():
  print(dict1['one'])
  print(dict2['two'])
```

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating with https://github.com/godotengine/godot-proposals/issues/737 (as this is a prerequisite for something like Rust's `Option`/`Result`).
