### ISSUE TITLE
Smartly create a new variable when Ctrl-dropping a resource in an empty script line

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7673]
### Describe the project you are working on

trying things in godot

### Describe the problem or limitation you are having in your project

In this clip, I drop first a node and then a resource while holding Ctrl.

[simplescreenrecorder-2023-09-15_15.21.48.webm](https://github.com/godotengine/godot-proposals/assets/71937306/f0e688dc-1b4f-4049-a9a7-83eda8eaf01a)

One of those cases create a variable for you, the other doesn't.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When holding Ctrl and dropping a resource from the filesystem on an **empty line** in a script, automatically create a variable in a similar way.

The type should be as narrow as possible (and should include user-defined resources).
If dropped on an non-empty line, the current behavior should apply.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

[simplescreenrecorder-2023-09-15_15.41.30.webm](https://github.com/godotengine/godot-proposals/assets/71937306/5d6c9e4d-5e59-4670-94a3-c0f08972adc8)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it allows saving a bit of typing and it's a consistency improvment

### Is there a reason why this should be core and not an add-on in the asset library?

small ux improvement

**Comment by JoNax97** [comment]
I'd like to tackle this one if that's ok 👍

**Comment by Calinou** [comment]
> I'd like to tackle this one if that's ok 👍

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by niklaswort** [comment]
Great idea! I think the scene should be saved as a constant in UPPER_CASE, though.

**Comment by JoNax97** [comment]
Now that I think about it, why would always assume that the correct action is to preload into a constant?

Isn't loading into a variable an equally valid option?
At any rate, it makes less assumptions about user intent.

**Comment by nubels** [comment]
> Now that I think about it, why would always assume that the correct action is to preload into a constant?
> 
> Isn't loading into a variable an equally valid option? At any rate, it makes less assumptions about user intent.

I think loaded scenes are a good examples for immutability but maybe I'm wrong. Could you please give me an example where it would make sense to change the value of a variable that was initialized with a preload?
