### ISSUE TITLE
Add the ability to change the color/icon of folders in the FileSystem view

### ISSUE THREAD

**Issue by the-sink** [godotengine/godot-proposals#768]
**Describe the project you are working on:**
Underground 3D facility with an interactive environment

**Describe the problem or limitation you are having in your project:**
Due to the nature of my project, I have lots of project files and this will inherently start to pile up with folders. Better folder organization is a good way to clean up your filestructure but is only a part of the solution.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There should be an option to change the icon or base color of any folder in the FileSystem view that would reflect in both the normal and split modes. You would right click and be presented with "Change folder icon"/"Change folder color" options (or something similar) that would allow you to customize the folder icon/color, and this would save.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![mockup](https://i.imgur.com/5PDycIE.png)
^ Only demonstrates colors

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not that I am aware of, short of completely replacing the FileSystem view with a custom one using a plugin.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is a relatively simple feature that would require an unnecessarily complex means to add yourself (see above question).

This is already a feature in Unreal Engine (at least the color part) and is a very nice tool to help organize and define which folders are more/less important when navigating the filesystem, and I think it would be a great QOL feature for developers.

**Comment by Calinou** [comment]
Should this information be stored in editor metadata (= not in version control) or in `project.godot` so it can be checked into version control?

**Comment by TheSink** [comment]
Fair point on the custom icons. A predefined color palette/presets would be more than enough to solve the bulk of the issue.

I'd definitely vouch for it being checked into version control so that when, let's say, another team member pulls a project or someone online downloads a demo project, the project itself can also reflect these folder colors. Would be better for continuity I think.

**Comment by dalexeev** [comment]
> Should this information be stored in project metadata (= not in version control) or in `project.godot` so it can be checked into version control?

KDE has `.directory` file that is used for similar purposes. Also `.gdignore` is already used to ignore directories.

Perhaps we should use `.gddir` or something similar. In this case, everyone can configure whether or not to include this file in version control.

**Comment by mhilbrunner** [comment]
>This is already a feature in Unreal Engine

It's also a fairly popular extension in Unity-land. (Mostly adding this for completion, as it may help gauge interest.)

**Comment by stilobique** [comment]
We have quickly lot folders, it's more easily to find a folder with a specific colour. When your work on a specific pole (Programmer, Graphites... you can give a colour system to your team.

**Comment by Norrox** [comment]
![Skärmbild 2022-07-14 100352](https://user-images.githubusercontent.com/13393087/178934582-e46faf60-9d3e-4093-846f-0022729aa068.png)
![Skärmbild 2022-07-14 100448](https://user-images.githubusercontent.com/13393087/178934592-24a34cc4-660f-4f0e-9b87-17fc062ebb28.png)
Some more refrence pictures.
Is this hard to do ? Are someone interesting in helping me navigating the source and make this change? is it a good beginning practice for a beginner ? :D

**Comment by the-sink** [comment]
I was also interested in working on this, although I'm personally still learning the ropes on Godot's source code. If you're interested, I'll (hopefully) be working on this at [the-sink/custom-folder-colors](https://github.com/the-sink/custom-folder-colors) after I've had some time to look around.

Question in regards to how folder colors are stored. I personally think adding them to the `project.godot` or (as @dalexeev suggested) adding a `.gddir` file are good ways to go about this, but what about when directories are externally manipulated? If someone deletes a folder outside of Godot, renames it, moves it, etc. All of that could present issues.

I like the `.gddir` idea as we could create this file inside of each directory that is customized. Granted, that method may cause some clutter in users' project directories if they decide to change the color of _all_ the folders in their project, but assuming the use case for this will almost always be coloring the root folders, it shouldn't be that bad in the vast majority of situations where it's utilized. It'd also mean the ability to choose yourself whether or not to include them in version control (as previously mentioned), and no need to constantly re-check all of the folders to make sure they weren't externally modified.

**Comment by Calinou** [comment]
> Question in regards to how folder colors are stored. I personally think adding them to the project.godot or (as @dalexeev suggested) adding a .gddir file are good ways to go about this, but what about when directories are externally manipulated? If someone deletes a folder outside of Godot, renames it, moves it, etc. All of that could present issues.

I don't think we can effectively track renames – it's like favorites in the FileSystem dock.

As for folder deletions, we can ignore them but keep the entries in `project.godot` in case the folder is externally added again.

**Comment by stilobique** [comment]
> [...]
> I wouldn't add a dedicated .gddir file, especially since I think folder colors should always be tracked in version control. You want those to be consistent across users when working in a team after all.

Good point about your feedback ; that important -I think- to have a main solution (for a studio project), and for a specific user.

**Comment by dalexeev** [comment]
There is also an option to add these settings to the `.godot/editor/dir_params` file (or similar). If you want, you can add it to the `.gitignore` exceptions, while with `project.godot` you have no choice.

In defense of the `.gddir` (or `.gd_directory`) file, this approach works well with moving, renaming, and restoring a directory, even with external programs (because `.gddir` only affects the folder it's directly in). Deleting the directory and creating a new one with the same name does not save the params, but on the other hand it sounds logical.

> -I think- to have a main solution (for a studio project), and for a specific user.

The ability to locally override directory params seems interesting, but I'm not sure we need such a detailed configuration. I think it will be enough just to choose whether or not to track the params in the VCS.

**Comment by the-sink** [comment]
I agree with @dalexeev in that it removes the need to track renaming/moving directories in-editor and removes any sort of problems created as a result of modifying folders outside of the editor. Buuuut...

I wonder, if it _were_ to be put in `project.godot`, what would be the best way to store this information? It's going to show up in the Project Settings window (unless there's a way to hide options from the editor gui). A dictionary would be nice, keys being the folder paths and values being the color the user set it to, but I wasn't sure what the value type should be. If we want a specified color palette, using the Color type wouldn't be a good idea as users could just change them to any color at random...

**Comment by Calinou** [comment]
> It's going to show up in the Project Settings window (unless there's a way to hide options from the editor gui).

We already have special checks to handle this with `class_name` declarations and input map actions, both of which are stored in `project.godot`.

**Comment by Norrox** [comment]
@the-sink any updates on this, i see your repository is gone? :)

**Comment by the-sink** [comment]
Sorry for the lack of a follow-up, I ended up not having enough time to try and implement it myself at the time. I can take another shot at it once I have more time in a few days, but if anyone else wants to try and implement this themselves please feel free to do so!

**Comment by the-sink** [comment]
Okay I _think_ I actually have some time to work on this now... It's definitely a learning experience for me since I'm not all too familiar with the codebase, but I'll try my best and of course if any of the more experienced contributors have critiques, feel free to mention them!

Currently at [the-sink/godot (folder-colors branch)](https://github.com/the-sink/godot/tree/folder-colors). I think it's a reasonable implementation to just have a sub-menu for all of the pre-defined folder color options. For instance:

![image](https://user-images.githubusercontent.com/18225391/208354918-ce3e5ddc-8cb6-44d7-93d5-0c6ccd6b4897.png)



This requires another, partially unrelated change that I'll submit a PR for in a bit that copies the ``get_item_icon_modulate``/``set_item_icon_modulate`` functions from the ``ItemList`` class over to ``PopupMenu``, so that I can use the same editor folder icon for the dropdown menu. Might be useful in other areas of the editor/for users' projects as well?

**Comment by DennisGHUA** [comment]
![gm2-comparison](https://github.com/godotengine/godot-proposals/assets/31701470/88ac1b70-25a2-49e3-9e66-203e71bd8da5)
I'd like to highlight a compelling feature from Gamemaker's asset browser that sets it apart from Godot's current implementation. Gamemaker not only uses distinct colors for folder icons but takes it a step further by matching the background color with that of the folder itself, slightly darkening it. To enhance visibility, opened folders in Gamemaker's asset browser receive an even darker shade, creating a clear visual distinction.

I think integrating this approach into Godot's asset browser would significantly improve user experience and navigation. The incorporation of folder background colors aligned with their icon color would make it easier to identify different folders and their states, allowing users to intuitively locate assets more efficiently.

As a side note, it's worth mentioning that Godot's asset view currently lacks a clear differentiation between opened and closed folders, which is a separate matter but may also benefit from attention and improvement in the future.

**Comment by Norrox** [comment]
i see #70286 got merged, does it mean you @the-sink can make this work?

**Comment by the-sink** [comment]
@Norrox Good reminder haha, started working on this again and got it to (I think?) a functional state:

https://github.com/godotengine/godot-proposals/assets/18225391/08090acf-2c08-4e62-b6d9-6fabff64af44

![image](https://github.com/godotengine/godot-proposals/assets/18225391/35d88e43-f392-40e7-b8bd-40b0a9b6df0b)


Stores folder colors in `project.godot` as was discussed. I'd be interested in trying what @DennisGHUA is suggesting, although I'm not too sure if Trees support that kind of background color adjustment? Might need to be a separate feature request.

**Comment by DennisGHUA** [comment]
@the-sink Impressive progress! I'd like to highlight a particular aspect in my example: when considering subfolders lacking an assigned color, they currently inherit the folder color from the one immediately above them. To enhance this, I propose that setting the default color of a subfolder to match that of its parent folder would be a more intuitive approach, moving away from the fixed blue color for all subfolders.

**Comment by the-sink** [comment]
@DennisGHUA Thanks! It definitely does look better when folder colors are inherited as the background color is:

![image](https://github.com/godotengine/godot-proposals/assets/18225391/b7747ff3-861c-4aa9-ac57-4fa009ef5cca)

Just created a draft PR!

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/80440.

**Comment by michaldev** [comment]
_The message is not for the author of the PR._

With all due respect to the people who put a lot of work into it. Despite everything, I see how much is changing in the engine and how much work the people involved in the project put into it.

A lot of time has passed since the release of Godot 4. There is no noticeable improvement in engine stability. **Many totally critical errors are ignored** (like my https://github.com/godotengine/godot/issues/79697, any many, many others from community. Web still doesn't work on iOS, with correctly cors too). 

Meanwhile (4.1, 4.2) features like this are being added that will cost developers time to maintain the code in the future.
Do not get me wrong. Improvements are also important, but I think you know what I mean when I talk about priorities.

I'm just a Godot user. I don't contribute much to the community other than donations. This isn't due to my laziness, but because I simply don't want to learn C++ and the skills needed to develop the engine.

After the recent **Unity scandal,** many people ask me about Godot, knowing that I am creating a game that they like.

I have a problem with the answer because Godot is free, but at the same time it requires a lot from the user.

After thinking for a while, I answer:
- Writing basic services (like login with Google/Apple, oauth2 and much more)
- Learning C++ and knowledge of the structure of the Godot engine
- Fixing engine errors

I ask them to calculate the number of hours and their own hourly rate. 
Then it turns out that **Unity is not that expensive at all**.
