### ISSUE TITLE
Quicker way to create a timer via code

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-proposals#7688]
### Describe the project you are working on

Tug-O-War style game

### Describe the problem or limitation you are having in your project

Creating a Timer via code currently takes takes too many lines for something that could be done using one line.

```gdscript
var timer = Timer.new()
timer.wait_time = 1.0
timer.autostart = true
timer.one_shot = true
add_child(timer)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

An easy way to create a timer without a Node. The Tween node was removed from 3.x in favor of `create_tween()`, I feel like the timer could have a similar function that could either:

* Run without a node (similar to Tween)
* Create a node in the scope in which it was called
    * `get_tree().create_timer(1.0)` &ndash; as a child of the root
    * `create_timer(1.0)` &ndash; as a child of the current node
    * `node_ref.create_timer(1.0)` &ndash; as a child to the referenced node

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# create_timer(wait_time: float, autostart: bool = false, one_shot: bool = false)
var timer = create_timer(5.0)
timer.start() # if autostart is false
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The workaround is same as above (a little cumbersome):

```gdscript
var timer = Timer.new()
timer.wait_time = 1.0
timer.autostart = true
timer.one_shot = true
add_child(timer)
```

### Is there a reason why this should be core and not an add-on in the asset library?

This affects the GDScript API code

**Comment by Calinou** [comment]
This already exists as `get_tree().create_timer()` (SceneTreeTimer) 🙂

**Comment by TheColorRed** [comment]
So, since that is a `one-shot` timer, would you have to do something like this to make it repeat, or or is there a way for `non-one-shot` timers?

```gdscript
func _ready() -> void:
	await get_tree().create_timer(1.0).timeout
	_done()


func _done():
	print("done")
	await get_tree().create_timer(1.0).timeout
	_done()
```

**Comment by Calinou** [comment]
> So, since that is a one-shot timer, would you have to do something like this to make it repeat, or or is there a way for non-one-shot timers?

If you want it to repeat, you'll have to recreate it every time it times out, or create a Node.

For your use case, it may be worth creating an autoload with a `create_timer()` method that works exactly as you want.
