### ISSUE TITLE
Impossible math operations should leave some kind of output

### ISSUE THREAD

**Issue by UhGoomba** [godotengine/godot-proposals#7694]
### Describe the project you are working on

3D stealth game, I have used division and the sqrt function for player movement

### Describe the problem or limitation you are having in your project

Godot just freezes the game when you do impossible math operations like dividing by zero or taking the square root of a negative number.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Those functions should have some kind of check or have some way to output why the game is freezing.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There will be some kind of output that informs the user of their issue. I don't know the inner working of the engine, but this should be communicated to the user in some way. I have spent a lot of time debugging both of those two issues. I know now that this issue is likely caused by a math operation, but most people will not.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/a

**Comment by Calinou** [comment]
This is a bug: https://github.com/godotengine/godot/issues/67317
