### ISSUE TITLE
Environment variables passed to the editor should be passed to the player

### ISSUE THREAD

**Issue by warent** [godotengine/godot-proposals#7695]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

There is no way of passing cmdline user args into the game/player thru the editor.

**NOTE** This is different from "Project Settings -> Editor -> Run -> Main Run Args"

The point is that these variables are supposed to be instance-specific, not project-wide

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The editor should pass args into the player so that scripts can read them via `OS.get_cmdline_user_args` while doing development.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Shortcut Target: "\path\to\godot.exe" -- --my-user-arg

![Screenshot 2023-09-16 153352](https://github.com/godotengine/godot-proposals/assets/13342266/3a072834-a3c4-420a-85ab-79460e982901)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not easily. Probably need to manually move files around and have Godot read them.

### Is there a reason why this should be core and not an add-on in the asset library?

`OS.get_cmdline_user_args`  is part of the core library (and IMO what is proposed here should be the expected behavior)

**Comment by Calinou** [comment]
Are you confusing between *environment variables* and [command-line arguments](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html)? These are different things, and the operating system handles them differently.

We shouldn't pass every CLI argument that was passed to the editor to the running project, as it can have unintended consequences (for instance, if you disable audio output for the editor using `--audio-driver Dummy`).

It sounds like you're looking for something like https://github.com/godotengine/godot-proposals/issues/522 instead :slightly_smiling_face:

**Comment by warent** [comment]
Ah apologies haha you're correct I mixed up my terms. Closing as a dupe of #522, thank you!
