### ISSUE TITLE
Let set children's transfrom properties for ContainerControl

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#7699]
### Describe the project you are working on

NoGame App

### Describe the problem or limitation you are having in your project

In UE, it can set control's transfrom properties for Container, like below GridContainer, I can easy make animation like this:
![GIF 2023-9-17 14-24-55](https://github.com/godotengine/godot-proposals/assets/35988767/3bab282a-7220-4fe7-9c3c-4f1903735308)
But in godot, I can't set control's properties in container, so make this was difficulty.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

/

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

/

### Is there a reason why this should be core and not an add-on in the asset library?

/

**Comment by mk56-spn** [comment]
Another convenient case for allowing transforms within containers is offsetting control nodes to create a diagonal menu of sorts. you can technically circumvent this by nesting another node within the one inside the container but that feels entirely redundant

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/413.
