### ISSUE TITLE
Add an real 3D and 2D Map editor in Godot without the need of any plugin,scripting or addon.

### ISSUE THREAD

**Issue by Serasul1984** [godotengine/godot-proposals#7711]
### Describe the project you are working on

Many Users who make 3D Games with GoDot will use this here to make the map (when they find this) https://www.youtube.com/watch?v=BUjCtwLO0S8  the problem is its lack of any feature we all know out of other Editors.

### Describe the problem or limitation you are having in your project

Problems:
For an fast workflow to make an 3d map you need an 4 camera view at the same time like the Source engine Editor has.You see what you make with an transparent 3d model from top,side and front view and in the forth window you see how its look with textures and light.
There is also an lack of preforms you can use to make quick some complex 3D elements like round-stairs,hypercube or even an Star or even an pyramid.
That we need to make our own 3d Map editor or 2d Map Tileset editor in godot itself first before wen make some maps is just very time and cost consuming.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Pls let us make 2d Maps with the same features "Tilesetter" has https://www.youtube.com/watch?v=trHr6piFLKw
And when it comes to 3D Mapping it would be nice to hafe the same Features as the Hammer++ Editor https://developer.valvesoftware.com/wiki/Hammer%2B%2B

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The user just select the Editor for 2d or 3d elements and it just works.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it will be used every time,because everyone makes an game that uses maps,tilemaps,open world 3d maps,racetrack maps,sidescroller maps and so on. Right now we just use an bunch of pieces to build the endproduct, we dont really have an 3d or 2d editor to make an Map.

### Is there a reason why this should be core and not an add-on in the asset library?

The main reason we dont want to use so many addons/plugins for making maps or even outside Program's is very easy.
It makes Game Development riskier and you get more bugs or even limitations because of this.
For example Tilesetters Dev hasn shown up the last year,this means all bugs and fetueres that are in or not are limitations for the users of his editor. We have enough Limits in Godot already we dont need some more outside of it.
I used the Hammer++ Editor for example because its clean and easy to use.
The Map-editor is always an Core part of every AAA Engine out there.
Pls give us an real 2d or 3d map editor, not an sandbox of it we need to build ourself only to build the real things we want to build only to make and game after all of this ......

**Comment by Zireael07** [comment]
1) This is several features requests disguised as one
2) For viewports, you can open four viewports at once already
3) Lack of 3d mesh prefabs is indeed a fact but there's at least one asset that adds them
4) 2D tileset editor in Godot 4 can do a lot of things. Please elaborate what you think is missing compared to this mythical "Tilesetter". (3D gridmaps having similar editor is a separate feature request already tracked)
5) What does Hammer Editor do that the current editor, plus CSG, can't do?

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2879.
