### ISSUE TITLE
Getting global key input

### ISSUE THREAD

**Issue by MudkipWorld** [godotengine/godot-proposals#7713]
### Describe the project you are working on

Working on a PNGTuber/ Vtuber app along with a desktop pet/ mascot app.

### Describe the problem or limitation you are having in your project

Unable to get the global key capture through GDScript. I can only find getting the position of the mouse, but nothing related to pressed keys. Which means I am unable to get my software working while unfocused in any way; in the background, minimized, mouse pressed somewhere else,....

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a get_global_key_input() for example. It will be detecting a specific key.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example :
if get_global_key_input("ui_left").pressed:
         # Do something here

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Sadly I have done a ton of searching and going on different sites and resources, this feature can't be done normally as far as I am aware. At least not with GDScript from what I know.

### Is there a reason why this should be core and not an add-on in the asset library?

I have seen this feature asked about so many times and I person would use it alot. I have seen different software with godot popping around where they mentioned not being able to achieve this due to it not being that possible or hard to find work around.

Not sure if I am allowed to link examples (since they aren't mine), but if needed, tell me!

**Comment by AThousandShips** [comment]
I'm unsure how possible this is, might be complicated to get keys when app is not focused

**Comment by MudkipWorld** [comment]
> I'm unsure how possible this is, might be complicated to get keys when app is not focused

I have seen apps made with Unity (away from the whole recent mess) back then that did have this functionality. Complicated? I agree, it might not be the easiest thing to add. Impossible? I don't think so personally, since as stated, other engines were able to do it and heads up, the "get_global_mouse_posistion()" does work when the window isn't focused.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1919.

> I'm unsure how possible this is, might be complicated to get keys when app is not focused

This is definitely feasible on a technical level, but only on desktop platforms. Linux + Wayland setups may also have trouble with this, as Wayland doesn't allow global shortcuts as part of its security model (at least by default).

**Comment by MudkipWorld** [comment]
> Thanks for the proposal! Consolidating in #1919.
> 
> > I'm unsure how possible this is, might be complicated to get keys when app is not focused
> 
> This is definitely feasible on a technical level, but only on desktop platforms. Linux + Wayland setups may also have trouble with this, as Wayland doesn't allow global shortcuts as part of its security model (at least by default).

Gotcha!, from my understanding from the linked issue, I would need to use C# in this case, correct?

**Comment by Calinou** [comment]
> Gotcha!, from my understanding from the linked issue, I would need to use C# in this case, correct?

Currently, you'd need to use C# interoperability with a native library or GDExtension to achieve this indeed.

**Comment by thiagola92** [comment]
> Currently, you'd need to use C# interoperability with a native library or GDExtension to achieve this indeed.

Sorry for asking here, but through GDExtension can we access any part of Godot code? For example, code from platform specific like:
https://github.com/godotengine/godot/blob/master/platform/windows/key_mapping_windows.cpp

I was also working on a PNGTuber.

**Comment by Calinou** [comment]
> Sorry for asking here, but through GDExtension can we access any part of Godot code? For example, code from platform specific like:
[godotengine/godot@master/platform/windows/key_mapping_windows.cpp](https://github.com/godotengine/godot/blob/master/platform/windows/key_mapping_windows.cpp?rgh-link-date=2025-02-22T04%3A08%3A29.000Z)

GDExtension can only reference what's exposed to the scripting API, so this can't be done with GDExtension alone. You'd need to fork the engine and compile custom builds instead.
