### ISSUE TITLE
Pass File Path to EditorScenePostImport's

### ISSUE THREAD

**Issue by Moe-Baker** [godotengine/godot-proposals#7718]
### Describe the project you are working on

I'm trying to make a script to automatically make an animation resource out of Mixamo FBX files using the EditorScenePostImport.
My custom EditorScenePostImport script is supposed to be used as an import script for Mixamo animation FBX files, where it will create an animation resource alongside the FBX file.

### Describe the problem or limitation you are having in your project

EditorScenePostImport's `_PostImport(Node scene)` method doesn't receive a path parameter and as such I can't save the resource next to the FBX from where it originates.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Pass in a path parameter to `_PostImport(Node scene)` that will point to the asset from which the scene originated.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

make
`public override GodotObject _PostImport(Node scene)`
into
`public override GodotObject _PostImport(Node scene, string filePath)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can technically be worked around by just saving all the animation resources to a single unified directory.
Or by making a custom import script for each directory needed.
All solutions that aren't really super great.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a simple minor change that will improve the functionality offered by EditorScenePostImport for everyone.

**Comment by squk** [comment]
`EditorScenePostImport` class has a `get_source_file()` method.

**Comment by Moe-Baker** [comment]
Thank you, can't believe I haven't noticed it in the documentation
