### ISSUE TITLE
A way to SOLO a node tree in the Scene editor.

### ISSUE THREAD

**Issue by ryaninlife** [godotengine/godot-proposals#772]
**Describe the project you are working on:**
Various 'object factories' that let you request a monster (or bullet, or whatever) from a single dedicated monster, bullet, etc node, it returns a subnode that contains the monster instances so you can spawn them elsewhere in your code.     Keeps code super clean and efficient.

<img width="765" alt="Screen Shot 2020-04-30 at 12 31 45 PM" src="https://user-images.githubusercontent.com/63005445/80735420-a727d600-8ade-11ea-9c6b-e805121f5c21.png">

**Describe the problem or limitation you are having in your project:**
The list of enemies, monsters, bullets, or other things I'm using this technique for becomes large and the objects all display on top of each other.  The only way to view one alone is to turn off all the others, which you then have to turn back on before running the game.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Being able to SOLO a nodetree would let us just focus on that tree without having to change the settings on all the others.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Open Eye that turns into Closed Eye would also turn into a 3rd state, perhaps a Monocle that would solo it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It would be used a lot, which is why it's a typical feature in apps like Illustrator, Photoshop, and many many others.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I imagine because its very core to the basic functionality.

**Comment by Jummit** [comment]
I'd just save every object as it's own scene instead of polluting one scene with all of them.

**Comment by KoBeWi** [comment]
Or you could keep them all hidden and only show the one you need to edit right now.

**Comment by ryaninlife** [comment]
Good points.  I realized also that I can just reposition them relative to the containing node and they don't overlap.

**Comment by mhilbrunner** [comment]
As noted by yourself and others, this seems to be more of a workflow/how you use it issue, with existing solutions. :)

I'll close this proposal for now, if you still encounter any UX issues with scenes/node handling, feel free to let us know!
