### ISSUE TITLE
Unity style freeform editor UI

### ISSUE THREAD

**Issue by Rain-Gayming** [godotengine/godot-proposals#7732]
### Describe the project you are working on

Currently working on a simple RPG

### Describe the problem or limitation you are having in your project

The editor UI could be improved

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The ability to move the UI like you can in unity (EG having the file system on the bottom)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Move the things that usually go on the bottom (Tileset/map, Debug, monitoring ect) to tabs like the file system, node, scene and inspector and allow for the freeform movement of them to how users want

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Its editor so it can be avoided

### Is there a reason why this should be core and not an add-on in the asset library?

I think it'd help those moving from unity and just generally other developers

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1508.
