### ISSUE TITLE
Provide MIDI device property in InputEventMIDI class

### ISSUE THREAD

**Issue by mcptron** [godotengine/godot-proposals#7733]
### Describe the project you are working on

I am working on a digital art project where I am using Godot as visualization engine which is influenced by audio analysis and incoming MIDI events.

### Describe the problem or limitation you are having in your project

Some external MIDI Hardware devices cannot change their MIDI channel and cannot be distinguished from each other without device information for each incoming MIDI event.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A string attribute "input" or "device" containing the device name as listed by OS.get_connected_midi_inputs() or an int attribute pointing to the corresponding array element of OS.get_connected_midi_inputs() would solve the problem.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

if input_event is InputEventMIDI and input_event.device == "my_awesome_midi_controller":
    do_something_useful()

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I haven't found any workaroung except integrating an external MIDI library like portmidi or rtmidi as GDExtension

### Is there a reason why this should be core and not an add-on in the asset library?

All necessary information should already be available and exposing the device name should be quiet simple (i would guess).

**Comment by ramdor** [comment]
yes, this would be a welcome addition. Currently `OS.GetConnectedMidiInputs()` which returns a string array of devices, however there is no property in the InputEventMidi event such as DeviceIndex which could be used to obtain the string out of that device array.

**Comment by PeterMarques** [comment]
Not fixed. At least it seens on my tests. Or i an using it wrong?

No matter the device used to input midi, it aways return 0.

'''
extends Node

func _ready():
 OS.open_midi_inputs()
 print(OS.get_connected_midi_inputs())

func _input(input_event):
 if input_event is InputEventMIDI:
  _print_midi_info(input_event)

func _print_midi_info(midi_event: InputEventMIDI):
 if "Note On" in str(midi_event):
  print(midi_event)
  print(midi_event.device)
'''

I am using the 4.3 dev release.
