### ISSUE TITLE
Color VisualShader nodes by category

### ISSUE THREAD

**Issue by Geometror** [godotengine/godot-proposals#7745]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

When editing a complex VisualShader with lots of nodes it can be difficult to maintain an overview/quickly parse the graph, especially at high zoom levels.
For comparison, this is a current screenshot of the editor: A bit monotonous, isn't it? :)
![grafik](https://github.com/godotengine/godot-proposals/assets/50084500/84210fa4-a6dd-4b27-82ef-9aecb1c1437b)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Coloring the title bar of VisualShader nodes according to the category they belong to makes it a lot easier to read the graph and orient oneself.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, I'm going to show Blender as an example again:
![grafik](https://github.com/godotengine/godot-proposals/assets/50084500/ae04d2ea-b6e5-466e-961f-03c8b4e5fc7b)

With color-coded nodes you can immediately see in which section e.g. your vector operations are located.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This needs to be deeply integrated into the VisualShader editor and is therefore core.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/85017.
