### ISSUE TITLE
Add an "OR" blend mode to CanvasItemMaterial

### ISSUE THREAD

**Issue by LordBrkica** [godotengine/godot-proposals#775]
**Describe the project you are working on:**
I am working on a strategy game. 
**Describe the problem or limitation you are having in your project:**
I am having trouble building a _field od view/ fog of war / visibility system_.

Lets say we have 2 friendly units in some strategy game. We want to show the player how far these units can see. I used a whitish semi transparent Sprite to show this:
![image](https://user-images.githubusercontent.com/51578785/80786750-d7c24b00-8b84-11ea-9e7e-6e6995b49223.png)
So the white area is the area which they see.

The thing is - I cannot properly graphically show this area. The closest I could get is shown in the image above, but a problem exists - no appropriate _CanvasItemMaterial_  _Blend_ property exist to mix these two vision fields. There is always some ugly overlap between them (marked blue in the image) and I dont to change this color. 
If you can imagine rts games , their visibility is always the same semitransparent color and it doesnt blend in unusual ways.

Other people would like to use this ability but for different purposes, example:
https://www.reddit.com/r/godot/comments/cgqo95/any_way_to_mix_two_sprite_textures_together/?utm_source=share&utm_medium=web2x

Intuitively I would say what is missing is some sort of an **OR** Blend, where when we have several overlapping items we blend using only one.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Early strategy games such ase Age of Empires and Starcraft introduced a concept of fog of war.
Units see other units only when they are in their respective field of vision area. Its technically possible to use Area2D to hide/show entering bodies (although this also isnt exactly ideal), but there is little possibility to actually show some sort of a visibility area.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I think easiest thing would be a some sort of a **OR** Blend implementation. 
I dont know much about shaders, if this is hard to implement than I am out of luck. But maybe its not and it would help not just me but some other people as well.
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Well I think stuff like this is often used in strategy games, I do not see an easy solution (and havent manage to find one on the internet),
**Is there a reason why this should be core and not an add-on in the asset library?:**
Every strategy game since Age of Empires has fog of war/visibility as a core mechanic, I think Godot has a chance to be used in such games and this feature would be very helpful.

**Comment by Calinou** [comment]
This can be achieved with opaque textures rendering to a ViewportTexture that would be transparent.

**Comment by PoirotovBrk** [comment]
> This can be achieved with opaque textures rendering to a ViewportTexture that would be displayed as transparent. There are many fog of war examples out there already.

Some links to these examples would be nice.

**Comment by Calinou** [comment]
@PoirotovBrk https://github.com/AntonWedemeier/Godot-FogOfWar

**Comment by PoirotovBrk** [comment]
> @PoirotovBrk https://github.com/AntonWedemeier/Godot-FogOfWar

Thanx, I will try to implement this approach to my game.

**Comment by clayjohn** [comment]
This is now possible in 4.0 with the new CanvasGroup node. You can read more about it here in the announcement post https://godotengine.org/article/godots-2d-engine-gets-several-improvements-upcoming-40
