### ISSUE TITLE
Add a string quote operator that doesn't process escape characters (e.g. for regex use)

### ISSUE THREAD

**Issue by HenryLoenwind** [godotengine/godot-proposals#7752]
### Describe the project you are working on

I'm currently writing code to parse my level data files using regexes.

### Describe the problem or limitation you are having in your project

The current syntax relies on supplying regexes as normal strings, and just like in way too many programming languages, this creates a conflict between regex and string escape syntax. The\/result\/is\/very\/much\/unreadable\/ascii\/art.

However, instead of promoting regexes to be a first-class language feature (although I'd be all for that), I propose to implement a more generic feature that can be of use in other contexts, too.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a string quote operator that doesn't do any kind of processing on the string aside from stopping at the end delimiter.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For example (borrowing from Perl):

```
var fancy = q[\\\\\o/////]
```

However, Perl's quote operators currently are (mostly) valid code in gdscript, so another syntax needs to be found. One option would be to use "/" as the delimiter (there's no prefix-/) but people might expect that to auto-instantiate a regex, another one would be to use ` or ´ (although those are hard to read). "<<...>>" might be an option (the existing use for those is infix, too).

Another way to handle syntax extensions like this without going full extended ASCII would be to add pseudo functions to the parser, e.g.:

```
var fancy = @quote(\\\\\o/////)
var also_fancy = @quote<\\\\\o/////>
```

For the original use case, pseudo functions would need to support variant delimiters. (), [], <>, {}, and // should cover all cases, I think. No need to go full "every character is possible" like Perl does.

A variant of that would be "@quote<space>"..."\n", e.g.:

```
var fancy = @quote \\\\\o/////
# or
var fancy = @quote: \\\\\o/////
```

This feels slightly less shoehorned in.

Note: As this would be purely a parser feature, there would be no runtime performance impact.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

n/a Parser feature

### Is there a reason why this should be core and not an add-on in the asset library?

n/a Parser feature

**Comment by Calinou** [comment]
Thanks for the proposal! Consoldiating in https://github.com/godotengine/godot-proposals/issues/5362.
