### ISSUE TITLE
Use a more donut-y icon for `TorusMesh` and `CSGTorus3D`

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7759]
### Describe the project you are working on

prototypes

### Describe the problem or limitation you are having in your project

![image](https://github.com/godotengine/godot-proposals/assets/71937306/272ff3e2-a477-4244-aee2-1d61326901b0)
![image](https://github.com/godotengine/godot-proposals/assets/71937306/edb618fd-aeb5-43d5-a3eb-12f4160777c8)

I find these icons too flat. Not toruses. More like discs.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use a better icon

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Blender does it that way:
![Screenshot from 2023-09-20 10-10-27](https://github.com/godotengine/godot-proposals/assets/71937306/ebe327a3-7711-40c7-962c-616f234d6045)

that's better I think!

### If this enhancement will not be used often, can it be worked around with a few lines of script?

can't be worked around with a few lines of script

### Is there a reason why this should be core and not an add-on in the asset library?

core already

**Comment by Mickeon** [comment]
@MewPurPur icon guy where are you at?

**Comment by MewPurPur** [comment]
I've wanted to do this for a long time.
