### ISSUE TITLE
Add an `albedo boost` option to lightmap to tweak it for artistic porpuses.

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot-proposals#7765]
### Describe the project you are working on

3D lighting

### Describe the problem or limitation you are having in your project

Currently, the lightmap result is base purely on the surface on which the light bounces, and the direct and indirect light energy. Further tweaking of the lightmap result cannot be done yet

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an albedo boost option to the lightmap which will tweak the result of the color after each bounce of the surface.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The albedo boost is the intensity of surface albedo throughout the lightmap when considered in lighting calculations. This value influences the energy of light at each bounce.

When light bounces off a surface, it is multiplied by the albedo of the surface. Change this value to increase or decrease the intensity of albedo used.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Can be work around with external software

### Is there a reason why this should be core and not an add-on in the asset library?

Lightmap is core

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/49968, as this is a missing feature that was present in 3.x.
