### ISSUE TITLE
Allow navigating the inspector history with mouse next/back buttons

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7797]
### Describe the project you are working on

stuff

### Describe the problem or limitation you are having in your project

Right now to navigate the editor history you have to use the tiny arrows:
![image](https://github.com/godotengine/godot-proposals/assets/71937306/7fcc8812-9921-49c2-85d0-eb6529c13ca5)

it's inconvenient. and they don't feel good

and right now, from time to time, the editor will display a resource I don't care about on certain actions (https://github.com/godotengine/godot/issues/81323, https://github.com/godotengine/godot/issues/82111). A fast way to navigate back would be a nice temp fix.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

when using the "next" or "previous" buttons on mice that have them, navigate in that history. (if the inspector has the focus, that is)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
if next pressed:
   navigate to next item
if prev pressed:
   navigate to prev item
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

used kinda often

### Is there a reason why this should be core and not an add-on in the asset library?

it's about making an editor feature less painful to use

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/954.
