### ISSUE TITLE
put the `streams` section after the first options in `AudioStreamRandomizer`

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7799]
### Describe the project you are working on

stuff

### Describe the problem or limitation you are having in your project

![image](https://github.com/godotengine/godot-proposals/assets/71937306/8c835de6-19d0-4663-87f3-800cd4450a86)

"where do I put my streams...? [...] oh, it's here"

this `streams` section is a bit hidden. I can't think of an occurence of a section leaving content that's below it visible when folded...
I always look for it, each time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

move the `streams` section down, below the non-categorized options.
I think it's because it's an array field, which makes it have this folding property automatically, but in this case it's not beneficial I think.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/71937306/f8a3c955-0b2a-42d1-ab59-7b957b8e4a01)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

used all the time

### Is there a reason why this should be core and not an add-on in the asset library?

core ux

**Comment by Calinou** [comment]
We generally try to keep non-foldable properties first in the list, as it looks a bit strange when you have non-foldable properties below a foldable section.

**Comment by mieldepoche** [comment]
> We generally try to keep non-foldable properties first in the list, as it looks a bit strange when you have non-foldable properties below a foldable section.

yep, that's what this proposal is about. (not sure if you mean something else)
