### ISSUE TITLE
Give TODO comments different formatting in script editor

### ISSUE THREAD

**Issue by JUSTCAMH** [godotengine/godot-proposals#7810]
### Describe the project you are working on

A platformer with lots of moving parts

### Describe the problem or limitation you are having in your project

When coding, I'll often make an initial quick pass of the code that gets the core functionality in, and insert # TODO comments to mark for later that I need to come back and fix, improve or expand some part of my code. In this way, a TODO statement is more important to me than a typical comment, and having a separate colour or formatting for that comment would help me find and resume working on things that need further improvement. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When I'm expanding a class, I want to at a glance see the TODOs separately from comments to know what features are missing and still need to be implemented. Whilst I can already use ctrl+F to find all TODOs in the project, I want a clear visual distinction to see which parts of a class I'm working on currently have caveats that may need to be addressed before continuing work in this class. This could be in the form of a different formatting style applied to comments that start with TODO in the text editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If a comment starts with TODO, that entire comment gets a different color, similar to this visual studio plugin that does similar. This could be an option that can be enabled / disabled in Editor Settings/Text Editor/Appearance

![image](https://github.com/godotengine/godot-proposals/assets/43807990/1de58401-0624-4db6-92f0-8b94f6527d4e)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't believe so

### Is there a reason why this should be core and not an add-on in the asset library?

The text editor is a part of the core engine and TODOs are frequently used in scripting both gdscript and c#

**Comment by Zireael07** [comment]
I'm like 99% sure it was already requested and 90% there's an open PR to do this.

**Comment by mieldepoche** [comment]
https://github.com/godotengine/godot-proposals/issues/4942

**Comment by AThousandShips** [comment]
Completed in https://github.com/godotengine/godot/pull/79761
