### ISSUE TITLE
Inspector folding Improvement 

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#7814]
### Describe the project you are working on

Projects on 4.x

### Describe the problem or limitation you are having in your project

With 4.0 and onwards the Inspector has too ways of folding the properties

- Folding Enabled : This is the default as of 4.2.dev* builds and in this option, properties are collapsed by default, except the top class, which are kind of expanded by default.
  User will **be able** to expand or collapse properties.

- Folding Disabled: This is other option which can be set in the editor settings and this option will expand all the properties in the inspector. 
  User will **not be able** to expand or collapse properties.

Both of the options have issues,

- Folding Enabled: 
  - To view a property value of a class the user has to expand the property, and it may have to expand subgroups too. Too Many clicks
  - Some of the nodes like HBoxContainer have only one property shown from BoxContainer and much needed Properties from Control classes are not shown by default. Too many clicks again, when the user just want to view the Properties.
  
![image](https://github.com/godotengine/godot-proposals/assets/84369217/fcbac0e3-e5eb-4ea1-938e-aa26612a5234)
  
- Folding Disabled:
  - User is not able to expand/collapse the properties
  - Too Much info like most of the projects I don't want to edit Node or script properties but it is shown

![image](https://github.com/godotengine/godot-proposals/assets/84369217/a7f45b61-4d3f-481e-9b6a-b968dd9a4fc6)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The proposed solutions do not request to change the existing implementation but adds changes to it, One or multiple options from below can be implemented.

- **Solution 1**: Also provide expansion and collapse at node/class level.
   This way user does not have to click multiple properties for just to view/edit some properties.
- **Solution 2**: By default, expand top three classes/nodes
- **Solution 3**. By default, expand all except Hierarchy below CanvasItem - Or make it configurable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N.A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Workaround is what we are trying to avoid, i.e., too many clicks.

### Is there a reason why this should be core and not an add-on in the asset library?

Inspector is part of the core editor

**Comment by tokengamedev** [comment]
It is a limitation in Godot so closing it.

**Comment by malcolmcdixon** [comment]
I've created a plugin to do this that's quite configurable for which groups you want auto expanded, check it out at https://github.com/malcolmcdixon/expand_this
