### ISSUE TITLE
Disable the blend file import setting support by default, to prevent the startup warning

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-proposals#7827]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

It's about a creating of empty project which immediately emit this warning to a console:

![изображение](https://github.com/godotengine/godot-proposals/assets/3036176/2d40b80b-53f1-4ec2-adbc-eb9a526dd17e)

I know it's easily to fix up, but IMO is not good experience for the new users which does not want to deal with it and see this warning.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Disable the feature or prevent this warning from emitting in new projects. Blend file support is not something every user wants in their project anyway.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by ywmaa** [comment]
My PR for it : 
https://github.com/godotengine/godot/pull/82242

**Comment by ywmaa** [comment]
Also it looks like FBX support is enabled by default too, should we disable it too ?

**Comment by Lamoot** [comment]
> Also it looks like FBX support is enabled by default too, should we disable it too ?

From what I understand, the .blend file importing works by referencing a path to the Blender executable. Hence the warning.

FBX import works differently in that it doesn't require any external programs and should definitely stay enabled by default. It would be a weird first-time experience if FBX import would need to be explicitly enabled. It's a standard way to transfer models to game engines and is expected to work out-of-the-box.

**Comment by ywmaa** [comment]
> FBX import works differently in that it doesn't require any external programs

afaik it does need an external program called [FBX2glTF](https://github.com/facebookincubator/FBX2glTF)

also maybe a warning should be added for FBX importer too.

**Comment by Lamoot** [comment]
Ah, you are right about that. I was assuming things to work out of the box, but when adding an .fbx file to Godot, I get an error popup that says it requires a path to FBX2glTF.

I'm not sure disabling the warning is the right way. When the models don't get imported into Godot, users not familiar with the editor's logic will have no hint as to what is causing the models to not import.

**Comment by souplamp** [comment]
I would also add that the warning is ineffective for those that need the feature the most.

It's a "hidden in plain sight" thing; recently watched a devlog and the developer was tediously importing Blender models to Godot scenes, and the warning was on screen hinting at the easier import method.

So not only do most users not need the feature, but those that need it won't even notice the warning is there. 

I think we should also discuss ways to make Blender import setup more obvious; maybe on engine setup, could there be a one-time prompt for setting the Blender import path?

**Comment by akien-mga** [comment]
Copying my reply from the linked PR:

I'm not sure this is the right solution.

The problem is the bad UX of having the import setting enabled by default, but Blender isn't automatically detected.
Disabling the import setting just means that users won't even know that Godot can import Blend files.

What this requires is either:
- Figuring out how to auto-detect where Blender is installed, if it's installed - could be used from `PATH`, though that's unlikely to be suitable on Windows or macOS.
- Make it easier for users to configure the Blender path when a .blend file is first added to the project, like we do for FBX2glTF. That's probably the better solution.

**Comment by Calinou** [comment]
Can we display this warning only if a `.blend` file is detected in the project?

**Comment by ywmaa** [comment]
> Figuring out how to auto-detect where Blender is installed, if it's installed - could be used from PATH, though that's unlikely to be suitable on Windows or macOS.

While making my PR, I think I saw code for that part, but it looks like it fails most of the time.

> Make it easier for users to configure the Blender path when a .blend file is first added to the project, like we do for FBX2glTF. That's probably the better solution.

maybe I can change my PR to that.

**Comment by souplamp** [comment]
Including the warning when a .blend file is present is a good solution, though if users don't know that Godot has a Blender import setting, then they are unlikely to include a .blend file with their project. Outside of that, it is a good solution for the original problem.

**Comment by KoBeWi** [comment]
https://github.com/godotengine/godot/pull/69012 would allow to move this setting to Editor Settings and disable it globally by people who don't need it.

**Comment by Chaosus** [comment]
Looks like this warning no longer shown at startup! So this proposal might be closed.
