### ISSUE TITLE
Add commands/shortcut to focus Compiler Output and Search Results panels

### ISSUE THREAD

**Issue by mlp1802** [godotengine/godot-proposals#7829]
### Describe the project you are working on

Learning godot

### Describe the problem or limitation you are having in your project

To reach Output and Search results, you have to use the mouse. Command or shortcuts would be preferable.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Command that focuses these areas. Additionally, Search Results should be auto focused after each search.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There's no code for it

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can't be worked around with script

### Is there a reason why this should be core and not an add-on in the asset library?

Completely standard in every other dev environment, besides, using the mouse can damage your hands.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/7301.
