### ISSUE TITLE
Create a way to get the controller's orientation

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot-proposals#7836]
### Describe the project you are working on

A library meant for mobile XR games which uses a bluetooth controller.

### Describe the problem or limitation you are having in your project

Getting the controller's orientation/gyroscope/acceleration.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would allow the programmers to get the controller's specific orientation/acceleration etc, which could be used in racing games or in menus.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`get_joy_accel(device: int) -> Vector3`
`get_joy_gravity(device: int) -> Vector3`
`get_joy_gyro(device: int) -> Vector3`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is so you can focus more on making your game other than finding the correct addon for what you're trying to make.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/2829.
