### ISSUE TITLE
Serialize data before sending and before recieving by rpc

### ISSUE THREAD

**Issue by iRumba** [godotengine/godot-proposals#7859]
### Describe the project you are working on

I'm creating multiplayer game

### Describe the problem or limitation you are having in your project

I want to send any structures, for example Texture, PackedScene or MyClass. But I can't. :)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think, it is impossible to configure serializing from side.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I think it can look for user as global settig `Rpc.configure_serializing(MyClass, Dictionary, some_func(MyClass) -> Dictionary)`

Or local 
```
@rpc()
@serialize(some_func(MyClass) -> Dictionary)
@deserialize(some_func(Dictionary) -> MyClass)
func rpc_func(data: MyClass):
    pass
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nothing

### Is there a reason why this should be core and not an add-on in the asset library?

Nothing

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6216.

**Comment by iRumba** [comment]
> Thanks for the proposal! Consolidating in #6216.

I read this issue and I don't understand way to send PackedScene. 

For example I want to send maps. I dont want to dublicate it on client and server. I want create process scripts (ClientLevel and ServerLevel) and send from server TheLevel.tscn with TileMap (TileSet if need) and some options.

Sure, I can send texture as bitmap, Tiles as some available data type and recreate it on client, but I think, that there is easier way.

**Comment by Calinou** [comment]
> Sure, I can send texture as bitmap, Tiles as some available data type and recreate it on client, but I think, that there is easier way.

As mentioned in that proposal, adding support for sending complex resources across the network is more complicated than it looks. There are also security concerns around this – it shouldn't be possible for clients to send executable code to the server by default.

**Comment by iRumba** [comment]
> > Sure, I can send texture as bitmap, Tiles as some available data type and recreate it on client, but I think, that there is easier way.
> 
> As mentioned in that proposal, adding support for sending complex resources across the network is more complicated than it looks. There are also security concerns around this – it shouldn't be possible for clients to send executable code to the server by default.

Yes, I understand. About security. Sender can check resorce for scripts (and nested scripts) and remove it with warning.

Using case

On server I have Map1.tscn and Map.gd (extends TileMap), that precessed map on server. 

On client I have Map.gd (extends TileMap) only

So, I can receive Map by
```
@rpc()
func(map: Map):
    #some code
```

When receiving sended resource instantiate (if it is scene) and aplly script Map.gd

It is safely, I think.

What about difficulty?

I don't know why it is difficult, because I don't know about real problems in source code. But I see problem with received resources organization.

I think sender can pack resources with its names and receiver can save all resources by names implicitly and use it with explicitly declared objects. 

For example. Server sends TileMap that contains TileSet res://resources/MyTileSet.tres that contains res://resources/MyAtlas.tres

Client receive it as Map extends TileMap and nested resources save as user://SomePath/resources/MyTileSet.tres and user://SomePath/resources/MyAtlas.tres

When server sends Map2.tscn instance client already has nested resources.

It solution has cache problems. If on server MyTileSet.tres will change, client will use old version. But it problem developer can solve by right organization. For example remove cache when server updates.

Also Engine can compare resources by hashsum.

If there are other problems please tell about.
