### ISSUE TITLE
Converting a resource path to a ' string ' path in visual script . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#786]
**Describe the project you are working on:**
A Tomb Raider game . . .

**Describe the problem or limitation you are having in your project:**
This is a VERY small problem, I use visual scripting, and like to use node boxes for EVERYTHING, right now if I move a ' scene ' into canvas, from res folder, it creates a ' Preload ' box, with a folder name, in it . . .

But, to ' change scene ', using the Get Scene Tree method box, I need the ' path ' to be written, as a string, and the obj from the ' Preload ' box doesn't go into, the Change Scene method, it only takes a string . . . For visual coders, that are afraid to go into the engine, make changes to it, almost entirely, could one make a new visual script node box, that constructs a ' string ' of the path, in the ' Preload ' box, so one can connect it, to the ' Change Scene ' method, from the ' Get Scene Tree ' script box, without writing any weird lines, I know it's small, but it would make it nicer, for non-coders, and probably not take very long, for a good engine master <3 <3 <3

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would just be another node, in visual script, that converts the path, of a ' Preload ' output ' obj ' to, a string, which can then be plugged into ' Get_Scene_Tree > Change_Scene ' script box . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I would like a construct box, that sort of ' gets ' the preload box ' file path, and construct a string variable, from it, as a new box, very simple . . .

![2020-05-02 1427](https://user-images.githubusercontent.com/61069740/80864816-703ff480-8c85-11ea-81dd-dba1046181e1.jpg)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I can't change the engine, I can't code, it would be really nice, for code-phobes, like me, to have boxes for everything, as MUCH as possible <3

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, I'm not sure what this means, I think if it was an add-on, I'd have to download the ' new box ', and how would I know where, to do that <3

Know it's very small request, but it would be nice, as an artist, I leave the heavy lifting to the code-gods, won't go near it, got the code-phobia, <3 <3 Thank you, for your time <3

**Comment by Jummit** [comment]
You can use change_scene_to and give it the packed scene directly.

**Comment by YuriSizov** [comment]
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!
