### ISSUE TITLE
Add a way for areas to report current collisions or whether they are colliding

### ISSUE THREAD

**Issue by jaymehta-g** [godotengine/godot-proposals#7863]
### Describe the project you are working on

A game where the player can place an object which appears right in front of them. I don't want to be able to place into a wall, so I make an area with collision bigger than the object, place it where the object will appear relative to the player in the player's scene, check if it is colliding with the level, and only instance the placed object if the area is not colliding.

### Describe the problem or limitation you are having in your project

Unfortunately, areas have no 'is_colliding' or 'get_collisions' methods. They can only emit a signal when a body enters or exits. I end up having to keep a bool value that becomes true when the level enters the area and false when it leaves. This is a lot of extra code I need to write for a relatively common use case.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a `get_collisions` method that will return an array of all bodies currently in the area.  Now I can do `area.get_collisions().is_empty()` to check if the space is free to place the object.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know exactly how areas work internally, but if they do not have a way to directly scan all colliding bodies, it can keep track of the list of bodies internally, adding/removing bodies when they enter/leave the area.

This probably hurts performance, so add an exported bool, something like "track collisions", that you can use to opt into the feature.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would all be possible through a script, but it will be used often enough that making this behavior built in would be worth it.

### Is there a reason why this should be core and not an add-on in the asset library?

Checking if an area is currently colliding or getting all current collisions is a behavior used commonly enough that it should be built in to the area node.

(I know bodies entering/exiting areas are technically not collisions, so the language would need to be updated to be more accurate)

**Comment by jaymehta-g** [comment]
Already implemented

**Comment by Calinou** [comment]
> Already implemented

To help people who find this proposal from a web searchn please document the solution here by commenting :slightly_smiling_face:
