### ISSUE TITLE
Add Continuous Collision Detection to Physical Bones

### ISSUE THREAD

**Issue by eddieataberk** [godotengine/godot-proposals#7882]
### Describe the project you are working on

A 3D game with physical animations

### Describe the problem or limitation you are having in your project

Physical bones go through surfaces at high speeds. Currently, I'm working around that issue by creating a rig that utilizes RigidBody3D instead of Physical Bones just to use CCD.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Just like RigidBody3D add Continuous CD option to Physical Bones. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/48696693/1e5934ed-470e-4e90-a7ac-1d8fb8afbd63)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving a built-in class

**Comment by eddieataberk** [comment]
for child in get_children():
		if child is PhysicalBone3D:
			PhysicsServer3D.body_set_enable_continuous_collision_detection(child.get_rid(), true)	

calling this code to Skeleton3D enables ccd for physical bones

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/5291.
