### ISSUE TITLE
Simplify getting all tile atlas coordinates in a TileSetAtlasSource

### ISSUE THREAD

**Issue by Stronkkey** [godotengine/godot-proposals#7902]
### Describe the project you are working on

TileMap Level editor (resource)

### Describe the problem or limitation you are having in your project

It is way too hard to get all tile coordinates in a TileSetAtlasSource. I need to get all tile coordinates to make a preview of all tiles (because a level editor where you can't see what you can place is not useful).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a function that returns all tile coordinates.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`
atlas_source.get_all_tile_coords() # Returns all tiles coords as Array[Vector2i]
`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is possible to use get_atlas_grid_size in a loop, but then you would have to check if the coordinates form a bigger tile or if they are standalone tiles which could be perfomance heavy.

### Is there a reason why this should be core and not an add-on in the asset library?

This is already internally implemented inside TileSetAtlasSource as `tiles_ids` which can be returned.

**Comment by Stronkkey** [comment]
I have already made implementation of this [here](https://github.com/godotengine/godot/commit/4ba3206e80d516369689234fb634c63a7a395b7e).

**Comment by Stronkkey** [comment]
I discovered that TileSetAtlasSource has a function to check if a tile exists (`has_tile()`) which can be used when looping through the Grid size to achieve this. It would still be nice to have a native function to do this as it can easily be exposed with better perfomance because it already saves all tiles coordinates.
```gdscript
static func get_all_tile_coords(tile_source: TileSetAtlasSource) -> Array[Vector2i]:
	var coords: Array[Vector2i] = []

	var grid_size = tile_source.get_atlas_grid_size()
	for x in grid_size.x:
		for y in grid_size.y:
			var tile_coord: Vector2i = Vector2i(x, y)
			if tile_source.has_tile(tile_coord):
				coords.append(tile_coord)

	return coords
```

**Comment by arkology** [comment]
Why closed? This is still requested.

**Comment by Stronkkey** [comment]
Closed because there is a workaround that works perfectly fine. [The PR is still open for consistency among on tilemap resources.](https://github.com/godotengine/godot/pull/82636)
