### ISSUE TITLE
Spritesheet Import Type (New type of Import for images)

### ISSUE THREAD

**Issue by Grainen** [godotengine/godot-proposals#7904]
### Describe the project you are working on

Im working on a simple cookie clicker game, but randomly hit an issue/thought.

### Describe the problem or limitation you are having in your project

I wanted to use less images than needed for my texture buttons, but i can't seperate the image into two.
![start_button_spritesheet](https://github.com/godotengine/godot-proposals/assets/97611394/66e7ecae-f5d3-4bd4-bd25-4c87e61f9632)

It would also be nice if i could have all of them inside a single image, like this:
![main_menu_buttons_spritesheet](https://github.com/godotengine/godot-proposals/assets/97611394/8ca2aeff-0510-4e98-8595-3a54cf56a4d2)

While you can use spritesheets for Sprite Nodes and i believe animations, but other than that, you can't use spritesheets for other things (i think).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would be able to set the import on the image as something like 'Spritesheet' and then edit the spritesheet to make godot see that i there are two images inside this single image and then being able to apply this to things like texture buttons etc.

It would allow games to have less files and help optimize things.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Changing the Import type of the image/resource file into Spritesheet will show a button 'Edit Spritesheet' in the Import Settings and you can slice the image using grid (width and height) and it will slice it.

When clicking Done, a dropdown arrow shows next to the spritesheet inside the FileSystem, and inside there will be the images that where sliced and they will have the original file name and number like '0' or '1' and it increases the more images you sliced out of it, and you can just drag and drop them like any other image file into things like texture buttons, even animation etc. Also whenever you try to drag and drop the original file, it will just default to the first sprite '0'.

After a bit of photoshopping. it would look something like this.
![feature_suggestion_image](https://github.com/godotengine/godot-proposals/assets/97611394/cc42b61a-cd90-4259-ac96-c71f147aee28)

And inside the 'Edit Spritesheet window', something like this:
![feature_display](https://github.com/godotengine/godot-proposals/assets/97611394/e5de3302-6ee2-47fb-882d-fccc02424709)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know much about plugins, but i don't think it is possible anyway. But i still think this is a good feature.

### Is there a reason why this should be core and not an add-on in the asset library?

It's definitely going to be used in the future alot for spritesheets and other images. Also i don't think/know if you can do this with just an add-on.

**Comment by inhalt120g** [comment]
Reading the feature / enhancement… everything there can already be achieved with Atlas Texture and (in this case) setting each button as a separate region. Or am I missing something? Here I made a few textured buttons sd sn example (with the original texture on the left) but the same resource can be used to make animated sprites or whatever:
![image](https://github.com/godotengine/godot-proposals/assets/106015575/a5f1608e-8eac-458a-95db-cf05b86eea96)

**Comment by Grainen** [comment]
Ah i see now! I apologize, i didn't know it was already implemented. Thank you for telling me that! (:
I will now close this proposal.
