### ISSUE TITLE
preload() issue, "Preloaded path must be a constant path"

### ISSUE THREAD

**Issue by Rebell10n** [godotengine/godot-proposals#7906]
### Describe the project you are working on

Heya there, I'm working on a small RPG platformer, but not the important point here.

The part I'm struggling on is a preloaded Script Lib for all "Knots", (I guess you can picture that as differents abilities)
And there is gonna be a lot of them, so I don't want to do 1000 preload, with each differents paths, yes you can drag and drop to get the path directly, still this gonna be hell to do that way, cuz 1000 might be a big number or a small number depending on how much time I put on the project.

### Describe the problem or limitation you are having in your project

The limitation ?
For that : 
![image](https://github.com/godotengine/godot-proposals/assets/43638454/b19bb120-1f6f-4b5c-aa5d-4de821484b45)
I get this.
![image](https://github.com/godotengine/godot-proposals/assets/43638454/1160b306-d2b8-468b-ab85-542fc414fa13)
So yeah... I understand where the issue is for the editor/etc, but that shouldn't in my humble opinion, especially while well, thoses are all constant strings, just stored in an Array, and just want to preload them while going through the array.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well can't deny that I've seen some similar post : https://github.com/godotengine/godot-proposals/issues/531, that covered a similar issue with preload() and load(). Honestly maybe I should'nt posted there anew post, maybe that was worth it to do it, I don't know.
Well if I shouldn't, guess responsible person gonna archive it, cuz I'm a newbie to posting suggestions on github. (Hope not everyone think like that through)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know how preload() work honestly, I don't have an hint on how it work. But I can picture it can preload from a string that is "constant". So technically in this for loop, while accessing the array, it should just get it like a "true" string, even if the id is different, after all it can't get something else from that array. 

Well maybe in some others code it could get something else, but I guess you would need typed array for that, and it's yet to come, so would just assume it's the programmer error till they got typed array.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Actually no.

Like I've seen a post where this happened, and the guy asked how he could improve it, but his objective being different than mine a got differents answers. Like naming each scripts classes, which would be the more easier solution for me (easier don't mean easy here), while the others was Autoload, which means adding thoses possibly hundreds of thousands of scrips each time in the autoload...

### Is there a reason why this should be core and not an add-on in the asset library?

Uhhh, I don't know. No real idea how to answer that, cuz I don't know how myself I would code it cuz I never coded an add-ons, even more on Godot, but the real question would be... can an add-on (really) modify the preload() function ?

### Duplicate or not
Yeah, I know this could be taken as a duplicate of https://github.com/godotengine/godot-proposals/issues/531, but maybe not, since I didn't know I prefered make a post about it. If that shouldn't been, feel free to do whatever needed, archive it or something else.

### Script overview
Here the script where it happens, so you can see yourself that probably not because my code is awful, or maybe it is for another reason lol
```gdscript
extends Object

const base_path = "res://Knots/"

var dir = DirAccess.open(base_path)
var KnotsLibPath = []
static var KnotsLib = []
var TypeFolders = []

func _init():
#	dir.list_dir_begin()
	TypeFolders = dir.get_directories()
	
	var filename
	
	for i in TypeFolders.size():
		var TempArray = dir.get_files_at(base_path+TypeFolders[i])
		for r in TempArray.size():
			TempArray[r] = base_path+TypeFolders[i]+"/"+TempArray[r]
		KnotsLibPath.append_array(TempArray)
	
	for i in KnotsLibPath.size():
		KnotsLib.append(preload(KnotsLibPath[i]))
```

**Comment by lufog** [comment]
Why not to use load()?

**Comment by Rebell10n** [comment]
.... Feels stupid now that it works... But then I have severals questions now... Why in the docs it says load() would work only with absolute path ? Did I misunderstood what absolute path means ? Like isn't a relative path a path that depend on the project folder

**Comment by Calinou** [comment]
> But then I have severals questions now... Why in the docs it says load() would work only with absolute path ? Did I misunderstood what absolute path means ? Like isn't a relative path a path that depend on the project folder and the absolute path depend on the harddisk one ? or that something different ?

An absolute path is a path that starts with `/`, `res://` or `user://`. Relative path is a path that does *not* start with that.

**Comment by Rebell10n** [comment]
Goodness... I was wrong all along, well thanks for the suggestion and the explanations. And sry to have made a post for... nothing 
in the end ?

**Comment by Calinou** [comment]
Closing, as there are no built-in engine changes to make.

**Comment by Sebauxs** [comment]
This helped! thanks
