### ISSUE TITLE
Split plugins on project and engine sides

### ISSUE THREAD

**Issue by NaleVex** [godotengine/godot-proposals#7915]
### Describe the project you are working on

Any project that use plugins, best use cases for popular plugins that users download for most of their projects.

### Describe the problem or limitation you are having in your project

Currently we can use download plugins as project side plugins, after downloading plugin we see it's contents in project file system and use those files if needed. But many plugins are just tools that user want to use as editor expansion and their "binding" to specific project and necessity to import/download for every project is counter intuitive as well as plugin files litter project file system.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This suggestion is about to make ability to make "Editor side" plugins, that "connect" not to specific project, but to whole engine version for every project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Users now have access to `Engine side plugins location` setting in `Editor settings`. Plugins now may be downloaded as `Project plugin` or `Editor plugin`. If user choses `Project plugin`, that plugin behaves same way as it works today. Plugins downloaded as `Editor plugin` store in chosen `Engine side plugins location` folder. Editor now register that folder as usual plugin folder for every project using this version of Godot. User still may turn on/off of what plugins from that folder should work in current project. `Engine side plugins location` not displayed in project File system but user still can toggle showing/hiding of that folder in File system (mainly for plugin developing). 
Plugin makers have new methods to use for plugins that may behave differently or have specific settings per project (for example: unique git settings, folder or project location on github for every project).
It total:
- In most cases "Engine side" plugins behaves like normal plugins if registered for current version of Godot and turned On for current project.
- User, on creating new project using same engine version, should not download "Engine side plugins", only to turn on already existing ones for new project.
- User have access to "Engine side plugins" folder toggling it on or off in File System.
- Plugins may be installed both ways from AssetsLib or manually moving folder with plugin to project file directory or "Engine side plugin" folder.
- Plugin makers have instruments for plugins to check if plugin works as in "project side" or "engine side" to store data per project correctly.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It cannot, the only way today is to download and register plugins every time in every new project.

### Is there a reason why this should be core and not an add-on in the asset library?

This whole idea is about how plugins should work in engine.

**Comment by YuriSizov** [comment]
Thanks for your detailed proposal. Consolidating with https://github.com/godotengine/godot-proposals/issues/831.
