### ISSUE TITLE
A simple idea for rearranging the dock-placement so it's more comfortable . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#792]
**Describe the project you are working on:**
A Tomb Raider game, about an explorer, history - student, like Lara Croft . . .

**Describe the problem or limitation you are having in your project:**
Okay, this is more of a lesser thing, not important, but I've always played a lot of games, action games, RPG's, and they have a classic inventory, often, where there are ' stats ' ( dex, str, vit, so on ), to the far left, a 3D preview of the character in the middle, where one can change armor, clothes, so on, and an inventory to the right, with all the ' stuff ' one has, loot, other stuff . . . I tried rearranging the docs, so it looks more like that, like this . . . So, I have the inspector ( stats, on the nodes, or so ) to the far - right, the 3D scene, in the middle, and the resource folder, and node tree dock, to the right, like so . .
![2020-05-03 0701](https://user-images.githubusercontent.com/61069740/80899121-7c22c980-8d0c-11ea-8ad8-7efe0ee3ac8c.jpg)

So, it looks like a classic screen, from most action games, RPG's, which I am very comfortable with, like these . .

![2020-05-03 0626](https://user-images.githubusercontent.com/61069740/80899127-90ff5d00-8d0c-11ea-9cc0-74688c336fe3.jpg)

![2020-05-03 0641](https://user-images.githubusercontent.com/61069740/80899134-96f53e00-8d0c-11ea-976e-3d15ef9d1262.jpg)

Godot is already very user-friendly, I wanted to ask, maybe make this the standard dock layout, and sort of explain, somewhere, that this is why, so it FEELS like a game, to MAKE a game, in Godot, as well, very fun, relaxing . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It's just a way of subtly making it more nice, to work with Godot, for gamers . . . . I know it's dumb, but it makes a lot of sense, to seasoned gamers, you just ' think ' like you're in the inventory, of a classic RPG, action game, when ' building ' the game, making using Godot, FEEL like a game, as well . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See images above, just a suggestion, know it won't change very much, just make it bit more relaxing for users, to use the engine, so it even feels like a GAME, to make the games . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I know it's silly, but it works for me, makes it more fun, understandable, play a game, to make a game, very fun, happy . . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, it's just a suggestion, for the makers of the engine, know it's probably beneath their time, but it could be quite fun, if it said in the docs, for the engine, the reason the layout is like so, is to make you feel like you're playing a game, while making a game, having more fun, joy . . .

It's just a nice thing, not important, really like it myself, it is what it is, a noob suggestion . . .

**Comment by jasperbrooks79** [comment]
Also, in an action-rpg game inventory, one sort of ' drags ' the stuff one has, on to the character, in the middle, and one can see the stats ( properties ) of the nodes, to the left, classic game - experience <3

So, it feels like a game, to use Godot, all the time, as well . . .

Know it's a bit dumb, but maybe you like it, a bit <3

**Comment by jasperbrooks79** [comment]
So, it's like you're making a 3D character, in an action game, or RPG game, while programming Godot, very natural, fun . . Levelling it up, adding new armor, changing stats, other stuff . . . It's silly, but also a bit neat, fun . . .

**Comment by Jummit** [comment]
Isn't this already achievable, as you shown in the first screenshot?

**Comment by jasperbrooks79** [comment]
Yes, but maybe it was nice, actually yes, just wanted to share, really like it myself, a lot . . Maybe others feel the same way, but you're right, it's not necessary . . .

:) <3 <3

**Comment by mhilbrunner** [comment]
Godot already supports rearranging the docks as you want, as you have shown.

We also changed around the docks in the default layout quite a bit in the recent past.

Changing the default layout *again* with 4.0 should only be done with a very good reason.

As this proposal doesn't offer any reasoning besides a vague "it would be fun", I'll close this for now.

Thanks for taking the time to write up a proposal. If you really would like to propose changing the default layout, please try to show how it improves working with the editor to such a degree that it is worth the tradeoff of forcing people to learn a new layout or manually change their layout back to the old default.
