### ISSUE TITLE
Ehancements to the Code Text Editor Side Panel Icons

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#7928]
### Describe the project you are working on

Multiple Projects

### Describe the problem or limitation you are having in your project

In the side panel where breakpoint run and bookmark icons are showed. It currently looks mangled when they are on the same line of code
See the picture below:
![image](https://github.com/godotengine/godot-proposals/assets/84369217/aec82e02-989c-47a1-b10a-fdb735e974ab)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Organize the icon in the order of priority and enhance it, so that it looks appropriate in all kinds of possibilities. 
I am not sure possibility of other icons to be displayed, but I will go with these for now. 

**Priority of icons from high to low**
- Run
- Breakpoint
- Bookmark

_This is in my opinion_

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Suggested Icons with their sizes, the color option is themed, so it can be changed based on the theme as it can do now.

 
![icons options](https://github.com/godotengine/godot-proposals/assets/84369217/9060a0b1-53a3-48b1-8c64-48a43fa396f6)

I shamelessly copied some idea from visual studio, but it makes sense.
All icons are designed out of 24 X 24 and is for reference.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Mostly as it will be used during debugging and other purposes. 

### Is there a reason why this should be core and not an add-on in the asset library?

Code editing is part of Core

**Comment by Zireael07** [comment]
That "side panel" is called the gutter, just to help people searching.

**Comment by inhalt120g** [comment]
This will work well as long as there are only three icons that have to be combined. If ever another icon has to be added to the gutter area, the stack point would just turn into a minestra (no offense to minestra, I actually like it a lot).

**Comment by tokengamedev** [comment]
> This will work well as long as there are only three icons that have to be combined. If ever another icon has to be added to the gutter area, the stack point would just turn into a minestra (no offense to minestra, I actually like it a lot).

I think you would have noticed there are already few more icons, and also there are two gutter areas, divided by functionality I believe. 
I agree with you there may be a functionality that may come up in future. Even I don't know if some feature already exists which I missed out, here. 
In this proposal I am proposing to declutter and streamline the already existing icons in the gutter area where user interaction is possible (like adding and removing breakpoints or bookmarks).

Additionally:
 - The code editor should highlight the code line by coloring the background too, like in other editors. **May be another proposal.**
- Adding and removing bookmarks using RMB and `Ctrl+B` to travel to the next bookmark and `Ctrl+Shift+B` to shift to previous bookmark. **May be another proposal.**
- Adding a Tasks panels listing all the bookmarks, TODOs, errors, warnings and more **May be another proposal.**

When time permits, I will search for or create one proposal.

@MewPurPur, would like to listen, your take on this.

**Comment by MewPurPur** [comment]
`Shift + B` is the easy way to add bookmarks

I don't think this will happen, each of these is an individual, whited out icon, whose different colors are based on the editor theme. What could happen is the three icons being reordered slightly when there are multiple in the same place, so they don't overlap ugly.

**Comment by YuriSizov** [comment]
I don't think they are supposed to overlap. The gutters system is designed to account for all of them. This looks like a bug (at least for the bookmark and the other two).

**Comment by YuriSizov** [comment]
> I don't think the gutter has ever had any logic for preventing overlaps.

It has. We have a collection of gutters and ensure all the visible ones contribute to the overall width.

**Comment by MewPurPur** [comment]
OH I see what you mean. This is a misunderstanding though, we have:
- Folding gutter, has folding arrows and now also folding regions
- Info gutter, has indicators for when methods are overridden or connected by signals. If a method is both, a 3rd special icon is displayed that's like a combination of the two.
- Main gutter

The main gutter contains these 3 icons and has not had any logic to separate them.

**Comment by Paulb23** [comment]
The main gutter should contain all three. The layout of the icons were biased off of QT Creator (https://github.com/godotengine/godot/pull/40973) though it looks like some of the icons have changed since then i.e no black outline around the bookmarks and much larger.

**Comment by tokengamedev** [comment]
As per the comments above it is ok, and contributor is not willing to change it, so closing it.
