### ISSUE TITLE
Automatically Repair Broken Project References

### ISSUE THREAD

**Issue by Naxum** [godotengine/godot-proposals#7935]
### Describe the project you are working on

My first Godot game for a game jam. I'm constantly moving my files around to try different project organization structures. 

### Describe the problem or limitation you are having in your project

Moving files to new folders and/or renaming files often causes a myriad of issues where scenes, resources, worlds, etc can no longer be loaded in Godot due to their external reference paths no longer pointing to the right assets. 

Often times a single leaf node will recursively cause of its hierarchy containers to not load, so tracking down which file needs its references resolved can be quite burdensome. Before making any file-level change I feel like I need to make sure I'm in a stable state in version control so I can back out of a change if I can't figure out how to resolve it in a reasonable amount of time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot should more gracefully handle this common error scenario and present an assistant window to identify and resolve the issues in as much of a streamlined way as possible.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When an external resource link is broken, Godot should offer an assistant window to:
1. Reveal specifically which files have broken references
2. Reveal specifically which references are broken
3. Ideally offer quick fixes in cases where the same file and extension exists in your project, just at a new path.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Today, you must recursively investigate each of your file's references (which you must either remember yourself or hit "edit dependencies" and make a mental note of all of the listed items) and manually open each file's dependencies to see which have missing references. It's quite burdensome.

### Is there a reason why this should be core and not an add-on in the asset library?

This is an essential workflow improvement to using Godot.

**Comment by KoBeWi** [comment]
> Moving files to new folders and/or renaming files often causes a myriad of issues where scenes, resources, worlds, etc can no longer be loaded in Godot due to their external reference paths no longer pointing to the right assets.

This is a bug. It's partially fixed in 4.2 dev5, with (hopefully) remaining part fixed in dev6.

**Comment by Naxum** [comment]
Oh you love to hear it!

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/6838 (as the rest of this proposal is a bug per the above comment).

**Comment by william-tjandra** [comment]
Hi! Just wondering if this also includes renaming Nodes in the editor.

For example:
- I have a `House/Room/Desk`. 
- In `house.gd`, I get a reference to desk using `$Room/Desk`.
- I rename `Desk` to `Table`
- I'm expecting `house.gd` to update `$Room/Desk` to `$Room/Table`, or at least show a notification that the path `$Room/Desk` does not exist.

**Comment by KoBeWi** [comment]
It doesn't and such feature would be difficult to implement without making renaming nodes extremely slow.

**Comment by NeonMika** [comment]
> It doesn't and such feature would be difficult to implement without making renaming nodes extremely slow.

I would much rather love to see slow renaming than having my game broken.
Also, if GDScript's compiler builds a good IR/AST, such a feature shouldn't be that hard to implement.
