### ISSUE TITLE
Improve editor profiles

### ISSUE THREAD

**Issue by ltecheroffical** [godotengine/godot-proposals#7941]
### Describe the project you are working on

A 2D RPG type game

### Describe the problem or limitation you are having in your project

When using editor profiles to hide tabs, they end up affecting all projects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a per project way to select editor features.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In project settings allow users to select editor feature profiles.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It cannot be worked around at all.

### Is there a reason why this should be core and not an add-on in the asset library?

This is useful for varied projects and this is not possible with an editor plugin.

**Comment by arkology** [comment]
See https://github.com/godotengine/godot-proposals/issues/827

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/827.
