### ISSUE TITLE
Move "Add Metadata" button to 3 dots menu

### ISSUE THREAD

**Issue by dmitryuck** [godotengine/godot-proposals#7949]
### Describe the project you are working on

Godot Editor

### Describe the problem or limitation you are having in your project

A suggestion to move Add Metadata button to 3 dots menu, since it's not used very often, and this button can confuse users coming from Unity where they see the Add Component

![Center-Container](https://github.com/godotengine/godot-proposals/assets/20966824/1328e81c-a9cf-496a-adce-f895293ba474)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This big button looks like something often used and important but this is not true, to not be like Unity's Add Component button, let's move it up in to 3 dots menu)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It looks very similar to Unity's Add Component button and for new users it can confuse, since it's not used often I believe, nothing bad happens if we move it to 3 dots menu from the panel

### If this enhancement will not be used often, can it be worked around with a few lines of script?

definitely not often

### Is there a reason why this should be core and not an add-on in the asset library?

Just Editor small UX improvement

**Comment by Calinou** [comment]
The button is at the bottom of the inspector, so it's not pushing down anything else. I don't think we should make this feature harder to discover.

**Comment by MrBBBaiXue** [comment]
Maybe the only thing we need to do is changing the button more consistent with the rest of the inspector
