### ISSUE TITLE
AStar check is there an (indirect) connection between 2 points

### ISSUE THREAD

**Issue by PoirotovBrk** [godotengine/godot-proposals#795]
**Describe the project you are working on:**
Turn based strategy game. Godot 3.2.1 stable and C#.
**Describe the problem or limitation you are having in your project:**
No way to check are 2 points connected.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
_AStar_ has a function called 
`are_points_connected ( int id, int to_id )
`
First of all, yes this function checks the connection, but it only checks (or return _true_) a direct connection between 2 points. I think one should emphasize this in the official documentation. 

For example, in connection A-B-C
`are_points_connected (A, C) == false` 
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
There already exist a sort of a solution to check are A-C connected, like so:
```
int[] are2PointsIndirectlyConnected =  star2D.GetIdPath(A,C);
if(are2PointsIndirectlyConnected.Count() >0)
       return true;
else
       return false 
```
However, this solution results in some small slowing/glitch of my app and debug message:   
```
ERROR: get_id_path: Condition "!from_exists" is true. Returned: PoolVector<int>()
   At: core/math/a_star.cpp:486
```
It doesnt _feel_ like this is healthy for the app.

I checked the original cpp code and a_star.cpp:486 comes from here:
```
Vector<int> AStar::get_id_path(int p_from_id, int p_to_id) {

	Point *a;
	bool from_exists = points.lookup(p_from_id, a);
	ERR_FAIL_COND_V(!from_exists, Vector<int>());
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
A quick solution is provided above, but I wanted to see if someone could check is this ok and/or would it make sense to add a _cleaner_ function whos sole purpose is to check does any indirect path exisit between 2 points.
**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it is reasonable to have in _AStar_  a clean function checking is there a path between A and C in connection A-B-C.

**Comment by Kequc** [comment]
From m understanding of the way this works, there is no faster way to find out whether two points are indirectly connected. You would have to perform a search as in your example. The error you are getting seems to say one of the points you are searching for doesn't exist.

**Comment by GaryShem** [comment]
There is no way to check if 2 arbitrary points are indirectly connected without actually tracing a path between them.

However, if you're making a turn-based strategy with some form of grid/tiles and a map where pathing doesn't change, you can either pre-calculate paths and save the results so you can avoid wasting calculation checking them later; OR save the check results as you do them to serve as cache (so you only have to make every check once).

**Comment by PoirotovBrk** [comment]
Calculating everything once and using that information doesnt come into question, as every turn the grid is being changed.
I am trying to make a workaround and bypass the problem.

Lets say I have a following AStar grid 
```
A0 - B0 - C0 - D0
|    |         |
A1 - B1   C1   D0
```
 
C1 is isolated. It exists as a point in my AStar but its not connected to anybody else. 
B0 is an important node, and I want to know is B0 connected to C1. Right now, the only thing that works is the _trick_ code I described at the beginning. 

Alternatively, I could try to get all the nodes with which B0 **is** connected. This would help me as I could indirectly know do we have a connection B0- C1. But for that I need to make some sort of algorithm on my own.  Also, since the real grid is around 100x100, I dont really wannt to get all connections for B1, but maybe only those within N steps...

There already exists a function _get_point_connections()_ which returns connected points of a single point. 
I think I will try using some recursive function starting at B0 and applying _get_point_connections_ on the way.
In the end I think I will get all the nodes except C0.

**Comment by Kequc** [comment]
Your trick code is the correct way to do it though.

You could improve your trick code's performance a little bit if it's common for an individual node to be completely isolated by first checking whether both points you are looking at have any connections. But using your AStar instance, to know whether there is any valid path between two points, you'll have to perform a search.

**Comment by PoirotovBrk** [comment]
Ok, but even if we say that this solution for checking connection between 2 points is ok;
```
int[] pathOfPoints =  star2D.GetIdPath(A,C);
if(pathOfPoints.Count() >0)
       return true;
else
       return false 
```
I think that the debug/error information should be remove. Because if this is a legitimate and valid way to check are 2 points connected, one shouldnt be notified about some errors during execution.

**Comment by PoirotovBrk** [comment]
Like I said, the main problem now is _a_star.cpp:486_ and the error line (I guess):
Vector<int> AStar::get_id_path(int p_from_id, int p_to_id) {

	Point *a;
	bool from_exists = points.lookup(p_from_id, a);
	**ERR_FAIL_COND_V(!from_exists, Vector<int>())**

So when trying to check is there a connection between two points by geting all the points in the path and when there is no connection - debugger gets error messages. When one checks the connection as a part of its game mechanic than these error messages pile up.

If there are no objections, I will open up an issue on the main godot repo to try to point to this problem.

**Comment by PoirotovBrk** [comment]
Like I said, the main problem now is _a_star.cpp:486_ and the error line (I guess):
Vector<int> AStar::get_id_path(int p_from_id, int p_to_id) {

	Point *a;
	bool from_exists = points.lookup(p_from_id, a);
	**ERR_FAIL_COND_V(!from_exists, Vector<int>())**

So when trying to check is there a connection between two points by geting all the points in the path and when there is no connection - debugger gets error messages. When one checks the connection as a part of its game mechanic than these error messages pile up.

If there are no objections, I will open up an issue on the main godot repo to try to point to this problem.

**Comment by Kequc** [comment]
As I suggested that error might be telling you that one of the points doesn't exist. When I have used the AStar tool it I believe correctly returned an empty array when there is no valid path. But if I'm wrong I hope that gets fixed.

**Comment by PoirotovBrk** [comment]
> As I suggested that error might be telling you that one of the points doesn't exist. 
Exactly that was the problem, thanks for help, I closed the issue.
