### ISSUE TITLE
Create public to_ok_hsl functions

### ISSUE THREAD

**Issue by Hysterelius** [godotengine/godot-proposals#7954]
### Describe the project you are working on

A 2D world map game with a variety of different countries in different colours.

### Describe the problem or limitation you are having in your project

Not currently able to create hsl colours from the base `Color` function.

I want to be able to create different variations of a rgb colour, through changing the lightness values, i.e. having light red troops for the red territory. This new function would allow it to be programmatically generated. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Creating a new `Color` function to allows `rgb` to be converted into `ok_hsl`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This would just involve exporting an already existing `srgb_to_okhsl` function:

https://github.com/godotengine/godot/blob/0ca8542329888e8dccba89d59d3b728090c29991/thirdparty/misc/ok_color.h#L542-L588

It could work like this:
```gdscript
var red = Color.RED
red_hsl = red.to_ok_hsl()
red_hsl.l += 10 # Makes red lighter by adding 10 to its lightness value
var light_red = Color.from_ok_hsl(red)
```

It would also involve creating a new `ok_hsl` class for easily passing around hsl values.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it would involve having to rewrite all this code:
https://bottosson.github.io/posts/colorpicker/

### Is there a reason why this should be core and not an add-on in the asset library?

This is already a standard library feature, which is currently not exported and it would be a simple implementation.

**Comment by Hysterelius** [comment]
I am happy to make a PR for this, as I am pretty sure I can get this working.

**Comment by Hysterelius** [comment]
Just wondering if anyone had any input on this idea with the ergonomics.

I'm considering two different approaches for editing the `Color` (but leaning toward the 2nd):

1. Should the `Color` be edited through conversion?
```gdscript
var red = Color.RED
red_hsl = red.to_ok_hsl()
red_hsl.l += 10 # Makes red lighter by adding 10 to its lightness value
var light_red = Color.from_ok_hsl(red)
```

2. Or should `Color` be edited in place?

And what should it look like? (I am currently thinking `Color.ok_hsl_l`) 
As HSL `h` and `s` values are different from HSV values (so it cannot line up with existing `Color` functions (`Color.h`, `Color.s` & `Color.v`)
```gdscript
var red = Color.RED
red.ok_hsl_l += 10 # Makes red lighter by adding 10 to its lightness value
```

**Comment by lostminds** [comment]
Is there another use for this apart from making lighter or darker color variants? For that Color already has [lightened() and darkened()](https://docs.godotengine.org/en/stable/classes/class_color.html#class-color-method-lightened) methods, and for greater control you could also use lerp() to mix the color with a reference color (like a specific black/white) to make it lighter or darker.

**Comment by Hysterelius** [comment]
The lightened() and darkened() methods in `Color` do provide a way to create lighter or darker colour variants. However, they operate on a percentage basis, which means the effect can vary depending on the original colour. For example, lightening a light red by 10% won’t have the same visual impact as lightening a dark red by the same percentage.

The OkHSL lightness value I’m proposing offers a different approach. It allows us to define “stops” of colour, creating a more controlled and predictable range of lightness values. This can be particularly useful when creating colour palettes like the one below, where each colour variant has a distinct lightness value.

[![image](https://github.com/godotengine/godot-proposals/assets/71912794/ac4d397c-8c8a-48c6-bf40-313ea0d14309)](https://coolors.co/e31313)

I hope this clarifies the intent behind my proposal and why OkHSL is a better way of achieving this. OkHSL would also allows for the manipulation of consistent saturation.

**Comment by lostminds** [comment]
Ok, thank you for the explanation. To get back to your earlier question I think option 2 above would be preferable if this was added. Basically since it would keep the same pattern as when editing RGB or HSV components for editing this new ok_hsl L component. Solving this by just adding some internal conversions in Color also avoids the complexity of a new subtype of the Color class for just this specific use.

**Comment by Hysterelius** [comment]
Could you help or know someone who could help with the implementation of this? (especially with the inline mathematics (e.g., `+=`, `\=`). I am pretty sure I could work out to implement it in cpp but not sure about the gdscript or c# aspect.
