### ISSUE TITLE
Allow drag-and-drop of Script files onto exported Script variables

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot-proposals#796]
**Describe the project you are working on:**
Tutorial (N/A)

**Describe the problem or limitation you are having in your project:**
I have a tool node with an exported `Script` variable.
Dragging a script onto the exported variable doesn't work.
The "red circle backslash" symbol doesn't go away when hovering over the exported variable, so the script can't be dropped there to set the variable.

Here's a screenshot:
![DragDropProblem](https://user-images.githubusercontent.com/60025044/80925111-e9f1e400-8d52-11ea-83dd-fd96560b6b60.png)

I statically typed the exported variable as a `Script`, so I would expect drag-and-dropping to work.
Here's the code:
```
export(Script) var other_script: Script = null setget set_other_script

func set_other_script(__script: Script) -> void:
	other_script = __script
```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Exported `Script` variables should allow drag-and-drop in the same way that we can drop scripts onto nodes.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![ScriptDragDropExample](https://user-images.githubusercontent.com/60025044/80924896-769ba280-8d51-11ea-80bd-aa0903f089a3.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think this is possible with script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't think this is possible with an add-on.

**Comment by Jummit** [comment]
Seems like a bug tbh.

**Comment by Janders1800** [comment]
Your syntax seems wrong, I had no problem doing drag-and-drop with this.

`export var test: Script `

![Captura de pantalla de 2020-05-04 14-03-51](https://user-images.githubusercontent.com/27329423/80964021-68608b80-8e10-11ea-90b6-785f44f64087.png)

**Comment by Jummit** [comment]
I can't reproduce this either.

**Comment by Error7Studios** [comment]
> Your syntax seems wrong, I had no problem doing drag-and-drop with this.

I tried this with several different kinds of syntax, all with the same result.

However, I discovered that dragging from the _**FileSystem dock**_ works, but dragging from the _**script dock**_ doesn't work.
![DragDropBugReason](https://user-images.githubusercontent.com/60025044/80968730-143cb380-8dde-11ea-8d00-0a3387d5cad6.png)

> Seems like a bug tbh.

I've opened a bug report here:
https://github.com/godotengine/godot/issues/38456

Closing, since this currently works when dragging from the FileSystem dock, and a bug report has already been opened.

Thanks.
