### ISSUE TITLE
Add support for importing non-scene meshes with formats other than Wavefront OBJ

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot-proposals#797]
**Describe the project you are working on:**
Not a specific project. I'm just tinkering with 3D and VR stuff.

**Describe the problem or limitation you are having in your project:**
I can't import a mesh with a second UV, since Wavefront only stores one UV, and is the only available format for mesh import. Right now I am obliged to work around the limitation by opening my glTF mesh as a scene, saving the Mesh resource of the MeshInstance in the scene as .mesh, then importing it in my scene.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Mesh import for formats other than Wavefront should be available. The workflow of making the scene in a DCC then importing it into Godot isn't always suitable, such as when using a GridMap in the scene, which is a Godot-specific object.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It will probably use the same importers already available in core for scene import, but instead import into a mesh resource in the same way the Wavefront importer works.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not in a way that I know of, at least.

**Is there a reason why this should be core and not an add-on in the asset library?:**
As far as I understand, importing meshes is a core functionality, and since scene import with other formats is already possible in core, it should be possible to add mesh import with those formats.

**Comment by fire** [comment]
An obj is stored as a single mesh, but modern scene formats store a mesh per node so you'll need to find a way to combine materials.
 
People don't expect that an import as mesh will spend 2-10 minutes churning to combine materials.

If we wanted to add this, it'll be under a section like make LOD, HLOD or merge scenes.

**Comment by fire** [comment]
That said, you can go to each mesh instance or similar and save the mesh to the file system. There's even a import preset for this.

**Comment by Tooniis** [comment]
> An obj is stored as a single mesh, but modern scene formats store a mesh per node so you'll need to find a way to combine materials.
> 
> People don't expect that an import as mesh will spend 2-10 minutes churning to combine materials.
> 
> If we wanted to add this, it'll be under a section like make LOD, HLOD or merge scenes.

How about making it a requirement for mesh import to have one node in the file?

**Comment by Tooniis** [comment]
Alternatively, maybe just make it possible to import a scene into an existing scene, so it just inserts new MeshInstances into the existing scene.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1632, which is more detailed and has gathered more discussion.
