### ISSUE TITLE
Add a `distance_to()` method to Vector2i

### ISSUE THREAD

**Issue by TheKassaK** [godotengine/godot-proposals#7983]
### Describe the project you are working on

A 2D colony simulation game, with a tilemap and a lots of calculation everywhere

### Describe the problem or limitation you are having in your project

There is no equivalent of Vector2.DistanceTo for Vector2I

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a Vector2I.DistanceTo() function, this function return a float => number of tiles between each position

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The code I use : 

```
        public static float DistanceTo(Vector2I from, Vector2I to)
        {
            float dx = to.X - from.X;
            float dy = to.Y - from.Y;

            float distance = Mathf.Sqrt(dx * dx + dy * dy);

            return distance;
        }
        
        GD.Print(Utils.DistanceTo(new Vector2I(1, 1), new Vector2I(5, 5))); // = 5,656854
        GD.Print(Utils.DistanceTo(new Vector2I(5,5), new Vector2I(1,1))); // = 5,656854
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, see my code above

### Is there a reason why this should be core and not an add-on in the asset library?

Because its a basic function when we use 2D grid (I guess)

**Comment by dalexeev** [comment]
Perhaps other metrics than Euclidean may be useful for `Vector2i` (see `AStarGrid2D`)?

**Comment by TheKassaK** [comment]
Yes, for my project I dont need more than Euclidean, but it seems to me a good idea to let the possibility of choosing the calculation method

**Comment by kleonc** [comment]
This proposal is a subset of #2297.


> Perhaps other metrics than Euclidean may be useful for `Vector2i` (see `AStarGrid2D`)?

I think other metrics are too use case specific for them to be included in vectors (whether as separate method(s) or as argument of `distance_to`/`distance_squared_to`). Note that such metrics are not limited to integers, they can be used with reals just fine. However, currently in `Vector2/3/4` there are only `distance_to`/`distance_squared_to` methods calculating the Euclidean distance. So if support for other metrics were to be added then it would make sense to do so for all vectors (both real and integer). But again, I'm against as this doesn't seem like a common/general enough use case.
And if that's needed/desired specifically for `AStarGrid2D` then probably some method could be added to `AStarGrid2D`.

---

Regarding the proposal, adding only `Vector2i.distance_to` would make things inconsistent. But adding both `distance_to` and `distance_squared_to` to all integer vectors (`Vector2i/3i/4i`) does make sense, it's a part of #2297 which shouldn't be anyhow controversial (like the `length`/`length_squared` case).
