### ISSUE TITLE
Add shortcut keyboard triggers to PopupMenu items

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-proposals#7988]
### Describe the project you are working on

And editor app with a menubar using the MenuBar and PopupMenus 

### Describe the problem or limitation you are having in your project

Using the MenuBar node I can now create top menus (like File and Edit) and even get this to work as the application top menu bar in macOS. However, there seems to be no way to add keyboard shortcuts for these menu items, as it common for this type of menu. Like add a Ctrl-S shortcut to trigger the Save menu item etc. This means the user has to select menu items using the mouse, and if you implement keyboard shortcuts in a different way this is not visible to the user in the menu item.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Buttons have a Shortcut property that you can map input to trigger the same action as pressing the button. I'd propose adding a similar property to PopupMenu items, so that you can configure a Shortcut that will trigger the same action as the selection of this item. 

Possibly the assigned shortcut can also optionally be displayed to the right in the item GUI representation (this is automatic for keyboard shortcuts assigned to macOS top menu menuitems) to show there is a keyboard shortcut for this item. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above

Mostly the shortcut code for Button could probably be reused here. This could be implemented as just another property on the current PopupMenu Items array objects, or as a new property of separated MenuItem child nodes as proposed in https://github.com/godotengine/godot-proposals/issues/7987 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not elegantly. You can detect keyboard shortcuts in different ways, but it will require a little work to highlight the menu and make sure it only works when the corresponding menu item is enabled etc.

### Is there a reason why this should be core and not an add-on in the asset library?

I think it's a core functionality of menu items to be able to have keyboard shortcuts.

**Comment by AThousandShips** [comment]
Both `MenuBar` and `PopupMenu` accept shortcuts? What is the functionality you lack?

**Comment by lostminds** [comment]
> Both `MenuBar` and `PopupMenu` accept shortcuts? What is the functionality you lack?

I'm not able to find a shortcut setting on either of them. Only a shortcut context on MenuBar as it's a Control subclass. But even if this is supported and I've missed it what I'm proposing here is shortcut support set for selecting individual items in the menu. Like triggering the selection of the "Save" item in the "File" menu, not for triggering the opening of the "File" menu.

**Comment by AThousandShips** [comment]
You need to use script to assign it, see [here](https://docs.godotengine.org/en/stable/classes/class_popupmenu.html#class-popupmenu-method-set-item-shortcut)

**Comment by lostminds** [comment]
I see, thank you. Indeed it seems you can assign command shortcuts using code, even if they are not applied to the converted macOS menu bar items they do display (with a "(Unicode)" addition) in godot menus and seem to work (the scaling is a separate issue).
![Screenshot 2023-10-05 at 13 02 05](https://github.com/godotengine/godot-proposals/assets/17763524/e8afab15-c5e9-4399-b6a8-a3cba8203c5b)

![Screenshot 2023-10-05 at 12 56 26](https://github.com/godotengine/godot-proposals/assets/17763524/0246e4d7-8e54-4d0e-b7c6-32d01d702490)

So I guess you could rephrase this proposal to expose these settings in the editor for the items to make this easier to work with and set up without script, and apply the shortcut settings to the macOS generated menus as well.

**Comment by AThousandShips** [comment]
Do they appear if you instead use `fileMenu.set_item_shortcut(0, openShortcut, true)`?

**Comment by lostminds** [comment]
> Do they appear if you instead use `fileMenu.set_item_shortcut(0, openShortcut, true)`?

No. The global flag makes no difference in the macOS menu case.

It seems however that something is still listening for the shortcut input events though, as the corresponding menu item selection is triggered. It's just done separately somewhere instead of being properly set on the macOS NSMenuItem, so the menu item doesn't display the shortcut key and isn't highlighted as it should when the shortcut is triggered.

**Comment by AThousandShips** [comment]
That sounds like a bug, please open a report for that part

Otherwise the functionality exists, the one thing would be to add it to the inspector, which this proposal could be rewritten to cover, otherwise there's no missing functionality here

**Comment by lostminds** [comment]
Ok, thanks for the help @AThousandShips , I've opened a bug report for the missing shortcuts in the macOS menu items instead: https://github.com/godotengine/godot/issues/82854
