### ISSUE TITLE
Add a tag layer system to AnimationTree StateMachine

### ISSUE THREAD

**Issue by elXill** [godotengine/godot-proposals#7989]
### Describe the project you are working on

3d character controller experiment.

### Describe the problem or limitation you are having in your project

So far all AnimationsTree/StateMachine solutions I have seen; while easy to follow and work with at start, they become quickly convoluted and crowded. AnimationTree AnimationNodeStateMachine is also very hard to work with and read when using more than a few animations. The below is only for a 4 way moving system; which I am glad with the animation system but it is hard too find mistakes and read. While other people use different aproaches this is inevitable with more than few animation..

![stateMach](https://github.com/godotengine/godot-proposals/assets/61533529/9cb4d3ed-0c6f-480d-a126-c88eae69c838)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A tag a system works similar to layers (or layers but being able to add a lot of tags, opening and closing them in combinations would be better i think..), you can select which nodes you want to see and see only selected nodes and their transitions. Just like as if other nodes are deleted. Even a simple hide function would make worlds of difference in readability... 

Bonus points if tags can be reached with scripts and be used for other purposes; sorting animation states, etc.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Tags become a bool in AnimationNodeStateMachine as a tag shelf, and you can check un-check depending on what you want to work with like below;

![1](https://github.com/godotengine/godot-proposals/assets/61533529/798c56b2-6b5f-46dd-9ebd-76e1c0bb7e37)
![2](https://github.com/godotengine/godot-proposals/assets/61533529/9892a15f-f33b-49fe-9295-708cd8b7cc79)
![3](https://github.com/godotengine/godot-proposals/assets/61533529/29d2a838-2b61-45b6-aa56-668bf443d2d2)
![4](https://github.com/godotengine/godot-proposals/assets/61533529/1cb38e3d-b8a5-4d21-9f31-3285b7776061)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm aware that this can be avoided to some extent by using Sub-StateMachines but they have their own limitations ex; not being able to connect an outside state directly if you want to quit sub-Mach with multiple parameters you can't do that. Also they add another layer of unneeded complexity, and paramaters gets duplicated for each state.

### Is there a reason why this should be core and not an add-on in the asset library?

This can be an addon but I think it would be a general betterment, while layers or tags are a concept often used in other areas, I think animation tree would benefit from it greatly. Also I haven't seen this feature in any other engine/system this can differentiate Godot from other engines/systems.
```[tasklist]
### Tasks
```

**Comment by Zireael07** [comment]
Your fork hasn't been merged into master, why close?

**Comment by elXill** [comment]
I wasn't aware of that, I guess I just misclicked.

**Comment by AThousandShips** [comment]
It's because you're on your `master` branch and linked this proposal, that'll automatically close it

**Comment by elXill** [comment]
I did 
git rebase -i upstream master and git push --force , to rebase, did I mess that up again?

**Comment by AThousandShips** [comment]
Not sure but it's one of those strange quirks of GitHub, I'd suggest removing the "fixes" part from the commit message to make sure this doesn't get randomly closed, the PR itself will handle that part when that gets merged
