### ISSUE TITLE
Godot 3.2.2 Android Plugin (v1) - package naming, GodotIO public access

### ISSUE THREAD

**Issue by yalcin-ata** [godotengine/godot-proposals#799]
(I am opening an issue here, because it is not a bug and actually also not a feature request. I am sure the Android plugin Godot developers (@m4gr3d ?) can point me to the right direction.)

**Describe the project you are working on:**
I am porting Android plugin for Firebase for Godot 3.2 (https://github.com/yalcin-ata/godot-android-module-firebase) to the new Android plugin system (v1) for Godot 3.2.2 (Beta 1).

**Describe the problem or limitation you are having in your project:**
With the new plugin system (v1) for Godot 3.2.2 (Beta 1) we can develop Android plugins with a custom package name. Before it was org.godotengine.godot, and we could set the applicationId in the gradle.conf file (which I still can in the build.gradle). Now I have a problem:

- when I keep the plugin's package name as before (org.godotengine.godot) gradle fails to build at task "processDebugGoogleServices" (it parses google-services.json which was downloaded from the Firebase console for my project, where the package name is the project's own package name, let's say com.project.game)
- when I change the plugin's package name (to com.project.game) the plugin builds the aar file and everything works, except:
  - for a Firebase service (Storage) I used in one of the the plugin's classes (Storage) the GodotIO class, whose constructor is package-private. To let gradle build the plugin I had to remove this class.

Are there plans to further improve the Android plugin (v1)? Am I doing something wrong (package naming maybe)? Will GodotIO's constructor get a public access?

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This is not a feature request.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
No code to provide.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It probably can be worked around.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is not a feature request, it's a question / help request to the Android plugin Godot developers.

**Comment by m4gr3d** [comment]
@yalcin-ata There's an [available public instance](https://github.com/godotengine/godot/blob/7b56111c297f24304eb911fe75082d8cdc3d4141/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L252) of `GodotIO` in the `Godot.java` class, and each plugin has access to a `Godot` object, so you can use that `Godot` object to access the `Godot.io` instance.

**Comment by yalcin-ata** [comment]
Thank you, that helped a lot.

For further questions: should I ask in this ticket, open another issue or is there any other platform?

I am sure there will come up more questions (like: will the [documentation](https://docs.godotengine.org/en/3.2/tutorials/plugins/android/android_plugin.html) be updated, what about different package names for the plugin and for the Godot project (when exporting), etc. ...)

**Comment by m4gr3d** [comment]
> Thank you, that helped a lot.
> 
> For further questions: should I ask in this ticket, open another issue or is there any other platform?
> 
> I am sure there will come up more questions (like: will the [documentation](https://docs.godotengine.org/en/3.2/tutorials/plugins/android/android_plugin.html) be updated, what about different package names for the plugin and for the Godot project (when exporting), etc. ...)

@yalcin-ata feel free to open another issue for further questions and inquiries.

Now that the [plugin system latest update](https://github.com/godotengine/godot/pull/38175) has been merged, the documentation will be updated accordingly to describe the updated process.

**Comment by yalcin-ata** [comment]
Thank you very much!
