### ISSUE TITLE
Create a `.force_physics_step(steps: int, delta: float)` method to the PhysicsServer2D and PhysicsServer3D

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot-proposals#7998]
### Describe the project you are working on

Roblox emulator, whole roblox runtime inside godot 4.2+

### Describe the problem or limitation you are having in your project

Having to adhere to a whole task scheduler system that godot is quite different from
![image](https://github.com/godotengine/godot-proposals/assets/69520693/79f84e0b-eef1-4bd2-aa17-3fe019ef0f11)
(All of the issues here could be solved by waiting for them or triggering them manually)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature would allow programmers to trigger physics steps arbitrarily for example while `set_active` is false.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
extends Node
func _ready(): PhysicsServer3D.set_active(false)
func _force_step(start: float):
    var delta := Time.get_ticks_msec()/1000.0-start
    PhysicsServer3D.force_step(delta,4)
func _process(delta: float):
    # Force the engine to run physics 3D after _process
    _force_step.call_deferred(Time.get_ticks_msec()/1000.0-delta)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

There may be more use cases, for example moving the order of when to do physics step, maybe forcing it before rendering, or forcing physics to be synchronous to the step currently done.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2821.
