### ISSUE TITLE
Allow @exported Arrays to set property hints for its elements

### ISSUE THREAD

**Issue by AbelToy** [godotengine/godot-proposals#8005]
### Describe the project you are working on

A top-down 3D game with turrets which use multiple lasers

### Describe the problem or limitation you are having in your project

I want to be able to customize the lasers' angular offsets using an Array of floats.
Since these are angles, I want to use `@export_range(-360f, 360f, 0.001f, "radians")` for each Array element.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Being able to set property hints for Arrays would allow me to use `@export_range` for the Array's elements.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The following export annotations should work on typed Arrays if they would work on the Array's elements.
For instance, `@export_range` should work on an Array if it's an `Array[float]` or `Array[int]`.
Additionally, they should also work for their respective packed array.

- `@export_file` / `@export_dir` / `@export_global_file` / `@export_global_dir` / `@export_multiline`: for Array[string] / PackedStringArray
- `@export_range`: for Array[float] / Array[int] / PackedInt32/64Array / PackedFloat32/64Array
- `@export_exp_easing`: for Array[float] / PackedFloat32/64Array
- `@export_color_no_alpha`: for Array[Color] / PackedColorArray
- `@export_node_path`: for Array[NodePath]
- `@export_flags` and `@export_flags_***`: for Array[int] / PackedInt32/64Array
- `@export_enum`: for Array[int] / PackedInt32/64Array / Array[String] / PackedStringArray

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I work around this by using _get_property_list() and related properties and emulating an array by actually defining multiple properties as prefix_i where i is the index of the array. It's not... pretty, and it's definitely convoluted, so official support for this would definitely be appreciated.

### Is there a reason why this should be core and not an add-on in the asset library?

It involves the GDScript parser and other engine parts that can't easily be modified with an add-on.

**Comment by dalexeev** [comment]
> * `@export_enum`: for Array[int] / PackedInt32/64Array / Array[String] / PackedStringArray

* See godotengine/godot#72951.

**Comment by AbelToy** [comment]
@dalexeev Oh nice!! If everyone’s OK with it I might use your PR as reference for implementing the other exports.

**Comment by dalexeev** [comment]
I meant that this is a valid proposal, we already have a precedent with `@export_multiline` and proposal and PR for `@export_enum`. I plan to generalize my PR later (after the 4.2 release) to implement this proposal.
