### ISSUE TITLE
An offer for separate downloads of build files

### ISSUE THREAD

**Issue by frkntlr** [godotengine/godot-proposals#8013]
### Describe the project you are working on

Content made using all types of godot

### Describe the problem or limitation you are having in your project

Although we upload smaller build files compared to other engines, by downloading the entire package we download a file of approximately 1 GB in size. This wastes a certain amount of time to test rapid prototypes. Of course, it can give really long download times for people with much more limited internet speed. Although the speeds are not that slow worldwide, there may be problems in some places.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Download sizes will decrease and people who will never develop projects on mobile, PC and web will not need to download extra files. It will save time for someone who has low internet speed and needs to export in a hurry.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It can be selected via the drop-down menu, which is the drop-down checklist. Example;

- All Platforms
- mobile
-- Android
--    iOS
--    Others
- web
- pc
--    Windows 32 64
--    Linux 32 64
--    Mac 32 64

Likewise, we can see what is loaded in a drop-down menu.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not a software developer, I don't know. I don't think it is necessary to write very long code.

### Is there a reason why this should be core and not an add-on in the asset library?

There is a section called Export Template Manager in Godot. It would be better to edit this place. It is not right to set it as a plugin and include it in the project. It's not practical. .

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/647.
