### ISSUE TITLE
Give editor nodes descriptive names

### ISSUE THREAD

**Issue by GuyUnger** [godotengine/godot-proposals#8023]
### Describe the project you are working on

addons

### Describe the problem or limitation you are having in your project

Accessing parts of the editor interface is barely useable, I see many addons doing things like:
```
var scripts_panel: Control = get_editor_interface().get_script_editor().get_child(0).get_child(1).get_child(0)
if scripts_panel.visible:
	EditorInterface.get_script_editor().get_child(0).get_child(0).get_child(0).get_popup().emit_signal("id_pressed", 14)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Give all editor nodes useful names, then there can be a cheat sheet online to find all the names.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not sure about the best practice method for accessing the nodes. `get_tree().root.find_child("NodenName", true, false)` isn't the most pretty, using unique names `get_tree().root.get_node("%NodeName")` could already be better, but I'm not sure if this works inside the editor?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

NA

### Is there a reason why this should be core and not an add-on in the asset library?

NA

**Comment by AThousandShips** [comment]
Them doing that is largely to try to gain access to things that aren't supposed to be exposed in the first place, because they are internal

**Comment by GuyUnger** [comment]
> Them doing that is largely to try to gain access to things that aren't supposed to be exposed in the first place, because they are internal

Addons can be much better with them exposed, there's no good reason to keep them locked away imo

**Comment by AThousandShips** [comment]
> there's no good reason to keep them locked away imo

I mean, there often is, can you give me some examples of cases where they should be exposed?

**Comment by passivestar** [comment]
One of the major pain points when doing editor scripting for Unity was the fact that there were a lot of cool stuff hidden behind internal methods, and the only way to access them was to use reflection. This proposal seems like a great opportunity for godot to be much cooler than unity and be more open to editor customization. I'd love to have better access to editor ui

**Comment by AThousandShips** [comment]
So here's the primary reason to keep editor internals internal:
It frees development up to change things

If everything is exposed you can't change anything without breaking compatibility, that's why you use restricted ways to provide access, not freely allow people to easily access the internals, because then you're stuck in one very particular setup long term

**Comment by passivestar** [comment]
I'd prefer it to break compatibility with my addons than not to give me a way to make addons at all 🤷

**Comment by AThousandShips** [comment]
I mean that's fine that you think that, but most people don't like to have to rewrite their code every so often because something changed, and we won't break compatibility except when absolutely necessary

**Comment by AThousandShips** [comment]
My question still stands though, what are some examples of cases where direct access is required and what are the reasons for accessing those, because chances are there are better ways to access it

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1018.
