### ISSUE TITLE
Accept uid://* paths in preload()

### ISSUE THREAD

**Issue by fabiosantoscode** [godotengine/godot-proposals#8035]
### Describe the project you are working on

An early stage 2D game prototype where I'm renaming and moving files around a lot as I tweak and add/remove game mechanics

### Describe the problem or limitation you are having in your project

When moving scene files I have to perform a global find for that scene file to look for preload() calls referring to it. This isn't a major problem but it's cumbersome to do.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like to be able to use an `uid://` path in preload(). This would enable me to stop worrying about file paths as much.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Right now this works:

`var xyz_scene = preload("res://path/to/scene_xyz.tscn") # Scene that does xyz`

This should work as well:

`var xyz_scene = preload("uid://tf8o633f5640") # Scene that does xyz`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am not aware that a workaround exists, but I'm very new to godot and would love to be proven wrong!

### Is there a reason why this should be core and not an add-on in the asset library?

preload() is a core language feature that kicks in at parse time, so I believe it has to be core.

**Comment by KoBeWi** [comment]
It does work though
![image](https://github.com/godotengine/godot-proposals/assets/2223172/eed19b68-5d14-4ae8-945a-346be53ae89d)
This is in 4.2

**Comment by fabiosantoscode** [comment]
I've downloaded 4.2 alpha 6 and looked into it deeper.

I can confirm that I can print() the preloaded scene.

But I can't instantiate or switch to it.

For comparison, I've modified one of my functions that was using preload():

![image](https://github.com/godotengine/godot-proposals/assets/1611595/87ae147b-8824-4047-9544-273368b7799a)

This prints my scene, the instance, and switches to the scene

![image](https://github.com/godotengine/godot-proposals/assets/1611595/3d532ebf-0a26-495d-942f-8328aa559551)

However, using uid://:

![image](https://github.com/godotengine/godot-proposals/assets/1611595/39074a89-ab4b-4578-9089-fc331ac83f24)

Prints the scene but `.instantiate()` returns null and causes some errors:

![image](https://github.com/godotengine/godot-proposals/assets/1611595/1ef0b26e-e9a8-4e98-ba9b-e3b5003135d1)

![image](https://github.com/godotengine/godot-proposals/assets/1611595/5d3202d3-0102-46bb-b189-caf4eac008b0)


So maybe this should be reposted as an issue on the main repo?

**Comment by KoBeWi** [comment]
It's a bug with instantiating scenes and already reported: https://github.com/godotengine/godot/issues/82701
Closing.
