### ISSUE TITLE
GDScript code formatting

### ISSUE THREAD

**Issue by ImRains** [godotengine/godot-proposals#8039]
### Describe the project you are working on

Can GDScript code formatting function codes be added to Godot? The inability to format the code has been very frustrating for me, which has made me spend time organizing the code.

### Describe the problem or limitation you are having in your project

.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

.

### Is there a reason why this should be core and not an add-on in the asset library?

.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/3630.
