### ISSUE TITLE
@export_category() does not throw an error when hiding Singletons

### ISSUE THREAD

**Issue by staticrainstudios** [godotengine/godot-proposals#8041]
### Describe the project you are working on

I am working on a 2D open-world RPG-ish game where there's a lot of complicated systems for things such as inventory items, stats, etc.

### Describe the problem or limitation you are having in your project

I just spent forever trying to figure out an error I kept getting, I was trying to reference my Stats singleton, but it kept saying that Stats was nil. I checked all the variables, every number was correct, but every time I tried to access Stats for some reason it wasn't letting me access it as it was returning nil.
![image](https://github.com/godotengine/godot-proposals/assets/147348360/12e37771-66f1-4068-83f8-b31db0ee0a6e)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The problem was that I had a category called @export_category("Stats") which hides the global Singleton, this SHOULD throw an error to be consistent with class_name Stats throwing an error.
![image](https://github.com/godotengine/godot-proposals/assets/147348360/b7a14a13-a11b-40db-80bc-7e0e1aaa993b)

Also, when I would control click on Stats in the next picture, it would bring me to Stats... unless I clicked on Stats on the right, in which case the title on the window's handle would flash something I couldn't see, and do nothing else. If I clicked on ID or Level however, it would bring me right to my Stats script (even though it shouldn't be doing that, as it is referencing the category)
![image](https://github.com/godotengine/godot-proposals/assets/147348360/5260c856-b7cb-464a-9213-5cd20e125a8e)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/147348360/697bf652-50df-41dd-86e3-59181f5d3286)
Check out beautiful figure B below for a simple and elegant solution.
![image](https://github.com/godotengine/godot-proposals/assets/147348360/7249208e-cfce-43b2-a1e6-1bea531b3334)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by just straight up not doing it, but I would almost even classify this as a bug with how it completely wastes your time chasing ghosts.

### Is there a reason why this should be core and not an add-on in the asset library?

This should be in the core engine because it's a missing error message. I'm starting to think this isn't the right place to be suggesting this, but it's _technically_ not a bug, just a missing feature.

**Comment by dalexeev** [comment]
* This was a bug that fixed by godotengine/godot#78254.

Thanks for the contribution nonetheless!
