### ISSUE TITLE
Let us end an inner class' definition with "pass"

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot-proposals#806]
**Describe the project you are working on:**
2.5d beat'em up

**Describe the problem or limitation you are having in your project:**
I guess this is neither a real problem nor a real improvement, but i(and i bet many others) am used to "close" loops, functions and classes with brackets or whatever way the language lets me do it, this way the code looks cleaner with more separation etc and reduces the possibilities of errors.
In the case of gdscript i can use "pass" for everything... except for inner classes.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I just want to be able to close the inner class with "pass". I know it may sound something little, stupid and unecessary, but it's one of those little things that makes things a little better for some people like me.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Write "pass" at the end of the definition of a inner class

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, i could use some other kind of separation like a line of comments but that wouldn't prevent errors due to wrong indentation.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's core.

**Comment by ThakeeNathees** [comment]
already implemented in master: https://github.com/godotengine/godot/pull/36767

**Comment by Calinou** [comment]
I'll close this as this is more of a bug than a missing feature; see @ThakeeNathees' comment above.
