### ISSUE TITLE
Import glb and gltf single meshes as root node

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#8069]
### Describe the project you are working on

Walking simulator.

### Describe the problem or limitation you are having in your project

When importing a *.glb or *.gltf, even there is a single mesh node, the root is still a Node3D, it would be more convenient if it were auto-detected as a single mesh and imported as the root.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would make it easier to drag a glb or gltf directly into a MeshInstance3D mesharray without having to manually extract the node (either via copy/paste, new instance or extract during import).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An option to import a glb or gltf that has only a single mesh as the root imported node with a parent Node3D.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be import code.

### Is there a reason why this should be core and not an add-on in the asset library?

It would be import code.

**Comment by Calinou** [comment]
Unfortunately, this also has a downside. If the structure of the glTF changes later on, the node structure has to be changed in a breaking way.

The current structure imposes some indirection, but it means the root node's type will *never* change unless you explicitly change it yourself in the Import dock.

**Comment by aaronfranke** [comment]
@elvisish I'm planning on working on similar functionality in the near future (next few months). I already opened a proposal here: https://github.com/godotengine/godot-proposals/issues/7494

My plan is to implement importing as a mesh resource instead of a mesh node, like you can already do with OBJ in Godot, but this is similar enough that I am closing this as a duplicate. If in the future after that proposal is implemented we decide importing as a scene with a single mesh node is useful functionality, we can do that.

**Comment by elvisish** [comment]
> @elvisish I'm planning on working on similar functionality in the near future (next few months). I already opened a proposal here: https://github.com/godotengine/godot-proposals/issues/7494 and I opened this PR as a small prerequisite cleanup https://github.com/godotengine/godot/pull/82988
> 
> 
> 
> My plan is to implement importing as a mesh resource instead of a mesh node, like you can already do with OBJ in Godot, but this is similar enough that I am closing this as a duplicate. If in the future after that proposal is implemented we decide importing as a scene with a single mesh node is useful functionality, we can do that.

Tbh, that sounds even better than what I proposed, a mesh resource to just drag into a meshinstance3d node. @Calinou sighested any changes to hierarchy (adding multiple meshes) would break if there was no root, could it work having Godot auto merge the meshes into a single mesh resource if more are added?

**Comment by xne** [comment]
Anyone looking to do this while #7494 is worked on can use this import script:
```gdscript
@tool
extends EditorScenePostImport

func _post_import(scene: Node) -> Object:
	return scene.get_child(0)
```

**Comment by CsloudX** [comment]
> Anyone looking to do this while [#7494](https://github.com/godotengine/godot-proposals/issues/7494) is worked on can use this import script:
> 
> @tool
> extends EditorScenePostImport
> 
> func _post_import(scene: Node) -> Object:
> 	return scene.get_child(0)

I'm test this in 4.5.1.stable, it not work and report error:

<img width="809" height="86" alt="Image" src="https://github.com/user-attachments/assets/13082e0b-95b9-4e4d-8be3-ad1d6051f729" />
who can help me?

**Comment by elvisish** [comment]
> Anyone looking to do this while [#7494](https://github.com/godotengine/godot-proposals/issues/7494) is worked on can use this import script:
> 
> @tool
> extends EditorScenePostImport
> 
> func _post_import(scene: Node) -> Object:
> 	return scene.get_child(0)

Unfortunately this gives an error:
```
  ERROR: Can't add child 'casing_metallic_root_unique' to '@SubViewport@765604', already has a parent 'casing'.
  ERROR: scene/main/node.cpp:1739 - Condition "p_child->data.parent != this" is true.

```
