### ISSUE TITLE
Object proxies (getters/setters with property key parameter)

### ISSUE THREAD

**Issue by liana-p** [godotengine/godot-proposals#8072]
### Describe the project you are working on

I want to create a simple library to create automatically reactive data stores in Godot which UI can then bind to.

The idea is the data store class takes a state as its parameter, and creates a proxy for the state object. Then, when any code tries to get/set a property within this object, the getter/setter are called with the property name/key as a parameter.

Using this proxy structure, said UI plugin could automatically update the UI whenever properties are set, in a way that is seamless for the user writing GDScript.

### Describe the problem or limitation you are having in your project

Right now getters and setters are static, they need to be created per variable. There is no way to dynamically generate getters and setters for arbitrary properties.

This limitation makes it impossible to have a proxy pattern where a variable can intercept get/set access to its properties and run custom logic.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

What I'm talking about is effectively a similar idea to [JavaScript proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

This could enable a lot of new patterns, but in my case the goal is to use proxies as a way to automatically update dependencies to add reactivity to Godot UI in a way that's seamless from a scripting point of view.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For example, I could do something like this:

```gdscript
var actual_data = "hello world"
var my_prop:
	get = get_my_prop, set = set_my_prop

func get_my_prop():
  return actual_data

func set_my_prop(newValue)
  actual_data = newValue
  // pseudo code to propagate the update to dependents
  ReactiveUI.update(self, 'my_prop', newValue)
```

But every getter/setter would have to be manually created. Now imagine something like this:

```gdscript
class_name Reactive: get = get_prop, set = set_prop

var actual_data

func _init(data):
  self.actual_data = data

func get_prop(propertyName):
  return self.actual_data[propertyName]

func set_prop(propertyName, newValue):
  self.actual_data[propertyName] = newValue
  ReactiveUI.update(self, propertyName, newValue);
```

Or to apply the same thing to dictionaries, and with a more concrete usage example of proxies:

```gdscript
# Imagine this is the player node
extends Node2D
var playerState = {
  'health': 50,
  'stats': {
    'str': 5,
    'def': 5
  },
  'name': 'Some name'
}: proxy = player_state_proxy;

var health_label: Label
var player_state_proxy = new Proxy('get_player_state', 'set_player_state');

func get_player_state(propertyName):
  if (propertyName == 'description'):
    # We can 'generate' properties on the fly
    return playerState.name + " has " + playerState.health " health.";
  return playerState[propertyName];

func set_player_state(propertyName, newValue):
  playerState[propertyName] = newValue
  if (propertyName == 'health'):
    health_label.text = newValue + ' HP';
```

```gdscript
extends Node2D
# Some node where gameplay happens

# Calling this will also automatically update the UI
func damage_player(playerState, amount):
  playerState.health -= amount;
```

With a little framework around this to automate binding with UI element properties, and to cache computed properties like that `description` example, it's possible to automate a lot of things in a seamless way.

A system like this allows reactivity on any properties, and could be nested deeply by iterating on properties and converting children that are objects to reactive objects too.

Ideally it would be good if this worked both for dictionaries and arrays (or just arbitrary objects, which in the case of GDScript would be class instances I believe? I couldn't find any generic "object" type in GDScript that can have arbitrary props, other than dictionaries).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't think of any way of doing this without proxies. The alternatives are:

* Users create getters/setters manually for all props, which defeats the purpose
* Manually creating set/get functions on the reactive class which do what the proxy would do. This works, but isn't seamless to use as now users would have to use `myState.get('someKey')` instead of being able to just do `myState.someKey`

### Is there a reason why this should be core and not an add-on in the asset library?

I want to make this as an add-on, but I believe there is no way to achieve this result without some `Proxy` feature or equivalent in GDScript.

Otherwise, it can only be mimicked with either clunky syntax, or lots of repetitive setup code for each property.

I'd be interested in implementing it, but have no idea in which area to look or how doable it is, as I have 0 knowledge of the Godot codebase.

**Comment by theraot** [comment]
> Right now getters and setters are static, they need to be created per variable. There is no way to dynamically generate getters and setters for arbitrary properties.

Does [`_get`](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-get) and [`_set`](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-set) not fulfill this role for you?

**Comment by liana-p** [comment]
> Does [`_get`](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-get) and [`_set`](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-set) not fulfill this role for you?

Oh it does, I was looking for exactly this but couldn't find anything else than the static get/set. Thanks
