### ISSUE TITLE
DLSS 2.0 support

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot-proposals#808]
A game running 1080p or 720p very smoothly could be upscaled to 4K and keep the same details, and get better anti aliasing without the disadvantages of TAA.

https://www.youtube.com/watch?v=RmSgJ3LJkvQ

**Comment by bojidar-bg** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:

**Comment by pycbouh** [comment]
See #2239.
