### ISSUE TITLE
Implement PackedStringNameArray for array of StringNames

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#8081]
### Describe the project you are working on

Casual Game in 4.2

### Describe the problem or limitation you are having in your project

Currently you cannot create a Packed array of StringNames optimized for StringNames.
Since `StringName`s are faster and better in search and compare against `String`s. It makes sense to have first class support for it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement `PackedStringNameArray` optimized for search and comparision of `StringName`s

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It should be similar to `PackedInt64Array`, if I understand the implementation correctly. 
The performance gain will not be similar to Int but at-least close to it.
Check the test below:

### If this enhancement will not be used often, can it be worked around with a few lines of script?

StringName is exposed in 4.0 onwards, it needs first class support to get used more often.
I am creating an Array of StringNames like this,

```gdscript
var str_array :Array[StringName] = []
# or 
var str_array :Array[StringName]
```
but when you `push_back()` it takes the parameter as `Variant`. It does not give confidence.
I did a quick perf test on the working project

**System:**

> Godot Engine v4.2.dev6.official.57a6813bb - https://godotengine.org
Vulkan API 1.3.242 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Ti
AMD Ryzen 7 5800X 8-Core Processor (3.80 GHz) - RAM (32.0 GB)

** Code:**
```gdscript
func perf_test_string_name_vs_int():
	const ITERATIONS = 100_000
	
	var str_name_array: Array[StringName] = []
	var int_array: Array[int] = []
	var packed_int_array: PackedInt64Array = PackedInt64Array()
	
	var start_time: int = 0
	var time_taken: int = 0
	
	print("# STRING NAME - ARRAY")
	start_time = Time.get_ticks_usec()
	#enumerate_children(str_array, self)
	for i in ITERATIONS:
		str_name_array.push_back(StringName("GameBoard%s" % i))
	time_taken = Time.get_ticks_usec() - start_time
	#print("Total number of Nodes: ", str_array.size()  )
	print("Time Taken(Creation): %s usec:" % time_taken )
	
	start_time = Time.get_ticks_usec()
	str_name_array.has(&"GameBoard56")
	time_taken = Time.get_ticks_usec() - start_time
	print("Time Taken(Search- Positive): %s usec:" % time_taken )
	
	start_time = Time.get_ticks_usec()
	str_name_array.has(&"Something")
	time_taken = Time.get_ticks_usec() - start_time
	print("Time Taken(Search- Negative): %s usec:" % time_taken )
	
	print("# INT - Array")
	
	start_time = Time.get_ticks_usec()
	for i in ITERATIONS:
		int_array.push_back(i)
	time_taken = Time.get_ticks_usec() - start_time
	print("Time Taken(Creation): %s usec:" % time_taken )
	
	start_time = Time.get_ticks_usec()
	int_array.has(100)
	time_taken = Time.get_ticks_usec() - start_time
	print("Time Taken(Search - Positive): %s usec:" % time_taken )
	
	start_time = Time.get_ticks_usec()
	int_array.has(-100)
	time_taken = Time.get_ticks_usec() - start_time
	print("Time Taken(Search - Negative): %s usec:" % time_taken )
	
	print("# PACKED Int Array")
	
	start_time = Time.get_ticks_usec()
	for i in ITERATIONS:
		packed_int_array.push_back(i)
	time_taken = Time.get_ticks_usec() - start_time
	print("Time Taken: %s usec:" % time_taken )
	
	start_time = Time.get_ticks_usec()
	packed_int_array.has(100)
	time_taken = Time.get_ticks_usec() - start_time
	print("Time Taken(Search - Positive): %s usec:" % time_taken )
	
	start_time = Time.get_ticks_usec()
	packed_int_array.has(-100)
	time_taken = Time.get_ticks_usec() - start_time
	print("Time Taken(Search - Negative): %s usec:" % time_taken )
```
**Result:**

![perf_string_name_vs_int](https://github.com/godotengine/godot-proposals/assets/84369217/ec678d57-1f7d-4b00-a5b7-44c4447bb3f2)

**Disclaimer:**
Performance test should be done in a clean system (no apps running), but in this case unable to do, so relative test results should be acceptable, with same apps running.

### Is there a reason why this should be core and not an add-on in the asset library?

It will be a core datatype

**Comment by AThousandShips** [comment]
The issue here is that adding new `Variant` types is a lot of work, and needs very good reason, I don't know that having a packed storage of `StringName` has that wide a need

Can you provide some use cases where you would need this data structure?

**Comment by tokengamedev** [comment]
> Can you provide some use cases where you would need this data structure?

In my current game, the game is designed to be played level wise. Each level is designed in the Godot Editor itself which consists of nodes of similar or derived type
For the level to be marked as complete, the nodes inside the level has to be tracked.
There may be around 100s of nodes may not be thousands.
There are multiple ways to do that, one of them is to track the name of the node or create integer id on the nodes to track.
Since name of the nodes are exposed as `StringName`, it can be used as unique identifier, less memory footprint as it is already stored and intuitive as you see the name in the editor itself.
I tested with StringName Array and it was working ok, as I broke down some of the logic of creation into multiple parts.

```gdscript
# sample logic for creating array of node names
func enumerate_children(arr_names:Array[StringName], arr_values: Dictionary, current_node: Node, is_recursive: bool = false ):
	for node in current_node.get_children():
		# Check for the interested base type
		if current_node is Piece:
			arr_names.push_back(node.name)
			# ...More stuff here like
			# arr_values[node.name] = {}
			if is_recursive:
				if node.get_child_count() > 0:
					enumerate_children(arr_names, arr_values, current_node, is_recursive)

```
I understand, there is lot of work involved and it may not get approved itself, but it made sense to me, so raised the proposal. It is a new concept compared to string what people think about Godot. I have not done a perf test on String vs StringName. May be I will do sometime and add here.

**Comment by Mickeon** [comment]
The code sample used for this test here may be flawed.

> ```gdscript
> 	#enumerate_children(str_array, self)
> 	for i in ITERATIONS:
> 		str_name_array.push_back(StringName("GameBoard%s" % i))
> 	time_taken = Time.get_ticks_usec() - start_time
> 	#print("Total number of Nodes: ", str_array.size()  )
> 	print("Time Taken(Creation): %s usec:" % time_taken )
> ```

The purpose of **StringName**s is that they are more memory efficient, because they can _point_ to the same **String**, instead of having potential duplicates in memory. For this to be even possible, to put it briefly, they're stored in such a way that makes creating completely new **StringNames** from a **String** slower than just using the **String** by itself.

As a result, I believe that creating completely new ones in a loop becomes exponentially slower.

**Comment by AThousandShips** [comment]
I understand your case, but I fail to see how it is absolutely needed to be done in this way

The thing is that "this would make my game more performant" is not necessarily an argument, the question is rather:
Would the average user, or sufficiently many users, be benefitted by this, as compared to the work and complexity

There are many things that could theoretically be made faster for specific cases or needs, but the question is if those cases are common or relevant enough

**Comment by Mickeon** [comment]
I'm not going to lie, there were occasions where I probably would've benefitted more if the already existing **PackedStringArray** was instead a **PackedStringNameArray**. The "copy-on-write" behavior of Strings cannot work sometimes because they are generated on the spot. As such, some code may end up assigning the same value to Strings while being different references. It bloats the memory footprint _a bit_ (if one were to obsessively think about it).
Regardless, I would only want to choose between one of the two types, not both. It's pretty confusing.

**Comment by tokengamedev** [comment]
> The purpose of StringNames is that they are more memory efficient, because they can point to the same String, instead of having potential duplicates in memory. For this to be even possible, to put it briefly, they're stored in such a way that makes creating completely new StringNames from a String slower than just using the String by itself.

First thing it is not actual code it is test code. It is the logic of creation of unique StringNames dynamically. In real practice you will not need it, rather you use it already created, like node name or others. or it will be more of hard coded literal.
Regarding, why slow in creation of string names, I found out, it was because of
```gdscript
"GameBoard%s" % i
```
I will publish the result of comparison with strings in the next comment.

Second, If StringName is supposed to save memory, then by how much? I believe it saves memory internally in the engine code, where the strings are repeated more than in game code,
In game code you can define a constant and use it everywhere. Then StringName memory saving is useless in my perspective. I personally don't use literals inside code except 0 even dictionaries.

> As a result, I believe that creating completely new ones in a loop becomes exponentially slower.

I expected it to be linearly slower and it shows in the result too, try by changing the number of iterations. If it was not the case i.e., exponentially slower, then it is a flawed implementation of StringNames. 

@AThousandShips, I am unable to present the code exactly from the game, as the code is split between design time (Level creation), and then during runtime (playing the game)
In design time you fetch the names of nodes and store in an array, and save it. The sample code I provided in the comment (not performance test code) is an example. 
In runtime you load the level, instantiate the array, then start all kinds of loop and search.
There is no edit in the StringNames from the list, which means adding, removing StringNames to/from the array. 
I understand creating StringNames is costly affair, so I keep it to design time.

**Additional Note:**
This proposal I created is based on two assumptions:
1. `StringName` is a reference to string stored in some internal dictionary or something. Comparing two `StringNames `will be similar(time) to (but not equal) to integer comparison vs String comparison.
2. `StringName` is different from `String` that it contents are unique in the perspective that it can be used as ids. Two StringNames with same values will be the same, unlike String

Hence the idea having an array of String Names is not that far as it is different kind of datatype. I have shared my use case, where I want to store the names of the nodes in an array and then loop through them.

There is another scenario I can think of is searching for a word in the english dictionary dynamically in a word game, but there are other means too like dictionary, 
Another option I think of is having set operations on the PackedStringNameArray a chance

**Comment by AThousandShips** [comment]
To clarify, I'm not asking "why would it be useful to have an array of `StringName`", I'm asking "why would it be useful to have `PackedStringNameArray`"

What *unique* problems does it solve? What does it make possible, or *significantly* easier?

Some details:
* `StringName` is reference counted, so only one "full" copy of the string is ever stored, though this depends in other ways on other details, but for the purposes of RAM only one copy of the actual text is stored, everything else stores a reference to that
* Creating `StringName` ahead of time saves processing in critical areas
* Comparing `StringName` is significantly faster as it compares pointers, not full strings

But none of this is really relevant for this, as this isn't about the usefulness of `StringName` but of `PackedStringNameArray`

**Comment by tokengamedev** [comment]
Updates with the String Name vs String Comparision result

Note: Following changes have been done with respect to Proposal performance test
1. Replaced `"GameBoard%s" % i` with `str(i)`
2. Replaced `Array[int]` with `Array[String]`
3. Replaced `PackedInt64Array` with `PackedStringArray`

![perf_string_name_vs_string](https://github.com/godotengine/godot-proposals/assets/84369217/afc3c578-74d5-4a53-a3f8-9b09fdcd6a4e)

**Overall:** `Array[StringName]` are better than `Array[String]` but worse than `PackedStringArray`

**Comment by AThousandShips** [comment]
You're still comparing *creating* with *inserting*

**Comment by tokengamedev** [comment]
I did a little bit study on the purpose of PackedArrays. With respect to StringNames and how the values are handled, it does not fit. Forget about performance and other stuff.

I think this proposal is invalid. This can be closed..

**Comment by Mickeon** [comment]
You can close your own proposals too 😉

**Comment by Calinou** [comment]
Closing per the above comments.
