### ISSUE TITLE
Mesh and UV editing in editor

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot-proposals#809]
Include a complete mesh editing tool and UV editing tool.
This would speed up a lot workflow, prototyping, or indies level creation without needing to constantly switch between a modeler.

This has huge advantage over CSG tool that lacks control and possibilities.

https://youtu.be/YtzIXCKr8Wo?t=288

Also the ability to extrude meshes from draw lines for even more faster and natural workflow.

https://youtu.be/7Ff0zZcHmaU?t=251

**Comment by Zireael07** [comment]
There was someone more than halfway through making something like ProBuilder for Godot on /r/godot, but hasn't returned.

So yes, it's definitely possible.

**Comment by bojidar-bg** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
