### ISSUE TITLE
Add optional warnings when accessing properties and methods whose name starts with an underscore from other scripts.

### ISSUE THREAD

**Issue by HexagonNico** [godotengine/godot-proposals#8095]
### Describe the project you are working on

Not related to a particular project, but could help people to keep a coherent style in GDScript. I was encouraged to open a proposal to discuss this idea when I opened godotengine/godot#83250 .

### Describe the problem or limitation you are having in your project

Whether GDScript should have access modifiers or not is a matter that has been discussed for a long time. Some people have suggested to add keywords or code annotations, but others are in favor of keeping everything public to avoid adding complexity to a language that was designed with simplicity in mind. Up to now, the convention has been to use identifier names starting with an underscore for private variables and functions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Until the matter is resolved, I suggest to implement an optional warning (ignored by default) that triggers when an attribute or method whose name starts with an underscore is accessed from another script to enforce the convention, without adding complexity to the language.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For example, this will trigger the warning, since `_private` and `_private_func` have a name that begins with an underscore and they are accessed from another script.
```
class_name MyScript
extends Node

var _private: int = 1

func _private_func():
    pass
```
```
extends Node

@onready var _my_script: MyScript = $MyScript

func _ready():
    _my_script._private += 1
    _my_script._private_func()
```
I should also mention that accessing the same variables and function from a child script will not trigger the warning, so technically they wouldn't be private, but protected. For example, this will not trigger the warning.
```
class_name OtherScript
extends MyScript

func _ready():
    _private += 1
    _private_func()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This could probably be worked around by adding a `push_warning` statement to the setter function of some variables, but this could become cumbersome for scripts containing many private variables.

### Is there a reason why this should be core and not an add-on in the asset library?

Since this is also mentioned in the [official GDScript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#functions-and-variables) I believe there should be an option in the engine by default.

**Comment by Mickeon** [comment]
This falls back to what I said a few days ago in https://github.com/godotengine/godot-proposals/issues/8065.

> I do agree with the proposal, but the more suggestions arrive about "hiding things from the user", the more justifiable it feels to begin work on a `private` keyword, or some... `@hidden` annotation. It would be a catch-all solution of sorts.

I'd rather have the matter solved once and for all, but I don't see harm in adding this warning for the time being, then removing it later. I believe there already existed a warning for a "private" property not being used anywhere within the same script? If yes, this does complement it.

**Comment by AThousandShips** [comment]
I don't think a style aspect should be enforced like this, especially as it is only partially effective as it works only in a strongly typed context, and doesn't affect `call` or `get/set`

I think leaving the use of underscore to be simply a stylistic detail until a proper access control system can be implemented, especially if it turns out such a system is not going to be implemented

The only way the underscore affects anything in the current code is that it controls how documentation is generated, but only partially, it is a suggestion, and I feel adding a warning or even error alone, that is only effective in some cases, is not something that should be focused on, as it will either enforce a rule without any access control, or will be removed once access control is enforced properly

**Comment by HexagonNico** [comment]
I also believe it shouldn't be a strict enforcement, hence why it is ignored by default the same way warnings that enforce static typing are, but since it is mentioned in the style guide I thought it could also be mentioned in the editor.

**Comment by AThousandShips** [comment]
Who said it shouldn't be strictly enforced?

**Comment by Calinou** [comment]
I would prefer adding an actual `@private` annotation for this, rather than rely on name-based warnings.

**Comment by HexagonNico** [comment]
I am closing this proposal since I am also in favor of the addition of a `@private` annotation. This was meant to be a temporary solution until #641 was resolved.
