### ISSUE TITLE
Tensor support

### ISSUE THREAD

**Issue by Jorvan758** [godotengine/godot-proposals#8099]
### Describe the project you are working on

I want to implement some machine learning models, as well as efficiently work with graphs inside the engine (which have adjacency matrixes and feature matrixes, among other things).

### Describe the problem or limitation you are having in your project

Without tensor support (or at least matrix support, that goes further than 3x3) it's unfeasible to even implement a linear regression (let's not even talk about a neural network).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Tensor support allows everything I mentioned and more. Besides, it's obviously useful, as the other big engines have already implemented it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Tensor support on GDScript could be based on what other libraries from Python do (like Numpy, PyTorch or TensorFlow) and should consider all the basic operations (addition/substraction, multiplication/division, exponentiation/logarithm, the trigonometric functions, Hadamard product and dot product), and ideally others like modulo, absolute value or truth statements (among others).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The engine can still go on without this feature, as most games won't **really** need it, but it will be really unfeasible to implement sophisticated stuff like I mentioned.

### Is there a reason why this should be core and not an add-on in the asset library?

I've been using the engine for months and can't think of a more relevant feature than this. It would truly allow amazing things.

**Comment by Jorvan758** [comment]
(I'm genuinely curious about why some have downvoted my suggestion. Has it already been asked and I didn't know? Do you think it just isn't a priority? Did I fill the template incorrectly?
Whatever it's your reason, I would be thankful if you tell me to keep it mind 👀)

**Comment by theraot** [comment]
I think you would tackle this with compute shaders. Barring that could you do it with a third party language?

*No, I didn't vote, but I don't think this belongs GDScript, or put another way, I don't GDScript is ready for this.*

**Comment by Stwend** [comment]
I downvoted because I don't think it should be core but rather an add-on. To use your examples, Numpy, PyTorch and TensorFlow aren't a fundamental part of Python itself, they're Python extensions, and I think the same applies here - I see how there's a huge benefit in it for people wanting to do machine learning with Godot, but I don't think it's relevant for most Godot users.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6049 and/or https://github.com/godotengine/godot-proposals/issues/2506.
