### ISSUE TITLE
Add automatic scrolling and toggleable scrollbars to ScrollBar and ScrollContainer

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#810]
**Describe the project you are working on:**
Space ship project

**Describe the problem or limitation you are having in your project:**
I have to manually code keyboard based scrolling and I have to supply empty textures for scrollbars to hide them
 
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
2 things
- make scrollbars and scroll containers automatically scroll to `none`, `top`, `middle`, or `end` focused child
- allow us to disable scrollbars for scrollbars and scroll containers 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
so when you are using non mouse or touch based controls godot will scroll to the focused control based on the focus scroll mode

disabling the scrollbars would only disable mouse scroll bar focus based scrolling would still work

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
yes but something like this we shouldn't have to code around its something most gui libraries have

**Is there a reason why this should be core and not an add-on in the asset library?:**
currently godots ui system needs some love especially for non mouse based interaction

**Comment by MaaaxiKing** [comment]
As to the point with an autoscroll, I have also an idea: as it is possible with PathFollow2D to set a unit offset, I think, this would be great here too! And I'd also like to be able to hide the scrollbar.

**Comment by Zephyr8965** [comment]
I just want to throw my voice in on this one. Being able to hide scrollbars would be wonderful. You could just make some checkboxes for scrolling elements in the editor for scroll bar, mouse wheel, touch scrolling, and focus auto scroll so those are each an independent, optional feature of the class.

**Comment by Jummit** [comment]
I think hiding the scrollbars is possible with `ScrollContainer.get_h_scrollbar().hide()`.

**Comment by Shadowblitz16** [comment]
> I think hiding the scrollbars is possible with `ScrollContainer.get_h_scrollbar().hide()`.

It might be possible is that documented?

**Comment by MaaaxiKing** [comment]
> I think hiding the scrollbars is possible with `ScrollContainer.get_h_scrollbar().hide()`.

Normally, everyone would think that that works but it It does not.

**Comment by KoBeWi** [comment]
> make scrollbars and scroll containers automatically scroll to none, top, middle, or end focused child [...] so when you are using non mouse or touch based controls godot will scroll to the focused control based on the focus scroll mode

What do you mean by this? Scrolling to focus was implemented in https://github.com/godotengine/godot/pull/34269, you just need to enable it (`follow_focus` property).

**Comment by MaaaxiKing** [comment]
> Scrolling to focus was implemented in [godotengine/godot#34269](https://github.com/godotengine/godot/pull/34269), you just need to enable it (`follow_focus` property).

Oh, that's genius. I meant something like that, just not so finished, but the topic you linked to is way better!

**Comment by pattlebass** [comment]
I think I found some workarounds to hide the scrollbars:

- If you want to still be able to drag the scroll bar, but want it invisible:
`ScrollContainer.get_h_scrollbar().modulate = Color(0, 0, 0, 0)`

- If you want it gone:
`ScrollContainer.get_h_scrollbar().rect_scale.x = 0`

**Comment by KoBeWi** [comment]
> I have to supply empty textures for scrollbars to hide them

Why do you want to hide scrollbars? ScrollContainer without scrollbars is basically any Control with `clip_content` enabled. Put anything under such control and move it to achieve the same effect. So why use ScrollContainer for this case?

**Comment by Shadowblitz16** [comment]
its so I can implement scrolling manually with buttons.
not everything has a mouse or keyboard

**Comment by KoBeWi** [comment]
But the point of ScrollContainer is that it has scrollbars and some scrolling controls (including touch). As I said, if you want custom scrolling, you can use any Control node as parent and just enable `rect_clip_content` property. It will make anything under it clipped and you can implement scrolling just by moving its children.

**Comment by Shadowblitz16** [comment]
Implementing the scrolling is harder the just marking a boolean to disable the scrollbar visibility.
Also it makes sense that a new user would use a scroll container to implement scrolling because that's what its for and its literally in the name.

**Comment by KoBeWi** [comment]
> Implementing the scrolling is harder the just marking a boolean to disable the scrollbar visibility.

Not really. You are just replacing `scroll_horizontal/vertical = ` with `rect_postion =`. Here's some example project for it:
[ReproductionProject.zip](https://github.com/godotengine/godot-proposals/files/6380258/ReproductionProject.zip)

ScrollContainer is meant as a control container with easy scrolling using scrollbars (which isn't exactly trivial to implement). If you want to disable scrollbars then, unless you want to use touchscreen scrolling in ScrollContainer, you are throwing away most of ScrollContainers functionality. It's like using disabled TextureButton instead of TextureRect. As I shown in my example above, scrollable canvas is as easy to implement without ScrollContainer.

**Comment by Shadowblitz16** [comment]
well what if I do want touch?
what if I don't want touch and want scrollbars?
these things should be configurable.

Also scrolling is not the same as just setting the rect_position one involves boundaries and possible item size calculation as well as easing.

**Comment by LightningAA** [comment]
Does `follow_focus` fit your needs for automatic scrolling? If so, this issue can be closed.

**Comment by Shadowblitz16** [comment]
what does follow_focus do?

**Comment by LightningAA** [comment]
Try it? There's a gif of it here: https://github.com/godotengine/godot/pull/34269

**Comment by Shadowblitz16** [comment]
that seems to fix the first part of the issue, but It doesn't solve the part of wanting to hide scrollbars

**Comment by LightningAA** [comment]
That's what https://github.com/godotengine/godot/pull/48008 was for

**Comment by Shadowblitz16** [comment]
this can be closed
