### ISSUE TITLE
Allow structs in GDScript

### ISSUE THREAD

**Issue by ltecheroffical** [godotengine/godot-proposals#8110]
### Describe the project you are working on

A RPG type game

### Describe the problem or limitation you are having in your project

Very simple data ends up being hard to store for 1 class.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add structs to GDScript as well as letting them be set in the inspector.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

someone can define a struct in GDScript using

struct StructName {
    var int_value: int = 348,
    var string_value: string = "Hello, World!",
}

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around with custom resources and classes but this is tedious to set up and classes cannot be exported in the inspector.

### Is there a reason why this should be core and not an add-on in the asset library?

This can be used to store simple data for 1 class out of the box and this exists in every programming language.

**Comment by dalexeev** [comment]
* There is already a proposal #7329 with a more detailed description.

Thanks for the proposal nonetheless!
