### ISSUE TITLE
Cannot achieve type safety in GDScript due to lack of basic language features

### ISSUE THREAD

**Issue by Johnrobmiller** [godotengine/godot-proposals#8136]
### Describe the project you are working on

Unions, intersections, type inferencing, declaring explicit types, interfaces, and more -- all of these GDScript does not have. I would not call it a dynamically typed language at the moment even if it is one technically speaking. And until these features are implemented, it is currently impossible to have type safety using GDScript.

This is a very serious problem, and I really hope the devs are reading this and taking this seriously. This is honestly very bad, and I think that implementing basic and essential features like this should be high priority.

Godot needs at least the minimum set of features needed to write typesafe code.

### Describe the problem or limitation you are having in your project

Cannot achieve type safety using Godot

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot needs at least the minimum set of features needed to write typesafe code.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Typescript is a great example of how this should work: https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no workaround for not having basic features like this.

### Is there a reason why this should be core and not an add-on in the asset library?

People are not going to write typesafe code without a basic set of features that enable them to do so, and this is so essential and importatn that it would make no sense for it to simply be an add-on.

**Comment by Calinou** [comment]
Please don't open duplicate issues after having opened [another proposal that was closed as duplicate](https://github.com/godotengine/godot-proposals/issues/8135). Further violations to this rule will get you blocked from participating in this repository.

**Comment by Johnrobmiller** [comment]
Bro, this is not a duplicate. Those two issues have nothing alike. Please stop trolling us
