### ISSUE TITLE
TileMap.get_used_cells_by_id() should use index instead of id

### ISSUE THREAD

**Issue by tylerecouture** [godotengine/godot-proposals#814]
**Describe the project you are working on:**
NA

**Describe the problem or limitation you are having in your project:**
Confusing method in TileMap node

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The `TileMap` method `get_used_cells_by_id(int id)` is confusing because nowhere is it explained what `id` is.  It should probably be `get_used_cells_by_index(int index)` to be consistent with the rest of the TileMap node.  Docs for this method should clarify that too.

For example, the related method `get_used_cells()` DOES refer to _index_, not _id_ (whatever that is)

> `Array get_used_cells() const`
> 
> Returns a `Vector2` array with the positions of all cells containing a tile from the tileset (i.e. a **tile index** different from -1).

_index_ is also referred to in the `setcell()` and `getcell()` methods, as opposed to _id_

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Self explanatory

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes, just update docs to explain what _id_ is reffering to

**Is there a reason why this should be core and not an add-on in the asset library?:**
Already core.

**Comment by tylerecouture** [comment]
Thanks!  Can the current 3.2.1 docs be updated for current users? https://docs.godotengine.org/en/stable/classes/class_tilemap.html?highlight=TileMap#class-tilemap-method-get-used-cells-by-id

Just a note that `id` = `index`?

**Comment by Calinou** [comment]
@tylerecouture Done in https://github.com/godotengine/godot/pull/38686.

**Comment by potaito** [comment]
I stumbled upon this by searching for the meaning of "index" and "id". Would it make sense to add to the documentation, that "index" is the index defined in the tilemap editor?
