### ISSUE TITLE
Rename WorldMarginShape3D to InfinitePlane3D

### ISSUE THREAD

**Issue by MarcusElg** [godotengine/godot-proposals#816]
The name makes absolutely no sence to me, can someone describe why it's named as it is. I could send a pr to change it but want to ask first.

**Comment by Zireael07** [comment]
It used to be named Plane3D, but then people were confused about the fact that it's infinite...

**Comment by MCrafterzz** [comment]
> It used to be named Plane3D, but then people were confused about the fact that it's infinite...

How about infinitePlane3D? I don't understand how it has any connection with margin.

**Comment by MCrafterzz** [comment]
Also shouldn't there be a way of having a non-infinite plane collision shape?

**Comment by Calinou** [comment]
> Also shouldn't there be a way of having a non-infinite plane collision shape?

A thin BoxShape can be used for that :slightly_smiling_face: 

Anyway, PlaneShape was renamed to WorldMarginShape to make its *infinite* property more obvious.

**Comment by MCrafterzz** [comment]
> > Also shouldn't there be a way of having a non-infinite plane collision shape?
> 
> A thin BoxShape can be used for that 
> 
> Anyway, PlaneShape was renamed to WorldMarginShape to make its _infinite_ property more obvious. I don't think we should revert this; a lot of people seem to not understand the "infinite" component of a mathematical plane.

InfinitePlane3D makes sense in my head

**Comment by Calinou** [comment]
Closing per https://github.com/godotengine/godot/pull/39595#issuecomment-644783280.

Also, WorldMarginShape was renamed to WorldBoundaryShape in https://github.com/godotengine/godot/pull/52679.
