### ISSUE TITLE
Improve editor gizmos for WorldBoundaryShape2D

### ISSUE THREAD

**Issue by MarcusElg** [godotengine/godot-proposals#817]
![image](https://user-images.githubusercontent.com/19669673/81498721-dac8e400-92c6-11ea-83e7-7e1af7b2a079.png)

From my experience being new to this component it does feel very unintuitive to use the handles. First of all for all other shapes the blue area represents the collision area so this make it look like the collision is a T shape which I guess it's not. Secondly you can move the line away from the origin and rotate it but there seams to be no way to change the length of it as the handles normalize the normal resulting in you having to use the inspector to change the line length. So what do I propose?

1. Use something else than a blue area for the normal to make it clear what's part of the collision shape and what's not.
2. Make it possible to use the rotation dot to also change the length of the line.

Let me know your thoughts! And depending on what you say I'll send a pr.

**Comment by Calinou** [comment]
reduz said on IRC LineShape2D should be removed in profit of using thin RectangleShapes instead.

**Comment by MCrafterzz** [comment]
> reduz said LineShape2D could be removed in profit of using thin RectangleShapes instead, so I'm not sure what we should do exactly.

Removing it would make sense. I'll send a pr.

**Comment by Calinou** [comment]
@MCrafterzz Please wait before opening a pull request, we need to discuss it further.

**Comment by MCrafterzz** [comment]
@reduz what do you think, should it be removed?

**Comment by clayjohn** [comment]
Also note this is the second issue you have opened without following the template. Doing so is against rule 1 https://github.com/godotengine/godot-proposals.

In the future, please properly fill out the template and follow the rules or your proposal will be closed.

**Comment by MCrafterzz** [comment]
@clayjohn what am I suppost to do then? Small feature request arent issues, also I dlnt wanna create a pr for something people dont want and on discord there's noone to ask about these kinda stuff. So what should I do to discuss small changes? @clayjohn

**Comment by Calinou** [comment]
> also I dlnt wanna create a pr for something people dont want and on discord there's noone to ask about these kinda stuff. 

You can join the engine developer channel on IRC: http://webchat.freenode.net/?channels=#godotengine-devel

**Comment by MCrafterzz** [comment]
> > also I dlnt wanna create a pr for something people dont want and on discord there's noone to ask about these kinda stuff.
> 
> You can join the engine developer channel on IRC: https://webchat.freenode.net/?channels=#godotengine-devel

Ok I'll check that out, maybe that's the best for small changes. What should I do with discussions like this (what todo with lineshape), where should they go?

**Comment by clayjohn** [comment]
@MCrafterzz Sure it does, in this case the project you are working on is the Godot editor. Look at how reduz handled something similar https://github.com/godotengine/godot-proposals/issues/815

**Comment by MCrafterzz** [comment]
> @MCrafterzz Sure it does, in this case the project you are working on is the Godot editor. Look at how reduz handled something similar #815

Ok I'll do that going forward. Thanks for your help

**Comment by MCrafterzz** [comment]
Going back to the intended discussion: LineSegment2D already exists which works like lines usually do with a start point and end point so you could use either that or the boxshape so imo there's no reason to have 3 different ways of achieving the same result.

**Comment by MCrafterzz** [comment]
@akien-mga what do you think of removing lineshape2d? Or is there a reason to keep it?

**Comment by Calinou** [comment]
@pouleyKetchoupp Should LineShape2D be removed in 4.0?

**Comment by pouleyKetchoupp** [comment]
@Calinou I think it can be useful to keep it as `WorldMarginShape2D` like we did for 3D.

About the original suggestions:
> 1. Use something else than a blue area for the normal to make it clear what's part of the collision shape and what's not.

That would be great, it does seem confusing to use the same color as for actual collision shapes.

> 2. Make it possible to use the rotation dot to also change the length of the line.

It's an infinite line, so there's no length to change. Although it would be nice to make the documentation clearer as this is not mentioned. Maybe a visual hint that it's infinite would help too, but I'm not sure what it could be :)

**Comment by MCrafterzz** [comment]
> @Calinou I think it can be useful to keep it as `WorldMarginShape2D` like we did for 3D.
> 
> About the original suggestions:
> 
> > 1. Use something else than a blue area for the normal to make it clear what's part of the collision shape and what's not.
> 
> That would be great, it does seem confusing to use the same color as for actual collision shapes.
> 
> > 1. Make it possible to use the rotation dot to also change the length of the line.
> 
> It's an infinite line, so there's no length to change. Although it would be nice to make the documentation clearer as this is not mentioned. Maybe a visual hint that it's infinite would help too, but I'm not sure what it could be :)

Seeing this again I clearly missunderstoud how the lineshape works. I think you could change the length of the line by scaling the object, but it's only a visual representation and not the accual shape of the object which is very confusing as its different from the other collision shapes. I'm probably not the only one confused by it so it would probably be a good idea to inprove the editor to make it more clear that it's a infinite line.

Also why not infinitelineshape instead of worldmarginshape2d?

**Comment by Calinou** [comment]
> Also why not infinitelineshape instead of worldmarginshape2d?

See https://github.com/godotengine/godot/pull/36388#issuecomment-589238938.

**Comment by AncientSion** [comment]
this is still a problem in 3.5.2, i have absolutely no idea how to set this up.

**Comment by Calinou** [comment]
> this is still a problem in 3.5.2, i have absolutely no idea how to set this up.

The LineShape2D editor requires you to move two points, but these are **not** the line's ends. The line shape is *perpendicular* to the two points you place, and is infinitely long. The axis the line shape follows is represented by the long blue line, while the short blue line represents the line's *normal*.
