### ISSUE TITLE
Automatically load specific resource packs when the project starts

### ISSUE THREAD

**Issue by programneer** [godotengine/godot-proposals#8172]
### Describe the project you are working on

A WW2-style FPS shooter game.

### Describe the problem or limitation you are having in your project

Having 1GB *for example* .pck might not only increase filesize a lot, but also adds a lot of download bandwidth which forces to download new one when update came out, For those have low-speed internet connection will have an difficulty for downloading it due to massive filesize.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding an new `PackedStringArray` called `Additional Packs` in `Project Settings > Application > Run` so we can put additional packs there.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When `graphics.pck` and `audio.pck` was added, the engine will attempt to load `graphics.pck` after the main pack has successfully loaded, then after also successfully loaded that, it will also attempt to load `audio.pck` but if they can't find `audio.pck` because it's missing in executable directory, it will fail and show the error message.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Maybe.

### Is there a reason why this should be core and not an add-on in the asset library?

It should be core.

**Comment by AThousandShips** [comment]
Please provide more reasons why you would need this, some actual examples

**Comment by Zireael07** [comment]
Splitting download into multiple files due to speed or data limits *is* a reason people would need this.

Another example use case is to allow easier modding - e.g. moddable data lives in one pck and core data in another

**Comment by Calinou** [comment]
> but also adds a lot of download bandwidth which forces to download new one when update came out

Remember that PCK files themselves are not compressed (even if they contain compressed data). This allows binary delta updates such as Steam's SteamPipe or itch.io's Butler to work correctly with these files and apply incremental updates, rather than having to download the entire PCK again.

**Comment by programneer** [comment]
Closing as this is useless unless you need.

**Comment by Zireael07** [comment]
Unless you need what?
