### ISSUE TITLE
Expose get_packet function in ENetPacketPeer to scripting

### ISSUE THREAD

**Issue by nwroyer** [godotengine/godot-proposals#8175]
### Describe the project you are working on

A multi-user GIS application requiring custom network functionality and integration with a non-Godot server using ENet. 

### Describe the problem or limitation you are having in your project

There is currently no functionality in the master branch to retrieve custom packet data from a standalone ENetConnection (i.e. one not wrapped by an ENetMultiplayerPeer). This means that I'm unable to use Godot's ENet implementation in my application for the client, in order to take advantage of some of the improvements (IPv6 support, etc.), while retrieving packet data and performing custom logic on it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose the existing `get_packet` method in `ENetPacketPeer` to scripting in order to allow users to operate on packets received by an ENet connection on a lower level than using the high-level multiplayer features.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There are two possible courses of action here:

- Expose a `get_packet` method on ENetPacketPeer that returns a PackedByteArray, allowing users to use ENetConnection and ENetPacketPeer to retrieve data from a connection at a lower level than using ENetMultiplayerPeer.
- Make the exposed `ENetConnection.service()` function return the same PackedByteArray as the third parameter (after event type and ENetPacketPeer) in the returned Array.

Both will allow users to work with the received data at a lower level than ENetMultiplayerPeer allows. The second option may be more in line with end user expectations; however, the first option will allow for the user to decide whether they want the data, potentially reducing unwanted copy operations.

Suggested implementation:

```C++
PackedByteArray ENetPacketPeer::_get_packet() {
	uint8_t* buffer;
	int buffer_size = 0;
	Error err = get_packet((const uint8_t**) &buffer, buffer_size);
	ERR_FAIL_COND_V(err != OK, PackedByteArray{});

	if (buffer_size < 1) {
		return PackedByteArray{};
	}

	PackedByteArray byte_array;
	byte_array.resize(buffer_size);

	// Copying to avoid the PackedByteArray's contents to 
	// point to undefined space once enet_packet_destroy is called on
	// its actual data
	std::memcpy((void*) &byte_array[0], (void*) buffer, buffer_size);
	return byte_array;
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No - this is an engine functionality that is not currently exposed to scripting. While the number of projects using this improvement might be limited, those projects requiring this functionality will likely be using it extensively.

### Is there a reason why this should be core and not an add-on in the asset library?

This is exposing an engine functionality to scripting - it is not possible to create a script, including GDExtension scripting, that replicates this functionality.

**Comment by nwroyer** [comment]
Implemented by pull request https://github.com/godotengine/godot/pull/83531.

**Comment by Faless** [comment]
`ENetPacketPeer.get_packet` is already exposed to scripting through the parent class [PacketPeer](https://docs.godotengine.org/en/latest/classes/class_packetpeer.html#class-packetpeer).
