### ISSUE TITLE
Tweak the AssetLib editor icon to not look like a padlock

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-proposals#818]
I've been getting some feedbacks on Twitter about how the AssetLib icon looks like a padlock.
This might make it more difficult for users (it took me a while too) to find the link for AssetLib.
What do you think? :)

https://twitter.com/NebulaBytes/status/976096307629588480

**Comment by fire** [comment]
This is transferred from the godotengine/godot-design repo because it sat in limbo.
