### ISSUE TITLE
Allow Lightmap Bake to be Cancelled

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot-proposals#8181]
### Describe the project you are working on

Graphics intensive demo scenes

### Describe the problem or limitation you are having in your project

Sometimes when lightmapping a large scene, there's a chance the lightmapper will take a _lot_ longer than expected and needs to be cancelled. Currently the only way to do this is to stop the Godot process altogether. This can be an arduous task since Godot will hog all GPU resources and slow interaction to a crawl, and all unsaved work is lost.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Cancels the bake.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a "cancel" button to the lightmap progress bar dialog.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often.

### Is there a reason why this should be core and not an add-on in the asset library?

Concerning a core aspect of Godot's functionality.

**Comment by jcostello** [comment]
Totally necesary in case of a mistake bake

**Comment by badsectoracula** [comment]
This was implemented by https://github.com/godotengine/godot/pull/99483 so i think this should be closed.
