### ISSUE TITLE
Add ignorable columns to translation CSVs

### ISSUE THREAD

**Issue by IntangibleMatter** [godotengine/godot-proposals#8183]
### Describe the project you are working on

An RPG with lots of dialogue and many characters in complex conversations, featuring many characters at once.

### Describe the problem or limitation you are having in your project

When I want to denote which character is speaking in a Translation file, either for my own use, or for the use of translators, there is no way to write a column which will be ignored in the CSV file when imported.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make it so that csv locale columns that begin with an underscore are ignored when being imported into Godot. This means that you can add columns exclusively for those editing the files, without having to worry about weird invalid translation files being generated.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

No change to the engine API, just the ability to write files like this
```csv
key,en,_character
hey,Hey!,John
whatsup,What's up?,John
notmuch,Not much.,Jade
cool,"Cool, cool.",John
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is a fundamental QOL thing for people working on translations. Additionally, it cannot be worked around without completely rewriting the CSV Translation importer.

### Is there a reason why this should be core and not an add-on in the asset library?

TranslationServer is core, and CSV is the most common way for indie games to do translations.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/84569.
