### ISSUE TITLE
Tweak GridSnap editor icon to not look like an abbreviation for "Antialiasing" in Chinese

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-proposals#819]
The current icon for [Grid Snap](https://github.com/godotengine/godot-design/blob/e88d4958b835497776d36f5bac397ecdda63adb0/engine/icons/svg/icon_snap_grid.svg) looks very similar to the Chinese character "抗"(anti-), which is often used as an abbreviation for "抗锯齿"(anti-aliasing) in a graphic software context.

The current icon looks like this on the toolbar. As a native speaker, I can't resist thinking it's an antialiasing toggle every time I look at the button in Godot :(

<img width="160" alt="current" src="https://user-images.githubusercontent.com/372476/76180306-8aff6b00-61f8-11ea-8acc-5f9231d4ece6.png">

I suggest using a more "grid" like graphic like this (icon taken from [here](https://www.iconfinder.com/icons/612278/grid_magnet_magnetic_snap_icon))

<img width="160" alt="sample" src="https://user-images.githubusercontent.com/372476/76180300-889d1100-61f8-11ea-9e2b-d711f3503a94.png">

**Comment by fire** [comment]
This is transferred from the godotengine/godot-design repo because it sat in limbo.
