### ISSUE TITLE
Improve workflow when adding elements to an @export array

### ISSUE THREAD

**Issue by ruanrothmann** [godotengine/godot-proposals#8193]
### Describe the project you are working on

Active ragdoll game - though the type of game is not relevant to the issue

### Describe the problem or limitation you are having in your project

I have an array of nodes that I am exporting:
`@export var items : Array [Node3D]`

That I need to populate with several nodes from the scene. Currently, it seems that the only way to do this is to click "Add Element" until the array is large enough to contain all the elements, and then drag items in one by one into the slots.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I have two proposals to improve the workflow for this:

First, and most straightforward: Dragging an item onto the "Add Element" button should increase the size of the array by 1 and add the element to the array.

Second, and even better is a way to multi select items from the scene and drop them all onto the array, appending them. This has another issue currently: releasing of M1 changes focus in the inspector to the item you clicked on (ie, the first item you would want to select to add to the array).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://imgur.com/a/F1naMyu

The first proposal is straightforward.

The second part is a bit more involved: Add a lock button in the inspector. Clicking that would make the inspector stay focused on the current node, allowing you to conveniently click in the Scene tree to e.g. expand, collapse, or multi select to set up various `@export` that you might need to. Unity does this and it is a godsend for working with complex scene setups.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

In some applications you could directly reference nodes in the scene with the $ operator and manually add them into an array in _onready but that is clunky and less flexible. I believe this will improve workflow for any scene that needs a lot of node `@export`, especially ones that need arrays. 

### Is there a reason why this should be core and not an add-on in the asset library?

This is a simple workflow improvement that would be overkill for an asset.

**Comment by tokengamedev** [comment]
@ruanrothmann First, please embed the img/video inside proposal. It really helps. I was not aware until I click the URL

Second i completely agree with your problem. It becomes a nuisance to track down a node among the list of similar named nodes, when they look almost the same in scene editor. God help you,  if you are designing a level with hundreds of nodes.

Lastly on the solution approach, I will go with locking of inspector approach as it helps selecting not only from scene tree but also from scene editor.

**Comment by AdriaandeJongh** [comment]
I was halfway into writing this exact proposal until I saw this one already existed. For everyone looking for this specific functionality, do note that you CAN drag one or multiple items from the filesystem on the top-most array object in the inspector to add them to the array, like so (red indicating mouse position):
<img width="464" alt="Screenshot 2024-02-06 at 14 52 49" src="https://github.com/godotengine/godot-proposals/assets/5611323/2035e979-9df5-4d0d-b9c7-8d1e55a777cf">
or, at least, this is possible in Godot 4.2.

**Comment by AeioMuch** [comment]
Here : https://github.com/godotengine/godot/pull/89406, I was suggesting the possibility to hold the dragged nodes above target one for a certain amount of time to inspect it as an alternative to pinning the inspector (even if this is added). It think it is intuitive to do it this way because so many programs do this. What do you think ?

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/89406.
