### ISSUE TITLE
Add File System dock side-by-side visualization

### ISSUE THREAD

**Issue by samdze** [godotengine/godot-proposals#82]
**Describe the project you are working on:**
2D platformer, 2D top view, ect. but applies to every project.

**Describe how this feature / enhancement will help your project:**
A new mode, featuring a side-by-side view of the File System dock would allow for much more space being utilized effectively by the dock itself in every type of project if a user decides to give the dock more width than default, making it possible to display two full-height columns of folders and files.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Unity already does this way:
![immagine](https://user-images.githubusercontent.com/19392104/65275720-877f0700-db26-11e9-97cd-7265f973c786.png)

**Describe implementation detail for your proposal (in code), if possible:**
I guess utilizing a HSplitContainer instead of a VSplitContainer and moving other UI accordingly could be enough.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, this is one of the editor's main features.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is an editor improvement that potentially benefits every project.

**Comment by fire** [comment]
This is the closest I can get Godot to go.

Perhaps you can scribble on it with your changes.

![Screen Shot 2019-09-19 at 1 02 02 PM](https://user-images.githubusercontent.com/32321/65276962-bfae2780-dadd-11e9-9ce2-bb8495bd42c4.png)

**Comment by samdze** [comment]
Yes that's the standard "one over the other" view mode.
Shouldn't be complex to add this additional side-by-side layout.

**Comment by YuriSizov** [comment]
I'll close this proposal, as there doesn't seem to be a lot of traction for this specific idea. However, do note that the idea of utilizing space more efficiently for the FileSystem dock is still considered. We have https://github.com/godotengine/godot-proposals/issues/4565 to discuss more global changes of the layout (though it will have to wait post-4.0).
