### ISSUE TITLE
Ability to rotate alternative tiles

### ISSUE THREAD

**Issue by verbess** [godotengine/godot-proposals#8203]
### Describe the project you are working on

A 2D top-down game based on TileMap.

### Describe the problem or limitation you are having in your project

Alternative Tiles offers a tile-flipping feature, but in some scenarios, tile rotation is also required to achieve all possible styles.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If a rotation feature was added, all possible designs could be achieved with just 15 differently patterned tiles. However, if only the flipping feature is used, it would require the addition of duplicate tiles on top of the 15 base tiles.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When using `Alternative Tiles`, you can rotate the tiles with the `Rotation` function.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature should be integrated into TileSet and not stand alone as a plugin.

### Is there a reason why this should be core and not an add-on in the asset library?

This feature should be core function of TileSet.

**Comment by verbess** [comment]
Sorry, I found another transpose function that could solve this problem.

**Comment by Calinou** [comment]
> Sorry, I found another transpose function that could solve this problem.

Please document the solution here by commenting :slightly_smiling_face:

**Comment by verbess** [comment]
> Please document the solution here by commenting 🙂

OK, Here is the solution for "rotating alternative tiles":

- Rotate 90 degrees clockwise:

  Enable `Flip H` and `Transpose`.

- Rotate 180 degrees clockwise:

  Enable `Flip H` and `Flip V`.

- Rotate 270 degrees clockwise:

  Enable `Flip V` and `Transpose`.

Further more, the statement in the [Godot documentation](https://docs.godotengine.org/en/latest/tutorials/2d/using_tilesets.html#creating-alternative-tiles) that `Transpose` is equivalent to rotating a tile counterclockwise by 90 degrees seems to be entirely incorrect. The accurate description should be that it is equivalent to rotating the tile counterclockwise by 90 degrees and then performing a vertical flip operation.

  > Rendering > Transpose: If true, the tile is rotated 90 degrees counter-clockwise.

**Comment by Calinou** [comment]
Thanks for pointing this out! Please review https://github.com/godotengine/godot-docs/pull/8299 :slightly_smiling_face:
