### ISSUE TITLE
Add settings and options the way code is commented in GDScript using shortcuts in 4.2+

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#8211]
### Describe the project you are working on

Projects in 4.2

### Describe the problem or limitation you are having in your project

Currently the code is commented using the shortcut keys like `Ctrl+/`or `Ctrl+K` in windows. 
The way code being commented is as follows

Before commenting
```gdscript
func some_func():
	var y :int = 0
	for x in 10:
		y += x * 2
	
	print(y)
```
After Comment (whole text selected):
```gdscript
#func some_func():
	#var y :int = 0
	#for x in 10:
		#y += x * 2
	#
	#print(y)
```
This is well and fine but, in my perspective, it looks unreadable comments and feels like interfering with my code. It may be fine for some people, hence requesting to, have alternative approach based on settings.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement a setting under `editor settings` to add the comment char at the level of the selected code.
The settings can be like `<Some Path>\comment_char_location`. the values can be like
 - Start of text
 - Start of Line (Optional - At par with 3.x)
 - Start of code with lowest indent (Proposal)

In all the three options, I would like to add the comment char `#` to be suffixed with a space char like `# `.

### Selection 1 -  Start of Text:
Behavior is same as current.  Ideally it should have space between comment char `#` and the text itself like 
```gdscript
# func some_func():
	# var y :int = 0
	# for x in 10:
		# y += x * 2
	#
	# print(y)
``` 
### Selection 2 - Start of Line(Optional):
Comment char will be placed at the start of the line, irrespective of the code indent. 

> This is optional and out of context of the proposal, but it is the way 3.x implemented, hence included in the list. 

```gdscript
# func some_func():
#	var y :int = 0
#	for x in 10:
#		y += x * 2
#
#	print(y)
```
### Selection 3 - Start of lowest indented code (Proposal):
Comment char will be placed at the start of the lowest code indent. 
This needs a little bit more logic. The behavior is similar to how VS code handles code commenting. Listed below is the list of possibilities I could think from the top of my head.

```gdscript
## Possibility 1 - When first line is lowest indent (func line)

# func some_func():
#	var y :int = 0
#	for x in 10:
#		y += x * 2
#
#	print(y)

## Possibility 2 - When first line is lowest indent (for loop)

func some_func():
	var y :int = 0
	# for x in 10:
	#	y += x * 2
	#
	# print(y)

## Possibility 3 - When first line is not lowest indent (assignment line)

func some_func():
	var y :int = 0
	for x in 10:
	#	y += x * 2
	#
	# print(y)
```

**Behavior:**
No change requested for selected code to comment or uncomment as it makes sense and logical.
Blank spaces commenting is fine.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This will be used very often. 

### Is there a reason why this should be core and not an add-on in the asset library?

Parsing of script is part of core.

**Comment by Deozaan** [comment]
> In all the three options, I would like to add the comment char `#` to be suffixed with a space char like `# `.

That part of the proposal contradicts [the GDScript style guide for comment spacing](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html#comment-spacing), which says:

> Regular comments should start with a space, but not code that you comment out. This helps differentiate text comments from disabled code.
>
> ### Good:
> 
> `# This is a comment.`
> `#print("This is disabled code")`
>
> ### Bad:
>
> `#This is a comment.`
> `# print("This is disabled code")`

**Comment by tokengamedev** [comment]
Guidelines are to guide.
We game developers have to live with the code. Write/read/change code on new and old games. The way we have to maintain the code depends upon our style. Hence some of the guidelines we follow, some not.

Now coming to the request, I don't see the code that much readable, in current format but 3.x style I can live with it.

I asked this proposal because I faced a problem recently in 4.2, where I commented a large part of code to test some scenario.
then piece by piece I tried to uncomment as part of test. It was very hard to read and uncomment because I have comments,
inside code. It was a mess.
when gave newlines between code, it went out of control. The only way out was uncommenting the whole code and comment only function calls.

**Comment by Deozaan** [comment]
Yes, of course you are free to ignore the official guidelines and style your code however you want in your projects. But I'm not sure it makes sense for Godot to offer a setting which contradicts its own style guides. Other than that, this seems like a fine proposal.

That said, it sounds to me like what you really want is multi-line comments. If GDScript supported multi-line comment then it might make sense for it to have a line showing where the block started, a line showing where it ended, and then commenting out everything in between with a straight vertical line and a space after it, as shown in your proposal.

Perhaps something like this:

```
## Possibility 1 - When first line is lowest indent (func line)

#*
# func some_func():
#	var y :int = 0
#	for x in 10:
#		y += x * 2
#
#	print(y)
*#

## Possibility 2 - When first line is lowest indent (for loop)

func some_func():
	var y :int = 0
	#*
	# for x in 10:
	#	y += x * 2
	#
	# print(y)
	*#

## Possibility 3 - When first line is not lowest indent (assignment line)

func some_func():
	var y :int = 0
	for x in 10:
	#*
	#	y += x * 2
	#
	# print(y)
	*#
```

**Comment by tokengamedev** [comment]
> Yes, of course you are free to ignore the official guidelines.

Those are style guides and moreover it has not been updated since 3.x, but the commenting has modified drastically since then. So yes, I will happily Ignore, if it makes sense to me. A professional developer knows, when to follow guidelines and when not.

> That said, it sounds to me like what you really want is multi-line comments.

It is not what I asked for, so stop changing the proposal direction.  

> If GDScript supported multi-line comments.

Personally, I do not want multiline comments in GDScript. It is kind of nuisance if you use inside code. 
But it is great for commenting large amount of code. But try nesting and feel the pain. 
Also, in some style guides (C# and Javascript), I have seen, they try to avoid multiline comments like a plague, unless it is documentation comments.

> Perhaps something like this:
```gdscript
#*
# func some_func():
#	var y :int = 0
#	for x in 10:
#		y += x * 2
#
#	print(y)
*#
```
I don't think multiline comments are written this way unless it is documentation comments: 

It would more look like this,

```
#*
  func some_func():
	var y :int = 0
	for x in 10:
		y += x * 2

	print(y)
*#
```
**I am just saying it. I do not want multi line comments.**

Next to reiterate my proposal, I do not want to modify the existing behavior of the comments, as it is obvious by now, some people like it. The only thing I want is an option for other people like me who want a different style of commenting.

**Comment by Deozaan** [comment]
> It is not what I asked for, so stop changing the proposal direction.

My apologies.

**Comment by ConteZero** [comment]
I've done a basic implementation of "Selection 3 - Start of lowest indented code"

Here the changes to `/editor/code_editor.cpp`

```
--- code_editor.cpp	2023-10-28 12:40:14.000000000 +0200
+++ mod/code_editor.cpp	2023-10-29 16:36:31.118538335 +0100
@@ -1505,6 +1505,24 @@
 			folded_to = text_editor->get_next_visible_line_offset_from(to + 1, 1) - 1;
 			to += folded_to;
 		}
+
+		// Start of lowest indented code
+		int indent_idx = -1;
+		for (int line = from; line <= to; line++) {
+			int tmp_indent_idx = text_editor->get_first_non_whitespace_column(line);
+			if (text_editor->get_line(line).strip_edges().is_empty()) {
+				if (text_editor->get_line(line).length() < indent_idx) {
+					tmp_indent_idx = 0;
+				}
+			}
+			if ((indent_idx == -1) || (tmp_indent_idx < indent_idx)) {
+				indent_idx = tmp_indent_idx;
+			}
+		}
+		if (indent_idx == -1) {
+			indent_idx = 0;
+		}
+
 		// Check first if there's any uncommented lines in selection.
 		bool is_commented = true;
 		bool is_all_empty = true;
@@ -1547,7 +1565,7 @@
 			if (is_commented) {
 				text_editor->set_line(line, line_text.replace_first(delimiter, ""));
 			} else {
-				text_editor->set_line(line, line_text.insert(text_editor->get_first_non_whitespace_column(line), delimiter));
+				text_editor->set_line(line, line_text.insert(indent_idx, delimiter));
 			}
 		}
 
```

**Comment by tokengamedev** [comment]
I think it is working as designed and most of the Godot users don't need it. So closing the Proposal.
