### ISSUE TITLE
Add `Node.is_being_edited()` as an equivalent of `Engine.is_editor_hint()` for editor plugins

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot-proposals#8216]
### Describe the project you are working on

A bespoke editor plugin for my game.

### Describe the problem or limitation you are having in your project

Plugin code needs to be marked with `@tool` in order to run in the editor.

However, this also causes the code to be run while editing a scene belonging to the plugin. This is often undesirable, because it makes changes to the scene which then get saved in the `.tscn` file.

For non-plugin scripts, `Engine.is_editor_hint()` is used to work around this. But in a plugin script, this function always returns true, even while the plugin is running "as a plugin" and is not being edited.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since the node will be part of the same engine instance and scene tree, whether it's running as a plugin or running in the scene editor, a global function like `Engine.is_editor_hint()` won't be possible.

Instead, maybe a function on `Node` could be added, like `is_being_edited()`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`is_being_edited()` could look at the node's ancestors to find out whether the node is a descendant of the scene editor. I think that would be the `CanvasItemEditor` class in the current implementation, but this is not exposed in the API.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, I'm currently using something along these lines as a workaround, but it only works for main screen plugins:

```cs
    public static bool IsRunningAsPlugin(Node node)
    {
        foreach (var mainScreenChild in EditorInterface.Singleton.GetEditorMainScreen().GetChildren())
        {
            if (mainScreenChild is MyPluginMainPanel && mainScreenChild.IsAncestorOf(node))
            {
                return true;
            }
        }
        return false;
    }
```

### Is there a reason why this should be core and not an add-on in the asset library?

Seems like many plugins that use scenes can benefit from this.

**Comment by ttencate** [comment]
A cleaner workaround to detect whether the node is being edited, thanks to @kleonc:

```gdscript
if owner == null || owner == get_tree().edited_scene_root:
```

This seems like a cleaner approach than checking all ancestors. The check for `null` is necessary because the root of the edited scene seems to have no `owner`.

If this is deemed robust, it could be added as a helper function to the `Node` class in core.

**Comment by KoBeWi** [comment]
The method exists, it's just not exposed:
https://github.com/godotengine/godot/blob/6543495b49613d20f7e32f2b9d38e4a2f1d06db1/scene/main/node.cpp#L2386-L2389

**Comment by KoBeWi** [comment]
> It's guarded by #if TOOLS_ENABLED though. Will that be a problem?

If a script uses this method, it will have parse error after export. This applies to all editor plugins, so usually it's not a problem.
Although if there is a use-case for using such script in non-editor context, the method can be changed to instead always return true in exported project, instead of not existing.
