### ISSUE TITLE
Add property usage flag for reordering inspector properties

### ISSUE THREAD

**Issue by dugramen** [godotengine/godot-proposals#8219]
### Describe the project you are working on

Editor plugins 

### Describe the problem or limitation you are having in your project

You can currently create inspector properties statically with `@export`, and dynamically with `_get_property_list()`. But the latter properties always appear after the export properties.

You have to convert everything to `_get_property_list()` to have custom ordering.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have another property usage flag, something like PROPERTY_USAGE_PLACEHOLDER_POSITION. It accepts a hint_string (or just its name), which is the name of the property that should be moved to this position. It'll move `@export` properties next to custom properties

There should also be an export version with `@export_plaheholder_position('prop_name')`, which behaves the same, but for moving custom properties next to `@export` properties

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Moving dyanamic properties up to `@export` properties:
```
@export var prop1 := 10
@export_placeholder_position("prop2")
@export var prop3 := "apple"

func _get_property_list():
    return [{
        name = "prop2",
        type = TYPE_VECTOR2
    }]
```

Moving `@export` properties down to `_get_property_list()`:
```
@export var prop2 := Vector2()

func _get_property_list():
    return [
        {
            name = "prop1",
            type = TYPE_INT,
        },
        {
            name = "whatever",  
            type = TYPE_NIL,
            usage = PROPERTY_USAGE_PLACEHOLDER_POSITION,
            hint_string = "prop2"
        },
        {
            name = "prop3",
            type = TYPE_INT,
        },
    ]
```

The order should be this for both cases:
- prop1
- prop2
- prop3

If there is no property defined for the given hint_string, then just ignore it

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's possible if every property gets converted to a custom property in `_get_property_list()`. But that's a lot more tedious, and the order of inherited properties still won't be adjustable

### Is there a reason why this should be core and not an add-on in the asset library?

Inspector behavior is core

**Comment by Mickeon** [comment]
Why do you need this? What is the use case? Why can't groups and categories accomplish what you need?

**Comment by dugramen** [comment]
> Why do you need this? What is the use case? Why can't groups and categories accomplish what you need?

For my plugin I have exported properties, each with another property for mutations/fallbacks. But the mutation properties are optional and only appear if they exist. 

Using groups would turn every property into a group, and again, I wouldn't be able bring it up next to the related property. Currently they all appear at the bottom which really hurts usability

**Comment by dalexeev** [comment]
There is no need to add a usage flag to the core, it can be handled exclusively by GDScript.

**Comment by dugramen** [comment]
Ok I managed to brute force this by moving the related EditorProperty nodes around in the scene tree. So I'll close this now since it seems to be undesired
