### ISSUE TITLE
Add ability to change export options from a plugin / ability to put project settings as export options

### ISSUE THREAD

**Issue by Sooshiko** [godotengine/godot-proposals#8221]
### Describe the project you are working on

I'm tired of changing every export template manually one by one for both File Version and Product Version.

### Describe the problem or limitation you are having in your project

They all need to be the same so I'd like to have a .txt file, .gd file or custom project setting for a version string that automatically updates everything at once. I tried downloading a plugin but they all do exactly the opposite. They take the version from export templates and put it in a gd file so you can read it at runtime. I want it the other way around where I change a gd file or project setting i can read at runtime and it updates every export options on export.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The simplest way to make it work would be to add some sort of function that let me change export options from a tool or plugin. EditorExportPlugin's _export_begin seems perfect for this but I can't find a way to edit/override the export options.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Option 1 : Some sort of function that let you override an export option like Export.set("file_version", "1.0.0.0") inside of EditorExportPlugin's _export_begin.

Option 2 : make template options able to hold a project setting. so you can make a custom Version setting and every export template reads from it during export.

I don't know how hard it would be to implement Option 2 but I think it would be the most elegant one.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I could not find a way around it. You just have to manually change every export template one by one.

### Is there a reason why this should be core and not an add-on in the asset library?

It cannot be done with plugins, obviously.

**Comment by KoBeWi** [comment]
It was implemented in https://github.com/godotengine/godot/pull/35555 (coming in 4.2)
There's also this addon, although it has a bit different use-case: https://github.com/KoBeWi/Godot-Auto-Export-Version

**Comment by Sooshiko** [comment]
That's the plugin i refer to in the proposal. It does exactly the opposite of what you'd expect. I can't get it to work in reverse.

**Comment by Sooshiko** [comment]
I'm still using the plugin, for the record. Because it's better than nothing.

**Comment by KoBeWi** [comment]
And what about the PR I linked? This functionality is available in 4.2 beta.

**Comment by Sooshiko** [comment]
It looks like that will do it. Can't wait for 4.2 :)

**Comment by KoBeWi** [comment]
Closing as implemented then.
