### ISSUE TITLE
Expose "Exclude nodes from collision" option on PhysicalBone3D joints

### ISSUE THREAD

**Issue by ruanrothmann** [godotengine/godot-proposals#8223]
### Describe the project you are working on

Active ragdoll game

### Describe the problem or limitation you are having in your project

In the vast majority of cases, you do not want two bodies connected with a joint to collide with each other. This functionality is already present in Generic6DOFJoint and others, but is not exposed in the joint used on PhysicalBone3D:

![image](https://github.com/godotengine/godot-proposals/assets/37209327/3d37db1c-6c08-441b-b131-a8968c4039bf)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would expect it to appear here:

![image](https://github.com/godotengine/godot-proposals/assets/37209327/cfa2b6ac-c5bd-445b-a797-1f88c00bb1fe)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As (I believe) the PhysicalBone3D's joint is just a wrapper for the other joints, the option exists, it simply needs to be exposed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can work around this by manually excluding collisions for the nodes, but I think it makes sense for PhysicalBone3D's joints to work the same as the underlying joints.

### Is there a reason why this should be core and not an add-on in the asset library?

Simply exposing a property that already exists.

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/issues/70942

**Comment by ruanrothmann** [comment]
> See also:
> 
> * [Collisions between 2 connected PhysicalBone3d godot#70942](https://github.com/godotengine/godot/issues/70942)

That captures my issue exactly and it seems is just waiting to be merged, apologies for the double post

**Comment by AThousandShips** [comment]
No worries!
