### ISSUE TITLE
Convert dicts into classes

### ISSUE THREAD

**Issue by ltecheroffical** [godotengine/godot-proposals#8235]
### Describe the project you are working on

A 2D proceedially generated Rpg/adventure type game.

### Describe the problem or limitation you are having in your project

Casting a dict to a class doesn't have the expected outcome.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The abilty to cast dicts to a class to fill the fields of it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This will be used like this:

```GDScript
var dict = {
    "x": 32,
    "y": 64
}

var vector_object = dict as Vector2

print(vector_object.x) # 32
print(vector_object.y) # 64
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

this can be worked around by itering through the dict and setting the fields but this ends up being complex and not very easy to do.

### Is there a reason why this should be core and not an add-on in the asset library?

This requires changes to the GDScript Server and as far as I know this is not possible for an addon.

**Comment by Mickeon** [comment]
> Casting a dict to a class doesn't have the expected outcome.

Are you sure this is not expected? Dictionaries and vectors, for example, store their variables in completely different ways. Any way of implementing this will inevitably be more complicated than using pure vectors in the first place. This conversion is a somewhat "hacky" way to use Dictionaries, so what is the use-case of this?

**Comment by ltecheroffical** [comment]
The use case would be this:

```GDScript
class CustomClass:
    var int_val: int
    var string_val: String

var class_instance = CustomClass.new()

class_instance.int_val = 43687
class_instance.string_val = "Hello, World!"

var bytes_value = var_to_bytes(class_instance)

print(bytes_value)

var orignal_value_bytes = bytes_to_var(class_instance) # We have to cast it because it returns a dict
var orignal_value = orignal_value_bytes as CustomClass # This is where the unexpected outcome would happen
```

**Comment by AThousandShips** [comment]
Have you tried `var_to_bytes_with_objects`?

**Comment by ltecheroffical** [comment]
This has the same risk as var_to_str and str_to_var if not more (https://youtu.be/j7p7cGj20jU)

**Comment by AThousandShips** [comment]
Yes, I am aware, but you are wanting a way to *automatically* serialize and deserialize objects, and there's really no in-between because you need to handle properties being set/get managed etc.

**Comment by ltecheroffical** [comment]
I do know but that seems like a proposal that will not get accepted anytime soon

**Comment by ltecheroffical** [comment]
also under the hood it can work like this:

```GDScript
var target_dict = {"a": 1, "b": "c"}
for property in target_dict:
  if property.ends_with(".gd"):
	  continue
  
  if property.ends_with(".cs"):
	  continue
  
  target_obj[property] = target_dict[property]
```

**Comment by Calinou** [comment]
> I do know but that seems like a proposal that will not get accepted anytime soon

I'd consider the proposal in question pretty much "accepted" already. It's just that the implementation will have to wait until 4.3 at the earliest to be merged, like any other implementation currently because 4.2 is in feature freeze.

**Comment by AThousandShips** [comment]
Well we don't do proposals that are "temporary fixes" like that, it is trivial to just do a save/load method that converts to a `Dictionary` so there's no pressing need for this

**Comment by ltecheroffical** [comment]
okay, closing issue as accepted?
