### ISSUE TITLE
Implement "any_key" event in input actions

### ISSUE THREAD

**Issue by CoyanCardenas** [godotengine/godot-proposals#8236]
### Describe the project you are working on

A game where I am waiting for any key pressed down this frame, I don't care which key.

### Describe the problem or limitation you are having in your project

The only option I can find for receiving any key event is Input.is_anything_pressed. However, I do not want keys that are being held down to be registered as valid, I only want keys that have been pressed down this frame to be registered.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding "any_key" to the built in action events would enable users to listen for pressed, just pressed and just released events like other actions.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a new built-in action to the Input Map "any_key" which would listen for any and all keys presses from user.

Users could than access this event like other built in and custom input actions:

Input.is_action_just_pressed("any_key")
Input.is_action_pressed("any_key")
Input.is_action_just_released("any_key")

In addition, consider adding to enable users to do the same through code:
+ Input.is_anything_just_pressed
+ Input.is_anything_just_released

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by adding a custom input action and manually add every key, but this would take much time, and would need to do it for every project.

### Is there a reason why this should be core and not an add-on in the asset library?

I believe this is basic functionality and shouldn't require users installing an addon for

**Comment by CoyanCardenas** [comment]
> > It can be worked around by adding a custom input action and manually add every key, but this would take much time, and would need to do it for every project.
> 
> Except this can be worked around by having a simple script like this:
> 
> ```gdscript
> var last_just_pressed := false
> 
> func _process(_delta):
>     if !last_just_pressed and Input.is_anything_pressed():
>         do_something_on_just_pressed()
>     if last_just_pressed and !Input.is_anything_pressed():
>         do_something_on_just_released()
>     last_just_pressed = Input.is_anything_pressed()
> ```

Couldn't get that script to work, which indicates it may not be a simple as you seem to think?

**Comment by AThousandShips** [comment]
Then you must have copied it wrong, because it works, it *is* as simple as I seem to think :)

**Comment by CoyanCardenas** [comment]
> Then you must have copied it wrong, because it works, it _is_ as simple as I seem to think :)
> 
> Try this and see:
> 
> ```gdscript
> var last_just_pressed := false
> 
> func do_something_on_just_pressed():
> 	print("Just pressed")
> 
> func do_something_on_just_released():
> 	print("Just released")
> 
> func _process(_delta):
> 	if not last_just_pressed and Input.is_anything_pressed():
> 		do_something_on_just_pressed()
> 	if last_just_pressed and not Input.is_anything_pressed():
> 		do_something_on_just_released()
> 	last_just_pressed = Input.is_anything_pressed()
> ```

I literally copied this and it's not working. do_something_on_just_pressed() get's called when I'm holding down the key.

Here's what I'm trying to do. I'm making visible a black screen over the game, I want it to be up for x duration via timer, when timer is stopped, it checks for a button press down and the black screen goes away, but not if the player has been holding down a key. This script works in isolation nfor detecting key down and released, but for some reason when I try to implement the above it is registering a key press as soon as the timer is over. Here's my exact script

I'm simply doing this:

**Comment by AThousandShips** [comment]
> do_something_on_just_pressed() get's called when I'm holding down the key.

Are you saying it is printed constantly?

**Comment by CoyanCardenas** [comment]
No just once

**Comment by CoyanCardenas** [comment]
No, it's printing "pressed" when the key is **held down**

**Comment by AThousandShips** [comment]
You're contradicting yourself, is it printing it *just once* or *constantly*?

**Comment by CoyanCardenas** [comment]
Just once

**Comment by CoyanCardenas** [comment]
That's what I'm saying. I want is_action_just_pressed but with **any key**

**Comment by AThousandShips** [comment]
But, the `is_action_just_pressed` does *not* work as you say, it *doesn't* detect if the key is *held down* it just detects if it was just pressed

That is what `just_pressed` means

I'm sorry but you are suggesting something that works *differently* from how `is_action_just_pressed` works, but your proposal asks for something different than you think it does, you need to clarify what you are asking for works *differently* from how the current system works

Because I gave you exactly what you asked for if you meant how the system works with actions

**Comment by CoyanCardenas** [comment]
Let me try and explain what I mean. I know what just_pressed is supposed to do, it's what I want. I want to start a timer, and only want to register input if the key is pressed down after the timer has stopped not if it has been previously held down before the timers up.

Using `Input.is_action_just_pressed("myAction")` works as expected, as above.

When I use your script this is the behaviour I observe:
If I start the timer then hold a key down, do_something_on_just_pressed() gets called when the timer is stopped, without me pressing a key down.

If I hold a key down, then start the timer, it acts as it should with no input being registered.

I don't know if this is a bug in the input system or just that this script isn't exactly equivalent to a `Input.is_action_just_pressed("myAction")`, but this is what I'm seeing in my project.

**Comment by CoyanCardenas** [comment]
> Let me try and explain what I mean. I know what just_pressed is supposed to do, it's what I want. I want to start a timer, and only want to register input if the key is pressed down after the timer has stopped not if it has been previously held down before the timers up.
> 
> Using `Input.is_action_just_pressed("myAction")` works as expected, as above.
> 
> When I use your script this is the behaviour I observe: If I start the timer then hold a key down, do_something_on_just_pressed() gets called when the timer is stopped, without me pressing a key down.
> 
> If I hold a key down, then start the timer, it acts as it should with no input being registered until I release the key and press it again, which is the desired behaviour.
> 
> I don't know if this is a bug in the input system or just that this script isn't exactly equivalent to a `Input.is_action_just_pressed("myAction")`, but this is what I'm seeing in my project.

**Comment by Calinou** [comment]
> The only option I can find for receiving any key event is Input.is_anything_pressed. However, I do not want keys that are being held down to be registered as valid, I only want keys that have been pressed down this frame to be registered.

Out of curiosity, why do you need to ignore keys being held down? Can you describe the *concrete* use case you need this for?

If this is for skipping cutscenes, it's generally frowned upon to make any key skip instantly. It's better to require holding down a specific key for a short amount of time instead.

**Comment by CoyanCardenas** [comment]
> If that code doesn't help I'm not sure how to help, I've failed to understand what you are asking for because you keep contradicting yourself, I'm sorry that I'm not able to understand what you are asking for

Yes it works now thanks. I still think it's too much code for something that should be trivial.

**Comment by AThousandShips** [comment]
Is four lines too much code?

This isn't a feature most people need, I can't find anyone else requesting this, it's trivial to do on your own

**Comment by CoyanCardenas** [comment]
> Is four lines too much code?
> 
> This isn't a feature most people need, I can't find anyone else requesting this, it's trivial to do on your own

For something that should just be 1, and is 1 in other game engines,  I think yes.

**Comment by AThousandShips** [comment]
What other engines implement this?

**Comment by CoyanCardenas** [comment]
> What other engines implement this?

https://docs.unity3d.com/2020.1/Documentation/ScriptReference/Input-anyKeyDown.html

**Comment by SilicDev** [comment]
I might be wrong but wouldn't checking `InputEvent.is_pressed()` in `_unhandled_input(event: InputEvent)` or `_input(event: InputEvent)` work for most cases?

**Comment by AThousandShips** [comment]
That would also solve this indeed, for that side of it

**Comment by AThousandShips** [comment]
Please be polite and constructive, I have not called your proposal preposterous or anything. Do not put words in my mouth, that's rude...

It *is* trivial and simple to achieve this functionality, I don't see why you put quotes around that

Just because a someone sees a feature as missing, or want it, doesn't mean it will be added, that's how open source works, you made a proposal, and I presented arguments against it being added

I have not said it *won't* be added, I simply stated that adding it feels unnecessary because:
* Few people seem to need this (there's not a single other proposal for this, I've searched)
* It is very simple to do on your own
