### ISSUE TITLE
Rework mouse_filter system to be more flexible and intuitive

### ISSUE THREAD

**Issue by cajallen** [godotengine/godot-proposals#824]
**Describe the project you are working on:**
RTS with camera panning

**Describe the problem or limitation you are having in your project:**
Mouse filters do not provide the desired functionality to have camera panning through `mouse_entered` and `mouse_exited` signals on control nodes behind the HUD in a simple and intuitive way.
![image](https://user-images.githubusercontent.com/56494731/81598676-4e352900-938d-11ea-9f3e-5b3899641ad9.png)
If I move the mouse into a corner only the control node furthest down in the tree will emit a `mouse_entered`. There are of course janky workarounds (like adding more buttons), but there is no reason to force this, and there are still limitations when you consider multiple UI systems working in unison. 
Many newer users are also confused when they first come to Godot and don't understand how mouse filters work. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Replace mouse filters with flags based on functionality. The flags I would suggest are:
READ
HANDLE
PASS_TO_PARENTS (if it handles)
I'm not sure about the naming here, it may be misleading because as I understand, mouse filters and input handling are not the same thing.
The existing mouse filters could easily be converted to these flags.
Stop -> True, True, False
Pass -> True, True, True
Ignore -> False, False, _
This would additionally add the functionality of allowing control nodes to read mouse, without preventing other nodes (especially siblings and cousins) from doing the same.
I would also consider adding a `READ_IF_HANDLED` flag, but I'm not fully sure how this would work and it's not core to this proposal. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![image](https://user-images.githubusercontent.com/56494731/81598676-4e352900-938d-11ea-9f3e-5b3899641ad9.png)
I would set the Button's mouse_filter flags to 
READ: True
HANDLE: True
PASS_TO_PARENTS: false,
and Left-Bottom's flags to
READ: True
HANDLE: False
PASS_TO_PARENTS: false
This would allow me to use the `mouse_entered` and `mouse_exited` signals on the control nodes to set the following booleans
![image](https://user-images.githubusercontent.com/56494731/81600192-d49e3a80-938e-11ea-8404-b557c8c3e483.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Examples of workarounds and why they aren't effective
* Parenting each node so that `Pass` will let the current sibling nodes also read the mouse.
This is not a very modifiable or readable approach. This doesn't use parenting for it's intended purpose, and in the case of multiple UI systems acting in unison, it isn't always possible.

* Reading mouse data in `_process`
Reading mouse data in process loses handling of the mouse. As a concrete example, I don't want to trigger `mouse_entered` on the bottom control node if the user is just mousing over the button.

* Adding corner control nodes
This works in this simple example, but it doesn't expand, to fix the problem as a whole. Again, it doesn't work if multiple UI systems are working in unison. It also doesn't work if there are multiple layers that want this functionality.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, This is a problem that comes up in tons of projects, and makes Godot more intuitive to new users.

**Comment by andy-noisyduck** [comment]
I've been looking a bunch of the Control proposals recently, so I'll chime in...

> Many newer users are also confused when they first come to Godot and don't understand how mouse filters work.

I feel your pain. When I first started working with Control nodes the mouse events also tripped me up. However, I am not sure adding even more complex options helps this. Surely we fix it by improving the documentation? The docs are already a lot better on this subject than they used to be - the [InputEvent tutorial](https://docs.godotengine.org/en/3.2/tutorials/inputs/inputevent.html) covers a lot of this now.

Your proposal essentially allows stacked controls to all receive the same input. This seems to be like a pretty funky edge case. Having a bunch of controls all able to receive the same mouse click seems likely trip users up even more? If I click somewhere, I would expect the top-most control under the mouse to receive that click, and only that control.

Allowing multiple controls to get the same event, and then also propagate that event, raises some questions that I don't think your proposal covers. Does the top-most control get the event first? When does a control underneath it get the event? How would the event propagate up the tree? What if those controls don't have the same parent? What if they do have a common parent (or common parent of parent etc)? Does the parent get it twice? Does it stop propagating up the tree if the tree has already seen that event from another control? You could of course decide on rules for all of these, but does this achieve your goal of a simpler event system?

> ...and there are still limitations when you consider multiple UI systems working in unison.

Are there some other use cases you had in mind? I'm not sure I'm seeing the problem from your perspective.

> ...Reading mouse data in process loses handling of the mouse. As a concrete example, I don't want to trigger mouse_entered on the bottom control node if the user is just mousing over the button.

Would `_unhandled_input` not be a good candidate for this?

**Comment by cajallen** [comment]
> However, I am not sure adding even more complex options helps this.
I would argue that, while this proposal adds functionality, the use of it becomes easier, as the concept of how these options affects your scene feels more intuitive to me, as they are simple and seperated. It can be thought of similar to the size flags.
> If I click somewhere, I would expect the top-most control under the mouse to receive that click, and only that control.
Sure. So set read and handle to true, and pass to parents as false.
> Allowing multiple controls to get the same event, and then also propagate that event, raises some questions that I don't think your proposal covers. Does the top-most control get the event first? When does a control underneath it get the event? How would the event propagate up the tree? What if those controls don't have the same parent? What if they do have a common parent (or common parent of parent etc)? Does the parent get it twice? Does it stop propagating up the tree if the tree has already seen that event from another control? You could of course decide on rules for all of these, but does this achieve your goal of a simpler event system?
All of these are answered by looking at how `_input` and `_unhandled_input` already work. Inputs propogate from the bottom of the tree vertically to the top, all the additional proposal does is give more granular control over stopping the propogation, it doesn't change any ordering.
> Are there some other use cases you had in mind? I'm not sure I'm seeing the problem from your perspective.
Nothing that I have in mind at the moment. This is an issue I've ran into frequently (specifically, not being satisfied with the existing mouse_filter system), but other examples I have are quite a bit more obfuscated,
> Would `_unhandled_input` not be a good candidate for this?
Unhandled input would work for mouse clicks, but it doesn't work for emulating `mouse_entered` and `mouse_exited` signals.

**Comment by andy-noisyduck** [comment]
> All of these are answered by looking at how `_input` and `_unhandled_input` already work. Inputs propogate from the bottom of the tree vertically to the top, all the additional proposal does is give more granular control over stopping the propogation, it doesn't change any ordering.

Then perhaps I have misunderstood your proposal. You said you wanted siblings and cousins to be able to read the same mouse event. If multiple controls are getting the same event (and can propagate) then your your path is no longer linear. Hence the questions.

> Unhandled input would work for mouse clicks, but it doesn't work for emulating mouse_entered and mouse_exited signals.

Fair. Though in your case, I still think it should be fine? You just want to check a defined border from the edge of the viewport and then scroll. That's just a few lines of code. That's actually probably easier than building it with control nodes anyway (and certainly easier than redesigning the input system).

**Comment by cajallen** [comment]
> Then perhaps I have misunderstood your proposal. You said you wanted siblings and cousins to be able to read the same mouse event. If multiple controls are getting the same event (and can propagate) then your your path is no longer linear. Hence the questions.

The only thing that would _change_ the order from how it already is, is if PASS_TO_PARENTS was able to be enabled while HANDLED was disabled, which should be fixable by just not considering PASS_TO_PARENTS if HANDLED is true.

> That's just a few lines of code. That's actually probably easier than building it with control nodes anyway (and certainly easier than redesigning the input system).

It would be if there was an easy way to check if the mouse was hovering over a GUI element that consumed mouse inputs.

**Comment by andy-noisyduck** [comment]
> The only thing that would change the order from how it already is, is if PASS_TO_PARENTS was able to be enabled while HANDLED was disabled, which should be fixable by just not considering PASS_TO_PARENTS if HANDLED is false.

Lets try something more concrete. In your example setup, if I click the bottom left corner (occupied by the intersection of 2 controls), which control gets the click input? How are your flags set to meet your requirement that siblings and cousins also get the click input? Or is that not what you mean by allowing siblings to read the mouse?

This might be easier if you detail what your flags mean. Perhaps the Godot input system is too ingrained in me that I can't see past it.

I think READ means something like "I want all mouse events in my bounding box regardless of where I am in the UI"? Compared to now, where only the top level control will get the input, and if it doesn't want it, it will be pushed up the tree.

What does HANDLE mean? I assume you can't handle an input you didn't read? If 2 controls have read the same event, how does the flag work? As a Control, how do I decide whether or not I want to handle the event after I get it? Or do I need to decide upfront? What if only want to handle certain types of mouse input? 

> It would be if there was an easy way to check if the mouse was hovering over a GUI element that consumed mouse inputs.

Understood. Yeah, I see the crux now. I guess you could wire up the `mouse_entered`\`exit` signals for all 4 of your borders to the same event handler, then check the region in there the same way, but it's not pretty. Though FWIW, if RTS style border scroll is actually what you are making, you normally want to always trigger the scroll, even if they are over another UI element (otherwise you get behaviour where users "edge nudge" and can't understand why it's not moving some of the time). 

Probably best if I stop the suggestions for your specific problem. The back & forth risks detracting from your actual proposal. Not my intention.

**Comment by cajallen** [comment]
> Lets try something more concrete. In your example setup, if I click the bottom left corner (occupied by the intersection of 2 controls), which control gets the click input? How are your flags set to meet your requirement that siblings and cousins also get the click input? Or is that not what you mean by allowing siblings to read the mouse?
This might be easier if you detail what your flags mean. Perhaps the Godot input system is too ingrained in me that I can't see past it.

Sure. Currently, I need to have the mouse_filter flags set to either pass, or stop if I want to read the mouse input.
The only difference between these is whether or not the MarginContainer gets it. This difference can be seen on the flag "PASS_TO_PARENTS". If it's ignore, that's false, if it's pass, that's true. Currently, Godot will give this input to the node named "Bottom" (as it works up vertically in the tree). If this isn't an action I consider to "handle" input, I would set HANDLE to false. This would then give Right a chance to read it, then Top, then Left, then the MarginContainer.
If it is set this way, it doesn't make sense to pass it to the parent. Because then the ordering would be Bottom -> Margin -> Right -> Margin -> ... That is why PASS_TO_PARENTS is automatically false if HANDLE is false.

READ is currently just a flag to emulate the current IGNORE behavior. It doesn't add functionality.
Theoretically, you could set READ to false on a node, and HANDLE to true if you wanted to consume mouse inputs in a certain area. I see no reason to disable this.

> As a Control, how do I decide whether or not I want to handle the event after I get it? Or do I need to decide upfront? What if only want to handle certain types of mouse input?

Important to note that the current system already has these problems. You can use `set_input_as_handled()` in `_gui_input()` to stop propagation (equivalent to setting HANDLE to true for the current event)

**Comment by andy-noisyduck** [comment]
I think I'm with you now. The example was helpful.

I think there's a couple of misunderstandings in how the current system works which confuses the proposal. 

> Sure. Currently, I need to have the mouse_filter flags set to either pass, or stop if I want to read the mouse input. The only difference between these is whether or not the MarginContainer gets it.

Sort of. Stop means the receiving Control will receive the event (via `_gui_input`) and then automatically consume the event and it won't pass up the tree (so in this case, the MarginContainer doesn't get it). Pass means the Control gets the choice. It will get the input event (again via `_gui_input`), can execute some logic, and then decide if the event should be allowed to continue to propagate (so the MarginContainer *might* get it, depending on the logic).

> Currently, Godot will give this input to the node named "Bottom" (as it works up vertically in the tree). If this isn't an action I consider to "handle" input, I would set HANDLE to false. This would then give Right a chance to read it, then Top, then Left, then the MarginContainer.

That isn't quite how it happens for mouse events. Godot will determine the single "highest level" Control using a depth-first search (from the root) and checking the bounding box at each stage. The first control found this way (i.e. contains the mouse coordinates, and has no more eligible children, and has mouse filters set to Pass or Filter) will be the control that receives the event. The event will then propogate up the tree (i.e. to the parent) until it's either consumed, or there are no more nodes. If you want to see the details it's in [viewport.cpp](https://github.com/godotengine/godot/blob/f7ca1c805ba2189627b49212ffbfba773f44acc5/scene/main/viewport.cpp#L1751).

If it helps, think of it as casting a ray into the GUI at the mouse coordinates. The control that is hit is the control that gets the event. If that control doesn't want it, Godot walks up the tree (so evaluates the parent) until it either finds a control that does or runs out.

In your example, if Bottom did not consume the event the next candidate control would be the parent MarginContainer. The other siblings are not ever considered.

**Comment by cajallen** [comment]
I see, my mistake. I thought it worked the same way as `_unhandled_input`, as my primitive tests were working the way I expected. I don't fully know how this suggestion would work in that case in terms of ordering, especially without breaking compatibility. I still think there's a problem here but I don't have a solution here for the ordering.
