### ISSUE TITLE
Remove 'Keep Custom Tracks' checkbox when saving animations to file

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot-proposals#8242]
### Describe the project you are working on

A third person adventure game with human main character and NPCs.

### Describe the problem or limitation you are having in your project

In the advanced importer there's a checkbox used when saving animations externally to keep custom AnimationPlayer tracks. It's off by default:
![image](https://github.com/godotengine/godot-proposals/assets/334808/034302b7-9381-4cfa-ab00-ffc074e90b6b)
Even when checked and reimported, we still have this in AnimationPlayer (probably a bug):
![image](https://github.com/godotengine/godot-proposals/assets/334808/e1aded70-f3e9-4832-8f52-95a7b2adfa9f)

While developing my game, I'm continually adding more animations. I sometimes forget to check the _Keep Custom Tracks_ checkbox and after adding my custom tracks, the data is quickly lost.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest just removing the checkbox entirely and always keeping custom tracks when anims are saved to file. If we have the ability to keep our custom data, should we not always use it? Data loss is pretty terrible and can result in a frustrating and time consuming debugging experience for the developer.

This could flow on to AnimationPlayer where if it detects the current Animation is a resource file, it could remove the 'Imported Scene' warning button.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

* Remove the 'Keep Custom Tracks' checkbox from advanced importer
* Remove the 'Imported Scene' button from AnimationPlayer when on an Animation saved to a resource file
* Always keep custom tracks using the existing functionality when anims are set to be saved to a file.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by remembering to check the 'Keep Custom Tracks' button in advanced import window.

### Is there a reason why this should be core and not an add-on in the asset library?

Addons cannot override advanced import settings after the Import button is clicked but before the importing process begins.

**Comment by Flynsarmy** [comment]
@AThousandShips Is there a reason for the confused emoji? There may be a good a reason we have this checkbox rather than doing things how I described in my post but I don't understand enough about internals to know why. If my request is bad let me know and I'll close it.

**Comment by AThousandShips** [comment]
Please don't tag or demand an explanation of someone just for reacting to your proposal...

**Comment by Zireael07** [comment]
Why are you so against explaining your reactions, especially confused emojis?

**Comment by Flynsarmy** [comment]
It could indicate I haven't explained my request well enough. If so that would be useful information and I could clarify. I wouldn't care about the reaction normally but when it comes from a maintainer it's a good indication there's something wrong with my post which is why I asked...

**Comment by AThousandShips** [comment]
It is an "hmm, I'm not sure" reaction, I don't have any strong opinions just a "I'm not so sure about this"

My reaction is to being tagged and asked to explain myself, is that so strange?

**Comment by AThousandShips** [comment]
I'm not against explaining anything, but reactions are a complement to comments, if I want to express my opinion on something I do, but if I were to explain every reaction I left I'd do nothing else, I am busy

I am sorry that you took my reaction to mean anything more than just what I explained it to be above, but please keep in mind that demanding an explanation of a reaction isn't very constructive or helpful, and to not take reactions for more than what they are

I am sorry if I reacted strongly but I don't like being put on the spot for trivial and minor things like me just leaving a reaction, I have many things to deal with

Have a good day

**Comment by Flynsarmy** [comment]
> but I disagree with the proposal to remove the checkbox, as there can be valid reasons to no want to save it

Just to clarify, the proposal isn't to remove the _Save to File_ checkbox - I agree there are valid reasons not to save to file, this proposal is to remove the _Keep Custom Tracks_ checkbox and just always keep custom tracks on anims that are saved to file.

**Comment by Flynsarmy** [comment]
> My argument was because that is always someone using a obscure workflow, and I believe we should not break it for those users. 

Fair and I agree! Thanks for the insight. Back to the drawing board!
