### ISSUE TITLE
Improve the look and formatting of node configuration warnings

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#8253]
### Describe the project you are working on

prototypes

### Describe the problem or limitation you are having in your project

![image](https://github.com/godotengine/godot-proposals/assets/71937306/952d1260-26b1-4a72-a980-058902e721d0)

- The text should adjust according to the '•'.
- separate errors are separated using several newlines.

They do however look good in the hover popup:
![image](https://github.com/godotengine/godot-proposals/assets/71937306/64d27987-2cef-4936-8868-12e05019afe0)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- Align subsequent lines in front of the `•` character used to denote a list.
- Use a horizontal line and a bit less vertical space to split the different errors. I think this makes it easier to see, considering there can be multiline text in some errors.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/71937306/64ae9c79-87cf-40a8-902a-f2446ef4f858)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

used often

### Is there a reason why this should be core and not an add-on in the asset library?

it's about improving core

**Comment by Calinou** [comment]
Neither the tooltip nor the dialog use RichTextLabel, so we have to use hacky solutions to align text with the bullet point. The tooltip and dialog do this by inserting a few spaces after line breaks, but this doesn't work with autowrapping as you can see in the dialog.

**Comment by Mickeon** [comment]
> They do however look good in the hover popup

[Thank you ❤](https://github.com/godotengine/godot/pull/64733)

Coming soon at your local pull request tracker after I iron out some things:

![image](https://github.com/godotengine/godot-proposals/assets/66727710/de29ea53-7744-4a17-b6ec-89154c3c18ae)

Adding a separation line would require changing how this dialog is generated. I don't think it's think is worth doing, because it would be a lot of code for a popup that I don't think matters too much.
