### ISSUE TITLE
Apply parent window content_scale_factor to Control Popup windows (Tooltips and Popup menus)

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-proposals#8267]
### Describe the project you are working on

An editor interface supporting hiDPI (retina) interface scaling. 

### Describe the problem or limitation you are having in your project

Implementing automatic hiDPI scaling of interfaces (https://github.com/godotengine/godot-proposals/issues/7968) I'm relying on detecting current scale and then using window content_scale_factor + resizing to get the window to be the same size by 2x resolution on hiDPI/retina displays as intended. However, some controls, like [MenuButton](https://docs.godotengine.org/en/stable/classes/class_menubutton.html) create additional popup windows to show their popup content. And these windows do not get the content scale or resizing applied, so they don't match the scaled interface.

![Screenshot 2023-10-26 at 20 22 52](https://github.com/godotengine/godot-proposals/assets/17763524/260e16ad-0498-4c45-b557-f1537aaa6a3f)

The same goes for the Control tooltips, that are shown in new separate non-scaled windows
![Screenshot 2023-10-26 at 20 40 14](https://github.com/godotengine/godot-proposals/assets/17763524/5fc2ce4c-0df2-4fff-b1c6-5bf0ce945e5c)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As these popup windows (menus and tooltips) are so strongly linked to the controls they originate from I'd propose that the content_scale_factor of the window the Control is in is automatically applied to the popup windows as well (and they're resized to match the new scale). 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When generating a popup for a control (a popup menu or tooltip), just apply the content_scale_factor of the window the control is in to the new popup window. And then when calculating the size of the new popup window, factor in content_scale_factor to get the correct new size for the scaled content (and not clipped).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not a few lines of code. For popup buttons you can try to intercept the popup when it's about to pop to apply the scaling, but it's unreliable as it's automatically resized and will be cropped. And for tooltips you'd need to supply a custom tooltip in a custom subclass of each control type to be able to apply the correct scaling.

### Is there a reason why this should be core and not an add-on in the asset library?

Getting the interface scaling of controls and their parts should just work out of the box. Applying scale to a popup button should also affect it's popup menu. And applying interface scaling to a window should also affect tooltips in that window.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/54030.

**Comment by lostminds** [comment]
> I'd consider this a bug,

I guess you're right. I also found this https://github.com/godotengine/godot/issues/69749 related bug report that is more specific, but I think could be considered a duplicate of the same issue. I'll close this proposal then since it seems this is already tracked elsewhere.
