### ISSUE TITLE
Select the root node resulting from the drag-and-drop operation after drag-and-dropping a file to the editor viewport

### ISSUE THREAD

**Issue by viksl** [godotengine/godot-proposals#8282]
### Describe the project you are working on

I'm adding gltf models into my scenes, every time I add one it doesn't get selected which makes it cumbersome to work with newly added meshes.

### Describe the problem or limitation you are having in your project

When you drag and drop a model into your scene the newly added object should be selected so you can immediately work with it - move, rotate, scale, ...

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Simply on drag and drop the object which was added should be selected to be ready to work with as an active object.
Dragging in multiple new items should have them all selected.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

No idea how to code this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No it's editor's basic feature.

### Is there a reason why this should be core and not an add-on in the asset library?

It's just a very basic functionality which works everywhere and shouldn't need an addon.

**Comment by Calinou** [comment]
This makes sense. From testing, this appears to be the case with any file type (also in the 2D editor).

**Comment by KoBeWi** [comment]
What if you want to drop multiple objects? Currently when you drag and drop, the new node is added as a child of the selected node. If the new node was selected, dropping multiple nodes would create a nested structure, which is rarely desirable (though it's the same behavior as copy paste).

**Comment by KoBeWi** [comment]
There are modifier that change the parent where the node is added. In 4.2.1 nodes are added to root by default, Ctrl adds them as child of selected node, Shift as a sibling.
In 4.3 the behavior was changed to add as child by default, so you can select a node and add multiple children. Though using a modifier you could still add the new nodes as sibling of the newly selected one, so I guess it's still possible (just less discoverable).

**Comment by viksl** [comment]
Would you please mind pointing me to the PR for 4.3 changes? I currently can't find it, or at least what was the name about? :)

The selecting currently added scene sure can be used to change properties if needed but the most value it has when building levels, you add something and you want to immediately move it, rotate it, currently you have to click on your node in the Scene tree or in the viewport before that happens. Especially in 3D this is impractical since clicking in viewport due to depth can easily select a different object, you ojbect might also not have an easily selectable AABB (imagine adding a marker or so scene, not saying it's common or why but it could happen), even more annoying is when you add multiple scenes and you want to quickly move them somewhere, currently you have to select them all and then work with them while with this PR you can start working with it straight. It doesn't sound like much but when filling the world in 3D it very quickly becomes a hindrance not having it. ^.^

**Comment by viksl** [comment]
@KoBeWi 
Ok I rebased (only on my end, did not push it!) on the current master with the changed behaviour you mentioned and there don't seem to be any issues.
Maybe this is a misudnerstanding about what this proposal and my PRs are about?
The PR changing the behaviour where the nodes go in the tree is not in conflict with the PRs for this proposal, both work together just fine as far as I can tell. But it was worth a check so thank you for bringing it up for testing, everything seems to be fine.

Do you think there's anything else which would be blocking the PRs please?

**Comment by KoBeWi** [comment]
> the most value it has when building levels, you add something and you want to immediately move it, rotate it, currently you have to click on your node in the Scene tree or in the viewport before that happens.

That makes sense.
Yeah, on a second though this change is fine.

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/84356 and https://github.com/godotengine/godot/pull/84347.
