### ISSUE TITLE
Add Label method to get position of a character

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#8299]
### Describe the project you are working on

Game with text.

### Describe the problem or limitation you are having in your project

I have various control prompts, i.e. stuff like "Press A to jump". I want to display the button image inside text, but I have a custom node type that displays action's icon, automatically switching between keyboard and joypad etc. so I can't use RichTextLabel's images.

I want to use a text placeholder, e.g. "Press * to jump" and place the button at *. However I couldn't find a reliable way to get the position of a character. I tried some TextServer methods, but to get it work I'd have to reimplement half of Label's text shaping. It's not reasonable.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If Label had a method that returns a Vector2 position of a given character, I could use it to position my node.
```GDScript
var pos = $Label.get_character_position($Label.text.find("*"))
$Label/TextureRect.position = pos
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add `Label.get_character_position(idx: int)` method, which would return a local position of the specified character.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, text shaping is complex.

### Is there a reason why this should be core and not an add-on in the asset library?

It could work as an addon, but it's difficult to implement.

**Comment by bruvzg** [comment]
> I have various control prompts, i.e. stuff like "Press A to jump". I want to display the button image inside text, but I have a custom node type that displays action's icon, automatically switching between keyboard and joypad etc. so I can't use RichTextLabel's images.

The proper way to do something like this would be using TextServer `shaped_text_add_object` (to add embedded object to string) and `shaped_text_get_object_rect` (to receive rect after shaping) methods. This is what RTL is using for images.

Character position can be implemented in the same way as text selection code (with length of 1). But there are problems with getting character positions: some characters do not have defined position (control chars, parts of ligature), or might have multiple drawn elements with the different positions (composite characters with diacritics, elongations).

**Comment by KoBeWi** [comment]
`shaped_text_add_object()` looks like it could work, but it requires shaped text RID, which Label does not expose. Also from what I gathered, there is separate RID for each line, so even getting line's RID is not that helpful, because line is not obvious when you use autowrapping. Getting line RID for a specific character index could be a replacement for the proposed method, if it's easier to implement.

> Character position can be implemented in the same way as text selection code (with length of 1). But there are problems with getting character positions: some characters do not have defined position (control chars, parts of ligature), or might have multiple drawn elements with the different positions (composite characters with diacritics, elongations).

Given the purpose of this method, this is not really a concern.

**Comment by bruvzg** [comment]
> but it requires shaped text RID, which Label does not expose. Also from what I gathered, there is separate RID for each line, so even getting line's RID is not that helpful

Yes, simple exposing RID won't work, since label will reset them on every change (and `add_object` should be used when setting text for shaping).

**Comment by KoBeWi** [comment]
Ok so the object does not have an index, it's just added at the end. Then it won't work for me, I want to use Label. With the method you provided I'd have to implement custom wrapping and other stuff .-.

**Comment by bruvzg** [comment]
I guess something like this should do it - https://github.com/godotengine/godot/pull/84185 (returns rects not just positions).

**Comment by KoBeWi** [comment]
Works perfectly, thanks.

**Comment by peachpieproductions** [comment]
Hey there, will this function be added to RichTextLabel? @bruvzg

**Comment by axilirate** [comment]
To add to this, I don't see a reason not to add the same method to RichTextLabel.
