### ISSUE TITLE
In-editor audio preview of music loop offset

### ISSUE THREAD

**Issue by davthedev** [godotengine/godot-proposals#83]
**Describe the project you are working on:**
A game for which I compose music for various levels. There are multiple pieces of music involved and some must be reworked.
Music has an intro part followed by a looping section.

**Describe how this feature / enhancement will help your project:**

In the imported OGG file properties, there is a loop offset setting. Getting it right requires a lot of guesswork.

For instance launching the game, listening to the music for the entire length, only to discover that the looping point has a "hiccup" due to not being correctly synced with the beat. Fine-tuning the value. Then doing it all over again. This is fairly time-consuming.

I can speed the process up by manually seeking towards the end of the music file on scene launch by code. But this is still not the most user-friendly solution.

Having an audio preview of the loop offset would greatly speed up that process.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

This is still to refine, but here is the main idea.
The preview mechanism would be located at the same place where the loop offset setting is.

Add a preview button that would play the music, starting one second or so before the end and actually perform the transition to the loop point. Or make it autoplay as the user changes the loop offset setting.

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

On a case-by-case basis, yes, as explained sooner. But it definitely is cumbersome for some fine-tuning work where the feedback loop must be fast.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This greatly improves the user experience for the audio offset point adjustement operation. Godot has an incredible mixer and effects bus system; this part of audio work also deserves a great experience.

**Comment by girng** [comment]
>  Music has an intro part followed by a looping section.

Isn't it conventional to split these up as 2 separate files?

**Comment by KoBeWi** [comment]
Are aware of this?
![image](https://user-images.githubusercontent.com/2223172/65325746-f8b6cc80-dbaf-11e9-9dee-63da45c4ba06.png)

It's an audio player that appears in the inspector when you double-click audio file in file system. You can play audio from any point, including near end, so it makes loop previewing ultra easy.

**Comment by davthedev** [comment]
How could not I see this before? It actually does a good job of previewing the loop point as well on OGG files!
My bad!
