### ISSUE TITLE
Add "paste unique" option when copy-pasting resources.

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#8308]
### Describe the project you are working on

Godot and VFX

### Describe the problem or limitation you are having in your project

When making particles, it can often happen to have to tweak color curves to different lifetimes. I already do this by copy pasting the gradient resource and making it unique, but that's a lot of clicks. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a paste-unique entry under paste where you can paste a resource (curvetexture, colorgradienttexture) and make it unique at the same time

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but clicks! More clicks.

### Is there a reason why this should be core and not an add-on in the asset library?

See above

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/7492.
