### ISSUE TITLE
Add an option to skip archive ipa in iOS export

### ISSUE THREAD

**Issue by abcjjy** [godotengine/godot-proposals#8310]
### Describe the project you are working on

An iOS casual game

### Describe the problem or limitation you are having in your project

My project uses Admob and various third party dependencies which rely on cocoapods. The exported ios project won't compile without pods installed. However, godot ios export is hard coded to archive and generate ipa, which is doomed to fail in my case. It wastes a lot of time. 

I'm trying to make an editor export plugin to run pod install. But I can't find a suitable method to override. For now, I can only override _export_end() and wait archive fail. 

Another use case is debugging on deivce. For most of the time, I export for debugging on device. Even when submitting to App Store, I use Xcode to archive and submit. The exported ipa is never used.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an option to skip archive and just export the xcode project

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I looked though the export_plugin source, the api does have a skip_ipa arguments. Only UI is needed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, EditorExportPlatformIOS exposes no api to script.

### Is there a reason why this should be core and not an add-on in the asset library?

It's hard coded. I didn't find a way to change it with an addon or plugin.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
In 4.2, there's already an option to only generate a Xcode project without building archive and ipa.
