### ISSUE TITLE
Don't render depth-based effects such as fog and depth of field when using an orthographic camera

### ISSUE THREAD

**Issue by ruanrothmann** [godotengine/godot-proposals#8334]
### Describe the project you are working on

A 3D game that uses the gridmap

### Describe the problem or limitation you are having in your project

If you have fog enabled in your WorldEnvironment, and would like to edit or view your scene with an orthogonal view (a very common scenario for games that use gridmap), fog is applied 100%, meaning you can't see anything in the scene. You need to go and disable fog in the WorldEnvironment and then remember to reapply it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

These settings (Fog and Depth are ones I found, but potentially there are more) should simply be ignored when the scene view camera is set to orthogonal. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Another option might be to change the "toggle preview environment" button active if there is a worldenvironment in the scene, but instead to change it's function to it being applied to the scene view.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can go and disable/enable fog etc every time you switch to orthogonal, but this is awkward and error prone.  Gridmap is a core feature for 3D prototyping though, and I believe this enhancement should benefit lots of users.

### Is there a reason why this should be core and not an add-on in the asset library?

Straightforward workflow improvement.

**Comment by yosoyfreeman** [comment]
An orthographic camera means no perspective, but the depth of the scene is still there.  It does not makes sense for me to remove features that are essential for 3D rendering regardless of perspective. 

In terms of your problem, could you show some images of it? I'm trying to re create the issue but all this effects seems to work properly for me. Here i have a test scene with Depth of field, Fog, and volumetric fog activated. I made the DoF very hard and without transition to check if the line changed between projections.

Perspective:
![imagen](https://github.com/godotengine/godot-proposals/assets/64601424/aa68ab2c-30e3-4612-8d48-a2152b79e47d)

Orthographic:

![imagen](https://github.com/godotengine/godot-proposals/assets/64601424/2c78ea42-29c3-4347-8ba4-53aee095798e)


The only difference i'm able to notice is with volumetric fog.  A shadow appears on the left side.

**Comment by ruanrothmann** [comment]
Usually my fog is dark grey, I've turned it green here for visibility's sake.

This is my scene normally:
![image](https://github.com/godotengine/godot-proposals/assets/37209327/206bbf56-5f7b-470c-9f23-155b3dfc4317)


I click this to get an orthographic view from the top:
![image](https://github.com/godotengine/godot-proposals/assets/37209327/fe9a9cb8-de67-4160-96aa-a23d58d716f1)

Which makes the scene look like this:
![image](https://github.com/godotengine/godot-proposals/assets/37209327/b45a4150-c340-4bfa-ba6b-4f7bece7ef47)

Disabling fog:
![image](https://github.com/godotengine/godot-proposals/assets/37209327/6703b054-86f2-4dd1-90e3-d41c11316915)

FWIW, Fog settings:

![image](https://github.com/godotengine/godot-proposals/assets/37209327/a689f22e-abdf-4cc7-8c39-409354a567eb)

Similar issue with DOF:

![image](https://github.com/godotengine/godot-proposals/assets/37209327/e8b7b4cc-0030-4da0-b78c-5c7a17d2f739)

**Comment by AThousandShips** [comment]
How does it look without cranking the fog density up?

**Comment by ruanrothmann** [comment]
Density at 0.001:
![image](https://github.com/godotengine/godot-proposals/assets/37209327/5ddebf7d-f396-4649-a062-000dd50e1894)

To illustrate how low the fog density is, see the distant piece of geometry entire unobscured:
![image](https://github.com/godotengine/godot-proposals/assets/37209327/d6a905d5-cf43-456e-964d-f0e461b7f00f)

**Comment by AThousandShips** [comment]
You will have to tweak it for different contexts, as usual? As you can see it's not useless or impossible to work

**Comment by Calinou** [comment]
To me, this sounds like this should be an editor setting rather than something that always affects orthogonal cameras. You may want to temporarily disable fog while in perspective mode too.

**Comment by ruanrothmann** [comment]
> To me, this sounds like this should be a button in the editor rather than something that always affects orthographic cameras. You may want to temporarily disable fog or depth of field while in perspective mode too.
> 

I agree. IMO the best way of addressing this could be to give these buttons some sort of functionality when the scene does already have a WorldEnvironment:

![image](https://github.com/godotengine/godot-proposals/assets/37209327/a4727db2-7b76-4740-99bf-2289f77f3f7a)

Currently, if you do not have a directional light or WorldEnvironment, you can enable a test one by clicking those buttons, but the buttons are nonfunctional if you do have either of those in the scene. It is actually useful to sometimes be able to turn off WorldEnvironment and lighting as a whole in the Scene View, in order to clearly see what is actually going on in the scene. For instance, if you are working on a of horror game where most often there is only one light source, it is hard to get an overview of what's going on in the scene, without continually tweaking those values. Unity has a similar feature that we use a lot when editing levels.

![image](https://github.com/godotengine/godot-proposals/assets/37209327/d9f0cdb4-6399-45ed-bf76-fdffef4a62fd)


> PS: Another way to make depth of field only effective during gameplay (or camera preview) is to add the CameraAttributes resource to the Camera3D node instead of the WorldEnvironment node. I strongly recommend doing this. This can also be done for the Environment resource itself (for fog) but it may impact LightmapGI baking, since the light baking nodes won't automatically "see" the Environment used by the camera.

The issue for this workaround is that the camera rig might be shared between scenes. For instance, if you are making an FPS game, you might have indoor and outdoor levels, but one Player scene to which the camera is attached.

**Comment by yosoyfreeman** [comment]
> Density at 0.001: ![image](https://user-images.githubusercontent.com/37209327/279968424-5ddebf7d-f396-4649-a062-000dd50e1894.png)
> 
> To illustrate how low the fog density is, see the distant piece of geometry entire unobscured: ![image](https://user-images.githubusercontent.com/37209327/279968748-d6a905d5-cf43-456e-964d-f0e461b7f00f.png)

Thanks! i see the problem now.  I was using a preview of a 3D camera with ortographic projection, which takes the position of the camera into account, so when i change between projections the effects looks the same. The issue for me is the difference between a "real" camera and the 3D viewport. Seems to me that the 3D viewport in orthographic mode does not have a "position" but is a infinite projection downwards, only allowing you to change the zoom. 

So, yo don't really need to hide the effects on camera previews, which will work good. The "problem" is how the 3D viewport handles it. So is a viewport specific issue.

**Comment by ruanrothmann** [comment]
> So, yo don't really need to hide the effects on camera previews, which will work good. The "problem" is how the 3D viewport handles it. So is a viewport specific issue.

Yes, sorry for lack if clarity, 100% a viewport issue.
