### ISSUE TITLE
Readd support for 2D isometric lighting and shadows by exposing `LIGHT_VEC` or `SHADOW_VEC`

### ISSUE THREAD

**Issue by just-wasted** [godotengine/godot-proposals#8339]
### Describe the project you are working on

2d isometric

### Describe the problem or limitation you are having in your project

Projecting shadows on isometric walls seems unpossible

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In the Godot 2.1 Isometric Lighting demo LIGHT_VEC was used to correct shadow on walls. This didn't work on Godot 3 but SHADOW_VEC got introduced to help with this. It looks like there is no way to achieve this in Godot 4. 
I don't know if re-implemention of SHADOW_VEC would be the right way or an enhancement of the fragment built-in SHADOW_VERTEX to further modify shadows.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

pass

### If this enhancement will not be used often, can it be worked around with a few lines of script?

i don't think that would be possible

### Is there a reason why this should be core and not an add-on in the asset library?

enhances the built-in lighting system

discussion on the subject https://github.com/godotengine/godot-proposals/discussions/8298#discussion-5793462

**Comment by just-wasted** [comment]
![grafik](https://github.com/godotengine/godot-proposals/assets/67445572/c6dc2698-fbff-44fc-916e-17bddb31f1ce)

ok turns out it was just me being stupid :D 

210.0 is the pixel position from view-port top, 410.0 from view-port left border.
I think this can be closed, `SHADOW_VERTEX` can do what i need.

**Comment by Calinou** [comment]
Closing per the above comment. I'll keep this in mind if I get around to reimplementing the 2D isometric light demo in 4.x :slightly_smiling_face:
