### ISSUE TITLE
Change the value of default ' Visual script nodes ' so they are correct, on screen . . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#834]
**Describe the project you are working on:**
A Tomb Raider like game, with traversal . .

**Describe the problem or limitation you are having in your project:**
Some of the visual script boxes say, they have a value, of ' false ', when it really is ' Null ' . . It's also in the inspector, when creating an ' Action ' node box, it says the value is the ' top ' value, like the latest input key or, movement, but the box is really ' Null ', also in the inspector . . . I think when making an ' Equals ' box, that takes ' Any ', and one puts a boolen in it, one can add a ' value ' by clicking it, just the box, without creating new variable, and by default it says ' False ', when doing that . . . But, it's really ' Null ', and it creates bugs, the box doesn't work, like it looks as . . . Could one change that, so if a box has a null value, it says ' Null ', on the screen canvas, instead of a value, it doesn't have, in it . . . :( :( <3

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Well, the boxes just need to show, what is really in them, like ' Null ' or, ' empty ', or so . . . Also, in the inspector, it should print what is really in it, so it makes sense, on the screen . . . Thank you . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Well, I hope it's been described properly, hope you can make sense of it, so the boxes on screen, show the actual value, instead of an incorrect one, at all times . . . . Thank you . . <3

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This is something needs to be done in the engine code, not by the ordinary user, I think . . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think everyone needs this, and not to look for a plug-in, to fix it <3

**Comment by jasperbrooks79** [comment]
Here's an image, when adding a ' Boolean ' to a Equals box, that takes any, it makes a ' Click ' box, where one can set it True or, False . . . It looks default, as if it is in False mode, but it actually contains ' Null ', that gives errors, when running it, hope you can look at it, thank you <3

![2020-05-13 1614](https://user-images.githubusercontent.com/61069740/81823763-f1747280-9534-11ea-8bdd-4dc49ead8aa8.jpg)

**Comment by Jummit** [comment]
This is a bug: godotengine/godot#27611

**Comment by groud** [comment]
ok, closing as this is not feature request then.
