### ISSUE TITLE
Add support for generating project documentation - i.e., a project custom class wiki

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot-proposals#8352]
### Describe the project you are working on

An open-source software planetarium @ivoyager, intended to be a platform for other developers building games/apps in a realistic solar system.

### Describe the problem or limitation you are having in your project

Godot Editor's custom class documentation is wonderful, but users can access it only from the editor. Personally, I learn a lot about Godot functionality browsing the online class reference on my phone while riding the metro (or other activities I won't mention). I'd like to provide the same experience for users of our "platform" project or other such projects developed using Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I imagine either a "Cadillac" version or a "Pinto" version for this proposal.

In the Cadillac version, the editor provides an "Export Project Docs" button. The output is Markdown or another format [ready to add to a GitHub wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages) (for example).

In the Pinto version, GDScript access is provided to C++ docs internals (the `DocData` object, I believe) so that an editor plugin could be developed to do the above.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For the Pinto version, I believe all we need is a `Script.get_documentation()` method that returns a GDScript `DocData` object. I think from there it would be possible to develop a GDScript editor plugin to do everything else.

I don't understand the editor internals well enough to make competent suggestions toward the Cadillac version. Perhaps `DocTools` is already doing most of the work...?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so. As far as I can tell, the internal C++ `DocData` is not accessible to GDScript and its generation could not easily be reproduced.

### Is there a reason why this should be core and not an add-on in the asset library?

Possibly the "Cadillac" version of this proposal should be an editor plugin (which I'd be eager to make!). But I'd need GDScript access to `DocData` to do so.

**Comment by dalexeev** [comment]
There is `--gdscript-docs` command line option, see [the docs](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html).

**Comment by charliewhitfield** [comment]
> There is `--gdscript-docs` command line option to dump XML files, see [the docs](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html).

Ah! I thought I looked everywhere, but did not think of command line options. I wonder if that renders this proposal moot? I'll either close the proposal or edit to take this into account (I guess my Cadillac version is still valid).

**Comment by charliewhitfield** [comment]
In light of above, I'm closing the proposal. I wish the docs were in Markdown (or some other format ready for GitHub wiki) but that's a topic for a different proposal.
