### ISSUE TITLE
Restore editor window size and position between sessions

### ISSUE THREAD

**Issue by saminton** [godotengine/godot-proposals#8358]
### Describe the project you are working on

Concerns the editor's behaviour and is not project specific.

### Describe the problem or limitation you are having in your project

I work with a big monitor and I much prefer using a split view, with Godot editor on the left and a code editor (either the built in, or external) on the right. Currently opening a project or simply reloading the project will reset the Godot editor window to fill the entire screen.

I am using macOs so this may be a mac only issue.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Considering that things like `@tool` require a reload, crashes are still pretty common and the editor slows down after time and frequently requires a reload, it become very tedious having to replace the window each time.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Opening Godot should restore the previous window size and location when opening or reloading a project.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This should be native behaviour and not require a plugin.

### Is there a reason why this should be core and not an add-on in the asset library?

This is the default behaviour for any other application on mac or windows.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/7223.

**Comment by Shigewara** [comment]
I use windows 10.

Yes, I really need this. Every single time I relaunch my project it starts with me either moving the entire window from my first monitor to the second, then resizing the project window to my preferred size. Or when only using one monitor just the resizing of the window.

**Comment by AdriaandeJongh** [comment]
Just wanted to leave a big +1 here. I have an ultra widescreen monitor _and_ second monitor, so Godot opening in full screen is a silly exercise in window resizing _every time_.

I'm not a fan of making this project specific because regardless of opening project A or B, my monitor setup and therefore my window management isn't necessarily different.

**Comment by zsolczai** [comment]
This! One thing I dig about Godot is the speed at which you can work vs UE and others. This nonstop repositioning is tedious especially with task specific monitor setups.

**Comment by Calinou** [comment]
@zsolczai Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by m21-cerutti** [comment]
Something that I would like also is to remember the screen where it was (even more if it was maximised). And have some guards. I frequently switch my screen disposition and godot options for choosing is quite static to the current disposition I am in. Just moving and save it until I re-move would be a better UX.

Also would be better to save float windows disposition, where I have my scene on one screen and code editor on the other.
Maybe with this change we don't need anymore the EditorScreen option.
![image](https://github.com/user-attachments/assets/dca705a7-e4ba-47c9-8e14-c8afdc3d9629)

**Comment by danijmn** [comment]
Shouldn't this also be the default behavior for exported projects?

**Comment by tetrapod00** [comment]
@danijmn My guess is that it might require a different implementation than the editor version, and it also seems like something Godot can't necessarily make assumptions about, since each game or application might want slightly different behavior.

I'd suggest opening a separate proposal to discuss that, since this one is already closed as implemented.

**Comment by ChildLearningClub** [comment]
Hi, this was working out of the box in I believe it was 4.4 dev 4. In dev 5 and now also dev 6 the editor always opens to full screen.  I don't recall changing anything in settings and I have "Restore Windows on load" and  "Remember Window Size and Position" both set to on. Is there something that I'm missing? I'm using Windows 11.

**Comment by Calinou** [comment]
> Shouldn't this also be the default behavior for exported projects?

This is being tracked in https://github.com/godotengine/godot-proposals/issues/10625.
