### ISSUE TITLE
Add an "Expand Branch" functionality to Remote Tree

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot-proposals#8359]
### Describe the project you are working on

SVG editor

### Describe the problem or limitation you are having in your project

I want to look for a node deep in the remote tree and...

https://github.com/godotengine/godot-proposals/assets/85438892/5432d23b-8c07-41ef-94d0-004b6d40cceb

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

An Expand Branch button, like for the local tree.

![image](https://github.com/godotengine/godot-proposals/assets/85438892/7a89a1f3-b3be-4f80-ac86-80835059b4b9)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's about the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

It's about making the editor usable.

**Comment by KoBeWi** [comment]
Shift-Click the expand arrow.
