### ISSUE TITLE
Make "Open Dominant Script on Scene Change" disabled by default

### ISSUE THREAD

**Issue by NatGazer** [godotengine/godot-proposals#8372]
### Describe the project you are working on

3D and 2D particle simulator for physics showcase

### Describe the problem or limitation you are having in your project

The only place I feel Godot looks unpolished is the Scripts List. What I personally felt when I started learning, was how messy the script list became after some time, new scripts are suddenly opened, with no apparent reason, and the script list starts growing bigger and chaotic.

Turns out that's because every time you select a new scene, in the scene tab, Godot opens the script of the topmost scene node. Fortunately, this can be disabled in `Editor settings -> Text Editor -> Behavior ->Open Dominant Script On Scene Change`, and after I discovered this, it became so much cleaner and pleasing to manage scripts.

Back in 2016, these gentlemen thought the same (https://github.com/godotengine/godot/issues/3638):
![image](https://github.com/godotengine/godot-proposals/assets/67602607/50730ae5-6d07-4fc8-9af0-b0f531ae2553)

My proposal is to make this option disabled by default or at least close the automatically opened scripts as proposed in the closed PR https://github.com/godotengine/godot/issues/3638. This way there's no tendency of the Script List growing larger over time. I'm just thinking about new users experience!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make "Open Dominant Script on Scene Change" disabled by default

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, it might just be a simple boolean value change

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often

### Is there a reason why this should be core and not an add-on in the asset library?

It's a simple modification

**Comment by AThousandShips** [comment]
That was proposed previously in:
* https://github.com/godotengine/godot-proposals/issues/8131

Off topic for this proposal
