### ISSUE TITLE
Add editor setting flag to disable the confirm dialog when starting a new track on the animation player

### ISSUE THREAD

**Issue by securas** [godotengine/godot-proposals#8379]
### Describe the project you are working on

Currently, whenever creating a new track on the animation player the user is presented with this dialog window.
![image](https://github.com/godotengine/godot-proposals/assets/2881755/ea147003-3812-4ade-aff8-9416bcf571b2)

It is reminiscent of the previous dialog on Godot 2.x for the same purpose.
Despite the indication that shift can be pressed to disable it, it would be substantially better to introduce a flag in the editor settings that would disable the dialog permanently.

### Describe the problem or limitation you are having in your project

Every time that a track is created, the user must either press shift, which is easily forgotten, or confirm the creation of a new track.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

An editor setting to permanently disable the dialog window, similar to what was performed in earlier versions of Godot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A flag can be used to turn on/off the dialog confirmation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is an editor feature. Hence there is no script workaround.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by Calinou** [comment]
- See https://github.com/godotengine/godot/pull/54524.

**Comment by securas** [comment]
The editor settings will not be overcrowded by this setting. It was there originally placed for a reason which is not considered in [https://github.com/godotengine/godot/pull/54524](url).

The fact that one can press shift to avoid the setting is not forgotten. However, the fact that one needs to press the shift key is easily forgotten. Once again, the dialog window was made option in 3.x for lack of practicality and poor UX.
