### ISSUE TITLE
Get Node2D Under Cursor

### ISSUE THREAD

**Issue by TushieSushies** [godotengine/godot-proposals#8382]
### Describe the project you are working on

A topdown 2D game

### Describe the problem or limitation you are having in your project

There's no built-in way to get the topmost node for mouse interactions

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A function get_viewport().get_node_under_cursor() would eliminate the need for a raycast2D node constantly following the mouse

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

using get_viewport().get_node_under_cursor() returns the topmost Node2D under the cursor

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by having a raycast2D node follow the mouse cursor, but it's neither elegant or convenient as it leads to potential mistakes like raycast2d not colliding because on a different layer

### Is there a reason why this should be core and not an add-on in the asset library?

useful in many type of 2D games

**Comment by Stronkkey** [comment]
This isn't reliable as you might want to get all Node2D under the cursor instead of just CollisionObject2D.

**Comment by Sauermann** [comment]
As fas as I know (I might be wrong there), a `Node2D` has no associated area in the physics engine. What would be your suggestion for determining the area of a `Node2D`?

**Comment by thygrrr** [comment]
I think the proper solution here is to give every clickable/hoverable node a CollisionObject2D child, and have code properly refer to its parent as needed.

**Comment by TushieSushies** [comment]
> I think the proper solution here is to give every clickable/hoverable node a CollisionObject2D child, and have code properly refer to its parent as needed.

This is what I ended up doing.
I linked the Mouse Entered to a Signal Bus and that turned out to be the better solution
