### ISSUE TITLE
Add "scroll_visibility_changed" signal to ScrollContainer

### ISSUE THREAD

**Issue by Sooshiko** [godotengine/godot-proposals#8388]
### Describe the project you are working on

I want to manually set the margins of some things inside of a ScrollContainer based on which scrollbars are visible to do things like add padding between scrollbars and the ScrollContainer's content.

### Describe the problem or limitation you are having in your project

To do this, I need to set a script to each scroll container and check every _process to see which scrollbars are visible and change margins based on the result. This isn't terribly slow but it does add up quickly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are two possibilities (For example: add margins to the content of ScrollContainers that would add padding between the scrollbars and the content) but the one I'm proposing is to add a signal (because signals are great).

By adding a "scroll_visiblity_changed" that triggers everytime a bar is hidden/shown. All i need is to run the script when the scrollbars change.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You connect ScrollContainer.scroll_visibility_changed to a callable.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Honestly, the more signals the better.

### Is there a reason why this should be core and not an add-on in the asset library?

Cannot be done with addons.

**Comment by KoBeWi** [comment]
You can get scrollbars using `get_h/v_scroll_bar()` and connect to their `visibility_changed` signal.

**Comment by Sooshiko** [comment]
I implemented that and can confirm, it works. Now I feel silly.

**Comment by MewPurPur** [comment]
So can we close the proposal, then?

**Comment by Sooshiko** [comment]
Sure

**Comment by Sooshiko** [comment]
Looks like it.
