### ISSUE TITLE
Enhanced Polygon Editing: Multi-Point Selection and Modification in Godot

### ISSUE THREAD

**Issue by sandygk** [godotengine/godot-proposals#8392]
### Describe the project you are working on

I am developing a 2D top down shooter game in Godot, which relies on complex polygon shapes for collision detection and environmental design.

### Describe the problem or limitation you are having in your project

Currently, editing polygon shapes in Godot is time-consuming and inefficient because I can only select and edit one point at a time. This makes adjusting complex shapes, like terrain or intricate collision areas, a tedious process.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The enhancement I propose is a multi-point selection and editing feature for polygons in Godot. This feature would allow users to select multiple points of a polygon simultaneously and move them

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Imagine a tool within the polygon editor that enables a 'multi-select' mode. When this mode is active, users can click and drag to create a selection box, or hold a modifier key (like Shift) to add individual points to their selection. Once multiple points are selected, any transformations applied (via mouse or keyboard shortcuts) affect all selected points. This could be implemented as an extension to the existing polygon editing toolset in Godot.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

While it may be possible to create a script or an editor plugin for this purpose, it would probably be complex and not as seamlessly integrated as a native feature. Additionally, this functionality is likely to be broadly useful for a wide range of projects, making it a valuable addition to the core Godot engine.

### Is there a reason why this should be core and not an add-on in the asset library?

Integrating this feature directly into the core of Godot would ensure a smoother, more efficient workflow for all developers working with polygon shapes. An add-on might not be able to offer the same level of integration and ease of use, and having this as a core feature would make it more accessible, especially for new or less technically inclined users.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6397.
