### ISSUE TITLE
Better in-engine Ambient occlusion ( SSAO ) and destructible mesh / object . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#841]
**Describe the project you are working on:**
A Tomb Raider game, also joining a game jam, for a week, <3

**Describe the problem or limitation you are having in your project:**
I have looked at the SSAO in the engine, it even says in the documentation, that a baked AO map is a lot better . . My thought was, since it looks really nice, to try and make the engine's own SSAO better, in Vulkan, as well as other render parameters, or so . . . It's a really nice effect, and if the quality was improved, it would make all games look nicer, to the point where one wouldn't need AO maps, and could save memory, performance, that way . . . Also, in many games there are destruction, of objects, meshes . . . Maybe one could make a node, ' DestructibleMeshInstance ', with basic functionality, since it adds to games, when that can happen, like driving through a wall, or so . . This is just a suggestion, and I know it's very hard to do, but those are two big WISHES, for the engine . . I HOPE it's okay to post it here, it would just be really nice, like a dam breaking, or driving through a stone fence . . I will keep it short to not waste your time, thank you . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Well, the in-engine shadows currently look blurry, I THINK they will get better, for Vulkan and, 4.0, but I hope SSAO also gets better, if possible . . . And, some sort of destructible mesh, like for crates, walls, would be a nice node, it's in many games, even engines, but it might be difficult . . . :O

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Well, I just HOPE the SSAO will get more detailed and, maybe precise, in 4.0, with Vulkan, that it doesn't get neglected, as AO REALLY makes a game look nice, when running . . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I can't code this, it's not something I can do, as a beginner, it's just two features, I would really like, for my own games, to be clear I'm super-happy with what I see in Godot 4.0, global illumination, Vulkan, all the stuff I see, the decals <3 Just wanted to add these things, to the list, they are very important, for me, to make the games ' that ' extra nice . . It might be VERY difficult, I know so little, sorry . . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
I'm not sure, I hope you know what to do with this, I'm NOT an expert of the engine, coding it, and ask perhaps a dumb question, all the same, thank you, for such an amazing engine, no matter what, I'm happy with where the engine is going, thank you <3

**Comment by jasperbrooks79** [comment]
I mean, in some games, you shoot a wooden crates, and it breaks, also a wooden door, like that, where it creates random breaks, in the mesh, at run-time . . Know you guys are pros, it would be a nice node, since it's common in games, maybe ice that breaks, when walking over it, so on . . Anyway, I'm a NOOB at the engine, and don't know how difficult this is, hope, it's okay . . .

**Comment by Jummit** [comment]
It's totally possible in Godot. Here is a text-based tutorial I made for it:
http://www.jummit.com/wp/2020/04/13/3d-destruction-in-godot-3-2/

**Comment by Calinou** [comment]
> Also, if this is very GPU / CPU intensive, maybe make some SSAO settings, with low, medium, high quality, so one can see how it works, and adjust performance, like so . . . :O <3 Thx

SSAO was already reimplemented in the `master` branch. There's an half-resolution setting you can enable in the Project Settings.

**Comment by Calinou** [comment]
Closing, as there should be *one* proposal per feature requested. Also, you need to further justify why mesh destruction needs to be part of the core engine rather than an add-on.

(Please don't open a proposal for SSAO, as it already has been reworked in the `master` branch. There's already #46 anyway.)
