### ISSUE TITLE
IAP for iOS in Godot 4.x

### ISSUE THREAD

**Issue by ultramarinebicycle** [godotengine/godot-proposals#8423]
### Describe the project you are working on

A mobile game that I want to export to Apple platforms, specifically iOS.

### Describe the problem or limitation you are having in your project

No first-party solution exists for implementing IAP on iOS.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Create a library/plugin that helps users create and test IAP, along with step-by-step documentation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Essentially [the same way as for Godot 3.x](https://docs.godotengine.org/en/stable/tutorials/platform/ios/plugins_for_ios.html#doc-plugins-for-ios). And also show common pitfalls.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not to the best of my knowledge.

### Is there a reason why this should be core and not an add-on in the asset library?

In-app purchases are pretty much a fundamental requirement in modern game development.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-ios-plugins/issues/47, as update requests don't need proposals.
