### ISSUE TITLE
Automatically add array item when dragged onto array

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-proposals#8428]
### Describe the project you are working on

Game

### Describe the problem or limitation you are having in your project

When an array is exported, it would be nice if one could drag an item onto the list, and have the size automatically increased by the number of items there were dragged.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This is more of a bells and whistles kind of thing for not having to press `Add Element` for every item you want to add to the list (or typing in the size in the input). Just drag, drop, done.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When you grab "x" items, and drag it to the area highlighted in red, it would automatically append "x" items to the array and fill them in with what was dragged (if they match the type).

![drag-drop-array](https://github.com/godotengine/godot-proposals/assets/1571806/fd702f78-dee5-47b1-b543-3cb55942cfda)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Probably not.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core functionality.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/8193.
