### ISSUE TITLE
Blender 4 Support

### ISSUE THREAD

**Issue by hr-98** [godotengine/godot-proposals#8436]
### Describe the project you are working on

A First person rpg.

### Describe the problem or limitation you are having in your project

Blender 4 is out but I have to keep Blender 3 installed for Godot. I really wanna try out the new Blender features.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Support Blender 4 too.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like Blender 3 import support.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Blender 3 support is core.

**Comment by bruvzg** [comment]
Do you have any issues with Blender 4 in particular? It seems to be working as is.

**Comment by hr-98** [comment]
Oh right it actually works in the latest version, sorry. In a previous version it said blender was too new, I assumed it didn't work in the new version because it still says blender 3 path in the settings. :sweat:

**Comment by AThousandShips** [comment]
We would need to verify there's no issues before changing the suggestion and details, or people will be confused if something doesn't work because we haven't done our due diligence on our end to ensure compatibility

**Comment by Calinou** [comment]
This is already implemented since 4.1.3 thanks to https://github.com/godotengine/godot/pull/81194, which also handles Blender 4.0 support.

If it doesn't work **after checking that it works with earlier Blender versions**, please open an issue on the main Godot repository.
