### ISSUE TITLE
Allow for arrays to be passed into annotations

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-proposals#8439]
### Describe the project you are working on

A form plugin.

### Describe the problem or limitation you are having in your project

```gdscript
const INPUT_TYPES = [
	"CheckBox",
	"CheckButton",
	"OptionButton",
	"Submit",
	"LineEdit",
	"TextEdit",
	"ItemList",
	"Slider",
	"SpinBox",
	"GraphEdit"
]

## Path to input control
@export_node_path(INPUT_TYPES) var input_path: NodePath
```
> Invalid argument for annotation "@export_node_path": argument 1 should be "String" but is "Array".

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow `Array[String] | ..String` to be passed into annotations

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See code above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

nope it's impossible to do this with code. In my example there's a workaround because it's a `const` anyways:
```gdscript
## Path to input control
@export_node_path(
	"CheckBox",
	"CheckButton",
	"OptionButton",
	"Submit",
	"LineEdit",
	"TextEdit",
	"ItemList",
	"Slider",
	"SpinBox",
	"GraphEdit"
) var input_path: NodePath
```

### Is there a reason why this should be core and not an add-on in the asset library?

It regards gdscript, not any specific project

**Comment by dalexeev** [comment]
It was previously possible to use a comma in string arguments, such as `@export_node_path("CheckBox,CheckButton")`, but we then added validation as this did not work correctly with `@export_enum` and `@export_flags` (although we could allow this mixing and handling it correctly).

I thought about this scenario, but there is an alternative in the form of the rest operator. If/when we add the syntax, you will be able to do `@export_node_path(...INPUT_TYPES)`. See also #1034 and godotengine/godot#82808.

**Comment by moritz-t-w** [comment]
Oh that does exist! I thought I had read somewhere that it does not. Thanks, that's the solution to this I think. Can't imagine a scenario where this wouldn't be the fix.
