### ISSUE TITLE
Facilitate class documentation of project singletons (or, allow hyperlinks to class docs using arbitrary text)

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot-proposals#8441]
### Describe the project you are working on

A solar system simulation @ivoyager that is distributed as a set of editor plugins.

### Describe the problem or limitation you are having in your project

Links to project or plugin singletons in class documentation are awkward. My plugin has an autoload singleton 'IVGlobal'. Unfortunately, I can't link it in class documentation using `[IVGlobal]`. Instead, I have to link it throughout class documentation using `["addons/ivoyager_core/singletons/global.gd"]`. Or I can give it `class_name IVGlobalSingleton` and then link it with that name. But that's still clunky. It's especially problematic for _this_ class, as I need to reference it very often in other class docs.

Compare with core singletons, which can be linked, e.g., `[PhysicsServer3D]`. [Edit: You can't do this in GDScript because you can't assign class_name with the same value as the autoload name.]

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It should be possible (by some means) to generate a link in class docs that has the name of the autoload and links to its class doc. In particular, this would improve documentation for plugins that use singletons.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Option 1: Allow a singleton to have class_name that is the same as its autoload name. This currently throws error: "Class XXXX hides an autoload singleton". (I have no clue whether this is technically feasible.)

Option 2: Add tag `[autoload <AutoloadName>]` to the docs system. This would resolve as a link <AutoloadName> in the docs (with the autoload name, not the class name) and point to the autoload class doc (whatever its actual class name).

Option 3 (most general): Analogous to the `url` tag, which does work in class docs, we could have a tag that allows linking to class docs using arbitrary text. This could be: `[class=<ClassName>]arbitrary text[/class]`.

My personal preference would be both 2 and 3. Option 2 is "cleaner" for solving this specific problem. However, option 3 could be used in many other cases (well, hyperlinks are like that).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It's core function, not accessible to GDScript.

**Comment by YuriSizov** [comment]
> Compare with core singletons, which can be linked, e.g., `[PhysicsServer3D]`.

Built-in singletons are registered classes of the same name. It would be the same as using the `class_name` keyword in your script.

**Comment by charliewhitfield** [comment]
> Built-in singletons are registered classes of the same name. It would be the same as using the `class_name` keyword in your script.

Yes, but the difference in GDScript is that we can't assign class_name with the same value as the autoload name.

**Comment by dalexeev** [comment]
* See also #7722.

**Comment by LunaticInAHat** [comment]
> > Built-in singletons are registered classes of the same name. It would be the same as using the `class_name` keyword in your script.
> 
> Yes, but the difference in GDScript is that we can't assign class_name with the same value as the autoload name. Hence, it's not possible to link to an autoload using the name that is actually most useful.

That's currently the case, but does it need to stay that way? Eliminating this restriction seems like it would result in the cleanest and least-exceptional syntax, to me.
