### ISSUE TITLE
Highlight error lines in minimap

### ISSUE THREAD

**Issue by miv391** [godotengine/godot-proposals#8444]
### Describe the project you are working on

I'm using GDScript and I'm using both Godot editor and vscode to write code.

### Describe the problem or limitation you are having in your project

Error lines are quite difficult to see in Godot's code minimap. In vscode errors are highlighted so that it is easy to see where the errors are and to jump to the error location using the minmap.

This is how vscode looks:
![kuva](https://github.com/godotengine/godot-proposals/assets/49998025/e830227e-b14c-420b-8aec-8d4691c3c419)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Drawing the error lines in the minimap with a brighter color would make the error lines more easily seen.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1) If the line's background color is something else than the default background color, let's use alpha 1.0 instead of multiplying the alpha by 0.6 as is done with normal lines.

2) A new editor setting is added: Text Editor / Appearance / Minimap / Highlight Errors. Default value would be true as I believe that most users would like to see errors highlighted. If this setting is changed to false, error are not highlighted and they would look as they look currently.

The next picture shows the current minimap with default and light themes, then a minimap with highlighted errors with the same themes.

![kuva](https://github.com/godotengine/godot-proposals/assets/49998025/b092b6ca-6d4f-4bce-bb47-eefa1e822b08)

If this enhancement is approved, I can implement this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be done with an add-on.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/8403.
