### ISSUE TITLE
Remember search string in Find in Files dialog

### ISSUE THREAD

**Issue by miv391** [godotengine/godot-proposals#8448]
### Describe the project you are working on

I'm making a game with GDScript.

### Describe the problem or limitation you are having in your project

How **Find** (Ctrl-F) works:
1. select some text (eg. "Foobar") in code editor
1. press Ctrl-F
1. -> Find UI opens, the selected text ("Foobar") is the default selection string.
1. close Find UI
1. clear selection ("Foobar" is no more selected)
1. press Ctrl-F
1. -> Find UI opens, the previously selected text ("Foobar") is still the default search string

Replace (Ctrl-R) works in the same way.

I like how this works (step 7 specifically) and apparently I'm not alone as at least vscode works just the same way.

#### The actual problem

How **Find in Files** (Ctrl-Shift-F) works:
1. select some text (eg. "Foobar") in code editor
1. press Ctrl-Shift-F
1. -> Find in Files dialog opens, the selected text ("Foobar") is the default selection string.
1. close Find in Files dialog
1. clear selection ("Foobar" is no more selected)
1. press Ctrl-Shift-F
1. -> Find in Files dialog opens, but **default search string is now empty**. The operation logic is different than it is with the Find operation.

Replace in Files works in the same way.

This is bad as quite often I would like to redo the same search or maybe modify the search string a bit. And if I can once again use vscode as a reference, it uses the same operation logic in Find in Files as in Find. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose that the Find in Files and Replace in Files are changed so that the search string is not cleared when the user has nothing selected in the code editor. Find and Find in Files would then use the same operating logic.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The implementation seems to be quite simple, just two ifs to prevent clearing the search string.

`script_editor_plugin.cpp`:
```c++
void ScriptEditor::_on_find_in_files_requested(String text) {
	find_in_files_dialog->set_find_in_files_mode(FindInFilesDialog::SEARCH_MODE);
	if (text != "") {
		find_in_files_dialog->set_search_text(text);
	}
	find_in_files_dialog->popup_centered();
}

void ScriptEditor::_on_replace_in_files_requested(String text) {
	find_in_files_dialog->set_find_in_files_mode(FindInFilesDialog::REPLACE_MODE);
	if (text != "") {
		find_in_files_dialog->set_search_text(text);
	}
	find_in_files_dialog->set_replace_text("");
	find_in_files_dialog->popup_centered();
}
```

However, there is still the replace string used in the Replace in Files dialog. Currently both the find string and the replace string are cleared every time the dialog is opened. In the above code replace string is still cleared. My opinion is that the best option would most likely to be not to clear the replace string ever. I think it's more likely that the user wants to reuse the replace string than the previous replace string causing any trouble.

If this enhancement is approved, I can implement this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No it cannot be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be done with an add-on.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6340.

> If this enhancement is approved, I can implement this.

Feel free to open a pull request for this :slightly_smiling_face:
