### ISSUE TITLE
Ternary statement or other single line if/else statement

### ISSUE THREAD

**Issue by Terrence-Holmes** [godotengine/godot-proposals#8462]
### Describe the project you are working on

Relevant to all projects

### Describe the problem or limitation you are having in your project

Setting a variable to 1 of 2 possibilities depending on a given 'if' statement requires 4 lines of code and could easily be shortened to just 1 with the use of ternary statements.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add ternary statements or another single line if/else statement that returns result #1 if the given argument is true, and result #2 if false.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the example code given, the int variable titled 'result' will be set as 3 if 'argument' is true, and 6 if 'argument' is false.
`var result : int = argument ? 3 : 6`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This syntax is completely optional and will only serve the purpose of making code easier to write, and cleaner to read.

### Is there a reason why this should be core and not an add-on in the asset library?

Ternary statements are a useful tool that all programmers should have immediate access to without having to jump through the hoops of downloading an add-on for something as simple as a single line if/else statement.

**Comment by Calinou** [comment]
This is already implemented in GDScript as described above. C-style ternary operator syntax would be ambiguous in GDScript (as `:` is already used to delimit some statements like `if ...:`).
