### ISSUE TITLE
Change % and $ from get_node() to get_node_or_null()

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot-proposals#8465]
### Describe the project you are working on

Application

### Describe the problem or limitation you are having in your project

Sometimes when functions get called on initiation (properties for example) or if nodes have been freed you get this error:
`script.gd:10 @ delete_all(): Node not found: "%UniqueNode" (relative to "Control")`

So we can try to solve it, like preparing the function with `if not %UniqueNode: return` or `if %UniqueNode == null`. This doesn't work and will generate the same error. This is the intuitive first solution I think most people will try.

However, you can do `if not get_node_or_null("NodePathToUniqueNode"): return`. This check will work.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

My suggestion is to default % and $ to be the shorthand for `get_node_or_null()` instead of `get_node()`. That way we can use % without having to fall back to the node path.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`if not %UniqueNode: return`
or
`if %UniqueNode == null: return`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

`get_node_or_null()` is available to use

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by Calinou** [comment]
Closing due to lack of support (see reactions on OP). This change would also break compatibility with existing projects, and it's not always a net win in terms of usability (silently failing when the result is `null` can lead to difficult-to-track bugs).
