### ISSUE TITLE
Control Nodes scrolling for phones that isn't limited to scrollbars 

### ISSUE THREAD

**Issue by Sectonidse** [godotengine/godot-proposals#8482]
### Describe the project you are working on

Ultimate File manager with editors (RobotFetch)

### Describe the problem or limitation you are having in your project

When using Control Nodes that has items that goes out of the node sizes, the scrollbar will appear to help find the needed item. However, on mobile devices, you have to use scrollbars instead of swiping to scroll, which leads to users doing this and accidentally activating the item.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By adding this enhancement, users will be able to scroll as they used to do.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This enhancement should add signals such as `tap_holding` and `tap_released` and the touch scroll itself with sliding on release. Also why not add `scroll` (scroll position) property?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As i tried to do it in GDScript, it's impossible to do. You have no way to scroll the contents of Node and even check if touch holds the Node.

### Is there a reason why this should be core and not an add-on in the asset library?

This will be useful for pretty much every game/program that plans to export for mobile devices.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/21137, as this is a bug.

**Comment by Sectonidse** [comment]
Just got Godot 4.2, it's still activates the item instantly on tap. Perhaps this is not a bug, but a way it was written. Buttons have 2 ways of activation: Instantly on click or by releasing it. Why not make this for ItemList?

Video showing that this still persists (Yes i tested it with my Touch screen monitor and sorry about bad quality)
https://github.com/godotengine/godot-proposals/assets/94748461/fdb21013-4912-48af-bc78-5738e072295e

**Comment by AThousandShips** [comment]
See the bug report linked above
