### ISSUE TITLE
Improve error message when Godot is unable to construct GDScriptInstance

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot-proposals#8488]
### Describe the project you are working on

I am building an addon to manage RPG data.

### Describe the problem or limitation you are having in your project

For optimal clean code, we addon developers like to use the `_init()` function as a custom constructor for objects, as it forces the user to always initialize an object:
```gdscript
class_name MyNode extends Node

var _value:int

func _init(arg:int):
   _value = arg
```
This works fine, especially for custom data structures that are not utilizing the scene tree. However, when adding a node to a scene tree and attaching the script above, Godot will spit out an error that is very confusing to people who never encountered it before:
```
_create_instance: Error constructing a GDScriptInstance.
```
While the above error is logical and makes sense (as Godot requires an `_init()` constructor to call `.new()`), it is irritating to users.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The error can potentially occur in multiple scenarios:

1. `_init()` function with arguments defined
2. script has a syntax error

This proposal aims to improve the error messages around these two scenarios.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When there are no script errors but a custom `_init(...)` function was defined, show an error like this:
```
Unable to create node /root/path/to/node/in/scene/tree: script does not define _init().
```
and in case of script errors:
```
Unable to create node /root/path/to/node/in/scene/tree: script has errors.
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No workaround sadly, apart from spending potentially hours trying to understand the issue (in larger code bases)

### Is there a reason why this should be core and not an add-on in the asset library?

As the original vague error is in core.

**Comment by HolonProduction** [comment]
> When there are no script errors but a custom `_init(...)` function was defined, show an error like this:
> 
> ```
> Unable to create node /root/path/to/node/in/scene/tree: script does not define _init().
> ```

The wording here will confuse users who didn't encounter the issue before. Not everyone will spot the difference between `_init(...)` and `_init()`. Let's be more precise:
```
Unable to create node /root/path/to/node/in/scene/tree: Can not init script, because _init(...) requires parameters. Consider adding default values.
```

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot-proposals/issues/5899

**Comment by LaraSQP** [comment]
This is still a problem in `v4.3.rc1.official`

Why require `_init()` and forbid `_init(...)` when we cannot overload methods? Something has to give.

I have 80 such "errors" in my project every time it runs, thereby making the identification of actual errors more difficult.

Could we at least have some sort of `@error_ignore("...")`?

**Comment by AThousandShips** [comment]
This should have been resolved by:
* https://github.com/godotengine/godot/pull/86999

The errors are clear now, for general discussion on this topic please open a new proposal with ideas for how to improve usability, this was about the error message

**Comment by LaraSQP** [comment]
> This should have been resolved by:
> 
> * [Improve error message when a GDScript instance fails to be constructed godot#86999](https://github.com/godotengine/godot/pull/86999)
> 
> The errors are clear now, for general discussion on this topic please open a new proposal with ideas for how to improve usability, this was about the error message

The non-error might be better reported but it is a non-error reported as an error.

I fail to see how this resolves the problem. Apologies.

**Comment by AThousandShips** [comment]
It's not a non-error, if you try to call a method that takes two arguments with anything else than two arguments it won't work

This proposal is about when you have an initializer that takes at least one argument (i.e. one without a default), but it's called with none, for example when loading a scene

Please read the proposal and check the issue and other linked issues

The behaviour this covers *is* incorrect use and *is* an error

If you find some specific error however (i.e. where it doesn't work as it should) please open a bug report [here](https://github.com/godotengine/godot/issues)

But regardless this proposal has been resolved and I think you are confused about what is talked about here

**Comment by LaraSQP** [comment]
> It's not a non-error, if you try to call a method that takes two arguments with anything else than two arguments it won't work

And yet it works.

```
var value : String

func _init( _value : String ):
  value = _value 
```

That code works and still gives an error message.

You are correct in that I am not concerned about the "clarity" of the error message. I want no error message at all.

**Comment by AThousandShips** [comment]
If you want no error write safe code, as seen in:
* https://github.com/godotengine/godot-proposals/issues/5899

Like so:
```gdscript
func _init(_value: String = ""):
    value = _value 
```
Or what ever default you want

This is well documented and now has a clear error message, the code you have there isn't valid if you want to use it for a `Node` being constructed in a scene

Does that solve your problem?

**Comment by LaraSQP** [comment]
> If you want no error write safe code, as seen in:
> 
> * [Inform the users that non-default-constructible nodes are a bad thing #5899](https://github.com/godotengine/godot-proposals/issues/5899)
> 
> Like so:
> 
> ```gdscript
> func _init(_value: String = ""):
>     value = _value 
> ```
> 
> Or what ever default you want
> 
> This is well documented and now has a clear error message, the code you have there isn't valid if you want to use it for a `Node` being constructed in a scene
> 
> Does that solve your problem?

Thank you for your patience. I might be able to rewrite my code to work with that.
