### ISSUE TITLE
Add "Affect Fog" to Sprite3D

### ISSUE THREAD

**Issue by Zinume** [godotengine/godot-proposals#8495]
### Describe the project you are working on

I'm working on an adventure game similar to The Last of Us.

### Describe the problem or limitation you are having in your project

Now it's time to add icons when you get close. I usually use a Sprite3D, but now that I'm using both types of fog, the Sprite3D is affected, resulting in a strange outcome. I've managed to work around this, but it would be great if it had the default function to ignore the fog.
![ss](https://github.com/godotengine/godot-proposals/assets/147895528/85c9e070-955f-497e-9a5e-9cc0799a2955)
I exaggerated the size of the icon for better appreciation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a boolean to enable or disable being affected by fog within the Flags category of the Sprite3D node.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![ss2](https://github.com/godotengine/godot-proposals/assets/147895528/af06c08c-dc88-4dec-b1ac-8a5cee175e64)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know how to create a shader that is not affected by different types of fog.

### Is there a reason why this should be core and not an add-on in the asset library?

The Sprite3D node has perfect functionalities for creating interactive icons in a 3D environment, among other uses. And now that in Godot 4, the use of different types of fog is more common, it should have this functionality to adapt to various current uses.

**Comment by AThousandShips** [comment]
Doesn't attaching a material and disabling fog on that work?

**Comment by Zinume** [comment]
> Doesn't attaching a material and disabling fog on that work?
> 
> Edit: this is 4.2 specific, but still applies
Oh oh! I just downloaded version 4.2, and you're right. I'm currently working on my project with 4.1.3, and that can be addressed in the future. Feel free to close my request, but if you find it helpful to have this option within the Flags category of the Sprite3D node, it would be very useful, especially since it already has a Billboard option just like materials. 
Many thanks, AThousandShips.

**Comment by Zinume** [comment]
Oh oh! I just downloaded version 4.2, and you're right. I'm currently working on my project with 4.1.3, and that can be addressed in the future. Feel free to close my request, but if you find it helpful to have this option within the Flags category of the Sprite3D node, it would be very useful, especially since it already has a Billboard option just like materials. Many thanks, AThousandShips.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/discussions/8418.
