### ISSUE TITLE
Allow the debugger panel to stay closed on play unless there are runtime errors

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot-proposals#8507]
### Describe the project you are working on

Any game

### Describe the problem or limitation you are having in your project

Every time I run the project, the debugger panel pops out, even if it doesn't have anything interesting to say. For example it opens when I only have a bunch of warnings that I don't care about:

https://github.com/godotengine/godot-proposals/assets/60579014/1c34ab19-eb00-419d-88d8-01c094b604a4

So every time I run the game I then have to manually close the bottom panel. This is especially distracting when I'm using the distraction-free mode

Also there's no way to close it with a hotkey, see #380

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There could be a dropdown in editor settings to change that behavior

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The dropdown could be:
"`Open Debugger Panel`": "`Always On Play`/`On Errors Only`/`On Errors or Warnings`/`Never`"

The dropdown could be in the Debugger section of editor settings:

![debugger](https://github.com/godotengine/godot-proposals/assets/60579014/d2df3d7f-5ce6-479b-849a-871617b1e235)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so

### Is there a reason why this should be core and not an add-on in the asset library?

QOL editor improvement, too basic to install an addon for this

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/380#issuecomment-1824728513.

**Comment by passivestar** [comment]
I found that if I click both of these it kinda solves the problem since it opens the output panel instead of the debugger and closes it on stop, making the bottom panel close (at least if there are no runtime errors), but the way of getting this behaviour isn't obvious

<img width="517" alt="image" src="https://github.com/godotengine/godot-proposals/assets/60579014/73cd90c9-b12b-458f-971f-740bec5a4814">

Since the debugger and the output panel kinda solve the same problem (they are both for debugging), maybe my proposed solution to add controls for debugger's behaviour doesn't really address the entire issue.

Maybe instead it could be something like:

`Editor Settings -> Run -> Bottom Panel`:

- `On Run`: `Open Output`/`Open Debugger`/`Do Nothing`
- `Close Bottom Panel On Stop`: `Always/If No Errors/Never`

This would solve multiple issues at once:
- It's straightforward how to get the bottom panel to close on stop (no need to open output)
- You'll be able to keep your current tab open, if it's Audio Mixer for example or whatever

Automatically opening the debugger on runtime errors probably makes sense and I'm not sure if that needs a checkbox in settings, at least I can't see a reason you wouldn't want that to happen

**Comment by Kyrio** [comment]
I second the solution of having a `Open Output`/`Open Debugger`/`Do Nothing` switch in the editor settings. In 3.x, when you disabled `Always Open Output on Play`, it would not open any panel (but surprisingly, it would close the debugger panel on Play if it was already open). In 4.x, you either get the Output panel or the Debugger panel.

What has been missing so far is a way to leave the currently opened panels as-is. For instance, if you've opened the Monitors tab of the debugger, as soon as you hit play the editor will switch over to Stack Trace (or Output if you kept the default setting). This can be a nuisance if you need to keep the monitors open for testing. If we had a `Do Nothing` setting, I would expect it to leave my workspace unaltered.

**Comment by RichardJECooke** [comment]
Is there a way to move the console at the bottom of the screen to a side panel instead? It's quite annoying always popping up

**Comment by Calinou** [comment]
> Is there a way to move the console at the bottom of the screen to a side panel instead? It's quite annoying always popping up

https://github.com/godotengine/godot/pull/36040 allows this, but you can't have a panel open at the bottom at the same time as it's moved to the side.

**Comment by RichardJECooke** [comment]
@Calinou sorry this says we should push Shift-F10 to move the output panel, but it does nothing?

**Comment by Calinou** [comment]
> @Calinou sorry this says we should push Shift-F10 to move the output panel, but it does nothing?

The pull request I linked hasn't been merged yet. Follow the steps in [Testing pull requests](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) if you wish to test that PR locally :slightly_smiling_face:

**Comment by KnIfER** [comment]
why not just "leave the currently opened panels as-is"  

Another scenario is  :  sometimes we need to reload the project, have to manually **OPEN** the OUTPUT panel  ...
