### ISSUE TITLE
Allow files to visually contain other associated files

### ISSUE THREAD

**Issue by heyitsdoodler** [godotengine/godot-proposals#8508]
### Describe the project you are working on

I have many scenes in my world with custom scripts that need to be associated with them.

### Describe the problem or limitation you are having in your project

Find better ways to organize my code while keeping related scenes and scripts together.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow files such as scripts to appear "within" other files.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Files will automatically be visually placed "within" other files based on their name.

Say you have a scene called "my_scene.tscn" then "my_scene.tscn.gd" would appear "within" it.

<img width="723" alt="Screenshot 2023-11-23 at 3 44 39 PM" src="https://github.com/godotengine/godot-proposals/assets/20733898/192b9f97-58b4-46f5-ad5a-d4b709805355">

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know if or how it would be possible to implement via an add-on.

**Comment by Calinou** [comment]
I feel this convention can backfire as OS file managers will not represent it. This means the FileSystem dock could essentially be allowed to disregard the underlying file structure, which can have implications. For instance, users may try to load a path of the form `res://Zombie.tscn/Zombie.tscn.gd` and find out it doesn't work.

**Comment by KoBeWi** [comment]
Thanks for the proposal! Consolidating in #3798
