### ISSUE TITLE
Add "Caster Mask" to Light3D shadow properties.

### ISSUE THREAD

**Issue by EMBYRDEV** [godotengine/godot-proposals#8509]
### Describe the project you are working on

Proceduraly generated first person shooter with dynamic lighting.

### Describe the problem or limitation you are having in your project

Light shadows are required to stop some light bleeding into different rooms, however these can be prohibitively expensive.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow the developer to utilise the render layer system to configure a light to only cast shadows using meshes on specific layers, allowing only the walls of the room to cast shadows.

Other meshes should still be capable of casting shadows from other lights such as the player's torch so universally disabling them is not a viable option. This allows us to configure each *light* to be as cheap as possible without bleeding.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/20043270/20beb24b-d888-4909-b1c6-7ca529ccfe8d)

Add a property similar to the `VisualInstance3D` layers property which will act as a mask for shadow casters.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It cannot be done as part of an addon.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/3606.
