### ISSUE TITLE
Create custom grap nodes feature similar GraphNode into game area, like any button, label, ...

### ISSUE THREAD

**Issue by catafest** [godotengine/godot-proposals#8518]
### Describe the project you are working on

I working on my one-man project with interactive issues. This project was started in Unity and now I use Godot. 
The main reason was my learning into development with shaders, VFX, C# and GDscript 

### Describe the problem or limitation you are having in your project

The player has to solve a puzzle and one of these types of puzzles can be connecting wires and cables and creating a _printed circuit board_ on a screen after seeing where it is placed in the game.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

possibility change to custom nodes for GraphNode to create games with nodes
at this moment: A container with connection ports, representing a node in a [GraphEdit](https://docs.godotengine.org/en/stable/classes/class_graphedit.html#class-graphedit).
this feature will bring the custom GraphNode feature into the node area like you add button, label, and viewer, and let users create wires, diagrams, etc 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If I can use images,2D, and 3D objects in the custom nodes for GraphNode then will more easier to build this  _printed circuit board_
One good example is this game; https://store.steampowered.com/app/504210/SHENZHEN_IO/it 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This improvement will be used often because it is related to graph theory and diagrams... and is used in all domains and will increase the number of developers using Godot.
Obviously, it will have to be reliable, known, and promoted.
This cannot be solved with a few lines of script, it will have to be implemented at the level of the Godot game and the team will need to create this feature like any button, label, or scene, PathFollow3D ...
For example, will be similar to GraphNode but will be in the game's visible area like any 2D or 3D connected elements with a logical implementation created from GraphNode.

### Is there a reason why this should be core and not an add-on in the asset library?

Because there is GraphNode implemented and from my point of view it would be simpler to rely on _it and possibly make a separate viewer or not with object classes with access to the interface_
I am not part of the development team, but I would consider this feature from the mentioned mods and I think it could solve a rather large area for those who want to use Godot as a development tool for applications not only for games.

**Comment by Calinou** [comment]
GraphEdit/GraphNode are intended to be used for non-game UI purposes, rather than creating games using it.

For a game, you should create a custom implementation that does just what you need. It doesn't need to be as complex as GraphEdit/GraphNode, both of which have grown to be pretty complex over time (and avoiding scope creep here is important).

**Comment by catafest** [comment]
Thank you. Best regards,
