### ISSUE TITLE
Establish a Dogfooding Initiative

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot-proposals#8524]
### Describe the project you are working on

I'm a professional Art Director working on AAA games and a regular Godot contributor through sample scenes, bug reports and proposals.

### Describe the problem or limitation you are having in your project

Blender is a very successful FOSS project in large part due to dogfooding (the act of using your own product to develop finalized projects, aka "eat your own dogfood").
This has been a priority for the foundation since 2006. Discoveries and developments in these short film projects have provided incredible benefit to Blender as a whole and directed the team towards better prioritization of features that artists will actually use.

Godot as of now has a profound lack of dogfooding.
Lead devs do sometimes embark on their own game development projects, but small-scale personal projects that may never see completion by a single dev is not dogfooding.
Your users making their own games and then reporting bugs or proposing features is also not dogfooding, since they have no control over the project at large and their suggestions or discoveries may be (and commonly are) lost in the Github deluge.

This lack of dogfooding is evident in my own testing; nearly every time I've pushed the engine to do something that wasn't trivial, it has either been impossible or was met with great friction.
Many of Godot's most basic systems (such as the asset workflow and lightmapping) are cumbersome beyond surface-level use cases, with very little meaningful control offered to users with no ability to simply implement the missing parts themselves.
Highly-demanded core aspects of the engine such as a terrain editor have been asked for time and time again without any implementation or prioritization, regardless of the fact that they are well-established crucial features in other engines.

These issues would become startlingly obvious and then quickly prioritized by the core dev team if projects were developed in-house with the explicit purpose of building games with Godot.
Many times I've used a particular feature and found it startlingly obvious that it was developed and implemented by an engineer who seemed unaware of how those features are already implemented to perfection in other engines, or simply unaware of how a game dev or artist would use that tool. Prioritized feedback based on undertaking real projects would make a world of difference.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The most obvious suggestion would be that the Godot Foundation initialize a studio or in-house team utilizing a portion of the engine's funding to develop shortform games or demos that test the engine against common indie or AA standards. These would not be full games, but simply a vertical slice or small contained project that represents a taste of what larger projects built in the engine might be like.
This team would be in tight communication with lead developers to help inform Godot's development priorities and identify areas in urgent need of care.

W4 Games would be another potential candidate for developing games in-house with the intent of developing games with the intent of furthering development, but since funding and priorities are external from the Foundation and are not guaranteed to be used for the purposes of furthering the engine itself I would advise against it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot-proposals/discussions/4694

**Comment by WickedInsignia** [comment]
> I thought it was already [taken care of](https://w4games.com/2023/09/19/an-insider-look-into-the-w4games-demo-team/)?

Huh, indeed it might be.
I thought I saw something like that around but wasn't sure. Colour me uninformed in this case 😅
