### ISSUE TITLE
Increase the default camera Z-far distance for better editor usability

### ISSUE THREAD

**Issue by salahchafai** [godotengine/godot-proposals#853]
**Describe the project you are working on:**

any 3d project

**Describe the problem or limitation you are having in your project:**

it's a very bad workflow when the gizmos (including the grid) disappear when you zoom a bit far away (i know you can change the view settings to make the distance higher but i still believe that no matter what the gizmos should never disappear)
 
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

the gizmos should never disappear when you zoom away even so far and that helps making working on games feel way better and more professional

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

i don't know

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

no

**Is there a reason why this should be core and not an add-on in the asset library?:**

because it must come by default and i don't know if that's even possible by an asset library

**Comment by TheFlamyy** [comment]
From my experience with 3d software (e.g. Blender) this is almost always the case. It could be that your models are too big. Because when working on my projects I never have issues with the gizmos disappearing

**Comment by salahchafai** [comment]
> From my experience with 3d software (e.g. Blender) this is almost always the case. It could be that your models are too big. Because when working on my projects I never have issues with the gizmos disappearing

zoom out a bit far and gizmos will disappear (ik it's not that important of a fix but it actually is for many of us)

**Comment by Calinou** [comment]
This will be solved by https://github.com/godotengine/godot/pull/33207 once it's merged.
