### ISSUE TITLE
Open file resurces in separate Inspector Window. Leave docked inspector for info about selected nodes in the scene.

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot-proposals#8534]
### Describe the project you are working on

A 3d ARPG game.

### Describe the problem or limitation you are having in your project

I'm at a point where I've created a lot of different resource classes for different purposes.
I save them in resource folder. 
Sometime I want to check what is saved in a resource. I want to edit data withing several resources at same time ( Maybe copying data, maybe just checking). 
And now when each resource opens only in main Inspector window it gets frustrating.

These are only few and I need to see data in some of these at same time to copy/match/check it etc.
![image](https://github.com/godotengine/godot-proposals/assets/3350340/4f71b1fb-8e4b-4db7-9d42-cf0d92388d8f)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Floating windows will speed up the work.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When user double clicks a resource in game folder it will be opened in new separate floating window or maybe even a tab.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No it can not. It should be and will be used often.

### Is there a reason why this should be core and not an add-on in the asset library?

Its core engine behavior.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/7459 (while it doesn't mention floating docks, it's implied that any new dock can be made floating as is done currently).
