### ISSUE TITLE
Allow `static enum` type

### ISSUE THREAD

**Issue by nonunknown777** [godotengine/godot-proposals#8541]
### Describe the project you are working on

On a scene transition system

### Describe the problem or limitation you are having in your project

I cant access a specific type of Transition singleton

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like that any class on my project has access to the Singleton's Transition specific type which is an enum called `SCENE`

this enum holds information for each scene:

```gdscript
enum SCENE {
	MAIN_MENU,
	LEVEL_1,
	LEVEL_2
}

const SCENES := {
	MAIN_MENU = preload("res://scenes/menus/scn_main_menu.tscn"),
	LEVEL_1 = preload("res://scenes/levels/Level1.tscn"),
	LEVEL_2 = preload("res://scenes/levels/Level2.tscn")
	
}
```

for example lets say that in level 1 I want to go to level 2, for that I have an Area2D called portal, and a script attached that has an export property that allow me to choose which scene I would like to go.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`@export var target_scene:Transtion.SCENE` currently this is not allowed, but it should show all the three options above written in the transition singleton

it should be possible by adding `static` to the enum variable in Transition.gd

### If this enhancement will not be used often, can it be worked around with a few lines of script?

yeah it can be workarounded if you copy the enum from Transition singleton to the portal class!

### Is there a reason why this should be core and not an add-on in the asset library?

not possible as far as I know

**Comment by Mickeon** [comment]
> I would like that any class on my project has access to the Singleton's Transition specific type which is an enum called `SCENE`

Why using `static` for this? It's not what the keyword is for in GDScript, or any other language. The closest thing I can imagine this proposal with is a `@global` annotation.

**Comment by HolonProduction** [comment]
I don't see why we need `@global` or `static` at all. Exporting an enum from another class seems like a "should just work" feature to me. Am I missing a reason why this could make problems?

**Comment by WeaverSong** [comment]
What version are you working on? Testing on 4.2 shows that it works without any keywords.

**Comment by Calinou** [comment]
Closing per the above comment. I can confirm this works as of 4.3.dev3, but only if `class_name Test` is added to your autoloaded script (the implicit global created by Godot won't work).

This particular issue may be considered a bug (which may have been reported on the main repository already), but `class_name` already functions to work around the issue.

**Testing project:** [test_class_name_enum.zip](https://github.com/godotengine/godot-proposals/files/14323735/test_class_name_enum.zip)
