### ISSUE TITLE
Ability to do `is not` when checking for type (e.g `weapon is not MachineGun`)

### ISSUE THREAD

**Issue by sandygk** [godotengine/godot-proposals#8547]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

when I need to check if a variable is not of a certain type I have to write it like `not (weapon is MachineGun)` because `weapon is not MachineGun` is not supported

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

it will improve readability

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

it's self explanatory

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

is an improvement on gdscript

**Comment by dalexeev** [comment]
Note that GDScript already supports the `not in` operator. From the point of view of binary/unary operators, it would be more logical to use `not is`, although this is probably incorrect for native English speakers. The good news that in 4.x `is` expects `TypeNode`, not `ExpressionNode`, so `is not` is also possible to implement.

**Comment by Mickeon** [comment]
The above, plus it is basically impossible to misinterpret for anything else even from the user perspective, which is a key goal for GDScript. In the case of `weapon is not Machine`, `not` can never be about negating a boolean, because `is` always requires a type.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/1319.
