### ISSUE TITLE
Allow for all editor modes to be able to select nodes in the viewport

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot-proposals#8563]
### Describe the project you are working on

![image](https://github.com/godotengine/godot-proposals/assets/105675984/e3c47256-d9fc-4475-876c-1aba3e556702)

### Describe the problem or limitation you are having in your project

Title

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I feel like it would improve workflow to allow the other modes to select objects in the viewport, because currently nothing happens, which I believe is counter-intuitive to what someone would expect. It seems more organic to just interpret a user clicking on a viewport object when nothing else is selected as their desire to select said object. I can't think of any downsides to allowing this.  

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

All modes allow selection of nodes in the viewport, but the gizmo maintains the current modes functionality. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I'm aware of.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a pretty fundamental change to the editor's core.

**Comment by YuriSizov** [comment]
I haven't looked into the reasons behind it yet, but would like to mention that I ran into this annoyance recently. It gets in your way very much, especially combined with the fact that modes keep changing when you press WASD keys in the flight mode (which is a bug but it also escalates this issue).

**Comment by ryevdokimov** [comment]
> I haven't looked into the reasons behind it yet, but would like to mention that I ran into this annoyance recently. It gets in your way very much, especially combined with the fact that modes keep changing when you press WASD keys in the flight mode (which is a bug but it also escalates this issue).

Yeah, I ended up binding 'Move Mode' to a different key for this exact reason.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/7834.

**Comment by passivestar** [comment]
Wanted to open this proposal myself, I tend to just do everything in select mode because it's too much of a hassle to constantly switch modes, so being able to select while not having **all** of the transform gizmos on screen will be much appreciated

**Comment by KoBeWi** [comment]
Related: #7691

**Comment by Magnesus** [comment]
Look for Inkscape for the best way to manipulate and select elements without constantly changing tools - you click to select and show handles that deal with scale, you drag to move, you click again to show handles dealing with rotation, and pivot point is another handle that you can move on the selected object - you do that all using one tool. Not sure why game editors use weird multiple tools and require switching them all the time for such a basic editor functionality.
