### ISSUE TITLE
Allow more Editor UI elements to be hidden. 

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot-proposals#8571]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Title

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The Godot editor itself can be a useful prototyping tool outside game development that doesn't necessarily need something externally ran. It would be nice to allow users to hide even more UI elements to reduce misclicks and clutter.

![image](https://github.com/godotengine/godot-proposals/assets/105675984/21b5627f-b4ec-430a-91ce-18382970e311)
 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add more stuff here, and possibly expose it to scripting as well.

![image](https://github.com/godotengine/godot-proposals/assets/105675984/155ba0ba-f0d3-4641-a06d-6058d29cbec7)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a fundamental change to the editor's core.

**Comment by passivestar** [comment]
Hi, if it's possible I'd like the options to disable these, thanks!

![gd](https://github.com/godotengine/godot-proposals/assets/60579014/c3243c59-da72-4cc4-9404-abfb234240f2)

**Comment by YuriSizov** [comment]
I think all elements highlighted here are core to the user experience and there is no good reason to add extra options to hide them. If you for some reason don't need them, you can make an editor plugin that hides them.

**Comment by ryevdokimov** [comment]
> I think all elements highlighted here are core to the user experience and there is no good reason to add extra options to hide them. If you for some reason don't need them, you can make an editor plugin that hides them.

Hi Yuri, I will investigate creating a plugin and will then close this issue. Thanks.

**Comment by RedMser** [comment]
> possibly expose it to scripting as well.

You can already use scripting to work with feature profiles. See the EditorFeatureProfile class, as well as the API added by https://github.com/godotengine/godot/pull/74382

For anything else, you can always dig into the UI via EditorPlugin like mentioned and manually hide the nodes you don't want.

**Comment by passivestar** [comment]
> you can make an editor plugin

@YuriSizov we can, but it seems to be [a bit of an uphill battle](https://github.com/GuyUnger/EditorMinimal/blob/main/addons/editor_minimal/plugin.gd) until editor nodes get [names](https://github.com/godotengine/godot-proposals/issues/1018) so we can easily find them. And [global addons](https://github.com/godotengine/godot-proposals/issues/831) arent a thing yet either, this addon will have to be copied into every project

**Comment by AThousandShips** [comment]
Those sounds all like reasons to *not* do this but do those instead of a stopgap solution here

**Comment by ryevdokimov** [comment]
> Those sounds all like reasons to _not_ do this but do those instead of a stopgap solution here

Agreed, and I will close this issue.

**Comment by YuriSizov** [comment]
@passivestar Yeah, I know I know 😭 While I can't promise you global plugins just yet, naming more key nodes in the editor tree is definitely something I want to do soon. Maybe even have a way to get a direct reference rather than rely on tree wrangling all the way.

**Comment by ryevdokimov** [comment]
In the meantime, this plugin was incredibly helpful to accomplish what I needed. 

[https://github.com/Zylann/godot_editor_debugger_plugin](url)
