### ISSUE TITLE
Animation Editor: base Zooming in / out anchoring on timeline marker

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot-proposals#8583]
### Describe the project you are working on

Classic arcade game.

### Describe the problem or limitation you are having in your project

I often have to zoom in / out when working with the AnimationPlayer's timeline. Right now, it's a bit fiddly because the zooming in / out is tied to the beginning of the timeline, so if the timeline is slightly longer (say more than 5 seconds) and I have to adjust some parts in the latter half, zooming in and out moves the currently visible part of the timeline way out of the screen so I have to scroll again just to find where is the part I'm working which just results in needless scrolling all the time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Zooming in / out should work like in Garage band on MacOS:
if the cursor (timeline marker) is visible on screen, anchor zooming in / out to the cursor.
if the cursor is not visible, anchor the scrolling to the beginning (or end, whichever is closer) of the timeline.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is what it looks like in Garage Band, I'm using a trackpad to scroll:
https://archive.org/download/ShowFlowFleetingWorld/画面収録%202023-12-04%208.01.32.mov

In Garage Band, when the cursor is not visible the zooming in / out is always tied to the beginning of the timeline, I think it'd be better if the anchoring could also switch to the end of the timeline in case this happens to be closer.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

???

### Is there a reason why this should be core and not an add-on in the asset library?

???

**Comment by Calinou** [comment]
Thanks for the proposa! Consolidating in https://github.com/godotengine/godot-proposals/issues/6204.
