### ISSUE TITLE
Play button for custom Scenes

### ISSUE THREAD

**Issue by gro-david** [godotengine/godot-proposals#8585]
### Describe the project you are working on

I am working on a farming rogue-like bullet hell game called Renegade Ranchers

### Describe the problem or limitation you are having in your project

I have set my game scene as my main scene so that i can test it in the fastest way possible. Since I started working on the main menu i, when i want to test the menu i have to switch to that scene and start it from there (since the game scene is still my main scene)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement the ability to add extra play buttons for running specific scenes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Extra button either in the project settings or somewhere around the play button for adding an extra play button to a specific scene where you need to select the scene.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I could be done with a plugin (which i would happily do), but have no real idea how to edit the default play button panel. If someone could point me in the right direction i would be more than happy to do it, :D

### Is there a reason why this should be core and not an add-on in the asset library?

No not really. Not all of the users would need this and if someone wants it they can just add the plugin.

**Comment by AThousandShips** [comment]
This seems like a lot of additional work and adding a feature to avoid having to just open the scene and run it, or change the main scene, I don't see the problem of just "having" to do that or it justifying adding a new feature

**Comment by YuriSizov** [comment]
> I could be done with a plugin (which i would happily do), but have no real idea how to edit the default play button panel. If someone could point me in the right direction i would be more than happy to do it, :D

You can't directly access the run bar, but you can add buttons next to it with [`EditorPlugin.add_control_to_container(CONTAINER_TOOLBAR, your_button)`](https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#class-editorplugin-method-add-control-to-container).

Then you can use [`EditorInterface.play_custom_scene`](https://docs.godotengine.org/en/stable/classes/class_editorinterface.html#class-editorinterface-method-play-custom-scene) to run an arbitrary scene by its filepath.

**Comment by YuriSizov** [comment]
@gro-david You first add your button to the toolbar, and then you can use `get_parent()` from your node.

**Comment by gro-david** [comment]
oh god... i should have thought of that. 🤦‍♂️

**Comment by KoBeWi** [comment]
This addon allows you to make a set of scenes for quick run/edit:
https://github.com/KoBeWi/Godot-Quick-Scenes
The scenes are in bottom panel, but you can select one of them as "main" and there is a dedicated shortcut for running too.

**Comment by gro-david** [comment]
I started developing my own  addon because i didnt see your message @KoBeWi. I think I will be finished sometime tomorrow. Then i'll send a link to the addon so that people reading this in the future can find it. Then i'll close this issue. Is this okay?
