### ISSUE TITLE
Save Images as PNG buffer

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot-proposals#859]
**Describe the project you are working on:** Drawing app that sends drawings via WebSocket.

**Describe the problem or limitation you are having in your project:** To get a PNG buffer (`PoolByteArray`) of an `Image`, you currently have to do `Image.save_png` and read the saved file with `File.get_buffer` into a `PoolByteArray`. It is currently not possible to get a PNG from an `Image` without saving it to disk first.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There should be something like `get_png_buffer` (and probably `get_exr_buffer`, too, to support all formats) which returns a `PoolByteArray` of the data that `save_png` saves to disk.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I saw that `Image` has `save_png_to_buffer` (https://github.com/godotengine/godot/blob/2fa795dea9b5ef672dd8ba75c26140e194d3f207/core/image.cpp#L2216) in current `master`, though it is not exposed to GDScript. It would be cool if that could also be backported to 3.x as it does not break existing games.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** No

**Is there a reason why this should be core and not an add-on in the asset library?:** The add-on also would have to save the file to disk.

**Comment by Xrayez** [comment]
I'm curious why do you need to get the PNG buffer specifically? Isn't `Image.get_data()` enough?

**Comment by timoschwarzer** [comment]
I'm uploading an image drawn by the user directly to a server. `Image.get_data()` is the raw, uncompressed image data which is not optimal for uploading (and further processing on the server).

**Comment by Xrayez** [comment]
It's totally possible to `PoolByteArray.compress()`, but you'd have to encode the original data size for it to be decompressed on the client/server, then `Image.create_from_data()`.

I wonder whether you also need some PNG-specific stuff like ancillary chunks? Perhaps index and palette data as well?

**Comment by Xrayez** [comment]
My assumption was that both server and client are both Godot instances, so yeah the native Godot image type is not suitable for your use case, this clarifies it.

From what I've seen `save_png()` only allows to store the essential image data. I was just wondering whether you needed to embed arbitrary data into the PNG with additional chunks, for example [Spore](https://gadgets.boingboing.net/2008/06/16/how-is-spore-hiding.html) stores creature data directly within PNG images, which is certainly not supported by Godot.

But yeah the proposal makes sense then. 🙂
