### ISSUE TITLE
Horizontal spinbox/optionbox

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#8599]
### Describe the project you are working on

Nothing right now, I'm waiting for the godot gui to mature

### Describe the problem or limitation you are having in your project

I needed to provide a way for controllers, touch, keyboard and mouse to interact with my game ui without it looking like a desktop interface.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a horizontal spinbox/optionbox which looks more native to a game console game ui

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://ask.godotengine.org/87874/horizontal-spin-box

Basicly it's a spinbox but it can accept other forms of data too. 
It works in such a way that when it's focused if your press left or right it selects the previus or next option.
Clicking on the left or right arrows focus it and also do the same thing.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would be used for a more traditional options menu.
I have tried to recreate this control with what we have available but it's not so easy.
The whole thing acts like a glorifyed spinbox except it can contain more then just ints or floats.

### Is there a reason why this should be core and not an add-on in the asset library?

Spinbox and scroll container's don't seem to work to create this type of control.
Since the whole thing is treated as one focus and most controls don't seem to automaticly accept focus from other controls it makes it hard to impliment.

Also spinbox already exists but while it might be able to modified to allow us to tell it where to place the previus and next buttons, it would need a whole new control for other forms of data like strings, scenes or colors.

Also I haven't tested it but I don't know if spinboxes have the ability to work without mouse either or specifying each focus nabour.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/5139.
