### ISSUE TITLE
Add range normalization functions for OpenSimplex

### ISSUE THREAD

**Issue by milesturin** [godotengine/godot-proposals#861]
**Describe the project you are working on:**
A project that uses noise to randomly generate terrain.

**Describe the problem or limitation you are having in your project:**
When using noise, it is common to use different value ranges for different things. For example, if you were using noise as a terrain heightmap, you could designate different kinds of terrain based on the noise value: values above 0.8 are snow, about 0.7 are mountain, above 0.4 are grass, etc. The issue is that OpenSimplex does not give consistent values between -1 and 1, its common range varies greatly depending on the octave settings. This makes it very difficult to do meaningful things with the noise.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I propose that OpenSimplex offers a setting that adjusts sampled values to better fit a consistent range.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The most common workaround for this issue is this:
```GDScript
var noise := OpenSimplexNoise.new()
noise.octaves = 4
noise.persistence = 0.8
noise.period = 17.0
noise.seed = randi()
var n_max := 0.0
for i in range(100000):
	var n = abs(noise.get_noise_2d(randi(), randi()))
	if n > n_max:
		n_max = n
```
now, every time you sample noise, divide it my n_max in order to get a normalized value. This is a sloppy, time consuming method, that still leaves a decent variance in sampled values. I believe that this problem could be solved within the implementation of OpenSimplex itself.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The existing workaround is a poor one, and the documentation surrounding this problem is sparse. I believe that it would be a very helpful addition to Godot.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, this issue is prevalent with almost all applications of noise, and should be part of the standard functionality of noise in Godot.

**Comment by YuriSizov** [comment]
Doesn't seem to be much support for this, so I have to close the proposal. Feel free to open a new one, given that the OpenSimplexNoise was recently replaced with FastNoiseLite, and many of its aspects have been improved and reworked: https://github.com/godotengine/godot/pull/56718.
