### ISSUE TITLE
Bad start for a newbie (due to documentation)

### ISSUE THREAD

**Issue by PRO1OO-yt** [godotengine/godot-proposals#8623]
### Describe the project you are working on

SSpace (itch.io kosstenko)

### Describe the problem or limitation you are having in your project

Null

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Out of curiosity, I opened the documentation in the "Coding the player" section.
**I WAS SHOCKED!**
![Снимок экрана (67)](https://github.com/godotengine/godot-proposals/assets/140896193/729aaf1c-50bb-4746-82bb-692328e290c6)
![Снимок экрана (68)](https://github.com/godotengine/godot-proposals/assets/140896193/99347553-1117-4fa2-8b54-41fed9762edd)

that's **HORRIBLE!**
What if a newbie sees this?

But the strangest thing is that the C++ script is written much better than in GDScript:

![Снимок экрана (69)](https://github.com/godotengine/godot-proposals/assets/140896193/f046e458-9279-4bf0-ad0a-0e00af764a49)

How can this be allowed?

In place of this, paste this script:

```
var input_dir = Vector2.ZERO
input_dir.x = int(Input.is_action_pressed(right_action)) - int(Input.is_action_pressed(left_action))
input_dir.y = int(Input.is_action_pressed(forward_action)) - int(Input.is_action_pressed(back_run_action))
input_dir = input_dir.normalized()
	
vel.x = input_dir.x * speed
vel.z = input_dir.y * speed
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Super

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Null

### Is there a reason why this should be core and not an add-on in the asset library?

Null

**Comment by paddy-exe** [comment]
This issue is violating the [CoC](https://godotengine.org/code-of-conduct/):
> Feedback is always welcome but keep your criticism constructive. We encourage you to open discussions, proposals, issues, and bug reports. Use the community platforms to discuss improvements, not to vent out frustration. Similarly, when other users offer you feedback please accept it gracefully.

I will close this issue for now. Please open a **constructive** issue in the dedicated [docs repository](https://github.com/godotengine/godot-docs)
