### ISSUE TITLE
Global gui input handling

### ISSUE THREAD

**Issue by darthLeviN** [godotengine/godot-proposals#8624]
### Describe the project you are working on

A project with a text input.

### Describe the problem or limitation you are having in your project

Grab a control, put a lineEdit on it. click away and focus isn't released. Pretty obvious it should release. It's basically common sense.

I don't want to make every control focusable because this will make `unhandled_input` useless

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We need two things.
1- A quick built in way to unfocus controls on outside clicks
2- A more customized way to handle this.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Global (Maybe in scenetree or viewport or both) `_gui_input(control, event)` that fires right after each control receives a `_gui_input` and will still be called if `accept_event()` was called for that control.

This will provide a way to customize the gui inputs in a better way. Sometimes we just don't want to script every control to get what we want.

Then using this system we can add an easy to use option that unfocuses a text input whenever :
a click outside is detected that doesn't fall in the line edit

Example :
Background (Control, no focus enabled)
LineEdit ( `auto_focus_release` checked )

now when a user clicks on Background, the focus releases from LineEdit

If a more customized way is desired the developer can use the global signal from the scene tree instead

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Trust me. it will be used very often. almost everywhere. In fact it should be on by default.

### Is there a reason why this should be core and not an add-on in the asset library?

Yea. the only way to get this is either scripting every control or modifying the `Control` class.

If approved i can implement it. It's pretty straighforward.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6501.

**Comment by KoBeWi** [comment]
You can press Escape to release focus.
