### ISSUE TITLE
Make the zoom speed configurable in the 2D scene editor

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-proposals#863]
**Describe the project you are working on:**
A regular project involving the creation and editing of 2D tilemaps.

**Describe the problem or limitation you are having in your project:**
When I work on a tilemap (or on any Scene, for that matter), I zoom in and out frequently so that I can quickly evaluate the looks both on a smaller and a larger scale. For that to happen routinely, I use the mousewheel to zoom in and out frequently.

It takes a lot of time, however, feeling slow. While a relatively small feature, my impression is that it has a huge impact in case zooming is prevalent. The Scene Editor has an option to reset Zoom to 100%, but it helps only in case of zooming in, not out.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A numeric configuration parameter added to Editor Settings called `Zoom speed`, similar to the currently existing `Pan speed`.

The value of this option would be bound to the zooming functions applied in the Scene Editor.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I imagine the perfect location of the new option to be `Editor Settings > Editor > 2D`. Here, a new config added with an integer value.

After some quick research, I found that `editor/plugins/canvas_item_editor_plugin.cpp::CanvasItemEditor::_gui_input_zoom_or_pan` is the function where the main logic is to be changed. Of course, it would mean that zooming with the mousewheel and using the GUI icons by clicking would be equally faster or slower, depending on the configuration.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
As with many configuration settings, chances are many people won't change them in the long run. However, since it depends on the interaction between an input and the response of the interface based on it, I'm not convinced a script solution is feasible.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is an option in the Editor Settings. Affects every 2D editor ever used in a project.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/37073. Would the enhancements there address your concerns about zooming speed?

**Comment by ExoidAgent** [comment]
> See [godotengine/godot#37073](https://github.com/godotengine/godot/pull/37073). Do the improvements there address your concerns about zooming speed?

The scope itself is *somewhat* different, but I'm not ruling out the possibility. Gonna check out the feature locally!

**Comment by ExoidAgent** [comment]
> See [godotengine/godot#37073](https://github.com/godotengine/godot/pull/37073). Do the improvements there address your concerns about zooming speed?

While it seems a reasonable solution after checking out thoroughly, I noticed this particular one is intended for 4.0 release. Would it be acceptable if I implement my own solution on 3.2?

I'd assume there are no obstacles for this feature to be transferred to 4.0 later on.

**Comment by Calinou** [comment]
@ExoidAgent That PR has the `cherrypick:3.2` label, which means it'll be cherrypicked to the `3.2` branch once it's merged.

**Comment by nodj** [comment]
Hi there,
I wrote #37073 and get notified for this suggestion. My PR doesn't affect zoom speed (only in a very minor way).
That being said, I share the observation that zooming in/out is quite slow. I think we can improve this in two way:
- just as you suggest: a speed factor setting
- use modifiers keys to affect zoom speed (eg. Ctrl for x3, Alt for 1/3)
Unfortunately, I don't have time right now to try and implement that...

**Comment by greensand3** [comment]
Hi, I'm new to Godot and found my way here after searching for a 'zoom speed' setting - having also found the mousewheel zoom a little slow. The speed factor setting sounds great. 

I would like to throw another option into the mix - what if we matched zooming from the 3D scene editor? i.e. hold down the MMB with a zoom modifier (e.g. Ctrl) and move the mouse to zoom. This could provide an alternative zoom speed or match the mousewheel zoom speed.

**Comment by Gnumaru** [comment]
> * just as you suggest: a speed factor setting
> * use modifiers keys to affect zoom speed (eg. Ctrl for x3, Alt for 1/3)

Indeed the 2d editor zoom speed is quite slow for using on bigger scenes. A speed factor setting would be useful but I think modifier keys would be even more useful. They could also affect the scroll speed on scroll bars so you can fully expand a scene tree full of nodes and scroll quickly through them all. 

I've been using an autohotkey script (on windows) for this purpose for sometime. I think this kind of behavior (with modifier keys) gives better usability

https://www.youtube.com/watch?v=qwCKHWXPlzg
