### ISSUE TITLE
Publicly Expose Tileset Physics Shapes

### ISSUE THREAD

**Issue by JHDev2006** [godotengine/godot-proposals#8632]
### Describe the project you are working on

2D platformer with lots of different variations of the same tileset

### Describe the problem or limitation you are having in your project

its getting really frustrating having to constantly have to set the physics shape of each tile manually, even though the layout of the tiles are the same between atlases, due to the large amount of unique shapes that are used,

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow for the physics shapes of tiles to be set through code, alongside being able to retrieve the shapes by returning a collision shape.

being able to write something to achieve this inside of a tileset tool script would be super helpful in being able to 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`tile_set.set_tile_physics_shape(atlas_id: int, physics_shape: Shape2D) -> void`
`tile_set.get_tile_physics_shape(atlas_id: int, tile_position: Vector2) -> Shape2D`

This would allow for one tile to copy the shape of another tile, which is something that would be used by me in my original problem, by utilizing it along side a basic for loop.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

nope, as this is something that will have to be included in the base GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

because the tileset resource does not allow for setting and getting of tile physics shapes. so it would have to be manually exposed through directly editing the engine core.

**Comment by AThousandShips** [comment]
Tiles don't use `Shape2D` at all, so it's not so much exposing anything, it just isn't there

**Comment by JHDev2006** [comment]
would it be possible to then be able to return an array of points or something?

**Comment by AThousandShips** [comment]
For the collision? Yes you already have it, in [this](https://docs.godotengine.org/en/stable/classes/class_tiledata.html#class-tiledata-method-get-collision-polygon-points)

**Comment by JHDev2006** [comment]
Aha! thats what ive been looking for! Thank you!
