### ISSUE TITLE
Allow comments to be hidden and shown only in searches

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#8639]
### Describe the project you are working on

FPS.

### Describe the problem or limitation you are having in your project

Finding comments to remove when a project is ready to be build for distribution, or when trying to look for lines of code is difficult and time-consuming, there should be a way of hiding all comments from searches, as well as a way of showing only comments in searches. This proposes to add a comments-only search from this old proposal: https://github.com/godotengine/godot-proposals/issues/563

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Finding comments to remove when a project is ready to be build for distribution, or when trying to look for only lines of code.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A dropdown that chooses if searches should show:

1. Everything
2. Only Comments
3. No Comments

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so

### Is there a reason why this should be core and not an add-on in the asset library?

I think it perhaps could be, but probably shouldn't.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/563.

Since the implementation details are very similar to https://github.com/godotengine/godot-proposals/issues/563, I've renamed that proposal to cover both use cases (search only in comments, don't search in comments).
