### ISSUE TITLE
Add a Path3D editor Option to "mimic" a closed curve

### ISSUE THREAD

**Issue by GreenCrowDev** [godotengine/godot-proposals#8650]
### Describe the project you are working on

A plugin for procedural mesh generation.

### Describe the problem or limitation you are having in your project

It's no secret that in the past few years there's been a lot of discussion and proposals to implement "closed curves" when talking about Path3D/Path2D and Curve3D/Curve2D.
The limitation is clear: having a "closed" and "continous" curve is cumbersome and not easily achievable, but it's something you would want almost all times.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The implementation I have in mind is very simple and straightforward, should be easy to implement, and will not even need to modify the Curve3D class.
The idea is to just have an **option** in the Path3D editor that will "synchronize" the first and the last point of the curve **mimicking** a closed curve without any other hassle.
Basically when this option is _true_, the **last point** will have the **same position, handle position, and tilt** of the **first point**.
This "mode" could alse be automatically activated when pressing the "Close Curve" button, but this is not mandatory.
I think this also has a lot of pros with respect to implement a Curve3D is_closed property, that would require a lot of work and could even be undesirable at times.
I can probably try an implementation in the next days.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![path3d_screenshot](https://github.com/godotengine/godot-proposals/assets/62719360/98196ce7-8ce1-4966-8c01-14cbd4d111f0)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would be used a lot if someone wishes to work with paths and curves.

### Is there a reason why this should be core and not an add-on in the asset library?

This should be core behaviour and desirable to have directly in the engine.

**Comment by Calinou** [comment]
I would prefer to have proper closed curve property support, like we have for Line2D since 4.2. This makes runtime modifications significantly easier and avoids any situations where points could get out of sync.

**Comment by matricola787** [comment]
@Calinou I would probably prefer that too. One of the reasons I proposed this implementation is because after all these years Curve3D still has not the closed property, even though everyone agree with that...
Why though? Would the implementation of a proper closed property be too difficult?
Do you think that if I'd take a look at the issue you mentioned I'd be able to implement that in a proper way for Curve3D?
