### ISSUE TITLE
Godot plugins should be able to specify a minimum required Godot version

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#8653]
### Describe the project you are working on

An addon which provides map editor for Godot.

### Describe the problem or limitation you are having in your project

Some updates to the code require features that are only available in Godot 4.2 and above.  The old version of the addon ran in Godot 4.0, but the new version requires Godot 4.2 and I would like users to be aware of this if they try to run the new addon on an older version of Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a line to the plugin.cfg file that lets you specify a minimum required Godot level.  Also have the Godot editor alert users if they are trying to use an addon on a version of Godot that is before the minimum version.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An extra line of text can be added to the plugin.cfg file, such as

min_godot_version="4.2"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This deals with how the editor installs addons and is not really something that can be done with a script.

### Is there a reason why this should be core and not an add-on in the asset library?

This will affect how the editor deals with addons.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1613.
