### ISSUE TITLE
Allow running headless editor scripts

### ISSUE THREAD

**Issue by JorensM** [godotengine/godot-proposals#8663]
### Describe the project you are working on

[Someone on Reddit](https://www.reddit.com/r/godot/s/FlnS5XXc2L) wants to run a headless script from CMD that extends EditorScript. The person faced the problem that the script must extend `SceneTree` or `MainLoop`, but when they do that, the editor specific functions are not available anymore.

### Describe the problem or limitation you are having in your project

Cannot run headless editor script from CMD

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allowing to run headless editor scripts would open opportunity for new ways to utilize headless scripts.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Don't know how it would work as I don't know the inner workings of Godot, sorry

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I know of

### Is there a reason why this should be core and not an add-on in the asset library?

This should be in core because to me it seems like a must-have feature for core.

**Comment by AThousandShips** [comment]
What would a headless editor script mean? What would an *editor* script do without the *editor*?
