### ISSUE TITLE
2D Light Occlusion with "walls" on tilemaps

### ISSUE THREAD

**Issue by M0LD** [godotengine/godot-proposals#8687]
### Describe the project you are working on

A recreation of RPG Maker currently we are working on 2D occlusion

### Describe the problem or limitation you are having in your project

https://forum.godotengine.org/t/how-can-i-make-tilemap-walls-with-an-occluder-show-and-cast-shadows/28236

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Some way to mark a tile to cast shadows without being cast on itself

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Emulate tiles to layer themselves so they don't act like a flat floor

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Currently this can not be worked around unless working with sprites instead of tilemaps, highly unrecommended

### Is there a reason why this should be core and not an add-on in the asset library?

I think alot of "45 perspective RPGs" would need this if they include 2D light occlusion

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/64939, as this is a bug.
