### ISSUE TITLE
Make 3x3 auto-tiles override

### ISSUE THREAD

**Issue by Alzter** [godotengine/godot-proposals#87]
**Describe the project you are working on:**
I am working on a 2D platformer game [(Link)](https://github.com/Alzter/TuxBuilder) that will let players play levels and create them in a custom level editor. I am trying to implement slope tiles in this project by making them as an auto-tile that replaces corners with slopes, although I have some problems with them.

**Describe how this feature / enhancement will help your project:** I need slopes to transition from the ground to the corner tiles but I can't do that using a 3x3 minimal auto-tile. I could use a 3x3 instead but that would require 512 combinations of tiles, most of them I wouldn't even need aside from a few corner transition tiles. So what I'm proposing is the ability to override the 3x3 minimal autotile if you use a specific bitmask. I find it a bit difficult to explain so I'll provide a mock-up below.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/22513909/65317517-56164200-dbdf-11e9-912e-73798f2b66c7.png)

**Describe implementation detail for your proposal (in code), if possible:**
I have no experience coding for Godot but my idea is to have tiles with a specific bitmask over-ride the behaviour of 3x3 minimal.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm not sure how to change the properties of auto-tiles through GDscript and it seems like it would be very complicated.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it could help for specific use cases in auto-tiles for things like transitions.

**Comment by groud** [comment]
Please [read the rules](https://github.com/godotengine/godot-proposals/blob/master/README.md), and fill the template. I'll reopen if this gets fixed.

**Comment by Alzter** [comment]
> Please [read the rules](https://github.com/godotengine/godot-proposals/blob/master/README.md), and fill the template. I'll reopen if this gets fixed.

I edited it, is this satisfactory?

**Comment by YuriSizov** [comment]
Thanks for your proposal! Unfortunately, it seems there isn't much interest in it, even after all this time, so I'm going to close it. But check out the new TileMap system in Godot 4.0, maybe it'll work for you in another way!
