### ISSUE TITLE
Add support for the physical 'back' and 'forward' buttons of my mouse in the script editor

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot-proposals#8704]
### Describe the project you are working on

I'm writing code in the internal Godot script editor.

### Describe the problem or limitation you are having in your project

I often find myself looking for the script I was editing, eg. after having used [cmd] + click on an engine API method to look at the docs, or after quickly looking up something in another open script. I intuitively press the physical 'back' or 'forward' buttons on my mouse, as those work in most other applications (eg. going to the previous web page in the browser), but they do nothing in the script editor in Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If support for the physical 'back' and 'forward' buttons of the mouse is added, users could navigate the script editor in Godot **a lot** quicker in many scenarios.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If the user pressed the physical 'back' button on their mouse, go to the previous edited document (if any).
If the user pressed the physical 'forward' button on their mouse, go to the next edited document (if any).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There are back and forward buttons in the top right corner of the script editor with the exact functionality, but to press those you HavE tO mOvE uR mOuSe CuRsOr AlL tHe WaY tHeRe!!! ;) It's just a lot less quick.

### Is there a reason why this should be core and not an add-on in the asset library?

It's part of the editor, not of one's game project.

EDIT1: further clarified I'm talking about the physical buttons on my mouse here, not the digital / virtual buttons of the script editor interface that can be clicked when the mouse cursor is over them.

**Comment by KoBeWi** [comment]
But back and forward *are* already functional in the script editor. They function the same as the "history" buttons:
![image](https://github.com/godotengine/godot-proposals/assets/2223172/d50f661a-6463-4076-b653-2a514c4b33f6)

**Comment by AdriaandeJongh** [comment]
Oh, I wasn't clear enough! I mean **the physical 'back' and 'forward' buttons of my mouse** – not the script editor buttons I can press with my mouse cursor in the digital world of my computer screen ;)

![Screenshot 2023-12-21 at 12 45 02](https://github.com/godotengine/godot-proposals/assets/5611323/29bf7cdd-12a1-42cc-afd3-1ec2887a3a3e)

**Comment by KoBeWi** [comment]
Yes, these **physical** buttons are functional in the script editor.
What OS are you using? Maybe it's some bug.

**Comment by AdriaandeJongh** [comment]
Dang, I'll have to make a bug report then. FYI I'm on Godot v4.2.1.stable - macOS 14.2.0 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (14 Threads) using plentycom.jp's Steermouse to config my Logitech MX Master 3S. Steermouse shouldn't do anything fancy – as I said, it works in other applications – so I don't understand what's going on there then.

**Comment by KoBeWi** [comment]
Try
```GDScript
func _input(event):
	print(event)
```
and see what happens when you press the buttons.

**Comment by AdriaandeJongh** [comment]
Good call: weirdly, nothing gets outputted.

**Comment by KoBeWi** [comment]
So this is clearly a bug.
Please open a new issue [here](https://github.com/godotengine/godot/issues) instead.

**Comment by Calinou** [comment]
Issue opened: https://github.com/godotengine/godot/issues/86393
