### ISSUE TITLE
Have a unit testing process / library for the engine

### ISSUE THREAD

**Issue by paulherman** [godotengine/godot-proposals#871]
**Describe the project you are working on:**
I have opened my first PR to Godot.

**Describe the problem or limitation you are having in your project:**
It would've been nice to gain confidence in my change by writing some tests.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In my example https://github.com/godotengine/godot/pull/38920 I would've checked that the method added is available as a bind when the module is initialized.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
We'll add an external dependency on a unit testing framework (googletest, catch2 come to mind). This is to be explored if there's interest in the idea.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't believe so.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This tests the core too.

**Comment by Jummit** [comment]
There are test for the engine (https://github.com/godotengine/godot/tree/master/main/tests) and there are multiple testing frameworks for testing games (https://github.com/CodeDarigan/WAT and https://github.com/bitwes/Gut/).

**Comment by Calinou** [comment]
This is already planned, see @Jummit's comment. It's just taking a while to be merged because the `master` branch is currently undergoing refactoring.

**Comment by paulherman** [comment]
Sounds good - perhaps what's missing is documentation / processes around how a PR should be tested and how to write a simple unit test. I'll close this.

**Comment by Xrayez** [comment]
See also my little testing endeavours at godotengine/godot-tests#8. I still feel like using GDScript-based testing framework is more practical in the long run.

As I'm thinking about it, it's also quite possible to modify the Travis CI configuration locally to run those tests on the fork side, with the link pointing to passing tests you've personally written yourself, but that's far, very far from being user friendly for new contributors of course.
