### ISSUE TITLE
Add LOD for Godot 3.x branch

### ISSUE THREAD

**Issue by Drakenroft** [godotengine/godot-proposals#8712]
### Describe the project you are working on

/

### Describe the problem or limitation you are having in your project

I know that Godot 4 is the "big thing" and the future, but i find Godot 3 to be really perfect until Godot 4 becomes more stable in his features, thus said Godot 3 has always fullfilled every thing i've tried to accomplish even more complex tests/example. The only thing that i miss there would be is the same (amazing) auto-lod there is in Godot 4. 
I know there are plugins and can be writed a simple script that works with MeshInstance to "simulate" a LOD, but those pratices are often inefficent and scale pretty bad.

It would be an amazing gift to have in the upcoming Godot 3.6 (which i imagine will be the last version, with his only 80+ ticket remaining) with the same Auto-LOD Godot 4 has, and would end the Godot 3.x cycle with a version that even if it's missing more complex/specific features, at least it would at least reach the capability to fullfill the vast majority of games more efficently than now (static typing GDScript would be amazing too in Godot 3.x but i don't want to ask too much, i know that Godot is moved by his amazing contributors and that a small team from the foundation is actually paid and has to focus on the more important Godot 4).

Also i would like to add that Godot 3 right now is still the "production" choice for many like me, we also are considering to use that in the software house were i work (which is a pretty big reality)  to replace Unity for some project, until Godot 4 becomes more stable, have a major feature like this back-ported to Godot 4 would let software houses have more confidence in using Godot for their products. A software house always aim for the more stable product to integrate in the workflow.
(just to clarify not saying Godot 4 is not stable or an incomplete product, but as you know better than me is still in the phase where many decision are been made and many thing are being changed and will change, like the replacement of SDFGI to name one)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Would make Godot 3 be able to scale a lot better than now in wide environments / open worlds games and simulation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I imagine a LOD Node much similar to MeshInstance but with some parameters that able us to set the distance to be rendered, a normal lod system like there is in Unity, Godot 4 and Unreal.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As said before it could be accomplish with MeshInstance and a script, but the result is extremely inefficent.

### Is there a reason why this should be core and not an add-on in the asset library?

A LOD system is a core part of a stable and feature-packed engine, it enables to work on a major variaty of game compared to now.

**Comment by Drakenroft** [comment]
(To clarify one thing, i know that Godot 3 has static typing too, i was referencing to the performance gains that comes in using it that as far as i know is only for Godot 4 at the moment)

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/40784, as this is technically a missing feature that was intended to be added (so it doesn't need a proposal).

In the meantime, use https://github.com/godot-extended-libraries/godot-lod :slightly_smiling_face:

**Comment by Drakenroft** [comment]
Thanks a lot for your answer (and your work!), i just checked to the links. 
So just to be absolutely clear, we can expect Godot 3.6 to have a functioning LOD system (no automatic LOD)?

Also is there an eta for Godot 3.6?

Thanks a lot!

**Comment by Calinou** [comment]
> So just to be absolutely clear, we can expect Godot 3.6 to have a functioning LOD system (no automatic LOD)?

We can't promise there will be a LOD system in 3.6, but contributors are doing work that *may* make it happen.

> Also is there an eta for Godot 3.6?

No, we can't provide an ETA for it as we don't know when it'll be in a releasable state.
