### ISSUE TITLE
Add camera support on Windows and Linux

### ISSUE THREAD

**Issue by Account-Accelerator** [godotengine/godot-proposals#8716]
### Describe the project you are working on

Augmented Reality, QR Code Scanning, Barcode Scanning, and a simple Webcam Chat.

### Describe the problem or limitation you are having in your project

Note: This class is currently only implemented on macOS and iOS. On other platforms, no [CameraFeed](https://docs.godotengine.org/en/stable/classes/class_camerafeed.html#class-camerafeed)s will be available.

Unable to use Webcam.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

With Webcam implementation a whole range of educational and creative possibilities open up.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

CameraTexture, CameraFeed, and CameraServer would be functional.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No current workarounds to my knowledge.

### Is there a reason why this should be core and not an add-on in the asset library?

For Educational and Creative purposes Godot users should have the ability to use a Webcam within the Godot environment as described in the documentation.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/46531.
