### ISSUE TITLE
Mac OS Engine Window resizing incorrectly

### ISSUE THREAD

**Issue by Railwanderer** [godotengine/godot-proposals#872]
**Describe the project you are working on:**
A simple 2d message dialog.

**Describe the problem or limitation you are having in your project:**
The editor window resizes incorrectly when switching from 2d scene to script and back.
Occurs in any project. Godot 3.2.1 Mac Os Catalina
Happens on both Monitors, Screen Resolutions 1280x800 and 1280x1024

![Bildschirmfoto 2020-05-22 um 13 07 22 (2)](https://user-images.githubusercontent.com/17583446/82662239-cb825880-9c2d-11ea-8f8e-58783c93871a.png)

![Bildschirmfoto 2020-05-22 um 13 07 09 (2)](https://user-images.githubusercontent.com/17583446/82662275-d9d07480-9c2d-11ea-8beb-9461bec96eaf.png)

![Bildschirmfoto 2020-05-22 um 13 07 20 (2)](https://user-images.githubusercontent.com/17583446/82662292-e359dc80-9c2d-11ea-8aea-acfcd92bbf56.png)

**Comment by Jummit** [comment]
This is a bug and should be reported in the godot repo: godotengine/godot

**Comment by Calinou** [comment]
This is a [known issue](https://github.com/godotengine/godot/issues/31133) due to the length of some translated texts, so please don't bother creating a new issue.
