### ISSUE TITLE
Add a method of animating embedded windows

### ISSUE THREAD

**Issue by fractalcounty** [godotengine/godot-proposals#8731]
### Describe the project you are working on

A simple main menu interface using the built-in ConfirmationDialog node embedded inside the viewport

### Describe the problem or limitation you are having in your project

In my game's main menu, a ConfirmationDialog node is used to warn the player before exiting the game. However, it appears quite abruptly due to the nature of the built-in Window class. 

https://github.com/godotengine/godot-proposals/assets/121070110/8b157144-050e-4f49-a515-bd2c0f4ad00d

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As of now, there doesn't seem to be any method of implementing this in Godot 4.2 for non-native (embedded) windows, nor does there seem to be any way to animate window behavior period.

I assume this is because Window inherits from Viewport (as opposed to something like CanvasItem) and is likely a restriction of its built-in functionality. Regardless, some method of animating the opening and closing of windows would be hugely beneficial to creating responsive user interfaces in Godot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Essentially, just exposing a property of Viewport that allows for simple animations based on events such as visibility changes or focus would overcome this. The user could just tween it or modulate it with an AnimationPlayer like any other property. I'm not quite sure what the feasibility of this is due to previously mentioned limitations of the Window node.

https://github.com/godotengine/godot-proposals/assets/121070110/e7a88b38-b408-4e78-aada-7a1c02d71b9f

A less common (but still useful) implementation of this would be simple bounce animations triggered by window focus, title bar blinking, rescaling animations, etc... However, that would likely be significantly more difficult to implement I imagine. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as far as I can tell, there are no exposed properties of ConfirmationDialog, AcceptDialog, Window, or Viewport that allow for opening & closing transitions or any type of animation. Modulating opacity might be already possible since transparent viewports are supported, but I couldn't figure out that either. The only real workaround is to just forgo the Window class altogether by manually creating a dialogue box system yourself via Control nodes, which may actually be the best practice here- the docs weren't quite clear on this. However, it's a shame to forego the built-in window system over such a small feature.

### Is there a reason why this should be core and not an add-on in the asset library?

Animated window transitions are an overwhelmingly common use case in many desktop environments and applications. A way to overcome this would bring the Window feature closer to parity with modern standards. 

However, it's possible I might be completely misunderstanding the purpose or intended use case of Godot's built in Window system as this only makes sense in the context of embedded windows (as opposed to native, OS windows that Godot can also create). A feature like this may be completely out of scope and better suited for interfaces built with CanvasItems. If that's the case, I can close/remove this issue.

**Comment by Calinou** [comment]
The window can't be resized every frame if it's not embedded for performance reasons (operating systems' window managers don't like when you manipulate things every frame), so this would have to be limited to embedded subwindows.

**Comment by fractalcounty** [comment]
> The window can't be resized every frame if it's not embedded for performance reasons (operating systems' window managers don't like when you manipulate things every frame), so this would have to be limited to embedded subwindows.

After further reflection I have come to the conclusion that this proposal was a stupid idea
