### ISSUE TITLE
Don't leave SCRIPTS and STRUCTURES so exposed when exporting to Android

### ISSUE THREAD

**Issue by dpnnl** [godotengine/godot-proposals#8746]
### Describe the project you are working on

A simple project with: scene_1.tscn and scene_1.gd

### Describe the problem or limitation you are having in your project

All my scenes, scripts (and especially my comments), audios, images, etc. are easily obtained through an APK, as they are all accessible in the "assets" folder.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add encryption to the mentioned files (even if it is simple) when exported to Android.

I saw about "Compiling with PCK encryption key" but it doesn't work for Android AAB (at least and I wasn't successful).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

During export to Android (AAB).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would not be necessary to deactivate it.

### Is there a reason why this should be core and not an add-on in the asset library?

(A security breach?) All my scenes, scripts, etc. are so exposed:

```
func _ready():
	print("ready")
```
This shouldn't be as readable when exported.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6675 and https://github.com/godotengine/godot-proposals/issues/4220. (This does *not* require rewriting the build system from scratch.)
