### ISSUE TITLE
Integration with the Modelica physics engine

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot-proposals#875]
**Describe the project you are working on:**
Simulation of a [tensegrity](https://en.wikipedia.org/wiki/Tensegrity) structure (a hang-glider airframe) which is like a self-connecting network of springs and joints.

**Describe the problem or limitation you are having in your project:**
The Godot physics engine appears to be targeted at rigid bodies and a generalized joint defined by a huge number of parameters.  It's always going to be incomplete.  

For example, the body only has mass and no angular inertia settings, and the joints are assumed to be at pin-points, and not damped or controlled by an external hydraulic actuator like you see on a bulldozer or a humanoid robotic arm.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Modelica seems to be the industry standard for dynamical simulations.  It is primarily a programming language that is fundamental across the industry in the same way that OpenGL is fundamental to all graphics.

It is a state-of-the-art solution for physical models (other than FEA).  It works by converting the system into a flat list of first order differential equations, then analyses their dependencies and applies esoteric numerical methods to solve and accurately time-step them forward.

A physics simulation that is converted to this form would be complete and future proof, and shift this difficult problem to where it has been solved by specialist experts -- in the same way that we use GPU shaders, and leave it to the good folks at NVidia to achieve the impossible job of implementing them.  

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The Open Modelica Editor (OMEdit) has an interface for defining bodies and joints.  Most of this structure can be encoded in the Godot editor with its bodies and joints -- except that Modelica allows you to have loops in your structures (eg an object held up by two spring/wires, like a child's swing), because it has no limits, and no need to invent a category known as "Inverse Kinematics".  All kinematics are instead treated as simultaneous.

![image](https://user-images.githubusercontent.com/677254/82727800-9f75de80-9ce4-11ea-88c8-e4d458a0d944.png)

A Modelica checkbox on a node would cause the network of bodies and forces defined in the tree below it to automatically export the code to be used for the simulation.  As an example, the following is the code for the double-pendulum above.

```
model fff
  Modelica.Mechanics.MultiBody.Parts.BodyBox boxBody1(r = {0.5, 0, 0}, width = 0.06) annotation(
    Placement(visible = true, transformation(extent = {{-20, -10}, {0, 10}}, rotation = 0)));
  inner Modelica.Mechanics.MultiBody.World world annotation(
    Placement(visible = true, transformation(extent = {{-100, -10}, {-80, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Revolute revolute1(phi(fixed = true), useAxisFlange = true, w(fixed = true)) annotation(
    Placement(visible = true, transformation(extent = {{-60, -10}, {-40, 10}}, rotation = 0)));
  Modelica.Mechanics.Rotational.Components.Damper damper(d = 0.1) annotation(
    Placement(visible = true, transformation(extent = {{-60, 30}, {-40, 50}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Revolute revolute2(phi(fixed = true), w(fixed = true)) annotation(
    Placement(visible = true, transformation(extent = {{20, -10}, {40, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Parts.BodyBox boxBody2(r = {0.5, 0, 0}, width = 0.06) annotation(
    Placement(visible = true, transformation(extent = {{60, -10}, {80, 10}}, rotation = 0)));
equation
  connect(world.frame_b, revolute1.frame_a) annotation(
    Line(points = {{-80, 0}, {-60, 0}, {-60, 0}, {-60, 0}}));
  connect(revolute1.frame_b, boxBody1.frame_a) annotation(
    Line(points = {{-40, 0}, {-20, 0}, {-20, 0}, {-20, 0}}));
  connect(boxBody1.frame_b, revolute2.frame_a) annotation(
    Line(points = {{0, 0}, {20, 0}, {20, 0}, {20, 0}}, color = {95, 95, 95}));
  connect(revolute2.frame_b, boxBody2.frame_a) annotation(
    Line(points = {{40, 0}, {62, 0}, {62, 0}, {60, 0}}, color = {95, 95, 95}));
  connect(damper.flange_a, revolute1.support) annotation(
    Line(points = {{-60, 40}, {-64, 40}, {-64, 14}, {-56, 14}, {-56, 10}, {-56, 10}}));
  connect(damper.flange_b, revolute1.axis) annotation(
    Line(points = {{-40, 40}, {-34, 40}, {-34, 18}, {-50, 18}, {-50, 10}, {-50, 10}}));

annotation(
    uses(Modelica(version = "3.2.3")));
end fff;

```

You can see the double pendulum in action (and other examples) here: https://youtu.be/k7lLBASaEJg?t=121

In the free implementation OpenModelica, this language is converted into C-code, compiled and then run as a process from the command line with all the settings (stepsize, tolerance, etc).  At the moment it is a batch process which produces an output file, but there's no reason it couldn't be streamed and be forced to take realtime parameter inputs.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
An early use-case could be for animation.  I am not an animator, but I am astonished at how labour-intensive it seems with every joint and every keyframe needing to be individually moved.  It's like doing artwork pixel-by-pixel before there were any photoshop tools.  

Modelica could be used to quickly generate neat pre-calculated animations of [Rube-Goldberg machines](https://en.wikipedia.org/wiki/Rube_Goldberg_machine) akin to the boardgame [Mousetrap](https://en.wikipedia.org/wiki/Mouse_Trap_(game)).  

**Is there a reason why this should be core and not an add-on in the asset library?:**
I know this is a highly speculative proposal.  However I don't think it's possible to rule out that it replaces the whole of the physics engine on day.  

I am writing this down to give a heads-up about this technology to the folks who depend on and are developing the physics engine, because too few people know about it at the moment.

**Comment by Jummit** [comment]
Can you include a link to this "Modelica" engine? I'd like to check it out.

**Comment by fire** [comment]
I cannot tell very easily what license https://github.com/OpenModelica/OpenModelica/blob/master/OSMC-License.txt is. It seems to be GPL3? 

Can you review?

The license needs to be as open as Godot Engine's license.

**Comment by goatchurchprime** [comment]
It seems to be dual licensed, where [Open Modelica Consortium members](https://openmodelica.org/home/consortium) get to use the code in proprietary industrial-strength products, and for everyone else it's GPL3. Godot is used to make proprietary products, so what it compiles down and distributes needs to be a permissive license, like MIT.  

However, this issue doesn't apply to the tools. For example, we use GIMP and Blender (both of which are GPL protected) to generate our assets, and Modelica could be another available tool in the box.  Any animations made using Modelica wouldn't have a license issue, obviously.  However it's not stated whether there is a license issue with any of the C-code that it generates and compiles for the simulation, which is what you would run.  It would hopefully be okay if they follow the pattern of the gcc, where the compiler is GPL but the output it makes is not covered by any license.

In an ideal world, the Modelica language for physics simulation would be directly interpreted by GPUs, just like shader code, because it is standard enough, but we're not there yet.

**Comment by fire** [comment]
The Godot Engine editor 50~MB is build on the Godot Game ~30mb. The whole combination needs to be MIT compatible.

I don't know how to avoid GPL3 from Modelica.

**Comment by fire** [comment]
That said, you can make a GPL3 version of Godot Engine as the license permits, I don't recommend this because tracking changes is a full time job.

**Comment by Calinou** [comment]
Closing due to lack of support and licensing concerns
.
