### ISSUE TITLE
RichTextEdit Node

### ISSUE THREAD

**Issue by CyberGh0st-droid** [godotengine/godot-proposals#8764]
### Describe the project you are working on

I've made a very simplistic and minimalistic text editor. though I would like to add more features like formatting text and adding images to the rtf file. 

### Describe the problem or limitation you are having in your project

there is no node that allows the end user to edit RichText with formatting and and other more advanced features

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

this would add great potential for godot to be used as a stand alone app development environment.
which I honostly think a lot of people including myself are using it for. 

Godot has great UI design elements and nodes. and is very simplistic to use. therefore I believe it's honestly one of the simplest ways for beginners, who don't know much about programming, to be able to make an application quite quickly and speedily. 
  

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'll use diagram since I'm not to sure about how the code would actually look.

just like TextEdit/CodeEdit: GetUserInput> then I assume you would parse BBCode > Display Output

this is much simplified but I think it's the basic Idea. otherwise you could add ui for formatting text like increasing font size, changing text color, adding image. although those are not strictly necessary to be part of the built in RichTextEdit node as the programmer could manually implement those features. Which would probably be better on a per use-case basis

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe it could but It would end up being more han a few. it would also be inefficient and unnecessarily time consuming to do so. not to mention it would be completely Impractical.

you'd have to use textEdit overlayed on a RichTextLabel. then everytime the user inputs text, copy that text from the TextEdit to the RichTextLaybel. then delete the text from the TextEdit node. 

then you'd have to make sure that the text in the RTL and the TE is perfectly alligned so that there are no visual bugs. 

at the end of the day it's completely impractical  

### Is there a reason why this should be core and not an add-on in the asset library?

I believe this could be useful in many use-cases when using Godot for building applications. which Honestly it has no right being, as good at as it is. Being a game engine

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot-proposals/issues/1781

**Comment by CyberGh0st-droid** [comment]
yeah https://github.com/godotengine/godot-proposals/issues/1781 doesn't include pasting images in the file like a rich text editor would. I don't think it's really the same thing. #1781 just wants more features in the textEdit. I want a RichTextEditor that also allows to show images like RichTextLabel or Microsoft Word would allow user to add image to the file
