### ISSUE TITLE
Variable sets/class?

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot-proposals#878]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**
having lots of variables makes the code harder to comprehend

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
-for sorting scripts with lots of condition

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
vars world_generator:
|  export(String) var chucky
|  onready var hello_world

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by bojidar-bg** [comment]
I assume this issue is about categories for exported variables? In this case, there is some discussion on https://github.com/godotengine/godot/issues/4378, #109, and #828.

**Comment by LoneDespair** [comment]
Indeed something like this https://github.com/godotengine/godot/issues/4378

it would be very handy for scripts with like 20-30 variables
which is very common for games that stores a lot of condition



or maybe something like a static dictionary like or class?
eg 
var_class Speed:
-var min = 999999

func _ready():
-print(Speed.min)
