### ISSUE TITLE
Allowing Remotesync RPC Return Values

### ISSUE THREAD

**Issue by AsherGlick** [godotengine/godot-proposals#879]
**Describe the project you are working on:**
Multiplayer Game

**Describe the problem or limitation you are having in your project:**
I would like to return a value from a `remotesync` rpc call. One example is when creating a new object on all clients and wanting to return the created object on the master to do additional work with.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Have `rpc()` return a value when calling a `remotesync`, `mastersync`, or `puppetsync` function instead of an empty variant. Or add a new function such as `rpc_sync()` that returns the value.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
extends Node

var testvar = "Unset"
func _ready():
	var peer = NetworkedMultiplayerENet.new()
	peer.create_server(33333, 10)
	get_tree().set_network_peer(peer)
	print("Pre-Call: ", self.testvar)
	var returnval = self.rpc("remotesync_function")
	print("Post-Call: ", self.testvar)
	print("Return Val: ", returnval)

remotesync func remotesync_function():
	self.testvar = "Set"
	return "Returned Value"

# Prints
# ======
# Pre-Call: Unset
# Post-Call: Set
# Return Val: Returned Value (currently prints Null)
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This enhancement can be worked around with a few modifications, however it necessitates the `remotesync` function be converted to a `remote` function and be called manually alongside the `rpc()` every time the `rpc()` is called.
```
extends Node

var testvar = "Unset"
func _ready():
	var peer = NetworkedMultiplayerENet.new()
	peer.create_server(33333, 10)
	get_tree().set_network_peer(peer)
	print("Pre-Call: ", self.testvar)
	self.rpc("remote_function")
	var returnval = remote_function()
	print("Post-Call: ", self.testvar)
	print("Return Val: ", returnval)

remote func remote_function():
	self.testvar = "Set"
	return "Returned Value"

# Prints
# ======
# Pre-Call: Unset
# Post-Call: Set
# Return Val: Returned Value
```

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a useful modification of the `rpc()` function and not an isolated feature that would be suitable for an asset library add-on.

**Comment by bojidar-bg** [comment]
In order to not block the main while requesting something, probably such a function should return an object with signal, or something like a promise.

That would allow doing something like this in GDScript:
```
func _ready():
	var returnval = yield(rpc_return("remotesync_function"), "complete")
	print("Return Val: ", returnval)

remotesync func remotesync_function():
	return "Returned Value"
```

Or, potentially, in the newer GDScript in Godot 4.0:
```
func _ready():
	var returnval = await rpc_return("remotesync_function")
	print("Return Val: ", returnval)

remotesync func remotesync_function():
	return "Returned Value"
```

**Comment by AsherGlick** [comment]
This proposal is indeed specifically for sync functions, I think though for remote functions there might be even more work then described due to a single call to `rpc` possibly being run on multiple different clients and may return multiple different times.

I should also mention that a I have working versions of my proposal for both 3.2 and 4.0 ready to submit for a PR, the guidelines said that new features should be discussed here first to see if they are wanted by the community.

**Comment by Jummit** [comment]
Only rpc_id should return values, otherwise it will get very confusing.

**Comment by AsherGlick** [comment]
@Jummit  you may be confused in the same way @bojidar-bg was. A non-empty variant return value will only be returned if the function being called is some form of `*sync` (`remotesync`, `mastersync`, or `puppetsync`) function meaning it is also run on the caller's machine, and only the return value from the local call will be returned. This should not imply that a return value from a remote client will be received, but I can see how some confusion could arise.

Though this brings up an interesting thought about `sync` in general and why it is used in the function definition and not in the call itself. eg `rpc_id_sync()` or `rpc_sync()` would ease the confusion that this proposal might introduce, however I am unsure about what other issues it might bring up.

**Comment by Jummit** [comment]
So you want to do
```gdscript
var local_result = rpc("sync_function")
```
instead of
```gdscript
rpc("sync_function")
var local_result = sync_function()
```

**Comment by AsherGlick** [comment]
The game I am working on is a card game where the logic for the game is almost entirely controlled by the server, while the clients represent little more then views into the state of the server. Card objects are created on the client and can be visually manipulated to a degree by the client's user, such as picking them up and putting them down, but no core-game logic is ever run on the client. Both the client and the server run off the same codebase and share as much code as possible to avoid complexity.

The server currently has roughly this snippit of code

``` gdscript
func draw_card(owner_character, source):
    ...
    self.rpc("NETWORK_draw_card", [owner_character.card_id], card_name, card_variant)
    var drawn_card = NETWORK_draw_card([owner_character.card_id], card_name, card_variant)
    if typeof(drawn_card) == TYPE_OBJECT and drawn_card.is_class("GDScriptFunctionState"):
        drawn_card = yield(drawn_card, "completed")
    ...
    return drawn_card

remote func NETWORK_draw_card(init_args, card_name, card_variant):
    var card = load("res://card.tscn").instance()
    ...
    var script_path = self.scripts_location + "/" + card_name + ".gd"
    card.set_script(load(script_path))
    ...
    self.add_child(card)
    var retval = card.configure_card(card_id, card_name, card_variant, init_args)
    if typeof(retval) == TYPE_OBJECT and retval.is_class("GDScriptFunctionState"):
        yield(retval, "completed")
    ...
    return card
```
The server then keeps track of that card for things like "displaying a menu containing all of the cards", while the client does not need such information and may run into trouble if trying to use it, such as calling an rpc that should have only been called by the server, or becoming out of sync when it does not receive an update that is only sent to the server and not relayed.

An advantage to this I enjoy is that the card can then have `rpc()`s called on it directly without having to worry about sending any kind of abstract object identifier over rpc as the engine will automatically look for a node with the same path to call the rpc on. That way the main logic can simply call `card.discard()` and the `discard()` function is as simple as :

``` gdscript
# inside the card's script
func discard():
    self.rpc("NETWORK_discard")

remotesync func NETWORK_discard():
    self.deleted = true
```
This same pattern is used for any sort of game-logic based state modification, `discard()` just happened to be a very simple example.

The big flaw of any argument made for allowing `rpc()` to return a value from `*sync` functions is that there is no case where it could not be worked around by simply changing the called function to not be `*sync` and calling it manually on the caller's side after the `rpc()`. However I would say that that argument is true for the entire concept of `*sync` functions in general.

**Comment by AsherGlick** [comment]
@Jummit Was this example good enough or is there more you would like to see?

**Comment by Jummit** [comment]
I understand your use case, but I still think this will do more harm than good.
Here is my reasoning:
If I call rpc("method") and `method` returns something, from which instance do I get the value from? Beginners could think that it's the value from one of the remote peers. It wouldn't work for all network modes, so `puppet`, `master` or `puppetsync` would all behave differently. If I'm master and call a master rpc, I do get the value, but if I'm puppet and call a master rpc, I don't.

I also don't think that this is ever really necessary, except if you use `remotesync` a lot. For reference, Unreal Engine's implementation doesn't have this feature.
This is all just a guess though.

**Comment by AsherGlick** [comment]
I had overlooked the case of `master` being called on the server and `puppet` being called on the client. Both of those will indeed cause the function to be called locally in a non-obvious way. Nearly all of my network calls are `remotesync` and I believe this feature to be as necessary as `remotesync` itself given that without it `remotesync` does not fulfill its full usefulness of replacing a call to `rpc()` followed by a call to the function itself. While I dont believe Unreal Engine not having a feature is a good reason for godot not to have it, I do believe that in its current state this proposal is too confusing due to the `master`/`puppet` interaction.

It may be better to go the route of letting rpcs return values over the network in which case you may have something where `rpc` returns a dictionary of promises.
``` gdscript
extends Node


func _ready():
	var peer = NetworkedMultiplayerENet.new()
	peer.create_server(33333, 10)
	get_tree().set_network_peer(peer)
	var returnval = await self.rpc("remotesync_function")[get_tree().get_network_unique_id()]
	print("Return Val: ", returnval)

remotesync func remotesync_function():
	return "Returned Value"
```
This may be too much overhead however if every rpc allocates an array of promises even when the functions they are calling have no return values, or useless return values. The useless return values may even be worse as they would cause additional network traffic while providing no value.


Or it may be better to have a unique function that will return things by forcing them to be called locally in addition to any other calls that may be made remotely.

``` gdscript
extends Node

func _ready():
	var peer = NetworkedMultiplayerENet.new()
	peer.create_server(33333, 10)
	get_tree().set_network_peer(peer)
	var returnval = self.rpc_sync("remotesync_function")
	print("Return Val: ", returnval)

remotesync func remotesync_function():
	return "Returned Value"
```
Though this is also slightly confusing with `*sync` being a keyword as well

I think in my use-case I will create a new function for `rpc_sync` in my own project and remove the use of "remotesync" which will solve my immediate issue. I am going to close the pull request and this proposal for now and make a new one in the future for the ability to generically return values from rpc instead of just from local function calls.

Thank you everyone involved for you time with this proposal.
