### ISSUE TITLE
TileSet Editor should allow multi-selection and duplication of Alternative Tiles

### ISSUE THREAD

**Issue by jummy0** [godotengine/godot-proposals#8792]
### Describe the project you are working on

A 2D platformer.

### Describe the problem or limitation you are having in your project

It is tedious to manipulate many Alternative Tiles at a time.  If I want to make flipped and rotated versions of all my tiles, I must methodically set the "Flip H", "Flip V", and "Transpose" checkboxes for all 7 alternatives of each tile (I have over 20 base tiles just for some basic grass Terrain).  Furthermore, after completing this task once, Godot crashed, undoing the process for me.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Assume all the Alternative Tiles have already been created.  7 Alternatives for each of my 20 Base Tiles.  Setting the flags for one row of my Alternatives currently takes 19 clicks: 1 to select each of the 7 Alternatives, and a total of 12 flags to be set per row.

19 clicks * 20 base tiles = **380 clicks**.

With multi-selection, this is reduced to **8 clicks**:
1. Select the 1st and 2nd columns of Alternative tiles
2. Select the 5th and 6th columns
3. Check "Flip H"
4. Select the 2nd and 3rd columns
5. Select the 6th and 7th columns
6. Check "Flip V"
7. Select the 4th through 7th columns
8. Check "Transpose"

Each base tile now has Alternatives for every combination of Flip and Transpose.

In case I ever decide to make *more* Alternatives for these base tiles, duplication would let me reuse common properties such as Collision or Terrain settings.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Multi-selection should behave analogously to that of Base Tiles.  Click-and-drag to make a rectangular selection, and hold shift to extend your current selection.

Duplication should be in the right-click menu of an Alternative Tile, analogous to the "Create an Alternative Tile" button when right-clicking a Base Tile.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know anything about editor plugins, but it sounds possible to do so.

### Is there a reason why this should be core and not an add-on in the asset library?

This feature completes a missing analogy between similar UI elements, streamlining their use.

**Comment by KoBeWi** [comment]
This is already planned, see https://github.com/godotengine/godot-proposals/issues/6415 (6th point), so closing.

Note that in 4.2 it's possible to set flip/transpose per placed tile, as opposed to setting it in the tileset. [There is a plugin](https://github.com/Portponky/better-terrain) that takes advantage of per-tile transforms in terrains.
