### ISSUE TITLE
Add `Export selected resource (without dependencies)` filter for export preset.

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot-proposals#8796]
### Describe the project you are working on

My project requires implementing update system of my own data package within the game. Mostly like a web game.Web game have to pack resources into PCKs and download it dynamically.The PCK file should not be too large.

The specific requirements are as follows:

1. Players can download a single executable program that only includes the entry scene(main scene), i call it `Launcher` like `game.exe`.
When this executable program runs,it runs the entry scene, it will check the version of the local data package and compare it with the version of the remote data package. This is done through the manifest.json file, which contains a record of the versions of the PCK and its MD5.
2. If the local data package version is too old and the PCK's MD5 does not match the one recorded in the server's manifest file, the program will automatically download it.
3. If the local data package version is up-to-date and there are no differences in the manifest file, the program do nothing.
4. After entering the main scene, it will scan and load all the data packages(PCK files), and then jump to the mainmenu scene. This mainmenu scene exists within the data package.

Exporting only the PCK can achieve this, but there is a dependency issue. 
To ensure that players can incrementally update only the modified data packages, I need to divide the PCKs into small enough packages, ideally one resource per PCK independently.

I don't need the PCK to have full dependency.

### Describe the problem or limitation you are having in your project

But the presets about `export selected scene (include dependency)` and `export selected resources (include dependency)` in Godot will pack the complete dependencies of the scene or resource into the PCK. At this time, there will be redundancy like below.

There has A.tscn , B.tscn, C.tscn.
![image](https://github.com/godotengine/godot-proposals/assets/1620585/7a8dab6f-b453-42e6-9a23-a0f3dc4268ac)
![image](https://github.com/godotengine/godot-proposals/assets/1620585/29c8a0a4-c965-4ec8-be01-936703650cd5)
![image](https://github.com/godotengine/godot-proposals/assets/1620585/0b23575e-86f9-4f2d-b8bd-932cb62941b5)

A dependent C
B dependent C
C dependent nothing 

Create three export presets to :
Pack A.tscn into A.pck.
Pack B.tscn into C.pck.
Pack C.tscn into C.pck.

![image](https://github.com/godotengine/godot-proposals/assets/1620585/f999b739-99e7-4769-9297-c4c7bf598c12)
![image](https://github.com/godotengine/godot-proposals/assets/1620585/d969dd00-f517-4916-8d35-21f0ff309667)

It seems that A.pck will contains a whole C.tscn resources inside as it's dependencies.
And B.pck will contains C.tscn resources too.

![image](https://github.com/godotengine/godot-proposals/assets/1620585/ad331956-d9ff-4f0f-8558-249c0b6e3158)
![image](https://github.com/godotengine/godot-proposals/assets/1620585/69adfde9-e8e2-4bf4-98c6-8a5fe6cd7e63)
![image](https://github.com/godotengine/godot-proposals/assets/1620585/38b09d90-577b-464a-9b6d-c987c200ea4e)

That is not a good thing for me. 

If I create lot of presets to pack PCKs. The PCK file will have too many redundance that out of control. 

The best flow for me is if c.tscn has export PCK, then PCK of A.tscn  and B.tscn  should not contains C.tscn.

But I know it's imposible ,because each preset is independent.

For me the best way is to export one PCK for one resource. 
Not like the Unity assetbundle，when we load PCK it not actually load all data into memery. It just maps the filesystem.
But the assetbundle is not like this, so it should deal with the dependencies.
That why I only want a independent PCK.

So for me a way to pack pck chunk to splite PCK independently is what I looking for.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

After all, I will load all the PCKs in the launcher anyway, and even if a single PCK has no dependencies, it does not affect its usage.

If PCKs can be exported without dependencies, I can even control which files are packed into the same PCK through a Python script. 
For example, I can pack all modified files into a patch.pck based on Git commit records. Or in a DLC branch, I can package all changes in the branch into a DLC.pck. Or I can scan the project and pack it into several PCKs with a chunk size of 10MB.

In any case, `export PCKs without dependencies` is very useful to me, especially for web games, as they require even smaller PCKs to dynamically load resources.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/1620585/f03c1533-51d4-47dc-85dc-641141d70e71)

Add a new export_filter `Export selected resources (without dependencies)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The EditorExportPlugin does not hook the _save_pack_file  process, not hook the _export_find_dependencies. It can't skip files to add in PCK by Skip().  I only can control the export_file to skip whole PCK file export.

### Is there a reason why this should be core and not an add-on in the asset library?

It's useful for web game-like dynamic download and load PCKs. This easy to build your own hot update/ Incremental update system.

**Comment by Zireael07** [comment]
If you try to export a resource without its dependencies, you'll end up with a broken, unusable resource...?

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/5992.

**Comment by chernjeff58-ux** [comment]
After using it for a while, I get the feeling that the Godot engine actually steers you toward shipping one big PCK.

If you split things up, every additional PCK drags its own dependencies along, whereas a single monolithic PCK loads the fastest.

When you only need a small patch later, you can still drop an extra PCK on top.
