### ISSUE TITLE
Allow auto-tiles to connect with each other if specified

### ISSUE THREAD

**Issue by Alzter** [godotengine/godot-proposals#88]
**Describe the project you are working on:**
I'm working on a 2D platformer game [(Link)](https://github.com/Alzter/TuxBuilder) with a built in level editor. I'm trying to add slopes by making them a separate auto-tile that makes corners slopes, but I want the autotile to connect with the main ground tileset seamlessly. I propose there is an option added that lets certain autotiles connect with other autotiles.

**Describe how this feature / enhancement will help your project:**
This enhancement could help me make slope autotiles that seamlessly blend in with the ground tiles, so I could easily implement slopes that could be used in the level editor.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/22513909/65321023-7c8bab80-dbe6-11e9-9ff7-932f28e64b4d.png)

**Describe implementation detail for your proposal (in code), if possible:**
I have no experience coding for Godot, but my idea is to have some sort of "Connect" menu for each autotile that allows them to connect to other auto-tiles when enabled.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm not sure if it's possible to adjust auto-tiles through GDscript.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It would help make seamless transitions between different auto-tiles and for me it could help make slope tiles.

**Comment by groud** [comment]
Please [read the rules](https://github.com/godotengine/godot-proposals/blob/master/README.md), and fill the template. I'll reopen if this gets fixed.

**Comment by Alzter** [comment]
> Please [read the rules](https://github.com/godotengine/godot-proposals/blob/master/README.md), and fill the template. I'll reopen if this gets fixed.

I updated it, can you re-open it now or do I need to adjust it more?

**Comment by MennoMax** [comment]
This is already possible by adding a script to the TileSet and overriding the virtual function _is_tile_bound in there. A "Connect" menu in the editor might be helpful though.

**Comment by YuriSizov** [comment]
Thanks for your proposal! Unfortunately, it seems there isn't much interest in it, even after all this time, so I'm going to close it. But check out the new TileMap system in Godot 4.0, maybe it'll work for you in another way!
