### ISSUE TITLE
Ability to write godot console output to log file

### ISSUE THREAD

**Issue by theromis** [godotengine/godot-proposals#8803]
### Describe the project you are working on

Creating a systemd service to run dedicated server

### Describe the problem or limitation you are having in your project

Not getting any log output neither `syslog` nor `file` or `append` type

https://github.com/godotengine/godot/issues/86785

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implementing --log /path/to/log.file in need of file logging states we working with file rather than redirect detection.
For logrotate important to handle SIGHUP to reopen log file.

I think as a future improvement same as predefined --headless parameter might be a good idea to have:

* --background (fork after start)
* --pid /path/to/pid.file (store process ID to be able to use `Type=forked` in systemd unit file it will help to restart process if it dies)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

By specifying logging ability we must flush on every line of code

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Unfortunately currently impossible to run godot in background and get to know what heppening

### Is there a reason why this should be core and not an add-on in the asset library?

This is pretty basic feature and it needed for dedicated servers

**Comment by AThousandShips** [comment]
Note that this is already possible with project settings, but adding command line options for it would be useful

**Comment by theromis** [comment]
@AThousandShips thank you for a note, it reminded me other question:
Let's say I have a new release and have to export game to 3 platforms (iOS, Android, Linux) for:
* iOS - default setup
* Android - change `Mobile` to `Compatibility` mode
* Linux - turn debugging on and set specific log path
Is there a way or recommendation how I can automate this process?

**Comment by AThousandShips** [comment]
Just add suffixes to the options, like `debug/file_logging/enable_file_logging.mobile` or `debug/file_logging/log_path.android`, don't remember exactly what tags are available

**Comment by theromis** [comment]
thank you, seeml like should solve an issue
