### ISSUE TITLE
Show error when attempting to compare the type of statically typed variable

### ISSUE THREAD

**Issue by diklor** [godotengine/godot-proposals#8805]
### Describe the project you are working on

All

### Describe the problem or limitation you are having in your project

There is no small feature for typification

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Show a warning / error when checking the type of a variable whose type is already defined via typeof()
(In any case, it can be changed in the settings)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
func parameter(string: String) -> void:
   if typeof(string) != TYPE_STRING:      return
   #ERROR: Attempt to compare the type of a static variable
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but it's just convenient for statically typed code

### Is there a reason why this should be core and not an add-on in the asset library?

GDScript

**Comment by AThousandShips** [comment]
This should be a warning not an error (only warnings can be controlled in the settings) and should default to warning, at most
