### ISSUE TITLE
Add a way to debug AnimationTree state machines and blend nodes at game run-time

### ISSUE THREAD

**Issue by CrayolaEater** [godotengine/godot-proposals#8820]
### Describe the project you are working on

Addition of a system to visualize the animation state machine and blend nodes flow at game run-time, similar with unity's.

### Describe the problem or limitation you are having in your project

I have a complex system with multiple layers of state machines and blend nodes and its pretty complicate to follow each transition and animation travel at run-time. There are situations when a transition is not triggered or a path to a certain animation is not reachable and that gets very hard to find especially in a graph with dozens of animation nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since all the playing animations/transition will become visible I think its pretty straightforward how this will make the flow much easier to follow and improve.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We already have this system but only works in the editor. My suggestion is this:
- run the game
- go to the remote tab
- select a specific AnimationTree in the scene
- the animation state machine playback will be visible in the corresponding window (same as in the editor  mode)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Right now  I'm printing the whole traversal in the console which is a very primitive method.

### Is there a reason why this should be core and not an add-on in the asset library?

I think this is a must that godot should really have, it will improve the overall debug features of the engine.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6111.
