### ISSUE TITLE
Add text wrapping functionality to buttons

### ISSUE THREAD

**Issue by bhiltune** [godotengine/godot-proposals#8823]
### Describe the project you are working on

A dialogue-heavy game, utilizing a system similar to [Disco Elysium](https://www.gameuidatabase.com/uploads/Disco-Elysium05242021-082736-79410.jpg). Some of the dialogue response options you can give are long enough to demand multiple lines of screen-space for the text.

### Describe the problem or limitation you are having in your project

Currently, the Godot Button does not support Text Wrapping (Autowrap) functionality, as you would see in Label nodes, for example. There are options for Text Overrun Behavior, but either way, the appearance of the button is currently limited to contain a single line of text.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an "Autowrap mode" selector to the Button nodes, similar to what Label has.

![Screenshot 2024-01-07 173019](https://github.com/godotengine/godot-proposals/assets/52609762/e2090fa7-8aec-4557-812d-e167685dc3f8)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This would possibly be as simple as reusing code from the Label node regarding the autowrap feauture and making sure that the Button resizes correctly to the new area, remains clickable etc. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There are some hacky workarounds involving the use of [child nodes](https://youtu.be/R7N2ew2rezA), but these have their own limitations and annoyances. 

Given that this is a very minor tweak that would improve workflow considerably for certain use-cases, I feel it's fair to add this to the engine.

### Is there a reason why this should be core and not an add-on in the asset library?

A small modification to the functionality of a core node doesn't merit an add-on.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/87025.
