### ISSUE TITLE
Implement a Resource type to impot excel file, or make a special folder such as "StreamingAssets" folder like unity

### ISSUE THREAD

**Issue by isJDongYa** [godotengine/godot-proposals#8824]
### Describe the project you are working on

a 2d survival game

### Describe the problem or limitation you are having in your project

I use excel to edit game object data with c#, it works when i am in editor , but when i exported the project, the excel file didn't pack to the "build exe", this is so confuse to me.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I wish there is a method to pack the excel(.xlsx) file, such as copy file directly or import it as resource.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

---

### If this enhancement will not be used often, can it be worked around with a few lines of script?

---

### Is there a reason why this should be core and not an add-on in the asset library?

---

**Comment by KoBeWi** [comment]
In export dialog there is an option to include extra files, by extension.

**Comment by isJDongYa** [comment]
> In export dialog there is an option to include extra files, by extension.

Oh, my wrong, i haven't found the option before.
It works!

And bty, is there any way to reference an dll(steam_api64.dll) in godot editor instead of editing the .csproj file in vscode?(and not use the visual studio IDE, just use the godot editor)

**Comment by Calinou** [comment]
Closing, as this already implemented.

> And bty, is there any way to reference an dll(steam_api64.dll) in godot editor instead of editing the .csproj file in vscode?(and not use the visual studio IDE, just use the godot editor)

Please use other [community platforms](https://godotengine.org/community/) for support questions, as GitHub is for bug reports and feature proposals only.
