### ISSUE TITLE
Add a way to toggle Android status and navigation bars at runtime

### ISSUE THREAD

**Issue by sosasees** [godotengine/godot-proposals#8826]
### Describe the project you are working on

a game with
- pre-game menus
- a pause menu

### Describe the problem or limitation you are having in your project

> i want the status bar and navigation bar to hide during gameplay so they don't distract me
>
> but i want to see the system bars during the menus so i can quickly check battery status and switch apps
>
> — user story

the first part is done because the system bars are hidden by default.
but i can't do the second part because i found no way to toggle system bars in GDScript

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

adding GDScript methods to
- show system bars
- hide system bars

would make it possible to solve the user story.

making separate methods to
- toggle status bar
- toggle navigation bar

would be even better because then games could also
- show navigation bar and status bar if the screen is tall enough
- show navigation bar but hide status bar if the screen is not so tall (a lot of Samsung apps do this in Landscape mode)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the GDScript methods would be:

- ``OS.set_status_bar_visible( bool value )``
- ``OS.set_navigation_bar_visible( bool value )``

to improve readability of the system bars, we could also set their background color (but that's out-of-scope for this proposal, and as a workaround we could always place ColorRects behind the system bars):

- ``OS.set_status_bar_color( Color background_color )``
- ``OS.set_navigaton_bar_color( Color background_color )``

### If this enhancement will not be used often, can it be worked around with a few lines of script?

i believe not:
i asked 1 time each across 2 Godot forums and no-one could answer
([no longer official forum](https://godotforums.org/d/30489-android-toggle-system-bars), [official forum](https://forum.godotengine.org/t/android-show-system-bars-when-the-game-is-paused/40564))

### Is there a reason why this should be core and not an add-on in the asset library?

this will benefit _all_ paid games (and many free games) because they _all_ have pre-game menus and a pause menu

**Comment by syntaxerror247** [comment]
@sosasees You can try my Android Plugin [System Bar Color Changer](https://github.com/syntaxerror247/godot-android-system-bar-color-changer), currently it do not have the functionality to hide system bars but I can add that. It has translucent system bars, I think that can help.

**Comment by syntaxerror247** [comment]
@sosasees You can try my Android Plugin [System Bar Color Changer](https://github.com/syntaxerror247/godot-android-system-bar-color-changer), It has the functionality to change system bars color and enable translucent system bars.

Currently you cannot toggle them seperately but you can use `DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_EXCLUSIVE_FULLSCREEN)` to toggle immersive mode.

**Comment by llama-nl** [comment]
in Godot 4.4 this feature is implemented with this PR: https://github.com/godotengine/godot/pull/96208#issue-2491653595

**Comment by AThousandShips** [comment]
Someone relevant to this topic would be better to ping than a random maintainer, please don't ping random people

**Comment by syntaxerror247** [comment]
> Probably, In Godot 4.4 this feature is implemented with this PR: https://github.com/godotengine/godot/pull/96208#issue-2491653595

Haven't I said the same thing in my above comment.
Quoting from PR: 
> The new Android immersive mode logic is hooked to the DisplayServer#window_set_mode(...) and DisplayServer#window_get_mode(....) apis which means that game logic can also leverage the new functionality to query and toggle immersive mode at runtime on Android

That time, I have only kept this proposal opened because it also asks to provide an option to change the system bar color at runtime.

**Comment by syntaxerror247** [comment]
@AThousandShips We can close this proposal now. Few weeks ago, I have discussed about the color part with `m4gr3d` and we agreed to not implement this because it will be android only and easily doable with plugin.
![IMG_20241207_173503.jpg](https://github.com/user-attachments/assets/6fe6f278-a4b5-45a0-a557-44f9f7fb484d)
