### ISSUE TITLE
Add way  to optimize release builds for size

### ISSUE THREAD

**Issue by sydist** [godotengine/godot-proposals#8833]
### Describe the project you are working on

A simple game.

### Describe the problem or limitation you are having in your project

A simple project build in godot on Windows is 70 MBs, that's extremely large. and the only way I know of to reduce it is to rebuild godot or something.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow users to remove unused parts of the engine on build.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Perhaps add some sort of screen where you can strip out the parts of the engine that aren't necessary for your game, similar to the "Customize Engine Build Configuration" screen.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think you currently have to rebuild godot.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't believe an addon can do this.

**Comment by YuriSizov** [comment]
There is no way to do this without rebuilding Godot. Your project is just your code and your assets. The rest of the size comes from export templates, which are pre-compiled for the complete feature set.

You can only achieve what you want by recompiling export templates with features you don't need disabled. Which is what the "Customize Engine Build Configuration" is for. See also https://docs.godotengine.org/en/stable/contributing/development/compiling/optimizing_for_size.html.

**Comment by sydist** [comment]
Interesting, might it be worth it to have a set of community maintained optimized export templates?

**Comment by sydist** [comment]
Thanks a lot anyway!

**Comment by YuriSizov** [comment]
> Interesting, might it be worth it to have a set of community maintained optimized export templates?

This can be done, if someone is willing. However, you would have to trust whoever maintains the builds that there is nothing malicious in them. Code signing might also be an issue (but the same goes if you compile a custom build yourself). And of course, they would need to update these templates with each stable release. It can be automated though.

You should give building Godot a try, I think. It's not that complicated.
