### ISSUE TITLE
Add a glTF2 scene exporter

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#885]
**Describe the project you are working on:**
3d multiplayer game

**Describe the problem or limitation you are having in your project:**
I wish to export my scene to a standardized exchange format.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would be useful to expose an engine api for a scene exporter. The ideal case is that we can click on a scene and then export it as a gltf2 file.

It may not be possible to be lossless exporting from scene to gltf2 and back to scene, but it would be helpful for these cases:

* Easy export to sketchfab
* Easy export to blender
* Storing scenes in a standard format that can be sent to another engine / renderer / future godot version.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This is a description of the architecture of the gltf plugin at https://github.com/godot-extended-libraries/gltf.

I split the importer into a glTF2 document and an importer. This allows us to modify the document to be a exporter.

This also allows for extensions through https://github.com/godotengine/godot-proposals/issues/1463 for import and export.

PRs:

* https://github.com/godotengine/godot/pull/42198 Move to a module.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Have to port 3000 lines of core module code to gdnative because it includes the importer code too.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Core code is large and I do not want to duplicate it. This moves the gltf2 importer into a doument and two plugins (import and export). If I make the gltf2 exporter a GDNative plugin which is possible, I can't do this without duplication. glTF runtime import is also a requested feature from the community and also export.

**Older Proposal**
<details><summary>Click for the old proposal.</summary>
<p>

@reduz I require a Scene Exporter api exposed to gdnative. Importing scenes has a large dialog of options, so would exporting scenes.

```
<iFire> reduz: is roundtrip from godot to gltf2 part of the roadmap? 
<reduz> iFire: not really
<Calinou> why would you want to export glTF from a game engine?
<Calinou> unless we get a level editor…
<iFire> Calinou: why not?
<Calinou> then it would start making *some* sense
<Calinou> (and not that much)
<iFire> Calinou: well it just feels more proper to import any format and then export as gltf2. A) I can then put it in sketchfab B) Save a copy of the scene in gltf format because it's changed now
<iFire> C) move the scene to another game engine ;)
<Calinou> again, it's not relevant until we get a level editor
<iFire> I thought the scene editor is a level editor
<Calinou> once we have that, it has one main use: making renders in Blender or similar. Only really high-end games can afford this, so it is probably not a priority at all
<Calinou> it is not quite one. it doesn't let you create actual geometry using a GUI (CSG or similar)
<iFire> I don't care about, that's a workflow thing
<Calinou> also, remember that Godot and Blender materials are not fully compatible anyway
<iFire> some people use csg others use models
<Calinou> Eevee should be mostly similar, but you're going to have to wait 5 years until most people use it :/
<iFire> Calinou: but gltf is a workable process for standardizing the import
<iFire> there are blender import pipelines for gltf2
<Calinou> how good are the importers, too?
<iFire> https://github.com/ksons/gltf-blender-importer <-
<iFire> apparently the importer and exporter are different projects
<iFire> Calinou: anyways for my use case I don't need to go all the way to blender
<Akien> Well I think it would be nice to have a gltf2 export feature as a plugin, someone just needs to write it
<iFire> Akien: Can you expose the apis?
<Akien> There is no huge use case, but it's still nice to have. I like the idea to export a 3.1 scene as gltf2 and import it against in Godot 8
<iFire> I don't know what I need
<Akien> iFire: Then how would I know? :p Best would be to start and see what you are missing.
<Calinou> GDScript would be too slow for this, probably
<Calinou> (for large scenes)
<Akien> I don't think so.
<Akien> Blender's plugins are in python :)
<iFire> Akien: I was able to get a fbx importer but the gdnative interace has a bug with the import plugin and scanning for the fbx extension. karroffel is on it.
<Calinou> do remember that Godot isn't a 3D DCC, it stores vertices and everything differently
<iFire> Calinou: I don't see how it's impossible
<iFire> those are only things that make it more difficult
<Calinou> is it worth spending time on right now?
<iFire> I might spend time for fun :)
<iFire> or I can make a game lol
<Calinou> I don't find that task particularly fun
<Calinou> I'd find new renderer features funnier
<Calinou> or, you know, a 3D level editor
```

</p>
</details>

**Comment by Hersir88** [comment]
Any progress on this ? :)

**Comment by fire** [comment]
I've updated the proposal and started a pr chain on Godot Engine master.

**Comment by wajrou** [comment]
Any progress? :-)

**Comment by Calinou** [comment]
> Any progress on exporting to blender through glTF2? :-)

This is now implemented: https://godotengine.org/article/introducing-the-godot-gltf-2-0-scene-exporter
