### ISSUE TITLE
Implement importing HDR images as tonemapped LDR (8-bit) images

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#886]
**Describe the project you are working on:**
3d multiplayer game

**Describe the problem or limitation you are having in your project:**
I want to use openexr for standard texture usage too.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Take a hdr (openexr) image, unable to make it a 8bit image.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Take the hdr image and tone map it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Image modification is cpu intensive.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Import code is already being owned by the built in openexr module, so have to modify the openxrr module.

**Comment by Calinou** [comment]
Out of curiosity, what do you need a 8-bit image for? Shouldn't importing an HDR image once be more efficient?

**Comment by fire** [comment]
I wanted to use openexr as a file format like psd or krita. Openexr can store both channels (rgba, and any thing else) and layers.

Why is this useful? 

1. I can store all the properties of a PBR material as one image. This requires some tooling to reassign non rgba openexr channels to the proper ones in Godot.
2. Downconvert a hdr image to rgba8 so one can see it via tone mapping operators. Like screenshots of the linear stages of Godot can be visualized. I think this can be done via https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-convert but you can't specify the tone mapper.

Note:

Also, this was my first few first issues from 2018. It brings back memories of a different time.
