### ISSUE TITLE
Modify the skeleton bone pose by handles in the 3D editor

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#887]
**Describe the project you are working on:**
3d multiplayer game

**Describe the problem or limitation you are having in your project:**
Cannot modify pose of the skeleton ik and the skeleton in the editor viewport.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Create subgizmos.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Create a system that is similar to handles by adding a small transform gizmo, then we can use those handles to handle bone pose modification.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Editor ui cannot be easily changed in script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Viewport ui for gizmos is deeply integrated with the editor.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/584, as that issue has more up-to-date information.
