### ISSUE TITLE
Make `print_rich` url tag  support meta_click.

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot-proposals#8879]
### Describe the project you are working on

I'm writting my owne logger  wraped by `print_rich`. And I need to make log message can jump to where it print.

### Describe the problem or limitation you are having in your project

I found it said it support url tag then i try.
![image](https://github.com/godotengine/godot-proposals/assets/1620585/9d81ef4c-4986-443a-be79-37f1192ff71e)

![image](https://github.com/godotengine/godot-proposals/assets/1620585/fdf77c7a-5e9d-4e08-bab8-a447b34e4ae2)

But it seems that it just support  to hint url right ,not support action.
RichtextLabel need us to connect meta_click signal and archive our own action to handle url click.
But I don't know where to connect meta_click signal of EditorLog. I can't visit  EditorLog. The EditorInterface not allow me to visit EditorLog in gdscript.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make some ways to connect the EditorLog meta_click signal will work for me .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For me is easy to add a `EditorInterface::get_editor_log` to get the richtextlabel and connect it's meta_click to a plugin function.

Or the more specialized way to encapsulate "register_url_tag_handler(callback: Callable)" would be:
```C++
void EditorInterface::register_log_url_tag_handler(callback: Callable[[str]]);
```

Is there any idea?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Seems impossable.  I can visit root editor control, try to get EditorLog Node, but the node are named automatic every time it create.

```gdscript
var control = EditorInterface.get_base_control()
```

![image](https://github.com/godotengine/godot-proposals/assets/1620585/94689ac2-7fff-4213-a36b-99b3f97d58e5)

So I can't deal with gdscript.

### Is there a reason why this should be core and not an add-on in the asset library?

It is just an unimplemented feature of the 'print_rich' method, which is relatively obscure and not essential. If it needs to be implemented, an interface needs to be exposed in the 'EditorInterface' to connect the URL click signal.

**Comment by Calinou** [comment]
EditorLog could be configured to handle URLs with `OS.shell_open()` automatically by implementing the `meta_clicked` signal.

**Comment by kaluluosi** [comment]
> EditorLog could be configured to handle URLs with automatically by implementing the signal in the editor C++ Code.`OS.shell_open()``meta_clicked`

Yep, default behavior is use OS.shell_open, and I think maybe people who plugin developer will need to archive them self meta_click.
