### ISSUE TITLE
PLEASE SUPPORT THE MULTIPLE INHERITANCE IN GDSCRIPT.

### ISSUE THREAD

**Issue by TheinThanHlan** [godotengine/godot-proposals#8880]
### Describe the project you are working on

...................................................

### Describe the problem or limitation you are having in your project

................................................

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

.........................................

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

............................................

### If this enhancement will not be used often, can it be worked around with a few lines of script?

.......................................

### Is there a reason why this should be core and not an add-on in the asset library?

.....................................

**Comment by AThousandShips** [comment]
This is not a valid post, please spend the minimum amount of work and respect the process

**Comment by AThousandShips** [comment]
Please see things like:
* https://github.com/godotengine/godot-proposals/issues/6416

For related things, but this is now how to propose a change
