### ISSUE TITLE
Make `auto_translate` state inheritable

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-proposals#8897]
### Describe the project you are working on

The Godot Engine.

### Describe the problem or limitation you are having in your project

`auto_translate` doesn't work correctly on some complex built-in `Control`s (e. g. `FileDialog`), due to the children being unaware if its parent's `auto_translate` is enabled or not.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a new `auto_translate_mode` member, that would work like `process_mode`, having values like `INHERIT`, `ALWAYS`, and `DISABLED`. This would not only fix the issue, but allow for some more advanced scenarios for users (e. g. having an entire portion of the UI not being translated).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

To preserve compatibility, it would work as follows:

- `auto_translated_mode` would be added with just the `INHERIT` (default) and `ALWAYS` values.
- If `auto_translate` is disabled, it would be the same as setting `auto_translated_mode` to `DISABLED`.
- Once we enter a phase were we can break compatibility again (likely Godot 5), `auto_translate` is removed and `DISABLED` is added to `auto_translate_mode`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really, since this is for built-in nodes.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by MewPurPur** [comment]
I can attest to needing these advanced cases. Disabling auto-translate on everything is so daunting that I just never got to it.

The compatibulity-breakage this change implies is also scary, but it's for the greater good I think.
