### ISSUE TITLE
Add clamped additive mode for 2D lights

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#891]
**Describe the project you are working on:**
A game with rather simple lighting.

**Describe the problem or limitation you are having in your project:**
So I wanted a simple lighting system for my game, i.e. lights are circles around light sources. But that alone would be too simple, so they can also have different colors.

And I came into a problem - overlapping lights will have their brightness combined, which is not what I'd like it to look. Check this visualization of the problem:
![image](https://user-images.githubusercontent.com/2223172/53688403-add48500-3d43-11e9-9420-a98fdd130565.png)
![image](https://user-images.githubusercontent.com/2223172/53688409-bd53ce00-3d43-11e9-9839-cf74611ada0f.png)
This can be partially avoided by using lights in mask mode, but this solution has problems with colors. So AFAIK, there's no way to properly have the lights overlap.

Right now I'm using an awful hack. My whole game view is rendered in a separate viewport. Every light is removed from its parent and moved to an upper space over the viewport (they are coded to follow the light source). The lights are drawn over a ViewportContainer which has a black rectangle underneath and is masked with the lights. This just sounds terrible, doesn't it? xd While visually it looks ok, I'd rather avoid having this weird setup, because it has some problems (like, I can't take over camera, because it moves in the space where ViewportContainer is, so I can't move my game view).

Workaround aside, people shouldn't be supposed to do such setups just to achieve a simple effect.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The general way to use 2D lights is to have black CanvasModulate and use additive lights. What would be helpful is to have the lights light up the canvas only up to original color (so no over-bright or something).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
No idea how lights work, so no code. But the feature itself could be available as an option (checkbox) in lights 2d.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Maaaybe it's possible with a light shader, but I never found any solution.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I wouldn't mind if this was possible actually.

**Comment by KoBeWi** [comment]
I just found a workaround. Instead of lights, I'm now using sprites with additive drawing mode, drawn over screen-sized black rectangle which then draws over everything else in multiplicative mode. This solved all my light2d-related problems, so closing this proposal (no one else supported it anyways).

**Comment by PoisonousGame** [comment]
> I just found a workaround. Instead of lights, I'm now using sprites with additive drawing mode, drawn over screen-sized black rectangle which then draws over everything else in multiplicative mode. This solved all my light2d-related problems, so closing this proposal (no one else supported it anyways).

Is there any example and implementation method? I want this effect. It's a pity that godot doesn't support such a feature.

**Comment by KoBeWi** [comment]
Here's example scene (Godot 4.0):
[LightScene.tscn.txt](https://github.com/godotengine/godot-proposals/files/9540340/LightScene.tscn.txt)
This actually looks like something that could be an addon 🤔 But the effect is pretty limited. It doesn't support shadows, just simple additive lights (kind of retro effect I think). Shadows are possible, but you'd need to replicate occluders in the light viewport, which is rather complicated to do.

**Comment by hsandt** [comment]
I totally forgot to comment on this, but basically I think the proposal still makes sense because as @KoBeWi noticed, the workaround of using pure masks doesn't support shadows. In fact, in my own game I combined Light2D just for shadows and light masks and gives weird edge cases such as seeing darker shades in the back of the character whereas it's right in the middle of 2 lights:

<img width="962" height="572" alt="Image" src="https://github.com/user-attachments/assets/b1f97e39-4cf2-4cf4-81e6-b22d2a375d6f" />

or the character's own torch light making the top-left flame look _darker_:

<img width="962" height="572" alt="Image" src="https://github.com/user-attachments/assets/f54d5dce-7706-4325-a2c4-a5f91b8cd539" />

(note that I use semi-soft lights for retro game effect aka color banding on the mask / light textures)

Where summing lights but clamping the sum would do exactly what I want.
