### ISSUE TITLE
Have community-made custom splash logos for every new release

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#894]
**Describe the project you are working on:**
A NES clone game.

**Describe the problem or limitation you are having in your project:**
Some nice splash logo my game.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would be nice if the project had a contest to use a custom logo the comunity could create, similar to how blender has custom splash screens in every release.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It would be a comunity contest, where the godot devs pick the best splash animation, similar to this tweet:
https://twitter.com/TheTransmogrify/status/1262054867302047747

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's more of a comunity improvement and aesthetical newer logos.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not really requires coding or addons, is more of a proposal to the comunity.

**Comment by groud** [comment]
For now, the current implementation of boot splash screen only allows for fixed images, its goal is currently to hide the fact it's loading things for a game to be ran. The problem with animated splash screens is that you would need those things to be loaded already, so basically even with an animation, you would still need a fixed image first.

It's very unlikely we are going to do something like that, as, during testing, you don't want to waste time seeing an animation while your game could already be running.

A simple solution to make those animations accessible would be to make a dedicated category in the asset store. But the user will have to install it. We will very unlikely force an (almost) useless animation for everyone.

**Comment by ca3games** [comment]
@groud  Ah, never considered it.
When if animated logos aren't a solution.
Then I think a simple comunity made logo or illustration for every release would be enough.
Similar to blender having custom splash for every version.

**Comment by Calinou** [comment]
Closing due to lack of support (see the above comments and general lack of activity).
