### ISSUE TITLE
Make the Script Editor's parser execute sooner on edit after error was found

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot-proposals#8945]
### Describe the project you are working on

Generally contributing to the engine.

### Describe the problem or limitation you are having in your project

I write code and I'm sure a lot of people reading this do too. I can make mistakes for a variety of reasons and the code parser is generally pretty good at telling me.

But it would also be nice if the **Script Editor** told me I fixed them right.
Suppose you misspell the name of a method. As you're writing the rest of the code an error will pop up, appropriately. You will then "fix" the code, but have to wait a bit to make sure that you did it correctly.

This wait time does add up. It's especially more noticeable for beginners, as they're likely to make more mistakes. It's overall a bit clunky to not see the errors disappear sooner.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the parser execute way sooner **if an error is known to exist**.

The time should depend on the user's `text_editor/completion/idle_parse_delay`, of course.
It could either be a hardcoded number of "half the time than usual", or exposed as a separate **Editor Setting**.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Unsure what to put here.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You could decrease the `text_editor/completion/idle_parse_delay` Editor Setting to something more comfortable for your needs. But it's not always nice. For some users, myself included, it makes the editor feel very "petty" or otherwise annoying to deal with.

_"Yes, I know! Of course there's an error, I wasn't even done writing the full thing!"_

### Is there a reason why this should be core and not an add-on in the asset library?

The Script Editor is core and as far as I know there is no way to trigger the code analyser early.

**Comment by Zireael07** [comment]
I didn't know I needed this until I saw that...

**Comment by Mickeon** [comment]
Right? Sometimes it's the small things you do not think about.

**Comment by DanielSnd** [comment]
![QuickerParseIfErrors](https://github.com/godotengine/godot-proposals/assets/9072324/df2eb754-f63d-4dde-a0c2-d68f31f383d6)
Just tried a quick and dirty implementation and damn, that feels nice D: indeed I did not know I needed this until I saw this.

I just went into `code_editor.cpp` and changed the set_error_count method to change the wait_time on the idle timer based on whether or not errors were present:

```c++
void CodeTextEditor::set_error_count(int p_error_count) {
	error_button->set_text(itos(p_error_count));
	error_button->set_visible(p_error_count > 0);
	if (!p_error_count) {
		_set_show_errors_panel(false);
		idle->set_wait_time(EDITOR_GET("text_editor/completion/idle_parse_delay"));
	} else {
		idle->set_wait_time(EDITOR_GET("text_editor/completion/idle_parse_delay_if_errors"));
	}
}
```

I believe a proper implementation would want to cache those values and perhaps have a bool to check if the wait time is already set to the correct time so it doesn't just keep re-setting, but I believe it shouldn't be too hard to implement properly?

**Comment by Mickeon** [comment]
Honestly, setting the wait time doesn't actually matter too much. Getting the editor setting is a much bigger bottleneck and it tends to be cached.

**Comment by DanielSnd** [comment]
> @DanielSnd will you develop the feature further? Otherwise, I could give it a shot doing it myself and open up a PR.

Feel free to go ahead, I'm not confident enough on my C++ skills to do so yet. For now just watching, reading and learning how these things work.
