### ISSUE TITLE
Add a batch reimport possibility

### ISSUE THREAD

**Issue by vPumpking** [godotengine/godot-proposals#8955]
### Describe the project you are working on

Shifting project from Godot 3 to 4

### Describe the problem or limitation you are having in your project

This project has a huge amount of data such as images, and they all need to be reimported. I'm forced to do this by hand, one by one

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There could be a "reimport resources ..." entry in the `Project` menu. It would open a popup asking which types of resources (like pngs, materials,...) to reimport and then when OK is clicked it would do it for you.
![image](https://github.com/godotengine/godot-proposals/assets/121762735/7be6318f-9869-494a-a28c-5087a41549cd)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would have a function with a loop iterating in every folder of the project and reimporting files with a certain type, like that:
```
for file in currentFolder:
    if file is folder:
        change currentFolder to it
    if file is file:
        if file is resource:
            reimport it
        if file is the last of the folder:
            if currentFolder != root:
                change currentFolder to parent folder
            else:
                stop
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know

### Is there a reason why this should be core and not an add-on in the asset library?

It would be more convenient, because an addon is a huge thing only for this

**Comment by Calinou** [comment]
> and they all need to be reimported

Out of curiosity, why do you need to reimport all resources in the project? Could you describe the specific use case where doing so is required?

**Comment by vPumpking** [comment]
> > and they all need to be reimported
> 
> Out of curiosity, why do you need to reimport all resources in the project if you haven't changed any import option? Could you describe the specific use case where doing so is required?

I shifted my project from gd3.5 to 4.2 and all the png files need to be reimported, I don't why

**Comment by AThousandShips** [comment]
Migrating a project will reimport anyway because the files are handled differently, there's no `.import` folder

**Comment by vPumpking** [comment]
> Migrating a project will reimport anyway because the files are handled differently, there's no `.import` folder
> 
> So if they weren't imported, they're not in the project at all after upgrading 

In my project, if I try to use any resource without reimporting it, it makes an import error `!resource_is_usable() returned true`

**Comment by AThousandShips** [comment]
That sounds like a bug in the project migration tool and not something we need a feature for

**Comment by vPumpking** [comment]
> That sounds like a bug in the project migration tool and not something we need a feature for

Ok I'll try redo the migration and then give an update

**Comment by vPumpking** [comment]
I tried many ways to do the migration, and I think I know what the problem is: under godot 3, the import folder is `res://.import`, whereas it's `res://.godot/imported` under 4.x. The thing is, I fon't know why, that only meshes and scenes from `.import` are copied into `.godot/imported`, every other file resource remains still in the `.import` folder, xhich is not recognized.

**Comment by vPumpking** [comment]
I get 22291 errors saying `• editor/editor_file_system.cpp:2286 - Condition "!importer.is_valid()" is true. Continuing.`

**Comment by vPumpking** [comment]
it worked, but this is still a bug that needs to be fixed
should I close this issue?

**Comment by Mickeon** [comment]
If you feel like you no longer need the feature you have proposed, you can close this proposal. If there is something that has not been reported yet feel free to open a [new issue on the main repository](https://github.com/godotengine/godot/issues). Judging by the previous conversations, it seems like the project converter itself is a bit at fault here.
