### ISSUE TITLE
Finding child node by type

### ISSUE THREAD

**Issue by DevPhusion** [godotengine/godot-proposals#8993]
### Describe the project you are working on

I'm working on an combat, action-packed 2D game

### Describe the problem or limitation you are having in your project

I wanted to get a node with a specific type from a parent node but there was no method for it yet, so I had to made an entirely new method for it which was annoying. This is a problem I've encounter in some of my other projects as well and it is tedious to have to reprogram it (or copy the code from another project).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I want a method that find a child with a specific type in a parent node. This is different from the GetNode<Type>("path") because it doesn't need the path of a specific child node. It will work similar to GetComponentInChildren<Type> in Unity

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will be a simple thing to add, there's already a FindChild() method but it only works for name pattern, so we can just reuse the code and change it to check for the type specified instead of name patterns.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around in a few lines of code but I think it is much better if this is in the core, it will save the process of remaking the method and it will take up less memory and processing power than the work around method.

### Is there a reason why this should be core and not an add-on in the asset library?

The reason why this shouldn't be an add-on is because it's a small quality of life feature and won't really fit as an add-on. It can also be implemented in the base Godot Engine easily and will benefit all developers in my opinion.

**Comment by AThousandShips** [comment]
This would essentially be `find_children` but limiting the result to one
