### ISSUE TITLE
iOS template need rebuild with iOS 13 SDK

### ISSUE THREAD

**Issue by kruglinski** [godotengine/godot-proposals#90]
**Describe the project you are working on:**
Any project that use iOS template

**Describe how this feature / enhancement will help your project:**
According to Apple iOS Apps submit guide,  "Starting April 2020, all new apps and app updates will need to be built with the iOS 13 SDK and support the all-screen design of iPhone XS Max or later."

https://developer.apple.com/ios/submit/

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by Calinou** [comment]
I think this can be submitted to the main Godot repository, as this will eventually be a requirement, not a "nice to have" feature.

**Comment by kruglinski** [comment]
Sorry, I'm confused by the new issues submit workflow of Godot repository, so I follow the guide to here.

if this neither a Bug or Feature / Enhancement , I don't known where I can submit it

![p1](https://user-images.githubusercontent.com/2869425/65381625-eb245280-dd27-11e9-9e8a-db32483f72e2.png)

![p2](https://user-images.githubusercontent.com/2869425/65381624-eb245280-dd27-11e9-97d0-a31171da8c08.png)
