### ISSUE TITLE
Add support for node sorting when importing Blender's .blend files

### ISSUE THREAD

**Issue by idealarealo** [godotengine/godot-proposals#9019]
### Describe the project you are working on

A 3D game using a MeshLibrary imported from Blender

### Describe the problem or limitation you are having in your project

Items order in the MeshLibrary is the same as Blender's objects creation order, not the position. To change the creation order in Blender I need to duplicate items...

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a control to the Advanced Import Settings of the .blend file to choose the node sorting algorithm (thus the item index).
If I choose "Sort by name", the meshes are imported in alphanumeric order.
![Godot4_meshlib_order](https://github.com/godotengine/godot-proposals/assets/113707830/af637c26-3969-4f04-a5bf-52a2b5251ad4)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

no need to remap MeshLibrary item indexes

### If this enhancement will not be used often, can it be worked around with a few lines of script?

yes, mapping old blender-indexes to new name-ordered indexes

### Is there a reason why this should be core and not an add-on in the asset library?

It's an improvement to an existing core feature

**Comment by UtterlyMagenta** [comment]
I have needed this as well, not for use with MeshLibrary specifically, but for levels imported from Blender via GLB files where it just looks messy to inspect a scene when everything is in Blender’s object creation order.

While it’s possible to work around using an EditorScenePostImport script, I think this should be an option in core, not just for the Blender importer for the glTF importer in general.

```gdscript
func _post_import(scene):
	var sorted_children = scene.get_children()
	sorted_children.sort_custom(func(a, b): return a.name.naturalnocasecmp_to(b.name) < 0)

	for child in scene.get_children():
		scene.remove_child(child)

	for child in sorted_children:
		scene.add_child(child)

	return scene
```

**Comment by idealarealo** [comment]
Sweet, I created a plugin from your code and it worked with little effort.
So, I'm no longer sure it's worth changing the core for this 3D specific issue.

- Tried using `_pre_process()`, but it didn't work as I expected.
- Changed `remove_child`+`add_child` with `move_child` because of node ownership issues.

Here is the code:

### plugin.cfg
```ini
[plugin]

name="Post Import Plugin Node Sorter"
description="Add node sorting capabilities to the 3D import tool"
author="IdealaRealo"
version=""
script="node_sorter.gd"
```

### node_sorter.gd
```gdscript
@tool
extends EditorPlugin

var scene_post_import_plugin

func _enter_tree() -> void:
	scene_post_import_plugin = preload("scene_post_import_plugin.gd").new()
	add_scene_post_import_plugin(scene_post_import_plugin)

func _exit_tree() -> void:
	remove_scene_post_import_plugin(scene_post_import_plugin)
	scene_post_import_plugin = null
```

### scene_post_import_plugin.gd
```gdscript
@tool
extends EditorScenePostImportPlugin

const OPT_SORT_ORDER := "nodes/sort_order"

const SORT_NONE = 0
const SORT_BY_NAME = 1

func _get_import_options(path: String) -> void:
	add_import_option_advanced(TYPE_INT, OPT_SORT_ORDER, 0, PROPERTY_HINT_ENUM, "None (Default),Sort by Name", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED)

func _get_option_visibility(path: String, for_animation: bool, option: String) -> Variant:
	if option == OPT_SORT_ORDER:
		return true
	return null

func _post_process(scene: Node) -> void:
	var sort_type = get_option_value(OPT_SORT_ORDER)
	
	if (sort_type == SORT_NONE) or (scene.get_child_count() == 0):
		return
	
	var sorted_children = scene.get_children()
	if sort_type == SORT_BY_NAME:
		sorted_children.sort_custom(func(a, b): return a.name.naturalnocasecmp_to(b.name) < 0)

	for child in sorted_children:
		scene.move_child(child, -1)
```

(_Godot is really cool!_)

**Comment by idealarealo** [comment]
I close the proposal because the issue can be resolved with a plugin.
