### ISSUE TITLE
Convert List to Tree View for Instance Child Scene Dialog and Quick Open dialog

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#9024]
### Describe the project you are working on

Working on a puzzle game with hundreds of levels

### Describe the problem or limitation you are having in your project

When your project has hundreds of scenes inside the game. It becomes difficult to find the scene for instancing and also for quick open 

It happens when you are developing levels as scenes. Instancing a scene inside another, opens up the dialog for selecting the scene. This dialog is filled up with hundreds of scene (tscn) files. You can filter the scenes by typing in the filter, that is great.
But when scenes are 3 to 4 level deep and have similar names, it becomes eye sore to find one, even with filter.

A sample example is shown below:
![image](https://github.com/godotengine/godot-proposals/assets/84369217/84d25bbc-644e-431f-9fdd-6b69d4838763)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Converting the list to **tree view** will help in these cases.
In tree view the folder/directory names will not be repeated and makes it easier to find and select.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It can be similar to that of **select a node** dialog.

![image](https://github.com/godotengine/godot-proposals/assets/84369217/099d5c68-5fd4-41ec-aa19-50d41f1d7964)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature will be mostly useful in case of large projects. For small projects where file system is generally flattened It will not have issues that much.

### Is there a reason why this should be core and not an add-on in the asset library?

It is core dialog changes

**Comment by KoBeWi** [comment]
Related https://github.com/godotengine/godot/pull/56772

**Comment by tokengamedev** [comment]
There is a pull request to solve to an extent. I think I can close the Proposal, if needed people can create new proposal.
