### ISSUE TITLE
Allow overriding virtual functions from the outside

### ISSUE THREAD

**Issue by dugramen** [godotengine/godot-proposals#9026]
### Describe the project you are working on

Editor plugins

### Describe the problem or limitation you are having in your project

Trying to add drag and drop behavior to controls from a plugin, but they are all handled via virtual functions. Also trying to adding extra properties via `_get_property_list()`, and saving them in their meta

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have a function that allows redirecting a virtual function to a different function / callable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Have a function in Object like `redirect_virtual_function(function_name, callable)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It adds a function to the built in Object class

**Comment by AThousandShips** [comment]
This really violates a lot of fundamental principles in the concept of inheritance IMO, you're not supposed to be able to change how a class works from the outside like this, it really violates safety and control principles for that

Can you point to any language that allows this?

**Comment by dugramen** [comment]
I mean in javascript, you can override, and are sometimes expected to override, class functions. 

But I don't think its too foreign in godot either. You can have variables that are callables, and just use them as normal functions. Those can be overriden, I'd just like to be able to do the same for class functions

**Comment by AThousandShips** [comment]
How do you override without an actual override in JavaScript? As in redirecting?

**Comment by dugramen** [comment]
> How do you override without an actual override in JavaScript? As in redirecting?
> 
> Let's be clear with terms here, "overriding" means what you can already do, this is redirecting, otherwise we'll talk at cross purposes
> 
> Note also that this would hurt performance for _all_ methods not just the ones that have been redirected, as you would need to look up if they have been redirected, further you'd have possible errors if two different places wants to redirect the same method, which you naturally don't have for overrides
> 
> There is also already a very simple workaround: Provide a callback, with:
> 
> ```gdscript
> var my_method_callback : Callable
> 
> func my_method(...):
>     if my_method_callbac.is_valid():
>         my_method_callback.call(...)
>         return
>     ...
> ```
> 
> Which still gives you control, and is specific, not affecting the whole engine when not needed

Yes this is what I mean. I need to be able to do this for virtual methods.

For example, to add any drag and drop functionality you need to use `_can_drop_data()`, `_get_drag_data()`, `_drop_data()`. I need to add this functionality to any general control node, so I have not control over the script contents

So I have to do something like this
```
var some_control := Button.new()
Button._get_drag_data = func(): return "my data"
```

This is possible only if `_get_drag_data` were a variable, not as is. (In javascript it is possible regardless)

As for performance, I'm not sure. There shouldn't be multiple redirects or anything, just a single one that can be changed. So it'd only be one property which could be hashed?

**Comment by AThousandShips** [comment]
It would still take performance, it'd still have to do one more lookup before calling it, for *every* virtual method

You can just do this manually, as a simple workaround, so I'd say it's not something that's needed, as the majority of users won't use this, and I'd suspect many don't want it because of the performance and security

Another issue with this idea:
You can't call `super` from the callable, as there's no system for that in the callable, and adding that would be require a custom new callable setup and it would have to be detected from the GDScript compiler, because this would *only* work when the callable is used for this purpose, not otherwise, which would make things highly complicated and confusing

**Comment by dugramen** [comment]
I'm not sure about the annotation. I agree with you that there's a simple alternative with using Callables instead, so an annotation isn't necessary there. For what I need, the annotation would have to be applied to some virtual methods used by the engine, in which case that could just be done under the hood. 

I guess if it isn't desirable to do it for any virtual method, is it plausible to do it with specific ones? I guess they could be specific methods, like `override_get_drag_data()`, `override_drop_data()`, `override_can_drop_data()`?

**Comment by KoBeWi** [comment]
In this particular case you can use `set_drag_forwarding()`.

**Comment by dugramen** [comment]
> In this particular case you can use `set_drag_forwarding()`.

Thanks, I didn't know about that! That solves one things I was trying to do. 

I needed this for the additional properties thing too, but I think there could be a better proposal for that
