### ISSUE TITLE
Add Rotary input support for android(wear os) platform.

### ISSUE THREAD

**Issue by AlekseyKapustyanenko** [godotengine/godot-proposals#9062]
### Describe the project you are working on

I'm working on game like space impact from old nokia phone for wear os smartwatches.

### Describe the problem or limitation you are having in your project

The display on smartwatch is quite small so when you use display to interact with game your finger overlap 20-50% of the display. Accelerometr also is not very convenient option.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

 Rotary input(Crown or bezel rotating ) is most convenient option for small games for smartwatches.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is the link how to handle rotary input in android apps https://developer.android.com/training/wearables/user-input/rotary-input#custom-scrolling .

Here is my PR to implement support rotary input: https://github.com/godotengine/godot/pull/88130

Here I detect if it is rotary input or not and if it is rotary input I convert it to vertical mouse wheel event.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It opens possibility to create games for wear os devices for many developers. As I know nowdays there is no game enguine which support Rotary input.

### Is there a reason why this should be core and not an add-on in the asset library?

There is no way to make workaround with scripts because solution lays on Input Device layer.

**Comment by Mickeon** [comment]
This proposal can be closed as https://github.com/godotengine/godot/pull/88130 is implemented.
