### ISSUE TITLE
Stack identical messages in output

### ISSUE THREAD

**Issue by sammonius** [godotengine/godot-proposals#9086]
### Describe the project you are working on

A game with a ton of bugs

### Describe the problem or limitation you are having in your project

The output fills up with errors quickly (the new "too many errors" feature in 4.2 helped a bit, but I think there's a better solution)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Errors with identical text to the previous error wouldn't be printed, and a counter beside the previous error would increase instead.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Chrome's JavaScript debugger has a feature similar to this.
![image](https://github.com/godotengine/godot-proposals/assets/104873652/676bb9e9-87f1-4dde-b311-391b5875f6bd)

The Unity editor also has this feature.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It wouldn't be possible to make this as an addon

**Comment by AThousandShips** [comment]
There is such a feature? It's been there since 4.0 AFAIK

**Comment by sammonius** [comment]
It doesn't happen in the output tab at least:
![image](https://github.com/godotengine/godot-proposals/assets/104873652/664ec5cc-ebc2-4ec8-98b1-910f01c63413)

**Comment by Mickeon** [comment]
Click here
![image](https://github.com/godotengine/godot-proposals/assets/66727710/2d19794e-28eb-4a40-b7dd-933947b292cf)

**Comment by dalexeev** [comment]
![](https://github.com/godotengine/godot-proposals/assets/47700418/5494fd6b-b32e-4540-a506-504691de38c2)

**Comment by AThousandShips** [comment]
Since this is implemented and appears to work I'll go ahead and close this, if you are experiencing issues with the feature please open a [bug report](https://github.com/godotengine/godot/issues)

**Comment by sammonius** [comment]
Ok, thanks. I didn't know this already existed.
