### ISSUE TITLE
Ability to render SubViewport with camera as a texture form models

### ISSUE THREAD

**Issue by Dente222** [godotengine/godot-proposals#9094]
### Describe the project you are working on

Im working on 3D game about ghost hunting and one of items that I need is Hand mirror

### Describe the problem or limitation you are having in your project

Currently only WORKING way is to use Sprite3D but problem is that you cant change shape of it soo you are stuck with basic ractangle shape which in my case is useless because my Mirror is round 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice to have a working way that displays SubViewport as a texture of a 3D model
Or option to reshape Sprite3D to fit my idea or in case someone wants to make different type of mirrors like for cars

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simply as is with Sprite3D
Or use it as normal texture, or allow Sprite3D to be reshaped and not only rectangle

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Could be but seems that it works properly with Sprite3D, but in case of using it as texture of model, it works in its own scene but when used in other scenes, it does not display anything

### Is there a reason why this should be core and not an add-on in the asset library?

Because this is by default in Godot but only limited to Sprite3D as long as i am aware of it

**Comment by clayjohn** [comment]
SubViewport can be used as a texture anywhere, it is definitely not limited to Sprite3D. 

We even have a tutorial in the docs dedicated to explain an advanced usage of using a SubViewport as a texture https://docs.godotengine.org/en/latest/tutorials/shaders/using_viewport_as_texture.html

**Comment by Dente222** [comment]
That's weird because If I use Viewport texture directly on designated material, it gives error for missing width and height, and texture is pink, although sometimes it's working and sometimes it's not, using spatial material works fine but another problem is that camera does not follow my model and always stays at 0/0/0

**Comment by Dente222** [comment]
However I will check it more deeply and check the tutorial you provided, thanks :)

**Comment by Calinou** [comment]
> That's weird because If I use Viewport texture directly on designated material, it gives error for missing width and height, and texture is pink, although sometimes it's working and sometimes it's not, using spatial material works fine but another problem is that camera does not follow my model and always stays at 0/0/0

Have you set the Viewport's update mode to **Always**?

**Comment by Dente222** [comment]
> > That's weird because If I use Viewport texture directly on designated material, it gives error for missing width and height, and texture is pink, although sometimes it's working and sometimes it's not, using spatial material works fine but another problem is that camera does not follow my model and always stays at 0/0/0
> 
> Have you set the Viewport's update mode to **Always**?

Manage to fix that, You need to set that viewport texture in Surface Material Override, the its working fine
But I still have other problem with camera staying at the world origin

**Comment by Calinou** [comment]
I'll close this as this feature is already implemented in Godot.

Please don't ask support questions here, as this issue tracker is meant to be used for feature proposals only. Use one of the other [community channels](https://godotengine.org/community) instead.
