### ISSUE TITLE
Use PackedScene original name to build name of node created via PackedScene.instantiate instead of @NodeType@

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-proposals#9103]
### Describe the project you are working on

A platformer

### Describe the problem or limitation you are having in your project

It is harder to debug the game when my instantiated nodes have generic names like `@CharacterBody2D@23`. Only the 1st instance of each PackedScene is named with the original name e.g. "Boss".

When navigating Remote or the debug variables, it's not obvious what we are dealing with. And currently Godot doesn't allow live scene debugging, ie showing the selected node in Remote in the live game scene, making it even harder.

Note: I said the first instance preserves the original name, but to be more exact: if there is not already a node with that name, then the generic `@NodeType@[Number]` is used. So if first instance is freed (for at least 1 complete frame, ie 2 frames ago), the next instance will be able to reuse the original name.

Workaround: hover for tooltip or click on the movie slate icon to see what PackedScene the instance comes from (but cannot be done at a glance).

![image](https://github.com/godotengine/godot-proposals/assets/1067772/843cc70f-2785-4251-804d-9dc1277d7eb8)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We could combine the two: keep PackedScene name as base name, and add an incremental numerical suffix (like Unity).

In this case we probably don't need the @ sign. If some devs like it we can keep it via some Project Preference though. As a compromise we could keep only the @ sign at the end, before numerical suffix, to indicate we are dealing with an instantiated scene suffix (some people may want @0 for the very first instance, but devs who rely on the first instance being exactly the PackedScene name may not like it).

In addition, it seems that the current system's incremental suffix is the count of ALL previous nodes of the same type, and it is shared across all nodes, not per PackedScene. We could either keep that system, or, since names would be more specific, keep a unique count per PackedScene (note that PackedScenes may be homonymous though), or be pragmatic and just add the next number unused when counting from 1 - at the risk or reusing the name of a previous nodes that was freed earlier.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- First instance of PackedScene is named "[PackedScene name]" as usual
- If a node named "[PackedScene name]" already exists (typically the first instance of PackedScene, placed either manually in inspector or spawned via code), the node is renamed `[PackedScene name]@1`
- From here, multiple incremental naming strategies exist. If it's easy to keep the existing one, then let's do this. Just remember that it means we'll skip numbers a lot if there are many PackedScenes of the same type.
- Otherwise, increment numbers individually for each PackedScene, or just fill the gaps if you don't care about preserving generations

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it's possible to rename the node manually, but I need to extract the basename from packed_scene.resource_path (still working on it).

EDIT: I found a one-liner: `instance.name = packed_scene.resource_path.get_file().get_basename()`

A generation-based incremental strategy is harder. Fortunately Godot has an automatic name safety system that increments numbers until name conflicts are resolved (in other words, it fills the first gap in 1, 2, 3...), which is good enough for me (but doesn't replace the current incremental system).

### Is there a reason why this should be core and not an add-on in the asset library?

It could be done but then users would be to download an add-on just to run a custom `instantiate_with_packed_scene_name` method.

**Comment by AThousandShips** [comment]
What happens if you do `add_child(scene, true)`?

**Comment by AThousandShips** [comment]
The solution here is to just use `force_readable_name`, tested and it generates the chosen name of the root node, this is already implemented :)

**Comment by hsandt** [comment]
> What happens if you do `add_child(scene, true)`?

Excellent, I forgot the `force_readable_name` flag. Setting it to true works, and give the same result as my workaround:

`instance.name = packed_scene.resource_path.get_file().get_basename()`

It says the operation is slow so I understand why it's not true by default. But it doesn't matter, I can do it in editor only just for debug.

Since this solution is satisfying (although a combination of PackedScene name + generation incremental number would be ideal for me, as both explicit and unique so fast), I'll close this issue.
