### ISSUE TITLE
Rename 'Quick Load' to 'Search'

### ISSUE THREAD

**Issue by emanvidmaker** [godotengine/godot-proposals#9112]
### Describe the project you are working on

Making godot more user friendly to new users.

### Describe the problem or limitation you are having in your project

The quick load's name can be misleading to new users and its name does not properly describes what it does. 
It requires prior knowledge of Godot's quick open feature to infer its propose.
While functionally its a search bar for assets. 
I propose lowering the barrier of entry for this feature, by Renaming it to Search. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The quick load's name can be misleading to new users and its name does not properly describes what it does. 
It requires prior knowledge of Godot's quick open feature to infer its propose.
While functionally its a search bar for assets. 
I propose lowering the barrier of entry to use this feature, by renaming it to Search. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A simple name change
![Scene](https://github.com/godotengine/godot-proposals/assets/16447282/661f36e4-7c33-4fb1-8ef6-a8631b4c90d6)
 A ready posted a pull request called [Renamed 'quick load' to 'search', to make it more User friendly #88416 ](https://github.com/godotengine/godot/pull/88416) that does this.
 Only two lines of the web documentation need to be change in order to update this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A This is a UI change

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the editor's usability out of the box for new and returning users. Allowing them to search their assets without ever needing to learn about quick open.
```[tasklist]
### Tasks
- [ ] https://github.com/godotengine/godot/pull/88416
```

**Comment by AThousandShips** [comment]
I don't follow the logic of `quick == preload`, `preload` isn't quicker, it takes the same amount of time to load, it just happens *at parse time*, meaning it can be used in performance critical cases because it's done ahead of time, so the underlying logic and confusion here is, well, confusing to me

**Comment by emanvidmaker** [comment]
> I don't follow the logic of `quick == preload` (mentioned in the PR), `preload` isn't quicker, it takes the same amount of time to load, it just happens _at parse time_, meaning it can be used in performance critical cases because it's done ahead of time, so the underlying logic and confusion here is, well, confusing to me

The logic comes from being novice and misunderstanding the UI at first impression, that's what i aim to fix.

When I first started using Godot (a year ago) I didn't understand why there was a quick load (since i didn't know about quick open) i didn't know what it would do since i have never seen it in any other program before so i assumed it was a different type of loading, and skipped it for a while. Until a couple projects in i got curious and clicked only to discover it was a search bar. 

The first thing that came to mind was that Why is this not called search. because if i had known i would have used it earlier.

Later on i found out about quick open, while i was coding the first iteration of this, because of how hidden it was in the menus.

Thats my user story.

**Comment by AThousandShips** [comment]
But the menu that opens isn't a search menu either? It's a quick list showing only the appropriate types of files without all the overhead of a normal file dialog, all in the same place

The concept isn't unique to Godot either AFAIK, a `Quick Search` menu is available in Unity apparently which allows you to search for things in a convenient compact menu (never used Unity so can't explain it deeper) and I'm sure other software have similar menus

It's named to match `Load` and the connection with it is important as well

Further this is used in several other places which should also be changed if this is (though those also match the behaviour)

I don't mind renaming it but it should be named something appropriate, not `Search` IMO

**Comment by emanvidmaker** [comment]
> Do you have any evidence that more people have the same difficulty? (I lurk in all the Godot communities a lot and never heard anything similar) Otherwise you may be trying to "fix" something that is a issue just for you or for a very small amount of people in detriment of everyone else.

No, I hadn't thought of that.
However I'm curious what a regular user would think about this change. Since i think Im hitting on a common UX issue but im not addressing it properly, with this change.  

## On a side note...
Slight off topic
In the grand scope of things, I want to help with Godot's general UX problem
I think a more drastic redesign will make it more apparent to experienced users what the issue current with Godot's UX is.
Since its so hard to explain.
I'm consider making a fork of with larger UX experimental features and picking good features from there. Rather than submit it bit by bit, like this since its hard to visualize that way. What do the maintainers think of this?

**Comment by emanvidmaker** [comment]
... Something we can also see in this proposal [Use "Files" instead of "FileSystem" in the UI #9067](https://github.com/godotengine/godot-proposals/discussions/9067) people miss interpreting godot's UI

**Comment by emanvidmaker** [comment]
Thank you for the heads up will see what can i help

**Comment by vvvvvvitor** [comment]
I also had difficulty understanding what it did at first, so much so I would actively avoid the button until I actually tried using it.

**Comment by AThousandShips** [comment]
It's extremely hard to convey what something does in just a few words, a tooltip would help too of course, but not everyone will immediately understand what it does, and to some extent people just need to test things out and not be afraid of checking what things do IMO

**Comment by vvvvvvitor** [comment]
> It's extremely hard to convey what something does in just a few words, a tooltip would help too of course, but not everyone will immediately understand what it does, and to some extent people just need to test things out and not be afraid of checking what things do IMO

Whilst I do agree, I feel like "Search" is way more intuitive than "Quick Load" as search is what you basically do in that window. It could also be named "Search Files" or "Quick Search" to make it's function even more obvious.

**Comment by AThousandShips** [comment]
But it loads, it doesn't search, search doesn't imply that you will load the file IMO, it's no more clear, if it said "Search" I'd not expect it to load a resource for me the way it does now

**Comment by nicolasgustafsson** [comment]
> But it loads, it doesn't search, search doesn't imply that you will load the file IMO, it's no more clear, if it said "Search" I'd not expect it to load a resource for me the way it does now

From my point of view I'm just setting a reference. Whether it loads something into memory is just an implementation detail to me, or am I missing something?

**Comment by AThousandShips** [comment]
But search doesn't imply anything being loaded or assigned or anything, it just implies searching, searching implies nothing is assigned or changed
