### ISSUE TITLE
Add Support for Correcting the Projection of Cube Map Reflections Based on Camera Position

### ISSUE THREAD

**Issue by Giwayume** [godotengine/godot-proposals#9113]
### Describe the project you are working on

3D game that needs cheap, but positionally accurate reflections

### Describe the problem or limitation you are having in your project

The reflection probe implementation generates an image from the origin point of the probe. This causes issues where the reflection does not accurately align with what the camera should see based on its position in most cases.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are a couple of names for the feature I am suggesting. three.js calls it "Box Projected Cube Map". Some call it "Parallax Corrected Cube Maps".

Here is a demo and comparison in the Source Engine:
https://m.youtube.com/watch?v=ZH6s1hbwoQQ

Demo in three.js:
https://raw.githack.com/sneha-belkhale/three.js/bpcem/examples/webgl_materials_envmaps_parallax.html

Example of how well it works in Source 2:
https://m.youtube.com/watch?v=XZw5CXAJ2hg

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This article discusses the technical implementation, it is a cheap shader trick:

https://www.clicktorelease.com/blog/making-of-cruciform/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, the user doesn't have this kind of fine tuned control over the reflection contribution in shaders.

### Is there a reason why this should be core and not an add-on in the asset library?

It cannot be done without modifying engine code.

**Comment by clayjohn** [comment]
We already have this, we call it "box projection". https://docs.godotengine.org/en/latest/classes/class_reflectionprobe.html#class-reflectionprobe-property-box-projection

**Comment by Calinou** [comment]
Closing per clayjohn's commment.
