### ISSUE TITLE
Don't show the `Search Results` bottom panel button until you search for something

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot-proposals#9114]
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

I see 3 related problems with how the `Search Results` tab currently works:

1. When you first open Godot there's no `Search Results` button in the bottom bar. It's a temporary tab. When you switch to the Script Editor it appears. But then when you switch back to 2D or 3D it *doesn't disappear*. And there's no way to close it manually

2. There's no need for it to appear when you switch to the Script Editor, it could only appear when you search for something, otherwise it's just taking up space. That panel is for the results only, there's no input field in it to search directly from it, and you need to press `Ctrl+Shift+F` in the Script Editor to make use of it. Also not everyone is using the built-in Script Editor, and it makes even less sense for it to appear when you open the Script Editor on accident or just to quickly check some docs

3. It's added in-between of the permanent buttons unlike other temporary buttons like `Theme` and `TileMap` which are added in the end. It would make more sense for it to be placed in the end for consistency with how other temporary buttons work and to reduce conditional reordering

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

All of those problems are easy to solve:

1. Don't show the `Search Results` button when the Script Editor is first opened. Open it when you perform a global search instead
2. Add a `Close` button to the `Search Results` panel
3. Move the `Search Results` button to the end so that it doesn't move permanent buttons

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![global_search](https://github.com/godotengine/godot-proposals/assets/60579014/e7076c5a-f989-4b55-bd1e-7c1ad93c3c9b)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

Basic editor usability improvement

**Comment by TokisanGames** [comment]
Today is the first day I've seen this tab in 6 years. I normally use grep.

* It should also allow the search line to be editable, since there is a refresh button and this panel is clearly intended to update.
* And ideally search input provides regex, since the library is built into godot

**Comment by passivestar** [comment]
@TokisanGames I agree that it would make sense for that tab to have an editable input, but it would have to be a separate proposal. This proposal is only about how and where that temporary tab appears on screen, and about adding a button to close it when it's not in use

**Comment by Mickeon** [comment]
The whole "Search Results" part of the editor needs a refresher. It just frankly sucks for a multitude of reasons that are easy to relate to, but hard to explain for a full-blwon proposal. Solving this proposal would be lovely but it's only one of many nuisances of the current system.

**Comment by Hyrilorius** [comment]
See this proposal and especially the WIP stuff showed by @EricEzaM in the comments regarding potential improvement to the whole "Search Results" part of the editor.
https://github.com/godotengine/godot-proposals/issues/5544
