### ISSUE TITLE
Potentially slow code in DocTools::merge_from

### ISSUE THREAD

**Issue by nlupugla** [godotengine/godot-proposals#9125]
### Describe the project you are working on

Godot.

### Describe the problem or limitation you are having in your project

Noticed some potentially slow code in `DocTools::merge_from` https://github.com/godotengine/godot/blob/5f05e2b9b1a3fedcdd7ecb2ab976a2687fd6f19a/editor/doc_tools.cpp#L79. The current algorithm used to merge is `O(n^2)` when it could be `O(n)`, where `n` is the number of members in a class. For example,
for each property in `this`, the following code block scans through all the properties in `p_data` to look for a match.
```cpp
                for (int i = 0; i < c.properties.size(); i++) {
                        DocData::PropertyDoc &p = c.properties.write[i];


                        for (int j = 0; j < cf.properties.size(); j++) {
                                if (cf.properties[j].name != p.name) {
                                        continue;
                                }
                                const DocData::PropertyDoc &pf = cf.properties[j];


                                p.description = pf.description;
                                p.is_deprecated = pf.is_deprecated;
                                p.deprecated_message = pf.deprecated_message;
                                p.is_experimental = pf.is_experimental;
                                p.experimental_message = pf.experimental_message;
                                p.keywords = pf.keywords;
                                break;
                        }
                }
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I haven't profiled to see whether the current algorithm is actually a problem, but I just thought I'd write up a formal issue to bring it to people's attention since the CI runs the doctool on every PR, so making it even a bit more efficient might help a lot. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

First step is profile to check whether it's actually a bottleneck. If it is, I have a few ideas to try out:

1. Start the inner loop index `j` at the current value of the outer loop index `i` on the assumption that `this` and `p_data` usually have the same number of elements in the same order. Optionally, ensure both `DocData` instances are sorted before merging.
2. Store the class members in a `HashSet` or `HashMap` so that the common members can be found more efficiently. Even though this would make the algorithm `O(n)`, I doubt it would actually be faster because of the extra hashing overhead, but it's perhaps worth trying anyway.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Doctool is core.

**Comment by AThousandShips** [comment]
I'd say to do a merge by keeping both `i` and `j` outside the loops and iterate skipping by comparison, a classic merge algorithm, assuming the inputs are sorted that will work, something like:
```cpp
while (i < size_i() && j < size_j()) {
    while (i < size_i() && names[i].compare(names[j]) < 0) {
        ++i;
    }
    while (j < size_j() && names[j].compare(names[j
i]) < 0) {
        ++j;
    }
    if (i >= size_i || j >= size_j) {
        break;
    }
    // Do our merge
    ++i;
    ++j;
}
```

Will take a look at something when I have the time, I've done code like that in the past

**Comment by AThousandShips** [comment]
Working on this code, it works currently, will test it out further

**Comment by nlupugla** [comment]
That's awesome! Didn't expect anyone to get to this so quickly :)

Did you get a chance to profile it? I'd hate to send you down a rabbit hole that doesn't make much of a performance difference in the end.

**Comment by AThousandShips** [comment]
Haven't profiled but it should be better, will do some tests later, but it does improve general code quality and stability in either case I'd say with my testing
