### ISSUE TITLE
Godot Editor for Windows on Arm

### ISSUE THREAD

**Issue by Drakenroft** [godotengine/godot-proposals#9131]
### Describe the project you are working on

/

### Describe the problem or limitation you are having in your project

Godot Editor missing for Windows on Arm devices, while runtime is already available

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot Editor already runs basically on every modern machines and operating system, the only missing at the moment are iPad and Windows on Arm.
Windows on Arm comes with some limitations or even no supports for OpenGL (and if i'm not wrong with Vulkan too).
Thus said Godot has, since long time, been supporting ANGLE that can enable a layer to translate OpenGL calls to DirectX11, which should make the Godot Editor run on all the devices that comes with Windows on ARM effortsly, at least for the 'Compatibility' render mode of Godot 4, and the full Godot 3.
And there is also the new DX12 render which should enable Forward+ and Mobile Renders for Godot 4 on those devices 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

/

### Is there a reason why this should be core and not an add-on in the asset library?

/

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2408.
