### ISSUE TITLE
Editor: Filter methods search window.

### ISSUE THREAD

**Issue by IIGreed** [godotengine/godot-proposals#9151]
### Describe the project you are working on

roguelite

### Describe the problem or limitation you are having in your project

Slow iteration between the text editor and the filter method search bar because the mouse is required to reach the filter method search bar in a timely manner

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Ideally there would be a shortcut to open a new window like the current Quick Open Script/Scene but instead display the methods on the current script. This way you can type and press up and down on the menu to select the function you want to move to unlike in the current filter search bar where you need to select with the mouse and then select the method with the mouse again. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It could look something like this and display the method's line
![image](https://github.com/godotengine/godot-proposals/assets/72952945/846bccf1-a203-4989-91bb-42e64f5ffa22)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

you can use your mouse to click the search box or press Control+F and tab a bunch of times until you get to the filter methods box.

### Is there a reason why this should be core and not an add-on in the asset library?

There's already similar functionality in the engine and this would be a welcome quality of life for people with big scripts.

**Comment by Jowan-Spooner** [comment]
Doesn't CTRL+ALT+F do exactly that? I might be misunderstanding something.

**Comment by IIGreed** [comment]
> Doesn't CTRL+ALT+F do exactly that? I might be misunderstanding something.

You are absolutly right I never knew. Closing.
