### ISSUE TITLE
Code editor scroll horizontally

### ISSUE THREAD

**Issue by FakerDomain** [godotengine/godot-proposals#9155]
### Describe the project you are working on

Sometimes I need to write a very long code in a single line.

### Describe the problem or limitation you are having in your project

Sometimes I need to write a very long code in a single line. When I want to check the long code, I need to drag the scrool bar to move the window of editor to move horizontally, which is not convenient at all

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I wish the code editor window can be moved by pressing the middle button of mouse.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user hold the middle button of mouse, then move the mouse horizontally, the code window will move horizontally as well.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around with an editor plugin, but it is not particularly convenient.

### Is there a reason why this should be core and not an add-on in the asset library?

This is to improve development efficiency and make coding more comfortable

**Comment by dalexeev** [comment]
There is `text_editor/appearance/lines/word_wrap` editor setting:
![](https://github.com/godotengine/godot-proposals/assets/47700418/3d054adf-52dc-4c18-9b81-9018aeab1351)

Perhaps we should change the default value.

**Comment by KoBeWi** [comment]
Word wrap can be toggled with Alt+Z. Disabled by default + easy toggle works better, because it tends to get in your way when not needed.

**Comment by FakerDomain** [comment]
> There is `text_editor/appearance/lines/word_wrap` editor setting: ![](https://private-user-images.githubusercontent.com/47700418/307259695-3d054adf-52dc-4c18-9b81-9018aeab1351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTk3MTAsIm5iZiI6MTcwODY5OTQxMCwicGF0aCI6Ii80NzcwMDQxOC8zMDcyNTk2OTUtM2QwNTRhZGYtNTJkYy00YzE4LTliODEtOTAxOGFlYWIxMzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4OWIxMmI2ZTNjNmUxNDgxMDAzNzgwODYzNDdkNTRhZDFlZWI3ZjQ0MWI0ZDI1YzdmNGQ0MTcwYTE2NzFkZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.38Dh3q-ggnR4Bf-vmIHowaaowt2P-SsDzKhIY5a3RcU)
> 
> Perhaps we should change the default value.

Thanks for your reply, the truth is I konw there is world wrap function, but when I toogle it on, the whole screen just like a mess. 

So, maybe this is just my personal problem, I just can't tolerate the word wrap, which makes to code much more difficult for me to read, I would rather they stay on one single line....

Thanks anyway, I really appreciate your help.

**Comment by KoBeWi** [comment]
Also you can scroll horizontally with Shift + wheel.

**Comment by FakerDomain** [comment]
> Also you can scroll horizontally with Shift + wheel.

Wow!! Thanks for help, I didn't know this trick before

Thank you very much!!~
