### ISSUE TITLE
Option to offset spotlight cone start

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot-proposals#9157]
### Describe the project you are working on

Quake-like retro fps.

### Describe the problem or limitation you are having in your project

Some spotlights are kind of large and I want the cone to start wider than a single point.  For example, here's a top-down view of a light partially submerged in water:
![image](https://github.com/godotengine/godot-proposals/assets/7751182/de1980b8-ec88-4f60-a4b8-f6241a7f3ede)
Note that the cone starts in front of the light, but looks a little weird not matching up with the texture.  It should be wider at the start.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A simple parameter on the SpotLight3D to set the offset so that the light could start sooner, but with a near clipping plane so the world geometry does not cast shadows from INSIDE the light fixture, so it would look like this:
![image](https://github.com/godotengine/godot-proposals/assets/7751182/fdfd40e4-c545-4f0f-b3f8-78a89c6a9410)

(Note: I was able to move the lights back in this case, but sometimes model geometry will cast shadows, preventing that solution).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/7751182/07000ea1-8dbf-4633-9e67-ec506d08e78c)
Here there would just be a new parameter like "Start Offset", in meters.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this would require modifying the shadow rendering.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think addons can modify this.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2520.

> (Note: I was able to move the lights back in this case, but sometimes model geometry will cast shadows, preventing that solution).

With https://github.com/godotengine/godot/pull/85338, you should have more flexibility for toggling shadows on specific geometry on a per-light basis.
