### ISSUE TITLE
add ability to write debug code blocks that don't get compiled into Releases

### ISSUE THREAD

**Issue by scotmcp** [godotengine/godot-proposals#9170]
### Describe the project you are working on

I am writing an MMO that makes HEAVY use of "if debug: do a thing" code blocks. 

### Describe the problem or limitation you are having in your project

Releases contain all the if debug: code blocks, and this increases CPU cycles and stack size, which can be significant especially in _process and also increase the weight of _physics_process. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We should be able to mark these as debug code blocks so they can marked as DO NOT COMPILE for releases

C uses the #ifdef   #endif keywords so the preprocesser can pull these items out before compiling.

We should have similar functionality so we can have debugging code for development and testing, but also not compile it all into Releases.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example from C

#define DEBUG

func donormalstuff():
stuff

#ifdef DEBUG
dosomedebug.stuff.and.properties
#endif

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really, although you can use if DEBUG: do stuff, that code will always be compiled and evaluated at runtime.

### Is there a reason why this should be core and not an add-on in the asset library?

This should be a core debugging capability, and therefore should be part of the core engine.

**Comment by dalexeev** [comment]
Thanks for the proposal! We already have several issues about this, so in order to consolidate the discussion, let's close this one.

* #4234
* #7375
* #7496
