### ISSUE TITLE
Add Unit Testing for the engine development process

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot-proposals#918]
**Describe the project you are working on:**
FBX Importer
**Describe the problem or limitation you are having in your project:**
We can't write a unit test easily which runs on our CI every commit for the C++ side of godot.
We can't write unit tests for /modules/fbx_importer etc.
We have complex code that needs simple test cases declared for it without making breaking changes.
**Describe the feature/enhancement and how it helps to overcome the problem or limitation:**
We can integrate a testing framework that allows for tests to be written for the engine.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
At the moment unit tests are not run when any commit is made to the engine, this needs to change, we need automated C++ unit tests for the engine which run and are completely independent of the engine.

Additionally if someone finds a bug in the engine and can fix it, they could also write a unit test to be sure it doesn't return.

Meaning when we do a release we have some regression testing and basic unit tests for core and other modules.

I propose we implement our own testing interface or use the doctest PR. 

### Doctest - little build time increase
doctest has a limitation which won't work in shared libraries without hacks since tests are compile-time, most frameworks have this limitation.
https://github.com/godotengine/godot/pull/30743 - this has a limitation of not being able to easily test modules.

### Rolling our own - not too hard to maintain but requires code which doesn't use core Godot types - minimal build time increase

We can also optionally roll our own solution, this would let us test across modules/core/whatever folder in the engine, so tests could be in modules/fbx_importer/tests for example.

The reason you would use non-godot types here would be you can't test yourself or in-engine types they could cause issues with the results or with how the tests execute.

https://gist.github.com/RevoluPowered/33e154902fa668f7ac87bcabd55d9295

This could easily be integrated into GDScript too, this is pseudo code / c++ 

### Catch 2
![PERF](https://raw.githubusercontent.com/onqtam/doctest/master/scripts/data/benchmarks/header.png)

Google test - too big for godot source to add 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no, this would be integrated into our CI/CD pipeline for each build to ensure the same behavior.
**Is there a reason why this should be core and not an add-on in the asset library?:**
yes, we need to write unit tests for core/ and for modules/fbx_importer

**Comment by akien-mga** [comment]
For the reference, see also https://github.com/godotengine/godot/issues/2641 which was the original proposal about this in the main engine repo.

**Comment by RevoluPowered** [comment]
@akien-mga thanks!

I also thought a bit about gd script only testing but it won't cover my use case e.g. the fbx importer testing the skin mathematics, which is what I would use it for.

Ideally, Godot has C++ testing which can also be used in GDScript the header example is probably the best way to handle both sides, but doctest gets us some of the way there for 4.0, so if we want it sooner rather than later it's a good approach.

**Comment by neikeq** [comment]
What is the status of this proposal? Was this approved?

**Comment by Calinou** [comment]
This was implementged in https://github.com/godotengine/godot/pull/40148, closing.
