### ISSUE TITLE
Add built-in logging capabilities

### ISSUE THREAD

**Issue by pwab** [godotengine/godot-proposals#919]
**Describe the project you are working on:**
N/A (generic issue)

**Describe the problem or limitation you are having in your project:**
I do use logging a lot to track things in the game and investigate bugs. But I don't believe that I do that in an efficient way (or that there's such way at all for GDScript) while simply using the print function.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
See original issue: https://github.com/godotengine/godot/issues/27958

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
An existing logger can be found here: https://github.com/hedin-hiervard/godot-logger
(Or take some ideas from the [Unity logger](https://docs.unity3d.com/ScriptReference/Logger.html) maybe)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm pretty sure it would be used quite often.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Print-debugging is used all over the place. At least a simple logger would help to solve most of the problems mentioned in the original issue (formatting, categories, destination).

**Original issue:** https://github.com/godotengine/godot/issues/27958

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5954, which is more detailed.
