### ISSUE TITLE
Add signal for adding a node to a group

### ISSUE THREAD

**Issue by dugramen** [godotengine/godot-proposals#9197]
### Describe the project you are working on

Editor Plugins

### Describe the problem or limitation you are having in your project

Cannot detect when groups are added to nodes. My plugin does things to a node based on which groups its in, and I need a signal to detect when the groups have changed to know when to update

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add related signals

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- Node exposes signals called `added_to_group` and `removed_from_group`, with the parameter `group`
- SceneTree exposes signals called `node_added_to_group` and `node_removed_from_group` with parameters `node` and `group`

Alternatively just a simple `groups_changed` would also suffice

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not for detecting changes in the editor. Unless you hook into methods like _process which is very undesired for obvious reasons

### Is there a reason why this should be core and not an add-on in the asset library?

SceneTree and Node are core

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/1259
