### ISSUE TITLE
Revamp of the Input Map system

### ISSUE THREAD

**Issue by Rain-Gayming** [godotengine/godot-proposals#9204]
### Describe the project you are working on

Currently I'm working on a realistic survival FPS game (very unique)

### Describe the problem or limitation you are having in your project

The current Input Map setting tab is very disorganised and hard to use, I feel like it's missing a lot of important quality of life features that could make it nicer to use.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I feel like something similar to Unity's New Input System menu could be nice. With catagories and then the actual maps themselves. I think this would make it more organised and easier to use, at current everything is all in one list and the only way to find something specific is to search for it, as well as this if you edit an existing or add a new input map all the others open with it and often scrolls up to the top, this is annoying and I feel it should be fixed for the betterment of the engine. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Something like the New Input System menu from Unity, shown below:
<img width="1085" alt="MyGameActions-2648220023" src="https://github.com/godotengine/godot-proposals/assets/120071361/3f4cc67a-d521-4c23-bc61-ebdd4771e0da">

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The enchancement I proposed will be used by almost everyone developing on the Godot engine

### Is there a reason why this should be core and not an add-on in the asset library?

It improves the work flow of implimenting new keybinds

**Comment by RedMser** [comment]
You don't really explain well what the goal is, especially for people who didn't use this feature from Unity it is not clear.

What are "Action Maps" on the left in the screenshot? Are the categories just visual or will they change how the system work? Which of these parts would be integrated into Godot's system, and how? Will the API have to change to accommodate?

It could be interesting to automatically group inputs by their name prefix, so all `ui_*` bindings are clustered under a `UI` collapsable section, etc.

> if you edit an existing or add a new input map all the others open with it and often scrolls up to the top, this is annoying and I feel it should be fixed for the betterment of the engine

This change can be done independently.

**Comment by Mickeon** [comment]
OP wants https://github.com/godotengine/godot-proposals/issues/4910 , I believe.

I would consolidate this issue with https://github.com/godotengine/godot-proposals/issues/4910 , or move it to Discussions as there is no concrete solution to the issue.

**Comment by Rain-Gayming** [comment]
@Mickeon yea i want something similar to that!

**Comment by Rain-Gayming** [comment]
@RedMser "action maps" are the catagories

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/4910.
