### ISSUE TITLE
Add ResourcePath to refer to a resource without preloading it

### ISSUE THREAD

**Issue by huwpascoe** [godotengine/godot-proposals#9216]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

There's no project-friendly way to reference resources without preloading them. There's a plain string with `@export_file` tag, but that's fragile and ineffective.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A new type called ResourcePath that the editor will track as if it were tracking an actual Resource.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# declare it manually and the editor could list as a dependency for the script
const res_1: ResourcePath = "res://thing.res"
const res_2: ResourcePath[Mesh] = "uid://..."

# or set the path from the inspector
@export var my_scene: ResourcePath[PackedScene]

func load_my_scene_on_demand():
  ResourceLoader.load_threaded_request(my_scene)
  # ...
  var s: PackedScene = ResourceLoader.get_threaded_request(my_scene)
  add_child(s.instantiate())
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a simple and obvious way to manage resource loading. It should be a core feature.

**Comment by KoBeWi** [comment]
Check ResourcePreloader node.

**Comment by KoBeWi** [comment]
> Easy [generic] specifier to facilitate said UI

What does that even mean?

> Allows editor to keep track of references and update them automatically

But the ResourcePreloader meets this point.

**Comment by huwpascoe** [comment]
> What does that even mean?
Well say you need a referenced for a PackedScene. You specify it as ResourcePath[PackedScene] so when you select it in the inspector, it doesn't show all derived from Resource, it only shows type of PackedScene

> If you want auto-updating paths without loading, it would require some new system.
Yes, that's what this proposal is about.

**Comment by huwpascoe** [comment]
Looking through the source at how much would need to be changed, I think an annotation would work better than a dedicated type like `@export_ref var my_resource: Resource`

**Comment by huwpascoe** [comment]
Nope. But the first step would probably be adding some way to flag any [ext_resource] to skip loading.

**Comment by huwpascoe** [comment]
# Resource Path

![icon](https://github.com/user-attachments/assets/136223d3-364c-4578-a270-5d8e9f530fac)
https://github.com/huwpascoe/godot_resource_path
I made it a plugin.

New improved syntax
```gdscript
@export_file("PackedScene")
var some_scene: String
```
It's working and you can use it in your project right now.
