### ISSUE TITLE
Nullable static types

### ISSUE THREAD

**Issue by Gato-X** [godotengine/godot-proposals#9217]
### Describe the project you are working on

Not for any particular game, useful in general.

### Describe the problem or limitation you are having in your project

When variables are statically typed, they can no longer be set to null and can only contain references to or values of the specified type. On many occasions, it would be useful to be able to set variables to null while still being able to specify a type for the variable.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose allowing for nullable types, meaning types that can either hold the specified type or null. 

Mainly for speed reasons, it might, however, be reasonable to prevent this for numeric types and booleans.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I propose adopting a syntax similar to what C# already uses. In particular, adding a question mark after the type to flag it as nullable.

This notation would only be allowed when explicitly specifying the type and not when creating an instance of said type.

This would be valid:

```
var pieces:Array? = null
var target:Vector3? = Vector3(1,2,3)

pieces = [4,5]
target = null

```

But not this:

```
pieces = Array?()
```

Nor this:

```
var pieces := Array?()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

When it's necessary to specify that a variable contains no value, a way to flag that without using nullable types is to either maintain a parallel variable indicating the value is not valid or picking a specific value that is understood to mean the value is invalid. This, in my opinion, increases code complexity and makes it more prone to errors.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be an add-on, as it requires a modification to the way GDScript itself is implemented.

**Comment by arkology** [comment]
See https://github.com/godotengine/godot-proposals/issues/162

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/162
