### ISSUE TITLE
Orthogonal mode enabled by default

### ISSUE THREAD

**Issue by skub007** [godotengine/godot-proposals#9220]
### Describe the project you are working on

A simple "don't touch the box or you die" type game

### Describe the problem or limitation you are having in your project

trying to focus camera by pressing on the buttons on the arrows on the top right corner of the editing scene focuses the camera but it suddenly feels as if its 2d the "auto enable othodox mode" or something should be disabled by default for 3d scenes

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

ok so who do you think needs the orthodox disabled by default?? 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

i guess no one will care but its just a life-improvement feature

### If this enhancement will not be used often, can it be worked around with a few lines of script?

nah it can be worked by just disabling it manually but really it should be disabled by default

### Is there a reason why this should be core and not an add-on in the asset library?

only can be implemented in the core

**Comment by AThousandShips** [comment]
What does "orthodox mode" mean? Do you mean "orthogonal"?

**Comment by Mickeon** [comment]
I'm sorry, I really do not understand.

Is it about these?
![image](https://github.com/godotengine/godot-proposals/assets/66727710/d26d2d31-3a13-4995-b82b-b30e85575b07)
If yes, orthogonal view when clicking on these is standard behavior (Blender also does this if I recall correctly). It allows you to move objects without perspective skewing your perception. If you do not need it you can disable it by unchecking "Auto Orthogonal Enabled":
![image](https://github.com/godotengine/godot-proposals/assets/66727710/267d3e3b-9170-41be-ab70-55140cce7cf3)

**Comment by skub007** [comment]
> I'm sorry, I really do not understand.
> 
> Is it about these? ![image](https://private-user-images.githubusercontent.com/66727710/309485513-d26d2d31-3a13-4995-b82b-b30e85575b07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTYzNTMsIm5iZiI6MTcwOTM5NjA1MywicGF0aCI6Ii82NjcyNzcxMC8zMDk0ODU1MTMtZDI2ZDJkMzEtM2ExMy00OTk1LWI4MmItYjMwZTg1NTc1YjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE2MTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZTY3MjY1NGMyMzg3ODk4NmZhZjAzZTZmNzBkYjIxMjc3MTlmZTExNjczMmY3MTQxNjQzODI4MTQ4ZDg5YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Cu-CQfnxHsEHSEeFlC2NmFF_kkTSNc-4A1E8d21dBI) If yes, orthogonal view when clicking on these is standard behavior (Blender also does this if I recall correctly). It allows you to move objects without perspective skewing your perception. If you do not need it you can disable it by unchecking "Auto Orthogonal Enabled": ![image](https://private-user-images.githubusercontent.com/66727710/309485798-267d3e3b-9170-41be-ab70-55140cce7cf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTYzNTMsIm5iZiI6MTcwOTM5NjA1MywicGF0aCI6Ii82NjcyNzcxMC8zMDk0ODU3OTgtMjY3ZDNlM2ItOTE3MC00MWJlLWFiNzAtNTUxNDBjY2U3Y2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE2MTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYjViYzE5YTE0M2M0N2UyNzY3ZDY4OGU5OGY1NzkwMWFjZjMzMDNjOWMyN2U0YmViZjBhOWMxNmM4NmFkMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JRPhiZYbQohVk62SYp75C0XTeaN2dKR3yCDSbIK1Quk)

yes i did found out how to change it but really should it be disabled by default??

**Comment by skub007** [comment]
> What does "orthodox mode" mean? Do you mean "orthogonal"?
> 
> Note that this is saved per scene when edited, so if you change this for a scene it is kept for that scene

yeah sry...

**Comment by AThousandShips** [comment]
Again other software like Blender has it enabled by default as well, what software have you used that doesn't do that?

**Comment by skub007** [comment]
> Again other software like Blender has it enabled by default as well, what software have you used that doesn't do that?

umm..unity engine sry nvm this one i guess its fine

**Comment by skub007** [comment]
> Again other software like Blender has it enabled by default as well, what software have you used that doesn't do that?
umm.unity....sry nvm

**Comment by Mickeon** [comment]
Wait is it true? Unity does not have this by default? That's worth acknowledging

**Comment by skub007** [comment]
> Wait is it true? Unity does not have this by default? That's worth acknowledging

yup it doesnt
