### ISSUE TITLE
[Particles2D] Particle enhancement 1: Allows particles to inherit transform in a more detailed manner rather than simply `local_coords`

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [godotengine/godot-proposals#9225]
### Describe the project you are working on

A 2D project where phantoms are generated by XXXParticles2D, XXX can be "CPU" or "GPU"

### Describe the problem or limitation you are having in your project

Currently, if one wants to generate phantoms by `XXXParticles2D`, he/she will figure out that the transform of particles inherits from the emitter **only when** the `local_coords` is turned on. However, people may hope to implement the transform inheritance separately, rather than a simple `local_coords`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Split the `local_coords` into `local_coords`, `local_scale`, `local_rotation`, and `local_skew`(if existing and needed).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As their names say, the `local_coords` keeps the same while it only works for `position`, while others works for `scale`, `rotation`, and `skew`(if exising and needed) respectively.
It's better to make this feature a flag byte:
```GDScript
@export_flags("local_coords", "local_scale", "local_rotation", "local_skew") var transform_local: int = 0b1110
```
As the default value presents, the latter three options are turned on by default while the first one keeps "off" as it is in Godot 4.2.x

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, because this requires modification or even overhaul on `local_coords` which is in the source code

### Is there a reason why this should be core and not an add-on in the asset library?

Same as the previous answer

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/4391.

Your proposal mentions additional features not mentioned in the linked proposal (such as local translation, scale and skew), so please write a comment in that proposal with an example use case for them. I've seen multiple requests for this over the years but it was usually limited to global translation with local rotation, so I'm curious what you need other local toggles for.
