### ISSUE TITLE
Rounded end of StyleBoxLine

### ISSUE THREAD

**Issue by feois** [godotengine/godot-proposals#9237]
### Describe the project you are working on

Simple 2D game

### Describe the problem or limitation you are having in your project

I am trying to use `VSeparator` which is fine but I want to customize the line however `StyleBoxLine` does not have rounded end and `StyleBoxFlat` does not seem to work with `VSeparator`

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a toggle for rounded end

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the toggle is on, the line looks like
![image](https://github.com/godotengine/godot-proposals/assets/68548170/d40497ce-d600-4e12-9085-d4bd9953663c)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

`StyleBoxLine` is core component

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/5711
