### ISSUE TITLE
StandardMaterial should support normal inversion for double sided faces

### ISSUE THREAD

**Issue by dotlogix** [godotengine/godot-proposals#9239]
### Describe the project you are working on

It would be nice if the StandardMaterial would account for the requirement to have the normals inverted for back-faces. By default Godot uses the same normals for the front and backface which leads to some strange looking darker faces.

### Describe the problem or limitation you are having in your project

I currently create shaders and meshes for foliage rendering. A lot of them have LODs with just a few double-sided quads.

I understand that for compatibility reasons we need to keep this behavior, but I wonder if it would be possible to either create an additional render_mode or a checkbox which inverts the normals. Currently I have to create custom shaders for all of these cases which unfortunately means I nearly have to copy everything the PBR material does and create a custom shader just for this.

I am not that sure how standard materials are handled behind the scene but I would assume a lot of features are not compiled in the actual shader if they are not enabled. Not sure if this is true for custom shaders as well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A render_mode double_sided would just act as if the quad has two sides actually so exact same behavior but with inverted normals.

A checkbox just for normals would be even easier to implement but not sure how this would apply to roughness and other textures.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The checkbox could just add this small snippet in the fragment function:
```
if(!FRONT_FACING and flipBackfacingNormals) {
    NORMAL = -NORMAL;
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It kind of can be worked around by creating an exact copy of the StandardMaterial but with this feature added manually.

### Is there a reason why this should be core and not an add-on in the asset library?

As mentioned above I can't tell if this is actually less efficient than a core feature.
I also think this should be the default behaviour but I understand that by definition cull_disabled does not imply double_sided.

**Comment by dotlogix** [comment]
Could be similar or a duplicate of #2735

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2735.
