### ISSUE TITLE
Add change_scene_to_node() method

### ISSUE THREAD

**Issue by sky94520** [godotengine/godot-proposals#9243]
### Describe the project you are working on

A 2D survivor game at mobile platform using c#

### Describe the problem or limitation you are having in your project

Godot has change_scene_to_file and change_scene_to_packed methods, change_scene_to_packed. Whyt not add method change_scene_to_node(const Ref<Node> &p_node). 
Now I use sub thread load and instance scene, and add_child, set_current_scene. but the replacement is raised error at Android Platform which too many
```
Condition 'p_elem->_root != this' is true
```
I guess the godot source code has another logic while change scene.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I can use the new method to change_scene

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

No

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

No

**Comment by AThousandShips** [comment]
Are you adding the node to the scene on the thread as well? That's [not supported](https://docs.godotengine.org/en/stable/tutorials/performance/thread_safe_apis.html#scene-tree)

**Comment by Mickeon** [comment]
> ### If this enhancement will not be used often, can it be worked around with a few lines of script?
> No

To be pedantic, I believe yes?

```
get_tree().current_node.free()
get_tree().current_node = new_node

```

**Comment by dalexeev** [comment]
> To be pedantic, I believe yes?
> 
> ```gdscript
> get_tree().current_node.free()
> get_tree().current_node = new_node
> ```

> Condition 'p_elem->_root != this' is true

```gdscript
func change_scene_to_node(node: Node) -> void:
    await get_tree().process_frame
    get_tree().current_scene.free()
    get_tree().root.add_child(node)
    get_tree().current_scene = node
```
