### ISSUE TITLE
make TypedArray return the specified type in GDExtension

### ISSUE THREAD

**Issue by xana43** [godotengine/godot-proposals#9244]
### Describe the project you are working on

I'm currently working on two RPG like games one 2D and one 3D, and as such they require a lot and I mean a lot of arrays.

### Describe the problem or limitation you are having in your project

when i'm trying to get an element from each array they are returned as a variant, this forces me to use Object::cast_to<T>()
which I have done some bench marking, casting in a tight loop tends to have some performance issues.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To fix this, I'd suggest that TypedArrays return the types that they are specified as, so like 

``` 
TypedArray<MyClass> myClassArray;

void accessArray(){
    UtilityFunctions::print(vformat("current element contains %s",myClassArray[0]->getMyClassData()));
}
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

since TypedArray is already a templated class, there are three solutions to this
A. change the array class to also be templated
```
template<class T = Variant>
class Array{
//all the other parts of the array class
const T* operator[](int p_index) const;
T* operator[](int p_index);
}

template<class T>
class TypedArray : Array<T>{
//standard implementation of typed array
}
```

B. make typed array have an Array instead of inherit from Array 
```
template<class T>
class TypedArray{
   public:
      T* operator[](int p_index);
      const T* operator[](int p_index) const;
   private:
           Array storedArray = Array();
}
//in a corresponding cpp file
T* TypedArray::operator[](int p_index){
     return Object::cast_to<T>(storedArray[p_index]);
}
```

or 

C. make TypedArray completely it's own type

```
template<class T>
class TypedArray{
   public:
      T* operator[](int p_index);
      const T* operator[](int p_index) const;
   private:
           std::variant<T> storedArray = Array();
}
//in a corresponding cpp file
T* TypedArray::operator[](int p_index){
     return storedArray[p_index];
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

```
TypedArray<MyClass> myClassArray;

void doSomethingWithMyClass(){
    MyClass* retrievedClass = Object::cast_to<MyClass>(myClassArray[0]);
}

void doSomethingWithMyClassInALoop(){
    for(int i = 0; i < myClassArray.size(); i++){
          MyClass* retrievedClass = Object::cast_to<MyClass>(myClassArray[i]);
    }

}

```

### Is there a reason why this should be core and not an add-on in the asset library?

though it may or maynot help performance, the main reason why I think this should be in core is because it'll help confusion. Most beginners who elect to use GDExtensions over using C# or GDScript will expect TypedArray<T> to actually return the type of the array, and those who haven't found out that there's 'Object::cast_to<T>()' function will try to cast normally then get confused as to why that doesn't work. Not to mention in a lot of scenarios it's not realistic to use static arrays or normal C arrays as a lot of times they need to be able to shrink and grow (plus in the case of properties they can't really be used to expose a full array to the editor as normal C arrays are not variant types)

**Comment by AThousandShips** [comment]
This matches the engine, both in scripting and c++

**Comment by xana43** [comment]
> This matches the engine, both in scripting and c++, and uses the same system as c++, this would be complicated to implement and should be done at least on the c++ side of the engine first
> 
> Further, there would still be casting, so any performance overhead with casting would remain, as `Array` always stores `Variant`, this won't and can't change without fundamentally reworking how `Array` works, and it's largely unavoidable to keep `Array` compatible
> 
> Note that `Array` is designed for use in the engine when interacting with scripting, when not passing data like this you should just use `Vector` in extensions

most of the data that i'm trying to work on using arrays are set using the editor as these are part of exported properties. it doesn't seem to be possible to use vectors to take in this information as vectors are not a variant type. I will experiment to see if I can find a work around though.

**Comment by xana43** [comment]
I was looking through the source code to see how the engine does this, two things I noticed A. I completely forgot about packed arrays, and B. there doesn't seem to be much in the way of Vectors that are exposed as an exported property (in terms of the the other types used outside of the packed arrays). I'll continue to look into it though, and see if i'm missing something.
