### ISSUE TITLE
Better workaround for some access modifiers in GDScript

### ISSUE THREAD

**Issue by CHERNOMORGAMES** [godotengine/godot-proposals#9264]
### Describe the project you are working on

Library for gdscript.

### Describe the problem or limitation you are having in your project

Related to https://github.com/godotengine/godot/issues/18411
Since 'real' modifiers not coming anywhere soon, workarounds is the only option.
But, since Godot 3, those workarounds regressed a bit, because ```setget``` syntax has changed in Godot 4.

What I think of is 2 workarounds for ```readonly``` modifier (speaks for itself) and ```hidden``` modifier, which is close to ```private protected``` one in C#. For the names, i think they must not copy C# naming, since they wont work the same way in godot, because full-scale access modifiers are not even planned to be implemented to the core. Workarounds can be done like this:

1.
```
var readonly_var = 'anything' : set = _readonly
func _readonly(a): return
```
2.
```
var kindof_private_var :String = 'only same type getter' : set = _readonly , get = _hidden
func _hidden() -> String: return 'I cant reuse this code for other types and in other scripts'
```

I have two problems here.
1. readonly workaround is fine but, it cant be reused. I have a utility class, but such code returns error:
``` var readonly = 'anything' : set = ut.readonly ```
So, the only way to not put ```func _readonly(a): return``` in every single script where I need it is to inherit all of them from my utility class. Which obviously is not always possible, limits me to my utility class as a sole class I can extend, e.t.c.
2. hidden workaround has same problem from №1, but also is type unsafe, what makes reusing it even harder. I have to make a hidden getter for each type and put it in each script or limit myself to only one class I can extend.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make workarounds simplier and more effective.

1. If possible, make ```readonly``` and ```hidden``` keywords solving the issue.
2. For setters and getters, adding the ability to write whole function inside set or get statement and to use dot to access classes.
3. Remove the requirment for getter return type not in general, but at least to make it able to return ```null``` for any kind of type he refers to.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. A perfect solution would use some kind of keywords and look like this:
``` var kindof_private_var = 'any type' : set = readonly , get = hidden```

2. Not so good, but still something for setters:
```var readonly = 'anything' : set = utility.readonly```
AND/OR
```var readonly = 'anything' : set = func(a): return```
Well, in a perfect word I would like to have => syntax like in javascript, but who cares.

3. Not so good, but still something for getters:
```
var kindof_private_var = 'anything' : set = utility.readonly , get = _hidden 
func _hidden(): return null
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Negative

### Is there a reason why this should be core and not an add-on in the asset library?

Why it should be done? To make gdscript a complete language you can be proud of, not a mimicing one which brakes every time you try to do something codewise creative on it.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/820
* https://github.com/godotengine/godot-proposals/issues/641

**Comment by Mickeon** [comment]
I wouldn't know about consolidating them. This proposal describes a more direct solution that is related to the other proposals, but is not one and the same.

**Comment by AThousandShips** [comment]
That should be added to those ones instead, as they are two distinct features, and is already extensively discussed there
