### ISSUE TITLE
Global 3d Axis View Gizmo out of the box.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot-proposals#927]
Hello. I am working on basic projects. Learning the basics of Godot engine workflow.

I cannot find a way to enable world axis view gizmo to change world view fast when editing scenes with the mouse. Nowadays we have to click a menu and then click on the required view option.

I propose enabling axis view gizmo in the right top corner out of the box in a similar way of blender and other 3d software.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

It can not be enabled with a simple script.

This usability feature is currently standard on 3d software and greatly improves 3d scenes editing.

**Comment by Zylann** [comment]
Check Godot 3.2.2 beta3:
![image](https://user-images.githubusercontent.com/1311555/83066783-7c895880-a05d-11ea-909d-403687c294e7.png)

**Comment by Calinou** [comment]
This is indeed implementated in 3.2.2 betas and the `master` branch, closing.

**Comment by jcarlosrc** [comment]
Good. Glad to see usability improvements for future releases. Thanks.
