### ISSUE TITLE
Replace Label by a LineEdit for GraphNode Title

### ISSUE THREAD

**Issue by m21-cerutti** [godotengine/godot-proposals#9271]
### Describe the project you are working on

I am working on a visual script solution for editing CI pipeline.

### Describe the problem or limitation you are having in your project

I am using GraphNode and GraphEdit to make my tool interface, but I would want to make title editable. It would allow a user to rename nodes directly, and It would be better of readability and ux in my use case.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There is some others solutions not refactoring title label, but the title field would be kind of useless by displaying static type of node or ID. It would be not readable on big graph, and also secondary to what would want an user by writing a custom name. This name could be handle in slots with a deactivated section with other informations, but difficult to maintain a information hierarchy with other nodes that would not need this custom name.

For now, it would mean to replace the default Label by a LineEdit, but I was wondering if it would not be part of https://github.com/godotengine/godot-proposals/issues/5271, where we could give to user a Title section with lineedit properties like "Editable", "Flat", etc and bring some signals from the LineEdit.

The only other ways would be to make custom GraphNode with https://docs.godotengine.org/en/stable/classes/class_graphnode.html#class-graphnode-method-get-titlebar-hbox but break the title field usage, or making it from scratch with a GraphElement. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Instead of a Title field like here

![image](https://github.com/godotengine/godot-proposals/assets/23432929/92f57231-f87e-4139-8438-9131793cc25a)

We could expose LineEdit properties in a Title group:

![image](https://github.com/godotengine/godot-proposals/assets/23432929/27e1e332-8b70-497b-b71a-3450e9053e0e)
 
 We could also make Flat and not editable by Default to have same behaviour as old label one.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If we not use title field it can be hacked by deleting the title label, but I would think this feature could be use broadly for Graph tools or edition.
Would also be better for future TitleBar customisation.

### Is there a reason why this should be core and not an add-on in the asset library?

GraphNode is core and would be more simple to add on GraphNode than doing a whole custom GraphNode as add-on.

**Comment by Calinou** [comment]
I'd probably handle it differently instead, both for ease of implementation and UX reasons.

Keep the Label as-is, but make it so a popup appears when you double-click the title. In this popup, have a LineEdit that asks the user for a new name (with the current name already filled in). When the user confirms this popup, replace the existing title with the new title.

The UX reason for doing this is that making the title a LineEdit will make it a lot harder to drag the box around, since single-clicking it will select text inside the LineEdit (even if it's read-only!). By making renaming require a double click, you avoid this issue.

This can likely already be done with a script too.

**Comment by m21-cerutti** [comment]
Good idea, I was using double click to open another graph in the example (kind of of special case in my app due to recursive behaviour), but that can be changed.
If I could make double click different on the title and the body of the node that would be great, but need some experiment for it (like attaching script to the title lavel, but don't know if it would work with double gui_input).
But could be also implemented via a open button or other interaction.

**Comment by m21-cerutti** [comment]
Work like a charm !
![ezgif-5-bd9b5a820b](https://github.com/godotengine/godot-proposals/assets/23432929/06c28cc1-4d9e-42d9-ae41-3ce44611c140)
