### ISSUE TITLE
Make `range()` return `Array[int]` instead of an untyped Array

### ISSUE THREAD

**Issue by feois** [godotengine/godot-proposals#9277]
### Describe the project you are working on

Irrelevant 

### Describe the problem or limitation you are having in your project

Not really a problem, just a small change that barely affects anybody

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Just a small enhancement

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

range() returns Array[int] instead of Array

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes

### Is there a reason why this should be core and not an add-on in the asset library?

range() is core function

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot/issues/87152

This would break compatibility by returning a different type

**Comment by feois** [comment]
Didn't realize `Array` is incompatible with `Array[Type]`
