### ISSUE TITLE
Assign a default shortcut to `Open in File Manager`

### ISSUE THREAD

**Issue by Hezaerd** [godotengine/godot-proposals#9284]
### Describe the project you are working on

A physics-based 3D game that uses lots of different files.

### Describe the problem or limitation you are having in your project

Having to right-click on each file and click on the "Open in File Manager" button is a bit clunky to use and slow down a lot my workflow. And it's not intuitive at all to have the shortcut already there but not assigned.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Assign the shortcut CTRL + B by default

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I've done a [PR](https://github.com/godotengine/godot/pull/89391/commits/82876f46ab67f477e10648699c3d2b1517bcfc0d) on the godotengine/godot repos with the implementation

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes and no... each user could define the shortcut in their settings, but the principle is to make it the default.

### Is there a reason why this should be core and not an add-on in the asset library?

t's just a setting in the engine, so it would be counterproductive to make it an add-on to be included in every project every time.

**Comment by AThousandShips** [comment]
> And it's not intuitive at all to have the shortcut already there but not assigned.

Many shortcuts are undefined, I don't see this as one that desperately needs one defined, I believe most people don't use this feature

**Comment by Hezaerd** [comment]
Yes, of course. If the engine's philosophy is not to define this kind of shortcut by default, I agree.

**Comment by AThousandShips** [comment]
There's plenty of others, and locking up a simple shortcut like `Ctrl + B` is risky, it would prevent this being used generally (for the editor globally) or specifically for the file manager, which would need to be weighed against the need, there's a lot of used shortcuts already and they don't come cheap

**Comment by Hezaerd** [comment]
Yes, I quite agree. There's no need to clutter up the editor with something that can be done in the settings and lose a valuable location for a future useful or crucial shortcut.
So on that basis I'm going to close the PR! Thanks for the feedback
