### ISSUE TITLE
TileMap using the engine draw/paint

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot-proposals#9287]
### Describe the project you are working on

For 2d games all types / most common used platformers and topDown Games

### Describe the problem or limitation you are having in your project

- Currently the godot4 tileMap system was made in a way that it could please the largest number of people.
- In way it can be use has destructible terrains ( broFroce ), or by drawing levels ( castlevania/ contra/ the chaos engine )
- Every tile in gd4 can have collision, has draw call, data related to each tile, etc... This makes it frustrating for people that just want to draw levels, due to the large overload it takes on each level.
- The results are fps between 200 fps to 300 fps using gd4 tilesets | VS | 2000 fps to 3000 fps when tiles are removed. 
- This takes out the fun of using tileMaps, because The person is always asking himself the question ( shouldn't i be using a png image instead ? )

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Tiles can be drawn individually in the the engine editor then grouped together into a single draw call.
Their color can be changed / flip / rotate / size / merge layers... just like using a drawing program.
This wont take any toll on the engine has its all converted into 1 drawCall ( 1 image ), or divide the image into parts of 4.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Its already working...
The problem here is how convoluted and messy the engine plugINs are / the information that is provided in the manual was NOT made by the person that created those functions...
Making something so simple has a simple boolean check so see if the TileDraw node is selected an absolute nightmare.
Whatever is in the plugINs editor is not working, people who say they know often have an idea of how it works withOut truly knowing resulting in passing false information.
This gives the idea that whoever made the plugINs functions had an intent to make it work in a simple and easy way, but this person is long gone, leaving the information scarce and confusing.

The result is noone knows anything about it in the GD comunity, and its a topic that its left out noone wasnt to mess with it.
An easy way to see how the information about plugins in the manual is working, is to compared it to the bug report issues in the GD github, were often an MRP (minimal reprodution project) is always asked. This is how a normal person your everyday average intelectual celebrity handles information. In the plugin manual not even one single line of code is writen, not to mention something so above has an MRP. Making the info in the manual an absolute nonsense. 

DRAWING WITH TILES
WORKING EXAMPLE:
-------//-----drawing-tiles-running-the-scene--//----------
https://github.com/jonSP12/godot-4-TileDraw
![268793287-15cf714a-f6c9-48d9-a311-dcde2070b457](https://github.com/godotengine/godot-proposals/assets/77213594/43ea0ff0-0933-4df4-962a-b475b0d9bbc3)

-------//-----using-a-plug-IN-(NOT WORKING)--//----------
https://github.com/jonSP12/TileDrawPlugIN_test01

https://github.com/godotengine/godot-proposals/assets/77213594/7346f1ee-f370-4da1-8ae8-bd6fc07737e2

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Ho, this enhancement will be used often. Whenever the subject of tiles is mentioned in godot a lot dirt starts to surface, like the engine preformance, more features, etc... People trying to evade the subject and asking how to use godot to make a drawing program instead, normally getting the same answers like a viewPort and so on, that also bring the engine performance into question, making them question instead ( WTH  is going on ? )

\\ TileMaps in godot need to be divided into 2 //
- People that want to make destructible levels for on side.
- People that want to draw levels for the other side.
- You put them togheter, and you will have a bunch of insterical people running around, were noone will be able to do anything.

### Is there a reason why this should be core and not an add-on in the asset library?

because for it to be in the asset library someone would need to know how the plugINs work, without looking into the manual or google search.

Drawing with tiles is has important has using tile has objects.
The current tileDraw should have the same reasons to be in the asset library, has the tileMap used in GD4... And vise versa...
Currently the only option avaiable in Core is the latest a diference of 500fps to 3000fps depending on how many tiles/layers are on the level.
Making the fps even lower if more features are added like changing color.
All this things that a simple tileDraw could make with ZERO impact on perfomance.

**Comment by jonSP12** [comment]
Dont know what is there to be confused about it.  --- simple Test, png image VS tileMap --
( Must be one of those mothos If 1 is all hes little friends follow. )
But Fine I'll do this alone anyway... Its just that the functions and descriptions in the manual wasnt me, and i have to read that.

**Comment by jonSP12** [comment]
Dont know what is there to be confused about it.  --- simple Test, png image VS tileMap --
( Must be one of those mothos If 1 is all hes little friends follow. )
But Fine I'll do this alone anyway... Its just that the functions and descriptions in the manual wasnt me, and i have to read that.

**Comment by AThousandShips** [comment]
> Must be one of those mothos If 1 is all hes little friends follow. 

What are you talking about? Are you saying that this is just people reacting based on what one person (a moderator?) reacts rather than their own opinion?

**Comment by jonSP12** [comment]
I dont know whos a moderator or not. But it is what it looks like, so yes that is what iam saying.
but Focus on the thing...
Godot already has a function ( ImageTexture.create_from_image )... You could anything with this, apply blur shaders to it / change the color, brightness etc... / merge 2 images into 1, like merging layers.
And the engine doesnt care it treats everything like 1 big image made in photoshop.
Dont know what is there to be confused about it, its not an idea its just something that is already there and its not being used.
I dont see how this can be done in the current tileSets with all the spaces for collisions boxes flying in there, and individual tiles that can be accessed in code, without bringing the performance down.
Photoshop wasnt made to be used has a tileMap, with this type of editor in the engine the levels could drawn and edited very fast.

**Comment by AThousandShips** [comment]
Then you need to not make such statements or assumptions, everyone responds on their own account, not based on what someone else is doing, and saying they do is unprofessional and rude.

I can't speak for anyone else, but my confusion stemmed from that it was largely impossible for me to understand what you were saying, and that a large portion of it is irrelevant ranting, rather than descriptions of what you are actually proposing, this isn't a blog post, this is about explaining your idea to others :)

So, you're free to reopen this, because a few people reacting like this to it isn't saying anything, and you shouldn't base your approach on what a few people react, but you do need to be more professional and respectful if you do, and if you are going to be engaging with the community, this attitude is not acceptable

**Comment by jonSP12** [comment]
"unprofessional and rude" is to shove colliders, rotating / flip data / coordinates data, etc... into every TileSet that is drawn on to a level, making the games much slower and ( !!! confusing !!! ). But that doesnt bother you, maybe if you had the same motivation to address those problems instead of how people respond to something that is working bad, things would be better.

And the community its the 5 or 6 people, who worked on tileMap and created the problem in the 1st place, i dont see anyone else ( confused ), so thank you... thank you very much for whatever help comes at me. All i was asking was some advice on getting the plugINs to work, because thats a mess. But its fine no help needed here.

**Comment by AThousandShips** [comment]
I'm asking you again to read the code of conduct, this is inappropriate and not constructive, either follow the rules or don't take part, you can't refuse to follow the rules *and* engage here, there are rules
