### ISSUE TITLE
Make warnings/notes in build scripts colored

### ISSUE THREAD

**Issue by dustdfg** [godotengine/godot-proposals#9291]
### Describe the project you are working on

Just build custom export template and try master branch

### Describe the problem or limitation you are having in your project

The build process shows me blue text (when it compiles files) but the warnings have the same white colors as any other text

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When you see a bunch of white text for especially when you enable SCU you can't notice if there was any warning because it scrolls out too quickly. If I saw a yellow color between white I would notice it...

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Use not just `print("Note: Using `execinfo=yes` for the crash handler as required on platforms where glibc is missing.")` but something [like it](https://stackoverflow.com/questions/287871/how-do-i-print-colored-text-to-the-terminal) at least in [linux specific script](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/detect.py)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is for those who enter godot building or just want custom export template so it won't be used much but can't be worked around

### Is there a reason why this should be core and not an add-on in the asset library?

It is a part of the build system

**Comment by Calinou** [comment]
Regarding the SCU build text (which I also find intrusive over time), I think we could simplify it so it takes fewer lines. We could display something like "SCU: Merging N files into 1 file.") and possibly display it in gray as well.

cc @lawnjelly

**Comment by akien-mga** [comment]
Implemented by https://github.com/godotengine/godot/pull/91220.
