### ISSUE TITLE
Save system : LocalStorage

### ISSUE THREAD

**Issue by MintStudios** [godotengine/godot-proposals#93]
**Describe the project you are working on:**
Money-Tracking App

**Describe how this feature/enhancement will help your project:**
Making saving way way way easier

**Show a mock-up screenshots/video or a flow diagram explaining how your proposal will work:**
![image](https://user-images.githubusercontent.com/54677274/65376828-c9b55f00-dc72-11e9-9d9f-3c7ee2700f17.png)

**Describe implementation detail for your proposal (in code), if possible:**
This would be like JavaScript, 
`localStorage.somevar("blah")`
 or to access,
`anothervar = localStorage.somevar()`

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, this enhancement will be used a lot, as the current saving and loading system is confusing.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't think this can be an add-on, but if it can, great!

**Comment by Calinou** [comment]
Doesn't saving to `user://` save to localStorage?

**Comment by MintStudios** [comment]
IDK, I think that the current save system sucks. I've been trying to do it for the past couple of days, looking at the docs and tuts on youtube, but,   no luck.

**Comment by Calinou** [comment]
@MintStudios Please describe accurately what you think is missing in the current save system. Otherwise, we can't know what should be improved.

**Comment by Jummit** [comment]
> I don't think this can be an add-on, but if it can, great!

This can be made as an add-on.

**Comment by MintStudios** [comment]
OK, I am closing this because no further discussion is needed.
