### ISSUE TITLE
Provide Nightly builds on the main branch.

### ISSUE THREAD

**Issue by Delsin-Yu** [godotengine/godot-proposals#9302]
### Describe the project you are working on

Testing newly merged features of the GodotEngine.

### Describe the problem or limitation you are having in your project

Nightly builds improve the accessibility for an engine user to test a new feature without building their engine.

Users have to clone and build their own engine binaries for now if they wish to test the latest feature recently merged to the main branch.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

N/A

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, engine users have to clone the GodotEngine repo and perform a mono build every time for testing.

### Is there a reason why this should be core and not an add-on in the asset library?

This is not a part of the Core

**Comment by AThousandShips** [comment]
What is the specific importance of this? The CI builds are relatively minimal especially the templates, so the usefulness to test things are relatively minimal, compared to the extra build time (windows builds are slow as it is) and extra artifact storage

**Comment by Delsin-Yu** [comment]
> What is the specific importance of this? The CI builds are relatively minimal especially the templates, so the usefulness to test things are relatively minimal, compared to the extra build time (windows builds are slow as it is) and extra artifact storage

That's a good point and I do agree with it. I will update my proposal shortly.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1458.
