### ISSUE TITLE
Add and emit <property>_changed signal on GDScript custom ressource properties

### ISSUE THREAD

**Issue by m21-cerutti** [godotengine/godot-proposals#9316]
### Describe the project you are working on

A visual script CI Tool.

### Describe the problem or limitation you are having in your project

I am not interested in the emit_changed signal because it seems overkill when wanting to update UI only for a specific property to listen to other changed properties. When having a lot of properties inside a resource, seems inefficient.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I have seen the issue https://github.com/godotengine/godot/issues/30179 and the documentation where it is recommended for custom ressources to manually call emit_changed function (changed signal), why it isn't by default if we don't make a setter ?

Would be the same problem for this news signals but have less consequences since it would be for gdscript users and custom logic.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The ideal usage would be to allow using the signal without connecting it with signal name API, like this :

```gdscript
class_name BigRessource
extends Ressource

# Have interface_changed signal
@export var interface: String = ""

# ... and a lot of others fields

# Would not have local_changed signal
var _local: String = ""

# ...

```

```gdscript
extends Node

@export var ressource: BigRessource

func _ready():
	ressource.interface_changed.connect(self._on_interface_changed)

func _on_interface_changed():
	$UILabel.text = ressource.interface

```

It also make sense that const and readonly properties would not have this signal.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

For now I am using the user_signal API, but it's heavy and need a base class for all my ressources. Look something like this:

```gdscript
class_name Data
extends Resource


func _init():
	var all_properties = get_property_list()
	all_properties = all_properties.filter(func(property): return property["usage"] & PROPERTY_USAGE_SCRIPT_VARIABLE and !(property["usage"] & PROPERTY_USAGE_READ_ONLY) )
	for property in all_properties:
		add_user_signal(property["name"]+"_changed",[])
		
```

```gdscript
class_name TestData
extends Data

@export var test: String = "":
	set(value): 
		test = value
		emit_signal("value_type_changed")

```

```gdscript
extends Node

@export var ressource: TestData

func _ready():
	ressource.connect( "test_changed," self._on_test_changed)

func _on_test_changed():
	$UILabel.text = ressource.test

```

We can see to write it"s heavier than the proposed solution, and we have the risk to forget to implement signal emit in setter.

### Is there a reason why this should be core and not an add-on in the asset library?

Would be more convenient and also would permit to have signal autocompletion inside the editor more easily if it's handled in core.

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot-proposals/issues/4867

**Comment by AThousandShips** [comment]
Consolidating there then, thank you for your proposal
