### ISSUE TITLE
code highliting readability lack for colorblinds (change from a highlight to an underline like in others code editors

### ISSUE THREAD

**Issue by saminouche** [godotengine/godot-proposals#9320]
### Describe the project you are working on

a project that requires coding (any project)

### Describe the problem or limitation you are having in your project

as a colorblind, I cannot read what is written under the big red ugly highlight in the code editor on errors

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

could change to an underline or a pointer (like in most others code editors, it works fine that way)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

<ins> something like that </ins> instead of `like that`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

.

### Is there a reason why this should be core and not an add-on in the asset library?

accessibility is important, do we really want to discriminate colorblind people ?

**Comment by dalexeev** [comment]
* See also #1005.

**Comment by saminouche** [comment]
issue 1005
