### ISSUE TITLE
Improve text shadows to feather

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot-proposals#9324]
### Describe the project you are working on

I'm working on a game with text, together with a graphic designer who'd love more text rendering features in Godot!

### Describe the problem or limitation you are having in your project

Shadows on text in Godot behave more like hard outlines with an offset while basically any graphics design program considers text shadow to be a feathered outline with its opacity and intensity becoming gradually less the further you move away from the text itself. Example:

![Screenshot 2024-03-18 at 09 12 44](https://github.com/godotengine/godot-proposals/assets/5611323/7e700b78-1300-45da-a157-b3efc6f6702e)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Replace the current shadows in Godot with shadows like in graphic design programs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know anything about font rendering. Sorry to be so unhelpful in that regard.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm guessing someone with intimate knowledge of shaders could produce shadows like in graphic design programs, but that person isn't me unfortunately.

### Is there a reason why this should be core and not an add-on in the asset library?

Shadows are already part of core Godot.

**Comment by Calinou** [comment]
Godot 2.x's bitmap font importer supported soft shadows, but these were rasterized on import so performance wasn't a concern. In comparison, traditional (non-MSDF) DynamicFonts are rasterized on demand, so we need to make sure the blurring algorithm used isn't too slow for this use case.

For MSDF fonts, rendering blurred shadows at no added cost should be trivial as changing the MSDF sharpness is a matter of changing a few constants.
