### ISSUE TITLE
Add Alt + Right mouse button functionality to all 2D modes in the editor

### ISSUE THREAD

**Issue by Broken1334** [godotengine/godot-proposals#9332]
### Describe the project you are working on

Any 2D project

### Describe the problem or limitation you are having in your project

Currently in 2D Alt+RMB ("Show list of selectable nodes") works only in Select mode.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add Alt+RMB functionality to all 2D modes, like in 3D. It helps to keep UX consistency and add more flexibility.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by Arnklit** [comment]
Should be resolved by https://github.com/godotengine/godot/pull/99795
