### ISSUE TITLE
Add a way to instantiate a node and add it as a child to a parent node in the same function call

### ISSUE THREAD

**Issue by fkeyzuwu** [godotengine/godot-proposals#9342]
### Describe the project you are working on

Not relevant, this feature can be used in virtually any context.

### Describe the problem or limitation you are having in your project

Very often, when instantiating a node from a packed scene, you follow it up with adding it to the scene tree in order for it to become visible, active, etc. Having a way to add these two actions together into one function call would help with:

1. Quality of life - only having to use one line instead of two whenever you are instantiating a node and adding it into the scene tree.
2. Beginners(and sometimes even seasoned Godot devs) can often instantiate a node, and forget to add it as a child to the scene tree afterwards, causing unexpected behavior. This could help make this error less common.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There's two possible solutions:

1. Add a brand new method called something like `instantiate_as_child`, taking a `parent` node as an argument. This method works fine. However it ends up being a pretty long name, and also a different method than the normal `instantiate`, so it's likely to get overlooked by people and not be used often.

2. The second solution would be to add a `parent` node default parameter to the current `instantiate` method. This would be far more cleaner and elegant imo, as well as it would prompt any old or new user to add a parent node inside of the parentheses with intellisense, which would hopefully eliminate most instances of forgetting to add the instantiated node to the scene tree. 
However, the problem with this is that there is already currently a default parameter in the instantiate method, so you cannot add a new default parameter before the previous one without breaking compatibility. That default parameter is a GenStateEdit enum which is not used very often, but I'm still suggesting this on the off chance that it would be worth breaking compatibility for this.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Method 1:
`var node = scene.instantiate_as_child(parent_node)`
Method 2:
`var node = scene.instantiate(parent_node)`

I also made a pull request demonstraiting Method 1: https://github.com/godotengine/godot/pull/89687

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around easily, however if it would be added it could be used in virtually any kind of project.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a very common use case.

**Comment by AThousandShips** [comment]
As mentioned on the PR:
I'd also add that I feel that the normal case is to do something with the instantiated node beyond just adding it, setting a position, modifying some value, etc., I'd say this case where you just add it is an exception

**Comment by fkeyzuwu** [comment]
> As mentioned on the PR: I'd also add that I feel that the normal case is to do something with the instantiated node beyond just adding it, setting a position, modifying some value, etc., I'd say this case where you just add it is an exception

I somewhat agree with this, but I feel like because an instantiated node practically does nothing UNLESS you add it to the scene tree, its a bit different than the other things listed here.
> > Method 2:
> > `var node = scene.instantiate(parent_node)`
> 
> This would obviously not be valid, it'd be: `var node = scene.instantiate(edit_state, parent_node)`

As stated, this would be assuming the breaking changes **would** go through, by switching the order of the GenEditState parameter with the parent Node parameter. Otherwise I wouldn't advise for this method as you wrote it, since it looks pretty atrocious writing the whole enum just to be able to add the parent node afterwards, especially since it is not really relevant in 99% of cases:
`var node = scene.instantiate(PackedScene.GEN_EDIT_STATE_DISABLED, parent_node)`
It kind of defeats the purpose of this PR to have a clean and easy way to do this sort of thing.

> > only having to use one line instead of two whenever you are instantiating a node and adding it into the scene tree.
> 
> Two lines how? What's wrong with:
> 
> ```gdscript
> parent.add_child(scene.instantiate())
> ```

This does let you have a reference to the instantiated node.

> This wouldn't solve this issue, as they'd have to remember to use this _new_ method that isn't used anywhere in the documentation or tutorials, it's also an extremely rare issue that is best solved by people learning how to do things properly, this feature risks making that worse by adding complexity and making new users rely on a feature they can only use some times, and then fail when they do anything complex

You are right, adding this as a seperate method does really do anything, or makes anything easier.. I guess the real option here would be Method 2, which would be much cleaner, assuming we switch the order of GenEditState parameter and the parent Node parameter. But if this is a no go since it introduces breaking changes for not enough value, and would be very unlikely to be approved.. then I guess we don't have to waste time and can close this proposal/pull request.

**Comment by AThousandShips** [comment]
I'd say that the two line operation isn't really a relevant difference from just adding it as a child and forgetting about it, most of the operations you want to do on a node you do *before* you add it to a parent, in my experience, like setting its position or configuring it

You also can't use that method on a thread, which is how many instance their nodes in practical cases, where you need to call `add_child` deferred

So I'd say that the number of times you:
* Aren't on a thread
* Aren't going to do anything to the node before you add it to the scene
* Still need the instance for something

Is very rare

**Comment by ettiSurreal** [comment]
I usually find myself using `get_tree().current_scene.add_child()` or `get_tree().current_scene.add_child.call_deferred()` to make the instantiated nodes independent from the parent (this is something that should probably be taught more), so this would not be all that useful regardless.

**Comment by fkeyzuwu** [comment]
> I'd say that the two line operation isn't really a relevant difference from just adding it as a child and forgetting about it, most of the operations you want to do on a node you do _before_ you add it to a parent, in my experience, like setting its position or configuring it

> And I'd say that if new users rely on it to ensure they remember to add it to the scene they risk doing less than optimal practices like setting local position _after_ adding it to the tree, which is slower (not necessarily by much, but I consider it a good practice to do it before, as it skips a lot of propagation and updates)

Honestly, that's news to me. That's a good thing to know, that we should do operations to instanced nodes BEFORE adding to the scene tree. Doing this the other way around using the new method would make this addition actively hurtful.

With all things mentioned here I can agree this is not an optimal change in most cases. Closing this. Thank guys!
