### ISSUE TITLE
Move Project Manager settings from Editor Settings to Project Manager Settings.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot-proposals#9357]
### Describe the project you are working on

Any dotnet project in 4.3.

### Describe the problem or limitation you are having in your project

Currently the Project Manager automatically creates the directory from the project name which is great (and as needed) but it doesn't work well with C# standards, for example a project named "My Big Project" will have a directory named as "my-big-project".
This will also be used as the top namespace in C#.
C# doesn't use this formating so it's at least odd if nothing else.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have the dotnet editor builds use traditional PascalCase so the "My Big Project" would produce a directory named "MyBigProject", or have a setting in settings to toggle PascalCase (godot editor already has this setting so perhaps the Project Manager could have the toggle in its own settings too?).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Code wise no idea how this works in godot.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The workaround is to disable the auto project creation, create a directory manually and browse there when creating the project.
(It doesn't feel right to disable a new functionality for this though.)

### Is there a reason why this should be core and not an add-on in the asset library?

It's the project manager.

**Comment by KoBeWi** [comment]
There is `project_manager/directory_naming_convention` editor setting. We could add it to the Settings menu in Project Manager.

**Comment by viksl** [comment]
Yeah, considering the functionality alread exists.
While on topic, since ProjectManager has its own settings and in side the Editor settings there are only 3, shouldn't all of that be in settings of the project manager to begin with?

**Comment by KoBeWi** [comment]
Sorting order and default renderer can already be set from Project Manager, just not from the Settings menu. The sorting is automatically saved when you set sorting and renderer when you create a project.

**Comment by viksl** [comment]
My bad I should have realized it was already there around the manager.

When it comes to the mockup, personally I'd still shove it into settings. This feels like a clutter in the create new project dialog. Considering this kind of settings is most likely a one time toggle it doesn't seem to be necessary to have it visible every time.
Can you perhaps come up with some cases when people change this often or would need to change it often/per project basis, please? Right now I can't really come up with any reason anyone would need to change it regularly but I might be missing something here.
For example Renderer seems something you want to have everytime available, version control too but right now I just can't justify the casing/naming control element like this here.

But as far as I'm concerned as long as it's available in the Manager to begin with it's better ;-).
