### ISSUE TITLE
Add WorldEnvironment custom material override

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot-proposals#936]
**Describe the project you are working on:**
3d open world game

**Describe the problem or limitation you are having in your project:**
Custom world effects are difficult to pull off.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Custom material override would enable various effects, incl. debugging overlays.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See original issue for mockup.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Nope.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't think asset lib could do it, it is highly likely it requires core changes (but I could be wrong, I'm not a Godot developer)

Original issue: https://github.com/godotengine/godot/issues/20280

Related issue:  https://github.com/godotengine/godot/issues/27911

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/10546, which is more detailed.
