### ISSUE TITLE
Add a way to immediately see the value of a constant without scrolling to its declaration

### ISSUE THREAD

**Issue by drippyParrot** [godotengine/godot-proposals#9365]
### Describe the project you are working on

A multiplayer game with hundreds of special feature weapons.

### Describe the problem or limitation you are having in your project

My workflow requires having an enormous number of constants declared inside a single script and simultaniously being able to sort their use cases into optimized categories. These categories are immediately obvious from the numerical value but the constant name is a specific to make multiple references easier. Adding the numerical value to the end of the name adds a lot of visual clutter and may not be possible in other projects encountering a similar problem.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A way to have the value of all the constants in a selected line be immediately obvious would be tremendously helpful.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I believe as tooltip hint / additional entry next to the line indicator this could be easily solvable.
I imagine the latter one along the lines of "weapon_x = 516  243 : 19"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, but it does not interfere with workflow not utilising it.

### Is there a reason why this should be core and not an add-on in the asset library?

An asset library instalable addon seems a little tedious for such a small feature.
Also, developers encountering this sort of problem are generally tempted to stick to scrolling up and down their script before even having the idea that such a feature might be useful ;)

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1393.
