### ISSUE TITLE
Improve in-engine links that will open in a web browser

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#9369]
### Describe the project you are working on

stuff

### Describe the problem or limitation you are having in your project

![image](https://github.com/godotengine/godot-proposals/assets/71937306/e64c57e8-3ce4-49d6-8dbc-fceaf3124d78)

Sometimes in the integrated docs there are links that when clicked, will open an url in the browser (as opposed to another page of the integrated docs). It's not that clear at a glance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- make those links blue with an underline appearing on hover,
- add the "external link" icon at the end of the link text,
- maybe add a tooltip when hovering, stating that it will open in the browser, and maybe the url?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/71937306/be39a13b-4de6-4865-a647-7c2c0720763b)

![image](https://github.com/godotengine/godot-proposals/assets/71937306/b7a1e1d4-8692-4c9e-84ed-d07d1b8e02d8)

idk if the icon should be colored, it looks correct like that to me.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

can't be worked around

### Is there a reason why this should be core and not an add-on in the asset library?

core already

**Comment by dalexeev** [comment]
* See godotengine/godot#89049.

> Note that this PR does not affect `[url]` tags at all for clarity.

CC @Mickeon

**Comment by Mickeon** [comment]
Ever since that PR, because the underlines no longer show on *every* link, the fact that they always show exclusively on these external links would already make them stand out more.

I do like the icon though... Could even use a "Click to open on browser" tooltip...

**Comment by mieldepoche** [comment]
I believe the icon alone is enough to communicate the browser part, but the coloring and dynamic underline make it feel extra obvious, web-browser-like, and pleasant to use. I don't like the fact that the current color is the normal text one, and I don't like the static aspect of it.

**Comment by Mickeon** [comment]
The current built-in documentation has a very limited colour palette (basically monochrome, between text and accent color) that I wanted to maintain for the time being. There used to be some concern that anything more would've hurt readability.

However, with efforts such as https://github.com/godotengine/godot/pull/89263 , there may be more of an encouragement to go ahead and make things more stylistically pleasing.
At some point I had hue shifts depending on the linked subject. I do look forward to experiment with it more at some point.
