### ISSUE TITLE
Collision Layers and Mask names should be zero-indexed, consistent with underlying collision bit indexes

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot-proposals#9375]
### Describe the project you are working on

A game using collisions layers and masks

### Describe the problem or limitation you are having in your project

It's needlessly confusing that collision layers are 1-indexed, but the underlying bits are 0-indexed.  They should be consistent.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Start counting layer names at 0 instead of 1, that way it will match the bits, so you don't have to worry about off-by-one errors every time you want to set layer 9 and have to mentally correct your set_collision_mask_bit to hit bit 8 instead.

![image](https://github.com/godotengine/godot-proposals/assets/89282845/99991213-a9bc-41ec-9507-9087e1cbc06b)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just change how the UI counts things, I'm pretty sure that the layer numbers are purely editor-space and don't get reflected in the underlying engine

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Core engine functionality, can't be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?

This is pretty core to how the editor displays layers.

**Comment by Proggle** [comment]
Oh, this was actually changed in v4 so set_collision_mask_value takes the layer number.  Still think it's weird that they're off-by-one, though.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/2050.
