### ISSUE TITLE
Add option to exclude the `addons` folder (or any other folder) from search operations in the editor

### ISSUE THREAD

**Issue by nubels** [godotengine/godot-proposals#9378]
- *Production edit: Related to https://github.com/godotengine/godot-proposals/issues/9321.*

### Describe the project you are working on

A 2d survivors style game

### Describe the problem or limitation you are having in your project

I use the features _Instantiate Child Scene_, _Find in Files_, _Quick Open Scene..._, and _Quick Open Script_ quite a lot and I like to use add ons like _AsepriteWizard_ in my projects. Here's the problem: When I search for files in my project using these features the windows gets flooded by all the files in the addons folder. This adds a lot of friction to the search.

![image](https://github.com/godotengine/godot-proposals/assets/81755541/ad22d78d-c532-4431-8be9-0d3a476f0220)
![image](https://github.com/godotengine/godot-proposals/assets/81755541/1a0192e9-47b5-4f5d-a5ee-be846a7ec47c)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There should be an option to exlude the addons folder (or any other folder for that matter) from these search operations.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- add an "Exclude from search" button below the "Add to Favorites" button

![image](https://github.com/godotengine/godot-proposals/assets/81755541/e71caf17-5e7c-463a-9a1e-8bd354c99b5b)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature is too complex to be worked around with a few lines of script. 
I also believe this enhancement will be used often since add-ons are very common.

### Is there a reason why this should be core and not an add-on in the asset library?

Instantiating child scenes and searching for files is something one does very frequently.

**Comment by Zireael07** [comment]
Doesn't the .gdignore cover this?

**Comment by nubels** [comment]
> Doesn't the .gdignore cover this?

First time hearing about this. Is it common to add a .gdignore to your add-ons folder? If so I suppose this is what I was looking for...

**Comment by KoBeWi** [comment]
`.gdignore` makes the folder completely invisible in the engine. You can't access it from FileSystem and the resources are not imported (and I think it's auto-excluded from export?). You can still load files inside it, but some addons would break, assuming they'd be even detected.

**Comment by Mickeon** [comment]
I think adding yet another option on the FileSystem's popup menu is a bit much. It's something you tend to toggle once and never again, so I'm not sure the quick access is worth it.

I've been thinking this could be a Project Setting, as unfriendly as the UI may be for it. Something that would also exclude them from the **Quick Open** and **Quick Open Scene** menus.

Perhaps there's a middle-ground here. The list of paths to exclude could be a Project Setting, but also be directly available in the search menus with an easy-to-access button.

**Comment by nubels** [comment]
> I think adding yet another option on the FileSystem's popup menu is a bit much. It's something you tend to toggle once and never again, so I'm not sure the quick access is worth it.
> 
> I've been thinking this could be a Project Setting, as unfriendly as the UI may be for it. Something that would also exclude them from the **Quick Open** and **Quick Open Scene** menus.
> 
> Perhaps there's a middle-ground here. The list of paths to exclude could be a Project Setting, but also be directly available in the search menus with an easy-to-access button.

I agree that this clutters up the popup menu in the FileSystem. I also agree that this is something you don't toggle often. The project settings seem to be a nice place for this setting.


Another thing came to mind:  what if the intended workflow for an add-on in to instantiate one of the scenes it provides? I think this is the case for the generators in the Gaea add-on for example. Perhaps you can specify to include certain subfolder from an excluded parent folder? Not sure about this one.

**Comment by AdriaandeJongh** [comment]
> Perhaps there's a middle-ground here. The list of paths to exclude could be a Project Setting, but also be directly available in the search menus with an easy-to-access button.

This is an excellent idea.

**Comment by nubels** [comment]
![image](https://github.com/user-attachments/assets/236b7a61-bafc-4ccc-8238-b10142e5ac8a)
with the addition of this feature in Godot 4.4 dev 3, I consider my proposal closed. Thanks ❤️
