### ISSUE TITLE
I need godot support to customize Android packaging options like unity.

### ISSUE THREAD

**Issue by androids7** [godotengine/godot-proposals#9382]
### Describe the project you are working on

I'm developing games on the Android platform. I need to call a lot of Android functions to access advertisements and some Android calls, while unity supports calling classes directly.

### Describe the problem or limitation you are having in your project

When I need to package the Android platform on godot, I can (check) customize the AndroidMainfest.xml file (this is very important) and support (optional) packaging java files into the Android platform apk.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

need diy AndroidMaindest.xml and more

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

use android pack window open the AndroidMainfest.xml item

### If this enhancement will not be used often, can it be worked around with a few lines of script?

use more,There is a lot of repetitive work to be done.

### Is there a reason why this should be core and not an add-on in the asset library?

It is necessary to customize more Android packaging support, otherwise, it is necessary to use android studio to build projects and use modifiers to modify the packaged AndroidMainfest.xml file, which is very troublesome and repetitive.

**Comment by androids7** [comment]
Usually every time I pack, godot's AndroidMainfest.xml always overwrites my customized content. This means that my local AndroidMainfest.xml custom content is invalid, because every time I package it, I will output a new AndroidMainfest.xml file.

**Comment by AThousandShips** [comment]
Yes that's by design, see the link, you need to provide the data in the editor instead

**Comment by androids7** [comment]
I mean, I want godot to start my custom Activity (which prompts the user privacy agreement to authorize godot's Activity only after the user authorizes it). Why don't I write the user privacy agreement directly with godot? Because usually godot gets permission privately after starting without the user's permission.

**Comment by AThousandShips** [comment]
Please look at those methods in the link, you need to use a plugin, you can't edit the file directly, is what I'm saying unclear? Is there some translation problems?
