### ISSUE TITLE
Allow extending or implementing custom Texture class

### ISSUE THREAD

**Issue by Hanprogramer** [godotengine/godot-proposals#9385]
### Describe the project you are working on

A game-centric database system for games. An addon for Godot. Useful in many games from RPG to RTS to FPS. 
![image](https://github.com/godotengine/godot-proposals/assets/30620423/33c0bb39-4c69-4688-8f89-69fbf5c30318)

### Describe the problem or limitation you are having in your project

The current limitting factor I have is setting stuffs directly from the editor for my custom editor window. For example setting icon using existing editor icons. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow for extending custom texture implementation or add a builtin "EditorIconTexture" class for easy designing of custom editors. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's how I currently implement it (only concept, doesn't work really.)
```gdscript
class_name EditorIconTexture
extends ImageTexture

@export var icon_name : String:
	set(value):
		icon_name = value
		_update()

@export var icon_texture: Texture2D

func _init():
	_update()

func _update():
	icon_texture = EditorInterface.get_editor_main_screen().get_theme_icon(icon_name, "EditorIcons")
	if icon_texture != null:
		create_from_image(icon_texture.get_image())

```

Inspired from:
https://github.com/Maujoe/godot-custom-gradient-texture
https://github.com/godotengine/godot/issues/42830

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really. Here's why:
1. The custom class isn't registered directly to the texture property menu. Only registered to custom resources menu. So I'd need to create a resource for every icons that I have.
2. Implementing a custom texture implementation would allow many more things like online texture or something like that.

### Is there a reason why this should be core and not an add-on in the asset library?

I tried implementing it myself in my own add-on, but then again, the limitations just makes it impossible to do.

**Comment by AThousandShips** [comment]
Have you tried to extend `Texture2D`? You're mixing an issue report and a plugin in 3.x with your own code that's in 4.x, but in 4.x you can make custom textures and just extend their virtual methods

**Comment by Hanprogramer** [comment]
> Have you tried to extend `Texture2D`? You're mixing an issue report and a plugin in 3.x with your own code that's in 4.x, but in 4.x you can make custom textures and just extend their virtual methods
That's the exact problem. There's no virtual methods for textures. Especially ImageTexture that I'm using right now. 

> So please try doing this with the virtual methods in 4.x, any new features like this is unlikely to be added to 3.x though, if you're trying to look at 3.x
No I'm using 4.x

**Comment by AThousandShips** [comment]
You shouldn't extend `ImageTexture`, extend `Texture2D`, that's the one that has virtual methods, like I said

**Comment by Hanprogramer** [comment]
I see. Let me try that

**Comment by AThousandShips** [comment]
It does show up, I tried it and it worked fine, you are looking at extending a class that isn't designed to be extended, you should either just use normal textures, or extend `Texture2D` or similar and do the drawing yourself, why do you need to extend `ImageTexture`? Why can't you use it as is? You can write a plugin to handle import etc. but otherwise you should just use normal images and textures and handle the loading and manipulation of them in script instead

**Comment by Hanprogramer** [comment]
Sorry for the confusion, english isn't my main language. But basically why I need to extend textures is so that I can just add it to the editor stuffs i made for my own plugin.

I want to add it to here:
![image](https://github.com/godotengine/godot-proposals/assets/30620423/fd52c11c-4165-4974-a6b5-c0908f4ab2d5)

So that I can just click `EditorIconTexture` which has properties for string icon name and it'll grab the editor theme icons directly. Without this, I'd need to write it on `_ready()` to set the icons for everything that I needed. 

The reason I extend `ImageTexture` is that I can just call `create_from_data` from the editor icons. Which is the 2nd best thing if possible. 

And again this has to be like this because I'm writting an editor plugin which adds custom editor to a custom file format as you can see in the first message

**Comment by AThousandShips** [comment]
I don't know what you're doing wrong in this case to prevent it being visible, I tried before and it worked, I think you need to rework what you're trying to do though, and I don't think extending texture is the way to do this

**Comment by dalexeev** [comment]
I haven't tested this in 4.x, but it seems to work well in 3.x, see my addon [godot-test-texture](https://github.com/dalexeev/godot-test-texture).

**Comment by KoBeWi** [comment]
Did you try restarting the editor? Sometimes the new classes aren't picked by the resource list.

**Comment by Hanprogramer** [comment]
Will try again today. Thank you for the example. And yes I did try to restart the editor many many times. The best thing i got was it showing in the create resource menu. Still need it to show on the properties menu

**Comment by Hanprogramer** [comment]
Confirmed working. Thanks for the example. The problem I had was because I have a custom ResourceFormatLoader configured wrongly so that it accepts all file formats even .tscn and .png. 

There's just a little bug, every time I change a string property on it, the caret always goes to the first of the line. This happens if i call `set_image(image)` which I needed to for it to display in the editor.
```gdscript
@tool
class_name EditorIconTexture
extends ImageTexture

@export var icon_name : String:
	set(value):
		icon_name = value
		_update()

@export var icon_set : String = "EditorIcons":
	set(value):
		icon_set = value
		_update()

@export var icon_texture: Texture2D

func _init():
	_update()

func _update():
	if Engine.is_editor_hint():
		icon_texture = EditorInterface.get_editor_main_screen().get_theme_icon(icon_name, icon_set)
	if icon_texture != null:
		set_image(icon_texture.get_image())
```

Other than that it works fine.
![image](https://github.com/godotengine/godot-proposals/assets/30620423/dd12ef97-57a8-4744-ad14-a0c5a06b50c5)


![image](https://github.com/godotengine/godot-proposals/assets/30620423/e51c217d-6c9d-4587-92e5-07b48b640773)

**Comment by KoBeWi** [comment]
`set_image()` calls `notify_property_list_changed()`, which causes the inspector to refresh. You could use a timer to update e.g. 0.5 seconds after change, though it's going to be hacky.

**Comment by dalexeev** [comment]
You can also use `_validate_property()` to replace the text field with a dropdown list of theme item names.

**Comment by Hanprogramer** [comment]
> `set_image()` calls `notify_property_list_changed()`, which causes the inspector to refresh. You could use a timer to update e.g. 0.5 seconds after change, though it's going to be hacky.
> 
> btw your properties should use StringName, because that's what the theme methods expect.
> 
> EDIT: Also with this implementation, your image is going to be embedded in the scene.

Can I possibly prevent `notify_property_list_changed`? I tried the timer. It works well but yes as you said it feels hacky

> You can also use _validate_property() to replace the text field with a dropdown list of theme item names.

will try that

**Comment by KoBeWi** [comment]
Looks like this works:
```GDSript
set_block_signals(true)
set_image(icon_texture.get_image())
set_block_signals(false)
```
It blocks the signal from reaching the inspector, so it doesn't update.
