### ISSUE TITLE
Allow Negative values for Input.ActionPress

### ISSUE THREAD

**Issue by emersonbottero** [godotengine/godot-proposals#9388]
### Describe the project you are working on

Testing Input implementation in a [Demo Project](https://github.com/chickensoft-games/GameDemo). 

### Describe the problem or limitation you are having in your project

I can't test joypad with negative values because the Input.ActionPress only accept positive values.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow Input.ActionPress to receive values from -1 to 1 or make a different method to allow simulating negative values input.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The bellow code would print -0.6 instead of 0

```cs
 Input.ActionPress("camera_up", -0.6f);
 System.Console.WriteLine($"Worked? {Input.GetActionStrength("camera_up")}");
 ```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is impossible to test code with negative values.. 
for now I'm only testing the positive entries.

### Is there a reason why this should be core and not an add-on in the asset library?

the method already exist in the core library.. this is an improvement.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/3070.

It's not possible for an action strength to have a negative value, as a gamepad axis can only go from 0.0 to 1.0. Axes that go both ways are mapped as separate actions (e.g. `move_left` and `move_right`), with each of these actions ranging from 0.0 to 1.0.
