### ISSUE TITLE
Get node or child of type

### ISSUE THREAD

**Issue by saminton** [godotengine/godot-proposals#9407]
### Describe the project you are working on

Project independant

### Describe the problem or limitation you are having in your project

Their doesn't appear to be a neat solution to be able to retrieve a single child node of a specific type (or class).

the `find_children` has a parameter to specify the type but `find_child` does not.

from the current doc:
```
find_child ( String pattern, bool recursive=true, bool owned=true ) const
find_children ( String pattern, String type="", bool recursive=true, bool owned=true ) const
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a type parameter to `find_child` would make it in line with `find_children`. It's rather confusing as to why it is not implemented in both.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An better implementation imo would be to have a `get_node_of_type(type)` and `get_nodes_of_type(type)` or `get_child_of_type(type)` and `get_children_of_type(type)`where type would be the actual `class_name` and not a string.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

#3661 has a workaround posted by @balintbarna in https://github.com/godotengine/godot-proposals/issues/3661#issuecomment-1003397595_

### Is there a reason why this should be core and not an add-on in the asset library?

While the workaround does the job, it's something I feel should be implemented natively.

When working with composition, which as far as I can tell is the preferred workflow for Godot, getting nodes via their type rather than their name seems like a more robust system.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/7498
