### ISSUE TITLE
Add support for parsing YAML files

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot-proposals#941]
**Describe the project you are working on:**
2d space game

**Describe the problem or limitation you are having in your project:**
I have to use csv files for data, which have their own limitations/problems (https://github.com/godotengine/godot/issues/38957, https://github.com/godotengine/godot/issues/31749)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
YAML is a popular data format that has one significant advantage over CSV/JSON - comments! Many of my data points are derived from others and comments would make it much more clear for any prospective contributors.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I imagine similar to how built in JSON parsing works.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Writing a YAML parser, especially one supporting comments (which are the main draw of YAML), is definitely not 'a few lines' 

**Is there a reason why this should be core and not an add-on in the asset library?:**
New developers will not be aware of asset library.

**Comment by fire** [comment]
https://github.com/commonmark/cmark is the standard library for this, it should be possible to include it and read the json as a resource to a dictionary.

**Comment by KoBeWi** [comment]
> New developers will not be aware of asset library.

That doesn't sound like a valid reason. A complete beginner won't need YAML either.

**Comment by Zireael07** [comment]
@KoBeWi But s/he will need JSON? If we have one, we should have the other, too.

**Comment by fire** [comment]
Well Godot has a BBCode parser too, which is the closest thing to this.

**Comment by fire** [comment]
Sorry, I got confused. 

There's several things that can be added.
* markdown as a resource
* json as a resource
* yaml as a resource

Personally, I want to add all of them, but this particular one is yaml.

**Comment by Xrayez** [comment]
It doesn't have to be a resource, but the parser class is enough to achieve this. JSON is quite popular so it has a dedicated parser already. Perhaps there could be a general-purpose parser implementing quite a bunch of those formats.

Not particularly related to the proposal, but the guys at SCons told that it would be possible to extend the serialization formats used by `env.Dump()` (including YAML). I've personally trying to merge this to support JSON: SCons/scons#3672. If you wonder why, this would be mainly useful for #119 (GDNative plugins can be compiled with SCons).

For markdown, there's #139 proposal.

**Comment by Calinou** [comment]
> New developers will not be aware of asset library.

I don't think this reason is sufficient in itself. We could aim to improve the asset library's discoverability instead.

**Comment by bojidar-bg** [comment]
> New developers will not be aware of asset library.

Not to jump on the statement, but new developers often don't know about the documentation either, and use Google / Youtube to find engine-related information. I'm quite sure that if an asset library solution for parsing YAML existed, searching for "Godot YAML" would quickly bring it up.

**Comment by jgillich** [comment]
YAML is by far the most popular markup language with comments support, IMHO that's enough of a justification into core. ConfigFiles are a decent alternative, but they do not integrate with other software.

**Comment by fire** [comment]
I have a branch for this. I don't remember where I posted, so I'll post again.

https://github.com/v-sekai/godot/tree/cmark

**Comment by Calinou** [comment]
> YAML is by far the most popular markup language with comments support, IMHO that's enough of a justification into core. ConfigFiles are a decent alternative, but they do not integrate with other software.

If you only use primitive types and arrays, TOML parsers should be able to read ConfigFiles (and Godot should be able to read TOML files that respect this subset).

**Comment by fire** [comment]
My bad.

We don't need to have second config file type. We have the godot scene / resource files and the config file. It would not be good to also use yaml unless you want to change godot engine to use YAML completely and avoid ConfigFiles. This would be a breaking change that doesn't seem to definitively better than the status quo of JSON / INI / RES.

In terms of implementation you can subclass the JSON class for the YAML and the apis will probably be the same considering that we can convert json to yaml.

**Comment by YuriSizov** [comment]
We've discussed this in a proposal review meeting, and agreed that this is better suited for addons and extensions. We may reconsider in the future, if the need arises for the engine itself to parse YAML files, like we do with some other formats right now, but for now we're rejecting bundled YAML support.

**Comment by Jeyanthinath** [comment]
@YuriSizov for text-based system for games having YAML based support will be awesome.

Of course, people can use JSON instead of YAML, but having a YAML based system it would be less cumbersome and more readable for human eyes.

Any chance to reconsider this proposal as of now?

**Comment by dsnopek** [comment]
This really feels like something that would be ideally addressed via GDExtension.

In fact, Googling turned up an existing YAML extension:

https://github.com/ynot01/godot_rust_yaml

I don't know if it's any good, though

**Comment by Jeyanthinath** [comment]
@dsnopek the library you shown need rust environment for non-window version. 

The other version I see is https://godotengine.org/asset-library/asset/254 which has open ticket for godot 4.0 support.

What I see is YAML specs don't change much (last change was from oct 2021), and also it provides best in class support for c/c++ based libraries. Including them will make developers using gdscript's live so much easier.

**Comment by KoBeWi** [comment]
What's the advantage of YAML over ConfigFile, other than interop with apps outside Godot?

**Comment by Jeyanthinath** [comment]
@KoBeWi one downside I see in gdscript is, it doesn't have a stable support for libraries like YAML (for eg: C#, Python), I won't be complaining about my case if I would be programming in C#. This fits not just for YAML it can be for other libraries like TOML and systems where we don't have stable support other system is providing.

That is where I feel some of these should be a part of Godot as its primary programming language is gdscript. 

--

About the use case, many of the text driven applications / games would be best in created with YAML configuration. YAML seems to have sweetspot in working with beginners than json which became more complex as the file grows bigger.

**Comment by KoBeWi** [comment]
You didn't answer the question.
Check ConfigFile. It's a file format similar to TOML. Much more friendly than JSON and probably better than YAML. It also has support for Godot-specific types like Vector2 etc.

**Comment by jgillich** [comment]
I think interop is a big one, but there is more. Nesting is not supported by ConfigFile (Toml does support it, but the syntax is awkward). Multi-line strings are also not supported by either ConfigFile, rather nice for storing e.g. dialogue. I like Toml too, but Yaml is the most widely used (human-friendly) markup language by far.

**Comment by Calinou** [comment]
> Multi-line strings are also not supported by either ConfigFile

ConfigFile does support multiline strings with the `"""` syntax, or even `"` and putting actual line breaks between the quotes.

**Comment by KoBeWi** [comment]
I created a YAML GDExtension:
https://github.com/KoBeWi/Godot-YAML
Works with Godot 4.4. Currently Windows-only, but I'll try to support other platforms too.

**Comment by ThePhilderbeast** [comment]
> What's the advantage of YAML over ConfigFile, other than interop with non-Godot apps?

Personally that interoperability is a fairly huge advantage and on its own is enough of a reason to have it as core, particularly over a "fairly similar to TOML" format

Realisticly this is a comparison between the currently supported JSON, and YAML. Comments and human readability have YAML winning that battle for a lot of uses cases, and the non-standard nature of the configFile format takes it out of the running.

It is nice to see the community making extensions for this, but the lack of full platform support is a big downside to that approach.

**Comment by KoBeWi** [comment]
For platform support, there is some implementation in GDScript:
https://github.com/lowlevel-1989/YAML.gd

**Comment by ThePhilderbeast** [comment]
> For platform support, there is some implementation in GDScript: https://github.com/lowlevel-1989/YAML.gd

Which on the asset library lists itself as compatible with 4.0, now it should work on anything greater then that, but its not guaranteed, and was only published in the last 2 weeks, not to mention issues that people will encounter if they are using C# rather then GDscript.

The other YAML assets have similar issues, for something as core as a data exchange format this seems like something that should be in core, even if its not a high priority to add.
