### ISSUE TITLE
Allow EditorScript to register into a menu

### ISSUE THREAD

**Issue by ultrasuperpingu** [godotengine/godot-proposals#9410]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

EditorScript are very useful to make some automatic script processing in a project. When you need a one shot processing, open the script and Ctrl+Shift+R it is ok. But I have script I need to launch not that often, but too much so it's annoying to have to open it to launch it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice to be able to register an EditorScript in a menu (the Edit/Tools menu for example) without having to implements an EditorPlugin. In fact, it would be nice to have the ability to create new top level menus.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I propose an annotation like:
```
@menu("MyMenu/MyCommand")
extends EditorScript

func _run() -> void:
	print("Hello World")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I didn't see any way to add command in menu except in the Project/Tools menu with a 'AddTool(Submenu)Item' in an editor plugin, and I think it's not really idea to maintains many commands like this which may be only temporary...

### Is there a reason why this should be core and not an add-on in the asset library?

See previous answer

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/8923.

**Comment by ultrasuperpingu** [comment]
Sorry, I did search for another proposal on this but I missed this one :(.
