### ISSUE TITLE
Add `VectorN.is_parallel(VectorN)` method to check whether a vector is parallel to another

### ISSUE THREAD

**Issue by huwpascoe** [godotengine/godot-proposals#9413]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

Some transform functions produce an error like `the target vector and up vector can't be parallel to each other` and there's no built in method to test for it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A standard way to check if two vectors are parallel.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Functions to check if parallel
Vector2.is_parallel(Vector2) -> bool
Vector3.is_parallel(Vector3) -> bool

### If this enhancement will not be used often, can it be worked around with a few lines of script?

```
# This is what I came up with in a minute, it seems to work but is obviously slow.
func is_parallel(a: Vector3, b: Vector3):
	if a.is_zero_approx() or b.is_zero_approx(): # probably should account for this case
		return false
	return is_zero_approx(abs(a.normalized().dot(b.normalized())) - 1.0)
```

### Is there a reason why this should be core and not an add-on in the asset library?

It compliments the other math functions, it's a basic operation and there's probably an optimized form that can be implemented internally.

**Comment by AThousandShips** [comment]
This is only really relevant for 3D transforms (in the problem issue, namely `looking_at`), where testing for parallel is trivial: `a.cross(b).is_zero_approx()`

**Comment by huwpascoe** [comment]
> you don't mention it for 4D

Actually I didn't know if it was possible or not, I'm not very familiar with 4 dimensional space!

> a.cross(b).is_zero_approx()

That's neat. Also, I assumed that parallel also meant in the opposite direction too, like (1,0,0) would be parallel to (-1,0,0) so that's good to know.

I agree that the solution is simple enough to add it to documentation.

**Comment by AThousandShips** [comment]
> Also, I wrongly assumed that parallel meant in the opposite direction too

It does, well, depends on your assumptions, anti-parallel is a form of parallel, and tested the same way

**Comment by AThousandShips** [comment]
I'll write up a documentation improvement for 2/3D when I find the time, adding some details on what the cross product is to the 3D one and mentioning the use to test parallelism
