### ISSUE TITLE
Support MMO Mouse Logitech G600

### ISSUE THREAD

**Issue by artvel** [godotengine/godot-proposals#9421]
### Describe the project you are working on

I am working on an MMO that should support devices like the Logitech G600.
![71rN4zDIDOL _AC_SX522_](https://github.com/godotengine/godot-proposals/assets/6398539/0ff8f0e6-5185-4d1e-8ecf-09a103685081)

### Describe the problem or limitation you are having in your project

No inputs are being fired on all the extra buttons that a normal mouse doesn't have.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Supporting special devices like G600 enables more possibilities.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Can't be worked around. Either it works or not.

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by AThousandShips** [comment]
Those buttons aren't "real" buttons on a mouse though, the OS API at least for windows only supports 5 buttons, so there's no way to handle this directly, this would require a specific API for this

**Comment by Mickeon** [comment]
There's no way to support these natively. Those buttons are programmable buttons. They are programmed by the user to correspond to specific key presses, hotkeys, shortcuts, etc. That's how the OS interprets them as.

**Comment by AThousandShips** [comment]
Some APIs for these can allow you to create fake buttons, AFAIK, but they require the program to have that specific API installed to handle them

Indeed this should be done as you handle any custom buttons: Mapping them to specific keys

**Comment by artvel** [comment]
@Mickeon and @AThousandShips thanks for your super fast responses.
Don't have any experience on how to handle such devices yet but I will have a closer look at it when I have time.

Right now, I feel like there has to be a generic way to handle them model independent. Otherwise it would be hard anyways as you already mentioned.

**Comment by AThousandShips** [comment]
> I feel like there has to be a generic way to handle them model independent.

What do you base that on? There isn't a native way, so the only way would be a shared library all manufacturers use, which is extremely unlikely

**Comment by artvel** [comment]
Just based on the 16 years experience I have. So yeah, I could be wrong. 

Either someone who already has the needed experience comes along or I will give it a shot at some point.

If you are 100% sure with what you have stated above. 
It means that there is literally no way to deal with this currently, right?
If that is true, then lets decide if it makes sense to keep this issue open or close it right away.

**Comment by AThousandShips** [comment]
I'd suggest that you search for such a system, if it exist it should be easy to find, but you said you had no experience with such, so I'm not sure what experience you have? Do you mean experience that different games support these features?

**Comment by artvel** [comment]
No, I meant experience in programming.

**Comment by bruvzg** [comment]
Only the low level protocols are standard ([USB HID](https://www.usb.org/hid)), you can directly control devices like this using [hidapi library](https://github.com/libsdl-org/SDL/tree/main/src/joystick/hidapi) for example. But the library will handle only detecting device and sending/receiving packets, contents of the packets for extra features is not standard.

Usually the only intended way to use a mouse like this is configuring button actions as a keyboard shortcuts in the Logitech app that is shipped with it (or using a [proprietary API](https://www.logitechg.com/en-us/innovation/developer-lab.html) from the manufacturer to communicate with their app).

**Comment by noorus** [comment]
Logitech at least *used to* call these "G-keys", and while they were/are programmable, a game could also read and override them directly via the old Logitech G-key SDK.

If someone [not me] is interested in looking at this, my old-ass input library had a copy of the SDK here: https://github.com/noorus/nil/tree/12ba815a8687626584913525d489d15325049ebd/external/LogitechGkeySDK_1.02.004

The SDK wasn't portable nor particularly pretty, but what it does under the hood also isn't rocket science; I'm almost certain someone has reversed it and an open implementation exist somewhere

**Comment by AThousandShips** [comment]
> I'm almost certain someone has reversed it and an open implementation exist somewhere

Unfortunately that's a complicated area legally, so based on how niche this is I'd say it's not worth it

**Comment by Calinou** [comment]
Closing, as this can't be implemented natively in Godot in a way that is compatible with devices released *after* a given game is released.

This can already be worked around on the user's end by making the additional mouse buttons emit other keys as macros.

> Usually the only intended way to use a mouse like this is configuring button actions as a keyboard shortcuts in the Logitech app that is shipped with it (or using a [proprietary API](https://www.logitechg.com/en-us/innovation/developer-lab.html) from the manufacturer to communicate with their app).

Note that since Godot supports function keys up to <kbd>F24</kbd> (on Windows) and <kbd>F35</kbd> (on macOS and Linux), you can use these keys in your macros if your macro software lets you emit these inputs. Godot will accept them in key binding configuration. Keyboards only go up to <kbd>F12</kbd> after all :slightly_smiling_face:
