### ISSUE TITLE
Add bicubic interpolation BlendMode to AnimationBlendSpace1D and AnimationBlendSpace2D

### ISSUE THREAD

**Issue by bitegw** [godotengine/godot-proposals#9429]
### Describe the project you are working on

A 3D movement system with procedural animations based on [this GDC talk](https://www.youtube.com/watch?v=LNidsMesxSE). This method relies heavily on interpolating between single keyframe animations, which is what this feature proposal is aimed at improving.

### Describe the problem or limitation you are having in your project

I have been able to recreate nearly all of the features in the presentation, but an important point that the presenter demonstrates is that linear interpolation looks bad on organic creatures as it resembles robotic movement. Bicubic interpolation looks much more natural in comparison, but Godot's AnimationBlendSpace nodes do not offer this method.

The AnimationBlendSpace1D and AnimationBlendSpace2D nodes only offer linear and nearest sampling interpolation of animations. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the bicubic interpolation BlendMode to the existing blend mode options.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/64689590/196f3a09-327b-49d4-aa76-472edb7606f5)
(It would also be nice if this dropdown actually named the different options so we don't have to guess what the difference is...)

You can best see how it would look and the difference from linear interpolation in the linked video at [6:49](https://youtu.be/LNidsMesxSE?t=409).

Another solution could be to offer some way for users to set a custom interpolation function, but I'm not sure how that would work...

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. To be able to use the existing animation tree features, the only option is to use builtin interpolation methods.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about expanding the capabilities of the AnimationBlendSpace nodes with more options that have real applications as nearly all game characters are organic and not robots. It's also a lightweight addition that is in line with existing options.

**Comment by TokageItLab** [comment]
For transitions between poses, Transition and StateMachine have a cross fade curve in 4.0. This is because the start and end points are clear. For GDC videos, this is complemented by the fact that the start and end points of the two poses are clearly known.

However, in BlendSpace, we do not know in advance which points will be blended with which points. So it makes no sense to have this option in BlendSpace.

It is possible for the user to move between arbitrary points by using a tween or other function, which can be solved by the user with a few lines of code.
