### ISSUE TITLE
Allow font outline anti-aliasing to be disabled

### ISSUE THREAD

**Issue by JayStringer** [godotengine/godot-proposals#943]
**Describe the project you are working on:**
Pixel art based platformer

**Describe the problem or limitation you are having in your project:**
It's currently not possible to turn off aliasing for the outline of dynamic fonts, this results fonts looking like this:
![Current implementation](https://user-images.githubusercontent.com/23702578/83171568-39d38900-a10e-11ea-8fec-783ba89bd6cd.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
We already have support for turning off aliasing for the font in general with this UI
![alias_off_example](https://user-images.githubusercontent.com/23702578/83171980-cd0cbe80-a10e-11ea-9a74-94b98d079a94.png)

So I propose a checkbox in the font settings section called "Outline Antialiased" to keep the naming convention, in order to turn off the outline anti-aliasing seen above.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
This would ideally result in the font outline looking more like this:
![ideal](https://user-images.githubusercontent.com/23702578/83172245-355ba000-a10f-11ea-98fe-fd668567830a.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's typical to not use aliasing when working with small pixel art i've noticed, the solution to this problem currently (that i've been using) is to duplicate the font 4 times, and offset each duplicate by 1 pixel in each direction, although I anticipate there are other solutions with shaders for example, this is a bit painful though, as each text field needs to be updated simultaneously, resulting in some pretty ugly code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
We support turning off anti-aliasing for the dynamic font, so it makes sense that a feature like this should be included in the core project.

**Comment by Calinou** [comment]
I don't think this issue is about antialiasing, but rather changing *how* FreeType grows the font outline. I'm not sure if we have control over this.

I think antialiasing is already disabled on both the main font and the outline when.

**Comment by JayStringer** [comment]
Awesome, thanks for looking into this :)
