### ISSUE TITLE
Update Baked normal implementation to support a Synced workflow

### ISSUE THREAD

**Issue by HaueryouGitHub** [godotengine/godot-proposals#9446]
### Describe the project you are working on

Considering moving from Unity and Unreal to Godot. However it doesn't appear the engine has a modern Normal Map synced workflow. 

### Describe the problem or limitation you are having in your project

Right now it appears normal maps are not in sync with the authoring application. Ideally when you do a stressed normal test, the cube should still look flat because the math used to encode the normal map is read and rendered in the same sequence. 

Right now there appears to be no "Correct" way to do this. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Does anyone have insight into generating Synced Normal Maps for GoDot?  A synced workflow is when the authoring application perfectly matches the normal map calculator settings the game engine uses. This is actually deeper then "Is it DirectX normals or OpenGL". My current knowledge is that GoDot is using OpenGL. What Im actually trying to determine is the following

Synced Workflow Expectations from Engine:
-Normal Map Mode: DirectX or OpenGL? OpenGL confirmed
-Normal Map Calculator: Are they using MikkTSpace or their own solution? If its a handroll solution is there a way to swap to MikkTspace? Since its the industry standard and supported by Substance Painter, Designer and other modern texturing applications
Compute Tangent Space Per Fragment: Is this something that is supported?
-Vertex Normals of Mesh: User has the ability to import assets with the same surface normals as the authoring application

Reason this is important: 
-Ease of authoring. By having a industry standard technique authoring assets will be faster and less prone to visual errors
-Great Looking Assets: Models that have 1 smoothing group or stressed vertex normals will always look great regardless of your unwrapping and mesh smoothing
-Faster authoring time: By having synced normals you dont need to worry about edge loops unless its to help sell silhouette changes. 

Continued Learning
-Generating Perfect Normals: https://bgolus.medium.com/generating-perfect-normal-maps-for-unity-f929e673fc57
-MikkTSpace: http://www.mikktspace.com/
-Unity Forum: https://forum.unity.com/threads/normal-maps-correct-geometry-for-acquired-scanned-map-to-read-

Im happy to talk shop on this topic. I have worked with many companies in the past to try and solve similar issues like this and can provide test assets if needed to streamline this process! 

![image](https://github.com/godotengine/godot-proposals/assets/165946640/072d203e-7688-4e56-a212-89672dc6860f)

If this was synced we wouldnt see this distortion, If I invert the G channel it looks like this. So clearly both are wrong regardless of OpenGL or DirectX
![image](https://github.com/godotengine/godot-proposals/assets/165946640/21e9da83-befe-4f5e-9d75-753b4adcd9bb)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The final technique should be able to receive files from Substance Painter and Desginer and render the test asset correctly. Please note I'm not using the terminology looks good. I want to know the math is in sync with the authoring application. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This will be used all the time by users who are baking normal maps. Your assets will look better and require less work overall. 

### Is there a reason why this should be core and not an add-on in the asset library?

ummm I assume it would be core. Its really the foundation to normal map authoring.

**Comment by Calinou** [comment]
Godot already uses mikktspace to generate tangents on import if the source mesh is missing  them. This is controlled by the **Generate Tangents** option in the Import dock. This option has no effect if the source mesh was already exported with tangents from the 3D modeling software.

**Comment by HaueryouGitHub** [comment]
@Calinou Thanks for the direction I will give that a shot and see where it gets me. If it fails, I will upload a test scene, and we can go from there!

GOooooooo Godot!

**Comment by clayjohn** [comment]
I think this should actually be a bug report. It looks the same as https://github.com/godotengine/godot/issues/84145 to me. 

The one thing we don't implement that you mention is computing tangent space per fragment. We always compute the tangent space in the vertex shader and then interpolate. That might explain the artifacts you are seeing (which appear to be the same as in https://github.com/godotengine/godot/issues/84145)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/84145.
