### ISSUE TITLE
Add an overridable method called when a node is added for the fisrt time in the editor

### ISSUE THREAD

**Issue by ultrasuperpingu** [godotengine/godot-proposals#9456]
### Describe the project you are working on

All projects

### Describe the problem or limitation you are having in your project

When you add a component to a scene, there is many use cases where you not to add others components and to do some actions for the setup of this component to be ok. Let's say you have a component implemeting a car for example, you may want to find its wheel in its children and affect the correspondant exported variables (just an example).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allowing to override a method called when the node is first added in the scene would allow to make this setup.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just add a _on_first_added_to_scene()` method or something like that in the node class and call it appropriatly.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure if it is possible to implement this in an addon.

### Is there a reason why this should be core and not an add-on in the asset library?

see above

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/7593

**Comment by ultrasuperpingu** [comment]
I don't really see how #7593 is related. Of course, override default property values if one of the use case but not the only one and not the main one...

**Comment by AThousandShips** [comment]
It's fully covers the title of "do something when first created in the editor", please read the actual proposal not just the title and you'll see

**Comment by ultrasuperpingu** [comment]
Yep, sorry, I did read the main post quickly but obviously, too quickly :(
