### ISSUE TITLE
Update the default Android loading behavior so that the engine also looks for the exported .pck or .zip file in the assets folder

### ISSUE THREAD

**Issue by dariuspranskus** [godotengine/godot-proposals#947]
**Describe the project you are working on:**
Any project which requires export to Android

**Describe the problem or limitation you are having in your project:**
This is related to [#946](https://github.com/godotengine/godot-proposals/issues/946
). Currently export to Android feature puts individual project files into assets folder on exported APK. Some of the files are exported as is in plain text. This allows easy retrieval of assets and other files.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Change the default Android load behavior so that it looks for a pck or zip file for the project assets when the project is executed on a Android device.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
During the load process, while executing the app on android device, the system will look for the .PCK file and loads all resources from it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Every time when the project is executed on Android device.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it is core Android load functionality

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/946, as both proposals must be implemented at the same time to work.
