### ISSUE TITLE
Add the option (and logic) to encrypt the exported .pck or .zip file and decrypt it at runtime to access the data

### ISSUE THREAD

**Issue by dariuspranskus** [godotengine/godot-proposals#948]
**Describe the project you are working on:**
Any project which needs to be exported to Android

**Describe the problem or limitation you are having in your project:**
This is related to [#946 ](https://github.com/godotengine/godot-proposals/issues/946) and [#947](https://github.com/godotengine/godot-proposals/issues/947). Currently export to Android functionality pushes individual project files into assets folder in exported APK. after implementing features #946 and #947, system by default will push the PCK or ZIP file instead. Adding PCK encryption option on top of that will add another level of protection. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Option will allow the exported PCK file to be encrypted and decrypted on the fly during the load process.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Every time when the project is exported to Android

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it is core export functionality

**Comment by dariuspranskus** [comment]
[#38308](https://github.com/godotengine/godot/pull/38308) seems to enable this functionality

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/38308, closing.
