### ISSUE TITLE
Adding, improving and unifying some features in the editor

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot-proposals#9484]
### Describe the project you are working on

any project

### Describe the problem or limitation you are having in your project

Here are some things that can be improved or added
## Attach Script from scene dock does not work properly
according to Godot's document 

> Style guide[¶](https://docs.godotengine.org/en/stable/tutorials/best_practices/project_organization.html#style-guide)
> For consistency across projects, we recommend following these guidelines:
> 
> Use snake_case for folder and file names (with the exception of C# scripts). This sidesteps case sensitivity issues that can crop up after exporting a project on Windows. C# scripts are an exception to this rule, as the convention is to name them after the class name which should be in PascalCase.
> 
> Use PascalCase for node names, as this matches the built-in node casing.

the problem is if I click on the attach the script button
![image](https://github.com/godotengine/godot-proposals/assets/92402263/b30918bd-3f22-4bd9-ac1c-9af896bf67af)
here is the result of the generation name
![image](https://github.com/godotengine/godot-proposals/assets/92402263/fed9151b-1258-4a82-86ec-de097679f6c5)
so why does Godot not follow them self rules

## Scene dock has an Instance scene button but FileSystem's new scene dialog does not have
Scene Dock:
![image](https://github.com/godotengine/godot-proposals/assets/92402263/9e5a46f0-0f70-4834-b314-38b2fde41fee)
FileSystem dialog:
![image](https://github.com/godotengine/godot-proposals/assets/92402263/4cd9dc17-368d-4375-ad28-8e767dcf9390)
Should be:
![image](https://github.com/godotengine/godot-proposals/assets/92402263/8181f087-9607-4aa7-b30f-6eb458c1b1ac)
## Add tool and class name filed in new script dialog
if we want to create the editor script we must add `@tool` and for the class name `class_name` so why don't we have quick access to these options?
![image](https://github.com/godotengine/godot-proposals/assets/92402263/130327a7-3f5f-4229-9217-51c454883469)
also the icon field for `@icon` can be useful
## Add a swap button for vector2 fields in the editor
in all programs with vector2 fields there is one button for swapping 2 values so why don't we have one?
![image](https://github.com/godotengine/godot-proposals/assets/92402263/7f94ab63-6a4b-4d5f-8266-5798cf0b5cca)
so here is in the editor:
![image](https://github.com/godotengine/godot-proposals/assets/92402263/642431f2-692a-411c-8fae-08f81ab19dea)
## The code editor caret position changed when scrolling with the shortcut
https://github.com/godotengine/godot-proposals/assets/92402263/f0c366dd-5dc4-4a92-b638-0b2bd2234cf2
as you can see scrolling with the mouse is fine but when using Ctrl + Arrow Down or Arrow Up change the position of the caret
so it needs to be fix
## The code editor does not scroll when selecting a multi-line with the shortcut
when selecting multi-line with Ctrl + Shift + Arrow down or Arrow Up, scroll does not happen
https://github.com/godotengine/godot-proposals/assets/92402263/feaba761-a973-4fe0-b9b1-fa7ddfcab27a
## insert Enter after folded function unfold function and add a new line
the problem is when I fold a function this means I don't want to see function details and press Enter just make it unfold and add a new line 
The problem (Godot):
https://github.com/godotengine/godot-proposals/assets/92402263/a2a80eb3-9200-4397-a2a8-52b58044e113
The solution (Android Studio):
https://github.com/godotengine/godot-proposals/assets/92402263/fa0f46e9-ce2c-4f1e-84a5-eac090a03ff8
## Enums members do not show up in the match statement
as you can see in the video, can not see the enum member before inserting the `:` character
https://github.com/godotengine/godot-proposals/assets/92402263/53cba24e-6302-493e-b7c9-35ce6a8e28f6

## Attach Script from scene dock does not work properly
just convert the node name (PascalCase) to snake_case
I don't know what's going on in the backend but as a programmer I know is not too hard to implement this
this change makes it faster to create new scripts and no need to overwrite the script name if your node name is correct
## Scene dock has an Instance scene button but FileSystem's new scene dialog does not have
just add an instance button in the dialog to make it easier to create new scenes based on the scene template we have
## Add tool and class name filed in new script dialog
I always use class names and `@tool` keywords for my games, it makes coding 10 times faster and cleaner
but adding `class_name` and `@tool` keywords over and over is boring. just add a field for the class name and a check box for the tool
## Add a swap button for vector2 fields in the editor
sometimes during entering a value into vector2 for example screen size, I enter a value for the vertical screen but I want a horizontal screen and I need to cut one value and paste it with another and write another value with the preview value
but it can be done with one single button click
## The code editor caret position changed when scrolling with the shortcut
During programming, we never use the mouse to scroll and look around, it's time-wasting 
so if this problem is fixed, we don't lose the current line we focus
## The code editor does not scroll when selecting a multi-line with the shortcut
every day I use a multi-line selection technique to speed up coding, but not scrolling makes it hard

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

All information is stated above
If there is any ambiguity or question, I will be happy to answer

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

No

**Comment by KoBeWi** [comment]
The rules say to post one proposal per feature:
> Please open one proposal per feature requested. Do not cram multiple feature requests in a single proposal, as this makes it harder to discuss features individually.

Also the script naming is already fixed in 4.3.

**Comment by DexterFstone** [comment]
> The rules say to post one proposal per feature:
> 
> > Please open one proposal per feature requested. Do not cram multiple feature requests in a single proposal, as this makes it harder to discuss features individually.
> 
> Also the script naming is already fixed in 4.3.

fine I post one by one
