### ISSUE TITLE
Print errors that make more sense

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#9488]
### Describe the project you are working on

NoGame APP

### Describe the problem or limitation you are having in your project

Everty time I start my project, it will report error like this:
![image](https://github.com/godotengine/godot-proposals/assets/35988767/9613373b-ea23-4964-bfc0-ce620db6350c)
It like has 2 error:
1. ~~Some resource need load 'res://.godot/imported/atlastexture.dds-68d580e348c8dc76609729290d138ab5.ctex'.~~
2. There was error image with 0 pixels.

I'm try solve this problems, I deleted `.godot` folder, but it not work.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Look the error log. ~~I can't found which file want load 'res://.godot/imported/atlastexture.dds-68d580e348c8dc76609729290d138ab5.ctex' and~~ I'm also can't found which image file with 0 pixels.
so i always has this error log here when start project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Make error more sense, let me know ~~which file want load 'res://.godot/imported/atlastexture.dds-68d580e348c8dc76609729290d138ab5.ctex' and~~ which image file with 0 pixels so i can check this files.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It should be core

**Comment by AThousandShips** [comment]
Imported resources create their internal versions, so in this case it's referenced via `res://.godot/imported/atlastexture.dds`

**Comment by CsloudX** [comment]
> Imported resources create their internal versions, so in this case it's referenced via `res://.godot/imported/atlastexture.dds`

I'm look the `res://.godot/imported` folder. where was no `tlastexture.dds` and `res://.godot/imported/atlastexture.dds-68d580e348c8dc76609729290d138ab5.ctex` file.

**Comment by AThousandShips** [comment]
The `atlastexture.dds` isn't there, it's in some other folder, my bad mistyped, it should be elsewhere :)

**Comment by CsloudX** [comment]
> The `atlastexture.dds` isn't there, it's in some other folder, my bad mistyped, it should be elsewhere :)
> 
> It might not be known to the editor where it's used though, as the editor might link directly to it, unsure without more details

Thanks, YES. I'm found the `atlastexture.dds` in my project folder.

**Comment by CsloudX** [comment]
Thanks @AThousandShips , I can search `atlastexture.dds` in my project.
So, only the point 2 need solve.

**Comment by AThousandShips** [comment]
That is likely not possible to clearly error, as `Image` isn't guaranteed to know its size, but without more details on what you're doing I can't tell

**Comment by lufog** [comment]
While poking around other people's demos and examples, I myself often encountered warnings/errors like “invalid UID, the path is being used instead” or something wrong with the animation track/mesh/material/etc. (I’m writing from memory). And since in such errors in almost all cases it is not written which file specifically causes it, only the path to the cpp file of the engine. You have to open scenes/scripts at random, trying to find the reason.

**Comment by CsloudX** [comment]
For ** There was error image with 0 pixels.**
I'm try debug with source. and found it because i'm create a error altas.
![image](https://github.com/godotengine/godot-proposals/assets/35988767/9417ca33-481e-48db-9f96-df54477a79c1)
Note the p_metadata, it was error data.
IMO, we can add a error message check the `generated`. if it was null, prints the error and output the `p_item.path`, then,  i can know which file was error.

**Comment by AThousandShips** [comment]
Consolidating in:
* https://github.com/godotengine/godot-proposals/discussions/10190
