### ISSUE TITLE
Bottom Window Stays Open, but is Empty

### ISSUE THREAD

**Issue by RidleyF** [godotengine/godot-proposals#9489]
### Describe the project you are working on

I am working on a top-down 2D game shadow game with an animated HUD.

### Describe the problem or limitation you are having in your project

After using the bottom panel to edit a SpriteFrame, when selecting a new node without a SpriteFrame, the bottom panel used to edit the SpriteFrame stays open, but shows no information.
![Godot 4 2 1 SpriteFrame edit panel stays open](https://github.com/godotengine/godot-proposals/assets/162085450/616bc9d4-2591-4f9e-873e-e6bd51303f36)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When selecting a new node after editing a SpriteFrame, the bottom panel closes. This will allow easier changes to other parts of projects faster.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When selecting a new node without a SpriteFrame after editing a SpriteFrame, the bottom panel shrinks to fit to the bottom.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can probably be solved with a few lines of code, but I haven't seen any fixes yet.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a quick fix that is not worth creating a new add-on for.

**Comment by KoBeWi** [comment]
This is a bug with SpriteFrames editor: https://github.com/godotengine/godot/issues/80756
