### ISSUE TITLE
SoundProbe based reverb/attenuation baking and HRTF audio rendering for XR

### ISSUE THREAD

**Issue by ellenhp** [godotengine/godot-proposals#949]
**Describe the project you are working on:**

I'm working on an audio-driven virtual reality experiece. Details are still TBD but we want to experiment with the way people experience sight and sound and blend the two.

**Describe the problem or limitation you are having in your project:**

Virtual reality in Godot suffers from a lack of positional audio. While the current system is great for most non-XR applications, it's difficult to feel present in a virtual reality experience without top-notch audio.

Also, since there isn't a clear place to put this in the template, I'm motivated enough to spend a few months getting this working myself.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

I would like to implement HRTF-based 3D audio alongside the existing audio system in Godot. I'm open to doing it any way that makes sense, but I'm convinced that this does need to be in-engine for reasons I'll outline below. My preference would be to use existing AudioStreamPlayer3D nodes, but this is definitely flexible. A SpatialAudioPlayer3D node or something could be added alongside the existing one, I just think it's confusing to Godot's users who may or may not understand the difference. I would also like to implement audio reverb/attenuation baking at build-time to make sure reverb feels right in any given scene and that sounds that the player doesn't have line-of-sight to are attenuated correctly.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This is all up for discussion. I'm open to any design that gets me good spatial audio for VR. That said, this is what I envision:

HRTF-based audio will be implemented as a module. I'll most likely want to lift some of the math-heavy code (following license requirements!) from Google's resonance audio, but I plan on leaving all the complicated audio graph stuff behind. In AudioStreamPlayer3D, code will check whether HRTF-based audio is enabled in project settings, confirm the presence of the module, then call it to render the audio in 3d. Once the audio is rendered, it will be added to the appropriate bus as normal.

The sound map baking is a bit more complicated, but I'll do my best to describe what I have in mind. I'd like to create a new node, AudioProbe, or something similar. Many AudioProbes be grouped together into an AudioMap node, which will inherit from Area. When a player enters the area, the reverb and attenuation of the audio they hear becomes governed by that AudioMap. At build time, the audio map baking code will (for each AudioMap):

1) Ray trace sound from each AudioProbe, making note of when rays arrive at other AudioProbes. Rays arriving at a sound probe are used to compute an impulse response. Optionally, a directional impulse response for every face of an axis-aligned cube can be computed instead. This multiplies the size of the baked sound map by 6 but can be useful with HRTF-based audio if developers want the best audio experience possible. This impulse response (or all 6 of them) will be cached for later use during baking.
2) 50 or so randomly sampled impulse responses will be assembled into a matrix, and a singular value decomposition of that matrix will be computed. Eigenvectors will be stored in the baked audio map. (see note, this step has feasibility questions)
3) All impulse repsonses are lossily converted into a linear combination of the stored eigenvectors. Instead of storing an entire impulse response for each AudioProbe-AudioProbe pair, only 50 coefficients need to be stored. This could allow the audio map to store fairly long impulse responses without much additional storage space compared to what's otherwise possible. This lets games create boomy echoes.
4) Store a mapping of (AudioProbe-AudioProbe pair) to eigen-impulse-response coefficients. Any AudioProbe-AudioProbe pairs with a zero or near-zero impulse response can be discarded.

NOTE: The singular value decomposition of a matrix composed of any impulse responses that could each be thousands of samples long is not a trivial operation, so there may be some additional optimizations here. Perhaps the impulse responses are generated at a lower sample rate and then interpolated at runtime? https://eigen.tuxfamily.org/dox/group__DenseDecompositionBenchmark.html

At runtime, a player inside an AudioMap will be snapped to the nearest AudioProbe. Any sound sources heard by the player will also be snapped to their nearest AudioProbes. From this AudioProbe-AudioProbe pair, a lookup into the baked audio map is made. The impulse response specified by the stored coefficients is applied to the audio the player hears. If only one impulse response was stored earlier, it's rendered assuming all of the sound came directly from the direction of the sound source. If multiple impulse responses were stored, each is rendered as if it came from the direction of its face of the cube. Once this is working, it would make a lot of sense to interpolate between nearby AudioProbes, but I don't know of a good algorithm to do that if they're placed at irregular intervals by a user. I'm sure one exists though.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Without access to the AudioServer, there isn't anything a script can do to extend the audio system in this way.

**Is there a reason why this should be core and not an add-on in the asset library?:**

In addition to not being possible currently, I don't think it makes sense from an engineering perspective to give scripts direct, real-time access to the audio server. There would be lots of questions there as to how to quickly marshal the data back and forth between script-world and engine-world.

**Comment by ellenhp** [comment]
Forgot to mention, a SoundMaterial node will have to be added to define the reflection/absorption/scattering values of a material. I'm imagining this node can be added as a child of a mesh so it won't take up space in the inspector on the mesh itself for developers who don't care about soundprobes.

**Comment by Wavesonics** [comment]
I wounder if we could add a system similar to the Physics Materials, where it's a resource that's added as a property on a mesh.

**Comment by ellenhp** [comment]
That gave me an idea. I feel like this is such a huge change for how audio works in godot that it's not likely to happen because it'll disrupt a lot of users. Which leads me to... What if we added the ability to set a directly impulse response to be applied to an AudioSource from a script? Then literally all of this proposal could be implemented with GDNative.

I'll come up with a PR demonstrating this soon :)

**Comment by ellenhp** [comment]
To elaborate, this would allow me to create a node inheriting from Spatial that spawns an AudioStreamPlayer (NOT the 3d kind) as a child at runtime to play the sound it contains. It'll dynamically look for the audio listener viewport every frame and update its own impulse response to apply the HRTF corresponding to the direction that the sound is coming from. Baking reverb could happen in a similar way, because reverb can be represented as just another impulse response.

Supplying the impulse response asynchronously ensures that the real-time audio code doesn't have to cross any scirpt-engine boundaries. It just applies the convolution.

**Comment by ellenhp** [comment]
Nevermind, I think this entire proposal is doable from GDNative with AudioStreamGenerators. It'll be ugly but I think it'll work. Closing, but I may reopen if there are any huge blockers along the way.
