### ISSUE TITLE
Add hotkey(Shortcuts) description to button tooltips. 

### ISSUE THREAD

**Issue by pragmaticsystematic** [godotengine/godot-proposals#95]
Currently there are no hotkey description in the tool tips of buttons:
![Godot_v3 1 1-stable_win64_2019-09-22_12-13-10](https://user-images.githubusercontent.com/55458414/65386472-ca1e2a80-dd44-11e9-9fc9-f207af8c7f8f.png)

It would be great if there were:
![2019-09-22_14-26-09](https://user-images.githubusercontent.com/55458414/65386490-094c7b80-dd45-11e9-972b-f07bf1da0fa2.png)

EDIT:(Answering questions)
**Describe the project you are working on:**
A clone of the dos game [Stone Age](https://www.youtube.com/watch?v=lbUAM20ix8w)

**Describe how this feature / enhancement will help your project:**
It's quite frustrating using the debugger and other features if you forget the hotkeys for some actions. It would be far easier to for the user to see the shortcut for the action in the tooltip of the button instead of searching for it in the keybinding menu.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Screenshot of VS code editor implementing the feature is above.

**Describe implementation detail for your proposal (in code), if possible:**
Well I assume the key bindings are in some sort of data-structure and so are the tool tips strings. 
for example :
Keys:

| Key  | function signal |
| --- | --- |
| F11| debug_step_into |
| F12  | debug_step_over |

Button Tool tips:

| String Tool Tip  | function signal |
| --- | --- |
| "Step Into"| debug_step_into |
| "Step over"  | debug_step_over |

So implementation would be to somehow connect those data structures. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't see how.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This seems like basic functionality that the overwhelming majority of similar software already implements.

**Comment by golddotasksquestions** [comment]
If you want this to be a proposal, you will have to fill out all the questions, though.

**Comment by pragmaticsystematic** [comment]
> If you want this to be a proposal, you will have to fill out all the questions, though.

Done.

**Comment by Fruitdude** [comment]
Would be super helpful!

**Comment by Calinou** [comment]
This is already done for most buttons out there, but not all. Some buttons don't use the shortcut system, so their tooltip needs to be set manually.

**Comment by pragmaticsystematic** [comment]
> This is already done for most buttons in the editor, but not all. Some buttons don't use the shortcut system, so their tooltip needs to be set manually.

Yes I've noticed now that the scene designer has this for it's toolbar:
![Godot_v3 1 1-stable_win64_2019-09-22_19-52-15](https://user-images.githubusercontent.com/55458414/65391490-89d5a100-dd72-11e9-8d15-a25d2177dee4.png)

Though the absence of this feature is sorely missed in the debugger specifically.

**Comment by Calinou** [comment]
I've opened a pull request that fixes this for the debugger buttons: https://github.com/godotengine/godot/pull/32258

There may be other instances of missing shortcut tooltips, please report them if you find any :slightly_smiling_face:

**Comment by KoBeWi** [comment]
I swear I've seen similar issue on main repo somewhere >_>
Can't find it though.

**Comment by vnen** [comment]
I believe this can be closed. godotengine/godot#32258 is merged, so the tooltips in the debugger are already solved. If there are other missing then an issue in the main repo can be opened so they can fixed case by case.
