### ISSUE TITLE
Make Output and Debugger visible when using script editor in distraction-free mode

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot-proposals#951]
**Describe the project you are working on:**
Any coding heavy project.

**Describe the problem or limitation you are having in your project:**
When using the script editor in ~fullscreen~ distraction-free mode (Ctrl+Shift+F11) it is not possible to see the output window or the debugger. It is required to exit fullscreen mode when debugging or when trying to see output logs.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It should be possible to make the debugger and the output window visible while having the code editor in ~fullscreen~ distraction-free mode.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The debug and output panel should be available to be made visible. 
Maybe this could be part of the floating-window-rework reduz is doing / has done.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This must be integrated into the editor.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This must be part of the core because it is directly related to the editor.

**Comment by Calinou** [comment]
Do you mean *distraction-free mode*, rather than fullscreen mode? Enabling fullscreen shouldn't hide anything on its own.

**Comment by BeayemX** [comment]
> distraction-free mode

I do, thanks for the clarification.
