### ISSUE TITLE
Add editor setting to keep bottom panel state on play and stop game

### ISSUE THREAD

**Issue by Hilderin** [godotengine/godot-proposals#9513]
### Describe the project you are working on

A 3D air combat game

### Describe the problem or limitation you are having in your project

I want to keep the current bottom panels as it is when I start and exit my game. 

Each time I start my game from the editor, the Output Panel opens even if the bottom panels are closed. When I'm editing GDScript I like to collapse the bottom panels to have more space, but when I start/close the game and go back to the editor, the Output Panel is now opened.

There is already an option to Open the Output panel instead of the Debugger and an option to close it when exiting the game.
![image](https://github.com/godotengine/godot-proposals/assets/81109165/cee83d8b-84da-41ad-8991-e065bc5786e1)

The problem with the current options is that I cannot just tell the editor to do nothing on start. If I use the option "Always close Output on Stop" I lose the current bottom panel when I exit the game.

My suggest is similar to #8507 but there is often errors thrown by the engine that are not important (especially when working in dev build).

Example of workflow #1:
1. Editing script...
![image](https://github.com/godotengine/godot-proposals/assets/81109165/11deb163-1348-4cce-bf11-a1eaf36d4668)

2. Play... We can see the Output panel in the way...
![image](https://github.com/godotengine/godot-proposals/assets/81109165/c839b222-e27c-4271-b17f-b72b04b9774f)

3. Exit game, when I come back in the Editor... The bottom panel is in the way...
![image](https://github.com/godotengine/godot-proposals/assets/81109165/b159c66e-24c7-4e9a-bd07-eeecf30017e2)

----------
Example of workflow #2:
1. Editing Animation...
![image](https://github.com/godotengine/godot-proposals/assets/81109165/4d06b19f-4770-4e33-974d-00bb0bffe04b)

2. Play... The animation panel is gone...
![image](https://github.com/godotengine/godot-proposals/assets/81109165/c4b97743-95a7-4ca0-b8e4-f98984971d47)

3. Exit game... I must click Animation again to go back editing the animation...
![image](https://github.com/godotengine/godot-proposals/assets/81109165/62792616-d999-40ff-848b-c21eb6e5add8)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The problem is backward compatibility with the current options. Currently, if the "Always Output on Play" option is Off, the debugger opens on start.
I suggest adding the option "Keep current bottom panel on play" with the default value false:
![image](https://github.com/godotengine/godot-proposals/assets/81109165/7881c592-0f9c-4d41-ac5d-f06d67c038f4)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If this new option is On, the editor will not open or collapse bottom panels when starting or stopping a game.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think it's possible.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure it can be done with a plugin because it's builtin in the editor code:
![image](https://github.com/godotengine/godot-proposals/assets/81109165/39336290-6b22-455c-8c0c-2b5bda797cb0)

**Comment by passivestar** [comment]
I like it but imo that entire settings section is starting to look like a riddle that users need so solve, especially if you add a setting that overrides two existing ones, and also the name of the option doesn't reflect that it affects what happens on stop (only the tooltip says it)

What if instead of those 3 settings we do:

`On Play (Open Output/Open Debugger/Do Nothing)`
`On Stop (Close Output/Do Nothing)`

The default behavior is preserved with `On Play (Open Output)` and `On Stop (Do Nothing)`
Your desired behavior is achieved with `On Play (Do Nothing)` and `On Stop (Do Nothing)`

Then we'll close both this proposal and https://github.com/godotengine/godot-proposals/issues/8507, because honestly my main issue was that the debugger is always getting opened no matter what and there's no way to prevent it

**Comment by Hilderin** [comment]
My main concern about what you suggest is breaking the compatibility with the existing options.

I agree the this third option is not ideal and if we were starting from scratch your suggestion would be the best choice.

With this third option, I think it's doing exactly what you want: The debugger is not open on start and it opens we there are errors at runtime. And this third option was super easy to code!

I'm new in Godot, maybe somebody else with more experience then me can confirm that backward compatibility is not that important or maybe there is a way not convert old settings in new ones?

**Comment by Hilderin** [comment]
Thanks for the answer, I'll look into it!
