### ISSUE TITLE
Copy-Paste for more data types

### ISSUE THREAD

**Issue by scrahe** [godotengine/godot-proposals#9515]
### Describe the project you are working on

A game for the Godot Wild Jam

### Describe the problem or limitation you are having in your project

For UI, I need two buttons to be in the same place in 2 different scenes, but there is no way to copy the entire transform settings, or just the size or position.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add buttons to copy/paste other data types such as dictionaries, PackedArrays, or Vectors

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When you click the copy button, it can set a global variable to something, and then set something to that global variable when paste is hit.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Theoretically, an editor plugin could be created, but it would be much more useful to have in the base engine.

### Is there a reason why this should be core and not an add-on in the asset library?

This would be helpful for every project, and setting up an add-on every project might be annoying.

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot-proposals/issues/8574
