### ISSUE TITLE
when godot version support openharmony os export like unity

### ISSUE THREAD

**Issue by yythlj** [godotengine/godot-proposals#9523]
### Describe the project you are working on

support for export on openharmonyos.so the huawei phone can play as well.like the unity do :
https://docs.unity.cn/cn/tuanjiemanual/Manual/openharmony.html

### Describe the problem or limitation you are having in your project

support for export on openharmonyos.so the huawei phone can play as well.like the unity do :
https://docs.unity.cn/cn/tuanjiemanual/Manual/openharmony.html

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

support for export on openharmonyos.so the huawei phone can play as well.like the unity do :
https://docs.unity.cn/cn/tuanjiemanual/Manual/openharmony.html

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

help to export godot game to openharmony app (hap)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by Jesusemora** [comment]
This reads like spam

**Comment by Calinou** [comment]
In the interest of making high-quality proposals, please [read the rules](https://github.com/godotengine/godot-proposals#readme) and fill in the issue template. This proposal will be reopened once this is done :slightly_smiling_face:
