### ISSUE TITLE
Add a undo/redo history log

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#953]
**Describe the project you are working on:** This applies to any game or project

**Describe the problem or limitation you are having in your project:**
I don't know which action I can undo and which action I can't undo. Jumping back and forth in the undo history is anything but transparent or user friendly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A panel with a history log for all undoable steps. Branching undo tree would be amazing, but a linear list would already be a great improvement.
Issue moved here from https://github.com/godotengine/godot/issues/25919

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![undohistory](https://user-images.githubusercontent.com/47016402/83196093-8ed9c400-a13b-11ea-9f36-94cb14108e51.gif)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a core usability feature.

**Comment by FlashDaggerX** [comment]
This is already *sort of* implemented. When you do anything with a scene in the editor, a message is printed to the console, telling you which property you edited.

So rather than calling it an *undo log*, let's call it an **action history**. This already-implemented editor feature can be edited to include the action history on a per-scene basis. Maybe this history can be saved to a dotfile (similar to `.import`) so it persists when you open the editor.

**Comment by golddotasksquestions** [comment]
Hm, the logging may be implemented, but when I hit Ctrl+Z  a couple times, I have no idea "where" I am in the history. Knowing where I am is the main purpose of such a panel or visualization. The added bonus of being able to just click on any undo state (or "action") as shown in the gif above  would be another very desirable UX improvement. 
Currently you are completely blind as to where you are in the history and often just have to guess. So I would not say it's already implemented.

**Comment by bojidar-bg** [comment]
Note that it might actually be possible to get the editor's UndoRedo and display a panel which displays the actions stored in that UndoRedo, all inside a plugin.

I do agree that it might be nicer to have it out of the box, however.

**Comment by me2beats** [comment]
Imo this wouldn't be very useful without implementing this #1630
@bojidar-bg I tried to make it as a gdscript plugin but I didn't find some basic api methods
like #1745 and #1746 Without them it's not possible to make a proper undo history list plugin
