### ISSUE TITLE
Toggleable Fullscreen Button

### ISSUE THREAD

**Issue by oliverastell** [godotengine/godot-proposals#9530]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

There is no default option to toggle fullscreen in the project settings.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A toggle in the window settings (possibly disabled by default) to allow the user to toggle fullscreen with the use of a single button. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If this feature is enabled, the user can toggle the fullscreen mode just by pressing F11 (windows).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes.

### Is there a reason why this should be core and not an add-on in the asset library?

It's for convenience, as toggle fullscreen is a common feature amongst most applications so it makes sense to just have it in the base engine.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1983.
