### ISSUE TITLE
Allow `Resource._init()` to be assumed if not declared

### ISSUE THREAD

**Issue by fauxhaus** [godotengine/godot-proposals#9537]
### Describe the project you are working on

Open-world RPG with multiple dungeons

### Describe the problem or limitation you are having in your project

I have a lot of fun playing with Resources and I enjoy how data-driven they are. I create custom ones frequently to define most (if not all) of my external data for items, cutscenes, camera data, etc -- as someone who prioritizes game system infrastructure, I tend to use custom resources a lot for workflow and flexibility.

When creating new custom resource types, I always get bothered by the current syntax. Here's one of the largest custom resources I have in my game, which defines the 3D positioning of the camera relative to any defined target:

```gdscript
extends Resource
class_name CameraData
## Defines relative positioning about a CameraTarget.

@export_category("Camera Positioning")
## The distance from the camera to the target.
@export_range(5.0, 25.0, 0.01, "or_greater") var distance := 13.0

## The height of the camera from the target.
@export_range(0.0, 15.0, 0.01, "or_greater") var height := 3.75

## The rotation of the camera around the target.
@export_range(0.0, 360.0, 1.0, "or_greater", "or_less") var angle := 0.0

## Camera FOV.
@export_range(5.0, 90.0, 1.0, "or_greater") var fov := 40.0

## Offset for the position we look at.
@export var look_at_offset := Vector3(0, 2, 0)

@export_category("Enter Tween")
## Do we have a tween when we're transitioning into this data?
@export var has_enter_tween := true
@export var enter_duration := 0.75
@export var enter_ease := Tween.EASE_IN_OUT
@export var enter_trans := Tween.TRANS_QUAD

@export_category("Exit Tween")
## Do we have a tween when we're transitioning out of this data?
## This takes priority over the enter of the new data.
@export var has_exit_tween := false
@export var exit_duration := 0.75
@export var exit_ease := Tween.EASE_IN_OUT
@export var exit_trans := Tween.TRANS_QUAD

func _init(p_distance := 13.0, p_height := 3.75, p_angle := 0.0, p_fov := 40.0, p_look_at_offset := Vector3(0, 2, 0),
		p_has_enter_tween := true, p_enter_duration := 0.75, p_enter_ease := Tween.EASE_IN_OUT, p_enter_trans := Tween.TRANS_QUAD,
		p_has_exit_tween := true, p_exit_duration := 0.75, p_exit_ease := Tween.EASE_IN_OUT, p_exit_trans := Tween.TRANS_QUAD) -> void:
	distance = p_distance
	height = p_height
	angle = p_angle
	fov = p_fov
	look_at_offset = p_look_at_offset
	has_enter_tween = p_has_enter_tween
	enter_duration = p_enter_duration
	enter_ease = p_enter_ease
	enter_trans = p_enter_trans
	has_exit_tween = p_has_exit_tween
	exit_duration = p_exit_duration
	exit_ease = p_exit_ease
	exit_trans = p_exit_trans
```

My personal gripe with this layout is that the `_init` function is an excessive, redundant, yet mandatory component for defining this Resource.
1. The boilerplate is overwhelming and redundant. The included `_init` syntax requires defining and declaring each variable twice (four times if including the function arguments).
2. While I have default arguments specified for the exported variables, there must also be default ones set in the `_init` function (affects initializing new Resources, it is recommended by the documentation, and may risk undefined behavior otherwise).
3. If I were to create or remove any more exported variables in this Resource, there is no exception raised for forgetting to include them in the `_init` function. However, the behavior is undefined and unpredictable. I've had issues where I added additional variables in exports but not in `_init`, leading to mysterious desyncs between the Resource's values in the editor and at runtime (which I can't seem to reproduce now).
4. It is inconsistent with how exports work for Nodes. For Resources, `_init` is required for exports to appear in the inspector.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The enhancement I'm requesting is simple: if `_init` is not defined in a resource, allow Godot to make the assumption about the Resource's `_init` function that it is initializing all exports to their default values (if default unspecified, use the default of their Variant, or null).

Since there are often times where we would want to extend the functionality of the initialization of a resource, I would also request two additional features:
1. The ability to override the assumed `_init` function by declaring it manually. This would maintain compatibility with existing custom Resources, and ensure they remain as flexible as they currently are.
2. The implementation of a `_post_init` function on Resources, which is called automatically after `_init`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For example, with the following Resource:
```gdscript
extends Resource
class_name CustomResource

@export var value_a: int
@export var value_b: String = "test"
```

Godot will assume the following `_init` without it being present in the script:
```gdscript
func _init(value_a: int = 0, value_b: String = "test"):
    self.value_a = value_a
    self.value_b = value_b
```

Here's an example of a resource that defines custom `_init` logic, and how it would be reimplemented with `_post_init`:

```gdscript
extends Resource
class_name CardDeck

@export var cards: Array[Card]
var starting_card_count: int

func _init(p_cards: Array[Card] = []):
    cards = p_cards
    starting_card_count = cards.size()
```

With an assumed `_init`, this would be reimplemented as:

```gdscript
extends Resource
class_name CardDeck

@export var cards: Array[Card]
var starting_card_count: int

func _post_init():
    starting_card_count = cards.size()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by following the current redundant design of implementing `Resource._init()`, so technically yes. However, I think that the enhancement would be a significant quality of life for creating custom resources, and would become the standard if implemented.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm unsure if an add-on can provide this functionality.

**Comment by KoBeWi** [comment]
That's the first time I hear `_init()` is required. Where did you get that from?

**Comment by fauxhaus** [comment]
> That's the first time I hear `_init()` is required. Where did you get that from?

I tested it further and I think I may have confused myself based on what appears to be a current issue in 4.3. The documentation link over [creating custom resources](https://docs.godotengine.org/en/latest/tutorials/scripting/resources.html#creating-your-own-resources) does seem to imply that the above syntax for `_init` is required. And testing the following scripts on my build of 4.3dev5 does lead to a runtime error, but seems to be stable in 4.2:
```gdscript
## test_resource.gd
extends Resource
class_name TestResource

@export var value: int

## test_script.gd
extends Node

@export var data: TestResource

func _ready():
	print(data.value)  # `Invalid access to property or key 'value' on a base object of type 'Nil'` in 4.3dev5, but stable in 4.2
```

So with the combination of my initial testing leading to stability errors validating the comments made in the documentation, I made the assumption that `_init` was indeed required, but it may also just be an issue with 4.3 instead.

I suppose I'd like confirmation on the intended behavior of Resources to determine if this is a necessary proposal, or if it should be reported as a 4.3 issue instead.

**Comment by KoBeWi** [comment]
The code you showed will work the same in Godot 4.2 and 4.3. Your error likely comes from the fact that you didn't assign resource to `data`.

The documentation you linked is misleading though. `_init()` arguments can be specified to make creating the Resource from code easier (e.g. `MyResource.new(1, "some_data")`), but as noted in the same page, you will run into problems if you don't provide defaults and try to use the resource in the inspector. That's just bad example; editing in the inspector is the main way of working with custom Resources, so `_init()` is completely unnecessary. And even if you create the resource from code, `_init()` with arguments just leads to boilerplate code in the class, while saving you some lines when creating. The example should likely be updated.

This proposal comes from a misunderstanding. It's only a documentation issue.

**Comment by fauxhaus** [comment]
Yes, after some further experimenting I believe you are correct. My mistake. I may look into creating a documentation issue for this later, since I can't imagine I'm the only one who's made this assumption.
