### ISSUE TITLE
zoom to mouse position in editor

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot-proposals#9546]
### Describe the project you are working on

3d game

### Describe the problem or limitation you are having in your project

its unhandy to navigate without a zoom to mouse position option in the editor

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

way easier to navigate around a 3d scene

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

when using scroll , zoom to mouse location on screen

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

its basicly standard in every 3d app

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/910.
