### ISSUE TITLE
Editor Plugin Register Callback into Trigger Save or Build

### ISSUE THREAD

**Issue by KarryCharon** [godotengine/godot-proposals#9562]
### Describe the project you are working on

-

### Describe the problem or limitation you are having in your project

-

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'm developing a editor plugin, and I need to generate c# code by some .tres files while save (ctrl+s) action is triggered.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When user press Ctrl + S, invoke code gen callback above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving editor plugin.

**Comment by KoBeWi** [comment]
Try EditorPlugin's `_save_external_data()`.

**Comment by KarryCharon** [comment]
> Try EditorPlugin's `_save_external_data()`.

So it's like this! Thank you very much.
