### ISSUE TITLE
Editor plugin default config property

### ISSUE THREAD

**Issue by KarryCharon** [godotengine/godot-proposals#9563]
### Describe the project you are working on

A editor plugin for code generating. It would be great if users could configure their own code generation path. 

### Describe the problem or limitation you are having in your project

Editor plugin have no config property(can be modified in the project addon panel).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add config property panel into addon enabled UI panel.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

-

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by KoBeWi** [comment]
You can register a custom project setting for that.

**Comment by KarryCharon** [comment]
> You can register a custom project setting for that.

Thanks! I made it!
