### ISSUE TITLE
Allow setting "application/run/disable_stdout" at runtime

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#9564]
### Describe the project you are working on

NoGame-APP

### Describe the problem or limitation you are having in your project

I'm create a console server app, and client can connect.
in my project, I have many code for debug use `prints` function.
when i export project, i don't want console print this info, so i set `disable_std_out` in ProjectSettings.
but for some info, like client connect server, client request info etc, i want print this info.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For now, the `application/run/disable_stdout` can't take effect on runtime:
![image](https://github.com/godotengine/godot-proposals/assets/35988767/6e23d9f5-953f-42cf-a82c-6bf0bc37af71)

Maybe can implement a method for this:
```
static func prints_smart(text, always:=false):
	if OS.has_feature("editor") or always:
		prints(text)
```
but there was 2 problems:
1. in my project, there was so much prints codes need update.
2. need to implement much methods like print_debug, printerr etc.
3. some info can't take effect like:
![image](https://github.com/godotengine/godot-proposals/assets/35988767/275f0846-ddee-4b68-ba41-5aabbb0b8f2c)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My code like this:
```
var disable_stdout = false

func _ready():
	if if OS.has_feature("editor"):
		disable_stdout = false
	else:
		disable_stdout = true
	ProjectSettings.set_setting("application/run/disable_stdout",disable_stdout)
	
	prints("App Start")

func print_always(text):
	if disable_stdout:
		ProjectSettings.set_setting("application/run/disable_stdout",false)
		prints(text)
		ProjectSettings.set_setting("application/run/disable_stdout",true)
	else:
		prints(text)
	

func _on_client_connect():
	print_always("client connect")

func _on_client_req_info(info):
	print_always("client req info:%s"%info)
	req_info(info)


func req_info(info):
	prints(info.id)
	prints(info.name)
	prints(info.many_info)


func quit():
	prints("quit")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

    
In the Editor, it should prints:
```
>App Start
>client connect
>client req info: aaa
>info.id = 564564563165
>info.name = "asfafdasdfasf"
>info.many_info = asdfasfasdf
sadfdsaf
saf
as
f
safd
>quit
```
For exported app, it should prints:
```
>App Start
>client connect
>client req info: aaa
```

Other a simple example:
```
func _ready():
	test(true)
	test(false)
	test(true)
	test(false)

func test(disable:bool):
	ProjectSettings.set_setting("application/run/disable_stdout",disable)
	if disable:
		prints("Disable, This line can't print")
	else:
		prints("Enable, This line should print")
```
I wish output was:
```
>Enable, This line should print
>Enable, This line should print
```
### Is there a reason why this should be core and not an add-on in the asset library?

No, it should be core

**Comment by AThousandShips** [comment]
This could be done by adding a companion to [`Engine.print_error_messages`](https://docs.godotengine.org/en/stable/classes/class_engine.html#class-engine-property-print-error-messages)

**Comment by AThousandShips** [comment]
Writing up some code for just that, with a property called `print_to_stdout`, with associated set/get, just like `print_error_messages`, will open a PR if it works out neatly

**Comment by KoBeWi** [comment]
You don't need to change this setting at runtime, you can add a setting override instead, to specify when it should take effect.
![image](https://github.com/godotengine/godot-proposals/assets/2223172/4c24f00c-07e8-4bc0-8d57-e75663c18fb9)
