### ISSUE TITLE
Add a `Array.filter_one` method

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#9565]
### Describe the project you are working on

No-Game-APP

### Describe the problem or limitation you are having in your project

Sometimes i want found one element in array. code like this:
```
func get_element(id):
	for i in elements:
		if i.id==id:
			return i
	return null
```
and I'm notice there was a `Array.filter` method I'm so love, i can use it like this:
```
func get_element(id):
	return elements.filter(func(i):i.id==id).front()
```
but there was performance issues, if the array has much elements can filter, but I'm only need one.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

implement a `Array.filter_one(method:Callable)->Variant` method return only the first one element or null if none.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I can code like this:
```
var n = elements.filter_one(func(i):return i.id==id)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it can be implement in GDS, but i think it be core was a good idea just like `Array.filter` method.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes. but I love it can be core.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/6889

See there for more details, if you think something was missed about this and it's not the same, please comment here and it can be reopened
