### ISSUE TITLE
Add a method for RayCast2D that returns the actual CollisionShape2D or CollisionPolygon2D hit instead of the rigidbody

### ISSUE THREAD

**Issue by kkjkjh** [godotengine/godot-proposals#9566]
### Describe the project you are working on

Im making a sandbox vehicle builder game like droneboi(great game check it out) or bad piggies, where destructable blocks have to be able to connect and disconnect automatically. To do this i have a "Block" scene, a "WeldPrefab" scene and a "object builder".

The block scene is a CollisionShape2d containing a script, a sprite, and raycasts for every side something can connect to.

The WeldPrefab scene is a rigidbody that contains a group of blocks that are connected to each other.

The object builder is a simple node with a script that manages and creates block groups.

### Describe the problem or limitation you are having in your project

This is basic pseudocode on how this is supposed to work:

//attatched to the object builder
```
func Build()
    var blocks = getAllBlocks()
    for block in blocks
        if (block has not been checked yet(prevents loops))
            var weld_group = WeldPrefab.instantiate()
            block.set_parent(weld_group)
            
            var newblocks = block.GetConnectedBlocks()
            for newblock in newblocks
                newblock.set_parent(weld_group)
                newblocks.append_array(newblock.GetConnectedBlocks())
```
                
//attached to all blocks
```
func GetConnectedBlocks()
    var foundBlocks
    for rayCast in APredefinedArrayOfRaycastsAttachedToTheBlock
        if(rayCast.get_collider() != null)
            foundBlocks.append(rayCast.get_collider()) //this is the problematic line as this will return the group the collider is in instead of the collider node
            
    var filteredBlocks
    
    for foundBlock in foundBlocks:
        filter out any blocks that have already been checked and add them to filteredBlocks

    return filteredBlocks
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having colliders be able to be referenced separately is quite neccesary for vehicle building games and the like.

For this sort of game to be possible in godot, one would have to make every block have its own rigidbody and somehow "glue" together connected blocks, which would certainly be more difficult and have worse performance...
...or create their very own raycast system from scratch which i might have to do.

in unity this would have been easy as raycast.get_collider() (pseudocode) actually returns the collider...

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have no clue how the godot collision system works so i dont know if collisions already reference the collider somehow or if even colliders on the same rigidbody get baked into one...

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Colliders on rigidbodies where they are the only collider and be referenced with get_collider().get_child("name") (again, pseudocode)

Having multiple colliders on one rigidbody and having each separately referencable in runtime is basically the only real way for sandbox vehicle builder games to not get too laggy and/or hard to develop.

EDIT: another workaround was suggested by Xireael07: catalouge every instance of CollisionShape, get the shape ID with RayCast.get_collider_shape(), and find the corresponding CollisionShape that way (still, not ideal)

### Is there a reason why this should be core and not an add-on in the asset library?

Depending on how the collision system in godot works, this could either be a simple asset called "Advanced Raycast" or something, or this would need a complete rework of the current collision system.

**Comment by Zireael07** [comment]
You can already access the collision shape instead of the body with like one more line of user code. (I don't have my example in front of me but I know it can be done)

**Comment by kkjkjh** [comment]
> You can already access the collision shape instead of the body with like one more line of user code. (I don't have my example in front of me but I know it can be done)

You are probably referring to RayCast2D.get_collider_shape(). I did try it but it only gives the shape ID of the shape, so unless one catalouges every CollisionShape2D (massive potential for error and kinda backwards) and checks their shape IDs against the one gotten from the raycast its still useless...

it is a valid workaround tho, will mention it

**Comment by Zireael07** [comment]
You can get the Shape2D node based on the shape IIRC. As I said, I don't have my code in front of me but I wanted to get the Shape*D of the collided thing and managed to do it

**Comment by AThousandShips** [comment]
See the [documentation](https://docs.godotengine.org/en/latest/classes/class_raycast3d.html#class-raycast3d-method-get-collider-shape) for instructions how to get this information

**Comment by kkjkjh** [comment]
> See the [documentation](https://docs.godotengine.org/en/latest/classes/class_raycast2d.html#class-raycast2d-method-get-collider-shape) for instructions how to get this information

as if i havent tried it already...

Anyway as stated in the [docs](https://docs.godotengine.org/en/stable/classes/class_raycast2d.html#class-raycast2d-method-get-collider-rid) 
get_collider() returns the object (the rigidbody)
get_collider_rid() returns the RID of the object (again, of the rigidbody)
get_collider_shape returns the ID of the shape (but this requires a list to be useful as stated before)

the problem is that having the [shape](https://docs.godotengine.org/en/stable/classes/class_shape2d.html) is pretty much useless because [resources](https://docs.godotengine.org/en/stable/classes/class_resource.html#class-resource) dont have a method to reference where they have been referenced

**Comment by AThousandShips** [comment]
> but this requires a list to be useful as stated before

How does it do that? Just use the methods for accessing the data, you don't need to track this yourself, just use `shape_owner_get_owner` and you get the `CollisionShape2D`

**Comment by Zireael07** [comment]
Thanks AThousandShips for giving the exact function that I used

**Comment by kkjkjh** [comment]
hmm...
theoretically SomeCollisionObject.shape_owner_get_owner(SomeRayCast.get_collider_shape()) should work except i have no idea how to get a reference to the collisionobject and am still looking for it

**Comment by AThousandShips** [comment]
Check the documentation and you'll get the exact instructions, the collision object is there too

**Comment by AThousandShips** [comment]
Did you read the documentation I linked? It explains exactly how to do this, and I'd say that's enough to do anything you need

A dedicated method would be more complicated and would fail with some cases, in confusing ways (it wouldn't work with a `TileMapLayer` for example)

**Comment by kkjkjh** [comment]
yes i got the workaround working but theres another bug (maybe related?) il fix before updating the request

**Comment by AThousandShips** [comment]
The intended method is to do:
```gdscript
var target = get_collider() # A CollisionObject2D.
var shape_id = get_collider_shape() # The shape index in the collider.
var owner_id = target.shape_find_owner(shape_id) # The owner ID in the collider.
var shape = target.shape_owner_get_owner(owner_id) # Your CollisionShape2D, or CollisionPolygon2D.
```

**Comment by kkjkjh** [comment]
oh... welp
Remember kids, always check the latest docs instead of the stable one

**Comment by AThousandShips** [comment]
Good advice, that's why I linked the latest version above

**Comment by outfrost** [comment]
Is there a reason why there isn't a builtin method to get the colliding `CollisionShape2D` without going through the owner id and shape id?
