### ISSUE TITLE
Expose Audio Encode/Decode methods to GDScript

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot-proposals#958]
**Describe the project you are working on:**
In-game VOIP

**Describe the problem or limitation you are having in your project:**
I was looking how to do VOIP within Godot without any extra libraries, and I got pretty far, I have a prototype working. The problem is, the audio buffer you get out of the `AudioStreamSample` is a Wav. What is needed for this to be a real solution is the ability to encode the buffer before sending it over the wire as even short voice messages can be upwards of 500KB as raw audio.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I don't see a way to access the audio encoders that Godot uses for imports at runtime. So my proposal would be exposing the audio code's compression/decompression methods to the scripting interface. This would allow you to use the existing Mic recording and audio playback mechanisms, but greatly reduce the bandwidth necessary to transmit it all.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`AudioStreamSample` (_is a Wav_) could have methods to convert to `AudioStreamOggVorbis`. And visa versa, OggVorbis to Wav.

For the VOIP example, this would mean you get a `AudioStreamSample` from the `AudioStreamMicrophone`, then you call our new method `var ogg := wav_sample.encode(VORBIS) # or something` and send the encoded bytes `ogg.data` over the wire. On the other side an `AudioStreamOggVorbis` can just directly accept those bytes and be played back.

One last thing to note: I know that OGG is not the most ideal compression for real-time voice. But this adds nothing new to the core engine, so seems like a cheap way of enabling something that's essentially impossible currently.

Ideally, we'd include a compression codec that's more well suited for this specific task, something like libOpus. But that's for another proposal.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It certainly could be an addon. I was already thinking of wrapping libOpus in a gdnative library. But the functionality to encode/decode at least ogg already exist right in the engine! So it seems like a bit of duplication.

**Comment by Calinou** [comment]
I don't think Godot even features an Ogg Vorbis encoder as it is? Either way, Ogg Vorbis is generally not considered suitable to VoIP as compared to Opus or even Speex.

**Comment by Wavesonics** [comment]
Ah I didn't realize it was just the decoder. If it's not essentially free, then yeah the effort would be better spent on something more appropriate to VoIP.

**Comment by Wavesonics** [comment]
@Calinou considering this is based on a false assumption, I'm going to close this issue.
