### ISSUE TITLE
Automatically select an object after it was drag-and-dropped in the 3D view

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot-proposals#9613]
### Describe the project you are working on

Making a 3d level for a Top Down shooter.

### Describe the problem or limitation you are having in your project

When I drag-and-drop an asset from the FileSystem to the 3D View, the newly created object is not selected.

This can be really cumbersome when the object is spawned behind or too close another object.
But even if the object is spawned in a visible spot, I still need to click on it so I can rotate/scale/move it.

Note : other people have found this to be [an issue](https://cookiebadger.itch.io/assetplacer).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Automatically select the latest object created after that the user drag-and-drop an asset in the 3D View.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I am hopeful that there is an easy way to know what object was newly created in the tree (after the drag and drop operation) and set this object as the currently selected object. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used thousands time 🚀 

### Is there a reason why this should be core and not an add-on in the asset library?

it is a core behaviour.

**Comment by AThousandShips** [comment]
This might be undesirable, the new node is parented to the selection, so you'd have to manually change back if you want to drop another child node, this should be a modifier IMO, not by default, so holding down some key makes it select it

**Comment by Nodragem** [comment]
So actually, they are not parented to the current selection ! They are added to the root node. So the feature would not be interfering with that behavior (I just tested in Godot 4.2.2).

**Comment by AThousandShips** [comment]
Nope, I just tested, they are parented to the currently selected node, at least in 4.3, don't have a 4.2 version around right now, but this *would* break behavior in 4.3

**Comment by Calinou** [comment]
For reference, drag-and-drop tree insertion order is determined by the modifiers outlined in https://github.com/godotengine/godot/pull/87623 since 4.3.

**Comment by timothyqiu** [comment]
The dropped object is already selected since 4.3.dev4 :P

**Comment by AThousandShips** [comment]
> The dropped object is already selected since 4.3.dev4

Not in latest on a standard build

**Comment by Nodragem** [comment]
I just downloaded 4.3dev5 and here the behaviours I've got:
- **default:** add new node as child of selected node and **select automatically the new node**;
- **ALT modifier:** add new node as child of root and **select automatically the new node**;
- **SHIFT modifier:** add new node as sibbling of currently selected node  and **select automatically the new node**.

The first (default) behaviour seems a bit counterproductive as mentionned by Calinou and AThousandShips.
The 2 last behaviours are _really useful_ when building a level (that is exactly what I needed).

@AThousandShips are you using a more recent build than dev5?

**Comment by AThousandShips** [comment]
I'm using the latest build, it doesn't select it for me, so unsure what differs there

**Comment by Nodragem** [comment]
Thank you, I wasn't sure what you meant by latest. 

I am a bit confused on what's happening on your working build and what is a bug. The default behaviour I experienced in 4.3dev5 (see my last message) is indeed surprising, I am not sure of its use case. But the SHIFT and ALT modifier behaviours are super useful for level editing; so please keep them 😃 !

People doing level editing will be super happy and be pressing SHIFT all the time 😄 Maybe the cherry on the cake would be to add an option in the Editor Setting so we can configure what is the default/shift/alt behaviours.

**Comment by AThousandShips** [comment]
It appears that this was intentionally introduced in:
* https://github.com/godotengine/godot/pull/84347

So this can be closed as implemented, though I missed this and would have been against it being introduced as it's messy

Closing and would be good to discuss improving this in the future

**Comment by Nodragem** [comment]
> would have been against it being introduced as it's messy

Please try the SHIFT behaviour, it is not messy. IMO, it should be the default behaviour. 
Thank you for investigating. Happy for the issue to be closed and really excited to save on clicks !

**Comment by AThousandShips** [comment]
Having to hold down a button to do what I'd call the default behavior isn't very ergonomic, but fair enough
