### ISSUE TITLE
Godot Icon

### ISSUE THREAD

**Issue by bbacle** [godotengine/godot-proposals#9614]
### Describe the project you are working on

I have created a Godot icon that looks better than the default one. I would like to upload it to you to see what you think.

### Describe the problem or limitation you are having in your project

Godot Icon

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot icon needs updating.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The Godot icon that I have created will better reflect the Godot game engine.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

NO

### Is there a reason why this should be core and not an add-on in the asset library?

Because it is the icon that will be used in the Godot game engine.

**Comment by bbacle** [comment]
![GODOT](https://github.com/godotengine/godot-proposals/assets/5198599/92c2ff4d-9c8c-457a-9132-3729df1a46da)

**Comment by bbacle** [comment]
I have been a Godot user off & on for a few years now, & I have never liked the Godot logo because it looks childish rather than something that a game engine should have.
So I spent 2 days making this icon logo that I believe better suits the Godot engine (I am a graphic designer).
I uploaded it in the hopes that it would inspire others to contribute also.
I am not a coder, but I can do graphics (although with a bit of effort).
So I would appreciate you or someone to at least consider it, rather than dismissing it because "you have more important things to focus on," as you said.

Robert Bacle
________________________________

**Comment by MurderVeggie** [comment]
Closing this now, as you clearly did not ready my message properly.
