### ISSUE TITLE
Add support for exporting projects as live/interactive wallpapers 

### ISSUE THREAD

**Issue by johnnyjmcivorv** [godotengine/godot-proposals#965]
**Describe the project you are working on:**

I am creating a series of interactive desktop wallpapers. They are 2D and employ ragdoll physics.

**Describe the problem or limitation you are having in your project:**

There doesn't seem to be any way to convert the project into a wallpaper. There is a way to do this in Unity, but it doesn't appear to be possible with Godot, as there are no tutorials online.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The feature would allow you to turn your application or project into a live wallpaper.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I do not know anything about programming. Maybe it would be some kind of plugin?

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I do not know. You could possibly make a separate program for it, assuming that it is simple.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It doesn't have to be core, but I think a lot of people would use it as it's an easy way to make downloadable content that you could sell. Making a game takes months; making a wallpaper takes a few hours to a few days.

**Comment by Jummit** [comment]
Rule 2: Use the template to show how Godot is not currently meeting your needs and then explain how your proposal will meet a particular need.

**Comment by Calinou** [comment]
See the old issue for further discussion: https://github.com/godotengine/godot/issues/30453.

**Comment by keenfoong** [comment]
Continuation on the discussion, in the previous thread someone mentioned that someone had already made a live wallpaper  for Godot a while back:
[https://www.facebook.com/groups/godotengine/permalink/740260046110592/](https://www.facebook.com/groups/godotengine/permalink/740260046110592/)

I've reached out to Kwesi the person who made that live wallpaper and he's linked me this repo that he worked on that could output a live wallpaper on android:
[A modification of the Godot engine that builds your game project as an Android 3D wallpaper.
](https://github.com/vision-kwest/godot-mirror)

I'm not sure how to use this though, maybe someone can chip in here?

**Comment by Calinou** [comment]
@keenfoong Look at the branches in this repository. Note that it's very old, so we'd have to take the commits in question and try to integrate it into the latest `master` branch.

**Comment by Wavesonics** [comment]
I'm taking a look at this right now. I'm seeing that currently in master we have `GodotRenderer` which is a `GLSurfaceView.Renderer` which pumps the whole render loop and what not.

But I don't think that will work for a LiveWallpaper.

I think we need to provide a concrete `WallpaperService.Engine` class which will look very similar to `GodotRenderer` internally, but just won't be a `View`.

So this leads me to a few questions:
1. Is this something we'd want as part of Godot's core? Or should this just be an addon?
2. If it's core to Godot, how would we expose it through export options?
2. If it's an Addon, how would that work exactly, since it would be part of the Android custom template?

**Comment by Calinou** [comment]
> 1. Is this something we'd want as part of Godot's core? Or should this just be an addon?

I'm not sure if it's worth implementing this as a core feature. Live wallpapers are generally considered niche, especially on mobile platforms where saving power is key.

> 2. If it's core to Godot, how would we expose it through export options?

It would be exposed as an export option in the Android export preset.

> 3. If it's an Addon, how would that work exactly, since it would be part of the Android custom template?

I don't think you can create an Android plugin for this. However, it could still be done by providing a custom Android source ZIP to be used with the [custom build](https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html system.

**Comment by Wavesonics** [comment]
> I'm not sure if it's worth implementing this as a core feature. Live wallpapers are generally considered niche

Ya that makes sense. Maybe a good route would be providing a project template or something in the asset library.

**Comment by Calinou** [comment]
> I think that means we could maybe close this proposal as wont-fix?

Indeed, third-party efforts can be pursued independently of the proposal system.
