### ISSUE TITLE
Allow class_name to be used within built in scripts.

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#9661]
### Describe the project you are working on

Space game

### Describe the problem or limitation you are having in your project

I would like to build some scenes that self contain their logic but also support type checking

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow support for class_name in built in scripts

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

it would work like it does in scripts saved to a file.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It allows for built in scripts to be type checked.

**Comment by RedMser** [comment]
You already made a proposal for this: #2307

**Comment by dalexeev** [comment]
Closed as per comment above.
