### ISSUE TITLE
Allowing the ability to combine for and match into one line

### ISSUE THREAD

**Issue by L-the-forgettable** [godotengine/godot-proposals#9668]
### Describe the project you are working on

I'm currently working on a websocket server for minecraft bedrock clients to connect to. It'll need to process multiple incoming events, from one or more clients, and respond accordingly.

### Describe the problem or limitation you are having in your project

I need to make a queue system for the server to process events with, and am uncomfortable seeing a large chunk inside my _process(), see image below.
![image](https://github.com/godotengine/godot-proposals/assets/51516412/b28dbce8-6118-4fb7-bc1f-6d8d50d9c3b4)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The ability to combine "for" and "match" into one line for readability. This could be used in place of the normal for-match usage in cases where all you'll be doing is matching, like in the example above.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

"for event in list match item" could be used instead of "for event in list: \\n match item:"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no workaround, just use the original way of doing it with all it's chunky glory

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think it's possible to do this with an add-on..

**Comment by AThousandShips** [comment]
I'd argue this reduces readability by making it harder to tell what the line is doing, making one keyword carry more weight tends to reduce readability IMO

It also makes the compiler and parser more complex, and opening up now areas of error

And it's only a very minor annoyance to have to have one additional line and one level of indentation, so IMO this adds very little and costs much more

**Comment by kleonc** [comment]
> and am uncomfortable seeing a large chunk inside my _process(), see image below.
> ![image](https://private-user-images.githubusercontent.com/51516412/327822230-b28dbce8-6118-4fb7-bc1f-6d8d50d9c3b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTczNjMsIm5iZiI6MTcxNDc1NzA2MywicGF0aCI6Ii81MTUxNjQxMi8zMjc4MjIyMzAtYjI4ZGJjZTgtNjExOC00ZmI3LWJjMWYtNmQ4ZDUwZDljM2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE3MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OWExMDI3OGYwZmRlOWY4YTk2OThlYTZiNmFjYmM1MGMxMGI3ODcxYTg4NmVhNWY3NGQ3NGVhNmQ4ZDM0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fd22FTVNMuUzX09YfRf5SNsFb-X0vkhHAF0hWXgMklQ)

Note that the `if event_queue.size() != 0:` is redundant, you can `for` over an empty `event_queue` just fine (it will result in no iterations). So one indentation level goes away.

**Comment by L-the-forgettable** [comment]
> > and am uncomfortable seeing a large chunk inside my _process(), see image below.
> > ![image](https://private-user-images.githubusercontent.com/51516412/327822230-b28dbce8-6118-4fb7-bc1f-6d8d50d9c3b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTczNjMsIm5iZiI6MTcxNDc1NzA2MywicGF0aCI6Ii81MTUxNjQxMi8zMjc4MjIyMzAtYjI4ZGJjZTgtNjExOC00ZmI3LWJjMWYtNmQ4ZDUwZDljM2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE3MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OWExMDI3OGYwZmRlOWY4YTk2OThlYTZiNmFjYmM1MGMxMGI3ODcxYTg4NmVhNWY3NGQ3NGVhNmQ4ZDM0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fd22FTVNMuUzX09YfRf5SNsFb-X0vkhHAF0hWXgMklQ)
> 
> Note that the `if event_queue.size() != 0:` is redundant, you can `for` over an empty `event_queue` just fine (it will result in no iterations). So one indentation level goes away.

On this specifically, I thought about that afterward and fixed it. Still doesn't make it any less chunky

Regardless, it ultimately isn't too consequential so I'll just put an end to it here.
