### ISSUE TITLE
Allow Mouse-Scroll Zoom-In Zoom-Out in TileSet Area

### ISSUE THREAD

**Issue by vrbandwagon** [godotengine/godot-proposals#968]
**Describe the project you are working on:**
2D platformer.
**Describe the problem or limitation you are having in your project:**
As of now, you need to click on the awkward little + and - buttons repeatedly in order to zoom in and out. This is not consistent with the rest of Godot, including the Texture Region editor, which lets you zoom in and out with the mouse.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
This would make Godot more consistent and less clunky.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
This time, no screenshot, as there is nothing to show.
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No idea how to do that.
**Is there a reason why this should be core and not an add-on in the asset library?:**
This is for Godot's overall improvement and success.

**Comment by Calinou** [comment]
This was implemented for the GridMap editor already: https://github.com/godotengine/godot/pull/33950

This should be relatively easy to port to the TileSet editor.

**Comment by vrbandwagon** [comment]
Thank you for your answer! I hope it will be implemented soon.

**Comment by Calinou** [comment]
Nevermind, I thought you were talking about the TileMap palette. I was looking into implementing it there right now, but you're talking about the TileSet editor which uses the old zooming UI. (The new zooming UI you can see in the 2D editor has yet to be ported to the texture region editors and stuff like that.)
