### ISSUE TITLE
Make signal autogenerated methods contain their type

### ISSUE THREAD

**Issue by Frozenfire92** [godotengine/godot-proposals#9684]
### Describe the project you are working on

A game that uses signals for event communication

### Describe the problem or limitation you are having in your project

When using the editor to auto generate a method from a signal, the parameter types are not included, even though they are shown in the Node dock

![image](https://github.com/godotengine/godot-proposals/assets/5893112/43741cbe-406d-477b-9184-6b5a4709c36d)

![image](https://github.com/godotengine/godot-proposals/assets/5893112/e9580bea-4c4b-4294-af97-fa384182afcd)

![image](https://github.com/godotengine/godot-proposals/assets/5893112/74760774-583c-4031-9ca3-2d012dba0fa5)

While godot is typing optional, I believe it would be helpful as it provides an immediate understanding what the parameter is, as well as a shortcut (ctrl + click) to quickly access the docs for that type

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Update the method auto generation to include the type for parameters

```gdscript
func _on_area_entered(area: Area2D):
	pass # Replace with function body.
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This may not be desired within godot's paradigms of types being optional, but I think it could be presented as an Editor Setting allowing users to opt into this functionality

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Unsure

### Is there a reason why this should be core and not an add-on in the asset library?

This feels like core engine functionality

**Comment by AThousandShips** [comment]
They do if you enable `text_editor/completion/add_type_hints`

**Comment by Frozenfire92** [comment]
That's great, thanks for pointing me in the right direction

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeHJ1ZGF4MDJpcjRlNnlqY2Nkdmp2NzZpb3RzcWMzazd2d2lhYTQ1ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/a93jwI0wkWTQs/giphy.gif)

**Comment by Calinou** [comment]
Note that this setting is enabled by default since 4.3: https://github.com/godotengine/godot/pull/88026

**Comment by Frozenfire92** [comment]
That's great 🙂
