### ISSUE TITLE
Use a colored speaker icon for `AudioStreamPlayer`s

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#9688]
### Describe the project you are working on

prototypes

### Describe the problem or limitation you are having in your project

This is the "formal" proposal version of [a discussion](https://github.com/godotengine/godot-proposals/discussions/9655) that I created a few days ago.

![image](https://github.com/godotengine/godot-proposals/assets/71937306/02c441a8-f2a4-48ec-b8e5-645bcbee4b97)
![image](https://github.com/godotengine/godot-proposals/assets/71937306/fb867238-9589-4cb1-92b9-d7289c532937)
![image](https://github.com/godotengine/godot-proposals/assets/71937306/b30e4ef1-1052-4604-8a46-9ba4e50867ec)

Those 3 icons only differ by a tiny color dot and I find them not symbolic enough to be pleasant to read.
As a bonus, the music notation used in the icon is, well, a *music* notation, not something related to sound in general.

Currently, the icon is made up of 2 parts:
1. the multi-colored note, this gradient having the "sound" meaning,
2. a small colored play icon, colored according to the spatialness of the node.

My point of view is the following:
- the gradient is useless. A good icon would convey the audio part much more naturally than the current design.
- the spatial part is way too small to be useful.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- Use an actual speaker icon instead
- Color it *fully* according to spatiality: either white for `AudioStreamPlayer`, blue for `AudioStreamPlayer2D` or red for `AudioStreamPlayer3D`
- Keep the gradient in `AudioStream`s since there is no common icon for them (some use the note, some don't)

Basically use the same icon as most other software:
blender|ubuntu|unity|godot, in the 3D view
-|-|-|-
![image](https://github.com/godotengine/godot-proposals/assets/71937306/dc2f4ecf-a449-4008-879a-11147c1fc5a2)|![image](https://github.com/godotengine/godot-proposals/assets/71937306/c9047d9b-a052-4c6a-8a00-5a3efd568e48)|![image](https://github.com/godotengine/godot-proposals/assets/71937306/3c2f7ad9-15c9-42ae-ad85-20921a3fae34)|![image](https://github.com/godotengine/godot-proposals/assets/71937306/308de9ab-864b-4bf2-bb86-d12e8508b65c)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/71937306/cc6c7c93-8581-4a86-913a-797f14253f8d)

a good icon would have to be designed by someone competent.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's used in 99% of godot projects.

### Is there a reason why this should be core and not an add-on in the asset library?

it's core already

**Comment by AllergenStudios** [comment]
This is a great idea! I do also find that the differences are hard to spot, and seeing they are 2D and 3D nodes I think they should definitely be designed as one instead.

**Comment by mieldepoche** [comment]
> For the main audio stream player that is not 2d or 3d related, I think it should be done like the world environment

I don't agree, the `Environment` icon is blue and red because it can affect both 2D and 3D visuals (iirc), but the non-positional `AudioStreamPlayer` is not "both 2D and 3D", it's non-dimentional, hence the necessity for the white color imo.

**Comment by RadiantUwU** [comment]
This seems very straight-forward to implement, all we need is... the svgs....

**Comment by mieldepoche** [comment]
[icons.zip](https://github.com/godotengine/godot-proposals/files/15362986/icons.zip)

Here are the icons I used for my screenshot.
They are derived from https://en.wikipedia.org/wiki/File:Speaker_Icon.svg iirc which seem to be cc0, but I don't know if they fit the godot style. The sound lines are a bit thin I think (especially compared to the AudioListener's line thickness), and I don't have the skill needed to improve them.

**Comment by RadiantUwU** [comment]
Just a note, it's gonna go in 4.4 due to 4.3 already being in **feature freeze**
