### ISSUE TITLE
Improve CSG Quality with `elalish/manifold`

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#9711]
### Describe the project you are working on

I am in the process of developing a 3D VR social networking application using the Godot engine and also working on Godot Engine.

### Describe the problem or limitation you are having in your project

The current limitation pertains to Godot's handling of trivial, large and intricate 3D models with CSG which adversely affects the user experience when doing 3d prototyping. CSGMesh corrupts trivially when operating on multiple complex assets.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose integrating the Manifold library into the Godot engine. This feature would enhance the quality and integrity of 3D models processed by the engine, thereby preventing mesh corruption even in large and complex models.

The promise that Manifold makes is as long as all the input meshes are manifold, they will stay manifold through the mesh Boolean operators.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I propose augmenting the CSG module in the Godot Engine with the manifold Boolean operators instead of Godot Engine's own operators. This change would improve the handling of complex geometries and prevent mesh corruption.

Testing many old CSG bug reports to see if they're solvable.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Given the 20-30 issues on GitHub related to CSG quality, it is clear that there is a need to improve this aspect of the Godot Engine.

### Is there a reason why this should be core and not an add-on in the asset library?

Before deciding whether this should be a core feature or an add-on, I would like to poll the community to gauge its importance. If it is deemed critical for improving the quality of 3D models, it should be integrated into the core. Otherwise, it could be developed as an add-on gdextension.

There is a cost to adding the manifold library to Godot Engine, so I want to ask.

We could remove CSG from core and point to this official as an extension too.

**Comment by Zireael07** [comment]
As a heavy user of CSG I am wholeheartedly in support

**Comment by fire** [comment]
See also https://github.com/elalish/manifold/issues/91

**Comment by marcgpuig** [comment]
Having this in core would be great not only for level prototyping, but also for reliability when using CSG in procedural generation.

**Comment by Sievaxx** [comment]
Another option for improving Godot's CSG could be to look into replicating the algorithm outlined in [Chisel for Unity](https://www.youtube.com/watch?v=Iqmg4gblreo), which has it's MIT Licensed [source available](https://github.com/RadicalCSG/Chisel.Prototype). As Chisel is not a library and is written in C#, it's algorithm would have to be reimplemented for godot, but that may be a better idea over adding a new library into core or deprecating/removing the current csg nodes and pointing to a plugin.

**Comment by 31** [comment]
Would it be reasonable to add a Convex Hull CSG node as part of the improvements? Or should I open another proposal? It would be an excellent general purpose node to have, and it seems quite easy to add with `manifold`'s functionality. I gave it a shot and only needed a small tweak to the current PR's `unpack_manifold` function to handle it: https://github.com/31/godot/commit/cb3f20f544a7f8029cded5ae7feca770911c3939.
