### ISSUE TITLE
Allow animation target switching

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot-proposals#973]
**Describe the project you are working on:**
a 3d sokoban like with twisty puzzle mechanics

**Describe the problem or limitation you are having in your project:**
I animated a mesh in blender imported that mesh and its animations, but I don't want those animations attached to the mesh. I want them attached to the kinematic body that mesh is a child of that way the collision box inherits the animation too. However I am struggling to switch the target. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I would like to be able to either right click or double click the target of an animation to pop open the same object selection menu that pops up when you first choose the type of track you want to animate from which you could choose a new target. And perhaps an additional method to do the same in the inspector when selecting the track. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Should be used often enough and you shouldn't have to do this through code. 

**Is there a reason why this should be core and not an add-on in the asset library?:**
because switching targets is probably really common

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2619, which has more details about the feature to implement (animation retargeting).
