### ISSUE TITLE
Temperary shadow settings for button just until 5.0?

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#9745]
### Describe the project you are working on

Space game

### Describe the problem or limitation you are having in your project

I need button shadows really bad but https://github.com/godotengine/godot-proposals/issues/4909 is marked for 5.0

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Can we get a temporary font shadow settings for button until 5.0 rolls around and we get outline and shadows moved to fonts and separate fonts per control state?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would work like label's shadow color and shadow offset x and y in theme and style settings

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be used in very low resolution pixel art games

### Is there a reason why this should be core and not an add-on in the asset library?

Label has it but button's doesn't
most controls can be made out of the 5 basic controls of..
- hbox
- vbox
- panel container
- label
- button

but button doesn't have support for shadows and coding separate label's per button state is kinda hard right now.

**Comment by AThousandShips** [comment]
> I need button shadows really bad but #4909 is marked for 5.0

It isn't and never was marked for 5.0?

**Comment by Calinou** [comment]
We can implement https://github.com/godotengine/godot-proposals/issues/4909 while keeping the existing shadow properties available (but deprecated).

**Comment by Shadowblitz16** [comment]
@Calinou thankyou
