### ISSUE TITLE
Imported scene meshes should be project-wide available.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot-proposals#977]
Working in a testing project.

I import scenes from Blender in glb2 format. I would like to use its meshes in other nodes as well. We can not reparent Mesh Instance nodes created by the importing process.

We should be able to pick meshes inside imported scenes from other Mesh Instance nodes.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

It can not be enabled by a simple script.

This a feature that would make the editor more flexible.

**Comment by Jummit** [comment]
There are import settings for that: https://docs.godotengine.org/en/latest/getting_started/workflow/assets/importing_scenes.html#import-hints

**Comment by Calinou** [comment]
PS: When filling in the [issue template](https://github.com/godotengine/godot-proposals/blob/master/.github/ISSUE_TEMPLATE/feature---enhacement-proposal.md), please don't remove the headers as that makes it more difficult to read.

**Comment by jcarlosrc** [comment]
Yes, I can see there is the option to include meshes. Thanks.
