### ISSUE TITLE
Tilemap editor: Show rectangle size while holding mouse button to draw a rectangle

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-proposals#9790]
### Describe the project you are working on

An adventure game

### Describe the problem or limitation you are having in your project

I am drawing rooms of precise size defined in level design document but I cannot preview the size of the rectangle I'm drawing unless I count tiles one by one with my eyes.

![image](https://github.com/godotengine/godot-proposals/assets/1067772/50cbf76e-125e-402a-9a2c-2fbada85e2f5)

Without grid, it's very hard, but at least it becomes feasible if setting the grid view properly (cell size = tile size and division every 10 tiles). You still need to do the count yourself, which can be more complicated if you don't start the selection at the start of a division.

![image](https://github.com/godotengine/godot-proposals/assets/1067772/df95506f-f393-45ad-a155-a18b6217a8fe)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Show a preview of the rectangle of tiles about to be drawn while holding the mouse primary button, so user can see if they reached the target size

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![Godot proposal - Show tilemap draw rectangle size](https://github.com/godotengine/godot-proposals/assets/1067772/d0071068-1d65-481a-88bd-1736faa8e9fa)

(and possibly add black outline around text to ensure contrast)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can enable the grid with divisions of 10 to at least count tiles manually. But I don't know the editor API enough to write a `@tool` script that could do that (tracking the cursor/draw state seems hard).

### Is there a reason why this should be core and not an add-on in the asset library?

It seems difficult to access native tilemap draw state.

**Comment by KoBeWi** [comment]
This already exists:

https://github.com/godotengine/godot-proposals/assets/2223172/a4e53011-dc33-42b4-90b7-2581515aa5f9

**Comment by KoBeWi** [comment]
Closing per above comment.
