### ISSUE TITLE
Add zoom presets of 110% and 120 or 125% in the script editor

### ISSUE THREAD

**Issue by devmark404** [godotengine/godot-proposals#9794]
### Describe the project you are working on

I make tutorials for godot

### Describe the problem or limitation you are having in your project

When I make tutorials it is common to forget the size of the code text which can make it difficult to read if users see them on small screens.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When many tutorial creators make tutorials, the code is not visible because they forget to change the zoom

Since version 4.3 includes this option, it will be easier for you to configure the size; however, the code zoom has unnecessary sizes like 25% or 200% and 300%

![image](https://github.com/godotengine/godot-proposals/assets/133308557/0c82ff3c-e5b6-4b4c-80a5-9153837c9122)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I suggest adding the zoom of 110% and 120% or 125% so you can better configure the code size in the tutorials

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It is already included in the editor, it would just be removing unnecessary sizes and adding new ones

**Comment by AThousandShips** [comment]
I suspect the zoom levels are picked to make the font render well, I'm not sure if levels like 1.1 would work correctly

**Comment by Calinou** [comment]
<kbd>Ctrl + Mouse wheel</kbd> already allows you to go through finer zoom levels than what's defined in the presets.

**Comment by devmark404** [comment]
> Ctrl + Mouse wheel already allows you to go through finer zoom levels than what's defined in the presets.
> 
> That said, I agree the presets defined here aren't very useful, as 25% is way too small and 200% and more are usually too large.
> 
> I'd change them to the following:
> 
> * 50%
> * 75%
> * 90%
> * 100%
> * 110%
> * 125%
> * 150%
> 
> We can also add a disabled entry at the end that reads "Ctrl + Mouse wheel: Finetune".

If that is what you propose, remove sizes that are too large or small

Using Ctrl + Mouse wheel
Other sizes can be achieved as you can see in the comment, I had not noticed it, thank you
![image](https://github.com/godotengine/godot-proposals/assets/133308557/60280e19-f968-4eed-989d-48cb58bd103b)
