### ISSUE TITLE
Change the default gravity settings of the RigidBody2D Node so its physics feel less floaty out of the box

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-proposals#98]
**Describe the project you are working on:**
2D Action game. Eventually I want to incorporate RigidBodys in my game, so I make a number of test projects.

**Describe how this feature / enhancement will help your project:**
RigidBodies2D gravity never seems to behave realistic out of the box. The reasons why one setting won't be the perfect setting that fits all projects, are obvious. What settings I have to change though and why the current default settings are not correct, is the exact opposite of obvious. But having the default settings come closer to what the majority of users do would already help A LOT in getting off from a much better start.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
My proposals is just to change the default settings.

**Describe implementation detail for your proposal (in code), if possible:**
I assume since in the 2D engine the unit is one pixel not one meter as it is in 3D, those 9.8 refer to 9.8 pixel, not meters. This seems plausible, because if you make your RigidBody2D's CollisionShape exactly 2 pixels high (comparatively to a person of 2 meters height), and zoom waaaay in with your camera onto your "character" so much so those two pixels seem as high as a character on screen normally would, gravity seems very natural.
However most people won't have 2 pixel characters to apply RigidBody2D physics to and a viewport of 11 by 20 pixels. At this resolutions, pretty much any "ball" will be a square. RigidBodies would not make that much sense here anyway:
![11x20](https://user-images.githubusercontent.com/47016402/65426638-e6879900-de10-11e9-9c12-8dd050c4a45f.png)
This brown football is never going to roll.

KidsCanCode RigidBody2D demo runs at 1024 by 600 and has a gravity scale of 20 and it still feels floaty. The more realistic value with a character that size and items that size would probably be around 50.
![default_gravity](https://user-images.githubusercontent.com/47016402/65430739-b0e6ae00-de18-11e9-81a9-68924880b440.gif)
The left ball has a gravity scale of 50, mass 2, and weight 19.6, 
the right ball has the default gravity scale of 1, mass 1, and weight 9.8, 

There are a lot of values to tweak to get RigidBodies to behave like you want them. Let's make new users not also wonder why the 9.8 they associate with gravity ever since school a specific value they don't need, and neither is the neat 1 of gravity scale. (Why would anyone who wants natural gravity think of scaling it?)
The default setting looks correct, it looks as if it needs no changing. When in fact they are only correct in a world with 2 pixel characters.

The 1024 by 600 is the default project resolution, the default Rigidbody2D physics settings should feel realistic with those settings.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Since this is about default values, it would be used every time RigidBody2Ds are used. 

**Is there a reason why this should be core and not an add-on in the asset library?:**
Core, because it's a usability setting of an existing feature.

**Comment by nuke-makes-games** [comment]
This would be a simple change and something certainly more user friendly. Perhaps have default physics settings for 3d projects and default settings for 2d projects. Make the 2d physics settings more earth-like and less floaty.

**Comment by Calinou** [comment]
This will break compatibility in all projects that don't override the default gravity, so this will have to be done for 4.0.

**Comment by golddotasksquestions** [comment]
> Perhaps have default physics settings for 3d projects and default settings for 2d projects.
Both are not necessary since we are talking about RigidBody**2D**, here. 3D has it's own RigidBody node.

**Comment by golddotasksquestions** [comment]
@Calinou 

> This will break compatibility in all projects that don't override the default gravity, so this will have to be done in 4.0.
I'd be fine with that. Better late than never. 4.0 will bring many compatibility changes anyway.

> Maybe something like 35 or 40 would be a better fit?

Anything would be better than 1.

**Comment by Xrayez** [comment]
I confirm this, I always set `physics/2d/gravity` set to ~700.

**Comment by SmartySmart702** [comment]
Since Area2D's can override the gravity for objects inside itself those gravity settings should be change too. Right now the values are clamped to -1024/1024.
But maybe a "World Scale" property in the Project Settings would be better? Something like 256*256px = 1*1m so physics can be constant. For 2D only oc.
