### ISSUE TITLE
Enabling Font outlines when the outline size is 0 should should show a warning indicator

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot-proposals#9819]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

If you turn on font outlines in label nodes it isn't obvious that you also have to set an outline size.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It isn't obvious that the default font outline size is 0 pixels, so enabling font outlines should result in a warning indicator being shown when the font outline is set to 0 pixels in size to tell the user to increase the size.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A warning indicator would appear next to the node.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No workaround possible

### Is there a reason why this should be core and not an add-on in the asset library?

Fonts are core

**Comment by AThousandShips** [comment]
What do you mean "enabling font outlines"? What property are you seeing that enables them? There's just the `outline_size` and `font_outline_color` theme properties, and no "enable outlines" of any kind?

**Comment by balloonpopper** [comment]
Sorry yes, via a theme override. It isn't intuitive that you turn the setting on and nothing changes considering the settings above it (font color and shadow color) make immediate changes to the font (even though I haven't created a theme so shadow size/x offset/y offset haven't been altered from their defaults). 

What you're saying about the theme makes sense, I would request (as someone just trying to follow the intuitive path) that turning it on should also check if both the override and theme have a outline of 0 pixels.
Alternatively, make the default outline size 1 pixel rather than 0?

**Comment by AThousandShips** [comment]
> It isn't intuitive that you turn the setting on and nothing changes considering the settings above it

But you aren't turning any setting on, that's a misunderstanding of what it does, it *overrides* the theme value

> Alternatively, make the default outline size 1 pixel rather than 0?

No, then all text would have an outline always

To me it's obvious that enabling it and it saying that it's set to 0 means it *is* set to 0, not something else, I don't understand where the confusion comes from that setting it to 0 means it should be visible

**Comment by balloonpopper** [comment]
> But you aren't turning any setting on, that's a misunderstanding of what it does, it _overrides_ the theme value
 
> > Alternatively, make the default outline size 1 pixel rather than 0?
> 
> No, then all text would have an outline always

I was thinking that the size would change to 1 automatically when you turn the outline feature on. What's the point of an enabled 0 pixel outline? If it's 0 pixels the behavior is the same as if it was not enabled. Having a minimum value of 1 when enabled would address this. 

> To me it's obvious that enabling it and it saying that it's set to 0 means it _is_ set to 0, not something else, I don't understand where the confusion comes from that setting it to 0 means it should be visible

The whole point is that I didn't know there was a setting and that the setting was set to 0.
It would be more obvious if the size was next to the enabled/disabled setting, but it's hiding under the "Constants" section which isn't intuitive to find - I didn't know it was there and couldn't figure out why it wasn't turning on the outline I requested when enabling the other color settings directly next to this one on resulted in immediate results. 

If I turn on any setting in Godot I expect to see a change as a result of changing that setting. If I don't see the change I expect, then it appears to be a bug. All I'm trying to point out is that as someone who doesn't know much about theming, the current behavior is not intuitive. If there was a warning that said "go set the size to non-zero" it makes the outline feature a lot more user friendly.

**Comment by AThousandShips** [comment]
> What's the point of an enabled 0 pixel outline?

You're still operating with an invalid assumption, you've not activated anything, you've just overridden the property. This is all based on a misunderstanding of what you're doing with the theme overrides. And I don't think adding complex behavior to detect if a theme property is "reasonable" is a good solution to this confusion. Having an override of `0` is 100% valid and shouldn't cause a warning.

Theming *isn't* a basic level feature, especially not per-node overrides, it's a reasonably medium level feature. You're IMO expected to understand the system, and is documented [here](https://docs.godotengine.org/en/stable/tutorials/ui/gui_skinning.html#customizing-a-control) for example, where it says it overrides the value.

So if the issue is "the theme override section is unintuitive for beginners" that's a very different issue, but the original issue is in my opinion not an issue or a feature that's needed, it's clear if someone understands the theme system.

> It would be more obvious if the size was next to the enabled/disabled setting

There *isn't* any enabled/disabled setting though, that's part of the incorrect assumption here.

**Comment by balloonpopper** [comment]
After further reading up and some testing @AThousandShips I agree with your points, thanks for your time to reply. I think themes are unintuitive for new users, and could be a lot more user friendly, but I'll agree that my suggestion isn't the right way to deal with the issue.
