### ISSUE TITLE
Godot should  support ARM64.

### ISSUE THREAD

**Issue by develroo** [godotengine/godot-proposals#9822]
### Describe the project you are working on

Given the growing popularity of ARM based platforms like the Apple Mx series and the recent [Qualcomm's Snapdragon X]( https://www.tomshardware.com/pc-components/cpus/early-snapdragon-x-elite-benchmarks-seemingly-confirm-the-chips-incredible-performance-and-battery-life-potential) Godot really should embrace building on ARM Linux with included scripts

### Describe the problem or limitation you are having in your project

Currently, there are neither pre-built ARM build or directions and scripts to compile it yourself.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Widening platform support means Godot can increase in popularity and be used by more developers. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There already an [unofficial fork](https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi) which does this, it would be good to combine the effort into one official codebase and keep everything updated and patched. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

All depends on how much you want to tweak it. You could write a script to be platform based. so Raspberry Pi M3, generic ARM64 etc.

### Is there a reason why this should be core and not an add-on in the asset library?

Having it as part of the Gotdot core means it can be built from the made engine source, either locally or for automated build systems.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/2408.

For future reference, Windows ARM support is already being looked at, but we can't give an ETA on when binaries will be available.

**Comment by develroo** [comment]
> For future reference, Windows ARM support is already being looked at, but we can't give an ETA on when binaries will be available. Linux ARM support is already available and official binaries are available for 4.2.x and 3.6.beta.

Interesting. I did not see any arm builds in the download list [here](https://godotengine.org/download/linux/)

**Comment by Calinou** [comment]
> Interesting. I did not see any arm builds in the download list [here](https://godotengine.org/download/linux/)

They're not listed on the download page (or download cards on dev release posts), so you need to browse to https://github.com/godotengine/godot-builds/releases.

**Comment by develroo** [comment]
Fairy nuff. Thanks.
