### ISSUE TITLE
Add Capitalization to Enumerations

### ISSUE THREAD

**Issue by scrahe** [godotengine/godot-proposals#9826]
### Describe the project you are working on

A neural networking plugin

### Describe the problem or limitation you are having in your project

I am trying to find a way to correctly capitalize ReLU, but I am using an enumeration, and I don't know how or if it's possible to change what letters are capitalized.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There could be escape characters to capitalize things not at the start of the sentence or to ignore characters as whitespace

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

\s - Ignore whitespace characters (_, ,-, etc.)
\c - Capitalize letter
\l - Don't capitalize letter

Re\cl\cu

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It doesn't get in the way of anything, so there's no point.

**Comment by AThousandShips** [comment]
What do you mean by enumerations? Do you mean the way they are displayed in the editor? Or in C#? Please provide more detail

**Comment by scrahe** [comment]
The way they're displayed in the editor.

**Comment by Calinou** [comment]
The way properties are displayed in the inspector is handled here: https://github.com/godotengine/godot/blob/master/editor/editor_property_name_processor.cpp

The capitalization is currently hardcoded, so scripts or editor plugins can't override it.
