### ISSUE TITLE
Add the option to select tracks to the Animation Player

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-proposals#9830]
### Describe the project you are working on

A game in production

### Describe the problem or limitation you are having in your project

Currently if you want to do an operation to several tracks, such as the "edit -> copy tracks" function. We need to generate a list for you to select from in a pop up window. I've recently been adding another function that is similar (https://github.com/godotengine/godot/pull/92199) and I basically had to copy over the code to create another pop up. It would make more sense that you could select tracks in the Animation Player directly and then do operations on the selected tracks.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest changing the check boxes that are currently "enabling / disbling" tracks to instead be selecting tracks and have a seperate icon for setting whether a track is active. There should also be a top checkbox that selects / deselects all tracks.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is a mockup I made. I used Krita's visibility icon for setting whether a track is active, not sure what the best icon for this would be.

![image](https://github.com/godotengine/godot-proposals/assets/4955051/9810d7c3-5b85-4c29-a314-53dde2c0765d)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be used often.

### Is there a reason why this should be core and not an add-on in the asset library?

This needs to be built in to be useful.

**Comment by mihe** [comment]
I would make one small change (brought over from #10143), which is to add a checkbox to the node rows (and not just the tracks) that would allow you to select every track of that node (and would become enabled if selecting all tracks for that node individually).

**Comment by Arnklit** [comment]
This is already logged in https://github.com/godotengine/godot-proposals/issues/5243 . Consolidating.
