### ISSUE TITLE
Add editor option to suppress specific error messages

### ISSUE THREAD

**Issue by Crusher48** [godotengine/godot-proposals#9834]
### Describe the project you are working on

A C# top-down shooter project.

### Describe the problem or limitation you are having in your project

My project has run into an engine-side issue that causes C++ asserts to fail, raising errors. These errors do not have any impact on the project's execution, but they do clog up my debugging console. Actual errors might not be caught because of these false alarm errors, and instead of being able to simply see whether the debugger tab is showing any errors at all, I have to dig through it to make sure those errors are important errors instead of the known engine issue.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

An editor setting to suppress a specific error would allow me to continue develop and be sure that any errors in the console are relevant to my development and issues that I am able to fix.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A new setting within the editor for "Ignored Console Messages". If the text of an error or console log matches a line within the ignored messages, the error is suppressed and does not appear in the editor. Errors will not be automatically suppressed, but only if the user deliberately acknowledges the issue and decides they do not want to see the messages popping up.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is currently no way to block a specific message in the console, and implementing such a feature would be a much more in-depth effort than a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?

While it is theoretically possible to access the debug console with plugins, it is difficult to do so. While this is a feature that would be used infrequently (ideally not at all), it would be much easier to implement inside the engine core than inside a plugin.

**Comment by RedMser** [comment]
> These errors do not have any impact on the project's execution

Note that this might be different in release builds, it could cause crashes there instead!
It sounds like the error in question should be fixed, either in your code or gracefully handle it on Godot's side. Hiding the problem doesn't sound like the correct approach at all.
Which error are you getting exactly?

**Comment by Calinou** [comment]
You can set `Engine.print_errors_enabled = false` before calling a line of code that causes an unwanted error, then set `Engine.print_errors_enabled = true` back (remember to **always** do that).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/10471, which gives more specific solutions.

**Comment by eliacanavera1111** [comment]
> You can set `Engine.print_errors_enabled = false` before calling a line of code that causes an unwanted error, then set `Engine.print_errors_enabled = true` below (remember to **always** do that).

Ok but what if the error happens continuously? My cmd is a wall of "Zoom level must be different from 0 (can be negative)."
I need the zoom level to be around 0.2, i can't set it differently and why should I? It gives me no problems except this...

**Comment by wyattbiker** [comment]
`Engine.print_errors_enabled ` is not a property in v4.7.1.stable.official [a13da4feb]. Instead use `Engine.print_error_messages` 

Even with that set to false,  it will continue printing error logs when in the editor as per documentation.
**Note: This property does not impact the editor's Errors tab when running a project from the editor.**

Example:

```gdscript
extends Node3D

func is_valid_iso_datetime(time_string: String) -> int:
	var e = Engine.print_error_messages
	Engine.print_error_messages = false
	var result:int=Time.get_unix_time_from_datetime_string(time_string)
	Engine.print_error_messages = e
	return result

func _ready() -> void:
	print(is_valid_iso_datetime("2026-12-32T10:25:00")) # Returns 0 BUT also prints the error if testing in Editor
	print(is_valid_iso_datetime("2026-02-28T15:00:00")) # Returns unixtime
```
