### ISSUE TITLE
 Always Close Debugger on Stop Editor Settings

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot-proposals#9835]
### Describe the project you are working on

I would also like to add "Always Close Debug Window on Stop" to the Editor Settings similar to 
"Always Close Output on Stop" which closes the Bottom Panel. 

![image](https://github.com/godotengine/godot-proposals/assets/930478/5d496d1e-50ff-407e-adf4-aee167f35283)

After Stop the Debugger can still be viewed by clicking on the tab at the bottom panel. 

### Describe the problem or limitation you are having in your project

Convenience in opening the full text editor

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Would extend the text editor window when debugging is stopped.. Similar to the way Output Stop behaves

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See screen shot as to where it would be placed

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't thing so.

### Is there a reason why this should be core and not an add-on in the asset library?

Core

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/9513, which covers the same feature by generalizing it across all panels.
