### ISSUE TITLE
Display viewport in UI with custom resolution and input support

### ISSUE THREAD

**Issue by FrenchKrab** [godotengine/godot-proposals#985]
**Describe the project you are working on:**
A project that needs to display viewports with a custom resolution. These viewports should be able to receive inputs to be used as regular GUI for example.

**Describe the problem or limitation you are having in your project:**
There seems to be no way to display a UI with custom resolution and allowing it to receive user input (hover, click, etc).
ViewportContainer is probably what comes the closest with its "shrink" variable (but it has no way to set the resolution manually). Another thing that comes very close to it is the TextureRect with a ViewportTexture assigned.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A simple solution would be to add a "adapt resolution" variable in ViewportContainer. 
When it's checked on, the ViewportContainer behaves as it currently does.
When it's checked off, the ViewportContainer do not automatically change the Viewport's resolution to match its own size, and just use the one currently set.
The "stretch shrink" variable could also have a special value (0 or -1).

It's also possible to allow the TextureRect to transmit its inputs to the Viewport it's linked to, but I guess that's not its purpose.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![godot windows tools 64_ML80jlcQsd](https://user-images.githubusercontent.com/14005967/83405882-c7b0bc00-a40d-11ea-84d7-6823a94e2645.png)

With this setting, the ViewportContainer would display the viewport as stretched , but wouldn't override its resolution.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
To make this work with a script, you have to replicate the behaviour of a ViewportContainer with a TextureRect.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think being able to control the game's resolution as wanted should be a core feature.

**Additional note**
Honestly I think TextureRect has useful attributes (stretch mode, flip) that are lacking on ViewportContainer and should definitely be added.

**Comment by Calinou** [comment]
Did you take a look at the [3D Viewport scaling demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_scaling)?

**Comment by FrenchKrab** [comment]
Hm I have no memory of this issue and the way it's done in the demo does fit my current needs ... 
I think I can close the issue then, thanks for digging it up !
