### ISSUE TITLE
Change error line indicator position of Static typed for loop

### ISSUE THREAD

**Issue by jupiterbjy** [godotengine/godot-proposals#9869]
### Describe the project you are working on

Working with `Skeleton3D`, fetching meshes from each `BoneAttachement3D` iteratively for arbitrary number of bones.

<br>

---

### Describe the problem or limitation you are having in your project

Assignment error for typed `for` loop marks error indicator at end of loop which could cause confusion.

![image](https://github.com/godotengine/godot-proposals/assets/26041217/614d4bb7-33cd-42e0-80a8-b3f6e1fec417)

MRE: [for_loop_test.zip](https://github.com/user-attachments/files/15524966/for_loop_test.zip)

<br>

For given MRE this is not an issue, but if the last line of the loop was assignment operations of ***Similar Types*** - then error message alone won't be helpful, and user might spend minutes or hours to debug nonexistence bug or file wrong bug report to godot main repo, consuming already busy dev's time further.

<br>

Best example for this is when fixing the breaking changes happened during upgrade of 4.2 to 4.3.

![image](https://github.com/godotengine/godot-proposals/assets/26041217/0ecaeaac-e0ed-4202-8ca7-48e10cc321eb)  
<sup>^ godot 4.3 beta 1 win64</sup>

Godot 4.3 introduced `PhysicsBoneSimulator3D` node, and it's now being *Sliently* added to `Skeleton3D` *Only In Remote*, not in local.

Therefore, if there's pre-4.3 codes that iterate thru bones and fetch meshs from it - it will break the code, and show error on unhelpful position and user will have no idea what happened.

Even more, if the last line of the for-loop is also confusing enough - it won't be easy day for that user finding that until navigating the long trees in remote to find what is going on.

<br>

---

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

advance/move back the error indicator to the line where `for` keyword is.

```gdscript

for element: Type in Iterable:  # <--- Error indicator goes here!
    ...
    pass
```

<br>

---

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

WARNING: I am yet to read src code for this section (literally sleeping 1~2 hr per day rn) - will update accordingly or even open PR if I have time to read.

(If there's internal line position cursor) Advance the cursor forward so it goes back to the start of the loop, or backtrack to the start of the loop on assignment error at `for` loop.

<br>

---

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Workaround shown on #632 like:

https://github.com/godotengine/godot-proposals/issues/632#issuecomment-869000807
> > This will give you the code hinting at least, and it makes sure it's of that type:
> > ```gdscript
> > for button in buttons:
> >     if button is Button:
> >         button.align = ALIGN_CENTER
> > ```
> 
> This fails silently at run-time if the type doesn't match, so beware. A safer alternative for debug builds is:
> 
> ```gdscript
> for button in buttons:
>     assert(button is Button)
>     button.align = ALIGN_CENTER
> ```

Do work and is clear. (indeed `assert()` is absolutely needed)

![image](https://github.com/godotengine/godot-proposals/assets/26041217/60463698-151d-48f7-9c44-ea2f1c5be74a)

But then, whole idea of #632 is lost in vein as we aren't using the static typing. 

<br>

---

### Is there a reason why this should be core and not an add-on in the asset library?

To improve static typing / type hinting further and make GDScript more friendly to newcomers.

**Comment by AThousandShips** [comment]
This is a bug, see:
* https://github.com/godotengine/godot/issues/81046

**Comment by jupiterbjy** [comment]
That looks like parser's eating thru blank lines to find a valid code, then just to reach unintended function definition and throw error there.

However this one's not advancing after executing last line in loop to for loop.

```gdscript
for a in ~~:  # <-- should go this line to continue checking then error
    pass
    pass
    pass  # <-- but errors here?
```

IIRC either python or C++/C line-by-line execution also moves line back to the start of loop, *then fail* upon execution in most IDE I ever used.

![Animation 2](https://github.com/godotengine/godot-proposals/assets/26041217/7993bc3b-0eb5-49e6-be5a-4dc13a0e5a02)

Seems like godot's a bit different if that's the case

**Comment by AThousandShips** [comment]
Regardless if it's the same bug this behavior in the proposal is a bug not a feature, the current behavior isn't intentional I'm quite sure, so it's not an odd quirk of the design but a bug

So I'd suggest making a bug report instead over [here](https://github.com/godotengine/godot/issues) if it's not the same as the bug I linked above

**Comment by jupiterbjy** [comment]
Thought I'd get expelled to GIP that it being intended behavior so I wrote as proposal, in reality it was reverse I guess, welp

Will leave this open just in case, people who know the internals will be able to decide if it's intended or accidental.

**Comment by dalexeev** [comment]
Closed since this is a bug, not a missing feature. Thanks for the contribution nonetheless!
