### ISSUE TITLE
Allow holding down mousewheel to quickly scroll through Documentation 

### ISSUE THREAD

**Issue by SheepCommander** [godotengine/godot-proposals#9879]
### Describe the project you are working on

In any Godot project, I often end up referencing the Documentation from inside the editor.

### Describe the problem or limitation you are having in your project

I want to scroll through longer doc pages faster than grabbing the small scrollbar on the right or spinning my mousewheel rapidly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Ability to hold down mousewheel and move the cursor in the direction you want to scroll, like on web pages.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot-proposals/assets/66646514/bedb2616-2379-4691-8424-3fb9a5df4fa6

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not easily, to my knowledge

### Is there a reason why this should be core and not an add-on in the asset library?

It makes more sense as a basic editor function than an addon

**Comment by AThousandShips** [comment]
This shouldn't be specific to the documentation but `RichTextLabel` in general as that's the UI element that's used to make the documentation work

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1046.
