### ISSUE TITLE
Add a simple way to obtain the complete waveform for a given audio file.

### ISSUE THREAD

**Issue by mk56-spn** [godotengine/godot-proposals#9881]
### Describe the project you are working on

A rhythm game of sorts, where a waveform would be a much welcomed addition for the editor. Although i could see this having wider applications, as in any audio related tooling made in godot could benefit

### Describe the problem or limitation you are having in your project

Browsing google for a reliable method to add a waveform returns results that are usually outdated, impractical, require external tooling ( which often limits you to using c# ) or are otherwise not suitable.

it should be noted that the issue mostly exists for generating static waveforms for the whole song, not live ones for part of the song currently being outputed.

https://godotforums.org/d/21285-how-do-you-get-godot-internal-widgets-in-your-own-game/6 in other cases people seem to have found solutions and then vanishes, as often happens sadly

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

a simple method / property that would return all the data points for each audio channel , making it easy to plug into a line2D or draw with the draw functions or whatever else the user may desire

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

not sure what i could add here that isnt covered above

"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not to my knowledge, not without using custom c++ modules for the engine anyways, which there seems to be a few on github, but all using woefully outdated versions of the engine

### Is there a reason why this should be core and not an add-on in the asset library?

the implementation would be rather minimal  and as such generate little bloat to the engine whilst providing a functionality that might not be very common but has clearly generated enough headaches over the years that a first party implementation would be desirable by my estimate

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/127
* https://github.com/godotengine/godot-proposals/issues/6466

And a few other similar proposals already covering this

**Comment by mk56-spn** [comment]
> Thank you for your proposal, consolidating in:
> 
> * [Expose more audio methods to be able to generate waveform previews #127](https://github.com/godotengine/godot-proposals/issues/127)
> * [Expose AudioStreamPreview to GDscript #6466](https://github.com/godotengine/godot-proposals/issues/6466)
> 
> And a few other similar proposals already covering this

my bad , didnt catch it with my search, shouldve been more thorough!

**Comment by AThousandShips** [comment]
No worries it can be hard to find!
