### ISSUE TITLE
Multiply light energy internally to prevent noise in lightmaps

### ISSUE THREAD

**Issue by sammonius** [godotengine/godot-proposals#9884]
### Describe the project you are working on

A 3D game, set inside a building with lighting that aims to be realistic and somewhat eerie.

### Describe the problem or limitation you are having in your project

Lightmaps are too grainy, especially on the edges.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I found that if I increase the energy on the lights and decrease the "bounce indirect energy" on the LightmapGI, the result is exactly the same except it's much less noisy. Here's a before/after comparison of how this affects some walls (top image: energy= 1, bounce_indirect_energy = 1. bottom image: energy - 100, bounce_indirect_energy = 0.03)

![image](https://github.com/godotengine/godot-proposals/assets/104873652/68bee99d-a93c-4493-ac20-ead63e3ef3c7)

![image](https://github.com/godotengine/godot-proposals/assets/104873652/8a275e84-f725-4197-ac0e-51e29b9334b9)

The desnoiser was turned on for both images, and the LightmapGI quality was set to "high".

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

These parameter changes would be done internally when baking lightmaps, which would significantly reduce noise. (The light energy multiplier should probably be some power of two, since the noise is most likely caused by floating point error, and floating point gets more/less precise every time the number changes by a power of two. Something between 256 and 1024 would probably do the trick)

From messing around with the numbers, I think the general formula to keep brightness the same is this:

    light source energy multiplier = x
    
    LightmapGI bounces = y
    
    bounce_indirect_energy multiplier = y'th root of reciprocal of x (sry i don't know the github math formatting thing)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

core lighting improvement

**Comment by Calinou** [comment]
The thing is that indirect light energy isn't the same as direct energy. These won't appear in the same position and you can't predict in which positions light energy will be able to go. If you have things like a room with a door that's barely open (with the sun shining outside), the room will receive a lot of indirect light but little to no direct light. This kind of situation will always result in visible noise unless you use a *lot* of samples. Here, multipling bounce light energy automatically would just prevent indirect light from entering the room.

**Comment by sammonius** [comment]
The light source was just an OmniLight that I disabled after baking. I think I just need to do more research on how the lighting works. (sorry, this is probably like the fifth proposal I made where I just didn't do proper research)
