### ISSUE TITLE
Add Project Manager option to set default Project Path directory

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot-proposals#9890]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

Every time I create a new project in Project Manager, the folder path is pointing at a folder that doesn't exist on my machine (specifically the OneDrive subfolder):
![image](https://github.com/godotengine/godot-proposals/assets/334808/63197bf9-523e-4609-8a58-476c09b19865)

There is a Settings button but it doesn't offer the option to change the default path:
![image](https://github.com/godotengine/godot-proposals/assets/334808/7e66b057-d447-43d6-86de-4d31a170c9e1)

The setting to do that is actually available only in Godot's 'Editor Settings' popup once you load a project:
![image](https://github.com/godotengine/godot-proposals/assets/334808/f60e33be-7a57-4f68-885f-b13701f5beeb)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow changing the default project path from the Project Manager. It makes sense having this option here.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simply add the setting to the Options window in Project Manager. It can stay as a duplicate option in Editor Settings if you like.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around easily by browsing to a folder that actually exists, creating a project then going to Editor Settings and updating the setting.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a papercut that shouldn't exist. Also addons can't change the project manager as far as I'm aware.

**Comment by Flynsarmy** [comment]
If we're copying/moving this setting to the Project Manager, it might also be worth adding the Autoscan setting while we're in there. If that setting gets changed, perhaps pop up a confirmation box asking if the user would like to rescan when hitting Close? An idea for another proposal perhaps.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/6070
