### ISSUE TITLE
Make adding AnimationMixer libraries more intuitive

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot-proposals#9893]
### Describe the project you are working on

Any involving `AnimationTree`s without an `AnimationPlayer` in 4.3. For example a third person player character that inherits its animations from a bunch of libraries.

### Describe the problem or limitation you are having in your project

Adding libraries to an `AnimationTree`s _libraries_ field inherited from `AnimationMixer` is workable but unintuitive.

Here's the current workflow as I understand it:
1. Expand _Libraries_ field
![image](https://github.com/godotengine/godot-proposals/assets/334808/8195e3e5-4a17-47dc-8d12-47462b5cbde6)

2. Set Key type to `StringName` and Value type to `Object`
![image](https://github.com/godotengine/godot-proposals/assets/334808/9401f147-e208-4715-a993-d640c35bed62)

3. Set your name and drag in your library
![image](https://github.com/godotengine/godot-proposals/assets/334808/1b8b2490-2a1c-4b38-a273-51880b2b2a4a)

4. Click _Add Key/Value Pair_
![image](https://github.com/godotengine/godot-proposals/assets/334808/d8c231b3-8083-45e8-b0ef-093de98f6e8d)

5. From here, the 'Animation' window appears in the bottom tab. You can open that up then use the 'Manage Animations' window to add further anims/lbraries easier:
![image](https://github.com/godotengine/godot-proposals/assets/334808/9a9b04df-c9cf-4302-8f15-52ca877aaedf)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose changing the Libraries Inspector row to simply use the 'Manage Animations' window from the beginning. A GUI is much easier to work with and consistent with AnimationPlayer's workflow.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Ideally we'd get something like this [inspector buttons proposal](https://github.com/godotengine/godot-proposals/issues/2149) implemented (there is a [PR](https://github.com/godotengine/godot/pull/78355) for it already) - then the Libraries row could be changed to a 'Manage Animations' button.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around a couple of ways:
1. Use the cumbersome method mentioned above.
2. Attach an `AnimationPlayer` the way we have in the past and add animations through it.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a usability issue. Using `AnimationTree` without an `AnimationPlayer` is being touted as a benefit of the new `AnimationMixer`  resource however actually using `AnimationTree` in this way as it stands is confusing and error prone due to the number of boilerplate steps.

**Comment by KoBeWi** [comment]
Animation tab is always visible and you can use it with AnimationTree right after creating it.

**Comment by Flynsarmy** [comment]
Ahh that makes things simpler! I didn't notice the new tab as it doesn't pop up when adding an AnimationTree the way it does when adding an AnimationPlayer despite adding libraries probably being the first thing you'd want to do.

**Comment by Flynsarmy** [comment]
Fixed via https://github.com/godotengine/godot/pull/114582
