### ISSUE TITLE
Option to provide Control pivot offset as ratio of size

### ISSUE THREAD

**Issue by Meorge** [godotengine/godot-proposals#9899]
### Describe the project you are working on

A 2D Zelda-esque game. The lively and vibrant user interfaces for Nintendo games have long been an inspiration for me, and I'd like to make my games' UIs as interesting as possible.

### Describe the problem or limitation you are having in your project

For my game, I'd like to have a simple UI scene that consists of a TextureRect that displays a button texture and plays a looping animation to convey the action on the button. This is what I have currently, demonstrating multiple animations:

![CleanShot 2024-06-05 at 19 22 46](https://github.com/godotengine/godot-proposals/assets/9957987/9f4f6c2b-238c-4dbe-b78e-d0ad60aa961b)

Each of these animations requires a different `pivot_offset` value relative to the bounding box of the texture: the "press button" animation needs it at the center, while the "wiggle stick" and "press stick" animations need it at the center-bottom.

This scene should be able to be placed in a variety of different layouts and still animate correctly. However, because `pivot_offset` works in pixels, I believe its value would need to be re-calculated for whatever layout it is placed in.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an option to provide the `pivot_offset` as normalized coordinates relative to the rect's `size` instead of absolute pixel coordinates. This way, for example, I could specify the pivot as the center-bottom of the node by providing the vector (0.5, 1.0) as the pivot offset.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In code, these pairs of statements would be equivalent:
```
# Equivalent, setting the rect offset to the top left
node.pivot_offset = Vector2(0, 0)
node.normalized_pivot_offset = Vector2(0, 0)

# Equivalent, setting the rect offset to the center
node.pivot_offset = node.size / 2
node.normalized_pivot_offset = Vector2(0.5, 0.5)

# Equivalent, setting the rect offset to the bottom right corner
node.pivot_offset = node.size
node.normalized_pivot_offset = Vector2(1, 1)
```

In general, I think the math for this would work out to just be:
```
pivot_offset = normalized_pivot_offset * size
```

In the editor, I'm imagining there could be a checkbox that specifies whether to use pixel-based or normalized coordinates. When the checkbox is ticked, the standard "Pivot Offset" field would become un-editable, and its values would change depending on the "Normalized Pivot Offset" and "Size" values.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As stated above, I think the calculation itself is relatively trivial, but having to include a script with it on every node that I want to exhibit this behavior seems like it would be quite unwieldy. If the node has a main purpose, then in my mind the script attached to it should be dedicated to that purpose.

### Is there a reason why this should be core and not an add-on in the asset library?

Ideally, this would be incorporated into the inspector for the Control node itself, not added on as a separate field, which I think is what would have to happen in an add-on. It would also interact closely with the Control node code and its existing properties.

**Comment by kleonc** [comment]
There's already a PR for something like this: https://github.com/godotengine/godot/pull/70646.
However, in its current state it would result in 2 separate properties:
- already existing `pivot_offset`,
- newly added `pivot_offset_ratio`.

The final pivot would be determined like `size * pivot_offset_ratio + pivot_offset`.
Which is way more flexible, it would allow to set the pivot to be e.g. 5 units above the middle of the bottom edge by setting `pivot_offset = (0, -5)` and `pivot_offset_ratio = (0.5, 1.0)` (would be useful e.g. for setting the pivot at fixed spot on the NinePatchRect's border).

**Comment by Meorge** [comment]
Thanks for pointing this out - I'll keep an eye on that PR, then!
