### ISSUE TITLE
Animation player seek using a key

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot-proposals#9904]
### Describe the project you are working on

A shmup that often use animations.

### Describe the problem or limitation you are having in your project

I'm animating logos at the beginning of the game. All animations are quite simple:

-  Fade in to show the logo
-  Wait a few seconds
-  Fade out to hide it

Nothing complicated. But I would like to add the possibility for the user to skip and directly hide the logo to show the next one instead of waiting. This is possible by using the seek method when the player presses a key to seek to X seconds.

This requires knowing the position in the animation player in seconds. It works, but it is easy to break when you make changes in the animation; the script needs to be in sync too.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Somehow in the animation player, add the possibility to include a key that can be used with a seek method, like `seek_to_key(key_name: StringName)`.

By doing this, the code always stays up to date; there is no need to change the time in it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Go to the animation player, select a point in the timeline, then right-click and add a "Seek Point". It will ask for the name of the key; enter and validate it.

Then in the code, using the animation player node, do the following:

```gdscript
_animation_node.seek_to_key("fade_out")

# Instead of
# _animation_node.seek(3)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be easily worked around using the `seek` method, but the point of the proposal is to "enhance" the `seek` method.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure add-on can add this feature.

**Comment by RedMser** [comment]
Would likely be fixed or easily worked around with https://github.com/godotengine/godot/pull/91765

**Comment by Cronos87** [comment]
That's totally what I meant in this proposal!

By the way, it can be closed as it is a duplicate of https://github.com/godotengine/godot-proposals/issues/8414.

Thank you @RedMser for pointing out this PR!
