### ISSUE TITLE
Editor screenshots are unusable in 4.x because the Editor is not using a single window.

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot-proposals#9907]
### Describe the project you are working on

https://github.com/godotengine/godot/pull/27510 was implemented in 3.2, but for 4.x it has a limited usage, and it also could be done easily with an EditorPlugin in gdscript.

### Describe the problem or limitation you are having in your project

It only saves a screenshot of the main editor viewport, we can't capture any opened menus or other sub windows.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It should be removed due to it's limited usage in 4.x.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by WhalesState** [comment]
how it's gonna be fixed while the shortcut is blocked by any other window?
Implementing it to the `Viewport` class as an Editor only code? it will still be limited because if i want to capture the Editor with a popup menu, it will only save the Popup Menu viewport texture, just tell me how to implement it correctly and i will give it a try, thanks in advance.

**Comment by AThousandShips** [comment]
> how it's gonna be fixed while the shortcut is blocked by any other window?

What shortcut and blocked how? What are you responding to?

**Comment by WhalesState** [comment]
> What shortcut and blocked how? What are you responding to?

open any menu (a top menu or right click menu in scene tree or file system) then press Ctrl+F12 and nothing will happen.

**Comment by AThousandShips** [comment]
Okay that should be in the main post, but what about that can't be solved? That's far from an impossible task to solve

**Comment by WhalesState** [comment]
a way to solve this is to request a screenshot from the OS similar to how `ColorPicker` is picking from screen, another way is to loop over the opened godot sub windows and to layer them correctly over the base main editor viewport texture, or to allow using a single window for the editor (optionally) to make the feauture at least usable for tutorials in 4.x.

**Comment by RedMser** [comment]
Could you enable Single Window Mode (search in Editor Settings) to capture menus, popup dialogs, etc.?

**Comment by AThousandShips** [comment]
It *is* usable, please let's not dismiss the ability to capture the main editor screen as usable, but I think we should mainly discuss the value of the feature and potential general changes rather than technical detail, that's not what a proposal is for

And indeed single window is the best approach, it makes a tutorial screenshot much better as well

**Comment by WhalesState** [comment]
Changed all the 3 settings for 4.3 to make sure i'm a single window for editor and popups, also have tested in 3.2, both can't capture a screenshot if a submenu is opened, which is required for tutorials.

The feauture we are discussing is just:
- get the editor's root texture's and saving it's image, which still could be done in just few lines using an editor plugin.

let's just go back to the main issue which was https://github.com/godotengine/godot/pull/92836, I have been adviced to open this proposal just fixing a simple issue.. should i just edit the tooltip to tell that it's saving to project data folder or we change the path to the edior data folder ?

**Comment by AThousandShips** [comment]
No I asked you to open a proposal to discuss where to put the screenshots and the configuration of it, you must have misread [my message](https://github.com/godotengine/godot/pull/92836#issuecomment-2152254131)

It's not just a simple issue to fix, as I explained there

**Comment by WhalesState** [comment]
It doesn't need a proposal, we can just fix the tooltip to tell that it's saving to the current project data folder same as how it was intended to be from the start (relative to each project), this will not break any compatibility, and could have saved our time 😄.

**Comment by WhalesState** [comment]
If you don't consider this as a limitation or an issue, please reopen.
