### ISSUE TITLE
Button bug issue godot4.3-bata1

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot-proposals#9917]
### Describe the project you are working on

Changing the border width of the button on hover and press in the editor will affect the default border width.

### Describe the problem or limitation you are having in your project

Changing the border width of the button on hover and press in the editor will affect the default border width.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Changing the border width of the button on hover and press in the editor will affect the default border width.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Changing the border width of the button on hover and press in the editor will affect the default border width.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Changing the border width of the button on hover and press in the editor will affect the default border width.

### Is there a reason why this should be core and not an add-on in the asset library?

Changing the border width of the button on hover and press in the editor will affect the default border width.

**Comment by AThousandShips** [comment]
This is not the place to report bugs, report bugs [here](https://github.com/godotengine/godot/issues) and please fill in every detail there

**Comment by Calinou** [comment]
Issue opened: https://github.com/godotengine/godot/issues/92890
