### ISSUE TITLE
Go back to project list without closing the current project

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#992]
**Describe the project you are working on:**

**Describe the problem or limitation you are having in your project:**
It's annoying that I must close a project to be able to open (an)other project(s).
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If I want to look for something, I have already done in another project and I want to "copy" it to the current project, I have to go back to the project list and then open both projects instead of just opening the other project without closing the current one. Another possibility is to open again Godot itself.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
not at all
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, everybody could have use of this.

**Comment by Jummit** [comment]
> Another possibility is to open again Godot itself.

What is the problem with that approach?

**Comment by MaaaxiKing** [comment]
There's no problem but why can't there just be this little possibility?

**Comment by Jummit** [comment]
Rule 2:
> All proposals must be linked to a substantive use-case. In justifying your proposal, it is not enough to say it would be "nice" or "helpful". Use the template to show how Godot is not currently meeting your needs and then explain how your proposal will meet a particular need.

**Comment by MaaaxiKing** [comment]
So you mean nobody cares about issues that don't have a real need?

**Comment by Jummit** [comment]
I leave the interpretation of the rule up to you / the maintainers.

**Comment by Calinou** [comment]
Related to #645.

**Comment by Calinou** [comment]
Closing due to lack of support. You can already achieve this by opening another Godot instance, which will open another project manager without closing the currently open project.

(If you've pinned Godot to your task bar on Windows, hold <kbd>Shift</kbd> and click on the Godot icon on the taskbar to start a new instance, or click it with the middle mouse button.)
