### ISSUE TITLE
Property tooltips sometimes go off screen - Web Editor

### ISSUE THREAD

**Issue by SheepCommander** [godotengine/godot-proposals#9921]
### Describe the project you are working on

A web editor project, on a chromebook with a small screen

### Describe the problem or limitation you are having in your project

Property tooltips in the inspector can sometimes go off the edge of the screen.

[Screen recording 2024-06-04 11.18.51 AM.webm](https://github.com/SheepCommander/gd-SoloVisibility/assets/93790365/add45e8b-086c-40fd-972b-e1e122c8b684)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If there's no space, the tooltip should be kept inside the window.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The main desktop binary already uses this behavior!

![image](https://github.com/godotengine/godot-proposals/assets/66646514/45d9bf0d-6b8a-44cc-9685-214da913445f)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not to my knowledge

### Is there a reason why this should be core and not an add-on in the asset library?

I don't believe EditorPlugin can easily modify tooltip functionality

**Comment by AThousandShips** [comment]
This is a bug, this is for feature proposals, please search for bug reports [here](https://github.com/godotengine/godot/issues) and report if you can't find one already open (or closed)
