### ISSUE TITLE
Add a getter to `EditorInterface` to obtain the editor root node

### ISSUE THREAD

**Issue by peachey2k2** [godotengine/godot-proposals#9929]
### Describe the project you are working on

I'm working on something similar to a video editor. Basically I wanna update the files visible in a list every time the window regains focus. I need to access the root window for that.

### Describe the problem or limitation you are having in your project

It's not really a limitation, I can still do that with `EditorInterface.get_base_control().get_tree().get_root()` but it feels wrong to have getters for pretty much every useful node but not the root window. It's also pointless reference chasing.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Purely convenience, except for the 3 picoseconds it'd take to look up 2 more references.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Instead of:
```gdscript
EditorInterface.get_base_control().get_tree().get_root()
```
it would be something like:
```gdscript
EditorInterface.get_editor_root()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes.

### Is there a reason why this should be core and not an add-on in the asset library?

It's such a small thing that people would just use the old method instead.

**Comment by AThousandShips** [comment]
> Purely convenience, except for the 3 picoseconds it'd take to look up 2 more references.

The only difference there would be in not doing the check in C++ but in GDScript, the root would probably be fetched by the same means, AFAIK the editor doesn't track the root window specifically

**Comment by KoBeWi** [comment]
You can use `get_tree().get_root()` in any node and get the same result.

**Comment by AThousandShips** [comment]
Indeed forgot that there's only ever one tree so this doesn't depend on anything else

**Comment by peachey2k2** [comment]
> You can use `get_tree().get_root()` in any node and get the same result.

Yup, my bad. I should've tried everything before asking.
I had tried to `get_tree()` through a non-node, which was what confused me. Thank you all and sorry for bothering.

**Comment by KoBeWi** [comment]
For non-nodes or nodes outside scene tree you can use `Engine.get_main_loop()` to get SceneTree.
