### ISSUE TITLE
Always uses UTF-8

### ISSUE THREAD

**Issue by feois** [godotengine/godot-proposals#9932]
### Describe the project you are working on

An application that only uses GUI

### Describe the problem or limitation you are having in your project

I am piping the stdout of the Godot "game" to a Rust program. It works fine on Linux but not on Windows because Godot uses UTF-16 on Windows while Rust primarily uses UTF-8 and only has little support for UTF-16 in standard libraries.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an option to always use UTF-8 in project settings

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It is engine-level

**Comment by AThousandShips** [comment]
Where do you mean you'd use UTF-8? In files?

**Comment by feois** [comment]
> Where do you mean you'd use UTF-8? In files?

In my Rust program, Rust uses UTF-8 and has little support for UTF-16

**Comment by AThousandShips** [comment]
I'm not sure what handles the console output specifically if it's a software thing or an OS thing on windows

**Comment by feois** [comment]
> I'm not sure what handles the console output specifically if it's a software thing or an OS thing on windows

[https://stackoverflow.com/q/66072117](Might be an OS thing)

**Comment by AThousandShips** [comment]
The current code does seem to at least try to set the console output to use UTF-8, so either that doesn't work or there's something in the Windows system that prevents it being read by Rust that way, in the latter case there's nothing we can do in the engine but you have to work around it yourself

**Comment by bruvzg** [comment]
It's already changed to use UTF-8 for stdio in 4.3, see https://github.com/godotengine/godot/pull/91147

**Comment by bruvzg** [comment]
And all file i/o is and always was using UTF-8 by default.

**Comment by feois** [comment]
> It's already changed to use UTF-8 for stdio in 4.3, see [godotengine/godot#91147](https://github.com/godotengine/godot/pull/91147)

I see

**Comment by feois** [comment]
I investigated more into the corrupted strings because I was unable to just simply use UTF-16 to decode (I initially thought Godot prints UTF-16 as I could not decode using UTF-8) and turns out Godot prints a mix of UTF-8 and UTF-16. Is this expected and will be fixed in 4.3? An example of this is that Godot prints 0xF3 instead of 0xC3 0xB3 for the character ó (0x00F3 in UTF-16) and 0xEB instead of 0xC3 0xAB for the character ë (0x00EB in UTF-16)

**Comment by bruvzg** [comment]
> Is this expected and will be fixed in 4.3?

It should be fixed by aforementioned PR. Unicode output before it is almost entirely broken and behave differently in different conditions.
