### ISSUE TITLE
Heightmap terrain Godot

### ISSUE THREAD

**Issue by novac07** [godotengine/godot-proposals#9934]
### Describe the project you are working on

Hello. Please add a well-integrated heightmap in the engine, like the shitty Unity Engine, it has a superb heightmap. The heightmap plugins for godot are buggy, some crash and others consume a lot of RAM.

### Describe the problem or limitation you are having in your project

Hello. Please add a well-integrated heightmap in the engine, like the shitty Unity Engine, it has a superb heightmap. The heightmap plugins for godot are buggy, some crash and others consume a lot of RAM.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Hello. Please add a well-integrated heightmap in the engine, like the shitty Unity Engine, it has a superb heightmap. The heightmap plugins for godot are buggy, some crash and others consume a lot of RAM.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Hello. Please add a well-integrated heightmap in the engine, like the shitty Unity Engine, it has a superb heightmap. The heightmap plugins for godot are buggy, some crash and others consume a lot of RAM.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Hello. Please add a well-integrated heightmap in the engine, like the shitty Unity Engine, it has a superb heightmap. The heightmap plugins for godot are buggy, some crash and others consume a lot of RAM.

### Is there a reason why this should be core and not an add-on in the asset library?

Hello. Please add a well-integrated heightmap in the engine, like the shitty Unity Engine, it has a superb heightmap. The heightmap plugins for godot are buggy, some crash and others consume a lot of RAM.

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/6121

In the future please fill in the form properly, if you can't fill in each question separately please open a discussion instead
