### ISSUE TITLE
Add multi-touch capability for BaseButton

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot-proposals#9965]
### Describe the project you are working on

I'm working on a music application for Android in the style of Drum Pads 24, where we play music samples by pressing buttons
![app](https://github.com/godotengine/godot-proposals/assets/130399274/3871eb5e-c03b-45e6-a11a-f861e8027a4b)

### Describe the problem or limitation you are having in your project

I use Button nodes for the keys since my keys are in a GridContainer, but when I test multiple keystrokes on the android, only one of the buttons is pressed, which prevents me from continuing to develop the game.

I have come across a similar discussion on this topic many times, many people need a multi-touch button for Control nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are several options to solve this problem

Add optional multi-touch support for BaseButton, or add a new TouchScreenButton for Control nodes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same as above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Probably... this problem can be solved (right?)

### Is there a reason why this should be core and not an add-on in the asset library?

Judging by internet searches, there are a huge number of questions about this, which means that this process is not simple, and people need an easier implementation of this

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/3976.
