### ISSUE TITLE
Ask for confirmation before closing Godot

### ISSUE THREAD

**Issue by MacdonaldRobinson** [godotengine/godot-proposals#9976]
### Describe the project you are working on

This is not project specific

### Describe the problem or limitation you are having in your project

When I run a project, I usually press CTRL + F4 to close the running project window. I have accidently shut down Godot several times

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

it would be nice for godot to have a "Are you sure?" confirmation dialog instead of just shutting down right away

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

On Closing show a confirmation / cancel dialog box

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am guessing we can create a tool script to add this in

### Is there a reason why this should be core and not an add-on in the asset library?

This is a simple confirmation dialog box on close, so it doesnt make sense for it to be a library

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/6915.
