### ISSUE TITLE
Add alt code input feature

### ISSUE THREAD

**Issue by O-39889** [godotengine/godot-proposals#9981]
### Describe the project you are working on

An incremental game (this is not really project specific, although I work with a lot of text strings like flavor text in it, so those small inconeniences might slowly accumulate over time)

### Describe the problem or limitation you are having in your project

Using "alt codes" for entering special characters does not seem to work in the editor, including code editor, inspector input fields and other input fields in the editor. So, holding down Alt, then entering a valid numerical code on the numpad while Num Lock is active results in no special symbol being inserted. That includes the code editor and the editor input fields; and, since the editor is said to use the Godot UI system itself, it also extends to nodes like LineEdit in games as well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the alt code input functionality to the text editors.
I feel like I probably don't need to describe how it should work since it's base functionality in a lot of regular desktop programs such as text editors and web browsers.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just like in most other text input fields in other programs, when the user holds Alt and types a combination of numbers on the numeric keypad while having Num Lock on and then releases Alt, the required symbol will be entered.

For example, Alt + 0151 corresponds to  — (the em dash symbol)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around by just opening any text editor or any program with a text input field (such as a web browser), entering a combination in here and copying the resulting symbol.

### Is there a reason why this should be core and not an add-on in the asset library?

I feel like it doesn't make sense for this feature to be a separate add-on or a library, considering how it's usually just supported out-of-the-box, so might either just add it as core functionality or not (and reject this proposal in the latter case).

**Comment by Calinou** [comment]
Alt codes are already implemented in 4.0 and later: https://github.com/godotengine/godot/pull/55441

**Comment by O-39889** [comment]
I'm using Godot 4.2.2, which is probably weird since it doesn't seem to work in here. Just to clarify, I'm using it exactly like in other Windows programs, as I described in my proposal, and it doesn't seem to work. Maybe I'm somehow using it the wrong way, not how it works in Godot, idk

**Comment by Rydian** [comment]
I'm using `v4.3.beta1.official [a4f2ea91a]` and it's not working in the code editor for me either.  Neither is it working in the LineEdit test section of a theme resource, etc.  ALT+0153 = ™ but it's not putting anything in that I can tell.

Pasting the symbol does work in both areas, so it's probably not a font/display issue.

**Comment by kitbdev** [comment]
Godot has [Unicode input](https://en.wikipedia.org/wiki/Unicode_input) (from https://github.com/godotengine/godot/pull/55441), and it works slightly differently than [Alt codes](https://en.wikipedia.org/wiki/Alt_code).
Hold Alt, then type plus `+` on the numeric keypad, then type the unicode character value, and then release Alt.
For instance, U+2014 is em dash — and U+2122 is trademark ™.

**Comment by O-39889** [comment]
Well, okay, I see, I checked that and it works that way indeed. Maybe it's less convenient for regular Windows users though, I guess
